### ISSUE TITLE
Support :option: reference defined in a program scope

### ISSUE THREAD

**Issue by marxin** [sphinx-doc/sphinx#10002]
@jakobandersen
I think it's impossible doing such a reference for:

```rst
.. program:: make

.. option:: --verbose

Use verbose mode.

.. program:: None

Use :option:`--verbose` mode.
```

I would like to use something like:
```rst
:option:`make.--verbose`
```

if I'm out of the `make` program scope.
Thank you.

**Comment by jakobandersen** [comment]
You should be able to do
```rst
:option:`make --verbose`
```
or if you don't wan't the prefix, then use a title
```rst
:option:`--verbose <make --verbose>`
```

**Comment by marxin** [comment]
Oh, thanks, I didn't read the documentation enough. Note, I would explain more the second reference format for which I created a PR.

**Comment by tk0miya** [comment]
Hi marxin,

Why do you add a mention to a specific maintainer on each issue? I think other maintainers (including me) are also able to answer your question.

**Comment by marxin** [comment]
> Why do you add a mention to a specific maintainer on each issue? I think other maintainers (including me) are also able to answer your question.

Well, I had some email conversion about option directives with Jakob so that's why I add him to bugs that are related to that. Similarly for Latex issues. But yes, I won't do that in the future.

Note you're very good at answering my questions ;) Thanks for it.

**Comment by tk0miya** [comment]
Okay, I understand. I feel your report surely improves Sphinx. So I'd like to say to thank you!

**Comment by marxin** [comment]
> I feel your report surely improves Sphinx.

Thanks, pleasure.
