### ISSUE TITLE
HtmlHelp: charset=cp1252 for language='en' does not work on Chinese OS

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1002]
When generating htmlhelp with language='en' the generated html-pages have charset=cp1252 in the meta tag. My document have Swedish characters 'åäö' and they are not displayed correctly on Chinese windows os. 

To make it work I reverted the change
https://github.com/sphinx-doc/sphinx/commit/0c7d972c81cb92088eff9bf7357639ef3908872d

so I could use the html_output_encoding and set it to 'utf-8' ('iso-8859-1' works also).  

Ulf Larsson

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1002
- Originally reported by: Anonymous
- Originally created at: 2012-09-05T15:16:26.548

**Comment by AA-Turner** [comment]
Please report against `sphinxcontrib-htmlhelp`.

A
