### ISSUE TITLE
AttributeError: 'ASTTrailingTypeSpecFundamental' object has no attribute 'names'

### ISSUE THREAD

**Issue by cliffburdick** [sphinx-doc/sphinx#10023]
### Describe the bug

I tried to switch from the rdt theme to book, and when doing so I get this error:

```
updating environment: [extensions changed ('sphinx_book_theme')] 24 added, 13 changed, 0 removed
reading sources... [ 29%] api/random
Exception occurred:
  File "/usr/local/lib/python3.8/dist-packages/sphinx/domains/cpp.py", line 1854, in _stringify
    return ' '.join(self.names)
AttributeError: 'ASTTrailingTypeSpecFundamental' object has no attribute 'names'
The full traceback has been saved in /tmp/sphinx-err-6dglior6.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
```

Full log is attached. Note, I don't know if this is an issue in Sphinx or the Book theme, but the error was thrown in a sphinx file. 

When I run ``make`` again without cleaning I get this: 

```
/usr/local/lib/python3.8/dist-packages/docutils/writers/__init__.py:78: FutureWarning: The configuration setting "embed_images" will be removed in Docutils 1.2. Use "image_loading: link".
  self.translate()

Theme error:
An error happened in rendering the page api/class.
Reason: TemplateNotFound('sidebar-logo.html')
```

[sphinx-err-6dglior6.log](https://github.com/sphinx-doc/sphinx/files/7778369/sphinx-err-6dglior6.log)

### How to Reproduce

```
$ git clone https://github.com/NVIDIA/MatX.git
$ cd MatX
$ (with cmake, doxygen/breathe/sphinx/book installed"
$ Modify conf.py.in to have ``html_theme = "sphinx_book_theme"``
$ cmake .. -DBUILD_DOCS=ON
$ make
```

### Expected behavior

Builds completely

### Your project

 https://github.com/NVIDIA/MatX

### OS

Ubuntu 20.04

### Python version

3.8

### Sphinx version

4.3.2

### Sphinx extensions

extensions = ['breathe', 'sphinx.ext.autodoc', 'sphinx_rtd_theme', 'sphinx.ext.mathjax', 'sphinx_book_theme']

### Additional context

Breathe version was updated to 4.31.0

**Comment by jakobandersen** [comment]
Thanks for reporting. Can you try doing a clean build?
I think I forgot to bump the env-version for 4.3.2, so it can load an old pickled doctree.

**Comment by cliffburdick** [comment]
Hi @jakobandersen , thanks for responding. I did a clean build and got:

```
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [  4%] api/class
Theme error:
An error happened in rendering the page api/class.
Reason: TemplateNotFound('sidebar-logo.html')
```

This might just be a problem with me configuring the plugin. I didn't see any of the parameters were required, but I'll try a few of the ones they suggest.

**Comment by cliffburdick** [comment]
This was user error. Unlike rdt I didn't notice book theme isn't supposed to be listed in the extensions. Removing that fixed the problem. Thanks!
