### ISSUE TITLE
htmlhelp builder: the target in hhc is resolved to the root_doc rather than the doc root directory

### ISSUE THREAD

**Issue by char101** [sphinx-doc/sphinx#10033]
### Describe the bug

Matplotlib has its `root_doc` in `users/index.rst`. When using the htmlhelp builder, the link in the generated contents points relative to `users/` (for example `tutorial/` instead of `users/tutorial/`) causing the link target to be not found.

### How to Reproduce

```
$ git clone https://github.com/matplotlib/matplotlib
$ cd matplotlib
$ pip install -r requirements/doc/doc-requirements.txt
$ cd docs
$ PYTHONPATH=. sphinx-build -b htmlhelp -v . build
```

### Expected behavior

Link inside hhc should be based to the documentation root directory rather than to the directory containing `root_doc`.

### Your project

https://github.com/matplotlib/matplotlib

### OS

Linux

### Python version

3.10

### Sphinx version

4.3.2

**Comment by AA-Turner** [comment]
Please report against `sphinxcontrib-htmlhelp`.

A
