### ISSUE TITLE
Linking parameter descriptions from file in autodoc docstrings

### ISSUE THREAD

**Issue by MahnoorAsghar** [sphinx-doc/sphinx#10059]
**Is your feature request related to a problem? Please describe.**
I am using the Sphinx autodoc extension to document Ironic's REST API. Ironic was already using Sphinx to generate its documentation, and autodoc satisfies the need to new need to use docstrings. 
The API method parameters are repeated across many methods, and many modules. Right For example, a node object is a parameter in many API calls, and its description should be the same in all docstrings. Right now, it is being repeated in many files and modules.

**Describe the solution you'd like**
The parameter descriptions should be placed in one file (e.g. parameters.yaml file [here](https://opendev.org/openstack/ironic/src/branch/master/api-ref/source/parameters.yaml)); and the descriptions from that file should be linked in all the docstrings.
For example, documentation should be generated from the following docstring, and the parameter descriptions should be read from a file called 'parameters.yaml':
```
def get_all(self, node=None, resource_class=None, state=None, marker=None,
                limit=None, sort_key='id', sort_dir='asc', fields=None,
                owner=None):
Lists all Allocations.

Request
-------
.. rest_parameters:: parameters.yaml
   - node: r_allocation_node
   - resource_class: r_resource_class
   - state: r_allocation_state
   - owner: owner
   - fields: fields
   - limit: limit
   - marker: marker
   - sort_dir: sort_dir
   - sort_key: sort_key

Response Parameters
-------------------
.. rest_parameters:: parameters.yaml
   - uuid: uuid
   - candidate_nodes: candidate_nodes
   - last_error: allocation_last_error
   - name: allocation_name
   - node_uuid: allocation_node
   - resource_class: allocation_resource_class
   - state: allocation_state
   - traits: allocation_traits
   - owner: owner
   - extra: extra
   - created_at: created_at
   - updated_at: updated_at
   - links: links
"""
```
Autodoc should replace the placeholders (e.g. r_allocation_node) with the appropriate description from the parameters file.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by tk0miya** [comment]
As I commented in the forum, it would be better to start this as a 3rd party extension. I'm not sure this is a commonly used feature.

**Comment by MahnoorAsghar** [comment]
Thank you for the input, @tk0miya!
I have started work on my own extension for this use case :)
