### ISSUE TITLE
:linenos: works badly with {{{pre {white-space:pre-wrap;}}} css style

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1007]
See the attached screenshot.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1007
- Originally reported by: Boris Kheyfets
- Originally created at: 2012-09-15T13:44:26.869

**Comment by usaturn** [comment]
![test restest 0 1 documentation - firefox_029](https://cloud.githubusercontent.com/assets/1503215/21285514/142cf954-c47e-11e6-90d8-0e9bf4ab58ce.png)

**Comment by tk0miya** [comment]
Since v4.0, the line-numbers are rendered as inline by default (see #7942). So this issue will be resolved after upgrading. So I'm closing this now.
