### ISSUE TITLE
Plus Signs Missing

### ISSUE THREAD

**Issue by sprengerst** [sphinx-doc/sphinx#10082]
### Describe the bug

Hi,

we upgraded our Sphinx version and the plus signs seem to have disappeared. Is this "work by design"?

Before:
![image](https://user-images.githubusercontent.com/6854862/148778406-d0d72659-d09f-41d6-b4cd-62f544edfac7.png)

After:
![image](https://user-images.githubusercontent.com/6854862/148778437-5f8c2db4-0518-4268-9a59-6ce24a2b989d.png)

I will add further versioning details when I know if this is a bug.

Best,
Stefan

### How to Reproduce

```
$ git clone https://github.com/.../some_project
$ cd some_project
$ pip install -r requirements.txt
$ cd docs
$ make html SPHINXOPTS="-D language=de"
$ # open _build/html/index and see bla bla
```

### Your project

?

### OS

Windows

### Python version

?

### Sphinx version

?

**Comment by tk0miya** [comment]
Please let me know what HTML theme do you use?

**Comment by sprengerst** [comment]
hi @tk0miya  sphinx-rtd

**Comment by jdillard** [comment]
I suggest opening an issue in https://github.com/readthedocs/sphinx_rtd_theme

**Comment by AA-Turner** [comment]
Thanks Jared, closing as not a Sphinx issue.
