### ISSUE TITLE
Filter for csv tables

### ISSUE THREAD

**Issue by lodgmar** [sphinx-doc/sphinx#10086]
Imagine you have a CSV containing a list of error codes for your project. A simple example of this would be:

```csv
method, code, value, description
get(), ERR_NOT_FOUND, -1, The URI doesn't point to an existing file.
get(), ERR_TOO_BIG, -2, The file size is too big to download.
put(), ERR_PATH_NOT_FOUND, -3, The upload path does not exist.
put(), ERR_TOO_BIG, -4, The file size is too big to upload.
```

Now, imagine you are documenting those methods, and you want to include their own error codes, so method `get()` shows the first two rows, and method `put()` shows the last two rows. Besides, you want to show the whole listing in another part of your documentation, i.e. a page about error codes of your whole project.

All of this can be done using a single CSV file, but it would need some new features in `csv-table` directive, adding a few arguments:

:columns:
----

A list of columns to show, so you can hide useless columns.

Example:

```
  :columns: 2 3 4
```

:filter:
----

A list of string expressions to filter rows, using "%1" as column indicator, and valid operators are "==", "<", "<=", ">", ">=", "!=". The list of expression are joined with AND operator.

If you specify several `:filter:` arguments, they'll be joined with OR operator

Examples:

```
  :filter: "%1==get()"
  # Resultset = rows 1 and 2

  :filter: "%1==get()" "%3>-1"
  # Resultset = row 2

  :filter: "%1==get()"
  :filter: "%3==-4"
  # Resultset = rows 1, 2 and 4
```

:types:
----

A list of strings indicating the column types, so comparison operators in `:filter:` arguments can work properly. The only possible values are "string" and "num". 

Example:

```
  :types: string string num string
```

**Comment by tk0miya** [comment]
Could you post a proposal to the doctuils project, please? The `csv-table` directive is a part of common reStructuredText. So it should not be extended by Sphinx.

IMO, documentation is not a programming. So -1 for adding such a programmable feature to "mark up" syntax. It would be better to add a custom directive instead.

**Comment by lodgmar** [comment]
Yes, you're completely right.
