### ISSUE TITLE
Multiple builder support in sphinx-build

### ISSUE THREAD

**Issue by kasium** [sphinx-doc/sphinx#10096]
**Is your feature request related to a problem? Please describe.**
The setuptools integration allows the definition of multiple builders, e.g. `builder = html,linkcheck,doctest`. However, the same is not possible over `sphinx-builder`. If I use `-b` with a comma/space separated list, the command fails. Specifying `-b` multiple times also doesn't work.

**Describe the solution you'd like**
Allow `-b` to get a comma/space separated list or to be specified multiple times

**Describe alternatives you've considered**
Running the command multiple times, which is not very nice...

**Comment by tk0miya** [comment]
How about using `make html linkcheck doctest` instead? I think following KISS principle is better.

**Comment by kasium** [comment]
Valid point. However, if I just want to use pure CLI w/o make or setuptools, I need to have multiple calls. Could that be added?

**Comment by astrojuanlu** [comment]
There have been some attempts at creating "a new CLI" (I took some notes months ago [here](https://gist.github.com/astrojuanlu/f1815093892f6c7fc1124e0577452eed/)), perhaps it could be included in those plans, rather than modifying the current CLI?

**Comment by kasium** [comment]
Fine for me 😄

**Comment by AA-Turner** [comment]
Closing in favour of #5618.

A
