### ISSUE TITLE
Missing commit in master branch

### ISSUE THREAD

**Issue by marxin** [sphinx-doc/sphinx#10102]
### Describe the bug

I noticed that `4.x` is periodically merged to `master`, but I noticed that 27db7f6307a928469608bf84385a05588e5e2aa9 is missing at `master`. Can we please fix it?

### How to Reproduce

Take a look at diff for `sphinx/themes/basic/static/doctools.js`.

**Comment by tk0miya** [comment]
Done.

**Comment by marxin** [comment]
Thanks.
