### ISSUE TITLE
confoverrides are not respected for theme configuration

### ISSUE THREAD

**Issue by chrisjsewell** [sphinx-doc/sphinx#10120]
### Describe the bug

Basically, there needs to be a slight amendment to https://github.com/sphinx-doc/sphinx/pull/10079

cc @pradyunsg 

### How to Reproduce

I come across this when running tests with sphinx fixtures

```python
pytest_plugins = 'sphinx.testing.fixtures'

@pytest.mark.sphinx('html', confoverrides={'pygments_dark_style': 'other'})
def test_html4_output(app, status, warning):
   # but pygments_dark_style wil not be set
    app.build()
```

### Your project

furo

### OS

any

### Python version

any

### Sphinx version

4.3.2

**Comment by pradyunsg** [comment]
You need Sphinx 4.4.0. Can you reproduce with that?

**Comment by chrisjsewell** [comment]
> You need Sphinx 4.4.0. Can you reproduce with that?

Yep: it picks up config in the `conf.py` (what the PR fixed) but not `confoverrides` (what the PR did not fix)

**Comment by AA-Turner** [comment]
See #10079.

**Comment by AA-Turner** [comment]
Overrides (``--define``, ``-D``, etc) should now work properly following #11855.

A
