### ISSUE TITLE
Sphinx build should be able to generate docs from directories that contain python modules.

### ISSUE THREAD

**Issue by rgbailey** [sphinx-doc/sphinx#10142]
**Is your feature request related to a problem? Please describe.**
Sphinx-build fails whenever I try to generate docs from python directories i.e folders without the `__init__.py` file.

**Describe the solution you'd like**
It would be nice if the build command generates docs from directories just like it does with packages.

**Describe alternatives you've considered**
A sphinx-build option that allows it to treat directories like packages.

**Additional context**
`Extension error (autoapi.extension):
Handler <function run_autoapi at 0x7fdab9390820> for event 'builder-inited' threw an exception (exception: Relative import with too many levels (2) for module 'widgets')`

**Comment by pradyunsg** [comment]
This looks like a feature request for https://pypi.org/project/sphinx-autoapi/ -- that is maintained by a separate group of individuals.

Please file an issue with https://github.com/readthedocs/sphinx-autoapi instead.

**Comment by rgbailey** [comment]
Okay, thanks for taking a look. I will make the post over there.
