### ISSUE TITLE
Make autodoc abbreviate long dictionaries

### ISSUE THREAD

**Issue by not-my-profile** [sphinx-doc/sphinx#10146]
Examples in the wild:

| [`babel.core.Locale.negotiate`](https://babel.pocoo.org/en/latest/api/core.html#babel.core.Locale.negotiate) | [`searx.engines.engine_shortcuts`](https://docs.searxng.org/src/searx.engines.html#searx.engines.engine_shortcuts)
|--|--|
|![image](https://user-images.githubusercontent.com/73739153/151689678-166605e4-2629-4734-a84d-c345fcfbd45c.png) | ![image](https://user-images.githubusercontent.com/73739153/151689697-c63764e9-1aa8-421c-9da1-aa7532969b42.png)

I think for long dictionaries it would be better if they were automatically abbreviated, or there at least should be an option to do so.

**Comment by tk0miya** [comment]
How about using `autodoc_preserve_defaults`? If you're using a constant for the default value, the signature will become looking better.
https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_preserve_defaults

**Comment by not-my-profile** [comment]
Ah I think this would help only with `babel.core.Locale.negotiate` but not with `searx.engines.engine_shortcuts`, which is a documented variable?

**Comment by tk0miya** [comment]
To suppress the value of variables and attributes, please use `:no-value:` option to the auto* directives.

**Comment by not-my-profile** [comment]
But `:no-value:` cannot be used with `automodule` can it?

**Comment by tk0miya** [comment]
OMG, it's not unexpected behavior. I'll fix it. The `:no-value:` option should be passed to both `automodule` directive and `autodoc_default_options`.
