### ISSUE TITLE
Docker image sphinxdoc/sphinx to support amd and arm

### ISSUE THREAD

**Issue by denisa** [sphinx-doc/sphinx#10159]
**Is your feature request related to a problem? Please describe.**
running the sphinxdoc/sphinx image on an ARM architecture (think: apple’s M1) is slow; docker itself warns
```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```

**Describe the solution you'd like**
A single Docker image can support multiple architecture, and most open-source projects now provide such images.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by tk0miya** [comment]
Could you send a PR please?

**Comment by denisa** [comment]
will do!
