### ISSUE TITLE
Characters for section headings are not displaying properly in basics.html 

### ISSUE THREAD

**Issue by noahsprent** [sphinx-doc/sphinx#10154]
### Describe the bug

What was I trying to do?
I wanted to know how to represent different levels of headings. On the basics page, [there is a section](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#sections) about which characters Python's style guide recommends for representing different levels of headings in .rst.

What did I expect to happen:
In the [.rst file preview on GitHub](https://github.com/sphinx-doc/sphinx/blob/master/doc/usage/restructuredtext/basics.rst#sections) and the [Python style guide page](https://devguide.python.org/documenting/#sections) the characters that it is recommended be used for these levels appear in a box that makes it clear the following comma is not to be included.

What happened:
In the page in the sphinx docs the characters are not surrounded by a box (see screenshot). This might lead people (me) to (perhaps stupidly) assume that the comma is part of the recommendation. e.g. the headings should look like:

```
Subheading
-,-,-,-,-,-,-,-,-,
```

Rather than:
```
Subheading
----------------
```

### How to Reproduce

Visit https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#sections

### Your project

https://www.sphinx-doc.org/

### Screenshots

![Screenshot 2022-02-01 09 05 33](https://user-images.githubusercontent.com/39567418/151941817-e5c0fdec-eed5-41d3-8eb5-940cc639181d.png)

### OS

Chrome OS Version 98.0.4758.67

### Python version

Not relevant

### Sphinx version

Not relevant

**Comment by jeanas** [comment]
Not having a box around inline code is part of the general theme; I'm not sure one would want to change it just for this. I'm a random lurker, not a maintainer, but here is my advice: how about submitting a PR yourself to fix the issue? That will be just as fast as reporting the problem. For example, you could include the characters in quotes (e.g., `"``=``"` in the reST source) so that they are clearly separated.

**Comment by noahsprent** [comment]
Thanks for the information on the theme, I didn't realise that was the case and thought it might be a more complex issue. I'm happy to submit a PR as it's quite a simple issue, but as I am not involved in the project at all have no idea whether there would be preferences from the core team about the way in which to resolve it. As one of the characters is themselves a quote it might be confusing to surround the characters in quotes. I think the easiest might be to simply remove the commas.

**Comment by jeanas** [comment]
Smartquotes are activated in Sphinx's documentation, so it will be a straight quote surrounded by curly quotes. But the choice is yours -- [any bikeshed color will do](bikeshed.com) (i.e., I don't think there are strong reasons to prefer one way or the other).
