### ISSUE TITLE
 emojis not rendered properly on PDF output

### ISSUE THREAD

**Issue by tomkralidis** [sphinx-doc/sphinx#10171]
### Describe the bug

(originally reported at https://github.com/readthedocs/readthedocs.org/issues/8841, moving here)

## Details

(via https://github.com/geopython/pygeoapi/issues/844 cc @maaattes)

Emojis used in HTML documentation do not render in the PDF so some parts lose their information.

### How to Reproduce

```bash
$ git clone https://github.com/geopython/pygeoapi.git
$ cd pygeoapi
$ pip install sphinx sphinx_rtd_theme
$ cd docs
$ make latexpdf
<snip>
! Package inputenc Error: Unicode char ✅ (U+2705)
(inputenc)                not set up for use with LaTeX.

See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.1626 \end{tabulary}
                     

! Package inputenc Error: Unicode char ❌ (U+274C)
(inputenc)                not set up for use with LaTeX.

See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.1626 \end{tabulary}                                   
```

### Expected behavior

Emoji's should render as per the HTML output:

![image](https://user-images.githubusercontent.com/910430/150971233-a94097ce-3ede-4c30-9f07-42bba0ac57d0.png)

### Your project

https://github.com/geopython/pygeoapi

### Screenshots

![image](https://user-images.githubusercontent.com/910430/150972115-3b630f46-07cb-462a-98fe-3161e0099167.png)

Also see Read the Docs PDF output: https://docs.pygeoapi.io/_/downloads/en/latest/pdf/ (see page 39 - screenshots also below).

### OS

Mac

### Python version

3.x

### Sphinx version

4.4.0

### Sphinx extensions

sphinx.ext.autodoc, sphinx.ext.todo, sphinx.ext.coverage, sphinx.ext.ifconfig, sphinx.ext.viewcode, sphinx.ext.doctest, sphinx.ext.githubpages, sphinx.ext.intersphinx'

### Extra tools

latexmk, texlive-latex-extra

### Additional context

Note this issue was originally detected on Read the Docs PDF output.

**Comment by tk0miya** [comment]
Please configure `latex_engine` to `'xelatex'` or `'lualatex'`.

On my local, these emojis are rendered well:
```
* check mark: ✅
* cross mark: ❌
```

<img width="185" alt="スクリーンショット 2022-02-12 2 49 07" src="https://user-images.githubusercontent.com/748828/153642946-d2a02c09-5a95-4895-a075-27be977cc909.png">

Note: To render show more better like HTML, you need to set up fonts for LaTeX. But I can't advice it to you because I'm not an expert of LaTeX...

**Comment by tomkralidis** [comment]
Thanks @tk0miya.  Using `xelatex` renders as follows:

![image](https://user-images.githubusercontent.com/910430/153648208-e24f5cc8-1d2c-4e3c-8cfb-eeb13309239f.png)
