### ISSUE TITLE
loading intersphinx inventory error

### ISSUE THREAD

**Issue by be-wise-be-kind** [sphinx-doc/sphinx#10173]
### Describe the bug

First, great tool -- absolutely love it and depend on it. 

As of today, executing "make html" gives the following error; The last known good run was last Wednesday. 

loading pickled environment... done
loading intersphinx inventory from https://docs.scipy.org/doc/numpy/objects.inv...
loading intersphinx inventory from https://docs.scipy.org/doc/scipy/reference/objects.inv...
WARNING: failed to reach any of the inventories with the following issues:
intersphinx inventory 'https://docs.scipy.org/doc/numpy/objects.inv' not readable due to ValueError: unknown or unsupported inventory version: ValueError('invalid inventory header: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">')
intersphinx inventory has moved: https://docs.scipy.org/doc/scipy/reference/objects.inv -> https://docs.scipy.org/doc/scipy-1.8.0/html-scipyorg/reference/
WARNING: failed to reach any of the inventories with the following issues:
intersphinx inventory 'https://docs.scipy.org/doc/scipy/reference/objects.inv' not readable due to ValueError: unknown or unsupported inventory version: ValueError('invalid inventory header: ')
building [mo]: targets for 0 po files that are out of date

### How to Reproduce

A simple "make html" on a project that previously built docs without error now causes the error. 

### Your project

I'm unable to encapsulate this into something meaningpul

### OS

Linux

### Python version

3.8

### Sphinx version

4.4.0

### Sphinx extensions

sphinx-rtd-theme==0.5.2     # (md to rst) 3rd-party sphinx extension for translating .md to .rst files     m2r2==0.2.7     # adds a button to copy documentation code blocks to clipboard     sphinx-copybutton==0.3.1

**Comment by astrojuanlu** [comment]
This is a SciPy issue, the URLs are changing. See https://github.com/scipy/docs.scipy.org/issues/61

**Comment by be-wise-be-kind** [comment]
The issue seems to have been resolved now -- thanks for pointing to the scipy issue and helping me save face with my organization.
