### ISSUE TITLE
Provide documentation for stable version

### ISSUE THREAD

**Issue by not-my-profile** [sphinx-doc/sphinx#10174]
Currently the documentation is only generated for the master branch:

https://readthedocs.org/projects/sphinx/

I would expect the documentation for the latest stable version to be available at:

https://www.sphinx-doc.org/en/stable/

but that link just redirects to /master/.

**Comment by tk0miya** [comment]
Could you let me know about your concern or trouble? We thought no (or very less) advantage if we'll provide the stable version.

**Comment by not-my-profile** [comment]
Ah, right I didn't consider that Sphinx versions are released so frequently. Fair enough, closing this.
