### ISSUE TITLE
Autosummary breaks on literal block notation

### ISSUE THREAD

**Issue by MagnusOstertag** [sphinx-doc/sphinx#10180]
### Describe the bug

I noticed this bug when developing [the docs in pyMOR](https://github.com/pymor/pymor/pull/1563). In the `index.rst`  in `pymor.algorithms/timestepping` I get three times `WARNING: Literal block expected; none found.`. The error orginates in the docstring of the `solve` method.

The problem is that autosummary tries to pick the first line of the docstring for the table and breaks if the first line contains a literal block notation. This should have be resolved since sphinx 1.7.6 as [the same issue](https://github.com/sphinx-doc/sphinx/issues/5146) was closed then. But I can reliably break autosummary in pyMOR this way (with the docstrings for classes and methods) and fix the issue if I change the docstring to not including a literal block.

### How to Reproduce

Get pyMOR:
```
$ git clone https://github.com/pymor/pymor pymor_source
$ cd pymor_source
$ python3 -m virtualenv venv
$ source venv/bin/activate
$ pip install -e '.[full]'
```
Get the version of the pull request where the problem occurred and run sphinx:
```
$ git fetch origin pull/1563/head:method-overview
$ git checkout method-overview
$ git revert --no-commit 3a4a17f13f206cac75d6fee30f76d2a0a57de46d..HEAD
$ sphinx-build -E docs/source docs/sphinx/
```

I would guess the examples from [the old issue](https://github.com/sphinx-doc/sphinx/issues/5146) also fail.

### Your project

[The docs in pyMOR](https://github.com/pymor/pymor/pull/1563).

### OS

Linux

### Python version

3.8, (3.7, 3.9)

### Sphinx version

4.4.0

### Sphinx extensions

sphinx.ext.autosummary

**Comment by tk0miya** [comment]
I reproduce the errors:
```
/pymor/docs/source/autoapi/pymor/algorithms/timestepping/index.rst:71:<autosummary>:2: WARNING: Literal block expected; none found.
/pymor/docs/source/autoapi/pymor/algorithms/timestepping/index.rst:134:<autosummary>:2: WARNING: Literal block expected; none found.
/pymor/docs/source/autoapi/pymor/algorithms/timestepping/index.rst:191:<autosummary>:2: WARNING: Literal block expected; none found.
```

These warning messages say the warning was raised from `autoapisummary` directive. This is not a part of autosummary. So I'm not sure why it emits warnings. Could you report this to the author of the extension, please?

**Comment by tk0miya** [comment]
Note: Dockerfile to reproduce this:

```
FROM python:3.9-slim

RUN apt update; apt install -y build-essential curl git unzip vim
RUN git clone https://github.com/pymor/pymor
WORKDIR /pymor
RUN pip install -e '.[full]'
RUN git fetch origin pull/1563/head:method-overview
RUN git checkout method-overview
RUN git revert --no-commit 3a4a17f13f206cac75d6fee30f76d2a0a57de46d..HEAD
RUN apt install -y python3-pyqt5
RUN sphinx-build -E docs/source docs/sphinx/
```

**Comment by MagnusOstertag** [comment]
Thanks and sorry for the confusion.
