### ISSUE TITLE
There is no way to enforce MathJax when maths only appear in TOC trees.

### ISSUE THREAD

**Issue by kwankyu** [sphinx-doc/sphinx#10192]
This is almost a bug report.

Sphinx behaves such that if there is no math in an rst document, MathJax javascript is not included in the generated html file. This is to save loading time. But it frequently happens that maths only appear in the TOC trees of the rst document, in which case maths are not rendered properly because MathJax is not activated. For example, see

https://doc.sagemath.org/html/en/reference/schemes/index.html

It seems that there is no mechanism to enforce MathJax in this situation. It would be nice if we can enable this enforcement through the conf file.

**Comment by Daltz333** [comment]
👎 to this. Math requires special symbols that should not be part of any title. It is not compatible with screen readers, it is not accessible, and it is not good practice.

**Comment by kwankyu** [comment]
I agree that including no maths in titles is a good practice. But it is not a rule.  As our project is math software, it is only natural to have math symbols  in titles here and there. 

Sphinx does allow maths in titles. Then breaking maths in TOC trees is close to a bug.

**Comment by jhpalmieri** [comment]
The _Annals of Mathematics_, one of the premier mathematics journals in the world, allows mathematical symbols in their titles — see https://annals.math.princeton.edu/2021/194-3, for instance. It is part of the culture in research mathematics to use math(s) in titles.

**Comment by jakobandersen** [comment]
This definitely sounds like a bug to me, otherwise math should be rejected in the originating document. I don't Sphinx should decide what is good or bad style, and as pointed out, having math in titles is very common in some areas.

The problem with screen readers and accessibility in general is quite important, so if possible something should be done. But I guess this is a problem for _any_ instance of math, even outside titles? A separate issue should probably be opened on the improvement of accessibility, and from https://docs.mathjax.org/en/latest/basic/accessibility.html it almost looks like we can "just" change the MathJax settings.

**Comment by kwankyu** [comment]
This code in `sphinx/ext/mathjax.py` seems responsible enabling mathjax when any equation is found in a document.

```
def install_mathjax(app: Sphinx, env: BuildEnvironment) -> None:
    if app.builder.format != 'html' or app.builder.math_renderer_name != 'mathjax':  # type: ignore  # NOQA
        return
    if not app.config.mathjax_path:
        raise ExtensionError('mathjax_path config value must be set for the '
                             'mathjax extension to work')

    builder = cast(StandaloneHTMLBuilder, app.builder)
    domain = cast(MathDomain, env.get_domain('math'))
    if domain.has_equations():
        # Enable mathjax only if equations exists. <-------------------------------
        options = {'async': 'async'}
        if app.config.mathjax_options:
            options.update(app.config.mathjax_options)
        builder.add_js_file(app.config.mathjax_path, **options)

        if app.config.mathjax_config:
            body = "MathJax.Hub.Config(%s)" % json.dumps(app.config.mathjax_config)
            builder.add_js_file(None, type="text/x-mathjax-config", body=body) 
```

However, when equations are included indirectly, like TOC trees, the method `has_equations()` seems to return `False`.

**Comment by kwankyu** [comment]
As there's no progress on the issue here, we overcame the problem just by inserting dummy math

    .. math::
       :nowrap:

with apparently no side effect. Anyway, thanks for your attention.
