### ISSUE TITLE
automodule rename

### ISSUE THREAD

**Issue by tdegeus** [sphinx-doc/sphinx#10199]
I have a set of functions written in C++ that I compile in a module `_foo`.
My python module simply imports all functions from it. I.e. `foo/__init__.py` reads
```python
from _foo import *
```

To document these functions I have to do `.. automodule:: foo._foo`, or specifically:
```rst
.. automodule:: foo._foo
    :members:
    :special-members:
    :undoc-members:
    :show-inheritance:
    :exclude-members: __weakref__, __doc__, __module__, __dict__, __members__, __getstate__, __setstate__
```
which results in a bit ugly and misleading documentation that seems to suggest that the user has to use functions like `foo._foo.myfunc`. How can I change the documentation such that instead it shows what the user *can* do, i.e. `foo.myfunc`?

**Comment by jbms** [comment]
You can fix this inside your extension code itself, which also has the advantage of fixing what is displayed by repr, etc.

If you are using pybind11, see for example:

https://github.com/google/tensorstore/blob/94be4f2e8715511bb60fc0a0eaf07335881673b3/python/tensorstore/tensorstore.cc#L75

**Comment by tdegeus** [comment]
That is amazing @jbms , thanks a lot!
