### ISSUE TITLE
Per annotation documentation support

### ISSUE THREAD

**Issue by Gobot1234** [sphinx-doc/sphinx#10206]
**Is your feature request related to a problem? Please describe.**
I'd like a way to do per variable documentation for annotations e.g. 
```py
class Review:
    """Represents a review for a game."""

    id: int
    """The ID of the review."""
```
This is especially important for me on dataclasses where the duplication and lack of an easy way to tell what's documented is particularly annoying.

Currently this is how this is rendered:
![image](https://user-images.githubusercontent.com/50501825/154742870-29bd69f4-787e-4e2f-861f-109a0122a63e.png)

**Describe the solution you'd like**
For the above to work the same as if I gave `id` a default value.

**Comment by tk0miya** [comment]
Autodoc extension already supports a docstring for attributes. How do you create your document? How mark it up?

**Comment by Gobot1234** [comment]
You're correct, I forgot the `:members:` directive sorry. I've definitely broken something on my end because the docstrings don't show up but I've confirmed this does work on a new project.
