### ISSUE TITLE
Search should use text fragment anchor

### ISSUE THREAD

**Issue by Timmmm** [sphinx-doc/sphinx#10201]
Search currently jumps to the page and appends `?highlight=search+terms` to the URL. E.g.

https://www.sphinx-doc.org/en/master/usage/builders/index.html?highlight=pseudoxml

But that doesn't jump to the result in the page unfortunately - you still have to manually scroll to it.

The web now has a feature for that - [Text Fragments](https://web.dev/text-fragments/) so you can do:

https://www.sphinx-doc.org/en/master/usage/builders/index.html?highlight=pseudoxml#:~:text=pseudoxml

(Note: the `higlight=` parameter doesn't seem to work on the main Sphinx page, but it's supposed to highlight the occurances.)

This is pretty easy to do I think.

**Comment by Timmmm** [comment]
Something like [this](https://github.com/Timmmm/sphinx/commit/e715ac4a2b499da437fda270c730266739c92fb0). I have done zero testing of that diff - I literally just used the Github editor. But it should give a rough idea. I don't have a Sphinx setup to test it with unfortunately.

**Comment by not-my-profile** [comment]
>The web now has a feature for that

Text fragments [are not supported in Firefox or Safari](https://caniuse.com/url-scroll-to-text-fragment). Just because Google implements something in their own browser does not mean that the web has a new feature.

**Comment by Timmmm** [comment]
Interesting, though they're just anchors so it wouldn't change any behaviour on Firefox or Safari.

There is also [an extension to support it on Firefox](https://techdows.com/2020/06/scroll-to-text-fragment-firefox-extension.html) and it seems [likely that they will implement it eventually](https://mozilla.github.io/standards-positions/#scroll-to-text-fragment).

**Comment by tk0miya** [comment]
+0 for this proposal. It would be nice if the text fragment becomes standard. But it must be helpful for some people even if it is only supported by Google Chrome.

**Comment by AA-Turner** [comment]
If/when text fragments are standardised we can look at this and re-open, until then I'm closing as not planned.

A
