### ISSUE TITLE
Must be able to remove all "_static" folders, replace with "static"

### ISSUE THREAD

**Issue by briandrawert** [sphinx-doc/sphinx#10216]
### Describe the bug

Github fails to work if a folder is named "_static". Need to rename all instances of "_static" with "static". 

### How to Reproduce

build any project, push to github, view docs

### Your project

SpatialPy

### OS

web

### Python version

n/a

### Sphinx version

4.5.0

**Comment by jeanas** [comment]
You need https://www.sphinx-doc.org/en/master/usage/extensions/githubpages.html. See https://github.com/sphinx-doc/sphinx/issues/2202#issuecomment-491480365.

**Comment by tk0miya** [comment]
Yes. Please install githubpages extension to your project.
Thanks,
