### ISSUE TITLE
Use "zh-CN" instead of "zh_CN" as the HTML lang tag for simplified Chinese pages

### ISSUE THREAD

**Issue by 0xMashiro** [sphinx-doc/sphinx#10214]
**Is your feature request related to a problem? Please describe.**
In [Sphinx language configuration](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-language): Simplified Chinese is presented as "zh_CN". But it is not the standard HTML tag (see [BCP 47 - Tags for Identifying Languages](https://link.zhihu.com/?target=http%3A//tools.ietf.org/html/bcp47)). So the auto-generated HTML lang tag will not be helpful for search engines.

https://github.com/sphinx-doc/sphinx/blob/b8789b4cb6ca034ed7209b9adc91095b0b9b763c/sphinx/themes/basic/layout.html#L107

**Describe the solution you'd like**
When the `language` is set to "zh_CN" or "zh-CN", the HTML lang tag should be "zh-CN".

**Describe alternatives you've considered**
Only support "zh_CN" in `language` configuration, but it would be treated as "zh-CN" while generating HTML lang tags.

![image](https://user-images.githubusercontent.com/21091736/155303964-de124cff-541c-4f71-a13d-8abe57ad2963.png)

**Comment by wendad** [comment]
Hello, I can't search Chinese in the search box on my computer, but I can search English。
I can search Chinese when I deploy it in ReadThedocs, do you know why ？

**Comment by tk0miya** [comment]
Thank you for reporting. I just posted #10311 to fix this bug.

@wendad I'm not sure. Please ask to the RtD team. We don't know at all how it works.

FYI: I'm not good at Chinese search. But it seems the Chinese search module requires "jieba" library. How about install it?

**Comment by wendad** [comment]
收到，谢谢
