### ISSUE TITLE
Bad formatting when def function in first line of example

### ISSUE THREAD

**Issue by Malachov** [sphinx-doc/sphinx#10225]
### Describe the bug

When using `sphinx.ext.napoleon`, google docstrings and autodoc to generate docs...

```python
"""
  Example:
      >>> a = 8
      >>> def union_return() -> int | float:
      ...     return 1
"""
```
Formatting is OK

![image](https://user-images.githubusercontent.com/39381691/156065881-a6909b91-21a1-4804-8890-14aa6ff91bed.png)

But when first line is function definition, formatting breaks

```python
"""
    Example:
        >>> def union_return() -> int | float:
        ...     return 1
"""
```
![image](https://user-images.githubusercontent.com/39381691/156066011-b9f98997-21de-474a-9359-87dd805d30a7.png)

Same without type.

[example.zip](https://github.com/sphinx-doc/sphinx/files/8157287/example.zip)

### How to Reproduce

Create file `sphinxexample.py` and insert 

```python
def sphinxexample():
    """
    Example:
        >>> def union_return():
        ...     return 1
    """
```
Then create file `example.rst` and insert
```
.. automodule:: sphinxexample
   :members:
```

Run

```
make html
```

### Expected behavior

Formatted normally as if `def` in not in first line.

### Your project

Zip in attachment

### Screenshots

![image](https://user-images.githubusercontent.com/39381691/156067036-7bf69127-3634-4dfa-b4cf-e4e80462b36d.png)

### OS

Windows

### Python version

3.10

### Sphinx version

Sphinx                        4.4.0

### Sphinx extensions

sphinx.ext.autodoc, sphinx.ext.napoleon

**Comment by tk0miya** [comment]
Sorry, I can't reproduce your error on my local. I can build attached document successfully:
<img width="356" alt="スクリーンショット 2022-03-06 15 09 43" src="https://user-images.githubusercontent.com/748828/156911541-ec215f07-d054-4447-9c58-1b80c7f2d8d6.png">


Could you make another reproducible example, please? It would be better to attach other project files (ex. conf.py).

**Comment by Malachov** [comment]
Oh... I'm sorry... I tried to make minimal reproducible config and realized, that among others

```python
napoleon_custom_sections = [
    ("Example", "returns_style"),
]
```

Which break it. Everything alright on sphinx side...
