### ISSUE TITLE
MathJax too keen to convert TeX markup in Sphinx generated HTML

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1023]
See https://github.com/mathjax/MathJax/issues/332

The best solution, I think, would be for MathJax to allow customisation via a user-supplied function 'get_nodes_for_MathJax_to_process()' and for Sphinx to add such a function to its configuration of MathJax.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1023
- Originally reported by: Jonathan Fine
- Originally created at: 2012-10-22T15:16:31.266

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2012-11-01 17:19:10+00:00_

So if I understand correctly, first MathJax needs to provide an API that we could use?

**Comment by tk0miya** [comment]
It seems mathjax/MathJax#332 has been closed and there are nothing to do from sphinx side. So I'm closing this now.
Please feel free to reopen this if there are something to do from sphinx side.
Thanks,
