### ISSUE TITLE
Doc: drop down box on top to select different version

### ISSUE THREAD

**Issue by buhtz** [sphinx-doc/sphinx#10230]
https://www.sphinx-doc.org does offer older versions of the documentation. That is very nice.

There should be a drop-down menu on top where the user can select a different (maybe release or nightly) version of the current page. This could also lower the problem with not indicating outdated version (#10229).

One good example is the Python documentation itself. https://docs.python.org/3.7/
There it is very easy to see which version I am reading currently, which other versions are available and where in the development roadmap they belong ("dev").

**Comment by tk0miya** [comment]
>https://www.sphinx-doc.org/ does offer older versions of the documentation. That is very nice.

Unfortunately, this is not correct. At present, we provide only one documentation for the master branch "officially". Surely, we've kept old versions of the documentation not removed. But it's only used to keep hyperlinks from external websites available.

**Comment by buhtz** [comment]
Again look at the Python docs.

They over older version. They offer version-independed and version-depended URLs.

And when you use `wontfix` than be strict and close the Issue.
What does `wontfix` mean for you? "fix" implicates a Bug. So you see a bug but won't fix it?
Or it is not a bug in your opinion? Then use another tag.
`wontfix` exists because of historical reasons but is impolite today.

**Comment by tk0miya** [comment]
Sorry, I don't know the meaning of "wontfix" tag. So I withdraw it now.

**Comment by tk0miya** [comment]
>Again look at the Python docs.
>They over older version. They offer version-independed and version-depended URLs.

Yes, they list (mainly) supported python versions on the menu. There are no hyperlinks to very old (historical) releases like 1.0. 

Additionally, Sphinx project is very small. So the difference between versions is also small. So I think there is no reason to show old versions.
