### ISSUE TITLE
Google Drive reports doctools.js to be a "virus"

### ISSUE THREAD

**Issue by holmuk** [sphinx-doc/sphinx#10248]
### Describe the bug

[doctools.js](https://github.com/sphinx-doc/sphinx/blob/v4.4.0/sphinx/themes/basic/static/doctools.js) from `v4.4.0` is considered to be a "virus" by Google Drive. As for `v4.3.2`, Google considers `doctools.js` to be a normal file.

### How to Reproduce

Copy `doctools.js` from `v4.4.0` tag to a Google Drive folder and then try to download the file with web or `rclone`.

### Your project

No project

### OS

Any Unix

### Python version

3.8

### Sphinx version

v4.4.0

### Additional context

It looks like a Google Drive issue, but I'm not sure about how to report this to Google.

**Comment by hugovk** [comment]
I don't get a virus warning, but a warning about the file type:

> This file type might be dangerous
>
> ‘doctools-4.3.2.js’ is a file type that might harm your computer. Only download this file if you understand the risks.

I get the same for both versions:

<img width="578" alt="image" src="https://user-images.githubusercontent.com/1324225/158019009-15f4313e-951d-4797-8083-ef9dfaf84924.png">

<img width="573" alt="image" src="https://user-images.githubusercontent.com/1324225/158019014-9ba33427-a0ad-4e8a-9126-f2ce45778c91.png">

And I get the same for `hello.js` that only contains `console.log("hello")`:

<img width="571" alt="image" src="https://user-images.githubusercontent.com/1324225/158019037-6c3fce23-780a-44c4-8faa-9950be73408b.png">

Please can you attach a screenshot of your virus warning?

**Comment by holmuk** [comment]
Seems like it's not an issue anymore, `rclone` is working normally, maybe it was a glitch back then. Anyway, thanks, @hugovk
