### ISSUE TITLE
Extension error: Could not import extension sphinxcontrib.blockdiag (exception: No module named sphinxcontrib.blockdiag)

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1025]
Hi,

I am unable to use blockdiag with Sphinx due to the following error seen when running "make html":

Extension error: Could not import extension sphinxcontrib.blockdiag (exception: No module named sphinxcontrib.blockdiag)

I have a base Ubuntu install on which I've run the following:
- sudo apt-get install make
- sudo apt-get install python-setuptools
- sudo apt-get install python-dev
- sudo easy_install PIL
- sudo easy_install -U Sphinx
- sudo easy_install blockdiag
- sphinx-quickstart
- Edit to conf.py file to add 'sphinxcontrib.blockdiag' to the extensions array.
- Edit to index.rst to include a simple blockdiag directive.

Looking for some guidance :)

Regards,
Kevin

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1025
- Originally reported by: Kevin Howe
- Originally created at: 2012-10-24T18:46:06.725

**Comment by shimizukawa** [comment]
_From Robert Lehmann on 2012-10-24 16:51:15+00:00_

Do you have [sphinxcontrib-blockdiag](http://pypi.python.org/pypi/sphinxcontrib-blockdiag/) installed?

**Comment by shimizukawa** [comment]
_From Kevin Howe on 2012-10-24 17:25:13+00:00_

I had though that "sudo easy_install blockdiag" covered it, i've also run "sudo  easy_install sphinxcontrib-blockdiag", thanks!

**Comment by shimizukawa** [comment]
_From Kevin Howe on 2012-10-24 17:29:27+00:00_

Issue resolved.

**Comment by shimizukawa** [comment]
_From Robert Lehmann on 2012-11-02 12:50:09+00:00_

I have run a quick experiment:  Is it commonplace for packages to have a base dependency and an equally-named sphinxcontrib counterpart?  That would probably warrant a documentation change or notice during import failure.

Currently, only 6 of 57 (actdiag, blockdiag, eagle, nwdiag, sadisplay, seqdiag) sphinxcontrib packages exhibit that feature.  Leaving this closed.

**Comment by cumulus13** [comment]
i has installed sphinxcontrib-blockdiag and blockdiag but still error ?

Running Sphinx v3.2.1
Traceback (most recent call last):
  File "/virtualenv/flask/lib/python3.8/site-packages/sphinx/registry.py", line 409, in load_extension
    mod = import_module(extname)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'sphinxcontrib.log_cabinet'

Extension error:
Could not import extension sphinxcontrib.log_cabinet (exception: No module named 'sphinxcontrib.log_cabinet')
make: *** [Makefile:20: html] Error 2

**Comment by tk0miya** [comment]
@cumulus13 Please read the output. It says "ModuleNotFoundError: No module named 'sphinxcontrib.log_cabinet'".
The error says `sphinxcontrib.log_cabinet` is not found, not blockdiag. I don't know at all about the extension. But, I guess you need to install it.

Anyway, it is not a bug of Sphinx. So please post a question if you're still in the trouble.

Thanks,
