### ISSUE TITLE
Makefile for building mo and merging po files

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1026]
AFAIK, there is no way to build po files for current locale, and not way to merge po files when the documentation is updated.

Are you interested in merging this Makefile [1] ?

[1] https://gist.github.com/3742565

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1026
- Originally reported by: Amirouche  Boubekki
- Originally created at: 2012-10-24T22:24:23.777

**Comment by shimizukawa** [comment]
_From Amirouche  Boubekki on 2012-10-27 19:21:13+00:00_

This Makefile has been updated to include a command which create the initial po files https://gist.github.com/3951659

**Comment by shimizukawa** [comment]
_From Amirouche  Boubekki on 2012-11-01 17:22:12+00:00_

Do you want a PR ?

**Comment by shimizukawa** [comment]
_From Robert Lehmann on 2012-11-01 17:27:58+00:00_

Please do!

**Comment by shimizukawa** [comment]
_From Amirouche  Boubekki on 2012-11-11 22:50:33+00:00_

There is still a problem, the script works only with one output directory where sphinx can take several po directories http://sphinx-doc.org/latest/config.html#confval-locale_dirs should the script only consider the first directory in the list ?

**Comment by tk0miya** [comment]
@shimizukawa Could you tell us your opinion?
The first `sphinx-intl` was released after this discussion (at 2013).

**Comment by shimizukawa** [comment]
Please use sphinx-intl.
- http://www.sphinx-doc.org/en/stable/intl.html#translating-with-sphinx-intl
- https://pypi.python.org/pypi/sphinx-intl
