### ISSUE TITLE
Sphinx fails with dev version of docutils

### ISSUE THREAD

**Issue by lsaffre** [sphinx-doc/sphinx#10264]
### Describe the bug

I'd like to contribute to docutils, but when I use the docutils dev version, pip says::

sphinx 4.4.0 requires docutils<0.18,>=0.14, but you have docutils 0.19b0.dev0 which is incompatible.

I can workaround this by specifying "pip install --no-warn-conflicts -e .", but I wondered why does Sphinx require "<0.18"? Shouldn't we simply remove this requirement?

### How to Reproduce

```
$ svn checkout https://svn.code.sf.net/p/docutils/code/trunk docutils-code
$ pip install -e docutils-code/docutils
```

### Your project

https://luc.lino-framework.org/blog/2022/0314.html

### OS

Linux

### Python version

3.8

### Sphinx version

4.4.0

**Comment by tk0miya** [comment]
The reason why we restrict the version of docutils is the combination not guaranteed yet. Please wait for the update (refs: https://github.com/sphinx-doc/sphinx/issues/9777)
