### ISSUE TITLE
Overloaded default values rendered as string literal.

### ISSUE THREAD

**Issue by laurensvalk** [sphinx-doc/sphinx#10279]
### Describe the bug

Some arguments of overloaded functions are rendered as a string literal. For example:

```
file: _io.FileIO = 'sys.stdin'
```

See screenshot below.

This may be a variant of https://github.com/sphinx-doc/sphinx/issues/8693

### How to Reproduce

Exactly the same as https://github.com/sphinx-doc/sphinx/issues/10278

### Expected behavior

Default values not rendered as string literals.

### Your project

https://github.com/pybricks/sphinx-issues-minimal

### Screenshots

![image](https://user-images.githubusercontent.com/12326241/159285246-12230d69-1fe6-4ce2-878f-6fcf2ebd7c31.png)

### OS

Ubuntu

### Python version

3.8.3

### Sphinx version

4.4.0

### Sphinx extensions

'sphinx.ext.autodoc', 'sphinx.ext.napoleon', 'sphinx_rtd_theme'

### Additional context

This was originally posted here: https://github.com/pybricks/pybricks-api/issues/81

**Comment by laurensvalk** [comment]
I confirm that https://github.com/tk0miya/sphinx/commit/5e418b4318e5fa80acbc75f71664fb88797f5176 fixes this issue and #10278 too. Thank you!

![image](https://user-images.githubusercontent.com/12326241/161207542-4a78a232-2fe8-4646-8230-59950485fa11.png)

**Comment by tk0miya** [comment]
Thank you for confirmation!
