### ISSUE TITLE
Cannot search for certain words (e.g. "using")

### ISSUE THREAD

**Issue by CendioOssman** [sphinx-doc/sphinx#10277]
### Describe the bug

Certain words fail to produce any search results. One such word is "using", but there are likely more.

### How to Reproduce

Include this simple document:

```rst
util
====

Synopsis
--------

**util** [*options*]

Description
-----------

**util** is great! See :ref:`index`.

Run this command using sudo
---------------------------

Will this be found by the search?
```

Generate some html, then search for "using".

### Expected behavior

The page should be included in the search results.

### Your project

N/A

### OS

Linux

### Python version

3.6.12

### Sphinx version

4.2.0

### Additional context

This is fallout from #2621. Which surprises me a bit since it is ages since that was committed. Perhaps something else hid the bug for so long?

The problem is that the JavaScript code assumes (in `Search.query()`) a word was left unstemmed if it is shorter than 3 characters. But that is not what `SearchLanguage.word_filter()` does as it has a much more complex logic. I also assume it can be overloaded for other languages than English.

Things work fine on Sphinx' own home page though for some reason. But it looks like it delegates the search to readthedocs rather than using the default search code.

**Comment by tk0miya** [comment]
Short words becomes not-filtered since v4.0 (refs: https://github.com/sphinx-doc/sphinx/pull/8070). So it should not be filtered by JS code.

**Comment by CendioOssman** [comment]
Thanks! Fix seems to solve the issue here.
