### ISSUE TITLE
module 'jinja2.utils' has no attribute 'escape'

### ISSUE THREAD

**Issue by rathishcholarajan** [sphinx-doc/sphinx#10289]
### Describe the bug

Getting this error in our builds since the latest release 3.1.0 of Jinja2.
```
module 'jinja2.utils' has no attribute 'escape'
```

### How to Reproduce

https://github.com/Qiskit/qiskit-ibm-runtime/runs/5677789048?check_suite_focus=true#step:5:683

### Expected behavior

Builds shouldn't fail.

### Your project

https://github.com/Qiskit/qiskit-ibm-runtime/runs/5677789048?check_suite_focus=true#step:5:683

### OS

Mac

### Python version

3.9

### Sphinx version

4.4.0

**Comment by aiwalter** [comment]
Having same issue, seems today released `jinja2` is causing the issue, there is also an issue open: https://github.com/pallets/jinja/issues/1626

**Comment by davidism** [comment]
Jinja2 itself uses Sphinx, and does not have this issue building its docs. Sphinx does not appear to import `escape` from Jinja2 (or MarkupSafe). Perhaps another extension or library you are using does? You may be able to turn on more verbose output from `sphinx-build` to see the full traceback and identify what is doing the import.

**Comment by aiwalter** [comment]
yes the issue comes actually from `nbconvert`, sry for confusion. I opened an issue there: 
https://github.com/jupyter/nbconvert/issues/1736

**Comment by rathishcholarajan** [comment]
Thanks @davidism @aiwalter. We are using `nbconvert` as well and looks like that's the issue.

**Comment by mjmeijer** [comment]
When the cause is hidden somewhere in your dependency tree, as in my Flask app, you can workaround for the moment by adding explicit dependecy to your `requirements.txt`
```
jinja2==3.0.3
```
