### ISSUE TITLE
Overridden, overloaded class docstring return type rendered as None

### ISSUE THREAD

**Issue by laurensvalk** [sphinx-doc/sphinx#10280]
### Describe the bug

Some overloaded class definitions show ``None`` as a return type, when there shouldn't be any return type.

This seems to happen when the overloaded functions are overridden in the final docstring.

A class without this problem is also provided for comparison.

### How to Reproduce

Exactly the same as https://github.com/sphinx-doc/sphinx/issues/10278

### Expected behavior

![image](https://user-images.githubusercontent.com/12326241/159285983-75d83f0b-4824-47ba-a511-2a28d54396c8.png)

### Your project

https://github.com/pybricks/sphinx-issues-minimal

### Screenshots

![image](https://user-images.githubusercontent.com/12326241/159285933-1385e59f-1d7c-47be-8a85-69bc980db8be.png)

### OS

Ubuntu

### Python version

3.8.3

### Sphinx version

4.4.0

### Sphinx extensions

'sphinx.ext.autodoc', 'sphinx.ext.napoleon', 'sphinx_rtd_theme'

### Additional context

Related Sphinx issue: https://github.com/sphinx-doc/sphinx/issues/10281

This was originally reported in https://github.com/pybricks/pybricks-api/issues/87

**Comment by tk0miya** [comment]
This is not related to overloaded constructors. Autodoc automatically fills return value annotation to the signature definitions in the docstring excluding the first entry unexpectedly. So I reproduced this with this class:
```
class Foo:
    """Foo()
    Foo(x: int)
    Foo(x: int, y: int)

    docstring
    """
```

I agree this is not unexpected behavior. So I'll fix this soon.

Note: The example you given uses `autoclass_content = 'both'` option. Then autodoc refers the docstring of `MyComplex.__init__()` method too.

**Comment by laurensvalk** [comment]
https://github.com/sphinx-doc/sphinx/pull/10320/commits/9f52d7dd3f5d29fe6fa9ce17cabe3728cc517c36 fixes it. Thanks!

![image](https://user-images.githubusercontent.com/12326241/161371700-c459054a-9470-49ae-b610-65c253097fcc.png)
