### ISSUE TITLE
Configure URL scheme for html_baseurl

### ISSUE THREAD

**Issue by ngulden** [sphinx-doc/sphinx#10282]
**Is your feature request related to a problem? Please describe.**

I have documentation in different versions and languages. 

I want to use the [sphinx_sitemap extension](https://github.com/jdillard/sphinx-sitemap). It requires the `html_baseurl` configuration in conf.py. The sitemap allows a schema configuration that considers the `version` and `language` settings, even as overwritten configuration options to `sphinx-build`.

The `html_baseurl` is responsible for adding the following line to the HTML build:
```
<link rel="canonical" href="{html_baseurl}/{doc}.html" />
```

What I need, is a baseurl in the form `{html_baseurl}/{version}/{lang}/{doc}.html`.

Without a customization possibility, my docs lack a correct `link rel="canonical"` line, which I'd like to have, and a suitable sitemap that I also like to use.

**Describe the solution you'd like**

I like to have a configuration option for the `html_baseurl` that allows to configure the scheme for the part after the base. For example:
```
html_baseurl = "https://docs.example.org/doc"
html_baseurl_doc_scheme = "{version}/{language}"
```

The result would then be `<link rel="canonical" href="https://docs.example.org/doc/1.0/en/index.html" />` for the English version and and `<link rel="canonical" href="https://docs.example.org/doc/1.0/de/index.html" />` for the German version.

**Describe alternatives you've considered**

I considered to configure `html_baseurl` depending on the language. But I couldn't find a way yet to access overwritten configuration variables in my conf.py to make suitable adjustment. I call the builder with the following command:
```
make -e SPHINXOPTS="-D language=de" -e BUILDDIR="_build/de" html
```

I need access to the `language` value passed in through the `-D` parameter.

**Comment by cblegare** [comment]
You could try a local extension an set the configuration for html_baseurl there.

something that looks like

```
# in your conf.py
def set_html_baseurl(app, config):
    config.html_baseurl = "{html_baseurl}/{version}/%s/{doc}.html" % config.language

def setup(app): 
    app.connect(
        "config-inited",
        set_html_baseurl,
    )
```

**Comment by tk0miya** [comment]
Agreed. It's better to use code to customize `html_baseurl`.

**Comment by ngulden** [comment]
Thank you very much. Your hint was a push in the right direction. I could solve my scenario. I already use an extension for my several projects and I just added the needed changes.

From my side, nothing to do here anymore. I close the issue.
