### ISSUE TITLE
An event after post-transform but before writing to filesystem?

### ISSUE THREAD

**Issue by cblegare** [sphinx-doc/sphinx#10295]
**Is your feature request related to a problem? Please describe.**

I would like to be able to change something in the environment or in the builder *after* cross-reference resolution, but *before* writing the files.  In my case, I wanted to add items (resolved cross-references) to a Domain index.

**Describe the solution you'd like**

I don't know if this could be possible, especially to keep the parallel builds working the same, but maybe an event that is fired not for a specific document, after post-transforms, before write?

**Describe alternatives you've considered**

Wrote a PostTransformer that regenerate the Domain index after xref resolution.  It works, but it need to redo the same job over and over, since it can't either

- Know when it processing the last document
- Know when all cross-references have been resolved.

And there is no later hooks before writing to the filesystem (that I know of).

**Additional context**

- [sphinx-dev post](https://groups.google.com/g/sphinx-dev/c/GaVMIwOA0sg)

**Comment by tk0miya** [comment]
Unfortunately, there is no chance to hook an event during xref resolution (post-transforming) and writing. Sphinx goes these two processes continuously for each document. For example, xref resolution for docB would be invoked after writing for docA. So it's hard to add such an event.

**Comment by cblegare** [comment]
Hello and thank you for this response.

> Unfortunately, there is no chance to hook

Yes, I suspected that

I have found an other way that would make even more sense and solve my issue ultimately, and opened a new issue about it.
