### ISSUE TITLE
Unpin docutils < 0.18?

### ISSUE THREAD

**Issue by befeleme** [sphinx-doc/sphinx#10309]
When preparing Sphinx 4.5.0 update in Fedora, I noticed that issues with docutils 0.18.1 were resolved and the test workflow runs green on Sphinx' branch 4.x. Based on that, could you also unpin it in [setup.py](https://github.com/sphinx-doc/sphinx/blob/4.x/setup.py#L25) or is there something preventing the change?

**Comment by tk0miya** [comment]
That's already discussed in #9777. Please wait for a while more.
