### ISSUE TITLE
Sphinx automodule: class method not documented when decorated with mocked function

### ISSUE THREAD

**Issue by GutiCW** [sphinx-doc/sphinx#10310]
### Describe the bug

I have a class with decorated methods. The function used as a decorator is provided by a module not available when building the documentation, hence this module is mocked in `conf.py` using `autodoc_mock_imports = ['module_with_decorator']`.

```
.. automodule:: my_class
    :members:
```

```
from module_with_decorator import my_decorator


class MyClass:
    """
    My test class.
    """

    @staticmethod
    def my_undecorated_static_method():
        """This is my_undecorated_static_method."""

    @staticmethod
    @my_decorator(param0, param1)
    def my_decorated_static_method():
        """This is my_decorated_static_method."""

    @classmethod
    def my_undecorated_class_method(cls):
        """This is my_undecorated_class_method."""

    @classmethod
    @my_decorator(param0, param1)
    def my_decorated_class_method(cls):
        """This is my_decorated_class_method."""

    def my_undecorated_instance_method(self):
        """This is my_undecorated_instance_method."""

    @my_decorator(param0, param1)
    def my_decorated_instance_method(self):
        """This is my_decorated_instance_method."""
```

The decorated class methods are not shown in the documentation - others are shown correctly.

[![Missing class method decorated with mocked function][1]][1]

Any suggestions regarding this issue?

  [1]: https://i.stack.imgur.com/c8cCe.png

### How to Reproduce

Decorate a class method with a function from a mocked module.
PowerShell:
$builder_name = "html" ; $doc_source = "...\test\doc\tp_testcase_docstring" ; $dest = "$doc_source\_build\$builder_name" ; conda activate $conda_env ; sphinx-build "$doc_source" "$dest" -b $builder_name

### Expected behavior

The class methods should be visible in the documentation.

### Your project

[test.zip](https://github.com/sphinx-doc/sphinx/files/8380987/test.zip)

### OS

Windows

### Python version

3.9.7

### Sphinx version

4.4.0

### Sphinx extensions

sphinx.ext.autodoc

### Additional context

Related to [stackoverflow.com](https://stackoverflow.com/questions/71613847/sphinx-automodule-class-method-not-documented-when-decorated-with-mocked-functi).

**Comment by tk0miya** [comment]
At present, decorators on the mocked module are not working because they return mocked objects instead of functions or methods. I don't have good ideas to generate documents for them. So I marked this as "help wanted".

Please post your idea or send a PR to implement it. Thanks,
