### ISSUE TITLE
RFE: enable `Discussions` tab in git repo

### ISSUE THREAD

**Issue by kloczek** [sphinx-doc/sphinx#10349]
I know that at the moment is mailing list for discussing various sphinx topics however drawback of that way of communication is that it does not create automatically cross references between tickets, PRs and discussions topics.
IMO it would be good to enable git repo discussion tab 😄

**Comment by adam-grant-hendry** [comment]
> IMO it would be good to enable git repo discussion tab 😄

I would also love this to ask general questions which are not bugs/feature requests/etc.

**Comment by picnixz** [comment]
@AA-Turner Do you want to enable this feature? Personally, I'm not against since I could turn issues into discussions if the latter are not really issues. On the other hand, people could use StackOverflow for general questions, but I don't think the sphinx tags are really enforced out there (or even read).

**Comment by AA-Turner** [comment]
I'm hesitant as I don't want to invite (more) basic/user questions, I want to keep the repo focussed on development. I briefly looked at Discourse (a la https://discuss.python.org), but the cheapest option is very expensive for a project with an effective budget of £0.

A

**Comment by picnixz** [comment]
> for a project with an effective budget of £0.

That's a great budget indeed :laughing: 

> I'm hesitant as I don't want to invite (more) basic/user questions

Yes, that's what I feared as well and I understand your point On the other side, I don't know how well SO posts are actually answered (and I don't have time to reply to them). But if you want to keep the repo focused on dev only, what we *might* do is actually create a "dummy" repo where you would have discussions only (no issue, no PRs). That caould be a fake Discourse approach.

**Comment by AA-Turner** [comment]
> create a repo where you would have discussions only

This might be a reasonable compromise; and would allow unsubscribing from the repository.

cc @sphinx-doc/developers @sphinx-doc/triagers for thoughts (if any), including naming suggestions(!).

A

**Comment by adam-grant-hendry** [comment]
> I'm hesitant as I don't want to invite (more) basic/user questions, I want to keep the repo focussed on development.

Discussions are separable by tags to differentiate basic questions from development. You can also create Announcements and Polls, which is more difficult with Issues in a repo.

![image](https://github.com/sphinx-doc/sphinx/assets/59346180/66581593-2740-4039-9d03-8f7a8a995683)

> But if you want to keep the repo focused on dev only, what we might do is actually create a "dummy" repo where you would have discussions only (no issue, no PRs).

The `pyvista` repo, for example, originally did this, but eventually switched to Discussions. Maintaining it became challenging and more people are expecting now to have one place to go.

I strongly suggest using it, even trying it on a temporary basis. I am confident you will like it and will regret the extra work of attempting a workaround.

**Comment by jdillard** [comment]
> I strongly suggest using it, even trying it on a temporary basis. I am confident you will like it and will regret the extra work of attempting a workaround.

+1 for setting expectations, having a plan for getting it organized, and giving Discussions in this repo a trial run.

**Comment by webknjaz** [comment]
@AA-Turner it is possible to declare one repo discussions as org-global. I chose to do this in a `.github` repo since that one needs to exist anyway. It's nice to have the discussions pop up as an org tab.

**Comment by jdillard** [comment]
> When you enable organization discussions, you will choose a repository in the organization to be the source repository for your organization discussions. You can use an existing repository or create a repository specifically to hold your organization discussions. Discussions will appear both on the discussions page for the organization and on the discussion page for the source repository.

https://docs.github.com/en/organizations/managing-organization-settings/enabling-or-disabling-github-discussions-for-an-organization#about-organization-discussions

hrm, I could vote for that option as well. Although seems weird to me at first glance to try and hide it in a configuration repo, but I could probably get over that.

**Comment by webknjaz** [comment]
Could be in this repo as well. I just don't think that if there's a config repo, there's a justification for another one just for discussions...

**Comment by AA-Turner** [comment]
I have found and applied for membership of Discourse's programme for open source: https://free.discourse.group

If accepted, we'll need to decide between Discourse and GitHub Discussions. I personally have a preference, but I'd be interested in taking soundings here--*ceteris paribus*, which of the two fora would you prefer?

A

**Comment by webknjaz** [comment]
I tend to prefer GH Discussions as external places end up forgotten and rotten. I stopped opening discourses of several places, even where I maintain projects — that's an addition maintenance burden.

**Comment by picnixz** [comment]
I vote for gh discussion so that I have all notifications at the same place.

**Comment by shimizukawa** [comment]
I also vote for GitHub Discussion.
Whether it is a mailing list or Discourse, I think the disadvantage of having multiple resources is significant when considering the operational capacity.

**Comment by stephenfin** [comment]
Yup, GitHub Discussions (coupled with the existing mailing lists) would be my preference also.

**Comment by blaisep** [comment]
I suppose, if we needed a place to forward requests and non-dev chit-chat,  we could have a Category on discuss.python.org which has a lot of long-form PEP and python docs conversations.

**Comment by AA-Turner** [comment]
Please see https://github.com/orgs/sphinx-doc/discussions

A

**Comment by kloczek** [comment]
Thank you 👍 😄
