### ISSUE TITLE
The example in the documentation in section 'Add your own static files to the build assets' is incorrect

### ISSUE THREAD

**Issue by Thecarisma** [sphinx-doc/sphinx#10344]
### Describe the bug

In the [Add your own static files to the build assets](https://www.sphinx-doc.org/en/master/development/theming.html#add-your-own-static-files-to-the-build-assets) documentation example 

```python
from os import path
from sphinx.util.fileutil import copy_asset_file

def copy_custom_files(app, exc):
    if app.builder.format == 'html' and not exc:
        staticdir = path.join(app.builder.outdir, '_static')
        copy_asset_file('path/to/myextension/_static/myjsfile.js', staticdir)

def setup(app):
    app.connect('builder-inited', copy_custom_files)
```

When sphinx-build is executed it will fail with the error message

```python
Handler <function copy_custom_files at 0x00000250277A53F0> for event 'builder-inited' threw an exception (exception: copy_custom_files() missing 1 required positional argument: 'exc')
```

Likely because when the `builder-initiated` event is emitted only 1 positional argument *app* is invoked with the function. But when the event is changed to `build-finished` event, the two positional arguments *app* and *exc* is invoked with the function.

The solution is simply to change the event in the example from `builder-inited` to `build-finished`. or provide the appropriate example for `builder-inited` event.

### How to Reproduce

Simply execute the example in the [Add your own static files to the build assets](https://www.sphinx-doc.org/en/master/development/theming.html#add-your-own-static-files-to-the-build-assets) section of the documentation

### Your project

https://github.com/Thecarisma/themata

### OS

Any

### Python version

Any

### Sphinx version

Any

**Comment by cblegare** [comment]
Hello @Thecarisma 

I am no maintainer here, just trying to help.  It seems to me that you are right, the example is wrong.  It also look superfluous, since files in a theme's `static` folder will all be copied to the built static folder.  See https://www.sphinx-doc.org/en/master/development/theming.html#creating-themes. Have you tried it?

I see that you opened a PR, which is great thank you. I also opened one, removing the section entirely. I suppose @tk0miya can choose whatever is best for Sphinx.

Finally, I've looked into these themes you are working on.  They're great :) thanks for this nice work!

**Comment by Thecarisma** [comment]
Hi @cblegare 

I am aware the files in the static folder get copied to the built _static folder, but my use case is to copy a javascript file from the module folder which is outside the themes static folder to the built static folder.

I don't see the example as superfluous, as without that example it might be difficult to implement a new feature am working in my sphinx themes.

**Comment by cblegare** [comment]
@Thecarisma I see! I didn't look into the code behind your themes, but I guess the right javascript/css/otherstatic is picked/configured/generated based on configuration or other user input.  That makes perfect sense! I think it should be worth it to add a small detail about why this is documented in addition to the theme thing.  I'll simply comment your PR and close mine.

**Comment by tk0miya** [comment]
The recommended way to install own JS/CSS files is putting files onto `static/` directory. But there are some themes that could not put them on the directory for some reasons (ex. dynamic generation, packging strategy, and so on). So it would be better to keep this section. So I'd like to merge #10345.

**Comment by tk0miya** [comment]
The recommended way to install own JS/CSS files is putting files onto `static/` directory. But there are some themes that could not put them on the directory for some reasons (ex. dynamic generation, packging strategy, and so on). So it would be better to keep this section. So I'd like to merge #10345.
