### ISSUE TITLE
make extensions installable from online repositories.

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#104]
The last issues [1], [2] let me come across a crazy idea:
during sphinx-quickstart the user could be asked whether to fetch additionaly extensions from an online repository. These additional extensions would be installed automatically and activated during the conf.py creation.
Such repositories could be PyPi or of other architecture (e.g. [3]).

Maybe too complicated. But also worth thinking about.

Thanks.

[1] http://groups.google.com/group/sphinx-dev/browse_thread/thread/e228b05024a5725c
[2] https://github.com/sphinx-doc/testing/issues/61
[3] http://wiki.qgis.org/qgiswiki/PluginRepositories

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/104
- Originally reported by: [timmie](https://bitbucket.org/timmie)
- Originally created at: 2009-02-18T19:51:23.180

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2009-02-18 20:15:34+00:00_

Thinking big is the key :)

I'll keep this in mind.

**Comment by tk0miya** [comment]
-1 for this.
That is not responsibility of Sphinx. We already have good package manager; pip.
In addition, we have a lot of python environments; OS packages, official package, pyenv, virtualenv and so on. It is hard to install python packages as users expected.

**Comment by stephenfin** [comment]
I concur: we should not be reproducing the functionality of `pip`. What I would like to see is some kind of manifest file for extensions, that would list not only the type(s) of extension(s) a package provides, but the configuration options available to them. This would help greatly in categorising extensions.

**Comment by stephenfin** [comment]
Perhaps this issue should be closed as a WONTFIX?

**Comment by stephenfin** [comment]
Perhaps this issue should be closed as a WONTFIX?

**Comment by shimizukawa** [comment]
It looks good with wontfix. I will close it. Thanks.
