### ISSUE TITLE
Proposal: Invite AA-Turner as a new collaborator

### ISSUE THREAD

**Issue by tk0miya** [sphinx-doc/sphinx#10408]
# Proposal

Hello maintainers,
Today, I'd like to invite @AA-Turner  as a new collaborator on our project

He had already contributed many works until now:

* https://github.com/sphinx-doc/sphinx/pulls?q=is%3Apr+author%3AAA-Turner+
* migrate PEPs website to Sphinx: https://github.com/python/peps/issues/2

I believe his experience would help us.
What do you think? Please 👍 for this if you agreed.

I know there is no special procedure to welcome a new committer/collaborator. So I will invite him if no objection.

**Comment by hugovk** [comment]
I'm not a maintainer here, but I'm working with Adam in the PEPs repo and can speak highly for his hard work and persistence in migrating the PEPs to using Sphinx.

**Comment by shimizukawa** [comment]
No objection from me.
Welcom!

**Comment by tk0miya** [comment]
Note: I promoted him to co-maintainer from collaborator now.

**Comment by jmckenna** [comment]
@tk0miya, @AA-Turner, wonderful, "the more the merrier"!

I also believe that the Sphinx project should have a Project Steering Committee (PSC), which would add a way to discuss and resolve difficult decisions together as a committee (for example PSC structure, see https://mapserver.org/development/rfc/ms-rfc-23.html ).

Please give that some consideration.

**Comment by tk0miya** [comment]
Unfortunately, I don't have enough time to establish SC. So it's better to do to people who are interested in that. Additionally, I don't have skills to discuss something in English... It's very tough and hard to me.

**Comment by marxin** [comment]
I would also recommend the project establish a sponsoring platform people can use in order to support Sphinx (right now one can only support @tk0miya). You're doing a great job and a gazillion projects write docs using Sphinx. I bet they would donate to you so that you can fully pay the key maintainers of the project.

**Comment by AA-Turner** [comment]
PSC -- @jmckenna I'd be interested to hear the background, but I suppose this is unlikely to happen as @tk0miya-san has said he doesn't have time to participate and he is the most active maintainer of Sphinx.

Sponsorship -- I've no strong opinion, though not sure how the legalities would work as Sphinx is an unincorporated association, and we have maintainers in Japan, France, the UK, etc.

A
