### ISSUE TITLE
Wrong display for footnotes/citations with docutils 0.18.1

### ISSUE THREAD

**Issue by stsewd** [sphinx-doc/sphinx#10415]
### Describe the bug

docutils 0.18 changed the html structure of citations/footnotes as noted in https://github.com/sphinx-doc/sphinx/issues/9777#issuecomment-1086868330, but all themes that sphinx includes haven't been updated to support that structure.

#### 0.18.1

![Screenshot 2022-05-02 at 15-28-57 Sphinx documentation contents — Sphinx documentation](https://user-images.githubusercontent.com/4975310/166323058-1e68baeb-1f5c-4106-91ac-a6e6e23ca963.png)

#### 0.17

![Screenshot 2022-05-02 at 15-32-13 Sphinx documentation contents — Sphinx documentation](https://user-images.githubusercontent.com/4975310/166323079-f1de342f-4b49-4c32-bf53-38c2a9cf4dad.png)

### How to Reproduce

Create a project with an index.rst file with the following content

```rst
Footnotes
---------

.. [1] A footnote contains body elements, consistently indented by at
   least 3 spaces.

   This is the footnote's second paragraph.

.. [#label] Footnotes may be numbered, either manually (as in [1]_) or
   automatically using a "#"-prefixed label.  This footnote has a
   label so it can be referred to from multiple places, both as a
   footnote reference ([#label]_) and as a hyperlink reference
   (label_).

.. [#] This footnote is numbered automatically and anonymously using a
   label of "#" only.

.. [*] Footnotes may also use symbols, specified with a "*" label.
   Here's a reference to the next footnote: [*]_.

.. [*] This footnote shows the next symbol in the sequence.

.. [4] Here's an unreferenced footnote, with a reference to a
   nonexistent footnote: [5]_.

Citations
---------

.. [11] This is the citation I made, let's make this extremely long so that we can tell that it doesn't follow the normal responsive table stuff.

.. [12] This citation has some ``code blocks`` in it, maybe some **bold** and
       *italics* too. Heck, lets put a link to a meta citation [13]_ too.

.. [13] This citation will have two backlinks.


Here's a reference to the above, [12]_, and a [nonexistent]_ citation.

Here is another type of citation: `citation`

```

Install sphinx from the 5.x branch and build that project with any of the themes included in sphinx (or even the default one, alabaster)

```
$ pip install git+https://github.com/sphinx-doc/sphinx.git@5.x
$ sphinx-build . _build/html
$ xdg-open _build/html/index.html
```

### Expected behavior

citations/footnotes to look similar to the ones generated with docutils 0.17.

![Screenshot 2022-05-02 at 15-32-13 Sphinx documentation contents — Sphinx documentation](https://user-images.githubusercontent.com/4975310/166323079-f1de342f-4b49-4c32-bf53-38c2a9cf4dad.png)

### Your project

[test.zip](https://github.com/sphinx-doc/sphinx/files/8605919/test.zip)

### OS

Linux

### Python version

3.10

### Sphinx version

5.x

### Additional context

I tried to add some CSS to fix this, but my CSS skills aren't that good

ref https://github.com/sphinx-doc/sphinx/issues/9777 https://github.com/sphinx-doc/sphinx/issues/9777#issuecomment-1112730120

[test.zip](https://github.com/sphinx-doc/sphinx/files/8605919/test.zip)

**Comment by mgeier** [comment]
I don't know if this is part of this issue or if there is already a separate issue ... but now there are double brackets in the reference links!

See e.g. https://www.sphinx-doc.org/en/master/usage/advanced/intl.html#sphinx-internationalization-details

**Comment by AA-Turner** [comment]
One set is in the HTML source, ``<span class="fn-bracket">[</span>``. The other is added as in CSS:

https://github.com/sphinx-doc/sphinx/blob/af425c069f6f51ba8fb3c348fd53479f0434a779/sphinx/themes/basic/static/basic.css_t#L240-L248

We should only use the CSS brackets if `span.fn-bracket` is absent.

A

**Comment by AA-Turner** [comment]
On second thoughts, @mgeier can you open a new issue to track this please? I'll keep this one closed for the positioning stuff.

**Comment by mgeier** [comment]
OK, done: https://github.com/sphinx-doc/sphinx/issues/10522
