### ISSUE TITLE
Inventory for external cross-reference not found

### ISSUE THREAD

**Issue by skyscribe** [sphinx-doc/sphinx#10425]
### Describe the bug

I'm following the user guides and initializing several external document site references by `intersphinx_mapping` in `conf.py`. One of these targets are named as `'target': ("url_to_target", None)`

In rst files, I'm trying to referring to these links explicitly by
```
:external+target:ref:`My TItle <external_link>`
```

I just meet below warning when building gitlab pages (html builder):

```
Introduction.rst:15: WARNING: inventory for external cross-reference not found: target
```

### How to Reproduce

Build my project with 
```
sphinx-build -E -b html . html_files
```

This is an occasional issue - for some of the builds it's working properly, while other builds may just fail with above mentioned warnings. Generated HTML page would show nothing for the external reference. 

### Expected behavior

External references shall always be build properly.

### Your project

Can't share here directly

### Screenshots

N/A

### OS

Ubuntu 20.04.x

### Python version

3.9

### Sphinx version

Sphinx v4.5.0

### Sphinx extensions

['sphinx.ext.graphviz', 'sphinxcontrib.plantuml', 'docxbuilder', 'sphinxcontrib.csv_filter', 'sphinxcontrib.csv2uml', 'sphinx.ext.autosectionlabel', 'sphinx.ext.intersphinx', 'sphinxcontrib.rsvgconverter', 'sphinx.ext.extlinks', 'sphinx.ext.autosectionlabel', 'sphinxcontrib.confluencebuilder', 'sphinx.ext.intersphinx', 'sphinxcontrib.rsvgconverter']

### Extra tools

NA

### Additional context

Clean up everything may work sometimes, though `sphinx-build -E` option doesn't work as expected.

**Comment by tk0miya** [comment]
```
Introduction.rst:15: WARNING: inventory for external cross-reference not found: target
```

This message is emitted when intersphinx can't find the inventory settings named "target". So please check your configuration. It might be helpful to check the build log carefully for investigation.

**Comment by skyscribe** [comment]
@tk0miya I'm pretty sure my configuration is correct! Even with the same configuration sometimes I get green build so correct links are available, or sometimes empty. 

I've figured out one workaround: cleaning up the whole output directory before each `sphinx-build` command so upon clean builds, problem would disappear.

**Comment by tk0miya** [comment]
Hmm... we need to reproduce the error to fix the bug. Is it difficult to make a minimal example?

**Comment by skyscribe** [comment]
I don't know if this is easy to do. My project is complex that 10+ external references are configured, all other external references are working except this one.

For now I just work around this problem  by cleaning up the whole build directory firstly so force clean build works. 

I would indeed be annoying so I was thinking if the `target` string might be special that I renamed it to another stuff like `xxx_target` but problem remains. 

I'll see if this can be reproduced easily.

**Comment by bskinn** [comment]
@skyscribe -- is there any particular reason why some extensions show up more than once in the list you provide?

> `['sphinx.ext.graphviz', 'sphinxcontrib.plantuml', 'docxbuilder', 'sphinxcontrib.csv_filter', 'sphinxcontrib.csv2uml', 'sphinx.ext.autosectionlabel', 'sphinx.ext.intersphinx', 'sphinxcontrib.rsvgconverter', 'sphinx.ext.extlinks', 'sphinx.ext.autosectionlabel', 'sphinxcontrib.confluencebuilder', 'sphinx.ext.intersphinx', 'sphinxcontrib.rsvgconverter']`

I don't know if naming an extension twice could cause weird behavior, but it seems like a possible candidate. Maybe try removing the duplicates?

**Comment by skyscribe** [comment]
> 

I'm running a complex system that setup.py is generated by combining customizable json configurations and default settings from a template, so there can be duplicate indeed. I'll also try to sort out and remove duplicate ones.

**Comment by bskinn** [comment]
Ah, in that case, I think it would suffice to just cast the list to a set and back:

```
new_list = list(set(old_list))
```

**Comment by skyscribe** [comment]
@bskinn definitely! I'll try with this the next day, thanks for the quick response.

**Comment by AA-Turner** [comment]
For ordered set behaviour, I tend to use ``list(dict.fromkeys(...))``.
