### ISSUE TITLE
Difference in behavior between -b and -M of sphinx-build

### ISSUE THREAD

**Issue by twodrops** [sphinx-doc/sphinx#10422]
### Describe the bug

sphinx-build, as per the documentation, supports two options to use builders.
[-b](https://www.sphinx-doc.org/en/master/man/sphinx-build.html#cmdoption-sphinx-build-b) and [-M](https://www.sphinx-doc.org/en/master/man/sphinx-build.html#cmdoption-sphinx-build-M).

Both options seems to behave in slightly different ways.

"-b html" for example, creates pickles in ".doctrees" folder and the output is created directly in the build folder.

"-M html" for example, creates pickles in "doctrees" (without a dot) folder and the output is created under a subfolder "html" in the build folder.

If different sphinx tools trigger builds in the same workspace using "-b" and "-M" it affects,
1. the incremental behavior of sphinx (because of two different doctrees folders)
and 
2. the output is produced twice (once directly under build and another one at build/html)

Sphinx API seems to be have "-M" as the default. Pickles is created in "doctrees" folder.

self.sphinx = sphinx.application.Sphinx( 
   ... 
    buildername="html", 
   ... 
 )

Also [sphinx-quickstart](https://www.sphinx-doc.org/en/master/man/sphinx-quickstart.html), creates a Makefile with "-M", but the [getting-started](https://www.sphinx-doc.org/en/master/usage/quickstart.html#running-the-build) documentation talks about using "-b".

This is unfortunately, highly confusing to know which option to use as the best default across tools. See discussion [here](https://github.com/swyddfa/esbonio/issues/373) for example.

### How to Reproduce

See above

### Expected behavior

* '-M' and '-b' and Sphinx-API (defaults) are consistent
* Sphinx documention is consistent

### Your project

-

### OS

WSL2 with Ubuntu 22.04

### Python version

3.8.10

### Sphinx version

4.5.0

**Comment by AA-Turner** [comment]
This isn't a bug, but a different API. See the [docs for make-mode](https://www.sphinx-doc.org/en/master/man/sphinx-build.html#cmdoption-sphinx-build-M).

We coud change `-b` to go into a directory, but that would be a breaking change and e.g. tools expecting the default location would fail.

> `which option to use as the best default across tools` 

We should improve the documentation here and be more opinionated.

A

**Comment by twodrops** [comment]
@AA-Turner Thanks for your quick response.

I understand that make-mode behaves differently. Is this intentional that doctree and output folder naming are different in make-mode or is the difference in behavior more historical?

I also understand that it will be tough to make these breaking changes. Hence I would not recommend it either.

- According to the [sphinx-build documentation](https://www.sphinx-doc.org/en/master/man/sphinx-build.html), `-b` is preferred (as `-M` is mentioned in the second position as alternative)
- If someone uses `sphinx-quickstart`, then they have a project using `-M`

If we want to start with a tool newly and and ensure the best compatiblity to the output structure, would you recommend `-b` or '-M'?

**Comment by AA-Turner** [comment]
`doctrees` (no leading full stop) was in the [first make-mode commit ](https://github.com/sphinx-doc/sphinx/commit/91d92be8adae2e44e1e23e1c07b7088c35261abf).

We would need to make the following three usages consistent (one is just a help message):

https://github.com/sphinx-doc/sphinx/blob/21fb2caad662f83610f3889864acebe45fe3fef4/sphinx/cmd/make_mode.py#L142

https://github.com/sphinx-doc/sphinx/blob/21fb2caad662f83610f3889864acebe45fe3fef4/sphinx/cmd/build.py#L207-L208

https://github.com/sphinx-doc/sphinx/blob/21fb2caad662f83610f3889864acebe45fe3fef4/sphinx/cmd/build.py#L139

@tk0miya is there time to get this change into 5.0? The first beta hasn't been released yet.

> ensure the best compatiblity to the output structure

Not entirely sure what you mean here, but for stability, I'd specify every argument explicitly. If you're just asking `sphinx-build -b` vs `sphinx-build -M`, personally I'd say that `-M` is a better design. 

A

**Comment by AA-Turner** [comment]
> Your recommendation, if I understand correctly, would be `-M` right?

Yep, especially if you're using multiple tools -- say tool A outputs PDFs with one of the TeX builders and tool B outputs HTML, they can both read from a shared doctree directory and then output into independent folders, making it easier to tell which tool generated what.

A
