### ISSUE TITLE
property domain not working

### ISSUE THREAD

**Issue by psifertex** [sphinx-doc/sphinx#10424]
### Describe the bug

According to: https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html I should be able to use:

```
:py:property:`Class.prop`
``` 
to link to a documented property. I have done similar with `:py:met:` and `:py:class:` without issue, but when I try (on version 4.5 -- which supposedly supports this domain) I get the error:
```
docstring of binaryninja.function.Function.llil_instructions:3: ERROR: Unknown interpreted text role "py:property
```

Exact python is:

```
	@property
	def llil_instructions(self) -> Generator['lowlevelil.LowLevelILInstruction', None, None]:
		"""
		.. note:: Use :py:property:`LowLevelIlFunction.instructions` instead.
		"""
		return self.llil.instructions
```

### How to Reproduce

See description above for reproduction steps.

### Expected behavior

The property should be linked. 

### Your project

https://github.com/Vector35/binaryninja-api/tree/dev/api-docs

### OS

Mac

### Python version

Python 3.10.4 (MacPorts)

### Sphinx version

sphinx-build 4.5.0

### Sphinx extensions

autodoc, autosummary, intersphinx, viewcode

**Comment by tk0miya** [comment]
We don't provide a special role to refer a property. Please use `:py:attr:` to refer a property.
https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#role-py-attr

**Comment by AA-Turner** [comment]
There is a `.. py:property:` *directive*, but no role for inline text. 

@psifertex did you explicitly want to use a role here, rather than a directive?

xref: https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#directive-py-property

A

**Comment by psifertex** [comment]
Ahh, looks like attr is indeed what I needed. Sorry for not understanding the documentation. I guess it was a bit unclear to me which was which.
