### ISSUE TITLE
我这边使用group by的是后没法对字段使用count(*) as num 来计数排行吗?

### ISSUE THREAD

**Issue by jishuXiaom** [sphinx-doc/sphinx#10420]
### Describe the bug

我这边用 api 或者 mysqli 方式 使用group by的是后没法对字段使用count(*) as num 来计数排行吗?

### How to Reproduce

```
$ git clone https://github.com/.../some_project
$ cd some_project
$ pip install -r requirements.txt
$ cd docs
$ make html SPHINXOPTS="-D language=de"
$ # open _build/html/index and see bla bla
```

### Your project

phinxx

### OS

Linux

### Python version

7

### Sphinx version

3.4.1

### Additional context

我这边使用group by的是后没法对字段使用count(*) as num 来计数排行吗?

**Comment by tk0miya** [comment]
I can't read Chinese (Am I correct?) at all. So please post your trouble in English.

At a first glance, you mentioned MySQL and SQL. But Sphinx is not related to both of them at all. I'm afraid you're using Sphinx search, not Sphinx. Please check your software.
