### ISSUE TITLE
Show repr of the value in warnings

### ISSUE THREAD

**Issue by ezio-melotti** [sphinx-doc/sphinx#10438]
### Describe the bug

A markup like `` :ref:`Python <test >` `` results in this warning: `WARNING: undefined label: test `.
By looking at it in the terminal it's difficult to notice the trailing space.
By using the `repr` of the value instead, the warning will show `WARNING: undefined label: 'test '`.

### How to Reproduce

```
:ref:`Python <test >`
```

### Expected behavior

`WARNING: undefined label: 'test '` instead of `WARNING: undefined label: test `.

### Your project

-

### OS

Linux

### Python version

3.10

### Sphinx version

Sphinx v4.5.0

### Additional context

https://github.com/sphinx-contrib/sphinx-lint/pull/27#discussion_r867758258

**Comment by tk0miya** [comment]
We can use a single quote for the label. So the "repr" form is a bit confusable. I'm not sure what is better message for a label including a single quote.

This is an example using `repr()`:
```
/Users/tkomiya/work/tmp/doc/index.rst:6: WARNING: undefined label: "i\'m happy"
```

**Comment by ezio-melotti** [comment]
See https://github.com/sphinx-doc/sphinx/pull/10439#issuecomment-1126682721.

**Comment by AA-Turner** [comment]
#10439
