### ISSUE TITLE
sphinx.ext.extlinks doesn’t work for epub

### ISSUE THREAD

**Issue by christoph-moder** [sphinx-doc/sphinx#10433]
### Describe the bug

Links are not replaced using the epub builder; in the EPUB document the raw markup like `':linkname: linktext <linktarget.html>'` appears.

With the html and latex builders everything works fine.

### How to Reproduce

```
$ # write *.rst file with extlinks link replacement
$ make epub
$ # open _build/epub/file.epub
```

### Expected behavior

The link is replaced as defined in conf.py.

### Your project

https://gitlab.com/cmoder/velomobil-grundwissen

### OS

Linux

### Python version

3.10.4

### Sphinx version

4.5.0

### Sphinx extensions

sphinx.ext.extlinks

**Comment by tk0miya** [comment]
It works fine on my local. Could you share a minimal reproducible example, please?

**Comment by christoph-moder** [comment]
You are totally right. I have chased this problem for months before submitting this issue; however, it turned out to be a problem in my Makefile.

=> Sorry for reporting, there is no bug.
