### ISSUE TITLE
imghdr is deprecated and slated for removal in Python 3.13

### ISSUE THREAD

**Issue by domdfcoding** [sphinx-doc/sphinx#10440]
### Describe the bug

The `imghdr` module is deprecated in Python 3.11 by [PEP 594](https://peps.python.org/pep-0594/#imghdr) and is slated for removal in Python 3.13. 

`imghdr` is used here to guess image mimetypes:
https://github.com/sphinx-doc/sphinx/blob/31eba1a76dd485dc633cae48227b46879eda5df4/sphinx/util/images.py#L50-L55

The `imghdr` code is not very large (see [here](https://github.com/python/cpython/blob/main/Lib/imghdr.py)). It could either be vendored by Sphinx or pulled out to a package on PyPI if there's no alternative.

### Python version

Python 3.11.0.beta1

**Comment by tk0miya** [comment]
Now we're using the `imagesize` package to obtain the image file size. It's better to extend it to detect the type of image.
https://pypi.org/project/imagesize/

And it's much better to use the `Pillow` package as a fallback when the `imagesize` can't detect the type.

**Comment by trevorbaca** [comment]
Hi,

With the public release of Python 3.11, the deprecation warning for `imghdr` is now showing up.

Any idea when `imghdr` might be removed?

Thanks!

**Comment by hugovk** [comment]
imghdr was removed in https://github.com/sphinx-doc/sphinx/commit/a502e7523376e0344c1c9cc8a9d128143cd98b2d (no PR) and released in [v6.2.0](https://github.com/sphinx-doc/sphinx/releases/tag/v6.2.0) :rocket:

**Comment by AA-Turner** [comment]
I had forgotten about this issue -- thanks for the reminder Hugo!

A
