### ISSUE TITLE
How to add an explicit reference with nodes.reference in 

### ISSUE THREAD

**Issue by dachym** [sphinx-doc/sphinx#10448]
### Describe the bug

Hello,

I'm sorry to post in the bug label, but I didn't have found a solution anywhere. I want to make a directive which gets all docstring with a directive "class_directive:: ClassToMap" like in my example.py in this repository https://github.com/dachym/sphinx_create_reference.
Once, I got this directive via my extension class_mapper with ClassDirective , I want to create another directive ClassListDirective which list all those classes and create a reference to the mapping documentation (in my case 

### How to Reproduce

```
$ git clone https://github.com/dachym/sphinx_create_reference
$ cd sphinx_create_reference
$ make html
$ # open build/html/class_list.html
```

### Expected behavior

Once I have opened my class_list.html, I have two link. The first "ClassToMap documentation" is created with my line code in class_mapper.py 
`para += nodes.reference(internal=False, refid=f"ClassToMap_documentation",
                                    text=f"ClassToMap documentation")` 
I thought that code create an explicit reference to the example.rst which contains `.. _ClassToMap-documentation`, but it just create a reference in the current file (class_list.html).
The second link "Example" doest what I want, I just want to know how to parametrize nodes.reference to make this kink of link.
I didn't find anything in Docutils documentation.

### Your project

https://github.com/dachym/sphinx_create_reference

### OS

Unix/Win

### Python version

3.10.4

### Sphinx version

4.5.0

**Comment by AA-Turner** [comment]
Hi Dachym,

Your question / bug report is very unclear. What is `ClassToMap`? Please can you simplify your explanation, and post a mimimal example of what you are trying, how it doesn't work or where you're stuck, and what you expect as output.

Thanks,
A

**Comment by AA-Turner** [comment]
Mathieu -- the below is a new `class_mapper.py`. 

As you're using cross-document links, it is easier to use `sphinx.addnodes.pending_xref`. Similarly, I'd advise doing the list of references transformation in a single document transform after reading all documents has finished, which means that you don't need to mess with merging environment information etc.

Ideally you might be able to hook into `autodoc` and get the qualname of the class automatically for documentation, but that is an exercise for later.

A

```python
from docutils import nodes
from docutils.parsers.rst import Directive

from sphinx import addnodes
from sphinx.util.docutils import SphinxDirective
from sphinx.transforms.post_transforms import SphinxPostTransform


class ClassListPending(nodes.General, nodes.Element):
    pass


def class_name_to_target(class_name: str) -> str:
    """Needs to be globally unique, so prefix"""
    return f"class-mapper-target--{class_name.lower()}"


class ClassListDirective(Directive):
    @staticmethod
    def run():
        return [ClassListPending("")]


class ClassDirective(SphinxDirective):
    # this enables content in the directive
    has_content = True

    def run(self):
        class_name = "".join(self.content).strip()
        self.env.class_names_list.append(class_name)  # NoQA

        # Create a new target node
        target = nodes.target(
            '', '', 
            ids=[class_name_to_target(class_name)], 
            names=[class_name_to_target(class_name)]
        )

        # Update the document with the new target (imperative note)
        self.state.document.note_explicit_target(target)

        # Add the target to the top of the document tree
        self.state.document.insert(0, target)
        return []


def initialise_class_all_classes(app):
    app.env.class_names_list = []


class ClassListTransform(SphinxPostTransform):
    default_priority = 5

    def run(self, **kwargs) -> None:
        for node in self.document.findall(ClassListPending):
            ref_nodes = []
            for class_name in self.app.builder.env.class_names_list:
                ref_node = addnodes.pending_xref(
                    "", 
                    nodes.inline(
                        "", 
                        f"Documentation for {class_name}", 
                        classes=["xref", "std", "std-ref"],  # copied from ``:ref:``
                    ),
                    refdoc=self.env.docname,
                    refdomain="std",
                    refexplicit=False,
                    reftype='ref',
                    reftarget=class_name_to_target(class_name),
                    refwarn=True,
                )
                ref_nodes.append(ref_node)
            node.replace_self(nodes.paragraph("", "", *ref_nodes))


def setup(app):
    def noop(self, node):  # NoQA
        """A do-nothing function."""

    # The ``ClassListPending`` node does nothing and serves as a marker for later
    # use.
    app.add_node(
        ClassListPending,
        html=(noop, noop),
        latex=(noop, noop),
        text=(noop, noop),
    )

    # The ``class_directive`` directive is used within the docstrings of classes
    # that we want to centrally list. It must be used with the class name as the
    # only directive content.
    app.add_directive('class_directive', ClassDirective)

    # The ``class_list_doc`` directive produces a list of references to the
    # classes in a two stage process. This first stage inserts a
    # ``ClassListPending`` node into the document as a placeholder.
    app.add_directive('class_list_doc', ClassListDirective)

    # We create the ``class_names_list`` attribute on the BuildEnvironment class
    # in this function
    app.connect('builder-inited', initialise_class_all_classes)

    # The ClassListTransform is the second and final stage of producing the list
    # of references. It finds all ``ClassListPending`` nodes and replaces them
    # with a list of references to classes generated from the names stored in
    # ``app.env.class_names_list``.
    app.add_post_transform(ClassListTransform)

    return {'parallel_read_safe': True, 'parallel_write_safe': True}
```

**Comment by dachym** [comment]
Hi Adam,

Thanks a lot for your quick and fast response. It works perfectly and your explanations are very clear.

Regards,

Mathieu
