### ISSUE TITLE
Equation render failed

### ISSUE THREAD

**Issue by chaoming0625** [sphinx-doc/sphinx#10459]
### Describe the bug

I found the eqution render failed in many documentation using sphinx. Like:

- https://jax.readthedocs.io/en/latest/jax-101/04-advanced-autodiff.html
- https://brainpy.readthedocs.io/en/brainpy-1.x/apis/simulation/generated/brainpy.simulation.layers.GRU.html

I don't know why?

### How to Reproduce

```
$ git clone https://github.com/.../some_project
$ cd some_project
$ pip install -r requirements.txt
$ cd docs
$ make html SPHINXOPTS="-D language=de"
$ # open _build/html/index and see bla bla
```

### Your project

https://brainpy.readthedocs.io/en/brainpy-1.x/apis/simulation/generated/brainpy.simulation.layers.GRU.html

### OS

Linux

### Python version

3.10

### Sphinx version

latest

**Comment by tk0miya** [comment]
Could you explain how it failed in detail, please? On my browser, it looks good.
<img width="738" alt="スクリーンショット 2022-05-22 16 06 12" src="https://user-images.githubusercontent.com/748828/169683226-db72f10f-55ed-4d43-8856-d5225fddab6c.png">

**Comment by chaoming0625** [comment]
I also got the same results in Chrome. However, when I turn on no-trace mode. I got

![image](https://user-images.githubusercontent.com/14275596/169683507-a18f5b59-0917-4b7b-b77e-b6092bb19a00.png)


Similarly, this is the screen shot of Edge browser:

![image](https://user-images.githubusercontent.com/14275596/169683409-2b2baf1c-cf62-49e8-8f77-a6c243dbcfc9.png)

**Comment by chaoming0625** [comment]
At least in many browers of my colleagues, the render of these equations failed.

**Comment by chaoming0625** [comment]
Another interesting thing is that using the Chrome browser on my another laptop, the equations also rendered failed. I cannot explain why only the Chrome on this computer works.

**Comment by chaoming0625** [comment]
I found this is because **MathJax** cannot load when open these webpages. This problem may only occur in **China**. There are some Chinese forums starting to discuss this issue. 

- https://www.zhihu.com/question/481937430

But I am wondering are there same problem encountered by netizen in other country?
