### ISSUE TITLE
Package inputenc Error: Unicode character ⏚ (U+23DA) with pdflatex

### ISSUE THREAD

**Issue by LuisBL** [sphinx-doc/sphinx#10469]
### Describe the bug

I have ⏚ (U+23DA) in my rst file and want to create a pdflatex

## sphinx index.rst and main file content

```
(venv) luis@spinoza:/tmp/s$ tree
.
├── _build
├── conf.py
├── index.rst
├── make.bat
├── Makefile
├── _static
├── _templates
└── vagrant.rst


(venv) luis@spinoza:/tmp/s$ cat index.rst 
Welcome to u23DA's documentation!
=================================

.. toctree::

   vagrant.rst
(venv) luis@spinoza:/tmp/s$ 



(venv) luis@spinoza:/tmp/s$ cat vagrant.rst 
Title
======
::

  $ ssh -i /home/luis/.vagrant.d/insecure_private_key -p 2222 vagrant@localhost
  vagrant@localhost's password: vagrant
  ⏚ [vagrant@blumug:~] $
  ⏚ [vagrant@blumug:~] $
(venv) luis@spinoza:/tmp/s$ 
```

## conf.py

```
(venv) luis@spinoza:/tmp/s$ grep -E 'extensions =|latex' conf.py 
extensions = []
latex_elements = {'preamble': r"\usepackage{pmboxdraw}"}
(venv) luis@spinoza:/tmp/s$ 
```
Releted to : # pmboxdraw Cf. https://github.com/sphinx-doc/sphinx/issues/3851

## Then run `latexpdf` get the error:

```
$ make latexpdf
...
Chapter 1.
(/usr/share/texlive/texmf-dist/tex/latex/txfonts/t1txtt.fd)
(/usr/share/texlive/texmf-dist/tex/latex/txfonts/ts1txtt.fd)

! Package inputenc Error: Unicode character ⏚ (U+23DA)
(inputenc)                not set up for use with LaTeX.
```

### Expected behavior

no error with latexpdf

### Your project

attached zip 
[u23DA.zip](https://github.com/sphinx-doc/sphinx/files/8750071/u23DA.zip)
```
(venv) luis@spinoza:/tmp/u23DA$ tree
.
├── _build
├── _conf.py
├── conf.py
├── index.rst
├── make.bat
├── Makefile
├── _static
├── _templates
└── vagrant.rst
(venv) luis@spinoza:/tmp/u23DA$
```

### OS

Linux Ubuntu 20.04

### Python version

3.8.10

### Sphinx version

5.1.0+/36367765f

### Additional context

related to #3851

**Comment by AA-Turner** [comment]
What is the content of the generated `.tex` file in the `latex` directory?

A

**Comment by jdillard** [comment]
> If your project uses Unicode characters, setting the engine to 'xelatex' or 'lualatex' and making sure to use an OpenType font with wide-enough glyph coverage is often easier than trying to make 'pdflatex' work with the extra Unicode characters. 

https://www.sphinx-doc.org/en/master/usage/configuration.html?highlight=latex_engine#confval-latex_engine

**Comment by AA-Turner** [comment]
Closing as it seems you should use `XeTeX` or similar.

A

**Comment by LuisBL** [comment]
Yes sorry with xelatex it work very well

```
$ grep xelatex conf.py 
# xelatex to solve Unicode problems https://github.com/sphinx-doc/sphinx/issues/4159
latex_engine = 'xelatex'
$
```
