### ISSUE TITLE
How to document R functions (.Rd or .R)?

### ISSUE THREAD

**Issue by sistia01** [sphinx-doc/sphinx#10475]
I've seen a lot of information about documenting python functions but have not seen anything for documenting R functions in a similar manner? 

I'm trying to create documentation for R functions that I have that will be automatically updated as I update the functions (similarly to what [Squidpy](https://squidpy.readthedocs.io/en/stable/api/squidpy.gr.spatial_neighbors.html#squidpy.gr.spatial_neighbors) does with python). 

Repo: [https://github.com/sistia01/Giotto](https://github.com/sistia01/Giotto)

**Comment by tk0miya** [comment]
Yes. Sphinx allows enhancing features via 3rd party extension. So it would be nice if somebody will create an extension for R language.

Thanks,
