### ISSUE TITLE
Bionic Reading support

### ISSUE THREAD

**Issue by martinlanton** [sphinx-doc/sphinx#10477]
Problem :
As many developer, I am often frustrated by reading documentation in general because of how verbose and boring it is (although absolutely essential to our job), as well as how long it takes.

Solution :
A support of Bionic Reading could help make documentation easier and faster to read, as well as making information easier to understand.

Example : 
https://bionic-reading.com/

**Comment by AA-Turner** [comment]
From a typographic perspective, certainly an *interesting* treatment to text.

This won't be implemented in core Sphinx though. I'd suggest creating an extension, although be wary of the many notices around patent protection etc on the website.

A
