### ISSUE TITLE
Links ending with an underscore are compiled as references

### ISSUE THREAD

**Issue by POMIN-163** [sphinx-doc/sphinx#10485]
### Describe the bug

* An error appears at compile time, it is “ERROR: Unknown target name: "pomin".”.
* I want add a herf: <https://blog.csdn.net/pomin_>, but it is compiled a "reference".
* I get an error when one of my hyperlinks ends with "_".
* I guess it's because the priority of the "reference" is higher than the priority of the "hyperlink", which causes the error.

### How to Reproduce

Error when adding a hyperlink with "_" at the end.

### Your project

a herf: <https://blog.csdn.net/pomin_>

### OS

WSL (Ubuntu18.04)

### Python version

3.8

### Sphinx version

v5.0.0b1

**Comment by AA-Turner** [comment]
See the end of 'hyperlink targets' -> 'external hyperlink targets' (item 2) in the reStructuredText specification: https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#explicit-hyperlink-targets

> If an external hyperlink target's URI contains an underscore as its last character, it must be escaped to avoid being mistaken for an indirect hyperlink target

A
