### ISSUE TITLE
Incomplete type hints for Sphinx.__init__

### ISSUE THREAD

**Issue by Cielquan** [sphinx-doc/sphinx#10483]
### Describe the bug

According to the type hints for the `sphinx.application.Sphinx.__init__` method the `status` and  `warning` parameters only take values of type `IO`, but inside the method's body both parameters are checked for `None`.

### How to Reproduce

See latest commit on `master`: fffba7b73d3456bb235f6e4c5ed74d0a638bc6c7

On [line 132](https://github.com/sphinx-doc/sphinx/blob/fffba7b73d3456bb235f6e4c5ed74d0a638bc6c7/sphinx/application.py#L132) you can see the types:
```python
...
status: IO = sys.stdout, warning: IO = sys.stderr,
...
```

On [line 162](https://github.com/sphinx-doc/sphinx/blob/fffba7b73d3456bb235f6e4c5ed74d0a638bc6c7/sphinx/application.py#L162) you can see the `status` none check:
```python
...
if status is None:
...
```

On [line 169](https://github.com/sphinx-doc/sphinx/blob/fffba7b73d3456bb235f6e4c5ed74d0a638bc6c7/sphinx/application.py#L169) you can see the `warning` none check:
```python
...
if warning is None:
...
```

### Expected behavior

Shouldn't the type hints be `Optional[IO]`?

EDIT: I would provide a PR to fix this.

### Your project

https://github.com/rstcheck/rstcheck

### OS

Linux

### Python version

3.8.10

### Sphinx version

master and 5.x branch

### Additional context

Over at rstcheck we have optional support for rst source which is used with the sphinx documentation builder. For this support we need to create an instance of the `sphinx.application.Sphinx` class.

I took over the maintainership of the project and added typing to it. That was when mypy showed me a type error for the `status` argument to the `Sphinx.__init__` method. After I looked into sphinx's source I found this issue.

As you can see in this [blame view of rstcheck v3.3.1](https://github.com/rstcheck/rstcheck/blame/v3.3.1/rstcheck.py#L898) (the last version before I took over) `status=None` is used for at least 6 years on our side.

**Comment by tk0miya** [comment]
Thank you for reporting. Will be fixed by #10488.

Note: At present, our type annotations do not use "Optional" well. So we should update them as possible .
