### ISSUE TITLE
Typo in new language warning

### ISSUE THREAD

**Issue by pquentin** [sphinx-doc/sphinx#10491]
### Describe the bug

See the following snippet:

https://github.com/sphinx-doc/sphinx/blob/e1bf4dd5d5860a4c3790f41c5f5fe389dc5b4cf9/sphinx/config.py#L167-L174

Both `langugae` and `langauge` are used incorrectly.

### How to Reproduce

Noticed in Read the Docs: https://readthedocs.org/projects/trustme/builds/17039627/

### Expected behavior

Mention "language" without typos.

### Your project

https://github.com/python-trio/trustme/tree/master/docs

**Comment by AA-Turner** [comment]
Fix is in #10492 - this is just a cosmetic issue as the actual code spells "language" correctly.

A

**Comment by oleksiyskononenko** [comment]
What about all the `sphinx.po` files for different locales? They all still have the typo, for instance, https://github.com/sphinx-doc/sphinx/blob/5.x/sphinx/locale/ar/LC_MESSAGES/sphinx.po#L178

Are these files autogenerated based on `config.py` somehow? If not, should they all be fixed too?

**Comment by AA-Turner** [comment]
Every Sunday. (https://github.com/sphinx-doc/sphinx/actions/workflows/transifex.yml)

A
