### ISSUE TITLE
Human-readable version of objects.inv missing

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1052]
It would be very handy to have a human-readable version of objects.inv. Or at least a list of available link targets.

I think it would really help intersphinx usage to gain steam, especially now that readthedocs.org is starting to become the standard place for python documentation. More links between the projects would be great.

But at the moment browsing through the other projects' doc source is a bit tedious, trying to find the proper link target :-)

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1052
- Originally reported by: Reinout van Rees
- Originally created at: 2012-12-04T12:52:01.905

**Comment by shimizukawa** [comment]
_From Michael Schlenker on 2012-12-04 14:50:14+00:00_

Try this snippet:

```
:::python
   import sys
   from sphinx.ext import intersphinx

   class DummyApp(object):
         srcdir = "."

         def warn(self, msg):
               sys.stderr.write("%s\n" % msg)

   def main():
         app = DummyApp()
         # baseurl to use
         uri = ""
         inv = sys.argv[1]
         inventory = intersphinx.fetch_inventory(app, uri, inv)
         for k in inventory.keys():
              print "Type: %s" % k
              for name, value in inventory[k].items():
                    print "  %s -> '%s'" % (name, value[2])

   return 0

if __name__ == "__main__":
    sys.exit(main())
```

**Comment by shimizukawa** [comment]
_From Jon Waltman on 2012-12-04 19:57:16+00:00_

I've written a script like the above as well.

This functionality could be added directly to intersphinx allowing you to do something like this:

```
$ python -m sphinx.ext.intersphinx path/to/objects.inv
```

**Comment by shimizukawa** [comment]
_From Reinout van Rees on 2012-12-04 20:06:24+00:00_

Well, you shouldn't need to point at an objects.inv on the commandline, right? There are two other options that are a bit easier:
- Such a script/command could use conf.py just like sphinx itself and print a list of all available link targets for all the configured intersphinxes. That can even be handy to debug your intersphinx conf.py setting :-)
- Sphinx could perhaps generate an objects.txt next to the objects.inv.

(The first one sounds the least intrusive, btw)

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2012-12-07 07:56:03+00:00_

Hum.. I think link-targets list is needed for the external intersphinx user. The user is time-consuming to get the list of in using command-line way.

> - Sphinx could perhaps generate an objects.txt next to the objects.inv.

I prefer it.
I think better when objects.txt is linked from the page.

And I propose other options too:
- "show link targets" at side menu provide link targets text file as the "show source".
- sphinx-build will auto generate link targets page as the index page.

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2014-01-12 23:16:44+00:00_

Something like this sounds good.

Intersphinx is easy with Python objects, but for :ref:s it's tricky to discover.

**Comment by eric-wieser** [comment]
> This functionality could be added directly to intersphinx allowing you to do something like this:
>
>      $ python -m sphinx.ext.intersphinx path/to/objects.inv

Isn't this implemented already? Stackoverflow seemed to think so

**Comment by tk0miya** [comment]
Indeed, it seems already added.
I'm closing this.
