### ISSUE TITLE
Double brackets in footnote references (docutils 0.18?)

### ISSUE THREAD

**Issue by mgeier** [sphinx-doc/sphinx#10522]
### Describe the bug

See https://github.com/sphinx-doc/sphinx/issues/10415#issuecomment-1146642591, that issue also has screenshots.

### How to Reproduce

x

### Your project

x

### OS

x

### Python version

x

### Sphinx version

x

**Comment by mgeier** [comment]
Very annoying new bug report template, BTW.

**Comment by AA-Turner** [comment]
My reply from #10457 

One set [of brackets] is in the HTML source, ``<span class="fn-bracket">[</span>``. The other is added in CSS:

https://github.com/sphinx-doc/sphinx/blob/af425c069f6f51ba8fb3c348fd53479f0434a779/sphinx/themes/basic/static/basic.css_t#L240-L248

We should only use the CSS brackets if `span.fn-bracket` is absent.

A

**Comment by AA-Turner** [comment]
Example: https://www.sphinx-doc.org/en/master/usage/advanced/intl.html#sphinx-internationalization-details

**Comment by AA-Turner** [comment]
Quick reproducer:

```python
import shutil
from pathlib import Path

from sphinx.cmd.make_mode import run_make_mode


def write(filename, text): Path(filename).write_text(text, encoding="utf-8")


write("conf.py", '''\
html_theme = "basic"
''')

write("index.rst", '''\
Imagine you have Spanish translations [2]_.

.. [2] Because nobody expects the Spanish Inquisition!
''')

shutil.rmtree("_build", ignore_errors=True)
run_make_mode(["html", ".", "_build", "-T", "-W"])
```

A

**Comment by AA-Turner** [comment]
Can't reproduce on Docutils 0.17.1, this is a 0.18.* issue.
