### ISSUE TITLE
Inline literal error with trailing whitespaces

### ISSUE THREAD

**Issue by Helveg** [sphinx-doc/sphinx#10537]
### Describe the bug

When I use the ` `` `` `, the value ` ``config =`` ` works, but ` ``config = `` ` (note the trailing whitespace) yields the following warning:

```
C:\Users\pwd06\git\bsb\docs\usage\projects.rst:60:Inline literal start-string without end-string.
```

### How to Reproduce

1. Put ` ``config = `` ` in `index.rst`
2. Build

### Expected behavior

Renders `config = ` with a trailing whitespace

### Your project

N/A

### OS

Windows

### Python version

3.9

### Sphinx version

4.5

**Comment by tk0miya** [comment]
AFAIK, reST syntax does not support a literal string ends with whitespace. That is a limitation of the mark-up language. It's difficult to support it from Sphinx side.

**Comment by AA-Turner** [comment]
It is a reStructuredText bug, yes.

A
