### ISSUE TITLE
Missing CSS for nav.contents (docutils 0.18)

### ISSUE THREAD

**Issue by mgeier** [sphinx-doc/sphinx#10534]
### Describe the bug

Previously, `docutils` produced `div.topic` for the `contents` directive, the latest version produces `nav.contents`.

This means that those tables of contents change appearance when switching to `docutils` 0.18.

### How to Reproduce

Look at the table of contents at https://www.sphinx-doc.org/en/master/usage/installation.html.

### Expected behavior

This is how it looked previously: https://web.archive.org/web/20220414010730/https://www.sphinx-doc.org/en/master/usage/installation.html

### Your project

x

### OS

x

### Python version

x

### Sphinx version

x

**Comment by AA-Turner** [comment]
Seems my fix worked: https://sphinx--10535.org.readthedocs.build/en/10535/usage/installation.html

A

**Comment by mgeier** [comment]
Yes, thanks!
