### ISSUE TITLE
inventory.py does not check type of 'version' config var

### ISSUE THREAD

**Issue by jaseg** [sphinx-doc/sphinx#10544]
### Describe the bug

I have a project in which I use the default templated conf.py. In my conf.py, I decided to generate the `release` variable automatically from git by calling a small helper function. I called this helper function `version`, thereby shadowing the `version` config var. This lead to sphinx'es inventory.py choking with the attached stack trace and unhelpful error message.

### How to Reproduce

Just use any conf.py, and set version to something other than a string or bytes object, e.g. `version = lambda x: None`

### Expected behavior

Two things:
1. In the default conf.py template, it would be good if there was a comment that `version` is a reserved variable name, even if it is not used in the template invocation.
2. In inventory.py, it would be good to add a check that `version` is in fact a string, and give a verbose error message in case it is not.

### Your project

https://gitlab.com/gerbolyze/gerbonara/

### Screenshots

https://gitlab.com/gerbolyze/gerbonara/-/jobs/2576333109
Error log: [sphinx-err-_uvliwtf.log](https://github.com/sphinx-doc/sphinx/files/8882249/sphinx-err-_uvliwtf.log)

### OS

linux

### Python version

3.10.4 (cpython)

### Sphinx version

5.0.0

### Sphinx extensions

autodoc

**Comment by AA-Turner** [comment]
PR welcome.

A

**Comment by tk0miya** [comment]
As I commented at https://github.com/sphinx-doc/sphinx/pull/10549#issuecomment-1157973147, Sphinx already detects invalid value is given as `version` and emits a warning. So I think no additional work is not needed. If you'd like to halt the Sphinx on the detection, please consider to use `-W` option.

**Comment by jaseg** [comment]
Lol, somehow I managed to not notice that warning *at all*. What I take from that is that that warning should be a hard crash instead. Given that a crash is going to happen regardless, might as well have a useful error message. If I find the time I might send you another PR.

**Comment by AA-Turner** [comment]
> Given that a crash is going to happen regardless, might as well have a useful error message. If I find the time I might send you another PR.

I'll defer to @tk0miya-san here - I'm maybe +0.

A
