### ISSUE TITLE
Jupyter Notebook Support for EPUB

### ISSUE THREAD

**Issue by Zeitsperre** [sphinx-doc/sphinx#10552]
**Is your feature request related to a problem? Please describe.**

When a project contains Jupyter Notebooks, when creating a downloadable EPUB file, there are numerous warnings stating that their mimetype is unknown and will thus be ignored. E.g.:
```
WARNING: unknown mimetype for notebooks/x.ipynb, ignoring
WARNING: unknown mimetype for notebooks/y.ipynb, ignoring
WARNING: unknown mimetype for notebooks/z.ipynb, ignoring
```
**Describe the solution you'd like**

I would like to see support for Jupyter Notebooks to be parsed and presented in EPUB files.

**Describe alternatives you've considered**

Existing issues have sidestepped this problem in their doc builds by ignoring EPUB altogether:
https://github.com/sphinx-doc/sphinx/issues/10350
https://github.com/sphinx-doc/sphinx/issues/3214

The nbconvert repo users suggest a very labour-intensive workaround:
https://github.com/jupyter/nbconvert/issues/1213

**Comment by AA-Turner** [comment]
> I would like to see support for Jupyter Notebooks to be parsed and presented in EPUB files.

We (Sphinx core) don't support notebooks. @chrisjsewell does https://github.com/executablebooks/MyST-NB work with ePub?

A

**Comment by chrisjsewell** [comment]
> @chrisjsewell does [executablebooks/MyST-NB](https://github.com/executablebooks/MyST-NB) work with ePub?

Yes, it does 👍, and you can customise mime-type handling of code outputs  https://myst-nb.readthedocs.io/en/latest/render/format_code_cells.html

However, these warnings appear to be coming from sphinx itself (i.e. #3214), which is maybe unrelated to the fact that it is a Jupyter notebook?

FYI @AA-Turner myst-nb also now has a docutils parser: https://myst-nb.readthedocs.io/en/latest/docutils.html

**Comment by AA-Turner** [comment]
Yeah, Chris is right -- @Zeitsperre you can add `suppress_warnings = ["epub.unknown_project_files"]` to your `conf.py` to entirely ignore warnings, or use a list of notebooks to exclude in `epub_exclude_files`.

> myst-nb also now has a docutils parser

Very cool! OOI was it harder to write than the Sphinx one? There are off and on discussions about Docutils' API and I think we can/should offer a better set of abstractions (potentially also making implementation details private) but change there takes time.

A

**Comment by tk0miya** [comment]
>However, these warnings appear to be coming from sphinx itself (i.e. https://github.com/sphinx-doc/sphinx/issues/3214), which is maybe unrelated to the fact that it is a Jupyter notebook?

FYI: These warnings are emitted when .ipynb files are archived to the EPUB file. Indeed, they can be suppressed via `suppress_warnings`. But it does not resolve the root cause. Because most of EPUB readers does not support .ipynb files. So the only way to fix this is using MyST-NB, I think.
