### ISSUE TITLE
Search appears to be broken at sphinx-doc.org

### ISSUE THREAD

**Issue by jfbu** [sphinx-doc/sphinx#10574]
### Describe the bug

Search does not work at <https://www.sphinx-doc.org>

### Sphinx version

master (6.0.0)

**Comment by AA-Turner** [comment]
What links are broken?

A

**Comment by jfbu** [comment]
> What links are broken?

sorry about that, I changed the title at last minute because the site appeared to be stalled on clicking on Docs link.  But it must have been a temporary connexion issue on my side.  I will edit title.

**Comment by tk0miya** [comment]
It seems the search feature of RtD does not support Sphinx-5.0. They should load jQuery explicitly.
```
readthedocs-doc-embed.js:1 Uncaught ReferenceError: $ is not defined
    at Object.get (readthedocs-doc-embed.js:1:22707)
    at Object.init (readthedocs-doc-embed.js:1:20796)
    at e (readthedocs-doc-embed.js:1:33951)
```

**Comment by tk0miya** [comment]
I merged #10582, but it still fails.

```
Uncaught TypeError: $.urlencode is not a function
    at Object.e [as query] (readthedocs-doc-embed.js:1:23257)
    at Object.performSearch (searchtools.js:234:35)
    at Object.init (searchtools.js:175:23)
    at HTMLDocument.<anonymous> (readthedocs-doc-embed.js:1:25891)
    at e (jquery.min.js:2:30038)
    at t (jquery.min.js:2:30340)
```

**Comment by tk0miya** [comment]
It seems RtD search depends on small patches in doctools. So we need to patch in sphinx-doc.org.
https://github.com/sphinx-doc/sphinx/blob/v4.5.0/sphinx/themes/basic/static/doctools.js#L30-L146

**Comment by tk0miya** [comment]
Fixed. It's working again. But the search result is collapsed. So I'll try to fix it.

**Comment by jfbu** [comment]
> Fixed. It's working again. But the search result is collapsed. So I'll try to fix it.

Great work!

**Comment by AA-Turner** [comment]
cc: @stsewd from read the docs -- are you aware of this on your end re dropping jQuery in Sphinx 6?

A

**Comment by AA-Turner** [comment]
I think this is now fixed, @jfbu can you confirm?

A

**Comment by jfbu** [comment]
> Le 20 juin 2022 à 00:21, Adam Turner ***@***.***> a écrit :
> 
> 
> I think this is now fixed, @jfbu <https://github.com/jfbu> can you confirm?
> 
> A
> 
> 

Hi, yes, and I see the RTD little pop-up window is back[1]. As per the search it appears to work but I don’t know what to expect precisely regarding the appearance of the search results, if things have changed recently, as I had not used it for some time.

[1] Although the « PDF » link leads to download of 4.0.0+/06c59d272 from more than a year ago.

**Comment by jfbu** [comment]
> 
> [1] Although the « PDF » link leads to download of 4.0.0+/06c59d272 from more than a year ago. 

forget this, on second try it is at 6.0.0...

**Comment by stsewd** [comment]
> cc: @stsewd from read the docs -- are you aware of this on your end re dropping jQuery in Sphinx 6?
> 
> A

Hi, yes, we are aware of the jquery removal, we will be prioritizing this work the following weeks.
