### ISSUE TITLE
display the line numbers using sphinx.ext.viewcode?

### ISSUE THREAD

**Issue by 12rambau** [sphinx-doc/sphinx#10589]
I'm using the [sphinx.ext.viewcode](https://www.sphinx-doc.org/en/master/usage/extensions/viewcode.html) to document my API. Is it possible to display the line numbers on the produced code-block and if yes how ?

I've tried to find an `html_option` in the docs but I didn't find anything. As this question is on stale for a month on SO, I assumed it was not available in Sphinx so I'm moving it to a feature request.

**Comment by tk0miya** [comment]
PR is welcome. Please use `add_config_value()` to add a new configuration variable.

**Comment by AA-Turner** [comment]
Closed by #6319.

A
