### ISSUE TITLE
Build failure if Docutils version is 0.18 (not 0.18.1) due to missing Node.findall()

### ISSUE THREAD

**Issue by jfbu** [sphinx-doc/sphinx#10596]
### Describe the bug

```
Exception occurred:
  File "/Users/path/to/sphinx/sphinx/transforms/__init__.py", line 204, in apply
    for node in self.document.findall():  # type: Node
AttributeError: 'document' object has no attribute 'findall'
```

### How to Reproduce

```
pip install docutils==0.18
```

then attempt ``make html`` on any Sphinx project.

### Expected behavior

No error

### Your project

any

### OS

Mac

### Python version

3.10.4

### Sphinx version

Sphinx v5.1.0+/1786e989c

### Additional context

#10044 prepared the migration.  But the Docutils 0.18 (which does not have ``Nodes.findall()`` ) is not detected:

https://github.com/sphinx-doc/sphinx/blob/20f52d9fa52363ebac60a28c81dbbc62fcc9fb27/sphinx/util/docutils.py#L552-L559

The [Docutils revision 8885](https://sourceforge.net/p/docutils/code/8885/) is part of Docutils `0.18.1` not of `0.18`.

People with Docutils version exactly at `0.18` (which is available on [pypi](https://pypi.org/project/docutils/)) and Sphinx 4.4.0 and later will encounter the problem.  Perhaps very few people will be in this situation, as `0.18.1` was released about one month after `0.18`.

**Comment by AA-Turner** [comment]
Closed in #10597

A
