### ISSUE TITLE
Ability to add links in signatures

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1059]
When generating autodoc it's not possible to insert links for the types mentioned in the docstring signature:

```
 |  mymethod(...)
 |      MyModule.mymethod(self, MyThing c, func=None) -> MyResult
```

Here it would be nice to be able to link to MyThing and MyResult. Even if it's not possible to do it automatically, you could still enclose MyResult in `` either in the source code, or via the autodoc-process-signature event. Same applies to MyThing.

If such a thing is attempted today, the `` will be shown as is in the HTML output, and no hyperlink will be generated.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1059
- Originally reported by: Daniel Svensson
- Originally created at: 2012-12-18T00:51:20.315

**Comment by wheerd** [comment]
There is an extension that does pretty much that: [sphinx-autodoc-typehints](https://github.com/agronholm/sphinx-autodoc-typehints)

**Comment by 3nids** [comment]
The extension is actually not doing what is asked, i.e. adding links within the signature. Instead, it introduces annotation where it can in the docstring.
Why can't we have links within the signature?

**Comment by tk0miya** [comment]
Simply, not implemented yet. All your support is welcome :-)

**Comment by tk0miya** [comment]
Since 3.0, Sphinx converts type-annotations in function signature to cross references (refs: #7341). I think this issue was already resolved. Closing now!

**Comment by 3nids** [comment]
awesome, thanks!
