### ISSUE TITLE
Missing type annotations in generic class description

### ISSUE THREAD

**Issue by francois-rozet** [sphinx-doc/sphinx#10605]
### Describe the bug

With `autodoc_typehints = 'description'`, the parameter type annotations of the constructor (`__init__`) of generic classes are missing from the description.

### How to Reproduce

With `autodoc_typehints = 'description'` in `conf.py`,

```python
from typing import *

#: whatever
T = TypeVar('T')

class Dummy(Generic[T]):
    r"""
    Arguments:
        arg: missing type annotation
    """

    def __init__(self, arg: str):
        pass
```

results in

<img width="275" alt="image" src="https://user-images.githubusercontent.com/37352336/175818496-76c2532f-3b23-461b-8f9d-4d22e6d415ed.png">

in which the type annotation is missing for the `arg` parameter.

### Expected behavior

The type annotations should not be missing.

### Your project

N/A

### OS

Ubuntu 20.04

### Python version

3.8.10

### Sphinx version

5.0.2

### Sphinx extensions

sphinx.ext.autodoc

### Additional context

This issue is probably related to https://github.com/sphinx-doc/sphinx/issues/8219 and https://github.com/sphinx-doc/sphinx/pull/8142.

**Comment by robsdedude** [comment]
I came across a similar issue with `autodoc_typehints = 'description'`. I'm working on a PR that will fix this and my issue.

Basically, the resolution doesn't work for constructors when `autodoc_typehints = 'description'`. So something like

```python
from __future__ import annotations

import typing as t

class Dummy():
    r"""
    Arguments:
        arg: missing type annotation
    """

    def __init__(self, arg: t.Optional[str]):
        pass
```

will also end up with a wrong type hint. In this case, it will be `t.Optional[str]` instead of `Optional[str]` which it'd be for other methods.

**Comment by francois-rozet** [comment]
Hello @robsdedude, thanks for your PR, I hope it gets merged!

> P.S. if you do a lot of `rebase`, avoid using issue identifiers in the commit message as it creates a lot of notifications 😅

**Comment by robsdedude** [comment]
Yeah, I just realized :see_no_evil: I'm sorry.

**Comment by robsdedude** [comment]
So sorry for the pings. I'll change the commit message now for goo.

**Comment by AA-Turner** [comment]
@francois-rozet is this now resolved?

**Comment by francois-rozet** [comment]
Hello @AA-Turner, yes. I tried with a more recent version of Sphinx (6.1.3) and it seems to be resolved.

```python
T = TypeVar('T')

class Dummy(Generic[T]):
    r"""Dummy class.

    Arguments:
        arg: missing type annotation
    """

    def __init__(self, arg: str):
        pass
```

results in

![image](https://github.com/sphinx-doc/sphinx/assets/37352336/6bf111d1-52ec-4ade-a3b5-63b3b0406724)

**Comment by robsdedude** [comment]
@AA-Turner do you reckon it's worth splitting https://github.com/sphinx-doc/sphinx/issues/10605#issuecomment-1199462450 into a separate issue as it's not been resolved yet?

**Comment by AA-Turner** [comment]
Please do!
