### ISSUE TITLE
option to follow aliases

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1064]
Right now autodoc'ing a class alias generates the following documentation:

```
mymodule.MYCLASS
    alias of MYFULLCLASSNAMEORSOMETHING
```

..and that's it. There's no methods or anything. It would be nice to be able to follow the alias and get what would be generated if MYFULLCLASSNAMEORSOMETHING were used with autodoc instead. The benefit is that the alias name would be the primary one.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1064
- Originally reported by: Daniel Svensson
- Originally created at: 2012-12-18T22:35:47.646

**Comment by tk0miya** [comment]
This was already implemented at #4184. Closing.
