### ISSUE TITLE
Run make linkcheck on only changed files

### ISSUE THREAD

**Issue by laysauchoa** [sphinx-doc/sphinx#10643]
Running ``make linkcheck`` for all the files is slow and not necessary if the files did not changed.

**Describe the solution you'd like**
I wonder if there is any possible way to run make linkcheck on specific files or files that have changed. Seems like the only way to run is running in all the files.

**Describe alternatives you've considered**
This [tool](https://github.com/wpilibsuite/sphinxext-linkcheckdiff) could be useful but is no longer working as explained:
https://github.com/wpilibsuite/sphinxext-linkcheckdiff/issues/6

**Additional context**
Pretty much want to be able to run the command in specific files rather than the whole project. Having the checked links cached could be an option. I could not find anything else related.

Are there any alternatives out there for this?

**Comment by AA-Turner** [comment]
Closing for @francoisfreitag's reason--a link can die at any time, so checking the entire documentation is the proper thing to do here.

A

**Comment by laysauchoa** [comment]
Thanks @lornajane for bringing this up and thanks a lot @tk0miya for showing this command. It works for my use case 👍
