### ISSUE TITLE
Update Sphinx to work with docutils-0.19.x

### ISSUE THREAD

**Issue by ViktorHaag** [sphinx-doc/sphinx#10644]
**Is your feature request related to a problem? Please describe.**
[Docutils 0.19 has been released](https://docutils.sourceforge.io/RELEASE-NOTES.html#release-0-19-2022-07-05), and at first glance it appears to be compatible with Sphinx (cloning the Sphinx repo, running the tests clean with `-e py310` and `-e du19pre`).

**Describe the solution you'd like**
Unpin Sphinx from Docutils 0.18 and include 0.19.x.

**Describe alternatives you've considered**
Remain pinned to 0.18.x; this may cause disruptions in projects and platforms that assume they can freely update dependencies to the latest versions, especially if they directly depend on docutils.

**Additional context**
One of the open issues concerning the move to docutils 0.18.x is [around the change in handling with footnotes that arrived with docutils 0.18.x](https://github.com/sphinx-doc/sphinx/issues/10531). One of the items in the docutils release notes for 0.19.0 states:
> - Output changes:
> 
> HTML5:
> Wrap groups of footnotes in an `<aside>` for easier styling.
> 
> The CSS rule .footnote-list { display: contents; } can be used to restore the behaviour of custom CSS > styles.

This seems like it would help address our issue #10531.

Addressed by: https://github.com/sphinx-doc/sphinx/pull/10656

**Comment by AA-Turner** [comment]
You beat me to opening this issue--we test with Docutils' master weekly and I recently merged a change to test with the betas so yes good confidence on tests passing (I've just updated CI to use the released Docutils). 

I'll do a visual regression test, and then update the declared support.

A
