### ISSUE TITLE
[docs] Front-page improvements to make content easier to navigate

### ISSUE THREAD

**Issue by choldgraf** [sphinx-doc/sphinx#10659]
On the front page of the Sphinx documentation, there are some quirks to the layout that make it a bit confusing to understand the site structure. Here are a few quick suggestions from me:

1. The structure presented in `Documentation` in the main content should match the structure in the left sidebar. Both of them read like "site layout" guides, so it is confusing that they have two different structures. I'd also remove some of the links that are also UI elements on the page like "Search page".
2. The sidebar navigation should be grouped into sections, rather than one flat list. There are many types of pages in that list, and it is difficult to navigate them all quickly when they're just a single list. I'd recommend: `Get Started` (tutorials), `Topic Guides` (anything about usage), `Reference` (more "complete" documentation about all the APIs etc), `About` (about the project, contribute, etc). I'd recommend roughly following [the Diataxis framework](https://diataxis.fr/)
4. Rename `Man pages` to `Command Line API`. I suspect that most people will not know what `Man pages` means. I'd also add a top-level `Python API` page that links to the API docs for the Python library.

![image](https://user-images.githubusercontent.com/1839645/178214155-511c05a3-0330-479c-9a3b-40214a60f73a.png)

**Comment by tk0miya** [comment]
+1
