### ISSUE TITLE
[docs] Heading anchors should appear next to the header

### ISSUE THREAD

**Issue by choldgraf** [sphinx-doc/sphinx#10658]
In the new theme refresh, the heading anchor characters show up to the far right of the heading, which can be difficult to notice and feels a bit awkward from a UI/UX standpoint:

![image](https://user-images.githubusercontent.com/1839645/178211550-58de62a6-9be3-4bf5-a6c6-0412c4d25c25.png)

I'd propose that heading anchors should show up just to the right of heading text when it is hovered, so that it is easier to notice and click.

**Comment by tk0miya** [comment]
+1
