### ISSUE TITLE
[docs] Mention that Sphinx can read markdown on its landing page

### ISSUE THREAD

**Issue by choldgraf** [sphinx-doc/sphinx#10663]
The [landing page of Sphinx](https://www.sphinx-doc.org/en/master/) makes it seem like reStructuredText is the only markup language that works with it:

> Sphinx uses [reStructuredText](https://docutils.sourceforge.io/rst.html) as its markup language, and many of its strengths come from the power and straightforwardness of reStructuredText and its parsing and translating suite, the [Docutils](https://docutils.sourceforge.io/).

While reStructuredText is powerful and great, the large majority of potential users will likely be familiar with, and want to use some version of markdown. Given that it is possible to write Markdown within Sphinx via tools like **[MyST Parser](https://myst-parser.readthedocs.io/)**, I think it is a good idea to mention Markdown support via community extensions rather than not mentioning Markdown at all. For users that are comparing Sphinx to other documentation engines like Docasaurus, MkDocs, Markdocs, etc, it will make it clear that Sphinx does not lack this feature.

(also note I think there's a typo in the sentence I've highlighted above...it ends quite abruptly...)

**Comment by tk0miya** [comment]
Understandable. +1 for adding mention to the markdown.
Could you send a PR, please? It's very helpful to me because I'm not good at English.
