### ISSUE TITLE
[docs] Use the Read the Docs docs preview feature on pull requests

### ISSUE THREAD

**Issue by choldgraf** [sphinx-doc/sphinx#10661]
Read the Docs has a [feature that will generate a preview of your documentation on Pull Requests](https://docs.readthedocs.io/en/stable/pull-requests.html). This is a useful way of quickly previewing changes in the PR without needing to hunt down a link or build it locally.

I propose that this feature be turned on for this repository, so that others can quickly look at changes.

**Comment by tk0miya** [comment]
I consider it has already been enabled. Is there anything wrong?

**Comment by humitos** [comment]
Quick reply from the phone: if it's enabled and does not trigger builds check this section https://docs.readthedocs.io/en/stable/pull-requests.html#troubleshooting

I'm guessing the problem is with the webhook not being well configured

**Comment by choldgraf** [comment]
I didn't see a link show up in the checks of this PR, which is what led me to open this:

- https://github.com/sphinx-doc/sphinx/pull/10652

**Comment by tk0miya** [comment]
It seems RtD builds docs on each PR. But it never updates the CI status.
https://readthedocs.org/projects/sphinx/builds/

I resync the webhook now. Let's see the next PR.

**Comment by humitos** [comment]
@tk0miya cool! It seems it worked. See #10677 and its preview at https://sphinx--10677.org.readthedocs.build/en/10677/ 🎉
