### ISSUE TITLE
mypy test fails due to ``# type: ignore`` in sphinx/util/logging.py

### ISSUE THREAD

**Issue by jfbu** [sphinx-doc/sphinx#10687]
### Describe the bug

https://github.com/sphinx-doc/sphinx/runs/7436585449?check_suite_focus=true

but recent merges are unrelated...

### How to Reproduce

```
$ git clone https://github.com/.../some_project
$ cd some_project
$ pip install -r requirements.txt
$ cd docs
$ make html SPHINXOPTS="-D language=de"
$ # open _build/html/index and see bla bla
```

### Your project

sphinx

### OS

Mac

### Python version

3.10.4

### Sphinx version

5.x f20fca9bf108244c65a88d901992fa6b8257e81b

### Additional context

Raising this to draw attention as I can't take care of it...

**Comment by tk0miya** [comment]
Fixed by https://github.com/sphinx-doc/sphinx/pull/10693.
