### ISSUE TITLE
Problem with ReadTheDocs PDF rendering regarding pict2e LaTeX package

### ISSUE THREAD

**Issue by jfbu** [sphinx-doc/sphinx#10695]
### Describe the bug

There is a problem with PDF rendering of our documentation at Read The Docs

https://readthedocs.org/projects/sphinx/builds/17516903/

### How to Reproduce

visit https://www.sphinx-doc.org/en/master/ and download PDF from pop-up

### Your project

Sphinx

### Screenshots

![Capture d’écran 2022-07-23 à 11 56 02](https://user-images.githubusercontent.com/2589111/180600664-49260cfe-ef15-4df9-acaa-345946267212.png)

### OS

?

### Python version

?

### Sphinx version

https://github.com/sphinx-doc/sphinx/commit/1199f7bd75378ca6f531e2099ef2b9c5624c7b23

### Additional context

This looks like a problem of pict2e version being too old at Read The Docs.  Surprisingly, the rounded corners are rendered correctly, the problem is with extra "pict2e" and other artefacts appearing in PDF output.

Sadly, on my current system I can not easily test older LaTeX systems, oldest I can easily check is with March 2020 TeXLive 2019.  I will try to see if I can fetch older pict2e versions.

Is there a way to obtain LaTeX log from compilation at Read The Docs?

**Comment by jfbu** [comment]
> Sadly, on my current system I can not easily test older LaTeX systems, oldest I can easily check is with March 2020 TeXLive 2019. I

SORRY, the problem DOES show with TeXLive 2019.  I *thought* I had tested.

I see the nature of the problem (`\@ifpackageloaded` could not be used in document body but only in document preamble, which is not the case anymore with current LaTeX) so I am confident I can fix this in time for 5.1.0 release. Perhaps only after lunch (European time) or at least putting stuff in the oven.

**Comment by humitos** [comment]
Quick reply from the phone: you can use a newer Ubuntu image that will come with a newer version of that package.

You need to use "build.os: ubuntu-22.04" in your config file. Take a look at https://docs.readthedocs.io/en/stable/config-file/v2.html#build-os

Let me know if that works.

**Comment by jfbu** [comment]
> Le 23 juil. 2022 à 12:39, Manuel Kaufmann ***@***.***> a écrit :
> 
> 
> Quick reply from the phone: you can use a newer Ubuntu image that will come with a newer version of that package.
> 
> You need to use "build.os: ubuntu-22.04" in your config file. Take a look at https://docs.readthedocs.io/en/stable/config-file/v2.html#build-os <https://docs.readthedocs.io/en/stable/config-file/v2.html#build-os>
> Let me know if that works.
> 
> 
Thanks! This is very useful to me for future. Fortunately I could identify that the cause is not too old version of pict2e package but the changed behaviour of a LaTeX core package author macro, which was less flexible in the past. Fix on its way...

**Comment by jfbu** [comment]
Thanks again @humitos for kicking in, I will keep your hint for future.

Fortunately my oversight is now fixed, and compilation at Read The Docs of PDF is fine!

https://readthedocs.org/projects/sphinx/builds/17517802/
