### ISSUE TITLE
C domain: allow inline reference to pointer of a defined type

### ISSUE THREAD

**Issue by marxin** [sphinx-doc/sphinx#10704]
It's quite common that one needs to explain that a pointer of a type is returned:

```rst
.. c:type:: my_type

This works :c:type:`my_type`, but I would like to point
to a pointer of the type (:c:type:`my_type *`).
```

but one gets:
```shell
/tmp/demo/source/index.rst:15: WARNING: Unparseable C cross-reference: 'my_type *'
Invalid C declaration: Expected end of definition. [error at 8]
  my_type *
  --------^
```

@jakobandersen Is it something that can be supported, please?

**Comment by jakobandersen** [comment]
The ``type`` directive is for declaring a type alias so that won't work.
If it's a return type then something like the following can be done:
```rst
... c:function:: Foo *f()

   :returns: a pointer to the thing.
   :rtype: Foo*
```
In general you can use the `expr` role in inline text, it accepts both expressions and types.

**Comment by marxin** [comment]
Yep, thanks, `::expr` role works very well!
