### ISSUE TITLE
Please use consistent UNIX line endings in release tarballs

### ISSUE THREAD

**Issue by mitya57** [sphinx-doc/sphinx#10714]
### Describe the bug

@AA-Turner Thank you for doing release work for Sphinx.

I am Sphinx maintainer in Debian and we are importing upstream tarballs into our version control system.

In the latest release 5.1.1, line endings format changed from UNIX-style `\n` to Windows-style `\r\n` for `CHANGES` and `sphinx/__init__.py`. This makes `git diff` not work properly, for example git thinks that CHANGES file change is 7045 insertions and 7035 deletions (while in fact it should be just 10 insertions).

See here: https://salsa.debian.org/python-team/packages/sphinx/-/commit/8d9ef9861ba22af08f539fd4c3231b10eead9ec8.

Please adjust your release scripting to use consistent `\n` endings for all files inside the tarball. Ideally, also for GPG signature (`*.asc`).

### How to Reproduce

```
$ wget https://files.pythonhosted.org/packages/3a/30/ac07935542607c876f3fcee1c1ab043d253332567009994a1bf71d9b55cd/Sphinx-5.1.1.tar.gz
$ tar xzf Sphinx-5.1.1.tar.gz
$ cd Sphinx-5.1.1
$ file CHANGES
CHANGES: ASCII text, with CRLF line terminators
$ file README.rst   # this one is correct
README.rst: ASCII text
```

### Your project

Debian packaging of Sphinx

### OS

Debian

### Python version

3.10

### Sphinx version

5.1.1

**Comment by AA-Turner** [comment]
@mitya57 hopefully this is fixed with 5.2.0.

A

**Comment by mitya57** [comment]
@AA-Turner Thanks, it is fixed, but now there are two other issues:

1. Signature does not verify:
    ```
    $ gpg --verify Sphinx-5.2.0.tar.gz.asc
    gpg: assuming signed data in 'Sphinx-5.2.0.tar.gz'
    gpg: Signature made Sat 24 Sep 2022 07:41:58 PM MSK
    gpg:                using RSA key D3549119BD51B4AFE643E59752C8F72A61F0FB52
    gpg: BAD signature from "Adam Turner <9087854+aa-turner@users.noreply.github.com>" [unknown]
    ```
2. Tarball has many `*.pyc` files in `tests/__pycache__` and some subdirectories of `tests/roots`.

**Comment by AA-Turner** [comment]
@mitya57 Please look at https://pypi.org/project/Sphinx/5.2.0.post0/, I recreated and resigned the release files.

A

**Comment by mitya57** [comment]
@AA-Turner Thank you, it's perfect now!

**Comment by mitya57** [comment]
@AA-Turner And now in 5.3.0 tarball `CHANGES` and `sphinx/__init__.py` have `\r\n` line endings again.

**Comment by AA-Turner** [comment]
I would prefer to release via CI but signing releases seems to prevent that...

**Comment by AA-Turner** [comment]
Can you check 6.0.0b1?

**Comment by mitya57** [comment]
6.0.0b1 is good.
