### ISSUE TITLE
Regression in agogo theme

### ISSUE THREAD

**Issue by gvimont** [sphinx-doc/sphinx#10715]
### Describe the bug

Pull request #10520 introduced a regression in the display of the Table of Content of the `agogo` theme.
The `agogo` sample can be seen here: https://sphinx-themes.org/sample-sites/default-agogo/

### How to Reproduce

https://sphinx-themes.org/sample-sites/default-agogo/

The background's width of the Table of Contents takes the whole page.

### Expected behavior

The background's width of the Table of Contents should be limited to the TOC width.

### Your project

Internal

### OS

Linux

### Python version

3.8

### Sphinx version

5.1.0

**Comment by gvimont** [comment]
This is not a regression but #10520 make visible a bug in `agogo` theme.

**Comment by mgeier** [comment]
I'm the author of #10520 and I must confess that I wasn't aware the `agogo` uses the wrong CSS class for its sidebar (`sidebar` instead of the `sphinxsidebar`) and it doesn't "correctly" style the `sidebar` directive.

So I agree that `agogo` was broken before but it is more broken after my change.
