### ISSUE TITLE
Sphinx 5.1.1 release plan

### ISSUE THREAD

**Issue by AA-Turner** [sphinx-doc/sphinx#10710]
I plan to release Sphinx 5.1.1 **tomorrow**, Tuesday 26 July 2022 [^1]

This release contains PR #10709 fixing issues #10701 & #10705, and PR #10702 fixing an issue with using third-party builders.

**Please test the `5.1.x` branch**, it can be installed with `pip install https://github.com/sphinx-doc/sphinx/archive/refs/heads/5.1.x.zip`

With thanks in advance,
Adam

[^1]: This would be late evening British time, around 22-24 hours from now.

**Comment by mwichmann** [comment]
As a "me too" on closed #10705: Works For Me.

**Comment by jdknight** [comment]
Changes work for the use case mentioned on #10702 (both active release and development branch of the builder in question). Appreciate the merge and tweaks to the pull request.

**Comment by yarikoptic** [comment]
> **Please test the `5.1.x` branch**, it can be installed with `pip install https://github.com/sphinx-doc/sphinx/archive/refs/heads/5.1.x.zip`

FWIW the version does fix #10701/#10705 for me and build completes fine (i.e. no some other regression as far as I can see).

**Comment by AA-Turner** [comment]
I have published the release of [Sphinx 5.1.1](https://pypi.org/project/Sphinx/5.1.1/), many thanks for testing this release at such short notice, and especially to @anntzer and to @jdknight for contributing the fixes.

Adam

**Comment by anntzer** [comment]
Sorry for the breakage I caused :)
