### ISSUE TITLE
Mechanism for definition of common footnotes.

### ISSUE THREAD

**Issue by jan-matejka** [sphinx-doc/sphinx#10732]
At the moment, we can add footnotes like

    .. [POSIX.1-2017]

Into each rst source file. However, footnotes like this example are generic enough that frequent usage in many different source files may occur. Therefore it is desirable to have a single place to define common footnotes and have them included in each page as needed.

It may seem these footnotes could be added to rst_prolog or rst_epilog configuration options but that is not the case since this generates WARNING: duplicate citation.

Current workaround seems to be to put the footnotes into standalone file like foot.rst and include it each document as needed. This not optimal because we still need to include the include directive in each document and when not all the common footnotes are used, a WARNING: Citation [Foo] is not referenced is generated. This can be worked around by self-referencing all the common footnotes. However, this causes appearance of unrelated footnotes in all content.

**Comment by yaccz** [comment]
Well, that's an oof. Citations can be actualy referenced from any document by default.
