### ISSUE TITLE
autoclass digests types from typehint but numpy types are not linked via intersphinx

### ISSUE THREAD

**Issue by 1kastner** [sphinx-doc/sphinx#10746]
### Describe the bug

I use numpy types in my function and method typehints. Unlike https://github.com/sphinx-doc/sphinx/issues/10151, I do not want to repeat the types in the docstring. I prefer the types to show up in the signature and only there. Usually, Sphinx does a very decent job injecting the types into the signature. Here, also intersphinx comes into play and adds links to Python types such as integers, datetime objects, etc.

Recently, I added numpy to the stack. Somehow, intersphinx does not create links for these types even though its inventory is added to `intersphinx_mapping`. 

### How to Reproduce

```
$ git clone https://github.com/1kastner/conflowgen.git
$ cd conflowgen
$ pip install -e .[dev]
$ cd docs
$ make html
$ # open _build/html/api.html#using-distributions and see that intersphinx did not turn numpy.typing.ArrayLike into a link
```

### Expected behavior

`numpy.typing.ArrayLike` should be detected by intersphinx and converted into a link

### Your project

https://github.com/1kastner/conflowgen

### Screenshots

Here, I played around and also included the typehints into the description of the class. Still no clickable links.

![grafik](https://user-images.githubusercontent.com/5236165/182433296-e3cf96a7-c63d-44b6-9324-653b01f9e93b.png)

### OS

Windows

### Python version

3.9

### Sphinx version

4.5

### Sphinx extensions

['sphinx.ext.autodoc', 'sphinx.ext.todo', 'sphinx.ext.napoleon', 'sphinx.ext.mathjax', 'sphinx.ext.intersphinx', 'sphinx.ext.autosectionlabel', 'sphinx.ext.viewcode', 'sphinxcontrib.bibtex', 'myst_parser', 'sphinx_math_dollar', 'enum_tools.autoenum', 'sphinx_toolbox.more_autodoc.autonamedtuple', 'nbsphinx']

**Comment by 1kastner** [comment]
See https://github.com/1kastner/conflowgen/blob/main/docs/conf.py#L114 for the inventory.

**Comment by 1kastner** [comment]
Completely my bad. I did not import `numpy.typing` which I should have. No linter or heuristic in the IDE warned me and I was too overwhelmed with issues from the past (like I cited) to see that it was a simple user error...

**Comment by ryancoe** [comment]
@1kastner - I'm having a similar issue. Where (in what file) were you missing the `import numpy.typing` call?

**Comment by 1kastner** [comment]
In the file that contained the auto-documented class.
