### ISSUE TITLE
Figure captions with citations fail in building PDF

### ISSUE THREAD

**Issue by astonzhang** [sphinx-doc/sphinx#10743]
### Describe the bug

Figure captions with citations fail in building PDF. Here is an example (note that `:citet:` is an alias of `:cite:t:`):

Input ipynb:
![Screen Shot 2022-08-01 at 11 59 48 AM](https://user-images.githubusercontent.com/22279212/182223966-66be83bb-cde5-44e4-82e4-4fc17f812ae6.png)

Output tex:
![bad](https://user-images.githubusercontent.com/22279212/182225049-62aa7654-3310-4508-bbd8-e79ce74eb331.png)

When compiling PDF from this tex, the following error shows up:

![Screen Shot 2022-08-01 at 11 56 21 AM](https://user-images.githubusercontent.com/22279212/182225235-fc2269b9-e96e-43dc-ba8c-eba55f947ec8.png)

### How to Reproduce

```
$ git clone -b sphinx-latex https://github.com/d2l-ai/d2l-en.git
$ cd d2l-en
$ vi static/post_latex/main.py # Comment out my hack https://github.com/d2l-ai/d2l-en/blob/sphinx-latex/static/post_latex/main.py#L141
$ pip install d2lbook
$ d2lbook build pdf  # The output pdf should be at _build/pdf
```

### Expected behavior

As a hack for this issue, I [post-process this tex file](https://github.com/d2l-ai/d2l-en/blob/master/static/post_latex/main.py#L136). So the processed tex has a `\protect` and becomes:
![good](https://user-images.githubusercontent.com/22279212/182225755-422b3986-5860-4494-99aa-6a65fd817e3c.png)

Then the output PDF is:
![Screen Shot 2022-08-01 at 11 56 32 AM](https://user-images.githubusercontent.com/22279212/182225972-426b503b-901d-4b36-b8f1-652328d1fbcb.png)

### Your project

https://github.com/d2l-ai/d2l-en/ and https://github.com/d2l-ai/d2l-book

### OS

Linux

### Python version

3.8

### Sphinx version

5.1.1

### Additional context

Following https://github.com/sphinx-doc/sphinx/issues/10719#issuecomment-1200382781, I submit this issue as suggested by @jfbu:

> Indeed it is no good to rely on Sphinx output syntax... I don't have specific suggestion as I have not looked in details at what your post-processing script does. I see now you e.g. add a \protect in front of \hyperlink, if this is a Sphinx issue, please report it.

**Comment by jfbu** [comment]
Thanks, note that the more correct mark-up in the `.tex` file should a priori be
```latex
from T5 (figures taken from Saharia \sphinxstyleemphasis{et al.} {[}\cite{chapter_references/zreferences:id489}{]})
```
in place of the more bulky
```latex
from T5 (figures taken from Saharia \sphinxstyleemphasis{et al.} {[}\protect\hyperlink{cite.chapter_references/zreferences:id489}{Saharia et al., 2022}{]})
```
With `\cite` there is no need for `\protect`.  And while we are at it it should probably be `\sphinxcite` by the way ;-).

In both cases the output in PDF is the same:
![Capture d’écran 2022-08-01 à 21 51 16](https://user-images.githubusercontent.com/2589111/182233886-7ae77da7-9582-49ac-93cc-1da0191306d2.png)

Chances are that the `\hyperlink` come from https://github.com/mcmtroffaes/sphinxcontrib-bibtex/blob/9a672e2be1fdebc3dda1e1a1f7afa947a0f01d31/src/sphinxcontrib/bibtex/style/template.py#L126-L137

```
    def render(self, backend: "BaseBackend") -> List[docutils.nodes.Element]:
        assert isinstance(backend, pybtex_docutils.Backend), \
               "SphinxReferenceText only supports the docutils backend"
        info = self.info[0]
        if info.builder.name == 'latex':
            key = f'cite.{info.todocname}:{info.citation_id}'
            return (
                [raw_latex(f'\\hyperlink{{{key}}}{{')]
                + super().render(backend)
                + [raw_latex('}')]
            )
        elif info.builder.name == 'rinoh':
...
```
Although I will stay cautious here until I get time for some precise investigation...

...I can't wait to see if will have to add the "report-elsewhere" label which I created recently but had to remove ;-). (see #10719 thread)  We'll see.

Thanks again for reporting and providing manageable reproducing project.

**Comment by jfbu** [comment]
> Although I will stay cautious here until I get time for some precise investigation...
> 
> ...I can't wait to see if will have to add the "report-elsewhere" label which I created recently but had to remove ;-). (see #10719 thread) We'll see.

Yes I confirmed it definitely is a sphinxcontrib-bibtex mark-up from the code lines I referred-to.  So the issue should be reported there...

...thanks for the effort here, but I must close this as not being a Sphinx issue!
