### ISSUE TITLE
Link in the "Bugs fixed" section of the 5.1.0 change log is not correct

### ISSUE THREAD

**Issue by WarrenWeckesser** [sphinx-doc/sphinx#10760]
### Describe the bug

The [bugs fixed](https://www.sphinx-doc.org/en/master/changes.html#id35) section of the 5.1.0 Changelog includes this line:

* [#10031](https://github.com/sphinx-doc/sphinx/issues/10031): py domain: Fix spurious whitespace in unparsing various operators (+, -, ~, and **). Patch by Adam Turner.

The problem is that the text "py domain: Fix spurious whitespace in unparsing various operators (+, -, ~, and **)" does not match the pull request #10031.

I noticed this because I was checking to see which release contains https://github.com/sphinx-doc/sphinx/pull/10551.  I don't see any mention of that pull request in the change log.

**Comment by AA-Turner** [comment]
PR welcome, otherwise I'll get to it at the weekend most likely. Thanks for reporting!

A
