### ISSUE TITLE
How to make a StackOverflow-like thumb up mechanism using sphinx?

### ISSUE THREAD

**Issue by zztiger123** [sphinx-doc/sphinx#10775]
How to make a StackOverflow-like thumb up mechanism using sphinx? As follows.
![image](https://user-images.githubusercontent.com/40046810/185335150-856e1f4c-9a39-47f2-b846-c961c07c6eac.png)

I would appreciate if there is some documentation reference

**Comment by jdillard** [comment]
You would need to customize your theme and add javascript requests to a backend service that stores the votes. This isn't related to the core of Sphinx.
