### ISSUE TITLE
Use https instead of http where possible

### ISSUE THREAD

**Issue by kjcole** [sphinx-doc/sphinx#10788]
I'm setting up a new web site from scratch and following the latest recommendations for content security policies (CSP). As I move documentation generated by Sphinx, I'm finding all sorts of places where "http://" is used when "https://" is available.

While it's true that some of the changes would need to happen upstream, e.g. the **jQuery** stuff,

* `_sphinx_javascript_frameworks_compat.js` and `doctools.js` belong directly to **Sphinx**
* even though it's only a namespace, not a true URL, http://www.w3.org/2000/svg redirects to https://www.w3.org/2000/svg when entered into a browser, and thus seems like a harmless and very quick & easy change.

**Comment by AA-Turner** [comment]
Done (23cef9b59a0a4a6955d2a54fe853bea650d3b725)

A
