### ISSUE TITLE
Remove heading from search box in sphinx13 style

### ISSUE THREAD

**Issue by timhoffm** [sphinx-doc/sphinx#10791]
The heading takes extra space and adds a bit of clutter. Since the only element in the section is the input field we can as well only show the input field and use the placeholder to spell out "Search".

Current (left) / suggestion (right):

![grafik](https://user-images.githubusercontent.com/2836374/187072608-9be3cd31-abce-4d48-b734-7a561358b1e2.png) ![grafik](https://user-images.githubusercontent.com/2836374/187072894-92e7a152-5c0f-4ef3-a97c-e4aaf85bf3e8.png)

Since the search box is a component (`searchbox.html`), which may need to stay as is for compatibility, I suggest to introduce a new reduced component (e.g. `searchfield.html`) and use that for sphinx13.

Let me know what you think. I can come up with a PR if there is interest for it.

**Comment by AA-Turner** [comment]
Seems useful, thank you.

A

**Comment by timhoffm** [comment]
👍 I will put up a PR in a couple of days.
