### ISSUE TITLE
Empty template for nbsphinx_input_prompt and nbsphinx_output_prompt lead to TypeError: not all arguments converted during string formatting

### ISSUE THREAD

**Issue by 1kastner** [sphinx-doc/sphinx#10792]
### Describe the bug

In my documentation, my idea was to hide the prompts. I wanted to be clever and just use an empty template for nbsphinx_input_prompt and nbsphinx_output_prompt. However, this lead to the following exception: `TypeError: not all arguments converted during string formatting`.

### How to Reproduce

```
nbsphinx_input_prompt =nbsphinx_output_prompt = ""
```

### Expected behavior

Maybe the filling of the variable could be more forgiving? So `%s` is only inserted in the template if such a variable is available in the template in the first place? I think this is better than tempering with HTML and CSS. 

### Your project

not applicable

### OS

Win

### Python version

3.10

### Sphinx version

5.1

**Comment by 1kastner** [comment]
This was meant to be posted at nbsphinx, somehow I ended up in the wrong tab.

**Comment by mgeier** [comment]
There are already some issues/PRs about this topic, feel free to chime in:

https://github.com/spatialaudio/nbsphinx/issues/131
https://github.com/spatialaudio/nbsphinx/pull/185
https://github.com/spatialaudio/nbsphinx/issues/442
https://github.com/spatialaudio/nbsphinx/pull/446
