### ISSUE TITLE
sphinx-build overwrites values from arguments -D , -A, -t , while user expects action='append' for these arguemnts

### ISSUE THREAD

**Issue by hub4andrey** [sphinx-doc/sphinx#10796]
### Describe the bug

**Business case:** need to build documentation by discarding config.py content, using only shpinx-build arguments.

Problem is in https://github.com/sphinx-doc/sphinx/blob/5.x/sphinx/cmd/build.py  line 254:
```
confoverrides[key] = val
```
Every new argument  "-D extensions=sphinx.ext.name" overwrites previous value.

This problem is valid for below arguments with action='append' only:

    group.add_argument('-D', metavar='setting=value', action='append',
                       dest='define', default=[],
                       help=__('override a setting in configuration file'))

    group.add_argument('-A', metavar='name=value', action='append',
                       dest='htmldefine', default=[],
                       help=__('pass a value into HTML templates'))

    group.add_argument('-t', metavar='TAG', action='append',
                       dest='tags', default=[],
                       help=__('define tag: include "only" blocks with TAG'))

### How to Reproduce

```
$ unzip docs-sphinx.zip
$ cd docs-sphinx
$ python -m venv .venv
$ . .venv/bin/activate
$ pip install -r app-docs-sphinx/requirements.txt

$ sphinx-quickstart \
    --sep \
    --project sphinx-doc \
    --author A.Lukyanov \
    --release 0.1 \
    --language en \
    docs

$ rm -R docs/build/*  ;  \
    if [[ ":$PYTHONPATH:" != *":$PWD:/app-docs-sphinx"* ]]; then export PYTHONPATH=$(pwd):$PYTHONPATH ; fi ; \
    sphinx-build \
        -a \
        -E \
        -b html \
        -C \
        -D html_theme=alabaster \
        -D extensions=sphinx.ext.duration \
        -D extensions=sphinx.ext.doctest \
        -D extensions=sphinx.ext.autodoc \
        -D extensions=sphinx.ext.autosummary \
        docs/source docs/build
```

As result, only *sphinx.ext.autosummary* extension is included into *confoverrides* variable. All other extensions are not imported into sphinx-build.

### Expected behavior

By adding several arguments "-D  extensions=extension_name" , each argument's value has to be appended into config variable "extensions" .

Example: 

```
$ sphinx-build \
    -a \
    -E \
    -b html \
    -C \
    -D html_theme=alabaster \
    -D extensions=sphinx.ext.duration \
    -D extensions=sphinx.ext.doctest \
    -D extensions=sphinx.ext.autodoc \
    -D extensions=sphinx.ext.autosummary \
    docs/source docs/build
```

Above script has to be converted into configuration statements:
extensions = [
        'sphinx.ext.duration',
        'sphinx.ext.doctest',
        'sphinx.ext.autodoc',
        'sphinx.ext.autosummary',
        ]

html_theme = 'alabaster'

See attached file [docs-sphinx.zip](https://github.com/sphinx-doc/sphinx/files/9481331/docs-sphinx.zip)

### Your project

[docs-sphinx.zip](https://github.com/sphinx-doc/sphinx/files/9481331/docs-sphinx.zip)

### OS

Ubuntu 22.04.1 LTS

### Python version

3.9.12

### Sphinx version

5.1.1

**Comment by mgeier** [comment]
I think this is intended behavior, you should maybe use something like this:

    -D extensions=sphinx.ext.duration,sphinx.ext.doctest,sphinx.ext.autodoc,sphinx.ext.autosummary

See also https://www.sphinx-doc.org/en/master/man/sphinx-build.html#cmdoption-sphinx-build-D, which mentions:

> For lists, you can separate elements with a comma like this: `-D html_theme_path=path1,path2`.

**Comment by hub4andrey** [comment]
Hi Matthias,

many thanks! I didn't notice this clarification in manual, trying to use standard functionality of argparse lib.

**Comment by mgeier** [comment]
> trying to use standard functionality of argparse lib

Just to give a bit more information: Sphinx is of course using the standard functionality of `argparse`, there is nothing special about it, but I think you have been misled by `action='append'`. This does indeed append all options given by `-D`, but that's not the end of the story. Because even though all `-D` options are appended into a list, the `key=val` pairs of this list are afterwards written into a dictionary (named `confoverrides`), which means that if there are repeated keys (like `extensions` in your case), all but the last one are overwritten:

https://github.com/sphinx-doc/sphinx/blob/5e9550c78e3421dd7dcab037021d996841178f67/sphinx/cmd/build.py#L248-L254

**Comment by hub4andrey** [comment]
Hi Matthias,

yes, it's clear from Sphinx's code. And most important, the documentation specifies how to add multiple values to -D option: `-D html_theme_path=path1,path2`. 

So, no more questions or doubt from my side. I very appreciate your prompt support and time you dedicated to my small issue.


For clarity: I've just tried to use standard functionality of `argarse` that allow the same option to be specified multiple times and expected the same from Sphinx (before you stressed my attention to appropriate note in Sphinx manual :-)  ) 

From [docs.python.org argparse manual](https://docs.python.org/3/library/argparse.html#action)  :

> 'append' - This stores a list, and appends each argument value to the list. This is useful to allow an option to be specified multiple times. Example usage:

```python
>>> parser = argparse.ArgumentParser()
>>> parser.add_argument('--foo', action='append')
>>> parser.parse_args('--foo 1 --foo 2'.split())
Namespace(foo=['1', '2'])
```

Best regards
Andrey

**Comment by mgeier** [comment]
> allow the same option to be specified multiple times and expected the same from Sphinx

The same is happening in Sphinx. You can give the same option `-D` multiple times, e.g. `-D x=a -D y=b -D z=c`, which will lead to all three config options options (`x`, `y` and `z`) being set. The only special behavior happens when you do something like `-D x=a -D x=b`, which is clearly a contradictory user input, they cannot both be assigned at the same time. So I think it is not surprising that the second one overrides the first one.
