### ISSUE TITLE
sphinx-doc.org APEX domain setting for ReadTheDocs

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#10797]
We previously did DNS configuration for HTTPS on `www.sphinx-doc.org` on #5522 (Fall 2018).

At the time, the official ReadTheDocs documentation stated that "ReadTheDocs doesn't support naked domains.", but now it states that they can be configured with ANAME.

https://docs.readthedocs.io/en/stable/custom-domains.html
> For a subdomain like docs.example.com add a CNAME record, and for a root domain like example.com use an ANAME or ALIAS record. (it comes since https://github.com/readthedocs/readthedocs.org/pull/9266, maybe)

Also, on 8/30/2022, ReadTheDocs sent an email notification to me, noting that the `sphinx-doc.org` domain was not set up correctly.
> <img width="326" alt="image" src="https://user-images.githubusercontent.com/151623/188257983-c21152a9-2fd6-45a7-9877-89b265b48dc9.png">

This ticket will do the following.

* Add DNS record: `sphinx-doc.org. ANAME www.sphinx-doc.org.`

This will solve two problems.

* `https://sphinx-doc.org` was not being provided.
* ReadTheDocs alerts are being displayed for `sphinx-doc.org`.

**Comment by shimizukawa** [comment]
@birkenfeld Can you please add a ANAME record to your DNS?

> * Add DNS record: `sphinx-doc.org. ANAME www.sphinx-doc.org.`

**Comment by birkenfeld** [comment]
Like I said in https://github.com/sphinx-doc/sphinx/issues/7779#issuecomment-640004434 I can't add ALIAS or ANAME entries :(

**Comment by shimizukawa** [comment]
Ah, you had already checked. Thanks very much for your comment.
Once again, give up on setting up a naked domain...

**Comment by birkenfeld** [comment]
I now made a support request at the hoster, but I'm not hopeful. I will also transfer the domain to you or a trusted maintainer, if that is better.

**Comment by AA-Turner** [comment]
I use cloudflare DNS for `docutils.org` and `restructuredtext.org`, which supports naked domains I believe.

A
