### ISSUE TITLE
Text following notes and warnings stay embedded inside the note or warning box

### ISSUE THREAD

**Issue by sofian** [sphinx-doc/sphinx#10803]
### Describe the bug

When building documentation, text following calls to ```.. warning::``` or ```.. note::``` stay embedded inside the warning or note box.

### How to Reproduce

```
$ git clone https://github.com/SofaPirate/Plaquette
$ mkdir Plaquette-docs
$ cd Plaquette/docs
$ pip install -r requirements.txt
$ make html
```
The open file ../../Plaquette-docs/html/AnalogOut.html

See how the note is embedded inside another note:

![Screenshot from 2022-09-06 11-05-35](https://user-images.githubusercontent.com/791244/188670172-35cb3a03-1b63-4fc5-a03e-72c1b9d5ad24.png)

You can also see file ../../Plaquette-docs/html/MinMaxScaler.html the behavior following the warning:

![Screenshot from 2022-09-06 11-07-02](https://user-images.githubusercontent.com/791244/188670441-0bf9e292-87dc-4a74-b72b-9e7beaa87400.png)

### Expected behavior

The text following note and warning should flow normally in plain text.

### Your project

https://github.com/SofaPirate/Plaquette

### OS

Linux Ubuntu 20.04

### Python version

Python 2.7.18

### Sphinx version

Sphinx==5.1.1

### Sphinx extensions

sphinx-rtd-theme==1.0.0 sphinxcontrib-applehelp==1.0.2 sphinxcontrib-devhelp==1.0.2 sphinxcontrib-htmlhelp==2.0.0 sphinxcontrib-jsmath==1.0.1 sphinxcontrib-qthelp==1.0.3 sphinxcontrib-serializinghtml==1.1.5

### Extra tools

breathe, Doxygen

**Comment by sofian** [comment]
Try with the following index.rst file:

```
Index
============

This filtering unit regularizes incoming signals by remapping them into a new interval of [0, 1].

.. warning::

   This filtering unit works well as long as there are no "outliers" in the signal (ie. extreme values)
   that appear in rare conditions. Such values will replace the mininum or maximum value and greatly
   restrict the spread of the filtered values.


Example
--------

Reacts to high input values by activating an output LED. Scaler is used to
automatically adapt to incoming sensor values.
```

Run 
```
$ mkdir htmldir
$ sphinx-build -b html . ./html
```

Sphinx runs Python 3 (on my system 3.8.10) by default. I tried running sphinx-build as shown and it generates the same problem

**Comment by AA-Turner** [comment]
Dear Sofian,

Please may you run the following reproducer script in a clean directory? (i.e. `python reproducer.py`)

```python
import shutil
from pathlib import Path

from sphinx.cmd.make_mode import run_make_mode


def write(filename, text): Path(filename).write_text(text, encoding="utf-8")

write("conf.py", '''\
include_patterns = ["index.rst"]
''')

write("index.rst", '''\
Index
============

This filtering unit regularizes incoming signals by remapping them into a new interval of [0, 1].

.. warning::

   This filtering unit works well as long as there are no "outliers" in the signal (ie. extreme values)
   that appear in rare conditions. Such values will replace the mininum or maximum value and greatly
   restrict the spread of the filtered values.


Example
--------

Reacts to high input values by activating an output LED. Scaler is used to
automatically adapt to incoming sensor values.
''')

shutil.rmtree("_build", ignore_errors=True)
run_make_mode(["html", ".", "_build", "-T", "-W"])
```

I am unable to reproduce the error still, the `index.html` file produced looks like the below when I run the reproducer script:

![image](https://user-images.githubusercontent.com/9087854/188894168-3cede3f8-d794-4af0-b51f-5b102b91b0b5.png)

A
