### ISSUE TITLE
support doc comment in func definition

### ISSUE THREAD

**Issue by Fmajor** [sphinx-doc/sphinx#10857]
when there are many args, I usually define the function like this
```
def somefunc(
        a : int,          #: a is a int
        blongname: float, #: comment for b with a long name
                          #: multi line comment for it
        cshort : list,    #: somecomment for c
        ....              # many more lines
    ) -> list:            #: return a list that contains the results
    """summary doc string"""
    pass
```

This format is very clear for documentation and are also very easy (and efficient) to modify (i'm a vim user, do modifications between lines is much easier than do modification in rows)

and I want it to be equivalent to this code

```
def somefunc( a : int, blongname: float, cshort : list, ... more args): -> list
    """summary doc string
       Args:
           a: a is a int
           blongname: comment for b with a long name
                      multi line comment for it
           cshort : somecomment for c
           ....# many more lines
    """
    pass
```
Since we have supported doc comment for class attributes, can we add doc comment support for func definition?

**Comment by AA-Turner** [comment]
You're welcome to create a Sphinx extension to implement this, but as of now it isn't planned for core Sphinx.

A
