### ISSUE TITLE
Sphinx 5.2.0: self-triggered warning `Pygments lexer name 'pycon3' is not known`

### ISSUE THREAD

**Issue by neutrinoceros** [sphinx-doc/sphinx#10861]
### Describe the bug

Sphinx 5.2.0 broke unyt's docs, see https://github.com/yt-project/unyt/issues/274

```
Warning, treated as error:
/home/runner/work/unyt/unyt/docs/index.rst:17:Pygments lexer name 'pycon3' is not known
ERROR: InvocationError for command /home/runner/work/unyt/unyt/.tox/py38-docs/bin/python -m sphinx -M html . _build -W (exited with code 2)
```

### How to Reproduce

```
$ git clone https://github.com/yt-project/unyt
$ cd unyt
$ pip install -r requirements.txt
$ cd docs
$ python -m sphinx -M html "." "_build" -W
```

with `requirements.txt`:
```
pytest
sphinx
numpy
sympy
matplotlib!=3.5.0
dask[array,diagnostics]>=2021.04.1
```

### Expected behavior

no error

### Your project

https://github.com/yt-project/unyt

### OS

seen on Linux and Mac

### Python version

reproduced with 3.8 and 3.10

### Sphinx version

5.2.0

### Sphinx extensions

sphinx.ext.autodoc, sphinx.ext.viewcode, sphinx.ext.doctest, sphinx.ext.napoleon,  sphinx.ext.mathjax

### Additional context

Getting no error with Sphinx 5.1.1

**Comment by AA-Turner** [comment]
[Sphinx 5.2.1](https://pypi.org/project/Sphinx/5.2.1/) has been released with a fix.

A

**Comment by AA-Turner** [comment]
Please let me know if 5.2.1 doesn't fix the issue and I'll re-open.

A

**Comment by neutrinoceros** [comment]
I confirm that the problem is resolved with the new release. Thank you !
