### ISSUE TITLE
Sphinx 5.2.0.post0 error with `sphinx_rtd_theme`: ValueError 'too many values to unpack'

### ISSUE THREAD

**Issue by StratFinancePy** [sphinx-doc/sphinx#10860]
### Describe the bug

Theme error:
[123] An error happened in rendering the page _autosummary/<my module>.
[124] Reason: ValueError('too many values to unpack (expected 3)')

### How to Reproduce

(To be added soon)

### Expected behavior

Proper page rendering as in Sphinx 5.1.1.

### Your project

(Not applicable)

### OS

linux

### Python version

3.10

### Sphinx version

5.2.0

### Sphinx extensions

autosummary

**Comment by StratFinancePy** [comment]
Sorry for the limited information, will try to provide a way to reproduce the issue soon but mostly wanted to flag a regression between 5.1.1 and 5.2.0

**Comment by natt96z** [comment]
[ReadTheDocs](https://readthedocs.org) constantly reproduces the issue when you use the site's build feature.

**Comment by rkdarst** [comment]
I am slightly too late but here is an analysis: https://github.com/sphinx-doc/sphinx/issues/10853#issuecomment-1257153452

But it is actually a sphinx_rtd_theme issue: https://github.com/readthedocs/sphinx_rtd_theme/issues/1343
Either sphinx_rtd_theme needs to release with a fix, or sphinx needs to release without a .post0 release.  The first is technically correct, but the second might happen first.

Suggested issue title: "5.2.0.post0 error with sphinx_rtd_theme, ValueError unpacking version"

**Comment by rkdarst** [comment]
Work around: prohibit the .post0 release in your requirements:
```
sphinx!=5.2.0.post0    # remove after next release
```

Of course this is a massive amount of work for everyone who uses sphinx_rtd_theme, so I hope one of the two will release soon.

**Comment by mara004** [comment]
Same problem with pypdfium2's docs: https://readthedocs.org/projects/pypdfium2/builds/18162606/

**Comment by StratFinancePy** [comment]
thank you very much @rkdarst, I'm indeed using read the doc theme so might be the issue that you linked: https://github.com/sphinx-doc/sphinx/issues/10853#issuecomment-1257153452

**Comment by StratFinancePy** [comment]
happy to close the issue too as it might be specific to read the doc theme

**Comment by rkdarst** [comment]
I think it's better to leave it open (maybe change the title?), since countless people are going to be looking here for a solution until it gets fixed.

**Comment by mara004** [comment]
Yes, seeing this report and the cross-reference to `sphinx_rtd_theme` directly was quite helpful.

**Comment by AA-Turner** [comment]
I will release 5.2.1 shortly.

RTD's theme should really use the version tuple attribute we provide, rather than somewhat clumsily introspecting the string version.

A

**Comment by AA-Turner** [comment]
[Sphinx 5.2.1](https://pypi.org/project/Sphinx/5.2.1/) has been released.

A
