### ISSUE TITLE
highlightSearchWords() is not called after fragments are loaded via AJAX

### ISSUE THREAD

**Issue by mitya57** [sphinx-doc/sphinx#10864]
### Describe the bug

When I build Sphinx' own documentation locally, and search for `example`, search results look like this:
![Screenshot 1](https://user-images.githubusercontent.com/1381584/192156464-a4d60702-bffd-4ad3-8dae-fa2bc520fa10.png)

Only if I go to browser console and call `SphinxHighlight.highlightSearchWords()`, it starts looking like this:
![Screenshot 2](https://user-images.githubusercontent.com/1381584/192156406-aee5af3e-da1c-42ac-b600-87d40644ebed.png)

`highlightSearchWords()` is called on DOMContentLoaded event, but page fragments are loaded separately after that event.

### How to Reproduce

```bash
$ git clone https://github.com/sphinx-doc/sphinx.git
$ cd sphinx
$ python3 ./sphinx/cmd/build.py -T doc build/html/
$ cd build/html
$ python3 -m http.server
$ # open http://127.0.0.1:8000/search.html?q=example
```

### Expected behavior

Search terms are highlighted after all page fragments are loaded.

### Your project

Sphinx itself

### OS

Linux

### Python version

3.10.7

### Sphinx version

5.2.0.post1 and master

**Comment by AA-Turner** [comment]
This is a consequence of the other search highlighting changes, only actual search results are highlighted within search result pages.

A

**Comment by mitya57** [comment]
OK, if you think it's intended behavior, feel free to close it.

But the other thing I want to note is that the current behavior is unstable. Sometimes DOMContentLoaded event occurs after one search result is loaded, and you end up with only one word being highlighted:

![Screenshot 3](https://user-images.githubusercontent.com/1381584/192165461-ea427fd9-bb7a-45d0-b2a8-4a49bc2d44b4.png)

For me it happens even more frequently than no results highlighted at all.
