### ISSUE TITLE
Sphinx v5.2.0.post0: sphinx-rtd-theme Theme error: ValueError('too many values to unpack (expected 3)')

### ISSUE THREAD

**Issue by seanlanter** [sphinx-doc/sphinx#10865]
### Describe the bug

unexpected 'Theme error' from sphinx-rtd-theme
- appears starting with  'Sphinx v5.2.0.post0'
- did not occur in 'Sphinx v5.1.1'

### confirm that 'pip -install -U -r requirments.txt ' runs correctly, where the content of 'requirements.txt' is:
     sphinx
     sphinx-rtd-theme
     sphinx-copybutton
     sphinx-tabs
     sphinxcontrib-napoleon
     sphinx-autobuild
     pyyaml
     flask
     flask_cors

### run the build command:
     sphinx-build -b html -a -W <source-dir> <output-dir>

### observe the output:
     Running Sphinx v5.2.0.post0
     loading intersphinx inventory from https://docs.python.org/3/objects.inv...
     building [mo]: all of 0 po files
     building [html]: all source files
     updating environment: [new config] 19 added, 0 changed, 0 removed
     reading sources... [100%] tutorial/wander                                                                    
     looking for now-outdated files... none found
     pickling environment... done
     checking consistency... done
     preparing documents... done
     writing output... [  5%] background/4kinds                                                                   
     Theme error:
     An error happened in rendering the page background/4kinds.
     Reason: ValueError('too many values to unpack (expected 3)')

### Expected behavior

No 'Theme error'.

### Your project

https://gitlab.com/cnxeng/wordsmith

### OS

Mac Monterey 12.5.1, Windows 10

### Python version

3.10

### Sphinx version

5.2.0.post0

### Sphinx extensions

sphinx.ext.autodoc, sphinx.ext.doctest, sphinx.ext.intersphinx, sphinx.ext.todo, sphinx.ext.coverage, sphinx.ext.imgmath, sphinx.ext.mathjax, sphinx.ext.ifconfig, sphinx.ext.viewcode, sphinx.ext.githubpages, sphinx_copybutton, sphinx_tabs.tabs, sphinx.ext.napoleon, sphinx.ext.autosectionlabel

**Comment by rouault** [comment]
I also reproduce that with GDAL doc builds that have started to fail starting with this job https://github.com/OSGeo/gdal/actions/runs/3122251004/jobs/5064218826 (using v5.2.0.post0) whereas previous job https://github.com/OSGeo/gdal/actions/runs/3114759364/jobs/5050956471 (using 5.1.1) is succesful.

**Comment by AA-Turner** [comment]
Duplicates https://github.com/sphinx-doc/sphinx/issues/10860

A
