### ISSUE TITLE
Changelog says 5.2.0 (development), but it is released

### ISSUE THREAD

**Issue by andreasabel** [sphinx-doc/sphinx#10862]
### Describe the bug

Changelog says 5.2.0 (development), but it is released

### How to Reproduce

Changelog says 5.2.0 (development), but it is released

### Expected behavior

Changelog says 5.2.0 (development), but it is released

### Your project

Changelog says 5.2.0 (development), but it is released

### Screenshots

Changelog says 5.2.0 (development), but it is released

### OS

Changelog says 5.2.0 (development), but it is released

### Python version

Changelog says 5.2.0 (development), but it is released

### Sphinx version

Changelog says 5.2.0 (development), but it is released

**Comment by AA-Turner** [comment]
I've merged 5.x into master.

A
