### ISSUE TITLE
permissions 700 after pip install, should be a+rx?

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1087]
Hello,

I already had yum installed the python-jinja2 package from epel, when I did 'sudo pip install sphinx', it left the permissions in my site-packages as 700 for the following

```
#!shell

ls -tl /usr/lib/python2.6/site-packages
drwx------   2 root root   4096 Jan 19 16:25 docutils-0.10-py2.6.egg-info
drwx------   8 root root   4096 Jan 19 16:25 docutils
drwx------   2 root root   4096 Jan 19 16:25 Jinja2-2.6-py2.6.egg-info
drwx------   4 root root   4096 Jan 19 16:25 jinja2
drwx------   2 root root   4096 Jan 19 16:25 Pygments-1.6rc1-py2.6.egg-info
drwx------   6 root root   4096 Jan 19 16:25 pygments
drwx------   2 root root   4096 Jan 19 16:25 Sphinx-1.1.3-py2.6.egg-info
drwx------  14 root root   4096 Jan 19 16:25 sphinx

uname -a:  Linux centos6.laptop 2.6.32-279.19.1.el6.i686 #1 SMP Wed Dec 19 04:30:58 UTC 2012 i686 i686 i386 GNU/Linux
umask is: 0022
```

Most packages I've installed come with dir's and executables 755, and read-only files 744.

Thank you!

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1087
- Originally reported by: Anonymous
- Originally created at: 2013-01-20T01:53:05.855

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2013-01-20 01:23:47+00:00_

It is not Sphinx issue (and not pip issue too).

I think your root's umask need to set to '022' instead of '077'.

**Comment by jelmd** [comment]
No - the problem is the brain damaged pip.
