### ISSUE TITLE
WARNING: Could not lex literal_block as "python". Highlighting skipped.

### ISSUE THREAD

**Issue by Sdaher21** [sphinx-doc/sphinx#10891]
### Describe the bug

I can see syntax highlighting in Visual Studio code but not when I generate through Sphinx:
According to my requirements.txt, I'm using Sphinx==3.2.1 and Pygments==2.6.1:

![image](https://user-images.githubusercontent.com/66412207/193456890-092ca4b5-68cd-4ea8-80fe-093affb0112a.png)

### How to Reproduce

NA

### Your project

NA

### OS

Linux

### Python version

3.8

### Sphinx version

3.2.1

**Comment by AA-Turner** [comment]
This isn't python code, so it can't be highlighted as python code. Please look at the Pygments lexers, you probably want one of the bash or console lexers.

Also, please update to Sphinx 5.2.x, Sphinx 3 is old and unsupported.

A
