### ISSUE TITLE
Exception in `sphinx-build`, dumping object inventory... failed

### ISSUE THREAD

**Issue by arengel** [sphinx-doc/sphinx#10904]
### Describe the bug

When running `sphinx-build`, towards the end I get the following exception. Full log also included below.

```
dumping object inventory... failed

Exception occurred:
  File "/Users/aengel/miniconda3/envs/dispatch/lib/python3.10/re.py", line 209, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
```

[sphinx-err-wbup6r8q.log](https://github.com/sphinx-doc/sphinx/files/9740245/sphinx-err-wbup6r8q.log)

### How to Reproduce

```
$ git clone https://github.com/rmi-electricity/dispatch.git@dev
$ cd dispatch
$ conda env create --name dispatch --file environment.yml
$ sphinx-build -b html docs docs/_build/html
```

After most of the build completes, the error shows up. It seems like most of the docs are in fact generated but the error causes `tox` and other tools to fail. 

### Expected behavior

Expect `sphinx-build` to complete without errors or exceptions.

### Your project

https://github.com/rmi-electricity/dispatch

### OS

macOS 12.6

### Python version

3.10.6 (CPython)

### Sphinx version

5.2.3

### Sphinx extensions

"sphinx.ext.doctest",     "sphinx.ext.intersphinx",     "sphinx.ext.napoleon",     "sphinx.ext.todo",     "sphinx.ext.viewcode",     "autoapi.extension",     "sphinx_issues",

**Comment by AA-Turner** [comment]
Could you try disabling the extensions you use, to check if this is an issue with 3rd party extensions, 1st party, or core Sphinx?

A

**Comment by arengel** [comment]
Thanks for the suggestion! That didn't solve it but provided a more intuitive error. Getting the package version using `from importlib.metadata import version` is dangerous if you leave that `version` in the namespace. My `conf.py` only defined `release` so I didn't realize that sphinx was expecting `version` to be a `str`, not a function.

**Comment by anernest** [comment]
Thank you @arengel. Saved me a ton of time.
