### ISSUE TITLE
make html && make latexpdf fails with: *** No rule to make target 'all-pdf'.  Stop.

### ISSUE THREAD

**Issue by marxin** [sphinx-doc/sphinx#10903]
### Describe the bug

It's caused by my b1390c4191319e75d14ce3e6e73ef43c31d981b4 where now the following happens:

```
$ make clean ; make html  SPHINXBUILD=~/bin/venv/bin/sphinx-build && make latexpdf SPHINXBUILD=~/bin/venv/bin/sphinx-build
...
Running LaTeX files through pdflatex...
make LATEXMKOPTS="-interaction=nonstopmode -f" -C _build/latex all-pdf
make[1]: Entering directory '/home/marxin/Programming/texi2rst-generated/sphinx/gdc/_build/latex'
make[1]: *** No rule to make target 'all-pdf'.  Stop.
make[1]: Leaving directory '/home/marxin/Programming/texi2rst-generated/sphinx/gdc/_build/latex'
make: *** [Makefile:58: latexpdf] Error 2
```

Where `_build/latex/` is an empty directory. Is there anything I forgot to change in the aforementioned commit or should I revert it?
@AA-Turner 

### How to Reproduce

See steps above.

### Your project

Sphinx

### OS

Linux

### Python version

3.10

### Sphinx version

master

**Comment by jfbu** [comment]
You can see same phenomenon emitting three successive commands in your shell:
- `make clean`
- `make html`
- `make man`
Then `_build/man` is actually empty and man build did not happen.

I did not investigate why but if last step is replaced by `make text`, the `_build/text/index.txt` is created.  But `make texinfo` behaves like `make latex` or `make man`: nothing in the corresponding build directories appears.

I am not familiar enough with builders/__init__.py, but indeed this commit should be reverted or problem fixed prior to release, naturally.  I marked it as regression but it has not yet made it to a release... only to stamp it as a "must-fix" issue ;-)

**Comment by jfbu** [comment]
> I did not investigate why but if last step is replaced by `make text`

It appears `to_build` in `build_update()` from `builders/__init__.py` is then a generator not a string and `list(to_build)` produces the list `['index']` and not `['__all__']`  so the https://github.com/sphinx-doc/sphinx/commit/b1390c4191319e75d14ce3e6e73ef43c31d981b4 logic does not inhibit the build process then.

**Comment by marxin** [comment]
All right, so it's likely related to the fact the some builders don't inform about outdated docs and they rather return a string which means effectively a rebuild:

https://github.com/sphinx-doc/sphinx/blob/c51a88da8b7b40e8d8cbdb1fce85ca2346b2b59a/sphinx/builders/manpage.py#L40-L41

https://github.com/sphinx-doc/sphinx/blob/c51a88da8b7b40e8d8cbdb1fce85ca2346b2b59a/sphinx/builders/latex/__init__.py#L127-L128

That said, one can't effectively distinguish when a rebuild is needed or not. Thus I'm going to revert my commit.

On the other hand, HTML has a more fine-grained control over the outdated docs:
https://github.com/sphinx-doc/sphinx/blob/c51a88da8b7b40e8d8cbdb1fce85ca2346b2b59a/sphinx/builders/html/__init__.py#L402-L415

**Comment by AA-Turner** [comment]
I wonder if the right fix here is ensuring a consistent contract in `get_outdated_docs`? I'll merge the revert though for now.

A

**Comment by marxin** [comment]
> I wonder if the right fix here is ensuring a consistent contract in `get_outdated_docs`?

I hope so, though I'm not familiar enough with the code.

**Comment by floam** [comment]
It'd sure be nice if the manpages didn't have to rebuild each time.
