### ISSUE TITLE
Freeze during generation of HTML (with typing)

### ISSUE THREAD

**Issue by mikir** [sphinx-doc/sphinx#10907]
### Describe the bug

In case of using python typing module, Sphinx freeze has been observed during HTML generation using automodapi extension. Example of the source which causes the freeze:

```
import typing

class Bar:
    def type_info():
        return None

    ROW_ANNOTATION = typing.Tuple[
        str]
```

conf.py:

```
extensions = ['sphinx_automodapi.automodapi']
```

index.rst:

```
.. automodapi:: bar
```

### How to Reproduce

```
cat > conf.py << EOF
extensions = ['sphinx_automodapi.automodapi']
EOF
cat > index.rst << EOF
.. automodapi:: bar
EOF
cat > bar.py << EOF
import typing

class Bar:
    def type_info():
        return None

    ROW_ANNOTATION = typing.Tuple[
        str]
EOF
python3 -m virtualenv pyenv
source pyenv/bin/activate
pip install sphinx pytest sphinx_automodapi
PYTHONPATH=. sphinx-build  -b html . html_python
```

### Expected behavior

No freeze, HTML output should be generated.

### Your project

N/A

### OS

Linux

### Python version

3.8.10

### Sphinx version

5.2.3

### Sphinx extensions

sphinx_automodapi.automodapi

**Comment by jfbu** [comment]
I tested your example with `sphinx.ext.napoleon` and it doesn't hang at my locale.  I used
```
.. automodule:: bar
   :members:
   :undoc-members:
```
and
```
extensions = ['sphinx.ext.napoleon']
```
and have no problem.

Please provide an example with `sphinx.ext.napoleon` so we can investigate.

**Comment by mikir** [comment]
Thanks a lot for quick feedback.

I confirm that the example with `sphinx.ext.napoleon` does not hang. However, it hangs if I ran the example with `sphinx_automodapi.automodapi` before. The reason is directory api generated by `automodapi`. If I remove this directory, `sphinx.ext.napoleon` does not hang again.

It can be that this problem is related only to `sphinx_automodapi.automodapi` extension. I don't know. Please see also, https://github.com/astropy/sphinx-automodapi/issues/154.
