### ISSUE TITLE
sphinx.ext.autosectionlabel and myst_parser does not work

### ISSUE THREAD

**Issue by torbsorb** [sphinx-doc/sphinx#10902]
### Describe the bug

```bash
Extension error (sphinx.ext.autosectionlabel):
Handler <function register_sections_as_label at 0x7fcf255cf910> for event 'doctree-read' threw an exception (exception: 'NoneType' object has no attribute 'parent')
```

### How to Reproduce

Enable sphinx.ext.autosectionlabel and use [myst_parser](https://myst-parser.readthedocs.io/en/latest/faq/index.html#include-markdown-files-into-an-rst-file)

```
.. include:: a_markdown_file.md
   :parser: myst_parser.sphinx_
```

`sphinx.ext.autosectionlabel` configuration:

```python
autosectionlabel_prefix_document = True
autosectionlabel_maxdepth = 2
```

### Expected behavior

No exceptions are thrown during build.

### Your project

Private repo

### OS

Ubuntu 20.04 in WSL2 on Windows

### Python version

Python 3.10.

### Sphinx version

Tested on 4.4.0 and 4.5.0

### Sphinx extensions

sphinx.ext.autosectionlabel, myst_parser

### Additional context

It works if we accept (cur_node != None) as a valid exit condition for the while-loop in `get_node_depth()`:

```python
def get_node_depth(node: Node) -> int:
    i = 0
    cur_node = node
    while (cur_node != None) and (cur_node.parent != node.document):
        cur_node = cur_node.parent
        i += 1
    return i
```

The correct solution might be that the `myst_parser` extension should set parent node correctly in the first place, and not leave it as None.

**Comment by AA-Turner** [comment]
Will close here until confirmed as a bug in Sphinx rather than MyST.

A
