### ISSUE TITLE
v5.2.3 bug Fail to define brpc::ENOSERVICE(1001) which is already defined as `unknown error 1001'

### ISSUE THREAD

**Issue by wangwg1** [sphinx-doc/sphinx#10917]
### Describe the bug

v5.2.3 bug Fail to define brpc::ENOSERVICE(1001) which is already defined as `unknown error 1001'
but this bug not found in v4.4.0

### How to Reproduce

```
$ git clone https://github.com/secretflow/secretflow.git
$ conda create -n sf python=3.8
$ conda activate sf
$ cd docs
$ ./build.sh -l en
or
$ ./build.sh -l zh_CN
```
en or zh_CN all error

### Your project

5.2.3

### OS

linux

### Python version

3.8.3

### Sphinx version

5.2.3

**Comment by AA-Turner** [comment]
Please provide a minimal reproducer without conda.

A
