### ISSUE TITLE
Pandoc missing

### ISSUE THREAD

**Issue by joacorapela** [sphinx-doc/sphinx#10923]
### Describe the bug

I have a Github action to build my Sphinx docs and move them to a Github page
https://github.com/joacorapela/svGPFA/actions/workflows/docs.yml

These Sphinx docs include a Jupyter (*.ipynb) notebook. Locally the documentation builds fine, but when the Github action runs it fails with the following message:

> Notebook error:
> PandocMissing in ipynb/doEstimateAndPlot_defaultInitialParams.ipynb:
> Pandoc wasn't found.
> Please check that pandoc is installed:
> https://pandoc.org/installing.html
> make: *** [Makefile:22: html] Error 2

https://github.com/joacorapela/svGPFA/actions/runs/3260313559

### How to Reproduce

GitHub Action workflow:

> name: docs
> on: [push, pull_request, workflow_dispatch]
> jobs:
>   docs:
>     runs-on: ubuntu-latest
>     steps:
>       - uses: actions/checkout@v2
>       - uses: actions/setup-python@v2
>       - name: Install Pandoc
>         uses: r-lib/actions/setup-pandoc@9598b8eeb6d88de7d76d580d84443542bbfdffce
>         with:
>           pandoc-version: 2.11.1.1
>       - name: Install dependencies
>         run: |
>           pip install -e .[notebook]
>       - uses: ammaraskar/sphinx-action@master
>         with:
>           docs-folder: "docs/sphinx"
>       - name: Deploy
>         uses: peaceiris/actions-gh-pages@v3
>         if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
>         with:
>           publish_branch: gh-pages
>           github_token: ${{ secrets.GITHUB_TOKEN }}
>           publish_dir: docs/sphinx/build/html
>           force_orphan: true

It seems that the Pandoc installation in step ``Install Pandoc`` succeeds:

> Preparing to unpack .../pandoc-2.11.1.1-1-amd64.deb ...
> Unpacking pandoc (2.11.1.1-1) ...
> Setting up pandoc (2.11.1.1-1) ...
> Processing triggers for man-db (2.9.1-1) ...

### Environment Information

I cannot find ttps://github.com/AA-Turner/sphinx/archive/refs/heads/5.x.zip

### Sphinx extensions

extensions = ['sphinx.ext.autodoc', 'sphinx.ext.doctest',               'sphinx.ext.intersphinx', 'sphinx.ext.todo',               'sphinx.ext.ifconfig', 'sphinx.ext.viewcode',               'sphinx.ext.graphviz', 'sphinx.ext.inheritance_diagram',               'sphinx.ext.autosummary', 'sphinxcontrib.bibtex',               'nbsphinx',              ]

**Comment by joacorapela** [comment]
Fixed the problem by adding
>>          sudo apt install -y pandoc
to step Install Dependencies.

**Comment by AA-Turner** [comment]
Locally, you have pandoc installed. On CI, it isn't. Closing as this isn't a Sphinx issue (we don't even support notebooks!), but hopefully installing pandoc on your CI will fix for you.

A
