### ISSUE TITLE
Missing urllib3 dependency

### ISSUE THREAD

**Issue by XuanWang-Amos** [sphinx-doc/sphinx#10927]
### Describe the bug

We encountered an issue early that Sphinx failed with the following error message:
```
Extension error:
Could not import extension sphinx.builders.linkcheck (exception: No module named 'urllib3')
```

After investigation, we found that we didn't install urllib3 in our docker thus caused this issue, urllib3 was [added couple months ago](https://github.com/sphinx-doc/sphinx/blob/c40bb7281ec26c833aa7e0f792f063b2d2254ec7/sphinx/util/requests.py#L10) and [not listed as dependencies](https://github.com/sphinx-doc/sphinx/blob/bf36a7905a3eee8fc49924b137612333454c9cb8/pyproject.toml#L59-L77) so it wasn't auto installed when we build Sphinx, can we include urllib3 as new dependency?

### How to Reproduce

``git clone``
```bash
$ git clone https://github.com/grpc/grpc
$ cd grpc
$ pip install -r requirements.txt
$ ./tools/distrib/docgen/all_lang-docgen.sh
```

### Environment Information

N/A

**Comment by AA-Turner** [comment]
I appreciate we don't declare the explicit dependency, but I believe `urllib3` should be installed via `requests`, which we do depend on. Are you able to re-install Sphinx and check if `requests` was installed and if so which version?

A

**Comment by XuanWang-Amos** [comment]
Thanks for the reply, we have `requests 2.14.2` installed which is pretty old, but since Sphinx only require 2.5.0  it's sufficient: https://github.com/sphinx-doc/sphinx/blob/bf36a7905a3eee8fc49924b137612333454c9cb8/pyproject.toml#L73

I checked the release history for requests, looks like for 2.14.2 urllib3 is embedded rather than required (2.14.2 project description said `powered by urllib3 <https://github.com/shazow/urllib3>,
which is embedded within Requests`.

So instead of declare the dependency, maybe we can consider bump the required `requests` version?

**Comment by AA-Turner** [comment]
2.16 is the oldest, 2.25 seems reasonable as a newer version, would you mind sending a PR?

A

**Comment by XuanWang-Amos** [comment]
Sure, just created one :)
