### ISSUE TITLE
sidebar links have increased a lot since Sphinx 5.2

### ISSUE THREAD

**Issue by xqt** [sphinx-doc/sphinx#10942]
### Describe the bug

Every attribute, method or function is placed to the sidebar links as a header and there is no ability to reduce the link depth there.

### How to Reproduce

https://doc.wikimedia.org/pywikibot/master/utilities/scripts_ref.html
shows the result for Sphinx 5.3 and
https://doc.wikimedia.org/pywikibot/stable/utilities/scripts_ref.html
shows the rsult for Sphinx 5.1.1

The source is mostly equal and can be found at
https://doc.wikimedia.org/pywikibot/master/_sources/utilities/scripts_ref.rst.txt and 
https://doc.wikimedia.org/pywikibot/stable/_sources/utilities/scripts_ref.rst.txt

### Environment Information

```text
Platform:              win32; (Windows-10-10.0.17763-SP0)
Python version:        3.11.0rc2 (main, Sep 11 2022, 20:22:52) [MSC v.1933 64 bit (AMD64)])
Python implementation: CPython
Sphinx version:        5.3.0
Docutils version:      0.17.1
Jinja2 version:        3.1.2
```

### Sphinx extensions

```
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.autosectionlabel',
    'sphinx.ext.autosummary',
    'sphinx.ext.extlinks',
    'sphinx.ext.napoleon',
    'sphinx.ext.todo',
    'sphinx.ext.viewcode',
]
```

**Comment by AA-Turner** [comment]
This is not a bug. See https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-toc_object_entries_show_parents, https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-toc_object_entries, and https://github.com/sphinx-doc/sphinx/issues/6316.

A

**Comment by electric-coder** [comment]
@AA-Turner these two posts should be tagged toctree.
