### ISSUE TITLE
Broken examples of sphinx.ext.inheritance_diagram

### ISSUE THREAD

**Issue by marxin** [sphinx-doc/sphinx#10948]
### Describe the bug

I think the examples are broken:
https://www.sphinx-doc.org/en/master/usage/extensions/inheritance.html#examples

### How to Reproduce

Take a look at the docs.

### Environment Information

Linux

**Comment by namurphy** [comment]
We ran into this issue too, over at https://github.com/PlasmaPy/PlasmaPy/issues/1838.  It looks like there were some recent [releases of `graphviz`](https://gitlab.com/graphviz/graphviz/-/releases), so I'm wondering if something is happening associated with that.  

For reference, the error on https://www.sphinx-doc.org/en/master/usage/extensions/inheritance.html#examples is still happening:

digraph inheritance02ef59160f { bgcolor=transparent; rankdir=LR; size="8.0, 12.0"; "docutils.parsers.rst.Directive" [URL="../../extdev/markupapi.html#docutils.parsers.rst.Directive",fillcolor=white,fontname="Vera Sans, DejaVu Sans, Liberation Sans, Arial, Helvetica, sans",fontsize=10,height=0.25,shape=box,style="setlinewidth(0.5),filled",target="_top",tooltip="Base class for reStructuredText directives."]; "sphinx.ext.inheritance_diagram.InheritanceDiagram" [fillcolor=white,fontname="Vera Sans, DejaVu Sans, Liberation Sans, Arial, Helvetica, sans",fontsize=10,height=0.25,shape=box,style="setlinewidth(0.5),filled",tooltip="Run when the inheritance_diagram directive is first encountered."]; "sphinx.util.docutils.SphinxDirective" -> "sphinx.ext.inheritance_diagram.InheritanceDiagram" [arrowsize=0.5,style="setlinewidth(0.5)"]; "sphinx.util.docutils.SphinxDirective" [URL="../../extdev/utils.html#sphinx.util.docutils.SphinxDirective",fillcolor=white,fontname="Vera Sans, DejaVu Sans, Liberation Sans, Arial, Helvetica, sans",fontsize=10,height=0.25,shape=box,style="setlinewidth(0.5),filled",target="_top",tooltip="A base class for Sphinx directives."]; "docutils.parsers.rst.Directive" -> "sphinx.util.docutils.SphinxDirective" [arrowsize=0.5,style="setlinewidth(0.5)"]; }

**Comment by marxin** [comment]
As seen here https://readthedocs.org/projects/sphinx/builds/18938758/ I can confirm the issue is caused by missing `dot` package:

```
WARNING: dot command 'dot' cannot be run (needed for graphviz output), check the graphviz_dot setting

```
