### ISSUE TITLE
Search is not working in Brave Browser

### ISSUE THREAD

**Issue by ikus060** [sphinx-doc/sphinx#10950]
### Describe the bug

When browsing the documentation generated by SPhinx, the search is not working. Looking at the browser console, a DOM exception is raised.

```
Uncaught DOMException: Window.localStorage getter: Forbidden in a sandboxed document without the 'allow-same-origin' flag.
```

### How to Reproduce

You may access the documentation here

https://nexus.ikus-soft.com/repository/archive/rdiffweb/2.4.9/doc/search.html?q=pip

### Environment Information

Not sure

### Sphinx extensions

sphinx_md, recommonmark sphinx-markdown-tables

### Additional context

N/A

**Comment by jdillard** [comment]
Seems to work for me in Brave: 
![image](https://user-images.githubusercontent.com/3474095/204964968-b1ff40fb-18f0-4f4c-ad8c-0b0c04338688.png)

The only thing that is blocked is the Google Tag Manager. It may be a configuration/plugin issue.

**Comment by ikus060** [comment]
I forgot to come back and explain the problem. Nothing related to Sphinx.

Nexus server, the server used to host the documentation added a security feature to sandbox the content of sphinx documentation. 

I've disable that feature to get the search working:
```
nexus.repository.sandbox.enable=false
```
