### ISSUE TITLE
`sphinx-build -M html -c .` sets the config dir to be `./html`

### ISSUE THREAD

**Issue by gwerbin** [sphinx-doc/sphinx#10968]
### Describe the bug

```text
$ sphinx-build -M html -c . ./source ./build -W

Running Sphinx v5.3.0

Configuration error:
config directory doesn't contain a conf.py file (<elided>/my-project/docs/html)
```

This seems like a bug. I was under the impression that `-c` set the configuration directory, and that the source and build directories would be set relative to the config directory. Why is `sphinx-build` looking in the nonexistent `./html` directory for my config file, when I asked it to look in `.`?

### How to Reproduce

```text
$ mv source/conf.py ./conf.py
$ sphinx-build -M html -c . ./source ./build -W
```

### Environment Information

```text
Platform:              darwin; (macOS-12.4-arm64-arm-64bit)
Python version:        3.10.7 (main, Nov  2 2022, 03:06:32) [Clang 13.1.6 (clang-1316.0.21.2.5)])
Python implementation: CPython Sphinx version:        5.3.0
Docutils version:      0.19
Jinja2 version:        3.1.2
```

### Sphinx extensions

N/A

### Additional context

I apologize if this is due to my misunderstanding of how `-c` works. However, if that's the case, the docs are very unclear, and I offer that this is probably still a "docs bug".

**Comment by gwerbin** [comment]
@AA-Turner I just saw that this was closed. Is it for lack of contributions? I can try to clarify the documentation if that's all that's needed.

**Comment by AA-Turner** [comment]
Hi Greg,

That would be really appreciated, thank you! The issue here is that `-M` requires the source and output directories to be passed before any options.

A

**Comment by jdillard** [comment]
Looks like this is the section of the docs that needs to be updated: https://www.sphinx-doc.org/en/master/man/sphinx-build.html#cmdoption-sphinx-build-M

**Comment by jdillard** [comment]
The docs were updated in https://github.com/sphinx-doc/sphinx/pull/11992
