### ISSUE TITLE
toctree includes classes and functions

### ISSUE THREAD

**Issue by electric-coder** [sphinx-doc/sphinx#10976]
### Describe the bug

Currently the `.. toctree::` directive includes (displays) classes and methods when it should only include sections and `.rst` files.

### How to Reproduce

Single `my_module.py`:
```py
class MyClass:
    """a test docstring."""
    pass
```

Single `toctree_bug_test.rst`
```rst
title this
==========

.. module:: my_package.my_module

    .. autoclass:: MyClass
```

Minimal `index.rst`:
```rst
.. toctree::
   :maxdepth: 2
   :caption: Contents:

   toctree_bug_test
```

Minimal `conf.py`:
```py
import os
import sys

sys.path.insert(0, os.path.abspath(os.path.join('..', '..', 'src')))

extensions = [
    'sphinx.ext.autodoc',
]

templates_path = ['_templates']
exclude_patterns = []

html_theme = 'alabaster'
html_static_path = ['_static']
```

Example screenshot, the class that shouldn't be shown in the toctree is highlighted:

![toctree_bug_sphinx1](https://user-images.githubusercontent.com/60424310/202329968-86ba7a8b-a51c-4568-8756-316560b1b2e6.png)

### Environment Information

Platform:              win32; (Windows-10-10.0.19041-SP0) Python version:        3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)]) Python implementation: CPython Sphinx version:        5.3.0 Docutils version:      0.19 Jinja2 version:        3.1.2

### Sphinx extensions

``sphinx.ext.autodoc``

A few questions are necessary:

1. Is this a bug or intended behavior? Sphinx didn't used to behave like this.
2. If it's intended behavior how to disable it?
3. If it's a bug what Sphinx version should be used in the meanwhile?

**Comment by AA-Turner** [comment]
This is a new feature, please check the changelog and other (closed) bugs: https://www.sphinx-doc.org/en/master/changes.html

https://github.com/sphinx-doc/sphinx/issues/10942#issuecomment-1295271524

A
