### ISSUE TITLE
Improving support for ultrawide screeens

### ISSUE THREAD

**Issue by apinski-cavium** [sphinx-doc/sphinx#10970]
### Describe the bug

Generated sphinx web sites get are centered in the window when used on an ultrawide screen and have so much white space on both sides. Rather than allowing the text to flow, it makes it feel unnatural.
This is a general problem with many modern web sites with ultrawide screens. I wish people would stop assuming the max width of a page and do the right thing.

I filed this with GCC since they moved over to sphinx this week but I suspect it is a foundmental issue with sphinx in general.
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=107644

**Comment by AA-Turner** [comment]
I am unsure what the issue is here, what specifically do you wish to see changed?

A

**Comment by apinski-cavium** [comment]
I want sphinx generated html do allow the browser to do the word wrapping rather than causing it to be only a fixed size.
It seems like most modern web sites decided the screen was a specific size and they would fit into that window only. But didn't we learn from the last 20 years that was bad behavior of saying a max size of the window?

**Comment by AA-Turner** [comment]
OK, this isn't an issue in Sphinx. The theme GCC uses is Furo, you are welcome to raise the issue there though I doubt the design of the theme will change.

A
