### ISSUE TITLE
5.3.0: `:option:` directive doesn't ignore orphan pages anymore

### ISSUE THREAD

**Issue by bastimeyer** [sphinx-doc/sphinx#10987]
### Describe the bug

According to the changelog, Sphinx 5.3.0 recently had a change in regards to its `:option:` directive, submitted by @marxin in #10840.

This unfortunately broke our docs:
We have a custom argparse extension which reads all available CLI arguments, does some help text modifications and prints out various `.. option::` directives. This extension gets called by the docs' cli page and the orphaned man page, as both need to list those CLI args. Since 5.3.0 however, all `:option:` directives across the docs now link to the orphaned man page instead of the cli page, which breaks our HTML docs.

Downgrading Sphinx to 5.2.3 fixes the issue.

### How to Reproduce

`Sphinx>5.2.3`

```bash
$ git clone https://github.com/streamlink/streamlink.git
$ cd streamlink
$ rm -rf ~/venv/streamlink-docs
$ virtualenv ~/venv/streamlink-docs
$ source ~/venv/streamlink-docs/bin/activate
$ pip install -e . -r docs-requirements.txt
$ pip list | grep Sphinx
$ make --directory=docs clean html
$ grep _man.html docs/_build/html/cli/config.html
```

`Sphinx==5.2.3`

```bash
$ git clone https://github.com/streamlink/streamlink.git
$ cd streamlink
$ rm -rf ~/venv/streamlink-docs
$ virtualenv ~/venv/streamlink-docs
$ source ~/venv/streamlink-docs/bin/activate
$ pip install -e . -r docs-requirements.txt sphinx==5.2.3
$ pip list | grep Sphinx
$ make --directory=docs clean html
$ grep _man.html docs/_build/html/cli/config.html
```

### Environment Information

```text
Platform:              linux; (Linux-5.17.0-rc6-1-git-01605-ge997b82745a5-x86_64-with-glibc2.36)
Python version:        3.10.8 (main, Nov  1 2022, 14:18:21) [GCC 12.2.0])
Python implementation: CPython
Sphinx version:        5.3.0
Docutils version:      0.19
Jinja2 version:        3.1.2
```

### Additional context

https://github.com/streamlink/streamlink/issues/4988

**Comment by marxin** [comment]
Hey, sorry for the trouble, let's work on fixing that. So it comes from the following hunk:
https://github.com/sphinx-doc/sphinx/blob/cd3f2e435000835dd98a11497440bc16a79ec31c/sphinx/domains/std.py#L783-L785

which now registers an option if it's new and not registered yet. That's not your case as you define duplicate `cmdoption`s.

So generally speaking one should not define duplicate options and that can be addressed:
1. using a `.. program::` directive that will create "namespaces" for options
2. conditional build that will build `_man.html` only? Btw. why do you build HTML version of a manual page? What about using [`..only:: man`](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-only)

**Comment by bastimeyer** [comment]
`.. only:: man` generates a warning (`WARNING: document isn't included in any toctree`) in both `html` and `man` builds, and we're treating warnings as errors (via `-W`), so this doesn't work.

Moving the man page into a separate build so that no duplicate `option`s are defined requires restructuring our entire docs and argparse help texts, because of certain references that are included for the HTML docs. It doesn't look like this can be done without much effort.

The `.. program:: ...` solution fixes the links in the docs, but this duplicates everything in the `genindex.html` (also an issue without the distinctive namespace).

**Comment by marxin** [comment]
I think the cleanest approach would be ignoring `_man.rst` for `html` builder, try this:

```patch
diff --git a/docs/Makefile b/docs/Makefile
index a7da25fa..e4900022 100644
--- a/docs/Makefile
+++ b/docs/Makefile
@@ -114,7 +114,7 @@ text:
 	@echo "Build finished. The text files are in $(BUILDDIR)/text."
 
 man:
-	$(SPHINXBUILD) -b man $(ALLSPHINXOPTS) $(BUILDDIR)/man
+	$(SPHINXBUILD) -b man $(ALLSPHINXOPTS) -t man $(BUILDDIR)/man
 	@echo
 	@echo "Build finished. The manual pages are in $(BUILDDIR)/man."
 
diff --git a/docs/conf.py b/docs/conf.py
index 0da15976..344269b5 100644
--- a/docs/conf.py
+++ b/docs/conf.py
@@ -67,6 +67,10 @@ release = streamlink_version
 # directories to ignore when looking for source files.
 exclude_patterns = ['_build', '_applications.rst']
 
+# Exclude _man.rst if we are not building manual pages
+if not tags.tags.get('man'):
+    exclude_patterns.append('_man.rst')
+
 # The reST default role (used for this markup: `text`) to use for all documents.
 #default_role = None


```

**Comment by marxin** [comment]
And you can also remove `:orphan:` for both `_man.rst` and `_applications.rst`.

**Comment by bastimeyer** [comment]
Thanks for taking the time looking at this and helping getting this fixed. I had already tried adding tags, but couldn't get it to work properly. This seems like a good solution, thanks. :+1:

I'm going to close this now, because as you said, defining the `option`s more than once should be avoided, so the changes in the 5.3.0 release are not to be blamed for this.

**Comment by marxin** [comment]
You're welcome, I think we found the sane approach.
