### ISSUE TITLE
Add retries to the linkcheck builder

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1099]
I'm using Sphinx in a continuous integration environment, and the linkcheck target is part of one of the jobs. 
Sometimes external links fail due to transient network issues, and it would be nice if the builder could be configured to retry checking a broken link.

My Python is pretty bad, but could something similar to [1] be used to extend the linkchecker?

[1] https://gist.github.com/anonymous/4738646

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1099
- Originally reported by: Kristian Kolev
- Originally created at: 2013-02-08T13:26:40.147

**Comment by alex** [comment]
Been hitting this one as well, configurable retry would be fantastic.

**Comment by keimlink** [comment]
Great idea! Testing documentation on CI is an important task.

**Comment by alex** [comment]
If I turned the linked gist into a PR, would this be of interest to the sphinx maintainers?

**Comment by birkenfeld** [comment]
Sure!

**Comment by tk0miya** [comment]
@alex Have you already started the work?
Or, I will merge the gist manually. We have hackday tomorrow :-)

**Comment by alex** [comment]
I'm sending a PR as we speak :-)

**Comment by alex** [comment]
#2312
