### ISSUE TITLE
Adding Sphinx-copy button extension would save a lot of time in copying commands.

### ISSUE THREAD

**Issue by VenkataBhaskarr** [sphinx-doc/sphinx#10998]
**Is your feature request related to a problem? Please describe.**

When I am going through getting started documentation in the official Sphinx website I observed that there is no click to copy text button available for commands.

**Describe the solution you'd like**

So if we add the sphinx_copy button extension to it would be great.

**Comment by jdillard** [comment]
A link to the extension: https://github.com/executablebooks/sphinx-copybutton
