### ISSUE TITLE
BUG: lru_cache_wrapper is not JSON serializable

### ISSUE THREAD

**Issue by jorgepiloto** [sphinx-doc/sphinx#10990]
### Describe the bug

Hi developers! 👋🏽

It's Jorge, from the @pyansys/pyansys-core team. We maintain a theme named [ansys-sphinx-theme] that inherits from [pydata-sphinx-theme].

We recently updated to `pydata-sphinx-theme==0.12.0` and our JSON builder started to fail with the following error:

```text
Exception occurred:
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _lru_cache_wrapper is not JSON serializable
```

### How to Reproduce

To reproduce this issue, just run the following commands using the gh command line tool:

```
gh repo clone https://github.com/ansys/ansys-sphinx-theme
gh pr checkout 155
python -m pip install -e .\[doc]\
make -C doc clean json
```

The whole issue can be found in https://github.com/ansys/ansys-sphinx-theme/pull/155. Use this branch to reproduce it. We are using the latest Sphinx version.

### Environment Information

```text
Platform:              linux; (Linux-5.15.0-53-generic-x86_64-with-glibc2.35)
Python version:        3.10.6 (main, Nov  2 2022, 18:53:38) [GCC 11.3.0])
Python implementation: CPython
Sphinx version:        5.3.0
Docutils version:      0.18.1
Jinja2 version:        3.1.2
```

### Sphinx extensions

```python
# Sphinx extensions
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "numpydoc",                 # Using numpydoc==1.5.0 
    "sphinx.ext.intersphinx",
    "notfound.extension",       # Using sphinx-notfound-page==0.8.3
    "sphinx_copybutton",        # Using sphinx-copybutton==0.5.1
    "ansys_sphinx_theme",       # Using development version
]
```

**Comment by jorgepiloto** [comment]
Pinging here @choldgraf, as I was able to reproduce this issue directly within the `pydata-sphinx-theme`. I just cloned the project, switched the HEAD to v0.12.0, modified the `nox` file to build JSON instead of HTML and got the same error.

**Comment by jorgepiloto** [comment]
I just checked with `pydata-sphinx-theme==0.10.1` and this the JSON builder stopped working in that version, Chris.

**Comment by Revathyvenugopal162** [comment]
Pinging PR https://github.com/pydata/pydata-sphinx-theme/commit/ebf7f704879a1cdc6016d6111062103353ac7677 in which lru-cache implemented, and taking it out, makes the build success.
