### ISSUE TITLE
RTD publishing fails because cannot find myst-parser.  This works locally?

### ISSUE THREAD

**Issue by solarslurpi** [sphinx-doc/sphinx#11006]
### Describe the bug

```
sphinx.errors.ExtensionError: Could not import extension myst_parser (exception: No module named 'myst_parser')
```
- sphonx-autobuild works locally.

- requirements.txt in /docs file includes  `myst-parser==0.18.1`

Can't figure out why RTD fails grabbing documentation from my github.  Help appreciated.  Thank you.

### How to Reproduce

Update doc in github, fails to build docs on RTD web site.

### Environment Information

```text Platform:              linux; (Linux-5.15.76-v7l+-armv7l-with-glibc2.31) Python version:        3.9.2 (default, Mar 12 2021, 04:06:34)  [GCC 10.2.1 20210110]) Python implementation: CPython Sphinx version:        5.3.0 Docutils version:      0.17.1 Jinja2 version:        3.1.2 ```

### Sphinx extensions

myst-parser

### Additional context

project is vs code SSH to  Rasp Pi.

**Comment by jdillard** [comment]
This sounds like a configuration issue with RTD and not Sphinx, I would recommend using the [support channels RTD recommends](https://docs.readthedocs.io/en/stable/support.html).

**Comment by solarslurpi** [comment]
I agree.  Closing.
