### ISSUE TITLE
side-by-side images in rst 

### ISSUE THREAD

**Issue by Ailsa90** [sphinx-doc/sphinx#11029]
I would like to have the images side by side in pdf and html.  I use the sphinx to generate the restructuredtext.  
![image](https://user-images.githubusercontent.com/111339743/207265185-fbd9d97c-5803-4c50-b0bc-0948808c8a41.png)

I have considered using csv-table, but it does not work well for the outlines around the images are awkward. 
.. csv-table::
  :header: 
  :widths: 60, 60

  ".. figure:: ../_static/1.png
    :width: 75mm
    :height: 75mm
    :align: left", ".. figure::  ../_static/2.png
                     :width: 75mm
                     :height: 75mm
                     :align: right
![image](https://user-images.githubusercontent.com/111339743/207264164-4188d945-098a-4990-a8d8-58938be3a25f.png)

**Comment by jdillard** [comment]
> For Q&A purpose, please use Stackoverflow with the tag python-sphinx

https://stackoverflow.com/questions/tagged/python-sphinx

**Comment by Ailsa90** [comment]
Thanks.
I thought side by side images are not supported by sphinx, so I made a feature request. 
I have tried to put the questions in the stakeoverflow, but failed. The reason is that I cannot prove that I am not a robot because I cannot access https://[en.wikipedia.org](https://en.wikipedia.org/wiki/Captcha)/wiki/Captcha in China.
