### ISSUE TITLE
Error with whitespaces in inline literals

### ISSUE THREAD

**Issue by big-r81** [sphinx-doc/sphinx#11028]
### Describe the bug

Whitespaces in inline literals aren't produce correct output results (html).

See this [gist](https://gist.github.com/big-r81/201e9dd4c04fc32a68d890d95cf3a08a) for rst-source and produced output.

### How to Reproduce

Nothing fancy in `conf.py`. ReST-Source in [gist](https://gist.github.com/big-r81/201e9dd4c04fc32a68d890d95cf3a08a).

```bash

$ echo "project = 'Whitespace-Test'
extensions = []

templates_path = ['_templates']
exclude_patterns = []

html_theme = 'alabaster'
html_static_path = ['_static']
" > conf.py

$ sphinx-build -M html . _build
$ open _build/html/index and look at the result
```

### Environment Information

```text
Platform:              darwin; (macOS-10.13.6-x86_64-i386-64bit)
Python version:        3.10.8 (main, Oct 19 2022, 19:54:49) [Clang 10.0.0 (clang-1000.11.45.5)])
Python implementation: CPython
Sphinx version:        5.3.0
Docutils version:      0.19
Jinja2 version:        3.1.2
```

### Sphinx extensions

None

### Additional context

None

**Comment by jfbu** [comment]
Looks like an upstream DocUtils issue. I have not yet checked  [DocUtils inline literals specs](https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#inline-literals) but a priori did not expect this to fail indeed, but I don't have deep knowledge of the details of their specs.

To test, i used `rst2html.py` interactively, for example:

```console
$ rst2html.py --link-stylesheet --strict > out.html
Docutils 0.19 <https://docutils.sourceforge.io>
converting "rst" into "html".
Call with option "--help" for more info.
.. Waiting for source text (finish with Ctrl+D on an empty line):
a `` = ``,
<stdin>:1: (WARNING/2) Inline literal start-string without end-string.
Exiting due to level-2 (WARNING) system message.
```

On the other hand this goes through

```console
$ rst2html.py --link-stylesheet --strict > out.html
Docutils 0.19 <https://docutils.sourceforge.io>
converting "rst" into "html".
Call with option "--help" for more info.
.. Waiting for source text (finish with Ctrl+D on an empty line):
a `` = `` b

$ cat out.html
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="Docutils 0.19: https://docutils.sourceforge.io/" />
<title>&lt;stdin&gt;</title>
<link rel="stylesheet" href=".venv310/lib/python3.10/site-packages/docutils/writers/html4css1/html4css1.css" type="text/css" />
</head>
<body>
<div class="document">


<p>a `` = `` b</p>
</div>
</body>
</html>
```

I will label this as a docutils issue, but as said above I don't know if it is expected or unexpected, but the place to report is at [DocUtils](https://sourceforge.net/projects/docutils/)

**Comment by jfbu** [comment]
[DocUtils](https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#inline-literals) says: ``Line breaks and sequences of whitespace characters are not protected in inline literals.``

But here we see that the behaviour seems also to depend on whether a whitespace follows or not the two closing backticks.  It could be a DocUtils issue.  Our labels got refactored some time ago and we have a ``closed:docutils`` which exists and incites me to close this with this comment...
