### ISSUE TITLE
Lint codebase using pyupgrade

### ISSUE THREAD

**Issue by danieleades** [sphinx-doc/sphinx#11065]
This repo has previously been linted/upgraded using pyupgrade. Now that python <3.8 has been dropped, and the complex branch structure simplified, it might be a good time to revisit this.

My preferred approach would be to add it to CI using pre-commit.

Might need a maintainer to look at this, as they'll have a better idea which modules need to be whitelisted, etc.

i'm particularly interested in adding pyupgrade, as once in place it can be used to automatically update all the type annotations to the python 3.10+ syntax (supported in python 3.8+ using `from __future__ import annotations`)

**Comment by danieleades** [comment]
see https://github.com/sphinx-doc/sphinx/pull/10725#issuecomment-1200478467

**Comment by AA-Turner** [comment]
> i'm particularly interested in adding pyupgrade, as once in place it can be used to automatically update all the type annotations to the python 3.10+ syntax (supported in python 3.8+ using `from __future__ import annotations`)

This has now been done.

A

**Comment by danieleades** [comment]
> > i'm particularly interested in adding pyupgrade, as once in place it can be used to automatically update all the type annotations to the python 3.10+ syntax (supported in python 3.8+ using `from __future__ import annotations`)
> 
> This has now been done.
> 
> A

you might want to consider adding [flake8-future-annotations](https://pypi.org/project/flake8-future-annotations/) to make sure the annotations are used consistently. They seem to have been used in some places but not others
