### ISSUE TITLE
sphinxcontrib-applehelp maintenance required

### ISSUE THREAD

**Issue by mgeier** [sphinx-doc/sphinx#11098]
When running the latest Sphinx, I got this warning:

    sphinx.deprecation.RemovedInSphinx80Warning: The alias 'sphinx.util.SkipProgressMessage' is deprecated, use 'sphinx.util.display.SkipProgressMessage' instead. Check CHANGES for Sphinx API modifications.

This comes from https://github.com/sphinx-doc/sphinxcontrib-applehelp, which doesn't have an "Issues" section, so I'm reporting it here.

I tried to make some quick fixes, but that's apparently not enough to get CI running again:

https://github.com/sphinx-doc/sphinxcontrib-applehelp/pull/10
https://github.com/sphinx-doc/sphinxcontrib-applehelp/pull/11

**Comment by AA-Turner** [comment]
I can add you as a maintainer to ``applehelp`` if you'd like?

A

**Comment by mgeier** [comment]
No, thanks, I don't even know what `applehelp` is!

I just want the warning to go away, I don't care at all about this project, whatever it is.

I guess it has something to with the company Apple ... that's not my thing anyway, I'm a Linux guy.

**Comment by AA-Turner** [comment]
Done, `sphinxcontrib-applehelp` 1.0.3 out now.

A

**Comment by mgeier** [comment]
Thanks for the quick turnaround!

The saga, however, continues: https://github.com/sphinx-doc/sphinxcontrib-htmlhelp/blob/7e05fea72537d9f40d781c38517cd059afd90dc0/sphinxcontrib/htmlhelp/__init__.py#L26

**Comment by renefritze** [comment]
Is it possible the wheel got mangled somehow @mgeier ?
https://zivgitlab.uni-muenster.de/pymor/docker/-/jobs/1271990#L2580

**Comment by AA-Turner** [comment]
Hmm, I just used `python -m build`
