### ISSUE TITLE
flake8 and isort deprecation

### ISSUE THREAD

**Issue by danieleades** [sphinx-doc/sphinx#11108]
Ruff can now fully replace flake8 and isort in this library. Ruff is missing a couple of lints from flake-simplify, but only ones that are currently disabled anyway.

**Comment by AA-Turner** [comment]
https://github.com/charliermarsh/ruff/issues/1718

**Comment by AA-Turner** [comment]
(``ruff . --select I`` reports 5 errors currently which isort does not agree with)

A

**Comment by danieleades** [comment]
> [charliermarsh/ruff#1718](https://github.com/charliermarsh/ruff/issues/1718)

Good catch.

Ah well, maybe we start with flake8 then?
