### ISSUE TITLE
The reference to the same file is interpreted as a duplicate

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1112]
Tested on Windows 7 64bit machine, Python 2.7.3, Sphinx 1.1.3

If there is reference in various ways to the same resource, it is interpreted as different file with duplicate name.

If there is a files structure as follows:

```
#!

[source]/
    document/
        downloads/archive.zip
        index.rst
```

And we have the following code in index.rst:

```
#!rest

:download:`downloads/archive.zip`
:download:`/document/downloads/archive.zip`
:download:`../document/downloads/archive.zip`
```

Then during the build of html output we will have three files (while only one is expected):

```
#!

[build]/
    _downloads/
        archive.zip
        archive1.zip
        archive2.zip
```

The same issue is with figure directive.

In attachment there is a simple Sphinx project just to illustrate the issue.

IMO the problem is because all paths in Sphinx code are not normalized (os.path.normpath() function is missing).

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1112
- Originally reported by: [Tawez](https://bitbucket.org/Tawez)
- Originally created at: 2013-02-18T14:47:34.934

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2013-03-30 11:44:40+00:00_

Closes #1112: Avoid duplicate download files when referenced from documents in
different ways (absolute/relative).

→ <<cset 181b075251e0f21fa19e4a7be9dd380d392135ae>>

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2013-03-30 11:44:59+00:00_

Thanks for the report!

**Comment by shimizukawa** [comment]
_From [Tawez](https://bitbucket.org/Tawez) on 2013-04-02 12:37:00+00:00_

Proposed solution works for downloads,
but doesn't work for images.

I think this would be a better fix:

```
#!python

def relfn2path(self, filename, docname=None):
    # ...
    try:
        return path.normpath(rel_fn), path.normpath(path.join(self.srcdir, rel_fn))
    except UnicodeDecodeError:
        return path.normpath(rel_fn), path.normpath(path.join(self.srcdir, enc_rel_fn))

```

**Comment by bashtage** [comment]
This is a bad fix.  Breaks Windows builds.
