### ISSUE TITLE
Memory hog for Linux documentation with `-j1`

### ISSUE THREAD

**Issue by marxin** [sphinx-doc/sphinx#11124]
### Describe the bug

As shown here:
https://lore.kernel.org/all/bdd04f2e-64a4-e3ef-eb4c-3681c6f52c2f@gmail.com/

```
 ======  ===================================  ===============================
                     elapsed time                       maxresident
         -----------------------------------  -------------------------------
 Sphinx     -j1     -j2      -j4      -j6       -j1     -j2     -j4     -j6
 ======  ======== ======== ======== ========  ======= ======= ======= =======
  6.1.3  15:03.83 11:31.99  9:35.15  8:49.01  2949056 1059516  978232  967400
  6.1.2  15:11.74 18:06.89 16:39.93      OOM  2961524 5548344 5255372      --
  5.3.0  14:13.04 10:16.81  8:22.37  8:09.74   711532  937660  846016  800340
 ======  ===================================  ===============================
```

The Linux documentation build takes much more memory with `-j1` compared to `5.3.0` release.

I bisected that to 463a69664c2b7f51562eb9d15597987e6e6784cd (one needs cherry-pick dcb4429abacda015f98875fe9489ced696155bd7)

### How to Reproduce

`make SPHINXOPTS="-q -j1" htmldocs`

### Environment Information

```text
Sphinx `6.1.3`
```

**Comment by marxin** [comment]
@AA-Turner

**Comment by marxin** [comment]
I'm attaching CPU and memory graphs for `linux` documentation (with `-j1`) with the current caching:

![linux-sphinx-cache](https://user-images.githubusercontent.com/2658545/229782597-03ccabd5-81dc-4345-82d7-1f3bedbf565b.svg)

and if I reverted the mentioned patch:

![linux-sphinx-no-cache](https://user-images.githubusercontent.com/2658545/229782677-1650d69a-18a5-4674-9505-ab5b81fded7e.svg)

So overall, the caching scheme speeds up the documentation build by **8%**.

However, I noticed that with `-j auto` (`j > 2`), there is **no** cache hit for ` _write_doc_doctree_cache` that is likely caused by the usage of a process pool where there is not overlap in between read and write phase.

**Comment by marxin** [comment]
So the situation with my patch should be back to when multiple jobs are used. When it comes to `-j1`, yes, the memory usage is higher, but the build finishes sooner. If it's really a problem, I can imagine a `sphinx-build` option for this optimization. Feel free to re-open the issue if it's the case.

**Comment by AA-Turner** [comment]
@marxin out of interest, what did you use to make the graphs above?

A

**Comment by marxin** [comment]
> @marxin out of interest, what did you use to make the graphs above?

Be my quest, it's my matplotlib-based script located here:
https://github.com/marxin/script-misc/blob/master/usage-wrapper.py
