### ISSUE TITLE
Allow for a query string to be added to local CSS/JS, for cache busting

### ISSUE THREAD

**Issue by chrisjsewell** [sphinx-doc/sphinx#11133]
**Is your feature request related to a problem? Please describe.**

When loading CSS or JS (via `link`/`script` tags) the browser will generally cache files, based on their file name.

This is a problem for updating CSS/JS files that are specified by `html_css_files`/`html_js_files`, or by ` Sphinx.add_css_files()`/` Sphinx.add_js_files()`,
since changes to the content of such files will not be seen by viewers of the website, if they have previously loaded the page.

**Describe the solution you'd like**

A common practice, to "cache bust" is to add a query string after the path

```html
<link rel="stylesheet" href="style.css?v=3.4.1">
```

Indeed, this is what e.g. the furo theme does, via an `html-context-page` event, using the hash of the files: https://github.com/pradyunsg/furo/blob/4909c419ecb99308b6d46bc1e420be2980ba75ef/src/furo/__init__.py#L164 (cc @pradyunsg)

but it would be nice to not have to get so "low level" for basic use cases.

Ideally, sphinx itself would automatically compute the hash of these files and append the requisite query string.

Or at least an option would be available on the methods, like:

```python
def setup(app):
	app.add_css_files("custom.css", query=f"v={version}")
```

**Describe alternatives you've considered**

One could change the file name, every time the content changes, but this is not very maintainable and leads e.g. to issues around merge conflicts when using git.

**Comment by pradyunsg** [comment]
In https://github.com/python/devguide/pull/1034, there's desire expressed for having this also be available via `conf.py` directly.

**Comment by bryevdv** [comment]
related and/or dupe: https://github.com/sphinx-doc/sphinx/issues/11771 We were manually adding a query string for cache-busting but that has recently been disallowed. There we asked for a configuration option to avoid the error, but an "automatic" way to add a version query argument would also be fine.

**Comment by AA-Turner** [comment]
This was done in #11415.

A
