### ISSUE TITLE
sphinxcontrib.applehelp should be distributed as sphinxcontrib_applehelp

### ISSUE THREAD

**Issue by ghost** [sphinx-doc/sphinx#11130]
### Describe the bug

If you look at how the distribution packages are named here: https://pypi.org/simple/sphinxcontrib-applehelp/ you will see that for some reason this  package changed name in the last version. `sphinx` package didn't update to depend on this package correctly.

For no good reason `pip` seems to replace the dot in the package name with a hyphen, and this makes it possible to install `sphinx` using `pip`, but `pkg_resources` doesn't do it (that's correct way to do it), and so `sphinx` isn't installable in this way. Most importantly, this leads to `build_sphinx` `setuptools` extension becoming unusable.

In other words, it's no longer possible to specify `sphinx` in `setup_requires` list, because that would lead to `setuptools` trying to resolve dependencies for `sphinx`, but failing to do so because `sphinx` needs `sphinxcontrib_applehelp` , but such dependency cannot be installed, because once found package called `sphinxcontrib.applehelp` `pkg_resources` will not try to look for a different version or anything like that, it'll just declare that the package doesn't exist.

In general, you shouldn't upload a package named differently into the same repository: the packaging system is already in shambles, and it's sure not prepared to deal with such cases. Why go looking for trouble if the obvious way was to use simpler naming schemes?

---

This behavior exists at least in Python 3.8, `setuptools` 56.0.0. 

### How to Reproduce

Create `setup.py` and specify `sphinx` in `setup_requires` list.

### Environment Information

```text
Sphinx is not installable.
```
---

BTW, [this](https://github.com/sphinx-doc/sphinxcontrib-applehelp/commit/b11afda3eb587a8eb18a931892046137f46df717) is the commit responsible for the breakage.

Also, the fact that using `pyproject.toml` is more recent, doesn't mean that it's better. It's actually worse... There's absolutely no reason to use it. Undoing this whole commit would've made the project a little bit better.

**Comment by benoj** [comment]
I think this issue is blowing up my CI - any workarounds?

**Comment by ajslater** [comment]
This currently breaks downstream builds like [ninemoreminutes/xapian-bindings](https://github.com/ninemoreminutes/xapian-bindings)

**Comment by bachya** [comment]
Any update on this? I can't install my package's dev environment because of this issue:

```
• Installing sphinxcontrib-applehelp (1.0.3): Failed

  KeyError

  "There is no item named 'sphinxcontrib.applehelp-1.0.3.dist-info/WHEEL' in the archive"

  at ~/.asdf/installs/python/3.11.2/lib/python3.11/zipfile.py:1473 in getinfo
      1469│     def getinfo(self, name):
      1470│         """Return the instance of ZipInfo given 'name'."""
      1471│         info = self.NameToInfo.get(name)
      1472│         if info is None:
    → 1473│             raise KeyError(
      1474│                 'There is no item named %r in the archive' % name)
      1475│
      1476│         return info
```

**Comment by nodiscc** [comment]
This breaks all sphinx installations where sphinx is installed through another module's `install_requires=[]`.

In my case this doesn't prevent installation, but sphinx-build will fail at run time, regardless of sphinx version:


```
$ sphinx-build -b html -c tests/ tests/awesome-selfhosted-html/ tests/awesome-selfhosted-html/html
Running Sphinx v5.3.0

Extension error:
Could not import extension sphinxcontrib.applehelp (exception: No module named 'sphinxcontrib.applehelp')
```

Are there any plans to fix this, or known workarounds?

**Comment by nodiscc** [comment]
@AA-Turner any chance of reverting the commit responsible for this?

**Comment by nodiscc** [comment]
> breaks all sphinx installations where sphinx is installed through another module's install_requires=[]

The problem was fixed by using `python3 -m pip install .` instead of `python3 setup.py install` to install the package which lists sphinx in its `install_requires` (https://github.com/nodiscc/hecat/pull/115).

Invoking `setup.py` directly is deprecated https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html.
