### ISSUE TITLE
Next and previous links disappear with nested toctree.

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1114]
In Sphinx 1.1.3 there's a bug. Here's a way to reproduce this:

```
source/
    nested/
         index.rst
         a.rst
    index.rst
    b.rst
```

in `source/index.rst`:

```
:toctree:

    nested/index
    b
```

In `source/nested/index.rst`:

```
:toctree:

    a
```

If you render this the first time, in `nested/a.html` you see a correct link to `b.html`, and vice versa. Edit a document and see the next/previous links disappear. Edit `conf.py` (change theme for instance) and re-build html. The links are back again. Touch a single rst file, and they disappear.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1114
- Originally reported by: Dmitri Lebedev
- Originally created at: 2013-02-19T17:19:17.389

**Comment by shimizukawa** [comment]
_From Jon Waltman on 2013-02-20 19:26:31+00:00_

I was unable to reproduce the problem.

Have you tried deleting the cached environment (everything under the _build directory) to force a fresh build?

If the problem persists, can you attach a copy of the source directory?

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2013-03-06 22:53:01+00:00_

I could not reproduce the problem, too.

**Comment by Kurara** [comment]
Althought this is old and closed, I would like to say that I had the same problem which was resolved by deleting _build cache as you suggested.
