### ISSUE TITLE
Keep 'translated' node attribute

### ISSUE THREAD

**Issue by jeanas** [sphinx-doc/sphinx#11157]
**Is your feature request related to a problem? Please describe.**

In my internationalized documentation, I am adding markers to untranslated or partially translated pages, to warn the user that they can see English content and nudge them to help translating (e.g., like this: 
![image](https://user-images.githubusercontent.com/37271310/215301306-62c0790a-ddec-44d0-b7ad-1f67c5f3578a.png)).

To do this, I'm essentially duplicating part of the `Locale` transform. This feels clumsy because the `Locale` transform already knows which nodes are translated and which aren't. In fact, it sets an attribute on the translated ones. However, this attribute is considered internal, so it deletes it at the end:

```python
        # remove translated attribute that is used for avoiding double translation.
        for translated in self.document.findall(NodeMatcher(translated=Any)):  # type: Element
            translated.delattr('translated')
```

**Describe the solution you'd like**

I'd like to know if it would be acceptable to just delete the two lines of code above in order to let extensions know whether a node has been translated.

**Describe alternatives you've considered**

Adding the functionality for "untranslated" markers to Sphinx itself.

**Comment by humitos** [comment]
I've thought about something similar some time ago and I didn't come up with a good idea to solve it. I'd love to see a warning in the page that I'm reading communicating me that's not finished and there may be some paragraphs in the original language. That will avoid lot of confusions to users.

In the official translation of the Python documentation to Spanish, we are using `potodo`[^1] to know the translation progress: https://python-docs-es.readthedocs.io/es/3.11/progress.html

Maybe `potodo` can be distributed as a sphinx extension that exposes all these values and substitutions that you mentioned. I think it could be a really good combination of existing tools. We would just need to put all the glue in between to make it user-friendly and integrated with Sphinx.

[^1]: https://pypi.org/project/potodo/

**Comment by AA-Turner** [comment]
> I'd like to know if it would be acceptable to just delete the two lines of code above in order to let extensions know whether a node has been translated.

Seems reasonable.

A

**Comment by humitos** [comment]
I opened a PR at https://github.com/sphinx-doc/sphinx/pull/11502 that keeps the `translated` attribute on translated nodes. The code seems to work fine and it does not break any other test. I was able to create a example Sphinx extension as well that uses this attribute to apply CSS and show a percentage of the translated pages.

**Comment by AA-Turner** [comment]
#11502 has been merged, thanks all!

A
