### ISSUE TITLE
Missing release tag for sphinxcontrib-htmlhelp 2.0.1

### ISSUE THREAD

**Issue by mrbean-bremen** [sphinx-doc/sphinx#11187]
### Describe the bug

A [commit](https://github.com/sphinx-doc/sphinxcontrib-htmlhelp/commit/81362a175cf405bc608fe57b303964a0a0cbc16b) has been made 10 days ago that suggests that release 2.0.1 is out, but a release tag is missing. 

The background is that we use to install packages from source, using a release tag, though I understand that we also could use a commit hash. 

Not sure if this is the correct place to mention this, as it's not really a bug, but I couldn't find a better one... Please close the issue if it does not belong here, or if not tagging releases was a conscious decision.

### How to Reproduce

Try to install sphinxcontrib-htmlhelp 2.0.1 from a tag. The [last tag](https://github.com/sphinx-doc/sphinxcontrib-htmlhelp/tags) is currently 2.0.0.

**Comment by AA-Turner** [comment]
Please don't comment on commits!

**Comment by AA-Turner** [comment]
Sorry for this oversight, and thank you for reporting -- I have pushed the tag now: https://github.com/sphinx-doc/sphinxcontrib-htmlhelp/tree/2.0.1

As a note, please don't comment on commits if at all possible -- they're quite hidden within the GitHub interface, and this issue already existed -- I had limited time for several months, though.

Thanks,
Adam

**Comment by mrbean-bremen** [comment]
Thank you, and sorry for the cross-posting!
