### ISSUE TITLE
autosummary "first-sentence" detection fails for some abbreviations

### ISSUE THREAD

**Issue by grayjk** [sphinx-doc/sphinx#11193]
### Describe the bug

If a docstring's first sentence contains an abbreviation such as `e.g.`, autosummary incorrectly cuts the summary immediately after the abbreviation.

Also fails if the first sentence includes: `(i.e. word, word, etc)`

### How to Reproduce

```bash
$ sphinx-quickstart --sep -m -p foo -a author -r0 -len --extensions sphinx.ext.autosummary
```
edit `index.html` to contain:
```
.. autosummary::
   foo.foo
```
edit foo.py to contain
```
def foo():
    """
    Does foo (e.g. foo the thing)
    """
```
this results in truncated output: `Does foo (e.g.`

### Environment Information

```text
sphinx latest
```

### Sphinx extensions

```python
sphinx.ext.autosummary
```

### Additional context

Need to add `e.g.` to https://github.com/sphinx-doc/sphinx/blob/master/sphinx/ext/autosummary/__init__.py#L102

WELL_KNOWN_ABBREVIATIONS should also support `(e.g.` and `(i.e.`

Relates to #7865

**Comment by thatlittleboy** [comment]
@AA-Turner We're facing the same issues with `a.k.a.` , would you consider also adding a fix for this abbreviation? Thanks.

**Comment by AA-Turner** [comment]
@thatlittleboy please may you open a new issue?

A
