### ISSUE TITLE
Get Parameter types from type annotation

### ISSUE THREAD

**Issue by JakobDev** [sphinx-doc/sphinx#11206]
Considering the following code:
```python
def print_msg(msg: str) -> None:
    """
    Prints a message

    :param msg: The message
    """
    print(msg)
```

This is rendered as the following:
![grafik](https://user-images.githubusercontent.com/15185051/220332718-523bde40-bcb4-4d29-8aff-db29c727cbf2.png)

As you can see, parameter contains no type.

Now lets' update the code:
```python
def print_msg(msg: str) -> None:
    """
    Prints a message

    :param msg: The message
    :type msg: str
    """
    print(msg)
```

This brings the following:
![grafik](https://user-images.githubusercontent.com/15185051/220333325-fc5ad9ad-5ac1-4081-9d34-2fb226806190.png)

The Parameter type is now displayed, but I have to t define it manually in the docstring. The Parameter has the correct type annotation in the function header. I think Sphinx should use the type annotation from the function header, if it has one and nothing other is set. Define the Type two times is annoying, if you have a larger codebase. And it needs to be changed every time the Parameter is updated.

Sphinx already shows the function header with the type annotation, but this is way harder to read, if you have a few Parameters.

**Comment by jmandreoli** [comment]
Just set option **autodoc_typehints** in your conf.py : '_description_' to have  the type hint in the description only, or '_both_' to also have it in the signature.
Details are in [the doc](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#configuration)

**Comment by electric-coder** [comment]
@picnixz can likely be closed as a solution as been identified.
