### ISSUE TITLE
Do not copy html_theme_options when setting builder.theme_options

### ISSUE THREAD

**Issue by choldgraf** [sphinx-doc/sphinx#11203]
In several themes I have worked on, it has been a common source of confusion that you cannot make edits in `html_theme_options` after the build has started.

For example, if you want to deprecate a theme option and use a sphinx event hook to detect the option and rename it to something else, then your changes will *not* show up in the HTML context if you do this by modifying `app.config.html_theme_options`.

I think the reason is because of these two things:

1. When the builder is inited, it creates a `builder.theme_options` dictionary and this is what is used in defining the HTML context.
2. When this happens, the `app.config.html_theme_options` object is *copied*, and so updating it's values will not be reflected in the builder's theme_options object (https://github.com/sphinx-doc/sphinx/blob/ba080286b06cb9e0cadec59a6cf1f96aa11aef5a/sphinx/builders/html/__init__.py#L305)

I think it would save a lot of confusion for HTML theme developers if this copy didn't happen at all, or if it happened before creating the `app.config.html_theme_options` object so that changes in one were mirrored in the other.

**Comment by choldgraf** [comment]
Another option if you don't want to change the behavior would be to add an event at the end of the build that checks whether html_theme_options has changed since the beginning, and if so, it emits a warning that builder.theme_options should be edited instead

**Comment by AA-Turner** [comment]
Done in 5073c296375e01297b1cef5ba7a8cf27aaec6b43

A
