### ISSUE TITLE
Replace dots with underscores in `id` and `href` attributes for generated HTML documentation

### ISSUE THREAD

**Issue by bheberlein** [sphinx-doc/sphinx#11208]
**Is your feature request related to a problem? Please describe.**
When generating HTML documentation with `autodoc` and `sphinx-build`, nodes representing documented Python objects (e.g. `<section>` tags for modules & submodules, `<dt>` & `<dd>` tags for function & method signatures) are assigned `id` attributes that may contain dots. Likewise, the `href` of any reference nodes pointing to those nodes will also contain dots. Dots are not valid for JavaScript identifiers, and will break things like ScrollSpy. See the [related issue with PyData Sphinx theme](https://github.com/pydata/pydata-sphinx-theme/issues/1207).

This might be considered a bug, although the presence of dots is not strictly invalid in HTML. But since HTML documentation is generally intended to be served over a web interface, it should be able to play nicely with modern web ecosystems.

**Describe the solution you'd like**
`HTMLTranslator` classes should replace dots with underscores when assigning `ids` of nodes representing `autodoc`'d Python members, and the `refuri` and `anchorname` attributes of any reference nodes pointing to those members. Personally I think this should be the default behavior, but it would be acceptable to add an option (e.g. to `sphinx-build`) that would allow the user to toggle this behavior.

**Describe alternatives you've considered**
The user can define a custom `HTMLTranslator` that handles this, as [demonstrated in the PR submitted](https://github.com/pydata/pydata-sphinx-theme/pull/1208) to PyData Sphinx theme.

**Comment by bheberlein** [comment]
I'm happy to put in the work here, but would appreciate some guidance from more senior devs on what is the right way to do this. The PR linked above might provide a useful template, or not.

**Comment by 12rambau** [comment]
After some more thoughts, we realized that the issue related to the anchor naming convention is only a problem when using the built-in ScrollSpy from Twitter Bootstrap. I think it should then be handled by us from the theme itself (either by using a custom SccrollSpy or use a bootstrap trick) and not from here. 

@AA-Turner I let you review https://github.com/pydata/pydata-sphinx-theme/issues/1435 and I think you can close this one.

**Comment by 12rambau** [comment]
As the names are actual python names I don't think you can face a dots that separate a name and a number as you can't set a variable name as a number.

**Comment by picnixz** [comment]
Err, I don't understand the names. What do you mean by "python names"? they are just strings stored in the `ids` array of the node. What I meant is "how did we generate the ids in the first place?", namely, why were we adding some "."? I don't know if we use that for some index purpose for instance.

**Comment by 12rambau** [comment]
ah sorry. These names are generated when documenting APIs via autodoc. The dots are just representing the path to the method in a python framework: 
```
<my package>.<my module>.<my class>.<my method>
```

With of course all the alternative possible if you document a package variable, a module function, a submodule ... etc

**Comment by picnixz** [comment]
Ok, so we should keep those dots on our side because they are meaningful (actually I took the thing with name/number from the issues you linked and your examples with "id.1" etc).

**Comment by 12rambau** [comment]
sure no problem. That's why I suggested to close the issue in the first place.

**Comment by picnixz** [comment]
Thank you. It's just that I wanted to be sure that we were on the same page. Now, I'll close the issue.
