### ISSUE TITLE
drop some of the html themes ?

### ISSUE THREAD

**Issue by 12rambau** [sphinx-doc/sphinx#11214]
I was working on a linting crusade for this repository and, jinja based template could benefit from a little love. 
By running [djlint](https://www.djlint.com/) I realized there were several themes included in the Sphinx distribution. My question is simple: 

Before I try to adapt all these things including the tests (as they are not linting safe) are they still used ? 

In the wild there are several well maintained and nice looking themes ([pydata-sphinx-theme](https://github.com/12rambau/pydata-sphinx-theme), [Furo](https://github.com/pradyunsg/furo), insipid, [material](https://github.com/jbms/sphinx-immaterial)... extensive list can be found [here](https://sphinx-themes.org/)), is it still necessary to ship anything else than the basic html theme ? even the Sphinx documentation is using a custom variation of basic.

**Comment by jdillard** [comment]
Dupe of https://github.com/sphinx-doc/sphinx/issues/10672. People still make [posts about some of them](https://github.com/sphinx-doc/sphinx/issues/11202) so it seems like offering a way for old bundled themes to die gracefully might be a good option.

**Comment by 12rambau** [comment]
sorry for the noise, I will listen to this one in the meantime and prevent these folders to be linted

**Comment by jdillard** [comment]
Apologies, I misinterpreted. I think skipping them from linting is a great solution until they (hopefully) get removed.
