### ISSUE TITLE
Documenting decorated methods returning callables as methods

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1122]
It'd be nice to easily handle this use case (bare bones example):

```
#!python

class MyCallable(object):
    def __init__(self, f):
        self.f = f
        self.__doc__ = f.__doc__

    def __call__(self):
        self.f()

def wrap(f):
    return MyCallable(f)

class MyClass(object):

    [False](https://bitbucket.org/wrap)
    def myMethod(self):
        """This is a method."""
        pass

```

such that autodoc does the right thing. 

At the moment it handles functions returned from decorators, but if a callable is returned, it treats the field as an attribute:

```
MyMethod = <MyCallable object at 0xe806c50> [source]
```

Is there a straight-forward way to handle this use case now (even if it means adding a new documenter class)?

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1122
- Originally reported by: Anonymous
- Originally created at: 2013-03-05T20:27:54.191

**Comment by tk0miya** [comment]
Please add your custom documenter. It is hard to determine the member is attribute or method (callable) in proper way.
