### ISSUE TITLE
Napoleon causes warning about missing end-string when encountering a reference on the first line of a docstring in a dataclass

### ISSUE THREAD

**Issue by provinzkraut** [sphinx-doc/sphinx#11246]
### Describe the bug

When using `ext.napoleon`, a docstring of a dataclass attribute will cause an `Inline interpreted text or phrase reference start-string without end-string` warning for a reference that's placed on the first line of this docstring.

The reference itself is processed correctly.

### How to Reproduce

This causes the warning

```python
from dataclasses import dataclass

@dataclass
class Thing:
    attribute: str = "anything"
    """
    Here some text. `Here a reference <https://example.org>`_
    """
```

This one works just fine. Notice the linebreak in the docstring

```python
from dataclasses import dataclass

@dataclass
class Thing:
    attribute: str = "anything"
    """
    Here some text. 
    `Here a reference <https://example.org>`_
    """
```

### Environment Information

```text
Platform:              linux; (Linux-5.19.0-35-generic-x86_64-with-glibc2.36)
Python version:        3.10.7 (main, Nov 24 2022, 19:45:47) [GCC 12.2.0])
Python implementation: CPython
Sphinx version:        5.3.0
Docutils version:      0.19
Jinja2 version:        3.1.2
```

### Sphinx extensions

```python
["sphinx.ext.autodoc", "sphinx.ext.napoleon"]
```

**Comment by picnixz** [comment]
When using `sphinx.ext.napoleon`, the docstrings are assumed to follow either NumPy or Google docstrings. According to [[1]](#1) and [[2]](#2), docstrings used on attributes and placed *after* the attribute *must* specify their type first, followed by a colon, and then by whatever you want. 

In particular, your specific docstring does not comply with Google or NumPy docstrings, hence the failure. In particular, what you could request is a *feature* to allow docstrings placed after the documented object to *optionally* specify the type. This, however, requires `GoogleDocstring._parse_attribute_docstring` and `GoogleDocstring._consume_inline_attribute` to be implemented differently (the work behind will not be trivial).

By the way, this does not affect dataclasses in general, but affects all members documented using post-docstrings together with the `sphinx.ext.napoleon` extension.

---

<a id="1">[1]</a> https://www.sphinx-doc.org/en/master/usage/extensions/example_google.html#example-google
<a id="2">[2]</a> https://www.sphinx-doc.org/en/master/usage/extensions/example_numpy.html#example-numpy

**Comment by provinzkraut** [comment]
> According to [[1]](https://github.com/sphinx-doc/sphinx/issues/11246#1) and [[2]](https://github.com/sphinx-doc/sphinx/issues/11246#2), docstrings used on attributes and placed after the attribute must specify their type first

Maybe I'm missing something here but I don't see where this says that these docstrings *must* specify their type. It says that they *may* do so, which is in line with how these are handled for arguments as well.

To quote the section you linked:

> The type may optionally be specified on the first line, separated by a colon.

But even following this supposed requirement, things still don't work as expected:

```python
module_level_variable2 = 98765
"""int: Module level variable documented inline. `link <https://example.org>`_"""
```

This is from the linked example, with only an external reference added. It results in the same error.

**Comment by picnixz** [comment]
> It says that they may do so, which is in line with how these are handled for arguments as well.

Yes, that's right. My bad ! Anyway, the issue is that "if there is a colon, then we assume that the LHS is the type, the RHS is the rest"

> You can make it even simpler:

Ok I confirmed this on my side. I'll edit my previous answer and try to work on that issue this afternoon then.

**Comment by provinzkraut** [comment]
> Ok I confirmed this on my side. I'll edit my previous answer and try to work on that issue this afternoon then.

Cool, thanks for the quick turnaround!

**Comment by picnixz** [comment]
I can confirm that the bug also affects `:meta public:` one-line type comments.
