### ISSUE TITLE
Build failure if Docutils version is 0.18 (not 0.18.1) due to missing Node.findall()

### ISSUE THREAD

**Issue by ktrsoft** [sphinx-doc/sphinx#11245]
### Describe the bug

```
Exception occurred:
  File "/Users/path/to/sphinx/sphinx/transforms/__init__.py", line 204, in apply
    for node in self.document.findall():  # type: Node
AttributeError: 'document' object has no attribute 'findall'
```

### How to Reproduce

`pip install docutils==0.18`

then attempt `make html` on any Sphinx project.

### Environment Information

```text
OS: Ubuntu 22.04
Python version: 3.8.13
Sphinx version: 6.0.0 and later
Docutils version: 0.18
```

### Additional context

In #10470, we dropped the patch code for [Nodes.findall()](https://github.com/sphinx-doc/sphinx/pull/10470/files?diff=split&w=0#diff-8a06a6233264b57f905c460f3a647e5e55246f2e6ba9f0ed4deb87adb68c85d1L591-L600) and still kept the _Docutils_ minimum version as [0.18](https://github.com/sphinx-doc/sphinx/pull/10470/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R66) (which doesn't have `Nodes.findall()`)

People with _Docutils_ version exactly at _0.18_ (which is available on [pypi](https://pypi.org/project/docutils/)), _Sphinx 6.0.0_ and later will encounter the problem.

### Solution
Either of the below will work
1. Add back the deleted `Nodes.findall()` code 
2. Change the _Docutils_ minimum version to `>=0.18.1`

**Comment by AA-Turner** [comment]
Thank you, this has been done in https://github.com/sphinx-doc/sphinx/commit/ae9008b1282278ae9ab7e53fa0d87e1a7be19e12.

A

**Comment by ktrsoft** [comment]
@AA-Turner Thanks for the quick fix!
