### ISSUE TITLE
Missing letter in french translation

### ISSUE THREAD

**Issue by JulienPalard** [sphinx-doc/sphinx#11252]
### Describe the bug

in:

https://github.com/sphinx-doc/sphinx/blob/2ee7d0f678324d8ea8e1400f6a3d376c9639bfc5/sphinx/locale/fr/LC_MESSAGES/sphinx.po#L3511

it miss the first letter.

it should be `incohérences`.

I know it's in Transifex, but looks like I'm not fluent in using Transifex: can't find the string with their search engine.

**Comment by jfbu** [comment]
Thanks, done.

You can use ``translation_text:ncohérenc`` to search for similar strings there.
