### ISSUE TITLE
Mac Scrollbars are white

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1125]
On Mac Mountain Lion (and assumedly also Lion), the scroll bar color is based on the background of the page.  For Sphinx, documents, I believe this is set to the footer color or something like that (I didn't check, but based on http://stackoverflow.com/questions/6762417/lion-scrollbar-colors, that sounds reasonable).  But the right-hand side of the page is bgcolor.  The result is that if you use the default (white bgcolor, but blue footer), the scroll bar is also white, and almost invisible, unless you hover over it with the mouse.  

For example, the in the Python 2 docs, the scrollbar is white. In the Python 3 docs, it is black.

This is the case for the default theme. I didn't check others.

(p.s., yes I know that this is sort of Apple's fault.  The scrollbar color should _really_ be based on the actual color of the stuff underneath it.  This even causes problems in GMail with any dark theme. But if the fix is as simple as the StackOverflow answer implies, it would be great to fix this.)

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1125
- Originally reported by: Aaron Meurer
- Originally created at: 2013-03-10T02:33:18.707

**Comment by tk0miya** [comment]
Confirmed with classic theme
![スクリーンショット 2019-06-02 11 28 04](https://user-images.githubusercontent.com/748828/58756185-117e7200-852e-11e9-868a-32a5fae375ba.png)

**Comment by tk0miya** [comment]
Fixed by #6426.
Thank you for reporting.
