### ISSUE TITLE
LaTeX: longtable with left alignment breaks out of current list indentation context in PDF

### ISSUE THREAD

**Issue by jfbu** [sphinx-doc/sphinx#11268]
### Describe the bug

To fix a wide gap at a bottom of our document in PDF, I added ``:class: longtable`` to a csv-table.  Compiling locally the longtable indeed was inserted with a suitable page break, but it lost the indentation of the list item.  However the total width of the table appears to take in to account the indentation.

![Capture d’écran du 2023-03-27 16-02-08](https://user-images.githubusercontent.com/2589111/227962782-f71eaf8f-ffb5-4717-931d-dac9362057ed.png)

### How to Reproduce

```rest
- More text styling:

  .. csv-table::
     :header: Name, ``maps argument #1 to:``
     :align: left
     :class: longtable

     ``\sphinxstyleindexentry``,       ``\texttt{#1}``
```

### Environment Information

```text
n/r
```

### Additional context

If one uses in this case ``:align: right`` the output is a bit better because the table width is computed to fit the available width in the indented context, so if pushed to the right it looks as if indentation is obeyed. 
![Capture d’écran du 2023-03-27 16-10-25](https://user-images.githubusercontent.com/2589111/227964722-1df4ee19-3567-412a-a7b3-8c236a62697c.png)

I was expecting this issue to have been raised already, there are a number of them for tables in general in PDF, and longtable in particular.

For some reason it appears it had not yet been done.  Sadly the matter with tables in LaTeX is a highly frustrating one.

**Comment by jfbu** [comment]
@picnixz excellent! Thanks for having looked into this.  Now for me this clearly qualifies as a bug of `longtable` handling of the `[l]` optional argument.  Lists are a core structure in LaTeX (although the documentation in Lamport's book is not bad, that book never has been free, the LaTeX Companion neither, and the documentation of list environment as well as the user interface is a great weak point of LaTeX2e, although `enumitem` at least provided useful interface) and where was I, ah yes, the fact that `longtable` behaves that way is for me a bug, although the answer may perhaps be that it is "by design".  I may perhaps raise it upstream but one always hesitates creating a ticket on LaTeX packages used for decades as one may not want actually any change to happen upstream once one has a workaround.  

Anyway, it looks to me as if your method is the correct incantation and should be incorporated to our latex/longtable.tex_t  template.  Would you care do so and handle also the right and center alignments?  One would need to suppress
`` `
<%- if table.align in ('center', 'default') -%>
  [c]
<%- elif table.align == 'left' -%>
  [l]
<%- elif table.align == 'right' -%>
  [r]
<%- endif -%>
```
and add some conditionals before the `\begin{longtable}`.  The centering will be more delicate and might warrant `\setlength\LTleft{\leftmargin plus 1fill}\setlength\LTright{\fill}`.

Hmm, this will not be quite correct in quoted context which have both left and right indentation so the correct stuff should be
```
\setlength\LTleft{\leftmargin plus 1fill}\setlength\LTright{\rightmargin plus 1fill}
```
for centering, and for "right" alignment adapt as is logical.  I tried the above and was happy with result ah no wait not quite happy this is more complex in case of nested lists or quoted lists.  LaTeX has a `\@totalleftmargin` but does not have a `\@totalrightmargin`.

Ok, taking care of this.  Thanks for input !

**Comment by picnixz** [comment]
@jfbu Sorry for the delay and thank you for your patch ! I was offline this week so I couldn't implement the fix myself !

Concerning `longtable`, the official doc says 

> Normally centring is the default, but this document specifies
`\setlength\LTleft\parindent`
`\setlength\LTright\fill`
> in the preamble, which means that the tables are set flush left, but indented
by the usual paragraph indentation. 

However, `\LTleft` is by default `\fill`, so that's why we don't have the correct indentation. As such, I'm not entirely sure that this should be categorized as a bug. Actually, using `[l]` seems to ignore `\LTleft` and `\LTright` and using no placement means to use those latter, so it should be "expected behaviour" (but not what I expected though).

**Comment by jfbu** [comment]
@picnixz the longtable code does:
```latex
\newskip\LTleft       \LTleft=\fill
\newskip\LTright      \LTright=\fill
...
  \if l#1%
    \LTleft\z@ \LTright\fill
  \else\if r#1%
    \LTleft\fill \LTright\z@
  \else\if c#1%
    \LTleft\fill \LTright\fill
  \fi\fi\fi
```
The `[l]` lets longtable adopt the configuration in the above `l` branch. Using no placement is like using the `c` branch.  The above code blissfully ignores the possibility of being inside a list environment, contrarily to the LaTeX `flushleft`, `flushright` or `center` environments, so the behavior of longtable is counter-intuitive and I consider it a bug of longtable, but as the package dates back to 1990 this was a time when LaTeX2e was not yet the dominant variant of original Lamport LaTeX: I went to check the documented source and find for example there
```latex
% \changes{v3.08}{1993/06/09}
%     {Update for \LaTeXe}
```
However I also see there
```latex
% \changes{v3.11}{1994/05/22}
%      {Option handling added, new style errors and warnings}
```
Probably few people have wanted to use a longtable inside an item of a list, but this we at Sphinx must support... I did not do the archeology of when the longtable Sphinx code was first added, and when align option got its support, but any averagely conversant LaTeX user will understand from longtable doc that `[l]` and friends achieve an alignment like using `flushleft` and friends, which is not the case. This is my pale excuse for  considering this s a bug of longtable... another issue is with LaTeX implementation of lists, which does expose to package author an `\@totalleftmargin` but not a `\@totalrightmargin` as the effect is attained by incrementally decreasing the `\linewidth` which served in a core TeX `\parshape` specification.  Hence the rather scary code I had to use...

(as per `\parindent` referred to in longtable documentation as one possible configuration of `\LTleft`: in Sphinx context, our texinputs/sphinxlatexstylepage.sty uses `\parskip` package which sets `\parindent` to the zero dimension globally)

*sorry for gory TeXies details*

**Comment by picnixz** [comment]
I see. I actually only looked at the documentation so I think their doc is a bit misleading. Thank your for the explanations and don't worry about the gory TeXies details (I am already doing black magic in TeX/LaTeX so I've had my share of those).

**Comment by jfbu** [comment]
please stay around to help in LaTeX sphinx maintenance :wink:

**Comment by picnixz** [comment]
Feel free to ping me if there's some help wanted (I'm free next week but in for the next months, I've got my own research to do so I may have some sparse presence). If you have other communication channel to avoid flooding the issue tracker, I'd be glad to join.

**Comment by jfbu** [comment]
@picnixz we definitely welcome any further help you can provide.  What you say about your other tasks apply to me as well, and even worse already now and until mid-May, so a priori I can only do some routine things here until then at least. Will think about communication channel also.
