### ISSUE TITLE
latex builder with footcite failed for resolving references

### ISSUE THREAD

**Issue by DeeliN221** [sphinx-doc/sphinx#11273]
### Describe the bug

I use footcite instead of cite directive in my project, the html can be built without any problem, but the latex builder failed when resolving references...

This is the log:
[sphinx-err-xu4yt9sh.log](https://github.com/sphinx-doc/sphinx/files/11120507/sphinx-err-xu4yt9sh.log)

### How to Reproduce

Must have the source rst files

### Environment Information

```text
Platform:              win32; (Windows-10-10.0.19045-SP0)
Python version:        3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)])
Python implementation: CPython
Sphinx version:        5.3.0
Docutils version:      0.17.1
Jinja2 version:        3.1.2
```

**Comment by jfbu** [comment]
Please provide a minimal example.  Simply using `:footcite:` directive with `sphinxcontrib.bibtex` works for me for LaTeX.

![Capture d’écran 2023-03-31 à 23 23 21](https://user-images.githubusercontent.com/2589111/229234284-d176c5c7-9574-4bc3-80e2-7bfc364d76ee.png)
![Capture d’écran 2023-03-31 à 23 23 27](https://user-images.githubusercontent.com/2589111/229234298-9d347510-c308-4a8e-b1cb-0d46be4e52e2.png)

**Comment by jfbu** [comment]
You are probably missing using ``.. footbibliography::``.

Please read [sphinxcontrib.bibtex documentation](https://sphinxcontrib-bibtex.readthedocs.io/en/latest/quickstart.html) first and in case of problem ask for help on some user group.  This is the repo for core Sphinx development.

**Comment by m3lab-zzl** [comment]
Hi jfbu, 

I opened this issue here because the feedback of the sphinx-build command told me to do so.

```txt
if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

Anyway, many thanks to your advice.

I did add the `.. footbibliography::` directive at the bottom of rst files, but in some of them, I did not put an empty line below the directive, and that caused the error.

**Comment by jfbu** [comment]
Hello @m3lab-zzl  sorry for somewhat expeditive handling, and thanks for explaining the root cause.  Somehow the wrong mark-up using ``sphinxcontrib-bibtex`` did not get reported to you adequately.
