### ISSUE TITLE
External links are not properly escaped in LaTeX

### ISSUE THREAD

**Issue by picnixz** [sphinx-doc/sphinx#11274]
### Describe the bug

When compiling a LaTeX document (independently of the underlying engine), external links containing ligatures are incorrectly escaped by `\sphinxhref` if they are inside a `\sphinxupquote` block.

The issue lies in the definition of `\sphinxupquote` itself:

https://github.com/sphinx-doc/sphinx/blob/c951f5f6393e4e3b4d820eb7d2e243fdc17b2cc1/sphinx/texinputs/sphinxlatexliterals.sty#L963-L994

As we can see, 

https://github.com/sphinx-doc/sphinx/blob/c951f5f6393e4e3b4d820eb7d2e243fdc17b2cc1/sphinx/texinputs/sphinxlatexliterals.sty#L993

defines `-` as a "special" character which when put inside a `\sphinxupquote` may be handled differently. The tex content being generated contains the following block:

```tex
\begin{fulllineitems}
\phantomsection\label{\detokenize{index:MyClass.config}}
\pysigstartsignatures
\pysigline{%
  \sphinxbfcode{\sphinxupquote{config}}%
  \sphinxbfcode{%
    \sphinxupquote{% <- the '-' will be interpreted differently inside 
      \DUrole{p}{:}\DUrole{w}{  }%
      \sphinxhref%
        {https://www.sphinx-doc.org/en/master/extdev/appapi.html\#sphinx.config.Config}%
        {sphinx.config.Config}}}}
\pysigstopsignatures\begin{quote}

\sphinxAtStartPar
A configuration object.
\end{quote}

\end{fulllineitems}
```

While the content being generated is correct, the actual target (i.e., what is really inside the resulting `\href`) is `https://www.sphinx\unhbox \voidb@x \kern \z@ \ETC. [...]`. This can be seen by adding after

https://github.com/sphinx-doc/sphinx/blob/c951f5f6393e4e3b4d820eb7d2e243fdc17b2cc1/sphinx/texinputs/sphinxlatexliterals.sty#L935

something like `\PackageWarning{}{\scantokens{\href{#1}}}` (note that the compilation *WILL* fail because the commands inside are still interpreted, but this is only for inspection). For instance, clicking on the link from a PDF viewer (e.g., Okular) shows the following error:

```
Malformed URL
Invalid hostname (character '%' not permitted); source was "x %5Ckern %5Cz@ %5Cchar %60%5Cprotect %5Cdiscretionary %7B%5Cchar %5Cdefaulthyphenchar %7D%7B%7D%7B%7D doc.org"; scheme = "https", userinfo = "www.sphinx\unhbox \voidb", host = "", path = "/en/master/extdev/appapi.html", fragment = "sphinx.config.Config"
``` 

# Simple Fix

Here is a hotfix using a custom extension:

```
_SPHINX_LITERAL_NOLIG = frozenset('`<>\'-')  
_is_unsafe = _SPHINX_LITERAL_NOLIG.__contains__

def quote_uri(refuri):
    r"""
    Safe escape for LaTeX links.

    This escapes all non-alphanumeric characters, which is stronger than simply
    escaping the URI using :func:`urllib.parse.quote`.

    :param refuri: The link to escape.
    :type refuri: str
    :return: A link that can be used in LaTeX.
    :rtype: str

    This patches the following code::

        \sphinxupquote{       # <- exclude some tokens that may appear in URI
            ...
            \sphinxhref{URI}  # <- fail if URI has non-alphanumeric characters
        }
    """

    def transform(c):
        return f'%{ord(c):02X}' if _is_unsafe(c) else c
    return ''.join(map(transform, refuri))


class CustomLaTeXTranslator(LaTeXTranslator):
    def visit_reference(self, node):
        if node.hasattr('refuri'):
            node['refuri'] = quote_uri(node['refuri'])
        super().visit_reference(node)

def setup(app):
    app.set_translator('latex', CustomLaTeXTranslator, override=True)
    return {'parallel_read_safe': True, 'parallel_write_safe': True}
```

### index.rst

```rst
Foo
===

.. py:class:: MyClass

   .. attribute:: config
      :type: sphinx.config.Config

       A configuration object.
```

### conf.py

```py
# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = 'Foo'
copyright = '2023, picnixz'
author = 'picnixz'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ['sphinx.ext.intersphinx']

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The master toctree document.
master_doc = 'index'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'alabaster'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

intersphinx_mapping = {
    'sphinx': ('https://www.sphinx-doc.org/en/master/', None)
}
```

### Environment Information

```text
Platform:              linux; (Linux-5.3.18-lp152.106-default-x86_64-with-glibc2.26)
Python version:        3.10.3 (main, Jan 31 2023, 10:47:25) [GCC 7.5.0])
Python implementation: CPython
Sphinx version:        6.1.3
Docutils version:      0.18.1
Jinja2 version:        3.1.2
Pygments version:      2.14.0
```

### Sphinx extensions

```python
['sphinx.ext.intersphinx']
```

**Comment by jfbu** [comment]
Thanks for very thorough report, which helped a lot.  Fixed at #11276. Python padawan had a bit of trouble extending build latex doc test to cover this hence a number of forced pushes which show here as the commit message announced the fix.

**Comment by jfbu** [comment]
Ah well, I don't know why I  misunderstood the PDF build was broken and spend some time to get it tested.  But it is only that the actual link is wrong. I may need some vacation.  Will try to fix my mess.

**Comment by AA-Turner** [comment]
Dear Jean-François,

> I pushed an additional [1397cb9](https://github.com/sphinx-doc/sphinx/commit/1397cb90f46c54e3409b094e81baacfc9abea44b) only to try my chances at getting rid of some Windows CI issue with `test_gettext_dont_rebuild_mo`. It was reported at #11276 but I was hoping CI after merge to master would not have it again, as has happened in the past. I don't have any Windows competence nor access so can't understand the problem there.

You are able to re-run the Windows CI through the GitHub interface, which doesn't require pushing additional commits:

1. Click into the commit details interface, e.g. 
2. Click on the tick or cross to the left of the commit title ('1' in the screenshot below)
3. Scroll down to Windows, and click 'Details' to the right ('2' in the screenshot below)
4. Click the icon of two arrows in a circle ('3' in the second screenshot below) to just re-run the Windows CI, or click 'Re-run all jobs' ('4' in the second screenshot) to restart multiple jobs. Sometiems there is an option to just re-run failed jobs.

Hopefully this is of use! At some point I mean to look into the issue, I use Windows primarily so should be able to investigate.

Thanks,
Adam

-------

Screenshots:

![image](https://user-images.githubusercontent.com/9087854/229199219-1650b5e8-fa4d-466b-8c8d-fc3c6c9fdf47.png)

![image](https://user-images.githubusercontent.com/9087854/229199223-2d2b485f-2463-4792-8723-042ba985ba02.png)

(@jfbu for the 'ping')

**Comment by jfbu** [comment]
@AA-Turner Thanks for detailed explanations.  Believe it or not I once upon a time knew about this ... as far back in the past 3 or 4 days ago or last week when I got rid of a number of red crosses on our commits page.  But clearly I reboot regularly and definitely today I had forgotten about this.  As we have this working workaround please don't worry too much... 
Let me also apologize to @picnixz for somehow mangling title of excellent bug report when adding Changes entry at #11276... there was no PDF build crash and I still can't understand why part of my brain caused me to be under this impression while other part which did the fix knew very well the correct state of affairs.
