### ISSUE TITLE
undefined symbol: clang_CXXMethod_isDeleted

### ISSUE THREAD

**Issue by franz-ms-muc** [sphinx-doc/sphinx#11302]
### Describe the bug

see this Log: 

https://readthedocs.org/api/v2/build/20050480.txt

### How to Reproduce

see:

https://github.com/Meisterschulen-am-Ostbahnhof-Munchen/visual-programming-languages-docs/blob/main/docs/conf.py

### Environment Information

```text
all Settings public Available:

https://github.com/Meisterschulen-am-Ostbahnhof-Munchen/visual-programming-languages-docs
```

**Comment by picnixz** [comment]
This might be an issue from the `sphinx_c_autodoc` extension itself (see https://readthedocs.org/projects/sphinx-c-autodoc/builds/20051941/). I'd suggest to open an issue on their repository directly (https://github.com/speedyleion/sphinx-c-autodoc).

**Comment by franz-ms-muc** [comment]
speedyleion/sphinx-c-autodoc#121

**Comment by franz-ms-muc** [comment]
> This might be an issue from the `sphinx_c_autodoc` extension itself (see https://readthedocs.org/projects/sphinx-c-autodoc/builds/20051941/). I'd suggest to open an issue on their repository directly (https://github.com/speedyleion/sphinx-c-autodoc).

i see. they have SAME Bug on their side.

**Comment by franz-ms-muc** [comment]
working again:

[https://readthedocs.org/api/v2/build/20068644.txt](https://readthedocs.org/api/v2/build/20068644.txt)

[speedyleion/sphinx-c-autodoc#121](https://github.com/speedyleion/sphinx-c-autodoc/issues/121)
