### ISSUE TITLE
[FEATURE] Update FAQ to clarify license of rST syntax

### ISSUE THREAD

**Issue by twodrops** [sphinx-doc/sphinx#11334]
**Is your feature request related to a problem? Please describe.**
Large organizations need clarity on re-distruibuting open source code as well as other artifacts like rST.

**Describe the solution you'd like**
The licensing of Sphinx as a tool is clear, but the license of the artifacts products by it or the syntax itself, is not really documented (or atleast I could not easily find it)

**Additional context**
A link to such a confirmation is needed by such organizations for documentation needs. For example, see [PlantUML FAQ](https://plantuml.com/de/faq). 
![image](https://user-images.githubusercontent.com/103930/232460100-177edccf-8b91-47cf-a0ce-f619791ea574.png)
![image](https://user-images.githubusercontent.com/103930/232460124-f244da5e-3d0f-4063-895c-d79239385bd4.png)
(Oops, information in the screenshots above are copyrighted by PlantUML )

I would like to have 2 FAQs in Sphinx FAQ/ documentation.

## What is the license of the rST syntax?

I am not sure if this belongs to Sphinx or docutils. As I am using Sphinx to create these files I would like to have this information provided by Sphinx as well. If this makes sense, I can create a PR.

**Comment by AA-Turner** [comment]
> Are HTMLs generated by Sphinx covered by the BSD license?

I don’t think this is a reasonable interpretation—Sphinx operates as a translation tool, and so the content remains copyright of the owner.

> What is the license of the rST syntax?

Public Domain (or: CC0; BSD0; etc)

A
