### ISSUE TITLE
Documenting Python dictionary key values

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1133]
We currently have the following kind of dictionary and will like to document them:

```
data_fields = {
    '''
    :description: Data id
    :sample: A positive integer
    '''
    'id': fields.String,
    '''
    :description: Data href
    :sample: example.com/data/1/
    '''
    'href': fields.Url('data'),
    'date_created': fields.DateTime,
    'name': fields.String,
}
```

Is it possible to parse the above documentation from within a Python dictionary?

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1133
- Originally reported by: [thierry](https://bitbucket.org/thierry)
- Originally created at: 2013-03-27T17:05:04.368

**Comment by shimizukawa** [comment]
_From [thierry](https://bitbucket.org/thierry) on 2013-04-02 15:11:31+00:00_

I wrote an extension to parse a dictionary.

**Comment by SarthakRout** [comment]
Is this extension public?
