### ISSUE TITLE
Include imports for Python objects in the `literalinclude` directive

### ISSUE THREAD

**Issue by haiiliin** [sphinx-doc/sphinx#11339]
**Is your feature request related to a problem? Please describe.**

I want to include the source code of a python object in a file, like:
```rst
.. literalinclude:: module.py
    :pyobject: Class
```
Is it possible to include lines of imports that are required by the object?

**Describe the solution you'd like**

Add an option like `include-imports` to include the relevant import lines, like:
```rst
.. literalinclude:: module.py
    :pyobject: Class
    :include-imports:
```

**Describe alternatives you've considered**

Manually specify the lines.

**Additional context**

**Comment by picnixz** [comment]
The issue with that approach is that it is limited to Python files. In addition, knowing which imports are required is quite complex. For instance, what do I import when I write something like:

```python

from collections.abc import *

class Foo:
   seq = Sequence
   def bar(self):
     return self.__class__.seq
```

If we only want to include Foo.bar, then we would probably detect that we need to import everything from `collections.abc`, but we would only see:

```python
from collections.abc import *

def bar(self): 
  return self.__class__.seq
```

This would be very confusing. Explicitly adding the requirements should be done and this would be less error-prone (and complicated on our side).

**Comment by picnixz** [comment]
You can use `:prepend:`.

```rst
.. literalinclude:: foo.py
   :pyobject: Foo.bar
   :prepend: import bar
             import baz
```

**Comment by haiiliin** [comment]
> prepend

Thanks, I find it in the docs, it is not so obvious in the docs.
