### ISSUE TITLE
阿铭Linux也用这个来构建Linux书

### ISSUE THREAD

**Issue by xiaohuazi123** [sphinx-doc/sphinx#11344]
### Describe the bug

阿铭Linux也用这个来构建Linux书

### How to Reproduce

阿铭Linux也用这个来构建Linux书

### Environment Information

```text
阿铭Linux也用这个来构建Linux书
```

### Sphinx extensions

```python
阿铭Linux也用这个来构建Linux书
```

### Additional context

阿铭Linux也用这个来构建Linux书

**Comment by AA-Turner** [comment]
Please report issues in English, the majority of the development team do not understand Chinese.

A
