### ISSUE TITLE
Exntend setuptools command to include sphinx-apidoc

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1135]
It would be nice if the setuptools integration would optionally call sphinx-apidoc before actually building the usual documentation. This in turn would allow to include always up to date API documentation in the usual manual generated with sphinx.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1135
- Originally reported by: [languitar](https://bitbucket.org/languitar)
- Originally created at: 2013-04-05T15:24:34.580

**Comment by tk0miya** [comment]
duplicated with #1861
