### ISSUE TITLE
Boolean Conversion and NotImplementedError

### ISSUE THREAD

**Issue by phantom-zsv** [sphinx-doc/sphinx#11351]
**Is your feature request related to a problem? Please describe.**
A few years ago I found it necessary to block boolean conversions from a few types.

The types had no obvious truthiness or falsiness because they had rather complex interactions.
You can't really delete the `__bool__` method from types.
You can however mark them as deleted with None, but that requires a secondary check in order to raise a reasonable exception.
I made the decision to mark the `__bool__` method as not implemented by always raising a NotImplementedError exception.
The issue with blocking the `__bool__` method from types is that it prevents certain constructs used by Sphinx.
A `__bool__` for types that raises a NotImplementedError exception, or any other, prevents successful document generation.

**Describe the solution you'd like**
I'd like to be able to raise the NotImplementedError in `__bool__` functions or mark them as deleted with None.

The goal is to prevent the default `__bool__` method truthiness without imposing some form of truthiness or falsiness in situations where there is no obvious conversion.

**Describe alternatives you've considered**
I discussed this at length with a few people, and alternatives are possible, but a simple `__bool__ = None` or similar is a very simple and obvious approach.

**Additional context**

I'm bad with git and the github site.
I have no idea how this simple patch may turn out, but I wanted to show that supporting a NotImplementedError `__bool__` for types would not be too difficult.
I would actually suggest a utility function to wrap the checks, but I've only been back at programming for a couple of weeks after a very long time away.

```
diff -ruN original/ext/autodoc/__init__.py modified/ext/autodoc/__init__.py
--- original/ext/autodoc/__init__.py	2023-01-10 09:55:38.165128500 -0600
+++ modified/ext/autodoc/__init__.py	2023-04-23 09:14:05.875421926 -0500
@@ -1615,7 +1615,11 @@
         return "\n".join(sigs)
 
     def get_overloaded_signatures(self) -> list[Signature]:
-        if self._signature_class and self._signature_method_name:
+        try:
+            iscls = bool(self._signature_class)
+        except NotImplementedError:
+            iscls = True
+        if iscls and self._signature_method_name:
             for cls in self._signature_class.__mro__:
                 try:
                     analyzer = ModuleAnalyzer.for_module(cls.__module__)
```

```
diff -ruN original/util/inspect.py modified/util/inspect.py
--- original/util/inspect.py	2023-01-10 09:55:38.310128500 -0600
+++ modified/util/inspect.py	2023-04-23 09:07:03.247018714 -0500
@@ -181,11 +181,15 @@
 
 def isclassmethod(obj: Any, cls: Any = None, name: str | None = None) -> bool:
     """Check if the object is classmethod."""
+    try:
+        iscls = bool(cls)
+    except NotImplementedError:
+        iscls = True
     if isinstance(obj, classmethod):
         return True
     elif inspect.ismethod(obj) and obj.__self__ is not None and isclass(obj.__self__):
         return True
-    elif cls and name:
+    elif iscls and name:
         placeholder = object()
         for basecls in getmro(cls):
             meth = basecls.__dict__.get(name, placeholder)
@@ -774,8 +778,11 @@
             return doc
         else:
             return None
-
-    if cls and name and isclassmethod(obj, cls, name):
+    try:
+        iscls = bool(cls)
+    except NotImplementedError:
+        iscls = True
+    if iscls and name and isclassmethod(obj, cls, name):
         for basecls in getmro(cls):
             meth = basecls.__dict__.get(name)
             if meth and hasattr(meth, '__func__'):
```

**Comment by picnixz** [comment]
I would vote against this change because it goes against Python specifications (https://docs.python.org/3/library/stdtypes.html#truth-value-testing): 

> Any object can be tested for truth value, for use in an [if](https://docs.python.org/3/reference/compound_stmts.html#if) or [while](https://docs.python.org/3/reference/compound_stmts.html#while) condition or as operand of the Boolean operations below.

Concerning `__bool__` itself:

> Called to implement truth value testing and the built-in operation bool(); should return False or True. When this method is not defined, [`__len__()`](https://docs.python.org/3/reference/datamodel.html#object.__len__) is called, if it is defined, and the object is considered true if its result is nonzero. If a class defines neither [`__len__()`](https://docs.python.org/3/reference/datamodel.html#object.__len__) nor [`__bool__()`](https://docs.python.org/3/reference/datamodel.html#object.__bool__), all its instances are considered true.

In particular, raising an exception for `__bool__` is (and should not be) supported. If you want to mark `__bool__` as deleted, you should instead document this behaviour. 

Concerning your patch, if we were to consider it, we would need there are probably more locations where this should be patched. We need to know how it would affect third-party extensions. Please format your patch differently or create a gist and share it here (it is unreadable in its current form).

**Comment by AA-Turner** [comment]
Please submit a PR and we can discuss further. However I would note that generally any object or class is 'truthy' and overriding `__bool__` probably is not the most pythonic solution.

A
