### ISSUE TITLE
Alternative operator tokens aren't highlighted in C++ code blocks

### ISSUE THREAD

**Issue by cjdb** [sphinx-doc/sphinx#11356]
### Describe the bug

`and`, `or`, and `not` are a part of the [alternative operator tokens](https://en.cppreference.com/w/cpp/language/operator_alternative), which are keywords in C++. These are typically highlighted like other keywords in editors, but they don't appear to be in Sphinx HTML docs.

These would ideally be highlighted like other C++ keywords are.

### How to Reproduce

Put the following in a project made by sphinx-autogen and then run `make html`.

```rst
.. code-block:: cpp

  template<class T>
  concept signed_integral = integral<T> and is_signed_v<T>;
```

### Environment Information

```text
Platform:              linux; (Linux-6.2.12-arch1-1-x86_64-with-glibc2.37)
Python version:        3.10.10 (main, Mar  5 2023, 22:26:53) [GCC 12.2.1 20230201])
Python implementation: CPython
Sphinx version:        6.1.3
Docutils version:      0.19
Jinja2 version:        3.1.2
Pygments version:      2.15.0
```

**Comment by jfbu** [comment]
Hi, this looks like a [pygmentize](https://github.com/pygments/pygments) issue of its cpp lexer.

Try this
```
$ cat <<EOF >temp.cpp
> template<class T>
> concept signed_integral = integral<T> and is_signed_v<T>;
> EOF
```
then (in my bash shell)
```
$ pygmentize -l cpp -f html temp.cpp
```
outputs
```html
<div class="highlight"><pre><span></span><span class="k">template</span><span class="o">&lt;</span><span class="k">class</span><span class="w"> </span><span class="nc">T</span><span class="o">&gt;</span>
<span class="k">concept</span><span class="w"> </span><span class="nc">signed_integral</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="n">integral</span><span class="o">&lt;</span><span class="n">T</span><span class="o">&gt;</span><span class="w"> </span><span class="n">and</span><span class="w"> </span><span class="n">is_signed_v</span><span class="o">&lt;</span><span class="n">T</span><span class="o">&gt;</span><span class="p">;</span>
</pre></div>
```
So the `and` is styled as `<span class="n">and</span>`.  Sphinx with default `alabaster` theme will use a ` alabaster.support.Alabaster` Pygments style and I copy here the relevant part
```
        # because special names such as Name.Class, Name.Function, etc.
        # are not recognized as such later in the parsing, we choose them
        # to look the same as ordinary variables.
        Name: "#000000",  # class: 'n'
```
The output mark-up `<span class="n">and</span>` from Pygments does not allow to distinguish this keyword from a variable name. Maybe you could raise this at their project?

**Comment by AA-Turner** [comment]
Yep, note from https://pygments.org/demo/?lexer=cpp&style=default&formatter=tokens&code=template%3Cclass+T%3E%0Aconcept+signed_integral+%3D+integral%3CT%3E+and+is_signed_v%3CT%3E%3B that the ``and`` is lexed as a name rather than as an operator. When Pygments fix this, Sphinx will pick it up automatically.

A

**Comment by AA-Turner** [comment]
(Please do feel free to help with C++ issues with Sphinx in general -- it's an area we could do with greater expertise in!)

**Comment by cjdb** [comment]
Thank you both for your fast feedback!
