### ISSUE TITLE
Make the word "Release" in title configurable

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1136]
As I use Sphinx for publishing books not related to software documentation I have to delete the word "Release" from the titlepage of the generated pdf by hand. It would be nice if I could configure this. So please make it configurable. 

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1136
- Originally reported by: Jan Ulrich Hasecke
- Originally created at: 2013-04-06T18:27:21.088

**Comment by petarmaric** [comment]
I'd find this feature useful as well, any idea how we can achieve this?

**Comment by jfbu** [comment]
Related #3393

**Comment by tk0miya** [comment]
It seems this was fixed by #3393. Closing.
