### ISSUE TITLE
Option not to emit sphinx version in the HTML

### ISSUE THREAD

**Issue by veltzer** [sphinx-doc/sphinx#11367]
**Is your feature request related to a problem? Please describe.**
When ever I run shinx it usually creates new files when the only thing that changes is the sphinx version number 
like:
     "Powered by <a href="http://sphinx-doc.org/">Sphinx 6.2.1</a>"
Since I commit the files to git (for github pages for instance) this counts as a real change and creates yet another commit when all that has changed is the sphinx version but the documentation hadn't really changed.

**Describe the solution you'd like**
Add an option to sphinx not to emit it's own version into the documentation. I see this as part of a larger effort to make sphinx as deterministic as possible (meaning under the same inputs it will produce the same outputs).

**Comment by picnixz** [comment]
You can do it by giving a custom HTML template (https://www.sphinx-doc.org/en/master/development/templating.html#working-with-the-builtin-templates). You'll simply need to extend the current HTML theme and change the footer block so that it does not include the Sphinx version (take a look at `alabaster/layout.html` for instance)

**Comment by AA-Turner** [comment]
Yep, closing as this is solvable via templates (I'd note that the output *does* change from version to version though, so determinism would only be within a given version of Sphinx).

A

**Comment by mgeier** [comment]
It's true that this can be modified via an HTML template, but there is also a much simpler and more direct way:

```python
html_show_sphinx = False
```

https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_show_sphinx

**Comment by veltzer** [comment]
I didn't know about the "html_show_sphinx" option.

**Comment by veltzer** [comment]
A few comments:
- The option `html_show_sphinx` does not work. I tried it with the default theme. does not  work. This means that the documentation misleads the users. Remove the documentation for it until this works (or forever if it doesn't).
- There is no `alabaster/layout.html` in the entire sphinx source code.
- There is no alabaster subfolder in the `themes` subfolder of the sphinx source code. This is disturbing as `alabaster` is supposed to be the default theme according to the documentation.

This is way too complicated for a tool that should just work out of the box and be as simple as possible.

**Comment by AA-Turner** [comment]
Please don't make demands of people who are providing support to you for free in their spare time.

I will accept pull requests to fix any of the issues you've enumerated. To your second and third points: this is correct, Alabaster is maintained in a [distinct repository](https://github.com/sphinx-doc/alabaster) and the file will be there. I don't find this disturbing.

A

**Comment by veltzer** [comment]
I don't make any demands. I'm just informing you that the tool is way too complicated.

I don't find this disturbing: you may not find this disturbing. I do. This means I had to figure out that this was in a different repo, which means that I have to grep two repos to find something. And I also had to guess that "template_foobar" is actually "foobar" as template option. This is not intuitive.

(I write a lot of free software as well and I provide support in my free time as well).

**Comment by picnixz** [comment]
In the meantime, you can use ``html_theme_options = {'show_powered_by': False}`` . This would probably only work for alabaster since other themes *should* instead rely on the``html_show_sphinx`` option.

**Comment by veltzer** [comment]
Thank you, this had helped me a lot.
