### ISSUE TITLE
The Table of Contents file is malformed: toc is not a mapping: <class 'list'> You may need to migrate from the old format

### ISSUE THREAD

**Issue by ethan530** [sphinx-doc/sphinx#11369]
### Describe the bug

https://github.com/phaustin/jupyter-book/blob/windows/docs/advanced/advanced.md#working-on-windows

Followed the instructions from the above link, 
```
1. conda install git
2. git clone https://github.com/eoas-ubc/quantecon-mini-example.git
3. cd quantecon-mini-example
4. git checkout windows
5. conda env create -f environment_win.yml
6. conda activate wintest
7. cd mini_book
8. runjb docs
```

I get the error message from the title when I run command 8.  There seems to be another user who had this error before: https://github.com/executablebooks/jupyter-book/issues/1329. But he managed to fix his problem through use of command, 
```
jupyter-book toc migrate _toc.yml -o _toc.yml.new
mv _toc.yml _toc.yml.old 
mv _toc.yml.new _toc.yml
```

I tried the command but got this, 
<img width="856" alt="image" src="https://user-images.githubusercontent.com/74956050/234833719-d926b373-2d84-40e9-b90f-0f5344fb3ca0.png">

The reason I am following the above instructions is because while I was following the instructions on creating a template jupyter book here, https://jupyterbook.org/en/stable/start/create.html. I got an error as detailed here when trying the build the book.
[sphinx-err-ylmnu6bm.log](https://github.com/sphinx-doc/sphinx/files/11342352/sphinx-err-ylmnu6bm.log)

What should I do to fix this issue? Any help would be appreciated.

### How to Reproduce

First follow the instructions until "runjb docs", more details here, https://github.com/phaustin/jupyter-book/blob/windows/docs/advanced/advanced.md#working-on-windows.

```
1. conda install git
2. git clone https://github.com/eoas-ubc/quantecon-mini-example.git
3. cd quantecon-mini-example
4. git checkout windows
5. conda env create -f environment_win.yml
6. conda activate wintest
7. cd mini_book
8. runjb docs
```
Should this error occur.
```
The Table of Contents file is malformed: toc is not a mapping: <class 'list'>
You may need to migrate from the old format,
```
Run this command.
```
jupyter-book toc migrate _toc.yml -o _toc.yml.new
mv _toc.yml _toc.yml.old 
mv _toc.yml.new _toc.yml
```
Alternatively, running the command below doesn't fix the error either.
```
jupyter-book toc migrate C:\Users\ethan\quantecon-mini-example\mini_book\docs\_toc.yml -o C:\Users\ethan\quantecon-mini-example\mini_book\docs\_toc.yml
``` 

### Environment Information

```text
Platform:              win32; (Windows-10-10.0.22621-SP0)
Python version:        3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 05:35:01) [MSC v.1916 64 bit (AMD64)])
Python implementation: CPython
Sphinx version:        5.3.0
Docutils version:      0.16
Jinja2 version:        3.1.2
```

### Sphinx extensions

```python
None.
```

### Additional context

None.

**Comment by AA-Turner** [comment]
Please report Jupyter Book issues to https://github.com/executablebooks/jupyter-book/; if the issue is with Sphinx itself please submit a reproducer sans notebook.

A
