### ISSUE TITLE
``FORCE_COLOR`` not working in Sphinx 5.1

### ISSUE THREAD

**Issue by theletterf** [sphinx-doc/sphinx#11391]
When running `sphinx-build`, I'd like warnings and errors to appear with a different color, such as red or blue, depending on the type. Currently. I get a rather flat output in both Visual Studio Code's terminal and GitHub Actions, even with `FORCE_COLOR.`

**Describe the solution you'd like**
Colorize build errors and warnings in Sphinx-builld's output.

**Comment by webknjaz** [comment]
cc @hugovk I think you added this, right?

**Comment by AA-Turner** [comment]
https://github.com/sphinx-doc/sphinx/pull/10260

**Comment by webknjaz** [comment]
I wonder if this if-branch https://github.com/sphinx-doc/sphinx/pull/10260/files#diff-9d3f7c748afced2d1bcf14457b34fe88fd51fae6829fc79f8164c22199b75959R66 should also enable colorama if it's present..

**Comment by AA-Turner** [comment]
@theletterf please do provide details on your Sphinx, Python, versions etc -- if you paste the output of ``sphinx-build --bug-report`` this would be very helpful.

A

**Comment by theletterf** [comment]
- Python 3.11
- Sphinx 5.1.1 (Read the Docs's default Python is stuck at 3.7 so I can't run Sphinx 6.x)

You can see the `requirements.txt` here: https://github.com/splunk/public-o11y-docs/blob/main/requirements.txt

**Comment by webknjaz** [comment]
> * Read the Docs's default Python is stuck at 3.7 so I can't run Sphinx 6.x

That's not really true. You can use a newer Python on RTD if you configure that. Also, Python 3.7 is about to be EOL anyway...

**Comment by theletterf** [comment]
I know it's configurable, but I wonder why the minimum hasn't been bumped yet. We're two months from EoS.

**Comment by webknjaz** [comment]
Probably because something else was prioritized 🤷‍♂️

**Comment by theletterf** [comment]
Yep. Let's get back to the color issue though.

**Comment by AA-Turner** [comment]
We only support latest Sphinx (as we don't backport fixes, etc). Please would you test locally with Sphinx 7?

A

**Comment by theletterf** [comment]
I'm exporting `FORCE_COLOR = 1` in the [Makefile](https://github.com/splunk/public-o11y-docs/blob/main/Makefile). Would that be the proper way?

**Comment by AA-Turner** [comment]
Do you have a public CI run that I'd be able to look at? Is there no colour at all?

**Comment by AA-Turner** [comment]
MyST errors should be reported to https://github.com/executablebooks/MyST-Parser/, we don't support it.

**Comment by theletterf** [comment]
Sounds like it's a MyST issue then. I wrongly assumed Sphinx's extensions would also have their output colored. We can close this one.

**Comment by AA-Turner** [comment]
Thank you for responding so quickly!

A

**Comment by webknjaz** [comment]
@theletterf FYI the makefile isn't used by RTD.
