### ISSUE TITLE
sharepoint online extension to publish sphinx-doc

### ISSUE THREAD

**Issue by yboujraf** [sphinx-doc/sphinx#11409]
**Is your feature request related to a problem? Please describe.**

> I'm using Sphinx to generate documentation for a python project, and the output of that is a bunch of static HTML, with some JS.  As part of a CI/CD pipeline, I want to take this automatically generated content and publish it to SharePoint Online so it can be consumed by internal users along side our other documentation.  

**Describe the solution you'd like**

> Use same way as [Confluencebuilder ](https://github.com/sphinx-contrib/confluencebuilder) extension 

**Describe alternatives you've considered**

**Additional context**

**Comment by AA-Turner** [comment]
Please feel free to implement this yourself, unfortunately we have no capacity to implement this within core Sphinx.

A
