### ISSUE TITLE
wrong documentation in directives.rst

### ISSUE THREAD

**Issue by generationext** [sphinx-doc/sphinx#11407]
### Describe the bug

In file sphinx/doc/usage/restructuredtext/directives.rst

Useful cases of these option is working with tag comments.
``:start-after: [initialized]`` and ``:end-before: [initialized]`` options
keep lines between comments:

      .. code-block:: py

         if __name__ == "__main__":
             # [initialize]
             app.start(":8000")
             # [initialize]

 [initialized] or  [initialize] ?

### How to Reproduce

.. literalinclude:: src/foo.py
	:start-after: [initialized]
	:end-before: [initialized]

start-after pattern not found: [initialized]

### Environment Information

```text
documentation
```

**Comment by jfbu** [comment]
Thanks, if you have time, please contribute a PR to fix this (choose anyone of the variants). Relates #7997.

**Comment by blaisep** [comment]
Hi @generationext , I think I got what you were looking for here https://github.com/sphinx-doc/sphinx/pull/11513

**Comment by blaisep** [comment]
@jfbu , I think you can easily rebase this onto the latest 
I believe this will close the issue.
