### ISSUE TITLE
Drop $.browser usage in doctools.js

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1140]
The use of $.browser in fixFirefoxAnchorBug() prevents us from using jquery 1.9.1 without the migrate plugin (with migrate it's working great though)

But moving forward, doctools should eventually do it's own userAgent sniff in order to reduce the jquery-migrate dependency.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1140
- Originally reported by: DJ Mountney
- Originally created at: 2013-04-09T18:42:22.367

**Comment by tk0miya** [comment]
It seems this was already fixed: #1438 c608af4bab.
So I'm closing this now.
