### ISSUE TITLE
Stricter field list parsing

### ISSUE THREAD

**Issue by ikonst** [sphinx-doc/sphinx#11427]
A stray space causes the second "param" in this field list to parse unexpectedly:
```rst
:param foo: spam
:param bar : ham
```

I'm trying to see whether there's any "strict parsing" setting which would highlight this, or whether one could realistically be added.

**Comment by picnixz** [comment]
With Sphinx 6.2.1, I get the following warning:

> WARNING: Field list ends without a blank line; unexpected unindent.

So technically it should highlight the issue by default. One possibility why it is *not* highlighted is if you are using an incremental build (i.e., not everything is rebuilt and hence not everything is re-parsed). 

To ensure a fresh build, use the `-E` option from the command-line or add it to ``SPHINXOPTS`` in the Makefile.

**Comment by picnixz** [comment]
Closing for now. Feel free to reopen if the issue persists with the latest version.
