### ISSUE TITLE
ValueError: Invalid IPv6 URL,//[::ffff:192.168.0.1

### ISSUE THREAD

**Issue by SimFG** [sphinx-doc/sphinx#11425]
### Describe the bug

When i use the `httpx` lib, the doc generation will fail
![image](https://github.com/sphinx-doc/sphinx/assets/21985684/8f3ba73d-ad03-4984-bd42-14d93726ebbd)

### How to Reproduce

Sphinx == 4.5.0
httpx == 0.24.0

### Environment Information

```text
Sphinx == 4.5.0
httpx == 0.24.0
```

**Comment by AA-Turner** [comment]
Please provide proper reproduction instructions, I currently do not understand your issue in any detail. Closing for now, please re-open when you've posted a minimum reproducer.

A
