### ISSUE TITLE
Support PEP 695 syntax for class definitions

### ISSUE THREAD

**Issue by JelleZijlstra** [sphinx-doc/sphinx#11438]
[PEP 695](https://peps.python.org/pep-0695/), which is implemented in the upcoming Python 3.12, adds a new syntax for defining generic classes:

```python
class Sequence[T]:
     def __getitem__(self, idx: int) -> T: ...
```

I would like to document generic classes with e.g. `.. class:: Sequence[T]`, but that doesn't render correctly (the `class` introduction doesn't appear):

<img width="580" alt="Screen Shot 2023-05-22 at 8 34 55 PM" src="https://github.com/sphinx-doc/sphinx/assets/906600/f6de9eba-294a-4b3c-a3af-37e67b0eec4c">

Presumably the parser for the `class` directive needs to be taught to recognize this syntax. (Cross-ref: https://github.com/python/cpython/pull/104642#discussion_r1200799012.)

**Comment by picnixz** [comment]
The issue lies in 

https://github.com/sphinx-doc/sphinx/blob/d3c91f951255c6729a53e38c895ddc0af036b5b9/sphinx/domains/python.py#L42-L49

We need a better regular expression for matching this new signature. If anyone knows some magical regex for that (otherwise I'll think of it this w-e).

**Comment by Gobot1234** [comment]
Just adding a smidge to this it'd also be nice for it to work for functions as well
