### ISSUE TITLE
Pygments warnings not turned into errors and not shown when using -W and -q

### ISSUE THREAD

**Issue by theletterf** [sphinx-doc/sphinx#11442]
### Describe the bug

When I run sphinx-build using the -W setting, which turns all warnings into errors able to interrupt a pipeline, and the -q setting, which mutes all output except errors and warnings, I expect Pygments / code highlighting related warnings to behave like errors. For example:

```
WARNING: Pygments lexer name 'test not known
```

Instead, the warning is silenced and doesn't turn into an error. This prevents my pipelines from failing when lexer issues are detected.

### How to Reproduce

1. Introduce a fake lexer in a code block.
2. Run sphinx-build. The warning appears.
3. Run sphinx-build with `-W --keep-going -n -E -q -d`. The warning doesn't appear.
4. Run sphinx build with `-W`. The warning is still a warning—doesn't behave like an error.

### Environment Information

```text
Sphinx 5.1.1
```

### Sphinx extensions

```python
extensions = [
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.ifconfig',
    'sphinx_copybutton',
    'notfound.extension',
    'myst_parser',
    'sphinx_tabs.tabs'
]
```

**Comment by theletterf** [comment]
Using Sphinx 6.2.1 and only MyST Parser 1.0.0 as an extension. Same behavior. 

I added this to one my rST docs:

```
   .. code-block:: tango
  
      Bla bla
```

With some time I could test with Sphinx 7.0.1 and no extensions, but something tells me it's not the versions.

**Comment by theletterf** [comment]
Error is https://github.com/sphinx-doc/sphinx/blob/master/sphinx/highlighting.py#L147

**Comment by picnixz** [comment]
> With some time I could test with Sphinx 7.0.1 and no extensions, but something tells me it's not the versions.

With Sphinx 6.2.1 and *no extension* at all, I got:

> Warning, treated as error: index.rst:1:Pygments lexer name 'tango' is not known

So the issue is probably `myst_parser`. 

### conf.py

```python
import os
import sys

sys.path.insert(0, os.path.abspath('.'))
sys.path.insert(0, os.path.abspath('..'))

extensions = []
``` 

### index.rst

```rst
.. code-block:: tango

   bla
```

### main

```python
from sphinx.cmd.build import main

if __name__ == '__main__':
    raise SystemExit(main(['-M', 'html', '.', '_build', '-W']))
```

The layout is:

```
sphinx
├── conf.py
└── index.rst
```

**Comment by theletterf** [comment]
@picnixz Does that throw an error code when building with -W?

**Comment by picnixz** [comment]
The exit code is 2 so yes. I did nor check with the Makefile though

**Comment by theletterf** [comment]
Reopening just in case, as it's happening also when not editing Markdown docs.

**Comment by picnixz** [comment]
> Reopening just in case, as it's happening also when not editing Markdown docs.

What do you mean by "it happens when not editing Markdown docs"? Also, why is it an issue ? Unless maybe you want to say that the `-W` flag should override `-q`?

**Comment by theletterf** [comment]
In our setup we're using MyST because we've some Markdown files, but the issue also surfaced when generating rST files. You suggested [here](https://github.com/sphinx-doc/sphinx/issues/11442#issuecomment-1566109824) that this might be a MyST issue, but I'm not sure—how can we confirm that?

To restate the issue: lexer warnings should be treated as an error and produce exit code 2 in our setup, but they don't, with or without `-q`.

**Comment by picnixz** [comment]
> but I'm not sure—how can we confirm that?

Well, you actually said "only MyST Parser 1.0.0 as an extension". So I just built my example without any extension and since I got the error, I assumed that the extension was the issue.

> lexer warnings should be treated as an error and produce exit code 2 in our setup

What is your setup *exactly* ? it might happen that errors are actually entirely suppressed. For instance, if your Makefile ignores errors and just continues or if there are some `||` branch after executing the build command. Can you please share the script you use to build your files so that I can check locally ?

**Comment by theletterf** [comment]
Sure! Have a look: https://github.com/splunk/public-o11y-docs/blob/main/Makefile

**Comment by picnixz** [comment]
Actually, the issue is your Makefile I think:

- if you run your build *normally* (`make html`), you are not using the TESTOPTS but the ALLSPHINXOPTS variable. 
- only your `make test` is using `-W`. In addition, you have `--keep-going` which results in an exit code of 1 instead of 2.

FWICS, `make html` will not fail, `make test` *should* fail with an error code 1 and `make livehtml` is using `sphinx-autobuild` which is not maintained here.

**Comment by theletterf** [comment]
Thanks for having a look!

- `make html` is indeed not failing. We're not using it in our pipelines, so that's OK. It shows warnings as warnings.
- `make test` should fail. We want it to fail. We use `--keep-going` because we want to capture all issues.

Does it make sense? Any suggested fix?

**Comment by theletterf** [comment]
I see. Thanks, I'll do the switch.

**Comment by theletterf** [comment]
Done. Works now. It's 4 minutes and a half now vs 1 minute using `dummy`... I wonder if lexer issues could be caught _before_ writing to disk. Could they?

**Comment by picnixz** [comment]
Depends. Informally,

- You create the document tree (so there are nodes that are created). This is the building phase. During this phase, pygments theme is loaded and the highlighter as well.
- If you encounter a literal block node during the writing process, then you highlight it. This is the moment where the lexer name is checked.  

We can actually change the dummy builder by adding a post-transformation similar to the reference resolver or a transformation act on the nodes directly, before serializing. If you want to do it yourself, you can actually add the transformation in the configuration file as follows:

```python
from docutils.nodes import literal_block
from pygments.lexers import ClassNotFound, find_lexer_class_by_name
from sphinx.locale import __
from sphinx.transforms.post_transforms import SphinxPostTransform

class LexerValidation(SphinxPostTransform):
    default_priority = 500
    builders = ('dummy',)

    def __init__(self, *args, **kwargs):
        from sphinx.highlighting import lexers, lexer_classes, logger

        super().__init__(*args, **kwargs)
        self.lexer_names = lexers.keys() | lexer_classes.keys()
        self.logger = logger

    def run(self, **kwargs):
        for node in self.document.findall(literal_block):
            lang = node.get('language', 'default')
            self.validate_lexer(lang, node)

    def validate_lexer(self, lang, location):
        if lang in {'py', 'py3', 'python3', 'default', 'pycon3'}:
            lang = 'python'

        if lang in self.lexer_names:
            return

        try:
            lexer = find_lexer_class_by_name(lang)
        except ClassNotFound:
            self.logger.warning(__('Pygments lexer name %r is not known'), lang,
                                location=location)

def setup(app):
    app.add_post_transform(LexerValidation)
```

**Comment by theletterf** [comment]
I'd rather not customize our Sphinx deployment. Would it be interesting to apply this to Sphinx through a PR?

**Comment by picnixz** [comment]
> I'd rather not customize our Sphinx deployment

Well, you are already using extensions and what I just did is.. essentially an extension. 

> Would it be interesting to apply this to Sphinx through a PR?

IMO, no. The dummy builder is meant to be as much lightweighted as possible (it is also used in our test pipeline). Only the rst parsing must be actually performed by the builder but no post-processing should be done (e.g., no link resolution). We would probably need another builder, but the number of usecases is limited. It is better to just have a lightweighted extension like that. Feel free to pick my code and modify it as you wish (mention the issue if you want to remember where you picked it).

**Comment by theletterf** [comment]
Ah, brilliant! I’ll try that. Thanks _so_ much!

**Comment by theletterf** [comment]
@picnixz The patch extension is working!

**Comment by picnixz** [comment]
(Well, I would be a bit embarassed if it weren't the case!)
