### ISSUE TITLE
Table cause endless loop 'item too long to fit on line (page N)'

### ISSUE THREAD

**Issue by pdu3hc** [sphinx-doc/sphinx#11471]
### Describe the bug

In Support_Sphinx\source\modules\WdgM\generated\modification_parameters.txt, If I do not delete table name :ar:`error_table_error_table_error_table`, I am unable to generate pdf file because the endless loop 'item too long to fit on line (page N)'.

Any workaround for this beside delete the table ?

### How to Reproduce

Use [Support_Sphinx.zip](https://github.com/sphinx-doc/sphinx/files/11865381/Support_Sphinx.zip)
run command 'python -msphinx -M etas_pdf source build'

### Environment Information

```text
Platform:              win32; (Windows-10-10.0.19041-SP0)
Python version:        3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)])
Python implementation: CPython


Sphinx version:        7.0.1
Docutils version:      0.20.1
Jinja2 version:        3.1.2
Pygments version:      2.15.1
```

**Comment by jfbu** [comment]
This question should probably be addressed to [rinohtype project](https://github.com/brechtm/rinohtype), see also https://www.mos6581.org/rinohtype/master/, ping @brechtm

**Comment by brechtm** [comment]
@jfbu Thanks for pointing @pdu3hc in the right direction. Please go ahead and close this issue.
