### ISSUE TITLE
Linkcheck reports an error for closed pull request on github

### ISSUE THREAD

**Issue by PierreMarchand20** [sphinx-doc/sphinx#11477]
### Describe the bug

Linkcheck reports an error for closed pull request on github

### How to Reproduce

Use a link to `https://github.com/sphinx-doc/sphinx/pull/11418` for example in a sphinx project, and use `make linkcheck`. I obtain a 404 error with something like this: 

<img width="1077" alt="image" src="https://github.com/sphinx-doc/sphinx/assets/15056323/ca2ad0f0-20c4-41c1-a431-b2a77592e98c">

### Environment Information

```text
I reproduced this error with Sphinx `7.0.1`.
```

**Comment by picnixz** [comment]
The link being checked is `https://github.com/sphinx-doc/sphinx/pull/11418)` (with the final `)`) not `https://github.com/sphinx-doc/sphinx/pull/11418`.

Please check your RST content.
