### ISSUE TITLE
生产的html如何支持中文检索。

### ISSUE THREAD

**Issue by IamJasonBoy** [sphinx-doc/sphinx#11478]
**Is your feature request related to a problem? Please describe.**
生产的html如何支持中文检索。不需要修改代码。哪怕安装插件也可以

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

- [e.g. URL or Ticket]

**Comment by AA-Turner** [comment]
Sphinx development is conducted in English, closing this non-English issue.

A
