### ISSUE TITLE
Allow disabling linkcheck anchor checks for specific URLs

### ISSUE THREAD

**Issue by yukiisbored** [sphinx-doc/sphinx#11484]
**Is your feature request related to a problem? Please describe.**
It appears GitHub has made the Markdown renderer/file viewer require JavaScript which breaks linkcheck anchor checks. 

**Describe the solution you'd like**

A config which disables the linkcheck anchors check based on a regex of the entire URL would allow for cases like these to be handled while still validating whether the page itself exists and keep anchor checks enabled for others.

```python
linkcheck_anchors_disabled = [
   # Requires JavaScript
   r'https://github.com'
]
```

**Describe alternatives you've considered**

**Additional context**

This is what [the page](https://github.com/NixOS/nix.dev/blob/master/CONTRIBUTING.md#user-content-vision) looks like without JavaScript enabled:

<img width="1007" alt="Capture d’écran 2023-07-07 à 17 00 57" src="https://github.com/sphinx-doc/sphinx/assets/18437312/bed935cb-f044-4cae-9f73-6bba242a3bd8">

- Related issue: https://github.com/NixOS/nix.dev/issues/631

**Comment by picnixz** [comment]
@yukiisbored Just to be clear, if the url is

- `https://github.com/org/repo#anchor`, or
- `https://github.com/org/repo/blob/main/file.ext#anchor`,

you want `linkcheck` to only check that `https://github.com/org/repo` and `https://github.com/org/repo/blob/main/file.ext` exist **without** checking the anchors in the README or in `file.ext` respectively ?

**Comment by yukiisbored** [comment]
@picnixz yup, that is correct.
