### ISSUE TITLE
Add `autodecorator` to autodoc extension

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1148]
Since issue #478 was completed there has been talk about the possibility of adding `autodecorator` and possibly `autodecoratormethod` to the autodoc extension.  Any chance that could be added?

I'm not that familiar with how the underlying sphinx code works but I was able to get the `autodecorator` to work well enough for me just by doing this:

```
class DecoratorDocumenter(FunctionDocumenter):
    """
    Specialized Documenter subclass for decorator functions.
    """
    objtype = 'decorator'
```

and then adding the autodocumenter in the `setup()` at the end of the file?  Is that all that needs to be done?

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1148
- Originally reported by: Anonymous
- Originally created at: 2013-04-15T20:12:55.391

**Comment by avylove** [comment]
@shimizukawa, thanks for the workaround. I did have to modify it slightly so decorators that don't take arguments do not show parentheses. This is a bit hackish and I'm sure there is a better way to do it, but it will work for now until a real implementation gets in the code.

Workaround (add to conf.py):
```python
from sphinx.ext.autodoc import FunctionDocumenter

class DecoratorDocumenter(FunctionDocumenter):
    """
    Specialized Documenter subclass for decorator functions.
    """
    objtype = 'decorator'

    def format_args(self):
        args = super(DecoratorDocumenter, self).format_args()
        return args if ',' in args else None

def setup(app):
    app.add_autodocumenter(DecoratorDocumenter)
```

**Comment by tk0miya** [comment]
+0: seems good. But it is hard to detect the function is decorator or not. So `automodule` will not be able to support `autodecorator`.

**Comment by avylove** [comment]
@tk0miya Makes sense, but `autodecorator` would still be useful for declaring individual decorators.

**Comment by tk0miya** [comment]
@shimizukawa what do you think? if no objection, I'll start to work for this.

**Comment by shimizukawa** [comment]
I have no objection.

**Comment by tk0miya** [comment]
Okay, let's add this to next major release :-)

Could anyone send a pull request for us please? To merge it, testcode is needed.

**Comment by tk0miya** [comment]
Done at #6074.
Thank you for proposal!
