### ISSUE TITLE
dead link in docs: sphinx-contrib repository is no longer on bitbucket

### ISSUE THREAD

**Issue by wimlewis-amazon** [sphinx-doc/sphinx#11487]
### Describe the bug

https://github.com/sphinx-doc/sphinx/blob/d3c91f951255c6729a53e38c895ddc0af036b5b9/doc/faq.rst?plain=1#L43

this hyperlink is broken.

### How to Reproduce

follow the link

**Comment by AA-Turner** [comment]
Thanks!

A

**Comment by AA-Turner** [comment]
Resolved in de3aa8a3187cafee937af5f07957458e150f757a

A
