### ISSUE TITLE
Mathjax not working with singlehtml

### ISSUE THREAD

**Issue by spaceChRiS** [sphinx-doc/sphinx#11483]
### Describe the bug

This is probably related to #9686.

When using the mathjax extension, math is working in the html output but not in the singlehtml output.

Manually adding the line

    <script async="async" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>

which is missing in the singlehtml output but present in the html output makes math work well.

### How to Reproduce

Run sphinx with mathjax extension on a documentation containing some math with the singlehtml target. The actual test case that was used uses markdown files and math is not present in the main rst file but in one of the later included files (in case that makes a difference, which may be the case reading #9686).

### Environment Information

```text
This is running in a linux CI environment. I can reproduce it locally with sphinx 7.0.1.
```

### Sphinx extensions

```python
myst_parser, sphinx_math_dollar, sphinx.ext.mathjax
```

**Comment by picnixz** [comment]
You can do the following trick in `conf.py`:

```python
def setup(app):
    app.set_html_assets_policy('always')
```

**Comment by spaceChRiS** [comment]
This works for me, thank you very much!
