### ISSUE TITLE
Add versionremoved directive to complement versionadded and deprecated

### ISSUE THREAD

**Issue by consideRatio** [sphinx-doc/sphinx#11480]
## Background

In [PEP4](https://peps.python.org/pep-0004/), deprecated is a word used to indicate something may be removed in the future.

> Usage of a module may be ‘deprecated’, which means that it may be removed from a future Python release.

The existing sphinx directives `versionadded`, `versionchanged`, and `deprecated` are excellent in reference documentation, but when something deprecated is removed, its not clear what to do without a `versionremoved` directive. Authoring reference documentation, I'd like to document that something has been around even after it is removed and can't be used any more.

## Proposal

I suggest a `versionremoved` directive is added alongside the other related directives below, together with new documentation alongside `versionadded` [as seen here](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-versionadded).

https://github.com/sphinx-doc/sphinx/blob/d3c91f951255c6729a53e38c895ddc0af036b5b9/sphinx/domains/changeset.py#L21-L31

Looking into the details, it seems like this is relevant to update:

- [ ] Update `versionlabels` and `versionlabel_classes` [in domains/changeset.py](https://github.com/sphinx-doc/sphinx/blob/d3c91f951255c6729a53e38c895ddc0af036b5b9/sphinx/domains/changeset.py#L21-L31)
- [ ] Update docstring [in addnotes.py](https://github.com/sphinx-doc/sphinx/blob/d3c91f951255c6729a53e38c895ddc0af036b5b9/sphinx/addnodes.py#L357-L362)
- [ ] Update logic in [builders/changes.py](https://github.com/sphinx-doc/sphinx/blob/d3c91f951255c6729a53e38c895ddc0af036b5b9/sphinx/builders/changes.py#L23-L43)
- [ ] Update tests in by searching for `paragraph of versionchanged` without case sensitivity in the code base

## Options

Sphinx users can patch sphinx via the sphinx extension [`sphinx-removed-in` does](https://github.com/MrSenko/sphinx-removed-in/blob/d92df304b94ccd26a0f412dc2c92273ed2d43194/sphinx_removed_in/__init__.py#L17-L20), from where the proposal stems from - thank you @atodorov, @hroncok, @nicoddemus who have made commits to that project.

For `sphinx>=2`, this extension is like adding this to a conf.py file:

```python
# -- Add versionremoved directive ---------------------------------------------------
# ref: https://github.com/sphinx-doc/sphinx/issues/11480
#
from sphinx.domains.changeset import VersionChange, versionlabel_classes, versionlabels


def setup(app):
    if "versionremoved" not in versionlabels:
        versionlabels["versionremoved"] = "Removed in version %s"
        versionlabel_classes["versionremoved"] = "removed"
        app.add_directive("versionremoved", VersionChange)
```

**Comment by consideRatio** [comment]
## Preliminary implementation notes

- [ ] Update `versionlabels` and `versionlabel_classes` [in domains/changeset.py](https://github.com/sphinx-doc/sphinx/blob/d3c91f951255c6729a53e38c895ddc0af036b5b9/sphinx/domains/changeset.py#L21-L31)
- [ ] Update docstring [in addnotes.py](https://github.com/sphinx-doc/sphinx/blob/d3c91f951255c6729a53e38c895ddc0af036b5b9/sphinx/addnodes.py#L357-L362)
- [ ] Update logic in [builders/changes.py](https://github.com/sphinx-doc/sphinx/blob/d3c91f951255c6729a53e38c895ddc0af036b5b9/sphinx/builders/changes.py#L23-L43)

**Comment by picnixz** [comment]
PR is welcomed!

**Comment by consideRatio** [comment]
Thank you @hugovk and everyone involved!! 🎉 ❤️
