### ISSUE TITLE
Problem building documentation with project located in Filr (micro focus)

### ISSUE THREAD

**Issue by AntoineDps** [sphinx-doc/sphinx#11493]
### Describe the bug

I'm not sure that this can be referred as a bug.

I'm able to build normally my documentation using sphinx when my project is located, let's say on my desktop or elsewhere.

However I I have all my files backup in Filr (micro focus) that is what we use at my work. having recently moved my project to this backup system, I noticed that the sphinx cannot build it anymore, I have perform test elsewhere and it works. 
Of course I have double check the path and files name but nothing seems to work.

For your info, I can access Filr off-line as well as, since it synch automatically.

Here is the basic error I obtain, it seems that the source file can't be found eventhough it is just there:

```
(sphinx) C:\Users\antdu953\Filr\My Files\WAVE ENERGY\RESEARCH\MODELLING\xModel\docs>make html

Application error:
Cannot find source directory (C:\Users\antdu953\Filr\My Files\WAVE ENERGY\RESEARCH\MODELLING\xModel\docs\source)
```

### How to Reproduce

Move sphinx `docs` files and associated matlab file in the Filr (micro focus) backup app.

Compile with cmd your sphinx project from the sphinx `docs` repertory:
```
(sphinx) C:\Users\antdu953\Filr\My Files\WAVE ENERGY\RESEARCH\MODELLING\xModel\docs>make html
```
`docs` has the general architecture: 
*build
*source
*make.bat
*Makefile
*sphinxlog

### Environment Information

```text
I use a virtual environment, through anaconda 3.
I have installed:
*Sphinx v6.2.1
*napoleon package
*matlab sphinxcontrib


Platform:              win32; (Windows-10-10.0.19045-SP0)
Python version:        3.9.17 (main, Jul  5 2023, 20:47:11) [MSC v.1916 64 bit (AMD64)])
Python implementation: CPython
Sphinx version:        6.2.1
Docutils version:      0.18.1
Jinja2 version:        3.1.2
Pygments version:      2.15.1
```

### Sphinx extensions

```python
extensions = ['sphinxcontrib.matlab',
    'sphinx.ext.autodoc',
    'sphinx.ext.doctest',
    'sphinx.ext.napoleon',
    'sphinx.ext.todo',
    'sphinx.ext.autosummary']
```

### Additional context

Note that I haven't created the documentation from scratch in the Filr files. I was first working locally, and it was great until I moved everything to the backup storage Filr.

Note also that I have been using one drive automatic backup storage as well as, and everything worked perfectly with sphinx

Note that I use anaconda prompt

**Comment by picnixz** [comment]
This one appears tk be a Filr issue. I don't know if it's possible but try to create a simple project directly on it and build it there (without having a local copy). Otherwise, try the following:

- Wipe out the build folder and do it again.
- Try to build it directly by CLI: `python -m sphinx -b html source build -E` without using the Makefile (I assume that `sourcr` contains the sources and the configuration file).

Otherwise, I don't know.
