### ISSUE TITLE
No translation pull from transifex

### ISSUE THREAD

**Issue by NorwayFun** [sphinx-doc/sphinx#11497]
### Describe the bug

Hello,
I've added Georgian to sphinx-doc project on transifex and it's 70+% complete, but I cannot see it in source code.
Could you look into it, please?
BR, Temuri

### How to Reproduce

Files are not being pulled from transifex.

### Environment Information

```text
Also, I'd like to also submit translation for docutils. Could you point out how to do it, plase?
```

**Comment by AA-Turner** [comment]
> Also, I'd like to also submit translation for docutils. Could you point out how to do it, plase?

Look at ``docutils.languages`` and ``docutils.parsers.rst.languages`` -- it involves copying ``en.py`` to ``ka.py`` and then translating all the strings. There is a guide at 
https://docutils.sourceforge.io/docs/howto/i18n.html. You could then make a PR against https://github.com/docutils/docutils

A

**Comment by NorwayFun** [comment]
> > Also, I'd like to also submit translation for docutils. Could you point out how to do it, plase?
> 
> Look at `docutils.languages` and `docutils.parsers.rst.languages` -- it involves copying `en.py` to `ka.py` and then translating all the strings. There is a guide at https://docutils.sourceforge.io/docs/howto/i18n.html. You could then make a PR against https://github.com/docutils/docutils
> 
> A

It's there, https://github.com/docutils/docutils/pull/2

**Comment by bellaperez** [comment]
> Also, I'd like to also submit translation for docutils. Could you point out how to do it, plase?

**Informative:** I have already noted that you have to adapt another file into docutils project

**Comment by AA-Turner** [comment]
There were three errors with ``ca`` and one with ``zh_CH`` that were causing the translations workflow to fail, I've attempted to fix these and left comments on Transifex. #11255 includes Georgian.

A
