### ISSUE TITLE
Sphinx 7.1 breaks Furo's usage of css_tag(css) on Windows

### ISSUE THREAD

**Issue by henryiii** [sphinx-doc/sphinx#11518]
### Describe the bug

The 7.1.0 release is breaking the Furo theme; `css_tag(css)` is causing a file to be attempted to be opened with `?digest=e6660623a769aa55fea372102b9bf3151b292993` added to it, which of course breaks.

```pytb
  File "D:\a\scikit-build-core\scikit-build-core\.nox\docs\Lib\site-packages\furo\theme\furo\base.html", line 62, in block 'regular_styles'
    {{ css_tag(css) }}
  File "D:\a\scikit-build-core\scikit-build-core\.nox\docs\Lib\site-packages\jinja2\sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\a\scikit-build-core\scikit-build-core\.nox\docs\Lib\site-packages\sphinx\builders\html\__init__.py", line 1202, in css_tag
    if checksum := _file_checksum(app.outdir, css.filename):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\a\scikit-build-core\scikit-build-core\.nox\docs\Lib\site-packages\sphinx\builders\html\__init__.py", line 1254, in _file_checksum
    with open(path.join(outdir, filename), encoding='utf-8') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument: 'D:\\a\\scikit-build-core\\scikit-build-core\\docs\\_build\\html\\_static/styles/furo.css?digest=e6660623a769aa55fea372102b9bf3151b292993'
```

If it's @pradyunsg's Furo's fault, I can open an issue there instead, but this looks like it's an issue with the checksum additions mentioned for 7.1.0? Especially since it only happens on Windows.

Seen in https://github.com/scikit-build/scikit-build-core/pull/440 and https://github.com/scikit-build/scikit-build-core/pull/441.

### How to Reproduce

It's hard for me to test, since it's Windows only. Building Scikit-build-core's docs (via nox) on Windows would repeat it. I _think_ any usage of Furo would break it, it doesn't seem to be specific, as it's loading a css file. Maybe other themes that have this construct.

### Environment Information

```text
GitHub Actions, windows-latest, with the latest sphinx.
```

### Sphinx extensions

I think it can be done with just a theme.

**Comment by AA-Turner** [comment]
This is a problem with Furo, it seems -- `css.filename` must be a local file or a URI, and Furo seems to have used a workaround to achieve a similar feature via using an invalid filename (appending the checksum earlier), which Sphinx didn't previously check.

As such I don't think I consider this a breaking change in Sphinx. Sorry not to be more helpful.

A

**Comment by henryiii** [comment]
Ahh, it must be https://github.com/pradyunsg/furo/blob/f8db95bed5d1c57b4ea6bf536c65560fa9ae33a9/src/furo/__init__.py#L149-L153 then. Thanks! Will open an issue there.

**Comment by pradyunsg** [comment]
FWIW, it isn't limited to Furo -- at least one more theme is broken by this change. :)

**Comment by pradyunsg** [comment]
Consider reporting that to pydata-sphinx-theme?

**Comment by AA-Turner** [comment]
@story645 I can't reproduce that failure, please may you open a new issue or provide the command that you ran?

A

**Comment by pradyunsg** [comment]
@AA-Turner Do you think it's worth improving the error message in this case?

**Comment by AA-Turner** [comment]
Done in 44a7820, thank you for the suggestion.

A

**Comment by pradyunsg** [comment]
Awesome, thanks for the quick change! :)
