### ISSUE TITLE
sphinx crashes while compiling aria2

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1151]
When compiling aria2, sphinx crashes due to IndexError, giving the traceback here.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1151
- Originally reported by: Burgess Wong
- Originally created at: 2013-04-23T06:45:35.331

**Comment by tk0miya** [comment]
I salvaged the traceback from bitbucket:

```
# Sphinx version: 1.1.3
# Python version: 3.3.0
# Docutils version: 0.10 release
# Jinja2 version: 2.6
Traceback (most recent call last):
  File "/usr/lib/python3.3/site-packages/sphinx/cmdline.py", line 189, in main
    app.build(force_all, filenames)
  File "/usr/lib/python3.3/site-packages/sphinx/application.py", line 204, in build
    self.builder.build_update()
  File "/usr/lib/python3.3/site-packages/sphinx/builders/__init__.py", line 191, in build_update
    self.build(['__all__'], to_build)
  File "/usr/lib/python3.3/site-packages/sphinx/builders/__init__.py", line 252, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/lib/python3.3/site-packages/sphinx/builders/manpage.py", line 88, in write
    docwriter.write(largetree, destination)
  File "/usr/lib/python3.3/site-packages/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "/usr/lib/python3.3/site-packages/sphinx/writers/manpage.py", line 35, in translate
    self.document.walkabout(visitor)
  File "/usr/lib/python3.3/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3.3/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3.3/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3.3/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3.3/site-packages/docutils/nodes.py", line 187, in walkabout
    visitor.dispatch_departure(self)
  File "/usr/lib/python3.3/site-packages/docutils/nodes.py", line 1640, in dispatch_departure
    return method(node)
  File "/usr/lib/python3.3/site-packages/sphinx/writers/manpage.py", line 91, in depart_desc
    self.depart_definition_list(node)
  File "/usr/lib/python3.3/site-packages/docutils/writers/manpage.py", line 544, in depart_definition_list
    self.dedent()
  File "/usr/lib/python3.3/site-packages/docutils/writers/manpage.py", line 865, in dedent
    self._indent.pop()
IndexError: pop from empty list
```

**Comment by usaturn** [comment]
I confirmed that a problem did not appear in a problem being given in an old version and the latest version.
This problem seemed to be revised in #998.

A problem is over this pattern.

Python 3.3.3
Sphinx==1.1.3
docutils==0.10
Jinja2==2.6

> $  python -V
> Python 3.3.3
> $ pip install Sphinx==1.1.3 docutils==0.10 Jinja2==2.6
> 
> git clone https://github.com/tatsuhiro-t/aria2.git
> cd aria2/doc/manual-src/en
> cp -ip conf.py.in conf.py
> 
> change conf.py
> 
> --- conf.py.in  2016-02-07 15:30:35.000000000 +0900
> +++ conf.py     2016-02-07 16:23:26.000000000 +0900
> @@ -48,9 +48,9 @@
>  # built documents.
>  #
>  # The short X.Y version.
> -version = '@PACKAGE_VERSION@'
> +version = '1'
>  # The full version, including alpha/beta/rc tags.
> -release = '@PACKAGE_VERSION@'
> +release = '1'
> 
>  # The language for content autogenerated by Sphinx. Refer to documentation
>  # for a list of supported languages.
> @@ -91,7 +91,8 @@
> 
>  # The theme to use for HTML and HTML Help pages.  See the documentation for
>  # a list of builtin themes.
> -html_theme = 'sphinx_rtd_theme'
> +#html_theme = 'sphinx_rtd_theme'
> +html_theme = 'default'
> 
>  # Theme options are theme-specific and customize the look and feel of a theme
>  # further.  For a list of options available for each theme, see the
> @@ -99,7 +100,7 @@
>  #html_theme_options = {}
> 
>  # Add any paths that contain custom themes here, relative to this directory.
> -html_theme_path = ['@srcdir@/../../sphinx_themes']
> +#html_theme_path = ['@srcdir@/../../sphinx_themes']
> 
>  # The name for this set of Sphinx documents.  If None, it defaults to
>  # "<project> v<release> documentation".
> 
> $ sphinx-build -b html . _build #OK
> 
> $ sphinx-build -b man . _build
>     Running Sphinx v1.1.3
>     loading pickled environment... done
>     building [man]: all manpages
>     updating environment: 0 added, 1 changed, 0 removed
>     reading sources... [100%] libaria2   aria2/doc/manual-src/en/libaria2.rst:218: SEVERE: Problems with "include" directive path:
>     InputError: [Errno 2] No such file or directory: 'libaria2api'.
>     looking for now-outdated files... none found
>     pickling environment... done
>     checking consistency... done
>     writing... aria2c.1 { } 
>     Exception occurred:
>       File "/var/env/sphinx/lib/python3.3/site-packages/docutils/writers/manpage.py", line 865, in dedent
>         self._indent.pop()
>     IndexError: pop from empty list
>     The full traceback has been saved in /tmp/sphinx-err-i1m0yn.log, if you want to report the issue to the developers.
>     Please also report this if it was a user error, so that a better error message can be provided next time.
>     Either send bugs to the mailing list at http://groups.google.com/group/sphinx-dev/,
>     or report them in the tracker at http://bitbucket.org/birkenfeld/sphinx/issues/. Thanks!

Pattern without a problem

Python 3.3.3
Sphinx==1.3.5
docutils==0.12
Jinja2==2.8

> $  python -V
> Python 3.3.3
> $ pip install Sphinx==1.3.5 docutils==0.12 Jinja2==2.8
> $ sphinx-build -b html . _build #OK
> $ sphinx-build -b man . _build #OK
> Running Sphinx v1.3.5
> making output directory...
> loading pickled environment... not yet created
> building [mo]: targets for 0 po files that are out of date
> building [man]: all manpages
> updating environment: 5 added, 0 changed, 0 removed
> reading sources... [100%] technical-notes aria2/doc/manual-src/en/libaria2.rst:218: SEVERE: Problems with "include" directive path:
> InputError: [Errno 2] No such file or directory: 'libaria2api'.
> looking for now-outdated files... none found
> pickling environment... done
> checking consistency... done
> writing... aria2c.1 { }
> build succeeded, 1 warning.

**Comment by shimizukawa** [comment]
Thanks @usaturn.
I agree that this issue is same as #998 and it is fixed.

Now I close this issue as fixed.
Feel free to reopen if you still have this issue.
