### ISSUE TITLE
latexpdf issue

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1153]
Doing a make latexpdf, I've just found a bug that prevents the tex document to be created. It happens when a figure appears inside a sidebar. here is the code:

```
#!python

.. sidebar:: Mysidebar

    Blablablablabla

    .. figure:: images/myimage.png 
        :width: 1286px
        :height: 959px
        :scale: 50 &#37;
        :alt: Alternative text
        :align: center

    Some tittle 

```

make stops returning 

```
#!python
! LaTeX Error: Float(s) lost.

```

With image insted of figure the problem is solved, but the output would not be the desired

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1153
- Originally reported by: Anonymous
- Originally created at: 2013-04-24T19:02:58.820

**Comment by tk0miya** [comment]
Fixed at f875059.
Thank you for reporting
