### ISSUE TITLE
Sphinx v6.2.1: doesnt exclude patterns per doxygen group

### ISSUE THREAD

**Issue by VSCBSt** [sphinx-doc/sphinx#11545]
### Describe the bug

Two c++ .h files contain some equal (duplicate) declarations. In the code, both files are mutually excluded from compilation in `cmake` file, dependent on a version. Everything compiles and functions as it should be.

Sphinx-doc however, produces errors.

The following situation describes my problem:
in file `a.h`
``` 
/// @addtogroup A
/// @{
```
...
and in file `ab.h`
``` 
/// @addtogroup AB
/// @{
```
...

In `conf.py.in`
`exclude_patterns = ['AB.rst*']`

Than the error message appears:
`docs/docs-gen/_sphinx_sources/cpp/A.rst:4: WARNING: Duplicate C++ declaration, also defined at cpp/A:4.`

And if 
`exclude_patterns = ['A.rst*']`

Than the error message appears:
`docs/docs-gen/_sphinx_sources/cpp/AB.rst:4: WARNING: Duplicate C++ declaration, also defined at cpp/AB:4.`

Only if I set
`exclude_patterns = ['A.rst*', 'AB.rst*']`
I dont get error messages.

It seems its a bug ?

Is there a way to set a switch to exclude patterns dependent on some input ?

### How to Reproduce

Try to have some equal declarations in two mutually excluded from compilation .h files and observer the above behavior.

### Environment Information

```text
Platform:              linux; (Linux-6.1.0-1008-oem-x86_64-with)
Python version:        3.10.12 (main, Jun  9 2023, 02:29:43) [GCC 12.2.1 20220924])
Python implementation: CPython
Sphinx version:        6.2.1
Docutils version:      0.18.1
Jinja2 version:        3.1.2
Pygments version:      2.15.1
```

**Comment by AA-Turner** [comment]
We only support the latest version of Sphinx -- does the error still appear in Sphinx 7.1.1?

A

**Comment by picnixz** [comment]
Closing since the OP didn't reply for a while. Feel free to reopen after giving us an example of what you want.
