### ISSUE TITLE
When not using -a option with sphinx-build, it will still modify all the html file.

### ISSUE THREAD

**Issue by revati-naik** [sphinx-doc/sphinx#11541]
### Describe the bug

When I use sphinx without the `-a` option, it will sill modify all the `.html` files in the output directory. 

### How to Reproduce

Run the `sphinx-build` command without the `-a` option. Verify the output files written to the output directory. 

### Environment Information

```text
Using sphinx version from this commit (https://github.com/sphinx-doc/sphinx/commit/ba7408209e84ee413f240afc20f3c6b484a81f8f)
```

**Comment by picnixz** [comment]
All files that are changed will be written again. The way that files are decided to be rebuilt is according to whether there are dependencies or not that are involved.

**Comment by revati-naik** [comment]
> All files that are changed will be written again. The way that files are decided to be rebuilt is according to whether there are dependencies or not that are involved.

Thanks for the reply. Another follow-up question is how it knows about the changed files. If I am running this in a new environment every time, then I believe there will be no reference for it to compare and get the changed files.

**Comment by picnixz** [comment]
I've explained a bit on how changed files are detected in https://github.com/sphinx-doc/sphinx/issues/11556#issuecomment-1667451983. 

> If I am running this in a new environment every time, then I believe there will be no reference for it to compare and get the changed files

I don't understand your point. If you are in a new environment, then it's as if you're building for the very first time so it's correct to assume that you will rewrite everything.

**Comment by picnixz** [comment]
Closing as the initial issue is no more an issue. For questions, please ask them on Stackoverflow (this repository is only for core development).
