### ISSUE TITLE
autodoc_docstring_signature fails for methods under Python 3.x

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1155]
Under Python 3.x, the automatic extraction of call signatures fails for methods. My (wild guess) is that this is related to the fact that the type (as reported in the _what_ parameter of _autodoc-process-signature_ has changed from `method` to `attribute`.

I have attached a test case. Run with:

```
$ python3.3 setup.py build_ext --inplace
$ PYTHONPATH=`pwd` sphinx-build -E -a . doc
```

Under Python 3.3, the Operations.lookup method lacks a signature, and the signature is still part of the docstring.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1155
- Originally reported by: Nikolaus Rath
- Originally created at: 2013-04-29T00:44:57.052

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2014-01-12 15:42:48+00:00_

Thanks for the testcase, that made it easy to debug!

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2014-01-12 15:43:00+00:00_

Closes #1155: Fix autodocumenting C-defined methods as attributes in Python 3.

→ <<cset aac72f175ab52779832961a88f6e8b8e94375d21>>

**Comment by embray** [comment]
Any idea what the test case for this was?  I'm trying to fix a related bug, but I want to make sure it doesn't cause a regression on this issue.  However, the old bitbucket site is disabled so I can't get at it.

**Comment by embray** [comment]
Nevermind, I think I understand the reason for this.  That's pretty obscure though.
