### ISSUE TITLE
toctree gives misleading warnings when contents isn't correctly aligned

### ISSUE THREAD

**Issue by cjdb** [sphinx-doc/sphinx#11555]
### Describe the bug

I get the following warnings when building:

```
/home/cjdb/projects/amcpp-book-sphinx/source/index.rst:9: WARNING: toctree contains reference to nonexisting document ' :maxdepth: 2'
/home/cjdb/projects/amcpp-book-sphinx/source/index.rst:9: WARNING: toctree contains reference to nonexisting document ' :caption: Contents:'
```

The toctree in question looks like this:

```rst
.. toctree::
   :maxdepth: 2
   :caption: Contents:

  01-intro
```

Notice that the indentation for `01-intro` is off-by-one. Rather than emitting the above two warnings---which aren't helpful in solving the problem---it would be good to warn that there are lines under `toctree` that are misaligned (this may even be worth erroring out on).

### How to Reproduce

Generate a new project using `sphinx-autogen`, copy my toctree from above, create  a file called `01-intro.rst`, and `make html`.

### Environment Information

```text
Platform:              linux; (Linux-6.4.7-arch1-2-x86_64-with-glibc2.38)
Python version:        3.11.3 (main, Jun  5 2023, 09:32:32) [GCC 13.1.1 20230429])
Python implementation: CPython
Sphinx version:        6.2.1
Docutils version:      0.18.1
Jinja2 version:        3.1.2
Pygments version:      2.15.1
```

### Sphinx extensions

```python
None
```

**Comment by cjdb** [comment]
Ah, I see what's happened here. My indentation isn't correct, and so Sphinx has gotten confused about stuff. I'm going to edit the bug accordingly.

**Comment by picnixz** [comment]
This is not a bug. RST specifications allow you to have an arbitrary number of spaces to indent the body of the directive and the number of indents is detected automatically. Although it is recommended to use 3-spaces, it is not mandatory. Here, docutils detected it as having a two-space indent. Note that the indent is determined by parsing the lines without entering the directives themselves (the first indentation level is assumed to be the one).

Also, it is entirely valid to write something like:

```rst
.. warning::
   
   3 indent


.. warning::
   
    4 indents
```

in the same file. One possibility would be to modify the `:toctree:` directive itself, but the question still remains on whether the directive options should indicate the correct level of indentation or the directive content. So I don't think it's a good idea.

**Comment by picnixz** [comment]
After reflection, I don't think we plan to change the current behaviour since we cannot say whether the directive options or the directive content are the most important and since it's docutils that is doing the job of parsing the directive content.
