### ISSUE TITLE
[Meta] Gather support for ``Framework :: Sphinx :: Domain`` PyPI classifier

### ISSUE THREAD

**Issue by jdillard** [sphinx-doc/sphinx#11562]
The [list of domains](https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#more-domains) in the docs is somewhat outdated and I think it would be useful if we could take advantage of the PyPI trove classifiers and create a ``Framework :: Sphinx :: Domain``, similar to [``Framework :: Sphinx :: Extension``](https://pypi.org/search/?c=Framework+%3A%3A+Sphinx+%3A%3A+Extension). But first we need to have the classifier approved and created using these guidelines:

> - New Framework classifiers should be created if they are "notable;" and
> - They will be of immediate use to existing projects (in other words, no creating classifiers simply in anticipation of future uses)
> We understand that "notability" is subjective and we'd appreciate help judging that.
>
> As to the other guideline ('immediate use to existing projects'), it's been suggested that
>
> - Requestors can demonstrate this by providing links to 10 or more existing PyPI projects that have expressed a desire to use the classifier; or
> - Another way to demonstrate this would be to have 10 or more other project maintainers submit comments on the requesting issue about their desire to use the classifier.

If you maintain a Sphinx domain and think a ``Framework :: Sphinx :: Domain`` would be useful for helping people find your domain as well as the greater Sphinx ecosystem, please leave a comment expressing interest in using the classifier with a link to the package that you maintain to help with the approval process.

**Comment by AA-Turner** [comment]
Note: there are ~200 ``Framework :: Sphinx :: Extension`` packages [listed on PyPI](https://pypi.org/search/?q=domain&o=&c=Framework+%3A%3A+Sphinx+%3A%3A+Extension) that match the term "domain".

A

**Comment by joeced** [comment]
I'm interested, I maintain the `MATLAB Domain` at

https://github.com/sphinx-contrib/matlabdomain

**Comment by markstory** [comment]
I can see the additional classifier being helpful to folks looking for domains. :+1:. I maintain the [php domain](https://github.com/markstory/sphinxcontrib-phpdomain)

**Comment by taminomara** [comment]
+1, that'd be useful (author of [AntLR4 domain](https://github.com/taminomara/sphinx-a4doc)).

**Comment by AWhetter** [comment]
I can see this being useful. Finding whether a domain exists currently involves using a search engine for something like "graphql sphinx domain" and hoping that brings something up, which might not always be the case for new projects. Alternatively a user could use the unreliable method of searching for packages with a common naming convention like "gqldomain" or "graphqldomain", but there's no guarantee that the naming convention is followed.

So if this classifier existed then I'd make use of it on https://github.com/AWhetter/graphqldomain

**Comment by SilverRainZ** [comment]
+1 from the [any](https://github.com/sphinx-notes/any) domain.

**Comment by danwos** [comment]
Also interested in this.
Mostly as a maintainer of [Sphinx-Bazel](https://github.com/useblocks/sphinx-bazel), but also as I'm maintaining an automated list of Sphinx-Extensions, which is based on the Classifiers: https://awesomesphinx.useblocks.com/

**Comment by hio** [comment]
+1 from [erlangdomain](https://github.com/hio/sphinx-erlangdomain).

**Comment by cblegare** [comment]
+1 from https://github.com/cblegare/sphinx-compendia which is not a domain per se but still a simple API for creating Sphinx domains and structuring arbitrary collections.

**Comment by jdillard** [comment]
That makes 10! I created the request to add the `Framework :: Sphinx :: Domain` classifier here: https://github.com/pypa/trove-classifiers/pull/163

**Comment by jdillard** [comment]
The new trove classifiers were merged in https://github.com/pypi/warehouse/pull/15012, and I'm fairly sure that was the last step but not 100% sure since it doesn't show up on [PyPi](https://pypi.org/search/?q=&o=&c=Framework+%3A%3A+Sphinx&c=Framework+%3A%3A+Sphinx+%3A%3A+Domain) if no packages are using it. Would anyone want to test out making a release with the new `Framework :: Sphinx :: Domain` to confirm it is live?

**Comment by joeced** [comment]
Confirmed! I released a new version of the `MATLAB Domain` and it's now listed when searching for `Framework :: Sphinx :: Domain`:

https://pypi.org/search/?c=Framework+%3A%3A+Sphinx+%3A%3A+Domain

**Comment by AA-Turner** [comment]
Closing as the trove classifier now exists!

A
