### ISSUE TITLE
``sphinx-testing`` on PyPI

### ISSUE THREAD

**Issue by AA-Turner** [sphinx-doc/sphinx#11564]
cc: @shimizukawa -- please would you be able to add me as an Owner to the [Sphinx-Testing ](https://pypi.org/project/sphinx-testing/) package, or transfer it to the [Sphinx organisation on PyPI](https://pypi.org/org/Sphinx/)?

A

**Comment by shimizukawa** [comment]
@AA-Turner OK, now you are invited in the owner role.

**Comment by AA-Turner** [comment]
Thank you! I've just transferred to the Sphinx organisation!

A
