### ISSUE TITLE
Using PEP585 builtin Generics gives fully qualified versions of its args with autodoc

### ISSUE THREAD

**Issue by EFord36** [sphinx-doc/sphinx#11571]
### Describe the bug

When using deprecated Generics from `typing` like `typing.List`, the arguments to the generic get resolved in a 'smart' way so that they're not fully qualified. However, this doesn't happen when using the PEP585 approach with just the builtin e.g. `list`.

This also affect deprecated `typing` members like `typing.Callable`, even though this isn't a builtin after PEP585, it's `collections.abc.Callable`. The behaviour seems similar/the same to me, and also causes issues.

E.g. 

 . This isn't much of an issue here, but fully qualified names become very unwieldy when 

### How to Reproduce

(order in code given alphabetically to match rendered docs order)

```python
from typing import List, Callable
from collections.abc import Callable as collectionsCallable
from re import Pattern


def test_callable_collections_abc(func: collectionsCallable[[Pattern], Pattern]) -> None:
    return None

def test_callable_typing(func: Callable[[Pattern], Pattern]) -> None:
    return None

def test_func_builtins(patterns: list[Pattern]) -> None:
    return None

def test_func_typing(patterns: List[Pattern]) -> None:
    return None
```

![Screenshot 2023-08-09 at 15 55 20](https://github.com/sphinx-doc/sphinx/assets/20516159/a0f8d938-a2bf-4916-b5c7-13deb6367d9a)

Note that the `typing` versions just get `Pattern` as opposed to `re.Pattern`

### Environment Information

```text
Platform:              darwin; (macOS-13.5-arm64-arm-64bit)
Python version:        3.9.16 (main, Apr 10 2023, 20:40:48) 
[Clang 14.0.3 (clang-1403.0.22.14.1)])
Python implementation: CPython
Sphinx version:        7.1.2
Docutils version:      0.20.1
Jinja2 version:        3.1.2
Pygments version:      2.16.1
```

### Sphinx extensions

```python
["sphinx.ext.autodoc"]
```

### Additional context

I think the preferable behaviour that annotations from `typing` get basically comes from this branch in the code:

https://github.com/sphinx-doc/sphinx/blob/3e30fa36a241bade5415051ab01af981caa29d62/sphinx/util/typing.py#L294

I'd be willing to give it a go changing this if you were interested, but I suspect there's more work involved in deciding things like whether this behaviour should affect user-defined Generics too, and whether/how this can be changed in a sphinx release (since there's a perspective of its a change in default behaviour rather than a bug fix), so not sure how useful my offer of help is.

For the broader context of what I'm trying to achieve - I got through a change to replace the deprecated typing aliases across my whole codebase automatically using `pyupgrade`, targeting pythons 3.9 and newer. However, this then raised new sphinx errors and make the docs pretty ugly in a substantial number of places because of how Sphinx handles these cases differently.

This seems to me like a bug in the sense that using the recommended approach (the builtins/collections.abc.Callable etc.) gives worse output and some errors when 'swapping in' for the old, deprecated approach.

This quite readable, nice annotation:

![image](https://github.com/sphinx-doc/sphinx/assets/20516159/d38c944f-e87d-4dad-afcd-72f10d5b6004)

becomes this, which I feel is too long to read:

![image](https://github.com/sphinx-doc/sphinx/assets/20516159/b58d2999-1126-4dcf-acf7-9844613c3910)

And a return type annotation fails - equivalent to:

```python
def some_func(cls, d) -> dict[str, Union[dict[str, Any], list, int, float, bool, str, type(None)]]
```

gives a warning from trying to link the reference with intersphinx:

`WARNING: py:class reference target not found: NoneType`

which is tricky for me because I get sphinx to treat warnings as error so I don't accidentally have broken links elsewhere.

**Comment by patacca** [comment]
I guess this https://github.com/sphinx-doc/sphinx/pull/11570 should fix the long name issue

**Comment by EFord36** [comment]
That's awesome! You must have been just submitting your PR for this while I was writing the issue?! Great timing if so - thanks so much for it!

**Comment by EFord36** [comment]
Deleting my 'repro repo' https://github.com/EFord36/sphinx-bug-report/tree/main now that this is closed

**Comment by AA-Turner** [comment]
Thanks Elliot!

A

**Comment by VikramJaryal** [comment]
Reinsert
