### ISSUE TITLE
``nbsphinx`` TocTree broken monkey-patching 

### ISSUE THREAD

**Issue by AA-Turner** [sphinx-doc/sphinx#11589]
> OK, I looked into it and it turns out that I was wrong. The document structure is not different, but my monkey-patching is broken.
>
> In https://github.com/spatialaudio/nbsphinx/pull/756 I'm trying to monkey-patch `_resolve_toctree` instead of `TocTree.resolve` (depending on Sphinx version), but it still doesn't work.
>
> It seems like setting the property `toctree['nbsphinx_gallery']` doesn't work anymore, do you have an idea why this might be the case?

_Originally posted by @mgeier in https://github.com/sphinx-doc/sphinx/issues/11565#issuecomment-1676435062_

**Comment by AA-Turner** [comment]
This is odd, as the ``toctree.get('nbsphinx_gallery', False)`` call happens before the call to ``original_toctree_resolve``.

A

**Comment by AA-Turner** [comment]
```python
import sphinx.environment.adapters.toctree
from sphinx import addnodes

original_toctree_resolve = sphinx.environment.adapters.toctree._resolve_toctree


def patched_toctree_resolve(env, docname, builder, toctree, *args, **kwargs):
    assert toctree.get('nbsphinx_gallery', False) is True
    node = original_toctree_resolve(env, docname, builder, toctree, *args, **kwargs)

    return node


def doctree_resolved(app, doctree, fromdocname):
    for node in doctree.findall(addnodes.toctree):
        node['nbsphinx_gallery'] = True


def setup(app):
    app.connect('doctree-resolved', doctree_resolved)
    sphinx.environment.adapters.toctree._resolve_toctree = patched_toctree_resolve
    return {'version': 1, 'parallel_read_safe': True, 'parallel_write_safe': True}
```

**Comment by AA-Turner** [comment]
@mgeier it turns out that the problem here is the patching itself--by changing from ``TocTree.resolve`` to a module-level function, when using a ``from ... import ...`` statement the patching doesn't apply to the copy in that module, and therefore fails. I've changed to look up the function on an imported module, which enables your use case.

A

**Comment by mgeier** [comment]
Thanks a lot @AA-Turner for looking into this and for fixing it on the Sphinx side!

I've fixed `nbsphinx` at https://github.com/spatialaudio/nbsphinx/pull/756, created a new release 0.9.3 and now the thumbnail galleries are displayed correctly again: https://nbsphinx.readthedocs.io/en/0.9.3/gallery/gallery-with-nested-documents.html
