### ISSUE TITLE
[ANNOUNCEMENT] Potential Breaking Changes in Sphinx 7.2.x

### ISSUE THREAD

**Issue by picnixz** [sphinx-doc/sphinx#11608]
# Sphinx 7.2.5

[Sphinx 7.2.5](https://pypi.org/project/Sphinx/7.2.5/) has been released **with fixes for all known outstanding issues**

**Please upgrade to Sphinx 7.2.5, and report any new failures**

A

-----

# Original issue

I am opening this issue in order to track the issues related to the API changes that Sphinx 7.2 implemented. Since most of the issues are hard to hotfix, I would just recommend using an older version of Sphinx until this is fixed (probably in 7.2.1).

## TocTree related API

In https://github.com/sphinx-doc/sphinx/pull/11565, we decided to refactor the toctree adapter. This caused issues with `pydata` theme and other themes as well. Most of the issues are caused by the fact that the TocTree adapter exposed as a class contained public methods that extensions used. However, TocTree was never considered as a public API (it is not documented at all, see https://github.com/pydata/pydata-sphinx-theme/issues/1404#issuecomment-1673713452), so we did not expect that this would lead to breaking changes (see https://github.com/pydata/pydata-sphinx-theme/issues/1404#issuecomment-1674070013). 

We are planning to something about this (maybe we could expose part of the private API).

Issues:

- https://github.com/sphinx-doc/sphinx/issues/11604
- https://github.com/sphinx-doc/sphinx/issues/11607
- https://github.com/pydata/pydata-sphinx-theme/issues/1404

## Javascript and CSS issues

Before, Javascript and CSS files were represented internally using classes that may also behave as strings. Many extensions relied on that and are broken (or may be broken). The string representation was originally intended for backward compatibility but way before these objects were introduced and should not have been used as such. It was now deprecated in https://github.com/sphinx-doc/sphinx/pull/11582 (but we should have kept the `str` behaviour until removing completely the old objects).

Another breaking change is `app.add_js_file` (everything I say about JS files is essentially valid for CSS files). Before `app.add_js_file` also injected the JS file into the builder's JS files, which was a *reference* to `ctx['script_files']` in the HTML context that extensions could play with. However, if extensions call `app.add_js_file` in their own `html-page-context` handler, the JS files will *NOT* be added to the builder's files, and not to `ctx['script_files']` neither. So no JS file will be injected (see https://github.com/sphinx-doc/sphinx/issues/11586#issuecomment-1682168097).

We are planning to something about this (either we revert to the old behaviour or fix the current one). 

Issues:

- https://github.com/sphinx-doc/sphinx/issues/11586#issuecomment-1676442009
- https://github.com/sphinx-doc/sphinx/issues/11606
- https://github.com/readthedocs/sphinx_rtd_theme/issues/1502
- https://github.com/kai687/sphinxawesome-theme/issues/1464
- https://github.com/pradyunsg/furo/discussions/693

## `pathlib.Path` objects vs plain strings

In https://github.com/sphinx-doc/sphinx/pull/11526, we changed most of the `str` objects that behaved like a path to `pathlib.Path` objects. This breaks extensions or themes relying on the fact that the object was a string. 

Issues:

- https://github.com/sphinx-doc/sphinx/issues/11605

cc @AA-Turner @humitos

**Comment by pllim** [comment]
Thanks for tracking this! Was there no RC period for so many breaking changes? 😢

**Comment by picnixz** [comment]
Most of them were actually considered as internal changes (we cannot be aware of all extensions using part of the API that we thought to be private since not documented). Nonetheless, the change concerning `add_js_files` shouldn't have introduced the bug (this change is actually a real regression, others are not really breaking changes since they should not have been used outside of Sphinx itself).

**Comment by picnixz** [comment]
@AA-Turner Thank you for the fixes. Can you pin the issue?

**Comment by stephenfin** [comment]
Found another one, I think. `Environment.srcdir` is now a `Path` object instead of a string. This breaks any and all plugins that rely on this attribute. This was introduced in 49d8304670. Given this breaks a user-visible API, this feels like something that should be reverted and introduced in a major version, rather than a minor release.

Example: https://review.opendev.org/c/openstack/openstackdocstheme/+/891678

**Comment by kevalmorabia97** [comment]
I am still getting the below error after upgrading to `7.2.1`
```python
Extension error (furo):
Handler <function _html_page_context at 0x7f3492215580> for event 'html-page-context' threw an exception (exception: This documentation is not using `furo.css` as the stylesheet. If you have set `html_style` in your conf.py file, remove it.)
make: *** [Makefile:24: html] Error 2
```

**Comment by AA-Turner** [comment]
[Sphinx 7.2.2](https://pypi.org/project/Sphinx/7.2.2/) has been released, which contains fixes for Furo, and three other bugs.

A

**Comment by picnixz** [comment]
@AA-Turner thank you very much ! (maybe you could edit the announcement, since it appears I cannot re-edit it?)

**Comment by oddbookworm** [comment]
Updating to sphinx 7.2.0 breaks our documentation headers at [pygame-ce](https://github.com/pygame-community/pygame-ce). As an example, here's the current [doc page for pygame-ce's draw module](https://github.com/pygame-community/pygame-ce/blob/main/src_c/doc/draw_doc.h), and here's what the doc looks like when I generate locally with 7.2.0 (7.1.2 produces what's on github)
```c
/* Auto generated file: with makeref.py .  Docs go in docs/reST/ref/ . */
#define DOC_DRAW_RECT "rect(surface, color, rect) -> Rect\nrect(surface, color, rect, width=0, border_radius=0, border_top_left_radius=-1, border_top_right_radius=-1, border_bottom_left_radius=-1, border_bottom_right_radius=-1) -> Rect\ndraw a rectangle"
```
The reST source for that doc is [here](https://github.com/pygame-community/pygame-ce/blob/main/docs/reST/ref/draw.rst) and here is our [makeref.py](https://github.com/pygame-community/pygame-ce/blob/main/buildconfig/makeref.py)

**Comment by pradyunsg** [comment]
Adding https://github.com/sphinx-doc/sphinx/commit/8e730ae303ae686705ea12f44ef11da926a87cf5 to the list here -- it changed the behavior such that `data-content_root` needs to be set (it moved from a script without `"use strict";` to a script that contains it).

Before:

```
document.getElementById("documentation_options").getAttribute('data-url_root')
```

After:

```
document.documentElement.dataset.content_root
```

It shouldn't affect themes that use `base.html` as-is from Sphinx; which... well, that's most theme. Furo doesn't and I'll be fixing that in a few minutes.

PS: Even though this release has been slightly disruptive, I do want to note that I appreciate the work that Sphinx's maintainers (notably @AA-Turner lately) have been doing! ^.^

**Comment by AA-Turner** [comment]
[Sphinx 7.2.3](https://pypi.org/project/Sphinx/7.2.3/) has been released.

A

**Comment by AA-Turner** [comment]
[Sphinx 7.2.4](https://pypi.org/project/Sphinx/7.2.4/) has been released.

A

**Comment by AA-Turner** [comment]
[Sphinx 7.2.5](https://pypi.org/project/Sphinx/7.2.5/) has been released.

A

**Comment by picnixz** [comment]
With [Sphinx 7.2.6](https://pypi.org/project/Sphinx/7.2.6) being released, I think this issue can be closed. Anyone is free to reopen if they think that a change introduced between 7.2.0 and 7.2.5 is breaking.
