### ISSUE TITLE
Builder linkcheck parsing wrong links declared inside HTML tags 

### ISSUE THREAD

**Issue by jorgepiloto** [sphinx-doc/sphinx#11601]
### Describe the bug

If a docstring contains a pure HTML tag like:

```python
class Foo:
    ...
    
Foo.__doc__ = "Some content with a pure HTML <a href='https://www.python.org/'>link</a> tag."
```

the ``linkcheck`` builder complains as it parses it with the closing single quote, see:

```console
(index: line 1) broken    https://www.python.org/' - 404 Client Error: Not Found for url: https://www.python.org/'
```

### How to Reproduce

The ``src/linkcheck_bug/__init__.py`` file:

```python
"""Test linkcheck."""

__version__ = "0.1.dev0"
class Foo:
    ...

Foo.__doc__ = "Some content with a <a href='https://www.python.org/'>link</a>."
```

The ``doc/source/conf.py`` file:

```python
# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = 'linkcheck-bug'
copyright = '2023, Jorge'
author = 'Jorge'
release = '0.1.dev0'

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = ["sphinx.ext.autosummary"]

templates_path = ['_templates']
exclude_patterns = []

# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_theme = 'alabaster'
html_static_path = ['_static']
```

The ``doc/source/index.rst`` file:

```rst
Documentation page
==================

.. currentmodule:: linkcheck_bug

.. autoclass:: linkcheck_bug.Foo
```

Run the following command to reproduce:

```console
sphinx-build -b linkcheck doc/source doc/build/html
```

### Environment Information

```text
Platform:              linux; (Linux-6.2.0-26-generic-x86_64-with-glibc2.35)
Python version:        3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0])
Python implementation: CPython
Sphinx version:        7.1.2
Docutils version:      0.20.1
Jinja2 version:        3.1.2
Pygments version:      2.16.1
```

### Sphinx extensions

```python
["sphinx.ext.autodoc"]
```

**Comment by jorgepiloto** [comment]
As a disclaimer, I know this is not the usual way to declare docstrings. Also, links should follow RST syntax.

**Comment by francoisfreitag** [comment]
Can you explain why the docstring does not follow RST syntax? Using autodoc on a docstring that’s not RST will very likely lead to unexpected results with Sphinx.

**Comment by jorgepiloto** [comment]
Thanks for your reply, @francoisfreitag.

We have an internal project that turned out to have links formatted in plain HTML. It was not until we introduced the usage of the linkcheck tool that we realized this situation.

**Comment by francoisfreitag** [comment]
Thanks! It looks to me that the issue comes from HTML being included in a docstring that’s `.. autoclass::`ed, which does not look like an issue with Sphinx. `.. autoclass::` expects RST, and that shouldn’t change.

Depending on the use case, maybe you could add RST markup around the HTML, something like
```rst
.. code-block:: html

   <h1>Awesome</h1>
````

Otherwise, maybe not `..autoclass::` the docstring?

**Comment by jayaddison** [comment]
@jorgepiloto out of interest, does [`sphinx-lint`](https://github.com/sphinx-contrib/sphinx-lint) detect any problems with these HTML docstrings in your codebase?

**Comment by picnixz** [comment]
Since the OP hasn't replied for a while, I am closing this issue. I personally am against allowing arbitrary HTML in a docstring assumed to contain RST contents only and would suggest transforming HTML links into inline RST links.

However, you could suggest a transformation similar to Napoleon -> RST which would instead do HTML pieces -> RST pieces. For instance, you could create an `autodoc-process-docstring` handler transforming HTML snippets into RST ones.
