### ISSUE TITLE
`toctree(...)` API changed in Sphinx 7.2

### ISSUE THREAD

**Issue by humitos** [sphinx-doc/sphinx#11607]
### Describe the bug

On Sphinx < 7.2 we were calling `toctree(includehidden=True)` and it was working fine. However, starting on Sphinx 7.2 it expects the `includehidden=` parameter to be a string. This was changed in https://github.com/sphinx-doc/sphinx/commit/6f5a99a05d0f760cebadcb15f55a952fcff02bc2

I'm opening this issue mainly to ask if this change was on purpose or was a mistake? What's the approach we should follow here? There are other attributes, like `titles_only=` and `collapse=` where we are passing boolean as well and that made me doubt about this.

### How to Reproduce

I found this issue when running tests for `sphinx_rtd_theme` while fixing another internal API change at https://github.com/readthedocs/sphinx_rtd_theme/pull/1503

### Environment Information

```text
Python 3.10
Sphinx 7.2.0
```

**Comment by AA-Turner** [comment]
This was inadvertent, yes. Will include in Sphinx 7.2.2.

**Comment by AA-Turner** [comment]
See also https://github.com/scikit-hep/pyhf/issues/2297

**Comment by AA-Turner** [comment]
[Sphinx 7.2.2](https://pypi.org/project/Sphinx/7.2.2/) has been released.

A
