### ISSUE TITLE
search does not work on the documentation website

### ISSUE THREAD

**Issue by mattip** [sphinx-doc/sphinx#11606]
### Describe the bug

This query does not return any answers https://www.sphinx-doc.org/en/master/search.html?q=sphinx

### How to Reproduce

Go to https://www.sphinx-doc.org/en/master/search.html and try to search for something

### Environment Information

```text
Any browser
```

**Comment by mattip** [comment]
Ahh, sorry. Could you change the title of that issue to reflect that this is a duplicate? I will close it, hope you find the problem soon.

**Comment by picnixz** [comment]
Ah no, keep it open actually. Because the other title is actually another issue (it's just a comment).

**Comment by mattip** [comment]
That was quick, thanks!
