### ISSUE TITLE
Don't add ANSI colour codes to Sphinx -w warnings file

### ISSUE THREAD

**Issue by hugovk** [sphinx-doc/sphinx#11617]
### Describe the bug

If the terminal supports colour, Sphinx outputs in colour. This is good, it improves readability.

But if outputting to a file, it also adds ANSI colour codes, where is shouldn't.

### How to Reproduce

`index.rst` with an error, in this case, a typo in the role:
```rst
:peep:`8`
```

And an empty `conf.py` will do.

1. Build with warnings and output to a file: `sphinx-build -b html . _build -n -w sphinx-warnings.txt`

![image](https://github.com/sphinx-doc/sphinx/assets/1324225/448edc41-6d06-43f6-a7e9-aaefcd3acaae)

3. View the file in an editor:

Actual result:

```
[31m/private/tmp/bug-report/index.rst:1: ERROR: Unknown interpreted text role "peep".[39;49;00m
```

Because Sphinx is correctly detecting my terminal can do colour, it's correctly adding ANSI colour codes to the terminal output.

But it's also incorrectly adding them to the text file. 

Expected result:

Colour in the terminal but no ANSI colour codes in the text file:

```
/private/tmp/bug-report/index.rst:1: ERROR: Unknown interpreted text role "peep".
```

### Environment Information

```text
Platform:              darwin; (macOS-13.5-arm64-arm-64bit)
Python version:        3.11.4 (v3.11.4:d2340ef257, Jun  6 2023, 19:15:51) [Clang 13.0.0 (clang-1300.0.29.30)])
Python implementation: CPython
Sphinx version:        7.2.2
Docutils version:      0.20.1
Jinja2 version:        3.1.2
Pygments version:      2.16.1
```

### Sphinx extensions

```python
None.
```

**Comment by picnixz** [comment]
Mmh sure. I think it's a reasonable feature. I'll work on it tomorrow (I don't think it'll need a lot of sork since it's just stripping ANSI control sequences).

**Comment by hugovk** [comment]
Thank you!

Personally I wouldn't bother with a flag unless there's some stated need for it, but no strong opinion as long as the default is off :)
