### ISSUE TITLE
Jinja template variables are empty when subclassing "Exception"

### ISSUE THREAD

**Issue by Dragonwilds** [sphinx-doc/sphinx#11616]
### Describe the bug

The template variables are all empty whenever you subclass the "Exception" class in Python. However, the methods can be displayed by using the directive **:members:** but if you want to manually loop though all members with the **methods** variable and use **.. automethod::** instead, it doesn't work.

### Python

```python
class MyClass:
    attribute: int 

    def __init__(self):
        """Docstring"""
        ...

    def method(self):
        """Docstring"""
        ...

class MyException(Exception):
    attribute: int 
    
    def __init__(self):
        """Docstring"""
        ...
        
    def method(self):
        """Docstring"""
        ...
```

### Index (index.rst)

```jinja
=====
index
=====

.. autosummary::
    :toctree: stubs
    :template: class.rst

    MyClass
    MyException
```
    
### Template (class.rst)

```jinja
{{ methods }}
{{ attributes }}

.. autoexception:: {{ fullname }}

    {% block methods %}
    {% if methods %}
    
    .. rubric:: Methods
    
    {% for item in methods %}
        ~{{ fullname }}.{{ item }}
    {%- endfor%}   
    {% endif%}   
    {% endblock%}   
```

### Environment Information

```text
4.4.0
```

### Sphinx extensions

```python
["sphinx.ext.autodoc", "sphinx.ext.autodoc.typehints", "sphinx.ext.autosummary"]
```

**Comment by Warcaith** [comment]
Hmm, I found this at `(https://github.com/sphinx-doc/sphinx/tree/ed84d63e6f2c4fd43b97fc43ee8be4156a13af9e/doc/usage/extensions)
[autosummary.rst]`:

```python
elif doc.objtype == 'class':
    ns['members'] = dir(obj)
```

Does anyone know why the members are not included when the `objtype` is an exception?

**Comment by picnixz** [comment]
Ah it's probably because the documenter is not the correct one (iirc there's also an ExceptionDocumenter whose object type is maybe 'exception' but I'm not sure). I'll have a look by the end of the week.

**Comment by picnixz** [comment]
Actually, I didn't see but why is your template with `autoexception` and not `autoclass` ?

Note that `autoexception` should only be used for exceptions and not for arbitrary classes. Also, can you tell me what you want to show in MyClass and in MyException exactly?

**Comment by picnixz** [comment]
I am closing the issue because I think you misused `autoexception` instead of `autoclass`. If you want to use `autoexception`, I think we should have documented that `autosummary` does not assume the members to be exposed.  

Feel free to re-open if you want to argue about this or if you want to turn your report into a feature request. I however think that exception classes should not expose methods if they are documented using `autoexception` by `autosummary`.

**Comment by picnixz** [comment]
@AA-Turner The author of this issue privately asked me to delete this issue as Google Search is linking this issue to his previous username. Would it be possible to do so? (or suggest a way to avoid this issue appearing on Google Search because of the previous username?)
