### ISSUE TITLE
sphinx.search._JavaScriptIndex: non-determinite searchindex.js output

### ISSUE THREAD

**Issue by jayaddison** [sphinx-doc/sphinx#11622]
### Describe the bug

While looking at some recent [Reproducible Build](https://reproducible-builds.org/) test failures, I noticed that one of the remaining [differences](https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/diffoscope-results/quodlibet.html) between builds of [`quodlibet`](https://quodlibet.readthedocs.io/) is due to sorting differences in `searchindex.js`, a file produced to enable client-side content search in web browsers.

Looking at the [relevant code in the `sphinx.search._JavaScriptIndex` class](https://github.com/sphinx-doc/sphinx/blob/c1f2a52d5d97f874d84e4d5421c99a566242af6b/sphinx/search/__init__.py#L150-L173), the code to output the `searchindex.js` content is a fairly straightforward [Python built-in `json.dumps`](https://docs.python.org/3/library/json.html#json.dumps) call.

The failures mentioned occurred with Sphinx v5.3.0 -- I believe they would occur when using the latest release v7.2.2 also (the [index export code appears unchanged](https://github.com/sphinx-doc/sphinx/blob/ed84d63e6f2c4fd43b97fc43ee8be4156a13af9e/sphinx/search/__init__.py#L155-L178)).

I think that a fix may be as straightforward as sending a `sort_keys=True` argument to the `json.dumps` call.  Writing test coverage to provide varying inputs that sort unequally otherwise could be the tricky part.

cc @lamby 

### How to Reproduce

I do not yet have a local reproducer for this bug, but the differences in output can be observed in the diffoscope results for `quodlibet` on Sphinx v5.3.0 here: https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/diffoscope-results/quodlibet.html

### Environment Information
Since the reproducer case I'm reporting from was a hosted build, I can't easily run the environment-reporting commands, but some relevant details are:

```text
Sphinx: v5.3.0
Operating System: Debian Linux (unstable / trixie)
Documentation-package-under-test: quodlibet v4.5.0
```

### Sphinx extensions

```python
extensions = ['sphinx.ext.autodoc', 'sphinx.ext.extlinks', 'contributors']
```

**Comment by AA-Turner** [comment]
Is ``sort_keys=True`` recursive? I.e. would it sort the list under ``alltitles``, which isn't top level?

**Comment by jayaddison** [comment]
> Is `sort_keys=True` recursive? I.e. would it sort the list under `alltitles`, which isn't top level?

I believe it is, yep.  It won't sort list/array elements, so if we have variance in those, then it won't help - but I _think_ that the problem here is mostly, if not entirely, related to dictionary keys.

**Comment by picnixz** [comment]
If you are interested in solving this issue, I think it would also be good to study #11578 at the same time.

**Comment by jayaddison** [comment]
Thanks @picnixz - yep, I'd like to solve this, although am feeling quite slow at the moment.  Reading the linked issue now.

**Comment by pietroalbini** [comment]
We're encountering this in our project too, where we need full reproducibility to digitally sign the output of Sphinx.

@jayaddison are you still intending to work on this? Otherwise I can open a PR later today or tomorrow fixing the issue (I don't want to step on your toes here if you already have a work in progress branch :slightly_smiling_face:).

**Comment by jayaddison** [comment]
Hi @pietroalbini! - thanks for asking, and nope, I haven't started on this (other than to read the code), so please go ahead if you have time :+1:

**Comment by pietroalbini** [comment]
Opened https://github.com/sphinx-doc/sphinx/pull/11665 with the fix to this.

**Comment by jayaddison** [comment]
Thanks @pietroalbini @AA-Turner!  I'll suggest a version-bump to the folks at `quodlibet` after this has been in place for a release and some bake-in time.
