### ISSUE TITLE
``BuildEnvironment.docname`` can now be `None`

### ISSUE THREAD

**Issue by AA-Turner** [sphinx-doc/sphinx#11620]
> It seems that `BuildEnvironment.docname` can now be `None`:

https://github.com/sphinx-doc/sphinx/blob/ed84d63e6f2c4fd43b97fc43ee8be4156a13af9e/sphinx/environment/__init__.py#L545

> or at least `env.docname` in `read-source` event can now be `None`:

https://github.com/sphinx-doc/sphinx/blob/da9f8a5c33ad5eeef05dd780f2988f3ff7351ef3/sphinx/io.py#L114

Ref: https://github.com/sphinx-gallery/sphinx-gallery/issues/1175

_Originally posted by @lucyleeow in https://github.com/sphinx-doc/sphinx/issues/11605#issuecomment-1683232145_

**Comment by AA-Turner** [comment]
@lucyleeow thanks for this report, do you have a reproducer for this at all please?

Thanks,
Adam

**Comment by AA-Turner** [comment]
May be related to #10678 & #11510

**Comment by AA-Turner** [comment]
Not a bug in Sphinx, will report upstream (https://github.com/sphinx-gallery/sphinx-gallery/issues/1175)

**Comment by lucyleeow** [comment]
Thank you @AA-Turner for looking into this!

Would it be appropriate to update the docs so `docname` return type is `str` or `None`.? Though I do note that `path2doc` has always had return type str or `None`, so this is not a new change.

**Comment by mgeier** [comment]
I seem to have the same problem in my `sphinx-last-updated-by-git` extension. I can work around it with https://github.com/mgeier/sphinx-last-updated-by-git/pull/59, but I'm not sure if that's the right thing to do.

I think at least the `source-read` docs should be updated to explain in which situations `docname` can be `None`.

**Comment by mgeier** [comment]
I have added a reproducer: #11648

We can continue discussion there.

**Comment by AA-Turner** [comment]
Closing as fixed by #11657.
