### ISSUE TITLE
Linux Kernel: TypeError: object of type 'PosixPath' has no len

### ISSUE THREAD

**Issue by severach** [sphinx-doc/sphinx#11629]
### Describe the bug

Linux Kernel 5.4 to 6.4 `make htmldocs` fail with `TypeError: object of type 'PosixPath' has no len()` and `unsupported operand type(s) for +: 'PosixPath' and 'str'`.

### How to Reproduce

Kernel [5.10](https://aur.archlinux.org/packages/linux-lts510). Disable `make all`.  Build with `make htmldocs`

### Environment Information

```text
Not working: python-sphinx 7.2.2
Working: python-sphinx 7.1.2


Platform:              linux; (Linux-6.1.46-1-lts-x86_64-with-glibc2.38)
Python version:        3.11.3 (main, Jun  5 2023, 09:32:32) [GCC 13.1.1 20230429])
Python implementation: CPython
Sphinx version:        7.2.0
Docutils version:      0.20.1
Jinja2 version:        3.1.2
Pygments version:      2.16.1


$ pacman -Q python-sphinx
python-sphinx v7.1.1.r11.g49d8304-1
```

### Additional context

Offending commit is 49d830467098cc149390bc8349c19b7501e0920f

Suspiciously similar to #11618.

**Comment by AA-Turner** [comment]
Are you able to run with the `-T` option enabled please?

A

**Comment by AA-Turner** [comment]
Please test with [Sphinx 7.2.3](https://pypi.org/project/Sphinx/7.2.3/), which should fix this issue.

A

**Comment by AA-Turner** [comment]
Duplicates #11605

**Comment by severach** [comment]
The kernel compiles with or without my patch on Sphinx 7.2.3 and 7.1.2. The patch eliminates the warnings. Would you say that my patch is good to keep compiles working for current versions and on through the deprecation in 8.x?

**Comment by AA-Turner** [comment]
Yes, that'll work for the forseeable (as it unconditionally coerces ``Path`` to ``str``).

I'd consider the below, though, assuming the Kernel's documentation requires Python 3.6 or later:

```patch
diff -ru a/Documentation/sphinx/kerneldoc.py b/Documentation/sphinx/kerneldoc.py
--- a/Documentation/sphinx/kerneldoc.py 2023-08-16 12:21:03.000000000 -0400
+++ b/Documentation/sphinx/kerneldoc.py 2023-08-22 10:54:28.646583489 -0400
@@ -148,7 +148,7 @@
                     lineoffset = int(match.group(1)) - 1
                     # we must eat our comments since the upset the markup
                 else:
-                    doc = env.srcdir + "/" + env.docname + ":" + str(self.lineno)
+                    doc = f"{env.srcdir}/{env.docname}:{self.lineno}"
                     result.append(line, doc + ": " + filename, lineoffset)
                     lineoffset += 1
```

Technically one ought use [``os.fspath()``](https://docs.python.org/3/library/os.html#os.fspath) instead of ``str``, but as it happens ``pathlib.Path.__fspath__()`` just calls ``str`` internally.

A
