### ISSUE TITLE
Who to contact for security issues

### ISSUE THREAD

**Issue by psmoros** [sphinx-doc/sphinx#11623]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@u32i) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by AA-Turner** [comment]
Hi,

Are you able to use the reporting field via https://github.com/sphinx-doc/sphinx/security/advisories/new?

A

**Comment by AA-Turner** [comment]
@psmoros please may you confirm you've seen the above? I haven't seen a new security issue created nor received an email.

A

**Comment by psmoros** [comment]
Sent @AA-Turner
