### ISSUE TITLE
The NEP 29 Python version support policy breaks projects

### ISSUE THREAD

**Issue by return42** [sphinx-doc/sphinx#11621]
### Describe the bug

The Python version support policy [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html#support-table) (superseded by [SPEC 0](https://scientific-python.org/specs/spec-0000/) ) and introduced in Sphinx by PR

- https://github.com/sphinx-doc/sphinx/pull/10921

breaks with python projects following the ["Python Release Cycle"](https://devguide.python.org/versions/) ... for no reasons / at least it is not clear why the motivation of scientific applications should apply to all projects using Sphinx-doc. 

### How to Reproduce

Build your python project on a python 3.8 (build host) / by example build process in a non scientific application:

- https://github.com/searxng/searxng/pull/2658

### Environment Information

Python 3.8 / [EOL 2024-10](https://devguide.python.org/versions/#supported-versions)

**Comment by AA-Turner** [comment]
I don't consider this a valid bug; documentation is a development activity and thus can be on a more restricted set of Python versions than your library might support. To use the *status of Python versions* argument, we would be justified in only supporting active bugfix releases of Python, which would be 3.11.

A

**Comment by return42** [comment]
> I don't consider this a valid bug;

Correct, this is not a bug, it is a change request.

> Note also our policy is inspired by NEP 29, and we do not consider ourselves bound by it, or any superseeding standards.

Correct, but what is the motivation behind? / Why not supporting Python versions until EOL .. like most of the packages in the Python eco system do / and most LTS do.

Are there any known issues with Sphinx 7.x python 3.8?

**Comment by AA-Turner** [comment]
> what is the motivation behind?

Making maintenance easier. It means we can use newer features (e.g. subscriptable generics, str.removeprefix), and there is one less version of Python to test.

A
