### ISSUE TITLE
plantuml with sphinx

### ISSUE THREAD

**Issue by Gowtham-kumar-reddy-Yerasi** [sphinx-doc/sphinx#11630]
### Describe the bug

Iam trying to integrate plantuml with sphinx and installed graphviz version 2.49 and plantuml plantuml-jar-mit-1.2023.7.zip .I had mentioned all the extensions and run as the administrator too but i could constantly face this problem as mentioned below:                writing output... 
building [html]: targets for 3 source files that are out of date
updating environment: [new config] 3 added, 0 changed, 0 removed
reading sources... [100%] modules
F:\sphinx\mydocs\index.rst:21: WARNING: Bullet list ends without a blank line; unexpected unindent.
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [ 33%] example
Exception occurred:
  File "D:\Users\V-Gowtham.Reddy\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1493, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] Access is denied
The full traceback has been saved in D:\Users\V-Gowtham.Reddy\AppData\Local\Temp\sphinx-err-kvjw8yih.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Makefile:20: recipe for target 'html' failed
make: *** [html] Error 2

log is as attached below iam not sure why iam unable to generate the uml with sphinx 
[sphinx_log.txt](https://github.com/sphinx-doc/sphinx/files/12409418/sphinx_log.txt)

### How to Reproduce

Normal generation with writing basic uml code in the .rst file to generate uml and adding plantuml extensions.Post which make html would be creating issue

### Environment Information

```text
installed graphviz as per the sw mentioned above and did  pip install sphinx sphinxcontrib-plantuml
```

### Sphinx extensions

```python
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.napoleon',
    'sphinx.ext.viewcode',
    'sphinxcontrib.plantuml',]

templates_path = ['_templates']
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']


# Configure PlantUML settings
plantuml = 'F:\pantuml\new_version\plantuml.jar'
```

### Additional context

i provided everything

**Comment by picnixz** [comment]
It appears that there are some problems when invoking the command itself so it's better if you report this on the repository for `sphinxcontrib-plantuml`.
