### ISSUE TITLE
Exposing more than just `sphinx-build` to `python -m sphinx`

### ISSUE THREAD

**Issue by jamesbraza** [sphinx-doc/sphinx#11656]
**Is your feature request related to a problem? Please describe.**

Running `python -m sphinx --help`, I see it's an alias for `sphinx-build`.

It would be cool if this was an entrypoint to other commands, like `sphinx-apidoc`.

**Describe the solution you'd like**

A more generalized console entrypoint that supports other commands:

```bash
python -m sphinx --help
# Tells about build, apidoc, etc.
python -m sphinx build ...
python -m sphinx apidoc ...
```

**Describe alternatives you've considered**

A workaround is directly invoking the relevant modules as listed [here](https://github.com/sphinx-doc/sphinx/blob/master/pyproject.toml#L105):

```bash
python -m sphinx.cmd.build ...
python -m sphinx.ext.apidoc ...
```

**Comment by AA-Turner** [comment]
See #5618, #6938; #10877 -- this is absolutely a goal, but mainly stuck on not having enough time. I did add ``-m sphinx build`` in 7.2 as preparation for this, though.

A

**Comment by jamesbraza** [comment]
I was sure this had been already requested, but my searching didn't yield any duplicate issues.  Thanks for linking them!  And your work with Sphinx is appreciated!

Feel free to close this out as a duplicate if desired 👌.
