### ISSUE TITLE
Unhelpful error message when theme.conf is missing

### ISSUE THREAD

**Issue by vsajip** [sphinx-doc/sphinx#11668]
### Describe the bug

If the `theme.conf` file is missing, the code here:
https://github.com/sphinx-doc/sphinx/blob/fcc38997f1d9b728bb4ffc64fc362c7763a4ee25/sphinx/theming.py#L72
creates an empty configuration and fails a few lines later at
https://github.com/sphinx-doc/sphinx/blob/fcc38997f1d9b728bb4ffc64fc362c7763a4ee25/sphinx/theming.py#L77
because of course there's no `[theme]` section, as the file doesn't exist!

It would be more helpful to raise an error saying that the `theme.conf` file is missing.

### How to Reproduce

Just remove `theme.conf ` from a theme and try to build some documentation with that theme.

### Environment Information

```text
Platform:              linux; (Linux-4.15.0-213-generic-x86_64-with-glibc2.27)
Python version:        3.10.8 (main, Nov 24 2022, 07:33:30) [GCC 7.5.0])
Python implementation: CPython
Sphinx version:        7.2.5
Docutils version:      0.20.1
Jinja2 version:        3.1.2
Pygments version:      2.16.1
```

### Sphinx extensions

```python
None
```

**Comment by picnixz** [comment]
PR is welcomed. 

You can first check the existence of the file and raise a warning accordingly. (The current check on the 'theme' setting should still be done)

I'll bave a look at it upon my return (late September).
