### ISSUE TITLE
`suppress_warnings` category for custom extension warnings

### ISSUE THREAD

**Issue by mroeschke** [sphinx-doc/sphinx#11669]
**Is your feature request related to a problem? Please describe.**
For a custom extension that is not defined as parallel safe e.g.

```python
def setup(app):
    app.add_directive("contributors", ContributorsDirective)

    return {"version": "0.1", "parallel_read_safe": False, "parallel_write_safe": False}
```

When running `sphinx build` in parallel mode, naturally, warnings would be issued

```bash
2023-09-01T00:15:49.6100801Z WARNING: the contributors extension is not safe for parallel reading
2023-09-01T00:15:49.6102239Z WARNING: doing serial read
2023-09-01T00:15:49.6151064Z looking for now-outdated files... none found
2023-09-01T00:15:52.1637560Z pickling environment... done
2023-09-01T00:15:52.1646822Z checking consistency... done
2023-09-01T00:15:52.1648662Z WARNING: the contributors extension is not safe for parallel writing
2023-09-01T00:15:52.1649791Z WARNING: doing serial write
```

It would be great to ignore these warnings especially when running with `-W`

**Describe the solution you'd like**
A new `suppress_warnings` category to suppress these types of warnings.

**Describe alternatives you've considered**
Not sure if there's an alternative way to ignore these errors

**Additional context**

- [e.g. URL or Ticket]

**Comment by picnixz** [comment]
PR is welcomed !

Otherwise I'll have a look upon my return. Best way to do it is to add a type/subtype to the warning and suppress it in conf.py afterwards.

**Comment by jdillard** [comment]
This partially relates to https://github.com/sphinx-doc/sphinx/issues/11003 I opened a while back, where I suggested:

> 2. `ext.{extension_name}` (`type='ext', subtype=ext.name`) for [L1279](https://github.com/sphinx-doc/sphinx/blob/cd3f2e435000835dd98a11497440bc16a79ec31c/sphinx/application.py#L1279) and [L1283](https://github.com/sphinx-doc/sphinx/blob/cd3f2e435000835dd98a11497440bc16a79ec31c/sphinx/application.py#L1283). If there are other places that throw warnings using the extension's name, this convention could be used there as well. Being able to supress warnings for an extension that are thrown outside the extension's code seems useful.

I wonder if a type/subtype isn't set, and the warning is thrown by an extension a `type='ext', subtype=ext.name` could be used, otherwise use the type/substype set by the extension.

**Comment by picnixz** [comment]
Oh thank you for catching this. I will close this one then and keep the other!
