### ISSUE TITLE
sphinx JS search is somehow broken / configuration changed in 7.2, please tell me where "undefined" is coming from 

### ISSUE THREAD

**Issue by zzzeek** [sphinx-doc/sphinx#11686]
### Describe the bug

SQLAlchemy uses a custom theme and sphinx 7.2 seems to have changed something somewhere, I can't find where, but my search results are coming out with all the file extensions as "undefined", note link in the browser toolbar:

![image](https://github.com/sphinx-doc/sphinx/assets/128223/ca6e1238-965d-44ce-a2b2-3e15ac66353f)

I apologize for not tracking this down, which if I dont hear from folks here I'll have to do and also revert sphinx on my site which will take me all day.  If I can just get a clue what changed in searchindex.js that suddenly it doesnt know the file extensions (obviously it works fine in my other sites that use built-in themes) that would be super helpful, thanks!

### How to Reproduce

go to https://docs.sqlalchemy.org/en/20/

search for any term, like "relationship"

links all stuffed with "undefined"

### Environment Information

```text
$ python -m sphinx --bug-report
Please paste all output below into the bug report template



Platform:              linux; (Linux-6.4.7-200.fc38.x86_64-x86_64-with-glibc2.37)
Python version:        3.11.4 (main, Jun  7 2023, 00:00:00) [GCC 13.1.1 20230511 (Red Hat 13.1.1-2)])
Python implementation: CPython
Sphinx version:        7.2.6
Docutils version:      0.20.1
Jinja2 version:        3.1.2
Pygments version:      2.15.1
```

**Comment by picnixz** [comment]
I think the culprit commit may be https://github.com/sphinx-doc/sphinx/commit/8e730ae303ae686705ea12f44ef11da926a87cf5 (see https://github.com/sphinx-doc/sphinx/issues/11608#issuecomment-1684410476).

**Comment by zzzeek** [comment]
yes it's that commit, as well as a957d6f7108f2ada9f5c93 , and ultimately DOCUMENTATION_OPTIONS is no longer a block inside the layout file.   

our layout still has this form and I think this is the problem:

```
<script type="text/javascript">
      var DOCUMENTATION_OPTIONS = {
          URL_ROOT:    './',
          VERSION:     '2.0.21',
          COLLAPSE_MODINDEX: false,
          FILE_SUFFIX: '.html'
      };
    </script>

   // this is not working because we have a block above with the variable locally
    <script type="text/javascript" id="documentation_options" data-url_root="./" src="[_static/documentation_options.js](view-source:https://docs.sqlalchemy.org/en/20/_static/documentation_options.js)"></script>


    <script type="text/javascript" src="[_static/init.js](view-source:https://docs.sqlalchemy.org/en/20/_static/init.js)"></script>
```

i think this is the problem, will close this momentarily
