### ISSUE TITLE
Differences between sphinx-build -b and -M are not documented

### ISSUE THREAD

**Issue by guyer** [sphinx-doc/sphinx#11690]
> This isn't a bug, but a different API. See the [docs for make-mode](https://www.sphinx-doc.org/en/master/man/sphinx-build.html#cmdoption-sphinx-build-M).

_Originally posted by @AA-Turner in https://github.com/sphinx-doc/sphinx/issues/10422#issuecomment-1118856482_

The documentation for `-M` at that link doesn't say anything about the differences in directories that were at issue in #10422 (and which have just consumed several hours of my debugging time).

**Comment by AA-Turner** [comment]
Hi Jonathan, 

I think you've just posted one of my comments as an issue -- please may you elaborate?

Thanks,
Adam

**Comment by guyer** [comment]
Editing now. GitHub interface for referencing other issues is cumbersome.

**Comment by guyer** [comment]
@AA-Turner, please see edited issue statement

**Comment by AA-Turner** [comment]
Thanks Jonathan. Do you have any suggestions for the improvement -- what would have been useful to you / saved you the time?

As an initial draft, how about:

>    The default output directory locations when using make-mode
>   differ from the defaults when using `-b`.
>
>   * doctrees are saved to ``<outputdir>/doctrees``
>   * output files are saved to ``<outputdir>/<builder name>``

A

**Comment by guyer** [comment]
I think that would've done it for me, thanks.

This came up for me because I was invoking sphinx in a GH Action, I couldn't easily see that the content was going into `_build`, instead of `_build/html`. All the other cases I'd tried worked fine, but a user supplied a Makefile using `-b` instead of `-M` and, when I looked at the documentation, it implied that shouldn't make a difference.
