### ISSUE TITLE
HTML search should set noindex

### ISSUE THREAD

**Issue by AA-Turner** [sphinx-doc/sphinx#11697]
``search.html`` should set the ``<meta name="robots" content="noindex">`` tag.

* xref: https://github.com/python/docsbuild-scripts/issues/53

A

**Comment by hugovk** [comment]
Another search tip, there's also a new `<search>` element:

https://webkit.org/blog/14445/webkit-features-in-safari-17-0/

Perhaps we can replace this `<div>`? 

```html
<div id="searchbox" style="display: none" role="search">
```

The article mentions the ARIA `role="search"` should be kept until there's wider browser support.

**Comment by AA-Turner** [comment]
It seems [very new](https://caniuse.com/mdn-html_elements_search). However, From Safari's blog post:

> We are excited to be the first browser to ship this new <search> element, now supported in Safari 17.0.
>
> ...
>
> Browsers without [support for the search element](https://caniuse.com/mdn-html_elements_search) will recognize there is an element present, and they will recognize any attributes it has — including roles, IDs, and classes. It will simply behave like a generic element, as if it were a <div>. Because of this, we recommend you include an ARIA search role on the <search> element for now. By using <search role="search">, you will ensure every user has the intended experience. And in the future, when all browsers have support, you can drop the ARIA search role.
>
> In the meantime, you can start using <search> today with confidence, long before a significant percent of your audience use browsers with support.

So it seems that even though only one browser supports the element, we can start using it, and nothing will break.

A

**Comment by jdillard** [comment]
@hugovk might be best to create a new issue for the search tag https://github.com/sphinx-doc/sphinx/issues/11697#issuecomment-1740678777? Unless it gets added to https://github.com/sphinx-doc/sphinx/pull/11700, this issue is likely to be closed and could end up overlooked.

**Comment by jayaddison** [comment]
For transparency: yep, I'm not currently planning to add support for the HTML `search` element in #11700 (could do, although I'd probably tend to wait until the `caniuse` stats increase)

**Comment by hugovk** [comment]
Sure, new issue created at https://github.com/sphinx-doc/sphinx/issues/11701. Thanks!
