### ISSUE TITLE
Extention error possibly due to matplotlib update to 3.8

### ISSUE THREAD

**Issue by NIkhilgKrish** [sphinx-doc/sphinx#11718]
### Describe the bug

On trying to use sphinx to locally generate docs received the following error
`Could not import extension sphinxext.opengraph (exception: cannot import name 'pyplot' from 'matplotlib' (unknown location))`

Managed to work around this error by downgrading matplotlib to 3.7

### How to Reproduce

The instructions would be as follows:

git clone git@github.com:nilearn/nilearn.git
cd nilearn
pip install -e '.[dev]'
pip install '.[doc]'
cd doc
python3 -m sphinx -b html -d _build/doctrees . _build/html

Additional documentations for any further help:  https://nilearn.github.io/stable/development.html#building-documentation

P.S: Sry for the clone method. Couldn't upload the index.rst here because that file type is not supported

### Environment Information

```text
Sphinx version = 7.1.2

Bug report is below:

Platform:              win32; (Windows-10-10.0.22621-SP0)
Python version:        3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)])
Python implementation: CPython
Sphinx version:        7.1.2
Docutils version:      0.20.1
Jinja2 version:        3.1.2
Pygments version:      2.16.1
```

**Comment by AA-Turner** [comment]
Please report to https://github.com/wpilibsuite/sphinxext-opengraph

A
