### ISSUE TITLE
When using Sphinx, letters in brackets and abbreviated names are probably formatted as enumerations.

### ISSUE THREAD

**Issue by Mauntenbeiker** [sphinx-doc/sphinx#11727]
### Describe the bug

I have created a table whose cells contain individual letters in brackets, which should also be displayed in exactly the same way. When building the html file, I notice that it is not displayed this way, but instead the brackets are omitted and a dot is set. In addition, the letter is moved centrally in the cell. When I build a PDF, the brackets are retained, but the letter is still moved to the center of the cell.

The same happens when I write an abbreviated name in the form A. Lastname in the cell. The name is moved to the middle of the cell. But here the behavior in the html and the PDF is identical.

The same behavior can be observed if you write the letter in brackets and the abbreviated name outside the table.

I suspect that the contents of those cells are formatted as a enumeration. Is this intended? Especially with the abbreviated name it doesn't seem to make sense to me.

### How to Reproduce

I created a small example tthat reproduces the error here:
https://github.com/Mauntenbeiker/table_bug.git

### Environment Information

```text
Platform:              win32; (Windows-10-10.0.19044-SP0)
Python version:        3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)])
Python implementation: CPython
Sphinx version:        7.2.6
Docutils version:      0.18.1
Jinja2 version:        3.1.2
Pygments version:      2.16.1
```

**Comment by jfbu** [comment]
have you tried escaping the brackets?
