### ISSUE TITLE
sphinx-build can't find `index.rst`, even though it exists -- `root file not found`

### ISSUE THREAD

**Issue by ralittl** [sphinx-doc/sphinx#11722]
### Describe the bug

Issue summary: **sphinx-build cannot correctly locate a root doc file.**

Ran: 

```bash
$ sphinx-build -b html -c sphinx-docs/ morpheus/ sphinx-docs/
```

Got this error: 

```
Sphinx error:
root file /home/dev/Morpheus/morpheus/index.rst not found
```

However, if I run:

```bash
$ file /home/dev/Morpheus/morpheus/index.rst
```

I get this output, so the file clearly does exist:

```
/home/dev/Morpheus/morpheus/index.rst: ASCII text
```

The `sphinx-build` tool is incorrectly claiming it doesn't exist.

### How to Reproduce

Run `sphinx-build`, with a SOURCEDIR and OUTPUTDIR in a different directory.

### Environment Information

```text
Platform:              linux; (Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.28)
Python version:        3.11.2 (main, Jun  6 2023, 07:39:01) [GCC 8.5.0 20210514 (Red Hat 8.5.0-18)])
Python implementation: CPython
Sphinx version:        7.2.6
Docutils version:      0.20.1
Jinja2 version:        3.1.2
Pygments version:      2.16.1
```

### Additional context

Running in a docker container, on Windows 10.

**Comment by picnixz** [comment]
Closing since the OP didn't reply.

**Comment by Jake-Carter** [comment]
This can occur if you've set `include_patterns` in your configuration file, but `index.rst` is not in the pattern.

i.e.
```python
#conf.py
include_patterns = []
# ...
```

Tripped me up a little too...  might be worth searching for `root_doc` independently of `include_patterns`?

**Comment by AA-Turner** [comment]
Thanks @Jake-Carter, good point -- I've opened a new tracking issue.

A

**Comment by LocutusGrax** [comment]
I have a simillar error. Running in docker image in a pipeline, the root index.rst is copied from an artifact to workspace. Shpinx cant find it, its there.  I have done 'ls' on it, its there, Done a 'cat' on it, its there. Its got correct permissions for Sphinx-build. My root_doc = 'index', include_patterns = ['development/test_component/**']

The error messsge isnt correct: root file /***/***/***/***/pipeline/document_templates/full_development/component/index.rst not found

Will try @Jake-Carter solution
