### ISSUE TITLE
MathJax blocked by browser security policy

### ISSUE THREAD

**Issue by thorstenhater** [sphinx-doc/sphinx#11729]
### Describe the bug

Hi,

we are using sphinx via readthedocs and observed that recently embedded math roles stopped rendering,
both a for local and hosted (=rtd) version of our docs. Example here:

https://docs.arbor-sim.org/en/latest/concepts/lif_cell.html

Turning on the dev console on Firefox and Chromium reveals errors like this:
<img width="1508" alt="Screenshot 2023-10-19 at 12 10 18" src="https://github.com/sphinx-doc/sphinx/assets/24411438/bed87f63-f3c1-44d2-a999-66fd669c4518">

Searching for the error online didn't turn up useful information and I am not an expert on web tech,
so I came here to ask.

### How to Reproduce

conf.py
```py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import sys
import os

# Add /scripts to path. Used for Furo theme and to generate images
this_path = os.path.split(os.path.abspath(__file__))[0]
script_path = this_path + "/scripts"
sys.path.append(script_path)

html_static_path = ["static"]
html_css_files = ["htmldiag.css"]
html_js_files = ["domarrow.js"]


def setup(app):
    app.add_object_type("generic", "gen", "pair: %s; generic")
    app.add_object_type("label", "lab", "pair: %s; label")
    app.add_js_file("latest-warning.js")

extensions = [
    "sphinx.ext.intersphinx",
    "sphinx.ext.autodoc",
    "sphinx.ext.todo",
    "sphinx.ext.mathjax",
    "divio_docs_theme",
]
source_suffix = ".rst"
master_doc = "index"
```
this is most of our config and serves mostly to demonstrate that we do not anything fancy.
Full version:
https://github.com/arbor-sim/arbor/blob/master/doc/conf.py

### Environment Information

```text
sphinx 7.2.4 is used both as hosted (rtd) and local versions, both exhibit the problem.
```

### Sphinx extensions

```python
sphinx.ext.mathjax
```

### Additional context

- Firefox & Chromiun show the problem.

**Comment by picnixz** [comment]
Please upgrade to 7.2.6. Also, we changed the way how CSS and JS files are represented, so your theme is likely not up-to-date (as you can see, the URL is actually `_Cascading...` which is actually `str(some_object)` so you are likely rendering the object instead of the url). 

See #11608 and the related issues.
