### ISSUE TITLE
sphinx.ext.extlinks: option for literal formatting?

### ISSUE THREAD

**Issue by hugovk** [sphinx-doc/sphinx#11745]
**Is your feature request related to a problem? Please describe.**

In the Python devguide, we have an extension to add custom roles that add links.

https://github.com/python/devguide/blob/2e9e657b53830806d202df70cbed3353afcdb5d1/_extensions/custom_roles.py

For example, ``` :cpy-file:`.github/CODEOWNERS` ``` will expand to `https://github.com/python/cpython/blob/main/.github/CODEOWNERS`:

<img width="753" alt="image" src="https://github.com/sphinx-doc/sphinx/assets/1324225/ec8dc772-b7e5-4b29-a111-695bb6ddb3a4">

https://devguide.python.org/core-developers/experts/

This could of course be replaced with `sphinx.ext.extlinks` with this in `conf.py`:

```python
_repo = "https://github.com/python/cpython"
extlinks = {
    "cpy-file": (f"{_repo}/blob/main/%s", "%s"),
    "gh-label": (f"{_repo}/labels/%s", "%s"),
}
```

However, the custom extension output as literal text, and `extlinks` does not apply any formatting and looks like this:

<img width="751" alt="image" src="https://github.com/sphinx-doc/sphinx/assets/1324225/936ddebc-14b9-420a-a57c-6e1c16d09f17">

**Describe the solution you'd like**

Add some sort of option to use literal formatting for `extlinks`.

This sort of thing adds literal formatting. But it would need some sort of option to enable it:

```diff
diff --git a/sphinx/ext/extlinks.py b/sphinx/ext/extlinks.py
index 173df4dde..af79f716d 100644
--- a/sphinx/ext/extlinks.py
+++ b/sphinx/ext/extlinks.py
@@ -106,7 +106,7 @@ def make_link_role(name: str, base_url: str, caption: str) -> RoleFunction:
                 title = full_url
             else:
                 title = caption % part
-        pnode = nodes.reference(title, title, internal=False, refuri=full_url)
+        pnode = nodes.reference(title, '', nodes.literal(rawtext, text), internal=False, refuri=full_url)
         return [pnode], []
     return role
```

**Describe alternatives you've considered**

Keep the extension and custom roles. 

Use CSS?

**Comment by picnixz** [comment]
The easiest way is orobably to add a CSS class but that would require doing it for all themes. I think the options approach is better. Unfortunately I don't have time for that :(

**Comment by AA-Turner** [comment]
I want to do this, with a menu of choices to include bold/italic/literal.

This probably requires changing extlinks to be a dict rather than tuple, though, for readability. The tuple format would be retained but not allow for any formatting or other advanced features.

A

**Comment by SilverRainZ** [comment]
I wrote an [extension](https://github.com/sphinx-notes/comboroles) for composing simple roles (more precisely, it is the TextElement produced after roles run, if @hugovk doesn't mind using a third-party extension, this issue can be implemented without changing `extlink`:

for example, we can compose `literal` and `cpy-file` in conf.py:

```py
extensions.append('sphinxnotes.comboroles')
comboroles_roles = {
    'cpy-file2': ['literal', 'cpy-file'],
}
```

by using ``:cpy-file2:`conf.py`` role we can be pseudo-nodes like:
```
<literal>
    <reference uri="https://github.com/python/cpython/blob/main/conf.py">
      conf.py
```
![image](https://github.com/sphinx-doc/sphinx/assets/8090459/77ddc9a6-0fea-4567-862e-bc4797dd2c21)
![image](https://github.com/sphinx-doc/sphinx/assets/8090459/3db3cc5d-7960-402c-bc97-780e953e9f73)

See https://sphinx.silverrainz.me/comboroles/ for more details.

**Comment by hugovk** [comment]
@SilverRainZ Thanks for mentioning the extension! If this is coming to Sphinx, then it can wait. My initial plan was to use this for the CPython devguide and PEPs repos, which can use extensions. If we wanted to also use it for CPython itself, then it's better to avoid extensions because we need to make sure the docs build without any for downstream redistributors.

**Comment by hugovk** [comment]
> **Describe alternatives you've considered**
> 
> Use CSS?

I'm now thinking this is the best option: it gives theme authors and docs builders the most flexibility to format the extlink in whatever way they want, without being tied to whatever formatting has been implemented in Sphinx.

It's also a very small change to Sphinx (two lines of code + two lines of tests) and requires no backwards compatibility concerns around maintaining both tuples and dicts for config.

More specifically for CPython, if a Linux distributor builds the docs with an older version of Sphinx, it will still build the docs, they just won't get the CSS class and will get the plain formatting, which I'm not worried about.

Please see PR https://github.com/sphinx-doc/sphinx/pull/12319.
