### ISSUE TITLE
Better rendering of Annotated types

### ISSUE THREAD

**Issue by dstansby** [sphinx-doc/sphinx#11773]
**Is your feature request related to a problem? Please describe.**
For classes that have a `__class_getitem__()` method that returns an `Annotated` type, the extra metadata stored on the Annotated object is not rendered in the type hints in sphinx docs.

**Describe the solution you'd like**
Extra metadata is included in rendered type hints.

**Describe alternatives you've considered**

**Additional context**
Minimal example that builds is at https://github.com/dstansby/quantity-typing-docs/tree/c69c2a8c86314ef672d4484072067888c2627ac7 The code and rendered docs are below:
```python
from typing import Annotated

__all__ = ["deg2rad"]

class A:
    def __class_getitem__(cls, t: type):
        return Annotated[cls, t]


def deg2rad(arg: A[str]) -> A[bytes]:
    return A()
```
![Screenshot 2023-11-28 at 13 30 51](https://github.com/sphinx-doc/sphinx/assets/6197628/4f0c7e2c-edc3-4477-9cf9-0e1fede12984)

Note how only the class `A` is shown. Ideally I would like the type hint to read A[str].

Possibly related to https://github.com/sphinx-doc/sphinx/pull/9590

**Comment by Zac-HD** [comment]
Consider the parameter `x: Annotated[int, Ge(0), Lt(10)]` ([using `annotated-types`](https://github.com/annotated-types/annotated-types#annotated-types)).  Rendering this as `x: int[Ge(0), Lt(10)]` would be absurd, so I think we should render `typing.Annotated` types in documentation with `f"Annotated[{stringify_annotation(T)}, {', '.join(repr(x) for x in metadata)}]`.
