### ISSUE TITLE
Add example for ``html_search_scorer``

### ISSUE THREAD

**Issue by JasonGrace2282** [sphinx-doc/sphinx#11783]
It would be nice to have a small example of what a ``scorer.js`` file might look like, that way it would be easier to write our own.

Currently, it is just this:
[https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_search_scorer](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_search_scorer)

**Comment by miketheman** [comment]
I _think_ it's any function that confirms to this kind of shape?
https://github.com/sphinx-doc/sphinx/blob/a8d580075e8608ba49315e136e5310c798edd5d0/sphinx/themes/basic/static/searchtools.js#L17-L47

**Comment by JasonGrace2282** [comment]
Indeed, it is so, but it should be documented somewhere; an end user should not have to search the source code for the answer.

**Comment by AA-Turner** [comment]
Hi Jason,

Would you consider writing an initial draft of what better wording would look like?

Thanks,
Adam

**Comment by JasonGrace2282** [comment]
The default `Scorer` is well commented enough that even just adding the following should be very helpful:
```js
  var Scorer = {
    // Implement the following function to further tweak the score for each result
    // The function takes a result array [docname, title, anchor, descr, score, filename]
    // and returns the new score.
    /*
    score: result => {
      const [docname, title, anchor, descr, score, filename] = result
      return score
    },
    */

    // query matches the full name of an object
    objNameMatch: 11,
    // or matches in the last dotted part of the object name
    objPartialMatch: 6,
    // Additive scores depending on the priority of the object
    objPrio: {
      0: 15, // used to be importantResults
      1: 5, // used to be objectResults
      2: -5, // used to be unimportantResults
    },
    //  Used when the priority is not in the mapping.
    objPrioDefault: 0,

    // query found in title
    title: 15,
    partialTitle: 7,
    // query found in terms
    term: 5,
    partialTerm: 2,
  };
```

**Comment by AA-Turner** [comment]
Done in 587e01177deeaf10b4fbe3f567b99ec083238b7e

A
