### ISSUE TITLE
AttributeError: 'Values' object has no attribute 'link_base'

### ISSUE THREAD

**Issue by pittnerf** [sphinx-doc/sphinx#11798]
### Describe the bug

I have a Django 4.2 project and wish to run Sphinx to generate the docs. When I run:
sphinx-build -b html docs_source/ docs/
I got the following error:

Exception occurred:
  File "C:\Users\user\.conda\envs\Django_4_1_9_Pyhto_3_11_6\Lib\site-packages\django\contrib\admindocs\utils.py", line 113, in _role
    inliner.document.settings.link_base,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Values' object has no attribute 'link_base'
The full traceback has been saved in C:\Users\user\AppData\Local\Temp\sphinx-err-ei20en_i.log, if you want to report the issue to the developers.
[sphinx-err-ei20en_i.log](https://github.com/sphinx-doc/sphinx/files/13693656/sphinx-err-ei20en_i.log)

### How to Reproduce

Install these packages:

Package                       Version
----------------------------- ------------
alabaster                     0.7.12
amqp                          5.2.0
asgiref                       3.5.2
attrs                         23.1.0
Babel                         2.11.0
billiard                      4.1.0
boto3                         1.29.1
botocore                      1.32.1
Brotli                        1.0.9
celery                        5.3.1
certifi                       2023.11.17
cffi                          1.16.0
charset-normalizer            2.0.4
click                         8.1.7
click-didyoumean              0.3.0
click-plugins                 1.1.1
click-repl                    0.2.0
colorama                      0.4.6
coverage                      7.2.2
cryptography                  41.0.7
Django                        4.1.7
django-debug-toolbar          4.2.0
django-postgres-extra         2.0.8
djangorestframework           3.13.1
docutils                      0.18.1
drf-extra-fields              3.7.0
drf-spectacular               0.22.0
et-xmlfile                    1.1.0
filetype                      1.2.0
flake8                        6.1.0
idna                          3.4
imagesize                     1.4.1
importlib-metadata            6.0.0
inflection                    0.5.1
Jinja2                        3.1.2
jmespath                      1.0.1
jsonschema                    4.19.2
jsonschema-specifications     2023.7.1
kombu                         5.3.4
MarkupSafe                    2.1.1
mccabe                        0.7.0
openpyxl                      3.1.2
packaging                     23.1
Pillow                        10.1.0
pip                           23.3.1
prompt-toolkit                3.0.36
psycopg2                      2.9.9
psycopg2-binary               2.9.9
pycodestyle                   2.11.1
pycparser                     2.21
pyflakes                      3.1.0
Pygments                      2.15.1
pyOpenSSL                     23.2.0
PySocks                       1.7.1
python-dateutil               2.8.2
pytz                          2023.3.post1
PyYAML                        6.0.1
redis                         3.5.3
referencing                   0.30.2
requests                      2.31.0
rpds-py                       0.10.6
s3transfer                    0.7.0
setuptools                    68.2.2
six                           1.16.0
snowballstemmer               2.2.0
Sphinx                        7.2.6
sphinx-autodoc-typehints      1.19.2
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.9
sqlparse                      0.4.4
tzdata                        2023.3
uritemplate                   4.1.1
urllib3                       1.26.18
vine                          5.0.0
wcwidth                       0.2.5
wheel                         0.41.2
win-inet-pton                 1.1.0
zipp                          3.11.0

Then try to run in a django project the following command:

sphinx-build -b html docs_source/ docs/

### Environment Information

```text
Platform:              win32; (Windows-10-10.0.19045-SP0)
Python version:        3.11.5 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:26:23) [MSC v.1916 64 bit (AMD64)])
Python implementation: CPython
Sphinx version:        7.2.6
Docutils version:      0.18.1
Jinja2 version:        3.1.2
Pygments version:      2.15.1
```

**Comment by picnixz** [comment]
This issue stems from `site-packages\django\contrib\admindocs\utils.py`, so it's the `django.contrib.admindocs` extension that is probably doing bad things. 

Please report that issue on their repo. Feel free to reopen if they tell you that it's on our side.
