### ISSUE TITLE
Configurable Doctest highlighter

### ISSUE THREAD

**Issue by HolgerPeters** [sphinx-doc/sphinx#11792]
Since #4143 limits the doctest highlighting language is set to `pycon`.  I would like to have an option to set my preferred highlighting, e.g. for documenting Scheme/Lisp/Clojure REPL interactions.

```
>>> (define a 10)
>>> (let ((b 5))
....   (+ a b))
15
```

Would be a perfect use case for the doctest syntax in a Scheme package.

**Comment by picnixz** [comment]
By `doctest`, we probably mean **Python** doctest. So I think we should stick to that (the `doctest` extension is for Python ones I think). If you want to use similar syntax, you need your own extension.
