### ISSUE TITLE
`Config.config_values` are shallow copies

### ISSUE THREAD

**Issue by agoose77** [sphinx-doc/sphinx#11795]
### Describe the bug

I stumbled across a mismatch between the invariants of `sphinx/registry.py::merge_source_suffix` and `sphinx/config/config.py::Config.__init__` whereby `Config.__init__` performs a shallow copy of `Config.config_values` whilst `merge_source_suffix` mutates a value (`source_suffix`). 

My assumption is that we want the values of each config to be deep copies, so the solution is to replace call to the dict method `.copy()` in `sphinx/config/config.py::Config.__init__` with one to the function `copy.deepcopy`.

### How to Reproduce

Define two extensions that invoke `add_source_suffix` with unique suffixes, and execute a Sphinx build from the Python API. 

### Environment Information

```text
Platform:              linux; (Linux-5.19.0-32-generic-x86_64-with-glibc2.35)
Python version:        3.10.4 | packaged by conda-forge | (main, Mar 24 2022, 17:39:04) [GCC 10.3.0])
Python implementation: CPython
Sphinx version:        7.0.0
Docutils version:      0.19
Jinja2 version:        3.1.2
Pygments version:      2.17.2
```

### Sphinx extensions

```python
I identified this with `myst-nb` and `myst-parser`, but I do not recommend using them to try and build a reproducer.
```

### Additional context

This should be fairly easy to identify from only looking at the source code.

**Comment by picnixz** [comment]
Correct me if I'm wrong, but the issue is that the class variable `source_suffix` is

**Comment by picnixz** [comment]
Correct me if I'm wrong but the issue is about the fact that `Config.config_values` is shallowed copied and thus other instances of `Config` will be affected, right?

If so, PR is welcomed. By the way, it'd be good if we are sure that no other part of the code uses that side-effect (but I don't think it's the case).

**Comment by AA-Turner** [comment]
Sphinx 7.3 refactored configuration handling.

A
