### ISSUE TITLE
[DOC] typo in describing-code.rst

### ISSUE THREAD

**Issue by raffaelemancuso** [sphinx-doc/sphinx#11799]
### Describe the bug

In [Including doctests in your documentation](https://www.sphinx-doc.org/en/master/tutorial/describing-code.html#including-doctests-in-your-documentation) tutorial chapter 

> And finally, make **test** reports success!

should be

> And finally, make **doctest** reports success!

### How to Reproduce

See above

### Environment Information

```text
Irrelevant
```

**Comment by electric-coder** [comment]
With emphasis:

> should be

> >    And finally, `make doctest` reports success!

**Comment by picnixz** [comment]
#11428 is addressing it but before merging it we have some organisational things to do. It should be fixed in a few weeks (or so).

**Comment by picnixz** [comment]
Resolved in #11428
