### ISSUE TITLE
Disconnect sidebar and current page TOCs

### ISSUE THREAD

**Issue by dbitouze** [sphinx-doc/sphinx#11805]
For the HTML output of our documentation, we would like to have:

- for the “starting” pages of our directories, a custom content: only a list of some of the children, precisely not the automatic list of all of them, usually obtained by something like: 
  ```rst
  .. toctree::
  :glob:

  *
  ```
- for the corresponding side bar, the full list of the children, precisely what would be obtained by the above code.

Would it be possible? (AFAICS, relying on the :`hidden:` option removes the children from the sidebar.)

**Comment by electric-coder** [comment]
@dbitouze depending on what you want there are several ways but none of them is very flexible.

> Would it be possible?

1. Take a look at the [PyData theme](https://pydata-sphinx-theme.readthedocs.io/en/stable/) it's currently one of the best supported themes and you can customize the front page with a number of boxes. Afterwards if you click on the toctree links you'll see the sidebar showing up and the [depth of the toctrees](https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/navigation.html) can be configured to an extent.

2. If you consider using the popular [RTD theme it has a `navigation_depth` setting](https://sphinx-rtd-theme.readthedocs.io/en/stable/configuring.html#confval-navigation_depth) for the sidebar that can be used together with the [`toctree`'s ](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-toctree) `:maxdepth:` option. Notice however [footnote 1](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#id6) if your planning on using this with LaTeX.

Other than taking advantage of the existing themes you could also make the `:glob:` toctree invisible using CSS to populate the sidebar and display a hand written bullet list of links styling it like a toctree. So again:

> Would it be possible?

Yes, but in most cases you'll want to avoid additional trouble and stay within the functionalities the themes make available.

**Comment by dbitouze** [comment]
@electric-coder

1. `PyData theme` is precisely the theme we are using ([here](https://faq.gutenberg-asso.fr/index.html)). But I must admit that I don't understand what you suggest about it.
2. `RTD theme` is not an option for us.
3. I have a look.

And I won't forget your last advice :wink:

Thanks!

**Comment by electric-coder** [comment]
@dbitouze the docs you linked look extremely good! Can you give an example of one specific page where you want the sidebar and the content to have a layout that's different from its current state? And what exactly you would need to change? (A screenshot with some scribbles would help.)

**Comment by dbitouze** [comment]
> @dbitouze the docs you linked look extremely good!

Thanks!

> Can you give an example of one specific page where you want the sidebar and the content to have a layout that's different from its current state? And what exactly would need to change? (A screenshot with some scribbles would help.)

In fact, thanks to your insights, we manage to obtain what we wanted, e.g. [here](https://faq.gutenberg-asso.fr/3_composition/start.html).

Many thanks again!
