### ISSUE TITLE
Several types, not just TracebackType, has incorrect module

### ISSUE THREAD

**Issue by jakkdl** [sphinx-doc/sphinx#11802]
### Describe the bug

https://github.com/sphinx-doc/sphinx/pull/9015 specifically fixed `types.TracebackType` - but in fact almost all of the classes in `types` have `__module__` set to `builtins`.

So the fix in #9015 should be expanded, in order to support the rest of them.

In particular we've had trouble with `FrameType` in the Trio project, but I don't see any reason not to support all the classes in `types`

```python
import types
for x in dir(types):
     if getattr(getattr(types, x), "__module__", None) == "builtins":
         print(x)
```
gives the following list on python 3.11.6:
```
AsyncGeneratorType
BuiltinFunctionType
BuiltinMethodType
CellType
ClassMethodDescriptorType
CodeType
CoroutineType
EllipsisType
FrameType
FunctionType
GeneratorType
GetSetDescriptorType
LambdaType
MappingProxyType
MemberDescriptorType
MethodDescriptorType
MethodType
MethodWrapperType
ModuleType
NoneType
NotImplementedType
TracebackType
WrapperDescriptorType
```

### How to Reproduce

See https://github.com/sphinx-doc/sphinx/issues/8992 and #8315

### Environment Information

The fix from #9015 is still live on master with no changes since:
https://github.com/sphinx-doc/sphinx/blob/35965903177c6ed9a6afb62ccd33243a746a3fc0/sphinx/util/typing.py#L23-L27

**Comment by picnixz** [comment]
Well, this part of the code has not been touched for a while and people totally forgot about it I think.

PR is welcomed.

**Comment by AA-Turner** [comment]
For future reference, to generate a list of mismatched types:

```python
import sys, importlib
successful = []
modules = sorted(m for m in sys.stdlib_module_names if not m.startswith('_') and '._' not in m)
for m in modules:
    try:
        mod = importlib.import_module(m)
    except:
        pass
    else:
        successful.append(m)
errs = [(m, x, n) for m in successful for x in dir(sys.modules[m]) if not x.startswith('_') and (n:=getattr(getattr(sys.modules[m], x), "__module__", m)) != m and type(getattr(sys.modules[m], x)) is type]
print(errs)
```
