### ISSUE TITLE
Allow control over Enum repr

### ISSUE THREAD

**Issue by rhshadrach** [sphinx-doc/sphinx#11803]
**Is your feature request related to a problem? Please describe.**

From #9272, [this commit](https://github.com/sphinx-doc/sphinx/commit/31ec519d3808617e333794493e0aabc5fe5d4f81) removed any user control over the representation of the Enum in the docs. As a result, what we would like to be represented as `<no_default>` becomes the slightly ugly `_NoDefault.no_default` in the [pandas docs](https://pandas.pydata.org/pandas-docs/version/2.1/reference/api/pandas.DataFrame.groupby.html). 

**Describe the solution you'd like**
Add a check to see if the user is overwriting Enum's repr: `object.__repr__ is Enum.__repr__`. If they are overwriting it, just use the repr as-is.

**Describe alternatives you've considered**

**Additional context**

- [e.g. URL or Ticket]

**Comment by picnixz** [comment]
PR is welcomed. I agree that using a custom ``__repr__`` (if available) is better.
