### ISSUE TITLE
Can't reference token from other productionlist's if its group name contains hypens

### ISSUE THREAD

**Issue by skirpichev** [sphinx-doc/sphinx#11854]
### Describe the bug

BTW, this poses problems only references *inside* of some productionlist directive.  Outside of the production list it's possible to use cross-references like `` :token:`~python-grammar:with_item` ``.

This affects CPython docs, see python/cpython#108184 for a proposed workaround.

### How to Reproduce

```
$ cat index.rst
.. productionlist:: a-foo
   digit: "0".."9"

.. productionlist:: b
   hexdigit: `a-foo:digit` | "a".."f"
```

### Environment Information

```text
Platform:              linux; (Linux-6.1.0-16-amd64-x86_64-with-glibc2.36)
Python version:        3.11.3+ (heads/3.11:9fbb614c4e, Apr 29 2023, 14:18:05) [GCC 10.2.1 20210110])
Python implementation: CPython
Sphinx version:        7.2.6
Docutils version:      0.18.1
Jinja2 version:        3.1.2
Pygments version:      2.15.1
```

**Comment by AA-Turner** [comment]
Fixed in 6ac7cdbb0284228db251a416c52b8816728554a2

A
