### ISSUE TITLE
How do sphinx not read all the source files when building specific files separately?

### ISSUE THREAD

**Issue by huodagu** [sphinx-doc/sphinx#11867]
I know that I can use `sphinx-build source_path build_path filenames` to generate a specific file or files individually.

During the build, I found that instead of reading only these specific files, sphinx read all the files in the source_path directory. Because I had a lot of files in my source directory, the entire build process ended up taking a long time.

I looked at the documentation, and there doesn't seem to be any ability to read only specific files in the build, or maybe I didn't look closely enough.

environment
`sphinx 4.4.0`

What configuration can be used to read only the contents of a specific file but not all the contents of the source file when building a specific file?

If there is no similar configuration, I hope to add such functions in the future, so that users can test and observe the style or appearance of some special files.

**Comment by AA-Turner** [comment]
All files need to be read to determine structure & eg in creating the ToC tree for sidebars. Incremental rebuilds ought be quicker, though.

A

**Comment by huodagu** [comment]
Thanks!
