### ISSUE TITLE
linkcheck builder: add a distinct reporting status code for timeouts

### ISSUE THREAD

**Issue by jayaddison** [sphinx-doc/sphinx#11868]
**Is your feature request related to a problem? Please describe.**
Currently when the `linkcheck` builder encounters a timeout while checking a link, the corresponding link will be reported as `broken`.

This makes it difficult to distinguish between webservers that are slow to respond, as compared to received responses that indicate that a given hyperlink no longer returns useful information.  That distinction could be valuable, for example to help determine whether hyperlink unavailability is due to transient or network-related conditions.

**Describe the solution you'd like**
An additional reporting status for the `linkcheck` builder.  The simplest name for this status would be `timeout`.

**Describe alternatives you've considered**
TODO: are there alternatives approaches that would be an improvement on this?

**Additional context**
Technically the linkcheck builder has (at least) two kinds of timeouts - there's a low-level network socket timeout, which we set to 5 seconds, and there's the per-hyperlink request timeout, relating to the time that the (connected) client will wait for a response from the webserver.

- Opened following discussion in #11853.

**Comment by AA-Turner** [comment]
I think this makes sense.

A
