### ISSUE TITLE
sphinx `maximum_signature_line_length` doesn't work consistently

### ISSUE THREAD

**Issue by s-banach** [sphinx-doc/sphinx#11866]
### Describe the bug

I have several classes with the same function signature:
```python
def transform(self, df: pl.DataFrame, /) -> pl.DataFrame: ...
```

In some of these classes, when sphinx builds the docs, the signature appears on one line:
```
transform(df: DataFrame, /) → DataFrame
```
whereas sometimes it appears split across lines:
```
transform(
df: DataFrame,
/,
) → DataFrame
```

Also asked this on SO, in case it turns out to be user error rather than a bug:
https://stackoverflow.com/questions/77788164/sphinx-maximum-signature-line-length-doesnt-work-consistently.

### How to Reproduce

config.py (minus package names and paths):
```
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.doctest",
    "sphinx.ext.githubpages",
    "numpydoc",
]

templates_path = ["_templates"]
exclude_patterns = []
maximum_signature_line_length = 105

autoclass_content = "both"
numpydoc_show_class_members = False
autosummary_generate = True
default_role = "code"
# autodoc_class_signature = "separated"


# ---- HTML CONFIG
html_theme = "pydata_sphinx_theme"
html_static_path = ["_static"]
html_css_files = ["css/custom.css"]  # relative to html_static_path
html_show_sourcelink = False
```

### Environment Information

```text
Platform:              win32; (Windows-10-10.0.19041-SP0)
Python version:        3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 17:59:51) [MSC v.1935 64 bit (AMD64)])
Python implementation: CPython
Sphinx version:        7.2.6
Docutils version:      0.18.1
Jinja2 version:        3.1.2
Pygments version:      2.17.2
```

**Comment by AA-Turner** [comment]
I don't know what you want to have changed here, as you cite user error in your note. 

Please also provide exemplar source files to reproduce the error.

I'll close for now, but we will re-open following clarification.

A
