### ISSUE TITLE
documentation: refresh the documentation for the linkcheck_timeout configuration setting

### ISSUE THREAD

**Issue by jayaddison** [sphinx-doc/sphinx#11869]
**Is your feature request related to a problem? Please describe.**
The [documentation for `linkcheck_timeout`](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-linkcheck_timeout) could be made clearer, and has drifted from the `linkcheck` implementation that it was written for a decade or so ago.

**Describe the solution you'd like**
Refresh the documentation for the `linkcheck_timeout` config setting.

**Describe alternatives you've considered**
N/A

**Additional context**
It may be worth auditing other `linkcheck` config documentation at the same time and refreshing other information.

- Relates to discussion in #11853.

**Comment by jayaddison** [comment]
(I'll attempt this soon, possibly borrowing from a reply I added in #11853)

**Comment by AA-Turner** [comment]
Thanks James!

A
