### ISSUE TITLE
HTMLHELP Relative URL strings must not have a query component

### ISSUE THREAD

**Issue by mkay-sh** [sphinx-doc/sphinx#11889]
### Describe the bug

With the implementation of #11415 checksums are added to css file links in the html output. But in the htmlhelp output format the windows help viewer fails to load the stylesheets. If I remove the query component before compiling the chm file it works.

### How to Reproduce

1. Use any sphinx project and run it with the output format htmlhelp.
2. Compile the .hpp file with the Microsoft HTML HELP Workshop.
3. Open the chm file and there are no styles.

### Environment Information

```text
Platform:              win32; (Windows-11-10.0.22631-SP0)
Python version:        3.12.1 (tags/v3.12.1:2305ca5, Dec  7 2023, 22:03:25) [MSC v.1937 64 bit (AMD64)])
Python implementation: CPython
Sphinx version:        7.2.6
Docutils version:      0.20.1
Jinja2 version:        3.1.3
Pygments version:      2.17.2
```

### Additional context
It's a similar issue to #11598 where it does not work with epub.
I can provide a pull request to fix this if you are interested.

**Comment by AA-Turner** [comment]
Hi @mkay-sh,

A PR would be appreciated, thank you!

A

**Comment by Hzmf88** [comment]
Hi
Opinion mobile [009665615191]()

**Comment by jayaddison** [comment]
Do you have any notes about the introduction of the CRC32 checksums @AA-Turner?  I'm guessing it may have been to help cache-bust CSS/JS retrieval?

**Comment by AA-Turner** [comment]
For exactly that reason, yes.

A

**Comment by jayaddison** [comment]
Ok - and is/was it not possible to use `<filename>.<checksum>.css` as a filename format instead of emitting `<filename>.css?<checksum>`-format URIs?  (there are no doubt other downsides to embedding the checksum in the filename that I'm not thinking of, but it seems like a possible alternative)

**Comment by jayaddison** [comment]
(my honest opinion is that I feel like this _should_ be solved by ETags (for content caching) and subresource integrity (content integrity validation) - but I don't know how reliable those are at scale, especially for legacy/speciality user agents)
