### ISSUE TITLE
Error in searchtools.js: Uncaught (in promise) TypeError: Cannot read properties of null (reading 'textContent')

### ISSUE THREAD

**Issue by kkntl** [sphinx-doc/sphinx#11884]
### Error:

There is an error when using the search if there is no `[role="main"]` element on the page:
> searchtools.js:159: Uncaught (in promise) TypeError: Cannot read properties of null (reading 'textContent')

### Expected:

No error, but a console warning:
> "Content block not found. Sphinx search tries to obtain it via '[role=main]'. Could you check your theme or template."

### Details:

In [searchtools.js](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/themes/basic/static/searchtools.js#L166), if `htmlElement.querySelector('[role="main"]');` doesn't find anything, then the [`querySelector`](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector) returns `null`. This causes the error in the next line `if (docContent !== undefined) return docContent.textContent;`

I guess this error was introduced in [commit 3b01fbe2ad](https://github.com/sphinx-doc/sphinx/commit/3b01fbe2adf3077cad5c2cf345c6d000d429d7ac#diff-52f537c2146ef4388e77c5e7616aecdabb7fc09454d03694ae238551b9fc1286R148), before which `htmlElement.find()` was used, which would return `undefined` if nothing found.

### How to Reproduce

(Sorry, I found this error in a project that is not mine, so I can't debug it properly, but I think the error is obvious enough in the code.)

- Have no `[role="main"]` element on the page
- search something using the search input box on the page

### Environment Information

```text
I don't know the environment
```

**Comment by picnixz** [comment]
I assume that #11885 fixed this one.
