### ISSUE TITLE
no rebuild after file changes are detected

### ISSUE THREAD

**Issue by Gatherer** [sphinx-doc/sphinx#11908]
### Describe the bug

I currently update out company template from 5.3.0 to 7.2.6 (7.3.0 is planned as final version). The I noticed that documents are not rebuild. Sphinx do detect changes but somehow latexmk thinks there is nothing to do. 
It is possible to do a make clean and then a rebuild. But as we often build multiple documents changes last 3 minutes instead 10 seconds. During documentation development this sums up to a lot wait time.

I tracked the point down to the 6.0.1 -> 6.1.0 update.

With 6.0.1 a change is detected and the document is rebuiild.
![sphinx_6_0_1_rebuildAfterChange](https://github.com/sphinx-doc/sphinx/assets/1643176/78f610b1-65a2-4622-a08e-338211d0f590)

Wit 6.1.0 the change is also detected but no rebuild.
![sphinx_6_1_0_noRebuildAfterChange](https://github.com/sphinx-doc/sphinx/assets/1643176/7fc8fd26-3075-4d0b-b50c-acb038363a86)

I found the bug #11474 which describes basically the same behavior but during my tests changing the numfig setting do not show any affect.
I also tested Sphinx 7.1.0 due to the mentioned bug and the latest version 7.2.6.  The behavior is the same as 6.1.0.

### How to Reproduce

I have no small example.  Can do it if needed.

```
make venv
make latexpdf
change one or multiple files
make latexpdf
```

### Environment Information

```text
Platform:              linux; (Linux-4.19.0-26-amd64-x86_64-with-glibc2.35)
Python version:        3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0])
Python implementation: CPython
Sphinx version:        6.0.1
Docutils version:      0.18.1
Jinja2 version:        3.1.3
```

```text 
Platform:              linux; (Linux-4.19.0-26-amd64-x86_64-with-glibc2.35)
Python version:        3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0])
Python implementation: CPython
Sphinx version:        6.1.0
Docutils version:      0.18.1
Jinja2 version:        3.1.3
Pygments version:      2.17.2
```

```text 
Platform:              linux; (Linux-4.19.0-26-amd64-x86_64-with-glibc2.35)
Python version:        3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0])
Python implementation: CPython
Sphinx version:        7.1.0
Docutils version:      0.20.1
Jinja2 version:        3.1.3
Pygments version:      2.17.2
```

```text 
Platform:              linux; (Linux-4.19.0-26-amd64-x86_64-with-glibc2.35)
Python version:        3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0])
Python implementation: CPython
Sphinx version:        7.2.6
Docutils version:      0.20.1
Jinja2 version:        3.1.3
Pygments version:      2.17.2
```

### Sphinx extensions

**requirements.txt for test with Sphinx 6.0.1 and 6.1.0**
```python
docutils==0.18.1
sphinx_rtd_theme==2.0.0
sphinx-autobuild==2021.3.14
sphinxcontrib-bibtex==2.5.0
sphinxcontrib-globalsubs==0.1.1
sphinxcontrib-scalebybuilder==0.1.1
sphinxcontrib-svg2pdfconverter==1.2.2
sphinxcontrib-wavedrom==3.0.4
```

**requirements.txt for test with Sphinx 7.1.0 and 7.2.6**
```python
sphinx_rtd_theme==2.0.0
sphinx-autobuild==2021.3.14
sphinxcontrib-bibtex==2.6.2
sphinxcontrib-globalsubs==0.1.1
sphinxcontrib-scalebybuilder==0.1.1
sphinxcontrib-svg2pdfconverter==1.2.2
sphinxcontrib-wavedrom==3.0.4
```

**Extension**
```python
extensions = [
    'sphinx_rtd_theme',
    'sphinx.ext.intersphinx',
    'sphinx.ext.autodoc',
    'sphinx.ext.mathjax',
    'sphinx.ext.viewcode',
    'sphinx.ext.todo',
    'sphinxcontrib.bibtex',
    'sphinxcontrib.inkscapeconverter',
    'sphinxcontrib.scalebybuilder',
    'sphinxcontrib.globalsubs',
    'sphinxcontrib.wavedrom'
]
```

**Comment by AA-Turner** [comment]
cc: @jfbu

**Comment by jfbu** [comment]
Try ``make latexpdf LATEXMKOPTS="-g"`` as workaround.

I can not reproduce on simple examples so a minimal example would be much appreciated.

**Comment by Gatherer** [comment]
OK, will create one.

**Comment by Gatherer** [comment]
Don´t worry. It last a bit because I´m still on it.

**Comment by ban2st** [comment]
Hi, I dug into this and actually uncovered what's causing the issue (at least I think so):

After all documents have been read, the `Builder.build` method is invoking the `BuildEnvironment.check_dependents` methods.
![image](https://github.com/sphinx-doc/sphinx/assets/155977476/fa8dba41-f2d9-4783-a43d-2e1027a3637e)

This in turn emits the `env-get-updated` event that causes the `EnvironmentCollector.get_updated_docs` to be called. The implementation of this method in `TocTreeCollector` is then calling a `assign_figure_numbers` method which does nothing except when setting `numfig = True`:
![image](https://github.com/sphinx-doc/sphinx/assets/155977476/ebac06be-c6f5-41fe-a26c-2139eb9c9459)

Then `_walk_doc` is calling `BuildEnvironment.get_doctree` on EVERY file in the worktree.
So every single doctree is read into a bytes array and stored in the `_pickled_doctree_cache`. 
![image](https://github.com/sphinx-doc/sphinx/assets/155977476/ea3f2be5-7798-43ca-801a-028572c254a3)

The real issue now is that all of this happens before the environment is pickled and written to disk for further incremental builds:
![image](https://github.com/sphinx-doc/sphinx/assets/155977476/8984c5ce-1844-4b74-8a57-6c64bf862ac0)

So the environment gets written to a file while it contains the data of all doctrees in the `_pickled_doctree_cache` map.
(this was actually what brought me onto track here, as my `environment.pickle` file was far too huge).
Now during the next incremental build, the environment gets unpickled while still having cached all the existing doctree files  in the worktree!
As `_pickled_doctree_cache` is not meant to be pickled and reloaded, this essentially breaks the update build.

An easy fix is to prevent it from being pickled in the `BuildEnvironment.__getstate__` method:
![image](https://github.com/sphinx-doc/sphinx/assets/155977476/775803b7-20a4-4177-a532-7b0f2b3167bf)

@Gatherer Can you try to set `numfig = False` and delete your `environment.pickle` file? After this your subsequent builds should be working again if my analysis is correct :)

**Comment by Gatherer** [comment]
@ban2st interessting findings but they not match what I see or already tested. 

- As I wrote I tested numfig = False, no change in the behavior -> I will retest it just to double check
- During my tests I only changes one file as seen in the screenshot, the hole document only consist of two files, index.rst and demo.rst

What might be interesting is disabling the parallel build. Need to check how to do it. The logfile show that this one a new feature in 6.1.0

- Cache doctrees in the build environment during the writing phase.
- Make all writing phase tasks support parallel execution.

Currently I quite busy at work and this is a background task. I will to schedule it this week.

**Comment by ban2st** [comment]
@Gatherer sorry, moved my post to the other related issue https://github.com/sphinx-doc/sphinx/issues/11474 as I think it fits there better after re-reading your issue (as you also stated)

**Comment by Gatherer** [comment]
Hello,

I finally boiled it done to a small example project. The outcome is not what I expected as I did end up in bug #11474. I have to retest more thinks but I was able to put it into a two github repos. This setup is maybe not the common but it is as near on the original git setup structure and as small as possible. 

I just saw that there is already a pull request so maybe it's a bit late. 
To reproduce the problem clone the sphinx debug repository `git clone --recursive https://github.com/Gatherer/sphinx_debug_repo` . This has a second repository as submodule. 

To test it do the following 

```
- check out sphinx_debug_repo either with --recursive or do a update --init later
- make venv
- make latexpdf
- change something in stuff.rst
- make latexpdf 
```
This should work.

```
- then uncomment numfig = True in submodule conf.py, line 135
- make clean
- make latexpdf
- change something in stuff.rst
- make latexpdf
```
The second run always fails for me. I can reproduce it with these two projects over and over again.

On another project I do have the same error. The PDF is updated even the PDF is rebuild. I also can trigger this behavior by enabling and disabling `numfig = true`

Will look forward to your answer.

**Comment by picnixz** [comment]
Does my PR fix your issue actually?

**Comment by Gatherer** [comment]
Yes, it fixes the problem in both project I mentioned in the comment above and in the original one where I discovered the problem.

**Comment by Gatherer** [comment]
Hello all,

is there any update? Will the fix be applied? You need more / other information's?

**Comment by Gatherer** [comment]
> The only thing I am wondering about is how much it could impact the build of very large projects but I think I'll merge it next week (I am currently travelling).

Happy traveling
