### ISSUE TITLE
Sphinx accesses inherited annotations incorrectly in python 3.9 and earlier

### ISSUE THREAD

**Issue by j-carson** [sphinx-doc/sphinx#11917]
### Describe the bug

In python 3.10, a bug was fixed where an attempt to read the annotations on a class object could accidentally return the annotations on a superclass instead.  For python 3.9 and earlier, the is the suggested workaround:

https://docs.python.org/3.10/howto/annotations.html#accessing-the-annotations-dict-of-an-object-in-python-3-9-and-older

It appears that this needs to be implemented in sphinx/util/inspect.py line 88

In my test case, class A1 is NOT using inherited-members and class A2 is using inherited-members.
The inherited attribute `inherit_me` shows up in both classes when sphinx is run in a python 3.9 environment but only on class A2 if you build and install in python 3.10

### How to Reproduce

index.rst 
```rst
My Docs
=======

.. currentmodule:: my_module

.. autoclass:: A1
   :members:

.. autoclass:: A2
   :members:
   :inherited-members:
```

source code
```python
class B:
    inherit_me: int
    """Inherit me from baseclass B"""

class A1(B):
    """inherit test #1  - members but not inherited-memebers"""

    my_a1 = 1
    """my_a1"""


class A2(B):
    """inherit test #2. -- members and inherited-members"""

    my_a2 = 2
    """my_a2"""
```

### Environment Information

Python 3.9 environment:

```text
Platform:              darwin; (macOS-14.2.1-arm64-arm-64bit)
Python version:        3.9.18 (main, Aug 24 2023, 18:16:58)
[Clang 15.0.0 (clang-1500.1.0.2.5)])
Python implementation: CPython
Sphinx version:        7.2.6
Docutils version:      0.20.1
Jinja2 version:        3.1.3
Pygments version:      2.17.2
```

Python 3.10 environment:
```text
Platform:              darwin; (macOS-14.2.1-arm64-arm-64bit)
Python version:        3.10.13 (main, Aug 24 2023, 12:59:26) [Clang 15.0.0 (clang-1500.1.0.2.5)])
Python implementation: CPython
Sphinx version:        7.2.6
Docutils version:      0.20.1
Jinja2 version:        3.1.3
Pygments version:      2.17.2
```

### Sphinx extensions

```python
extensions = [ "sphinx.ext.autodoc" ]
source_suffix = {
  '.rst': 'restructuredtext'
}
```

### Additional context

This is possibly a duplicate or related to a number of other issues referencing inherited annotations... but I've debugged this particular test case

**Comment by electric-coder** [comment]
Can you add a screenshot of the HTML built from the example for easier visualization?

**Comment by j-carson** [comment]
> Can you add a screenshot of the HTML built from the example for easier visualization?

Python 3.9 output shows inherited member regardless of inherited-members directive
![python39_output](https://github.com/sphinx-doc/sphinx/assets/44308120/923faae3-a052-4d10-8a24-54d8cc94cd9a)

Python 3.10 output only shows inherited member when inherited-members is turned on
![python3 10_output](https://github.com/sphinx-doc/sphinx/assets/44308120/c1795248-1a13-449f-bf67-612c02c0c65b)
