### ISSUE TITLE
Image size option in command \includegraphics is overwritten during latexpdf re-compile

### ISSUE THREAD

**Issue by pique-b** [sphinx-doc/sphinx#11930]
### Describe the bug

I am using Sphinx to generate both HTML and latexpdf documents. To include a logo in my documents, 
in my *conf.py*, I have defined a logo (stored in images folder in static root) using:

`latex_logo = '_static/logo/logo.png'`

In order to keep the logo size to a certain size I am using option `[width=0.2\textwidth]` in the command `\includegraphics`., as shown below:

\newcommand{\sphinxlogo}{\sphinxincludegraphics[width=0.2\textwidth]{logo.png}\par}

The above post-processing is being done in a TeX editor and the logo re-sizes successfully (as viewed in the resulting pdf file - both in the editor as well as the standalone file itself).

However, in case I make some changes in a (or, any number of) source file, on recompiling using `make latexpdf`, I find that the inclusion of the *option* part is missing from the `\includegraphics` command. And I am back to square one.

### How to Reproduce

# -- Options for LaTeX output -------------------

latex_engine = 'pdflatex'
latex_elements = {
    # The paper size ('letterpaper' OR 'a4paper')
    'papersize': 'a4paper',
    'releasename': " a_name ",
    'figure_align': 'htbp',
    'pointsize': '10pt',
    'pxunit': '0.75bp', 

    }
latex_logo = '_static/logo/logo.png' # As stated above
latex_show_urls = 'footnote'
latex_show_pagerefs = True
latex_domain_indices = True

### Environment Information

```text
Sphinx 7.2.6
macOS 10.12
TeX Live 2023
```

### Sphinx extensions

```python
I have included the following extensions in `conf.py`:

'sphinx.ext.autodoc'
'sphinx.ext.imgmath'
```

### Additional context

Under the circumstances, what needs to be done so that the logo size does not revert back to the original size?

**Comment by picnixz** [comment]
I think the issue is we don't use your command but our own (for some obscure reason). I haven't tried but maybe if you have some `\renewcommand` instead of `\newcommand` in your preamble, this could work?

@jfbu any idea ?

**Comment by jfbu** [comment]
Unfortunately the definition by `\newcommand` of `\sphinxlogo` is done by out template after insertion of `latex_elements['preamble']`
https://github.com/sphinx-doc/sphinx/blob/41ab0f9a414fc73c4a322adf0dd3c5ab857686f9/sphinx/templates/latex/latex.tex_t#L79-L89

And in the above we see there is no interface to tell `\sphinxincludegraphics` to use options, because the curly brackets are there around `logofilename`.

So one has to do something such as
```
latex_elements = {
    'preamble': r"""
\AtBeginDocument{\renewcommand\sphinxlogo{\sphinxincludegraphics[width=0.2\textwidth]{logo.png}\par}}
""",
}
```

**Comment by pique-b** [comment]
It works.

Thanks
