### ISSUE TITLE
Using symbol pi (π) raises compilation error "Unicode character not set up for use with LaTeX"

### ISSUE THREAD

**Issue by pique-b** [sphinx-doc/sphinx#11949]
### Describe the bug

I am trying to use `pi` (symbol π) in my Sphinx `.rst` file. Till the point of the said addition, the `make latexpdf` was executing without any error. However, once I add the symbol I start getting the following error (in the terminal):

```
! LaTeX Error: Unicode character π (U+03C0)
               not set up for use with LaTeX.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.

You may provide a definition with
\DeclareUnicodeCharacter 
 ...                                              
                                                  
l.436 ...pi is the command to insert the symbol π
```

Next I added `\DeclareUnicodeCharacter{03C0}{\π}` in `conf.py`, and ran `make latexpdf` again when I got the following:

```
! Undefined control sequence.
<argument> \?
             ?
l.433 ...pi is the command to insert the symbol π
```

Hitting `Return` raises the following:

```
! LaTeX Error: Invalid UTF-8 byte "80.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.433 ...pi is the command to insert the symbol π
```

Typing **h** and hitting `Return` gets me:

```
The document does not appear to be in UTF-8 encoding.
Try adding \UseRawInputEncoding as the first line of the file
or specify an encoding such as \usepackage [latin1]{inputenc}
in the document preamble.
Alternatively, save the file in UTF-8 using your editor or another tool
```

Finally the compilation ends with:

```
Latexmk: If appropriate, the -f option can be used to get latexmk
  to try to force complete processing.
make[1]: *** [techno23.pdf] Error 12
make: *** [latexpdf] Error 2
```

If I add option `latin1` in the inputenc as a separate preamble `usepackage` command, I get:

```
! LaTeX Error: Option clash for package inputenc.
```

Hitting `Return` at this point gets me:

```
The package inputenc has already been loaded with options:
  [utf8]
There has now been an attempt to load it with options
  [latin1]
Adding the global options:
  utf8,latin1
to your \documentclass declaration may fix this.
Try typing  <return>  to proceed.
```

And the processing again stops at `l.433 ...pi is the command to insert the symbol π` stage.

At the end, the compilation ends with:

```
Latexmk: If appropriate, the -f option can be used to get latexmk
  to try to force complete processing.
make[1]: *** [techno23.pdf] Error 12
make: *** [latexpdf] Error 2
```

### How to Reproduce

Adding the following text:

`\pi is the command to insert the symbol π`

starts the compilation error **as described above**.

I have tried adding the following in `conf.py`:

```
       \DeclareUnicodeCharacter{03C0}{\π}
```

However it **does not seem to have any effect at all**.

### Environment Information

```text
Sphinx v7.2.6
TeX Live 2023
macOS 10.12.6
```

### Sphinx extensions

```python
These are the extension I am using:


extensions = ['sphinx.ext.autodoc',
              'sphinx.ext.imgmath',
              
]
```
```


### Additional context

_No response_

**Comment by picnixz** [comment]
This is not how you use `DeclareUnicodeCharacter`. You need to write `\DeclareUnicodeCharacter{03C0}{$\pi$}` (and use the `[utf8]` option for `inputenc`, but that's the default for `pdflatex`).

Now, I'd suggest you use the [`.. math`](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-math) directive or the [`:math:`](https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#role-math) role for rendering maths.

**Comment by pique-b** [comment]
I am sorry but what I am doing is:

I am putting the *text* `\pi` in a sentence, as in:

> \pi is the command to insert the symbol ...


So, then I have to add :math:`\pi` in the body of a sentence, wherever I have a requirement to do so without having the command `\DeclareUnicodeCharacter{03C0}{$\pi$}` in the preamble.

So that I want to avoid putiing :math: role as often as needed, and to avoid the terminal raising the aforesaid error,  adding `\DeclareUnicodeCharacter{03C0}{$\pi$}` solves the problem.

**And of course**, in a math formula we need to use directive ``.. math::`` or ``:math:`` role for inline.

Would you please clarify the above?

**Comment by picnixz** [comment]
Ah sorry I misunderstood since you said you want to use `pi` the symbol. If you want to render something like `\pi is the command to render π`, then you need to do something like:

```rst
\\pi is the command to render :math:`\pi`
```

You can't just put `\pi` as a 'standalone' text because otherwise LaTeX will only see `\pi`. So you need to escape the `\` in the RST document. If you additionally use `\DeclareUnicodeCharacter` as I said, you can write:

```rst
\\pi is the command to render π
```

AFAIK, you can't escape from the needs of escaping the backslash though.
