### ISSUE TITLE
Glossary does not render in latex pdf file.

### ISSUE THREAD

**Issue by ngminhthanh12a3** [sphinx-doc/sphinx#11946]
### Describe the bug

I had a problem on using the glossary directive with latex pdf build.
The latex pdf file does not contain the glosary. But the html output file does.

### How to Reproduce

Here are my texts and results.

```
// rst file content

Training :term:`MCU` of the device is STM32F103RCT6.

.. glossary::

  MCU
    Micro Controller Unit

```

```
// In HTML result

Training MCU of the device is STM32F103RCT6.
```

```
// In latex pdf file result

Training of the device is STM32F103RCT6.
```

### Environment Information

```text
Platform:              linux; (Linux-5.15.0-92-generic-x86_64-with-glibc2.35)
Python version:        3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0])
Python implementation: CPython
Sphinx version:        7.2.6
Docutils version:      0.19
Jinja2 version:        3.0.3
Pygments version:      2.16.1
```

**Comment by picnixz** [comment]
You have bad indentation in your glossary which is possibly the reason why it fails. I cannot reproduce the issue on my side if I simply do `make latexpdf`.

**Comment by ngminhthanh12a3** [comment]
> You have bad indentation in your glossary which is possibly the reason why it fails. You need 3 spaces before your MCU and not 2. I cannot reproduce the issue on my side if I simply do `make latexpdf`.
> 
> (Sorry for closing it directly, so feel free to reopen if you still have an issue).

Thank you so much! The problem has been fixed. The ``MCU`` glossary can be printed in the PDF file.
