### ISSUE TITLE
HTML Search: Partial matches can overwrite main matches in certain rare cases

### ISSUE THREAD

**Issue by wlach** [sphinx-doc/sphinx#11957]
### Describe the bug

In the case of the first document in a Sphinx index, partial matches can overwrite the main one. This causes the rank to be artificially lowered.

### How to Reproduce

This is difficult to reproduce manually, I will reproduce it with a unit test when I file a PR.

### Environment Information

Sphinx main as of 2024-02-06: https://github.com/sphinx-doc/sphinx/commit/e976059fd6ab49b1c2784445d7095c9287897724

**Comment by jayaddison** [comment]
I'm relatively confident that this is a problem with the structure of our test fixture that does not affect the search indices for projects that have been built into HTML deployments; see #12028 for details, and feel free to re-open if I'm (provably, preferably!) incorrect.

**Comment by jayaddison** [comment]
My mistake closing this; terms in the JS search index that only exist in a single document are represented as standalone integers, not as the elements of list/array types.
