### ISSUE TITLE
[tests] _setup_intl autouse fixture writes mo files to unused paths

### ISSUE THREAD

**Issue by jayaddison** [sphinx-doc/sphinx#11953]
### Describe the bug

While reading #11940 I was looking through some of the `test_intl.py` code and noticed the [`_setup_intl` `pytest` fixture](https://github.com/sphinx-doc/sphinx/blob/ceb3b2a904cb14f959917873e8be91fb194ca393/tests/test_intl/test_intl.py#L41-L56), which has `autouse=True` (meaning that the fixture is evaluated for all tests in the module - I've checked that that's the case).

The fixture appears to write `.mo` translation catalog files for applications when they have `.po` resource files and where either no `.mo` file exists, or it is out-of-date.

However: the file path that is checked for an `.mo` file -- and subsequently the file path that an `.mo` file is written to - contain a duplicate path structure:

```
/tmp/pytest-of-user/pytest-28/builder-gettext-dont-rebuild-mo/xx/LC_MESSAGES/xx/LC_MESSAGES/bom.mo
```

Because these paths seem incorrect, I think it may be valid to remove the `_setup_intl` fixture entirely; it's performing file I/O but not to paths that are used by other tests.

I've confirmed that unit tests continue to pass locally with the fixture removed.

### How to Reproduce

Apply the following patch to ceb3b2a904cb14f959917873e8be91fb194ca393 (or any relatively recent commit):

```diff
diff --git a/tests/test_intl/test_intl.py b/tests/test_intl/test_intl.py
index 4287182fa..b4109c021 100644
--- a/tests/test_intl/test_intl.py
+++ b/tests/test_intl/test_intl.py
@@ -52,6 +52,10 @@ def _setup_intl(app_params):
                 mo.parent.mkdir(parents=True, exist_ok=True)
 
             if not mo.exists() or os.stat(mo).st_mtime < os.stat(po).st_mtime:
+                print(app_params.kwargs['srcdir'])
+                print(dirpath / f)
+                print(mo)
+                raise
                 # compile .mo file only if needed
                 write_mo(mo, read_po(po))
 
```

And then run a test from the `test_intl.py` module:

```sh
$ pytest tests/test_intl/test_intl.py -k test_gettext_dont_rebuild_mo
```

The test should fail due to the raised exception during the autouse fixture, and the unexpected `.mo` file path will be printed.

### Environment Information

```text
Platform:              linux; (Linux-6.6.13-amd64-x86_64-with-glibc2.37)
Python version:        3.11.7 (main, Dec  8 2023, 14:22:46) [GCC 13.2.0])
Python implementation: CPython
Sphinx version:        7.3.0+/ceb3b2a90
Docutils version:      0.20.1
Jinja2 version:        3.1.3
Pygments version:      2.17.2
```

### Sphinx extensions

```python
N/A
```

### Additional context

N/A

**Comment by picnixz** [comment]
Superseeded by #11940.
