### ISSUE TITLE
New line and line-brack doesn't work in cnfluance.

### ISSUE THREAD

**Issue by sargis2000** [sphinx-doc/sphinx#11999]
### Describe the bug

When I try to build Confluence pages using sphinxcontrib.confluencebuilder, it ignores new lines and line breaks in .md files. I used 'myst-parser' and 'm2r' for including Markdown files, but both have the same issue.

I contacted the Atlassian Development team, and they said the problem is not on their side. They suggested that I contact the Sphinx development team.

### How to Reproduce

```python
# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = "PrjName"
copyright = "2023, Sargis"
author = "Sargis"
release = "1.0"

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = [
    "sphinx.ext.todo",
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinxcontrib.confluencebuilder",
    'm2r',
#  '"myst_parser"'
]

templates_path = ["_templates"]
exclude_patterns = []
autodoc_mock_imports = ["exc"]

napoleon_google_docstring = True
napoleon_use_ivar = True
confluence_cleanup_from_root = True
confluence_publish = True
confluence_space_key = "Myspace"
confluence_parent_page = "Root Page"
confluence_server_url = "my-url"
confluence_ask_user = True
confluence_ask_password = True
# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_theme = "alabaster"
html_static_path = ["_static"]
source_suffix = [".rst", ".md"]

```

**#  index.rst**

```restructuredtext

Documentation!
=========================================

.. toctree::
   :maxdepth: 10
   :caption: Modules:

   my_libs/index
   envvars.md
   googlestyledocstrings.md



Indices and tables
==================

* :ref:`genindex`
* :ref:`modindex`
* :ref:`search`

```

### Environment Information

```text
My requirements versions

alabaster==0.7.13
astroid==3.0.2
Babel==2.14.0
black==23.12.1
certifi==2023.11.17
cfgv==3.4.0
charset-normalizer==3.3.2
click==8.1.7
dill==0.3.7
distlib==0.3.8
docutils==0.20.1
filelock==3.13.1
identify==2.5.33
idna==3.6
imagesize==1.4.1
importlib-metadata==7.0.1
isort==5.13.2
Jinja2==3.1.2
m2r==0.3.1
markdown-it-py==3.0.0
MarkupSafe==2.1.3
mccabe==0.7.0
mdit-py-plugins==0.4.0
mdurl==0.1.2
mistune==0.8.4
mypy-extensions==1.0.0
myst-parser==2.0.0
nodeenv==1.8.0
packaging==23.2
pathspec==0.12.1
platformdirs==4.1.0
pre-commit==3.6.0
pydocstyle==6.3.0
Pygments==2.17.2
pylint==3.0.3
PyYAML==6.0.1
requests==2.31.0
snowballstemmer==2.2.0
Sphinx==7.2.6
sphinxcontrib-applehelp==1.0.7
sphinxcontrib-confluencebuilder==2.4.0
sphinxcontrib-devhelp==1.0.5
sphinxcontrib-htmlhelp==2.0.4
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.6
sphinxcontrib-serializinghtml==1.1.9
tomli==2.0.1
tomlkit==0.12.3
typing_extensions==4.9.0
urllib3==2.1.0
virtualenv==20.25.0
zipp==3.17.0
```

### Sphinx extensions

```python
extensions = [
    "sphinx.ext.todo",
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinxcontrib.confluencebuilder",
    'm2r',
#  '"myst_parser"'
]
```

**Comment by electric-coder** [comment]
You're not giving any reStructuredText or Markdown example file than can be tested. It would also help if you included a screenshot of the problem you're having. I'd never heard of the [m2r](https://pypi.org/project/m2r/) but from you description I'm guessing there's something wrong in the transformation step from md to rst.

Also the [sphinxcontrib-confluencebuilder](https://github.com/sphinx-contrib/confluencebuilder/issues) has their own active issues page, I think you're likely to get a quicker response if you post there and they help figuring out what's wrong.

**Comment by sargis2000** [comment]
[envvars.md](https://github.com/sphinx-doc/sphinx/files/14384849/envvars.md)
![What we expect](https://github.com/sphinx-doc/sphinx/assets/100423404/956ef1cf-7c0c-4dd2-b4b3-eae128002f7e)
![Result in Confluence ](https://github.com/sphinx-doc/sphinx/assets/100423404/bf41f5a4-c312-446d-819a-46f952b4ce12)

**Comment by sargis2000** [comment]
> You're not giving any reStructuredText or Markdown example file than can be tested. It would also help if you included a screenshot of the problem you're having. I'd never heard of the [m2r](https://pypi.org/project/m2r/) but from you description I'm guessing there's something wrong in the transformation step from md to rst.
> 
> Also the [sphinxcontrib-confluencebuilder](https://github.com/sphinx-contrib/confluencebuilder/issues) has their own active issues page, I think you're likely to get a quicker response if you post there and they help figuring out what's wrong.

I will also write them

**Comment by electric-coder** [comment]
I think your `.md` is wrong because a paragraph needs to be separated by a blank line, see:

> [Paragraphs][1]
>
> To create paragraphs, use a blank line to separate one or more lines of text.

Without a blank line separating the paragraphs the lines get joined. So get rid of the `<br>` with Markdown you're supposed to use a blank line instead of it.

[1]: https://www.markdownguide.org/basic-syntax/#paragraphs-1

**Comment by jayaddison** [comment]
> Without a blank line separating them lines are joined into a single line.

This isn't strictly true according to the [Markdown spec regarding linebreaks](https://www.markdownguide.org/basic-syntax/#line-breaks):

> To create a line break or new line (\<br\>), end a line with two or more spaces, and then type return.

The sample markdown snippet provided does include multi-spaces at the end of some of the lines, so it appears valid.  What's TBD here is where (in terms of codebase) those newlines are being omitted, and what can be done about it.

**Comment by electric-coder** [comment]
@jayaddison good catch! Also in the spec:

> **in nearly every Markdown application** (, but it’s controversial)

Since this choice depends on the *flavor* I generally disregard it. Maybe Sphinx hasn't defined its *Markdown flavor* because it's originally a reST processor.

**Comment by picnixz** [comment]
AFAIK, we expect valid RST content and not just markdown content. Since the issue stems from a 3rd party extension, I am closing this one (this repo is only meant for core issues and not non-native extensions). I think the issue should be reported to `myst_parser` or `m2r` instead.

**Comment by chrisjsewell** [comment]
@sargis2000 myst-parser follows commonmark, it is recommended to use `\` hard line breaks.
You can see this working in https://myst-parser.readthedocs.io/en/latest/live-preview.html 😄
