### ISSUE TITLE
Minify css and js

### ISSUE THREAD

**Issue by athioak7** [sphinx-doc/sphinx#11997]
It would be great if the css and js files were minified in the build or if there is the option to minify them, so that the end result is faster. My sphinx build is really big so any performance enhancements will help.

**Comment by mgeier** [comment]
Can you provide some speed measurements?
For example with your browser's developer tools or maybe with something like https://pagespeed.web.dev/?

It would be interesting where those big CSS and JS files come from. I might be core Sphinx, or your Sphinx theme, or maybe some Sphinx extension you are using?

**Comment by athioak7** [comment]
My sphinx build is local, so I can't test it, but I have some long pages that take 3-4 seconds to load. I don't necessarily have an example of a large css/js file but I thought minifying could help with the performance. I cannot manually minidy the files so I'm asking if it is possible to minify them during the build
