### ISSUE TITLE
Write out JUnit-like XML file for doctests

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1200]
Hi there,

it'd be great if the sphinx's doctest runner could write out an [XML file](http://stackoverflow.com/questions/442556/spec-for-junit-xml-output) of results so that doctests can be automatically run by a CI server (such as Jenkins).

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1200
- Originally reported by: Andreas Kloeckner
- Originally created at: 2013-06-20T19:20:11.005

**Comment by AA-Turner** [comment]
This hasn't been commented on for seven years, if there's still demand please open a new issue or PR.

A
