### ISSUE TITLE
Optionally warn about not highlighted blocks

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1201]
If I use automatic highlighting of python code and make typo which leads to unparseble python snippet then Sphinx silenty renders code not highlighted.

It would be nice feature if Sphinx will warn be about such blocks, where syntax highliting failed.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1201
- Originally reported by: [rutsky](https://bitbucket.org/rutsky)
- Originally created at: 2013-06-20T22:46:10.471

**Comment by shimizukawa** [comment]
_From [rutsky](https://bitbucket.org/rutsky) on 2013-06-25 19:29:41+00:00_

I monkey-patched Sphinx to fail if not highlighted block found in [Buildbot](http://buildbot.net/) project documentation: https://github.com/buildbot/buildbot/blob/e8ef280b5ab6601eb172562fbbe1df03891f535b/master/docs/conf.py#L238

So now either code is valid Python code and highlighted as Python, or it has language explicitly specified. No silently unhighlighted Python code with unmatched brackets. 

IMHO this feature request can be quite easily implemented in Sphinx, it only requires "green light" from project developers.

**Comment by ericholscher** [comment]
:+1: Just ran into this. Also wish it would try and parse more smartly, and not just bail back to plain text.

**Comment by tk0miya** [comment]
The warning was introduced since 1.3.5.
More details, see #1565.

Thanks,
