### ISSUE TITLE
quickstart: use $NAME envvar for default 'Author name'

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1202]
It would be nice if the variable was used if it has content.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1202
- Originally reported by: Tshepang Lekhonkhobe
- Originally created at: 2013-06-21T15:58:19.729

**Comment by tk0miya** [comment]
+0; I don't know `$NAME` is best, but that's nice if there are standard envvars for authors.

**Comment by tk0miya** [comment]
I can't find appropriate envvar for authors. So -1 for this idea.
It is not good to use Sphinx-original envvars to me.

Note: `$USER` or `%USERNAME%` is commonly used for "username". But, I feel username is not name of authors.
https://unix.stackexchange.com/questions/76354/who-sets-user-and-username-environment-variables

**Comment by shimizukawa** [comment]
No comment from me.

**Comment by tk0miya** [comment]
Closing now.
