### ISSUE TITLE
Search: don't show content of raw HTML `<script>` tags (and maybe others) in search preview

### ISSUE THREAD

**Issue by mgeier** [sphinx-doc/sphinx#12052]
### Describe the bug

Some tags are filtered out before creating the search index (I don't know why this appears in two places in the code):

https://github.com/sphinx-doc/sphinx/blob/ae51974e217cc7590e1b9c68f18af3e043027c6d/sphinx/search/__init__.py#L221-L227

https://github.com/sphinx-doc/sphinx/blob/ae51974e217cc7590e1b9c68f18af3e043027c6d/sphinx/search/__init__.py#L487-L495

However, those parts still seem to be contained in the search preview.

### How to Reproduce

`index.rst`:

```rst
Hello
=====

.. raw:: html

    <script type="text/javascript">
      console.log("green");
    </script>

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
culpa qui officia deserunt mollit anim id est laborum.

And here the search word: green
```

When searching for "green", the JavaScript code is shown in the preview text:

![image](https://github.com/sphinx-doc/sphinx/assets/705404/60698a83-908a-4382-a0ce-0a867d919b32)

Note that this only happens if the word "green" is also part of the "normal" text.

### Environment Information

```text
any
```

### Sphinx extensions

```python
none
```

### Additional context

This problem was reported to `nbsphinx`, where the raw HTML is created from output cells of Jupyter notebooks: https://github.com/spatialaudio/nbsphinx/issues/777

**Comment by picnixz** [comment]
Wow, never expected that this bug wasn't noticed before! so PR is welcome though I will be less available in the next 10 days.

**Comment by jayaddison** [comment]
We may need to implement some equivalent filtering in the client-side JavaScript code to resolve this; when configured to, the client makes an HTTP request per search result to retrieve the summary content (as HTML).

The relevant `makeSearchSummary` code (current v7.2.6 release link, some small changes since then) is here: https://github.com/sphinx-doc/sphinx/blob/cf7d2759af0852d67288e58d823d51fe860749ca/sphinx/themes/basic/static/searchtools.js#L547-L572

**Comment by jayaddison** [comment]
HTML/XML comments occurred to me as another thing that we'd want to filter out from the summary text; they already are, though.  I'll spend some more time to think about other elements that could require filtering.  In the meantime, #12057 begins by handling the `<script>` elements.

**Comment by mgeier** [comment]
> other elements that could require filtering

According to the search index filtering code I referenced above, it looks like `<style>` tags should also be filtered out, which makes sense.

I assume that the third regular expression is supposed to filter out the tags themselves, without removing the content within those tags. It looks like this is already working correctly.

**Comment by jayaddison** [comment]
Note: this can only occur when the non-visible HTML elements are located within `role="main"` on the page -- because content outside of that area will not be retrieved by the `htmlToText` function.

**Comment by zerothi** [comment]
freaking love this! Thanks! :)
