### ISSUE TITLE
label of math not work before `make clean` when math_numfig=True

### ISSUE THREAD

**Issue by berlin2123** [sphinx-doc/sphinx#12062]
### Describe the bug

Maybe a bug of build process:
> When setting `math_numfig=True`, and after add a new `math with label` into a `*.md` or `*.rst` source file,
> if we just run `make html` or just only using `sphinx-autobuild`, the lable of this added math will be a empty `()` .
> However, after `make clean; make html`, all lable will be fine.

Screenshots and discussions can be viewed in https://github.com/executablebooks/MyST-Parser/issues/886
The bug was initially mislocated, so it was submitted over there.

### How to Reproduce

conf.py:
```
math_numfig = True
numfig = True               # if its False, will not be empty `()` , but, it's not the type I wanted `(n.m)`.
numfig_secnum_depth = 2
```
Add a new math with label, 'make html' or do not restart `sphinx-autobuild`, always empty `()` .
It will be fine after `make clean; make html`.

### Environment Information

```text
Platform:              linux; (Linux-6.5.11-7-pve-x86_64-with-glibc2.35)
Python version:        3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0])
Python implementation: CPython
Sphinx version:        7.2.6
Docutils version:      0.20.1
Jinja2 version:        3.1.3
Pygments version:      2.17.2
```

### Sphinx extensions

```python
extensions = ['sphinx.ext.mathjax', 'myst_parser']
```

**Comment by picnixz** [comment]
Thank you for the report. 

Could you check if #11939 solves your issue?

**Comment by picnixz** [comment]
(the patch landed but please check if it now works)

**Comment by berlin2123** [comment]
it works fine now.

ps. need restart the `sphinx-autobuild` to test, after used #11939

**Comment by picnixz** [comment]
Perfect ! (now I'm confident enough to say that the patch was needed)
