### ISSUE TITLE
add additional lints

### ISSUE THREAD

**Issue by danieleades** [sphinx-doc/sphinx#12084]
- [x] #12070 
- [x] #12068 
- [x] #12069 
- [x] #12073
- [x]  #12086 

cc @picnixz

**Comment by picnixz** [comment]
Are there more tasks like that that you have on your backlog?

**Comment by danieleades** [comment]
> Are there more tasks like that that you have on your backlog?

i can think of one or two more

**Comment by picnixz** [comment]
Don't hesitate to put them here and ping me when needed

**Comment by jayaddison** [comment]
Are all the changes for this issue completed @danieleades?  And if so, is it OK to close?

**Comment by jayaddison** [comment]
Thank you!
