### ISSUE TITLE
function description above the function

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1208]
Hi All!

Is it possible to have the documentation comment code for python above the function
instead of inside?

Best, Marc

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1208
- Originally reported by: Anonymous
- Originally created at: 2013-07-08T12:33:51.814

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2013-07-08 13:24:17+00:00_

Impossible. Currently, you can write a document in front only for attributes.

```
#!python

#: This is a document for attr_value
attr_value = 0

#: This line is not recognized.
def foo_func(arg):
    pass

```

Why do you want to use comment avobe the function?

**Comment by tk0miya** [comment]
-1; docstring is standard way to add description for functions.
