### ISSUE TITLE
Unicode superscript fails with LaTeX

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1212]
I have a block of Python code that contains Unicode superscript characters:

```
#!python

>>> x = ufloat_fromstr("20(1)×10⁻²")
```

I need the Sphinx document to be output both in HTML and LaTeX. However, LaTeX complains that the superscript minus cannot be used:

```
! Package inputenc Error: Unicode char \u8:⁻ not set up for use with LaTeX.
```

Is there a simple solution to this problem?

I thought about using :raw:, but I understand it cannot be nested inside the code block. I thought about using XeLaTeX instead of the default Sphinx pdflatex (because XeLaTeX can use OpenType fonts instead of the 256-character LaTeX fonts), but this entails writing an extension, right?… which I would like to avoid, so that my documentation can be distributed easily…

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1212
- Originally reported by: Anonymous
- Originally created at: 2013-07-14T15:48:28.018

**Comment by ghost** [comment]
@shimizukawa Maybe try the suggestion I linked to in your other ticket (#894); this enables xunicode for extended unicode input and opentype fonts; you might find the combination helps to eliminate the inputenc issue.

**Comment by tk0miya** [comment]
It was already fixed at current release.
Thanks,
