### ISSUE TITLE
RFE: move away from deprecated `html5lib`

### ISSUE THREAD

**Issue by kloczek** [sphinx-doc/sphinx#12150]
**This ticket is about `sphinx` and `sphinxcontrib-htmlhelp`.**

**Is your feature request related to a problem? Please describe.**
It would be nice tu cut tail of some legacy modules decencies.
One of those modules is `html5lib`.

**Describe the solution you'd like**
it wold be good to remove use of the html5lib deprecated  `html5lib` like it has been  done with pip ~2 years ago.
https://github.com/pypa/pip/pull/11259

**Describe alternatives you've considered**

**Additional context**
`html5lib` depends on `six` which is on list of deprecated modules even longer implanting this RFE would make easier kill two birds using one stone 😋

**Comment by picnixz** [comment]
I think we only use `html5lib` in tests, but sure I can do it.

**Comment by kloczek** [comment]
As work on move away from `htm5lib` the `sphinx` code looks like started may I ask again someone to have look on `sphinxcontrib-htmlhelp` code as well? This RFE is about both modules😋

**Comment by picnixz** [comment]
``sphinxcontrib-htmlhelp`` is another repo but sure

**Comment by picnixz** [comment]
Concerning `sphinxcontrib-help`, I need to bump versions and so on so I'm not entirely confident (also I cannot make a pypi release since I don't have permissions for that (I think?)).

**Comment by picnixz** [comment]
So I've upgraded the `sphinxcontrib-htmlhelp` extension but it requires the latest sphinx version. However... we have not release 7.3 yet so... I will make it the change when it's been upgraded.

**Comment by picnixz** [comment]
Actually, I was wrong. `sphinxcontrib-htmlhelp` requires some weird HTML which is not XML compliant and Microsoft's docs don't give a simple example or clear specs (maybe it's us that are doing bad as well). So for `sphinxcontrib-htmlhelp`, I'll keep the deprecated lib since otherwise having a dedicated parser would be an overkill (alternative, we could have used BeautifulSoup but it's an overkill as well).
