### ISSUE TITLE
[linting] Enforce module-level dunder naming style?

### ISSUE THREAD

**Issue by jayaddison** [sphinx-doc/sphinx#12179]
**Is your feature request related to a problem? Please describe.**
After some recent [discussion](https://github.com/sphinx-doc/sphinx/pull/12144#discussion_r1532115125), we landed on using [PEP8 style Module Level Dunder Names](https://peps.python.org/pep-0008/#module-level-dunder-names) for a module `__all__` declaration:

https://github.com/sphinx-doc/sphinx/blob/b7f708dc634732aa90978e1c141ba6bd2af7ee84/tests/utils.py#L1-L5

**Describe the solution you'd like**
There is a `module-level-line` plugin for `flake8` that could achieve this for us.  Although.. we are considering removing `flake8` (see #12163).

**Describe alternatives you've considered**
It would be nice if `ruff` reported this - currently it doesn't seem aware of `MLL004`.

**Additional context**
 - Inspired by a code review question at https://github.com/sphinx-doc/sphinx/pull/12178#discussion_r1535943497

**Comment by AA-Turner** [comment]
We ought not add more flake8 plugins, which are too slow -- if implemented in Ruff, we can return to this.
