### ISSUE TITLE
Role-based cross referencing for non-Sphinx API documentation

### ISSUE THREAD

**Issue by sr-murthy** [sphinx-doc/sphinx#12211]
**Is your feature request related to a problem? Please describe.**
This is just an idea, but it would be nice to be able to make role-based cross references from Sphinx-based API documentation to non-Sphinx based API documentation, e.g. MkDocs. This is not possible via Intersphinx which by design is limited to Sphinx, and the only real option is external links.

**Describe the solution you'd like**
Provide roles to cross reference from Sphinx to non-Sphinx API documentation. Example: if I have another (public) Python project documented with MkDocs, including an API reference, I would like to link to a library function in the MkDocs project from my Sphinx documentation via role such as:
```
:mkdocs:py:func:`<function name>`
```
Similarly for classes, methods, attributes etc. The result would be an anchored link to the target in the MkDocs API documentation, renderly appropriately.

**Describe alternatives you've considered**
ATM I think external links are the only option for the scenario I've described.

**Additional context**
N/A

- [e.g. URL or Ticket]

**Comment by chrisjsewell** [comment]
Heya, well unless mkdocs provides an index file for the location of references as part of their served websites, like sphinx does with the `objects.inv`, then this is probably not possible.

So I would invert this, and say that you should be asking mkdocs to generate an `objects.inv`, which would then allow for direct use by intersphinx 😉

**Comment by sr-murthy** [comment]
Hi. Np. I was going to mention that for this idea it would probably also require some work on the part of other non-Sphinx documentation providers, e.g. MkDocs. I will enquire, but I am also hinting at a future solution where there was a common standard to allow for this kind of "intra-provider" cross-referencing.

**Comment by cmarqu** [comment]
There is https://github.com/mkdocstrings/mkdocstrings (for MkDocs) that supports this in both directions: https://mkdocstrings.github.io/usage/#cross-references-to-other-projects-inventories

**Comment by sr-murthy** [comment]
> There is https://github.com/mkdocstrings/mkdocstrings (for MkDocs) that supports this in both directions: https://mkdocstrings.github.io/usage/#cross-references-to-other-projects-inventories

Thanks. I guess it's a case then of requesting the MkDocs projects I want to link to, to provide an `objects.inv`. Shouldn't be difficult. 😄 

I suppose this can be closed.
