### ISSUE TITLE
Display issue tracker URL instead of ML address in the error message.

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1221]
A number of reports have been sent to the ML.
But many mails will be buried without being replied from anyone.

I think this issue tracker is more suit to report.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1221
- Originally reported by: Takayuki Shimizukawa
- Originally created at: 2013-07-24T15:40:19.659

**Comment by jdillard** [comment]
It seems like this issue can be closed due to inactivity.

**Comment by shimizukawa** [comment]
Ok, thanks.
