### ISSUE TITLE
ubuntu 22.04 & python 3.10: cannot import name union from types - installing sphinx debian corrupted python install 

### ISSUE THREAD

**Issue by lcbw** [sphinx-doc/sphinx#12239]
### Describe the bug

Ubuntu 22.04 | Python 3.10
Upon installation of Sphinx via apt-get install python3-sphinx, running and attempting to build python3 packages of any kind fails due to " cannot import name union from types " 

This has corrupted my python install. The known way to rectify this is through using the pip installation: pip install -U "sphinx>=5.3"
Please either update the Debian with the patch or remove the recommendation of Debain installation from the documentation.  

### How to Reproduce

have python3.10 installed on an ubuntu 22.04 machine and run: apt-get install python3-sphinx

### Environment Information

```text
Prior to pip install -U "sphinx>=5.3"
username@machine:~$ sphinx-build --bug-report
Traceback (most recent call last):
  File "/home/lbayewallace/.local/bin/sphinx-build", line 5, in <module>
    from sphinx.cmd.build import main
  File "/home/lbayewallace/.local/lib/python3.10/site-packages/sphinx/cmd/build.py", line 25, in <module>
    from sphinx.application import Sphinx
  File "/home/lbayewallace/.local/lib/python3.10/site-packages/sphinx/application.py", line 31, in <module>
    from sphinx.config import Config
  File "/home/lbayewallace/.local/lib/python3.10/site-packages/sphinx/config.py", line 21, in <module>
    from sphinx.util import logging
  File "/home/lbayewallace/.local/lib/python3.10/site-packages/sphinx/util/__init__.py", line 41, in <module>
    from sphinx.util.typing import PathMatcher
  File "/home/lbayewallace/.local/lib/python3.10/site-packages/sphinx/util/typing.py", line 37, in <module>
    from types import Union as types_Union
ImportError: cannot import name 'Union' from 'types' (/usr/lib/python3.10/types.py)
After pip install -U "sphinx>=5.3":

Platform:              linux; (Linux-6.5.0-26-generic-x86_64-with-glibc2.35)
Python version:        3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0])
Python implementation: CPython
Sphinx version:        7.2.6
Docutils version:      0.20.1
Jinja2 version:        3.1.3
Pygments version:      2.17.2
```

**Comment by electric-coder** [comment]
A strange bug with an even stranger fix... I'm not a Linux user but I vaguely remember some bugs looking like this one being mentioned on the issue tracker around the time of the last release. [Maybe related](https://github.com/sphinx-doc/sphinx/issues/11567#issuecomment-1671561913).

**Comment by picnixz** [comment]
It's weird because that portion of the code is clearly not present as you can see:

https://github.com/sphinx-doc/sphinx/blob/cf7d2759af0852d67288e58d823d51fe860749ca/sphinx/util/typing.py#L18-L21

I suspect it's something to be reported on Ubuntu bugtracker instead.

**Comment by picnixz** [comment]
I think we should just remove the recommendation about the bundled package and rather suggest using `pip` in the first place.

**Comment by n-peugnet** [comment]
This is clearly a user error. We can see in the stacktrace that sphinx-build is called from `~/.local/bin`, so Sphinx was obviously already installed via pip without virtualenv before the install of Sphinx via apt. So packages from the user and system location were conflicting. This has been widely known to break system python packages. With [a newer python version the user would have been properly warned about this](https://veronneau.org/python-311-pip-and-breaking-system-packages.html) and this situation would probably have been avoided (or at least the user would have been aware of the issue beforehand and chose to ignore it).

**Comment by picnixz** [comment]
> We can see in the stacktrace that sphinx-build is called from ~/.local/bin

AH ! I missed that one. But I still think it might be better to recommend a local installation with a virtual environment.

**Comment by electric-coder** [comment]
> We can see in the stacktrace that sphinx-build is called from `~/.local/bin`

If this had happened on Windows it would have taken me 1 minute to diagnose :P It's the usual problem of having several Python installations discoverable on the Path.
