### ISSUE TITLE
Drop old docutils versions

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1223]
A few days ago, [docutils-0.11](https://pypi.python.org/pypi/docutils/0.11) has been released.

Currently, Sphinx is testing many docutils versions: 0.7, 0.8.1, 0.9.1, 0.10 and 0.11.

Because the docutils is to maintain backward compatibility, it's not complicated to continue support for many older versions. However, test time has been prolonged by this.

I propose that we drop 0.7 and 0.8 versions from tox.ini, but not limit in setup.py.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1223
- Originally reported by: Takayuki Shimizukawa
- Originally created at: 2013-07-25T02:41:46.401

**Comment by tk0miya** [comment]
Now, sphinx-1.3.3 depends on docutils-0.11 or later.
So I close this.

**Comment by shimizukawa** [comment]
Thanks!
