### ISSUE TITLE
Remote image download: consider using a packaged dependency to provide content caching.

### ISSUE THREAD

**Issue by jayaddison** [sphinx-doc/sphinx#12275]
**Is your feature request related to a problem? Please describe.**
Currently the [`ImageDownloader` component](https://github.com/sphinx-doc/sphinx/blob/cf7d2759af0852d67288e58d823d51fe860749ca/sphinx/transforms/post_transforms/images.py#L46-L108), used as a post-transform step to process remotely-downloaded images, contains Sphinx application code to maintain a local cache of retrieved content.

**Describe the solution you'd like**
I think it might be sensible to migrate to use an existing and popular Python HTTP content caching package such as [`requests-cache`](https://github.com/requests-cache/requests-cache) to handle the details of cache management (filesystem layout, HTTP protocol adherence, cache expiry, ...).

**Describe alternatives you've considered**
The existing `ImageDownloader` seems to be quite stable and reliable; there are very few bugreports related to it [in the Sphinx issue tracker](https://github.com/sphinx-doc/sphinx/issues?q=is%3Aissue+ImageDownloader).  Continuing to use it as-is is a very valid option.

**Additional context**
This idea is a result of learning that a subset of short URLs -- in particular those of 32-characters or less, and containing a port number specification in the netloc -- were not saved to disk on Windows (#12100).

That kind of slightly-obscure mix of conditions is often most rapidly discovered and best-resolved by shared components that by their nature handle lots of different use-cases for diverse projects; the suggestion here is to benefit from the experience and bugfixes of a component like that (including future improvements) while also adding our own usage patterns to the mix that could help to develop it.

**Comment by jayaddison** [comment]
Note also: to apply good engineering practices, we'd want to add test coverage for the existing image download caching behaviour (not the implementation specifics, but the behaviour - doesn't repeat downloads, does expire old content, etc) before performing a migration.  That'd help to confirm that the migration, when implemented, functions as expected.

**Comment by AA-Turner** [comment]
To be honest, I'd prefer to avoid an extra dependency here -- a cursory glance over requests-cache indicates it's a fairly complex package, of which we don't really have many use-cases for. I see the point about preferring a solid external implementation, but the change in our code to make things 'work' seems reasonably minimal.

There's also the point that at some point I want to move our HTTP handling to asynchronous code, and so we don't want to be too tied to requests.

That doesn't mean we can't revisit this discussion later if it becomes more relevant, though, and it's a generally good principle to keep in mind.

A
