### ISSUE TITLE
tabularry usage fails since 5.3.0

### ISSUE THREAD

**Issue by franzhaas** [sphinx-doc/sphinx#12285]
### Describe the bug

starting with this commit my latex based table generation which uses tabularry under the hood fails with.:

```

! LaTeX3 Error: Control sequence \c@rownum already defined.

For immediate help type H <return>.
 ...                                              
                                                  
l.112 \int_new:N \c@rownum
                          
```

we are using a self written 

### How to Reproduce

- unfortunately i do not have a minimal example at the moment. I can provide a relatively large one if it helps...

### Environment Information

```text
22.04.1-Ubuntu LTS
```

### Sphinx extensions

```python
none
```

### Additional context

I have a hard time finding a minimal example... I hope the provided information is enough to find an explanation.

Sorry, 
Franz

**Comment by picnixz** [comment]
It appears that the issue is with the fact that our LaTeX files are loaded before you are using `tabulary`. However the latter appears to forcibly define a new counter that we actually defined ourselves (and probably prior to its loading).

I think the problem can go away if you don't use tabulary, or if you can try patching `tabulary` itself (see `etoolbox`). @jfbu any suggestions you have in mind?

**Comment by jfbu** [comment]
Hello, are you referring to `tabularray` or to `tabulary`? `l.112 \int_new:N \c@rownum` is LaTeX3 code, which `tabulary` does not use.

Sphinx LaTeX code does  define a `rownum` counter, as would package `xcolor` with option `table`.

Some non-Sphinx code is doing a non cautious `\newcounter{rownum}` (or equivalent in LaTeX3 lingua).

Hmm I tried to trick `tabularray` into throwing the same error but its LaTeX3 code is `\int_zero_new:N \c@rownum` and this code does check for prior existence.  Your code is `\int_new:N \c@rownum`.  It may be that an old version of`tabularray` has the problem.   I can't test any other installation of TeXLive than current one or TL2019 and older ones, and `tabularray` did not exist then.

You could try `\makeatletter\let\c@rownum\relax\makeatother` before loading your version of `tabularrray`.

**Comment by jfbu** [comment]
P.S. I found the [tabularray commit](https://github.com/lvjr/tabularray/commit/d262ce4d64da3790786acb3ef47be379097d8f0c)  which changed its way of doing things, and thus with `tabularray  2022-07-01: Version 2022C` you would not have seen this conflict.  I can not test but if you add 

```latex
\makeatletter
\let\c@rownum\relax
\let\therownum\relax
\makeatother
```

before loading `tabularray` problems should go away.

**Comment by franzhaas** [comment]
Thanks a lot, this solved my issue!
