### ISSUE TITLE
v7.3 release breaks jupyterbook builds

### ISSUE THREAD

**Issue by ajfriend** [sphinx-doc/sphinx#12290]
### Describe the bug

Before v7.3, my jupyterbook project built fine. Afterwards:

```
Running Sphinx v7.3.0
making output directory... done
WARNING: The config value `myst_enable_extensions' has type `list'; expected `Any'.
WARNING: The config value `myst_url_schemes' has type `list'; expected `Any'.
WARNING: The config value `nb_execution_excludepatterns' has type `list'; expected `Any'.
```

### How to Reproduce

I'm working on it here: https://github.com/uber/h3-py/pull/362
You can see the working, then failing, then working again builds. The fix was introduced here: https://github.com/uber/h3-py/pull/362/commits/0e612825e6266aef1838e3aeb41fef672226db92

### Environment Information

The environment where it breaks is

```text
Platform:              darwin; (macOS-14.4.1-arm64-arm-64bit)
Python version:        3.11.8 (main, Apr  5 2024, 19:20:42) [Clang 15.0.0 (clang-1500.3.9.4)])
Python implementation: CPython
Sphinx version:        7.3.0
Docutils version:      0.20.1
Jinja2 version:        3.1.3
Pygments version:      2.17.2
```

The environment when it works is:

```text
Platform:              darwin; (macOS-14.4.1-arm64-arm-64bit)
Python version:        3.11.8 (main, Apr  5 2024, 19:20:42) [Clang 15.0.0 (clang-1500.3.9.4)])
Python implementation: CPython
Sphinx version:        7.2.6
Docutils version:      0.20.1
Jinja2 version:        3.1.3
Pygments version:      2.17.2
```

**Comment by AA-Turner** [comment]
Thanks @ajfriend -- please could you paste your ``conf.py``?

A

**Comment by ajfriend** [comment]
I don't have a `conf.py` since I'm doing everything via https://github.com/executablebooks/jupyter-book

Maybe the closest would be: https://github.com/uber/h3-py/blob/cd59584b8321259f5230e2588c4306744c208ef0/docs/_config.yml

**Comment by AA-Turner** [comment]
Are you able to test with 7bf847d2? It ought to fix the issue.

A

**Comment by AA-Turner** [comment]
[Sphinx 7.3.3](https://pypi.org/project/Sphinx/7.3.3/) has been released with fixes.

A

**Comment by ajfriend** [comment]
Confirmed that 7.3.3 works for me. Thanks for the fast fix!
