### ISSUE TITLE
get_config fails with any section that is not 'theme' or 'options'

### ISSUE THREAD

**Issue by Carreau** [sphinx-doc/sphinx#12305]
### Describe the bug

See https://github.com/sunpy/ablog/issues/277

in 360c7a80223e7818d002ce91146ee92c1eae7ec2 the following change was introduced:
```
-        try:
-            return self.config.get(section, name)
-        except (configparser.NoOptionError, configparser.NoSectionError):
-            if self._base:
-                return self._base.get_config(section, name, default)
-
-            if default is _NO_DEFAULT:
-                raise ThemeError(__('setting %s.%s occurs in none of the '
-                                    'searched theme configs') % (section, name)) from None
-            return default
+        if section == 'theme':
+            value = self._settings.get(name, default)
+        elif section == 'options':
+            value = self._options.get(name, default)
+        else:
+            value = _NO_DEFAULT
+        if value is _NO_DEFAULT:
+            msg = __(
+                'setting %s.%s occurs in none of the searched theme configs',
+            ) % (section, name)
+            raise ThemeError(msg)
+        return value
```

This means that any section name that is not 'theme', or 'options' will raise. Extensions, (typically `ablog`) use section names that are not 'theme' or 'options', and call get_config with a default values, failing.

https://github.com/sunpy/ablog/blob/b39f90bda1fc2bfddc373f5e5e970201914e1549/src/ablog/__init__.py#L121C14-L121C21

### How to Reproduce

Build anything that use `ablog` as extension with sphin
Build pydata-sphinx-theme docs by default for example

### Environment Information

```text
sphinx 7.3.6
```

### Sphinx extensions

```python
ablog
```

**Comment by AA-Turner** [comment]
Thanks for reporting.

The rationale for the changes is to tighten the theme configuration interface to allow supporting ``theme.toml``. The [documentation](https://www.sphinx-doc.org/en/master/development/theming.html#theme-configuration-theme-conf) has never advertised support for other sections, and whilst it has not been prohibited, it is not supported.

We could make the below change to remove the error, but this would mask the true behaviour, as Sphinx 7.3 and newer do have a behavioural change in that these other sections are unsupported.

```diff
 else: 
-    value = _NO_DEFAULT
+    value = default
```

https://github.com/sphinx-doc/sphinx/blob/630b4fb9df3fa3c2c74c96a84077b5e9e66a2066/sphinx/theming.py#L105-L130

A

**Comment by AA-Turner** [comment]
4a0c9dd

**Comment by AA-Turner** [comment]
[Sphinx 7.3.7](https://pypi.org/project/Sphinx/7.3.7/) has been released with fixes.

A

**Comment by Carreau** [comment]
Thanks for the quick fix !
