### ISSUE TITLE
Outdated docker images

### ISSUE THREAD

**Issue by lstrojny** [sphinx-doc/sphinx#12316]
### Describe the bug

The latest Docker image on https://hub.docker.com/r/sphinxdoc/sphinx is 7.1.2 but the latest sphinx version is 7.3.7.

**Comment by lstrojny** [comment]
I realize this should have been filed for https://github.com/sphinx-doc/sphinx-docker-images

**Comment by AA-Turner** [comment]
Done.

**Comment by lstrojny** [comment]
Thank you!
