### ISSUE TITLE
Build time is increased by 6x after upgrading from `>=5.1.1` to `5.2.0+`

### ISSUE THREAD

**Issue by surya-sigtech** [sphinx-doc/sphinx#12327]
### Describe the bug

When upgrading sphinx-build to the latest version (7.3.7), I noticed a significant increase in build time for generating HTML pages in our project. Upon further investigation, I found that the build time increases noticeably after upgrading to any version 5.2.0+.

**Observations:**
The build time for the exact same project and same configuration is:
- With version `5.1.1`, it is approx 2min 30sec
- With version `5.2.0`, it is approx 15mins (6 times more)

**Root Cause:**
Upon deeper investigation, I found that the commit [f57177d](https://github.com/sphinx-doc/sphinx/commit/f57177de89ff1a154c830558d218c3e334b2b437) is the cause of the issue. 
Specifically, the changes made to the function `build_toc` in file `sphinx/environment/collectors/toctree.py`.

Cc: @AA-Turner 

### How to Reproduce

1. Upgrade sphinx-build to version 7.3.7 or any version 5.2.0+.
2. Generate HTML pages using sphinx-build
Command: 
```
sphinx-build -b html -j auto ${base_path}/docs/source ${base_path}/html
```

### Environment Information

```text
Platform:              darwin; (macOS-14.2.1-arm64-arm-64bit)
Python version:        3.11.9 (main, Apr 19 2024, 11:43:47) [Clang 14.0.6 ])
Python implementation: CPython
Sphinx version:        7.4.0+/a66546895
Docutils version:      0.21.2
Jinja2 version:        3.1.3
Pygments version:      2.17.2
```

**Comment by surya-sigtech** [comment]
Just tried disabling it by adding it to my `conf.py`. 
Still the same.

**Comment by surya-sigtech** [comment]
Just tried disabling it by adding it to my conf.py.
Using latest sphinx version, it's working 👍
Thanks man!! @AA-Turner 

Build time now is **4min 55sec**
It's taking a bit more time while **reading sources** with new versions (not sure after which one).

**Comment by surya-sigtech** [comment]
I'm wondering if there are any additional configurations we could adjust to further improve the build time.

With disabling the `toc_object_entries` flag for my project, 

- Prior to version `<6.0.0`, the build time averaged around 2min 30 sec
- However, after version `>=6.0.0`, it increased ranging from 4min 50sec to 5min 50sec (approximately twice as before).

Any insights on potential configuration adjustments or optimizations would be greatly appreciated.

**Comment by chrisjsewell** [comment]
> I'm wondering if there are any additional configurations we could adjust to further improve the build time.

Been looking into this a bit for sphinx-needs: https://github.com/useblocks/sphinx-needs/discussions/967#discussion-5526873

One thing is to set: `smartquotes = False` as that is a big time kill (although in the newest docutils release I added some improvements to this)

Also looking to eventually improve multi-processing performance: https://github.com/sphinx-doc/sphinx/pull/11746

Happy to hear about more reports like this though!

**Comment by surya-sigtech** [comment]
Appreciate the pointers, @chrisjsewell 

I've taken a look at the other issues you mentioned, yet I'm still struggling to pinpoint what's causing such a drastic increase in build time with the latest versions. I've noticed a substantial slowdown with sphinx-build post **version 6.0.0**, with the build process now taking **more than twice as long** as it did previously.

This slowdown is concerning, as we'd like to leverage the latest features, but the performance hit is making it impractical. Any further insights will be really helpful.
