### ISSUE TITLE
Should `defusedxml` be moved to the runtime dependencies?

### ISSUE THREAD

**Issue by befeleme** [sphinx-doc/sphinx#12339]
### Describe the bug

In pyproject.toml, defusedxml is defined as one of the test dependencies: https://github.com/sphinx-doc/sphinx/blob/master/pyproject.toml#L97
However, in Sphinx 7.3.x its import was added to `sphinx/testing/util.py` (https://github.com/sphinx-doc/sphinx/commit/885818bb7f63783ac93ff2f81bb50fe5a1cb5831). Many sphinx plugins use that code in their test suites and break.
Should it be moved to the list of runtime dependencies?

### How to Reproduce

```
(venv)$ pip install sphinx
(venv)$ git clone git@github.com:sphinx-doc/sphinxcontrib-devhelp.git && cd sphinxcontrib-devhelp
(venv)$ tox
 <snip>
  File "~/sphinxcontrib-devhelp/.tox/py313/lib/python3.13/site-packages/sphinx/testing/util.py", line 14, in <module>
    from defusedxml.ElementTree import parse as xml_parse
ImportError: Error importing plugin "sphinx.testing.fixtures": No module named 'defusedxml'
```

### Environment Information

```text
sphinx 7.3.x
```

**Comment by jdillard** [comment]
I asked a similar question here: https://github.com/orgs/sphinx-doc/discussions/12333

Happy to close the discussion if this is a better place.

**Comment by picnixz** [comment]
No, but we should have a better tox.ini which would setup the environment correctly.

**Comment by picnixz** [comment]
Ok, I see what happened actually. It's because the dependencies of *sphinxcontrib-* were not updated accordingly, namely we are installing `sphinx` as `sphinx` (so we are only using the release dependencies and not the test dependencies for `sphinx`).

Is there a way to tell tox to install the sphinx *test* dependencies in `tox.ini`?

**Comment by chrisjsewell** [comment]
> Now, I am willing to actually split the test dependencies into dev and test 

yes this is what should happen; I was about to say, your first responses seemed to be conflating sphinx internal development with the actual opened issue of users interacting with `sphinx.testing.fixture` 😅

(in general, it is a bit of an open question in python packaging, where/how you define internal development dependencies vs defining extra user dependencies)

**Comment by mgorny** [comment]
I think it would also be useful to avoid importing `defusedxml` in global scope. It is only used by `etree_parse()`, and not every consumer of `sphinx.testing` uses this function.

For example, `breathe` is currently broken by this. However, it does not use this API and without the `import` in global scope, it doesn't have to be updated to depend on `defusedxml` (or `sphinx[dev]`, as suggested above).
