### ISSUE TITLE
Untranslatable strings

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1235]
The content of some tags are untranslatable (do not appear on .pot files). Examples:
- meta
- raw

In addition, embedded code (e.g. php) is also untranslatable. I understand some syntax could solve this, but it is unclear to me how to use it.
This is a blocker for multilanguage websites.
Does http://jinja.pocoo.org/docs/extensions/#i18n-extension help?

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1235
- Originally reported by: [pcav](https://bitbucket.org/pcav)
- Originally created at: 2013-08-16T11:28:30.336

**Comment by shimizukawa** [comment]
_From [pcav](https://bitbucket.org/pcav) on 2013-08-16 09:34:46+00:00_

Even more serious:

.. toctree::

**Comment by shimizukawa** [comment]
_From [pcav](https://bitbucket.org/pcav) on 2013-08-16 14:20:37+00:00_

Also:

.. image::

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2013-08-16 16:54:31+00:00_

Why `.. toctree::` and `.. image::` need translation?

**Comment by shimizukawa** [comment]
_From [pcav](https://bitbucket.org/pcav) on 2013-08-16 16:56:48+00:00_

Unsure about toctree; my case for image:
.. image:: images/jobs_map.jpg
   :alt: Faunalia job locations
   :target: http://www2.faunalia.eu/map/lizmap/www/index.php/view/map/?repository=faunalia&project=faunalia_map_it

I need to put a different link for different languages

**Comment by shimizukawa** [comment]
_From [pcav](https://bitbucket.org/pcav) on 2013-08-16 16:58:54+00:00_

toctree should be for making navigation menus translatable

**Comment by shimizukawa** [comment]
_From [pcav](https://bitbucket.org/pcav) on 2013-08-16 17:02:16+00:00_

Unclear to me whether the jinja approach could solve this, and how.

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2013-08-16 17:04:22+00:00_

Ah, OK. It is necessary, but is difficult to determine the rules for all other directives.

**Comment by shimizukawa** [comment]
_From [pcav](https://bitbucket.org/pcav) on 2013-08-18 16:50:32+00:00_

Same thing for the footer.

**Comment by shimizukawa** [comment]
_From [paolo_cavallini](https://bitbucket.org/paolo_cavallini) on 2013-08-26 15:41:04+00:00_

Footer is solved in Sphinx 1.2 by using {{ gettext('text') }} in layout.html
Manus must be defined by hand in layout, then they are also translatable.
Main remaining issues I have are  .. raw:: html and .. image:: blocks, where the above syntax does not seem to work: any workaround or fix?
Thanks a lot.

**Comment by shimizukawa** [comment]
_From [gioman](https://bitbucket.org/gioman) on 2013-09-03 15:42:57+00:00_

It would be nice to have also anchors as translable text.

**Comment by shimizukawa** [comment]
_From [pcav](https://bitbucket.org/pcav) on 2013-10-02 03:49:00+00:00_

Yes, untranslatable anchors are a problem: any plans to fix that?

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2013-10-02 04:17:43+00:00_

I think many translators will wish this feature.

Probably it will be provided by 1.3.

**Comment by shimizukawa** [comment]
_From [pcav](https://bitbucket.org/pcav) on 2013-10-02 04:19:19+00:00_

Thanks. Any roadmap for this, or possible time frame?

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2013-10-02 04:29:53+00:00_

It is not decided yet.

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2013-10-03 14:04:27+00:00_

From #1265, add "labeled reference target" such as:

```
#!rst

Python is the one of `light weight language`_ .

.. _light weight language: http://en.wikipedia.org/wiki/Lightweight_programming_language
```

`light weight language` is not translatable.

**THIS FEATURE WAS IMPLEMENTED.** see #1265.

**Comment by shimizukawa** [comment]
In this ticket, I'll try to do for these targets:
- image directive url, alt, title
- raw directive content
- literal block (`::`) content
- code-block content

All of this should be option as `gettext_enables` conf.py parameter.

**Comment by shimizukawa** [comment]
Now, gettext_additional_targets conf.py option allow to translate `literal-block`, `doctest-block`, `raw`, `image`. For detail, please refer to https://raw.githubusercontent.com/sphinx-doc/sphinx/bb85c1c87f27e15011a74cf15c00d4867def135e/doc/config.rst

toctree is bit difficult for now, it will be developed at #1734.

**Comment by fpatz** [comment]
A typical use case for "translating" image directives are images that contain text (say UI screenshots). It would be handy to have Sphinx search for `<image path>.<lang>.*` (or similar) and use that instead of `<image path>.*` for a particular language if a language specific image file exists. This issue doesn't address something like this, right? We'd roll our own extension to support that, but I'd love to see this in the standard. We could provide a PR that implements this, if it would be welcome.

**Comment by shimizukawa** [comment]
@fpatz Thanks! if you create a PR, I'll take a look.

**Comment by benallard** [comment]
@fpatz : I'd also welcome such an extension / feature ! Made some progress on that side ?

**Comment by fpatz** [comment]
@benallard: thanks for reminding me! I have pushed the change I came up with into a fork here: 151dd5c3a9ea4c898844352274d6154ab225357a 
This basically allows for referencing config values from image file names like in `my-image-{language}.png`. I think my patch is a little too generic and obviously underdocumented, so no PR yet. @shimizukawa Please let me know what you think of the variable interpolation approach and what you want to see in a viable pull request.

**Comment by benallard** [comment]
@fpatz: In the meantime, I wrote a very basic extension that look for filename.<lang>.extension, and use them if present, see #1921 for my version of that .

**Comment by fpatz** [comment]
Wow, that was quick! I don't know which approach is preferrable. Variable interpolation may be useful for other cases also. At least that was, why I did it that way.
