### ISSUE TITLE
toc_object_entries uses language (Python) scoping instead of documentation scoping

### ISSUE THREAD

**Issue by jakobandersen** [sphinx-doc/sphinx#12352]
### Describe the bug

The entries added by ``toc_object_entries`` for Python (and other domains?) seems to use the scoping of the language to nest the toc entries, instead of how they were declared in the document. E.g., if a nested class is declared after the class, then its entry is nested inside the class instead of appended.

### How to Reproduce

E.g., with
```rst
.. py:currentmodule:: myMod
.. py:class:: MyClass

	.. py:method:: f()

.. py:class:: MyClass.MyNestedClass
```
I get the toc
```
- MyClass
  - MyClass.f()
  - MyClass.MyNestedClass
```
instead of
```
- MyClass
  - MyClass.f()
- MyClass.MyNestedClass
```

### Environment Information

```text
Tested with current master.
```

### Additional context

Could the check at https://github.com/sphinx-doc/sphinx/blob/88a54d8a1394b09c7425d7a5bfebae55ab615d32/sphinx/environment/collectors/toctree.py#L146 be changed to check if the parent in the language is also the parent in the current toctree generation?

**Comment by electric-coder** [comment]
Being a directive shouldn't `currentmodule` also have an empty line and one level of nesting? Like this:

```rst
.. py:currentmodule:: myMod

	.. py:class:: MyClass

		.. py:method:: f()

	.. py:class:: MyClass.MyNestedClass
```

**Comment by jakobandersen** [comment]
> Being a directive shouldn't `currentmodule` also have an empty line and one level of nesting? Like this:

The ``currentmodule`` has no content, but simply sets the module. However, if you use ``module`` with content, then it's equivalent to the original example, and produces the wrong TOC as well.

> To get the nested class I'd rely only on reST scoping rules so it seems the most robust and language agnostic solution would be to put `f()` and `MyNestedClass` on the same level:

Generally I agree that showing them nested is a good default. However, in the original use-case there are multiple nested classes and all involved classes are relatively large, making it desirable to separate them.
