### ISSUE TITLE
Internationalization doc mentions deprecated transifex-client

### ISSUE THREAD

**Issue by rffontenelle** [sphinx-doc/sphinx#12363]
### Describe the bug

In the [Internationalization](https://www.sphinx-doc.org/en/master/usage/advanced/intl.html) page, the [Using Transifex service for team translation](https://www.sphinx-doc.org/en/master/usage/advanced/intl.html#using-transifex-service-for-team-translation) section tells to use the Python-based transifex-client, however it is deprecated. Quoting the info on the new  tool:

> Please start using the new Transifex CLI [here](https://github.com/transifex/cli) , since this software is considered deprecated (as of January 2022) and will sunset on Nov 30, 2022.

The new Transifex tool is written in Go, commonly named "Transifex CLI tool" , that has almost the same options (tx pull, tx push, etc.) and has the same binary name `tx`. The installation and usage instructions can be found in the documentation (https://developers.transifex.com/docs/cli) and source code repository (https://github.com/transifex/cli)

The section needs to be updated with this information.

### How to Reproduce

It doesn't apply to the issue

### Environment Information

```text
It doesn't apply to the issue
```

**Comment by chrisjsewell** [comment]
Heya, It would be great if you could open a PR 😄
