### ISSUE TITLE
Error prone `Cross-referencing arbitrary locations`

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1236]
Please, add a note to the `Cross-referencing arbitrary locations` to noticing
that the ref definition must have an initial underscore that is not present in
the referencing. Now is very difficult to realize that.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1236
- Originally reported by: Anonymous
- Originally created at: 2013-08-16T12:17:54.047

**Comment by tk0miya** [comment]
Fixed by #3905
