### ISSUE TITLE
External Link Footnotes Not Working in Definition List

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1237]
When a definition list term is an external link, and the "latex_show_urls" option is set to "footnote", the generated PDF shows the footnote number next to the link, but fails to create a footnote at the bottom of the page.

The generated LaTeX looks like this:

```
#!latex

\item[{\href{http://sphinx-doc.org}{Sphinx Website}\footnote{http://sphinx-doc.org}}] \leavevmode

```

If you change it to look like the following, then the footnote shows up a the bottom, but the number is a space away from the link:

```
#!latex

\item[{\href{http://sphinx-doc.org}{Sphinx Website}}]\footnote{http://sphinx-doc.org} \leavevmode
```

I'm not fluent in LaTeX, so there might be a better solution that keeps the number next to the link while producing the footnote.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1237
- Originally reported by: Anonymous
- Originally created at: 2013-08-16T15:04:39.303

**Comment by tk0miya** [comment]
Fixed at #2159.
