### ISSUE TITLE
Add option to disable transformation of straight to smart quotes in PDF output

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1239]
See [Pyramid Issue 669](https://github.com/Pylons/pyramid/issues/669)

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1239
- Originally reported by: Steve Piercy
- Originally created at: 2013-08-19T01:25:38.039

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2014-03-25 09:36:27+00:00_

These straight quotes are changed by latex itself, and with changeset 92577b1cbfe3 this is fixed.

**Comment by shimizukawa** [comment]
_From Steve Piercy on 2014-03-25 11:04:51+00:00_

Thank you!

**Comment by Kraymer** [comment]
Apparently the fix has been shipped with sphinx 1.2.3 but that's the version I use and my  

```
``block``
```

code blocks continue to be printed with fancy quotes in the output pdf.
Any idea why?

**Comment by petsuter** [comment]
> These straight quotes are changed by latex itself, and with changeset 92577b1cbfe3 this is fixed.

I appears this was the Mercurial changeset. After the conversion to Git this is now  commit 53abebda699551a460bb0b8e60982304e5b96415
