### ISSUE TITLE
Use a dataclass for extension metadata

### ISSUE THREAD

**Issue by timhoffm** [sphinx-doc/sphinx#12467]
Using a dict (even when codified via types #12153) feels vague, and information is scattered:
- defaults (missing values) are resolved in different parts throughout the code
- types are defined in `typing.ExtensionMetadata`
- semantics are described in docs https://www.sphinx-doc.org/en/master/extdev/index.html#extension-metadata

IMHO this could be made more robust and obvious by using a dataclass `sphinx.extension.ExtensionMetaInfo`; i.e. extension authors could write:

```
from sphinx.extension import ExtensionMetaInfo

def setup(app: Sphinx) -> ExtensionMetaInfo:
    ...
    return ExtensionMetaInfo(
        version="1.0",
        parallel_read_safe=True,
    )
```

**Backward compatibility**:
This would be a long-term migration. We'd need to support both the current `ExtensionMetadata` dict and the new `ExtensionMetaInfo` dataclass as return values of extension setup.py (that's one coersion step inside `load_extension()`). Extension authors may not be able to immediately switch to the new dataclass if they want to support older versions of sphinx. However, if we go into the lead with supporting both APIs, a migration can happen evolutionary, and if desired we could also phase out the dict support in far-future versions.

Let me know what you think. If this is desirable, I could craft a PR. But I can also understand if you say that it's too much churn for too little gain.

**Comment by electric-coder** [comment]
> IMHO this could be made more robust and obvious by using a dataclass

Up until recently dataclasses were an incomplete type with essential features missing in its specification, e.g. before the introduction in Python 3.10 of `[KW_ONLY](https://docs.python.org/3/library/dataclasses.html#dataclasses.KW_ONLY)` some basic signatures couldn't be sufficiently expressed.

So the Sphinx devs made the right call back then in not adopting that type immediately.

**Comment by timhoffm** [comment]
To be clear, I'm not saying anybody did something wrong. There are aways good reasons why decisions are made in a certain way. This is just an open question whether we should move one step further.

**Comment by chrisjsewell** [comment]
Heya, thanks for the write-up, but I'm going to say no on this for now.

In a perfect world, yes we would use a dataclass,
but as you mentioned, this would then mean a protracted period of support for both formats, adding:

1. A burden to core maintainers
2. A burden on extension maintainer to update and also support both (usually they are supporting multiple sphinx versions)

I just don't feel the benefits outweigh this
(particularly when there are plenty more "impactful" things to work on in Sphinx)

`ExtensionMetaInfo` was only just added (by me) and I feel it strikes a good middle ground; for providing more help to extension developers, whilst not altering the API in any way
