### ISSUE TITLE
i18n: Highlight untranslated paragraphs

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1246]
I would like to mark paragraphs that are missing translation with an additional css class. Comments in the code ( https://github.com/sphinx-doc/sphinx/blob/88c72be190afd98cc1619624ae37b8955f393e97/sphinx/transforms.py#L183 ) suggest that this idea is not new.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1246
- Originally reported by: [defnull](https://bitbucket.org/defnull)
- Originally created at: 2013-08-26T20:33:10.370

**Comment by lehmannro** [comment]
Idea from @JulienPalard:  Not only highlight but also allow jumping directly to the translation instructions/portal.

**Comment by humitos** [comment]
This will be possible in Sphinx 7.0.1 thanks to #11502. That PR has a link to an example about how to do exactly what the description of this issue mentions (use CSS to highlight untranslated paragraphs). I think we can probably close this issue as well.

**Comment by shimizukawa** [comment]
Sounds good! Now I will close this ticket. Thanks.

**Comment by humitos** [comment]
@AA-Turner yes. Do you have a page in mind where it could be a good place for it?

**Comment by AA-Turner** [comment]
``doc/usage/advanced/intl.rst``?
