### ISSUE TITLE
Support adding a target to a link (to open in new tab)

### ISSUE THREAD

**Issue by dylanh724** [sphinx-doc/sphinx#12477]
**Is your feature request related to a problem? Please describe.**

> In 1997, HTML 4.0 first introduced external links 

In 2024, you generally don't need to deep Google just to see if they support external links, a feature as old as the internet. This seems to possibly be the only web project that has no native external link support: I believe it's time. 

**Describe the solution you'd like**

Please include native support for external links opposed to dirty js workarounds.

**Describe alternatives you've considered**

Creating a custom .js file.

**Comment by chrisjsewell** [comment]
Heya, I'm afraid you are going to be more specific here:
what is the use-case, what exactly is it that you want to achieve?

**Comment by dylanh724** [comment]
> Heya, I'm afraid you are going to be more specific here:
> what is the use-case, what exactly is it that you want to achieve?
> 

Currently, all links are internal from the same browser tab. The feature request is for an equivalent of html target=new (new tab).

**Comment by electric-coder** [comment]
> The feature request is for an equivalent of html link target="_new" (new tab).

This is one of those cases where browser tech with right+click "open in new tab" ends up giving almost the same result.

> This seems to possibly be the only web project that has no native external link support: I believe it's time.

I suppose it would be a pretty dope feature to have in Sphinx core. However, I don't know of another documentation generation tool that's open source, multi-language, tries to support the whole Python ecosystem, and has a ton of free features like search, automatic index, i18n , etc... And actually works as well as Sphinx does.

This leads me to think that the builtin nicety that's "open link in new tab" was never considered a priority by the community because simple workarounds are available, but pretty much every other feature/fix in Sphinx would leave devs without viable alternatives elsewhere.

Did someone in the ecosystem write a custom extension that allows this? Is there some previous work somewhere?

**Comment by chrisjsewell** [comment]
Well, actually, I believe this is already in myst-parser 😉  https://github.com/executablebooks/MyST-Parser/pull/857

and sphinx already supports having a `target` attribute on a `reference` node: https://github.com/sphinx-doc/sphinx/blob/f85f50e52614c627adbcf43629ca028829454081/sphinx/writers/html5.py#L324-L325
(not a `rel` though I don't think 🤔)

So then, for reStructureText, it just depends how do you want to set `target`: I believe you could already add a `Transfrom` that adds it to all `reference` nodes if you want

**Comment by electric-coder** [comment]
@chrisjsewell a couple of old SO threads [Add open-in-new-tab links in Sphinx/reStructuredText](https://stackoverflow.com/questions/25583581/add-open-in-new-tab-links-in-sphinx-restructuredtext) and [Open a link in a new window in reStructuredText](https://stackoverflow.com/questions/11716781/open-a-link-in-a-new-window-in-restructuredtext) which has an answer from SHIMIZUKAWA himself :) linking back to #1634

**Comment by jayaddison** [comment]
@dylanh724 have you encountered https://github.com/ftnext/sphinx-new-tab-link ?  I think it might do what you want here - it's an extension (available on PyPi) that processes hyperlinks in your project and adds `target="_blank"` (and also `rel="noopener noreferer"`) to the external ones.  I also notice in their bugtracker that there's a feature request to add custom HTML styling for those.

**Comment by dylanh724** [comment]
> @dylanh724 have you encountered https://github.com/ftnext/sphinx-new-tab-link ? I think it might do what you want here - it's an extension (available on PyPi) that processes hyperlinks in your project and adds `target="_blank"` (and also `rel="noopener noreferer"`) to the external ones. I also notice in their bugtracker that there's a feature request to add custom HTML styling for those.

Great find! Thank you! It's up to you guys whether you want to keep this open or closed: Closed since I'm satisfied, or open if you wanted to absorb it into your main product (it still feels strange this isn't a native feat!). Cheers!

**Comment by electric-coder** [comment]
> (it still feels strange this isn't a native feat!)

It seems there are **accessibility** concerns over the feature, as one of the more experienced maintainers said [here](https://github.com/sphinx-doc/sphinx/issues/1634#issuecomment-68592349). (IOW it might work fine for the average user but would be problematic for folks using screen readers...)

> In another point of view, accessibility guideline recommended that target attribute should not be used until user agents allow users to turn off spawned windows [1]_.
>
> .. [1] http://www.w3.org/TR/2000/NOTE-WCAG10-TECHS-20001106/#gl-interim-accessibility

Noting the W3C recommendation against it, more specifically:

> [12.6 Page updates and new windows](https://www.w3.org/TR/WCAG10-HTML-TECHS/#script-refresh)
>
> [10.1](https://www.w3.org/TR/WCAG10-TECHS/#tech-avoid-pop-ups) Until user agents allow users to turn off spawned windows, do not cause pop-ups or other windows to appear and do not change the current window without informing the user. [Priority 2]

**Comment by jayaddison** [comment]
Not planned as a feature for core `sphinx`, although as noted during discussion, there are extensions available that may be able to help on a per-project basis.
