### ISSUE TITLE
make html not working 

### ISSUE THREAD

**Issue by DarureTej** [sphinx-doc/sphinx#12482]
### Describe the bug

I was able to create all the rst files, changed the conf file, added modules in  index file . But when I do .\make.bat html nothing happens. Doesn't give any error or produces any file in build. I am vscode 1.90, python 3.11. 
![image](https://github.com/sphinx-doc/sphinx/assets/23451102/76716ad3-6ec1-4aa1-9b87-58d6db9bd2fb)

### How to Reproduce

![image](https://github.com/sphinx-doc/sphinx/assets/23451102/14e6eb52-df67-48f1-95b7-0b98b6b1f231)

### Environment Information

```text
vscode 1.90, python 3.11. terminal: window powershell
```

**Comment by electric-coder** [comment]
I advise not using PowerShell terminal. Try CMD as that's what `make.bat` was originally written for. There has been a pull request to convert the makefile to a powershell script but the PR was never completed.

**Comment by jayaddison** [comment]
@DarureTej if using PowerShell, could you try running:

```sh
> Set-Item env:SPHINXOPTS "-D language=de"
> .\make.bat html
```

We mention the `Set-Item` step for PowerShell in some of our ['advanced usage' documentation](https://www.sphinx-doc.org/en/master/usage/advanced/intl.html#quick-guide), but not elsewhere as far as I can tell.  That might be something we can improve.

**Comment by jayaddison** [comment]
In rapid hindsight: that probably shouldn't make a difference at all - there should be a default language configuration, so `Set-Item` shouldn't be needed.

**Comment by jayaddison** [comment]
Unfortunately I don't have access to a system with PowerShell on it at the moment, so my ability to help here may be limited.  One thing that I would be curious about is what kind of output running the `sphinx-build` command from the shell (without any arguments) does.

**Comment by jayaddison** [comment]
We'd need more information to be able to figure out what happened in this case; if you still believe there's a bug that we should investigate, please let us know.  Information about available sources of help for Sphinx can be found on the project's website here: https://www.sphinx-doc.org/en/master/internals/contributing.html#get-help
