### ISSUE TITLE
Sphinx v7.4.0: Failed to get a method signature: unhashable type

### ISSUE THREAD

**Issue by sphuber** [sphinx-doc/sphinx#12579]
### Describe the bug

When installing `sphinx=7.4.0` that was just released, using the `typing.ParamSpec` results in the following warning:
```
WARNING: Failed to get a method signature for thing.ProcessFunctionType.run: unhashable type: 'ParamSpecArgs'
```

### How to Reproduce
`conf.py`
```
import os
import sys
sys.path.insert(0, os.path.abspath('../src'))

extensions = ['sphinx.ext.autodoc']
```
`index.rst`
```
.. automodule:: thing
   :members:
```
The following source file
```python
import typing as t

P = t.ParamSpec('P')
R_co = t.TypeVar('R_co', covariant=True)
N = t.TypeVar('N', bound=str)


class ProcessFunctionType(t.Protocol, t.Generic[P, R_co, N]):
    """Protocol type."""

    def run(self, *args: P.args, **kwargs: P.kwargs) -> R_co:
        """Some method."""
```
compiled with Sphinx v7.4

### Environment Information

```text
Only happens for `sphinx==7.4.0`. Builds fine with older versions
```

### Sphinx extensions

```python
sphinx.ext.autodoc
```

**Comment by AA-Turner** [comment]
@sphuber please can you provide the ``index.rst`` and the ``conf.py`` for the minimal example?

**Comment by sphuber** [comment]
@AA-Turner done

**Comment by AA-Turner** [comment]
Simpler reproducer:

```python
from typing import ParamSpec

from sphinx.util.typing import stringify_annotation

def test_stringify_paramspec():
    P = ParamSpec('P')
    stringify_annotation(P.args, 'smart')
    stringify_annotation(P.kwargs, 'smart')
```

The first issue is that ``ParamSpecArgs`` isn't hashable, and hence ``annotation in {None, NoneType}`` raises a ``TypeError``. The second is that ``ParamSpecArgs`` has no ``__name__`` or ``__qualname__`` (though it does have ``__module__``). This will be slightly harder, though I admit I'm not sure why the name attributes don't exist.

A

**Comment by AA-Turner** [comment]
[Sphinx 7.4.1](https://pypi.org/project/Sphinx/7.4.1/) has been released with a fix.

A

**Comment by sphuber** [comment]
Can confirm that 7.4.1 fixes the issues, thanks a lot for the very quick resolution!

**Comment by AA-Turner** [comment]
Glad to be of service!

A
