### ISSUE TITLE
Sphinx 7.4.0 breaks parsing of MyST-Parser (and probably others) configuration in conf.py

### ISSUE THREAD

**Issue by jfbu** [sphinx-doc/sphinx#12582]
### Describe the bug

Bad output:
![Capture d’écran 2024-07-15 à 12 11 14](https://github.com/user-attachments/assets/7a1263de-4fab-47db-bef3-4f1b67287bfe)

Good output:
![Capture d’écran 2024-07-15 à 12 10 44](https://github.com/user-attachments/assets/f863767b-3736-432f-8be0-191898d73136)

### How to Reproduce

`conf.py`:

```
extensions = ['myst_parser',
]

myst_enable_extensions = ["colon_fence"]
source_suffix = ['.rst', '.md']
```

`index.md`:

```
# La FAQ LaTeX francophone !


:::{only} html
Hello
:::

## Section

:::{admonition} Here's my title
:class: tip

Here's my admonition content.
:::
```

### Environment Information

Git bisect blames 82edc3d38

```text
Running Sphinx v7.4.0+/82edc3d38
Sphinx version: 7.4.0+/82edc3d38
Python version: 3.12.3 (CPython)
Docutils version: 0.20.1 
Pygments version: 2.18.0
Jinja2 version: 3.1.4
MyST-parser version: 3.0.1
```

### Sphinx extensions

```python
extensions = ['myst_parser',
]

myst_enable_extensions = ["colon_fence"]
source_suffix = ['.rst', '.md']
```

**Comment by jfbu** [comment]
I am sorry I did not catch that, but right priori to 7.4.0 release I was on my PR #12508 branch all of the time and did use it on big project regularly until a few days agoa and clearly the branch was without the bad commit.  Perhaps at very end it did after I the one or two merges of master I did (not checked that speaking hypothetically) but at this stage (last two days) I was only compiling via latexpdf some small testing project for finalizing admonition styles and was not using Markdown/MyST-Parser for input.

**Comment by AA-Turner** [comment]
Your [``source_suffix``](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-source_suffix) should ideally be:

```python
source_suffix = {
    '.rst': 'restructuredtext',
    '.md': 'markdown',
}
```

However the list-style has not yet been fully deprecated and removed, so I will restore support.

**Comment by jfbu** [comment]
@AA-Turner Indeed! I fetched that config from the big project where the problem was first detected! Issue is much less serious I first thought then...

**Comment by AA-Turner** [comment]
[Sphinx 7.4.3](https://pypi.org/project/Sphinx/7.4.3/) has been released with a fix.

A
