### ISSUE TITLE
Sphinx v7.3.7: AttributeError: 'Symbol' object has no attribute '_children'

### ISSUE THREAD

**Issue by sphuber** [sphinx-doc/sphinx#12580]
### Describe the bug

The example Python source file (see in how to reproduce) excepts when compiled with Sphinx 7.3.7. Any other older version works just fine. It excepts with the following error:
```
Exception occurred:
  File "/home/sph/.mambaforge/envs/aiida-py311/lib/python3.11/site-packages/sphinx/domains/c/_symbol.py", line 179, in get_all_symbols
    for sChild in self._children:
                  ^^^^^^^^^^^^^^                                                                                                                                                                                 AttributeError: 'Symbol' object has no attribute '_children'
```

### How to Reproduce
`conf.py`
```
import os
import sys
sys.path.insert(0, os.path.abspath('../src'))

extensions = ['sphinx.ext.autodoc']
```
`index.rst`
```
.. automodule:: thing
   :members:
```
```python
import typing as t

P = t.ParamSpec('P')
R_co = t.TypeVar('R_co', covariant=True)
N = t.TypeVar('N', bound=str)


class ProcessFunctionType(t.Protocol, t.Generic[P, R_co, N]):
    """Protocol type."""

    def run(self, *args: P.args, **kwargs: P.kwargs) -> R_co:
        """Some method."""
```
build it Sphinx v7.3.7

### Environment Information

```text
sphinx==7.3.7
```

### Sphinx extensions

```python
sphinx.ext.autodoc
```

**Comment by AA-Turner** [comment]
@sphuber please can you provide the ``index.rst`` and the ``conf.py`` for the minimal example?

**Comment by sphuber** [comment]
@AA-Turner done

**Comment by AA-Turner** [comment]
@sphuber with the patch from #12581 I'm unable to reproduce -- I'd expect a C or C++ domain directive given that the error is in the C domain. Please could you double check the reproducer?

A

**Comment by AA-Turner** [comment]
Is Sphinx 7.4.0 also broken for this?

**Comment by nortikin** [comment]
https://github.com/nortikin/sverchok/actions/runs/9937287904/job/27447450138 also

**Comment by AA-Turner** [comment]
Are you able to create a minimal reproducer please @nortikin? This error is a little confusing, as ``_children_by_docname`` should always be defined:

https://github.com/sphinx-doc/sphinx/blame/73dd9fcb9b9d29867754d5a220100ae6c1f4f972/sphinx/domains/c/_symbol.py#L108

A

**Comment by sphuber** [comment]
> Is Sphinx 7.4.0 also broken for this?

I don't think so, because I don't get the exception there, just the warning reported in #12579

**Comment by sphuber** [comment]
It may have to do something with caching of compiled files. If I build clean, it seems to work just fine. The exception seems to crop up if I first compile with v7.4.1, then downgrade to v7.3.7 and build again. If I clean the old build before building again, v7.3.7 seems to work fine. So this may be a non-issue

**Comment by AA-Turner** [comment]
I came to the same conclusion -- see #12583 for a fix (by invalidating old environments)

**Comment by AA-Turner** [comment]
[Sphinx 7.4.2](https://pypi.org/project/Sphinx/7.4.2/) has been released with a fix.

A
