### ISSUE TITLE
Sphinx 7.4: autodoc: ``typing.Annotated`` failure with pydantic

### ISSUE THREAD

**Issue by AA-Turner** [sphinx-doc/sphinx#12601]
I think I found a regression about this. We're using the `Annotated` class + pydantic to validate types of a user-defined config in conf.py...

```py
CSSClassType = Annotated[str, pydantic.AfterValidator(nodes.make_id)]

class CustomAdmonitionConfig(pydantic.BaseModel):
    title: Annotated[Optional[str], pydantic.Field(validate_default=True)] = None
    classes: List[CSSClassType] = []
```
But autodoc-ing `CustomAdmonitionConfig`'s `title` and `classes` attributes results in errors trying to reference the metadata:
> /opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/sphinx_immaterial/custom_admonitions.py:docstring of sphinx_immaterial.custom_admonitions.CustomAdmonitionConfig.title:1: WARNING: py:obj reference target not found: typing.Annotated[str | None, FieldInfo(annotation=NoneType, required=True, validate_default=True)]

> /opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/sphinx_immaterial/custom_admonitions.py:docstring of sphinx_immaterial.custom_admonitions.CustomAdmonitionConfig.classes:1: WARNING: py:obj reference target not found: typing.List[~typing.Annotated[str, AfterValidator(func=<function make_id at 0x7fd2a7b5cae0>)]]

I think lesson here is that not all metadata is compatible with autodoc. Is there a way to disable it?

_Originally posted by @2bndy5 in https://github.com/sphinx-doc/sphinx/issues/11785#issuecomment-2230045019_

**Comment by 2bndy5** [comment]
I'm not sure there's anything autodoc can do about this. Pydantic doesn't use sphinx to generate the their docs (sadly).

Honestly, this "feature" should be hidden behind a config option until if/when it is stable to use in autodoc.

**Comment by AA-Turner** [comment]
Hi @2bndy5 are you able to help with a reproducer? I currently have the below, which doesn't generate the cited warnings/errors:

``python
extensions = ['sphinx.ext.autodoc']
nitpicky = True
```

```rst
.. automodule:: bug
   :members:
```

```python
from typing import List, Optional, Annotated

from docutils import nodes
import pydantic

CSSClassType = Annotated[str, pydantic.AfterValidator(nodes.make_id)]


class CustomAdmonitionConfig(pydantic.BaseModel):
    title: Annotated[Optional[str], pydantic.Field(validate_default=True)] = None
    classes: List[CSSClassType] = []
```

A

**Comment by 2bndy5** [comment]
Example was taken straight from sphinx-immaterial docs. Maybe the theme does something extra to return types... I'll look into it.

**Comment by 2bndy5** [comment]
I haven't narrowed it down yet, but I was able to suppress the warnings using `autoattribute`'s `:annotation:` option:
```rst
   .. autoclass:: sphinx_immaterial.custom_admonitions.CustomAdmonitionConfig
      :exclude-members: __new__, __init__

      .. autoattribute:: name
      .. autoattribute:: title
         :annotation: : str | None
      .. autoattribute:: icon
      .. autoattribute:: color
      .. autoattribute:: classes
         :annotation: : List[str]
      .. autoattribute:: override
```

**Comment by 2bndy5** [comment]
I found the culprit. So, the sphinx-immaterial theme (in `sphinx_immaterial.apidoc.python.attribute_style`) monkey-patches the `handle_signature()` function of `sphinx.domains.python.PyAttribute` (and `PyProperty`) to

1. add a punctuation to the signature
   - `sphinx.addnodes.desc_sig_punctuation("", " : ")` for a type
   - `sphinx.addnodes.desc_sig_punctuation("", " = ")` for a value
2. convert the signature's type into xrefs using a monkey-patched `sphinx.domains.python._parse_annotation()`

I'll discuss a solution downstream. Sorry for not singling out the theme first. I'm not competent enough to understand all the monkey-patching that jbms does with the API domains.

@AA-Turner I can't close this myself.

**Comment by AA-Turner** [comment]
> That is unless the nitpicky_ignore field supports a glob or regex pattern of which I'm unaware.

Today is your lucky day: https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-nitpick_ignore_regex

A

**Comment by AA-Turner** [comment]
I would still be interested in a reproducer that has new failures on 7.4 compared to 7.3 so that I can release a fix, if you have one.

A

**Comment by 2bndy5** [comment]
I ended up factoring out our use of the `Annotated` class as an attribute type, at least for the documented API. Pydantic is refreshingly flexible. It just took a little more code to achieve the same behavior.
`
> Today is your lucky day

I'm glad to see I have multiple options to recommend others that may come across this (or a similar) problem. 👍🏼

> I would still be interested in a reproducer

You're example does reproduce it but it needs the `--fail-on-warning` option added to `sphinx-build` command. Just to be proper, I packaged it up into a zip file (with a requirements.txt file) and added to `:members:` for conciseness.

Steps: to reproduce
1. extract the zip: [issue#12601.zip](https://github.com/user-attachments/files/16279197/issue.12601.zip)
2. navigate to "issue#12601" directory
3. ```
   pip install -r requirements.txt
   ```
4. ```
   sphinx-build . ./_build -W --keep-going
   ```

> release a fix, if you have one.

I don't have a fix other than ways to avoid the warning. I just don't know the domain API well enough. Downstream, we were considering a theme-specific config option to help filter the transformations of type annotations (see [our docs](https://jbms.github.io/sphinx-immaterial/apidoc/python/index.html) for options already implemented), but nitpicky warnings are often ignored in the wild.

**Comment by AA-Turner** [comment]
I've made some progress and there is a mitigation we can apply, but part of the problem is with Pydantic.

Sphinx tries to parse a function annotation and from there convert the components within autodoc.

```pytb
>>> import ast
>>> annotation ='~typing.List[~typing.Annotated[str, AfterValidator(func=<function make_id at 0x0000020883233100>)]]'
>>> ast.parse(annotation, type_comments=True)
Traceback (most recent call last):
  File "S:\Development\sphinx\sphinx\domains\python\_annotations.py", line 207, in _parse_annotation
    tree = ast.parse(annotation, type_comments=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Micromamba\envs\sphinx\Lib\ast.py", line 52, in parse
    return compile(source, filename, mode, flags,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<unknown>", line 1
    ~typing.List[~typing.Annotated[str, AfterValidator(func=<function make_id at 0x0000020883233100>)]]
                                                            ^
SyntaxError: invalid syntax
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "S:\Micromamba\envs\sphinx\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-ce0ec65a4b87>", line 1, in <module>
    ast.parse('~typing.List[~typing.Annotated[str, AfterValidator(func=<function make_id at 0x0000020883233100>)]]', type_comments=True)
  File "S:\Micromamba\envs\sphinx\Lib\ast.py", line 52, in parse
    return compile(source, filename, mode, flags,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<unknown>", line 1
    ~typing.List[~typing.Annotated[str, AfterValidator(func=<function make_id at 0x0000020883233100>)]]
                                                            ^
SyntaxError: invalid syntax
```

Ideally, given that pydantic ought know that ``func`` is a function or callable, they would implement a custom ``__repr__()`` that returns ``f'{func.__module__}.{func.__qualname__}'``.

A

**Comment by 2bndy5** [comment]
Ideally for sphinx maybe, but is it really pydantic's responsibility to provide representation of function pointers specified from user-space?

I don't think falling back to `__repr__()` is the best last resort, especially if Python's by default implementation does not include the info that `ast.parse()` is looking for. It my understanding that the `ast` module's source is beyond the scope of Sphinx (as with the `inspect` module).

---
There is a similar problem with using an instantiated object as a parameter default value.
```py
# in defaults.py
class A:
    """Some class A doc"""
    pass

def some_fn(param: A = A()):
    """Some function doc"""
    pass
``` 

![image](https://github.com/user-attachments/assets/b50d3c07-e633-4701-82a4-16171c570ae9)

We've come across yet another seemingly similar problem in https://github.com/jbms/sphinx-immaterial/issues/140

**Comment by AA-Turner** [comment]
[Sphinx 7.4.5](https://pypi.org/project/Sphinx/7.4.5/) has been released with a fix.

A

**Comment by AA-Turner** [comment]
[Sphinx 7.4.7](https://pypi.org/project/Sphinx/7.4.7/) has been released with a fix.

A
