### ISSUE TITLE
modifying image files after a first `make latex` will cause next `make latex` to refuse the new ones since #12647 merge

### ISSUE THREAD

**Issue by jfbu** [sphinx-doc/sphinx#12656]
**update** the issue (which has changed title twice) is more serious (in terms of consequences, but fix seems easy) than initially thought, see [comment](https://github.com/sphinx-doc/sphinx/issues/12656#issuecomment-2245759876)

### Describe the bug

I have started seeing things like (hard-wraps manually added)
```text
WARNING: Aborted attempted copy from /pathtoclone/sphinx/sphinx/texinputs/sphinxlatexnumfig.sty
to 
/path/_build/latex/sphinxlatexnumfig.sty
(the destination path has existing data). [misc.copy_overwrite]
```

whenever I edit a file in `sphinx/sphinx/texinputs` from git clone checkout and execute `make latex` on a test project.

### How to Reproduce

git clone Sphinx, install it via `pip install -e.` into your local virtual env, create  a dummy test project via `sphinx-quickstart`, do `make latex` once, then start modifying a LaTeX support file [^1] in the git clone and try again `make latex`.

It is not the destination that has changed but the source, but that is a detail, nevertheless it is somewhat annoying as it forces `make clean` at each change we may want to test as part of developing a PR related to LaTeX.

[^1]: if you do this with Emacs/AUCTeX don't forget to set `TeX-auto-save` to nil, because the `auto/` directory will not be appreciated by next `make latex`, but this altogether different problem which has been here for ages. Edit: or customize once and for all `TeX-auto-local` to something such as `.auto`. Years of suffering have ended :smiley:.

### Environment Information

```text
Sphinx version: 8.0.0+/f90b506a9
Python version: 3.12.3 (CPython)
Docutils version: 0.20.1 
Pygments version: 2.18.0
Jinja2 version: 3.1.4
```

Admittedly changes to LaTeX support files may be done from inside the testing build repertory after initial `make latex` but this is a bit annoying as it is not under git supervision, one can not do `git stash` or similar things to save changes if they start accumulating.

**Comment by jayaddison** [comment]
@jfbu this seems to be an unintended side-effect of #12647 - fortunately there is a `force=True` flag that we may be able to use here to work around these warnings.

Based on the code it appears that the relevant content being referred to is static (that is, the output written to the destination doesn't change between builds, at least when using the same version of Sphinx).

I think the relevant `copy_asset_file` calls are here: https://github.com/sphinx-doc/sphinx/blob/61daf1c27cb0366181319e7771f4ff01f0e3ae27/sphinx/builders/latex/__init__.py#L411-L421

cc @AA-Turner as this seems worth noting/addressing before 8.x release?

**Comment by AA-Turner** [comment]
Yep, we should also make sure that this is covered by tests.

A

**Comment by jayaddison** [comment]
> then start modifying a LaTeX support file [1](#user-content-fn-1-4b32326a5657a370d422f098b3e19dcb) in the git clone

I'm puzzling over this part of the bug - this would be unexpected behaviour for most Sphinx deployments, wouldn't it?  Initially I thought that the editing related to documents in the project source, but learning more, it appears to be some `.tex` files, and they do not appear to be evaluated as templates (I could be mistaken there; still checking).

**Comment by jayaddison** [comment]
I might have to get some rest and have another think about it fresh tomorrow.

**Comment by jfbu** [comment]
> > then start modifying a LaTeX support file [1](#user-content-fn-1-4b32326a5657a370d422f098b3e19dcb) in the git clone
> 
> I'm puzzling over this part of the bug - this would be unexpected behaviour for most Sphinx deployments, wouldn't it? Initially I thought that the editing related to documents in the project source

Hi @jayaddison yes no urgency here! The change is mainly impacting my workflow for Latex maintenance. Definitely not something which is of concern to usual Sphinx usage, afaict.

There is a very positive aspect of this change: if you start fiddling with `.sty` files inside some `<builddir>/latex/` output repertory of some test project, then on next attempt at `sphinx-build -b latex` or `make latex`, there is now a warning and you do not lose your work, this is good.

Side remark: `<builddir>/latex/Makefile` and `<builddir>/latex/latexmkrc` are issued from `.jinja` templates and will be overwritten with no warning though, but this is understandable as the source is always different from end product, the source being a template.

I can live with the new state of affairs; being forced to a `make clean` is no big deal on a tiny test project and avoids sometimes annoying problems with left-over auxiliaries from previous latexpdf build.  The `make clean` (even limited to only latex builddir) is an inconvenience if testing say our own docs, as example of a somewhat upper-medium-sized project. Latex-PR authors can also do most of their development from inside the existing builddir and use there directly `make all-pdf` to check out changes, which I sometimes do.  But as I said it loses git convenience, but we can always do git init there. If however changes-to-be-tested are in sync with pure Python updates, then we have to go through a new `make latex` which now will have either to be `make clean latex` or be prefixed by a manual copy of modified file from Sphinx source repertory to project build repertory. I can surely add some shell-script to my environment to automatize this copy, and modify the sphinx-quickstart produced Makefile in project repertory to automatize even more, so this issue is not cause to delay 8.x.

**Comment by jfbu** [comment]
Only to confirm that with
```diff
index 705a9cca8..731f6669b 100644
--- a/sphinx/builders/latex/__init__.py
+++ b/sphinx/builders/latex/__init__.py
@@ -412,7 +412,7 @@ class LaTeXBuilder(Builder):
         for filename in os.listdir(staticdirname):
             if not filename.startswith('.'):
                 copy_asset_file(path.join(staticdirname, filename),
-                                self.outdir, context=context)
+                                self.outdir, context=context, force=True)
 
         # use pre-1.6.x Makefile for make latexpdf on Windows
         if os.name == 'nt':
```
I recover former behavior.

I can definitely keep this patch handy and apply it whenever I want to try out some LaTeX changes, no big deal.

**Comment by jfbu** [comment]
@jayaddison @AA-Turner Maybe we can use `force=True` for copying LaTeX assets in time for 8.0.0?

(I see the 8.0.0 milestone so I can take my time writing this...)

Indeed I realized the following regression: one can not use `latex_additional_files` anymore to override Sphinx LaTeX support files with one's own. Some years ago the `sphinx.sty` had started to grow big, so it was split into separate smaller files, the idea being that you may want to override some details of the smaller ones and sometimes the simplest is to overwrite the file.

# How to reproduce

```text
- Create a project with sphinx-quickstart
- Do `make latex`
- Copy from the builddir the `sphinxmanual.cls` file back to root repertory where conf.py is
- add `latex_additional_files = ['sphinxmanual.cls']` to conf.py
- do some edit in `sphinxmanual.cls` like modifying a comment or s/1995/1996/ in the LaTeX year version near top
- try again `make latex`
```

This triggers (sorry for French ;-))

```
Copie de fichiers supplémentaires...  sphinxmanual.clsWARNING: Aborted attempted copy from /path/to//12656_nooverwrite/sphinxmanual.cls to /path/to/12656_nooverwrite/_build/latex/sphinxmanual.cls (the destination path has existing data). [misc.copy_overwrite]
```

According to [our docs](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-latex_additional_files):

> Changed in version 1.2: This overrides the files provided from Sphinx such as sphinx.sty.

**Comment by jfbu** [comment]
This appears to fix it for me:
```diff
diff --git a/sphinx/builders/latex/__init__.py b/sphinx/builders/latex/__init__.py
index 705a9cca8..a930af0f5 100644
--- a/sphinx/builders/latex/__init__.py
+++ b/sphinx/builders/latex/__init__.py
@@ -412,19 +412,27 @@ class LaTeXBuilder(Builder):
         for filename in os.listdir(staticdirname):
             if not filename.startswith('.'):
                 copy_asset_file(path.join(staticdirname, filename),
-                                self.outdir, context=context)
+                                self.outdir, context=context,
+                                force=True
+                                )
 
         # use pre-1.6.x Makefile for make latexpdf on Windows
         if os.name == 'nt':
             staticdirname = path.join(package_dir, 'texinputs_win')
             copy_asset_file(path.join(staticdirname, 'Makefile.jinja'),
-                            self.outdir, context=context)
+                            self.outdir,
+                            context=context,
+                            force=True
+                            )
 
     @progress_message(__('copying additional files'))
     def copy_latex_additional_files(self) -> None:
         for filename in self.config.latex_additional_files:
             logger.info(' ' + filename, nonl=True)
-            copy_asset_file(path.join(self.confdir, filename), self.outdir)
+            copy_asset_file(path.join(self.confdir, filename),
+                            self.outdir,
+                            force=True
+                            )
 
     def copy_image_files(self) -> None:
         if self.images:
```

**Comment by jfbu** [comment]
Ooops situation is even worse: we can not modify image files anymore!

Add 

```
.. figure:: foo.png
   :name: somename

   some caption
```
 to your project.

Do `make latex`.

Modify the file `foo.png`.  Try again `make latex`:

WARNING: Aborted attempted copy from /path/to/12656_nooverwrite/foo.png to /path/to/12656_nooverwrite/_build/latex/foo.png (the destination path has existing data). [misc.copy_overwrite]

I am waving my arms here but I think people will have seen the red `regression` tag :smiley:

**Comment by jayaddison** [comment]
@jfbu I think the intent of #12647 was to raise a loud warning when a destination file is copied to twice during the same build.

The bug it resolves, #12096, was a case where an external theme relied on overwriting a file.  They worked around it by copying the file using a different event-handler, but it still seems problematic to allow an extension/something else to overwrite something you had intended to place into a build output.

What I think we should check here is: the files that warnings are appearing for: are they being written once, or more than once during each build?

If they are only been written once, then I think the warning logic may be broken and we should investigate that.  However: if they are being written twice, then that indicates a bug with the build process, not with the warning.

**Comment by jfbu** [comment]
@jayaddison I think they are copied once, I can check later, but now I report another aspect of the problem with the configuration variable `latex_logo`.  It allows to specify some logo to put on title page. The situation with current master is that you can't  edit the image file in-place in between two `make latex`.  You have to modify the value of `latex_logo` in conf.py and assign it some other image name.

And as I pointed out, the same issue applies to *any* image file used in a `figure` or `image` directive.  Once used, you are not allowed to modify it in the source repertory if you don't change the filename (hence have to update the sources).

The warning is counter-intuitive in thoses cases : `latex_logo`, `latex_additional_files`, image inclusions)  I am not aware of extensions which overwrite LaTeX support files or image files in the latex build directory, so I I don't know if there is a pre-existing problem to fix viz latex builder. Although I have not studied the original HTML-CSS issue closely, #12096, it looks as if for time being we could simply use `force=True` throughout the LaTeX builder Python code.  This has no impact whatsoever on HTML builds or other builders so it will not undo the fix of #12096.

**Comment by jfbu** [comment]
@jayaddison They are written once, I added `print('copying ...')` everywhere here is sample output

```console
copying TeX support files... copying TeX support files...
copying sphinxlatexstylepage.sty
copying sphinxlatexliterals.sty
copying LatinRules.xdy
copying LICRcyr2utf8.xdy
copying sphinxlatexstyletext.sty
copying LICRlatin2utf8.xdy
copying sphinxlatexgraphics.sty
copying sphinxmanual.cls
copying sphinxpackagecyrillic.sty
copying python.ist
copying sphinxlatexobjects.sty
copying make.bat.jinja
copying sphinxhowto.cls
copying sphinxlatextables.sty
copying sphinxlatexshadowbox.sty
copying sphinxlatexindbibtoc.sty
copying sphinx.sty
copying sphinxlatexstyleheadings.sty
copying sphinxoptionsgeometry.sty
copying sphinxpackagesubstitutefont.sty
copying sphinx.xdy
copying sphinxlatexlists.sty
copying sphinxlatexadmonitions.sty
copying Makefile.jinja
copying sphinxlatexnumfig.sty
copying latexmkrc.jinja
copying sphinxpackagefootnote.sty
copying sphinxoptionshyperref.sty
copying sphinxlatexcontainers.sty
copying sphinxpackageboxes.sty
copying latexmkjarc.jinja
done
copying additional files...  sphinxmanual.clscopying sphinxmanual.cls
done
processing foo.tex... index 
resolving references...
done
writing... done
copying foo.png.. [100%] foo.png

copying latex logo logo.png
build succeeded.
```

near end we see result of some `latex_additional_files`,  a `latex_logo` and the project used a figure directive with image file `foo.png`.

**Comment by jfbu** [comment]
Only now do I see (some years late) the duplicate

```console
copying TeX support files... copying TeX support files...
```

in console output (using current master). Seems to have been doing this for ages (at least since v2.0.0).  The `latex/__init__.py` contains both

```python
 @progress_message(__('copying TeX support files'))
```

and 

```python
logger.info(bold(__('copying TeX support files...')))
```

I am not sure of the semantics here but could it have been oversight at 66353b333067a to have kept the `logger.info()` at that place? Or maybe it was to support earlier Python and was kept?
