### ISSUE TITLE
Latex builder doesn't emit the `write-started` event

### ISSUE THREAD

**Issue by hwayne** [sphinx-doc/sphinx#12680]
### Describe the bug

`write-started` is emitted in `Builder.write` ([here](https://github.com/sphinx-doc/sphinx/blob/ace5744b82345150baf3c71d6f47a257c89001ec/sphinx/builders/__init__.py#L582)), but `LatexBuilder` overrides `write` and does not call `super()` ([here](https://github.com/sphinx-doc/sphinx/blob/ace5744b82345150baf3c71d6f47a257c89001ec/sphinx/builders/latex/__init__.py#L273)).

### How to Reproduce

In conf, add `extensions = ["foo"]`. For `foo.py`, put:

```python
import sys
def setup(app):
    app.connect("write-started", lambda *x: sys.exit(1))
```

`sphinx-build -Eb html` will terminate building early. `sphinx-build -Eb latex` will complete building normally.

### Environment Information

```text
Platform:              win32; (Windows-10-10.0.22631-SP0)
Python version:        3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)])
Python implementation: CPython
Sphinx version:        7.4.7
Docutils version:      0.20.1
Jinja2 version:        3.1.2
Pygments version:      2.18.0
```

**Comment by jfbu** [comment]
You can put 
```
def setup(app):
    app.connect("write-started", lambda *x: sys.exit(1))
```
directly I end of conf.py.

Same behavior as latex observed with texinfo, singlehtml and man builders.

**Comment by chrisjsewell** [comment]
> as the author of that event

but not the author of the "tweak" 😏; https://github.com/sphinx-doc/sphinx/pull/12567/commits/e536eb90e91a635ef1880f07b7bae515bf1d6bb3
