### ISSUE TITLE
Intersphinx reference to Sympy function does not render as expected

### ISSUE THREAD

**Issue by sr-murthy** [sphinx-doc/sphinx#12689]
### Describe the bug

I'm trying to create an API reference link in my own Sphinx docs project (using Sphinx 7.4.7) to the Sympy [`totient`](https://docs.sympy.org/latest/modules/functions/combinatorial.html#sympy.functions.combinatorial.numbers.totient) function using [Intersphinx](https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html) - here is the fragment in my source (reST) file:
```rst
... using the Sympy :py:func:`~sympy.functions.combinatorial.numbers.totient` function ...
```
When I built my docs site locally (using `make -C docs html` from the project root, in which `docs/` is the subfolder containing Sphinx conf + source files) the HTML output for this fragment renders incorrectly as shown in the image below:

<img width="286" alt="Screenshot 2024-07-26 at 12 20 48" src="https://github.com/user-attachments/assets/dce4d5aa-ecde-434b-97d2-b66dd1fb771b">

The expected rendering should have the referred function hyperlinked to the Sympy docs target below:

https://docs.sympy.org/latest/modules/functions/combinatorial.html#sympy.functions.combinatorial.numbers.totient

There are no build errors. In my `conf.py` I do define Sympy as one of the external documentation domains:
```python
# Intersphinx mappings to reference external documentation domains
intersphinx_mapping = {
    ...
    'sympy': ('https://docs.sympy.org/latest/', None),
    ...
}
```
and I can verify that the correct object entry for this function appears to be available from the intersphinx CLI:
```shell
$ python -m sphinx.ext.intersphinx https://docs.sympy.org/latest/objects.inv | grep combinatorial.numbers.totient
    sympy.functions.combinatorial.numbers.totient                                         : modules/functions/combinatorial.html#sympy.functions.combinatorial.numbers.totient
```

I've tried now to do the same for other Sympy functions and targets, and the result is the same: the HTML reference renders without hyperlinking to the correct target.

### How to Reproduce

I'm using Sphinx 7.4.7. 

The Intersphinx bug is not in `index.rst`, but in another reST page in the docs tree: here is a fragment of that page which does not render correctly (as HTML):
```rst
... using the Sympy :py:func:`~sympy.functions.combinatorial.numbers.totient` function ...
```
This fragment should render with the referred function ([`sympy.functions.combinatorial.numbers.totient`](https://github.com/sympy/sympy/blob/2e489cf4b1438ae134ba98a44a80cc9add1306b0/sympy/functions/combinatorial/numbers.py#L2117-L2164)) hyperlinked to the Sympy API docs target below:

https://docs.sympy.org/latest/modules/functions/combinatorial.html#sympy.functions.combinatorial.numbers.totient

Instead the fragment renders (in HTML) as below:

<img width="286" alt="Screenshot 2024-07-26 at 12 20 48" src="https://github.com/user-attachments/assets/dd783710-5851-4e83-92b8-784ccd10b6f3">

The HTML is built using locally using:
```shell
make -C docs html
```
from the project root, in which the Sphinx `docs/` is a subfolder containing the conf. + sources. There are no build errors.

### Environment Information

```text
Platform:              darwin; (macOS-14.5-x86_64-i386-64bit)
Python version:        3.11.2 (main, Jun  5 2023, 22:10:43) [Clang 14.0.0 (clang-1400.0.29.202)])
Python implementation: CPython
Sphinx version:        7.4.7
Docutils version:      0.21.2
Jinja2 version:        3.1.4
Pygments version:      2.18.0
```

### Sphinx extensions

My current list of extensions is longer, but below is the minimal list of extensions with which I can reproduce the bug. 

```python
['sphinx.ext.autodoc',
 'sphinx.ext.extlinks',
 'sphinx.ext.intersphinx',]
```

**Comment by AA-Turner** [comment]
Did this work correctly in a prior version of Sphinx?

A

**Comment by sr-murthy** [comment]
Not that I know of, but this is the first time I've tried to use an Intershphinx reference to Sympy. Other Intersphinx references to external domains such as Python, Numpy, Pandas etc. do seem to work fine.

For Sympy I know this definitely doesn't work with Sphinx v7.3.7 as well as the latest version (v7.4.7). I only upgraded to v7.4.7 today.

**Comment by sr-murthy** [comment]
As a test I've added the following fragments to that page to test Intersphinx refs to Pandas and Numpy:
```rst
...
Test Pandas reference :py:func:`~pandas.concat`.

Test Numpy reference :py:class:`~numpy.ndarray`.
...
```
which are output as expected (with the correct hyperlinks and targets):

<img width="261" alt="Screenshot 2024-07-26 at 17 45 04" src="https://github.com/user-attachments/assets/447a0382-1614-4937-9978-a3349bf4c3b4">

**Comment by jfbu** [comment]
Try (works for me) `` :py:class:`~sympy.functions.combinatorial.numbers.totient` `` as the source you linked to shows it uses a class definition.

**Comment by sr-murthy** [comment]
@jfbu Thanks, that does seem to work. I assumed the callable was a function, but have just noticed it is defined as a class.

**Comment by sr-murthy** [comment]
Closing
