### ISSUE TITLE
QEMU fails to build with sphinx 8

### ISSUE THREAD

**Issue by eli-schwartz** [sphinx-doc/sphinx#12686]
### Describe the bug

https://bugs.gentoo.org/936620

```
[45/908] /usr/bin/env CONFDIR=/etc/qemu /usr/bin/sphinx-build -q -j auto -Dversion=9.0.2 -Drelease= -Ddepfile=docs/docs.d -Ddepfile_stamp=docs/docs.stamp -b html -d /var/tmp/portage/app-emulation/qemu-9.0.2/work/qemu-9.0.2/tools-build/docs/manual.p /var/tmp/portage/app-emulation/qemu-9.0.2/work/qemu-9.0.2/docs /var/tmp/portage/app-emulation/qemu-9.0.2/work/qemu-9.0.2/tools-build/docs/manual
FAILED: docs/docs.stamp 
/usr/bin/env CONFDIR=/etc/qemu /usr/bin/sphinx-build -q -j auto -Dversion=9.0.2 -Drelease= -Ddepfile=docs/docs.d -Ddepfile_stamp=docs/docs.stamp -b html -d /var/tmp/portage/app-emulation/qemu-9.0.2/work/qemu-9.0.2/tools-build/docs/manual.p /var/tmp/portage/app-emulation/qemu-9.0.2/work/qemu-9.0.2/docs /var/tmp/portage/app-emulation/qemu-9.0.2/work/qemu-9.0.2/tools-build/docs/manual

Extension error (depfile):
Handler <function write_depfile at 0x77a1775ff560> for event 'build-finished' threw an exception (exception: unsupported operand type(s) for +: 'PosixPath' and 'str')
```

### How to Reproduce

```python
"""depfile is a Sphinx extension that writes a dependency file for
   an external build system"""

import os
import sphinx
import sys
from pathlib import Path

__version__ = '1.0'

def get_infiles(env):
    for x in env.found_docs:
        yield env.doc2path(x)
        yield from ((os.path.join(env.srcdir, dep)
                    for dep in env.dependencies[x]))
    for mod in sys.modules.values():
        if hasattr(mod, '__file__'):
            if mod.__file__:
                yield mod.__file__
    # this is perhaps going to include unused files:
    for static_path in env.config.html_static_path + env.config.templates_path:
        for path in Path(static_path).rglob('*'):
            yield str(path)


def write_depfile(app, exception):
    if exception:
        return

    env = app.env
    if not env.config.depfile:
        return

    # Using a directory as the output file does not work great because
    # its timestamp does not necessarily change when the contents change.
    # So create a timestamp file.
    if env.config.depfile_stamp:
        with open(env.config.depfile_stamp, 'w') as f:
            pass

    with open(env.config.depfile, 'w') as f:
        print((env.config.depfile_stamp or app.outdir) + ": \\", file=f)
        print(*get_infiles(env), file=f)
        for x in get_infiles(env):
            print(x + ":", file=f)


def setup(app):
    app.add_config_value('depfile', None, 'env')
    app.add_config_value('depfile_stamp', None, 'env')
    app.connect('build-finished', write_depfile)

    return dict(
        version = __version__,
        parallel_read_safe = True,
        parallel_write_safe = True
    )
```

### Environment Information

```text
#######################################
# installed packages (qlist -ICvUSS): #
#######################################
dev-python/sphinx-8.0.0_rc1:0 -doc -latex python_targets_pypy3 python_targets_python3_10 python_targets_python3_11 python_targets_python3_12 -python_targets_python3_13 -test
dev-python/sphinx-rtd-theme-2.0.0-r1:0 python_targets_pypy3 python_targets_python3_10 python_targets_python3_11 python_targets_python3_12 -python_targets_python3_13 -test
dev-python/sphinxcontrib-applehelp-1.0.8:0 python_targets_pypy3 python_targets_python3_10 python_targets_python3_11 python_targets_python3_12 -python_targets_python3_13 -test
dev-python/sphinxcontrib-devhelp-1.0.6:0 python_targets_pypy3 python_targets_python3_10 python_targets_python3_11 python_targets_python3_12 -python_targets_python3_13 -test
dev-python/sphinxcontrib-htmlhelp-2.0.6:0 python_targets_pypy3 python_targets_python3_10 python_targets_python3_11 python_targets_python3_12 -python_targets_python3_13 -test
dev-python/sphinxcontrib-jquery-4.1:0 python_targets_pypy3 python_targets_python3_10 python_targets_python3_11 python_targets_python3_12 -python_targets_python3_13 -test
dev-python/sphinxcontrib-jsmath-1.0.1-r3:0 python_targets_pypy3 python_targets_python3_10 python_targets_python3_11 python_targets_python3_12 -python_targets_python3_13 -test
dev-python/sphinxcontrib-qthelp-1.0.8:0 python_targets_pypy3 python_targets_python3_10 python_targets_python3_11 python_targets_python3_12 -python_targets_python3_13 -test
dev-python/sphinxcontrib-serializinghtml-1.1.10:0 python_targets_pypy3 python_targets_python3_10 python_targets_python3_11 python_targets_python3_12 -python_targets_python3_13 -test
```

### Additional context

I'm pretty confident the root cause of this is https://github.com/sphinx-doc/sphinx/commit/de15d61a46daaaa2b0a0e341cdb4e0abe107e012

It changes app.env.doc2path to return a `pathlib.Path` instead of a `str`, breaking consumers that assume it's a str.

I also looked in the changelog and saw #12650 which indicates there are many other places that were formerly using `sphinx.util._pathlib._StrPath` as return values, which both provided a Path object, and allowed people to keep using it as a `str` with a deprecation warning. But doc2path never used _StrPath which means no warning was emitted when people used it as a str. Perhaps QEMU would have noticed, perhaps not.

**Comment by eli-schwartz** [comment]
Reported to QEMU at https://gitlab.com/qemu-project/qemu/-/issues/2458 since they need to fix this anyway. Unsure how you want to handle this (offer more deprecations? Proceed with the API change and note it in the changelog?)

**Comment by AA-Turner** [comment]
> I'm pretty confident the root cause of this is [de15d61](https://github.com/sphinx-doc/sphinx/commit/de15d61a46daaaa2b0a0e341cdb4e0abe107e012)
> 
> It changes app.env.doc2path to return a `pathlib.Path` instead of a `str`, breaking consumers that assume it's a str.

This right, and speaks to a larger issue.

Long-term, I want all path-handling logic in Sphinx to use ``pathlib``. It makes handling os-related differences easier, and signals on a type level that this-is-a-filesystem-path. Currently though, people (ab)use the fact that Sphinx uses a simple string representation internally, instead of using [``os.fspath``](https://docs.python.org/3/library/os.html#os.fspath), their own string coercion, or etc.

I see a few options here:

1) Continue down the current path of a (slow) gradual migration. Each major version might change more APIs to taking/yielding ``pathlib.Path`` objects, but there's no great way to warn about this beyond release notes.
2) Change everything all-at-once to use ``pathlib.Path``. This will cause up-front pain, but won't be a constant nag.
3) Re-introduce ``_StrPath`` and convert functions to use that, and then in Sphinx 9(?) switch to ``pathlib``. This might mean consumers see deprecation warnings and have time to switch.
4) Revert the change to ``doc2path`` and do nothing. This leaves us with the less-than-ideal status quo ante, but means no downsteam projects need to change.
5) Something else?

I think (4) is untenable beyond the very short term. (2) would be my ideal, but is unlikely to be popular, which leaves 1, 3, or 5.

Additionally, there's a question of how lenient we are on *input* values -- we can accept an ``os.PathLike`` and coerce internally, or just accept ``Path``. My preference is for almost everything to accept and return ``Path``, but accepting ``os.PathLike`` on 'external' APIs.

A

**Comment by eli-schwartz** [comment]
I would probably suggest 3 -- choosing 1 is IMO just a worse version of 2, people who get surprised by the change aren't going to be any happier. And I, too, cannot think of a 5.

I agree that 4 is unreasonable to impose on you -- you have real motivations for making the API change and other projects cannot just say "freeze your API in amber until the end of time".

**Comment by electric-coder** [comment]
> 2. Change everything all-at-once to use pathlib.Path. This will cause up-front pain, but won't be a constant nag.

A pragmatic argument can be made that `pathlib` has become so commonplace that the change won't be unpopular except for nearly abandoned software.

**Comment by eli-schwartz** [comment]
It's not that the change is going to be unpopular because people don't like pathlib. The change is potentially going to be unpopular because it is an API change that people have to adapt to and until they adapt, their documentation builds error out with tracebacks.

That's kind of the entire point of having a deprecation warning :) otherwise option 3 would be just as unpopular as option 2.

**Comment by pm215** [comment]
Right, the problem from QEMU's point of view is that we need our docs to build with a wide range of Sphinx versions, and so non-backwards-compatible changes in its API are awkward for us. We would hope that such changes should be advertised in advance, start generating warnings before failures, and have attached documentation on how to write code that works both with older Sphinx versions and the new one.

**Comment by picnixz** [comment]
I'm a bit late but I also prefer 3. By the way 5 could have been "Do not deprecate StrPath *at all* and switch from pathlib to StrPath instead" (it's like 3+4 but I don't like that road at all).
