### ISSUE TITLE
new Alabaster package released today (1.0.0) gives warning

### ISSUE THREAD

**Issue by jmckenna** [sphinx-doc/sphinx#12693]
### Describe the bug

- Error: `sphinx 7.4.7 requires alabaster~=0.7.14, but you have alabaster 1.0.0 which is incompatible.`

- Cause: Sphinx requires `alabaster~=0.7.14`
  - see [source](https://github.com/sphinx-doc/sphinx/blob/master/pyproject.toml#L69)

### How to Reproduce

`python -m pip install alabaster==1.0.0`

### Environment Information

```text
Sphinx 7.4.7
```

**Comment by AA-Turner** [comment]
This isn't an error, as such; the packaging tools are working as intended.

I intend to relax the upper-bound on Alabaster following the Sphinx 8 release.

A

**Comment by jmckenna** [comment]
@AA-Turner ok thanks

**Comment by AA-Turner** [comment]
See 8c6846c238c141b747f85db6c5f765687ba692f7.

A
