### ISSUE TITLE
environment.pickle file is too big.

### ISSUE THREAD

**Issue by chen19901225** [sphinx-doc/sphinx#12705]
**Is your feature request related to a problem? Please describe.**

my environment.pickle file is 137M. but i only have 500 rst files.and load environment slow.

**Describe the solution you'd like**

can `BuildEnvironment.__getstate__` restore  `_write_doc_doctree_cache` to default `{}` ?

**Describe alternatives you've considered**

**Additional context**

**Comment by AA-Turner** [comment]
Please can you provide a reproducer, ideally the project you're working on? For CPython the environment is less than 8MB.

A

**Comment by chen19901225** [comment]
my version is too low, now code restore _write_doc_doctree_cache to {}

**Comment by chen19901225** [comment]
my sphinx version is 7.2.5.

update to 7.4 solve it
