### ISSUE TITLE
autodoc drops docstrings for re-exported constants

### ISSUE THREAD

**Issue by MKuranowski** [sphinx-doc/sphinx#12706]
### Describe the bug

The docstrings of re-exported constants are ignored when being re-exported.

### How to Reproduce

**mymodule/__init__.py**:

```py
from .limit import DEFAULT_STEP_LIMIT
__all__ = ["DEFAULT_STEP_LIMIT"]
```

**mymodule/limit.py**:

```py
DEFAULT_STEP_LIMIT = 1_000_000
"""DEFAULT_STEP_LIMIT is the default limit for number of steps before the algorithm
concludes no solution exists.
"""
```

**index.rst**:

```rst
mymodule documentation
======================

.. autodata:: mymodule.DEFAULT_STEP_LIMIT
.. autodata:: mymodule.limit.DEFAULT_STEP_LIMIT
```

**conf.py**

Default, generated by sphinx-quickstart, but with the autodoc extension

<details>
<summary>conf.py</summary>

```py
project = 'mymodule'
copyright = '2024, Mikołaj Kuranowski'
author = 'Mikołaj Kuranowski'

extensions = ["sphinx.ext.autodoc"]

templates_path = ['_templates']
exclude_patterns = []

html_theme = 'alabaster'
html_static_path = ['_static']
```

</details>

The result is as follows:

![image](https://github.com/user-attachments/assets/1329d2f7-8380-4e66-b853-63672293a7cf)

The docstring for both constants should be the same (DEFAULT_STEP_LIMIT is the default limit [...]).

### Environment Information

```text
Platform:              linux; (Linux-6.10.1-arch1-1-x86_64-with-glibc2.40)
Python version:        3.12.4 (main, Jun  7 2024, 06:33:07) [GCC 14.1.1 20240522])
Python implementation: CPython
Sphinx version:        7.4.7
Docutils version:      0.21.2
Jinja2 version:        3.1.4
Pygments version:      2.18.0
```

### Sphinx extensions

```python
["sphinx.ext.autodoc"]
```

**Comment by electric-coder** [comment]
> The docstring for both constants should be the same

Actually it shouldn't. Module level constants don't have a `__doc__` according to the Python data model, so what happens is that Sphinx gives you several possibilities to locally write a docstring that's parsed ([see the examples](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#directive-autoattribute) in the snippet under the `annotation` option) but it doesn't get set on the constant's `__dict__` so it's lost when reexporting - although maybe surprising, the behavior is formally correct . There are [many posts on SO explaining this][1] and [apparently there's a new possibility of using `typing.Annotated`][2] but I haven't bothered trying it - and I'm unsure if it's worth the extra effort over existing parsing alternatives.

[1]: https://stackoverflow.com/search?q=%5Bpython-sphinx%5D+constant
[2]: https://stackoverflow.com/a/8820636

**Comment by electric-coder** [comment]
I think this is the same as #8547.

**Comment by MKuranowski** [comment]
Yes, it is a duplicate of #8547. Sorry, I haven't found that issue, probably I haven't tried searching for "reimported".
