### ISSUE TITLE
Option -q (quiet) gets not passed to latexmk

### ISSUE THREAD

**Issue by jo-so** [sphinx-doc/sphinx#12717]
### Describe the bug

Running sphinx-build with `-q` reduces the output for html, but not for latexpdf. I would be useful if the option `-q` results in the option `-quiet` for latexmk.

### How to Reproduce

Run `make O=-q latexpdf`

### Environment Information

```text
Platform:              linux; (Linux-6.5.0-45-generic-x86_64-with-glibc2.35)
Python version:        3.10.12 (main, Mar 22 2024, 16:50:05) [GCC 11.4.0])
Python implementation: CPython
Sphinx version:        7.2.6
Docutils version:      0.18.1
Jinja2 version:        3.1.4
Pygments version:      2.18.0
```

### Additional context

A workaround is the environment variable `LATEXMKOPTS`, e.g. running `make O=-q LATEXMKOPTS=-quiet latexpdf` reduces the output.

**Comment by jfbu** [comment]
The `-q` description is `'no output on stdout, just warnings on stderr'`. This is not quite what Latexmk's `-quiet` (same as `-silent`) does.  There is also `-Q` which says `'no output at all, not even warnings'`.

We have to choose whether
1. apply shell redirects also to the Latexmk runs after latex file is done,
2. or follow your suggestion of Latexmk `-quiet`.  In that case I would map `-Q` to Latexmk `-quiet` and use for `-q` rather `LATEXOPTS=-halt-on-error -interaction=batchmode` in place of `LATEXMKOPTS=-quiet`.

My preference is rather for 1. as 2. can always be achieved as you indicated with `LATEXOPTS` and/or `LATEXMKOPTS` on command line (or in environment).

**Comment by jo-so** [comment]
Jean-François B. schrieb am Sa 03. Aug, 05:49 (GMT):
> The `-q` description is `'no output on stdout, just warnings on stderr'`. This is not quite what Latexmk's `-quiet` (same as `-silent`) does.  There is also `-Q` which says `'no output at all, not even warnings'`.
> 
> We have to choose whether
> 1. apply shell redirects also to the Latexmk runs after latex file is done,

Do I get you right that you plan to do something like `latexmk -quiet >&2`,
if `-q` is set? That would be fine, because it makes the output more
quiet/less noisy.

**Comment by jfbu** [comment]
@jo-so I originally planned to do as `-q` and `-Q` for `make html` or `make latex`.  The former inhibits stdout but leaves stderr echo on console output.  The latter suppresses all messages.  But `Latexmk` outputs to stderr some purely informative messages.

So it is a bit disturbing to expect only error messages to pop up and to see some innocuous Latexmk messages.

So in actual PR https://github.com/sphinx-doc/sphinx/pull/12729, I decided that `-q` would leave Latexmk output is usual interaction but `-batchmode` is used  (but maybe I tested on a too minimal project -- I need to check more when I get time) for the actual latex runs.

I am undecided, please have a look.  The `-Q` suppresses completely all output to user except for a one line in case a  LaTeX error is encountered in the pdf build phase.
