### ISSUE TITLE
Regression under py 3.12.4, py:class reference target not found: PurePath

### ISSUE THREAD

**Issue by dimaqq** [sphinx-doc/sphinx#12715]
### Describe the bug

- works under py 3.12.3
- fails under py 3.12.4

(tested: linux and mac, both versions)

Error:

```/code/operator/ops/model.py:docstring of ops.model.Container.pull:1: WARNING: py:class reference target not found: PurePath
/code/operator/ops/model.py:docstring of ops.model.Container.pull:1: WARNING: py:class reference target not found: PurePath
```

For code that uses PurePath from pathlib. The other uses of the same weirdly work fine.

MRE at https://github.com/dimaqq/MRE-sphinx-PurePath

### How to Reproduce

MRE at https://github.com/dimaqq/MRE-sphinx-PurePath

```
pyenv install 3.12.3
pyenv install 3.12.4
tox -e docs-3.12.3  # OK
tox -e docs-3.12.4  # Error
```

### Environment Information

```text
Platform:              linux; (Linux-6.8.0-31-generic-aarch64-with-glibc2.39)
Python version:        3.12.4 (main, Jul 31 2024, 09:20:17) [GCC 13.2.0])
Python implementation: CPython
Sphinx version:        6.2.1
Docutils version:      0.19
Jinja2 version:        3.1.4
Pygments version:      2.18.0
```

### Sphinx extensions

```python
sphinx==6.2.1
sphinx-autobuild==2024.4.16
sphinx-basic-ng==1.0.0b2
sphinx-copybutton==0.5.2
sphinx-design==0.6.0
sphinx-notfound-page==1.0.2
sphinx-tabs==3.4.5
sphinxcontrib-applehelp==2.0.0
sphinxcontrib-devhelp==2.0.0
sphinxcontrib-htmlhelp==2.1.0
sphinxcontrib-jquery==4.1
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==2.0.0
sphinxcontrib-serializinghtml==2.0.0
sphinxext-opengraph==0.9.1
```
```


### Additional context

_No response_

**Comment by AA-Turner** [comment]
> sphinx==6.2.1

We don't support old versions of Sphinx -- please could you test with Sphinx 8?

For the record, ``:py:class:`pathlib.PurePath` `` works for me locally.

A

**Comment by dimaqq** [comment]
Sure, will do.

Note that the code in question doesn't contain `:py:class:\`pathlib.PurePath\`` or `:py:class:\`PurePath\`` in the docstrings, these are all inferred from type hints, like `path: PurePath` in Python code.

**Comment by dimaqq** [comment]
No issue in the latest 7.x (7.4.7).
I couldn't get 8.x to work, because one of our deps hasn't caught up yet.

I guess it's fair to close the issue.

However, I'm personally very curious how Python 3.12.3 --> 3.12.4 change could possibly break things.

There are a couple of typing items in the Python changelog, but I can't immediately see those as being relevant...

Would you have an idea who may be interested in this, and how to surface this to them?

**Comment by dimaqq** [comment]
Longer discussion here: https://discuss.python.org/t/3-12-3-3-12-4-regression-deep-rabbit-hole-warning/59584/12

If perhaps Sphinx switched the mechanism it uses to decode type hints between py 3.12 and 3.13, or between Sphinx 6 and 7, please comment.

**Comment by AA-Turner** [comment]
Here is the fix: https://github.com/sphinx-doc/sphinx/pull/12317

A

**Comment by dimaqq** [comment]
I guess I'll leave it up to maintainers wrt. 6.x series:
- do nothing, hope that users have already moved to 7.x or 8.x
- note somewhere that 6.x doesn't work on py 3.12.4 in this specific case
- or make a micro version bump 6.2.2 backporting just this fix

**Comment by AA-Turner** [comment]
Per earlier,

> We don't support old versions of Sphinx

So the status quo will remain, but this issue & discussion can provide hints to those stuck on 6.2.

a
