### ISSUE TITLE
LaTeX: the ``py:class`` directive renders badly in PDF when used for generics with typing

### ISSUE THREAD

**Issue by jfbu** [sphinx-doc/sphinx#12735]
### Describe the bug

With 7.4.0 and current Sphinx I obtain:

![Capture d’écran 2024-08-05 à 14 22 22](https://github.com/user-attachments/assets/1d0d2295-af5c-481d-bd62-b111474523ef)

while with 7.0.1 I obtain

![Capture d’écran 2024-08-05 à 14 19 53](https://github.com/user-attachments/assets/4394e261-17f1-424a-bff8-7adbf788f86a)

(intermediate 7.1.0, 7.2.0, and 7.3.0 raise an error when building the minimal example).

Perhaps my mark-up is not legit? But this copied over from tests/test_builders/test_build_latex.py::test_one_parameter_per_line.

The 7.4.0 HTML build is ok (like PDF from 7.0.1).

### How to Reproduce

index.rst

```rest
domain-py-maximum_signature_line_length
=======================================

text

.. py:class:: MyGenericClass[X]

   A very nice class.

.. py:class:: MyList[T](list[T])

   Another very nice one.

```

### Environment Information

```text
Python version:        3.12.3 (v3.12.3:f6650f9ad7, Apr  9 2024, 08:18:48) [Clang 13.0.0 (clang-1300.0.29.30)])
Python implementation: CPython
Sphinx version:        7.4.0
Docutils version:      0.21.2
Jinja2 version:        3.1.4
Pygments version:      2.18.0
```

### Sphinx extensions

```python
none
```

### Additional context

I tested also with DocUtils 0.19 and DocUtils current master same output.

Same output with current Sphinx also.

I am not one hundred percent sure this is a bug because I never used directly the `py:class` directive always via autodoc. Ping @picnixz for advice.

**Comment by jfbu** [comment]
I forgot to say the problem goes away with

```
python_maximum_signature_line_length = 1
```

in conf.py:

![Capture d’écran 2024-08-05 à 14 54 01](https://github.com/user-attachments/assets/1bf7ae3f-a8c7-4aff-b997-2e38c9dbb926)

```
Sphinx version: 8.1.0+/df871ab15
Python version: 3.12.3 (CPython)
Docutils version: 0.21.2 
Pygments version: 2.18.0
Jinja2 version: 3.1.4
```

but reappear with 

```
python_maximum_signature_line_length = 23
```

(same bad PDF as initially reported).

This is clearly  a LaTeX problem with lists, which I will investigate but now I don't have much disponibility immediately.  Let's milestone this nevertheless for 8.x.

**Comment by jfbu** [comment]
It is not clear this is a bug in so fat as the parentheses are lacking from ``MyGenericClass[X]`` and our docs mentions only 
```
 .. py:class:: name
.. py:class:: name(parameters)
.. py:class:: name[type parameters](parameters)
```
as input forms.

**Comment by electric-coder** [comment]
> Perhaps my mark-up is not legit?

It's legit. Whatever signature is specified in the directive declaration is applied in the documentation; **IF using autodoc** then writing the declaration without a signature should extract the signature automatically from the Python source code.

**Comment by jfbu** [comment]
> This is strange:
> 
> > ```
> > .. py:class:: name[type parameters](parameters)
> > ```

[Python 3.12](https://docs.python.org/3/library/typing.html#user-defined-generic-types) gives this example

```
Generic classes can also inherit from other classes:

from collections.abc import Sized

class LinkedList[T](Sized):
    ...


```

but the vocabulary "parameters", "type parameters" may not be quite appropriate.  If I say anything more people will realize the immensity of my ignorance and under pressure I will have to admit never having taken any CS class.

**Comment by electric-coder** [comment]
Good example, it's for user defined generic classes which is a recent feature and arguably somewhat uncommon.

> I will have to admit never having taken any CS class.

Don't worry, I took plenty of CS classes but I didn't get any smarter because of it.
