### ISSUE TITLE
Double slashes when generating the inventory file URL

### ISSUE THREAD

**Issue by replaceafill** [sphinx-doc/sphinx#12782]
### Describe the bug

This might be considered an edge case but I've noticed that if the value tuple of a `intersphinx_mapping` contains a base URI with a trailing slash and `None` as the inventory file, Sphinx will try to load a URL with double slashes.

### How to Reproduce

Using Sphinx 8.0.2 set the following in the `conf.py` file of a `sphinx-quickstart` project:

```python
extensions = ["sphinx.ext.intersphinx"]
intersphinx_mapping = {'python': ('https://docs.python.org/3/', None)}
```

Run `make html` and notice the double slashes in the output message:

```console
...
loading intersphinx inventory 'python' from https://docs.python.org/3//objects.inv ...
...
```

The double slashes URL could be problematic depending on the web server setup.

### Environment Information

```text
Platform:              linux; (Linux-6.5.0-45-generic-x86_64-with-glibc2.35)
Python version:        3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0])
Python implementation: CPython
Sphinx version:        8.0.2
Docutils version:      0.21.2
Jinja2 version:        3.1.4
Pygments version:      2.18.0
```

### Sphinx extensions

```python
["sphinx.ext.intersphinx"]
```

### Additional context

I think the problem could have been introduced in https://github.com/sphinx-doc/sphinx/pull/12087 where:

https://github.com/sphinx-doc/sphinx/blob/f90b506a9ff2b202fbec707be776cfa590519a14/sphinx/ext/intersphinx/_load.py#L185-L186

was changed into:

https://github.com/sphinx-doc/sphinx/blob/fadb6b10cb15d2a8ce336cee307dcb3ff64680bd/sphinx/ext/intersphinx/_load.py#L214

`posixpath.join` removes the trailing slash in the target URI, but the f-string doesn't.

**Comment by AA-Turner** [comment]
PR welcome!

A

**Comment by picnixz** [comment]
Ah yes, this one is on me. I don't remember why I did this. Maybe I incorrectly thought that the target_uri was stripped of its slash and wanted to reduce the imports. If this is the case, then I'm sorry. I'll do something for that this w-e or someone can fix it (it shouldn't be that hard).

**Comment by jayaddison** [comment]
Would `removesuffix('/')` be sufficient to fix this, or should we reinstate `posixpath` joining?

**Comment by picnixz** [comment]
Technically, since we are dealing with URLs, we should have used `rstrip('/')` because if you put 3 forward slashes, then 

```py
>>> posixpath.join('https://a.com//', 'b')
'https://a.com//b'
```

I'll prepare a PR.

**Comment by jayaddison** [comment]
Websites probably _shouldn't_ accept significant-multiple-separators in their paths, but I think that technically it's valid for them to do that. (serving different content at `foo.invalid/file.txt` from `foo.invalid/////file.txt`, for example).

But `foo.invalidobjects.env` is never what we want, so I wonder whether the logic here should in fact be `base + ('/' if not base.endswith('/') else '') + inv_filename`.

**Comment by jayaddison** [comment]
(and then it's a question of whether we do that ourselves or via `posixpath` -- as presented -- or some other mechanism.  it's not a _file_ path, so `posixpath` seems a bit odd to me, but in this use case, the relevant logic does probably overlap fairly closely..)

**Comment by picnixz** [comment]
I revert it to the old behaviour in #12807. I don't want to mess with URLs and get complaints later :'). If we want to move from our current logic, more places need to be changed (there are some ifs where we test whether the URI is in some set of URIs where we explicitly add a forward slash, I don't remember where but I know it exists).
