### ISSUE TITLE
no attribute 'reprunicode' when running m2r.py

### ISSUE THREAD

**Issue by akkana** [sphinx-doc/sphinx#12793]
### Describe the bug

I have a project for which I haven't regenerated the `documentation in a few years, but it used to work. Now, I'm getting
```
Exception occurred:
  File "/home/akkana/pythonenv/3env/lib/python3.12/site-packages/m2r.py", line 585, in run
    path = nodes.reprunicode(path)
           ^^^^^^^^^^^^^^^^^
AttributeError: module 'docutils.nodes' has no attribute 'reprunicode'
The full traceback has been saved in /tmp/sphinx-err-nv9ayxl8.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [Makefile:19: html] Error 2
```

so I'm reporting it as suggested, since I don't see any open issues matching 'reprunicode'.

It looks like m2r.py is no longer maintained; is there a preferred new way to import from markdown?

Attaching the full log:
[sphinx-err-nv9ayxl8.log](https://github.com/user-attachments/files/16641770/sphinx-err-nv9ayxl8.log)

### How to Reproduce

Sorry, I don't have a minimal way to reproduce this. I've checked in the current state of the project and pushed it to
https://github.com/akkana/metapho/commit/c8aad17cca9edffca58c24245c520e57b5387a4b
and I'm doing
```
doc/sphinxdoc
make html
```

### Environment Information

```text
Platform:              linux; (Linux-6.10.4-amd64-x86_64-with-glibc2.39)
Python version:        3.12.5 (main, Aug  7 2024, 13:49:14) [GCC 14.2.0])
Python implementation: CPython
Sphinx version:        8.0.2
Docutils version:      0.21.2
Jinja2 version:        3.1.3
Pygments version:      2.18.0
```

### Sphinx extensions

```python
sphinx-markdown m2r
```

**Comment by AA-Turner** [comment]
This is, as you deduce, due to `m2r`. Docutils removed the deprecated function in 0.21.

There exists a fork at https://pypi.org/project/m2r2/, or there are sugegstions at https://www.sphinx-doc.org/en/master/usage/markdown.html.

I'll close this though, as the problem doesn't lie with Sphinx.

A
