### ISSUE TITLE
Local link's anchors scrolling beyond vertical distance against expected value

### ISSUE THREAD

**Issue by pique-b** [sphinx-doc/sphinx#12803]
### Describe the bug

In my documentation project, I have used custom `layout.html` to include a banner (in the page header area). Towards that end I have also incorporated `custom.css` in order to maintain (as closely as possible) the standard page layout as being employed in **Sphinx** [online  help](https://www.sphinx-doc.org/).

Every thing seems to have workd out fine only with one **problem**:

The local links created (and referred to using **roles**) are scrolling beyond the **anchor** as should be happening. In addition, the index page links are also experiencing the same problem of scrolling beyond the area where the objects are supposed to appear.

See the images below:

**How it should be**

![anchor_as_shd_b](https://github.com/user-attachments/assets/688ca912-720a-4f7c-ae53-a6e807dbd57c)

**How it is rendered**

![anchor_as_is](https://github.com/user-attachments/assets/5d4bf505-9f2b-40bd-98bc-1dcb84787abc)

### How to Reproduce

**How the header banner has been implemented**

To achieve this, in my *custom* `layout.html`, I am using a `<div>` element and using *css* (in `custom.css`) to fashion it with some background color and link to my *index.rst*.

```
<div id="id_div_banner" class="cls_hdr_banner">
	<a href="{{ pathto('index') }}">
		<div id="id_div_banner_text" class="cls_banner_text"> <!-- For some text on the header banner -->
			<span class="cls_banner_text_span"> XYZ </span>
		</div>
	</a>
</div>
```

In my `custom.css`, I have:

```
.cls_hdr_banner {
	left:0;
	right:0;
	top:0;
	padding-top: 10px;
	padding-right: 20px;
	padding-bottom: 10px;
	padding-left: 20px;
	height: 38px;
	width: 100%;
	position: fixed;
	background-color: #0A507A;
	z-index: 400;
}

```

### Environment Information

```text
Sphinx v.7.2.6
Python 3.9
```

### Sphinx extensions

```python
Minimal extensions have been included.
```

### Additional context

1. Why am I experiencing a **malfunction** of the link anchors?
2. What steps may be initiated to mitigate the problem?

**Comment by electric-coder** [comment]
> 1. Why am I experiencing a malfunction of the link anchors?

I'm not sure but I was implementing something similar to this (FR pending). When you click a cross-reference Sphinx generally does `.scrollTo` but if you start changing the existing layout it might not show the `div` that contains the `<a>`. It does roughly something like:

```js
const topPos = ref_target.getBoundingClientRect().top + window.pageYOffset;
window.scrollTo({top: topPos, behavior: 'smooth'});
```

> 2. What steps may be initiated to mitigate the problem?

Good question, in my case I was hoping to change the target from the enclosing `<a>` to the enclosing `<div>`. So I don't yet know.

**Comment by pique-b** [comment]
@electric-coder
1. So it seems there is no "ready" solution to the problem of local link scrolling past the anchor position?
2. > You don't say exactly what element in the list you are cross-referencing, ...

The examples (the images in the original query here) are taken from the `index` page and as may be apparent, a user clicking on the link **A** on top should expect to scroll to the region starting with a *sub-section* **A** followed by list of indixed entries found. **What is happening instead is**: the sub-section header **A**, the following blank line and the *first row* of the indexed values (`About graphviz` etc) are missing.

I have since removed the `z-index` but has not made a difference to the situation.

**Comment by electric-coder** [comment]
I don't know... Maybe adjust `scroll-margin-top:` to make up for the extra banner in the header?! See the screenshot:

```css
.body :target {
  scroll-margin-top: 6.5rem;
}
```

![scroll-margin-top](https://github.com/user-attachments/assets/0d7f9a00-5fba-4809-a03b-612cc214b5d1)

**Comment by pique-b** [comment]
@electric-coder Thanks to your input, things are now working as expected.

Many thanks!
