### ISSUE TITLE
`no-index` ignored for `:py:module:`

### ISSUE THREAD

**Issue by stephenfin** [sphinx-doc/sphinx#12843]
### Describe the bug

The `noindex` flag allows you to avoid creating an index entry for a directive. This is useful where e.g. a module is documented twice. It looks like the long-term plan is to deprecate `noindex` in favour of `no-index` and in #12620 we made changes to that effect. However, that PR has completely removed the ability to set the `noindex` property on these directives, introducing a regression. I suspect the author assumed inheritance, but we don't call `super()` from `PyObject.run`.

### How to Reproduce

See https://github.com/stephenfin/sphinx-issue-12843

### Environment Information

```text
n/a (occurs with any commit from e439c6f33f to ce0d1791d6 (`HEAD` of `master` at time of writing)
```

### Sphinx extensions

```python
[]
```

**Comment by AA-Turner** [comment]
Thanks, seems we don't have test coverage for this. Your assumption about my assumption is probably correct!

A
