### ISSUE TITLE
Remove unnecessary `:func:` & `:meth:` parentheses from reST content

### ISSUE THREAD

**Issue by mattwang44** [sphinx-doc/sphinx#12847]
### Describe the bug

The func & meth role's parentheses are unnecessary as Sphinx will add them to the rendered output.

```rst
.. bad
:func:`sphinx.locale._()`

.. good
:func:`sphinx.locale._`
```

We're introducing a new rule to the sphinx-lint ([issue](https://github.com/sphinx-contrib/sphinx-lint/issues/114) & [PR](https://github.com/sphinx-contrib/sphinx-lint/pull/115)) and, since sphinx-lint utilizes Sphinx doc content in the CI, we'd like to also fix the issue in doc.

**Comment by AA-Turner** [comment]
Could you do this for method roles too? See https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-add_function_parentheses

**Comment by mattwang44** [comment]
> Could you do this for method roles too? See [sphinx-doc.org/en/master/usage/configuration.html#confval-add_function_parentheses](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-add_function_parentheses)

Thanks, I've updated the PR and also the sphinx-lint PR!
