### ISSUE TITLE
:ref:`section title` should work w/o explicit label

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1286]
Currently I have to write:

.. _Built-in Functions:
## Built-in Functions

if I want to refer to the section from other documents using :ref:.

I think this is redundant and also goes against the spirit of documentation being human readable even as plain text.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1286
- Originally reported by: Ben Franksen
- Originally created at: 2013-10-07T01:12:26.443

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2013-10-07 03:25:11+00:00_

The label doesn't have to have the same text as the heading: you could use `.. _builtins:` for example.

This is by design: so that you don't need to change lots of links when changing the heading (or translating it).

**Comment by shimizukawa** [comment]
_From Ben Franksen on 2013-10-07 10:47:41+00:00_

Well, it is your decision, of course, but I suggest you re-think your rationale.

First, the feature I requested would not prevent you from using a separate label if that is the way you like to work.

Second, I do not plan to ever translate the documentation for my project. I just do not have the manpower for that, and since I often work to improve it, any translation would be out of date very soon. I think this situation is not untypical, there are lots of one-man projects out there.

Last not least, chosing a different text for the label actually makes things more difficult for me. Each time I want to add a cross-reference, I have to look up the name of the label. I find it a lot easier to remember the section name. Besides, I usually have a web-browser open where I can read the formatted version of what I write, and I can find section headings there easily via the local TOC. The label I have to look up in the rst sources.

Having to add a separate label makes it harder for people to add cross-references. This is bad since in my experience, the more cross-references, the easier it is to navigate around a complex project, especially if you are still unfamiliar with it. Therefore adding a cross-reference should be as easy as possible for the documentation writer.

**Comment by tk0miya** [comment]
Now, I add `sphinx.ext.autosectionlabel` into master branch.
Sphinx-1.4a1 will be released soon. Please try it :-)
