### ISSUE TITLE
Parentheses in function arguments cause warnings

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1290]
Example:

```
#!rst

.. function:: hexchat_hook* hexchat_hook_command (hexchat_plugin *ph, const char *name, int pri, \
                                                  int (*callb) (char *word[], char *word_eol[], void *user_data), \
                                                  const char *help_text, void *userdata)
```

Result:

plugins.rst:958: WARNING: c:type reference target not found: callb

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1290
- Originally reported by: Eustachy Kapusta
- Originally created at: 2013-10-10T12:03:49.876

**Comment by tk0miya** [comment]
It seems the warning is not shown with Sphinx-1.7.1.
So I'm closing this now.
Please feel free to reopen if you still have this problem.

Thanks,
