### ISSUE TITLE
[Feature Request]Sidebar button on mobile

### ISSUE THREAD

**Issue by ghost** [sphinx-doc/sphinx#12909]
Many other themes such as [Furo](https://pradyunsg.me/furo/) and [PyData](https://pydata-sphinx-theme.readthedocs.io/en/stable/) have a sidebar button on mobile.

Since many people like using a sidebar to navigate, why not add a sidebar for mobile, since the sidebar actually hides itself on mobile screens?

**Comment by AA-Turner** [comment]
Opening generic feature requests (cf. https://github.com/sphinx-doc/alabaster/issues/223) isn't helpful. Please avoid doing so in the future.

A
