### ISSUE TITLE
Document suppressing cross-references via ! prefix

### ISSUE THREAD

**Issue by timhoffm** [sphinx-doc/sphinx#12940]
I just learned from the sphinx doc sources that one can disable cross-references by prefixing the reference with an exclamation mark.

The relevant source code seems to be:

https://github.com/sphinx-doc/sphinx/blob/341b0417d5ccc2b495276cd60c5c6d8accd2a72c/sphinx/util/docutils.py#L602-L603

I haven't found anything about this in the documentation. Is this an official feature? If so, we should document it.

**Comment by AA-Turner** [comment]
The main documentation is at (1), with (2) giving a precis. However, if an experienced user (read: you) has missed this, perhaps there's an opportunity for improvement or more cross-links?

1. https://www.sphinx-doc.org/en/master/usage/referencing.html
2. https://www.sphinx-doc.org/en/master/usage/domains/index.html#cross-referencing-syntax


A

**Comment by timhoffm** [comment]
Thanks for the links.

I have indeed missed this, likely because the description is quite dense. After I've seen examples in the docs, I've tried to find this in reverse, searching for `` `!`` and `exclamation mark` both in source and on the doc search site.

I'll come up with a suggestion how to improve the docs.

**Comment by electric-coder** [comment]
> I'll come up with a suggestion how to improve the docs.

I'll make an argument that the exclamation mark `!` functionality is *"marginal"* (if you're writing a cross-reference why would you want to disable linking given it's so convenient?). Hence it gets mentioned once (right at the top of the [Cross-referencing syntax doc][1] in one of three prominent bullet-points) and that's it. It's also *straightforward* and thus a trivial feature that doesn't cause any doubts to users who know about it.

Now, I do agree the exclamation mark `!` itself needs more emphasis in that doc. The best option might be adding triple backticks around it for visibility. Or a simple pair of backticks with bold.

[1]: https://www.sphinx-doc.org/en/master/usage/referencing.html#cross-referencing-syntax

**Comment by timhoffm** [comment]
> if you're writing a cross-reference why would you want to disable linking given it's so convenient?

There are cases where the target does not exist and you don't want warnings about that:
- either because it has been removed (Classical example: Changelog entries that point to removed functions. I have so far solved this by turning the references into literals, but deactivating the link is more elegant)
- or because the target is not documented. In an ideal world that should not happen, but there are cases, where documentation is not straight forward and you have to find ways to cope with it (e.g. private base classes, undocumented attributes etc.) They should work in the long run, but in a certain working context you want to indicate the intent to cross-reference without sorting out the missing reference right there.

**Comment by AA-Turner** [comment]
I would strongly counter that suppressing cross-references is "marginal", it is an extremely useful feature. For example, when referencing the same object twice in a paragraph, keeping the same presentational style but only one link (for the first instance) is only possible with suppressed cross references. As Tim notes, references to functions that have been removed, or protocol functions, or third-party libraries without intersphinx, using reference suppression enables keeping the presentation of functions (e.g. automatic trailing brackets ``()``) and any custom CSS styles, but without reference failures.

It also enables easier find-and-replace in the future, as `:role_name:` is much easier to search for than simply the literal pattern.

For some statistics, in the Python documentation there are over three and a half thousand uses (~3,700) of ``:`!`` indicating a suppressed reference, and 53,000 uses of `` :` `` (for all interpreted text roles), so ~7% of all roles used (including those that don't support ``!``).

A

**Comment by electric-coder** [comment]
> add a "heading" to the bullet points

@timhoffm  I think that's probably the clearest and most stylish choice!

@AA-Turner very insightful sum up of the use cases! Makes lots of sense.
