### ISSUE TITLE
Make the figure directive agnostic to content

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1297]
It would be nice if we could insert eg. graphviz graphs in the figure directive to have a caption.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1297
- Originally reported by: Jan Ulrich Hasecke
- Originally created at: 2013-10-22T10:23:49.037

**Comment by andreacassioli** [comment]
Definitely!

I just stumble across the graphiz case...

**Comment by tk0miya** [comment]
Nowadays, the `:caption:` option makes common sense to set captions to any objects like graphviz, code-block and so on.
So I think this is already resolved.

@andreacassioli Do you still have any problem about this?

**Comment by andreacassioli** [comment]
@tk0miya 

indeed now I can set a caption, but graphs has not the same options that images/figures. And there is something fishy with alignment, see #2575

**Comment by tk0miya** [comment]
Agreed. but that is different issues with this. this issue said that it would be nice if figure directive makes graphviz and other components captionable (like `figure` environment on LaTeX).
But, now sphinx provides `:caption:` option to some directives individually.

In fact, our approach is different from expects, but we've accomplished the purpose.
So I want to close this issue now.

BTW, what you said is correct. It would be better to improve graphviz and other directives.
About alignment, I will work it on #2575.

If you have other themes, please open new issues.

Thanks,

**Comment by andreacassioli** [comment]
@tk0miya 

I see your fix for the graphiz align. Great! Thanks a lot again.

For me you can close the issue.

**Comment by tk0miya** [comment]
:-)
