### ISSUE TITLE
Could not import extension sphinxcontrib.mermaid (exception: cannot import name 'ExtensionError' from 'sphinx.util' ...

### ISSUE THREAD

**Issue by IHMEkaleb** [sphinx-doc/sphinx#13002]
### Describe the bug

When I run `sphinx-build` with `sphinxcontrib.mermaid 0.9.2` and `sphinx 8.1.0`, I get this error:
```
sphinx-build /path/to/docs /path/for/build/output
Running Sphinx v8.1.0
loading translations [en]... done

Extension error:
Could not import extension sphinxcontrib.mermaid (exception: cannot import name 'ExtensionError' from 'sphinx.util' (/path/to/my_env/lib/python3.11/site-packages/sphinx/util/__init__.py))
```

However, with `sphinx 8.0.x`, it builds fine.

### How to Reproduce

1. Install `sphinxcontrib.mermaid 0.9.2` and `sphinx 8.1.0`, and add the extension.
2. Run `sphinx-build`.
3. Build fails.

### Environment Information

```text
`sphinxcontrib.mermaid=0.9.2` and `sphinx=8.1.0`
```

### Sphinx extensions

```python
sphinxcontrib.mermaid
```

### Additional context

Filed same issue with Mermaid: https://github.com/mermaid-js/mermaid/issues/5954

**Comment by AA-Turner** [comment]
`sphinxcontrib.mermaid` should use the proper import location for `sphinx.errors.ExtensionError`.

A

**Comment by AA-Turner** [comment]
@IHMEkaleb you should report this to https://github.com/mgaitan/sphinxcontrib-mermaid

A

**Comment by IHMEkaleb** [comment]
Oh, wait, AA-Turner, I see that you responded in that ticket as well and have added it to the 8.1.0 milestone here. Thanks!

**Comment by jacobtomlinson** [comment]
I've proposed https://github.com/mgaitan/sphinxcontrib-mermaid/pull/161 to resolve this
