### ISSUE TITLE
locale_dirs default value inconsistency

### ISSUE THREAD

**Issue by rffontenelle** [sphinx-doc/sphinx#13025]
### Describe the bug

_sphinx-build_ searches for translation files in the directory 'locale', even though
[locale_dirs](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-locale_dirs) conf value defaults to 'locales' since Sphinx 1.5, as per [changelog entry](https://github.com/sphinx-doc/sphinx/blob/a1510de4777eaa2e569435f95b05f6f3293d7035/doc/changes/1.5.rst?plain=1#L199).

This causes weird behaviors like sphinx-intl looking for translations in 'locales' (https://github.com/sphinx-doc/sphinx-intl/issues/14), but sphinx-build builds translated docs using translations from 'locale'.

Related code (I think, not sure though):

https://github.com/sphinx-doc/sphinx/blob/a1510de4777eaa2e569435f95b05f6f3293d7035/sphinx/application.py#L321

https://github.com/sphinx-doc/sphinx/blob/a1510de4777eaa2e569435f95b05f6f3293d7035/sphinx/config.py#L217

### How to Reproduce

```bash
# Get sphinx and sphinx-doc-translations sources
git clone --single-branch --depth 1 --branch 3.13 https://github.com/python/cpython
git clone --single-branch --depth 1 --branch 3.13 https://github.com/python/python-docs-pt-br cpython/Doc/locale/pt_BR/LC_MESSAGES
# Enter sphinx dir
cd cpython/Doc
# Build translated from locale
make html SPHINXOPTS='-Dlanguage=pt_BR'
# and check built files, should be translated
# Now rename directory
mv locale locales
# Again build translated from locale
make html SPHINXOPTS='-Dlanguage=pt_BR'
# and check the built files, which should NOT be translated now.
```

### Environment Information

```text
Latest sphinx commit
```

**Comment by AA-Turner** [comment]
`locale_dirs += [path.join(package_dir, 'locale')]` is using the Sphinx `sphinx.locale` directory as a final fallback, so I think unrelated.

**Comment by rffontenelle** [comment]
@AA-Turner I see. So the usage/configuration page that says locale_dirs defaults to 'locales' is incorrect, right?

**Comment by AA-Turner** [comment]
``config.locale_dirs`` defaults to ``['locales']``

When I try and run locally with the `.mo` files under `Doc/locales/pt_BR/LC_MESSAGES`, I get translated results. When under `Doc/locale`, I don't.

This seems opposite to your reproducer @rffontenelle?

A

**Comment by rffontenelle** [comment]
It doesn't, hence my original statement is incorrect (now?). Proposed a fix for the Configuration page that is currently stating 'locale' is the default.
