### ISSUE TITLE
    from sphinx.cmd.build import main

### ISSUE THREAD

**Issue by helinyu** [sphinx-doc/sphinx#13030]
### Describe the bug

[1/870][  0%][1.580s] Building HTML documentation
FAILED: docs/CMakeFiles/docs_html /Users/helinyu/workspace/GitHub/space_swift/build/Ninja-DebugAssert/swift-macosx-x86_64/docs/CMakeFiles/docs_html
cd /Users/helinyu/workspace/GitHub/space_swift/swift/docs && /usr/local/bin/sphinx-build -D latex_elements.papersize=letter -d /Users/helinyu/workspace/GitHub/space_swift/build/Ninja-DebugAssert/swift-macosx-x86_64/doctrees -b html . /Users/helinyu/workspace/GitHub/space_swift/build/Ninja-DebugAssert/swift-macosx-x86_64/docs/html
Traceback (most recent call last):
  File "/usr/local/bin/sphinx-build", line 5, in <module>
    from sphinx.cmd.build import main
ModuleNotFoundError: No module named 'sphinx'

### How to Reproduce

compile swift project https://github.com/swiftlang/swift

### Environment Information

```text
Platform:              darwin; (macOS-15.0.1-x86_64-i386-64bit)
Python version:        3.12.5 (v3.12.5:ff3bc82f7c9, Aug  7 2024, 05:32:06) [Clang 13.0.0 (clang-1300.0.29.30)])
Python implementation: CPython
Sphinx version:        8.1.3
Docutils version:      0.21.2
Jinja2 version:        3.1.4
Pygments version:      2.18.0
```

**Comment by AA-Turner** [comment]
This is not a useful bug report, but from the traceback it appears you do not have Sphinx installed.

A
