### ISSUE TITLE
threeparttable is not a float - let's have an option to let it float

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1303]
A threeparttable is not a float by itself. You must put it into a table environment in LaTeX to make it a float. 

There should be an option to the table directive in Sphinx that puts the resulting threeparttable in a floating table-environment in LaTeX.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1303
- Originally reported by: Jan Ulrich Hasecke
- Originally created at: 2013-11-07T11:16:57.013

**Comment by andreacassioli** [comment]
+1

**Comment by tk0miya** [comment]
We are discussed about this at #3377.
Finally we decided not to make tables as float.

Thank you for proposal.
