### ISSUE TITLE
support `prop: Annotated[str, typing.Doc("...")]` as property document

### ISSUE THREAD

**Issue by trim21** [sphinx-doc/sphinx#13100]
**Is your feature request related to a problem? Please describe.**

[PEP 727](https://peps.python.org/pep-0727/) support annotated types and add new class `typing.Doc`(backport with `typing_extensions.Doc`, this can be used to add doc to class property, and I hope sphinx autodoc could support this

for example: 
from this:
```python
class File(NamedTuple):
    name: str
    """file name"""
```
to this:
```python
class File(NamedTuple):
    name: Annotated[str, typing_extensions.Doc("file name")]
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

- [e.g. URL or Ticket]

**Comment by AA-Turner** [comment]
PEP 727 isn't accepted (and personally, I don't think it's the right solution to the problem discussed). As such I'll close this.

A

**Comment by trim21** [comment]
do we consider add this feature if it's accepted?

**Comment by AA-Turner** [comment]
Perhaps. Though `typing.Doc` has several drawbacks, so perhaps not.

A
