### ISSUE TITLE
Support non-newline glossary term separator(s)

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1315]
The current way of expressing multiple term variations is:

```
#!rest

   .. glossary::

      term 1
      term 2
         Definition of both terms.
```

This can be suboptimal when there are several terms; in such a case there will be several lines (all terms) highlighted. A nicer, more readable alternative way to express could be:

```
#!rest

   .. glossary::

      term 1 | term 2
         Definition of both terms.

```

A different term separator could be chosen of course; for example a comma or (forward) slash would be fine as well. Or allow all three, as they are all commonly used in computing to list alternative tokens.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1315
- Originally reported by: Petri Savolainen
- Originally created at: 2013-11-27T18:25:33.589

**Comment by tk0miya** [comment]
-1: Sphinx handles many kind of terms. so nobody can't say what character is most proper for separator.
Multi-lines definition does not prevent to write the such terms. And we can adjust how to represent them in later step.
