### ISSUE TITLE
ePubs does not validate due to references to images

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1317]
epubcheck 3.0.1 throws errors validating Sphinx epubs, because images are referenced, which seems to be not allowed

This is code generated by Sphinx 1.2b3:

```
#!html

<a class="reference internal image-reference" href="_images/sphinx-logo.png"><img alt="_images/sphinx-logo.png" src="_images/sphinx-logo.png" style="width: 160.0px;" />
```

is causing this error:

```
#!bash

ERROR: ../../_build/epub/Sphinx.epub/abbildungen.html(48,78): hyperlink to non-standard resource '_images/sphinx-logo.png' of type 'image/png'
```

While this code produced by another tool validates without errors.

```
#!html

<img alt=" " src="images/images.png" width="600" height="734" />
```

It seems to me that the href-tag should not be included in the code.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1317
- Originally reported by: Jan Ulrich Hasecke
- Originally created at: 2013-11-28T18:17:17.393

**Comment by mgifford** [comment]
Related issue https://github.com/sphinx-doc/sphinx/issues/2371

**Comment by shibukawa** [comment]
I couldn't reproduce it by Sphinx 1.6
