### ISSUE TITLE
cascading toctree

### ISSUE THREAD

**Issue by bitmodeler** [sphinx-doc/sphinx#13176]
### Describe the bug

I set my toctree maxdepth to 2.

I have used sphinx before and don't remember it doing this. Each successive chapter ("=", under and over...) in the sidebar toctree is indented one to the right, up to a depth of 6 (the maximum that can be rendered in the allotted sidebar width...), and then it starts over again at the left. Is this the way sphinx just does it? (now??) It doesn't seem logical to me; you would think each chapter would be under each other, left aligned.

I tried a number of things suggested in online threads, to no avail.

Screenshot:
![toctree](https://github.com/user-attachments/assets/5ca995b4-5931-4787-937a-b083cc5bb04b)

index.rst:
[index.rst.txt](https://github.com/user-attachments/files/18080193/index.rst.txt)

conf.py:
[conf.py.txt](https://github.com/user-attachments/files/18080196/conf.py.txt)

### How to Reproduce

Files attached above...

### Environment Information

```text
Platform:              linux; (Linux-6.1.0-28-amd64-x86_64-with-glibc2.36)
Python version:        3.11.2 (main, Sep 14 2024, 03:00:30) [GCC 12.2.0])
Python implementation: CPython
Sphinx version:        5.3.0
Docutils version:      0.19
Jinja2 version:        3.1.2
```

**Comment by AA-Turner** [comment]
@bitmodeler you haven't included the content of the 'dolphin' file.

Can you confirm that each heading has the same line decoration (i.e. all '=')? Does it still happen with e.g. `furo` or `alabaster` as the theme?

A

**Comment by bitmodeler** [comment]
Yes, all equal's. Can send you the other rst's, if you need them.

Will try the themes...

**Comment by AA-Turner** [comment]
I've just noticed you're on `Sphinx version:        5.3.0` - it shouldn't make a difference, but we only support the latest version (8.1.x).

A

**Comment by bitmodeler** [comment]
That was it! I will play with that CSS to see how I can get those square bullets without having that side effect on the sidebar.

Thanks for having a look; case closed...

**Comment by bitmodeler** [comment]
Refined the CSS selectors (to support square bullets...) All good now. Thanks again...
