### ISSUE TITLE
APT release outdated

### ISSUE THREAD

**Issue by ttlns** [sphinx-doc/sphinx#13194]
### Describe the bug

The latest version of  `python3-sphinx` on debian is way outdated (5.3.0-4, [apt release](https://packages.debian.org/bookworm/python3-sphinx) whilst latest is is 8.1.3 [pypi release](https://pypi.org/project/Sphinx/)).

This especially is an issue due to [pip install -r requirements.txt is failing: "This environment is externally managed"](https://stackoverflow.com/q/75602063/20443541)

Further, this makes `sphinx-build -M html docs_src docs_out` fail with
```
Sphinx version error:
The alabaster extension used by this project needs at least Sphinx v6.2; it therefore cannot be built with this version.
```
(even if `sphinx_rtd_theme` is used)

### How to Reproduce

```bash
sudo apt install python3-sphinx
sphinx-build --version
```

### Environment Information

```text
Platform:              linux; (Linux-6.1.0-22-amd64-x86_64-with-glibc2.36)
Python version:        3.11.2 (main, Sep 14 2024, 03:00:30) [GCC 12.2.0])
Python implementation: CPython
Sphinx version:        5.3.0
Docutils version:      0.21.2
Jinja2 version:        3.1.2
```

### Sphinx extensions

```python
["sphinx_rtd_theme"]
```

**Comment by AA-Turner** [comment]
Please report this to the Debian packagers, this project has no control in that regard. We would of course like to see the latest versions distributed and used.

A

**Comment by kaliiiiiiiiii** [comment]
> Please report this to the Debian packagers, this project has no control in that regard. We would of course like to see the latest versions distributed and used.
> 
> A

Well the maintainers appear to be
1. [Dmitry Shachnev](mailto:mitya57@debian.org) ([QA Page](https://qa.debian.org/developer.php?login=mitya57%40debian.org))
2. [Debian Python Team](mailto:team+python@tracker.debian.org) ([QA Page](https://qa.debian.org/developer.php?login=mitya57%40debian.org))

Isn't [1.] @mitya57 in the dev team here anyway?
( [commits by mitya57](https://github.com/sphinx-doc/sphinx/commits?author=mitya57) )

Either way, if it is not possible to resolve this issue on your side, shouldn't the (now broken) apt installation be removed from the documentation?

**Comment by mitya57** [comment]
I am here, but the proper way to report bugs for Debian packages is using Debian BTS, not upstream bug tracker.

Anyway, Debian testing has Sphinx 8.1.3 (the latest version). Debian stable has whatever version was at the moment of freeze, and it is not possible to update it because it will break many packages.

**Comment by mitya57** [comment]
> This especially is an issue due to [pip install -r requirements.txt is failing: "This environment is externally managed"](https://stackoverflow.com/q/75602063/20443541)

Oh, and I forgot to mention that you should probably use virtualenv. Inside virtualenv, pip won't complain about breaking system packages.
