### ISSUE TITLE
autosummary not linking to Stub pages

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1320]
I'm trying to set up an API using the autodoc and autosummary extensions. 

At the top of the page, I've got:

.. currentmodule:: <module>

   :toctree: <folder for stub pages>

   <classes>

Below that I've got:

.. automodule:: <module>

   :members:

and in the conf.py, I've got:

autosummary_generate = ['<module>']

and 
extensions = ['sphinx.ext.autodoc', 'sphinx.ext.autosummary']

... this produces the stub pages,  plus a page with the summary table at top and the full API below.   As is, the class names in the summary table link to the full API below -- but I'd like them to link to the stub pages instead. In fact, I'd like to be able to link to them without having to include the full API in the doc.   Is that possible?

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1320
- Originally reported by: Jon Hertzig
- Originally created at: 2013-12-10T21:52:01.405

**Comment by shimizukawa** [comment]
_From Jon Hertzig on 2013-12-13 01:20:43+00:00_

Nevermind.... removing the automodule directive fixes it.

**Comment by Michael-E-Rose** [comment]
Apparently this issue is solved and can be closed.

**Comment by shimizukawa** [comment]
Thanks for letting me know!
