### ISSUE TITLE
Sphinx multilanguage functionality

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#133]
Hello,

I was wondering if it would be possible to integrate some document translation functionality in sphinx. Besides creating a whole new sphinx documentation root for any language one would want to support I could not find any other possibility though.

I could imagine that documentation for a given project should be made available in different languages from a single sphinx document root.
You could have seperate versions of the same document for several languages. Think of a language switch too making it possible to switch language for a given document (at least for the html version) and toc trees that display available languages optionally.

Best regards,

Rico Moorman

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/133
- Originally reported by: r moorman
- Originally created at: 2009-03-26T12:17:57.566

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2009-03-26 18:58:24+00:00_

This has actually something been considered a few times.  I agree that it's a nice feature, and I've added a SoC project idea to our page.  Perhaps someone is going to do it :)

**Comment by shimizukawa** [comment]
_From r moorman on 2009-03-30 18:54:57+00:00_

That would be really great! Furthermore if it could be managed it would surely make this (already powerful) documentation tool even more versatile and helpful.

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2010-08-21 18:17:47+00:00_

Done now in SoC, and merged.

**Comment by deepakajaylinux** [comment]
i would like to add multi language in my sphinx documentation... pls help me i need help and ideas

thank you

**Comment by lehmannro** [comment]
@deepakajaylinux, please refrain from adding unrelated questions to closed issues.  Documentation for multi-language support in Sphinx can be found [online](http://sphinx-doc.org/intl.html).  If you have any further questions please consider asking on the [sphinx-users mailing list](https://groups.google.com/forum/#!forum/sphinx-users) first.

**Locking** this issue.
