### ISSUE TITLE
Manual destination for HTML builder

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1333]
Add options for HTML output to manual destantion path.

**I have structure of documentation:**

mybook/

|--chapter1/

|--chapter2/

|--chapter3/

**I need html structure:**

html/

|--introduce/

|--overview/

|--examples/

**for urls like:**

example.com/introduce/

example.com/overview/

example.com/examples/

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1333
- Originally reported by: Anonymous
- Originally created at: 2013-12-21T16:01:51.830

**Comment by shimizukawa** [comment]
_From Robert Lehmann on 2014-01-20 11:03:38+00:00_

What's stopping you from moving chapter1/ to introduce/, by just renaming the folders/files?

**Comment by shimizukawa** [comment]
_From [ANAT01](https://bitbucket.org/ANAT01) on 2014-01-21 08:09:54+00:00_

For example I use numbers in chapter's name to sort it and fast find one of them  for effective orientation in mybook
I have many parts of book (10 chapters and ~10-15 paragraphs for every chapter).

mybook/
|--01_blablabla/
|--02_blablabla/
|--|--0203_blabla.rst
|--|--...
|--...

After building I have url like example.com/01_introduce//0101_Wellcome_text.html and it look bad.

Now i use prebuilding bash script for copy mybook and rename files without numbers.

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2014-01-21 09:39:35+00:00_

I would say that for this usecase your current method is perfectly fine.

**Comment by tk0miya** [comment]
-1; it is too complicated. It is good to pre-process using bash or other scripts before building by Sphinx.

**Comment by tk0miya** [comment]
I'm closing this now.
Thank you for your proposal!
