### ISSUE TITLE
Django docs build fails for text format

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1334]
Building Django docs to html target works fine but for the text target it fails. I've tried updating docutils but it didn't help. Attached are tracebacks for both versions of docutils.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1334
- Originally reported by: Ljuba Nedeljkovic
- Originally created at: 2013-12-24T23:59:12.593

**Comment by tk0miya** [comment]
I salvaged attached files from bitbucket:
[sphinx-err-ddXyw0.log](https://files.zenhub.io/56b70c38c7438c6402f46463)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)
[sphinx-err-H5zcFY.log](https://files.zenhub.io/56b70c3dc7438c6402f46464)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by tk0miya** [comment]
MEMO: related with #1370 (maybe)

**Comment by tk0miya** [comment]
It is same as #1370.
The problem was fixed at 1.2.2.

Thank you for reporting.
