### ISSUE TITLE
visit_pending_xref missing from html.py

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#134]
I don't fully understand why yet, but I was choking on the error:

NotImplementedError: Unknown node: pending_xref

It appears that `visit_pending_xref` and `depart_pending_xref` are not defined there.

I am not exactly sure what should be in these, but defining these allows the documentation to be generated.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/134
- Originally reported by: Michael Forbes
- Originally created at: 2009-03-26T16:03:15.966

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2009-03-26 15:05:50+00:00_

pending_xref nodes shouldn't remain in documents once they're fed throug the writer. If they do, this is a bug in some other module or extension -- can you track down what generates it?

**Comment by shimizukawa** [comment]
_From Michael Forbes on 2009-03-26 15:09:50+00:00_

At what stage should they be filtered out (and why are no-op {{{*_pending_xref}}} functions defined in the LaTeX and tex writers then)?

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2009-03-26 18:30:13+00:00_

They should be filtered out in the Environment's resolve_doctree. The visitor methods in latex and tex are probably debugging leftovers...

**Comment by shimizukawa** [comment]
_From Michael Forbes on 2009-03-26 20:54:42+00:00_

The problem is with the todo extension...  I will see if I can figure out why.

**Comment by shimizukawa** [comment]
_From Michael Forbes on 2009-03-26 21:01:15+00:00_

It looks like the content for the todo nodes is not processed by the environments resolve_doctree and then get inserted when doctree-resolved is emitted, and then never processed.  If the content contains references, then these are left unprocessed in the collected todo list, causing the error.  (They seem to get processed properly in the original context which makes sense).

I am not sure what the appropriate fix is here: perhaps somehow grabbing the processed admonitions rather than inserting the stale copies...

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2009-03-27 17:05:30+00:00_

Thanks! Fixed in trunk and 0.6 dev branch.

**Comment by Naereen** [comment]
Hi @shimizukawa,
I encountered this issue again, with Sphinx v1.8.5, on the documentation [of my SMPyBandits package](https://github.com/SMPyBandits/SMPyBandits/).
See the log file attached:
[sphinx-err-3eo7ao_8.log](https://github.com/sphinx-doc/sphinx/files/2952408/sphinx-err-3eo7ao_8.log)
I solved the issue by adding the following (useless) piece of code to `sphinx/writers/html.py` (just before line 903):
```python
    def visit_pending_xref(self, node):
        # type: (nodes.Node) -> None
        pass

    def depart_pending_xref(self, node):
        # type: (nodes.Node) -> None
        pass
```
(this was naively copied/pasted from `sphinx/writers/text.py`.

Thanks.

**Comment by shimizukawa** [comment]
@Naereen  This issue has been closed 10 years ago.
Please create a new issue. Thanks.

**Comment by Naereen** [comment]
Okay, sorry I wasn't sure if opening a new issue was necessary. Regards.
