### ISSUE TITLE
No partial word search

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1341]
Hi all

It seems that the partial word search is not supported in html documentation. It would be interesting to have it optionally.

Suddenly I found a problem in the result context display : if I search for the word "first" in a page containing the words "firstsecond" and "first", the "first" word is correctly detected but this is the "firstsecond" word that is highlighted.

Step to reproduce :
- create index.rst with this content : "firstsecond first"
- generate html documentation
- search for word "firs" : no result (no partial word search)
- search for word "first" : "firstsecond" is highlighted

Thank you (and sorry for my english.)

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1341
- Originally reported by: Anonymous
- Originally created at: 2014-01-06T18:10:56.625

**Comment by andreacassioli** [comment]
Hi,
this is a crucial feature for the search. 

Say I have an API and I want to search for a method whose name contains putacol, possibly a very large name. I would like to just type that, not remembering or type the whole name.

**Comment by birkenfeld** [comment]
APIs (object names) _are_ searched by substrings already.

**Comment by TimKam** [comment]
I changed the label from *bug* to *enhancement*, because this is no "hard" bug.
