### ISSUE TITLE
TOC shows differently when using make incremental vs make html after make clean

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1360]
The attached .rst files show the issue:
make html with files as they are to get a base line.
In index.rst, change the tocdepth to 1, then:
incremental make html changes just the toc that appears on index.html
make clean make html changes the toc in the index.html and also in the side-bar of heading1.html

I think incremental make should really do the same as clean make, although I really like the behaviour from the incremental change. So this is also a new-feature request.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1360
- Originally reported by: Raymond Obin
- Originally created at: 2014-01-25T13:17:40.944

**Comment by tk0miya** [comment]
I salvaged the attached files from bitbucket: [1360.zip](https://github.com/sphinx-doc/sphinx/files/72638/1360.zip)

**Comment by shimizukawa** [comment]
1. What happen?

When user use 'globaltoc.html' for sidebar of each pages, globaltoc.html should reflects toctree representation in master_doc page (usually, it is index.html).
In such case, on changing `maxdepth` value of toctree in master_doc should cause regenerating of each pages that uses 'globaltoc.html'. But, Sphinx doesn't.
1. How to fix it?

For now, sidebar page fragments (including globaltoc.html) doesn't care whether the result of function (such as `toctree()`) will be changed or not. In fact, Sphinx doesn't have such mechanism.

---

In this time, I reject this ticket because it is hard to resolve in current sphinx structure.
Please `make clean && make html` in such case as a workaround.
