### ISSUE TITLE
support Py3.4 "sig=(...)" signatures in autodoc

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1369]
Py3.4 (Argument Clinic) supports generating a text signature as the first line of a docstring. The syntax isn't completely final yet, but it seems like it will be a leadig `sig=` and then a signature in parens.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1369
- Originally reported by: Georg Brandl
- Originally created at: 2014-02-02T12:08:30.184

**Comment by shimizukawa** [comment]
I guess these are information sources of Argument Clinic: 
- https://docs.python.org/3/howto/clinic.html
- https://www.python.org/dev/peps/pep-0436/

However I can't find any `sig=(...)`.
@birkenfeld this sphinx feature ticket was created by you. Please let me know the detail what we should support.

**Comment by tk0miya** [comment]
ping. any updates?
If none, I will postpone this to 1.6.

**Comment by tk0miya** [comment]
I'm closing this now.
Please reopen this again if you'll come back.
Thanks,
