### ISSUE TITLE
linkcheck does not validate TLS

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1373]
Specifically: it does not check when it loads a page that the certificate the server presented is a) signed by any recognized signing authority, and b) has a hostname matching the actual hostname. The result is a) linkcheck is open to MITM, b) it doesn't really emulate what a browser does, a real user clicking the link in a modern browser will get an error page.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1373
- Originally reported by: Alex Gaynor
- Originally created at: 2014-02-03T19:38:29.171

**Comment by shimizukawa** [comment]
_From Michael Schlenker on 2014-02-05 12:18:51+00:00_

Basically means you could do linkcheck with the basic python httplib only for Python 3.x where certificate validation is implemented.

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2014-02-05 14:24:32+00:00_

I have no objections to use requests (which I assume does TRT on 2.x) when available.

But in general a) is not a concern at all for this application, and b) is a minor annoyance (and usually nothing the documentation author could fix).

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2014-12-19 14:03:46+00:00_

Issue #1655 was marked as a duplicate of this issue.

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2014-12-19 14:04:59+00:00_

Python 2.7.9 also fine.

**Comment by tk0miya** [comment]
Since 1.5, we started to use `requests` library for linkcheck.
At same time, we also verify TLS certifications.
http://www.sphinx-doc.org/en/master/config.html#confval-tls_verify

So I think this was already resolved.
Thanks,
