### ISSUE TITLE
filter table of contents

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1388]
I am considering using this for knowledgebase authoring; however, it is not immediately clear to me whether or not it is possible to filter the table of contents dynamically. I have looked through the example website and it seems no one has done this before. 

I want to be able to filter the table of contents similar to the way that tagging works. But I do not want to get a set of page links when I click on the the tag keyword. I'd like to be able to filter the TOC. Is that possible with any themes?

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1388
- Originally reported by: Anonymous
- Originally created at: 2014-02-12T22:20:56.239

**Comment by tk0miya** [comment]
I'm closing this now because nobody had tried to implement or discuss this for a long time. Please file a new issue if you still have more detailed idea.
Thanks,
