### ISSUE TITLE
wrong css style for cross reference in note

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1389]
Consider the following doc snippet::

```
#!reST

Hello, I am :class:`.A`!

.. note:: Here is another link to :class:`.A`.

```

The first xref has background-color: transparent, as is apparently the norm for cross reference links. The second however has a medium gray, like literal text withing the note.

This happens because the rule '.note tt' takes precedence over the rule 'tt.xref' which is supposed to set transparent background for cross reference links. Maybe a '.note tt.xref' should be added to the default style sheets?

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1389
- Originally reported by: [mwoehlke](https://bitbucket.org/mwoehlke)
- Originally created at: 2014-02-12T23:47:08.191

**Comment by tk0miya** [comment]
I confirmed with alabaster and classic theme (other themes are okay).

* alabaster
![2018-03-08 23 37 36](https://user-images.githubusercontent.com/748828/37156676-1d5e5854-232a-11e8-913d-c10643e79091.png)

* classic
![2018-03-08 23 37 17](https://user-images.githubusercontent.com/748828/37156675-1b961e9e-232a-11e8-880b-f1b749826a51.png)

**Comment by tk0miya** [comment]
This was introduced at #287. It seems the coloring is intended.

**Comment by tk0miya** [comment]
I'm not good at design and coloring. So I'm closing this now.
Thanks,
