### ISSUE TITLE
Inheritance diagrams are not floats in LaTeX

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1401]
so they don't float and mess up the typesetting.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1401
- Originally reported by: Jan Ulrich Hasecke
- Originally created at: 2014-02-20T14:53:06.178

**Comment by tk0miya** [comment]
I added `:caption:` option to the `inheritance-diagram` directive. It works like figure directive and make the diagram as float.

Thanks,
