### ISSUE TITLE
AttributeError: 'ReadtheDocsBuilder' object has no attribute 'globalcontext'

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1407]
Hello,
sorry if this is not the right place where to signal this but all of the sudden I can no longer build doc for psutil project hosted on http://psutil.readthedocs.org/en/latest/
I get this and I'm not sure how to fix it:

```
    WARNING: master file /var/build/user_builds/psutil/checkouts/latest/docs/contents.rst not found

    Exception occurred:
      File "/home/docs/checkouts/readthedocs.org/user_builds/psutil/envs/latest/local/lib/python2.7/site-packages/readthedocs_ext/readthedocs.py", line 27, in copy_media
        ctx = app.builder.globalcontext
    AttributeError: 'ReadtheDocsBuilder' object has no attribute 'globalcontext'
    The full traceback has been saved in /tmp/sphinx-err-kN3Rx5.log, if you want to report the issue to the developers.
    Please also report this if it was a user error, so that a better error message can be provided next time.
    Either send bugs to the mailing list at <http://groups.google.com/group/sphinx-users/>,
    or report them in the tracker at <https://bitbucket.org/birkenfeld/sphinx/issues/>. Thanks!
```

FWICT I have no problems at building docs locally via "make html".

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1407
- Originally reported by: Giampaolo Rodola
- Originally created at: 2014-02-28T13:53:28.498

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2014-02-28 14:47:39+00:00_

Sorry, I don't have any information for that. I googled then I found the error sometimes has been raised on RTD. I recommend that you try contact to the RTD maintainer.

**Comment by shimizukawa** [comment]
_From Giampaolo Rodola on 2014-02-28 15:37:44+00:00_

OK, I will, thanks.

**Comment by shimizukawa** [comment]
_From [ericholscher](https://bitbucket.org/ericholscher) on 2014-08-15 18:06:10+00:00_

This is actually a Sphinx issue -- where it is only generating the globalcontext variable on certain builds.

**Comment by shimizukawa** [comment]
_From [ericholscher](https://bitbucket.org/ericholscher) on 2014-08-15 18:13:22+00:00_

I believe if nothing is written to the filesystem, it doesn't get generated -- I have hopefully fixed the RTD code to handle this  though.

**Comment by shimizukawa** [comment]
_From [ericholscher](https://bitbucket.org/ericholscher) on 2014-08-15 18:14:05+00:00_

https://github.com/sphinx-doc/sphinx/blob/544e73602c95db464e3d91d25dc45de0846917f2/sphinx/builders/html.py#L321

**Comment by tk0miya** [comment]
@ericholscher Do you remember this problem is resolved now? Sorry, this is very old issue. But I'm cleaning old issues now. So please let me know if you remember something about this.
I guess this is already resolved at present.
Thanks,

**Comment by ericholscher** [comment]
I'm not sure. I think it can be closed though, and I will re-open another issue if it happens again!

**Comment by tk0miya** [comment]
Thank you for comment. Okay, I'm closing this now :-)
