### ISSUE TITLE
Check latex_logo validity before copying

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1408]
The code handling html_logo (in sphinx/builders/html.py) now checks for existence of logo file. I suggest that the code handling latex_logo (in sphinx/builders/latex.py) have the same check.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1408
- Originally reported by: Arfrever Frehtes Taifersar Arahesis
- Originally created at: 2014-03-03T13:26:11.815

**Comment by tk0miya** [comment]
Fixed at d0576cd.
Thank you for reporting.
