### ISSUE TITLE
Exception when combining figure with .. only:: directive

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1412]
Hi there, 

I have [asked this question on stackoverflow](http://stackoverflow.com/questions/22182394/how-can-i-reference-figures-with-numfig-while-including-png-files-for-html-and-p) but as requested in the exception also wanted to report this here. 

I am trying to use the numfig extension while generating both HTML and PDF documentation and so far this has worked great. 

Now, I would like to use PDF figures in the latex version and PNG figures in the html version. I tried to use the .. only:: directive as follows

```
#!python

.. _import-dmmetamodel:

.. only:: html

   .. figure:: _static/dataext/DM-Example.png

      My caption for the figure.

.. only:: latex

   .. figure:: _static/dataext/DM-Example.pdf

      My caption for the figure.
```

I get this error message: 

```
#!

Exception occurred:
  File "/MyPath/Documentation/sphinxext/numfig.py", line 76, in doctree_resolved
    target_doc = app.builder.env.figid_docname_map[target]
KeyError: u'import-dmmetamodel'
The full traceback has been saved in /var/folders/h7/qxg81k7c8xj6ws001s7mslb00000gn/T/sphinx-err-fyu24Y.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
Either send bugs to the mailing list at <http://groups.google.com/group/sphinx-users/>,
or report them in the tracker at <https://bitbucket.org/birkenfeld/sphinx/issues/>. Thanks!
make: *** [html] Error 1
```

I am not sure whether this is a bug or user error. Could you please let me know? Thank you.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1412
- Originally reported by: Anonymous
- Originally created at: 2014-03-05T16:27:34.984

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2014-03-05 18:12:17+00:00_

Thanks for the report. You have a "numfig" extension installed. Where does this extension come from? It seems that its author would need to check that it handles "only" directives correctly.

**Comment by shimizukawa** [comment]
_From Arno Schulz on 2014-03-05 18:27:07+00:00_

Ah OK, great. Thank you. Yes, [numfig (see here)](https://bitbucket.org/arjones6/sphinx-numfig) is an extension that makes it possible to reference figures by number. I will check with them directly.

**Comment by tk0miya** [comment]
In this case, you can use `*` for images extension. Then the builder chooses an appropriate filetype automatically. So only directive is not needed for this case.

```
   .. figure:: _static/dataext/DM-Example.*

      My caption for the figure.
```

Closing.
