### ISSUE TITLE
source-read() callback doesn't resolve includes

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1415]
It is impossible for extension to process included texts with [source-read](http://sphinx-doc.org/extdev/appapi.html#event-source-read) event handler, because it doesn't resolve the includes.

For example, in this file.rst, CHANGES.txt will not be processed.

```
=============
Release Notes
=============

.. include:: ../CHANGES.txt
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1415
- Originally reported by: anatoly techtonik
- Originally created at: 2014-03-08T11:36:31.592

**Comment by tk0miya** [comment]
I think this is not a bug. `source-read` event is emitted before parsing. It simply gives a content of the source file. If you'd like to get parsed document, please use `doctree-read` instead.

Note: there are no way to get plain text after processing `include` directive. The directive works on parsing phase. so the result is not a plain text.
