### ISSUE TITLE
PicklingError on environment when config option value is a callable

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1424]
https://travis-ci.org/pypa/pip/jobs/20852384

I am trying to add extension to Sphinx that does [filtering on HTML](https://bitbucket.org/techtonik/wikify/) based on callable regex rules specified in `conf.py`. However, my build fails with PicklingError when I specify extension options.

```
...
looking for now-outdated files... none found
pickling environment...
Exception occurred:
  File "C:\Python33\lib\site-packages\sphinx-1.3a0dev_20140315-py3.3.egg\sphinx\environment.py", line 146, in topickle
    pickle.dump(self, picklefile, pickle.HIGHEST_PROTOCOL)
_pickle.PicklingError: Can't pickle <class 'function'>: attribute lookup builtins.function failed
The full traceback has been saved in c:\users\user\appdata\local\temp\sphinx-err-z8bc2u.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://bitbucket.org/birkenfeld/sphinx/issues/>. Thanks!
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1424
- Originally reported by: anatoly techtonik
- Originally created at: 2014-03-16T04:16:09.388

**Comment by shimizukawa** [comment]
_From anatoly techtonik on 2014-03-16 03:17:51+00:00_

See intended usage scenario here - https://github.com/pypa/pip/pull/1647

**Comment by shimizukawa** [comment]
_From anatoly techtonik on 2014-03-20 20:31:51+00:00_

The problem was caused by function in closure returned by function call in `conf.py`. I solved the issue by transforming the closure into object.

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2014-03-20 22:41:59+00:00_

Yes, it's limitation of the sphinx. Because conf.py is loaded by a `exec` from `sphinx.config` module, objects/functions in the conf.py are not able to pickle.

**Comment by shimizukawa** [comment]
_From anatoly techtonik on 2014-03-21 01:28:36+00:00_

That's not completely true. After converting closure to object, the error is gone.

**Comment by webknjaz** [comment]
@techtonik do you recall what you meant by converting the closure to object?

**Comment by techtonik** [comment]
@webknjaz closure is a returnable function that "remembers" values from an outer scope. See the fix https://bitbucket.org/techtonik/wikify/commits/9775a693789d601eac17a767e013489039bad779

**Comment by webknjaz** [comment]
FTR: this quirk is now documented in the tutorial: https://github.com/sphinx-doc/sphinx/pull/6754.
