### ISSUE TITLE
Problem with progress display

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1425]
When I build documentation for a package, the progress is printed in multiple lines instead of just one line, see the attached screenshot.

This is the output I have of pip freeze.

```
Jinja2==2.7.2
MarkupSafe==0.19
Pygments==1.6
Sphinx==1.2.2
autopep8==1.0
backports.ssl-match-hostname==3.4.0.2
docutils==0.11
ipython==1.2.1
matplotlib==1.3.1
nose==1.3.0
numpy==1.8.0
pep8==1.4.6
pyparsing==2.0.1
python-dateutil==2.2
pyzmq==14.1.0
scipy==0.13.3
six==1.5.2
sphinx-bootstrap-theme==0.4.0
tornado==3.2
wsgiref==0.1.2
```

![Screen Shot 2014-03-17 at 3.44.41 AM.png](https://bitbucket.org/repo/7zgG/images/2697695974-Screen&#37;20Shot&#37;202014-03-17&#37;20at&#37;203.44.41&#37;20AM.png)

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1425
- Originally reported by: Yoshiki Vazquez-Baeza
- Originally created at: 2014-03-17T10:45:58.635

**Comment by shimizukawa** [comment]
_From WAKAYAMA shirou on 2014-08-14 12:17:04+00:00_

That multiple lines are default behavior.  Below is my output.

```
building [html]: targets for 15 source files that are out of date
updating environment: 15 added, 0 changed, 0 removed
reading sources... [  6%] advanced
reading sources... [ 13%] around
reading sources... [ 20%] command
reading sources... [ 26%] conclusion
reading sources... [ 33%] config
reading sources... [ 40%] blah
reading sources... [ 46%] index
reading sources... [ 53%] introduction
reading sources... [ 60%] larger
reading sources... [ 66%] module
reading sources... [ 73%] book
```

**Comment by shimizukawa** [comment]
_From Yoshiki Vazquez-Baeza on 2014-08-14 13:20:18+00:00_

What I've found is that if your terminal window has fewer columns that
the longest line to be displayed and updated, then the progress line
will be re-rendered after every "cycle", causing the effect that I
described.

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2014-08-14 13:22:55+00:00_

This should actually not be default behavior unless verbose mode is turned on (`-v` command line switch). Otherwise it might be a thing with the terminal not processing carriage returns (`\r`).

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2014-08-14 13:26:14+00:00_

> What I've found is that if your terminal window has fewer columns that the longest line to be displayed and updated, then the progress line will be re-rendered after every "cycle", causing the effect that I described.

Right, that would do it.  And I don't think there's anything we can do about it without taking full control over the terminal; this behavior is only eye-candy anyway.

**Comment by shimizukawa** [comment]
_From Yoshiki Vazquez-Baeza on 2014-08-14 13:40:14+00:00_

Sounds good, thanks!

**Comment by shimizukawa** [comment]
_From WAKAYAMA shirou on 2014-08-14 13:44:53+00:00_

Ah, sorry. I don't know that feature while a long time...

**Comment by anntzer** [comment]
FWIW it is "relatively" easy to check the column width, see e.g. https://github.com/tqdm/tqdm/blob/0464e8aaeb569981a7ba6d31803d256fbf328de9/tqdm/_utils.py (_environ_cols_wrapper).
