### ISSUE TITLE
Accelerator key not underlined in EPUB and PDF

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1432]
The accelerator key, which is underlined in HTML output, is not underlined in LaTeX and EPUB output. 

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1432
- Originally reported by: Jan Ulrich Hasecke
- Originally created at: 2014-03-25T11:58:48.208

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2014-03-25 12:00:26+00:00_

epub was fixed together with the enumerations issue.

**Comment by tk0miya** [comment]
This was already fixed by https://github.com/sphinx-doc/sphinx/commit/2c5c54aa67869ca5d3ae36f8392b6ab170c20c9a

Thanks,
