### ISSUE TITLE
sphinx-apidoc doubles up on __doc__ strings of classes

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1439]
Related Issue (_from circuits project_): https://bitbucket.org/circuits/circuits/issue/74/auto-generated-api-docs-for

I haven't as yet had the time to develop a specific trivial test case, but at fisrt glance the `sphinx-apidoc` tool is inheriting the `__doc__` string from all base classes despite the subclass having it's own `_-doc__`.

This is a bug IHMO.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1439
- Originally reported by: James Mills
- Originally created at: 2014-04-04T17:48:08.725

**Comment by picnixz** [comment]
Ah yes indeed. We tend to forget those old issues because either they were fixed somewhere or because no one remembered them.

Thanks for checking if they need to be closed btw.
