### ISSUE TITLE
Make qthelp more configurable

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1448]
Please apply the attached patches to add configuration options for controlling qch output names.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1448
- Originally reported by: Anonymous
- Originally created at: 2014-04-10T10:34:49.729

**Comment by stephenfin** [comment]
This was a pull request - not an issue. Without access to the original patch, and it's not available [on Bitbucket](https://bitbucket.org/birkenfeld/sphinx/pull-requests/), or a more detailed description, we can't do anything. This should be closed as **invalid** or similar.

**Comment by shimizukawa** [comment]
Actually, administrators can get the file from the BB Issue. However, this issue is sufficiently old and we do not know whether there is demand yet, so close once.
[sphinx-1448-patch.zip](https://github.com/sphinx-doc/sphinx/files/1357571/sphinx-1448-patch.zip)

**Comment by tk0miya** [comment]
Reopened. We should review the patches before closing. I think some of them is obviously important.

**Comment by tk0miya** [comment]
Note:

* `0001-Document-the-qthelp_basename-option.patch`:  I said this is "important" patch. But our document is already updated on master branch. (I only checked stable branch and there are no docs there...)
* `0002-Add-the-qthelp_namespace-option.patch`: enough reasonable. The qthelp expects the namespace is identifier like domain name. It should be modified.
* `0003-Make-the-qch-output-name-configurable.patch`: I feel changing `.qch` file is not necessary. We can already change an output filename through `qthelp_basename`.

**Comment by shimizukawa** [comment]
Thanks!
