### ISSUE TITLE
xml builder creates invalid xml file

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1450]
Wrong file example is 'library/functions.xml'
(generated from python2.7 docs with sphinx 1.2.2 and 1.3.0a)

Error is in lines as such:
<desc_signature class="" first="False" fullname="abs" ids="abs" module names="abs"><desc_name>abs</desc_name><desc_parameterlist><desc_parameter>x</desc_parameter></desc_parameterlist></desc_signature>
where 'module' should be probably something like 'module=""'

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1450
- Originally reported by: Anonymous
- Originally created at: 2014-04-11T08:56:51.750

**Comment by shimizukawa** [comment]
_From [bjakubiak](https://bitbucket.org/bjakubiak) on 2014-04-11 06:58:22+00:00_

Error is in lines as such: 

<desc_signature class="" first="False" fullname="abs" ids="abs" module names="abs"><desc_name>abs</desc_name><desc_parameterlist><desc_parameter>x</desc_parameter></desc_parameterlist></desc_signature>

where 'module' should be probably something like 'module=""'

**Comment by shimizukawa** [comment]
_From [bjakubiak](https://bitbucket.org/bjakubiak) on 2014-04-11 07:27:04+00:00_

other wrong xml files in library directory:
stdtypes.xml, pickle.xml and constants.xml

generated by:
./sphinx-build.py -b xml Python-2.7.6/Doc dest

**Comment by shimizukawa** [comment]
_From Robert Lehmann on 2014-04-11 15:25:08+00:00_

Technically, this is a bug in Docutils.  Sphinx uses its docutils_xml writer, which [uses Node.starttag](http://sourceforge.net/p/docutils/code/7747/tree/trunk/docutils/docutils/writers/docutils_xml.py#l132) to render the opening tag.  It seems to be a deliberate decision to [handle](http://sourceforge.net/p/docutils/code/7747/tree/trunk/docutils/docutils/nodes.py#l535) _boolean attributes_ differently in there.

You seem to be right in that the XML [spec requires all attributes to have a value](http://www.w3.org/TR/xml/#sec-starttags).  I think reporting to the [Docutils issue tracker](http://sourceforge.net/p/docutils/bugs/) is the best path.

**Comment by shimizukawa** [comment]
_From [bjakubiak](https://bitbucket.org/bjakubiak) on 2014-04-11 17:56:20+00:00_

Reported there: https://sourceforge.net/p/docutils/bugs/253/

**Comment by shimizukawa** [comment]
_From Robert Lehmann on 2014-04-12 04:13:05+00:00_

Thanks!

**Comment by shimizukawa** [comment]
_From engelbert gruber on 2014-06-03 09:31:11+00:00_

the erronous xml::

```
<desc_signature class="" first="False" fullname="abs" ids="abs" module names="abs">
```

xml seams to require a value.

the code producing the error ::

```
for name, value in self.attlist():
    if value is None: # boolean attribute
        parts.append(name)
        continue
```

to me None is not boolean, boolean is True/False or maybe 0/1

to me "module" looks like yes it is a module
and "" like no it is not.

Having a value None says no value , therefore "module " seams reasonable to me.
If I want 'module=""' I would assign a value.

More important who relies on which form of output

**Comment by stephenfin** [comment]
This has been [fixed in docutils](https://sourceforge.net/p/docutils/bugs/253/) and can now be closed.

**Comment by shimizukawa** [comment]
Confirmed. Thanks!
