### ISSUE TITLE
"Source code" link can not be disabled.

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1452]
According to the [plot_directive.py](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/sphinxext/plot_directive.py) one should be able to supress the generation of the source code links by setting 

```
plot_include_source = False
plot_html_show_source_link = False
```

However this does not seem to have an effect.  See for example http://beta.book.xogeny.com/behavior/equations/first_order/ which is generated using [this conf.py setting](https://github.com/xogeny/ModelicaBook/blob/967e7b10f05378370418f68428f60178de776283/text/source/conf.py#L303).

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1452
- Originally reported by: Dietmar Winkler
- Originally created at: 2014-04-15T10:36:03.979

**Comment by dietmarw** [comment]
Just tested this again with sphinx-build v1.4.8 and the switch seems now to work as expected. So this issue can be closed.

**Comment by tk0miya** [comment]
It seems not a bug of plot_directive. And @dietmarw says it was already fixed.
So I'm closing this now.

Thanks,
