### ISSUE TITLE
Add support for Epytext in Napoleon extension

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1461]
I received a suggestion from a Sphinx user to add support for Epytext in Napoleon:

> I really liked the old Epydoc format. The PyCharm IDE also supports reST and Epytext, which is another reason why I like Epytext more than the Google and NumPy styles.
> 
> Have you ever thought about adding support for Epytext keywords such as `[Premkumar Subramanian](https://bitbucket.org/param)` and `[Premkumar Subramanian](https://bitbucket.org/param)` in napoleon? Do you think that it might be feasible to implement such functionality given the current architecture of napoleon?

I think this is an excellent idea, and it doesn't seem unfeasible to me. A quick google search shows that this is not an uncommon desire.

The work to support Epytext in Napoleon will be submitted as a pull request for final approval.

Does anyone have any objections?

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1461
- Originally reported by: Rob Ruana
- Originally created at: 2014-05-02T05:14:33.015

**Comment by shimizukawa** [comment]
_From John Vandenberg on 2014-11-20 03:27:40+00:00_

If you only need epydoc fields (param/type/return, etc) to parse correctly, I've written a very small plugin which does that.
https://pypi.python.org/pypi/sphinx-epytext

I've only added enough syntax support for the one project I'm working on at the moment (http://pywikibot.readthedocs.org/en/latest/), but I'll be adding more for my own needs, and don't mind getting it to support another open source project that still uses epytext and is looking for a documentation solution.

**Comment by RobRuana** [comment]
I don't think epydoc support is going to make it into napoleon, especially since there is another extension which implements this feature. Development time would be best spent making the sphinx-epytext extension more robust.
