### ISSUE TITLE
Sanity checking for html_static_path needed?

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1464]
See https://bugs.gentoo.org/show_bug.cgi?id=509810. Their `html_static_path` starts with `../`, which is apparently not something Sphinx deals well with.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1464
- Originally reported by: Dirkjan Ochtman
- Originally created at: 2014-05-09T09:08:17.404

**Comment by shimizukawa** [comment]
_From Mike Gilbert on 2014-05-09 14:29:07+00:00_

I think it has more to do with the `html_static_path` being the same as the output directory.

In the case of the Gentoo bug, both html_static_path and the output directory were effectively "./html".

**Comment by tk0miya** [comment]
+0; I don't think this is a bug. But we have to check it on building.

**Comment by tk0miya** [comment]
Fixed by #6500.
Thank you for reporting.
