### ISSUE TITLE
Support backslashes with following newline and indentation

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1465]
Frequently when writing docstrings, it is necessary to link to another module/method/class; frequently, these links are long and frequently these links result in lines of text greater than [PEP8 recommends](http://legacy.python.org/dev/peps/pep-0008/#maximum-line-length).

You might try to get around it with something like this:

```
#!python
        """
        :meth:`~foobar.foobarbaz.foobarbazbarbaz.\
        foobarfoobarfoobarbaz`
        """
```

But this does not work and does not show up as a link in generated documentation because there are spaces after the newline. This works:

```
#!python
        """
        :meth:`~foobar.foobarbaz.foobarbazbarbaz.\
foobarfoobarfoobarbaz`
        """
```

But it's also ugly and has poor indentation. It would be very helpful if the backslash prevented indentation from messing up links and other RST elements.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1465
- Originally reported by: [plasmasheep](https://bitbucket.org/plasmasheep)
- Originally created at: 2014-05-12T05:59:57.925

**Comment by 1kastner** [comment]
This feature would still be nice to have in 2022. I just tried it myself and for the role "meth" this issue still exists. Interestingly, there are other RST elements such as web links for which it works though.

**Comment by tk0miya** [comment]
Single backslash in docstring concatenates a line in python level.

```
>>> def func():
...     """:meth:`some_module.\
...     some_class.some_method`"""
...
>>> inspect.getdoc(func)
':meth:`some_module.    some_class.some_method`'
```

So autodoc can't process it well.

Please use raw string (`r"..."`) or double backslashes to mark it up.

```
>>> def func():
...     """:meth:`some_module.\\
...     some_class.some_method`"""
...
>>> inspect.getdoc(func)
':meth:`some_module.\\\nsome_class.some_method`'
```
