### ISSUE TITLE
cmdoption missing documentation

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1468]
It seems that the docs for `cmdoption` are missing. I tried to find out how to document command line interfaces properly for quite a while now. 

I found these old docs: https://bitbucket.org/birkenfeld/sphinx/raw/4464818aea168b52fb2a9a0cde603d9f2c164a51/doc/markup/desc.rst

It seems that the documentation for `cmdoption` disappeared some day. Are there any reasons for this? This directive works quite well in the most recent release of sphinx.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1468
- Originally reported by: Stefan Tatschner
- Originally created at: 2014-05-16T18:53:03.759

**Comment by TimKam** [comment]
@tk0miya Presumably, this one can be closed as well (I'm taking a look at open `docs` tickets atm).

**Comment by tk0miya** [comment]
Thanks!
