### ISSUE TITLE
:std:event: links do not work

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1469]
This inventory file at http://spihnx-doc.org/objects.inv lists several entries whose role is `:std:event:` (for instance `:std:event:autodoc-skip-member`), but attempting to include these links in a sphinx rest source file does not work correctly. 

For instance, I have the following in my rest:

```
:std:event:`sphinx:autodoc-skip-member`
```

With the following intersphinx configuration in `conf.py`:

```
intersphinx_mapping = {
    'python': ('http://docs.python.org/2', None),
    'sphinx': ('http://sphinx-doc.org/', None),
}
```

It gets rendered in HTML as:

```
<a href="#id1">
    <span id="id2" class="problematic">:std:event:`sphinx:autodoc-skip-member`</span>
</a>
```

Notice it does not link to the correct location (targets an anchor on the same page, instead of the intended location on the sphinx-doc stie), and the link text is the entire rest link code, instead of just the expected "autodoc-skip-member."

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1469
- Originally reported by: Maytag Metalark
- Originally created at: 2014-05-19T16:17:35.634

**Comment by tk0miya** [comment]
I think this is not a bug. `:event:` is a custom object type for sphinx document. It's not standard one. So you need to set up your project to refer it.

I copied from some implementations from `sphinx/docs/conf.py` like following:
```
import re
from sphinx import addnodes
from sphinx.util.docfields import GroupedField

event_sig_re = re.compile(r'([a-zA-Z-]+)\s*\((.*)\)')

def parse_event(env, sig, signode):
    m = event_sig_re.match(sig)
    if not m:
        signode += addnodes.desc_name(sig, sig)
        return sig
    name, args = m.groups()
    signode += addnodes.desc_name(name, name)
    plist = addnodes.desc_parameterlist()
    for arg in args.split(','):
        arg = arg.strip()
        plist += addnodes.desc_parameter(arg, arg)
    signode += plist
    return name

fdesc = GroupedField('parameter', label='Parameters',
                     names=['param'], can_collapse=True)


def setup(app):
    app.add_object_type('event', 'event', 'pair: %s; event', parse_event,
                        doc_field_types=[fdesc])
```

Then, I can refer events correctly.
