### ISSUE TITLE
The purpose of "!" that escape a cross reference linking and substitution by title text

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1474]
from #sphinx-doc IRC, Friday, May 23rd, 2014

> 00:14 <heyimalex> this is pretty cursory but, in roles.py, XRefRole: "if the first character is a bang, don't cross-reference at all"
> 
> 00:14 <heyimalex> seems like a really roundabout way of just creating a literal
> 
> 00:15 <heyimalex> would it be better if instead (withthout an explicit title) it just wrote out the title of the target doc without an actual link?
> 
> 00:16 <heyimalex> so you could do :doc:`!some/other/doc` and the title would be written instead of `some/other/doc`

src: `# if the first character is a bang, don't cross-reference at all`: 
https://github.com/sphinx-doc/sphinx/blob/80fd0f72d958c57070b35dcd9da33ece6a3589ed/sphinx/roles.py#L108

document: `* If you prefix the content with``!``, no reference/hyperlink will be created.`
https://bitbucket.org/birkenfeld/sphinx/annotate/1463240443/doc/markup/inline.rst#cl-37

I tried it.

```
* :doc:`foo/bar`
* :doc:`!foo/bar`
* :ref:`foo-bar`
* :ref:`!foo-bar`
```

it compiled into:

```
<li><a class="reference internal" href="foo/bar.html"><em>Hello</em></a></li>
<li><tt class="xref doc docutils literal"><span class="pre">foo/bar</span></tt></li>
<li><a class="reference internal" href="foo/bar.html#foo-bar"><em>Hello</em></a></li>
<li><em class="xref std std-ref">foo-bar</em></li>
</ul>
```

What is the purpose of the `bang` ?

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1474
- Originally reported by: Takayuki Shimizukawa
- Originally created at: 2014-05-25T17:28:54.574

**Comment by ncoghlan** [comment]
Just noting that the CPython docs make use of `!` to allow cross-references to C API functions and other interfaces that aren't currently documented (e.g. old What's New documentation may reference APIs that no longer exist, so adding a leading `!` is a straightforward way to tell Sphinx that the dangling reference is expected and OK)

**Comment by picnixz** [comment]
I think the question is now answered (after 9 years!). Thank you for digging up that issue so that we can close it!
