### ISSUE TITLE
Cannot create PDF due to error

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1478]
When I try to create a localized PDF by using `make -e SPHINXOPTS="-D language='tr'" latexpdf`, I receive the following error:

```

(/usr/share/texlive/texmf-dist/tex/latex/base/t1enc.def)<<t1.cmap>>)
(/usr/share/texlive/texmf-dist/tex/generic/babel/babel.sty

! Package babel Error: You haven't specified a language option.

See the babel package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              

l.329 ...ry to proceed from here, type x to quit.}

? h
You need to specify a language, either as a global option
or as an optional argument to the \usepackage command;
You shouldn't try to proceed from here, type x to quit.
```

However, this error is not reproducible if I just `make latexpdf`.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1478
- Originally reported by: [vgezer](https://bitbucket.org/vgezer)
- Originally created at: 2014-06-01T13:13:04.500

**Comment by shimizukawa** [comment]
_From [vgezer](https://bitbucket.org/vgezer) on 2014-06-01 12:27:01+00:00_

It was due to missing language packages.

**Comment by flo1o1** [comment]
Hi @shimizukawa, I have the same issue - which packages were missing?

**Comment by flo1o1** [comment]
Got it. For the record, for me the package `texlive-lang-german` was missing on Ubuntu. To see which language packages are available, run `apt-cache search texlive-lang-` on Debian based Linux distributions, check the result and install the missing language package with `sudo apt-get install <packagename>`.

**Comment by shimizukawa** [comment]
Hi @floeschie, actually this issue was made by `vgezer`, not by me.
Anyway, thanks for sharing the information!
