### ISSUE TITLE
option role only links to option directive in the same file

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1479]
Hi,

I am documenting an command option like this

```
#!rst

.. option::   --epub-embed-font=<DATEI>
```

When I refer to the option with

```
#!rst

:option:`--epub-embed-font` 
```

I only get a link reference when the directive is in the same file as the role.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1479
- Originally reported by: Jan Ulrich Hasecke
- Originally created at: 2014-06-03T15:54:38.075

**Comment by shimizukawa** [comment]
_From Jan Ulrich Hasecke on 2014-06-10 06:44:27+00:00_

The link does not work because it might be ambiguous. Sphinx just silently prints the option in italics. I would prefer a warning that the option needs the name of the program.

**Comment by tk0miya** [comment]
It seems this works fine with latest release.
I don't know when this was fixed.
So I'm closing this now.

Thanks,
