### ISSUE TITLE
latex math output is broken for inline math in chapters.

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1480]
We are trying to upgrade sphinx shipped in sage (sagemath.org) to the latest 1.2 release. However producing pdf documents is broken with this release. We get the following error:

```
Chapter 1.

Package hyperref Warning: Token not allowed in a PDF string (PDFDocEncoding):
(hyperref)                removing `math shift' on input line 170.


Package hyperref Warning: Token not allowed in a PDF string (PDFDocEncoding):
(hyperref)                removing `subscript' on input line 170.


! LATEX ERROR: BAD MATH ENVIRONMENT DELIMITER.

SEE THE LATEX MANUAL OR LATEX COMPANION FOR EXPLANATION.
Type  H <return>  for immediate help.
 ...                                              

l.170 ... index subgroups of \({\rm SL}_2(\ZZ)\))}

? 
! Emergency stop.
 ...                                              

l.170 ... index subgroups of \({\rm SL}_2(\ZZ)\))}

!  ==> Fatal error occurred, no output PDF file produced!
```

The issue is caused by the commit solving issue #929 were the delimiter for inline math was changed from "$...$" to "(...)", the later form being actually tex syntax rather then latex. The breakage occurs because the math is in a chapter header

```
\chapter{Arithmetic subgroups (finite index subgroups of \({\rm SL}_2(\ZZ)\))}
```

where the "(..)" construct is deemed fragile. Reading issue #929 I have trouble understanding the reason for changing the delimiter for math.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1480
- Originally reported by: François Bissey
- Originally created at: 2014-06-04T04:43:09.709

**Comment by shimizukawa** [comment]
_From Phil Tresadern on 2014-07-11 13:01:50+00:00_

I'm having the same problem. Is there an easy way to include the delimiter as user-defined option/setting in mathbase rather than it being hardcoded (mathbase.py line 91)?

**Comment by shimizukawa** [comment]
_From François Bissey on 2014-07-11 13:05:12+00:00_

Hi,

I am on leave until the 15th of July. I will be away from computer and off the internet completely
for most of that time.

If you have an issue with the BlueFern facilities and you are a UC collaborator
(project code bfcs######) please send an email at
bluefern@nesi.org.nz
and another member of the BlueFern team will be able to assist you.

If you have an issue with the BlueFern or other NeSI facilities and you are a NeSI user
or you want to enquire about NeSI, please send an email at
support@nesi.org.nz
and a member from the NeSI team will be able to assist you.

If you are a sage-on-gentoo user and you have a problem please open a new
issue on github at:
https://github.com/cschwan/sage-on-gentoo/issues

If you have a question/problem with sage please post on sage-devel or sage-support
mailing list on google group:
http://groups.google.com/group/sage-devel
http://groups.google.com/group/sage-support

## Best regards,

Dr François Bissey
BlueFern team - http://bluefern.canterbury.ac.nz
University of Canterbury
New Zealand

This email may be confidential and subject to legal privilege, it may
not reflect the views of the University of Canterbury, and it is not
guaranteed to be virus free. If you are not an intended recipient,
please notify the sender immediately and erase all copies of the message
and any attachments.

Please refer to http://www.canterbury.ac.nz/emaildisclaimer for more
information.

**Comment by shimizukawa** [comment]
_From Steven Trogdon on 2014-07-13 21:14:11+00:00_

[Phil Tresadern](https://bitbucket.org/ptresadern):

Not that it's the correct thing to do, but does the patch at http://trac.sagemath.org/ticket/16396#comment:22 solve your issue?

**Comment by xuhdev** [comment]
This issue can be solved by adding

``` latex
\robustify\(
\robustify\)
```

to the preamble.

**Comment by xuhdev** [comment]
@tk0miya Shall we incorporate the change (see my previous comment) into Sphinx?

**Comment by tk0miya** [comment]
@xuhdev Sorry, I could not determine that. Do you know that are there any side effects by adding it into preamble?
If not, I'll incorporate it.

**Comment by xuhdev** [comment]
@tk0miya You're right that this solution may have some unwanted global effects. A better solution would be `\protect`ing all `\(` and `\)` in section titles. However, I cannot find a way to determine whether the inline math is in a title in the mathbase extension (`latex_visit_math` function).

**Comment by tk0miya** [comment]
@xuhdev I'm not good at LaTeX. So your comments are very helpful for me.

You can check the `math` node is in a section title by following function:

```
def is_in_section_title(node):
    from sphinx.util.nodes import traverse_parent

    for ancestor in traverse_parent(node):
        if isinstance(ancestor, nodes.title) and isinstance(ancestor.parent, nodes.section):
            return True

    return False
```

**Comment by xuhdev** [comment]
@tk0miya Thanks for your suggestion. I've made PR #2188 to fix this issue.

**Comment by tk0miya** [comment]
PR #2188 is merged to stable. Thanks @xuhdev !
