### ISSUE TITLE
Add unittest integration

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1487]
Unit testing frameworks, although they all (unittest, py.test, nose) have ways of running standard doctests in both text files and docstrings, currently appear to have no way to run Sphinx doctests that use “testcode/testoutput” blocks. The documentation for sphinx.ext.doctest should be expanded to explain how to expose such tests as bare normal unittest objects so that all test frameworks can consume them. Currently, unless I am missing something, everyone who buys into Sphinx’s great “testcode/testoutput” mechanism of formatting tests — which saves so much hassle involving prompts that other doctest formats incur — break the ability to have a single test suite, and instead have to remember to run both their normal test runner then also “make doctest” in their documentation directory.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1487
- Originally reported by: Anonymous
- Originally created at: 2014-06-11T20:17:18.131

**Comment by shimizukawa** [comment]
_From Brandon Rhodes on 2014-06-11 18:18:17+00:00_

(Whoops—I was not logged in, so I want to go ahead and identify myself as the questioner!)

**Comment by mjstahlberg** [comment]
Does anyone know a workaround/solution for this? I'd love to integrate my ReST files using `testsetup`, `testcode` and `testoutput` with my unittest runner. Python's `doctest.DocFileSuite` does not recognize any of these directives.

**Comment by tk0miya** [comment]
AFAIK, there are no good way to integrate them. So workaround is to run both `pytest` and `make doctest`.

**Comment by jab** [comment]
In case it's helpful for anyone else, I've been using https://github.com/thisch/pytest-sphinx to work around this (though [not all options (e.g. skip-if) are fully supported yet](https://github.com/thisch/pytest-sphinx/issues/9)), and also recently discovered https://github.com/astropy/pytest-doctestplus which looks like another workaround (though also doesn't support skip-if... ([yet!](astropy/pytest-doctestplus#193):)).

**Comment by jab** [comment]
Hi @AA-Turner, you closed this as completed, but I couldn't find any sign that this has been fixed. Is the workaround mentioned in https://github.com/sphinx-doc/sphinx/issues/1487#issuecomment-551142954 no longer needed, or was this perhaps closed by mistake? If not, a link with info about the fix for this would be very helpful.

Thank you for your work on Sphinx and best wishes.
