### ISSUE TITLE
Docutils configuration

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#149]
Currently there is no mechanism (that I am aware of) to specify configuration values to the docutils module when it gets used.

Ideally a set of values in the 'conf.py' would be great.  I ran into this as an issue when trying to specify the 'report_level' in docutils.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/149
- Originally reported by: Anonymous
- Originally created at: 2009-05-01T18:54:11.231

**Comment by shimizukawa** [comment]
_From Kevin Horn on 2010-06-29 02:43:39+00:00_

**Bump!**

**Comment by shimizukawa** [comment]
_From [tpowers](https://bitbucket.org/tpowers) on 2010-08-14 20:18:23+00:00_

I had to do something very similar a few months ago. Search the source for "compact_lists" to see how to get a conf.py setting changed to a docutil Configuration Setting. Perhaps the technique can now be generalized?

**Comment by tk0miya** [comment]
Now sphinx refers `docutils.conf` on your config directory.
Thanks,
