### ISSUE TITLE
QtHelp generate html title element should have more context

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1492]
When generating QtHelp files for CMake, html files are first generated. The 'embedded' variable is true in the context when generating the html files from the templates (as appropriate). However, this causes Sphinx to create a html file with a <title> stripped of context: 

 https://github.com/sphinx-doc/sphinx/blob/dcd3408b8ab11d6677313748a0f95c9b02799be0/sphinx/themes/basic/layout.html#L21

The qhelpgenerator tool reads that title when generating the final qch file:

 http://code.woboq.org/qt5/qttools/src/assistant/help/qhelpgenerator.cpp.html#524

This means that in the case of CMake, the title is only 'include', not 'include -- CMake 3.0'.

This means that when the generated documentation is loaded in QtCreator, the title does not disambiguate if there are multiple APIs with different identifiers. See attachment before.png.

When the context is included in the title, it may be disambiguated in Qt Assistant. See after.png.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1492
- Originally reported by: Anonymous
- Originally created at: 2014-06-17T11:25:56.780

**Comment by AA-Turner** [comment]
Issue should be reported against `sphinxcontrib/qthelp`.

A
