### ISSUE TITLE
Trying to follow "Tutorial: Writing a simple extension" leads to PicklingError

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1493]
Steps to reproduce:

Attempt to follow

http://svn.python.org/projects/external/Sphinx-1.0.5/doc/ext/tutorial.rst

to implement todo or todolist (changing names to avoid any possible clashes), placing all code at the end of conf.py.  In your index.rst place your directive.  Run `make clean; make html`.

You will successfully read your codebase in preparation for documentation, but then fall foul of a PicklingError:  Can't pickle <class 'my_todo'>: attribute lookup **builtin**.my_todo failed.

The documentation is silent on this, and needs a lot more examples and definition of expected behaviour so that someone attempting to apply it can tell whether or not they are doing the correct thing.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1493
- Originally reported by: Anonymous
- Originally created at: 2014-06-18T11:57:21.728

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2014-06-19 04:45:21+00:00_

A newer version of the documentation is here: http://sphinx-doc.org/extdev/index.html#dev-extensions

The reason of the exception `PicklingError` is that you've implemented extension code into conf.py. Generally, conf.py is not proper place to develop a extension because instances of class that is implemented in conf.py can't pickling (similar issue: #1424). You should implement extensions code in another .py file like todo.py as the documentation mentioned.

**Comment by webknjaz** [comment]
FTR: this quirk is now documented in the tutorial: https://github.com/sphinx-doc/sphinx/pull/6754.
