### ISSUE TITLE
``sphinx-apidoc`` does not work with namespace packages

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1500]
I have following directory structure: 

```
foo 
- bar 
  - baz 
      __init__.py
      other_code.py
```

In this case `foo` and `foo.bar` are [python namespace packages](http://legacy.python.org/dev/peps/pep-0420/), and (at least in python 3.3+) I can import: `from foo.bar.baz import other_code`. 

However `sphinx-apidoc` does not detect `foo` being a namespace packages, and only way in which could re-generate apidocs was by adding `__init__.py` to `foo` and `bar`. 

It would be good if  `sphinx-apidoc` worked properly with namespace packages. 

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1500
- Originally reported by: Jacek Bzdak
- Originally created at: 2014-06-28T13:01:38.580

**Comment by hobson** [comment]
I have the same problem with a [namespace package](github.com/hobson/pug/) and its [subpackages](http://github.com/hobson/pug-ann)

**Comment by marius311** [comment]
I'm running into this same issue. Is there a solution or workaround for this at this point?

**Comment by hobson** [comment]
No workaround for me. Manually generating docs when they are needed (basically never)

**Comment by cblegare** [comment]
Bump @shimizukawa :
This is fixed, see #2949 : expected in the [1.5 release](https://github.com/sphinx-doc/sphinx/milestone/16) (by the end of 2016)

Please add to milestone and/or close.  Good job!

**Comment by tk0miya** [comment]
Thanks. I'd overlooked this issue.
Indeed, this is already fixed!
