### ISSUE TITLE
Sphinx website is broken

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1504]
I can access the sphinx website using a url of sphinx-doc.org, but not www.sphinx-doc.org.  The latter gives a server error.

Sorry if this is not the best place to report this.  I couldn't find a contact e-mail.  I had the same server error accessing http://pythonic.pocoo.org/, where I went looking for an e-mail address.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1504
- Originally reported by: Anonymous
- Originally created at: 2014-07-02T18:40:16.162

**Comment by tk0miya** [comment]
This server error is already fixed now.

Thanks,
