### ISSUE TITLE
html builder prefixes relative path to a data URI image when rst file is in subdirectory

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1505]
I'm currently using sphinx 1.2.2 as bundled at the moment in Debian unstable (1.2.2)

if the .rst file is inside a subdirectory and the image being referred to is a data-URI, the generated HTML has the subdirectory's path prefixed (and thus producing a broken image link)

e.g. example_dir/test.rst

.. |image2| image:: data:image/jpeg;base64,/9j/4AAQSkZJRgABAQ...

produces this HTML when make html/dirhtml/singlehtml is run:

<img alt="image2" src="example_dir/data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQ...

instead of the expected output:

<img alt="image2" src="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQ...

During the build there are warnings, e.g.

/path/to/example_dir/test.rst:10: WARNING: image file not readable: example_dir/data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQ...

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1505
- Originally reported by: Paolo Alexis Falcone
- Originally created at: 2014-07-03T13:04:10.365

**Comment by shimizukawa** [comment]
_From Paolo Alexis Falcone on 2014-07-04 10:12:56+00:00_

At the moment I made a modification in sphinx/environment.py that ignores data uri filenames when mangling the pathnames, will submit a patch later that will have more stringent checks for RFC2397 specs (as this patch is admittedly quite naive):

```
#!python

--- /usr/share/pyshared/sphinx/environment.py 2014-07-04 18:06:09.296611919 +0800 +0800
+++ /usr/share/pyshared/sphinx/environment.modified.py   2014-07-04 18:08:51.898609065
@@ -317,6 +317,9 @@
         source dir, while relative filenames are relative to the dir of the
         containing document.
         """
+        #Return filename for data uri paths"
+        if filename.startswith('data:'):
+            return filename, filename
         if filename.startswith('/') or filename.startswith(os.sep):
             rel_fn = filename[1:]
         else:

```

**Comment by shimizukawa** [comment]
_From Paolo Alexis Falcone on 2014-07-07 06:50:56+00:00_

I've given some thought about this, and it dawned to me that supporting data uri images can be better implemented in an extension to the htmlbuilder, as the implementation is specific to HTML and not applicable to the other builders (latex, epub, etc).

**Comment by tk0miya** [comment]
This was already fixed at https://github.com/sphinx-doc/sphinx/pull/3589. Closing.
