### ISSUE TITLE
Nested decorators and autodoc

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1506]
The following method **foo** will not be documented:

```
#!python

"""
.. automethod:: foo

"""

def decor(key):
    def wrapper(f):
        """wrapper"""
        def wrap(self, *args, **kwargs):
            """wrap"""
            return f(self, *args, **kwargs)
        return wrap
    return wrapper

[decor](https://bitbucket.org/decor)
def foo():
    """
    This is the foo method
    """
    pass
```

Only the wrapper method will be documented.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1506
- Originally reported by: Rickard Zachrisson
- Originally created at: 2014-07-04T11:30:50.650

**Comment by tk0miya** [comment]
Your implementation of decorator hides a original docstring of the method. This is problem of target code, not autodoc.
Please use `functools.wraps()` to keep docstring of original method.

Thanks,
