### ISSUE TITLE
Sidebar toggle chevrons misplaced on iOS Safari when zooming

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1511]
For example, open https://docs.python.org/3/library/json.html in iOS 7 Safari and pinch-zoom around a bit. The double chevron symbol in the button to close/expand the navigational sidebar gets misplaced.
Screenshot:
![image.jpg](https://bitbucket.org/repo/7zgG/images/2914101588-image.jpg)
Note how the double-chevron is positioned between two main body paragraphs. It can also be made to overlap the body text.

I have not checked whether this occurs on other mobile browsers.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1511
- Originally reported by: Chris Rebert
- Originally created at: 2014-07-14T18:43:08.297

**Comment by tk0miya** [comment]
I checked this with iOS 13.5.1. And it seems fine to me. I guess the double-chevron is a part of the sidebar (used to collapse sidebar). So this was an issue of the theme of python-doc. I don't know where it was resolved. Anyway, no reason to keep this opened. Thank you for reporting.
