### ISSUE TITLE
Stemming removes some words from search results

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1529]
Consider the word "ZFS". English stemming rules convert this into "zf", and since that's shorter than three characters `sphinx.search` doesn't bother indexing it at all.

I would say that if stemming results in a word not being indexed, the original word should be indexed instead, since stemming is a guess not a guarantee.

--itamarst (don't have my bitbucket credentials handy)

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1529
- Originally reported by: Anonymous
- Originally created at: 2014-08-05T22:56:31.715

**Comment by shibukawa** [comment]
#2621 fix this issue

**Comment by shimizukawa** [comment]
Thanks!
