### ISSUE TITLE
Test timings in doctest output

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1532]
It would be useful if, along with the test status, the doctest output would contain timings for individual tests.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1532
- Originally reported by: Martyn Gigg
- Originally created at: 2014-08-08T15:13:49.833

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2014-08-12 08:24:27+00:00_

What do you mean? Please describe a scenario and current weak point detail.

**Comment by shimizukawa** [comment]
_From Martyn Gigg on 2014-08-12 12:35:37+00:00_

In our standard C++ unit tests, our framework reports the timing of individual test methods within a class. Extracting this information to a C.I. server, such as Jenkins, then allows us to monitor timings of all of these tests and identify those tests that start to show themselves as taking too long.

We already have a parser that converts the Sphinx doctest output to JUnit-style XML and it would be very useful for us to be able to add information about the timing of each _testcode_ case with that output.

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2014-08-12 14:21:15+00:00_

Ah, I got. I found a example::

```
<?xml version="1.0" ?>
<testsuite name="info.classmethod.testing.HogeTest" tests="4" errors="1" failures="1" time="0.003">
  <testcase classname="info.classmethod.testing.HogeTest" name="testCase01" time="0.001" />
  <testcase classname="info.classmethod.testing.HogeTest" name="testCase02" time="0.001">
    <failure type="java.lang.AssertionError" message="test failed" >...
```

Your request is that you want to display the elapsed time (as `time` attribute in above example) for each doctest, isn't it? 

For now, I don't know when it will be implemented. However if you have a request for the output format, please let me know. Thanks!

**Comment by shimizukawa** [comment]
_From Martyn Gigg on 2014-08-12 14:25:04+00:00_

Yes, that's it. If the timings could be included in the display of the output and in the output.txt file that would be enough.

I see there is already an open issue, #1200, surrounding an option to write JUnit-style xml so I wasn't including that here.

Thanks!

**Comment by AA-Turner** [comment]
This hasn't been commented on for seven years, if there's still demand please open a new issue or PR.

A
