### ISSUE TITLE
Word wrap long lines in Latex verbatim blocks

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1534]
For example `literalinclude` blocks are nicely displayed in PDF output. But if a file contains a long line it just overflows, gets cut off and is not readable a all.

Apparently there's nothing I can do as a user (with e.g. additional latex preamble) as Sphinx creates verbatim blocks which do not suport word wrapping.

The recommended Latex solution seems to be using some other package instead(like `lstlisting` or `minted`). Could Sphinx get an option to switch to some other package?

Or is there some other trick to get long lines to wrap in code blocks in PDFs?

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1534
- Originally reported by: Anonymous
- Originally created at: 2014-08-15T09:43:07.191

**Comment by shimizukawa** [comment]
_From Peter Suter on 2014-09-29 09:15:59+00:00_

Actually `minted` [can't do it](http://tex.stackexchange.com/questions/10239/breaking-long-lines-using-latex-with-minted-and-pygments) either apparently, and `lstlistings` does not seem to use pygments but its own system.

**Comment by jnaulty** [comment]
I found this helpful as to what direction to go towards:
http://comments.gmane.org/gmane.comp.python.sphinx.devel/5961

**Comment by tk0miya** [comment]
Now #2343 is merged. This is already resolved.

**Comment by mgielda** [comment]
This doesn't work with long lines between double backticks (like long path/to/file/with/long/filename sequences)... Is there any way to get a similar result with inline verbatim text?

**Comment by jfbu** [comment]
There are some partially satisfying ways. But can you open new issue, because this one is closed.
