### ISSUE TITLE
Napoleon ignores parameter if description is empty

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1542]
With numpy-style docs, and `napoleon_use_param = True`, if we have a function documented like

```
    summary

    Parameters
    ----------
    x :

    y : int

    parms :
       other summary
```

generates this:

```
summary



:type y: int
:param parms: other summary
```

Notice that we are missing `:param x:` and `:param y:` lines.  This means that x and y do not show up in the generated html file.  This problem is mitigated when `napoleon_use_param = False`.  The problem appears to lie in the if statement at https://github.com/sphinx-doc/sphinx/blob/de0b87be3e3504c744ad9f589ae83f324a66cd35/sphinx/ext/napoleon/docstring.py#L294  If the parameter description is empty (i.e., `line==''`), then only an empty string is output.  I think perhaps the first line of results should always have `prefix` appended.  Then I think we'd have `:param x:` and `:param y:` lines output above.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1542
- Originally reported by: Anonymous
- Originally created at: 2014-08-21T21:47:01.537

**Comment by shimizukawa** [comment]
_From [jasongrout](https://bitbucket.org/jasongrout) on 2014-08-23 04:48:10+00:00_

Thanks for taking a look at this (I submitted it, but didn't have my login credentials when I did).  I think just switching the two tests `if line` and `if i==0` might be sufficient.

**Comment by shimizukawa** [comment]
_From Nils Gran on 2014-10-11 13:53:22+00:00_

I have the same problem but with Google style args.

This fix seems to be working for me:

Package: napoleon, 
Module: docstring, 
Class: GoogleDocString, 
Method: _block_format

```
#!python

            # Gutting the for and replace with new if-statement:
            for i, line in enumerate(lines):
                if i == 0:
                    result_lines.append(prefix + line)
                elif line:
                    result_lines.append(padding + line)
                else:
                    result_lines.append('')

```

**Comment by jasongrout** [comment]
I agree that the above if/elif/else fix looks correct (and not my suggested fix at https://github.com/sphinx-doc/sphinx/issues/1542#issuecomment-68590640)

**Comment by birkenfeld** [comment]
Thanks!
