### ISSUE TITLE
:orphan: options sometimes shows up

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1545]
More precisely, I use the `:orphan:` option in RST files that are not used in the `toctree`, but are included by other files (for factorizing role declarations, for example).

If the `include` directive is at the top of the including file, then no problem, the `:orphan:` does not appear, as expected. However, if the `include` directives appears at other places, then the `:orphan:` option shows up at the beginning of the included content.

Although I guess I understand why this happens, it seems to contradict [the documentation](http://sphinx-doc.org/markup/misc.html?highlight=orphan#file-wide-metadata) stating that:

>  In Sphinx, a field list preceding any other markup (...) is not displayed in the output.

Also, this is in my opinion a bug worth fixing, as included files are an obvious use case for the `:orphan:` option.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1545
- Originally reported by: Pierre-Antoine Champin
- Originally created at: 2014-08-26T18:17:41.807

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2014-09-02 14:32:08+00:00_

I create a small project to reproduce the issue.

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2014-09-02 14:43:59+00:00_

It might be a docutils specification (or limitation), not a bug.

`docinfo` reST syntax is a same as `field-list`. When a field-list placed at the top of the file, it will become `docinfo`.

BTW, `include` directive include another file into the caller document. In this case, these 2 files are interpreted into 1 doctree intermediate structure. At this time, `:orphan:` is not docinfo anymore.

**Comment by smithsp** [comment]
I agree that having an `:orphan:` field would be very useful for files that are included.  It should be stripped from the top of the included files.
