### ISSUE TITLE
Automatically enumerate public classes in a module/package

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1558]
Currently, I am writing this explicitly, but it is hard coded and hence not good practice. It would be nice to have a way to automatically get the classes listed.

.. module:: mypackage

.. autoclass:: Foo
    :members:

.. autoclass:: Bar
    :members:

.. autoclass:: Baz
    :members:

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1558
- Originally reported by: Laszlo Papp
- Originally created at: 2014-09-03T19:11:00.218

**Comment by shimizukawa** [comment]
_From Robert Lehmann on 2014-09-04 06:09:02+00:00_

What's wrong with [automodule](http://sphinx-doc.org/ext/autodoc.html#directive-automodule)?

**Comment by shimizukawa** [comment]
_From Laszlo Papp on 2014-09-04 09:30:55+00:00_

So that my package contains this **init**.py file:

from mypackage.foo import Foo

from mypackage.bar import Bar

from mypackage.baz import Baz

Could you please write down a simple example how automodule would work in that case?

**Comment by shimizukawa** [comment]
_From Robert Lehmann on 2014-09-04 11:49:59+00:00_

The [documentation for the autodoc extension](http://sphinx-doc.org/ext/autodoc.html) can be found online;  usage questions are better suited to the [sphinx-users mailing list](https://groups.google.com/forum/#!forum/sphinx-users) than the bug tracker.

Nevertheless, I have prepared a minimal example for you:

```
#!restructuredtext
.. automodule:: mypackage
   :members:
   :imported-members:
```

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2014-09-04 12:34:49+00:00_

So far, nobody mentioned external extensions. Can you tell us what does not work with the example that Robert gave you?

**Comment by shimizukawa** [comment]
_From Laszlo Papp on 2014-09-04 16:12:34+00:00_

I had literally copied and pasted this into my index.rst, but then I got an empty html page with regards to my actual documentation.

**Comment by shimizukawa** [comment]
_From Laszlo Papp on 2014-09-05 13:47:25+00:00_

Any advice? Is there a googlegroups free mailing list? I do not own an account that allows me to post there, unfortunately, and I would rather not do it if possible just for the sake of this.

The aforementioned code did not work for me, sadly.

**Comment by shimizukawa** [comment]
_From Laszlo Papp on 2014-09-05 15:25:36+00:00_

Just in case, this did not work:

```
#!python

.. Test documentation master file, created by
   sphinx-quickstart on Wed Sep  3 11:42:18 2014.
   You can adapt this file completely to your liking, but it should at least
   contain the root `toctree` directive.

Welcome to Test's documentation!
================================

Contents:

.. toctree::
   :maxdepth: 2

.. automodule:: mypackage
   :members:
   :imported-members:


Indices and tables
==================

* :ref:`genindex`
* :ref:`modindex`
* :ref:`search`
```

This did work:

```
#!python

.. Test documentation master file, created by
   sphinx-quickstart on Wed Sep  3 11:42:18 2014.
   You can adapt this file completely to your liking, but it should at least
   contain the root `toctree` directive.

Welcome to Test's documentation!
================================

Contents:

.. toctree::
   :maxdepth: 2


.. module:: mypackage

.. autoclass:: Foo
    :members:


Indices and tables
==================

* :ref:`genindex`
* :ref:`modindex`
* :ref:`search`


```

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2014-09-05 16:16:58+00:00_

Thanks. This should work as you showed; we'll investigate why it didn't.

**Comment by tk0miya** [comment]
I don't know what was happened in the original report. But, nowadays, autodoc, autosummary and apidoc become matured. So this would be already fixed, I guess. So I'm closing this now.
Please file a new issue if you've still seen the trouble.

Thanks,
