### ISSUE TITLE
more info fields for Python domain

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1559]
Hi,
wouldn't be nice to have method info fields to add virtual qualifier? Something like

```
.. method:: my_method
   :virtual:

----------------------------------------
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1559
- Originally reported by: Andrea Cassioli
- Originally created at: 2014-09-05T11:21:26.750
```

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2014-09-05 09:26:58+00:00_

"virtual" is not really a common term for Python methods; I don't want to introduce terms in Sphinx that aren't used in the community first.

**Comment by tk0miya** [comment]
It seems there are no alternative keywords for a long time. I'm closing this because of no chance to implement it.
