### ISSUE TITLE
Custom roles are not properly translated into LaTeX

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1564]
# Problem

The LaTeX-command to handle custom roles (or better: its class-directives) is not working as expected.
# Detailed explanation and example
## Working example with non-custom role

With the role _strong_ one can markup some text like this

```
#!reST
:strong:`This is emphasized.`
```

which correctly gets translated into LaTeX:

```
#!LaTeX
\textbf{This is emphasized.}
```
## Non-working example with custom role

However, if using a custom role _boldanditalics_

```
#!reST
.. role:: boldanditalics
   :class: bold italics

:boldanditalics:`This is bold and italics.`
```

the generated LaTeX-code looks like this:

```
#!LaTeX
\DUspan{bold,italics}{This is bold and italics.}
```

And in the generated PDF this sentence is neigher bold nor italics.

After inspecting the definition of **\DUspan** in _sphinx.sty_ I figured, that I need to provide two commands _\docutilsrolebold_ and _\docutilsroleitalics_ for **\DUspan** to do more than just printing the original text unmodified:

```
#!LaTeX
\newcommand{\docutilsrolebold[1]{\textbf{#1}}
\newcommand{\docutilsroleitalics[1]{\textit{#1}}
```

Sadly, this leads to errors when trying to generate the PDF.
(With only one class-directive for the role it would not fail but still only unmodified text would be printed in the PDF.)
# Solution / Patch

The solution is to replace the implementation of **\DUspan** in _sphinx.sty_ by the following:

```
#!LaTeX
&#37; Inspired by docutils.writers.latex2e but fixed and improved.
\providecommand{\DUspan}[2]{&#37;
  {&#37; group ("span") to limit the scope of styling commands
    &#37; Reverse order of class-names (if more than one received).
    \def\class@names{}&#37;
    \[False](https://bitbucket.org/for)\node@class@name:=#1\do{&#37;
      \ifx \class@names \empty&#37;
        \edef\class@names{\node@class@name}&#37;
      \else&#37;
        \edef\class@names{\node@class@name,\class@names}&#37;
      \fi&#37;
    }&#37;  
    &#37; Store the content for the class-names in a variable of its own and build
    &#37; up the nested command-chain to modify the content. However, make sure not
    &#37; to expand the content while building up the nested command chain!
    \def\content@class@names{#2}&#37;
    \protected@edef\cmd@chain{\protect\content@class@names}&#37;
    \[False](https://bitbucket.org/for)\node@class@name:=\class@names\do{&#37;
      \ifcsname docutilsrole\node@class@name\endcsname&#37;
        \protected@edef\cmd@chain{&#37;
          \csname docutilsrole\node@class@name\endcsname{\cmd@chain}&#37;
        }&#37;
      \fi&#37;
    }&#37;  
    &#37; Now, the command-chain is build up and we can call it
    &#37; (and thereby expand the content).
    \cmd@chain
  }&#37; close "span"
}

```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1564
- Originally reported by: Deniz Bahadir
- Originally created at: 2014-09-12T17:30:16.040

**Comment by shimizukawa** [comment]
_From Ignacio Fernández Galván on 2014-09-15 12:53:24+00:00_

I'm finding another problem if I use a custom role in a title:

```
#!rst


.. role:: sc

An introduction to :sc:`test`
=============================

:sc:`Test` is a *good* program.
```

Compilation fails with:

```
#!none

! Undefined control sequence.
<argument> \node@class@name 

l.125 ...ter{An introduction to \DUspan{sc}{test}}
```

This one can be fixed making **\DUspan** robust:

```
#!latex


\RequirePackage{fixltx2e}
\MakeRobust\DUspan
% I'm not sure if there is a better way
```

But another problem appears here:

```
#!rst

.. role:: sc

An introduction to :sc:`test`
=============================

:sc:`Test` is a *good* program.

An introduction to :sc:`test`
=============================

:sc:`Test` is a good program.
```

Now the _second_ title fails with:

```
#!none

! Missing \endcsname inserted.
<to be read again> 
                   \node@class@name 
l.130 ...ter{An introduction to \DUspan{sc}{test}}
```

or, with your patch:

```
#!none

! Argument of \@iforloop has an extra }.
<inserted text> 
                \par 
l.130 ...ter{An introduction to \DUspan{sc}{test}}
```

And this only happens because of the italics between the two titles. If I remove the italics (or the **\emph** in the generated LaTeX code) then all is fine.

Unfortunately I don't have a solution, and I have no idea why this happens.

**Comment by shimizukawa** [comment]
_From Ignacio Fernández Galván on 2014-09-16 09:31:17+00:00_

It seems the problem is caused by the use of **\DUspan** in PDF strings. The complete fix can be something like this:

```
#!latex

% From docutils.writers.latex2e
\providecommand{\DUspan}[2]{%
  {% group ("span") to limit the scope of styling commands
   \texorpdfstring{% Hide formatting from strings used in PDF bookmarks
    \[False](https://bitbucket.org/for)\node@class@name:=#1\do{%
    \ifcsname docutilsrole\node@class@name\endcsname%
      \csname docutilsrole\node@class@name\endcsname%
    \fi%
    }%
    {#2}% node content
   }{#2}% safe version for PDF strings
  }% close "span"
}
\RequirePackage{fixltx2e}
\MakeRobust\DUspan
```

(I only added the **\texorpdfstring** macro, and the **\RequirePackage** line could be moved up with other similar ones.)

By the way, the patch suggested in the first post is unneeded, the problem is that the formatting commands are not correctly defined, they should have no arguments. This works fine:

```
#!latex

\newcommand{\docutilsrolebold}{\bfseries}
\newcommand{\docutilsroleitalics}{\itshape}
```

and, in any case, the syntax of **\newcommand** with arguments is missing a closing brace before **[1]**

**Comment by shimizukawa** [comment]
_From Deniz Bahadir on 2014-09-16 14:59:46+00:00_

Good catch with the missing closing brace in **\newcommand**. But that was just a typo in my bug-report. In my code-tests I did not miss the closing brace. :-)

Your solution with **\texorpdfstring** and **\MakeRobust** fixes the problems you mentioned, which is good. It still supports multiple classes/style-commands, too, which is even better.

However, I would still prefer to extend my solution with it (instead of the original one), as it allows custom formatting commands **\docutilsrole**_<cmd-name>_ to work with an argument.

For formatting text in bold or italics it might be ok to have commands without an argument (as **\bfseries** can be used instead of **\textbf** and **\itshape** instead of **\textit**). However, for some other formatting there might not exist a command without arguments. The **\sout** command from the _ulem_ package (which allows to strike through a text) is a good example for such a command that requires an additional argument.

Therefore, I would recommend to replace the implementation of **\DUspan** with the following:

```
#!LaTeX
% Inspired by docutils.writers.latex2e but fixed and improved.
\providecommand{\DUspan}[2]{%
  {% Group ("span") to limit the scope of styling commands.
    \texorpdfstring{% Hide formatting from strings used in PDF bookmarks.
      % Reverse order of class-names (if more than one received).
      \def\class@names{}%
      \[False](https://bitbucket.org/for)\node@class@name:=#1\do{%
        \ifx \class@names \empty%
          \edef\class@names{\node@class@name}%
        \else%
          \edef\class@names{\node@class@name,\class@names}%
        \fi%
      }%  
      % Store the content for the class-names in a variable of its own and
      % build up the nested command-chain to modify the content. However, make
      % sure not to expand the content while building up the nested command
      % chain!
      \def\content@class@names{#2}%
      \protected@edef\cmd@chain{\protect\content@class@names}%
      \[False](https://bitbucket.org/for)\node@class@name:=\class@names\do{%
        \ifcsname docutilsrole\node@class@name\endcsname%
          \protected@edef\cmd@chain{%
            \csname docutilsrole\node@class@name\endcsname{\cmd@chain}%
          }%
        \fi%
      }%  
      % Now, the command chain is built up and we can call it
      % (and thereby expand the content).
      \cmd@chain%
    }{#2}% Safe version for PDF strings.
  }% Close "span".
}
\RequirePackage{fixltx2e}
\MakeRobust\DUspan
```

By doing that, all commands with or without an additional argument are supported. E.g. all of the following commands will be supported:

```
#!LaTeX
\newcommand{\docutilsrolebold}{\bfseries}
\newcommand{\docutilsroletextbf}[1]{\textbf{#1}}
\newcommand{\docutilsroleitalics}{\itshape}
\newcommand{\docutilsroletextit}[1]{\textit{#1}}
\usepackage{ulem}
\newcommand{\docutilsrolestrike}[1]{\sout{#1}}
```

**Comment by shimizukawa** [comment]
_From Ignacio Fernández Galván on 2014-09-16 16:16:18+00:00_

Yes, I also find your solution could be useful when I tried to make the text uppercase. I ended up trying the switch to luaLaTeX just to test [this](http://tex.stackexchange.com/questions/100336/towards-a-ucshape-and-textuc-command-for-uppercase-text-xetex-luatex).

I'll try your complete solution and report back if I find any issue.

**Comment by shimizukawa** [comment]
_From Ignacio Fernández Galván on 2014-09-17 14:54:44+00:00_

Sadly, the code doesn't work with **\MakeUppercase**, so I may have to use luaLaTeX after alll.

**Comment by tk0miya** [comment]
Now `\DUrole` has been improved using docutils' implementation. So this issue is no longer needed. Please file a new issue if you have still troubles.
Thanks,
