### ISSUE TITLE
Add an option to throw a warning when Pygments throws an ErrorToken

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1565]
Currently, the behavior of Sphinx is to highlight the code-block as none in case the configured lexer throws an ErrorToken. It would be great if it could trigger a warning in this case as well (this could be subject to a configuration setting). It would allow spotting more easily code blocks which cannot be highlighted properly because of a mistake.
What do you think about it ?

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1565
- Originally reported by: Christophe Coevoet
- Originally created at: 2014-09-13T13:31:55.630

**Comment by tk0miya** [comment]
I add warnings at 0329edc.
It always warns if could not parsed.

Thank you for reporting.

**Comment by stevepiercy** [comment]
Just wanted to say thank you for this change, because it helped me catch a couple of mistakes in our docs.

**Comment by birkenfeld** [comment]
Nice, thanks for the feedback!

**Comment by tk0miya** [comment]
:smile:

**Comment by saulshanabrook** [comment]
Currently pygments cannot parse TypeScript with JSX syntax in it. How can I set the warn flag to true to have this not error on my build?

**Comment by tk0miya** [comment]
@saulshanabrook  I just added `:force:` option to code directives in Sphinx-2.1.0. I believe it helps your case.
https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-code-block

**Comment by saulshanabrook** [comment]
@tk0miya Thank you! That works wonderfully.
