### ISSUE TITLE
mathjax and epub

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1570]
I'm building epub and html versions of doc.  I'm currently using sphinx.ext.mathjax for math rendering, however it doesn't seem to work with epub.  I'd prefer not to use sphinx.ext.pngmath  for everything.  Is it possible to bundle mathjax in epub? Failing that, can I specify a math extension on a per builder basis?

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1570
- Originally reported by: Nathan Charles
- Originally created at: 2014-09-17T20:11:38.499

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2014-09-17 18:15:09+00:00_

Good question. Roland, what would you say is the preferred way to embed math in EPUB?

**Comment by shimizukawa** [comment]
_From Nathan Charles on 2014-09-23 19:29:10+00:00_

Any update on this?

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2014-09-24 00:29:09+00:00_

In my short investigation,
- many EPUB reader doesn't support Javascript. 
- EPUB3 supports SVG and MathML [1][2].

However, implementing Sphinx EPUB3 support is little hard. For a while, we need to use pngmath for EPUB output. How do you think [Roland Meister](https://bitbucket.org/rolmei)?

[1] http://www.idpf.org/epub/30/spec/epub30-changes.html#sec-new-changed-svg

[2] http://mpsltd.wordpress.com/2011/05/25/epub-3-vs-epub-2-0-2/

**Comment by shimizukawa** [comment]
_From Roland Meister on 2014-09-25 18:33:33+00:00_

This is also my impression. I think we have to live with pngmath for the epub2 builder.
Does anyone know if the second alternative, using different math extensions, is possible?
I haven't used the math extensions up to now...

**Comment by shimizukawa** [comment]
_From Ignacio Fernández Galván on 2014-09-28 08:22:09+00:00_

EPUB2 supports SVG too (but not javascript)

**Comment by shimizukawa** [comment]
_From Andrea Cassioli on 2014-11-29 20:36:40+00:00_

Hi I have a similar problem. I think that as a first step there should be a way to customize conf.py so that png or mathjax can be selected depending on the builder. In some sense is a more general issue...

**Comment by tk0miya** [comment]
We will introduce `sphinx.ext.imgmath` in Sphinx-1.4 (unreleased yet).
It enables to store formulas as SVG format.

**Comment by ax3l** [comment]
@tk0miya How can I use `sphinx.ext.imgmath` for epub only im my `conf.py`? :)

**Comment by tk0miya** [comment]
@ax3l 
There are no good way to do that. But you can do it with `-D` option of `sphinx-build` like following:
```
$ sphinx-build -b epub -D extensions=sphinx.ext.imgmath,...(any other extensions you used)... srcdir outdir
```

**Comment by ax3l** [comment]
@tk0miya thank you for the hint!
Do you by coincidence know if one can set such epub specific extensions with readthedocs?

It would still be awesome to control extensions per builder in `conf.py`. shall I open an issue for that?

**Comment by tk0miya** [comment]
There are no way to switch extensions per builder inside sphinx. So it is also difficult in readthedocs.

>shall I open an issue for that?

Yes, please. It's reasonable.
