### ISSUE TITLE
var support for cpp domain

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1577]
For a while, c:var seemed sufficient to document C++ variables too, but it isn"t sufficient anymore now that we have constexpr variables. It would be great to add cpp:var so that constexpr variables can be correctly documented.

When Sphinw supports templates, an hypothetical cpp:var could also be used to document C++14 variable templates.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1577
- Originally reported by: Morwenn Ed
- Originally created at: 2014-09-24T13:05:38.226

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2014-09-24 13:29:01+00:00_

I'm not familiar to latest C++ specification, however the latest 1.3 version (not released yet) can handle extra C++ expressions than 1.2.x. Please check the behavior by using default branch's tip version. Also this is a test code to parsing C++ expressions: https://github.com/sphinx-doc/sphinx/blob/88540e9a3b7d3a9f323b83b2c5cd6342ee037572/tests/test_domain_cpp.py#L43

If it satisfy your demand, I'll close this ticket. Thanks!

**Comment by shimizukawa** [comment]
_From Morwenn Ed on 2014-09-24 21:16:02+00:00_

I meant that there does not seem to be any way to document a C++ variable that is not a member of a class. Until there I used c:var to document a C++ variable that wasn't the member of a class, but since C variables can't be constexpr, it is not sufficient anymore. Maybe I am mistaken and cpp:member is also meant to document variables that are not members of a class? Here is an example of what I want to document (a non-member constexpr variable):

```
#!cpp

constexpr double M_PI
```

**Comment by shimizukawa** [comment]
_From Jakob Lykke Andersen on 2014-12-03 19:50:21+00:00_

Even though the directive is called `cpp:member` it also works for variables in namespace scope (maybe there should be an alias called `cpp:var`).
For example:

```
.. cpp:class:: A

   .. cpp:member:: int a

      The member variable `A::a`, i.e., `a` in class `A`.

.. cpp:member:: int A::b

   The variable `A::b`, i.e., `b` in namespace `A`, which happens to actually be a "class namespace".

.. cpp:member:: constexpr double M_PI

   A global variable.
```

The use of `constexpr` is supported in 1.3 (both for variables and functions).

**Comment by shimizukawa** [comment]
_From Morwenn Ed on 2014-12-04 12:14:01+00:00_

Ok, thank you, that's clear now. I wouldn't have expected "member" to also cover the namespace-level variables. Thanks for the carification; it may be a good idea to make a note about it in the doc.

**Comment by jakobandersen** [comment]
There is now a `cpp:var` directive (and role). It works exactly like `cpp:member`.
