### ISSUE TITLE
Apply translations before "include"

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1587]
I have the following problem: I have 4 documents included into my index.rst file. Each of these 4 documents contains a small header (several lines of text) and a number of ..include:: directives which pull in the subsections located in separate .rst files.

Currently Sphinx behaves as follows. When I generate the .po files, it includes all the subsections into the section file first, and then generates a large .po file for this section file. So I have 4 big .po files instead of a nuber of small .po files corresponding to each separate .rst file.

Also, if I generate the .po files for each of the small subsection files, these translations are not applied when building the final html document.

So my suggestion is to make Sphinx generate the .po files for each of the small included files, and apply those translations _before_ merging these small rst-files into a big one.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1587
- Originally reported by: [v_2e](https://bitbucket.org/v_2e)
- Originally created at: 2014-10-06T10:33:40.915

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2014-10-19 08:11:55+00:00_

Thanks for your suggestion. 

I respect your opinion, but it is difficult because `include` processing is done in earlier stage rather than sphinx gettext builder processing.

I'll keep this issue New for somebody who implement this feature.

**Comment by tk0miya** [comment]
I agree that it is very hard to implement such a feature. It seems nobody tries to rewrite whole of Sphinx for a long time. So now I'm closing this now.
Please send a pull request if you try to challenge this topic :-)
