### ISSUE TITLE
:type: or :rtype: value should only link to actual types

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1592]
With

```
#!python

:type a_param: any
```

entry, a link is generated for 'any' to the function any().

The use case is when the method really does act on any kind of thing whatsoever, including say instances of old-style classes, classes, etc.

Of course, an alternative is to specify

```
#!python

:type a_param: instance or object or type
```

which should probably cover most things.

But, I still think that, in a place where only a type should go, sphinx should avoid setting links to non-types (like any, which is a value).

It might be just as easy as to check that the type of the type value is actually type.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1592
- Originally reported by: the mulhern
- Originally created at: 2014-10-09T14:23:29.161

**Comment by rhelmot** [comment]
I would like to bump this and request that it be made a priority to someone. This is a pretty obnoxious bug affecting our docs.

If it's simple, I can do it myself, but I'll need a few pointers on where to start.

**Comment by rouge8** [comment]
I think this might be fixed by https://github.com/sphinx-doc/sphinx/pull/3933

**Comment by rhelmot** [comment]
This is in fact fixed!

**Comment by shimizukawa** [comment]
Thanks for letting me know!
