### ISSUE TITLE
DOC: link to awesome-sphinxdoc

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1598]
https://github.com/yoloseem/awesome-sphinxdoc is an outstanding third-party resource.

Would a link from e.g. http://sphinx-doc.org/extensions.html be appropriate?

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1598
- Originally reported by: Wes Turner
- Originally created at: 2014-10-18T09:21:12.356

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2014-10-18 07:27:37+00:00_

Linking, sure. But why not contribute that list to core docs? Are you interested in asking the author?

**Comment by tk0miya** [comment]
Already done in #4690.
