### ISSUE TITLE
epubs in iBooks don't obey font-related CSS

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1604]
See attached patch.

This is usually seen in the context of not obeying embedded fonts, but it impacts things like code blocks as well.

http://stackoverflow.com/questions/13575074/unable-to-see-the-embedded-fonts-in-ibook-3-0-2 points to this being the answer (as well as several other sites).

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1604
- Originally reported by: Bruce Mitchener
- Originally created at: 2014-10-21T09:56:05.254

**Comment by shimizukawa** [comment]
Recovering attached file: [epub_sphinx.diff.txt](https://github.com/sphinx-doc/sphinx/files/160215/epub_sphinx.diff.txt)

**Comment by tk0miya** [comment]
@shibukawa Could you give us some advice?

**Comment by shibukawa** [comment]
https://itunesconnect.apple.com/docs/iBooksAssetGuide5.1Revision2.pdf

Apple provides some extra meta tags. We should check this including this patch.
