### ISSUE TITLE
Python 3.4 enum classes not working

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1609]
I tried something like

``` rst

.. autoclass:: lensfunpy.ModifyFlags
   :members:
   :undoc-members:
```

but it only prints the class name without the enum members. Does this need some new support or does the enum implementation need to be more doc-friendly?

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1609
- Originally reported by: Maik Riechert
- Originally created at: 2014-10-27T21:50:29.850

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2014-10-27 20:53:03+00:00_

enums are special enough that I think they warrant some special casing.

**Comment by letmaik** [comment]
Seems to work partly now. It prints the enum members but the members' doc string is not printed.

**Comment by rossengeorgiev** [comment]
Does it work with the `enum34` module, which is a backport for older version of `python`?

**Comment by rossengeorgiev** [comment]
@neothemachine what version are you using? Doesn't work for me on neither py2 or py3 with latest version from master

**Comment by letmaik** [comment]
@rossengeorgiev See https://pythonhosted.org/rawpy/api/enums.html Uses sphinx 1.4

**Comment by rossengeorgiev** [comment]
@naokisatoname That's strange. I get no members listed, even with `:undoc-members:`. If I specify a docstring to any member the value is showing as `None`. If I list members with `:members: a b c` those members show up in docs as expected with their correct value.

Python3 with `sphinx 1.5a0`

**Comment by rossengeorgiev** [comment]
After looking into the sphinx source code, I notice that if it looks up the members using `__dict__`, doesn't contain any members. However, if I add `:inherited-members:`, it will lookup the members using `dir()`, which will in fact return the members. Works for me on py2.7 with sphinx 1.4 and py3.4 with sphinx 1.5a1.

Adding `:inherited-members:` will show `Enum` members as expected, including docstrings.

**Comment by shimizukawa** [comment]
Confirmed. It works fine to me too.
- Sphinx-1.5a2
- Python-3.5.2
- Windows 10

foo.py:

``` python
import enum


class E(enum.Enum):
    """
    this is enum class
    """

    val1 = 1  #: doc
    val2 = 2  #: doc


Animal = enum.Enum('Animal', 'ant bee cat dog')  #: this is doc string
```

index.rst:

``` rst
.. automodule:: foo
   :members:
   :undoc-members:
```

Result:
![image](https://cloud.githubusercontent.com/assets/151623/19480645/248da7c0-9586-11e6-9338-e06a9974472c.png)

**Comment by shimizukawa** [comment]
Actually, I don't know which sphinx versions are not good. Anyway, it works with sphinx-1.4 and 1.5.

**Comment by shimizukawa** [comment]
Sphinx project I tested with: [1609.zip](https://github.com/sphinx-doc/sphinx/files/536458/1609.zip)

**Comment by rossengeorgiev** [comment]
Would it be possible to display just the value? Enum will create this verbose repr `<Animal.ant: 1>`, which can get pretty difficult to read when class and property names are long. Especially when there are a dozen or more properties.

**Comment by shimizukawa** [comment]
@rossengeorgiev It might be possible. However it is another feature request. Can you create new feature request issue please?

**Comment by evanunderscore** [comment]
I get this problem in Python 3.4.3 and 3.4.4 but not 3.5.2, and not with 2.7.11 using enum34 from PyPI.

**Comment by shimizukawa** [comment]
@evanunderscore confirmed. I created another issue #3255. Thanks.
