### ISSUE TITLE
Included toctrees fail when placed after a heading

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1613]
Here's my main index.rst:

```
#!rst

.. toctree::
    :maxdepth: 1

    introduction/index
    how_to/index
    topics/index
```

And here's introduction/index.rst:

```
#!rst

###############
Getting started
###############

.. toctree::
    :maxdepth: 2
    :hidden:

    first_item_for_sidebar
    second_item_for_sidebar


**********************
Third item for sidebar
**********************
```

And that works, the sidebar contains:

```
#!
Getting started
    First item for sidebar
    Second item for sidebar
    Third item for sidebar
```

However, if I move the toctree so that it's after that "Third item for sidebar" heading, nothing in it will make it to the sidebar:

```
#!
Getting started
    Third item for sidebar
```

I am not sure if this is a bug, or intended behaviour because the toctree is now within that heading's scope, but it means it's not possible to combine headings and toctree items in the order I require.

Thanks.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1613
- Originally reported by: [evildmp](https://bitbucket.org/evildmp)
- Originally created at: 2014-11-05T10:44:53.894

**Comment by AA-Turner** [comment]
I can't reproduce this, if it remains an issue please re-open with details against `5.x`.

A
