### ISSUE TITLE
Adding LuaTeX and XeTeX support for latex builder

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1615]
Currently, Sphinx LaTeX output can't be compiled by using LuaTeX because Sphinx depends to `\DeclareUnicodeCharacter` and LuaTeX doesn't provide the command (LuaTeX ignore `\usepackage[utf8]{inputenc}`).

Sphinx using `\DeclareUnicodeCharacter` at `writers/latex.py` that was introduced at 3e1f33ab8245.

To resolve this, Sphinx can use `ifluatex` and `ifxetex`:  http://tex.stackexchange.com/questions/184358/declareunicodecharacter-and-luatex

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1615
- Originally reported by: Takayuki Shimizukawa
- Originally created at: 2014-11-06T05:53:24.189

**Comment by tk0miya** [comment]
PR #2200 is merged into master branch.
It resolve this issue.

Thanks.
