### ISSUE TITLE
The index feature needs some improvement

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1627]
Some things that frustrated me when I was trying to create an index:
1. The sorting seems to be hard-wire to the character codepoints. No relation to the document's locale (already reported in #736).
2. There's apparently no way to alter the sorting of entries, like, for instance, have 'ln(x)' sorted as 'logarithm'. This would be a workaround for 1 too.
3. Inline formatting or substitutions cannot be used for index entries. The above should be :math:`\ln(x)`, but this doesn't work.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1627
- Originally reported by: Ignacio Fernández Galván
- Originally created at: 2014-11-17T15:03:15.910

**Comment by AA-Turner** [comment]
Closing as the sorting issue is fixed. If the other issues persist, please re-open with a minimal reproducer.

A
