### ISSUE TITLE
Image maps

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1628]
Feature request: **Image-Maps**

This is to allow documentation utilizing technical images, with regions that link to more information.

This is essential for good technical documentation.
Examples: Architecture images, where clicking on blocks links to the relevant information.

Examples: 
http://www.mediawiki.org/wiki/Extension:ImageMap

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1628
- Originally reported by: Peter Mueller
- Originally created at: 2014-11-19T08:44:42.580

**Comment by shimizukawa** [comment]
_From mike lang on 2014-11-27 08:41:10+00:00_

The interesting question is: how to do image-maps in LaTeX?

I think one could use Packages such as [pstricks](http://tug.org/PSTricks/main.cgi?file=Examples/misc#hyperref) or [tikz](https://groups.google.com/d/msg/comp.text.tex/KqyGL1AOFyk/KbTCC7jYvsAJ), etc.

**Comment by hamishwillee** [comment]
+1

**Comment by 62mkv** [comment]
+1

**Comment by tk0miya** [comment]
Note: The doc of docutils mentions about imagemap directive. But it has still not been implemented for a long time.
https://docutils.sourceforge.io/docs/ref/rst/directives.html#imagemap

**Comment by 62mkv** [comment]
Hi! has corresponding issue been raised against docutils? @tk0miya

**Comment by sebastien-riou** [comment]
+1

**Comment by tk0miya** [comment]
@62mkv Sorry, I'm not sure. Please search it by yourself.
