### ISSUE TITLE
Choice of label for div causes CSS conflicts

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1630]
This commit: 78d8ebf76b630ab4073a7328af9d91e8123b8d96 adds CSS to improve the appearance of numfig captions. However, some files use `div.container`, which being a commonly-used label in CSS has the potential to interfere with some themes, such as [sphinx-bootstrap-theme](https://github.com/ryan-roemer/sphinx-bootstrap-theme/issues/114). Can it be renamed it to something other than "container", or the CSS files use more specific selectors?

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1630
- Originally reported by: Eric Knibbe
- Originally created at: 2014-11-27T04:57:28.288

**Comment by birkenfeld** [comment]
Git commit reference: 88001924196e1a15eb71c581938e036f0f284766
