### ISSUE TITLE
LaTeX tables error

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1632]
The first table shown here [ref](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#grid-tables)

```
+------------------------+------------+----------+----------+
| Header row, column 1   | Header 2   | Header 3 | Header 4 |
| (header rows optional) |            |          |          |
+========================+============+==========+==========+
| body row 1, column 1   | column 2   | column 3 | column 4 |
+------------------------+------------+----------+----------+
| body row 2             | Cells may span columns.          |
+------------------------+------------+---------------------+
| body row 3             | Cells may  | - Table cells       |
+------------------------+ span rows. | - contain           |
| body row 4             |            | - body elements.    |
+------------------------+------------+---------------------+
```

causes errors when using

```
make latex; make latexpdf
```

The error reported is

```
Runaway argument?
{ \multicolumn {2}{l|}{\begin {itemize} \item {} Table cells 
! Paragraph ended before \@xmultirow was complete.
<to be read again> 
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1632
- Originally reported by: mike lang
- Originally created at: 2014-11-28T01:01:44.633

**Comment by shimizukawa** [comment]
_From Eric Knibbe on 2014-12-16 05:39:38+00:00_

It looks like the current implementation can only handle one multi-row cell per row.

Also, multi-row cells still have `\hline`s running through them. Anyone looking for a challenge could write support for calculating proper `\cline` values for each row.

**Comment by shimizukawa** [comment]
_From Eric Knibbe on 2014-12-23 06:10:54+00:00_

Ah, so this particular error is because block content doesn't work inside spanned cells when output to LaTeX. Nonetheless, I have a patch for latex.py that generates proper markup and horizontal lines on spanned cells which I'll file in a separate issue.

**Comment by EricFromCanada** [comment]
Filed as #1667.

**Comment by shimizukawa** [comment]
#1667 has been merged. Thanks!

**Comment by EricFromCanada** [comment]
Thought I'd point out that the list in the lower right multirow table cell is failing because the `\multirow` call generated by Sphinx in that case sets its width to `*`, so it requires extra markup to handle multiline content according to the [multirow manual](http://ctan.org/pkg/multirow).
