### ISSUE TITLE
ENH: <a target="_glossary">

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1634]
It would be great if glossary links opened in the same new tab.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1634
- Originally reported by: Wes Turner
- Originally created at: 2014-11-30T07:58:32.519

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2014-12-02 07:35:20+00:00_

Hum.., in my case, several `.. glossary::`` directives are written in several pages which are not single purpose page for glossary. Because of it, I prefer the current (non target specified) implementation.
In another point of view, accessibility guideline recommended that target attribute should not be used until user agents allow users to turn off spawned windows [1]_.

I propose as an alternative, the behavior can be implemented by using JavaScript.
If you have a chance, please try it.

.. [1] http://www.w3.org/TR/2000/NOTE-WCAG10-TECHS-20001106/#gl-interim-accessibility

**Comment by shimizukawa** [comment]
_From Wes Turner on 2014-12-02 10:37:03+00:00_

Thank you for the explanation!

I've added this to a few documentation sets, which I suppose either a) interrupts the UX; b) makes tangents (e.g. wikipedia pages) more noticeable:

```
$(document).ready(function() {
    $("a[href^='http']").attr('target','_blank');
});
```

On further review, I should probably add a checkbox.

**Comment by shimizukawa** [comment]
_From Wes Turner on 2014-12-02 10:37:21+00:00_

Closed. Not a good idea.

**Comment by kmmbvnr** [comment]
jQuery free version:

```javascript
window.addEventListener('turbolinks:load', function() {
  document.querySelectorAll('a.reference.external').forEach(function(link) {
    link.target = '_blank';
  });
});
```
