### ISSUE TITLE
Document parser breaks quietly with ParseError("bad input on print() (from __future__ import print_function)

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1641]
See Also #1547 #1547

``` python
            import dotfiles
            version = dotfiles.version
            print(version, file=stdout)  # 3486
            return 0
```

```
[autodoc] module analyzer failed: parsing failed (exception was:
... ParseError("bad input: type=22, value=u'=', context=('', (3486, 31))",))
```
- https://github.com/westurner/dotfiles/blob/33cf7f6c4/src/dotfiles/venv/ipython_config.py#L3486
- https://github.com/westurner/dotfiles/blob/33cf7f6c4/docs/conf.py
- https://github.com/westurner/dotfiles/blob/33cf7f6c4/Makefile
- https://github.com/westurner/dotfiles/blob/33cf7f6c4/docs/Makefile
- Makefile (`make docs` -> `make -C docs html`) 

With Python 2.7.8, sphinx 1.3b1

[EDIT]

**WORKAROUND**

Redefine print at the top of the file

``` python
 if sys.version_info[0] == 2:
    def print(*args, **kwargs):
        print(*args, **kwargs)
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1641
- Originally reported by: Wes Turner
- Originally created at: 2014-12-03T16:43:26.165

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2014-12-15 09:25:17+00:00_

Confirmed. The issue has been reproduced with Python2.7 & Sphinx-1.3b2. I attached a sample project that contains `console.log`.

I have a question. The error message `[autodoc] module analyzer failed: parsing failed (exception was: ParseError("bad input: type=22, value=u'=', context=('', (xx, xx))",))` is only displayed if you provide `SPHINXOPTS=-vv`  and it doesn't have side-effect for html output. It's just a warning, isn't it?

**Comment by shimizukawa** [comment]
_From Wes Turner on 2014-12-16 02:33:52+00:00_

I suppose it is just a warning, but the performance hit does seem to exist whether or not the verbosity level is increased.

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2014-12-16 03:18:30+00:00_

Thanks for clarification. I guess that some `__future__` syntaxes  are not supported by `sphinx.pycode.pgen2.tokenizer`.

**Comment by shimizukawa** [comment]
_From Wes Turner on 2014-12-16 06:24:04+00:00_

> Thanks for clarification. I guess that some `__future__` syntaxes are not supported by `sphinx.pycode.pgen2.tokenizer`.

This does appear to be the case. This workaround is working for this use case, as there is only one file to modify:

```
#!python

from __future__ import print_function
import sys

if sys.version_info[0] == 2:
    # workaround for Sphinx autodoc bug
    import __builtin__
    def print(*args, **kwargs):
        __builtin__.print(*args, **kwargs)
```

**Comment by silvester747** [comment]
I recently stumbled upon this exact issue in pyglet. It took me quite a while to figure out what was going wrong, as the error output is very cryptic. I ended up modifying pgen2/parse.py to figure out what it was.

For me the first time it results in a fatal error, then if I run sphinx again it will succeed. It would be helpful to at least output the name of the file causing trouble. Currently all I get is this:

```
ParseError: bad input: type=22, value=u'=', context=('', (539, 51))
```

In this case it fails on a line like this:

```
print('some text', end=' ')
```

It fails on the = in there.

**Comment by silvester747** [comment]
The workaround does not work for me. It actually now fails in the workaround code:

```
Exception in: pyglet.graphics /home/rob/python/pyglet/bitbucket/main/pyglet/graphics/__init__.py
Traceback (most recent call last):
  File "/home/rob/python/pyglet/venv/py2/local/lib/python2.7/site-packages/sphinx/pycode/__init__.py", line 266, in parse
    self.parsetree = pydriver.parse_tokens(self.tokens)
  File "/home/rob/python/pyglet/venv/py2/local/lib/python2.7/site-packages/sphinx/pycode/pgen2/driver.py", line 70, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/home/rob/python/pyglet/venv/py2/local/lib/python2.7/site-packages/sphinx/pycode/pgen2/parse.py", line 159, in addtoken
    raise ParseError("bad input", type, value, context)
ParseError: bad input: type=1, value=u'print', context=(u' ', (179, 8))

Traceback (most recent call last):
  File "/home/rob/python/pyglet/venv/py2/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 244, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/rob/python/pyglet/venv/py2/local/lib/python2.7/site-packages/sphinx/application.py", line 188, in __init__
    self._init_builder(buildername)
  File "/home/rob/python/pyglet/venv/py2/local/lib/python2.7/site-packages/sphinx/application.py", line 250, in _init_builder
    self.emit('builder-inited')
  File "/home/rob/python/pyglet/venv/py2/local/lib/python2.7/site-packages/sphinx/application.py", line 497, in emit
    results.append(callback(self, *args))
  File "/home/rob/python/pyglet/bitbucket/main/doc/ext/autosummary/__init__.py", line 575, in process_generate_options
    base_path=app.srcdir)
  File "/home/rob/python/pyglet/bitbucket/main/doc/ext/autosummary/generate.py", line 289, in generate_autosummary_docs
    ns['iattributes'] = get_iattributes(obj)
  File "/home/rob/python/pyglet/bitbucket/main/doc/ext/autosummary/generate.py", line 231, in get_iattributes
    attr_docs = analyzer.find_attr_docs()
  File "/home/rob/python/pyglet/venv/py2/local/lib/python2.7/site-packages/sphinx/pycode/__init__.py", line 280, in find_attr_docs
    self.parse()
  File "/home/rob/python/pyglet/venv/py2/local/lib/python2.7/site-packages/sphinx/pycode/__init__.py", line 274, in parse
    raise PycodeError('parsing failed', err)
PycodeError: parsing failed (exception was: ParseError("bad input: type=1, value=u'print', context=(u' ', (179, 8))",))

Exception occurred:
  File "/home/rob/python/pyglet/venv/py2/local/lib/python2.7/site-packages/sphinx/pycode/__init__.py", line 274, in parse
    raise PycodeError('parsing failed', err)
PycodeError: parsing failed (exception was: ParseError("bad input: type=1, value=u'print', context=(u' ', (179, 8))",))
```

Note that this is with -vv and some extra traceback prints from me, as even -vvv did not give any information on what actually failed.

**Comment by silvester747** [comment]
Never mind the last issue. I had to put the workarond code as early as possible. There were some other imports in between, causing it to fail.

**Comment by bootc** [comment]
The workaround posted for me also doesn't work, so I had to resort to something altogether more nasty. As soon as I use `print([...], file=sys.stderr)` the Sphinx parser keels over and barfs at _any_ use of `print` anywhere in the file: very strange.

So I resorted to defining a `print_()` function and using that throughout my code:

``` python
# Workaround for Sphinx bug 1641. Without this kind of thing, Sphinx barfs when
# using print as a function. https://github.com/sphinx-doc/sphinx/issues/1641
try:
    import builtins
    print_ = getattr(builtins, 'print')
except ImportError:
    import __builtin__
    print_ = getattr(__builtin__, 'print')
```

Then where necessary: `print_("something", file=sys.stderr)`. This works in Python 2.6+ including Python 3.x.

This is the commit where I started using it: https://github.com/tigercomputing/vortex/commit/8e247bcbb8f8e9277fa17c78c6cd782192fe4865

**Comment by chadwhitacre** [comment]
I got bit by this as well. The symptom in my case is that, given the following input, the `Foo.bar` attribute does not show up in the generated HTML, because the reference to `print` causes the parser to fail with [`ParseError('bad input')`](https://github.com/sphinx-doc/sphinx/blob/1.4.4/sphinx/pycode/pgen2/parse.py#L159).

``` python
"""Foo bar baz buz.
"""
from __future__ import print_function

class Foo(object):
    """
    """

    #: bar

    bar = 0

def baz(buz=print):
    """
    """
```

**Comment by chadwhitacre** [comment]
I'm not sure what the right fix is. It looks like the `pgen2` module was vendored in years ago (49c15e93a21014f6640bfd0e0c6752bdc61d105c). Why? How has it evolved since then? How does the Sphinx version of `pgen2` relate to [this one](https://pypi.python.org/pypi/pgen2)? Has this bug been fixed in @jriehl's `pgen2`? Or in another version (where did `pgen2` come from in the first place?)?

**Comment by chadwhitacre** [comment]
A quick inspection of mython/pgen2 suggests that it's unrelated to the version in Sphinx.

**Comment by chadwhitacre** [comment]
There are [a number of changes](https://github.com/sphinx-doc/sphinx/commits/master/sphinx/pycode/pgen2) to Sphinx's `pgen2` since it was first added, suggesting that, whatever its origin, it should be fully considered a submodule of `sphinx.pycode` at this point. Any fix for this bug should be made here in Sphinx and not upstream somewhere.

**Comment by davidswelt** [comment]
This bug, reported in early 2015, cost me several hours productivity.  

Without warning, Sphinx (and autodoc) fails to include anything from this module, iff the following is included:

  def warning(*objs):
      print("WARNING: ", *objs)   # THIS CAUSES SPHINX TO SILENTLY FAIL

The workaround does not compile.

[bla2.py.txt](https://github.com/sphinx-doc/sphinx/files/1038197/bla2.py.txt)

**Comment by tk0miya** [comment]
With Sphinx-1.7, this problem is already resolved. It supports `print_function` feature.
So I'm closing this now.
Thanks,
