### ISSUE TITLE
issue #505 is back

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1642]
Search doesent work locally on browsers other than firefox.
#505

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1642
- Originally reported by: ALIANE Abdelouahab
- Originally created at: 2014-12-03T18:34:17.687

**Comment by shimizukawa** [comment]
_From ALIANE Abdelouahab on 2014-12-03 17:44:32+00:00_

teste on 1.3b2, on chrome it takes long time to give results, it gave two results and then hangs, on firefox it returns them instantly!

**Comment by vitaut** [comment]
Same issue here with Sphinx version 1.2.2 and Chrome.

**Comment by andreacassioli** [comment]
Same for Sphinx 1.2.3 and Chrome.

**Comment by birkenfeld** [comment]
I hope this fixes it, sorry for the delay in checking it out.
