### ISSUE TITLE
Error in date format

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1647]
Exception occurred:
  File "/usr/local/src/faunalia-website/_templates/layout.html", line 118, in block "footer"
    {&#37; trans last_updated=last_updated|e &#37;}Last updated on {{ last_updated }}.{&#37; endtrans &#37;}<br/><br/>
ValueError: incomplete format

From conf.py:

html_last_updated_fmt = '&#37;d &#37;b &#37;Y'

Thanks.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1647
- Originally reported by: [pcav](https://bitbucket.org/pcav)
- Originally created at: 2014-12-06T19:08:32.893

**Comment by shimizukawa** [comment]
_From [pcav](https://bitbucket.org/pcav) on 2014-12-06 18:40:05+00:00_

Apparently this prevents compilation for `fr` locale, so it's rather serious.
May be my mistake, I apologize in advance.

**Comment by tk0miya** [comment]
I can't reproduce this.
I tried with combination of these parameters:
- `language = 'fr'` in conf.py
- environment variable `LANG=fr`
- environment variable `LANG=fr_FR.utf-8`

Could you tell me your settings and environment in detail?

**Comment by shimizukawa** [comment]
@pcav do you still have this issue?

**Comment by pcav** [comment]
Yes, with 1.3.4

Exception occurred:
  File "/usr/local/src/pcav/faunalia-website/_templates/layout.html", line 107, in block "footer"
    {% trans last_updated=last_updated|e %}Last updated on {{ last_updated }}.{% endtrans %}<br/><br/>
ValueError: incomplete format

**Comment by shimizukawa** [comment]
@pcav Please try below command (-P for debugging mode when exception is occurred)

```
> sphinx-build -M html . _build -P
...
Exception occurred while building, starting debugger:
...
(Pdb) from sphinx import locale
(Pdb) locale.mygettext('Last updated on %(last_updated)s.')
u'Mis \xe0 jour le %(last_updated)s.'
```

I suspect that the translated string (last line) is broken.

**Comment by tk0miya** [comment]
Ping, any updates?

**Comment by pcav** [comment]
Yes, still the same, with:
`html_last_updated_fmt = '%d %b %Y'` in `conf.py`

{{{
Exception occurred:
  File "/usr/local/src/pcav/faunalia-website/_templates/layout.html", line 107, in block "footer"
    {% trans last_updated=last_updated|e %}Last updated on {{ last_updated }}.{% endtrans %}<br/><br/>
ValueError: incomplete format
The full traceback has been saved in /tmp/sphinx-err-VnZIoQ.log, if you want to report the issue to the developers.
}}}

**Comment by tk0miya** [comment]
@pcav Thanks. Could you check the shimizukawa's comment?
We need more detailed information using debugging mode.

**Comment by pcav** [comment]
sphinx-build -M html . _build -P does not throw an error.

**Comment by shirou** [comment]
I cloned https://github.com/pcav/faunalia-website, add `html_last_updated_fmt = '%d %b %Y'` on conf.py, and `make html`. But no exception occurred.

```
Sphinx==1.3.4
sphinx-bootstrap-theme==0.4.12
```

<img width="351" alt="2016-07-28 21 34 43" src="https://cloud.githubusercontent.com/assets/177213/17212594/24ff4b98-550b-11e6-8089-c00c254895df.png">

**Comment by pcav** [comment]
I use sphinx 1.4.
Thanks for testing.

**Comment by shirou** [comment]
I also checked with  sphinx 1.4.0 and 1.4.5, but same as no exception.
What is your `locale` on your terminal and your os or distribution?

**Comment by pcav** [comment]
it_IT.UTF-8 UTF-8
Debian sid

**Comment by tk0miya** [comment]
> sphinx-build -M html . _build -P does not throw an error.

Hmm, it's strange...
Do you get the errors if you remove `-P` option from this command line?
If not, please add `-P` option to the command line which raises errors.

**Comment by pcav** [comment]
`sphinx-build -M html . _build` does not throw an error.
`make html` does:

{{{
Exception occurred:
  File "/usr/local/src/pcav/faunalia-website/_templates/layout.html", line 107, in block "footer"
    {% trans last_updated=last_updated|e %}Last updated on {{ last_updated }}.{% endtrans %}<br/><br/>
ValueError: incomplete format
}}}

My Make:

{{{
html:
    @for lang in $(LANGUAGES);\
    do \
        mkdir -p $(BUILDDIR)/html/$(SOURCE)/$$lang $(BUILDDIR)/doctrees/$(SOURCE)/$$lang; \
        echo "$(SPHINXBUILD) -b html $(ALLSPHINXOPTS) $(SOURCE) $(BUILDDIR)/html/$$lang";\
        $(SPHINXBUILD) -b html $(ALLSPHINXOPTS) $(SOURCE) $(BUILDDIR)/html/$(SOURCE)/$$lang;\
}}}

Thanks

**Comment by tk0miya** [comment]
I understand. You use custom Makefile and give `-Dlanguage=$$lang` option on buliding docs.
Surely, `sphinx-build -M html . _build` does not raise errors.

Could you add `-P` to `$ALLSPHINXOPTS`?
It would be raise errors.

**Comment by pcav** [comment]
```
Exception occurred while building, starting debugger:                                                                  
Traceback (most recent call last):
  File "/usr/local/src/py_virtual_stable/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 244, in main
    app.build(opts.force_all, filenames)
  File "/usr/local/src/py_virtual_stable/local/lib/python2.7/site-packages/sphinx/application.py", line 287, in build
    self.builder.build_update()
  File "/usr/local/src/py_virtual_stable/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "/usr/local/src/py_virtual_stable/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 322, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/local/src/py_virtual_stable/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 360, in write
    self._write_serial(sorted(docnames), warnings)
  File "/usr/local/src/py_virtual_stable/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 368, in _write_serial
    self.write_doc(docname, doctree)
  File "/usr/local/src/py_virtual_stable/local/lib/python2.7/site-packages/sphinx/builders/html.py", line 451, in write_doc
    self.handle_page(docname, ctx, event_arg=doctree)
  File "/usr/local/src/py_virtual_stable/local/lib/python2.7/site-packages/sphinx/builders/html.py", line 802, in handle_page
    output = self.templates.render(templatename, ctx)
  File "/usr/local/src/py_virtual_stable/local/lib/python2.7/site-packages/sphinx/jinja2glue.py", line 138, in render
    return self.environment.get_template(template).render(context)
  File "/usr/local/src/py_virtual_stable/local/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/src/py_virtual_stable/local/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/src/py_virtual_stable/local/lib/python2.7/site-packages/sphinx/themes/basic/page.html", line 10, in top-level template code
    {%- extends "layout.html" %}
  File "/usr/local/src/pcav/faunalia-website/_templates/layout.html", line 39, in top-level template code
    {% block languageswitch %}
  File "/usr/local/src/py_virtual_stable/local/lib/python2.7/site-packages/sphinx_bootstrap_theme/bootstrap/layout.html", line 81, in top-level template code
    {%- include sidebartemplate %}
  File "/usr/local/src/py_virtual_stable/local/lib/python2.7/site-packages/sphinx/themes/basic/layout.html", line 185, in top-level template code
    {%- block footer %}
  File "/usr/local/src/pcav/faunalia-website/_templates/layout.html", line 107, in block "footer"
    {% trans last_updated=last_updated|e %}Last updated on {{ last_updated }}.{% endtrans %}<br/><br/>
ValueError: incomplete format
> /usr/local/src/pcav/faunalia-website/_templates/layout.html(107)block "footer"()
-> {% trans last_updated=last_updated|e %}Last updated on {{ last_updated }}.{% endtrans %}<br/><br/>
```

**Comment by tk0miya** [comment]
Okay, you succeeded to catch the error by pdb.
Could you run following commands (which starts with "(Pdb)") as shimizukawa said and let us know its results?

```
(Pdb) from sphinx import locale
(Pdb) locale.mygettext('Last updated on %(last_updated)s.')
u'Mis \xe0 jour le %(last_updated)s.'
```

**Comment by pcav** [comment]
```
(Pdb) from sphinx import locale
/usr/local/src/pcav/faunalia-website/_templates/layout.html:1: RuntimeWarning: Parent module '/usr/local/src/pcav/faunalia-website/_templates/layout' not found while handling absolute import
  {# Import the theme's layout. #}
u'Mis \xe0 jour en %(last_updated).'
```

So it's French.
Thanks.

**Comment by takuan-osho** [comment]
I cloned https://github.com/pcav/faunalia-website, add `html_last_updated_fmt = '%d %b %Y'` and `language = 'fr'` in conf.py, and `sphinx-build -M html . build -P`. But no exception occurred.

The versions of sphinx and extension are here:

```
Sphinx==1.3.4
sphinx-bootstrap-theme==0.6.0
```

In the case of sphinx 1.6.5, there is no exception occurred too.

**Comment by takuan-osho** [comment]
I cloned https://github.com/pcav/faunalia-website, add `html_last_updated_fmt = '%d %b %Y'` and `language = 'fr'` in conf.py, and `make html` with `-P` in `$ALLSPHINXOPTS`. But no exception occurred.

The versions of sphinx and extension are here:

```
Sphinx==1.3.4
sphinx-bootstrap-theme==0.6.0
```

In the case of sphinx 1.6.5, there is no exception occurred too.

**Comment by picnixz** [comment]
It appears that tk0miya's French translation is:

> `u'Mis \xe0 jour le %(last_updated)s.'`

whereas pcva's translation is

> `u'Mis \xe0 jour en %(last_updated).'`

In the second case it's `%(last_updated)` without the final `s`, causing the issue. So it's likely that the locales were out-of-date. As of Sphinx 7.1, the `fr` locale contains `"Mis à jour le %(last_updated)s."` which is correct in French, so there shouldn't be an issue anymore.
