### ISSUE TITLE
util.get_module_source doesn't work for egg files

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1648]
Like the description says; if you have a library installed in a virtualenv that is still inside a zipped .egg file, the get_module_source function fails, even if the source is clearly available inside the egg file.

I'm sure there are other consequences of this bug, but the one I'm encountering right now is that it breaks sphinxcontrib-httpdomain's auto-flask functionality (in python 2.7). 

Steps to reproduce:
- install sphinx in a virtualenv
- also install something in an unextracted egg - "pycrypto" is a good choice.
- then, from the python interpreter:

```
#!python
>>> import sphinx.util
>>> s = sphinx.util.get_module_source('Crypto')
```

At this point I see a stack trace for <my virtualenv>lib/python2.7/site-packages/sphinx/util/**init**.py", line 237, in get_module_source 

The error message is:
sphinx.errors.PycodeError: source file is not present: '<my virtualenv>/lib/python2.7/site-packages/pycrypto-2.6.1-py2.7-macosx-10.4-x86_64.egg/Crypto/**init**.py'

Looking at the code, I see two possible fixes. It'd be fairly easy to patch this specific case by adding logic that will consider using loader.get_source() again if the file is not found. However, the method as currently written seems pretty complex, and I'm wondering if the right choice would be to just use loader.get_source() anywhere you can - but I don't have an exhaustive knowledge of the cases the code is trying to cover, and I couldn't find any unit tests for this specific code.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1648
- Originally reported by: Oliver Stacey
- Originally created at: 2014-12-08T20:26:59.657

**Comment by AA-Turner** [comment]
Egg files are deprecated, closing.

A
