### ISSUE TITLE
:type foobar: is ignored for :ivar foobar:

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1651]
With the following source code:

```
#!python

class Path(object):
    """
    :ivar edge_indices: The indices within `textured_points` of the places.

    :type edge_indices: list of int
    """
```

The output of autodoc does not include the type.  I only checked HTML output.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1651
- Originally reported by: Torsten Bronger
- Originally created at: 2014-12-17T05:28:08.028

**Comment by pjxiao** [comment]
According to [documents](http://sphinx-doc.org/domains.html#info-field-lists), `type` directive describe "Type of a _parameter_." (Not type of variable)
If you want to describe a type of _variable_, you can use `vartype`.

``` py
#!python

class Path(object):
    """
    :ivar edge_indices: The indices within `textured_points` of the places.
    :vartype edge_indices: list of int
    """

    def some_method(self, arg):
        """
        :param arg: an argument
        :type arg: type of an argument
        """
```
