### ISSUE TITLE
No link created (and warning given) if option does not begin with -, / or +

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1658]
If I write

.. option:: -my_test_option

and then refer to it with :option:`-my_test_option` then the reference is linked as expected.  However, if I remove the leading dash, i.e., if I have

.. option:: my_test_option

and then refer to it with :option:`my_test_option` then the link is not generated and a warning

src/chapter2/section3.txt:5397: WARNING: Malformed :option: u'my_test_option', does not contain option marker - or -- or / or +

This seems to contradict the documentation (http://sphinx-doc.org/domains.html) whereby

.. option:: dest_dir

is allowed (luckily, because almost all my options begin with a letter).

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1658
- Originally reported by: [bagnara](https://bitbucket.org/bagnara)
- Originally created at: 2014-12-27T10:49:36.699

**Comment by claashk** [comment]
I seemingly have the same problem using sphinx 1.3.1 on OpenSuse with the following code:

``` rst
.. program:: svn help

.. option:: tool

   tool for which to provide help.
```

Referencing this somewhere with `:option:`svn help tool`` neither creates a warning nor a link. I this intended behaviour or does the bug still persist in version 1.3.1 with python 2.7 ?
