### ISSUE TITLE
Sphinx already used project name scine 2001

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1661]
Hi,

I develop application based on Sphinx Search ( http://sphinxsearch.com/ ) and once at morning I found you project witout my Search engine solution. Could you think about your project name and collistion may occure before start of selected name?

Thanx for answer?

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/1661
- Originally reported by: Vitold S
- Originally created at: 2014-12-30T22:02:44.108

**Comment by birkenfeld** [comment]
Unfortunately this happened, yes. It has to do with the history of Sphinx, not being planned as a public utility. Now it's too late to change.
