### ISSUE TITLE
Expose language in template/theme

### ISSUE THREAD

**Issue by martin-ueding** [sphinx-doc/sphinx#1669]
I need to know the language in the template for instance for `<body lang="{{ lang }}">` and other cases. So far, I have build an [ugly contraption](http://martin-ueding.de/de/programming/sphinx-personal-website/index.html#getting-the-language-into-the-template) to do this. I assume it would be possible to expose the language that is currently built for in the template. Could you please look into that?

**Comment by keimlink** [comment]
I agree this would be useful. Especially for the improvement of the i18n feature.

**Comment by martin-ueding** [comment]
Thank you for the fast fix! I hope that it will trickle down to Ubuntu in a decent timeframe :-)
