### ISSUE TITLE
napoleon extension and *args and **kwargs arguments

### ISSUE THREAD

**Issue by mwiebusch78** [sphinx-doc/sphinx#1670]
When using the napoleon extension to parse Google-style docstrings the documentation of variable argument and keyword lists (_args and *_kwargs) are not parsed correctly. For example, when parsing the file at

```
http://sphinxcontrib-napoleon.readthedocs.org/en/latest/example_google.html
```

the explanations of the _args and *_kwargs arguments of module_level_function do not appear in the generated documentation.

**Comment by mwiebusch78** [comment]
I was able to fix the issue in the sphinxcontrib-napoleon-0.2.8 package which I'm using with Sphinx 1.2.3. It's a simple case of allowing one or two leading stars in the regex for argument names and then escaping the stars if present. I have a patch file, but I can't figure out how to attach it here.

**Comment by RobRuana** [comment]
If it's small enough, can you just copy and paste the diff in a comment?

**Comment by mwiebusch78** [comment]
It gets mangled by the markdown, but here we go:

diff -Naur sphinxcontrib-napoleon-0.2.8/sphinxcontrib/napoleon/docstring.py sphinxcontrib-napoleon-0.2.8-patched/sphinxcontrib/napoleon/docstring.py
--- sphinxcontrib-napoleon-0.2.8/sphinxcontrib/napoleon/docstring.py    2014-06-13 20:12:33.000000000 +0100
+++ sphinxcontrib-napoleon-0.2.8-patched/sphinxcontrib/napoleon/docstring.py    2015-01-09 16:15:25.888066952 +0000
@@ -17,8 +17,8 @@

 _directive_regex = re.compile(r'.. \S+::')
-_google_untyped_arg_regex = re.compile(r'\s_(\w+)\s_:\s_(._)')
-_google_typed_arg_regex = re.compile(r'\s_(\w+)\s_(\s_(.+?)\s_)\s_:\s_(._)')
+_google_untyped_arg_regex = re.compile(r'\s_(*?*?\w+)\s_:\s_(._)')
+_google_typed_arg_regex = re.compile(r'\s_(*?*?\w+)\s_(\s_(.+?)\s_)\s_:\s_(._)')

 class GoogleDocstring(object):
@@ -223,6 +223,11 @@
                 _name = match.group(1)
                 _desc = match.group(2)
-        if _name[:2] == '**':
-            _name = r'**'+_name[2:]
-        elif _name[:1] == '*':
-            _name = r'*'+_name[1:]
  +
       if prefer_type and not _type:
           _type, _name = _name, _type
       indent = self._get_indent(line) + 1

**Comment by RobRuana** [comment]
Also, if you're using the sphinxcontrib-napoleon extension with an older version of sphinx, I've uploaded [version 0.2.9 to pypi](https://pypi.python.org/pypi/sphinxcontrib-napoleon) with a fix for this issue.
