### ISSUE TITLE
index feature and cross reference targets

### ISSUE THREAD

**Issue by mwiebusch78** [sphinx-doc/sphinx#1671]
The documentation states that the .. index:: and :index: roles generate cross reference targets. The names of these targets seem to be something non-descriptive like index-0 etc. Is there a way to set the name of the cross reference targets, so that one can use them in :ref: roles?

The use case is the following: Let's say I define some abbreviation or technical term somewhere in my documentation. The abbreviation should appear in the index. But to make things simpler for the reader I also want to put a link to the definition in other places where I use the abbreviation. It seems at the moment the only way to do this is to set a custom label and an index entry. Would be nice if one could do it in one step.

**Comment by birkenfeld** [comment]
Currently the anchors are only for use by the index. But your use case is valid. I'm just struggling a bit to find an acceptable syntax. It's also not clear what role should be used for referencing -- :ref: should be reserved for labels I think.

**Comment by mwiebusch78** [comment]
But :ref: is used for all sorts of targets (sections, subsections, figures, etc.). Why not locations in the text where abbreviations are defined? My current workaround is to add a label as well as an .. index:: role.

```
.. index:: MyAbbreviation

.. _myabbr:

Definition of MyAbbreviation
```

A simple fix would be to change the .. index syntax so that you can put the label on the same line

```
.. index:: MyAbbreviation <myabbr>
```

or something similar. Of course the same should be possible with the inline :index:`...` role.

**Comment by geographika** [comment]
Perhaps a new directive such as `:indexref:` could be used? There is a [:numref:](https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#cross-referencing-figures-by-figure-number) role that serves a similar purpose. 

I'm currently using hard-coded links for the MapServer docs e.g. https://mapserver.org/mapfile/class.html#index-1 which isn't ideal (as part of [Python API documentation](https://github.com/mapserver/mapserver/pull/5870)). The API docs make extensive use of an index with all keywords indexed such as [this example](https://github.com/mapserver/docs/blob/branch-7-4/en/mapfile/class.txt)

```
.. index::
   pair: CLASS; BACKGROUNDCOLOR
```

It would be great to be able to reference this location using syntax such as:

```
:indexref:`My index reference <CLASS; BACKGROUNDCOLOR>`
```

**Comment by tk0miya** [comment]
We can put same index to multiple places. So `:indexref:` will be confused and not working well in such case. Of course, we can generate two hyperlinks for `:indexref:`. But I don't understand it is useful.

IMO, adding `:name:` option to `index` directive might be better. `:name:` option is well known and commonly used for many directives in reStructuredText. And it can give a hyperlink name to an arbitrary index entry. I feel it would be a bit redundant. But it is explicit to me at same time.
```
.. index:: MyAbbreviation
   :name: myabbr

blah blah blah

reference myabbr with ref: :ref:`myabbr`

.. index:: MyAbbreviation

This paragraph is not hyperlinked because of no hyperlink-name.
```

**Comment by geographika** [comment]
@tk0miya - many thanks for the reply. 

I hadn't considered the indexes to multiple places. Testing these Sphinx already treats the links in the genindex.html slightly differently e.g.

```
.. index::
   single: Test1
   
.. index::
   single: Test1
```

Produces a genindex.html containing the following, with the second link listed as [1]. 

```
Test1, [1] 
```

The two generated URLs are `page.html#index-1` and `page.html#index-2`

In order to save having to create unique labels for each index directive (for linking) could an option be to create URLs such as `page.html#test1-1` and `page.html#test1-2` and an `:indexref:` which would always reference the first of any duplicates?
Perhaps this could be in conjunction with the additional :name: option for fine tuning. 

I presume any chnages involved would be to the `sphinx/environment/adapters/indexentries.py` file? I'll try and experiment with this further.

**Comment by tk0miya** [comment]
Are there some feature changes in this request, right?
1. allow to specify anchor name in HTML output
2. allow to refer an index entry via new `:indexref:` role
3. allow to refer an index entry via `:ref:` role

>an :indexref: which would always reference the first of any duplicates?

Surely, it is easy to find it if your project is consist of a single file. But sphinx project can have multiple source files. So it is hard to find "first" entry.

In addition, I wonder linking to first entry is right behavior even if possible. Why not `:indexref:` is a reference to an entry in index page? I feel the behavior `:indexref:` is ambiguous from its name.

>I presume any chnages involved would be to the sphinx/environment/adapters/indexentries.py file? I'll try and experiment with this further.

Yes, it is a database of index entries. And `index` directive is implemented at `sphinx/directive/other.py`.

**Comment by tk0miya** [comment]
Finally, #7087 resolved this issue. It supports  "1. allow to specify anchor name in HTML output" and "3. allow to refer an index entry via :ref: role" with `:name:` option.
Thank you for patient work, @geographika !
Thank you for discussion, all!
