### ISSUE TITLE
nitpick_ignore cannot ignore :doc:

### ISSUE THREAD

**Issue by tautrimas** [sphinx-doc/sphinx#1673]
Using sphinx 1.2.3.

Having configuration like this:

``` python
nitpicky = True
nitpick_ignore = [('doc', '/handbook/requirements')]
```

I cannot ignore this because of error:

```
Exception occurred:
  File "/usr/local/lib/python2.7/dist-packages/sphinx/environment.py", line 1409, in _warn_missing_reference
    if domain.name == 'std' and (typ, target) in self._nitpick_ignore:
AttributeError: 'NoneType' object has no attribute 'name'
```

Offending line: https://github.com/sphinx-doc/sphinx/blob/1.2.3/sphinx/environment.py#L1409

Variable `domain` is always `None`, because `dtype` is `doc`.

How do I ignore missing links? Because we are building documentation from multiple repos, and we want to validate each of them individually with "warnings as error" flag `-W`. There is no need to ignore links when performing full build, but cross repository links are broken when building repos individually.

**Comment by birkenfeld** [comment]
Thanks for the report!
