### ISSUE TITLE
Sidebar/TOC needs improvements in usability and style

### ISSUE THREAD

**Issue by heliodor** [sphinx-doc/sphinx#1677]
I keep using the Python docs website and can't help but notice how unusable the table of contents in the sidebar is. For example: https://docs.python.org/2/library/stdtypes.html#set.

I'd expect the table of contents to be vertically scannable with the eye, but that's not the case with Sphynx, unfortunately.

Problems:
1) Sidebar is too narrow. There's barely a word or two on the first line of each bullet point.
2) The bullet points are too bright and distract from the contents of each line.
3) Similarly, the numbering gets in the way. Plenty of times, people don't care that they're reading section 15.1.3.7, for example.
4) The line height is too small.

Proposed solutions, respectively:
1) Make the edge of the sidebar draggable so people can expand the sidebar to at least 600px. Or at least add a button to expand it to 600px.
2) The default style should have subtle bullet points.
3) Add a toggle link to turn off the numbering for the whole site, so people can focus on the content instead.
4) Make the default line height big enough to give the text at least a little bit of breathing room.

**Comment by usaturn** [comment]
I'm sorry for the late reply.
This is a matter of HTML theme. Currently, because Python 3's document uses a different theme, I think that the problem has been solved, so I will close it.

Thank you.

**Comment by tk0miya** [comment]
Note: Now Sphinx uses "alabaster" theme by default. The "classic" theme which py2 doc uses is an optional one.
I know these theme is not perfect for ALL of docs. But you can customize them with your own stylesheet.

So I recommend you to customize the width of sidebar in python-doc project.
