### ISSUE TITLE
Use the toctree in template freely

### ISSUE THREAD

**Issue by martin-ueding** [sphinx-doc/sphinx#1679]
I currently use the `toctree()` function in the template to get a navigation for [my whole site](http://martin-ueding.de/). This works well but forces me to have the layout of my site to contain a navigation with this structure.

In the future, I would like to create my own navigation that perhaps uses dropdown items or something else. There is the `parent` variable, but it appears to only have the fields `title` and `link`. I would really like to have the whole site structure in some variable in the template such that I can build my very own navigation using Jinja.

Is there some way to do this? Can I do this by writing an extension? It would be really great if you could lead me into the right direction. Thank you.

---

This is also related to [this question on StackOverflow](https://stackoverflow.com/questions/19413325/change-sphinxs-template-for-table-of-contents).

**Comment by tk0miya** [comment]
Sorry for very late response.

The `toctree()` function returns the toctree rendered as HTML. You can't modify it in template side.

So you have to write an extension to do that.
Sphinx providees `html-page-collect` event to add template variables from an extension.
http://www.sphinx-doc.org/en/stable/extdev/appapi.html#event-html-page-context

The implementation of `toctree()` function is here. Please use it as a reference.
https://github.com/sphinx-doc/sphinx/blob/1.5.3/sphinx/builders/html.py#L732
