### ISSUE TITLE
Make message about missing environment.pickle sound less like an error

### ISSUE THREAD

**Issue by cdeil** [sphinx-doc/sphinx#1680]
After running `sphinx-quickstart` there's always this message when running `make html` for the first time:

```
loading pickled environment... failed: [Errno 2] No such file or directory: '/private/tmp/asdf/_build/doctrees/environment.pickle'
```

To me and a few others this sounds like an error (see [here](http://stackoverflow.com/questions/9490006/sphinx-loading-pickled-environment-failed-errno-2-no-such-file-or-direct), [here](https://github.com/vladris/tinkerer/issues/78) and [here](https://github.com/astropy/photutils/pull/236#issuecomment-70243578)).

Since this is completely normal behaviour, can you please change the message to something more friendly that doesn't contain "failed" and "Errno"?

**Comment by birkenfeld** [comment]
Makes sense.

**Comment by birkenfeld** [comment]
This should actually be already handled here: https://github.com/sphinx-doc/sphinx/blob/master/sphinx/application.py#L220

But the exact type check is not ideal, and it fails on newer Python 3 with the many IOError subclasses.

**Comment by cdeil** [comment]
@birkenfeld - Thank you!
