### ISSUE TITLE
Does sphinx really need to read files out of order and then to save them and discard them from memory?

### ISSUE THREAD

**Issue by callegar** [sphinx-doc/sphinx#1683]
If I am not wrong, sphinx does the following:

1) Reading phase
1a) Read the saved environment
1b) Decide what source files need to be re-read
1c) Pick a file that needs re-reading in arbitrary order
1d) Read it, apply docutil transformations and sphinx own transformations
1e) Update the environment based on what has been found in the file
1f) Save the file as a pickle
1g) Repeat from 1b) until all files are read
1h) Do final things on the environment
2) Move to building phase

Now, this out-of order reading of the input files seems to create complications and misbehaviors. For instance, consider the numpydoc extension. This 'rewrites' bibliographic references. However, since these are found in arbitrary order, they always get rewritten in the wrong order. For instance R5 coming before R1, etc.  This is very noticeable when working with latex output to produce a pdf document.

Furthermore, it is not clear to me why sphinx rewrites each file as a pickle and then reloads each pickle one at a time to do the building.  Why aren't the toctrees kept in memory as they are read? From the documentation I read that this is for memory reasons, but this is certainly not the case, since some builders (such as the latex one) end up compacting all the trees in a single one.  Wouldn't having all the trees in memory after the read phase simplify operations such as the reference rewriting done by numpydoc? The rewriting could be done traversing the 'whole' document tree with much more ease...

**Comment by birkenfeld** [comment]
The trees are pickled and not kept in memory for several reasons. The main reason still is memory use, which should be kept as low as possible even when some builders can't afford that luxury. (However, most large projects will be split over multiple .tex/PDF outputs such as the Python doc, otherwise the page counts and PDF sizes just get out of hand.) The other thing is that, for caching the pickles have to be written anyway.

Now on to numpydoc. I'm not familiar with numpydoc or with how exactly it processes references, but I'm sure that there is no requirement to have all document trees ready in order to fix the problem you describe. The key is to put information in the environment object, do transformation passes on the environment at the end of the reading phase, and handle necessary changes to the trees while loading them, just like resolving references.

(As for 1c), the order is not arbitrary - the filenames are sorted before reading.)

**Comment by callegar** [comment]
Thank you very much for the explanation.

The issue is that, to the best of my understanding, the only thing that numpydoc can do while operating on the reading phase is to make the references somehow unique.

Traversing the 'large' tree in order is the only way to sort them properly and this can be done only after all the sources have been read.

Hence:
1) is it OK to rely on the `env-updated` event to add functionality to perform this tree traversal and store in the environment the 'reference translations' (E.g. ref R5 should become R7)? Or is there some better point to hook onto?
2) If I understand correctly, performing this translation means that all the files where the translations occur need to be marked as 'outdated'. Can this be done at this point?
3) In order not to rewrite all the builders to use this new information there should be some appropriate event in the building phase to connect to. Unfortunately, I cannot find any standard event emitted in the building phase (e.g. a pre-writing event). Is this the case?
4) In case there are no events to connect to, an alternative to rewriting all the builders would be to act at the env-update event to update all the pickles (e.g. load doctree, modify, restore to disk with the references updated).  Would this be OK?  Seems to me sort of contrary to the way sphinx normally operates...

Sorry for all this questions, but unfortunately, there is not much documentation on the way sphinx internally operates.  Unfortunately, at my first encounter with sphinx, I find it almost impossible to produce good pdf documentation in conjunction with autodoc, numpydoc, autosummary. I have alread opened some bugs with respect to obvious things (like the tons of latex overfull boxes caused by autosummary, or the Greek letter escaping), proposing patches, but with respect to citations the matter seems fairly more complex.

**Comment by birkenfeld** [comment]
> Sorry for all this questions

Not at all! We can only improve by getting such feedback. E.g. I'd be happy for the latex output to be overhauled by someone who really knows the developments in that world. While I use latex, it's only for pretty "standard" (and English) stuff. So thank you for submitting issues and patches.

1) That event is emitted once after reading everything. If the reading steps have already extracted necessary information from the trees (e.g. in `doctree-read`) then this is a good point to process everything.

2-3) Currently there is no such event. It's easy to add a mechanism, though. For example, `env-updated` currently doesn't use its return value; it could return a list of docnames to consider outdated. This we could add starting in version 1.3.

4) Even when you update the pickles, it does not mean that the output files are actually written (in case of one-file-per-source-file builders).
