### ISSUE TITLE
sphinx make html error

### ISSUE THREAD

**Issue by XiaogangHe** [sphinx-doc/sphinx#1684]
Hi, everyone, 

I was trying to build html using sphinx. However, I faced the following errors, and have no idea how to solve it. Any idea? Thanks!!

Running Sphinx v1.2.3

Extension error:
Could not import extension matplotlib.sphinxext.only_directives (exception: No module named matplotlib.sphinxext.only_directives)

**Comment by birkenfeld** [comment]
You'll have to install matplotlib, the doc project you're trying to build uses some of its sphinx extensions.

**Comment by XiaogangHe** [comment]
Hi, birkenfeld, thanks for your reply. Actually I already installed matplotlib.
