### ISSUE TITLE
Custom directives do not get "src" attribute set

### ISSUE THREAD

**Issue by itamarst** [sphinx-doc/sphinx#1685]
http://sphinx-doc.org/extdev/markupapi.html#directives claims that a `src` attribute is set on `Directive` instances. This does not appear to be actually set (and I suspect some of the other attributes listed there are also missing).

**Comment by birkenfeld** [comment]
That doc comes directly from the docutils docstring (you might want to report an issue to them as well). I'll have a look and remove not-actually-present attributes.

**Comment by TimKam** [comment]
@tk0miya I think this can be closed :-)

**Comment by tk0miya** [comment]
Indeed. Closed.
