### ISSUE TITLE
-j options does not exit with failure status on failure

### ISSUE THREAD

**Issue by dwaynebailey** [sphinx-doc/sphinx#1688]
When building docs that contain errors in conjunction with using the `-j` option Sphinx will exit with an exit status of 0.  With any use of `-j > 2` the failures do not return a correct failure exit status.

Here are some runs, first with no `-j` options (slightly redacted to make it easier to read) which shows a correct failure exit status:

``` bash
$ make SPHINXOPTS="-W -q" html 
sphinx-build -b html -d _build/doctrees  -W -q . _build/html

Warning, treated as error:
some.rst:17: WARNING: undefined label: roadmap (if the link has no caption the label must precede a section header)

make: *** [html] Error 1
$ echo $?
2
```

Followed by `-j 4` with the same error present. This results in an exit status of 0, no failure:

``` bash
$  make SPHINXOPTS="-W -q -j 4" html 
sphinx-build -b html -d _build/doctrees  -W -q -j 4 . _build/html
Process Process-4:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run

### REPEATED A FEW TIMES ###


Build finished. The HTML pages are in _build/html.
$ echo $?
0
```

**Comment by birkenfeld** [comment]
Thanks, I will look into this.

**Comment by birkenfeld** [comment]
OK, the warnings are now emitted. But the "Process ... Traceback" lines are strange, they should not be there...
