### ISSUE TITLE
C++ domain doesn't understand function parameters with a const binding to the left.

### ISSUE THREAD

**Issue by bruxisma** [sphinx-doc/sphinx#1689]
Given the following:

``` rst
.. function:: constexpr T operator () (T const&, T const&) const

   some text describing the above operation
```

Sphinx will complain with the following output:

```
WARNING: Invalid definition: Expecting "," or ")" in parameters_and_qualifiers, got "&". [error at 32]
  constexpr T operator () (T const& lhs, T const& rhs) const
  --------------------------------^
```

And not generate any entries.

Moving `const` to be before _T_ for each parameter removes this warning, and the correct behavior will occur.

These function signatures are taken directly from C++11 source code. This behavior was encountered with 1.3b2

**Comment by jakobandersen** [comment]
This is indeed a bug. I will make a pull request to fix this soon.
Should Sphinx normalise the position of `const`? or should it be output where it was in the input? Should this be configurable? It looks like "volatile", "friend", "static", "virtual", "constexpr", etc. are also allowed to be on the right of the type. E.g. `T  constexpr operator () (T const& lhs, T const& rhs) const` compiles.
I guess any normalisation should only apply to `const` and `volatile`, or at least be separate.

**Comment by bruxisma** [comment]
I personally would prefer the output to not be normalized, as I try to write the function signatures as they are in the source code so that someone can copy-paste into a terminal and grep if necessary (or do a search in the file). On the other hand I'd rather have it work correctly, so my opinion stops there.

**Comment by jakobandersen** [comment]
PR #1705 should fix this issue (I failed to tag the commit). decl-specifiers are properly allowed on both sides of the type, and will be rendered on the same side as in the input. The order among decl-specifiers is however still normalised.

**Comment by bruxisma** [comment]
Awesome! Thank you so much for all your work on the C++ domain. It's made my job so much easier and saved me a ton of time. :)
