### ISSUE TITLE
toctree bug with :glob: option 

### ISSUE THREAD

**Issue by coolplay** [sphinx-doc/sphinx#1690]
In Sphinx, we can specify explicit title with following method:

``` rst
.. toctree::

   explicit title <file>
   blahblahblah
```

This works fine until the `:glob:` flag is turned on, where Sphinx fails to match any file named file.rst.

I don't know whether this can be called a bug, but hope to hear your solution.

**Comment by birkenfeld** [comment]
Thanks for the report!

**Comment by coolplay** [comment]
thanks
