### ISSUE TITLE
make command not found

### ISSUE THREAD

**Issue by christinepham** [sphinx-doc/sphinx#1693]
Hi,

So I downloaded sphinx and ran sphinx-build which gave me the Makefile and make.bat file. But when I run 'make' I get told that it's not found. I'm using a git shell on a Window's machine. Thanks in advance!

**Comment by frenetic** [comment]
Hello o/
At first, did you try running the **make.bat** from the Windows CMD? (not the git bash).

If this doesn't work, you can try downloading the make for your bash.
Go to http://sourceforge.net/projects/mingw/files/MSYS/Base/make.
There you will find 3 different versions, try downloading the newest first.
To download, click on the folder, which will lead you to a new page. Look for the file that has the BIN on the description, for example: make-3.81-3-msys-1.0.13-**bin**.tar.lzma
Download it and extract the make.exe from it (7zip is a good tool for that).
Move the **make.exe** to the **bin** folder inside of your git instalation. Probably it will be on C:\Program Files (x86)\Git.
After moving the **make.exe** to the **bin** folder, close all of your git bashes.
Open a new one and try the **make** command.
If it doesnt work, try downloading a older versions of the make.

Note: remember to close all of your git bashes before openning a new one to try the make command.

I hope it works.

**Comment by birkenfeld** [comment]
As @frenetic said, you'll either have to use Windows' `cmd` shell to use the `make.bat` file, or install a GNU make program for use in the Git bash. The Git bash cannot execute Windows batch files.

**Comment by richardwang96** [comment]
按这个教程https://blog.csdn.net/nicholas_liu2017/article/details/78323391 直接安装WinGW，再把make拷出来也可以

**Comment by Rattanpal1** [comment]
Just add environment variable

C:\Program Files (x86)\GnuWin32\bin

Thats All.

Cheers,
Ranjit
