### ISSUE TITLE
Allow getting URL to a reference from theme templates.

### ISSUE THREAD

**Issue by tomprince** [sphinx-doc/sphinx#1702]
I'd like to have some deeplinks to some parts of the documentation in a footer. Right now, I have something like 

``` html
<li><a href="{{ pathto('indepth/installation') }}#using-amazon-web-services">AWS</a></li>
```

but it would be nice if I could change this to

``` html
<li><a href="{{ refto('using-amazon-web-services' }}">AWS</a></li>
```

or something. I think the former will break on the given page, since it will render as

``` html
<li><a href="##using-amazon-web-services">AWS</a></li>
```

**Comment by shimizukawa** [comment]
FYI, this is it: https://gist.github.com/shimizukawa/37e26f6353327dad3f9d
