### ISSUE TITLE
Broken permalinks for C++ classes when migrating to version 1.3

### ISSUE THREAD

**Issue by vitaut** [sphinx-doc/sphinx#1704]
The code

```
.. cpp:class:: TestClass
```

generates a permalink of the form `<filename>.html#_CPP9TestClass` in Sphinx version 1.3. In version 1.2 it was just `<filename>.html#TestClass` which is much cleaner and more consistent with other domains.

For nested classes it is even worse, for example, `_CPPN9TestClass6NestedE` for `TestClass::Nested`.

Apart from general readibility, this will also break the links to the documentation from external sources and violate the whole purpose of permalinks when migrating from Sphinx 1.2 to Sphinx 1.3.

**Comment by jakobandersen** [comment]
Unfortunately the old ids were not unique in general (e.g., didn't respect the namespace directive). Instead of reinventing the wheel, I changed the generation scheme to follow one of the normal name mangling schemes used by compilers.
In the branch with commit f4cf30b I have tried to replicate the old ids in addition to the new. Temporarily it uses the old links as the shown permalink (but new links also work), so the ids can be extracted from the index for comparison with links from v1.2. Please report any declarations where ids are not correct.

**Comment by vitaut** [comment]
Thanks a lot for the explanation and adding support for backward-compatible IDs. While I agree that the old approach was incomplete, I am a bit concerned that using a mangling scheme designed for internal use in compilers/linkers and which is rather obscure is not the best match for a documentation system where readability is more important (even if it concerns URLs which are visible to user). Cannot the old scheme which is very readable and close to C++ code be extended to accommodate for namespace directive?

**Comment by jakobandersen** [comment]
The namespaces are rather easy to add, but there are some other cases it didn't support that are much more complicated. I don't find it trivial do create a mangling scheme without errors, and I don't know if the old scheme had other collisions than that from missing namespaces. I will rather trust the Itanium ABI, and accept somewhat obscure ids. This also makes it easier to check the mangling implementation for errors.

**Comment by vitaut** [comment]
I still don't understand the purpose of mangling here. Why not simply use the full signatures as they are as it is done by other documentation systems and Sphinx domains. Here are just a few examples: 

Python:

```
string.html#string.Formatter
```

JavaDoc:

```
http://docs.oracle.com/javase/7/docs/api/java/io/Writer.html#write(char[], int, int)
```

Sphinx Java domain provided by [JavaSphinx](https://github.com/bronto/javasphinx):

```
JunitPathMapper.html#com.nikolavp.approval.pathmappers.JunitPathMapper.getPath(Object, Path)
```

As you can see, neither is using any mangling and have clean IDs that directly correspond to the declarations they identify. The same can be done for C++. This will simplify (and, possibly, speed up) generation of IDs as there will be no mangling step involved and make the IDs easily verifiable which is not possible with the currently used complex mangling scheme more suitable for use in compilers.
