### ISSUE TITLE
make visited links default color different

### ISSUE THREAD

**Issue by lilydjwg** [sphinx-doc/sphinx#1708]
Browsers differ visited links with unvisited ones. And some users (like me) make use of this: it makes it easier to find frequently visited links, especially when there is a list and I often visit a small fraction of links in the list. It also tells me whether the content behind a link is fresh to me, or I've already read, as I don't remember the exact titles.

Making visited links default color different from unvisited ones, so when the doc authors don't find a reason to make them the same, they will be different, as the browsers always do.

**Comment by tk0miya** [comment]
In my short investigation:
I checked bundled themes and the alabaster theme.
- alabaster: NG (same color)
- classic: NG
- bizstyle: NG
- agogo: NG
- haiku: OK (different colors)
- nature: NG
- pyramid: NG
- scrolls: NG
- sphinxdoc: NG
- traditional: OK

`alabaster` theme: text color for whole of anchors (`:visited` too) is defined at `alabaster/static/alabaster.css_t`. 

```
183:/* -- body styles ----------------------------------------------------------- */
184:
185:a {
186:    color: {{ theme_link }};
187:    text-decoration: underline;
188:}
```

`classic` theme: `classic` theme can use different colors for unvisited links and visited one. but, now, same color is used for both  at `sphinx/themes/classic/theme.conf`. 

```
26:linkcolor        = #355f7c
27:visitedlinkcolor = #355f7c
```

**Comment by tk0miya** [comment]
I'd change color of visited links, but I do not have design (coloring?) skills.
Can anyone support me about this?

**Comment by septatrix** [comment]
I would choose something similar to the [html5 reference](https://html.spec.whatwg.org/multipage/rendering.html#phrasing-content-3) color as this is what most people probably expect...

```css
:link { color: #0000EE; }
:visited { color: #551A8B; }
:link:active, :visited:active { color: #FF0000; }
:link, :visited { text-decoration: underline; cursor: pointer; }
```

So maybe just add a bit more red to give it a purplish tint? An alternative would be to just define the default color as `initial` so the browser default will be chosen

**Comment by naveen8801** [comment]
Hiii @septatrix  , is this issue open ? , can i work on it ?

**Comment by tk0miya** [comment]
@naveen8801 This issue have not been resolved yet. So any pull requests are welcome!

**Comment by naveen8801** [comment]
@tk0miya , Ok , thanks !

**Comment by Vaibhavi1707** [comment]
Hi @septatrix, can I work on this issue? I intend to change the visited link colour to ` initial` as you suggested. I'm a beginner in open source and want to start off here.

**Comment by septatrix** [comment]
I am not a maintainer but by the looks of it no one has started to work on this. @naveen8801 has not posted an update or PR yet but you may want to ask him. Otherwise just go ahead - it should be rather simple.

**Comment by Vaibhavi1707** [comment]
Okay, thank you :)

**Comment by Vaibhavi1707** [comment]
Where can I find the alabaster theme module?

**Comment by tk0miya** [comment]
Here: https://github.com/bitprophet/alabaster

**Comment by septatrix** [comment]
All the bundled themes should be here IIRC: https://github.com/sphinx-doc/sphinx/tree/3.x/sphinx/themes

**Comment by Vaibhavi1707** [comment]
Thanks a lot. I've made the changes in the other themes and submitted pull request #9027. Can anyone please have a look? I'll commit my alabaster changes to the other repo later today.

**Comment by kaycebasques** [comment]
I just put in a fix. Even if that PR doesn't work for whatever reason, I figured I would share the Bash script that I created to speed up the process of generating the screenshots for each theme:

```
conf=/tmp/1708/conf.py

if [ -d "/tmp/1708" ]; then
  rm -rf /tmp/1708
fi

echo "setting up /tmp/1708"
sphinx-quickstart --project=1708 --author=1708 --quiet /tmp/1708
mkdir /tmp/1708/_my_themes
echo "html_theme_path = ['_my_themes']" >> $conf
mv sphinx/themes/* /tmp/1708/_my_themes/
git checkout -- .
ls /tmp/1708/_my_themes

cd /tmp/1708
make html
xdg-open /tmp/1708/_build/html/index.html

function build {
  echo "html_theme = '$1'" >> $conf
  make html
  read -p "Create $1-after.png and then press Enter to continue: " unused
}

build "agogo"
build "basic"
build "bizstyle"
build "classic"
build "default"
build "epub"
build "haiku"
build "nature"
build "nonav"
build "pyramid"
build "scrolls"
build "sphinxdoc"
build "traditional"

cd -
```
