### ISSUE TITLE
[bug] $.browser is undefined in doctools.js

### ISSUE THREAD

**Issue by marble** [sphinx-doc/sphinx#1709]
In jQuery 1.9 the `$.browser` function/property has been removed. So we now get `TypeError: $.browser is undefined`. This happens here:
https://github.com/sphinx-doc/sphinx/blob/master/sphinx/themes/basic/static/doctools.js#L182
Compare with http://jquery.com/upgrade-guide/1.9/#jquery-browser-removed
http://modernizr.com/ is recommended by the jQuery people.

**Comment by bfncs** [comment]
I can replicate this problem, it leads to a JS error on all pages using the basic template opened with a hash in the URL.

There's a better workaround that doesn't rely on `jQuery.browser` as a [comment to the original bug description](https://bugzilla.mozilla.org/show_bug.cgi?id=645075#c39).
