### ISSUE TITLE
:numref: does not work with capital letters in the label

### ISSUE THREAD

**Issue by Jellby** [sphinx-doc/sphinx#1718]
```
.. _code_1:

.. code-block:: none
   :caption: Lowercase

   Test code
.. _Code_2:

.. code-block:: none
   :caption: Uppercase

   Test code

References to :numref:`code_1` and :numref:`Code_2`
```

The references appear as "Listing 1" (correct) and "Code 2" (wrong). But the link is correct, it's only the number which is not picked up.

**Comment by shimizukawa** [comment]
Thanks for reporting!

In fact, label names are normalized as "code-2".
I suspect that `:numref:` target names aren't normalized.
We will fix it soon.

For a moment, please use lowercase label. Thanks.

**Comment by Jellby** [comment]
Proposed fix: In sphinx/domains/std.py (line 638) change:

```
title = contnode.astext()
```

to:

```
title = contnode.astext().lower()
```
