### ISSUE TITLE
toctree template does not expand in agogo theme

### ISSUE THREAD

**Issue by Jellby** [sphinx-doc/sphinx#1722]
With 1.2.3 and the agogo theme, the toctree in the sidebar expands as the entries are clicked, or deeper sections visited (see "Documentation" and "Software" in http://www.florian-diesch.de/index.html). With 1.3b2, all I see is the top sections, and never anything else.

**Comment by shimizukawa** [comment]
I can't figure out the detail. I think something relates to toctree in the sidebar was changed at 1.3beta. Please let me know the small sample sphinx project to reproduce the problem.

**Comment by Jellby** [comment]
Main file with:

```
.. toctree::

   test1
   test2
```

test1.rst:

```
Test 1
======

.. toctree::

   one
   two
```

one.rst:

```
One
===
```

two.rst

```
Two
===
```

test2.rst

```
Test 2
======
```

And in conf.py:

```
html_theme = 'agogo'
```

Is this enough?

I tried to look in the code, but I can't find where the toctree() template is processed...

**Comment by shimizukawa** [comment]
Thanks, I got. The change da4c67e2a35ef84395a0d6cee84a13b661c458c0 cause this issue. I'll fix it.
