### ISSUE TITLE
sphinxcontrib.findanything

### ISSUE THREAD

**Issue by DrLulz** [sphinx-doc/sphinx#1726]
Might someone here know how to fix this? Most appreciative. 

`easy_install sphinxcontrib-findanything`

```
extensions = [
    'sphinx.ext.todo',
    'sphinx.ext.mathjax',
    'sphinxcontrib.googlechart',
    'sphinxcontrib.findanything',
]
```

```
Running Sphinx v1.3b2
Extension error:
Could not import extension sphinxcontrib.findanything (exception: cannot import name any)
```

**Comment by lehmannro** [comment]
Yikes!  It seems sphinxcontrib-findanything is not compatible with Sphinx 1.3+.  Until we get this resolved, you could monkeypatch it like this somewhere in `conf.py`:

```
import sphinx.util.pycompat                                                     
sphinx.util.pycompat.any = any
```

@birkenfeld, @shimizukawa:  I think we need to keep `sphinx.util.pycompat`'s API stable for backwards-compatibility.  What do you think?

**Comment by shimizukawa** [comment]
@lehmannro sounds good.

IMO, we should define API to keep or not keep compatibility.
For a moment, we should recover compatibility on `pycompat.py` with deprecation warning.

**Comment by lehmannro** [comment]
PR coming in a few minutes.

**Comment by birkenfeld** [comment]
Hmm, I wouldn't have considered pycompat to be public API. With the switch from 2to3 to single-source the compatibility infrastructure is expected to change in any case.

However, since you already did the work, I see nothing wrong with offering compatibility with deprecation warnings.
