### ISSUE TITLE
Not included file is nevertheless included in EPUB

### ISSUE THREAD

**Issue by juh2** [sphinx-doc/sphinx#1730]
When you create a file foo.rst which is not included with a toctree directive it is nevertheless included in the epub file. This can cause problems:
1. There is information in the epub which should not be included (security)
2. When you convert the epub on Kindle Direct Publishing the excluded content shows up at the end of the Kindle ebook.

**Comment by shimizukawa** [comment]
In fact, it's not only EPUB but also other builders' output.
Sphinx emits WARNING if the foo.rst doesn't belong any toctree at building time.

**Comment by juh2** [comment]
So at least the WARNING should indicate the security problem.

**Comment by shimizukawa** [comment]
I can't decide whether file doesn't referred from toctree is intended or not.

For such case, I recommend `-W` option for sphinx-build that turn WARNING into ERROR.
Now I close this issue. Please feel free to reopen if you have any comments. Thanks.

**Comment by juh2** [comment]
I think Sphinx should not include anything that is not intended to be included.
