### ISSUE TITLE
Use https in default python stdlib intersphinx mapping url

### ISSUE THREAD

**Issue by thijstriemstra** [sphinx-doc/sphinx#1735]
When you start a new project and enable intersphinx, it'll add the following to `conf.py`:

``` python
intersphinx_mapping = {'http://docs.python.org/': None}
```

Please use the https link instead:

``` python
intersphinx_mapping = {'https://docs.python.org/': None}
```

Ask Snowden why. :palm_tree: 

I can make a PR but not sure where to start (and where its tested).

**Comment by shimizukawa** [comment]
Thanks for your reporting! I'll do it soon :)
