### ISSUE TITLE
error during moving rst file to subfolder

### ISSUE THREAD

**Issue by nazarlviv07** [sphinx-doc/sphinx#1736]
Hi,

Now all my .rst files are in the folder ( docs).

```
docs/
    file1.rst
    file2.rst
     file3.rst
```

When I create subfolder ( folder3) and move there file3.rst file.

```
docs/
   file1.rst
   file2.rst
   folder3/
       file3.rst
```

After that error occured.

```
 Sphinx version: 1.2.2
 Python version: 2.7.0
 Docutils version: 0.11 release
 Jinja2 version: unknown
 Loaded extensions:
   sphinx.ext.autodoc from \\deploy\1.9.83-20150101100747\lib\Lib\sphinx\ext\autodoc.py
   sphinx.ext.oldcmarkup from \\deploy\1.9.83-20150101100747\lib\Lib\sphinx\ext\oldcmarkup.py
Traceback (most recent call last):
  File "\\deploy\1.9.83-20150101100747\lib\Lib\sphinx\cmdline.py", line 254, in main
    app.build(force_all, filenames)
  File "\\deploy\1.9.83-20150101100747\lib\Lib\sphinx\application.py", line 212, in build
    self.builder.build_update()
  File "\\deploy\1.9.83-20150101100747\lib\Lib\sphinx\builders\__init__.py", line 212, in build_update
    self.build(to_build,
  File "\\deploy\1.9.83-20150101100747\lib\Lib\sphinx\builders\__init__.py", line 233, in build
    for docname in self.status_iterator(iterator, 'reading sources... ',
  File "\\deploy\1.9.83-20150101100747\lib\Lib\sphinx\builders\__init__.py", line 134, in status_iterator
    for item in iterable:
  File "\\deploy\1.9.83-20150101100747\lib\Lib\sphinx\environment.py", line 477, in update_generator
    self.read_doc(docname, app=app)
  File "\\deploy\1.9.83-20150101100747\lib\Lib\sphinx\environment.py", line 690, in read_doc
    os.makedirs(dirname)
  File "\\deploy\1.9.83-20150101100747\lib\jython-standalone-2.7-b4.jar\Lib\os.py", line 172, in makedirs
    mkdir(name, mode)
    OSError: [Errno 17] File exists: '\\\\deploy\\1.9.83-20150101100747\\docs\\doctrees\\a_language'.
```

---

Same issue was created early (https://github.com/sphinx-doc/sphinx/issues/1678 ).
Early it was jython issue.

Jython fault is  corrected in Jython 2.7 b4  ( today we have received new version of jython), now we received correct OSError 17 , but after that exception should be caught by Sphinx and err.errno is checked.
 Errno 0 & 17 are ignored.  
But  Sphinx doesn’t ignore errno 17 now . 

Do you know about that problem?
Could you tell me when this issue approximately will be corrected ?

Thanks,

Br,
Nazar

**Comment by birkenfeld** [comment]
Hi,

nice that Jython fixed this bug. However, there is still a problem somewhere, since the call to `os.makedirs()` in Sphinx is guarded by `if not os.path.isdir()` (the line before). I could add a workaround, but this is not ideal.

Can you check id `os.path.isdir()` works with UNC paths?

**Comment by nazarlviv07** [comment]
Hi,

I have checked how os.path.isdir() is working with UNC paths.
List of the program is below:

```
import os
import sys

dirname_folder1 = "\\\\sphinx_python\\folder1"

list = os.listdir("\\\\sphinx_python")

print list

print "folder1 is dir "
print os.path.isdir(dirname_folder1)
print dirname_folder1
```

Printout from console is below 

```
H:\sphinx_python>test.py
['start', 'test.py', 'test_old.py', 'folder1']
folder1 is dir
True
\\sphinx_python\folder1
```

We can assume that os.path.isdir() works with UNC paths.

Correct me If I am wrong.
Thanks.

**Comment by birkenfeld** [comment]
This is just a problem with your example script: you should write `"\\\\sphinx_python\\folder1"`, otherwise Python interprets the `\f` as a formfeed character.

**Comment by nazarlviv07** [comment]
Thanks, you are right. I have already update program ( updated list of program and printout are in my previous comment).
I have also noticed that in sphinx/environment.py, part of code is below

```
 if not path.isdir(dirname):
     os.makedirs(dirname)
```

we received OSError 17 even if folder is not created.
Probably it is fault in os.makedirs(dirname).

I have already register issue in jython page (http://bugs.jython.org/issue2277)

**Comment by tk0miya** [comment]
I think that is too nervous to handle errors from python primitives.
In addition, 9 months has passed since the bug was fixed. So there is no need to handle it.

Now, I'll close this issue after a week.
Please comment here if you has any advices or objections.

Thanks,

**Comment by shimizukawa** [comment]
Now I close this issue.
Please feel free to reopen at any time if you still have the issue.
