### ISSUE TITLE
:py:obj: equivalent in cpp domain

### ISSUE THREAD

**Issue by vitaut** [sphinx-doc/sphinx#1744]
The Python domain has the [`:py:obj:` role](http://sphinx-doc.org/domains.html#role-py:obj) that can be used to reference an object of any kind:

> :py:obj:
> Reference an object of unspecified type. Useful e.g. as the default_role.

It would be extremely useful if similar role (e.g. `:cpp:obj:`) was available in the cpp domain. Currently there are only roles that refer to a single kind of object like `:cpp:function:` or `:cpp:class:` which doesn't work very well with the `default_role`.

**Comment by jakobandersen** [comment]
Currently all the roles in the C++ domain can reference any declaration (the only difference being that `func` adds `()` after the name). There is now a `cpp:any` role which should keep working like this.

**Comment by vitaut** [comment]
Thanks @jakobandersen.
