### ISSUE TITLE
Error building sphinx_rtd_theme demo docs with pdf target

### ISSUE THREAD

**Issue by fcoelho** [sphinx-doc/sphinx#1745]
I'm getting this error when trying to build `sphinx_rtd_theme`'s [demo docs](https://github.com/snide/sphinx_rtd_theme/tree/master/demo_docs):

``` pytb
File "/tmp/themetest/env3/lib/python2.7/site-packages/sphinx/util/smartypants.py", line 219, in educate_quotes_latex
    s = opening_single_quotes_regex.sub("\\1\x03", s)
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

I tried using Sphinx 1.2, 1.3b3, and also tried sphinx directly from GitHub. All three versions generated the same error.

What could be causing this and where should I look into fixing that? The error is being caused by the `source/demo.rst` file, which is, apart from ~15 lines, a copy of http://docutils.sourceforge.net/docs/user/rst/demo.txt

**Comment by shimizukawa** [comment]
Thanks for your reporting!
The issue can be reproduced with this small example w/o sphinx_rtd_theme:

```
BODY footnote mark to label1: [#label1]_ .

.. [#label1] FOOTNOTE label1 to label1: [#label1]_.
```

I'll fix it.
