### ISSUE TITLE
C++ domain function arguments and returns as well as references do not look within local tree for cross references

### ISSUE THREAD

**Issue by bruxisma** [sphinx-doc/sphinx#1746]
Given a document "string.rst" with the following content:

``` rst
.. default-domain:: cpp
.. class:: basic_string_view<CharT, Traits>

   .. type:: reference

      some text describing this

   .. function:: reference front () const noexcept

      :returns: :type:`reference` to the first item in the string_view
```

And a different file that gets processed in order _before_ 'string.rst' named 'memory.rst' with the following content:

``` rst
.. default-domain:: cpp
.. class:: observer_ptr<T>

   .. type:: reference
```

The resulting HTML will link to the memory.rst reference declaration. The only solution workaround I've had thus far regarding this is to explicitly place the class name in front of every single parameter, function and return type, which can get extremely lengthy in some cases...

``` rst

.. type:: basic_string_view<CharT, Traits> basic_string_view<CharT, Traits>::substr(basic_string_view<CharT, Traits>::size_type pos=0, basic_string_view<CharT, Traits>::size_type n = basic_string_view<CharT, Traits>::npos) const noexcept
```

This behavior wasn't in sphinx 1.2 and local links would perform the correct lookup.

**Comment by jakobandersen** [comment]
Thanks, there are two lookup bugs, but I'm not sure if I get the same result as you describe, so maybe there is a third. I tried compiling with both `memory.rst` and `string.rst`, and with `memory.rst` and `a_string.rst` to get the reverse processing order. In both cases I get the following in string.rst/a_string.rst:

``` rst
.. default-domain:: cpp
.. class:: basic_string_view<CharT, Traits>

   .. type:: reference

      some text describing this

   .. function:: reference front () const noexcept

      Bug: the return type should have been a link to the local `reference` declaration as well. I get no link.

      :returns: :type:`reference` this points to the expected local `reference` declaration
```

Do you get something else?

**Comment by bruxisma** [comment]
Odd, I will get a different 'reference' if described in another class, or explicitly defined like `.. type:: myclass::reference:` in some cases (thought not all).

Other times I do get where the return type ends up not linking to the local reference declaration. :/

**Comment by jakobandersen** [comment]
The name lookup bugs I know of should be fixed now. The following code should now have correct links, and all of them.

``` rst
.. default-domain:: cpp

Link test: :any:`::A` and :any:`A`

.. class:: A

    Link test: :any:`::A` and :any:`A`

    .. class:: A

        Link test: :any:`::A` and :any:`A`

    .. type:: T

    .. function:: Template<T> f(T, Template<T>)

```

@slurps-mad-rips, do you still get strange results?

**Comment by bruxisma** [comment]
So far, so good! I need to do one more test. I'm getting a bunch of 'duplicate id' warnings in a specific file where many types have the same member typedefs, but it may not be related to this.

**Comment by bruxisma** [comment]
OK, everything looks good! But... I've found another bug, it seems. I'll try to get a minimal test case for reproducing and file that as a separate bug. Can't quite tell what is causing it, but there are a bunch of incorrect warnings concerning 'duplicate IDs'

**Comment by jakobandersen** [comment]
Great, at least the name lookup seems fixed :-).
