### ISSUE TITLE
excessive output in parallel build?

### ISSUE THREAD

**Issue by andreacassioli** [sphinx-doc/sphinx#1749]
Hi,
I have noticed that running Sphinx 1.2b3 with more than one thread it generates a huge amount of duplicates warnings. 

Durring the writing phase, a warning generated running on one thread is repeated 36 times on 2 o more threads! 

Now, apart from the cluttering of the output and the huge increase of the output size, I wonder if it may be related to this issue I reported once https://github.com/sphinx-doc/sphinx/issues/1640

I have been not able to consistently reproduce the issue, but it happens again recently. I can not install 1.3 beta now to see whether it has been implicitly solved.

**Comment by birkenfeld** [comment]
I'm sorry, we can't support 1.2b3 anymore. If this can be reproduced with 1.3b3 or 1.3 (to be released in a few hours), please reopen.
