### ISSUE TITLE
Invalid definition for a C++ function taking an array reference as an argument

### ISSUE THREAD

**Issue by vitaut** [sphinx-doc/sphinx#1753]
I get the error

```
index.rst:1: WARNING: Invalid definition: expected identifier [error at 1]
  f(int (&array)[10])
  -^
```

on the following Sphinx code:

```
.. cpp:function:: f(int (&array)[10])
```

**Comment by lehmannro** [comment]
No, _expected identifier_ is unrelated to cppformat/cppformat#125:  This complaint is about the missing return type. `void f(int &array[10])` works fine.  The underlying issue with template declarations should be covered in #1314.

**Comment by vitaut** [comment]
I get an error even with return value on Sphinx 1.3b3:

```
index.rst:1: WARNING: Invalid definition: Expecting "," or ")" in parameters_and_qualifiers, got "(". [error at 11]
  void f(int (&array)[10])
  -----------^
```

**Comment by vitaut** [comment]
Please note that the declaration is `void f(int (&array)[10])` and not `void f(int &array[10])` as an array of references is not valid in C++.

**Comment by lehmannro** [comment]
Can you drop the surrounding braces around `&array`?

**Comment by vitaut** [comment]
> Can you drop the surrounding braces around &array?

Unfortunately not, because it changes semantics.

**Comment by jakobandersen** [comment]
Yes, this is indeed a bug. Furthermore, the error is not accurate. In this case it should be
`Invalid definition: Expecting "," or ")" in parameters_and_qualifiers, got "(".` as you indicate.
I'm working on a fix.

**Comment by vitaut** [comment]
Thanks, @jakobandersen.
