### ISSUE TITLE
Sphinx 1.3b3 requires jsonschema and mistune (used by parallel.py), not declared as package dependency

### ISSUE THREAD

**Issue by ViktorHaag** [sphinx-doc/sphinx#1754]
It appears that .../sphinx/util/parallel.py requires `jsonschema` and the `mistune` packages, but these don't seem to be declared in the package as dependencies. Making HTML with parallel writers provokes these errors -- first, this:

```
waiting for workers...

Exception occurred:
  File "/usr/local/lib/python2.7/site-packages/sphinx/util/parallel.py", line 114, in join
    raise SphinxParallelError(*result)
SphinxParallelError: ImportError: No module named jsonschema

    IPython notebook format depends on the jsonschema package:

        https://pypi.python.org/pypi/jsonschema

    Please install it first.
```

then, this:

```
writing output... [ 62%] foo .. bar                                                     
Exception occurred:
  File "/usr/local/lib/python2.7/site-packages/sphinx/util/parallel.py", line 103, in add_task
    raise SphinxParallelError(*result)
SphinxParallelError: ImportError: No module named mistune
```

After manually installing jsonschema and mistune packages, the `make html` passes fine.

**Comment by birkenfeld** [comment]
Sphinx doesn't require either of these packages; however, it is possible that the documentation project imports them, e.g. through autodoc. 

The error should be the same when you build with `-j1`. If it isn't, we'll have to find out why.

**Comment by ViktorHaag** [comment]
I can confirm that the error still occurs (dependency on jsonschema), but is not exactly the same (see below). Presumably it doesn't get thrown from parallel.py, because the execution path with -j1 does not pass through it -- so, I guess this isn't an issue with the Sphinx core itself, but it's still an issue with the Sphinx packaging.

```
[klm2-vhaag:~/foo] % make SPHINXOPTS="-j1" html
/usr/local/bin/sphinx-build -b html -j 3 -d "/in"/int/doctrees -D latex_paper_size=letter -A d2l_internal=true -t internal -j1 . "/out"/int/html
Running Sphinx v1.3b3
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 76 source files that are out of date
updating environment: 76 added, 0 changed, 0 removed
reading sources... [100%] bar                                                                     
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [ 11%] rod                                                                     
Exception occurred:
  File "/usr/local/lib/python2.7/site-packages/IPython/nbformat/validator.py", line 21, in <module>
    raise ImportError(str(e) + verbose_msg)
ImportError: No module named jsonschema

    IPython notebook format depends on the jsonschema package:

        https://pypi.python.org/pypi/jsonschema

    Please install it first.
```

**Comment by shimizukawa** [comment]
@ViktorAtD2L `IPython/nbformat/validator.py` requires jsonschema, ref: https://github.com/ipython/ipython/blob/master/IPython/nbformat/validator.py

However sphinx doesn't depend on IPython.
It seems your documentation or some python code requires IPython.

To get more details, you can use `-T` and `-vvvv` option for sphinx-build command. Please check it.

**Comment by ViktorHaag** [comment]
Ah, I see what's happened, I think. I'm using Pygments, and the documentation build is choking when it gets to using Pygments to format a code-block that's explicitly typed as type "http". This is almost certainly down to a recent upgrade of either the Pygments or IPython libraries and not to do with Sphinx. I will close this issue.

Thanks for your patience.
