### ISSUE TITLE
Using more complication glob patterns in toctree directives

### ISSUE THREAD

**Issue by jamiehannaford** [sphinx-doc/sphinx#1755]
Is it possible in the `toctree` directives to have glob patterns like `specs/*/index.rst`? I'd love to be able to pull in one common file from multiple directories without having to manually define the directory names (from the project root `index.rst`). Is this currently possible? If not, would it be a suitable enhancement for somebody to write a PR for?

**Comment by birkenfeld** [comment]
This should be possible already, with two caveats: the globbing works on document names, not file names, so you should remove the `.rst` suffix. And a single `*` does not match directory separators, use `**` for that.

**Comment by jamiehannaford** [comment]
@birkenfeld Awesome, got it working. Thanks for the pointers :)
