### ISSUE TITLE
Incorrect section titles in search

### ISSUE THREAD

**Issue by vitaut** [sphinx-doc/sphinx#1756]
Search results sometimes display incorrect titles. Here's a repo that reproduces the problem: https://github.com/vitaut/amplgsl-sphinx

How to reproduce:

```
$ git clone https://github.com/vitaut/amplgsl-sphinx.git
$ cd amplgsl-sphinx
$ make
```

Then open `_build/html/index.html` and search for "zeta". This will show the following search results:

![screenshot from 2015-03-04 16 53 45](https://cloud.githubusercontent.com/assets/576385/6497020/25004940-c28f-11e4-968e-2835f822debb.png)

Observe that clicking on any link leads to a wrong section, for example clicking on "The Weibull Distribution" opens "Special Functions".

**Comment by shimizukawa** [comment]
Confirmed. It also can be reproduced by using sphinx documentation http://sphinx-doc.org/latest/search.html?q=todo+items
It seems just searched titles are not correct.
