### ISSUE TITLE
Could you please rewrite the step-by-step instructions to create documentation using sphinx?

### ISSUE THREAD

**Issue by shyamalschandra** [sphinx-doc/sphinx#1761]
Hi,

I have tried many times and have been unsuccessful.  If you could help, this would be great!

Thanks!

**Comment by lehmannro** [comment]
Hi Shyamal, thanks for your report!  I assume you're talking about the [First Steps with Sphinx](http://sphinx-doc.org/tutorial.html) document.  Could you be a bit more specific and attach error reports or exact steps you've struggled with?  From a cursory glance I could not see anything wrong with it.

**Comment by shyamalschandra** [comment]
How am I supposed to specify the source directory which I want to recursively drill down through?

**Comment by lehmannro** [comment]
I am not sure I understand your problem.  If you use `sphinx-quickstart` you have been prompted for a _root path for the documentation,_ which defaults to the current directory (where you have executed the quickstart command.)  All source files, eg. `index.rst`, need to be present in that directory.

Please also note that such questions are better directed at our [sphinx-users](http://groups.google.com/group/sphinx-users) mailing list.

**Comment by shyamalschandra** [comment]
Thanks!
