### ISSUE TITLE
Wrong :numref: links for figure, table and code-block

### ISSUE THREAD

**Issue by Jellby** [sphinx-doc/sphinx#1763]
Similar test file as in #1742:

```
Float Test
==========

.. figure:: acrolein.*
   :name: my_figure

   Figure caption

.. table:: Table caption
   :name: my_table

   === === ===
   1   2   3
   4   5   6
   === === ===

.. code-block:: none
   :name: my_block
   :caption: Block caption

   Foo

References to :ref:`my_table`, :ref:`my_figure`, :ref:`my_block`.

References to :numref:`my_table`, :numref:`my_figure`, :numref:`my_block`.
```

with this in ''conf.py'':

```
numfig = True
numfig_format = {'figure': 'My fig %s', 'table': 'My tab %s', 'code-block': 'My code %s'}
```

In the HTML, `:numref:`my_figure` comes out as "My fig 2", although the caption correctly shows "My fig 1". I think this is related with the fact tha the `my_figure` id is being applied to the `<img>` tag, which is inside a `<div>`: the `<div>` gets the number 1, the `<img>` gets the number 2.

In the LaTeX-PDF output all `:numref:` links come out as: "My tab ??, My fig ??, My code ??". Indeed, the "floats" are created with no `\label`.

**Comment by shimizukawa** [comment]
Thanks! I'll fix it soon.

**Comment by shimizukawa** [comment]
>  I think this is related with the fact tha the my_figure id is being applied to the `<img>` tag, which is inside a `<div>`

@Jellby your investigation is correct. Now I fixed it. Please try it with latest dev code if you have a chance. Thanks!
