### ISSUE TITLE
error running sphinx on pypy3 / Python 3.2

### ISSUE THREAD

**Issue by rbtcollins** [sphinx-doc/sphinx#1766]
We run sphinx in our CI for testtools (https://github/testing-cabal/testtools) and with Sphinx 1.3 we started seeing this:

make[1]: Entering directory `/home/travis/build/testing-cabal/testtools/doc'
sphinx-build -b html -d _build/doctrees   . _build/html
Error: Sphinx requires at least Python 2.6 to run.
make[1]: **\* [html] Error 1

e.g. from https://travis-ci.org/testing-cabal/testtools/jobs/53883928

Since both pypy3 and Python3.2 are at least Python 2.6 the error message is at best misleading :).

**Comment by shimizukawa** [comment]
Thanks!
