### ISSUE TITLE
Error building docs on 1.3, Text Assignment in make_xref

### ISSUE THREAD

**Issue by jlaura** [sphinx-doc/sphinx#1772]
Getting a cryptic error try to build documentation after an upgrade to version 1.3.  First appeared on a Travis-CI run and I can reproduce after manually upgrading a local sphinx install to 1.3.  I can build successfully in both environments using version 1.2.3.

Full stack trace as a GIST: https://gist.github.com/jlaura/92dfeefb38af9b433552

Totally stumped on this one, as I am not seeing any linkage in the stack trace back to our code base (https://github.com/jlaura/pysal/tree/coveralls).

Here is a Travis-CI build log as well if that sheds any light: https://travis-ci.org/jlaura/pysal/jobs/54262773

**Comment by shimizukawa** [comment]
confirmed. I'll fix it soon.

**Comment by shimizukawa** [comment]
fixed.
