### ISSUE TITLE
Add separated source directory to search path of docutils.conf

### ISSUE THREAD

**Issue by tk0miya** [sphinx-doc/sphinx#1775]
With sphinx-1.3, `sphinx-build` searches `docutils.conf` on project root directory.
It would be nice if it searches on separated source directory (a.k.a. `source/`)

**Comment by shimizukawa** [comment]
Hum..., your report is already addressed at 0511ced2 (I don't confirm the behavior yet).

**Comment by shimizukawa** [comment]
Confirmed, `sphinx-build` searches `docutils.conf` from source directory instead of project root directory. Please re-check the behavior on your environment. Thanks.

**Comment by tk0miya** [comment]
Sorry, I'd tested on sphinx-1.2.3. It is already fixed on 1.3.
thanks!
