### ISSUE TITLE
source_suffix = ['.rst'] cause unfriendly error prior version.

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1776]
Sphinx-1.3 quickstart generates  `source_suffix = ['.rst']` line in conf.py that cause unfriendly exception as:

```
TypeError: cannot concatenate 'str' and 'list' objects
```

We have 2 options for this problem:
1. set `needs_sphinx = '1.3'` by default.
2. revert `source_suffix` default value as `'.rst'` and add comment line to explain the multiple extensions feature.

Speaking of option 1, the document might works fine on prior versions except `source_suffix` line. Just for it, `needs_sphinx = '1.3'` is too heavy restriction.

Option 2 is better for a while.

**Comment by lehmannro** [comment]
+1 for option 2.  Option 1 is basically the status quo:  Configs _do_ need 1.3 anyways with `source_suffix` set to a list currently, otherwise they will fail.  No need to make that even more explicit.

**Comment by blink1073** [comment]
This change to a list for `source_suffix` is affecting major projects like `matplotlib` and `scikit-image`.  We need a way to support Sphinx <1.3 and Sphinx 1.3.

**Comment by blink1073** [comment]
cc @tacaswell.

**Comment by blink1073** [comment]
Here's the best workaround I have right now:

``` python
import sphinx
if sphinx.__version__.startswith('1.3'):
    source_suffix = ['.txt']
else:
    source_suffix = '.txt'
```

**Comment by shimizukawa** [comment]
@blink1073 Sphinx-1.3 still support `source_suffix = '.txt'` and we will keep supporting it. IMO, conf.py default that generated by sphinx-quickstart (1.3) is not good.

**Comment by blink1073** [comment]
Ah, I stand corrected.  It was our handling of `cfg.source_suffix` after the fact that was the problem.  FWIW, I ended up doing this:

``` python
    cfg = app.builder.config

    if isinstance(cfg.source_suffix, list):
        cfg.source_suffix_str = cfg.source_suffix[0]
    else:
        cfg.source_suffix_str = cfg.source_suffix
```

And then used `cfg.source_suffix_str` wherever we would have used `cfg.source_suffix`.
