### ISSUE TITLE
Sphinx cannot build in Windows user venvs if there are spaces in the path name

### ISSUE THREAD

**Issue by Themanwithoutaplan** [sphinx-doc/sphinx#1778]
Windows user folders default to having spaces in them: `C:\Users\Mickey Mouse\` when running sphinx in a venv in a user folder this can lead to sphinx using an abbreviated, and therefore nonexistent, path and failing to build and exit with  `C:\Users\Mickey` is not a directory. How can this be resolved?

**Comment by shimizukawa** [comment]
pip and virtualenv have that problem:
- https://github.com/pypa/pip/issues/1961 (fixed)
- https://github.com/pypa/virtualenv/issues/637 (still opened)

Additionaly, current pip can't handle non-ASCII path. `sphinx-*.exe` (quickstart, build,..) that is installed into non-ASCII path don't work properly.
- https://github.com/pypa/pip/issues/1923

Unfortunately, there is no way to fix from the sphinx side.
In your case, the white space issue might be fixed then you can try with latest virtualenv and pip.
Thanks.
