### ISSUE TITLE
Setting html_domain_indices to a list raises a new warnings with Sphinx 1.3.0

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#1781]
This issue is reported at: https://groups.google.com/d/msg/sphinx-users/Ycv1u0OgxMs/LaYXMAS3Vt4J

To build the Matplotlib development documentation (here: matplotlib.org/devdocs) we use Travis-CI to automatically build the docs using Sphinx installed from pip. 
In order to catch as manny of our own formatting, broken links etc issues we are treating warnings as errors. This used to work great and have helped us catch a number of 
issues. But with Sphinx 1.3 this causes our docs build to fail since a new warning is raised:

```
WARNING: the config value 'html_domain_indices' has type `list', defaults to `bool.'
```

Sure enough we do set html_domain_indices to a list: 

```
html_domain_indices = ["py-modindex"]
```

However, this is described in the documentation here http://sphinx-doc.org/config.html?highlight=html_domain_indices#confval-html_domain_indices
and should as far as I can see be ok. Is setting html_domain_indices to a list deprecated? If so what is the best alternative? Alternatively is there an easy way 
to suppress this warning. 

Thanks
Jens

**Comment by shimizukawa** [comment]
@lehmannro do you have any idea to fix this issue?

**Comment by lehmannro** [comment]
I quickly skimmed the source and I'm afraid there's no way to infer this automatically.

Three options:
(a) Augment the configuration with explicit type hints.  Could default to the type of the default value and only use this when multiple types are allowed.  (Would probably change `sphinx.config` and `app.add_config_value(…, types=[list, bool])`.)
(b) Add a way to silence the warnings. Something like `ignore_type_warnings = ['html_domain_indices']`.
(c) Don't bother, it's only a warning anyways.

I, honestly, prefer option _(a)_.  This would be the significant change in the configuration system Georg predicted.

**Comment by jenshnielsen** [comment]
Thanks for looking into this. We noticed this in matplotlib because we use warnings as errors which helped fix a rater large number of formatting issues and broken examples. From our perspective it would be a shame to miss out on the option of doing this which would be the result of option c.

**Comment by shimizukawa** [comment]
I prefer option (a) too.
However, IMO, the significant change shouldn't include in minor updated 1.3.1 version.
So, I suggest that:
1. for 1.3.1, type check will be ignores three '*_domain_indices' by hard-coding.
2. for 1.4, we will implement option (a).

@lehmannro @jenshnielsen how do you think this?

**Comment by jenshnielsen** [comment]
Sounds like a good solution to me, Thanks

**Comment by shimizukawa** [comment]
I pushed at 085bcfa5189ea135f91efa8d88b266be12c9b587. Please check it out.

**Comment by shimizukawa** [comment]
I'm going to release 1.3.1 at Mar 17, 9 AM (UTC) :smile:

**Comment by jenshnielsen** [comment]
Thanks. This does indeed resolve the issue. With this change, #1783 and matplotlib/matplotlib#4233 we are back to a warning free and working docs build using the Sphinx stable branch.

**Comment by shimizukawa** [comment]
Thanks for confirmation!

**Comment by shimizukawa** [comment]
Option (a) will be took over at #1786.
