### ISSUE TITLE
release number in latex

### ISSUE THREAD

**Issue by andreacassioli** [sphinx-doc/sphinx#1782]
Hi, 
I was trying to get rid of the release number. I set

```
 release = '2'
```

and 

```
'releasename': ''
```

This remove completely the release from the title page, but on the header of each paage I still got 

```
Title,
```

i.e. there is a redundant comma still there. Ii sound to me a bug.

**Comment by eolo999** [comment]
Hi Andrea,
in conf.py there's a configuration dictionary called _latex_elements_ where you can set 'releasename' to an empty string.

This should solve your issue.

**Comment by birkenfeld** [comment]
We've now updated the docs (thanks EuroPython sprinters!) to explicitly allow you to override 'releasename'.
