### ISSUE TITLE
Useless noise in tests output

### ISSUE THREAD

**Issue by mitya57** [sphinx-doc/sphinx#1785]
When running Sphinx' own tests, it is hard to read the output because the content of some big files is printed there.

In [my log](https://gist.github.com/mitya57/4f6f46d1c169dde2a714/raw/2d855ad96964080bf83a865690865e50a04db001/sphinx_test_log):
- Output of `test_build_gettext.test_all` contains content of some big gettext file;
- Most of `test_intl.test_html_builder` tests contain HTML data in their output;
- Most of `test_intl.test_text_builder` and `test_intl.test_xml_builder` tests contain lots of Sphinx warnings in their output.

**Comment by shimizukawa** [comment]
+100
We need a solution for that. 
(For now, I have no idea to improve outputs... :(

**Comment by birkenfeld** [comment]
The solution is not to run the tests with `-v`.

**Comment by mitya57** [comment]
@birkenfeld I (with my Sphinx Debian maintainer hat on) **do** want to run tests with `-v`. I **don't** want test names to be unreadable.

Maybe it will be possible to add docstrings to the problematic tests? If there is a docstring, then it is printed to the console instead of the test name. `test_env_read_docs` is an example.

**Comment by birkenfeld** [comment]
> I (with my Sphinx Debian maintainer hat on) do want to run tests with -v.

Why? If a test fails you'll get the info you need from the traceback.

> Maybe it will be possible to add docstrings to the problematic tests? If there is a docstring, then it is printed to the console instead of the test name. test_env_read_docs is an example.

A very bad feature IMO: you have no idea which test functions are actually running.

And for parametric tests, such as those Sphinx is using, you will get the same output duplicated for _every_ invocation of the parametric test.

**Comment by lehmannro** [comment]
Can override `__repr__`, will prepare a patch.
