### ISSUE TITLE
graphviz extension raises exception when caption option is present

### ISSUE THREAD

**Issue by davedittrich** [sphinx-doc/sphinx#1788]
I have a reST document that generates the following exception when HTML is built with `sphinx-build` using either Sphinx 1.3.1b3 or 1.3.1:

```
Exception occurred:
  File "/Users/dittrich/.environs/sphinx/lib/python2.7/site-packages/sphinx/writers/html.py", line 353, in depart_caption
    node.parent.traverse(nodes.image)[0], _('Permalink to this image'))
IndexError: list index out of range
```

I have determined that the cause is the `:caption:` that accompanies the .`.graphviz::` directive.

This causes the exception:

```
.. graphviz:: tools.dot
  :caption: Relationships between tools and processes
```

This works (but has no caption, obviously):

```
.. graphviz:: tools.dot
```

This document rendered perfectly fine (with the caption) using Sphinx 1.2.\* and 1.3.1b2.

**Comment by shimizukawa** [comment]
Thanks for reporting. I'll take a look.

**Comment by davedittrich** [comment]
Tested. Can confirm it works. Thanks!

**Comment by shimizukawa** [comment]
You're welcome :smile:

**Comment by xuhdev** [comment]
Is there a way to fix the exception? It does not seem reasonable for me to workaround the bug in the sphinx doc but leave it in the Sphinx code base. I'm actually having this problem in my own doc...

**Comment by xuhdev** [comment]
I see, it seems that this bug is fixed. Thanks!
