### ISSUE TITLE
literalinclude :pyobject: adds extra line

### ISSUE THREAD

**Issue by uralbash** [sphinx-doc/sphinx#1789]
literalinclude `:pyobject:` adds extra line if it comment.

Example:

``` python

import os


class FooClass(object):
    print('Hi')


# Some other things print OS name
print(os.name)
```

``` rst
.. literalinclude:: /foo.py
   :language: python
   :pyobject: FooClass
   :linenos:
```

![_094](https://cloud.githubusercontent.com/assets/619015/6750850/7c5bee18-cf20-11e4-83d8-b0608ce31b66.png)

**Comment by shimizukawa** [comment]
Thanks for your reporting!
I reproduced this issue with 1.2.3 and 1.3.1.  I'll fix it.
