### ISSUE TITLE
literalinclude:: with only line, make an error on latexpdf export

### ISSUE THREAD

**Issue by dfleury2** [sphinx-doc/sphinx#1790]
Hi,
if I do something like : 

```
.. literalinclude:: ./sources/Memory.cpp
    :lines: 46
    :linenos:
    :lineno-start: 46
```

the latexpdf export do not work anymore, I had to put 46-47 to correct this issue.

**Comment by shimizukawa** [comment]
Hum.., I can't reproduce the "do not work" behavior. Please let me know the detail and version set which are you using. Thanks.

**Comment by dfleury2** [comment]
I have made further test, and It's happen when the included line is an empty one.

I am using the version 1.4a0+

**Comment by shimizukawa** [comment]
I got. Thanks.

**Comment by shimizukawa** [comment]
memo: target.tex contain such invalid section when `literalinclude` includes empty file:

```
\begin{Verbatim}[commandchars=\\\{\},numbers=left,firstnumber=3,stepnumber=1]
\end{Verbatim}
```
