### ISSUE TITLE
reference in title causes LaTeX build failure

### ISSUE THREAD

**Issue by benjaminp** [sphinx-doc/sphinx#1798]
I just tried building CPython's docs with Sphinx 1.3.1. Attempting to build PDFs (e.g. running `make dist` in `Doc/`) fails with the error

```
! Undefined control sequence.
<argument> \node@class@name 

l.166120 ...n{xref,std,std-ref}{import} internals}
```

The reST that seems to be causing problems is this

``` rst
:mod:`imp` --- Access the :ref:`import <importsystem>` internals
================================================================
```

This works fine with Sphinx 1.2.3, though, which seems to simply demote the reference to an `\emph{}` tag.

**Comment by eudoxos** [comment]
I am getting the same error as @gutworth with references (`:cite:` or `:ref:`) in `.. figure::` caption.

**Comment by jnothman** [comment]
Having the same issue in scikit-learn. I had no problems compiling with 1.3b2 (although there was another issue that I hoped 1.3.1 would remove). Now trying with 1.3.0.

**Comment by tcpaiva** [comment]
I still face this problem with :term: in a figure caption. I'm using sphinx 1.3.3.

**Comment by tk0miya** [comment]
I think your case is different from this issue.
Could you open new issue?
