### ISSUE TITLE
latex build cannot resolve internal references

### ISSUE THREAD

**Issue by ekeating** [sphinx-doc/sphinx#1805]
I can 'build html' without any problems, but when I 'build latex'
I get quite a few errors like this one:

LaTeX Warning: Hyper reference `user_interface:leakratefile' on page 7 undefine
d on input line 221.

**Comment by tk0miya** [comment]
Sorry for late response.
Could you tell me about the problem in detail?
For example, your reST codes, what is on the line 221, and so on.

**Comment by tk0miya** [comment]
Now I close this issue.
please reopen and tell us details if you still get the problem.

Thanks,
