### ISSUE TITLE
Japanese indexing with libmecab crashes in some 64bit systems

### ISSUE THREAD

**Issue by gashiforce** [sphinx-doc/sphinx#1807]
The Python crashes if libmecab.mecab_new2 returns the pointer allocated to more than 32 bit address, because the return value type is not specified. By the default C functions are assumed to return the C integer value, so the 64 bit pointer is masked to the 32 bit integer. There is a need to be modified to specify the type of C.

```
$ make html
sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v1.3.1
loading translations [ja]... done
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 1 source files that are out of date
updating environment: 0 added, 0 changed, 0 removed
looking for now-outdated files... none found
preparing documents... done
make: *** [html] Segmentation fault: 11
```
#### My environments
- Mac OS X 10.9
- Python 3.4.3 (distributed by Python.org)
- Sphinx 1.3.1
- MeCab 0.996 (installed by Homebrew)
  - The binding is not installed, use directly the libmecab.

`conf.py`

```
html_search_language = 'ja'
html_search_options = {'type': 'mecab'}
```
#### Sample of broken pointer in the Python

Tested in Mac OS X 10.9.

`test.c`: Return the 64 bit pointer.

```
    int *get_pointer(void)
    {
        /* over the max of 32 bit int */
        return (int*)4294967297ULL;
    }
```

Build the library.

```
    $ cc -c -fPIC test.c
    $ cc -shared -o libtest.dylib test.o
```

Test in the Python console.

```
    >>> import ctypes
    >>> libtest = ctypes.CDLL('./libtest.dylib')
    >>> libtest.get_pointer()
    1
    >>> libtest.get_pointer.restype = ctypes.c_void_p
    >>> libtest.get_pointer()
    4294967297
```

**Comment by tk0miya** [comment]
The fix has merged into stable.
Thanks,
