### ISSUE TITLE
LaTeX image/figure with :align: center not scale

### ISSUE THREAD

**Issue by uralbash** [sphinx-doc/sphinx#1813]
See example with `:align: center`:

``` rst
.. figure:: /_static/wsgi/blog/1_0_step.png
   :align: center
   :width: 100px
   :figwidth: 150px
```

![_100](https://cloud.githubusercontent.com/assets/619015/6850012/4978249e-d3f8-11e4-96e4-ec36f9443151.png)

And with `:align: left`^:

``` rst
.. figure:: /_static/wsgi/blog/1_0_step.png
   :align: left
   :width: 100px
   :figwidth: 150px
```

![_101](https://cloud.githubusercontent.com/assets/619015/6850058/9489ea1c-d3f8-11e4-9d32-01da56049f2e.png)

**Comment by andreacassioli** [comment]
Hi,
it works if you use :scale:

**Comment by uralbash** [comment]
@andreacassioli Thanx, I solved this problem by replacing the `px` on `pt`. This also works.

**Comment by andreacassioli** [comment]
Great, then please close the issue.
