### ISSUE TITLE
linkcheck does not raise an exception if warniserror set to true and link is broken

### ISSUE THREAD

**Issue by electrofelix** [sphinx-doc/sphinx#1815]
linkcheck tests 'self.app.quiet' to determine whether to call self.warn() or not, however sphinx uses warniserror in self.warn to determine whether to raise exceptions or not when warnings are triggered.

This means that warniserror can never be triggered by a broken link in the linkchecker builder and makes it impossible to have a script look for a non-zero exit code if any links are broken.

**Comment by electrofelix** [comment]
Hi wondering if the fix for this could be merged? It would be really useful for an OpenStack project https://github.com/openstack-infra/jenkins-job-builder to have our CI watch out for broken links being added to the docs. Right now we cannot catch such issues even though 'broken' appears beside a number of the links over time and we have no way to distinguish between a clean run and one with missing links without grepping the printed output.

The pull request ensures that if warniserror is configured that the linkcheck will return an error when issues occur exactly as documentation suggests it should.

**Comment by shimizukawa** [comment]
@electrofelix please make pull request to review the fix in your repository.

**Comment by shimizukawa** [comment]
OK, I found it as #1816

**Comment by tk0miya** [comment]
Fixed at 2bcf92dfb0837f3be804662770fb4d45b767c284.

Thank you for reporting.
