### ISSUE TITLE
Sphinx crashes - IndexError: pop from empty list

### ISSUE THREAD

**Issue by sc68cal** [sphinx-doc/sphinx#1821]
When using Sphinx v1.1.3 with Python 2.7.6 on OS X 10.10.2 (14C1510) - I get the following stack trace:

https://gist.github.com/sc68cal/ca6e134cf050ab2e3aec

The gist includes the RST file that is causing the issue. It appears to revolve around the paragraph

```
.. Note:: We'll use the :code:`conn` object throughout the tutorial, so ensure you always have one handy
```

https://gist.github.com/sc68cal/ca6e134cf050ab2e3aec#using-code

**Comment by sc68cal** [comment]
Gistfile 2 - https://gist.github.com/sc68cal/ca6e134cf050ab2e3aec#file-gistfile2-txt has a pdb session

**Comment by sc68cal** [comment]
This appears to be an issue over in docutils

**Comment by shimizukawa** [comment]
#1214 is same issue and it is fixed at Sphinx-1.2. Please try Sphinx-1.2 or later version.

**Comment by sc68cal** [comment]
@shimizukawa Thanks for the info. Unfortunately our tooling has Sphinx pinned at v.1.1.3 due to other dependencies and a switch to Sphinx-1.2 would require code changes to PBR.

**Comment by shimizukawa** [comment]
#998 is also related. 'docutils-0.10 api change' is the cause I think.
If you need to use pinned Sphinx-1.1.3 version, docutils-0.9.1 might avoid this trouble.

**Comment by sc68cal** [comment]
Pinning docutils to the suggested version fixes

**Comment by shimizukawa** [comment]
Thanks!
