### ISSUE TITLE
sphinx should take care of the difference between Python2 and Python3

### ISSUE THREAD

**Issue by BerlinNurse** [sphinx-doc/sphinx#1824]
I had variouse problems because of the difference between Python2 and Python3.
This means
- there is a Sphinx version for Python2 and 3.
- and Sphinx read itself Python2 and/or Python3 code

The point is that the Py2-Sphinx is not able to handle Python3 code of course.
But it is really easy to find out if the given code is 2 or 3.
Py2-Sphinx should just check for that and give an error message or minimal a warning about it.

e.g.
_You are running Spinx v1.3.1 with Python2 but give Python3 code to process. This can cause errors._

I am not sure if a Py3-Sphinx should be able to handle Python2 code. But I think this would cause errors, too. Because Py3-Sphinx would (per default) look in the Python3-path for modules and not in the Python2.

**Comment by shimizukawa** [comment]
I think you mentioned about autodoc.

IMO, such detection is difficult. However, if that is possible we are waiting for your contribution! 
Now I close this issue, but please make Pull Request at any time.
