### ISSUE TITLE
Go to Page Directly for Exact Search Match?

### ISSUE THREAD

**Issue by TaylorSMarks** [sphinx-doc/sphinx#1827]
(Note: I originally proposed this for the Python Website, but had the issue closed because evidently the Python website's documentation is done with Sphinx. See the original issue there:
https://github.com/python/pythondotorg/issues/724 )

Example, when I search for "re", it would be nice if, rather than taking me to the search results as it currently does, if it would take me directly to the page for re, https://docs.python.org/2/library/re.html

Maybe it could insert a notice at the top of the page along the lines of "Automatically selected since it was by far the best match. See other results for re."

It would just be nice to use this in conjunction with DuckDuckGo, if I could do:

!py re -> in the documentation for re

instead of

!py re -> wait for results to load... click on link -> in the documentaiton for re

Is the website itself an open source project where if I want something, I should implement it myself, or is there some kind of process? I figured I'd open this issue to start...

**Comment by shimizukawa** [comment]
Please try it. There is no process to start hacking ;) ...However we probably will not have the feature into Sphinx itself.
So to have that feature on docs.python.org you will need to implement the feature and suggest it to the Python documentation team.
