### ISSUE TITLE
Napoleon: Return type containing colons is not handled properly for NumPy-style docstrings

### ISSUE THREAD

**Issue by RobRuana** [sphinx-doc/sphinx#1831]
Originally reported on the [sphinxcontrib repo](https://bitbucket.org/birkenfeld/sphinx-contrib/issue/82/napoleon-return-type-containing-colons-is)

Using a return type containing colons isn't being handled correctly.

This is often the case when using interpreted text roles to specify, for instance, a custom return type.

More specifically, the colon is interpreted as a field separator, causing Sphinx to fail to parse the return type as interpreted text.

Here's an example:

```
#!python
def my_func(my_args):
    '''
    ...
    Returns
    -------
    :py:class:`~my_mod.my_class`
        an instance of :py:class:`~my_mod.my_class`
```

The "Returns" section would render as

**Returns:** py:class:_~my_mod.my_class_

instead of the expected

**Returns:** [my_class](#)

The colon is relevant for sections like "Args" where it separates the argument name from the argument's type, but in the case of the "Returns" section this should be handled differently, since only the return type is placed on that line.

**Comment by vkruoso** [comment]
A similar problems seems to be happening with Google Style docstrings too. Consider the following examples:

``` python
@property
def example(self):
    """Example property.

    Returns:
        :py:class:`~.module.submodule.SomeClass`: an example instance
        if available, None if not available.
    """
    pass
```

I'm running Sphinx 1.3b2. Am I doing something wrong?

**Comment by timseries** [comment]
I had the same problem  (with Google style return types). Works on 1.3b2, breaks on 1.3b3 and up.

**Comment by timseries** [comment]
I had the same problem (with Google style return types). Works on 1.3b2, breaks on 1.3b3 and up.

**Comment by RobRuana** [comment]
Looks like this was fixed for NumPy style, but not Google style
