### ISSUE TITLE
Sphinx 1.3.1 produce bare html without any nice visual style

### ISSUE THREAD

**Issue by bialix** [sphinx-doc/sphinx#1835]
I have documentation to my small intelhex project in sphinx format.
I want to build new version of documentation to new release. 
I've pip-installed latest Sphinx, and got 1.3.1 + 11 more packages (on Python 3.3).
But after running `make html` in the docs directory I've got just bare html without any nice visual style.
My last attempt to build doc was in 2013 year though, I admit I may miss something important, but I'm not sure why newer Sphinx don't want to produce as nice as result as older one.
Here is example what I want: http://pythonhosted.org//IntelHex/ - as I ca see from footer note it was built with Sphinx 1.0.7.
Here is my docs tree: https://github.com/bialix/intelhex/tree/master/docs/manual
I've just installed Sphinx 1.0.7 on Python 2.7 and it still produces normal result, as on the link above.
I think I can stick with 1.0.7 if there is no solution.

**Comment by shimizukawa** [comment]
I guess it is "alabaster" theme instead of "bare html".
Since Sphinx-1.3, when user doesn't specify `html_theme`, "alabaster" theme is used as a default theme.

https://github.com/bialix/intelhex/blob/master/docs/manual/conf.py doesn't specify `html_theme`.
If you want to keep previous theme (like 1.0.7), you can specify it in conf.py as:

```
html_theme = 'classic'
```

Please try it.

**Comment by bialix** [comment]
I think I found the problem. My conf.py for documentation was created very long time ago, I don't remember exact sphinx version, but I'm sure it was pre 1.0. I see option in the conf.py

 The style sheet to use for HTML and HTML Help pages. A file of that name
 must exist either in Sphinx' static/ path, or in one of the custom paths
 given in html_static_path.
html_style = 'default.css'

In the generated html this css file is still referenced, but .build/html/_static does not have this css, only alabaster.css. If I copy alabaster.css to default.css the generated html becomes much better.

I've therefore deleted this (outdated option I believe) and replaced with what you suggested.
Now it looks OK. Thank you for the help.

**Comment by evieluvsrainbows** [comment]
@bialix Uh, just a suggestion, but why don't you upgrade to Python 3.4? It's a lot better than 3.3, and fixes a lot of bugs & things.

**Comment by bialix** [comment]
@KamranMackey: well, 3.3 is just work and is currently used in my working project.
But, just FYI
C:\Python>dir /b
2.3
2.4
2.5
2.6-32
2.6-64
2.7-32
2.7-64
3.2-32
3.2-64
3.3-32
3.3-64
3.4-32
3.4-64
3.5-32
3.5-64

**Comment by evieluvsrainbows** [comment]
Why the heck do you have so many Python installations? You don't need THAT
many.

**Comment by rkuska** [comment]
According to sphinx docs:

> Changed in version 1.3: The ‘default’ theme has been renamed to ‘classic’. ‘default’ is still available,
> however it will emit notice a recommendation that using new ‘alabaster’ theme.  

But it produces warning when default is used and doesn't create the default.css (I use import default.css in my theme css file). Is this expected?

**Comment by shimizukawa** [comment]
@rkuska Sphinx-1.3.2 fixes your problem.
https://github.com/sphinx-doc/sphinx/blob/1.3.3/CHANGES#L25
Please try latest (1.3.3) version.

And now I close this issue because original issue is already resolved.
