### ISSUE TITLE
Napoleon causes error when docstring contains e.g. "Example::"

### ISSUE THREAD

**Issue by lsaffre** [sphinx-doc/sphinx#1840]
After activating Napoleon, docstrings like the following failed with "ERROR: Unexpected indentation.":

```
    """Return a list of names of fields that should be disabled (not
    editable) for this record.

    Example::

      def disabled_fields(self,request):
          if self.user == request.user: return []
          df = ['field1']
          if self.foo:
            df.append('field2')
          return df

    """
```

Workaround was to replace "Example::" by e.g. "Usage example::" so that Napoleon no longer tries to convert it. Not very severe, but the double colon should IMHO indicate that this particular docstring was not meant for Napoleon.

**Comment by RobRuana** [comment]
Note, because this is a bug I've committed the fix to both master and stable.
