### ISSUE TITLE
Feature Request: copy parameter descriptions

### ISSUE THREAD

**Issue by breedlun** [sphinx-doc/sphinx#1841]
It would be very nice to be able to do copy parameter descriptions, as discussed in [this stackoverflow post](http://stackoverflow.com/questions/8320909/repeated-parameters-with-python-sphinx).  

Here is the original post:

Suppose I have a function `foo(a,b)` and `bar(a,c)`, such that the parameter `a` has the same description for both functions.

Is it possible to document a just once (in `foo`, say) and then copy that description in `bar` to avoid having to update both pieces of text if something in a's description changes?

For example, say I document `foo`:

```
def foo(a,b,c):
    """
    a function description.

    :param a: a string, your name
    :param b: something else
    """
```

What would be great is something in `bar`'s documentation like:

```
def bar(a,c)
    """
    another function description.

    :inheritParams foo a: # somehow inherits a's description from foo
    :param c: description for parameter c.
    """
```

even better, if it were `foo(a,b,d)` and `bar(a,c,d)` and I could do (in `bar`'s documentation):

```
:inheritParams foo:  # grabs a and d documentation from function foo
:param c: description for parameter c
```

to have any descriptions of parameters in common with `foo` and `bar` taken from `foo`. That is, it would copy the definition for a and d from `foo`, and I'd have to document any leftovers (c).

**Comment by lehmannro** [comment]
While I'm not exactly opposed to the feature request (patches welcome!) I'm not sure if it's really useful.

I assume one of the functions is the reference function and the others are just convenience wrappers or some such.  If the API of the reference function changes (adding/removing parameters) and you write functions the way you do, you will have to _touch_ the convenience function _anyways._  A better way might be using `*args, **kwargs` and passing through all parameters verbatim.  Then you can have a verse like "all other positional and keyword arguments are passed through to foo."

If all functions handle their parameters the same way, maybe you should introduce a common helper function/interface.  If you determine it's really necessary to have functions with identical descriptions I think substitutions are the way to go.

**Comment by breedlun** [comment]
Thanks for the thoughtful reply.  

Yes, I am passing `**kwargs` through a convenience function to one or more reference functions.  I considered adding a verse like "See foo for additional keyword arguments", but when you have more than one reference function this gets annoying for the user.  It's much more convenient for the user if all the keyword arguments to a function are listed directly under the function heading, rather than following links to all the reference functions.

I will look into substitutions.   If they will do the trick for me, I will report back here and close the issue.

**Comment by breedlun** [comment]
Hmmm.  It looks like substitutions would work for me, but I can only get them to work with normal sphinx.  I am using numpydoc with my project, and it seems to just ignore substitutions.  Is there a special trick to this, or should I submit an issue on numpydoc's github page?

**Comment by tk0miya** [comment]
I guess nobody knows how numpydoc works.

Anyway, I also feel substitution is good for your case. So -0 for your proposal.

**Comment by tk0miya** [comment]
I'm closing this now. Thank you for your proposal :-)
