### ISSUE TITLE
wrong section numbering using ifconfig

### ISSUE THREAD

**Issue by andreacassioli** [sphinx-doc/sphinx#1842]
I would like to include some section conditionally. I did as follow

```
test
========

.. ifconfig:: True

   section 1
   -------------

   ssection 2
   ^^^^^^^^^^^^^^^
```

But the output is 
1. test
2. section 1
3. ssection 2

with the right layout but not the right numbering.

**Comment by shimizukawa** [comment]
You can't use `only` and `ifconfig` to make conditional sections.
It's a limitation of both directives.
See also #1488 for details.
