### ISSUE TITLE
Sphinx seems to have stopped highlighting inline code

### ISSUE THREAD

**Issue by debugger22** [sphinx-doc/sphinx#1848]
Sphinx seems to have stopped highlighting inline code with a background color. See following for instance.

SymPy docs built with Sphinx 1.1.3: http://docs.sympy.org/latest/gotchas.html#single-equals-sign
SymPy docs built with Sphinx 1.3.1: http://sympy-docs.s3-website-us-west-2.amazonaws.com/open-sans/gotchas.html#single-equals-sign

Or am I doing something wrong?

**Comment by birkenfeld** [comment]
In 1.3, we've switched from `<tt>` to `<code>` tags. SymPy will have to adapt its CSS.

**Comment by debugger22** [comment]
Thanks Georg!
