### ISSUE TITLE
Napoleon: **kwargs argument

### ISSUE THREAD

**Issue by vkruoso** [sphinx-doc/sphinx#1849]
I'm having problems rendering the docs for a docstring like the one below.

``` python
def bind(self, **kvargs):
    """Allows to create attributes binded to this device.

    Some other paragraph.

    Code sample for usage::

      dev.bind(loopback=Loopback)
      dev.loopback.configure()

    Arguments:
      **kwargs: name/class pairs that will create resource-managers
        bound as instance attributes to this instance. See code
        example above.
    """
    pass
```

If you render this as is, the final result is a code snippet, with the sample code and everything below it inside the snippet - with exception of the "Arguments" and the "kwargs" lines.

If you remove the "**" from the kwargs argument, the argument is rendered correctly after the code sample. I'm not sure it this happens only when there is a code block before the Arguments section, or if it is only related to the asterisks.

**Comment by RobRuana** [comment]
Looks like this was either fixed earlier or fixed along with #1831. In any case, I've added your example as a unit test in 42f2b305791507e6bfe9507832daefc5071969cd.
