### ISSUE TITLE
LaTeX: no pagerefs for citations

### ISSUE THREAD

**Issue by Jellby** [sphinx-doc/sphinx#1857]
With latex_show_pagerefs=True, the LaTeX writer adds page references to internal links, except to glossary links. I think it shouldn't add them to citations.

**Comment by tk0miya** [comment]
+1

In my short investigation:
LaTeX writer puts page reference to every reference node with no distinction citation or not.
To do that, we have to distinguish citations from reference nodes.
But there is not differences now.
So we have to mark what type is the reference (a.k.a refdomain and reftype).

**Comment by tk0miya** [comment]
It might be resolved by #4904. I'll confirm that later.

**Comment by tk0miya** [comment]
I confirmed this is already resolved in master branch.
I'm closing this now.
