### ISSUE TITLE
Man page using :samp: with braces - font doesn't reset

### ISSUE THREAD

**Issue by ghost** [sphinx-doc/sphinx#1860]
There are issues with the man page rendering when using :samp:`{blah}` 
The font change doesn't reset after the closure of the samp but runs onto subsequent lines until certain 'resetting' elements are encountered, such as a bullet, heading and probably others I haven't tested for.
:samp:`like this` is ok. HTML and Latex (pdf) formats are also unaffected by this issue.

MWE included with screen shot.
###### 

Manpage Test
###### 

:samp:`Sample Text (with 'samp') {and this text in braces}`

Text that should be plain.
- A bullet that should be plain.

And back to normal.

:samp:`{this text in braces} but not this`

More text that should be plain.
- A bullet that should be plain.

And back to normal.

:samp:`Now a 'samp' with no braces`

All ok on this line. 

![screen shot 2015-04-22 at 11 26 43](https://cloud.githubusercontent.com/assets/12054648/7270284/c9749204-e8e3-11e4-9ed7-c87383e045ee.png)

**Comment by tk0miya** [comment]
Fixed at c6c9c5c
Thank you for reporting

**Comment by marxin** [comment]
Apparently, I face the same problem with the latest release `4.0.2`:

index.rst:
```
Welcome to demo documentation!
==============================

This is :samp:`fine`.

Show :samp:`{problematic}` underscore starting here.

And this is also bad.
```

conf.py:
```
project = 'Demo project'
copyright = '2001-2021 XYZ'
authors = 'Me'

man_pages = [
    ('index', 'demo', 'GNU project C
```
and template Makefile is needed:

```
$ make man
man _build/man/demo.1
$ grep problematic _build/man/demo.1
Show \fB\fIproblematic\fP\fP underscore starting here.
```

![Screenshot from 2021-06-15 22-00-24](https://user-images.githubusercontent.com/2658545/122115842-2aac9f80-ce25-11eb-867c-b479b076fe92.png)

**Comment by marxin** [comment]
Apparently, it's problematic only when a `:samp:` directive begins with `{`. I've got a patch for it.
