### ISSUE TITLE
Allow option in `setup.cfg` to run `sphinx-apidoc` first

### ISSUE THREAD

**Issue by jakirkham** [sphinx-doc/sphinx#1861]
If there is a way to do this and I missed it, I would really appreciate a pointer in the right direction. If not, I think it would be really nice to have a way to specify in `setup.cfg` or otherwise an optional run of `sphinx-apidoc` with arguments before running `sphinx-build`.

**Comment by solidsnack** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by DanLipsitt** [comment]
Although it isn't built in, [PBR](https://docs.openstack.org/pbr/latest/) can help with this.

**Comment by peterjc** [comment]
Is this a duplicate of #1135?

**Comment by jakirkham** [comment]
Not sure. Am unclear on how the reporter there wants to achieve the intended outcome. If they are wanting to add a flag on the command line, that does not really work for my use case.

**Comment by stephenfin** [comment]
This is a duplicate of #1135 and should be closed as a dupe. @tk0miya, @shimizukawa: can one of you do this? Do note, however, that #1135 should be renamed with this name, which is more generic (we don't necessarily want to do it in setuptools, as #4101 shows (Alternatively, we could close #1135?)

**Comment by matthiasha** [comment]
Workaround: Insert the following code in conf.py (adjust apidoc parameters to your needs):
```python
import sphinx.apidoc

def setup(app):
    sphinx.apidoc.main(['-f', '-T', '-e', '-o', 'doc/autogen', 'src'])
```

**Comment by paulmelnikow** [comment]
This is also possible using the [sphinxcontrib.apidoc extension](https://github.com/sphinx-contrib/apidoc) as mentioned in https://github.com/rtfd/readthedocs.org/issues/1139#issuecomment-398543990.

**Comment by partofthething** [comment]
There is now an extension that does this: https://github.com/sphinx-contrib/apidoc. Probably safe to close this ticket now.

**Comment by stephenfin** [comment]
Agreed

**Comment by dboeckenhoff** [comment]
> This is a duplicate of #1135 and should be closed as a dupe. @tk0miya, @shimizukawa: can one of you do this? Do note, however, that #1135 should be renamed with this name, which is more generic (we don't necessarily want to do it in setuptools, as #4101 shows (Alternatively, we could close #1135?)

Inifinte regression here: 1135 says duplicate of 1861

**Comment by dboeckenhoff** [comment]
> Workaround: Insert the following code in conf.py (adjust apidoc parameters to your needs):
> 
> ```python
> import sphinx.apidoc
> 
> def setup(app):
>     sphinx.apidoc.main(['-f', '-T', '-e', '-o', 'doc/autogen', 'src'])
> ```

The pyhton module sphinx has no apidoc submodule in latest versions. On the basis of this comment I directly use subprocess:
```python
import subprocess
def setup(app):
    subprocess.call(['sphinx-apidoc', '-o', 'docs/source/', <your module name>])
```
