### ISSUE TITLE
Add a texinputs/make.bat

### ISSUE THREAD

**Issue by petsuter** [sphinx-doc/sphinx#1867]
`make.bat latexpdf` only works if you have a `make` installed:

```
>make.bat latexpdf
Running Sphinx v1.3.1
making output directory...
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [latex]: all documents
updating environment: 1 added, 0 changed, 0 removed
reading sources... [100%] index
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
processing test.tex... index
resolving references...
writing... done
copying TeX support files...
done
build succeeded.
'make' is not recognized as an internal or external command,
operable program or batch file.
```

There should be a `make.bat` for tex on Windows that does not need `make`.

(Previously discussed in #1520)

**Comment by sdybvik** [comment]
I'm new to Sphinx (and Python). How do you install make? I believe that would be a workaround for this issue.

**Comment by shimizukawa** [comment]
Suggestion as workaround: http://sourceforge.net/projects/gnuwin32/files/make/3.81/ (or some other make.exe like MinGW, Cygwin, gnupack)

**Comment by navenduagarwal** [comment]
install miktex and then generate pdf by running cmd pdflatex ___.tx file.

**Comment by petsuter** [comment]
My workaround has been to edit the `make.bat` and replace `make all-pdf` by `pdflatex MySphinxProjectName.tex`. Would be nice if that was already in the generated `make.bat`. Putting a call to `make.exe` in `make.bat` just makes no sense to me. Even if it's theoretically available from gnuwin32, MinGW, Cygwin, gnupack, ... why would anyone use `make.bat` if you need a `make.exe`  to use it anyway?

(I'm not sure if `pdflatex` is actually the right command. `latexmk.exe` would probably be better, but then Perl is required. 👎 A Python script replacement would be great. Maybe bundle https://github.com/aclements/latexrun?)

(Also, its unfortunate that this subcommand is named `latexpdf` but the executable is named `pdflatex`. I get these mixed up all every time now.)

**Comment by tk0miya** [comment]
In https://github.com/sphinx-doc/sphinx/pull/5267, make.bat was added to Sphinx. So this was already resolved. Closing.
