### ISSUE TITLE
Text of code examples in Django documentation not formatting properly in PDF doc

### ISSUE THREAD

**Issue by Blueliner** [sphinx-doc/sphinx#1868]
When a PDF file is generated the code examples in the documentation for Django 1.7 and 1.8 isn't properly formatting making documentation unreadable. Trying to determine if this is being caused by Sphinx. Here is a summary of the problem including examples of a page from a PDF generated using Sphinx 1.2.0 where the code examples look fine along with a more recent PDF generated using Sphinx 1.2.3 where the code examples aren't being formatted properly

https://code.djangoproject.com/ticket/23751#no2

Any feedback as to whether anyone else is having a similar problem and how best to resolve this would be appreciated.

Randy

**Comment by birkenfeld** [comment]
There is some LaTeX handler code in the `djangodocs.py` extension. It might need to be adapted for Sphinx 1.3.

**Comment by tk0miya** [comment]
Is this fixed in recent release?
The ticket you linked is closed now, and current document seems good.

**Comment by tk0miya** [comment]
Now I close this.
Please reopen if you still have problem.
