### ISSUE TITLE
Problem while generating documentation

### ISSUE THREAD

**Issue by GitHK** [sphinx-doc/sphinx#1870]
Exception occurred:
    File "...../venv/lib/python2.7/site-packages/sphinxcontrib/tgjsonautodoc/**init**.py", line 138, in _generate_doc
    for field, validator in info['validation'].validators.items():
AttributeError: 'Validators' object has no attribute 'items'

From what I could tell it seems that info['validation'].validators is not a list.

Any ideas why this could occur?
Thanks

**Comment by shimizukawa** [comment]
It seems the error is caused by interface mismatch with sphinxcontrib.jsoncall  and TruboGears.
Please contact to sphinxcontrib.jsoncall author: https://github.com/amol-/sphinxcontrib.jsoncall
