### ISSUE TITLE
LaTeX Table build failure due to wrong indentation in latex.py

### ISSUE THREAD

**Issue by lnevay** [sphinx-doc/sphinx#1871]
When building latex output of documentation with a table with referenced objects (images) in the table, I get a build error (make latexpdf).

Exception occurred:
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinx/writers/latex.py", line 885, in depart_row
    if linestart <= col:
UnboundLocalError: local variable 'col' referenced before assignment
The full traceback has been saved in /var/folders/wc/j61j24zj1b1d_49lpm69jrnh0000gn/T/sphinx-err-VJiMvA.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at https://github.com/sphinx-doc/sphinx/issues. Thanks!
make: **\* [latexpdf] Error 1

Looking at this latex.py file, the error is indeed correct - the variable 'col' doesn't exist as it's not indented far enough.  Super simple fix.  I edited mine manually and it does indeed work and build correctly.

Lines 885 to 888 should be indented one tab (4 spaces) more.

![screen shot 2015-05-01 at 18 56 33](https://cloud.githubusercontent.com/assets/9283103/7470259/3cf42328-f313-11e4-93ee-93455341302b.png)

**Comment by kdambekalns** [comment]
I just tripped over the same error and can confirm the fix given above.
