### ISSUE TITLE
Error with 'make latexpdf'

### ISSUE THREAD

**Issue by StefanLiebig** [sphinx-doc/sphinx#1877]
Running 'make latexpdf' creates the following output:

> Running Sphinx v1.3.1
> loading translations [de]... done
> loading pickled environment... done
> building [mo]: targets for 0 po files that are out of date
> building [latex]: all documents
> updating environment: 0 added, 0 changed, 0 removed
> looking for now-outdated files... none found
> processing smartup.tex... index scale
> resolving references...
> writing... done
> copying TeX support files...
> done
> build succeeded.
> Error on line 19: ')' is not a valid filename char
> 
> Build finished; the PDF files are in _build/latex.

Although it says that the pdf files are in _build/latex, there are no pdf files.

make created with sphinx-quickstart

(Windows 8.1 Pro, Python 2.7.9, Sphinx 1.3.1)

**Comment by shimizukawa** [comment]
I'm not sure what happen on your environment.

> Error on line 19: ')' is not a valid filename char

Googling `make "is not a valid filename char"` indicates "The make program that emits such message is not support Gnu Make syntax."
To resolve this, you can use another make program that supports Gnu Make syntax.

For your information, I'm using make.exe that is contained in msys-1.0.

```
> make.exe --version
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i686-pc-msys
```

**Comment by shimizukawa** [comment]
I'm closing this ticket, however please feel free to reopen at any time if you catch a problem. Thanks!
