### ISSUE TITLE
autosummary doesn't recurse.  function.rst is mentioned but absent

### ISSUE THREAD

**Issue by yarikoptic** [sphinx-doc/sphinx#1879]
Hi Guys,

Thanks for the sphinx!!!  In our recent website update for pymvpa.org we ran into the problem of lacking recursive autodoc'ing of functions/classes contained within the modules, see e.g.
http://dev.pymvpa.org/generated/mvpa2.base.constraints.html which is generated since we have autosummary_generate=True and pointed `:autosummary:` to it.  So I looked inside autosummary and got a bit confused on how was it supposed to work really?  e.g.
- http://sphinx-doc.org/ext/autosummary.html  is mentioning providing/using function.rst template but I can't locate it either in distribution nor in current git
- shipped `module.rst` template only uses `:rubric:` to designate what follows -- functions or classes or ...,  doesn't use autofunction etc -- it is all ":autosummary:", and as a result autosummary/generate.py:find_autosummary_in_lines doesn't provide any toctree nor designation for template for any of the found elements, and nothing gets generated.

It could be my naive misunderstanding on how autosummary should operate, but at least doc should be adjusted for missing function.rst ;)

**Comment by jfowkes** [comment]
Yeah I would really like to edit the `function.rst` template as per the autosummary documentation (so that I can have shorter function page titles) but it doesn't seem to exist anywhere!

**Comment by tk0miya** [comment]
Finally, I added `:recursive:` option to autosummary directive (see #7527). I think half of this issue is fixed now.

On the other hand, I don't understand what is another problem. Indeed, Sphinx does not have `function.rst`. But it's not a problem. You can change the template for functions by putting `function.rst` in your template directory.

If you need an example of the file, please copy `base.rst` to your local and modify it. Sphinx uses it as a fallback if `function.rst` not found.

**Comment by jfowkes** [comment]
That’s great, many thanks! Ah I see, thank you: it wasn’t clear to me from the autosummary documentation that you can change the template for functions by writing your own `function.rst` based on `base.rst`which Sphinx uses as a fallback.

**Comment by tk0miya** [comment]
Please make a pull request for our document if you have good idea to describe the feature!

I'm closing this now. Please let me know if you still have a problem.
Thanks!
