### ISSUE TITLE
autodoc skips subclasses of mocked modules

### ISSUE THREAD

**Issue by theiviaxx** [sphinx-doc/sphinx#1880]
foo.py

```
import bar

class MyClass(bar):
    """This is myclass"""
```

foo.rst

```
foo
===

.. automodule:: foo
    :members:
```

conf.py

```
autodoc_mock_imports = ['bar']
```

Running `sphinx-build html` on this will yield an empty doc for foo.html.  If MyClass is subclassed from an importable module, it documents as expected.

**Comment by Psirus** [comment]
Any progress on this?

**Comment by djhoese** [comment]
I know this is really old, but I'm investigating sphinx's mocking behavior and I'm curious about your example. It looks like you are subclassing an instance of a module? How is that possible?

**Comment by theiviaxx** [comment]
@davidh-ssec Oh man, this was a long time ago and i dont have the code anymore.  Basically it revolved around pyside and how classes were created.  Here is a some code off the cuff:

    from PySide import QtGui, QtCore
    FORM, BASE = loadUIFile('path/to/file.ui')

    class MyWindow(FORM, BASE):
        def __init__(self, parent=None):
            super(MyWindow, self).__init__(parent)
            self.setupUi(self)

And `MyWindow` would be skipped if QtGui and QtCore were mocked.  Again, this was a long time ago and i dont have the code in front of me, but that's what I can remember.

**Comment by djhoese** [comment]
Looks like #2174 is a duplicate of this and is working in the newest versions of sphinx. And thanks for replying. Your example looked like you were doing `import my_module` followed by `class MyWindow(my_module)` which doesn't make sense.

**Comment by tk0miya** [comment]
@davidh-ssec Thank you for your help.
As you commented, it seems this is a bit strange. So I close this issue now.

Please feel free to reopen if somebody get same trouble.
Thanks,

**Comment by ederag** [comment]
Unfortunately, this is not #2174.
Actually, the docstrings of classes inheriting from other classes in mocked modules are ignored.
A real case is described in https://stackoverflow.com/q/50203452/3565696.
Here is a minimal working example, all files in the same directory.
Project module `foo.y`:
```
import bar

class FooClass(bar.BarClass):
    """This is myclass"""
    pass
```
`conf.py`:
```
import sys
import os

# The FooClass docstring shows up only if this line is commented out
autodoc_mock_imports = ['bar']

sys.path.insert(0, os.path.abspath('.'))

extensions = [
    'sphinx.ext.autodoc',
]
```
`contents.rst`:
```
foo
===

.. automodule:: foo
    :members:
    :noindex:
```
And finally, the`bar.py` "external" module (only used when the autodoc_mock_imports is commented out):
```
class BarClass():
	pass
```

The command used to build:
`sphinx-build  -b html . _build/html`

To see the file where the dosctring should be visible:
`firefox _build/html/foo.html`

tested with `sphinx-build 1.7.4`

**Comment by djhoese** [comment]
@ederag It might be best to make a new issue for this to get fresh eyes on it and you can tag this issue for consistency.

**Comment by ederag** [comment]
@djhoese done, in #4956
