### ISSUE TITLE
using "automethod" in autodoc to hide decorated method signature outputs two signatures

### ISSUE THREAD

**Issue by viktorasm** [sphinx-doc/sphinx#1881]
My .rst file looks like this:

``` rst
.. autoclass:: ngSkinTools.importExport.LayerData
    :members:

    .. automethod:: saveTo(mesh)
```

releavant python sources:

``` python
    @Utils.undoable        
    def saveTo(self, mesh):
        '''
        saves data to actual skin cluster
        '''
```

``` python
    def undoable(function):
        '''
        function decorator, makes function contents undoable in one go
        '''
        @wraps(function)
        def result(*args,**kargs):
```

When documentation is generated, I get two entries generated for the same method, one with `automethod` signature which is `saveTo(mesh)` and one with `*args, **kwargs`:

![double entry](https://cloud.githubusercontent.com/assets/2631366/7535480/507f9170-f58e-11e4-80fe-a619f5a3b899.png)

I would like to keep the `:members:` directive like it is, without explicitly skipping `saveTo` in it - I want to include all documented members as they're being added/removed.

Sphinx v1.3.1

**Comment by shimizukawa** [comment]
I think method signature overriding  by `automethod` directive is reasonable proposal.

**Comment by shimizukawa** [comment]
BTW, you can override the wrapped method signature in other ways.

A. use Python3. functools.wraps of python3 is keep original function object as `wrapper.__wrapped__`. Sphinx follows this and get original signature.

or

B. write signature at the first line of docstrings as:

```
@Utils.undoable        
def saveTo(self, mesh):
    ''
    saveTo(self, mesh)

    saves data to actual skin cluster
    '''
```

**Comment by viktorasm** [comment]
Second tip worked wonders, thanks. Would be nice if some kind of follow-through logic could be possible with Python 2 as well, `.__wrapped__` can be manually added in decorators.

**Comment by brechtm** [comment]
I'm having the same problem but with `.. autoattribute::` (to set `:annotation:`).

I'm using `:exclude-members:` for now to exclude the attribute.

**Comment by tk0miya** [comment]
I'm closing this now because it seems already resolved via workaround. Additionally, we have `:exclude-members:` option to exclude arbitrary members manually.

From the perspective of implementation, it is difficult to skip `saveTo` automatically when the docstring of `autoclass` contains the `automethod` for it. So it would be better to use `:exclude-members:` to do that.
