### ISSUE TITLE
plug-in html themes cannot inherit another plug-in theme

### ISSUE THREAD

**Issue by Suzumizaki** [sphinx-doc/sphinx#1884]
When some plug-in theme try to inherit another plug-in theme, the Sphinx cannot find it.
This issue is similar to #1794, but not limited 'alabaster' theme.

I'll post the patch later.

**Comment by shimizukawa** [comment]
I think the issue you mentioned is also fixed on stable branch (1.3.1+).
If I'm wrong, please let me know a example case. Thanks!

**Comment by Suzumizaki** [comment]
Thank you for your comment. I tried with the latest stable brunch just now. but it seems failed.
Again, I will make the pull request and post the theme and extension as I told on the twitter.

**Comment by Suzumizaki** [comment]
I posted both the patch(#1885) and the [package](https://pypi.python.org/pypi/sphinx_html5_basic_theme). Please try them to check!

How to reproduce this issue:
1) pip install sphinx_html5_basic_theme
2) cd python_path/lib/site-packages/sphinx_html5_basic_theme/doc
3) make html
4) Stop with the error message below:
Theme error:
no theme named 'html5_basic' found, inherited by 'html5_sphinxdoc'

I tested with Windows 8.1 Pro 64bit, 32bit Python 2.7.9, 64bit Python 3.4.3.
