### ISSUE TITLE
Enhancement: Bash code block highlighting logic improvement

### ISSUE THREAD

**Issue by tojon** [sphinx-doc/sphinx#1893]
Sorry if this is a duplicate, I searched all open and closed issues.

It would be nice if bash code block highlighting had some extra built in logic to detect:
- an increased number of unix commands eg. `systemctl`
- an argument to unix command being interpreted as an arg (plain text) rather than a command eg. `enable`

I've provided an example in a closed PR on one of our projects.
https://github.com/mozilla/treeherder/pull/539

![before](https://cloud.githubusercontent.com/assets/3660661/7712898/1d4e7be2-fe42-11e4-85c2-4403528d1b3d.jpg)

If for some reason this is pilot error and there is a better way to correct the appearance rather than just making the code block 'none', feel free to close this issue and let me know :)

Thank you for your time and consideration.

**Comment by xmo-odoo** [comment]
Sphinx does not do syntax highlighting itself (though it does perform some of the munging), it delegates that to [pygments](http://pygments.org), you'd probably want to take a look there.

**Comment by birkenfeld** [comment]
As @xmo-odoo says, this would have to be handled in Pygments.

**Comment by tojon** [comment]
@birkenfeld I see on [pygments](http://pygments.org/) it says you are the maintainer of that project. Are you aware of a bug reported already, or do you recommend I re-enter/cross-ref this issue there.

**Comment by birkenfeld** [comment]
Would be great if you could open an issue here: https://bitbucket.org/birkenfeld/pygments-main
