### ISSUE TITLE
Unlisted phony targets in quickstart Makefile

### ISSUE THREAD

**Issue by cjdrake** [sphinx-doc/sphinx#1894]
From sphinx/quickstart.py, the following phony targets are not listed in the `.PHONY:` line:
- applehelp
- latexpdfja
- texinfo
- info
- xml
- pseudoxml

Also, the `gettext` target is out of order. It should appear between `info` and `changes`, but it appears at the end.

As a matter of style, you might consider using the following convention to avoid the phony target list getting out of sync with a changing set of phony targets:

``` makefile
.PHONY: foo
foo:
    @echo foo

.PHONY: bar
bar:
    @echo bar
```

**Comment by tk0miya** [comment]
Fixed at e8e5391.
Thank you for reporting and good suggestion!
