### ISSUE TITLE
There should be an easy way to disable certain warnings

### ISSUE THREAD

**Issue by wolph** [sphinx-doc/sphinx#1895]
Within my docs I use a few nonlocal images since they're automatically being generated by remote systems, and right now Sphinx warns me every time about this:

```
../README.rst:None: WARNING: nonlocal image URI found: https://travis-ci.org/WoLpH/mt940.png?branch=master
```

To have my docs automatically tested I generally run sphinx-build with `-W`, but this makes it difficult to do that.

**Comment by shimizukawa** [comment]
Agreed.
I can't find any evidence for necessary of the warning.
https://github.com/sphinx-doc/sphinx/commit/ba47f283f67aad9151bbf0e4874cdff7bfad8adb

**Comment by shimizukawa** [comment]
However, LaTeX builder might need local image to build.
It would be better if nonlocal image warning can be disabled by some option.

**Comment by birkenfeld** [comment]
Now tracked in #1969.

**Comment by ben-albrecht** [comment]
Any progress on this?

**Comment by wolph** [comment]
@ben-albrecht look at #1969, that issue is now tracking this.
