### ISSUE TITLE
Autosummary Difference from v1.2.3

### ISSUE THREAD

**Issue by bhermanmit** [sphinx-doc/sphinx#1896]
I am currently changing our documentation to work with v1.3.1 of Sphinx. I am having issues with one aspect of autosummary that worked fine in v1.2.3, but not in v1.3.1. In v1.2.3 I was able to do the following:

```
.. autosummary::
   :toctree: generated

   package.Model
```

where package is a directory that contains an __init__.py that imports Model from package.model:

```
from package.model import Model
```

I could only get the following to work when autosummary references the exact module that the class is in:

```
.. autosummary::
   :toctree: generated

   package.model.Model
```

What is the intended behavior?

One can download my simple example at https://github.com/bhermanmit/test_autosummary.

**Comment by tk0miya** [comment]
Sorry for very late response.
Since 1.3, autosummary avoids imported members by default. see #1061.
