### ISSUE TITLE
"latexpdf" option is absent in make help

### ISSUE THREAD

**Issue by nastasviatoha** [sphinx-doc/sphinx#1897]
Hi all,

When creating PDF document for my Sphinx project, I have always used this way and it works fine:
1. make latex
2. pdflatex <projectname>.tex

But today I've decided to try another way, that is 'make latexpdf' and got the following output:

" build succeeded, 2 warnings.
'make' is not recognized as an internal or external command,
operable program or batch file.
Build finished; the PDF files are in build/latex."

Firstly, I've decided to check my make "makefile", and it contains "latexpdf" option. Please check it here: https://drive.google.com/file/d/0B4mCq7gApRAgcllkU0dEeV94SzQ/view?usp=sharing

Secondly, I just run "make" in order to see the list of available options and haven't found "latexpdf" there (I'm Windows user):

D:\Admin>make
Please use `make <target>` where <target> is one of
  html       to make standalone HTML files
  dirhtml    to make HTML files named index.html in directories
  singlehtml to make a single large HTML file
  pickle     to make pickle files
  json       to make JSON files
  htmlhelp   to make HTML files and a HTML help project
  qthelp     to make HTML files and a qthelp project
  devhelp    to make HTML files and a Devhelp project
  epub       to make an epub
  latex      to make LaTeX files, you can set PAPER=a4 or PAPER=letter
  text       to make text files
  man        to make manual pages
  texinfo    to make Texinfo files
  gettext    to make PO message catalogs
  changes    to make an overview over all changed/added/deprecated items
  xml        to make Docutils-native XML files
  pseudoxml  to make pseudoxml-XML files for display purposes
  linkcheck  to check all external links for integrity
  doctest    to run all doctests embedded in the documentation if enabled
  coverage   to run coverage check of the documentation if enabled

**Comment by shimizukawa** [comment]
It's a duplicated issue for #1867 . Sorry for inconvenience.
