### ISSUE TITLE
BuildEnvironment.srcdir documentation gives false information

### ISSUE THREAD

**Issue by storax** [sphinx-doc/sphinx#1900]
It says under [srcdir documentation](http://sphinx-doc.org/extdev/envapi.html#sphinx.environment.BuildEnvironment.srcdir):
`Source directory (the directory containing conf.py).`
But that is only by default. You can put the conf.py somewhere else and specify the '-c' option of `sphinx-build`. This caused some confusion. The dir of conf.py can be looked up in the Sphinx App attribute `confdir`.

**Comment by tk0miya** [comment]
Fixed at bef3025
Thank you for reporting
