### ISSUE TITLE
Napoleon: Return statement containing colons is not handled correctly

### ISSUE THREAD

**Issue by qnzhou** [sphinx-doc/sphinx#1904]
This problem is related to https://github.com/sphinx-doc/sphinx/issues/1831.  It seems the greedy parsing strategy introduced in https://github.com/sphinx-doc/sphinx/commit/42f2b305791507e6bfe9507832daefc5071969cd is the culprit.

For example a return doc in Google style would be parsed incorrectly:

```
Returns: 
    :class:`numpy.ndarray`: A :math:`n \\times 2` array containing...
```

Napoleon "mis-parse" the return type as `numpy.ndarray: A :math`

Sphinx v1.3.1
Napoleon v0.3.4

**Comment by RobRuana** [comment]
Thanks, I'm looking into it!
