### ISSUE TITLE
**This text :ref:`does not <render-correctly>**

### ISSUE THREAD

**Issue by pop** [sphinx-doc/sphinx#1908]
When italicizing or bolding text which includes a :ref: internal link it renders incorrectly.
For example:

```
I wrote some docs! They are **so cool you should :ref:`read them <my-new-docs>`!**
```

Which references a document that starts:

```
.. _my-new-docs:

They are so fancy!
------------------
Pls be happy for me.
```

gets rendered as:  I wrote some docs! They are **so cool you should :ref:`read them <my-new-docs>`!**

This _might_ be a feature, but it doesn't feel like one and I haven't found any documentation that verifies this theory. If it is in fact not accidental feel free to close this issue. I will understand.

If it is not on purpose but nobody wants to fix it I'd appreciate someone pointing me in the general direction of the code which affects this part of sphinx so I can fix it myself. 

_edit: minor grammar and spelling_

**Comment by RobRuana** [comment]
I believe this is because reStructuredText does not support nested inline markup. Support for this feature would have to be added in the docutils codebase.

See the [relevant question](http://docutils.sourceforge.net/FAQ.html#is-nested-inline-markup-possible) in the docutils FAQ.
