### ISSUE TITLE
internal error due to enum support in 1.3.1

### ISSUE THREAD

**Issue by poulson** [sphinx-doc/sphinx#1913]
As far as I can tell, the `:cpp:enum::` plus `:cpp:enumerator::` support is broken with Sphinx 1.3.1 on both Ubuntu and OS X. I see internal errors of the form::

```
reading sources... [ 18%] blas_like/level3/Gemm                                 
Exception occurred:
  File "/Users/poulson/anaconda/lib/python2.7/site-packages/Sphinx-1.3.1-py2.7.egg/sphinx/domains/cpp.py", line 656, in __init__
    assert len(names) > 0
AssertionError
The full traceback has been saved in /var/folders/54/044qly2s21dcnhfh1xk_mtgm0000gn/T/sphinx-err-HgtOqO.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [web] Error 1
```

The offending code appears to be the enum located at https://raw.githubusercontent.com/elemental/elemental-web/master/source/doc-dev/blas_like/level3/Gemm.rst

The log file can be found here: https://gist.github.com/poulson/e5b5b7d39e3770a0a1a7

**Comment by shimizukawa** [comment]
@jakobandersen can you take a look this?

**Comment by jakobandersen** [comment]
Thanks for reporting.

**Comment by shimizukawa** [comment]
@jakobandersen Thanks!
