### ISSUE TITLE
AttributeError: admin

### ISSUE THREAD

**Issue by korjcjeong** [sphinx-doc/sphinx#1914]
It seems everything is installed smoothly, but I have got following errors. 
What could be the reason and how I can solve this problem?
Could anyone help me?

sphinx-build -b html -d build/doctrees   . build/html
Running Sphinx v1.3.1
making output directory...

Exception occurred:
  File "/home/jcj15/.local/lib/python2.7/site-packages/enum34-1.0.4-py2.7.egg/enum/**init**.py", line 373, in **getattr**
    raise AttributeError(name)
AttributeError: admin
The full traceback has been saved in /tmp/sphinx-err-cWHJnc.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at https://github.com/sphinx-doc/sphinx/issues. Thanks!
make: **\* [html] Error 1

**Comment by birkenfeld** [comment]
Thanks for the report! Could you attach the traceback file referred to in the traceback report?

**Comment by tk0miya** [comment]
Now, it seems this issue is obsoleted. So I close this.
If you get tracebacks or additional info, please reopen.

Thanks,
