### ISSUE TITLE
Minor documentation bug in windows install guide

### ISSUE THREAD

**Issue by ianrrees** [sphinx-doc/sphinx#1920]
http://sphinx-doc.org/install.html#windows-install-python-and-sphinx at the bottom claims:

_After installation, type **sphinx-build** on the command prompt. If everything worked fine, you will get a Sphinx version number and a list of options for this command._

It appears that the appropriate command is actually **sphinx-build --help**.  -Ian-

**Comment by shimizukawa** [comment]
Fixed it on repository. Thanks!
