### ISSUE TITLE
Upper characters problem in French stemmer

### ISSUE THREAD

**Issue by jibalamy** [sphinx-doc/sphinx#1922]
I've found a bug in the HTML / Javascript search engine with the French language. The bug is actually related to the indexing of the doctree. The HTML / Javascript search engine expects only lower characters in the index. When indexing, the English stemmer removes upper characters and replace them with lower ones (with .lower()). However, the French stemmer (in sphinx/search/fr.py) keeps the upper characters. Consequently, any word with an upper character in wrongly indexed in French.
This can easily be fixed by adding ".lower()" in SearchFrench.stem().

**Comment by usaturn** [comment]
@jibalamy 

Thank you for giving me a suggestion.
If you do not mind, can you give me a pull request?
Thank you.

**Comment by tk0miya** [comment]
I just made a very simple PR #4396 for this.
@jibalamy could you try this please?

**Comment by jibalamy** [comment]
Hello,

I've just tested, and it seems ok :)

Best regards,
Jean-Baptiste Lamy
MCF, LIMICS, Université Paris 13
