### ISSUE TITLE
XeLaTeX: Error using polyglossia instead of babel due to unconditional use of babel features

### ISSUE THREAD

**Issue by ghost** [sphinx-doc/sphinx#1923]
I have configured a custom preamble, disabling babel so that I can use polyglossia with XeLaTeX.  We do this so we can use UTF-8 sphinx input text and get decent unicode font handling, substitution, subsetting etc. with PDF output, which the default pdflatex can't provide .  Important lines marked with `****`:

We start by disabling a bunch of features which break with XeLaTeX, or which have better replacements; we'll enable these ourselves in the preamble.  https://github.com/openmicroscopy/bioformats/blob/develop/docs/sphinx/conf.py.in#L295

```
latex_elements = {
    'classoptions': ',oneside',
    'pointsize': '10pt',
    'inputenc': '%% Unused',
    'utf8extra': '%% Unused',
    'fontenc' : '%% Unused',
    'fontpkg': '%% Unused',
    'babel': '%% Unused',                                   ****
    'printindex': '''\\phantomsection
\\addcontentsline{toc}{part}{\indexname}
\\printindex''',
    'preamble': '''
\input{preamble.tex}                                        ****
''',
}
```

Here, we enable modern features, such as extended unicode, latex fixes, polyglossia and opentype fonts:

preamble.tex: https://github.com/openmicroscopy/bioformats/blob/develop/docs/sphinx/preamble.tex

```
\usepackage[a4paper, left=1.5cm,top=2cm,right=1.5cm,bottom=2cm]{geometry}

\usepackage{newunicodechar}
\newunicodechar{ }{\nobreakspace{}}

\usepackage{amsmath}
\usepackage{color}
\usepackage{fixltx2e}
\usepackage{mathspec}

\usepackage{xunicode}
\usepackage{xltxtra}
\usepackage{polyglossia}                                    ****
\defaultfontfeatures{Mapping=tex-text}
\setmainfont{TeX Gyre Termes}
\setromanfont{TeX Gyre Termes}
\setsansfont{TeX Gyre Heros}
\setmonofont{TeX Gyre Cursor}
\setmathsfont{TeX Gyre Termes Math}
\setdefaultlanguage{english}
```

This worked fine with sphinx 1.2.3.  With 1.3.1, this is added to the TeX file:

```
% Generated by Sphinx.
\def\sphinxdocclass{report}
\documentclass[letterpaper,10pt,oneside]{sphinxmanual}
%% Unused
%% Unused
\usepackage{cmap}
%% Unused
%% Unused
%% Unused                                                   ****
\usepackage[Bjarne]{fncychap}
\usepackage{longtable}
\usepackage{sphinx}
\usepackage{multirow}
\addto\captionsenglish{\renewcommand{\figurename}{Fig. }}   ****
\addto\captionsenglish{\renewcommand{\tablename}{Table }}   ****
\floatname{literal-block}{Listing }

\input{preamble.tex}                                        ****
```

Note that while babel is commented out, the `\addto\captionsenglish{...` is used unconditionally, and this causes the build to fail:

```
! Undefined control sequence.
l.15 \addto
           \captionsenglish{\renewcommand{\figurename}{Fig. }}
```
- Would it be possible to wrap these commands in a conditional, so they are only used if the babel commands/variables are already defined?

As an aside, having sphinx support XeLaTeX properly either in place of or as an alternative to pdflatex would be a great improvement to have in sphinx.  The above samples are what I use at present to work around the lack of native support, but the essential parts could be easily integrated.

Kind regards,
Roger Leigh

**Comment by pmcguinn** [comment]
Hi did you get any further feedback on this? I'm having the same issue and a work around isn't just as simple.

**Comment by ghost** [comment]
@pmcguinn I'm afraid not.  I'm currently downgraded 1.2.3 to avoid the issue.  I'm not a latex expert, but if this could be wrapped in a conditional checking if \captionsenglish was defined, then that's probably a simple fix to make to sphinx.

**Comment by pmcguinn** [comment]
Hi Roger,

I guess you could make a slight modification to the writers/latex.py file and do as you say wrap it in an IF statement, but really I would prefer not to have to customise sphinx if I could get around it by disabling it somehow.

**Comment by mitya57** [comment]
We are facing the same issue in sympy build: https://gist.github.com/mitya57/f43720cba9ab12b07d92.

**Comment by birkenfeld** [comment]
Thanks for the report. This should now be fixed if you set `latex_elements['babel']` to an empty string.

**Comment by ghost** [comment]
@birkenfeld Awesome, thanks.  This really is most appreciated.

**Comment by pmcguinn** [comment]
Brilliant 😊

Sent from my Windows Phone

**Comment by NoralK** [comment]
FYI - I just tested this using the "Stable" build and these lines are still present:

```
\addto\captionsenglish{\renewcommand{\figurename}{Fig. }}
\addto\captionsenglish{\renewcommand{\tablename}{Table }}
```

using this in the `conf.py`:

```
latex_elements = { 
    'classoptions': ',oneside', 
    'pointsize': '10pt', 
    'inputenc': '', 
    'utf8extra': '', 
    'fontenc' : '', 
    'fontpkg': '', 
   'babel': '', 
    'printindex': '''\\phantomsection 
\\addcontentsline{toc}{part}{\indexname} 
\\printindex''', 
    'preamble': ''' 
\usepackage{fontspec}
\setmainfont{Calibri}
'''
} 
```
