### ISSUE TITLE
Liquid-style tags for including IPython notebooks in Sphinx documentation

### ISSUE THREAD

**Issue by ostrokach** [sphinx-doc/sphinx#1926]
Is there a Sphinx equivalent of [liquid_tags](https://github.com/getpelican/pelican-plugins/tree/master/liquid_tags), and if not, has anyone considered making a port? 

It would be super useful if you could write sections of the documentation inside an IPython notebook (in order to include a short run-through or a tutorial, for example).

**Comment by lehmannro** [comment]
I'm not sure what your actual request is.  If it's IPython integration a quick search for _"Sphinx IPython"_ [yields](https://ipython.org/ipython-doc/dev/api/generated/IPython.sphinxext.ipython_directive.html) [numerous](http://sphinx-ipynb.readthedocs.org/en/latest/howto.html) results.  (One being supplied by IPython itself...)

If you want liquid tags for whatever reason, I'd like to note that [Jinja2 tags](http://jinja.pocoo.org/docs/dev/templates/) are _very_ similar for templating and usually [ReST directives](http://docutils.sourceforge.net/docs/ref/rst/directives.html) fit the bill for content.

I don't see any actionable request here right now;  closing.

**Comment by ostrokach** [comment]
In case someone stumbles on this issue from google, I ended up using [yt](http://yt-project.org/) project's [`notebook_sphinxext`](https://bitbucket.org/ngoldbaum/yt-doc/src/tip/extensions/notebook_sphinxext.py) extension, which allows you to include notebooks in your sphinx documents using a simple command: 

```
.. notebook:: examples/demo.ipynb
   :skip_exceptions:
```

No need to run `ipython nbconvert` (required by `sphinx_ipynb`), and no need to copy-paste your code from ipython notebooks into into _.rst_ files (required by the `sphinxext.ipython_directive`).
