### ISSUE TITLE
option-group doesn'

### ISSUE THREAD

**Issue by abellgithub** [sphinx-doc/sphinx#1930]
This may be an issue for docutils, but figured I'd start here.  When the node tree is walked for HTML, an option-group considers the length of the text to determine whether the text should span two columns or not, however it doesn't seem to consider an optional argument string following the options, which results in the argument string being placed in column 1, below the option text itself, rather than to the right.

For instance:

```
--longoption, -short argument  Description text
```

will be displayed properly as:

```
--longoption, -short argument
              Description text
```

because the option strings themselves are longer than the first column size, but

```
--longoption arg  Description text
```

Might be displayed as:

```
--longoption    Description text
arg
```

depending on the length of the string `--longoption`.

**Comment by birkenfeld** [comment]
Yes, this should go to docutils.
