### ISSUE TITLE
Document generations for library modules

### ISSUE THREAD

**Issue by sidd411** [sphinx-doc/sphinx#1932]
Hi,
I have a requirement where in I have to generate the documentation for the all my python scripts and library modules. There are some modules that are not protected by a if **name** == '**main**' condition.

Is there any way to override it or is it practically not possible ?

Thanks,
Srinivas

**Comment by shimizukawa** [comment]
There is no way to autodoc without executing global level code.

Related discussion is here: https://groups.google.com/d/msg/sphinx-users/7quQx2r4dGc/0WtQmsDdTM4J

**Comment by sidd411** [comment]
Thanks for pointing me to the related discussion on the issue.
