### ISSUE TITLE
Make top_sectionlevel configurable for the LaTeX writer

### ISSUE THREAD

**Issue by bgeron** [sphinx-doc/sphinx#1937]
I have a Sphinx document that I want in LaTeX in a more personalised style, with a different document class. (I'm preparing a conference publication; the conference provides the document class.) This document class has `\section` for the top level headings, not `\chapter`, but Sphinx generates `\part` or `\chapter` by default depending on `latex_use_parts`. 

I'm currently working around this by setting the `docclass` field of `latex_documents` in `conf.py` to `howto`, and overriding `latex_elements['wrapperclass']`, but it would be cleaner if there was a proper configuration option for this.

The relevant logic is in: https://github.com/sphinx-doc/sphinx/blob/27be6614f77f99a5d5d633903f306920413c5bc8/sphinx/writers/latex.py#L275

I'm not sure what the cleanest way is to make this configurable. Perhaps `latex_use_parts` can be a ternary choice (0/1/2 or -1/0/1), but then the name `latex_use_parts` itself sounds odd.

**Comment by bgeron** [comment]
This is a feature request.

**Comment by tk0miya** [comment]
Since 1.4, sphinx provides `latex_toplevel_sectioning` to do that.
This might be resolved.

Thanks,
