### ISSUE TITLE
Export directly to PDF

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#194]
I'm not sure if there is a capacity to do this however I would love to be able to export to PDF directly from the hosted docs via a button on the page. I want to use this platform to host all the product documentation for my company.

Maybe I've missed this in the documentation but I only see export to LaTex from which I can create a PDF. Please advise. 

p.s. I use this for another project I'm working with and love how easy it is to use. Thanks for the great work, I really appreciate it!

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/194
- Originally reported by: [linji](https://bitbucket.org/linji)
- Originally created at: 2009-06-05T18:38:31.816

**Comment by shimizukawa** [comment]
_From Juha Mustonen on 2009-06-06 12:45:52+00:00_

When it comes to PDF conversion, it is currently done via LaTex: Sphinx generates LaTeX sources, where it is converted to PDF using //pdflatex// (make file is also generated). This two step conversion can be easily combined using bash or python scripting, or even Ant, like I've done at work.

Having said that, there also exists a sphinx -fork (https://bitbucket.org/gminick/sphinx-rst2pdf-builder/overview/) that tries to provide native PDF writer, using rst2pdf. However, this is still work in progress.

Why do you need to have PDF conversion per request? I, for example, use Hudson (https://hudson.dev.java.net/) to convert all the documents whenever they are committed into version control, making the latest documents to be always available via Apache powered website.

One more resource you might also want to have a look is : http://rst2a.com/

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2009-06-15 15:20:49+00:00_

The rst2pdf writer is already tracked in <<issue 27>>.

Duplicate of #27.

**Comment by shimizukawa** [comment]
_From Andreas H. on 2010-03-11 18:56:13+00:00_

Sorry to disagree, but I don't think this is resolved.

It would be really great if the requested functionality //"to be able to export to PDF directly from the hosted docs via a button on the page"// would be implemented. I'm thinking of a link right under the "Show source" link in the sidebar, so that the user can easily access the PDF version of a page with one single click.

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2010-04-06 09:41:42+00:00_

Ah yes. It seems I've not completely read the OP. I'll leave this open as a RFE then.

**Comment by shimizukawa** [comment]
_From WAKAYAMA shirou on 2014-08-11 15:53:48+00:00_

How about 'Print as PDF' or use PDF printer driver?

**Comment by blaisep** [comment]
Actually, I am also interested in _make pdf_ because we have reviewers who prefer to look at a facsimile of the whole document.
I have tried the rst2pdf extension [http://rst2pdf.ralsina.me/stories/index.html] but when I update the Makefile like this:

```
pdf:
    $(SPHINXBUILD) -b pdf $(ALLSPHINXOPTS) $(BUILDDIR)/pdf
    @echo
    @echo "Build finished. The PDF files are in build/pdf."
```

 I get these errors and the PDF file is empty:

```
# Sphinx version: 1.2.3
# Python version: 2.7.9
# Docutils version: 0.12 release
# Jinja2 version: 2.7.3
# Loaded extensions:
#   sphinx.ext.autodoc from /Users/u135/.virtualenvs/py3/lib/python2.7/site-packages/sphinx/ext/autodoc.pyc
#   sphinx.ext.intersphinx from /Users/u135/.virtualenvs/py3/lib/python2.7/site-packages/sphinx/ext/intersphinx.pyc
#   rst2pdf.pdfbuilder from /Users/u135/.virtualenvs/py3/lib/python2.7/site-packages/rst2pdf-0.93.dev-py2.7.egg/rst2pdf/pdfbuilder.pyc
#   sphinxcontrib.restbuilder from /Users/u135/.virtualenvs/py3/lib/python2.7/site-packages/sphinxcontrib/restbuilder.pyc
#   sphinx.ext.coverage from /Users/u135/.virtualenvs/py3/lib/python2.7/site-packages/sphinx/ext/coverage.pyc
#   sphinxcontrib.napoleon from /Users/u135/.virtualenvs/py3/lib/python2.7/site-packages/sphinxcontrib/napoleon/__init__.pyc
#   sphinx.ext.todo from /Users/u135/.virtualenvs/py3/lib/python2.7/site-packages/sphinx/ext/todo.pyc
#   sphinx.ext.ifconfig from /Users/u135/.virtualenvs/py3/lib/python2.7/site-packages/sphinx/ext/ifconfig.pyc
#   sphinx.ext.oldcmarkup from /Users/u135/.virtualenvs/py3/lib/python2.7/site-packages/sphinx/ext/oldcmarkup.pyc
Traceback (most recent call last):
  File "/Users/u135/.virtualenvs/py3/lib/python2.7/site-packages/sphinx/cmdline.py", line 254, in main
    app.build(force_all, filenames)
  File "/Users/u135/.virtualenvs/py3/lib/python2.7/site-packages/sphinx/application.py", line 220, in build
    self.builder.build_update()
  File "/Users/u135/.virtualenvs/py3/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 214, in build_update
    'out of date' % len(to_build))
  File "/Users/u135/.virtualenvs/py3/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 276, in build
    self.write(docnames, list(updated_docnames), method)
  File "/Users/u135/.virtualenvs/py3/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 308, in write
    self.prepare_writing(docnames)
  File "/Users/u135/.virtualenvs/py3/lib/python2.7/site-packages/sphinx/builders/html.py", line 296, in prepare_writing
    path.basename(self.config.html_logo) or ''
  File "/Users/u135/.virtualenvs/py3/bin/../lib/python2.7/posixpath.py", line 121, in basename
    i = p.rfind('/') + 1
AttributeError: 'list' object has no attribute 'rfind'
```

**Comment by tk0miya** [comment]
We have readthedocs now. It builds HTML, ePub and PDF at same time and serves them.
So I think this is already resolved.

Please reopen if you still have any problem.

In addition, rst2pdf works fine now :-)
