### ISSUE TITLE
Error in "code-block" directive: unknown option: "caption".

### ISSUE THREAD

**Issue by electronwill** [sphinx-doc/sphinx#1943]
http://sphinx-doc.org/markup/code.html says it's a new option in Sphinx 1.3 to put a caption in a code block, but when I tried it on 1.3.1 I got "ERROR: Error in "code-block" directive: unknown option: "caption"." Please let me know if there are more debugging steps I can try or if there's more info I can collect to add to the issue.

**Comment by shimizukawa** [comment]
@electronwill, to clarify, please let me know the full command and its output. I suspect that sphinx version is not 1.3, or code-block directive is replaced by some extension.

**Comment by electronwill** [comment]
Closer examination shows that the first output from sphinx-build is "Running Sphinx v1.2.3", even though my package manager said Sphinx 1.3.1. I'll take it up with the package manager. I'm very sorry I bothered you, and I thank you and everyone on the team for all your good work on Sphinx!

**Comment by shimizukawa** [comment]
:thumbsup:
