### ISSUE TITLE
rst_prolog breaks file-wide metadata

### ISSUE THREAD

**Issue by takluyver** [sphinx-doc/sphinx#1944]
I'm trying to mark pages as `:orphan:` so Sphinx doesn't complain that they're not in a toctree. But the project's conf.py sets an `rst_prolog` (to make it clear that the docs are for a development version). This means that the field list is no longer the first thing in the file, so Sphinx doesn't see it as metadata, and it shows up in the page instead.

It looks like rst_prolog is added by string concatenation; is it possible to understand enough of the file structure to insert it after the file's field list?

**Comment by tk0miya** [comment]
Fixed at 9ed3d51.
Thank you for reporting
