### ISSUE TITLE
html.parser.HTMLParseError was removed in Python 3.5

### ISSUE THREAD

**Issue by warsaw** [sphinx-doc/sphinx#1945]
The Sphinx test suite fails under Python 3.5 because this exception, which was deprecated in Python 3.3 has finally been removed.   I'll try to work up a pull request for a workaround.

**Comment by shimizukawa** [comment]
Good to know!

**Comment by warsaw** [comment]
https://github.com/sphinx-doc/sphinx/pull/1946

**Comment by birkenfeld** [comment]
And merged. Thanks Barry!
