### ISSUE TITLE
Use graphviz directive in autodoc-process-docstring

### ISSUE THREAD

**Issue by codingjoe** [sphinx-doc/sphinx#1950]
I currently try to write an extension, that processes certain classes representing an FSM and try to create a graphviz model on the fly.

I can create the proper code using `autodoc-process-docstring` but the directive is not being executed.
If I add the generated code to my docstring it works just fine.

Is there any way to manually trigger the directive or do I need to have a certain order importing the extensions?

**Comment by birkenfeld** [comment]
This is strange; processing the docstring should come before any processing is done.

Are you sure you are modifying the list of lines in place?

**Comment by codingjoe** [comment]
@birkenfeld yes I am. I see the right output, but it doesn't render. Same if you use the inheritance graph. Doesn't render ether.

**Comment by tk0miya** [comment]
On my local, it seems working fine.
```
def process_docstring(app, what, name, obj, options, lines):
    lines.extend(['',
                  '.. graphviz::',
                  '',
                  '   digraph { A -> B }'])


def setup(app):
    app.connect('autodoc-process-docstring', process_docstring)
```

I think this issue can be closed. any comments?

**Comment by codingjoe** [comment]
@tk0miya you are right. I can be closed I am using it in two projects already. Sorry
