### ISSUE TITLE
:ref: :doc: :any: roles aren't working and information as to why isn't in the documentation

### ISSUE THREAD

**Issue by newbie2356** [sphinx-doc/sphinx#1955]
Instead of a link appearing I just get the plaintext output coming straight out. I can't find the information in the documentation as to why this doesn't work. I'm reasonably certain :ref: :doc: :any: roles are built in sphinx functionality and not an extension (can't find any mention that they require an extension) so I can only determine that it's either a default configuration issue or a full on bug.

**Comment by birkenfeld** [comment]
Thanks for the report! These roles should work "out of the box". You should get a warning if no target is found for `doc` and `ref`. Do you get these? Can you give an exampe what markup you are writing?

**Comment by newbie2356** [comment]
Hmm, after reading the documentation more closely, I noticed that it was a backtick ` not a single quote '

I was using single quotes 'like-this' and that was throwing the builder off. e.g. :ref:'banana' where I should have typed :ref:`banana`

Might I suggest adding a warning to the builder when single quotes are used after one of the link roles?

**Comment by birkenfeld** [comment]
Thanks for the feedback. It is not easy to recognize these kinds of markup error, so I'd rather not try and special case this one.
