### ISSUE TITLE
Default conf.py is not PEP8-compliant

### ISSUE THREAD

**Issue by evildmp** [sphinx-doc/sphinx#1956]
https://github.com/sphinx-doc/sphinx/blob/6b8f29bb45e3cda4cbd38727cc6726286b50db0e/sphinx/quickstart.py creates a `conf.py`, but it's not PEP8-compliant. 

For example, commented-out lines should start with `#`, while https://github.com/sphinx-doc/sphinx/blob/6b8f29bb45e3cda4cbd38727cc6726286b50db0e/sphinx/quickstart.py#L90 imports shlex, which as far as I can tell is never used.

Would you accept a pull request addressing this?

**Comment by birkenfeld** [comment]
I'll fix the unused import; the different comment style is there to differentiate real comments from commented-out code that you can use.

**Comment by johnthagen** [comment]
@birkenfeld Could this be reopened?

The default `conf.py`, while very close to being PEP8 compliant, is not quite. All that is needed now is an extra newline at the end of the file. This is hopefully an easy fix and would make it a nice experience out of the box.

To reproduce the problem:

```bash
$ pip list
Package                  Version   
------------------------ ----------
...
flake8                   3.6.0
...
Sphinx                   1.8.2     

$ sphinx-quickstart
# Select all defaults

$ flake8 conf.py 
conf.py:173:1: W391 blank line at end of file
```

**Comment by tk0miya** [comment]
@johnthagen I posted #5840 as a fix
