### ISSUE TITLE
C++ indexing not super useful when everything's in a root namespace

### ISSUE THREAD

**Issue by cbiffle** [sphinx-doc/sphinx#1958]
(Reported against Sphinx 1.3.1)

I really like Sphinx's automatic index generation.  Unfortunately, it's not uncommon for a C++ library's code to live inside a namespace -- and that makes the index less valuable, because it can't strip the common name prefix.

For example:
![screenshot of index with everything under E](https://cloud.githubusercontent.com/assets/45247/8677709/7e2030a2-2a05-11e5-8a97-cb1d7b2c1e0e.png)

The Python module index generator can address this problem through the `modindex_common_prefix` configuration parameter, but I see no equivalent for index generation, and the Python module index generator doesn't grok C++.

**Comment by jakobandersen** [comment]
A `cpp_index_common_prefix` configuration variable should be easy to make, but probably it shouldn't be applied on the general index. When I find time I will try to make a C++ specific index instead.

**Comment by cbiffle** [comment]
A C++-specific index, analogous to the Python module index, would be _fantastic._  I agree that any namespace-stripping should apply to such an index.

Separately, I wonder if it would be useful to remove prefixes in the _text_ index also.  e.g. index the symbol "__cxxabi_pure_virtual" under both "_" and "C".  But I suppose that's a separate feature request.

**Comment by jakobandersen** [comment]
The configuration variable `cpp_index_common_prefix` can now be used to list prefixes that should be removed from C++ objects in the global index.
Though, it would still be nice to be able to create indices for specific scopes.
