### ISSUE TITLE
copyong downloadable files output line

### ISSUE THREAD

**Issue by slavkoja** [sphinx-doc/sphinx#1960]
When i do sphinx-build for html otput i can see (beside other):

```
copying downloadable files... [  4%] /home/slavko/Dokumenty/sphinx/poznamky/elektro/020_raspberry/010_popis/zzz-rpib/files/Raspberry-Pi-Mounting-Hole-Templa
copying downloadable files... [ 95%] /home/slavko/Dokumenty/sphinx/poznamky/elektro/010_arduino/100_periferia/500_wireless/files/ESP8266-ESP-201-pin-referen
copying downloadable files... [100%] /home/slavko/Dokumenty/sphinx/poznamky/elektro/170_moduly/files/bmp180.pdfo/files/ad5206BRU10.pdf
```

The line (IMO) must be truncated to terminal width, because the line is wrapped by (my) terminal emulator and then it continues at the new line...

This problem with calculating of the line width is in another situations too: i often can see the lost ends of previous items, when the next are shorter. E.g.:

```
copying downloadable files... [ XY%] /some/path/file.pdf    .pdf
```

BTW, why there is displayed full path and not only part relative to buildroot? 

regards

**Comment by birkenfeld** [comment]
I don't consider that a real problem; the output is supposed to be pretty but no special care is taken to get it 100% right. When you pipe to a file you'll get different output with every item on one line anyway.

I'll fix the display to be a relative path, though.
