### ISSUE TITLE
:orphan: is rendered during include

### ISSUE THREAD

**Issue by vkruoso** [sphinx-doc/sphinx#1965]
I'm trying to mark pages as `:orphan:` so Sphinx doesn't complain that they're not in a toctree. The problem is when I have a file with `:orphan:` that is included using `.. include:: orphan_file.rst`. This causes Sphinx to render a `orphan:` text where the file was included.

Is looks like it should not happen. Any ideas?

**Comment by shimizukawa** [comment]
Please refer #1545

**Comment by vkruoso** [comment]
Sorry, I did my search only on the open issues. Please, fell free to close this one too.

Anyway, looks like it is docutils bug (or limitation). There is an issue in the docutils project for this (could no find one)? I've worked around this by adding the files to the `exclude_patterns` variable in `conf.py` configuration.

**Comment by shimizukawa** [comment]
Don't worry that, now I close this issue.
BTW, I also think it's a limitation of include directive. Actually I don't know there are some ticket for that or not. In my case, I use another file extension like `.inc` or `.txt` for that.
