### ISSUE TITLE
Keyboard shortcuts to navigate Next and Previous topics

### ISSUE THREAD

**Issue by bkowshik** [sphinx-doc/sphinx#1970]
While reading HTML pages build with Sphinx, it would be a nice feature to have keyboard shortcuts to navigate `Next` and `Previous` topics.

Thus, irrecpective of the Sphinx theme and placements of the `Next` and `Previous` buttons on the HTML page, keyboard shortcuts work on all Sphinx pages.

**Comment by birkenfeld** [comment]
I agree, this would be nice.

**Comment by fty48jj19** [comment]
bhargv  kowshik     uma ,pergunta para vc porque vc esta mem pedino reposutorio   acertos para vc crecer aqui vc e um contribuite e vc esta fazendo coisa desagradavel vc esta com um contribuite privado  vou broquia vc  se vc continua com sua versao   por favor  coloca um contribuite em aberto  por favor  vc esta tentano munipular a empresa  nao espere q eu broquio vc nao vou esta de olho em vc  pega a visao do que estou falando com vc,
