### ISSUE TITLE
label work incorrect when mixing use of Chinese and English

### ISSUE THREAD

**Issue by kkzhang** [sphinx-doc/sphinx#1973]
```
.. _faq-server-addr-changed:

服务器IP变更后无法更新
----------------------------------------
```

The anchor generated is `#IP`, which `faq-server-addr-changed` is expected.

If `IP` is removed from the header, everything works fine.

So, it seems a bug.

Sphinx version: 1.3.1

**Comment by shimizukawa** [comment]
Duplicate: #1961
