### ISSUE TITLE
make doc fails for git-version

### ISSUE THREAD

**Issue by HJarausch** [sphinx-doc/sphinx#1978]
make latexpdf
sphinx-build -b latex -d _build/doctrees   . _build/latex
Running Sphinx v1.3.1

Exception occurred:
  File "/Store2/Obj/Python/py-earth-git/pyearth/earth.py", line 1, in <module>
    from ._forward import ForwardPasser
ImportError: No module named 'pyearth._forward'

Many thanks for a hint,
Helmut

**Comment by shimizukawa** [comment]
It seems that the `_forward` is not importable.
Please check your environment, or please contact to py-earth author.
Thanks.
