### ISSUE TITLE
Autodoc can't detect module variables

### ISSUE THREAD

**Issue by urosjarc** [sphinx-doc/sphinx#1980]
Here is more information obout what is the source of my problems: http://stackoverflow.com/questions/31763600/why-sphinx-do-not-autodoc-module-variables

I joust cant make autodoc to recognize module variables auto. But if I add

```
#:
test = 'test'
```

It works.... But never for private or special members of module...
I joust can't make autodoc to recognize all module variables and list them in documentation...
I believe this is a bug...

**Comment by kratsg** [comment]
:+1: I seem to have a similar issue as well.

**Comment by xeroc** [comment]
+1

**Comment by tk0miya** [comment]
It seems this is same as #1063. So I marked this as duplicated and closing now.
