### ISSUE TITLE
SPHINX and codepage 65001

### ISSUE THREAD

**Issue by mr-raphael-martin** [sphinx-doc/sphinx#1982]
On windows platform (tested on Windows 2008 R2 server SP1) : 
- Open **cmd.exe**
- Enter **chcp 65001** (i.e. Codepage for Unicode)
- Run **sphinx-build** on a SPHINX project

You will obtain the following **error**

```
Exception occurred:
  File "D:\integ\python2.7.10\lib\site-packages\sphinx-1.3.1-py2.7.egg\sphinx\application.py", line 289, in _log
    wfile.write(message)
LookupError: unknown encoding: cp65001
The full traceback has been saved in ...\sphinx-err-eylnh3.log, if you want to report
 the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**Comment by shibukawa** [comment]
cp65001 is not supported on Python 2.7, but its support was added on Python 3.3. Try it.

https://docs.python.org/3.5/library/codecs.html#standard-encodings

**Comment by tk0miya** [comment]
Now I close this. Please reopen if you still have a trouble with python 3.3 or later.
