### ISSUE TITLE
primary_domain = None triggers a warning

### ISSUE THREAD

**Issue by chris-morgan** [sphinx-doc/sphinx#1984]
[From the `primary_domain` documentation](http://sphinx-doc.org/config.html#confval-primary_domain):

>  Can also be `None` to disable a default domain.

From a build of a project where I have set `primary_domain` to `None`:

> ```
> WARNING: the config value 'primary_domain' has type `NoneType', defaults to `str.'
> ```

Sphinx 1.3.1.

**Comment by shimizukawa** [comment]
@lehmannro please take a look.

**Comment by lehmannro** [comment]
Will do, I think I had improvements for the configuration types in the pipeline anyways.  ETA ~4 weeks though.
