### ISSUE TITLE
PDF output for :menuselection: and :guilabel:

### ISSUE THREAD

**Issue by NoralK** [sphinx-doc/sphinx#1987]
These get generated correctly in HTML:

```
:guilabel:`&Cancel`

:menuselection:`&File --> E&xit`
```

but they are not underlined in the PDF output.

How can this be fixed?

**Comment by NoralK** [comment]
Ping

**Comment by tk0miya** [comment]
I investigated about this problem.
The latex writer rendered `:guilabel:&Cancel` as `\emph{\DUspan{accelerator}{C}ancel}` in .tex file.

And then, latex expands it as `\emph{{\docutilsroleaccelerator C}ancel}`.
So if sphinx defines `\docutilsroleaccelerator` macro, it will be resolved.
but `\underline` requires text as argument. So I can't define the macro.
Can anyone fix this?

MEMO: I tested the behavior by adding following definition to `sphinx.sty`

```
\newcommand{\docutilsroleaccelerator}{\bf}
```

**Comment by shirou** [comment]
`DUspan` at [here](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/texinputs/sphinx.sty#L448), I think limiting scope and node content args are little bit diffcult to use.

Referencing `DUrole` of docutils.writer.latex2e at [here](http://repo.or.cz/w/docutils.git/blob/HEAD:/docutils/docutils/writers/latex2e/__init__.py#l555),  I changed DUspan to 

```
\providecommand{\DUspan}[2]{%
  \ifcsname docutilsrole#1\endcsname%
    \csname docutilsrole#1\endcsname{#2}%
  \else%
#2%
  \fi%
}
```

and then define docutilsroleaccelerator,

`\newcommand{\docutilsroleaccelerator}[1]{\textbf{\underline{#1}}}`

it works for me.

**Comment by tk0miya** [comment]
@shirou Thank you for advice.
Finally, I fixed this bug without through `DUspan`.

**Comment by NoralK** [comment]
Awesome - I just verified with the Stable build

Thank you
