### ISSUE TITLE
PDF generation "Contents" title

### ISSUE THREAD

**Issue by NoralK** [sphinx-doc/sphinx#1990]
When generating PDF output the Table of Contents title does not get updated to what I named it in the toctree:

```
.. toctree::
    :maxdepth: 2
    :caption: Table of Contents

    chapter1
    chapter2
```

This is the output:

![untitled](https://cloud.githubusercontent.com/assets/13447087/9184421/0d813308-3f6a-11e5-923c-4af6ec38a9d1.png)

How can this be fixed?

**Comment by tk0miya** [comment]
Thank you for reporting!
