### ISSUE TITLE
autosummary with no default primary domain

### ISSUE THREAD

**Issue by pinsardfr** [sphinx-doc/sphinx#2001]
Hi

Using Sphinx v1.3.1 with autosummary extension

In my rst file 

.. autosummary::
   :toctree: generated

   pypago.pypago_tonc

HTML build work fine. (all func, class, obj explicitly prefixed with :py:)

Because I won't to avoid ambiguity between some matlab and python homonyns,
I add  my conf.py 
   primary_domain = "None"

I have this message 
 ERROR: Unknown interpreted text role "obj"

What should I modify to avoid this ? 

Regards

**Comment by shimizukawa** [comment]
@pinsardfr you have 2 problems. Please correct as:
1. use `= None` instead `'None'`.
2. use

```
:py:obj:`foobar`
```

instead of

```
:obj:`foobar`
```
