### ISSUE TITLE
Decode error under python2 (only) when `make linkcheck` is run

### ISSUE THREAD

**Issue by garrison** [sphinx-doc/sphinx#2003]
We have recently run into a situation where `make linkcheck` fails (https://github.com/JuliaLang/julia/commit/354c730642346300c8eb5819b99e5d5e5aff729c#commitcomment-12365073) when it attempts to verify a page that contains `latin-1` bytes.  This only happens under python2; with python3 everything works as expected.

I made a small [test repository](https://github.com/garrison/sphinx-decode-testcase), where one can run `make linkcheck` to witness the behavior.

**Comment by tkelman** [comment]
Anything we can do to help triage, diagnose, and/or fix this any faster?

**Comment by tk0miya** [comment]
Fixed at 8b57bc7

**Comment by tkelman** [comment]
Thank you @tk0miya!
