### ISSUE TITLE
latex figure_align doesn't work

### ISSUE THREAD

**Issue by ghtmtt** [sphinx-doc/sphinx#2008]
I'm working on a debian testing machine with python-sphinx 1.2.3 installed.
I needed to _fix_ the figure in the final _pdf_ file built with `make latexpdf`
So in the`conf.py`` file I added::

```
latex_elements = {
    'figure_align':'H'
}
```

But it doesn't work. Figures in the `*.tex` file have **always** the **htbp** default options.

**Comment by tk0miya** [comment]
The `figure_align` option is added at v1.3.
Please upgrade your sphinx to newest.
