### ISSUE TITLE
Generated conf.py from sphinx tools should conform to PEP 8

### ISSUE THREAD

**Issue by johnthagen** [sphinx-doc/sphinx#2011]
`Sphinx` tools such as `sphinx-quickstart` and `sphinx-apidoc` generate `Sphinx` projects.  Within this, they generate a boilerplate `conf.py` for the user.  The problem is that the generated `conf.py` comes with dozens needless PEP 8 violations.  If the user generates a `Sphinx` project this way and then runs `pep8` or `flake8`, by default these tools search recursively for `.py` files and will inspect `conf.py`.

To save a bunch of manual work for each project, `Sphinx`'s generation of `conf.py` should be altered slightly to avoid these PEP 8 violations.

A sampling of the PEP 8 warnings (from `Sphinx 1.3.1`):

``` bash
.\conf.py:18:1: F401 'shlex' imported but unused
.\conf.py:28:1: E265 block comment should start with '# '
.\conf.py:215:1: E122 continuation line missing indentation or outdented
.\conf.py:305:80: E501 line too long (80 > 79 characters)
...
```

**Comment by shimizukawa** [comment]
Thanks, it seems duplicates to #1956 .

**Comment by johnthagen** [comment]
Sorry about that, tried to search for the issue before posting.  I might have missed it because the duplicate was already closed.
