### ISSUE TITLE
sphinx-quickstart finished " core dumped " error

### ISSUE THREAD

**Issue by colin4124** [sphinx-doc/sphinx#2015]
When sphinx-quickstart finished, it errors: [1]    17316 abort (core dumped)  sphinx-quickstart.  Does it matter? if so, how to sovle it ?  Environment is win7， babun windows shell base on cygwin.

```
Creating file ./source/conf.py.
Creating file ./source/index.rst.
Creating file ./Makefile.
Creating file ./make.bat.

Finished: An initial directory structure has been created.

You should now populate your master file ./source/index.rst and create other documentation
source files. Use the Makefile to build the docs, like so:
   make builder
where builder is one of the supported builders, e.g. html, latex or linkcheck.

[1]    17316 abort (core dumped)  sphinx-quickstart
```

**Comment by shimizukawa** [comment]
Which versions combination are you use? (cygwin, sphinx, python, and other sphinx related libraries that can be listed by `pip freeze`)
Please try isolating the problem by versions.

**Comment by colin4124** [comment]
Sphinx (sphinx-build) 1.3.1
Python 2.7.8 (default, Jul 28 2014, 01:34:03)
alabaster==0.7.6
Babel==2.0
docutils==0.12
Jinja2==2.8
MarkupSafe==0.23
Pygments==2.0.2
pytz==2015.4
six==1.9.0
snowballstemmer==1.2.0
Sphinx==1.3.1
sphinx-bootstrap-theme==0.4.7
sphinx-rtd-theme==0.1.8
wheel==0.24.0

**Comment by colin4124** [comment]
CYGWIN_NT-6.1 think-PC 1.7.35(0.287/5/3) 2015-03-04 12:07 i686 Cygwin

**Comment by shimizukawa** [comment]
Please try `pip install "babel<2.0"`

**Comment by colin4124** [comment]
It does not work. 

```
 Babel==1.3
```

There still is "python2.7.exe.stackdump" in the  source directory:

```
Stack trace:
Frame     Function  Args
0022C678  61030F12 (00000174, 0000EA60, 000000A4, 0022C6D8)
0022C798  610E514A (00000000, 00000000, 000000B0, 000000B4)
```

**Comment by shimizukawa** [comment]
Thanks for trying.
I guess the problem doesn't depend on Sphinx code.
So, I have no idea how to resolve it.

**Comment by colin4124** [comment]
thinks very much
