### ISSUE TITLE
Is there a way to put image in a section title?

### ISSUE THREAD

**Issue by huaiweicheng** [sphinx-doc/sphinx#2017]
Seeking for help~ Thanks buddies.

**Comment by shimizukawa** [comment]
I don't understand what you want to know, but using `.. image::` directive puts image in your document.

**Comment by huaiweicheng** [comment]
I wanna the effect such as this. Images follow text in the same line. Is that supported by sphinx?

![image](https://cloud.githubusercontent.com/assets/4011117/9574093/ef76a978-4ff5-11e5-8062-5ec9c8b11958.png)

**Comment by shimizukawa** [comment]
OK. In theory, you can use substitution (not tested).
http://docutils.sourceforge.net/docs/user/rst/quickref.html#substitution-references-and-definitions

e.g.

```
section title |yourimage|
=====================================

.. |yourimage| image:: actual-image-name.png
```

**Comment by huaiweicheng** [comment]
It works fine! Nice try! Many thanks.

**Comment by shimizukawa** [comment]
:smile:
