### ISSUE TITLE
ROI : html logo link to user specify URL

### ISSUE THREAD

**Issue by andreacassioli** [sphinx-doc/sphinx#2018]
It would be nice to be able to specify a URL the LOGO in HTML should point to. This has been posted already on the G group:

https://groups.google.com/forum/#!searchin/sphinx-users/html$20logo/sphinx-users/O4fHXX4b3wo/fkRpLmKFS1wJ

and a workaround proposed. But I guess it would be a natural option to provide.

**Comment by andreacassioli** [comment]
Sounds no one reacted on this. I will close the issue.

**Comment by tk0miya** [comment]
I think this idea is not bad. I will add the option in future version.
(I don't have enough time to do this. so I can't say when it will come)

**Comment by willcharlton** [comment]
@tk0miya - I just ran into this same issue. Can you give an estimate of when this might become available?

**Comment by tk0miya** [comment]
Not planned. We are always welcome your PR.
