### ISSUE TITLE
.htaccess not being copied along with other files.

### ISSUE THREAD

**Issue by josephcslater** [sphinx-doc/sphinx#2022]
html_extra_path brings in all of my other files, but neglects .htaccess for whatever reason.

**Comment by tk0miya** [comment]
In my short investigation:
`html_extra_path` is documented as:

> A list of paths that contain extra files not directly related to
> the documentation, such as `robots.txt` or `.htaccess`.

But, since its appearance in 1.2b1, it does not support the files starts with dot.
It might this is unexpected behavior. 

The main problem is caused by `sphinx.util.copy_static_entry()`.

**Comment by tk0miya** [comment]
As a workaround, you can avoid the bug with specifying a path to `.htaccess`.
Example::

```
html_extra_path = ['extra_path', 'extra_path/.htaccess']
```

**Comment by josephcslater** [comment]
Thanks!

**Comment by tk0miya** [comment]
In my short investgation (part 2):
`sphinx.util.copy_static_entry()` is used in these features:
- applehelp: `copy_localized_files()`
- changes: copy `themes/default/static/default.css_t` and `themes/basic/static/basic.css`
- `html`: copy static files from the selected theme
- `html`: copy files in `html_static_path`
- `html`: copy files in `html_extra_path`

It seems it is not insecure operation to copy files starts with dot without the case of applehelp.
(I don't know what is the builder doing in `copy_localized_files()`)

I'll take a look about applehelp builder. After that I'll change behavior of `copy_static_entry()`

**Comment by tk0miya** [comment]
Oh, I noticed that the `copy_static_entry()` expands template files end with `_t`.
It is undocumented behavior. It might be another bug of `html_extra_path`.

@mcmtroffaes Could you tell me about `html_extra_path` if you can recall? Did you expect it would expand templates on copying?

**Comment by mcmtroffaes** [comment]
@tk0miya I don't think I'd expect it to expand templates - but maybe there is a use case for it? Anyway, that seems unrelated to the original bug reported here, right?

Looking at the implementation, it seems to me that it should work if dot files are listed explicitly. I've added a test case here: https://github.com/sphinx-doc/sphinx/compare/master...mcmtroffaes:feature/fix_html_extra_path_dot_files which passes. If you simply list a path to a folder, then dot files from that folder will not be copied. I think that's not so surprising (it's in line with all the other folder copy operations elsewhere), but maybe the documentation can be updated at this point to remind folks about .htaccess requiring an explicit path.

@josephcslater Am I correct in guessing that you're not listing .htaccess directly, but instead listed only the folder containing it?

**Comment by josephcslater** [comment]
@mcmtroffaes Yes. I didn't. I've since added it, and it does work. However, this creates a lot of messy complexity in a more complex scenario. To work around, I have to rethink how I structure my website. However, right now, I have a website that includes pages (sub pages) for each of my courses. One link on each course page is to copyrighted resources (distribution legal under education clauses in copyright law). However, I have to keep think "locked down" which I do through an .htaccess file that requires a server level password. I don't want to lock everything down: it's a hassle for a student to have to log in just to see a homework assignment or read other material. So, each time I create such a directory, Not only do I have to remember to add the .htaccess file (which is the means to activate low level security), but I also have to remember to modify the configuration file. The multiple steps are easy to forget given time between actions (I'm human... very much so). I won't forget I have to do one thing, but a second is easy when your mindset (day to day) is that everything I put in these location is copied. 

This isn't all your responsibility, but a bit of explanation of why I do wish this worked. I can't imagine it's worth a lot of work by others. However, as the docs stated that this works, it's a bug if it doesn't. The solution for the community might be to change the docs to say it doesn't, and that these steps need to be taken to copy files starting with a .htaccess

FWIW: The number of folders I'm talking about is on the order of 12 and increasing semi-regularly, while the number of files is a few hundred, a few files added every month.  (thus the reason it's easy to forget the process)

**Comment by josephcslater** [comment]
What would be helpful for me, to be legally conservative, is to have the ability to point to a default .htaccess file to put in every folder of a site, where it would have to be turned off manually. A single complaint would remind me to "unlock" by added a path to the _exception_ list. I have accidentally posted copyright material wide-open because the behavior defaults to a fail to copy the .htaccess file, leaving me legally exposed when I make a mistake.

**Comment by mcmtroffaes** [comment]
Maybe an option to only exclude certain files from copy operations could be added (which would default to excluding all hidden files as it is now, but could be overridden by the user)? I guess that would solve your problem.

**Comment by josephcslater** [comment]
It would. I have to admit, I'm more a user than a programmer in this arena or I would have already pushed a solution.

**Comment by tk0miya** [comment]
> I don't think I'd expect it to expand templates - but maybe there is a use case for it? Anyway, that seems unrelated to the original bug reported here, right?

I think copying dotfiles is not surprising for me.
So I'd want to replace `copy_static_entry()` with new copy function which copies all files in the specified directory including dot files.
I wanted to ask you that the function should expand templates.

We already have `exclude_patterns`. If anyone want to skip copying dotfiles, it will help them.

**Comment by mcmtroffaes** [comment]
Yes, agreed. You suggest that we drop the logic that omits dot files, and replace it with a logic that uses exclude_patterns instead? That seems reasonable to me.

**Comment by josephcslater** [comment]
Having some defaults in exclude_patterns would also have some trivial benefit. For instance, MacOS creates a .DS_Store file in each directory. This is very unlikely to be useful in any copy. However, it also does little harm if copied. For the purposes of Sphinx, one could easily argue that it is irrelevant. I don't know if harm would occur in other operating systems and thus if such a feature (copying . files) would create problems for others. Are their experts on Windows and Linux who could verify that this wouldn't cause problems for current users? Should a warning be given short term about copying .files? I certainly wouldn't want my benefit to result in hard to diagnose issues for others.

**Comment by shimizukawa** [comment]
IMO, 
1. all files in html_extra_path including dot files should be copied by default.
2. exclude_patterns should be applied for copying procedure of html_extra_path.
3. some defaults for exclude_patterns in conf.py would be useful as a usage and it bring a procedure to control copying behavior to user.

**Comment by shirou** [comment]
1. Since dotfiles are _hidden_ files, avoiding them is natural for me.
2. I also understand @tk0miya and @josephcslater because user explicitly specify `html_extra_path` to copy them _all_.
3. @shimizukawa 's idea about adding `.DS_Store`, `.git` or else to `exclude_patterns` default may confuse user if user really want to copy them. (And it causes other argument what kind of files should be added :-P)
4. Document should be more clear to describe the behavior in both case.

I agree to @tk0miya because implementation become clear if omit dotfiles checking. But no strong objection.

**Comment by tk0miya** [comment]
Hi all, thank you for comment.
I'll change the behavior of `html_extra_path`.

@shimizukawa could you change the default value of `exclude_patterns`? I can not determine what is good for default.

**Comment by shimizukawa** [comment]
Finally, I decided to add 'Thumbs.db' and '.DS_Store' as a default of exclude_patterns config value.

**Comment by mcmtroffaes** [comment]
Looks good to me - thanks for your work on this @tk0miya and @shimizukawa! @tk0miya I've submitted an extra commit for your branch to fix some grammar issues.

**Comment by tk0miya** [comment]
Just merged #2237 into master branch now.
Thank you for all your help!

**Comment by josephcslater** [comment]
You guys did all the work. All I did is (gently) complain about software I get to use with no investment on my part not quite behaving the way I had hoped. Then a bunch of people jumped in to help me out, all without knowing me. This is precisely why I explain to my students they should:
- use open source
- support open source by contributing time/money
  You guys rock! Now I need to get back to making my package, which would go faster if I wasn't an amateur in Python!

**Comment by tebanep** [comment]
Something like:

cd docs/
rsync -R **/.htaccess _build/

Could be used to copy .htaccess files inside subdirectories.

**Comment by josephcslater** [comment]
This was actually patched by [#2237](https://github.com/sphinx-doc/sphinx/pull/2237) and is no longer an issue.  

The "problem" with your solution is it adds another step to the build process, beyond `make html` and is something that users would have to learn to add. Thus the patch is better as it supports the default assumption by users that files indeed are copied.
