### ISSUE TITLE
extending reference label

### ISSUE THREAD

**Issue by andreacassioli** [sphinx-doc/sphinx#2025]
I was wondering whether it would be possible and/or commonly useful to extend the reference system as follow: labels may accept a text to be used in order to override section title and in case define arbitrary entry point. For instance, say I want to jump to  a bullet list, I may do

```
.. _bullet_list: list of item

* blah blah
* blah blah blah
```

In the text I only need to say :ref:`bullet_list`. I can imagine the same with rubric. That would also make numref a bit less useful, as one could just put a figure title in there.

**Comment by andreacassioli** [comment]
Any comments? Would be it possible?

**Comment by tk0miya** [comment]
I object to this proposal.
Because Sphinx should not extend syntax of reStructuredText, I think.

If we want to introduce new feature, use directives or roles instead. It's reST way.
So it would be better that adding new directive to wrap block and caption it::

```
.. captioned-container::
   :name: bullet_list
   :caption: list of item

   * blah blah
   * blah blah blah
```

BTW The syntax you shown is already defined in reST. It's called as "indirect hyperlink targets".
It works as alias of existing labels.
http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#hyperlink-targets

**Comment by andreacassioli** [comment]
Hi,
thank you for the comment.

I know understand better how sphinx works and I agree with you, well partially.

My point is I think that Sphinx should provide a clean and simple way to create links to arbitrary positions in a document, with an arbitrary label, not necessary a caption.

I have taken a look to the rest link you provide, but to me is still very unclear and few test I have done leaded me nowhere. I will make a referenced-container directive, I guess you are right on that.

**Comment by tk0miya** [comment]
> My point is I think that Sphinx should provide a clean and simple way to create links to arbitrary positions in a document, with an arbitrary label, not necessary a caption.

We can do it with following code::

```
.. _bullet_list:

* blah blah
* blah blah blah

This is :ref:`a reference to the list <bullet_list>`
```

In this case, we can put arbitary label before bullet list and create links to it.
But the bullet list does not have any captions and titles, so we have to specify the link title on `:ref:` role.

I think captions are required to resolve your request.

Sorry if i misread your comments.

**Comment by andreacassioli** [comment]
Hi again,
thank you for the clarification. Now I see.

However, I definitely want to avoid being forced to write the label on the link. That is very annoying and breaks the way one work. It is also boring when a link is repeated may times. I want the target to know the label, as we do for sections.

**Comment by tk0miya** [comment]
I created sample implementation to resolve this::

```
# put following line into your conf.py
from sphinx.util import ws_re
from docutils import nodes
from docutils.parsers.rst import Directive, directives


class NamedTarget(Directive):
    has_content = False
    required_arguments = 1
    optional_arguments = 0
    option_spec = {'label': directives.unchanged}

    def run(self):
        targetname = ws_re.sub(' ', self.arguments[0].strip())
        node = nodes.target('', '', names=[targetname])
        if 'label' in self.options:
            node['label'] = self.options['label']
        self.state.document.note_explicit_target(node)
        return [node]


def on_doctree_read(app, doctree):
    def lookup_name(id):
        for name, (docname, labelid) in app.env.domaindata['std']['anonlabels'].items():
            if labelid == id:
                return (name, docname)
        else:
            return (None, None)

    labels = app.env.domaindata['std']['labels']
    for node in doctree.traverse(nodes.target):
        if 'label' in node:
            name, docname = lookup_name(node['refid'])
            if name not in labels:
                labels[name] = (docname, node['refid'], node['label'])


def setup(app):
    app.add_directive('target', NamedTarget)
    app.connect('doctree-read', on_doctree_read)
```

It works fine for me. (but I do not test this)
Have a fun :-)

Thanks,

**Comment by andreacassioli** [comment]
I finally find the time to try it.....it works like a charm! I hope one day it will go upstream and be available as standard tool.

Thank you a lot.

**Comment by ideasman42** [comment]
Is this closed because its a **feature-request**?
Or because the functionality isn't being considered for inclusion?

The ability to define the label text on the target would be very useful when linking to bullet-points and definition lists.

Note, I asked about this functionality on SE: http://stackoverflow.com/questions/35347170

**Comment by andreacassioli** [comment]
Hi,
the solution proposed by @tk0miya works well and can help you I guess.

Of course, it would be great to get the upstream
