### ISSUE TITLE
:image target support opening url in a new tab?

### ISSUE THREAD

**Issue by huaiweicheng** [sphinx-doc/sphinx#2032]
In the url below, the browser will go to the url directly when click
![image](https://cloud.githubusercontent.com/assets/4011117/9809298/8bcf0904-5899-11e5-87e4-0de699d8452c.png)?
Does it support opening the url in new tab ?

http://rest-sphinx-memo.readthedocs.org/en/latest/ReST.html#image-and-figure

Many thanks!

**Comment by shimizukawa** [comment]
For now I have no plan to support the feature.
There is a discussion: #1634

**Comment by huaiweicheng** [comment]
Thanks all the same. ^-^
