### ISSUE TITLE
Sphinx HTML builder renders unnecessary script tags

### ISSUE THREAD

**Issue by ClodoaldoPinto** [sphinx-doc/sphinx#2037]
The `Sphinx` HTML builder renders script tags which are in my case unnecessary:

```
<script type="text/javascript" src="_static/jquery.js"></script>
<script type="text/javascript" src="_static/underscore.js"></script>
<script type="text/javascript" src="_static/doctools.js"></script>
```

They add considerable lag to the page load. Is there a way to prevent the builder from rendering these tags?

This is how it is done in the layout.html template from the basic theme:

```
{%- for scriptfile in script_files %}
<script type="text/javascript" src="{{ pathto(scriptfile, 1) }}"></script>
{%- endfor %}
```

It is hard coded in the `StandaloneHTMLBuilder(Builder)` class:

```
# This is a class attribute because it is mutated by Sphinx.add_javascript.
script_files = ['_static/jquery.js', '_static/underscore.js',
                '_static/doctools.js']
```

**Comment by pradyunsg** [comment]
>  Is there a way to prevent the builder from rendering these tags?

The trick I've used is to have a conditional in the template to prevent using those paths.

**Comment by tk0miya** [comment]
Not to load these scripts forcedly, please overwrite `StandaloneHTMLBuilder.script_files` in your conf.py
```
from sphinx.builders.html import StandaloneHTMLBuilder
StandaloneHTMLBuilder.script_files = []
```

But I don't know what will be happened.

Thanks,
