### ISSUE TITLE
Way to tell if a builder produces HTML

### ISSUE THREAD

**Issue by ericholscher** [sphinx-doc/sphinx#2038]
Currently there is lots of code that has to guess if a builder produces HTML, PDF, or other output. A lot of stuff does things like `if 'html' in builder.name` or other quite fragile code. The builders should accept an attribute that tells what the type of output that it produces is, and we should document this as the canonical way to tell if a specific builder if HTML, PDF, etc. Depending on builder names is quite fragile, and doesn't work in many cases (eg. the JSON builder).

**Comment by ericholscher** [comment]
Ah, I see a format on Sphinx Builder's: https://github.com/sphinx-doc/sphinx/blob/master/sphinx/builders/html.py#L69

Perhaps this should be documented?

**Comment by shimizukawa** [comment]
+1.
http://sphinx-doc.org/builders.html indicates `name` and `supported_image_types` field. We should indicate `format` too.

**Comment by shimizukawa** [comment]
Done! http://sphinx-doc.org/builders.html

**Comment by ericholscher** [comment]
Great, thanks :)

On Mon, Sep 14, 2015 at 6:29 PM, Takayuki SHIMIZUKAWA <
notifications@github.com> wrote:

> Done! http://sphinx-doc.org/builders.html
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sphinx-doc/sphinx/issues/2038#issuecomment-140247790.

## 

Eric Holscher
Maker of the internet residing in Portland, Oregon
http://ericholscher.com

**Comment by ericholscher** [comment]
Closing this to get it off the `1.3.2` release list.
