### ISSUE TITLE
Add all options to "build_sphinx" distutils command

### ISSUE THREAD

**Issue by LeoHuckvale** [sphinx-doc/sphinx#2039]
I'm trying to set up a CI/Jenkins job which builds my Sphinx documentation, but I want it to fail when Sphinx reports errors. Please see related StackOverflow question: http://stackoverflow.com/questions/32526150/how-to-deliberately-fail-a-sphinx-build-when-autodoc-fails-an-import

I could do this with the '-W' option in the sphinx-build console script, but it seemed more natural to use 'python setup.py build_sphinx'. However, I found I can't specify the same options in my setup.cfg file as I could by running the console script, nor can I override all of the options in sphinx.application.Sphinx(...).

Is there a reason this is the case, or is it just that these options haven't yet been implemented in sphinx.setup_command.BuildDoc(...)? - I'm happy to try implementing this myself and lodging a pull request.

Thanks!

**Comment by stxlvt** [comment]
+1

I'm facing this issue as well. I use `devpi --with-docs` to build my docs, so I have no direct control of how `build_sphinx` is invoked. I need a config file option to turn warnings into errors, but there is no such option, not in `docs/conf.py` and not in `setup.cfg`.

It seems that overriding the build_sphinx command in setup.py would work, but it would be much cleaner if I could simply set an option in `setup.cfg`.

**Comment by nikicc** [comment]
+1. This would come really handy for those of us who use autodocs.

**Comment by tk0miya** [comment]
It seems `--warning-is-error` option for setup.py was already added (refs: #2663). Closing.
Please file a new issue if you still have a problem related to this.
Thanks,
