### ISSUE TITLE
docutils errors do not cause a Sphinx error with a non-zero exit code

### ISSUE THREAD

**Issue by jayvdb** [sphinx-doc/sphinx#2041]
If there are errors emitted by docutils, they appear in the Sphinx output as "....: ERROR: ...." but they are not treated as a Sphinx error unless `-W` is enabled.

The workaround is to create `docutils.conf` with

```
[general]
halt_level: error
```

**Comment by tk0miya** [comment]
I can't reproduce the problem. Please tell me about the issue in detail (versions, configurations and any examples).

**Comment by tk0miya** [comment]
Now I close this issue.
Please feel free to repoen if you get the same error.

Thanks,
