### ISSUE TITLE
Document how to access metadata

### ISSUE THREAD

**Issue by ericholscher** [sphinx-doc/sphinx#2043]
This section mentions that things are included in "file wide metadata" http://sphinx-doc.org/markup/misc.html#file-wide-metadata -- However, you are never told how to actually _access_ the data in an extension, etc. Is this on `env.meta` or something equivalent?

**Comment by tk0miya** [comment]
It is stored in `env.metadata[docname]` and `doctree[0]` (as nodes.docinfo node).
Does this help you?

**Comment by tk0miya** [comment]
`env.metadata` is already mentioned on our docs:
http://www.sphinx-doc.org/en/stable/extdev/envapi.html#sphinx.environment.BuildEnvironment.metadata

Thanks,
