### ISSUE TITLE
Table column width is mis-calculated for `make latexpdf` with fix for issue #1522

### ISSUE THREAD

**Issue by ssokolow** [sphinx-doc/sphinx#2047]
In Sphinx 1.2.2, my tables render perfectly aside from the duplicated footnote bug mentioned in issue #1522. However, with later _or earlier_ versions of `tabulary.sty` that fix the duplicated footnote bug, the table is forced to 100% width and the left-hand column is given an unacceptably tight word-wrap despite there being plenty of room.

See this comparison:
![tabulary_bug](https://cloud.githubusercontent.com/assets/46915/9980381/a539a5a2-5f65-11e5-917c-2bc935d00d21.png)

Here's the minimized problematic reST example. The `conf.py` should be ordinary enough `sphinx-quickstart` output but let me know if you need it.

I tested both with or without ensuring all cells in the left column had trailing whitespace (it's significant in some markup languages and Vim's syntax highlighter gets confused by it) but there was no difference.

``` rst
+-------------+-------------------------------------+
|Component    |Formats Supported                    |
+=============+=====================================+
|`aurora.js`_ | LPCM, aLaw, µLaw [#f_aurora.js]_    |
+-------------+-------------------------------------+
|`csv.js`_    | Excel-compatible CSV                |
+-------------+-------------------------------------+
|`epub.js`_   | ePub eBooks                         |
+-------------+-------------------------------------+
|`flac.js`_   | FLAC (Free Lossless Audio Codec)    |
+-------------+-------------------------------------+
|`ViewerJS`_  | PDF, OASIS OpenDocument [#f_webodf]_|
+-------------+-------------------------------------+
|`vorbis.js`_ | Ogg Vorbis audio                    |
+-------------+-------------------------------------+

.. _aurora.js: https://github.com/audiocogs/aurora.js
.. _csv.js: https://github.com/okfn/csv.js
.. _epub.js: https://github.com/futurepress/epub.js
.. _flac.js: https://github.com/audiocogs/flac.js
.. _vorbis.js: https://github.com/audiocogs/vorbis.js

.. _ViewerJS: http://viewerjs.org/
.. _WebODF: http://webodf.org/

.. rubric:: Footnotes

.. [#f_aurora.js] Aurora.js is the base framework upon which the other
   listed JavaScript audio codecs depend. However, it has internal support for
   several simple audio formats.

.. [#f_webodf] While strongly beneficial to the goals of this project, use of
   WebODF_ outside of ViewerJS_ to enable collaborative document editing and
   in-document annotation is out-of-scope for this project due to its
   complexity.
```

**Comment by tk0miya** [comment]
I tried this in newest version. 
It seems the problem was already resolved, now.

32d1ebec5 (without duplicated footnote fix):
![sphinx_32d1ebec5](https://cloud.githubusercontent.com/assets/748828/12078884/819b1f32-b266-11e5-9ebb-408775183542.png)
e9aae6563 (with duplicated footnote fix):
![sphinx_e9aae6563](https://cloud.githubusercontent.com/assets/748828/12078883/819aca78-b266-11e5-8a51-4a95acd6e5ac.png)
Sphinx-1.3.3
![sphinx_1 3 3](https://cloud.githubusercontent.com/assets/748828/12078885/819b8486-b266-11e5-9ee7-56446757933d.png)

Now, I close this issue. Please reopen if you found any problem in newest Sphinx.

Thank you for reporting.
