### ISSUE TITLE
Official Sphinx Docs on readthedocs are still using bitbucket

### ISSUE THREAD

**Issue by Callek** [sphinx-doc/sphinx#2049]
I noticed this from

https://bitbucket.org/birkenfeld/sphinx/src/default/doc/devguide.rst which is using bitbucket for issues, despite the move.

Then clicking "edit" from the template brings me to: https://bitbucket.org/birkenfeld/sphinx/src/default/doc/devguide.rst which indicates that read the docs is building from bitbucket not github...

**Comment by shimizukawa** [comment]
Thanks for informing it!
https://readthedocs.org/projects/sphinx/ is dismissed in last several months.

@birkenfeld please give me (`shimizukawa` on rtd) a management permission for it (or remove it).

**Comment by birkenfeld** [comment]
Done!

**Comment by shimizukawa** [comment]
Thanks!

Now close this issue.
