### ISSUE TITLE
:manpage: role uses incorrect style (node)

### ISSUE THREAD

**Issue by Earnestly** [sphinx-doc/sphinx#2060]
When referencing a manual on Linux the notation in groff is to use `.BR ls (1)` which results in **ls**(1). (bold "ls" and roman "(1)")

Currently `:manpage:` simply [adds emphasis](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/roles.py#L32) which is inconsistent with the rest of the [system](http://man7.org/linux/man-pages/man7/man-pages.7.html) manuals.

**Comment by tk0miya** [comment]
Thank you for advice.
We should represents the reference as `nodes.strong`.

> ```
>   Any reference to another man page should be written with the name in
>   bold, always followed by the section number, formatted in Roman
>   (normal) font, without any separating spaces (e.g., intro(2)).  The
>   preferred way to write this in the source file is:
> 
>       .BR intro (2)
> ```

I'll think about this. Which is better change the style in all formats or in man page only.
