### ISSUE TITLE
Type alias declarator not parsed properly

### ISSUE THREAD

**Issue by Rapptz** [sphinx-doc/sphinx#2061]
Hello.

The docs mention that type-alias-declarators are allowed but I can't get it to work in a non-template context. Some examples:

```
.. cpp:type:: template<typename T> ptr = T*

    This one is actually fine.

.. .cpp:type:: cool = int

     This one causes failures.
```

The error:

```
WARNING: Error if typedef:
Type must be either just a name or a typedef-like declaration.
Just a name error: Invalid definition: expected end of definition, got u'= int' [error at 5]
  cool = int
  -----^
Typedef-like expression error: Invalid definition: Expected identifier in nested name. [error at 5]
  cool = int
  -----^
Error if type alias or template alias:
Invalid definition: Expected identifier in nested name. [error at 5]
  cool = int
  -----^
```

I've tried investigating it, and for some reason `_parse_type_using` is failing. The string seems to imply that the `_identifier_re` fails to match but as far as I can tell, that shouldn't be the case.

**Comment by jakobandersen** [comment]
Thanks, I forgot to reset the parsing position, so _parse_type_using was not given the chance to parse "cool" after _parse_type failed.

**Comment by Rapptz** [comment]
That was really quick. Thanks a bunch. You're the best :+1:
