### ISSUE TITLE
Error in "currentmodule", autosummary extension

### ISSUE THREAD

**Issue by keleshev** [sphinx-doc/sphinx#2066]
I'm getting the following error on latest Sphinx from PyPI on Python 2.7, both Mac and Linux:

```
/var/lib/jenkins/jobs/wiki-cb1805f95166/workspace/venv/lib/python2.7/site-packages/sphinx/ext/autosummary/templates/autosummary/class.rst:4: ERROR: Error in "currentmodule" directive:
maximum 1 argument(s) allowed, 3 supplied.

.. currentmodule:: {{ module }}
```

Looks like it interprets `{{ module }}` literally, as 3 arguments, instead of interpolating it first.

**Comment by keleshev** [comment]
One live example is use of `Template` and `Color` in the bundled testing framework: https://github.com/keleshev/Terminal.ml/blob/190cefaa7ddc0fa4c6f254592d8912afa567bd7f/vendor/Test.ml

**Comment by tk0miya** [comment]
It's strange. It seems Sphinx processed a template file of autosummary module.
How did you invoke `sphinx-build`? I guess Makefile or build scripts are not good.

**Comment by tk0miya** [comment]
Any comment? If none, I'll close this later.

**Comment by tk0miya** [comment]
I'm closing this now.
Please feel free to reopen if you still get same error.
Thanks,

**Comment by convoliution** [comment]
I encountered this same error; I determined that for me, it was because Sphinx was finding the venv/ I created in my package directory and was unsurprisingly unable to parse any Python source code from it.

Moving venv/ out of that directory resolved my case. I suspect that adding `'venv'` to `exclude_patterns` in conf.py would have also resolved my case.

**Comment by Caster** [comment]
I had the same problem as @convoliution and can confirm that adding the virtual environment directory to the `exclude_patterns` in `conf.py` solves the issue.

**Comment by tk0miya** [comment]
Thank you for reporting. I understand what happened. If you put venv directory under sphinx project, Sphinx searches source files from it. And it considers a template file of autosummary module as a source file.

As you commented, please mark the venv dir as excluded. Then it will be resolved.
Thanks,
