### ISSUE TITLE
Are the non-minified js file for the search feature required now?

### ISSUE THREAD

**Issue by Naereen** [sphinx-doc/sphinx#2067]
The solution for the issue #1784 might have broken something else:

Now the `latest` `sphinx` version seems to require the `non-minified-js/*-stemmer.js` files, but they are not installed automatically on `PATH/sphinx/search/` if sphinx is installed with `pip` from the live git branch (dunno if the `stable` `pypi` package has the same issue).

Please find attached below [a log of the issue](https://paste.debian.net/314676/) I just encountered (I add to download manually the `non-minified-js/*-stemmer.js` file from [here](https://github.com/sphinx-doc/sphinx/tree/master/sphinx/search/non-minified-js)).
[sphinx-err.log](https://paste.debian.net/314676/)

**Comment by shimizukawa** [comment]
This issue has been fixed on #2114.
