### ISSUE TITLE
Add an option to not use intersphinx references as a fallback

### ISSUE THREAD

**Issue by adamtheturtle** [sphinx-doc/sphinx#2068]
That intersphinx references are used as fallbacks if a reference is not available in a project recently caused us a problem.

We have a site (`latest`) which is the latest build of `master`.

We use intersphinx as follows, so we can link to the latest documentation in some sections:

``` python
intersphinx_mapping = {
    'latest': ('http://doc-dev.clusterhq.com/', None),
}
```

``` rst
Make sure to follow the :ref:`latest documentation <latest:release-process>` when doing a release.
```

Our docs included a label (`.. foo:`) so this reference was available on `latest`.
This label was removed on a branch, along with one of the two references to this label.
In this case we would expect that building the branch would fail, as there is a reference to a label which doesn't exist.
Unexpectedly, the branch built successfully, because the label was found in `latest` as a fall back when it was not found locally. The branch was merged, and then later, when `latest` changed (because `master` was built again) builds stopped working because there was a reference to a non-existent label.

It would be good to have an option to not fall back, maybe something like `nitpicky`.

**Comment by nijel** [comment]
The initial PR adding this is https://github.com/sphinx-doc/sphinx/pull/8981

**Comment by astrojuanlu** [comment]
I know that I'm 6 years late and apparently clusterhq is no more, but for future reference, I just wanted to say that it looks weird to me to have an `intersphinx` mapping to _your own online documentation_. In principle I guess that this should not be needed, but I'd be keen to learn more in case I'm missing anything.

**Comment by adamtheturtle** [comment]
@astrojuanlu I believe that it was so that we could keep old versions of the documentation alive in `<url>/<old-version>` and still link to the "latest" documentation from those old versions where necessary.
