### ISSUE TITLE
cpp:type does not suppurt function types

### ISSUE THREAD

**Issue by webmaster128** [sphinx-doc/sphinx#2069]
At Botan we have a bunch of typedef that are functions. Those are not supported in the docs.

E.g.

```
.. cpp:class:: TLS::Channel

   .. cpp:type:: std::function<void (const byte[], size_t)> output_fn
```

where in the .h we have

```
class BOTAN_DLL Channel
   {
   public:
      typedef std::function<void (const byte[], size_t)> output_fn;
```

produces

```
/home/me/botan/doc/manual/tls.rst:84: WARNING: Invalid definition: "," or ">" in template expected [error at 19]
  std::function<void (const byte[], size_t)> output_fn
```

Tested on Sphinx v1.2.3 (Ubuntu) and v1.3.1 (OS X)

**Comment by webmaster128** [comment]
If you need some input data for unit testing, here you go:

```
   .. cpp:type:: std::function<void (const byte[], size_t)> output_fn
   .. cpp:type:: std::function<void (const byte[], size_t)> data_cb
   .. cpp:type:: std::function<void (Alert, const byte[], size_t)> alert_cb
   .. cpp:type:: std::function<bool (const Session&)> handshake_cb
```

**Comment by jakobandersen** [comment]
I can not reproduce the problem on the development branch. If I remember correctly then those kind of declarations (with function types in them) were not supported before version 1.3.

**Comment by webmaster128** [comment]
Thanks. Could you point me to some changelog note or release version where it is fixed? Then I could confirm and close this one.

**Comment by jakobandersen** [comment]
Specifically the function types as template arguments got supported in version 1.3b1 (search for 'Rewrite of C++ domain' in the changelog (https://github.com/sphinx-doc/sphinx/blob/master/CHANGES)).

**Comment by webmaster128** [comment]
Merci
