### ISSUE TITLE
Add a way to get current namespace and class in C++ domain

### ISSUE THREAD

**Issue by Rapptz** [sphinx-doc/sphinx#2070]
Hello.

The python domain has a way to get the current module and current class to help facilitate with the `autodoc` extension. It would be nice if the C++ domain had something similar to help facilitate similar tools.

I believe the implementation for it should be fairly straightforward (just store it under `domaindata`) but I am not sure if it's a desirable feature. I would appreciate it since I'm working on an autodoc tool for C++ so there is some personal bias on my part.

**Comment by jakobandersen** [comment]
The current scope is already tracked, but in which way do you plan to use the information?

**Comment by Rapptz** [comment]
I must have missed the current scope. Under what key in domaindata is it in?

I'm using the information to have some better context-sensitive autodoc (e.g. taking into consideration the current namespace).

**Comment by jakobandersen** [comment]
It is stored in `env.ref_context['cpp:parentSymbol']`, though if it doesn't exist then the current scope is global scope, which is obtained as `env.domaindata['cpp']['rootSymbol']`. A scope is actually represented by it's corresponding symbol in the global symbol tree that the domain creates.
I can not guarantee that this may not change, so for the sake of maintainability I think it would be best if you define what kind of API you need, instead of relying on the current implementation details.

**Comment by Rapptz** [comment]
Well at the bare minimum it'd be nice to have something like the python domain has (e.g. `py:domain` and `py:class`).

So in C++'s case we would have `cpp:namespace` to point to the current namespace stack (e.g. `ns::some_nested_ns::other_ns`) and `cpp:class` to point to the most recent class specified. 

e.g. .https://github.com/sphinx-doc/sphinx/blob/master/sphinx/domains/python.py#L313

**Comment by jakobandersen** [comment]
From the `cpp:parentSymbol` it is possible to get all that information. Though it can quickly become complicated when you want to use it.
- A scope is not just an identifer, but potentially also a template parameter list and a template argument list. For example, the scope in the description of `.. cpp:class:: template<typename T> SomeClass<T*>`.
- Some scopes don't even have a "normal" identifier, but instead one of the operators. E.g., `.. cpp:func:: T &operator*()`.
- The cast operators have a type as an "identifier". E.g., `.. cpp:func:: operator std::function<bool(HugeTypeExpression&)>() const`.

**Comment by jakobandersen** [comment]
Closing for now as the functionality essentially is there, but may be a bit complicated to use. Please reopen if it becomes relevant to access it.
