### ISSUE TITLE
Same footnote in more than two section titles => LaTeX/PDF Bug

### ISSUE THREAD

**Issue by DenizThatMenace** [sphinx-doc/sphinx#2071]
As a result of issue #633 footnotes are allowed in section-titles.

However, having two sections both referencing the same footnote results in a LaTeX file which cannot be translated into a PDF by `pdflatex`.

For example, try the following simple input.

```
Doc-Title
=========

Chapter 1
*********

still fine [#ft1]_
------------------

foo

Chapter 2
*********

now buggy [#ft1]_
-----------------

bar


.. [#ft1] buggy footnote just fine for first occurence.
```

When calling `make latexpdf` It will fail with the following output:

```
[1] [2]
Chapter 1.

Package hyperref Warning: Token not allowed in a PDF string (PDFDocEncoding):
(hyperref)                removing `\@ifnextchar' on input line 130.

[1] [2]
Chapter 2.
! TeX capacity exceeded, sorry [input stack size=5000].
\reserved@a ->\def \reserved@a 
                               *{\ttl@assign@i {\@tempskipb }}\reserved@a 
l.138 \section{now buggy \footnotemark[1]}

!  ==> Fatal error occurred, no output PDF file produced!
```

The problem seems to be that the second footnote-reference is translated into `\footnotemark[1]` which seems to be illegal in section-titles.

**Comment by tk0miya** [comment]
Fixed at 0719611.

Thank you for reporting.
