### ISSUE TITLE
gettext builder needs smart timestamp regeneration

### ISSUE THREAD

**Issue by techtonik** [sphinx-doc/sphinx#2073]
`make gettext` in 1.3.1 unconditionally overwrites `.pot` files inserting new timestamps even if nothing is changed. Could there be an option to avoid file regeneration if its contents is the same?

**Comment by lehmannro** [comment]
That sounds reasonable!  Maybe we can solve this by making `Builder.get_outdated_docs` a bit more useful?  It seems most builders other than `StandaloneHTMLBuilder` do something very stupid here.

**Comment by techtonik** [comment]
The code that builds `.pot`s - https://github.com/sphinx-doc/sphinx/pull/2074/files 

The easiest way for it would be if builder could parse existing .pot files and compare messages. Otherwise the files need to be built somewhere to compare contents line by line with the exclusion of `POT-Creation-Date: ...` lines.

**Comment by lehmannro** [comment]
As I said, I don't think manually checking during the build phase (let alone based on the _old_ built file) is the best way to address this.  It can be inferred from looking at the inputs, ie. the source files, and then determining which output files need to be rebuilt.

This exists, as pointed out previously, in `Builder.get_outdated_docs` but is vastly under-used.

**Comment by techtonik** [comment]
It is not _old_ build file. We are talking about regeneration of `.pot` files, which are used by translators, who don't want to get false alarms that source for their translation had changed.

**Comment by shimizukawa** [comment]
fixed by #3490

**Comment by techtonik** [comment]
Thanks, @shimizukawa. Is it 1.6 that will get this released?

**Comment by tk0miya** [comment]
No, #3490 is merged into stable branch. So it will be released as 1.5.4.
