### ISSUE TITLE
gettext: need option to set location for .pot files

### ISSUE THREAD

**Issue by techtonik** [sphinx-doc/sphinx#2075]
I need to maintain .pot files in project source tree at `./locale/pot`. Is it possible to create an option to specify the target directory for the .pot build?

**Comment by lehmannro** [comment]
I'm not exactly sure if I understand — you want the `gettext` builder's output to go somewhere else?  Why is configuring the second argument to `sphinx-build` (aptly named `outdir`) not sufficient?

**Comment by techtonik** [comment]
@lehmannro is it possible to specify that argument in conf.py?

**Comment by shimizukawa** [comment]
You can do it by using Makefile / make.bat.

**Comment by techtonik** [comment]
@shimizukawa I'd like to avoid patching these files, because they are regenerated when new Sphinx version comes out. I also don't want to change the output location for `html` files.

**Comment by shimizukawa** [comment]
You can choose whether regenerating Makefile or not. IMO, output location management is a responsibility of Makefile.

**Comment by techtonik** [comment]
@shimizukawa it is not about management of output location, it is about proper localization workflow. See #2073 for other issue. Basically, `html` needs to go into `_build`, which is dropped on every rebuild and `.pot` data need to be stored in `locale/`, committed and shared.
