### ISSUE TITLE
search totally broken with html_search_language = de

### ISSUE THREAD

**Issue by logemann** [sphinx-doc/sphinx#2083]
Hi,

i tried using the search engine with sphinx with "de" set as indexing locale and the results seem totally random. Most words wont get found at all, some were found with fewer results. I changed the indexing locale to "en" and now the search seems correct. 

Dont know what details i can provide because i dont know how the index should look like in german. Dont know if its an index issue at all because the "en" index looks not so different from the "de" one. I suspect something in the code? Sorry. Cant help here without other help. If anyone tells me what to report, i will happily do that.

**Comment by usox** [comment]
I can confirm this issue. The searchtools need lowercase searchterms but unfortunately, the german (imho other languages are affected, too) index builder doesn't perform a `lower()` on the terms like the english one does.
