### ISSUE TITLE
Stylesheets added by Sphinx.add_stylesheet should be updated on rebuild if they are changed.

### ISSUE THREAD

**Issue by ideasman42** [sphinx-doc/sphinx#2090]
Style-sheets aren't copied with the html builder, when doing incremental builds.

http://sphinx-doc.org/latest/extdev/appapi.html#sphinx.application.Sphinx.add_stylesheet

**Comment by shimizukawa** [comment]
Please describe more detail.
If it was happened when you just update css file after previous `make html` command, it is current behavior of sphinx. For now, Sphinx doesn't follow timestamps of extra css/js and user custom theme files.

**Comment by ideasman42** [comment]
I think this is the issue you describe, it will copy the file correctly for a clean build, but after making some edits - `make html` wont update to file at the build destination.

**Comment by shimizukawa** [comment]
OK, I think it's a feature request.

**Comment by tk0miya** [comment]
In my short investigation:
- `Sphinx.add_javascript()` has same issue.
- Could not use `env.note_dependency()` to register them to dependencies.
  - The dependency is used for arbitary docname. but these files are used in whole of document.
  - The function is able to call in reading phase. It could not use in initialization phase...
- HTML builder copies these static files after building documents. They are not copied (updated) if no documents updated.

As quick-hack, adding the css and javascript files as dependencies of master_doc.
Maybe it works. (I know it causes waste rebuilding)

**Comment by andreycizov** [comment]
Can someone deny or acknowledge that a Sphinx builder, given a set of lines in conf.py
```
def setup(app)
    app.add_stylesheet('styles.css')
```

Will _never_ copy the files when doing an HTML build?

**Comment by andreycizov** [comment]
For anyone struggling with it: I have fixed it by putting `styles.css` into `_static` directory and then adding an `html_static_path` line: 

```python
html_static_path = ['_static']

def setup(app):
    app.add_stylesheet('styles.css')
```
I am sorry for spamming the issues of the project with it, but I don't think docs ever mention these two together anywhere, so hard to pin point why it does not work.

**Comment by tk0miya** [comment]
The API doc says:

>The filename must be relative to the HTML static path , or a full URI with scheme.
>http://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx.application.Sphinx.add_js_file

I think this comment describes it.

**Comment by maartenbreddels** [comment]
I got bitten by this when developing an extension/plugin.
I was doing in the extension's setup:

```python
def setup(app)
    app.config.html_static_path.append(glr_path_static())
    app.add_stylesheet('gallery.css')
```

But it was never copying it. I figured, maybe `conf.py`will override it, since it includes `html_static_path = ['_static']` by default.

And yes, if you add it later on, it does get picked up:
```python
def setup(app)
    app.connect('builder-inited', lambda app: app.config.html_static_path.append(glr_path_static()))
    app.add_stylesheet('gallery.css')
```

**Comment by tk0miya** [comment]
@maartenbreddels  Sphinx does not expect that extensions overrides user configuration.
In addition, your case is not related with this issue. Even with your code, Sphinx does not detect the change of the css file.

**Comment by tk0miya** [comment]
@KDMortimer It seems your question is not related with this issue. So please post this question to sphinx-users list; https://groups.google.com/forum/#!forum/sphinx-users .
Thanks,

**Comment by KDMortimer** [comment]
@tk0miya as per your post, I have deleted my comment here and posted it to the sphinx-users list.

**Comment by mike-matera** [comment]
I have the same problem. If I change only static content and do an incremental build the static content is not copied. Here's a workaround: 

Create a handler in `conf.py` that reports `index.rst` as outdated. You might need to change `index` to something else  if you don't have an `index.rst`. It can be any document name without the `.rst`: 

```python3 
def env_get_outdated(app, env, added, changed, removed):
    return ['index']
```

Then add the handler in `setup()`:

```python3 
def setup(app):
    app.connect('env-get-outdated', env_get_outdated)
```

After that incremental builds will always rebuild `index.rst` and the copy will always be done.

**Comment by AA-Turner** [comment]
#1810
