### ISSUE TITLE
intersphinx problem

### ISSUE THREAD

**Issue by huaiweicheng** [sphinx-doc/sphinx#2091]
In my doc project, I use intersphinx to produce hyperlinks to 3rd library as follows:

intersphinx_mapping = {  
'numpy': ('http://docs.scipy.org/doc/numpy/', None),
'scipy': ('http://docs.scipy.org/doc/scipy/reference/', None) 
}

Then in a rst file I wrote
:mod:`numpy`
:mod:`scipy`
:func:`scipy.integrate.odeint`

The question is that why :mod:`scipy` does not change into hyperlink? However, some :func: odeint seems working out.
![image](https://cloud.githubusercontent.com/assets/4011117/10570571/d5725480-7667-11e5-86fc-efaa78fde7d3.png)

Waiting for help. Thanks~

**Comment by huaiweicheng** [comment]
Another problem is that I use intersphinx to ref some builtin function. However, some functios work out while others are not.
It really confuse me.
Should I check the object.inv? How to do that?
![image](https://cloud.githubusercontent.com/assets/4011117/10571600/51bd6006-7673-11e5-808f-09b1e9f661dc.png)

**Comment by huaiweicheng** [comment]
![image](https://cloud.githubusercontent.com/assets/4011117/10579157/1e6c6de2-76a9-11e5-8b97-f758620730d5.png)

Just can not understand why numpy and pandas work out while others do not.

**Comment by tk0miya** [comment]
It seems the `scipy` module is not documented.
```
python -m sphinx.ext.intersphinx http://docs.scipy.org/doc/scipy/reference/objects.inv
```

On the other hand, `numpy` module is documented.
https://github.com/numpy/numpy/blob/master/doc/source/reference/index.rst


If you'd like to refer them, please ask to each project.
Thanks,
