### ISSUE TITLE
sphinx-apidoc fails with Django

### ISSUE THREAD

**Issue by amikrop** [sphinx-doc/sphinx#2095]
I use sphinx-apidoc with my django application, and after I run "make html" I get this error: https://bpaste.net/show/40728fe68140
I tried to add the path in conf.py as well as export DJANGO_SETTINGS_MODULE but the same error occured. I have tried anything I found on the web with no luck.

conf.py https://bpaste.net/show/c10e9d3877bf

traceback https://bpaste.net/show/d2451bcd91fd

the app is this one https://github.com/amikrop/django-uaccounts/ and I put the docs directory right in the root

I even tried

import django
django.setup()

after settings.configure() but still nothing: https://bpaste.net/show/730b6345ee5e

**Comment by amikrop** [comment]
After all I managed to do it by monkeypatching FileDescriptor's `__get__`
in conf.py. First, I needed to be in a Django project, not enough to just be in a "projectless" app. Second, it needed manual setting of environment variable DJANGO_SETTINGS_MODULE, which settings.configure() couldn't do. And third it needed the monkeypatch. These were the lines needed in conf.py:
`sys.path.insert(0, os.path.abspath('..'))`
`os.environ['DJANGO_SETTINGS_MODULE'] = 'myproject.settings'`

`import django`
`django.setup()`

`from django.db.models.fields.files import FileDescriptor`
`FileDescriptor.__get__ = lambda self, *args, **kwargs: self`

I mentioned it for future reference and it would be nice if it could all be documented together.

**Comment by keimlink** [comment]
Defining the `DJANGO_SETTINGS_MODULE` environment variable and calling `django.setup()` is what I also do. But I don't understand why you are expanding `sys.path` and why you are patching `FileDescriptor.__get__`.

**Comment by amikrop** [comment]
Including the directory which contains the app, in sys.path is something I see everyone do in their conf.py for Django projects. Setting DJANGO_SETTINGS_MODULE and django.setup() are two things most people don't do (and I wonder how it works for them without doing those two). Patching FileDescriptor needs to be done for django.models.FileField and django.models.ImageField to work.

**Comment by keimlink** [comment]
Thanks for the explanations @amikrop!

**Comment by timgraham** [comment]
Also reported at https://code.djangoproject.com/ticket/25602. I don't think there's a demonstrated bug in Sphinx here?

**Comment by tk0miya** [comment]
Was this already fixed by django side? If true, I'd like to close this.

**Comment by timgraham** [comment]
This can be closed as far as I'm concerned.

**Comment by tk0miya** [comment]
@timgraham Thank you for comment!
I'm closing this now :-)
