### ISSUE TITLE
Labels before include directives ignore the included header

### ISSUE THREAD

**Issue by PeridexisErrant** [sphinx-doc/sphinx#2096]
Suppose we have `index.rst`, `docs/file.rst` and `scripts/useful.lua`.

`index.rst` contains a link to the script:

```
See also :ref:`useful_script`.
```

`docs/file.rst` contains the label (link target) and an include directive (start-after and begin-before roles omitted for brevity):

```
.. _useful_script:

.. include:: scripts/useful.lua
```

And `scripts/useful.lua` includes it's own documentation:

```
A Very Useful Script
====================
Lorem ipsum, etc.
```

This seems like it should work, but instead it gives `docs/file.rst:10: WARNING: undefined label: useful_script (if the link has no caption the label must precede a section header)`.  It seems that links are being resolved before `include` directives, which in this case would only work if the reference resolver searched included text for the link title.

The current workaround is to include an explicit title in the link, but it's long and ugly by comparison and I'd rather not have to.  More importantly, it's difficult to keep all the client-side links up to date when many may be added by users, and the titles may also change.

```
See also :ref:`A Very Useful Script <useful_script>`.
```

In a project with tens of authors contributing hundreds of scripts across several submodules (DFHack/dfhack), this is not ideal.  I've got every other aspect automated, including generation of pages with the include directives and labels for each, but this a sticking point.  I guess the workaround will do for now, but it's not as pretty as I hoped it would be :(

---

A similar problem, which a fix for the above may also address, is that labels in included .rst files are not found when links are looking for a target.  For example, if the label is moved into `script.lua` - undesirable in my case, but someone must want to - it can't be found at all, and the link still fails.

**Comment by PeridexisErrant** [comment]
...trying to create a truly minimal example to share made the problem vanish.

I'm not sure whether the footnoted issue is also a mirage, but either way I guess this will be available next time someone is searching for a solution.  [PM me!](https://xkcd.com/979)

**Comment by shaloo** [comment]
Thanks, this workaround saved me a lot of debugging time today!
