### ISSUE TITLE
Bookmark on pdf for Korean language is broken

### ISSUE THREAD

**Issue by jumogehn** [sphinx-doc/sphinx#2104]
As the title stated, bookmark of pdf is broken when Korean language tex is used.
And I know how fix this. So I am pasting it below.

Could you please apply this for many Korean users?

Thank you very much!
Journeyer

--- build/latex/sphinx.sty      2015-10-30 23:37:18.702865000 +0900
+++ sphinx.sty  2015-11-01 12:41:54.751111051 +0900
@@ -435,6 +435,7 @@

 % Include hyperref last.
 \RequirePackage[colorlinks,breaklinks,
-                pdfencoding=auto,bookmarks,
               linkcolor=InnerLinkColor,filecolor=OuterLinkColor,
               menucolor=OuterLinkColor,urlcolor=OuterLinkColor,
               citecolor=InnerLinkColor]{hyperref}

**Comment by jumogehn** [comment]
<pre>
--- build/latex/sphinx.sty      2015-10-30 23:37:18.702865000 +0900
+++ sphinx.sty  2015-11-01 12:41:54.751111051 +0900
@@ -435,6 +435,7 @@
 
 % Include hyperref last.
 \RequirePackage[colorlinks,breaklinks,
+                pdfencoding=auto,bookmarks,
                 linkcolor=InnerLinkColor,filecolor=OuterLinkColor,
                 menucolor=OuterLinkColor,urlcolor=OuterLinkColor,
                 citecolor=InnerLinkColor]{hyperref}
</pre>

**Comment by jfbu** [comment]
@Jeonghum Since Sphinx 1.4.2, hyperref is loaded with `pdfencoding=unicode`  (done at commit 0f0d505), except if using `platex` engine (used for Japanese). Is this issue with Korean language fixed since 1.4.2 and can we thus close it?

**Comment by jumogehn** [comment]
I won't be able to test this soon, but this issue remained long time open.
So I am closing this without testing.
Thanks and I am sorry that I cannot test this issue.
