### ISSUE TITLE
Support async method definitions in the py domain

### ISSUE THREAD

**Issue by brettcannon** [sphinx-doc/sphinx#2105]
Python 3.5 adds async methods. It would be great to has a directive like `.. async::` to define a method as asynchronous. Not sure how to render it since `def` isn't rendered for `.. method::`, but maybe `await` can be used to denote the asynchronous method since `await` is appropriate for  the method call?

**Comment by Rapptz** [comment]
Libraries such as `aiohttp` and I believe even the Python stdlib themselves use something akin to [this](https://github.com/KeepSafe/aiohttp/blob/master/docs/aiohttp_doctools.py). I suppose it should be fairly easy to add something like this to the main Sphinx py domain.

The actual Python stdlib has other useful ones for [decorators and the such](https://github.com/python/cpython/blob/7e780dc4a5eb19bc5698196ee2f69b3a88b27342/Doc/tools/extensions/pyspecific.py#L123).

**Comment by tk0miya** [comment]
Done in #6295.
Thanks,
