### ISSUE TITLE
[napoleon] rendering of google-style class attributes

### ISSUE THREAD

**Issue by carlodri** [sphinx-doc/sphinx#2115]
I am puzzled as to why this docstring:

``` python
class FastMovie(object):
    '''This is the main class that represents a FAST movie

    Args:
        file_name (str): the name of the .h5 file to be opened
        x_phase (int): the x-phase shift to be applied. Defaults to the value in the metadata

    Attributes:
        data (1darray): the FAST data
        metadata (dict): all the metadata in the .h5 file
    '''
```

etc...

is rendered like this in the html output default theme:

![image](https://cloud.githubusercontent.com/assets/5230366/11119770/20d4bf84-894c-11e5-91aa-c5e7bae96975.png)

The same happens when rendering to latex. Is this an issue with the `napoleon` extension? I'm using `sphinx` `v1.3.1`.

**Comment by RobRuana** [comment]
I believe this is being rendered correctly as of Sphinx v1.3.1. What specific issues do you have with the rendered output?

Note: the rendering of attributes has changed slightly in the most recent (unreleased) version of Sphinx. Attribute types are rendered on the same line as the Attribute description, so it will look like this:

**data**
  _1darray_ - the FAST data

**metadata**
  _dict_ - all the metadata in the .h5 file

**Comment by carlodri** [comment]
well, actually I saw [this](http://zulko.github.io/moviepy/ref/VideoClip/VideoClip.html#videoclip) and I liked it much better (and it's very different from my output). 

[EDIT: I just saw that the example I linked uses `numpydoc`, not `napoleon`, I don't know if this matters...]

It happens that classes can have a large number of attributes and the layout I deemed buggish is especially distracting and space-consuming (at least to me...), whereas the tabular-like output looks really neat.

**Comment by carlodri** [comment]
A more fundamental question I have is: who governs this behavior? Is it `sphinx`, the specific theme I'm using, or `napoleon`?  Thinking about it, `napoleon` should just be a parser to reStructuredText, right? So it should have nothing to do with the way the attributes are formatted. I cannot decide who to blame between `sphinx` and the output theme.... Can you help me @RobRuana ?

**Comment by RobRuana** [comment]
Yes, you are correct that ultimately the theme is what determines the visual styling. I think the page you linked is using the [sphinx read the docs theme](https://github.com/snide/sphinx_rtd_theme). I agree that it's an appealing and readable theme. You may want to give that a try.

I am going to close this issue, but please feel free to reopen it if you find napoleon is interfering with any other themes.

**Comment by carlodri** [comment]
Thanks for your feedback @RobRuana. I have tried also the RTD theme, but the rendering is the same as the one I reported (i.e. no tabular display of attributes). I will head to the sphinx_rtd_theme repo and post an issue there...

**Comment by RobRuana** [comment]
Before posting to the sphinx_rtd_theme repo, try doing this first: set `napoleon_use_ivar = True` in your `conf.py`. That will slightly alter how the attributes are rendered, and may get you what you want.

**Comment by carlodri** [comment]
Thanks, I tried right away, and here is what I get with `napoleon_use_ivar = True` flag:

![screen shot 2015-11-15 at 21 44 16](https://cloud.githubusercontent.com/assets/5230366/11170937/14b601ec-8be3-11e5-868f-ef2177208aae.png)

and here is what I get with `napoleon_use_ivar = False`

![screen shot 2015-11-15 at 21 45 19](https://cloud.githubusercontent.com/assets/5230366/11170907/696a26d8-8be2-11e5-8a9d-c67bbcf7d935.png)

It is definitely much better (compact and readable), but still different from the tabular view I saw at the link above...
I'm too ignorant about the inner workings of `napoleon` (e.g. what does `ivar` do?) so still don't quite get the source of these differences... after all, a class Attribute is a class Attribute...

**Comment by RobRuana** [comment]
Okay, that project is using the numpydoc extension to render the tabular output.

If that is the really the look you are going for, you could convert your docs to use the NumPy format and then use the numpydoc extension, plus the sphinx_rtd_theme.

**Comment by drorata** [comment]
I stumbled across this issue, and I'm a little confused. The addition of `napoleon_use_ivar = True` indeed improved the look of the output, but instead of `Attributes` what rendered is `Variables`. Is it expected and make sense?

**Comment by rmjarvis** [comment]
When trying to improve Napoleon's rendering of Attributes, I found [this page](https://michaelgoerz.net/notes/extending-sphinx-napoleon-docstring-sections.html) by Michael Goerz to be exactly what I wanted.  Just cross-posting here in case others find it helpful.
