### ISSUE TITLE
Heading with reference causes Latex build error

### ISSUE THREAD

**Issue by fushar** [sphinx-doc/sphinx#2118]
If we use reference in a heading, like this 2-file project:

---

`foo.rst`:

```
.. _foo:

Foo
===

Foo!
```

`index.rst`:

```
Index
=====

:ref:`Reference to Foo <foo>`
-----------------------------

Foo is bar.
```

---

then `pdflatex` gives compile error:

```
! Missing \endcsname inserted.
<to be read again> 
                   \node@class@name 
l.133 ...span{xref,std,std-ref}{Reference to Foo}}
```

**Comment by tk0miya** [comment]
With Sphinx-1.3.3, I can't reproduce this problem.
Please try again and let me know if you got same error.
