### ISSUE TITLE
anchor mathjax formulas

### ISSUE THREAD

**Issue by pacija** [sphinx-doc/sphinx#2120]
Hi,

is there a way to create anchors on mathjax formulas?

Thank youn in advance.

**Comment by andreacassioli** [comment]
I agree that would be quite interesting...

**Comment by tk0miya** [comment]
You can do it with label syntax.

```
.. _theFormula:

.. math:: \sqrt{x + y}

blah blah blah

:ref:`refer the formula <theFormula>`
```

Is this helps you?
