### ISSUE TITLE
while  builds the API documentation from the source code

### ISSUE THREAD

**Issue by mvnnn** [sphinx-doc/sphinx#2123]
bhautik-Inspiron-3537 docs # make html

sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.3.1
/home/bhautik/Desktop/GSOC/astropy/astropy/astropy_helpers/astropy_helpers/sphinx/conf.py:156: UserWarning: matplotlib's plot_directive could not be imported. Inline plots will not be included in the output
  "Inline plots will not be included in the output")

Exception occurred:
  File "conf.py", line 44, in <module>
    from astropy.extern import six
ImportError: No module named astropy.extern
The full traceback has been saved in /tmp/sphinx-err-sJMCAW.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at https://github.com/sphinx-doc/sphinx/issues. Thanks!
make: **\* [html] Error 1

**Comment by shimizukawa** [comment]
I guess `astropy` or `astropy.extern` is not installed in your environment. Please check the astropy documentation building procedure.
