### ISSUE TITLE
Can't get ``imported-members`` to work.

### ISSUE THREAD

**Issue by amueller** [sphinx-doc/sphinx#2128]
Following the discussion at #1892 I tried to make the scikit-learn docs build using the `imported-members` flag.

I tried autodoc_default_flags = ['members', 'inherited-members', 'imported-members'] but that didn't include any additional classes. I also just did autodoc_default_flags = ['imported-members'] with the same result.  (version 1.3.1)

Did I misunderstand anything? Were there changes to this in master?
And is there a timeline for a release?

**Comment by veox** [comment]
`:imported-members:` works for me when the package's `__init__.py` imports classes from sub-modules; the classes are meant as an interface to the module's provided functionality. E.g.:

``` python
# krakenex/krakenex/__init__.py
from .api import API
from .connection import Connection
__all__ = ['API', 'Connection']

# krakenex/doc/source/index.rst
.. automodule:: krakenex
   :members:
   :imported-members:
```

-----

@amueller As I understand, you want to document [sub-modules in scikit-learn's `__all__`](https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/__init__.py#L60), correct?.. JIC, I haven't found a way to do it (yet).

**Comment by amueller** [comment]
I think what I wanted to do is possible in 1.3.2. I'm not sure how it related to that flag.

**Comment by veox** [comment]
Is the issue OK to close then ? ;)

**Comment by amueller** [comment]
Let's close as I don't have time to investigate now and the original problem is solved. We can always reopen.
