### ISSUE TITLE
Chapter 0?

### ISSUE THREAD

**Issue by mixmastamyk** [sphinx-doc/sphinx#2129]
Very geeky request, I know, sorry about that.

I would like to have a chapter 0 for the intro to my geeky book.

Thanks for the great doc tool!

**Comment by xuhdev** [comment]
You can add the following to `preamble`  in `latex_elements` option in `conf.py`:

``` latex
\setcounter{chapter}{-1}
```

**Comment by mixmastamyk** [comment]
Thank you.  I also found a sectnum directive to do it.
