### ISSUE TITLE
unimplemented merge_domaindata in <class 'sphinx.domains.cpp.CPPDomain'>

### ISSUE THREAD

**Issue by jschueller** [sphinx-doc/sphinx#2130]
When enabling parallel builds for my projects I encountered the following error:

```
NotImplementedError: merge_domaindata must be implemented in <class 'sphinx.domains.cpp.CPPDomain'> to be able to do parallel builds!
```

Indeed, it's not implemented:
sphinx/domains/cpp.py

```
# merge_domaindata(self, docnames, otherdata):
         # TODO: merge rootSymbol
```

There's a class Symbol in sphinx/domains/cpp.py too:

```
class Symbol(object):
...
    def __init__(self, parent, identifier,
                 templateParams, templateArgs, declaration, docname):
        self.parent = parent
        self.identifier = identifier
        self.templateParams = templateParams  # template<templateParams>
        self.templateArgs = templateArgs  # identifier<templateArgs>
        self.declaration = declaration
        self.docname = docname
        self._assert_invariants()

        self.children = []
        if self.parent:
            self.parent.children.append(self)
        if self.declaration:
            self.declaration.symbol = self
        # add symbols for the template params
        # (do it after self.children has been initialised
        if self.templateParams:
            for p in self.templateParams.params:
                if not p.get_identifier():
                    continue
                decl = ASTDeclaration('templateParam', None, None, p)
                nne = ASTNestedNameElement(p.get_identifier(), None)
                nn = ASTNestedName([nne], rooted=False)
                self._add_symbols(nn, [], decl, docname)
```

How do I proceed ?

**Comment by jakobandersen** [comment]
Thanks for the report. I disabled the parallel build support recently due to some major changes (to gain template support). I'm working on implementing the merging, but have not had time to finish it yet.
The current "solution" is unfortunately to not do parallel builds when the C++ domain is in use.

**Comment by jschueller** [comment]
@jakobandersen, thanks for your reply.

Glad someone is working on this, parallel builds would be very appreciated for large projects.

My doc is generated from python files, why is there some cpp involved ? is this enabled by default ?

I tried removing the cpp keyword from numpydoc extension doesn't but it doesn't change anything;

```
diff --git a/python/doc/sphinxext/numpydoc/linkcode.py b/python/doc/sphinxext/numpydoc/linkcode.py
index d635b81..ed6c78b 100644
--- a/python/doc/sphinxext/numpydoc/linkcode.py
+++ b/python/doc/sphinxext/numpydoc/linkcode.py
@@ -42,7 +42,6 @@ def doctree_read(app, doctree):
     domain_keys = dict(
         py=['module', 'fullname'],
         c=['names'],
-        cpp=['names'],
         js=['object', 'fullname'],
     )
```

**Comment by jakobandersen** [comment]
Hmm, for some reason I thought the merging would only be called when needed. I have just pushed a 'fix' (c286917f534e2e22285dc199162ac8fe934f16cf), so Sphinx only stops if you have actually used the C++ domain and is using parallel builds. Does the commit also fix your case?

**Comment by jschueller** [comment]
@jakobandersen Yes, the error is gone.

**Comment by jschueller** [comment]
@jakobandersen, but now, after about 50% of the reading step, 4 sphinx-build processes are starting to slowly grow from 1-2% constant until now ram usage to 10, 20, 30% and it ends in swaping (I have 12 gigs of ram)!
I suspect there's a race condition somewhere, and it's the same when disabling numpydoc. Did you experience speedups with parallel builds ?
Without parallel build, the memory usage is reasonable and goes from 1.5% to 3% at the end of the reading step.
On the other end, I got a speedup on the write step, but it crashes again:

```
Exception occurred:
  File "/home/schueller/.local/lib/python2.7/site-packages/Sphinx-1.4a0.dev_20151125-py2.7.egg/sphinx/util/parallel.py", line 114, in join
    raise SphinxParallelError(*result)
SphinxParallelError: IOError: [Errno 22] Invalid argument
```

**Comment by jakobandersen** [comment]
Great that the fix works, though unfortunately I don't know what goes on with the memory consumption and the new error. It would be great if you can open a new issue with the problems. Thanks again for the reports.
