### ISSUE TITLE
Man page builder should escape words starting with a dot

### ISSUE THREAD

**Issue by rhertzog** [sphinx-doc/sphinx#2131]
See https://github.com/django/django/pull/5720 for an example a manual page generated with Sphinx that suffers from the lack of escaping of words starting with a dot... In particular when they end up at the start of a line and are interpreted as a groff command. When this happens and when the word is not a valid groff command the whole line is not displayed.

I found out that escaping such words involves prepending `\&` before the word.

**Comment by tk0miya** [comment]
This is a bug of docutils.
`rst2man.py` ignores lines starts with dot too.

I reported the problem at https://sourceforge.net/p/docutils/bugs/289/ .
Please watch the issue.
