### ISSUE TITLE
Unexpected automatic reference to constructor in C++ domain

### ISSUE THREAD

**Issue by ngladitz** [sphinx-doc/sphinx#2133]
Given e.g.:

```
.. cpp:class:: Test

    My class Test

    .. cpp:function:: Test()   

        My constructor

    .. cpp:function:: void test(Test const& other)

        Some function that takes another Test object
```

Using html output the "Test" in "void test(Test const& other)" links to the constructor function named "Test()" rather than the class "Test".

I think it should be the later?

**Comment by jakobandersen** [comment]
Thanks for the bug report, you are completely right.

**Comment by ngladitz** [comment]
That was quick! Thank you very much.
