### ISSUE TITLE
Figure caption with reference causes latex build error

### ISSUE THREAD

**Issue by hagenw** [sphinx-doc/sphinx#2134]
If you include references in your figure like

``` rst
.. figure:: img/example.png

    This is the figure caption with a reference to [AuthorYear]_.

.. [AuthorYear] Author, Title, Year
```

The latexpdf builds fails with:

```
<use example.png> <use example.png>)
! Incomplete \iffalse; all text was ignored after line 6576.
<inserted text> 
                \fi
```

This issue maybe related to #2118 and/or #2094.

**Comment by xuhdev** [comment]
@tk0miya Rather than removing the anchor, I think my solution in mcmtroffaes/sphinxcontrib-bibtex#92 is better: generate `\renewcommand{\phantomsection}{}` at the beginning of each `figure` and `table` environment. The anchor is still there and there is no loss.

**Comment by tk0miya** [comment]
@xuhdev Thank you for your advice. I'll check it in next weekend!

**Comment by xuhdev** [comment]
@tk0miya I guess we have to reopenthis again?

**Comment by xuhdev** [comment]
@tk0miya I now have a simpler solution, which is similar to [this line](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/writers/latex.py#L1290): do not generate `\phantomsection` in figure and table captions.

**Comment by xuhdev** [comment]
Never mind, forget what I said---the line I referred to removes the anchor. Sorry. I think `\renewcommand{\phantomsection}{}` is still the best solution.

**Comment by tk0miya** [comment]
@xuhdev Sorry for late response. I'd just read your suggestion now.

At 32b483d, I removed `\phantomsection` from captions.
In your suggestion, the macro will not be removed, but be invalidated.

I think there is no differences between these solutions.
Please tell me what is your solution better than current implementation.

**Comment by xuhdev** [comment]
@tk0miya Yes, you are right. It seems to be my local setup issue. Sorry for the noise, now I think the issue was perfectly solved.

**Comment by tk0miya** [comment]
I'm relieved to hear that. Thank you for your support.
