### ISSUE TITLE
admonition + class => different rendering

### ISSUE THREAD

**Issue by lyrixx** [sphinx-doc/sphinx#2137]
Hello.

I have the following markup:

```
admonition
""""""""""

with class
==========

.. admonition:: Please give us feedback
   :class: feedback

    Hello, give me some feedback

without class
=============

.. admonition:: Please give us feedback

    Hello, give me some feedback
```

I expected to have the same HTML genrerated (except the class, obviously), but it's not:

**With class**

``` html
              <div class="feedback admonition">
                <p class="first admonition-title">Please give us feedback</p>
                <blockquote class="last">
                  <div>Hello, give me some feedback</div></blockquote>
                </div>
              </div>
```

**without class**

``` html
                <div class="admonition-please-give-us-feedback admonition">
                  <p class="first admonition-title">Please give us feedback</p>
                  <p class="last">Hello, give me some feedback</p>
                </div>
```

I don't understand why if I specify a `class`, the content in not wrapped in a `p` anymore, but in a `blockquote + div` ?

**Comment by lehmannro** [comment]
Your `Hello, give...` paragraph is actually indented by one more space than the `:class:` option.  This makes it a [block quote](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#block-quotes), whereas it is regular content in the other case.

Please consult [sphinx-users](https://groups.google.com/d/forum/sphinx-users) for other questions on reStructuredText.

**Comment by lyrixx** [comment]
Thanks for your feedback ;)
