### ISSUE TITLE
Proposal: Using PyLaTeX to generate LaTeX

### ISSUE THREAD

**Issue by JelteF** [sphinx-doc/sphinx#2138]
I created a library to generate LaTeX code in a nice simple and readable fashion. https://github.com/JelteF/PyLaTeX

I was wondering if you guys would like to use it to generate the LaTeX code generated by Sphinx. It can even be partially used, since all objects have `dumps` method, which converts them to a string.

**Comment by tk0miya** [comment]
To introduce your package, we need to refactor whole of latex writer.
But we don't have enough time to do that.
So I decided we don't switch to PyLaTeX at this moment.

Thank you for proposal.
