### ISSUE TITLE
How can I disable ``imported-members``?

### ISSUE THREAD

**Issue by lsaffre** [sphinx-doc/sphinx#2144]
I cannot build the docs for one of my projects with version 1.3.2 because I did not find out how to disable the `imported-members` of autodoc. I tried to put `autodoc_default_flags = ['no-imported-members']`to my conf.py without success. 
I need to disable it because my source code does `from django.db.models import Q`, and the docstring of that class `Q` contains invalid syntax which causes a warning (and I want to turn warnings into errors (`-W` option).
I use autodoc indirectly via autosummary.

**Comment by shimizukawa** [comment]
I think this issue is invalid because the real problem is in autosummary which was fixed in #2336. If true, please close this issue. Otherwise, please let me know the problem what you get.

**Comment by lsaffre** [comment]
I started to try to write a show case that demonstrates the problem. But it is not easy. I will post my showcase here when i got it to work.

**Comment by lsaffre** [comment]
Yes, you were right, this problem is fixed with #2336. I do have another problem yet, but it seems to be only with the functools.partial function. I will create a new ticket for this.
