### ISSUE TITLE
cpp:enumerator is broken

### ISSUE THREAD

**Issue by ngladitz** [sphinx-doc/sphinx#2145]
e.g.

```
.. cpp:enum:: Foo

    .. cpp:enumerator:: Bar

```

Fails with:

```
Exception occurred:
  File "/usr/local/lib/python2.7/dist-packages/sphinx/domains/cpp.py", line 3450, in _add_enumerator_to_parent
    s = targetSymbol.find_identifier(symbol.identifier)
TypeError: find_identifier() takes exactly 3 arguments (2 given)
```

**Comment by jakobandersen** [comment]
Thanks for reporting this. It was a recent refactoring error. Though the commit also fixes a lookup bug with enumerators in unscoped enums:

``` rst
.. cpp:enum:: Foo

    .. cpp:enumerator:: Bar

Reference to ``Foo::Bar`` via the unscoped name: :cpp:any:`Bar` (didn't generate the correct link before)
Reference to ``Foo::Bar`` via the scoped name: :cpp:any:`Foo::Bar`
```

**Comment by ngladitz** [comment]
Thanks. I don't know if this is related in any way but sphinx seems to have become very slow in this context.
I haven't taken the time to actually let it finish but aborting a run seems to suggest that a lot of time is spend here:

```
  File "/usr/local/lib/python2.7/dist-packages/sphinx/domains/cpp.py", line 3456, in _add_enumerator_to_parent
    declClone = symbol.declaration.clone()
  File "/usr/local/lib/python2.7/dist-packages/sphinx/domains/cpp.py", line 478, in clone
    return deepcopy(self)
```

Sorry I don't (yet) know how to properly debug/profile python.

**Comment by jakobandersen** [comment]
Thanks for catching that (it was present before as well). The declarations know about their symbol, so the line you found basically makes a copy of the complete symbol table. My test case runs way faster, is it fixed in yours as well?

**Comment by ngladitz** [comment]
Yes, thank you! It runs much faster now.

**Comment by jakobandersen** [comment]
Great!
