### ISSUE TITLE
cpp:function trouble parsing pointer to member arguments

### ISSUE THREAD

**Issue by ngladitz** [sphinx-doc/sphinx#2146]
Given e.g. this nonsensical C++ snippet:

```
struct MyClass { int member; };

void my_function(int MyClass::* parameter);

int main() { my_function(&MyClass::member); }
```

Based on which I've got e.g. this documentation:

```
.. cpp:function:: void my_function(int MyClass::* parameter)

    my_function does this and that.
```

I get the following diagnostic:

```
index.rst:3: WARNING: Error when parsing function declaration:
If no return type {
Invalid definition: Expected identifier in nested name, got keyword: void [error at 4]
  void my_function(int MyClass::* parameter)
  ----^
} else if return type {
Invalid definition: Expecting "," or ")" in parameters_and_qualifiers, got "*". [error at 30]
  void my_function(int MyClass::* parameter)
  ------------------------------^
}
```

Unrelated to the main issue but the line reference in the diagnostic does not seem to correspond to the exact location of the parsing problem (which is in line 1 rather than 3).

**Comment by jakobandersen** [comment]
Pointers to members and pointers to member functions should now work. I also think the line number problem has been resolved. @ngladitz can you confirm this?

**Comment by ngladitz** [comment]
Thanks! Both issues seems to be fixed for me.

**Comment by jakobandersen** [comment]
Great, thanks!
