### ISSUE TITLE
[PATCH] Email role with obfuscation

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#215]
This extension provides an email role that obfuscates addresses in HTML.

Usage:

:email:`Name Surname <user@myplace.org>` -> renders as "Name Surname" with the appropriate mailto link

:email:`user@myplace.org` -> renders as "user@myplace.org" with the
appropriate mailto link

I make use of

http://pypi.python.org/pypi/bud.nospam

that encodes the e-mail address using ROT13 and generates a javascript
snippet such as:

```
#!html


 <p><script type="text/javascript">document.write(
             "<n uers=\"znvygb:fgrsna\100fha\056np\056mn\">Fgrsna inaqre Jnyg <\057n>".replace(/[a-zA-Z]/g,
             function(c){
               return String.fromCharCode(
               (c<="Z"?90:122)>=(c=c.charCodeAt(0)+13)?c:c-26);}));
               </script></p>
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/215
- Originally reported by: [sjvdwalt](https://bitbucket.org/sjvdwalt)
- Originally created at: 2009-07-07T14:17:15.762

**Comment by shimizukawa** [comment]
_From Pedro Algarvio on 2011-01-29 17:34:09+00:00_

Released on behalf of Kevin Teague:

  http://pypi.python.org/pypi/sphinxcontrib-email

**Comment by teake** [comment]
Could the PyPI release be updated? The version on https://github.com/thewtex/sphinx-contrib/blob/master/email/sphinxcontrib/email.py works for Python 3, but the old one on PyPI doesn't.

**Comment by shimizukawa** [comment]
`sphinxcontrib-email` is not managed by sphinx-doc/sphinx repository.
Please contact to the owner of sphinxcontrib-email package.

**Comment by teake** [comment]
Will do, thanks for the quick reply.
