### ISSUE TITLE
cpp:type reference enhacement

### ISSUE THREAD

**Issue by ngladitz** [sphinx-doc/sphinx#2151]
Given index.rst:

```
.. toctree::

    test1
    test2
```

test1.rst:

```
======
Test1
======

.. cpp:type:: std::string my_type

.. cpp:function:: void foo(my_type v)

```

test2.rst:

```
======
Test2
======

.. cpp:type:: std::string my_type

.. cpp:function:: void bar(my_type v)

```

The "my_type" reference in both the foo() and bar() function signatures point at the cpp:type directive in test1.rst.

While I don't think this is technically wrong (also given that the typedefs are identical) it would be nice if a reference to the cpp:type in the same file / scope could be preferred.

e.g. my_type in foo() would point to cpp:type in test1.rst and my_type in bar() would point to cpp:type in test2.rst

**Comment by jakobandersen** [comment]
I'm not sure this is a good idea. Essentially you are documenting `my_type` twice, which seems a bit strange. If it were really two different types, but you just don't want their individual namespace to show, then you can do something like

``` rst
======
Test1
======
.. cpp:namespace:: NS1

.. cpp:type:: std::string my_type

.. cpp:function:: void foo(my_type v)

======
Test2
======
.. cpp:namespace:: NS2

.. cpp:type:: std::string my_type

.. cpp:function:: void bar(my_type v)
```

**Comment by ngladitz** [comment]
In my case the typedefs are identical (same namespace).
The directives are auto-generated from C++ headers where one .rst corresponds to one header.

I will (probably) not add any hand written documentation to these cpp:type directives given that for my use case the directive's head is sufficient documentation in itself.

From the C++ compiler's point of view multiple typedefs can declare the same typedef-name as long as the type being referred to stays the same.

The references as they are being generated certainly aren't erroneous as they are.
I'd just prefer them to be closer in context.

If this would complicate the implementation unnecessarily or generally doesn't map to other use cases beyond my own I'd be OK with this issue being closed.

**Comment by jakobandersen** [comment]
It would definitely be a complication, but maybe not an impossible one. Though, before considering it we first need to find out what should happen in all cases. Should the same lookup logic apply to in-text references (the :cpp:*: roles)? How should lookup work when the same rst file has multiple identical declarations?
The most complicated case is probably what should happen when a reference is needed and there are multiple matches, but none in the same rst file.

**Comment by ngladitz** [comment]
> Should the same lookup logic apply to in-text references (the :cpp:*: roles)? 

I think preferably, yes.

> How should lookup work when the same rst file has multiple identical declarations?

For my use case that would not happen though I think I would prefer the last declaration before the current reference (following the mantra the closer the more relevant).

> The most complicated case is probably what should happen when a reference is needed and there are multiple matches, but none in the same rst file.

Hm yes I haven't thought that case out properly.

For my use case I would like it if it could pick a declaration from the same directory (as in filesystem location of the .rst; which corresponds to the filesystem layout I have for the headers).

If that also leaves multiple or no matches in the current directory I would be fine with it picking up any remaining declaration.

I can see how that is likely not transferable to other use cases.

**Comment by jakobandersen** [comment]
Closing for now. Using ``cpp:type`` in a single place with the documentation and then ``cpp:alias`` for the other places may a reasonable solution.
