### ISSUE TITLE
NotImplementedError: Unknown node: inline in line 344 of manpage.py

### ISSUE THREAD

**Issue by mcepl** [sphinx-doc/sphinx#2154]
When trying to build documentation for `python-hypothesis` 1.11.2 on RHEL 7 (python-sphinx-1.1.3-9) I got `NotImplementedError: Unknown node: inline in line 344 of manpage.py` error. Log attached.

[sphinx-err-Mn5q5o.log.txt](https://github.com/sphinx-doc/sphinx/files/51915/sphinx-err-Mn5q5o.log.txt)

I am not sure whether https://groups.google.com/forum/#!topic/sphinx-users/tkByKOJR2Zw has anything to do with it. I expect that this might be fixed in the more recent version of sphinx, so if you can just point me to the patch which resolves I would be grateful. Thank you.

**Comment by tk0miya** [comment]
It seems the bug was already fixed. Could you try current version?

**Comment by mcepl** [comment]
> I expect that this might be fixed in the more recent version of sphinx, so if you can just point me to the patch which resolves I would be grateful.

**Comment by shimizukawa** [comment]
@mcepl  0ef7a0a7 is.

**Comment by tk0miya** [comment]
Now this issue is already resolved I think.
Now, I close it. If you still have any problem, please reopen again.

Thanks.
