### ISSUE TITLE
Issue log messages from jinja template

### ISSUE THREAD

**Issue by eli-collins** [sphinx-doc/sphinx#2157]
It'd be helpful if there was a way to call app.warn() / builder.warn() from jinja template (maybe  .debug() and .info() as well).  This would be particularly helpful for theme development...  I've got a .css_t file which does some parsing / numeric calculations, and would like to be able to display a cmdline warning to the user that some of the theme.conf inputs couldn't be parsed / were invalid.

E.g:

``` jinja2
{% set theme_var = 'notanumber' %}
{% if not theme_var|float %}
    {{ sphinx_warning("theme_var must non-zero float: %r"|format(theme_var)) }}
{% endif %}
```

Something further, like an ability to abort compilation with an error message, would be icing, but looking at jinja2glue.py's environment setup, it looked like inserting builder.warn() into the jinja environment wouldn't be hard, presuming there weren't security / design considerations I'm not aware of.

**Comment by tk0miya** [comment]
Fixed by #4751 
Thank you for your proposal!
