### ISSUE TITLE
test_latex_build.test_footnote fails (on Py3.4) on Win10

### ISSUE THREAD

**Issue by takaakiaoki** [sphinx-doc/sphinx#2158]
test_latex_build.test_footnote fails with py3.4 on windows 10 by this command,

```
c:\sphinx\tests > python run.py -I py35 -d -m test_footnote test_build_latex.py 2> testlog.txt
```

The contents of testlog.txt is following,

```
F
======================================================================
FAIL: test_build_latex.test_footnote
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Tools\python\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Users\aoki\work\sphinx_develop\sphinx\tests\util.py", line 248, in deco
    func(app, status, warning, *args2, **kwargs2)
  File "C:\Users\aoki\work\sphinx_develop\sphinx\tests\test_build_latex.py", line 309, in test_footnote
    assert '\\footnote[1]{\nnumbered\n}' in result
nose.proxy.AssertionError: 
-------------------- >> begin captured stdout << ---------------------
% Generated by Sphinx.

\def\sphinxdocclass{report}

\documentclass[letterpaper,10pt,english]{sphinxmanual}

\usepackage[utf8]{inputenc}

(skip)

 print(<_io.StringIO object at 0x0000000005C3F4C8>.getvalue())
 print(<_io.StringIO object at 0x0000000005C588B8>.getvalue())
>>  assert '\\footnote[1]{\nnumbered\n}' in '% Generated by Sphinx.\r\n\\def\\sphinxdocclass{report}\r\n\\documentclass[letterpaper,10pt,english]{sphinxmanual}\r\n\\usepackage[utf8] ... '

(skip)

----------------------------------------------------------------------
Ran 1 test in 3.104s

FAILED (failures=1)
```

This error seems due to ... ,
- test string includes newline character.
- On windows, .tex file is saved with \n -> \r\n translation
  (see sphinx.builders.latex.LatexBuilder.write and docutils.io.FileOutput)
- However, invert translation is not valid.
  Files are loaded by tests.path.path.text(encoding='utf-8'). This method opens the given path
  using codecs.open(path, mode='U', encoding='utf-8'), but codecs.open() does not support
  newline translation as in built-in open() function for Py3.4 (moreover, mode='U' is no longer recommended).

This failure will be resolved by adding f.read().replace('\r\n', '\n'), simply. But it does not seem smart.

**Comment by shimizukawa** [comment]
Please let me know which version of sphinx did you test on?

**Comment by takaakiaoki** [comment]
I am testing it on commit 0dd6ce3063ddb2f8b7f084e923ecc7f4ab4e9423

Regards,

**Comment by shimizukawa** [comment]
Fixed. Thanks for your reporting!
