### ISSUE TITLE
raw directive does not work for text writer

### ISSUE THREAD

**Issue by rartino** [sphinx-doc/sphinx#2168]
When asking for .. raw:: text, I get the following crash:

```
Exception occurred:
  File "/home/rar/Local/Httk/sphinx/sphinx/writers/text.py", line 943, in visit_raw
    self.body.append(node.astext())
AttributeError: TextTranslator instance has no attribute 'body'
```

Full log is attached:
[sphinx-err-lIPmGJ.log.txt](https://github.com/sphinx-doc/sphinx/files/60278/sphinx-err-lIPmGJ.log.txt)

A patch that fixes the issue is also attached:
[sphinx_raw_text.patch.txt](https://github.com/sphinx-doc/sphinx/files/60279/sphinx_raw_text.patch.txt)

**Comment by tk0miya** [comment]
Fixed at  209e5f2
