### ISSUE TITLE
Autodoc unable to mock submodules

### ISSUE THREAD

**Issue by Psirus** [sphinx-doc/sphinx#2174]
conf.py:

```
autodoc_mock_imports = ['PySide.QtGui']
```

foo.py:

```
import PySide.QtGui as QtGui

class Gui(QtGui.QMainWindow):
    """ Example Docstring """
```

foo.rst:

```
.. automodule:: foo
   :members:
```

Gives this error:

```
AttributeError: type object 'QtGui' has no attribute 'QMainWindow'
```

**Comment by danbrees** [comment]
I am running into the same type of issue.  I am trying to mock the import of a third party submodule of a submodule of a module (mod.Submod.subsubmod).  When Submod has a capitalized first letter, I get: 
 AttributeError: type object 'Submod' has no attribute 'subsubmod' 

I don't get the error if Submod is submod.  I think Sphinx is interpreting Submod as a class, not a submodule. Unfortunately, I cannot just lowercase the submodule name.

**Comment by AlexBudesteanu** [comment]
Is there a fix for this issue or a way to get around it?

**Comment by tk0miya** [comment]
Could you share me a reproducible example? I'd like to investigate that.

**Comment by AlexBudesteanu** [comment]
Before giving an example, I would like to enforce what @danbrees said:

> I think Sphinx is interpreting Submod as a class, not a submodule.

by referencing _MockModule class in /ext/autodoc.py on my machine. (I have installed sphinx via debian so i have  version '1.3.6-2ubuntu1.1')

```
class _MockModule(object):
    """Used by autodoc_mock_imports."""
    def __init__(self, *args, **kwargs):
        pass

    def __call__(self, *args, **kwargs):
        return _MockModule()

    @classmethod
    def __getattr__(cls, name):
        if name in ('__file__', '__path__'):
            return '/dev/null'
        elif name[0] == name[0].upper():
            # Not very good, we assume Uppercase names are classes...
            mocktype = type(name, (), {})
            mocktype.__module__ = __name__
            return mocktype
        else:
            return _MockModule()
```

**Comment by tk0miya** [comment]
> (I have installed sphinx via debian so i have version '1.3.6-2ubuntu1.1')

Now newest stable version is 1.6.5.
1.3 series is too old. Could you try newest version? It is much improved.

**Comment by AlexBudesteanu** [comment]
I can confirm that it works with v1.6.5.
Thank you for the support!

**Comment by tk0miya** [comment]
@Psirus Have you still been in trouble with newest Sphinx?
If not, I will close this. Please let me know your status.

**Comment by Psirus** [comment]
No trouble; it works under 1.6.5. Thank you.

**Comment by tk0miya** [comment]
Thank you for confirmation.
This issue was already fixed. so I close this now :-)

**Comment by pitrou** [comment]
This seems to fail with 1.8.3.
Let's say I have a module `pyarrow.cuda` which is not available.

In `conf.py` I have:
```python
import pyarrow
try:
    import pyarrow.cuda
except ImportError:
    autodoc_mock_imports.append('pyarrow.cuda')
```

But I get errors such as:
```
Warning, treated as error:
[autosummary] failed to import 'pyarrow.cuda.BufferReader': no module named pyarrow.cuda.BufferReader
```

If instead I mock the module manually:
```python
import pyarrow
try:
    import pyarrow.cuda
    cuda_enabled = True
except ImportError:
    from unittest import mock
    pyarrow.cuda = sys.modules['pyarrow.cuda'] = mock.Mock()
```

Then things work ok.

**Comment by tk0miya** [comment]
@pitrou Could you file a new issue please. It would be nice if you prepare a minimal project for the error.
Thanks,
