### ISSUE TITLE
Parallel build often hangs, apparently waiting for subprocesses to finish

### ISSUE THREAD

**Issue by danrings** [sphinx-doc/sphinx#2177]
We have started using sphinx on a 1000+ rst-files project. It is pretty impressive, however the parallel build option (-j <N>) does not work properly. I find sphinx hangs in most cases some way through the files. I assume this is due to some deadlock arising from the interplay of multiprocessing, threading and semaphores. I managed to simplify the parallel.py module and make it run robustly. Will upload my changes for review shortly.

**Comment by birkenfeld** [comment]
That would be great!

**Comment by andreacassioli** [comment]
Hi,
I have been experiencing the same issue, and we have a similar size project. 

It seems to me the hang does not happen if the output on screen is disabled.
