### ISSUE TITLE
Support rendering math as svg in html and epub output

### ISSUE THREAD

**Issue by xuhdev** [sphinx-doc/sphinx#2179]
Rendering math as svg is pretty useful: the vector image would look much nicer than the png correspondence. Although MathJAX can be used for html, it (a) does not work in epub, (b) is heavy (takes time to load), (c) requires javascript.

I have a solution which I've implemented locally, which modifies `pngmath` to render math as svg images. The major part of the extension is pretty much the same, thus I would prefer to modify `pngmath` to support svg output. However, the name `pngmath` would no longer be appropriate. I have a few questions here, if they can be answered, I can make a proper PR:
- How about renaming `pngmath` to `imgmath`? Or simply not renaming (a bit confusing)?
- If renamed, how to deprecate the old name?
- The PR should be sent to master, is this correct?

Solving this issue also solves #1570

**Comment by xuhdev** [comment]
The hack I'm currently using is available [here](https://github.com/xuhdev/sphinx/commit/4fc2f49d1a66f9d5fb974d3c0ba10c8826369406)

**Comment by tk0miya** [comment]
> How about renaming pngmath to imgmath? Or simply not renaming (a bit confusing)?
> If renamed, how to deprecate the old name?

To keep compatibility, it would be better adding `imgmath` as new extension.
And, `pngmath` should warn deprecated message on importing.

> The PR should be sent to master, is this correct?

Yes, please!

@shimizukawa @birkenfeld  What do you think?

**Comment by birkenfeld** [comment]
Yes, no renames please. Renaming the default theme was painful enough :)

**Comment by shimizukawa** [comment]
+1 for no renaming :)

2015年12月19日(土) 18:59 Georg Brandl notifications@github.com:

**Comment by xuhdev** [comment]
OK, no renaming :)

**Comment by xuhdev** [comment]
I have made a PR at #2192 to for this issue :)

**Comment by tk0miya** [comment]
#2192 is merged now! Thanks a lot!
