### ISSUE TITLE
Previous sibling link for first file in subdirectory uses last file, not intended previous from root toctree

### ISSUE THREAD

**Issue by stevepiercy** [sphinx-doc/sphinx#2189]
# How to reproduce

We use `toctree` directives in two files located relatively from the root of the source directory as follows.
## index.rst

``` rst

.. toctree::
   :maxdepth: 2

   narr/introduction
   ...about 30 files listed here...
   narr/zca

.. toctree::
   :maxdepth: 1
   :glob:

   api/index
   api/*
```
## api/index.rst

``` rst
.. toctree::
   :maxdepth: 1
   :glob:

   *
```
# Expectation

When viewing the first globbed file in the api subdirectory:
http://docs.pylonsproject.org/projects/pyramid/en/master/api/authentication.html
the previous link should be for narr/zca, according to root index.rst.
# Observation

Previous link is for api/wsgi, the last file in the subdirectory when sorted alphabetically and globbed.
# Source

https://github.com/Pylons/pyramid/tree/master/docs
# Version

Sphinx 1.3.1
# Possibly related issues
- #790
- #1414
- #466

**Comment by tk0miya** [comment]
Fixed at f85d1a0.

I keep this ticket opened for a while. I'll check that are the related issues resolved or not.

**Comment by stevepiercy** [comment]
That fixed this specific issue, but now the issue has moved to the other end. So I'm updating this issue as follows:

# Expectation

When viewing the _last_ globbed file in the api subdirectory:
http://docs.pylonsproject.org/projects/pyramid/en/master/api/wsgi.html
the _next_ link should be for whatsnew-1.6, according to root index.rst.

# Observation

_Next_ link is for api/authentication, the _first_ file in the subdirectory when sorted alphabetically and globbed.

**Comment by tk0miya** [comment]
@stevepiercy Thank you for letting me know.
I fixed again at 222a51e.
Could you try it again?

**Comment by stevepiercy** [comment]
@tk0miya on Python 2.7, there's a syntax error:

```
  File "/Users/stevepiercy/projects/hack-on-pyramid/env/lib/python2.7/site-packages/sphinx/environment.py", line 1989
    for parinc in parincs[parindex 1:]:
                                   ^
SyntaxError: invalid syntax
```

In which version of Python do you build?

**Comment by tk0miya** [comment]
@stevepiercy Oh, really? We tests the script in py26-27 and py33-34 at Travis CI.
It seems all tests are passed https://travis-ci.org/sphinx-doc/sphinx/builds/98863191

Could you try it again with the HEAD of stable branch?

**Comment by stevepiercy** [comment]
@tk0miya I looked around through the [pip reference](https://pip.pypa.io/en/latest/reference/pip_install/#options), and tried several things, but could not figure out how to upgrade Sphinx 1.3.3 to HEAD in my virtualenv for Pyramid. I even tried un/installing. Do you have any suggestion?

**Comment by tk0miya** [comment]
@stevepiercy You can do it with following command:

```
pip install git+https://github.com/sphinx-doc/sphinx.git@stable
```

**Comment by stevepiercy** [comment]
OK, after throwing out my venv, i realized one should never "cross the streams" when installing packages via easy_install then pip. I basically resorted to installing all the necessary packages we use for Pyramid using pip instead of easy_install for Python 2.7 (didn't try 3.5) and this patch works correctly, even when traversing sibling directories. Thank you!

Now I need to figure out how to get RTD to install this version.

**Comment by stevepiercy** [comment]
FWIW, I tested this out, in our `rtd.txt` file:
git+https://github.com/sphinx-doc/sphinx.git@222a51e0cf0080b74f3a8a233590c707ee4eec32#egg=sphinx-222a51e0cf0080b74f3a8a233590c707ee4eec32

That worked via RTD:
http://pyramid-stevepiercy.readthedocs.org/en/master/narr/zca.html (click through to next a couple of times)

We're going to wait for the release of 1.3.4 before deploying. Do you have a release announcement only list/twitter/etc?

**Comment by tk0miya** [comment]
Thank you for verification. I was relieved to hear it.
Now, I close this issue.

> We're going to wait for the release of 1.3.4 before deploying. Do you have a release announcement only list/twitter/etc?

It will be announced in list: https://groups.google.com/forum/#!forum/sphinx-users

(Maybe it will released in a week: https://groups.google.com/forum/#!topic/sphinx-dev/HyAUsaPMZ1M)

Thanks.
