### ISSUE TITLE
apidoc extension docs don't list all available options (at least `--module-first` missing)

### ISSUE THREAD

**Issue by pekkaklarck** [sphinx-doc/sphinx#2190]
I wanted to have module contents before submodules but didn't find anything related when looking at [docs](http://sphinx-doc.org/man/sphinx-apidoc.html). Looking at the [source](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/apidoc.py#L296) I noticed that `--module-first` does exactly what I wanted.

**Comment by tk0miya** [comment]
MEMO: related with #2250

**Comment by tk0miya** [comment]
Now the reference is updated.
http://www.sphinx-doc.org/en/master/man/sphinx-apidoc.html#cmdoption-sphinx-apidoc-m

Thank you for reporting!
