### ISSUE TITLE
error in pot translation

### ISSUE THREAD

**Issue by coline-carle** [sphinx-doc/sphinx#2198]
Hi, I might have stumbled upon an issue with the pot file generation
Here on these three lines : 
https://gist.github.com/libellul/4c34ac12f74c90aa9f69#file-installing-pot-L56
https://gist.github.com/libellul/4c34ac12f74c90aa9f69#file-installing-pot-L64
https://gist.github.com/libellul/4c34ac12f74c90aa9f69#file-installing-pot-L72

The msgid SHOULD be links if you watch the following rst file in my gist. Something more like that
msgid "`Latest Stable Release <http://www.blender.org/download/>`__"

I know everything works fine on Arch Linux that's not the case on my mac

Python 2.7.11
Sphinx 1.3.3

**Comment by methane** [comment]
Isn't it a "term" of definition list?

see https://github.com/sphinx-doc/sphinx/commit/d3375761d27a11a23636673c2390c321f1754114#commitcomment-15202832

**Comment by coline-carle** [comment]
I do not have the programming skills but I norrowed down the problem effectively it has to do with definitions

```
`Definition Link <http://link>`__
    this is a definition
```

the pot file is  : 

``` pot
#: ../../source/links.rst:2
msgid "Definition Link"
msgstr ""

#: ../../source/links.rst:2
msgid "this is a definition"
msgstr ""
```

**Comment by shimizukawa** [comment]
@libellul @methane Thanks for your helpful information!. I fixed it.
