### ISSUE TITLE
:scale: option for figure:: doesn't work in Sphinx 1.3.3

### ISSUE THREAD

**Issue by pborenstein** [sphinx-doc/sphinx#2199]
The following markup works in Sphinx 1.3.1 but not in Sphinx 1.3.3:

```
..  figure:: _images/502x748.png
    :scale: 60%
    :align: right

..  list-table::
    :header-rows: 1
    :widths: 20 30

    * - Field
      - Description
    * - Item 1
      - Item 1 is the first item.
    * - Item 2
      - Item 2 is the second item.
```
## Sphinx 1.3.1

<img width="350" alt="sphinx131" src="https://cloud.githubusercontent.com/assets/113034/12037950/e3487b88-ae21-11e5-9d30-21a4414c0782.png">
## Sphinx 1.3.3

<img width="393" alt="sphinx133" src="https://cloud.githubusercontent.com/assets/113034/12037949/e344b002-ae21-11e5-875d-8f60d07f389b.png">
## ZIP file containing project

[scale-bug-133.zip](https://github.com/sphinx-doc/sphinx/files/74135/scale-bug-133.zip)

**Comment by tk0miya** [comment]
In my environment, it works fine for me.
I took a look at the difference of sphinx131.html and sphinx133.html.
I found there is no style attribute in sphinx133.html.

```
--- _build/html/sphinx131.html  2015-12-30 01:10:24.000000000 +0900
+++ _build/html/sphinx133.html  2015-12-30 01:10:46.000000000 +0900
@@ -61,7 +61,7 @@
 Under Sphinx 1.3.1, the image is scaled.
 Under Sphinx 1.3.3, the image is <em>not</em> scaled.</p>
 <div class="figure align-right">
-<a class="reference internal image-reference" href="_images/502x748.png"><img alt="_images/502x748.png" src="_images/502x748.png" style="width: 301.2px; height: 448.8px;" /></a>
+<a class="reference internal image-reference" href="_images/502x748.png"><img alt="_images/502x748.png" src="_images/502x748.png" /></a>
 </div>
 <table border="1" class="docutils">
 <colgroup>
```

It looks like behavior without installing pillow.
Could you check your sphinx 1.3.3 environement?
If pillow is not installed yet, please install it and try again.

**Comment by tk0miya** [comment]
Now, @shibukawa released a package to obtain image size in pure python:
https://pypi.python.org/pypi/imagesize
It enables `:scale:` option without installing Pillow.

Or, we have to warn scaling is disabled if Pillow not found.

**Comment by shimizukawa** [comment]
+1 for depending to `imagesize` package since Sphinx-1.4 if Sphinx just use PIL(Pillow) for image size recognition.
