### ISSUE TITLE
configuration to use specified directory name instead of underscore prefixed names as `_static`

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#2203]
For what?
- for github pages (now a days, `.nojekyll` is recommended)
- some other purpose?

Targets:
- _static
- _images
- _downloads
- _sources

Limitations:
- Conflicts with user's directories, however user should know.
- Some extensions write files into `_static` or `_images` directories directory, maybe (ex: diagram or some image generators).

Relates:
- #2202 want to use `static` instead of `_static`
- [sphinxtogithub](https://pypi.python.org/pypi/sphinxtogithub) plugin rename underscore prefixed directories on the `build-finished` event.

**Comment by tk0miya** [comment]
I think it is better that creating `.nojekyll` by default (or ask that on quickstart) if main reason is github-page support.

**Comment by birkenfeld** [comment]
+1 for asking in quickstart.

**Comment by afiorillo** [comment]
This would still be very useful if serving with another web server (Harp in particular). Not necessarily GitHub.

**Comment by Abdur-rahmaanJ** [comment]
If i understood correct, the PR asks on quickstart. A conf parameter is needed!
