### ISSUE TITLE
make.bat generated by quickstart.py cannot be called from another dir

### ISSUE THREAD

**Issue by quarion** [sphinx-doc/sphinx#2215]
## Problem

make.bat cannot be called from another directory that its own. It can be problematic in some situations, for example if you would want to call it from a build script.
## Solution

add `pushd` and `popd` directives in the output .bat

I will try to make a pull request later, if nobody would pick this up

**Comment by tk0miya** [comment]
+1
Yes, please! We'll merge your pull request.

**Comment by Paebbels** [comment]
What's the current status?
How can users update their existing make.bat?

**Comment by tk0miya** [comment]
Nothing changed. I'm only waiting pull request.

> How can users update their existing make.bat?

Unfortunately, sphinx does not provide the way to update existing project.
Any other hacks are needed to do that.

**Comment by shimizukawa** [comment]
Now #3085 is merged. This feature will be included in 1.5 release.
