### ISSUE TITLE
list-table caption garbled in LaTeX output

### ISSUE THREAD

**Issue by RobertoBagnara** [sphinx-doc/sphinx#2219]
With Sphinx 1.3.3 (not sure about previous versions)
a source line like

  .. list-table:: bla bla bla

results into the LaTeX output

  \caption{[u'bla bla bla']}

instead of

  \caption{bla bla bla}

**Comment by tk0miya** [comment]
Sorry for inconvenience. This has been fixed at #2201.
We will release new version including this fix soon (maybe).
Please wait a moment.

Thank you for reporting.
