### ISSUE TITLE
Mirror more of the docutils documentation

### ISSUE THREAD

**Issue by bgamari** [sphinx-doc/sphinx#2228]
While reading the Sphinx documentation I tend to find myself dreading finding references to `docutils` documentation. While the Sphinx documentation is clear, readable, and well-organized, the `docutils` documentation sorely lacks in all three of these areas. Unfortunately, it's quite difficult to avoid needing to drop down to `docutils` at some point. Perhaps the Sphinx project could consider providing a better-organized, more readable version of `docutils`' library documentation.

**Comment by lehmannro** [comment]
I'd generally frown upon documenting something which is out of our control — we'd always be chasing docutils' head (granted, it's not too-lively a target.)  Could we instead improve Docutils documentation?

**Comment by birkenfeld** [comment]
AFAICR, there have been multiple attempts to convince docutils people to use Sphinx, always declined.

**Comment by bgamari** [comment]
For the record, there is some discussion [here](http://sourceforge.net/p/docutils/mailman/message/32409387/) and a rather rough import of the docutils documentation to ReadTheDocs [here](http://docutils.readthedocs.org/en/sphinx-docs/index.html).

**Comment by tk0miya** [comment]
Now I close this issue. because it is out of our control.
