### ISSUE TITLE
Invoke latex rules in the files

### ISSUE THREAD

**Issue by ghtmtt** [sphinx-doc/sphinx#2231]
I hope github's issues is the right place where to add this problem.

I did not figure out how to call latex _customizations_  in the `rst` files.
The steps are:
- create a style.tex file and place it in the same folder of `conf.py`. Example of `style.tex`:

```
% My personal "bold" command
\newcommand{\mybold}{\textbf} 
```
- edit `conf.py` and include the new `style.tex`:

```
f = open('style.tex', 'r+');
PREAMBLE = f.read();
latex_elements = {
# Additional stuff for the LaTeX preamble.
'preamble': PREAMBLE,
}
```
- try to call **mybold** command in the various `.rst` files:

```
:mybold:`my text` #doesn't work

.. role: mybold
:mybold:`my text` #doesn't work

```

I don't know if this is an expected behavior or not.

**Comment by tk0miya** [comment]
To apply your styles to custom roles, please define `\docutilsrole{rolename}` macro.
For example, `mybold` role requires `\docutilsrolemybold`. So you can set up it in your conf.py:

```
latex_elements = {
    'preamble': r'\newcommand{\docutilsrolemybold}{\bfseries}',
}
```

Is this helps you?

**Comment by ghtmtt** [comment]
Hi, thanks for the answer. 
I added your suggestions to the code but I get an error during the compilation

```
! Latex error: missing \begin{document}
```

**Comment by tk0miya** [comment]
I tested with following environment:
- Sphinx 1.3.4
- Python 2.7.11
- MacTeX 2015

Please tell me about your environment.

For reference, I attached my project. It works fine.
[2231.zip](https://files.zenhub.io/569608ec5a0cfd1c5d6e9733)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by ghtmtt** [comment]
Ok it's working now (I had a typo)! Thanks!
If you don't mind I have some doubts:
- I have always to _declare_ the `.. role::` at the beginning of each single rst file, right? Is there a way to make the role _global_ for the whole project?
- how can I add **many roles**, for example what am I looking for is to have a role that colors some words in a sentence, like: this should be :red:`red text here`?

Many thanks..

**Comment by tk0miya** [comment]
> I have always to declare the .. role:: at the beginning of each single rst file, right? Is there a way to make the role global for the whole project?

Maybe, `rst_prolog` will help you.
http://www.sphinx-doc.org/en/stable/config.html#confval-rst_prolog

For example::

```
rst_prolog = """
.. role:: mybold
"""
```

> how can I add many roles, for example what am I looking for is to have a role that colors some words in a sentence, like: this should be :red:red text here?

What did you mean? The roles can wrap multiple words.

```
reST's role can :mybold:`wrap multiple words` in sentence.
```

**Comment by ghtmtt** [comment]
Thanks for `rst_epilog` I didn't know that.

For the other example maybe I wasn't clear enough, sorry my fault. 
Suppose I want to have in the final pdf some red colors words. I tried to add another role in the `conf.py`, like:

```
\usepackage{color}
\renewcommand{\docutilsrolemyred}[1]{\color{red{#1}}}
```

and I tried to call it in the text as usual:

```
in this sentence, there is :myred:`red text here`
```

but it did not work. I don't get any error during the compilation, but if I had a look in the compiled `.tex` file I see that the words that should be included in red color have the following code:

```
in this sentence, there is \DUspan{myred}{red text here}
```

instead of something that should look so:

```
in this sentence, there is {\color{red}red text here}
```

Do you have an idea of why the role is not correctly interpreted?

Thanks again!

**Comment by tk0miya** [comment]
Oh, I understand.

Now, the macro `\DUspan{myred}{red text here}` is expanded to `{\docutilsrolemyred red text here}`.
It puts a group which enclose the `docutilsrole...` macro and target text.
And, `DUspan` expects that the `docutilsrole...` macros are modal commands (ex. `\rm`, `\sf`, `\tt` and so on).
So it is difficult to support to give the `docutilsrole...` macro which take texts as argument, now.

Sorry for inconvinience. We should improve the `DUspan` to support them.

**Comment by ghtmtt** [comment]
Hi,
ok so using  `docutilsrole` is not the right way in order to include colored words in the `rst` files.
Do you know if there is another way to doing that (colored words)?

Thanks again for your time

**Comment by tk0miya** [comment]
Now, I replaced `DUspan` with `DUrole` at 6b36b31 (at master branch).
It comes from newest docutils.
And, it supports the macro which take texts as argument.

Please use `DUrole...` macros instead of `docutilsrole...`.
More details, please read following page:
http://docutils.sourceforge.net/docs/user/latex.html#custom-interpreted-text-roles

If you get troubles, please reopen this issue and let me know.

Thanks,

**Comment by ghtmtt** [comment]
Thanks for the code improvements you made.
Now when I compile the role and `DUrole` work nice!
I still have some trouble with the colors because of the `xcolor` packages and its options that I'm not able to overwrite by default (in the custom stylesheet):

```
The package xcolor has already been loaded with options:
  [xcdraw]
There has now been an attempt to load it with options
  [dvipsnames]
Adding the global options:
  xcdraw,dvipsnames
to your \documentclass declaration may fix this.
```

**Comment by tk0miya** [comment]
@ghtmtt I think it is different problem of this issue.
Could you create a new issue about that?

I want to know what you did in detail (preambles, reST files, and so on).
Thanks,

**Comment by ghtmtt** [comment]
@tk0miya done! #2245
