### ISSUE TITLE
autoclass and autodata fail on deep imports

### ISSUE THREAD

**Issue by halfak** [sphinx-doc/sphinx#2233]
See https://github.com/halfak/python-sphinx-break-stuff for a working example of the bug developed against Python 3.4.3 and Sphinx 1.3.4.   I made that working example as simplistic as I could.  It demonstrates how importing from a module that is at least two directories up from the root and then one additional level down (through another brach) seems to cause `autoclass` and `autodata` to fail to render correctly.  The demo also shows how several other import patterns work as expected.  

module structure:
- sphinx_test/
  - module/
    - submodule/
      - imports_nothing.py
      - imports_base_module.py
      - imports_break_stuff.py **(broken)**
    - imports_nothing.py
    - imports_base_module.py
    - imports_break_stuff.py
  - base_module.py
  - do_things/
    - break_stuff.py

Note that "sphinx_text/module/submodule/imports_break_stuff.py" is marked
as **(broken)**.  This is because a strange behavior that happens in
sphinx.  See the demo for more discussion.

**Comment by halfak** [comment]
I just ran a test with Sphinx 1.2.3 and the example works (with some hacking in conf.py to get `alabaster` working), but from 1.3.0 forward it does not. It seems that the issue was introduced in Sphinx 1.3.0.

**Comment by tk0miya** [comment]
I tried this with latest Sphinx and succeeded to build the example without errors. I think this issue was already resolved. So I'm closing this now. Sorry for not responding you so long.
