### ISSUE TITLE
Insert sphinx version in conf.py generated by sphinx-quickstart

### ISSUE THREAD

**Issue by fkromer** [sphinx-doc/sphinx#2234]
The _conf.py_ file which is created using the command line command `sphinx-quickstart` does include the date of creation in the comment section of the file. However the comment section does not include the version of sphinx (e.g. Sphinx v1.3.4) which would be helpful in many situations.

**Comment by tk0miya** [comment]
Please let me know in detail. I'd like to know what does the version comment help.

Note: At present, creation date were dropped from generated conf.py.

**Comment by fkromer** [comment]
I think my use case back then was that a plugin I have written depended on features of a specific version of Sphinx. In case a plugin user wanted to use the plugin with a too old version of Sphinx the plugin should warn about this... But I am not quote Sure about the details anymore.

**Comment by fkromer** [comment]
> Note: At present, creation date were dropped from generated conf.py.

... doesn't matter for me because it wouldn't help in my use case.

**Comment by tk0miya** [comment]
> In case a plugin user wanted to use the plugin with a too old version of
Sphinx the plugin should warn about this...

I think the version on conf.py does not resolve the case. For example, the
conf.py of Sphinx was generated for a long time ago (About 10 years ago!).
But, we use latest version of Sphinx for generating documents.

BTW, extension authors can use `app.require_sphinx()` API to check version
of Sphinx. I think this is better resolution for your case.
http://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx.application.Sphinx.require_sphinx

Thanks,
Takeshi KOMIYA


2018-04-02 3:54 GMT+09:00 thinwybk <notifications@github.com>:

**Comment by fkromer** [comment]
> BTW, extension authors can use `app.require_sphinx()` API to check version of Sphinx. I think this is better resolution for your case. http://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx.application.Sphinx.require_sphinx

That's a better way to check it. Thx.
