### ISSUE TITLE
:term: in figure caption causes LaTeX build to fail

### ISSUE THREAD

**Issue by tcpaiva** [sphinx-doc/sphinx#2238]
I am using sphinx 1.3.3 and the `latexpdf` buid from

```
.. figure:: atca-shelves.png
   :name: fig-atca-shelves

   :term:`ATCA` shelves
```

fails with

```
! Undefined control sequence.
<argument> \node@class@name 

l.214 ...span{xref,std,std-term}{ATCA}}}} shelves}
                                                  {\small
```

although `make epub` or `make html` works very well.

In line 214 of the mentioned file, the problematic excerpt inside of the `\caption` macro is

```
\DUspan{xref,std,std-term}{ATCA}
```

which in turn call this

```
\@for\node@class@name:=#1\do{%
\ifcsname docutilsrole\node@class@name\endcsname%
  \csname docutilsrole\node@class@name\endcsname%
\fi%
```

PS: maybe it is related to #1798.

**Comment by tk0miya** [comment]
Thank you for reporting. I'll take a look later.

**Comment by tk0miya** [comment]
Now, in master branch, that is already resolved.
Since 6b36b31984083faa88862bbff475c610bf409a04, LaTeX writer uses `DUrole` instead of `DUspan` for custom roles.

Thank you for reporting.
