### ISSUE TITLE
double backslash \\ in .rst replaced by single backslash \ in .html

### ISSUE THREAD

**Issue by ltalirz** [sphinx-doc/sphinx#2239]
I stumbled upon this when using the Math support in Sphinx. According to the [documentation](http://www.sphinx-doc.org/en/stable/ext/math.html#module-sphinx.ext.mathjax), there should be no need to escape backslashes when writing mathematical expressions using LaTeX _within_ .rst files (it should only be necessary, when writing them in python docstrings).

E.g. `$$\pi$$` within the .rst file should give `$$\pi$$` within the .html file (to be further processed by MathJax in my case).

However, I find that `$$\pi$$` in RST gives `$$pi$$` in HTML (and `$$\\pi$$` in RST gives `$$\pi$$` in HTML). Is this a bug or am I missing something?

I am using sphinx 1.3.4 (from macports) on MacOS 10.10.5, and I have attached my conf.py file.

[conf.txt](https://github.com/sphinx-doc/sphinx/files/92208/conf.txt)

**Comment by tk0miya** [comment]
It is specification of reStructured Text:
http://docutils.sourceforge.net/docs/user/rst/quickref.html#escaping

BTW, if you want to write mathmatical expressions in Sphinx, use `:math:` role or `.. math::` directive. Inside of these role and directive, it is not needed to escape backslashes.
For example::

```
.. math::

   x = y \times \pi
```

**Comment by ltalirz** [comment]
Thank you tk0miya & my bad, I should have read the documentation more thoroughly.

This means using the default MathJax delimiters is really not a viable option in reST.
I like them since, coming from LaTeX, they feel so natural, but I guess one can't have everything :-)
