### ISSUE TITLE
strange table caption

### ISSUE THREAD

**Issue by andreacassioli** [sphinx-doc/sphinx#2242]
I have a dummy table

```

   ======= ========
   a              1
   b              2
   c              3
   ======= ========

```

When rendered in html I get

```
Table 
1 abc
a   1
b   2
c   3
```

That is the caption is forced to be as large as the table columns.

**Comment by tk0miya** [comment]
Now, Sphinx uses `<caption>` tag for represent table caption.
Its width is restricted to table body's.
This behavior comes from the CSS specification. so this is not a bug of sphinx, I think.

Such a small table, it seems a bit strange. but, in almost case it works fine.
Please let us know if you have a good solution

**Comment by andreacassioli** [comment]
OK, I see.

Well, the table I wrote is a limit case, my actual code is a bit less extreme! But I see you point. I will try to change the table and /or the text.
