### ISSUE TITLE
numref not working

### ISSUE THREAD

**Issue by andreacassioli** [sphinx-doc/sphinx#2244]
Hi,
it seems in some situation `numref` is not able to resolve links. See the following example:

```
:numref:`ex1` demonstrates how the example is solved.


.. literalinclude:: go1.m
   :caption: Example.
   :name: ex1

```

The name `ex1` is unique in my docs, and the referenced file exists. But running Sphinx 1.3.4 results in a broken link. 

I have other cases for tables. For instance

```
Other dependencies follow in :numref:`dependency_table`\ .


.. _dependency_table:

.. table::  supported versions

   =====================  ============================
   Interface              Supported versions
   =====================  ============================
   java                   Sun  java  1.6+
   microsoft   dotnet     2.1+
   python  2              2.6+
   python  3              3.1+
   =====================  ============================
```

Again, the reference is missing. Notice that the table is displayed and numbered correctly.  Using `:name:` option instead does not solve the issue.

Any idea??

**Comment by tk0miya** [comment]
Really? In my environment, it works fine.
For reference, I attach my project and generated docs here:
[2244.zip](https://github.com/sphinx-doc/sphinx/files/93802/2244.zip)

Please tell me about the problem in detail? How break the link? What builder did you use?

**Comment by andreacassioli** [comment]
Hi,
thank you for the reply.

I run on Linux, Sphinx 1.3.4 and I am using html builder. I am not sure I can boil down a small example, my project is fairly big.

I have changed a bit the code

```
:numref:`toolbox.guided_tour_go_ex1_list` demonstrates how the example is solved using :ref:`toolbox.mskgpopt`.


.. literalinclude:: go1.m
   :caption: Example on how to use `mskgpopt`.
   :name: toolbox.guided_tour_go_ex1_list
```

 I have connected a printer function to the `missing-reference` event and print out the node:

```
<pending_xref refdoc="tutorial-geometric" refdomain="std" refexplicit="False" reftarget="toolbox.guided_tour_go_ex1_list" reftype="numref" refwarn="True"><literal classes="xref std std-numref">toolbox.guided_tour_go_ex1_list</literal></pending_xref>
```

The code header in the HTML output is 

```
<div class="literal-block-wrapper container" id="toolbox-guided-tour-go-ex1-list">
<div class="code-block-caption"><span class="caption-text">Example on how to use <cite>mskgpopt</cite>. Click <a class="reference download internal" href="_downloads/go1.m"><code class="xref msk_download docutils litera
l"><span class="pre">here</span></code></a> to download.</span><a class="headerlink" href="#toolbox-guided-tour-go-ex1-list" title="Permalink to this code">¶</a></div>
```

**Comment by tk0miya** [comment]
I feel your HTML output is strange. There is no caption number.
In my environment, I can see `<span class="caption-number">Listing 1 </span>` in `<div class="code-block-caption">`::

```
<div class="literal-block-wrapper container" id="toolbox-guided-tour-go-ex1-list">
<div class="code-block-caption"><span class="caption-number">Listing 1 </span><span class="caption-text">Example on how to use <cite>m
skgpopt</cite>.</span><a class="headerlink" href="#toolbox-guided-tour-go-ex1-list" title="Permalink to this code">¶</a></div>
```

Did you set up `numfig = True` in your `conf.py`?

**Comment by andreacassioli** [comment]
Hi,
yes, I set `numfig = True`. Indeed in other part of the docs the numref works.

**Comment by tk0miya** [comment]
Sorry, I can't reproduce the problem. Could you make a small example?

**Comment by andreacassioli** [comment]
Hi,
thank you again.

I will try, but my project is fairly big and isolate the issue might not be that easy. Any suggestions on how to debug?

**Comment by andreacassioli** [comment]
Hi,
I think I have figured out: `numref` is indeed working, but the file I was looking at was not included in any toctree and since it is flagged as orphan, I got o warning. 

I am sorry I have made you waste time! Thank again!

**Comment by tk0miya** [comment]
Thank you for letting me know that.
I do not expect such a situation
I added warning message if target is not assigned any numbes.

Thank you for reporting and investigations :-)
