### ISSUE TITLE
Error when configuring Latex package options

### ISSUE THREAD

**Issue by ghtmtt** [sphinx-doc/sphinx#2245]
Hi all,
I have created and external `style.sty` file that contains some Latex options.
It is called (and it work nice) in the `conf.py` file as follow:

```
# -- Options for LaTeX output ---------------------------------------------

f = open('stile.sty', 'r+');
PREAMBLE = f.read();
latex_elements = {
# The paper size ('letterpaper' or 'a4paper').
#'papersize': 'letterpaper',
# The font size ('10pt', '11pt' or '12pt').
#'pointsize': '10pt',
# Additional stuff for the LaTeX preamble.
'preamble' : PREAMBLE
} 
```

in the `style.sty` file I have created some _roles_ like:

```
\usepackage[dvipsnames]{xcolor}

\newcommand{\docutilsrolemybold}{\bfseries}
\newcommand{\DUrolemyblu}[1]{\color{Blue{#1}}} 
```

while the role `mybold` works nice (thanks to this improvements #2231) I have some trouble with configuring the color rules.
A piece of one `.rst` file is:

```
=======
Section
=======

.. role:: myblu

I am a :myblu:`blue text`.

.. role:: mybold

I am :mybold:`bold text`.
```

During the compilation (`make latexpdf` or either in 2 steps `make latex` and  `make all-pdf`) I get this error:

```
The package xcolor has already been loaded with options:
  [xcdraw]
There has now been an attempt to load it with options
  [dvipsnames]
Adding the global options:
  xcdraw,dvipsnames
to your \documentclass declaration may fix this.
```

So it seems it is not possible to overwrite the standard package configuration for the xcolor package made by sphinx.

Thanks!

**Comment by tk0miya** [comment]
LaTeX says adding `dvipsnames` to the global options.
So you can do it with `latex_elements['extraclassoptions']`.

Following code works fine for me::

```
latex_elements = {
    'extraclassoptions': 'dvipsnames',
    'preamble': r'''\newcommand{\docutilsrolemybold}{\bfseries}
\newcommand{\DUrolemyblu}[1]{{\color{Blue}#1}}
'''
}
```

Could you try it please?

BTW, we can add the new option for xcolor package.
But, IMO, too much options will make users confused.
So I would not add the option in this case.
of course, I will add it if really needed.

Thanks,

**Comment by ghtmtt** [comment]
Hi tk0miya,
it works nice now! 
I think it's not necessary to add this options by default, it's quite confusing when you don't know the whole process.

Is there a place where all this instructions you have provided can be added? It is a pity to _loose_ all this super useful information..

I can obviously help on that!

**Comment by tk0miya** [comment]
Now, there is no appropriate pages for customization of LaTeX output.

> I can obviously help on that!

It would be better if you send any pull requests for these docs.
Thanks,

**Comment by jfbu** [comment]
@tk0miya  

The `preamble` key allows only to insert material after the `\usepackage{sphinx}`. As global class options in LaTeX may sometimes cause problems (same option name used by different packages, ony one was targeted), there would be a need for a `latex_elements` key allowing also to inject material before  the `\usepackage{sphinx}`.

Indeed the issue reported here could have been fixed by inserting in the preamble, before the location of `\usepackage{sphinx}`:

``` latex
\PassOptionsToPackage{dvipsnames}{xcolor}
```

Currently one can abuse for example the `babel` key to `latex_elements` to do something like:

``` python
latex_elements = {
# The paper size ('letterpaper' or 'a4paper').
#'papersize': 'letterpaper',

# The font size ('10pt', '11pt' or '12pt').
#'pointsize': '10pt',

# Additional stuff for the LaTeX preamble.
# ---- Note added: this will end up after \usepackage{sphinx} in the preamble ----
#'preamble': '',

# Latex figure (float) alignment
#'figure_align': 'htbp',

'babel': '''\\usepackage{babel}
\\PassOptionsToPackage{dvipsnames}{xcolor}'''
}
```

**Comment by tk0miya** [comment]
@jfbu I agree with you.
Do you have any suggestion about the new key name?
I'll think about it later.

**Comment by jfbu** [comment]
@tk0miya hmm... tough call, as it depends if the material will be inserted immediately after `\documentclass` or later, right before `\usepackage{sphinx}`. Perhaps `earlypreamble` ?

documentation:

``` rest
For user material before package loading (e.g. ``\PassOptionsToPackage{foo}{bar}``)
```

**Comment by tk0miya** [comment]
I added `latex_elements["passoptionstopackages"]` in 84fb1b7.
The variable is embeded next of `documentclass`.

Thanks,

**Comment by jfbu** [comment]
looks good ;-)
