### ISSUE TITLE
Add extension interface to sphinx.ext.graphviz

### ISSUE THREAD

**Issue by fkromer** [sphinx-doc/sphinx#2246]
I would like to extend the built-in sphinx-doc extension sphinx.ext.graphviz with a few featues. As the features are very special for my use case i do not want to fork and extend sphinx.ext.graphviz itself.

Essentially i just want to (graphviz sources for reference)
- parse with graphviz to get the graphviz nodes (~ Graphviz.run()),
- modify the graphviz dotcode of the nodes (~ node['code'] = dotcode),
- output/render (html/pdf) with graphviz without modification (~ e.g. for html: html_visit_graphviz() -> render_dot_html()).

I have read the sphinx-doc extension developer guide but do not fully understand the build phases/procedure and how to "combine" extensions like described above.

Is it possible to modifiy the inlined graphviz code between "Build Phase 1: Reading" and "Build Phase 3: Resolving" with a "dependent-on sphinx.ext.graphviz" extension somehow? If not: Would it be possible to add an extension interface for sphinx.ext.graphviz to allow modification of the parsed data? (I am pretty sure many people out there would like to avoid to develop private manipulated forks of sphinx.ext.graphviz.)

**Comment by tk0miya** [comment]
Maybe you can do it with following code:

```
def on_doctree_read(app, doctree):
    for node in doctree.traverse(graphviz):
        code = re.sub('\];', ', color = red];', node['code'])  # change color of nodes and edges
        node['code'] = code


def setup(app):
    app.connect('doctree-read', on_doctree_read)
```

In this example, I used the `doctree-read` event.
It is raised at Reading phase. In more detail, you can see what is "Sphinx core events" at http://www.sphinx-doc.org/en/stable/extdev/appapi.html#sphinx-core-events

Does this help you?

**Comment by fkromer** [comment]
Thanks for the hint. This was exactly what i did miss (i have obviously just "scanned" it and did not read it). Is there also an example or guidance about testing own extensions in an overall sphinx-doc setup?

**Comment by tk0miya** [comment]
Sorry, no docs for testing extensions yet.
But we have `sphinx-testing` package to do that.
https://github.com/sphinx-doc/sphinx-testing

I usually use it for testing extensions.

**Comment by fkromer** [comment]
Thank you for the hint. I found some good inspiration which also uses `sphinx-testing` for testing .png and .svg output here: https://github.com/blockdiag/sphinxcontrib-blockdiag/blob/master/tests/test_html.py

**Comment by tk0miya** [comment]
Good to know. Please let us know if you get any problems using the package.

Thanks,
