### ISSUE TITLE
Circular redirect on sphinx-doc.org

### ISSUE THREAD

**Issue by rossengeorgiev** [sphinx-doc/sphinx#2248]
Accessing http://sphinx-doc.org/latest/markup/inline.html, a link from google will redirect to itself.

``` bash
$ curl -I http://sphinx-doc.org/latest/markup/inline.html
HTTP/1.1 302 Found
Date: Mon, 18 Jan 2016 03:56:44 GMT
Server: Apache/2.2.15 (Unix) mod_ssl/2.2.15 OpenSSL/0.9.8e-fips-rhel5 mod_fastcg                                                                i/2.4.6
Location: http://www.sphinx-doc.org/latest/markup/inline.html
Content-Type: text/html; charset=iso-8859-1
```

**Comment by shimizukawa** [comment]
Thanks for your reporting!
@birkenfeld can you resolve this issue?

**Comment by birkenfeld** [comment]
I tried, but was unsuccessful (adding another prefix redirect for `/latest`). Maybe @ericholscher can help?

**Comment by ericholscher** [comment]
This should be fixed. Let me know if it isn't.

On Sun, Jan 17, 2016 at 10:41 PM, Georg Brandl notifications@github.com
wrote:

> I tried, but was unsuccessful (adding another prefix redirect for /latest).
> Maybe @ericholscher https://github.com/ericholscher can help?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sphinx-doc/sphinx/issues/2248#issuecomment-172441327.

## 

Eric Holscher
Maker of the internet residing in Portland, Oregon
http://ericholscher.com

**Comment by tk0miya** [comment]
Now, it seems fixed. so I close the issue.
@ericholscher Thank you for help :-)
