### ISSUE TITLE
Enum class from enum34 not working

### ISSUE THREAD

**Issue by rossengeorgiev** [sphinx-doc/sphinx#2249]
`enum34` is backported `python 3.4`'s Enum for older versions of `python`.

Problem is the same as #1609

**Comment by shimizukawa** [comment]
Confirmed. It works fine as well as #1609 
- Sphinx-1.5a2
- Python-2.7.12
- Windows 10

foo.py:

``` python
import pkg_resources
import foo
foo.__doc__ = str(pkg_resources.require("enum34"))

import enum


class E(enum.Enum):
    """
    this is enum class
    """

    val1 = 1  #: doc
    val2 = 2  #: doc


Animal = enum.Enum('Animal', 'ant bee cat dog')  #: this is doc string
```

index.rst:

``` rst
.. automodule:: foo
   :members:
   :undoc-members:
```

Result:
![image](https://cloud.githubusercontent.com/assets/151623/19482467/2e478dac-958c-11e6-891a-0b7784acc6c4.png)

**Comment by shimizukawa** [comment]
Sphinx project I tested with: [2249.zip](https://github.com/sphinx-doc/sphinx/files/536552/2249.zip)
