### ISSUE TITLE
Document sphinx-apidoc --separate

### ISSUE THREAD

**Issue by anntzer** [sphinx-doc/sphinx#2250]
At least the `--separate` option is missing from [the docs for `sphinx-apidoc`](http://www.sphinx-doc.org/en/stable/invocation.html#invocation-of-sphinx-apidoc).
I didn't check whether there's any other options missing overall.

**Comment by kefirbandi** [comment]
-M --module-first missing from the man page.
-M is in the docs referred above, but --module-first is not mentioned.
Both man and the docs fail to mention the role of the SPHINX_APIDOC_OPTIONS environment variable.

**Comment by stephenfin** [comment]
Looks like ``--separate`` is now present in [the docs](http://www.sphinx-doc.org/en/latest/man/sphinx-apidoc.html). We still need to add the make mode docs and the environment variable.
