### ISSUE TITLE
Provide a way to change the language if a translation exists

### ISSUE THREAD

**Issue by JulienPalard** [sphinx-doc/sphinx#2252]
In the context of translating the Python documentation to french (https://github.com/AFPy/python_doc_fr), I did not found a way in the sphinx documentation (did I missed it ?) to provide a way for the readers to change the language of a currently displayed part of the doc (probably by jumping on the same part of the doc on a completely different directory, for clarity / maintenability / SEO / whatever).

Also, the "link" should probably be generated / displayed / clickable only if the target translation is completed, to avoid misleading users and bots. 

The check about the completeness of a translation should probably be computed per rst file and not per po files as sometimes po files can be huge (Python documentation library.po is ~24k msgid, covering like 300 rst files.).

I'm not on the design / user interface / ux side so I can't think of something user friendly, but someone probably does ? :-)

**Comment by shimizukawa** [comment]
For now, Sphinx doesn't have the feature that provides links to other language page if exists. However ReadTheDocs provides the feature that is achieved by using multiple sphinx project on ReadTheDocs service. http://docs.readthedocs.org/en/latest/localization.html

**Comment by JulienPalard** [comment]
I don't think building multiple sphinx trees linked to each others is a nice solution (yet it's an easy one): a lot of link will point to a still untranslated page. Python is like 42k msgids, it can't be done in a year ^-^.

Yet it's better than nothing ^-^

**Comment by lehmannro** [comment]
The reason why it's hard (in terms of elegance) to implement this in core Sphinx is because builds are fundamentally _separate._  You could build the English version to `./_build/html` which the French one could end up in `/var/opt/frenchdocs/` and there is no way to know beforehand.

This functionality is better suited for something as ReadTheDocs or sphinx-intl.

> Also, the "link" should probably be generated / displayed / clickable only if the target translation is completed, to avoid misleading users and bots. 

I'd tend to disagree.  This way, you wouldn't get _anything_ until all 42k msgids are translated 100%.  Currently, we pick translations wherever available and leave the original otherwise.  (There is a long-standing TODO to highlight the untranslated parts, so they're easier to distinguish.)

**Comment by JulienPalard** [comment]
@lehmannro I think you didn't read my message, I explicitly said that the link should probably be masked / unmasked at a rst file granularity, not a po file granularity, not even at a whole project granularity, so we can show links only to translated atomic parts (rst files) that each take only a couple of hours to translate.

I however understand that this may, by design, not be possible, and highlighting untranslated entries may be a nice choice, even better if untranslated parts expose a way to redirect user to the translators home :)

Just for reference I link the ticket about highlighting here: https://github.com/sphinx-doc/sphinx/issues/1246 and close this issue.

**Comment by lehmannro** [comment]
Sorry, hyperbole on my part.  My argument stands:  You wouldn't want to hide a 99% completed (or, any n% where n≥1) RST file;  it makes achieving any useful translation much harder.

**Comment by JulienPalard** [comment]
Yes, a threhold may be interesting, you're right, in the other hand, also from an SEO point of view, but from a user point of view too, having a nice link "Hey, read the french version here" pointing to a page entierly in english is highly disappointing, and on the Python doc, we have two choices:
- Wait 5 year for the french team to complete translation at about 90%
- Have 90% of misleading links (advertising french, pointing to untranslated (english))
