### ISSUE TITLE
pyobject truncates code at comment

### ISSUE THREAD

**Issue by stevepiercy** [sphinx-doc/sphinx#2253]
# How to reproduce

Here is the sample code block which I want to include for the file `quick_tour/requests/app.py`.

``` python
def hello_world(request):
    # Some parameters from a request such as /?name=lisa
    url = request.url
    name = request.params.get('name', 'No Name Provided')

    body = 'URL %s with name: %s' % (url, name)
    return Response(
        content_type="text/plain",
        body=body
    )
```

Use the rst directive:

``` rst
.. literalinclude:: quick_tour/requests/app.py
    :pyobject: hello_world
```

I expect the above code block to be included, but instead I only see:

``` python
def hello_world(request):
```

I noticed that this single line also lacks Pygments syntax highlighting styles.

Workarounds:
- Remove the commented line, but then there is no comment.
- Move the comment to the end of a line, but this results in excessive line length.
- Use docstring style comments, e.g., `""" Some parameters from a request such as /?name=lisa """`.

**Comment by shimizukawa** [comment]
Fixed. Thanks for your reporting.

**Comment by stevepiercy** [comment]
Thank you! I confirm it works for me.
