### ISSUE TITLE
Two-stage model for initializing options from conf.py

### ISSUE THREAD

**Issue by mgeier** [sphinx-doc/sphinx#2255]
This was suggested by @birkenfeld in https://github.com/sphinx-doc/sphinx/issues/2162#issuecomment-168629682.

The built-in values should be initialized first, then the extensions' `setup()` functions should be called and finally the extension-specified setup values should be initialized.

This would allow extensions to check (and manipulate) user-specified config values (e.g. `latex_elements`) from within their `setup()` function.

**Comment by AA-Turner** [comment]
This is now doable with the changes to Config.

A
