### ISSUE TITLE
Allow table caption formatting 

### ISSUE THREAD

**Issue by ghost** [sphinx-doc/sphinx#2257]
Sphinx 1.3.1 ignored formatting (bold, italic, code) of table captions.
Sphinx 1.3.4 removes the entire formatted element.
This request is to allow table formatting within table captions (as for figures).

**Comment by tk0miya** [comment]
It works fine in my environment.
Could you tell me about your situation in detail please?

Input:

```
.. figure:: logo.jpg

   blah *hello* **world** blah

.. list-table:: blah *hello* **world** blah

   * - blah blah blah
     - blah blah blah
   * - blah blah blah
     - blah blah blah
   * - blah blah blah
     - blah blah blah
   * - blah blah blah
     - blah blah blah
```

Generated PDF:
![2016-01-22 10 58 42](https://cloud.githubusercontent.com/assets/748828/12500511/240e4c82-c0f7-11e5-9fb9-d40697ca9db9.png)

**Comment by ghost** [comment]
Apologies, the problem lies in one of our custom extensions. When I find out which, and what has changed to affect it, I will inform you here, if relevant. Thanks.

**Comment by ghost** [comment]
For both this and #2259, our custom table extension (created to use longtabu) wasn't aligned with the changes made in depart_table in the latex writer. Sorry for the knee-jerk reaction.

**Comment by tk0miya** [comment]
Good to know.
BTW, do you share the extension in public?
I'm interested in it personally.

**Comment by ghost** [comment]
No, the extension is not public. It was created (by an ex-employee) from the guts of latex.py which is why it sometimes breaks with sphinx updates. I've attached it. I'm not a python guy but it looks like the existing latex.py could be adjusted/extended to cater for the longtabu package. We've added some stuff to alter the row shading, and the sphinx preamble reduces the fontsize. This helps with our heavy use of tables for technical documentation.
P.S. Note (line 62) the temporary work-around, as we are running multiple build servers with different sphinx versions.
[ac_table.txt](https://github.com/sphinx-doc/sphinx/files/100857/ac_table.txt)

**Comment by tk0miya** [comment]
Thank you for giving extension! I'll take a look. 

It would be nice if longtabu feature feature is merged into sphinx core.
It is discussed at #1681. I'll work it soon :-)

Thanks a lot!
