### ISSUE TITLE
Footnotes missing in PDF

### ISSUE THREAD

**Issue by ghost** [sphinx-doc/sphinx#2259]
Sphinx 1.3.3: PDF footnotes present.
Sphinx 1.3.4: PDF footnotes missing. (Ok in HTML format).

**Comment by tk0miya** [comment]
It works fine in my environment.
Could you tell me about your situation in detail please?
Environment, your input (.rst file), generated file (.tex), any warnings and so on.

**Comment by ghost** [comment]
As for 2257, apologies, the problem lies in one of our custom extensions. When I find out which, and what has changed to affect it, I will inform you here, if relevant. Thanks.
