### ISSUE TITLE
literal_block and its caption has been separated by pagebreak in LaTeX output

### ISSUE THREAD

**Issue by tk0miya** [sphinx-doc/sphinx#2262]
Now, with sphinx-1.3.4, literal_block and its caption has been separated by pagebreak.
![2016-01-23 23 53 38](https://cloud.githubusercontent.com/assets/748828/12530769/aba6ba36-c22c-11e5-82a2-f120a76cfa34.png)

**Comment by tk0miya** [comment]
I attatched sample project to reproduce the problem.
[2262.zip](https://github.com/sphinx-doc/sphinx/files/101910/2262.zip)

**Comment by andreacassioli** [comment]
Hi,
I am experiencing the same issue on Sphinx 1.3.5.

**Comment by jfbu** [comment]
Here are some images to illustrate the effect of the PR #2297 on the provided test files 

![capture d ecran 2016-02-05 a 18 13 18](https://cloud.githubusercontent.com/assets/2589111/12853542/ef335306-cc34-11e5-81cc-c932cda3c71d.png)

After removing one item, no change, after removing two items, one gets
![capture d ecran 2016-02-05 a 18 15 43](https://cloud.githubusercontent.com/assets/2589111/12853553/028e3092-cc35-11e5-81b0-9ae9e671b859.png)

To check that caption counter is not increased too many times, here is with the test file extended to include a second literal-block:

![capture d ecran 2016-02-05 a 18 13 57](https://cloud.githubusercontent.com/assets/2589111/12853576/23a1fd4a-cc35-11e5-8860-e2d9424e0cfd.png)

**Comment by jfbu** [comment]
If one suppresses two `\item`'s from the produced `test.tex` file, and then adds 

``` latex
    \vskip .56298cm
```

immediately after the itemize environment,
the frame starts like in the second picture of last comment (with `SPHINXOPTS  =` moved to next page). But with a slightly bigger skip

``` latex
    \vskip .56299cm
```

it starts like in the first picture, the whole thing inclusive of caption being moved to next page. This shows the PR does fix the page break problems, however I don't know enough of sphinx's latex builder yet to ascertain if other areas may be impacted (other than direct insertion by user of a framed environment, which was already impacted by earlier `sphinx.sty` and `latex.py`).
