### ISSUE TITLE
Calling setup_extension() does not import sphinx built-in extension

### ISSUE THREAD

**Issue by fkromer** [sphinx-doc/sphinx#2263]
I develop an extension for sphinx-doc which shall use the built-in extension sphinx.ext.graphviz. To keep things easier for the moment I use the system installation of Python 3.4.3 with Sphinx==1.3.4 installed (avoid virtualenv issues, etc.). The extension source code is located in the `<sphinx-doc project root>/exts/sphinxcontrib_p3/sphinxcontrib/p3.py` (<sphinx-doc project root> is eswp3/). In p3.py i want to import sphinx.ext.graphviz using:

```
def setup(app):
    app.setup_extension('sphinx.ext.grahviz')
    ...
```

However after calling `make html` ("default" makefile generated with `sphinx-quickstart`, modified conf.py) from my sphinx-doc project root directory i get the following error message:

```
florian@florian-desktop ~/ws_github/eswp3 $ make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.3.4

Extension error:
Could not import extension sphinx.ext.grahviz (exception: No module named 'sphinx.ext.grahviz')
make: *** [html] Fehler 1
```

**Comment by birkenfeld** [comment]
If that is a literal copy-paste, please try again with `sphinx.ext.graphviz` (added `p`) :smiley:

**Comment by fkromer** [comment]
Oh no, what a shame. I am sorry for wasting your time. sphinx.ext.graphviz is imported.
