### ISSUE TITLE
Sphinx 1.3.5: Could not parse literal_block as "language"

### ISSUE THREAD

**Issue by stevepiercy** [sphinx-doc/sphinx#2264]
The following might not be a bug, but it is a changed behavior that enforces stricter syntax, and should be noted.
# How to reproduce

For this code sample (and several others):

``` rst
.. code-block:: ini
   :linenos:

   [app:main]
   ...
   pyramid.includes =
       pyramid_debugtoolbar
```

Sphinx 1.3.4 yielded no errors. Upgrading to 1.3.5 and attempting to build HTML causes the following error:

`/home/travis/build/Pylons/pyramid/docs/narr/project.rst:434: WARNING: Could not parse literal_block as "ini". highlighting skipped.`
# How to Fix/Workaround

Use a comment for elided output instead of a literal `...`. It appears that one can no longer use incorrect syntax for a given language for highlighting.

``` rst
.. code-block:: ini
   :linenos:

   [app:main]
   # ... elided configuration
   pyramid.includes =
       pyramid_debugtoolbar
```

The screenshot compares two examples, where the first is highlighted but the second is not.

![google chrome005](https://cloud.githubusercontent.com/assets/102112/12535376/c0773b80-c235-11e5-9f85-6aa2046182ac.png)

I noticed that this shows up for `javascript` or `posh` syntaxes, too.

Possibly related to #2262.

**Comment by birkenfeld** [comment]
The second block would have been unhighlighted in previous Sphinx versions too. Only the warning is new to make you aware of it.

**Comment by stevepiercy** [comment]
@birkenfeld is this a change in Pygments or Sphinx? Either way, it's a good change that helped me catch a couple of other mistakes.

**Comment by birkenfeld** [comment]
This was added to Sphinx in #1565.

**Comment by stevepiercy** [comment]
Would it be helpful to add to the change log something like this?

> If the syntax is incorrect for the `:language:` option in a `.. code-block::` directive, Sphinx will now emit a warning as follows.
> 
> `WARNING: Could not parse literal_block as "<language>". highlighting skipped.`

Reasoning: When searching the change log, I could not find anything relevant to "literal_block". This would link the error message to a specific change log entry and provide a clue for what changed in 1.3.5 and how to fix it.

Alternatively, the warning message could refer to the specific directive that literal_block refers to, e.g.,

`WARNING: Could not parse code-block as "<language>". highlighting skipped.`

I can submit a PR, but the change log is very terse, and I wouldn't want to break that pattern.

If not, then this issue can be closed, and at the least this discussion can be indexed by search engines.

**Comment by tk0miya** [comment]
OK, I'll update it later.

**Comment by tk0miya** [comment]
@stevepiercy This change also effects to other directives (cf. `literalinclude`, `parsed-literal` and so on).

So I rewrite changelog as follows:

> - #1565: Sphinx will now emit a warning that highlighting was skipped if the syntax
>   is incorrect for `code-block`, `literalinclude` and so on.

Thanks,

**Comment by stevepiercy** [comment]
Thank you!

**Comment by karelyatin** [comment]
If i use sphinx 1.6.2 or 1.6.3 with pygments<=2.1.3 the following error is reported:
  Could not lex literal_block as "ini". Highlighting skipped.

But with pygments 2.2 The above error is not reported.

**Comment by jean** [comment]
Is it possible to log in more detail why lexing failed?

**Comment by tk0miya** [comment]
@jean could you file a new issue please? I'll take a look later.
