### ISSUE TITLE
\addto\caption... is added when babel is disabled

### ISSUE THREAD

**Issue by vlotorev** [sphinx-doc/sphinx#2265]
I'd like to use xelatex to generate PDF.

I've added make target which calls xelatex instead of latexpdf.

My latex_elements at conf.py looks like following:

``` python
language = 'ru'
...
    'utf8extra': '',
    'fontpkg': r'',
    'babel': '',
    'fncychap': '',
    'inputenc': '',
    'fontenc': '',
    'preamble': r"""

\usepackage{fontspec}
\setmainfont{Liberation Serif}
\setsansfont{Liberation Sans}
\setmonofont{Liberation Mono}
"""
}
```

But the generated output tex file still contains reference to _captionsrussian_
which causes an error during call of xelatex:

``` tex
\addto\captionsrussian{\renewcommand{\figurename}{Fig. }}
\addto\captionsrussian{\renewcommand{\tablename}{Table }}
```

As far as I understand captionrussian is babel macro, right?

Checked on sphinx 1.3.5

**Comment by tk0miya** [comment]
Fixed at 9b21115.

Thank you for reporting
