### ISSUE TITLE
1.3.5 - make test fails with Python 2.7.10

### ISSUE THREAD

**Issue by stroeder** [sphinx-doc/sphinx#2268]
Tried to package 1.3.5 for Python 2.7.10.

But "make test" fails:
https://build.opensuse.org/build/home:stroeder:branches:devel:languages:python/openSUSE_Tumbleweed/x86_64/python-Sphinx/_log

**Comment by shimizukawa** [comment]
Thanks for your reporting, I'll take a look.

BTW, the link you pasted indicate `anonymous_user(Anonymous user is not allowed here - please login):`

**Comment by shimizukawa** [comment]
Memo:
- Sphinx-1.3.5 + Python-2.7.9 is fine: https://travis-ci.org/sphinx-doc/sphinx/jobs/104384116
- It might be caused by differently of UCS2 and UCS4.
  https://github.com/travis-ci/travis-ci/issues/5107

**Comment by tk0miya** [comment]
FYI:
I try to reproduce with MacOSX 10.9.5 and Sphinx-1.3.5 and Python-2.7.10.
But `make test` works fine:

```
$ python --version
Python 2.7.10
$ make test
Checking dependencies...
Temporary files will be placed in /Users/tkomiya/work/sphinx/tests/build.
Running Sphinx test suite (with Python 2.7.10)...
..................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................S..................................................
----------------------------------------------------------------------
Ran 773 tests in 102.956s
```

**Comment by shimizukawa** [comment]
```
(venv)vagrant@vagrant-ubuntu-wily-64:~/sphinx-1.3.5$ make test
Checking dependencies...
Temporary files will be placed in /home/vagrant/sphinx-1.3.5/tests/build.
Running Sphinx test suite (with Python 2.7.10)...
.......................................................S...........................................................................................................................................................................................................................................................................................................................................................................S.S...............S................................................................................................................................S......................S..................................................
----------------------------------------------------------------------
Ran 639 tests in 52.597s

OK (SKIP=6)

(venv)vagrant@vagrant-ubuntu-wily-64:~/sphinx-1.3.5$ python -c "import sys;print(sys.maxunicode)"
1114111
```

**Comment by shimizukawa** [comment]
@stroeder please let me know the detail of error.

**Comment by mitya57** [comment]
@shimizukawa I'm getting failures now too (when trying to package Sphinx 1.3.5), here are the errors: https://gist.github.com/mitya57/06fdea89516262eae831

This is with Python 2.7.11, however I built Sphinx 1.3.4 with the same Python previously. So the regression is somewhere else (maybe in Sphinx itself)?

**Comment by stroeder** [comment]
Find failure log attached.

[Sphinx-1.3.5-test.zip](https://github.com/sphinx-doc/sphinx/files/103319/Sphinx-1.3.5-test.zip)

**Comment by shimizukawa** [comment]
@stroeder @mitya57 It seems it depends on https://github.com/sphinx-doc/sphinx/commit/5574aba60ed76f2bae947722122ac4d71ab8ed5a
Please update your Pygments version 2.1 and re-testing.

**Comment by mitya57** [comment]
@shimizukawa Right, that's what I have just figured out myself. With 2.1 it works fine. Thanks!

**Comment by stroeder** [comment]
I confirm that updating to Pygments 2.1 fixed the issue.

**Comment by birkenfeld** [comment]
Hm, this is not optimal - Sphinx tests should not depend on specific Pygments versions since we do not require 2.1.

I probably wrote these tests, so I'm not blaming anyone else. But it would be nice to rewrite them anyway.

**Comment by tk0miya** [comment]
+1 for rewriting. It makes testcases robust :-)

**Comment by tk0miya** [comment]
Note:
To be robust, we should not inspect the results of pygments. This is testcases for Sphinx, not for pygments. So we should not be care of the highlighted codes in our tests.
