### ISSUE TITLE
\begin{flushNone} with uml without :align: attribute

### ISSUE THREAD

**Issue by emmanuelmathot** [sphinx-doc/sphinx#2269]
When generating latex with `uml` directive and no `:align:` attribute, the generated latex creates an environment `flushNone` which is incorrect.

```
\begin{figure}[H]\begin{flushNone}
...
}\end{flushNone}\end{figure}
```

I dont know if the error comes from the uml code generation that should align include a `:align:` attribute when none are provided or if this case should be taken into account here:

https://github.com/sphinx-doc/sphinx/blob/b1a23817fc6e880fb7ed6c5e873f70bf65e2272b/sphinx/writers/latex.py#L1378-L1386

**Comment by tk0miya** [comment]
I think this is not a bug of Sphinx.
Please report it to the extension author (`sphinxcontrib-plantuml`?).
Sphinx does not expect the `node.attributes['align']` equals to None.

Thanks,
