### ISSUE TITLE
[fix] sphinx-build doesn't honor current Python environment

### ISSUE THREAD

**Issue by donjan** [sphinx-doc/sphinx#2270]
Sphinx (sphinx-build) 1.3.5 on a Ubuntu 14.04 system.

I need to run sphinx-build in both Python2 and Python3 environments, installed in parallel.
Boost Python requires the scripts to be run with the same version the shared objects have been built with.

Everything in the project works fine by setting up a virtualenv, except when building the Python part of the documentation: `/usr/bin/sphinx-build` points to `/usr/share/sphinx/scripts/python2/sphinx-build` respectively `/usr/share/sphinx/scripts/python3/sphinx-build` depending on which pythonX-sphinx package was installed/removed last, both of which have the Python interpreter location in the file system hardcoded in the shebang line.
This means they ignore any virtualenv settings, and either changing the symlink back and forth or having to specify a local duplicate ./sphinx-build is tedious.

A simple fix (sufficient for my case) in `/usr/share/sphinx/scripts/python2/sphinx-build` is to change
`#!/usr/bin/python`
into
`#!/usr/bin/env python`
and use only the "Python2 version" of Sphinx in either virtualenv (or bare).

I propose this shebang change (aka the proper way to do things) should be done generally for all Sphinx files.

**Comment by shimizukawa** [comment]
The sphinx-build script and its shebang are generated by pip/setuptools instead of sphinx. There is nothing to do from sphinx side.
In you case, I propose that please install sphinx in each virtualenv.
