### ISSUE TITLE
Exception in  C++ domain

### ISSUE THREAD

**Issue by ngladitz** [sphinx-doc/sphinx#2271]
I currently don't have a reduced test case for this but on one of my systems I get the following exception with the current master branch:

```
Exception occurred:
  File "/usr/local/lib/python2.7/dist-packages/sphinx/domains/cpp.py", line 4060, in _resolve_xref_inner
    contnode.pop(0)
AttributeError: 'Text' object has no attribute 'pop'
```

I am hoping this is something obvious (perhaps specific to my system since I think it might be working on other systems).

**Comment by jakobandersen** [comment]
I can't reproduce it at the moment. It's somehow related to a reference that resolves to a function. It would be great if you have time make a small test case.
(Note: Line 4060 with the exception was introduced in connection with #2178.)

**Comment by ngladitz** [comment]
I reduced it to:

```
.. cpp:function:: const bar & bar() 

```

What seems to trigger it in this case is the function and the return type having the same name.

**Comment by jakobandersen** [comment]
Great, I'll look into it. Though I'm curious, in which context is that declaration meaningful? (Sphinx should of course not crash no matter what.)

**Comment by ngladitz** [comment]
e.g. in boost filesystem directory_entry has a member [1]:

```
const path& path() const;
```

[1] http://www.boost.org/doc/libs/1_60_0/libs/filesystem/doc/reference.html#directory_entry-observers

**Comment by jakobandersen** [comment]
It looks like this a simplification of the Boost documentation, as the real code seems to be (`boost/filesystem/operations.hpp:701`):

``` c++
const boost::filesystem::path&  path() const
```

It would be nice with a compilable example to make sure the lookups are correct in the end. My attempt with GCC doesn't compile:

```
test.cpp:12:2: error: declaration of ‘bar& foo::bar()’ [-fpermissive]
  }
  ^
test.cpp:1:8: error: changes meaning of ‘bar’ from ‘struct bar’ [-fpermissive]
 struct bar {
        ^
```

`test.cpp`:

``` c++
struct bar {
    bar(int a) : a(a) { } 
public:
    int a;
};

bar g(42);

struct foo {
    bar &bar() {
        return g;
    }   
};

void test() {
    foo f;
    bar &b = f.bar();
}
```

**Comment by ngladitz** [comment]
Hm yes I see what you mean.
My documentation generator performs the same simplification (it removes the namespace from the return type if there has been a matching "cpp:namespace::" directive before).

Your example does seem to compile with clang ... I don't know which compiler is right though.

**Comment by jakobandersen** [comment]
The crash has been fixed, but the link for the return type will target the function itself. I will wait with changing the lookup rules until we find out which compiler is right. Thanks again for finding the bug.

**Comment by ngladitz** [comment]
Thanks for the quick fix!

I tried the example in VS2015 too now where it works as well but I am aware that standard conformance is not a question of majority :)
