### ISSUE TITLE
Feature request: GIF support in latexpdf builder

### ISSUE THREAD

**Issue by kottkrig** [sphinx-doc/sphinx#2272]
## Repro Steps
1. Refence a GIF image in source files
2. Run `make latexpdf`

**Expected:** The GIF should be visible in the generated PDF. If it's an animated GIF, show the first frame.
**Actual:** `make latex` produces an error `! LaTeX Error: Unknown graphics extension: .gif.` and the image is not visible in the generated pdf.

**Comment by jfbu** [comment]
Citation from pdftex manual: "pdfTEX supports inclusion of pictures in png, jpeg, jbig2, and pdf formats." 

Hence, the gif format is not supported. What you can do is convert the gif `foo.gif` to `foo.png`, then, according to 

http://www.sphinx-doc.org/en/stable/rest.html#images

code in your `.rst` file:

```
.. figure:: foo.*
```

The LaTeX builder will then select the `foo.png` file and create the latex source to use it. Actually the html builder also, as I just tested. Seems to match this order:

```
supported_image_types = ['image/svg+xml', 'image/png', 'image/gif', 'image/jpeg']
```

from http://www.sphinx-doc.org/en/stable/builders.html#builders

Ah, there seems to be a bug in the LaTeX builder image supported types:

```
supported_image_types = ['application/pdf', 'image/png', 'image/gif', 'image/jpeg']
```

as, as said above, `gif` is not usable directly by pdflatex.

**Comment by lehmannro** [comment]
It _seems_ [media9](https://www.ctan.org/pkg/media9) is the LaTeX way to include GIFs into PDFs.  Until somebody builds support for that, I'd agree that removing `image/png` from LaTeXBuilder seems sensible.

**Comment by tk0miya** [comment]
I removed `image/gif` rom supported_image_types of LaTeX writer.

Now, pdflatex does not support GIF format. So we cannot support it at this present.
Please let me know if pdflatex supports it or commonly used package to do that appears.

Thanks,
