### ISSUE TITLE
Parallel builder fails to unpack certain exceptions under python2

### ISSUE THREAD

**Issue by ngoldbaum** [sphinx-doc/sphinx#2275]
This is a weird one.

I've created a repository that constitutes a minimal example to trigger this behavior. It's located here:

https://github.com/ngoldbaum/sphinx-bug

To trigger the error just do `make html`, you'll get back the following error:

```
Exception occurred:
  File "/Users/goldbaum/Documents/sphinx/sphinx/util/parallel.py", line 97, in _join_one
    exc, result = pipe.recv()
TypeError: ('__init__() takes exactly 2 arguments (1 given)', <class 'bad-extension.MyChildException'>, ())
```

The full traceback is here:

https://gist.github.com/ngoldbaum/7c09582f94ac94bb740d

This happens in the example when the extension (see `extensions/bad-extension.py`) I've defined raises an exception has a string attribute defined on it. It doesn't happen with a trivial exception (i.e. deleting the implementation of `__init__` and `__str__`.

As far as I can tell, the `TypeError` is being raised inside the multiprocessing library, so I guess it's bug in Python itself. I can trigger this on Python 2.7.11. Under Python 3.5.1 I get the error message I expect back.

Should sphinx be adapting for python2, possibly sanitizing the objects it sends over a multiprocessing pipe? I think this might be fixable by not sending arbitrary exception objects over the pipe, but that seems like it would trigger a substantial corresponding change in sphinx....

**Comment by ngoldbaum** [comment]
I can't find a bug for this on the python issue tracker, but I gather that multiprocessing was completely rewritten for Python3.3

**Comment by tk0miya** [comment]
With python-2.7.14 and sphinx-1.6.6, it works fine.
```
$ python -V
Python 2.7.14
$ make html
sphinx-build -b html -d build/doctrees  -j2 source build/html
Running Sphinx v1.6.6
making output directory...
/Users/tkomiya/work/tmp/doc/sphinx-bug/lib/python2.7/site-packages/sphinx/util/compat.py:40: RemovedInSphinx17Warning: sphinx.util.compat.Directive is deprecated and will be removed in Sphinx 1.7, please use docutils' instead.
  RemovedInSphinx17Warning)
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 9 source files that are out of date
updating environment: 9 added, 0 changed, 0 removed
reading sources... [100%] index
waiting for workers...

Sphinx parallel build error:
MyChildException: error message
make: *** [html] Error 1
```

I don't know when this was fixed. Anyway, this issue is no longer needed.
So I'm closing this now.

Thank you for reporting!
