### ISSUE TITLE
sphinx extension/sphinxcontrib testing

### ISSUE THREAD

**Issue by fkromer** [sphinx-doc/sphinx#2277]
I would like to test my [extension for sphinx-doc which i have under version control in my sphinx-doc project](https://github.com/fkromer/eswp3/tree/master/exts/sphinxcontrib-p3). Running `make html` over the project results in the expected behaviour and the results of my first low-level unit tests (_tests/test_p3.py_) are fine. However if i try to run the acceptance tests (_tests/test_html.py_) using `sphinx-testing` inspired by [extension blockdiag](https://github.com/blockdiag/sphinxcontrib-blockdiag/blob/master/tests/test_html.py) i get an import error for `sphinx_testing`. `with_app` is imported with `from sphinx_testing import with_app`. In the built-in extensions like [sphinx.ext.graphviz](https://github.com/sphinx-doc/sphinx/blob/master/tests/test_ext_graphviz.py) it is imported using `from util import with_app`. How can i run my tests?

**Comment by tk0miya** [comment]
Could you install `sphinx_testing` package? It is not included in Sphinx package.
https://pypi.python.org/pypi/sphinx-testing/

BTW, Sphinx does not use `sphinx_testing` for its testing. So `sphinx_testing.with_app` and `util.with_app` are different.

**Comment by fkromer** [comment]
@tk0miya Thanks for the hint. I could install `sphinx-testing`. My directory structure should be the same as in [sphinxcontrib-blockkdiag](https://github.com/blockdiag/sphinxcontrib-blockdiag/tree/master) expect from the fact that i do not have separate subdirs _basic_ and _subdir_ in _tests/docs/_ but only _tests/docs_. But if i try to run the acceptance tests with `python -m unittest test_html.py` in _exts/sphinxcontrib-p3/tests_ (like i do for the unit tests with `python -m unittest test_p3.py` in the same directory) i get an error.

```
ERROR: test_href_in_p1 (test_html.TestSphinxcontribP3HTML)
File "/usr/local/lib/python3.4/dist-packages/sphinx_testing/util.py", line 139, in decorator
app = TestApp(*self.sphinxargs, **sphinxkwargs)
File "/usr/local/lib/python3.4/dist-packages/sphinx_testing/util.py", line 51, in __init__
srcdir.copytree(tmproot)
File "/usr/local/lib/python3.4/dist-packages/sphinx_testing/path.py", line 118, in copytree
shutil.copytree(self, destination, symlinks=symlinks)
names = os.listdir(src)
FileNotFoundError: [Errno 2] No such file or directory: path('/home/florian/ws_github/eswp3/exts/sphinxcontrib-p3/tests/tests/docs')
```

When i adjust the `srcdir` in `test_html.py`

```
with_svg_app = with_app(srcdir= 'docs' # original from blockdiag: 'tests/docs',
                        buildername='html',
                        write_docstring=True)
```

i get another error:

```
...
File "/usr/local/lib/python3.4/dist-packages/sphinx/application.py", line 435, in setup_extension
err)
sphinx.errors.ExtensionError: Could not import extension sphinxcontrib.p3 (exception: No module named 'sphinxcontrib'
```

**Comment by tk0miya** [comment]
In first case, `with_app` accepts `srcdir` as relative path from current directory or absolute path. So it is better to use absolute path (or always execute test script in same directory).

Second case is a problem of python. Can your test script import `sphinxcontrib.p3`?
Maybe, it had better to add the path to root directory of the extension to your `sys.path`.

BTW, In my case (in sphinxcontrib-blockdiag), I use `tox` and `nose` as test runner.
It clears both of issues. They install the extension into brandnew virtualenv, and execute the test scripts.

**Comment by fkromer** [comment]
I did definitely have an import issue: I separated the extension from my sphinx-doc project into a [separate github project](https://github.com/fkromer/sphinxcontrib-p3) and set up travis-ci. (I used sphinxcontrib-blockdiag as template, thanks by the way for this great extension!) All travis builds [like this one](https://travis-ci.org/fkromer/sphinxcontrib-p3/jobs/106338745) state an import error `196 ImportError: No module named 'p3'`.
I diffed `sphinxcontrib-blockdiag` and `sphinxcontrib-p3` but was not able to identify any differences related to this problem... until i discovered the import error in `test_p3.py` (used for "low level" unit tests which may be run independently from `sphinx-testing`). As `sphinx-blockdiag` does use `sphinx-testing` for all tests i did not catch it right away...

**Comment by tk0miya** [comment]
Now, it looks fine to me. Maybe this commit works https://github.com/fkromer/sphinxcontrib-p3/commit/9d862a4c4034b3b92846d4aa4d105f72a30a28c8 :-)

It seems there are no problems for testing the extension.
May I close this issue?

**Comment by fkromer** [comment]
Sure, you can close this issue. Thank you a lot.

**Comment by tk0miya** [comment]
OK. Have fun for hacking!
Please post a mail to [sphinx-devel group](https://groups.google.com/forum/#!forum/sphinx-dev) if you have any problems on developing extensions :-)
