### ISSUE TITLE
page_source_suffix not in 1.3.5

### ISSUE THREAD

**Issue by ericholscher** [sphinx-doc/sphinx#2278]
I added a a while ago adding page_source_suffix to HTML context, so you can tell if you're working on markdown or rst files. It isn't included in 1.3.5:

https://github.com/sphinx-doc/sphinx/blob/1.3.5/sphinx/builders/html.py#L427

It however has been in master for a long time:

https://github.com/sphinx-doc/sphinx/blob/master/sphinx/builders/html.py#L431

How is it not included in any of the releases?

**Comment by ericholscher** [comment]
Seems like it isn't included in the `stable` branch, so it isn't being included in releases. How do I get this included in stable?

**Comment by ericholscher** [comment]
This is the commit -- should be backwards compat, and included in releases, I think: https://github.com/sphinx-doc/sphinx/commit/5f6503c905e67c12b6050e1f49682feab0389126

**Comment by tk0miya** [comment]
At this moment, the milestone for v1.4 is put on Feb. 8th.
So I think next major release is coming within a month (maybe beta releases are needed before proper one)

@shimizukawa Let us know about the release plan.

**Comment by shimizukawa** [comment]
I'm going to release 1.4 alpha 1 around Feb 14th. I'll send my 1.4 release schedule to sphinx dev ML later.

**Comment by ericholscher** [comment]
Great -- I guess my question is what I would have done differently to get that patch into the 1.3.x release? It's arguably a bug fix for the suffix support, as pages can't tell what markup they were rendered from.

**Comment by birkenfeld** [comment]
I assume there was a PR made against the master branch.  Bugfix releases are made from the stable branch.

**Comment by birkenfeld** [comment]
That said, it is also our responsibility as maintainers to check whether a PR against master should go to stable instead.

**Comment by tk0miya** [comment]
+1 for stable.

Surely, `page_source_suffix` is a new template variable. 
But it is a bug of multiple parsers support.
And it seems the commits is not a breaking change.

**Comment by ericholscher** [comment]
:+1: -- would love to see this get merged into a stable release as soon as possible. Should I open a PR against `stable` for this?

**Comment by birkenfeld** [comment]
Yes, please. I don't know when @shimizukawa has planned the next 1.3.x release.

**Comment by shimizukawa** [comment]
Ah, ok, I'll cherry-pick the commit by #1876 to avoid merge conflict.
BTW, I'm planning to release 1.3.6 around the end of this month (Feb, 2016).

**Comment by shimizukawa** [comment]
Now stable branch contains a 5f6503c905e6 change for page_source_suffix.

**Comment by ericholscher** [comment]
Thanks!
