### ISSUE TITLE
Highlighting of one block can affect another

### ISSUE THREAD

**Issue by prattmic** [sphinx-doc/sphinx#2280]
Here is the simple reproducer: https://gist.github.com/prattmic/74d997aebb067facf99b

Both `01works.rst` and `02broken.rst` contain the same `sourcecode` blocks, just in a different order. `01works.rst` builds just fine, but `02broken.rst` emits the warning `02broken.rst:15: WARNING: Could not parse literal_block as "http". highlighting skipped.` This warning is new (#2264), which has helped make this bug more apparent.

The problem seems to be that Sphinx reuses the same Pygments Lexer for all code blocks of the same language (created [here](https://github.com/sphinx-doc/sphinx/blob/92e4b0cac6d522e6c10d8473e7257f3e6ad42cc3/sphinx/highlighting.py#L167)).

The Pygments HTTP Lexer ([source](https://bitbucket.org/birkenfeld/pygments-main/src/b483ad23e36e79d51700f995b622a066371de814/pygments/lexers/textfmts.py?at=default&fileviewer=file-view-default#textfmts.py-113)) is stateful. Note that in `header_callback`, the lexer saves `self.content_type` if it encounters the `Content-Type` HTTP header. Then in `content_callback`, it tries to lex the content as `self.content_type`.

In `02broken.rst`, the first code block has a `Content-Type` of JSON, so the content is lexed as JSON. The second block does not have `Content-Type`, so `self.content_type` remains set to JSON, causing the lexer to attempt to lex the content as JSON. Since the content is not valid JSON, the highlighting fails.

I think the correct behavior is for Sphinx to create a new Lexer object for each code block, thus avoiding any stateful changes from affecting another block.

**Comment by birkenfeld** [comment]
Hm, I rather consider that broken behavior of the lexer.  I fixed it in Pygments, it will be part of its next bugfix release.

Thanks for the report!

**Comment by huayra** [comment]
I'm hitting a similar bug with sphinx 1.5 and pygmentize 2.2 (built from source) when using the VCL (tried with vclsnippet also) lexer with literal includes. It keeps failing on me.

Should I be looking at a solution on Sphinx or rather try to see whether the lexer(s) is the one not working?
