### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by radarhere** [sphinx-doc/sphinx#2281]
Hi.

As described in python-pillow/Pillow#1494, the `title` tag for https://pillow.readthedocs.org/en/3.1.x/ lists the Pillow version as 2.6.1, where one would expect it to be 3.1.0.
- https://github.com/python-pillow/Pillow/blob/3.1.x/docs/conf.py#L126-L128 shows that `html_title` is not defined.
- https://github.com/python-pillow/Pillow/blob/3.1.x/docs/conf.py#L62 shows that `release` is the Pillow version
- https://github.com/python-pillow/Pillow/blob/3.1.x/PIL/__init__.py#L15 shows that the Pillow version is 3.1.0

I originally created an issue to investigate this - https://github.com/rtfd/readthedocs.org/issues/1852 - but the response that I received as that this was a Sphinx issue. If you have any thoughts, that would be good.

**Comment by lehmannro** [comment]
I clicked _Build version: `3.1.x`_ on ReadTheDocs, and now it seems fixed.  Sphinx gets this value straight from `conf.py`, so I'm going to defer this to RTD failure.

**Comment by radarhere** [comment]
Thanks very much.
