### ISSUE TITLE
symfony-docs Exception occurred

### ISSUE THREAD

**Issue by xxfaxy** [sphinx-doc/sphinx#2286]
File "/home/test/symfony-docs/_theme/_templates/layout.html", line 6, in <module>
    {% set isIndex = pagename is index %}
TemplateAssertionError: no test named 'index'
The full traceback has been saved in /tmp/sphinx-err-ng9Bu_.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at https://github.com/sphinx-doc/sphinx/issues. Thanks!
Makefile:45: recipe for target 'html' failed
make: **\* [html] Error 1

**Comment by lehmannro** [comment]
In our templating engine Jinja2, `is` is the _test operator,_ eg. `pagename is lower`.  This is definitely an user error.

I'm going to leave this bug open to fix the error message;  it seems there is currently no handling for `jinja2.TemplateError` (bonus points if we detect if the file is a Sphinx asset or not.)

**Comment by tk0miya** [comment]
Fixed by #4752 
Thank you for reporting!
