### ISSUE TITLE
Configuration variables for built-in domains

### ISSUE THREAD

**Issue by jakobandersen** [sphinx-doc/sphinx#2293]
I would like to add some configuration options for the C++ domain, but I can't find any way to do it without modifying the central Config class. It seems this has already happened with two config variables, `add_module_names` and `modindex_common_prefix`, that "belong" to the Python domain.
I would however prefer to keep C++ specific stuff in a single file.
Would it be possible to have an optional `setup` method on the built-in domains that gets called at the appropriate time? (similar to how external extensions work) Or is there some other mechanism already in place for this?

**Comment by lehmannro** [comment]
It should be easy to pass `app` to the domain's `__init__` method (see `sphinx.application.Sphinx._init_env` for where domains are currently intialized.)

(You could, in theory, access the configuration values through `domain.env.config`, but that doesn't give you the nice Sphinx API.)

**Comment by jakobandersen** [comment]
I would indeed be nice to use the normal API for extensions. It seems that `_init_env` is called after all configuration values has been initialised and checked. Isn't it too late to add new variables then?

**Comment by tk0miya** [comment]
+1

I'd like to make the bundled modules (builders, domains and so on) as extension in future version. And they set up itself.
It gives loose coupling to Sphinx and Sphinx becomes more robust, I believe.

BTW, I think initializing them is good for before loading any user-given extensions instead of `_init_env`.

**Comment by jakobandersen** [comment]
Fixed by PR #2748. Thanks!
