### ISSUE TITLE
Sample of what markdown is valid for use in Sphinx & which isn't?

### ISSUE THREAD

**Issue by brianjking** [sphinx-doc/sphinx#2303]

**Comment by shimizukawa** [comment]
Actually it depends on commonmark spec and recommonmark implementation.
If any commonmark notation are not supported by recommonmark, please report it to https://github.com/rtfd/recommonmark/

**Comment by birkenfeld** [comment]
Can we add this info to the docs somewhere?

**Comment by tk0miya** [comment]
Documented at #3373.

**Comment by donatelloOo** [comment]
what about the support of GitHub Flavored Markdown (GFM) ?
it is certainly one of the best flavor (until included in CommonMark ?) and could be the missing build chain item for serious integration !

**Comment by tk0miya** [comment]
AFAIK, there are no way to handle gfm files.
Your contribution is always welcome!
