### ISSUE TITLE
'\tablename - continued from previous page' is wrapped with textsf in LaTeX

### ISSUE THREAD

**Issue by vlotorev** [sphinx-doc/sphinx#2308]
![git-local-commit3](https://cloud.githubusercontent.com/assets/5903498/12990260/88388690-d11a-11e5-98ba-d6a09033cb84.png)
as per https://github.com/sphinx-doc/sphinx/blob/master/sphinx/writers/latex.py#L1005
'\tablename - continued from previous page' is wrapped with textsf which gives different look for table caption and 'continued from previous page'.
IMHO they should look in a similar way, because the 'continuation' is placed at the same place (above the table)

My request is to wrap captions (as well as 'continuations' for tables) with some macro which can be easily redefined from custom user preabmle.

**Comment by tk0miya** [comment]
Now, I defined `\tablecontinued` macro to decorate continued labels at d9be95a.

So, you can change the style like following settings::

```
latex_elements['preamble'] = """
\\renewcommand{\\tablecontinued}[1]{\\textcolor{red}{#1}}
"""

Thanks,
```

**Comment by vlotorev** [comment]
Thanks.
