### ISSUE TITLE
`code-block` disappear if no parameter is given after a `highlight` directive

### ISSUE THREAD

**Issue by xuhdev** [sphinx-doc/sphinx#2328]
Example:

``` rst
.. highlight:: java

.. code-block::
   :linenos:

   class X
```

**Comment by tk0miya** [comment]
Thank you for reporiting. But this is not a bug.
The `code-block` directive requires an argument. You'd have seen following error message on building docs.

```
/Users/tkomiya/work/tmp/doc/index.rst:11: ERROR: Error in "code-block" directive:
1 argument(s) required, 0 supplied.

.. code-block::
   :linenos:

   class X
```

Sphinx skips processing the code-block because of error.
Then it looks like the code-block disappears.

Thanks,
