### ISSUE TITLE
"Copy downloadable files" is not adjustable to the environmenent change during building process

### ISSUE THREAD

**Issue by xxks-kkk** [sphinx-doc/sphinx#2329]
**Problem Description**:
copying downloadable files... [100%] /home/zeyuan_hu/Documents/zeyuan-s-doc/source/project/db2fedsvrcfg/db2fedsvrcfg-debug-loWARNING: cannot copy downloadable file u'/home/zeyuan_hu/Documents/zeyuan-s-doc/source/project/db2fedsvrcfg/db2fedsvrcfg-debug-log-impala.html': [Errno 2] No such file or directory: u'/home/zeyuan_hu/Documents/zeyuan-s-doc/source/project/db2fedsvrcfg/db2fedsvrcfg-debug-log-impala.html'

**How to Reproduce**:
1. Suppose I have two sphinx working directories: `/home/foo/source` and  `/home/bar/source` with git properly setup.

**Note:** both source directories point to the same git repo
# Inside `/home/foo/source`
1. Create a rst file with `:download:` directive and assign a download target file right after it.
2. do `make html`
3. `git add "files"; git commit -m "Reproduce issue"; git push`

**Note: we tack the build output files in git as well**
# Inside `/home/bar/source`
1. We do `git pull` and do some editing in rst files in `/home/bar/source`
2. Run `make html`
3. Error reproduced like the one in the problem description.

Essentially, sphinx doesn't check the build environment difference. It would be nice it able to do a little environment detection before raising _cannot copy downloadable file_ warning

**Comment by tk0miya** [comment]
Thank you for reporting

**Comment by xxks-kkk** [comment]
My pleasure :smile:
