### ISSUE TITLE
Is LaTeX builder use of xcdraw option for xcolor really needed ? (confuses xdvi)

### ISSUE THREAD

**Issue by jfbu** [sphinx-doc/sphinx#2331]
Commit 454a4b9c655380dbcb50409127ff98932fc61653 introduces the use of 

``` latex
\RequirePackage[xcdraw]{xcolor}
```

The `xcdraw` option causes `dvi` output from latex run to confuse `xdvi`  viewer. Only postscript file obtained via `dvips` is then OK. This can be tested with 

``` rst

Testing code-block
==================

.. code-block:: python
   :linenos:

   def foo(x,y):
       return None

```

After `make latex` and then `latex` on the `.tex` file, the `dvi` does not display correctly:

![capture d ecran 2016-02-17 a 11 41 13](https://cloud.githubusercontent.com/assets/2589111/13106955/60d9f7e6-d56b-11e5-8f2c-b02da8fea8a1.png)

Without `xcdraw` option:

![capture d ecran 2016-02-17 a 11 45 08](https://cloud.githubusercontent.com/assets/2589111/13107067/127ef014-d56c-11e5-91f5-b964a07d3e13.png)

(as an aside producing dvi was broken before commit 297c1647110b766c6d0aeadcbaa74a365d75d2a1 due to forced `pdftex` graphicx option).

The documentation of `xcolor` (not updated since 2007) says 

```
Option xcdraw uses PostScript commands to draw frames and color boxes in case
of the dvips driver and PDF code to draw frames in case of the pdftex and
dvipdfm drivers. This is still experimental code that may confuse .dvi viewers.
```

On the other hand the graphicx drivers for various output engines (xetex, dvipdfmx, pdftex) are maintained by various people, hence I am not sure `xcdraw` option is such a good thing nowadays.

Is there some pdf output to demonstrate that behaviour is better with `xcdraw` ?

If the option is kept perhaps the documentation for LaTeX should say that `latex+dvips` is possible but that the intermediate `dvi` files from `latex` run will not display properly code-blocks.

**Comment by jfbu** [comment]
See http://tex.stackexchange.com/questions/294409/does-option-xcdraw-to-package-xcolor-do-any-good-nowadays, and current answer http://tex.stackexchange.com/a/294428/4686 which says this option `xcdraw` was _only for special cases, years ago._

**Comment by tk0miya** [comment]
The option comes from #1906.
And it still looks fine to me if the `xcdraw` option removed.

@kieranh5511 Are there any reason to use `xcdraw` option?

**Comment by kieranh5511** [comment]
I should confess that I more or less use `xcdraw` with `xcolor` out of habit.  I'll dig out the files that were causing problems to check but I'm pretty sure that it can be dropped.

**Comment by tk0miya** [comment]
Now, I remove the `xcdraw` option at 84fb1b7.

Thanks!

**Comment by jfbu** [comment]
@tk0miya @kieranh5511  Thanks, I will keep an eye on any additional information I may come across relative to `xcdraw`.
