### ISSUE TITLE
Parsing strategy for code to highlight

### ISSUE THREAD

**Issue by birkenfeld** [sphinx-doc/sphinx#2332]
With the change to default "python3" highlighting in 1.4, I intentionally didn't add the try-parse step for code blocks with "python3" language. 423bf7b added it back, but when Sphinx is running under Python 2, it will fail to highlight blocks with Python 3 syntax.

We'll need a lenient parser for Python code (basically py3 plus print statement, `except Exc, e` and other py2-isms) if we want to continue doing this check.

We can investigate if we can use the pgen2 parser in `sphinx.pycode`. But it currently has two different grammars as well.

**Comment by tk0miya** [comment]
I understand. Sorry, I didn't check the what the `try_parse()` does.
Sure, my change breaks the python3 highlighting on python2 environment.
BTW, 
Do you mean the `try_parse()` misdetects in spite of the code is written in python3?
If so, I understand the problem and +1 for improving it.

BTW,

**Comment by tk0miya** [comment]
I understand. Sorry, I didn't check the what the try_parse() does.
Sure, my change breaks the python3 highlighting on python2 environment.

BTW, what do you think about the fallbacks?
I think it is needed if the python3 language become as default settings.

**Comment by tk0miya** [comment]
I merged #2339 into master branch. So this issue might be meaningless now.
Can I close this issue?

**Comment by birkenfeld** [comment]
Sure!
