### ISSUE TITLE
autosummary with toctree always lists imported members

### ISSUE THREAD

**Issue by lsaffre** [sphinx-doc/sphinx#2336]
I continue to have the problem which I tried to describe in #2144. At that time there was some hassle because my patch caused problems elsewjere. Opening a new ticket, this time with a (hopefully) clean patch. It is inspired by 
http://stackoverflow.com/questions/25405110/sphinx-autosummary-with-toctree-also-lists-imported-members and the solution described there. The patch is against today's master from github.
[20160218.txt](https://github.com/sphinx-doc/sphinx/files/136248/20160218.txt)

**Comment by tbetbetbe** [comment]
I'm seeing this as well.  Thanks for the patch! 
FYI @vsubramani

**Comment by lsaffre** [comment]
NB: how I apply the patch:
  $ patch -p1 < 20160218.txt
I had to apply it myself again after updating my copy of the repository. Note also that if you had the problem and applied the patch, you must remove the files generated by autosummary so that they get generated again without imported members.

**Comment by lsaffre** [comment]
What a pity, this problem is still open in Sphinx 1.5a2. Is there any problem with my patch?

**Comment by lsaffre** [comment]
Here is a slightly modified patch which fixes a failure in the Sphinx test suite caused by my first patch.

[20160218_autosummary.txt](https://github.com/sphinx-doc/sphinx/files/504606/20160218_autosummary.txt)

**Comment by lsaffre** [comment]
Here is above patch, adapted for 1.6 (currently in development)
[fix2336_autosummary.txt](https://github.com/sphinx-doc/sphinx/files/646555/fix2336_autosummary.txt)

**Comment by shimizukawa** [comment]
Fixed by #3235. Thanks to @lsaffre !
