### ISSUE TITLE
use \url{URL} macro instead of \href{URL}{URL}

### ISSUE THREAD

**Issue by vlotorev** [sphinx-doc/sphinx#2337]
simple rst text

```
link to https://asdf.com
```

is written to LaTex using href macro like: 

``` latex
 .... href{https://asdf.com}{https://asdf.com}
```

In case link is long and doesn't have dashes there is no way to hyphenate or wrap it
and it's overflowing the page margin.

All the solutions I googled was for 'url' macro and not for 'href'
(e.g breakurl package, \PassOptionsToPackage{hyphens}{url}\usepackage{hyperref}, etc.)

So with 'href' macro user has almost no conrol over href breaking and hyphenating.

My request is to replace generation of 'href{URL}{URL}' with 'url{URL}'.
Which would be more native to Tex environment and eliminate text overflow problem.

**Comment by jfbu** [comment]
In this context, there is `\urlstyle`. Indeed, by default `\url` will use monospace font. This is not the case for `\href` thus, switching to `\url` will change the look of all documents. But one can use `\urlstyle{rm}`,  `\urlstyle{sf}`, or perhaps simpler `\renewcommand*\UrlFont{\normalfont}` or replace `\normalfont` by `\sffamily` or `\rmfamily`...

As an aside although `\url` does help in breaking links, it breaks only at certain locations. You already mention  `\PassOptionsToPackage{hyphens}{url}` before loading `hyperref`. It is possible to define `\UrlBreaks` command to tell `url` more characters where breaks are allowed.

**Comment by jfbu** [comment]
I am adding this for reference. 

In particular `\urlstyle{same}` allows to keep for URLs typeset with `\url` the current text font, rather than switching to mono-space family.

Also one finds in the code comments which characters will allow linebreaks. Notice though that linebreaks happen _after_ said characters. Package `url` has no facility to allow breaks _before_ given characters.

``` latex
\documentclass{article}
\usepackage[T1]{fontenc}

%\PassOptionsToPackage{hyphens}{url}
\usepackage{hyperref}

%\urlstyle{sf}, \urlstyle{rm}, \urlstyle{tt}<-default

\urlstyle{same}% Use current text font.

% EXTRACTS FROM url SOURCE CODE (with comments added)
% % default style assignments

% List of characters with breaks allowed AFTER THEM.
% \def\UrlBreaks{\do\.\do\@\do\\\do\/\do\!\do\_\do\|\do\;\do\>\do\]%
%  \do\)\do\,\do\?\do\&\do\'\do+\do\=\do\#}%

% List of characters where break can only occur at end of consecutive ones
% hyphen activated only under option hyphens
% \def\UrlBigBreaks{\do\:\do@url@hyp}%

% No breaks after those characters
% \def\UrlNoBreaks{\do\(\do\[\do\{\do\<}%

% Defined to add up easily to \UrlBreaks
% 
% \def\UrlOrds{\do\*\do\-\do\~\do\'\do\"\do\-}% (remark \- twice there)

% One can do
%  \makeatletter \g@addto@macro\UrlBreaks{\UrlOrds}\makeatother
% to add *, -, ~, ' and " to the \UlrBreaks list.

\begin{document}


\hrule
\sffamily

\url{https://github.com/sphinx-doc/sphinx/issues/2337} \url{https://github.com/sphinx-doc/sphinx/issues/2337} \url{https://github.com/sphinx-doc/sphinx/issues/2337} \url{https://github.com/sphinx-doc/sphinx/issues/2337} \url{https://github.com/sphinx-doc/sphinx/issues/2337} \url{https://github.com/sphinx-doc/sphinx/issues/2337} \url{https://github.com/sphinx-doc/sphinx/issues/2337}

\rmfamily

\url{https://github.com/sphinx-doc/sphinx/issues/2337} \url{https://github.com/sphinx-doc/sphinx/issues/2337} \url{https://github.com/sphinx-doc/sphinx/issues/2337} \url{https://github.com/sphinx-doc/sphinx/issues/2337} \url{https://github.com/sphinx-doc/sphinx/issues/2337} \url{https://github.com/sphinx-doc/sphinx/issues/2337} \url{https://github.com/sphinx-doc/sphinx/issues/2337}

\itshape

\url{https://github.com/sphinx-doc/sphinx/issues/2337} \url{https://github.com/sphinx-doc/sphinx/issues/2337} \url{https://github.com/sphinx-doc/sphinx/issues/2337} \url{https://github.com/sphinx-doc/sphinx/issues/2337} \url{https://github.com/sphinx-doc/sphinx/issues/2337} \url{https://github.com/sphinx-doc/sphinx/issues/2337} \url{https://github.com/sphinx-doc/sphinx/issues/2337}

\bfseries\sffamily

\url{https://github.com/sphinx-doc/sphinx/issues/2337} \url{https://github.com/sphinx-doc/sphinx/issues/2337} \url{https://github.com/sphinx-doc/sphinx/issues/2337} \url{https://github.com/sphinx-doc/sphinx/issues/2337} \url{https://github.com/sphinx-doc/sphinx/issues/2337}

\hrule

\end{document}
```

![urltest](https://cloud.githubusercontent.com/assets/2589111/13201730/15606a3c-d87e-11e5-91d9-7663342f1820.png)

**Comment by vlotorev** [comment]
> In this context, there is \urlstyle. Indeed, by default \url will use monospace font. This is not the case for \href thus, switching to \url will change the look of all documents. But one can use \urlstyle{rm}, \urlstyle{sf}, or perhaps simpler \renewcommand*\UrlFont{\normalfont} or replace \normalfont by \sffamily or \rmfamily...

Hi jfbu. Yes, switching from `href{URL}{URL}` to `url{URL}` most definitely will require `sphinx.sty` to be updated to redefine `url` macro so that old documents looked in the same way as previously with `href`.

**Comment by jfbu** [comment]
Issuing in `sphinx.sty` `\urlstyle{same}` after `\RequirePackage[...]{hyperref}` promises that the font used for `\url{URL}` will be the same as current text font at the location of `\url`, hence with the same looks as from `\href{URL}{URL}`.

However, this replacement should not be done inside arguments to sectioning units. Try:

```
\section{\url{https://github.com/sphinx-doc/sphinx/issues/2337}}
```

and you will see that it raises an error on second LaTeX run. One must use

```
\section{\texorpdfstring{\url{https://github.com/sphinx-doc/sphinx/issues/2337}}{https://github.com/sphinx-doc/sphinx/issues/2337}}
```

**Comment by fredrik-johansson** [comment]
+1 for using \url{}

I would also like an easy way to use tt font style for URLs.

**Comment by tk0miya** [comment]
Thank you for comment, all :-)
I replaced it with `\url` macro now.

But I do not pass to `hyphens` option to url package.
The documentation of url package says about the option:

> Ordinarily, breaks are not allowed after “-” characters because this leads to
> confusion. (Is the “-” part of the address or just a hyphen?) The package option
> “[hyphens]” allows breaks after explicit hyphen characters. The \url command
> will never ever hyphenate words.

I think this is not good for the default settings of Sphinx.
if you want to give the option, please configure it on your conf.py:

```
latex_elements['passoptionstopackages'] = r"\PassOptionsToPackage{hyphens}{url}"
```

Thanks,

**Comment by jfbu** [comment]
@tk0miya I tried it on some real life project of mine and it works fine. Also I checked with 

``` rst

========================
Testing URLs in headings
========================

See http://www.sphinx-doc.org
-----------------------------

Hello, see http://www.sphinx-doc.org.
```

to see what happened inside headings but anyhow even before the new commit, it seems no link is generated by the Sphinx latex writer in such locations, hence the switch to `\url` causes no problems there.

**Comment by jfbu** [comment]
@fredrik-johansson to use `tt` font style for URLs now after 0211e19ae6d303f6c814fc6753c1e0024ce5bf6d, you only need to include `\urlstyle{tt}` in `'preamble'` key for example. Something like

``` rst
latex_elements = {
# The paper size ('letterpaper' or 'a4paper').
#'papersize': 'letterpaper',

# The font size ('10pt', '11pt' or '12pt').
# 'pointsize': '12pt',

# Additional stuff for the LaTeX preamble.
'preamble': r'\urlstyle{tt}',

# Latex figure (float) alignment
#'figure_align': 'htbp',
}
```

**Comment by tk0miya** [comment]
Ah, sorry, I fogget to comment that.
Sphinx does not generate any hyperlinks inside headings now.
It comes from this line:
https://github.com/sphinx-doc/sphinx/blob/0211e19ae6d303f6c814fc6753c1e0024ce5bf6d/sphinx/writers/latex.py#L1599

In this fix, I don't touch the behavior.

**Comment by fredrik-johansson** [comment]
Awesome, thanks for fixing this!

**Comment by vlotorev** [comment]
Thanks.
