### ISSUE TITLE
LaTex Internal link style inconsistency

### ISSUE THREAD

**Issue by vlotorev** [sphinx-doc/sphinx#2338]
LaTex writer creates  emphasized with 'emph' links to internal chapters[1]. And it can't be overwritten
by user.
While link to internal table and figures are not emphasized.

My request is to generate macro for internal references which could be easily redefined from user's preamble.

[1] - https://github.com/sphinx-doc/sphinx/blob/master/sphinx/writers/latex.py#L1700

**Comment by tk0miya** [comment]
I added the style macros
- `\menuselection`
- `\accelerator`
- `\internalreference`

Please refer new sphinx.sty to customize these macros.

Thanks,

**Comment by vlotorev** [comment]
Thanks a lot.
