### ISSUE TITLE
sphinx-quickstart not translated

### ISSUE THREAD

**Issue by slavkoja** [sphinx-doc/sphinx#2341]
Hi,

i am sphinx's Slovak translator, and i see that the default `index.rst` generated by the `sphinx-quickstart` is not translated. On the first build, the items as "next", "previous", etc are translated, but in page the English `Welcome to projectXY's documentation!`, `Contents` and `Indices and tables` appears. I understand that this is example only, but i consider this as something what doesn't show the full sphinx power.

Please, can you make at least  these strings in `sphinx-quickstart` translatable?

**Comment by tk0miya** [comment]
Note:
In `sphinx-build`, we use `language` variable in `conf.py` to determine the display language.
But, in `sphinx-quickstart`, `conf.py` is not generated yet. so we have to use other way to determine the language.

IMO, `$LANG` or any other locale envvars are good to do that.

At same time, it might help to fill the default `language` value of `conf.py`.
I believe it is very helpful for beginners.

**Comment by tk0miya** [comment]
This was already done by #4698 (1.8.0).
Now all messages are translatable. Now I'm waiting for help from translators :-)
Closing.
