### ISSUE TITLE
LaTeXPDF output: add "This page intentionally left blank" for empty pages

### ISSUE THREAD

**Issue by xuhdev** [sphinx-doc/sphinx#2344]
One solution is [available](https://gist.github.com/philipptempel/5220000). Shall we incorporate this?

**Comment by xuhdev** [comment]
This may be important, since many new users may get confused by the blank pages for the first time they generate a PDF file.

**Comment by jfbu** [comment]
But this means an option must be added to not do that ? there will be no blank page if `howto` type of document is used. A `manual` is like a book and chapter open on odd pages, this is normal. Which empty pages are you referring to ? Apart from page 2 of the document, all have a header/footer in class `manual` in my brief test.

Perhaps there should be a way to pass option `openany` to the `manual` class ?

**Comment by xuhdev** [comment]
@jfbu Sorry I didn't make it clear. I was talking about the empty page before the starting of a new chapter in a double sided format. This is normal if it is printed; however, it does not look normal if you look at the PDF file, without being informed about this "double sided".

It is possible to pass `openany` to the manual class in Sphinx currently, but it is not obvious---it is only available in the LaTeX knowledge set, not in Sphinx. Perhaps making `openany` an default option is a better option than making a note on empty pages.

**Comment by jfbu** [comment]
I am not too much in favor of making `openany` default. In using the `manual` document type, I see it is structured with chapters. As a LaTeX user I am used to see chapters open on odd pages even on screen. But making it easier to pass the option to the document class is surely worthwile, if it makes for better reading experience on screen. (I guess some people have big enough screens to display side by side pages, but that's not everyone...)

**Comment by jfbu** [comment]
Perhaps some interface should be made more official to pass more options to the LaTeX document class alongside papersize and pointsize (one can abuse pointsize to include more options like ``'pointsize': '10pt,openany'``.) There is a ``classoptions`` which is listed as 

> Keys that are set by other options and therefore should not be overridden

In fact in the LaTeX writer code overwrites the contents in case of Japanese document and define it to be ``,dvipdfmx``. But when it is adding LaTeX babel language, it simply extends. Thus, only for Japanese is a conf.py setting for ``'classoptions'`` lost.

There is also a not documented ``extraclassoptions``. Is this used by anything ? It was added at 4f08d04, and then fa32253, perhaps for one special topic (unknown to me). Perhaps it would be better to not document ``classoptions``  and only document ``extraclassoptions``?  (I would have preferred ``otherclassoptions`` as name, "other" meaning "not papersize or pointsize", but if ``extraclassoptions`` is already in use...)

**Comment by tk0miya** [comment]
As a quick look, it seems `extraclassoptions` is not documented, a private option.
```
$ grep -r extraclassoptions *
sphinx/writers/latex.py:    'extraclassoptions': '',
sphinx/writers/latex.py:        if self.elements['extraclassoptions']:
sphinx/writers/latex.py:                                             self.elements['extraclassoptions']
Binary file sphinx/writers/latex.pyc matches
```

So we can deprecate it and replace with new option as you like.

**Comment by jfbu** [comment]
in the end I got used to ``'extraclassoptions'``, thus simplest is to make it public interface at #3480. I couldn't figure if it was introduced at 4f08d04 for needs of a specific extension (in which case public use could annoy extension).
