### ISSUE TITLE
amssymb require in sphinx.sty may break use of math font packages

### ISSUE THREAD

**Issue by jfbu** [sphinx-doc/sphinx#2348]
This is similar to #2290 which was fixed in 532e99c96bfc8c9b24525681df56304a268f3ceb (stable)

Commit 19a7dfd348d7fdc30f19034e1d420e3a7bc49a7a added `\RequirePackage{amssymb}` to `sphinx.sty`. This commit is in master branch but not in 1.3.5 (hence I did not realize impact on a project of mine until trying it on master branch).

The problem is if one uses `'fontpkg'` key to `latex_elements` to load some font packages. Among them, there may be math font packages, and the later loading of `amssymb` by `sphinx.sty` can cause conflicts. For example, using (in a `lualatex` project) `\setmathfont{xits-math}`, I got

``` latex
(/usr/local/texlive/2015/texmf-dist/tex/latex/amsfonts/amssymb.sty
Package: amssymb 2013/01/14 v3.01 AMS font symbols


/usr/local/texlive/2015/texmf-dist/tex/latex/amsfonts/amssymb.sty:240: LaTeX Er
ror: Command `\eth' already defined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              

l.240 ...mbol{\eth}            {\mathord}{AMSb}{"67}

Your command was ignored.
Type  I <command> <return>  to replace it with another command,
or  <return>  to continue without it.


/usr/local/texlive/2015/texmf-dist/tex/latex/amsfonts/amssymb.sty:259: LaTeX Er
ror: Command `\digamma' already defined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              

l.259 ...mbol{\digamma}        {\mathord}{AMSb}{"7A}

Your command was ignored.
Type  I <command> <return>  to replace it with another command,
or  <return>  to continue without it.


/usr/local/texlive/2015/texmf-dist/tex/latex/amsfonts/amssymb.sty:265: LaTeX Er
ror: Command `\backepsilon' already defined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              

l.265 ...mbol{\backepsilon}    {\mathrel}{AMSb}{"7F}

Your command was ignored.
Type  I <command> <return>  to replace it with another command,
or  <return>  to continue without it.
```

The fix should be like for #2290 to move loading of `amssymb` earlier. 

Actually `amssymb` loads automatically `amsfonts`. Hence one can  reuse the `'amsfonts'` key which was introduced in 532e99c96bfc8c9b24525681df56304a268f3ceb and set its default value to `r'\usepackage{amssymb}'`. 

(perhaps the key should be renamed to `'amssymb'`).

**Comment by tk0miya** [comment]
MEMO: the `amssymb` package came from #1971

**Comment by tk0miya** [comment]
In my environment, it must load the `amsmath` package earlier too.

So I would move both `amsmath` and `amssymb` to the position of `amsfonts` key.
And then, rename it to `amsmath` and assigns `\usepackage{amsmath,amssymb}` by default.
Of course, I will remove `amsfonts` installation hack from sphinx.ext.math*. It is already replaced by `amssymb`.

@xuhdev What do you think?

**Comment by xuhdev** [comment]
It looks good to me :)

**Comment by tk0miya** [comment]
Ok, I will modify it later.

**Comment by tk0miya** [comment]
Modified.
Thank you always :-)
