### ISSUE TITLE
customize style of :term:

### ISSUE THREAD

**Issue by fladrinar** [sphinx-doc/sphinx#2355]
I would like to be able to customize the rendered style of `:term:` words in both latex and html. 

As it is, the styling is buried in the cross reference code and in latex, at least, uses the same `\emph` style as cross references, making it impossible for the reader to tell that it's a different type of entry.  

Ideally, I'd like to be able to set both font style and color to greatly distinguish a glossary link from other types of links.

**Comment by tk0miya** [comment]
Now, I defined `\termref` macro for style of `term` roles.
Thank you for reporting!
