### ISSUE TITLE
LaTeX writer should generate breaking URLs

### ISSUE THREAD

**Issue by fredrik-johansson** [sphinx-doc/sphinx#2356]
URLs in latexpdf output mess things up. The standard LaTeX solution is to use the breakurl package and wrap URLs in \url{}. Since Sphinx doesn't use \url{...}, it's not enough for the user to insert \usepackage{breakurl} in the preamble.

This patch to Sphinx almost does the job:

```
def visit_reference(self, node):
    ...
    elif uri.startswith(URI_SCHEMES):
        self.body.append('\\href{%s}{\\url{' % self.encode_uri(uri))
        self.context.append('}}')
    ...
```

Compare this excerpt of a bibliography listing, before:

![nonbreaking](http://imgur.com/DUr4YkM.png)

After:

![breaking](http://imgur.com/5KvHUF7.png)

(Note that there is a small bug that needs to be fixed: tilde becomes ~{}.)

Is there a reason why Sphinx doesn't use \url{...} already? Note that the font changes to tt, though I guess this can be changed. Personally, I prefer tt font for URLs and wouldn't mind if this was the default (or at least easily configurable). Anyway, if this is not the best way to do it, some other solution would be fine too.

**Comment by jfbu** [comment]
Package `breakurl` is only for `dvips` compilation route ( `latex+dvips+ps2pdf`). Excerpt from package `breakurl` documentation:

```
As stated in the introduction, the breakurl is designed for those compiling documents
via LaTeX, not pdfLaTeX. In the latter case, the package doesn’t (re)define
the \url command: it only defines \burl to be a synonym of whatever \url is
defined (e.g., via url or hyperref packages). Of course, \burl may behave differently
compared to (non-pdf)LATEX, because then the system will use other rules
to make line breaks, spacing, etc.
Also, this package was not designed to nor tested against other drivers: it’s
compatible with dvips only.
```

For the issue of breaking URLs see earlier ticket #2337

**Comment by fredrik-johansson** [comment]
Thanks for the hint; closing this as duplicate.
