### ISSUE TITLE
LaTeX: additional paragraphs inside the "compound" directive should have \noindent

### ISSUE THREAD

**Issue by Jellby** [sphinx-doc/sphinx#2361]
In a case like:

```
.. compound::

  If you type::

    ls

  you will get a list of the directory contents.
```

the last paragraph ("you will...") should have \noindent in the LaTeX output.

**Comment by tk0miya** [comment]
Thank you for reporting. I fixed now.

MEMO:

> If paragraphs are rendered with a first-line indent, only the first physical paragraph of a compound paragraph should have that indent -- second and further physical paragraphs should omit the indents;

http://docutils.sourceforge.net/docs/ref/rst/directives.html#compound-paragraph
