### ISSUE TITLE
Internet Explorer: Invalid links in ToC panel

### ISSUE THREAD

**Issue by TimKam** [sphinx-doc/sphinx#2366]
In the ToC panel, `.current reference internal` elements have empty `href` attributes.

Clicking these elements in Internet Explorer can cause a 404 error, see:

https://msdn.microsoft.com/en-us/library/cc848861(v=vs.85).aspx

Perhaps it's better to set the `href`value to `#`?

**Comment by tk0miya** [comment]
What does "the ToC panel" refer to? How reproduce that?
Please let me know the situation in detail. I'm glad if you have small example project.

Thanks,

**Comment by TimKam** [comment]
With "the ToC panel" I mean the "global" table of contents (side bar).
[Here](https://github.com/TimKam/sphinx-ie-toc-bug-example) you can find an example project.
Opening `.../newlevel/bug.html` and then clicking the ToC item that I labelled "_here, the issue should appear_" will cause a 404 when the files are hosted somewhere (e.g. some server on localhost).
(When opening the file via the Windows explorer, Windows will open the corresponding directory.)

Thanks.

**Comment by tk0miya** [comment]
I understand and fix it now.
Thank you for reporting!
