### ISSUE TITLE
Moving to standard logging/warning module

### ISSUE THREAD

**Issue by tk0miya** [sphinx-doc/sphinx#2367]
Sphinx now provides logging and emitting warnings feature through `Application.warn()`.
It would be nice if we are moving to standard logging/warning module in future version.

**Comment by shimizukawa** [comment]
+1 for removing custom logging mechanism. Please note that we should keep current useful functionality after moving standard logging mechanism.

BTW, I propose structlog package for logging that is  better solution than standard logging.
- Package: https://structlog.readthedocs.org/en/stable/
- Talk https://hynek.me/talks/beyond-grep/  at EuroPython2015 (he also talked at PyCon JP 2015 as a keynote speaker)

**Comment by tk0miya** [comment]
This comes from #2346.
Since 1.4, we can suppress the warnings by types and subtypes.

**Comment by lehmannro** [comment]
Structured logging is really if you want to run (large-scale) data analysis on your logs, usually traffic logs.  For Sphinx' purposes, standard (unstructured, text) logging should be enough.
