### ISSUE TITLE
Broken search results for internal includes

### ISSUE THREAD

**Issue by ivankravets** [sphinx-doc/sphinx#2369]
### Description of problem

We have received report from our @PlatformIO community that search result for the some pages are broken in our documentation. I tried to look into the source code and found that issue is related with the documents which have internal `.. include::`.
#### Steps to Reproduce
1. Open our documentation: http://docs.platformio.org
2. Enter into search form `OTA`
3. Borken results: http://docs.platformio.org/en/latest/search.html?q=OTA&check_keywords=yes&area=default#
### Actual Results

We see 2 broken results with "copyrights" content. Affected RAW files:
- https://github.com/platformio/platformio/blob/develop/docs/history.rst
- https://github.com/platformio/platformio/blob/develop/docs/platforms/espressif.rst
- https://github.com/platformio/platformio/blob/develop/docs/platforms/espressif_extra.rst
### Expected Results

Results should contain matched text according to the search query.

**Comment by tk0miya** [comment]
What did you mean "broken"?
It looks fine for me. each documents includes the keyword `OTA`.

**Comment by ivankravets** [comment]
Take a look at the search results

## ![screen shot 2016-03-06 at 13 02 07](https://cloud.githubusercontent.com/assets/1760209/13553748/b8a3b67c-e39b-11e5-918c-88e0a46755b9.png)

Here are results from the pages which not contain internal `.. include::`
http://docs.platformio.org/en/latest/search.html?q=MBED+&check_keywords=yes&area=default
![screen shot 2016-03-06 at 13 03 32](https://cloud.githubusercontent.com/assets/1760209/13553753/e39f65d8-e39b-11e5-97a8-70f7b859dbe0.png)

**Comment by ivankravets** [comment]
> It looks fine for me. each documents includes the keyword OTA.

Hm... Could you provide me the search output where do you see "OTA"? Thanks.

**Comment by tk0miya** [comment]
Thank you for explanation. I understand what you said "broken".
Indeed, it does not work well.

At this present, Sphinx uses the source file (*.rst) to display contents around the keyword. So it fails to highlight the keywords if the keyword does not exist in the document directly.
it might be happen when the document is generated by autodoc extension.

I think big change is needed to fix this. It might be generate another text file to show contents around the keyword.

**Comment by TimKam** [comment]
With #1618, Sphinx is getting the search preview snippets from the HTML files. We can expect this issue to be fixed once 2.0 is released. I will close this issue now.
