### ISSUE TITLE
epub3 validation error

### ISSUE THREAD

**Issue by juh2** [sphinx-doc/sphinx#2371]
I created a epub3 from the project that quickstart creates.

It throws the following validation errors while validating agains epubcheck.

Epubcheck Version 3.0.1

```

Validating against EPUB version 3.0
ERROR: _build/epub3/Test.epub/content.opf(8,38): character content of element "dc:description" invalid; must be a string with length at least 1 (actual length was 0)
ERROR: _build/epub3/Test.epub/content.opf(15,39): assertion failed: dcterms:modified illegal syntax (expecting: 'CCYY-MM-DDThh:mm:ssZ')
ERROR: _build/epub3/Test.epub/genindex.html: Obsolete or irregular DOCTYPE statement. External DTD entities are not allowed. Use '<!DOCTYPE html>' instead.
ERROR: _build/epub3/Test.epub/genindex.html(8,74): value of attribute "http-equiv" is invalid; must be a string matching the regular expression "([Dd][Ee][Ff][Aa][Uu][Ll][Tt]\-[Ss][Tt][Yy][Ll][Ee])|([Rr][Ee][Ff][Rr][Ee][Ss][Hh])"
ERROR: _build/epub3/Test.epub/index.html: Obsolete or irregular DOCTYPE statement. External DTD entities are not allowed. Use '<!DOCTYPE html>' instead.
ERROR: _build/epub3/Test.epub/index.html(7,74): value of attribute "http-equiv" is invalid; must be a string matching the regular expression "([Dd][Ee][Ff][Aa][Uu][Ll][Tt]\-[Ss][Tt][Yy][Ll][Ee])|([Rr][Ee][Ff][Rr][Ee][Ss][Hh])"
ERROR: _build/epub3/Test.epub/genindex.html(22,28): '': fragment identifier is not defined in 'genindex.html'
ERROR: _build/epub3/Test.epub/index.html(22,53): '': fragment identifier is not defined in 'index.html'
ERROR: _build/epub3/Test.epub/index.html(42,59): 'py-modindex.html': referenced resource missing in the package.
ERROR: _build/epub3/Test.epub/index.html(43,54): 'search.html': referenced resource missing in the package.

Check finished with warnings or errors
```

In an old real world project I get tons of errors. Error file is attached.

[errors.zip](https://github.com/sphinx-doc/sphinx/files/161647/errors.zip)

**Comment by mgifford** [comment]
Epubcheck is at Version 4.0.1 now I think.

Here are some of the errors I'm getting.

WARNING: Irregular DOCTYPE: found '-//W3C//DTD XHTML 1.0 Transitional//EN', expecting '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" 
"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">'. in epub-cover.html
WARNING: hyperlink to resource outside spine '_images/noun_5983_cc.svg' in principles.html on line 21

ERROR: element "div" not allowed here; expected the element end-tag, text or element "a", "abbr", "acronym", "applet", "b", "bdo", "big", "br", "cite", "code", "del", "dfn", "em", "i", "iframe", "img", "ins", "kbd", "map", "noscript", "ns:svg", "object", "q", "samp", "script", "small", "span", "strong", "sub", "sup", "tt" or "var" (with xmlns:ns="http://www.w3.org/2000/svg") in attacks.html on line 21

ERROR: attribute "i:viewOrigin" not allowed here; expected attribute "alignment-baseline", "baseProfile", "baseline-shift", "class", "clip", "clip-path", "clip-rule", "color", "color-interpolation", "color-interpolation-filters", "color-profile", "color-rendering", "contentScriptType", "contentStyleType", "cursor", "direction", "display", "dominant-baseline", "enable-background", "externalResourcesRequired", "fill", "fill-opacity", "fill-rule", "filter", "flood-color", "flood-opacity", "font-family", "font-size", "font-size-adjust", "font-stretch", "font-style", "font-variant", "font-weight", "glyph-orientation-horizontal", "glyph-orientation-vertical", "height", "id", "image-rendering", "kerning", "letter-spacing", "lighting-color", "marker-end", "marker-mid", "marker-start", "mask", "onabort", "onactivate", "onclick", "onerror", "onfocusin", "onfocusout", "onload", "onmousedown", "onmousemove", "onmouseout", "onmouseover", "onmouseup", "onresize", "onscroll", "onunload", "onzoom", "opacity", "overflow", "pointer-events", "preserveAspectRatio", "requiredExtensions", "requiredFeatures", "shape-rendering", "stop-color", "stop-opacity", "stroke", "stroke-dasharray", "stroke-dashoffset", "stroke-linecap", "stroke-linejoin", "stroke-miterlimit", "stroke-opacity", "stroke-width", "style", "systemLanguage", "text-anchor", "text-decoration", "text-rendering", "unicode-bidi", "version", "viewBox", "visibility", "width", "word-spacing", "writing-mode", "x", "xml:base", "xml:lang", "xml:space", "y" or "zoomAndPan" in _images/druplicon.svg on line 16

"word-spacing", "writing-mode", "x", "xml:base", "xml:lang", "xml:space", "y" or "zoomAndPan" in _static/images/druplicon.svg on line 16
ERROR: value of attribute "version" is invalid; must be equal to "1.1" in _static/images/druplicon.svg on line 16
ERROR: element "variableSets" not allowed anywhere; expected the element end-tag or text in _static/images/druplicon.svg on line 18
ERROR: element "sfw" not allowed anywhere; expected the element end-tag or text in _static/images/druplicon.svg on line 24
ERROR: element "x:xmpmeta" not allowed anywhere; expected the element end-tag or text in _static/images/druplicon.svg on line 28
ERROR: attribute "i:layer" not allowed here; expected attribute "alignment-baseline", "baseline-shift", "class", "clip", "clip-path", "clip-rule", "color", "color-interpolation", "color-interpolation-filters", "color-profile", "color-rendering", "cursor", "direction", "display", "dominant-baseline", "enable-background", "externalResourcesRequired", "fill", "fill-opacity", "fill-rule", "filter", "flood-color", "flood-opacity", "font-family", "font-size", "font-size-adjust", "font-stretch", "font-style", "font-variant", "font-weight", "glyph-orientation-horizontal", "glyph-orientation-vertical", "image-rendering", "kerning", "letter-spacing", "lighting-color", "marker-end", "marker-mid", "marker-start", "mask", "onactivate", "onclick", "onfocusin", "onfocusout", "onload", "onmousedown", "onmousemove", "onmouseout", "onmouseover", "onmouseup", "opacity", "overflow", "pointer-events", "requiredExtensions", "requiredFeatures", "shape-rendering", "stop-color", "stop-opacity", "stroke", "stroke-dasharray", "stroke-dashoffset", "stroke-linecap", "stroke-linejoin", "stroke-miterlimit", "stroke-opacity", "stroke-width", "style", "systemLanguage", "text-anchor", "text-decoration", "text-rendering", "transform", "unicode-bidi", "visibility", "word-spacing", "writing-mode", "xml:base", "xml:lang" or "xml:space" in _static/images/druplicon.svg on line 272
ERROR: hyperlink to non-standard resource '_images/noun_67380_cc.svg' of type 'image/svg+xml' in server.html on line 381
ERROR: 'id1': fragment identifier is not defined in 'server.html' in server.html on line 400
ERROR: hyperlink to non-standard resource '_images/noun_18141.svg' of type 'image/svg+xml' in web-server.html on line 21
ERROR: '_static/fonts/Lato/Lato-Regular.ttf': referenced resource missing in the package. in _static/epub2.css on line 16
ERROR: '_static/fonts/Open_Sans/OpenSans-Regular.ttf': referenced resource missing in the package. in _static/epub2.css on line 23
ERROR: Unable to locate a valid publication date.  A date with the event attribute publication (opf:event=publication) is required in content.opf
ERROR: Unable to locate a valid creator.  A creator with the author role (role=aut) and the file-as attribute is required in content.opf
ERROR: URI '_static/fonts/Anonymous Pro.ttf' is invalid in content.opf
ERROR: Unmanifested file: _static/fonts/Anonymous Pro.ttf

**Comment by tk0miya** [comment]
Now experimental HTML5 writer is introduced at master branch.
With it, epubcheck emits no warnings.
```
$ sphinx-build -b epub -D html_experimental_html5_writer=1 doc test
$ epubcheck test/sphinx.epub
Validating using EPUB version 3.0.1 rules.
No errors or warnings detected.
epubcheck completed
```
