### ISSUE TITLE
Autodoc: Wrong formatting of signature in presence of return annotations

### ISSUE THREAD

**Issue by SylvainCorlay** [sphinx-doc/sphinx#2372]
While the `py_sig_re` regular expression successfully extracts the return annotations from signatures of the form

```
foo (a, b) -> c
```

when such a return annotation is present in the signature string, the generated description of the signature incorrectly adds parentheses when listing the functions of a module with their one-line summary with autodoc.

<img width="685" alt="screen shot 2016-03-08 at 6 31 49 pm" src="https://cloud.githubusercontent.com/assets/2397974/13620270/6a9fd646-e55c-11e5-9f73-64402309c29e.png">

However, the signature representation is correct in the long form.

<img width="680" alt="screen shot 2016-03-08 at 6 32 02 pm" src="https://cloud.githubusercontent.com/assets/2397974/13620259/63737d46-e55c-11e5-974b-424f9c6a4a80.png">

**Comment by SylvainCorlay** [comment]
cc @wjakob

**Comment by tk0miya** [comment]
Fixed by #4541 
Thank you for reporting!
