### ISSUE TITLE
Cannot generate PDF on Windows

### ISSUE THREAD

**Issue by peastman** [sphinx-doc/sphinx#2373]
On Windows, when I try to generate PDF output with the command `make.bat latexpdf`, it fails with the following error:

```
'make' is not recognized as an internal or external command,
operable program or batch file.
```

Looking through `make.bat`, I see that in the section for `latexpdf` it includes the command

```
make all-pdf
```

How is that supposed to work?  Is there a special make program for Windows I'm supposed to have installed?

**Comment by tk0miya** [comment]
Sorry for inconvinience.
Please install the `make` command to use latexpdf.
https://sourceforge.net/projects/gnuwin32/files/make/3.81/

MEMO: relates wtih #1867
