### ISSUE TITLE
Documenting __init__ function with napoleon

### ISSUE THREAD

**Issue by mausr** [sphinx-doc/sphinx#2374]
Maybe it is due to the lack of my proper googling skills but I could not figure out how I could document the **init** methods of my classes. Thus, I rewrote napoleon a little bit by adding a new option (napoleon_include_init_with_doc ) alongside the existing napoleon_include_private_with_doc and napoleon_include_special_with_doc.

Would this functionality made sense to you to be included with a new version of napoleon?

**Comment by RobRuana** [comment]
Here are some examples of how to document `__init__` using [Google style](https://sphinxcontrib-napoleon.readthedocs.org/en/latest/example_google.html) or [NumPy style](https://sphinxcontrib-napoleon.readthedocs.org/en/latest/example_numpy.html).

In particular:

```
The __init__ method may be documented in either the class level
docstring, or as a docstring on the __init__ method itself.

Note:
    Do not include the `self` parameter in the ``Args`` section.
```

For an example class level docstring see `ExampleError`. For an example docstring on the `__init__` method itself see `ExampleClass`.

If your `__init__` docs still aren't showing up, can you post a sample of your docs and the napoleon/autodoc portions of your `conf.py`?

**Comment by mausr** [comment]
Hi Rob,
thanks for the quick answer!

I have tried the linked NumPy style and saw the following:
- in line 5, the underscore at the end of `Documentation HOWTO`_` raised an error -> I deleted that underscore
- warnings were given for lines 86 and 88 because of the missing escape char before the stars in *args and **kwargs -> I left them untouched due to the comment line line 65 and 66 (i.e.: If \*args or \*\*kwargs are accepted, they should be listed as `*args` and `**kwargs`)

I generated the `.rst` file with `apidoc`and it contains the followings:

```
example_numpy module
====================

.. automodule:: example_numpy
    :members:
    :undoc-members:
    :show-inheritance:

```

The relevant part of `conf.py` is the following:

```
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.coverage',
    'sphinx.ext.napoleon',
    'sphinx.ext.viewcode'
]
```

and

```
# Napoleon settings
napoleon_include_private_with_doc = True
napoleon_include_special_with_doc = True
```

Unfortunately, the docstring of the `__init__` function of `ExempleClass` is not inserted into the generated document. I can force to insert all special and private methods by using 

```
   :private-members:
   :special-members:
```

in the `.rst` file but this way a lot of methods unnecessary for me are also inserted (dict, weakref, etc.).

I could overcome this problem by deleting the condition `name != '__init__'`at line 352 of `__init__.py` of `napoleon`and I added a config option to be able to document the `__init__` methods based on this option.

I am using Anaconda with sphinx 1.3.5

Am I overlooked something and did I something overly complicated instead of a simple solution?

**Comment by ScottABrown** [comment]
I'm experiencing a similar issue, unable to get `__init__()` to document, as described in [this stackoverflow question](http://stackoverflow.com/questions/36270358/sphinx-autodoc-skip-member-handler-cant-show-init-when-using-napoleon). I can get other special methods to show up in my documentation, but not `__init__()`.

**Comment by RobRuana** [comment]
Sorry for the delay, for some reason github did not send me a notification about your reply until @ScottABrown commented :(

I think you need to check your autodoc settings in conf.py. In particular, make sure [autoclass_content](http://www.sphinx-doc.org/en/stable/ext/autodoc.html#confval-autoclass_content) is set to either `init` or `both`.

**Comment by ScottABrown** [comment]
Thanks for the quick reply, Rob. 

I'm pretty sure `autoclass_content` isn't the difference.

What I was trying to do is put the class documentation under the class, and then have `__init__()` appear as a method just like `__repr__()` or `__str__()` or any other method, with its own documentation.
- `autoclass_content = 'both'` just adds the `__init__()` documentation to the class documentation without calling out `__init__()` as a separate function.
- `autoclass_content = 'init'` uses the `__init__()` documentation as the entirety of the class documentation, and also omits `__init__()` as a separate function.

If I remove the napoleon extension and follow [the accepted answer to this stackoverflow question](http://stackoverflow.com/questions/5599254/how-to-use-sphinxs-autodoc-to-document-a-classs-init-self-method), what I get is:
- The class docstring appears under the class heading.
- `__init__()` appears as a separate class function listing, with its docstring there as with any class function.

(ETA: Just saw your reply on SO, and posted this reply as a comment on it. I'll continue there, thanks!)

**Comment by RobRuana** [comment]
Ah, I didn't realize you wanted `__init__` to appear as a separate method. The standard Python docs document the `__init__` method along with the class documentation (here's the [first example](https://docs.python.org/3/library/argparse.html#argparse.ArgumentParser) I dug up, but I don't think you'll find `__init__` documented separately anywhere in the stdlib). That's _probably_ why there isn't a built-in way to document `__init__` separately in the sphinx tools.

If you really want `__init__` to appear separately, I'm happy to accept a pull request that adds a `conf.py` flag to napoleon that implements this functionality.

**Comment by ScottABrown** [comment]
Hmm, any idea what interaction is happening that prevents the autodoc-skip-member handler approach to stop working with napoleon?

**Comment by RobRuana** [comment]
Napoleon _also_ hooks the `"autodoc-skip-member"` event. 

If two extensions both hook the `"autodoc-skip-member"` event, then autodoc simply uses the result from the first one to respond. The event listeners are stored in a python `dict`, so the order in which they are called is not deterministic :(

We can't guarantee that the custom `__init__` handler will run first :(

**Comment by mausr** [comment]
No problem for the delay.:)

I will create a pull request until the end of this week.

I've just seen your last comment: very useful indeed.

**Comment by ScottABrown** [comment]
Rob, thanks, that's  useful piece of knowledge to add to my mental library. :)
