### ISSUE TITLE
Support for multiple source directories

### ISSUE THREAD

**Issue by ishitatsuyuki** [sphinx-doc/sphinx#2375]
Hello,
I want to request support for multiple source directories.

Things like sphinx-apidoc generates files currently in source directories.
I'm not sure with the practices in Python, but we don't add generated files in version control for C/C++ repositories. Doxygen is exactly the example. Doxygen also support multiple source directories (in an other meaning).

I'm currently porting sphinx-apidoc for Breathe(a C/C++ extension for Sphinx), and I think using a separate source directory for generated files makes a sense.

**Comment by Letme** [comment]
Sounds like same as: #3132

**Comment by tk0miya** [comment]
It seems there many comments in #3132. So I close this instead.
Thanks,
