### ISSUE TITLE
Sphinx does not produce HTML5 output

### ISSUE THREAD

**Issue by jfinkels** [sphinx-doc/sphinx#2376]
This seems to be because Sphinx uses docutils to translate ReST to HTML, and docutils doesn't provide an HTML5 writer until version 0.13 (see http://docutils.sourceforge.net/docs/user/html.html). Version 0.13 doesn't seem to be released yet (see https://sourceforge.net/projects/docutils/files/docutils/).

**Comment by tk0miya** [comment]
An experimental HTML5 writer is now introduced at #3464.
Thanks,
