### ISSUE TITLE
type recognition of keyword arguments in ext.napoleon

### ISSUE THREAD

**Issue by dahpgjgamgan** [sphinx-doc/sphinx#2379]
Hello, 

Right now, following code:

```
class Arg1:
    pass

def f(**kwargs):
    """
    A function, obviously.

    Args:
        arg1(test_package.Arg1 or sth else): arg1
        arg2(test_package.Arg1): arg2

    Keyword Args:
        kwarg1(test_package.Arg1): kw1
        kwarg2(:class:`test_package.Arg1`): kw2
    """
    pass
```

with napoleon extension on, would generate a description of arguments, with working links to argument types for arg2, but for keyword arguments, the same method (specifying type of keyword in parentheses does not work - the closest way to achieve that is to yse `:class:` as in kwarg2, but that yields a slightly different formatting.

I though this would be a quick fix, and peeked at the code, but it turns out that napoleon translates google docstrings to docutils syntax, and this in turn, does not support specifying types of keyword
arguments (at least would not generate links), so the change would be a bit more extensive, thus I though it might be better to ask before working my way through a patch.

I have two suggestions:
1. Add option to napoleon to treat keyword args similarly to parameters, i.e: translate them into `:keyword:` lines. This would results in keywords merged to arguments in generated docs (at least in html)
2. Add `:kwtype:` (similar to `:type:` , `:rtype:` which would allow specifying types for keyword arguments, than use it in napoleon.

I'd be grateful for info, if any of those changes are welcome - I could work on a patch.

**Comment by RobRuana** [comment]
Yes, `Keyword Args` should use the same formatting as `Args` for the output. I'll look into this, thanks for reporting it!

**Comment by RobRuana** [comment]
Okay, your two suggestions are both good.
1. Suggestion 1. is easier to implement, but like you said, the keywords end up merged with the other params
2. Suggestion 2. would produce the output you want, but would be a more in-depth change. The napoleon extension would need to add an override to the [PyObject.doc_field_types](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/domains/python.py#L124). I'm not 100% sure how to do this right now, but you probably need to use something like this:

```
PyTypedField('keywordargs', label=l_('Keyword Args'),
             names=('keyword', 'kwarg', 'kwparam'),
             typerolename='obj', typenames=('paramtype', 'type'),
             can_collapse=True)
```

I don't have time to work on suggestion 2. right now, but I would be very grateful for a pull request that implements it.

**Comment by dahpgjgamgan** [comment]
hi, did you have a moment to take a look at the PR?
