### ISSUE TITLE
The default spacing for "Fig." is incorrect in LaTeX output

### ISSUE THREAD

**Issue by xuhdev** [sphinx-doc/sphinx#2382]
By default, the following line is in the LaTeX output:

``` tex
\addto\captionsenglish{\renewcommand{\figurename}{Fig. }}
```

However, by default, LaTeX sees `.` as the end of a sentence, thus the spacing after `Fig.` is significantly larger, while `Fig.` should really indicate abbreviation for `Figure`. The solution is to either set it to be `Fig.~` or `Fig.\` (see [here](https://tex.stackexchange.com/questions/2229/is-a-period-after-an-abbreviation-the-same-as-an-end-of-sentence-period)). I'm not sure about how to handle it in Sphinx, as this is specified in an option in `conf.py`---we need to take care of the html output as well.

**Comment by xuhdev** [comment]
Or maybe we can just change the default to `Figure`.

**Comment by tk0miya** [comment]
I found this article: http://tex.stackexchange.com/questions/116528/vs-after-abbreviation-read-backslash-at-vs-backslash-space

It says:

> If you are making a macro it's better to use \@ form.

So, I will insert `\@` after period.

**Comment by tk0miya** [comment]
Fixed at ca8aec9.
Thank you for reporting!
