### ISSUE TITLE
Numfig do works for latex

### ISSUE THREAD

**Issue by mickours** [sphinx-doc/sphinx#2384]
The doc says in `config.html#confval-numfig` that numfig is only supported for HTML.
This is not true and I tried several unmaintained plugin before I realize that it actually working for LateX too!

I would like to replace the `For now, it works only with the HTML builder.` sentence by a list of supported builders but I really don't know.

Any developer of this module could update this please?

**Comment by tk0miya** [comment]
Thank you for reporting.
I fixed it.
