### ISSUE TITLE
Adding Jira Issue Collector to Sphinx Doc - Help, Please!

### ISSUE THREAD

**Issue by brianjking** [sphinx-doc/sphinx#2388]
I'm attempting to add an Issue Reporter/Collector from Jira to my Sphinx docs and am having trouble. Jira provides two ways of doing this -- either HTML or Javascript.

`
// Requires jQuery!
jQuery.ajax({
            url: "http://domain.com/s/83ddc972c3081d22fffbf8446fbc64db-T/en_US-kq69xc/71006/b6b48b2829824b869586ac216d119363/2.0.11/_/download/batch/com.atlassian.jira.collector.plugin.jira-issue-collector-plugin:issuecollector-embededjs/com.atlassian.jira.collector.plugin.jira-issue-collector-plugin:issuecollector-embededjs.js?locale=en-US&collectorId=680c22f9",
        type: "get",
    cache: true,
    dataType: "script"
});`
### HTML Method

`
 <script type="text/javascript" src="http://domain.com/s/83ddc972c3081d22fffbf8446fbc64db-T/en_US-kq69xc/71006/b6b48b2829824b869586ac216d119363/2.0.11/_/download/batch/com.atlassian.jira.collector.plugin.jira-issue-collector-plugin:issuecollector/com.atlassian.jira.collector.plugin.jira-issue-collector-plugin:issuecollector.js?locale=en-US&collectorId=680c22f9"></script>`

**Comment by tk0miya** [comment]
It might be resolved by adding following code to your `conf.py`::

```
def setup(app):
    app.add_javascript('http://domain.com/s/83ddc972c3081d22fffbf8446fbc64db-T/en_US-kq69xc/71006/b6b48b2829824b869586ac216d119363/2.0.11/_/download/batch/com.atlassian.jira.collector.plugin.jira-issue-collector-plugin:issuecollector/com.atlassian.jira.collector.plugin.jira-issue-collector-plugin:issuecollector.js?locale=en-US&collectorId=680c22f9')
```

It inserts script tags into all HTML files. Maybe it works.

**Comment by brianjking** [comment]
Thanks @tk0miya for the reply. I ended up solving this by grabbing the Javascript method and creating a file which I named `jira.js` to the `_static` directory.

Then inside of my `conf.py` file I added the following:

`def setup(app):
        app.add_javascript('jira.js')`
