### ISSUE TITLE
sphinx support ditaa plugin

### ISSUE THREAD

**Issue by daoiqi** [sphinx-doc/sphinx#2392]
https://github.com/baloo/sphinx-ditaa

Does sphinx support ditaa idea?

usage:

```
.. ditaa::
  +--------+   +-------+    +-------+
  |        | --+ ditaa +--> |       |
  |  Text  |   +-------+    |diagram|
  |Document|   |!magic!|    |       |
  |     {d}|   |       |    |       |
  +---+----+   +-------+    +-------+
      :                         ^
      |       Lots of work      |
      +-------------------------+
```

**Comment by lehmannro** [comment]
What's the problem with the external extension?

**Comment by daoiqi** [comment]
not problem, just want to sphinx support by default?
but I think not necessary.

**Comment by lehmannro** [comment]
Extensions are a first-class citizen in Sphinx and ain't go away.  If there's anything missing from our extension mechanism feel free to open a new ticket — I'm closing this one.
