### ISSUE TITLE
Getting errno on mscgen

### ISSUE THREAD

**Issue by thiagobrunoms** [sphinx-doc/sphinx#2393]
File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinxcontrib/mscgen.py", line 77, in run_cmd
    if err.errno != getattr(errno, 'ENOEXEC', 0):
NameError: global name 'errno' is not defined

Does it seem to be a bug?

**Comment by shimizukawa** [comment]
Yup, it seems a bug. 
`errno` is used unless `import errno` in mscgen.py:
https://bitbucket.org/birkenfeld/sphinx-contrib/src/6d1c958ca7bd2a3095763d51c8547ff1ab0ae5ec/mscgen/sphinxcontrib/mscgen.py?at=default&fileviewer=file-view-default#mscgen.py-77

Please report the issue to author Leandro Lucarella on https://bitbucket.org/birkenfeld/sphinx-contrib/issues/new
