### ISSUE TITLE
Problems with pdflatex in a Turkish document built with sphinx

### ISSUE THREAD

**Issue by Znni** [sphinx-doc/sphinx#2397]
I have a project where, among other things, I try to convert a Turkish tex file built with sphinx to PDF. The conversion works with several other languages, but there are problems with Turkish. Trying to run pdflatex with the file gives errors starting with these:

```
 [exec] C:/Kiln/Troubleshoot/build/latex_tr/EEM4FSensors.tex:143: Missing 
 [exec] C:/Kiln/Troubleshoot/build/latex_tr/EEM4FSensors.tex:143: Missing number, treat
 [exec] ed as zero
 [exec] C:/Kiln/Troubleshoot/build/latex_tr/EEM4FSensors.tex:143: Illegal unit of measu
 [exec] re (
 [exec] C:/Kiln/Troubleshoot/build/latex_tr/EEM4FSensors.tex:143: Extra 
 [exec] C:/Kiln/Troubleshoot/build/latex_tr/EEM4FSensors.tex:143: Missing 
 [exec] C:/Kiln/Troubleshoot/build/latex_tr/EEM4FSensors.tex:143: Missing number, treat
 [exec] ed as zero
 [exec] C:/Kiln/Troubleshoot/build/latex_tr/EEM4FSensors.tex:143: Illegal unit of measu
 [exec] re (
 [exec] C:/Kiln/Troubleshoot/build/latex_tr/EEM4FSensors.tex:143: Extra 
 [exec] C:/Kiln/Troubleshoot/build/latex_tr/EEM4FSensors.tex:143: Missing number, treat
 [exec] ed as zero
```

etc. "Improper alphabetic constant" etc. There are also other similar error from other rows.

Row 143 in EEM4FSensors.tex reads

```
  \includegraphics[width=0.900\linewidth]{{engine_sensors_4F_3}.png}
```

After some investigation I found out that this has something to do with shorthandoff commands. I found out that modifying sphinx\writers\latex.py function get_shorthandoff given here:

```
def get_shorthandoff(self):
        shortlang = self.language.split('_')[0]
        if shortlang in ('de', 'ngerman', 'sl', 'slovene', 'pt', 'portuges',
                         'es', 'spanish', 'nl', 'dutch', 'pl', 'polish', 'it',
                         'italian'):
            return '\\shorthandoff{"}'
        return ''
```

to this:

```
def get_shorthandoff(self):
        shortlang = self.language.split('_')[0]
        if shortlang in ('de', 'ngerman', 'sl', 'slovene', 'pt', 'portuges',
                         'es', 'spanish', 'nl', 'dutch', 'pl', 'polish', 'it',
                         'italian'):
            return '\\shorthandoff{"}'
        elif shortlang in ('tr', 'turkish'):
                                  return '\\shorthandoff{=}'
        return ''
```

solves the problem. I don't know if this breaks something else, but at least my problem was solved by this. Does anyone have any ideas what caused the problem and how it should be solved?

I am using sphinx 1.3.6, Babel 2.2.0 and Miktex 2.9.

**Comment by jfbu** [comment]
As a side note, there is a list of shorthands per language in the current Babel (latex package) documentation. Particularly regarding `"`, 

```
Languages with only " as defined shorthand character Albanian, Bulgarian,
Danish, Dutch, Finnish, German (old and new orthography, also Austrian),
Icelandic, Italian, Norwegian, Polish, Portuguese (also Brazilian), Russian,
Serbian (with Latin script), Slovene, Swedish, Ukrainian, Upper Sorbian
```

and then one finds also 

```
Basque, Catalan, Czech, Estonian, Galician, Latin, Slovak, Spanish
```

as the other languages with `"` among shorthands. Thus the current list in Sphinx appears to be  incomplete.

As per `=` sign as shorthand, it is only for `Latin` and  `Turkish`. Hence indeed `Turkish` is special.

I don't know where `get_shorthandoff` is used in Sphinx, but your proposed change does not appear likely to break something, except of course if at some point the produced latex file makes use of `=`  with its meaning as shorthand.

**Comment by jfbu** [comment]
The documentation of Turkish language for LaTeX Babel says

``` latex
Turkish typographic rules specify that a little ‘white space’ should be added
before the characters ‘:’, ‘!’ and ‘=’.

[...]

The = shorthand is potentially dangerous. You can deactivate with the babel
option shorthands or with \shorthandoff:
\usepackage[turkish,shorthands=:!]{babel}
```

Thisway of loading Babel activates only the `:` and `!` shorthands.

**Comment by tk0miya** [comment]
Sphinx appends `\shorthandoff{=}` on building turkish documents at c289a35.
@Znni Could you try the stable branch? The fix was not tested because I don't have any turkish documents. This issue will be closed after your confirmation.

@jfbu Thank you for comments. Finally, I changed the shorthandoff definitions only for turkish. Because I could not check what will be happened from the changes. If you have a good idea, please let me know. It would be nice to keep updated the shorthandoff definitions.

BTW, `ExtBabel.get_shorthandoff()` is used for generate `\shorthandoff` macro at the top of document environment.

**Comment by Znni** [comment]
I tried the latest stable branch version with the Turkish documents. The fix works for me, thanks.

**Comment by jfbu** [comment]
@tk0miya I don't have good idea... `\shorthandoff{=}` looks like a good one. I am not a Latin practitioner, but if I ever do Sphinx project in Latin, maybe I will make a PR to do `\shorthandoff{=}` there too ;-)

**Comment by tk0miya** [comment]
Okay, I close this issue now.
Thank you for reporting and helping!
