### ISSUE TITLE
Glossary terms are not case sensitive

### ISSUE THREAD

**Issue by kohr-h** [sphinx-doc/sphinx#2403]
The closest issue I could find is #167, but other than that I don't get any good hits just by searching the issue tracker.

My issue is the following: I have an `Operator` class and a glossary entry `operator` which does not explain the class, but rather the abstract concept. Two different things. Unfortunately, Sphinx thinks they are the same and gives heaps of warnings

```
 WARNING: more than one target found for 'any' cross-reference u'Operator': could be :std:term: or :py:class:
```

What's bad about this is that it seems to prefer the glossary entry over the class, which messes up a number of cross-links in the API doc. My current workaround is to define the `default_role` to `py:class`, but that does not help in other situations where I have a `py:function` or `py:obj` with a name clash.

If it's too troublesome to make the glossary case-sensitive (or if it breaks existing "sloppy" docs), a viable solution would be to offer some extended version of `default_role` where one could define an order of precedence (where in my case, `std:term` would come last).

I have Sphinx 1.2.3 installed on my machine, but I think the same problem occurred with the latest PyPI version (1.4).

**Comment by tchernobog** [comment]
> If it's too troublesome to make the glossary case-sensitive

It might be: think about creating a glossary entry such as "bearer token". Now, if you are at the beginning of a sentence after a full stop, you want the first letter capitalized. E.g. "Bearer token".

But then you cannot use :term:`Bearer token`.

> a viable solution would be to offer some extended version of default_role where one could define an order of precedence (where in my case, std:term would come last

That would be a good solution.

**Comment by tk0miya** [comment]
You can use ```:term:`Bearer token <bearer token>` ``` instead :-)

Anyway, Sphinx supports case-sensitive terms since v3.0.0. So I'm closing this now.

**Comment by kohr-h** [comment]
That's good news, thanks!

**Comment by colseanm** [comment]
@kohr-h, I am experiencing the same problem where the glossary entries have precedence over Python objects in my cross references in my API doc when I use `default_role='any'`.

You had said:
> What's bad about this is that it seems to prefer the glossary entry over the class, which messes up a number of cross-links in the API doc. My current workaround is to define the `default_role` to `py:class`, but that does not help in other situations where I have a `py:function` or `py:obj` with a name clash.

Were you able to develop a workaround for this problem without using `default_role='py:class'` (and without adding Sphinx syntax other than backquotes to your docstrings), for example, when you want to reference a Python class `Operator` but you have a glossary term `operator`?

> a viable solution would be to offer some extended version of default_role where one could define an order of precedence (where in my case, std:term would come last).

I have been thinking the exact same thought  - that it would be convenient if `default_role` were an ordered list of roles.
