### ISSUE TITLE
Embedded images may cause build to crash

### ISSUE THREAD

**Issue by erikalfthan** [sphinx-doc/sphinx#2407]
I am in process of converting a file / docx based documentation into sphinx. A step in this is to use PyDocX and pandoc (pandoc unfortunatly dies on a table with property labels (i.e `<title>` included in the docx-template, PyDocX manages.

This creates rst-files with large embedded images (base64 encoded). This in turn causes sphinx build html to crash

Im using Windows 10, WinPython3.4 (standalone installation of python). sphinx is installed with `pip install -U sphinx`.

```
C:\<userfolder>\NextGenDocs>make html
Running Sphinx v1.4
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 12 source files that are out of date
updating environment: 12 added, 0 changed, 0 removed
reading sources... [ 25%] <folder>/<revealing file name>
Exception occurred:
  File "C:\<userfolder>\winpython-64bit-3.4.3.7\python-3.4.3.amd64\lib\site-packages\sphinx\environment.py", line 939, in process_images
    if not os.access(path.join(self.srcdir, imgpath), os.R_OK):
ValueError: access: path too long for Windows
The full traceback has been saved in C:\<userfolder>\AppData\Local\Temp\sphinx-err-w43mroka.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

[sphinx-err-w43mroka.log.txt](https://github.com/sphinx-doc/sphinx/files/197317/sphinx-err-w43mroka.log.txt)
This is caused by a too long embedded file, about 170 000 bytes. Removing the image and references to it removes the issue.

I would have liked a better error message and of course if possible a solution. A workaround to warn+ignore the "offending" tag is fully acceptable for my case. The resulting rst-files from the conversion need some manual editing anyway, but the page need to exist to be fixed.

**Comment by erikalfthan** [comment]
Comment: My post looks like a mess, a mix of raw html and text with no line breaks. Please feel free to highlight my mistake.

EDIT: Strange - now when I got some time to look into my previous post, it looks fine.

**Comment by lehmannro** [comment]
(The raw `<title>` tag in your first paragraph caused the Markdown parser to trip up, it seems.)

**Comment by tk0miya** [comment]
Sorry, I don't know about embedding base64 encoded images as reST notation.
Could you give me any examples that embeds them?

It seems sphinx recognizes the encoded-string as filename and tries to check its existence.

**Comment by erikalfthan** [comment]
I dont have a full sharable example, but the reST directive looks like this

```
.. |image2| image:: data:image/png;base64,iVBORw0KGgoAAAANSUhEU<lots more>
```

I'm a beginner at reST, so the reason I believe it is valid is that I _didnt_ write it, a converter tool did. My current (working) workaround is to use mkdocs with markdown instead, which becomes this

```
![](data:image/png;base64,iVBORw0KGgoAAAANSUhEU<lots more>
```

I dont know if the embedded file is valid reST image and I don't know if sphinx aims to comply 100% with reST. I have also solved my task using other tools, so it is not urgent to me. Use the information as you see fit.

**Comment by tk0miya** [comment]
The `image` directive take image URI as argument. It also allows image Data URI.
http://docutils.sourceforge.net/docs/ref/rst/directives.html#image

Sphinx allows it, but it works only for HTML builder (maybe).

Now I added file existence check if the image URI is image data URI.
It will help you.

Thanks,
