### ISSUE TITLE
dummy builder not available in Makefile

### ISSUE THREAD

**Issue by astrojuanlu** [sphinx-doc/sphinx#2408]
I downloaded Sphinx 1.4 to try the new dummy builder but it does not feature a dedicated entry in the Makefile. Instead, the `sphinx-build` command has to be used. It would be nice to have it in the Makefile, since it's a fast way to check for syntax errors.

**Comment by shimizukawa** [comment]
OK, I'll add it to Makefile/make.bat.

BTW, current style Makefile/make.bat will be replaced with new style Makefile/make.bat that are already provided by `sphinx-quickstart -m` option. Please try it.

**Comment by shimizukawa** [comment]
Fixed.

**Comment by astrojuanlu** [comment]
Thanks @shimizukawa - Regarding `sphinx-quickstart -m`, I found no references in the official docs http://www.sphinx-doc.org/es/stable/invocation.html would you please provide some more information so I can try it?

**Comment by shimizukawa** [comment]
`-m` is `--use-make-mode`: http://www.sphinx-doc.org/en/1.4.8/invocation.html#cmdoption-sphinx-quickstart--use-make-mode
You can use the option since sphinx-1.3.
