### ISSUE TITLE
crash using only directive

### ISSUE THREAD

**Issue by andreacassioli** [sphinx-doc/sphinx#2409]
Hi,
the following code 

```
.. only:: latex

   --------------------------------------------------------------------------------------


some text

```

generate the following crash:

```
Exception occurred:
  File "/usr/lib/python3/dist-packages/docutils/transforms/misc.py", line 109, in visit_transition
    isinstance(node.parent, nodes.section))
AssertionError
The full traceback has been saved in /tmp/sphinx-err-pnm4zl0e.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!

```

I am running the latest 1.4 on linux.

**Comment by tk0miya** [comment]
My short description:
- In reST, sequence of punctuations means transitions (http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#transitions)
- docutils expects the transition node is put on between other nodes. It warns if the blocks begin with transitions

The assertion error comes from the second rule.

I think this is an irregular case, but the effect of the bug is small.

**Comment by andreacassioli** [comment]
Hi @tk0miya 
thank you for the feedback.

The reason I use transition is to have a horizontal line between paragraphs, but I want that line only in latex. That's why I use only. What would be a workaround?

**Comment by jfbu** [comment]
Hi @andreacassioli you could try this workaround:

``` rst
some text

.. raw:: latex

   \par\bigskip\hrule\bigskip

some text
```

or, possibly better, use rather in the above `\mytransition`, set `'transition'` key from `latex_elements` to `'\n\n\\mytransition\n\n'` and use `'preamble'` key to define `'\\def\\mytransition{whatever}'`. (not tested)

**Comment by tk0miya** [comment]
Yes, `raw` directive will help you :-)

@jfbu Thank you for advice.

**Comment by andreacassioli** [comment]
Hi,
yes the `raw` directive works perfectly to my purpose. Thank again. 

But the issue (the small bug) remains open, right?

**Comment by tk0miya** [comment]
Yes, keep opening please.
We will fix it later
