### ISSUE TITLE
Keep parentheses in a zero-argument function-like macro in c:macro

### ISSUE THREAD

**Issue by vitaut** [sphinx-doc/sphinx#2410]
It would be useful if `c:macro` preserved parentheses in

``` rst
.. c:macro:: FOO()
```

Currently it is rendered as

```
FOO
```

rather than

```
FOO()
```

which makes it impossible to distinguish

``` c
#define FOO()
```

from

``` c
#define FOO
```

and inconsistent with macros with multiple arguments.

https://github.com/michaeljones/breathe/issues/233

**Comment by vermeeren** [comment]
@jakobandersen could it be this one has already been silently fixed?

Asking for michaeljones/breathe#233, thanks.

**Comment by jakobandersen** [comment]
Fixed by 515fb53.
