### ISSUE TITLE
:numref: in latexpdf generetes very buggy labels

### ISSUE THREAD

**Issue by arafune** [sphinx-doc/sphinx#2412]
Hello, 

While the numref function works for html generation, it does not work well.
Here is the test rst.

------------from below--------
###### 

TEST
###### 

:numref:`test1` should be Fig. 1.1.  And :numref:`test2` should be Fig. 1.2.  But th
e generated pdf is not.

.. _test1:

.. figure:: image/test1.png

```
    caption of test1.
```

.. _test2:

.. figure:: image/test2.png

```
      caption of test2.
```

----------------to above---------------

By stroring these lines as index.rst in source directory, and prepare two image files named test1.png and test2.png.  And then run "make latexpdf".  (numfig = True in conf.py, of course) You would see the warning message like:

LaTeX Warning: Label `index:test1' multiply defined.

In fact, the generated latex file contains wrong labels:
\label{index:test2}\label{index:test1}\label{index:id2}\end{figure}

The needless "\label{index:test1}" is inserted!, which causes the generated pdf through latexpdf useless, unfortunately.  I believe it should be:
\label{index:test2}\label{index:id2}\end{figure}

Could you fix this problem immediately as possible?

**Comment by jfbu** [comment]
I can't for lack of knowledge comment if what you observe is a bug, but can you try the following way which seems to work ok:

``` rst
#################
TEST
#################

:numref:`test1` should be Fig. 1. And :numref:`test2` should be Fig. 2.
And indeed, it does work.

.. figure:: image/test1.png
   :name: test1

   caption of test1.


.. figure:: image/test2.png
   :name: test2

   caption of test2.

```

**Comment by arafune** [comment]
Thanks for good suggestion.

But in the practical use, I cannot use this technique, because I prepared
two format png and pdf, the former is for html the latter for latex-pdf.
Bests,

Ryuichi Arafune

2016-04-04 4:51 GMT+09:00 jfbu notifications@github.com:

**Comment by tk0miya** [comment]
Sorry for inconvenience.
Fixed at 1313726

Thank you for reporting.

**Comment by thorade** [comment]
I still see have this issue with Sphinx 1.4.1
```
pip show sphinx
---
Metadata-Version: 2.0
Name: Sphinx
Version: 1.4.1
Summary: Python documentation generator
Home-page: http://sphinx-doc.org/
Author: Georg Brandl
Author-email: georg@python.org
Installer: pip
License: BSD
Location: c:\python34\lib\site-packages
Requires: six, Jinja2, Pygments, imagesize, colorama, alabaster, snowballstemmer, babel, docutils
```

**Comment by thorade** [comment]
Thanks for fixing this.
I also had to restart my computer after updating sphinx to see the effect.
