### ISSUE TITLE
Alignment doesn't work when rendering to LaTeX

### ISSUE THREAD

**Issue by DavidGriffith** [sphinx-doc/sphinx#2428]
Given something like this:

```
.. image:: /images/picL.png
   :scale: 50%
   :align: left

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec rutrum aliquet
enim, et condimentum diam pretium a. Morbi et justo ipsum. Vivamus lobortis
risus at dapibus volutpat. Nullam velit orci, rhoncus ac enim in, auctor sollicitudin
tortor. Vivamus egestas lacus at neque sollicitudin ultricies. Vestibulum sit amet
feugiat metus, nec fringilla mauris. Quisque at nulla ligula. Nulla sit amet augue
ut arcu lobortis ultricies nec a justo. Sed nec mi et elit vestibulum aliquam.
```

When it is rendered to HTML, picL.png (a large illuminated letter L) will appear embedded in the paragraph with the text wrapping around it.  When rendered to LaTeX, the resulting PDF shows the illuminated letter above a plain paragraph.

**Comment by andreacassioli** [comment]
I experienced something similar in the past, but now it seems to work for me. Is it still an issue? If so, could you link the image as well? Otherwise you should close the request.

**Comment by tk0miya** [comment]
Indeed. This was already fixed now. So I'm closing this.
