### ISSUE TITLE
Add KaTeX math rendering support

### ISSUE THREAD

**Issue by fredrik-johansson** [sphinx-doc/sphinx#2430]
KaTeX (https://github.com/Khan/KaTeX) is a lot faster than MathJax, and it supports pre-rendering. It would be nice to do this at build time with Sphinx.

A drawback is that it doesn't support all TeX markup. It would be nice to use KaTeX when possible, and MathJax as a fallback.

**Comment by tk0miya** [comment]
That sounds good.

Sphinx already has extension archtecture.
It would be nice if any Sphinx extension supports KaTeX.

**Comment by tk0miya** [comment]
To keep sphinx-core simple, KaTeX module should be implemented as an extension.
Thank you for proposal.

**Comment by jason-s** [comment]
What is the method for proposing/implementing extensions in sphinx? MathJax and KaTeX are so similar that they really would benefit from having one unified extension.

**Comment by tk0miya** [comment]
Do you mean how to add KaTeX support into sphinx-core?

If true, I want to know why is KaTeX important to sphinx-core.
Sphinx has already the framework for extensions. So many developers provides their extensions as a 3rd party's. I want to know why should KaTeX be bundled.
(ex. it is important for **all** sphinx users. it is commonly used in the world....)

In addition, we don't have enough time and knowleges to maintain it.
So please find the maintainer of the module.
