### ISSUE TITLE
The extensions value is checked before the needs_sphinx value

### ISSUE THREAD

**Issue by asr** [sphinx-doc/sphinx#2436]
In conf.py I have the following values:

``` phyton
needs_sphinx = '1.4'

extensions = ['sphinx.ext.imgmath']
```

By running `make html` using  Sphinx 1.3.6 I would expect the following error:

```
Sphinx version error:
This project needs at least Sphinx v1.4 and therefore cannot be built with this version.
```

but instead I got the following error:

```
Extension error:
Could not import extension sphinx.ext.imgmath (exception: No module named imgmath)
```

That is, the `extensions` value is checked before the `needs_sphinx` value. It is the expected behaviour?

**Comment by tk0miya** [comment]
Ok, I'll take a look

**Comment by tk0miya** [comment]
Unfortunately, older sphinx (<= 1.4.1) checks it **after** loading extensions.
I fixed the behavior to do that **before** loadings at febfd68.

But this change does not effect to older sphinx.
So if you want to require the sphinx is newer than 1.4.1, please add following code to your conf.py::

```
import sys
import sphinx
from sphinx.errors import VersionRequirementError

needs_sphinx = '1.4'
if needs_sphinx > sphinx.__display_version__:
    message = 'This project needs at least Sphinx v%s' % needs_sphinx
    raise VersionRequirementError(message)
```

Thank you for reporting!

**Comment by asr** [comment]
The code to be used with older Sphinx worked for me.

Thanks for fixing the issue and the code!
