### ISSUE TITLE
Installing an older build of sphinx

### ISSUE THREAD

**Issue by ArendDanielek** [sphinx-doc/sphinx#2438]
I am looking to install Sphinx 1.3.3 as currently my department is under a deadline and due to some external conflicts with changes we made to the sphinx-rtd-theme we can not upgrade to Sphinx 1.4 immediately. Now you may be asking if you were using 1.3.3 before why can't you just keep reusing it? Why do we need to install what is already installed? Well several of us got new office computers last week and while installing our tool chain I have run into a number of issues.

Currently I just want to get the new machines on 1.3.3. I can download the repo revision at the 1.3.3 version. I also found the .whl file for 1.3.3 on the python package index. However I have no idea how to get the files from the downloaded zip where they need to go when trying to use the manual approach. With the .whl file I ran "wheel install " on it but I got back this.

```
C:\Python27\Scripts>wheel install D:\Downloads\Sphinx-1.3.5-py2.py3-none-any.whl
c:\python27\lib\site-packages\wheel\pep425tags.py:77: RuntimeWarning: Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
  warn=(impl == 'cp')):
c:\python27\lib\site-packages\wheel\pep425tags.py:81: RuntimeWarning: Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
  warn=(impl == 'cp')):
c:\python27\lib\site-packages\wheel\pep425tags.py:87: RuntimeWarning: Config variable 'Py_UNICODE_SIZE' is unset, Python ABI tag may be incorrect
  sys.version_info < (3, 3))) \
```

Now I do not claim to be an expert in build systems but I took over managing our's a couple years ago for our documentation site, but I have never run into an issue quite like this while using Sphinx.

Apologies if this is not the correct place to post this, hopefully someone can help.

**Comment by shimizukawa** [comment]
I'm sorry, I have no idea what you're referring to :)
I guess you can do:

```
pip install Sphinx==1.3.5
```

instead of `wheel install`.

**Comment by ArendDanielek** [comment]
I'm just a software developer just getting by with very few self-taught pip skills in a sphinx project made by someone who isn't around anymore. This worked perfectly, thanks for your time.
