### ISSUE TITLE
function argument generate broken links in C domain

### ISSUE THREAD

**Issue by andreacassioli** [sphinx-doc/sphinx#2439]
Hi,
I have tried

```
.. c:function:: int func(int i)


   :param int i: an arg
```

on Sphinx 1.4. But in the output I get a broken link for the `int` type. In my understanding the `TypedField` does not check the stop words and therefore cannot distinguish what should be a link or not. Any clue?

**Comment by andreacassioli** [comment]
The same with 1.4.1

**Comment by tk0miya** [comment]
Could you tell me what did you mean "broken link"?
In my environment, the `int` field is a normal text. not a link.
(Sorry, I don't use C domain usually)

**Comment by andreacassioli** [comment]
Hi @tk0miya ,
 I am sorry I haven't been clear.

I see that `TypedField` create a xref node regardless whether the type of the field is a documented link or not. If the xref is not resolvable than its text is used instead. Am I wrong?

I say broken link because I use a tiny extension that raises an exception if an unresolved link is detected.

**Comment by jakobandersen** [comment]
@andreacassioli, I made a fix as you suggested, in another branch (https://github.com/jakobandersen/sphinx/tree/c-fix-2439). Could you check if it generates the result you expected?

**Comment by andreacassioli** [comment]
It seems OK, though I cannot be sure 100%. I wonder whether other domains have the same issue...

**Comment by tk0miya** [comment]
@jakobandersen Thank you for your help! I leave this up to you.

**Comment by jakobandersen** [comment]
Sorry, I completely forgot about this. The fix should be in 'stable' now.
