### ISSUE TITLE
Full text search adapters: support elasticsearch?

### ISSUE THREAD

**Issue by deric** [sphinx-doc/sphinx#2441]
Currently [supported backends](https://github.com/sphinx-doc/sphinx/tree/master/sphinx/websupport/search) are IMHO quite outdated:
- Whoosh search
- Xapian

Firstly, is there any tutorial how to configure full-text search backend? And secondly, any chance to extend support to e.g. elasticsearch, PostgreSQL, MongoDB, etc.?

**Comment by tk0miya** [comment]
These backends are used for websupport feature.
You have to build an application to use these search backends.

There are no tutorials for websupport. But we have quickstart document(http://www.sphinx-doc.org/en/stable/web/quickstart.html) and some sample implementations:
- https://github.com/shirou/sphinx-websupport-demo-for-heroku
- https://bitbucket.org/jacobmason/sphinx-demo-webapp
- https://github.com/shimizukawa/sphinx-websupport-app

Secondly, there is no way to add search backends. But, IMO, we can support that if you want to add them.

**Comment by deric** [comment]
Thanks, there's also [Dipus](https://pypi.python.org/pypi/dipus) which uses also Whoosh search. It's distributed as pypi package and it seems to me that it provides similar functionality as the demo apps you mention.

**Comment by tk0miya** [comment]
It seems resolved. Now I close this.
Thanks,
