### ISSUE TITLE
Use rst_prolog and rst_epilog only for rst files?

### ISSUE THREAD

**Issue by mgeier** [sphinx-doc/sphinx#2445]
Apparently, Sphinx adds those to all source files, regardless if those are actually reST files or not.

This leads to problems with some custom `source_parsers`, e.g. https://github.com/spatialaudio/nbsphinx/issues/38

I think `rst_prolog` and `rst_epilog` should only be prepended/appended for actual reST files.
Is there anything speaking against this?

**Comment by birkenfeld** [comment]
No, that makes a lot of sense. Should be a bugfix for 1.4.2.

**Comment by cmdcolin** [comment]
I might want to apply replacements in markdown for example (using recommonmark or similar), so it would be actually nice to preserve some way to do replacements on non RST.

I wasn't actually even getting the rst_epilog to work on markdown though so I am not sure if it's just me or not but this would be a nice-to-have for markdown :)

**Comment by tk0miya** [comment]
Fixed at 9cd5ba9.

BTW, `rst_prolog` is not related with substitution feature directly.
It is a feature of reStructured Text itself. so I think new feature is needed to substitute for markdown or other format.
Now, Sphinx emits `source-read` event for third party extensions. It might support to make extensions which supports substitution on markdowns.
