### ISSUE TITLE
VerbatimBorderColor wrongly used also for captions of PDF literal blocks

### ISSUE THREAD

**Issue by jfbu** [sphinx-doc/sphinx#2447]
This was introduced by commit  9d82cad1 which fixed #2262 and #2319. A fix is upcoming.

test file `index.rst`:

``` rst
=====================
VERBATIM BORDER COLOR
=====================


TEST
====

.. raw:: latex

   \definecolor{VerbatimBorderColor}{rgb}{1,0,0}

.. code-block:: python
   :caption: This is advanced technique.

   x, y = y, x
```

![capture d ecran 2016-04-14 a 08 45 40](https://cloud.githubusercontent.com/assets/2589111/14519287/1d66e444-021e-11e6-995b-4c1ec9ce9021.png)

**Comment by tk0miya** [comment]
Merged.
