### ISSUE TITLE
Generated search index doesn't contain bold and cursive words

### ISSUE THREAD

**Issue by alpharder** [sphinx-doc/sphinx#2449]
We have the following RST:

```
To close the storefront, complete the following steps:

* In the Administration panel, go to **Settings → General**.

* Tick the **Close storefront** checkbox.

* Fill in in the **Access key to temporarily closed store** field.
```

The bolded "close storefront" and "Access key to temporarily closed store" phrases cannot be found at search - the words from those phrases aren't being added to the index.

Facing the same issue with the cursive-selected phrases.

**Comment by TimKam** [comment]
@alpharder I created a minimal working example based on your RST snippet. There, everything works fine.

**Comment by alpharder** [comment]
@TimKam Thanks for your reply. The full RST of the page can be found here: https://raw.githubusercontent.com/cscart/docs/4.3.x/user_guide/look_and_feel/changing_attributes/store_closed.rst

However, our documentation is large and this is not the only article that faces the issue described above. Can the issue be caused by the fact that we have hundreds of articles?

**Comment by TimKam** [comment]
With just this file, it's still fine. Are you able to break the problem down to a clean build that includes not more than a handful of short articles?

**Comment by tk0miya** [comment]
In my envrionment, I can also search the document::

```
$ sphinx-quickstart test
$ cd test
$ curl -LO https://raw.githubusercontent.com/cscart/docs/4.3.x/user_guide/look_and_feel/changing_attributes/store_closed.rst
$ make clean html
```

Searching results:
- close storefront: Matched
- "close storefront": Unmatched
- Access key to temporarily closed store: Matched
- "Access key to temporarily closed store": Unmatched
- Settings → General: Unmatched
- Settings General: Matched

It seems quoted keywords do not work. But it almost work fine.

Could you check your results and environment please?
It would be nice if there is small sample project to reproduce the issue.

**Comment by tk0miya** [comment]
Any updates? I will close this if no one can reproduce this.
