### ISSUE TITLE
Silence warning (opt in) when overriding extension directive

### ISSUE THREAD

**Issue by bsipocz** [sphinx-doc/sphinx#2451]
1.4 introduced a warning for overriding roles/directives from an extension (https://github.com/sphinx-doc/sphinx/issues/1962). 

It would be great if this could be silenced. In our case the overriding is intentional (e.g this contains a few workarounds https://github.com/astropy/astropy-helpers/blob/master/astropy_helpers/sphinx/ext/autodoc_enhancements.py), thus the warning causes unnecessary troubles for the travis docs builds (that are set to fail if any warnings come from sphinx).

**Comment by tk0miya** [comment]
OK, I'll take a look

**Comment by tk0miya** [comment]
I added new configurations values to `suppress_warnings`: `app.add_node`, `app.add_directive`, `app.add_role` and `app.add_generic_role` at 21ee53d.
Please set up your project to ignore warnings using this.

Thanks,
