### ISSUE TITLE
Add keywords of "meta" directive to search index

### ISSUE THREAD

**Issue by TimKam** [sphinx-doc/sphinx#2463]
It would be great to have the keywords of `meta` directives included in the search index.

Like this, one can help users who are searching for a synonym of the "correct" term through simply adding synonyms as keywords to a `meta` directive on the corresponding page.

**Comment by TimKam** [comment]
Given the following meta statement:

```
.. meta::
    :keywords: backup
    :keywords lang=en: pleasefindthiskey pleasefindthiskeytoo
    :keywords lang=de: bittediesenkeyfinden
```

Now, the script adds:
- `pleasefindthiskey`, `pleasefindthiskeytoo` for English
- `bittediesenkeyfinden` for German
- `backup` for all languages

However, it might be good to implement i18n support for meta tags in addition.

Feedback is very much appreciated.

**Comment by tk0miya** [comment]
Now #2516 is merged.
