### ISSUE TITLE
Autodoc: same method from different modules are only once documented

### ISSUE THREAD

**Issue by yuki-93** [sphinx-doc/sphinx#2464]
I am using `.. automodule:: <module>` to generate the documentation of my source. 

I have a method named main in my main module (main.main()) within my source folder and in my tests folder i have a main method in my run_tests module (run_tests.main()). But when I autodoc them, the main method is only once documented. I renamed the second method so that it is run_tests.run_tests(), now it works for both methods.
Is this a feature or bug, that method names are unique, for all modules? Or is there an option, which enables the feature I want?

**Comment by tk0miya** [comment]
I can't reproduce this problem. I tried with Sphinx-1.7.7 and following files:
```
index.rst


.. automodule:: main
   :members:

.. automodule:: tests
   :members:
```
```
# main.py
def main():
    """main function."""
    pass
```
```
# tests.py
def main():
    """main function."""
    pass
```

AFAIK, there are no restriction like "method names are unique, for all modules".
Please let me know your problem in detail if you're still in trouble.

Thanks,

**Comment by tk0miya** [comment]
I'm closing this now because of no response.
Please feel free to reopen if you're still in problem.
Thanks,
