### ISSUE TITLE
Feature request: add ability to exclude/ignore external image warnings

### ISSUE THREAD

**Issue by jputrino** [sphinx-doc/sphinx#2466]
It would be nice to be able to exclude or ignore the warnings that are triggered by external images.

Example:

```
Running Sphinx v1.4
making output directory...
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 14 source files that are out of date
updating environment: 14 added, 0 changed, 0 removed
reading sources... [100%] troubleshooting
README.rst:33: WARNING: nonlocal image URI found: https://readthedocs.org/projects/f5-openstack-lbaasv2/badge/?version=latest
README.rst:37: WARNING: nonlocal image URI found: https://f5-openstack-slack.herokuapp.com/badge.svg
```

See #2429 (where I and another user ran into the same problem when trying to turn off these warnings ourselves). There are enough results about this same issue that come up in a google search to suggest that many others would probably benefit from this option as well.

My use case:
The projects I document use travis-ci; I'd like to be able to use the `sphinx-build -W` command as part of our builds. I use a travis badge and a slack badge on some of our pages, which trigger the `nonlocal image URI` warnings; these would break the build (unnecessarily, IMHO), so I can't use the option to treat sphinx warnings as errors in our builds.

**Comment by tk0miya** [comment]
Thank you for reporting.

I wonder which branch is best to fix this. Anyway, I will add a way to suppress the warning.

**Comment by jputrino** [comment]
Thanks!

**Comment by tk0miya** [comment]
Note:
I discussed with @shimizukawa about target branch. And we decided to fix this in stable branch.

**Comment by tk0miya** [comment]
I added new types to `suppress_warnings` at 52c7867.
After this, you can suppress the warnings with following configuration:

```
suppress_warnings = ['image.nonlocal_uri']
```

Thank you for reporting!

**Comment by jputrino** [comment]
Awesome, thanks!
