### ISSUE TITLE
Exclude content in a specific dir from `sphinx-build` toctree check?

### ISSUE THREAD

**Issue by jputrino** [sphinx-doc/sphinx#2467]
I extensively reuse content in my documentation and normally place files for reuse in an `includes` directory. It would be nice to be able to exclude this directory from the `sphinx-build` toctree check. I currently get a `WARNING: document isn't included in any toctree` for every one of these files (and there are A LOT of them!).

If this functionality already exists, pointers in the right direction would be greatly appreciated!

**Comment by jputrino** [comment]
Here's an example:

```
putrino@BLD-ML-PUTRINO-2: proj (feature.release8.0.1)$ sphinx-build docs/ docs/_build
Running Sphinx v1.4
making output directory...
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 14 source files that are out of date
updating environment: 14 added, 0 changed, 0 removed
reading sources... [100%] troubleshooting
README.rst:33: WARNING: nonlocal image URI found: https://readthedocs.org/projects/f5-openstack-lbaasv2/badge/?version=latest
README.rst:37: WARNING: nonlocal image URI found: https://f5-openstack-slack.herokuapp.com/badge.svg
looking for now-outdated files... none found
pickling environment... done
checking consistency... /Users/putrino/proj/docs/includes/topic_before-you-begin.rst:: WARNING: document isn't included in any toctree
/Users/putrino/proj/docs/includes/topic_configure-neutron-lbaasv2.rst:: WARNING: document isn't included in any toctree
/Users/putrino/proj/docs/includes/topic_configure-the-agent.rst:: WARNING: document isn't included in any toctree
/Users/putrino/proj/docs/includes/topic_features.rst:: WARNING: document isn't included in any toctree
/Users/putrino/proj/docs/includes/topic_install-f5-lbaasv2-packages.rst:: WARNING: document isn't included in any toctree
/Users/putrino/proj/docs/includes/topic_restrictions.rst:: WARNING: document isn't included in any toctree
/Users/putrino/proj/docs/includes/topic_tip-stop-agent.rst:: WARNING: document isn't included in any toctree
/Users/putrino/proj/docs/includes/topic_troubleshooting-f5agent.rst:: WARNING: document isn't included in any toctree
/Users/putrino/proj/docs/includes/topic_troubleshooting-general.rst:: WARNING: document isn't included in any toctree
done
preparing documents... done
writing output... [100%] troubleshooting
generating indices... genindex
writing additional pages... search
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 11 warnings.
```

**Comment by tk0miya** [comment]
Please use `exclude_patterns` to do that.

```
exclude_patterns = ['includes/*.rst']
```

BTW, this behavior is hard to understand to users. It would be nice if sphinx marks the included files as "included in toctree".

**Comment by jputrino** [comment]
@tk0miya - Thanks!

**Comment by flazzarini** [comment]
I still have another use case. I actually want sphinx to render a **non toctree included** rst file, but instruct sphinx so that it would not complain about the file not being in any toc-tree.

**Comment by tk0miya** [comment]
@flazzarini I think `:orphan:` helps you
http://www.sphinx-doc.org/en/stable/markup/misc.html#file-wide-metadata

**Comment by tk0miya** [comment]
I noticed this issue is already fixed by #2605.
So I close this issue now.
Thanks,

**Comment by JonathonReinhart** [comment]
New link for https://github.com/sphinx-doc/sphinx/issues/2467#issuecomment-352774679:

https://www.sphinx-doc.org/en/master/usage/restructuredtext/field-lists.html#metadata

**Comment by Voyz** [comment]
Just in case you struggle to understand why[ the example above](https://github.com/sphinx-doc/sphinx/issues/2467#issuecomment-211697586) doesn't work for you like I did:

>  List of patterns, **relative to source directory** ... to ignore when looking for source files.

So make sure the **paths are relative to your source folder**.

Also, make sure to include full path, in case your files reside in subfolders, eg:

```python
exclude_patterns = ['includes/python/*.rst']
```
for files placed in `source/includes/python` folder.
