### ISSUE TITLE
autosummary: generated stub files are not re-written

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#247]
If the top-level autosummary directive is changed from one sphinx run to the other (e.g. a new option added or the template was changed) the generated stub files in the directory given with the :toctree: option are not automatically updated.

The are onyl re-created if the stub files direcory is deleted manually from the file explorer.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/247
- Originally reported by: [timmie](https://bitbucket.org/timmie)
- Originally created at: 2009-08-29T17:49:55.802

**Comment by shimizukawa** [comment]
_From [pv](https://bitbucket.org/pv) on 2009-08-30 13:10:45+00:00_

This was intended to be a feature allowing customizing the stub files manually when needed. At the moment, I'm undecide which is better.

**Comment by Michael-E-Rose** [comment]
If I understand this correctly I really like to see this feature being implemented.  Whenever new attributes or methods are being added to classes or modules, I am forced to do so much manually which can really be automated.

**Comment by tk0miya** [comment]
Fixed by #6422. It will be released as 3.0 in future (for compatibility reasons, we have to wait a major release).
