### ISSUE TITLE
Request for addition of `timeout` parameter for `intersphinx` downloads

### ISSUE THREAD

**Issue by soupault** [sphinx-doc/sphinx#2474]
It would be great to be able to set `timeout` for `intersphinx` downloads somehow.

To justify the request:
At the moment, AppVeyor provides 60mins builds' limit for all of free accounts. `intersphinx` downloads and linking can take (for environment with unreliable servers) up to 40mins of this quota.

See https://github.com/scikit-image/scikit-image/issues/2042 for the details.

**Comment by lehmannro** [comment]
It should be as trivial as adding the `timeout=` parameter to `Opener.open`.  I'll gladly review a PR.

On another note, I think it'd also be worthwhile to revamp the intersphinx code to rely on `requests` after #2389 is in.

**Comment by soupault** [comment]
@lehmannro do you have any preferences regarding the configuration of this feature? 
Should it be available via [standard API](https://github.com/scikit-image/scikit-image/blob/master/doc/source/conf.py#L304-L305)? Does it make sense to set some default value for timeout (e.g., 5-10 minutes).

**Comment by soupault** [comment]
Perfect, thanks!
