### ISSUE TITLE
autosummary: option for all modules of a package

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#248]
Like in this example:

``` rst

.. autosummary::
   :toctree: generated/

   MaskedArray.base
   MaskedArray.ctypes
   MaskedArray.dtype
   MaskedArray.flags
```

one currently has to explicitly state the modules that should be documented by autosummary.

Please add option to automatically create stub files for all files in a package:

coule be like: 

``` rst

.. autosummary::
   :toctree: generated
   :nosignatures:
   :fullpackage: mypackage_toplevel_dir
```

This should then automatically include all modules in teh package "mypackage_toplevel_dir".

P.S.: I hope that this is not a misunderstanding or misconfiguration on my side. maybe this is already implemented?

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/248
- Originally reported by: [timmie](https://bitbucket.org/timmie)
- Originally created at: 2009-08-29T17:55:22.407

**Comment by shimizukawa** [comment]
_From [jasongrout](https://bitbucket.org/jasongrout) on 2014-08-23 05:03:39+00:00_

FYI, the astropy automodsumm has functionality something like this (see https://github.com/astropy/astropy-helpers/blob/master/astropy_helpers/sphinx/ext/automodsumm.py).  It looks like sphinxydoc might be something good to look at too from https://github.com/sphinx-doc/sphinx/issues/317 (see https://github.com/Ciantic/sphinkydoc)

**Comment by maikelmeyers** [comment]
Is this still not implemented? I would like to see this feature.

**Comment by ben-spiller** [comment]
+1 

Would be best as a general capability for autosummary to include/exclude members (whether members of a module or a class/exception), similar to how automodule/autoclass work. 

e.g.
```
.. autosummary:: MyModuleOrClass
  :members:
  :private-members:
  :inherited-members:
  :exclude-members: not_this_one
```

We already have logic for getting the members of a module. Hopefully we can find some way to also reuse the autodoc code for include/excludes for autosummary.
