### ISSUE TITLE
FileNotFoundError with ext/autosummary when using multiple source_suffix values

### ISSUE THREAD

**Issue by marshalc** [sphinx-doc/sphinx#2485]
I have (an edge case?) bug with ext/autosummary when using `conf.py: source_suffix = ['.rst', '.md', '.txt']` and then trying to build documents. I'm set up to use a mixture of Markdown and ReST, but find that autosummary makes assumptions about there only being one type of file present and that it needs to add a file extension.

You'll see output like this on the build:

```
Exception occurred:
  File "/Users/carl/.virtualenvs/guerdon/bin/../lib/python3.5/codecs.py", line 895, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: <<filepath>>
```

I'll confess that I haven't managed to work through the logic fully to determine why this would make sense (there could well be a valid reason for most other users), however I've found that patching `lib/python3.5/site-packages/sphinx/ext/autosummary/__init__.py` lines 599 & 600 with the following works for me...

```
    # genfiles = [genfile + (not genfile.endswith(ext) and ext or '')
    #             for genfile in genfiles]
    # Filter files for ReST files only
    genfiles = [genfile for genfile in genfiles if genfile.endswith('.rst')]
```

Is this a bug? Is the fix likely to cause consequences elsewhere that I've not yet discovered?

**Comment by tk0miya** [comment]
Maybe it's a bug. There might be more bugs related with a mixture of multiple source suffix.

**Comment by kdebrab** [comment]
Using ext/autosummary with `source_suffix = ['.rst', '.md']` and having a file `<<docs_folder>>/index.md` defined, I got the same issue:

```
# Sphinx version: 1.4.5
# Python version: 2.7.10 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\sphinx\cmdline.py", line 243, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "c:\python27\lib\site-packages\sphinx\application.py", line 204, in __init__
    self._init_builder(self.buildername)
  File "c:\python27\lib\site-packages\sphinx\application.py", line 279, in _init_builder
    self.emit('builder-inited')
  File "c:\python27\lib\site-packages\sphinx\application.py", line 551, in emit
    results.append(callback(self, *args))
  File "c:\python27\lib\site-packages\sphinx\ext\autosummary\__init__.py", line 564, in process_generate_options
    base_path=app.srcdir)
  File "c:\python27\lib\site-packages\sphinx\ext\autosummary\generate.py", line 115, in generate_autosummary_docs
    items = find_autosummary_in_files(sources)
  File "c:\python27\lib\site-packages\sphinx\ext\autosummary\generate.py", line 225, in find_autosummary_in_files
    errors='ignore') as f:
  File "c:\python27\lib\codecs.py", line 884, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: u'<<docs_folder>>\index.md.rst'
```

index.md.rst? That should be index.md!

It indeed seems like the root cause of this issue lies in lines 558-560 of `c:\python27\lib\site-packages\sphinx\ext\autosummary\__init__.py`:

```
ext = app.config.source_suffix[0]
genfiles = [genfile + (not genfile.endswith(ext) and ext or '')
            for genfile in genfiles]
```

which looks only at the first element of source_suffix.

A quick workaround was changing the order of source_suffix into `source_suffix = ['.md', '.rst']`, but then the same problem would occur for .rst files, if present. The solution proposed by @marshalc seems the appropriate solution (and in any case worked for me).
