### ISSUE TITLE
Figure directive with :figwidth: generates incorrect Latex-code

### ISSUE THREAD

**Issue by chriswthorp** [sphinx-doc/sphinx#2492]
.. figure:: _static/1833-CharlesBabbageDifferenceEngine.JPG
   :align: right
   :width: 25%
   :figwidth: 30%

generates this:

\begin{wrapfigure}{r}{30%}
\centering
\includegraphics[width=0.250\linewidth]{{1833-CharlesBabbageDifferenceEngine}.JPG}
\caption{Figurtittel}{\small 
Figurtekst
}\label{bilder:id1}\end{wrapfigure}

Latex chokes on "{30%}", but will accept {0.3\linewidth}.

**Comment by tk0miya** [comment]
Fixed at 4789ef8.
Thank you for reporting!
