### ISSUE TITLE
AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by Taymindis** [sphinx-doc/sphinx#2494]
# Sphinx version: 1.4.1
# Python version: 3.5.1 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:
# Loaded extensions:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/sphinx/cmdline.py", line 243, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/usr/lib/python3.5/site-packages/sphinx/application.py", line 132, in **init**
    confoverrides or {}, self.tags)
  File "/usr/lib/python3.5/site-packages/sphinx/config.py", line 289, in **init**
    execfile_(filename, config)
  File "/usr/lib/python3.5/site-packages/sphinx/util/pycompat.py", line 130, in execfile_
    exec_(code, _globals)
  File "conf.py", line 272, in <module>
AttributeError: 'str' object has no attribute 'decode'

**Comment by tk0miya** [comment]
It seems the error is happened at your `conf.py`.
Could you check your conf.py, line 272?

**Comment by Taymindis** [comment]
def **init**(self, dirname, filename, overrides, tags):
         self.overrides = overrides
         self.values = Config.config_values.copy()
         config = {}
         if 'extensions' in overrides:  # XXX do we need this?
             if isinstance(overrides['extensions'], string_types):
                 config['extensions'] = overrides.pop('extensions').split(',')
             else:
                 config['extensions'] = overrides.pop('extensions')
         if dirname is not None:
             config_file = path.join(dirname, filename)
             config['**file**'] = config_file
             config['tags'] = tags
             with cd(dirname):
                 # we promise to have the config dir as current dir while the
                 # config file is executed
                try:
                     execfile_(filename, config)
                except SyntaxError as err:
                     raise ConfigError(CONFIG_SYNTAX_ERROR % err)
                except SystemExit:
                     raise ConfigError(CONFIG_EXIT_ERROR)
`

**Comment by tk0miya** [comment]
Sorry for late response.

It seems `config.py` in sphinx, not `conf.py`.
Could you show me your `conf.py` on project directory?
It is placed near `Makefile` or `index.rst`.

Thanks,

**Comment by tk0miya** [comment]
Now I close this.
Please reopen if you still have this problem.

Thanks,
