### ISSUE TITLE
Document versioning

### ISSUE THREAD

**Issue by adrienb4** [sphinx-doc/sphinx#2496]
Hi

It is possible to have a versioning of document and go back to old version ? 

Thank

Adrien

**Comment by lehmannro** [comment]
_Please note this is our issue tracker, used to report deficiencies and discuss possible code improvements.  For usage questions, please see [sphinx-users](https://groups.google.com/d/forum/sphinx-users)._

There is [versioning](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/versioning.py) in Sphinx, but it's not for going back to old versions.  ReadTheDoc's [Versions](http://docs.readthedocs.org/en/latest/versions.html) might be more what you're looking for.
