### ISSUE TITLE
Wrong LaTeX generation of Unicode numerical subscripts in code examples

### ISSUE THREAD

**Issue by asr** [sphinx-doc/sphinx#2501]
For example, the inline code ``Foo₁`` is generated as `\code{Foo1}` instead of `\code{Foo₁}` when using `make latex`.

Tested with Sphinx  1.4.1.

Blocking https://github.com/agda/agda/issues/1953.

**Comment by asr** [comment]
I fixed the example in the OP.

**Comment by asr** [comment]
I only could  reproduce the issue using the numerical subscripts `₁` or `₂`. Weird!

**Comment by tk0miya** [comment]
This comes from escaping process for LaTeX:
https://github.com/sphinx-doc/sphinx/blob/1.4.1/sphinx/util/texescape.py#L50

I don't know why subscript numbers are normalized.

Anyway, I fixed it at 488ee52.
Thank you for reporting.

**Comment by asr** [comment]
Thanks for fixing the issue.
