### ISSUE TITLE
:orphan: field causes WARNING: Field list ends without a blank line; unexpected unindent.

### ISSUE THREAD

**Issue by tylerbutler** [sphinx-doc/sphinx#2505]
This is easy to reproduce; simply create a new RST file in your sphinx project that looks something like the below, but is not contained in any toctrees:

``` rst

:orphan:

..  _Email integration:

Email integration
=================

TODO: write content
```

When you do a build, you'll see a warning like this:

```
email.rst:3: WARNING: Field list ends without a blank line; unexpected unindent.
```

Sort of defeats the purpose of the field, since I'm just trading one warning (`WARNING: document isn't included in any toctree`) for a different warning.

**Comment by barbara-sfx** [comment]
Why don't you just add a Return after the TODO line? I think that fixes it.

**Comment by barbara-sfx** [comment]
P.S. Thanks for asking the question. I didn't know about :orphan: and now I have finally gotten rid of all those stupid warnings.

**Comment by tylerbutler** [comment]
@barbara-sfx That does not fix it, at least not in version 1.4.1. The attached file reproduces this for me (rename the extension if needed depending on your Sphinx config).

[foo.rst.txt](https://github.com/sphinx-doc/sphinx/files/243028/foo.rst.txt)

**Comment by barbara-sfx** [comment]
I'm in 1.4 and it works for me. I put your file in my project and didn't get any errors when I built it. Now I'm afraid to install 1.4.1. Not that I even knew it existed until just now.... Actually I tried without that Return at the end and didn't get an error. Did you try make clean html? Other than that, I've reached the limit of my expertise. Sorry.

**Comment by tk0miya** [comment]
I could not reproduce the issue with following steps too:

```
$ sphinx-quickstart test

$ cd test
$ curl -L -o foo.rst https://github.com/sphinx-doc/sphinx/files/243028/foo.rst.txt
$ make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.4.1+
making output directory...
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 2 source files that are out of date
updating environment: 2 added, 0 changed, 0 removed
reading sources... [100%] index
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index
generating indices... genindex
writing additional pages... search
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded.

Build finished. The HTML pages are in _build/html.
```

It might another settings or configurations are needed to reproduce this.
Could you check it again please?

**Comment by tylerbutler** [comment]
Thanks; I'll try to repro on a fresh virtualenv with just Sphinx installed. Then I'll try it with a fresh clone of my repo and see if it repros there. I'll let you know what I find.

**Comment by tylerbutler** [comment]
BTW, in case it matters, I'm on Windows Server 2012 R2.

**Comment by nmat** [comment]
I have tried to reproduce this on a win environment using cygwin but can't reproduce it either.

**Comment by tk0miya** [comment]
Any updates? I will close this if no one can reproduce this.

**Comment by tk0miya** [comment]
Now I close this.
Please reopen if you get the warning.

Thanks,

**Comment by pgerber** [comment]
I ran into the same issue. In my case the cause was a `rst_prolog = ".. include:: /global.rst"` in `conf.py` which inserted the include at the beginning of the document. I was able to resolve the issue by appending the include to the document instead (`rst_epilog = …`).

**Comment by tk0miya** [comment]
@pgerber I'd like to know your case in detail. Could you file a new issue please?
Especially, I'd like to know how you can reproduce it.

**Comment by cpitclaudel** [comment]
I believe this was fixed in https://github.com/sphinx-doc/sphinx/commit/07c5348a56471201b5901881b0d9d83f4823a6fd

Before that commit, it seems that the content of the prolog were inserted before the info lines (is that right?)

**Comment by tk0miya** [comment]
I believe the commit did not change the behavior of prolog.

**Comment by cpitclaudel** [comment]
Hmm, you're right, I misread.
