### ISSUE TITLE
Improve LaTeX makefile

### ISSUE THREAD

**Issue by nowox** [sphinx-doc/sphinx#2511]
The current LaTeX makefile does not really follow the make philosophy. Generic rules can be written instead of shell `for` loop: 

```
all-ps: all-dvi
    for f in *.dvi; do dvips $$f; done
```

I guess this is way better:

```
%.ps: %.dvi
   dvips $< -o $@
```

The whole makefile might be rewritten according to my remarks...

I think I'll do it if you guys agree with me.

**Comment by tk0miya** [comment]
That's a good point :-)
