### ISSUE TITLE
Use jinja templates for LaTeX output

### ISSUE THREAD

**Issue by nowox** [sphinx-doc/sphinx#2512]
The main LaTeX document is partially hard-coded in the LaTeX writer using directives such as: 

```
HEADER = r'''%% Generated by Sphinx.
\def\sphinxdocclass{%(docclass)s}
\documentclass[%(papersize)s,%(pointsize)s%(classoptions)s]{%(wrapperclass)s}
%(passoptionstopackages)s
%(inputenc)s
%(utf8extra)s
%(cmappkg)s
%(fontenc)s
%(amsmath)s
%(babel)s
%(fontpkg)s
%(fncychap)s
%(longtable)s
\usepackage{sphinx}
\usepackage{multirow}
\usepackage{eqparbox}
%(usepackages)s
%(contentsname)s
%(numfig_format)s
%(pageautorefname)s
%(tocdepth)s
%(preamble)s

\title{%(title)s}
\date{%(date)s}
\release{%(release)s}
\author{%(author)s}
\newcommand{\sphinxlogo}{%(logo)s}
\renewcommand{\releasename}{%(releasename)s}
%(makeindex)s
'''   
```

Sphinx currently accepts two standard classes: `manual` and `howto`. Back compatibility can be preserved forcing the these two classes to use the same template `default.tex`.

I am thinking to modify the `astext` method (showed below) to load a jinja2 template where tags such as `%(docclass)s` are rewritten using jinja delimiters.

```
    def astext(self):
        return (HEADER % self.elements +
                self.highlighter.get_stylesheet() +
                u''.join(self.body) +
                '\n' + self.elements['footer'] + '\n' +
                self.generate_indices() +
                FOOTER % self.elements)
```

Eventually we will get one new file named `default.tex` into the `texfiles` directory. The user is free to mention a different template name with a config option `latex_template`

**Comment by tk0miya** [comment]
Note:
For now, LaTeX builder uses jinja templates (customized to JSP/eRuby like syntax):
https://github.com/sphinx-doc/sphinx/blob/1.5a2/sphinx/templates/latex/content.tex_t
