### ISSUE TITLE
Generated Makefile should allow easy change of build dir

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#252]
Currently the generated Makefile uses './build/' as a build dir prefix. However in my projects I keep sphinx docs under '/docs/' but want to have the generated html documentation in '/build'. This can be accomplished by changing the Makefile.

However there are a lot of references to the build directory so you have to change each and every of them. It would be easier if there is just a variable which can be changed once.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/252
- Originally reported by: Felix Schwarz
- Originally created at: 2009-09-02T22:43:17.523

**Comment by shimizukawa** [comment]
_From Felix Schwarz on 2009-09-02 20:44:16+00:00_

The batch file patch is untested (due to a lack of Windows)

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2009-09-03 13:56:17+00:00_

Thanks, added in <<cset 3276bb42c864006a06ec8ea93af23f71760401c0>>.

**Comment by FrancescoSaverioZuppichini** [comment]
So, how can I change the output dir?

**Comment by shimizukawa** [comment]
Please change the BUILDDIR parameter in your Makefile.
For more detail. please ref sphinx-build command option reference: https://www.sphinx-doc.org/en/master/man/sphinx-build.html

BTW, this issue was closed a long time ago, so please create a new Issue if you have problems.
https://github.com/sphinx-doc/sphinx/issues/new/choose
