### ISSUE TITLE
quickstart makefile error catch for "Command not found" not working correctly.

### ISSUE THREAD

**Issue by michaelaye** [sphinx-doc/sphinx#2521]
I have my dev setup running on 2 different machines, and recently started to dabble with Sphinx. When I swapped machines, I forgot to install sphinx on the 2nd machine.
Instead of being told that the `sphinx-build` command was not found though, I got the most mysterious (well, I'm not good with Makefiles) error:

``` bash
(stable)└─❱❱❱ make html                                                          1 ⏎  +5137 16:45 ❰─┘
Makefile:12: *** commands commence before first target.  Stop.
```

After looking at line 12:

``` make
    $(error The '$(SPHINXBUILD)' command was not found. Make sure you have Sphinx installed, then 
```

it dawned on me, that I forgot to install `sphinx` on this machine. But I guess one would want this error reporting to work better?
I wondered if this were caused by me using `zsh`, but switching to `/bin/bash` did not make it better.

For your convenience, I copy the first lines of the Makefile here (which is the exact one created by the sphinx-quickstart script) for your review:

``` make
# Makefile for Sphinx documentation
#

# You can set these variables from the command line.
SPHINXOPTS    =
SPHINXBUILD   = sphinx-build
PAPER         =
BUILDDIR      = _build

# User-friendly check for sphinx-build
ifeq ($(shell which $(SPHINXBUILD) >/dev/null 2>&1; echo $$?), 1)
    $(error The '$(SPHINXBUILD)' command was not found. Make sure you have Sphinx installed, then set the SPHINXBUILD environment variable to point to the full path of the '$(SPHINXBUILD)' executable. Alternatively you can add the directory with the executable to your PATH. If you don\'t have Sphinx installed, grab it from http://sphinx-doc.org/)
endif
```

**Comment by tk0miya** [comment]
Sorry for inconvenience. This comes from #1024. It seems this is unexpected behavior.
But I don't know the good way to fix this.
@techtonik @shimizukawa Do you have any idea to fix this error?

Thanks,

**Comment by shimizukawa** [comment]
The feature depends on GNU make functionality, so it doesn't work with BSD make.
IMO, we should remove the friendly message to keep simple. Simple way is not friendly than now, but it is not confusable.

**Comment by techtonik** [comment]
Those system-dependent runners should be replaced by Python script.

**Comment by techtonik** [comment]
I don't know why there is Makefile dependency at all. If somebody needs cross-platform Pythonic solution, it is better use SCons etc.

**Comment by lepistone** [comment]
Hi! Personally I think Makefiles are just fine and this one does its job nicely, no need to reinvent the wheel to have everything in python.

But the error message makes things actually harder with BSD make (including Macs) so I think #1024 should just be reverted.

Thanks!

EDIT: the error without #1024 is just

```
sphinx-build -b html -d _build/doctrees   . _build/html
make: sphinx-build: No such file or directory
make: *** [html] Error 1
```

it looks fine to me.

**Comment by tk0miya** [comment]
Hi all,
Finally, I reverted #1024 and keep makefile simple.

Thank you for your comments.

**Comment by techtonik** [comment]
@tk0miya did you revered make.bat changes? Why?

**Comment by tk0miya** [comment]
I think there is no reason to revert make.bat. Because this problem is caused from combination of BSD make and Makefile. make.bat is not related.

**Comment by lepistone** [comment]
Yup, `make.bat` looks unrelated. Sorry for the confusion!
