### ISSUE TITLE
For some projects, the toctree_only flag in latex_documents has no effect

### ISSUE THREAD

**Issue by brechtm** [sphinx-doc/sphinx#2525]
I'm trying to obtain similar output from my [rinohtype](http://www.mos6581.org/rinohtype/) builder as what the LaTeX builder produces. I'm running into either something I don't understand, or a bug.

For [Jupyter's documentation](http://jupyter.readthedocs.io/en/latest/), `toctree_only` is not set in `conf.py`, yet the LaTeX builder acts as if it was set to `True`; the top-level section title "Project Jupyter and IPython" is missing from the PDF. Explicitly setting `toctree_only` to `True` or `False` has not effect on this behaviour. Setting it to `True` does remove the non-toctree elements from the output however.

I could not find out why the LaTeX builder acts as if `toctree_only` was set to `True` even though it was not specified and defaults to `False`.

**Comment by brechtm** [comment]
I am indeed misunderstanding things. I thought the `toctree_only` flag also had an effect on the removal of the top-level section title, but that doesn't seem to be the case...

I believe the top-level section title is always being removed by the LaTeX builder. Is that correct?

**Comment by tk0miya** [comment]
Yes, you're right. The top-level section is always removed on latex builder. And `toctree_only` option ignores non-TOC tree elements on startdocs. The reference manual says:

> toctree_only: Must be True or False. If true, the startdoc document itself is not included in the output, only the documents referenced by it via TOC trees. With this option, you can put extra stuff in the master document that shows up in the HTML, but not the LaTeX output.
> http://www.sphinx-doc.org/en/stable/config.html#confval-latex_documents

I don't know why and it is a bit strange to me. But LaTeX builder behaves like that since 0.3 (ref: 9fc2a9b7ad3421c8e7db4e64986413689a6d7c22).

**Comment by tk0miya** [comment]
It seems resolved. Now I close this.
Thanks,
