### ISSUE TITLE
ReadTheDocs+Sphinx : sphinx documentation of my github repo not building on ReadTheDocs

### ISSUE THREAD

**Issue by anirbanroydas** [sphinx-doc/sphinx#2526]
I have been trying to build my github repo having sphinx documentation files on readthedocs.org to host it there, but every time it is giving me this error:

**NOTE  :**  I have already tried to do `make html` and found it to be working locally.
**Github repo :** [https://github.com/anirbanroydas/sphinxSimDoc](https://github.com/anirbanroydas/sphinxSimDoc)

**The following build process and error is being shown :** 

`python /home/docs/checkouts/readthedocs.org/user_builds/sphinxsimdoc/envs/latest/bin/sphinx-build -b latex -D language=en -d _build/doctrees . _build/latex`

**And this is the build process log showing the error :**

> Running Sphinx v1.3.5
> making output directory...
> loading translations [en]... done
> loading pickled environment... failed: 'module' object has no attribute 'Symbol'
> building [mo]: targets for 0 po files that are out of date
> building [latex]: all documents
> updating environment: 10 added, 0 changed, 0 removed
> reading sources... [ 10%] README
> reading sources... [ 20%] custom_look
> reading sources... [ 30%] getting_started
> reading sources... [ 40%] guide
> reading sources... [ 50%] guide/details
> reading sources... [ 60%] guide/installation
> reading sources... [ 70%] guide/overview
> reading sources... [ 80%] guide/technical_specs
> reading sources... [ 90%] guide/usage
> reading sources... [100%] index
> 
> /home/docs/checkouts/readthedocs.org/user_builds/sphinxsimdoc/checkouts/latest/sampledoc/custom_look.rst:6: WARNING: Duplicate explicit target name: "sphinx".
> looking for now-outdated files... none found
> pickling environment... done
> checking consistency... done
> processing sphinxSimDoc.tex... index guide guide/details guide/overview guide/technical_specs guide/installation guide/usage README getting_started custom_look 
> resolving references...
> writing... 
> Exception occurred:
>   File "/home/docs/checkouts/readthedocs.org/user_builds/sphinxsimdoc/envs/latest/local/lib/python2.7/site-packages/sphinx/writers/latex.py", line 723, in visit_title
>     short = '[%s]' % ' '.join(clean_astext(node).split()).translate(tex_escape_map)
> TypeError: expected a character buffer object
> The full traceback has been saved in /tmp/sphinx-err-M_gCC6.log, if you want to report the issue to the developers.
> Please also report this if it was a user error, so that a better error message can be provided next time.
> A bug report can be filed in the tracker at https://github.com/sphinx-doc/sphinx/issues. Thanks!

**Comment by brianjking** [comment]
@anirbanroydas Looks like it's failing not in the html deployment, but in the PDF or ePub creation on readthedocs.org. Have you tried to create this locally? Have you disabled PDF & epub on readthedocs.org to see if you can deploy without those features?

**Comment by anirbanroydas** [comment]
@brianjking  Yes you are right, I did not try `make latex` or `make latexpdf` locally. So I went ahead and tried those commands and I get the same error locally.

Moreover, even with those build errors in readthedocs, since my html is successfully built, so the html site is accessible. Since I have enabled pdf in readthedocs, its trying to build latex too, and I am sure disabling those will give me a clean build.

Now, in light of the fact that `make latex` is giving such build errors, can you tell me what might be the problem with `make latex` and how to solve this.

As far as readthedocs is concerned, consider that solved. Just the `latex` build issue is what I want to solve now.

> **OS:**  Mac OS X 10.11.x

**Comment by tk0miya** [comment]
Thank you for reporting. I could reproduce the issue with your repository.
This issue is caused by the section having only images.

I fixed this at 7c0b7e1.

Thanks,

**Comment by anirbanroydas** [comment]
@tk0miya  Thanks for fixing. What did you mean by **"you could reproduce the issue with my repository"**?

**Comment by tk0miya** [comment]
It means I reproduced the issue with your repository located at https://github.com/anirbanroydas/sphinxSimDoc .
I downloaded and builded it locally. And then I get the same error.

**Comment by anirbanroydas** [comment]
Okay. Thanks a lot. I'll upgrade sphinx once the bug fix is released.
