### ISSUE TITLE
make latexpdf and hiperlinks: "LaTeX Error: Counter too large."

### ISSUE THREAD

**Issue by jcea** [sphinx-doc/sphinx#2530]
Sphinx 1.4.1 here. Latex as included in Debian Jessie.

After spending many hours trying to isolate a minimal testcase, I have this file:

```
O
=

.. _X: http://example.com/

X_ X_ X_ X_ X_ X_ X_ X_ X_
X_ X_ X_ X_ X_ X_ X_ X_ X_
X_ X_ X_ X_ X_ X_ X_ X_ X_

.. warning::

   X_
```

When doing "make latexpdf" I get this error:

```
Adding blank page after the table of contents.
[1] [2]
Cap\'{\i }tulo 1.

! LaTeX Error: Counter too large.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              

l.205 \href{http://example.com/}{X}\footnote[28]
                                                {\sphinxAtStartFootnote%
```

If I have less that 27 links, no problem. If I have more but no "warning" directive, no problem.

With my configuration, hiperlinks are converted to footnotes. That is, "latex_show_urls = 'footnote'" in "conf.py". Using "no" or "inline" works fine.

**Comment by jfbu** [comment]
HI, this is caused because the warning type admonition is done in `1.4.1` using a minipage. The good news is that current stable branch for 1.4.2 does not use a minipage anymore. The bad news is that it still uses minipage numbering for footnotes, which uses letters hence crashes beyond footnote number 26. Thus your issue will happen still with 1.4.2 (if nothing is changed until release). To go around the problem you can add this to `conf.py` (commented out things only for context)

``` python
latex_elements = {
# The paper size ('letterpaper' or 'a4paper').
#'papersize': 'letterpaper',

# The font size ('10pt', '11pt' or '12pt').
#'pointsize': '10pt',

# Additional stuff for the LaTeX preamble.
'preamble': 
"""\\def\\thempfootnote{\\arabic{mpfootnote}}
""",

# Latex figure (float) alignment
#'figure_align': 'htbp',
}
```

**Comment by tk0miya** [comment]
I got same error with stable branch.

I think it would be nice if `\thempfootnote` is defined by default.
@jfbu What do you think?

**Comment by jfbu** [comment]
@tk0miya as Sphinx generates footnotes with `[Number]` in latex source, independent of whether the footnote is located in a context rendered by minipage (*), and the `[Number]` is part of a continuous numbering across document, I agree it is better to have `\def\thempfootnote{\arabic{mpfootnote}}` as default. 

anyway, besides the 26 max problem, it is odd to have for example a  `\footnote[5]` in a Warning which will thus use letter `e`, hence we go from 1, 2, 3, 4 before the Warning to `e` inside it, then to 6 again etc in document... I think it is better to have `5` also in the Warning box.

one could imagine that an author uses 

``` rst
.. warning::

   test [1]_

   .. [1] hello

   test [2]_

   .. [2] hello
```

to force use of `a`, `b`, etc... but then (I tested now) the automatic numbering of footnotes elsewhere will not use `1` and `2` and start at `3` which is odd. And one can not do another warning block with again `1` and `2` (to produce `a` and `b`), as one gets on `make latex`

```
ERROR: Duplicate target name, cannot be used as a unique reference: "2".
```

(*) like a Warning; side note: technically up to 1.4.1 Warning used really a minipage, but now in stable branch with commit 68becb11, it is breakable across pages, and for backwards compatibility aspects of minipage such as handling of footnotes was maintained  and they are printed inside the Warning box, not at bottom of page. On the other hand lightweight Notices like `hint` never used a minipage thus a footnote from there is printed at bottom of page.

added memo: with current stable branch it would be easy to get the footnotes from inside Warning to be among the regular footnotes at bottom of page, as one only needs to remove some LaTeX code from `sphinx.sty` (in `\py@heavybox` and `\py@endheavybox`). But perhaps it makes sense to keep footnotes inside the frame.

note: during testing I saw that LaTeX writer adds a space before `\footnote` for normal footnotes but not for those generated if `latex_show_urls='footnote'`. I will open issue but will then be off internet until May 31.

**Comment by jfbu** [comment]
about

> added memo: with current stable branch it would be easy to get the footnotes from inside Warning to be among the regular footnotes at bottom of page, as one only needs to remove some LaTeX code from sphinx.sty (in \py@heavybox and \py@endheavybox). But perhaps it makes sense to keep footnotes inside the frame.

sorry I was too quick, it is more complicated due to multi-pass `framed` environment. One would need to use the `\makesavenoteenv{framed}` using loaded package `footnote.sty` like `sphinx.sty` already does with `tabulary`. But `footnote.sty` has bugs, and better would be to use more recent http://www.ctan.org/pkg/footnotehyper which could be shipped with sphinx. Anyway, sorry for digression, this is not main issue here.

**Comment by tk0miya** [comment]
I added the definition of `\thempfootnote` at e3e827e.
So this will be resolved with the issue.

Note: we still have many themes to improve footnotes:
- numbering rule of footnotes; manually numbered footnotes and auto numbered
- scope of footnote numbers
- position of footnotes defined inside admonitions
- switching footnote counter (cf. a, b, c...) in adomonitions

I will post a new issue and close this later

**Comment by jfbu** [comment]
@tk0miya making working hyperlinked (clickable) footnotes from code captions, from inside tables, etc..., is another thorny issue for pdf output, it works for some constructs but not all. But before making effort on this for tables, the way Sphinx does tables in LaTeX probably needs reviewing. (unfortunately `tabu` package is still awaiting its announced update)

**Comment by tk0miya** [comment]
> I will post a new issue and close this later

I made #2616. so I close this now.

Thank you for reporting!
