### ISSUE TITLE
ReST external links not working with sphinx.ext.napoleon

### ISSUE THREAD

**Issue by cdwilson** [sphinx-doc/sphinx#2537]
I tried the napoleon extension for the first time using the example from http://www.sphinx-doc.org/en/stable/ext/example_numpy.html#example-numpy and I'm getting the error:

`example_numpy.py:docstring of sphinxtest.example_numpy:3: ERROR: Unknown target name: "numpy documentation howto".`

However, if I move the target `.. _NumPy Documentation HOWTO:` before the reference, the error goes away:

```
"""Example NumPy style docstrings.

.. _NumPy Documentation HOWTO:
   https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt

This module demonstrates documentation as specified by the `NumPy
Documentation HOWTO`_. Docstrings may extend over multiple lines. Sections
are created with a section header followed by an underline of equal length.
...
```

Here's my extensions in `conf.py`:

```
xtensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.doctest',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.mathjax',
    'sphinx.ext.ifconfig',
    'sphinx.ext.viewcode',
    'sphinx.ext.githubpages',
    'sphinx.ext.napoleon',
]
```

I'm using Sphinx==1.4.1

**Comment by cdwilson** [comment]
Adding an additional empty line after the attributes section appears to fix this issue:

```
Attributes
----------
module_level_variable1 : int
    Module level variables may be documented in either the ``Attributes``
    section of the module docstring, or in an inline docstring immediately
    following the variable.

    Either form is acceptable, but the two should not be mixed. Choose
    one convention to document module level variables and be consistent
    with it.


.. _NumPy Documentation HOWTO:
   https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt
```

Is there a requirement to have 2 or more blank lines after each section?

**Comment by RobRuana** [comment]
Thanks for reporting, I'll look at the docs as soon as I get a chance!

**Comment by RobRuana** [comment]
Yes, there is a requirement for sections to have two blank lines, unless the section is indented. I think what happened is that the `Attributes` section looks like it is indented even though it isn't, because the `module_level_variable1` description is so long.

Great catch, I'll update the docs as needed!
