### ISSUE TITLE
Sphinx 1.4+ and block literals in Returns with sphinx-napoleon don't work anymore

### ISSUE THREAD

**Issue by Drachenfels** [sphinx-doc/sphinx#2541]
Hi guys,

I am not perfectly sure if it's bug, or some change that I didn't catch after reading changelog.

I am using this example as template:

http://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html

To be exact this part of the guide:

The `Returns` section supports any reStructuredText formatting, including literal blocks::

My code looks as follows (documentation of function signature):

```
Returns:
    None:

    ::

        {
            "status": "update",
            "success": True,
        }
```

For sphinx 1.3.5-1.3.6 it works as expected.

For sphinx 1.4.0-1.4.1 it throws error like that:

```
api/v0_0/views.py:docstring of api.v0_0.views.add_gallery:19: ERROR: Unexpected indentation.
api/v0_0/views.py:docstring of api.v0_0.views.add_gallery:21: WARNING: Block quote ends without a blank line; unexpected unindent.
```

Is it a bug? Has something changed recently? I tried several combinations with different indentations and short block literals format, it makes  no difference.

**Comment by tk0miya** [comment]
@RobRuana Could you check this please?

**Comment by RobRuana** [comment]
Thanks, I'll take a look!

**Comment by Drachenfels** [comment]
@RobRuana I have prepared  demo that may help you pinpoint problem. All you need to do is to git clone, pip install Sphinx and then execute ./generate_docs.sh. There will be warning about Returns section.

https://github.com/Drachenfels/sphinx-bug-example

Screenshot that demonstrates bug, only first opening curly bracket is part of Returns section.

![20160518134853](https://cloud.githubusercontent.com/assets/135730/15359041/5828556c-1cff-11e6-9553-afa4d305850c.png)

**Comment by RobRuana** [comment]
Wow, an entire example project to demonstrate the bug! Excellent bug report :)

Many thanks!
