### ISSUE TITLE
epub spine and toc are in different order

### ISSUE THREAD

**Issue by eshellman** [sphinx-doc/sphinx#2545]
epubs built by sphinx cannot be loaded to KDP (Amazon) because the spine and toc are not in the same order. The issue is discussed here: http://www.mobileread.com/forums/showthread.php?s=87209496c36420aee0544932c0aa2c0f&t=254453&page=2

It looks to me like the best way to fix this by generating the spine in sphinx.builders.epub.EpubBuilder.build_navpoints and passing it to sphinx.builders.epub.EpubBuilder.build_content. This is my first time looking at the Sphinx code and would appreciate comments from anyone who's worked on the code before I go in and change things around.

**Comment by mgifford** [comment]
I ran into this issue too. I think it's a problem in pushing to other platforms too. I think it was Lulu or Barnes & Noble that failed with me.

**Comment by shibukawa** [comment]
From 1.6, Sphinx migrates Epub builder from 2 to 3. 3 generates cleaner toc.

I made epub on master branch (1.6 will be released soon) and generates mobi file via kindlegen command. They have same spine/toc.

Please reopen if master branch (or future 1.6 release) still has this issue.
