### ISSUE TITLE
Higher levels of :maxdepth: is ignored in latexpdf output

### ISSUE THREAD

**Issue by pburdine** [sphinx-doc/sphinx#2547]
If creating a manual in PDF output, it defaults to a maximum depth of 3 for `{secnumdepth}`.  The writer should set this based on the `:maxdepth:` value in the main TOC.  In order to get more than 3 levels deep of numbering in Sphinx 1.4.1, you need to add a line similar to the following in the preamble:

`\setcounter{secnumdepth}{9}`

**Comment by tk0miya** [comment]
Since 1.4, LaTeX writer refers the `:maxdepth:` value from main TOC.
Could you check its behavior please?

**Comment by pburdine** [comment]
Yes, I have a main TOC defined as:

```
.. toctree::
    :maxdepth: 15
    :numbered:
    :caption: Table of Contents
    :name: mastertoc
```

Under that I can put the following:

```
===============
Heading 1
===============

***************
Heading 2 
***************

^^^^^^^^^^^^^^^
Heading 3
^^^^^^^^^^^^^^^

Heading 4
@@@@@@@@@

Heading 5
%%%%%%%%%
```

The above also works when nesting toctrees to more than 3 levels deep.

When done, only headings 1-3 have numbering.  See attached screen shot
![headings missing numbering](https://cloud.githubusercontent.com/assets/14918001/15292662/f977464e-1b38-11e6-9d59-5641e0f3d4cb.png)

**Comment by jfbu** [comment]
LaTeX standard classes report and article have no finer subdivision than subparagraph. In the case of your example, using `'manual'` in `latex_documents` , the Heading 5 is at paragraph level.

You can get it numbered in the TOC by setting `secnumdepth` counter to at least 4.

```
 \setcounter{secnumdepth}{4}
```

but it will not be numbered in the pdf due to the settings in `sphinx.sty`. You also need to add to preamble (this uses `titlesec` lingua, which is loaded by `sphinx.sty`).

``` latex
\makeatletter
\titleformat{\paragraph}{\small\py@HeaderFamily}%
            {\py@TitleColor\theparagraph}{0.5em}{\py@TitleColor}{\py@NormalColor}
\makeatother
```

You can then even add one more level which will use `subparagraph` at the latex end. This one is not even configured in `sphinx.sty` thus will be numbered in text naturally. However to get the same font you should imitate the above with `subparagraph` in place of `paragraph`, and 

```
 \setcounter{secnumdepth}{5}
```

All this can be added via `'preamble'` key of `latex_elements` in conf.py.

By the way I saw when testing that a `setcounter{tocdepth}{14}` is generated from LaTeX writer. This seems to originate in 

```
            self.elements['tocdepth'] = ('\\setcounter{tocdepth}{%d}' %
                                     (document['tocdepth'] + self.top_sectionlevel - 2))
```

It appears `document['tocdepth']` gives `15`,  and I don't how this 15 is generated. But anyhow for LaTeX setting the `tocdepth` to anything larger (strictly) than  `5` has no effect in standard classes, because it does not have finer division units than `subparagraph`.

**Comment by jfbu** [comment]
Oh, I had overlooked the

```
:maxdepth: 15
```

in your `.. toctree`.  This explains what I observed naturally copying pasting your code. As I said, in LaTeX it does not make sense to have the tocdepth larger than 5 (in general) but it does not hurt either.

**Comment by pburdine** [comment]
Ok, thank you for the explanation.  I already had figured the part about `\setcounter{secnumdepth}{x}`, but I didn't realize that that by default the level 5 heading (`paragraph`) wasn't numbered.  

I find it strange that be default, if `secnumdepth`is set to `6`, then the `subparagraph`has numbering turned on and is a larger font than a depth of `5`.

We are looking at converting some of our Word documentation to Sphinx, and we have documents that do go up to level 8 currently.  Being constrained to 6 levels of headings would make the transition difficult.  

It looks like the sectioning is determined by this list (`writers/latex.py`):

```
class LaTeXTranslator(nodes.NodeVisitor):
    sectionnames = ["part", "chapter", "section", "subsection",
                    "subsubsection", "paragraph", "subparagraph"]
```

It seems that this list could be redefined to allow people to apply their own mapping in an style (from `visit_title`):

```
            try:
                self.body.append(r'\%s%s{' % (self.sectionnames[self.sectionlevel], short))
            except IndexError:
                # just use "subparagraph", it's not numbered anyway
                self.body.append(r'\%s%s{' % (self.sectionnames[-1], short))
            self.context.append('}\n') 
```

Could `sectionnames`be an option in `latex_elements` so that end users have the ability to extend the number of levels they support?  This would allow users to configure a style file that would include something like this: http://tex.stackexchange.com/questions/60209/how-to-add-an-extra-level-of-sections-with-headings-below-subsubsection

This doesn't appear to be an issue to LaTeX, but rather the document class, which could be worked around with an sty file to extend the class.  I apologize if if the terminology I am using is wrong, I'm still fairly new to using LaTeX.

The current documentation (http://www.sphinx-doc.org/en/stable/rest.html) only states "limited", but does not provide a limit.  I think it should be updated to say LaTeX output only works up to 4 levels without doing something extra which makes it work up to 6.

> Of course, you are free to use your own marker characters (see the reST documentation), and use a deeper nesting level, but keep in mind that most target formats (HTML, LaTeX) have a limited supported nesting depth.

**Comment by jfbu** [comment]
> I find it strange that be default, if secnumdepthis set to 6, then the subparagraphhas numbering turned on and is a larger font than a depth of 5.

Yes, it appears that `sphinx.sty` is lacking the configuration for `subparagraph`.

Furthermore the `paragraph` configuration forces non-numbered paragraphs, even if `secnumdepth` is `4` or `5`. This looks wrong. I will make a PR, probably.

Note that `\titleformat` has a "`label`" argument, but it is displayed only if the value of `secnumdepth` is high enough for that sectioning unit.

> This doesn't appear to be an issue to LaTeX, but rather the document class

Yes, there is no limitation in LaTeX per se. But if you want to add levels you have to define some extrathings, as I guess is explained at  http://tex.stackexchange.com/questions/60209/how-to-add-an-extra-level-of-sections-with-headings-below-subsubsection. Ok I looked. Only the first answer explains that when adding a new level you should also define the `l@<sectioningunit>`  macros for the TOC.

For the appearance of the extra sub-headings in the body, you should imitate what `sphinx.sty` does using `\titleformat` from `titlesec.sty`.

**Comment by jfbu** [comment]
The `maxdepth` option to `toctree` directive affects LaTeX `tocdepth` counter, not `secnumdepth`. Unnumbered headings to not look very good in TOCs usually (with LaTeX defaults) thus if `maxdepth` is set to `4` or higher, then the user should use `'preamble'` key to set secnumdepth to `3`, `4` or `5` (for numbering subsubsection, paragraph, or subparagraph in the body of document).

**Comment by tk0miya** [comment]
Oh, sorry. I confused `secnumdepth` with `tocdepth`.
Indeed, Sphinx does not set `secnumdepth` automatically. It would be nice if `:maxdepth:` option affects to `secnumdepth` too.

BTW, I merged #2551 into stable now. So `paragraph` and `subparagraph` will be numbered.

**Comment by tk0miya** [comment]
Now, `:maxdepth:` option affects to `secnumdepth` automatically in master branch. It will be included in next major release (maybe in autumn).

BTW, sphinx now supports 8 sectioning units. You want to use all of them, set `latex_toplevel_sectioning = 'parts'` in your conf.py. Then, you can use `part` unit as a toplevel.

Thanks,

**Comment by nmat** [comment]
If this is going to be in 1.5 then might be good to add the 1.5 milestone on the issue? (just to keep track?)

**Comment by tk0miya** [comment]
This issue has some toipcs:
- paragraph and subparagraph could not have any section numbers (#2551, fixed in stable)
- `:maxdepth:` option affects `secnumdepth` (fixed in master branch)
- Sphnx supports only 8 sectioning units at most.

The last topic is not fixed yet. but I don't fix it and close this issue if nobody requests.

**Comment by tk0miya** [comment]
Now I close this.
Please reopen if you want to support over 8 sectioning units.

Thanks,
