### ISSUE TITLE
autodoc mock imports the entire module hierarchy when mock importing a submodule

### ISSUE THREAD

**Issue by cdwilson** [sphinx-doc/sphinx#2557]
I'm trying to mock the import of a platform specific submodule `app.plugin.win64`, but I would like to have autodoc generate documentation for `app` and `app.plugin` parent modules.

`conf.py`:

``` python
autodoc_mock_imports = ['app.plugin.amd64']
```

`autodoc.py` appears to recursively walk up the module hierarchy generating mock objects until there is a mock object for each node in the hierarchy:

``` python
def mock_import(modname):
    if '.' in modname:
        pkg, _n, mods = modname.rpartition('.')
        mock_import(pkg)
    mod = _MockModule()
    sys.modules[modname] = mod
    return mod
```

This generates:

``` python
sys.modules['app'] = _MockModule()
sys.modules['app.plugin'] = _MockModule()
sys.modules['app.plugin.win64'] = _MockModule()
```

autodoc automatically generates mock objects for `app` and `app.plugin` modules, even though I didn't specify them in the `autodoc_mock_imports` configuration option.

Is it possible to mock a submodule without autodoc mocking each parent node in the module hierarchy?

**Comment by lubo** [comment]
Hi, I came across the same problem. Any update ?

**Comment by offlinemark** [comment]
+1

**Comment by tk0miya** [comment]
@shimizukawa is this resolved with #2961?

**Comment by shimizukawa** [comment]
In order to mock `a.b`, you need to also mock `a`. This is explained in [PEP 302](https://www.python.org/dev/peps/pep-0302/):

> The Importer Protocol operates at this level of individual imports. By the time an importer gets a request for "spam.ham", module "spam" has already been imported.

This was discussed at https://github.com/sphinx-doc/sphinx/pull/2961#discussion_r111751899

@rjarry do you have any opinion for this issue?

**Comment by rjarry** [comment]
Hi all,

@cdwilson unfortunately that is not possible, due to what @shimizukawa said.

Why do you need to mock one of your own modules?

I feel like there could be another saner solution.

**Comment by cdwilson** [comment]
Hi @rjarry 

At the time I filed this issue last year, I was working on a python package (https://pypi.python.org/pypi/aardvark-py/5.15.2) with embedded shared library objects from a 3rd party vendor (https://www.totalphase.com/products/aardvark-software-api/).  

Here's the package layout:

```
├── aardvark_py
│   ├── __init__.py <-- This is the high level Python API
│   └── aardvark
│       ├── __init__.py <-- This detects the OS and imports the OS dependent module
│       ├── darwin
│       │   ├── __init__.py <-- This detects 32bit vs. 64bit and imports the arch dependent module
│       │   ├── arch32
│       │   │   ├── __init__.py <-- this simply does "from aardvark import *"
│       │   │   └── aardvark.so <-- pre-compiled shared library from 3rd party (Total Phase)
│       │   └── arch64
│       │       ├── __init__.py
│       │       └── aardvark.so
│       ├── linux
│       │   ├── __init__.py
│       │   ├── arch32
│       │   │   ├── __init__.py
│       │   │   └── aardvark.so
│       │   └── arch64
│       │       ├── __init__.py
│       │       └── aardvark.so
│       └── windows
│           ├── __init__.py
│           ├── arch32
│           │   ├── __init__.py
│           │   └── aardvark.pyd
│           └── arch64
│               ├── __init__.py
│               └── aardvark.pyd
```

I wanted to have autodoc extract documentation from the docstrings embedded in all the `__init__.py` files in the package.  However, since autodoc imports all the modules in the hierarchy, this always fails because the build machine can't import shared libraries built for other OS/arch.  

To get around this issue, I thought I could use `autodoc_mock_imports` to simply mock the shared library files (since they don't have any docstrings anyways):
```
autodoc_mock_imports = [
    'aardvark_py.aardvark.darwin.arch32.aardvark',
    'aardvark_py.aardvark.darwin.arch64.aardvark',
    'aardvark_py.aardvark.linux.arch32.aardvark',
    'aardvark_py.aardvark.linux.arch64.aardvark',
    'aardvark_py.aardvark.windows.arch32.aardvark',
    'aardvark_py.aardvark.windows.arch64.aardvark',
]
````

However, as my original post mentioned, this generated unwanted mock objects for:
```
aardvark_py
aardvark_py.aardvark
aardvark_py.aardvark.darwin
aardvark_py.aardvark.darwin.arch32
```
when I only wanted a mock object for:
```
aardvark_py.aardvark.darwin.arch32.aardvark
```

At the time, I just needed to get something simple running quickly, so instead I just told `sphinx-apidoc` to exclude all the platform dependent modules completely:

```
sphinx-apidoc -T -f -o docs/apidoc/ aardvark_py/ aardvark_py/aardvark/{darwin,linux,windows}
```

I'm no python expert, so I may have been trying to use `autodoc_mock_imports` in a way it was never intended to be used...

**Comment by rjarry** [comment]
@cdwilson, I understand your problem a little better. That is a tough one...

However I don't see any better workaround than the one you found.

autodoc_mock_imports is mainly intended to allow building autodoc of modules without requiring that the third-party libs they import are available.

**Comment by tk0miya** [comment]
In #2961, we improve `autodoc_mock_imports` and mock on demand.
So I think this is already fixed at HEAD of master branch.
Could you try this please?

**Comment by cdwilson** [comment]
@tk0miya I don't think #2961 fixes this issue.  Based on the feedback from @rjarry it sounds like `autodoc_mock_imports` will automatically mock everything it finds between the module explicitly  specified and the root of the module hierarchy.  There appears to be no way to tell autodoc to stop this behavior, which is not always wanted...  It would be nice if there was a way to tell `autodoc_mock_imports` to only mock the modules explicitly listed in the autodoc `conf.py` file.

**Comment by MakersF** [comment]
I second this issue.

At work we use python namespaces for all the libraries.

I'm writing library `A` which depend on library `B`. They are both in `company` namespace.

If I put `autodoc_mock_imports = ['company.B']` autodoc ignores everything from my `company.A` library.
Documentation is generated in an environment I don't have the control of, so I can't install the package I need.

The problem I see is at https://github.com/sphinx-doc/sphinx/blob/master/sphinx/ext/autodoc/importer.py#L105, where it only checks for the root package.

**Comment by rjarry** [comment]
Hi @MakersF,

this is due to what @shimizukawa said in https://github.com/sphinx-doc/sphinx/issues/2557#issuecomment-298169690:
> In order to mock a.b, you need to also mock a. This is explained in [PEP 302](https://www.python.org/dev/peps/pep-0302/):
>> The Importer Protocol operates at this level of individual imports. By the time an importer gets a request for "spam.ham", module "spam" has already been imported.

Unfortunately, there is no other solution. I don't understand why you need to mock your own sub-modules. Aren't they in the same source tree? If not, it would be a good thing to put them in separate root packages (modules). Mocking namespace packages (see [PEP 402](https://www.python.org/dev/peps/pep-0420/)) is not supported by autodoc.

**Comment by rjarry** [comment]
@MakersF,

Maybe you can trick mock import by adding this in your `conf.py` file:

```python
import company.A
```

That way, this module will not be mocked since it is already in `sys.modules`.

This obviously works only if `company.A` does NOT depend on `company.B`.

**Comment by tk0miya** [comment]
>In order to mock a.b, you need to also mock a. This is explained in PEP 302:
>>The Importer Protocol operates at this level of individual imports. By the time an importer gets a request for "spam.ham", module "spam" has already been imported.

@shimizukawa Why do we need to mock `a` module? PEP 302 only says `spam` module is **imported** before `spam.ham` is imported. It does not mention to **mock**.

I feel mocking `a.b` module and its descendants is very simple. Is there any reason to mock ancestor modules?

**Comment by rjarry** [comment]
@tk0miya maybe we can "try" to import it before mocking it. If it fails with an ImportError, we mock it, otherwise we get the normal module.

Here is an example:

```diff
diff --git a/sphinx/ext/autodoc/importer.py b/sphinx/ext/autodoc/importer.py
index 101cb930f4e6..3b5d9f8d4dd0 100644
--- a/sphinx/ext/autodoc/importer.py
+++ b/sphinx/ext/autodoc/importer.py
@@ -13,6 +13,7 @@ import sys
 import warnings
 import traceback
 import contextlib
+import importlib
 from collections import namedtuple
 from types import FunctionType, MethodType, ModuleType
 
@@ -117,10 +118,13 @@ class _MockImporter(object):
             # module has already been imported, return it
             return sys.modules[name]
         else:
-            logger.debug('[autodoc] adding a mock module %s!', name)
-            module = _MockModule(name, self)
-            sys.modules[name] = module
-            self.mocked_modules.append(name)
+            try:
+                module = importlib.import_module(name)
+            except ImportError:
+                logger.debug('[autodoc] adding a mock module %s!', name)
+                module = _MockModule(name, self)
+                sys.modules[name] = module
+                self.mocked_modules.append(name)
             return module
```

**Comment by tk0miya** [comment]
I'd like to know why `MockImporter` mocks `a` module. The instruction from user is mocking `a.b`, not `a`. So I feel raising ImportError is much simple and understandable if importing `a` failed.
If user want to mock whole of `a` module, `a` should be used for `autodoc_mock_imports`.

With current implementation, giving `a.b` is almost same as `a`. I know we can import specific modules before mocking like `import company.A` as you said. But the behavior is hard to understand to users.

So please let me know why `MockImporter` mocks the ancestors of `autodoc_mock_imports` modules.

**Comment by rjarry** [comment]
I believe that the whole idea was to have similar behavior with the older implementation of `autodoc_mock_imports` (mocking ancestors was here before #2961).

I agree that it would be better not to do this but it may surprise existing users. I can submit a PR with a change that only mocks the specified modules (not their ancestors) if that suits you. We need to warn people about this in release notes.

**Comment by MakersF** [comment]
In my case it was a namespace module, but I do age with Takeshi that the
current behavior is surprising: at the moment mocking 'a' and 'a.b' are the
same, while the user is clearly stating something different (s/he is when
typing more to specify the full name of the module to mock).

I would personally opt for only mocking 'a.b' (and maybe descending
modules, but that might be tricky) if that's what the user typed, and fail
if 'a' is not importable. In that case the user can always define 'a' in
the list.

I would not use the mock as a silent (as it doesn't error out) fallback as
that might produce different results based on the environment in which the
documentation is generated, but i guess both solution address the problem
and it's a matter of preferences.

I'm wondering if the change can be made in a backward compatible way
though..

Thanks for the effort you out on the issue Robin!

Il 11 gen 2018 16:45, "Robin Jarry" <notifications@github.com> ha scritto:

I believe that the whole idea was to have similar behavior with the older
implementation of autodoc_mock_imports.

In any case, if importing a.b, a will be imported first. So if the user
puts autodoc_mock_imports = ['a.b'] and 'a' is not importable, the build
will fail.

I agree that's a less intrusive behavior but it may surprise existing
users. I can submit a PR with a fix if that suits you.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/sphinx-doc/sphinx/issues/2557#issuecomment-356987633>,
or mute the thread

**Comment by tk0miya** [comment]
@rjarry Thank you for explanation and quick work. I understand. Surely, old mock code had also mocked ancestors.
I believe new behavior is much simple and easy to understand.
Of course we need to add some option to support old behavior to keep compatibility for a while.
@shimizukawa what do you think?

**Comment by shimizukawa** [comment]
I reconsidered the behavior of mock. Ignoring compatibility with previous Sphinx, I think that it is better to match the behavior of mock to `unittest.mock`.
Certainly PEP-302 says "Parents are imported", but that is not the basis for mocking parents.

Then, I +1 to the new behavior.

**Comment by tk0miya** [comment]
@shimizukawa Thank you for comment. I'll go to change the behavior with @rjarry 's help :-) (see #4413)
