### ISSUE TITLE
If a role content is empty, it's never called? - How can I show a warning "empty role on line 12"?

### ISSUE THREAD

**Issue by lakhman** [sphinx-doc/sphinx#2562]
Say I have the following role which converts an icon role into an inline font awesome icon:

``` python
# e.g: Create an inline <span class="fa fa-rocket fa-2x"></span>
def icon_role(role, rawtext, text, lineno, inliner, options={}, content=[]):
    options.update({'classes': ["fa-" + x for x in text.split(",")]})
    options['classes'].append('fa')
    set_classes(options)
    node = nodes.inline(**options)
    return [node], []

# ... add it

app.add_role('icon', icon_role)
```

``` rest
# Now I use it like so:
:icon:`rocket,2x`

#= <span class="fa fa-rocket"></span>
```
## Issue

``` rest
# Now say I forget to pass through some text or empty space
# (accidently deleted, forget I had it, etc..)
:icon:``    # No text
:icon:` `   # Space empty text

#= :icon:``
#= :icon:` `

# Notice how it just outputs the role raw, it doesn't seem to even call `icon_role`
# so I don't have a chance to check the value (and throw a warning)
```

If the content with backticks is empty, I would like to decide what to do with the role (output a empty node, throw a warning, place a default icon).

Am I missing something?

The `:download:` role does this, but I'm finding it confusing as to who it's implemented. It throws the following error if you pass an empty string.

``` rest
# Throws an error: WARNING: Inline literal start-string without end-string.
:download:``

# Just outputs the raw role text (I don't have a chance to do anything)
:icon:``
```

Any Ideas? 💭

**Comment by tk0miya** [comment]
Maybe, we can't handle that. The warning message of `:download:` is come from docutils; the parser of reST.
http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#interpreted-text

I am sorry that I couldn't be of any help to you.

**Comment by lakhman** [comment]
Thanks for replying, I've sent out an email to the [docutils mailing list](http://docutils.sourceforge.net/docs/user/mailing-lists.html#docutils-users), I'll see what they say and reply back.

If any one else has any ideas, please comment.

**Comment by lakhman** [comment]
I haven't heard back from this, I looked into it and modifying the core is quite a pain, I'm closing this issue as it's not really an issue.

Thanks for your reply.
