### ISSUE TITLE
Sphinx autosummary creates long lines instead of wrapping text

### ISSUE THREAD

**Issue by jat255** [sphinx-doc/sphinx#2565]
When using the autosummary extension, there is a problem with the resulting output if the short function description is longer than just a few words. See here for an example from one of my packages:

![image](https://cloud.githubusercontent.com/assets/1278301/15445922/e52f7f8a-1eda-11e6-9c04-78d7a3bbfff6.png)

This isn't so much a problem when building web documentation, since there is a scroll bar, but it is a serious problem when generarting latex pdf output, since the lines run off the page and become unreadable:

![image](https://cloud.githubusercontent.com/assets/1278301/15445931/151070f6-1edb-11e6-9d42-cae949db7310.png)

Arguably, my short function descriptions should probably be shorter, but I think it would be useful if the autogenerated documentation here knew to put in line breaks when necessary. Otherwise the function descriptions are limited to fewer than about 8 words or so to fit on a line.

**Comment by tk0miya** [comment]
In my short investigation:

In LaTeX, apidoc generates tables as longtable having following table spec:

```
\begin{longtable}{ll}
```

So all texts cannot break lines in the table.

It will be fixed by using `{p{0.5\linewidth}p{0.5\linewidth}` to the table spec.

**Comment by tk0miya** [comment]
Fixed at 4c2d679.
Thank you for reporting!

**Comment by jat255** [comment]
Great, thanks for the quick fix!
