### ISSUE TITLE
some latex default_elements note accessible

### ISSUE THREAD

**Issue by andreacassioli** [sphinx-doc/sphinx#2566]
Looking at the source code it seems `default_elements` options for `latex` are many more than those documented and actually accessible.

I have tried to set `contentsname` but nothing happen. It seems to me that values in `latex_elements` in `conf.py` are processed in a way some values are discarded or ignored.

Is this on purpose?

**Comment by tk0miya** [comment]
I think no special reason for that.
But, IMO, providing many customizable points makes LaTeX writer complicated.
It will increase maintenance cost.

In case of `contentsname`, Sphinx allows to set `contentsname` through `:caption:` option of toctree directive.
Are there any reason not to use it or to override forcely?

**Comment by andreacassioli** [comment]
Hi @tk0miya ,

thank you as usual for your help. To be honest I have not realised that content could be override by the toctree caption. 

I understand that to many options make things complicated, but it is also not clear how to customize more the output. I know I can use the preamble, but it is not clear what could conflict with Sphinx generated code.

**Comment by tk0miya** [comment]
I agree with you. It's not easy and clear. I would like to improve latex writer and its documents.
Please tell me your ideas, issues and so on.

Thank you always.
