### ISSUE TITLE
Makefile: 12: *** recipe commences before first target.  Stop.

### ISSUE THREAD

**Issue by voetsjoeba** [sphinx-doc/sphinx#2568]
The autogenerated Makefile produced by `sphinx-quickstart` contains a syntax error that manifests when the check for the SPHINXBUILD command fails. Verified w/GNU make versions 3.82 and 4.0 on resp. CentOS and Ubuntu 14.04.

To reproduce (on a system that does not yet have sphinx installed):

```
vmuser@vm:~/sphinx$ sphinx-build
sphinx-build: command not found
vmuser@vm:~/sphinx$ virtualenv ~/py2env
vmuser@vm:~/sphinx$ (. ~/py2env/bin/activate; pip install -U sphinx)
vmuser@vm:~/sphinx$ (. ~/py2env/bin/activate; sphinx-quickstart )
# specify 'doc' as directory, answer 'y' to '> Create Makefile? (y/n)'
vmuser@vm:~/sphinx$ cd doc/
vmuser@vm:~/sphinx/doc$ make html
Makefile:12: *** recipe commences before first target.  Stop.
```

The problem happens because of the tab character used to indent the `$(error ...)` line:

``` Makefile
ifeq ($(shell which $(SPHINXBUILD) >/dev/null 2>&1; echo $$?), 1)
    $(error The '$(SPHINXBUILD)' command was not found. Make sure you have Sphinx installed, etc.)
endif
```

The tab character is the prefix for recipe lines, so make assumes that this line is part of a recipe. It's complaining that no recipe was started for this line to be a part of.

The error only manifests when the SPHINXBUILD command is missing, because these `ifeq`/`endif` blocks are evaluated statically in a separate pass prior to interpretation of the Makefile, much like a C-style preprocessor `#if`/`#endif` pair.

Removing the tab character resolves the issue.

**Comment by tk0miya** [comment]
The warning will be removed in next stable release.
More details, see #2521 .

Thank you for reporting.

**Comment by voetsjoeba** [comment]
Thx, sorry for the dup.
