### ISSUE TITLE
Sphinx does not produce signature of python functions and methods

### ISSUE THREAD

**Issue by ghost** [sphinx-doc/sphinx#2571]
## Problem: Strange Sphinx Autodoc Warnings

When I built the documentation from my Python code using the **sphinx** extensions **autodoc** and **napoleon**, I always found the doc _without the signature of functions, methods_.
Simultaneously, sphinx gave me a strange warning for each of my python code structures. 

```
WARNING: error while formatting arguments for <a code obj here>: 
'code' object has no attribute 'co_kwonlyargcount'
```

But: **build succeeded, 369 warnings** .

Unable to find a solution for this warning, I connected the python debugger to a fresh git clone of the sphinx project. 
It showed that the warning was created from an exception, that has been thrown in the function **autodoc.formatargspecs**. The later calls `typing.get_type_hints`, that again `typing._get_defaults` with the highly suspect line:
`kw_count = code.co_kwonlyargcount`.

[Stacktrace in Pycharm](http://i.stack.imgur.com/0zo23.png)
## Solution: try-excepting the erroneous code:

So i tried to fix the issue by quick and dirty _try-except-clause_:

From:

```
introspected_hints = (typing.get_type_hints(function)
                          if typing and hasattr(function, '__code__')`
```

to:

```
try:
   introspected_hints = (typing.get_type_hints(function)
                             if typing and hasattr(function, '__code__')
except AttributeError:
   introspected_hints = {}
```

Indeed, the quick fix solved both problems: no more Warnings were created and further the documentation shows the right (!) signature of my functions.

The issue may be a problem in the sphinx code (together with typing?) or one that existed only for me.

**Comment by tk0miya** [comment]
Thank you for reporting.

Now, Sphinx on py27 ignores the `typing` package.
More detail, see 20b3da5cf6aa4917301b2db2259bc78c3e20a122.

Thanks,
