### ISSUE TITLE
Why does sphinx replace underscores w/ hyphens in page anchors?

### ISSUE THREAD

**Issue by gordonje** [sphinx-doc/sphinx#2574]

**Comment by andreacassioli** [comment]
That is a good question I asked my self as well...

**Comment by tk0miya** [comment]
It is a rule of docutils; the core library of Sphinx. It normalizes underscores to hyphens.

More details, please refer the comment of `make_id()`:
http://docutils.sourceforge.net/docutils/nodes.py

**Comment by lehmannro** [comment]
Please note this issue tracker is used for discussing defects and improvements to Sphinx;  general development questions are better suited to the [sphinx-dev](https://groups.google.com/d/forum/sphinx-dev) or [sphinx-users](https://groups.google.com/d/forum/sphinx-users) mailing list.

There are several reasons to generally use hyphens over underscores in URLs, see [_Why are dashes preferred?_ on StackOverflow](http://stackoverflow.com/questions/7560813/why-are-dashes-preferred-for-css-selectors-html-attributes).

**Comment by gordonje** [comment]
Thanks for the prompt responses. @tk0miya, you def pointed me at what I was looking for.
