### ISSUE TITLE
Intersphinx causes exception on appending auth handler

### ISSUE THREAD

**Issue by ipiqueras** [sphinx-doc/sphinx#2578]
A simple uri with username and password causes interphinx to generate an exception when calling to urllib2.build_opener:

In `conf.py`:

``` python
intersphinx_mapping = {'mydoc': ('http://ipiq:pass@example.com', None)}
```

Provokes:

WARNING: intersphinx inventory 'http://ipiq:pass@example.com/objects.inv' not fetchable due to &lt;type 'exceptions.TypeError'&gt;: expected BaseHandler instance, got &lt;type 'list'&gt;

Seems to be a problem of packing arguments before calling to `urllib2.build_opener`. 
I changed `_read_from_url` from:

``` python
opener = request.build_opener(default_handlers + [handler])
```

to:

``` python
handlers = default_handlers + [handler]
opener = request.build_opener(*handlers)
```

to make it work for me...

**Comment by tk0miya** [comment]
This problem is already fixed at #2398.
It will be released soon. Please wait next version.

Thank you for reporting.
