### ISSUE TITLE
LaTeX writer inserts extra space before `\footnote` in produced latex code 

### ISSUE THREAD

**Issue by jfbu** [sphinx-doc/sphinx#2582]
With this

``` rst
TEST
----

hello [#]_

.. [#] test

X_ 

.. _X: http://example.com/

```

in index.rst and `latex_show_urls = 'footnote'` in conf.py one gets

``` latex
hello \footnote[1]{\sphinxAtStartFootnote%
test
}

\href{http://example.com/}{X}\footnote[2]{\sphinxAtStartFootnote%
http://example.com/
}
```

in produced latex file. The first `\footnote` has a space before it, contrarily to the second one, which was automatically generated.

I think second is the correct one, and first footnote should look like `hello\footnote...` not `hello \footnote`.

**Comment by tk0miya** [comment]
This is not a bug. it is specification of reStructured Text.
It comes from the space between `hello` and `[#]_`, not generated by Sphinx.

You can remove it in several ways:

(1) Escaping spaces manually: use `\` (escaped space) to separator of footnote marks:

```
hello\ [#]_
```

(2) Use `trim_footnote_reference_space` option in your conf.py:
More details, please refer http://docutils.sourceforge.net/docs/user/config.html#trim-footnote-reference-space

**Comment by jfbu** [comment]
@tk0miya thanks I should have checked docutils documentation first. Your hints solve my problem. I close now.
