### ISSUE TITLE
Latexpdf and miktex creates no contents tree and blank pages

### ISSUE THREAD

**Issue by nmat** [sphinx-doc/sphinx#2594]
When generating the latexpdf using miktex the contents page is empty.

Also before and after the content page there is 1 respectively 2 empty pages.

Miktex version: pdfTeX, Version 3.14159265-2.6-1.40.16 (MiKTeX 2.9)
Sphinx: 1.4.2

It does however tell me that it is running: sphinx-build -b latex -d _build/doctrees   . _build/latex

**Comment by tk0miya** [comment]
Sphinx uses `openright` document-class option in LaTeX by default. It specifies all chapters begin on a right-hand page.

If you want to switch the behavior, please give `openany` to `extraclassoptions` option.

```
latex_elements = {
    'extraclassoptions': 'openany'
}
```

Thanks,

**Comment by nmat** [comment]
Maybe this should be added to the quickstart conf.py then for easier getting started with latex?

I have not tested it yet. Will have to test it when I get home.

**Comment by nmat** [comment]
Hello again,

I did try to set this and run latexpdf on my windows 10 machine but "table of contents" is still not generated.

**Comment by tk0miya** [comment]
Oh, sorry. I've misread the problem. I'll take a look later.

**Comment by nmat** [comment]
I tested it a bit more now.

The build of the pdf failed. Now what I did is the below:
1. Clean build (the build fails on the tabular problems in #2593 
2. Running: `make latexpdf` a second time creates the table of contents

Whats note worthy is that.

On first run the latexpdf creates 2 blank pages and 2 table of contents pages.

1 blank page is after the first page.

2nd blank page is after the 1 st table of contents.

After that blank page......the second table of contents page is created. Really strange.

**Comment by AlexEshoo** [comment]
An artefact of LaTeX is that you need to run at least twice to get all those references correct in the pdf. That is why the table of contents is not building properly on the first go. the Makefile should be edited in a way to assure that pdflatex is invoked at least twice to build it correctly automatically.

Also I am experiencing the same issue on both windows and debian

**Comment by tk0miya** [comment]
@nmat Could you add `openany` option? It would remove empty pages you said.
BTW, did you see two table of contents in PDF? It's strange for me. Could you show me your document?

@alenz33 At this moment, sphinx invokes `pdflatex` multiple times by default. So you do not need to edit the Makefile.

**Comment by AlexEshoo** [comment]
What is the control sequence that causes `pdflatex` to be run multiple times? When I run `make latexpdf` command I only see `pdflatex` run once and I am missing my table of contents afterward.

**Comment by nmat** [comment]
openany did not remove the empty pages.IMO I believe this is a problem of multiple things.
1. The tabulary issue
2. The generating of table of contents when first fails due to tabulary issue

So in this case it would be best to test it when tabulary issue is fixed to try and get no errors from that first.

**Comment by jfbu** [comment]
@alenz33 have you tried doing `make latex` and then go to build repertory and manually issue `pdflatex`?  perhaps `pdflatex` fails with an error, then `make latexpdf` would indeed do only one compilation.

**Comment by jfbu** [comment]
@AlexEshoo see previous comment.

@alenz33 sorry for pinging you by error on this.

**Comment by nmat** [comment]
I now ran this so that there are no errors in the document.

Now the table of content is generated.

2 blank pages + one more page named Contents: is still being created though.

This is a test of completely removing the whole latex/ build directory. So the document is built from scratch completely.

**Comment by AlexEshoo** [comment]
@jfbu I am getting an error on build `make: *** [foo.pdf] Error 1` but then it says build finished and there is a PDF output. Theres a few latex package warnings throughout could these, but should those affect this error?

Edit:

I found the source of the error code, I had some problems with the syntax in my custom preamble that caused pdflatex to exit with a nonzero error code. Now that it is resolved `make latexpdf` functions as expected. Thanks for your help

**Comment by jfbu** [comment]
@AlexEshoo good to know ;-)

**Comment by tk0miya** [comment]
I just released sphinx-1.4.3. It includes the fix for figures in table.
Could you try this again please?

I think this problem comes from crash of LaTeX. so it might be resolved in newest release.

**Comment by nmat** [comment]
I tested it and works fine. I can verify it here.

@jfbu could you maybe do a double check before I close the ticket?

**Comment by nmat** [comment]
@tk0miya should I open a different ticket for the blank pages?

**Comment by tk0miya** [comment]
@nmat Yes, please!

**Comment by jfbu** [comment]
@nmat I think you can close this ticket if your problem is solved. I have no access to a Windows environment, hence to MikTeX. Blank table of contents is sign first LaTeX run failed and make rule stopped. The .toc file is written when LaTeX reaches end of document, if something gets wrong before it may not be written and next run even if done manually will have blank table of contents.

**Comment by nmat** [comment]
Closing issue and creating a blank pages issue instead. Thanks @tk0miya and @jfbu
