### ISSUE TITLE
Warnings not shown in colour

### ISSUE THREAD

**Issue by GadgetSteve** [sphinx-doc/sphinx#2597]
Attempting to add some graphviz processing to a project I was mystified that it didn't seem to be working - eventually I noticed that I had the warning: 

> WARNING: dot command 'dot' cannot be run (needed for graphviz output), check the graphviz_dot setting

But it was lost even though I had colour output:
![screenshot](https://cloud.githubusercontent.com/assets/5593690/15640833/08bef0ec-2634-11e6-9404-9a63b265b505.png)

Please consider at least colour coding, when colour output is available, warnings both in place and in the summary line.

**Comment by nmat** [comment]
Coloring output is not something that is built in to sphinx I believe. Instead this is part of colormake and bash shell options.

Standard make only gives standard coloring. AFAIK I would not consider this a bug on sphinx end.

**Comment by GadgetSteve** [comment]
@nmat : I would consider this more of a feature request - I am sure that there is a way to get colour make to highlight warnings - I'll do some digging.

**Comment by nmat** [comment]
Yes you can. But it is different on different systems. So yes in this case then it would be considered a feature request rather than a bug. But as mentioned there are packages for make to color the output and to set the prompt to do it based on rules.

It is the developers choice.

**Comment by GadgetSteve** [comment]
@nmat : There is colour inserted (conditionally) to messages in both cmdline.py and quickstart.py the warning messages are currently output in application.py by the method _log which has a standard destination of self._warning which defaults to stderr a similar check to those in cmdline to ensure that the output is going to a colour compatible device could conditionally colour warnings in a device independent manner.

**Comment by tk0miya** [comment]
PR#2599 is merged now. It makes warnings as red.
Thank you for proposal.
