### ISSUE TITLE
latexpdf figure numbering "0.1", "0.2" "0.3" when using "howto" documentclass

### ISSUE THREAD

**Issue by gm6** [sphinx-doc/sphinx#2598]
Hi,
How to change the figure numbering from "0.1", "0.2" "0.3" ... to "1", "2" "3" ...
Any idea? Thank you!

**Comment by tk0miya** [comment]
Really? In my environment, I can't reproduce that. Could you share your project or small examples?

**Comment by gm6** [comment]
Hi, I should mention that I am using Jinja2-2.8 MarkupSafe-0.23 Pygments-2.1.3 docutils-0.12 sphinx-1.2.3, since I am testing https://github.com/jterrace/sphinxtr. It doesn't work with Sphinx 1.3.x or newer versions. Any suggestions?

**Comment by tk0miya** [comment]
I try to reproduce using bare sphinx-1.2.3. But it works fine.
It seems this is not a bug of Sphinx, and might be a bug of sphinxtr.

**Comment by gm6** [comment]
Thank you for your time! I agree. I'll dig the "sphinxtr" deeper later :)

**Comment by tk0miya** [comment]
Now I close this once.
Please reopen if you get more information.

Thank you for reporting.
