### ISSUE TITLE
Enhancement: Add Graphviz option to specify image filename for diagram

### ISSUE THREAD

**Issue by GadgetSteve** [sphinx-doc/sphinx#2600]
Currently the graphviz extension names the output file using the rule:

```
hashkey = (code + str(options) + str(graphviz_dot) +
           str(self.builder.config.graphviz_dot_args)).encode('utf-8')

fname = '%s-%s.%s' % (prefix, sha1(hashkey).hexdigest(), format)
```

Which is fine for avoiding possible clashes of names but results in image files with names such as: graphviz-88cfa414d22dd3242c19a9cb35b8312723e8386c.svg which is not very user friendly.  

It would be nice to have a graphviz_name option within the diagram tag to specify the desired output name of a given diagram.

**Comment by tk0miya** [comment]
Sphinx uses the filename as cache key also. It enables to regenerate the image only if diagram or options are changed on incremental updates.
So renaming the generated image is not good to me.
