### ISSUE TITLE
autodoc type links broken for Python builtins

### ISSUE THREAD

**Issue by jantman** [sphinx-doc/sphinx#2602]
I can't be exactly sure if this is the fault of Sphinx or Python itself, but if the latter, then either Sphinx needs changes or documentation examples.

I have quite a number of projects that make use of autodoc to process docstrings like the following:

```
def foo(bar):
    """
    Do something

    :param bar: my variable
    :type bar: list
    """
```

As of May 21st, this was working correctly, though it would link `list` to the [function reference](https://docs.python.org/library/functions.html#list). However, as of today, these automatic links to python builtins (i.e. `:type varname: <list|str|...>`) are failing. I can confirm on one of my projects that hasn't had any code changes at all that the build [worked on May 21st](https://travis-ci.org/jantman/awslimitchecker/jobs/131914533) and [failed when re-run automatically on May 27th](https://travis-ci.org/jantman/awslimitchecker/jobs/133296992). I first discovered this issue on a new, not-yet-released project, but it's happening on other [projects](https://travis-ci.org/jantman/vault-redirector-twisted/jobs/133297815) as well.

```
Warning, treated as error:

/home/travis/build/jantman/vault-redirector-twisted/docs/source/vault_redirector.redirector.rst:2: WARNING: broken link: https://docs.python.org/library/functions.html#str
```

I've been using the same `:type paramname: typename` syntax for years, according to the Sphinx examples. Any idea why this suddenly stopped working, and what the issue is?

**Comment by tk0miya** [comment]
`https://docs.python.org/objects.inv`; the inventory file which the project refers has been move to `https://docs.python.org/2/objects.inv`. But `sphinx.ext.intersphinx` does not recognize the redirection. Then, it generates hyperlinks starts with `https://docs.python.org/` instead of `https://docs.python.org/2/`.
So the hyperlinks has been broken.

It will be fixed after #2606 is applied.

As a workaround, please use `https://docs.python.org/2/` to `intersphinx_mapping` instead.

**Comment by jantman** [comment]
Cool, thanks soooooo much!!! I spent hours trying to trace down what the problem was, but I missed that.

**Comment by tk0miya** [comment]
Now #2606 is merged. It will be detect redirection automatically.

Thank you for reporting!

**Comment by jantman** [comment]
@tk0miya sorry for not responding sooner. Thank you SO much!!!
