### ISSUE TITLE
Artifacts when using include:: with orphaned file

### ISSUE THREAD

**Issue by barbara-sfx** [sphinx-doc/sphinx#2603]
## Details
- Project URL: private on rtd.com
- Build URL (if applicable):
- Read the Docs username (if applicable): 

I wanted to include a file in other files, without including the former in the toctree, so I put :orphan: at top of the file.
## Expected Result

The included file shows up as expected. 
## Actual Result

The included file shows up with:

   orphan:

at the top of the included text. Note single colon.
### Text file:

<img width="638" alt="screen shot 2016-05-23 at 9 31 07 am" src="https://cloud.githubusercontent.com/assets/17709550/15477444/796f15d0-20c9-11e6-9757-91cfe7e7fb46.png">
### As rendered:

<img width="594" alt="screen shot 2016-05-23 at 9 32 39 am" src="https://cloud.githubusercontent.com/assets/17709550/15477443/796b7678-20c9-11e6-8916-6a6e675a781d.png">

**Comment by tk0miya** [comment]
I think it is meaningless to mark the included document as orphaned.
Actually, it is not orphaned.
So I just made a new pull request #2605. It suppresses the warnings if the document is already included.

It will help this case.

**Comment by tk0miya** [comment]
I merged #2605. so you don't need to add orphaned mark to each included file.
So this issue was solved with other approach.

Now I close this. Please reopen if you still have any problems.

Thank you for reporting.
