### ISSUE TITLE
When excute "make html" to generate the full web page of "http://scikit-learn.org" pops up ERROR

### ISSUE THREAD

**Issue by yingwei13mei** [sphinx-doc/sphinx#2609]
I wanted to generate the full web page of "http://scikit-learn.org" under the guide of "scikit-learn-master\doc\README.md", there are the error message:
D:\scikit-learn-master\doc>make html
Running Sphinx v1.3.1

Exception occurred:
  File "D:\Anaconda3\lib\subprocess.py", line 1220, in _execute_child
    startupinfo)

> FileNotFoundError: [WinError 2] 系统找不到指定的文件。
> The full traceback has been saved in C:\Users\AAA\AppData\Local\Temp\sphinx-err-c4x44do0.log, if you want to report the issue to the developers.
> Please also report this if it was a user error, so that a better error message can be provided next time.
> A bug report can be filed in the tracker at https://github.com/sphinx-doc/sphinx/issues. Thanks!
> 
> Build finished. The HTML pages are in _build/html.

I opened up D:\Anaconda3\lib\subprocess.py found line 1220 was that winapi create process 

> ```
>        try:
>             hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
>                                      # no special security
>                                      None, None,
>                                      int(not close_fds),
>                                      creationflags,
>                                      env,
>                                      cwd,
>                                      startupinfo)
> ```

[sphinx-err-c4x44do0.txt](https://github.com/sphinx-doc/sphinx/files/293751/sphinx-err-c4x44do0.txt)

**Comment by tk0miya** [comment]
It seems the error comes from `github_link` extension in scikit-learn-master module.

```
  File "D:\scikit-learn-master\doc\sphinxext\github_link.py", line 82, in make_linkcode_resolve
    revision = _get_git_revision()
  File "D:\scikit-learn-master\doc\sphinxext\github_link.py", line 13, in _get_git_revision
    revision = subprocess.check_output(REVISION_CMD.split()).strip()
  File "D:\Anaconda3\lib\subprocess.py", line 629, in check_output
    **kwargs).stdout
  File "D:\Anaconda3\lib\subprocess.py", line 696, in run
    with Popen(*popenargs, **kwargs) as process:
  File "D:\Anaconda3\lib\subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "D:\Anaconda3\lib\subprocess.py", line 1220, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
```

It is not a part of sphinx. it might be made by scikit-learn project.
Could you ask about the error to scikit learn project please?

Thanks,

**Comment by yingwei13mei** [comment]
thanks a lot

**Comment by Chaitya62** [comment]
@yingwei13mei did you find the solution to this please let me know!

**Comment by tk0miya** [comment]
Note: This was filed to the scikit-learn project as https://github.com/scikit-learn/scikit-learn/issues/6860 .

**Comment by Chaitya62** [comment]
Thanks a lot ! Once again
