### ISSUE TITLE
Safari rendering issue

### ISSUE THREAD

**Issue by cholcombe973** [sphinx-doc/sphinx#2610]
Not sure if this is sphinx or just safari being weird.  This http://pythonhosted.org/ceph_api/ceph_api.html#ceph_api.ceph_command.MdsCommand.fs_set looks fine on firefox, chrome on linux but my friend says it looks very weird on Safari/macbook.  Here's a picture: [Safari pic](https://plus.google.com/photos/albums/pvkas10pdmg6ls6r2gsnorqq5b18tr76c?pid=6291355655087916658&oid=105169085652175712547)

**Comment by tk0miya** [comment]
It seems any permission is needed to see your picture. Could you make it public or upload here?

BTW, I looked the page using firefox, chrome and safari. But it seems almost same for me in all browsers.
Here is a picture of chrome:
![2016-06-02 10 48 51](https://cloud.githubusercontent.com/assets/748828/15731415/f1d5ed9e-28af-11e6-84e7-bea2abfbb550.png)

Are you saying the default value of `valid_range` argument overflows?

**Comment by cholcombe973** [comment]
Yeah that looks correct.  Yes I was referring to the valid_range overflowing.  :)  Sorry about the permissions.  I wasn't sure if that would share properly.  Here's the image:  
![screen shot 2016-06-01 at 6 32 35 pm](https://cloud.githubusercontent.com/assets/3058195/15745730/3de24bc4-2888-11e6-84a8-0e009ec769c6.png)

It appears to match your image.  On Linux firefox it looks like this:
![fs-set](https://cloud.githubusercontent.com/assets/3058195/15745806/97629cf8-2888-11e6-8eb3-28c492a68335.png)

This could be just a silly quirk of different browsers.  I'm not sure.

**Comment by tk0miya** [comment]
It might browsers could not find good line breaking point because the default value is built from consecutive characters. It will be folded automatically if there are any spaces in the value.

In this case, this problem comes from `sphinx.ext.autodoc`. It should add the spaces to the default value.

I will take a look later.

**Comment by tk0miya** [comment]
Finally, I found the cause of the error.
The docstring of `fs_set` has very long the definition of default value which has no spaces.
https://github.com/cholcombe973/ceph-api/blob/master/ceph_api/jewel/ceph_command.py#L775

Could you add some spaces here? It would be fixed.

**Comment by cholcombe973** [comment]
Sounds great!  Thanks for finding the root cause.  I'll see if I can get
yapf to break some of the lines up.  :)

**Comment by tk0miya** [comment]
Good to hear. Enjoy documentation :-)
