### ISSUE TITLE
Source signature key

### ISSUE THREAD

**Issue by kyrias** [sphinx-doc/sphinx#2612]
A list of keys that are allowed to sign source releases on PyPI should be listed on the website and preferably also in the repository.

Without the keys that are allowed to sign releases listed somewhere trusted signing sources is pointless since there is no way to verify that the key is correct.

**Comment by kyrias** [comment]
(Though, for them to be listed on the website to be of any significance, it would also have to have https support.)

**Comment by tk0miya** [comment]
Now sphinx-doc.org is hosted on readthedocs.org. It provides pages by plain HTTP.
So it is better to put pubkeys on the repository in our project.

But I don't know way to open to the public my key on repository.
Do you know any examples on other projects?
I would appreciate it if you could give advice for me.

Thanks,

**Comment by kyrias** [comment]
https://github.com/SirCmpwn/sway is one example

**Comment by tk0miya** [comment]
Thank you for letting me know.
I updated our README.

Thanks,
