### ISSUE TITLE
PicklingError: Can't pickle class `docutils.parsers.rst.directives.html.meta` attribute lookup failed

### ISSUE THREAD

**Issue by lakhman** [sphinx-doc/sphinx#2625]
When I use the meta directive, on my home page (index.rst) it works fine, but when I use it in a document I get the following error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 244, in main
    app.build(opts.force_all, filenames)
  File "/usr/local/lib/python2.7/site-packages/sphinx/application.py", line 294, in build
    self.builder.build_update()
  File "/usr/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "/usr/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 284, in build
    self.env.topickle(path.join(self.doctreedir, ENV_PICKLE_FILENAME))
  File "/usr/local/lib/python2.7/site-packages/sphinx/environment.py", line 137, in topickle
    pickle.dump(self, picklefile, pickle.HIGHEST_PROTOCOL)
PicklingError: Can't pickle <class 'docutils.parsers.rst.directives.html.meta'>: attribute lookup docutils.parsers.rst.directives.html.meta failed
```

This is what I'm including at the top of my rst fle.

``` rest
.. meta::
   :keywords: plaintext, markup language
```

I use it in my template like so:

``` jinja
{% if metatags -%}
    {{ metatags }}
{%- else -%}
    <meta content="Description!" name="description">
{%- endif %}
```

From my understanding, it can't serialize something, any ideas how to debug this or trace it down?

I think it's down to this extension i'm using (i removed all them and added one by one), I think this causes the issue.

```
ablog (0.8.3) from /usr/local/lib/python2.7/site-packages/ablog/__init__.pyc
```

> https://github.com/abakan/ablog/tree/master/ablog

Any ideas on an easy fix? I suspect the ablog package is missing a function to help serialize something?

I set a breakpoint and listed everything inside `self.config`.

```
_raw_config = {dict} {'spelling_show_suggestions': True, 'ablog': <module 'ablog' from '/usr/local/lib/python2.7/site-packages/ablog/__init__.pyc'>, 'html_sidebars': {'**': ['postcard.html', 'recentposts.html', 'tagcloud.html', 'categories.html', 'archives.html']}, 'pygments_s
actdiag_html_image_format = {str} 'svg'
api_url = {str} 'http://api.symfony.com/master/%s'
blockdiag_fontpath = {str} '/Users/anillakhman/Library/Fonts/GoogleFonts/roboto/Roboto-Black.ttf'
blockdiag_html_image_format = {str} 'svg'
blog_authors = {dict} {'Anil': ('Anil', 'https://google.com')}
blog_baseurl = {str} 'anil.io'
blog_default_author = {str} 'Anil'
config_block = {dict} {'rst': 'reStructuredText', 'markdown': 'Markdown', 'varnish3': 'Varnish 3', 'varnish4': 'Varnish 4'}
config_values = {dict} {'latex_logo': (None, None, [<type 'unicode'>, <type 'str'>]), 'applehelp_indexer_path': ('/usr/bin/hiutil', 'applehelp'), 'applehelp_stopwords': (<function <lambda> at 0x10f658668>, 'applehelp'), 'html_show_sphinx': (True, 'html'), 'html_link_suffix': (No
copyright = {str} '2016'
exclude_patterns = {list} <type 'list'>: ['_theme', 'cheatsheets/sphinx/code/examples']
extensions = {list} <type 'list'>: ['sphinx.ext.autodoc', 'sphinx.ext.doctest', 'sphinx.ext.todo', 'sensio.sphinx.refinclude', 'sensio.sphinx.configurationblock', 'sensio.sphinx.phpcode', 'sensio.sphinx.bestpractice', 'sphinx.ext.mathjax', 'sphinxcontrib.actdiag', 'sphinxcont
fontawesome_included = {bool} True
highlight_language = {str} 'php'
html_additional_pages = {dict} {'error': 'error.html'}
html_context = {dict} {'isProduction': 'False'}
html_extra_path = {list} <type 'list'>: ['robots.txt', 'anil.appcache', '.htpasswd']
html_favicon = {str} '_static/favicon.ico'
html_sidebars = {dict} {'**': ['postcard.html', 'recentposts.html', 'tagcloud.html', 'categories.html', 'archives.html']}
html_static_path = {list} <type 'list'>: ['_static']
html_theme = {str} 'classic'
latex_elements = {dict} {}
master_doc = {str} 'index'
mathjax_path = {str} 'https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML'
nwdiag_html_image_format = {str} 'svg'
overrides = {dict} {}
packetdiag_html_image_format = {str} 'svg'
post_date_format = {str} '%d %B %Y'
primary_domain = {str} 'php'
project = {str} 'Blog'
pygments_style = {str} 'sphinx'
rackdiag_html_image_format = {str} 'svg'
seqdiag_html_image_format = {str} 'svg'
setup = {NoneType} None
source_suffix = {list} <type 'list'>: ['.rst']
spelling_lang = {str} 'en_GB'
spelling_show_suggestions = {bool} True
spelling_word_list_filename = {str} 'assets/spelling_wordlist.txt'
templates_path = {list} <type 'list'>: ['_theme/_templates', '/usr/local/lib/python2.7/site-packages/ablog/templates']
```

I can use pydev debugger to inspect the state of the app, but I don't see anything I can use to help narrow down the issue.

Any help on how I can track down exactly what the issue is?

**Comment by tk0miya** [comment]
Sphinx replaces meta nodes to `sphinx.addnodes.meta` class because the original meta node of docutils could not be serializable.
https://github.com/sphinx-doc/sphinx/blob/1.4.3/sphinx/environment.py#L792
But it seems the original node is used in your environment.

Please track down who generates the node.

**Comment by lakhman** [comment]
great, that helps and makes sense!

I did a search on the ablog extension, this is the only `meta` info I found:
https://github.com/abakan/ablog/blob/devel/ablog/post.py#L223

I set a breakpoint on line 792 where we change the class of meta to addnodes.meta, it doesn't seem to throw any errors there.

```
sphinx-build -T -b html -d _build/doctrees   . _build/html
Running Sphinx v1.4.2
Initializing Spelling Checker
A Translator for the html builder is changed.
A Translator for the html builder is changed.
A Translator for the dirhtml builder is changed.
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 33 source files that are out of date
updating environment: 33 added, 0 changed, 0 removed
reading sources... [100%] index                                                                                                                                                                        
looking for now-outdated files... none found
pickling environment...  [Error happens here] 
```

The error happens after line 732 on line 136, It seems like it can read all the meta tags, but when it comes to writing them in `topickle` it fails.

https://github.com/sphinx-doc/sphinx/blob/1.4.3/sphinx/environment.py#L136

I also tried setting a breakpoint in the docutils.meta directive, I was expecting it not to be hit but it is for all meta tags.

Can I get any information from here: this is where the error is triggered?

https://github.com/sphinx-doc/sphinx/blob/1.4.3/sphinx/environment.py#L136

Any ideas how I can help track down who generates the node? 
Where could I set a breakpoint to help track down who generates the node?

You said "But it seems the original node is used in your environment." - Does this mean something may be wrong with my setup? - Should I perhaps reinstall sphinx? or your mean it's a code issue?

Sorry, i'll try debug further tomorrow, it's 4am here now, been on this almost all day! :@

**Comment by tk0miya** [comment]
Oh, sorry. I've misread your error log. I understand your error happened at `Environment.topickle()`.
My comment above is wrong. The line 792 is not related with this error. Sorry for confuse you.

It's more strange to me. In sphinx, nobody stores meta nodes into environment object.
I don't have good idea to track down. As a first step, it is good to inspect the environment object (`self` in the line 136) and search what attribute has the meta node.
