### ISSUE TITLE
Latex sphinx.sty Notice Enviroment formatting problems

### ISSUE THREAD

**Issue by AlexEshoo** [sphinx-doc/sphinx#2630]
The notice environments appear to have some problems when inserted into enumerated lists in latex. When the notice fields that invoke the lightbox command, the bottom rule line is offset back to the top level indentation, which is not the indentation level of a quoted item in the list. The length, however is correct. 

I renewed the command in my preamble and I was able to move the `\rule` generated line where it needs to be. but now there is a slight increase in the vertical space between the text and the line.

Here is the original command (defined in `sphinx.sty`)

``` LaTeX
\newcommand{\py@endlightbox}{%
  \par
  % counteract previous possible negative skip (French lists!):
  % (we can't cancel that any earlier \vskip introduced a potential pagebreak)
  \ifdim\lastskip<\z@\vskip-\lastskip\fi
  \nobreak\vbox{\noindent\rule[.4\baselineskip]{\linewidth}{0.5pt}}\allowbreak
  }
```

And here is how I redefined it:

``` LaTeX
\renewcommand{\py@endlightbox}{%
  \par
  % counteract previous possible negative skip (French lists!):
  % (we can't cancel that any earlier \vskip introduced a potential pagebreak)
  \ifdim\lastskip<\z@\vskip-\lastskip\fi
  \nobreak{\noindent\rule[.4\baselineskip]{\linewidth}{0.5pt}\allowbreak
  }
```

Simply getting rid of the `\vbox` command is enough to fix the final `\rule` command, however there is a small amount of vertical space added between the text and line now.

**Comment by jfbu** [comment]
Thanks for reporting. I see the problem. Lists in LaTeX are implemented using what is called a `\parshape` which affects only paragraphs. The  `\vbox` does not initiate a paragraph, the `\noindent\rule` does. Earlier code had `\noindent` but then we must control the `\parskip`. This version avoided that (because it has other aspects). I will work on a fix. (most probably taking into account `\@totalleftmargin` if we are in a list).

**Comment by jfbu** [comment]
fixed at b5261d5. Does this work for you ?

**Comment by AlexEshoo** [comment]
This works for me, Thanks!

**Comment by jfbu** [comment]
Thanks for reporting. I am closing now.
