### ISSUE TITLE
latexpdf and phpdomain 

### ISSUE THREAD

**Issue by jandicke** [sphinx-doc/sphinx#2633]
I installed phpdomain 0.1.4 for Sphinx 1.4.2 (Macbook Pro OS X 10.11.5) and added it to the conv.py of my project:

`extensions = [
    'sphinx.ext.todo',
    'sphinx.ext.imgmath',
    'sphinxcontrib.phpdomain'
]`

Creating HTML documents via "make html" works fine, using "make latexpfs" ends up with the following error message: 

`Exception occurred:
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinx/writers/latex.py", line 1590, in visit_index
    for type, string, tid, ismain, key_ in entries:
ValueError: need more than 4 values to unpack`

Is this a bug, or have I forgotten anythink (I'm new to Sphinx...)?

Thanks a lot,

Jan

**Comment by tk0miya** [comment]
Since sphinx-1.4, the structure of indices are changed.
It seems phpdomain does not support it.
Please let author of the extension know that.

BTW, I created a PR #2636 to avoid the crashes if extensions are old.
It will be cleared if it is merged.

**Comment by tk0miya** [comment]
Now I merged #2636. (Thanks to @shimizukawa !)

Thank you for reporting.

**Comment by jandicke** [comment]
Thank you!
