### ISSUE TITLE
toctree_only options does not work in 1.4.2

### ISSUE THREAD

**Issue by andreacassioli** [sphinx-doc/sphinx#2637]
According to  http://www.sphinx-doc.org/en/stable/config.html#confval-latex_documents I have set  `toctree_only` option to `True`.

However the following code

```
|project|
============================================


This document provides general information.


.. toctree::
   :numbered:
   :maxdepth: 1

   overview

   changes
```

Produces pdf that after the content table has a page with the text `This document provides general information.`

Well it sounds the option is just ignored....

**Comment by tk0miya** [comment]
Really? In my environment, it works surely.

Here is `toctree_only=False` (by default)
[test.pdf](https://github.com/sphinx-doc/sphinx/files/302208/test.pdf)

Here is `toctree_only=True`
[test.pdf](https://github.com/sphinx-doc/sphinx/files/302207/test.pdf)

```
latex_documents = [
    (master_doc, 'test.tex', u'test Documentation',
     u'test', 'manual', True),
]
```

**Comment by andreacassioli** [comment]
Oh my!
I should take a day off...it definitely works!

You know, I literally put 

```
`toctree_only`:True
```

in the `latex_elements` dictionary!

BTW: passing something unexpected to the dictionary generates no warning, is this OK?

**Comment by tk0miya** [comment]
> BTW: passing something unexpected to the dictionary generates no warning, is this OK?

Not so good. Users did not notice the settings are invalid.
So it would be nice if emitting warnings.

**Comment by tk0miya** [comment]
In addition, master branch is good to add warnings.
The warnings break compatibility. Because the additional warnings make crashes `sphinx-build` if `-W` option is specified.

Once, I've received much reports from who influenced by new warnings...

**Comment by andreacassioli** [comment]
OK.
Anyway, I'll close the issue.

**Comment by tk0miya** [comment]
FYI: I added the warning at e3b817d.
