### ISSUE TITLE
Version 1.4.3 introduces new requirement for iftex.sty

### ISSUE THREAD

**Issue by pburdine** [sphinx-doc/sphinx#2639]
This looks like it may have been the result of #2590.  

After updating from 1.4.1 to 1.4.3, when trying to build PDF output, the following error is displayed:
`! LaTeX Error: File`iftex.sty' not found.`

As a work around, you can download the .sty file from https://www.ctan.org/tex-archive/macros/latex/contrib/iftex?lang=en and then use the `latex_additional_files` option to include it in the build to make it work.  

Should this file be included with the sphinx distro?  This error has been reported with cygwin and Ubuntu.

Here is the group discussion:
https://groups.google.com/d/msg/sphinx-users/bnMy8qde5Zw/M7zZkPFxAgAJ

**Comment by birkenfeld** [comment]
If the file is not present in "usual" TeX distributions, it must be shipped with Sphinx.

This may well be the reason for a quick 1.4.4. No reason to be afraid of "release often".

**Comment by nmat** [comment]
I got this problem when I had the tex installed for cygwin and old miktex.

What I did as a workaround is to remove anything tex related in cygwin and install miktex new release: http://mirrors.ctan.org/systems/win32/miktex/setup/basic-miktex-2.9.5997-x64.exe and then it worked.

Not sure if you are using windows or not.

**Comment by tk0miya** [comment]
Sorry for inconvenience. I will work it and release new package in this weekend.
Thank you for reporting.

Note: It comes from #2590.

**Comment by tk0miya** [comment]
Now I bundled iftex.sty at fc3bfbca5c33bd2c2d17210a033ca7769c761e0e.
In addition, I found some more problem on building PDF on ubuntu precise. more details, see #2659.

Thank you for reporting

**Comment by jmckenna** [comment]
Thank you Komiya-san, 1.4.4 fixes issues on Precise (newfloat.sty & iftex.sty).

**Comment by JonathonReinhart** [comment]
For those who find themselves here after searching for this error message:

I didn't see this file (`iftex.sty`) included in my Debian 9 installation ([`python3-sphinx 1.4.9-2`](https://packages.debian.org/stretch/python3-sphinx)). I had to install the package [`texlive-generic-extra`](https://packages.debian.org/stretch/texlive-generic-extra) (which is *suggested* by `python3-sphinx`) to get it.

```
    apt-get install --no-install-recommends -yqq \
        locales \
        latexmk \
        make \
        python3 \
        python3-pip \
        python3-setuptools \
        python3-sphinx \
        python3-sphinx-rtd-theme \
        python3-wheel \
        texlive-fonts-recommended \
        texlive-generic-extra \
        texlive-latex-extra \
        texlive-latex-recommended \
```
