### ISSUE TITLE
C++ class constructor is not referenceable via :cpp:func:

### ISSUE THREAD

**Issue by alexsr** [sphinx-doc/sphinx#2666]
The reference to a constructor instead is a reference to the class itself.
I.e.:

```
.. cpp:class:: Test

    .. cpp:function:: Test()

:cpp:func:`Test` does not work correctly.
```

This issue could have been introduced in #2133 since this issue seems to be the exact opposite.

**Comment by jakobandersen** [comment]
Thanks for finding this. It was indeed a introduced by the commit you mentioned. It should be fixed in 'stable' now.
