### ISSUE TITLE
sphinx-build crashes with "raise EOFError" on "make html"

### ISSUE THREAD

**Issue by pletnes** [sphinx-doc/sphinx#2670]
I'm trying to use the `autodoc` extension to generate nice, browsable API docs for a python library, but `sphinx-build` crashes. Error message on screen:

```
% make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.4.1
making output directory...

Exception occurred:
  File "/home/paul/anaconda3/envs/ecopy0.2.1/lib/python2.7/pickle.py", line 886, in load_eof
    raise EOFError
EOFError
The full traceback has been saved in /tmp/sphinx-err-JESPyR.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Makefile:55: recipe for target 'html' failed
make: *** [html] Error 1
```

Removing the 'sphinx.ext.autodoc' extension from `conf.py` removes the error message, and beautiful HTML output is produced. Unfortunately, autodoc is not generated (naturally)..

The log file is attached.
[sphinx-err-JESPyR.log.txt](https://github.com/sphinx-doc/sphinx/files/311286/sphinx-err-JESPyR.log.txt)

**Comment by tk0miya** [comment]
It's a bit strange. The error happened on loading `sphinx/pycode/Grammar-py*-sphinx*.pickle`. These are a part of sphinx package and never be rewritten.
Please check if they are not broken.

**Comment by pletnes** [comment]
After downgrading sphinx from 1.4.1 to 1.3.5 (py 2.7.11 for both), the problem disappears. Some regression bug? The error takes place even on a trivial one-file project.

**Comment by tk0miya** [comment]
Oh, sorry. I said it wrong.

> These are a part of sphinx package and never be rewritten.

The `sphinx/pycode/Grammar-py*-sphinx*.pickle` are generated at first execution of autodoc. So please remove these files and invoke sphinx again after upgrading.
Please let me know if you get same error after removal it.

**Comment by pletnes** [comment]
You're correct, removing the files and reinstalling sphinx fixed the error! Thanks!
