### ISSUE TITLE
Feature request: Adjustable colour/thickness of border/rule in latex admonitions

### ISSUE THREAD

**Issue by ghost** [sphinx-doc/sphinx#2674]
Referring to sphinx.sty, and the `lightbox` and `heavybox` commands that determine the style of latex admonitions.
**This feature request:**
- Add colour and rule thickness arguments to the lightbox command.
- Add colour and box border thickness arguments to the heavybox command.

The defaults will keep the current stylings (black and 0.5pt rules/box).
This will allow these commands to be renewcommand'd (I guess) elsewhere, overriding the arg values to create a better visual distinction between the different types of admonition in the resulting PDF.
Cheers

**Comment by jfbu** [comment]
I can work on it. Default for heavybox is currently with 1pt width frame.

**Comment by jfbu** [comment]
I have given it a start at https://github.com/jfbu/sphinx/tree/jfbu_customizablenoticeborders which is on top of current master branch of main repo.

It answers your feature request but doing it I realized it probably should be better to customize separately say warning and caution directives, or hint and note for the "light" admonitions. This is feasible. As usual I have had some problems in choosing appropriate LaTeX names for lengths or for colors.

Then one will probably want also one shot customization via options to the directive, but this is more out of my domain.

With this source

``` rst
Hello
=====


Section
-------

.. warning::

   Attention!



.. raw:: latex

   \setlength{\sphinxWarningBorderThickness}{3pt}
   \definecolor{sphinxWarningBorderColor}{rgb}{1,0,0}
   \definecolor{sphinxWarningBackgroundColor}{rgb}{0,0.9,0.9}

.. warning::

   Attention!


.. raw:: latex

   \setlength{\sphinxNoteRuleThickness}{3pt}
   \definecolor{sphinxNoteRuleColor}{rgb}{0,1,0}

A paragraph

.. hint::

   Use ``'preamble'`` key to set the lengths and colors for the whole document.

.. raw:: latex

   \setlength{\sphinxNoteRuleThickness}{6pt}
   \definecolor{sphinxNoteRuleColor}{rgb}{0,0,1}

A paragraph

.. note::

   up to some extent thickness of light notices does not affect vertical
   distances between text lines.

.. raw:: latex

   \setlength{\sphinxNoteRuleThickness}{10pt}
   \definecolor{sphinxNoteRuleColor}{rgb}{0,1,0}
   \setlength{\sphinxWarningBorderThickness}{5pt}
   \definecolor{sphinxWarningBackgroundColor}{named}{yellow}
   \definecolor{sphinxWarningBorderColor}{named}{magenta}

A paragraph

.. note::

   and in strong admonitions, contents are not shifted by thick border (up to
   some quite lower limit for the thickness).

.. warning::

   Attention!

      warning, caution, attention, danger and error share the same settings.

      note, hint, important, tip, also share the same settings.

   .. raw:: latex

      \setlength{\sphinxNoteRuleThickness}{1pt}

   .. note::

      It would be nice to have options to these various admonition directives
      to allow to set the parameters on a one shot basis. 


   .. note::

      Or perhaps it would be more important to be able to distinguish more the
      various types of admonitions.

   .. raw:: latex

      \setlength{\sphinxWarningBorderThickness}{2.5pt}
      \definecolor{sphinxWarningBackgroundColor}{named}{green}
      \definecolor{sphinxWarningBorderColor}{named}{black}

   .. caution::

      proceed cautiously.

```

I get:
![capture d ecran 2016-06-13 a 20 04 45](https://cloud.githubusercontent.com/assets/2589111/16017864/2638dc86-31a2-11e6-9e78-5f0dad498175.png)

**Comment by tk0miya** [comment]
Good idea!
It would be nice if we can set up styles for each admonition directive.

In feature version, I want to introduce theming feature to LaTeX writer like HTML's.
I believe this would be a first step of it.

**Comment by jfbu** [comment]
New version allows to customize each type. Attention, naming scheme changed. And now use `\renewcommand` for length specification, not `\setlength`. At https://github.com/jfbu/sphinx/tree/jfbu_customizablenoticeborders

Example. Source:

``` rst
Hello
=====


Section
-------

.. warning::

   Attention!

.. raw:: latex

   \renewcommand{\sphinxwarningborder}{3pt}
   \definecolor{sphinxwarningbordercolor}{rgb}{1,0,0}
   \definecolor{sphinxwarningbgcolor}{rgb}{0,0.9,0.9}

   \renewcommand{\sphinxhintborder}{3pt}
   \definecolor{sphinxhintbordercolor}{rgb}{0,1,0}

   \renewcommand{\sphinxnoteborder}{6pt}
   \definecolor{sphinxnotebordercolor}{rgb}{0,0,1}

.. warning::

   Attention!

.. hint::

   Use ``'preamble'`` key to set the lengths and colors for the whole document.

.. note::

   up to some extent thickness of light notices does not affect vertical
   distances between text lines.

.. raw:: latex

   \renewcommand{\sphinxnoteborder}{10pt}
   \definecolor{sphinxnotebordercolor}{rgb}{0,1,0}

   \renewcommand{\sphinxattentionborder}{5pt}
   \definecolor{sphinxattentionbgcolor}{named}{yellow}
   \definecolor{sphinxattentionbordercolor}{named}{magenta}

   \renewcommand{\sphinxwarningborder}{2.5pt}

   \renewcommand{\sphinxhintborder}{3pt}
   \definecolor{sphinxhintbordercolor}{named}{black}

   \definecolor{sphinxcautionbgcolor}{named}{green}
   \definecolor{sphinxcautionbordercolor}{named}{black}

.. note::

   and in strong admonitions, contents are not shifted by thick border (up to
   some quite lower limit for the thickness).

.. raw:: latex

   \renewcommand{\sphinxnoteborder}{5pt}
   \definecolor{sphinxnotebordercolor}{named}{magenta}


.. attention::

      warning, caution, attention, danger and error each have their settings

.. warning::

      note, hint, important, tip, also each have their respective settings.

   .. note::

      It would perhaps be nice to have options to these various admonition
      directives to allow to set the parameters on a one shot basis.

   .. hint::

      We now distinguish the various types of admonitions.

   .. caution::

      proceed cautiously.

```

produces

![capture d ecran 2016-06-15 a 22 42 20](https://cloud.githubusercontent.com/assets/2589111/16096759/b58b121a-334a-11e6-9d64-92633a37c31f.png)

**Comment by ghost** [comment]
Nice! (The implementation, not the colours ;)
How does this become official functionality, and would it fit in with whatever @tk0miya was thinking about for theming?

**Comment by jfbu** [comment]
thanks, what's wrong with colours ? ;-) OK, now I have made notices fully customizable by user, maintaining complete backwards compatibility --- except for people who are modifying some relevant internal macros of sphinx.sty of course. This is still at https://github.com/jfbu/sphinx/tree/jfbu_customizablenoticeborders

All environments have public names and may be individually renewenvironment'd in addition to the parameters of the default environment being customizable by user. For example, there is now:

``` latex
\newenvironment{sphinxnote}[1]
  {\begin{sphinxlightbox}\strong{#1} }{\end{sphinxlightbox}}
```

hence the user can completely redefine `sphinxnote` environment if wanted. Or simply customize the

```
\definecolor{sphinxnotebordercolor}{rgb}{0,0,0}
\newcommand{\sphinxnoteborder}{0.5pt}
```

parameters which are passed over to `sphinxlightbox` environment. The latter having also a public name can be itself completely redefined. Similarly for `sphinxheavybox`, now provided with public name.

As per becoming official, I guess I need to make a PR... i must think a bit about `\sphinxcolorlet`. in previous commit I used `\colorlet` if package `xcolor` is loaded, but looking at what it does I saw it is really overkill, hence this time I use a two line definitions which seems ok, but perhaps I need some testing if I get the time.

**Comment by jfbu** [comment]
a for theming, I currently have no knowledge about how extensions are done. But now either user or extension writer has freedom to completely redefine environments `sphinxnote`,  `sphinxwarning`, etc... which until now were not defined as environments proper, and had private names. It is also possible to redefine `sphinxlightbox/sphinxheavybox` for handling simultaneously either the `note, hint, ...` or the `warning ,caution, ...` rather than individually re-defining them.

**Comment by tk0miya** [comment]
I think LaTeX theming feature is a collection of settings. For example, colorscheme, text styles, page styles and so on.
It would enable to change looks of documents for users who is not familiar to LaTeX.
(I know it is mere style file in LaTeX words)

To realize it, we have to improve customizability of LaTeX document at first.
So recent commits of @jfbu are very good to me. It provides public named, stable macro sets.
It will be a base of LaTeX theming.

**Comment by jfbu** [comment]
hi, future Sphinx 1.5 addresses your future request via merged PR #2685. Thanks for suggestion !

**Comment by ghost** [comment]
Fantastic, can't wait to try it out.

**Comment by jfbu** [comment]
;-) currently changing the thickness of border for Warning, Attention etc... has limited utility, because the text inside remains at same position, and the border becomes thicker towards the inside, the external edges not moving.

![capture d ecran 2016-06-20 a 10 34 17](https://cloud.githubusercontent.com/assets/2589111/16187810/9cd06ab4-36d2-11e6-80ce-a9059985e1be.png)

the first one has border set at `10pt` (via a `renewcommand{\sphinxwarningborder{10pt}`)  the second at `2pt`. Using `5pt` is about ok still. I can't now, but perhaps before 1.5 release, I can think about this. Current code is heritage from maintaining exact same text position as earlier.

For directives like  `note` or `hint` there is a wider range of applicable border thickness (still without moving text baselines either before, inside, or after), because the extra thickness of the horizontal rules goes to the "outside".

**Comment by ghost** [comment]
Tried it out. Fantastic.
