### ISSUE TITLE
\end{Verbatim} block needs to be on its ownline to work with latexdiff

### ISSUE THREAD

**Issue by pburdine** [sphinx-doc/sphinx#2677]
When I create `.tex` files with Sphinx and try to diff them using `latexdiff`, I get the following message:

```
! FancyVerb Error:
  Empty verbatim environment
.
\FV@Error ... {FancyVerb Error:
\space \space #1
}

l.1175 }\end{Verbatim}

?
! Emergency stop.
\FV@Error ... {FancyVerb Error:
\space \space #1
}

l.1175 }\end{Verbatim}

!  ==> Fatal error occurred, no output PDF file produced!
```

I found a forum post somewhere that `latexdiff` can't handle the end of an environment unless it is on its own line.  Using the following `sed` command, it appears to fix it:

```
sed -i 's|\\end{Verbatim}|\n\\end{Verbatim}|g' build/latex/*.tex
```

Then the following works as expected:

```
latexdiff-vc --pdf --only-changes \
    doc1.tex \
    doc2.tex
```

I understand that this is not a Sphinx bug, but is there a way to make sure there is a new line before any `\end{Verbatim}` blocks?

**Comment by jfbu** [comment]
This also applies to `figure` environment. I noticed that today with `\end{figure}` while testing another issue. This could be fixed at level of LaTeX writer.

**Comment by jfbu** [comment]
could you give an example of rst source giving rise to a latex file which does not have all `\end{Verbatim}`'s on their own lines ? I can't reproduce it so far.

**Comment by pburdine** [comment]
Ok, I double checked, I mis-characterized the issue.  The `\end{Verbatim}` is already on its own line, eg I can see the following in my original `.tex` file:

```
\begin{Verbatim}[commandchars=\\\{\}]
\PYG{g+gp}{\PYGZsh{}} /admin/installZone.ksh \PYG{l+s+se}{\PYGZbs{}}
\PYG{g+go}{    \PYGZhy{}\PYGZhy{}archive /mypath\PYGZhy{}002\PYGZus{}name.uar \PYGZbs{}}
\PYG{g+go}{    \PYGZhy{}\PYGZhy{}zone zonename}
\end{Verbatim}
```

So the above looks clean.  After it goes through latexdiff it becomes:

```
%DIFDELCMD < \begin{Verbatim}[commandchars=\\\{\}]
%DIFDELCMD < \PYG{g+gp}{\PYGZsh{}} %%%
\DIFdel{/admin/installZone.ksh }%DIFDELCMD < \PYG{l+s+se}{\PYGZbs{}}
%DIFDELCMD < \PYG{g+go}{    \PYGZhy{}\PYGZhy{}archive /mypath{}002\PYGZus{}name.uar \PYGZbs{}}
%DIFDELCMD < \PYG{g+go}{    \PYGZhy{}\PYGZhy{}zone zonename}
%DIFDELCMD < %%%
\DIFdelend \end{Verbatim}
```

If I preprocess the file with the `sed` command, it inserts an extra blank line before `\end{Verbatim}`, the output from `latexdiff` becomes:

```
%DIFDELCMD < \begin{Verbatim}[commandchars=\\\{\}]
%DIFDELCMD < \PYG{g+gp}{\PYGZsh{}} %%%
\DIFdel{/admin/installZone.ksh }%DIFDELCMD < \PYG{l+s+se}{\PYGZbs{}}
%DIFDELCMD < \PYG{g+go}{    \PYGZhy{}\PYGZhy{}archive /mypath\PYGZhy{}002\PYGZus{}name.uar \PYGZbs{}}
%DIFDELCMD < \PYG{g+go}{    \PYGZhy{}\PYGZhy{}zone zonename}
%DIFDELCMD < 

%DIFDELCMD < \end{Verbatim}
%DIFDELCMD < 
```

I don't know that I can easily come up with a single `rst` file that would show this.  This particular one is being generated by a yaml file and being feed through `sphinx-jinja`.

I have a lot of `Verbatim` blocks prior to this, I am not sure why when it gets to this point, it breaks, but adding that extra newline fixes it.

**Comment by jfbu** [comment]
sadly, I have no experience with latexdiff. All I can say is that it is a requirement of fancyvrb package that `\end{Verbatim}` <strike> is alone</strike> is last on its line. <strike>Seems latexdiff does not take this into account.</strike> I don't know the exact cause of the problem.

quickly looking at latexdiff doc (http://www.ctan.org/pkg/latexdiff) I read

> For environments whose content does not conform to standard LaTeX or where
> graphical markup does not make sense all markup commands can be removed
> by setting the PICTUREENV configuration variable, set by default to picture
> and DIFnomarkup environments; see --config option). The latter environment
> (DIFnomarkup) can be used to protect parts of the latex file where the markup
> results in illegal markup.

**Comment by jfbu** [comment]
Sphinx can not systematically add a blank line before `\end{Verbatim}` as this will create a corresponding blank line at bottom of framed literal block in pdf output.

**Comment by pburdine** [comment]
Makes sense.  I just can't figure why the first 20 or so are good.  At least now if anyone runs into this same issue they will know a workaround even if it does add an extra line here and there.

**Comment by tk0miya** [comment]
As a workaround, following script will help you:

```
def on_doctree_resolved(app, doctree, docname):
    from docutils import nodes

    if app.builder.name == 'latex':
        for node in doctree.traverse(nodes.literal_block):
            node[0] = nodes.Text(node[0] + "\n")


def setup(app):
    app.connect('doctree-resolved', on_doctree_resolved)
```

Please append this script to your `conf.py`. It will be append a blank line to all literal blocks on building latex document.
I don't know this resolves your latexdiff problem or not. But I wish this helps the investigation :-)

**Comment by jfbu** [comment]
@tk0miya  for some reason this seems to change all `Verbatim` into `allttt` environments, hence literal-blocks are not framed in output.(and without language highlighting...)

**Comment by jfbu** [comment]
Attached patch makes LaTeX writer always add a blank line before `\end{Verbatim}`, then it patches the execution of `\end{Verbatim}` to reverse the extra whitespace. Does not apply inside tables, because there original Verbatim is used which is harder to patch without after effects.

[forlatexdiff.txt](https://github.com/sphinx-doc/sphinx/files/315505/forlatexdiff.txt)

In my brief testing, this seems to work.

Nota Bene: 1.5 will use `sphinxVerbatim` name for what is currently called `Verbatim`, and `Verbatim` for what is called `OriginalVerbatim`. The patch will not apply cleanly anymore and wlll need to be patched (sic).

**Comment by tk0miya** [comment]
Ah, you're right. I missed to rewrite `node.rawsource`.

```
def on_doctree_resolved(app, doctree, docname):
    from docutils import nodes

    if app.builder.name == 'latex':
        for node in doctree.traverse(nodes.literal_block):
            node[0] = nodes.Text(node[0] + "\n")
            node.rawsource += "\n"


def setup(app):
    app.connect('doctree-resolved', on_doctree_resolved)
```

Thanks,

**Comment by tk0miya** [comment]
Any updates? I don't want to keep this opened because this is not a bug of sphinx.

**Comment by tk0miya** [comment]
Now I close this.
Please reopen if any updates.

**Comment by glikely** [comment]
The latest release of latexdiff (v1.2.1) has a way to fix this. Setting VERBATIMENV=sphinxVerbatim tells latexdiff to leave the verbatim block alone. This can be done from the command line by adding "--config VERBATIMENV=sphinxVerbatim" to the latexdiff command.
