### ISSUE TITLE
Feature Request: Todo extension should output todo list when todo_include_todos is false

### ISSUE THREAD

**Issue by AlexEshoo** [sphinx-doc/sphinx#2680]
I think there should be a way to get all the todo directive entries in a document without having to have them show up in the documentation. Currently if `todo_include_todos` is set to False, then there is no todo output generated and `.. todolist::` doesnt generate any output either. This behavior is okay, I don't want my todo items showing up in my documents but I want a way to see whats left to do in a way that doesn't write on my docs.

Could we perhaps have an option to output todo entries as "warnings" or something in sphinx-build output?

**Comment by ghost** [comment]
Good idea, and I would add to it by requesting the todo's should be one or both of:
- in the log file in a form that can be easily parsed to extract only the todo items,
- dumped into a (csv) file.
  In both cases they could include the path to the rst file and line number of the todo (as well as the test of the todo entry). This means we can load up a spreadsheet for tracking large numbers of todo's for prioritising and assignment.

**Comment by tk0miya** [comment]
I post #2737 for this issue. It emits warnings and todo-defined events.
You can write an extension to export the TODO list to CSV or other formats after this change.

**Comment by tk0miya** [comment]
I merged #2737 now.
