### ISSUE TITLE
Tabbing in code-block directive is reflected in output

### ISSUE THREAD

**Issue by AlexEshoo** [sphinx-doc/sphinx#2681]
When tabbing in the code-block directive, the output is also tabbed. Note that in the example I used spaces, which does not affect it, but tabbing does. Example:

```
.. code-block:: python
    print hello world!
```

The resulting output would be tabbed before the `print`. I think this is unintentional behavior.

**Comment by jfbu** [comment]
isn't there a blank line line:

```
.. code-block:: python

    print hello world!
```

Without the line `make html` gives a warning. Surpringly `make latex` doesn't. Which target do you use ? (in pdf output I see nothing at all if no blank line and no tabbing if a blank line in rest source --- on stable branch).

``` rst
.. code-block:: python

                print hello world!
```

this has four tabs, and pdf output has no tabbing.

**Comment by jfbu** [comment]
but I do see spacing in pdf output starting with at least two lines, like

``` rst
.. code-block:: python

                print hello world!
   coucou       zut zut
```

This sounds reasonable enough.

**Comment by jfbu** [comment]
admittedly a bit hard to understand latex file

```
\begin{Verbatim}[commandchars=\\\{\}]
                             print hello world!
coucou               zut     zut
\end{Verbatim}
```

which has 29 spaces before print, where the original had (after indentation) 4 tabs. Second line was 

```
coucou<TAB><TAB>zut<TAB>zut
```

and got converted to

```
coucou<15 spaces>zut<5 spaces>zut
```

strange...

**Comment by AlexEshoo** [comment]
Apologies, I just made a quick example in the markdown here and I forgot that blank line, but I do have it in my source. I was using make html as my target and I had observed that with a tab character I got a tab before the content block, but with 4 spaces I did not.

**Comment by tk0miya** [comment]
The reST specification says:

> Spaces are recommended for indentation, but tabs may also be used. Tabs will be converted to spaces. Tab stops are at every 8th column
> http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#whitespace

If 4 spaces and TABs are mixed in same code, you'll see the lines using TAB are indented.

To resolve it, please make `docutils.conf` on your confdir and set `tab_width` to 4.
http://docutils.sourceforge.net/docs/user/config.html#tab-width

**Comment by AlexEshoo** [comment]
@tk0miya But is it intentional for the indentation to be reflected in the first line of the `code-block` directive? My understanding was that if we are tabbed out one level past the `.. code-block::`, then it should ignore leading whitespace until the first indentation within that directive's content. If it were intentional I would think you would have the same behavior using spaces as well, but these are in fact stripped off as I expected.

**Comment by tk0miya** [comment]
Yes, leading spaces and TABs are ignored until the first indentation.

In fact, the following code-blocks are rendered as same result.

```
.. indent with spaces
.. code-block:: none

        hello world
        hello world
        hello world

.. ident with TABs
.. code-block:: none

>...>...hello world
>...>...hello world
>...>...hello world
```

I want to know your concrete problem. Could you tell me in detail? It would be nice if you upload actual reST file here.

**Comment by tk0miya** [comment]
Any updates? If not, I will close this soon.

**Comment by andreasabel** [comment]
> Yes, leading spaces and TABs are ignored until the first indentation.

Is there a way to change this?  My problem (unrelated to TABs) is that I want to continue a code block after some text inbetween with the correct indentation, say

``` rst
bla bla::

  module M where    -- indentation: 2
    def1  -- indentation: 4

more bla bla::

    def2 -- needs indentation 4
```

(My application is writing documentation for Agda, which is also type-checked by Agda, see e.g. http://agda.readthedocs.io/en/latest/language/module-system.html ).

The current rendering (in html) is like:

```
bla bla:

  module M where    -- indentation: 2
    def1  -- indentation: 4

more bla bla:

  def2 -- needs indentation 4
```

Note the wrong indentation of the last line.

My proposal is to remember relative indentation of code blocks throughout a file.

**Comment by barbara-sfx** [comment]
In the spirit of hack-y workarounds that are not pretty but are better than nothing, I offer this - a space before the 2nd code block. I hope this shows up styled as code so you can see what I'm doing.

`bla bla:

::

  module M where    -- indentation: 2
    def1  -- indentation: 4

more bla bla - there is a single space before the directive below:

 ::

  def2 -- needs indentation 4
`

![image](https://cloud.githubusercontent.com/assets/17709550/16958531/b9a740de-4d95-11e6-90db-3ab5d9fdb4cf.png)

**Comment by andreasabel** [comment]
Thanks!  Unfortunately, it does not show up as code.  Can you enclose the code block in triple backquotes please?  Like this:

```
<triple backquotes>
code
<triple backquotes>
```

**Comment by tk0miya** [comment]
Here is her comment.

```
bla bla:

::

  module M where    -- indentation: 2
    def1  -- indentation: 4

more bla bla - there is a single space before the directive below:

 ::

  def2 -- needs indentation 4
```

The second code-block behaves like quoted.
This reST is interpreted as following doctree.

```
        <paragraph>
            bla bla:
        <literal_block xml:space="preserve">
            module M where    -- indentation: 2
              def1  -- indentation: 4
        <paragraph>
            more bla bla - there is a single space before the directive below:
        <block_quote>
            <literal_block xml:space="preserve">
                def2 -- needs indentation 4
```

**Comment by tk0miya** [comment]
In addition,

> > Yes, leading spaces and TABs are ignored until the first indentation.
> 
> Is there a way to change this?

To my knowledge, there is no way to change baseline of code-blocks.
It is not a rule of `code-block` directive. It's common rule of docutils.

**Comment by AlexMabry** [comment]
I am also having this problem.  It just showed up in a recent upgrade.

**Comment by tk0miya** [comment]
@AlexMabry What did you mean "this problem"?
Could you tell me it in detail?

**Comment by AlexMabry** [comment]
Sorry.  It ended up being my problem.  I was indenting the Sphinx body in my theme template like this:  {{ body|indent(4) }}

It caused my code-block to show improperly.

**Comment by tk0miya** [comment]
Okay.
It seems all questions are resolved. So I close this now.

Thanks,
