### ISSUE TITLE
Error when parsing function declaration if using __deprecated qualifier

### ISSUE THREAD

**Issue by inakypg** [sphinx-doc/sphinx#2682]
When adding qualifiers to a function declaration, like ___deprecated_
(or _ALWAYS_INLINE_, or any others #defined somewhere), for example:

[from the Zephyr kernel in zephyrproject.org]

```

  /**
   * @brief Register a task IRQ object.
   *
   * This routine connects a task IRQ object to a system interrupt based
   * upon the specified IRQ and priority values.
   *
   * IRQ allocation is done via the microkernel server fiber, making simultaneous
   * allocation requests single-threaded.
   *
   * @param irq_obj IRQ object identifier.
   * @param irq Request IRQ.
   * @param priority Requested interrupt priority.
   * @param flags IRQ flags.
   *
   * @return assigned interrupt vector if successful, INVALID_VECTOR if not
   */
  uint32_t __deprecated task_irq_alloc(kirq_t irq_obj, uint32_t irq,
                     uint32_t priority, uint32_t flags);
```

the _Sphinx_ parser can get confused with errors such as::

```

  doc/api/microkernel_api.rst:35: WARNING: Error when parsing function declaration.
  If the function has no return type:
    Error in declarator or parameters and qualifiers
    Invalid definition: Expecting "(" in parameters_and_qualifiers. [error at 9]
      uint32_t __deprecated task_irq_alloc(kirq_t irq_obj, uint32_t irq, uint32_t priority, uint32_t flags)
      ---------^
  If the function has a return type:
    Error in declarator or parameters and qualifiers
    If pointer to member declarator:
      Invalid definition: Expected '::' in pointer to member (function). [error at 22]
        uint32_t __deprecated task_irq_alloc(kirq_t irq_obj, uint32_t irq, uint32_t priority, uint32_t flags)
        ----------------------^
    If declarator-id:
      Invalid definition: Expecting "(" in parameters_and_qualifiers. [error at 22]
        uint32_t __deprecated task_irq_alloc(kirq_t irq_obj, uint32_t irq, uint32_t priority, uint32_t flags)
        ----------------------^
  ... <etc etc>...
```

a workaround is to name with _@fn_ the function:

```

  /**
   * @fn uint32_t task_irq_alloc(kirq_t irq_obj, uint32_t irq,
   *                             uint32_t priority, uint32_t flags)
   * @brief Register a task IRQ object.
   *
   * This routine connects a task IRQ object to a system interrupt based
   * upon the specified IRQ and priority values.
   *
   * IRQ allocation is done via the microkernel server fiber, making simultaneous
   * allocation requests single-threaded.
   *
   * @param irq_obj IRQ object identifier.
   * @param irq Request IRQ.
   * @param priority Requested interrupt priority.
   * @param flags IRQ flags.
   *
   * @return assigned interrupt vector if successful, INVALID_VECTOR if not
   */
```

Is this a bug in _Sphinx_? Can we get it fixed?

Versions:

```

    $ doxygen --version
    1.8.10
    $ breathe-apidoc --version
    Breathe (breathe-apidoc) 4.2.0
    $ sphinx-build --version
    Sphinx (sphinx-build) 1.4.4

```

**Comment by jakobandersen** [comment]
The C++ parser doesn't know about macros (and probably never will). However, at some point it would be nice to parse attributes (so "[[deprecated]]" in this case). They have specific places in the C++ grammar, but so far none of them have been implemented.
If you give the examples using attributes of what you need, I will try to implement them as soon as possible.

**Comment by inakypg** [comment]
This was in C context, btw.
In the Zephry kernel we use plenty of constructs like

```
static inline __attribute__((always_inline))
void somefunc(int arg) {
        ...
}
```

or 

`__deprecated void somefunc(int arg);
`

Now sometimes we do not want to use **attribute** because we might have to #define for another toolchain whose C compiler doesn't declare deprecateds with an **attributte**. Hence where it comes interesting to just have the parser take any "qualifiers" (even if non standard) prefixing the function name.

**Comment by inakypg** [comment]
I just came about another iteration of a similar problem:

```
/** Get the buffer type
 *
 *  @param buf   Bluetooth buffer
 *
 *  @return The BT_* type to of the buffer
 */
static inline enum bt_buf_type bt_buf_get_type(struct net_buf *buf)
{
    return *(uint8_t *)net_buf_user_data(buf);
}
```

Warns with:

```
/home/e/inaky/z/kernel-oss.git/doc/api/bluetooth.rst:56: WARNING: Invalid definition: expected parentheses for function [error at 24]
  static enum bt_buf_type bt_buf_get_type(struct  net_buf  * buf)
```

however, it seems to render correctly.

Similarly: 

```
/** Set the buffer type
 *
 *  @param buf   Bluetooth buffer
 *  @param type  The BT_* type to set the buffer to
 */
static inline void bt_buf_set_type(struct net_buf *buf, enum bt_buf_type type)
{
    *(uint8_t *)net_buf_user_data(buf) = type;
}

```

which yields:

```
/home/e/inaky/z/kernel-oss.git/doc/api/bluetooth.rst:56: WARNING: Invalid definition: expected comma between arguments [error at 70]
  static void bt_buf_set_type(struct  net_buf  * buf, enum  bt_buf_type type)
```

It is definitely choking on having the 'enum XYZ' listed there, but other than that, it also renders correctly.

**Comment by inakypg** [comment]
Scratch that last one off, by mistake I was building with Sphix 1.2.3, which didn't support it. Phew!

**Comment by jakobandersen** [comment]
> This was in C context, btw.

I think Breathe assumes C++ (and doesn't know C), which is why Sphinx thinks that too.

In https://github.com/jakobandersen/sphinx/tree/cpp-attributes I tried some initial support for attributes. Currently only simple GNU style attributes are supported (i.e., `__attribute__((list, of, identifiers))`), but I will try to add other styles when needed. Also, only attributes in the decl-specifier-seq are parsed.
Maybe we should add a configuration variable where each project can define custom attributes, i.e., `__deprecated`? (resolving #2293 would be awesome for this)
If you find no unexpected problems I will merged it into 'master'.

**Comment by inakypg** [comment]
This may be a silly question, as my knowledge of how to parse C/C++ is quite severely limited.

Would it be possible to treat the "qualifiers" as a list of "any qualifiers"? kind of like:

TYPEDECL := [QUALIFIER1|TYPE1] [QUALIFIER2|TYPE2] ...

FNDECL := TYPEDECL NAME(TYPEDECL [NAME], TYPEDECL [NAME]...)

After all, via #defines and the such are going to be used to workaround or smooth different toolchains for code that works amongst different environments. 

If possible to do something like that, it would avoid having to have a race trying to support different toolchain's qualifiers (as any valid identifier would count as a qualifier) and still verify is more or less correct, as at the end the code is going to be compiled one way or another and errored out if it is wrong.

[it is common to #define GCC style **attribute**((XYZ)) if anything to increase the readability of the code]

**Comment by jakobandersen** [comment]
Most C/C++ declarations are relatively easy to parse, but when you add (member-)function pointers and templates it becomes "interesting". Due to function overloading in C++ you however need to extract the parts that participates in the overload resolution.
Therefore I try to follow the official grammar (e.g., see http://www.nongnu.org/hcb/#simple-declaration), and I'm afraid that trying to parse any identifier as an attribute will be very hard to disambiguate.
From `include/toolchain/*.h` in the public Zephyr code it seems that all custom attributes are one of:
1. an identifier (e.g., "__packed")
2. an identifier followed by something with balanced brackets (e.g., "_ALIAS_OF(of)")
My suggestion is that you can white list those identifiers as attributes in `conf.py` with something like:

``` python
domains.cpp.id_attributes = ["__packed", "__deprecated"]
domains.cpp.paren_attributes = ["_ALIAS_OF", "__printf_like"]
```

Would that work? For testing it would be awesome if you can provide complicated uses of attributes that you use.

**Comment by inakypg** [comment]
Absolutely, that is a suitable solution.

In terms of **attribute** on gcc toolchains, the one specifying printf formats is the most complicated one I can think of. So if this would handle anything SOMETHING(SOMETHINGELSE) as an attribute when SOMETHING is also found in domains.cpp.id|paren_attributes, then it'd be set.

Looking forward any others that we might use in the future (especially for other toolchains), the work around you propose would take care of them by just extending it, this was my main concern, which I am very thankful that you are addressing.

**Comment by jakobandersen** [comment]
The two configuration variables are now implemented, though named `cpp_id_attributes` and `cpp_paren_attributes`.
