### ISSUE TITLE
Napoleon does not link container types

### ISSUE THREAD

**Issue by AWhetter** [sphinx-doc/sphinx#2688]
The example for Google Style docstrings shows that `List[str]` is a valid parameter and return type. This does not get linked properly with intersphinx though as (I'm guessing) it get's treated like "`~.List[str]`" instead of "`~.list`[`~.str`]"

**Comment by RobRuana** [comment]
Yes, that's currently a problem. We're in the process of revamping the Napoleon docs, which should hopefully resolve this issue.

Thanks for the report!

**Comment by RobRuana** [comment]
The example docstrings have been updated so they'll work with intersphinx. I wasn't sure of the best way to document container types, so I've turned `List[str]` into `:obj:`list` of :str:`str``, which seems to work well with intersphinx.

The suggestion to use PEP 484 formatting in docstrings has been removed from the Napoleon docs. Instead, the docs have been updated to compare actual PEP 484 type annotations with Napoleon style docstring type specifications.

Thanks again for the report!

**Comment by AWhetter** [comment]
How do you define tuples? It's not in the documentation.

**Comment by RobRuana** [comment]
There's no real standard for how to document tuples, or any other container for that matter. The [PyCharm documentation](http://www.jetbrains.com/help/pycharm/2016.1/type-hinting-in-pycharm.html) has some good suggestions for type hinting.

You could just use parenthesis: `(int, str, MyClass)`, but to be picked up by intersphinx you still have to write `(:obj:`int`, :obj:`str`, :class:`MyClass`)`.

Intersphinx linking for primitives probably isn't that important, so you could just do `(int, str, :class:`MyClass`)`. For maximum clarity, maybe something like `tuple(int, str, :class:`MyClass`)`

**Comment by AWhetter** [comment]
Sounds good to me. Thanks for your help!

**Comment by AWhetter** [comment]
After having tried a few of these solutions, none seem that great. Doing something like `:obj:`list` of :str:`str``  or `(:obj:`int`, :obj:`str`, :class:`MyClass`)` means that the links look inconsistent with other linked types. `tuple(int, str)`, as you mentioned, doesn't link at all. Plus it's even worse in napoleon because it renders the "tuple" at the start of the return documentation and only `int, str` gets listed in the return type (which is maybe a separate issue).

I've been trying to change the Python domain to allow for automatic linking of the following syntaxes `list(str)`, `list[str]`, `dict(str, MyClass)`, `dict[str, MyClass]`, etc as suggested by PyDev (http://www.pydev.org/manual_adv_type_hints.html) but `resolve_xref` and `make_xref` in the Python domain both return only a single reference node. I can't figure out how to let them return multiple nodes, or a node tree. Is this possible?

**Comment by RobRuana** [comment]
I agree, the situation is not great. For my own documentation, I don't sweat it too much because there isn't a lot of value in creating links for Python builtins like list, dict, or tuple. Everyone pretty much already knows what those are.

**Comment by AWhetter** [comment]
I think the syntax given on the pydev link seems quite nice and I want to try and get it working. If I do `dict[str, MyClass]` it would be great for it to link as though it was `~.dict[~.str, ~.MyClass]`. It's possible to split up the target around `[](),` to get the individual parts, so we should be able to get reference nodes for each of those.
I can't find where in the code this logic is best put though as both `make_xref` (https://github.com/sphinx-doc/sphinx/blob/86c9767cedb3d6a851075d96922806527fa92bc2/sphinx/domains/python.py#L88) and `resolve_xref` (https://github.com/sphinx-doc/sphinx/blob/86c9767cedb3d6a851075d96922806527fa92bc2/sphinx/domains/python.py#L717) return only a single reference node. We would need to be able to return multiple nodes, or a node tree with the reference nodes as children.
Do you know if there is somewhere else in the code that the split and node construction logic should go?

**Comment by RobRuana** [comment]
OK, looking at your pull request, I think modifying `make_xref` looks great.
