### ISSUE TITLE
Build fails online with % in graphic file name, but no warning when built locally

### ISSUE THREAD

**Issue by barbara-sfx** [sphinx-doc/sphinx#2689]
I think the title says it all. I had created some images with "%" in the file name. Built fine locally but failed online. Please raise at least a warning offline. Thanks.

**Comment by tk0miya** [comment]
What did you mean "online" and "offline"?

**Comment by tk0miya** [comment]
Any updates?

**Comment by tk0miya** [comment]
Now I close this.
Please reopen if you have any updates.
