### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'traverse'

### ISSUE THREAD

**Issue by rameshthoomu** [sphinx-doc/sphinx#2692]
I am getting `AttributeError: 'NoneType' object has no attribute 'traverse'` error while building documentation using Sphinx for .md files using python3. Could you please let me know why I am getting below error message.

**Comment by tk0miya** [comment]
Have you ever seen following message on error?
We need the full traceback to help you from the error. Could you check it please?

```
The full traceback has been saved in /var/folders/g5/j1dpbw856fs0kk2nghyhtnsh0000gp/T/sphinx-err-zRysb1.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at https://github.com/sphinx-doc/sphinx/issues. Thanks!
```

**Comment by tk0miya** [comment]
Now I close this.
Please reopen this if you still get this problem.

Thank you for reporting
