### ISSUE TITLE
Why does BuildDoc.run() not catch exceptions?

### ISSUE THREAD

**Issue by mgeier** [sphinx-doc/sphinx#2695]
`sphinx-build` catches exceptions and displays them in a non-Python-programmer-friendly way, so I was surprised that the same error is not intercepted when using `python setup.py build_sphinx`.

I thought that both do basically the same thing, but it turns out that there is not a lot of code re-use between the two.

It would be possible to add (more) exception handling to [setup_command.py](https://github.com/sphinx-doc/sphinx/blob/c7c07db86b30b811bd8cbd31e6b2a26224c675e4/sphinx/setup_command.py), but wouldn't it be better to use the same exception handling for both use cases?

**Comment by tk0miya** [comment]
I think there is no reason not to catch them.
The base structure of exception handling is not changed since its appear at https://github.com/sphinx-doc/sphinx/commit/68f5d02390f0bc56759a4b6b74fec2b756bd2cd0#diff-b189b53617e25089010a1ff018f75d66R78

+1 for user-friendly exception handling

**Comment by tk0miya** [comment]
As a trial, I refactored `sphinx.setup_command` at https://github.com/tk0miya/sphinx/tree/2695_errhandling_on_setup_command.
But I don't know how the `distutil.cmd.Command` indicates an error.
So my fix handles the exception and show user-friendly messages. But it still raises exceptions.

Does anyone know the way to do that?
If nobody knows that, I will merge it to show better errors.

**Comment by mgeier** [comment]
I'm not sure if that's the right way, but what about raising `SystemExit`?

I think factoring out the exception handling is most natural using a context manager, see http://stackoverflow.com/a/129177/500098.

I created a possible implementation in https://github.com/mgeier/sphinx/commit/96f8d22f627a441117a005b5f0484895a6a9b28e.

I guess the `Sphinx` constructor can also raise errors, so I included it in the exception handling in `setup_command.py`.

I'm not sure if `terminal_safe()` does the right thing ... shouldn't it consider `sys.stdout.encoding` or something?
What if the terminal supports UTF8? Then converting to ASCII seems wrong, doesn't it?

In `cmdline.py` there are still several `print()` calls, I guess it would make sense to include those in the exception handling?

**Comment by mgeier** [comment]
@tk0miya ping?

**Comment by tk0miya** [comment]
Sorry for late response.

Agree with `SystemExit`. But using context manger is not good to me.
I think `sphinx.cmdline:main()` would be better to return an integer value as a result. I believe it is a de facto standard behavior.

BTW I don't know so much about `terminal_safe()`. But `sphinx.setup_command` behaves as same as the function does at caught any exceptions. So I just replaced it.

**Comment by tk0miya** [comment]
In addition, to show error messages through `SystemMessage` and `terminal_safe()` is very new to sphinx. so we need to verify it really works in many environment (ex. Windows).
I think no tests are needed if `print()` used. Because it was already used long time in Sphinx.

**Comment by mgeier** [comment]
Thanks for the changes, now it works very nicely for my use case!

There is still one thing that's inconsistent, though:
In `cmdline.py`, the call to the `Sphinx()` constructor happens within the `try` block, in `setup_command.py`, it happens outside.

I don't know if the constructor may raise or not, but at least both cases should use the same, right?

**Comment by mgeier** [comment]
BTW, I found [an old blog post from 2003 by GvR](http://www.artima.com/weblogs/viewpost.jsp?thread=4829) that confirms that you should return the error code instead of raising `SystemExit`. The reason is that you then can also call `main()` from other Python code (e.g. from an interactive prompt). Raising `SystemExit` would also quit the calling Python interpreter, which wouldn't be desired in this case.

**Comment by tk0miya** [comment]
Updated. Thank you for reviewing :-)
I will merge it soon.
