### ISSUE TITLE
Most builders not support "html_file_suffix" option

### ISSUE THREAD

**Issue by 20Tauri** [sphinx-doc/sphinx#2699]
First, thank you for this great piece of software.

In most builders that embed HTML, there's this line

``` python
        self.out_suffix = '.html'
```

Since 0.4, this is no longer valid if "html_file_suffix" option used... Causing link dead.
To solve this, `link_suffix` should be set to the same value

``` python
        self.out_suffix = '.html'
        self.link_suffix = '.html' # this line should be added
```

Regards,

**Comment by tk0miya** [comment]
Fixed at bd2ad1b.
Thank you for reporting.
