### ISSUE TITLE
HtmlHelp builder has hard coded index.html

### ISSUE THREAD

**Issue by 20Tauri** [sphinx-doc/sphinx#2700]
If conf.py redefines `master_doc`, this cause error...
Should be `self.config.master_doc + self.out_suffix` instead

**Comment by tk0miya** [comment]
Fixed at https://github.com/tk0miya/sphinx/tree/2700_htmlhelper.
But I could not test it because I don't have window environment.
Could you check this please?

**Comment by 20Tauri** [comment]
Thank you,
I'm merged your file with my one... 'chm' is generated and no longer generate an error on open.

My version have an extra line to fix  https://github.com/sphinx-doc/sphinx/issues/2699, to set       self.link_suffix = '.html'

Thank again

**Comment by tk0miya** [comment]
Thank you for confirmation. I merged it into stable branch.
I will take a look #2699 later.
