### ISSUE TITLE
documentation of c:type is unclear / faulty

### ISSUE THREAD

**Issue by return42** [sphinx-doc/sphinx#2713]
The documentation of the `.. c:type:: name` directive is faulty:

see http://www.sphinx-doc.org/en/stable/domains.html#directive-c:type

> Describes a C type (whether defined by a typedef or struct). 
> **The signature should just be the type name.**

There is a `<desc_type/>` node which makes use of the signature's type. E.g. with  `.. c:type:: struct name` we get a `<desc_type>struct<desc_type/>` node. For functions the signature's type is automatically the return type of the function. Leaving the signature's type for struct, enums or whatever, means you will miss the signature's type in the writer. On the other hand, there is no drawback, if the signature contains the type on struct, enums or whatever. Please fix the documentation / thanks.

**Comment by jakobandersen** [comment]
Fixed or no longer relevant since v3.0.
