### ISSUE TITLE
! Undefined control sequence.

### ISSUE THREAD

**Issue by charris** [sphinx-doc/sphinx#2715]
Hi All,

Generating NumPy PDF documentation with Sphinx 1.4.4 leads to an `!Undefined control sequence` error while Sphinx 1.3.5 does not. I've included the reST snippet and corresponding generated Latex for both Sphinx versions below.

```
reST
====

.. figure:: figures/dtype-hierarchy.png

   **Figure:** Hierarchy of type objects representing the array data
   types. Not shown are the two integer types :class:`intp` and
   :class:`uintp` which just point to the integer type that holds a
   pointer for the platform. All the number types can be obtained
   using bit-width names as well.


Sphinx 1.3.5 Latex
==================

\begin{figure}[htbp]
\centering
\capstart

\includegraphics{{dtype-hierarchy}.png}
\caption{\textbf{Figure:} Hierarchy of type objects representing the array data
types. Not shown are the two integer types \code{intp} and
\code{uintp} which just point to the integer type that holds a
pointer for the platform. All the number types can be obtained
using bit-width names as well.}\end{figure}
\phantomsection\label{reference/arrays.scalars:arrays-scalars-character-codes}

Sphinx 1.4.4 Latex
==================

\begin{figure}[htbp]
\centering
\capstart

\includegraphics{{dtype-hierarchy}.png}
\caption{\textbf{Figure:} Hierarchy of type objects representing the array data
types. Not shown are the two integer types \code{intp} and
\code{uintp} which just point to the integer type that holds a
pointer for the platform. All the number types can be obtained
using bit-width names as well.}\label{reference/arrays.scalars:id5}\end{figure}
\phantomsection\label{reference/arrays.scalars:arrays-scalars-character-codes}

Latex to PDF Error
==================

<dtype-hierarchy.png, id=469, 527.9725pt x 414.54875pt>
<use dtype-hierarchy.png> <use dtype-hierarchy.png>
! Undefined control sequence.
\@noligs ...lig@list \let '\textquotesingle \let `
                                                  \textasciigrave \ifx \enco...
l.5578 using bit-width names as well.}
                                      \label{reference/arrays.scalars:id5}\e...
```

**Comment by tk0miya** [comment]
It seems your error is similar to #2676.
Could you try the HEAD of stable branch?

**Comment by charris** [comment]
Yep, looks like the same problem. If I delete the `\code{...}` bits from the caption it works. Will give the development version a shot.

**Comment by charris** [comment]
Works with `Sphinx-1.5a0.dev20160625`, so this can be closed.

**Comment by tk0miya** [comment]
Thank you for confimation, and sorry for inconvenience.
Please wait a v1.4.5 or use HEAD version.

Thanks,

**Comment by charris** [comment]
Just to be sure, it also works with`Sphinx-1.4.4.dev20160625`.

**Comment by jfbu** [comment]
@charris sorry about inconvenience. This problem was from a commit of mine which made it into 1.4.4. Additionally this commit (whose aim is to render single quotes with "upright" glyphs like is done in code-blocks) had another problem (extra space appeared at end) which got fixed on stable branch at b6daf6b (June 24) hence fix will be in Sphinx-1.4.5.

**Comment by dylanmc** [comment]
I just started getting error when I upgrade to sphinx-build version 1.5.3, but wasn't with 1.4.8.

**Comment by jfbu** [comment]
@dylanmc do you mean the error like reported at top of this issue? if not please open new issue. In both cases, please try to identify which portion of your reST source corresponds in LaTeX file to location of first error and communicate that information so that we can reproduce the error.

**Comment by dylanmc** [comment]
Yes, it was the error at the top of the issue, as if the UTF-8 for accented characters was getting mangled. 
However, when I did a "make clean", which removed the .build directory, and make again, things started working, which is odd, but there you go. I guess "make clean" after a major version upgrade is a reasonable thing to expect to have to do.

**Comment by jfbu** [comment]
I am not sure if this is what happened here, but auxiliary files of LaTeX compilation remain in the build repertory. If you upgrade Sphinx and then execute  a PDF build, only the `.tex` file gets rewritten and the first LaTeX run will be with the auxiliary files (`.aux`, `.toc`, index files) from the last run which was done with earlier Sphinx. This, in itself, can in some contexts lead to failed builds. Notice that it is also possible to create some macros giving some error in a LaTeX document and that not only you then have to fix the macros in `.tex` file but also you must remove all auxiliary files to recover a sane state, else LaTeX will never by itself be able to recover.

On can go to the build repertory and do a `make clean` there which will remove these auxiliary files. But another thing is that Sphinx in some versions shipped with LaTeX support files, these support files remain in build repertory when you upgrade to a newer Sphinx which does not ship them anymore. It may happen then that these files are antiquated and mask the correct ones from your up-to-date system TeX installation. (I have not looked closely but one possibility coming to mind is `tabulary` LaTeX package which was shipped in a hacked version by Sphinx in the past.)

Thus indeed, doing `make clean` at top level is simplest to avoid such artefacts.

Sometimes I get a bit annoyed that `make clean` removes also html build where in fact I only wanted to make sure it was clean for latex build. (this happens to me when I build the own Sphinx docs !) But it does not seem worthwhile to invest some effort in this, after all it is a one liner on command line to do the selective `rm` (or `delete`; or is it `del` on Windows? I will never know) by oneself.
