### ISSUE TITLE
Making 'raw:: html' a replacement produces different html

### ISSUE THREAD

**Issue by ghost** [sphinx-doc/sphinx#2719]
I wanted a way to insert html comments in the sphinx-generated output. 
I.e. 
...
`<!-- comment -->`
`Other stuff`
`<!-- comment -->`

I tried first with:

`.. raw:: html`

   `<!-- comment -->`

which works fine. However, when I turn this into a replacement (for convenience) I get the comment line embedded in `<p>`'s. I also tried doing it as a role, e.g.
`.. role:: raw-custom(raw)`
`:format: html`

but this just wraps my comment text in a `<span>` with the class name of the role.

Any idea why making the basic raw directive into a replacement changes the output html?

MWE attached.
[test.zip](https://github.com/sphinx-doc/sphinx/files/335272/test.zip)

**Comment by tk0miya** [comment]
As a standard reST way, the substitution is good for this case.

```
.. |comment| raw:: html

   <!-- comment -->

Hello |comment| world!
```

But it seems ugly a bit. so I just made an extension for such a case.
https://gist.github.com/tk0miya/88901de09906f5f8a9fb8b729a4ff3ab

This extension adds `:raw:html` role. So you can do it with following notation:

```
Hello :raw:html:`<!-- comment -->` world!
```

It works fine for simple cases. Please check this out :-)

**Comment by tk0miya** [comment]
As a standard reST way, the substitution is good for this case.

```
.. |comment| raw:: html

   <!-- comment -->

Hello |comment| world!
```

But it seems ugly a bit. so I just made an extension for such a case.
https://gist.github.com/tk0miya/88901de09906f5f8a9fb8b729a4ff3ab

This extension adds `:raw:html` role. So you can do it with following notation:

```
Hello :raw:html:`<!-- comment -->` world!
```

It works fine for simple cases. Please check this out :-)

**Comment by ghost** [comment]
Thanks, I'll give it a try. In my company extensions cause headaches as each build platform and user (20+) have to install them and keep them up-to-date. We prefer to keep the list of dependencies as small as possible, impossible as that seems to be.
But my real question was why a replacement produces different output html to the 'replaced' version. I expected a replacement to be a literal drop-in and produce identical output.

**Comment by tk0miya** [comment]
Sorry, I don't know why it inserts `<span>` tag.
The docutils; the core library for reStrucruedText output the tag on rendering.
https://sourceforge.net/p/docutils/code/HEAD/tree/trunk/docutils/docutils/writers/html4css1/__init__.py#l1409

Please ask that in docutils project.

**Comment by tk0miya** [comment]
Now I close this again because this is not a bug of Sphinx.
Thanks,

**Comment by vlakoff** [comment]
Hi @tk0miya, just to notify you there is a duplicate comment (Jul 2, 2016), if you want to clean this :)

(I'm going to link to this topic for reference, about generating html comments)
