### ISSUE TITLE
C++, incomplete namespace support for var/member

### ISSUE THREAD

**Issue by other-mickk** [sphinx-doc/sphinx#2722]
It looks like the mangling and/or linking machinery does not fully take into account C++ namespaces when it comes to the `cpp:member`/`cpp:var` role. Consider the following:

``` rst
.. namespace-push:: ::ns_a

.. cpp:function:: int count_sheep()

.. cpp:member:: int number_of_sheep

This involves a :cpp:func:`count_sheep` and a :cpp:member:`number_of_sheep`.

.. namespace-pop::

.. namespace-push:: ::ns_b

.. cpp:function:: int count_sheep()

.. cpp:member:: float number_of_sheep

This involves a :cpp:func:`count_sheep` and a :cpp:member:`number_of_sheep`.

.. namespace-pop::

:cpp:func:`::ns_a::count_sheep` should not be confused with :cpp:func:`::ns_b::count_sheep`, nor
:cpp:member:`::ns_a::number_of_sheep` with :cpp:member:`::ns_b::number_of_sheep`.
```

On my end (using a 1.5 pre-release snapshot from master), all `number_of_sheep` references link to `…/index.html#_CPPv215number_of_sheep`, and in fact the two generated HTML elements share that same `id` attribute. The functions don't exhibit that issue and behave as expected.

Interestingly though the link titles are correct, i.e. hovering over a `number_of_sheep` reference displays a tooltip showing either `ns_a::number_of_sheep` or `ns_b::number_of_sheep`, accordingly.

Alternatively if this is a known limitation it should be documented.

**Comment by jakobandersen** [comment]
This is definitely not intended. It seems that it is "just" the id generation that doesn't use the complete name. It should be fixed in 'stable' now.
