### ISSUE TITLE
Overwriting a block in theme

### ISSUE THREAD

**Issue by bogatyrjov** [sphinx-doc/sphinx#2724]
I ran into a problem where block overwriting isn't working ( is simply skipped ) from theme but works from template. I suspect that it might be related to the fact that this block is not there in the extendable theme ( sphinx_rtd_theme ), but is there in basic theme. Seems like a bug, but might be a feature as well ...

Example: I tried overriding 'header' block from my own theme, which extends sphinx_rtd_theme ( which doesn't have that block in layout ), which in turn extends basic theme ( which has this block in layout )

**Comment by tk0miya** [comment]
Thanks, but sphinx_rtd_theme is not a part of sphinx. So please file this issue to their repository: https://github.com/snide/sphinx_rtd_theme

**Comment by bogatyrjov** [comment]
This is not related to that theme in particular but to overwriting / fallback in general. Cheers
