### ISSUE TITLE
Position of table of contents should be configurable (latex target, possibly others)

### ISSUE THREAD

**Issue by jfbu** [sphinx-doc/sphinx#2725]
In French editing, tables of contents are printed at the end of books, no at the beginning. But latex writer (and possibly others) puts the table of contents immediately after the document title. This should be configurable.

**Comment by tk0miya** [comment]
+1
Now the order of parts of LaTeX codes is defined at `sphinx/writers/latex.py` (as constants variable named HEADERS and FOOTERS). And users can not change it even if using extensions.

It would be nice if we can reorder them like HTML templating.
http://www.sphinx-doc.org/en/stable/templating.html

Note: As a workaround, you may use following settings:

```
latex_elements = {
    'footer': '\\tableofcontents',
    'tableofcontents': '',
}
```

**Comment by jfbu** [comment]
thanks for this info and the workaround

**Comment by tk0miya** [comment]
Note:
Similar case for REVTex: https://groups.google.com/forum/#!topic/sphinx-users/eAeb7g4EnZE .

**Comment by tk0miya** [comment]
Now #2866 is merged. It allows you to use user-defined template.
It will be resolve your case.

Thanks,
