### ISSUE TITLE
locale-dependent smartypants

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#274]
Would it be possible to pass smartypants replacement characters through gettext translation?

For example, russian documents should use « and » instead of “ and ” (in latex, << and >> instead of `` and ''.)

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/274
- Originally reported by: alexander smishlajev
- Originally created at: 2009-11-04T08:11:14.449

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2009-11-08 15:26:21+00:00_

Yes, that should be possible, together with the language-specific search (#273). Targeting at 1.1.

**Comment by tk0miya** [comment]
Since Sphinx-1.6, we're switched to docutils' smartypants feature (a.k.a. smart_quotes).
It supports multiple languages. So I think this is already resolved.
