### ISSUE TITLE
Support for Python 2/3 "straddling" type hint comments

### ISSUE THREAD

**Issue by ches** [sphinx-doc/sphinx#2755]
Many libraries will likely maintain Python 2 compatibility for some time yet. It would be fantastic if Sphinx apidoc supported [the Python 2.7-friendly "straddling" syntax for type hints that was added to PEP 484](https://www.python.org/dev/peps/pep-0484/#suggested-syntax-for-python-2-7-and-straddling-code) (i.e. `# type:` comments), for rendering in the same way as Python 3 type hints currently do. Additionally, support for `.pyi` files could also help for similar use cases.

PyCharm supports the `# type:` comments now, so demand might increase from people maintaining Python 2-compatible code.

I'm not at all familiar with Sphinx internals but I could try to work on this with a bit of guidance, perhaps.

Note that [GvR directed me](https://twitter.com/gvanrossum/status/750365065778384896) to [dropbox/typed_ast](https://github.com/dropbox/typed_ast) for getting at the information, urging not to try to use mypy as a library due to instability of its API. typed_ast supports parsing Python 2.7 code but unfortunately itself only runs in Python 3.

**Comment by cbornet** [comment]
👍

**Comment by thomascobb** [comment]
I made a start on extracting type comments in another project, could be useful as a starting point for you:

https://github.com/dls-controls/annotypes/blob/master/annotypes/_calltypes.py#L81

I only attempt to parse comments where they exactly match the number of arguments given to the function, otherwise ast parsing would have been required rather than just tokenizing and comparing the type strings with the arguments of the function...

**Comment by Zac-HD** [comment]
[`annotypes` permalink](https://github.com/dls-controls/annotypes/blob/c46dc495fdfc25fd9f3c9dceb902e332d304c91a/annotypes/_calltypes.py#L83-L134)

**Comment by tk0miya** [comment]
EOL of python2 will come soon. So I feel this issue become less important now. In addition, we don't have enough time to implement this. So I'd like to mark this as "wontfix".
Has anyone tried to implement this? If doing, I can wait for a while.

**Comment by tk0miya** [comment]
Note: About .pyi file support, we are discussing in #4824.

**Comment by eric-wieser** [comment]
I think this is partially handled by master of https://github.com/agronholm/sphinx-autodoc-typehints

**Comment by tk0miya** [comment]
Since python 3.8, typed_ast is merged into python core as 'ast.parse(..., type_comment=True)`.
So I just created a PR #6982 to support this. Could you try it please?
