### ISSUE TITLE
epub xhtml validation errors

### ISSUE THREAD

**Issue by mixmastamyk** [sphinx-doc/sphinx#2762]
Apparently the epub theme (inherited from basic) is adding these attributes to the generated xhtml which cause validation errors:
- `<body role="document">`
- `<div role="navigation" aria-label="related navigation">`
- `<img src="..." />`  (alt="" is required)

Browsers don't seem to mind, but Apple iBooks (via epubcheck) won't accept them.  Have confirmed with http://validator.w3.org/check .

**Comment by tk0miya** [comment]
Note: related with #2371

**Comment by mixmastamyk** [comment]
Interesting, I just noticed that the html builder does add a default alt attribute for img tags, but the epub builder doesn't.

Unfortunately looking through the code I can't figure why so far.

**Comment by tk0miya** [comment]
The epub builder uses HTML writer internally. so it is a bit strange.
Could you show me your project or any examples?

**Comment by mixmastamyk** [comment]
Ok, figured it out.  It is not the difference between html and epub, it is a difference in filetypes.  Svg images are handled differently and the sphinx HTMLTranslator does not add a default alt attribute.  The docutils version did, however, so it is a new bug.  

There is a different reason for this third issue so I will create a new bug, and am working on a pull request.
