### ISSUE TITLE
pip uninstall sphinx leaves behind files

### ISSUE THREAD

**Issue by brechtm** [sphinx-doc/sphinx#2765]
To reproduce:

```
pip install sphinx
sphinx-build -b html ...    # build a Sphinx project (that includes Python code blocks)
pip uninstall sphinx
python -c "import sphinx; print(sphinx)"
    # prints: <module 'sphinx' (namespace)>
```

Sphinx generates the file `Grammar-py3-sphinx1.4.pickle` in `site-packages/sphinx/pycode` which is left behind on uninstall.

**Comment by tk0miya** [comment]
I confirmed too. The pickle file is generated after installation, so pip does not remove it on uninstallation.
It seems the content of the file is changed by only the version of python. it does not related with the running environments. So it might be resolved if sphinx package bundles the pickle files for py2 and py3.

@birkenfeld It seems the grammer files generated by `sphinx.pycode.pgen2` are not related with version of sphinx. Is there any reason to give a version of sphinx to the filename?

Memo: it is named at 42a8138c30ca2415c068f6dc19f9dbffddca0cac
