### ISSUE TITLE
Make Sphinx work efficiently on multicores using multiprocessing

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#277]
For that, both reading and writing must be parallelizable.

The writing step (let's care about HTML for now) should already be fine, because all files can be written independently.

The reading step populates the environment, and some way must be found to merge more than one environment after reading.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/277
- Originally reported by: Georg Brandl
- Originally created at: 2009-11-08T10:09:35.770

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2013-01-13 16:39:10+00:00_

Work ongoing in pull request #108.

**Comment by shibukawa** [comment]
Sphinx already seems to use multiprocessing.

**Comment by tk0miya** [comment]
Right! We already have `-j` option for `sphinx-build` :-)
