### ISSUE TITLE
Using intersphinx with :ref: to another project results in wrong URL

### ISSUE THREAD

**Issue by jgweir** [sphinx-doc/sphinx#2771]
Hi,

I seem to be having issues with using intersphinx when linking two of my own projects together.  The conf.py seems to be correct, as it is correctly picking up the object.inv and the reference, though once compiled when clicking on the built html code the final URL is wrong.

I have two projects:

appcenter-docs/admin/en
and
appcenter-docs/apis/en

I would like to reference a file from admin -> apis.  In the admin project conf.py I have added the following configuration:

`intersphinx_mapping = {'apis' : ('../../../apis/en/build/html/', None)}`

I use reference the following reference (unique) label in the APIs docs:

```
.. _apis-index:
Welcome to UForge AppCenter REST APIs Documentation
==========================================
```

In one of the admin .rst files, I use the following :ref:

```
The contents of each message is described in an .xsd file in the :ref:`apis:apis-index`.
```

When I compile the admin project I get the following output (all seems ok):

```
make clean ; make html
rm -rf build/*
sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v1.4.4
making output directory...
six version: 1.10.0
loading pickled environment... not yet created
loading intersphinx inventory from ../../../apis/en/build/html/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 83 source files that are out of date
updating environment: 83 added, 0 changed, 0 removed
reading sources... [100%] pages/upgrade/upgrade-overview
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] pages/upgrade/upgrade-overview
generating indices... genindex
writing additional pages... search
copying images... [100%] images/uforge-arch-fe.jpg
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 1 warning.

Build finished. The HTML pages are in build/html.
```

When I open the html file, it correctly picks up the reference (by referencing the title of the API index page).  

Though the URL is:

```
file:///Users/james/UShareSoft/GitHub/appcenter-docs/admin/en/apis/en/build/html/index.html#apis-index
```

The actual correct URL I am expecting is:

```
file:///Users/james/UShareSoft/GitHub/appcenter-docs/apis/en/build/html/index.html#apis-index
```

i.e. intersphinx seems to have added the base `admin/en` to the final URL.

Is this a bug, or am I doing something wrong) ?

Current versions used:
Python: 2.7
Sphinx: 1.4.4
(also latest six: 1.10 as this was also breaking)
Platform: MacOS (El Capitan)

Thank you 
James

**Comment by tk0miya** [comment]
Hi,

Please absolute path to your `intersphinx_mapping`.
If you want to use relative path, you should specify the second tuple value of `intersphinx_mapping` like following:

```
intersphinx_mapping = {
  'apis': ('../../../../../apis/en/build/html/',
           '../../../apis/en/build/html/object.inv')
}
```

The first value is a relative path to the target directory from the output directory (usually `_build/html` is used).
The second one is a relative path to the inventory file from the project directory.

**Comment by jgweir** [comment]
That worked, thank you.  I had also tried with:

```
intersphinx_mapping = {
  'apis': ('../../../apis/en/build/html/',
           '../../../apis/en/build/html/object.inv')
}
```

which was giving me the same result.  The relative path to the target directory was wrong. 

I will close this question.

**Comment by ajdapretnar** [comment]
I know this is an old issue, but I seriously cannot find a proper answer anywhere on the internet or in the documentation,

I also have two separate projects I'd like to connect. My objects.inv got read properly thanks to these instructions. However, I cannot seem to point to the right file.
So my issue is I'd like to reference an actual .rst document from Project 1 in Project 2. It's not an object. It's just simple .rst documentation.

Mapping:

```
intersphinx_mapping = {'orange3': ('..\..\orange3\doc\\visual-programming\\build\html',
                                   '..\..\orange3\doc\\visual-programming\\build\html\
                                   objects.inv')}
```

I would like to point to .rst file for **Select Columns** documentation, which can be found in the folder data, which can be further found in the folder widgets. Based on the index.rst the path would be /widgets/data/selectcolumns.rst. I've tried.

```
 :ref:`orange3:../data/selectcolumns`
 :ref:`orange3:selectcolumns`
 :ref:`orange3:data/selectcolumns`
```

What am I doing wrong?
Sorry for n00bing here, but I really need some help.

**Comment by barbara-sfx** [comment]
I know nothing, but I'm wondering why you aren't including widgets/ in any of your refs.

But in any case, the OP was pointing to a label, not a filename, so maybe that's what you are missing. So if you had a label .. _select-columns: at the top of your file,  then if I am reading the thread correctly, orange3:select-columns should work.

**Comment by ajdapretnar** [comment]
@barbara-sfx None of these worked. :disappointed: 
I wasn't including widgets/ in my refs since my core documentation was built this way (e.g. ../data/selectcolumns worked internally completely fine). I guess that's the magic of '..'.

Also I wasn't quite sure where should I add the label - to the top of the original file or in the file where the reference was made. I tried both and it didn't work. :(

**Comment by tk0miya** [comment]
@ajdapretnar 
This issue is already closed. and it seems your situation is not related with this.
Could you file a new issue please?

If possible, it would be nice if you have minimal reproducible projects.
I will check it later.

**Comment by ajdapretnar** [comment]
I will open a new issue. Sorry and thanks for the reply.

**Comment by EricKJagde** [comment]
Thank you so much for this information.
