### ISSUE TITLE
Bad alignment of equation links

### ISSUE THREAD

**Issue by mgeier** [sphinx-doc/sphinx#2785]
This is a new issue for something I brought up in https://github.com/sphinx-doc/sphinx/pull/2643#issuecomment-231580477:

> [...] the link marker moves the equation number a bit to the left and therefore the the numbers don't align with the right text margin anymore, which looks a bit awkward (when not hovering over the equation).

Here's a screenshot for illustration (the mouse pointer is not visible in the screenshot, but I was hovering over the second equation and the ¶ sign is visible in grey):

![equation-labels](https://cloud.githubusercontent.com/assets/705404/16894118/3751d4ea-4b4d-11e6-92b6-c9cc7c514a98.png)

Would it be possible to move the link marker further to the right so it protrudes into the right margin?

Another option would be to put the link marker to the left of the number, which would restore the nice right margin but probably would look a bit awkward?

When making the screenshot, I found another problem: The equations and their numbers seem to be aligned at the top, which looks a bit strange.
Ideally, they would be aligned at the baseline, but I guess this is not possible with MathJax/PNG/CSS, right?
I think it would still be better to vertically center them.

**Comment by tk0miya** [comment]
I checked this, but the equation numbers don't move even if cursor hovers on. I confirmed with Chrome, Safari and Firefox on Mac OS. I don't know this is already resolved or browsers are updated.

But this does not mean all problems are resolved. There are still problem of alignment.
![2018-04-14 14 34 55](https://user-images.githubusercontent.com/748828/38764863-f898625a-3ff1-11e8-83a1-7333bafd8825.png)

* At present, all of numbers are aligned to right. As a result, two digits and slim numbers are seems misaligned. Look at (9), (10) and (11). They should be aligned by center.
* Equations are also misaligned if equation numbers are wide. Look at equations numbered (9), (10) and (11).
* As pointed above, equation numbers are vertically aligned at top. Look at (4).

To resolve them, we should move other CSS techniques not floating box (like grid table and flexbox).

**Comment by mgeier** [comment]
> I checked this, but the equation numbers don't move even if cursor hovers on.

Thanks for checking this out, but the problem isn't that something *moves*. The equation labels are right-aligned (which I think is good), but they are not aligned with the right edge of the surrounding text.
That's what I tried to show with the horizontal lines in my example above.

> Look at (9), (10) and (11). They should be aligned by center.

I think right-aligning them (as it is now) looks best.

> Equations are also misaligned if equation numbers are wide. Look at equations numbered (9), (10) and (11)

Yes, this looks strange. I didn't notice that before.
