### ISSUE TITLE
No documentation for variables passed to jinja

### ISSUE THREAD

**Issue by theMichaelB** [sphinx-doc/sphinx#2788]
I've been trying to write a theme, without inheriting from basic, apart from picking through the basic code there is very little documentation about what variables are sent from Sphinx to Jinja. Is there a way to find this out?

**Comment by tk0miya** [comment]
Does this page help you?
http://www.sphinx-doc.org/en/stable/templating.html

**Comment by theMichaelB** [comment]
That (seems) to describe the blocks available if I inherit from the basic template. 

My theme.conf contains - 

  [theme]
  inherit = none
  stylesheet = css/theme.css

So if I put {{ body }} into layout file, I get the body of the document. 

The documentation on that page talks about the {{ document }} block, that contains the {{ body }} block, which is how the basic template has it coded. 

I am trying to find some documentation of the lower level {{ body }} like elements.

**Comment by tk0miya** [comment]
Unfortunately, there are no more detailed document. Please read the source code of the HTML builder.

BTW, the `body` variable is "the naked body" of the document.
https://sourceforge.net/p/docutils/code/HEAD/tree/tags/docutils-0.12/docutils/writers/html4css1/__init__.py#l782
I don't know what "naked" means. Just FYI.

I keep this issue opening until somebody will update the docs.

**Comment by theMichaelB** [comment]
Am I right in thinking that the 'body' (naked or not!) is something that comes out of the back of docutils and sphinx just passes it over? - should I be looking at docutils to figure out what is going on with it? (I'll try not to hit the close button this time!)

**Comment by tk0miya** [comment]
Yes, sphinx's HTML builder calls `docutils.writers.html4css1.Writer.assemble_parts()` here and use `parts['fragment']` as the body attribute.
https://github.com/sphinx-doc/sphinx/blob/1.4.5/sphinx/builders/html.py#L447

**Comment by TimKam** [comment]
Shouldn't this issue be closed, @tk0miya ?

**Comment by tk0miya** [comment]
I missed this. Thanks!
