### ISSUE TITLE
Intersphinx URLs broken when using non-default inventory with Sphinx 1.4.3+

### ISSUE THREAD

**Issue by tjanez** [sphinx-doc/sphinx#2789]
Here is a minimal example to reproduce the problem:
- prepare a new directory for a testing project
- create `conf.py` file with the following contents:

``` python
master_doc = 'index'

project = 'Foo'
version = '0.1'
release = '0.1'
author = 'Bar'
copyright = 'Baz'

extensions = [
    'sphinx.ext.intersphinx',
]

intersphinx_mapping = {
    'django': ('https://docs.djangoproject.com/en/dev/',
               'https://docs.djangoproject.com/en/dev/_objects/'),
}
```
- create `index.rst` file with the following contents:

``` rst
Reference to Django's ``User`` class: :class:`django.contrib.auth.models.User`.
```
- build the documentation with: `sphinx-build -E ./ html/` (ensure `html` directory exists)

With Sphinx 1.4.2, the generated URL has `href="https://docs.djangoproject.com/en/dev/ref/contrib/auth/#django.contrib.auth.models.User"`, which is correct.

With Sphinx 1.4.5, the generated URL has `href="https://docs.djangoproject.com/en/dev/_objects/ref/contrib/auth/#django.contrib.auth.models.User"`, which is incorrect.

Looking at the commit history, I would guess commit 851929c912c2b1c2d0c0eaaad41e8fbea8ed66e1 is probably at fault?

**Comment by tk0miya** [comment]
Sorry for inconvenience.
I fixed this at d5078a6.

Thank you for reporting
