### ISSUE TITLE
Support for Chinese pinyin index

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#279]
currently, sphinx's  index by letter only supports English letters(and maybe some other latin languages). But truly Chinese has pinyin for each character, which has the mapping to the 26 letters in English. 

So it will be more sound if we can make the index by pinyin in Chinese pinyin, not just put them in Symbols. 

And I will try to make the patch. But I'm not sure whether I can.

Any tips about sphinx's generating the index will be appreciated. 

Regards.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/279
- Originally reported by: Zhu Tao
- Originally created at: 2009-11-09T08:37:31.694

**Comment by AA-Turner** [comment]
We now support unicode and NFD normalisation for the index.

A
