### ISSUE TITLE
control display level?

### ISSUE THREAD

**Issue by daoiqi** [sphinx-doc/sphinx#2792]
such production has one version, and development has another version.

```
  .. level: 
    :production

    only production can display


  .. level: 
    :developer

    only development can display


  .. level: 
    :production
    :development

    production and development can display



```

**Comment by lehmannro** [comment]
Please find our documentation at sphinx-doc.org, especially the parts about the [`only` directive](http://www.sphinx-doc.org/en/stable/markup/misc.html#directive-only).
