### ISSUE TITLE
Substitutions inside directives

### ISSUE THREAD

**Issue by javiereguiluz** [sphinx-doc/sphinx#2793]
To avoid repetition, I'm trying to combine includes with substitutions to simulate variables inside the contents:

``` rst
# -- parent.rst ---------------------------------------------------------------

.. |component_name| replace:: css-selector

Installation
------------

.. include:: child.rst.inc


# -- child.rst.inc ------------------------------------------------------------

.. code-block:: bash

    $ composer require symfony/|component_name|
```

---

However, substitutions don't seem to work inside directives, only on normal text:
- https://github.com/sphinx-doc/sphinx/issues/941: substitutions don't work inside the index directive
- https://github.com/sphinx-doc/sphinx/issues/185: substitutions don't work inside the titles
- _(StackOverlow contains some questions about this too...)_

---

My question: is there any built-in way to make a global replacement of contents no matter if they are used inside directives or not? Thanks!

**Comment by tk0miya** [comment]
To my knowledge, there are no way to do that in built-in feature.

**Comment by tk0miya** [comment]
I think general text pre-processors are good for your case.
There is no way to do that in built-in feature.

Thanks,

**Comment by adamtheturtle** [comment]
This is not possible without changing `code-block`.
I have created a Sphinx extension which provides `substitution-code-block` for this purpose.

It allows you to define `substitutions` in `conf.py` and then use these substitutions in `.. substitution-code-block` blocks.

This extension is at https://github.com/adamtheturtle/sphinx-substitution-extensions.

However, this is a very small amount of code.
To enable this in your own codebase without a third party extension, create a module in your codebase with the following contents:

```python
    """
    Custom Sphinx extensions.
    """

    from typing import List

    from sphinx.application import Sphinx
    from sphinx.directives.code import CodeBlock


    class SubstitutionCodeBlock(CodeBlock):  # type: ignore
        """
        Similar to CodeBlock but replaces placeholders with variables.
        """

        def run(self) -> List:
            """
            Replace placeholders with given variables.
            """
            app = self.state.document.settings.env.app
            new_content = []
            self.content = self.content  # type: List[str]
            existing_content = self.content
            for item in existing_content:
                for pair in app.config.substitutions:
                    original, replacement = pair
                    item = item.replace(original, replacement)
                new_content.append(item)

            self.content = new_content
            return list(CodeBlock.run(self))


    def setup(app: Sphinx) -> None:
        """
        Add the custom directives to Sphinx.
        """
        app.add_config_value('substitutions', [], 'html')
        app.add_directive('substitution-code-block', SubstitutionCodeBlock)
```

Then, use this module the `extensions` defined in `conf.py`.
Then, set the `substitutions` variable in `conf.py` e.g. to `[('|foo|', 'bar')]` to replace `|foo|` with `bar` in every `substitution-code-block`.
