### ISSUE TITLE
Overriding conf.py settings doesn't work for configuration variables added by extensions

### ISSUE THREAD

**Issue by brechtm** [sphinx-doc/sphinx#2802]
Only config variables that are defined in `sphinx.config.Config.config_values` can be overridden. For config variables that are defined by an extension, the following warning is given:

```
WARNING: unknown config value '<extension_config_variable>' in override, ignoring
```

**Comment by brechtm** [comment]
Please ignore this bug report. I missed the fact that I made a typo in the variable name :-/

**Comment by brechtm** [comment]
I discovered that this only doesn't work when the extension is passed to `confoverrides` when instantiating `sphinx.application.Sphinx`. If the extension is already listed in the extensions list in `conf.py`, overriding its variables does work. See also #2795.

**Comment by tk0miya** [comment]
Thank you for updating.
It seems the behavior comes from #2795. because the extensions you specified by `-D` option is not installed.

Now I close this because this is duplicated with #2795.
Please reopen if you have objection.

Thanks,
