### ISSUE TITLE
Running autodoc on Flask/Werkzeug project raises RuntimeError

### ISSUE THREAD

**Issue by vkrizan** [sphinx-doc/sphinx#2807]
Using autodoc on project using Flask/Werkzeug raises:

```
RuntimeError: working outside of request context
```

(raised from `site-packages/flask/globals.py`)

Reason for this is accessing proxied object's attribute, when the proxy is not initialized (not in right context). See commit: 6f058ba.

A fix could be to only inspect objects `__dict__` when NotImplementedError (or other) is risen after getattr -OR- ignore RuntimeError when accessing objects attribute (and print a warning).

**Comment by tk0miya** [comment]
Sorry for inconvenience.
It was already fixed at #2778.

Thanks,

**Comment by vkrizan** [comment]
Thank you!
