### ISSUE TITLE
making svg with imagemath is incredibly slow!

### ISSUE THREAD

**Issue by andreacassioli** [sphinx-doc/sphinx#2808]
I am considering switching from MathJax to SVG when it comes to formulae: when you have many formulae SVG are faster, do not rely on a MathJax server and the page does not scroll wildy until all has been rendered.

But the price to pay is a huge increase on running time. With MathJax my docs builds in 40sec. With SVG it takes 4 minutes. Now I understand that one must run Latex and the dvisvg, but still sounds an incredible performance degradation.

I have the feeling looking at the processes that nothing is parallelized, or at least it seems a formula is processed a the time. Moreover, I got the impression Tex runs many times per formula. If so, Is that necessary? 

If I re-run Sphinx then I get the images cached but to me is pointless. I run an automatic system that builds many different docs and each time the env is wiped-out. Using SVG will result the whole running time to jump from 10min to one hour and half.

Any suggestion?

**Comment by birkenfeld** [comment]
This sounds bad indeed, some questions:
- parallelized - are you using the `-jX` option?
- many times per formula - that would be an obvious bug, should be investigated.

**Comment by tk0miya** [comment]
I close this now.
Please reopen if you still have a problem even if using `-j` option.

Thanks,
