### ISSUE TITLE
Problems with pdflatex in an Italian document built with sphinx

### ISSUE THREAD

**Issue by Znni** [sphinx-doc/sphinx#2810]
In an earlier case I had problems with shorthands in a Turkish document built with sphinx in pdflatex: [https://github.com/sphinx-doc/sphinx/issues/2397](https://github.com/sphinx-doc/sphinx/issues/2397).

Now I have a similar issue with an Italian document in the same system:

`[exec] C:/foo/bar.tex:141:
BUILD FAILED`

Line 141 of bar.tex reads `\shorthandoff{"}`.

I was able to fix this in a way similar to the earlier case: I removed Italian from get_shorthandoff function from sphinx\writers\latex.py. I.e. I modified this 

```
def get_shorthandoff(self):
      shortlang = self.language.split('_')[0]
       if shortlang in ('de', 'ngerman', 'sl', 'slovene', 'pt', 'portuges',
             'es', 'spanish', 'nl', 'dutch', 'pl', 'polish', 'it',
                    'italian'):
             return '\\shorthandoff{"}'
       elif shortlang in ('tr', 'turkish'):
             return '\\shorthandoff{=}'
       return ''
```

to this

```
def get_shorthandoff(self):
      shortlang = self.language.split('_')[0]
       if shortlang in ('de', 'ngerman', 'sl', 'slovene', 'pt', 'portuges',
             'es', 'spanish', 'nl', 'dutch', 'pl', 'polish'):
             return '\\shorthandoff{"}'
       elif shortlang in ('tr', 'turkish'):
             return '\\shorthandoff{=}'
       return ''
```

Tested with sphinx 1.4.5. Just to make myself clear: This is not a new issue with a new version of sphinx. I have a new document (new language) with which this problem appeared.

**Comment by jfbu** [comment]
This is a LaTeX problem. I tried it with 2012 TeX installation and it worked, but it fails with TL2013 and TL2016. Possibly the Italian language module of Babel changed at some point. Its current documentation contains:

``` none
Table 1: shorthands for the Italian language. These shorthands are available
only if command \setactivedoublequote is given after loading babel and before
\begin{document}. 
```

As Sphinx does not insert this `\setactivedoublequote`, compilation fails with error:

`Package babel Error: I cannot switch `"' on or off--not a shorthand.`

Thus, to sum up the correct course of action is like you did, remove Italian from languages for which Sphinx emits `\shorthandoff{"}`.

@tk0miya Looks like italian addition to the `get_shorthandoff` function was added at 628adc4d. I don't know the reason for not allowing `"` as shorthand (if in `.rst` file in text, it becomes anyhow ```''` pair in tex file). People using Sphinx may have TeX installations of various levels of "oldness". I don't currently know best way in Babel to check if a character is a shorthand, hence following code could be used in `get_shorthandoff`  function:

```
return '\\if\\catcode`\\"\\active\\shorthandoff{"}\\fi'
```

With this we could leave `'italian''` in list of language for compatibility with old TeX installations.

**Comment by jfbu** [comment]
@Znni thanks for reporting the issue. The Sphinx code was adapted to older version of the Italian module for LaTeX Babel system. Around TeXLive 2013, the Italian module changed and Sphinx code became invalid due to behaviour of Babel `\shorthandoff` which rather than silently failing aborts LaTeX run with an error.
