### ISSUE TITLE
searchindex.js does not get regenerated

### ISSUE THREAD

**Issue by mavam** [sphinx-doc/sphinx#2821]
I'm facing an issue that has first been reported [on the mailing list](https://groups.google.com/forum/#!topic/sphinx-users/mmMDTirUr4s) in 2010, but doesn't appear to have been solved since. To summarize: the file `searchindex.js` doesn't get regenerated with each new build. The fix is to scratch the entire build directory. This is not an option for me, since I keep the pages under version control.

I'd assume the fix would be straightforward: whenever the content changes, just trigger a rebuild of `searchindex.js`.

**Comment by abulhol** [comment]
+1 I have the same issue.

**Comment by abulhol** [comment]
This seems to be fixed in current Sphinx Doc versions.

**Comment by jayaddison** [comment]
Closing as this appears to be resolved; please re-open with details if that's not the case, and we'll look into it.
