### ISSUE TITLE
Functools partialmethod and autodoc

### ISSUE THREAD

**Issue by benoit9126** [sphinx-doc/sphinx#2823]
Hi,

In python 3.4 the method `partialmethod` has been added to the package `functools`: https://docs.python.org/3.5/library/functools.html#functools.partialmethod
It seems that it is not currently handled by the autodoc extension even if I define the field `__doc__` of the partial method? Or maybe should defining the `__doc__` field of the method is not enough to be detected by the automodule directive?

**Comment by tk0miya** [comment]
I confirmed. It seems you can do it with variable comment. How about this?
```
class Cell(object):
    """An example for partialmethod.

    refs: https://docs.python.jp/3/library/functools.html#functools.partialmethod
    """

    def set_state(self, state):
        """Update state of cell to *state*."""

    #: Make a cell alive.
    set_alive = partialmethod(set_state, True)

    set_dead = partialmethod(set_state, False)
    """Make a cell dead."""
```

**Comment by tk0miya** [comment]
I think autodoc can document partial-methods. So I'm closing this now.
Thanks,
