### ISSUE TITLE
Overwritten `__signature__`s not followed by Sphinx

### ISSUE THREAD

**Issue by anntzer** [sphinx-doc/sphinx#2828]
MWE (Sphinx 1.4.5, Python 3.5.2, Arch Linux):

`foo.py`

```
import functools
import inspect

def _update_signature(func):
    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        return func(*args, **kwargs)
    wrapper.__signature__ = inspect.signature(lambda x, y: None)
    return wrapper

@_update_signature
def bar(*args, **kwargs):
    pass
```

`pydoc foo.bar` shows a signature of `bar(x, y)` but `sphinx-apidoc -o doc -F . && cd doc && PYTHONPATH=.. make html` results in a signature of `foo.bar(*args, **kwargs)` in the docs.

(the `__signature__` dunder is documented at https://www.python.org/dev/peps/pep-0362/#implementation)

**Comment by tk0miya** [comment]
It seems this has been already fixed with Sphinx-1.8. So I'm closing this now.
Thanks,

**Comment by asmeurer** [comment]
I am having an issue with Sphinx 3.0.3 where classes that define `__signature__` are being shown with `*args` (the naive signature from `__init__`). This is the project https://github.com/Quansight/ndindex/tree/master/docs.

**Comment by tk0miya** [comment]
@asmeurer Could you file a new issue please? I'll take a look later.
