### ISSUE TITLE
Support extension lists that are dependent on the builder type

### ISSUE THREAD

**Issue by jason-s** [sphinx-doc/sphinx#2837]
Sometimes extension lists in conf.py need to be dependent on the builder type.

For example, the `rst2pdf.pdfbuilder` is fine for the PDF builder and supports math, but it conflicts with `sphinx.ext.mathjax` which is only used in HTML.

I would like to set extension lists accordingly. As a workaround, right now I can parse `sys.argv` in my conf.py to look for `-b`, but this is a smelly hack, and it would be better if I could just access a copy of the `buildername` field of the `Sphinx()` constructor.

**Comment by jason-s** [comment]
relates to #2499

**Comment by tk0miya** [comment]
Unfortunately, your case is a bug of rst2pdf. rst2pdf always initializes math extensions internally. It conflicts to other math extensions.
https://github.com/rst2pdf/rst2pdf/blob/master/rst2pdf/pdfbuilder.py#L863

Please report that to their project.
