### ISSUE TITLE
CSV table within numbered list breaks numbering

### ISSUE THREAD

**Issue by BanHammor** [sphinx-doc/sphinx#2842]
I'm trying to have a table be situated in a numbered list. Here's how I do it:

[expl.rst.txt](https://github.com/sphinx-doc/sphinx/files/410843/expl.rst.txt)

On rst2html, this produces a list where the csv-table is embedded in one of the points, so it ends with 
"2. Point Two!". This is expected behaviour.

On Sphinx, however, it produces two lists, as the csv-table is considered a list-breaking object. Which means it ends with "1. Point Two!".

This is not reproducible with regular grid tables, even if they are prefaced with `.. table::` that describes their names.

Ergo Sphinx treats grid tables and CSV tables as different kinds of objects, and one breaks up list numbering but the other doesn't. This needs to be fixed.

**Comment by tk0miya** [comment]
Really?
I can see "2. Point two!" as a result of following commands:

```
$ sphinx-quickstart test
$ cd test
$ curl -LO https://github.com/sphinx-doc/sphinx/files/410843/expl.rst.txt
$ cat expl.rst.txt >> index.rst
$ make html
```

This is a screenshot of the rendered text:
![2016-08-12 9 53 54](https://cloud.githubusercontent.com/assets/748828/17609775/fdde9398-6072-11e6-8e22-e67f7101a301.png)

**Comment by tk0miya** [comment]
Now I close this issue.
Please reopen if you still have a problem.
