### ISSUE TITLE
`singlehtml` builder does not include figure numbers

### ISSUE THREAD

**Issue by pchampin** [sphinx-doc/sphinx#2846]
Steps to reproduce the bug:
- create a sphinx project
- add `numfig = True` in `conf.py`
- in `index.rst`, add one or more subpages in the `toctree` directive
- add a figure in one of the subpages
- (optionally add a figure in `index.rst`)
- make singlehtml

Expected result:
- all figures are numbered

Actual result:
- only the figures in `index.rst` are numbered, the others have no number displayed.

Actually, the figures have a number (appearing if the `numref` role is used to refer to the figure), but it is not included in the HTML files.

**Comment by tk0miya** [comment]
Fixed at ed2d554.
Thank you for reporting!
