### ISSUE TITLE
Section link in Latex

### ISSUE THREAD

**Issue by andreacassioli** [sphinx-doc/sphinx#2850]
I see that an internal line to a section is resolved using the section title even when the target is Latex.

This is quite non standard, as usually one would expect the section number to be used instead. 

Is there any way to
- use section number instead,
- have an option to choose which way.

The same applies to html actually.

**Comment by tk0miya** [comment]
refs: #326

**Comment by andreacassioli** [comment]
I have just stumbled across

http://docutils.sourceforge.net/docs/ref/rst/directives.html#id52

could this be used?

**Comment by tk0miya** [comment]
No, Sphinx has original section-numbering feature. so it might not work.

**Comment by tk0miya** [comment]
I updated `numref` role at #2963. It allows to refer sections if numbered.
Please try it out.
After reviewing, I will merge it.

**Comment by tk0miya** [comment]
Now I merged #2963 to master.
This might be resolved.
