### ISSUE TITLE
missing reference event for equations 

### ISSUE THREAD

**Issue by andreacassioli** [sphinx-doc/sphinx#2851]
I think that an event similar to missing-reference should be emitted when an equation reference is not resolved. 

That will allow an easy detection of equation broken links.

**Comment by andreacassioli** [comment]
Hi @tk0miya ,

I see you have find the time to look to this issue! I hope it will make it in Sphinx 1.5.

Thanks a lot!

**Comment by tk0miya** [comment]
I fixed this on PR #2861. I want to merge it into v1.5. Could you try this please?
I need reviewing and confirmation :-)

**Comment by andreacassioli** [comment]
Hi @tk0miya 
it works perfectly!

**Comment by tk0miya** [comment]
I merged #2861 into master branch now. It will be fixed at next major release (v1.5).
Thanks,
