### ISSUE TITLE
align not working with graphviz?

### ISSUE THREAD

**Issue by andreacassioli** [sphinx-doc/sphinx#2855]
In my understanding this should be a valid piece of code

```
.. graphviz::
   :caption: TSP example.
   :align: center

   digraph tsp_net{
   0->1 [label="1"];
   0->2 [label="0.1"];
   0->3 [label="0.1"];
   1->0 [label="0.1"];
   1->2 [label="1"];
   2->1 [label="0.1"];
   2->3 [label="1"];
   3->0 [label="1"];
   }
```

But I actually get this error

```
/home/andrea/blddoc/source/case-studies-tsp.rst:103: ERROR: Error in "graphviz" directive:
unknown option: "align".
```

Is there anything I am missing?

**Comment by tk0miya** [comment]
What version are you using? The `align` option is not released yet.
You should check out the code from master branch to use it.

**Comment by tk0miya** [comment]
Note: It was added at 1d17475a08c70289d4ca575090d0ee3854a53c7b

**Comment by andreacassioli** [comment]
I am sorry, I pick it up browsing the code and I haven't check whether it was already in 1.4.5....my mistake!
