### ISSUE TITLE
Search on generated HTML site doesnt find some symbols

### ISSUE THREAD

**Issue by madydady** [sphinx-doc/sphinx#2856]
For example dash symbol "-".  I try to search for "PIN-code" and there is no match. But when i search for "PIN" it finds "PIN-code", but highlites only "PIN"

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/issues/1485 similar thing.

**Comment by tk0miya** [comment]
This will be fixed by #2879.

**Comment by tk0miya** [comment]
Merged #2879. It will be released as next stable release (v1.4.7)
Thank you for reporting.

**Comment by ThomasWaldmann** [comment]
@tk0miya Are you sure this completely fixes it? See the updated borgbackup ticket:

https://github.com/borgbackup/borg/issues/1485#issuecomment-241388147
