### ISSUE TITLE
improve option role

### ISSUE THREAD

**Issue by andreacassioli** [sphinx-doc/sphinx#2862]
Currently if the program is specified in the option role as 

```
some text :option:`myprogram -h` 
```

that will display 

```
some text myprogram -h
```

being `myprogram -h` a link to the option definition. 

I think that by default the program name should be dropped. My feeling (and personal experience) is that usually the program is clear from the context. And moreover, if multiple options must be listed, it pollute the text.

Of course I know I can style the link, but it is overly annoying to customize the link every time....

**Comment by tk0miya** [comment]
You can use `program` directive to represent your **context**.

```
.. program:: myprogram

some text :option:`-h` 
```

**Comment by andreacassioli** [comment]
OK, I see, This relate to #2863.
