### ISSUE TITLE
option role not working before option definition

### ISSUE THREAD

**Issue by andreacassioli** [sphinx-doc/sphinx#2863]
I have some docs such the following (this is a simplified example)

```
You can use option :option:`-d` to...

.. program:: myprog

.. option:: -d

   description


Remember :option`-d` ?
```

It ends up that the second role works nicely, but the first can not resolve the link, .i.e.

```

```

But if I include the program name

```
You can use option :option:`myprog -d` to...

.. program:: myprog

.. option:: -d

   description


Remember :option`-d` ?
```

Then it works.

I think this is a bug, isn't it?

**Comment by tk0miya** [comment]
No, it is an expected behavior of standard domain. The `program` directive works like a namespace (context).

```
No program is specified here.
So :option:`-d` means an option for unnamed, the *default* program.

.. option:: -d

   The **d** option for unnamed, the default program.

.. program:: myprog

Now program is specified. So any ``:option:`` roles and directives works for ``myprog`` command.

.. option:: -d

    The **d** option for myprog.

The :option:`-d` refers the ``-d`` option of ``myprog``

.. program:: otherprog

The current program has been changed here.
But option reference with command-name :option:`myprog -d` refers ``myprog`` implicitly.
```

This behavior allows to represent both single command and multiple commands.
If you write a doc about single command, no `program` directive are needed.
The `program` directive helps you in case of you want to write multiple commands.

**Comment by andreacassioli** [comment]
OK, I see.

It is not that clear from the docs: for the `option` role I read

> A command-line option to an executable program. This generates a link to a option directive, if it exists.

That says nothing about scope. In the `program` directive I find

>  Instead, it serves to notify Sphinx that all following option directives document options for the program called name.

That make sense. But does it hold for that document or for all subsequent document in the toctree?

However, I think it would be nice if the program would be a parameter like

```
.. option:: -x
   :program: prog

```

That would make the program directive useless as scope I think, but rather it could actually output some text and be referentiable.

**Comment by tk0miya** [comment]
> But does it hold for that document or for all subsequent document in the toctree?

The `program` directive effects to only inside of single document (in other word, inside the file). So it does not effect to other documents.

BTW, about your proposal, I feel the case using `program` directive are much simpler for me.

```
With ``program`` directive
==========================

.. program:: sphinx-build

.. option:: -C

   use no config file at all, only :option:`-D` options

.. option:: -D setting=value

   override a setting in configuration file

Your proposal
=============

.. option:: -C
   :program: sphinx-build

   use no config file at all, only :option:`-D <sphinx-build -D>` options

.. option:: -D setting=value
   :program: sphinx-build

   override a setting in configuration file
```

Please tell me your situation.

**Comment by andreacassioli** [comment]
Hi @tk0miya 
I agree that my idea is a kind of redundant. It was just the first that crossed my mind. 

My point is that whereas is nice to have this scope approach for sake of compactness, it is to me confusing when it comes to refer to the options.
1. it makes reference format inconsistent as the program name is sometimes needed, sometimes not. 
2. If I put the program reference in a separate file say down in the toctree

```
.. toctree::

   intro
   sec1
   sec2
   reference
```

Basically I will need to specify the program each time I refer to an option.

Now, I am not saying it is bad to put the program name. Clearly if I have two program with a `-p` option, I must pick up the right one.

Actually I think the solution would be to make the program compulsory in the reference, so that there will be no room for mistakes.

The same is about the program role: It is to me a possible source of mistakes (say you move some text and forget to adjust the `program` role?). My draconian solution is redundant, but error proof. I agree that people may not like it! 

I hope it helps.

**Comment by tk0miya** [comment]
Now I marked this as wontfix.
Please let us know you find any good solution.

Thanks,
