### ISSUE TITLE
**kwargs in docstrings leads to 

### ISSUE THREAD

**Issue by waprin** [sphinx-doc/sphinx#2869]
Putting **kwargs in :param docstring leads to:

WARNING: Inline literal start-string without end-string.

http://stackoverflow.com/questions/30454549/a-literal-in-restructuredtext

Couldn't' find this when searching for it sorry if I missed it. Any existing discussion on best practices to avoid this or suggestions on how to fix it?

**Comment by tk0miya** [comment]
I think reST spec might help you. 
http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#escaping-mechanism

Personally, I don't use `*` and `**` for param notations.

**Comment by tk0miya** [comment]
I'm closing this now because this is not a bug.
Thanks,
