### ISSUE TITLE
latex footer element ignored?

### ISSUE THREAD

**Issue by andreacassioli** [sphinx-doc/sphinx#2877]
Following the Sphinx docs

```
'footer'
    Additional footer content (before the indices), default empty.
```

I thought I could use footer to add a copyright statement to my docs. But it seems that the `footer` element is just ignored. I have searched a bit the code, but it seems it is definitely never used.

**Comment by tk0miya** [comment]
Unfortunately, the `footer` element does not mean the page footer. It is a part of body.
Please refer the template of LaTeX code. The `footer` is placed here:
https://github.com/sphinx-doc/sphinx/blob/master/sphinx/templates/latex/content.tex_t#L37

I agree that this make us misread.
So it would be better to rename it.

**Comment by andreacassioli** [comment]
OK I see.
Yes, the name (and docs) are a bit misleading. Maybe the tex template should be mentioned in the docs.
