### ISSUE TITLE
error occurs when write command sudo make html

### ISSUE THREAD

**Issue by susmita1d** [sphinx-doc/sphinx#2886]
Exception occurred:
  File "conf.py", line 18, in <module>
ImportError: No module named sphinx_rtd_theme

**Comment by shibukawa** [comment]
https://github.com/sphinx-doc/sphinx/blob/master/CHANGES#L383

CHANGES said sphinx_rtd_theme is optional now.

See instruction here: https://pypi.python.org/pypi/sphinx_rtd_theme#installation

**Comment by tk0miya** [comment]
Yes, since Sphinx-1.4, sphinx_rtd_theme became optional.
So please install the package manually.

Thanks,
