### ISSUE TITLE
sphinx-apidoc --full doesn't add sourcedir to conf.py

### ISSUE THREAD

**Issue by cowst** [sphinx-doc/sphinx#2892]
Without _sourcedir_ propagated to _conf.py_ (I suppose it defaults to _._), following _make html_ for example would fail to pull the modules content.
You could say: do it manually once and forget about it.
But I want to automate the code doc generation, and although _conf.py_ could be unchanged, the initial configuration needs to be run every time because it builds _index.rst_ from the code.
Also, if I tell sphinx to create a _conf.py_ using one specific _sourcedir_ to generate the documentation, why would that _conf.py_ not be ready to use it but asking for manual intervention?

Does it make sense or I missed some additional flag to achieve what I need (or there is a reasoning behind the current behavior)?

**Comment by tk0miya** [comment]
I posted a PR #2893 to support this. Please check it :-)
