### ISSUE TITLE
Each function/method to a separate file with sphinx-apidoc?

### ISSUE THREAD

**Issue by jluttine** [sphinx-doc/sphinx#2897]
Currently, sphinx-apidoc supports putting each module to a separate file with `--separate`. I would like to have separation on a function level so that each function is on a separate file. Otherwise the module file becomes very long and difficult to read.

I like to have a list of classes/functions in a module as a table of contents on the module page, and then each class/function on a separate page. And the same thing for class pages: each method on a separate page. Is this possible currently or is there any workaround? Thanks!

**Comment by jluttine** [comment]
So to clarify a little bit what I'm after:
- Module page would contain a TOC list of classes and functions, and links to those pages.
- Package page would contain a TOC list of modules, classes and functions, and links to those pages.
- Class page would contain a TOC list of methods, and links to those pages.

And those lists would _NOT_ be recursive: they just list the names as TOC but not the submodules/classes/methods/functions of those listed elements recursively.

**Comment by jluttine** [comment]
Basically I like how autosummary extension shows modules and classes as toctrees but it doesn't recurse properly. Apidoc does a brilliant job at collecting and organizing packages and modules. Any ideas how to get the best of both worlds?

**Comment by tk0miya** [comment]
Now, autosummary supports recursive generation. And apidoc supports user-templates. So you can do what you want to do now. Please try the latest Sphinx. And please let us know if something goes bad.
Sorry for not respond you so long.
Thanks,
