### ISSUE TITLE
Warning is raised for valid tags

### ISSUE THREAD

**Issue by pcav** [sphinx-doc/sphinx#2898]
I have it for `.. todo::`, which is valid rst, handled by `conf.py`.
Nothing terrible, but it pollutes the output.
Thanks.

**Comment by tk0miya** [comment]
Could you tell me your problem in detail?
How do you mark up `todo` directives in your docs?
What warning did you see?
And what version of sphinx do you use?

**Comment by pcav** [comment]
This is an example:

`.. todo:: do this`

which results in:

`ERROR: Unknown directive type "todo".`

Sphinx v1.4.6

Thanks

**Comment by tk0miya** [comment]
Did you enable the todo extension?
It seems todo extension is not activated.

You need to add `sphinx.ext.todo` into extensions in your `conf.py` for enabling.

```
extensions = ['sphinx.ext.todo']
```
