### ISSUE TITLE
quickstart does not allow users to specify contrib extensions such as autohttp.

### ISSUE THREAD

**Issue by dusktreader** [sphinx-doc/sphinx#2903]
The autohttp extension isn't available in the current quickstart script. Adding extensions to the conf.py file generated by sphinx-quickstart must be done manually even if the user knows which contrib extensions they wish to have added to the file. It would be useful to be able to supply a list of contrib extensions that you wish to use in the quickstart script

pull request #2904 addresses this

**Comment by tk0miya** [comment]
It seems this was already fixed by https://github.com/sphinx-doc/sphinx/commit/ae1f523d52cc42d4836e1408846d4b18434b1f3a.
So I'm closing this now.

Thanks,
