### ISSUE TITLE
Epub output contains errors

### ISSUE THREAD

**Issue by Blendify** [sphinx-doc/sphinx#2906]
When trying to open epub xhtml files in a web browser I get:

`XML Parsing Error: mismatched tag. Expected: </body>.` (firefox)
`error on line 101 at column 7: Opening and ending tag mismatch: body line 0 and div` (chrome)

Epub files:

https://drive.google.com/file/d/0B6dOW1HeIPTHc2Z6TjdzUmlPNWc/view?usp=sharing

Source:

https://developer.blender.org/project/profile/53/

**Comment by shibukawa** [comment]
I confirmed too many `</div>` tag appears. I will check.

**Comment by shibukawa** [comment]
I think your template has extra `</div>` tag. 

blender_docs/templates/layout.html  

```
{% extends "!layout.html" %}

{% block footer %}
{{ super() }}
<script type="text/javascript">
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-1418081-1', 'auto');
  ga('send', 'pageview');

</script>
</div>
{% endblock %}
```

Your html document has same issue, but from 1.4.6, Sphinx generates xhtml instead of html for epub to satisfy epub standard. So Chrome/Firefox check more strictly than before version.

**Comment by Blendify** [comment]
That seems to be correct thanks for helping.
