### ISSUE TITLE
Class with metaclass becomes alias of one of its descriptors

### ISSUE THREAD

**Issue by yggdr** [sphinx-doc/sphinx#2911]
This might be related to other descriptor bugs, but I haven't seen this particular one described yet.
The bug manifests in the generated HTML as claiming a class "Test" with metaclass "TestMeta" (which is a noop) that has a descriptor field set on it like so
    field = Descriptor("bla")
is actually just an alias to said "field". With multiple descriptors available, the descriptor 
"chosen" for this apparent alias seems to be random.

See this repo for a working example: https://github.com/yggdr/sphinx_descriptor

In the src I have a simple descriptor and a class using that descriptor. That class has a metaclass which essentially does nothing: In its **new** it inspects the namespace of the class, getting all data descriptors out, and that's it. You'll see afterwards a for-loop over the extracted descriptors that just has a pass as its body. In my original code I set a "field_name" on the descriptor here, but it turns out, this looping is enough to make sphinx think that the class is an alias to its descriptor field.
Comment out this NOOP-loop, and everything is fine.

To see what I'm talking about, just `make html`, then open the documentation for src.bug.Test. You'll see that I claims the class Test to be an alias for "field". Without the for loop, the correct docs come up.

**Comment by tk0miya** [comment]
Your `Test` class says "field" as its class name. Does this intended?

```
$ git clone https://github.com/yggdr/sphinx_descriptor
$ cd sphinx_descriptor/src
$ python3.5
>>> import bug
>>> bug.Test.__name__
'field'
```

It seems `TestMeta.__new__` overrides `name` of the class at `config_fields.items()` loop.

**Comment by yggdr** [comment]
And suddenly, everything makes sense!
Using "name" in the for-loop is of course idiotic since that variable name is already in use.
Sorry for the noise!
