### ISSUE TITLE
quickstart generates an empty master table of contents

### ISSUE THREAD

**Issue by dusktreader** [sphinx-doc/sphinx#2912]
the quickstart script generates an empty master table of contents. This is frustrating, in particular when chaining quickstart with autodoc. Autodoc can execute quickstart and add modules to the mastertoc, but you have less control of quickstart options when doing this.

It would be very useful to be able to specify a list of entries to add to the master toc through the quickstart command line

Pull request incoming

**Comment by tk0miya** [comment]
How about `sphinx-apidoc --full` command? It seems the command might help you.
It scans your source code automatically. and then it generates project files including filled toctree.

**Comment by tk0miya** [comment]
Anyway, pull requests are always welcome.
I will review them if you send us :-)

**Comment by tk0miya** [comment]
Oh, sorry. I missed #2913. I'll take a look.

**Comment by dusktreader** [comment]
@tk0miya The problem with using sphinx-apidoc --full is that it assumes some settings that aren't quite right for my project.

**Comment by tk0miya** [comment]
Does this really help you?
Even if your PR accepted, quickstart still generates needless comment and "Welcome to project's documentation" heading and so on as a initial masterdoc.
quickstart generates a mere skeleton Sphinx project. I think all users should rewrite the whole of master_doc, not only around toctree.

**Comment by dusktreader** [comment]
@tk0miya The issue is that my project uses a single script to generate all documentation in a single run. I would prefer not to have to doctor index.rst between the quickstart call and apidoc. That was the purpose of this pull request

**Comment by tk0miya** [comment]
index.rst also has heading and meaningless "Indices and tables" section.
After your PR will be merged, you still have to modify the master doc after you invoke quickstart.
I think your PR could not satisfy your request.

I prefer to use an user-template for quickstart like following

```
$ sphinx-quickstart —template=[my.tpl] -d [varname]=[value] -d [varname]=[value]
```

In this way, you don't need to modify index.rst after generation.
And you can customize the default contents of master doc as you like.
What do you think about this idea?

**Comment by dusktreader** [comment]
@tk0miya yeah, that sounds better actually. If I supply a template for index.html, quickstart will not overwrite it or throw an exception? I suppose I could just rtfc...

**Comment by tk0miya** [comment]
I added `-t` and `-d` option to quickstart at 2981664178c17cfcbd46ee5af6f3329529490b60.
Could you check this please?
