### ISSUE TITLE
numref-like role with number and caption

### ISSUE THREAD

**Issue by wblock** [sphinx-doc/sphinx#2916]
I would like a numref-like role that inserts both a table or figure number _and_ the the linked object's caption.  Right now, this can be sort of crudely done (using Sphinx 1.4.4):

```
See :numref:`<example-table>`,\ :ref:`example-table`.

.. figure:: supernumref.jpg

   The Super-Numref Role
```

Which renders as:

  `See Figure 10.1,The Super-Numref Role.`

Obviously, this would be better done by a single role, without repeating captions or links.  Ideally, this would take a default format string, so the user would have some control over the formatting.  Some users might want "Figure 1: XYZ", while others might want "XYZ (Figure 1)".

**Comment by tk0miya** [comment]
I updated `numref` role at #2963. It allows to use both numfigs and titles at the same time

```
:numref:`Fig.{number} {name}`  # => Fig.1 A nice picture
```

Please try it out.
After reviewing, I will merge it.
