### ISSUE TITLE
sphinx directives: AttributeError: Values instance has no attribute 'env

### ISSUE THREAD

**Issue by moylop260** [sphinx-doc/sphinx#2922]
Using the library [restructuredtext-lint](https://github.com/twolfson/restructuredtext-lint) we can use the directive [code.Highlight](https://github.com/sphinx-doc/sphinx/blob/637ad2af48de9469e42b19930982598975d3b34f/sphinx/directives/code.py#L26) without problems.

But If we try use the directives from [other.py](https://github.com/sphinx-doc/sphinx/blob/637ad2af48de9469e42b19930982598975d3b34f/sphinx/directives/other.py) we have the following error:

``` bash
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "restructuredtext_lint/lint.py", line 62, in lint
    reader.parser.parse(content, document)
  File "docutils/parsers/rst/__init__.py", line 172, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "docutils/parsers/rst/states.py", line 170, in run
    input_source=document['source'])
  File "docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "docutils/parsers/rst/states.py", line 2299, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "docutils/parsers/rst/states.py", line 2311, in explicit_construct
    return method(self, expmatch)
  File "docutils/parsers/rst/states.py", line 2054, in directive
    directive_class, match, type_name, option_presets)
  File "docutils/parsers/rst/states.py", line 2103, in run_directive
    result = directive_instance.run()
  File "sphinx/directives/other.py", line 52, in run
    env = self.state.document.settings.env
AttributeError: Values instance has no attribute 'env'
```

Steps:
- Install:
  - `virtualenv test && source test/bin/activate && pip install restructuredtext_lint sphinx`
- Test:
  - `python -c "import restructuredtext_lint;from sphinx.directives import other;restructuredtext_lint.lint('.. toctree::\n   :maxdepth: 1\n\n   project/contribute')"`

I found other similar case for rst2beamer library in the following [thread](https://sourceforge.net/p/docutils/mailman/message/31406755/)
- Environment

``` bash
$pip freeze
alabaster==0.7.8
Babel==2.3.4
docutils==0.12
imagesize==0.7.1
Jinja2==2.8
MarkupSafe==0.23
Pygments==2.1.3
pytz==2016.4
restructuredtext-lint==0.14.3
six==1.10.0
snowballstemmer==1.2.1
Sphinx==1.4.4
```

`$python --version: Python 2.7.6`

Issue related: https://github.com/twolfson/restructuredtext-lint/issues/29

I don't know if here is the correct place to discuss it but your comments are welcome.
Thanks in advance.

**Comment by tk0miya** [comment]
The directives which sphinx provides are specialized to Sphinx.  So standard reStructuredText engine can not use them.
Especially `toctree` directive depends on `sphinx.envirnonment.Environment` object to store ToC information.

This is not a bug of restructuredtext-lint and Sphinx. Simply,  restructuredtext-lint does not support the directives of sphinx.

**Comment by moylop260** [comment]
Thanks for reply

**Comment by moylop260** [comment]
@tk0miya 
Do you have doc with examples to use a parser with `sphinx`?

We have the following script

``` python
# Code copied from https://github.com/twolfson/restructuredtext-lint to see license terms
from docutils import utils
from docutils.core import Publisher


def parser(content):
    pub = Publisher(None, None, None, settings=None)
    pub.set_components('standalone', 'restructuredtext', 'pseudoxml')
    settings = pub.get_settings(halt_level=5)
    pub.set_io()
    reader = pub.reader
    document = utils.new_document(None, settings)
    document.reporter.stream = None
    reader.parser.parse(content, document)


from sphinx.directives import other
parser('.. toctree::\n :maxdepth: 1\n\n project/contribute')
```

Result: `AttributeError: Values instance has no attribute 'env'`

I read the documentation:
- http://www.sphinx-doc.org/en/stable/extdev/tutorial.html

I know that I need use custom class of sphinx but I'm not very clear `how`

**Comment by tk0miya** [comment]
Unfortunately, Sphinx is a monolithic application. So there is no way to use only parsers.

**Comment by moylop260** [comment]
I got it
Thank you
