### ISSUE TITLE
Mathjax rendering problem is fixed by double "make html"

### ISSUE THREAD

**Issue by vpoughon** [sphinx-doc/sphinx#2927]
I am working on a project where math rendering fails for an unknown reason. However, when modifying the source file and recompiling a second time, the rendering comes out fine. So:

```
make html
touch sourcefile.rst
make html
```

Produces correct math rendering. To investigate I used git to track changes in the build directory html output, and the diff between first and second "make html" looks like this (an extract):

```
-<li><span class="math">S_{ll} = 0.5(S_{hh}+2j S_{hv}-S_{vv})</span></li>
-<li><span class="math">S_{lr} = 0.5(j S_{hh}+j S_{vv})</span></li>
-<li><span class="math">S_{rr} = 0.5(-S_{hh}+2j S_{hv}+S_{vv})</span></li>
+<li><span class="math">\(S_{ll} = 0.5(S_{hh}+2j S_{hv}-S_{vv})\)</span></li>
+<li><span class="math">\(S_{lr} = 0.5(j S_{hh}+j S_{vv})\)</span></li>
+<li><span class="math">\(S_{rr} = 0.5(-S_{hh}+2j S_{hv}+S_{vv})\)</span></li>
```

another example:

```
-<p>Where <span class="math">C_{ij}</span> are related to the elements of the reciprocal
+<p>Where <span class="math">\(C_{ij}\)</span> are related to the elements of the reciprocal
```

our conf.py is here: https://github.com/orfeotoolbox/OTB/blob/cookbook/Documentation/Cookbook/rst/conf.py.in

**Comment by tk0miya** [comment]
It seems the `math` role is overrided at top of `recipes/bandmathx.rst`.
https://raw.githubusercontent.com/orfeotoolbox/OTB/cookbook/Documentation/Cookbook/rst/recipes/bandmathx.rst

**Comment by vpoughon** [comment]
Removing that fixed the issue. Thanks a lot.
