### ISSUE TITLE
 update search function

### ISSUE THREAD

**Issue by riddle911** [sphinx-doc/sphinx#2928]
I'm a Chinese user.
I find the "html search"cannot give me the whol results.
I wonder whether I could  substitute  the default search function with my own python-based search plugin which supports Chinese search better.

**Comment by shibukawa** [comment]
Yes, Sphinx provides API to register your own search index generator:

http://www.sphinx-doc.org/en/stable/extdev/appapi.html#sphinx.application.Sphinx.add_search_language

Current available languages are here:

https://github.com/sphinx-doc/sphinx/tree/master/sphinx/search

Sphinx already bundles "zh" search. If you want to improve this, we welcome Pull Requests.

https://github.com/sphinx-doc/sphinx/blob/master/sphinx/search/zh.py

SearchLanguage provides three entry points:
- split
- filtering
- stemming

You should implement Python's word splitter at least. Western languages uses simple splitter that uses simple regexp. Japanese one provides three options and user can select one of them by config(TinySplitter: builtin one,  Janome: external pure python one, Mecab: external native program).

Filtering filters stop words (noise words for search index). Western languages have stop words list statically.

If you have an extra power (and technically reasonable), you can implement stemming. It uniforms words. It improves search ability.

If you want to word splitting when searching, you should implement word splitter in JavaScript. You can implement filtering/stemming in JS too.

**Comment by riddle911** [comment]
@shibukawa 
Sorry for replying so late.
I checked the doc which you gived me and found that the _Chinese search function_is supported by _jieba_ which I want to use before.
But unfortunately Jieba's  Chinese search is not so good ,either. 
Maybe someone or I will do something to improve it. 
Thank you . : )

**Comment by tk0miya** [comment]
Now I close this.
We always welcome your contribution.

Thanks,
