### ISSUE TITLE
Un-escapable warning with includes

### ISSUE THREAD

**Issue by Blendify** [sphinx-doc/sphinx#2939]
In the file `/editors/movie_clip_editor/masking.rst` I am using

```
.. _mask-feather:

Feather
-------
```

And then in the file `/editors/uv_image/masking` I am using:

```
.. include:: ../movie_clip_editor/masking.rst
```

As a result, Sphinx gives a warning about there being a duplicate label:

`manual/editors/movie_clip_editor/masking.rst:94: WARNING: duplicate label mask-feather, other instance in C:\Users\Aaron\BlenderDev\manual\manual\editors\movie_clip_editor\masking.rst`
# Possible Solution

As a possible solution the label in `/editors/movie_clip_editor/masking.rst` should not be copied to  `/editors/uv_image/masking`.

**Comment by tk0miya** [comment]
It seems `/editors/movie_clip_editor/masking.rst` is processed twice.
How about renaming it to non `.rst` file like `masking.txt`? Then sphinx will process it only once and the conflict will be resolved.

**Comment by andreacassioli** [comment]
I had the same issue. It seems Sphinx processes all .rst files in the build directory. I usually use .inc files for inclusion, so that Sphinx sjip them.

BTW: maybe there should be a way to specify the exact list of file to be compiled.

**Comment by tk0miya** [comment]
> BTW: maybe there should be a way to specify the exact list of file to be compiled.

No. There is only way to exclude from target (see `exclude_pattern`).

**Comment by tk0miya** [comment]
It seems resolved. So I close this now.
Please reopen if you still have the problem.
