### ISSUE TITLE
Sphinx apidoc does not process PEP-0420 implicit namespaces

### ISSUE THREAD

**Issue by arcivanov** [sphinx-doc/sphinx#2949]
Under [PEP-0420](https://www.python.org/dev/peps/pep-0420/) implicit namespaces are possible. 

That is a path structure like this:

```
a/b/c/d/__init__.py
a/b/c/d/e/__init__.py
```

produces two modules whose qualified names are "a.b.c.d" and "a.b.c.d.e".

Assuming `a/b/c` is located in `src/main/python` the invoking `sphinx-apidoc -o docs src/main/python` does not see and does not process modules `a.b.c.d` and `a.b.c.d.e`. However, if `sphinx-apidoc -o docs src/main/python/a/b/c/` is invoked then modules `d` and `e` are observed and RSTs are generated, albeit with incorrect qualified names due to wrong package path.

The compliant behavior is to follow namespace resolution in PEP-0420 and traverse package paths to arbitrary depth treating directories without `__init__.py` in the manner consistent with PEP-0420.

**Comment by arcivanov** [comment]
This should be a default behavior when running in Python >= 3.3

**Comment by arcivanov** [comment]
Strike that, it cannot be implicit behavior by default as it will be break assumed behavior where creating documentation even for sphinx itself.

Adding `--pep-420` key to force the behavior.

**Comment by arcivanov** [comment]
@tk0miya ready for review and comments

**Comment by arcivanov** [comment]
I would like this to be backported to stable as well, if possible.

**Comment by tk0miya** [comment]
> I would like this to be backported to stable as well, if possible.

The stable release should be include bug fixes. but this is a new feature.
So please wait for next major release.
