### ISSUE TITLE
Quickstart should return an error consistently on all error conditions

### ISSUE THREAD

**Issue by arcivanov** [sphinx-doc/sphinx#2955]
https://github.com/sphinx-doc/sphinx/blob/master/sphinx/quickstart.py#L630 and https://github.com/sphinx-doc/sphinx/blob/master/sphinx/quickstart.py#L636 do not return an error but
https://github.com/sphinx-doc/sphinx/blob/master/sphinx/quickstart.py#L595 does, even though all three conditions are equally fatal to the execution.

**Comment by tk0miya** [comment]
#2956 merged.
