### ISSUE TITLE
Unexpected `-D` and `-A` behavior

### ISSUE THREAD

**Issue by aetter** [sphinx-doc/sphinx#2958]
Hi there,

I'm struggling with the following code in `conf.py`:

```
html_context = {
    'external': False
}

if html_context.get('external', False) is False:
    # do something
else:
    # do something else
```

Then my build command is:

```
sphinx-build -b html -D html_context.external=True . _build/html
```

or

```
sphinx-build -b html -A external=True . _build/html
```

I've also tried `1` in place of `True`.

My expectation is that the `'external': False` value should be overwritten by either of the command line arguments, and `html_context.get('external', False)` should return True. Instead, it seems the overrides are ignored. `html_context.get('external', False)` always returns False.

Is this behavior as-designed?

**Comment by tk0miya** [comment]
`-D` and `-A` options are evaluated after conf.py. So you can refer them inside conf.py.
If you really want, please use `builder-inited` handler:

```
# in your conf.py
def on_builder_inited(app):
    # `-D` and `-A` are evaluated here
    print app.config.html_context.get('foo')

def setup(app):
    app.connect('builder-inited', on_builder_inited)
```

**Comment by aetter** [comment]
Hi @tk0miya, thanks for the clarification. 👍
