### ISSUE TITLE
Intersphinx doesn't recognize external projects' plain .rst

### ISSUE THREAD

**Issue by ajdapretnar** [sphinx-doc/sphinx#2970]
I am trying to use intersphinx to link to our core project. The core project has documentation for both GUI and scripting. I'm trying to link to documentation for GUI, which is in plain .rst.

Here's the structure:

```
core-project:
    doc:
        index.rst
        widgets:
            somedocumentation.rst

sister-project:
    doc:
        index.rst
        sister-widgets:
             sisterdocumentation.rst
```

So in my `sisterdocumentation.rst` I'm trying to point to `somedocumentation.rst`. How do I do it?

I've set my conf.py to include:

```
intersphinx_mapping = {'core-project': ('..\..\core-project\doc\build\html',
                                       '..\..\core-project\doc\build\html\objects.inv')}
```

Sphinx build doesn't complain about not recognizing the mapping, but the links are not there (in the documentation).

My guess: documentation doesn't include actual Python object and thus intersphinx cannot link them properly.

I'd appreciate your help truly. If required, I can point you to the actual project.

**Comment by tk0miya** [comment]
Thank you for filing :-)

I investigated. objects.inv also includes docnames. So you can refer them by `:doc:` role.
`:ref:` role is used to refer labels. so it could not find docnames.

Thanks,

**Comment by tk0miya** [comment]
MEMO: It was implmented at #1909

**Comment by ajdapretnar** [comment]
Thanks for the quick reply @tk0miya! However, I still don't know well how to link properly.
Now I've tried many combinations of:

```
:doc:`core-project:somedocumentation`
:doc:`core-project:../widgets/somedocumentation`
```

and none seem to work.
Sphinx is still complaining it cannot find this file. If you can please tell me what I'm doing wrong, I'd appreciate it very much. It would be a life saver for our project!

**Comment by tk0miya** [comment]
I succeeded with following steps:
```
$ sphinx-quickstart doc1 -q -a author -p proj -v 1.0
$ cd doc1/
$ make html
$ cd ../
$ sphinx-quickstart doc2 -q -a author -p proj -v 1.0
$ cd doc2/
$ vi conf.py
$ vi index.rst
$ make html
```
```
# conf.py
extensions = ['sphinx.ext.intersphinx']
intersphinx_mapping = {
    'doc1': ('../../../doc1/_build/html',
             '../doc1/_build/html/objects.inv')
}
```
```
# index.rst
:doc:`doc1:index`
```

The docnames are contained to inventory file since Sphinx-1.4. So you should use Sphinx-1.4 or above on both referrer and target.

**Comment by tk0miya** [comment]
It looks working. So I close this.
Thanks,

**Comment by ajdapretnar** [comment]
Ok, sorry, but I'm still confused. You made two doc folders side by side, but if I put them in separate folders (e.g. ../Big project/doc1, ../Small project/doc2), everything stops working. I'm lost at how many ../ should this have... 😕 I've tried adding one more for the extra folder included, but nothing seems to work.
Also, when I follow your steps exactly, the reference is still not recognized as valid (objects.inv is, though).

**Comment by tk0miya** [comment]
Okay, I understand your situation.
It seems your problem is caused by settings.
```
intersphinx_mapping = {'core-project': ('..\..\core-project\doc\build\html',
                                       '..\..\core-project\doc\build\html\objects.inv')}
```

The first element of the value of `intersphinx_mapping` is used to create hyperlinks.
So it should be a relative path from the HTML file.
In other words, it is a relative path from `_build/html` directory.

The second one is used to fetch inventory file.
It should be a relative path from source directory.

Usually, the first element has one or two `../` more than second one.
