### ISSUE TITLE
If you search for "url", you get 400 Bad Request

### ISSUE THREAD

**Issue by mpacer** [sphinx-doc/sphinx#2974]
It looks like something is happening when parsing the json you get back from readthedocs because it's transforming 

http://www.sphinx-doc.org/en/stable/search.html?q=url

to http://www.sphinx-doc.org/en/stable/%3Cem%3Eurl%3C/em%3E=%20%(toc)s

which seems like something is wrong…

**Comment by tk0miya** [comment]
In my local environment, I can search sphinx-doc with "url". I think this is a bug of readthedocs. It seems they overrides search features by their custom javascripts.
Could you report this to their project?

**Comment by tk0miya** [comment]
I close this now because this isn't a bug of Sphinx.
