### ISSUE TITLE
Problem with ..only:: and heading levels

### ISSUE THREAD

**Issue by barbara-sfx** [sphinx-doc/sphinx#2978]
I have this in conf.py (I was planning to delete the tags.remove when the feature is released):

tags.add('show_muted')

tags.remove('show_muted') 

If I have the ..only directive above an h2, the first label following the end of the ..only is not found.  If I remove the h2 indicator, everything works as expected.

Attached are files with and without the h2 indicator to illustrate the problem. (couldn't upload rst so please change extension to test)

[label-doesnt-work.txt](https://github.com/sphinx-doc/sphinx/files/496163/label-doesnt-work.txt)
[label-works.txt](https://github.com/sphinx-doc/sphinx/files/496164/label-works.txt)

**Comment by tk0miya** [comment]
Thank you for reporting.
I close this because it seems this is duplicated with #2306.
