### ISSUE TITLE
autosummary creates files with module in name

### ISSUE THREAD

**Issue by psifertex** [sphinx-doc/sphinx#2981]
I'm using autosummary to automatically generate `.rst` files but they're generating with the name of the module plus the class when I'd prefer just the name of the class. See http://api.binary.ninja/ (way too many duplicate details listing the module in both the ToC and main index).

My config is: https://github.com/Vector35/binaryninja-api/blob/master/api-docs/source/conf.py

Any help would be appreciated. 

If I can't figure out an alternative, I can just disable the autosummary and use the existing files with some mass search/replace/rename but that seems inefficient and prone to breakage long-term versus always generating it from the code.

**Comment by tk0miya** [comment]
There are no way to configure the way to control the filename of autosummary. And I think such configuration causes conflicts with other classes in different module (ex. `foo.MyClass` and `bar.MyClass`). So it's not needed.

**Comment by psifertex** [comment]
I'd settle for a way to generate the RST and then do a second pass where I could re-write the text but right now it's done as a single step.

**Comment by psifertex** [comment]
As I understand it, my only option right now is to try to patch the HTML directly which is a poor choice.
