### ISSUE TITLE
themes/basic/defindex.html should be changed for html5 friendly

### ISSUE THREAD

**Issue by hhsprings** [sphinx-doc/sphinx#2986]
[themes/basic/defindex.html](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/themes/basic/defindex.html#L21) uses `align` attribute for `table` and `width` attribute for `td`, but these are invalid as html5.

**Comment by tk0miya** [comment]
Fixed.
Thank you for reporting

**Comment by tk0miya** [comment]
After fixed, I investigated about `defindex.html`.
It was used to keep compatibility to before Sphinx-0.2.
And no longer used in current source code.

So finally, I removed it.
Thanks,

**Comment by leplatrem** [comment]
@tk0miya, removing this `defindex.html` is a breaking change IMO ;) Our documentation suddenly broke with Sphinx 1.5a2

I thought we were the only ones inheriting that internal file, but apparently thousands of projects rely on it too: https://github.com/search?q=defindex.html&type=Code&utf8=%E2%9C%93

**Comment by tk0miya** [comment]
Hmm... that's strange situation.
Okay, I will restore it again.
But, the status is still not changed. `defindex.html` is no longer used by default. so I will emit deprecation warning to `defindex.html`.

**Comment by tk0miya** [comment]
I restored `defindex.html` and add deprecation warning.
Thanks,
