### ISSUE TITLE
linkcheck.py is broken?

### ISSUE THREAD

**Issue by hhsprings** [sphinx-doc/sphinx#2990]
Regarding to #2988: in the first place, linkcheck.py is broken now?

There are at least two problems.
1. for Python 3.x (for me, it is 3.5.2), linkcheck.py is likely to have a unicode problem.
2. for both 3.x and 2.7, [#L167](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/builders/linkcheck.py#L167) may raise `UnboundLocalError` (`local variable 'code' referenced before assignment`).

For now, running `make linkcheck` in CPython documentation fails, because the UnboundLocalError occurs.

Former is like this:

```
distributing\index.rst:123: [broken] https://packaging.python.org/en/latest/distributing/#packaging-your-project: Can't convert 'bytes' object to str implicitly
distributing\index.rst:124: [broken] https://packaging.python.org/en/latest/distributing/#uploading-your-project-to-pypi: Can't convert 'bytes' object to str implicitly
distributing\index.rst:111: [broken] https://packaging.python.org/en/latest/current/#packaging-tool-recommendations: Can't convert 'bytes' object to str implicitly
distutils\apiref.rst:1002: [broken] http://nfs.sourceforge.net/#section_d: Can't convert 'bytes' object to str implicitly
howto\descriptor.rst:126: [broken] https://www.python.org/download/releases/2.2.3/descrintro/#cooperation: Can't convert 'bytes' object to str implicitly
howto\logging-cookbook.rst:1639: [broken] https://tools.ietf.org/html/rfc5424#section-6: Can't convert 'bytes' object to str implicitly
howto\logging-cookbook.rst:1376: [broken] https://docs.djangoproject.com/en/1.9/topics/logging/#configuring-logging: Can't convert 'bytes' object to str implicitly
howto\logging-cookbook.rst:1320: [broken] https://docs.djangoproject.com/en/1.9/topics/logging/#configuring-logging: Can't convert 'bytes' object to str implicitly
...
```

It is likely that all of these has a fragment...

**Comment by hhsprings** [comment]
- TypeError (`Can't convert 'bytes' object to str implicitly`): at [#L65](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/builders/linkcheck.py#L65) (called from [#L133](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/builders/linkcheck.py#L133)). (type of `chunk`  is bytes.)
- Using `response.iter_content()` is likely not to behave as your intent in Python 3.5.

**Comment by hhsprings** [comment]
I got it.
Need to be changed: `response.iter_content(decode_unicode=True)`.

**Comment by hhsprings** [comment]
<s>
- from `https://packaging.python.org/distributing/`
- to     `https://packaging.python.org/en/latest/distributing/`
  </s>
- <s>When requesting the same url multiple times</s>somtimes:
  - response.history == []
  - status code: 200

**Comment by tk0miya** [comment]
I reproduce the unicode problem with `linkcheck_anchors` option.
Indeed, `response.iter_content(decode_unicode=True)` resolves it.

But, on the other hand, I could not reproduce `UnboundLocalError` problem.
Could you show me an example URLs?

**Comment by hhsprings** [comment]
Please clone [CPython repo (mirror)](https://github.com/python/cpython), and run `make linkcheck`. This will reproduce this case immediately.

**Comment by hhsprings** [comment]
Ah, wait, wait. Your previous fix might fix this case...I'll try it.

**Comment by hhsprings** [comment]
YES. `UnboundLocalError` problem had gone :)

I'll rebase and revert this fix from #2992 .

**Comment by remyleone** [comment]
Hello I got a similar problem trying to launch the linkcheck builder on the linux kernel tree. I get the same results with both python 2.7/3.5 on last stable sphinx:

> Exception in thread Thread-4:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
>     self.run()
>   File "/usr/lib/python2.7/threading.py", line 754, in run
>     self.__target(*self.__args, **self.__kwargs)
>   File "/home/sieben/.local/lib/python2.7/site-packages/sphinx/builders/linkcheck.py", line 207, in check_thread
>     status, info, code = check()
>   File "/home/sieben/.local/lib/python2.7/site-packages/sphinx/builders/linkcheck.py", line 190, in check
>     status, info, code = check_uri()
>   File "/home/sieben/.local/lib/python2.7/site-packages/sphinx/builders/linkcheck.py", line 170, in check_uri
>     return 'redirected', new_url, code
> UnboundLocalError: local variable 'code' referenced before assignment
>

**Comment by tk0miya** [comment]
@sieben It seems your problem is same as #3552. 
If not, could you file a new issue please? This is already closed issue even if it is similar.

**Comment by remyleone** [comment]
When I've tried using the master version of sphinx I've gotten this error:

>  # Sphinx version: 1.6
>  # Python version: 2.7.12 (CPython)
>  # Docutils version: 0.13.1 release
>  # Jinja2 version: 2.9.5
>  # Last messages:
> 
> # Loaded extensions:
> Traceback (most recent call last):
>   File "/home/sieben/.local/lib/python2.7/site-packages/Sphinx-1.6.dev20170320-py2.7.egg/sphinx/cmdline.py", line 305, in main
>     opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
>   File "/home/sieben/.local/lib/python2.7/site-packages/Sphinx-1.6.dev20170320-py2.7.egg/sphinx/application.py", line 173, in __init__
>     confoverrides or {}, self.tags)
>   File "/home/sieben/.local/lib/python2.7/site-packages/Sphinx-1.6.dev20170320-py2.7.egg/sphinx/config.py", line 150, in __init__
>     execfile_(filename, config)
>   File "/home/sieben/.local/lib/python2.7/site-packages/Sphinx-1.6.dev20170320-py2.7.egg/sphinx/util/pycompat.py", line 154, in execfile_
>     exec_(code, _globals)
>   File "/home/sieben/.local/lib/python2.7/site-packages/six.py", line 699, in exec_
>     exec("""exec _code_ in _globs_, _locs_""")
>   File "<string>", line 1, in <module>
>   File "conf.py", line 20, in <module>
> ValueError: need more than 2 values to unpack
>

**Comment by tk0miya** [comment]
It seems your error is happened at your conf.py. It might be a bug of your conf.py. Could you check it please?

And, I say repeatedly, please file a NEW issue. This is closed issue.
