### ISSUE TITLE
Search index fails if index names start with -

### ISSUE THREAD

**Issue by tohojo** [sphinx-doc/sphinx#2998]
Bug #2902 still exists for search index items that start with a dash. Which is kinda unfortunate when one tries to document command line arguments by using `.. option:: --my-parameter` :)

**Comment by tk0miya** [comment]
I can't reproduce the bug. Could you tell me in detail?

```
sphinx-quickstart doc
cd doc
echo '.. option:: --my-parameter' >> index.rst
make html
touch foo.rst
make html  # => no error
```

**Comment by tohojo** [comment]
Takeshi KOMIYA notifications@github.com writes:

> I can't reproduce the bug. Could you tell me in detail?
> 
> sphinx-quickstart doc
> cd doc
> echo '.. option:: --my-parameter' >> index.rst
> make html
> touch foo.rst
> make html  # => no error

Hmm, not sure what's missing when compared with my repo. You're welcome
to try that:

git clone https://github.com/tohojo/flent.git
cd flent/doc
make html

-Toke

**Comment by hhsprings** [comment]
Do you mean this?

```
preparing documents... WARNING: search index couldn't be loaded, but not all documents will be built: the index will be incomplete.
```

If so, it occurs only when you build incrementaly, doesn't it? After editting your `options.rst`, I saw above warnings "sometimes" (unpredictably).

**Comment by tohojo** [comment]
Hiroaki Itoh notifications@github.com writes:

> Do you mean this?
> 
> preparing documents... WARNING: search index couldn't be loaded, but
> not all documents will be built: the index will be incomplete.

Yes, exactly.

> If so, it occurs only when you build incrementaly, isn't it? After
> editting your options.rst, I saw above warnings "sometimes"
> (unpredictably).

That may very well be. That was what I was doing when I got the error,
at least. Adding a - to the end of the _name_re in util/jsdump.py fixed
it. I.e. same change as in this commit:
https://github.com/sphinx-doc/sphinx/commit/acd4d9f2ba42baec9e538b6f16f18efe2e595286
but with an added dash.

-Toke

**Comment by hhsprings** [comment]
Dash is irrelevant to this issue:

```
>>> from sphinx.util.jsdump import dumps, loads
>>> dumps({"-foo": 42})  # expect: "-foo" (quoted)
'{"-foo":42}'
>>> loads(dumps({"-foo": 42}))
{'-foo': 42}
>>> dumps({"_foo": 42})  # expect: _foo (not quoted)
'{_foo:42}'
>>> loads(dumps({"_foo": 42}))
{'_foo': 42}
```

`_name_re` is for control quoting key (like `"-foo"`) <s>as valid json</s> or not (like `foo`).

**Comment by hhsprings** [comment]
I suspect that your case is similar to #3001.

To reproduce:
1. remove `_build`
2. `make html`
3. edit `options.rst`
4. `make html`
5. revert `options.rst`
6. `make html`  (error occurs unpredictably)

I'm noticing step 4 is also broken. (The warning `unkown option` may occur or not on a whim.)

**Comment by hhsprings** [comment]
Ah...maybe I understood.

#2902 was reported to sphinx-v1.4.5, and the fix had done to v1.4.7 (actually released as v1.4.8). I can reproduce above, but it was v1.4.6 which has no underscore fix.

You are using sphinx v1.4.6, aren't you? If so, updating to latest v1.4.8 is answer to your issue.

**Comment by tohojo** [comment]
Yeah, seems you're right. Can't reproduce with 1.4.8. Thanks :)

**Comment by tk0miya** [comment]
Thank you for your help @hhsprings  :-)
