### ISSUE TITLE
undefined label error since Sphinx 1.4.7 with numref to a code-block caption

### ISSUE THREAD

**Issue by jfbu** [sphinx-doc/sphinx#3012]
Consider these 

``` rst
===========
test-numref
===========

See :numref:`foo`


.. code-block:: python
   :caption: foo

   def foo():
       return None

End of file.
```

with `numfig=True` in `conf.py`.

Then 

```
index.rst:5: WARNING: undefined label: foo
```

error arises on `make html` (or  `make latex`).

Does not happen with Sphinx 1.4.6. First bad commit is 82c153ffd2965fd56f1e51fd4b960014c5e4621b which fixed https://github.com/sphinx-doc/sphinx/issues/2931

**Comment by jfbu** [comment]
I forgot to attach the zip archive of the test project.
[testnumref.zip](https://github.com/sphinx-doc/sphinx/files/511943/testnumref.zip)

**Comment by tk0miya** [comment]
Sphinx usually uses label to refer sections, tables, figures, code-blocks and so on.
But e2a921ff allows to refer code-blocks using its caption instead. That is inconsistent feature for cross reference feature of Sphinx.
Before fixing #2931, I and @shimizukawa discussed about it. And, finally he admitted his mistake in e2a921ff. And then I disabled it on #2931. 

Could you use instead label to reference the code-block? You can define it using `:name:` option.

**Comment by jfbu** [comment]
I have no issues using the `:name:` option to `code-block` directive, to define reference. It is only that I had grown used to use the possibility to use the `:caption:` for that, and the feature was available when I started using Sphinx in this way, I didn't know it had been an addition from https://github.com/sphinx-doc/sphinx/commit/e2a921ff07e87a5b157f3241f6d1fca432bd04f3. Thus I am happy to close this issue and remove the bug tag. I am all in favor of consistence for the feature of cross references. 

@tk0miya I have not checked so far, is the user documentation clear about the situation ?

**Comment by jfbu** [comment]
I am closing this issue as the documentation at http://www.sphinx-doc.org/en/stable/markup/code.html#caption-and-name does explain to use `:name:` option of `code-block`  to create reference target for `:ref:` role and possibility to use `:caption:` was only temporarily in existence.
