### ISSUE TITLE
Using Sphinx with DBus Introspection

### ISSUE THREAD

**Issue by ghost** [sphinx-doc/sphinx#3021]
Hello,

dbus introspection uses docstring xml in the class, like:

```
class TestClass(object):
   """
     <node>
        <interface name='org.test.something'>
          <method name='something'>
            <arg type='s' name='somestring' direction='in'/>
          </method>
        </interface>
      </node>
   """
```

Trying to build the docs here seems to freeze sphinx or something after reading the sources. Is there a way to still document such classes with Sphinx?

**Comment by tk0miya** [comment]
What did you mean "freeze"?
At my local, I can build the docs including the class.

```
# index.rst

.. automodule:: example
   :members:
```

But sphinx expects that the docstrings are written by reST. So the docstring of TestClass is recognized as definition list (`<dl>` in HTML).
I don't know good way to do that. The adhoc way only I know is writting an extension to wrap the XML by code-block directive.

**Comment by ghost** [comment]
With freeze i mean, after generating everything with sphinx-quickstart and sphinx-apidoc -f -o source/ ../mypackage/, when i try to build the docs with a mingw console, following output is generated :

```
$ cmd //c make.bat html
Running Sphinx v1.4.8
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 3 source files that are out of date
updating environment: 3 added, 0 changed, 0 removed
reading sources... [100%] mypackage
```

From there nothing happens anymore and there is no htmls generated. I have to abort with ctrl+C.
BUT I found the cause. These lines which are also in the python module seem to make trouble (maybe because of the glib main loop?):

```
# start routine
loop = GObject.MainLoop()
bus = SessionBus()
bus.publish("de.test", TestClass())
loop.run()
```

**Comment by tk0miya** [comment]
Okay, I understand.
automodule imports your modules to obtain the docstring.
As a result, automodule invokes the glib main loop.

Please enclosure `if __name__ == '__main__':` block to prevent to invoke your script on importing.

This is described at the document of autodoc. Please read it again:
http://www.sphinx-doc.org/en/stable/ext/autodoc.html
