### ISSUE TITLE
is the documentation of ``documentclass`` element from ``latex_documents`` correct ?

### ISSUE THREAD

**Issue by jfbu** [sphinx-doc/sphinx#3035]
It says:

> documentclass: Normally, one of 'manual' or 'howto' (provided by Sphinx). Other document classes can be given, but they must include the “sphinx” package in order to define Sphinx’s custom LaTeX commands.

But it seems  `\usepackage{sphinx}` is always included.

For example if if I use `'memoir'` as fifth element to `latex_documents`, the produced LaTeX will use `memoir` as document class but also will do `\usepackage{sphinx}`.

**Comment by tk0miya** [comment]
Right. The `sphinx` package is always loaded even if other documentclasses are used.
The description should be updated...

**Comment by jfbu** [comment]
ok, donc at daee1fc, thanks!

**Comment by tk0miya** [comment]
good!
