### ISSUE TITLE
got an unexpected keyword argument 'align'

### ISSUE THREAD

**Issue by simonyangcj** [sphinx-doc/sphinx#3036]
hi guys,I got an error it says  " an unexpected keyword argument 'align' " when I run following command:

`sphinx-build -E -W -d doc/install-guide/build-obs/html.doctrees -b html -t obs doc/install-guide/source doc/install-guide/build-obs/html`
1. system: Mac OS
2. sphinx version: 1.4.8

Following is the error log:

> # Sphinx version: 1.4.8
> # Python version: 2.7.10 (CPython)
> # Docutils version: 0.12 release
> # Jinja2 version: 2.8
> # Last messages:
> #   reading sources... [ 89%] neutron-verify
> #   reading sources... [ 91%] neutron-verify-option1
> #   reading sources... [ 92%] neutron-verify-option2
> #   reading sources... [ 94%] nova
> #   reading sources... [ 95%] nova-compute-install
> #   reading sources... [ 97%] nova-controller-install
> #   reading sources... [ 98%] nova-verify
> #   reading sources... [100%] overview
> #
> #   adding watermark...
> # Loaded extensions:
> #   alabaster (0.7.9) from /Library/Python/2.7/site-packages/alabaster/**init**.pyc
> #   sphinxmark (0.1) from /Library/Python/2.7/site-packages/sphinxmark/**init**.pyc
> Traceback (most recent call last):
>   File "/Library/Python/2.7/site-packages/sphinx/cmdline.py", line 244, in main
>     app.build(opts.force_all, filenames)
>   File "/Library/Python/2.7/site-packages/sphinx/application.py", line 297, in build
>     self.builder.build_update()
>   File "/Library/Python/2.7/site-packages/sphinx/builders/**init**.py", line 251, in build_update
>     'out of date' % len(to_build))

Please help.
Many thx :)

**Comment by tk0miya** [comment]
It seems the error log you pasted is not full version.
It does not include most important part...
Could you paste it again please?

**Comment by simonyangcj** [comment]
thanks @tk0miya please see below:

> # Sphinx version: 1.4.8
> # Python version: 2.7.10 (CPython)
> # Docutils version: 0.12 release
> # Jinja2 version: 2.8
> # Last messages:
> #   reading sources... [ 89%] neutron-verify
> #   reading sources... [ 91%] neutron-verify-option1
> #   reading sources... [ 92%] neutron-verify-option2
> #   reading sources... [ 94%] nova
> #   reading sources... [ 95%] nova-compute-install
> #   reading sources... [ 97%] nova-controller-install
> #   reading sources... [ 98%] nova-verify
> #   reading sources... [100%] overview
> #  
> #   adding watermark...
> # Loaded extensions:
> #   alabaster (0.7.9) from /Library/Python/2.7/site-packages/alabaster/**init**.pyc
> #   sphinxmark (0.1) from /Library/Python/2.7/site-packages/sphinxmark/**init**.pyc
> Traceback (most recent call last):
>   File "/Library/Python/2.7/site-packages/sphinx/cmdline.py", line 244, in main
>     app.build(opts.force_all, filenames)
>   File "/Library/Python/2.7/site-packages/sphinx/application.py", line 297, in build
>     self.builder.build_update()
>   File "/Library/Python/2.7/site-packages/sphinx/builders/**init**.py", line 251, in build_update
>     'out of date' % len(to_build))
>   File "/Library/Python/2.7/site-packages/sphinx/builders/**init**.py", line 265, in build
>     self.doctreedir, self.app))
>   File "/Library/Python/2.7/site-packages/sphinx/environment.py", line 577, in update
>     for retval in app.emit('env-updated', self):
>   File "/Library/Python/2.7/site-packages/sphinx/application.py", line 551, in emit
>     results.append(callback(self, *args))
>   File "/Library/Python/2.7/site-packages/sphinxmark/**init**.py", line 152, in watermark
>     buildpath, imagefile = getimage(app, env)
>   File "/Library/Python/2.7/site-packages/sphinxmark/**init**.py", line 121, in getimage
>     imagefile = createimage(app, srcdir, buildpath)
>   File "/Library/Python/2.7/site-packages/sphinxmark/**init**.py", line 85, in createimage
>     d.text((x, y), text, font=font, fill=color, align="center")
> TypeError: text() got an unexpected keyword argument 'align'

**Comment by tk0miya** [comment]
> File "/Library/Python/2.7/site-packages/sphinxmark/init.py", line 85, in createimage
> d.text((x, y), text, font=font, fill=color, align="center")

It seems the error comes from sphinxmark extension.
Please report this to their project.

**Comment by simonyangcj** [comment]
@tk0miya thx :) I guess I will do a upgrade first.
