### ISSUE TITLE
Enable one-folder built for html-pages

### ISSUE THREAD

**Issue by MMKrell** [sphinx-doc/sphinx#3041]
As long as #2193 was not active, it was possible to have source file and html file in the same folder which I found very convenient. Obvisously for large projects it is insane and I am well aware of the large number of documents that would mess up in this case. But for small projects as my CV, I think it should be possible to use the same folder. Shouldn't it? For github the main directory should contain the webpage and I think also the main documents.

https://github.com/MMKrell/CV/tree/gh-pages

**Comment by tk0miya** [comment]
As I said at #2193, Sphinx is not designed to support same folder.
AFAIK, many changes are needed to do that.
So we need to discuss about advantage of that.
At this moment, it seems not important to me.

**Comment by MMKrell** [comment]
For me the advantage is that if you use gh-pages, the index.html has to be in the main folder. If you have a very small project like the CV, you can have all relevant files in one folder and nothing will mess up.

**Comment by tk0miya** [comment]
Now gh-pages support `/docs` directory on master branch.
I recommend it instead.

Anyway, PRs are always welcomed. If you interest to support that, please send us PRs.
