### ISSUE TITLE
Sphinx 1.4.8 fails to build python-matplotlib docs

### ISSUE THREAD

**Issue by daym** [sphinx-doc/sphinx#3044]
Hi,

Sphinx 1.4.8 fails to build matplotlib 1.4.3 docs due to latex complaining about "\footnote[*]" at Matplotlib.tex:171. If I manually change it to "\footnote[1]" it works. The file Matplotlib.tex was generated by Sphinx LaTeX writer.

Is this a problem in LaTeX or Sphinx? Should "\footnote[*]" work?

**Comment by jfbu** [comment]
`\footnote[*]` is not expected and it is normal LaTeX complains about it. Do you have `latex_show_urls = 'footnote'` in conf.py ? (asking to restrict scope...)

**Comment by jfbu** [comment]
do you mean matplotlib 1.4.3 or 1.5.3 ? I see on http://matplotlib.org/contents.html that current is 1.5.3. Which version of Sphinx compiled it successfully ?

**Comment by jfbu** [comment]
ah ok I see Sphinx 1.4.6 at bottom of page.

**Comment by jfbu** [comment]
not much has changed between 1.4.6 and 1.4.8 which could be relevant. The `sphinx.sty`has a single change unrelated to footnotes and the `latex.py` also a single change not immediately related to footnotes.

**Comment by daym** [comment]
> Do you have latex_show_urls = 'footnote' in conf.py ? (asking to restrict scope...)

No, there's no latex_show_urls in conf.py .

matplotlib built successfully using sphinx 1.2.3. 

I'm trying to update the sphinx package in the Guix distribution (I'm writing the package definition) and rebuilding the world brought up matplotlib.

(I'll try the github release https://github.com/matplotlib/matplotlib/archive/v1.5.3.tar.gz next)

**Comment by jfbu** [comment]
I will git clone matplotlib but it takes time ;-) I will see later but README says there is a dependency on colorspacious and

```
$ anaconda search -t conda colorspacious
Using Anaconda API: https://api.anaconda.org
Run 'anaconda show <USER/PACKAGE>' to get more details:
Packages:
     Name                      |  Version | Package Types   | Platforms      
     ------------------------- |   ------ | --------------- | ---------------
     endolith/colorspacious    |    0.1.0 | conda           | win-64         
                                          : A powerful, accurate, and easy-to-use Python library for doing colorspace conversions
     karenfeyen/colorspacious  |    1.0.0 | conda           | win-64         
                                          : A powerful, accurate, and easy-to-use Python library for doing colorspace conversions
Found 2 packages
```

proposes only win-64 packages, I guess I need to pip install then.

**Comment by jfbu** [comment]
I have git clone matplotlib, installed dependencies, move to doc/ repertory and run `python make latex` in an environment with Sphinx 1.4.8. There are many warnings from the build but the tex file is produced. Then the pdflatex produces only errors of the following type:

```
./Matplotlib.tex:4599: Package inputenc Error: Unicode char 思 (U+601D)
(inputenc)                not set up for use with LaTeX.

See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              

l.4599 ...ExtraLight,Source Han Sans TW ExtraLight
```

and the tex file contains no `\footnote[*` or `\footnote [*`.

Done with latest matplotlib, not with 1.5.3. I will launch with 1.5.3. now.
I get no other errors.

**Comment by jfbu** [comment]
Full log at https://gist.github.com/jfbu/fe934ac50565ed28144f6f59c11da528

**Comment by jfbu** [comment]
ok I confirm there issue with 1.5.3 and Sphinx 1.4.8.

```
[4]
Chapter 2.
(/usr/local/texlive/2016/texmf-dist/tex/latex/txfonts/ts1txtt.fd) [5] [6]
[7] [8]
Chapter 3.
(/usr/local/texlive/2016/texmf-dist/tex/latex/txfonts/ts1txr.fd)
! Missing number, treated as zero.
<to be read again> 
                   *
l.202 the MATLAB® \footnote[*]
                               {\sphinxAtStartFootnote%
? 
```

I will investigate later, I don't have much time today. Good news is that more recent matplotlib doc doesn't have that error anymore.

**Comment by jfbu** [comment]
File `doc/users/intro.rst` has

``` rst
Introduction
============

matplotlib is a library for making 2D plots of arrays in `Python
<http://www.python.org>`_.  Although it has its origins in emulating
the MATLAB |reg| [*]_ graphics commands, it is
independent of MATLAB, and can be used in a Pythonic, object oriented
way.  Although matplotlib is written primarily in pure Python, it
makes heavy use of `NumPy <http://www.numpy.org>`_ and other extension
code to provide good performance even for large arrays.
```

I guess 

```
 MATLAB |reg| [#]_ graphics commands
```

was meant for auto-numbered footnotes. This is an reST markup error.

**Comment by jfbu** [comment]
I confirm after fixing the `[*]` in the matplotlib doc sources that make latex works

```
Output written on Matplotlib.pdf (2808 pages, 38408230 bytes).
Transcript written on Matplotlib.log.
```

But matplotlib developers should be alerted about the problem with asiatic characters in current master branch.

**Comment by jfbu** [comment]
forgot to say that if using `[#]_` then the 

```
.. [*] MATLAB is a registered trademark of The MathWorks, Inc.
```

at bottom of document must be corrected to 

```
.. [#] MATLAB is a registered trademark of The MathWorks, Inc.
```

**Comment by daym** [comment]
Thanks for the investigation! I'm not really knowledgeable in texinfo. What exactly should I patch? The bottom of the document to .. [#] MATLAB is a registered trademark of The MathWorks, Inc. - okay. 

What do I write instead of MATLAB |reg| [*]_ ?

**Comment by jfbu** [comment]
> What do I write instead of MATLAB |reg| [*]_ ?

```
MATLAB |reg| [#]_ 
```

The `[#]_` tell Sphinx to auto-number the footnote. To match the `[#]_` you need the corresponding `.. [#]` at bottom of  `doc/users/intro.rst`.

Thus the patch consists exactly in replacing the two `*` by two `#` in file `doc/users/intro.rst`. I will now close this issue as it is not a Sphinx problem. Thanks for reporting !
