### ISSUE TITLE
Cross referencing breaks for inherited objects imported and documented in a parent module

### ISSUE THREAD

**Issue by anjos** [sphinx-doc/sphinx#3048]
I'm trying to get my Sphinx documentation build correctly and have cross-references (including those from inherited relations) work right.

In my project, I have a situation which is depicted in the example below, which I replicated for convenience on [this github repo](https://github.com/anjos/sphinx-broken-xref):

``` sh
$ tree .
.
├── a
│   ├── b
│   │   └── __init__.py
│   └── __init__.py
├── conf.py
├── index.rst
└── README.md
```

In `a.b.__init__`, I declare classes `A` and `B`. `B` inherits from `A`. In `a.__init__`, I import `A` and `B` like: `from .b import A, B`. The reason I do this in my real projects is to reduce the import paths on modules while keeping implementation of specific classes in separate files.

Then, in my rst files, I _autodoc_ module `a` with `.. automodule:: a`. Because `a.b` is just an auxiliary module, I don't _autodoc_ it since I don't want to get repeated references to the same classes and not to confuse the user on what they should be really doing. I also set `show-inheritance` expecting `a.B` will have a back link to `a.A`.

If I try to sphinx-build this in nit-picky mode, I'll get the following warning:

``` sh
WARNING: py:class reference target not found: a.b.A
```

If I look at the generated documentation for class `B`, then I verify it is not properly linked against class `A`, which just confirms the warning above.

Is there a fix for this?

[1] http://stackoverflow.com/questions/40018681/sphinx-cross-referencing-breaks-for-inherited-objects-imported-and-documented-in
[2] https://github.com/anjos/sphinx-broken-xref

**Comment by anjos** [comment]
Apparently, the solution is to reset the value of `__module__` on the affected classes. So, in `a/__init__.py`, you can do the following to fix the issue:

``` python
A.__module__ = __name__
B.__module__ = __name__
```

Closing this issue now.

**Comment by 183amir** [comment]
Is that a solution or a workaround?

**Comment by anjos** [comment]
I don't think Sphinx can do any better that asking the object where it is and trying to cross-reference from there. So, IMO this is a solution to this issue. Another solution would be if `py:foo` clauses accepted a `:alias:` parameter that allowed us to specify this class is an alias from another one, making sphinx also look in there for a resolution. I'll leave to this community to debate and decide. I have not inside knowledge in Sphinx and if this other solution would bring an undesired side-effect.

**Comment by 183amir** [comment]
I wonder how other libraries like `xarray` don't have to do this. For example `xarray.Dataset` is actually implemented in another file and is imported in the main module (https://github.com/pydata/xarray/blob/bd84186acbd84bd386134a5b60111596cee2d8ec/xarray/__init__.py#L23) but its documentation shows up correctly as `xarray.Dataset` in https://xarray.pydata.org/en/stable/generated/xarray.Dataset.html#xarray.Dataset
