### ISSUE TITLE
Explicit comment markup

### ISSUE THREAD

**Issue by HFriberg-mosek** [sphinx-doc/sphinx#3053]
Currently in Sphinx:
"Every explicit markup block which isn’t a valid markup construct is regarded as a comment", from the reStructuredText Primer.

This leaves me vulnerable to a long range of typos which goes undetected as being comments, such as
.. incude:: inclusion.txt
.. include: inclusion.txt

Can we please get an explicit syntax for making comments, such as:
.. comment:: This is a comment

and the possibility in conf.py to only allow comments on this form, such as:
explicit_comments = True  (with default value False for backwards compatibility..)

**Comment by tk0miya** [comment]
It seems this is expansion of reST syntax.  Please report this to docutils project.

Now sphinx uses docutils as a parser of reST.
So to expand syntax is very hard from sphinx side.

BTW, you can write a comment linter as a Sphinx extension.
It might help you.

**Comment by HFriberg-mosek** [comment]
I wrote this simple extension and it helped me identify 12 cases of faulty directive syntax in our codebase. But I understand your point @tk0miya, it may more apparent as a docutils feature.

```
from docutils import nodes
from docutils.parsers.rst import Directive

class Comment(Directive):
    has_content = True
    def run(self, *args):
        return []

def warn_implicit_comment(app, doctree):
    if app.env.config.warn_implicit_comment:
        for node in doctree.traverse(nodes.comment):
            app.env.warn_node("Implicit comment found. Use 'comment' directive to make explicit.", node)

def setup(app):
    app.add_directive('comment', Comment)
    app.add_config_value('warn_implicit_comment', False, 'env')
    app.connect('doctree-read', warn_implicit_comment)
    
    return {'parallel_read_safe': True}
```
