### ISSUE TITLE
document isn't included in any toctree

### ISSUE THREAD

**Issue by riddle911** [sphinx-doc/sphinx#3054]
The Problem comes with this warning when making, and the code is as follows:

```
.. toctree::
    :maxdepth: 1

[site wiki="copter"]
    Tuning <common-tuning>
    Compass Setup (Advanced) <common-compass-setup-advanced>
    UBlox GPS Configuration <common-ublox-gps>
    Parameter Reset <common-parameter-reset>
    Auxiliary Function Switches <channel-7-and-8-options>
    Vibration Damping <common-vibration-damping>
    Current Limiting and Voltage Scaling <current-limiting-and-voltage-scaling>
    RCMAP <common-rcmap>
    Sensor Testing <common-sensor-testing>
    Telemetry Port Setup <common-telemetry-port-setup-for-apm-px4-and-pixhawk>
    Magnetic Interference <common-magnetic-interference>
    Full Parameter List <parameters>
[/site]
```

The warning shows that
`../source/docs/common-advanced-configuration.rst:: WARNING: document isn't included in any toctree`
you can see my page at here `http://wiki.osdrone.net/copter/docs/common-advanced-configuration.html`

I did Google it for the whole night, but it doesn't work. May you guys could help me with it.

**Comment by tk0miya** [comment]
Surely, it seems `common-advanced-configuration` is not included the toctree.
If not intended, please add it to your toctree.

Thanks,

**Comment by riddle911** [comment]
Yeah I know the toctree need contain those missing files, and I checked I have put the files in the toctree. But it seems that sphinx cannot recognize it which really make me confused.

**Comment by tk0miya** [comment]
Could you give me a reproducible example?
I can't understand your problem yet.

**Comment by riddle911** [comment]
I'm sorry that I am on a business trip that I cannot reply your message immediately.
Well my example is in my repo of riddle911/ardupilot_wiki. When I run the make, It always comes up with the above mistake.
I don't mean to offend you, but I wonder if you can log on my vps to have a try and see what's go ing on with the toctree.

**Comment by tk0miya** [comment]
I was looking your repos today, your repos includes many sphinx projects.
So I can't reproduce the problem.

Anyway, `WARNING: document isn't included in any toctree` messages means that the document is not included in your toctree.
But this warning does not prevent building HTML. so `common-advanced-configuration.html` has built, but it is not included in your table of contents (ToC) of your document.

>I don't mean to offend you, but I wonder if you can log on my vps to have a try and see what's go ing on with the toctree.

Sorry. I'm not a user support of Sphinx.
So settings of VPS is not needed.

**Comment by riddle911** [comment]
All right. Many thanks. I need to do mork work.
