### ISSUE TITLE
Using the same 'caption' attribute in multiple 'toctree' directives results in warning / error

### ISSUE THREAD

**Issue by stefanseefeld** [sphinx-doc/sphinx#3058]
In a document hierarchy I'm writing I have multiple 'index.rst' files (one per subdirectory). Each contains a toctree like

```
.. toctree::
   :caption: Table of Contents
   :maxdepth: 2

  ...
```

The toplevel one includes the nested ones as

```
.. toctree::
   :caption: Table of Contents
   :maxdepth: 2

   Tutorial <tutorial/index>
   Reference <reference/index>
```

This results in the warning

`.../reference/index.rst:None: WARNING: duplicate label table of contents, other instance in .../index.rst`

The reason appears to be that the ":caption:" option is translated into an "id" attribute in the generated html, which then eventually conflict as they aren't unique.

Using a "caption" verbatim for an "id" sounds quite dangerous to me in any case, so I'd suggest to change that. At least I see no reason why ":caption:" values should have to be unique in a document set, while for "id"s such a requirement makes sense.

**Comment by tk0miya** [comment]
Thank you for reporting. completely I agree with you.
Fixed at 4411f67.
