### ISSUE TITLE
UnpicklingError: NEWOBJ class argument isn't a type object

### ISSUE THREAD

**Issue by aqing1987** [sphinx-doc/sphinx#3063]
when I do 
 /usr/ports/editors/vim# make WITHOUT_X11=yes install clean
# issue below occur:

Exception occurred:
  File "/usr/local/lib/python2.7/site-packages/sphinx/environment.py", line 1261, in get_doctree
    doctree = pickle.load(f)
UnpicklingError: NEWOBJ class argument isn't a type object
# The full traceback has been saved in /tmp/sphinx-err-Znb2Nz.log, if you want to report the issue to the developers.

[sphinx-err-Znb2Nz.txt](https://github.com/sphinx-doc/sphinx/files/538053/sphinx-err-Znb2Nz.txt)

**Comment by shimizukawa** [comment]
@aqing1987 please try redo "make ...".
Actually, I don't know what is the "NEWOBJ". I think it relates to target document. Please let us know what sphinx document are you building?

**Comment by aqing1987** [comment]
hi, i am building vim in freebsd ports style, as mentioned above:
/usr/ports/editors/vim# make WITHOUT_X11=yes install clean

**Comment by shimizukawa** [comment]
@aqing1987 thanks. I think there is nothing to do from Sphinx side because it might be a issue of vim ports. Please report to maintainer of FreeBSD vim ports.
