### ISSUE TITLE
Nested classes break contextual qualifying

### ISSUE THREAD

**Issue by obskyr** [sphinx-doc/sphinx#3065]
If you nest one class inside another (which is something that occurs fairly frequently in code), all subsequent members of the parent class will be superfluously qualified.

Using this input:

``` rst
.. class:: Parent()

    .. class:: Parent.Child1()
    .. class:: Parent.Child2()
    .. method:: Parent.method()
```

The output looks like this:
![wrong](https://cloud.githubusercontent.com/assets/4363779/19526915/4767131c-9626-11e6-8187-0b6a636771b7.png)

When it should look like this:
![right](https://cloud.githubusercontent.com/assets/4363779/19526930/54ef58be-9626-11e6-8a3b-b0c0447e2230.png)

This is due to the fact that class context is handled as a single value, and not a stack that goes deeper as another class is entered. When exiting the first class, the class context is set to not being inside a class anymore, and the following children are therefore qualified as they think they're on the top level. This is also touched upon in the discussion for #2665.

Pull request incoming shortly!

Pull request to fix this incoming shortly.

**Comment by tk0miya** [comment]
Fixed by #3520.
