### ISSUE TITLE
warning directive puts contents below title in html but not in LaTeX

### ISSUE THREAD

**Issue by jfbu** [sphinx-doc/sphinx#3073]
I won't pretend that this is real issue but with

``` rst
Hello
=====


Section
-------

.. warning::

   Attention!

```

the html looks like this

![capture du 2016-10-20 16-15-16](https://cloud.githubusercontent.com/assets/2589111/19563550/ad29d53a-96e0-11e6-82cc-5b8d9fc451d9.png)

and the pdf like this

![capture du 2016-10-20 16-14-48](https://cloud.githubusercontent.com/assets/2589111/19563556/b3edd4fc-96e0-11e6-983d-2a438d05cde0.png)

Naturally the styling differs, but my issue is about the directive contents starting on the same line as the `Warning:` title in LaTeX contrarily to PDF. In case of multi-paragraph, this is a bit disturbing.

**Comment by jfbu** [comment]
closing this because the LaTeX style is actually fine if contents of the warning type admonition is one-paragraph only, which is usually the case.

**Comment by tk0miya** [comment]
Note: With `classic` theme, the contents start at right of `Warning:` title.
It's representation of each theme.
![2016-10-27 21 01 12](https://cloud.githubusercontent.com/assets/748828/19766510/47f79e3c-9c89-11e6-8f06-07de0f8a90c0.png)
