### ISSUE TITLE
Bug. ValueError: too many values to unpack

### ISSUE THREAD

**Issue by madydady** [sphinx-doc/sphinx#3075]
I have updated Sphinx to version 1.4.8. I used version 1.3 before that and everything was ok while generating HTML output. 

Now, when i run "make.bat html" in a Windows console i got an exeption:

File "D:\Git\DocsJob_themes\basicplus\genindex.html", line 39, in block "body"
    {%- for entryname, (links, subitems) in entries -%}
ValueError: too many values to unpack

Above it is an entry from a log file

basicplus is a modified basic theme that i use and when i worked with previous Sphinx version it was ok

Here what is written in my genindex.html file

```
{%- for key, entries in genindexentries %}
<h2 id="{{ key }}">{{ key }}</h2>
<table style="width: 100%" class="indextable genindextable"><tr>
  {%- for column in entries|slice(2) if column %}
  <td style="width: 33%" valign="top"><dl>
    {%- for entryname, (links, subitems) in column %}
      {{ indexentries(entryname, links) }}
      {%- if subitems %}
      <dd><dl>
      {%- for subentryname, subentrylinks in subitems %}
        {{ indexentries(subentryname, subentrylinks) }}
      {%- endfor %}
      </dl></dd>
      {%- endif -%}
    {%- endfor %}
  </dl></td>
  {%- endfor %}
</tr></table>
{% endfor %}
```

I also tried to use html5_basic theme instead (https://pypi.python.org/pypi/sphinx_html5_basic_theme)

But i ve got the same problem

  File "D:\sphinx_themes\html5_basic\genindex.html", line 39, in block "body"
    {%- for entryname, (links, subitems) in entries -%}
ValueError: too many values to unpack

So can you tell me is it a Bug or what? And how can i fix it myself without waiting for a new Sphinx update?

**Comment by davidcarroll** [comment]
Just wanted to report, that I have this same issue too.

**Comment by ThomasLecocq** [comment]
same problem for me, but solved https://github.com/rst2pdf/rst2pdf/issues/568 here

**Comment by tk0miya** [comment]
Sorry for late response and inconvenience.

This is incompatible change since 1.4 (see #2320).
After the change, the `entries` was changed to a list of `entryname, (links, subitems, key)`.

AFAIK, there were no migration path. So could you update your theme please?

Thanks,

**Comment by tk0miya** [comment]
I'm closing this now.
Thanks,
