### ISSUE TITLE
bug with adding multiple .rst files to source

### ISSUE THREAD

**Issue by natemwilson** [sphinx-doc/sphinx#3076]
When I only have a single .rst file, index.rst, everything works fine.

But, when I add any other file, while I am using Sphinx 1.4.8 and Python 3.5.2, and try and run a make html, I get the following error:

```
Exception occurred:
  File "/Users/johndoe/miniconda3/envs/env1/lib/python3.5/site-packages/docutils/io.py", line 236, in __init__
    self.source = open(source_path, mode, **kwargs)
DeprecationWarning: 'U' mode is deprecated
The full traceback has been saved in /var/folders/xd/nfvsb81d155d0gzr5vcwfksh0000gp/T/sphinx-err-p2g44cw2.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [html] Error 1
```

What is weird though is that I can solve this issue and get successful builds by simply using an environment with Sphinx 1.3.1 and Python 3.3.5, so it leads me to believe that the newest release of sphinx has some issue.

**Comment by mihaic** [comment]
@natemwilson You should probably close this issue considering our email discussion.
