### ISSUE TITLE
texinfo Makefile not installing images into infodir

### ISSUE THREAD

**Issue by mantepse** [sphinx-doc/sphinx#3079]
I am trying to produce texinfo documentation for sagemath, which uses sphinx, see  https://trac.sagemath.org/ticket/21734.

The `Makefile` in `texinfo.py` has the following target:

```
install-info: info
\tfor f in *.info; do \\
\t  cp -t $(infodir) "$$f" && \\
\t  $(INSTALL_INFO) --info-dir=$(infodir) "$$f" ; \\
\tdone
```

It appears to me, that this doesn't copy the supported images, as initialized here:

```
class TexinfoBuilder(Builder):
    """
    Builds Texinfo output to create Info documentation.
    """
    name = 'texinfo'
    format = 'texinfo'
    supported_image_types = ['image/png', 'image/jpeg',
                             'image/gif']
```

Is my expectation wrong, or is this a bug?  In either case, how do I fix it?  (because, indeed, the info reader cannot find the pictures...)

**Comment by tk0miya** [comment]
I'll take a look later.

**Comment by tk0miya** [comment]
Note: The texinfo manual says:

>If you want to install image files for use by Info readers too, we recommend putting them in a subdirectory like ‘foo-figures’ for a package foo. Copying the files into $(infodir)/foo-figures/ should be done in your Makefile.
>https://www.gnu.org/software/texinfo/manual/texinfo/html_node/Image-Syntax.html

So it would be better to copy image files to `{proj}-figures` directory

**Comment by tk0miya** [comment]
I just posted #6123 to fix this. But I'm not good at texinfo system. Could you check the PR please?
Thanks,

**Comment by tk0miya** [comment]
I merge #6123 now. Please check it in HEAD of 2.0 branch or next release.
Thanks,

**Comment by mantepse** [comment]
Dear @tk0miya, I'm afraid I won't be able to check anytime soon, because sagemath is still using an older sphinx, the upgrade seems non-trivial, and the incentive is small because of #3089.

**Comment by mantepse** [comment]
Still, I am grateful for your work on this!
