### ISSUE TITLE
Overly eager "Highlighting skipped" with Pygments

### ISSUE THREAD

**Issue by other-mickk** [sphinx-doc/sphinx#3088]
This is for HTML output with Pygments in charge of the highlighting.

I sometimes like to write pseudo-code examples in my documentation, e.g. for C++:

``` cpp
    auto result = my_documented_function(a, b, c, …);
```

In this instance Pygments correctly identifies the ellipsis ('…') as invalid C++. Because Sphinx sets the [`raiseonerror` filter](https://github.com/sphinx-doc/sphinx/blob/d0dbd60d94d825d4c92c3e42e2ea0cf49b5b0f70/sphinx/highlighting.py#L128) on the lexer, this raises an exception at which point Sphinx decides to give up on highlighting the block.

(Now I could use three periods ('...') instead of a literal ellipsis and Pygments would not complain. On the other hand it likely doesn't complain because three dots can be a token in C++, so that's mostly coincidental—other forms of pseudo-code could be rejected by Pygments as well. Perhaps more importantly, it's particularly _because_ three periods can be valid C++ that I would rather use something which obviously stands out, especially in a monospaced font: that makes it clear which part is pseudo-code.)

Sphinx does have `highlight_options` in the config to customise the behaviour of the Pygments lexer to an extent. Unfortunately, this doesn’t give control over filters or what Sphinx does with the lexer (i.e. later setting `raiseonerror`).

If I tweak Sphinx to not set the filter, Pygments classifies the parts of the code it doesn’t understand as errors but otherwise goes on its business and highlights the rest as expected. With stock styling those errors are rendered in a very visible manner, but I can also customise the styling so that they appear as normal code. These two hacks together give me the behaviour I want.

What's the correct course of action here:
- Push the problem upstream so that Pygments comes with a lexer that does what I need. I think there's a precedent here with e.g. `PythonConsoleLexer`. On the other hand if every `LanguageParser` had a `PseudoLanguageParser` that could grow out of hand
- Push upstream for Pygments to make it possible to pass filters in the lexer constructors, so that a Sphinx user can use `highlight_options` to customise lexer behaviour. The current `raiseonerror` behaviour would be kept by giving `highlight_options` an appropriate default value.
- Let Sphinx expose more Pygments internals, e.g. a `highlight_filter_options` so that users can choose which filters are applied.
- Together with one of the above, ask upstream for some sort of `ignoreerror` filter as an opposite to `raiseonerror` so that bits which Pygments doesn't understand are _not_ marked as errors. This spares the user from using style hacks.

or else do nothing or something else entirely.

**Comment by tk0miya** [comment]
Finally, we choose the "force" option for code directives (refs: https://github.com/sphinx-doc/sphinx/pull/2310, https://github.com/sphinx-doc/sphinx/pull/6416). So I believe this was already resolved.
