### ISSUE TITLE
texinfo external references

### ISSUE THREAD

**Issue by mantepse** [sphinx-doc/sphinx#3089]
when compiling a texinfo reference manual for sagemath, I have many references of the form

```
:class:`~sage.structure.factory.UniqueFactory`
```

which are translated into a node of the form

```
<reference internal="False" reftitle="(in Sage Reference Manual: Basic Structures v7.4)" refuri="../../../../../../html/en/reference/structure/sage/structure/factory.html#sage.structure.factory.UniqueFactory"><literal classes="xref py py-class">UniqueFactory</literal></reference>
```

Since they are really part of the same project, I'd like to turn them into proper references.  In `builders/texinfo.py` I found the note:

```
 # TODO: add support for external :ref:s
```

Is this what I would have to do?  It's not quite clear to me yet what an internal and what an external reference really is...

**Comment by tk0miya** [comment]
Really the class you referred is defined in same project?
In sage project, the document sets up `intersphinx` to reference.
https://github.com/sagemath/sage/blob/master/src/doc/common/conf.py#L119

Anyway, the reference of sagemath is too complicated for me.
Could you give me a simple project?

**Comment by mantepse** [comment]
Thanks for looking into this!

> Really the class you referred is defined in same project?

Yes, the same project but a different module, in a different directory.  As far as I know (but my knowledge is incomplete :-), the documentation of sage is structured by the directory tree below `src/sage/doc`.  In each sub(sub...sub)directory there is a `conf.py`, and there is also a `common/conf.py` which seems to provide defaults for everything.

For each sub(sub...sub)directoy with a `conf.py`, sphinx builds one manual.  References within one manual work fine.

For references to other manuals, `intersphinx` is used, as you remarked above.  However, this is currently designed with html references in mind.  I want to add texinfo references.

Meanwhile, I figured out that the important place for me seems to be the call

```
app.connect('missing-reference', find_sage_dangling_links).
```

in line 787.  (I have no clue what the class `app` is.  Maybe this is part of my problem.  Does it depend on the builder, and if so, how?)  So, if I understand correctly, the function defined by

```
def find_sage_dangling_links(app, env, node, contnode):
```

is called by sphinx, whenever a reference is not in the same manual.  This in turn mostly calls

```
def call_intersphinx(app, env, node, contnode):
```

in line 608 of the same file.

So, my question is: what should  `find_sage_dangling_links` return, so it works for both html and texinfo?

**Comment by tk0miya** [comment]
Sorry, I can't understand the structure of sagemath project yet.
Why does it use intersphinx to resolve references?
It is not needed if all modules are in same project as you said.

BTW, `intersphinx` extension generates "external" reference node like following:

```
            newnode = nodes.reference('', '', internal=False, refuri=uri,
                                      reftitle=_('(in %s v%s)') % (proj, version))
```

I feel the reference node which you reported first is very similar to the node intersphinx generates (for example, format of reftitle attribute).

> So, my question is: what should find_sage_dangling_links return, so it works for both html and texinfo?

The texinfo builder says it does not support external references yet as you pointed.
So it would be rendered correctly if `find_sage_dangling_links` returns _internal_ references.

(Sorry I'm not good at texinfo builder)

**Comment by mantepse** [comment]
> Sorry, I can't understand the structure of sagemath project yet.

I don't understand it either :-(

> Why does it use intersphinx to resolve references?

I think because the documentation is built separately for each subdirectory.  (note that sage is huge)

> It is not needed if all modules are in same project as you said.

So, for sphinx, what is "one project"?

**Comment by tk0miya** [comment]
Sorry for late response.

>So, for sphinx, what is "one project"?

AFAIK, it means the set of documents (*.rst files), config files and files related the document.
In this case, it is described as the documents built in once.

**Comment by tk0miya** [comment]
It seems the document of sagemath are consist of multiple Sphinx projects. So this is expected behavior.
I think it is hard to support intersphinx on texinfo builder. So I'd like to close this.

@shimizukawa any ideas?

**Comment by mantepse** [comment]
I'd just like to mention that I'm still very (very!) interested in a solution and also willing to spend some time on it.  Just notify me here if you have any questions or any suggestion on how to proceed.

Martin

**Comment by shimizukawa** [comment]
I do not know how to handle external links with texinfo. So, +1 to close this issue.

**Comment by mantepse** [comment]
Might there be a workaround?

**Comment by tk0miya** [comment]
Please integrate your project into single one.

**Comment by tk0miya** [comment]
I believe there is nothing to do from Sphinx code.
So I close this now.
