### ISSUE TITLE
Specify number of columns?

### ISSUE THREAD

**Issue by dstromberg** [sphinx-doc/sphinx#3092]
It'd be really nice to be able to specify the number of columns in "Source code for <module>" - we use 120 columns.  I know it's a pep8 violation, but our (substantial amount of) code uses 120, and even an old physical vt220 could do 132 columns.  Plus monitors have been getting wider.

We can scroll around to see our 120 columns, but if you combine that with the 8 column tabstops (we use 4), it's a pretty myopic view currently.

Thanks!

**Comment by dstromberg** [comment]
It turns out we can _kind_of_ do this with CSS in _build/html/_static/custom.css:
pre {tab-size: 4;width: 80em;}
div.document {width: 100em; margin-top: 0px; margin-bottom: 0px; margin-right: 0px; margin-left: 0px;}

However, it's proportionate to the font's height, not its width, so it's a little weird.  I want a width of 120 columns, so I specified 80em.  As long as the ratio of the font's height to its width doesn't change, it should be fine.

**Comment by tk0miya** [comment]
Now I proposed `viewcode_tab_width` configuration at #3100.
If accepted, it would help you.

Thanks,

**Comment by tk0miya** [comment]
Finally, I withdrew #3100 because expanding tabs modifies the source codes.
It had better use CSS to change tab width on HTML.
So the custom.css is good idea for me.

I think there is nothing to do from sphinx side. So I would like to close this issue.
@shimizukawa what do you think?

**Comment by shimizukawa** [comment]
+1 for closing.

**Comment by tk0miya** [comment]
Thank you for reporting.

**Comment by dstromberg** [comment]
The solution I described previously can be improved by using 120ch and 140ch, instead of 80em and 100em.  ch is a measure of width, em is a measure of height.

However, the hook for adding custom css appears to have changed in the latest pip'able version of sphinx?  Anyway, the things I'm putting in _build/html/_static/custom.css are now ignored.

What's the new way of adding custom CSS?

**Comment by dstromberg** [comment]
It turns out this is part of recent versions of the alabaster theme.  In alabaster 0.7.6, custom.css does not work.  In alabaster 0.7.9, custom.css does work.
