### ISSUE TITLE
[Not a bug] "UndefinedError: 'sourcename' is undefined" while generating indices

### ISSUE THREAD

**Issue by OlivierDescout** [sphinx-doc/sphinx#3094]
I get an exception "`jinja2.exceptions.UndefinedError: 'sourcename' is undefined`" while Sphinx is processing my `layout.html` file, where I added the line:
`<a class="uplink" href="{{ pathto('_sources/' + sourcename, true)|e }}" rel="nofollow">{{ _('Source page') }}</a>`

Exception is thrown while generating _genindex_, after the step "_writing output..._", and prevents Sphinx from copying static and source files to the build directory.

Complete error log is attached:
[sphinx-err-lkz0ropw.log](https://github.com/sphinx-doc/sphinx/files/550938/sphinx-err-lkz0ropw.log.txt)

**Comment by tk0miya** [comment]
The `sourcename` means "The name of the copied source file for the current document". So it has empty value when Sphinx generates the file does not related with document (.rst) like genindex.
Could you check your layout.html?
It is needed to skip process if `sourcename` is empty.

For example, in `basic/sourcelink.html`, the `sourcename` is handled as following:

```
{%- if show_source and has_source and sourcename %}
  <div role="note" aria-label="source link">
    <h3>{{ _('This Page') }}</h3>
    <ul class="this-page-menu">
      <li><a href="{{ pathto('_sources/' + sourcename, true)|e }}"
            rel="nofollow">{{ _('Show Source') }}</a></li>
    </ul>
   </div>
{%- endif %}
```

Did you check the variable is empty or not like this?

**Comment by OlivierDescout** [comment]
My mistake, you are totally right. Checking `show_source and has_source and sourcename` solved it. So I close the issue.

May I suggest the documentation should be supplemented with this useful information?
My suggestion would be to add something like what follows to the `.. data:: sourcename` section of the "templating" documentation file:

> .. data:: sourcename
> 
>   The name of the copied source file for the current document.  This is 
>   non-empty only if Sphinx generates a file related to a .rst document
>   (unlike genindex, for example) and the :confval:`html_copy_source` value is `True`.
>   Otherwise, its usage should be skipped, like in the example below:
>           `{%- if show_source and has_source and sourcename %}`
>             `<a href="{{ pathto('_sources/' + sourcename, true)|e }}" rel="nofollow">{{ _('Show Source') }}</a>`
>            `{%- endif %}``

**Comment by abitrolly** [comment]
Link to `sourcename` for Google.

https://www.sphinx-doc.org/en/stable/templating.html?highlight=sourcename#sourcename
