### ISSUE TITLE
No link to download current stable

### ISSUE THREAD

**Issue by slavkoja** [sphinx-doc/sphinx#3102]
text at home page tells : "Current version: 1.4.8", it is followed by the link to pypi, but it is redirected to Sphinx 1.5a2 page. The "Installing Sphinx" page point to the same pypi page and to the github's master .zip and .tar.gz files. Of course, i found the 1.4.8 version on github's releases page, but i found no link to it on the home page.

Please, add link to download current stable.

**Comment by TimKam** [comment]
@tk0miya This issue is no longer reproducible.

**Comment by tk0miya** [comment]
Thanks!
