### ISSUE TITLE
Graphistz

### ISSUE THREAD

**Issue by chadyred** [sphinx-doc/sphinx#3105]
I test this exemple in the doc here http://www.sphinx-doc.org/en/stable/ext/graphviz.html#module-sphinx.ext.graphviz but not work and this return litlle errors

```
Unknown directive type "graphviz"
Unknown directive type "graph"
Unknown directive type "digraph"
```

**Comment by lehmannro** [comment]
Hi Florian, please note that this is the official bug tracker for the Sphinx project.  If you have questions, please use the [sphinx-users@](http://groups.google.com/group/sphinx-users) mailing list instead.

My stab at your problem:  Did you activate the `sphinx.ext.graphviz` [extension](http://www.sphinx-doc.org/en/stable/config.html#confval-extensions)?
