### ISSUE TITLE
rst2pdf seems to be broken

### ISSUE THREAD

**Issue by grommit007** [sphinx-doc/sphinx#3107]
Hi
I have just installed Sphinx, installed with the latest version of python. Everything worked fine so tried to get rst2pdf working as well.
Ran pip install rst2pdf, everything seemed to install correctly
When I ran make html I got the following errors

> make html

Running Sphinx v1.4.8

Exception occurred:
  File "c:\users\dave\appdata\local\programs\python\python35-32\lib\site-packages\sphinx\application.py", line 473, in setup_extension
    mod = __import__(extension, None, None, ['setup'])
  File "c:\users\dave\appdata\local\programs\python\python35-32\lib\site-packages\rst2pdf\pdfbuilder.py", line 129
    except Exception, e:
                    ^
SyntaxError: invalid syntax
The full traceback has been saved in C:\Users\Dave\AppData\Local\Temp\sphinx-err-2qjnhq3_.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!

I have included the log file so hopefully you can tell me what is going on
[sphinx-err-2qjnhq3.txt](https://github.com/sphinx-doc/sphinx/files/562882/sphinx-err-2qjnhq3.txt)

**Comment by tk0miya** [comment]
It seems rst2pdf does not support python3. So please report that them.
https://github.com/rst2pdf/rst2pdf

Thanks,
