### ISSUE TITLE
Dropped latex builder enhancement

### ISSUE THREAD

**Issue by nyarbin** [sphinx-doc/sphinx#3112]
https://github.com/sphinx-doc/sphinx/issues/2512 is closed by a commit that describes https://github.com/sphinx-doc/sphinx/issues/2521 (but references #2512). This looks suspiciously like a typo. #2512 was an enhancement target for version 1.5; has it been dropped intentionally? If so, why? If not ... it's a pretty good idea.

**Comment by tk0miya** [comment]
Oh, it's my mistake. Thank you for letting me know.
But LaTeX builder already uses jinja templates now (customized to JSP/eRuby like syntax):
https://github.com/sphinx-doc/sphinx/blob/1.5a2/sphinx/templates/latex/content.tex_t
