### ISSUE TITLE
Pickle load slows down documentation generation

### ISSUE THREAD

**Issue by xavierhardy** [sphinx-doc/sphinx#3127]
Hi Sphinx team,

I was trying to figure why building documentation was taking more than 2 minutes. Profiling with cProfile, it turns out most of the time is spent for loading Sphinx-generated doctree files in Pickle format. _pickle.load has been called 615 times with a total of 138 seconds spent inside this function (out of 166, for the whole doc generation process).

```
23722469 function calls (22446458 primitive calls) in 166.047 seconds
...
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        2    0.000    0.000    0.000    0.000 {built-in method _pickle.dumps}
       16    0.096    0.006    0.097    0.006 {built-in method _pickle.dump}
      615  137.918    0.224  158.224    0.257 {built-in method _pickle.load}
```

Note that generating them does not seem to be an issue here.

I have tried deactivating everything I could and activating multi processing, it does not speed up anything. Any idea, please?

Thanks in advance

**Comment by tk0miya** [comment]
Note: Similar to #4576.

We need to reproduce the situation to investigate this.
