### ISSUE TITLE
latex does not implement ``:emphasize-lines:`` option to ``code-block`` directive

### ISSUE THREAD

**Issue by jfbu** [sphinx-doc/sphinx#3129]
This (from http://www.sphinx-doc.org/en/stable/markup/code.html#line-numbers)

```rst
.. code-block:: python
   :linenos:
   :emphasize-lines: 3,5

   def some_function():
       interesting = False
       print 'This line is highlighted.'
       print 'This one is not...'
       print '...but this one is.'

```
does not produce any special effect (beyond the line numbers), contrarily to html build. The feature appears never to have been implemented in the latex builder or writer.

**Comment by jfbu** [comment]
Appears to be a duplicate of https://github.com/sphinx-doc/sphinx/issues/1238

**Comment by tk0miya** [comment]
Can I close this?

**Comment by jfbu** [comment]
Closing as duplicate of #1238
