### ISSUE TITLE
the Sphinx own documentation in html has rendering problems in latex page (1.5b1)

### ISSUE THREAD

**Issue by jfbu** [sphinx-doc/sphinx#3130]
See the big Note at http://www.sphinx-doc.org/en/master/latex.html#the-sphinx-latex-style-package-options

Same with the Hint  a bit lower in the page.

There seems to be an issue with the used theme, as I tested with other themes such as classic and alabaster and have no issue.

**Comment by tk0miya** [comment]
Fixed!

Note: at my PC, I have to force reload the page to clear CSS cache.

**Comment by jfbu** [comment]
confirmed, 👍  ;-)

I always configure on all computers Firefox to use "private browsing mode" with "zero Ko" for the cache (plus of course AdBlockPlus), to try to limit a bit the spying done via web sites, and perhaps related to that the improvement was immediately visible.
