### ISSUE TITLE
Infinite recursion when building project with a self-referencial toctree entry

### ISSUE THREAD

**Issue by arigo** [sphinx-doc/sphinx#3131]
I'm trying to build a project where the file index.rst has got the following toctree:

```

.. toctree::

   index
   whatsnew
```

This gives an infinite recursion error in ``sphinx-build``.  What I would like is for the TOC to include the index.rst too, so that index.rst appears like a normal entry on my readthedocs pages.  For reference: the readthedocs page is http://cffi.readthedocs.io/en/latest/, and the source repository with the self-referential doc is https://bitbucket.org/cffi/release-doc/ at revision ff3437c07f77 (``cd doc; make html``).

**Comment by tk0miya** [comment]
What version did you use?
It was fixed at Sphinx-1.4.2
https://github.com/sphinx-doc/sphinx/blob/1.4.2/CHANGES#L41

Please update your Sphinx.
Thanks,

**Comment by arigo** [comment]
Ah, sorry!  readthedocs.org is still using v1.3.5.  Thanks!
