### ISSUE TITLE
Add possibility to specify a config file

### ISSUE THREAD

**Issue by rweickelt** [sphinx-doc/sphinx#3133]
**Current state:**
The name ``conf.py`` is hard coded and it's impossible to rename it.

**Problem:**
One cannot have multiple conf files in one project folder, i.e. to build two different documentation variants. I work around that problem by setting an environment variable in the makefile and conditionally setting some parameters in ``conf.py`` based on that variable.

**Suggestion:**
Change the ``-c`` option so that it accepts a filepath to a config file instead of directories only. If a directory is specified, search for ``conf.py`` by default.

**Comment by jfbu** [comment]
What about having `conf-A.py`, `conf-B.py`, etc.., and dynamically create a symlink `conf.py->conf-whatever.py` from your Makefile before calling `sphinx-build` ?  (depending on a Makefile variable for example, or the contents of a a file `confpy.txt` containing the path to the actual `conf.py`  to use).

**Comment by jfbu** [comment]
This seems to work for me:

```
# Minimal makefile for Sphinx documentation
#

# You can set these variables from the command line.
SPHINXOPTS    =
SPHINXBUILD   = sphinx-build
SPHINXPROJ    = temp
SOURCEDIR     = .
BUILDDIR      = _build

# Put it first so that "make" without argument is like "make help".
help:
    @$(SPHINXBUILD) -M help "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)

.PHONY: help Makefile confpy.txt

conf.py: confpy.txt
    ln -fs `cat confpy.txt` conf.py

# Catch-all target: route all unknown targets to Sphinx using the new
# "make mode" option.  $(O) is meant as a shortcut for $(SPHINXOPTS).
%: Makefile conf.py
    @$(SPHINXBUILD) -M $@ "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)
```

 (sorry I don't recall offhand if a  Makefile like this was already in Sphinx 1.4.8, will check later)

the file `confpy.txt` is one-line file containing `conf-A.py`, or `conf-B.py`, etc...

tested on a unix-like system (mac os x)

edit: better `ln -fs "`cat confpy.txt`" conf.py`

**Comment by jfbu** [comment]
> (sorry I don't recall offhand if a Makefile like this was already in Sphinx 1.4.8, will check later)

yes a Makefile like the above is available in Sphinx 1.4.8 and created via `sphinx-quickstart -m`. The Makefile in my previous post is based on the Sphinx 1.5 one (which fixes an issue) and it works with Sphinx 1.4.8.

**Comment by rweickelt** [comment]
Thanks, but that's a workaround as well. What happens with symlinks in the windows file system? Unfortunately, most of my team members check the repo out in Windows and build using Vagrant.

**Comment by jfbu** [comment]
I am a no-ob in Windows, but I see that `sphinx-quickstart -m` created a make.bat file. This make.bat could be enriched with a new recipe for conf.py, if symlinks are impossible, then just a copy of conf-A.py, etc... however no idea about the syntax.

This being said, yes it is a work-around, but it does realize separate conf.py files: you don't have to clutter a single conf.py with complicated conditionals. Also, the conf.py's can be located anywhere you want.

**Comment by lehmannro** [comment]
You can also already do "complicated conditionals" and then just use plain Python imports.

**Comment by jfbu** [comment]
Just to say that my symlink suggestion was indeed purely a work-around, and I was not meaning to  imply anything against @rweickelt's suggestion about `-c` accepting a filepath.

**Comment by rweickelt** [comment]
Implementing the functionality was quite easy, but the filename conf.py is so deeply hard-coded into the Sphinx documentation that an update is cumbersome. Before I proceed, I want to know, whether such a change would be accepted at all. May I kindly ask for suggestions regarding the documentation?

Further do I think that it would make sense to change the default behavior (without -c) into "Search for a file with the suffix .py in the current working directory and fail when there are multiple .py files". But that would be incompatible.

**Comment by tk0miya** [comment]
You can switch multiple configurations using `-c` option. With `-c foo`, sphinx refers `foo/conf.py`, and with `-c bar` will refer `bar/conf.py`.
What about this?

I don't opposite your proposal strongly. But we can do that using existing feature. So I feel no implementation is needed.

**Comment by Paebbels** [comment]
Windows supports symbolic links, hard links, sparse points, ... on NTFS file systems since years.

**Comment by tk0miya** [comment]
I'm closing this because we already have `-c` option.
Thanks,

**Comment by nedclimaterisk** [comment]
it would be nice if sphinx-quickstart also had a -c option
