### ISSUE TITLE
Autodoc's format_annotation() failing for plain Callable

### ISSUE THREAD

**Issue by yoongu** [sphinx-doc/sphinx#3135]
Autodoc fails on a function that takes in a plain Callable annotation (an example shown below). It fails with the message: `error while formatting arguments for...: 'NoneType' object is not iterable`

```python
from typing import Callable
def func(param: Callable):
    pass
```

This fails in the autodoc()'s `format_annotation()` function, which expects a Callable annotation to have arguments: e.g., Callable[int, str].

But according to Python documentation [1], a plain Callable is permitted, and should be treated as being equal to Callable[..., Any].

[1] https://docs.python.org/3/library/typing.html#typing.Callable

**System Configuration**
- Python: 3.4.3 AMD64 on Win32
- Sphinx 1.4.8

**Comment by tk0miya** [comment]
Fixed at 4ca84ab.
Thank you for reporting!
