### ISSUE TITLE
referencing a function parameter

### ISSUE THREAD

**Issue by brechtm** [sphinx-doc/sphinx#3137]
It would be useful to be able to directly reference function parameters. The [sphinx-paramlinks](https://pypi.python.org/pypi/sphinx-paramlinks/) adds this functionality, but it does not work with docstrings in Google format.

I agree with the author that this [should be built-in functionality](http://stackoverflow.com/a/20845306/438249). Is there any particular reason this is not the case, or is this simply something that has not yet been implemented?

**Comment by brechtm** [comment]
Oops. I think this is a duplicate of #538.

**Comment by tk0miya** [comment]
Thank you for proposal.
Let's discuss it in #538.
