### ISSUE TITLE
the type of an attribute is not hyperlinked (napoleon)

### ISSUE THREAD

**Issue by brechtm** [sphinx-doc/sphinx#3138]
For parameters listed in docstrings ("Parameters" section) using the Google docstring format, the parameter's type is hyperlinked to the autoclass documentation of the type.

For attributes ("Attributes" section), these links are not created. They *are* created if the `napoleon_use_ivar` is set to True.

I suspect the reason for this is that the napoleon extension handles the types included in the Attributes section itself, since I see no way to pass the type to the `.. attribute::` directive. By contrast, the `:param:` and `:ivar:` fields do support specifying a type.

**Comment by RobRuana** [comment]
That is correct, there is no way to add hyperlinks using the `.. attribute::` directive.

If you need your attribute types hyperlinked, then set `napoleon_use_ivar` to `True`.

I suspect this issue is getting at the same thing presented in issue #2979.

**Comment by brechtm** [comment]
ivars are different from class attributes, so I'd rather not set `napoleon_use_ivar`.

I was able to work around the issue by entering the attribute's type using a `:class:` reference, which does create links (but is styled differently).

**Comment by RobRuana** [comment]
I am going to close this issue for now, because I think it's better addressed by #3141.
