### ISSUE TITLE
How about a PowerShell based 'make' file?

### ISSUE THREAD

**Issue by Paebbels** [sphinx-doc/sphinx#3145]
Hello,

the generated `make.bat` is kind of outdated on modern Windows machines. At first batch files are called command files (`*.cmd`) since more than 15 years (Windows 2000). Second, the old Windows command line  (`cmd.exe`) is also outdated. Windows is shipped with PowerShell since Windows Vista.

So how about a PowerShell based `make.ps1` file with self-documentation (integrated help page)?

I could provide a basic file with a selection of "build targets". I don't use all target nor have I a full setup to test them all. So I could provide a start for further feature additions.

Kind regards
    Patrick Lehmann

**Comment by tk0miya** [comment]
I'm not a Windows user, so I don't have strong opinion for this.
It's okay to move to powershell if anyone sends pull request to us.

@shimizukawa what do you think?

**Comment by Paebbels** [comment]
I just found out that the next PowerShell version (6.0) will be released for "all" operating system (incl. Linux). The project is hosted on [GitHub](https://github.com/PowerShell/PowerShell?ts=2). I'll check how good this port is and if it supports Windows PowerShell files also on Linux (e.g. the path separator problem ...).

**Comment by shimizukawa** [comment]
Now Makefile/make.bat become simpler than earlier. So I'm OK to have PowerShell based one.

Memo: CPython venv module also includes Activate.ps1 https://github.com/python/cpython/tree/master/Lib/venv/scripts/nt for PowerShell users.

**Comment by Paebbels** [comment]
What for is the configuration option `make_mode` in [`quickstart.py:446`](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/quickstart.py?ts=2#L446)? Why are there two template files?

According to [`quickstart.py:611`](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/quickstart.py?ts=2#L611) this option applies only to Windows batch files, but in  [`quickstart.py:446`](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/quickstart.py?ts=2#L446) both (makefile and batchfile) are effected.

**Addendum:**

Which syntax is preferred?

Example 1:
`.\make.ps1 -html`

Example 2:
`.\make.ps1 html`

While the second can be implemented, I would prefer the first, because this is available via tab completion and is equivalent to the displayed help page by `man make.ps1`.

**Comment by Paebbels** [comment]
Pull request #3153 should implement a first version of a new build script written in PowerShell.

**Comment by Kilo59** [comment]
Has this issue been abandoned?

**Comment by Paebbels** [comment]
Sorry, I haven't had time to continue on this PR. You can take over and finish it if you like. It's hard to fulfill all requirements drawn up by sphinx-doc.

**Comment by cblegare** [comment]
Since Sphinx is fading out Makefiles, should this issue be closed as wontfix?

**Comment by Paebbels** [comment]
@cblegare how are make files replaced?

The problem was not the Makefile itself, the problem of Sphinx is, it provides outdated `*.bat` files for Windows. At first, these files should be called `*.cmd` since more then 20 years. At second, since 15 years, scripting on Windows should use PowerShell instead of the outdated Command Prompt.

**Comment by cblegare** [comment]
@Paebbels I absolutely agree that *.bat are artifacts from another era.

From the issue above (#5618)

> The goal of this issue is "Makefile-less sphinx project".

My question was simply based on the fact that since in more than 5 years nobody contributed a patch for a make.ps1 script and that the project maintainers are looking into making these scripts (including the actual Makefile itself) irrelevant anyways, maybe one could find it appropriate to close this issue.

**Comment by AA-Turner** [comment]
Closing in favour of #5618.

A
