### ISSUE TITLE
html search not work for Chinese?

### ISSUE THREAD

**Issue by pangxiezhou** [sphinx-doc/sphinx#3147]
I use sphinx 1.4.8 to write Chinese doc, but html search do not work。

deep into searchtool.js，I found this code in `query` method

` var tmp = query.split(/\W+/);`

So I test:
`test_str = "呵呵" //chinese word`
`test_str.split(/\W+/)`

The result is:
`["", ""]`

so this code is only work for English ?

now I changed the code to：
`var tmp = query.split(/\s+/);`

just work fine for English and Chinese :D

**Comment by TimKam** [comment]
For the same reason, search doesn't work with terms containing umlauts (ö, ä ü, ø, etc.).

**Comment by tk0miya** [comment]
@TimKam could you try or review #3154 if possible?

**Comment by TimKam** [comment]
@tk0miya I built a comprehensive set of German Docs with https://github.com/sphinx-doc/sphinx/pull/3154 and the search works fine as far as I can tell. I added some comments (nits).

**Comment by tk0miya** [comment]
#3154 is merged now.
Thank you for reporting!

**Comment by pangxiezhou** [comment]
👍
