### ISSUE TITLE
BugFix to support CJK search

### ISSUE THREAD

**Issue by scaret** [sphinx-doc/sphinx#3150]
https://github.com/sphinx-doc/sphinx/commit/4ff5cbfaf920700382f809abe5def23e07bd0553

This change will break the CJK search. For Chinese:

```JavaScript
var query = "Hello from 中国 上海";
var tmp = query.split(/\W+/);
// tmp: [ 'Hello', 'from', '' ];
```
Former one:
```JavaScript
var query = "Hello from 中国 上海";
var tmp = query.split(/\s+/);
// tmp: [ 'Hello', 'from', '中国', '上海' ]
```

I suggest to revert the commit.

**Comment by shibukawa** [comment]
Thank you for reporting. #2856 needs to split "PIN-code" into `["PIN", "code"]`, but this regexp doesn't work on Chinese characters. We have to create new JS regexp that compatible with Python's `r'\W+'`.

**Comment by tk0miya** [comment]
refs: #3147

**Comment by tk0miya** [comment]
#3154 is merged now.

**Comment by tk0miya** [comment]
Thank you for reporting!
