### ISSUE TITLE
The search function on master doesn't work in Internet Explorer, Opera

### ISSUE THREAD

**Issue by TimKam** [sphinx-doc/sphinx#3155]
[The JS code introduced with this commit](https://github.com/sphinx-doc/sphinx/commit/71e1aaf3770831df1b5b7f36aaadb789176a2927) uses `String.prototype.endsWith.endsWith`, which [doesn't work in Internet Explorer, Opera](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/String/endsWith).

Instead we should use (in this context, not tested):

`item[5].indexOf(.txt, item[5].length - 4) !== -1`

**Comment by tk0miya** [comment]
Thank you for reporting!
I will fix it later.

**Comment by shibukawa** [comment]
`item[5].slice(-4) === '.txt'` This is the easiest and compatible with ECMAScript 3.

**Comment by tk0miya** [comment]
Fixed at 1250738.
Thank you for reporting!
