### ISSUE TITLE
too much space after ``Fig.`` in PDF output

### ISSUE THREAD

**Issue by jfbu** [sphinx-doc/sphinx#3158]
With for example English language, we get this in latex file:

    \addto\captionsenglish{\renewcommand{\figurename}{Fig.\@ }}

But ``\figurename`` is used by LaTeX in this context:

    \figurename \nobreakspace \thefigure

Thus we have _two_ spaces: the one from after ``\@`` and the one from ``\nobreakspace``.

Note: after control sequences ``\foo`` TeX usually ignores a space immediately following in source, but not after one-character control word such as  ``\@``. It would if the ``\@`` as above had appeared in a package file (like sphinx.sty), but here it is used in preamble of latex document where  ``@`` is not a "letter". Hence the space after ``\@`` does count.

The latex code should have ``\@``  without a following space.

**Comment by tk0miya** [comment]
I determined to postpone this to 1.5.1

**Comment by jfbu** [comment]
Actually, the issue title is misleading. It is not caused by the ``\@`` the phenomenon shows also with no abbreviation.

    \addto\captionsenglish{\renewcommand{\tablename}{Table }}

has an extra space after ``Table``. But LaTeX already puts by default a space after the caption name and before the caption number. Paradoxically the ``\@`` is easier because to fix it it was enough to add ``\\makeatletter...\\makeatother``  around generated string from ``babel_renewcommand(self, command, definition)`` in ``latex.py``. I prepared a branch doing that, but then realized the problem was also with non abbreviated caption names such as ``Table`` in English. It is at https://github.com/jfbu/sphinx/tree/fixextraspace

**Comment by tk0miya** [comment]
quick investigation:

The default settings:
![2017-01-15 21 22 30](https://cloud.githubusercontent.com/assets/748828/21962420/d830aafc-db68-11e6-8f7f-d5893f3578e9.png)

With following settings:
```
numfig_format = {
    'section': 'Section%s',
    'figure': 'Fig.%s',
    'table': 'Table%s',
    'code-block': 'Listing%s',
}
```
![2017-01-15 21 22 47](https://cloud.githubusercontent.com/assets/748828/21962424/e64e209c-db68-11e6-8e7e-e3054212944f.png)


I will remove white spaces at tail of numfig_formats later.
