### ISSUE TITLE
Add ro_RO language?

### ISSUE THREAD

**Issue by trasher** [sphinx-doc/sphinx#3159]
Hello,

For a doc I wrote and put on an translation online system, someone requested the ro_RO language, we've added it and the translation has begin...

But I did not pay attention this is not part of supported languages! Would it be possible to get it added?

Thank you very much!

**Comment by shimizukawa** [comment]
To be clarify, please let me know a URL of the `translation online system`.
I have two or three possibility which document you mentioned: Sphinx itself, Sphinx reference, Some doc written by sphinx, ..

**Comment by trasher** [comment]
OK, let me clarify :)

I wrote a doc using sphinx:
https://github.com/pluginsGLPI/doc

I've used sphinx-intl and publish my pot files on transifex:
https://www.transifex.com/teclib/glpi-plugins-documentation

And finally, I used rtfd to put that online. Note that "romanian" is available on rtfd languages list (I've just seen it).

Maybe there is something I misunderstood regarding to supported langs list on sphinx side?

Thank you.

**Comment by shimizukawa** [comment]
First of all, there is no limit to the language that Sphinx can handle. Of course, Sphinx itself has a [limited language catalog](https://github.com/sphinx-doc/sphinx/tree/master/sphinx/locale), but users' documents and their translations are fine in any language(even country codes not included in ISO-639).

Transifex seems to be able to select both `ro` and `ro_RO`, but ReadTheDocs does not seem to be able to select `ro_RO`. This is not a limitation of Sphinx, it seems to be a limitation of ReadTheDocs.

**Comment by trasher** [comment]
Hi @shimizukawa,

All of that is much more clear in my mind now! I was a bit lost! I did think readthedocs limitations were sphinx limitations...

Thank your very very much for your explanations; ad sorry for the noise :)
