### ISSUE TITLE
Document metadata like :orphan: is rendered as text if the ReST file is included.

### ISSUE THREAD

**Issue by Paebbels** [sphinx-doc/sphinx#3167]
I have a include file called `Authors.rst`, which is included into another document. The file is not referenced by a toctree directive. To suppress the "not referenced" warning, I added the metadata `:orphan:` to the `Authors.rst` file. Unfortunately, the text `orphan:` is displayed in the HTML output. (Not there is no leading colon in the text.)

**Authors.rst:**
```rst
:orphan:

.. # This file is included. So it needs to be marked as orphan to suppress warnings.

Some content
```

**index.rst:**
```rst
List of Contributers
********************

.. include:: ./Authors.rst

```

**Rendered HTML output:**
![image](https://cloud.githubusercontent.com/assets/956109/20489068/9c827380-b009-11e6-8cee-91b8703485fc.png)

-----------------------------------------
Related issues: #3149

**Comment by tk0miya** [comment]
You should not mark `:orphan:` for included files.
At current release, Sphinx does not warn for included files as orphaned.
So please remove them and upgrade your sphinx (if still warned).
