### ISSUE TITLE
Autodoc's autodoc-skip-member event not working properly with multiple callbacks registered

### ISSUE THREAD

**Issue by allebacco** [sphinx-doc/sphinx#3174]
Autodoc extension emits the 'autodoc-skip-member' event using `emit_firstresult`, so if multiple callbacks are registered on this event, only the first result is used.
When the user enable the the Napoleon extension and add a custom callback to the 'autodoc-skip-member', only the result from napoleon callback is used and the result from the custom callback is ignored.

The solution could be to emits the event using `emit` and then check the content of the returned list.

**Comment by allebacco** [comment]
Another solution could be to return `None` from Napoleon callback, but, however, if multiple user custom callbacks are registered to the `autodoc-skip-member` event, only the fist `not None` result is used.

**Comment by tk0miya** [comment]
+1

Note:
autodoc module has used `emit_firstresult()` on `autodoc-skip-member` event since appeared (155411a9).

**Comment by RobRuana** [comment]
Napoleon has been doing the incorrect thing for ``autodoc-skip-member``. It returns the ``skip`` parameter by default, when it should return ``None``.

```
def _skip_member(app, what, name, obj, skip, options):
    # run napoleon skip checks
    return skip
```

I will change it to return ``None``:
```
def _skip_member(app, what, name, obj, skip, options):
    # run napoleon skip checks
    return None
```

**Comment by allebacco** [comment]
However, even if Napoleon returns `None`, if the user register multiple callbacks on the `autodoc-skip-member` event, only the first result is used.

The issue could be fixed by:
- returning `None` as default value in napoleon, as suggested by @RobRuana
- improving documentation about the `autodoc-skip-member` event to force the users to return `None` instead of `skip` as default value.

**Comment by RobRuana** [comment]
Yes, I think improving the documentation for ``autodoc-skip-member`` is a requirement. I'll also update that.

I think the reason ``emit_firstresult()`` was used instead of ``emit()`` is because there's no best way to resolve the conflict when one extension returns ``False`` and another returns ``True``. The simplest strategy is to use the first result.

**Comment by RobRuana** [comment]
Is meaning of the new text (in bold) below clear?

> autodoc-skip-member(app, what, name, obj, skip, options)
>  New in version 0.5.
> 
>  Emitted when autodoc has to decide whether a member should be included in the documentation. The member is excluded if a handler returns True. It is included if the handler returns False.
> 
>  **Handlers should return ``None`` to fall back to the skipping behavior of autodoc and other enabled extensions.**

**Comment by allebacco** [comment]
Yes, for ne is clear.
We could warning that

*Returning a value that is not `None` will prevent other handlers to be called.*

Just to clarify the meaning of the requirements on the return value.

**Comment by ccmaymay** [comment]
What release will this fix appear in?

**Comment by RobRuana** [comment]
This should appear in sphinx versions 1.5 and higher.

**Comment by ccmaymay** [comment]
It looks to me like neither [1.5](https://github.com/sphinx-doc/sphinx/archive/1.5.tar.gz) nor [1.5.3](https://github.com/sphinx-doc/sphinx/archive/1.5.3.tar.gz) has the change from f45fe6fc (e.g., by looking at [the last line of sphinx/ext/napoleon/__init__.py](https://github.com/sphinx-doc/sphinx/blob/f45fe6fc8ca95f5b71b57b0ab80a3a44560c0295/sphinx/ext/napoleon/__init__.py#L467))?  (I didn't look at 1.5.1 or 1.5.2.)

**Comment by jfbu** [comment]
the commit is in master branch which is preparation for 1.6 release. It is not as of today in stable branch which is preparation for 1.5.4 release. I imagine it was merged into master at a time when the 1.5 pre-release branch existed and for some reason never made it to it, so it has stuck in master since.

**Comment by ccmaymay** [comment]
That's disappointing, this is a very useful feature for some auto-generated code.  Is there a mechanism to get it released in 1.5.x?

**Comment by RobRuana** [comment]
I'll cherry pick it as soon as I get home!

**Comment by RobRuana** [comment]
Ok, 1.5.3 was just released, but I'll make sure it's in the next release – either 1.5.4 or 1.6.

**Comment by RobRuana** [comment]
FYI: this will be in the 1.5.4 release

**Comment by ccmaymay** [comment]
Thanks so much!
