### ISSUE TITLE
WARNING: Could not lex literal_block as "sql". Highlighting skipped.

### ISSUE THREAD

**Issue by NikitaEgorov** [sphinx-doc/sphinx#3175]
If code block contains $

Sphinx show 
WARNING: Could not lex literal_block as "sql". Highlighting skipped.

```
.. code-block:: sql

    USE [$Database]
    alter table [dbo].Project add Status BIT
    GO
```

**Comment by tk0miya** [comment]
What did you mean? Please tell me what do you want in detail.

Note:
The error is raised by pygments which sphinx uses as highlighting engine.

**Comment by NikitaEgorov** [comment]
Add to any RST document code block with language sql
And in this code block wrote $ symbol

Like this

```
.. code-block:: sql

    alter table [dbo].$Project add Status BIT
```

And try to make html

Sphinx show 1 warning
WARNING: Could not lex literal_block as "sql". Highlighting skipped.

And not highlight code block

**Comment by tk0miya** [comment]
The message says our highlighting engine could not parse your input as sql.
Is `$` symbol valid in standard SQL?

Anyway, there are no way to avoid it at this moment.
We have a proposal to add `force` option to highlighting engine (#2310).
It might help you if the engine works well.

**Comment by tk0miya** [comment]
As I commented above, `$` symbol is not valid in standard SQL, AFAIK.
So I think this is not a bug of Sphinx.

Thanks,

**Comment by xxks-kkk** [comment]
I was wondering when pygments throws could not lex literal_block error, is it possible for sphinx-doc to propagate the exact location of the code-block where the lex errors happen? This will be extremely helpful debugging the syntax mistake in code-block. Thanks!

**Comment by tk0miya** [comment]
It seems no way to obtain where pygments detects syntax error. If you have good idea, please post a pull request. Contribution is always welcome!

**Comment by erezsh** [comment]
The following works in sqlite3:

```sql
select 10 as a$;
```
