### ISSUE TITLE
Error while generating PDF

### ISSUE THREAD

**Issue by klpatil** [sphinx-doc/sphinx#3179]
Hello,

I am trying to generate PDF of this documentation site : https://github.com/Sitecore/Helix.Docs/ and I am using these links : 
http://rst2pdf.ralsina.me/handbook.html
https://www.quora.com/How-to-create-a-PDF-out-of-Sphinx-documentation-tool

After configurign rst2pdf I am facing an error. Log files attached here. Can you please help?

[Logs.zip](https://github.com/sphinx-doc/sphinx/files/611941/Logs.zip)

**Comment by tk0miya** [comment]
Simply, rst2pdf does not support python3.
This is not a bug of Sphinx.
Thank you
