### ISSUE TITLE
sphinx can't work with nbsphinx because of julia version issues

### ISSUE THREAD

**Issue by scordature** [sphinx-doc/sphinx#3188]
What version of Julia works with sphinx and nbsphinx?

Running sphinx on Mac OS 10.10.5, with nbsphinx, all in a virtualenv environment called "venv"

```
$ make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.4.9
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 85 source files that are out of date
updating environment: 85 added, 0 changed, 0 removed
reading sources... [ 60%] venv/lib/python2.7/site-packages/nbconvert/tests/files/notebook_jl                                             
Notebook error:
NoSuchKernel in venv/lib/python2.7/site-packages/nbconvert/tests/files/notebook_jl.ipynb:
No such kernel named julia-0.4
make: *** [html] Error 1
```

This error made sense, because I have the current version of Julia installed: it is 0.5, not 0.4.

So, I edited `notebook_jl.ipynb` to call Julia 0.5 instead of 0.4.

Now I get a new error:

$ make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.4.9
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 85 source files that are out of date
updating environment: 85 added, 0 changed, 0 removed
reading sources... [ 60%] venv/lib/python2.7/site-packages/nbconvert/tests/files/notebook_jl                                             
Exception occurred:
  File "/Users/somebody/test-sphinx-venv/venv/lib/python2.7/site-packages/nbformat/reader.py", line 63, in reads
    raise NBFormatError('Unsupported nbformat version %s' % major)
NBFormatError: Unsupported nbformat version 5
...
make: *** [html] Error 1
```
Here is the stack trace:


[sphinx-err-I_Mjop.log.txt](https://github.com/sphinx-doc/sphinx/files/628376/sphinx-err-I_Mjop.log.txt)

**Comment by tk0miya** [comment]
It seems your case is an issue of nbsphinx.
Sorry, this is an issue tracker for Sphinx core. not nbsphinx.
Please ask it on their mailing list or forums.
We don't know the behavior of individual extensions.
