### ISSUE TITLE
util.split_docinfo fails to parse multi-line field bodies.

### ISSUE THREAD

**Issue by jkawamoto** [sphinx-doc/sphinx#3190]
From [the reStructuredText Markup Specification](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html), field lists, which are used to define docinfo, allow multi-line field bodies, but util.split_docinfo seems not to consider such case.

For example, 

```
:fieldname: one
    two
    three

Hello world.
```

is expected to be split to

~~~
:fieldname: one
    two
    three
~~~

and

~~~

Hello world.
~~~

but util.split_docinfo returns 

~~~
:fieldname: one
~~~

and

~~~
    two
    three

Hello world.
~~~

**Comment by tk0miya** [comment]
Merged #3191.
