### ISSUE TITLE
When make(1) is not GNU make(1) - one patch and one outstanding issue

### ISSUE THREAD

**Issue by illumino** [sphinx-doc/sphinx#3194]
Greetings,

I was building sphinx-1.3.1 on Solaris 10 system, where make(1) is not GNU make(1), and encountered a few problems. I have GNU make(1) available as gmake(1).  Note: Sphinx-Newbie-Warning: I'm building Sphinx to get documentation for other FLOSS products, so I have not entered the Sphinx world yet - please excuse any noobishness.

 I was able to fix one consistency issue in sphinx/quickstart.py (see consistency.patch.txt). 

 While I can see a few references to 'makevar' in the source tree I was unable to determine how to use that that feature, and regardless there are hard-coded uses of make(1) in the source code. While I was able to improve latex-based PDF generation with the patch example-fix.patch, this is NOT a general fix that can be applied to the source code. It is provided to assist other who may tread this path, and to identify to the developers three simple instances of hard-coded uses make(1). As a non-sphinx developer, I am not sure how the team would approach the replacement of these hard-coded uses, so I'll simply point them out.

Regards,
Peter

[consistency.patch.txt](https://github.com/sphinx-doc/sphinx/files/630224/consistency.patch.txt)
[example-fix.patch.txt](https://github.com/sphinx-doc/sphinx/files/630226/example-fix.patch.txt)

**Comment by tk0miya** [comment]
+1 for using environment variable like `$(MAKE)`.

**Comment by illumino** [comment]
Thanks for the +1. A small note: technically $(MAKE) is the expansion make(1) variable/macro, but values for such variables can be influenced by your environment variables (both in general and by the -e option). Most users would not have most make(1) variables coming from the environment, but from built-in make defaults (see -p option - what is built-in varies by make(1) implementation). So when I run gmake, it sets MAKE to gmake and thus $(MAKE) expands to gmake and recursive make files which need a given make(1) implementation just work. Unfortunately you still a lot of hard-coding in open-source, like rm -f rather than $(RM), but that could be influenced by old make(1) implementations.
Regards, Peter

**Comment by tk0miya** [comment]
Note:
In Sphinx-1.5, quickstart generates following Makefile (with `-M` option):
```
.PHONY: latexpdf
latexpdf:
        $(SPHINXBUILD) -b latex $(ALLSPHINXOPTS) $(BUILDDIR)/latex
        @echo "Running LaTeX files through pdflatex..."
        $(MAKE) -C $(BUILDDIR)/latex all-pdf
        @echo "pdflatex finished; the PDF files are in $(BUILDDIR)/latex."
```
It seems already fine.

But, without any options, Sphinx runs under make-mode by default.
In the mode, Sphinx uses hard-coded `make` command.
https://github.com/sphinx-doc/sphinx/blob/1.5.1/sphinx/make_mode.py#L192

We have to replace the command using environment variable `$MAKE`.
