### ISSUE TITLE
Missing changelog entry for Sphinx 1.5

### ISSUE THREAD

**Issue by asr** [sphinx-doc/sphinx#3197]
There isn't an entry for Sphinx 1.5 in the [changes](https://github.com/sphinx-doc/sphinx/blob/a265670b79e737a0c88ea76dbac5485c19f6e350/CHANGES) file.

**Comment by jfbu** [comment]
please look at correct branch https://github.com/sphinx-doc/sphinx/blob/1.5-release/CHANGES

**Comment by asr** [comment]
Thanks for the right link.

**Comment by jfbu** [comment]
Glad it helped, the branch will be merged into master later I guess ;-)

**Comment by shimizukawa** [comment]
Now 1.5-release is merged into master ;)
