### ISSUE TITLE
latex_use_modeindex deprecation warning always thrown 

### ISSUE THREAD

**Issue by JDWarner** [sphinx-doc/sphinx#3204]
Scikit-Image does not set or change the default value for this config parameter in our doc build - indeed, searching for `latex_use_modeindex` in our repo yields no results at all.  

However, we require the doc build to complete without warnings.  It seems with completely default settings, this is throwing a warning on Sphinx 1.5.  As a result, all of our continuous integration builds are failing.  The warning is thrown from [this line](https://github.com/sphinx-doc/sphinx/blob/2ec179044bc7dfc647731a08bc3da7d6e133c994/sphinx/builders/latex.py#L252) in Sphinx.

See log here: https://travis-ci.org/scikit-image/scikit-image/jobs/182043593
In reference to recently merged PR https://github.com/scikit-image/scikit-image/pull/2366, which passed with flying colors in the PR Travis build.

**Comment by tk0miya** [comment]
Really? It seems your project sets False value.
https://github.com/scikit-image/scikit-image/blob/master/doc/source/conf.py#L277

**Comment by tk0miya** [comment]
Oh, sorry. I understand. There is a typo in our warning message.
`latex_use_modindex` was deprecated, not mod-"e"-index.
I will fix the message later.

Thank you for letting me know!

**Comment by tk0miya** [comment]
Fixed at 	e6ca4ee.
