### ISSUE TITLE
Italian localization does not work in 1.5

### ISSUE THREAD

**Issue by lelit** [sphinx-doc/sphinx#3211]
This release added (in commit 30b9acc3026c795ba98beb361afff271fe197821) the `it_IT` catalog: since it is more specific than the `it` one, it is picked as the main translation, but being empty (that is, all entries are untranslated) its `gettext` returns the original message (even if the underlying stdlib `GNUTranslation` **does** carry a reference to the `it` catalog as a _fallback_, the logic in its entry points uses the fallback catalog only when the message is missing in the main one, not when it's untranslated...)

I would simply remove the `it_IT` catalog, or fill it with the content of the `it` one.

**Comment by shimizukawa** [comment]
OK, I'll remove it.

**Comment by shimizukawa** [comment]
On https://www.transifex.com/sphinx-doc/sphinx-1/dashboard/ , there are 6 "completely untranslated" langs that include 4 "without translator". I'll remove these from both transifex and sphinx/locale.

**Comment by shimizukawa** [comment]
![image](https://cloud.githubusercontent.com/assets/151623/21070693/285078f8-bece-11e6-820a-169caae5f02d.png)

- Chinese (Mandarin) (cmn) 0% (created Nov 23, 2013)
- Icelandic (is) 0%
- Italian (Italy) (it_IT) 0% 'Language without translators' (created Feb 8, 2015)
- Norwegian (no) 0%  'Language without translators' (created Apr 10, 2015)
- Norwegian Bokmål (nb) 0%  'Language without translators' (created Apr 10, 2015)
- Serbian (Serbia) (sr_RS) 0%  'Language without translators' (created Sep 25, 2016)

**Comment by shimizukawa** [comment]
done.
