### ISSUE TITLE
Need several image folders support for multilanguage doc

### ISSUE THREAD

**Issue by NtsDK** [sphinx-doc/sphinx#3216]
I'm working with Sphinx doc and I want to translate my documentation to other languages. I want to make images language dependent so screenshots in English will be in one folder and screenshots in German in other.

Currently Sphinx takes all images from /images folder. As I see in stackoverflow questions it is impossible to modify image directive path with variable substitutions.

Is it possible to have several image folders in Sphinx?

**Comment by tk0miya** [comment]
How about using `figure_language_filename`?
```
figure_language_filename = '{path}{language}/{basename}{ext}'
```
With the configuration, you can put images under language-named directory like `en/image.png`, `de/image.png` and so on.

**Comment by NtsDK** [comment]
tk0miya, thank you for your answer. It solves my problem. May I share your answer on [stackoverflow ](http://stackoverflow.com/questions/39008064/how-to-customize-sphinx-doc-images-folder) or you want to do it yourself?

**Comment by tk0miya** [comment]
Okay, please post this answer.

Note: The reference of `figure_language_filename`
http://www.sphinx-doc.org/en/stable/config.html#confval-figure_language_filename
