### ISSUE TITLE
Deprecate epub2 builder

### ISSUE THREAD

**Issue by tk0miya** [sphinx-doc/sphinx#3221]
Since 1.5, we've start to use epub3 builder by default for `make epub` command.
AFAIK, EPUB3 is upper compatible with EPUB2. So there is no reason to keep providing the epub2 builder.
To simplify our package, it would be nice if the builder would be removed in future version.
How about doing it in 1.6?

**Comment by shimizukawa** [comment]
+1 for removing.
I think we should emit DprecationWarning to remove the feature.
I wrote a deprecation policy document. Please read and give me your opinion.
http://www.sphinx-doc.org/en/1.5/devguide.html?highlight=deprecation#deprecation-policy

**Comment by tk0miya** [comment]
Note:
The epub3 builder is a derived class of epub2 builder.
Before deprecation, we have to split the implementation.
