### ISSUE TITLE
Define issue template

### ISSUE THREAD

**Issue by tk0miya** [sphinx-doc/sphinx#3222]
To resolve issues quickly, I'd like to define issue template for github.

* Environment info (cf. version of sphinx)
* Problem
* Error logs
* reproducible project / your project

Any ideas for question?

**Comment by shimizukawa** [comment]
Something like

[.github/ISSUE_TEMPLATE.md](https://github.com/blog/2111-issue-and-pull-request-templates):
```markdown
Subject: <what happen when you do on which document project>

# Problem
- <Detail of problem>

## Procedure to reproduce the problem
\```
<Paste your command-line here which cause the problem>
\```

## Error logs / results
\```
<Paste your error log here>
\```
- <public link of unexpected result if you have>

## Expected results
<Describe what to actually do>

# Reproducible project / your project
- <link to your project, or attach zipped small project sample>

# Environment info
- OS: <Unix/Linux/Mac/Win/other with version>
- Python version: 
- Sphinx version: 
- <Extra tools e.g.: Browser, tex or something else>
```

In addition, it is nice if we have CONTRIBUTING.md and PULL_REQUEST_TEMPLATE.md.

**Comment by shimizukawa** [comment]
Now I added a `.github/ISSUE_TEMPLATE.md`.

**Comment by tk0miya** [comment]
Looks great! It would be wonderful if we could use reStructured Text :-)

BTW, would you like to add also CONTRIBUTING and PULL_REQUEST_TEMPLATE?
If not, I will close this issue.

Thanks,

**Comment by shimizukawa** [comment]
Can someone do? (otherwise, I will)

**Comment by shimizukawa** [comment]
Last one is  `PULL_REQUEST_TEMPLATE.md`. somebody?

**Comment by jfbu** [comment]
with this template my mail client displays headers gigantically from using ``<h1>`` tag:

```
<p>It is not reproduced in the current version.<br>
I will close it.</p>
<h1>Environment info</h1>
<ul>
<li>OS: Windows 10</li>
<li>Python version: 3.5.2</li>
<li>Sphinx version:</li>
<li>TeX : TeX Live 2016</li>
</ul>
```
which showas as
![capture d ecran 2016-12-17 a 09 11 31](https://cloud.githubusercontent.com/assets/2589111/21285439/f274ab26-c438-11e6-9717-4d8f9416a7d0.png)

Could it be possible to use `##/###` markdown tags or even `###/####` ?

**Comment by tk0miya** [comment]
@jfbu Yes please.

**Comment by jfbu** [comment]
done at d8a420b.

**Comment by shimizukawa** [comment]
I added a PULL_REQUEST_TEMPLATE.md. @tk0miya, @jfbu if it's OK, please close this ticket.
