### ISSUE TITLE
Build fails with newer docutils version

### ISSUE THREAD

**Issue by skirpichev** [sphinx-doc/sphinx#3223]
Simple workaround (for me) is [adding conflict](https://github.com/diofant/diofant/pull/392) for newer docutils versions: <=0.12 works ok.

[An example](http://readthedocs.org/projects/diofant/builds/4772316/) of failure with traceback.  In [my project](https://github.com/diofant/diofant/) this happens because of [that part of code](https://raw.githubusercontent.com/diofant/diofant/master/docs/modules/vector/coordsys.rst):
```rst
.. only:: html

    The orientation is shown in the diagram below:

    .. image:: coordsys_rot.*
       :height: 250
       :width: 250
       :align: center
```

**Comment by tk0miya** [comment]
Thank you for reporting.
It was already fixed at #3217
