### ISSUE TITLE
Autosummary fails to import methods 

### ISSUE THREAD

**Issue by sirno** [sphinx-doc/sphinx#3232]
Hello,

trying to autodocument a small project using numpydocs is causing me some trouble. 

The code includes docstrings mostly conforming to the numpy docstring standard. 
In the method section numpydocs will either generate a table or generate an autosummary table containing the methods that are not summarized in the classes' docstring. 

Now the issue is that these methods can not be imported, resulting in a bunch of import errors:

`<path_to_rst>:<line>: WARNING: failed to import <method>`

where the generated file `<path_to_rst>` after preprocessing contains:
```
..autosummary::

    <method>
```
#
Is autosummary supposed to fail importing methods? or is this an issue with the way I set things up? 
May this be a bug in numpydocs, since the summary of methods is not supported?

**Comment by shimizukawa** [comment]
Actually I don't know the numpydoc completely, so I can't say anything.
Please let me know a procedure of making environment and also minimum example to reproduce the issue.
I think it is better way to discuss your problem with numpydoc author/team before here.

**Comment by sirno** [comment]
Yes, I wasn't sure where to post it, anyways I constructed an example that reproduces the warning. Only requirements are sphinx and numpydoc installed. `make html` then reproduces the warning:
[example.zip](https://github.com/sphinx-doc/sphinx/files/646696/example.zip)

**Comment by shimizukawa** [comment]
Thanks.
After several trial, I think it is a bug of numpydoc.
When extensions in conf.py doesn't have 'numpydoc', `import error` warning isn't appeared. So your example project works well without 'numpydoc' extension.

**Comment by shimizukawa** [comment]
Now I close this issue because there are nothing from Sphinx side.
Please contact to numpydoc author. Thanks.

**Comment by shimizukawa** [comment]
FYI.
```
$ make html SPHINXOPTS=-vvv
```
It display verbose information that have intermediate reST source what is generated by `autodoc` and/or  `numpydoc`. Please check a diff of with/without numpydoc extension.

**Comment by sirno** [comment]
Ok thanks, thats very helpful.
I think I know what might fix it, it should be possible to fix it in numpydoc by adding a line 
`.. currentmodule:: <class>`. Will try to do that.
