### ISSUE TITLE
Don't store modules and data to class attributes

### ISSUE THREAD

**Issue by tk0miya** [sphinx-doc/sphinx#3239]
# Problem
Some Sphinx API stores modules and data to class attribute.
For example, `Sphinx.add_transform()` stores transform class to `SphinxStandaloneReader`:
```
    def add_transform(self, transform):
        # type: (Transform) -> None
        self.debug('[app] adding transform: %r', transform)
        SphinxStandaloneReader.transforms.append(transform)
```
This causes these modules and data affect to other builds in same process.
We should store them to instance variables.

**Comment by shimizukawa** [comment]
Also `themes` and `themepath` attributes in `sphinx.theming.Theme`. (however these have no side-effect like SphinxStandaloneReader).

**Comment by tk0miya** [comment]
During 1.8 development, we've refactored much. So I'm closing this now.
Let's file a new issue if there were remaining tasks.
