### ISSUE TITLE
search.html fails with v1.5.1 (adds extra ".txt" extension)

### ISSUE THREAD

**Issue by jmckenna** [sphinx-doc/sphinx#3250]
- executing search.html?q=term   fails with version 1.5.1  (on TravisCI, and locally)
 - works fine with version 1.4.9
 - firebug shows the following in console:
```
  404 (not found)   /_sources/myfolder/filename.txt.txt
```
...where the correct file is named "filename.txt"

Similar errors occur for any search term (the extra ".txt" extension is added to every filename).

**Comment by shimizukawa** [comment]
Thanks for your reporting!

memo:
```
_build149rst/html/_sources:
index.txt

_build149txt/html/_sources:
index.txt

_build151rst/html/_sources:
index.rst.txt

_build151txt/html/_sources:
index.txt
```

_build149rst/html/_static/searchtools.js:
```JavaScript
$.ajax({url: DOCUMENTATION_OPTIONS.URL_ROOT + '_sources/' + item[0] + '.txt',
```
_build151rst/html/_static/searchtools.js
```JavaScript
$.ajax({url: DOCUMENTATION_OPTIONS.URL_ROOT + '_sources/' + item[5] + (item[5].slice(-suffix.length) === suffix ? '' : suffix),

**Comment by tk0miya** [comment]
@jmckenna What theme do you use?
if sphinx_rtd_theme, it's a bug of the theme: https://github.com/snide/sphinx_rtd_theme/pull/346 .

Thanks,

**Comment by jmckenna** [comment]
Confirmed.  I will close this ticket, as it is not a bug of Sphinx.   Thanks!

**Comment by jmckenna** [comment]
Sadly I am still facing this exact same issue, with Sphinx 2.0.0 and the latest sphinx-rtd-theme (?).

**Comment by jmckenna** [comment]
You can test it in action at https://mapserver.org/search.html

**Comment by jmckenna** [comment]
Using the recent sphinx-rtd-theme (0.4.3 released 2 months ago) and Sphinx 2.0.0:

   404 (not found)   /_sources/myfolder/filename.txt.txt

   ...where the correct file is named "filename.txt"

**Comment by fty48jj19** [comment]
e  vou dar demim para verificar os erros obrigado por mi reporta essa açao ,

**Comment by jmckenna** [comment]
Reopening: the issue still exists for Sphinx 2.0.0 release.   In fact we are not using the "sphinx-rtd-theme" theme, we are using the "classic" Sphinx theme in conf.py:

````
    # Set the theme explicitly
    html_theme = "classic"
````

**Comment by jmckenna** [comment]
Does the "classic" Sphinx theme use the Alabaster theme deep in the code of Sphinx?   (in other words: using the "classic" theme, where in the code is this search function handled??)

**Comment by jmckenna** [comment]
Could it be that our original conf.py (I believe settings have existed long before the 'classic' theme was created) contains parameters from the Alabaster theme?   See our conf.py at https://github.com/mapserver/docs/blob/branch-7-2/conf.py

**Comment by jmckenna** [comment]
Maybe I need to change from html_theme = "classic" to html_theme = "alabaster" ?  (I believe someone else added that theme= parameter to our conf)

**Comment by jmckenna** [comment]
I filed this as an Alabaster theme ticket instead. https://github.com/bitprophet/alabaster/issues/155
