### ISSUE TITLE
Search does not work for docs generated using sphinx 1.5.1

### ISSUE THREAD

**Issue by dkliban** [sphinx-doc/sphinx#3258]
I have a Jenkins job that builds docs nightly for http://pulpproject.org/docs. I noticed that the search stopped working recently. I was able to determine that the broken search appeared after Jenkins started using sphinx 1.5.1 to generate the docs. Using sphinx 1.4.8 resolves the problem.

**Comment by tk0miya** [comment]
Same as #3203 .
Sorry, it is a bug of sphinx_rtd_theme.
