### ISSUE TITLE
sphinxcontrib.matlab and sphinx.ext.autodoc are incompatible

### ISSUE THREAD

**Issue by erxnmedia** [sphinx-doc/sphinx#3269]
Subject: If you put one before the other it overrides methods and either Matlab or Python will work but not both

### Problem
Depending on this order:

extensions = [
    'sphinxcontrib.matlab',
    'sphinx.ext.autodoc',

I will get this or vice versa:

WARNING: while setting up extension sphinxcontrib.matlab: directive 'automodule' is already registered, it will be overridden
WARNING: while setting up extension sphinxcontrib.matlab: directive 'autoclass' is already registered, it will be overridden
WARNING: while setting up extension sphinxcontrib.matlab: directive 'autoexception' is already registered, it will be overridden
WARNING: while setting up extension sphinxcontrib.matlab: directive 'autodata' is already registered, it will be overridden
WARNING: while setting up extension sphinxcontrib.matlab: directive 'autofunction' is already registered, it will be overridden
WARNING: while setting up extension sphinxcontrib.matlab: directive 'automethod' is already registered, it will be overridden
WARNING: while setting up extension sphinxcontrib.matlab: directive 'autoattribute' is already registered, it will be overridden
WARNING: while setting up extension sphinxcontrib.matlab: directive 'autoinstanceattribute' is already registered, it will be overridden

#### Procedure to reproduce the problem
 As above

#### Error logs / result
Using one order autodoc will work for Python but not Matlab, using the other order, Matlab but not Python, even if you put in a Domain directive.

#### Expected results
I want to be able to document Matlab and Python in the same project.

### Environment info
- OS: Windows 
- Python version: Python 2.7
- Sphinx version: 1.5

**Comment by tk0miya** [comment]
Did you mean this is a bug of sphinx? It seems a bug of sphinxcontrib.matlab for me.

Anyway, what is `sphinxcontrib.matlab`? Did you mean `sphinxcontrib-matlabdomain`?
Unfortunately, I don't know the package. so I could not reproduce the problem.
https://pypi.python.org/pypi/sphinxcontrib-matlabdomain

Thanks,
