### ISSUE TITLE
How to create extension with own `ref`-derived role?

### ISSUE THREAD

**Issue by rprots** [sphinx-doc/sphinx#3273]
### Problem
Seems to be the same as http://stackoverflow.com/questions/38943023/sphinx-custom-role

**Comment by rprots** [comment]
Resolution: https://groups.google.com/forum/#!topic/sphinx-users/6Sb_9s3EgFg

**Comment by tk0miya** [comment]
Is it resolved?

Anyway, this is list of sphinx issues. Not mailing list.
Please post your question to sphinx-dev list.
https://groups.google.com/forum/#!forum/sphinx-dev

Thanks,
