### ISSUE TITLE
List of parameters overflows 'Parameter:' in Alabaster theme when napoleon 'Returns:' statement spans two or more lines

### ISSUE THREAD

**Issue by benjaminweb** [sphinx-doc/sphinx#3276]
### Problem
See how the list of parameters overflows 'Parameters:' caption.

![sepcaus](https://cloud.githubusercontent.com/assets/1290837/21444909/2994b1c2-c8b3-11e6-8f99-1337c44e99fe.png)

That occurs when 'Returns:' or 'Raises:' (sphinx.ext.napoleon) spans on multiple lines.
It starts with two lines to occur. The left-indent increases with each subsequent line.

#### Procedure to reproduce the problem

```
  $ unzip alabaster.zip # see below for attached file
  $ cd albaster/doc
  $ make html
  $ open _build/html/index.html
```
#### Expected results
The list of parameters should begin after the colon of 'Parameters:' like here:

![decimal_gcd](https://cloud.githubusercontent.com/assets/1290837/21445190/2e22b254-c8b6-11e6-8eee-7b9c49ad2748.png)

### Reproducible project / your project

See [alabaster.zip](https://github.com/sphinx-doc/sphinx/files/670163/alabaster.zip).

### Environment info
- OS: Mac OS X El Capitain 10.11.6 (15G1212)
- Python version: 3.5.2
- Sphinx version: 1.4.9+
- Used extensions: sphinx.ext.autodoc, sphinx.ext.napeleon

**Comment by RobRuana** [comment]
Thanks for the report! I'm looking into it!

**Comment by RobRuana** [comment]
It looks like this issue is a direct result of this [pull request](https://github.com/sphinx-doc/sphinx/pull/2301), because the `<th>` element is inheriting its `hyphens` attribute from its parent `<dd>` element.

Does anyone object to me adding a more specific rule in `basic.css` to fix this issue for field names?

Something like this: (`manual` is the default value for `hyphens`)
```
.field-name {
    -moz-hyphens: manual;
    -ms-hyphens: manual;
    -webkit-hyphens: manual;
    hyphens: manual;
}
```

**Comment by RobRuana** [comment]
As an aside, thank you for the excellent bug report. Very clear, plus included a reproducible product! Excellent!

**Comment by benjaminweb** [comment]
@RobRuana Thanks for your timely fix. I confirm the complete resolution of the reported problem.

**Comment by bitprophet** [comment]
Belatedly, I just ran into this (was tracking under bitprophet/alabaster#95) and independently confirmed the same cause/effect. 👍
