### ISSUE TITLE
Tests: Allow specific tests to be disabled

### ISSUE THREAD

**Issue by FRidh** [sphinx-doc/sphinx#3277]
### Problem
- `make test` doesn't seem to provide a way to disable specific tests. On our distribution we run tests when building packages. Because network access is disabled during building/testing certain tests fail. With e.g. `py.test` it is straightforward to disable a test with the `-k` option.

#### Procedure to reproduce the problem
```
make test
```

### Environment info
- OS: NixOS / Nix package manager
- Python version: any
- Sphinx version: 1.5.1

**Comment by tk0miya** [comment]
+1
Pull requests are all ways welcome :-)

**Comment by FRidh** [comment]
Simple solution: use `NOSE_EXCLUDE` since `run.py` calls `nose` and `nose` respects that environment variable.


The following is what I was writing before finding the solution I just described.

In my opinion the best solution is to just run the test runner, without invoking some custom script. That is, get rid of `run.py` and just invoke `nosetests` or `py.test`.

Temporary directory handling is done in `run.py`. I think that should be handled by the tests, they should call something like `tempdir.makedirs()` and that function makes sure it's cleared, possibly using the environment variable. Basically shifting this code into `util.py` should be sufficient.

At that point it is I think possible to just run `nosetests` and get rid of `run.py`. Here it is I saw `nose` was invoked and arguments passed to `run.py` are passed to `nose`.

**Comment by tk0miya** [comment]
Thank you for advice.
But, unfortunately, we don't have enough time to improve test toolkit.
Once we talked about moving to py.test and others. But nothing changed ever.
If you are interested in improving, please send us pull request.

Thanks,
