### ISSUE TITLE
autosummary escaping *'s

### ISSUE THREAD

**Issue by LevN0** [sphinx-doc/sphinx#3285]
Between sphinx 1.4.6 and 1.4.8 there seems to have been made a change, where autosummary will escape *s. 

For example, it might generate,

ClassName(\\\*args, \\\*\\\*kwds) 	Description of class.

Tried 1.5.1 and obtained same result. Just downgrading to 1.4.6 solves this.
 
Possibly introduced by https://github.com/sphinx-doc/sphinx/commit/8d96c90fc6ca7805ba7a8e8fd80cc74da7caf46c

**Comment by naoyak** [comment]
We had this issue with scikit-learn docs as well.

Here is a build with 1.4.6: https://5815-843222-gh.circle-artifacts.com/0/home/ubuntu/scikit-learn/doc/_build/html/stable/modules/generated/sklearn.pipeline.Pipeline.html#sklearn.pipeline.Pipeline
And with 1.4.8: https://6137-843222-gh.circle-artifacts.com/0/home/ubuntu/scikit-learn/doc/_build/html/stable/modules/generated/sklearn.pipeline.Pipeline.html#sklearn.pipeline.Pipeline

I opened a PR at #3344 - thanks in advance!

**Comment by tk0miya** [comment]
Fixed at bfcb92f.
Thank you for reporting!

**Comment by naoyak** [comment]
Thanks! This fixes the issue for scikit-learn docs.
