### ISSUE TITLE
The table in exported EPUB doesn't pass EpubCheck validation

### ISSUE THREAD

**Issue by cwchentw** [sphinx-doc/sphinx#3287]
Subject: The table in exported EPUB doesn't pass EpubCheck validation

### Problem
As mentioned, the HTML code of table in EPUB, which generated by Sphinx, doesn't pass EpubCheck validation and there is no proper way to change it.

#### Procedure to reproduce the problem

Here is a sample that reproduces the problem.

```
.. table:: Truth table of AND
   :widths: auto

   ======= ====== =======
   p       q      Resutl
   ======= ====== =======
   true    true   true
   true    false  false
   false   true   false
   false   false  false
   ======= ====== =======
```

#### Error logs / results

If the caption is included, EpubCheck produces the following error:

```
'The element type "span" must be terminated by the matching end-tag "</span>".'
```

If the caption is removed, EpubCheck produces the following error:

```
'attribute "width" not allowed here;
# Some message omitted.

'attribute "valign" not allowed here;
# Some message omitted.
```

Here is the related excerpt of the generated XHTML code:

```
<h1>Welcome to Buggy Book&#8217;s documentation!</h1>
<table border="1" class="colwidths-auto docutils" id="id1">
<caption><span class="caption-text">Truth table of AND</caption>
<colgroup>
<col width="35%" />
<col width="30%" />
<col width="35%" />
</colgroup>
<thead valign="bottom">
<tr class="row-odd"><th class="head">p</th>
<th class="head">q</th>
<th class="head">Resutl</th>
</tr>
</thead>
<!-- other part omitted --!>
```

#### Expected results
The EPUB output passes EpubCheck validation 

### Reproducible project / your project
https://github.com/cwchentw/buggy-book-demo-in-Sphinx

### Environment info
- OS: Mac 10.11.6
- Python version: 3.5.2
- Sphinx version: 1.5.1

**Comment by tk0miya** [comment]
Thank you for reporting.
I fixed mismatched `<span>` tag at 60b7bfd.

On the other hands, other problem will not be resolved easily.
At this moment, Sphinx generates HTML files as HTML4. And EPUB spec expects them as HTML5.
We have to work hard to support HTML5.
refs: #2371

**Comment by tk0miya** [comment]
An experimental HTML5 writer is now introduced at #3464.
Thanks,

**Comment by tk0miya** [comment]
Unfortunately, new HTML5 writer also has same issue (refs: #1562)

**Comment by shibukawa** [comment]
I confirmed this issue was fixed in a master branch. 1.6 includes this fix.

```html
<table class="colwidths-auto docutils" id="id1">
<caption><span class="caption-text">Truth table of AND</span></caption>
<thead>
<tr class="row-odd"><th class="head"><p>p</p></th>
<th class="head"><p>q</p></th>
<th class="head"><p>Resutl</p></th>
</tr>
</thead>
<tbody>
<tr class="row-even"><td><p>true</p></td>
<td><p>true</p></td>
<td><p>true</p></td>
</tr>
<tr class="row-odd"><td><p>true</p></td>
<td><p>false</p></td>
<td><p>false</p></td>
</tr>
<tr class="row-even"><td><p>false</p></td>
<td><p>true</p></td>
<td><p>false</p></td>
</tr>
<tr class="row-odd"><td><p>false</p></td>
<td><p>false</p></td>
<td><p>false</p></td>
</tr>
</tbody>
</table>
```
