### ISSUE TITLE
shall_skip doesn't safely access 'implicit_namespaces' option

### ISSUE THREAD

**Issue by dusktreader** [sphinx-doc/sphinx#3290]
Subject: `shall_skip` doesn't use `getattr` to get `implicit_namespaces`

### Problem
- The recurse_tree method safely accesses attributes of the `opts` because they may not exist on the opts object. However, the `shall_skip` method accesses the `implicit_namespaces` attribute directly, causing it to fail if the `opts` object has no `implicit_namespaces` attribute

#### Procedure to reproduce the problem
```
        opts = types.SimpleNamespace(
            output_dir=self.build_dir,
            maxdepth=2,
            force=True,
            no_toc=True,
            module_first=True,
            suffix=self.fetch_ext_from_index(),
            implicit_namespaces=False,
        )
        modules = sphinx.apidoc.recurse_tree(self.root_dir, [], opts)
```

#### Error logs / results
```
Traceback (most recent call last):
  File "bin/sphinx-view", line 61, in <module>
    (server, builder) = create_server(**config)
  File "/Users/tbeck/work/sphinx-view/sview/server.py", line 46, in create_server
    builder.build()
  File "/Users/tbeck/work/sphinx-view/sview/builder.py", line 126, in build
    self.api_doc()
  File "/Users/tbeck/work/sphinx-view/sview/builder.py", line 106, in api_doc
    modules = sphinx.apidoc.recurse_tree(self.root_dir, [], opts)
  File "/Users/tbeck/.virtualenvs/sview/lib/python3.5/site-packages/sphinx/apidoc.py", line 245, in recurse_tree
    if not shall_skip(path.join(rootpath, py_file), opts):
  File "/Users/tbeck/.virtualenvs/sview/lib/python3.5/site-packages/sphinx/apidoc.py", line 171, in shall_skip
    if not opts.implicit_namespaces and not path.exists(module):
AttributeError: 'types.SimpleNamespace' object has no attribute 'implicit_namespaces'
```

#### Expected results
Should not fail if opts has no implicit_namespaces attribute. Should treat non-existence as False. 

### Reproducible project / your project
- https://github.com/dusktreader/sphinx-view/tree/dusktreader/apidoc-bug

### Environment info
- OS: OSX El Capitan
- Python version: 3.5
- Sphinx version: 1.5

**Comment by tk0miya** [comment]
@shimizukawa Is this expected behavior?
It seems only `apidoc.recurse_tree()` access through `getattr`. But other functions does not use it.
I don't feel this is important.

**Comment by tk0miya** [comment]
-1; I think this is not important for Sphinx. It's not correct opts object for apidoc. The interface is not public one. So I'd like to keep as is.

**Comment by tk0miya** [comment]
I'm closing this now.
Thank you for proposal!
