### ISSUE TITLE
Bug in the add_latex_package() function

### ISSUE THREAD

**Issue by paternal** [sphinx-doc/sphinx#3294]
Subject: The [`add_latex_package`](https://github.com/sphinx-doc/sphinx/blob/ef60dbfce09286b20b7385333d63a60321784e68/sphinx/application.py#L859) method seems to be broken

### Problem
- When writing a sphinx extension calling the `add_latex_package` method (for instance ``app.add_latex_package("babel")``), an exception is raised (see below).

#### Procedure to reproduce the problem

A minimal working example has been created in https://github.com/paternal/sphinx-bug-mwe. Its only differences from the setup created by command `sphinx-quickstart` are:

- a [dummy extension](https://github.com/paternal/sphinx-bug-mwe/blob/master/foo.py) is created ;
- this extension [is loaded](https://github.com/paternal/sphinx-bug-mwe/blob/master/conf.py#L33).

Then, I try to build the documentation using:

```
make html
```

#### Error logs / results
```
$ make html
Running Sphinx v1.5.1

Exception occurred:
  File "/home/louis/.virtualenvs/sphinx-mwe/local/lib/python2.7/site-packages/sphinx/application.py", line 809, in add_latex_package
    self.builder.usepackages.append((packagename, options))
AttributeError: 'NoneType' object has no attribute 'usepackages'
The full traceback has been saved in /tmp/sphinx-err-EpYThM.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Makefile:20 : la recette pour la cible « html » a échouée
make: *** [html] Erreur 1
```

Content of the `/tmp/sphinx-err-XXX.log` file:
~~~
# Sphinx version: 1.5.1
# Python version: 2.7.13 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.8.1
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/home/louis/.virtualenvs/sphinx-mwe/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 295, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/louis/.virtualenvs/sphinx-mwe/local/lib/python2.7/site-packages/sphinx/application.py", line 199, in __init__
    self.setup_extension(extension)
  File "/home/louis/.virtualenvs/sphinx-mwe/local/lib/python2.7/site-packages/sphinx/application.py", line 523, in setup_extension
    ext_meta = mod.setup(self)
  File "/home/louis/projets/_contrib/sphinx-bug-mwe/foo.py", line 2, in setup
    app.add_latex_package("babel")
  File "/home/louis/.virtualenvs/sphinx-mwe/local/lib/python2.7/site-packages/sphinx/application.py", line 809, in add_latex_package
    self.builder.usepackages.append((packagename, options))
AttributeError: 'NoneType' object has no attribute 'usepackages'
~~~

#### Expected results
I expect the documentation to build flawlessly.

### Reproducible project / your project
https://github.com/paternal/sphinx-bug-mwe

### Environment info
- OS: Debin Testing
- Python version: Python 2.7.13
- Sphinx version: 1.5.1 (I checked, and it worked up to version 1.4.9, and stopped working from version 1.5)

**Comment by tk0miya** [comment]
Thank you for reporting.
Fixed at 54cac94.
