### ISSUE TITLE
Doctest execution only for specific Python versions

### ISSUE THREAD

**Issue by marco-buttu** [sphinx-doc/sphinx#3303]
Sometimes it is useful to execute a doctest only for specific Python versions. For instance, think at the Python documentation: if the doc explains a new feature available from Python 3.6, I would like the code example to be doctested only for Python >= 3.6. I was thinking to add an option like this one:
```
.. doctest::
   :pyversion: >= 3.6
```

In that case, also the testsetup, testcleanup and testcode directives should have this option. What do you think?

**Comment by tk0miya** [comment]
+1
