### ISSUE TITLE
Could not import extension sphinx.builders.linkcheck (exception: cannot import name SSLError)

### ISSUE THREAD

**Issue by jamercee** [sphinx-doc/sphinx#3307]
### Problem
We create a new project using `sphinx-quickstart`. Accept all defaults. Immediately try `make html`, and receive the following error:

`Could not import extension sphinx.builders.linkcheck (exception: cannot import name SSLError)`

### Environment info
- OS: Debian Jessie
- Python version: 2.7.9
- Sphinx version: 1.5.1

**Comment by tk0miya** [comment]
Same as #3268.

**Comment by jamercee** [comment]
Brilliant -- thanks.
