### ISSUE TITLE
add and crossreference labels in docstrings ?

### ISSUE THREAD

**Issue by samotracio** [sphinx-doc/sphinx#3325]
Is it possible to define a label for a section in a docstring and then cross-reference that label from other parts of the docstring?  In modu.py I have a function : 

    def foo(x, y):
        """  This routine does bla bla bla...
 
        Parameters
        ---------------
        x : float 
            First number
        y : float 
            Second number. See :ref:`thisnote` below
    
        .. _thisnote:
        
        Notes
        --------
        Some warning text....  
        """  

modu.py is then parsed by autodoc from an api.rst file 

        API Reference
        =============

        .. automodule:: modu
                 :members: foo

Doing a "make html" complains that there is no reference label defined, and indeed, the label .. _thisnote: is always interpreted as plain text. Surely I must be missing something big or I am too naive expecting labels and refs to work in docstrings

**Comment by tk0miya** [comment]
Did you check the warning messages?
At my local, I got following messages:
```
/Users/tkomiya/work/tmp/doc/modu.py:docstring of modu.foo:4: SEVERE: Unexpected section title.

Parameters
---------------
/Users/tkomiya/work/tmp/doc/modu.py:docstring of modu.foo:13: SEVERE: Unexpected section title.

Notes
--------
```
```
/Users/tkomiya/work/tmp/doc/index.rst:15: WARNING: undefined label: thisnote (if the link has no caption the label must precede a section header)
```

This describes

* You can't use sections in docstrings
* That causes `:ref:` role unlinkable because of no captions

So you can use cross references if there are no sections. For example, following works well.
```
def foo(x, y):
    """  This routine does bla bla bla...

    .. rubric:: Parameters

    x : float_
        First number
    y : float_
        Second number. See :ref:`Notes <thisnote>` below

    .. _thisnote:

    .. rubric:: Notes

    Some warning text....
    """
```

**Comment by samotracio** [comment]
Thanks for the reply @tk0miya . Indeed, your example using rubric works fine, albeit with two minor caveats : 
(1) Changes the HTML rendering : Parameters and Notes are rendered differently and the list of parameters x,y,z,.... also appears different.
(2) The :ref: linking works ok within the same docstring and when put in other .rst files. It doesn't work however from docstrings of other functions

I am a complete novice in RST and Sphinx, but from the documentation I understood that writing

        Parameters
        ----------
        (...some pars...)

        Notes
        -----
        (...some text...)

makes the sections recognizable in an RST file, and indeed, when they are scanned from a docstring and parsed by autodoc somehow they get recognized and rendered as should. Just type "Paramoters" instead of "Parameters" to trigger a warning -> "UserWarning: Unknown section..." , suggesting that sections are being recognized. Only when labels and :ref: are added things break down. BTW, I do not get any of  "SEVERE: Unexpected section title"

Anyway, thanks for your time!

**Comment by RobRuana** [comment]
It looks like you are using NumPyDoc style docstrings. Try adding an additional line break after the `Parameters` section, like so:

```
def foo(x, y):
    """  This routine does bla bla bla...

    Parameters
    ---------------
    x : float 
        First number
    y : float 
        Second number. See :ref:`thisnote` below


    .. _thisnote:
    
    Notes
    --------
    Some warning text....  
    """
```

Sections breaks are created with two blank lines, so I'm guessing `.. _thisnote:` was being scooped up into the `Parameters` section.

**Comment by samotracio** [comment]
Great suggestion. Thanks! Unfortunately works halfway. It seems like labels sandwiched between sections are parsed wrong. Please check this 3 examples.

This works wonderful

    def foo(x, y):
        """  This routine does bla bla bla...lots of text...Please check :ref:`Parameters <somelabel>`

        .. _somelabel:
    
        Parameters
        ---------------
        x : float 
            First number
        y : float 
            Second number. See :ref:`thisnote` below
    
        Notes
        --------
        Some warning text....  
        """

But this breaks down and indeed looks like the .._somelabel: definition is stuck within the scope of the upper section and rendered like the parameter x or y. Does not matter how many line breaks in between

    def foo(x, y):
        """  This routine does bla bla bla...lots of text...Please check :ref:`Notes <somelabel>`
   
        Parameters
        ---------------
        x : float 
            First number
        y : float 
            Second number. See :ref:`thisnote` below


        .. _somelabel:
    
        Notes
        --------
        Some warning text....  
        """

Finally, moving the label below the Notes section heading seems to work again !

    def foo(x, y):
        """  This routine does bla bla bla...lots of text...Please check :ref:`Notes <somelabel>`
   
        Parameters
        ---------------
        x : float 
            First number
        y : float 
            Second number. See :ref:`thisnote` below
    
        Notes
        --------
        .. _somelabel:

        Some warning text....  
        """

**Comment by RobRuana** [comment]
I think the issue is that the `Notes` header doesn't really start a new section, so sphinx doesn't know what label to use for ``:ref:`thisnote` ``. It should work as expected if you use the angle brackets in your reference ``:ref:`Notes <thisnote>` ``.

So the docstring should be like this:

```
def foo():
    """  This routine does bla bla bla...lots of text...

    Parameters
    ---------------
    x : float
        First number
    y : float
        Second number. See :ref:`Notes <thisnote>` below


    .. _thisnote:

    Notes
    --------
    Some warning text....
    """
```
