### ISSUE TITLE
Sphinx should provide a syntax for providing "Usage" or "Syntax" for stand alone scripts/applications

### ISSUE THREAD

**Issue by pburdine** [sphinx-doc/sphinx#3326]
### Problem
Currently Sphinx offers a lot in the way of documenting APIs for Python code (http://www.sphinx-doc.org/en/1.5.1/domains.html#the-python-domain), but there doesn't seem to be any obvious way at a script/module level for documenting how the script/module should/can be used from the command line.  Originally I was looking for a way to use the Napoleon syntax for my scripts, but there isn't an obvious choice there either (https://sphinxcontrib-napoleon.readthedocs.io/en/latest/#id1).  

If there was a way to do the following:
1) Have a "Usage:" or "Syntax:" or similar header that would translate well into Sphinx/Napoleon for script/module CLI usage.
2) Have the ability to include the usage information from an argparse object.

Currently I take my modules, run them on the CLI to get the argparse help, then go back and update the doc strings to make man/info pages out of them.  Then I try to use the "Args:" header at the module level to document how each of the options/args should be used and valid values for them.  However this doesn't work very well because putting "Syntax:" or "Usage:" followed by some information doesn't create its own sections that stand out.  Especially when they are followed by "Args:", "Note:", or "Example:"

Am I missing some or can this be added?

Currently we are using Sphinx 1.4.8.

**Comment by RobRuana** [comment]
Check out the [autoprogram](https://pythonhosted.org/sphinxcontrib-autoprogram/) sphinx extension. I think it'll do exactly what you are looking for :)

**Comment by pburdine** [comment]
Yes, it does.  Thank you!  Any plans on adding this to the distro like Napoleon?

Warning to those that find this, the 0.1.3 release of autoprogram on pypi doesn't work on Python 2 without modifying the source files.
https://bitbucket.org/birkenfeld/sphinx-contrib/issues/169/incompatibility-with-python-2
Fix was supposedly checked in 3 months ago, but they haven't released a version since then.

**Comment by RobRuana** [comment]
I don't think there are any plans on adding it the main distro.

It may be worthwhile to add a comment to that [issue](https://bitbucket.org/birkenfeld/sphinx-contrib/issues/169/incompatibility-with-python-2) asking if they plan to roll a new release including that fix. That may have just been an oversight.
