### ISSUE TITLE
few Docstring Sections not working

### ISSUE THREAD

**Issue by aztrock** [sphinx-doc/sphinx#3331]
Subject: few Docstring Sections not working, most exactly [http://www.sphinx-doc.org/en/1.5.1/ext/napoleon.html#docstring-sections](url)

### Problem
    """Table for administrator, marked in Mode.. ts User with is_superuser=True list.

    Args:
        tables.Table (:obj:`django_tables2`): Inheritance from django_tables2.

    Attributes:
        country: Name country and city

    Todo:
        Not working

    .. todo::
        Working

    .. versionchanged:: 3.0
        Add new column ACD, ASR, TC, TF, TA, ROL.

    """

#### Error logs / results
[http://www.sphinx-doc.org/en/1.5.1/ext/napoleon.html#docstring-sections](url)

### Environment info
- OS: GNU/Linux Debian 9
- Python version: 3.5.2
- Sphinx version: 1.5.1
- Django version: 1.10.4

**Comment by RobRuana** [comment]
Can you verify that you have `sphinx.ext.napoleon` enabled in your `conf.py`? Like this:
```
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.napoleon',
    # ... any other extensions you'd like to enable
    ]
```

If so, can you verify that you have set `napoleon_google_docstring = True`? This is the default, so if that setting is missing it should still be working. Just make sure it's not set to `False`.

**Comment by aztrock** [comment]
I  have this:

```
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.napoleon',
    'sphinx.ext.coverage',
    'sphinx.ext.todo',
    'sphinx.ext.doctest',
    'sphinx.ext.viewcode',
    'celery.contrib.sphinx'
]
```

**Comment by RobRuana** [comment]
Can you verify that `napoleon_google_docstring = True` in your `conf.py`?

**Comment by tk0miya** [comment]
I understand what happened in this report. You need to set `todo_include_todos = True` to show todo blocks.
