### ISSUE TITLE
Ugly rendering of definition list term's classifier

### ISSUE THREAD

**Issue by lelit** [sphinx-doc/sphinx#3337]
I tried using the _classifiers_ on a [definition list](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#definition-lists) terms, but the result is not what I'd expected.

The following snippet
```
term : classifier
  description of term
```

is transformed to the following HTML snippet by current (1.5.1) Sphinx:
```html
<dl class="docutils">
<dt>term</dt>
 <span class="classifier-delimiter">:</span> <span class="classifier">classifier</span><dd>description of term</dd>
</dl>
```

that renders like:
```
term
: classifier
    description
```

Standard docutils (0.13.1) produces:
```html
<dl class="docutils">
<dt>term <span class="classifier-delimiter">:</span> <span class="classifier">classifier</span></dt>
<dd>description of term</dd>
</dl>
```

which looks nicer:
```
term : classifier
    description
```

I see that Sphinx's HTML writer [overrides](https://github.com/sphinx-doc/sphinx/blob/e7469eb32ccd357cd1bb83faca5bb22604a46ce0/sphinx/writers/html.py#L705) the `depart_term()` and `visit_definition()` docutils methods so it seems done on purpose, and I wonder if there is some CSS trick and/or customization I could apply to restore the original aspect.

**Comment by tk0miya** [comment]
It was rendered correctly at v1.3.6, but it was broken since v1.4.
It seems #2318 breaks the rendering.

In docutils, `<dt>` tag is generated at `visit_term()` and `visit_definition` (It' asymmetric...).
```
    def visit_term(self, node):
        self.body.append(self.starttag(node, 'dt', ''))

    # ersatz for first/last pseudo-classes
    def visit_definition(self, node):
        self.body.append('</dt>\n')
        self.body.append(self.starttag(node, 'dd', ''))
        self.set_first_last(node)
```

But sphinx overrides them like following:
```
    # overwritten (but not changed) to keep pair of visit/depart_term
    def visit_term(self, node):
        self.body.append(self.starttag(node, 'dt', ''))

    # overwritten to add '</dt>' in 'depart_term' state.
    def depart_term(self, node):
        self.body.append('</dt>\n')

    # overwritten to do not add '</dt>' in 'visit_definition' state.
    def visit_definition(self, node):
        self.generate_targets_for_listing(node)
        self.body.append(self.starttag(node, 'dd', ''))
        self.set_first_last(node)
```

So we should two ways to fix this.
The first is to remove overriding methods from our writer.
The another is to handle correctly classifier node.
I don't know which is simple or easy way to do that.

@shimizukawa could you give me your advice?

**Comment by shimizukawa** [comment]
I've fixed by the first idea of @tk0miya.
Thanks for your reporting!
