### ISSUE TITLE
Missing prompt syntax highlighting in code-block and doctest with options

### ISSUE THREAD

**Issue by marco-buttu** [sphinx-doc/sphinx#3338]
### Problem

If I write an example using the `code-block` or `doctest` directive, using some options, the prompt syntax highlight is not applied. For instance, let's have this example:
   
```
.. doctest::
   :options: +SKIP

    >>> a = 33
    >>> a
    33
```
In this case the prompt (` >>>`) syntax highlighting is not applied. I looked both at the HTML and LaTex output. Here is a screenshot of the HTML output:

![doctest_options](https://cloud.githubusercontent.com/assets/3822393/21946325/31395fca-d9e0-11e6-9319-fa4068329ff2.png)

The reason of this issue is that, in case of options, the raw source code has a wrong indentation: one extra whitespace at the beginning of the line. For instance, this code:

```
.. code-block:: python
   :linenos:
   
   >>> a = 33
```

will generate the source `' >>> a = 33'` instead of `'>>> a = 33'`. That is a problem because 
[here](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/highlighting.py#L98) all of the tests `if source.startswith('>>>'):` will fail. I do not know where is the root source of the problem, but my feeling is that there is a bug in the docutils library. In any case, if we want we can easily fix the problem from our side, by removing (in [highlight_block()](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/highlighting.py#L98)) the extra indentation at the beginning of every source line, in case the first one starts with `' >>>'`. 

### Environment info
- OS: Linux Mint
- Python version: 3.7.0a0, 3.6, 3.
- Sphinx version: 1.6b1, 1.3.6

**Comment by marco-buttu** [comment]
@tk0miya unfortunately it is a core problem, not just of the doctest extension :( I got where the problem is (look at the description above), and I also have a test that fails. How can we proceed? Can I send I pull request with just the test that fails, and after I work on the bug fix?

**Comment by tk0miya** [comment]
reST spec says directive block is a subsequent indented text.

>The directive block is consists of any text on the first line of the directive after the directive marker, and any subsequent indented text. The interpretation of the directive block is up to the directive code. There are three logical parts to the directive block:
>
>Directive arguments.
>Directive options.
>Directive content.
>http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#directives

But it seems your directive content is deeper than the directive option. reST expects directive blocks starts with same indent level. So this is a mistake of mark up.
Please remove a space of directive content or add a space to directive option.

**Comment by marco-buttu** [comment]
You are right, I did not know that specification :-) I am sorry for your loosing of time, thansk
