### ISSUE TITLE
Replace the custom smartypants code with docutils’ smart_quotes

### ISSUE THREAD

**Issue by mitya57** [sphinx-doc/sphinx#3345]
Sphinx currently uses [its own code](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/util/smartypants.py) to handle the [`html_use_smartypants`](http://www.sphinx-doc.org/en/latest/config.html#confval-html_use_smartypants) option. However, that uses a hard-coded set of quotes for every language: `“”` and `‘’`.

That is not optimal for some languages: i.e. in Russian we use `«»`, and in German `„“` are used instead.

Docutils has a [`smartquotes.py` file](https://sourceforge.net/p/docutils/code/HEAD/tree/trunk/docutils/docutils/utils/smartquotes.py) since version 0.10 (released in 2012), which provides support for 27 different languages, and takes the current block language into account.

Sphinx already [depends](https://github.com/sphinx-doc/sphinx/blob/master/setup.py#L48) on docutils ≥ 0.11, so in my opinion the custom code for smartypants can be dropped, and the `html_use_smartypants` can be mapped directly to docutils’ [`smart_quotes`](http://docutils.sourceforge.net/docs/user/config.html#smart-quotes) configuration option.

What do you think?

**Comment by tk0miya** [comment]
I don't have strong opinion because my mother language (Japanese) does not have a concept of smartypants. I really don't know much about it...

**Comment by mitya57** [comment]
Actually the docutils code has something for Japanese too:
```python
'ja':           u'「」『』',
```
