### ISSUE TITLE
Search is broken (as in: JS is broken)

### ISSUE THREAD

**Issue by quasipedia** [sphinx-doc/sphinx#3347]
### Problem
On a freshly generated site, entering any term as a search query will bear a stuck "three dots blinking" and no results.

#### Procedure to reproduce the problem
conf.py
```
html_theme = 'sphinx_rtd_theme'
html_show_sourcelink = False
html_sourcelink_suffix = 'txt'
```
command
```
sphinx-build -b html -n -W -d _build/doctrees  doc _build/html
```

#### Error logs / results
![xxx](https://cloud.githubusercontent.com/assets/309045/21992192/ce75a4e2-dc15-11e6-83d5-b17823684779.png)

I should add that I checked `searchindex.js` and the payload of `Search.setIndex` is a totally fine js object, that can be read, parsed and used in the console and on node.

The topmost file in the stack trace has:
```        } else if (DOCUMENTATION_OPTIONS.HAS_SOURCE) {
          var suffix = DOCUMENTATION_OPTIONS.SOURCELINK_SUFFIX;
          $.ajax({url: DOCUMENTATION_OPTIONS.URL_ROOT + '_sources/' + item[5] + (item[5].slice(-suffix.length) === suffix ? '' : suffix),
```
Yet... the suffix seem to be `undefined` for some reason.

#### Expected results
To find document matching my query!

### Environment info
- OS: Fedora 25 64 bit
- Python version: 3.5.2 
- Sphinx version: 1.5.1

**Comment by tk0miya** [comment]
Same as #3203 .
Sorry, it is a bug of sphinx_rtd_theme.
