### ISSUE TITLE
Page layout for Japanese ``manual`` docclass has a shorter text area

### ISSUE THREAD

**Issue by jfbu** [sphinx-doc/sphinx#3356]
Subject: (PDF issue) when specifying `language='ja'`  there is diverging page layout for ``'howto'`` and ``'manual'`` docclass

### Problem

Here is the background. In current Sphinx latex style file we find this:

```latex
% adjust the margins for footer,
% this works with the jsclasses only (Japanese standard document classes)
% FIXME: rather, pass options to "geometry".
\ifx\@jsc@uplatextrue\undefined\else
  \PassOptionsToPackage{setpagesize=false}{hyperref}
  \setlength\footskip{2\baselineskip}
  \addtolength{\textheight}{-2\baselineskip}
\fi
```

I would like to use geometry options but the problem is that the conditional is true for ``'manual'`` (which uses ``jsbook`` Japanese LaTeX document class) and False for ``'howto'`` which uses (``jreport`` Japanese LaTeX document class).

Thus only for ``'manual'`` is 

```
  \setlength\footskip{2\baselineskip}
  \addtolength{\textheight}{-2\baselineskip}
```

executed. But this code looks possibly unintended, because the ``\footskip`` setting looks like it is followed by  a ``\textheight`` adjustment, but the latter is strange because ``\footskip`` regards a dimension below the text area.

We can use `geometry` options like this for Japanese:
```latex
\usepackage[margin=1in,marginparwidth=0.5in,footskip=2\baselineskip,dvipdfm]{geometry}
```

but if we want to also do the ``\addtolength{\textheight}{-2\baselineskip}`` we need also option ``includefoot`` for `geometry`.

Hence having two distinct behaviors complicates matters.

The above was introduced at 5228571 (Sphinx 1.2), hence is long established behaviour. I think it was a bug, but changing this will modify appearance of Japanese documents using ``'manual'`` and not customizing the defaults, as the text area would not be shortened by two baselineskips.

@uchida, @tk0miya what do you think ?

edit: I think the intent of `\addtolength{\textheight}{-2\baselineskip}` was to compensate the change in `\footskip`, but then the value substracted should have been the delta of  `\footskip`, thus possibly what was intended is what `\addtolength{\textheight}{\footskip}`, `\setlength{\footskip}{2\baselineskip}`, `\addtolength{\textheight}{-\footskip}` would achieve.

About ``\PassOptionsToPackage{setpagesize=false}{hyperref}`` this is because the `jsbook.cls` puts itself the correct `\special` in the DVI output. I know `geometry` does the same but I could not find option to tell it not to put the specials like this code does with `hyperref`. But if users have detected no issue since `geometry` started been used by Sphinx LaTeX, maybe I should not worry to much.

There is also the issue with `geometry` that it should receive option `dvipdfm`, not `dvipdfmx` (else it thinks driver is `dvips`, and does something different in case of landscape option.)

#### Procedure to reproduce the problem

```
$ sphinx-quickstart # choosing language 'ja'
```

Also, add in conf.py ``latex_elements`` dictionary:

        'preamble': '\\usepackage{layout}',

and 

```
.. raw:: latex

   \layout
   \the\textheight
   \relax
```

inside ``index.rst``. Then

```
$ make latexpdf # this uses by default 'manual'
$ make latexpdf # after having changed docclass to 'howto' in conf.py
```

#### Results

Using ``'manual'`` and latex package layout as above, we get this screenshot:

![capture d ecran 2017-01-19 a 18 36 34](https://cloud.githubusercontent.com/assets/2589111/22118358/b98c5990-de77-11e6-8262-696cbc3ffbc1.png)

Using ``'howto'`` we get rather

![capture d ecran 2017-01-19 a 18 37 58](https://cloud.githubusercontent.com/assets/2589111/22118375/c8e21f56-de77-11e6-89b9-f3e926960a18.png)

i.e. the text area is longer.

#### Expected results

The default text area should be the same: except if there is some mandatory Japanese typographical requirement, I am completely ignorant !

### Reproducible project / your project

[temptestja.zip](https://github.com/sphinx-doc/sphinx/files/717403/temptestja.zip)

### Environment info
- OS: Mac os x 10.9.5
- Python version: 3.5.2
- Sphinx version: 1.5.1

**Comment by jfbu** [comment]
@tk0miya peripheral to this issue, I see in `jsbook.cls`:

```latex
\newif\if@report
\@reportfalse
\DeclareOption{report}{\@reporttrue\@openrightfalse\@twosidefalse\@mparswitchfalse}
```

hence it seems it is possible to pass option `report` to `jsbook`. Would it make sense to use it for ``'howto'`` rather than `jreport.cls`  ? (I do not suggest this, I am only trying to understand why the ``manual`` uses other family of Japanese LaTeX class).

It seems the "Japanese Standard Document Classes" are currently actively maintained, I saw updates announced recently on CTAN (http://www.ctan.org/pkg/jsclasses).

**Comment by uchida** [comment]
For `\addtolength{\textheight}{-2\baselineskip}` line, I agree with @jfbu, it seems a bug.

Just little off-topic but I noticed about `\PassOptionsToPackage{setpagesize=false}{hyperref}`, there exists some alternatives:

1. jsclasses has `papersize` option (I've noticed when introduced that line, but only available in jsclasses)
2. use [pxjahyper](https://github.com/zr-tex8r/PXjahyper): this package solves some hyperref problems in Japanese environment including what [sphinx/texinputs/sphinx.sty#L996-L1012](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/texinputs/sphinx.sty#L996-L1012) does.

**Comment by jfbu** [comment]
@uchida what do you think is best decision to make about ``\addtolength{\textheight}{-2\baselineskip}``? Should it be removed ?

Thanks for the reference to pxjahyper, I have it on my TL2016 v0.2 and also v0.2 in my TeXLive 2013. Hence once Sphinx requires TL2013 or equivalent, it can be used (or even earlier if shipped with Sphinx). But all I understand from doc is the date ``2012/05/27`` ;-) 

(some confusion arises from the fact that the pxjahyper.sty file on TeXLive says 2012/05/27 v0.2 and also the one on github site but the README says it is version 2012/05/28 v0.3)


I found on internet paper by author of *js* classes Haruhiko Okumura ([link](http://ajt.ktug.org/2008/0201okumura.pdf))

> The Asian Journal of TEX, Volume 2, No. 1, April 2008 Article revision 2008/3/16 pTEX and Japanese Typesetting

For left to right typesetting it says

> In designing Japanese document classes, it is important to set every horizontal dimensions, such as `\hsize` and `\leftmargin`, to integer multiples of `1 zw`.

But Sphinx sets margins to 1inch, for Japanese as non-Japanese documents. The difficulty is that `1 zw` unit depends on font:

> Note that the unit “zw” is defined with respect to the current font.

@uchida, @tk0miya should Sphinx make an effort to reset text width to integer multiple of `1 zw` at end of preamble after font selection ? 

And does Sphinx support right to left, top to bottom Japanese writing ?

**Comment by uchida** [comment]
> @uchida what do you think is best decision to make about \addtolength{\textheight}{-2\baselineskip}? Should it be removed ?

I think `\addtolength{\textheight}{-2\baselineskip}` should be removed.

> But Sphinx sets margins to 1inch, for Japanese as non-Japanese documents. The difficulty is that 1 zw unit depends on font:

I'm not expert for Japanese typesetting and pLaTeX, but I think I could give some comments:
"zw" is a abbreviation for "zenkaku width", here "zenkaku" means fullwidth, see [Halfwidth and fullwidth forms - Wikipedia](https://en.wikipedia.org/wiki/Halfwidth_and_fullwidth_forms) for ref.
Most Japanese characters(Hiragana, Katakana, Kanji) fit into `1zw` x `1zw` square and line length and indentation width should be multiples of `1 zw`, because characters which have same column position and different lines should be same horizontal position as possible.
(there may be some exceptions for this rule, e.g. non-Japanese characters are not fit for `1zw` x `1zw` square.)

`zw` multiples case:
<img width="685" alt="screen shot 2017-01-30 at 22 30 58" src="https://cloud.githubusercontent.com/assets/578500/22424938/33335470-e73c-11e6-8c49-83f60ea32761.png">

No multiples case:
<img width="705" alt="screen shot 2017-01-30 at 22 31 17" src="https://cloud.githubusercontent.com/assets/578500/22424978/5c340f9a-e73c-11e6-9418-466ef3a53e67.png">

Therefore, I think sphinx should reset text width, but reset position could be anywhere because I think "zw" is defined with respect to the current **"Japanese"** font.

> And does Sphinx support right to left, top to bottom Japanese writing ?

For most technical writings in Japanese are written with left to right, so I think right to left, top to bottom is not so important.

**Comment by jfbu** [comment]
Thanks @uchida ! I have looked at the `jsbook.cls` and also `jreport.cls` and both arrange text width to be an integer multiple of some unit (1zw for `jsbook.cls` in one-column mode and width of ``\char\euc"A1A1`` for `jreport.cls`, not tested if same thing in practice, for some reasons there are only a few  uses of `zw` unit in `jreport.cls`), and the text height to be an integer multiple of baselineskip (taking topskip in account).

I have the macros ready for amending the current Sphinx specification of 1in margins so that the above is respected, after small adjustments to the horizontal and vertical margin sizes. This will use the `1zw` unit for normal size, at time of sphinx.sty the font packages are supposedly already loaded (in case of two column mode we need integer multiple of `2zw`). There is a difficulty currently that I must use `reset` option of geometry package first, hence if user has customized the  `geometry`  key to `latex_elements` I need to think about what to do. 

side note: Sphinx could propose a new macro like  `sphinxsetmarginsto {hor margins}{ver margins}{marginparwdth}` which would abstract the way I set up geometry options  for 1in margin on all sides (but then it would need to be defined in the `sphinxmanual.cls` and `sphinxhowto.cls` for availability before loading of `sphinx.sty`). But I don't want to go to more complicated things like distinct top and bottom margins, or left and right if twosided, etc.. as I can not reproduce all the various geometry layout options.

I could be possible to put the code to get the line lengths and text body height right for Japanese, explicitely in the default value of geometry key, but then 

1. we need to move geometry key to after fontpkg in the latex template,

2. the somewhat complicated thing will appear explicitely in preamble. On the other hand this will show user how to do it perhaps with other margin settings and custom use of `geometry` key.

memo: we must set `\textwidth` before `fncychap` loading due to bug of the latter for (at least) Bjarne style. But this can also be corrected from inside sphinx.sty, hence there is no intrinsic problem in moving geometry loading to after fncychap loading. (and fncychap is not used by default for Japanese).

side note: for vertical positioning I hesitated between having "text body" (in the sense of geometry package) be centered exactly in page, or having the top margin exactly fixed to 1in. For horizontal positioning the same hesitation could exist, but then one needs to think about twosided or onesided, hence it was simpler to decide that the left and right margin be exactly identical to that value near 1in which makes for a textwidth an integer multiple of 1zw.

Before making PR with these, I have another question about use of `parskip.sty` package. This uses `0.5\baselineskip` as space between paragraphs, which is not good with respect to the above mentioned textheight adjustments, depending on how many times it happens in the page. The vertical spacing for lists is affected in the same way as paragraphs. Also the parindent vanishes, But the Japanese classes take pain to set suitable values for parindent and list parameters.

I thus propose adding a Boolean option to sphinxsetup, something like `loadparskippkg` (because this is currently done inside sphinx.sty) and propose that its default value for Japanese be set to `false`.

Or, probably better: we move loading of parskip away from sphinx.sty into some new `parskip` template variable, and set this variable to empty by default for Japanese document, and add a `parskip` key to `latex_elements`.

Any thoughts on this ? Besides I don't know if bug fix or feature. If matter of parskip is left aside, this can qualify as bug fix I guess, although the removal of the `2\baselineskip` shortening of the textheight will change layout. For parskip, change of layout will be even more visible, hence perhaps this should be moved to feature release ? (if at all done).

**Comment by jfbu** [comment]
> I have looked at the `jsbook.cls` and also `jreport.cls` and both arrange text width 

to be more precise, for some reason `jreport.cls` does a final truncation of the width and height to an integer multiple of the (TeX)  `pt` unit. Perhaps because it uses integer multiple of (TeX) `pt` everywhere (except on looking briefly `\footnotesep`)

**Comment by jfbu** [comment]
Memo: since 1.5 (2aace8d), Sphinx latex writer uses `jreport` Japanese LaTeX class if docclass is `'howto'` and language `'ja'`. But `jreport` does not recognize `letterpaper` option, which is the Sphinx default. At the same time, also since 1.5 (34f1ce1), Sphinx latex style uses `geometry` package. The latter recognizes the `letterpaper` global option and it does set the paper dimensions according to it. I have not finished my PR to use zenkaku widths, because I observed this while working on it: if Japanese user removes usage of `geometry` package, then the `letterpaper` option (which is Sphinx default) is not obeyed (and `a4paper` is used, which is the `jreport` class default), the user must set accordingly herself `\paperwidth` and `\paperheight`, for Japanese `'howto'` document and set all text layout dimensions.

About dvi specials: there are three sources: `hyperref`, `geometry` and `graphicx` via the `dvipdfmx` driver, if recent. The first two put  `papersize=...` into the dvi, the latter `pdf:pagesize ...` but I am not sure what is really at stake here. Something related to  `\mag` perhaps according to the code comments of `dvipdfmx.def`.

```latex
% v4.10
% Support new (no)setpagesize option of graphics and color.
% v4.11
% Use \special{pdf:pagesize ...} instead of \special{papersize=...}
% to support \mag (dvipdfmx only)
```
Thus I don't know if it is really important to get hyperref not to put this special, and also I see no option in `geometry` doc to tell it not to do it (it puts same info as hyperref). And as said above, recent `dvipdfmx` driver for `graphics/color` puts a `pdf:pagesize ...` special in the dvi. In my brief testing there is no conflict between the information put by the three sources.

Writing this comment here for documentation purposes only ;-)

**Comment by uchida** [comment]
FYI, latex3/graphics-def#1 seems to be related to `pdf:pagesize`.

**Comment by jfbu** [comment]
@uchida thanks ! that is very extensive discussion indeed... I have now pulled together a PR addressing this matter of the two baselines removed from text area. It is at #3387.

**Comment by jfbu** [comment]
@uchida the `jsclasses` have a surprising handling of `\mag` which means that all dimensions must be multiplied by `\inv@mag` by default **except** the `zw` dimension ! This means that it is not possible to set up a user interface and allowing use of  `in`, `cm`, ...  and at the same time `zw` if not going into input parsing, which is close to impossible if the user is allowed to also pass a dimen register etc...

edit: *the above applies to dimensions specifying the page layout; font related dimensions like `em` behave like `zw`. The issue is that if we want to express, say `\marginpar`, in centimeters we must use the`\inv@mag` factor (0.48216 under document option `21pt` for example) but if we want a marginpar of `2zw` we must just say `2zw`.* I guess, the simplest is to require user to use `truein`, `truecm`, ... and not add inner complications to dimension handling.

This problem aside, I think I will be able to work around ``geometry`` bad interaction with ``jsclasses`` if class option ``21pt`` for example is used. But I have other issues like for example ``jsclasses``  accepting ``papersize`` document class option, which then creates an error with ``geometry`` because it has its own ``papersize`` option which **must** have a value, thus it is mandatory to do ``papersize=true`` or ``papersize=false`` at document class level. My current evaluation is that Sphinx must avoid this option, and hack around ``geometry`` being surprised by the way ``\mag`` is used by ``jsclasses``. In my brief and incomplete testing there might be the option to always pass ``nomag`` option to the ``jsbook`` class, but I will try first tricking ``geometry`` into putting the suitable ``papersize:`` special in dvi (unfortunately there is no option in ``geometry`` like the ``setpagesize=false`` of hyperref).

**Comment by jfbu** [comment]
@uchida : #3387 works around the bad interaction of ``geometry`` and ``jsbook.cls``. I have not tested but I hope that  the problem at https://github.com/latex3/graphics-def/pull/1 which applies to older ``graphicx`` drivers (``dvipdfmx, dvipdfm``) is fixed because ``geometry`` will put its special latest in the ``dvi``. At any rate, the problem is fixed for people with up-to-date TeX installations.

**Comment by jfbu** [comment]
fixed at 09324bd and parent commits (refs #3387)

**Comment by uchida** [comment]
@jfbu good job!
And just to note about `\mag`, in recent jsclasses has `nomag` option in texjporg/jsclasses#3 (discussion in Japanese), but seems experimental, use `true*` is best in the present.

**Comment by jfbu** [comment]
@uchida thanks for feedback ! I indicated [here in the latex docs](http://www.sphinx-doc.org/en/stable/latex.html#latexsphinxsetuphmargin) about possibility of `nomag`, not knowing then it was [relatively recent](https://github.com/texjporg/jsclasses/pull/3/commits/72f0150b3063617ab1f7610bb2d0ec8030dd4245) addition to the Japanese standard classes. 

While studying `jsbook.cls` I was a bit worried about complicated looking code which I see now is even [more recent](https://github.com/texjporg/jsclasses/pull/29) but translate.g..le made miracles so I now understand the purpose of that commit. As Sphinx code tests the `\mag` value, it makes no difference if user managed to pass `nomag` or `nomag*` option to the document class.

The good thing is that `geometry` has a delayed handling of dimension computations, so the `truedimen` option can be passed to it as package option even after it has processed (via its own system) the document class options and in particular options such as `letterpaper` or `a4paper` (it will choke on `jsbook`'s `papersize` option; imho JS classes should have chosen `papersizespecial` or similar more explicit name). And geometry takes into account  the `\mag` value for putting the correct special in the dvi so it is ok. In my brief investigation I recall seeing that the least significant digits may differ slightly from the one the `jsbook` class would put with `papersize` option, due to different ways of handling the computations, but this is minor point.

``geometry`` package should get improved by an option (like ``hyperref`` has and now ``graphicx``) not to create the special, as only official way is to use its ``pass`` option which actually I think deactivates it entirely.

**Comment by jfbu** [comment]
OMG... some code I had prepared in another branch was forgotten at merge time, so I have now added it at eb1e9e0. I think it is the thing to do. Perhaps it should be wrapped in a test for geometry package having been loaded.
