### ISSUE TITLE
Sphinx "autodoc-skip-member" fails to build documentation for Flask web application

### ISSUE THREAD

**Issue by szlinjia** [sphinx-doc/sphinx#3368]
Subject:  skipping members "autodoc-skip-member" error at Flask application 

### Problem
- I used Sphinx v1.5.3+ to build document for a Flask web application. I need to skipping some functions with special keywords in it. Then I got the error
`RuntimeError: Working outside of application context.`

#### Procedure to reproduce the problem
I follow the explanation in Sphinx website [here](http://www.sphinx-doc.org/en/1.5.1/ext/autodoc.html#skipping-members) to add "autodoc-skip-member" in conf.py 
```
# ----- skip  docstring in module for test case-----------------------------
def autodoc_skip_docstring(app, what, name, obj, skip, options):
    if obj is None:
        return True
    else:
        skip_fun = str(obj).find("Tests") != -1 and name.find("Tests") != -1
        return skip or skip_fun

def setup(app):
    app.connect('autodoc-skip-member', autodoc_skip_docstring)
```
The I got the error:
```
Exception occurred:
  File "/home/venv/lib/python2.7/site-packages/flask/globals.py", line 44, in _lookup_app_object
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.
```
This is the traceback from the error log:
```
Running Sphinx v1.5.3+
/home/venv/lib/python2.7/site-packages/sphinx/util/requests.py:38: UserWarning: Some links may return broken results due to being unable to check the Server Name Indication (SNI) in the returned SSL cert against the hostname in the url requested. Recommended to install "requests[security]" as a dependency or upgrade to a python version with SNI support (Python 3 and Python 2.7.9+).
  'Some links may return broken results due to being unable to '
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 25 source files that are out of date
updating environment: 25 added, 0 changed, 0 removed
reading sources... [  4%] apps

Exception occurred:
  File "/home/venv/lib/python2.7/site-packages/flask/globals.py", line 44, in _lookup_app_object
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
to interface with the current application object in a way.  To solve
this set up an application context with app.app_context().  See the
documentation for more information.
The full traceback has been saved in /tmp/sphinx-err-UT1vxh.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!

Process finished with exit code 1
```
### Environment info
- OS:   CentOS release 6.4
- Python version: Python2.7
- Sphinx version:Sphinx1.5.3+
- Pycharm: 2016.2.2

**Comment by tk0miya** [comment]
Is there any example or minimal producible project?
I can't reproduce the problem...

**Comment by szlinjia** [comment]
@tk0miya 
Thanks for reply. I had solved the problem. This is not a sphinx issue. The error due to sphinx working under Flask framework.

The Flask runs in context mechanism, where _app_ctx_stack and _request_ctx_stack are in use to maintain configure information for application. By default, uwsgi will push an app in _app_ctx_stack when it receives a request but _app_ctx_stack is empty.  The problem is sphinx runs out of uwsgi, so when sphinx parses a flask application,  the _app_ctx_stack  is empty so it raises `RuntimeError(_app_ctx_err_msg)`

For exmaple, you can see my python code :
in mycode.py
```
app = Flask(__name__)
@app.route('/create_account', methods=_METHODS)
def create_account():
    #codo is here....
    ...
    ...
```

in conf.py:
```
# ----- skip  docstring in module for test case-----------------------------
def autodoc_skip_docstring(app, what, name, obj, skip, options):
    try:
        # this call push obj, which is a flask app, into _app_ctx_stack
        obj.app.test_client()
        skip_fun = name.find("Tests") != -1 or str(obj).find("Tests") != -1
        return skip or skip_fun
    except:
        return skip

def setup(app):
    app.connect('autodoc-skip-member', autodoc_skip_docstring)
```

Is it possible to have  this stack push step in autodoc.py so users don't need to worry about sphinx working for flask apps?

**Comment by arcivanov** [comment]
This the same issue as #3280. Sphinx is generally unable to document modules that cannot be loaded without an application-specific configuration context, such as Django, Flask etc.

**Comment by tk0miya** [comment]
I don't know how to document flask apps with bare Sphinx.
But `sphinxcontrib.autohttp.flask` might help you.
https://pythonhosted.org/sphinxcontrib-httpdomain/#module-sphinxcontrib.autohttp.flask

**Comment by szlinjia** [comment]
@arcivanov 
how do make sphinx work for a running flask app? For now I just runs sphinx by using sphinx-build and I believe that's in build time

@tk0miya 
that autohttp.flask  ext works. Thanks.

**Comment by arcivanov** [comment]
@szlinjia The current dev version stopped crashing and simply skips documenting the modules it can't load. 

I don't use Flask, I use Django but the issue is the same - you have to allow a module to be loaded without an application. So you might need to stub-out the app or have 

```python

try:
    from django import User, ...
except AppRegistryMissing:
   User = object()
```

It's ugly, but so far, because Sphinx actually loads and executes the modules instead of introspecting them, there isn't really an elegant solution.
