### ISSUE TITLE
Error: Sphinx requires at least Python 2.7 or 3.4 to run.

### ISSUE THREAD

**Issue by katsar0v** [sphinx-doc/sphinx#3369]
Subject: Running sphinx-build

### Problem
- Trying to use Sphinx with PyPy

#### Procedure to reproduce the problem
sphinx-build
```

#### Error logs / results
```
Error: Sphinx requires at least Python 2.7 or 3.4 to run.
```
- <public link of unexpected result if you have>

#### Expected results
To build

### Reproducible project / your project
- <link to your project, or attach zipped small project sample>

### Environment info
- OS: <Unix/Linux/Mac/Win/other with version>
- Python version: 3.3 (PyPy)
- Sphinx version: latest from PyPy pip
- <Extra tools e.g.: Browser, tex or something else>

**Comment by tk0miya** [comment]
Could you tell me the version of pypy you used?

**Comment by katsar0v** [comment]
**PyPy3.3 v5.5**

**Comment by tk0miya** [comment]
>We’re pleased to announce the release of PyPy3 v5.5.0. Coming four months after PyPy3.3 v5.2, it improves compatibility with Python 3.3 (3.3.5). We strongly recommend updating from previous PyPy3 versions.
>http://doc.pypy.org/en/latest/release-pypy3.3-v5.5.0.html

The release announcement of pypy3.3-5.5.0 says it has compatibility with python 3.3.
But Sphinx no longer supports python3.3 since Sphinx-1.5.
If you want to use Sphinx with pypy, please use Sphinx-1.4.x series.

Thanks,

**Comment by katsar0v** [comment]
....
