### ISSUE TITLE
Caption of code-block directive not picked up for translation in 1.5.2

### ISSUE THREAD

**Issue by leture** [sphinx-doc/sphinx#3370]
I have the following directive:

    .. code-block:: json
        :caption: Grundlegender Aufbau der JSON-Datenstruktur für eine Objektliste

        {
          "count": 118,
          "next": "https://emco.descript.de/api/jobs/?page=2",
          "previous": null,
          "results": [

          ]
        }

After calling make gettext "Grundlegender Aufbau der JSON-Datenstruktur für eine Objektliste" is not part of the generated pot file. I tested that the versions 1.4.9, 1.5.0 and 1.5.1 do include the string when calling make gettext.

### Environment info
- OS: Windows 8.1
- Python version: 2.7.10

**Comment by tk0miya** [comment]
Sorry for inconvenience.
As a quick look, it seems the 4d6d8ae3691202c2da77e2d846ea2d09b21e29d8 causes the problem.
I'll take a look later.

**Comment by tk0miya** [comment]
Fixed at 1a24886.
Thank you for reporting.

**Comment by leture** [comment]
Thank you for the quick fix!
