### ISSUE TITLE
Adding auto-generated page to toctree

### ISSUE THREAD

**Issue by bomb-on** [sphinx-doc/sphinx#3376]
Subject: Adding auto-generated page to toctree

### Problem
I tried to put a link to the ['routing table'](https://pythonhosted.org/sphinxcontrib-httpdomain/http-routingtable.html) page generated by [`sphinxcontrib.httpdomain`](https://pythonhosted.org/sphinxcontrib-httpdomain/) extension into my `toctree`:

```
.. toctree::
   :maxdepth: 3
   :hidden:

   Introduction <docs/intro>
   :ref:`Complete Reference <routingtable>`
   Changelog <docs/changelog>
```

but I got an error:
```
WARNING: toctree contains reference to nonexisting document u':ref:` <routingtable>`'
```

Is it possible to somehow link the routing table page in my `toctree`?

#### Procedure to reproduce the problem
- Install the extension
`pip install sphinxcontrib-httpdomain`

- Update config.py
```
from sphinx.domains.std import StandardDomain

extensions.append('sphinxcontrib.httpdomain')

def setup(app):
    StandardDomain.initial_data['labels']['routingtable'] = (
        'http-routingtable',
        '',
        'HTTP Routing Table')
    StandardDomain.initial_data['anonlabels']['routingtable'] = (
        'http-routingtable',
        '')
"""
```
- Add to `index.rst` file
```
Documentation
=============

.. toctree::
   :maxdepth: 3
   :hidden:

   Introduction <docs/intro>
   :ref:`Complete Reference <routingtable>`
   Changelog <docs/changelog>
```
- Build docs
`make html`

- Visit generated TOC page in your build.

#### Error logs / results
```
WARNING: toctree contains reference to nonexisting document u':ref:` <routingtable>`'
```

#### Expected results
I'd like to include generated page into my `toctree`.

### Environment info
- OS: AWS Linux and Mac OS X
- Python version: 3.4
- Sphinx version: 1.5.2
- sphinxcontrib.httpdomain version: 1.5.0

**Comment by tk0miya** [comment]
Thank you for proposal.
We'll consider the feature in #2354 and #1800.

Thanks,
