### ISSUE TITLE
Add support for Docutils 0.13 `:align:` option for tables

### ISSUE THREAD

**Issue by jfbu** [sphinx-doc/sphinx#3377]
[Docutils 0.13](http://docutils.sourceforge.net/RELEASE-NOTES.html) has new ``:align:`` [option for tables](http://docutils.sourceforge.net/docs/ref/rst/directives.html#tables).  Could Sphinx add support for it ?

**Comment by tk0miya** [comment]
Sphinx uses table directives (table, csv-table and list-table) from docutils' implementation.
We don't modify them.
So you can just use that option by upgrading docutils.

What I said in #2620 is `:width:` support on LaTeX builder. Let's do it in #3378.

**Comment by jfbu** [comment]
But it seems neither HTML nor LaTeX builder currently respond to the use of the ``:align:`` option in my brief testing.
```
.. table:: First Table
   :align: right

   === ===
    A   B
   === ===
    a   b
    c   d
   === ===
```

I am not actually sure how it is entended to render, I mean with respect to text flow. (I have not tested yet with docutils itself) (but my testing was with Sphinx + docutils 0.13.1)

**Comment by jfbu** [comment]
ah sorry, yes html  produces corresponding mark-up:

    <table border="1" class="docutils align-right" id="id1">

but the issue is there with the LaTeX writer which ignores this `:align:` option.

**Comment by tk0miya** [comment]
Oh, sorry. I was confused with `:align:` and `:widths:`. I'll take a look.

**Comment by tk0miya** [comment]
At last year, I made a pull request for this problem: #2323.
At that moment, docutils did not support `:align:` option. So the PR includes patches to the table directives. But they are not needed now. So I will update that.

**Comment by jfbu** [comment]
I see... a kind of "boomerang" in action here !
