### ISSUE TITLE
Feature request: the ability to suppress missing download files.

### ISSUE THREAD

**Issue by Blendify** [sphinx-doc/sphinx#3402]
Subject: Feature request: the ability to suppress missing download files.

### Problem
Our project has some files that are only on our server and therefore not available for local compiles.
It would be nice to be able to suppress the warning instead.

#### Procedure to reproduce the problem
- Add `:download:` but link to a not existent file
- Compile
#### Error logs / results
```
 WARNING: download file not readable:
```

#### Expected results
The warning should not be shown.

### Reproducible project / your project
- https://developer.blender.org/tag/documentation/

### Environment info
- OS: Windows
- Python version: 1.5.1
- Sphinx version: 1.5.2

**Comment by tk0miya** [comment]
Fixed at 2968ef3. It will be released as next major release.
Thank you for reporting!

**Comment by Blendify** [comment]
Thank you
