### ISSUE TITLE
Types are matched case-insensitively

### ISSUE THREAD

**Issue by rhelmot** [sphinx-doc/sphinx#3408]
Disclaimer: I'm using sphinx pretty much exclusively for autodoc and don't know a whole lot about the underlying structure.

When I mark an element as having a type with `:rtype x:` or `:type x:` or `:param x name:`, `x` is matched case-insensitively against the types that may be linked to. This is a problem in my project since I have a class named `Int`, but many functions take a parameter of type `int`, i.e. the python builtin type. Sphinx will link these parameter's types to my `Int` class, which is extremely confusing.

**Comment by tk0miya** [comment]
I can't reproduce with following notation:
```
.. py:function:: foo(x)

   :param Int x: a number
   :rtype: Int

.. py:function:: bar(x)

   :param int x: a number
   :rtype: int
```
conf.py:
```
extensions.append('sphinx.ext.intersphinx')
intersphinx_mapping = {
    'python': ('https://docs.python.org/', None),
}
```

Could you show me your project or reproducible small example?

**Comment by rhelmot** [comment]
oh shit, I tried to reproduce this myself and failed until I realized that the bad link in my project (seen here: http://angr.io/api-doc/simuvex.html#simuvex.engines.successors.SimSuccessors) is actually a link to a *module* named int, making this a duplicate of https://github.com/sphinx-doc/sphinx/issues/1592

my comment on that issue stands :)

**Comment by tk0miya** [comment]
Okay, I understand. I'll take a look the issue later.
