### ISSUE TITLE
literalinclude: Combining :start-after: and :lines: results in an empty code

### ISSUE THREAD

**Issue by Wrzlprmft** [sphinx-doc/sphinx#3412]
Using the `:start-after:` and `:lines:` options of `literalinclude` always yields an empty code line and not the expected result.

### Minimal example

* `index.rst`, the main documentation file:
	
	``` RST
	Behold this example code:
	
	.. literalinclude:: example.py
		:start-after: blobfish
		:lines: 1
	```

* `example.py`, the example to be included:
	
	``` Python

	# blobfish
	this = line is an_example
	this = line is another_example
	```

* `conf.py`:
	
	``` Python

	source_suffix = '.rst'
	master_doc = 'index'
	```

I compile by calling `sphinx-build . out` in the folder containing the above files. There is no error message.

In the output, I expect to see the introductory sentence followed by `this = line is an_example`. However, instead of the latter I only get an empty line. If I change `:lines:` to `:emphasize-lines:`, everything is working as expected: The line in question is highlighted and the other line is printed additionally.

### Environment info
- OS: Ubuntu 14.04
- Python version: 3.4.3
- Sphinx version: 1.4.4 and 1.5.2

**Comment by jfbu** [comment]
indeed, using ``:lines:`` is not compatible with using ``:start-after:``, as testing shows. The [doc](http://www.sphinx-doc.org/en/1.5.2/markup/code.html) does present the two as alternatives, but perhaps it should say an explicit word about incompatibility (I don't know if incompatibility is intended).

Also, if made compatible decision should be done whether ``:lines:`` still refers to absolute line number in file, or to lines counted after the start tag specified by ``:start-after:``. (in your example if was not that surprising if ``:lines: 1`` meant first line in source, but then ``:lines: 3`` could have worked, which it does not)

memo: in the case of ``:emphasize-lines:`` the count starts after the ``:start-after:`` location.

**Comment by Wrzlprmft** [comment]
> I don't know if incompatibility is intended

Well, if it is, I feature-request this to be changed.

**Comment by jfbu** [comment]
work around is simply to make sure your line selection contains the lines with the tags looked for by start-after or end-before

```
Behold this example code:

.. literalinclude:: example.py
   :start-after: blobfish
   :end-before: 9
   :lines: 1, 5-

```

and 

```
# blobfish
this = 2 is an_example
this = 3 is an_example
this = 4 is an_example
this = 5 is an_example
this = 6 is an_example
this = 7 is an_example
this = 8 is an_example
this = 9 is an_example
this = 10 is an_example
this = 11 is an_example
this = 12 is an_example
this = 13 is an_example
this = 14 is an_example
this = 15 is an_example
this = 16 is an_example
this = 17 is an_example
this = 18 is an_example
this = 19 is an_example
this = 20 is an_example
this = 21 is an_example
this = 22 is an_example
```

Gives:

![capture du 2017-02-10 14-28-43](https://cloud.githubusercontent.com/assets/2589111/22828391/48d11dc6-ef9d-11e6-9d92-6577782efd79.png)


but as said above `:lines:` currently requires absolute line numbers from top of file. Explanation of observed behaviour  is simply that the lines not having the requested numbers are pruned out. So if your start tag is pruned out, it doesn't work afterwards.

**Comment by jfbu** [comment]
notwithstanding possible additional changes, I improved docs at 839e924 regarding current situation, thanks for report !

**Comment by Wrzlprmft** [comment]
> but as said above `:lines:` currently requires absolute line numbers from top of file.

Sadly, the entire point of `:start-after:` is that you can modify whatever comes before this point (e.g., a docstring) without having to adapt the line numbers in `literalinclude`.

**Comment by jfbu** [comment]
I will make a PR

**Comment by jfbu** [comment]
Thank you for your reporting ! Sphinx 1.6 will interpret ``:lines:`` in a way relative to ``:start-after:`` if present.
