### ISSUE TITLE
Sphinx to AsciiDoc converter

### ISSUE THREAD

**Issue by lruzicka** [sphinx-doc/sphinx#3424]
Subject: Create a Sphinx to AsciiDoc converter

### Problem
- Although there are some third-party RST to asciidoc converters, none are able to produce flawless output that would allow to use the documentation written in Sphinx rst to create a similar tree in AsciiDoc.  Unfortunately, for me, it is exactly what I need to do and there is no way I could change the workflow.

#### Procedure to reproduce the problem
Not applicable

#### Error logs / results
Not applicable

#### Expected results
* Run sphinx to convert rst files to asciidoc  as they are in a directory, producing a tree similar to the original tree of rst files. 
* Also, accepting and converting all Sphinx rst specialities that can be used on top of the normal rst.

### Reproducible project / your project
- if somebody wanted to build on some existing converter, for example the html converter, where should one look? I am not such a good programmer to write it from scratch, but I might be able to get inspiration from existing functions.

### Environment info
- OS: Linux
- Python version: 3 and more
- Sphinx version: Current

**Comment by tk0miya** [comment]
Sphinx is designed to be extensible on several levels. The builder is an extension what you want.
Unfortunately, it seems there are no builders for asciidoc.

So if you make asciidoc-builder, then you'll be able to convert your docs to asciidoc format.
http://www.sphinx-doc.org/en/stable/extdev/index.html

Thanks,

**Comment by tk0miya** [comment]
I marked this as "wontfix" because our policy is small sphinx-core and many 3rd party extensions.
So it should not be added the builder into sphinx-core.
