### ISSUE TITLE
Different output created on Windows

### ISSUE THREAD

**Issue by brechtm** [sphinx-doc/sphinx#3427]
### Problem
Rendering the Sphinx documentation on Windows produces different output from other platforms. Specifically, the documentation generated for the `Sphinx.warn` function is different. On Windows, the representation of the default `colorfunc` includes a memory address.

This image illustrates the difference (red = Windows, green = macOS/Linux):
![warn](https://cloud.githubusercontent.com/assets/652887/23022115/7510667e-f44f-11e6-9755-193c322a010a.png)

### Environment info
- OS: Windows (all?)
- Python version: 3.5
- Sphinx version: 1.5.1

**Comment by brechtm** [comment]
This can be fixed by adding the `re.IGNORECASE` flag to [memory_address_re](/sphinx-doc/sphinx/blob/6fa0262802a09050e09445c9fd630c69b5ad1204/sphinx/util/inspect.py#L27). On Windows, memory addresses use uppercase letters.

**Comment by tk0miya** [comment]
Fixed at 79b7c46.
Thank you for reporting!
