### ISSUE TITLE
Guidance on documenting Events for EventEmitters

### ISSUE THREAD

**Issue by LivInTheLookingGlass** [sphinx-doc/sphinx#3431]
Subject: It is unclear how to document Events in EventEmitters, either in Javascript or Python

### Problem

When creating events with the exact same syntax as I do in Javascript, the Python domain does not parse this as a method. This means that it does not generate an HTML ID that I can link to.

So this works:

```
.. js:function:: js2p.mesh.mesh_socket Event 'connect'(conn)
```

And this does not:

```
.. py:function:: py2p.mesh.mesh_socket Event 'connect'(conn)
```

#### Procedure to reproduce the problem
```
make html
```

#### results
- https://dev-docs.p2p.today/python/mesh.html#py2p.mesh.mesh_socket

#### Expected results

For the Python domain to behave in the same way as the Javascript domain, or for there to be an alternative syntax proposed.

### Reproducible project / your project
- https://github.com/p2p-today/p2p-project

### Environment info
- OS: Linux
- Python version: 2.7
- Sphinx version: latest
- Uses Netlify build image (which is why inheritance chart is currently failing. This is unrelated)

**Comment by LivInTheLookingGlass** [comment]
@jfhbrook, you may be interested in this

**Comment by tk0miya** [comment]
`js:function` and `py:function` take a signature of the functions.
http://www.sphinx-doc.org/en/stable/domains.html#python-signatures

It seems your examples are not correct signatures.

Note: JS domain parses the signatures with loose rules. As a result, `js2p.mesh.mesh_socket Event 'connect'` is recognized as the function name.

**Comment by LivInTheLookingGlass** [comment]
I recognize that they aren't correctly formatted signatures. Unfortunately I don't know of a way to represent these with correct signatures in the sphinx framework. The syntax I gave above is an admittedly hacky way that happens to work in one domain but not the other.

**Comment by tk0miya** [comment]
Please refer the document for domains:
http://www.sphinx-doc.org/en/stable/domains.html

Basically, it is same as the definitions of functions or classes on each language.

Anyway, it seems this is not a bug of Sphinx. So I close this now.
Thanks,

**Comment by LivInTheLookingGlass** [comment]
@tk0miya, what I'm trying to figure out is if there's any way to do this within sphinx at all. It seems that there is not, even though this is a fairly common feature in libraries.

I have read all the relevant documentation. I have tried numerous ways to work within the system to do this. I was hoping that you had one which I did not try, or that you would decide to add this functionality to sphinx.

For the Javascript domain specifically, it feels like a rather large oversight to not have it. And with libraries like `pyee.EventEmitter` giving similar capabilities to Python, I'm at a loss as to how this never came up before.

**Comment by tk0miya** [comment]
Both domains use function declaration on each language.
Are these valid function declaration?
```
.. js:function:: js2p.mesh.mesh_socket Event 'connect'(conn)

.. py:function:: py2p.mesh.mesh_socket Event 'connect'(conn)
```
Unfortunately I don't know `pyee.EventEmitter`. But, AFAIK, python might not allow such a declaration.

**Comment by LivInTheLookingGlass** [comment]
So what I'm trying to figure out is how to document a user-defined function which is fed to my object's `on()` method. So they would say `on('connect', some_function)`.

Node.js documents this [like so](https://nodejs.org/api/net.html#net_event_connection).

In the sphinx tool, the closest I've found is declaring a function with an invalid signature. This works in the Javascript domain, but not Python.

It also does not work to declare it as an attribute.

**Comment by LivInTheLookingGlass** [comment]
My current workaround is to use text replacement, and throw raw html ids into the function declarations. This is obviously not ideal, but it's the only solution I'm aware of for the moment.

**Comment by jfhbrook** [comment]
No real horse in this race, but commenting because I'm curious to see how this plays out.

So as far as EventEmitter goes, it's just a tiny pubsub library, so you would subscribe to an event with `some_ee.on('some_event', some_handler)` and then publish the event with `ee.emit('some_event', some_payload)`. If you've used node.js, it's a mostly-straight reimplementation of the EventEmitter there. In light of that and this issue, it sounds like what's wanted is a way to describe some user-supplied callback to a class, such as `some_handler` in this case\*.

idk sphinx that well, but I have to assume that there's a way to link to content without necessarily using some function-specific syntax. I'd work with that, personally.

\* Edit: Complicated by the fact that the type signature of some_handler is different depending on what some_event is, otherwise I'd just say to document the subscribe method.

**Comment by tk0miya** [comment]
Reopened for discussing.

In javascript domain, function describes only a function of JavaScript. In this case, `on` is corresponded.
In the domain, `connect` and `some_function` are treated as arguments simply.

There are no type to describe "events" and "event handlers" on JavaScript domain.
AFAIK they are commonly used techniques, but they are not a term of JavaScript language.

So if you want to mark up events and its handlers, please make new enhanced javascript domain as a extension.
Or please use `describe` or `object` directive. It does not restrict anything.
http://www.sphinx-doc.org/en/stable/domains.html#directive-describe

**Comment by tk0miya** [comment]
Closed again.
