### ISSUE TITLE
Highlighting of a jinja2 template/code-block fails if the % modulo operator is present

### ISSUE THREAD

**Issue by JoeVirtual** [sphinx-doc/sphinx#3433]
### Problem
The highlighting of a jinja2 template/code-block fails if the `%` modulo operator is present.
I am not sure if the problem is caused by the `Pygments` lexer or by `Sphinx` itself.

#### Procedure to reproduce the problem
```
.. code-block:: jinja

   {% for _ in range(24) %} {{ loop.index % 10 }}{% endfor %}
```
The  `%` modulo operator in the part `{{ loop.index % 10 }}` triggers the failure.

#### Error logs / results
```
WARNING: Could not lex literal_block as "jinja". Highlighting skipped.
```

#### Expected results
The highlighting should work.

### Reproducible project / your project
None.

### Environment info
- OS: Windows 7
- Python version: 3.6
- Sphinx version: 1.5.2
- Jinija2 version: 2.9.5
- Pygments version: 2.2.0

Thank you in advance for your help.

**Comment by tk0miya** [comment]
It's a bug of pygments. The module operator causes parsing error:
```
$ echo '{% for _ in range(24) %} {{ loop.index % 10 }}{% endfor %}' | pygmentize -l jinja -F raiseonerror

*** Error while highlighting:
ErrorToken: %
   (file "/Users/tkomiya/work/tmp/lib/python2.7/site-packages/pygments/filters/__init__.py", line 196, in filter)
*** If this is a bug you want to report, please rerun with -v.
{% for _ in range(24) %} {{ loop.index %
```

Please report your case to their project.

Thanks,
