### ISSUE TITLE
CSS is different between HTML and SingleHTML

### ISSUE THREAD

**Issue by Blendify** [sphinx-doc/sphinx#3440]
Subject:  When we compile a single html page for the [Blender documentation](https://developer.blender.org/project/view/53/) we get results that inconsistent with https://docs.blender.org/manual/

### Problem

When we run singlehtml we get a couple of difference compared to multipage html:

- captions are different
- links are on their own line

#### Procedure to reproduce the problem
```
make html
make single html
```

#### Error logs / results

![broken page](https://cloud.githubusercontent.com/assets/15183467/23182425/7c7723e4-f846-11e6-8030-afa30301419f.JPG)

#### Expected results
I would expect singlehtml to look like https://docs.blender.org/manual/en/dev/getting_started/about/introduction.html#key-features

### Reproducible project / your project

```
svn checkout https://svn.blender.org/svnroot/bf-manual blender-manual
cd blender-manual
make html
make singlehtml
```
### Environment info
- OS: Windows 10
- Python version: 3.5.2
- Sphinx version: 1.5.2

**Comment by tk0miya** [comment]
Thank you for reporting.
I'll take a look.

Did you check which styles causes this? Let me know if you know that. It is very helpful for me :-)

**Comment by Blendify** [comment]
What do you mean by styles? Themes? or Markup?

**Comment by tk0miya** [comment]
I meant stylesheet (CSS).

**Comment by tk0miya** [comment]
It seems a style for `.toctree-wrapper * a` causes the problem. It is defined in sphinx_rtd_theme.
It is defined as `display: block`. So all hyperlinks under the `.toctree-wrapper` elements are treated as block level.

But I don't know why this list is surrounded in `.toctree-wrapper` element. I'll investigate it later.
As a adhoc way, please stop to use the style.

**Comment by tk0miya** [comment]
Hmm... it have also surrounded in older version (I confirmed with Sphinx-1.3.6).
I don't know this is a specification or not. But, this is not a bug at least.

I believe this is a bug of sphinx_rtd_theme.
Please report this to their project.

Thanks,
