### ISSUE TITLE
sphinx-apidoc: the generated html won't change, remain the same

### ISSUE THREAD

**Issue by ujsxn** [sphinx-doc/sphinx#3448]
I changed the code and comment, remove the entire _build, make, but the generated html remain the same, even I delete it.

### Environment info
- OS: Mac Sierra 10.12.3 (16D32)
- Python version: 2.7.13
- Sphinx version: Sphinx (1.5.2)

**Comment by tk0miya** [comment]
Sorry, I can't reproduce your problem.
Could you share me an example?

**Comment by ujsxn** [comment]
https://github.com/ujsxn/wechat-master

you could pull my code, build the doc, then delete the WxApi in official.py, then rebuild, the doc remain the same.

**Comment by ujsxn** [comment]
Maybe there is cache or backup something, but I didn't find the document about that...

**Comment by tk0miya** [comment]
It seems this is a problem for loading path of python.
In your `conf.py`, you added `../webchat` into sys.path, and you try to document `wechat.official` module in `wechat.rst`.
```
sys.path.insert(0, os.path.abspath('../wechat'))
```
```
.. automodule:: wechat.official
    :members:
    :undoc-members:
    :show-inheritance:
```

But, python and sphinx could not load `wechat.official` module from the directory. `wechat/official.py` should be placed at relative path from the sys.path.
So you should add `..` directory to your sys.path.

On your environment, Sphinx might load `wechat.official` module from system-installed wechat module, not from current directory. So removal does not effect to the document, I think.

Could you check this please?

**Comment by ujsxn** [comment]
yes, it is, I had installed the wechat for try, 

    Wand (0.4.4)
    wechat (0.4.16)
    wheel (0.29.0)

and I set the 

    sys.path.insert(0, os.path.abspath('..'))

It works fine!

thanks very much!
