### ISSUE TITLE
&nbsp is appeared in EPUB docs

### ISSUE THREAD

**Issue by tk0miya** [sphinx-doc/sphinx#3450]
### Problem
- `&nbsp;` entity is appeared in EPUB docs. It is not allowed in EPUB (XHTML5).

#### Procedure to reproduce the problem
```
.. list-table::
   :header-rows: 1
   - * one
     * two
     * three
   - * un
     * 
     * trois
```

#### Error logs / results
The generated EPUB file contains `&nbsp;` entity
```
<tbody valign="top">
<tr class="row-even"><td>un</td>
<td>&nbsp;</td>
<td>trois</td>
</tr>
</tbody>
```

#### Expected results

It should be represented as SPACE character (0x20) or `&#32;`.

**Comment by tk0miya** [comment]
Note: `docutils.writers.html4css1.Writer` generates `&nbsp;` entity

- on `encode()` method (for `0xA0`; non breaking space)
- on `visit_entry()` method if the table cell is empty

**Comment by shibukawa** [comment]
```
.. py:function:: test() -> string
```

makes ``&rarr;``

**Comment by shibukawa** [comment]
Field-list that has more than [limit of field name count](http://docutils.sourceforge.net/docs/user/config.html#field-name-limit) characters (default 14)

```:abcdefghijklmnopqrstuvwxyz: fieldlist```

makes ``&nbsp;``

**Comment by shibukawa** [comment]
Option-list that has more than [limit of option name count](http://docutils.sourceforge.net/docs/user/config.html#option-limit) characters (default 14)

```
-a                 all
-b long_long_file  use file
```

makes ``&nbsp;``
