### ISSUE TITLE
Sphinx repo own ``make clean`` should remove ``doc/_build`` if empty

### ISSUE THREAD

**Issue by jfbu** [sphinx-doc/sphinx#3453]
Subject: when issuing ``make clean`` at top level of a checkout of Sphinx's own git repo, it stops if ``doc/_build/`` exists, even if empty.

#### Procedure to reproduce the problem
```
doc$ make clean
Removing everything under '_build'...

doc$ cd ..

sphinx$ make clean
find . -name '*.pyc' -exec rm -f {} +
find . -name '*.pyo' -exec rm -f {} +
find . -name __pycache__ -exec rm -rf {} +
find . -name '*.orig' -exec rm -f {} +
find . -name '*.rej' -exec rm -f {} +
find . -name '*~' -exec rm -f {} +
find . -name '*.bak' -exec rm -f {} +
find . -name '*.swp' -exec rm -f {} +
find . -name '*.swo' -exec rm -f {} +
find . -name '.DS_Store' -exec rm -f {} +
rm -f doc/_build/
rm: doc/_build/: is a directory
make: *** [Makefile:59: clean-generated] Error 1
```

The problem is that this stops prior to doing

```
rm -f sphinx/pycode/*.pickle
rm -f utils/*3.py*
rm -f utils/regression_test.js
rm -rf tests/.coverage
rm -rf tests/build
rm -rf .tox/
rm -rf .cache/
rm -rf build
rm -rf .mypy_cache/
```

which possibly make cause problems (I imagine) if I go on with ``make test``

(in fact I had such a problem possibly while doing ``make test`` on various checkouts which resulted in a stray ``foo.py`` file at top level which had not been removed but perhaps ``make clean`` would have not removed it anyhow, but reporting nevertheless)

Perhaps the ``make clean``  should test for emptiness of  ``doc/_build`` and the remove it rather than aborting ?

### Environment info
- OS: Mac 10.9.5
- Python version: 3.5.2
- Sphinx version: current repo

**Comment by tk0miya** [comment]
Fixed at 341986c.
it should be removed. so I simply use `rm -rf doc/_build/`.
