### ISSUE TITLE
Sphinx should contain the testing utilities under tests/ as sphinx.testing

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#3458]
### Goal

- `sphinx.testing` provides test utilities of pytest for sphinx and newly 3rd party extensions
- `sphinx-testing` provides test utilities of nose for traditional 3rd party extensions

### Background

Now a day, sphinx using pytest for unit testing and testing utilities are provided under `tests/`. Unfortunately, developers of sphinx extension can not use the utilities if they want to use  it in their product because modules under `tests/` are not importable even if sphinx is installed.

`sphinx-testing` package provides testing utilities for development of sphinx extensions with using `nose` runner. If developers want to use `nose` runner for their testing as before, they can use `sphinx-testing` package. However, pytest version testing utilities is not provided.

### Links

- https://pypi.python.org/pypi/sphinx-testing
- https://github.com/sphinx-doc/sphinx/blob/master/tests/conftest.py

**Comment by tk0miya** [comment]
+1. We don't have enough time both `tests/` utilities and `sphinx-testing`. As a result, `sphinx-testing` is not maintained at this moment and not released v1.0 yet...
So providing self-hosted testing framework is very worthy, and it will also save our time.

**Comment by mbukatov** [comment]
When it's done, it would be nice to add testing into section *Writing a simple extension* in the Sphinx documentation.

**Comment by shimizukawa** [comment]
#3718 has been merged and [sphinx-1.6(.1)](https://pypi.python.org/pypi/Sphinx/1.6.1) has been released 🎉 

For now, `sphinx.testing` is experimental feature.
Also, there is not enough documentation yet http://www.sphinx-doc.org/en/stable/devguide.html#unit-testing
However, I think it's time to close this ticket. We will update docs and implementations of `sphinx.testing`.
