### ISSUE TITLE
support for patent bibtex 

### ISSUE THREAD

**Issue by suunni-zz** [sphinx-doc/sphinx#3469]
Subject: In sphinxcontrib.bibtex, getting error for @Patent type entries
### Problem
Parsing of bibtex throws error for Style not found for @Patent entries

```
parsing bibtex file /home/sunanda/github/cloudmesh/classes/docs/source/refs.bib... parsed 540 entries

Exception occurred:
  File "/home/sunanda/.local/lib/python2.7/site-packages/pybtex/style/formatting/__init__.py", line 60, in format_entries
    f = getattr(self, "format_" + entry.type)
AttributeError: 'Style' object has no attribute 'format_patent'
The full traceback has been saved in /tmp/sphinx-err-RORfZI.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

#### Procedure to reproduce the problem
```
sphinx-build -b html -d build/doctrees   source build/html

```

#### Expected results
<Describe what to actually do>

### Reproducible project / your project
- 
[sphinx-err-RORfZI.txt](https://github.com/sphinx-doc/sphinx/files/802167/sphinx-err-RORfZI.txt)

### Environment info
- OS: ubuntu
- Python version:2.7
- Sphinx version:
- <Extra tools e.g.: Browser, tex or something else>

**Comment by tk0miya** [comment]
Thank you for reporting, but this is Sphinx project, not bibtex's. so we can't help the error for sphinxcontrib-bibtex.
Please report this to thier project.

Thanks,
