### ISSUE TITLE
Less description about make-mode

### ISSUE THREAD

**Issue by cocoatomo** [sphinx-doc/sphinx#3477]
Subject: Sphinx project document has less description about make-mode.

### Problem
- Description about make-mode is too short to understand what make-mode is and how --use-make-mode affects.

link to source file: https://github.com/sphinx-doc/sphinx/blame/5d715cb14877058f9586e92c0f5f224bce56ff81/doc/invocation.rst#L131

#### Procedure to reproduce the problem
Open http://www.sphinx-doc.org/en/stable/invocation.html in any browser.

#### Error logs / results
N/A

#### Expected results
Sphinx project document has enough description to understand make-mode.

### Reproducible project / your project
N/A

### Environment info
N/A

**Comment by TimKam** [comment]
#3938 fixed this ~half a year ago. I think this can be closed @tk0miya.

**Comment by tk0miya** [comment]
Right! Closing now:)
