### ISSUE TITLE
Some admonitions in HTML writer don't pass the node argument to depart_admonition

### ISSUE THREAD

**Issue by abathur** [sphinx-doc/sphinx#3506]
### Problem
In the HTML writer, the methods depart_attention, depart_caution, depart_danger, depart_error, depart_hint, depart_important, and depart_tip all fail to pass the node method to depart_admonition, limiting the ability of extensions that subclass the html writer to customize these particular admonitions. I'll submit a PR shortly.

**Comment by tk0miya** [comment]
Note: this is happened only in master branch. It might be contaminated in refactoring (sorry...)

**Comment by abathur** [comment]
No worries. I just bumped into it while working on multi-building.
