### ISSUE TITLE
Should commit messages updating CHANGES use ``PR#xxxx`` or ``PR #xxxx`` ?

### ISSUE THREAD

**Issue by jfbu** [sphinx-doc/sphinx#3513]
Often we add commits to update CHANGES (because including the change in PR's often lead to merge conflicts, so it is simpler to modify CHANGES directly on master or stable HEAD after merge). I see many such entries are worded

    Update CHANGES for PR#xxxx

as there is no space after PR, this prevents github interface to create a link from the commit message to the PR. I am wondering if this is deliberate tradition so as not to clutter the PRs with added automatic info by github linking to the CHANGES update commit, or if it would be better to actually use ``PR #xxxx`` in the commit message.

The later option would make easier reverting a merge completely it the need ever arises. Currently we would have after reverting the merge to find the CHANGES update too and revert it. With ``PR #xxxx`` the github web interface on the PR page would show us a backlink to the CHANGES commit hence it is speedier to find it.

**Comment by tk0miya** [comment]
It is used since bitbucket era (cf. b6452fe0819fe4c5b9d23beca8a6b166efa9515e).
There are no special reason to use it now.
+1 for changing.

**Comment by jfbu** [comment]
OK, I will start leaving a space after PR in future.
