### ISSUE TITLE
Proposal: Invite shibukawa as a new commiter

### ISSUE THREAD

**Issue by tk0miya** [sphinx-doc/sphinx#3516]
### Proposal
- I'd like to invite @shibukawa as a new commiter / maintainer of our project
- He had contributed many works until now
    - Improve search engine (index, stemmer and so on)
    - Add HTML5 builder
    - Improve EPUB builder to pass epubcheck
    - and so on
* He had commited about 60 times ever
* He is a founder of Sphinx-users.jp (Sphinx local users group in Japan)

He had help us ever with his great works. So I'd like to welcome him.
What do you think? Please 👍  for this if you agreed.

I know there are no special procedure to welcome a new commiter. So I will invite him if no objection.

**Comment by tk0miya** [comment]
ping @birkenfeld @shimizukawa

**Comment by shimizukawa** [comment]
:+1:

**Comment by jbking** [comment]
:+1:

**Comment by yassu** [comment]
:+1:

**Comment by usaturn** [comment]
:+1:

**Comment by tk0miya** [comment]
Finally, he joined to our project.
Welcome @shibukawa!

Your first mission is updating AUTHORS file.
https://github.com/sphinx-doc/sphinx/blob/master/AUTHORS#L6

**Comment by tk0miya** [comment]
Thank you for all voting supporters :-)
We'll continue improving Sphinx with powerful developers.

Enjoy documentation!

**Comment by birkenfeld** [comment]
Welcome!

**Comment by shibukawa** [comment]
Thank you all!
