### ISSUE TITLE
NameError: name 'latex_elements' is not defined

### ISSUE THREAD

**Issue by bfrk** [sphinx-doc/sphinx#3524]
It says I should report this so I do.

I was getting deprecation warnings:

`WARNING: latex_paper_size is deprecated. Use latex_elements['papersize'] instead.`

So I did that: removed `latex_paper_size` and added `latex_elements['papersize'] = 'a4'`. This got me:

```
NameError: name 'latex_elements' is not defined
Exception occurred:
  File "conf.py", line 202, in <module>
    latex_elements['papersize'] = 'a4paper'
NameError: name 'latex_elements' is not defined
The full traceback has been saved in /tmp/sphinx-err-oaf5fmxf.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
```

The mentioned file contains this:

```
# Sphinx version: 1.5.2
# Python version: 3.5.2 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.9.5
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/home/ben/.local/lib/python3.5/site-packages/sphinx/cmdline.py", line 295, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/ben/.local/lib/python3.5/site-packages/sphinx/application.py", line 163, in __init__
    confoverrides or {}, self.tags)
  File "/home/ben/.local/lib/python3.5/site-packages/sphinx/config.py", line 134, in __init__
    execfile_(filename, config)
  File "/home/ben/.local/lib/python3.5/site-packages/sphinx/util/pycompat.py", line 129, in execfile_
    exec_(code, _globals)
  File "conf.py", line 202, in <module>
    latex_elements['papersize'] = 'a4'
NameError: name 'latex_elements' is not defined
```

**Comment by bfrk** [comment]
Note: I was making the change in conf.py.

**Comment by jfbu** [comment]
Thanks for report, maybe message should be improved.

Indeed when conf.py is read there is no `latex_elements` Python dict. Thus, either use

```
latex_elements = {}
latex_elements['papersize'] = 'a4paper'
```

or

```
latex_elements = {
    'papersize' : 'a4paper',
}
```

syntax. The sphinx-quickstart script adds such a definition by default with commented out contents for the dict.

**Comment by bfrk** [comment]
Thanks. As you can see I am not very fluent in Python... I would have thought the dictionary gets created automatically when I assign to a key (as it would in Perl IIRC).

**Comment by jfbu** [comment]
Thanks for reporting. I don't see immediately how to make a concise warning which would convey information that `latex_elements` is not yet in existence in `conf.py`'s namespace when executed. My best candidate is:

    WARNING: latex_paper_size is deprecated. Define a latex_elements dict with a 'papersize' key.

Ideas anyone ?

**Comment by tk0miya** [comment]
Updated messages at 9f5f169.
