### ISSUE TITLE
Only directive blocks headers from being in TOC

### ISSUE THREAD

**Issue by roxannemoslehi** [sphinx-doc/sphinx#3539]
Subject: Only directive blocks headers from being in TOC

### Problem
- If you use the "only directive" to flag off some content, any headers inside that directive won't show up in the TOC.

#### Procedure to reproduce the problem
```
**CONTENTS:**

.. contents::
   :local:
   :depth: 1

Title1
======

Some content. 

.. only:: internal

   Title2
   ======

   Some more content.

Title3
======

Even more content.
```

#### Error logs / results
When you run:
```
sphinx-build -b html -t internal ....
```
The generated TOC at the top of the page looks like this:

**CONTENTS:**

- Title1
- Title3

#### Expected results
What we really want is this:

**CONTENTS:**

- Title1
- Title2
- Title3

The "Title2" header should only be missing from the TOC if I run something like ``sphinx-build -b html -t external`` so using a ``-t`` flag other than ``internal``.

**Comment by tk0miya** [comment]
Sorry, "only" directive was not designed to control section. This behavior is specification.
(refs: #2132)
