### ISSUE TITLE
Sphinx has difficulties with expressions in C++ types

### ISSUE THREAD

**Issue by wjakob** [sphinx-doc/sphinx#3542]
### Problem
Consider the following Sphinx snippet below. The first line is parsed without problems. The second one results in an error message. It appears that Sphinx stumbles over the "!" (boolean negation) expression.

#### Procedure to reproduce the problem
```
.. cpp:type:: template <typename T> enable_if_array_t = std::enable_if_t<is_array<T>::value, int>

.. cpp:type:: template <typename T> enable_if_not_array_t = std::enable_if_t<!is_array<T>::value, int>
```

#### Error logs / results
```
WARNING: Invalid definition: Expected end of definition. [error at 82]
  template <typename T> enable_if_not_array_t = std::enable_if_t<!is_array<T>::value, int>
  ----------------------------------------------------------------------------------^
```

#### Expected results
Sphinx should parse the second line as well.

### Environment info
- OS: MacOS
- Python version: 3.5
- Sphinx version: 1.5.3

**Comment by jakobandersen** [comment]
Thanks for reporting this. The parsing of non-type expressions is very simplistic, but I have extended the hax to cover this case as well. Unfortunately that means that the ``T`` (or any other name in the non-type template argument) in the problematic line is still not a link.
