### ISSUE TITLE
existing project documentation won't build with 1.5.1 or 1.5.3: the linkcheck problem 

### ISSUE THREAD

**Issue by prjemian** [sphinx-doc/sphinx#3547]
### Problem
This is a problem with 1.5.1 & 1.5.3, but not a problem with 1.4.8.

    Could not import extension sphinx.builders.linkcheck (exception: No module named exceptions)
Makefile:53: recipe for target 'html' failed

This is the Makefile line that fails:
https://github.com/prjemian/punx/blob/cache_45/docs/Makefile#L53

Chances are good that this report is related to this existing discussion:

https://groups.google.com/forum/#!searchin/sphinx-users/linkcheck|sort:relevance/sphinx-users/Rn_ITu4hxmQ/RyXTNpKfEAAJ

but this is a problem with an existing project that has built previously, not an initial setup.

The revision of "Raghuram BK" [commenting out  'sphinx.builders.linkcheck', from .../sphinx/applications.py] allows the "make html" to continue past that point but that's an ugly repair.

#### Procedure to reproduce the problem

see RTD build: http://readthedocs.org/projects/punx/builds/5137110/

#### Error logs / results

    Could not import extension sphinx.builders.linkcheck (exception: No module named exceptions)
Makefile:53: recipe for target 'html' failed

#### Expected results
documentation should build and show version >= 0.1.5 with date >= 2017-03-11

### Reproducible project / your project

https://github.com/prjemian/punx

### Environment info

Linux x86_64

**Comment by tk0miya** [comment]
It seems you're mocking `requests` module in your conf.py. That causes this issue...
Since 1.5, Sphinx depends on the module.

Please use "autodoc_mock_imports" instead.
http://www.sphinx-doc.org/en/stable/ext/autodoc.html#confval-autodoc_mock_imports
