### ISSUE TITLE
The built-in sphinxdoc theme is not the same as the one used on doc website

### ISSUE THREAD

**Issue by fireattack** [sphinx-doc/sphinx#3548]
I am using `html_theme = 'sphinxdoc'` parameter in the conf.py, but the result is very different from the one shown on http://www.sphinx-doc.org/en/stable/contents.html

From the document http://www.sphinx-doc.org/en/stable/theming.html it says:

> sphinxdoc – The theme used for this documentation. It features a sidebar on the right side. There are currently no options beyond nosidebar and sidebarwidth.

While it does have similar layout, the color scheme is quite different.

Did I miss something obvious?

**Comment by tk0miya** [comment]
Hmm... it seems the description is wrong.
Our document uses its original theme named `sphinx13`, not sphinxdoc.
https://github.com/sphinx-doc/sphinx/tree/master/doc/_themes/sphinx13

I don't know difference with them. I'll take a look later.
Thank you for reporting.

**Comment by fireattack** [comment]
Oh, thanks!

**Comment by TimKam** [comment]
The `sphinxdoc` theme doesn't contain a design update made to the `sphinx13` theme.
Probably because it doesn't make sense to impact users of the `sphinxdoc` theme when changing the design of the Sphinx documentation page. I added a PR to adjust the docs accordingly.
