### ISSUE TITLE
PDF info dictionary is lacking author and title data

### ISSUE THREAD

**Issue by jfbu** [sphinx-doc/sphinx#3551]
Subject: PDF (from ``make latexpdf``) does not contain any author or title attributes in its info dictionary.

#### Procedure to reproduce the problem

Any project. For example with
```
latex_documents = [
    (master_doc, 'FOO.tex', 'FOO Documentation',
     'Georg Brandl \\and Sphinx team', 'manual'),
]
```

in `conf.py`. The information correctly displays on title page but does not make it to the PDF file info dictionary.

#### Diagnosis

The ``sphinxmanual.cls`` and ``sphinxhowto.cls`` contain code using ``\pdfinfo`` but its effect is annihilated presumably by ``hyperref``. Correct way is to use

        \hypersetup{pdfauthor={\@author}, pdftitle={\@title}}

However one must be careful with ``\and`` and possibly problems of Unicode encoding in PDF.

Regarding ``\and`` anyhow the current definitions:

```latex
    \begingroup
    % These \defs are required to deal with multi-line authors; it
    % changes \\ to ', ' (comma-space), making it pass muster for
    % generating document info in the PDF file.
    \def\\{, }%
    \def\and{and }%
    \pdfinfo{
      /Author (\@author)
      /Title (\@title)
    }%
    \endgroup
```

are faulty because not multi-lingual. Anyhow this bug is unseen because the whole thing is without effect.

#### Expected results
The PDF contains suitable meta-data. (the ``and`` should be translatable string too or at least a comma).

### Environment info
- OS: mac os x 10.9.5
- Python version: 3.5.3
- Sphinx version: 1.5.3
- TeXLive 2016, up-to-date.

**Comment by jfbu** [comment]
@tk0miya at #3567 I discovered that things like `\large` if used in `latex_documents` for PDF title caused failed PDF build, even though as explained here the `\pdfinfo` use fails to fill in the PDF Document Information Dictionary due to hyperref overwriting it.

I have pushed now a commit at 895014c to fix this secondary issue on stable branch, but
in this commit I leave in commented out lines how to set  ``/Title``, and ``/Author`` entries, as I have no good solution for how to represent ``\and`` token in a way compatible with all languages Sphinx supports,  and as it seems the Adobe spec does not have clear way to handle multiple authors, or I did not find it. It seems XMP is to be used nowadays, but ``hyperref`` has no interface for it (to the best of my knowledge).

**Comment by tk0miya** [comment]
Now we don't have raw text (not marked up with LaTeX macros). So the only way is replacing and removing macros in Sphinx side::
```
def make_pdfinfo(text):
    text = text.replace('\\and', '&')
    text = re.sub(r'\\\w+', '', text)  # remove all TeX macro like string (starts with '\')
    return text
```
I know this has side-effects. But I believe many case goes well.

**Comment by jfbu** [comment]
Thanks @tk0miya, if you feel `&` is correct multilingual separator, then I will use it. In detail, I will use `\& ` mark-up (with  a space) because:
- hyperref will transform `\&` in `\textampersand` which will then be transformed to ``UTF-16BE`` encoding at least for non-Japanese. (Sphinx passes option `pdfencoding=unicode` to hyperref for non-Japanese documents). The `\&` form does not swallow space following it, contrarily to `\textampersand` form.
- we can not use `\pdfinfo` directly in the `\maketitle` as it seems to get overwritten by `hyperref` and besides, it would require us to do ourselves either the suitable octal escapes or the ``UTF-16BE`` encoding, which is simply not possible if we have to handle LaTeX mark-up.
- doing text replacement on Python side would be less sophisticated than `hyperref` in its handling of LaTeX mark-up.

After some hesitation I do not put a space before the ``\&`` too, thus Sphinx user should use ``'John Doe \\and Jack Done'`` with a space before ``\and`` which anyhow is ignored in LaTeX output for title, I figured most people will have done this naturally and not ``'John Doe\\and...'``.

About ``&`` is as separator,  I initially thought about using the comma and a space, but was worried perhaps it is not suitable for all languages.

Second worry is whether things will work ok with Japanese documents. Can you try effect of #3582 ?
