### ISSUE TITLE
Auto numbering of footnote doesn't check missing

### ISSUE THREAD

**Issue by shibukawa** [sphinx-doc/sphinx#3558]
Subject: <what happen when you do on which document project>

### Problem

- Sphinx doesn't report footnote mismatch for auto numbering items.

```rst
Too many footnotes
------------------------

test1 [#]_
test2 [#]_

.. [#] footnote 1
.. [#] footnote 2
.. [#] footnote 3   (no warning and no error)
```

```rst
Less footnotes
==================

test1 [#]_
test2 [#]_ (warning)

.. [#] footnote 1
```

#### Expected results

I hope to get warning messages with the first sample. And I'd like to have extra strict mode (produce errors instead of warnings).

**Comment by tk0miya** [comment]
Unfortunately, it's not a bug.

You'll also be not warned even if you use manually-numbered footnotes.
```
Too many footnotes
------------------------

test1 [1]_
test2 [2]_

.. [1] footnote 1
.. [2] footnote 2
.. [3] footnote 3   (no warning and no error)
```

These footnotes are defined, but not referenced. So this is valid behavior.
I know this is unexpected behavior and users might miss often.
So I changed this to an enhancement.
