### ISSUE TITLE
Sharing info about docker-sphinx-doc, a Docker image for Sphinx

### ISSUE THREAD

**Issue by lasomethingsomething** [sphinx-doc/sphinx#3561]
### Problem => Offering

Hello: My colleague created [this Docker image](https://github.com/zalando/docker-sphinx-doc/) a while back. Wondering if some folks from the Sphinx community might want to take a look and give us feedback, use it, etc.

**Comment by tk0miya** [comment]
Sorry, this is issue list of sphinx. here is not "community".
Please move to sphinx-users list: https://groups.google.com/forum/#!forum/sphinx-users

Thanks,

**Comment by lasomethingsomething** [comment]
Thank you + done :)
