### ISSUE TITLE
PEP 484 type hints using typing module are awful to read

### ISSUE THREAD

**Issue by WeaverThree** [sphinx-doc/sphinx#3570]
Subject: PEP 484 type hints using typing module are awful to read

### Problem
- Sphinx's autodoc system currently includes 'typing.' before every single reference to one of that module's members. In pretty much all other cases I'd think this would be desirable, but here it really detracts from the intent of type annotations.
- Problem is only somewhat ugly with individual uses of these hinting tools, but nested ones as shown are terrible.
- I've flailed around google for half an hour and gone through the documentation closely and found nothing about this except #1968 , in which it was commented in passing that this might be too long

#### Procedure to reproduce the problem
```
from typing import Iterable, Sequence
class MyClass:
    def __init__(self, csv_rows: Iterable[Sequence[str]]):
        pass
```

#### Error logs / results
http://i.imgur.com/CmIk5hr.png

#### Expected results
- Same, but without the repeated 'typing.' prefixes
- Possibly a configuration list of modules to ignore when making these prefixes?

### Reproducible project / your project
- Above code should be sufficient?

### Environment info
- OS: Win7
- Python version: 3.5.2
- Sphinx version: 1.4.3? (Whatever's on pypi today)

**Comment by ilevkivskyi** [comment]
Just my 5 cents: note that Python's own ``pydoc`` module switched to skipping ``typing.`` prefixes recently:
```
>>> help(MyClass)  # Using the definition in OP example

Help on class MyClass in module __main__:

class MyClass(builtins.object)
 |  MyClass(csv_rows:Iterable[Sequence[str]])
 |  
 |  Methods defined here:
 |  
 |  __init__(self, csv_rows:Iterable[Sequence[str]])
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)
```
