### ISSUE TITLE
Sphinx does not follow Docutil's title and subtitle definition

### ISSUE THREAD

**Issue by getreu** [sphinx-doc/sphinx#3574]
When I run the following code with 
```
*****
Title
*****
----------------------
Subtitle
----------------------

.. sectnum::

Section
=======

Subsection
----------

body
```
Running `rst2html` I get the desired result 

![screenshot_2017-03-21_05-26-36](https://cloud.githubusercontent.com/assets/579082/24131377/140a8a1e-0df7-11e7-83df-9dbca8d10999.png)

The string `Subtitle` is placed under the string `Title` on the title page with a smaller font.

The `rst2pdf` output is also ok:
 
![screenshot_2017-03-19_12-18-46](https://cloud.githubusercontent.com/assets/579082/24080088/433a0150-0ca0-11e7-8e09-6a09edff1ae5.png)

Now I try with Sphinx:

This is my input 

index.rst
```
********
Title
********

------------
Subtitle
------------


.. toctree::
   :maxdepth: 2
   :caption: Contents:

   body
```

body.rst
```
Section
=============

Subsection
---------------

body
```

`make html` gives the following:
![459ede0c-0ca0-11e7-89f6-c4d5d53fe2a5](https://cloud.githubusercontent.com/assets/579082/24131863/d0d0bce8-0df9-11e7-9246-6a29d33bc871.png)

@jfbu  noticed in  #3567

> The html output is not fully satisfying, why is subtitle linked in the sidebar holding the TOC ? it does suggest subtitle is a sectioning command, not part of the title.

The output of `make latexpdf` is discussed in #3567

**Comment by jfbu** [comment]
The context of my remark was at #3567 in the comparison done there at your top post of html vs latexpdf. There isn't a single reference to ``subtitle`` in [Sphinx docs](http://www.sphinx-doc.org/en/stable/contents.html). The [reStructuredText](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#document-structure) reference seems to be more indicative than prescriptive. Sphinx diverges it seems from Docutils here, but as `pseudoxml` illustrates. it is coherent across builders, hence I don't think the issue here is one of "misinterpretation by html backend", it is, or not, a general thing.  But does subtitle make sense in man pages output or texinfo output ? (asking because I simply don't know much beyond the latex things).

**Comment by getreu** [comment]
> it is, or not, a general thing. But does subtitle make sense in man pages output or texinfo output ? (asking because I simply don't know much beyond the latex things).

## Title and subtitles in Docutils

[title and subtitle definition in Docutils](http://docutils.sourceforge.net/docutils/transforms/frontmatter.py)

> Specifically, there is no way to indicate a document title and subtitle explicitly in reStructuredText. [1] Instead, a lone top-level section title (see Sections below) can be treated as the document title. Similarly, a lone second-level section title immediately after the "document title" can become the document subtitle. The rest of the sections are then lifted up a level or two. See the 
[DocTitle](http://docutils.sourceforge.net/docutils/transforms/frontmatter.py) for details.


## Subtitle in Docbook

[subtitle in docbook](http://docbook.org/tdg/en/html-ng/subtitle.html)

**Comment by getreu** [comment]
@jfbu  
I think Sphinx should be coherent with Docutils in this matter.

> hence I don't think the issue here is one of "misinterpretation by html backend", it is, or not, a general thing. 

I think you are right. I suggest changing the headline of this issue.
"Sphinx does not follow Docutil's title and subtitle definition".

**Comment by tk0miya** [comment]
As I said in #3567, this is an intentional behavior.
https://github.com/sphinx-doc/sphinx/issues/3567#issuecomment-288093991

**Comment by getreu** [comment]
Thank you for the workaround in the upcoming  release 1.5.4 described 
[here](https://github.com/sphinx-doc/sphinx/issues/3567#issuecomment-288677681).

BTW: I think, it would be preferable not to repeat the document title in ``latex_documents`` at all. This introduces redundancy. 

In addition Docutils defines a ``meta`` directive. For the moment it is used for generating html meta data only. But can the same markup be used for _latexpdf_ also? Then we could also omit the redundant ``Author`` in the following:

```
latex_documents = [
    (master_doc, 'project.tex', 'Project Documentation\\\\\\LARGE Subtitle',
     'Author', 'manual'),
]
```

**Comment by tk0miya** [comment]
It seems this is already resolved. So I'm closing this now.
Please feel free to reopen this if you still have problem.

Thanks,

**Comment by getreu** [comment]
@tk0miya 
You wrote "Sphinx does not support a "subtitle" (see quote below). 
This is what we know, what my feature request is about and what should change in my opinion.
Do we agree that "Sphinx" should follow "DocUtils" conventions where possible? Here it is possible. 
You might disagree with my feature request, but but  "solved" is not correct here.

*Subtitle support is essential for larger documents Sphinx is designed for.*

> Please feel free to reopen this if you still have problem.

I tried to, but do not have rights to do so it seems.

> Unfortunately, Sphinx does not support a "subtitle". Sphinx recognizes it as a mere second level section. So it is appeared in TOC as a section.
In detail, Sphinx always uses doctitle_xform: False on parsing reST.
http://docutils.sourceforge.net/docs/user/config.html#doctitle-xform
https://github.com/sphinx-doc/sphinx/blob/1.5.3/sphinx/environment/__init__.py#L59

**Comment by tk0miya** [comment]
Thank you for comment. Reopened for discussion.

>Do we agree that "Sphinx" should follow "DocUtils" conventions where possible? 

Difficult to answer. I think both yes and no. docutils has two faces; as a specification of reStructuredText and as a reference implementations of rst converter. And Sphinx should follow the first one. But it is not needed to follow the another one.

In this case, I think promoting subtitle feature is behavior of converter's side.

>Subtitle support is essential for larger documents Sphinx is designed for.

I don't oppose to the subtitle support itself. So we can add it into Sphinx with another way.

**Comment by getreu** [comment]
I found the following conventions in 
[frontmatter.py](http://docutils.sourceforge.net/docutils/transforms/frontmatter.py)
```
In reStructuredText_, there is no way to specify a document title
    and subtitle explicitly. Instead, we can supply the document title
    (and possibly the subtitle as well) implicitly, and use this
    two-step transform to "raise" or "promote" the title(s) (and their
    corresponding section contents) to the document level.

    1. If the document contains a single top-level section as its
       first non-comment element, the top-level section's title
       becomes the document's title, and the top-level section's
       contents become the document's immediate contents. The lone
       top-level section header must be the first non-comment element
       in the document.

       For example, take this input text::

           =================
            Top-Level Title
           =================

           A paragraph.

       Once parsed, it looks like this::

           <document>
               <section names="top-level title">
                   <title>
                       Top-Level Title
                   <paragraph>
                       A paragraph.

       After running the DocTitle transform, we have::

           <document names="top-level title">
               <title>
                   Top-Level Title
               <paragraph>
                   A paragraph.

    2. If step 1 successfully determines the document title, we
       continue by checking for a subtitle.

       If the lone top-level section itself contains a single
       second-level section as its first non-comment element, that
       section's title is promoted to the document's subtitle, and
       that section's contents become the document's immediate
       contents. Given this input text::

           =================
            Top-Level Title
           =================

           Second-Level Title
           ~~~~~~~~~~~~~~~~~~

           A paragraph.

       After parsing and running the Section Promotion transform, the
       result is::

           <document names="top-level title">
               <title>
                   Top-Level Title
               <subtitle names="second-level title">
                   Second-Level Title
               <paragraph>
                   A paragraph.

       (Note that the implicit hyperlink target generated by the
       "Second-Level Title" is preserved on the "subtitle" element
       itself.)

    Any comment elements occurring before the document title or
    subtitle are accumulated and inserted as the first body elements
    after the title(s).

    This transform also sets the document's metadata title
    (document['title']).

    .. _reStructuredText: http://docutils.sf.net/rst.html
```

**Comment by tk0miya** [comment]
I know it. But I'll say again, we consider that promoting subtitle feature is behavior of converter's side. So we make it disabled in Sphinx.

**Comment by bb010g** [comment]
It'd be really nice if there was *some* way to create `subtitle` elements from Sphinx (without extensions).
