### ISSUE TITLE
Problems with pdflatex in a Turkish document built with sphinx has reappeared

### ISSUE THREAD

**Issue by Znni** [sphinx-doc/sphinx#3575]
The problem described in this issue [https://github.com/sphinx-doc/sphinx/issues/2397](https://github.com/sphinx-doc/sphinx/issues/2397) has reappeared in newer versions of Sphinx. 

It seems that this commit [https://github.com/sphinx-doc/sphinx/commit/308d3ae](https://github.com/sphinx-doc/sphinx/commit/308d3ae) broke the Turkish pdflatex transformation. In my Turkish .tex file it now reads 

\if\catcode`\=\active\shorthandoff{=}\fi

This results in the same error messages as in the earlier issue. If I replace that line simply with

\shorthandoff{=}

everything works fine again.

In fact, I have four different Turkish documents and the problem appears with all of them.

I'm running Sphinx 1.5.3, Babel 2.3.4 and Windows 7 64-bit.

**Comment by jfbu** [comment]
Thanks for catching this and very sorry for inconvenience. I committed at 308d3ae and earlier at  85b9547 completely buggy TeX code which made it into 1.5 release, I must have abused energizers at that time.

Fixed at aa03441 for 1.5.4 release. Thanks for reporting.

**Comment by jfbu** [comment]
Of course, reopen if fix does not work for you. LaTeX babel evolved over the years, and sometimes one has issues with a language module evolution.
