### ISSUE TITLE
indented code blocks and bulleted lists in auto numbered lists treated as block quotes 

### ISSUE THREAD

**Issue by jputrino** [sphinx-doc/sphinx#3580]
Subject: Should all indented elements be tagged as blockquotes?

Note - When I refer to indents, I'm talking about the standard 4 spaces (not tabs).

### Problem
In a sphinx project that's in a private github repo (sorry!), I often use auto-numbered lists for sets of tasks. The tasks often include a code-block or a bulleted list of sub-tasks. In order to make the auto-numbering work, you have to indent content that appears between each numbered item, like so:

```
#. Task 1

    .. code-block:: bash
        
        some code

#. Task 2
```

When transformed to html, the indented code block is treated as a block-quote.

![2017-03-22_13-25-48](https://cloud.githubusercontent.com/assets/12143793/24216755/130537ba-0f03-11e7-9bef-c581f77c5dc9.png)

This becomes a problem when using bulleted lists, specifically because of how blockquotes are generally handled in CSS (this example is using bootstrap):

![2017-03-22_13-27-20](https://cloud.githubusercontent.com/assets/12143793/24216864/6cb4c870-0f03-11e7-9e20-502507d00f31.png)

![2017-03-22_13-39-21](https://cloud.githubusercontent.com/assets/12143793/24218031/682fbad6-0f07-11e7-814b-1ada1e63c543.png)

#### Procedure to reproduce the problem
see above examples

#### Error logs / results
N/A

#### Expected results
My question is whether this behavior -- treating all indented content as blockquotes -- is intended.  Indenting is required to make the auto-numbered list work, but the blockquotes tag becomes problematic when a) your project's CSS has specific font size/formatting for blockquotes and b) you don't necessarily have control over the CSS your project has to use/you want to actually be able to use that blockquote formatting in certain cases.

### Reproducible project / your project

The actual repo I'm seeing the issue with is private, but I threw together a test repo: https://github.com/jputrino/sphinx-blockquote-test

Try it first with the default theme (alabaster), then change to f5-sphinx-theme (`pip install git+https://github.com/f5devcentral/f5-sphinx-theme.git@master`) and see how the nested content gets formatted differently. 

### Environment info
- OS: Mac OS Sierra
- Python version: 2.7.12
- Sphinx version: 1.5.3
- [f5-sphinx-theme](https://github.com/f5devcentral/f5-sphinx-theme)

**Comment by jfbu** [comment]
Perhaps I am missing something but I don't quite get why you don't use this mark-up:
```
#. Task 1

   .. code-block:: bash
        
      some code

#. Task 2
```

where the code-block is not additionally indented hence avoiding the blockquote. Yes it is part of the item, but it is not needed for blockquote to not interrupt automatic numbering. The above works fine with automatic numbering.

**Comment by jputrino** [comment]
@jfbu, I guess I just didn't try the right number of spaces. I may have been thinking about it too literally. O_o 
Thanks for your help!
