### ISSUE TITLE
BUG: test_apidoc and test_setup_command do not respect SPHINX_TEST_TEMPDIR

### ISSUE THREAD

**Issue by eric-wieser** [sphinx-doc/sphinx#3583]
These both contain code like

```
@pytest.fixture()
def apidoc(tempdir, apidoc_params):
```

Which loads `tempdir` as `C:\Users\<me>\AppData\Local\Temp\pytest-of-<me>\pytest-15\test_pep_0420_disabled_top_lev0`, despite saying `Temporary files will be placed in C:\Users\<me>\Repos\forks\sphinx\tests\build`

**Comment by tk0miya** [comment]
@shimizukawa could you check this please?

**Comment by shimizukawa** [comment]
`SPHINX_TEST_TEMPDIR` has been removed at #5902 (two weeks ago), so sphinx doesn't use `SPHINX_TEST_TEMPDIR` anymore.
I'm closing this because I think this issue is also resolved by #5902. If you still have the problem, please let me know. Thanks.
