### ISSUE TITLE
unnecessary <p class="first"> inserted between <li> , <a> , <td> when generate translated html

### ISSUE THREAD

**Issue by yu-liang-dev** [sphinx-doc/sphinx#3588]
### Problem

unnecessary `<p class="first">`  inserted between `<li>` when generate translated html

#### Procedure to reproduce the problem

I translated some text in .po file like this:

![image](https://cloud.githubusercontent.com/assets/9611408/24343997/00b7dab6-12fc-11e7-95e3-171ebb800b67.png)

then use sphinx-intl to build and sphinx-build to generate html

```
sphinx-intl build 
make -e SPHINXOPTS="-D language='zh-CN'" html
```

finally, some unnecessary `<p class="first">`  inserted between `<li>`. (Whether Chinese or English)

![image](https://cloud.githubusercontent.com/assets/9611408/24344053/39c1ba8e-12fc-11e7-8517-19fdecd46637.png)

also inserted between `<a>`, `<td>`

![image](https://cloud.githubusercontent.com/assets/9611408/24344262/3030b69a-12fd-11e7-968e-cf2553fa25a8.png)

just use `make html` or untranslated `<li>` will not be inserted unnecessary `<p class="first">`

set ``language`` to ``zh-CN`` in `conf.py` then use `make html` also result in this problem.
#### Expected results

remove unnecessary `<p class="first">` from `<li>` , `<a>`, `<td>` when generate translated html

### Environment info
- OS: Mint 18
- Python version: 3.5.2
- Sphinx version: 1.3.3

Thanks for any suggest !

**Comment by tk0miya** [comment]
It is a well-known behavior of docutils (a library for reST).
http://docutils.sourceforge.net/FAQ.html#how-are-lists-formatted-in-html

You can see it even without translation.
```
list containing paragraph
-------------------------

* foo
* bar

  baz

list not containing paragraph
-----------------------------

* foo
* bar
```

To disable it, please specify `html_compact_lists` option to `False`.
http://www.sphinx-doc.org/en/stable/config.html#confval-html_compact_lists

Thanks,

**Comment by kozzzx** [comment]
@tk0miya Thanks for your help. I think this not cause by ``html_compact_lists``.
You can see from picture. untranslated <li> will not be inserted unnecessary <p class="first">.

**Comment by yu-liang-dev** [comment]
@tk0miya 
Thank you for your help. But I think this question is not caused by ``html_compact_lists``. and this question is also in `<a>` or `<td>`.

I did an experiment about it. 

I have three untranslated `<li>` and three translated `<li>`.
Then use ``make -e SPHINXOPTS="-D language='zh-CN'" html`` to generate HTML.

![image](https://cloud.githubusercontent.com/assets/9611408/24506291/93596016-158f-11e7-9b3e-c79ad3ce9faf.png)

**Step 1**
Not specify ``html_compact_lists``. I got this HTML, only three translated `<li>`  inserted `<p class="first">`
![image](https://cloud.githubusercontent.com/assets/9611408/24506378/def9176e-158f-11e7-9d11-03eb2da51697.png)

**Step 2**
Specify ``html_compact_lists`` to ``True`` in `conf.py`.
![image](https://cloud.githubusercontent.com/assets/9611408/24506434/0ebe9168-1590-11e7-8e2b-c77b0b7890c1.png)
I got same HTML. only three translated `<li>`  inserted `<p class="first">`
![image](https://cloud.githubusercontent.com/assets/9611408/24506505/51bdbfca-1590-11e7-825a-1fa047d21baa.png)

**Step 3**
Specify ``html_compact_lists`` to ``False`` in `conf.py`.
![image](https://cloud.githubusercontent.com/assets/9611408/24506801/38059296-1591-11e7-91f2-e3897ca8d7ba.png)
I got different HTML. all `<li>`  inserted `<p class="first">`, but not what i want.
![image](https://cloud.githubusercontent.com/assets/9611408/24506680/e2d71498-1590-11e7-9d81-9fd9f0df1b56.png)

Step1 and Step2 got same HTML, specify ``html_compact_lists`` to ``True`` have no effect on translated `<li>`.
I want translated `<li>`, can compact like untranslated `<li>` :
```
<li>Session based authentication</li>
<li>Role management</li>
<li>Password encryption</li>
<li>基础 HTTP 身份验证</li>
<li>基于令牌的身份验证</li>
<li>基于令牌的账户激活 (可选)</li>
```

**Comment by barbara-sfx** [comment]
I've been seeing this in tables, with both class="first" and "last", when a cell has >1 paragraph, just never got around to asking about it and I can't find that class defined anywhere. Can I make it go away?

```
<td><p class="first">blahblah.</p>
<p class="last">blahblah</p>
</td>

**Comment by jfbu** [comment]
@barbara-sfx this looks like some other problem, can you open other issue with the corresponding source in reStructuredText ?

**Comment by jfbu** [comment]
@kozzzx I reproduced your problem. Whenever one builds an internationalized html, the compact list setting is ignored and the `<p>` tags are added. Moreover, only the list items with the translated strings get the `<p>` tag (of course with ``html_compact_lists = False`` all `<li>` items get the `<p>` tag).

The latter behaviour is even more disconcerting than the usual one from Docutils where, if I recall correctly, all items are treated alike, either with or without `<p>` tags (if they fulfill the `simple item` condition). Personally I find the concept of `simple list` from Docutils ([here](http://docutils.sourceforge.net/docs/user/config.html#compact-lists)) very weird one and I have already been surprised by its behaviour (#3489). But I do agree that your are pin-pointing a seemingly even more weird situation.

@tk0miya what do you think ? To test this I prepared 
```
Welcome to FOO's documentation!
===============================

bonjour
=======

* demain
* hier
* avant-hier
* la semaine prochaine
* la semaine dernière

Au revoir!

```
and ran `make gettext`, renamed the `index.pot` in build to `index.po` to top repertory, added some translations therein but not all, executed ``msgfmt "index.po" -o "locale/en/LC_MESSAGES/index.mo"`` and then ``make -e SPHINXOPTS="-D language='en'" html`` and I get same as in @kozzzx reporting. This is indeed very disturbing when only some items are affected because they are the translated ones.

**Comment by tk0miya** [comment]
Oh, I'm sorry. It's my wrong. I'll also take a look later.
@jfbu thank you for your help!

**Comment by tk0miya** [comment]
It seems the nodes for translated paragraph are marked as "translated".

Original psuedoxml:
```
    <section ids="bonjour" names="bonjour">
        <title>
            bonjour
        <bullet_list bullet="*">
            <list_item>
                <paragraph>
                    demain
            <list_item>
                <paragraph>
                    hier
            <list_item>
                <paragraph>
                    avant-hier
            <list_item>
                <paragraph>
                    la semaine prochaine
            <list_item>
                <paragraph>
                    la semaine dernière
```
Translated pseudoxml:
```
    <section ids="bonjour" names="bonjour hello">
        <title translated="True">
            Hello
        <bullet_list bullet="*">
            <list_item>
                <paragraph translated="True">
                    tomorrow
            <list_item>
                <paragraph translated="True">
                    yesterday
            <list_item>
                <paragraph translated="True">
                    day before yesterday
            <list_item>
                <paragraph translated="True">
                    next week
            <list_item>
                <paragraph translated="True">
                    last week
```

In addition, the docutils considers them as not compactable paragraph.
(In detail, please refer `docutils.writers.html4css1.HTMLTranslator.should_be_compact_paragraph()`)

@shimizukawa Why these nodes are marked as "translated"? Where are the attribute used? I think they should be removed (at least processing in the writer).

**Comment by tk0miya** [comment]
ping @shimizukawa

**Comment by shimizukawa** [comment]
I removed 'translated' attribute from all of nodes. (on 1.6-release and stable branch)
@kozzzx can you please check the behavior with stable branch code?
```
pip install https://github.com/sphinx-doc/sphinx/archive/stable.zip
```

**Comment by yu-liang-dev** [comment]
@shimizukawa Thank you for update. I think it is fixed.

## Before

pip list

![b](https://cloud.githubusercontent.com/assets/9611408/25577148/bbaf80a2-2e96-11e7-98c4-51b578a25396.png)

html

![b1](https://cloud.githubusercontent.com/assets/9611408/25577150/be3f3358-2e96-11e7-8587-2fbcdff275b7.png)
![b2](https://cloud.githubusercontent.com/assets/9611408/25577152/c0da3df6-2e96-11e7-87dc-01c480774510.png)
![b3](https://cloud.githubusercontent.com/assets/9611408/25577156/c5209d88-2e96-11e7-802e-90f2ac8ca5d3.png)

## Use https://github.com/sphinx-doc/sphinx/archive/stable.zip

pip list

![a](https://cloud.githubusercontent.com/assets/9611408/25577174/e36c84f0-2e96-11e7-8244-6e1c36cb3a5c.png)

html

![a1](https://cloud.githubusercontent.com/assets/9611408/25577177/e4b0a72e-2e96-11e7-94b1-364799a4ccbb.png)
![a2](https://cloud.githubusercontent.com/assets/9611408/25577180/e6fa4878-2e96-11e7-84b6-e8e38ac58566.png)
![a3](https://cloud.githubusercontent.com/assets/9611408/25577185/e8b22e88-2e96-11e7-8747-8bcd0e4d8bb4.png)

**Comment by shimizukawa** [comment]
@kozzzx Thanks for your quick confirmation!
Yes, it seems fine.
