### ISSUE TITLE
Errors due to forward/backslash in test suite

### ISSUE THREAD

**Issue by Andne** [sphinx-doc/sphinx#3592]
### Problem
I've been trying to work on an improvement to intersphinx but am getting confused by errors in the test suite on windows.  These appear to be false negatives, most often due to path separator issues.  More details below, is this something that should be corrected?  Based on what I'm seeing, I suspect runs on windows may at times generate paths with mixed separators, but I haven't investigated that yet.  Should the various modules be updated to always use forward slash since that's what browser URLs are supposed to contain?

#### Procedure to reproduce the problem
```
python.exe run.py --color=no --capture=sys --ignore py35
```

#### Error logs / results
Test result summary shows failures
```
25 failed, 857 passed, 23 skipped in 95.91 seconds
```

#### Expected results
I assume there should be no failures, the test suite appears to work fine on travis-ci

### Environment info
- OS: Windows 8.1
- Python version: 2.7.13
- Sphinx version: stable
- Command Prompt

**Comment by tk0miya** [comment]
Thank you for reporting. But I don't have windows PC. So I can't fix it.
If possible, could you send us pull request to fix it?

ping @shimizukawa, please take a look if you have time now.

**Comment by Andne** [comment]
I can work on fixing it, but I need to know which way is best.  I see two main options:
1. Update the tests to expect the generated path specifiers, least impact on the code itself but maybe not ideal.
2. Add logic to normalize URI's as needed in the code.  The simplest way I know to do this is add `uri = uri.replace(path.sep, '/')` before writing the uri to the files.  Feels a bit hackish to me, but may be better from the standpoint of what going out in the files, this way they should have only forward slashes in them which may be more correct for html file content.

Thoughts?

**Comment by tk0miya** [comment]
Sorry, I can't say comments because I don't know what error happened.
What I know is 25 errors are happened in windows.

Could you show me the detail of errors? then I will help you.

**Comment by Andne** [comment]
I'll have to see if I can get the full results, it tends to exceed the scroll-back on my command window, I've been having to run a single test file at a time in order to know what I'm working on.

Some of the ones I have started to look into appear to just be string mismatches where expected contained `/` and actual contained `\`.  Off the top of my head, I know that some in `test_intl.py` and one in `test_ext_intersphinx.py` are like this.  These are what I'm asking about for now, they most often appear to be a result of the use of `path.sep` or `path.join()`.  Should I be updating the tests to expect `\` or updating the application to always generate `/`?

**Comment by tk0miya** [comment]
If my memory is correct, Sphinx usually uses `/` for docnames and URLs. And either is fine for paths.
So it is important what purpose the string is used for.
(So I'd like to know where the error happened.)

**Comment by Andne** [comment]
Here's the list of assertions from a full test run:
```
================================== FAILURES ==================================
sphinx\ext\autodoc.py:782: AttributeError: type object 'EnumCls' has no attribute '__members__'
sphinx\util\__init__.py:495: ExtensionError: Could not import parsermod (needed for source parser) (exception: No module named parsermod)
sphinx\util\__init__.py:495: ExtensionError: Could not import parsermod (needed for source parser) (exception: No module named parsermod)
sphinx\util\__init__.py:495: ExtensionError: Could not import parsermod (needed for source parser) (exception: No module named parsermod)
sphinx\util\__init__.py:495: ExtensionError: Could not import parsermod (needed for source parser) (exception: No module named parsermod)
sphinx\util\__init__.py:495: ExtensionError: Could not import parsermod (needed for source parser) (exception: No module named parsermod)
sphinx\util\__init__.py:495: ExtensionError: Could not import parsermod (needed for source parser) (exception: No module named parsermod)
sphinx\util\__init__.py:495: ExtensionError: Could not import parsermod (needed for source parser) (exception: No module named parsermod)
sphinx\util\__init__.py:495: ExtensionError: Could not import parsermod (needed for source parser) (exception: No module named parsermod)
sphinx\util\__init__.py:495: ExtensionError: Could not import parsermod (needed for source parser) (exception: No module named parsermod)
sphinx\util\__init__.py:495: ExtensionError: Could not import parsermod (needed for source parser) (exception: No module named parsermod)
sphinx\util\__init__.py:495: ExtensionError: Could not import parsermod (needed for source parser) (exception: No module named parsermod)
sphinx\util\__init__.py:495: ExtensionError: Could not import parsermod (needed for source parser) (exception: No module named parsermod)
sphinx\util\__init__.py:495: ExtensionError: Could not import parsermod (needed for source parser) (exception: No module named parsermod)
sphinx\util\__init__.py:495: ExtensionError: Could not import parsermod (needed for source parser) (exception: No module named parsermod)
sphinx\util\__init__.py:495: ExtensionError: Could not import parsermod (needed for source parser) (exception: No module named parsermod)
sphinx\util\__init__.py:495: ExtensionError: Could not import parsermod (needed for source parser) (exception: No module named parsermod)
sphinx\util\__init__.py:495: ExtensionError: Could not import parsermod (needed for source parser) (exception: No module named parsermod)
tests\test_build_html.py:153: AssertionError: Warnings don't match:
tests\test_build_latex.py:147: AssertionError: Warnings don't match:
tests\test_build_linkcheck.py:26: assert 2 == 1
tests\test_build_linkcheck.py:39: assert not "links.txt:3: [broken] https://www.w3.org/TR/2006/REC-xml-names-20060816/#defaulting: HTTPSConnectionPool(host='www.w3...fiedHTTPSConnection object at 0x05498690>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed',))\n"
tests\test_build_texinfo.py:43: AssertionError: Warnings don't match:
tests\test_ext_intersphinx.py:208: AssertionError: assert 'py3k\foo.html#module-module1' == 'py3k/foo.html#module-module1'
tests\\test_intl.py:161: AssertionError: assert 'Datei mit UT...uts: \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd.\\n' == 'Datei mit UTF...mlauts: \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd.\\n'
tests\util.py:89: AssertionError: The node[uri] is not 'subdir/svgimg.*': u'subdir\\svgimg.*'
tests\util.py:89: AssertionError: The node[candidates] is not {'*': 'subdir/rimg.png'}: {'*': u'subdir\\rimg.png'}
tests\test_util_i18n.py:252: AssertionError: assert 'subdir\\en/foo.png' == 'subdir/en/foo.png'
============= 28 failed, 854 passed, 23 skipped in 106.31 seconds =============
```

I guess not as many as I thought have path errors in them.  A lot seem to have something to do with a missing extension/module.  Towards the end several have mis-matched slashes though.  I'm a little unsure why `test_intl.py` has its backslashes escaped though.

**Comment by tk0miya** [comment]
Thanks!
Surely, I feel it is better to use `posixpath.join()` to represent paths using slash.
@shimizukawa do you have any opinions?

On the other hand, I don't know why loading parsermod failed. It should be investigated more.

**Comment by shimizukawa** [comment]
Actually, I didn't use windows environment recently (testing on docker ubuntu instead).
So I setup appveyor: https://ci.appveyor.com/project/sphinxdoc/sphinx/build/1.0.3
The result of appveyor is not good as @Andne reported.

Sphinx will work with either path separator, but if we have to force a slash we are using `sphinx.util.osutil.canon_path`. `sphinx.builders.gettext` uses canon_path to force the slash for paths in the generated pot files even if on windows envronment.

We will fix the failed tests.

**Comment by tk0miya** [comment]
I marked this as "help wanted". At this moment, no maintainers uses windows platform. So it is hard to fix this from our side.

.. note:: As a trial, I made #3619 once. But I could not determine it works fine or not.
