### ISSUE TITLE
[documentation] Compare Sphinx vs. docutils

### ISSUE THREAD

**Issue by stephenfin** [sphinx-doc/sphinx#3595]
I'm trying to document the various directives Sphinx supports, but I'm getting a bit lost in identifying which directives are provided by Sphinx and which ones are provided by docutils. There don't appear to be any good guides that provide a summary of the relationship between Sphinx and docutils.

I'd love some help understanding how the two are related, and think this is something that should probably go into the docs.

**Comment by barbara-sfx** [comment]
This page http://www.sphinx-doc.org/en/stable/rest.html#directives mentions "Directives added by Sphinx are described in Sphinx Markup Constructs."  http://www.sphinx-doc.org/en/stable/markup/index.html#sphinxmarkup

The latter also notes at the bottom "More markup is added by Sphinx Domains."  http://www.sphinx-doc.org/en/stable/domains.html#domains

hth

**Comment by tk0miya** [comment]
Thanks @barbara-sfx,
AFAIK there are no *good* documents which compares Sphinx and docutils.
So it would be nice if you update/improve our document with your results.

Thanks,
