### ISSUE TITLE
Add a way to easily include a Google custom search.

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#36]
Since the JS-based search is not optimal for every project.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/36
- Originally reported by: Georg Brandl
- Originally created at: 2008-11-09T20:28:42.675

**Comment by tk0miya** [comment]
You can customize your search box using google custom search via custom template.

1. Create Google custom search on console: https://cse.google.com/cse/all
2. Copy HTML snippet for Google custom search
3. Paste it into `_templates/searchbox.html` in your project like following:

```
<div>
<h3>{{ _('Quick search') }}</h3>
<script>
  (function() {
    var cx = '......';
    var gcse = document.createElement('script');
    gcse.type = 'text/javascript';
    gcse.async = true;
    gcse.src = 'https://cse.google.com/cse.js?cx=' + cx;
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(gcse, s);
  })();
</script>
<gcse:search></gcse:search>
</div>
```

4. Configure `html_sidebars` to use `searchbox.html` in your document


No special options and extensions are not needed to do that. So it would be better if we add this procedure to our docs as a tip.
