### ISSUE TITLE
MathJax should be loaded with async attribute

### ISSUE THREAD

**Issue by jfbu** [sphinx-doc/sphinx#3606]
It is possible and seems recommended (see the [MathJax CDN change announcement](https://www.mathjax.org/cdn-shutting-down/)) to use the ``async`` attribute for the loading of MathJaX from CDN resource.

This is not done currently,and as explained https://github.com/sphinx-doc/sphinx/pull/3602#issuecomment-291370524:

> But, unfortunately, we don't have an interface to do that.
> sphinx.ext.mathjax uses app.add_javascript() API to add mathjax.js to each HTML file. But this API does not have any options to add async attribute.
> So we have to improve the API as a first step.
> 

From [w3schools page](https://www.w3schools.com/tags/att_script_async.asp), HTML5 should use simply ``async`` but XHTML should use the ``async="async"`` syntax.

### Environment info
- Sphinx version: 1.5.5

Relates to #3602

**Comment by tk0miya** [comment]
Fixed by #5005!
