### ISSUE TITLE
error while building Linux html documentation

### ISSUE THREAD

**Issue by bhardwajhp** [sphinx-doc/sphinx#3608]
Subject: error while building Linux html documentation

### Problem
@localhost linux]$ make htmldocs
  SPHINX  htmldocs --> file:///home/der/workspace/c-cpp/linux/linux/Documentation/output
  DOT     Documentation/media/uapi/v4l/pipeline.dot
  PARSE   include/uapi/linux/dvb/audio.h
  PARSE   include/uapi/linux/dvb/ca.h
  PARSE   include/uapi/linux/dvb/dmx.h
  PARSE   include/uapi/linux/dvb/frontend.h
  PARSE   include/uapi/linux/dvb/net.h
  PARSE   include/uapi/linux/dvb/video.h
  PARSE   include/uapi/linux/videodev2.h
  PARSE   include/uapi/linux/media.h
  PARSE   include/uapi/linux/cec.h
  PARSE   include/uapi/linux/lirc.h
Running Sphinx v1.1.3

Exception occurred:
  File "/home/der/workspace/c-cpp/linux/linux/Documentation/sphinx/load_config.py", line 6, in <module>
    from sphinx.util.pycompat import execfile_
ImportError: cannot import name execfile_
The full traceback has been saved in /tmp/sphinx-err-GmB4kq.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
Either send bugs to the mailing list at <http://groups.google.com/group/sphinx-dev/>,
or report them in the tracker at <http://bitbucket.org/birkenfeld/sphinx/issues/>. Thanks!
make[1]: *** [htmldocs] Error 1
make: *** [htmldocs] Error 2

#### Procedure to reproduce the problem
```
make htmldocs
```

#### Error logs / results
```
# Sphinx version: 1.1.3
# Python version: 2.7.5
# Docutils version: 0.11 repository
# Jinja2 version: 2.7.2
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sphinx/cmdline.py", line 188, in main
    warningiserror, tags)
  File "/usr/lib/python2.7/site-packages/sphinx/application.py", line 102, in __init__
    confoverrides or {}, self.tags)
  File "/usr/lib/python2.7/site-packages/sphinx/config.py", line 216, in __init__
    exec code in config
  File "/home/jitender/workspace/c-cpp/linux/linux/Documentation/conf.py", line 27, in <module>
    from load_config import loadConfig
  File "/home/jitender/workspace/c-cpp/linux/linux/Documentation/sphinx/load_config.py", line 6, in <module>
    from sphinx.util.pycompat import execfile_
ImportError: cannot import name execfile_

```
- <public link of unexpected result if you have>

#### Expected results
Generate linux documentation

### Reproducible project / your project
https://github.com/torvalds/linux

### Environment info
- OS: Linux/CentOS
-  Sphinx version: 1.1.3
- Python version: 2.7.5
- Docutils version: 0.11 repository
- Jinja2 version: 2.7.2

**Comment by tk0miya** [comment]
`sphinx.util.pycompat.execfile_` was introduced at 1.2 (ref: 05718e4a1).
Please upgrade your Sphinx to new one.

Note: Now we are supporting Sphinx-1.5.x series only. So I recommend you to upgrade to latest one.
