### ISSUE TITLE
autodoc extension does not support f-strings under Python 3.6

### ISSUE THREAD

**Issue by lelit** [sphinx-doc/sphinx#3611]
The autodoc extension (or more probably the underlying pycode/pgen2) does not recognize `f"strings"`, so it fails to extract docstrings from a class that happens to use the new literals.

**Comment by tk0miya** [comment]
Indeed, we need to improve `pycode`.

**Comment by tk0miya** [comment]
Fixed by #3937 
Thank you for reporting
