### ISSUE TITLE
Sphinx 1.5 requires requests>=2.6.0

### ISSUE THREAD

**Issue by ipwnponies** [sphinx-doc/sphinx#3614]
Subject: Sphinx 1.5 depends on requests>=2.6.0

### Problem
- According to setup.py, sphinx depends on requests>=2.0.0. InsecurePlatformWarning class was introduced in requests 2.6.0.

#### Procedure to reproduce the problem
I've distilled the error out of the specific project:
```shell
virtualenv sphinx_repo
sphinx_repo/bin/pip install sphinx==1.5.0 requests==2.5.0 &> /dev/null
sphinx_repo/bin/python -c 'from requests.packages.urllib3.exceptions import InsecurePlatformWarning'
sphinx_repo/bin/pip install --upgrade requests==2.6.0 &> /dev/null
sphinx_repo/bin/python -c 'from requests.packages.urllib3.exceptions import InsecurePlatformWarning'
```

#### Error logs / results
This is the error snippet I encountered on my project when building docs:
```
making output directory...

Exception occurred:
  File "/blargh/.tox/docs/local/lib/python2.7/site-packages/sphinx/util/requests.py", line 48, in <module>
    requests.packages.urllib3.exceptions.InsecurePlatformWarning)
AttributeError: 'module' object has no attribute 'InsecurePlatformWarning'
```

#### Expected results
I've pinned sphinx==1.5.5 and requests==2.5.0 in requirements, which are expected to be compatible.

### Reproducible project / your project
- [See above](#Procedure-to-reproduce-the-problem)

### Environment info
- OS: Ubuntu Trusty
- Python version: 2.7
- Sphinx version: 1.5.0

This [commit](https://github.com/sphinx-doc/sphinx/commit/0b9ee8d451ded14718c45988eab5111a2f36dc12#diff-bb67587af94a24f53692228ea27061edR49) first introduced the use of `InsecurePlatformWarning` to sphinx and was released as version 1.5.
`requests` introduced InsecurePlatformWarning in this [commit](https://github.com/kennethreitz/requests/commit/a0790f37b762ec737b2a4a13c167aad2defa8575#diff-b3a258e3bb4c5fd2bc2d44af48393904R162), which was released in version 2.6.0.

**Comment by tk0miya** [comment]
Thank you for reporting.
Fixed at b6e4cce.
