### ISSUE TITLE
Add papersize to latex_documents (to create same PDF in two sizes simultaneously (letterpaper & a4paper))

### ISSUE THREAD

**Issue by ghost** [sphinx-doc/sphinx#3617]
This is a combined question and enhancement request (with suggestion).

I want to build two versions of the same document, in both A4 and US letter size. I don't want to have two conf.py files (one obvious solution) and have to run the build twice. A natural place for it would be to move the 'papersize' argument to become an element of latex_documents. That already has my list of individual PDFs.

Background: US customers want to print portions of A4 PDFs but their printer crops the page (and no, I don't want to tell them fiddle with printer settings). I want to offer both sizes without too much complexity or extending the build time.

**Comment by tk0miya** [comment]
Please use `latex_elements['papersize']` instead.
You can use `-D latex_elements.papersize=a4paper` option of `sphinx-build` without more conf.py.

**Comment by ghost** [comment]
Hi, thanks, I reluctantly came to the solution/conclusion. You have to build twice but at least I got what I wanted.
