### ISSUE TITLE
def foo((a, b)): .. causing unhashable type: 'list'

### ISSUE THREAD

**Issue by thebjorn** [sphinx-doc/sphinx#3618]
Subject: This happened when ReadTheDocs used a newer version of sphinx than I had been using.

### Problem
The following valid code:
```
def foo((a, b)):
    "Returns sum of a and b."
    return a + b
```
causes this warning:
```
w:\srv\tmp\sphinxparam\myfile.rst:4: WARNING: error while formatting arguments for myfile.foo: unhashable type: 'list'
```

#### Procedure to reproduce the problem
All commands used are listed in: https://github.com/thebjorn/sphinx-unhashable/blob/master/README

The commands consist of: creating a new virtualenv, downloading latest sphinx, running sphinx-quickstart and sphinx-apidocs, adding the generated modules.rst to index.rst, and typing make.

#### Error logs / results
This didn't happen with the previous version I used, Sphinx 1.3.2
```
w:\srv\tmp\sphinxparam\myfile.rst:4: WARNING: error while formatting arguments for myfile.foo: unhashable type: 'list'
```

A github repo is here: https://github.com/thebjorn/sphinx-unhashable

#### Expected results
No warning.

### Reproducible project / your project
https://github.com/thebjorn/sphinx-unhashable

### Environment info
- OS: Windows 10 (me), Read The Docs (reported)
- Python version: 2.7.11
- Sphinx version: 1.5.5
- Extra tools e.g.: None

**Comment by tk0miya** [comment]
Thank you for reporting.
Fixed at 7897678.
