### ISSUE TITLE
Intersphinx doesn't load inventory's compressed with gzip

### ISSUE THREAD

**Issue by wisaac407** [sphinx-doc/sphinx#3624]
Subject: Intersphinx doesn't load inventory's compressed with gzip

### Problem
When using intersphinx to load an object inventory file compressed with gzip it fails to load the compressed file. Running the command `python -m sphinx.ext.intersphinx https://docs.blender.org/api/blender_python_api_master/objects.inv` outputs nothing, where as running `https://docs.python.org/3/objects.inv` outputs the expected info. After poking around a little it seems that it's because the first file is gzipped and the second one isn't.

#### Procedure to reproduce the problem
```
python -m sphinx.ext.intersphinx https://docs.blender.org/api/blender_python_api_master/objects.inv
```

#### Error logs / results
There was no output.

#### Expected results
It should print all kinds of data.

### Environment info
- OS: Ubuntu 16.04
- Python version: 3.5.2
- Sphinx version: 1.5.5

**Comment by tk0miya** [comment]
Fixed at 1db67af.
Thank you for reporting!
