### ISSUE TITLE
Include rinohtype as a suggestion for building PDFs

### ISSUE THREAD

**Issue by brechtm** [sphinx-doc/sphinx#3626]
Seeing that rinohtype is now fairly mature, I'd like to suggest it being referenced in the documentation besides rst2pdf. I can provide a pull request, of course.

You might want to consider updating the docs with respect to rst2pdf as well, since it hasn't seen a release since December 2012. I did some quick tests and the Sphinx builder included with it crashes rendering the Sphinx docs with Sphinx 1.5.5 unless the `pdf_use_index` in `conf.py` is set to `False`. `pdf_use_modindex` also needs to be set to `False` when rendering the Requests docs.

**Comment by tk0miya** [comment]
+1; it is worthy for giving users choices. Could you send us a pull request please?
