### ISSUE TITLE
Implement get_full_qualified_name() to C, C++, JavaScript and reST domains

### ISSUE THREAD

**Issue by tk0miya** [sphinx-doc/sphinx#3630]
The remained task of #3425, we should implement `get_full_qualified_name()` to C, C++, JavaScript and reST domains.

**Comment by jakobandersen** [comment]
I'm not sure exactly how intersphinx works, but if I understand correctly then it is something like:
1. Each Sphinx compilation generates ``objects.inv``, which essentially contains all declarations that one could/should reference in the project.
2. Other projects load these files, and
3. looks up missing references using the appropriate context. I would think this lookup should proceed as if the external declarations were in the same project.

How is the ``get_full_qualified_name()`` function used? Templates in C++ makes this complicated (as always), as you can have something like:
```rst

.. cpp:class:: template<typename TA> A

   .. cpp:var:: int a

   .. cpp:class:: template<typename TB> B

      .. cpp:var:: int b
```
and then in another project I guess you should be able to do
```rst
.. cpp:namespace:: template<typename TA> A

Link to variable: :any:`a`.

.. cpp:namespace-push:: template<typename TB> B

Link to variable: :any:`b`.
But also: :any:`a`.
```
Must the data in objects.inv be strings, or can pickling be used? There is already a way to have lookup keys for symbols in the C++ domain, but they are lists of tuples of internal AST objects.

**Comment by tk0miya** [comment]
`get_full_qualified_name()` is called at the 3rd step; "looking up" step. It is not related with building objects.inv.

At current implementation, intersphinx only uses `target` key on pending_xref node. It does not refer the context attributes. For example, it does not refer `cpp:parent_key` on looking up C++ objects.

>Must the data in objects.inv be strings, or can pickling be used? There is already a way to have lookup keys for symbols in the C++ domain, but they are lists of tuples of internal AST objects.

Now intersphinx uses `Domain#get_objects()` to gather the symbols (objects) from each domain.
As a quick look, C++ domain uses following code to represent objects:
```
            name = text_type(symbol.get_full_nested_name()).lstrip(':')
```

**Comment by tk0miya** [comment]
I implement the methods for each domains in #3658 
@jakobandersen Could you check this please? As a quick look, it seems working. But I need your reviewing :-)
