### ISSUE TITLE
Env vars for sphinx-build & pdflatex options

### ISSUE THREAD

**Issue by ghost** [sphinx-doc/sphinx#3632]
We use maven/jenkins to build sphinx docs. I noticed the new Makefile is much simpler and I'd like to use it instead of a wrapper script. However I can't because the sphinx output directory can't be specified by environment variable, but must be a sphinx-build command line arg. There are also some useful settings in pdflatex that might be worthy of setting before/in the (new improved) sphinx Makefile.

Use-case: We create A4 and US letter versions of a PDF doc. By default, the output dir is _build/latex for both. A wrapper script separately calls sphinx-build and pdflatex on the tex files, with different output latex dirs each time.

**Comment by tk0miya** [comment]
How about this?
```
make latexpdf BUILDDIR=a4_paper
```

**Comment by tk0miya** [comment]
Please feel free to reopen if you still have problem.
Thanks,
