### ISSUE TITLE
symfony-docs-2.8

### ISSUE THREAD

**Issue by Aguirolacu** [sphinx-doc/sphinx#3636]
Subject: <what happen when you do on which document project>

### Problem
- make html

#### Procedure to reproduce the problem
```
<Paste your command-line here which cause the problem>
```

#### Error logs / results
```
File "D:\Desarrollo\wamp\www\Desarrollo\symfony-docs-2.8\_theme\_exts\symfonycom\sphinx\__init__.py", line 77, in visit_literal_block
    **highlight_args)
  File "c:\python27\lib\site-packages\sphinx\highlighting.py", line 147, in highlight_block
    type='misc', subtype='highlighting_failure')
TypeError: warner() got an unexpected keyword argument 'type'
```
- <public link of unexpected result if you have>

#### Expected results
<Describe what to actually do>

### Reproducible project / your project
- <link to your project, or attach zipped small project sample>

### Environment info
- OS: Win
- Python version:2.7.13
- Sphinx version:1.5.5
- <Extra tools e.g.: Browser, tex or something else>

**Comment by tk0miya** [comment]
Is this same as #2429?

**Comment by tk0miya** [comment]
It seems not a bug of Sphinx. So I'm closing this now.
Please reopen if you still have this problem.

Thanks,
