### ISSUE TITLE
Reference equation with added "Equation"

### ISSUE THREAD

**Issue by jessetan** [sphinx-doc/sphinx#3638]
When using `:eq:` to reference an equation, the LaTeX output generated by `\eqref` puts the equation number between parentheses, which looks like "(3.1)".

It would be nice if there was a way to have Sphinx output something like "Equation 3.1". This would be similar to what `:numref:` does (e.g. "Section 2.4", "Table 12"). The `numfig_format` config option could be used to set a (translated) label.

The only workaround I see know is to [override the eqref command](https://tex.stackexchange.com/questions/28894/modify-eqref-command), but that is not so user friendly

**Comment by tk0miya** [comment]
I proposed `math_eqref_format` in #3676. Please try it :-)
