### ISSUE TITLE
`autodoc_member_order = 'bysource'` does not work for modules containing __all__

### ISSUE THREAD

**Issue by carmenbianca** [sphinx-doc/sphinx#3673]
Subject: `autodoc_member_order = 'bysource'` does not work for modules containing `__all__`

### Problem
When setting `autodoc_member_order` to `'bysource'` in conf.py, it does not work entirely as expected on modules that contain `__all__`. The members are listed in the order dictated by `__all__`, which is expected. But the members of the members are listed alphabetically.

#### Procedure to reproduce the problem
```
- I have a module `foo` in `foo/__init__.py`
- `__init__.py` itself contains no code other than import
  statements from private modules
  (e.g., `from ._bar import spam, eggs`)
- `__init__.py` has a line that says `__all__ = ['spam', 'eggs']`
- `spam`, in this scenario, is a class that contains two
  methods in this order: `b` and `a`.
- Apply Sphinx magic.
- Module foo in Sphinx is listed in this order:
  - spam
    - a
    - b
  - eggs

```

#### Error logs / results
```
N/A
```
- https://i.imgur.com/jzz6VF6.png

#### Expected results
b and a should be swapped.

### Reproducible project / your project
- https://github.com/carmenbianca/foo-sphinx-bug
  - just `make html` in the docs directory.

### Environment info
- OS: Debian Stretch
- Python version: 3.5.3
- Sphinx version: 1.5.3

**Comment by the-holger** [comment]
I have _almost_ the same issue:
- I'm working on a module
- `__init__.py` only contains Docstring and imports
- `__init__.py` **does not** have an `__all__` assignment
- I have the line `autodoc_member_order = 'bysource'` at the end of my conf.py
- Class functions are ordered alphabetically...

### Environment info

OS: macOS 10.12.6
Python version: 3.6.1
Sphinx version: 1.6.2

**Comment by MarvBob** [comment]
I'm working on a package, there is nothing in `__init__.py`.
When I add the line `autodoc_member_order = 'bysource'` in my conf.py, in the documentation some modules are still ordered alphabetically. I can't find why some of them are well ordered by source and some of them aren't. It seems that the problem occurs more when a module contains class declaration.

### Environment info
- OS: Windows 10
- Python version: 2.7.13
- Sphinx version: 1.6.3

**Comment by peterjc** [comment]
The comment https://github.com/sphinx-doc/sphinx/issues/2042#issuecomment-203033366 suggests ``bysource`` fails if Sphinx failed to parse the Python code, which might be related to the pattern you are seeing?

**Comment by eric-wieser** [comment]
> `bysource` fails if Sphinx failed to parse the Python code, which might be related to the pattern you are seeing?

I've seen this happen for class definitions where `cls.__module__` is overloaded, as this results in `inspect.getsource` failing.
