### ISSUE TITLE
No 1.5.6 release tarball available

### ISSUE THREAD

**Issue by jluttine** [sphinx-doc/sphinx#3678]
At the home page http://www.sphinx-doc.org/en/stable/ it is said that the current version is 1.5.6 and that one can get it from Python Package Index. However, there is no 1.5.6 available in PyPI: https://pypi.python.org/simple/sphinx/ nor there is 1.5.6 release in this GitHub repository. Where can I get 1.5.6 release tarball?

**Comment by tk0miya** [comment]
Sorry for confusing. it's wrong. v1.5.6 is not released yet.

**Comment by tk0miya** [comment]
Fixed by #3679
