### ISSUE TITLE
"Error: The websupport.utils module cannot be found." during sphinx-build

### ISSUE THREAD

**Issue by erikrose** [sphinx-doc/sphinx#3688]
Subject: When I run sphinx-build under Sphinx 1.6b2, I get an error. Previous versions were fine.

### Problem
When I run `make html` on the [Fathom](https://github.com/mozilla/fathom) project, I get this:

```
(py27) [12:36:03 Smoof/fathom/docs]% make html
sphinx-build -b html -d _build/doctrees   . _build/html
Error: The websupport.utils module cannot be found. Did you install Sphinx and its dependencies correctly?
make: *** [html] Error 1
```

#### Procedure to reproduce the problem
```
git clone git@github.com:mozilla/fathom.git
npm install jsdoc
pip install 'sphinx-js>=1.5,<2.0' sphinx_rtd_theme
cd docs
PATH="$CHECKOUT/node_modules/.bin:$PATH"
make html
```

Note that this works fine under Sphinx 1.6b1; it breaks in 1.6b2.

#### Expected results
I'd expect the docs to build successfully, as they do under Sphinx 1.6b1 and earlier.

### Environment info
- OS: Mac and Travis's Ubuntu workers
- Python version: 2.7
- Sphinx version: 1.6b2
- sphinx-js 1.5.2

**Comment by tk0miya** [comment]
Fixed at 0135948
