### ISSUE TITLE
HTML search don't work at all since 1.5

### ISSUE THREAD

**Issue by pybride** [sphinx-doc/sphinx#3691]
Subject: HTML search don't work at all since 1.5

### Problem
- Search result page only display "Searching..."

#### Procedure to reproduce the problem
```
Try to search a term that returned result with 1.4.9 (or before)
```

#### Error logs / results
```
No result displayed

Browser debugger always break in function startPulse of searchtools.js, on line:
Search._pulse_status = (Search._pulse_status + 1) % 4;

```

### Environment info
- OS: Win 10
- Python version: 2.7
- Sphinx version: any 1.5.X
- sphinx-pretty-searchresults 0.1.6
- Tested in Firefox, Edge and Chrome

**Comment by tk0miya** [comment]
what theme do you use?
is this related with #3203?

**Comment by pybride** [comment]
I'm using a modified version of sphinx_rtd_theme.

I tried the linked fix (SOURCELINK_SUFFIX), the search is then working, but only the title is display in the results, not the text itself. I will try to update the whole theme.

Anyway, I don't understand why  #3203 was closed, as it is a sphinx bug: a breaking change that isn't listed in release notes.
If Sphinx need something new from theme, it should be clearly documented.

**Comment by tk0miya** [comment]
ah, you're right. indeed, this is breaking changes since v1.5.
So I added an entry to CHANGES now: https://github.com/sphinx-doc/sphinx/commit/097cd87fd8ceda2fed377c5207909e351315b24e

**Comment by pybride** [comment]
Only SOURCELINK_SUFFIX was missing in the theme, but the search still not display the full result.
As I'm using sphinx-pretty-searchresults, the files in _sources are like something.txt and not something.rst.txt
And sphinx-pretty-searchresults isn't the issue, because it is just using sphinx to output text.

It isn't possible to configure html_sourcelink_suffix to remove this buggy behavior. I think that the html_sourcelink_keep_suffix from #2399 is missing. Or is it a way that I didn't found to remove this behavior?
Sure, I can modify my searchtools.js_t, but it isn't a good solution.

**Comment by tk0miya** [comment]
Unfortunately, there are no option to remove the behavior. to support multiple mark-ups, the behavior is required.

**Comment by pybride** [comment]
I will close this bug, and I created a new one that describe better the issue, see #3696
