### ISSUE TITLE
Moving :doc: to std domain broke backwards compatibility

### ISSUE THREAD

**Issue by mgeier** [sphinx-doc/sphinx#3698]
Before, I could use `sphinx.addnodes.pending_xref(reftype='doc', refdomain=None, ...)`, which now doesn't work anymore and prints this warning:

    WARNING: 'doc' reference target not found: ...

Using `refdomain='std'` would be a work-around, but this (I think) wouldn't work in older versions.

See https://groups.google.com/forum/#!topic/sphinx-dev/98bvia7i7II and https://github.com/spatialaudio/nbsphinx/pull/111.

**Comment by tk0miya** [comment]
I made #3699. It converts the nodes automatically.
