### ISSUE TITLE
LaTeX replacement of `✓` by macro `\checkmark` can not be boldened

### ISSUE THREAD

**Issue by jfbu** [sphinx-doc/sphinx#3707]
At https://github.com/sphinx-doc/sphinx/blob/master/sphinx/util/texescape.py#L39, there is 

```
 ('✓', r'\(\checkmark\)'),
```

There are some issues:

1. ``\checkmark`` which is provided by `amssymb` can work in math mode as well as in text mode to the same result. Thus the `\(..\)` are superfluous and would raise an error if the thing was encountered while being already in math mode

2. There is no way to bolden the character: it does not react to `\textbf`,  `\boldmath`, etc.. So it does not provide candidate for the heavy Unicode variant ✔.

3. The replacement itself is unfriendly to lualatex, xelatex users, as OpenType fonts will have the character (often). And even with pdflatex, there are better ways, for example `\usepackage{pifont}` and `\ding{51}`. Then one can use `\ding{52}`  for ✔ (via `\newunicodechar{✔}{\ding{52}}`.

### Environment info
- Sphinx version: 1.5.5

**Comment by tk0miya** [comment]
I don't have strong opinion for this.

Note:

1. `texescape.py` is not applied to math nodes. so it does not cause an error. Of course, removing is okay to me.
2. No idea.
3. I'm okay to switch a rule of escaping by `latex_engine` :-)
