### ISSUE TITLE
LaTeX links: irc protocol

### ISSUE THREAD

**Issue by tobiasHeinke** [sphinx-doc/sphinx#3708]
Subject: If a link uses the irc protocol a warning is shown by the latex-builder.

Might be:
[latex.py#L49](https://github.com/sphinx-doc/sphinx/blob/f547e59a7a6cb3ad56d74edf97c59abe71b5f8d2/sphinx/writers/latex.py#L49)

#### Procedure to reproduce the problem
```
`#blender <irc://irc.freenode.net/blender>`__
```

#### Error logs / results
```
Warning: unusable reference target found: irc://irc.freenode.net/blender
```

### Reproducible project / your project
html:
https://docs.blender.org/manual/en/dev/getting_started/about/community.html#irc-channels

### Environment info
- OS: Win
- Python version: 3.5.3
- Sphinx version: 1.5.5

**Comment by tk0miya** [comment]
Fixed at #3712. Thank you for reporting!
