### ISSUE TITLE
Copright "owner" instead of "holder" in license

### ISSUE THREAD

**Issue by travisspencer** [sphinx-doc/sphinx#3721]
The Sphinx Web site says that the license for the code is BSD. I diffed it though, and noticed that one word is different (at least from the version of the BSD 2-caluse license I found). The Sphinx license says "owner" whereas the BSD license I found on opensource.org uses the word "holder". 

```diff
 "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
-OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
+HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
```

I'm not a lawyer, but I imagine it makes little/no difference. However, when distributing Sphinx in binary form with other OSS in a product where attributions are included in the docs, it is helpful to refer the consumer to an appendix in those docs where all the OSS licenses can be found. This way, the same license need not be repeated over and over for each lib/component that use the same license. Because of this one word change, however, the BSD license used by Sphinx has to be included verbatim in such a doc whereas other components may simply reference to it an appendix.

I know this seems petty and annoying. Sorry. It's just when you have like 50+ OSS components, making this kind of attributions doc as readable as possible is appreciated by users. So, I'm wondering if it is possible to change this one word in the LICENSE file?

**Comment by tk0miya** [comment]
It came from first commit of CHANGES file: fb561d22f6
As a quick look, wikipedia says the templates of 2-clause BSDL uses "COPYRIGHT OWNER". So it seems nobody modifies the word. I don't know where the difference came from.

>IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, ...

https://en.wikipedia.org/wiki/BSD_licenses#2-clause_license_.28.22Simplified_BSD_License.22_or_.22FreeBSD_License.22.29


Anyway, I don't have strong opinion for this. But I can't rewrite this because I'm not an "owner" of this project.
@birkenfeld May we update this?

**Comment by birkenfeld** [comment]
(IANAL.) There is "copyright holder" already in the first line of that paragraph, so it seems reasonable to use "holder" everywhere.

On the other hand, [the spdx.org text](https://spdx.org/licenses/BSD-2-Clause.html) indicates (in red) that the two passages can be replaced with actual name(s), as it is done in the FreeBSD license, so I don't know how useful it would be.

**Comment by tk0miya** [comment]
Thank you for comment. I made for this. Please approve this :-)

**Comment by tk0miya** [comment]
👍

**Comment by travisspencer** [comment]
Thanks @tk0miya and @birkenfeld for this fix!
