### ISSUE TITLE
Memory addresses being output that break reproducible builds

### ISSUE THREAD

**Issue by JustinCappos** [sphinx-doc/sphinx#3722]
I am taking a look at some of Debian's reproducible-builds packages that are still failing and still see some issues that look like they may be from memory addresses being output by sphinx.

For example, django-celery outputs the following memory address (see
https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/diffoscope-results/django-celery.html ):

./usr/share/doc/python-django-celery-doc/html/reference/djcelery.app.html:

<code·​class="descclassname"​>djcelery.​app.​</​code><code·​class="descname">app<​/​code><em·​class="property">·​=·​&lt;​Celery·​default:​**0x7f468b76b310**&gt;​</​em><a·​class="headerlink"·​href="#djcelery.​app.​app"·​title="Permalink·​to·​this·​definition">¶</​a></​dt>

./usr/share/doc/python-django-celery-doc/html/searchindex.js 
​·​·​·​·terms:​·​{	
·​·​·​·​·​·​·​·​"**0x7f468b76b310**":​·​8,​	
·​·​·​·​·​·​·​·​"2to3":​·​0,​

I checked the github issue tracker and this doesn't seem to be listed there, but it is possible that this issue is related: https://github.com/sphinx-doc/sphinx/issues/1721.

**Comment by tk0miya** [comment]
Now sphinx already tries to strip a memory address like `at 0x000000` from arguments.
https://github.com/sphinx-doc/sphinx/blob/1.5.5/sphinx/util/inspect.py#L23

But, in celery's case, it seems the library customizes the representation format of each object.
https://github.com/celery/celery/blob/master/celery/app/utils.py#L73

So I think it is hard to strip the address from celery objects.

**Comment by JustinCappos** [comment]
Would it be possible to make the memory address regex more permissive? https://github.com/sphinx-doc/sphinx/blob/1.5.5/sphinx/util/inspect.py#L23

The broadest change would be to remove ' at ' from the arguments, but there may be a few false positives.  Perhaps also filtering ':0x000000' and similar would work for most cases that are currently missed?

**Comment by tk0miya** [comment]
I'm okay to make it permissive. But I feel it's not easy to support customized repr format.

As a extreme example, I made following example.
```
>>> class Foo():
...     def __repr__(self):
...         return "<Foo; %s>" % id(self)
...
>>> Foo()
<Foo; 4337280448>
```
The developers can make very easily non-regular repr format. So I think it is very hard to remove them perfectly.

I don't have good idea now. But I will accept if your proposal is enough good.

>The broadest change would be to remove ' at ' from the arguments, but there may be a few false positives. 

It's not good way. It makes terrible result like `<object object at >`. It's not human readable.

**Comment by pkmoore** [comment]
Celery's merged a fix to make the representation format match the more standard "at" flavor.  This means the existing Sphinx memory address regex should work now.

**Comment by brianmay** [comment]
Unfortunately the celery team appear to be struggling to make a release :-(

https://github.com/celery/celery/pull/3958#issuecomment-313997326

**Comment by tk0miya** [comment]
I think there are nothing to do from sphinx side. So I'm closing this now.
Please feel free to reopen this if you still have a comment.

Thanks,
