### ISSUE TITLE
Search not finding some values

### ISSUE THREAD

**Issue by ylibman** [sphinx-doc/sphinx#3728]
Subject: HTML Search not finding some values

### Problem
- When searching for certain strings in my project, and I know the text exists, the search returns with a "Your search did not match any documents" message.

### Environment info
- OS: Mac/Win
- Python version: 2.7
- Sphinx version: 1.5.5
- Tested on multiple browsers

**Comment by tk0miya** [comment]
Thank you for reporting. But I can't understand your problem.
Please let me know your problem in detail?
It would be nice if you share your document and actual searching keyword for us.

**Comment by tk0miya** [comment]
Any comments? I need to know your situation to fix the problem.

**Comment by tk0miya** [comment]
I'm closing this now. Please fell free to reopen if you still get the problem.
Thanks,
