### ISSUE TITLE
Docs compilation started to fail when created a requirements.txt file

### ISSUE THREAD

**Issue by DominiqueMakowski** [sphinx-doc/sphinx#3730]
Docs compilation started to fail when created a requirements.txt file

### Problem
I had my documentation up and running (see [here](http://neurokit.readthedocs.io/en/latest/documentation.html)) until I created a [requirements.txt](https://github.com/neuropsychology/NeuroKit.py/blob/master/requirements.txt) file. I created this file to be used by travis and codecov for testing purposes. This file is only called within the [.travis.yml](https://github.com/neuropsychology/NeuroKit.py/blob/master/.travis.yml) file.

However, this makes my docs [build to fail](http://readthedocs.org/projects/neurokit/builds/5402802/). It says that the problem lies within another package (`bioread`) where it throwns the following error `ImportError: No module named numpy`. However, it worked nicely before this requirements.txt file. 

I tried to go to advance settings, tick the "compile in a virtual env" box, and provided the requirements.txt file. But it didn't solve the problem.

Is there a way to ignore this requirements.txt file upon documentation building?

Thanks!

#### Procedure to reproduce the problem
Build the docs

#### Error logs / results
```python
Collecting numpy (from -r requirements.txt (line 1))
  Using cached numpy-1.12.1-cp27-cp27mu-manylinux1_x86_64.whl
Collecting pandas (from -r requirements.txt (line 2))
  Using cached pandas-0.20.1-cp27-cp27mu-manylinux1_x86_64.whl
Collecting scipy (from -r requirements.txt (line 3))
  Using cached scipy-0.19.0-cp27-cp27mu-manylinux1_x86_64.whl
Collecting sklearn (from -r requirements.txt (line 4))
  Using cached sklearn-0.0.tar.gz
Collecting matplotlib (from -r requirements.txt (line 5))
  Using cached matplotlib-2.0.1-cp27-cp27mu-manylinux1_x86_64.whl
Collecting mne (from -r requirements.txt (line 6))
  Using cached mne-0.14.tar.gz
Collecting bioread (from -r requirements.txt (line 7))
  Using cached bioread-1.0.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ygKJm_/bioread/setup.py", line 13, in <module>
        metadata = get_locals(os.path.join('bioread', '_metadata.py'))
      File "/tmp/pip-build-ygKJm_/bioread/setup.py", line 10, in get_locals
        exec(open(filename, 'r').read(), {}, l)
      File "<string>", line 13, in <module>
      File "bioread/__init__.py", line 13, in <module>
        from bioread import reader
      File "bioread/reader.py", line 18, in <module>
        import numpy as np
    ImportError: No module named numpy
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ygKJm_/bioread/
```

### Reproducible project / your project
- [https://github.com/neuropsychology/NeuroKit.py](https://github.com/neuropsychology/NeuroKit.py)

### Environment info
- OS: Win 10
- Python version: 3.5
- Sphinx version: readthedocs

**Comment by tk0miya** [comment]
This might be a question for readthedocs. But, this is not issue list of readthedocs. Please move to support of readthedocs.
Thanks,
