### ISSUE TITLE
Nonsensical code in theming.py

### ISSUE THREAD

**Issue by bgeron** [sphinx-doc/sphinx#3738]
I found this snippet in `theming.py`:

    def load_external_theme(self, name):
        # type: (unicode) -> None
        """Try to load a theme using entry_points.

        Sphinx refers to ``sphinx_themes`` entry_points.
        """
        for entry_point in pkg_resources.iter_entry_points('sphinx_themes'):
            target = entry_point.load()
            if callable(target):
                themedir = target()
                if not isinstance(path, string_types):
                    logger.warning(_('Theme extension %r does not response correctly.') %
                                   entry_point.module_name)
            else:
                themedir = target

            themes = self.find_themes(themedir)
            for entry, theme in iteritems(themes):
                if name == entry:
                    self.themes[name] = theme

I've not tried the code, but `path` seems to refer to the `os.path` module, because it's imported as such and never changed in theming.py. So then surely `isinstance(path, string_types)` doesn't make any sense?

That code seems to have been introduced in this commit: https://github.com/sphinx-doc/sphinx/commit/b405c0aaf52840e370a1ed6c88ab122fb1df644d

Before that commit, the line made more sense:

    def load_theme_plugins():
        # type: () -> List[unicode]
        """load plugins by using``sphinx_themes`` section in setuptools entry_points.
        This API will return list of directory that contain some theme directory.
        """
        theme_paths = []  # type: List[unicode]

        for plugin in pkg_resources.iter_entry_points('sphinx_themes'):
            func_or_path = plugin.load()
            try:
                path = func_or_path()
            except Exception:
                path = func_or_path

            if isinstance(path, string_types):
                theme_paths.append(path)
            else:
                raise ThemeError('Plugin %r does not response correctly.' %
                                 plugin.module_name)

        return theme_paths

Because `path` was actually used as a variable.

Should `path` be replaced by `themedir` here?

**Comment by tk0miya** [comment]
Oops, you're right!
Thank you for helping!

**Comment by tk0miya** [comment]
Fixed at bac9fcb.

**Comment by bgeron** [comment]
That was fast! Thanks.
