### ISSUE TITLE
Enabling multiple make targets and sphinx-build options in Windows make.bat (non-PowerShell)

### ISSUE THREAD

**Issue by bskinn** [sphinx-doc/sphinx#3741]
This may be an obsolete improvement when considered in light of #3145 and #3196, but I've put together modified versions of the [make.bat.new_t](https://github.com/bskinn/sphinx/blob/feature-winmake/sphinx/templates/quickstart/make.bat.new_t) and ~~~[make.bat_t](https://github.com/bskinn/sphinx/blob/feature-winmake/sphinx/templates/quickstart/make.bat_t)~~~ Jinja templates that enable handling of multiple make targets and (AFAIK) the full suite of `sphinx-build` command line options.

It runs through all of the arguments passed to `make.bat` and splits them into `%TARGETS%` and `%OPTIONS%`, then re-runs `make.bat` once for each target, passing in all of the `%OPTIONS%` that were provided.  This makes it somewhat inefficient if, say, `-E` is passed, but I'm not sure how the behavior could be reasonably implemented otherwise. The script performs how I expect it to in a few minutes of poking at different valid and invalid invocation cases (Windows 7 64-bit, py3.5.1, all other packages those installed by default after a `pip install -e .` invocation in the repository root). The `%OPTIONS%` handling accounts (AFAICT properly) for the subset of options that take arguments.

Is this enhancement of interest to the project? 

If so, I didn't see anywhere in the test suite where the commandline/make utilities were tested. If I missed something, please advise where to put any tests; or, if I should create a new suite for some tests, please advise of that.

Further: I'm not 100% sure about Vista / XP / 2k compatibility -- would I need to confirm any of those?

Finally: I've made these changes in a branch off of `stable` for now; please advise if I should rebase to `master`.

Thanks!

**Comment by tk0miya** [comment]
That's sounds good. All PRs are welcome! I've not used windows for long time, but I'll try to review your PR :-)

>If so, I didn't see anywhere in the test suite where the commandline/make utilities were tested. 

Yes, there are no testcases for that. Now we're testing only inside python.
And we don't have testing platform for windows. so it is hard to test batch files on CI server.
So please check the improvement manually.

>Further: I'm not 100% sure about Vista / XP / 2k compatibility -- would I need to confirm any of those?

It seems all of them are no longer supported even by Microsoft. So I think it is not needed.

>Finally: I've made these changes in a branch off of stable for now; please advise if I should rebase to master.

It's tough question. Now we are just going to ship new major version in this weekend.
So `stable` branch will be replaced by `1.6-release` branch after the release.
On the other hand, `master` branch is used for developing. It will released as v1.7 at a half year (or more) later.
It might be better to go with two steps: 1) send the PR into stable branch at first 2) rebase it on stable HEAD after the release. Then we can merge it for v1.6.1.
How about this?

Note: I know this is an improvement. According to our policy, new features should be merged into master branch. But I feel this might be not a breaking change. So +1 for merge this into stable.

**Comment by bskinn** [comment]
@tk0miya This all sounds good to me.  I actually have a few more improvements that I want to include now, so I think I'll just wait until the v1.6 release is made, and then merge into `stable` per your (2).

I agree, that technically it may be more proper to target at `master`, but it doesn't touch the internals of Sphinx at all; it's a tooling augmentation more than anything, and is accordingly pretty minor. This is why I branched off of `stable` in the first place -- sounds like my instincts were in the ballpark.

I also have some ideas for a separate script to test the feature -- I'll include that in the PR when I submit it.

**Comment by bskinn** [comment]
The behavior of the old-style `make.bat` (in `make.bat_t`) and new-style `make.bat` (in `make.bat.new_t`) were sufficiently different that I abandoned the attempt to make this work for the old-style batch file.

I figure most users are just going to run `sphinx-quickstart` with the default `make.bat` options anyways, yielding them the new version, so there's not a lot of value in making it work for both.

**Comment by AA-Turner** [comment]
Closing in favour of #5618.

A
