### ISSUE TITLE
The '-M' commandline option to sphinx-build is not documented.

### ISSUE THREAD

**Issue by bskinn** [sphinx-doc/sphinx#3751]
The `-M` commandline option to `sphinx-build`, discussed e.g. [here](https://github.com/sphinx-doc/sphinx/issues/3196#issuecomment-266178346) under #3196, is not documented on the [sphinx-build docs page](http://www.sphinx-doc.org/en/stable/man/sphinx-build.html#options).

Documentation of `-M` is also not present on the [`sphinx-quickstart` 'invocation' doc page](http://www.sphinx-doc.org/en/stable/invocation.html).

**Comment by bskinn** [comment]
@tk0miya I would add the docs entry myself, but I don't think I know enough about its under-the-hood behavior of the option to do a good job of it.

**Comment by tk0miya** [comment]
Thank you for post. I will take a look. (I also do not know about the option...)

**Comment by dasevilla** [comment]
Some additional resources to help with documenting this

- `make_mode.py` has the source code
- Initial commit message: https://github.com/sphinx-doc/sphinx/commit/91d92be8adae2e44e1e23e1c07b7088c35261abf

**Comment by berkerpeksag** [comment]
PR #3938 has been merged. This issue can be closed.

**Comment by tk0miya** [comment]
Right, thanks!
