### ISSUE TITLE
Generate different outputs from single source for different audiences

### ISSUE THREAD

**Issue by ArthurFlag** [sphinx-doc/sphinx#3752]
Hello all and thanks a lot for creating this excellent piece of software.

I'm trying to find information on Sphinx's ability to tag certain bits of documentation as targeted for specific audiences and later build the output for each of these audiences, filtering out the tags of my choices.

That would allow me to generate several versions of my docs while keeping it single-source.

Example:

```
.. audience::internal

Page title
============

This whole page will be available only in the internal docs.
```

and

```
Page title
============

This whole page will be available in the internal and external docs. 

.. audience::internal

That p will only be available in the internal docs.

This p will be available in the internal and external docs.

```

Once all my content is tagged with this audience directive, I could build whatever version by including or excluding certain tags from the command line:
`sphinx-build -include-audience internal -b sourcedir builddir`
or
`sphinx-build -exclude-audience internal -b sourcedir builddir`

I know about the `ifconfig` extension which seems to be a step in that direction but, if I understood it right, that would mean having to edit the `conf.py` file to choose which output I want to build before every build if I have more than 1 target audience. Is that correct?
This is why being able to pick the audiences from the command line would be great.

How difficult would it be to develop this feature?

Thank you!

**Comment by bskinn** [comment]
I think what you want is already implemented as the [`.. only::` directive.](http://www.sphinx-doc.org/en/stable/markup/misc.html#directive-only):

 > Include the content of the directive only if the *expression* is true. The expression should consist of tags, like this:
 >    ``` .. only:: html and draft```
 > Undefined tags are false, defined tags (via the `-t` command-line option or within `conf.py`, see [here](http://www.sphinx-doc.org/en/stable/config.html#conf-tags)) are true. Boolean expressions, also using parentheses (like `html and (latex or draft)`) are supported.
 > ...

**Comment by ArthurFlag** [comment]
Hi Brian, 

Thanks a lot I didn't see this option, this is perfect!

**Comment by tk0miya** [comment]
FYI: only directive has some troubles when it contains sections and reference targets (refs: #1488, #2143 and so on).
Please take care!

**Comment by ArthurFlag** [comment]
Thanks Takeshi, very good to know... and... also quite a pity that this issue seems complicated to fix. I guess a lot of us will have to learn how to live with this for a while.

**Comment by tk0miya** [comment]
From design of Sphinx, it is hard to fix behavior of only directive (IMO, it's impossible!).

But, for some case, the extension introduced at #2150 might help you. It also has restriction, but it behaves as you expected.
