### ISSUE TITLE
Feature Request: Fix any relative links on include

### ISSUE THREAD

**Issue by pri22296** [sphinx-doc/sphinx#3753]
### Problem
- Including README.rst in index breaks relative links. It would be nice if sphinx includes the documents    while handling any relative links.

### Environment info
- OS: <Win>
- Python version: 3.5
- Sphinx version: 1.5.5

**Comment by tk0miya** [comment]
Do you mean `include` directive? If true, its implementation is on docutils. Please ask to them.
http://docutils.sourceforge.net/docs/ref/rst/directives.html#including-an-external-document-fragment

Note: The behavior is defined as following.

>the file is parsed in the current document's context at the point of the directive.

**Comment by tk0miya** [comment]
I'm closing this now.
Feel free to reopen if you still have this problem.
Thanks,
