### ISSUE TITLE
1.6.1 incorrectly warns about dedent with literalinclude

### ISSUE THREAD

**Issue by dhermes** [sphinx-doc/sphinx#3755]
### Problem

Our [build][1] fails when [running][2] `sphinx-build` with the `-W` flag. An [example][3] would be

```
  .. literalinclude:: logging_snippets.py
     :start-after: [START client_create_default]
     :end-before: [END client_create_default]
     :dedent: 4
```

and viewing the [actually included][4] source, one can see that 4 space dedent is correct. (FWIW I tried 1-space dedent and it also failed.)

#### Procedure to reproduce the problem

```
sphinx-build -W -b html -d docs/_build/doctrees docs/ docs/_build/html/
```

#### Error logs / results

```
Warning, treated as error:
/var/code/gcp/docs/logging-usage.rst.rst:25:Over dedent has detected
```

- Public link: [build][1]

#### Expected results

The build should succeed.

### Reproducible project / your project

- Project: https://github.com/GoogleCloudPlatform/google-cloud-python (just run `nox -s docs` at the project root, though you may have to install `pip install nox-automation`)

### Environment info

- OS: Ubuntu (not sure which version our docker image uses)
- Python version: 3.6
- Sphinx version: 1.6.1

[1]: https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/1896
[2]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/b807a0047c4a9d6a6f2fb80b82d8b1bb8e6d48f4/test_utils/scripts/update_docs.sh#L27
[3]: https://raw.githubusercontent.com/GoogleCloudPlatform/google-cloud-python/b807a0047c4a9d6a6f2fb80b82d8b1bb8e6d48f4/docs/logging-usage.rst
[4]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/b807a0047c4a9d6a6f2fb80b82d8b1bb8e6d48f4/docs/logging_snippets.py#L50-L53

**Comment by tk0miya** [comment]
Thank you for reporting and sorry for inconvenience.
Fixed at dabd356.

**Comment by dhermes** [comment]
Thanks @tk0miya. Would you like me to install from `HEAD` to verify or to wait until a release?

**Comment by tk0miya** [comment]
I confirmed it works well at local. But it would be nice if you also confirm this.
Anyway, we will release next bug-fixed version soon. So it's okay to wait it.

**Comment by dhermes** [comment]
Just confirmed via:

```
pip install git+https://github.com/sphinx-doc/sphinx/
```

See [build][1].

[1]: https://circleci.com/gh/GoogleCloudPlatform/google-cloud-python/1962
