### ISSUE TITLE
Epub error,  Entity 'mdash' not defined

### ISSUE THREAD

**Issue by pashango2** [sphinx-doc/sphinx#3756]
### Problem
When reST below code is built with Epub, `conf.py` does not write epub setting at all.

```
.. epigraph::
     ”Don't think. Feel!”

    -- Movie ”Fist of Fury”
```

#### Error logs / results
an error appears at the top of the page.
```
This page contains the following errors:

error on line 93 at column 31: Entity 'mdash' not defined
Below is a rendering of the page up to the first error.
```
xhtml code.
```
<div>”Don’t think. Feel!”</div></blockquote>
<p class="attribution">&mdash;Movie ”Fist of Fury”</p>
```

### Environment info
- OS: Linux
- Python version: 3.6
- Sphinx version: 1.6.1

**Comment by tk0miya** [comment]
Thank you for reporting.
Fixed at 9795dca.
