### ISSUE TITLE
PyTango installation

### ISSUE THREAD

**Issue by ghost** [sphinx-doc/sphinx#3757]
### Problem
Hi all. I want to install PyTango 9.2.1 using source code. But when I run installation script, I get error in terminal.

#### Procedure to reproduce the problem
This is bash script I'm using to install PyTango:
```
#!/bin/bash

sudo apt install libboost1.58-dev libboost-python1.58-dev

sudo -H pip install setuptools
sudo -H pip install python_dateutil pytz cycler pyparsing Sphinx futures gevent numpy mock

sudo apt-get install libzmq3-dev libzmqpp3 libzmqpp-dev 
sudo apt-get install libomniorb4-1 libomnithread3c2 python-omniorb-omg python-omniorb 
sudo apt-get install libomnithread3-dev libssl-dev libssl-doc libomniorb4-dev

sudo -HE pip install pytango fandango
```

#### Error logs / results
After some time of compiling PyTango, this is what is showed in terminal:
```
  running build_doc
  creating /tmp/pip-build-teAosy/pytango/build/sphinx
  creating /tmp/pip-build-teAosy/pytango/build/sphinx/doctrees
  creating /tmp/pip-build-teAosy/pytango/build/sphinx/html

 Running Sphinx v1.6.1
    Mocking tango._tango extension module
    
    Exception occurred:
      File "/tmp/pip-build-1a5VE3/PyTango/build/lib.linux-x86_64-2.7/tango/__init__.py", line 123, in <module>
        from . import _tango
    ImportError: cannot import name _tango
    The full traceback has been saved in /tmp/sphinx-err-qgXabO.log, if you want to report the issue to the developers.
    Please also report this if it was a user error, so that a better error message can be provided next time.
    A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```   
In the file located  at /tmp/sphinx-err-qgXabO.log this is what I have
```

# Sphinx version: 1.6.1
# Python version: 2.7.12 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.9.6
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/setup_command.py", line 191, in run
    warningiserror=self.warning_is_error)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/application.py", line 167, in __init__
    confoverrides or {}, self.tags)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/config.py", line 150, in __init__
    execfile_(filename, config)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 699, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "conf.py", line 27, in <module>
    from mock_tango_extension import tango
  File "mock_tango_extension.py", line 121, in <module>
    import tango
  File "/tmp/pip-build-1a5VE3/PyTango/build/lib.linux-x86_64-2.7/tango/__init__.py", line 123, in <module>
    from . import _tango
ImportError: cannot import name _tango
```   

#### Environment info
- OS: Ubuntu 16.04 LTS
- Python version: Python 2.7.12
- Sphinx version: Sphinx 2.2.9-id64-release (this is what I get with command searchd -help), but as you can see, in error log file it says that I'm using 1.6.1 version. 
- Tango: 9.2.5a

**Comment by ghost** [comment]
P.S. For installing PyTango for python3, I didn't have this kind of error.
I found this link http://programtalk.com/vs2/python/12719/pytango/doc/mock_tango_extension.py/ where it is said " Patching tango._tango using sys.modules does not seem to work for python
version older than 3.5 (failed with 2.7 and 3.4)". Is it possible to overcome this problem so I could install PyTango for python 2.7 also?

**Comment by tk0miya** [comment]
Sorry, this is issues for Sphinx. so we can't support tango package.
Could you ask it on thier project?

**Comment by rile993** [comment]
Ok, sorry,  I post it here because there was this line said next:

>A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!

Anyway, thank you for response. :)

**Comment by ghost** [comment]
Ok, sorry,  I post it here because there was this line:

>A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!

Anyway, thank you for response. :)

**Comment by tk0miya** [comment]
You're welcome :-)
