### ISSUE TITLE
Option to Getting DocString as JSON

### ISSUE THREAD

**Issue by Bernardrouhi** [sphinx-doc/sphinx#3762]
Subject: Option to Getting DocString as JSON

### Enhancement
Why doesn't `body` block return **DocString** as **JSON** format instead of **HTML**?

I want to develop a customised template, and `body` block provides DocString in HTML format, but it's way much easier to work with JSON data since many DataView accepts JSON data and more flexible to customise the HTML layout as well.

**Comment by tk0miya** [comment]
In sphinx, the builder module is used to build HTML, not HTML templates.
So please write your builder extension to do that. Then, you can handle raw document as doctree.

Thanks,
