### ISSUE TITLE
AttributeDocumenter.method_types removed without deprecation

### ISSUE THREAD

**Issue by bsipocz** [sphinx-doc/sphinx#3771]
Using the latest 1.6.1 sphinx release, we've into issues when using our ``sphinx-automodapi`` package (or it's precursor files in ``astropy-helpers``).

```
Exception occurred:
  File "/Users/bsipocz/munka/devel/sphinx-automodapi/sphinx_automodapi/autodoc_enhancements.py", line 78, in can_document_member
    non_attr_types = cls.method_types + class_types + \
AttributeError: type object 'AttributeDocumenter' has no attribute 'method_types'
The full traceback has been saved in /var/folders/dc/hsm7tqpx2d57n7vb3k1l81xw0000gq/T/sphinx-err-g0jqhl13.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

The removal of method_types were done in 
https://github.com/sphinx-doc/sphinx/commit/3e2255cd64d96adbd53b3bd58d14019c6a2da0df
 part of https://github.com/sphinx-doc/sphinx/pull/3644

**Comment by bsipocz** [comment]
Given that the code part that runs into this issue is there to provide a workaround for https://github.com/sphinx-doc/sphinx/pull/1843, my easy fix is to check the sphinx version number and have that part run only for <1.5

**Comment by swapsha96** [comment]
@bsipocz I am facing it right now. How to check Sphinx version?

**Comment by bsipocz** [comment]
we usually use LooseVersion for comparison, e.g.:
https://github.com/astropy/sphinx-automodapi/blob/master/sphinx_automodapi/autodoc_enhancements.py#L19
