### ISSUE TITLE
Literalinclude adds empty lines

### ISSUE THREAD

**Issue by szabolcsdombi** [sphinx-doc/sphinx#3776]
Subject: `.. iteralinclude::` adds empty lines

### Problem
- I get a random number of empty lines on the end of the file included

Files:

- The [.rst file](https://raw.githubusercontent.com/cprogrammer1994/ModernGL/master/docs/Examples/01_hello_world.rst)
- The [result](https://moderngl.github.io/Examples/01_hello_world.html)
- The [included file](https://github.com/cprogrammer1994/ModernGL/blob/master/examples/GLWindow/01_hello_world.py)

#### Procedure to reproduce the problem
```
python setup.py build_sphinx
```

#### Error logs / results
```
I get no errors or warnings
```
- public link of unexpected result if you have: The [result](https://moderngl.github.io/Examples/01_hello_world.html)

#### Expected results
I want no extra lines to be added randomly.

### Reproducible project / your project

Requirements for `build_sphinx`:

```
Sphinx
sphinx-rtd-theme
sphinxcontrib-napoleon
```

- [ModernGL](https://github.com/cprogrammer1994/ModernGL)
- Run `python setup.py build_sphinx`

### Environment info
- OS: Windows 10
- Python version: 3.6.1
- Sphinx version: 1.5.5

**Comment by jfbu** [comment]
It is not that empty lines are added, but the line spacing is shorter for the code itself compared to the code numbering. I tried a minimal project using the files you provided and using 

    extensions = [
        'sphinx.ext.autodoc',
        'sphinx.ext.napoleon'
    ]

    html_theme = 'sphinx_rtd_theme'

in conf.py. 

![capture d ecran 2017-05-20 a 16 57 08](https://cloud.githubusercontent.com/assets/2589111/26276784/88d9af8a-3d7e-11e7-845d-15fcde1d211a.png)

Tested with Sphinx 1.5.1 and with Sphinx 1.6.1.

Is there anything modifying your CSS ?

**Comment by szabolcsdombi** [comment]
I had a css but I removed it.

I just created a small [repo](https://github.com/cprogrammer1994/sphinx-literalinclude) with the necessary files.

I updated my sphinx to 1.6.1 but the problem persists.

I also tried with a fresh new python install:

```
T:\test-python\python.exe -m pip install sphinx sphinx-rtd-theme sphinxcontrib-napoleon
T:\test-python\python.exe -m sphinx docs build\sphinx
```

same problem.

**Comment by szabolcsdombi** [comment]
I also tried `CRLF` and `LF` line endings on the `01_hello_world.py` but no use.

**Comment by szabolcsdombi** [comment]
No extra lines were added. Those were just shifted down due to a bug in `sphinx_rtd_theme`. ( [issue](https://github.com/rtfd/sphinx_rtd_theme/issues/417) )

Closing the issue, thank you.

**Comment by jfbu** [comment]
ah ok I probably wasn't using the version of ``sphinx_rtd_theme`` which is displaying the issue. Good that you figured it out at https://github.com/rtfd/sphinx_rtd_theme/issues/417
