### ISSUE TITLE
 Multiple lines in bullet list are not applied

### ISSUE THREAD

**Issue by pashango2** [sphinx-doc/sphinx#3778]
### Problem
The bullet list is not correctly converted to HTML when converting the following rest code to HTML.

```
* This is a bulleted list.
* It has two items, the second
  item uses two lines.
```
output HTML.
```
<ul class="simple">
<li>This is a bulleted list.</li>
<li>It has two items, the second
item uses two lines.</li>
</ul>
```

Expected HTML output.
```
<ul class="simple">
<li>This is a bulleted list.</li>
<li>It has two items, the second<br/>
item uses two lines.</li>
</ul>
```

### Environment info
- OS: OpenSUSE
- Python version: 3.6
- Sphinx version: 1.6.1 & 1.5.3

**Comment by jfbu** [comment]
This is the expected output. (some people hardwrap their sources, other don't, imagine if line breaks in output were decided by line breaks in input).

Perhaps this is what you need:

```
* This is a bulleted list.
* | It has two items, the second
  | item uses two lines.

```

It produces

```
<ul>
<li><p class="first">This is a bulleted list.</p>
</li>
<li><div class="first line-block">
<div class="line">It has two items, the second</div>
<div class="line">item uses two lines.</div>
</div>
</li>
</ul>
```

**Comment by pashango2** [comment]
I appreciate the reply.
Everything went well.Thank you
