### ISSUE TITLE
encounter ''NoneType' object is not iterable' 

### ISSUE THREAD

**Issue by jichenjc** [sphinx-doc/sphinx#3782]
https://review.openstack.org/#/c/463446/3
had this issue, master branch didn't have issue while I did not change too much stuff in this patch, might be related to some recent sphinx changes ?

 File "/home/jichen/stack-forge-nova-zvm/nova-zvm-virt-driver/.tox/docs/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", li    ne 440, in _write_serial
 34     self.write_doc(docname, doctree)
 35   File "/home/jichen/stack-forge-nova-zvm/nova-zvm-virt-driver/.tox/docs/local/lib/python2.7/site-packages/sphinx/builders/html.py", line 5    56, in write_doc
 36     self.handle_page(docname, ctx, event_arg=doctree)
 37   File "/home/jichen/stack-forge-nova-zvm/nova-zvm-virt-driver/.tox/docs/local/lib/python2.7/site-packages/sphinx/builders/html.py", line 9    40, in handle_page
 38     output = self.templates.render(templatename, ctx)
 39   File "/home/jichen/stack-forge-nova-zvm/nova-zvm-virt-driver/.tox/docs/local/lib/python2.7/site-packages/sphinx/jinja2glue.py", line 176,     in render
 40     return self.environment.get_template(template).render(context)
 41   File "/home/jichen/stack-forge-nova-zvm/nova-zvm-virt-driver/.tox/docs/local/lib/python2.7/site-packages/jinja2/environment.py", line 100    8, in render
 42     return self.environment.handle_exception(exc_info, True)
 43   File "/home/jichen/stack-forge-nova-zvm/nova-zvm-virt-driver/.tox/docs/local/lib/python2.7/site-packages/jinja2/environment.py", line 780    , in handle_exception
 44     reraise(exc_type, exc_value, tb)
 45   File "/home/jichen/stack-forge-nova-zvm/nova-zvm-virt-driver/.tox/docs/local/lib/python2.7/site-packages/sphinx/themes/basic/page.html",     line 10, in top-level template code
 46     {%- extends "layout.html" %}
 47   File "/home/jichen/stack-forge-nova-zvm/nova-zvm-virt-driver/.tox/docs/local/lib/python2.7/site-packages/oslosphinx/theme/openstack/layou    t.html", line 2, in top-level template code
 48     {% set css_files = css_files + ['_static/tweaks.css'] %}
 49   File "/home/jichen/stack-forge-nova-zvm/nova-zvm-virt-driver/.tox/docs/local/lib/python2.7/site-packages/sphinx/themes/basic/../basic/lay    out.html", line 128, in top-level template code
 50     {%- block csss %}
 51   File "/home/jichen/stack-forge-nova-zvm/nova-zvm-virt-driver/.tox/docs/local/lib/python2.7/site-packages/sphinx/themes/basic/../basic/lay    out.html", line 129, in block "csss"
 52     {{ css() }}
 53   File "/home/jichen/stack-forge-nova-zvm/nova-zvm-virt-driver/.tox/docs/local/lib/python2.7/site-packages/jinja2/sandbox.py", line 427, in     call
 54     return __context.call(__obj, *args, **kwargs)
 55   File "/home/jichen/stack-forge-nova-zvm/nova-zvm-virt-driver/.tox/docs/local/lib/python2.7/site-packages/jinja2/runtime.py", line 553, in     _invoke
 56     rv = self._func(*arguments)
 57   File "/home/jichen/stack-forge-nova-zvm/nova-zvm-virt-driver/.tox/docs/local/lib/python2.7/site-packages/sphinx/themes/basic/../basic/lay    out.html", line 108, in template
 58     {%- for css in css_files %}

**Comment by tk0miya** [comment]
Sorry for inconvenience.
That was already fixed at #3754.

**Comment by jichenjc** [comment]
thanks a lot for your help~
