### ISSUE TITLE
Ability to suppress warning "Title underline too short"

### ISSUE THREAD

**Issue by andy-maier** [sphinx-doc/sphinx#3797]
Subject: Would like to have the ability to suppress the warning "Title underline too short".

### Problem

In an internal project, we are generating .rst files that are then processed using Sphinx. The titles in the .rst files are dynamically generated, but we are not generating the "===" section underliner in the same length, but instead have it with a fixed length.

That obviously causes these warnings.

I did notice that the "===" underliner can be longer than the title, but our titles can be fairly long.

Also, I do understand that we could generate the underliner dynamically with the correct length, but that would require changes to the generator tool, and that is not under our control.

#### Procedure to reproduce the problem

Some title line with an underliner that is shorter than the title text.

#### Error logs / results

WARNING: Title underline too short.

#### Expected results

I read about the "suppress_warnings" config option and suggest that a value gets added that allows suppressing the "Title underline too short" warning.

### Reproducible project / your project

N/A

### Environment info
- OS: RHEL 7.3 on x86-64
- Python version: 2.7.5
- Sphinx version: 1.5.3

**Comment by tk0miya** [comment]
The warning is emitted by docutils. So we can't suppress it. Please request it to the project.
thanks,
