### ISSUE TITLE
gettext: Support ngettext

### ISSUE THREAD

**Issue by pyhedgehog** [sphinx-doc/sphinx#3799]
At least in [sphinx/application.py#334](https://github.com/sphinx-doc/sphinx/blob/78a20617b52e02e422d78a22cc3dc98e4b417f1b/sphinx/application.py#L334).

**Comment by TimKam** [comment]
Since #3833 is closed, [sphinx/application.py#334](https://github.com/sphinx-doc/sphinx/blob/78a20617b52e02e422d78a22cc3dc98e4b417f1b/sphinx/application.py#L334) doesn't actually use any gettext functionality. But I can add a PR to support `ngettext`, anyway.
