### ISSUE TITLE
error after latest update to requests 2.16.0

### ISSUE THREAD

**Issue by pri22296** [sphinx-doc/sphinx#3810]
Subject: Exception occurs after latest update to requests 2.16.0

#### Error logs / results
```
Exception occurred:
  File "/home/travis/build/pri22296/yaydoc/yaydocvenv/local/lib/python2.7/site-packages/sphinx/util/requests.py", line 51, in <module>
    requests.packages.urllib3.disable_warnings(
AttributeError: 'module' object has no attribute 'packages'
```
This error does not happen with requests 2.15.1

### Environment info
- OS: Ubuntu 12.04.5 LTS (on travis CI with language as php)
- Python version: 2.7
- Sphinx version: Tested on 1.5.5 and 1.6.1

**Comment by BiranLi** [comment]
I have got same problem in Ubuntu 12.04. I installed the sphinx with pip-9.0.1.

**Comment by pri22296** [comment]
This should be fixed in the next release of **requests** as per kennethreitz/requests#4073

**Comment by tk0miya** [comment]
@pri22296 Thanks! Certainly requests-2.16.1 goes well :-)

It seems there are nothing to do from sphinx side.
Thanks,
