### ISSUE TITLE
Add Algolia search Plugin

### ISSUE THREAD

**Issue by benjaminweb** [sphinx-doc/sphinx#3812]
### Problem
The search is not as responsive as it could be.

#### Expected results
Instant results while typing like https://middlemanapp.com/basics/install/ using [Algolia](https://www.algolia.com).

Python reference implementation: https://github.com/sherbondy/lektor-algolia

**Comment by tk0miya** [comment]
Does it work on only browsers?
Sphinx expects search engines which works on only browsers.

**Comment by benjaminweb** [comment]
Yes, the search only works on the browser:

https://github.com/algolia/docsearch#setup

Injection of API key could be configured via ``conf.py`` IMHO.

[docsearch-scraper](https://github.com/algolia/) is a Python script indexing the generated html
and pushing the index to Algolia's servers.

Would you mind giving me an example of a [hook point](http://www.sphinx-doc.org/en/stable/extdev/index.html?highlight=hook), please?

Would such a thing be the place to trigger docsearch-scraper, so when html has been compiled afresh? When is that the case (in terms of specific code location)?

**Comment by zhex900** [comment]
Is anyone using algoila search with sphinx-doc? I want to know whether it is possible to use algoila search on sphinx-doc.

**Comment by tk0miya** [comment]
Oh, sorry. I did not notice the @benjaminweb 's message.

>Would you mind giving me an example of a hook point, please?

I don't know. The document says application class has `add_search_language()` to add new language for internal searching feature.
http://www.sphinx-doc.org/en/stable/extdev/appapi.html#sphinx.application.Sphinx.add_search_language

But it seems there are no way to add switch search engine to others.

So we need to add new API for indexing.


@zhex900 Sphinx package itself does not support it. And there are no extensions AFAIK.

**Comment by boy-vd** [comment]
Don't know if this is helpful, but the following configuration works well for a Sphinx 1.8.5 environment with `sphinx_rtd_theme` version 0.4.3. Very easy to implement:

```
# -- Options for HTML output ----------------------------------------------

# Load custom stylesheets to support Algolia search.
html_css_files = [
  'algolia.css',
  'https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css'
]

# Load custom javascript to support Algolia search. Note that the sequence
# defined below (external first) is intentional!
html_js_files = [
  ('https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js', {'defer': 'defer'}),
  ('algolia.js', {'defer': 'defer'})
]

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']
```

The `algolia.css` file in the `_static` directory contains the following:

```
.wy-nav-side { overflow: visible; }
.wy-side-scroll { overflow: inherit; }
```

And the `algolia.js` file in the same `_static` directory contains this:

```
docsearch({
  apiKey: '<API_KEY>',
  indexName: '<INDEX_NAME>',
  // Replace inputSelector with a CSS selector
  // matching your search input
  inputSelector: '#rtd-search-form input[type=text]',
  // Set debug to true if you want to inspect the dropdown
  debug: false,
  algoliaOptions: {
    hitsPerPage: 8,
  }
});
```

This setup makes use of the public crawler that Algolia hosts for free on their servers: https://community.algolia.com/docsearch/dropdown.html. Implementing it based on a crawler that you build yourself shouldn't be much different: https://community.algolia.com/docsearch/run-your-own.html.

PS: I also posted this info on the GitHub repo for `sphinx_rtd_theme`: https://github.com/rtfd/sphinx_rtd_theme/issues/761.

**Comment by tk0miya** [comment]
That sounds good. It means no new APIs are not needed for algolia search. It would be better if somebody packages it as an extension :-)
IMO, there are no tasks for sphinx-core. So I'm closing this now.
