### ISSUE TITLE
sphinx-build fails with docutils 0.14rc1

### ISSUE THREAD

**Issue by jayvdb** [sphinx-doc/sphinx#3814]
Subject: sphinx-build fails with docutils 0.14rc1

### Problem
https://pypi.python.org/pypi/docutils/0.14rc1 has been released.
See https://github.com/coala/coala/issues/4280

#### Procedure to reproduce the problem
```
<Paste your command-line here which cause the problem>
```

#### Error logs / results
```
<Paste your error log here>
```
- <public link of unexpected result if you have>

#### Expected results
<Describe what to actually do>

### Reproducible project / your project
- <link to your project, or attach zipped small project sample>

### Environment info
- OS: <Unix/Linux/Mac/Win/other with version>
- Python version:
- Sphinx version:
- <Extra tools e.g.: Browser, tex or something else>

**Comment by tk0miya** [comment]
Thank you for reporting. I just fixed it at #3809!

**Comment by jayvdb** [comment]
Hey @tk0miya, this breaks all versions of sphinx in production when docutils is updated as pip & setuptools automatically upgrades to 0.14rc1 (i.e. they havent marked it as a pre-release).

**Comment by tk0miya** [comment]
Thanks, I will release bug fix release soon. Please wait a moment
