### ISSUE TITLE
Error report on bibtex error.

### ISSUE THREAD

**Issue by fschaef** [sphinx-doc/sphinx#3815]
Subject: Quex Documentation -- using bibtex for citations

### Problem
- Using sphinx to generate documentation with a syntax error in the underlying '.bib' file (missing '}')

#### Procedure to reproduce the problem

(1) generate a citations.bib file such as
 
   @book{schafer2004generalized,
        title={Generalized feedback control and application to vehicle path following control},
       author={Sch{\"a}fer, Frank Ren{\'e}},
       year={2004}
    %% note the missing '}'

(2) Use bibtex in the "conf.py"
    projectextensions = ['sphinxcontrib.bibtex'] # INSTALL: "sudo pip install sphinxcontrib-bibtex"

(3) Run 'make html'

#### Error logs / results
parsing bibtex file /home/fschaef/prj/quex/trunk/doc/source/citations.bib... 
Exception occurred:
  File "/usr/local/lib/python2.7/dist-packages/pybtex/errors.py", line 77, in report_error
    raise exception
TokenRequired: '}' expected

#### Expected results
<Describe what to actually do>

### Reproducible project / your project
- <link to your project, or attach zipped small project sample>

### Environment info
- OS: <Unix/Linux/Mac/Win/other with version>
- Python version: 2.7 / 3.5
- Sphinx version: Sphinx (sphinx-build) 1.5.5

- <Extra tools e.g.: Browser, tex or something else>
bibtext, see above

**Comment by tk0miya** [comment]
This might be a bug of `sphinxcontrib-bibtex`, not Sphinx-core.
Please let them know this.
Thanks,

**Comment by tk0miya** [comment]
I'm closing this because this is a bug of bibtex extension.
