### ISSUE TITLE
failed to install due to docutils latest version contains string

### ISSUE THREAD

**Issue by kfirilani** [sphinx-doc/sphinx#3821]
while trying to upgrade sphinx, it tries to update docutils.
docutils latest package version is 0.14rc1
while parsing the version, it fails due to parse error for int()

File "/Users/ci/workspace/wrk_automation_utils_mac_debug/.eggs/Sphinx-1.3.1-py2.7.egg/sphinx/util/compat.py", line 17, in 
docutils_version = tuple(int(x) for x in _du_version.split('.')[:2])
ValueError: invalid literal for int() with base 10: '14rc1'

Can you fix that it wont fail in case of dependency version parsing error?

**Comment by tk0miya** [comment]
Same as #3814. It is fixed newest release: 1.6.2.
Please upgrade to newest one.

Thanks,

**Comment by jfbu** [comment]
@tk0miya unfortunately this is not duplicate but other one at sphinx.util.compat

**Comment by tk0miya** [comment]
oh, sorry. reopened.

**Comment by tk0miya** [comment]
I will take a look tomorrow (in Japan, it's night 🌃  now)

**Comment by jfbu** [comment]
it was a hectic and very productive day thanks to you...

unfortunately we overlooked this one in time for 1.6.2, sorry because I should have looked more systematically  at the time of my [initial report](https://github.com/sphinx-doc/sphinx/issues/3788#issuecomment-303678523) for other such situations in Sphinx code base relative to Docutils version string

**Comment by jfbu** [comment]
@kfirilani actually I was too pessimistic. The `sphinx.util.compat` module is not imported by core Sphinx anywhere anymore afaict. It may be imported by extensions. Can you try upgrading to Sphinx 1.6.2 ?

**Comment by tk0miya** [comment]
Good morning, all.
I checked with 1.6.2, and it did not reproduced.

>The sphinx.util.compat module is not imported by core Sphinx anywhere anymore afaict.

Yes, the module is deprecated now. So it does not prevent the behavior of sphinx-core.

**Comment by tk0miya** [comment]
About `sphinx.util.compat`, fixed at ff1adc7.
