### ISSUE TITLE
unchanged_required option spec is ignored: missing unchanged_required options don't raise an error

### ISSUE THREAD

**Issue by cpitclaudel** [sphinx-doc/sphinx#3831]
### Problem

Sphinx doesn't seem to honor the `unchanged_required` option spec. Omitting an option marked as unchanged_required does not to raise an error.

#### Procedure to reproduce the problem

Simple procedure: run sphinx-quickstart, then remove the `:caption:` argument of the `toctree` directive. This should raise an error, since the definition of TocTree uses this:

```
    option_spec = {
        'maxdepth': int,
        'name': directives.unchanged,
        'caption': directives.unchanged_required,
```

But in fact it doesn't.

#### Expected results
Sphinx should complain about missing options when they are declared as unchanged_required and missing in the rst document.

### Reproducible project / your project

Run sphinx-quickstart, then in conf.py uncomment the `sys.path.insert` part and add `'ext'` as an extension.  In `ext.py` add this:

```
from docutils.parsers.rst import Directive, directives

class MustHaveAName(Directive):
    has_content = False
    required_arguments = 0
    optional_arguments = 0
    final_argument_whitespace = False
    option_spec = { 'name': directives.unchanged_required }

    def run(self):
        return []

def setup(app):
    app.add_directive('must-have-a-name', MustHaveAName)
```

Then in index.rst use this:

```
.. must-have-a-name::
```

Finally, run `make html`. Sohinx doesn't report errors.

### Environment info

```
$ python --version
Python 2.7.12
$ python3 --version
Python 3.5.2
$ sphinx-build --version
Sphinx (sphinx-build) 1.5a1
$ uname -a
Linux clem 4.4.0-78-generic #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by tk0miya** [comment]
Hmm? did you mean that docutils warns it, but sphinx does not?
AFAIK `changed_required` does not mean "required option". It only means the option take a required argument.

**Comment by cpitclaudel** [comment]
Ouch, sorry. Looks like I misread this line of the docs:

```
unchanged_required: Returns the text argument, unchanged. Raises ValueError if no argument is found.
```

as meaning "if the option isn't found", rather than the argument.

**Comment by tk0miya** [comment]
:-)
