### ISSUE TITLE
Language of diagnostics should not change

### ISSUE THREAD

**Issue by jdemeyer** [sphinx-doc/sphinx#3833]
Subject: when compiling a Japanese document, the diagnostic messages from the Sphinx build system are also translated in Japanese:
```
loading translations [ja]... 完了
WARNING: 拡張 ['?', 'sphinx.ext.graphviz'] のセットアップ中: nodeクラス 'graphviz' は既に登録されています。visitor関数は上書きされます
WARNING: 拡張 ['?', 'sphinx.ext.inheritance_diagram'] のセットアップ中: nodeクラス 'inheritance_diagram' は既に登録されています。visitor関数は上書きされます
WARNING: 拡張 ['?', 'sphinx.ext.todo'] のセットアップ中: nodeクラス 'todolist' は既に登録されています。visitor関数は上書きされます
WARNING: 拡張 ['?', 'sphinx.ext.todo'] のセットアップ中: nodeクラス 'todo_node' は既に登録されています。visitor関数は上書きされます
WARNING: 拡張 ['?', 'sphinx.ext.mathjax'] のセットアップ中: nodeクラス 'displaymath' は既に登録されています。visitor関数は上書きされます
WARNING: 拡張 ['?', 'sphinx.ext.mathjax'] のセットアップ中: nodeクラス 'eqref' は既に登録されています。visitor関数は上書きされます
```

### Problem
This is breaking the continuous integration system of Sage because we check for certain messages (not) appearing in the Sphinx build log (more detail: we want to build the documentation without warnings, but we need to white-list certain warnings like the one above).

The locale for the build system (messages shown on the console) and the locale for the output document (HTML/PDF files generated by Sphinx) should be independent. Just because I'm compiling Japanese documentation doesn't mean that I want the diagnostics from the Sphinx build system in Japanese.

This problem appeared when upgrading from Sphinx-1.5.3 to Sphinx-1.6.1

#### Procedure to reproduce the problem
Checkout https://trac.sagemath.org/ticket/23023 and build the Sage documentation.

### Environment info
- OS: Linux
- Python version: 2.7.13
- Sphinx version: 1.6.1

**Comment by tk0miya** [comment]
Now #3889 is merged!
