### ISSUE TITLE
upload_docs throws AttributeError with Sphinx 1.6

### ISSUE THREAD

**Issue by eli-collins** [sphinx-doc/sphinx#3837]
Under Sphinx 1.6, running `python setup.py build_sphinx upload_docs` causes setuptools to throw `AttributeError: builder_target_dir` around [line 65 of upload_docs.py](https://github.com/pypa/setuptools/blob/master/setuptools/command/upload_docs.py#L65).   *(Tested with python 3.5.2, setuptools 35.0.2, sphinx 1.6.2)*

This appears to be caused by Sphinx 1.6's adding support for multiple builders into `build_sphinx`, which caused `build_sphinx.builder_target_dir` to be renamed to `build_sphinx.builder_target_dirs` (plural).  

I previously filed this as setuptools [issue #1041](https://github.com/pypa/setuptools/issues/1041), but wasn't entirely positive which side of the interface needed fixing.  They indicated this was probably something that needed fixing on the Sphinx side.   

My initial idea would be adding a `.builder_target_dir` compatibility attr to help out setuptools; which reports the first builder's target dir (or even prioritizes the html builder's target dir).

Let me know if there's anything I can do to help.

**Comment by tk0miya** [comment]
As a quick look, the upload_docs command seems deprecated.
So I feel strange to restore old variable (singular one) to support it.

**Comment by eli-collins** [comment]
It's still quite widely used for non-pypi indices, such as testing with devpi.   

Also, jaraco [stated](https://github.com/pypa/setuptools/issues/1041#issuecomment-305039113) in the linked setuptools issue that they plan to remove the general deprecation from that command.

**Comment by tk0miya** [comment]
I understand. but the `builder_target_dir` is an internal variable for us. It's not a public interface. so I feel strange the 3rd party library accesses it and prevents to refactor our code. I don't opposite strongly to add it again. But I can't understand why don't they change setuptools.

**Comment by eli-collins** [comment]
I definitely understand the frustration at finding a third party's using something you thought was an internal attribute.  Refactoring under those conditions always leaves me with a frustrated "I was working here!" kind of feeling.  

Annoyingly there seems to be a long history of that kinda of behavior all over distutils.  Since it's composed of legacy code upon hack upon legacy code, I've gotten the feeling that any build command attributes not prefixed with "_" end up being fair game for external connections.  Particularly because distutils has no clear/clean API for how pass state between chained commands. 

If it would be acceptable to add it back as a legacy proxy attribute, I can give a shot at a PR. 

Alternately I could try and convince setuptools to reopen their issue.  But I can see their position: upload_docs is there to upload *one* docs bundle, so it's expectation is the command it's pulling output from will offer a single path.  Whereas if support for `.builder_target_dirs` is implemented on the upload_docs side, it has to reach in and read *more* metadata, in order to locate the html builder among the list of builders, figure out which output dir it's using, etc.   All things which could be encapsulated and kept as internals if implemented in `build_docs`.

So while I understand not wanting to letting that attribute be semi-public; I think fixing the issue on setuptools' side will just cause it to rely on even *more* of sphinx's internals.

**Comment by letmaik** [comment]
This broke my build as well. Solution for me is to go back to sphinx 1.5 until this is fixed :/

**Comment by tk0miya** [comment]
>If it would be acceptable to add it back as a legacy proxy attribute, I can give a shot at a PR.

Thanks, PRs are always welcome. I don't opposite to add it back as a *public interface*.

To do that, we have to know what setuptools expected for `builder_target_dir`.
In 1.5, it was used to point a location of build directory. It does not mean "HTML" build directory. Users can change the builder type using `builder` option (`-b`). So sometimes it points "LaTeX" build directory.

In 1.6, users can specify multiple builders for build target like `builder = man,texinfo,html`. so `build_target_dir` would change on each building process.

I guess `upload_docs` command expects to build HTML docs, and to obtain the its output path. I don't think adding `build_target_dir` does not help it perfectly. It might work in almost case, but sometimes not.  So we need to discuss about the better interface.

**Comment by eli-collins** [comment]
The "[always html] might work, but sometimes not" issue is a fair point.   

After thinking about it a bit, I've got an idea how to fix this on setuptools end instead, but want to make sure it passes muster here before proposing it back on [setuptools issue #1041](https://github.com/pypa/setuptools/issues/1041)...

I could submit a setuptools PR that adds an option to upload_docs to choose *which* builder target it should choose for uploading (defaulting to "html" for backward compat).  It would then need to access `build_sphinx.builder_target_dirs`, if that's acceptable to be used as a (semi-)public attribute. 

They may push back on allowing non-html uploads, but I think that's a reasonable thing for upload_docs to support ... it seems to me it's up to the receiving server to decide if it wants to accept a particular zip upload, and there's no html-specific code in upload_docs that I can see.

Let me know if that sounds good on this project's side, and I'll propose it back over there.

---

Edit - Alternately, upload_docs could be coded to pick the "first" builder by default, but it looks like builder_target_dirs isn't ordered. 

Or it could default to using the solitary builder output if there's only one, and require an explicit selection otherwise.   

Maybe one of those would be better choices?

---

Edit 2 - After some testing myself, I think the last option probably offers the fewest chances of breaking existing deploys.  Having it default to "use the solitary builder, or require an explicit choice for multiple builders", would allow cases like `python setup.py build_sphinx -b latex upload_docs -r <index alias>` would work unchanged.  

I have a setuptools PR ready to go, if that plan sounds good, and `build_sphinx.builder_target_dirs` is ok to use as a public attribute.

**Comment by hoefling** [comment]
More than one year passed, ``setuptools`` reached version 40 and ``upload_docs`` is still around, being incompatible with ``Sphinx`` newer than 1.6. Here's the workaround I use in the meantime, maybe it will be helpful for someone. In your `setup.py`:

```python
import os
from setuptools import setup

# workaround for https://github.com/sphinx-doc/sphinx/issues/3837
from sphinx.setup_command import BuildDoc

fin_orig = BuildDoc.finalize_options
def finalize_options(self):
    fin_orig(self)
    self.builder_target_dir = next(
        (target_dir for (builder, target_dir) in self.builder_target_dirs if builder == 'html'),
        os.path.join(self.get_finalized_command('build').build_base, 'docs')
    )

BuildDoc.finalize_options = finalize_options
# end workaround

setup(...)
```

**Comment by AA-Turner** [comment]
The setuptools integration is deprecated and will be removed.

A
