### ISSUE TITLE
epub check validation error at dc:identifier

### ISSUE THREAD

**Issue by shibukawa** [sphinx-doc/sphinx#3840]
Subject: epub check validation error at dc:identifier

#### Procedure to reproduce the problem

https://groups.google.com/forum/#!topic/sphinx-users/WEpSezgn2cA

#### Expected Result

if the identifier is URL, use "website", otherwise, "pub-id".

**Comment by tk0miya** [comment]
ping @shibukawa 
Can you fix this until the next release (see #3888)?
If it is hard, please postpone this to 1.6.4.
