### ISSUE TITLE
Path to images broken using singlehtml builder when master doc is not in source root

### ISSUE THREAD

**Issue by MattWherry** [sphinx-doc/sphinx#3842]
Subject: Building docs with images in has incorrect relative path to images in output when 

### Problem
- I have a project from which I build multiple docs - each of which contain images.

./document1
./documentation/document2
./documentation/otherdocument/document3

/output

When I build using sphinx-build -D master_doc=./document1 everything is fine.
When I build using sphinx-build -D ./documentation/document2 or sphinx-build -D ./documentation/otherdocument/document3 image links are broken.

On inspection of the generated HTML source, the offset to the _images folder is being miscalculated.
In the first instance, it's correct, the _images folder is beside the html.
In the second, the offset is incorrectly calculated as ../../, rather than ../
In the third, the offset is incorrectly calculated as ../../../../, rather than ../../.

I've attached a test project to reproduce - and I think I can see what's happening from the source -

In  StandaloneHTMLBuilder.write_doc:

get_target_uri(docname) returns the target URI to calculate the relative link to the _images and _downloads folder.

Uses osutil.relative_uri to calculate the relative URI.
Give-or-take a little complexity, in cases like mine, where there is no leading space, this simple returns:
return ('..' + SEP) * (len(b2) - 1) + SEP.join(t2)
Where b2 is the result of previous get_target_uri(docname), split on "/".

Here's the problem. 

SingleFileHTMLbuilder overrides get_target_uri to return not just docname, but anchor too:
            return self.config.master_doc + self.out_suffix + \
                '#document-' + docname

Which means the code in osutil.relative_uri counts both the slashes before and after the #, and double accounts for the image path.

If I add code in StandaloneHTMLBuilder.write_doc to use:
get_target_uri(docname.split("#")[0]) instead of get_target_uri(docname) - everything works.

I'd submit a PR, but I don't know the codebase welll enough to know whether this is the "right" place to fix it, or if it's symptomatic of a wider problem that needs a brain cleverer than mine to fix ;-)

#### Procedure to reproduce the problem
Unzip the attached zip.
Run test.bat

#### Error logs / results
No Error Logs
Look in _build folder.
Note document1.html has kittens as expected.
documentation/document2.html and documentation/otherdocumenatation/document3.html have broken kittens.

### Reproducible project / your project
- Attached test.zip

### Environment info
- OS: Windows
- Python version: 3.6
- Sphinx version: 1.5.1 - 1.5.6

**Comment by tk0miya** [comment]
Thank you for reporting. I'll take a look.
It seems `Attached test.zip` is missing. Could you attach it again?

**Comment by MattWherry** [comment]
[test.zip](https://github.com/sphinx-doc/sphinx/files/1058646/test.zip)

**Comment by MattWherry** [comment]
Thanks for that - My apologies for the delay with the test zip - I've been out of the office.

**Comment by gvcgael** [comment]
I'm having the same problem. Did you find any workaround ?

**Comment by tk0miya** [comment]
On my local, #7339 fixed this problem. Could you check it please?

**Comment by gvcgael** [comment]
Yes it fixes the problem !

**Comment by tk0miya** [comment]
Thank you for confirming :-) Merged now. It will be released as 3.0.0 soon (maybe in early April).
