### ISSUE TITLE
Can't reset namespace with py:module

### ISSUE THREAD

**Issue by YuriPetrov** [sphinx-doc/sphinx#3844]
Subject: Can't reset namespace with py:module

### Problem
In my docs I have refs to some Python functions. Problem is that when I use the following code:

`.. py:module:: re`
`   .. py:function:: match(...)`
``
`# some code`
``
`.. py:module:: `
`   .. py:function:: map(function, iterable, ...)`

`map()` function happens to be inside `re` namespace, not in builtins (without module namespace). If I change the order of modules - it's ok. So I can't figure how to reset module level back to nothing.

#### Procedure to reproduce the problem

Just take the code above.

#### Error logs / results
-

#### Expected results
`map()` function should be without `re` module namespace.

### Reproducible project / your project
-

### Environment info
- OS: Windows 7+, Ubuntu 14+
- Python version: 3.5
- Sphinx version: 1.6.2

**Comment by tk0miya** [comment]
You can do it with `.. py:currentmodule:: None`.
Thanks,
