### ISSUE TITLE
:numref: numbering of Figures in PDF (XeLatex) - error: WARNING: no number is assigned

### ISSUE THREAD

**Issue by h10a** [sphinx-doc/sphinx#3855]
Subject: :numref: numbering of Figures in PDF (XeLatex) - error: WARNING: no number is assigned

### Problem
I have spent quite a bit of time searching and trying to figure out what I am doing wrong. If anyone happens to see what I have missed, I would appreciate the guidance.  

Here are the relevant pieces from my conf.py file: 
```
# -- Options for automatic Figure numbering
numfig = True
numfig_secnum_depth = (2)

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ['sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.ifconfig',
    'sphinx.ext.githubpages',
    #'rst2pdf.pdfbuilder'
    ]


latex_engine = 'xelatex'
```
-----------------------------------------

I have a topic file that is trying to reference a figure as follows: 
>>>
Login screen displays first when accessing the interface.

The **Authentication** window displays ( :ref:`fig-login` ).

The **Authentication** window displays ( :numref:`Figure <fig-login>` is my caption ).

.. _fig-login:

.. figure:: /_static/login/login.png
   :align: center

   Login Screen
<<<

The first sentence outputs the caption of the figure. 
The second sentence gives me an error that says: 
WARNING: no number is assigned for figure: fig-authentication

In the PDF output, the figures do have numbers assigned to them.  

I would appreciate any direction that you can provide. 

Thanks, 
barbara

#### Procedure to reproduce the problem

```
make TYPE_DOCUMENT="test" latexpdf
```

#### Error logs / results
```
processing Web_0.1.tex... _latex/index login
resolving references...
/Users/barbarapilbin/Documents/docs/test/source/login.rst:8: WARNING: no number is assigned for figure: fig-login
writing... done
```
- <public link of unexpected result if you have>

#### Expected results
<Describe what to actually do>

### Reproducible project / your project
Attached a zip file. 
[docs.zip](https://github.com/sphinx-doc/sphinx/files/1058813/docs.zip)

### Environment info
- OS: Mac
- Python version: 2.7.10
- Sphinx version: Running Sphinx v1.5.5
- <Extra tools e.g.: Browser, tex or something else>

**Comment by tk0miya** [comment]
Sphinx tries to verify numbered-reference from `master_doc`. But LaTeX document only refers `latex_documents`, not `master_doc`. In addition to this, some builders also does not refers `master_doc`.
I'll try to follow these builders.

**Comment by h10a** [comment]
I am still new to Sphinx and the builders.  I am not sure exactly where master_doc is defined at this point. If there is a work around that you would suggest, I am happy to try it!

**Comment by tk0miya** [comment]
As a workaround, please write `master_doc` in your conf.py to point `"_latex/index"`.
By default, it is defined as `master_doc = "index"`.

**Comment by h10a** [comment]
Okay! I think I have something working!
Here are the changes I made (maybe it will help someone else). 

in config.py: 

```
master_doc = '_latex/index'
numfig = True
numfig_secnum_depth = (2)
numfig_format = {'figure': 'Figure %s', 'table': 'Table %s', 'code-block': 'Code Block %s'}
```
(added numfig_format)

In my topic file, I figure and the reference looks like the following: 
```
Login screen displays first when accessing the interface.

The **Authentication** window displays ( :ref:`fig-login` ).

The **Authentication** window displays ( :numref:`fig_login1` is my caption ).

.. _fig-login:

.. figure:: /_static/login/login.png
   :name: fig_login1
   :align: center


   Login Screen
```

I found this question, and it also helped me figure out the initial error I was getting after I changed the master_doc configuration. 
https://github.com/sphinx-doc/sphinx/issues/1763

Thank you very much for your time!
