### ISSUE TITLE
use str() instead of repr() to display function type annotations

### ISSUE THREAD

**Issue by sbourdeauducq** [sphinx-doc/sphinx#3857]
According to https://stackoverflow.com/questions/1436703/difference-between-str-and-repr-in-python, it would be more appropriate to use ``str()`` instead of ``repr()`` to display the type annotations of documented functions. ``str()``'s goal is to be readable, whereas ``repr()``'s goal tries to produce something that you could put into ``eval()`` to reconstruct the object. The former seems more appropriate to me for something to put into documentation.

The function ``format_annotation()`` (two uses of ``repr()``) in ``sphinx/autodoc.py`` could be changed to do this.

There might be other places in sphinx where ``str()`` would be more appropriate (``object_description()`` in ``util/inspect.py``?) but I have not thoroughly checked that.

**Comment by tk0miya** [comment]
I don't have strong opinion. @shimizukawa do you have any comment?

**Comment by sbourdeauducq** [comment]
Ping

**Comment by sbourdeauducq** [comment]
Can someone please look into this? It's not a complicated change, is it? @tk0miya @shimizukawa

**Comment by sbourdeauducq** [comment]
@tk0miya @shimizukawa ping

**Comment by tk0miya** [comment]
Sorry for very very late response.

It seems @shimizukawa has been busy.
Okay, let's go ahead. But I've not understood what we should change. Could you send us a PR please?

**Comment by sbourdeauducq** [comment]
The code has been refactored in 2.0 and I'm not completely sure what this change should become either, but I think using ``str()`` instead of ``repr()`` on user objects in ``sphinx/util/inspect.py`` should be the way to go.

**Comment by tk0miya** [comment]
Yes, we'd stopped to use `format_annotation()`. And there are no `repr()` calls in `sphinx.util.inspect:Signature` class; the successor of the function.
I guess this problem was already resolved. Is this right?

I know `object_description()` is still using `repr()`. But I don't understand what problem it caused. If you think it is problem, please let me know an example for it. I don't understand what is real problem.

**Comment by sbourdeauducq** [comment]
> But I don't understand what problem it caused. If you think it is problem, please let me know an example for it. I don't understand what is real problem.

Create a function with some type annotation, e.g. ``def foo(x: bar)``, then it calls ``repr()`` on ``bar`` which produces a less appropriate result than ``str()``.

I do not know if this still happen with the latest code, but it did when I reported the issue.

In general I do not see why sphinx would use ``repr()`` anywhere instead of ``str()``.  As I posted above: ``str()``'s goal is to be readable, whereas ``repr()``'s goal tries to produce something that you could put into ``eval()`` to reconstruct the object. The former seems more appropriate to me for something to put into documentation.

**Comment by tk0miya** [comment]
I feel there are nothing to do for this issue now. So I'm closing this now.
Please feel free to reopen if you found another call.

Thank you for reporting.

**Comment by dnadlinger** [comment]
`repr()` is still (again?) used in master: https://github.com/sphinx-doc/sphinx/blob/7faeb793e2e16cde4e5759443fb7f84efddcd9ea/sphinx/util/inspect.py

**Comment by tk0miya** [comment]
Yes, we did not replace `repr()` call. Are you in trouble? If so, please let me know your real problem in detail. I'd like to know it.

**Comment by dnadlinger** [comment]
I am building documentation for a project which uses the [ARTIQ](https://github.com/m-labs/artiq) real-time control system framework. ARTIQ includes a compiler from Python to machine code, which uses custom type annotations (plus type inference) to implement static typing. (The target is usually a soft CPU on an FPGA).

As per the above, the maintainers of the compiler believe that `str()` is supposed to be used for human-readable strings, while `repr()` ought to include a complete representation of the internal state. Accordingly, for the types used for annotations, `__repr__` returns details of their internal representation, while `__str__` returns a string on the right abstraction level for users.

This leads to autodoc output for type hints being cluttered and multiple lines long as-is, while they render beautifully when using `str()` instead.

Currently, I'm using a crude monkey patch to change Sphinx's behaviour (
https://github.com/OxfordIonTrapGroup/ndscan/commit/39578bc657417db81f47e3bcc22fbcfef7b4f64c), but it would be good to have a configuration option (maybe even by default) that more closely matches the officially documented meaning of these in Python.

The docs for [`__repr__`](https://docs.python.org/3/reference/datamodel.html#object.__repr__) say "If at all possible, this should look like a valid Python expression […]", while for [`__str__`](https://docs.python.org/3/reference/datamodel.html#object.__str__), they mention "[…] nicely printable string representation of an object […] a more convenient or concise representation can be used". It seems pretty clear that the latter would be more appropriate to use in human-readable output.

**Comment by tk0miya** [comment]
I know `str()` and `__str__()` are used for "human readable" output. In my thought, "human" means users of the program. Sometimes, I made `__str__()` method to represent its value for users. I think that's not so wrong design.

On the other hand, the users of autodoc are programmers, not users. So it would be better to represent objects to describe what the object is. This is my understanding why we use `repr()` to stringify method signatures. I'm not original author of autodoc, so I don't know my understanding is right.

I know `repr()` is not good for some kind of objects. But I feel `str()` is also not perfect.

FYI:
If we use `str()` to stringify method signature, we'll get `foo(bar=baz)` from `def foo(bar="baz")`. We have to give a special treatment for `str` (and some kind of objects?).

**Comment by tk0miya** [comment]
Reopened for discussion.

**Comment by sbourdeauducq** [comment]
> On the other hand, the users of autodoc are programmers, not users.

Taking this and also backward compatibility into account, maybe there could be an option in ``conf.py`` to select ``str`` vs. ``repr`` behavior?

**Comment by tk0miya** [comment]
As I commented above, using `str()` will break the output of autodoc. So I will not provide such an option. Please patch a `sphinx.util.inspect:object_description()` to use `str()` instead of `repr()`. Then, you'll see the broken result.

Side note: autodoc calls `object_description()` at here and there. So it is difficult to pass an option to it...

**Comment by Liam-DeVoe** [comment]
Is there a reason this has been closed? It's quite possible I'm missing something, but I don't think a resolution was reached by the above comments.

**Comment by sbourdeauducq** [comment]
It seems this just won't get resolved.

**Comment by Liam-DeVoe** [comment]
it's even less likely to get resolved if you close it :)

**Comment by sbourdeauducq** [comment]
You can use a hack like this: https://github.com/m-labs/artiq/commit/97e994700bc98f1d7376c184efda87b4919bdea0
