### ISSUE TITLE
Some warnings are not colored when using --color option

### ISSUE THREAD

**Issue by ArtFlag** [sphinx-doc/sphinx#3858]
### Problem

When building a project using `sphinx-build --color -b html source/ out`, the **Undefined substitution referenced: "xxxxx"** warning is not colored (but the other warnings that I have seen are colored).

#### Procedure to reproduce the problem
1. In a Sphinx project, add an undefined variable to a rst file, i.e `|qwerty|`.
2. Build using `sphinx-build --color -b html source/ out`
3. Notice that the warning about the unknown `|qwerty|` variable is not colored.

#### Expected results
All warning messages should be colored (and using the same color).

### Environment info
- OS: Mac (Sierra)
- Python version: 2.7.10
- Sphinx version: 1.6.2

**Comment by tk0miya** [comment]
Thank you for reporting.
Fixed at 6cf78da

**Comment by ArtFlag** [comment]
Hi Takeshi, and thanks for the quick fix. 
I have noticed that the following warning is also uncolored:  `WARNING: Unknown interpreted text role "xxxxx".`

Not sure if your commit fixes this one automatically. If not, let me know and I will create a new issue.

**Comment by tk0miya** [comment]
Yes, it is also colored with my fix.
Thanks,
