### ISSUE TITLE
code-block captions are not displayed correctly in man pages

### ISSUE THREAD

**Issue by zjs** [sphinx-doc/sphinx#3859]
### Problem
code-block captions are not displayed correctly in man pages

#### Procedure to reproduce the problem
Run the following:
```
mkdir /tmp/code-block-test
cd /tmp/code-block-test
yes "n" | sphinx-quickstart --dot _ --project code-block-test --author "Example" -v 0 --release 0 --language en --suffix .rst --master index --makefile --batchfile docs
echo '
Below is an example of a codeblock with a caption.

.. code-block:: bash
   :caption: This is a caption

   echo 1234
' >> docs/index.rst
make -C docs man
```

#### Error logs / results
The rendered man page contains:
```
       Below is an example of a codeblock with a caption. This is a caption.INDENT 0.0

          echo 1234
```

#### Expected results
".INDENT 0.0" should not appear in the man page.

I would expect the rendered version of the man page to look more like:

```
       Below is an example of a codeblock with a caption.

       This is a caption

          echo 1234
```

(This would be consistent with the behavior of `html` and `latexpdf`.)

### Reproducible project / your project
See above.

### Environment info
- OS: Ubuntu 16.04 LTS
- Python version: Python 2.7.12
- Sphinx version: Sphinx v1.5.6

**Comment by tk0miya** [comment]
Fixed by #6159.
Thank you for reporting
