### ISSUE TITLE
in i18n setups sphinxprettysearchresults returns only previews from canonical language

### ISSUE THREAD

**Issue by acsr** [sphinx-doc/sphinx#3862]
In the past I had issues finding particular words using the sphinx search with 1.5.2.

For example a level 2 (h2) headline contains the word "Codecs" search did not find the actual headline but the paragraphs below.

The same was found with our i18n translated version.
There was also a bug in the sphinx-rtd-theme affecting the search not working with sphinx-rtd-theme 0.1.x that had needed a patch in layout.html to make it work.

I updated today to Sphinx (sphinx-build) 1.6.2 and to sphinx-rtd-theme 0.2.4 and still use sphinx-intl 0.9.9

no improvement!

### Problem
- the sphinx search results returns only preview snippets from the canonical language and does not find all words.

#### Procedure to reproduce the problem

We use to render the html using this command:

`make SPHINXOPTS="-D language='de'" BUILDDIR="_build/de" clean html`

and 

`make SPHINXOPTS="-D language='en'" BUILDDIR="_build/en" clean html`

We have primarily german main language and translate to english using po files. Some content is english only (the new in 1.4 section in the example) ! So if you see some english results, they are actually not translated!

Before we do proper recompile of mo files etc.

When you browse the html (cache deleted!) and search in the english content translated from german, the preview of the context of the find is shown in german, but the resulting link goes to the proper english translation location.

Some words are found if they are in top level headlines!

#### Error results

- http://www.present4d.de/wiki/update/en/search.html?q=codec&check_keywords=yes&area=default

#### Expected results

- Find results pointing to subheadlines that contain the topic/word

### Sugestions

- Developers: If you fiddle around with search result prettification, make sure you use a i18n setup to make sure you do not use a text source for display, that is not properly translated. English only developers tend to miss this scope.

### Environment info
- OS: MacOS 10.11.6 with Python 3.4 in a sphinx specific virtualenv
- Python version: Python 3.4
- Sphinx version: 1.6.2
- Browser Chrome

**Comment by acsr** [comment]
for the record: We always update the translations using this workflow:

1.  `make gettext`
2. `bin/sphinx-intl update -p _build/locale -l de` and  `bin/sphinx-intl update -p _build/locale -l en`
3. Update the .po files with translations
4. Check the translations using `bin/sphinx-intl stat`
5. Compile the mo `bin/sphinx-intl build --output-dir="_source/locale"`
6. render the html as described above. `make SPHINXOPTS="-D language='en'" BUILDDIR="_build/en" clean html`

**Comment by acsr** [comment]
In an earlier version of this ticket the title of the ticket contained a reference to the third party module sphinxprettysearchresults. I removed this word due to ambigous meaning. The module sphinx-pretty-searchresults was not involved in this issue or in the site-packages path either.

**Comment by acsr** [comment]
Update: in my latest builds of the english language (translated via i18n from german (de)) , the search results end up without any (neither german or english) content context rendered by the Javascript search result when serverd from a webserver. No additional details show up. But now all occurences are properly highlighted in the result by Javascript, even in the sub-headlines.

**Comment by tk0miya** [comment]
>Developers: If you fiddle around with search result prettification, make sure you use a i18n setup to make sure you do not use a text source for display, that is not properly translated. English only developers tend to miss this scope.

Unfortunately, current sphinx uses source files to show highlights and contents-previews. So it might be includes even bare mark-ups like directives and roles. As you said, it is also not translated.
AFAIK, it behaves likes an experimental feature.

`sphinxprettysearchresults` tries to resolve this situation. So we have to merge it into Sphinx and improve it to support i18n :-)

**Comment by TimKam** [comment]
Related to #1618.
As mentioned in the issue I just referenced, `sphinxprettysearchresults` *can* work well with i18n - the issue most likely depends on some specific build setting.
Also, I'd be happy to merge `sphinxprettysearchresults` (which I maintain) into Sphinx, but this is not trivial, especially because `sphinxprettysearchresults` increases the build time significantly.
If anyone has suggestions on how this can be achieved, I'm happy to help.

**Comment by TimKam** [comment]
When 2.0 is released (with #1618), there will be no need to use ``sphinxprettysearchresults`` anymore. Hence, I close this issue.
