### ISSUE TITLE
Failure of deprecation warning mechanism of `sphinx.util.compat.Directive` with IPython extension

### ISSUE THREAD

**Issue by jfbu** [sphinx-doc/sphinx#3873]
Subject: the `sphinx.util.compat` module is deprecated at 1.6 and will be removed at 1.7. But when I use `ipython` directive with Sphinx 1.6.2, there is no warning.

#### Procedure to reproduce the problem

With Sphinx 1.6.2:

```
mkdir /tmp/IPython-test
cd /tmp/IPython-test
yes "n" | sphinx-quickstart --dot _ --project IPython-test --author "Example" -v 0 --release 0 --language en --suffix .rst --master index --makefile --batchfile .
echo "
extensions = [
    'IPython.sphinxext.ipython_console_highlighting',
    'IPython.sphinxext.ipython_directive',
]

ipython_mplbackend = None
" >> conf.py
echo "
Welcome to IPython-test's documentation!
========================================

.. ipython::

   In [1]: x = 1

   In [2]: y = x**2

   In [3]: print(y)

" > index.rst
make html
```
there is no warning.

On the other hand when using Sphinx master branch, build fails

```
Extension error:
Could not import extension IPython.sphinxext.ipython_directive (exception: No module named 'sphinx.util.compat')
make: *** [Makefile:20: html] Error 1
```

#### Expected results

1.6.x Sphinx users of `ipython` directive get a warning and can report upstream... but I did it already at https://github.com/ipython/ipython/issues/10666 ;-)

### Environment info
- OS: Mac
- Python version: 3.5.3
- IPython version: 6.1.0
- Sphinx version: 1.6.2

**Comment by tk0miya** [comment]
Fixed at 6a37912.
