### ISSUE TITLE
Problem since Sphinx 1.6.1 with Multiple multi-line signatures (cpp domain)

### ISSUE THREAD

**Issue by jfbu** [sphinx-doc/sphinx#3877]
### Problem
Consider this

```
.. cpp:function:: template<typename T> void f() 

   Multi-line signature.

.. cpp:function:: template<typename T> void g() 
                  template<typename T> void h()

   Multiple multi-line signatures. They should probably have a bit of vertical whitespace.

.. c:function:: void g()
                void h()

   Single-line signatures, they should probably have the same vertical whitespace.
```

With 1.6.1 there is a line break in html, and latex output:

![capture d ecran 2017-06-19 a 01 50 16](https://user-images.githubusercontent.com/2589111/27265215-b18beb12-5491-11e7-9c3a-dd679cd4d55e.png)

```
template<
typename T
>
```

With 1.5.6 there is only one line.

### Environment info
- OS: Mac
- Python version: 3.5.3
- Sphinx version: 1.6.1

**Comment by jfbu** [comment]
The first bad commit appears to be e3cb2bbcf18d301400835d0778c81a15cfd0da99, which added the ``:tparam-line-spec:`` option. But perhaps the example code I picked from https://github.com/sphinx-doc/sphinx/pull/3072#issue-184161890 was only for demonstration at that time and is not valid cpp syntax, hence there is no problem at all ?

**Comment by jakobandersen** [comment]
There was indeed a bug, specifically when multiple signatures were declared in one go. Thanks.
