### ISSUE TITLE
Setuptools integration placing build results in unwanted directories

### ISSUE THREAD

**Issue by multimeric** [sphinx-doc/sphinx#3883]
### Problem
When adding a `BuildDoc` task to Sphinx, it correctly builds the documentation, but places the output files in directories named after their builder, e.g. `html`.

#### Procedure to reproduce the problem
Running the following command with the following `setup.py` results in a directory named `html` located in the current directory:
```bash
python setup.py build_html
```
```python
setup(
    name=name,
    version=version,
    packages=find_packages(),
    cmdclass={
        'build_html': BuildDoc
    },
    command_options={
        'build_html': {
            'project': ('setup.py', name),
            'version': ('setup.py', version),
            'source_dir': ('setup.py', 'docs/source'),
            'build_dir': ('setup.py',  '.'),
            'builder': ('setup.py', 'html')
        }
    },
)
```

#### Expected results
Sphinx, with the `setup.py` above, should act the same way as running the following sphinx command:
```bash
sphinx-build -b html docs/source .
```

Namely, the file `<master doc>.html` should exist in the current directory, not in an `html` directory.

### Environment info
- OS: Ubuntu 16.04
- Python version: 3.6.0
- Sphinx version: 1.6.2

**Comment by tk0miya** [comment]
Sphinx generates multiple files at once. For example, `_images`, `_static` and `_sources` directories.
Sphinx is mainly designed for middle or large document. So It does not generate single file.

Personally, I feel your proposal is not worthy for users of Sphinx.

**Comment by multimeric** [comment]
No, I don't think you understand my problem. I believe this is a bug in the `BuildDoc` command class, it's not a feature request. 

If you run `setup.py` with a `BuildDoc` command with `'build_dir': ('setup.py',  '.'),`, namely, *the build dir is also `.`*, Sphinx will put the build results in a subdirectory called `html`:
```
.
├── docs
│   ├── Makefile
│   └── source
├── doctrees
│   ├── environment.pickle
│   └── readme.doctree
├── html                       ← This directory is created
│   ├── genindex.html
│   ├── _modules
│   ├── objects.inv
│   ├── readme.html               ← The HTML file is placed inside this subdirectory
│   ├── search.html
│   ├── searchindex.js
│   ├── _sources
│   └── _static
├── LICENSE
├── pandas_diff
│   ├── diff.py
│   ├── __init__.py
│   ├── __pycache__
│   ├── scripts.py
│   └── test.py
├── readme.rst
├── requirements.txt
├── setup.py
└── venv
    ├── bin
    ├── include
    ├── lib
    ├── lib64 -> lib
    ├── pyvenv.cfg
    └── share
```

However, when you run `sphinx-build -b html docs/source .`, it builds the HTML page (and subdirectories like `_images`, `_static`, etc) _directly_ in the build directory. There is no `html` directory. I believe this is how it should work:
```
.
├── docs
│   ├── Makefile
│   └── source
├── doctrees
│   ├── environment.pickle
│   └── readme.doctree
├── genindex.html
├── LICENSE
├── _modules
│   ├── index.html
│   └── pandas_diff
├── objects.inv
├── pandas_diff
│   ├── diff.py
│   ├── __init__.py
│   ├── __pycache__
│   ├── scripts.py
│   └── test.py
├── readme.html           ← The HTML is placed directly in the build directory
├── readme.rst
├── requirements.txt
├── search.html
├── searchindex.js
├── setup.py
├── _sources
│   └── readme.rst.txt
├── _static
│   ├── ajax-loader.gif
│   ├── alabaster.css
│   ├── basic.css
│   ├── comment-bright.png
│   ├── comment-close.png
│   ├── comment.png
│   ├── custom.css
│   ├── doctools.js
│   ├── down.png
│   ├── down-pressed.png
│   ├── file.png
│   ├── jquery-3.1.0.js
│   ├── jquery.js
│   ├── minus.png
│   ├── plus.png
│   ├── pygments.css
│   ├── searchtools.js
│   ├── underscore-1.3.1.js
│   ├── underscore.js
│   ├── up.png
│   ├── up-pressed.png
│   └── websupport.js
└── venv
    ├── bin
    ├── include
    ├── lib
    ├── lib64 -> lib
    ├── pyvenv.cfg
    └── share
```

*The BuildDoc class behaves differently from the Sphinx command line*. Surely this is a bug.

**Comment by tk0miya** [comment]
>I believe this is a bug in the BuildDoc command class, it's not a feature request.

The BuildDoc command has generated files under sub-directory `html` since v0.5 (its appearance; https://github.com/sphinx-doc/sphinx/commit/68f5d02390f0bc56759a4b6b74fec2b756bd2cd0#diff-b189b53617e25089010a1ff018f75d66R62).
I don't know this is whether intended or not (in other words, a bug or not). But, at least, many people uses it as is for a long time. So I think the fix might bring incompatible changes.

BTW we've improved the options of BuildDoc independently of `sphinx-build` command (ref: #3476). So we need to fix this carefully.

**Comment by stephenfin** [comment]
@TMiguelT Yeah, as @tk0miya mentions, we support multiple builders using the `sphinx_build` setuptools command now. This would suggest that we _can't_ fix this now, even if we wanted to (and I'm not sure we do).

My personal suggestion would be to add a note on the `build_dir` option for the extension noting this fact. That extension is a helper method and I don't think it should be expected to work exactly like, or offer the same functionality as, `sphinx-build`.

**Comment by AA-Turner** [comment]
The setuptools integration is deprecated and will be removed.

A
