### ISSUE TITLE
Ignore/delete options by using "sphinx-build -D html_theme_options"

### ISSUE THREAD

**Issue by danwos** [sphinx-doc/sphinx#3884]
Subject: I need to ignore/delete html_theme_options inside a "sphinx-build" call

### Problem
I want to build a given sphinx project, which template-settings needs to be replaced.
To achieve this, I use the -D option of sphinx-build [1].
-D works pretty well for setting single values like "html_theme".
But it seems to have some drawbacks, if a dictionary needs to be configured/replaced (like html_theme_options).

The detailed problem of my use case:
1. A given conf.py uses a defined theme and some html_theme_options for this theme
2. If I replace the theme via "sphinx-build -D html_theme=MyTheme", Sphinx cancels the build
with the error  "Theme error: unsupported theme option 'XYZ' given".
3. I need to get rid of the unknown(!) html_theme_options, as they are not used by my theme.

#### sphinx-build -D html_theme_options=
sphinx gives me this warning:
"WARNING: cannot override dictionary config setting 'html_theme_options', ignoring (use 'html_theme_options.key=value' to set individual elements)"

So the idea is to set specific elements of html__theme_options.
**Problem with this proposal**: I do not know the used options of a given conf.py.

### Expected Behavior
First of all, I do not understand why a not used html_theme_option is so bad for the current sphinx build, that it needs be to canceled.
A warning would be ok, but I see no technical reasons for cancelling the whole build.

**sphinx-build -D html_theme_options=** should be a valid operation and should replace/clean the whole html_theme_options dictionary.
Or there should be some other option to clean/remove a config parameter.

Or does somebody have another idea how to solve my problem?

[1] http://www.sphinx-doc.org/en/stable/man/sphinx-build.html#options

**Comment by danwos** [comment]
I took a look into the code and this seems to be the part, which raises an error, if html_theme_options has  unknown theme options:
https://github.com/sphinx-doc/sphinx/blob/78a20617b52e02e422d78a22cc3dc98e4b417f1b/sphinx/theming.py#L136
```python
for option, value in iteritems(overrides):
    if option not in options:
        raise ThemeError('unsupported theme option %r given' % option)
    options[option] = value

    return options
```

In my understanding there is no need to raise an Error, as this is not really a problem for the build process and we could simply skip unknown options.
So this code could be changed to:
```python
for option, value in iteritems(overrides):
    if option not in options:
       # This is an unknown option for the used theme. We skip it.
        logger.warning('unsupported theme option %r given' % option)
    else:
        # Configured options is valid for used theme. Let's add it to the list of returned/valid options
        options[option] = value

    return options
```

I could create a pull request, but before doing this I would like to see some professional feedback on this.

**Comment by tk0miya** [comment]
+1 for warning.
Could you send us PR?

**Comment by danwos** [comment]
Pull request: #3893
