### ISSUE TITLE
Import error: no module named airflow

### ISSUE THREAD

**Issue by N-CP** [sphinx-doc/sphinx#3886]
problem
- Try to run a Dag by using command
python xxx.py

giving error
 File "/usr/bin/airflow", line 17, in <module>
    from airflow import configuration
ImportError: No module named airflow

- OS: Linux
- Python version:2.7

**Comment by tk0miya** [comment]
Is this related with Sphinx?

**Comment by N-CP** [comment]
no

**Comment by tk0miya** [comment]
Sorry, this is issues for Sphinx.

**Comment by ustbfc** [comment]
u can change ur default python version as python3
