### ISSUE TITLE
sphinx-quickstart in 'First Steps' (docs/tutorial.rst) is misleading (for newbies)

### ISSUE THREAD

**Issue by AlbertMietus** [sphinx-doc/sphinx#3895]
Context
======

Frequently I train *young*, high-tech, *professional* **software-engineers** on the art of the craft. This includes documentation (and version-control of it). They have work on a 'big project' and learn a lot (like we all once needed).

We use **sphinx** in this "training-project", for all documentation.
They have, to be able to create the (html) docs and to extend the rst-files docs read/scan/understand the Sphinx-doc's documentation (the website).

'First Steps'
------------

The 'First Steps' chapter is very appealing for them. It more or less says:
1) Install Sphinx (**OK**)
2) Run ``sphinx-quickstart`` (**WRONG**, see below)
3) Add a toctree      *[to add their 'team-pages']*
4) Add more docs   *['team-pages' (notes) and real docs, and more]*
5) etc.

Problem
======
As the *"big-project"* already exist, its docs --including the ``conf.py`` file-- does exist! It is stored in version-control. 
Basically, they **shouldn't** *"start"*  with a new doc-project! But the docs says they should ...

This goes wrong with many new trainees. 

Even seniors make the same mistake
-------------------------------------

Also, at many customers, which I advice to use Sphinx, people make the same mistake.  They are more experienced, but are 'new' to sphinx. So they do make the same mistake (but less frequently).

Typically,  one one person in the team/project should set-up the (initial) structure and create those (``conf.py``) file 
Often that is me.  So nobody is interessed in this 'first step'. It more an initial-step then a first ...

Flaws
=====

* Typical people spend time on the 'wrong' fist steps. 
* Sometimes they add ``conf.py`` (and more) files into a existing doc-structure (repository)

Mostly, it can be fixed (actually: always). **_But they lose motivation for Sphinx_** That is the most important driver to submit this "bug".

Suggestion
=========

I propose to move this "quickstart" procedure (in the docs) to the advanced section. As it is only needed once, typical run by an experienced user.

And add a short note about "getting"  ``conf.py`` from e.g. version-control in the 'fitst-step'.  Or to use this tool --as a last-resource.

Being able to *run*  ``sphinx-build`` is a lot more important. That should be mentioned in the 'First Steps'. With a small, typical (so: html) command-line example.

Auto-run
---------
The option to run it from **``make``** (or any other runner, like: ANT,  RTfD, Eclipse-run)  is nice, but not that important for a 'first-time-user'. 

So, that should be part of 'first steps'. And so, we don't need ``sphinx-quickstart`` for that neither.

Alternative
-----------

As an alternative, this tool can be removed (almost) completely. I never use it. 

Creating the ``conf.py``file is a lot easier by copy-and-modify a existing one (or a template). The makefile-part is typically add to a generic/overal Makefile.

This tool is (in my opinion) only useful for small-project starting with Sphinx. Then it is useful to make the really-first set-up. I used it once, when I downloaded Sphinx the fist time. It was useful, but a template to fill in the details (in my editor) would be fine too.

**Comment by AlbertMietus** [comment]
As always, I'm willing to help implement this :-)

**Comment by shibukawa** [comment]
Trainees in the some (your) courses are unusual users. We cannot support all use cases all over the world. Our tutorial document was written for users they learn by themselves and write documents from scratch. Almost all users don't have any templates.

We recommend to fork Sphinx's repository and modify the tutorial for your course.

https://github.com/sphinx-doc/sphinx/tree/master/doc

Sphinx is structured in Unix's philosophy. sphinx-build is a basic building block. As you said, advanced users modify Makefile/make.bat or use any task running system that maches their needs.

**Comment by tk0miya** [comment]
I agreed with @shibukawa. I don't think everyone works on "big project" and having their existing `conf.py`. I guess they are special case.

**Comment by AlbertMietus** [comment]
I really *hope* most teams  use version-control for there projects. And store there docs in version-control. Isn't that one of the great things of Sphinx/RST: having version-controllable "sources" of your docs. 
Thats also a a bit of a no-brainer, here on github, I guess.

PS ' big-project' shouldn't be misread: It's big for them: former students. They have to work with several people/teams on one code-base (incl. docs). And pass the work to a next team/class. That is to motivate & train them for real projects (independent of size); and so, use version-controll. And write good docs; as they like to get from the former team/class

I guess, that the typical use-case. At least that is what I experience. Both in my profession, and with open-source. See RTfD: most project have many contributors. 
See sphinx itself: : many contributors and only one ``conf.py``

**Comment by tk0miya** [comment]
I think nobody denies to use version controls for document here.
Indeed, version-control is very useful and all developers should use it.

But what I'd like to say here is our tutorial should includes the way to create sphinx document from scratch. It is basic of our tool. For sphinx beginners, to create own testbed is important to know how sphinx works.

**Comment by AlbertMietus** [comment]
I agree with the last remark. 

All I ask for is to acknowledge that in the docs. 

Instead of only mention the "quickstart" option, lets add a few words (a note?) on the version-controlled option too. 

Is that acceptable?


--albert
An iPhone is great, but for typing mail

**Comment by shibukawa** [comment]
Sphinx itself is independent of any version control system.

**Comment by AlbertMietus** [comment]
True. Sphinx is independent of any (specific) VCS. 

That however, isn't an argument to not write a note about "getting ``conf.py`` from the project's VCS" ? 

Not on how, nor which VCS, just about the option!
Just to make sure those "project user" --reading the sphinx-docs to understand how to start use it-- don't make the mistake to start all over



--albert
An iPhone is great, but for typing mail

**Comment by kalenkovich** [comment]
@AlbertMietus sorry for using this thread to contact you. I am a young inexperienced student of the sort you described. I work on a project that has some .rsts and a conf.py in it and I want to build html using that conf.py. How do I do that? It seems that all the tutorials and docs assume that I start from scratch.

**Comment by AlbertMietus** [comment]
Hi @kalenkovich,

My “pupils” have to use sphinx, etc. And hope to document how to install/use/etc each step (for the next class, which continues where the left).

That document is “public”: http://pathways-extensions-training.readthedocs.io/. Most of it is about the project, but it does contain info how to setup the project, including Sphinx. So, it may be of help

Note: part is in English, partially it in Dutch. But then google-translate is your friend. 

---Albert 
Verstuurd via mijn iPad; excuus voor typo's etc.

**Comment by tk0miya** [comment]
Now I'm closing this now.
Thank you for your proposal.

**Comment by epogrebnyak** [comment]
Sphinx doucmentation really could do more to expose its workflow to newbies. *sphinx-quickstart* is overloaded with detail, but it does not create a runnable documentation, you need changes to *conf.py* as well as running *sphinx-apidoc*. The documentation says _There is also an automatic “API documentation” generator called sphinx-apidoc_, suggesting it is an extra feature. But if you do not run it, what the use of *sphinx-quickstart* result? Basically, you cannot do anything useful after *sphinx-quickstart*, unless extra steps are taken, why not write about these steps explicitly in the manual? 

I would have been grateful if I learned earlier that a workflow with sphinx most likely consists of:

- run *sphinx-quickstart* to create *docs* directory
- change system path in *conf.py* to make sure your package is importable 
- populate *docs* directory with .rst files with *sphinx-apidoc*
- change *index.rst*
- run *make html*
- pray it works
- dig into *_build\html\index.html* to see the result  
 
I wish this path was explict in the documentation, I think it could have made sphinx adoption easier and more wide-spread.

**Comment by tk0miya** [comment]
@epogrebnyak +1 for an additional document for apidoc. I don't think tutorial is good place to do it, but the document is really we need. PR is welcome :-)

**Comment by epogrebnyak** [comment]
@tk0miya, do you think the workflow outlined above is valid approach to beginner workflow or mind model of sphinx?

**Comment by tk0miya** [comment]
Sorry, I don't know so much about apidoc. Personally, I've never used it. So I can't answer it correctly. But I can agree there are very less official document for apidoc. So it would be very nice if we can add a section like "introducing apidoc".

On the other hand, Sphinx is not only for python users. Now it has been used by many people. IMO, apidoc is not a common feature for all of beginners. So I said tutorial is not good place for it.

**Comment by AlbertMietus** [comment]
I guess, we should make the tutorial a good place for starters.
That are completely newbies. And people -new on Sphinx, but- joining a project that is using Sphinx for documentation...


--albert
An iPhone is great, but for typing mail


[removed mail-tail ]
