### ISSUE TITLE
BUG? Autosummary `methods` missing in Sphinx 1.6

### ISSUE THREAD

**Issue by christianbrodbeck** [sphinx-doc/sphinx#3900]
Since Sphinx 1.6 methods seem to be missing from class documentation generated with autosummary. I use a file with contents like below as `autosummary/class.rst`. Methods are properly documented on Sphinx 1.5.6, but not on 1.6.1 and 1.6.2 (`conda`). If I insert `{{ methods }}` into the template, the docs display an empty list(`[]`) with 1.6 and a list of method names in 1.5.

```
{{ fullname | escape | underline  }}

.. currentmodule:: {{ module }}

.. autoclass:: {{ objname }}
   

{% block methods %}

Methods
-------

.. autosummary::
   :toctree:

{% for item in methods %}
   {%- if not item.startswith('_') or item in ['__call__'] %}
   ~{{ name }}.{{ item }}
   {%- endif -%}
{%- endfor %}
{% endblock %}
```

**Comment by tk0miya** [comment]
Could you share any example and procedure?
It's hard to reproduce this for me because I'm beginner of autosummary...

**Comment by christianbrodbeck** [comment]
[Here](https://github.com/christianbrodbeck/sphinx_test) is a minimal project that reproduces the problem (building with `conda` Sphinx 1.5.6 vs 1.6.2). Make sure to delete the `doc/generated` when changing version.

**Comment by tk0miya** [comment]
Thanks, I confirmed the issue. This comes from #3235.
I'll try to fix this later.

**Comment by tk0miya** [comment]
Fixed at b3e0e29.
Thank you for reporting!

**Comment by christianbrodbeck** [comment]
Thanks!

**Comment by jorisvandenbossche** [comment]
The exact same thing happens for Attributes (eg if you want to include automatically a list of the attributes in a class template, as done for methods in the example above). 
Can you 'attributes' be special cased as well (with a similar fix as the one that closed this issue?)

**Comment by jorisvandenbossche** [comment]
I see this is already reported in #4058 as well (although that has a broader scope)
