### ISSUE TITLE
Feature request: multiple columns in toctree

### ISSUE THREAD

**Issue by fredrik-johansson** [sphinx-doc/sphinx#3907]
It would be nice if toctree had an option to produce multiple columns (for HTML output), like the hlist directive. 

Example source code:

    .. toctree::
       :columns: 2
       :maxdepth: 2

       moduleA.rst
       moduleB.rst

Example output before:

    * moduleA
        * moduleA content
        * moduleA more content
    * moduleB
        * moduleB content
        * moduleB more content
        * moduleB even more content

Example output after:

    * moduleA                              * moduleB
        * moduleA content                      * moduleB content
        * moduleA more content                 * moduleB more content
                                               * moduleB even more content

Apologies if there already is some simple way to accomplish this that I've overlooked.

**Comment by timhoffm** [comment]
basically, you can adapt the css to include

~~~
.toctree-wrapper {column_count: 2}

**Comment by tk0miya** [comment]
@timhoffm seems good!
@fredrik-johansson what about this technique?

**Comment by fredrik-johansson** [comment]
Yes, that would seem to do the trick.

A small problem is that moduleA or moduleB can get broken up in the middle unless they have exactly the same number of entries, which looks bad. The following seems to be a workaround:

    div .toctree-wrapper { column-count: 2; }

    div .toctree-wrapper > ul { margin: 0; }

    ul .toctree-l1 { 
        margin: 0;
        -webkit-column-break-inside: avoid;
        page-break-inside: avoid;
        break-inside: avoid-column;
    }

Edit: even this doesn't work perfectly, but it's better than nothing.

**Comment by tk0miya** [comment]
Good to know!

Internally, toctree is stored as a bullet list. So it is hard to change the form of HTML tags soon.
So the CSS hack is good way to do that.

Note: I will accept changes if anyone works for it.
