### ISSUE TITLE
sphinx 1.6.[23] reports error with pygments 2.0.2 but not with 2.2.0

### ISSUE THREAD

**Issue by karelyatin** [sphinx-doc/sphinx#3910]
Subject: Reports error: Could not lex literal_block as "ini". Highlighting skipped

### Problem
- true for any project that uses pygments 2.0.2 and sphinx 1.6.2 or sphinx 1.6.3 
Example project: openstack/networking-ovn
In logs i see following warning: Could not lex literal_block as "ini". Highlighting skipped
But if i use pygments 2.2.0 and sphinx 1.6.2 or 1.6.3 no warning.

#### Procedure to reproduce the problem
```
project: openstack/networking-ovn
In virtualenv do:-
pip install -r test-requirements.txt
pip install pygments==2.0.2
python setup.py build_sphinx
```

#### Error logs / results
```
<Paste your error log here>
```
- <public link of unexpected result if you have>

#### Expected results
<Describe what to actually do>

### Reproducible project / your project
- https://github.com/openstack/networking-ovn/

### Environment info
- OS: Centos
- Python version: 2.7
- Sphinx version: 1.6.2/1.6.3
- virtualenv

**Comment by tk0miya** [comment]
We use pygments for highlighting. So the warning is emitted on pygments' error.

Anyway, what is your problem? It is already fixed at newest pygments.
It seems the parsing process is improved at current version.

**Comment by karelyatin** [comment]
<<< Anyway, what is your problem? It is already fixed at newest pygments.
if i use pygments 2.0.2 with sphinx 1.6.2 then i see warning but with pytments 2.2.0 no warning, looks like latest pygments fixed the warning.
I just wanted to know setup.py contains pygments>2.0 but looks like pygments 2.2.0 has many fixes, when it would be updated in sphinx(pygments>-2.2).

**Comment by tk0miya** [comment]
Thank you for comment.
pygments-2.2.0 is released Jan 2017. So it is very new for us. To support many people, it would be nice to reduce strong restriction.
I know newest package is much improved and having bug fixes. But I feel they are not critical. so I'd like to keep our dependency as is.

Thanks,
