### ISSUE TITLE
Unable to find docutils.conf

### ISSUE THREAD

**Issue by alejandrovr** [sphinx-doc/sphinx#3916]
I got this error:

```
/../miniconda3/lib/python3.5/site-packages/Sphinx-1.6.2-py3.5.egg/sphinx/environment/__init__.py:684: RemovedInSphinx17Warning: html_use_smartypants option is deprecated. Smart quotes are on by default; if you want to disable or customize them, use the smart_quotes option in docutils.conf.
  RemovedInSphinx17Warning)
```

I tried to locate the docutils.conf file, but it seems like it does not exist on my computer. Is there any other aproach to disable the smart_quotes option?

Thanks in advance,

Alejandro.

**Comment by tk0miya** [comment]
Please create it as a new file named `docutils.conf` on the same directory as `conf.py`.

Thanks,

**Comment by jfbu** [comment]
Closing because [previous comment](https://github.com/sphinx-doc/sphinx/issues/3916#issuecomment-315581754) appears to answer question.
