### ISSUE TITLE
How to prevent items from showing in the nav?

### ISSUE THREAD

**Issue by juanshishido** [sphinx-doc/sphinx#3925]
Subject: How to prevent items from showing in the nav?

### Problem
- This isn't a specific problem. It's a question about functionality and how to achieve a desired result. I am interested in listed certain links *on* the page I'm working on. I **can** achieve that now using the following:

```
.. toctree::
   :glob:

   path/to/**
```

This is great. However, I would like to to *exclude* those items from showing up in the nav.

Is there a way to do this? It doesn't have to involve using `toctree`.

Thanks!

**Comment by timhoffm** [comment]
This is currently not possible, but discussed in #9969. Thus, I think we can close this as duplicate.
