### ISSUE TITLE
Feature Request: UPDATE text field on an RT index

### ISSUE THREAD

**Issue by nunoperalta** [sphinx-doc/sphinx#3935]
### Problem
It is really messy that I can't do an UPDATE on an index when I need to update a text field.

I understand Sphinx design might not permit that, but it would be really nice if we were able to use UPDATE, even if in the background Sphinx does a DELETE and re-INSERT with the new edits.

#### Why is this a problem
Say I am indexing a few fields and attributes of a given Post in my website, and some attributes are derived from values of different other tables (e.g. derived from the Category of the Post and the User who posted).

If the user edits the Post (fixing a typo), the process will update the database, and then update Sphinx.
However, the update on Sphinx will not be as simple as an "UPDATE index SET message = 'new message' WHERE id = 123". Unfortunately, I will have to query the whole thing again in order to build a REPLACE/INSERT statement.

This causes a bit of code junk/disorganization in the client side.

### Environment info
- OS: Linux
- Python version: (latest)
- Sphinx version: 2.2.11

**Comment by tk0miya** [comment]
Do you mention about sphinx the search engine?
This is a repository for sphinx the documentation tool.
http://www.sphinx-doc.org/en/stable/

Thanks,
