### ISSUE TITLE
Arguments parenthesis

### ISSUE THREAD

**Issue by abuesol08** [sphinx-doc/sphinx#3941]
Hi there,

I have created a custom domain starting from the JavaScript one. My question is: How can you get rid of the automatic parenthesis that appear to enclose the arguments of any method/function for which "has_arguments" is true?

For example, suppose I want this particular formatting for a command:

**Command:** **model_comparison**_(marginal_density = a | b) FILENAME[(DOUBLE)]…;_

For this command, I want to have everything after "model_comparison" formatted as argument. I am able to do that by coding as follows:

```
class RandomObject(ObjectDescription):
    has_arguments = True
    display_prefix = "Command: "
    allow_nesting = False   

    def handle_signature(self, sig, signode):
        sig = sig.strip()
        if '(' in sig:
            member, arglist = sig.split('(', 1)
            member = member.strip()
            arglist = arglist.strip()
```

...but then in the output file I get:

**Command:** **model_comparison**_(marginal_density = laplace | modifiedharmonicmean) FILENAME[(DOUBLE)]…;)_

...that is, with extra parenthesis that I don't need.

Moreover, if the command is 
**dsample** _INTEGER [INTEGER];_ 
the output reads 
**dsample** _(INTEGER [INTEGER];)_

It is probably easy to remove, but I am just starting to work with Sphinx and my Python is also a bit rusty :)

Thanks in advance!

**Comment by tk0miya** [comment]
When `has_arguments = True`, the `JSObject` inserts `desc_parameterlist` node into the signature node. And it is rendered as parenthesis. So you need to add your nodes inside parens as children of the `desc_parameterlist` node.

It seems it's too late to answer. I don't know this is still needed for you. Please let me know if you still in trouble.

Thanks,
