### ISSUE TITLE
Autodoc silently fails on triple-parent import

### ISSUE THREAD

**Issue by pkgw** [sphinx-doc/sphinx#3943]
Subject: Autodoc silently fails on triple-parent import

### Problem

I have a project where autodoc was failing to document certain class members. I have traced the problem to a silent failure in the pgen2 code parser.

#### Procedure to reproduce the problem

Try to use autodoc on a file that is three levels deep inside a package that has an import from the top of the package. Example layout:

```
package/__init__.py
package/outer.py
package/sub1/__init__.py
package/sub1/sub2/__init__.py
package/sub2/sub2/inner.py
```

And then `inner.py` looks like:

```
from ...outer import symbol

class MyClass(object):
   foo = 12345
   "Docstring."
```

And then RST file looks like:

```
.. autoclass:: package.sub1.sub2.MyClass
   .. autoattribute:: foo
```

#### Error logs / results

The docstring on "foo" does not appear.

If I run `sphinx-build -vvv ....`, I see the following output:

```
[autodoc] import pwkit.environments.casa.dftdynspec
[autodoc] => <module 'pwkit.environments.casa.dftdynspec' from '/home/peter/sw/pwkit/pwkit/environments/casa/dftdynspec.py'>
[autodoc] module analyzer failed: parsing failed (exception was: ParseError("bad input: type=1, value='astutil', context=('', (23, 8))",))
```

where `astutil` is the equivalent of `outer` in my streamlined example.

#### Expected results

The docstring on "foo" should appear properly.

Sphinx should report that the detailed parse of the file failed!!! It needn't be fatal error but I wasted a lot of time because it was hidden from me that `pgen2` was not able to handle my file. This can also be seen in #1641, which I have *also* run into and wasted a lot of time trying to figure out what was going on.

### Reproducible project / your project

[Here's my project](https://github.com/pkgw/pwkit/commit/eed57209e67c860591bfe502cca3d6ce9d1da1fe).

### Environment info

- OS: Linux (Fedora 25)
- Python version: 3.6.1
- Sphinx version: 1.6.3

### Side note

I haven't looked into it too much but this might be limited to triple-parent imports. Maybe there's a problem where the parser decides that the periods represent an ellipsis token?

### Workaround

**If** you can figure out that this is what's going on, you can work around the problem by just inserting a space between some of the periods in the relative import line. As with #1641, it would be really nice to see this get fixed for real though, since it's a finicky and extremely non-obvious workaround. Also as with #1641, in my opinion the best first step would be some communication to the user that autodoc parsing has failed, though.

**Comment by tk0miya** [comment]
Now I'm going to replace pgen2 by new parser: #3937
Could you try it instead?

**Comment by tk0miya** [comment]
I think this is already fixed at current master. So I close this now.
Please let me know if you still get same error.

Thanks,
