### ISSUE TITLE
Feature Request: Automatic tread dection for multithreaded builds

### ISSUE THREAD

**Issue by Blendify** [sphinx-doc/sphinx#3947]
Subject: Feature Request

### Problem
- Multithreaded builds should allow users to let sphinx pick the number of threads it should use.

#### Procedure to reproduce the problem
```
sphinx-build -b html -j 0
```

#### Expected results
`-j 0` should choose the best number of threads for the system.

### Reproducible project 
Any project.

### Environment info
- OS: Windows 10
- Python version: 3.6
- Sphinx version: 1.6.2

**Comment by tk0miya** [comment]
+1; We always welcome your PRs!

**Comment by Blendify** [comment]
I will give it a try. Can you tell me where in the threading happens?

**Comment by tk0miya** [comment]
Fixed by #4271 
Thank you for proposal
