### ISSUE TITLE
Release process: fetching translations from transifex

### ISSUE THREAD

**Issue by JulienPalard** [sphinx-doc/sphinx#3958]
Subject: I spotted that translations where not pulled from transifex in the latest releases.

### Problem

The translation fix discussed in https://github.com/sphinx-doc/sphinx/pull/3801 where not pulled in the last two releases.

#### Expected results

I expected the translations to be pulled before the release process so the translation fixes would be available.

**Comment by tk0miya** [comment]
@shimizukawa is there any reason not to update i18n messages on our release process?
https://github.com/sphinx-doc/sphinx/blob/1.6.3/utils/release-checklist#L12

If none, I will do this step on every release.

**Comment by shimizukawa** [comment]
The i18n files have been updated only before the major release. If applying the i18n files to the stable release, it may be somewhat problematic because the master's i18n messages do not always apply to stable.

**Comment by tk0miya** [comment]
Ah, you're right. The message catalog on transifex is already moved to master branch. So some messages might be removed or changed.

@JulienPalard Could you make a pull request to change the message file (.po) for stable branch? I will merge it.

**Comment by tk0miya** [comment]
now #3964 is merged.
