### ISSUE TITLE
inheritance diagram should support rename/alias

### ISSUE THREAD

**Issue by gaborbernat** [sphinx-doc/sphinx#3959]
Often there can be a discrepancy between what's the fully qualified name of a class and how it's exposed. For example, the PyTest module has it's code in _pytest package, but enumerates and exposes stuff in a pytest.py module (which loads the relevant classes from _pytest). Exposing at a different entry point is possible via tools such as autodoc, by just using the appropriate path (so e.g. pytest.Magic instead of _pytest.code.Magic). Autodoc e.g. also generates this aliased links/references for these classes (so the inheritance diagram links will be broken upon using this feature of autodoc). 

In such cases we should offer some kind of way so that the user can build an inheritance without exposing the underlying actual path (so e.g. can set that _pytest.code.Magic is actually pytest.Magic, and _pytest.magic.BaseMagic is pytest.BaseMagic). Classes not overwritten can keep their fully qualified name. 

Does that make sense?

I believe the appropriate aliasing could be done here https://github.com/sphinx-doc/sphinx/blob/master/sphinx/ext/inheritance_diagram.py#L216 by using a configuration value map to specify what alter to what (allowing the user to define in the conf.py what alias to use for what fully qualified name).

**Comment by tk0miya** [comment]
+1 that's sound good. It would be nice if you make pull request for this :-)

**Comment by gaborbernat** [comment]
will do :wink:
