### ISSUE TITLE
Sphinx-apidoc does not recognize implicit namespace packages correctly

### ISSUE THREAD

**Issue by hoefling** [sphinx-doc/sphinx#3962]
### Problem
In a project structured according to PyPA's [tutorial](https://packaging.python.org/tutorials/distributing-packages/), if a source package is a namespace package and passed as input to ``sphinx-apidoc``, it is treated as a regular dir containing "real" python packages.

#### Procedure to reproduce the problem
Reproducible using the PyPA's official example for implicit namespace packages:
```
$ git clone https://github.com/pypa/sample-namespace-packages.git
$ cd sample-namespace-packages/native/pkg_a/
$ sphinx-apidoc --output-dir=apidoc --implicit-namespaces example_pkg
```

#### Error logs / results
Sphinx log:
```
Creating file apidoc/a.rst.
Creating file apidoc/modules.rst.
```
Contents of ``apidoc/modules.rst``:
```
example_pkg
===========

.. toctree::
   :maxdepth: 4

   a
```

Contents of ``apidoc/a.rst``:
```
a package
=========

Module contents
---------------

.. automodule:: a
    :members:
    :undoc-members:
    :show-inheritance:
```

#### Expected results
Module ``a`` should be ``example_pkg.a``.

### Reproducible project / your project
- https://github.com/pypa/sample-namespace-packages

### Environment info
- OS: Linux
- Python version: 3.5.3
- Sphinx version: 1.6.3

**Comment by hoefling** [comment]
Right now, I install Sphinx in a virtual environment and use the following patch to avoid this issue:

```
diff --git a/sphinx/apidoc.py b/sphinx/apidoc.py
index b9a445c9..048f59c4 100644
--- a/sphinx/apidoc.py
+++ b/sphinx/apidoc.py
@@ -205,12 +205,7 @@ def recurse_tree(rootpath, excludes, opts):
     Look for every file in the directory tree and create the corresponding
     ReST files.
     """
-    # check if the base directory is a package and get its name
-    if INITPY in os.listdir(rootpath):
-        root_package = rootpath.split(path.sep)[-1]
-    else:
-        # otherwise, the base is a directory with packages
-        root_package = None
+    root_package = rootpath.split(path.sep)[-1]

     toplevels = []
     followlinks = getattr(opts, 'followlinks', False)
```

**Comment by tk0miya** [comment]
Now I made PR #3963. It will be resolve this. Please check it :-)

**Comment by tk0miya** [comment]
note: PR is updated as #3966

**Comment by hoefling** [comment]
Yay, that was fast, thanks a lot! Waiting for 1.6.4 to be released now... :-)
