### ISSUE TITLE
Some domain values doesn't create a link

### ISSUE THREAD

**Issue by YuriPetrov** [sphinx-doc/sphinx#3970]
Subject: Some domain values doesn't create a link

### Problem
Some domain values doesn't create a link, for example for ``if`` or ``while`` statements

#### Procedure to reproduce the problem
```
.. py:data:: if
```
#### Expected results
Domain with link

### Environment info
- OS: Win
- Python version: 3.5
- Sphinx version: 1.6.2

**Comment by tk0miya** [comment]
Hmm? out document says `py:data` is a global data in a module, not statement. Your expectation is a bit strange for me.

>Describes global data in a module, including both variables and values used as “defined constants.” Class and object attributes are not documented using this environment.

**Comment by YuriPetrov** [comment]
Is there any chance I can do it with a statement?

**Comment by tk0miya** [comment]
Never. these preserved keywords are not data. So `py:data` never support them.

How about using `:keyword:` instead?
http://www.sphinx-doc.org/en/stable/markup/inline.html#role-keyword

The python-doc uses it to create links:
https://raw.githubusercontent.com/python/cpython/3.6/Doc/reference/compound_stmts.rst

**Comment by YuriPetrov** [comment]
Thanks!
