### ISSUE TITLE
typo in autosummary.rst

### ISSUE THREAD

**Issue by AlanJayWeiner** [sphinx-doc/sphinx#3978]
I'd fix it, but it seems silly to fork, fix, and then request a pull just to fix one letter in documentation...

At the end of doc/ext/autosummary.rst, there is a line that says "...prevents asterisks making things bolt."

"bolt" should be "bold"

**Comment by TimKam** [comment]
@AlanJayWeiner To fix such small things, you can simply edit the text directly in GitHub's web UI. The system then creates a PR for you and the maintainers merely need to click the _merge_ button.

**Comment by AlanJayWeiner** [comment]
@TimKam - saw your message in my email; went ahead and did that (for some reason it hadn't worked yesterday - maybe I hadn't logged in...  dunno)
So you'll get the pull request.

*Then* came to this thread and saw you already fixed it.   So you can ignore my PR.

**Comment by TimKam** [comment]
Sorry for not mentioning in the message that I added a PR. Can you close yours? To avoid confusing the maintainers.

**Comment by AlanJayWeiner** [comment]
ok - just did.
