### ISSUE TITLE
The sphinx linux kernel documentation not in the list of projects using sphinx

### ISSUE THREAD

**Issue by pvergain** [sphinx-doc/sphinx#3979]
Subject: Sphinx linux kernel documentation not in the list of projects using sphinx

### Problem
- The sphinx linux doumentation should be in http://www.sphinx-doc.org/en/stable/examples.html

#### Procedure to reproduce the problem
Go to  http://www.sphinx-doc.org/en/stable/examples.html and search https://www.kernel.org/doc/html/latest/index.html.

linux kernel not found

**Comment by tk0miya** [comment]
Could you make PR please?

**Comment by tk0miya** [comment]
Are sorry. I'd overlooked #3979. Finally merged.
Thank you @TimKam !
