### ISSUE TITLE
inconsistent term references in translated message: not on every cases

### ISSUE THREAD

**Issue by JulienPalard** [sphinx-doc/sphinx#3985]
Subject: On some specific translations, some references are hard to keep, or it may be usefull to duplicate them, a way to mute a warning locally should be provided.

### Problem

- We're getting some hard to fix "inconsistent term references in translated message".

#### Procedure to reproduce the problem

In a `.po` file, translate a paragraph containing term references, but remove or add one.

#### Error logs / results
```
WARNING: inconsistent term references in translated message
```

#### Expected results

It *is* expected to have this WARNING, and it's nice, it helps to spot translation errors, but sometimes we'd like to disable it for a specific paragraph.

Possible fixes I see are:

- Allow a `po` translator comment to disable those warnings, like `noqa`
- Don't warn if the references are present in the translation, just not the right number of them

I think the second fix is enough for our cases, typically the sentence:

    Foo :ref:`a` bar :ref:`a` baz :ref:`b`.

When translated as:

    Lorem :ref:`b` ipsum :ref:`a`.

currently warns, (invalid "number" of references) but all references are here, and maybe the redundency in not necessary in the translated message.

### Reproducible project / your project

- https://github.com/python/python-docs-fr/pull/15

### Environment info

- OS: Debian buster
- Python version: 3.5.3
- Sphinx version: 1.6.1

**Comment by entwanne** [comment]
For example, the documentation of Python `datetime` module says "comparison of `time` to `time`", it is more convenient in French to say "comparaison entre deux `time`" than repeating the term "time".

**Comment by humitos** [comment]
Hi! I just wanted to chime in here to say that the feature as it is right now helped us a lot to find malformed references:

* space between the role's name and the colon
* missing backtick
* etc

If I could vote, I'd like to have something like @JulienPalard's mentioned to be able to disable only in one paragraph.

**Comment by jeanas** [comment]
What would be good syntax for this "disable" marker? Maybe a one-element field list: `:noqa: Translated paragraph text ...`?

I wish it could be put in translator comments, but as far as my understanding of the Gettext world goes, they're not reflected in mo files. A pity.
