### ISSUE TITLE
WARNING: image file not readable, case issue?

### ISSUE THREAD

**Issue by ArtFlag** [sphinx-doc/sphinx#3989]
### Problem
I can successfully build the output locally, but when I push my code to Github and build it via Travis, I get warnings for *some* of the images used in this page. 

I call all of them with the following directive:

```
.. image:: _images/ef1b53.png
   :align: center
```

#### Error logs / results
```
WARNING: image file not readable: _images/blabla.png
...
```

#### Expected results
No warning at all, since it works locally.

### Environment info
- OS (local): Mac Sierra
- OS (remote): Ubuntu 14.04 (Travis'  trusty image)
- Python version (both env): 2.7.13  
- Sphinx version (both env): 1.6.3

### Root cause
So, after trying to fix the issue, I found the real cause of the issue.

If you have case mismatch between the parameter of the  `.. image` directive and the filename (in my case I had an all-caps image name as parameter while my image file was lower case) then you get the warning `image file not readable`.

I didn't get the problem locally, probably because I'm using Mac OS, but the Ubuntu distribution on Travis couldn't handle the case difference... At least that's my idea...

### Solution (if relevant)
Could we make the image search case-insensitive?

Thanks!

**Comment by tk0miya** [comment]
-1: I believe case-sensitive is common law of UNIX. Adding case-insensitive is boring and not worthy for most of users.

**Comment by ArtFlag** [comment]
Fair enough, but this has to be documented to avoid users wasting time on this issue. 

Can I just edit the `image` directive page or do I have to submit a PR from my fork?
