### ISSUE TITLE
avoid to reread all on error

### ISSUE THREAD

**Issue by jschueller** [sphinx-doc/sphinx#3990]
when sphinx encounters an error, it rereads all the source files the next time it's started, and for a large project this can be long (>2/3min)

Is there an option to avoid rereading all the files on error ?

That would allow for example to fix the error in the corresponding file and go to the next error right away :)

**Comment by tk0miya** [comment]
No, we don't have such option. Sphinx always clears intermediate files on errors. I think it is hard to keep consistent builds after errors. So I'd not like to provide such option.

**Comment by jschueller** [comment]
I understand, and if I want to hack my own sphinx, where should I look ?

**Comment by tk0miya** [comment]
Sorry for late response. In `sphinx.application:Sphinx.build()`, Sphinx removes envfile on errors.

**Comment by jschueller** [comment]
cool, thanks

**Comment by jschueller** [comment]
comment out the unlink line:
```
except Exception as err:
            # delete the saved env to force a fresh build next time
            envfile = path.join(self.doctreedir, ENV_PICKLE_FILENAME)
            #if path.isfile(envfile):
            #    os.unlink(envfile)
            self.emit('build-finished', err)
            raise
```
