### ISSUE TITLE
Page source shown with wrong encoding

### ISSUE THREAD

**Issue by lelit** [sphinx-doc/sphinx#3992]
Subject: when I view the reStructuredText source of a page, the browser shows it with the wrong encoding.

### Problem
See for example [this page](http://pg-query.readthedocs.io/en/latest/index.html) and [its related source](http://pg-query.readthedocs.io/en/latest/_sources/index.rst.txt): the former is shown with a `utf-8` encoding and the ©️ glyph at the bottom appears correct, while the latter uses `windows-1252` and thus the ©️ glyph in the header does not look good.

This is **not** related to RtD, as I observe the very same behaviour using latest Sphinx on my local machine (that by the way is a GNU/Linux system, with a `it_IT.UTF-8` environment).

### Environment info
- OS: GNU/Linux, Debian `sid`
- Python version: 3.6.2
- Sphinx version: 1.6.3 (but RtD currently uses 1.5.3)

**Comment by tk0miya** [comment]
Sphinx only copies your source code. So this is a problem of encoding-detection feature of browsers.
I think sending `Content-type` header with charset params (like `Content-type: text/plain; charset=UTF-8`) will resolve this problem.

**Comment by lelit** [comment]
That seems effectively the case, and indeed I can reproduce the problem with Firefox and not, for example, with Chromium. Loading the source file directly from the filesystem (that is, `firefox _build/html/_sources/foo.rst.txt`) exhibits the issue.
Thank you!
