### ISSUE TITLE
Possibly wrong options in documentation of setuptools integration

### ISSUE THREAD

**Issue by padix-key** [sphinx-doc/sphinx#3996]
Subject: Some options given at http://www.sphinx-doc.org/en/stable/setuptools.html do not work

### Problem

The options containing a hypen (e.g. 'source-dir') not work when using them in 'command_options' in setup.py.
However, when replacing the hypen with an underscore, it works fine (e.g. 'source_dir').

#### Error logs / results

error in setup.py: command 'BuildDoc' has no such option 'source-dir'

**Comment by TimKam** [comment]
These options work fine if they are provided as command line arguments or in a ``setup.cfg`` file.
I'll add a note to the docs that in case of providing the option directly in the setup command, one has to replace hyphens in variable names with underscores.
