### ISSUE TITLE
Section numbering in plain text output

### ISSUE THREAD

**Issue by spwhitton** [sphinx-doc/sphinx#3998]
In our HTML output, Sphinx is numbering sections and subsections.  It does not do this in our plain text output.

Since we are getting section numbers in one output format, I believe we're not missing some option that would turn numbering on in plain text.  So I believe this is a missing feature -- it would be great to see it in a future version of Sphinx.

Thanks!

**Comment by tk0miya** [comment]
Fixed by #4218 
Thank you for reporting!
