### ISSUE TITLE
some web site house cleaning

### ISSUE THREAD

**Issue by cs5102** [sphinx-doc/sphinx#4017]
Subject: bad links on www.sphinx-doc.org/en/stable/examples.html page 

### Problem
The following links had trouble (these are not necessarily in the order they appear on the page):

Site can't be reached (timed out):

openWNS: http://docs.openwns.org/
Djagios: http://djagios.org/
GetFEM++: http://home.gna.org/getfem/
Pyre: http://docs.danse.us/pyre/sphinx/
Istihza (Turkish Python documentation project): http://belgeler.istihza.com/py2/
NoTex: https://www.notex.ch/overview/
Tablib: http://tablib.org/

The domain here is for sale or not in use:

lunarsite: http://lunaryorn.de/
VOR: http://www.vor-cycling.be/
Glashammer: http://glashammer.org/

404 error:

UC Berkeley Advanced Control Systems course: http://msc.berkeley.edu/tomizuka/me233spring13/
Blinker: http://discorporate.us/projects/Blinker/docs/
WFront: http://discorporate.us/projects/WFront/
Google or-tools: https://or-tools.googlecode.com/svn/trunk/documentation/user_manual/index.html
Setuptools: http://pythonhosted.org/setuptools/
sqlparse: http://python-sqlparse.googlecode.com/svn/docs/api/index.html

I hope that's of some use.

Cheers

**Comment by shimizukawa** [comment]
Thanks!
I've confirmed almost you mentioned has gone. However one site is still there.

- Pyre: http://docs.danse.us/pyre/sphinx/

And two famous tools was moved on RTD.

- Setuptools
- sqlparse

Others has been removed on 63c1599.
