### ISSUE TITLE
html_file_suffix for htmlhelp output

### ISSUE THREAD

**Issue by timworthington** [sphinx-doc/sphinx#4018]
Currently html_file_suffix affects _html_ output, but the file suffix for the _htmlhelp_ output is always '.html' regardless. 

I think this is a bug because the docs state _"Options for HTML output. These options influence HTML as well as HTML Help output, and other builders that use Sphinx’s HTMLWriter class."_

I am currently porting a program's context sensitive help system from HTML Help to Sphinx (HTML Help output). The program accesses the files inside the CHM file directly with the HH_DISPLAY_TOPIC command. The trouble is the original file names had a '.htm' extension and the new Sphinx generated files are '.html'.

**Comment by tk0miya** [comment]
Certainly, htmlhelp builder does not refer it since its beginning.
https://github.com/sphinx-doc/sphinx/blob/1.6.3/sphinx/builders/htmlhelp.py#L196
I don't know why it always use `.html`. But it seems that is intentional.
Does it also work fine with other (short) extensions? If so, there are no reason to refer the configuration.

**Comment by timworthington** [comment]
The HH_DISPLAY_TOPIC command requires the exact file name to be specified (inside the CHM archive). 
https://msdn.microsoft.com/en-us/library/windows/desktop/ms670084.aspx

The MSDN example is accessing 'intro.htm'. If this help file was built with Sphinx then HTML Help would not be able to locate the file because 'intro.rst' was output as 'intro.html'. I think '.html' is a good default, but sometimes it is necessary to use '.htm' if compatibility with (unmodified) old software help API is desired.
