### ISSUE TITLE
[cpp domain] Default template arguments are not parsed correctly.

### ISSUE THREAD

**Issue by twesterhout** [sphinx-doc/sphinx#4025]
__In short:__ Sphinx fails to parse a valid `C++` code-code block and no syntax highlighting is thus provided.

__A longer description:__
Here's a piece of valid `C++` code:
```cpp
template <class View, class Predicate, class = std::enable_if_t<
    boost::static_views::concepts::View::test<View>()>>
constexpr auto operator()(View const& xs, Predicate&& p) const;
```
If included using `code-block` like this
```rst
.. code-block:: cpp

  template <class View, class Predicate, class = std::enable_if_t<
      boost::static_views::concepts::View::test<View>()>>
  constexpr auto operator()(View const& xs, Predicate&& p) const;
```
Sphinx fails to parse it and produces the following warning:
```
WARNING: Could not lex literal_block as "cpp". Highlighting skipped.
```
The problem seems to lie in the use of `class = std::enable_if_t<...` without a name. If `class Dummy = std::enable_if_t<...` is used instead, no warning is generated and everything works as expected.

__Environment info:__
- OS: Linux
- Python version: `python3 --version` gives `Python 3.4.2`
- Sphinx version: `git status` says `Your branch is up-to-date with 'origin/stable'.`

**Comment by jakobandersen** [comment]
Thanks for the bug report. The ``code-block`` directive doesn't actually use the C++ domain but is only doing syntax highlighting (via Pygments I think). 
Using the C++ domain would be something like the following (probably nested inside some ``cpp:class`` directive):
```rst
 .. cpp:function:: template<class View, \
                            class Predicate, \
                            class = std::enable_if_t< \
                               boost::static_views::concepts::View::test<View>()>> \
    constexpr auto operator()(View const& xs, Predicate&& p) const
```
This will declare the member function and make hyperlinks to other declarations.

**Comment by twesterhout** [comment]
Right, sorry for incorrect wording! I had a complete function implementation in my `code-block`, but left it out to simplify the example. Let me know if I can help in some way.

**Comment by jakobandersen** [comment]
I double-checked and indeed ``code-block`` is using Pygments and running the code through the command line tool reproduces the problem. The best would be if you can submit a bug report over there (https://bitbucket.org/birkenfeld/pygments-main).
