### ISSUE TITLE
autosummary: Allow customizing template environment

### ISSUE THREAD

**Issue by flying-sheep** [sphinx-doc/sphinx#4030]
the autosummary extension uses [this code](https://github.com/sphinx-doc/sphinx/blob/cb0220de1a0d8acd00292b898d2ef03b588179b0/sphinx/ext/autosummary/generate.py#L130-L144) to create a jinja template environment.

there is no room for customization via conf.py, and users will have to modify e.g. `jinja2.defaults.DEFAULT_FILTERS` if they want to add filters for autosummary pages.

it would be useful to have customization options like `html_context`, e.g. for usage like this: rtfd/readthedocs-sphinx-ext#28

**Comment by tk0miya** [comment]
+1: Reasonable.

**Comment by tk0miya** [comment]
@flying-sheep Do you still need such a feature? If true, I'll add `autosummary_context` to add template variables for templates of autosummary.

**Comment by flying-sheep** [comment]
Yes, It would be cleaner to do it that way for sure!

**Comment by tk0miya** [comment]
Okay, I'll post a PR later.

**Comment by flying-sheep** [comment]
Great, thank you!
