### ISSUE TITLE
graphviz: Node with image="blah.png" doesn't render via sphinx (but ok in dot)

### ISSUE THREAD

**Issue by ghost** [sphinx-doc/sphinx#4033]
Using dot, I can use a png image as a graphviz node, e.g in a .dot file containing
`graph { mynode [image="myimage.png"]}` and `dot -Tpng -O <file>` (or `-Tsvg`)
Resulting png/svg includes the image, sphinx's (latex or html) output doesn't. All other sphinx-generated graphviz stuff renders fine.

I tried adding graphviz_dot_args = ['-v'] to get some clues from the logs but no joy there either (doesn't seem to use the supplied option).

**Comment by tk0miya** [comment]
In my short investigation:

* We need to parse dot files to know the path of images
* We have to rewrite the dot code if the graph depends on images in different directories (only same directory is allowed).

I think that is a bit tough work...

**Comment by tk0miya** [comment]
Fixed by #5156!
Thank you for reporting :-)
