### ISSUE TITLE
Incorrect links with :download:, duplicate names, and parallel builds

### ISSUE THREAD

**Issue by bluekeyes** [sphinx-doc/sphinx#4034]
### Problem

When building documentation in parallel (with the `-j` flag), using the `:download:` role to link to files with duplicate names can result in incorrect links in the output.

I believe this is because the [`DownloadFileCollector`](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/environment/collectors/asset.py#L137) rewrites link targets on name conflict, but [`FilenameUniqDict#merge_other`](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/util/__init__.py#L153) (which is used to implement the `env-merge-info` hook) can change the filenames again without updating the link nodes.

#### Procedure to reproduce the problem

The shell script below generates a minimal project with the correct properties, but any project with links to files with the same name from multiple documents should reproduce the problem. Run `sphinx-build` with the `-j` flag:

```
sphinx-build -b html -j4 "." "_build" 
```

#### Expected results

In the example project, the link on each of the 20 pages should lead to a matching file, e.g. "File 1" should lead to a file containing the text `File 1`, "File 2" should lead to a file containing the text `File 2`, etc.

Instead, the linked files are mixed up and the content does not match the origin page.

### Reproducible project

Run the following shell script in an empty directory to generate a test project:

```bash
#!/bin/bash
set -e

cat > conf.py <<EOF
exclude_patterns = ['_build']
master_doc = 'index'
project = u'sphinx-download-bug'
source_suffix = '.rst'
EOF

cat > index.rst <<EOF
Welcome to sphinx-download-bug's documentation!
===============================================

.. toctree::
EOF

for i in {1..20}; do
    mkdir -p files/$i

    echo "File $i" > files/$i/file.txt
    cat > $i.rst <<EOF
File $i
#######

Download :download:\`File $i <files/$i/file.txt>\`
EOF
    
    echo "   $i" >> index.rst
done
```

### Environment info

- OS: Ubuntu 16.04
- Python version: 2.7.12 
- Sphinx version: 1.6.3

**Comment by tk0miya** [comment]
Fixed by #5377.
Thank you for reporting!
