### ISSUE TITLE
viewcode does not abide by viewcode_import

### ISSUE THREAD

**Issue by AWhetter** [sphinx-doc/sphinx#4035]
### Problem
- With the `viewcode` extension loaded, and `viewcode_import` set to `False`, `viewcode` will still attempt to load documented modules. This is because it uses `sphinx.pycode.ModuleAnalyzer.for_module` (https://github.com/sphinx-doc/sphinx/blob/cb0220de1a0d8acd00292b898d2ef03b588179b0/sphinx/ext/viewcode.py#L66), which uses `sphinx.util.get_module_source()`, which attempts to import the module. 

#### Procedure to reproduce the problem
```
sphinx-build source build
```
with the `viewcode` extension loaded, and `viewcode_import` set to `False`

#### Expected results
Ideally, there would be an option to `viewcode` that let's you specify source directories, and it would use these to find source code, falling back to `ModuleAnalyzer` only if `viewcode_import` is True.

You could also attempt to make `sphinx.util.get_module_source()` optionally attempt to get the source without loading the module. This would likely require using something like `pkgutil.get_loader()` but would add a dependency. Plus handing eggs could be difficult because the code exists in an egg, rather than on disk, ready to read. Overall the implementation of this method would be a lot more messy.

### Reproducible project / your project
I don't have a sample project but a simple test case would be to define a module in the python path with:
```
raise RuntimeError()

class MyClass(object):
    """This is my class."""
```

and to document the class in an rst file. The sphinx config would use `viewcode` and set `viewcode_import` to `False`.

### Environment info
- OS: Linux
- Python version: 2.7.3
- Sphinx version: 1.6.3

**Comment by shimizukawa** [comment]
> - With the `viewcode` extension loaded, and `viewcode_import` set to `False`, `viewcode` will still attempt to load documented modules. 

The `viewcode_import` option means:
```
If this is ``True``, viewcode extension will follow alias objects that
imported from another module such as functions, classes and attributes.
```
So, "loading documented modules by viewcode extension even if viewcode_import is False" is intended behavior. The config name `viewcode_import` is not nice. From the viewpoint of behavior, it seems better to call `viewcode_follow_imported_members`.
