### ISSUE TITLE
C domain cross-reference documentation lacks the "member" role 

### ISSUE THREAD

**Issue by jnikula** [sphinx-doc/sphinx#4038]
The documentation for cross-referencing C domain constructs does not describe the "member" role: http://www.sphinx-doc.org/en/stable/domains.html#cross-referencing-c-constructs although it certainly does work and it's alluded to in the documentation for c:member directive http://www.sphinx-doc.org/en/stable/domains.html#directive-c:member in the paragraph above: "References to structure members in text should use the member role."

**Comment by jakobandersen** [comment]
Thanks, fixed in stable.
