### ISSUE TITLE
'WARNING: cpp:typeOrConcept targets a member' reported for a structure

### ISSUE THREAD

**Issue by krzychb** [sphinx-doc/sphinx#4041]
### Problem

A `cpp:typeOrConcept targets a member` warning is reported when documenting a structure with variable definition, e.g. `sample_integer`, that is also used as a function parameter declared within the same structure.

Example of documented structure:

```c
/**
* Description of sample_structure
*
*/
typedef struct {
    int sample_integer;  /*!< Description of sample_integer */
    void (*sample_function)(int sample_integer); /*!< Description of sample_function */
} sample_structure;
```

#### Procedure to reproduce the problem

Build documentation using Spxinx + Doxygen + Breathe for above structure including members:

```
.. doxygenstruct:: sample_structure
    :members:
```

#### Error logs / results
```
C:/msys32/home/krzysztof/esp/rtd-test-bed/docs/case-type-or-concept.rst:11: WARNING: cpp:typeOrConcept targets a member (sample_structure::sample_integer).
```
- Build logs on Read The Docs site: http://readthedocs.org/projects/rtd-test-bed/builds/5932722/

#### Expected results
- No any warning reported. 

This warning is distinctive from other legitimate warnings. It makes it difficult to implement failure of documentation build on legitimate warnings.

### Reproducible project / your project
- http://rtd-test-bed.readthedocs.io/en/latest/case-type-or-concept.html

Similar warning has been documented in https://github.com/sphinx-doc/sphinx/pull/3894

### Environment info
- OS: Ubuntu 16.04 / Windows 7 + MSYS2
- Python version: 2.7.13
- Sphinx version: 1.6.3
- Breathe version: 4.7.0

**Comment by jakobandersen** [comment]
Thanks for reporting! It should be fixed in stable now. (Note, with #3894 the warning even becomes a hard assertion failure)

**Comment by krzychb** [comment]
@jakobandersen, 
This was really impressive turnaround :1st_place_medal:
Thanks a lot for support and resolution of this issue.
It was bugging me for weeks and months and now I can't believe it is resolved!
Krzysztof
