### ISSUE TITLE
Autosummary extension has many deficits for proper using

### ISSUE THREAD

**Issue by maikelmeyers** [sphinx-doc/sphinx#4058]
First to mention is that the bug found in #3900 is not really fixed, because the same applies to using class attributes `{{ attributes }}` in the templates. Autosummary does not find attributes anymore. Also the fix that was done for this in b3e0e29 is maybe not a good solution because `{{ methods }}` now returns also all inherited methods of a class.

Autosummary with it's templates is a really good solution for auto-documenting a library package without the need for any hand-written ResT file except the master-doc. But at the moment the available variables in the templates do not have enough granularity to achieve this. Beside of the available variables:

- members
- functions
- classes
- exceptions
- methods
- attributes

I miss the following variables for having the ability to fully automize the documentation:

- modules
- packages (sub packages)
- module-level variables
- class attributes
- instance attributes
- inherited class attributes
- inherited instance attributes
- methods
- inherited methods
- static methods
- inherited static methods

With this variables it would be possible to walk recursively thru a package with 3 templates (packages.rst, modules.rst and class.rst).  Especially the modules and packages variables would be important for this). And it would give us the full freedom for the layout of a package- module, and class- page. In example I could write my own headers in between the different groups of members inside the summary or in the details section because this variables mirror the granularity which we have with the autodoc directives.

### Environment info

OS: Windows 10
Python version: 2.7
Sphinx version: 1.6.4

**Comment by jorisvandenbossche** [comment]
FYI, I opened a PR to properly fix #3900 (so to make sure also attributes are available again in the autosummary template): https://github.com/sphinx-doc/sphinx/pull/4247

**Comment by tk0miya** [comment]
Fixed by #4247.
Thank you for reporting

**Comment by jorisvandenbossche** [comment]
I am not the original reporter of the issue, but to me it seems that his enhancement request was more broad than what #4247 fixed (expose more variables to autosummary).

**Comment by tk0miya** [comment]
oh, I'd misunderstood. Thanks,

**Comment by TheMagSec** [comment]
I'm working on a recursive auto summary to cover packages, sub-modules and sub-packages.
