### ISSUE TITLE
Most of included image files are only used by websupport

### ISSUE THREAD

**Issue by mitya57** [sphinx-doc/sphinx#4064]
When HTML documentation is built, Sphinx copies all files from `themes/basic/static/` to the build’s `_static` directory.

Out of 11 image files there, 8 are only needed when websupport is in use, which is a very rare case:
- ajax-loader.gif
- comment-bright.png
- comment-close.png
- comment.png
- down.png
- down-pressed.png
- up.png
- up-pressed.png

Please do not copy these files unless websupport is used.

**Comment by tk0miya** [comment]
Fixed by https://github.com/sphinx-doc/sphinxcontrib-websupport/pull/22 . 
Thank you for your work @takuan-osho!!

**Comment by tk0miya** [comment]
OMG, we still have old copies on this repo. Reopening.

**Comment by tk0miya** [comment]
Finally fixed with #5949
