### ISSUE TITLE
transforms/post_transforms/images.py : "Unicode-objects must be encoded before hashing"

### ISSUE THREAD

**Issue by e-roux** [sphinx-doc/sphinx#4073]
Subject: <what happen when you do on which document project>

### Problem
Generation of latex doc with img address containing "&" or ending with '/' drive to exception

Had to change 
```
.. |docs| image:: https://readthedocs.org/projects/lerp/badge/?badge=latest
    :alt: Documentation Status
    :target: https://lerp.readthedocs.io/en/latest/?badge=latest

|docs|
```

to

```
.. |docs| image:: https://readthedocs.org/projects/lerp/badge
    :alt: Documentation Status
    :target: https://lerp.readthedocs.io/en/latest/?badge=latest

|docs|
```

get the project compilation passed

html compilation works!

#### Procedure to reproduce the problem
```
make clean && make -d latex
```

#### Error logs / results
```
Exception occurred:
  File "/Users/manu/Documents/Developpement/python/anaconda3/lib/python3.6/site-packages/Sphinx-1.6.3-py3.6.egg/sphinx/transforms/post_transforms/images.py", line 73, in handle
    basename = sha1(node['uri']).hexdigest()
TypeError: Unicode-objects must be encoded before hashing
```

log available at readthedocs last compilation line
<http://readthedocs.org/projects/lerp/builds/5995089/>

#### Expected results
<Describe what to actually do>

### Reproducible project / your project

The configuration is available here:
https://github.com/gwin-zegal/lerp/tree/master/docs

### Environment info

Reproduced at home with :

- OS: Mac
- Python version: 3.6.1
- Sphinx version: 1.6.3

**Comment by tk0miya** [comment]
Thank you for reporting.
I believe it was fixed by #4062.
Could you check the HEAD of stable branch?

Thanks,
