### ISSUE TITLE
Equation numbers across multiple pages

### ISSUE THREAD

**Issue by hagenw** [sphinx-doc/sphinx#4080]
#1210 introduced the possibility to reference equations across different files, which is very helpful for larger mathematical documentation projects.

One remaining problem is that the numbering of the equation starts with (1) on each of the single pages. That means you can have something like:
"The integral equation [(1)](http://sfstoolbox.org/en/splitup/problem_statement/#equation-single-layer) together with the expanded basis functions [(1)](http://sfstoolbox.org/en/splitup/solution_nfchoa/#equation-G_expansion) ..."
where you have the same name (1) for different equation links.

This does not happen for figures as they are counted consistently across all pages.
For an example of this problem, have a look on this site: http://sfstoolbox.org/en/splitup/solution_nfchoa/#equation-G_expansion
There you can find an equation (1) and a link to equation (1), but that one is on another page.

**Comment by tk0miya** [comment]
Fixed by #4166
