### ISSUE TITLE
Warnings and errors colored the same when building

### ISSUE THREAD

**Issue by mivade** [sphinx-doc/sphinx#4081]
### Problem

Running `make html` (presumably the same behavior occurs for other targets) results in warnings that are colored in red the same as errors. This is a severe usability problem as it requires significantly more attention to determine if there is actually an issue that needs to be addressed or not.

#### Procedure to reproduce the problem
```
make html
```

#### Expected results

Warnings should use a color that is not red (perhaps yellow instead).

### Environment info
- OS: Mac and Linux
- Python version: any
- Sphinx version: 1.6.1, 1.6.2

**Comment by tk0miya** [comment]
Agreed, but we decided not to use yellow to the warnings (see #2599).
I can change the color if there is any other suitable one.

**Comment by shimizukawa** [comment]
How about `brown` ?

**Comment by tk0miya** [comment]
In ASCII colorseq, `brown` is very similar to `yellow`. so I think it is not good for this case.
I think `red` is a bit better.

**Comment by shimizukawa** [comment]
+1
