### ISSUE TITLE
Tests for C++ domain and intersphinx are broken on master branch

### ISSUE THREAD

**Issue by tk0miya** [sphinx-doc/sphinx#4082]
### Problem
- Tests are crashed: https://travis-ci.org/sphinx-doc/sphinx/builds/279200960

#### Error logs / results
- see https://travis-ci.org/sphinx-doc/sphinx/builds/279200960
- At present, the problematic testcases are commented out temporarily (https://github.com/sphinx-doc/sphinx/commit/617bb43cae3c8a620c2e57f84fc6fbe3ed0b4d34)

**Comment by jakobandersen** [comment]
The PR #3894 was applied to stable, but more changes were needed in master. Though, in master now the name ``std`` and all names starting with ``std::`` are ignored for reference resolution (throwing ``NoUri()`` ) so two of the tests are no longer valid. @Andne, can you verify that the intersphinx test is good enough? and potentially add some extra cases not using the ``std`` namespace?
