### ISSUE TITLE
Latex Makefile does not respect latex_additional_files in conf.py

### ISSUE THREAD

**Issue by markkuriekkinen** [sphinx-doc/sphinx#4090]
Subject: if the Sphinx `conf.py` includes additional `tex` files with the setting `latex_additional_files`, compiling PDF with `make latexpdf` fails.

### Problem
- when you run `make latex`, it generates a Makefile in the build directory in order to compile `tex` files to a PDF document
- when you run `make latexpdf`, it also runs the Makefile in the same command, but it uses the Makefile recipe `all-pdf`that tries to compile all `tex` files in the directory to PDFs
- if `conf.py` includes additional `tex` files (for example, because an additional file may define new Latex commands with `\newcommand` and they should be included in the preamble with `\input` so that the RST code may use the new commands everywhere in mathematical notations (`.. math::` or `:math:`)), the additional files are copied to the build directory
- since `make latexpdf` tries to compile also the additional `tex` file to PDF on its own, it fails. The additional file is not a complete Latex document and it is only included in the master `tex` file. Compiling the master `tex` works fine (with `\input` in the preamble)
- `make latexpdf` could be made more aware of the main Latex document and it could compile only that one to PDF instead of files given in `latex_additional_files` in `conf.py`

The [Sphinx documentation](http://www.sphinx-doc.org/en/stable/latex.html#basic-customization) actually suggests that using `latex_additional_files` and `latex_elements` with `'preamble': r'\input{mycommands.tex}'` should work since it is given as an example, but then it fails like described above.

### Environment info
- OS: Ubuntu Linux 16.04
- Python version: 3.5.2
- Sphinx version: 1.6.1

**Comment by jfbu** [comment]
Oops, this is bad problem indeed, and sorry for the [documentation](http://www.sphinx-doc.org/en/stable/latex.html#basic-customization) glitch (my fault; I thought I had illustrated it with a `.sty` file rather).

As workaround, you can use `.tex.txt` extension for example, of course doing then `\input{mycommands.tex.txt}`. The file extension does not matter to LaTeX, you can also use directly `.txt` extension. However this is probably not good for syntax highlighting in your editor. Thus, you may use `.sty` extension. But still with `\input{mycommands.sty}`, not of course `\usepackage{mycommands}`, **except** if you do add a `\ProvidesPackage{mycommands}[2017/01/29 v1.0 My own custom macros]` line in that file.

I admit this is only a work-around. Advantage of it in its `\ProvidesPackage` version is that you can use directly the `@` symbol there, which is not the case of macros loaded via `\input`.

**Comment by markkuriekkinen** [comment]
Thanks for the fast response. The `txt` file extension works fine for me for the time being.

**Comment by tk0miya** [comment]
I think adding notes to our document is better for this case.
It is not unexpected...

**Comment by jfbu** [comment]
@tk0miya I had forgottent about this; is it still time I fixe our docs for 1.6.5?

**Comment by jfbu** [comment]
If there is time before 1.6.5 I can push this to stable:

[mypatch.txt](https://github.com/sphinx-doc/sphinx/files/1404814/mypatch.txt)

**Comment by jfbu** [comment]
Well, I pushed it (witch CHANGES updated) at 5e86c1c93, regarding documentation. Keeping milestone at 1.6.6 as perhaps the underlying core problem can still be addressed.

**Comment by jfbu** [comment]
Sorry, had to fix my fix at 6b4a0123f

**Comment by tk0miya** [comment]
Don't mind, I'll wait you. Please let me know if finished.

**Comment by jfbu** [comment]
@tk0miya it is done now for 1.6.5. I left 1.6.6 milestone so that we can reconsider if needed at core level. Currently I changed only documentation.

**Comment by tk0miya** [comment]
Thanks!
IMO, it is very rare case, so any more code is not needed for this.
(it's okay if you already have some idea. my opinion does not prevent it)
