### ISSUE TITLE
Private members not documented without :undoc-members:

### ISSUE THREAD

**Issue by jwodder** [sphinx-doc/sphinx#4091]
This problem was mentioned in passing at the end of #3969 but was apparently overlooked.

Sphinx version: 1.6.4  
Python version: 3.5.2 (CPython)  
Docutils version: 0.14  
Jinja2 version: 2.9.6

`foo.py`:
```
class Foo:
    """ This is a class. """

    def __init__(self, bar, baz):
        #: This is a public attribute.
        self.bar = bar
        #: This is a private attribute.
        self._baz = baz
```

`index.rst`:
```
===
Foo
===

.. automodule:: foo
    :members:
    :private-members:
    :undoc-members:
```

`conf.py`:
```
import os.path
import sys
sys.path.insert(0, os.path.abspath('.'))

master_doc = 'index'
extensions = ['sphinx.ext.autodoc']
exclude_patterns = ['_build', 'venv']
```

Building with `sphinx-build -b html -W . _build/html` succeeds, and the resulting HTML page shows the documentation for both `bar` and `_baz`.  However, if `:undoc-members:` is removed, the `_baz` entry does not show up in the output despite it being a documented member!  The same behavior also occurs with double-underscore names (`__baz`).

**Comment by tk0miya** [comment]
Fixed by #4368 .
Thank you for reporting!
