### ISSUE TITLE
Sphinx build make mode creates empty directories for unknown targets/builders

### ISSUE THREAD

**Issue by markkuriekkinen** [sphinx-doc/sphinx#4093]
Subject: the new Sphinx build "make mode" creates empty directories under the build directory even when the builder argument refers to a non-existent builder

### Problem
- Sphinx quickstart 1.6 generates a Makefile with the catch-all target that uses the Sphinx "make mode" for building
- `make` can not check if the given argument is sensible since anything hits the catch-all target
- The Sphinx make mode gives an error when the given builder is not found, however, an empty directory with the target name has already been created under the build directory
- The empty directory should not be created at all if the builder does not even exist

#### Procedure to reproduce the problem
```
make fake
```

#### Error logs / results
```
Running Sphinx v1.6.4
making output directory...
loading translations [en]... done

Sphinx error:
Builder name fake not registered or available through entry point
Makefile:27: recipe for target 'fake' failed
make: *** [fake] Error 1
```
Sphinx gives an error that the `fake` builder does not exist, but nonetheless, an empty directory `fake` has been created under the build directory.

#### Expected results
The Sphinx make mode should not create empty directories for unknown builders.

### Environment info
- OS: Ubuntu Linux 16.04
- Python 3.5.2
- Sphinx version: 1.6.4
- GNU Make 4.1

**Comment by tk0miya** [comment]
Fixed by #4389 
Thank you for reporting!
