### ISSUE TITLE
An odd number of single quotes in bash code-clock line causes Highlighting skipped warning

### ISSUE THREAD

**Issue by donovan** [sphinx-doc/sphinx#4098]
Subject: An odd number of single quotes in bash code-clock line causes Highlighting skipped warning

### Problem
- Any bash code block that contains a line that contains an odd number of single quotes " ' " will cause the following warning: `WARNING: Could not lex literal_block as "bash". Highlighting skipped.`

Note that this seems to be bash specific, I could not trigger the same warning in a python block _but_ I did not test anything else.

#### Procedure to reproduce the problem
```
$ cat source/tutorials/bash-code-block-bug.rst
###################
Bash code block bug
###################

Bug
===

The following code block will trigger this warning: `WARNING: Could not lex
literal_block as "bash". Highlighting skipped.`

.. code-block:: bash

 $ echo Can't be using a single single quote
$ make html
...
preparing documents... done
writing output... [100%] tutorials/using-packer-to-build-custom-bootable-images-on-the-catalyst-cloud                                                                                                       
/home/foo/src/cc-docs/source/tutorials/bash-code-block-bug.rst:11: WARNING: Could not lex literal_block as "bash". Highlighting skipped.
generating indices... genindex
...
```

#### Error logs / results
```
/home/foo/src/cc-docs/source/tutorials/bash-code-block-bug.rst:11: WARNING: Could not lex literal_block as "bash". Highlighting skipped.
```

#### Expected results
When typing `make html` lines within a bash code-block that contains an odd number of single quotes do not cause any warnings and highlighting is not skipped.

### Environment info
- OS: Ubuntu 16.04
- Python version: Python 2.7.12
- Sphinx version: Sphinx==1.6.4

**Comment by tk0miya** [comment]
It seems your input has broken. So pygments failed to highlight.
```
bash-3.2$ cat input.txt
echo Can't be using a single single quote
bash-3.2$ cat input.txt | pygmentize -l bash -F raiseonerror

*** Error while highlighting:
pygments.filters.ErrorToken: '
   (file "/Users/tkomiya/.pyenv/versions/3.6.2/lib/python3.6/site-packages/pygments/filters/__init__.py", line 196, in filter)
*** If this is a bug you want to report, please rerun with -v.
```

How about quoting the message with double-quote?

**Comment by donovan** [comment]
Ok the problem here was we are using code-block bash when displaying command line interaction. I have changed these to use code-block console and these warnings are gone. Avoiding single quotes in real bash code blocks is then a simple matter of writing real bash in most cases.

Closing
