### ISSUE TITLE
C++: Trying to reference a class results in a reference to its constructor

### ISSUE THREAD

**Issue by mitya57** [sphinx-doc/sphinx#4099]
I was looking at pybind11 project, which currently fails to build with Sphinx 1.6.4 with this error:
```pytb
  File "/usr/lib/python2.7/dist-packages/sphinx/domains/cpp.py", line 4969, in checkType
    assert False
AssertionError
Type is class, declType is function
```

See also [the full log](https://tests.reproducible-builds.org/debian/rbuild/unstable/amd64/pybind11_2.0.1-4.rbuild.log). After applying my pull request #4096, I get warnings instead:
```
/tmp/pybind11-2.0.1/docs/reference.rst:60: WARNING: cpp:class targets a function (handle::handle).
/tmp/pybind11-2.0.1/docs/reference.rst:158: WARNING: cpp:class targets a function (object::object).
/tmp/pybind11-2.0.1/docs/reference.rst:163: WARNING: cpp:class targets a function (object::object).
```

The [source rst file](https://raw.githubusercontent.com/pybind/pybind11/v2.0/docs/reference.rst) looks correct to me. Example for the block where the first error occurs:
```
.. function:: handle::handle(PyObject *)

    Creates a :class:`handle` from the given raw Python object pointer.
```

In my opinion Sphinx is at fault here: there should be no warning on error when trying to reference a class here.

Note that the latest version of pybind11 switched to Breathe for documenting C++ code, but I was looking at version 2.0.1 which we have in Debian.

**Comment by jakobandersen** [comment]
This is indeed a bug. The lookup should be role sensitive when dealing with constructors.

**Comment by MKaslaan** [comment]
issue

**Comment by jakobandersen** [comment]
This is fixed in stable.
