### ISSUE TITLE
Spurious print() in autodoc.Documenter class

### ISSUE THREAD

**Issue by lelit** [sphinx-doc/sphinx#4100]
There is a leftover debug `print()` statement in the method `filter_members()` of the `autodoc.Documenter` class, both in the 1.6 branch and in [current master](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/ext/autodoc/__init__.py#L719).

**Comment by tk0miya** [comment]
Thank you for reporting. Fixed at fd0a56b.
