### ISSUE TITLE
Building CouchDB Docs

### ISSUE THREAD

**Issue by VladimirCores** [sphinx-doc/sphinx#4104]
Subject: Exception occurred:
File "conf.py", line 17, in <module>
ImportError: No module named sphinx_rtd_theme
The full traceback has been saved in /tmp/sphinx-err-Hwv9Fw.log, if you want to report the issue to the developers.

![image](https://user-images.githubusercontent.com/442111/31093447-0f6b6186-a7b2-11e7-8a7b-26f907e19409.png)

### Environment info
- OS:  Unix (ARMv7)

**Comment by tk0miya** [comment]
Now`sphinx_rtd_theme` is not bundled with sphinx. so please install it manually.
