### ISSUE TITLE
search is not working for some words.

### ISSUE THREAD

**Issue by lquissakng** [sphinx-doc/sphinx#4123]
Subject: search is not working for some words.

### Problem
Search box is not working on our project using pt language. For example, word "VM" is not comming.

#### Procedure to reproduce the problem
Go to search box and try to search "então", "do", "que", etc. The result is:
Your search did not match any documents. Please make sure that all words are spelled correctly and that you've selected enough categories.

<Paste your command-line here which cause the problem>
```

#### Error logs / results
```
<Paste your error log here>
```
- <public link of unexpected result if you have>

#### Expected results
<Describe what to actually do>

### Reproducible project / your project
- <link to your project, or attach zipped small project sample>

### Environment info
- OS: <Unix/Linux/Mac/Win/other with version>
- Python version:
- Sphinx version:
- <Extra tools e.g.: Browser, tex or something else>

**Comment by tk0miya** [comment]
@shibukawa could you check this please?
AFAIK, Sphinx does not add short keywords like 'do' to index. so it would not be matched any document. Is this right?

**Comment by shibukawa** [comment]
Yes, not only Sphinx but also many search engines define stops words, they are not indexed.
See the following code:

https://github.com/sphinx-doc/sphinx/blob/master/sphinx/search/pt.py

**Comment by lquissakng** [comment]
Hello Yoshiki, in this case should we change the pt.py removing the words
we would like to be searched?

<https://about.me/l.quissak?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api&utm_content=thumb>
Luís Fernando Quissak
about.me/l.quissak
<https://about.me/l.quissak?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api&utm_content=thumb>

2017-10-07 8:55 GMT-03:00 Yoshiki Shibukawa <notifications@github.com>:

**Comment by shibukawa** [comment]
Yes. But as you know, Sphinx makes index files and browsers should download it to search. Removing the word could expand your index file size.

**Comment by lquissakng** [comment]
Hello Yoshiki, no problem we have a small content. Let´s try!

Thanks.


<https://about.me/l.quissak?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api&utm_content=thumb>
Luís Fernando Quissak
about.me/l.quissak
<https://about.me/l.quissak?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api&utm_content=thumb>

2017-10-10 11:18 GMT-03:00 Yoshiki Shibukawa <notifications@github.com>:

**Comment by lquissakng** [comment]
Olá,

Eu acabei de assinar o abaixo-assinado "Queremos que Flávio Bolsonaro e
Queiroz esclareçam R$ 1,2 milhão encontrados em relatório do Coaf" e queria
saber se você pode ajudar assinando também.

A nossa meta é conseguir 15.000 assinaturas e precisamos de mais apoio.
Você pode ler mais sobre este assunto e assinar o abaixo-assinado aqui:

http://chng.it/gYzsmvYQwN

Obrigado!
Luís Fernando
