### ISSUE TITLE
docutils.conf is not documented explicitly.

### ISSUE THREAD

**Issue by funkyfuture** [sphinx-doc/sphinx#4134]
though a `docutils.conf` [is mentioned](http://www.sphinx-doc.org/en/stable/search.html?q=docutils.conf&check_keywords=yes&area=default) in the documentation, it should be mentioned explictly in the `config.rst` that it is possible to create such for further configuration.

**Comment by stephenfin** [comment]
For reference, the docutils docs on same as [here](http://docutils.sourceforge.net/docs/user/config.html).

**Comment by jfbu** [comment]
Thanks, fixed at 77c5aaaa973dfaab652197ae345f17f904a943fe

**Comment by funkyfuture** [comment]
perfect, mille gracie.
