### ISSUE TITLE
[sphinx.ext.doctest] set language for doctest blocks

### ISSUE THREAD

**Issue by wojdyr** [sphinx-doc/sphinx#4137]
It would be nice to have the language of `doctest` blocks set to Python.
It matters in documents that have `highlight_language` set to something else (in my case c++).
I think in such cases it's currently necessary is to use the `highlight` directive before (and after) doctests.

It's not very convenient, so I monkey-patched it in my conf.py:
```py
import sphinx.ext.doctest
def DoctestDirective_run(self):
    nodes = sphinx.ext.doctest.TestDirective.run(self)
    nodes[0]['language'] = 'pycon'
    return nodes
sphinx.ext.doctest.DoctestDirective.run = DoctestDirective_run
```

but it'd be more elegant to have it in [ext/doctest.py][1], maybe next to these lines:

        if self.name == 'testoutput':
            # don't try to highlight output
            node['language'] = 'none'

[1]: https://github.com/sphinx-doc/sphinx/blob/master/sphinx/ext/doctest.py#L123

**Comment by tk0miya** [comment]
Good point!
