### ISSUE TITLE
Parsing fails if you have a field list first in the document

### ISSUE THREAD

**Issue by regebro** [sphinx-doc/sphinx#4145]
Subject: <what happen when you do on which document project>

### Problem
from the docutils docs: "When a field list is the first non-comment element in a document (after the document title, if there is one), it may have its fields transformed to document bibliographic data. "

This shows that you can start a document with a field list. This is commonly done by Hovercraft, for example. However, doing so causes an error, because for some reason visit_field_list() will not be called, instead visit_field is called directly. This gives an AttributeError: HTMLTranslator' object has no attribute '_fieldlist_row_index'

#### Procedure to reproduce the problem
Start a document with a field list, for example: 
https://raw.githubusercontent.com/regebro/hovercraft/master/docs/examples/tutorial.rst

#### Error logs / results

```
SmartyPantsHTMLTranslator' object has no attribute '_fieldlist_row_index'
```

#### Expected results
Correct parsing

### Reproducible project / your project
https://raw.githubusercontent.com/regebro/hovercraft/master/docs/examples/tutorial.rst

### Environment info
- OS: Linux
- Python version: 3.5
- Sphinx version: 3.4

**Comment by tk0miya** [comment]
Fixed by #4152. Thank you for contribution!
