### ISSUE TITLE
Reduce questions of sphinx-quickstart

### ISSUE THREAD

**Issue by tk0miya** [sphinx-doc/sphinx#4148]
### Problem
- At present, `sphinx-quickstart` asks many questions. it's not "quick" start.

#### Expected results
Make it simple.

**Comment by tk0miya** [comment]
Now sphinx-quickstart asks following questions:
```
> Separate source and build directories (y/n) [n]:
> Name prefix for templates and static dir [_]:
> Project name:
> Author name(s):
> Project version []:
> Project release []:
> Project language [en]:
> Source file suffix [.rst]:
> Name of your master document (without suffix) [index]:
> Do you want to use the epub builder (y/n) [n]:
> autodoc: automatically insert docstrings from modules (y/n) [n]:
> doctest: automatically test code snippets in doctest blocks (y/n) [n]:
> intersphinx: link between Sphinx documentation of different projects (y/n) [n]:
> todo: write "todo" entries that can be shown or hidden on build (y/n) [n]:
> coverage: checks for documentation coverage (y/n) [n]:
> imgmath: include math, rendered as PNG or SVG images (y/n) [n]:
> mathjax: include math, rendered in the browser by MathJax (y/n) [n]:
> ifconfig: conditional inclusion of content based on config values (y/n) [n]:
> viewcode: include links to the source code of documented Python objects (y/n) [n]:
> githubpages: create .nojekyll file to publish the document on GitHub pages (y/n) [n]:
> Create Makefile? (y/n) [y]:
> Create Windows command file? (y/n) [y]:
```

**Comment by tk0miya** [comment]
My proposal:

> Name prefix for templates and static dir [_]:

I wonder why is this really needed. I suppose our users does not modify this.
So I'd like to remove this question or whole of feature.

> Source file suffix [.rst]:

Somebody might change the extensions, but almost people do not.
I think this question can be removed.

> Name of your master document (without suffix) [index]:

This might be not changed by default also.

> Do you want to use the epub builder (y/n) [n]:

Nowadays EPUB is an one of commonly used documentation format.
And the builder becomes enough stable at present.
So I think it's time to go it as default builder.

> Create Makefile? (y/n) [y]:
> Create Windows command file? (y/n) [y]:

It's okay to generate these build scripts by default.

> imgmath: include math, rendered as PNG or SVG images (y/n) [n]:
> mathjax: include math, rendered in the browser by MathJax (y/n) [n]:

`math` directive and role are built into docutils since 0.8.
So I think they are also built into Sphinx by default.
I know we have some choices of equation renderers for HTML builder.
Hence we should improve it as pluggable.

> autodoc: automatically insert docstrings from modules (y/n) [n]:
> doctest: automatically test code snippets in doctest blocks (y/n) [n]:
> intersphinx: link between Sphinx documentation of different projects (y/n) [n]:
> todo: write "todo" entries that can be shown or hidden on build (y/n) [n]:
> coverage: checks for documentation coverage (y/n) [n]:
> ifconfig: conditional inclusion of content based on config values (y/n) [n]:
> viewcode: include links to the source code of documented Python objects (y/n) [n]:
> githubpages: create .nojekyll file to publish the document on GitHub pages (y/n) [n]:

I propose you that all extensions are enabled by command-line-options only.
They are certainly useful, but I think its usecase is advanced usage and uncommon.

**Comment by jfbu** [comment]
> I propose you that all extensions are enabled by command-line-options only.
> They are certainly useful, but I think its usecase is advanced usage and uncommon.

Will they still be present in conf.py in commented out form?

**Comment by tk0miya** [comment]
There is only one config value for bundled extensions; `todo_inculde_todos`.
IMO, it is not needed when todo extension disabled.

**Comment by PhySci** [comment]
Current 'Getting Started' page was not updated and does not reflect new short list of questions. Spent a couple hours figuring out what's going wrong.

**Comment by MartinThoma** [comment]
It is super confusing to see

    Welcome to the Sphinx 2.4.2 quickstart utility.

    Please enter values for the following settings (just press Enter to
    accept a default value, if one is given in brackets).

    Selected root path: .

    You have two options for placing the build directory for Sphinx output.
    Either, you use a directory "_build" within the root path, or you separate
    "source" and "build" directories within the root path.


when you're used to be able to enter a root path. Maybe one could change "Selected root path" to "root path" or "Used root path" ... and maybe show the absolute path there?

**Comment by superlevure** [comment]
Why are we not able to change the root path anymore ?
