### ISSUE TITLE
latex_engine = 'xelatex' if language != 'ja' else 'platex' 

### ISSUE THREAD

**Issue by JulienPalard** [sphinx-doc/sphinx#4150]
Subject: I can either build french or japanese but not both with the same `conf.py`

### Problem

Building PDFs for the cPython documentation works for french using xelatex and for japanese with platex, but while initializing latex_engine value we don't have access to the language value.

I'd like to configure something like:

    latex_engine = 'xelatex' if language != 'ja' else 'platex'

But we're giving language from [a script](https://github.com/python/docsbuild-scripts/blob/29eaa1cc1effbdddf4e467daa0cff4fa828f91f9/build_docs.py#L181) via [the makefile](https://github.com/python/cpython/blob/590665c399fc4aa3c4a9f8e7104d43a02e9f3a0c/Doc/Makefile#L16) using the form `-D language=fr`.

Maybe we're doing it the wrong way, and by doing it more naturally we would not enconter this issue? Maybe we should pass latex_engine from the makefile too and have the `'xelatex' if language != 'ja' else 'platex'` in our script?

### Reproducible project / your project

- https://github.com/python/cpython/tree/master/Doc

### Environment info
- OS: Linux
- Python version: 3.4.3 and 3.5.4
- Sphinx version: 1.6.4

**Comment by tk0miya** [comment]
Unfortunately Sphinx does not support configuration per languages. Please use `-D` option of `sphinx-build` command to override configuration.

BTW, I made very simple extension to realize your idea:
https://gist.github.com/tk0miya/8e9aa5aaa7d83a27a013839ad5463354

I wish this helps you.

**Comment by tk0miya** [comment]
Note:
Internally, Sphinx does not know what configuration values are specified at reading `conf.py`. Because extensions are not loaded here (They are listed at conf.py!). so it is hard to provide the value of `language`.
(I know some built-in config values are enabled here, but ...)

**Comment by JulienPalard** [comment]
@tk0miya Thanks for the clarification. We're currently using `-D` (https://github.com/python/docsbuild-scripts/pull/34).
