### ISSUE TITLE
Chinese language doesn't trigger Chinese search automatically

### ISSUE THREAD

**Issue by fyears** [sphinx-doc/sphinx#4169]
Subject: Chinese language doesn't trigger Chinese search automatically

### Problem
According to [doc](http://www.sphinx-doc.org/en/stable/config.html#confval-html_search_language),

> `html_search_language`
> ...  This defaults to the global language selected with `language`.

However, while I set the `language` to (Simplified) Chinese:

```
language = 'zh_CN'
```
The search function still uses the `en` version:

```
$ make html
... (some output)
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded.

Build finished. The HTML pages are in _build\html.
```

For those who doesn't know Chinese:

sphinx supports two versions of Chinese: `zh_CN` – Simplified Chinese, `zh_TW` – Traditional Chinese, **under different names**.

Also sphinx supports the search, under the name `zh`.

I reasonably guess sphinx just don't know that `zh_CN` and `zh_TW` `language` should both trigger `zh` `html_search_language`.

#### Procedure to reproduce the problem

In `conf.py`, set `language` and **not set** `html_search_language`
```
language = 'zh_CN'
# html_search_language # <- do NOT set it and let sphinx guess it
```

Then

```bash
make html
```

#### Error logs / results

```
$ make html
... (some output)
dumping search index in English (code: en) ... done # <- notice this
...
```

#### Expected results

```
$ make html
... (some output)
dumping search index in Chinese (code: zh) ... done # <- should automatically call Chinese search index
...
```

### Reproducible project / your project

None. Just use any sphinx example project and change the `conf.py` as above.

### Environment info
- OS: Win
- Python version: 3.6
- Sphinx version: 1.6 (1.7dev20171020 has not fixed this issue but has slightly different output)

**Comment by tk0miya** [comment]
Fixed by #4171
