### ISSUE TITLE
Viewcode extension documentation text cleanup.

### ISSUE THREAD

**Issue by Shaun-Griffith-Hive** [sphinx-doc/sphinx#4185]
Subject: Incomplete or corrupted sentence in Viewcode extension documentation.

### Problem
- "As side effects, this option else they produce nothing."

- http://www.sphinx-doc.org/en/stable/ext/viewcode.html#module-sphinx.ext.viewcode

**Comment by jfbu** [comment]
refs https://github.com/sphinx-doc/sphinx/commit/e8b870de0cbaf724986b65de9552262ac253a6d2

**Comment by Shaun-Griffith-Hive** [comment]
I'm sorry, was that commit addressing this issue? There still seems to be some words missing between "option" and "else".

**Comment by jfbu** [comment]
@Shaun-Griffith-Hive no it was seemingly the commit introducing the issue... Possibly the whole line is in extra, but I have a hard time understanding exactly the meaning. Ping @shimizukawa

**Comment by tk0miya** [comment]
I updated it at #5859.
I'm not good at English. So please let me know if it is not understandable.
Thanks,

**Comment by crazyjay0516** [comment]
I'm sorry
