### ISSUE TITLE
How to preserve Index.rst when running sphinx-apidoc ?

### ISSUE THREAD

**Issue by MikeNeate** [sphinx-doc/sphinx#4190]
I'm using sphinx to generate docs from python docstrings but I also want user guides, tutorials etc defined in manually created .rst files. I'm using sphinx-apidoc to generate the structure from the python code and then `make html` to generate the final html output. Everything is working well but one problem. When a python class changes I need to run sphinx-apidoc  again with --force to ensure the rst files are updated. Obviously this wipes all manual changes that I've made to index.rst (these changes are references to the user guide, tutorials etc).

How do I preserve my manual changes to index.rst when when I re-run sphinx-apidoc ?

Any help much appreciated
Mike

**Comment by tk0miya** [comment]
This is a issue list of Sphinx. Please post your question to sphinx-users forum.
https://groups.google.com/forum/#!forum/sphinx-users

BTW, I guess `sphinx.ext.autosummary` is much better to your situation.
`sphinx-apidoc` is an alternative of `sphinx-quickstart`. So it is better to use for bootstrap of documentation.

**Comment by tk0miya** [comment]
I'm closing this now because it seems no updates.
Feel free to reopen this if you still have this problem.

Thanks,
