### ISSUE TITLE
Creating documentation stub fails in Python3.6

### ISSUE THREAD

**Issue by tastyminerals** [sphinx-doc/sphinx#4191]
Attempting to create documentation stub fails. 

### Problem
`sphinx-build . mydocs` throws
`ModuleNotFoundError: No module named 'mods'`
`ModuleNotFoundError: No module named 'res'`

Project structure:
```
project/
    docs/conf.py
    project/main.py
    project/mods/mod1.py
                 mod2.py
    project/res/dic1.py
                blacklist.py
```
`conf.py` contains `sys.path.insert(0, os.path.abspath(os.path.pardir))` at the top and with this setup I am getting import errors of `mod1.py` and `mod2.py` as well as `dic1.py` and `blacklist.py`. I actually tried all kind path variants and none worked.

All subdirs contain `__init__.py`. Same setup works fine with Python2.7.

### Environment info
- OS: Linux
- Python version: 3.6
- Sphinx version: 1.6.4-1

**Comment by tk0miya** [comment]
Do you mean this is a bug of Sphinx?
If so, Please share your project or reproducible example.

Thanks,

**Comment by tastyminerals** [comment]
Ok, everything seems to work if I move `docs` into inner `project` dir.
```
project/
    project/main.py
           docs/conf.py
    project/mods/mod1.py
                 mod2.py
    project/res/dic1.py
                blacklist.py

```
