### ISSUE TITLE
Error while using sphinxcontrib-visio

### ISSUE THREAD

**Issue by Msrgit** [sphinx-doc/sphinx#4192]
Subject: Attempting to include a visio file in a sphinx document

### Problem

Performed:  make html

#### Procedure to reproduce the problem
```
<Paste your command-line here which cause the problem>
Directive used:

..visio-figure:: TestVisio.vsd

#### Error logs / results
```
This is the error log:
[sphinx-err-NFza7e.log](https://github.com/sphinx-doc/sphinx/files/1421591/sphinvNFza7e.log)

This is the file used:
[TestVisio.vsd.zip](https://github.com/sphinx-doc/sphinx/files/1421629/TestVisio.vsd.zip)

#### Expected results
Expecting to see a swimlane diagram in the document

### Reproducible project / your project
- <link to your project, or attach zipped small project sample>

### Environment info
- OS: Linux Mint Cinnamon
- Python version: 2.7.12
- Sphinx version:1.6.5
- Extra tools : sphinxcontrib-exceltable

**Comment by Msrgit** [comment]
Looks like I can only use this on a Windows platform - needs PyWin32 - not available on Linux. Oops - newbie!

I'll leave it open:

Quote: "Please also report this if it was a user error, so that a better error message can be provided next time."

**Comment by tk0miya** [comment]
Sorry, this is issues of Sphinx. so I'm closing this now.
Please post this to sphinxcontrib-visio project if you want to fix it.

Thanks,
