### ISSUE TITLE
list-table :widths: & tabularcolumns?

### ISSUE THREAD

**Issue by ghost** [sphinx-doc/sphinx#4196]
I was playing with the new(ish) `:widths:` table param and thought I could use that for width setting and `tabularcolumns` for column alignment, i.e.

`.. tabularcolumns:: |C|R|`

`.. list-table::`
`   :header-rows: 1`
`   :widths: 1 2`

`   * - Header A1 (Centre, 1/3)`
`     - Header B1 (Right, 2/3)`

`   * - DATA A1`
`     - DATA B1`

No dice.
Why not?
How does one specify (proportional) column widths and column alignment?

**Comment by jfbu** [comment]
Once you make use of ``tabularcolumns`` directive the ``:widths:`` is ignored.

The specifiers ``C`` and  ``R`` are specific to ``tabulary`` LaTeX package, which chooses the column widths proportionally to contents.

If you remove ``tabularcolumns`` the widths are in the specified proportion, but the whole linewidth is occupied. And we have no syntax for centering or right alignment. But you can achieve it with some work.

```rst
Welcome to FOO's documentation!
===============================

.. tabularcolumns:: |>{\centering\arraybackslash}\X{1}{5}|>{\raggedleft\arraybackslash}\X{2}{5}|

.. list-table::
   :header-rows: 1
   :widths: 1 2

   * - Header A1 (Centre, 1/3)
     - Header B1 (Right, 2/3)

   * - DATA A1
     - DATA B1
```

produces 

![capture d ecran 2017-10-30 a 14 54 48](https://user-images.githubusercontent.com/2589111/32174506-5cb49030-bd82-11e7-846e-7c90be277ed7.png)

I chose widths as `1/5` and `2/5` so they are in the ratio `1:2` but occupies only 3/5th of the full width. (else the table appeared too wide).

The good thing here is that we don't modify syntax which will influence say HTML output. So we can use same source for both HTML and LaTeX.

perhaps this could be added to the docs, or `\Xleft`, `\Xcentered`, `\Xright` columns specifiers could be added to ``sphinx.sty``

**Comment by jfbu** [comment]
Variant achieving same PDF output:

```rst
Welcome to FOO's documentation!
===============================

.. tabularcolumns:: |>{\centering\arraybackslash}\Y{0.2}|>{\raggedleft\arraybackslash}\Y{0.4}|

.. list-table::
   :header-rows: 1
   :widths: 1 2

   * - Header A1 (Centre, 1/3)
     - Header B1 (Right, 2/3)

   * - DATA A1
     - DATA B1
```

then you can use `\Y{0.125}`, `\Y{0.333}` etc... if using fractions is not appropriate (here that would be `\X{3}{24}` and `\X{8}{24}` for example but it can become cumbersome quicky.

**Comment by ghost** [comment]
I appreciate the tips and will consider them 'workarounds'. It makes the markup messy and I was trying to clean it up (remembering that RST was meant to be as nice to read raw as the formatted versions it produces). Use of `:widths:` is clean, simple and part of standard docutils. If only there was an easier `tabularcolumns` syntax to work with it for column alignment (clear enough hint?).
While on the subject, there are a few variants of `tabularcolumns` syntax, I guess catering for the `longtable`, `tabular` and `tabulary` tables that they configure. (Another hint coming) Is there a place for sphinx to intercept a standard `tabularcolumns` format and translate into column alignments, (possibly including widths rewritten as `:widths:`?). I.e. I would only need to specify a simple `tabularcolumns` line, using one style, and not be confused by the variations caused by different table packages. I got so used to the reasonably simple `|X[c,1.5]|` format of `longtabu` but I know that's not in the running. Or maybe I'll just try and not use PDF quite so much.

**Comment by jfbu** [comment]
To simplify syntax you only need to add to preamble some new column type definitions. We have to take into account at least 12 possibilities:

- vertical positioning inside the cell can be either top (p), middle (m), bottom (b),

- horizontal justification inside the cell can be left (l), centered (c), right (r), justified (default in LaTeX).

I can provide a tabu-like syntax say  `|Z[m,l]{coeff}|` which will mean "left aligned inside a vertically centered rendering" but `coeff` will mean a proportion of linewidth.

Tabu multiple pass approach, like tabulary's, has issues which makes it incompatible with what the reST specs allow. Currently we can render code-blocks inside merge cells, which is impossible with LaTeX packages in common use.

Going back to the 12 possibilities above, the Docutils table specs do not seem to include syntax for this kind of things. The ``tabularcolumns`` allows control of PDF output which is not available for HTML output.

To return to the situation of earlier comments, 

```rst
.. tabularcolumns:: |\Yc{0.2}|\Yr{0.4}|

.. list-table::
   :header-rows: 1
   :widths: 1 2

   * - Header A1 (Centre, 1/3)
     - Header B1 (Right, 2/3)

   * - DATA A1
     - DATA B1
```

together with

```
latex_elements = {
    'preamble': r'''
\newcolumntype{\Yl}[1]{>{\raggedright\arraybackslash}\Y{#1}}
\newcolumntype{\Yr}[1]{>{\raggedleft\arraybackslash}\Y{#1}}
\newcolumntype{\Yc}[1]{>{\centering\arraybackslash}\Y{#1}}
''',
}
```

in `conf.py`. Yes, here we have to re-code the ``1:2`` proportion for LaTeX especially but we have more control.

If Docutils provides interface to accompany ``:widths:``  with some alignments (vertical and horizontal) of cell contents, we at Sphinx will implement it for compatible writers.

**Comment by ghost** [comment]
Hi, excellent approach, thanks. It nicely hides the complexity away in a single place. Meanwhile I will look to suggesting to the docutils team. Wonder why they didn't think of it already...
EDIT
They did but put it in their todo list: http://docutils.sourceforge.net/docs/dev/todo.html#tables
