### ISSUE TITLE
ParseError triggered by f-strings

### ISSUE THREAD

**Issue by gioelelm** [sphinx-doc/sphinx#4204]
### Problem
I encounter a Parse Error that causes both ``autodoc_member_order = 'bysource'`` and ``:member-order: bysource`` to fail and the members to be outputed in alphabetical order.
The problem seem to have deeper roots and it seems to be caused by presence of f strings.

#### Procedure to reproduce the problem
I was trying to build the docs for my project [velocyto](https://github.com/velocyto-team/velocyto.py)

If f-strings are present in the source and I try to run autodocs, for example consider the .rst file
```
.. automodule:: velocyto.analysis
   :members:
   :undoc-members:
   :show-inheritance:
   :member-order: bysource
```

The output is not sorted by source and I can find out that something has gone wrong silently only running
```
sphinx-build -vvv PROJECTFOLDER OUTFOLDED
```

#### Error logs / results
An example of two of the many errors where f-strings are used and related code line that is triggering the parse error.

```
[autodoc] module analyzer failed: parsing failed (exception was: ParseError('bad input: type=3, value=\'"fraction of _Valid cells is {tmp_str} but all will be taken in consideration"\', context=(\'\', (86, 30))',))
```

```
logging.warn(f"fraction of _Valid cells is {tmp_str} but all will be taken in consideration")
```

```
[autodoc] module analyzer failed: parsing failed (exception was: ParseError('bad input: type=3, value=\'"First search the {self.sight_k} nearest neighbours for {self.n_samples}"\', context=(\'\', (158, 23))',))
```

```
logging.debug(f"First search the {self.sight_k} nearest neighbours for {self.n_samples}")
```

#### Expected results
<Describe what to actually do>

### Reproducible project / your project
To reproduce
```
git clone https://github.com/velocyto-team/velocyto.py
mkdir velocyto.docs
cd velocyto.py/doc
sphinx-build -vvv "." "../../velocyto.docs"
```

### Environment info
- OS: Mac
- Python version: python 3.6.2 (anaconda)
- Sphinx version: 1.6.3 (anaconda, build: py36hcd1b3e7_0)

Also reproduced on Linux

**Comment by tk0miya** [comment]
Could you try our master branch? It includes new python code parser for autodoc.
I hope it resolves your problem.

**Comment by gioelelm** [comment]
Thanks! Now output is correct.

**Comment by takuan-osho** [comment]
@tk0miya It seems you can close this issue now, doesn't it?
