### ISSUE TITLE
How to handle a missing parameter description in numpydoc

### ISSUE THREAD

**Issue by timhoffm** [sphinx-doc/sphinx#4205]
### Problem
I've recently come across a numpy docstring with a missing parameter description. Example: `axis` has no description.

~~~
Parameters
----------
by : mapping, function, str, or iterable
    Used to determine the groups for the groupby.
axis : int, default 0
level : int, level name, or sequence of such, default None
    If the axis is a MultiIndex (hierarchical), group by a particular
~~~

**First question**: Is this a valid numpy docstring at all? If not, what would be the correct way to write this?

This docstring converted to:

![grafik](https://user-images.githubusercontent.com/2836374/32249943-f907d29a-be8a-11e7-930a-55afb7f6acfb.png)

Note the broken format and indentation on `axis`.

#### Procedure to reproduce the problem
The example comes from `pandas.DataFrame.groupby`. I've seen it in Spyder, which uses Sphinx to generate help on the fly.

Simply open Spyder, type

    import pandas
    pandas.DataFrame.groupby

and press `Ctrl+I`

#### Error logs / results

The generated .rst is essentially unmodified (shortend to the essential parts):

~~~
Group series using mapper (dict or key function) [...]

Parameters
----------
by : mapping, function, str, or iterable
    Used to determine the groups for the groupby. [...]
axis : int, default 0
level : int, level name, or sequence of such, default None
    If the axis is a MultiIndex (hierarchical), group by [...]
~~~

See above for the resulting html.

### Expected results

Sphinx should gracefully handle missing parameter descriptions in numpy docstrings. Maybe more generally, the handling of a ReST definition list with missing descriptions could be handled better.

### Environment info
- OS: Windows 10
- Python version: 3.6.2
- Sphinx version: 1.6.3

**Comment by RobRuana** [comment]
You could try adding a newline, like so:

```
Parameters
----------
by : mapping, function, str, or iterable
    Used to determine the groups for the groupby.
axis : int, default 0

level : int, level name, or sequence of such, default None
    If the axis is a MultiIndex (hierarchical), group by a particular
```

**Comment by timhoffm** [comment]
An empty line does not work. One would have to use an empty comment:

~~~
axis : int, default 0
    ..
level : int, level name, or sequence of such, default None
    If the axis is a MultiIndex (hierarchical), group by a particular
~~~

I'm just wondering, does the format have to be so strict? Either the converter numpydoc -> `.rst` or even better `.rst` -> `.html` could handle this more gracefully.

**Comment by tk0miya** [comment]
It seems numpydoc spec accepts parameters without descriptions. So this should be fixed.
https://numpydoc.readthedocs.io/en/latest/format.html

**Comment by tk0miya** [comment]
With Sphinx-3.2.1, it seems already resolved now. So I'm closing this.
