### ISSUE TITLE
PyTorch import fails for make html

### ISSUE THREAD

**Issue by gauss256** [sphinx-doc/sphinx#4207]
### Problem
Using `autodoc`, when I run `make html` on even the simplest file that uses PyTorch, it fails with the error message below.

#### Procedure to reproduce the problem
Sphinx was set up using `quickstart` and taking all the defaults except to say yes for `autodoc`. I have reproduced the problem with a project that has just one source file, whose contents are:
```
"""
PyTorch import example
"""
import torch

def dummy():
    """dummy"""
    print(torch.__version__)
```

#### Error logs / results
```
ImportError: dlopen: cannot load any more object with static TLS
```

### Environment info
- OS: Ubuntu 14.04
- Python version: 3.5.3
- Sphinx version: 1.6.5

**Comment by tk0miya** [comment]
Can you import `torch` in your environment? The error says failed to import dynamic libraries for TLS.
I guess this is environment issue.
autodoc tries to import the target program on generating document. So it should be importable.

**Comment by gauss256** [comment]
Right, I forgot to mention that I have no problems importing `torch` when I run my script standalone through Python.

**Comment by tk0miya** [comment]
Sorry for late response.
I just tried to reproduce this again. But I can't.
Are you still in trouble? If so, please let me know how to reproduce this. As I commented above, I think this is an issue of environment.

This is my dockerfile:
```
FROM tk0miya/sphinx-html

RUN pip3 install http://download.pytorch.org/whl/cu80/torch-0.3.1-cp35-cp35m-linux_x86_64.whl_
RUN pip3 install torchvision
RUN sphinx-quickstart -q -a author -p project --extensions sphinx.ext.autodoc .
RUN echo '"""\n\
PyTorch import example\n\
"""\n\
import torch\n\
\n\
def dummy():\n\
    """dummy"""\n\
    print(torch.__version__)\n\
' > test.py
RUN echo '\nimport os, sys\nsys.path.insert(0, os.path.abspath("."))'
RUN echo '.. automodule:: test\n\
   :members:\n\
' > index.rst
RUN sphinx-build -b html . _build/html
```

**Comment by gauss256** [comment]
It's been a while since I've tried this. Not sure if the problem is still there. The next time I try it I'll post a follow-up message.

**Comment by tk0miya** [comment]
Thank you for comment.
Okay, I'm closing this now. Please reopen this issue if you'll see the same error.
Thanks,

**Comment by JuanFMontesinos** [comment]
Im facing similar error:


```
Running Sphinx v2.1.2
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 3 source files that are out of date
updating environment: 3 added, 0 changed, 0 removed
terminate called after throwing an instance of 'std::runtime_error'             
  what():  expected ) but found 'ident' here:
quantized::fake_quantize_per_tensor_affine_forward(Tensor X, float scale, int zero_point, int num_bits = 8, int quant_delay = 0, int iter = 0) -> Tensor
                                                                                                            ~~~ <--- HERE

Aborted (core dumped)
Makefile:20: recipe for target 'html' failed
make: *** [html] Error 134
```

Just by creating this doc:
```
import torch
def hola():
	"""
	Wraps ffprobe to get file duration and fps

	:param str filename: str, Path to file to be evaluate
	:return: tuple(time, fps) in the mentioned format
	"""

	pass
```

Running same code but just changing torch by cv2 works:
```
import cv2
def hola():
	"""
	Wraps ffprobe to get file duration and fps

	:param str filename: str, Path to file to be evaluate
	:return: tuple(time, fps) in the mentioned format
	"""

	pass
```
```
Running Sphinx v2.1.2
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 3 source files that are out of date
updating environment: 3 added, 0 changed, 0 removed
reading sources... [100%] modules                                               
looking for now-outdated files... none found
pickling environment... done
checking consistency... /home/jfm/asd/docs/source/modules.rst: WARNING: document isn't included in any toctree
done
preparing documents... done
writing output... [100%] modules                                                
generating indices... genindex py-modindex
highlighting module code... [100%] asd.jamon                                    
writing additional pages... search/home/jfm/.local/lib/python3.6/site-packages/sphinx_rtd_theme/search.html:20: RemovedInSphinx30Warning: To modify script_files in the theme is deprecated. Please insert a <script> tag directly in your theme instead.
  {{ super() }}

copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 1 warning.
```

Why?

**Comment by tk0miya** [comment]
It seems torch is crashed internally.
```
terminate called after throwing an instance of 'std::runtime_error'             
  what():  expected ) but found 'ident' here:
quantized::fake_quantize_per_tensor_affine_forward(Tensor X, float scale, int zero_point, int num_bits = 8, int quant_delay = 0, int iter = 0) -> Tensor
                                                                                                            ~~~ <--- HERE

Aborted (core dumped)
```

Is your script able to run standalone?

**Comment by JuanFMontesinos** [comment]
Hi,  it is. In fact it's nothing but a dummy script in a single python file which just contains that import and that function.  I couldn't identify where that error was coming from and tried to find a minimal example.  I realised autodoc extension was failing if torch was imported. It is pytorch 1.1 installed from binaries, thus,  I doubt it were a compiling problem from my side.  However this is my first attempt with sphinx and I have no clue about how to address the issue.

**Comment by tk0miya** [comment]
If `python example.py` is succeeded but autodoc is failed, it might be a bug of Sphinx. If so, please file an another issue with your example. I'll take a look it.

**Comment by JuanFMontesinos** [comment]
Done in #6521
