### ISSUE TITLE
In Intersphinx link hover text, "v" should be optional if target has no version

### ISSUE THREAD

**Issue by ekpgh** [sphinx-doc/sphinx#4209]
Subject: 
When using Intersphinx to link between two HTML documents, the version number for the target document automatically shows shows up in the hover text of the hyperlink, even if the target does not have a version number. This gives a "v" with nothing else after it.

### Problem
Created Intershpinx links to a help document that doesn't have version numbers. When the link is rendered in the HTML file, there's hover text that says 
> (in [My Project] Help v) 

I tried:
- changing the version and release values to ```''``` 
- changing the version and release values to ```'0'``` 
(note that this also gave the empty v behavior - I expected "v0.0")
- commenting out the version and release lines in conf.py  

The v always showed up, with no number, after a clean build. 

#### Procedure to reproduce the problem
conf.py for the target document (shows default values from sphinx-quickstart): 
```
# General information about the project.
project = u'My Project Help'
copyright = u'2017, My Company, Inc.'
author = u'My Company, Inc.'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = u'n'
# The full version, including alpha/beta/rc tags.
release = u'n'
```

#### Error logs / results

Additional information and screenshots in this forum post: http://groups.google.com/forum/#!msg/sphinx-users/yG_rG0psM_U/Ccn4x8kQCAAJ

#### Expected results

- If the version number in the target document's conf.py is null, the v should not appear. 
- Alternate approach: the v should be part of text that can be customized so that it can be removed if not wanted. 

### Environment info
- OS: MacOS 10.12.6 
- Python version: 2.7.10
- Sphinx version: 1.5.5

**Comment by tk0miya** [comment]
Fixed by #4519 
Thank you for reporting!
