### ISSUE TITLE
unknown directives within only:: or ifconfig:: blocks still generate error messages

### ISSUE THREAD

**Issue by markcmiller86** [sphinx-doc/sphinx#4224]
Subject: unknown directives within only:: or ifconfig:: blocks still generate error messages

### Problem
Both of the following constructs aim to prevent the `.. spelling::` directive block from being interpreted except in certain conditions.

```
.. only:: spelling

   .. spelling::

      foobar


```

or

```
.. ifconfig:: spellcheck in ('yes')

   .. spelling::

      foobar

```

With `sphinx-build` invoked with or without `-t spelling` the `.. only::` version winds up generating the error message below. Likewise with `conf.py` adjusted to include the ifconfig extension and then...

```
spellcheck = 'no'
def setup(app):
    app.add_config_value('spellcheck', '', 'html')
```

Also winds up generating the error message...

```
/Users/miller86/visit/trunk_SphynxDocs/WorkingWithFiles/Supported_File_Types.rst:3: ERROR: Unknown directive type "spelling".

.. spelling::

   foobar
```

#### Expected results
I expected sphinx not to attempt to intepret *any* content in a block that was deemed not relevant by the enclosing `.. only::` or `.. ifconfig::` directive.

### Environment info
- OS: OSX 10.11.6
- Python version: 2.7 and 3.6
- Sphinx version: 1.5.5 and 1.6.3
sphinx-spelling extension

**Comment by tk0miya** [comment]
Unfortunately, `only` and `ifconfig` works on writing phase. So the contents of these directives are parsed on reading phase. This is specification of these directives.

**Comment by markcmiller86** [comment]
Thanks for response.

Indeed...that is unfortunate!

That said, I did resolve my particular issue a different way and you can read about it [here](https://github.com/sphinx-contrib/spelling/issues/8#issuecomment-344338038) if interested.
