### ISSUE TITLE
sphinx-apidoc generates old-style (long) Makefile

### ISSUE THREAD

**Issue by anntzer** [sphinx-doc/sphinx#4226]
Subject: sphinx-apidoc generates old-style (long) Makefile

### Problem
sphinx-apidoc generates the old-style, long form Makefile, rather than the newer, short-form Makefile that simply forwards to sphinx's make-mode.

#### Procedure to reproduce the problem
```
mkdir pkg && touch pkg/__init__.py
sphinx-apidoc -o doc -F pkg
cat doc/Makefile
```

#### Error logs / results
The long form Makefile is printed.

#### Expected results
The short form Makefile is printed.

The invocation of quickstart from apidoc is
```
 qs.generate(d, silent=True, overwrite=args.force)
```
without setting the `make_mode` entry in `d` but quickstart checks
```
if d.get('make_mode') is True:
```
i.e. it defaults to no-make-mode.

### Reproducible project / your project
- <link to your project, or attach zipped small project sample>

### Environment info
- OS:  linux
- Python version: 3.6
- Sphinx version: 1.6.5
- <Extra tools e.g.: Browser, tex or something else>

**Comment by tk0miya** [comment]
+1
