### ISSUE TITLE
Document python -msphinx as allowing to dump an intersphinx db

### ISSUE THREAD

**Issue by anntzer** [sphinx-doc/sphinx#4244]
Subject: python -msphinx.ext.intersphinx is a practical way to dump an intersphinx db

### Problem
Sometimes a doc is missing an intersphinx db entry, causing headscratching for other projects that want to link to it.  `python -msphinx.ext.intersphinx url-or-path` is a practical, already existing way to print the contents of an intersphinx db, allowing one to quickly confirm that the entry is missing.  It would benefit from being documented at http://www.sphinx-doc.org/en/stable/ext/intersphinx.html.

#### Procedure to reproduce the problem
n/a

#### Error logs / results
n/a

#### Expected results
n/a

### Reproducible project / your project
n/a

### Environment info
n/a

**Comment by tk0miya** [comment]
PR is always welcome :-)
