### ISSUE TITLE
Limit page width in all themes

### ISSUE THREAD

**Issue by timhoffm** [sphinx-doc/sphinx#4246]
### Problem
The following themes do not have a width limit on their pages:

- nature
- classic
- traditional
- pyramid
- bizstyle

This can result in extremely long text lines on large screens, making text difficult to read.

### Proposal

I propose to change the css of the above projects to limit the page width.

In case there are concerns that this changes the themes and breaks backward compatibility, one could at least add an option, so that users could set the width in the config.

**Comment by timhoffm** [comment]
If the basic idea is ok, I could write a pull request.

**Comment by tk0miya** [comment]
+1

**Comment by tk0miya** [comment]
Now #4246 is merged. It will be release as 1.7.
Thank you for your contribution!

**Comment by AndrewShepherd** [comment]
I understand why you did this, but is there a way that we can configure our setup (add to the `conf.py` file) so it reverts to `max-width:none` or `max-width:fill-available`?

**Comment by timhoffm** [comment]
It should be possible to set the body_max_width parameter to strings like initial, none or fill-available.

See also 
https://www.sphinx-doc.org/en/master/usage/theming.html

**Comment by pradyunsg** [comment]
Noting that the PR that fixes this was https://github.com/sphinx-doc/sphinx/pull/4376 (not #4246 -- which is this issue itself -- as noted by @tk0miya).
