### ISSUE TITLE
Clarify startdocname value of latex_documents 

### ISSUE THREAD

**Issue by JulienPalard** [sphinx-doc/sphinx#4255]
Subject: The doc is unclear about the expected value of the first element of tuples expected in `.latex_documents`

The documentation tells:

> startdocname: document name that is the “root” of the LaTeX file. All documents referenced by it in TOC trees will be included in the LaTeX file too. (If you want only one LaTeX file, use your master_doc here.)

But the expected value is a "path-link-thingy" (I still don't know what is is exactly), but I was able to use it with `api/schema` for my documentation containing an `api/` directory with a `schema.rst` file in it.

Does someone know how it is expected to work exactly?

**Comment by tk0miya** [comment]
In sphinx, docname is a string which indicates a document path relative from srcdir. And it does not contain any file-suffix.

Certainly, our docs does not mention about the word. So we need to update it. I think glossary is needed.
