### ISSUE TITLE
Autodoc issue

### ISSUE THREAD

**Issue by jorivanee** [sphinx-doc/sphinx#4260]
Subject: Autodoc issue

### Problem
- Currently I have this: https://gyazo.com/3782bbce5d406ef9cb636b458cbcc509, how do I remove https://gyazo.com/0019a029a377e99bbab493fa9c894b4e

#### Procedure to reproduce the problem
```py
class BotDescription:
	"""Represents a DBL Bot Description

	Attributes
	----------
	short: str
		The bot's short description.
	long: str
		The bot's long description.
	"""
	def __init__(self, *, data={}):
		self.long = None
		self.short = None
		self.update(data=data)

	def update(self, *, data):
		longdesc = data.get("longdesc",None)
		shortdesc = data.get("shortdesc",None)
		if shortdesc:
			self.short = shortdesc
		if longdesc:
			self.long = longdesc
```

#### Error logs / results
```
Nothing
```
- Nothing

#### Expected results
Not display (*, data={})

### Reproducible project / your project
- https://github.com/JustMaffie/PyDBL

### Environment info
- OS: Windows
- Python version: 3.6.1
- Sphinx version: 1.6.2

**Comment by tk0miya** [comment]
Fixed by #4599.
Thank you for reporting!
