### ISSUE TITLE
Race in 'making output directory...' causing fatal OSError: File exists

### ISSUE THREAD

**Issue by stbergmann** [sphinx-doc/sphinx#4262]
Doing a (12-fold) parallel build of LLVM against python2-sphinx-1.6.5-1.fc27.noarch caused two failures

> [5537/5742] Generating man Sphinx docu...o "/data/sbergman/llvm/build/docs/man"
> FAILED: docs/CMakeFiles/docs-llvm-man 
> cd /data/sbergman/llvm/build/docs && /usr/libexec/python2-sphinx/sphinx-build -b man -d /data/sbergman/llvm/build/docs/_doctrees-man -q /data/sbergman/github.com/llvm-project/llvm-project-20170507/llvm/docs /data/sbergman/llvm/build/docs/man
> 
> Exception occurred:
>   File "/usr/lib64/python2.7/os.py", line 157, in makedirs
>     mkdir(name, mode)
> OSError: [Errno 17] File exists: '/data/sbergman/llvm/build/docs/man'
> The full traceback has been saved in /tmp/sphinx-err-OWvr5K.log, if you want to report the issue to the developers.
> Please also report this if it was a user error, so that a better error message can be provided next time.
> A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
> [5538/5742] Generating man Sphinx docu...o "/data/sbergman/llvm/build/docs/man"
> FAILED: docs/CMakeFiles/docs-llvm-dwarfdump-man 
> cd /data/sbergman/llvm/build/docs && /usr/libexec/python2-sphinx/sphinx-build -b man -d /data/sbergman/llvm/build/docs/_doctrees-man -q /data/sbergman/github.com/llvm-project/llvm-project-20170507/llvm/docs /data/sbergman/llvm/build/docs/man
> 
> Exception occurred:
>   File "/usr/lib64/python2.7/os.py", line 157, in makedirs
>     mkdir(name, mode)
> OSError: [Errno 17] File exists: '/data/sbergman/llvm/build/docs/man'
> The full traceback has been saved in /tmp/sphinx-err-6_hAPk.log, if you want to report the issue to the developers.
> Please also report this if it was a user error, so that a better error message can be provided next time.
> A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!

in a row, and each of the two /tmp/sphinx-err-*.log contains

> # Sphinx version: 1.6.5
> # Python version: 2.7.14 (CPython)
> # Docutils version: 0.13.1 release
> # Jinja2 version: 2.9.6
> # Last messages:
> 
> # Loaded extensions:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/site-packages/sphinx/cmdline.py", line 305, in main
>     opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
>   File "/usr/lib/python2.7/site-packages/sphinx/application.py", line 163, in __init__
>     os.makedirs(outdir)
>   File "/usr/lib64/python2.7/os.py", line 157, in makedirs
>     mkdir(name, mode)
> OSError: [Errno 17] File exists: '/data/sbergman/llvm/build/docs/man'

And indeed

>         if not path.isdir(outdir):
>             logger.info('making output directory...')
>             os.makedirs(outdir)

in /usr/lib/python2.7/site-packages/sphinx/application.py looks racy.

**Comment by tk0miya** [comment]
This will be fixed at #4282.

**Comment by tk0miya** [comment]
Fixed by #4282.
