### ISSUE TITLE
Skip unsupported HTML theme options?

### ISSUE THREAD

**Issue by ghost** [sphinx-doc/sphinx#4263]
My conf.py uses a theme (RTD).

Sometimes I want to also build a plain version using the basic/default theme.

I tried adding -D options to override the conf.py settings.

But I cannot override html_theme_options directly (its a dictionary?) and tried using html_theme_options.key=''.

When I do that, I still fail with a message of unsupported theme option 'display_version' (in my case) given.

Enhancement Suggestions:

- Skip unsupported options for theme instead of failing.
- Add a sphinx-build option to UNSET an option rather than override.

Meanwhile, any workarounds to my situation would be welcome. I know I can use -C and -D together but I have a vast (VAST) number of conf.py settings and don't want to put them all as -D options. Neither do I want to have a slightly modified conf.py in another directory and use -c as this will just mean duplicated maintenance/sync effort.

Cheers & TIA

**Comment by tk0miya** [comment]
It will be fixed in next major release (see #3893). Thanks,
