### ISSUE TITLE
Header and Footer alignment parameter is not available

### ISSUE THREAD

**Issue by Shadowell** [sphinx-doc/sphinx#4264]
Subject: <what happen when you do on which document project>

### Problem
I modify the style file sphinx-style and add two items like this below:

    footer:
      parent: normal
      alignment: TA_RIGHT

    header:
      parent: normal
      alignment: TA_CENTER

The page num is still on the left at the bottom.What should I do to put the  page num on the right at the bottom of every page?

#### Procedure to reproduce the problem
```
<Paste your command-line here which cause the problem>
```

#### Error logs / results
```
<Paste your error log here>
```
- <public link of unexpected result if you have>

#### Expected results
<Describe what to actually do>

### Reproducible project / your project
- <link to your project, or attach zipped small project sample>

### Environment info
- OS: <Unix/Linux/Mac/Win/other with version>Win 10
- Python version: 2.7.14
- Sphinx version: 1.6.5
- <Extra tools e.g.: Browser, tex or something else>

**Comment by tk0miya** [comment]
what did you mean "sphinx-style"? It seems not a stylesheet. I don't know it.

**Comment by tk0miya** [comment]
I'm closing this now because it seems no updates.
Feel free to reopen this if you still have this problem.

Thanks,
