### ISSUE TITLE
Translated HTML version contains English sources

### ISSUE THREAD

**Issue by mgeier** [sphinx-doc/sphinx#4265]
Sorry if this is a known issue ...

I've just noticed that when clicking on the source link (ソースコード) in the Japanese docs, I get to the English sources, e.g.

http://www.sphinx-doc.org/ja/stable/_sources/markup/toctree.rst.txt

This isn't right, is it?

**Comment by mgeier** [comment]
The same problem happens with the Spanish translation:

http://www.sphinx-doc.org/es/stable/intro.html

http://www.sphinx-doc.org/es/stable/_sources/intro.rst.txt

**Comment by tk0miya** [comment]
The "show source" link points the original source code. So it is not translated.
It is hard to show translated one because we don't have it.

**Comment by mgeier** [comment]
OK, sorry, I didn't think about how the translation machinery works ...
It makes sense that there is no translated source file, because the translation is done paragraph by paragraph after parsing the original source file, right?

**Comment by tk0miya** [comment]
Right, sphinx does translation after parsing on the memory (a.k.a. doctree based translation).
So there are no translated source file.
