### ISSUE TITLE
Autodoc issue with attributes without any format to be documented

### ISSUE THREAD

**Issue by markova24** [sphinx-doc/sphinx#4269]
Subject: Sphinx documents class attributes without any format to be documented.

### Problem
- Some class attributes keep appearing in final document results within these attributes have no Sphinx format to be documented.

#### Procedure to reproduce the problem
Let's say you have an enumerated class like this, with a little description:
```
class ProfileType(object):

    """Enum class to define user profiles."""

    AGRONOW = 'agronow'
    ADMIN = 'admin'
    COMPANY = 'company'
    USER_COMPANY = 'user_company'
    VIEWER = 'viewer'

    TRIAL = 'trial'
    USER_MANAGER = 'user_manager'
    USER = 'user'
    BASIC_USER = 'basic_user'
    FREE_USER = 'free_user'
    TEST = 'test'
```
So, as you see, these "constants attributes" have no Sphinx format to be documented in final results. Anyways, after I run the "make html" on my terminal, these attributes look like they have, indeed, some kind of tag or something that make them able to appear in my documentation.
#### Error logs / results
```
Constant values keep showing in final documents results.
```
Image provided as an example of what I'm getting as a final result:

![screenshot-2017-11-29 agronow models package agronow 2 documentation](https://user-images.githubusercontent.com/16785264/33400544-3cd35e7a-d535-11e7-959b-bba5535f5522.png)

#### Expected results
I'm not giving any kind of format to that attributes to be documented (I'm not interested in it, actually), so the expected results are that these attributes should not appear in the documentation.

### Reproducible project / your project
- At the moment, I can't give any source. It is a private code, it's not mine.

### Environment info
- OS: Centos 7
- Python version: 2.7
- Sphinx version: 1.5.1
- Browser: Google Chrome
- Documentation theme: sphinx-rtd-theme

**Comment by tk0miya** [comment]
+1 for subclasses of `enum.Enum`. It's reasonable.

**Comment by tk0miya** [comment]
I confirmed these attributes are shown only if `:undoc-members:` option given. Also subclass of `Enum`. I think all of these behavior is expected. So there are nothing to do.
Closing.
