### ISSUE TITLE
Formats accepted by sphinx.util.i18n.format_date are limited

### ISSUE THREAD

**Issue by hftf** [sphinx-doc/sphinx#4275]
[The documentation](http://www.sphinx-doc.org/en/stable/config.html#confval-html_last_updated_fmt) describes `html_last_updated_fmt` as accepting a string in `strftime()` format:

> <dl><dt>html_last_updated_fmt</dt>
> <dd>If this is not None, a ‘Last updated on:’ timestamp is inserted at every page bottom, using the given <code>strftime()</code> format. The empty string is equivalent to <code>'%b %d, %Y'</code> (or a locale-dependent equivalent).</dd></dl>

`%-d` is a valid `strftime()` format on my system, which represents the day without leading zeros, i.e. `1` to `31`. However this is not parsed correctly by Sphinx:
```python
from datetime import datetime
from sphinx.util.i18n import format_date

now = datetime.now()

now.strftime('%d %-d')
# '04 4'

format_date('%d %-d', now, 'en')
# u'04 %-d'
```

Either the docs should be modified to indicate the actual list of acceptable formats, which seems to be contained in a dict [here](https://github.com/sphinx-doc/sphinx/blob/f746959bbd5127ee448b38efc0f014956beb0827/sphinx/util/i18n.py#L153), or the `format_date` function should be modified to accept all valid `strftime()` formats.

**Comment by tk0miya** [comment]
Fixed by #4510.
Thank you for reporting!
