### ISSUE TITLE
[q] sphinx-build Threads - when/how to use them - rules of thumb - tips/tricks

### ISSUE THREAD

**Issue by ghost** [sphinx-doc/sphinx#4277]
A question about using the sphinx-build -j option. Does anyone have general tips, advice, rules-of-thumb for using them? My brief experiments don't show much improvement. Is it my platform, resources, sphinx project?

And thumbs up for not having to know all this if/when https://github.com/sphinx-doc/sphinx/issues/3947 is implemented.

**Comment by tk0miya** [comment]
Unfortunately I don't know that...

**Comment by tk0miya** [comment]
It seems nobody know the best settings.
But #3947 is added now. So let's improve it.
I'm closing this now because of #3947.

Thanks,
