### ISSUE TITLE
autodoc ignores documented attributes when using f-strings

### ISSUE THREAD

**Issue by calconst** [sphinx-doc/sphinx#4327]
Subject: autodoc ignores documented attributes when using f-strings anywhere in the module

### Problem

If a f-string is used in a module, all module level, class level, and class instance level attributes
in the module are ignored.

#### Procedure to reproduce the problem

In the following code, `MODULE_CONST`, `ExampleClass.my_class_var2`, and `ExampleClass.my_property` will
not appear the HTML output produced by Sphinx.

```
MODULE_CONST = 1
""" Constant for the module. """

class ExampleClass:
    """ Class docs """

    my_class_var2 = None
    """  This is a class attribute. """

    def __init__(self, arg1: int):

        self.my_property = arg1
        """ This is an instance attribute. """

    def oh_my(self) -> str:
        """ Oh my!! """
        x = 42 
        # Here is the source of the problem.
        blah = f"big issue here {x}"
        return blah
```

However, if one replaces the f-string `blah = f"big issue here {x}"` with a simple string
Sphinx generates documentation for the attributes as expected.

#### Error logs / results

Sphinx does not generate any warnings or errors.

This is documentation I get using the example above:
```
class example.ExampleClass(arg1: int)
    Bases: object

    Class docs

oh_my() -> str
    Oh my!!
```

#### Expected results

Module attributes, class attributes, and instance attributes should be documented if they contain docstrings.
In particular, using a f-string should not remove the documentation of class or module attributes.

Here's an example of expected documentation, which is obtained if f-string are not used:

```
class example.ExampleClass(arg1: int)
    Bases: object

    Class docs

my_class_var2 = None
    This is a class attribute.

my_property = None
    This is an instance attribute.

oh_my() -> str
    Oh my!!

example.MODULE_CONST = 1
    Constant for the module.
```

### Environment info
- OS: Windows 7, 64-bit
- Python version: 3.6.2
- Sphinx version: 1.6.5

### Related tickets

[#4301](https://github.com/sphinx-doc/sphinx/issues/4301)

**Comment by tk0miya** [comment]
Could you try Sphinx on master branch? Then it would be resolved it.

**Comment by calconst** [comment]
I tried the master branch as suggested (Sphinx-1.7.dev20171221) and it looks like the problem is addressed; I got the results I expected.
