### ISSUE TITLE
Make directives and roles for math to sphinx-core

### ISSUE THREAD

**Issue by tk0miya** [sphinx-doc/sphinx#4333]
### Problem
- Since docutils-0.8, `math` directive and `math` role became a part of reST spec.
  - http://docutils.sourceforge.net/docs/ref/rst/directives.html#math
  - http://docutils.sourceforge.net/docs/ref/rst/roles.html#math
- In sphinx, users have to enable one of math extension to use them.

#### Expected results
Enable to use the directive and role by default

**Comment by jfbu** [comment]
I think policy of Docutils to insert contents verbatim if output format does not support natively math input is fine. And that it is strange for latex output to have to activate either mathjax or imgmath extensions which are for html like targets. Thus +1 for this feature.
