### ISSUE TITLE
sphinx-apidoc generates references to non-existing files in TOC for folders containing only an empty __init__.py

### ISSUE THREAD

**Issue by zufallsgenerator** [sphinx-doc/sphinx#4334]
### Problem
When using sphinx-apidoc to generate RST files, there are references to non-existing files generated in the TOC of a package when encountering a directory with only an empty __init__.py.

#### Procedure to reproduce the problem
```
$ sphinx-apidoc ./sphinx-toc-test/ -o ./source
```

#### Error logs / results
```
Creating file ./source/mypackage.rst.
Creating file ./source/mypackage.something.rst.
Creating file ./source/modules.rst.
```

#### Expected results
In ./source/mypackage.rst:
```
mypackage package
=================

Subpackages
-----------

.. toctree::

    mypackage.resource
    mypackage.something
...
```
*mypackage.resource* is reference, but the file *mypackage.resource.rst* does not exists.
The same inconsistencies exists with the --implicit-namespaces flag.

The solution should be to only reference files that get created. I've been working on a patch that I want to submit, including test cases.

### Reproducible project / your project
A zip file with an example file structure is provided.
[sphinx-toc-test.zip](https://github.com/sphinx-doc/sphinx/files/1580096/sphinx-toc-test.zip)

### Environment info
- OS: OSX 10.10.5
- Python version: 3.6
- Sphinx version: 1.6.5

**Comment by zufallsgenerator** [comment]
[sphinx-toc-test.zip](https://github.com/sphinx-doc/sphinx/files/1580089/sphinx-toc-test.zip)

**Comment by zufallsgenerator** [comment]
I think this is related to implicit namespaces #2949 although I don't think it's caused by that fix. @arcivanov you wrote that patch, does my patch make sense? @tk0miya ?

This is my first contribution by the way, so I hope I managed to follow all the guidelines correctly.

**Comment by arcivanov** [comment]
What's the significance of the *empty* `__init__.py` vs a non-empty one? It's still a package and should be treated as such.

**Comment by zufallsgenerator** [comment]
@arcivanov I tend to agree. It's there since the first commit to this repo, though: https://github.com/sphinx-doc/sphinx/commit/87cebf1a070a2c8956ef2939f43d53bf826600e9#diff-65ef293822255803d59c56efd9002e27
@birkenfeld Did you write this code? It's ages ago, I know.
