### ISSUE TITLE
tox testing of texinfo fails due to unset PERL5LIB environment variable

### ISSUE THREAD

**Issue by jfbu** [sphinx-doc/sphinx#4339]
#### Procedure to reproduce the problem
```
tox -e py36 tests/test_build_texinfo.py::test_texinfo
```

#### Error logs / results
```
>                   assert False, 'makeinfo exited with return code %s' % retcode
E                   AssertionError: makeinfo exited with return code 2
E                   assert False

tests/test_build_texinfo.py:68: AssertionError
----------------------------- Captured stdout call -----------------------------
b''
b"Can't locate Locale/Messages.pm in @INC (@INC contains: /sw/lib/texinfo /sw/share/texinfo/lib/Unicode-EastAsianWidth/lib /sw/share/texinfo /sw/share/texinfo /Library/Perl/5.16/darwin-thread-multi-2level /Library/Perl/5.16 /Network/Library/Perl/5.16/darwin-thread-multi-2level /Network/Library/Perl/5.16 /Library/Perl/Updates/5.16.2 /System/Library/Perl/5.16/darwin-thread-multi-2level /System/Library/Perl/5.16 /System/Library/Perl/Extras/5.16/darwin-thread-multi-2level /System/Library/Perl/Extras/5.16 .) at /sw/bin/makeinfo line 109.\nBEGIN failed--compilation aborted at /sw/bin/makeinfo line 109.\n"
```

#### Expected results

tox testing succeeds of current master branch (2e04c2a05)

Success is obtained if ``tox.ini`` includes ``PERL5LIB`` among ``passenv`` arguments.

Discussed [here](https://github.com/sphinx-doc/sphinx/pull/4320#issuecomment-353651076) by @stephenfin who identified the cause as a missing environment variable in ``tox.ini``. The missing one for this problem at my locale is ``PERL5LIB``.

### Environment info
- OS: Mac 10.9.5 with a Fink installed makeinfo (texi2any  (GNU texinfo) 6.3)
- Python version: 3.6.4
- Sphinx version: master  (2e04c2a05)
- tox

**Comment by tk0miya** [comment]
@stephenfin could you fix this please?

**Comment by jfbu** [comment]
It would be nice if tox allowed an additional `tox.ini`,  say `tox.ini2`. Contributors to Sphinx could create such a file which would _not_ be under git version control, and would be used for needed additional environment variables by Sphinx contributors at their locale.

**Comment by stephenfin** [comment]
> @stephenfin could you fix this please?

Done in #4341.



> It would be nice if tox allowed an additional tox.ini, say tox.ini2. Contributors to Sphinx could create such a file which would not be under git version control, and would be used for needed additional environment variables by Sphinx contributors at their locale.

Can't say I agree with this one. If there are environment variables that one user needs to pass through for successful tests, then it's likely other users will also benefit from them and they should be part of the default configuration. On the other hand, if it's a case of hacking the file while actively developing something, you can simply modify the `tox.ini` to use `passenv = *` and tell Git to ignore changes to this file like so:

    git update-index --skip-worktree tox.ini

Once you've done hacking, you can undo this like so:

    git update-index --no-skip-worktree tox.ini
    git checkout -f tox.ini

If you do this, you should `tox` one last time after to make sure you haven't forgotten anything. Perhaps we can add this note to `tox.ini`, if this is indeed something you do regularly?

**Comment by jfbu** [comment]
@stephenfin thanks for the git tip. I would probably go for the 

    git stash save "passenv hack"

and then do ``git apply`` before testing after having checked out the branch to test, expecting that it is improbable that merge conflicts will be frequent. (hmm... perhaps they will each time we upstream at Sphinx need to add some new environment variable ;-) ). I can clean up in various ways after that.

I think we could add a note to ``tox.ini`` about telling testers to report to us upstream any missing environment variable they might need.
