### ISSUE TITLE
sphinx v 1.6.5 - extension error with sphixcontrib.disqus

### ISSUE THREAD

**Issue by mennamorato** [sphinx-doc/sphinx#4340]
Subject: using ReadTheDocs to build documents for the past 6 months using Sphinx 1.5.6, but when it was changed to V1.6.5 it started to fail builds with disqus extension

### Problem
- build fails with this message
Running Sphinx v1.6.5
making output directory...
loading translations [en]... done

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/aviatrix/envs/latest/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 305, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/aviatrix/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 196, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/aviatrix/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 456, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/aviatrix/envs/latest/local/lib/python2.7/site-packages/sphinx/registry.py", line 199, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname, err)
ExtensionError: Could not import extension sphinxcontrib.disqus (exception: cannot import name SphinxError)

Extension error:
Could not import extension sphinxcontrib.disqus (exception: cannot import name SphinxError)

#### Procedure to reproduce the problem
```
<Paste your command-line here which cause the problem>
```

#### Error logs / results
```
<Paste your error log here>
```
- <public link of unexpected result if you have>

#### Expected results
<Describe what to actually do>

### Reproducible project / your project
- <link to your project, or attach zipped small project sample>

### Environment info
- OS: <Unix/Linux/Mac/Win/other with version>
- Python version:
- Sphinx version: 1 6.5
- <Extra tools e.g.: Browser, tex or something else>

**Comment by tk0miya** [comment]
I think this is a bug of sphinxcontrib-disqus as you said.
Could you report this to disqus project?

**Comment by mennamorato** [comment]
will do

**Comment by mennamorato** [comment]
Hi
this is definitely a Sphinx issue as I just installed v1.6.5 locally on my PC and got this:
![image](https://user-images.githubusercontent.com/1237638/34471338-d2f16868-ef14-11e7-9af0-a3baaa0ac6aa.png)

I update from v1.5.5, which works fine.

I really need to fix this *soon* ... any pointers?  thanks!

**Comment by tk0miya** [comment]
I think it is another problem.
Could you run `sphinx-build` with `-P` option (ex. `sphinx-build -P -b html /path/to/srcdir /path/to/outdir`)?
Then you can see what error happened inside Sphinx. So please let me know it.

Note: after that, you can exit debug mode with `quit` or `exit` command.

I feel your case is very strange. The SphinxError is a part of Sphinx. So I guess your environment has broken.

**Comment by mennamorato** [comment]
Thank you so much! Here is the output, my environment has not changed in many months and v1.5.5 works perfectly fine.
![image](https://user-images.githubusercontent.com/1237638/34574586-da627438-f145-11e7-81c5-637020179dfb.png)

**Comment by tk0miya** [comment]
It seems a bug of disqus module: see https://github.com/Robpol86/sphinxcontrib-disqus/pull/7

**Comment by tk0miya** [comment]
note: disqus extension tries to import `SphinxError` from `sphinx.application` module.
But officially it is placed at `sphinx.errors` module.
http://www.sphinx-doc.org/en/stable/extdev/appapi.html#sphinx.errors.SphinxError

**Comment by mennamorato** [comment]
ahhh!  Thank you !
