### ISSUE TITLE
URL parsing problem when the path contains "_-"

### ISSUE THREAD

**Issue by lazka** [sphinx-doc/sphinx#4350]
Given reST:

```
http://example.com/a_-b
```

sphinx output:

`WARNING: Unknown target name: "a".`

Expected output:

None. The whole text should be treated as a URL.

### Environment info
- OS: Debian
- Python version: 2.7.14
- Sphinx version: 1.6.5

**Comment by jfbu** [comment]
This is (possibly) a reStructuredText issue. Their [docs](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#hyperlink-targets) says:

> If an external hyperlink target's URI contains an underscore as its last character, it must be escaped to avoid being mistaken for an indirect hyperlink target

Here, it is not last character but

    http://example.com/a\_-b

does fix the issue. Can your report this at [Docutils](https://sourceforge.net/p/docutils/bugs/?source=navbar) ?

**Comment by lazka** [comment]
> does fix the issue. 

Yes, it does, thanks!

> Can your report this at Docutils ?

Reproduced with rst2html and forwarded to https://sourceforge.net/p/docutils/bugs/336/

Thanks, and feel free to close this.

**Comment by jfbu** [comment]
Thanks for reporting upstream, indeed as  ``http://example.com/a_b`` raises no Docutils error with `rst2html.py`, but ``http://example.com/a_-b`` does, I think it is a problem of Docutils.

Closing this as not being a bug of Sphinx. Thanks for reporting!
