### ISSUE TITLE
`make man` replacing ellipsis string (...) with single-character

### ISSUE THREAD

**Issue by marshallward** [sphinx-doc/sphinx#4357]
Subject: `make man` replacing ellipsis string (...) with single-character

### Problem
- When I do `make man` using a default project makefile on a file containing three dots ... (0x2e) it instead replaces this with some sort of single-character ellipsis … (U+2026, 0x e2 80 a6).

Note that `rst2man` does not create this character.  But I also cannot find any reference to this character in the source, so I am not sure where it is coming from.

#### Procedure to reproduce the problem

Make any generate project (sphinx-quickstart), place three periods (0x2e) in any text file, then run `make man` and inspect the output in `_build/make`.

#### Expected results
I would prefer to avoid non-ASCII characters in my manpages, so would prefer that ... be explicitly substituted rather than …

### Environment info
- OS: Linux 4.14.5
- Python version: 3.6.3
- Sphinx version: 1.6.5

**Comment by jfbu** [comment]
This is due to SmartQuotes Docutils transform. You can deactivate it by creating a file ``docutils.conf`` in same repertory as ``conf.py``, with contents

```
[parsers]
	smart_quotes = no
```

(uses a tabulation on second line; _edit_: which however is not needed).

Relates #3967, #3917, ...

**Comment by marshallward** [comment]
This doesn't seem to be working for me unfortunately.  Would you be able to try it out and confirm that it works for you?

**Comment by jfbu** [comment]
It works. However checking [Docutils doc](http://docutils.sourceforge.net/docs/user/config.html#configuration-file-syntax) for syntax I should perhaps not have left a tabulation at start of line. But it uses [ConfigParser](https://docs.python.org/3/library/configparser.html?highlight=configparser#quick-start) see also [ConfigParser accepted syntax](https://docs.python.org/3/library/configparser.html?highlight=configparser#supported-ini-file-structure) which says

> Leading and trailing whitespace is removed from keys and values. 

Anyway, you can try
```
[parsers]
smart_quotes: no
```

but I think most probably you misplaced the file or misnamed it.

If this does not solve your problem, please provide a minimal example. The [Sphinx 1.6.5 conf.py documentation](http://www.sphinx-doc.org/en/1.6.5/config.html) does provide the relevant links to Docutils. 

edit: in my testing, it is not even needed to issue `make clean` or to pass the `-E` option to `sphinx-build` after changes to the `docutils.conf` file relative to the `smart_quotes` setting. The next `make man` or `sphinx-build -b man . _build/man` obeys it immediately.

**Comment by marshallward** [comment]
OK it seems to be working after a `make clean`, which I was missing.  Not sure why you did not need to do it, but it does seem to be working now.

There may be some other nuance or lingering config file around, but either way it seems to work now.

My next question was how to restrict this to the man builds, but that seems to be an ongoing topic in the referenced addresses.

**Comment by jfbu** [comment]
You are right that after adding a previously non-existing `docutils.conf` file a `make clean` is needed. My testing was with an already existing file where one would toggle the `smart_quotes` setting.

It is good that this tidbit is documented here in case people encounter the problem.

Regarding restricting this to  ``man`` (and ``text``) builds, this is part of #4360 currently under discussion. We have a problem though that if user makes use of the Makefile created by sphinx-quickstart (whether the lean "make-mode" one or the legacy one now produced under sphinx-quickstart option ``--no-use-make-mode``) then by default the pickled environment is shared across build targets (in ``$BUILDDIR/doctrees/``), hence `make html` immediately followed by `make man` will still apply smart quotes to the latter (in current version of #4360). 

In contrast direct use of `sphinx-build` by default stores the cached files separately in each build repertory (in ``_build/<target>/.doctrees/`` sub-repertory) hence #4360 works fine with no further ado.

**Comment by jfbu** [comment]
ah I forgot to say, that if #4360 is merged, then you should remove the ``docutils.conf`` file: it is ignored if it says to activate smart-quotes (because if Sphinx says not to, then preventive measures are taken prior to handing over the parsing to Docutils), but it is obeyed if its says to deactivate them (because even if Sphinx says to activate them, Docutils will read its config file and obey it).

**Comment by marshallward** [comment]
Thanks, that is useful to know.  Currently, my man build is integrated into `setup.py` (using a `BuildDoc` subclass) and I expect that would be the main way that manpages are built.  Do the `BuildDoc` commands use its own load `.doctrees` directory?

**Comment by jfbu** [comment]
I looked at the ``setup.py`` https://github.com/marshallward/f90nml. Currently you seem to use Sphinx only for ``man``, but if you add other builders, then you could insert at https://github.com/marshallward/f90nml/blob/master/setup.py#L57

```
            self.fresh_env = True
            self.all_files = True
```

which will force re-parsing of source files. Indeed, from a brief look at ``BuildDoc`` class in ``sphinx.setup_command`` the ``doctree_dir`` is shared and location not easily customizable. Hence the above way.

I tested this by replacing ``self.builder = 'man'`` by ``self.builder = 'html, man'`` in order to get your ``setup.py install`` to build simultaneously html and man version of docs. With #4360 in place, I get the hoped-for behaviour that Smart Quotes is skipped for the man page, and is applied for the html pages.

**Comment by marshallward** [comment]
Thanks for having a look, I'll give that a try.  I don't generally expect people to build the HTML docs using setup.py (the man build is for the bin script) but I think there's enough info here to work it out.

Thanks again for your help, feel free to close this issue if you like.

**Comment by jfbu** [comment]
Sphinx 1.6.6. will not apply Smart Quotes to ``man`` builder output.

**Comment by marshallward** [comment]
Fantastic, thanks for the update!
