### ISSUE TITLE
Sphinx not parallel installable for python2 and python3

### ISSUE THREAD

**Issue by gtristan** [sphinx-doc/sphinx#4375]
There is no stable entry point one can rely on to invoke sphinx-apidoc or sphinx-build specifically for python3, as far as I can see there is only *${prefix}/bin/sphinx-build* and  *${prefix}/bin/sphinx-apidoc*.

It is unclear, on any given system, if the `/usr/bin/sphinx-*` tools will be using python2 or python3, however projects which depend on sphinx must be able to assert that sphinx is installed for their python version, and have an API stable way of invoking sphinx for their python version.

I tried installing python-sphinx and python3-sphinx on debian, it did not complain about a conflict and happily installed both, the resulting `/usr/bin/sphinx-build` is for python2, and I cannot find an entry point it may have added for python3.

**Comment by stephenfin** [comment]
@tk0miya I discussed this with @gtristan on `#sphinx-doc` today and am happy to work on it. Looks like something that we'll need to work with packagers to really solve and it won't be necessary after Sphinx 2.0 (which should be Python 3-only). However, it would be a good enhancement until then.

**Comment by tk0miya** [comment]
@stephenfin thank you for your help.
I don't have knowledge for this. So it would be nice if you help us.

**Comment by tk0miya** [comment]
It seems `/usr/bin/sphnx-*` are hyperlink to `/usr/share/sphinx/scripts/python*/sphinx-*`.
```
root@f45348219a96:/# ls -l /usr/bin/sphinx-build
lrwxrwxrwx 1 root root 44 Jan 21 18:01 /usr/bin/sphinx-build -> ../share/sphinx/scripts/python2/sphinx-build
```
I think you can use Sphinx with python3 if you add `/usr/share/sphinx/scripts/python3` to PATH.

I think this is packaging problem, not Sphinx itself. So I recommend you to report this to Debian project.

**Comment by gtristan** [comment]
if the user has to setup any special environment to specify which API to use, it is not truely parallel installable.

Parallel installability would just require that your entry point be accessible under a different name (something like sphinx3-build would work), for access via python imports this is not an issue because of how people generally install into versioned subdirectories of a python installation, and once you are running python code you have already selected your python version so only the desired API is found, this is not so when using the entry point, as such, the command "sphinx-build" is ambiguous on any given host.

Where this hurts the most is not when someone wants to manually generate docs on their machine, or be the only one who uses their own makefile. The goal should rather be that any package which depends on sphinx can by itself assert that the sphinx API (and version) they need is present on the build host automatically in their build scripts, bailing out at configure time with a comprehensive error should the host prerequisites not be found.

**Comment by stephenfin** [comment]
@tk0miya Not quite. You can test this by installing via pip.

```
$ pip install --user sphinx
$ whereis sphinx-build
sphinx-build: /home/sfinucan/.local/bin/sphinx-build
$ cat /home/sfinucan/.local/bin/sphinx-build | head -1
#!/usr/bin/python2
$ pip3 install --user sphinx
$ whereis sphinx-build
sphinx-build: /home/sfinucan/.local/bin/sphinx-build
$ cat /home/sfinucan/.local/bin/sphinx-build | head -1
#!/usr/bin/python3
```

Installing the Python3 version has caused the old, Python 2 version to be overwritten. Whatever about packaging on other environments, this is a bug with out installation script, IMO.

@tk0miya I'm still working on this, btw. I want to solve it as part of a unified `sphinx` executable (we will have a `sphinx`, `sphinx2`, `sphinx2.7` etc.)

**Comment by tk0miya** [comment]
>if the user has to setup any special environment to specify which API to use, it is not truely parallel installable.

What do you mean "API"? Python version?

**Comment by gtristan** [comment]
> What do you mean "API"? Python version?

In this case yes, sorry i tend to use the word API loosely but its also a loosely defined term, and usually used when discussing stability, i.e relying in the interfaces to remain compatible for downstreams which depend on consistency (in this case, python projects who have build scripts which directly invoke sphinx CLI by name, and expect it to continue working indefinitely).

It is in this sense, api incompatible to use a python2 sphinx-build entry point to document a python3 project, and vice versa.

Note that this is only because sphinx makes use of python imports to generate the docs for python projects; if sphinx were to do all the parsing required itself in order to generate docs, it could use the same CLI name for any python version.

**Comment by tk0miya** [comment]
Thanks, I understand what you mean and what you want.
I know python version is related with autodoc builds. But I feel it is too much to make Sphinx parallel installable for this case. How about using virtualenv or `pythonX -m sphinx` instead?

**Comment by gtristan** [comment]
That is an option, i think @stephenfin mentioned something similar on irc, and that it will become a possibility in a later release after he breaks the internal python api we would have to call in that module.

As i understand it, its not yet a possibility, or there is an upcomming api break which means i should just wait for now.

**Comment by tk0miya** [comment]
I marked this as wontfix.
Thank you for your proposal!
