### ISSUE TITLE
skipsdist option bothers developers.

### ISSUE THREAD

**Issue by tk0miya** [sphinx-doc/sphinx#4378]
### Problem
- Since #4338, `skipsdist` option was introduced to our tox.ini 
- Surely, it makes our test faster
- But it bothers local development

#### Procedure to reproduce the problem
```
$ tox -e py27  # => success
$ rm sphinx/application.py  # => try to make tests failed
$ tox -e py27  # => but it still succeeds...
$ tox -r -e py27  # => it fails after recreate tox environment
```

#### Expected results
- tox should refer latest source code

### Environment info
- OS: Mac
- Python version: All version
- Sphinx version: master branch

**Comment by tk0miya** [comment]
I think `skipsdist` is very useful on CI servers, because it is invoked at disposable environment.
But local devleopment is not. It uses same environment for many time.

So I think `usedevelop` option is better for local development. It is a bit faster than making sdist package:


Time to update environment (usedevelop):
```
tox -e py27 --notest  2.83s user 0.94s system 92% cpu 4.057 total
tox -e py27 --notest  2.56s user 0.82s system 95% cpu 3.516 total
tox -e py27 --notest  2.43s user 0.78s system 94% cpu 3.382 total
```

Time to update environment (no options):
```
tox -e py27 --notest  9.16s user 4.71s system 85% cpu 16.206 total
tox -e py27 --notest  8.12s user 4.49s system 85% cpu 14.755 total
tox -e py27 --notest  9.30s user 4.80s system 86% cpu 16.350 total
```

Ref: Time to update environment (skipsdist):
```
tox -e py27 --notest  0.99s user 0.31s system 86% cpu 1.506 total
```

**Comment by tk0miya** [comment]
I guess `.[test,websupport]` on deps section installs Sphinx itself. And tox does not update source code because of `skipsdist` option.

@stephenfin Any idea?

**Comment by stephenfin** [comment]
Ah, good catch. I'm ok using `usedevelop` and can submit a patch, if it would help?

**Comment by tk0miya** [comment]
Thanks, I'll do it later.

BTW, do you know the way to switch `skipsdist` and `usedevelop`? In Travis CI, `skipsdist` is much better. So it would be nice if we can switch only on Travis CI.
