### ISSUE TITLE
Proposal: Change release and tag model

### ISSUE THREAD

**Issue by tk0miya** [sphinx-doc/sphinx#4398]
### Problem
- The document of sphinx is published as x.y.z, not x.y
    - ex. http://www.sphinx-doc.org/en/1.6.5/

#### Expected results
- All the documents are published as x.y

### Proposal

- Add a tag `x.y` to latest release of `x.y` series
    - The tag will be moved on each minor release
- Give a `x.y.0` version to first major release package (cf. 1.7.0)
    - So far the first major releases don't have revision number (cf. 1.5, 1.6)
    - It reduces confusion of `x.y` series with `x.y` release
    - It enables to follow semver rule
- Rename release tags to `releases/x.y.z`.
    - It also reduces confusion of series with release

### Not to do

- This does not change branch models
    - After this change, we continue to use both `stable` and `master`
    - New branch model does not related with our document management model. So it is not needed to change.
    - We don't want to maintain the old releases (at least now)

### Related issues

- #4211

**Comment by tk0miya** [comment]
@shimizukawa @stephenfin @jfbu This is my proposal for branch and tag model discussed at #4211.
What do you think? IMO, it is simple and easy to go for us to arrange tag rules.

**Comment by shimizukawa** [comment]
+1.

On our development scale, I think that it is appropriate to operate only the 2 branches rather than having many past branches.

**Comment by stephenfin** [comment]
A (soft 😄) -1.

I completely understand the reason not to have many past branches: we simply do not have the bandwidth. Given that you folks are the maintainers, any change here is going to overwhelmingly impact you. However, tags are supposed to represent a single point in time and I'm not sure about moving them. To me, it sounds like force pushing. I'd like to propose one of the two below options:

- We use `stable/X.Y` branches but we emphasise that only the latest `stable/X.Y` branch is supported. Any pull requests to older branches can be closed by a bot. If someone wants to maintain older branches in the future, we can re-evaluate this.
- We keep things as they are and simply add a "this is not the latest version of Sphinx" message to the top of old pages. This requires an extra click from the user but will solve my biggest issue.

I'd much rather the first option, but it's not really my call.

PS: Thanks for following up on this, @tk0miya 😄

**Comment by jfbu** [comment]
I would propose to create the `x.y` tag only when `x.y+1.0` is released. For example future 1.7 will have its first release as `1.7.0`, and only then will a `1.6` tag be created, as an alias to either `1.6.6` or  `1.6.7` if there is an `1.6.7` at the time of `1.7.0`. This way we never move  the tags targets.

Hence during life-time of `1.7.x` series there is no `1.7` tag, but `1.7.0`, `1.7.1`, ... and the `1.7` tag is created only at time of release of `1.8.0`.

Unfortunately, this means tag names do not obey [PEP 440](https://www.python.org/dev/peps/pep-0440/) rules for package versions, which states that 

> X.Y and X.Y.0 are not considered distinct release numbers

but this is mitigated by the fact that Sphinx will not use `1.7` as a version number, only  as tag for its dev repo.

**Comment by tk0miya** [comment]
>We use stable/X.Y branches but we emphasise that only the latest stable/X.Y branch is supported.

For document use, `stable/X.Y` branch is not good. readthedocs uses the branch name for URL like 
`http://www.sphinx-doc.org/en/{branch_name}/`. So `stable/X.Y` becomes `http://www.sphinx-doc.org/en/stable/X.Y/` (I've never tested the branch having slash in its name).
So I think simply `X.Y` is better for this case.

>Any pull requests to older branches can be closed by a bot.

Do you know good bot service for this?

>We keep things as they are and simply add a "this is not the latest version of Sphinx" message to the top of old pages. This requires an extra click from the user but will solve my biggest issue.

Current document already says "You are not using the most up to date version of the library. 1.6.6 is the newest version.".
(see http://www.sphinx-doc.org/en/1.5.6/)
Do you mean changing this message?

**Comment by tk0miya** [comment]
>I would propose to create the x.y tag only when x.y+1.0 is released. 

I think this is not much changed from now. Using `x.y` tag or branch gives us fixed URL for document.

For example, I just released 1.6.6 today. As a result, the URL for latest document of 1.6 series has been changed from http://www.sphinx-doc.org/en/1.6.5/ to http://www.sphinx-doc.org/en/1.6.5/ .
It means the URL is often changed (almost monthly) and hard to index to search engine.

Either tags and branches are fine to me. Personally, I prefer tags slightly because branch is "active" and always commitable and PR-able. We don't want to change anymore after the final release.

>Unfortunately, this means tag names do not obey PEP 440 rules for package versions,

Using both `x.y` and `x.y.z` tags is confusing. They are similar, but different. `x.y` is a series number, and `x.y.z` is a release number (version number). So I don't think `x.y` conflicts with PEP-440.

In addition, to avoid confusing, I proposed to use two tag-formats (`x.y` and `releases/x.y.z`) properly. Then we can know what the tag means easily from its name.

**Comment by stephenfin** [comment]
> Current document already says "You are not using the most up to date version of the library. 1.6.6 is the newest version.".
> (see http://www.sphinx-doc.org/en/1.5.6/)
> Do you mean changing this message?

No, this is perfect. I never noticed this before! It could do with being a bit more obvious (perhaps the entire width of the document) but that's a future change. Good to know!

> > We use stable/X.Y branches but we emphasise that only the latest stable/X.Y branch is supported.
> 
> For document use, stable/X.Y branch is not good. readthedocs uses the branch name for URL like
> http://www.sphinx-doc.org/en/{branch_name}/. So stable/X.Y becomes http://www.sphinx-doc.org/en/stable/X.Y/ (I've never tested the branch having slash in its name).
> So I think simply X.Y is better for this case.

That's a good point. I don't notice this on docs.openstack.org because they're not hosted on readthedocs.org. For my own projects, it seems the tag is "slugified" and all non-alphanumeric characters replaced with a hyphen. For example, patchwork.readthedocs.io/en/stable-2.0/ (comes from tag `stable/2.0`).

I wonder if we could add prefix redirects (or _aliases_) on ReadTheDocs? For example, `2.0` -> `stable-2.0`. This would resolve a lot of our problems, I suspect. If not, perhaps I should add this feature. I will investigate.

> Either tags and branches are fine to me. Personally, I prefer tags slightly because branch is "active" and always commitable and PR-able. We don't want to change anymore after the final release.

Yes, as noted above I would prefer branches as tags are supposed to be (IMO) immutable. Also, I'd like to allow the possibility of editing the branch in the future.

> In addition, to avoid confusing, I proposed to use two tag-formats (`x.y` and `releases/x.y.z`) properly. Then we can know what the tag means easily from its name.

The biggest issue with the `releases/x.y.z` format is that a lot of tooling expects `X.Y.Z` or `vX.Y.Z` formats. If we change that, we break said tooling.

**Comment by tk0miya** [comment]
>For my own projects, it seems the tag is "slugified" and all non-alphanumeric characters replaced with a hyphen. For example, patchwork.readthedocs.io/en/stable-2.0/ (comes from tag stable/2.0).

Good to know. But I feel strange for `stable-` suffix for URL. Of course, we'll see the suffix on version switching interface like (`stable-1.6`, `stable-1.5`, `stable-1.4`...)
![2018-01-10 1 46 57](https://user-images.githubusercontent.com/748828/34732297-34a41fd0-f5a8-11e7-9c9b-f6c8c7009473.png)

I'd like to say again, I feel `X.Y` is better for readthedocs.

>Yes, as noted above I would prefer branches as tags are supposed to be (IMO) immutable. Also, I'd like to allow the possibility of editing the branch in the future.

Hmm? tags are not immutable. It can be changed easily.
```
$ git tag -d 1.6  # remove a tag on local
$ git tag 1.6
$ git push origin :1.6  # remove a tag on remote
$ git push origin --tags
```

And we can also change tag to branch easily. It does not prevent future availability.

Anyway, we need to use any good service to introduce branches for this use case.
But I don't know good one. Do you know it?

>The biggest issue with the releases/x.y.z format is that a lot of tooling expects X.Y.Z or vX.Y.Z formats. If we change that, we break said tooling.

Really? I don't know that. Then I feel `vX.Y` is better.

out of curiosity: Could you tell me any tooling expects the format? I'd like check it.

**Comment by tk0miya** [comment]
>Give a x.y.0 version to first major release package (cf. 1.7.0)
>So far the first major releases don't have revision number (cf. 1.5, 1.6)
>It reduces confusion of x.y series with x.y release
>It enables to follow semver rule

I think nobody objects to this rule.  So I will release next major release as `1.7.0`.

**Comment by stephenfin** [comment]
> I'd like to say again, I feel `X.Y` is better for readthedocs.

Yeah, I agree. Let's go with `X.Y`. Can we please use branches though? More on this below...

> Hmm? tags are not immutable. It can be changed easily.
>
>    $ git tag -d 1.6  # remove a tag on local
>    $ git tag 1.6
>    $ git push origin :1.6  # remove a tag on remote
>    $ git push origin --tags

Right, but we can also do this with branches.

```
$ git branch -D stable  # remove a branch on local
$ git branch stable
$ git push origin :stable  # remove a branch on remote
$ git push origin stable
```

This is basically a force push and, as we know, force pushes shouldn't be done on shared branches. I think doing this for tags is a bad idea that will cause pain for people. I'd really like to avoid this.

> Anyway, we need to use any good service to introduce branches for this use case.
> But I don't know good one. Do you know it?

What do you mean by "introduce branches"?

> > The biggest issue with the releases/x.y.z format is that a lot of tooling expects X.Y.Z or vX.Y.Z formats. If we change that, we break said tooling.
>
> Really? I don't know that. Then I feel vX.Y is better.
> 
> out of curiosity: Could you tell me any tooling expects the format? I'd like check it.

Sure. The two that jump to mind are `reno` (for release note management) and `pbr` (a setuptools plugin that configures some defaults for us). I'm sure there are many more.

**Comment by stephenfin** [comment]
> I think nobody objects to this rule. So I will release next major release as 1.7.0.

Agreed. `1.7.0` it is. 🎆

**Comment by tk0miya** [comment]
>Anyway, we need to use any good service to introduce branches for this use case.
>But I don't know good one. Do you know it?
>
>What do you mean by "introduce branches"?

We have two ways to manage `X.Y` series; branches and tags. Both are almost same. So I feel either is fine.
The my last worry about using branch is that developers can send PRs to old branches.

You'd said like following:

> Any pull requests to older branches can be closed by a bot.

But I don't know good one to do that. So I don't agree to adopt using branches.
I think it is last piece for adoption.

Note: we don't have any servers. so it would be nice if we can use any free service.

**Comment by stephenfin** [comment]
@tk0miya I'll research and find one. If there isn't one, I write one myself. We use them for OpenStack so they do exist.

In the interim, is the `1.7-release` branch a temporary one?

**Comment by tk0miya** [comment]
>I'll research and find one. If there isn't one, I write one myself. We use them for OpenStack so they do exist.

Thanks, but we don't have any servers and 💰 . So it would be nice if we can freely use it.
It might go well if the tooling works on CI servers.

>In the interim, is the 1.7-release branch a temporary one?

Yes, this branch is temporary. We've usually used such named branch during pre-release.

**Comment by jfbu** [comment]
> Yes, this branch is temporary. We've usually used such named branch during pre-release.

For people reading this thread, anything merged (only) to master branch now will not be released before 1.8.0, which is next major after upcoming one 1.7.0. When 1.7.0 is released it will become new stable branch, for bug fixes. Patches which will have been merged to master in the interim period will not be in that stable branch but only in the master branch. Already now a priori PRs merged to 1.7-release should not introduce new features only bug fixes.

**Comment by tk0miya** [comment]
ping @shimizukawa 
Do you have time for such changing? AFAIK there are some tasks around tags/branch models (transifex, readthedocs and so on). If you don't have, we can't move to new model.
So please let me know that.

**Comment by shimizukawa** [comment]
I understood the conclusion in this discussion as follows..

branches:

- `master`: next major release that accept new features.
- `stable`: current stable release that only accept bug fixes.
- `X.Y-release`: feature freeze for a next major release (that removed after major releasing)

tags:

- `X.Y`: Point to latest release of X.Y series to build doc on RTD (en)
- `vX.Y.Z`: release tag.

I think it's OK and no objection from me.

Sphinx's official document (en) is not affected by the above policy. As before, once a new tag is created, manually configure the new version in RTD's build settings (there is a possibility that this can be automated in the future).

--------

Regarding translation documents, X.Y version name is already used to display the latest one of the series of X.Y. For this reason, the above policy will not affect how to build translation documents. (BTW, automatic build of translated document has stopped because the https: //drone.io/ service has ended. I plan to fix the automatic build to work with travis.)

**Comment by tk0miya** [comment]
@shimizukawa almost right

>tags:
>X.Y: Point to latest release of X.Y series to build doc on RTD (en)

This is not determined yet. We might use branches for this purpose if we find good tooling.
(see my comment above: https://github.com/sphinx-doc/sphinx/issues/4398#issuecomment-359247403)

I'd like to choose tag to manage series if no tooling found within a week (because we have new major release soon!).

Note: I don't mean this choice does not prevent to move branch model in future. It's only our first step of migration.

Anyway, I'm glad to hear that these changes does not affect to translation.

**Comment by stephenfin** [comment]
> This is not determined yet. We might use branches for this purpose if we find good tooling.
> (see my comment above: #4398 (comment))

I'm still investigating this. I want to write one myself using [hubot](hubot.github.com) but I haven't had time. How about using `X.Y` branches and then deleting the branch and replacing it with an `X.Y` tag at EOL? That way we don't break references and don't move tags about.

**Comment by tk0miya** [comment]
> How about using X.Y branches and then deleting the branch and replacing it with an X.Y tag at EOL? 

Sounds good. It seems very easy and simple.
What we should do is renaming stable to `X.Y` branch and replace it by tag on next major release.
Any tooling is not needed. That's perfect.
+1 for your idea.

@shimizukawa any opinion?

**Comment by shimizukawa** [comment]
+10!

**Comment by tk0miya** [comment]
It seems everyone gets agreed, right?

**Comment by tk0miya** [comment]
Now this model was mentioned at `CONTRIBUTING.rst` (see #4566).

And I made remaining tasks as #4565 and #4586.
So I'm closing this now.

Thank you!
