### ISSUE TITLE
Support for !(...) matcher

### ISSUE THREAD

**Issue by ghost** [sphinx-doc/sphinx#4400]
### Problem

It would be nice to have support for something like `!(pattern-list)` (documented [here](https://www.gnu.org/software/bash/manual/bashref.html#Pattern-Matching)) where `pattern-list` is `(foo|bar|quaz)` etc.

### Use-case

The use-case would be something like this:

```
.. toctree::
    :glob:

    gettingstarted
    fedora/!(gettingstarted)
```

### Test-case

The test-cases would probably look like:

```
pat = compile_matchers(['hello!(12).py']).pop()
assert not pat('hello1.py')
assert not pat('hello2.py')
assert not pat('hello!.py')
assert pat('hello3.py')
```

Of course I'm probably just missing an obvious workaround.

### Environment info
- OS: Fedora 27
- Python version: 2.7.14 / 3.6.3
- Sphinx version: 1.6.5

**Comment by tk0miya** [comment]
Why do you want to such complicated match? Please tell me your concrete use case.
I can't understand why `fedora/gettingstarted` is placed under `fedora/` directory.

**Comment by ghost** [comment]
Fair enough. I'll hoist it out.
