### ISSUE TITLE
base64 data image uris are being copied and converted to local embed paths

### ISSUE THREAD

**Issue by justinfx** [sphinx-doc/sphinx#4402]
Subject: Images using base64 encoded data uris are being converted to local embed paths

### Problem
When upgrading from sphinx 1.4.4 to 1.6.5 I have found a change in behaviour for image nodes that are using base64 encoded svgs, as data uris. Where previously they had preserved the data uri value, they are now being copied to the doctree images/embeded/<hash>.svg location. This breaks my existing logic because the absolute path is now local, and the images no longer work when the generated content is posted to a server.

I am not sure if this is related to the changes in #3589 and #3860. But that looks like it could be.

How to I ensure that my data uri is left unmodified so that it can be embedded in the generated content and not loaded from the filesystem?

#### Procedure to reproduce the problem
Use a custom directive or build the docutil nodes manually, and use a data uri for an image node:

```
icon = nodes.image( uri='data:image/svg+xml; ...' )
```

#### Error logs / results
The node is later transformed to:

```
print icon['uri']
# /path/to/project/root/build/doc/md/doctrees/images/embeded/36368b09e55adde9b6ed443770944b3b62c593d4.svg
```

#### Expected results
I would expect to keep the data uri unmodified so that it can be directly embedded instead of loaded from the filesystem.

```
print icon['uri']
# data:image/svg+xml; ...
```
### Environment info
- OS: Linux (Ubuntu 16.04)
- Python version: 2.7.6
- Sphinx version: 1.6.5

**Comment by justinfx** [comment]
It appears that `sphinx.builders.Builder.supported_data_uri_images` is a new magic undocumented property that fixes my issue if I set it to `True` on my custom builder class:

```python
class Builder(builders.Builder):
    supported_data_uri_images = True
```

Is this the expected usage, if I am creating a markdown builder and I want to be able to support data uri images?

**Comment by tk0miya** [comment]
Yes, the image translation feature follows `supported_data_uri_images`.

Surely, we need to update docs for the attributes.

**Comment by tk0miya** [comment]
Updated by #4517 
Thank you for reporting!
