### ISSUE TITLE
upgrade jquery included with Sphinx (to version 3.1.2)

### ISSUE THREAD

**Issue by dbkinder** [sphinx-doc/sphinx#4412]
jquery 3.1.1+ includes a [fix for reporting the offset of zero-sized elements](https://github.com/jquery/jquery/issues/3167) 

### Problem
When you place a label in a document ``.. label_here:`` before a heading, the HTML that's generated by Sphinx is an empty span:  ``<span id="label-here"></span>``.  A jquery reference to retrieve position information for this empty span  such as ``.offset().top`` (used to fix the problem with [anchor links being hidden behind a fixed header](https://stackoverflow.com/questions/10732690/offsetting-an-html-anchor-to-adjust-for-fixed-header)) does not return a consistent value in all browsers (firefox works, chrome does not).  The jquery 3.1.1 (and later) release fixes this problem, and should be included in an upcoming Sphinx release.

Workaround is to override the jquery.js Sphinx would copy to the generated html output by using the ``html_static_path`` with a jquery.js for 3.1.2.

**Comment by tk0miya** [comment]
Thank you for letting me know! I'll do that in next release.

**Comment by tk0miya** [comment]
Fixed by #4453.
Thank you for reporting :-)

**Comment by return42** [comment]
@tk0miya for what is https://github.com/sphinx-doc/sphinx/blob/master/sphinx/themes/basic/static/jquery-3.2.1.js good? Can we drop this file? Consider that unneeded files in `basic/static` will blowup the HTML build (e.g. see here https://www.sphinx-doc.org/en/master/_static/jquery-3.2.1.js)

**Comment by tk0miya** [comment]
It is requested by distro maintainers (see #1434).
I'm okay to drop it if everybody says okay. Do you have good idea?
