### ISSUE TITLE
autodoc classifies inherited classmethods as regular methods

### ISSUE THREAD

**Issue by 0phoff** [sphinx-doc/sphinx#4415]
Subject: autodoc classifies inherited _classmethods_ as _regular methods_

### Problem
- When a class inherits _classmethods_, they are marked as _regular methods_ in the documentation
- This might also be a problem with _staticmethods_ (not tested)

#### Expected results
Correctly mark them as _classmethods_ (correct CSS class).

### Reproducible project / your project
Code file
```python
class Base:
  def __init__(self):
    pass

  @classmethod
  def custom_method(cls):
    """ Dummy method to prove point """
    pass

class Derived(Base):
  def __init__(self):
    pass
```
Documentation file
```rst
.. autoclass:: project.Derived
   :members: custom_method
```

### Environment info
- OS: Linux
- Python version: 3.6
- Sphinx version: 1.7+

**Comment by tk0miya** [comment]
autodoc uses `parent.__dict__` to check the type of methods:
https://github.com/sphinx-doc/sphinx/blob/3b01697e11445ddfeda891aa53d410259fab6163/sphinx/ext/autodoc/__init__.py#L1262-L1268

But it does not work for derived classes.
we need to check `im_self` or `__self__` attribute.

Note:
https://github.com/russianidiot/isclassmethod.py/blob/master/isclassmethod/__init__.py

**Comment by tk0miya** [comment]
I found staticmethods on subclass are also classified as method.

**Comment by 0phoff** [comment]
Thank you for the quick respons! :+1: 
While it is not that important, it did frustrate me quite a bit... :stuck_out_tongue_closed_eyes:
