### ISSUE TITLE
Add spacing after comment hash for commented-out code without real comments.

### ISSUE THREAD

**Issue by ghost** [sphinx-doc/sphinx#4418]
Since there is nothing to differentiate from.
For example:
```py

# html_sidebars = {
#    'index': ['sidebarintro.html', 'sourcelink.html', 'searchbox.html'],
#    '**': ['sidebarlogo.html', 'localtoc.html', 'relations.html',
#           'sourcelink.html', 'searchbox.html']
```

**Comment by tk0miya** [comment]
Please let me know what version do you use?
https://github.com/sphinx-doc/sphinx/blob/f3f829664dce9ed8b236ffdb1d909524096d3b76/sphinx/templates/quickstart/conf.py_t#L96

It seems current sphinx already behaves as you said.
