### ISSUE TITLE
Docs conflict on use of rst_prolog and rst_epilog

### ISSUE THREAD

**Issue by trebawa** [sphinx-doc/sphinx#4420]
Subject: Sphinx docs conflict on use of `rst_prolog` and `rst_epilog` for substitutions

### Problem
- The [ReST Primer states](https://github.com/sphinx-doc/sphinx/blame/master/doc/rest.rst#L447) that `rst_prolog` should be used for substitutions that are to be included in all documents, whereas the [build config doc states](https://github.com/sphinx-doc/sphinx/blame/master/doc/config.rst#L174) that `rst_epilog` should be used.

#### Procedure to reproduce the problem
Open the [ReST primer](http://www.sphinx-doc.org/en/stable/rest.html#substitutions) and [build config doc](http://www.sphinx-doc.org/en/stable/config.html#confval-rst_epilog) in a browser and compare their instructions.

#### Error logs / results
N/A

#### Expected results
Documentation is consistent on where substitutions for all documents should be placed.

### Reproducible project / your project
N/A

### Environment info
N/A

**Comment by tk0miya** [comment]
8 yrs ago vs 9 yrs ago... They are too old.
Both are okay for substitution. so they should be rewritten.
