### ISSUE TITLE
Make sphinx.ext a namespace package

### ISSUE THREAD

**Issue by eric-wieser** [sphinx-doc/sphinx#4421]
Making `sphinx.ext` a [namespace package](https://packaging.python.org/guides/packaging-namespace-packages/) would make it possible for third parties to distribute extensions under the namespace `sphinx.ext.<theirpackage>`

**Comment by tk0miya** [comment]
-1; We already use `sphinxcontrib` namespace

**Comment by shimizukawa** [comment]
IMO, namespace package introduces technical complexity. In order to avoid this problem, I heard that Django and Pyramid avoid using namespace package.

**Comment by eric-wieser** [comment]
`sphinxcontrib` was what I was looking for, thanks
