### ISSUE TITLE
Make script_files deprecated to?

### ISSUE THREAD

**Issue by Blendify** [sphinx-doc/sphinx#4439]
Subject: script_files should be made depricated

### Problem
Since `css_files` was made deprecated in 83d3fd2c365f314877086c72eef79df2c43da69d Should `script_files` also be made deprecated?

#### Procedure to reproduce the problem
N/a

#### Error logs / results
N/a

#### Expected results
`script_files` marked as deprecated.

### Reproducible project / your project
N/a

### Environment info
- OS: N/a
- Python version: N/a
- Sphinx version: 1.6.x

**Comment by tk0miya** [comment]
Yes, I think so. But we still modify it inside HTML theme. so we have to refactor it first.
So I marked this as 1.8 milestone.

**Comment by tk0miya** [comment]
Modified by #5021.
Thanks,
