### ISSUE TITLE
Inconsistent documentation for sphinx-apidoc

### ISSUE THREAD

**Issue by TimoMorris** [sphinx-doc/sphinx#4451]
[invocation.rst.txt](https://github.com/sphinx-doc/sphinx/files/1642740/invocation.rst.txt)
[sphinx-apidoc.rst.txt](https://github.com/sphinx-doc/sphinx/files/1642741/sphinx-apidoc.rst.txt)

Subject: the documentation for the standard sphinx-apidoc call is inconsistent across different locations, on two points that already have potential for confusion

### Problem
The 'signature' for the sphinx-apidoc call is given in three different locations (all of them official Sphinx references): 

- On the [sphinx-apidoc manual page](http://www.sphinx-doc.org/en/stable/man/sphinx-apidoc.html):
  `sphinx-apidoc [options] -o <outputdir> <sourcedir> [pathnames …]`
- On the [sphinx invocation page](http://www.sphinx-doc.org/en/stable/invocation.html#invocation-of-sphinx-apidoc):
  `sphinx-apidoc [options] -o outputdir packagedir [pathnames]`
- In the 'internal' help, i.e. when you call `sphinx-apidoc --help`:
  `sphinx-apidoc [options] -o <output_path> <module_path> [exclude_pattern, ...]`

The inconsistency is confusing in itself, but especially the `<sourcedir>` in the main manual (1st link above), as 'source' here refers to the fact that the Python package is the 'source' (i.e. input) for sphinx-apidoc, whereas the other three uses of the word 'source' on that page are referring to the Sphinx source files, which is actually the **output** from sphinx-apidoc.

The root problem is that documenting with sphinx-apidoc is a two-stage process (running sphinx-apidoc, and then running the actual build), with both steps requiring input that could legitimately be called 'source'. This means that the term is overloaded (

that one processes output is the other's input only compounds this problem!). Using the term `<module_path>` is *much* more helpful.

Using `[exclude_pattern, ...]` is similarly helpfully descriptive with the explicit mention of 'exclude', avoiding confusion as [seen here](https://stackoverflow.com/questions/13116155/sphinx-apidoc-usage-multiple-source-python-directories/13442889#13442889).

(I might add that as someone new to Sphinx and relatively new to Python, I found it very tricky to get sphinx-apidoc to work, in part because of this unhelpful/inconsistent naming.)

### Fix
I don't know how the documentation files are edited, or indeed, if this is the right place to submit documentation corrections. But I've attached updated versions of the source files for the sphinx-apidoc manual page and the sphinx invocation page (i.e. the first two references in the list). I've made minor adjustments so they both more closely match the third reference ('internal' help), which seems to be most up-to-date and most helpful.

### Attachments
- invocation.rst.txt (edited source file for http://www.sphinx-doc.org/en/stable/invocation.html)
- sphinx-apidoc.rst.txt (edited source file for http://www.sphinx-doc.org/en/stable/man/sphinx-apidoc.html)

#### Finally...
If anyone can tell me the correct/standard terms for what I've called 'signature' and 'internal help' that would be also useful!

**Comment by stephenfin** [comment]
I'll take a look at this tomorrow, @tk0miya, if you don't get to it first

**Comment by tk0miya** [comment]
@stephenfin thanks, could you fix this if you have time :-)

**Comment by stephenfin** [comment]
@MarmiteFox There seems to be some issue with the attachment and I'm receiving the following error:

    $ curl -L https://github.com/sphinx-doc/sphinx/files/1642741/sphinx-apidoc.rst.txt
    curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number

It could be my connection at fault. In any case, could you upload these to gist.github.com and share the link here?

**Comment by tk0miya** [comment]
just FYI: I can download them from chrome on mac.

**Comment by TimoMorris** [comment]
@stephenfin here they are:
invocation: https://gist.github.com/MarmiteFox/1efd6828795445e0513deeec9453beb8
sphinx-apidoc: https://gist.github.com/MarmiteFox/b0e638a32a729a89a5afcf76a91a9083

**Comment by stephenfin** [comment]
I've resolved this in #4464. I already removed `invocation.rst` in 9b7525d47df40c1e5d63ec4ee2fdbc51d35bf1ea (which will be part of 1.7) so only the man page needed updates.

**Comment by tk0miya** [comment]
Fixed by #4464. Thank you for reporting!
