### ISSUE TITLE
Proposal: Integrate source_suffix and source_parsers

### ISSUE THREAD

**Issue by tk0miya** [sphinx-doc/sphinx#4474]
### Problem
- Now Sphinx has two confvals to control filetypes of documents; `source_suffix` and `source_parsers`
- `source_suffix` are used to discovery target files on srcdir
- Since 1.3, `source_parsers` was introduced to add new parsers (ex. recommonmark) for specific filetypes (ex. `*.md`)
    - The users who want to use external parsers have to specify both `source_suffix` and `source_parsers`::

      ```
      source_suffix = ['.rst', '.md']
      source_parsers = {'.md': 'module.name.to.external.parsers'}
      ```

    - These confvals are partially duplicated.
    - The users have to know the module of parsers to configure `source_parsers`.

- Since 1.4, `app.add_source_parser()` was added for source parser extensions.
     - The extension can set up source parser automatically
     - What users should do is only add the name to extensions list
     - But users still need to set up `source_parsers` if they wants to use parsers to specific file-extensions (ex. use recommonmark for `*.txt`)

#### Expected results
Merging `source_suffix` and `source_parsers` using filetypes keyword.
```
# maps from extension to filetypes
source_suffix = {
    '.rst': 'restructuredtext',
    '.md': 'markdown',
    '.txt': 'markdown',
}
```

In addition, we give a new specification to source_parsers. The parser classes have to define `Parser.supported` attribute. The `supported` attribute is a basis of docutils components. All of docutils components should define what type of formats the component supports.
For example, reST parser has this definition:
```
class Parser(docutils.parsers.Parser):

    """The reStructuredText parser."""

    supported = ('restructuredtext', 'rst', 'rest', 'restx', 'rtxt', 'rstx')
    """Aliases this parser supports."""
```

I think filetypes is much simpler than name of parser module for users.

### Compatibility

To keep compatibility, we have to support old `source_suffix` and `source_parsers`.

* If `source_parsers` is defined, Sphinx follows the settings to choose source parsers
* If no `source_parsers` and `source_suffix` is a list of string, all entries of `source_suffix` are parsed as `reST`
* The extensions can add an entry to `source_suffix` through API, but user can override it by `conf.py`
* The parser class not having `supported` definition is allowed for a while

**Comment by shimizukawa** [comment]
Looks great!

**Comment by stephenfin** [comment]
Looks good! Only one request: use `restructuredtext` for the `txt` extension. As far as I know, docutils still suggests using this extension for rST files.

**Comment by tk0miya** [comment]
-0; either is okay, but I personally prefer to `.rst` for reST files. It is better to use more appropriate file extension to me.

Anyway, it is not related with this directly. So I'd like to separate your proposal and this change.

**Comment by stephenfin** [comment]
> -0; either is okay, but I personally prefer to .rst for reST files. It is better to use more appropriate file extension to me.

What I'm referring to is this:

```python
# maps from extension to filetypes
source_suffix = {
    '.rst': 'restructuredtext',
    '.md': 'markdown',
    '.txt': 'markdown',
}
```

If we're defining a default for this attribute, please use `'.txt': 'restructuredtext'` or don't assign anything for `.txt`.

Also, how about dropping the leading `.` from the extensions (e.g. `txt` instead of `.txt`)? I can comment on the pull request once it's there.

**Comment by tk0miya** [comment]
At present, only `.rst` is a target of Sphinx. So I would not like to assign `.txt`.

>Also, how about dropping the leading . from the extensions (e.g. txt instead of .txt)?

+0; no opinion, but I'll welcome PR for that.

Note: I think users will not modify `source_suffix` with this change. so I don't think the removal of dot is not important.

**Comment by stephenfin** [comment]
> At present, only `.rst` is a target of Sphinx. So I would not like to assign `.txt`.

Cool. Just please don't assign `.txt` to Markdown. That's my point 😄

**Comment by tk0miya** [comment]
Yes, of course. We don't provide markdown parser. So it will cause crashes if we do that.

**Comment by tk0miya** [comment]
Now #4483 is merged. Thank you for comment!
