### ISSUE TITLE
sphinx picks up block quotes even with `.. code-block:: none`

### ISSUE THREAD

**Issue by TomasTomecek** [sphinx-doc/sphinx#4479]
### Problem
I am using `autoclass` extensions and I have some terminal output sample in a class' method, which looks like this:

```python
    def method(self):
        """
        <not important text>


        This will output

        .. code-block:: none

            b'1\n'
            b'2\n'
            b'3\n'
            b'4\n'
            b'5\n'

        <rest of the docstring>
        """
```

Unfortunately, sphinx picks this as block quotes and produces following warnings:
```
file.18: WARNING: Block quote ends without a blank line; unexpected unindent.
file.20: WARNING: Definition list ends without a blank line; unexpected unindent.
file.22: WARNING: Definition list ends without a blank line; unexpected unindent.
file.24: WARNING: Definition list ends without a blank line; unexpected unindent.
file.26: WARNING: Definition list ends without a blank line; unexpected unindent.
```

Is there a way to turn off block quotes? I tried quoting them but that didn't really help. After a bit of reading, it seems the issue is smart quotes of docutils.

[Here's the real example](https://github.com/fedora-modularity/conu/pull/121/files#diff-7538688383356907def19785aa262da5R315)

### Environment info
- OS: Linux
- Python version: 2.7
- Sphinx version: 1.6.6

**Comment by jfbu** [comment]
Does escaping the backslashes help you?

```python
    def method(self):
        """
        Get logs from this container. Every item of the iterator contains one log line
        terminated with a newline. The logs are encoded (they are bytes, not str).

        Let's look at an example::

            image = conu.DockerImage("fedora", tag="27")
            command = conu.DockerRunBuilder(["bash", "-c", "for x in `seq 1 5`; do echo $x; sleep 1; done"])
            container = image.run_via_binary(command)
            for line in container.logs(follow=True):
                print(line)

        This will output:

        .. code-block:: none

            b'1\\n'
            b'2\\n'
            b'3\\n'
            b'4\\n'
            b'5\\n'

        :param follow: bool, provide new logs as they come
        :return: iterator (of bytes)
        """
        return None
```

![capture d ecran 2018-01-22 a 18 59 46](https://user-images.githubusercontent.com/2589111/35236141-88023736-ffa6-11e7-8149-a17d0b6ba873.png)

**Comment by stephenfin** [comment]
As @jfbu notes, you can escape this to resolve the issue. Alternatively, make the block a raw string with the `r` prefix.

    def method(self):
        r"""
        Get logs from...
        """

**Comment by TomasTomecek** [comment]
And the whole time I thought the issue is quotes, not backslashes.

You guys are geniuses, thank you so much!

(not sure if it makes sense to update the documentation so that others won't be so confused as I was)

**Comment by jfbu** [comment]
For info, these warnings originate in [Docutils](http://docutils.sourceforge.net/docs/index.html), not Sphinx. I am not sure why  Docutils 's warning refers to a "Block quote" rather than a "Literal block", perhap I should dig into internals to learn something. And, here the user quiproquo was between "quote" as in "block quote" (for indenting a quoted text) and "quote" as in "left and right quotes, the typographical characters".)

**Comment by TomasTomecek** [comment]
Should we file an issue on docutils then?

**Comment by jfbu** [comment]
I have opened a [Docutils issue](https://sourceforge.net/p/docutils/bugs/341/).

For what a Block quote is see [here](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#block-quotes)

**Comment by TomasTomecek** [comment]
thank you!
