### ISSUE TITLE
codecov.io for Sphinx does not work

### ISSUE THREAD

**Issue by tk0miya** [sphinx-doc/sphinx#4503]
### Problem
- codecov.io for Sphinx does not work: https://codecov.io/gh/sphinx-doc/sphinx
- It was added by #4337 

#### Error logs / results
https://codecov.io/gh/sphinx-doc/sphinx/commit/fd2425238e5407b5caf9b3f8d9e7840de7dc6583
```
Woops!
There was an error processing coverage reports.
```

#### Expected results
Works fine or disable it.

**Comment by tk0miya** [comment]
@stephenfin could you check this please? What should I do?

**Comment by stephenfin** [comment]
I'll have a look at this this week. I suspect it's something to do with `pytest-cov` and how we're calling it, personally

**Comment by tk0miya** [comment]
Fixed by #4542.
