### ISSUE TITLE
regression in 1.7.0b2: sphinx.ext.autodoc.Options moved

### ISSUE THREAD

**Issue by njsmith** [sphinx-doc/sphinx#4538]
In previous releases, `from sphinx.ext.autodoc import Options` worked. This was treated as a public API by both sphinx's internal extensions (e.g. `sphinx.ext.autosummary` did this), and also external extensions like sphinxcontrib-asyncio and sphinxcontrib-trio (https://github.com/python-trio/sphinxcontrib-trio/issues/7). In 1.7.0b2, the `Options` class has moved to `sphinx.ext.autodoc.directive`, causing these extensions to crash on import.

To avoid breaking downstream packages, it would be helpful if the final 1.7.0 release could provide `Options` from `sphinx.ext.autodoc`, e.g. by adding `from .directive import Options` to `sphinx/ext/autodoc/__init__.py`.

**Comment by tk0miya** [comment]
Okay, I'll do it later.
Thanks,

**Comment by tk0miya** [comment]
Fixed by #4547 
Thank you for reporting!
