### ISSUE TITLE
Tables should be centered by default.

### ISSUE THREAD

**Issue by eflanigan00** [sphinx-doc/sphinx#4550]
In general having all tables pushed to the left is an undesirable behaviour. 
Tables should be centred by default and the user should be able to align them the the left or right if desired.

See #3942

**Comment by tk0miya** [comment]
Personally, I love it. But it seems `rst2html` does not center the table by default. So we have to introduce this carefully.

**Comment by eflanigan00** [comment]
@tk0miya do you know if this proposed update would center Bokeh plots also?

**Comment by tk0miya** [comment]
I don't know. I've never used it.

**Comment by bearsh** [comment]
I'm not really happy with this change as most of my existing documentation looks quite ugly now :unamused: ! why not have a config option where to align by default?

**Comment by tk0miya** [comment]
Could you show me the example of your case? I can't imagine the change of alignment causes documents ugly.

IMO, the alignment would be changed via theme. So -1 for adding alignment. But +1 for changing it via CSS.

**Comment by bearsh** [comment]
When using smaller tables, centering isn't always best:
![image](https://user-images.githubusercontent.com/1089356/56115255-4a08c300-5f63-11e9-9c56-728111272703.png)
vs:
![image](https://user-images.githubusercontent.com/1089356/56115176-175eca80-5f63-11e9-8224-cbf9d79dd6b5.png)

How can that be done via CSS? Sure I can align the `align-center` class to the left but that would align all elements with `align-center` to the left, even the one I want to have centered. So in the end I have to add the table directive to all tables across the whole documentation...

**Comment by ghost** [comment]
> IMO, the alignment would be changed via theme. So -1 for adding alignment. But +1 for changing it via CSS.

The problem seems to be that `:align: left` does not exhibit the same behavior as before the change. For example:

![Screenshot_2019-05-02_22-34-51](https://user-images.githubusercontent.com/47402505/57117542-cb65a100-6d2a-11e9-9d58-8a92273026db.png)

The explicit float causes problems.

**Comment by tk0miya** [comment]
Thank you for comment. I understand your case. Okay, let's make it customizable using CSS. I just make a PR #6341 to do that.

About floating, it might be a problem of your theme (rtd_theme?). The default theme does not make a table as a float. It simply aligns the table left.

**Comment by ghost** [comment]
Thanks for the PR. I like the idea of having the default state being logically separated from the other alignments. You are correct that sphinx_rtd_theme does use `float`, I didn't realize this. I did try to fix it using clear-fix but wasn't successful, so your PR is much better.

**Comment by brechtm** [comment]
I know I'm quite late to the party, but I'm wondering why the _align_ attribute is set to an explicit value of `'default'`. `'default'` is not supported by docutils, and isn't documented in the Sphinx docs, so it took me a long time to find out where this value was coming from.

Simply not setting a value for _align_ can trivially be used for the same purpose. The builder/stylesheet can decide alignment when no value for _align_ is supplied. So why introduce something that is not compatible with docutils when it's not needed?

**Comment by tk0miya** [comment]
Indeed, it would be better to handle it in the later step. Okay, I'll refactor it to do it.

**Comment by brechtm** [comment]
> Indeed, it would be better to handle it in the later step. Okay, I'll refactor it to do it.

Glad you agree, and thanks for the instant fix!
