### ISSUE TITLE
Question: Can a page have two code listings side-by-side?

### ISSUE THREAD

**Issue by arekbulski** [sphinx-doc/sphinx#4553]
I have a page that has pairs of code listings (kind of like input/output pairs). **Would it be possible to show these two code listings in 2 columns, side by side?** I realise that long lines would pose a problem, soft wrap versus cutoff, but thats a secondary issue.
https://construct.readthedocs.io/en/latest/compilation.html#motivation

**Comment by tk0miya** [comment]
Sphinx does not support that. But there might be any third party extension supports that.
Thanks,

Note: this is an issue list for Sphinx, not forum.
Please post questions to sphinx-users group; https://groups.google.com/forum/#!forum/sphinx-users

**Comment by arekbulski** [comment]
In case someone gets intersted in this topic, I found out that Sphinx can render columns as tables:
http://openalea.gforge.inria.fr/doc/openalea/doc/_build/html/source/sphinx/rest_syntax.html#tables
