### ISSUE TITLE
How to get URI from a ref name.

### ISSUE THREAD

**Issue by rowanG077** [sphinx-doc/sphinx#4555]
Subject: In an extension I want to make use of existing references and allow a user to cross reference. The plugin in question outputs svg so directly keeping the ref in the result won't work. So what I want to do is translate an rst fragment to the output it would represent in the output. For instance if I would pass
``  `google <www.google.com>`_`` It would the return the correct format for the output specified. The same should work for using roles or domain references.

### Problem
I can't find how to do something like this. Even reading parts of the builder source code I can't see how I can do this.

**Comment by tk0miya** [comment]
It is resolved inside docutils. So I can't help you...

**Comment by tk0miya** [comment]
anyway, this is an issues for Sphinx, not forum.
Please move to sphinx-dev group; https://groups.google.com/forum/#!forum/sphinx-dev.

Thanks,
