### ISSUE TITLE
How to customly render the html of the TocTree?

### ISSUE THREAD

**Issue by Dubrzr** [sphinx-doc/sphinx#4559]
Subject: I want to create a custom rendering of the TocTree with the StandaloneHTMLBuilder

### Problem
The current {{toc}} or {{toctree()}} directives generates html but I want it to respect the following format (with maxdepth=2):

```
<li class="menu-toggle-open">
  <a class="deep0" href="#">
    <div class="al deep0-number">1</div>
    <div class="ar deep0-title">Chapter</div>
  </a>
  <ul class="deep1">
    <li><a href="#">link1</a></li>
    <li><a href="#">link2</a></li>
    <li><a href="#">link3</a></li>
  </ul>
</li>
```

What would be the best way to change the TocTree rendering?

### Reproducible project / your project
I am creating my own Sphinx template, a preview is available [here](https://ds.futureistech.com/) and the corresponding template is available [here](https://github.com/Dubrzr/Jdu-Sphinx-Template/blob/master/source/jdu/layout.html)

### Environment info
- OS: All
- Python version: 3
- Sphinx version: 1.6.7

**Comment by Dubrzr** [comment]
One way I thought about is to get the TocTree value inside the conf.py file and add a variable in html_context containing my own templated html: 

```
...
html_context = {
    'site_name': 'ML FutureIsTech'
}
...
from sphinx.directives import TocTree
from docutils.parsers.rst import directives

class myTocTree(TocTree):
    option_spec = dict(TocTree.option_spec, reversed=directives.flag)

    def run(self):
        rst = super(myTocTree, self).run()
        here
        if 'reversed' in self.options:
            print(rst)
            rst[0][0]['entries'].reverse()
        html_context 
        return rst

def setup(app):
    app.add_directive('toctree', myTocTree)
```

**Comment by tk0miya** [comment]
Unfortunately, its structure is hard coded in HTML builder.
So it is hard to modify it. The only way is replacing the builder by custom one.

**Comment by Dubrzr** [comment]
Thank you for your answer :)

Can you tell me where exactly this HTML is hardcorded in the builder so that I can create my own builder? I have hard times finding it in the following file: https://github.com/sphinx-doc/sphinx/blob/master/sphinx/builders/html.py

**Comment by tk0miya** [comment]
Please refer this. ToC is built as doctree once at here. After that, it is converted to HTML at HTML builder (`render_partial()`).
https://github.com/sphinx-doc/sphinx/blob/master/sphinx/environment/adapters/toctree.py#L49

**Comment by Dubrzr** [comment]
Thank you, I'll try to work something out!

**Comment by Dubrzr** [comment]
I fixed it like this: https://github.com/FutureIsTech/Data-Science/blob/master/custombuilder/custombuilder.py#L114

Hope this will be easier in future releases!
Thanks again
