### ISSUE TITLE
Incorrect end of line punctuation detection with "autosummary".

### ISSUE THREAD

**Issue by thomasmansencal** [sphinx-doc/sphinx#4563]
Subject: `autosummary` incorrectly detects end of line punctuation.

### Problem
When using `autosummary` with a docstring featuring *et al.*, the sentence is cut after the dot.
`using *Kang et al. (2002)* method.` is trimmed as follows: `using *Kang et al.`

#### Procedure to reproduce the problem
Such a docstring is not only problematic but will also raise a collateral warning:

``` python
def xy_to_CCT_Hernandez1999(xy):
    """
    Returns the correlated colour temperature from given *CIE XYZ* tristimulus
    values *xy* chromaticity coordinates using *Hernandez-Andres et al. (1999)*
    method.
    """

    pass
```

#### Error logs / results
```
Kali:autosummary kelsolaar$ rm -rf _build generated && make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.6.6
making output directory...
loading pickled environment... not yet created
[autosummary] generating autosummary for: doe.rst, index.rst
[autosummary] generating autosummary for: /Users/kelsolaar/Downloads/autosummary/generated/doe.rst, /Users/kelsolaar/Downloads/autosummary/generated/john.bar.rst, /Users/kelsolaar/Downloads/autosummary/generated/john.foo.rst, /Users/kelsolaar/Downloads/autosummary/generated/john.the_dict.rst, /Users/kelsolaar/Downloads/autosummary/generated/krystek.xy_to_CCT_Hernandez1999.rst
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 2 source files that are out of date
updating environment: 7 added, 0 changed, 0 removed
reading sources... [100%] index
/Users/kelsolaar/Downloads/autosummary/index.rst:1: WARNING: Inline emphasis start-string without end-string.
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index
generating indices... genindex py-modindex
writing additional pages... search
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 1 warning.

Build finished. The HTML pages are in _build/html.
```

![image](https://user-images.githubusercontent.com/99779/35846493-c67bbeb6-0b7b-11e8-8086-4e3a348f290b.png)

#### Expected results
I would expect correct end of line punctuation detection and no collateral warnings.

### Reproducible project / your project
Reproducible sample project: https://drive.google.com/file/d/1469JtgHLunCYud8DHWvgBofFYQ1qwpG6/view?usp=sharing

### Environment info
- OS: macOs
- Python version: 2.7
- Sphinx version: 1.6.6

**Comment by tk0miya** [comment]
Fixed by #4637.
Thank you for reporting!

**Comment by lsaffre** [comment]
It seems that this fix caused a regression: now when I have a docstring "blabla, i.e. blablabla", autosummary trims it to "blabla, i." I'll create issue #4689 for this.

**Comment by thomasmansencal** [comment]
@tk0miya : Is it possible to reopen this one, I just installed v3.3.1 and the same error occurs again unfortunately!

```
(colour-49B8_mty-py3.8) Kali:autosummary kelsolaar$ rm -rf _build generated && make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v3.3.1
making output directory... done
[autosummary] generating autosummary for: index.rst
[autosummary] generating autosummary for: /Users/kelsolaar/Downloads/autosummary/generated/hernandez1999.xy_to_CCT_Hernandez1999.rst, /Users/kelsolaar/Downloads/autosummary/generated/john.bar.rst, /Users/kelsolaar/Downloads/autosummary/generated/john.foo.rst, /Users/kelsolaar/Downloads/autosummary/generated/john.the_dict.rst, /Users/kelsolaar/Downloads/autosummary/generated/machado2009.msds_cmfs_anomalous_trichromacy_Machado2009.rst
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 1 source files that are out of date
updating environment: [new config] 6 added, 0 changed, 0 removed
reading sources... [100%] index                                                                                                                                               
/Users/kelsolaar/Downloads/autosummary/index.rst:14:<autosummary>:1: WARNING: Inline emphasis start-string without end-string.
/Users/kelsolaar/Downloads/autosummary/index.rst:14:<autosummary>:1: WARNING: Inline emphasis start-string without end-string.
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index                                                                                                                                                
generating indices... genindex done
writing additional pages... search done
copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 2 warnings.

The HTML pages are in _build/html.

Build finished. The HTML pages are in _build/html.
(colour-49B8_mty-py3.8) Kali:autosummary kelsolaar$ 
```

![image](https://user-images.githubusercontent.com/99779/100317129-b04f3600-3020-11eb-825d-0839dbdebcff.png)

Updated project attached: [autosummary.zip](https://github.com/sphinx-doc/sphinx/files/5600961/autosummary.zip)

**Comment by thomasmansencal** [comment]
So I tested a few versions:

**1.8, 2.0.0, 2.4.4, 3.0.0, 3.1.2**

Not breaking but double punctuation mark:

![image](https://user-images.githubusercontent.com/99779/100318526-0f15af00-3023-11eb-9ca5-e0888f3b5457.png)

![image](https://user-images.githubusercontent.com/99779/100318334-bba36100-3022-11eb-9cc4-0e7e4e7c0f52.png)

![image](https://user-images.githubusercontent.com/99779/100318185-80a12d80-3022-11eb-8700-c5aeb6789c77.png)

![image](https://user-images.githubusercontent.com/99779/100318071-4df73500-3022-11eb-9d2f-baea1bccca06.png)

![image](https://user-images.githubusercontent.com/99779/100317867-ec36cb00-3021-11eb-8064-8c08a580df24.png)

**3.2.0**

Breaking, i.e. regression:

![image](https://user-images.githubusercontent.com/99779/100317987-24d6a480-3022-11eb-8847-5a61db398d5d.png)

**Comment by tk0miya** [comment]
Thank you for reporting. It was a side effect of https://github.com/sphinx-doc/sphinx/pull/7877. I'll fix it from now on.

**Comment by tk0miya** [comment]
I filed a new issue for this https://github.com/sphinx-doc/sphinx/issues/8501

**Comment by thomasmansencal** [comment]
You are welcome and thanks!
