### ISSUE TITLE
rst_prolog/rst_epilog not working on master

### ISSUE THREAD

**Issue by jakobandersen** [sphinx-doc/sphinx#4564]
Subject: ``rst_prolog`` and ``rst_epilog`` are not added to files

### Problem
A bit of git bisect shows that 2b6c8b33be0e66160c6f5d14fd78c7a47e3389b0 is the problematic commit. I guess that somehow it interacts badly with #2445.

#### Procedure to reproduce the problem
Create a new project with ``sphinx-quickstart`` and to ``conf.py`` assign some code to ``rst_prolog``/``rst_epilog``, say
```python
rst_prolog = ".. thisShouldGiveAWarning::\n\n"
rst_epilog = rst_prolog
```

#### Error logs / results
With 2b6c8b33be0e66160c6f5d14fd78c7a47e3389b0 the code won't have effect. With any version without the commit (including the 1.7-release branch) it works as expected.

**Comment by tk0miya** [comment]
Oh, this was already fixed by #4594.
I'm closing this now.
Thank you for reporting
