### ISSUE TITLE
vertical space before equation in latex

### ISSUE THREAD

**Issue by aszekMosek** [sphinx-doc/sphinx#4574]
It seems to me that equations without a label are written to the latex source as

```
handles problems of the form:
\begin{equation*}
```
and equations with a label as:

```
form of a linear minimization problem is:

\phantomsection\label{\detokenize{linear:equation-eq-linear-standard1}}\begin{equation}\label{equation:linear:eq-linear-standard1}
```

The extra empty line before ``phantomsection`` starts a paragraph and causes an unnecessarily large vertical space before ``equation``, unlike for ``equation*`` where it is OK. 

Removing the empty line fixes the problem.

Also, I'm not sure ``phantomsection`` is necessary for equations. ``hyperref`` seems to produce links to equations without it just as well.

Sphinx 1.6.7

**Comment by jfbu** [comment]
Fixed at e1e46cdf8. Thanks for report!
