### ISSUE TITLE
slow running sphinx in large project

### ISSUE THREAD

**Issue by abchenson** [sphinx-doc/sphinx#4576]
Subject: slow running sphinx in large project
### Problem

We have a sphinx project with about 300 rst files ( about 200 generated stubs, e.g. for each member of each class etc. comparable to pandas docs, 60k lines in the non generated pages).  The build takes over 12mins and each file takes over a second to write, using up most of that time.  This single file writing time is the concern as it seems excessive, and to have been getting worse, so we're worrying about scaling, which might affect our choice of tools.  The amount of code being documented is not that huge present, and this part of the docs may double in size, at which point we'll really be in trouble.  

I know about the -j option already but the scaling is still a worry here if there project e.g. doubled in size.  I've also had a look at https://github.com/sphinx-doc/sphinx/issues/4230 but this seems unrelated as 1.5 was not that much better for us.  Here I have used sphinx 1.6.6.  I tried 1.7.0b2 but this causes the code documentation to fail (see https://github.com/sphinx-doc/sphinx/issues/4573 ) so it's difficult to compare but doesn't seem to help a lot.

The question is really where the bottleneck is here and if anything could be done to significantly increase the speed (either at our end our yours). Any help would be much appreciated!

#### Procedure to reproduce the problem

This is very hard to reproduce with a simple mocked-up example.  Below there is a version of our project with code (and notebooks) replaced with mockups and the rst "scrambled" (alphanumerics randomised apart from navigation directives and roles). The scrambling results in a lot of warnings, but this does not seem to affect the speed issue so I'm hoping it has not effected the cause of the problem.

Unpack into one directory, have the speed_test_requirements/requirements.txt pip installed, and then use the following command run in the docs directory to see the slow running
```
make html
```

[scrambled_slow_example.tar.gz](https://github.com/sphinx-doc/sphinx/files/1703979/scrambled_slow_example.tar.gz)

#### Error logs / results

This mock/scrambled version takes over 10 minutes, a bit quicker than the real version.

### Environment info
- OS: Linux
- Python version: 3.5
- Sphinx version: 1.6.6

**Comment by marcinpraczko** [comment]
Hi, Is there any work on this? I have the same issue - which to be honest slow down my work.
Simple RST update and then times required to rebuild HTML pages:

```
make: Entering directory '/code/docs'
Running Sphinx v1.8.5
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 37 source files that are out of date
updating environment: [] 0 added, 46 changed, 0 removed      # !!! <---- This is where time is lost (1-2 mins) for each build
reading sources... [100%] modules/testing.write_xml
```

And my docs are having around 300 RST files:
```bash
find docs/source/ -name '*.rst' | wc -l
     298
```

**Comment by webknjaz** [comment]
> This is where time is lost (1-2 mins) for each build

It's not that slow compared to a docs build process that takes hours to complete :)

**Comment by marcinpraczko** [comment]
I agree with this. Issue increases with freqently of builds. With current CI/CD movement and more frequent builds - having 1-2 mins delays for very simple page adjustment becomes big issue.
For me issue is that (happy to learn about solutions):
1. I don't see nice preview for RST (Sphinx) in editors - such us markdown can do (So need to rebuild page to see output)
2. Sphinx - should detect only files which changed ... however even simple change is causing slowness (not good as well).
3. So there is no way to preview context without dealy (Becuase of slowness) - which automatically is causing willinges for searching alternatives :( 

So I agree builds can take hours - hover job which should take 15 mins (some changes in few files / review / etc) - increases 2 or 3 times (30/45 mins) - I think that this is really not optimal.

**Comment by marcinpraczko** [comment]
Can we at least confirm whether that was or is some plans to work on this issue and try resolve? Speed up build process? IMHO this is really important for more adoption for sphinx.

**Comment by webknjaz** [comment]
> 1. I don't see nice preview for RST

It's not preview but make sure to run basic checks via https://pypi.org/project/rstcheck/. This way you can fail early.



> 2. Sphinx - should detect only files which changed

Do you use caches? Like an optional TOC tree cache. I'm almost sure it's not cached if now specified explicitly: https://github.com/sanitizers/octomachinery/blob/74698d1/tox.ini#L40.

**Comment by marcinpraczko** [comment]
@webknjaz - Thank you for feedback and suggestions. Installed rstcheck and had minor errors.
Will check this TOC tree cache as well. 
However just discovered that had some temporary venv folder in source (for testing some code and was not deleted) - so this means that build step: 'updating environment:' is checking for EVERY file within source tree - not only RST, etc. 
When removed this venv folder - above step become much faster.
Still writes files are not as fast as expected - but are now much faster.

**Comment by hofmandl1** [comment]
I just wanted to add another data point to this. Sorry if everyone's already well aware of this.

[flame.pdf](https://github.com/sphinx-doc/sphinx/files/7244530/flame.pdf)

Attached is a flame-graph created with `py-spy` when doing a clean, non-incremental, non-parallel build on our documentation with Sphinx 4.2.0. (incremental is not perfect, but still really!! helpful, parallel helps a bit but not too much).

Documentation consists of 6090 pages and it takes about 16minutes on my i9 workstation to complete (most other devs here have slower machines).

Not sure, what to make of it, other than lots of time (~50%) spent in `_get_local_toctree`. Probably has to do with the large number of pages we have ?
