### ISSUE TITLE
variable types missing for autosummary

### ISSUE THREAD

**Issue by abchenson** [sphinx-doc/sphinx#4582]
Subject: variable types missing for autosummary in current version
### Problem
- in Sphinx 1.7.0b autosummary genarates nice summaries for the attributes in a class, where you can include a type and description and they both appear. E.g. if you have
```
class_var = 0
    """int: description of class_var under its definition"""
```
in your class the summary in the output shows int italicised and with a hyphen.
In Sphinx-1.8.0.dev20180208 (which fixes another issue #4536 with autosummary) the types go missing.

#### Procedure to reproduce the problem
```
make html
```

#### Error logs / results
missing types in the attribute summary in the html file for `_build/html/generated/test_mod.TestCls.html#test_mod.TestCls`
![attributes_1 8](https://user-images.githubusercontent.com/32451279/35985035-97a5e7f6-0ced-11e8-9b6c-ba76d98fb545.png)

#### Expected results
in 1.7.0b2 the example gives the types:
![attributes_1 7 0b2](https://user-images.githubusercontent.com/32451279/35985044-9c36f59e-0ced-11e8-97f9-fe71f7648b57.png)

### Reproducible project / your project
this is an simple example using sphinx-quickstart which can be run with make html, using either version of sphinx:
[min_docstring_err_example.tar.gz](https://github.com/sphinx-doc/sphinx/files/1707874/min_docstring_err_example.tar.gz)

### Environment info
- OS: linux
- Python version: 3.5
- Sphinx version: Sphinx-1.8.0.dev20180208
- <Extra tools e.g.: Browser, tex or something else>

**Comment by tk0miya** [comment]
The description is generated by combination of autosummary and napoleon extensions. But I think that is not intended.
Anyway, the behavior of napoleon was changed at #4047.

Since 1.7, `"int: description of class_var ..."` is converted to following document:
```
*int* -- description of class_var ...
```

But, from next release, it will be rendered as following:
```
description of class_var ...

:type: int
```

As a result, the summary has been changed since 1.8 release.

**Comment by tk0miya** [comment]
I think there are nothing to do for both autosummary and napoleon. It seems the change of #4047 would be worthy for napoleon users. So I'm closing this now.
Thank you for reporting.
