### ISSUE TITLE
TypeError: issubclass() arg 1 must be a class

### ISSUE THREAD

**Issue by jschueller** [sphinx-doc/sphinx#4596]
Some commits to master today (2018/2/11) broke my builds does the following ring a bell?
```
Exception occurred:
  File "/home/ubuntu/.local/lib/python2.7/site-packages/sphinx/application.py", line 740, in add_directive
    if not issubclass(obj, Directive):
TypeError: issubclass() arg 1 must be a class
```
I'll try to bisect tomorrow.

**Comment by jschueller** [comment]
seems related to https://github.com/sphinx-doc/sphinx/pull/4589

**Comment by jschueller** [comment]
Is this issue present in 1.7.0 ?

**Comment by tk0miya** [comment]
Yes, this condition (and deprecation warning) is only in master.
