### ISSUE TITLE
Links to inherited functions don't work

### ISSUE THREAD

**Issue by rahasurana** [sphinx-doc/sphinx#4600]
ASubject: Links to functions inherited from parent class in derived class don't work

### Problem
- I'm currently using sphinx-epytext as migration from epydoc to sphinx until the source code is updated and i'm stuck with the below "simple" issue. 
Consider the simple inheritance below: 

ABC1.py:

```
class A(object):
     """Parent class which defines test"""
     def test(self):
         """Test function from A"""
         pass

class B(A):
      def test2(self):
         pass

```
ABC2.py:

```
class C(object):
    """This is dummy reference for :py:obj:`ABC1.B.test`"""
    pass
```
Now when the documentation for both the files are generated, the directive link in docstring for class C seems to be a dead link and doesn't point to the method `test` from A class.
Although, directive seems to work fine if methods defined in B are specified, say `test2`, but only fails to link to parent class inherited methods.

I tried adding `autodoc_default_flags = ['members', 'inherited-members']`  as suggested in https://groups.google.com/forum/#!topic/sphinx-users/Avob81ALLYo, but that only adds doc from A to B.

sphinx-epytext by default replaces L{<text>}/ C{<text>} to :py:obj:`text`.
I could always go back and add a :ref: tag, but wanted to continue using the :py:obj: for consistency and also the replacement to ref would require a lot of manual effort.

Any suggestions on how this can be fixed?
### Environment info
- OS: Linux
- Python version: 2.7.14
- Sphinx version: 1.6.7

**Comment by tk0miya** [comment]
I confirm the cross reference works fine with following files:

index.rst
```
.. automodule:: ABC1
.. automodule:: ABC2
```
conf.py
```
import os, sys
sys.path.insert(0, os.path.abspath('.'))

master_doc = 'index'
extensions = ['sphinx.ext.autodoc']
autodoc_default_flags = ['members', 'inherited-members']
```

I suppose your trouble is came from a bug of epytext.

**Comment by tk0miya** [comment]
I'm closing this now.
Feel free to reopen if you still have the problem.
Thanks,
