### ISSUE TITLE
Sphinx - Problem with CSS and 'make html' command

### ISSUE THREAD

**Issue by Hallam1995** [sphinx-doc/sphinx#4604]
I have a sphinx project and some .rst files. I am using the read_the_docs theme for sphinx. When i run 'make html', my CSS resets and anything I add to the HTML pages in my text editor do not save when I run 'make html' again. 

Basically, nothing saves when I do 'Make html' after adding new content to the .rst file. All of the custom CSS that I add just doesn't saves and it reverts to what it was when i first downloaded the rtd_theme. 
 
### Environment info
- OS: MacOS High Sierra
- Python version: 2.7.10
- Sphinx version: 1.7.0b1
- <Extra tools e.g.: Google Chrome

**Comment by tk0miya** [comment]
Did you modify the generated HTML directly? Sphinx does not refer them, and it simply overrides it on `make html`. So please do not modify them directly.

You can add custom CSS by following step:

1. Create custom CSS as a independent file under `_static/` directory (ex. `_static/mystyle.css`).
2. Add the following code into your `conf.py` to enable the custom CSS file.

   ```
   def setup(app):
      app.add_stylesheet('mystyle.css')  # give a filename you created.
   ```

**Comment by Hallam1995** [comment]
I'll give it a go thanks. Yeah, I was editing the HTML files directly after i did make html to add some other content but I'll add the code to the conf.py file. Is there a particular place the code snippet is meant to go?

**Comment by Hallam1995** [comment]
Doesn't seem to be working, I've tried creating a new css file and added it to the conf.py file, the css still resets and goes back to the default sphinx_rtd_theme css file.

**Comment by Hallam1995** [comment]
I've added this and its made a difference so I'm on the right track thanks. However, since I can't edit the HTML files directly since 'make html' just overrides it, how do I add a navigation bar to the top of my HTML page? I've got it in the css but that's just for the design of it. Can I add stuff like this in the .rst file?
