### ISSUE TITLE
Creating a html navigation bar within Sphinx

### ISSUE THREAD

**Issue by Hallam1995** [sphinx-doc/sphinx#4618]
Hi, I recently put forward an issue on here about my html pages which was fixed, many thanks. 

However, I've now come across something I'm not sure about. I am wanting to add a horizontal navigation bar to the top of my html pages that are created with Sphinx, however, due to the fact that I can't edit the html files themselves since Sphinx ignores this on 'make html', is there anyway i can do this without raw html code?

I have the css for 'topnav' and 'topnav2' ready to go, it's just I'm not sure if its actually possible to do this without writing the html in myself, which is no good. 

I am using the sphinx_rtd_theme with a custom CSS file if that helps at all?

Thanks!

### Environment info
OS: MacOS High Sierra
Python version: 2.7.10
Sphinx version: 1.7.0b1
Extra tools: Google Chrome

**Comment by tk0miya** [comment]
This is a list of issues for Sphinx, not a forum.
Please move to sphinx-users group
https://groups.google.com/forum/#!forum/sphinx-users

Thanks,
