### ISSUE TITLE
Invalid section numbering

### ISSUE THREAD

**Issue by nowox** [sphinx-doc/sphinx#4628]
Subject: The document title should not always be numbered

### Problem
With a file such as 

```rst
==========
Document Title
==========

.. sectnum:: 

Section
=====

Subsection
------------
```

I am expecting to see 

```
Document Title

1. Section

1.1 Subsection
```

Unfortunately, the document title is also numbered which does not make any sense here. 

```
1. Document Title

1.1 Section

1.1.1 Subsection
```

To show that I am not the only one to think that way, if you look at how GitHub render ReST files here:

https://github.com/nowox/sphinx-fix-sectnum/blob/master/index.rst

You will see that the numbering is the same as what I want

#### Procedure to reproduce the problem
```
git clone https://github.com/nowox/sphinx-fix-sectnum
cd sphinx-fix-sectnum
sed -i "s/'fix-secnum'//" conf.py
make html
```

To see the corrected version:

```
git reset --hard master
make html
```

**Comment by tk0miya** [comment]
In sphinx, `--no-doc-title` option of docutils is set (note: internal name is `doctitle_xform`). The reason of that is a conflict with toctree.

FYI: Without `--no-doc-title`, docutils promotes a top-level section title to document title. As a result, `sectnum` directive does not assign a number to it. But it means Sphinx does not treat it as section.

**Comment by tk0miya** [comment]
I don't know this is a specification or not. But it seems difficult to support it to me.

**Comment by tk0miya** [comment]
I'm closing this because this is intentional change of Sphinx.
Thanks,
