### ISSUE TITLE
Is http://docutils.sourceforge.net dead?

### ISSUE THREAD

**Issue by return42** [sphinx-doc/sphinx#4635]
Does anyone know what happens with http://docutils.sourceforge.net ?
There is just a blank page with one line: `Project web is currently offline pending the final migration of its data to our new datacenter.` Is it only to me?

**Comment by tk0miya** [comment]
I don't know. Please ask sourceforge or docutils project.
This is Sphinx project.

**Comment by return42** [comment]
I did, but the docutils ML there ignores mails?!?. Anyway, we all (and http://www.sphinx-doc.org also) refer this url since the beginning, or try a google search, nothing works anymore. No matter what I asked, I never got a feedback from David Goodger and the virus centrifugally named sourceforge is annoying. With all respect to David, but IMO this project is no longer well maintained ... may be it is time to fork.

**Comment by tk0miya** [comment]
Why are you posting here? This is an issue list of Sphinx, not docutils'.
We are not maintainers of docutils. So we can't answer anything to you, unfortunately.

**Comment by return42** [comment]
Sorry, I thought you are interested in, that your links no longer work.

**Comment by tk0miya** [comment]
The message says they're in migration now. So it will be recovered after a while.
So we don't mind. Please let us know if the migration will continue for a long time.

Thanks,
