### ISSUE TITLE
External link in TOC cannot contain "?"

### ISSUE THREAD

**Issue by Silmathoron** [sphinx-doc/sphinx#4641]
Including external links in the TOC doesn't work if these links contain question marks (e.g. php).

#### Example

```
.. toctree::
   :glob:
   :maxdepth: 1
   :caption: Miscellaneous

   various/various
   GitHub <https://github.com/Silmathoron/>
   Other <https://duckduckgo.com/?q=sphinx+link+%22question+mark%22+toc&t=lm&ia=web>
```

The GitHub links works fine, but not the Other.

#### Error logs / results
```
WARNING: toctree glob pattern u'Other <https://duckduckgo.com/?q=sphinx+link+%22question+mark%22+toc&t=lm&ia=web>' didn't match any documents
```

Is there an already existing way to solve this? If not, is there a way to fix it

### Environment info
- OS: Linux Mint 18.3
- Python version: 2.7.12
- Sphinx version: 1.6.6 and 1.7

**Comment by tk0miya** [comment]
This comes from the combination of `:glob:` option and URL containing `?`.
I fixed this in #4644.

**Comment by Silmathoron** [comment]
Ok, looking forward to 1.7.1 then, thanks!

**Comment by tk0miya** [comment]
Now #4644 is merged.
Thank you for reporting!
