### ISSUE TITLE
Why is add_node() limited to built-in builders?

### ISSUE THREAD

**Issue by brechtm** [sphinx-doc/sphinx#4643]
I was looking into rendering the Open Data Kit with the rinoh builder. The project defines a custom `video` directive that only generates output when using the HTML builder. See the [add_node() call in video.py](https://github.com/opendatakit/docs/blob/bef9a746138d43058c6789d2639af6695d8c65a7/video.py#L144).

I was hoping that if the rinoh builder would set a `default_translator_class`, that adding a `rinoh=(visit, depart)` argument would add these functions to the translator. It doesn't, so support for this custom node needs special handling for a third party builder.

Note that in this case the behavior for all builders is the same except for the HTML builder. So it would be very convenient to be able to provide default visit/depart methods for builders that are not explicitly mentioned in the add_node call. Especially, since these nodes are not necessarily builder-specific (simply resolving into other nodes).

Is there any particular reason that `add_node` is limited to the built-in builders? Why not allow it to modify third-party builders?

Also, the purpose of having `default_translator_class` is not clear to me; is this only to allow overriding them?

**Comment by tk0miya** [comment]
I think it is not limited. It's simply a bug. And, I believe #4605 will fix it.

>Also, the purpose of having default_translator_class is not clear to me; is this only to allow overriding them?

Yes, it is used to the translator class by default.
And extensions can override it using `app.set_translator()` API.

**Comment by tk0miya** [comment]
I think this is resolved by #4605.
Please let me know if it still does not work well.
Thanks,

**Comment by brechtm** [comment]
Thanks @tk0miya. I'll report back here once I've had the time to try it.

**Comment by brechtm** [comment]
This approach doesn't work for rinohtype because it doesn't make use of a translator class like the other builders. However, it's still possible to make rinohtype support custom nodes. You can find a little more information in [this comment](https://github.com/brechtm/rinohtype/issues/118#issuecomment-613582610).
