### ISSUE TITLE
"rubric" should create an unnumbered \paragraph in latex mode

### ISSUE THREAD

**Issue by Jellby** [sphinx-doc/sphinx#4648]
I use `.. rubric` to create a heading with no number and no entry in TOC. It works fine in HTML, but in the latex output I get something like:

```
1.1.3 Normal heading

Lorem ipsum...

1.1.3.0.0.1 "Rubric" heading
```

which makes no sense. I wanted it unnumbered and got a full set of numbers.

I think `.. rubric` should just create `\paragraph*{...}` instead of `\paragraph{...}`. (Changing "secnumdepth" is not an option, as I have other paragraphs (and subparagraphs) that should be numbered.)

**Comment by tk0miya** [comment]
+1; reasonable.

The reST definition says it is not a part of document structure.

>A rubric is like an informal heading that doesn't correspond to the document's structure.
>http://docutils.sourceforge.net/docs/ref/rst/directives.html#rubric

I don't know `\paragraph*{...}` is best. But I can say `\paragraph{...} is not good.

Note: We have to change the behavior carefully. This might be a bug. But it is longly used behavior, so it is like an incompatible change. It might be needed a migration path.

**Comment by tk0miya** [comment]
@Jellby it would be nice if you use our issue template on next time. An input example is very helpful for me.

**Comment by jfbu** [comment]
> I don't know \paragraph*{...} is best. But I can say `\paragraph{...} is not good.

I agree. Sure that `\paragraph{..}` is a bug. Using `\paragraph*` is minimal change to obey Docutils specs, although not clear if fully satisfying.

But +1 for `\paragraph*`.
