### ISSUE TITLE
Broken Search

### ISSUE THREAD

**Issue by cruggieri** [sphinx-doc/sphinx#4649]
### Problem
- Broken Search

build docs with: $make html works as a charm. Pointing docs via webserver is working fine, but search doesn't works:
- cannot find any numbers: index.rst contain "1234567", which is displayed on browser,but if I search it no results displayed. This happen also with IP Address, and others numbers;
- Lots of words with dots doesn't appear: if I search www.example.com, search doesn't find it.

#### Error logs / results
No errors displayed

#### Expected results
Search results.

### Reproducible project / your project
Private project.

### Environment info
- OS: Linux Ubuntu 14.04.5
- Python version: 2.7.6
- Sphinx version: 1.7.0
- same behaviour in multiple browsers.

**Comment by cruggieri** [comment]
Made another test in this enviroment:
OS: Linux Ubuntu 16.04
Python version: 3.5
Sphinx version: 1.7.0

A little better. Now I can find hostnames. But problem is still present serching numbers.
"1234567" as simple text in index.rst doesn't appear.

**Comment by tk0miya** [comment]
@shibukawa could you check this please?

**Comment by PatrickMassot** [comment]
Another example: searching for "calc" in [Theorem proving in Lean](https://leanprover.github.io/theorem_proving_in_lean/search.html?q=calc&check_keywords=yes&area=default) returns a couple of result but completely misses [a full subsection](https://leanprover.github.io/theorem_proving_in_lean/quantifiers_and_equality.html#calculational-proofs) whose title contains "calc" and whose body contains 13 occurences.

**Comment by tk0miya** [comment]
@PatrickMassot The searching of Sphinx goes exact match. It seems Chapter 4.3 does not contain the "calc" word. I know highlighting is not good. It behaves like partial match. That's very confusable.

**Comment by PatrickMassot** [comment]
The title of the section does not contain the full word but the body contains it a lot.

**Comment by tk0miya** [comment]
@PatrickMassot It seems your case is not same as this issue says. Please file a new issue, and please let me know in detail. I'd like to know what you expect.

**Comment by PatrickMassot** [comment]
@tk0miya Thank you. I've opened:  #4711 with a guess of what goes wrong (the word appears only in code snippets).

**Comment by TimoL** [comment]
I think we're also affected by the ``Lots of words with dots doesn't appear`` problem.
Our generated html website contains filenames like ``some_file.py``.

* Search for ``some_file`` matches.
* Search for ``some_file.py`` does not match.

**Comment by TimKam** [comment]
@TimoL When searching for ``some_file.py``, the search splits ``some_file`` and ``py`` in separate terms (which makes sense). It looks like the problem is that the search function considers every page a "miss"/no match if the search contains a term with length <= 2. I'll add a PR for this.

**Comment by TimoL** [comment]
@TimKam thx for taking care :)
