### ISSUE TITLE
sphinx-apidoc question

### ISSUE THREAD

**Issue by raybellwaves** [sphinx-doc/sphinx#4654]
Subject: First time sphinx user, so have a basic question.

### Question
I'm using sphinx for the first time for a small project I started: https://github.com/raybellwaves/cfanalytics

I was able to follow the readthedocs.org [get started page](https://docs.readthedocs.io/en/latest/getting_started.html).

I'm now trying to document and show the API.

I then tried
`sphinx-apidoc -o source/ ../cfanalytics`
which now lists:
```
$ cd source
$ ls
cfanalytics.core.rst	cfanalytics.rst		cfanalytics.tests.rst	modules.rst
```
But i'm now not sure what to do with these and how to include it my index.rst to show something on http://cfanalytics.readthedocs.io/en/latest/#

I couldn't find much help online. The doc for [`sphinx-apidoc`](http://www.sphinx-doc.org/en/stable/man/sphinx-apidoc.html) shows how to use it but I couldn't find any step-by-step tutorials which show what to do after typing the `sphinx-apidoc` command.

Edit: On closer inspection opening the file https://github.com/raybellwaves/cfanalytics/blob/master/docs/_build/html/py-modindex.html seems fine on my laptop. It may be something to do with readthedocs which i'm looking into (https://stackoverflow.com/questions/48878411/readthedocs-build-failing-using-aiohttp)

### Environment info
- OS: MacOS 10.13.3
- Python version:  3.6.4
- Sphinx version: 1.6.6 (I use python installed from anaconda and installed sphinx using `conda install -c anaconda sphinx`)

Cheers,
Ray

**Comment by tk0miya** [comment]
This is an issue list of Sphinx, not a forum.
Please post a question to sphinx-users list: https://groups.google.com/forum/#!forum/sphinx-users
I think many sphinx users will help you.

FYI: I think toctree is good for your case.
http://www.sphinx-doc.org/en/master/markup/toctree.html

**Comment by raybellwaves** [comment]
Thanks a lot. I'll close this. Mind it I make a quick PR to add the google-group url into the README? I was looking for something like this to post
