### ISSUE TITLE
Reading objects.inv fails again in 1.7.0.

### ISSUE THREAD

**Issue by ederag** [sphinx-doc/sphinx#4664]
### Problem
- Reading PyQt5 remote `objects.inv`, adapting from [this answer](https://stackoverflow.com/a/36831198/3565696) failed.
But it is not limited to PyQt5. The command 
`python -m sphinx.ext.intersphinx 'http://python-eve.org/objects.inv'`
fails with the same error, although it was claimed to work with 1.6.2 in [this comment](https://stackoverflow.com/questions/30939867/how-to-properly-write-cross-references-to-external-documentation-with-intersphin?rq=1#comment77204692_36831198).

#### Procedure to reproduce the problem
```
python3 -m sphinx.ext.intersphinx 'http://pyqt.sourceforge.net/Docs/PyQt5/objects.inv'
```
#### Error logs / results
```
Print out an inventory file.
Error: must specify local path or URL to an inventory file.
```

#### Expected results / workaround / clue

As a workaround, adding another argument before the url (e.g. `aa`, but any would do), like in
```
python3 -m sphinx.ext.intersphinx aa 'http://pyqt.sourceforge.net/Docs/PyQt5/objects.inv'
```
yield the expected result:

```
<snipped>
        ref-module-index                         Modules                                 : modules.html#ref-module-index
        ref-opengl                               Support for OpenGL                      : opengl.html#ref-opengl
        ref-qvariant                             Support for QVariant                    : pyqt_qvariant.html#ref-qvariant
        search                                   Search Page                             : search.html
```

The reason is probably the [`len(argv) < 2` check](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/ext/intersphinx.py#L384).

### Environment info
- OS: Linux
- Python version: 3.4.6
- Sphinx version: 1.7.0

**Comment by tk0miya** [comment]
Fixed by #4665

**Comment by tk0miya** [comment]
Thank you for reporting!

**Comment by ederag** [comment]
Confirmed, it works fine with 1.7.1. Congratulations !
