### ISSUE TITLE
.. raw:: latex is not includes with sphinx 1.7

### ISSUE THREAD

**Issue by rddaz2013** [sphinx-doc/sphinx#4677]
Subject: .. raw:: latex is not include with sphinx 1.7

### Problem
- content after ".. raw:: latex" is not includes with sphinx 1.7 

#### Procedure to reproduce the problem
```
make latexpdf
```

#### Error logs / results
```
no error log only content is missing
```

### Environment info
- OS: '3.6.1 |Anaconda custom (64-bit)| (default, May 11 2017, 13:09:58) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]'
- Sphinx version: 1.7.0
- <Extra tools e.g.: Browser, tex or something else>

**Comment by tk0miya** [comment]
On my local, it seems working fine.
Could you show me an example of reST file and generated .tex file please?

**Comment by jfbu** [comment]
On simple project I see no problem either.

**Comment by rddaz2013** [comment]
aftermate from #3594

> some code
> 
> .. raw:: latex
> 	\begin{OriginalVerbatim}[commandchars=\\\\\\{\\}]
> 		hello too
> 	\end{OriginalVerbatim}
> 		
> * item1
> * item2

works in my old env...

now i need

> some code
> 
> .. raw:: latex
>
> 	\begin{OriginalVerbatim}[commandchars=\\\\\\{\\}]
> 		hello too
> 	\end{OriginalVerbatim}
> 		
> * item1
> * item2

**Comment by jfbu** [comment]
@rddaz2013 It worked really? I thought rst directives had to be followed by empty line after options. Thus, seems old syntax was working by chance. I don't see if you have correct indentation here but I guess you do.

**Comment by rddaz2013** [comment]
For my 'Latex' -documents i have a submission page - that was just gone now after the update to 1.7.
Nothing serious - but confusing the moment I discovered the missing pages in the report.

It may be that my preprocessing of the rst / markdown file is the real cause. One part adding a "\n" into the block and now not anymore.

Can be closed..
Sorry for the inconvenience
