### ISSUE TITLE
literal text got colored python keywords

### ISSUE THREAD

**Issue by rpuntaie** [sphinx-doc/sphinx#4679]
In 

```
Example::
  This is not Python
```

``is`` and ``not`` are colored.

Sphinx 1.7.1

**Comment by tk0miya** [comment]
This is not a bug. By default, `highlight_language` is set as `python3`.
http://www.sphinx-doc.org/en/master/config.html#confval-highlight_language

**Comment by rpuntaie** [comment]
It is a reasonable default for 

```
.. code-block::
```

or 

```
.. code::

```

but one cannot apply any coloring for my example above. 
That is rather to be treated like the text enclosed in double backticked

```
``this is not colored``
```

Your link doesn't say anything about my example.

**Comment by tk0miya** [comment]
In reST, both `::` notation and `.. code::` directive are used for creating "literal-block".
http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#literal-blocks
http://docutils.sourceforge.net/docs/ref/rst/directives.html#code

In Sphinx, they are also treated as same.

**Comment by rpuntaie** [comment]
From http://docutils.sourceforge.net/docs/ref/rst/directives.html#code

    The "code" directive constructs a literal block.

"code is a literal block" does not mean that all literal blocks are code.

    If the code language is specified, the content is parsed by the Pygments syntax highlighter 

So there should be no default coloring for ``.. code::``.

This was about the code diretive. 
It doesn't say anything about ``::``-started literal block.
That is a literal, block that is not a code block.

Why would you treat a ``::``-started literal block as a code block.
For that there is the code directive.

We have to give 

``::``

and

``.. code::``

a different meaning,
because why else would one chose to write
either the first or the second.
If we started from scratch,
we would have the opportunity to give the choice a meaning.
But ``RST`` is there already for some time
and why should we deteriorate it.

Another argument:

There are more tools processing RST: rst2html, Pandoc, Sphinx
All of them should have the same result.
RST should not be dependent on the tool one uses.

On can extend RST and Sphinx did,
but the extension must not contradict existing specifications.

Also editors depend on a stable RST specification.

**Comment by rpuntaie** [comment]
There are more tools processing RST: rst2html, Pandoc, Sphinx
All of them must have the same result.
RST must not be dependent on the tool one uses.

It is only that, when extending the RST specification, 
some tools can be first to implement the new things.
Sphinx can and did extend RST, 
but the extension must not contradict existing specification.

Of course, "must" has the sense of "is reasonable".

**Comment by jfbu** [comment]
Just add

```rst
.. highlight:: none
```

before

and

```rst
.. highlight:: default
```

(or whatever) after the part of your source where you don't want any syntax highlighting.

**Comment by rpuntaie** [comment]
1) You missed my point.

2) I tried

```
.. highlight:: none

::

    test if not highlighted

.. code:: python

    if test is highlighted:
        return OK

.. highlight:: default
```

and it does not "return OK". 

It would be OK if in conf.py one could set the behavior such
that the example here worked as expected, i.e. as before.

Then 

- those who do want ``::`` to color in python as well as
- those who do not want ``::`` to color in python 

can be satisfied.

**Comment by jfbu** [comment]
I did get your point but assumed you would be using Sphinx ``code-block`` directive, not the Docutils  ``code``. If you use the ``code-block`` directive, from

```rst
.. highlight:: none

::

  test if not highlighted

.. code-block:: python

   if test is highlighted:
       return OK

.. highlight:: default
```

you do get

![capture d ecran 2018-03-23 a 14 49 25](https://user-images.githubusercontent.com/2589111/37832625-698207dc-2ea9-11e8-8f46-c1db118b67ca.png)

Simpler alternative is probably to set ``highlight_language = 'none'`` in conf.py, then from

```rst
::

  test if not highlighted

.. code-block:: python

   if test is highlighted:
       return OK

```

you get same output as image above.

Regarding the ``code`` directive it does obey ``highlight_language`` or the ``.. highlight::`` directive, producing thus non-highlighted result in the situations above.

Regarding the behaviour of ``::``  a change of behaviour occurred at Sphinx 1.4. Then this

```rst
::

  test if not highlighted

.. code-block:: python

   if test is highlighted:
       return OK

.. code:: python

   if test is highlighted:
       return OK

```

(and nothing in conf.py) started producing

![capture d ecran 2018-03-23 a 14 55 49](https://user-images.githubusercontent.com/2589111/37832973-73df32da-2eaa-11e8-8b49-f395efacdd67.png)

whereas at Sphinx 1.3.6 the same source gave output

![capture d ecran 2018-03-23 a 14 57 55](https://user-images.githubusercontent.com/2589111/37833041-9b3456da-2eaa-11e8-9706-39ed96d83ae4.png)

I don't know if the change was properly documented. The relevant commit is c1b7b6f369ab5622774a418cda6356bd887601d9.

@tk0miya what do you think, is this Sphinx 1.4 change of behaviour of ``::`` code blocks regarding highlighting a bug? At Sphinx 1.3.6, ``::`` and ``.. code::`` were not treated the same.

remark: all my testing above done with Docutils version 0.14, for lazyness of setting up complete virtual envs.

**Comment by jfbu** [comment]
At end of previous comment, explanation is simply presumably that

```
::

  test if not highlighted
```

is not recognized as valid Python2 by the Pygments python lexer, hence at Sphinx 1.3.6, this is why it got not highlighted. For example, if I try

```rst
::

  def foo(x):
      return None
```

I do get highlighting with Sphinx 1.3.6 (and nothing in conf.py)

![capture d ecran 2018-03-23 a 15 23 53](https://user-images.githubusercontent.com/2589111/37834533-3936b546-2eae-11e8-8431-8ef28e224b85.png)



This had been indeed my first understanding but then tried ``highlight_language = 'python'`` with Sphinx 1.4.0 and it (i.e. the sentence with ``if not`` below) still got highlighted, contrarily to my fleeting expectations.

```
::

  test if not highlighted
```

hence I got confused at this stage.


At sphinx 1.4, Python3 lexer is used and it behaves differently,  thus highlighting arises.

**Comment by jfbu** [comment]
My explanation about Python2 lexer not accepting ``test if not highlighted`` isolated as genuine Python is pure non-sense:

![capture d ecran 2018-03-23 a 15 38 18](https://user-images.githubusercontent.com/2589111/37835386-572d265a-2eb0-11e8-83de-db73236d6201.png)

Hence I do not know why at Sphinx 1.3.6 the input

```
::

  test if not highlighted
```

produced no highlighting.

**Comment by tk0miya** [comment]
Sorry for very late response.

>This was about the code diretive.
>It doesn't say anything about ::-started literal block.
>That is a literal, block that is not a code block.

In docutils, there are no "code block". The internal representation format of docutils (a.k.a. doctree) considers the output of both literal-notation and `code` directive as "literal_block".
http://docutils.sourceforge.net/docs/ref/doctree.html
Sphinx make them colored with `highlight_language` setting.

In docutils, there are no "default highlight" setting. So literal notation is not colored. But it does not mean literal notation must not be colored.

In addition, `highlight_language` is used since Sphinx-0.5. It is a basic setting of Sphinx. So I don't like to change its default. It's breaking change.

Note: Unfortunately, Sphinx does not support `code` directive yet. Because it was added after Sphinx's `code-block`.

**Comment by rpuntaie** [comment]
```
highlight_language = "none"
```

in ``conf.py``

and using ``.. code-block:: `` instead of ``.. code::``

gives me the wanted behavior.

Thanks a lot for the clarification.
