### ISSUE TITLE
asciinema video support

### ISSUE THREAD

**Issue by shahzebsiddiqui** [sphinx-doc/sphinx#4680]
I would like to add asciinema https://asciinema.org/ video into my documentation. I don't know if there is a way to embed the video so you can view it inside the documentation. I dont want to link to the page since that defeats the purpose of this issue request.

Please see https://asciinema.org/docs/embedding for more details on asciinema embedding support

**Comment by tk0miya** [comment]
-1; It would be nice if this is implemented as Sphinx extension, not sphinx-core.

**Comment by tk0miya** [comment]
I'm closing this now.
Thank you for your proposal!

**Comment by shahzebsiddiqui** [comment]
@tk0miya can you add this issue in Sphinx Extension project. I am not sure where I am suppose to post this feature request.

**Comment by tk0miya** [comment]
Sphinx extensions are created by many people. For example, over 100 packages are registered to PyPI.
https://pypi.python.org/pypi?:action=browse&c=598

Sphinx extension is ecosystem of Sphinx. Not a single project. So I can't file the your request.
sphinx-users list might be good to find who interested your idea.
https://groups.google.com/forum/#!forum/sphinx-users

Of course, it would be nice if you'll make the asciinema extension by yourself.
http://www.sphinx-doc.org/en/master/extdev/index.html

Thanks,

**Comment by andyofmelbourne** [comment]
I was able to embed an asciinema video in my sphinx docs with:

```
.. raw:: html

    <script src="https://asciinema.org/a/14.js" id="asciicast-14" async></script>
```

**Comment by divi255** [comment]
I made a little sphinx extension

https://github.com/divi255/sphinxcontrib.asciinema

just insert

.. asciinema:: 261648
