### ISSUE TITLE
role any does not work with intersphinx

### ISSUE THREAD

**Issue by juh2** [sphinx-doc/sphinx#4682]
### Problem

```any:`Builder` ``` does not link to sphinx.builders.Builder

#### Procedure to reproduce the problem

In conf.py

```
intersphinx_mapping = {
'sphinx': ('http://sphinx-doc.org', None)
}
```

In test.rst

```
:any:`Builder`
```

#### Error logs / results
```
WARNING: 'any' reference target not found: Builder
```

#### Expected results

Link to sphinx.builders.Builder

### Environment info
- OS: <Linux
- Python version:  3.5.3
- Sphinx version: 1.7.1

**Comment by tk0miya** [comment]
How about adding module?
```
:any:`sphinx.builders.Builder`
```

**Comment by tk0miya** [comment]
I'm closing this now.
Please feel free to reopen if you consider this is a bug of Sphinx.
Thanks,
