### ISSUE TITLE
Toctree not being translated

### ISSUE THREAD

**Issue by joelanders** [sphinx-doc/sphinx#4683]
[First reported in the Google Group, I'm opening an issue here on request](https://groups.google.com/forum/#!topic/sphinx-users/BMK0zWylFhQ)

### Problem
Not all of a `toctree`'s text is being translated.

Given an example `.rst`:
```
.. toctree::
   :maxdepth: 2
   :caption: Contents:

    Explicit Title <some_doc>
    External Link <https://google.com>
```
running `sphinx-build gettext` produces a `.pot` with a `msgid`/`msgstr` pair for "Contents:" but not "Explicit Title" or "External Link".

It's somewhat avoidable for "Explicit Title" if you just let it pull the title from some_doc.rst, but the explicit text is required for the external link, and it will stand out as being the wrong language on an otherwise-translated page.

This is version 1.5.5 on Linux; I think that's enough to reproduce^.
Thanks for the quick response in the Google Group.

**Comment by tk0miya** [comment]
+1

**Comment by tisonkun** [comment]
Any updates?

**Comment by tk0miya** [comment]
Fixed by #6784.
Thank you for reporting.

**Comment by tisonkun** [comment]
Thanks for your working @tk0miya !

**Comment by tisonkun** [comment]
One question here, how can I reach the change? Is it publish as a pip lib or I need to clone the repo and install manually?
