### ISSUE TITLE
Bad translation is causing compilemessages issue

### ISSUE THREAD

**Issue by tuchfarber** [sphinx-doc/sphinx#4692]
Subject: Running compilemessages on a project that depends on Sphinx causes an error due to a bad translation.

### Problem
- A translation in the zh_CN locale has a mismatch of formatting variables. The message_id has 2 and the translation only has 1, causing an error. 

#### Procedure to reproduce the problem
1. Create a django project that has Sphinx as a dependency
2. Run `python manage.py compilemessages`

#### Error logs / results
```
CommandError: Execution of msgfmt failed: <REDACTED>/.venv/lib/python2.7/site-packages/sphinx/locale/zh_CN/LC_MESSAGES/sphinx.po:1298: number of format specifications in 'msgid' and 'msgstr' does not match
```

#### Expected results
`compilemessages` command should run without error.

#### Possible fix
I have a PR to remove the bad translation here #4684 . Prior to commit bc068e4 this translation was empty, so I am returning it to it's empty state as I don't know the language. 

### Environment info
- OS: Ubuntu 14.04.5 LTS  
- Python version: 2.7
- Sphinx version: 1.7.0, 1.7.1 (1.6.7 works)

**Comment by tk0miya** [comment]
I'm closing this because this is duplicated with #4655.
Anyway, thank you for reporting!
