### ISSUE TITLE
python2 tests on Fedora, fail with import error on Sphinx 1.7+

### ISSUE THREAD

**Issue by stratakis** [sphinx-doc/sphinx#4710]
### Problem
On the Fedora build system, when invoking the tests under python2 with `make test` some tests fail with <ImportError: No module named websupport> . Full build log is attached. The sphinxcontrib-websupport is packaged for Fedora and pulled during build. There is no failure when invoking the tests under python3.

#### Procedure to reproduce the problem
Unfortunately it wasn't possible for me to reproduce it outside the build system, by invoking the tests at my own machine or through venv.

#### Error logs / results
Build log is attached. The failures are towards the end.
[build.log](https://github.com/sphinx-doc/sphinx/files/1781889/build.log)

### Environment info
- OS: Fedora 27+
- Python version: 2.7.14
- Sphinx version: 1.7+

**Comment by tk0miya** [comment]
What can I help you with? It looks there are no `sphinx.writers.websupport` on building.

**Comment by stratakis** [comment]
It seems that sphinx.writers.websupport is indeed there while building however the tests are not able to discover it. During the testing phase of the build (but before invoking `make test`) I also invoked the interpreter and imported the module successfully. Adjusted PYTHONPATH as well but the same issue. Will try to debug further.

**Comment by stratakis** [comment]
List of failed (and one passed) tests:

tests/test_api_translator.py::test_html_translator PASSED
tests/test_api_translator.py::test_html_with_set_translator_for_html_ ERROR
tests/test_api_translator.py::test_singlehtml_set_translator_for_singlehtml ERROR
tests/test_api_translator.py::test_pickle_set_translator_for_pickle ERROR
tests/test_api_translator.py::test_json_set_translator_for_json ERROR
tests/test_api_translator.py::test_html_with_set_translator_for_latex ERROR
tests/test_api_translator.py::test_html_with_set_translator_for_man ERROR
tests/test_api_translator.py::test_html_with_set_translator_for_texinfo ERROR
tests/test_api_translator.py::test_html_with_set_translator_for_text ERROR
tests/test_api_translator.py::test_html_with_set_translator_for_xml ERROR
tests/test_api_translator.py::test_html_with_set_translator_for_pseudoxml ERROR

**Comment by stratakis** [comment]
Actually I was able to reproduce it on a Fedora system, not sure why I couldn't get it before. On the latest stable Fedora just by invoking `make test` I can get the error:

> E       from sphinx.writers.websupport import WebSupportTranslator
E   ImportError: No module named websupport

And the same import actually succeeds if it's run from within a python shell. The issue only persists under python2.

**Comment by stratakis** [comment]
Seems that invoking pytest on its own doesn't pose any issues.
`pytest -v tests/test_api_translator.py` is fine while,
`python -m pytest -v tests/test_api_translator.py` triggers the error.
It might be a pytest issue.

**Comment by stratakis** [comment]
@nicoddemus any insight here?

**Comment by nicoddemus** [comment]
`pytest -v ...` and `python -m pytest -v ...` are slightly different, in the latter `python` will also add the current directory to `PYTHONPATH`. See: https://docs.pytest.org/en/latest/pythonpath.html#invoking-pytest-versus-python-m-pytest

**Comment by tk0miya** [comment]
I confirmed with this Dockerfile.
```
FROM fedora:latest

RUN dnf install -y git python2 python2-pip ImageMagick
RUN git clone https://github.com/sphinx-doc/sphinx
WORKDIR /sphinx
RUN git checkout 1.7
RUN pip install --user -e .[test,websupport]
ENV LC_ALL=C.utf-8
RUN make test
```
This passed almost of tests:
```
============= 1202 passed, 24 skipped, 1 xfailed in 127.15 seconds =============
```
I hope this recipe helps you.

**Comment by tk0miya** [comment]
Any updates?

**Comment by tk0miya** [comment]
Since Sphinx-2.0, we've dropped python2 support. So there nothing to do for this issue.
So I'm closing this.
Thanks,
