### ISSUE TITLE
html_theme ignored for builder QtHelp in Sphinx >= 1.5.0

### ISSUE THREAD

**Issue by SKremers** [sphinx-doc/sphinx#4722]
Up to Sphinx version 1.4.9 the configured html_theme was also used for qthelp. 
Since version 1.5.0 it is used for html but not qthelp. qthelp html ignores the configured theme and only uses nonav.

### Problem
The html files created for qthelp only use nonav theme. That may be an acceptable default, but there should be a way to configure something else.

The documentation still hints that html_theme is also used for html help builders. Since qthelp is a html based format I always understood it to be a variant of html help. 

The documentation is unclear or doesn't fit to the behavior anymore. 

We cannot upgrade to Sphinx beyond 1.4.9 because it would break the look and feel of our documentation.

#### Procedure to reproduce the problem
Create a sphinx-quickstart project with defaults.
Change directory to the project.

``sphinx-build -b qthelp . _build/qthelp``
``sphinx-build -b html . _build/html``
open ``_build\html\index.html`` and
``_build\html\index.html`` in a browser.

#### Error logs / results
Nothing suspicious, I guess:
```
Running Sphinx v1.7.1
making output directory...
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [qthelp]: targets for 1 source files that are out of date
updating environment: 1 added, 0 changed, 0 removed
reading sources... [100%] index
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index
generating indices... genindex
writing additional pages...
copying static files... done
copying extra files... done
writing project file...
writing collection project file...
build succeeded.
```
#### Expected results
I expected the output for qthelp to be the same as that for html. I expected some documentation how to overrule the default nonav theme.

### Reproducible project / your project
[qhelp_no_html_theme.zip](https://github.com/sphinx-doc/sphinx/files/1792514/qhelp_no_html_theme.zip)

### Environment info

- OS: Windows 10 (same problem on Linux)
- Python version: 2.7.14
- Sphinx version: 1.7.1 (also confirmed in: 1.5.0, 1.5.6, 1.6.6, 1.6.7)
- Browsers: Chrome, Edge, Qt Assistant

**Comment by tk0miya** [comment]
What about setting up `qthelp_theme`?
http://www.sphinx-doc.org/en/master/config.html#confval-qthelp_theme

**Comment by SKremers** [comment]
That's it! Thank you very much for your quick reply! 

It seems I always used the documentation from stable (for Sphinx 1.6.8+). It's not documented there.
http://www.sphinx-doc.org/en/stable/config.html

Also, when I googled for "qthelp theme", the first three pages of results don't help.

For me, this issue is resolved. But maybe someone could merge the _Options for QtHelp output_ to the stable branch.

**Comment by tk0miya** [comment]
Thank you for letting me know. But, unfortunately, we only maintain the document on master branch. So please refer the latest one.
Thanks,
