### ISSUE TITLE
Intl documentation fix

### ISSUE THREAD

**Issue by scottpetrovic** [sphinx-doc/sphinx#4734]
I was setting up the sphinx-intl and kept getting stuck at this step (I am on Windows)
This page: http://www.sphinx-doc.org/en/master/intl.html 

Step 6 has this command.

make -e SPHINXOPTS="-D language='de'" html 

Which is giving an error. After moving a few things around this command works...

make html -e SPHINXOPTS="-D language='de'"

**Comment by tk0miya** [comment]
man page of GNU make says:
```
NAME
       make - GNU make utility to maintain groups of programs

SYNOPSIS
       make [ -f makefile ] [ options ] ... [ targets ] ...
```

What type of `make` command did you use?

@shimizukawa any comment?

Note: GNU make also accepts `make html -e SPHINXOPTS...` command.

**Comment by scottpetrovic** [comment]
I just did all the default options when setting up the sphinx install.  I am guessing it is using the make.bat file that Sphinx generates.

when I was doing what was on the instructions, it gave me the error "-b expects an argument". moving the html earlier made it go away and it seems to work right then. I am on Sphinx 1.68 that I downloaded from pip.

**Comment by tk0miya** [comment]
I see. Indeed, `make.bat` might not work with `make -e SPHINXOPTS...`.
+1 for update!

**Comment by shimizukawa** [comment]
Sorry for your inconvenience. Correct information is this:

for BSD/GNU make:

- `make -e SPHINXOPTS="-D language='de'" html`
- `make html SPHINXOPTS="-D language='de'"`

for make.bat on Windows command-line:
```
set SPHINXOPTS=-D language='de'
.\make.bat html
```

for make.bat on Windows PowerShell:
```
Set-Item env:SPHINXOPTS "-D language='de'"
.\make.bat html
```

**Comment by shimizukawa** [comment]
fixed. Thanks for your reporting!
