### ISSUE TITLE
sphinx-apidoc 1.7.1 ignores all subpackages but first encountered

### ISSUE THREAD

**Issue by pkaramol** [sphinx-doc/sphinx#4737]
Subject: <what happen when you do on which document project>

### Problem

I have the following structure in my project:

 ```
  .
     my_project/
      |
      __init__.py
       pythonfile1.py
       pythonfile2.py
      package1/
        | 
        __init__.py
        datatypes.py
        decorators.py
      package2/
        | 
        __init__.py
        somefile.py
        anotherfile.py
      (...more packages following)
```

#### Procedure to reproduce the problem
```
root@02fj3e08i43: mkdir -p ~/rst ~/html
root@02fj3e08i43: sphinx-apidoc -o rst/ /path/to/my_project/
```

The above command will create in my `~/rst` folder:

```
root@02fj3e08i43: ls -1 ~/rst

my_project.package1.somesubpackage.rst
my_project.package1.anothersubpackage.rst
my_project.package1.rst
my_project.package2.somesubpackage.rst
my_project.package2.rst
...(rsts for all packages/subpackages)...
modules.rst
```

However: 

```
root@02fj3e08i43:~# head -30 ~/rst/my_project.rst 
my\_project package
====================

Subpackages
-----------

.. toctree::

    my_projecy.package1

Submodules
----------

```
...(direct submodules of `my_project` following...)

The problem (unexpected outcome) is that beneath `.. toctree:` directive, **only the first package (`package1`) lying directly under `my_project` is listed**;
as a consequence, when running `sphinx-build rst html`, the `index.html` has no listings of the other packages!

#### Error logs / results
No error-specific logs generated

#### Expected results
<Describe what to actually do>

### Environment info
- OS: happens on both `Debian 9` + `Ubuntu 16.04.03`
- Python version: `2.7.9`
- Sphinx version: `sphinx-apidoc 1.7.1`

**Comment by tk0miya** [comment]
I confirmed the issue with this Dockerfile.
```
FROM tk0miya/sphinx-html

RUN mkdir -p my_project/package1 my_project/package2
RUN echo '' > my_project/__init__.py
RUN echo '' > my_project/pythonfile1.py
RUN echo '' > my_project/pythonfile2.py
RUN echo '' > my_project/package1/__init__.py
RUN echo '' > my_project/package1/datatypes.py
RUN echo '' > my_project/package1/decorators.py
RUN echo '' > my_project/package2/__init__.py
RUN echo '' > my_project/package2/somefile.py
RUN echo '' > my_project/package2/anotherfile.py
#RUN pip3 install git+https://github.com/sphinx-doc/sphinx@1.7
RUN sphinx-apidoc -o docs/ my_project
RUN find docs/
RUN cat docs/my_project.rst
```

This is same as #4520, and already fixed in HEAD of 1.7 branch.
Thank you for reporting!
