### ISSUE TITLE
Allow to build Japanese PDF document on windows

### ISSUE THREAD

**Issue by tk0miya** [sphinx-doc/sphinx#4739]
### Problem
- On windows, there are no way to build Japanese PDF document (see #3807, #4716)
- It expects to install `make.exe` and `sh.exe` internally

#### Expected results
- Allow to build Japanese PDF document on Windows
- It would be nice if no extra software to do that

### Environment info
- OS: Win
- Sphinx version: 1.7

**Comment by tk0miya** [comment]
After #4911 and #5264, we can do it finally :-)

**Comment by shimizukawa** [comment]
㊗️ !!
