### ISSUE TITLE
Allow loading intersphinx inventory files from a proxy

### ISSUE THREAD

**Issue by gaborbernat** [sphinx-doc/sphinx#4765]
In case of enterprise environments the build env might not have access to the outside world directly (for security reasons). In these cases a good compromise is to cache and host the inventory file internally (e.g. ``https://docs.python.org/3/objects.inv`` might be hosted under ``dev.magic.com/python/3/objects.inv``).  The way intersphinx now works it also means that if one would specify the internal link to the file, although the download would succeed all generated intersphinx would point to where the ``objects.inv`` is hosted, e.g. ``dev.magic.com/python/3/typing.html#typing.Union``. This is because https://github.com/sphinx-doc/sphinx/blob/master/sphinx/ext/intersphinx.py#L199 passes in the root URI specified for the download location.

Proposal: we should allow the user to specify separately the points too uri. The current  ``intersphinx_mapping`` interface does not seem extensible for this, as all elements of the tuple are joined to get the download URI:

```python
intersphinx_mapping = {'python': ('http://dev.magic.com/python/3/', 'objects.inv')}
```

So I recommend a new settings ``intersphinx_links_to`` based on the same key-value tuple interface:

```python
intersphinx_links_to= {'python': ('https://docs.python.org/3/', None)}
```

If we agree on the how to, I can make a PR.

**Comment by tk0miya** [comment]
I believe you can do that already with this:
```
intersphinx_mapping = {
    'python': ('https://docs.python.org/3/', 'http://dev.magic.com/python/3/objects.inv)
}
```

The second element of the tuple also accepts an URL for inventory file.

**Comment by gaborbernat** [comment]
@tk0miya you are correct, thanks!

**Comment by Eldadc** [comment]
Is it possible to elaborate on how to migrate a site to an offline env ?
