### ISSUE TITLE
URL footnotes don't start at 1 in latexpdf build 

### ISSUE THREAD

**Issue by ekpgh** [sphinx-doc/sphinx#4784]
### Problem
I'm building a multi-chapter PDF document in Sphinx with footnotes that reference URLs outside of the document. 

- The first footnote in the document does not start at 1, it starts at some large number (32 in my case)
- Footnote numbers are skipped when assigning numbers in subsequent chapters. That is, if chapter 1 includes footnotes 32-40, the first footnote in chapter 2 is not 41, it's some larger value. 

Originally I found this problem when I used InterSphinx and set `latex_show_urls = 'footnote'` in conf.py but later I found I can reproduce it simply by using a footnote that references an rst_prolog substitution that contains a URL. 

More details are here: https://groups.google.com/forum/#!topic/sphinx-users/e93WiwjrQLg 
(This thread also includes a workaround to override footnote numbering that seems to be working for me.)

#### Procedure to reproduce the problem

The attached example project reproduces the problem when built with `make latexpdf`.

I saw slightly different behavior when I built the project on Sphinx 1.6.6 compared to building on 1.7.1. In 1.6.6 I believe it did not skip additional footnote numbers between chapters, it only started at a large number (also the first footnote was around number 43 instead of 32). 

#### Error logs / results

see sample project
 
#### Expected results

Footnotes should start at 1 and be numbered sequentially throughout the document without skipping numbers.

(It would be nice if we could easily configure whether or not to restart footnote numbering each chapter, but that's a separate issue.)

### Reproducible project / your project

Example project: 
[footnote_debug.zip](https://github.com/sphinx-doc/sphinx/files/1848430/footnote_debug.zip)

### Environment info
- OS: MacOS 10.13.3
- Python version: 2.7
- Sphinx version: 1.6.6 and 1.7.1

**Comment by tk0miya** [comment]
Note: Internally, docutils leaves `substitution_definition` node as is even after substitution. As a result, LaTeX writer fails to assign correct numbers to footnotes.

**Comment by tk0miya** [comment]
Fixed by #4827 
Thank you for reporting!
