### ISSUE TITLE
[napoleon] Add strings to translation file for localisation for the Napoleon extension.

### ISSUE THREAD

**Issue by dullin** [sphinx-doc/sphinx#4785]
Subject: Keywords in napoleon but not used in translated domain do not get translated .

### Problem
The following sections from the napoleon extension are not translated when using another language in the sphinx config file.
- Example
- Examples
- Raises
- References
- Yields

I tried checking inside the translation files (the sphinx.po files) and it seems the strings aren't located inside the translation file for localisation.

#### Procedure to reproduce the problem
Start a sphinx project, set the language to something other than en (used fr in my case). Add the napoleon extension to your config.py and use autodoc on a function that has the mentionned section.

Build for HTML or LaTeX
#### Error logs / results
The named section don't have translations and are in english instead of the specified language

#### Expected results
Sections should have appropriate names for the napoleon specific sections

### Reproducible project / your project
Here's a repo and a small zip of a sample project with a python function and HTML generated with the sections not translated correctly.
https://github.com/dullin/sphinxnapoleontesttranslation
https://github.com/dullin/sphinxnapoleontesttranslation/releases/download/1.0/sphinxnapoleontesttranslation.zip

### Environment info
- OS: macOS 10.13.3
- Python version: 3.6.4
- Sphinx version: 1.7.1

**Comment by tk0miya** [comment]
It seems the download file is broken. Could you check it please?

>https://file.io/TZUmbG

**Comment by dullin** [comment]
I made a repo of the project and zipped it here
https://github.com/dullin/sphinxnapoleontesttranslation/releases/download/1.0/sphinxnapoleontesttranslation.zip

**Comment by tk0miya** [comment]
Confirmed. Certainly the labels listed up in `_sections` are not translated.
https://github.com/sphinx-doc/sphinx/blob/525f3bd10435398f070f27e4c57800b93eda652f/sphinx/ext/napoleon/docstring.py#L141-L172

**Comment by tk0miya** [comment]
Fixed by #4999. It will be fixed in next major release (1.8.0).
Thank you for reporting.
