### ISSUE TITLE
Install sphinx

### ISSUE THREAD

**Issue by brianlane** [sphinx-doc/sphinx#4786]
Subject: I'm trying to install sphinx to later use with a Dockerfile

### Problem
- Here is the problem received from npm run docs:

Running Sphinx v1.7.2
loading pickled environment... failed: unsupported pickle protocol: 4

Exception occurred:
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

#### Procedure to reproduce the problem
wget https://github.com/veg/phylotree.js/archive/master.zip
unzip master.zip
cd phylotree.js-master/
pip install -r requirements.txt
npm run docs

#### Error logs / results
cat /phylotree.js-master/npm-debug.log 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'docs' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose run-script [ 'predocs', 'docs', 'postdocs' ]
5 info lifecycle phylotree@0.1.6~predocs: phylotree@0.1.6
6 silly lifecycle phylotree@0.1.6~predocs: no script for predocs, continuing
7 info lifecycle phylotree@0.1.6~docs: phylotree@0.1.6
8 verbose lifecycle phylotree@0.1.6~docs: unsafe-perm in lifecycle true
9 verbose lifecycle phylotree@0.1.6~docs: PATH: /usr/share/npm/bin/node-gyp-bin:/phylotree.js-master/node_modules/.bin:/phylotree.js-master/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
10 verbose lifecycle phylotree@0.1.6~docs: CWD: /phylotree.js-master
11 silly lifecycle phylotree@0.1.6~docs: Args: [ '-c', 'sphinx-build -b html docs documentation' ]
12 silly lifecycle phylotree@0.1.6~docs: Returned: code: 2  signal: null
13 info lifecycle phylotree@0.1.6~docs: Failed to exec docs script
14 verbose stack Error: phylotree@0.1.6 docs: `sphinx-build -b html docs documentation`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid phylotree@0.1.6
16 verbose cwd /phylotree.js-master
17 error Linux 4.4.0-116-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "docs"
19 error node v4.2.6
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error phylotree@0.1.6 docs: `sphinx-build -b html docs documentation`
22 error Exit status 2
23 error Failed at the phylotree@0.1.6 docs script 'sphinx-build -b html docs documentation'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the phylotree package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     sphinx-build -b html docs documentation
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs phylotree
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls phylotree
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

#### Expected results
Should have installed the docs successfully

### Reproducible project / your project
This was preformed in the root directory as root in a virtual environment - atmosphere 

### Environment info
- OS: Ubuntu 16.04 GUI XFCE Base v2.1

**Comment by tk0miya** [comment]
Could you check the message from `sphinx-build -b html docs documentation` command?
I'd like to see the error message of Sphinx itself.

**Comment by brianlane** [comment]
Running Sphinx v1.7.2
loading pickled environment... failed: unsupported pickle protocol: 4

Exception occurred:
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
The full traceback has been saved in /tmp/sphinx-err-TlLriM.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!

**Comment by tk0miya** [comment]
Oh, sorry. I need the full traceback. Could you try it again?

**Comment by brianlane** [comment]
That is the full traceback (all the output) using the command you provided: sphinx-build -b html docs documentation

**Comment by tk0miya** [comment]
>The full traceback has been saved in /tmp/sphinx-err-TlLriM.log, if you want to report the issue to the developers.

Please see the message. The full traceback is saved to the file. What you see on console is short traceback.

**Comment by brianlane** [comment]
Ah sorry about that! Thanks
Here is the full traceback:

```
root@vm142-57:/# cat /tmp/sphinx-err-TlLriM.log
# Sphinx version: 1.7.2
# Python version: 2.7.12 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/cmdline.py", line 303, in main
    args.warningiserror, args.tags, args.verbosity, args.jobs)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/application.py", line 233, in __init__
    self._init_builder()
  File "/usr/local/lib/python2.7/dist-packages/sphinx/application.py", line 311, in _init_builder
    self.emit('builder-inited')
  File "/usr/local/lib/python2.7/dist-packages/sphinx/application.py", line 444, in emit
    return self.events.emit(event, self, *args)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/events.py", line 79, in emit
    results.append(callback(*args))
  File "/usr/local/lib/python2.7/dist-packages/sphinx_js/jsdoc.py", line 31, in run_jsdoc
    p = Popen(jsdoc_command, stdout=temp, stderr=PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by tk0miya** [comment]
It seems the error is raised from `sphinx_js`. I guess jsdoc is required to run it.
```
  File "/usr/local/lib/python2.7/dist-packages/sphinx_js/jsdoc.py", line 31, in run_jsdoc
    p = Popen(jsdoc_command, stdout=temp, stderr=PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
```

Anyway, this is a bug of `sphinx_js`. Please report this to their project.

**Comment by brianlane** [comment]
I got help in sphinx_js's project by having them tell me to use this command:

npm install jsdoc

which I followed with

npm install -g express

but I still receive the same full traceback

root@vm142-73:/phylotree.js-master# npm run docs

> phylotree@0.1.6 docs /phylotree.js-master
> sphinx-build -b html docs documentation

Running Sphinx v1.7.2
loading pickled environment... failed: unsupported pickle protocol: 4

Sphinx error:
jsdoc found no JS files in the directories ['/phylotree.js-master']. Make sure js_source_path is set correctly in conf.py. It is also possible (though unlikely) that jsdoc emitted invalid JSON.

npm ERR! Linux 4.4.0-116-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "docs"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! phylotree@0.1.6 docs: `sphinx-build -b html docs documentation`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the phylotree@0.1.6 docs script 'sphinx-build -b html docs documentation'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phylotree package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     sphinx-build -b html docs documentation
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phylotree
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phylotree
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /phylotree.js-master/npm-debug.log
root@vm142-73:/phylotree.js-master# sphinx-build -b html docs documentation
Running Sphinx v1.7.2
loading pickled environment... failed: unsupported pickle protocol: 4

Exception occurred:
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
The full traceback has been saved in /tmp/sphinx-err-WDrHsF.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
root@vm142-73:/phylotree.js-master# cat /tmp/sphinx-err-WDrHsF.log
# Sphinx version: 1.7.2
# Python version: 2.7.12 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/cmdline.py", line 303, in main
    args.warningiserror, args.tags, args.verbosity, args.jobs)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/application.py", line 233, in __init__
    self._init_builder()
  File "/usr/local/lib/python2.7/dist-packages/sphinx/application.py", line 311, in _init_builder
    self.emit('builder-inited')
  File "/usr/local/lib/python2.7/dist-packages/sphinx/application.py", line 444, in emit
    return self.events.emit(event, self, *args)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/events.py", line 79, in emit
    results.append(callback(*args))
  File "/usr/local/lib/python2.7/dist-packages/sphinx_js/jsdoc.py", line 31, in run_jsdoc
    p = Popen(jsdoc_command, stdout=temp, stderr=PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by tk0miya** [comment]
Sorry, we can't help that... Please ask to them.
Thanks,
