### ISSUE TITLE
Wrong argument name?

### ISSUE THREAD

**Issue by mortenvp** [sphinx-doc/sphinx#4787]
In https://github.com/sphinx-doc/sphinx/blob/a014caa4f04dd69df5fabd855080c54259557c4e/sphinx/application.py#L674

There is no argument called ``directiveclass`` should this be ``obj``? Sorry if this is a stupid question - I am new to Sphinx.

All the best,
Morten

**Comment by tk0miya** [comment]
Absolutely! Now fixing at #4788.
