### ISSUE TITLE
latex builds should not use "small" typeface for code-blocks with xelatex/lualatex

### ISSUE THREAD

**Issue by jfbu** [sphinx-doc/sphinx#4791]
For code-blocks in PDF builds, Sphinx uses by default `\fvset{fontsize=\small}`. This is because the legacy default font choice for pdflatex build was Courier which is bigger in apparence than Time which is used as text font. Furthermore, once upon a time, long lines would not wrap in code-blocks.

For xelatex/lualatex engines, the font is by default the one chosen by LaTeX for these engines, i.e. Latin Modern OpenType. Then the `\small` is really too small, I believe. I propose that Sphinx should not use `\small` by default then.

Here is a screenshot from a PDF build of the SciPy documentation v1.0.0. I added use of `xelatex` because of many Unicode characters.

![capture d ecran 2018-03-28 a 00 27 53](https://user-images.githubusercontent.com/2589111/37998466-fa5990a4-321e-11e8-8618-fcbdf57dc1fc.png)

I feel the code-blocks uses a too small typeface. Here is at normal size.

![capture d ecran 2018-03-28 a 00 32 30](https://user-images.githubusercontent.com/2589111/37998625-87e4ae0e-321f-11e8-9cc6-70e9f62496d0.png)

**Comment by tk0miya** [comment]
+1
