### ISSUE TITLE
A way for extensions to change configuration settings

### ISSUE THREAD

**Issue by cpitclaudel** [sphinx-doc/sphinx#4805]
There does not seem to be a way for extensions to change values in `app.config` before they are used by other parts of Sphinx. This would be a convenient feature for extensions that want to add suffixes to `source_suffix`, or add patterns to `exclude_patterns`, for example.

The best I could find was to use `app.connect('builder-inited', …)`, but it happens too late:

```python
self.config.init_values() # ← conf.py options are processed here

verify_required_extensions(self, self.config.needs_extensions)

primary_domain = self.config.primary_domain
if primary_domain and not self.registry.has_domain(primary_domain):
    logger.warning(__('primary_domain %r not found, ignored.'), primary_domain)

self.builder = self.create_builder(buildername)
self.config.check_types()
self._init_source_parsers()
self._init_env(freshenv) # ← find_files is called here
self._init_builder() # ← build-inited fires here
```

It would be nice to have a config-loaded event, or something similar.

Thanks!

### Environment info
- OS: Linux _ 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Python version: Python 3.5.2
- Sphinx version: sphinx-build 1.7.1

**Comment by tk0miya** [comment]
In 1.8, we'll introduce `config-inited` event. You can do it using this event.
http://www.sphinx-doc.org/en/master/extdev/appapi.html#event-config-inited

But I think it is not good way to override user configurations from extension.

To add `source_suffix`, we'll also add a new API `app.add_source_suffix`. So I recommend to use this instead.
http://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx.application.Sphinx.add_source_suffix

**Comment by cpitclaudel** [comment]
Thanks, these two new functions look very useful.
