### ISSUE TITLE
Feature request: exclude certain static assets from processing 

### ISSUE THREAD

**Issue by cpitclaudel** [sphinx-doc/sphinx#4811]
Hi there,

If I understand correctly, there is no way at the moment to tell Sphinx to not process certain source files (but still include them in the output).  In my case I have source files in `_static`, and I don't want Sphinx to touch them — they are just there to be downloaded.

Using `exclude_patterns`, Sphinx will ignore the files entirely and omit them from the output.  Using `html_extra_path`, Sphinx will copy the files twice (once is `html/_static` and once in `html`).

Is there a way to tell Sphinx to not process certain documents, but still include them in the output directories?  I know one trick (add `_static/<folder name>` to the exclusion list, which will work because the document finder uses full paths whereas copy_assets uses paths rooted at `_static`), but I'm not sure if it's intended to work that way.

Background: I have a Sphinx extension that turns source files (extension: `.fs`) with special comments into a reST document.   To work well, this extensions needs extra javascript and CSS files, but also WebAssembly files (`.wasm`) and other source files (`.fs`).  There extra files are large, so they are distributed separately from the extension.  Users copy them into their `_static` directory, under `_static/myextensionsassets`.  Unfortunately, Sphinx tries to process all the `.fs` files in `_static`, which takes a long time and isn't useful.

### Environment info
- OS: Linux _ 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Python version: Python 3.5.2
- Sphinx version: sphinx-build 1.7.1

Thanks!

**Comment by jfbu** [comment]
Is it needed your source files are in `_static`? Testing with `foo.fs` file in `_extras/` sub-directory of config directory and ``html_extra_path = ['_extras']``, the file `foo.fs` is in `_build/html/` and not in `_build/html/_static/`.

(edited)

ah sorry I see now you said

> Users copy them into their _static directory, under _static/myextensionsassets.

which was clear enough...

**Comment by jfbu** [comment]
Why not then `_myextensionassets` rather than `_static/myextensionassets`? (and of course `html_extra_path = ['_myextensionassets']`

**Comment by cpitclaudel** [comment]
> Why not then _myextensionassets rather than _static/myextensionassets? (and of course html_extra_path = ['_myextensionassets']

The problem is that I don't want to pollute the website's root (so I want everything to be copied not to `build/html`, but to `build/html/somefolder/`.  You can do this currently by creating `dummyfolder/myextensionassets` and adding `html_extra_path = ['dummyfolder']`, but it's not great to have to explain that to users.

**Comment by picbox474** [comment]
Hi,... cognitive folder?

Le mar. 3 avr. 2018 14:59, Clément Pit-Claudel <notifications@github.com> a
écrit :

**Comment by tk0miya** [comment]
What did you mean "processing"? Scanning source files on `html_static_path`?
If so, I agree with you. I also feel the behavior is strange. I believe nobody wants to read source files from static directories.

**Comment by cpitclaudel** [comment]
> What did you mean "processing"? Scanning source files on html_static_path?

Right, exactly; converting to HTML.

**Comment by tk0miya** [comment]
Fixed by #4908.
Thank you for reporting!
