### ISSUE TITLE
logger warning points to dead link

### ISSUE THREAD

**Issue by ngoldbaum** [sphinx-doc/sphinx#4817]
The following code:

https://github.com/sphinx-doc/sphinx/blob/f26db5b2287b3c4fc12ce5649507440c6f2dc456/sphinx/writers/html.py#L877-L879

Points at http://sphinx-doc.org/ext/math.html, which is a dead link. I believe it's trying to link to http://sphinx-doc.org/en/master/ext/math.html (or similar), but that doesn't feel like a very canonical link. I'm not sure what the correct canonical link should be.

**Comment by tk0miya** [comment]
Absolutely! Thank you for letting us know :-)

**Comment by tk0miya** [comment]
Fixed by #4823.
Thank you for reporting!
