### ISSUE TITLE
Sphinx with breathe throws warnings when building.

### ISSUE THREAD

**Issue by rowanG077** [sphinx-doc/sphinx#4820]
Subject: Sphinx with breathe throws warnings when building.

### Problem
We use breathe to document our C++ projects and since upgrading to anything higher then version 1.7.0 there are errors for `doxygen` directives complaining about duplicate declarations.  I have manually walked through recent sphinx versions and this problem doesn't occur on 1.6.6 and 1.6.7 and is introduced in 1.7.0 and occurs in 1.7.1 and 1.7.2 as well.

#### Procedure to reproduce the problem
I have created a small example project which demonstrates the error with a struct.
It depends on breathe so it should be installed. Unpack the attached zip and with a console open in the unpacked directory run:

```
python -msphinx -c ./sphinx -b html ./rst ./sphinx/html
```

#### Error logs / results
I get duplicate declaration errors even though there obviously are none.

```
~/sphinx_breathe_warnings# python -msphinx -c ./sphinx -b html ./rst ./sphinx/html

Running Sphinx v1.7.2
loading translations [en]... done
making output directory...
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 3 source files that are out of date
updating environment: 3 added, 0 changed, 0 removed
reading sources... [100%] index
~/sphinx_breathe_warnings/rst/doxygenstruct.rst:4: WARNING: Duplicate declaration.
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index
generating indices... genindex
writing additional pages... search
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 1 warnings.

The HTML pages are in sphinx/html.
```

#### Expected results
I expect no errors.

### Reproducible project / your project
[sphinx_breathe_warnings.zip](https://github.com/sphinx-doc/sphinx/files/1887361/sphinx_breathe_warnings.zip)

### Environment info
- OS: Ubuntu. But reproduced with WSL and arch linux as well.
- Python version: 2.7 and confirmed with 3.6.4
- Sphinx version: >= 1.7.0
- Breathe 4.7.3

**Comment by tk0miya** [comment]
I got same warning with both 1.5.6, 1.6.7 and 1.7.1.
```
Running Sphinx v1.5.6
making output directory...
loading translations [en]... done
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 1 source files that are out of date
updating environment: 1 added, 0 changed, 0 removed
reading sources... [100%] index
Warning: Duplicate target detected: structnumber__pair

/docs/rst/index.rst:2: SEVERE: Duplicate ID: "structnumber__pair".
/docs/rst/index.rst:2: WARNING: Duplicate explicit target name: "structnumber__pair".
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index

generating indices... genindex
writing additional pages... search
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 2 warnings.
```
```
Running Sphinx v1.6.7
making output directory...
loading translations [en]... done
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 1 source files that are out of date
updating environment: 1 added, 0 changed, 0 removed
reading sources... [100%] index
Warning: Duplicate target detected: structnumber__pair

/docs/rst/index.rst:2: WARNING: Duplicate ID: "structnumber__pair".
/docs/rst/index.rst:2: WARNING: Duplicate explicit target name: "structnumber__pair".
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index

generating indices... genindex
writing additional pages... search
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 2 warnings.
```
```
Running Sphinx v1.7.1
loading translations [en]... done
making output directory...
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 1 source files that are out of date
updating environment: 1 added, 0 changed, 0 removed
reading sources... [100%] index
Warning: Duplicate target detected: structnumber__pair

/docs/rst/index.rst:2: WARNING: Duplicate ID: "structnumber__pair".
/docs/rst/index.rst:2: WARNING: Duplicate explicit target name: "structnumber__pair".
/docs/rst/index.rst:15: WARNING: Duplicate declaration.
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index

generating indices... genindex
writing additional pages... search
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 3 warnings.

The HTML pages are in sphinx/html.
```

It seems the warnings is not related with Sphinx-core.
In addition, I don't know about breathe at all. So I can't help you.
Could you report this to breathe project?

**Comment by tk0miya** [comment]
Note: my dockerfile for investigation
```
FROM tk0miya/sphinx-html

RUN apt install -y unzip
RUN curl -LO https://github.com/sphinx-doc/sphinx/files/1887304/sphinx_breathe_warnings.zip
RUN unzip sphinx_breathe_warnings.zip
RUN rm -rf sphinx/html
RUN pip3 install breathe
RUN pip3 install Sphinx==1.6.7
RUN python3 -msphinx -c ./sphinx -b html ./rst ./sphinx/html
```

**Comment by rowanG077** [comment]
Hmm I changed some things this morning to simplify the issue. But that has seemed to generate another issue. I will restore it to the original. See The updated attachment.

Because this is only occuring after 1.7.0 I don't believe it is a breathe issue.

**Comment by tk0miya** [comment]
Confirmed.
```
FROM tk0miya/sphinx-html

RUN apt install -y unzip
RUN curl -LO https://github.com/sphinx-doc/sphinx/files/1887361/sphinx_breathe_warnings.zip
RUN unzip sphinx_breathe_warnings.zip
RUN rm -rf sphinx/html
RUN pip3 install breathe
RUN python3 -msphinx -c ./sphinx -b html ./rst ./sphinx/html
```
```
Running Sphinx v1.7.1
loading translations [en]... done
making output directory...
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 3 source files that are out of date
updating environment: 3 added, 0 changed, 0 removed
reading sources... [ 33%] doxygenfile
reading sources... [ 66%] doxygenstruct
reading sources... [100%] index

/docs/rst/doxygenstruct.rst:4: WARNING: Duplicate declaration.
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [ 33%] doxygenfile
writing output... [ 66%] doxygenstruct
writing output... [100%] index

generating indices... genindex
writing additional pages... search
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 1 warnings.

The HTML pages are in sphinx/html.
```

Surely, this warning is only emitted with 1.7.

**Comment by tk0miya** [comment]
What I can do is only confirming a bug. I don't know what breathe extension (and doxygen) doing and how it working.

**Comment by rowanG077** [comment]
Found the issue. The same problem occurs when putting two C++ domain classes with the same name in two files. It seems sphinx can't handle the same domain object documented twice.

**Comment by jakobandersen** [comment]
Right, currently there has not been a good use-case for doing that, so for now I would say it works as intended. Documenting the same entity opens a lot of issues in how to handle cross-references (see also #2151), but if you have a good use-case it may be worth looking into a solution.

**Comment by rowanG077** [comment]
The use case that is used in breathe itself is that it creates a class multiple times. Because when you navigate to a namespace a list of classes is given without their methods. When you go to the actual class documentation the full definition with members is given. 

I think even without breathe it is a good use case to have a full set of documentation (for instance class + members functions and properties) somewhere and then you can still have short snippets in other parts. For instance when explaining how to use some API you have the class with a subset of the member function. Or only the member function itself. 

This is at least how I intended to use sphinx.

**Comment by jakobandersen** [comment]
That is indeed a nice way to structure it, but it is currently not possible to do in a pretty way. There must be one of the declarations which is the real one. The rest should in a sense be aliases. I will look into making a role and directive for this purpose. As the original problem is not really a bug I will close this and open another more fitting issue.
