### ISSUE TITLE
Setting the figure format requires setting all format types in numfig_format

### ISSUE THREAD

**Issue by misev** [sphinx-doc/sphinx#4828]
### Problem
Changing the 'figure' format with `numfig_format` requires listing all other formats as well, otherwise an exception will be thrown.

#### Procedure to reproduce the problem
In `conf.py` set `numfig_format={'figure': 'Figure %s'}`, then try to build a document which has some figures _and_ tables.

#### Error logs / results
```
Exception occurred:
  File "/usr/lib/python2.7/dist-packages/sphinx/writers/html.py", line 279, in append_fignumber
    self.body.append(prefix % numsstr + ' ')
TypeError: not all arguments converted during string formatting
The full traceback has been saved in /tmp/sphinx-err-PjF2Qy.log, if you want to report the issue to the developers.
```

#### Workaround
Specify all formats:
```
numfig_format = {'figure': 'Figure %s', 'table': 'Table %s',
                 'code-block': 'Listing %s', 'section': 'Section %s'}
```

### Environment info
- OS: Ubuntu 16.04
- Python version: 2.7.12
- Sphinx version: 1.7.2

**Comment by tk0miya** [comment]
Fixed by #4842.
Thank you for proposal!
