### ISSUE TITLE
URL-Redirection on the Sphinx website doesn't work anymore

### ISSUE THREAD

**Issue by mgeier** [sphinx-doc/sphinx#4829]
For at least several years in the past links of this style have worked:

    http://www.sphinx-doc.org/ext/autodoc.html

They were automatically forwarded to

    http://www.sphinx-doc.org/en/stable/ext/autodoc.html

Since the "stable" branch has been dropped recently, this doesn't work anymore, leading to a page saying "This page does not exist yet."

I think this can be simply solved by adding a [prefix redirect](https://docs.readthedocs.io/en/latest/user-defined-redirects.html#prefix-redirects) with an *empty* "from URL" field.

Related issue (but not the same!): #4744

**Comment by mgeier** [comment]
Ping?

**Comment by mgeier** [comment]
Any news on this? It still doesn't seem to work ...

This should be a really quick fix, just a few clicks!

**Comment by tk0miya** [comment]
We decided to disable the redirection to resolve #4778.
Unfortunately, we can't help your case.

**Comment by tk0miya** [comment]
I'm closing this now.
Sorry for breaking links.

**Comment by mgeier** [comment]
I have just tried it again, and now the forwarding seems to work again (using `master` instead of `stable`)!
