### ISSUE TITLE
LaTeX output forces same formatting of :menuselection: and :guilabel:

### ISSUE THREAD

**Issue by tesch1** [sphinx-doc/sphinx#4830]
Subject: LaTeX output forces same formatting of :menuselection: and :guilabel:

### Problem
- I'm documenting a project that has menus and buttons.  I have used :menuselection: to refer to menu items, and :guilabel: to refer to buttons.  I want the generated LaTeX to look different for these two different things.

- The LaTeX writer outputs both roles as \sphinxmenuselection{}, here: https://github.com/sphinx-doc/sphinx/blob/master/sphinx/writers/latex.py#L2516  

#### Expected results
- either add a \sphinxguilabel{}, or use the parameterized DUrole that can be overridden in the local style?

**Comment by tk0miya** [comment]
+1; reasonable.

**Comment by jfbu** [comment]
This got fixed at https://github.com/sphinx-doc/sphinx/commit/cb4da734125a24177320d92cfc1f80361800d727 (#4868). Closing.
