### ISSUE TITLE
sphinx-build in python3 TypeError: 'Mock' object is not iterable

### ISSUE THREAD

**Issue by kodexp** [sphinx-doc/sphinx#4835]
Subject: sphinx-build in python3 TypeError: 'Mock' object is not iterable

$ make html
Running Sphinx v1.7.2

Exception occurred:
  File "<frozen importlib._bootstrap_external>", line 1123, in _get_spec
TypeError: 'Mock' object is not iterable
The full traceback has been saved in /local/ha3/fxz547/tmp/sphinx-err-v3da7q70.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [html] Error 2

**Comment by tk0miya** [comment]
We can't resolve your trouble because this report does not have enough information.
Please fill questions of our issue template.

>The full traceback has been saved in /local/ha3/fxz547/tmp/sphinx-err-v3da7q70.log, if you want to report the issue to the developers.

In next time, please attach this full traceback.
Thanks,
