### ISSUE TITLE
Sphinx search not working, failed to load searchindex.js

### ISSUE THREAD

**Issue by bluprince13** [sphinx-doc/sphinx#4851]
#### Procedure to reproduce the problem
Opening index.html and searching for anything

#### Error logs / results
```
Failed to load file:/searchindex.js: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
```
```
Uncaught TypeError: Cannot read property 'length' of undefined
    at displayNextItem (searchtools.js:543)
    at Object.query (searchtools.js:574)
    at Object.setIndex (searchtools.js:362)
    at searchindex.js:1
```

#### Expected results
A search that works

### Environment info
- OS: Win
- Python version: 2.7
- Sphinx version: 1.6.3

**Comment by tk0miya** [comment]
Search feature of Sphinx is implemented as JavaScript. AFAIK, it can't work on local files. Please view it through HTTP server.
Thanks,

**Comment by bluprince13** [comment]
Search does work on local files. 

I didn't figure out exactly what was causing the error, but I just resolved it. I used sphinx-quickstart to create a new repo, and then I copied over the brand new makefiles and config.py into my faulty repo. It now works fine :)

**Comment by psifertex** [comment]
I've got this issue happening as well. Local search worked fine on 1.4.5, I upgraded to 1.8.1 and made a few small `conf.py` changes (enabling parallel was the main reason I upgraded) and now search is broken again. :-/

**Comment by psifertex** [comment]
nevermind, looks like my problem is #5460
