### ISSUE TITLE
DOI for sphinx, preferred citation method

### ISSUE THREAD

**Issue by bsipocz** [sphinx-doc/sphinx#4852]
I wonder whether there is a way to formally cite Sphinx, is there a preferred way? Is there a DOI for it somewhere?

**Comment by tk0miya** [comment]
Did you read our message on issue template?

>  Important: This is a list of issues for Sphinx, not a forum.
>  If you'd like to post a question, please move to sphinx-users group.
>  https://groups.google.com/forum/#!forum/sphinx-users

Or you meant this is bug of Sphinx?

**Comment by bsipocz** [comment]
Yes, I read it and posted the issue nevertheless as it's a question to the developers rather than what other users could answer.
(the missing `CITATION` file may be seen an issue for the repo)

**Comment by tk0miya** [comment]
As I mentioned above, this is not a forum. So I'd not like to answer the question.
Please post this to the group.

Thanks,

**Comment by AA-Turner** [comment]
A DOI now exists: https://doi.org/10.5281/zenodo.7857310
