### ISSUE TITLE
Option list not working with ":"

### ISSUE THREAD

**Issue by dvorapa** [sphinx-doc/sphinx#4858]
Subject: On Pywikibot Project command-line parameters containing ":" are not formatted as reST option list

### Problem
- Our command-line parameters look like "-parameter:value". But this is not recognized in reST option list (`-parameter:value  The value of the parameter parameter is...`) and therefore also Sphinx because of the ":" character. Is there a way to add this as some exception into Sphinx or reST?

#### Procedure to reproduce the problem
```
docs>-parameter value  The value of the parameter parameter is...
works
docs>-parameter:value  The value of the parameter parameter is...
doesn't work
```

#### Expected results
There should be some exception to allow also this format

### Reproducible project / your project
- See https://doc.wikimedia.org/pywikibot/scripts/scripts.html or try by yourself in https://livesphinx.herokuapp.com/

### Environment info
- OS: Debian Linux
- Python version:3.4-3.6.5
- Sphinx version:1.7.2
- autodoc, apidoc, rstcheck, epytext, numpydoc or napoleon, alabaster

**Comment by dvorapa** [comment]
Asked in reST maillist

**Comment by tk0miya** [comment]
Note: This is discussion on the list.
https://sourceforge.net/p/docutils/mailman/message/36296385/

**Comment by tk0miya** [comment]
I'm closing this now because this is not an issue of Sphinx itself.
Thank you for reporting.

**Comment by dvorapa** [comment]
@tk0miya Sure, could you just have a newbie question?
What is the library responsible for building HTML from `-parameter:value  desc` reST lines like this? This library should not break option list, because what if it would be `-param:eter  desc`? I am really confused, I'm a little bit lost in those.

**Comment by tk0miya** [comment]
docutils is. It is used for reST parser of Sphinx.

If it would not support `-parameter:value desc` style options, you can enhance it by making an extension. Directive is one of the way to enhance syntax from extensions.

**Comment by dvorapa** [comment]
Finally asked on https://sourceforge.net/p/docutils/feature-requests/59/, hopefully this will be handled by an upstream
