### ISSUE TITLE
An option to copy .htaccess files?

### ISSUE THREAD

**Issue by cpitclaudel** [sphinx-doc/sphinx#4859]
### Problem

The HTML builder excludes all dotted files:

https://github.com/sphinx-doc/sphinx/blob/c35eb6fade7a3b4a6de4183d1dd4196f04a5edaf/sphinx/builders/html.py#L822

As a consequence, `.htaccess` files are not copied to `_build/html/_static`

#### Expected results

I'd like to be able to tell Sphinx to copy all files, including the ones that start with a `.`. In my project I use a `.htaccess` to set server-side compression options (`AddOutputFilterByType DEFLATE application/javascript`).

### Environment info
- OS: Linux _ 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Python version: Python 3.5.2
- Sphinx version: sphinx-build 1.7.1

**Comment by tk0miya** [comment]
For security reason, Sphinx ignores dotfiles on `html_static_path`. If you want to copy them, please add each file to `html_static_path`:
```
html_static_path = ['_static', '_static/.htaccess']
```

Another way is to use `html_extra_path`. Sphinx copies dotfiles on the directories intentionaly.

**Comment by cpitclaudel** [comment]
> `html_static_path = ['_static', '_static/.htaccess']`

Great, thanks a lot!
