### ISSUE TITLE
html_favicon warning when icon is in html_static_path

### ISSUE THREAD

**Issue by tymonpitts** [sphinx-doc/sphinx#4860]
Subject: html_favicon warning when icon is in html_static_path

### Problem

I'm trying to setup html_static_path to contain my html_favicon but since the favicon is not relative to my configuration directory I get the following warning:

```
    copying static files... WARNING: favicon file 'default_favicon.ico' does not exist
```

The resulting html actually works just fine though and has the favicon, however, I like to enable -W for all of my projects so that my team cannot just ignore warnings. This warning fails my sphinx builds even though it is a benign warning.

I found the following pull request which seems to be responsible for this behavior: https://bitbucket.org/birkenfeld/sphinx/pull-requests/211/fix-for-issue-1352/diff

It looks like a simple fix would be to first check if ``icontarget`` exists, and then do the other checks in an elif afterwards.

#### Procedure to reproduce the problem
```
> cd <repo root dir>
> sphinx-build -b html -W sphinx_project build
```

#### Error logs / results
```
Running Sphinx v1.6.5
loading pickled environment... done
building [mo]: all of 0 po files
building [html]: all source files
updating environment: 0 added, 0 changed, 0 removed
looking for now-outdated files... none found
preparing documents... done
writing output... [100%] contents                                                                                                                                         
generating indices... genindex
writing additional pages... search
copying static files... 
Warning, treated as error:
favicon file 'default_favicon.ico' does not exist
```

#### Expected results
I expect the build to succeed without warnings/errors since the favicon does exist in the html_static_path already. Running without -W still prints the warning but the favicon works as expected.

### Reproducible project / your project

https://github.com/tymonpitts/sphinx_html_favicon_issue_repro

### Environment info
- OS: Ubuntu 16.04.3 LTS
- Python version: 2.7.6
- Sphinx version: 1.6.5

**Comment by tk0miya** [comment]
-1; As described in document, `html_favicon` is a relative path from confdir, not `html_static_path`

**Comment by dimpase** [comment]
Does this mean that `suppress_warnings` facility just cannot be used to suppress this warning? In our project (sagemath) we just [scrape the log to suppress this warning](https://github.com/dimpase/sage/blob/e2dcdeeabb578c37bcf0361c0be3079315e9252c/src/sage_setup/docbuild/sphinxbuild.py#L107) - but this breaks down with non-English locale, as we [found out](https://trac.sagemath.org/ticket/30002)

**Comment by tk0miya** [comment]
What happened in sagemath project? AFAIK, the warning is raised by the wrong configuration. So what you should do for the warning is fixing the configuration, I believe. Why have you suppressed it? Anyway, your comment is not related to this issue.

I think there are nothing to do for this issue. Closing.

**Comment by dimpase** [comment]
Hi Dima,

Thank you for explanation in detail. I understand what is happening in
your project.
I think the warning came from something wrong implementation of the
custom builder.
So there is nothing to do from Sphinx side. But please let me know if
there is something I can help you.

Thanks,
Takeshi KOMIYA

2020年6月29日(月) 18:30 Dima Pasechnik <dimpase+github@gmail.com>:
>
> Dear Takeshi KOMIYA,
>
> Thank you for the comment (also put your email in CC, as I probably
> can't comment on closed issues).
>
> > What happened in sagemath project? AFAIK, the warning is raised by the wrong configuration. So what you should do for the warning is fixing the configuration, I believe. Why have you suppressed it?
>
> we have a heavily customised sphinx configuration, that was set up
> years ago to e.g. make sure to the global index is created correctly,
> and parallelisation was possible (as building docs was becoming the
> bottleneck). Here is an overview if you're interested.
> https://trac.sagemath.org/ticket/20080
>
> In particular there is a 2-stage build, where in the 1st run only
> sphinx inventories are created. While that favocon warning was just a
> caused by some outdated bits, more serions issue is that we still get
> bogus cross-doc citation warnings (with Sphinx 3.0.4) that were
> supposed to be done with by #3874.
>
> And out static files configuration is a mess, due to that custom
> 2-stage process.
>
>

**Comment by dimpase** [comment]
Hi,

I would like to know whether nowadays Sphinx has standard means to
parallelize builds. The primary reason for the non-standard setup we have
is speed, so that most of the work on modules of the library can be done in
parallel.

Thanks,
Dima

**Comment by tk0miya** [comment]
At present, the `-j` option is the only way to build documents parallel. I guess it does not help your project. I need to know what are bottlenecks on sagemath project. I'd like to check it later (if I have time).

Please file a new issue please?

**Comment by dimpase** [comment]
On Mon, 29 Jun 2020, 16:28 Takeshi KOMIYA, <notifications@github.com> wrote:

> At present, the -j option is the only way to build documents parallel. I
> guess it does not help your project. I need to know what are bottlenecks on
> sagemath project. I'd like to check it later (if I have time).
>
> Please file a new issue please?
>
I've opened https://github.com/sphinx-doc/sphinx/issues/7891 - hopefully it
is useful.
