### ISSUE TITLE
Section headings not translating correctly

### ISSUE THREAD

**Issue by joelanders** [sphinx-doc/sphinx#4863]
Hi, I posted [this](https://groups.google.com/forum/#!topic/sphinx-users/hdzuCi7AvRY) on the sphinx-users mailing list a couple days ago and haven't got a response, so apologies for the duplicate. Also, I'm not sure if this is a sphinx issue or a sphinx-intl issue. Since that post, I've been working around this issue by putting a non-breaking space before the numbers so the headings don't get interpreted as numbered headings.
(Repeating what I wrote on the list below.)

I just reproduced my issue on top of the sample project that `sphinx-quickstart` generates to be sure I'm not messing it up in another way.

I added the following lines to `index.rst`:
```
1. A Header
-----------
A paragraph.
```

Then I did a `make gettext` to generate the `.pot` file.

Then I did a `sphinx-intl update -l ru` to generate the `.po` file.

Then I edited the Russian `index.po` file like this:
```
#: ../../index.rst:23
msgid "1. A Header"
msgstr "1. a header in russian"

#: ../../index.rst:24
msgid "A paragraph."
msgstr "a paragraph in russian"
```

Finally I did a `make -e SPHINXOPTS="-D language='ru'" html` to build the HTML, which ends up looking like:
```
1. A Header
a paragraph in russian
```

That is, the paragraph text gets translated but the section header/title does not.
(I just tried this with an un-numbered header, and that works correctly.)
Am I missing something? I think I'll try to learn how `rst`'s `sectnum` works in the meantime.
[ed.: I couldn't get this to work with autonumbering either.]

Thanks in advance!
-Joe

**Comment by shimizukawa** [comment]
Thanks for your reporting!
I've overlooked this issue and I created another one #4938 about same problem.
#4938 has been fixed by #4939 and that will be shipped as sphinx-1.7.5.

Now I close this issue.
Please feel free to reopen if you still have problem related this issue. 
Thanks.
