### ISSUE TITLE
Documentation of inheritance_diagram extension does not reflect actual behavior

### ISSUE THREAD

**Issue by goerz** [sphinx-doc/sphinx#4872]
The [documentation of `sphinx.ext.inheritance_diagram`](http://www.sphinx-doc.org/en/master/ext/inheritance.html#directive-inheritance-diagram) states

    This directive supports an option called ``parts`` that, if given, must be an
    integer, advising the directive to remove that many parts of module names
    from the displayed names.  (For example, if all your class names start with
    ``lib.``, you can give ``:parts: 1`` to remove that prefix from the displayed
    node names.)

However, this is not the actual behavior of the code! Due to https://github.com/sphinx-doc/sphinx/blob/96c5605374135652cf7ec0ad517b532b9261ef19/sphinx/ext/inheritance_diagram.py#L234
`parts` specifies the number of parts that are kept (right-to-left), not the number of parts that are dropped (left-to-right). In principle, the documented behavior would be achieved with negative values for `parts`, except that this is prevented by
https://github.com/sphinx-doc/sphinx/blob/96c5605374135652cf7ec0ad517b532b9261ef19/sphinx/ext/inheritance_diagram.py#L333-L338

One would have to change line 334 to `'parts': int,`.

So, I could imagine four possible solutions, which I'll outline below (in order of least to most effort), so people can vote on them:

**Comment by goerz** [comment]
### Solution 1

Change the documentation to describe the actual behavior. Dropping `parts` number of parts from the left would be impossible (as it is now).

**Comment by goerz** [comment]
### Solution 2

Change the documentation, but also allow negative values for `parts` as an undocumented feature.

**Comment by goerz** [comment]
### Solution 3

Change the documentation, but also allow negative values for `parts` as a *documented* feature.

The drawback is that the negative values are a bit of a dirty trick that really don't make sense unless one is looking at the implementation. It would be hard to explain in any understandable way in the documentation.

**Comment by goerz** [comment]
### Solution 4

Keep the documentation, and change

    result = '.'.join(name_parts[-parts:]) 

 to

    result = '.'.join(name_parts[parts:]) 
    
while also allowing both positive and negative values for `parts`. If one were to write the `inheritance_diagram` extension from scratch, I think this would be the cleanest solution.

However it has the *major* drawback that it breaks backwards compatiblity. I would imagine that most users of the extension are currently using `:parts: 1` to only show class names without any parts. Everybody would have to change their RST code to `:parts: -1` to get the same behavior.

**Comment by goerz** [comment]
@birkenfeld and @tk0miya, what do you think?

**Comment by tk0miya** [comment]
Good point!

The behavior of `parts` which you reported was started since beginning of the extension (c5d0ba9913).
Therefore, there might be many documents using this feature.

Personally, I prefer "Solution 4". But we can't choose it because of backward compatibility.
So I think "Solution 3" is better.

**Comment by goerz** [comment]
Yeah, I agree completely.

I'll leave this open for a while to give more people a chance to comment, and then at some point when I have some free time I'll prepare a pull request.

**Comment by tk0miya** [comment]
ping. any updates?

**Comment by goerz** [comment]
Thanks for the reminder.. I'll have some free time in a few weeks. I put it on the calendar for then!

**Comment by tk0miya** [comment]
We'll release 2.0 soon (maybe next weekend or the following weekend). It would be nice if we can change this until then.

**Comment by goerz** [comment]
Do we still want to do "Solution 3"?
