### ISSUE TITLE
[docs] sphinx-doc.org sidebar boundaries

### ISSUE THREAD

**Issue by svenevs** [sphinx-doc/sphinx#4873]
Subject: sidebar boundaries are not correct (?)

### Problem

See [the table here](http://www.sphinx-doc.org/en/master/extdev/index.html#deprecated-apis), attached is a screenshot.

![sphinx_html_boundaries](https://user-images.githubusercontent.com/5871461/39068339-d38806d4-4490-11e8-858d-6a6bda11bbee.jpeg)

You can see that the table rules are bleeding over into the sidebar.

#### Procedure to reproduce the problem

N/A

#### Error logs / results

N/A

#### Expected results

The horizontal rules from the table end before the sidebar.

I tried playing around with [`_themes/sphinx13/layout.html`](https://github.com/sphinx-doc/sphinx/blob/master/doc/_themes/sphinx13/layout.html), but couldn't figure out a fix (I don't know Jinja / html / css very well).

But I feel like there's a way to end the table by putting things inside another `<div>` or something?

**Comment by tk0miya** [comment]
Fixed at #4884.
Thank you for reporting.
