### ISSUE TITLE
Question: automodule documentation fails on methods wrapped by a decorator (python 2.7)

### ISSUE THREAD

**Issue by mathieu-xy082** [sphinx-doc/sphinx#4898]
Subject: <Sphinx doc is not generated for decorated methods !??>

My use case is as follows, I have a decorated method `compute_something`.
It turns out that the decorator disable Sphinx auto documentation ...

```python
@validate(argument)
def compute_something(param1, param2):
    """

    Compute something

    Parameters
    ----------
    param1 : type
        Description of parameter `param1`.
    param2 : type
        Description of parameter `param2`.

    Returns
    -------
    type
        Description of returned object.

    """
    # do many things 

    return
```

the .rst file used by Sphinx is as follows

```
.. automodule:: compute_things
    :members:
    :undoc-members:
    :show-inheritance:
```

Sphinx generates no doc for this function when I add the decorator
`@validate(argument)` whereas it works well without the decorator

Is there any work around ?

### Environment info
- OS: Linux Ubuntu 16.04
- Python version: 2.7.12
- Sphinx version: 1.7.0

**Comment by tk0miya** [comment]
Do you use `functools.wraps()` for the decorator?
https://docs.python.org/3.6/library/functools.html#functools.wraps

**Comment by mathieu-xy082** [comment]
Thanks for your answer, it worked perfectly !
