### ISSUE TITLE
Make latexpdf fails on windows

### ISSUE THREAD

**Issue by dm413** [sphinx-doc/sphinx#4911]
Subject: Make latexpdf fails with "Failed to run: make"

### Problem
- When running on windows, if you run "make latexpdf", sphinx-build generates the latex files, but then fails with the message "Failed to run: make". 
- After sphinx-build fails, if I manually run "latexpdf ProjectName.tex" from the _build/latex folder, it correctly runs Miktex and builds the pdf file.
- It appears that build-spinx does not create a make.bat file in the _build/latex folder. It does create a makefile, but that won't run on windows (no make command/executable).
- This problem can be reproduced by running quickstart with all the defaults to create a minimal project, and then running "make latexpdf".

#### Procedure to reproduce the problem
```
sphinx-quickstart                     (accept all the defaults)
make latexpdf
```

#### Error logs / results
```
F:\SphinxTest3>make latexpdf
Running Sphinx v1.7.4
making output directory...
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [latex]: all documents
updating environment: 1 added, 0 changed, 0 removed
reading sources... [100%] index
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
processing SphinxTest3.tex...index
resolving references...
writing... done
copying TeX support files...
done
build succeeded.

The LaTeX files are in _build\latex.
Error: Failed to run: make
```

#### Expected results
sphinx-build should create a make.bat in the _build/latex folder and execute it.

### Environment info
- OS: Windows 7-64
- Python version: 2.7.12
- Sphinx version:  1.7.4

**Comment by t-b** [comment]
@dm413 Yeep same here. I've also tested sphinx 1.5.4 and it does not work in that neither. So maybe it was never working?

**Comment by dm413** [comment]
Thanks for confirming. It worked at one time, because I discovered the problem after I updated sphinx. Unfortunately I don't have good notes about what version I was running.

**Comment by Sow-Hunter** [comment]
same problem.

**Environment info**
- OS: Windows 7-64
- Python version: 2.7.15
- Sphinx version: 1.7.5

**Comment by fleimgruber** [comment]
Same problem.

**Environment info**

- OS: Windows 7-64
- Python: 3.6.5
- Sphinx: 1.7.5

How to debug?

**Comment by tk0miya** [comment]
At present, Sphinx does not provide make.bat script for windows environment. So you need to install `make.exe` to build PDF. In detail, please see #1867.

**Comment by dm413** [comment]
Sphinx does provide a make.bat script. Sphinx-quickstart asks if you want to create one, and the default answer (at least on windows) is yes. The make.bat works for html, but does not work for pdf.

Furthermore, this used to work. I have projects I generated with an older version of sphinx (not sure what version, but it was 2016), that generated a much larger make.bat than does the current version. This make.bat does include the pdflatex command and successfully creates a pdf file.

**Comment by jfbu** [comment]
You might be looking for [`--no-use-make-mode`](http://www.sphinx-doc.org/en/1.7/man/sphinx-quickstart.html#cmdoption-sphinx-quickstart-use-make-mode) option of `sphinx-quickstart`.

**Comment by fleimgruber** [comment]
@tk0miya thanks, installing `make.exe` solved it.

**Comment by dm413** [comment]
The `--no-use-make-mode` option to `sphinx-quickstart` does not solve the problem. In the resulting generated project, running `make.bat  latexpdf` still produces "Error: Failed to run: make". 

Make-mode is an option to move some of the functionality of make into Sphinx itself. It does not affect the problem here, which is that the generated make.bat file tries to run make.exe instead of running the command `latexpdf ProjectName.tex`.

Running make.bat to build other output types works, it is just building pdf that fails.

**Comment by tk0miya** [comment]
>Sphinx does provide a make.bat script. Sphinx-quickstart asks if you want to create one, and the default answer (at least on windows) is yes. The make.bat works for html, but does not work for pdf.

Sorry for confuse. The `make.bat` I mentioned is different with which `sphinx-quickstart` generates. `sphinx-build` generates additional make script for building PDF on output directory (cf. `_build/latex/Makefile`). But `sphinx-build` does not generate batch file at present.

>Furthermore, this used to work. I have projects I generated with an older version of sphinx (not sure what version, but it was 2016), that generated a much larger make.bat than does the current version. This make.bat does include the pdflatex command and successfully creates a pdf file.

So far, `sphinx-quickstart` has never generated `make.bat` which calls `latexpdf` directly, AFAIK. Is it really generated by Sphinx?


Anyway, we need to generate an additional `make.bat` on `make latex`. I'll try it on next release.
Thanks,

**Comment by jfbu** [comment]
>  the problem here, which is that the generated make.bat file tries to run make.exe instead of running the command latexpdf ProjectName.tex.

Just for the record,  the command would be `pdflatex`  not `latexpdf` which is nickname adopted by Sphinx for make target. On GNU/Linux, the natural thing to do after `make latex` is  `make -C <latexbuilddir> all-pdf` and for some reason Sphinx proposes `make latexpdf` instead (related: #5085). For Windows, one sees at  https://github.com/sphinx-doc/sphinx/blob/148b47168cf59ea6cdfd9ffc3ad4ee4b92b5f982/sphinx/templates/quickstart/make.bat_t#L77-L85
that the "old" make.bat will indeed as you report try to execute `make all-pdf` in the latex build directory.

**Comment by dm413** [comment]
I tested with version 1.8.0. Running
`    make latexpdf`
give the error message
`    latexmk: The script engine could not be found.
    latexmk: Data: scriptEngine="perl.exe", scriptName="latexmk"
`

Although latexmk is installed with MiKTeX, it requires perl to be installed as well. This is a new dependency for Sphinx as far as I know.

I note another minor issue -- if you run `make` with no parameters, it lists the possible targets, but does not list `latexpdf` as one of those possible targets.

**Comment by tk0miya** [comment]
@dm413 Thank you for confirmation. I'd forgotten to add `latexmk` to new dependency (because it had been already used in other platforms).
And I also added help entry (you can see it if you re-generate make.bat).

see #5451 .
Thanks,

**Comment by panda-z** [comment]
Hello, 
I've noticed that sphinx use make.bat.new_t as template when invoking sphinx-quickstart. The latexpdf help entry is still missing.
