### ISSUE TITLE
Styline codeblocks and 

### ISSUE THREAD

**Issue by cmhughes** [sphinx-doc/sphinx#4917]
I'd like to start by thanking the team for `sphinx`, I find it a really helpful tool.

Is there a way to style `codeblocks` and `literalinclude` on a per-instance basis? For example, given the following

```
.. literalinclude:: myfile
 	:caption: ``fileExtensionPreference`` 
 	:name: lst:fileExtensionPreference
```
is there a way to append this with something that would, for example, change the background colour for certain instances? Perhaps something like:

```
.. literalinclude:: myfile
 	:caption: ``fileExtensionPreference`` 
 	:name: lst:fileExtensionPreference
        :style:mystyle
```
Similarly, for codeblocks, is there a way to style codeblocks such as the following?
```
::

    mycommand goes here
          
```
Note that I'd like to be able to do this for certain instances of `literalinclude` and `::`, not on a global basis.

**Comment by tk0miya** [comment]
Did you read our notice on issue template? It seems this is a question...

>  Important: This is a list of issues for Sphinx, not a forum.
>  If you'd like to post a question, please move to sphinx-users group.
>  https://groups.google.com/forum/#!forum/sphinx-users
