### ISSUE TITLE
dev: node.asdom() crush if node has secnumber with tuple value

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#4919]
### Problem
- toctree directive with `:numbered:` generate unexpected attribute value for docutils

This code expects `list` type if attribute value of node has sequence.
https://github.com/docutils-mirror/docutils/blob/e88c5fb08d5cdfa8b4ac1020dd6f7177778d5990/docutils/nodes.py#L490-L492

#### Procedure to reproduce the problem
1. make toctree with `:numbered:` and it have some rst pages (ex. `sub.rst`). Sections in the pages will be numbered.
2. `sub.rst` have a section and a subsection that will be numbered as `1.1`
3. do `node.asdom()` after the `env-get-updated` internal event.

#### Error logs / results
- https://travis-ci.org/sphinx-doc/sphinx/jobs/372925222#L2000

#### Expected results
- no error

### Reproducible project / your project
- [asdom-with-secnum.zip](https://github.com/sphinx-doc/sphinx/files/1960175/asdom-with-secnum.zip)

### Environment info
- OS: any (reproduced with ubuntu, windows)
- Python version: 3.6
- Sphinx version: 1.8+

### After fixing this issue:
correct workaround on bellow code.
https://github.com/sphinx-doc/sphinx/blob/fce6d0d7d7e8a53d2cfd78c9e82a0455f8d02da0/sphinx/util/logging.py#L120-L121

**Comment by tk0miya** [comment]
Merged. #4998.
Please do your afterwork.

**Comment by shimizukawa** [comment]
WIP

**Comment by shimizukawa** [comment]
Thanks!
