### ISSUE TITLE
sphinx-apidoc needs more options

### ISSUE THREAD

**Issue by kotoroshinoto** [sphinx-doc/sphinx#4920]
There is currently no way to have it automatically add flags like :special-members: , :inherited-members:, etc. 

(basically anything relevant that is added to autodoc that might be relevant to api docs ought to have a corresponding flag in this tool)

**Comment by mwatts15** [comment]
Recommend closing this: there's already `apidoc_options`

**Comment by tk0miya** [comment]
Indeed. We can specify these options via the environment variable `SPHINX_APIDOC_OPTIONS`.
https://www.sphinx-doc.org/en/master/man/sphinx-apidoc.html#envvar-SPHINX_APIDOC_OPTIONS

Closing.
