### ISSUE TITLE
Multi-line copyright notice

### ISSUE THREAD

**Issue by ghost** [sphinx-doc/sphinx#4925]
### Problem
- Sphinx cannot generate multi-line copyright notice in the HTML output

### How to reproduce
Assuming we want to display:
:copyright: Copyright 2017, A
:copyright: Copyright 2018, B

It seems impossible to display these lines under each other. The best behavior can be achieved using:
```py
copyright = u'2017, A, \xA9 Copyright 2018, B'
```
which outputs: :copyright: Copyright 2017, A, :copyright: Copyright 2018, B
but this is hacky and still renders in the same line!

### Expected behaviour
Either to allow `copyright` variable being a list:
```py
copyright = [u'2017, A', u'2018, B']
```
which should generate the two lines properly

Or at least to allow HTML embedding:
```py
copyright = u'2017, A<br />&copy; Copyright 2018, B'
```
which still hacky anyway!

**Comment by tk0miya** [comment]
+0: I can accept if anybody send a PR for this to us.

As a workaround, you can customize the footer manually. Please put a following file onto your project as named `_templates/layout.html`:
```
{%- block footer %}
    <div class="footer" role="contentinfo">
    &#169; Copyright Copyright 2017, A.<br />
    &#169; Copyright Copyright 2018, B.
    {%- if last_updated %}
      {% trans last_updated=last_updated|e %}Last updated on {{ last_updated }}.{% endtrans %}
    {%- endif %}
    {%- if show_sphinx %}
      {% trans sphinx_version=sphinx_version|e %}Created using <a href="http://sphinx-doc.org/">Sphinx</a> {{ sphinx_version }}.{% endtrans %}
    {%- endif %}
    </div>
{%- endblock %}
```

(I just used `<br />` to fold the line after first copyright. But you can use other tags as you like).
