### ISSUE TITLE
Search result links are broken (extra ".rst" in URL)

### ISSUE THREAD

**Issue by mikelandry** [sphinx-doc/sphinx#4929]
Subject: Search result links are broken because there is an extra ".rst" in the URL

### Problem
After upgrading from 1.3.1 to 1.7.4 the links are broken on Search Result pages.

The links are broken because the URL has an extra ".rst" in the file extension. For example:

`overview.rst.html?highlight=token`

should actually be

`overview.html?highlight=token`

#### Procedure to reproduce the problem
There is no specific procedure. This is a usability issue in the final build. Our users have been unable to use search since March.

#### Error logs / results
See it here: https://apidocs.apperian.com/production/search.html?q=token&check_keywords=yes&area=default

#### Expected results
Search result links should take user to a new page.

### Environment info
- OS: Linux
- Python version:
- Sphinx version: 1.7.4
- classic theme

**Comment by tk0miya** [comment]
Since 1.5, new variable `SOURCELINK_SUFFIX` is added for searching JavaScript.
But your custom theme does not support it.

Could you update your theme like following?
```
     <script type="text/javascript">
       var DOCUMENTATION_OPTIONS = {
         URL_ROOT:    '{{ url_root }}',
         VERSION:     '{{ release|e }}',
         COLLAPSE_INDEX: false,
         FILE_SUFFIX: '{{ '' if no_search_suffix else file_suffix }}',
         HAS_SOURCE:  {{ has_source|lower }},
+        SOURCELINK_SUFFIX: '{{ sourcelink_suffix }}'
       };
     </script>
```

**Comment by tk0miya** [comment]
I'm closing this now because it seems this is not a bug.
Thanks,
