### ISSUE TITLE
Failed to extract content when class docstring is exactly the same as class name

### ISSUE THREAD

**Issue by killa1218** [sphinx-doc/sphinx#4930]
Subject: Failed to extract content when class docstring is exactly the same as class name

### Problem
When the docstring of one class is the same as class name, sphinx will not extract it in html files.
For example:
``` python
class MyClass(object):
  '''MyClass'''
  pass
```
The docstring "MyClass" will be ignored. Is this a bug or deliberately designed?

### Environment info
- OS: Win 10
- Python version: 3.6.5
- Sphinx version: 1.5.5 and 1.7.4

**Comment by tk0miya** [comment]
Yes, it is intended behavior. It is called as `autodoc_docstring_signature`, and it is enabled by default.
http://www.sphinx-doc.org/en/master/ext/autodoc.html#confval-autodoc_docstring_signature

With this feature, the first line is considered as a signature of the class if matched.

**Comment by killa1218** [comment]
Thanks @tk0miya for your answer. But I still have one confusion: As `autodoc_docstring_signature` is designed for functions and methods, why it will effect on class?

**Comment by tk0miya** [comment]
In case of class definition, the signature is used for its constructor.

**Comment by killa1218** [comment]
Thanks a lot. Will close this issue.
