### ISSUE TITLE
build fails with napoleon enabled: Null object is not iterable

### ISSUE THREAD

**Issue by mwichmann** [sphinx-doc/sphinx#4931]
### Problem
Experimenting with converting [scons](https://github.com/SCons/scons) to generate API docs using Sphinx instead of Epydoc. During this, someone asked if could turn on display of class members starting with underscores. Experimenting with this by enabling napoleon extension and adding the two flag settings as described in http://www.sphinx-doc.org/en/master/ext/example_google.html

napoleon_include_special_with_doc = True
napoleon_include_private_with_doc = True

and the build blew up. I backed off the two flags, and the build still blew up.  Since the error message requested filing an issue on this, I am doing so.  I don't have a "simple reproducer", my simple example using the extension works fine.  Removing the line for the napoleon extension allows the build to complete.

#### Error Results
```
$ make html
Running Sphinx v1.5.6
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 13 source files that are out of date
updating environment: 13 added, 0 changed, 0 removed
reading sources... [ 38%] SCons.Script                                          
Exception occurred:
  File "/usr/lib/python3.6/site-packages/sphinx/ext/napoleon/__init__.py", line 421, in _skip_member
    cls_path, _, _ = qualname.rpartition('.')
TypeError: 'Null' object is not iterable
The full traceback has been saved in /tmp/sphinx-err-qxul9qji.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [Makefile:20: html] Error 1
```

#### Error log
[sphinx-err-qxul9qji.log](https://github.com/sphinx-doc/sphinx/files/1967804/sphinx-err-qxul9qji.log)

### Environment info
- OS: Fedora 26
- Sphinx version: 1.5.6
- Python version: 3.6.5 (CPython)
- Docutils version: 0.13.1 release
- Jinja2 version: 2.9.6

**Comment by tk0miya** [comment]
>Sphinx version: 1.5.6

The latest version is 1.7.4. I don't know this problem is fixed or not. But 1.5.6 is no longer supported. Please try it again with latest version.
Thanks,

**Comment by mwichmann** [comment]
Okay, in a virtualenv, the information now is:

- Sphinx version: 1.7.4
- Python version: 3.6.5 (CPython)
- Docutils version: 0.14 
- Jinja2 version: 2.10

The error is the same, however (new line number :)) -

Exception occurred:
  File "/home/mats/virtualenv/numpydoc3/lib/python3.6/site-packages/sphinx/ext/napoleon/__init__.py", line 431, in _skip_member
    cls_path, _, _ = qualname.rpartition('.')
TypeError: 'Null' object is not iterable

**Comment by tk0miya** [comment]
Thank you for confirmation. This must be a bug.

**Comment by mwichmann** [comment]
So it seems we use a funky object **SCons.Util.Null** which trips the effort to pick a usable **\_\_qualname\_\_** out of the object. This is in fact stolen (err, shared) at some time in the mists of time from the Python Cookbook, as noted by http://aspn.activestate.com/ASPN/Cookbook/Python/Recipe/68205 (ASPN: Python Cookbook: Null Object Design Pattern).  Since this is described as "reliably always does nothing", getting the **\_\_qualname\_\_** attribute does work, but it returns itself, which when passed on to the rpartition method leads to the error posted above - not iterable.

    DEBUG: type of qualname is <class 'str'>   # normal
    DEBUG: type of qualname is <class 'SCons.Util.Null'>  # about to break

It's possible just skipping in this case is okay... here's what my debuggy version did - just catching the case where rpartition gets unhappy:

            elif sys.version_info >= (3, 3):
                qualname = getattr(obj, '__qualname__', '')
                try:
                    cls_path, _, _ = qualname.rpartition('.')
                except TypeError:
                    print("DEBUG: qualname null for object ", type(obj))
                    cls_path = None
                if cls_path:

**Comment by tk0miya** [comment]
I think `__qualname__` is one of common attributes of python objects. autodoc and napoleon expect the target module obeys the standards.
refs: https://docs.python.org/3.6/reference/datamodel.html

So I don't think napoleon should handle the error. On the other hand, sphinx-core should not be crashed on the error inside extension. Therefore I prefer to handle the error on sphinx-core side and warn about it.

**Comment by ederag** [comment]
The same issue happened when mocking pyQt5, for classes using `pyqtSignal`:
```
class _GScene(QGraphicsScene):
	"""The graphical class corresponding to :class:`.Scene`."""
	
	signal_set_all_selected = pyqtSignal(bool)
```
Here is a minimal working example:
https://github.com/ederag/bug-sphinx-mock/tree/pyqtSignal

The build passes with the fix #4997. But obviously it still fails when the `-W` option is used.

**Comment by tk0miya** [comment]
@ederag just updated my PR. It will resolve your case.

**Comment by ederag** [comment]
Either in python 3.4.6 or 3.6.4, it fails with
`iter() returned non-iterator of type 'list'`

Changing `return []` with return `return iter(())`
fails too:
`not enough values to unpack (expected 3, got 0)`

**Comment by tk0miya** [comment]
Oh, sorry. My patch was wrong. Could you try it again please?

**Comment by ederag** [comment]
It works now, both for the minimal example and the complete geoptics project. Congratulations !

**Comment by tk0miya** [comment]
@ederag Thank you for confirmation!
I just merged.

@mwichmann 
Thank you for reporting!
Please wait for next release :-)
