### ISSUE TITLE
Show warnings even if files are not modified

### ISSUE THREAD

**Issue by techtonik** [sphinx-doc/sphinx#4937]
Subject: Sphinx forgets warnings in files

### Problem
Sphinx prints warnings only when it reads files for the first time. If files are not modified, no warning are shown.

#### Procedure to reproduce the problem
```
$ make html
$ make html
```
Run `make html` on a docs with warnings twice and you won't see any warning on the second run. So the only way to show warnings again is to use `-E`, which repeats processing and triggers write of all documentation files to disk.

#### Expected results
Warning should be cached and shown every time even if file is unmodified unless visibility options prevent warnings. If `-n` (nit-picky) is in effect, cached it too. If `-a` (write anyway) is supplied, file is unmodified and cached warning is different from new warning, show some error.

### Environment info
- Sphinx version: 1.7.4

**Comment by tk0miya** [comment]
Thank you for reporting. Duplicated with #725.
Thanks,

**Comment by techtonik** [comment]
Oh, I missed that one. Thanks!
