### ISSUE TITLE
cannot concatenate 'str' and 'list' objects when doing build using sphinx 1.1.3

### ISSUE THREAD

**Issue by nareshg4** [sphinx-doc/sphinx#4957]
Subject: cannot concatenate 'str' and 'list' objects when doing build using sphinx

Hi Team,

We are running a jenkins job to do a build using sphinx version 1.1.3.
while running we are encountering the following issue.

Running Sphinx v1.1.3
loading pickled environment... not yet created

Exception occurred:
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/sphinx/util/__init__.py", line 85, in get_matching_docs
    suffixpattern = '*' + suffix
TypeError: cannot concatenate 'str' and 'list' objects

  Thanks,
Naresh.G

### Problem
We were able to build usin sphinx using an older version of jenkins 1.609 on a different server.
Later we installed jenkins v2.60.1 on a new server and are encountering the above issue while running the job.
Job configuration remains the same in both the servers. unfortunately we have decommissioned the old instance.

#### Procedure to reproduce the problem
```
sphinx-build -b html modules /XXXX/XXXX/jenkins/apache-tomcat-8.0.30/webapps/docs/wlsfk/
```

#### Error logs / results
```
Jenkins Artifactory Plugin version: 2.12.1
[Jenkins_CommitStage] $ /bin/sh -xe  /XXXX/XXXX/jenkins/apache-tomcat-8.0.30/temp/jenkins8611964102338670981.sh
+ APACHE_WEBAPPS_FOLDER= /XXXX/XXXX/jenkins/apache-tomcat-8.0.30/webapps
+ mkdir -p  /XXXX/XXXX/jenkins/apache-tomcat-8.0.30/webapps/docs/wlsfk/
+ rm -rf ' /XXXX/XXXX/jenkins/apache-tomcat-8.0.30/webapps/docs/wlsfk/*'
+ cd wlst
+ pwd
 /XXXX/XXXX/jenkins/workspace/WLSFK_CommitStage/wlst
+ sphinx-build -b html modules /XXXX/XXXX/jenkins/apache-tomcat-8.0.30/webapps/docs/wlsfk/
Running Sphinx v1.1.3
loading pickled environment... not yet created

Exception occurred:
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/sphinx/util/__init__.py", line 85, in get_matching_docs
    suffixpattern = '*' + suffix
TypeError: cannot concatenate 'str' and 'list' objects
The full traceback has been saved in /tmp/sphinx-err-cU8A_d.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
Either send bugs to the mailing list at <http://groups.google.com/group/sphinx-dev/>,
or report them in the tracker at <http://bitbucket.org/birkenfeld/sphinx/issues/>. Thanks!
Build step 'Execute shell' marked build as failure
Recording fingerprints
Sending e-mails to: 
Finished: FAILURE
#### Expected results
To generate WebLogic Framework documentation

### Environment info
- OS: Linux
- Python version:2.7
- Sphinx version:1.1.3

**Comment by tk0miya** [comment]
I guess you have given a list to `source_suffix`. But it had been supported since v1.3.

In addition, v1.1.3 is too old. It is not supported now. Please update to latest one.

Thanks,

**Comment by tk0miya** [comment]
I'm closing this now because 1.1.3 is not supported at present.
Thanks,
