### ISSUE TITLE
space in inline :math:

### ISSUE THREAD

**Issue by aszekMosek** [sphinx-doc/sphinx#4968]
When inline math starts with a space, such as:
```
:math:` a=b`
```
then it is not recognized and gets rendered literally as the text ":math:\` a=b\`" in both HTML and LaTeX. It would be nice if there at least was a warning. In 99.9% of cases the user actually meant "a=b".

When it ends with a space then at least there is a warning "Inline interpreted text or phrase reference start-string without end-string."

I used Sphinx 1.7.2

The same applies to ``:code:``. And maybe others.

**Comment by tk0miya** [comment]
Please read reST spec. it says:

>1. Inline markup start-strings must be immediately followed by non-whitespace.
>2. Inline markup end-strings must be immediately preceded by non-whitespace.
>http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#inline-markup

If you want to use whitespace to the start (or the end) of string, please escape it by backslash.
```
:math:`\ a=b`
```

Thanks,

**Comment by aszekMosek** [comment]
Thanks! Too bad it is not enforced though, leading to potential silent fails. I close.
