### ISSUE TITLE
Split some builders and extensions to external package

### ISSUE THREAD

**Issue by tk0miya** [sphinx-doc/sphinx#4971]
### Problem
- As discussed in #4484, split some builders and extensions to external packages.

**Comment by tk0miya** [comment]
This is my proposal:

* builders
    * [x] applehelp
    * [x] devhelp
    * [x] json
    * [x] htmlhelp
    * [x] pickle
    * [x] qthelp
* extensions
    * [x] jsmath

**Comment by shimizukawa** [comment]
+1 for your proposal.

**Comment by tk0miya** [comment]
I feel `sphinx.ext.coverage` is one of candidate. I've never used it, so I can't say it should be bundled or not. But I would not be able to maintain it...

**Comment by tk0miya** [comment]
Note: htmlhelp (chm) was now deprecated. So it's time to split package from core.

* [Deprecated: .chm Help files | Microsoft Docs](https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/deprecated-chm-help-files)
* [Ask HN: What is the current stable help generation system for Windows? | Hacker News](https://news.ycombinator.com/item?id=9426878)
* [Microsoft Compiled HTML Help - Wikipedia](https://en.wikipedia.org/wiki/Microsoft_Compiled_HTML_Help)

**Comment by tk0miya** [comment]
I just made a repository for jsmath!
https://github.com/sphinx-doc/sphinxcontrib-jsmath

**Comment by tk0miya** [comment]
Finally, I separated packages which I proposed!
