### ISSUE TITLE
Explicit labels on code blocks are duplicated in LaTeX output

### ISSUE THREAD

**Issue by cpitclaudel** [sphinx-doc/sphinx#4980]
### Problem

The following snippet causes laTeX to complain about multiply-defined labels:

```rst
.. _test:

.. code:: python

   pass
```

This is low-priority, because using a proper `:name:` annotation works fine:

```
.. code:: python
   :name: test

   pass
```

(But it's still an issue when one wants to place an anchor before a list of multiple code samples.)

#### Error logs / results
```
Latexmk: List of undefined refs and citations:
  Label `index:test' multiply defined
Latexmk: Summary of warnings:
  Latex found 1 multiply defined reference(s)
```

### Environment info
- OS: GNU/Linux
- Python version: 3.5.2
- Sphinx version: 1.7.4

**Comment by tk0miya** [comment]
Fixed by #4982.
Thank you for reporting!
