### ISSUE TITLE
C++, add role/directive for rendering aliases of declarations.

### ISSUE THREAD

**Issue by jakobandersen** [sphinx-doc/sphinx#4981]
See #4820.
For making a synopsis of some part of the documentation it would be nice to be able to insert a (shortened?) rendering of declarations. There could be both a role for making an inline rendering and a directive where multiple lines are allowed.

**Comment by rowanG077** [comment]
Sounds good to me. An idea that would be great as well is that if a declaration is an alias that it will automatically be a cross reference to the "real" declaration. It might be the easiest to include an `alias` option that renders the declaration, references the "real" declaration and isn't picked up by sphinx as a duplicate.

Also is this really only applicable for C++?
