### ISSUE TITLE
Misleading signature for env-merge-info

### ISSUE THREAD

**Issue by anntzer** [sphinx-doc/sphinx#5018]
Subject: env-merge-info is documented as having a signature of (env, docnames, other) though it's actually (app, env, docnames, other)

### Problem
See title & http://www.sphinx-doc.org/en/master/extdev/appapi.html#event-env-merge-info

#### Procedure to reproduce the problem
Examine sphinx.ext.todo.merge_info (for instance) and observe that the app is indeed passed as first argument.

Note that the problem likely also affects env-check-consistency (http://www.sphinx-doc.org/en/master/extdev/appapi.html#event-env-check-consistency), which likewise does not document app as first argument (unlike all other events), but I haven't checked whether the first argument is indeed app.

### Environment info
- OS: Arch Linux
- Python version: 3.6
- Sphinx version: 1.7.4

**Comment by tk0miya** [comment]
You're right. Both are given an `app` object as a first argument.
I'll fix our docs on #5020 

Thanks,

**Comment by tk0miya** [comment]
Fixed by #5020.
Thank you for reporting :-)
