### ISSUE TITLE
Does numref works with any self-defined anchor?

### ISSUE THREAD

**Issue by tonyriverms** [sphinx-doc/sphinx#5027]
I would like numref to work for any anchor besides images, tables, equations, etc. For example, like, 

```
.. _my-anchor-1:

Some content here...

.. _my-anchor-2:

Some content here...

:numref:`Definition %s <my-anchor-1>`

:numref:`Definition %s <my-anchor-2>`
```

I would like to numbering to be automatic for the same text like "Definition %s", "Example %s". Does numref currently support similar functionality? What is the right way to do so?

**Comment by tk0miya** [comment]
`:numref:` role is available for enumerable objects. In Sphinx, anchors are not enumerable.

**Comment by tonyriverms** [comment]
Thanks. My question was not clearly. I would like the "numref" to work with any title I use, for example. I am not sure if this is supported at this moment.

```
:numref:`Definition %s <my-anchor-1>` : some content a here. 

:numref:`Definition %s <my-anchor-2>` : some content b here.
```

Then the output gives 

```
Definition 1-1 : some content a here.
Definition 1-2 : some content b here.
```

Can we do this?

**Comment by tk0miya** [comment]
As I commented above, `:numref:` is available only for enumerable objects. So you have to make them enumerable before using `:numref:`.
You can make specific nodes enumerable using `add_enumerable_node()` API:

This is an example to make paragraph node enumerable.
```
def setup(app):
    from docutils import nodes
    app.add_enumerable_node(nodes.paragraph, figtype='paragraph')
    app.config.numfig_format['paragraph'] = '%s'
```

Then you can use `:numref:` for labeled paragraphs.

Note: This only assigns numbers internally. So paragraph numbers are not shown on output. To show them, you also need to customize writers. In detail, please read our docs and source codes.

**Comment by tk0miya** [comment]
I'm closing this now because this is not a bug or feature request of Sphinx.
Please feel free to reopen if you still in trouble.
Thanks,

**Comment by paternal** [comment]
Shameless self promotion: @tonyriverms, if you want to define (and reference) definitions, theorems, examples, and so on, I wrote such an extension: [sphinxcontrib-proof](http://framagit.org/spalax/sphinxcontrib-proof).
