### ISSUE TITLE
Extension error: Could not import extension sphinx.builders.latex (exception: No module named 'docutils.writers.latex2e')

### ISSUE THREAD

**Issue by handavidbang** [sphinx-doc/sphinx#5033]
Subject: <Extension error when trying to use make html>

### Problem
- <I just got started with Sphinx and after typing in the following command in Linux Terminal ```make html``` I got the following error. 

```Extension error:
Could not import extension sphinx.builders.latex (exception: No module named 'docutils.writers.latex2e')
make: *** [html] Error 1
```
I've been struggling for several hours and modified the **conf.py** file to no avail. 
>

#### Procedure to reproduce the problem
```
<make html>
```

#### Error logs / results
```
<Extension error:
Could not import extension sphinx.builders.latex (exception: No module named 'docutils.writers.latex2e')
make: *** [html] Error 1>
```
- <public link of unexpected result if you have>

#### Expected results
<It would make a directory called html with several files>

### Reproducible project / your project
- <link to your project, or attach zipped small project sample>

### Environment info
- OS: <Unix/Linux/Mac/Win/other with version>
- Python version:
- Sphinx version:
- <Extra tools e.g.: Browser, tex or something else>

**Comment by tk0miya** [comment]
It seems your docutils library has broken. How did you install it? Please install (or update) it again.
Thanks,

**Comment by jfbu** [comment]
Closing as this [appears to have been solved](https://stackoverflow.com/questions/50648220/sphinx-how-to-download-extensions) by OP via reinstalling docutils.
