### ISSUE TITLE
qthelp_namespace doesn't allow dashes

### ISSUE THREAD

**Issue by NomAnor** [sphinx-doc/sphinx#5035]
When setting the qthelp_namespace variable to a reverse URL with a dash the dash is removed. For example Qt uses ``org.qt-project.qtbluetooth.5110`` as Namespace which would not be possible with the qthelp Builder because it would be changed to ``org.qtproject.qtbluetooth.5110``.

I think namespaces should at least allow a reverse URL.

This code in ``sphinx.builders.qthelp`` tries to clean the namespace:

    nspace = re.sub('[^a-zA-Z0-9.]', '', nspace)
    nspace = re.sub(r'\.+', '.', nspace).strip('.')
    nspace = nspace.lower()

**Comment by tk0miya** [comment]
Do you know the spec of namespace for qthelp?
I'd like to know what character is allowed for it.

**Comment by NomAnor** [comment]
I tried to find it but the documentation for the file format is very sparse.

**Comment by NomAnor** [comment]
I think I found the code in qt5/qttools/src/assistant/help/qhelpprojectdata.cpp

    } else if (name() == QLatin1String("namespace")) {
                    namespaceName = readElementText();
                    if (!hasValidSyntax(namespaceName, QLatin1String("test")))
                        raiseError(QCoreApplication::translate("QHelpProject",
                                       "Namespace \"%1\" has invalid syntax in file: \"%2\"").arg(namespaceName, fileName));

and then:

    bool QHelpProjectDataPrivate::hasValidSyntax(const QString &nameSpace,
                                                 const QString &vFolder) const
    {
        const QLatin1Char slash('/');
        if (nameSpace.contains(slash) || vFolder.contains(slash))
            return false;
        QUrl url;
        const QLatin1String scheme("qthelp");
        url.setScheme(scheme);
        const QString &canonicalNamespace = nameSpace.toLower();
        url.setHost(canonicalNamespace);
        url.setPath(slash + vFolder);

        const QString expectedUrl(scheme + QLatin1String("://")
            + canonicalNamespace + slash + vFolder);
        return url.isValid() && url.toString() == expectedUrl;
    }

So it looks like a valid namespace is the host part of an URL.

I think the plugin should not change the string in any way. If a user uses an invalid string the qt tools will tell them.

**Comment by tk0miya** [comment]
Thank you for comment. Good point!

**Comment by tk0miya** [comment]
I just made #5097. I simply added hyphens to our rule.

**Comment by tk0miya** [comment]
Fixed by #5097.
Thank you for reporting
