### ISSUE TITLE
Typing Control-U in sphinx-quickstart clears the line

### ISSUE THREAD

**Issue by asmeurer** [sphinx-doc/sphinx#5036]
To reproduce, start `sphinx-quickstart test`, start typing something for the first answer, and press `Control-U`. The entire question line is cleared, rather than just what was typed.

### Environment info
- OS: Mac
- Python version: 3.5
- Sphinx version: 1.7.4

**Comment by tk0miya** [comment]
This might be come from the fix for #3364. We have to use `input()` to protect prompt.

**Comment by asmeurer** [comment]
Maybe you just needed to wrap your ANSI escapes with `\[` and `\]`.

**Comment by tk0miya** [comment]
What did you mean? Wrapping all escape sequences with `\[` and `\]`?
I'm not good at console manipulation. Please let me know your idea.

Thanks,

**Comment by asmeurer** [comment]
Actually it needs to be `\1` and `\2`. Like `\1ESCAPECODE\2`. Those are `\[` and `\]` in bash but not in Python. Those tell readline that the ANSI codes are zero-width (invisible). It's hard to find good docs on this, but it's mentioned at https://tiswww.case.edu/php/chet/readline/readline.html

**Comment by tk0miya** [comment]
Fixed by #5059.
Thank you for reporting.
