### ISSUE TITLE
New warnings with multiple `Sphinx` instances

### ISSUE THREAD

**Issue by larsoner** [sphinx-doc/sphinx#5038]
### Problem

Sphinx 1.8 dev emits a warning when instantiating multiple Sphinx instances, which makes previously-passing warning-checking code (sphinx-gallery) fail.

### Procedure to reproduce the problem

```
import os
from sphinx.application import Sphinx
import tempfile
from io import StringIO


with tempfile.TemporaryDirectory() as dir_:
    srcdir = os.path.join(dir_, 'src')
    os.mkdir(srcdir)
    with open(os.path.join(srcdir, "conf.py"), "w") as conffile:
        conffile.write('')

    app = Sphinx(srcdir, srcdir, os.path.join(srcdir, "_build"),
                 os.path.join(srcdir, "_build", "toctree"),
                 "html", warning=StringIO())
    build_warn = app._warning.getvalue()
    assert build_warn == '', build_warn

    app2 = Sphinx(srcdir, srcdir, os.path.join(srcdir, "_build"),
                  os.path.join(srcdir, "_build", "toctree"),
                  "html", warning=StringIO())
    build_warn2 = app2._warning.getvalue()
    assert build_warn2 == '', build_warn2
```

### Error logs / results

```
Running Sphinx v1.8.0+
making output directory...
Running Sphinx v1.8.0+
Traceback (most recent call last):
  File "minimal.py", line 23, in <module>
    assert build_warn2 == '', build_warn2
AssertionError: WARNING: while setting up extension sphinx.domains.math: role 'eq' is already registered, it will be overridden
```

### Expected results
On 1.7.x this code passes (no warning).

### Reproducible project / your project

https://github.com/sphinx-gallery/sphinx-gallery/pull/385

### Environment info

Linux / Travis, Python 3.

If it's not obvious to maintainers what the cause/solution is, I can try bisecting.

**Comment by tk0miya** [comment]
Sphinx itself and its extensions register directives and roles to docutils core. That is global change.
As a result, they are conflicted when invoking Sphinx twice or more.

Please use `sphinx.util.docutils:docutils_namespace()` to create a namespace for docutils on each invoking:
```
from sphinx.util.docutils import docutils_namespace

with docutils_namespace():
    app = Sphinx(...)
```

**Comment by tk0miya** [comment]
Note:
`sphinx.util.docutils.patch_docutils()` is also used to patch docutils temporarily. So I'd like to propose you to use it also. (added since 1.6)

**Comment by larsoner** [comment]
The context manager works, thanks. I'll look into `patch_docutils` if needed.
