### ISSUE TITLE
pass a file in command line

### ISSUE THREAD

**Issue by jacgeo** [sphinx-doc/sphinx#5041]
I Introduced  a module for generating rst file from a json file and import that module in conf.py. Currently I hard coded the file path, but I want to pass the file_name in command line argument like ('sphinx-build -b html source build file_name'). How to pass the file_name in command line with sphinx-build.

**Comment by tk0miya** [comment]
How about using environment variable?

**Comment by jacgeo** [comment]
can you share a sample example for that?
Currently is there any extension for that?

**Comment by tk0miya** [comment]
It's python's technique. Not sphinx issue.
```
import os

path = os.environ['PATH']  # read $PATH envvar
```

Note:
This is not a forum for sphinx. If you want to discuss about way to develop extensions, please post to sphinx-dev list: 
https://groups.google.com/forum/#!forum/sphinx-dev

**Comment by jacgeo** [comment]
Suppose we pass file name in command line 'sphinx-build -b html source build filename' and get the path using sys.argv[5] and convert into multiple rst files. Then sphinx processing only index.rst other rst files was ignored.
