### ISSUE TITLE
:numref: fallback to :ref: in case of "no number is assigned for section ..."

### ISSUE THREAD

**Issue by Dutchtallman** [sphinx-doc/sphinx#5042]
### Problem

A big tree of reST documents is converted to HTML documents using sphinx. That tree has many section levels, but only numbers them down to level 4. All lower level sections do not get numbers. Some branches in the tree (for example covering section levels 3 to 5 in the big tree) are also converted to latexpdf to be used as separate documents. 

In those branches that will be converted to latexpdf, I use :numref:`reference` a lot. However, when converting the big tree to html, I get an error:

    /directory/file.rst:12: WARNING: no number is assigned for section: reference

Which is a logic warning, because there is no section number for sections below level 4, there is nothing to refer to. This error is displayed after:

    writing output... [100%] 

appears in the console. 

### Not working mitigation using the only directive

I first tried to circumvent this warning by using the `only` directive, as in:

    .. only:: latex
 
       paragraph using :numref:`reference to another paragraph` and some text

    .. only:: html
 
       paragraph using :ref:`reference to another paragraph` and some text

But this does not work, as the `only` directive does not function as a conditional when parsing the input rst-files, see https://github.com/sphinx-doc/sphinx/issues/2150

### Suggestion to make :numref: smarter

It is suggested to make :numref: smarter. Use the section number if there is a section number and fall back to :ref: behaviour when there is no section number, perhaps with an extra switch in the conf.py file to allow this behaviour.

Perhaps, this feature could be combined with https://github.com/sphinx-doc/sphinx/issues/3209

**Comment by tk0miya** [comment]
-1: I think `:numref:` and `:ref:` are different semantic. So it should not be fallback automatically.
