### ISSUE TITLE
Anyway to specify "numbered" title depth?

### ISSUE THREAD

**Issue by tonyriverms** [sphinx-doc/sphinx#5047]
If I add ``:numbered:`` to toctree, then every title in the whole documentation is numbered. Anyway to specify like "numbered" up to a certain level? like number H1, H2, H3 titles but not H4, H5, ...?

**Comment by barbara-sfx** [comment]
Docs say: Numbering up to a specific depth is also possible, by giving the depth as a numeric argument to numbered.

http://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html

**Comment by tk0miya** [comment]
Right. The `toctree` directive takes an integer value as depth.

**Comment by tk0miya** [comment]
It seems this is not a bug of Sphinx. So I'm closing this now.
Thanks,

**Comment by zhaoweiguo** [comment]
Still do not know how to use it
If i wanted to use h1,h2,h3 not h4,h5...
I tried
```
.. toctree::
   :numbered: 3
   :maxdepth: 2

   registers/personal
```

```
.. toctree::
   :numbered:
   :depth: 3
   :maxdepth: 2

   registers/personal
```

I wanted to use this feature, but when the level is over 5, It will display like `1.2.3.4.5.6.7` which seems ugly

**Comment by zhaoweiguo** [comment]
Reason found.
https://github.com/sphinx-doc/sphinx/pull/5050
https://github.com/buildbot/buildbot/commit/4daad50751aad97a8d41fa455c1c65753d99060e
