### ISSUE TITLE
External Hyperlink returns 403 Client Error: FORBIDDEN for url error

### ISSUE THREAD

**Issue by askb** [sphinx-doc/sphinx#5051]
### Problem
We seem to be hitting the following 403 Client Error: FORBIDDEN when using with linkcheck for the below code sample trying to refer to an external hyperlink, (https://wiki.debian.org/MeetBot)

With curl this is not reproducable. 
```
$ curl -I -X HEAD -H "accept-encoding: identity" -A 'Mozilla/5.0 (X11; Linux x86_64; rv:25.0) Gecko/20100101 Firefox/25.0' --url https://wiki.debian.org/MeetBot
HTTP/1.1 200 OK
Date: Thu, 07 Jun 2018 01:24:49 GMT
Server: Apache
X-Content-Type-Options: nosniff
X-Frame-Options: sameorigin
Referrer-Policy: no-referrer
X-Xss-Protection: 1
Strict-Transport-Security: max-age=15552000
Public-Key-Pins: pin-sha256="yPqY/77C2aLVJIEAYtuMrFy+cX6g4CatH03gcBQbxpo="; pin-sha256="TzmD7DK6d5d7RU66/XTJtlENSfv+i0P7x2Xmpl8uFrY="; max-age=5184000
Vary: Cookie,User-Agent,Accept-Language,Accept-Encoding
X-Clacks-Overhead: GNU Terry Pratchett
Content-Type: text/html; charset=utf-8
```
Is this a known issue?

#### Procedure to reproduce the problem
code:
```
`Meetbot <http://wiki.debian.org/MeetBot>`_
```

#### Error logs / results
```
Warning, treated as error:
/w/workspace/lf-infra-docs-tox-verify-any/docs/infra/meetbot.rst.rst:7:broken link: https://wiki.debian.org/MeetBot (403 Client Error: FORBIDDEN for url: https://wiki.debian.org/MeetBot)

ERROR: InvocationError: /w/workspace/lf-infra-docs-tox-verify-any/.tox/docs-linkcheck/bin/sphinx-build -W -b linkcheck -d /w/workspace/lf-infra-docs-tox-verify-any/.tox/docs-linkcheck/tmp/doctrees ./docs/ /w/workspace/lf-infra-docs-tox-verify-any/docs/_build/linkcheck (see /w/workspace/lf-infra-docs-tox-verify-any/.tox/docs-linkcheck/log/docs-linkcheck-2.log)
coala runtests: PYTHONHASHSEED='3644858330'

```
- https://logs.opendaylight.org/releng/vex-yul-odl-jenkins-1/lf-infra-docs-tox-verify-any/324/console.log.gz

#### Expected results
embed a target URI inline in "Meetbot"

### Reproducible project / your project
- https://gerrit.linuxfoundation.org/infra/#/c/11088/

### Environment info
- OS: Linux, CentOS 7
- Python version: python 2.7.x
- Sphinx version: v1.7.5

**Comment by tk0miya** [comment]
I can't reproduce it on my local.

>OS: Linux, CentOS 7
>Python version: python 2.7.x

Could you check your python version in detail? If it is older than 2.7.9, please update to latest one. It does not support SNI (Server Name Indication). So it is not good to use HTTPS.

**Comment by askb** [comment]
The version that gets pulled in is 2.7.5 with tox, will test with anything > 2.7.9 and update here.

**Comment by askb** [comment]
As a workaround used linkcheck ignore.

```
from docs_conf.conf import *

intersphinx_mapping['ansible'] = ('https://docs.ansible.com/ansible/latest/', None)

linkcheck_ignore = [
    'https://wiki.debian.org/MeetBot',  # SNI link needs Python 2.7.9+
]
 
```

**Comment by tk0miya** [comment]
Are you still in trouble? If not, I'd like to close this. Please let me know your situation.
Thanks,

**Comment by askb** [comment]
@tk0miya we have a workaround which is good, but is this a known issue or something which needs to be fixed?

**Comment by tk0miya** [comment]
This is a well known issue of python interpreter, not sphinx's.
https://www.python.org/downloads/release/python-279/

The resolution for this is only updating python itself.

**Comment by tk0miya** [comment]
I'm closing this because this is not an issue of Sphinx.
Thanks,
