### ISSUE TITLE
KeyError on 'literal_block' in new Latex transform

### ISSUE THREAD

**Issue by jakobandersen** [sphinx-doc/sphinx#5064]
Subject: KeyError on ``literal_block`` in new Latex transform

### Problem
The new Latex math transform added in 489d86d47094155c4334851a03abddfb25fc215a assumes all ``docutils.nodes.container`` has the ``literal_block`` attribute, but extensions (e.g., Breathe)  add containers as well without that attribute. Is the visitor matching the right node type?

#### Procedure to reproduce the problem
[sphinx-literal_block.zip](https://github.com/sphinx-doc/sphinx/files/2086935/sphinx-literal_block.zip)
Run ``make latex``.

**Comment by tk0miya** [comment]
Thank you for letting me know. I just posted #5065 to fix this.

**Comment by jakobandersen** [comment]
Thanks! That should do it.

**Comment by tk0miya** [comment]
Just merged. Thank you for reporting :-)
