### ISSUE TITLE
Wrong internal href fragment links in epub output

### ISSUE THREAD

**Issue by claudep** [sphinx-doc/sphinx#5070]
Let's take for example the Django settings documentation (https://docs.djangoproject.com/en/2.0/ref/settings).

In the HTML output, a text like ```:setting:`STATICFILES_FINDERS` ``` is translated to `<a class="reference internal" href="#std:setting-STATICFILES_FINDERS">` and the anchor is indeed matching that link.

In epub output, the link is `<a class="reference internal" href="#std-setting-STA     TICFILES_FINDERS">`, while the anchor is still `<span id="std:setting-STATICFILES_FINDERS">` (like for HTML). Therefore, the link doesn't work, because of the `-`/`:` mismatch in the link name.

**Comment by tk0miya** [comment]
Note: The `setting` role is a role which added by djangodoc using `app.add_crossref_type()`.
https://github.com/django/django/blob/860903b261517442098bdf14e44f4fd4ae20aeb9/docs/_ext/djangodocs.py#L25-L29

**Comment by tk0miya** [comment]
In EPUB builder, targets having colon in its name are forcely renamed (see e06a11bd644328ac36fc760c485922de6c9c3826).
It seems this bug comes from this `fix_ids()` processing...

**Comment by tk0miya** [comment]
Fixed by #5107.
Thank you for reporting.

**Comment by claudep** [comment]
Awesome! Thanks for fixing this quickly!

**Comment by carltongibson** [comment]
Hi @tk0miya (Hi @claudep) 

Sorry to dig up an old issue, but it looks like we're still seeing this issue with the Django epub output, using `Sphinx==2.2.0`. 

We're seeing the the `-/:` mismatch in the link name, some 2700 times. We've manually dug down at the DjangoCon sprints and have found ourselves back here. 

We think the fix here went into v1.7, over a year ago (Is that right?) but it seems not to have quite resolved our case. 

Tracking this in https://code.djangoproject.com/ticket/20935

Copying a fragment here for info: 

> Re the two-thousand-odd Fragment identifier is not defined. errors, I think those should be (cough) straight-forward enough to fix.
> 
> The issue is in cross links:
> 
> genindex.xhtml:979 has:
> 
> ```
>         <li><a href="ref/templates/builtins.xhtml#std-templatefilter-addslashes">template filter</a>
> ```
> 
> But the destination is ref/templates/builtins.xhtml:1220, which has:
> 
> ```
> <span id="std:templatefilter-addslashes">...
> ```
> `std:templatefilter-addslashes` is not `std-templatefilter-addslashes`. 

Any thoughts on how we might get this right? Thanks!

**Comment by tk0miya** [comment]
@carltongibson Thank you for letting us know. I made a PR #6734  for the bug. Could you try this please?
