### ISSUE TITLE
Test failures(s) when .tox is a symlink

### ISSUE THREAD

**Issue by blueyed** [sphinx-doc/sphinx#5071]
### Problem

If the `.tox` directory is a symlink `tests/test_build_html.py::test_html_warnings` fails, because the location of the first warning differs.

It uses the path with the symlink in the "Expected" part, but for some reason (only) the first warning gets the resolved path in the actual output:

```
E         --- Expected (regex):
E         …/Vcs/sphinx/.tox/py36/testbuild/warnings/autodoc_fodder.py:docstring of autodoc_fodder.MarkupError:: WARNING: Explicit markup ends without a blank line; unexpected unindent.
E         …/Vcs/sphinx/.tox/py36/testbuild/warnings/index.rst:: WARNING: Encoding 'utf-8-sig' used for reading included file '…/Vcs/sphinx/.tox/py36/testbuild/warnings/wrongenc.inc' seems to be wrong, try giving an :encoding: option
E         --- Got:
E         /tmp/tox…/Vcs/sphinx/py36/testbuild/warnings/autodoc_fodder.py:docstring of autodoc_fodder.MarkupError:: WARNING: Explicit markup ends without a blank line; unexpected unindent.
E         …/Vcs/sphinx/.tox/py36/testbuild/warnings/index.rst:: WARNING: Encoding 'utf-8-sig' used for reading included file '…/Vcs/sphinx/.tox/py36/testbuild/warnings/wrongenc.inc' seems to be wrong, try giving an :encoding: option
```

#### Procedure to reproduce the problem

```
# Run tox to ensure `.tox` exists - this passes.
% tox -e py36 -- tests/test_build_html.py::test_html_warnings
% mv .tox /tmp/tox
% ln -s /tmp/tox .tox
# Run tox through the symlink.
% tox -e py36 -- tests/test_build_html.py::test_html_warnings
```

I've only investigated into this failure, but there are likely others caused by
this.

I am using a wrapper around `tox` to create its dirs in `/tmp` for performance
(and automatic cleanup) mostly, which then triggered this.

### Environment info
- OS: Linux (Arch)
- Python version: 3.6.5
- Sphinx version: 1.8.0+/3aa686e68

**Comment by tk0miya** [comment]
How about using `tox -e py27 --workdir /tmp/tox` instead? Then you'll get succeeded.

**Comment by jfbu** [comment]
@tk0miya I tried `tox -e py36 --workdir /tmp/tox` but it fails at my locale (mac os x) because some output ends up in `/private/tmp/tox/py36/...` for the "warnings" test (html, latex, texinfo). At my locale (mac os x 10.9.5) `/tmp` is a symlink to `/private/tmp`.

Then I tried `tox -e py36 --workdir /private/tmp/tox` which succeeded.

**Comment by tk0miya** [comment]
Oh, sorry. Please give non-symlink-ed path to `--workdir` option.
I know this is a workaround. But replacing a directory of tox is a bit hacky. So I'm not interested in to fix them. So it would be nice if this technique works well.

**Comment by blueyed** [comment]
I see, thanks for the workaround.
Do you know why the locations differ in the first place?

**Comment by tk0miya** [comment]
Maybe some module calls `realpath()`.

**Comment by tk0miya** [comment]
I'm closing this now.
If you're interested in fixing out tests, please send a pull request :-)

Thanks,
