### ISSUE TITLE
backwards incompatible change calling apidoc programatically

### ISSUE THREAD

**Issue by carandraug** [sphinx-doc/sphinx#5088]
### Problem

The function signature for `sphinx.ext.apidoc` changed in a backwards incompatible manner. One used to be able to call:

    apidoc.main([program-name, args, ...])

but this changed to:

    apidoc.main([args, ...])

This happened in commit 3e968bb1d4626c9af2b2643ece2563a9dcb8b0b0 although it's not clear what issue it was trying to fix or improve.

#### Procedure to reproduce the problem

I'm using my own package below for the sake of a complete example but the code below should work with any python package:

```
$ git clone https://github.com/MicronOxford/microscope.git
$ cd microscope
$ python -c 'from sphinx.ext.apidoc import main; main(["sphinx-apidoc", "--output-dir", "foo", "microscope"])'
usage: -c [OPTIONS] -o <OUTPUT_PATH> <MODULE_PATH> [EXCLUDE_PATTERN, ...]
-c: error: unrecognized arguments: microscope
```

This code fails because `"sphinx-apidoc"` is being passed in the list of arguments to main.  This is backwards incompatible with older versions.

Another side effect of the change 3e968bb1d4626c9af2b2643ece2563a9dcb8b0b0 is that if another script is calling `apidoc.main`, the error message displayed will use the script name that calls `apidoc` as the program with incorrect usage instead of sphinx-apidoc.

**Comment by carandraug** [comment]
> Another side effect of the change 3e968bb is that if another script is calling apidoc.main, the error message displayed will use the script name that calls apidoc as the program with incorrect usage instead of sphinx-apidoc.

Ignore this comment.  This was already not the case.

The backwards incompatible is still an issue and is breaking our builds.

**Comment by tk0miya** [comment]
Sorry for inconvenience. What version of Sphinx do you use? Surely, `sphinx.apidoc:main()` was broken between v1.7.0 and v1.7.1. But it was resolved now AFAIK. Do you mean the problem is still in latest release?

**Comment by carandraug** [comment]
> Sorry for inconvenience. What version of Sphinx do you use? 

We have two systems doing our builds. One is running version 1.6.4 where everything was working. The new one is running version 1.7.5.

> Surely, sphinx.apidoc:main() was broken between v1.7.0 and v1.7.1. But it was resolved now AFAIK. Do you mean the problem is still in latest release?

Yes.  The signature for `sphinx.apidoc:main()` in version 1.7.5 is still incompatible with the versions before 1.7.0.  You can try it yourself with one of your own packages:

    ## using sphinx 1.6.4
    $ git clone git@github.com:tk0miya/typematch.git
    $ cd typematch/
    $ python -c 'from sphinx.apidoc import main; main(["sphinx-apidoc", "--output-dir", "foo", "typematch"])'
    Creating file foo/typematch.rst.
    Creating file foo/modules.rst.

    ## using sphinx 1.7.5
    $ python -c 'from sphinx.ext.apidoc import main; main(["sphinx-apidoc", "--output-dir", "foo", "typematch"])'
    usage: -c [OPTIONS] -o <OUTPUT_PATH> <MODULE_PATH> [EXCLUDE_PATTERN, ...]
    -c: error: unrecognized arguments: typematch

At the moment I'm working around this incompatibilities like so:

```
try: # In sphinx 1.7, apidoc was moved to the ext subpackage
  import sphinx.ext.apidoc as apidoc
  ## In addition of changing the subpackage, the signature for main()
  ## also changed https://github.com/sphinx-doc/sphinx/issues/5088 If
  ## we are building in older versions, the program name needs to be
  ## included in the args passed to apidoc.main()
  apidoc_ini_args = []
except ImportError:
  import sphinx.apidoc as apidoc
  apidoc_ini_args = ['sphinx-apidoc']

## much much later...
apidoc.main(apidoc_ini_args + [
            "--separate", # each module on its own page
            "--module-first",
            "--output-dir", "doc/api",
            "microscope"])
```

**Comment by tk0miya** [comment]
Thank you for declaration. Surely `sphinx.apidoc:main()` and `sphinx.ext.apidoc:main()` is not incompatible. It is intended change.
What I'd like to say is that the interface of `sphinx.apidoc:main()` is not different with past release.

**Comment by carandraug** [comment]
> Thank you for declaration. Surely `sphinx.apidoc:main()` and `sphinx.ext.apidoc:main()` is not incompatible. It is intended change.

All right, fair enough then. I'll close the issue then

The deprecation warning:

> `sphinx.apidoc.main()` has moved to `sphinx.ext.apidoc.main()`

suggests to me that what changed was the subpackage though.

**Comment by TimZaman** [comment]
Also it stopped returning a value, and now returns nothing (None).
