### ISSUE TITLE
latex: curly braces in index entries are not handled correctly

### ISSUE THREAD

**Issue by xitology** [sphinx-doc/sphinx#5091]
### Problem
An index entry containing braces, e.g.,
```
.. index:: index{with}braces
```
is converted to ill-formed latex
```
\index{index\sphinxleftcurlybracewith\sphinxrightcurlybracebraces}
```

#### Procedure to reproduce the problem
- Create a new project with `sphinx-quickstart`
- Add an index entry `.. index:: index{with}braces`
-  run `make latexpdf`

#### Error logs / results
```
...
! Undefined control sequence.
l.5   \item index\sphinxleftcurlybracewith
                                          \sphinxrightcurlybracebraces, \hyp...
...
```
#### Expected results
Expected the latex builder to properly escape curly braces, e.g.,
```
\index{index{\sphinxleftcurlybrace}with{\sphinxrightcurlybrace}braces}
```
### Environment info
- OS: Ubuntu 16.04
- Python version: 2.7.12
- Sphinx version: 1.7.5

**Comment by tk0miya** [comment]
Fixed by #5095.
Thank you for reporting!
