### ISSUE TITLE
Search in the released docs is broken

### ISSUE THREAD

**Issue by timhoffm** [sphinx-doc/sphinx#5100]
# Subject: Search in the released docs is broken

## Steps to reproduce:

1. Go to http://www.sphinx-doc.org/en/master/search.html
2. Enter 'role'

### Expected result

The search starts and the results pop up.

### Actual result

The url changes to http://www.sphinx-doc.org/en/master/search.html?q=role
However, the search field gets cleared and no results are shown.

**Comment by tk0miya** [comment]
Fixed. Thank you for reporting!
