### ISSUE TITLE
Wrong 3-level menu rendering

### ISSUE THREAD

**Issue by postb99** [sphinx-doc/sphinx#5109]
Subject: 
Wrong 3-level menu rendering.

### Problem
I have a menu with 3 levels, using #, * and = restructuredtext markup.
I use sphinx_rtd_theme for html theme.
The 3rd level menu item appears not nested but below.

#### Procedure to reproduce the problem
- create a project using `sphinx-quickstart`
- in conf.py, change theme:
`html_theme = 'sphinx_rtd_theme'`
- change index.rst so that it contains this:

```
Title 1
###################

Subtitle 1
****************

Paragraph
==========================
Information
```
#### Error logs / results
"Paragraph" appears below "Subtitle 1" and not nested
![image](https://user-images.githubusercontent.com/173565/41601840-b99de4f0-73d9-11e8-85f4-f3ca447363c1.png)

#### Expected results
Nested items

### Reproducible project / your project
https://softinux-base.readthedocs.io/en/latest/write_extensions.html#

### Environment info
- OS: Windows
- Python version: 3.6
- Sphinx version: 1.8

**Comment by tk0miya** [comment]
I guess this might be a bug of sphinx_rtd_theme. Are you saying this is a bug of sphinx-core?

**Comment by postb99** [comment]
Did I report it to the wrong place? I think you're right about the bug concerning the theme, I didn't get the bug with the default theme.

**Comment by tk0miya** [comment]
sphinx_rtd_theme is not bundled theme. Please report to thier project: https://github.com/rtfd/sphinx_rtd_theme

Thanks,

**Comment by postb99** [comment]
Thanks, for anyone interested: https://github.com/rtfd/sphinx_rtd_theme/issues/653
