### ISSUE TITLE
Raise error when an autodoc directive produces no output

### ISSUE THREAD

**Issue by Zac-HD** [sphinx-doc/sphinx#5113]
*This is a suggested improvements, not a bug report.*

Sometimes, autodoc directives do not result in any output being created.  This is almost certainly the result of misuse or a mistake by the user, but because it requires manual checks (or hand-written tests) to detect it may often go unnoticed for some length of time - see for example HypothesisWorks/hypothesis#1326.

Instead, I suggest that autodoc directives should raise an error if they would produce no output.  This can be handled simply by deleting the ineffective directive, which does not change the output at all.  If the current behaviour *must* be maintained, despite the downsides, a warning could be emitted instead of an error.

**Comment by Zac-HD** [comment]
https://github.com/sphinx-doc/sphinx/blob/e1201f277902df12ff5fca1e2a63a73bbae58296/sphinx/ext/autodoc/directive.py#L128-L133

Changing `return []` to `raise SphinxError(...)` (or a new autodoc-specific subtype) should be enough to fix this, with appropriate testing.

**Comment by tk0miya** [comment]
+1: But I think warning is much better.

**Comment by tk0miya** [comment]
@Zac-HD Sorry, I can't reproduce the error. Could you share how to reproduce the situation?

**Comment by Zac-HD** [comment]
I don't have a minimal reproducer yet - if so I would have opened a PR already!  We've seen autodoc give no output in [Hypothesis' docs](https://hypothesis.readthedocs.io/en/latest/numpy.html) though, and we'd like to catch that when we run a Sphinx build on Travis.

I unfortunately have very little free time at the moment (and several things to fix in Hypothesis), but do intend to come back to this once my work calms down.

**Comment by tk0miya** [comment]
It seems sphinx-build has already emitted warnings for imports.
```
WARNING: autodoc: failed to import module u'hypothesis.extra.dateutil'; the following exception was raised:
No module named dateutil
WARNING: autodoc: failed to import module u'hypothesis.extra.numpy'; the following exception was raised:
No module named numpy
WARNING: autodoc: failed to import module u'hypothesis.extra.pandas'; the following exception was raised:
No module named numpy
```
https://readthedocs.org/projects/hypothesis/builds/7517368/

If true, additional warning is not needed to me.

**Comment by Zac-HD** [comment]
Ah, it turns out that the problem is that we had different environments (ie installed dependencies) between Travis and readthedocs.io.  I agree that an additional warning is therefore not needed - thanks for pointing this out!
