### ISSUE TITLE
Display all warnings with -W (warningiserror)

### ISSUE THREAD

**Issue by blueyed** [sphinx-doc/sphinx#5121]
Currently using `-W` will stop on the first warning, but that makes it harder to interate over existing warnings, since you only get the first one.

This appears to happen via the `WarningIsErrorFilter` currently, which raises `SphinxWarning`.

I think using `-W` should display all warnings (i.e. keep on processing), but then cause a non-zero exit status only (and e.g. forcing a fresh build the next time, like it appears to happen for exceptions currently in general).

**Comment by tk0miya** [comment]
Thank you for proposal. But that is already posted as #4614.
So I'm closing this because of dup.
