### ISSUE TITLE
semantics of sphinx.main was changed when sphinx.cmd.build.main was introduced

### ISSUE THREAD

**Issue by guyer** [sphinx-doc/sphinx#5125]
Subject: <what happen when you do on which document project>

### Problem

As discussed in #4615, prior to 89f9c7cab, `sphinx.main` took a list as its argument:

    def main(argv=sys.argv[1:])

Afterwards, it took a variable number of arguments and passed them on to `sphinx.cmd.build.main`

    def main(*args, **kwargs)

With b5bae23, though

    args = args[1:]

throws everything away, because `args` is not a list, it's a tuple that holds a list.

#### Procedure to reproduce the problem
```
>>> import sphinx
>>> sphinx.main(['sphinx_build', '-b', 'html', '-c', 'documentation/', '.', 'documentation/_build/html'])
```

#### Error logs / results
```
usage:  [OPTIONS] SOURCEDIR OUTPUTDIR [FILENAMES...]
: error: too few arguments
```

#### Expected results
If `sphinx.main` is being deprecated anyway, it should retain the sematics it always had:

    def main(argv=sys.argv[1:])

### Reproducible project / your project

usnistgov/fipy@71c48d9037

invoke

    python setup.py build_docs --html

### Environment info
- OS: Mac 10.13.5 (doesn't matter)
- Python version: 2.7.15 
- Sphinx version:  1.7.5

**Comment by tk0miya** [comment]
Fixed by #5131.
Thank you for reporting
