### ISSUE TITLE
Links to Sphinx documentation are broken

### ISSUE THREAD

**Issue by goerz** [sphinx-doc/sphinx#5148]
Pretty much all links to the Sphinx documentation are currently broken, leading to a 404 page. This includes Google search results and StackOverlfow. For example, https://stackoverflow.com/a/22768779/152544 links to
http://sphinx-doc.org/ext/autodoc.html#confval-autodoc_default_flags

The current URL for that link is http://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_default_flags

It would probably be a good idea to set up the webserver hosting the documentation to forward the URLs. I'd consider Sphinx to be a pretty high-level project, so breaking all links to its documentation seems like a problem.

**Comment by tk0miya** [comment]
Thank you for reporting.
I'd forgotten to update redirection mapping on restructuring our document.
Now I updated it :-)
