### ISSUE TITLE
Using title:: in an include file replaces <title> tag of file containing the included text

### ISSUE THREAD

**Issue by barbara-sfx** [sphinx-doc/sphinx#5149]
### Problem

Including `title::` in an include file replaces the <title> tag of the page containing the include file with the title of the include file.

#### Procedure to reproduce the problem

1. Create a file to include in another file (file A).

1. In file A, add the statement `.. title:: File A`

1. Create another file (file B). File B has a standard RST title, like "File B".

1. In file B, add the statement `.. include:: file A`

1. Build your project and load file B into a browser.

#### Error logs / results

Title shown in browser is  "File A"

#### Expected results

Title shown in browser is "File B"

### Reproducible project / your project

[include-bug.zip](https://github.com/sphinx-doc/sphinx/files/2168567/include-bug.zip)

![screen shot 2018-07-05 at 4 56 20 pm](https://user-images.githubusercontent.com/17709550/42353335-ad6f098c-8074-11e8-9b12-06d8115beed0.png)

### Environment info
- OS:  Mac 10.13.4
- Python version: 2.7.11
- Sphinx version: 1.7.5
- <Extra tools e.g.: Browser, tex or something else>

**Comment by barbara-sfx** [comment]
BTW the problem persists even if I add a title:: File B into the containing file. The title of the include file still overrides the correct title.

**Comment by tk0miya** [comment]
Hmm? The `title` directive is executed as part of file B. So this is not surprising result.
I don't know why do you add the directive into included rst file.
Could you tell me your goal.

**Comment by barbara-sfx** [comment]
My SEO folks want all files to have a title, so when they show up in a search results list, they don't just say `<no title>`.

**Comment by barbara-sfx** [comment]
Actually, it's the RTD search engine that shows them with `<no title>` in the list. google excludes them from search results completely, which is why the SEO folks want them to have titles.

**Comment by tk0miya** [comment]
Is your goal that putting same title to all document? I'd like to know why did you put `title` directive into included document.
If you want to set individual title to each document, you should put the directive to each document.

Note: I don't know how search of readthedocs works. AFAIK, it implements original search engine. So I can't answer why they returns "no title".

**Comment by barbara-sfx** [comment]
Here is the issue:

The include files don't include an RST-style title, because then that would show up in the target file (file containing the `include::` directive). They may be just a series of paragraphs, with no headings at all.

This has 2 negative ramifications: google won't index them, and RTD displays them as "No title".

Therefore, I want to add titles that google and RTD can use. However, if I put a` title:: `directive into an include file, it propagates to the target file.

For example, say I have a file titled "Getting started with charts" and another file titled "Customizing charts" ." Each file has `.. include:: options.rst` to display common content on setting chart options.

I want google and RTD to handle options.rst correctly, so I add `title:: Chart options` to options.rst. However, when I open "Getting started with charts"  or "Customizing charts," the title of the doc is now "Chart options", which is incorrect.

I do not want the `title::` directive in the include file to overwrite the real title in the target file.

**Comment by tk0miya** [comment]
Okay, I understand. 

>The include files don't include an RST-style title, because then that would show up in the target file (file containing the include:: directive). They may be just a series of paragraphs, with no headings at all.

Sphinx picks up the first section title of the document as a title. If it does not have any headings, Sphinx fills a title "<no title>" by default. This is behavior of Sphinx.

>For example, say I have a file titled "Getting started with charts" and another file titled "Customizing charts" ." Each file has .. include:: options.rst to display common content on setting chart options.

Yes, of course. `title` directive *overrides* a title of current document. Hence this behavior is intended.

>I do not want the title:: directive in the include file to overwrite the real title in the target file.

I don't know that. The included file is considered as a part of includee file. So it is hard to skip the directive.

Anyway, this is not a bug of Sphinx. So I'm closing this.
Thanks,

**Comment by barbara-sfx** [comment]
How would I create a feature request such that directives like this in include files do NOT overwrite the target file? If you think about it, it doesn't make sense, since the whole point of include files is to show up in multiple target files. So having the same title get put in multiple documents would never be desirable.

**Comment by tk0miya** [comment]
The include directive of sphinx works like concatenation.

For example:
```
index.rst
=========

This is parent reST file.

.. include:: common.rst

Hello index.rst!
```
```
This is common reST file.

.. title:: new title
```

Sphinx considers them as following:
```
index.rst
=========

This is parent reST file.

This is common reST file.

.. title:: new title

Hello index.rst!
```

It is very simple feature. So there are no way to prevent disable arbitrary directive in included file. So we can't help you if you post a feature request. Please don't use title directive inside included file. I think it is wrong usage.

Thanks,
