### ISSUE TITLE
Directives documentation has a ton of dead links

### ISSUE THREAD

**Issue by NapsterInBlue** [sphinx-doc/sphinx#5155]
### Problem
- Following any of the links in the [directives section of the basics page](http://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#directives) takes me to a  completely blank page.

- Intended Link:
http://docutils.sourceforge.net/docs/ref/rst/directives.html

- Screenshot of Index showing page has size=0:
![image](https://user-images.githubusercontent.com/3505365/42460918-27e10dbe-836d-11e8-9eef-8f62e5c4535b.png)

#### Procedure to reproduce the problem

Following any of the hyperlinks in the directive section:

http://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#directives

#### Expected results
- Rendered version of [this text file](http://docutils.sourceforge.net/docs/ref/rst/directives.txt)

### Environment info
- Browsers
    - Chrome: Version 66.0.3359.181 (Official Build) (32-bit)
    - IE: Version 11.492.16299.0

**Comment by tk0miya** [comment]
This was a trouble of docutils project. And it seems already resolved now.
So I'm closing this.
Thanks,
