### ISSUE TITLE
Regression 1.7.0 to 1.7.1: autosummary, bad module summary

### ISSUE THREAD

**Issue by paugier** [sphinx-doc/sphinx#5158]
### Problem

Autosummary fails to correctly parse a rst docstring like

```
"""
My title
========

blabla...

"""
```

and produce an incorrect summary "My title ========".

### Reproducible project / your project
- http://fluiddyn.readthedocs.io/en/latest/

### Environment info
- OS: linux
- Python version: tested on 3.6 and 3.7
- Sphinx version: 

The bug only happens for versions > 1.7.0.

More precisely, the bug appeared with commit d40db5efa260efbecdbd7cf3d8b86d3de7280b10 (Fix #4563: autosummary: Incorrect end of line punctuation detection).

**Comment by tk0miya** [comment]
Fixed by #5182 .
Thank you for reporting!
