### ISSUE TITLE
dead links in documentation of sphinx itself

### ISSUE THREAD

**Issue by MareoRaft** [sphinx-doc/sphinx#5160]
### Problem
When visiting the page

http://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html

the directive links bring send the user to, for example,

http://docutils.sourceforge.net/docs/ref/rst/directives.html#csv-table

which is just a blank page.  Hence, the links are dead.

#### Expected results
It brings the user to a webpage that explains in further detail how to use that directive.

### Environment info
Opera, version 54.0

**Comment by NapsterInBlue** [comment]
Related Issue: #5155 

In the meantime, bookmarking [the `.txt` file that generates the page](http://docutils.sourceforge.net/docs/ref/rst/directives.txt) has helped me in a couple of pinches.

**Comment by tk0miya** [comment]
This was a trouble of docutils project. And it seems already resolved now.
So I'm closing this.
Thanks,
