### ISSUE TITLE
 mkdir(name, mode) NotADirectoryError: [Errno 20] Not a directory: '..doc/_build/html/_static/fonts/RobotoSlab'

### ISSUE THREAD

**Issue by disencd** [sphinx-doc/sphinx#5161]
Subject:  mkdir(name, mode) NotADirectoryError: [Errno 20] Not a directory: '..doc/_build/html/_static/fonts/RobotoSlab'

### Problem
```
 mkdir(name, mode) NotADirectoryError: [Errno 20] Not a directory: '..doc/_build/html/_static/fonts/RobotoSlab'
```

#### Procedure to reproduce the problem
```
 mkdir(name, mode) NotADirectoryError: [Errno 20] Not a directory: '..doc/_build/html/_static/fonts/RobotoSlab'
```

#### Error logs / results
```
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... WARNING: search index couldn't be loaded, but not all documents will be built: the index will be incomplete.
done
writing output... [100%] library                                                                                                                              
generating indices... genindex py-modindex
writing additional pages... search
copying static files... 
Exception occurred:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
NotADirectoryError: [Errno 20] Not a directory: '/Users/ddevassy/Documents/logi/Seam/lci/doc/_build/html/_static/fonts/RobotoSlab'
The full traceback has been saved in /var/folders/0n/by0ts5_d6qg7yfry647x5fxh2ngr3b/T/sphinx-err-r2et3w57.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [html] Error 2
```

- <public link of unexpected result if you have>

#### Expected results
<Describe what to actually do>

### Reproducible project / your project
- <link to your project, or attach zipped small project sample>

### Environment info
- OS: Mac
- Python version: 3.6
- Sphinx version: sphinx-quickstart 1.7.5
- <Extra toolsGoogle Chrome

**Comment by disencd** [comment]
[sphinx-err-r2et3w57.log](https://github.com/sphinx-doc/sphinx/files/2182988/sphinx-err-r2et3w57.log)

Attaching the log

**Comment by tk0miya** [comment]
It seems a type of `_build/html/_static/fonts/RobotoSlab` had been changed since last build.
I don't know what was actually happened in your environment.
But it will be resolved with `make clean` command. It completely clears your build directory.

**Comment by tk0miya** [comment]
Note: I give a better error message for this case (refs: #5175).

**Comment by disencd** [comment]
Thanks everyone for reviewing this bug. It was observer only once. Now always its working as expected.

make clean ; make html.  resolved this issue

**Comment by tk0miya** [comment]
:-)
