### ISSUE TITLE
HTML builder: Spaces in links are not converted to %20

### ISSUE THREAD

**Issue by ArtFlag** [sphinx-doc/sphinx#5162]
### Problem

Spaces in link anchors ``linktitle <www.mypage.net#this anchor>_`` are not converted to `%20`.

#### Procedure to reproduce the problem

Build the HTML output of a page that contains a link with spaces:

```
`My link <www.mypage.net#my anchor>`_
```

#### Results

`<a href="www.mypage.net#myanchor">`

Therefore link does not behave as expected from the rST content.

#### Expected results

`<a href="www.mypage.net#my%20anchor">`

### Environment info

- OS: MacOS High Sierra
- Python version: 2.7
- Sphinx version: 1.7.5

**Comment by tk0miya** [comment]
This is same behavior as docutils (rst2html).
```
$ echo '`My link <www.mypage.net#my anchor>`_' | rst2html.py | grep anchor
<p><a class="reference external" href="www.mypage.net#myanchor">My link</a></p>
```

It is an issue of reST spec. Please ask to docutils team.

**Comment by tk0miya** [comment]
I'm closing this now because this is not a bug of Sphinx.
Note: This was reported as https://sourceforge.net/p/docutils/bugs/345/

Thanks,
