### ISSUE TITLE
Permission Error when trying to make html

### ISSUE THREAD

**Issue by asasanuma** [sphinx-doc/sphinx#5166]
Subject: <When I try to make html it gives me a permission error>

When trying to create html, which is only my second step after sphinx-quickstart, it gives me a permission error and doesn't allow me to create the html.

### Problem
- <Permission Error>

#### Procedure to reproduce the problem
```
<Command-line here which causes the problem>
make html 
```
```
<Error log>
Exception occurred:
File  File "/Users/asasanuma/anaconda3/lib/python3.6/site-packages/sphinx/util/osutil.py" line 102, in walk
    names = os.listdir(top)
PermissionError: [Errno 13] Permission denied: File '/Users/asasanuma/Library/Saved Application State/com.adobe.flashplayer.installmanager.savedState'
```

#### Expected results
Should create html file.

### Environment info
- OS: <Mac>
- Python version:3.6
- Sphinx version:1.7.4
- <Extra tools e.g.: Browser, tex or something else>

**Comment by tk0miya** [comment]
Where did you create your sphinx project?

```
PermissionError: [Errno 13] Permission denied: File '/Users/asasanuma/Library/Saved Application State/com.adobe.flashplayer.installmanager.savedState'
```

This error says Sphinx project contains unreadable file or directory. And it seems `Library/Saved Application State` is not a part of sphinx project.
I guess you might create sphinx project on your home directory. Please create a sub directory and create new project into it.

Thanks,

**Comment by tk0miya** [comment]
I'm closing this now because this would caused by usage, not a bug.
Thanks,
