### ISSUE TITLE
Lualatex: escaping of `>` by `\textgreater{}` is not enough, `>>`  applies ligature

### ISSUE THREAD

**Issue by jfbu** [sphinx-doc/sphinx#5179]
Sphinx LaTeX escapes `>` in source to `\textgreater{}` in produced TeX file. Unfortunately with `lualatex`, `\textgreater{}\textgreater{}` becomes a ligature: `»`. This is not the case with `xelatex` or `pdflatex`.

This showed up as real-life problem when trying to build the PDFs of the CPython documentation using lualatex, as Python wants ``>>>`` indexed of course!

**Comment by tk0miya** [comment]
It seems `>>` (not `\textgreater{}` is also combined to `»`. It should be change behavior of ligature for LuaLaTeX.
```
\documentclass{report}

\begin{document}
Ligature test: >> and \textgreater{}\textgreater{}
\end{document}
```

**Comment by jfbu** [comment]
@tk0miya To prevent ligature I was recommended upstream by David Carlisle to use either `\textgreater\/` or `\mbox{\textgreater}`.

side-note: for literals and code-blocks, preventing `>>` TeX ligature is achieved via other means and needs no fix for lualatex

**Comment by jfbu** [comment]
By the way also `-{}-` or `-{-}` mark-up with LuaLaTeX give via ligature a long dash rather than `--` in PDF. One does not see it easily in Sphinx documents, as in this example from our own doc `sphinx.tex`:

```
\pysigline{\sphinxbfcode{\sphinxupquote{-q}}\sphinxcode{\sphinxupquote{}}\sphinxcode{\sphinxupquote{,~}}\sphinxbfcode{\sphinxupquote{-{-}quiet}}\sphinxcode{\sphinxupquote{}}}
```

because:

1. `fontspec` does not apply `Ligatures = TeX` for mono font, which is triggered by `\sphinxcode` or `\sphinxbfcode` by default,

2. additionally `\sphinxupquote` does extra things with `-` which also make ligature impossible.

But with LuaLaTeX and a non-monospace font, input such as `-{}-` or `-{-}` does create ligature. (contrarily to pdflatex/xelatex)
