### ISSUE TITLE
sphinx make html command error

### ISSUE THREAD

**Issue by asasanuma** [sphinx-doc/sphinx#5184]
Subject: <Error occurs after make html command on sphinx>

### Problem
- After make html command
make: *** No rule to make target `html'.  Stop. 
This error appears. I saw a similar problem on the forum but the answer didn't seem to solve the question.

#### Procedure to reproduce the problem
```
<make html>
```

#### Error logs / results
```
make: *** No rule to make target `html'.  Stop.
```

#### Expected results
Creates html docs

Do I need to specify the directory when inputting the command "make html"? Would appreciate any form of help.

**Comment by jfbu** [comment]
Please there is a template here when posting issues. What is your system?

Besides this is not user forum but site to report bugs. Please consider stackoverflow.com with tag `python-sphinx` and sphinx-users group which you can access with Thunderbid via GMane gmane.comp.python.sphinx.user, news://news.gmane.org:119/gmane.comp.python.sphinx.user or use the gggggggggglllllllleeeee groups web interface.

**Comment by tk0miya** [comment]
I'm closing this now because this would not be a bug of Sphinx.
If you are still in trouble, please file a new issue with detailed information.
Thanks,
