### ISSUE TITLE
JavaScript tests?

### ISSUE THREAD

**Issue by TimKam** [sphinx-doc/sphinx#5186]
According to the GitHub stats, 26.2% of the Sphinx code is JS. This metric is inaccurate, as it includes code like stemmers that is copied from other projects and requires little maintenance effort. Still, it probably makes sense to add JavaScript tests to avoid regressions and increase maintainability in the long run.

If deemed beneficial, I would gladly work on introducing JavaScript tests and propose proceeding as follows:

1. Reduce the code that is contained in JavaScript "templates" to global configuration variables and move the rest of the code into ordinary `.js` files.
2. Write a handful of example JavaScript tests.
3. Set up JavaScript CI with Travis or Circle CI.
4. Gradually increase test coverage.

**Comment by tk0miya** [comment]
+1: it's very helpful

**Comment by TimKam** [comment]
As the branch is merged, I'll close this issue. I will add more tests and create new issues for each PR to have a 1-1 Issue - PR mapping.
