### ISSUE TITLE
CUDA Function Decorators Give Warnings

### ISSUE THREAD

**Issue by cliffburdick** [sphinx-doc/sphinx#5187]
Subject: When compiling the markup files for CUDA code, I see the warnings.

### Problem
The sphinx compiler shows:

Invalid definition: Expected identifier in nested name, got keyword: void [error at 15]
      __global__ void TL::est(float * a)

I'm guessing this is because the parser doesn't recognize the __device__ and __global__ decorators since it's cuda-specific. Is there a workaround for this? There should be two underscores on global and device, but github's markdown seems to make it bold.

**Comment by jakobandersen** [comment]
I assume this is with the C++ domain?
In that case, it is possible to tell Sphinx that ``global`` should be treated as a valid attribute: http://www.sphinx-doc.org/en/master/usage/configuration.html#confval-cpp_id_attributes.
That is, in ``conf.py`` insert something like: ``cpp_id_attributes = ["__global__", "__device__"]``

(Perhaps we should improve the documentation to make this much clearer.)

**Comment by cliffburdick** [comment]
Thanks @jakobandersen! That seemed to work for that case. Do you know if there's a way to fix it within the function definition itself on C++ functions that use __restrict__? Here's an example:

  If declarator-id:
    Invalid definition: Expecting "," or ")" in parameters_and_qualifiers, got "a". [error at 72]
      __global__ void TL::est2(float*__restrict__ a)

It looks similar to this issue:

https://github.com/sphinx-doc/sphinx/issues/2682

But cpp_paren_attributes still gives the errors

**Comment by dabe5** [comment]
Namaste

**Comment by dabe5** [comment]
Kolkata

**Comment by jakobandersen** [comment]
The ``cpp_paren_attributes`` is for custom attributes that takes an argument, so that is not the right one to use here. Attributes are only parsed in a few places, and as part of declarators was not one of them. On master, which will become version 1.8, it should work now. You just have to add ``__restrict__`` to ``cpp_id_attributes`` as well.
