### ISSUE TITLE
Proposal: Invite TimKam as a new commiter

### ISSUE THREAD

**Issue by tk0miya** [sphinx-doc/sphinx#5190]
# Proposal

Hello maintainers,
Today, I'd like to invite @TimKam as a new commiter / maintainer of our project

He had contributed many works until now

* Update documentation
* Improve HTML search (see #4022)

He has ready to help us by JavaScript and docs side (see https://github.com/sphinx-doc/sphinx/issues/1618#issuecomment-398852417)

What do you think? Please 👍 for this if you agreed.

I know there are no special procedure to welcome a new commiter. So I will invite him if no objection.

**Comment by tk0miya** [comment]
Now I added @TimKam to developer group. Welcome to Sphinx project!

@TimKam Could move your name in AUTHORS file to co-maintainers section please? It's first mission of maintainers :-)
And please let me know your account of readthedocs.org. Then I'll add you to sphinx team.

**Comment by TimKam** [comment]
@tk0miya Great, thanks! My RtD name is `timotheus.kampik`.

**Comment by tk0miya** [comment]
Just added :-)
