### ISSUE TITLE
Markdown configuration instructions use deprecated config parameter

### ISSUE THREAD

**Issue by TimKam** [sphinx-doc/sphinx#5216]
Subject: Markdown configuration instructions use deprecated config parameter

### Problem
The [Markdown parser configuration instructions](http://www.sphinx-doc.org/en/master/usage/markdown.html) refer to the deprecated [source_parsers](http://www.sphinx-doc.org/en/master/usage/configuration.html#confval-source_parsers) configuration parameter instead of the proper [add_source_parser](http://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx.application.Sphinx.add_source_parser) API.
We should update this.

**Comment by tk0miya** [comment]
In master branch, recommonmark has already used `add_source_parser()` API. But it is not released yet. I feel it has been no longer maintained. The last release was 2+ years ago...

**Comment by tk0miya** [comment]
Note: I just send a PR to use new styled APIs in recommonmark. It would be nice if merged. Because old styled `add_source_parser()` will be removed in Sphinx-3.0.
https://github.com/rtfd/recommonmark/pull/113

**Comment by TimKam** [comment]
Great. Then I'll wait for this PR to be merged, but will prepare a Sphinx docs PR in anticipation asap.
