### ISSUE TITLE
"make html" does not read and build "po" files in "locale" dir.

### ISSUE THREAD

**Issue by road42** [sphinx-doc/sphinx#5231]
Subject: make html does not read and build "po" files in "locale" dir.

### Problem
- When I build my documentation, sphinx ignores all my ".po" files.

I debugged the problem down to this line in `builders\__init__.py:258`

```python
        catalogs = i18n.find_catalog_source_files(
            [path.join(self.srcdir, x) for x in self.config.locale_dirs],
            self.config.language,
            domains=list(specified_domains),
            charset=self.config.source_encoding,
            gettext_compact=self.config.gettext_compact,
            excluded=Matcher(['**/.?**']))
```

When I remove the content of the Matcher. The `.po` files are
found and everything works

```python
        catalogs = i18n.find_catalog_source_files(
            [path.join(self.srcdir, x) for x in self.config.locale_dirs],
            self.config.language,
			None,
            charset=self.config.source_encoding,
            gettext_compact=self.config.gettext_compact,
            force_all=True,
            excluded=Matcher([]))
```

#### Procedure to reproduce the problem
```
make html
```
but not so easy to reproduce

#### Error logs / results
`building [mo]: all of 0 po files`

#### Expected results
`building [mo]: all of 13 po files`

### Environment info
- OS: Win Server 2012 R2
- Python version: 3.5.1 64bit
- Sphinx version: 1.7.6

**Comment by tk0miya** [comment]
Thank you for reporting. I'll take a look this later.
Note: the matcher was added in #4928.

**Comment by road42** [comment]
If I run the same generation on

- OS: Windows 10
- Python version: 3.5.2 64bit
- Sphinx version: 1.7.6

Everything works well.

**Comment by road42** [comment]
Ah sorry, I removed my previous comment, that it works on Pyhton 3.5.2. I updated "sphinx" in between and now I have the same error, too.

**Comment by tk0miya** [comment]
I'm trying this issue now. But I can't reproduce this error.
What language do you use? What command line options do you use? Could you share your project if possible?

**Comment by tk0miya** [comment]
Any updates?

**Comment by road42** [comment]
I've had no time to look into anything. After removing the matcher anything worked again.
The language is "de" and we only call "make.bat html". I'll see if I have some time to reproduce
the error on an empty project.

**Comment by csezenoglu** [comment]
I have the same problem. I explain steps below:,

- I create pot files with this command: "make gettext" command.
- I create po files with this command: "sphinx-intl update -p _build/locale -l tr_TR"
Message:
Create: locale/tr_TR\LC_MESSAGES\index.po
Create: locale/tr_TR\LC_MESSAGES\content\circuit-modeling.po
...
- Then I want to build po files to mo files with this command: "sphinx-build -b html -D language=tr_TR . _build/html/tr_TR"

Everything is ok: html files and mo files except "index.po" file in "locale/tr_TR/LC_MESSAGES" dir.

I tried many variations. build all po files under any folder in "locale/tr_TR/LC_MESSAGES" folder. But only it did not build files under "locale/tr_TR/LC_MESSAGES" directory.

**Comment by road42** [comment]
I cleaned up all pip-packages on my Windows PC and reinstalled every sphinx-package - 1.8.1 (still Python3). 
Still does not find the .po-files and as soon as I remove the parameters from the Matcher they are found.
Have not had the time to create an example-project with the same behaviour (sorry for that).

**Comment by tk0miya** [comment]
Can anyone try this patch? This bug might be related with OS path separator.
```
diff --git a/sphinx/util/matching.py b/sphinx/util/matching.py
index bddf84f5c..08e478545 100644
--- a/sphinx/util/matching.py
+++ b/sphinx/util/matching.py
@@ -86,6 +86,8 @@ class Matcher(object):

     def match(self, string):
         # type: (unicode) -> bool
+        from sphinx.util.osutil import canon_path
+        string = canon_path(string)
         return any(pat(string) for pat in self.patterns)
```

**Comment by tk0miya** [comment]
What about patch on last comment?

**Comment by tk0miya** [comment]
I applied the last patch to 1.8 branch. Please check it on next release.
Thanks,
