### ISSUE TITLE
LaTeX: ``xindy`` does not detect that index is empty, creates empty Index section in PDF

### ISSUE THREAD

**Issue by jfbu** [sphinx-doc/sphinx#5240]
master branch has incorporated usage of xindy for UTF-8 index in PDF builds. Unfortunately, contrarily to `makindex`, `xindy` does not detect that `.idx` file is empty. With an empty `.idx` file (no usage of ``index`` role or directive in reST sources), `makeindex` produces an empty `.ind` file, but `xindy` produces an `.ind` file including the preamble/postamble the `\begin{sphinxtheindex}...\end{sphinxtheindex}` configured in `sphinx.xdy`. This causes an empty Index section at end of document.

#### Procedure to reproduce the problem

Do `make clean latexpdf O="-D latex_use_xindy=1"` on any project which does not use ``index`` directive or role.

#### Error logs / results

The PDF contains an empty Index section at end of PDF.

#### Expected results

No empty Index section is created.

For pdflatex, this bug is not really an issue because `latex_use_xindy` is an opt-in option.

But for xelatex/lualatex it is on by default.

@tk0miya the easy way to fix this is to let default's value of `latex_use_xindy` always be `False`, even for `xelatex`, and `lualatex`.

If I find no solution at xindy's side, this is what I suggest to do.

### Environment info
- OS: Mac
- Python version: 3.6.4
- Sphinx version: 1.8+
- TeXLive 2018

Relates:

#5134, #5192, #5212

**Comment by jfbu** [comment]
This is fixed by either #5241 (make xindy purely opt-in), or by #5242 (use a shell test to see if raw index file is empty and use xindy only if non-empty). I prefer #5242, hoping its shell syntax works on all Unixen.

**Comment by tk0miya** [comment]
+1 for #5242!

**Comment by jfbu** [comment]
Thanks @tk0miya for advice, I will merge #5242. In future it could be possible as alternative to the ``[ -s FILE.idx ]`` shell test to use a "Latexmk subrule" to express it all in Perl syntax...
