### ISSUE TITLE
apidoc internationalization

### ISSUE THREAD

**Issue by m-aciek** [sphinx-doc/sphinx#5255]
Subject: apidoc extension does not internationalize phrases

### Problem
- Files generated with apidoc are English despite locale specified in conf.py.
- Those strings are missing in Sphinx translation on Transifex.

#### Procedure to reproduce the problem
```
sphinx-apidoc [OPTIONS] -o <OUTPUT_PATH> <MODULE_PATH> [EXCLUDE_PATTERN, …]
```

#### Error logs / results
Not translated files.

```
[name] package
===============

Subpackages
-----------

.. toctree::

    …

Module contents
---------------

.. automodule:: …
```

#### Expected results
apidoc-generated files translated in my locale, or a way to make them translated.

```
Pakiet [name]
===============

Podmoduły
-----------

.. toctree::

    …

Zawartość modułu
---------------

.. automodule:: …
```

- Python version: 3.6
- Sphinx version: 1.7.6

**Comment by tk0miya** [comment]
Did you mean "apidoc" instead of "autodoc"?
I think you can translate generated document by autodoc using gettext.

**Comment by m-aciek** [comment]
Sure, I mean apidoc, thank you. Let's supose I have one-language documentation, not using i18n for it. Could we add gettext wrappers in apidoc extension to let generated files be already translated according to locale in conf.py?

**Comment by tk0miya** [comment]
No, we already have i18n feature. AFAIK, you can use it by `make gettext`. I believe it also works for generated document by apidoc.
So I don't want to support your request.
Thanks,

**Comment by m-aciek** [comment]
Ok, thank you for your feedback.

It looks like I can achieve similar result using https://github.com/goerz/better-apidoc (and waiting for #3545 to be done). I'll check it out.
