### ISSUE TITLE
Index layout is atrocious (HTML)

### ISSUE THREAD

**Issue by skaller** [sphinx-doc/sphinx#5268]
The layout of the index is extremely poor. HTML on RTD. I get a list like this:
```
A
abstract
type
application
direct
indirect
```

It should look like this:

```
A
abstract
  type
application
  direct
  indirect
```
or
```
A
abstract, type
application
  direct
  indirect
```
Actually this case is harder because "application" by itself (without qualifiers) should be listed.

**Comment by tk0miya** [comment]
Please repost an issue using our issue template. It seems your report does not contain reproducible information.
Thanks,

**Comment by skaller** [comment]
Thanks. You've never used an index.

So here is a link:

https://felix.readthedocs.io/en/latest/genindex.html

The result is whatever ReadTheDocs does.  Maybe they use a bad index renderer and I should post the bug there.
