### ISSUE TITLE
Help Wanted - Build keeps failing

### ISSUE THREAD

**Issue by roppenheimer** [sphinx-doc/sphinx#5272]
I have cloned another project which builds successfully but this copy keeps failing the build - I cannot work out why. 

The project is https://readthedocs.org/projects/androidaps-altguide/ 

I get the following error message...

TypeError: 'NoneType' object is not callable

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/androidaps-altguide/envs/latest/local/lib/python2.7/site-packages/recommonmark/states.py", line 134, in run_role
    content=content)
TypeError: 'NoneType' object is not callable
The full traceback has been saved in /tmp/sphinx-err-153P00.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.

Subject: <what happen when you do on which document project>

### Problem
- <Detail of problem>

#### Procedure to reproduce the problem
```
<Paste your command-line here which cause the problem>
```

#### Error logs / results
```
<Paste your error log here>
```
- <public link of unexpected result if you have>

#### Expected results
<Describe what to actually do>

### Reproducible project / your project
- <link to your project, or attach zipped small project sample>

### Environment info
- OS: <Unix/Linux/Mac/Win/other with version>
- Python version:
- Sphinx version:
- <Extra tools e.g.: Browser, tex or something else>

**Comment by tk0miya** [comment]
It seems your error is raised by recommonmark. So this error is related with recommonmark, not sphinx-core.
Please report this to their project.
Thanks,
