### ISSUE TITLE
Refactor links on Examples page

### ISSUE THREAD

**Issue by TimKam** [sphinx-doc/sphinx#5278]
As discussed in #5259: I think it would be nice to use properly formatted links instead of raw URLs at http://www.sphinx-doc.org/en/master/examples.html.
If there are no objections, I re-format all links there, i.e.:

```
Alabaster: https://alabaster.readthedocs.io/
```
->

```
`Alabaster`__

__ https://alabaster.readthedocs.io/
```
and so on.

**Comment by tk0miya** [comment]
+1
