### ISSUE TITLE
"document isn't included in any toctree" warning even when document is linked

### ISSUE THREAD

**Issue by aspiers** [sphinx-doc/sphinx#5281]
### Problem

A `document isn't included in any toctree` warning is issued even when a document missing from all `toctree`s is linked from another document one of the `toctree`s.

### Procedure to reproduce the problem

Set up a Sphinx tree where one file is only referenced from `index.rst` or another file in the `toctree` via a `:doc:` hyperlink, and is not included or referenced within a `toctree`.

Then run a Sphinx build to see the warning.

For example, removing the `:orphan:` line from the top of this file:

https://review.openstack.org/#/c/590406/7/CONTRIBUTING.rst

will trigger the issue.

### Expected results

If a document file is linked from a non-orphan, then it is reachable from the root document and therefore not an orphan.  So it does not necessarily make sense to warn that it is unreachable via a `toctree`.

This is very similar to [Suppress "document isn't included in any toctree" warning if the document is included (#2605)](https://github.com/sphinx-doc/sphinx/pull/2605), except it's for internal links rather than `include` directives.

### Reproducible project

- https://review.openstack.org/#/c/590406/7/
- https://git.openstack.org/cgit/openstack/self-healing-sig/commit/?id=0a1d4929967cc772b3f57181b975cd50c76d9a82

### Environment info

- OS: openSUSE Leap 15.0
- Python version: 2.7.14
- Sphinx version: 1.7.6

**Comment by tk0miya** [comment]
Certainly, we can follow the document via hyperlink in HTML output. But it is not available for other formats. For example, in LaTeX output, the hyperlink will get broken.
So I think `:orphan:` mark is needed for this case.

**Comment by aspiers** [comment]
That's a good point although LaTeX can output to PDF which supports hyperlinks.  But yes, if outputting to formats which don't support hyperlinks then the warning should be preserved.

**Comment by tk0miya** [comment]
"orphaned" means the document is not contained in the toctree. It does not equal to not hyper-referenced. So I'd not like to suppress the warning because it is still orphaned even if referenced.

In orphaned page, some navigation links are broken even if HTML output. Because it does not have "next" page, "prev" page and parent tree.

**Comment by aspiers** [comment]
[**@tk0miya**](https://github.com/tk0miya) commented on [2 Sep 2018, 10:21 BST](https://github.com/sphinx-doc/sphinx/issues/5281#issuecomment-417916479 "2018-09-02T09:21:13Z - Replied by Github Reply Comments"):
> "orphaned" means the document is not contained in the toctree. It does not equal to not hyper-referenced.

That's one valid definition of "orphaned", but not necessarily the most obvious to everyone.  Another is that it means the document is not reachable by navigating via any links from the starting point (index / entry point). 

> So I'd not like to suppress the warning because it is still orphaned even if referenced.

It's fine to have the warning, but it would be good if it was clearer about the meaning of "orphaned", and even better if it spotted that the document was hyperlinked from elsewhere and mentioned that in the warning, so that people can more easily judge whether that is good enough for them.

Thanks!
