### ISSUE TITLE
Prefer source over installed egg

### ISSUE THREAD

**Issue by Syndace** [sphinx-doc/sphinx#5290]
Subject: Sphinx tries to get the source from an installed egg instead of the source directory and fails.

### Problem
Sphinx tries to load the source code for the viewcode extension and for the bysource member-order. Usually, the user points sphinx to the sources (using sys.path) and sphinx extracts the sources directly from this directory. If an egg is installed (e.g. using pip), sphinx tries to extract the sources from this egg instead of the actual source directory. If the egg is zipped, this attempt will fail. Deleting the egg by hand will make sphinx use the actual sources again.

#### Procedure to reproduce the problem
Set up a simple python project with a `setup.py` and make sure to set the `zip_safe` flag to `True`. Run `setup.py install`. Try to generate the sphinx documentation, using the `autodoc` and `viewcode` extensions. The source links will not be generated and using `-vv` the error stated below can be found in the logs. Now, delete the egg manually and try to generate the documentation again. This time the source links will be intact and no errors are in the log.

#### Error logs / results
```
[autodoc] module analyzer failed: source file is not present: '/home/user/.local/lib/python3.5/site-packages/Test-0.1.0-py3.5.egg/test/test.py'
```

#### Expected results
Sphinx should prefer the source directory over an installed egg or it should attempt to unpack the egg if it is zipped. Whatever works.

### Environment info
- OS: Linux
- Python version: 3.5
- Sphinx version: sphinx-build has version 1.7.6

Sorry if this has been reported before, I did a quick search and did not find anything.

**Comment by tk0miya** [comment]
-1: AFAIK, pypa said good-bye to .egg package. So I think no reason to support it from now on.

**Comment by Syndace** [comment]
At least python3.5 (the most recent python version in debian stable) uses eggs all over the place. Just `ls` your `site-packages` and see that it's full of eggs.

This issue is not specific to eggs aswell. Even if there is any other packaging mechanism the problem will persist, as long as sphinx looks at installed packages instead of the sources it is pointed to.

**Comment by tk0miya** [comment]
Could you share any example? I'd like to investigate it in detail.
On my local (docker images), I can't find any egg packages on debian stable. I know they contains .egg file. But they are not archive files.

**Comment by tk0miya** [comment]
I found setuptools uses .egg file. So we can see it with `python setup.py install`.
I perfectly reproduce this problem.

+1; we need to support it. It is still used...

**Comment by Syndace** [comment]
Oh damn, sorry for not answering. Exactly, I'm using the most recent version of setuptools. Just a super simple setup.py file (with zip_safe=True) creates a zipped egg file when calling `setup.py install`.

Glad you can reproduce.

**Comment by tk0miya** [comment]
I just made a PR #5290 for this problem.
Please try this on your document if you have time.

**Comment by Syndace** [comment]
Nice, this indeed fixes the issue. Thank you!

I don't want to annoy you but don't you think it would be more future-safe to always try to read the sources first, falling back to the installed package only if no sources are found in the path?
I mean, if Python ever decides to do a different package format using for example tar.gz instead of zip you got the same problem again.

Anyway, thanks for that fast reaction, I hope to see the release containing this PR soon!

**Comment by Syndace** [comment]
Actually, nevermind. You'd have to support it anyway, whether you would look for sources first or not doesn't matter.

Again, thanks.

**Comment by tk0miya** [comment]
Thank you for comment. I'll go with this.
Let's consider again if something happened :-)
