### ISSUE TITLE
math_number_all = True causes equations to have two numbers in html

### ISSUE THREAD

**Issue by certik** [sphinx-doc/sphinx#5298]
### Problem
When using the following configuration in `conf.py`:
```
imgmath_image_format = 'svg'
imgmath_dvisvgm_args = ['--no-fonts', '--exact']
math_number_all = True
math_numfig = True
numfig = True
numfig_secnum_depth = 3
```

All equations suddenly have 2 numbers. A latex generated number `(1)`, and an html generated number (which is correct):

![screenshot_2018-08-13 3 2 complex numbers theoretical physics reference 0 5 documentation](https://user-images.githubusercontent.com/20568/44062326-1525df84-9f19-11e8-94b9-b888acec6371.png)

The html generated one is correct, the latex generated number `(1)` should be removed.

When I use a pdf output, then all equations have just one number (the correct one).

#### Procedure to reproduce the problem
Put this into your `conf.py` and use some math:
```
imgmath_image_format = 'svg'
imgmath_dvisvgm_args = ['--no-fonts', '--exact']
math_number_all = True
math_numfig = True
numfig = True
numfig_secnum_depth = 3
```

### Reproducible project / your project
- https://github.com/certik/theoretical-physics

### Environment info
- OS: Ubuntu 16.04
- Python version: 3.7.0
- Sphinx version: 1.7.6

**Comment by certik** [comment]
It turns out, this is caused by the `math_number_all = True` flag. If I disable it, then it fixes the problem. But of course, not all equations are labeled anymore.

**Comment by tk0miya** [comment]
Fixed by #5304.
Thank you for reporting.

**Comment by certik** [comment]
Thank you @tk0miya, much appreciate the quick fix!

**Comment by certik** [comment]
I tested it and it works, as of the commit 11331c59230cba17d78b5668bcb6193ba7e9dbe0.
