### ISSUE TITLE
C++ domain does not like namespaced friends

### ISSUE THREAD

**Issue by mquinson** [sphinx-doc/sphinx#5316]
Some of my classes declare friend relationship with classes that are in the same namespace. Using the short name (without repeating the namespaces) seem to mess up sphinx with the following error message:
```
/builds/simgrid/simgrid/docs/source/api/classsimgrid_1_1s4u_1_1Comm.rst:22: WARNING: Invalid definition: Expected identifier in nested name, got keyword: friend [error at 6]
  friend simgrid::s4u::Comm::Mailbox
  ------^
```

Here is the content of that `classsimgrid_1_1s4u_1_1Comm.rst` file (generated by exhale):
```
.. _exhale_class_classsimgrid_1_1s4u_1_1Comm:

Class Comm
==========

- Defined in :ref:`file__home_mquinson_Code_simgrid_include_simgrid_s4u_Comm.hpp`


Inheritance Relationships
-------------------------

Base Type
*********

- ``public simgrid::s4u::Activity`` (:ref:`exhale_class_classsimgrid_1_1s4u_1_1Activity`)


Class Documentation
-------------------


.. doxygenclass:: simgrid::s4u::Comm
   :members:
   :protected-members:
   :undoc-members:
```

The relevant source code is here:
https://framagit.org/simgrid/simgrid/blob/master/include/simgrid/s4u/Comm.hpp#L21

```
namespace simgrid { 
namespace s4u {
class Comm : public Activity {   
   Comm() : Activity() {} 
public:
   friend XBT_PUBLIC void intrusive_ptr_release(simgrid::s4u::Comm * c);
   friend XBT_PUBLIC void intrusive_ptr_add_ref(simgrid::s4u::Comm * c);
   friend Mailbox; // Factory of comms
...
```

Note that the error message is speaking of `simgrid::s4u::Comm::Mailbox` while the class is actually `simgrid::s4u::Mailbox`: that's not a inner class, but another class of the same namespace.

If I give the full namespace path `friend simgrid::s4u::Mailbox`, the warning disappears of my logs.

**Comment by jakobandersen** [comment]
I think this is a problem with how Breathe handles friend declarations. The error is indeed from Sphinx, and relates only to parsing. If I remember correctly there has been an issue with Breathe assuming all friend declarations are for functions, which could explain part of the issue. Though I don't know why fully qualifying the name seems to help.
Note also that Sphinx has no dedicated support for friend classes, as they can never (to my understanding) define a new class, only reference another one (which can be handled by cross-references).

**Comment by mquinson** [comment]
Sorry if I miss-filled this issue against sphinx while the error is in breathe. 

I can confirm that fully qualifying all my friend classes actually remove the problem.

BTW, I'm using the Debian version of things:
ii  breathe-doc                       4.9.1-1      all          Sphinx autodox support for languages with doxygen support (documentation)
ii  libjs-sphinxdoc                   1.7.6-1      all          JavaScript support for Sphinx documentation
ii  python-sphinx                     1.7.6-1      all          documentation generator for Python projects (implemented in Python 2)
ii  python-sphinx-rtd-theme           0.4.0+dfsg-1 all          sphinx theme from readthedocs.org (Python 2)
ii  python3-breathe                   4.9.1-1      all          Sphinx autodox support for languages with doxygen support (Python 3)
ii  python3-sphinx                    1.7.6-1      all          documentation generator for Python projects (implemented in Python 3)
ii  python3-sphinx-rtd-theme          0.4.0+dfsg-1 all          sphinx theme from readthedocs.org (Python 3)
ii  sphinx-common                     1.7.6-1      all          documentation generator for Python projects - common data
ii  sphinx-intl                       0.9.11-2     amd64        translation support utility for Sphinx
ii  sphinx-rtd-theme-common           0.4.0+dfsg-1 all          sphinx theme from readthedocs.org (common files)
