### ISSUE TITLE
"indexer" command doesn't get found

### ISSUE THREAD

**Issue by GildedHonour** [sphinx-doc/sphinx#5319]
Linux:

`apt-get install python3-sphinx`

After installing it, the command "indexer" from my "conf" file:

```
indexer
{
}

searchd
{
//.........

```

doesn't get found. Why not?

`sh: 1: indexer: not found
`

**Comment by tk0miya** [comment]
Parhaps, do you want Sphinx-search? If true, this package is not. This is a documentation tool.
http://www.sphinx-doc.org/en/master/

**Comment by tk0miya** [comment]
I'm closing this now because this is not a bug of Sphinx.
Thanks,
