### ISSUE TITLE
trim_footnotes_reference_space has no effect

### ISSUE THREAD

**Issue by juh2** [sphinx-doc/sphinx#5338]
Subject: 

The configuration value trim_footnotes_reference_space has no effect in Sphinx 1.7.6 and 1.8.0b1

### Problem
- When I set a footnote like this [#]_ there is a space between the reference number and the text. From the documentation I guess that setting trim_footnotes_reference_space to True should trim the space.

- I have to trim the space with a backslash before the space `\ [#]_` 

#### Procedure to reproduce the problem

in conf.py:

```
trim_footnotes_reference_space = True
```

In a document:

```
foo bar [#]_

lorem ipsum

.. [#] footnote text


### Environment info
- OS: Debian 4.9.110-3+deb9u3
- Python version: 3.5.3
- Sphinx version: 1.7.6 and 1.8.0b1

**Comment by tk0miya** [comment]
Please use `trim_*footnote*_reference_space` instead (footnote is singular).
http://www.sphinx-doc.org/en/master/usage/configuration.html#confval-trim_footnote_reference_space

**Comment by tk0miya** [comment]
I'm closing this because this is not a bug of Sphinx.
Thanks,
