### ISSUE TITLE
Selectively ignoring changes to conf.py when deciding what to rebuild

### ISSUE THREAD

**Issue by anntzer** [sphinx-doc/sphinx#5341]
Subject: Selectively ignoring changes to conf.py when deciding what to rebuild

### Problem
Currently, if sphinx detects that a value has changed in conf.py (compared to the previous run), it invalidates the entire previous environment and rebuilds the whole thing from scratch.  For a project such as Matplotlib, a doc build can easily take 5-10min, so I'd like to avoid spurious rebuilds when developing locally.  However, Matplotlib also derives the `version` value of the config from the git hash of the repo, which means that each new commit will trigger a full rebuild.

What would happen if we could tell sphinx "if you see that `version` changed (but nothing else) in conf.py", then don't invalidate the tree, and just do the normal thing of only rebuilding the new files?  Well, this would mean that some old files will display the wrong version, but that's acceptable for me (this is for local development only anyways).  I would thus like to suggest adding a way to say, "ignore changes to this, this and this variable when deciding what to rebuild".

Of course, this could go to conf.py, but that seems a bit recursive and importantly not so useful when you only want to do this locally, not on CI; so a better option may be to introduce an environment variable, e.g.`SPHINX_IGNORE_CONF_CHANGES=foo,bar`.  I don't think the change is particularly complicated in itself (likely just involves patching `BuildEnvironment._update_config + documenting it), so I'm mostly just asking here how the devs think about it.

#### Procedure to reproduce the problem
Build the matplotlib docs from a git clone of the repo, add a new local commit touching only one file, try to rebuild them and note that we get a full rebuild rather than having only that one file being invalidated.

#### Error logs / results
N/A

#### Expected results
See "Problem".

### Reproducible project / your project
N/A

### Environment info
- Sphinx: 1.7.7
- other: N/A

**Comment by tk0miya** [comment]
How about giving an option like `-D version=""`? It forcedly overrides the variable. So Sphinx would not rebuild the document even after committed.
Another way, you can give git hash as the version only on CI: ```-D version=`git rev-parse HEAD` ```.

**Comment by anntzer** [comment]
Ah, that looks good.  Thanks, sorry for the noise.
