### ISSUE TITLE
Any snippets source for Sphinx documentation.

### ISSUE THREAD

**Issue by ofenerci** [sphinx-doc/sphinx#5355]
I wonder  there are any snippets to speed the writing of sphinx documents. Although those snippets are editor specific, we  may adapt those into other editors.

**Comment by tk0miya** [comment]
I think sphinx-users is much better to post such topic.
https://groups.google.com/forum/#!forum/sphinx-users

Thanks,

**Comment by ofenerci** [comment]
Done.
