### ISSUE TITLE
If module named "modules",it will get wrong content

### ISSUE THREAD

**Issue by ghost** [sphinx-doc/sphinx#5362]
### Problem
If module named **"modules"**,it will got wrong content.

```
dev
===

.. toctree::
   :maxdepth: 4

   conf
   handlers
```

Title **"dev"** is the directory name which I want to using sphinx to generating API documentation.

**"conf"** / **"handlers"** and **"modules"** in the same directory(**"dev"**).Directory structure like:

```
dev
├── conf
│   ├── a
│   └── b
├── handlers
│   ├── c
│   └── d
├── modules
│   ├── e
│   └── f
```
 
But,if rename "modules" to "module",it will work fine:

```
module package
==============

Submodules
----------

module.e
---------------------------

.. automodule:: module.e
    :members:
    :undoc-members:
    :show-inheritance:
```

#### Expected results
Do it no matter module's name.

### Reproducible project / your project
Make a directory named **"modules"**,and using **sphinx-apidoc** command to parsing it.

### Environment info
- OS: Ubuntu18.04 LTS
- Python version:3.6.5
- Sphinx version:1.7.8

**Comment by tk0miya** [comment]
This is minimum reproducible steps:
```
$ ls
$ touch modules.py
$ sphinx-apidoc -o docs .
Creating file docs/modules.rst.
File docs/modules.rst already exists, skipping.
```

`modules.rst` is a default filename of index file which apidoc generates. So it is conflicted with target python module.

**Comment by tk0miya** [comment]
I just added `--tocfile` option for renaming `modules.rst` (see #5375).
Thank you for reporting!
