### ISSUE TITLE
Signature overrides for autodoc via automethod cause wrong order

### ISSUE THREAD

**Issue by torfsen** [sphinx-doc/sphinx#5364]
### Problem
I'm using `automethod` to override the signature of a method that is actually a callable instance of another class. Overriding the signature works fine, but causes the method to show up at the top of the class' documentation instead of its place in the alphabetical ordering.

Here's the Python source (`stest.py`):

```python
class FakeMethod(object):
    '''
    Documentation of FakeMethod
    '''
    def __call__(self):
        '''
        Documentation of FakeMethod.__call__
        '''
        print("I'm a fake method of {}!".format(self))


class Test(object):
    '''
    Documentation of Test

    Try :py:meth:`fake_method` or :py:meth:`real_method`!
    '''
    def another_method(self):
        '''Documentation of Test.another_method'''

    #: Documentation of Test.fake_method
    fake_method = FakeMethod()

    def real_method(self):
        '''Documentation of Test.real_method'''
```

And here's the reST:

```rst
.. autoclass:: stest.Test
    :members:
    :exclude-members: fake_method

    .. automethod:: fake_method()
```

I'm using `:exclude-members:` as [a workaround](https://github.com/sphinx-doc/sphinx/issues/1881#issuecomment-259644309) for #1881 (otherwise I get two entries for `fake_method` in the documentation, one for the original attribute and one for the automethod).

In the generated HTML, the overriding of `fake_method`'s signature works fine, but `fake_method` is listed as the first method instead of its correct second place according to the alphabetical order:

![image](https://user-images.githubusercontent.com/2877717/44799428-3109f800-abb4-11e8-9a8c-7154ac325a2d.png)

If I omit the `:exclude-members:` option then the entry for the original attribute shows up at the correct place:

![image](https://user-images.githubusercontent.com/2877717/44799517-63b3f080-abb4-11e8-96f1-c8d34e19f784.png)

I've tried specifying the signature in the first line of the docstring of `fake_method` instead of using `automethod` (as suggested [here](https://github.com/sphinx-doc/sphinx/issues/1881#issuecomment-100240702)), but that doesn't seem to work (perhaps because `fake_method` is not a real method?):

```python
    #: fake_method()
    #:
    #: Documentation of Test.fake_method
    fake_method = FakeMethod()
```

only results in

![image](https://user-images.githubusercontent.com/2877717/44799770-08363280-abb5-11e8-96e0-ed5578832206.png)

#### Expected results

I would like `fake_method` to be listed in the correct place according to alphabetical order but with the signature provided via `automethod`, or I would like to be able to override the signature of `fake_method` in `fake_method`'s docstring as suggested [here](https://github.com/sphinx-doc/sphinx/issues/1881#issuecomment-100240702).

### Environment info
- OS: Debian 8.6
- Python version: 2.7.9
- Sphinx version: 1.7.8

**Comment by tk0miya** [comment]
Unfortunately, autodoc only **appends** generated document after its contents part.
So all methods and attributes are listed after `.. automethod:: fake_method()`.

**Comment by torfsen** [comment]
Thank you @tk0miya for your quick response! So I guess this is simply the intended behavior. Unfortunate for my use case, but good to know. Thanks again!
