### ISSUE TITLE
Could not import extension sphinx.builders.linkcheck

### ISSUE THREAD

**Issue by petarnikolovski** [sphinx-doc/sphinx#5366]
Subject: Cannot build documentation: No module named `requests.exception`

### Problem

When I install the most recent sphinx version in a new project (1.7.8) and uncomment the module import in `conf.py` documentation build fails.

#### Procedure to reproduce the problem

Uncomment and change source directory of the project in `conf.py`:

```python
import os
import sys
sys.path.insert(0, os.path.abspath('../mylib'))
```

```
make html
```

#### Error logs / results
```
Running Sphinx v1.7.8

Extension error:
Could not import extension sphinx.builders.linkcheck (exception: No module named 'requests.exceptions'; 'requests' is not a package)
Makefile:20: recipe for target 'html' failed
make: *** [html] Error 2
```

#### Expected results

Documentation build successful.

### Environment info
- OS: Ubuntu 16.04
- Python version: 3.5
- Sphinx version: 1.7.8
- Sphinx installed using **pipenv (2018.7.1)**
- I use the official **requests** library in my package, and also I have a submodule on path `mylib.requests`
- Extensions used: 'sphinx.ext.autodoc', 'sphinx.ext.coverage'

**Comment by tk0miya** [comment]
It seems `requests.exceptions` package is missing on your environment. Could you check it please?
If you're using `python-requests` package on debian or ubuntu, they are broken to us. If true, please reinstall it via pip.

Thanks,

**Comment by petarnikolovski** [comment]
My project is initiated with pipenv and it's using Python 3.5. The package `python-requests` is globally installed:

```bash
sudo apt list --installed | grep request

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

python3-requests/xenial,xenial,now 2.9.1-3 all [installed]
```

but in the projects I've installed it using:

```bash
pipenv install requests
```

Sphinx is also installed locally in the pipenv's virtualenv too, but is it trying to use the global requests package?

Also, if I drop down to virtualenv in the project, the following imports work fine:

```bash
pipenv shell
python -c 'import requests'
python -c 'import requests.exceptions'
```

Furthermore, if I start new project, and use the same version of requests and sphinx (both installed with pipenv) `make html` does not fail when I enable:

```
import os
import sys
sys.path.insert(0, os.path.abspath('../dummylib'))
```

in `conf/py`

**Comment by tk0miya** [comment]
Hmm... I can't find why `requests` is not a package on your environment. I have no idea to fix it.

**Comment by petarnikolovski** [comment]
I've removed and reinstalled `python3-requests` using pip, and the error is still happening. I've seen other issue reports where the cause of error was mocking of `requests` in `conf.py`. I'm not mocking `requests` in that file, but in my unit tests, I'm specifically mocking `requests.get` and `requests.post`. But tests are in a separate directory. I'll let you know if I find the fix.

**Comment by petarnikolovski** [comment]
If I change

`sys.path.insert(0, os.path.abspath('../mylib'))`

to:

sys.path.insert(0, os.path.abspath('../'))

The documentation compiles! However, `../` contains library, tests, documentation, etc. I'm not sure why it compiles like this, and it makes me uneasy to set the path to root of the project rather then the root of the library itself.

**Comment by tk0miya** [comment]
I don't know what `mylib` contains. But that is related with this issue. Is there a `requests` package on your library?
Anyway, this must be not a bug of Sphinx. So I'm closing this now.

If you want a help more, please post this again to sphinx-users list:
https://groups.google.com/forum/#!forum/sphinx-users

Thanks,

**Comment by petarnikolovski** [comment]
Yes, there is one `import requests` and one `requests.py` file. It may be the filename in the package that caused the problem.

**Comment by tk0miya** [comment]
I understand. It causes your problem. Sphinx uses `requests` package internally. So they are conflicted.
Unfortunately, I don't have good workaround for your case.
