### ISSUE TITLE
code-block directive without language should cause error, not warning

### ISSUE THREAD

**Issue by mgeier** [sphinx-doc/sphinx#5407]
### Problem
- If a `code-block` directive is missing the (AFAIK required) language option, it is not included in the output and only a warning is shown instead of an error.

#### Procedure to reproduce the problem

```
.. code-block::

    a = 15
```

#### Error logs / results
```
WARNING: Error in "code-block" directive:
1 argument(s) required, 0 supplied.

.. code-block::

    a = 15
```

#### Expected results

There should be an error message, because IMHO completely stripping the code block is a strong failure.

#### Possibly related issues
#1851
#4130

**Comment by mgeier** [comment]
Alternatively, instead of completely removing the `code-block`, it could be formatted with some default language setting (or without syntax highlighting at all). In that case, IMHO a warning would suffice.

**Comment by tk0miya** [comment]
I think #1851 is a good way to do that.

**Comment by tk0miya** [comment]
I'm closing this because of duplicated.
Thanks,
