### ISSUE TITLE
Parsing of IDNA-encodable URLs

### ISSUE THREAD

**Issue by funkyfuture** [sphinx-doc/sphinx#5416]
### Problem

i'm using URLs that contain non-ascii characters as part of the domain name with different roles in documents, mainly standalone URLs. these are not parsed in their completeness, e.g. `https://die-fpö-ist-ein-reaktionärer-misthaufen.at` is matched as `https://die`.

it is quiet simple to fix that behaviour by changing `Inliner.uric` in `docutils.parsers.rst.states.py#671`. is there an elegant way i can incorporate that into Sphinx, so i can provide a patch? the only approach that i see atm would be to change that property at import or runtime. the latter would probably allow that value to be configured which seems reasonable. afaict there's hardly a generally usable character set for that purpose.

i don't think docutils or Sphinx should encode such occurances with the idna codec as i think this is the responsibility of the consuming software.

**Comment by tk0miya** [comment]
I think it is responsibility of docutils. So it would be better to send the patch to docutils project.
Thanks,

**Comment by tk0miya** [comment]
I'm closing this now.
Thank you for proposal.

**Comment by funkyfuture** [comment]
i doubt that a general solution is easy to achieve with the docutils maintainers, i certainly don't have the time for trying so.

for those who may seek advice in a similar situation, it's quiet simple to mock the value in question in a project's `conf.py`, e.g.:

```python
from docutils.parsers.rst.states import Inliner
Inliner.uric = Inliner.uric.replace('a-z', 'a-zäöüß')
```
