### ISSUE TITLE
Incorrect default path for sphinx-build -d/doctrees files

### ISSUE THREAD

**Issue by zeroepoch** [sphinx-doc/sphinx#5418]
https://github.com/sphinx-doc/sphinx/blob/efdc95ef8b041a90096d43144fad7086b1f93cc9/sphinx/cmd/build.py#L222

This should be using `args.outputdir` instead of `args.sourcedir` according to the usage.  This causes our build to fail now with 1.8 because our source tree is read-only.  We started adding -d to the command line to workaround the issue.

**Comment by tk0miya** [comment]
Thank you for letting us know. Yes, the line is wrong.

Note: This bug was added in #4436.

**Comment by tk0miya** [comment]
Fixed by #5425 
Thank you for reporting!
