### ISSUE TITLE
'function based directive support is now deprecated' could be more helpful

### ISSUE THREAD

**Issue by svenevs** [sphinx-doc/sphinx#5438]
Subject: I would like to make understanding a deprecation notice a little easier for future users.

### Problem

```
sphinx/util/docutils.py:272: RemovedInSphinx30Warning: function based directive support is now deprecated.
Use class based directive instead.
```

For reference, we're talking about this specific code:

https://github.com/sphinx-doc/sphinx/blob/2e9d311ad51d0a1f622b38b301a8d10746b84878/sphinx/util/docutils.py#L268-L272

There's nothing _wrong_ with the deprecation message itself.  Finding what to do or what is causing it is what was difficult _for me_ (disclaimer: I'm a directive n00b).

#### Procedure to reproduce the problem

Use `breathe` with 1.8.

#### Proposed options ready for PR with counsel

1. I added the `stacklevel` optional parameter for [`warnings.warn`](https://docs.python.org/3/library/warnings.html#warnings.warn) function.  I was able to discern where the problem was after setting `stacklevel=3`.  Would that be a reasonable thing to add in a pull request?  `1` is the default, `2` seemed to be something from sphinx, `3` is what got me to `breathe`.

    It doesn't really seem like `stacklevel` is used anywhere else though, so that's kind of imbalanced.

2. In the [changelog for 1.8.0 beta1](http://www.sphinx-doc.org/en/master/changes.html#release-1-8-0-beta1-in-development), it states

    > Drop function based directive support. For now, Sphinx only supports class based directives.

    This was easy enough to find from the code deprecation message.  But `directive` is kind of hard to search for in the docs.  In addition to _or_ instead of (1), j ust add a link to [`docutils.parsers.rst.Directive`](http://www.sphinx-doc.org/en/master/extdev/markupapi.html#docutils.parsers.rst.Directive), is this correct?

    Are there any other "class based directives" _besides_ `docutils.parsers.rst.Directive` that can work that should be linked?

I'm happy to add a PR with advice.  In my opinion (2) should be sufficient.  I just don't know if there are alternatives that should be mentioned as well.

**Comment by tk0miya** [comment]
Thank you for comment.

I think both (1) and (2) is good to me. Could you send us a PR please?

Note: we're listing deprecated APIs in http://www.sphinx-doc.org/en/master/extdev/index.html#deprecated-apis . So it would be better to fix it as (2).

**Comment by tk0miya** [comment]
Note: I post a PR for (1) in #5532.

**Comment by tk0miya** [comment]
I did the case (2) in #5542.

**Comment by tk0miya** [comment]
I'm closing this because this would be closed soon.
Thank you for reporting!
