### ISSUE TITLE
Error exportion

### ISSUE THREAD

**Issue by apacph** [sphinx-doc/sphinx#5444]
Subject: 
- Error exception when execute make html

### Problem
- Originally, my sphinx environment is work fine. 
- However, I want to draw a venn diagram in my document.
- I tried to install sphinxcontrib.googlechart.
- Also, I modified my conf.py by adding extensions = ['sphinxcontrib.googlechart', 'sphinxcontrib.googlechart.graphviz']
- I found that I cannot successfully make my html through command line. 
- Maybe I've some trouble with conf.py configuration.

#### Procedure to reproduce the problem
```
pip install sphinxcontrib.googlechart
make html
```

#### Error logs / results
```
# Sphinx version: 1.7.6
# Python version: 3.6.3 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "c:\Python3632\lib\site-packages\sphinx\cmdline.py", line 303, in main
    args.warningiserror, args.tags, args.verbosity, args.jobs)
  File "c:\Python3632\lib\site-packages\sphinx\application.py", line 191, in __init__
    self.setup_extension(extension)
  File "c:\Python3632\lib\site-packages\sphinx\application.py", line 411, in setup_extension
    self.registry.load_extension(self, extname)
  File "c:\Python3632\lib\site-packages\sphinx\registry.py", line 315, in load_extension
    mod = __import__(extname, None, None, ['setup'])
  File "c:\Python3632\lib\site-packages\sphinxcontrib\googlechart\__init__.py", line 178
    except Exception, e:
                    ^
SyntaxError: invalid syntax

```
- <public link of unexpected result if you have>

#### Expected results
successfully execute 'make html' command

### Reproducible project / your project
- <link to your project, or attach zipped small project sample>

### Environment info
- OS: Win 10
- Python version: v3.6.3 32-bit
- Sphinx version: v1.7.6
- Browser: Chrome

**Comment by tk0miya** [comment]
Simply, the extension does not support py2.
Please report this to their project. I'll take a look later (I'm author of the module!).

Thanks,
