### ISSUE TITLE
VPATH (out of source) builds

### ISSUE THREAD

**Issue by dilyanpalauzov** [sphinx-doc/sphinx#5491]
Autotools and other build systems allow out VPATH (out of source) builds.  During such a build some .rst files are generated in the builddir, others are in the sourcedir.  The compiled documentation must include both files.

How to achieve this with sphinx-build?

**Comment by chopperg** [comment]
M3W6+V4 Fieldale, Virginia

**Comment by tk0miya** [comment]
Sphinx only supports files on source directory. So I propose you to move them to source directory before running sphinx-build.
