### ISSUE TITLE
warning when build

### ISSUE THREAD

**Issue by wqh17101** [sphinx-doc/sphinx#5494]
Subject: warning when build

### Problem
- warning when build

#### Procedure to reproduce the problem
```
.. MatchZoo documentation master file, created by
   sphinx-quickstart on Mon May 28 16:40:41 2018.
   You can adapt this file completely to your liking, but it should at least
   contain the root `toctree` directive.

Welcome to MatchZoo's documentation!
====================================
.. toctree::
   :maxdepth: 2
   :caption: API Document:

   matchzoo

Indices and tables
==================

* :ref:`genindex`
* :ref:`modindex`
* :ref:`search`

```

#### Error logs / results

![image](https://user-images.githubusercontent.com/26429138/46131518-6fa3d880-c26e-11e8-9328-a967bff09ee8.png)

#### Expected results
no warning

### Environment info
- OS: Win
- Python version: 3.6
- Sphinx version: 1.8.1

**Comment by tk0miya** [comment]
I guess your translation catalog was broken.
Could you check it first please?

**Comment by wqh17101** [comment]
how to do it @tk0miya

**Comment by wqh17101** [comment]
No problem with 1.7.9 sphinx

**Comment by tk0miya** [comment]
I'm closing this now.
Please feel free to reopen if you're still in trouble.
Thanks,
