### ISSUE TITLE
Do not include MathJax.js unless it is really needed

### ISSUE THREAD

**Issue by mitya57** [sphinx-doc/sphinx#5497]
When a project does not have any math directives or roles, still every HTML page has this tag when built with Sphinx 1.8:
```html
<script async="async" type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
```

This is unwanted, and did not happen with Sphinx 1.7.

It would be nice if the tag was included only when the page (or the project as a whole) has a math directive or role.

**Comment by tk0miya** [comment]
+1; reasonable.

**Comment by tk0miya** [comment]
Fixed by #5536 
Thank you for reporting!

**Comment by mitya57** [comment]
Wow, thanks a lot!

**Comment by jabl** [comment]
Would it be possible to only include the mathjax js script on a per-page basis? While #5536 is an improvement, it still seems that even if only one page in the build contains math, mathjax is included in every page.

In our case, we have 1 page that needs math, and 167 that don't. And mathjax is huuuuge..

**Comment by tk0miya** [comment]
@jabl That is not easy, but maybe possible. Could you file a new issue please? I'll try it in future version.

**Comment by NateZimmer** [comment]
Something about this does not operate well. I clearly got math in my docs but randomly mathjax isn't included. This seems to occur when I update the conf.py but I don't edit the .rst files. When I edit a .rst file it fixes itself.

**Comment by tk0miya** [comment]
@NateZimmer I guess it might be a bug of incremental build. Could you file an issue with detailed procedure please? I'll take a look later.
