### ISSUE TITLE
build should not unconditionally rewrite pickle file

### ISSUE THREAD

**Issue by eqvinox** [sphinx-doc/sphinx#5501]
Starting as of 1.8.0, with the change in commit 20f625b4d39d0e981b4922f629212acc74271665, sphinx-build unconditionally writes the `environment.pickle` file.  This breaks the build system expectation that a
`-b pickle` run can be done first, and then various output formats can be built off that file.

Before the above commit, the timestamp of the pickle file could be compared against an output format's timestamp to determine whether it is out of date; now it's always out of date since it keeps getting rewritten.

Reference build system integration: https://github.com/FRRouting/frr/blob/master/doc/subdir.am#L32 (uses text instead of pickle to support older sphinx versions)

**Comment by eqvinox** [comment]
(sorry, forgot mention @blueyed for commit relation)

**Comment by tk0miya** [comment]
#5525 is merged now.
Thanks,

Note: I opened #5594 for the original issue of 20f625b.
