### ISSUE TITLE
allow linkcheck to tolerate transient HTTP 503 errors

### ISSUE THREAD

**Issue by jab** [sphinx-doc/sphinx#5502]
I have a link in my docs to https://www.python.org/dev/peps/pep-0020/, which just happened to have been giving 503 errors when my daily Travis build ran this morning, causing my build to fail. I know I can configure `linkcheck_ignore` so that broken links matching specified URL patterns are ignored, but that wouldn't help here, since I want to be able to only warn (not fail) on *any* link giving a 503 error, but still have any link fail on e.g. 404 responses.

**Comment by tk0miya** [comment]
Fixed by #6427.
Thank you for reporting.
