### ISSUE TITLE
On sphinx-doc.org, we should use https:

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#5522]
For now, http://www.sphinx-doc.org/ doesn't support HTTPS.

If we change the settings of ReadTheDocs and CNAME settings, it seems that we can use HTTPS.
ref: https://docs.readthedocs.io/en/latest/alternate_domains.html

**Comment by shimizukawa** [comment]
@birkenfeld Please change the www.sphinx-doc.org domain CNAME

- current: `sphinx.readthedocs.org`
- To Be: `readthedocs.io`

ref: https://docs.readthedocs.io/en/latest/alternate_domains.html

**Comment by shimizukawa** [comment]
Now `www.sphinx-doc.org` point to `readthedocs.io`
```
$ dig  www.sphinx-doc.org

; <<>> DiG 9.8.3-P1 <<>> www.sphinx-doc.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 18608
;; flags: qr rd ra; QUERY: 1, ANSWER: 6, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;www.sphinx-doc.org.		IN	A

;; ANSWER SECTION:
www.sphinx-doc.org.	3600	IN	CNAME	readthedocs.io.
readthedocs.io.		300	IN	A	104.18.230.122
readthedocs.io.		300	IN	A	104.18.229.122
readthedocs.io.		300	IN	A	104.18.231.122
readthedocs.io.		300	IN	A	104.18.227.122
readthedocs.io.		300	IN	A	104.18.228.122

;; Query time: 380 msec
;; SERVER: 192.168.43.1#53(192.168.43.1)
;; WHEN: Tue Oct 23 14:40:56 2018
;; MSG SIZE  rcvd: 144
```

**Comment by shimizukawa** [comment]
Unfortunately, we still can not use https protocol for https://www.sphinx-doc.org domain.
I'm keep going to setup HTTPS on RTD...

**Comment by shimizukawa** [comment]
Finally we can use https. 
https://www.sphinx-doc.org/en/master/

Once I deleted the www.sphinx-doc.org entry on RTD and re-registered it, I got the expected results.

**Comment by jeffwidman** [comment]
Thanks for fixing this.

I noticed that https://sphinx-doc.org/ does not resolve, is that expected?

**Comment by shimizukawa** [comment]
Yes, It is intended.

Technically, ReadTheDocs doesn't support `naked domains`.
https://docs.readthedocs.io/en/latest/alternate_domains.html#custom-domain-support
Currently, `sphinx-doc.org` domain points to a personal server. `http://sphinx-doc.org/` will be redirected to `www.sphinx-doc.org` but since that does not have an SSL certificate, so we can not use `https://sphinx-doc.org/`.
