### ISSUE TITLE
import matplotlib.pyplot as plt stop make html from working

### ISSUE THREAD

**Issue by Doc-Scott** [sphinx-doc/sphinx#5527]
Subject: <import matplotlib.pyplot as plt stop make html from working or sphinx causes a conflict in python>

### Problem
 
When using ` sphinx-apidoc` to write docstrings to docs I have found that files with:

`import matplotlib.pyplot as plt ` stop  `make html`  from working. commenting out or removing `import matplotlib.pyplot as plt ` makes it work and `import matplotlib` is fine. Investigating I found that I cant import matplotlib.pyplot in shell `>>>Segmentation fault (core dumped)` so maybe not a problem with Sphinx, however, I can import it in other environments and have just installed sphinx so maybe there's a conflict. Wasn't sure if to post here or not once I realised this, but thought its best just in case. I can still import it in jupyter notebooks run from  the environment 

#### Error logs / results
```
<Running Sphinx v1.8.1
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 7 source files that are out of date
updating environment: [] 1 added, 7 changed, 0 removed
10ading sources... [ 50%] docs/dataframes                                                                                                                                
Segmentation fault (core dumped)lots                                                                                                                                     
Makefile:19: recipe for target 'html' failed
make: *** [html] Error 139

or when 'make html -d`

GNU Make 4.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2014 Free Software Foundation, Inc.
Licence GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Reading makefiles...
Reading makefile 'Makefile'...
Updating makefiles....
 Considering target file 'Makefile'.
  File 'Makefile' does not exist.
  Finished prerequisites of target file 'Makefile'.
 Must remake target 'Makefile'.
 Successfully remade target file 'Makefile'.
Updating goal targets....
Considering target file 'html'.
 File 'html' does not exist.
 Looking for an implicit rule for 'html'.
 Trying pattern rule with stem 'html'.
 Trying rule prerequisite 'Makefile'.
 Found an implicit rule for 'html'.
  Pruning file 'Makefile'.
 Finished prerequisites of target file 'html'.
Must remake target 'html'.
Putting child 0x560ae971af40 (html) PID 28693 on the chain.
Live child 0x560ae971af40 (html) PID 28693 
Running Sphinx v1.8.1
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 1 source files that are out of date
updating environment: [] 3 added, 3 changed, 0 removed
Segmentation fault (core dumped)lustering                                                                                                                                
Reaping losing child 0x560ae971af40 PID 28693 
Makefile:19: recipe for target 'html' failed
make: *** [html] Error 139
Removing child 0x560ae971af40 PID 28693 from chain.

>


### Environment info
- OS: <Linux>
- Python version: 3.5.4 
- Sphinx version: v1.8.1
- <Extra tools e.g.: Browser, tex or something else>

**Comment by tacaswell** [comment]
@Doc-Scott I suspect that you have multiple pythons installed and depending on how you start it you are finding a different python and a different Matpotlib.

Make sure sphinx is installed into the same python enviroment that Matplotlib is.

**Comment by Doc-Scott** [comment]
@tacaswell Thank you. 

I checked but it seems that the environment only has Python 3 installed. However,  I noticed that I have some modules pip installed and conda installed, with different versions, maybe this is the issue with similar root to your suspicion?  

I installed Sphinx into my test environment and I didn't get the same problem. In hindsight I should have created a separate environment for Sphinx rather than lumping it into my Machine Learning environment. Apologies if this was a silly issue to report. Its my first and I had spent hours going round in circles. Hopefully it will be helpful to someone one day.

**Comment by tk0miya** [comment]
I guess this is installation problem between pip and conda. So there are nothing to help from sphinx side.

**Comment by jnsebgosselin** [comment]
Maybe something is wrong with the backend matplotlib it is trying to import during the setup of pyplot when in the shell. You are probably able to import it in the notebook because it is plotting inline.

Make sure your `pyqt` - `qt` - `sip` installation is correct, or else it will cause segfaulting when trying to import `backend_qt5agg.py` or try to change your backend to something else.

**Comment by tk0miya** [comment]
I'm closing this now because this is not an issue of Sphinx.
Thanks,
