### ISSUE TITLE
Convert rst with sphinx field lists directives to pure rst/html

### ISSUE THREAD

**Issue by Sup3rGeo** [sphinx-doc/sphinx#5529]
Hi guys, this is a question.

Docutils can render a rst string to html, as done in this application:
http://rst.ninjs.org/

This is useful because it is superfast, so we use it on some utility UI where we generate on the fly a nicer html representation of the function docstring.

What I would like to be able to do is to have something like that, but that would accept a rst string containing the sphinx field lists, like in the example below, and quickly generate html/rst with something that resembles the table we get when we generate html from sphinx.

```
    Format the exception with a traceback.

    :arg etype:  exception type
    :type etype: str
    :arg value: exception value
    :type value: int
    :arg tb: traceback object
    :type tb: traceback
    :keyword limit: maximum number of stack frames to show [optional]
    :type limit: int or None
    :returns: out
    :rtype: list of strings
    :raises: AttributeError, KeyError

    A really great idea.  A way you might use me is

    >>> data = format_exception_Sphinx('stoopid', 1, ValueError)
```

We are not just generating full html from sphinx because it takes a while to run, and I don't know if it is possible to run just for a specific rst snippet (instead of having a full project with files etc).

Is there any sphinx function we can tap into that would accept a string with rst and return formatted rst/html? Or maybe another solution for this use case?

Thanks!

**Comment by tk0miya** [comment]
Nothing. Sphinx is an application (or framework). It's implementation is placed at `sphinx.util.docfileds` and `sphinx.domains.python`. But it is strongly coupled with Sphinx core. So I don't think it is hard to use from bare docutils project.

BTW, this is not a forum for Sphinx. Please post questions to developers forum:
https://groups.google.com/forum/#!forum/sphinx-dev

Thanks,

**Comment by tk0miya** [comment]
I'm closing this now.
Thanks,
