### ISSUE TITLE
Custom code highlight using Pygments does not apply to TeX output

### ISSUE THREAD

**Issue by mchirik** [sphinx-doc/sphinx#5551]
Subject: <what happen when you do on which document project>

### Problem
- <Detail of problem>

We developed a custom syntax highlighting using Pygments and include that styling in our conf.py file. 

This is applied by including the static style sheet. 

HTML files are compiled accurately but the code highlighting in our Tex files is always in the default (looks like python highlighting) 

#### Procedure to reproduce the problem
```
<Paste your command-line here which cause the problem>
```
Use this to include the Custom code block styling

html_context = {
    'css_files': ['_static/Custom_CodeBlock.css', '_static/custom.css'],
}

Tried this for Latex, wouldn't work 

latex_additional_files = ['_fortex/Makefile', '_static/Custom_CodeBlock.css']

Perhaps I need to do this in some other way ? Did not find any documentation about this in the Latex customization style sheet. 
#### Error logs / results
```
<Paste your error log here>
```
- <public link of unexpected result if you have>

#### Expected results
<Describe what to actually do>

### Reproducible project / your project
- <link to your project, or attach zipped small project sample>

### Environment info
- OS: <Unix/Linux/Mac/Win/other with version>Win 10
- Python version: 2.7
- Sphinx version: Latest
- <Extra tools e.g.: Browser, tex or something else>

**Comment by tk0miya** [comment]
LaTeX does not support CSS. So you need to learn LaTeX macros to do that. I'm not an expert of the technique.

**Comment by ArthurHerbemont** [comment]
You may also build a dedicated new Pygments Style. I ran into the same problem for the [AIMMS language](https://download.aimms.com/aimms/download/manuals/AIMMS3_LR.pdf), and I had to build a new style from scratch, then publish it on the [Python Package index](https://pypi.org/), install it and refer to it in my Sphinx conf.py file. It is actually not that complicated if you start from an appropriate template.

**1. Build your new Style** 
Please check my repo [here](https://gitlab.com/ArthurdHerbemont/aimms-pygments-style), and modify it to your need (notably [aimmslexer.py](https://gitlab.com/ArthurdHerbemont/aimms-pygments-style/blob/master/style/aimmslexer.py), using Pygments documentation http://pygments.org/docs/styles/). 

**2. Build and register your python package** 
Then register your package using the following documentation https://packaging.python.org/tutorials/packaging-projects/, allowing everybody to use it through a straight forward `pip install <your package name>`

**3. Make it work with Sphinx** 
By installing this package, a new Style will be added to pygments style list that you can get `from pygments.styles import get_all_styles` method. Afterwards, you may refer to this style in your Sphinx conf.py, by setting the option `pygments_style = <your style name>` (see http://www.sphinx-doc.org/en/master/usage/configuration.html#confval-pygments_style)

Sphinx will then create the LaTeX style sheet accordingly when building your LaTeX files.

**Comment by tk0miya** [comment]
I'm closing this now because this is not a bug of Sphinx itself.
Thanks,
