### ISSUE TITLE
latex backend - missing packages

### ISSUE THREAD

**Issue by joakim-hove** [sphinx-doc/sphinx#5566]
### Problem
Latex compilation fails due to missing packages.

#### Error logs / results
```
(/usr/share/texlive/texmf-dist/tex/generic/babel/babel.sty
(/usr/share/texlive/texmf-dist/tex/generic/babel/english.ldf
(/usr/share/texlive/texmf-dist/tex/generic/babel/babel.def)))
(/usr/share/texlive/texmf-dist/tex/latex/psnfss/times.sty)

! LaTeX Error: File `fncychap.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)
```

### Environment info
- OS: RHEL 7
- Python version: 2.7.14
- Sphinx version: 1.7.2
- texlive-latext: texlive-latex-svn27907.0-38.el7.noarch

Would it be possible to bundle some of the LaTeX packages with the sphinx package? I installed `fncychap` and `titlesec` manually, then the manual installation of `tabulary` failed and then I gave up. I must admit that my PhD memories of fighting with exotic LaTeX packages are not the happiest - I was hoping to not go down that path ....

**Comment by mzjn** [comment]
A problem is that TeX Live on RHEL7 is a bit old (TeX Live 2013 AFAIK).

Sphinx development currently depends on TeX Live 2015 or later. See https://www.sphinx-doc.org/en/master/changes.html#dependencies.

The `fncychap` and `tabulary` packages were previously distributed with Sphinx (until version 1.4.9). See https://www.sphinx-doc.org/en/master/changes.html#release-1-5-released-dec-5-2016.

**Comment by joakim-hove** [comment]
OK - thank you for answering.

> The `fncychap` and `tabulary` packages were previously distributed with Sphinx (until version 1.4.9). See https://www.sphinx-doc.org/en/master/changes.html#release-1-5-released-dec-5-2016.

OK - I take that as you will not include those packages in the sphinx distribution - and I can kind of unerstand that,

But - would it be possible to explicitly list the *somewhat exotic* - for whatever measure of exotic - latex packages required. If you are presented with a list of packages downloading and bundling them with out source code seems feasible, but just started in one end and downloading seems a bit daunting.

**Comment by tk0miya** [comment]
Now, Sphinx-1.8 depends on TeXLive 2013. So it would work fine.
https://www.sphinx-doc.org/en/1.8/usage/builders/index.html#sphinx.builders.latex.LaTeXBuilder

We have a list of packages for Ubuntu. But we don't have it for RHEL. So it would be nice if someone make it :-)

**Comment by mzjn** [comment]
TeX Live on RHEL7 appears to be incomplete. A number of packages are mentioned in this script (in the Linux kernel repository):

https://github.com/torvalds/linux/blob/6f0d349d922ba44e4348a17a78ea51b7135965b1/scripts/sphinx-pre-install#L42

`fncychap`, `titlesec` and `tabulary` are included in that list.

On line 512, it says "RHEL 7.x and clones have Sphinx version 1.1.x and incomplete texlive":

https://github.com/torvalds/linux/blob/6f0d349d922ba44e4348a17a78ea51b7135965b1/scripts/sphinx-pre-install#L512

**Comment by joakim-hove** [comment]
OK - I found an Ubuntu box where worked as they should; and copied the sty files over. I will integrate that into my build system - seems to work. The files I had to nick from ubuntu where:
```
capt-of.sty
fncychap.sty
framed.sty
needspace.sty
tabulary.sty
titlesec.sty
upquote.sty
wrapfig.sty
```
Thank you for the help - closing.

**Comment by vpoughon** [comment]
Hi, FYI I'm using sphinx 1.8.5 on CentOS 7.21511 with TexLive 2015, and I'm seeing a similar problem: missing package `fncychap.sty`.

edit: same problem when downgrading to sphinx 1.4.8 with pip

**Comment by tk0miya** [comment]
@vpoughon How did you install texlive? If you've installed it with RPM, please install `texlive-fncychap`.

**Comment by maikeriva** [comment]
Leaving a comment for future readers.

On Fedora 33 the necessary packages are:
- texlive
- texlive-fncychap
- texlive-tabulary
- texlive-framed
- texlive-wrapfig
- texlive-upquote
- texlive-capt-of
- texlive-needspace

And finally I got it to work

**Comment by tk0miya** [comment]
I hope this list will help you: https://github.com/sphinx-doc/sphinx/blob/3.x/bindep.txt
