### ISSUE TITLE
Better documentation for `Sphinx.add_enumerable_node()`

### ISSUE THREAD

**Issue by paternal** [sphinx-doc/sphinx#5567]
### Problem

When writing Sphinx extensions, there is very few documentation about numbering and referencing directives. To do this, one has to use method [Sphinx.add_enumerable_node()](http://www.sphinx-doc.org/en/stable/extdev/appapi.html#sphinx.application.Sphinx.add_enumerable_node), which is documented, but one need to have a good understanding of Sphinx, and Sphinx types and object, to be able to use it.

### Solution

I wrote a [dummy extension](https://sphinxcontrib-stuffcounter.readthedocs.io/en/latest/) to illustrate this (using `add_enumerable_node()` to define a directive that is numbered and can be referenced). It contains the minimal code to define such a directive.

If you (@sphinx-doc) want, you can integrate it as a part of [sphinxcontrib](https://github.com/sphinx-contrib/). If you do so, I can:
-  update every link on the repository to reflect that http://github.com/sphinx-contrib/stuffcounter is the new home of this extension;
- transfer ownership of the [rtfd.io doc](https://sphinxcontrib-stuffcounter.readthedocs.io/en/latest/) to you.

Thanks for your work,
Louis

**Comment by tk0miya** [comment]
@stephenfin could you check this please?

**Comment by stephenfin** [comment]
I really need to document this process. I've invited you to the organisation, @paternal, so you just need to accept and then migrate the repo across. GitHub have good docs on this, if needed.

**Comment by stephenfin** [comment]
I assume this issue can be closed now, given https://github.com/sphinx-contrib/stuffcounter ?

**Comment by paternal** [comment]
Closed. Thanks.

By the way, I wrote [two](https://pypi.org/project/sphinxcontrib-proof/) [other](https://pypi.org/project/sphinxcontrib-packages/) Sphinx extensions. May I mirror them to [sphinx-contrib](http://github.com/sphinx-contrib) (I do not know the "requirements" to be listed there)?

**Comment by stephenfin** [comment]
@paternal Entirely up to you. If you think they're generally useful, go for it
