### ISSUE TITLE
Question about sphinx doc structure

### ISSUE THREAD

**Issue by shengchao-lin** [sphinx-doc/sphinx#5582]
My dir structure is 

python
python/build
python/doc
python/doc/modules.rst
python/doc/AAA.rst
python/source
python/source/conf.py
python/source/index.rst
python/source/readme.rst
python/source/folder
python/source/folder/AAA.py 
python/make.bat
python/Makefile

-----------------------------------
In my conf.py, I use 
`sys.path.append(os.path.abspath('./folder/'))`

In my readme.rst, I have 
`.. include:: ../doc/modules.rst`
`.. include:: ../doc/AAA.rst`

but in a.rst, it uses
`.. automodule:: AAA`

Then when I `make html`, it reported
`WARNING: toctree contains reference to nonexisting document 'AAA'`
`WARNING: autodoc: failed to import module 'AAA'; the following exception was raised:
No module named 'AAA'`

The structure and link in sphinx is really confusing.
I don't know what to do.

Thanks.

**Comment by tk0miya** [comment]
Did you read our issue template? This is not a forum. Please don't post a question here.

>  Important: This is a list of issues for Sphinx, not a forum.
>  If you'd like to post a question, please move to sphinx-users group.
>  https://groups.google.com/forum/#!forum/sphinx-users
>
>  Thanks,
