### ISSUE TITLE
Recommended internationalization of pictures

### ISSUE THREAD

**Issue by DaGeger** [sphinx-doc/sphinx#5584]
Usually, when we use internationalization, we can translate the text content of the document, 

But the text in the picture will not be translated. It is suggested to add the function of internationalization to the picture.

For example
```
_images/
  --en/
     |__ a.png
  --zh_CN/
     |__ a.png
```

As workaround:
```
class Images_I18N(Transform):
    default_priority = 10

    def apply(self):
        for node in self.document.traverse(nodes.image):
            new_uri = re.sub('/_images/',
                             lambda m: '/_images/%s/' % language,
                             node.attributes.get('uri'))

            node.attributes['uri'] = new_uri


def setup(app):
    app.add_transform(Images_I18N)
```

**Comment by tk0miya** [comment]
Sphinx already supports i18n for images. For example, Sphinx searches a file named`image.{language}.png` for `.. image:: image.png` directive.

Note: You can customize the format of image files by `figure_language_filename` option:
http://www.sphinx-doc.org/en/master/usage/configuration.html#confval-figure_language_filename

**Comment by tk0miya** [comment]
I'm closing this now.
Thank you for comment.
