### ISSUE TITLE
Extension docs: add a simple hello world tutorial

### ISSUE THREAD

**Issue by ArtFlag** [sphinx-doc/sphinx#5585]
Subject: extension documentation lacks a simpler tutorial.

The current example with the todo is interesting, but I wish it was more basic.

I've been trying to write a simple extension that simply outputs the arguments passed by the user:

```python
from docutils import nodes
from docutils.parsers.rst import Directive, directives

class my_node(nodes.Admonition, nodes.Element):
  pass

class myDirective(Directive):
  """Declare the directive.
  Used as:
  .. myDirective:: param1 param2

  Generates a new paragraph:

  "Got param1 and param2."
  """
  required_arguments = 1
  optional_arguments = 10
  has_content = False
  node_name = "myDirective"

  option_spec = {'class': directives.class_option,
                 'name': directives.unchanged}

  def run(self):
    text = " ".join(self.arguments)
    output_node = my_node(text, **self.options)

    return [output_node]


def html_visit_my_node(self, node):
  self.visit_admonition(node)

def html_depart_my_node(self, node):
  self.depart_admonition(node)

def setup(app):
  app.add_node(my_node, html=(html_visit_my_node,
    html_depart_my_node))
  app.add_directive('mydirective', myDirective)

  return {
        'version': '0.1',
        'parallel_read_safe': False,
        'parallel_write_safe': False,
  }
```

When I call it, I get the following error message:
```shell
Exception occurred:
  File "/Users/.../repositories/sphinx-stuff/venv/lib/python3.7/site-packages/sphinx/writers/text.py", line 1194, in unknown_visit
    raise NotImplementedError('Unknown node: ' + node.__class__.__name__)
NotImplementedError: Unknown node: my_node
```
I imagine this should happen we have no `visit` methods for a node, but I have defined them, and my node also extends admonition. 
So I have no idea what's going on.

If we had a new example, coming before the `todolist` example, which is quite involved, people could just copy paste it and start outputting whatever as long as it's for very simple extensions.

If you help me fix this simple extension, I would be more that happy to push a docs update.

Thanks!

**Comment by tk0miya** [comment]
It seems your extension installs visitor functions only for HTML builder. But it seems the error was raised by text writer.
You have some ways to avoid the error.

1. Add visitor functions for other builders
2. Transform your node to common one before outputting
3. Limit an output format

Note: Sphinx supports many kinds of extensions. The directive extension is one of them. It would be nice if we can provide docs for all of them in future :-)

**Comment by ArtFlag** [comment]
Hi Takeshi,

Thanks for your comment, that's interesting and I have more questions. Don't worry, it's not for nothing, I will update the docs based on what you share. 

- About visitor functions: I tried to copy [this directive](https://github.com/bokeh/bokeh/blob/master/bokeh/sphinxext/collapsible_code_block.py). It uses only HTML visitor methods. Why does it work in that case and not in mine?
- Would you have an example of `2` and `3`?

**Comment by tk0miya** [comment]
>About visitor functions: I tried to copy this directive. It uses only HTML visitor methods. Why does it work in that case and not in mine?

It looks like not supporting non-HTML output. I guess it would be crashed.

>Would you have an example of 2 and 3?

`LiteralBlockTransform` would be an example of (2). It replaces some kind of `literal_block` node by original one.
https://github.com/sphinx-doc/sphinx/blob/bebea6bd8cd96ca39077d87c68ad47509452f467/sphinx/builders/latex/transforms.py#L572-L584

(3) is simple. Please say "This extension only support HTML output" in your README.

**Comment by ArthurFlageul** [comment]
This can be closed! 

Thanks 🙂

**Comment by ArtFlag** [comment]
Closing this issue as the tutorial is merged.

**Comment by tk0miya** [comment]
:-)
