### ISSUE TITLE
Reopen of 4895: autoclass inherited methods always shown

### ISSUE THREAD

**Issue by max3-2** [sphinx-doc/sphinx#5595]
### Problem
Generating docs for classes with inheritance always generates the full inherited methods docstring. Sam issue is described here #4895 
https://github.com/sphinx-doc/sphinx/issues/4895
Reproducable for me with the shown code. Other option to reproduce

main.py
```
import numpy as np


class TestClass(np.ndarray):
    """A little docstring.

    Parameters
    ----------
    inp: str
        with numpy style
    """
```

in *rst
```
==========
Main Test
==========
Some doc

.. py:currentmodule:: main
.. autoclass:: TestClass
```

in conf, mainly basic QuickStart, I changed to use NumPy (Maybe that's the issue?)
```
extensions = [
    'sphinx.ext.autodoc',
    'numpydoc',
    'sphinx.ext.autosummary',
    'sphinx.ext.doctest',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.mathjax',
    'sphinx.ext.ifconfig',
    'sphinx.ext.viewcode',
    'sphinx.ext.githubpages',
]
```

#### Error logs / results
Screenshot of the doc, which shows the inheritance. I do NOT want to have the inheritance and its documented to not show it

<img width="843" alt="bildschirmfoto 2018-11-06 um 18 55 41" src="https://user-images.githubusercontent.com/10244463/48083688-1d9f8c80-e1f6-11e8-880a-8ceb16ca59f8.png">

### Environment info
- OS: macOS 10.14, Win7, Win10
- Python version: 3.6, 3.7
- Sphinx version: 1.8.1

**Comment by max3-2** [comment]
Forgot to mention: added the path to main.py in conf.py (relative)
```
sys.path.insert(0, os.path.abspath('..'))
```
Then compiling with make html
Getting a ton of warnings connected to the super() methods. For every method I get 3:
```
main.py:docstring of main.TestClass:69: WARNING: toctree references unknown document 'main.TestClass.all
index.rst:: WARNING: toctree contains reference to nonexisting document 'main.TestClass.all
main.py:docstring of main.TestClass:128:<autosummary>:: WARNING: toctree contains reference to nonexisting document 'main.TestClass.all
```

**Comment by mzjn** [comment]
Have you tried to use the Napoleon extension instead of numpydoc?

http://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html

**Comment by max3-2** [comment]
No change here, but I found that ..autosummary actually is the issue. I can remove that and it runs on either numpydocs or Napoleon.

However im running into a new issue: Napoleon completely ignores custom headers in doc strings. so only the numpy ones are allowed? I think this might have to go into a new issue after ill put some time into it. Thanks so far!

**Comment by mzjn** [comment]
Napoleon supports a set of predefined section headers.

https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html?highlight=napoleon#docstring-sections

**Comment by tk0miya** [comment]
I guess this might be related with numpydoc. Without numpydoc, inherited methods are not shown.

**Comment by tk0miya** [comment]
I'm closing this because this might not be a bug of Sphinx.
Thanks,
