### ISSUE TITLE
JSON builder produces wrong link

### ISSUE THREAD

**Issue by apfelbox** [sphinx-doc/sphinx#5599]
Subject: JSON builder produces wrong link

### Problem

I have the following tree:
![2018-11-07 at 15 22](https://user-images.githubusercontent.com/1032411/48136850-fe116e00-e2a0-11e8-88ac-775426a73d12.png)

<details>
<summary><code>index.rst</code></summary>

```rest
.. toctree::
    :hidden:

    first/example

####
Test
####
```
</details>

<details>
<summary><code>first/example.rst</code></summary>

```rest
.. toctree::

    example/nested

###
Sub
###

:doc:`example/nested`
```
</details>

<details>
<summary><code>config/conf.py</code></summary>

```python
# -*- coding: utf-8 -*-
#
# Becklyn Docs documentation build configuration file, created by
# sphinx-quickstart on Mon May 22 21:32:02 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = []

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'Project'
copyright = u'2018, Copyright'
author = u'Author'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = u'0.1'
# The full version, including alpha/beta/rc tags.
release = u'0.1'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'basic'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = {
    "nosidebar": True,
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = []


# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'Mydoc'

```

</details>

#### Procedure to reproduce the problem
```
sphinx-build -b json/html/xml -c config docs out
```

#### Error logs / results

The link created in `` :doc:`example/nested` `` is wrong, but only in the `json` format.

* `-b json`: `<a class="reference internal" href="nested/">Nested</a>` ❗️ 
* `-b html`: `<a class="reference internal" href="example/nested.html">Nested</a>` ✅ 
* `-b xml`: `<reference internal="True" refuri="example/nested"><inline classes="doc">Nested</inline></reference>` ✅ 

#### Expected results

All links should be the same.

### Reproducible project / your project

* [docs-test.tar.gz](https://github.com/sphinx-doc/sphinx/files/2557716/docs-test.tar.gz)

### Environment info
- OS: macOS 10.14.1
- Python version: Python 2.7.15
- Sphinx version: sphinx-build 1.8.1

**Comment by tk0miya** [comment]
Sorry, I don't know what is correct behavior. But it seems this implementation has come from 10 yrs ago (see [builders.py](https://github.com/sphinx-doc/sphinx/blob/v0.5/sphinx/builder.py) in v0.5).
I agree the behavior might be wrong. But I'm afraid of breaking compatibility.

**Comment by apfelbox** [comment]
To me it seems that the correct behaviour would be the output of `xml`/`html`, because it mirrors the actual directory structure.

It's fine to push this into 2.0, as it hasn't come up so far and it might indeed add some BC for old apps.

**Comment by kaymccormick** [comment]
The link should be to do the target "docname" relative to the docname of the source document, just like in HTML. 

The JSON builder seems ill-conceived, like a one-off builder for a specific architecture or implementation. it even outputs files with a proprierty extension (jfson or something). To me, there is no value add over the XML builder. I process Sphinx XML on the client with xml2js, and it works great, and generates a usable object structure.

**Comment by apfelbox** [comment]
Yeah, the file extension is `fjson` and it is like a hybrid builder for HTML (the content) + JSON (the rest of the structure).

I solved my use case by
a) building a custom XML -> HTML compiler for generating the output
b) using a two-step compiler, by first building to JSON to extract the metadata and then building to XML to compile to HTML using our custom parser + renderer.

The implementations seem to be all over the place: `json` is HTML + metadata, `xml` is content only without metadata. I am not too deep into the whole topic, but maybe generating the metadata should always be a separate step aside from the actual content building?

**Comment by tk0miya** [comment]
It seems json builder always considers source files as directories.

* ```:doc:`foo` ``` -> `<a href="foo/">`
* ```:doc:`foo/index` ```  -> `<a href="foo/">` (`.../index` is omitted)

As a result, the builder says the relative URI of `/first/example/nested.rst` from `/first/example.rst` is `nested/`.

I don't understand this concept is useful. But I feel consistent. So -0 for this change.

**Comment by shimizukawa** [comment]
Current maintainers do not know the output specification of fjson and I do not know where they are affecting, so I think that output should not be changed. For this reason I disagree with the change proposal to the current fjson builder. 
IMO, it would be better to develop a new builder that will produce the desired JSON output.

**Comment by tk0miya** [comment]
@shimizukawa Thank you for comment.
Okay, let's keep as is.
