### ISSUE TITLE
Add option to sphinx-apidoc to not create headings

### ISSUE THREAD

**Issue by andreas-h** [sphinx-doc/sphinx#5602]
My apologies if the used terminology is not correct.  I am aware that there is an option `-E` to `sphinx-apidoc` which is documented as *--no-headings*.

I am also aware that this is an aesthetic question.  Please consider it as request for enhancement.  I am happy to contribute code to implement this, but would need some guidance on where to start.

Here, when I refer to *headings*, I refer to

- the `<h1/>` heading at the top of each module page (*lamospy package* in the screenshot below)
- the `<h2/>` heading *Subpackages*
- the TOC entries *Submodules*

I am already using `--no-headings` (see below)

### Problem

1. The *lamospy package* `<h1/>` heading is redundant with the module heading (rendered as `<h2/>` right below; *LAMOSpy* in the screenshot below, which comes from my module's `lamospy/__init__.py` file). This is apparent both in the page's main area, and also in the navbar on the left.
2. In both navbar and TOC it is a bit irritating that e.g. *FLEXPART input data* is a child of *Submodules* and not directly of *Handling FLEXPART and FLEXPART-WRF* 

When using `sphinx-apidoc`, the generated HTML code is rather verbose when it comes to headlines.  There is always a headline *module.submodule.subsubmodule module* generated, which comes before the "headings" (what I can switch off with `-E`). This is a bit too verbose.  

It would be nice if `sphinx-apidoc` would get an additional option to not generate these headings.

#### Procedure to reproduce the problem
```
sphinx-apidoc -M -e -E -H API -o api/ ../lamospy
```

#### Error logs / results
![screenshot_2018-11-08_17-05-57](https://user-images.githubusercontent.com/358378/48210942-b0683480-e378-11e8-934e-3f54accb8e7e.png)

#### Expected results
It would be good if there were an additional command line switch to `sphinx-apidoc` in order to do the following:

1. The *Heading* (which can be switched off with `-E` when one has RST headings in the module files themselves) should be the top-level heading; there should be no auto-generated *XXX package* or *YYY module* `<h1/>` level headings.
2. Individual subpackages and submodules should be direct children of their parents in the TOC, and not children of an additional *Subpackages* or *Submodules* layer.

### Reproducible project / your project
Project is not public at the moment

### Environment info
- OS: Debian Linux (Buster/Testing)
- Python version: 3.6.6 (Anaconda)
- Sphinx version: 1.8.1

**Comment by mzjn** [comment]
You might be interested in these SO questions and their answers:

https://stackoverflow.com/q/29385564/407651
https://stackoverflow.com/q/28481471/407651

**Comment by tk0miya** [comment]
I feel supporting templates is great idea :-)
It makes customizing easier.

**Comment by tk0miya** [comment]
Fixed by #6492.
Thank you for reporting.
