### ISSUE TITLE
async loading of mathjax breaks equations

### ISSUE THREAD

**Issue by zingale** [sphinx-doc/sphinx#5616]
Subject: async loading of mathjax breaks equations

### Problem
- I am using sphinx 1.8.2 and using a custom `mathjax_conf.js` as described here:
   http://paugargallo.com/posts/2016-05-05-sphinx-mathjax.html
   to allow me to define latex `\newcommand`s to work with mathjax.  This worked great with an earlier sphinx but now it fails to render the custom math macros.  If I remove the `async="async"` line in 
   the html on the mathjax load, then things render as expected.  It looks like this was added recently
   (#3606).  Is there a way to disable this so we can render math with macros? 

#### Procedure to reproduce the problem

The attached .html was generated by sphinx 1.8.2.  Also included is the `mathjax_conf.js` I am using.  As written, some of the special macros don't render.  If I remove the `async="async"` in the mathjax load, then it works as expected.

#### Error logs / results
```
<Paste your error log here>
```
- <public link of unexpected result if you have>

#### Expected results
mathjax should allow for customization

### Reproducible project / your project
- <link to your project, or attach zipped small project sample>

### Environment info
- OS: Fedora 28
- Python version: 3.6.6
- Sphinx version: 1.8.2
[test.zip](https://github.com/sphinx-doc/sphinx/files/2569841/test.zip)

- <Extra tools e.g.: Browser, tex or something else>

**Comment by tk0miya** [comment]
Please use `mathjax_config` instead.
https://www.sphinx-doc.org/en/master/usage/extensions/math.html?highlight=math#confval-mathjax_config

Another way, please use `<script type="text/x-mathjax-config">` tag to load the configuration file instead. mathjax expects to use it on loading configurations.
https://docs.mathjax.org/en/latest/configuration.html#using-in-line-configuration-options

**Comment by zingale** [comment]
that works (the first one).  Thank you.  I saw that in the docs, but it was not immediately clear to me that it worked with macros.  Would you accept a PR that added another example to the docs showing a tex macro example there?

**Comment by tk0miya** [comment]
I'm not good at mathjax, so I don't understand what macro means. but any PR is always welcome.

**Comment by tk0miya** [comment]
Now I'm closing this because resolved.
