### ISSUE TITLE
index.html missing in QtHelp

### ISSUE THREAD

**Issue by magro11** [sphinx-doc/sphinx#5627]
### Problem

In Sphinx 1.8.2 it seems that the index.html as well as other html-files, which are located in the root directory (and no
subdirectory) are not longer contained in the compressed Qt help file *.qch. This is at least the behavior for Windows operating systems (Python 3.6 and 3.7).

The problem seems to be a wrong entry in the <files> section of the .qhp file. Former versions of Sphinx inserted for instance <file>index.html</file> in this files section, whereas Sphinx 1.8.2 writes <file>/index.html</file>. Once I remove the slash, the documentation is built correctly again.

The error seems to appear in the qthelp.py --> `def get_project_files`.

Due to the first if-case, `os.sep` (which is \\\\ under Windows) is appended to the outdir. The index.html file is located in this root folder, however `posixpath.join(root, fn)` (Line 272) inserts a slash between root and fn, although root already finishes with \\\\. Hence, the result is for instance C:\\\\temp\\\\/index.html. The slicing operation `[olen:]` then removes the root and "/index.html" remains.

If subdirectories are walked through, the variable root does not end with a slash or backslash, such that posixpath.join correctly joins the two path components.

### Possible Solution
It should be verified, that all file pathes, returned by **get_project_files**, should not start with a slash or backslash. The main problem seems to be, that posixpath.join does not work correctly under windows if the first path component ends with two backslashes.

### Environment info
- OS: Windows
- Python version: 3.6 / 3.7
- Sphinx version: 1.8.2
- Qt 5.6 and 5.9

Thank you.

Marc

**Comment by tk0miya** [comment]
Note: The `posixpath.join()` was added in #4923.

**Comment by tk0miya** [comment]
Fixed by #5628.
Thank you for reporting.
