### ISSUE TITLE
classes with the same attributes

### ISSUE THREAD

**Issue by schriftgestalt** [sphinx-doc/sphinx#5647]
I have and .rst file and no implementation of the classes (I’m documenting wrapper so it is mostly implemented outside of python).

There is probably a very simple solution but I can’t find it.

Here is an example:
```
.. class:: AClass

an object

.. autosummary::

	name
	age

.. attribute:: name

	the name

	:type: string

.. attribute:: age

	the age

	:type: int


.. class:: BClass

another object


.. attribute:: name

	the name

	:type: string

.. attribute:: age

	the age

	:type: int
```

My problem is that only the first two attributes get a link (to `#name`and `#age`). And both autosummary links point to the first class. 

I need those anchors to be `#AClass.name`. I could add the class prefixes myself, but that makes the documentation almost unreadable.

**Comment by tk0miya** [comment]
Please move description of the class and `attribute` directives under `class` directive like this:
```
.. class:: AClass

   an object

   .. attribute:: name
   .. attribute:: age
```

**Comment by schriftgestalt** [comment]
Thanks. The attributes do work now but the `.. autosummary::` is not. 

And I had a section title like this:
```
----------
Properties
----------
```
To structure the doc a bit. If I keep it without indentation, it closes the class block and if I indent it, I get this:
```
index.rst:155: WARNING: Unexpected section title.
```

**Comment by tk0miya** [comment]
If you want to use `autosummary` and section headers for class members, please give a class name to them:

```
.. class:: AClass

.. attribute:: AClass.name
.. attribute:: AClass.age
```

Sphinx considers `attribute:: name` is a top level (module global) variable, not a class member.

**Comment by schriftgestalt** [comment]
Thanks for the help.

**Comment by tk0miya** [comment]
I'm closing this now.
Please post a question to our forum in next time.
Thanks,
