### ISSUE TITLE
class name "versionmodified" used by all versionchanged/added/deprecated

### ISSUE THREAD

**Issue by Grovkillen** [sphinx-doc/sphinx#5660]
Subject: HTML output for change log (I want to CSS the headlines)

### Problem
The current implementation use the same class name for all three version roles. This means I cannot use CSS to have the color of the text reflect if its added (green), changed (yellow) or deprecated (red). The only difference between them is the text itself but for the reader this might become hard to read through when its all the same color (default black).

http://www.sphinx-doc.org/en/1.6/extdev/nodes.html#sphinx.addnodes.versionmodified

#### Expected results
Role | ClassName
------------ | -------------
versionadded | versionmodified.added
versionchanged | versionmodified.changed
deprecated | versionmodified.deprecated

### Reproducible project / your project
- https://espeasy.readthedocs.io/en/latest/

### Environment info
- Sphinx version: 1.8.1

**Comment by tk0miya** [comment]
+1: Resonable.
