### ISSUE TITLE
splinx autodoc does not retain type hints of a member field

### ISSUE THREAD

**Issue by alexyiu875** [sphinx-doc/sphinx#5679]
Subject: splinx autodoc does not retain type hints of a member field

### Problem
splinx autodoc does not retain type hints of a member field

#### Procedure to reproduce the problem
Sample Python source code: 
```
class LocalTimezoneEnum(str, Enum):
    """
        An enum that represents which local time zone is being used.
        E.g. "user" vs "subject" (e.g. a mill or an airport)
    """

    user: str = 'user'
    """
        using user's local time zone
    """

    subject: str = 'facility'
    """
        using the local time zone of a facility
    """


class DateTimeIso8601(BaseModel):
    """
        A data class that combines an ISO-8601 date time field with a local timezone indicator
    """

    iso8601_datetime: datetime.datetime
    """
    """

    local_timezone: Optional[LocalTimezoneEnum] = None
    """
        This 'DateTimeIso8601' data item should have 'local_timezone' (e.g. 'user' vs 'facility'),
        if and only if iso8601_datetime does not have a timezone designator
    """
```

Generated Sphinx HTML doc of "DateTimeIso8601" does not contain type information of these 2 member fields: "iso8601_datetime" and  "local_timezone" 

#### Error logs / results
N/A

#### Expected results
Autodoc should automatically retain type hints information of a member field of a class, just like retaining function / method signature of a class. 

### Workaround: 
Manually adding ":type: " back to doc string. E.g.:
```
class LocalTimezoneEnum(str, Enum):
    """
        An enum that represents which local time zone is being used.
        E.g. "user" vs "subject" (e.g. a mill or an airport)
    """

    user: str = 'user'
    """
        using user's local time zone
    """

    subject: str = 'facility'
    """
        using the local time zone of a facility
    """


class DateTimeIso8601(BaseModel):
    """
        A data class that combines an ISO-8601 date time field with a local timezone indicator
    """

    iso8601_datetime: datetime.datetime
    """
        :type: datetime.datetime
    """

    local_timezone: Optional[LocalTimezoneEnum] = None
    """
        :type: Optional[LocalTimezoneEnum]

        This 'DateTimeIso8601' data item should have 'local_timezone' (e.g. 'user' vs 'facility'),
        if and only if iso8601_datetime does not have a timezone designator
    """
```

(BTW, the above sample code is using the "BaseModel" from pydantic as the parent class.  
See also: https://github.com/samuelcolvin/pydantic
https://pydantic-docs.helpmanual.io/
)
 
### Environment info
- OS: MacOSX 
- Python version: 3.6
- Sphinx version:  Sphinx 1.8.2 & Alabaster 0.7.12

**Comment by tk0miya** [comment]
+1; Absolutely!

**Comment by tk0miya** [comment]
Since Sphinx-3.0, autodoc supports typehints for variables!
So this was already resolved. Closing.
