### ISSUE TITLE
Error when using :widths: option for ..table::

### ISSUE THREAD

**Issue by barbara-sfx** [sphinx-doc/sphinx#5716]
Subject: Error when using `:widths:` option for `..table::`

### Problem
- Sphinx throws an error when I use the `:widths: auto` for a `..table::` directive

#### Procedure to reproduce the problem

```
.. table::
   :widths: auto

   ==============    ===============
   abc               def
   ==============    ===============
   >2M               c5.18xlarge
   1-2M              c5.9xlarge
   250k-1M           c5.4xlarge
   <250k             c5.2xlarge
   ==============    ===============
```

#### Error logs / results

```
/Users/barbara/Documents/github-sfx/doc.rst:36: WARNING: Error in "table" directive:
unknown option: "widths".

```
Also, table does not render.

#### Expected results
No error and table renders with correct widths

### Reproducible project / your project
- n/a (private repo)

### Environment info
- OS: Mac 10.13.6
- Python version: 2.7.11
- Sphinx version: 1.8.2

**Comment by tk0miya** [comment]
Sorry, I can't reproduce the error on my local.
Could you try again in new project please?

**Comment by tk0miya** [comment]
I'm closing this now.
Please feel free to reopen this if you're still in problem.
Thanks,
