### ISSUE TITLE
sphinx-quickstart fails when $LC_ALL is empty

### ISSUE THREAD

**Issue by cocoatomo** [sphinx-doc/sphinx#5724]
Subject: sphinx-quickstart fails when $LC_ALL is empty

### Problem
- sphinx-quickstart fails when $LC_ALL is empty

#### Procedure to reproduce the problem
```
$ python3.7 -m venv venv
$ . venv/bin/activate
(venv) $ pip install sphinx
(venv) $ export LC_ALL=
(venv) $ sphinx-quickstart
```

#### Error logs / results
```
Traceback (most recent call last):
  File "/private/tmp/issue/venv/bin/sphinx-quickstart", line 11, in <module>
    sys.exit(main())
  File "/private/tmp/issue/venv/lib/python3.7/site-packages/sphinx/cmd/quickstart.py", line 616, in main
    locale.setlocale(locale.LC_ALL, '')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/locale.py", line 604, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

#### Expected results
sphinx-quickstart do not raise exception

### Reproducible project / your project
- Nothing (this issue occurs before having a project created)

### Environment info
- OS: macOS 10.14.1
- Python version: 3.7
- Sphinx version: 1.8.2

**Comment by ghost** [comment]
I don't believe this is a Sphinx bug specifically. The idiom of `locale.setlocale(locale.LC_ALL, '')` works on Windows/Linux even if `LC_ALL` is empty. From research it seems to be a problem specific to Mac:

https://bugs.python.org/issue18378#msg215215

**Comment by tk0miya** [comment]
@remyabel Thank you for comment.

I understand the error has been filed on bugs.python.org. I just made a workaround for the bug at #5829.
I believe it helps users on Mac OS.
