### ISSUE TITLE
Use latest mathjax version by default

### ISSUE THREAD

**Issue by goerz** [sphinx-doc/sphinx#5725]
The current `sphinx.ext.mathjax` plugin uses mathjax version 2.7.1, see
https://github.com/sphinx-doc/sphinx/blob/c2fcb82221d4b6b2b57bc8cd01954eda239ad7e8/sphinx/ext/mathjax.py#L108

This version is not the most current one, and is known to have problems with accents in Safari (https://github.com/mathjax/MathJax/issues/1737) and on iOS (https://github.com/mathjax/MathJax/issues/2091).

I would advocate switching to `https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/latest.js` as the default `mathjax_path` (as recommended by http://docs.mathjax.org/en/latest/configuration.html). Anyone who needs to pin a specific version can still set that version in their `conf.py`, but for most people, using "latest" will probably cause the least problems.

**Comment by tk0miya** [comment]
+1; Resonable.
Could you send us a PR please?

**Comment by goerz** [comment]
Done. `CONTRIBUTING.rst` seems to say the pull request should be with respect to the `1.8` branch, so I hope I did the right thing there...

**Comment by tk0miya** [comment]
:-)
