### ISSUE TITLE
glob for files with extensions other than .rst

### ISSUE THREAD

**Issue by ltalirz** [sphinx-doc/sphinx#5756]
For extensions like `nbsphinx` that add the ability to document files with extensions other than `.rst` it would be very useful to be able to use wildcards in toctrees as well, using a syntax like:
```rst
.. toctree::
   :titlesonly:
   :glob:

   *.ipynb
```

When raising this issue with nbsphinx (spatialaudio/nbsphinx#151), @mgeier suggested that this should probably be solved at the sphinx level.
Do you agree?

**Comment by tk0miya** [comment]
The content of toctree directive is not a list of filename. It is list of **docname** s. So -1 for your proposal.

BTW, why do you want to such feature? How about move .ipynb files to under the sub-directory? Please let me know your motivation to pick up individual filetypes in toctree directive.

**Comment by ltalirz** [comment]
> The content of toctree directive is not a list of filename. It is list of docname s. So -1 for your proposal.

I see, happy to amend: Since `nbsphinx` treats `ipynb` files as pieces of documentation, would it make sense for sphinx to offer a way (for extensions like `nbsphinx`) to modify which files are picked up by the [existing](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#table-of-contents) `*`, so that the following would also pick up files with `ipynb` extension?
```rst
.. toctree::
   :titlesonly:
   :glob:

   *
```

@mgeier Would this make sense? Does sphinx currently offer a way to do this?

> why do you want to such feature?

My use case is that the number of `ipynb` files to be documented may be changing over time (they may even reside in a folder outside the sphinx documentation folder, and people working on `ipynb` files may be different from people working on the documentation) and I would like to make sure that sphinx always produces documentation for all of them without having to update some `index.rst` file every time a new `ipynb` file is added.

**Comment by mgeier** [comment]
This already works, see https://github.com/spatialaudio/nbsphinx/blob/master/doc/index.rst.

The only thing that doesn't seem to work is including the file suffix in the glob pattern.

If you use a single `*`, all source files in the directory should be used, regardless of their suffix.

> they may even reside in a folder outside the sphinx documentation folder

This doesn't work with `nbsphinx`, but you can use https://github.com/vidartf/nbsphinx-link for this.

**Comment by ltalirz** [comment]
> This already works, see https://github.com/spatialaudio/nbsphinx/blob/master/doc/index.rst.

Great! This is all I need, I guess my original question was not clear enough.
From my point of view the issue can be closed.

> This doesn't work with nbsphinx, but you can use https://github.com/vidartf/nbsphinx-link for this.

Thanks for the hint!

**Comment by mgeier** [comment]
@tk0miya 

> The content of toctree directive is not a list of filename. It is list of **docname**s

If I'm not mistaken, it is actually a list that can contain three different types of things:

* docname, glob patterns can be used
* file name (= docname + suffix), glob patterns don't work
* external link

I can see that it might be surprising that glob patterns work in the first case but not in the second.

I personally can live with this, but I think, strictly speaking, this is a bit inconsistent.

BTW, I think the second case is not documented, it might even be an accidental feature?

Related question: #1755.

**Comment by tk0miya** [comment]
>file name (= docname + suffix), glob patterns don't work

Indeed, toctree directive accepts the filenames implicitly. And it is not documented:
https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html

We can found the hint from Georg on the comment of toctree directive:
https://github.com/sphinx-doc/sphinx/blob/914e65596075a77452a50b829fa3c06c9e7fa0c0/sphinx/directives/other.py#L123-L127

As my understand, the filename support in toctree directive was obsoleted. It is working only for compatibility.

**Comment by mgeier** [comment]
Thanks @tk0miya, it makes sense that it is not documented if it was obsoleted.

I will remove the suffixes from my example: https://github.com/spatialaudio/nbsphinx/pull/272.
