### ISSUE TITLE
LaTeX: should the Bjarne style of fncychap be used for English also if passed as language option?

### ISSUE THREAD

**Issue by jfbu** [sphinx-doc/sphinx#5772]
Currently  there is https://github.com/sphinx-doc/sphinx/blob/ca2ce49830f2e574aa0e9426670d08d44078187b/sphinx/writers/latex.py#L595-L601

but this has the effect that when `sphinx-build` is executed on our documentation at RTD to produce the PDF, it will use "Sonny" `fncychap` style because `language` is explicitely set. If the documentation is build locally (for testing) it uses the "Bjarne" style from this default: https://github.com/sphinx-doc/sphinx/blob/ca2ce49830f2e574aa0e9426670d08d44078187b/sphinx/writers/latex.py#L149

The question is whether it would make sense to apply the Sonny style only for non-English, when a language is explicitely selected. It is a bit weird that explicitely specifying English as language turns off some style elements of PDF which were tested with English... and apply if no language is specified.

**Comment by tk0miya** [comment]
Our document says:

>Inclusion of the “fncychap” package (which makes fancy chapter titles), default '\\usepackage[Bjarne]{fncychap}' for English documentation (this option is slightly customized by Sphinx), '\\usepackage[Sonny]{fncychap}' for internationalized docs (because the “Bjarne” style uses numbers spelled out in English). 
http://www.sphinx-doc.org/en/master/usage/configuration.html#confval-latex_elements

So +1 for applying Bjarne for English document even if language is explicitly given.
