### ISSUE TITLE
Add htmlhelp_ascii_output option to htmlhelp builder

### ISSUE THREAD

**Issue by ghost** [sphinx-doc/sphinx#5788]
Subject: non-ASCII characters can not display in chm

### Problem
chm is an old tech from 20 years ago, maybe for backward compatibility reason, `hh.exe` using system's local encoding to render chm content by default.

Then some non-ASCII characters display as mojibakes, for example if a page's charset is cp1252, and it has a string `classical “sequential” programming`, (`“` \u201C and `”` \u201D are legal in cp1252).
Now we open this chm in a Simplified Chinese Windows, then `hh.exe` using gbk as default encoding, `“s` (0x93 0x73 byte sequence) is decoded as `搒`, `” ` (0x94 0x20 byte sequence) is decoded as `�`, the entire string looks like `classical 搒equential� programming`.

Python's chm doc suffered this problem about one year, see https://bugs.python.org/issue32174 , you can see some screenshots in this issue.

It seems impossible to specify the encoding of .chm to ASCII [1], the available encodings of .chm are limited to a list [2].

[1] https://github.com/sphinx-doc/sphinx/blob/96c5605374135652cf7ec0ad517b532b9261ef19/sphinx/builders/htmlhelp.py#L203-L205
[2] https://github.com/sphinx-doc/sphinx/blob/96c5605374135652cf7ec0ad517b532b9261ef19/sphinx/builders/htmlhelp.py#L136-L169

### Suggestion
We can add a `htmlhelp_ascii_output` option to htmlhelp builder, when this is set to `True`, the output html using ASCII encoding, it escapes every non-ASCII characters to ASCII form, then we can get the right visual effect everywhere.

I wrote a patch to demonstrate this idea, see https://github.com/sphinx-doc/sphinx/pull/5808/commits/2fc00f4ec8945422e2558ecef9843c6b6e1da298
Do you like this idea?

This is one screenshot:
![Python chm](https://raw.githubusercontent.com/animalize/pics/master/issues/chm.png)

**Comment by animalize** [comment]
not prepared yet, close it.

**Comment by ghost** [comment]
> What "Binary" means? Is there any description for these options?

There is another hh.exe problem. "Index search in CHM help crashes the viewer", after turning "Binary Index" to "Yes", hh.exe no longer crash.

Please read: https://bugs.python.org/issue35228
So I add this option.

> If my understanding is right, this is a hack to choose encoding via configuration. If true, I feel htmlhelp_encoding is much better for this case.

I prepared another `htmlhelp_ascii_output` implementation **Method C**, let me explain.

## Method A
I wrote a [Sphinx extension](https://github.com/python/cpython/commit/6261ae9b01fb8429b779169f8de37ff567c144e8) (in [Pythin issue32174](https://bugs.python.org/issue32174)) to fix Python chm's problem, this extension escapes the `body` part of html to 7-bit ASCII, however this extension is not perfect, the related navigation bar still has corrputed characters.

Because the `body` part is not equal to `body` tag, navigation bar is not included in `body` part.
(`body` part is `<div class="body" role="main">...</div>` inside a html file.)

![](https://raw.githubusercontent.com/animalize/pics/master/issues/not%20perfect%20yet.png)

## Method B
Yesterday I created [PR5808](https://github.com/sphinx-doc/sphinx/pull/5808) to this repository,  `htmlhelp_ascii_output` option escapes the entire html file to 7-bit ASCII.

This method is not perfect as well. hh.exe using specified `Language` (e.g. `Language=0x409`) to process some meta datas of html, if the `title` tag inside `head` tag is escaped, the search results display a square for escaped character (e.g. `’`-> `&#8217;`).

Please see the screenshot below.

## Method C
So I prepared a Method C, it escapes html file excepts `head` tag, this method seems perfect.

This is Method C patch:
https://github.com/animalize/sphinx/commit/f8d79c6fa96b4efbd636688c8dac7dbb46fcc1e7
How about it? If you accept it, I will create a PR base on it.

![](https://raw.githubusercontent.com/animalize/pics/master/issues/methodBC.png)

**Comment by tk0miya** [comment]
Sorry for late.

I think Method C is a kind of error handler on encoding.
I just wrote small example for the handler.
```
import codecs


def decimal_charrefreplace(error):
    # type: (UnicodeEncodeError) -> Tuple[str, int]
    """Replace unencodable characters by decimal escaped representation (RFC 5137)

    refs: https://tools.ietf.org/html/rfc5137#section-5.2
    """
    text = error.object[error.start:error.end]
    escaped = ''.join('&#x%d;' % ord(c) for c in text)
    return escaped, error.end


codecs.register_error('decimal_charrefreplace', decimal_charrefreplace)

# a text contains unicode; "Hello Sphinx" in Japanese
s = 'Hello スフィンクス'

print(s.encode('ascii', errors='xmlcharrefreplace'))
# => b'Hello &#12473;&#12501;&#12451;&#12531;&#12463;&#12473;'

print(s.encode('ascii', errors='decimal_charrefreplace'))
# => b'Hello &#x12473;&#x12501;&#x12451;&#x12531;&#x12463;&#x12473;'
```

If this is fine, it would be better to switch the fourth parameter for `codecs.open()`.
https://github.com/sphinx-doc/sphinx/blob/503cf9c39e829024160145d03bc1e9bc12d65ec9/sphinx/builders/html.py#L1196-L1197

What do you think?

**Comment by tk0miya** [comment]
Note: I still can't find what "Binary Index" and "Binary TOC" mean.
I found unofficial document for CHM. But it does not describe the fields...
http://chmspec.nongnu.org/latest/INI.html#HHP

**Comment by ghost** [comment]
> Sorry for late.

Never mind, this patch is just a prototype.

You misunderstood this problem.

The IE kernel can handle hex-escaping well in .html files, so we don't need decimal-escaping here.
Hex-escaping is only bad in .hhc/.hhk files, this already fixed in https://github.com/sphinx-doc/sphinx/pull/5853.

The problem is, `htmlhelp` only accept a limited encoding list for .html output, while `ascii` is not in the list:
https://github.com/sphinx-doc/sphinx/blob/96c5605374135652cf7ec0ad517b532b9261ef19/sphinx/builders/htmlhelp.py#L136-L169

Let's cite a case, here is some points:
1. Python's chm doc is using [`cp1252`](https://en.wikipedia.org/wiki/Windows-1252) as .html encoding.
2. `cp1252` extended `ascii`, it includes some non-ascii characters, such as `ß` (\xDF), `€` (\u20AC), `“` (\u201C), `”` (\u201D) ...
3. these non-ascii characters present in .html file as `b'[\x80-\xFF]'` bytes.
4. chm viewer `hh.exe` uses system default encoding to render a chm file by default. For example on a Simplified Chinese Windows, will using `gbk` to decode those .html.
5. so using `gbk` to decode those `b'[\x80-\xFF]'` bytes will get wrong result. (using `cp1252` encoding will get the correct result.)

The option `htmlhelp_ascii_output` escapes non-ascii characters in .html output, to ensure no `b'[\x80-\xFF]'` bytes will be wrongly decoded.
For example: under `cp1252` encoding, `“` is represented as `b'\x93'` in .html file. with this option, it will be represented as `&#8220;`, so `“` will display correctly everywhere.

But we don't need to escape the `<head>` tag, because:
1. `<head>` tag is not visible to user.
2. `hh.exe` uses specified encoding (such as `cp1252`, when set `Language=0x409` in .hhp file) to process some meta datas of .html file, so we need keep `<head>` tag using `cp1252` encoding, otherwise squares may appear in search result, please see the picture above.

What **Method C** does: escape non-ascii characters after `<head>` tag.

**Comment by ghost** [comment]
> Note: I still can't find what "Binary Index" and "Binary TOC" mean.

I guess it will pre-compile some data for better performance, I feel they are not important.

I'm going to sleep, too late.

**Comment by ghost** [comment]
After turning `Binary Index` to `Yes`:
* the .chm will generate a binary file `python371.chw` in the same folder of `python371.chm` when it first opened.
* if the .chm's directory is not writable, the .chw will be created, and later reused from, `%APPDATA%\Microsoft\HTML Help`

After turning `Binary TOC` to `Yes`:
* the compiler will create a extra file `#TOCIDX` inside .chm file.
![](https://raw.githubusercontent.com/animalize/pics/master/issues/TOC_Binary.PNG)

Maybe these two options bring better performance.

**Comment by ghost** [comment]
This is a quality patch for `htmlhelp_ascii_output` option:
https://github.com/animalize/sphinx/commit/74d2cccb71e62e14afe284960eaa942d546489a4

We don't need to hurry, please process this issue when you have time, even do it within a few months is ok.

**Comment by tk0miya** [comment]
>The option htmlhelp_ascii_output escapes non-ascii characters in .html output, to ensure no b'[\x80-\xFF]' bytes will be wrongly decoded.
>For example: under cp1252 encoding, “ is represented as b'\x93' in .html file. with this option, it will be represented as &#8220;, so “ will display correctly everywhere.

How about using htmlentities for non ASCII characters on CP1252?
For example, `“` (left double quotation) is represented as `&ldquo;` in HTML entities.

I think it is better to use ASCII and HTML entities instead of CP1252 (ISO-8859-1), especially for English.
https://www.w3schools.com/charsets/ref_html_8859.asp

**Comment by ghost** [comment]
>How about using htmlentities for non ASCII characters on CP1252?

Yes, the current Python .chm doc is using htmlentities as possible.
https://github.com/python/cpython/blob/v3.7.1/Doc/tools/extensions/escape4chm.py#L13-L20

But `html.entities` only aviliable sine Python 3.0, we need to write a different code path for Python 2.

BTW, I will add testcase for it later.

**Comment by AA-Turner** [comment]
From the linked PR

> I feel there are no reason to add a new option htmlhelp_ascii_output.
