### ISSUE TITLE
How to download site from the web to an offline server

### ISSUE THREAD

**Issue by Eldadc** [sphinx-doc/sphinx#5809]
Hi,

Is it possible to download the whole site build on sphinx to an offline site.

Thanks

**Comment by tk0miya** [comment]
If you have source of the document, you can build it locally.
If not, Sphinx itself does not provide a special way to do that.

Thanks,

**Comment by Eldadc** [comment]
Thanks for the follow up.
If iI download a site with some tools.
Is it possible to create a site on my own sphinx server on offline server ?

**Comment by tk0miya** [comment]
Please read our document first. Sphinx is not a "server".

In addition, this is an "issue" list of Sphinx, not a forum.
Please post to our forum if you still have question.

Thanks,
