### ISSUE TITLE
"Enter module/class/function name ..." is Python-specific

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#582]
The little hint below the quick search bar is not suited for projects that don't have Python docs in them.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/582
- Originally reported by: Georg Brandl
- Originally created at: 2011-01-05T17:25:09.132

**Comment by shimizukawa** [comment]
@birkenfeld do you have any ideas for usage message of search box?

**Comment by birkenfeld** [comment]
Actually I think the hint isn't really needed anymore.

**Comment by shimizukawa** [comment]
OK, I'm going to remove the hint for version 1.4 ;)
