### ISSUE TITLE
Standard element "Table of content" has not been localized

### ISSUE THREAD

**Issue by mgpcs** [sphinx-doc/sphinx#5836]
Standard element "Table of content" has not been localized

### Problem
The standard element "Table of content" (layout.html) has not been localized.
- html_theme = 'agogo'
- language = 'de'

#### Expected results
Localization for "Table of content" at language "de".

### Environment info
- OS: Win 10
- Python version: 3.6.5
- Sphinx version: 1.8.2

**Comment by tk0miya** [comment]
Surely it is not translated yet. If you can understand German, please join our translation project! We need your help :-)
https://www.transifex.com/sphinx-doc/

**Comment by jfbu** [comment]
I translated it into Inhaltsverzeichnis now... there remains many non translated chains for German https://www.transifex.com/sphinx-doc/

**Comment by tk0miya** [comment]
Thanks, jfbu!
This will be fixed in next major release. So I'm closing this now.
