### ISSUE TITLE
Support HTML Help Associative Links

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#584]
as described in http://www.mail-archive.com/sphinx-dev@googlegroups.com/msg02223.html

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/584
- Originally reported by: Georg Brandl
- Originally created at: 2011-01-05T17:39:27.821

**Comment by jdillard** [comment]
It seems like this issue can be closed due to inactivity. The OP most likely won't receive any notifications about answers anyways.

**Comment by shimizukawa** [comment]
Thanks for the suggestion. I'll close it.
