### ISSUE TITLE
LaTeX: custom document class ``\maketitle`` is overwritten with no possibility to keep its meaning 

### ISSUE THREAD

**Issue by matwei** [sphinx-doc/sphinx#5849]
Subject: When I try to access features from \maketitle, I'm limited to the version in sphinxmanual.cls

### Problem

I want to use certain features of \maketitle in srcbook.cls.
In particular I want some text on the backside of the title.
While scrbook supports this and scrbook can be used with Spinx,
the \maketitle command doesn't work as expected.

#### Procedure to reproduce the problem

Create an empty project and copy the following text into conf.py:

```
    latex_elements = {
    ...
        'maketitle': r'''
    \uppertitleback{
        This work is licensed under a Creative Commons\\
        Attribution-NonCommercial-ShareAlike 3.0 Unported License
    }
    \maketitle
    ''',
    }
    latex_docclass = {
       'manual': 'scrbook',
    }
```

Then run `make latexpdf`

#### Error logs / results

There is no copyright text on the back side of the title.

The \uppertitleback is ignored, because \maketitle is redefined in sphinxmanual.cls (and in sphinxhowto.cls).

#### Expected results

In the PDF output I expected the copyright text on the back side of the title.

### Workaround

It would be better to define and use a \sphinxmaketitle rather than \renewcommand the \maketitle. 

Replacing *sphinxmanual.cls* with a local version as was suggested by Jean-François in <https://groups.google.com/forum/#!topic/sphinx-users/F2eQYSw05tU> is a usable workaround.
The local version has to be placed into the source directory.

### Environment info
- OS: Ubuntu 18.04
- Python version: 2.7
- Sphinx version: 1.8.2 (installed with pip in a virtual environment)
- TeX Live from Ubuntu Repositories

**Comment by jfbu** [comment]
Thanks for detailed report, fixed at a77f344035b3cb18b9fe9a06e41059c654c7dafe.
