### ISSUE TITLE
Python code block with question mark (?) could not be highlighted

### ISSUE THREAD

**Issue by yoonghm** [sphinx-doc/sphinx#5855]
Subject: Sphinx could not highlight Python code block with question mark (?)

### Problem

Sphinx could not highlight Python code block with question mark (?)

#### Procedure to reproduce the problem

I have the following code block

```
..  code:: Python

    >>> a = 1.0
    >>> print(a, '=> integer? ', a.is_integer())
    1.0 => integer?  True
    >>> a = 1.1
    >>> print(a, '=> integer? ', a.is_integer())
    1.1 => integer?  False
```
If I remove the question mark from the *output*, it then works

```
..  code:: Python

    >>> a = 1.0
    >>> print(a, '=> integer? ', a.is_integer())
    1.0 => integer  True
    >>> a = 1.1
    >>> print(a, '=> integer? ', a.is_integer())
    1.1 => integer  False
```
#### Error logs / results
It produces error:  ```... WARNING: Could not lex literal_block as "Python". Highlighting skipped. ...```

#### Expected results

Remove any question mark (?) from the output.

### Reproducible project / your project
NIL

### Environment info
- OS: Windows 10
- Python version: 3.7
- Sphinx version:
- <Extra tools e.g.: Browser, tex or something else>

**Comment by tk0miya** [comment]
What version of Sphinx, docutils and pygments are you using?
On my local, it is highlighted correctly. Please let me know about your environment.
Thanks,

**Comment by yoonghm** [comment]
Hi @tk0miya I think the reason was caused by additional line ```..  highlight:: Python```. I attach the file here.
Thank you for check on the issue.
[test.zip](https://github.com/sphinx-doc/sphinx/files/2706023/test.zip)

**Comment by tk0miya** [comment]
Thank you for example.
It seems pygments expects "python" in lowercase. Could you change the name please?

**Comment by yoonghm** [comment]
[test.zip](https://github.com/sphinx-doc/sphinx/files/2706039/test.zip)
@tk0miya , it is working now after changing `Python` to `python`. Thanks.
