### ISSUE TITLE
make html does delete associated html when we delete an .rst file?

### ISSUE THREAD

**Issue by Chrisbuuren** [sphinx-doc/sphinx#5908]
Subject: make html does delete associated html when we delete an .rst file?

### Problem
Hello I have a question, does make html(sphinx-build) delete the associated html files for when we remove the .rst from source?

I saw that it adds the changes, but when we remove an .rst file, is there HTML file also removed from the build?

#### Procedure to reproduce the problem
```
make html
```

#### Expected results
to see what changed in the source files and remove associated HTML

### Environment info
- OS: Linux 18.04 Ubuntu Bionic
- Python version: 2.7
- Sphinx version: 1.8.2

**Comment by tk0miya** [comment]
+0

**Comment by Chrisbuuren** [comment]
Thank you very much!
