### ISSUE TITLE
CI error with  "raise child_exception"

### ISSUE THREAD

**Issue by pengxin99** [sphinx-doc/sphinx#5914]
Subject: <what happen when you do on which document project>

### Problem
- The ci work interrupt twice with this pr commit in [mxnet-pr12498](https://github.com/apache/incubator-mxnet/pull/12498) 
thanks for your time.

#### Procedure to reproduce the problem
```
<Paste your command-line here which cause the problem>
```

#### Error logs / results
```
/usr/local/lib/python2.7/dist-packages/recommonmark/parser.py:280: UserWarning: Unsupported inline type Hardbreak

  warn("Unsupported inline type " + inline.t)

reading sources... [ 41%] faq/develop_and_hack

reading sources... [ 41%] faq/distributed_training

reading sources... [ 42%] faq/env_var

reading sources... [ 42%] faq/faq

reading sources... [ 43%] faq/finetune

Converted 1 tables in faq/finetune

reading sources... [ 43%] faq/float16

reading sources... [ 44%] faq/gradient_compression

reading sources... [ 44%] faq/index

reading sources... [ 45%] faq/model_parallel_lstm

reading sources... [ 45%] faq/multi_devices

reading sources... [ 46%] faq/new_op

reading sources... [ 46%] faq/nnpack

Converted 1 tables in faq/nnpack

reading sources... [ 47%] faq/perf


Exception occurred:

  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child

    raise child_exception

OSError: [Errno 14] Bad address

The full traceback has been saved in /tmp/sphinx-err-DtF09X.log, if you want to report the issue to the developers.

Please also report this if it was a user error, so that a better error message can be provided next time.

A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!

Makefile:75: recipe for target 'html' failed

make[1]: *** [html] Error 1

make[1]: Leaving directory '/work/mxnet/docs'

Makefile:563: recipe for target 'docs' failed

make: *** [docs] Error 2

build.py: 2019-01-09 04:56:12,848Z INFO Waiting for status of container 9ab3db47b10b for 600 s.

build.py: 2019-01-09 04:56:13,144Z INFO Container exit status: {'Error': None, 'StatusCode': 2}

build.py: 2019-01-09 04:56:13,144Z ERROR Container exited with an error 😞

build.py: 2019-01-09 04:56:13,144Z INFO Stopping container: 9ab3db47b10b

build.py: 2019-01-09 04:56:13,146Z INFO Removing container: 9ab3db47b10b

build.py: 2019-01-09 04:56:13,384Z INFO Other running containers: ['fb57c720b496']

build.py: 2019-01-09 04:56:13,385Z CRITICAL Execution of ['/work/runtime_functions.sh', 'deploy_docs'] failed with status: 2

```
- <public link of unexpected result if you have>

#### Expected results
<Describe what to actually do>

### Reproducible project / your project
- <link to your project, or attach zipped small project sample>

### Environment info
- OS: <Unix/Linux/Mac/Win/other with version>
- Python version:
- Sphinx version:
- <Extra tools e.g.: Browser, tex or something else>

**Comment by tk0miya** [comment]
Please paste the full traceback file here. It helps us to investigate error.
Thanks,

**Comment by pengxin99** [comment]
The whole file is a bit big, and you can find the log [here](http://jenkins.mxnet-ci.amazon-ml.com/blue/rest/organizations/jenkins/pipelines/mxnet-validation/pipelines/website/branches/PR-12498/runs/10/nodes/73/steps/118/log/?start=0). @tk0miya

**Comment by tk0miya** [comment]
No, full stacktrace is generated as external file. Please see this line which you pasted.
```
The full traceback has been saved in /tmp/sphinx-err-DtF09X.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

If it is hard to get the error log,  You can see it on log with `-T` option to `sphinx-build` command.

BTW, it seems you're using very old Sphinx. How about upgrading it to newest one? It might be resolved.

>Running Sphinx v1.5.6

**Comment by pengxin99** [comment]
@tk0miya Thanks, and i cannot get the full stacktrace file. I will recommend the this repo to use a new version.

**Comment by tk0miya** [comment]
I'm closing this now.
Please feel free to reopen this if you're still in trouble.
Thanks,
