### ISSUE TITLE
`special-members` with `inherited-members` shows all default special methods

### ISSUE THREAD

**Issue by pitrou** [sphinx-doc/sphinx#5923]
When using `special-members` together with `inherited-members`, the default versions of special methods which were not specialized are shown, which means the doc for even the simplest class will list all special methods such as `__len__`, etc. (with a docstring such as "Return len(self).").

It would be nice if autodoc could detect that a special method was not defined and skip documenting it.

**Comment by tk0miya** [comment]
+1; Acceptable. IMO, it would be better not to display special methods defined in `object` class. I suppose nobody expects to display them.

**Comment by tk0miya** [comment]
I posted #6873 for this. But it brings incompatible changes to `:inherited-members:` option. So I'd like to merge it to 3.0 release.

**Comment by tk0miya** [comment]
Now #6873 is merged. I hope this helps your case. Thanks,
