### ISSUE TITLE
how to choose the directory which the autodoc use

### ISSUE THREAD

**Issue by wqh17101** [sphinx-doc/sphinx#5925]
my dir structure is below
-source
--conf.py
-A
--B
--C

A,B,C are three dirs
i want to use ```sphinx-apidoc -o source A``` to generate .rst file(A.rst,C.rst)
i do not want the B.rst
how can i do 
such as modifying the conf.py or use some options of sphinx-apidoc

**Comment by Chrisbuuren** [comment]
enter conf.py -> go to -> add your directory name

`#` List of patterns, relative to source directory, that match files and
`#` directories to ignore when looking for source files.
exclude_patterns = []

**Comment by Chrisbuuren** [comment]
Or from the CLI:

`(sphinx_env)` cristicatana@cristicatana-VirtualBox:~/workspace/sphinx_env/$ sphinx-apidoc --help
usage: sphinx-apidoc [OPTIONS] -o <OUTPUT_PATH> <MODULE_PATH> [EXCLUDE_PATTERN, ...]

Look recursively in <MODULE_PATH> for Python modules and packages and create
one reST file with automodule directives per package in the <OUTPUT_PATH>. The
<EXCLUDE_PATTERN>s can be file and/or directory patterns that will be excluded
from generation. Note: By default this script will not overwrite already
created files.

positional arguments:
  module_path           path to module to document
  **exclude_pattern       fnmatch-style file and/or directory patterns to exclude from generation**

**Comment by tk0miya** [comment]
How about `sphinx-apidoc -o source A A/B.py`?

**Comment by tk0miya** [comment]
I'm closing this now because this would not be a bug of Sphinx.
Please post a question to our forum in next time.
https://groups.google.com/forum/#!forum/sphinx-users

Thanks,
