### ISSUE TITLE
Is it possible to set file processing order?

### ISSUE THREAD

**Issue by skirpichev** [sphinx-doc/sphinx#5940]
It seems, sphinx always process sources in the alphabetical order.  This is an issue for sphinxcontrib-bibtex plugin, see [this](https://sphinxcontrib-bibtex.readthedocs.io/en/latest/usage.html#unresolved-citations-across-documents).  Renaming sources is an option (e.g. `literature.rst` to `zliterature.rst`), but may be it's possible to tell sphinx to process `literature.rst` in the end?

**Comment by tk0miya** [comment]
It can't be controled. Sphinx supports parallel build. So it is hard to promise users and extensions to the order. It would be better to handle other hook point. For example, you can use env-check-consistency event. It is emitted after all documents have read.
https://www.sphinx-doc.org/en/master/extdev/appapi.html#event-env-check-consistency

**Comment by skirpichev** [comment]
> you can use env-check-consistency event

Hmm, sphinxcontrib-bibtex can use this to process "bibliography" directive?

**Comment by tk0miya** [comment]
Yes, of course!

**Comment by skirpichev** [comment]
I was a little misguided by event's docstring (You can check consistency of metadata for whole of documents.), but in this case - new content will be generated (bibliography list).

Ok, thank you, I will try to implement suggested solution or/and point plugin devs to your suggestion.

**Comment by tk0miya** [comment]
Sorry for not explaining enough. The `env-check-consistency` event is mainly used to check consistency as our docs said. In addition to that, it is first event after reading phase. It means the handlers which handles it can process the whole of the document. It almost same as the end of reading reST file.

**Comment by skirpichev** [comment]
@tk0miya, are there other options?  Developers of the sphinxcontrib-bibtex claim that env-check-consistency runs [too late](https://github.com/mcmtroffaes/sphinxcontrib-bibtex/issues/134#issuecomment-527803296).
