### ISSUE TITLE
Let LaTeX be more rational in handling image dimensions

### ISSUE THREAD

**Issue by jfbu** [sphinx-doc/sphinx#5956]
Currently, here is situation for image directive with options width, height, scale:

- if neither width nor height, then `\sphinxincludegraphics` will make sure that the graphics width does not exceed "`\linewidth`", (after obeying ``:scale:`` option since Sphinx 1.5),

- if either width or height is explicitly set, then no rescaling happens. https://github.com/sphinx-doc/sphinx/blob/0081482eb7b65cb286afd6ed1c466990545226be/sphinx/texinputs/sphinx.sty#L704-L707

Recently an exception to this has been added (#5939): inside an admonition a too tall image can break the PDF build, so new macro `\sphinxsafeincludegraphics` is used which makes sure the height is never too tall. PR #5955 will improve this by making sure `\scalebox` is never used as it could ruin the cap on height, by increasing again the size.

I suggest that the "`\linewidth`" limitation should always be applied whether or not the user has added ``:width:`` and/or ``:height:`` option. Indeed these options mostly target usually HTML builds, and it does not make sense that they should be absolutely obeyed in LaTeX even if the page size (which can be modified) is too small.

And the height also should be limited to "`\textheight`", even outside of admonitions.

This is easy to do in LaTeX, because when one specifies both ``width=``, ``height=``, then with ``keepaspectratio`` keyword as last option, the `\includegraphics` macro will ensure that the image original aspect ratio is preserved and that width and height are maximal while obeying the specifications.

Basically, this all means (once #5955 is merged thus removing some complications with LaTeX handling of `scale=` option in presence of `width=` or `height=`) we should make `\sphinxincludegraphics` an alias for `\sphinxsafeincludegraphics` (the `\spx@image@maxheight` is by default set to `\textheight`): what this does is

- compute the graphics dimensions from user options,

- if width turns out bigger than "`\linewidth`", or  height bigger than "`\textheight`" (or suitably smaller value if picture inside a frame), then downscale picture (keeping aspect ratio) so that it fits.

The only thing to decide I see is this: when user specifies both ``:width:`` and ``:height:`` and those are not too big, the picture will obey exactly the user demands, hence possibly get distorted ; if one or both are too bigs, the code will give a picture keep same aspect ratio as native dimensions, fitting in both width and height. Thus

- Q1: should Sphinx, in case both ``:width:`` and ``:height:`` are specified and one or both are too big, keep the aspect ratio ``height/width`` corresponding to user specifications, or keep the native aspect ratio? The former is more complicated for LaTeX, the latter is easy (already implemented by `\sphinxsaveincludegraphics`).

- Q2: if Q1 is answered by keeping native aspect ratio, shouldn't then Sphinx for LaTeX pictures *always* preserve aspect ratio, thus *always* handle the user specified ``:width:`` and ``:height:``  only as upper limits, even if they fit with no rescaling on the page ? This is tempting, but will break user expectations as HTML distorts the picture in such cases. Thus my guess is that the answer to Q2 should be "no".

**Comment by tk0miya** [comment]
Q1. The spec of image directive does not mention about aspect ratio (ref: 
http://docutils.sourceforge.net/docs/ref/rst/directives.html#image ). But the implementation of docutils (`rst2html.py`, `rst2latex.py` and so on) uses given `width` and `height` via directive options as new aspect ratio. Basically, Sphinx would be better to follow this behavior. So it would be better to follow directive options even if too big.

>The former is more complicated for LaTeX

I know, but Sphinx can use the power of Python. For example, we can generate resized image on LaTeX builder if Pillow has been installed.

**Comment by jfbu** [comment]
Thanks for advice. It is not too complicated on LaTeX side, we can do the needed computation with LaTeX code. It will slightly complicate `\sphinxincludegraphics` that's all. I will make PR in future. 

Also, I will take this  opportunity to fix a TeXnical thing that `\includegraphics` does not produce the exact dimensions requested by `width` and `height` but some approximation which sometimes make be bigger than requested value and can cause in some circumstances TeX to move the image down by one blank line or even to push it to next page. See https://github.com/latex3/latex2e/issues/112. The Sphinx version will simply reset the box dimensions after it comes back from `\includegraphics` to fix that upstream issue. (it [can show](https://www.latex-project.org/cgi-bin/ltxbugs2html?category=LaTeX&responsible=anyone&state=open&keyword=&pr=graphics%2F4451&search=) in `\begin{center}..\end{center}` but I have not set-up an example with Sphinx as it is rare). Pardoxically the problem with `height` of produced box possibly larger than requested `height` is not a problem in the context of #5936 because the requested `height` is safely enough smaller than error-triggering  height so the mismatch on output of `\includegraphics` is of no concern.
