### ISSUE TITLE
Sphinx Markdown MathJax doesn't work correctly

### ISSUE THREAD

**Issue by zjZSTU** [sphinx-doc/sphinx#5957]
**Describe the bug**
1. use sphinx-quickstart create a new project，add the **mathjax support**
2. Reference to official documents for **markdown**: [Markdown](https://www.sphinx-doc.org/en/master/usage/markdown.html?highlight=markdown)
3. in markdown.md files，MathJax doesn't work correclty 
          3.1 the Inline Notes on Math Formula $...$ doesn't work
          3.2 if there are several rows math formula， $$...$$, doesn't work

**To Reproduce**

step1: $f(\tau )$ can't work fine
step2: The following mathematical formulas can't be displayed correctly either.

$$
f(\tau )
f(\tau )
f(\tau )
$$

**Your project**

page 1: [Markdown使用-5 数学公式](https://zj-markdown-guide.readthedocs.io/zh/latest/Markdown%E4%BD%BF%E7%94%A8-5-%E6%95%B0%E5%AD%A6%E5%85%AC%E5%BC%8F.html)
page2: [充分条件-必要条件](https://zj-computer-foundation.readthedocs.io/zh_CN/latest/maths/%E5%85%85%E5%88%86%E6%9D%A1%E4%BB%B6-%E5%BF%85%E8%A6%81%E6%9D%A1%E4%BB%B6.html)

**Environment info**

- OS: Ubuntu 16.04
- Python version: 3.7.1
- Sphinx version: 1.8.2
- Sphinx extensions:  sphinx.ext.mathjax, recommonmark

**Comment by tk0miya** [comment]
Sphinx itself does not support markdown. So this would be a bug of recommonmark.
Please post this to their project.
Thanks,

**Comment by zjZSTU** [comment]
> Sphinx itself does not support markdown. So this would be a bug of recommonmark.
> Please post this to their project.
> Thanks,

ok, i'll try
