### ISSUE TITLE
BUG: numpydoc + autosumarry broken

### ISSUE THREAD

**Issue by larsoner** [sphinx-doc/sphinx#5959]
#4611 broke rendering for me of a `numpydoc` + `autosummary` `html` build where the input is like:
```
...
    Parameters
    ----------
    data : array, shape (n_chan,)
        The data values to plot.
...
```
Which `numpydoc` turns into something like:
```
...
:Parameters:

    **data** : array, shape (n_chan,)
        The data values to plot.
...
```
On the commit in `master` before this (b04bfcfab7b4a47dca1a5c9dda88e810ffc81bcd) I get the correct output with `:` between items:

![screenshot from 2019-01-15 15-03-42](https://user-images.githubusercontent.com/2365790/51206714-c6452900-18d6-11e9-8044-fe1d1a9a67c1.png)

On `master` after this PR (on commit 7459d8771af1afaf6c2342b689fb70a56ba00efa) the colon is gone (`<span>` missing in output):

![screenshot from 2019-01-15 14-57-04](https://user-images.githubusercontent.com/2365790/51206359-dad4f180-18d5-11e9-8ca6-a0f5170c1888.png)

I'm not sure how to fix this because I'm out of my depth, though :(

**Comment by jschueller** [comment]
I confirm the bug with the current master, the colon removed in the html output:
```
-<dt><strong>problem</strong> <span class="classifier-delimiter">:</span> <span class="classifier"><a class="reference internal" href=...
+<dt><strong>problem</strong><span class="classifier"><a class="reference internal" href=...
```

http://openturns.github.io/openturns/latest/user_manual/_generated/openturns.AbdoRackwitz.html
http://openturns.github.io/openturns/master/user_manual/_generated/openturns.AbdoRackwitz.html


cc @regislebrun, @sofianehaddad

**Comment by tk0miya** [comment]
Thank you for reporting.
I just post #5976 to fix this. Please try it out.
Thanks,
