### ISSUE TITLE
Inquiry on embed reStructuredText source code line numbers in generated HTML pages

### ISSUE THREAD

**Issue by lextm** [sphinx-doc/sphinx#5965]
**Is your feature request related to a problem? Please describe.**
I am working on the VSCode extension for reStructuredText,

https://github.com/vscode-restructuredtext/vscode-restructuredtext

It supports previewing HTML pages in this way,

1. Call sphinx in the background to compile the source files.
1. Load the generated HTML pages for preview.

One feature I want to improve is synchronized preview scrolling, which means when an HTML page in preview panel is scrolled, the editor can be scrolled automatically to a suitable location.

Microsoft implemented such for Markdown, where there is a way to embed Markdown file line numbers in the generated HTML page.

I want to do the same for reStructuredText/sphinx. However, currently in the generated HTML pages there are no such line numbers, and sphinx documentation does not have any indication of such a feature.

Is this already a hidden feature or it still needs some effort to be implemented?

I can provide more information if needed.

**Comment by tk0miya** [comment]
>Is this already a hidden feature or it still needs some effort to be implemented?

Sphinx does not have such feature. So we need to implement it. Fortunately, the doctree which is internal data structure of Sphinx contains line numbers as its properties. So you can convert them into `id` or other attributes.

On the other hand, I don't know this is commonly used feature or not. So I propose you to implement this as an extension.

Note: Sphinx ignores line breaks in paragraph on parsing. So the line numbers we can get from doctree are the line which the paragraph starts.

**Comment by tk0miya** [comment]
This is a sample implementation for your idea. This adds `line-%d` class to each paragraph node. What do you think?
```
from docutils import nodes
from docutils.transforms import Transform


class LineNumberTransform(Transform):
    default_priority = 500

    def apply(self):
        for node in self.document.traverse(nodes.paragraph):
            if node.line:
                node['classes'].append('line-%d' % node.line)


def setup(app):
    app.add_transform(LineNumberTransform)
```

**Comment by lextm** [comment]
Thank you very much for pointing out what I should try. I will follow your advice and see what I can work out.
