### ISSUE TITLE
mathjax not loaded?

### ISSUE THREAD

**Issue by Jellby** [sphinx-doc/sphinx#5966]
**Describe the bug**
When the documentation is compiled inside a GitLab CI runner, mathjax is not added to the HTML header, but compiling locally, even using *the same docker image*, includes mathjax. This becomes really difficult to debug. What in the environment could make mathjax present or not?

**To Reproduce**
I can't reproduce it, at least not locally

**Expected behavior**
The generated HTML should contain mathjax regardless of where it is compiled.

**Your project**
https://gitlab.com/Molcas/OpenMolcas

**Screenshots**
(rather code-shots)

The GitLab-built documentation: https://molcas.gitlab.io/OpenMolcas/sphinx/users.guide/programs/single_aniso.html contains in the header:

```
    <script type="text/javascript" src="../../_static/language_data.js"></script>
    <script type="text/javascript" src="../../_static/styleswitcher.js"></script>
```

while, when I compile locally:

```
    <script type="text/javascript" src="../../_static/language_data.js"></script>
    <script async="async" type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/latest.js?config=TeX-AMS-MML_HTMLorMML"></script>
    <script type="text/javascript" src="../../_static/styleswitcher.js"></script>
```

**Environment info**
- OS: Linux
- Python version: 2.7
- Sphinx version: 1.8.3
- Sphinx extensions:  mathjax

**Comment by tk0miya** [comment]
It seems your document has its own custom theme.
https://gitlab.com/Molcas/OpenMolcas/blob/master/doc/source/_theme/molcas/layout.html

And it has overrided `script_files`. I don't recommend that. Please use `app.add_js_file()` API instead.

**Comment by Jellby** [comment]
Yes, I should update it, but I don't think it has anything to do here. However, after a couple of retries now it seems to work. I haven't changed anything in the code, theme or environment (same docker image), so maybe it was a glitch. If you can think of any reason why something like this could happen, I guess you can close this, and I may report back if it happens again.

**Comment by Jellby** [comment]
Actually, I can kind of reproduce it locally, although I'm not sure this is the same I was seeing before:

`make html`

Input files are parsed, environment is pickled, consistency is checked (*here is where mathjax is installed*), and output files are generated. I get a mathjax line in the html files.

Now I touch layout.html, and run `make html` again. Pickled environment is loaded, no outdated files are found, output is written. But now, there is no consistency check, so mathjax is not installed, and indeed I get no mathjax line in the html files.

When I get some more quality time I can try to create a small test case, if needed.

**Comment by Jellby** [comment]
Just a default setup with `sphinx-quickstart`, enabling mathjax and adding some math in `index.rst` results in:

`make latex`
`make html`
(no mathjax included)
`touch index.rst`
`make html`
(mathjax included)

**Comment by Jellby** [comment]
> although I'm not sure this is the same I was seeing before

It probably is. What happened is that I was compiling both pdf and html versions, generated as CMake targets, and the order in which these are run is apparently arbitrary. If the html version is compiled first, everything goes fine, but if the pdf goes first, then it's the same as above.

**Comment by tk0miya** [comment]
Thank you for nice report. I can also reproduced on my local.
And I just posted #5975 as a fix for this. Could you check it please?
Thanks,

**Comment by Jellby** [comment]
Works fine, as far as I can see. Thanks.

**Comment by tk0miya** [comment]
Thank you for confirmation :-)
I'll release it as 1.8.4 soon. Please wait a moment.
