### ISSUE TITLE
Docs don't specify how to add table of contents in a markdown index file

### ISSUE THREAD

**Issue by ghost** [sphinx-doc/sphinx#5982]
**Describe the bug**
The docs of sphinx don't specify how to add table of contents in a markdown index file.

I would have expected this information at least somehow mentioned/linked from here:
https://www.sphinx-doc.org/en/master/usage/quickstart.html#defining-document-structure
(like add some "when using markdown..." box/paragraph/note that sends me the right way)

And some more detail information possibly here:
https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#toctree-directive
(that page doesn't even appear to mention markdown anywhere)

**To Reproduce**
1. Go to https://www.sphinx-doc.org/en/master/usage/quickstart.html#defining-document-structure and try to figure out what you are supposed to do when using markdown
2. Go to https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#toctree-directive and try to figure out what you are supposed to do when using markdown

**Expected behavior**
Docs contain necessary information, or at least I can't find it in the linked places where I would have expected it

**Your project**
Applies to any project

**Screenshots**
See links above

**Environment info**
Not really relevant I believe (but I'd be happy to add it)

**Additional context**
none

**Comment by tk0miya** [comment]
Wait, sphinx does not support markdown format officially. So we should not mention about it.
It is responsibility of recommonmark docs.

In addition, AFAIK, there are no proper way to define ToC in markdown. Only you can do is adding AutoStructify component manually. But it breaks compatibility of markdown format. Personally, I don't think it is recommended way.

**Comment by ghost** [comment]
@tk0miya so how can I enable AutoStructify manually? I don't even know what that is. I found this here but it doesn't say "write this into your markdown" or similar: https://recommonmark.readthedocs.io/en/latest/auto_structify.html#auto-toc-tree Edit: sorry, are the docs saying just *any* link list will become a TOC? I'm really unsure about how this is supposed to be used like without an example, and the index.md mentioned isn't actually a link

It would be really cool if at least the page that mentions markdown had an example of this, because it's really not obvious how to do it (that page being this one https://www.sphinx-doc.org/en/master/usage/markdown.html )

**Comment by tk0miya** [comment]
Sorry, I can't answer you how recommonmark works. Because I've never used the extension. Only I know is the document says AutoStructify helps to create ToC as you mentioned. Please ask about that to recommonmark team. They can answer it better than us.

**Comment by ghost** [comment]
For what it's worth, this is a related upstream bug I filed now: https://github.com/rtfd/recommonmark/issues/135 (just in case anyone ends up here via google or something)

**Comment by TimKam** [comment]
Thanks, @JonasT. I will close this issue then.
