### ISSUE TITLE
Support custom variable in templates

### ISSUE THREAD

**Issue by jaraco** [sphinx-doc/sphinx#5986]
**Description**

I'd like to include a link using the `package_url` (from config) in a template. I'm using an HTML sidebar configured thus:

```
extensions = ['jaraco.packaging.sphinx']
html_sidebars = {'index': 'indexsidebar.html'}
```

In that template, I'd like to have:

```
<p>Visit the <a href="{{ package_url }}">Project page</a> </p>
```

Reading the docs, I see that `version` and `project` and `version` are present, but the package URL is not.

I tried using `{{ url }}` and `{{ package_url }}`, but the result is an empty string, same as if I'd done `{{ anything }}`.

I also tried `{{ config.package_url }}` and `{{ app.config.package_url }}`, but that resulted in an error during the build.

**Proposed Solution**

For this need, I only need `package_url` to be exposed as a global variable. A more general solution that exposes anything in `config` might be better.

**Considerations**

Reading the docs, I don't see any mechanism that enables new names in templates, and there's nothing proximate to the Global Variables documentation that suggests there are any variables other than those documented on which one can rely.

**Comment by jaraco** [comment]
Digging a little deeper, I see now that `package_url` isn't a standard construct but is instead [injected by a plugin](https://github.com/jaraco/jaraco.packaging/blob/7d26360dd59ae6eb93e9db52bea05cb3d6772e5a/jaraco/packaging/sphinx.py#L12-L36). So perhaps the best solution would be for the plugin to somehow add that variable to the template's globals.

**Comment by jaraco** [comment]
After a bit more investigation, I found I was able to, using standard hooks for the plugin, [expose that variable to the template](https://github.com/jaraco/jaraco.packaging/commit/c84fd1282b222bc262a2bab7a2e668c947472f46).

**Comment by tk0miya** [comment]
Yes, `html-page-context` event may help you :-)
