### ISSUE TITLE
mechanism for specifying that a given doc string is for developers only

### ISSUE THREAD

**Issue by Phillip-M-Feldman** [sphinx-doc/sphinx#5988]
I'd like to have a mechanism for specifying that a given doc string is for developers only.  When Sphinx parses the source code, it would skip such doc strings.

**Comment by tk0miya** [comment]
How about `only` directive? Then the docstrings are not shown for user documents.
https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-only

**Comment by Phillip-M-Feldman** [comment]
From the documentation, it appears that the only directive should do what I
want, but I have not been able to figure out how to control the scope.
(I'd like to make the scope apply to the triple-quoted doc string that
immediately follows the directive, but haven't been able to make this work).

**Comment by tk0miya** [comment]
The `only` directive allows to show or hide given paragraph via tag settings.
For example, following paragraph is displayed only if `-t for_developers` given to `sphinx-build` command:
```
This paragraph is always shown.

.. only:: for_developers

   Usually, this paragraph is hidden.
```

You can use the directive even inside python docstring :-)

**Comment by Phillip-M-Feldman** [comment]
OK.  I think that I will have to take the route of a custom preprocessor.
I see that there are instructions for this at
http://www.sphinx-doc.org/en/master/extdev/index.html#dev-extensions

Thanks!

**Comment by Phillip-M-Feldman** [comment]
I ended up using pcpp (see https://github.com/ned14/pcpp) to hide doc strings that I don't want Sphinx to see, and that approach seems to work.
