### ISSUE TITLE
Enable sphinx-build to use environment variables for certificates (Requests/urllib2)

### ISSUE THREAD

**Issue by espoelstra** [sphinx-doc/sphinx#5993]
It appears that although Sphinx uses `Requests` a user may still need to set the certificate directory in their conf.py manually via a `tls_cacerts = '/path/to/your/certs'` as it doesn't appear to honor the `REQUESTS_CA_BUNDLE` or the other SSL environment variables commonly used to pass trusted certs. This has made using `sphinx-build linkcheck` very tricky in an enterprise environment with a proxy, especially with some of the resources also require a login to view, and hardcoding the login credentials anywhere is a bad idea.

It would be good to document whether it supports a directory of certificates in the openssl style ie `/usr/local/etc/openssl/certs` or if it requires a bundle of all the certs in a single `cacerts.pem` file.

**Comment by tk0miya** [comment]
+1; Resonable. But we need to investigate what variable is commonly used for cert-files.

**Comment by tk0miya** [comment]
As a trial, I set `REQUESTS_CA_BUNDLE` locally. And it seems working fine. Is really not working on your environment? Did you set `tls_cacerts`? If true, Sphinx preferentially use it.

**Comment by tk0miya** [comment]
I'm closing this now because it is working well.
