### ISSUE TITLE
generated html refers to function by alias

### ISSUE THREAD

**Issue by Phillip-M-Feldman** [sphinx-doc/sphinx#5994]
My module contains a function called `Kolmogorov_Smirnov_1`.  Following the definition of the function, there is a line of code that defines an alias:

`KS1= Kolmogorov_Smirnov_1`

In the generated html, the documentation for this function appears under the name `KS`.  Is there any way to force Sphinx to use the function name that appears in the `def` statement?

**Comment by tk0miya** [comment]
What extension did you use? How did you write your document?
There are no reproducible information. So I can't help you.
Please fill our issue template please.

Thanks,
