### ISSUE TITLE
Autodoc: Metaclass conflict with multiple inheritance

### ISSUE THREAD

**Issue by justusschock** [sphinx-doc/sphinx#5995]
**Describe the bug**
Generating docs of a class, which is inherited from multiple classes does not work, if one of the base classes is mocked by autodoc.

The error message is 
`TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses ofall its bases` 

although both base classes have `type` as their metaclass.

**To Reproduce**
```
$ git clone https://github.com/justusschock/delira
$ cd delira/
$ git checkout tf_update_docs
$ cd docs
$ pip install -r requirements.txt
$ make html
```
**Expected behavior**
A working build with generated docs

**Your project**
https://github.com/justusschock/delira

**Environment info**
- OS: Ubuntu 18.04
- Python version: 3.7.1
- Sphinx version: 1.8.3/1.7.9/1.7.0 (happes with all of them)
- Sphinx extensions:  [sphinx.ext.autodoc, sphinx.ext.autosummary, sphinx.ext.intersphinx, sphinx.ext.ifconfig, sphinx.ext.viewcode, sphinx.ext.githubpages, sphinx.ext.napoleon, sphinx.ext.inheritance_diagram, sphinx.ext.autosectionlabel]
- Extra tools: Chrome (for displaying not necessary for building)

**Additional context**
The same build works with sphinx==1.5.3 if all submodules are added to autodoc_mock_imports

**Comment by tk0miya** [comment]
reproduced with following Dockerfile:
```
FROM python:3.7

RUN git clone https://github.com/justusschock/delira
WORKDIR /delira
RUN git checkout tf_update_docs
WORKDIR /delira/docs
RUN pip3 install -r requirements.txt
RUN make html
```
```
WARNING: autodoc: failed to import function 'training.train_utils.create_optims_default_tf' from module 'delira'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/delira/delira/__init__.py", line 59, in <module>
    from .models import AbstractNetwork
  File "/delira/delira/models/__init__.py", line 1, in <module>
    from .abstract_network import AbstractNetwork
  File "/delira/delira/models/abstract_network.py", line 140, in <module>
    class AbstractPyTorchNetwork(AbstractNetwork, torch.nn.Module):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```

**Comment by tk0miya** [comment]
Note: This is minimal code to reproduce the error:
```
import abc
from sphinx.ext.autodoc.importer import _MockObject

MockedClass = _MockObject()

class Base:
    @abc.abstractmethod
    def __init__(self):
        pass

class Derived(Base, MockedClass):
    pass
```

**Comment by tk0miya** [comment]
Fixed by #5998. (Note: it works only with py37+)
Thank you for reporting!

**Comment by saffa19** [comment]
How come this doesn't work for 3.6?

**Comment by tk0miya** [comment]
@saffa19 It seems nobody reports that. Could you file a new issue please? I'll take a look later.
