### ISSUE TITLE
<what happen when you do on which document project>

### ISSUE THREAD

**Issue by Shambho-Jobs** [sphinx-doc/sphinx#5999]
**Describe the bug**

**To Reproduce**
```
<Paste your command-line here which cause the problem>

$ git clone htps://github.com/.../some_project
$ cd some_project
$ pip install -r requirements.txt
$ cd docs
$ make html SPHINXOPTS="-D language=de"
$ # open _build/html/index and see bla bla
```

**Expected behavior**

**Your project**
Link to your sphinx project, or attach zipped small project sample.

**Screenshots**

**Environment info**
- OS: [e.g. Unix/Linux/Mac/Win/other with version]
- Python version: [e.g. 3.7.1]
- Sphinx version: [e.g. 1.8.2]
- Sphinx extensions:  [e.g. sphinx.ext.autodoc, recommonmark]
- Extra tools: [e.g. Browser, tex or something else]

**Additional context**

- [e.g. URL or Ticket]

**Comment by shimizukawa** [comment]
please fill issue information.
