### ISSUE TITLE
LaTeX does not wrap long code lines at backslash character

### ISSUE THREAD

**Issue by jfbu** [sphinx-doc/sphinx#6001]
There is no line-wrapping at ``\`` in code-blocks.

```rest
::

   \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
```
produces this via `make latexpdf`

![capture d ecran 2019-02-02 a 15 14 46](https://user-images.githubusercontent.com/2589111/52165168-71d6e180-26fd-11e9-835b-597682d3e505.png)

**Additional context**

- #6000

Not sure if qualifies at bug, so currently labelling it as feature request.

**Comment by tk0miya** [comment]
I think this must be "a bug", but minor. So it is better to mark this as "prio:low" and "bug".

**Comment by jfbu** [comment]
Fixed at https://github.com/sphinx-doc/sphinx/commit/a7f53a7957968e9f7daa3678ea695213af3e296e
