### ISSUE TITLE
Our docs does not update at RTD

### ISSUE THREAD

**Issue by jfbu** [sphinx-doc/sphinx#6003]
See https://readthedocs.org/projects/sphinx/

![capture d ecran 2019-02-02 a 17 35 16](https://user-images.githubusercontent.com/2589111/52166719-0991fb00-2711-11e9-800f-4ca335ba5de7.png)

**Comment by stsewd** [comment]
I'm guessing you are using the old webhook with the deprecated github services

https://docs.readthedocs.io/en/latest/webhooks.html#i-was-warned-i-shouldn-t-use-github-services

**Comment by TimKam** [comment]
If I understand the docs correctly, we need somebody with admin permissions to this GitHub project to configure the new web hook. @tk0miya?

**Comment by tk0miya** [comment]
Thank you for letting me know. I just update the settings for webhook.
It seems fixed :-)

**Comment by tk0miya** [comment]
Reopened.

The builds are often failed. It seems the error comes from inside readthedocs.
https://readthedocs.org/projects/sphinx/builds/

**Comment by TimKam** [comment]
I _wiped_ the builds for *master* and *latest* and triggered re-builds. The builds succeeded. So I guess it was an issue with the build environment and switches between old and new hooks. I will close this issue for now.
