### ISSUE TITLE
Class member constants defined inside tuples cannot be documented properly

### ISSUE THREAD

**Issue by k-yaegashi** [sphinx-doc/sphinx#6020]
**Describe the bug**

When documenting constants of class member defined inside tuples using autodoc function and comment docstrings, only the first constant is documented and all subsequent constants are overwritten with the first constant's documentation.

**To Reproduce**
```
mkdir /path/to/empty/directory
cd /path/to/empty/directory
sphinx-quickstart -q -p 'Test' -a 'Test Author' .
vim test.py     # See below
vim conf.py     # See below
vim index.rst   # See below
make html
```

`test.py`:
```
class TestClass(object):

    """
    This class is defined to check whether comment docstrings
    defined in the tuple works well. If it works, the English
    constants are documented as corresponding integers.
    Otherwise, ``autodoc`` function may have some kind of problem.
    """

    (
        #: This is 1.
        I_01_FIRST,
        #: This is 2.
        I_02_SECOND,
        #: This is 3.
        I_03_THIRD,
        #: This is 4.
        I_04_FORTH,
        #: This is 5.
        I_05_FIFTH
    ) = range(1, 6)

    (
        I_06_SIXTH,    #: This is 6.
        I_07_SEVENTH,  #: This is 7.
        I_08_EIGHTH,   #: This is 8.
        I_09_NINTH,    #: This is 9.
        I_10_TENTH     #: This is 10.
    ) = range(6, 11)
```

`conf.py`: Remove from comment to expose:
```
import os
import sys
sys.path.insert(0, os.path.abspath('.'))
```
and add an extension:
```
extensions = [
    'sphinx.ext.autodoc'
]
```

`index.rst`: Put the following lines somewhere:
```
.. automodule:: test
   :members:
```

The project produces the following output:

> **I_01_FIRST** = *1*
> This is 1.
>
> **I_02_SECOND** = *2*
> This is 1.
>
> **I_03_THIRD** = *3*
> This is 1.
>
> **I_04_FORTH** = *4*
> This is 1.
>
> **I_05_FIFTH** = *5*
> This is 1.
>
> **I_06_SIXTH** = *6*
> This is 6.
>
> **I_07_SEVENTH** = *7*
> This is 6.
>
> **I_08_EIGHTH** = *8*
> This is 6.
>
> **I_09_NINTH** = *9*
> This is 6.
>
> **I_10_TENTH** = *10*
> This is 6.

**Expected behavior**
> **I_01_FIRST** = *1*
> This is 1.
>
> **I_02_SECOND** = *2*
> This is 2.
>
> **I_03_THIRD** = *3*
> This is 3.
>
> **I_04_FORTH** = *4*
> This is 4.
>
> **I_05_FIFTH** = *5*
> This is 5.
>
> **I_06_SIXTH** = *6*
> This is 6.
>
> **I_07_SEVENTH** = *7*
> This is 7.
>
> **I_08_EIGHTH** = *8*
> This is 8.
>
> **I_09_NINTH** = *9*
> This is 9.
>
> **I_10_TENTH** = *10*
> This is 10.

**Your project**
[sphinx-test.zip](https://github.com/sphinx-doc/sphinx/files/2831328/sphinx-test.zip)

**Screenshots**
![sphinx-test](https://user-images.githubusercontent.com/2884380/52261497-f1b6b300-296c-11e9-9ded-9ffe3ff19e4e.png)

**Environment info**
- OS: macOS 10.12.6
- Python version: 3.6.4
- Sphinx version: 1.8.4
- Sphinx extensions: sphinx.ext.autodoc
- Extra tools: None

**Additional context**
None

**Comment by tk0miya** [comment]
autodoc expects the comment is placed before assignment or after assignment:
```
#: before assignment
a = 1

b = 2  #: after assignment
```
So this style assignment does not supported.

I feel this style code will be replaced by enum class. So -0 to support the notation.

**Comment by tk0miya** [comment]
No opinions are posted. So closing now.
