### ISSUE TITLE
Specifying tocdepth doesn't influence the sidebar TOC depth on that page

### ISSUE THREAD

**Issue by jorisvandenbossche** [sphinx-doc/sphinx#6033]
**Describe the bug**

I am trying to use `:tocdepth:` to specify the depth of the toctree in the sidebar on a specific page. However, whatever depth I specify, it doesn't make the toctree on that page deeper.

Example set-up of my docs is here: https://github.com/jorisvandenbossche/sphinx-test/tree/master/test-toctree 
So basically, I have a subdirectory with pages. And on those individual pages, I want that the sidebar toc also shows additional toc levels for the sections on that page. 
On the main `index.rst` page, I included the toc with a `:maxdepth: 2`, because on the body of that page, I want to show only a limited table of contents of the site.

**To Reproduce**

```
$ git clone https://github.com/jorisvandenbossche/sphinx-test
$ cd sphinx-test/test-toctree
$ make html
$ # open _build/html/user_guide/page1.html
```

**Expected behavior**

I would expect that a `:tocdepth:` on a certain page would overrule the `:maxdepth:` of a toctree in the sidebar. 

However, it might be that my expectation is wrong. If so, it is not fully clear to me what the purpose is of `:tocdepth:`, and the documentation saying "The maximum depth for a table of contents of this file." ([docs](https://www.sphinx-doc.org/en/master/usage/restructuredtext/field-lists.html?highlight=tocdepth)) is also not that very clarifying.

But, going from some old threads on sphinx-users (eg https://groups.google.com/forum/#!searchin/sphinx-users/tocdepth|sort:date/sphinx-users/SqY5O0jM1JA/i74RIRoIBwAJ or https://groups.google.com/forum/#!searchin/sphinx-users/tocdepth|sort:date/sphinx-users/TzfuzcDo7Hs/RUOiOtIGI04J), I understand that `:tocdepth:` should be able to control the depth of the sidebar TOC.

**Environment info**
- OS: Linux (Ubuntu)
- Python version: 3.5.5
- Sphinx version: 1.8.1

**Comment by ghost** [comment]
@jorisvandenbossche That seems to be an issue with the theme: https://github.com/bitprophet/alabaster/issues/89

Do you have the same issue with other themes?

When testing this with [sphinx_rtd_theme](https://github.com/rtfd/sphinx_rtd_theme) I found that setting `tocdepth` seems to influence the sidebar depth no matter what page I'm on, which seems like a bug in of itself. But I think the particular issue you're dealing with is an issue with alabaster or whatever theme you're using.

**Comment by segevfiner** [comment]
On my own project, this is bugging out differently. Setting `tocdepth` seems to cause it to be set to 1, or something like that, for the sidebar. But my docs are only two pages so who knows what buggy behavior this really exhibits on my end.

Sphinx 2.1.2
Python 3.7.4

**Comment by danielhuppmann** [comment]
Seems that using https://pypi.org/project/sphinxcontrib-fulltoc/ also resolves this issue.

**Comment by tk0miya** [comment]
Confirmed. Indeed `:tocdepth:` is not applied to HTML output.

In my short investigation, it modifies the depth of *local* toctree. But alabaster uses *global* toctree instead. So `:tocdepth:` feature is disabled on the theme. For example, you can see the its behavior when you switches the theme of your project to `classic`.

I agree with you that our document is not kind. So I'll update it to mention about above behavior later.

**Comment by tk0miya** [comment]
I just added a note to our document. Closing.
Thanks,
