### ISSUE TITLE
latexpdf image :target: changes output

### ISSUE THREAD

**Issue by FearTheBadger** [sphinx-doc/sphinx#6067]
**Describe the bug**
When I add the :target: to the image construct in an *.rst file, the tex file changes how text following an image is represented. The tex files ignores the image alignment, and the text directly after the image is no longer on a new line.

To be more specific here is the tex output between the two. The noindent is missing, as well as a blank new line when you include the :target: tag in the *.rst file.

*.tex without the :target:
```
\section{Example}
\label{\detokenize{docs/readme:test}}\label{\detokenize{docs/readme:test1}}\label{\detokenize{docs/readme::doc}}
\noindent{\hspace*{\fill}\sphinxincludegraphics[width=184\sphinxpxdimen]{{logo}.png}\hspace*{\fill}}

\sphinxhref{https://www.example.com}{Example} Test
```

*.tex with :target:
```
\section{Example}
\label{\detokenize{docs/readme:test}}\label{\detokenize{docs/readme:test1}}\label{\detokenize{docs/readme::doc}}\sphinxhref{https://www.example.com}{\sphinxincludegraphics[width=184\sphinxpxdimen]{{logo}.png}}
\sphinxhref{https://www.example.com}{Example} Test
```

**To Reproduce**
*.rst file with target
```
.. image:: logo.png
    :target: https://www.example.com
    :alt: Logo
    :align: center
    :width: 184px

`example <https://example.com>`_ test
```

*.rst file with target
```
.. image:: logo.png
    :alt: Logo
    :align: center
    :width: 184px

`example <https://example.com>`_ test
```

**Expected behavior**
The image should be a link to the URI provided and the text should be on a new line.

**Screenshots**
With :target:
![screen shot 2019-02-12 at 12 49 17 pm](https://user-images.githubusercontent.com/3730852/52663809-ac423a80-2ec4-11e9-8ade-e7f861882aaf.png)

Without :target:
![screen shot 2019-02-12 at 12 50 08 pm](https://user-images.githubusercontent.com/3730852/52663837-c419be80-2ec4-11e9-9784-5b046e022a0d.png)

**Environment info**
- OS: Ubuntu 16.04
- Python version: 2.7.15rc1
- Sphinx version: sphinx-build 1.8.4
- Sphinx extensions: n/a
- Extra tools: texi2pdf (GNU Texinfo 6.5) 7842, Latexmk, John Collins, 1 January 2015. Version 4.41

**Comment by tk0miya** [comment]
Fixed by #6116.
Thank you for reporting!
