### ISSUE TITLE
Proposal: Invite stephenfin as a new maintainer

### ISSUE THREAD

**Issue by tk0miya** [sphinx-doc/sphinx#6084]
# Proposal

Hello maintainers,
Today, I'd like to invite @stephenfin  as a new commiter / maintainer of our project

He had already contributed many works until now:

* Improve document
* CI and automations
* argparse integration
* bindep (new!, #5832)

I believe his experience in other OSSs would help us.
What do you think? Please 👍 for this if you agreed.

I know there are no special procedure to welcome a new commiter. So I will invite him if no objection.

**Comment by shimizukawa** [comment]
Welcome!

**Comment by tk0miya** [comment]
Hi, all. Thank you for reaction! I just send an invitation to him.
Closing.

**Comment by stephenfin** [comment]
Thanks! :smile:

**Comment by tk0miya** [comment]
Welcome to our team!

**Comment by jfbu** [comment]
@stephenfin I have a bug report :)
https://github.com/sphinx-doc/sphinx/blob/783d077dc81bebd4e0e7dba04e3a1fa6e589ffe0/AUTHORS#L82
should be replaced by your added name to co-maintainers list...

**Comment by jfbu** [comment]
and forgot to say welcome to you!
