### ISSUE TITLE
Autodoc does not document class constructors for Cython signatures

### ISSUE THREAD

**Issue by david-cortes** [sphinx-doc/sphinx#6087]
If I define some Cython classes with embedded signatures and put docstrings either on the `__init__` method or right below the class definition, these would show up just fine when I try `help(<class_name>)` in Python, but would not show up in the documentation generated by Sphynx with autodoc.

E.g.
```python
cimport cython
@cython.embedsignature(True)
cdef class classy:
    def __init__(self):
        """docstring goes here"""
```

Here’s an example (see line 459):
https://github.com/david-cortes/stochQN/blob/master/stochqn/pywrapper.pyx

Whose documentation is configured like this:
https://github.com/david-cortes/stochQN/blob/master/docs/source/index.rst
```
.. automodule:: stochqn._optimizers
        :members:
        :undoc-members:
        :inherited-members:
```

And the generated docs are here (does not document the class constructors if I generate PDF files locally either):
https://stochqn.readthedocs.io/en/latest/
(Build #8596847)

**Comment by tk0miya** [comment]
Sorry, I'm not good at cython. Could you let me know how to build your project (or minimal project) please? This would be a first case of cython to me.

**Comment by david-cortes** [comment]
> Sorry, I'm not good at cython. Could you let me know how to build your project (or minimal project) please? This would be a first case of cython to me.

Packages with Cython are built the same way as regular ones, e.g. `python setup.py build_ext --inplace`, `python setup.py install`. For Sphinx it’s also the same - `sphinx-quickstart`, edit the `.rst` file, then `make`.
Only difference is in the `setup.py` file, which usually needs to include either `cythonize` or `Cython.Distutils.build_ext`. In addition, for Cython signatures, they need to either be put as class decorators or an option added to the `setup.py` file.
For a minimal example, that same snippet above would be accompanied by a `setup.py` like this:
```python
from setuptools import setup
from distutils.extension import Extension
from Cython.Distutils import build_ext
setup(
    name  = "pkg_name",
    packages = ["pkg_name"],
    cmdclass = {'build_ext': build_ext},
    ext_modules = [Extension("module_name", sources = ["cython_file.pyx"], cython_directives = {"embedsignature": True} )],
    )
```
You can build it with `python setup.py build_ext --inplace`, then the docstring would show like this:
```python
import module_name
help(module_name.classy)
```

Or, if you clone the repo above or install it from `pip`, something like this:
```python
from stochqn import oLBFGS_free
help(oLBFGS_free)
```
(It shows the docstring in Python, but not on the documentation - docs are already build in readthedocs.org for that same package)

**Comment by tk0miya** [comment]
@david-cortes could you give me an minimal reproducible example?
I tried to install stochqn, but failed to build it.
Unfortunately, I don't have a time to investigate how to install it. So it would be very helpful if you make a minimal cython project.

Thanks,

**Comment by david-cortes** [comment]
> @david-cortes could you give me an minimal reproducible example?
> I tried to install stochqn, but failed to build it.
> Unfortunately, I don't have a time to investigate how to install it. So it would be very helpful if you make a minimal cython project.
> 
> Thanks,

[cythonsign.zip](https://github.com/sphinx-doc/sphinx/files/2911678/cythonsign.zip)
Attached is a minimal example (build with `python setup.py build_ext --inplace` at the top level, then run the code in the file `test.py` from the same folder where it was generated). Please see the PDF generated in `/docs/_build/latex/cymodule.pdf`and compare it with the docs in `help(cymodule.Classy)` (or `?cymodule.Classy` in an IDE like jupyter or spyder).

Note that it requires `cython`, which can be installed with pip (e.g. `pip install cython`)

**Comment by tk0miya** [comment]
Thank you for example! Very helpful for me.

In my investigation, the `Classy` class has two docstrings: `Classy.__doc__` and `Classy.__init__.__doc__`.
```
root@99f017149c11:/docs# python3
Python 3.5.2 (default, Nov 12 2018, 13:43:14)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cymodule
>>> cymodule.Classy.__doc__
'Classy(a=1)'
>>> cymodule.Classy.__init__.__doc__
'\n\t\tdocstring goes here\n\n\t\tParameters\n\t\t----------\n\t\ta : int\n\t\t\tNumber to store inside this object\n\t\t'
>>>
```

By default, autodoc uses the docstring of the class to the document prior to `__init__()` method's.
To refer `__init__()`'s one, please set `autoclass_content`. On my local, `autoclass_content = 'both'` displays the docstring of `__init__()`'s.
https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autoclass_content

Thanks,

**Comment by david-cortes** [comment]
Thanks, seems then it's Cython generating an extra docstring where it shouldn't be.

**Comment by david-cortes** [comment]
Another thing though: in the attached example, if I move the docstring to below the class definition instead of below the `__init__` method, it will end up showing in the PDF, but in the repo above, if I move them to below the class definition, they show in `class.__doc__` when imported, but still won't show in the PDF.

**Comment by david-cortes** [comment]
Attached is a modified example of the repo. If I try the following:
```python
import stochqn
stochqn.adaQN_free.__doc__
```
It will show the full docstring, but the generated autodoc doesn't show it (PDF is in `docs/build/latex/stochqn.pdf`)
[sqn_docs.zip](https://github.com/sphinx-doc/sphinx/files/2922201/sqn_docs.zip)

**Comment by tk0miya** [comment]
As I commented above, I failed to build your extension
```
Traceback (most recent call last):
  File "setup.py", line 45, in <module>
    include_dirs = [np.get_include(), "include"], define_macros = [("_FOR_PYTON", None)] )]
  File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.5/dist-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/usr/lib/python3.5/distutils/command/build_ext.py", line 338, in run
    self.build_extensions()
  File "setup.py", line 24, in build_extensions
    build_ext_with_blas.build_extensions(self)
  File "/usr/local/lib/python3.5/dist-packages/findblas/distutils.py", line 29, in build_extensions
    print("Installation: Using BLAS library found in:\n" + os.path.join(blas_path, blas_file) + "\n\n")
```

Please let me know how to build your library from scratch if you still need somebody's help.

**Comment by david-cortes** [comment]
Sorry again - seems there's a problem with one of the dependencies. I'm attaching a simplified version that should not have that other package as dependency. Building is as follows:
* Run `python setup.py build_ext --inplace` in the first folder level where the `setup.py` is.
* Run python from that same folder.
--- or ----
* Run `python setup.py install` (then it doesn't need to be run from the same folder).

Requires cython, numpy, scipy, scikit-learn (`pip install cython numpy scipy scikit-learn`).

Inside it is also a small test file (`test.py`) that shows two classes, with one having the docstring under `class.__doc__` and another under `class.__init__.__doc__`. Neither of them show the docstring on the docs on `/docs/build/latex/stochqn.pdf` (made with `make latexpdf` inside the `/docs` folder).
[sqn_docs2.zip](https://github.com/sphinx-doc/sphinx/files/2937913/sqn_docs2.zip)

**Comment by tk0miya** [comment]
On my local, it seems working fine.
```
FROM tk0miya/sphinx-html

RUN pip3 install cython
RUN curl -LO https://github.com/sphinx-doc/sphinx/files/2937913/sqn_docs2.zip
RUN unzip sqn_docs2.zip
RUN pip3 install cython numpy scipy scikit-learn mock sphinx_rtd_theme pandas
RUN python3 setup.py install
RUN make html -C docs
```

It seems your `conf.py` adds the parent directory to `sys.path`. But it is "docs/" directory, not package root. I guess you're using installed stochqn package, not on local.
```
import os
import sys
sys.path.insert(0, os.path.abspath('../'))
```

**Comment by david-cortes** [comment]
Oh, ok, got it, working fine now, thanks!

**Comment by david-cortes** [comment]
@tk0miya : One more question: I’m now trying to modify Cython so as not to produce a docstring for `class.__doc__` when there’s a docstring under `__init__`, and managed to make it behave like that, i.e.
* `class.__doc__ == None`
* `class.__init__.__doc__ == "docstring"`

But now the class constructor is not documented at all (neither the arguments nor the docstring appear in the documentation).

What else is required for the class constructor to show with autodoc?

-------------
For the long answer, I simply took file `Cython/Compiler/AutoDocTransforms.py`, modified lines 160-165 from:
```python
if signature:
	if is_constructor:
		doc_holder = self.class_node.entry.type.scope
	else:
		doc_holder = node.entry
```

to:
```python
if signature:
	if not is_constructor or not self.class_node.entry.type.scope.doc:
		doc_holder = node.entry
	else:
		doc_holder = self.class_node.entry.type.scope
```
then built again the simple module that I attached here (`cythonsign.zip`), rebuilding the docs for it. I'm now wondering what other requirement there is.

**Comment by tk0miya** [comment]
Sorry, I'd overlooked your comment. Could you move to sphinx-users forum? Here is an issue list of Sphinx. And I usually skip mails if issue is already closed.

Note: Have you change `autoclass_content` settings? Sphinx does not refer the docstring of `__init__()` method by default. I guess your problem is not related with cython.
