### ISSUE TITLE
Anchor links are not added to Figures

### ISSUE THREAD

**Issue by franckl** [sphinx-doc/sphinx#6096]
@tk0miya , as per my message on the google group, I am adding a bug report on github.

Sphinx is not adding an anchor to Figures automatically. I am using Python 3.7.1 and sphinx-build 1.8.4

This is a table (with anchor) :
![image](https://user-images.githubusercontent.com/3875803/53288763-cd404080-378c-11e9-9780-ed65f3f6c696.png)

This is a figure (no anchor) :
![image](https://user-images.githubusercontent.com/3875803/53288765-d16c5e00-378c-11e9-8cba-28d79190be86.png)

**Comment by tk0miya** [comment]
Fixed by #6098.
Thank you for reporting.
