### ISSUE TITLE
offer an update option to sphinx-quickstart

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#61]
Hello,
in every new version, nice new parameters and extensions are added to sphinx.

It would be nice to just re-run sphinx-quickstart on a ready prepared conf.py file and update it with the new configuration options.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/61
- Originally reported by: [timmie](https://bitbucket.org/timmie)
- Originally created at: 2008-12-01T12:08:15.766

**Comment by shimizukawa** [comment]
_From Anonymous on 2009-01-01 08:21:02+00:00_

**Bump!**

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2010-07-02 09:54:37+00:00_

Issue #455 was marked as a duplicate of this issue.

**Comment by shimizukawa** [comment]
_From anatoly techtonik on 2010-07-02 10:07:08+00:00_

Wow. I couldn't even imagine there could be the same issue one year old age. I hope #455 will be revisited when time come as it proposes to add the same capability to build scripts.

**Comment by asr** [comment]
> It would be nice to just re-run sphinx-quickstart on a ready prepared conf.py file and update it with the new configuration options.

:+1:

**Comment by AA-Turner** [comment]
This is hard to do right for `conf.py`, but could be considered when designing a new `sphinx` command (#5618).

A
