### ISSUE TITLE
Could not link to Python's standard library

### ISSUE THREAD

**Issue by felixdivo** [sphinx-doc/sphinx#6100]
**Describe the bug**
Sphinx could not find `collections.namedtuple`.

**To Reproduce**

```
$ git clone https://github.com/hardbyte/python-can
$ cd python-can
$ pip install .
$ pip install -r doc/doc-requirements.txt
$ python3 -m sphinx doc/ doc/_build -na
$ # search the log for collections.namedtuple
```

**Expected behavior + Fix**
No warning is written and the classes/methods etc. are correctly linked.

[According to the documentation](https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html), this should work:

```python
intersphinx_mapping = {
    'python': ('https://docs.python.org/3', None),
}
```

But apparently it doesn't. But this does:

```python
intersphinx_mapping = {
    'python': ('https://python.readthedocs.io/en/latest', None),
}
```

Maybe the documentation should be adjusted?

**Your project**
https://github.com/hardbyte/python-can

**Screenshots**
-

**Environment info**
- OS: Ubuntu
- Python version: e.g. 3.6.7
- Sphinx version: e.g. 1.8.4
- Sphinx extensions:  ['sphinx.ext.autodoc',
              'sphinx.ext.doctest',
              'sphinx.ext.extlinks',
              'sphinx.ext.todo',
              'sphinx.ext.intersphinx',
              'sphinx.ext.coverage',
              'sphinx.ext.viewcode',
              'sphinx.ext.graphviz',
              'sphinxcontrib.programoutput'
              ]
- Extra tools: -

**Additional context**
-

**Comment by felixdivo** [comment]
Slightly offtopic:
We also see the warning: `WARNING: py:class reference target not found: Iterator`.  Should it work, when we  include the following in the docstring of a method: `:rtype: Iterator[dict]`?

**Comment by tk0miya** [comment]
All warnings I can see are about `NamedTuple`, not `collections.namedtuple`. Is this right?
```
/docs/python-can/can/bus.py:docstring of can.BusABC.state:: WARNING: py:class reference target not found: NamedTuple
/docs/python-can/can/interfaces/pcan/pcan.py:docstring of can.interfaces.pcan.PcanBus.state:: WARNING: py:class reference target not found: NamedTuple
/docs/python-can/can/interfaces/systec/ucanbus.py:docstring of can.interfaces.systec.ucanbus.UcanBus.state:: WARNING: py:class reference target not found: NamedTuple
/docs/python-can/can/bus.py:docstring of can.BusABC.state:: WARNING: py:class reference target not found: NamedTuple
```

If so, Sphinx expects these types are full qualified name. Please use `typing.NamedTuple` instead.


Note: I used this Dockerfile to reproduce the warnings:
```
FROM tk0miya/sphinx-html

RUN git clone https://github.com/hardbyte/python-can
WORKDIR /docs/python-can
RUN pip3 install --upgrade pip
RUN pip3 install .
RUN pip3 install -r doc/doc-requirements.txt
RUN python3 -m sphinx doc/ doc/_build -na 2>&1 | tee build.log
RUN grep -i namedtuple build.log
```

**Comment by felixdivo** [comment]
It will test and report back. Thanks for your effort so far!

**Comment by felixdivo** [comment]
Okay great, this now works!
