### ISSUE TITLE
Table cells have large margins in HTML output

### ISSUE THREAD

**Issue by tk0miya** [sphinx-doc/sphinx#6113]
**Describe the bug**
Table cells have large margins in HTML output

**To Reproduce**
Build following table:
```
.. list-table:: caption
   :header-rows: 1

   * - hello
     - world
   * - hello
     - blah

       blah
```

**Expected behavior**
All cells should have appropriate margins.

**Your project**
N/A

**Screenshots**
![2019-02-27 23 47 33](https://user-images.githubusercontent.com/748828/53498817-71f2b300-3aea-11e9-8d36-4e2102e75834.png)

**Environment info**
- OS: Mac
- Python version: 3.6.5
- Sphinx version: 2.0.0b1
- Sphinx extensions: Nothing

**Comment by hftf** [comment]
I'm skeptical about the style `li > p:last-child { margin-bottom: 0px; }` added here in https://github.com/sphinx-doc/sphinx/commit/1522baf58aa4368bbc268fa112ed35089fbc85c2#diff-f19a96d9d3ab687445d135108041a607L485, which seems to condense the spacing for all lists, not just simple/compact lists. See also http://docutils.sourceforge.net/docutils/writers/html5_polyglot/minimal.css under `/* Lists */`.

**Comment by tk0miya** [comment]
@hftf +0; Do you have any good example non-simple lists? I'd like to see it to adjust style.

Note: docutils sets `margin-top` and `margin-bottom` to 0.5em by default. So non-simple lists are displayed not too sparse.
http://docutils.sourceforge.net/docutils/writers/html5_polyglot/plain.css
