### ISSUE TITLE
Sphinx 2.0 adds <p> tags in tables

### ISSUE THREAD

**Issue by cpitclaudel** [sphinx-doc/sphinx#6117]
In Sphinx 2.0, tables are translated with an extra `<p>` tag around the contents of each cell, which adds additional spacing inside table cells.

**To Reproduce**
```
   +-----+-------+----------------------------------------------------------------+
   | Bit | Value | Optimization (default is on unless noted otherwise)            |
   +-----+-------+----------------------------------------------------------------+
   |   0 |    1  | Remove local dummy variables                                   |
   +-----+-------+----------------------------------------------------------------+
   |   1 |    2  | Use special treatment for fixpoints                            |
   +-----+-------+----------------------------------------------------------------+
   |   2 |    4  | Simplify case with iota-redux                                  |
   +-----+-------+----------------------------------------------------------------+
   |   3 |    8  | Factor case branches as functions                              |
   +-----+-------+----------------------------------------------------------------+
```

**Expected behavior**

Sphinx 1.8.4 produced this:

![old](https://user-images.githubusercontent.com/8181630/53532007-2973cf00-3ac3-11e9-9b40-a336774cb484.png)

But the beta produces this:

![pre](https://user-images.githubusercontent.com/8181630/53532019-2ed11980-3ac3-11e9-84cb-1b3177fd14a7.png)

**Environment info**
- OS: GNU/Linux "Linux Mint 18.3 Sylvia"
- Python version: 3.5.2
- Sphinx version: 1.8.4 → 2.0b

**Comment by tk0miya** [comment]
I guess this is same as #6113. And I fixed it yesterday. Could you check the HEAD of master branch?

Thanks,

**Comment by cpitclaudel** [comment]
Thanks for the quick reply.  This seems to work, in conjunction with https://github.com/rtfd/sphinx_rtd_theme/pull/635 :)
