### ISSUE TITLE
HTML table headers have larger hight when built by Sphinx 2.0.0b1

### ISSUE THREAD

**Issue by cocoatomo** [sphinx-doc/sphinx#6127]
**Describe the bug**
HTML table headers built by Sphinx 2.0.0b1 are higher than ones built by Sphinx 1.8.4.

**To Reproduce**
```
$ git clone https://github.com/python/docsbuild-scripts.git
$ cd docsbuild-scripts

## build with Sphinx 1.8.4
$ mkdir -p www_184 logs_184 build_root_184
$ python3 -m venv build_root_184/venv/
$ cp requirements.txt requirements.184.txt
$ emacs requirements.184.txt
...
sphinx==1.8.4
...
$ build_root_184/venv/bin/python -m pip install -r requirements.184.txt
$ python3 ./build_docs.py --quick --branch 3.7 --build-root build_root_184 --www-root www_184 --log-directory log_184 --languages ja
$ open www_184/ja/3.7/library/functions.html

## build with Sphinx 2.0.0b1
$ mkdir -p www_200b1 logs_200b1 build_root_200b1
$ python3 -m venv build_root_200b1/venv/
$ cp requirements.txt requirements.200b1.txt
$ emacs requirements.200b1.txt
...
sphinx==2.0.0b1
...
$ build_root_200b1/venv/bin/python -m pip install -r requirements.200b1.txt
$ python3 ./build_docs.py --quick --branch 3.7 --build-root build_root_200b1 --www-root www_200b1 --log-directory log_200b1 --languages ja
$ open www_200b1/ja/3.7/library/functions.html
```

**Expected behavior**
HTML table headers built by Sphinx 2.0.0b1 have the same hight as ones built by Sphinx 1.8.4.

**Your project**
https://github.com/python/cpython/

**Screenshots**
Sphinx 1.8.4
<img width="1097" alt="screen shot 2019-02-22 at 23 33 01" src="https://user-images.githubusercontent.com/223050/53685881-db312b00-3d63-11e9-9da9-0b6d1bc29b76.png">

Sphinx 2.0.0b1
<img width="1067" alt="screen shot 2019-02-22 at 23 33 16" src="https://user-images.githubusercontent.com/223050/53685891-fe5bda80-3d63-11e9-97b1-ac0a6a2e80a0.png">

**Environment info**
- OS: macOS 10.14.3
- Python version: 3.7.1
- Sphinx version: 2.0.0b1
- Sphinx extensions:  N/A
- Extra tools: N/A

**Additional context**

- [e.g. URL or Ticket]

**Comment by tk0miya** [comment]
Thank you for reporting. But it seems same as #6113 and already fixed. Closing.
