### ISSUE TITLE
Replace mock with unittest.mock?

### ISSUE THREAD

**Issue by hroncok** [sphinx-doc/sphinx#6140]
Hey, I've noticed that the test suite uses 3rd party `mock` module.

E.g. here.

https://github.com/sphinx-doc/sphinx/blob/ba86f4ea7895ff59368a602d43bb85fc4d453546/tests/test_roles.py#L12

Now when Python 2.7 is not supported, would you accept a PR that switches over to `unittest.mock` from the Python standard library?

See also (very old) https://github.com/sphinx-doc/sphinx/issues/1410

**Comment by tk0miya** [comment]
Thank you for letting us know. It's good timing to replacing!

**Comment by tk0miya** [comment]
Fixed by #6143.
