### ISSUE TITLE
breathe: Exception: TypeError: parse_declaration() missing 1 required positional argument: 'directiveType'

### ISSUE THREAD

**Issue by meeludwig** [sphinx-doc/sphinx#6146]
**Describe the bug**
breathe: TypeError: parse_declaration missing 1 required positional argument directiveType
running doxygen, breathe and sphinx with the breathe Nutshell project.  I know this is rather breathe, and not sphinx, and I am contacting the breathe project as well. 

**To Reproduce**

sphinx-build source/ sphinx-result/

Running Sphinx v2.0.0b1
/usr/local/lib/python3.6/dist-packages/Sphinx-2.0.0b1-py3.6.egg/sphinx/util/docutils.py:312: RemovedInSphinx30Warning: function based directive support is now deprecated. Use class based directive instead.
  RemovedInSphinx30Warning)
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 1 source files that are out of date
updating environment: [] 0 added, 1 changed, 0 removed
reading sources... [100%] nutshell                                                              
Exception occurred:
  File "/usr/local/lib/python3.6/dist-packages/breathe-4.11.1-py3.6.egg/breathe/renderer/sphinxrenderer.py", line 38, in parse_definition
    ast = parser.parse_declaration("class")
TypeError: parse_declaration() missing 1 required positional argument: 'directiveType'
The full traceback has been saved in /tmp/sphinx-err-w9f5bnbl.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!

See log
[sphinx-err-w9f5bnbl.log](https://github.com/sphinx-doc/sphinx/files/2942160/sphinx-err-w9f5bnbl.log)

**Expected behavior**
adding another directive like i.e. :dummy: avoids the exception and only gets a warning, but no class reference is generated in the html either. 

**Your project**
https://breathe.readthedocs.io/en/latest/index.html 
Nutshell project

**Environment info**
- OS: ubuntu18.04 LTS, updated to 7.march.2019, python 3.6.7, doxygen 1.8.13, breathe cloned from  https://github.com/michaeljones/breathe 
- Python version: 3.6.7
- Sphinx version: v2.0.0b1
- Sphinx extensions:  breathe cloned from https://breathe.readthedocs.io/en/latest/index.html 

**Additional context**
- C++ documentation

**Comment by jakobandersen** [comment]
Thanks for reporting, though I'm quite sure it's a Breathe problem. I believe this is due to a change in internal APIs in Sphinx 2.0 where Breathe needs changes as well. PR michaeljones/breathe#411 should fix the problem.

**Comment by meeludwig** [comment]
yep, I am just writing to him. If that can be made working it should be great stuff !

**Comment by jakobandersen** [comment]
@meeludwig, if you downgrade to the stable release of Sphinx, 1.8.4, for another few weeks, that particular bug shouldn't trigger.
