### ISSUE TITLE
`sphinx.ext.autodoc` should respect `docutils` `tab_width` configuration

### ISSUE THREAD

**Issue by doerwalter** [sphinx-doc/sphinx#6165]
Currently the `sphinx.ext.autodoc` directives (e.g. `.. automodule::`) expand tabs to 8 spaces irrespective of the `tab_width` configuration of `docutils`.

This could be fixed by changing the `expandtabs()` call in `sphinx.util.docstrings.prepare_docstring` to pass the correct `tab_width` value.

(See #642 for more context).

**Comment by tk0miya** [comment]
Fixed by #6201.
Thank you for reporting!
