### ISSUE TITLE
Corrupted output in builded html

### ISSUE THREAD

**Issue by Viktor-Demin** [sphinx-doc/sphinx#6169]
**Describe the bug**
I want to build docs using sphinx and ipython directive.
I try on simple command:

```
.. ipython:: python

    import datatable as dt
    DT = dt.Frame(A=range(5))
    DT
```

In jupyter notebook results look well:
![image](https://user-images.githubusercontent.com/19714042/54150278-1e1c8e00-4449-11e9-9a1d-ca3a99faeafd.png)

but  html corrupted:

![image](https://user-images.githubusercontent.com/19714042/54150315-2e346d80-4449-11e9-86f0-e4f74cc78c73.png)

**To Reproduce**
```

$ git clone https://github.com/Cheburusska/datatable.git
$ cd sdatatable
$ pip install datatable
$ pip install jupyter notebooks
$ cd docs
$ make html 
when it freezes during building of test directive ipython.rst do ctrl+C
$ # open test directive ipython.html
```

**Expected behavior**

![image](https://user-images.githubusercontent.com/19714042/54150278-1e1c8e00-4449-11e9-9a1d-ca3a99faeafd.png)

**Your project**
https://github.com/Cheburusska/datatable/tree/master/docs

**Environment info**
- Mac 10.13.6
- Python version: 3.7.2
- Sphinx version: 1.8.4
- Sphinx extensions:  [    'nbsphinx',
    'sphinx.ext.autodoc',
    'sphinx.ext.mathjax',
    'sphinx.ext.napoleon',
    'IPython.sphinxext.ipython_directive',
    'IPython.sphinxext.ipython_console_highlighting']

What could be the reason?

**Comment by tk0miya** [comment]
The `ipython` directive is not a part of Sphinx-core. So we can't answer about it. So please ask this to their project.
