### ISSUE TITLE
BUG: Tables now centered by default is a backward incompatible change

### ISSUE THREAD

**Issue by larsoner** [sphinx-doc/sphinx#6170]
2502794 / #4550 has changed all table rendering for us when using latest Sphinx. Long tables [rendered with 1.8](http://mne-tools.github.io/dev/python_reference.html):

![Screenshot from 2019-03-11 16-57-50](https://user-images.githubusercontent.com/2365790/54157529-dd0f8400-441e-11e9-87a7-a4c5e941e523.png)

... are now centered when built on latest Sphinx master:

![Screenshot from 2019-03-11 16-57-44](https://user-images.githubusercontent.com/2365790/54157537-df71de00-441e-11e9-9764-7d711500d944.png)

2502794 thus seems like a backward-incompatible -- and potentially widely disruptive -- change.

It be might be best to have this configurable via a top-level conf.py option with *opt-in* behavior, rather than changing all Sphinx-rendered tables. But if it's added as a top-level option with *opt-out* behavior (here meaning: I'll have to set a value in conf.py in all docs I manage to get the old behavior back) that's at least a workable solution, too. But without at least some sort of global option, having to mark all tables in all docs I manage to `:align: left` to get the old behavior back would be challenging to say the least.

**Comment by tk0miya** [comment]
It seems your page does not contain `<div>` tag having `body` class. Are you using custom HTML theme, right? If true, please update your theme. Our basic theme expects to wrap the whole of document with `<div class="body">`. 

With the div tag, this stylesheet will keep text-align of table cells.
https://github.com/sphinx-doc/sphinx/blob/fadab68ffc6a79de2d285eca930e58cddece4c45/sphinx/themes/basic/static/basic.css_t#L261-L263

**Comment by larsoner** [comment]
> Are you using custom HTML theme, right? If true, please update your theme.

We use `sphinx-bootstrap-theme`, so I guess it could be addressed there, assuming that we don't errantly override some HTML template. In the meantime we can add it to our custom CSS to work around it.

> With the div tag, this stylesheet will keep text-align of table cells.

Ahh, so #4550 was only meant to make the *table* justified to the left, not the *table cells* individually?

That's still a backward incompatible change, but much less invasive at least. It might be worth adding to the release notes (where it's noted that behavior was changed) how it can be reverted in CSS, if it can be.

**Comment by tk0miya** [comment]
>Ahh, so #4550 was only meant to make the table justified to the left, not the table cells individually?

Yes, target of #4550 is only table. I'd not like to change the align of cells. 

>That's still a backward incompatible change, but much less invasive at least. It might be worth adding to the release notes (where it's noted that behavior was changed) how it can be reverted in CSS, if it can be.

Unfortunately, no way to revert it. There are no difference between tables having no `:align:` option and one having `:align: center` option.

**Comment by larsoner** [comment]
PR to sphinx-bootstrap-theme opened, thanks for the clarifications

https://github.com/ryan-roemer/sphinx-bootstrap-theme/pull/193
