### ISSUE TITLE
exception: No module named 'sphinx.ext.pngmath'

### ISSUE THREAD

**Issue by heksbeks** [sphinx-doc/sphinx#6182]
Running Sphinx v2.1.0+ (also 1.8.x)

Extension error:
Could not import extension sphinx.ext.pngmath (exception: No module named 'sphinx.ext.pngmath')

**Comment by tk0miya** [comment]
pngmath module was removed since 1.8. The successor is `sphinx.ext.imgmath`. Thanks,
