### ISSUE TITLE
Allow customization of Python prompt ">>>"

### ISSUE THREAD

**Issue by jhpalmieri** [sphinx-doc/sphinx#6188]
**Is your feature request related to a problem? Please describe.**
The SageMath project (http://www.sagemath.org/) has been happily using Sphinx for some time. Right now we patch Sphinx, and I was wondering about the possibility of incorporating the patch into Sphinx itself. In particular, SageMath is based on Python, but rather than using ">>>" as a prompt in doctests, it uses "sage: ". This means that without patching Sphinx, doctests in Sage's reference manual are not properly highlighted, and `<BLANKLINE>` is not rendered properly.

**Describe the solution you'd like**
I would like a configuration option (unless there's a better way to do it) to allow the Python prompt to be changed.

**Describe alternatives you've considered**
As noted, Sage currently patches Sphinx. We could try Sphinx extensions instead, but that essentially means forking Sphinx (creating our own versions of `highlighting.py` and `transforms/post_transforms/code.py`), and so it requires more maintenance.

**Additional context**
I posted a draft of possible changes to https://groups.google.com/d/msg/sphinx-dev/wOcC3oIdixQ/fHvICpzjBwAJ, but others more familiar with Sphinx may know better ways to accomplish this. The proposed changes add a configuration option, and then also modify `highlighting.py` and `transforms/post_transforms/code.py`.

**Comment by tk0miya** [comment]
Does `highlight_language` option help your project? I wonder this option is really necessary for other users.
I think a transform module like following also helps you:
```
class SagemathTransform(Transform):
    default_priority = 500

    def apply(self):
        for node in self.document.traverse(nodes.literal_block):
            if node.get('language') is None and node.astext().startswith('sage:'):
                node['language'] = 'pycon'


def setup(app):
    app.add_transform(SagemathTransform)
```

**Comment by jhpalmieri** [comment]
Both `highlight_language` and the proposed transform module more or less work for me, so I think we can close this issue. (I say "more or less" because Sage code blocks are not identical to Python code blocks, so highlighting fails for some existing code blocks. If the language is "default", this is done gracefully, but if the language is "pycon", then it prints warnings. So we will probably end up suppressing those warnings.)

**Comment by jhpalmieri** [comment]
I don't know the etiquette for Sphinx development, so I don't know if it's appropriate for me to close this. I will wait a few days and if no one else takes action, I will close it.

**Comment by tk0miya** [comment]
Okay, let's close this. Thanks,
