### ISSUE TITLE
Proposal: Introducing a new branch model

### ISSUE THREAD

**Issue by tk0miya** [sphinx-doc/sphinx#6191]
**Is your feature request related to a problem? Please describe.**
Since 2.0, we'd migrated to new versioning model; semantic versioning (https://semver.org/). According to the model, additional new branch is needed for us.

- a branch for bugfix release (ex. v2.0.1)
- a branch for minor release (ex. v2.1.0)
- a branch for major release (ex. v3.0.0)

At present, we have two branches; `2.0` for bugfix, and `master` for minor release. Therefore, we don't have a branch for major release at present.

**Describe the solution you'd like**
Introducing new branch model.

- `X.Y` (ex. `2.0`) for bugfix release
- `stable` for minor release
- `master` for major release.

**Comment by shimizukawa** [comment]
For confirmation, I'm reading current branch model:
http://www.sphinx-doc.org/en/master/devguide.html#branch-model
that introduced at https://github.com/sphinx-doc/sphinx/pull/5938

It says that our current branch model is:

* master: for MAJOR version
* X.Y: for maintain current MINOR release
* X.Y.Z for MAJOR.MINOR.PATCH release

So, I think it would be nice to proceed with the documentation as soon as version 2.0 is released.

**Comment by tk0miya** [comment]
oh, my bad. I'd confused.
Thanks,
