### ISSUE TITLE
Custom searchresults.html has no effect

### ISSUE THREAD

**Issue by tbekolay** [sphinx-doc/sphinx#6193]
**Describe the bug**
I am developing a custom theme based on the `basic` theme. I was hoping that I could extend the `searchresults.html` to customize the display or results without redoing `search.html`, but that file does not seem to be used anywhere.

**To Reproduce**

- Add `searchresults.html` to the theme, rebuild and perform a search

**Expected behavior**
The new `searchresults.html` would be used in the search results page.

It seems like this would be possible by doing `{% include "searchresults.html" %}` at https://github.com/sphinx-doc/sphinx/blob/master/sphinx/themes/basic/search.html#L4, but perhaps there's a reason why that's not being done?

**Your project**
https://github.com/nengo/nengo-sphinx-theme

**Environment info**
- OS: Debian sid
- Python version: 3.7.2
- Sphinx version: 1.8.4
- Sphinx extensions:  nengo-sphinx-theme
- Extra tools: N/A

**Comment by tk0miya** [comment]
It seems `searchresults.html` was added only for websupport feature (8c4e535170). So I think this is not a bug.
I think your request has not been implemented ever.

**Comment by tk0miya** [comment]
Note: We should move the file to `sphinxcontrib-websupport` package.

**Comment by tbekolay** [comment]
Moving it to `sphinxcontrib-websupport` would be great, thank you. Feel free to remove the bug label (I can't remove it myself).

**Comment by tk0miya** [comment]
Now I moved it into sphinxcontrib-websupport package.
Thanks,

**Comment by tbekolay** [comment]
Thanks @tk0miya!
