### ISSUE TITLE
Search Box Enhancement Proposal

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#620]
==== Search Box Enhancement Proposal ====

It would be nice if during the typing it suggests some query-keywords, e.g like Google.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/620
- Originally reported by: Michele Lacchia
- Originally created at: 2011-01-25T19:46:39.189

**Comment by jdillard** [comment]
It seems like this issue can be closed due to inactivity.

**Comment by shimizukawa** [comment]
Thanks for the suggestion. I'll close it.

IMO, to improve the experience of the search functionality in Sphinx itself, we will need to revisit the JS in its entirety.
