### ISSUE TITLE
WARNING: image file not readable on animated SVGs

### ISSUE THREAD

**Issue by gpotter2** [sphinx-doc/sphinx#6200]
Hi !

**Describe the bug**
Animated SVGs render correctly in the browser + sphinx generated doc, but Sphinx will still put a warning when building, saying that it won't work.

**To Reproduce**
Here's an SVG animation: https://scapy.readthedocs.io/en/latest/_images/animation-cansend.svg (it was generated using [termtosvg](https://github.com/nbedos/termtosvg))
The image is linked in the doc via
```rest
.. image:: graphics/animations/animation-cansend.svg
```
Let's build it
```
make html
```
> [Lots of normal good stuff]
> ... WARNING: image file not readable: layers\graphics/animations/animation-scapy-python-can-cansocket.svg

However, it will render properly: https://scapy.readthedocs.io/en/latest/advanced_usage.html#setup
(except if you're using Microsoft Edge, but who cares)

**Environment info**
- OS: WSL (same on other platforms)
- Python version: 3.7.2
- Sphinx version: 1.8.5
- Sphinx extensions:  shpinx_rtd_theme

![Wow look at my fancy animation 😄](https://scapy.readthedocs.io/en/latest/_images/animation-cansend.svg)

**Comment by tk0miya** [comment]
Could you check permission to the file on local?
It seems the warning is not emitted on readthedocs: https://readthedocs.org/projects/scapy/builds/8802516/. So this would be related with your local machine.

**Comment by gpotter2** [comment]
Thanks for the tip.
Boo to myself for having missed that 😄
