### ISSUE TITLE
Hyperlinks to Glossary Entries

### ISSUE THREAD

**Issue by markperfectsensedigital** [sphinx-doc/sphinx#6202]
**Is your feature request related to a problem? Please describe.**
Sphinx generates links to headings, similar to the following:

`<a class="headerlink" href="#step-1-define-the-content-types" title="Permalink to this headline">¶</a>`

When I mouse over a heading, I can right-click and copy the link.

This feature is not available for glossary entries.

**Describe the solution you'd like**
Generate similar links to glossary entries. Sphinx already generates links to glossary entries such as http://docs.brightspot.com/cms/glossary/index.html#term-action-bar, but there is no possibility to right-click and copy the link.

**Describe alternatives you've considered**
None so far, but I will be writing a javascript as a workaround.

**Additional context**

**Comment by tk0miya** [comment]
+1; Reasonable.

**Comment by vsajip** [comment]
Isn't this the same as #996?

**Comment by markperfectsensedigital** [comment]
It is exactly the same as [#996](https://github.com/sphinx-doc/sphinx/issues/996). Because that ticket is written so much better than mine, I'll close this ticket.
