### ISSUE TITLE
Sphinx 1.8 docs have disappeared

### ISSUE THREAD

**Issue by stephenfin** [sphinx-doc/sphinx#6222]
Just a quick FYI - the 1.8 docs, which should be available at https://www.sphinx-doc.org/en/1.8/, no longer appear. I could have sworn these were here before. I'd try to fix this myself but I don't know where to start :disappointed:

**Comment by tk0miya** [comment]
Sorry for inconvenience. Thank you for letting me know. I just rebuild the document manually on readthedocs. I guess it might be broken on replacing the branch by git tag.

**Comment by stephenfin** [comment]
Thanks!
