### ISSUE TITLE
An exception occured when trying append “pending_xref” node to signode

### ISSUE THREAD

**Issue by madTeddy** [sphinx-doc/sphinx#6227]
**Describe the bug**
I'm trying append **pending_xref** node to _signode_ of **handle_signature** function, but getting exception in docutils script:
```
Exception occurred: File "\python\python37-32\lib\site-packages\docutils\nodes.py", line 569, in __getitem__
return self.children[key] IndexError: list index out of range
```

**To Reproduce**
My code:
```python
def handle_signature(self, sig, signode):
   if 'mod' in self.options:
      signode += nodes.Text(self.options['mod'] + ' ')
   signode += nodes.Text('Some text ')
   names, _, _ = Obj.parse_signature(sig)
   if names:
      ns = names.strip().split('.')
      for cl in ns:
         # because off this, i'm get an error
         signode += addnodes.pending_xref('', refdomain='mydomain',
         reftype='ahg', reftarget=cl, modname=None, classname=None)
   return sig
```
Everything is working without **+= addnode.pending_xref()** (other nodes appends successfully, except this).

> In nodes.py when exception occures, index equals to 0 (but it's nothing tells me).

You can reproduce this with my script on [pastebin](https://pastebin.com/Yxb0U8CZ). For test just use the directive `.. sphinxtest:recipe:: TestRecipe`. In my case after `make html`, i'm getting the error above.

**Environment info**
- OS: Windows 10 x64
- Python version: 3.7.3
- Sphinx version: 2.0.0

**Comment by tk0miya** [comment]
Sphinx expects a pending_xref node has one TextElement node as a child for its title. Please append it on your script.
Thanks,

**Comment by madTeddy** [comment]
@tk0miya, **thank you** for help. Two days i couldn't solve this problem...
