### ISSUE TITLE
Napoleon's Attributes directive ignores :noindex: option.

### ISSUE THREAD

**Issue by asbuch** [sphinx-doc/sphinx#6240]
**Description of the bug**
Sphinxcontrib-napoleon's `Attributes:` directive appears to ignore the `:noindex:` option. 

The following reST code produces an index that includes the `Attributes:` directives found in `example_google.py` but leaves out all other directives:

```reST
Google Example
==============

.. automodule:: example_google
   :members:
   :noindex:

:ref:`genindex`
```

**Expected behavior**
The above example should produce an empty document index.

**Environment info**
I am using the Sphinx packages that are provided by Ubuntu 18.04 and installed Napoleon with pip3 afterwards:

```
apt install make python3-sphinx python3-pip
pip3 install sphinxcontrib-napoleon
```

The file `example_google.py` is from https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html

I used `sphinx-quickstart` to configure my directory, edited `conf.py` to include `sphinxcontrib-napoleon` and set the Python path, then typed `make html`.

**Comment by avacariu** [comment]
I'm hitting this bug as well, but I believe this bug is in `autodoc` not `napoleon`, since all `napoleon` does is convert Google/Numpy style docstrings to valid reST. As far as I can tell from the code, it doesn't set `:noindex:` for any other option so I don't see how Attributes is handled any differently.

**Comment by tk0miya** [comment]
I just posted #7350 to fix this. Could you check it please?

Please note this is a bug fix for `sphinx.ext.napoleon`. `sphinxcontrib-napoleon` will not be fixed. I don't know the status of it, but it seems not maintained now.
