### ISSUE TITLE
Latex 'releasename' ignored in version 2.0.0

### ISSUE THREAD

**Issue by tbird1965** [sphinx-doc/sphinx#6243]
**Latex 'releasename' Broken in verion 2.0.0**
Setting latex element releasename no longer works, displays "Release" instead.

**To Reproduce**
Edit conf.py and set latex_elements as follows:

latex_elements = {
    'releasename': 'Test',
}

Then build latex:
```
make latex
```

View latex file and you will see:
```
\renewcommand{\releasename}{Release}
```

**Expected behavior**
Sphinx version 1.8.5 and older (at least until the 1.7.x and possibly older) even allows releasename to be a space (which I use).

I use Sphinx for custom product manuals and using the word "Release" makes no sense.  My conf.py files are setup so the PDFs will display "Version 1.0" on the title page.

In version 2.0.0, my PDFs display "Release Version 1.0"

**Environment info**
- OS: Windows 7, 64 bit, SP1
- Python version: 3.6.5
- Sphinx version: 2.0.0
- Sphinx extensions:  none, that I know of
- Extra tools: MiKTeX 2.9 for PDF build

**Temporary Workaround**
Either use Sphinx 1.8.5 or edit latex file and manually change the releasename entry.

**Comment by tk0miya** [comment]
Fixed by #6253.
Thank you for reporting.
