### ISSUE TITLE
Support sidewaysfigures

### ISSUE THREAD

**Issue by stratosgear** [sphinx-doc/sphinx#6247]
**Is your feature request related to a problem? Please describe.**
I find the need to sometimes rotate really wide images or tables in my PDF docs

**Describe the solution you'd like**
It seems a combination of `\include{rotating]` in the preamble and the ability to have access to something to a new directive like `..sidewaysfigure:: My landscape figure`, would fix this issue.  For the HTML builder something with some css rotating, should also work too.

**Describe alternatives you've considered**
I haven't found any way of currently doing this in Sphinx.

**Links**
https://tex.stackexchange.com/questions/44427/rotate-picture-with-caption

I have really searched for an option like this but haven't found any solutions.  Has this been discussed in the past?

**Comment by tk0miya** [comment]
-1: It would be better to implement it as an extension.

**Comment by stratosgear** [comment]
Would you be able to suggest an extension that is doing something similar to this, to use as a starting point?  Not that familiar with Sphinx extensions and a push in the right direction would be greatly appreciated!

**Comment by tk0miya** [comment]
Sorry, I don't know similar extension. I hope our tutorial helps you.
http://www.sphinx-doc.org/en/master/development/tutorials/index.html
