### ISSUE TITLE
.. include directive works for .. |exampleimage| image:: im.png but not for .. |examplefigure| figure:: im.png

### ISSUE THREAD

**Issue by EWouters** [sphinx-doc/sphinx#6248]
**Describe the bug**
`.. include` directive works for `.. |exampleimage| image:: im.png` but not for `.. |examplefigure| figure:: im.png`

**To Reproduce**
Check the repo I included that reproduces the problem.
```
$ https://github.com/EWouters/include_figure.git
$ make html
include_figure\source\index.rst:24: WARNING: Substitution definition "examplefigure" empty or invalid.

.. |examplefigure| figure:: sphinxheader.png
source/README.rst:3: WARNING: Undefined substitution referenced: "examplefigure".
```
Open source/_build/html/index and see:
![result](https://user-images.githubusercontent.com/6179932/55553710-71909d80-56d0-11e9-897d-1c0980d89b1c.PNG)

**Expected behavior**
Substitution of figure should result in a similar behavior as the substitution of image.

**Your project**
[https://github.com/EWouters/include_figure](https://github.com/EWouters/include_figure)

**Environment info**
- OS: Windows 10
- Python version: Python 3.6.8 :: Anaconda, Inc.
- Sphinx version: 2.0.0

**Comment by tk0miya** [comment]
This is restriction of substitution. `include` directive is not related.
substitution accepts only inline directives for argument. But `figure` directive is not an inline directive. So it does not work.
http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#substitution-definitions

**Comment by EWouters** [comment]
Ok, sorry! I tried to find in the documentation which directives were supported, but didn't find a list.

Is there a way to make this work anyway?

**Comment by tk0miya** [comment]
Sorry, I have no idea.
