### ISSUE TITLE
Create hrefs for :bcp:

### ISSUE THREAD

**Issue by ioggstream** [sphinx-doc/sphinx#6255]
## I wish

Support for :BCP: like :RFC: and :PEP:

## It could be done

reusing RFC/PEP code in [roles.py](sphinx/roles.py)

**Comment by tk0miya** [comment]
This is first time I hear about BCP. So I can't determine it is commonly used or not.
If it is commonly used and worthy, it should be added into reStructuredText standard. How about proposing this to docutils project?

IMO, adding to new directives and roles into Sphinx causes division of reST syntax more.

**Comment by ioggstream** [comment]
BCP are IETF Best Current Practices https://en.wikipedia.org/wiki/Best_current_practice
which are served from the same RFC website.

A couple of BCP are https://tools.ietf.org/html/bcp47 (language tags) and https://tools.ietf.org/html/bcp42

@tk0miya if there's an easy way to contribute it to `docutils` (eg. their github seem stale, and the sourceforge page seems very old http://docutils.sourceforge.net/ ) please let me know: I have some patches to propose them too.

**Comment by tk0miya** [comment]
They're still working on sourceforge. The page you mentioned is active :-)
To contribute them, please post a patch from here: https://sourceforge.net/p/docutils/patches/.

**Comment by tk0miya** [comment]
I'm closing this now.
Thank you for your proposal. I wish this proposal will be merged into docutils!

**Comment by ioggstream** [comment]
Ok, for future reference, see https://sourceforge.net/p/docutils/feature-requests/61/
