### ISSUE TITLE
The display of the field list has changed

### ISSUE THREAD

**Issue by usaturn** [sphinx-doc/sphinx#6262]
**Describe the bug**
This is a comparison of 1.8 and 2.0.
Please display like 1.8.

**To Reproduce**
```
Welcome to test's documentation!
================================

:spam: Spiced Ham
:ham: pork
:eggs: Chicken egg
```

```
make html
```

`html_theme = 'alabaster'` sphinx 1.8.5
![2019-04-06_15h09_25](https://user-images.githubusercontent.com/1503215/55665781-ed7d1800-587f-11e9-92ae-c29ef368a806.png)

`html_theme = 'alabaster'` sphinx 2.0
![2019-04-06_15h10_32](https://user-images.githubusercontent.com/1503215/55665776-e6eea080-587f-11e9-84f1-89f93fc20202.png)

`html_theme = 'bizstyle'` 1.8.5
![2019-04-06_15h11_32](https://user-images.githubusercontent.com/1503215/55665786-038ad880-5880-11e9-97a3-dd2329c06bb1.png)

`html_theme = 'bizstyle'` 2.0
![2019-04-06_15h11_01](https://user-images.githubusercontent.com/1503215/55665791-12718b00-5880-11e9-8ee1-48b82ff22846.png)

**Your project**
[tmp.zip](https://github.com/sphinx-doc/sphinx/files/3050222/tmp.zip)

**Environment info**
- OS: Windows10
- Python version: 3.6.4
- Sphinx extensions: none

**Comment by tk0miya** [comment]
Fixed by #6266.
Thank you for reporting!
