### ISSUE TITLE
documentation issue: What is a "local table of contents"?

### ISSUE THREAD

**Issue by Phillip-M-Feldman** [sphinx-doc/sphinx#6265]
I'm looking at the document at https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html.  It contains the following statement:

"For local tables of contents, use the standard reST contents directive."

It would be helpful if the document explained what is meant by a "local table of contents".

**Comment by tk0miya** [comment]
I suspect it means table of contents for the current document source (.rst file).

**Comment by Phillip-M-Feldman** [comment]
I'm still confused.  It would be very strange to have multiple tables of contents for a single document.

**Comment by tk0miya** [comment]
Sphinx has two types of ToC. First one is "global" ToC. It is a table of contents for all of documents. Another one is "local" ToC. It is a table of contents for single document (.rst file). In another word, local ToC is a list of hyperlinks for local page. It would be useful for large document file (ex. README).

**Comment by Phillip-M-Feldman** [comment]
Perhaps a few sentences (more or less what you've just written) can be
added to the Sphinx documentation?

Thanks!

Phillip

**Comment by tk0miya** [comment]
:-)
