### ISSUE TITLE
Make clean is catastrophically broken if building into '.'

### ISSUE THREAD

**Issue by EtchedPixels** [sphinx-doc/sphinx#6271]
**Describe the bug**

If the build directory is . the default makefile destroys the entire document tree and configuration when you make clean

**To Reproduce**
Set the build directory to .
make clean

**Expected behavior**
Not to trash the source document

**Environment info**
- Linux (Fedora)
- Python 3.6.8
- Sphinx version: 1.7.5

**Comment by tk0miya** [comment]
Fixed by #6227.
Thank you for reporting.
