### ISSUE TITLE
Usage of stix2 for rendering math as SVG breaks HTML build by a LaTeX error "too many symbol fonts"

### ISSUE THREAD

**Issue by jfbu** [sphinx-doc/sphinx#6278]
I tried this document

```rst
Hello

.. math::

   F^{\mu\nu} = \partial^\mu A^\nu - \partial^\nu A^\mu

World
```

with the following setup in conf.py

```
extensions = [
    'sphinx.ext.imgmath',
]

imgmath_image_format = 'svg'

imgmath_latex_preamble = '\\usepackage{stix2}'
```

But then `make html` fails with a report of a LaTeX error.

```
! LaTeX Error: Too many symbol fonts declared.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.89 ...nt{arrows3}       {LS2}{stix2tt}   {m} {n}
```

It appears that https://github.com/sphinx-doc/sphinx/blob/f4a98d8ca0cc88a5a993a6b90a3af0892fdc19c0/sphinx/ext/imgmath.py#L60-L71 is incompatible with using `stix2` package.

On the other hand trying `latex` on 

```
\documentclass{article}

\usepackage{stix2}

\begin{document}
$F^{\mu\nu} = \partial^\mu A^\nu - \partial^\nu A^\mu$
\end{document}
```

works. One can do latex on this file then dvisvgm (without even the option ``--no-fonts``, dvisvgm 2.6.2) and one obtains a valid svg file. (see attachment)

[temp.svg.zip](https://github.com/sphinx-doc/sphinx/files/3072174/temp.svg.zip)

**Environment info**
- OS: Mac
- Python version: 3.6.8
- Sphinx version: 2.0.0
- Sphinx extensions:  imgmath
- Extra tools: TeXLive 2019, dvisvgm 2.6.2 (MacPorts)

**Additional context**

- #5301

**Comment by tk0miya** [comment]
I don't have good idea for this. IMO, Adding new settings for stix2 is not good resolution. Because we will add another settings for each font package.
It might be better to allow for users to customize LaTeX template like #6308. It is a bit bother, but easy to customize.

**Comment by jfbu** [comment]
Thanks to #6308 user can customize a template to fix such issues, should they arise in real life. Thus closing this issue.
