### ISSUE TITLE
For math into SVG, allow PDF as intermediate format (as dvisvgm can handle it)

### ISSUE THREAD

**Issue by jfbu** [sphinx-doc/sphinx#6280]
**UPDATE on April 2, 2023**:

With my current installation (TeXLive 2023, dvisvgm 3.0.3 built with ghostscript support) the problems mentioned below with executing `dvilualatex + dvisvgm` with LaTeX file configured to use `unicode-math` and XITS or other OpenType Math font seem to have disappeared.

So it is even less urgent to support PDF as intermediate image type.

<hr>
<hr>

This is related to #5301 and #6279.

I tried using `lualatex` with `XITS` fonts. I tested with this latex file `temp.tex`

```
\documentclass{article}
\usepackage{unicode-math}\setmainfont{XITS}\setmathfont{XITS Math}
\begin{document}
$F^{\mu\nu} = \partial^\mu A^\nu - \partial^\nu A^\mu$
\end{document}
```

and executed `dvilualatex` and then `dvisvgm` (with or without `--no-fonts`). But the `dvisvgm` currently fails:

```
kpathsea:make_tex: Invalid filename `XITSMath:mode=base;script=math;language=DFLT;+ssty=0;.mf', contains ':'
WARNING: font file 'XITSMath:mode=base;script=math;language=DFLT;+ssty=0;.mf' not found
kpathsea:make_tex: Invalid filename `XITSMath:mode=base;script=math;language=DFLT;.mf', contains ':'
WARNING: font file 'XITSMath:mode=base;script=math;language=DFLT;.mf' not found
kpathsea:make_tex: Invalid filename `XITS:mode=node;script=latn;language=DFLT;+tlig;.mf', contains ':'
WARNING: font file 'XITS:mode=node;script=latn;language=DFLT;+tlig;.mf' not found
pre-processing DVI file (format version 2)
processing page 1
  graphic size: 164.198365pt x 580.858197pt (57.709125mm x 204.148308mm)
  WARNING: can't embed font 'XITS:mode=node;script=latn;language=DFLT;+tlig;'
  WARNING: can't embed font 'XITSMath:mode=base;script=math;language=DFLT;+ssty=0;'
  WARNING: can't embed font 'XITSMath:mode=base;script=math;language=DFLT;'
  output written to temp.svg
1 of 1 page converted in 0.244583 seconds
```

and produces this svg file

```
<?xml version='1.0' encoding='UTF-8'?>
<!-- This file was generated by dvisvgm 2.6.2 -->
<svg height='578.688116pt' version='1.1' viewBox='76.712329 51.947002 163.584922 578.688116' width='163.584922pt' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink'>
<style type='text/css'>
<![CDATA[
text.f0 {font-family:XITSMath:mode=base;script=math;language=DFLT;+ssty=0;;font-size:10px}
text.f1 {font-family:XITSMath:mode=base;script=math;language=DFLT;;font-size:10px}
text.f2 {font-family:XITS:mode=node;script=latn;language=DFLT;+tlig;;font-size:10px}
]]>
</style>
<g id='page1'>
<text class='f1' x='76.712329' y='62.764633'>𝐹</text>
<text class='f0' x='87.320909' y='58.780002'>𝜇<tspan x='96.709074'>𝜈</tspan>
</text>
<text class='f1' x='98.424214' y='62.764633'>=<tspan x='110.355319'>𝜕</tspan>
</text>
<text class='f0' x='119.917818' y='58.780002'>𝜇</text>
<text class='f1' x='124.65252' y='62.764633'>𝐴</text>
<text class='f0' x='133.81652' y='58.780002'>𝜈</text>
<text class='f1' x='139.815964' y='62.764633'>−<tspan x='151.193648'>𝜕</tspan>
</text>
<text class='f0' x='160.756147' y='58.780002'>𝜈</text>
<text class='f1' x='164.541908' y='62.764633'>𝐴</text>
<text class='f0' x='173.705908' y='58.780002'>𝜇</text>
<text class='f2' x='231.13325' y='630.635118'>1</text>
</g>
</svg>
```

but my browser Firefox does not understand the syntax (coming from luatex) for the fonts and it substitutes some replacement. The result is not good.

On the other hand, by running `lualatex`  to produce a PDF file, then one can execute `dvisvgm --pdf` on the PDF file and it works. The produced SVG looks as if it does have the correct glyphs (as in PDF output).

Generally speaking running `lualatex` with `\usepackage{unicode-math}` is much much slower than a regular `pdflatex`, but if this is solution to embed OpenType fonts with a MATH table into the output, it may be useful to Sphinx users to support it.

Hence my proposal to let the image converter also support the `dvisvgm --pdf` usage. However if #6279 is solved to allow `xelatex --no-pdf` usage and `dvisvgm` on the `.xdv` files, then this feature request is less important. It could remain useful because it is known that xelatex has issues in math mode of placement of glyphs, which possibly lualatex does not have.

- #5301, #6279

**Comment by tk0miya** [comment]
>Hence my proposal to let the image converter also support the dvisvgm --pdf usage.

I think you can do it with `imgmath_dvisvgm_args = ['--pdf']`. Is this right?

**Comment by jfbu** [comment]
> I think you can do it with imgmath_dvisvgm_args = ['--pdf']. Is this right?

I succeeded into using lualatex with intermediate pdf format after applying this patch

```diff
diff --git a/sphinx/ext/imgmath.py b/sphinx/ext/imgmath.py
index eb0d35c25..0376370d4 100644
--- a/sphinx/ext/imgmath.py
+++ b/sphinx/ext/imgmath.py
@@ -134,7 +134,12 @@ def compile_math(latex, builder):
 
     try:
         subprocess.run(command, stdout=PIPE, stderr=PIPE, cwd=tempdir, check=True)
-        return path.join(tempdir, 'math.dvi')
+        if builder.config.imgmath_latex in {'xelatex', 'lualatex', 'pdflatex'}:
+            return path.join(tempdir, 'math.pdf')  # needs --pdf option for dvisvgm
+        elif builder.config.imgmath_latex == 'xelatex --no-pdf':  ## NO! option must be separate
+            return path.join(tempdir, 'math.xdv')
+        else:
+            return path.join(tempdir, 'math.dvi')
     except OSError:
         logger.warning(__('LaTeX command %r cannot be run (needed for math '
                           'display), check the imgmath_latex setting'),
```

(but the patch is broken for ``xelatex --no-pdf`` case)
and using the following conf.py

```
extensions = [
    'sphinx.ext.imgmath',
]

imgmath_image_format = 'svg'

imgmath_latex = 'lualatex'

imgmath_dvisvgm_args = ['--pdf']

imgmath_latex_preamble = '\\usepackage{unicode-math}\\setmathfont{XITS Math}'
```

and this source

```rst
TEST LUATEX FOR MATH TO SVG
===========================


.. math::

   x^n + y^n = z^n

.. math::

   E = mc^2

```

Then ``make html`` succeeds and produces two svg files. Problems:

- As expected with lualatex+unicode-math this is slow. It is also slow with xelatex+unicode-math.

- For all three lualatex, xelatex, pdflatex (for the latter without unicode-math, XITS Math) the svg are not cropped to their contents:

  ```xml
  <?xml version='1.0' encoding='UTF-8'?>
  <!-- This file was generated by dvisvgm 2.6.2 -->
  <svg height='841.89pt' version='1.1' viewBox='0 -841.89 595.276 841.89'   width='595.276pt' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink'>
  ...
  ```

  On the other hand when applying ``dvisvgm --pdf -p "1-"`` on a pdf file produced by ``xelatex``  on a document using ``standalone`` class I obtain correctly sized svg's

  ```console
  $ dvisvgm --pdf -p "1-" test.pdf
  processing PDF file
    graphic size: 58.488512pt x 9.134125pt (20.556361mm x 3.210278mm)
    output written to test-1.svg
  processing PDF file
    graphic size: 58.488512pt x 9.184312pt (20.556361mm x 3.227917mm)
    output written to test-2.svg
  2 of 2 pages converted in 0.167296 seconds
  ```

I need to check if I am missing some other option of ``dvisvgm`` to use in case of pdf; for some reason we did not need to worry about this with ``latex`` and ``dvi`` output format. Perhaps it is needed to apply ``pdfcrop`` on pdf file first before using ``dvisvgm``?

Incidentally I think ``dvisvgm`` uses the ghostscript library in the case of ``--pdf`` option which is extra dependency. (and ``pdfcrop`` which comes with TeXLive also uses gs).

Another thing: (in relation with #6281) I encountered a LaTeX problem of compatibility of ``standalone`` with the amsmath environments which I have to investigate; I needed to use plain ``$...$`` for the math in my latex file (this is the same for pdflatex, xelatex, lualatex). I could not use the amsmath environments with ``standalone`` directly.

The present issue is about supporting PDF as intermediate format but as I explained, the rationale is that there are problems of interaction of ``dvisvgm`` with ``dvilualatex`` regarding font specifiers, hence the idea to use ``lualatex`` which outputs PDF as an alternative. 

But if #6279 is solved, then we don't need to worry too much about this. And indeed the [patch](https://github.com/sphinx-doc/sphinx/issues/6279#issuecomment-483302127) you propose worked for me. I will comment over there and I think we can thus close this issue.
