### ISSUE TITLE
Wrong smart quote (apostrophe) when source is in Markdown, but ok for reST

### ISSUE THREAD

**Issue by jfbu** [sphinx-doc/sphinx#6282]
**Describe the bug**

See attached project. The markdown source produces ``l”eau`` in html, and the reST source produces the correct ``l’eau``. The language is French.

**Environment info**
- OS: Mac
- Sphinx version: 2.0.2+
- Python version: 3.6.8 (CPython)
- Docutils version: 0.14 
- Pygments version: 2.3.1
- Jinja2 version: 2.10

Using `recommonmark` freshly installed in a virtualenv via ``pip install -U``.

[markdownsmartquotes.zip](https://github.com/sphinx-doc/sphinx/files/3074605/markdownsmartquotes.zip)

**Comment by tk0miya** [comment]
The result of reST parser (docutils') is consisted with single text element.
```
[<#text: "l'eau">]
```

On the other hand, the result of recommonmark parser is consisted with 3 text elements.
```
[<#text: 'l'>, <#text: "'">, <#text: 'eau'>]
```

This is unexpected structure by docutils' smartquote processor. IMO, recommonmark should concatenate these text element into single one.

**Comment by tk0miya** [comment]
I think there are nothing to do from Sphinx side. So closing now.
