### ISSUE TITLE
Warning for usage of source_suffix for Markdown input format isn't very helpful to end user

### ISSUE THREAD

**Issue by jfbu** [sphinx-doc/sphinx#6283]
**Describe the bug**

A friend has a project which uses old syntax for Markdown and is built with Sphinx 1.8.5.

I tried it out on Sphinx 2.0.2+ keeping deprecated conf.py like this:

```
# The markdown parser
source_parsers = {
   '.md': 'recommonmark.parser.CommonMarkParser',
}

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
source_suffix = ['.rst', '.md']
```

On `make html` this generates warning of this type:

```
Sphinx v2.0.2+/c3899e4 en cours d'exécution
Chargement des traductions [fr]...fait
/Users/xxx/sphinx/sphinx/util/compat.py:33: RemovedInSphinx30Warning: The config variable "source_parsers" is deprecated. Please use app.add_source_parser() API instead.
  RemovedInSphinx30Warning)
/Users/xxx/sphinx/sphinx/util/compat.py:37: RemovedInSphinx30Warning: app.add_source_parser() does not support suffix argument. Use app.add_source_suffix() instead.
  app.add_source_parser(suffix, parser)
loading pickled environment... fait
construction en cours [mo]:targets for 0 po files that are out of date
construction en cours[html]: targets for 0 source files that are out of date
updating environment: 0 added, 0 changed, 0 removed
recherche des fichiers périmésaucun résultat
aucune cible n'est périmée
compilation réussi.
```

But in fact the end user should follow the guidelines from [our docs](https://www.sphinx-doc.org/en/2.0/usage/markdown.html?highlight=markdown). Hence the warning looks strange and is not helpful.

**Environment info**
- OS: Mac
- Python version: 3.6.8
- Sphinx version: v2.0.2+/c3899e4
- Sphinx extensions:  recommonmark

**Comment by tk0miya** [comment]
Understand. Do you have any idea for better message?

**Comment by jfbu** [comment]
> Understand. Do you have any idea for better message?

Perhaps like this

```
The config variable "source_parsers" is deprecated. It is not needed for recommonmark usage (see docs). And extensions can use app.add_source_parser() API instead.
```

**Comment by tk0miya** [comment]
`source_parsers` is not only for recommonmark. So second sentence is strange to me.

**Comment by jfbu** [comment]
I agree but I feel some sentence like second one is needed when usage comes from conf.py. Maybe check if `'.md'` key was used in `source_parsers` ?

**Comment by tk0miya** [comment]
How about this?
```
The config variable "source_parsers" is deprecated. Please update your extension for the parser and remove the setting.
```

**Comment by jfbu** [comment]
Probably is indeed better...

**Comment by tk0miya** [comment]
Updated at #6307.

**Comment by rpgoldman** [comment]
A link to an explanation to how to fix this would make this error message more helpful.  Even the revised error message seems pretty cryptic to me.  The problem with "Please update your extension for the parser and remove the setting." is that the library I'm trying to fix has this in its `conf.py`:

```
source_parsers = {".md": "recommonmark.parser.CommonMarkParser"}
source_suffix = [".rst", ".md"]
```

In the existing warning to a non-expert:
1. What is "the parser"?  is it `"recommonmark.parser.CommonMarkParser"` if so
2. What does it mean to update the the extension? Update from `".md"`?  But what do we update it *to*?
3. What does it mean to **both** update the extension **and** remove the setting?  If we remove the setting, then isn't the extension gone? If not....?

Probably the easiest fix would be to put a FAQ in the sphinx docs for this, and put a URL to that link in the warning message.

**Comment by rpgoldman** [comment]
Looks like this `https://www.sphinx-doc.org/en/master/usage/markdown.html` is the URL that should go here.
