### ISSUE TITLE
A warning on using recommonmark

### ISSUE THREAD

**Issue by jfbu** [sphinx-doc/sphinx#6284]
**Describe the bug**
When using current recommonmark extension installed in a virtualenv by `pip install` I get seemingly systematically 

```
/Users/xxx/yyy/sphinxvenv/lib/python3.6/site-packages/recommonmark/parser.py:65: UserWarning: Container node skipped: type=document
  warn("Container node skipped: type={0}".format(mdnode.t))
```

Got it on two projects. One with old way (deprecated) of using recommonmark, the other one following [our guidelines](https://www.sphinx-doc.org/en/2.0/usage/markdown.html?highlight=markdown)

**Environment info**
- OS: Mac
- Python version: 3.6.8
- Sphinx version: 2.0.2+
- Sphinx extensions:  recommonmark

I suppose I should report to recommonmark project...

**Comment by tk0miya** [comment]
The warning is emitted inside recommonmark. So there are nothing to do from sphinx side.
https://github.com/rtfd/recommonmark/blob/815d75ea503f30af26ab67c6820078f84875b1fc/recommonmark/parser.py#L64-L65

**Comment by tk0miya** [comment]
Closing.

**Comment by jacobtomlinson** [comment]
This issue has been raised over on recommonmark, linking for others that land here.

readthedocs/recommonmark#177
