### ISSUE TITLE
Unable to document bound instance methods exported as module functions

### ISSUE THREAD

**Issue by alsrgv** [sphinx-doc/sphinx#6287]
**Is your feature request related to a problem? Please describe.**
We're building an API documentation site for Horovod project (http://horovod.ai) and faced the problem with documenting bound methods that we export as module functions (duck typing yay!)

Simple example:
```python
class _Boo(object):
    def m(self):
        """Everybody needs a method that returns 42, right?"""
        return 42


_b = _Boo()
n = _b.m
```

Real example: [declaration](https://github.com/horovod/horovod/blob/68f525c64cdd5a31536f5485448960fbb00d19fc/horovod/common/__init__.py#L58), [usage](https://github.com/horovod/horovod/blob/6643d6aa4abd583e5d254e2658e413a309f47a54/horovod/tensorflow/mpi_ops.py#L64).

I found that it does not show up in the docs because it does not match either of these conditions:

`FunctionDocumenter`:
```python
@classmethod
def can_document_member(cls, member, membername, isattr, parent):
    # type: (Any, unicode, bool, Any) -> bool
    return isfunction(member) or isbuiltin(member)
```

`MethodDocumenter`:
```python
@classmethod
def can_document_member(cls, member, membername, isattr, parent):
    # type: (Any, unicode, bool, Any) -> bool
    return inspect.isroutine(member) and \
        not isinstance(parent, ModuleDocumenter)
```

**Describe the solution you'd like**
I'd like those doc strings to show up in the docs.

I tried modifying both `MethodDocumenter` and `FunctionDocumenter` conditions to allow for `inspect.isroutine(member) and isinstance(parent, ModuleDocumenter)` and found that `FunctionDocumenter` gives more satisfying results.

What is the best way to document those functions?  Would you take a PR where `FunctionDocumenter` is modified as follows:

```python
@classmethod
def can_document_member(cls, member, membername, isattr, parent):
    # type: (Any, unicode, bool, Any) -> bool
    return isfunction(member) or isbuiltin(member) or (inspect.isroutine(member) and  isinstance(parent, ModuleDocumenter))
```

... or maybe there's another way to achieve this?

**Comment by tk0miya** [comment]
+0; It's not a function, but acceptable change :-)

**Comment by alsrgv** [comment]
@tk0miya, thanks for the feedback!  Created a PR :-)
