### ISSUE TITLE
make Sphinx read bibtex files for references

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#63]
== Description ==
Sphinx is used by many (and becoming more every day) scientific python projects.
Especially in science, naming references for implemented algorithms is very important.

This also reflected in the numpy example docstings:
http://projects.scipy.org/scipy/numpy/browser/trunk/doc/example.py#L37

These can be processed by the sphinx extension numpydoc.

Many scientist maintain such refernces in Bibtex data base files which are actually specially formatted ascii files (like .rst).

It would be nice if Sphinx could parse such reference lists.

== Example docstring ==

def myfunc(x):
    """
    This function was implemented like shown by [brandl:08].

```
"""
```

== Example result ==

def myfunc(x):
    This function was implemented like shown by //Brandl et al.//.

Then, we could add a page which adds up all literature:

References

Branl et al (2008): Sphinx

== List of python bibtex projects ==
A list of bibtex parser for python is provided below.
The first one seems to be the most promising.
# Pybtex is a drop-in replacement for BibTeX written in Python.

http://pybtex.sourceforge.net
https://launchpad.net/pybtex
http://pybtex.sourceforge.net/manual.html
# Pybliographer

https://launchpad.net/pybliographer
# python-bibtex

https://launchpad.net/ubuntu/+source/python-bibtex

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/63
- Originally reported by: [timmie](https://bitbucket.org/timmie)
- Originally created at: 2008-12-01T21:47:58.965

**Comment by shimizukawa** [comment]
_From [timmie](https://bitbucket.org/timmie) on 2008-12-01 20:58:10+00:00_

== Another library ==

Digging deeper and refinig my Google search I found another interesting library that could be used.
It seems to be closer targeted at ReSt files:

http://code.google.com/p/bibstuff/

== Bibtex explanation ==
http://en.wikibooks.org/wiki/LaTeX/Bibliography_Management

== Example for reference in  docstrings ==
http://docs.scipy.org/doc/scipy/reference/sparse.linalg.html?highlight=reference

**Comment by shimizukawa** [comment]
_From [timmie](https://bitbucket.org/timmie) on 2008-12-01 22:37:02+00:00_

Some further ideas:

according to the examples [1](http://bibstuff.googlecode.com/svn/trunk/examples/examples-README.txt) this is ready to be used:

{{{
#!python

testout.txt
    Example output bibliography from running bib4txt.py on
    rst_input.txt. 
    `> python bib4txt.py -i examples/rst_input.txt -no examples/new-testout.txt examples/example.bib`
}}}

I can imagine the following procedure to make it work in Sphinx:

1) insert reference key in text like:

   Blah, blah, see [isaac.schwilk-2010]_

2) put your bibtex file in source/_static
3) run sphinx-build

### 
- Inside sphinx the whole process seems to be similar like the index, module index, and glossary creation.
- Sphinx would run all files through bib4txt.py to collect the references. These would then be written into a reference.html file and added to the TOC like the index.
- bib4txt.py works with include files to integrate the restifyed bibtex file.
  
  {{{
  #!python

.. include:: testout.txt
}}}

```
Such a include could be defined in conf.py. A request ins already made here [2]
```

**Comment by shimizukawa** [comment]
_From [timmie](https://bitbucket.org/timmie) on 2008-12-16 16:19:29+00:00_

== First version of bibtex extension ==

=== Purpose ===
Collect all citations within the source docs and 
docstrings.
Assesmble a document with the used references from
a bibtex data base file.
=== Status === 
- works on documents in source
- references also citations in docstrings
  === ToDo === 
- parse docstrings in order to compile references only
  of the used citations
- Reformat the citation links:
  *\* assign a title instead of the bibtex key
  *\* example: [smith54]_ => `Smith et al. (1954) <smith>`_

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2008-12-20 22:36:40+00:00_

Hi Timmie,

I just want to note that I'm not ignoring your work here :) It is much appreciated and will be revisited in time for 0.6 or 0.7. Thanks!

**Comment by shimizukawa** [comment]
_From [timmie](https://bitbucket.org/timmie) on 2008-12-30 22:54:55+00:00_

Hello,
thank for coming back on this.
It works well as described above. Only the docstrings give me trouble...

Thanks.

**Comment by shimizukawa** [comment]
_From [timmie](https://bitbucket.org/timmie) on 2009-01-13 18:56:55+00:00_

Please note a discussion here:

coding style: citations - http://article.gmane.org/gmane.comp.python.numeric.general/27213

**Comment by shimizukawa** [comment]
_From Anonymous on 2011-02-01 19:50:30+00:00_

Hello Timmie,

are you still using Bibtex with Sphinx?

If so, could you repost a snapshot of your Bibtex extension? The attachment link above seems to be broken.

Thanks,
Peter

**Comment by shimizukawa** [comment]
_From [bmu](https://bitbucket.org/bmu) on 2011-03-21 21:40:08+00:00_

For bibtex I use an adapted version of the bibcite-extension (http://hg.telking.com/foobaron/bibcite). 

For latex I use rubber (https://launchpad.net/rubber) to make sure, that citations and references are resolved (I call rubber from the sphinx makefile).

For html I use a direct link to reference papers in a local directory (this is not really nice, but it's ok for  a html document). For a real bibliography in html I think Pybtex (http://pybtex.sourceforge.net) could be good, but would add a dependency.

**Comment by xuhdev** [comment]
I think this has been solved by [sphinxcontrib-bibtex](https://sphinxcontrib-bibtex.readthedocs.org/)...

**Comment by tk0miya** [comment]
Now we have great ecosystem of Sphinx extensions. And I believe sphinxcontrib-bibtex works fine for reading bibtex resources on Sphinx document. There are no reason to merge it into Sphinx core.
So I'm closing this now.
