### ISSUE TITLE
Tables render without borders in 2.0.0

### ISSUE THREAD

**Issue by 2uasimojo** [sphinx-doc/sphinx#6312]
When I build a table like

    .. list-table:: Worklists
       :header-rows: 1
    
       * - List
         - Main Tag
         - Description
       * - `Untriaged Stories <https://storyboard.openstack.org/#!/worklist/580>`_
         - No tags
         - New or unvisited stories which have not yet been categorized (and should
           be).
       * - `Bugs <https://storyboard.openstack.org/#!/worklist/574>`_
         - ``bug``
         - Incorrect behavior in existing code, features or documents. If the issue
           is with documentation, add the tag ``docs``.
       * - `Features <https://storyboard.openstack.org/#!/worklist/594>`_
         - ``rfe``
         - Planned or requested features or enhancements to the system.
       * - `Cleanups <https://storyboard.openstack.org/#!/worklist/575>`_
         -  ``cleanup``
         - Improvements to the code or surrounding repository to help with
           maintenance or other development lifecycle issues that are not otherwise
           a bug or feature.

using sphinx 1.8.5 vs 2.0.0 my <table> tag changes thusly:

    226c226
    < <table border="1" class="docutils" id="id2">
    ---
    > <table class="docutils align-center" id="id2">

...meaning my table renders with no border in 2.0.0 whereas it used to have one under 1.8.5.

**Comment by tk0miya** [comment]
I'm sorry but could you update your theme please? This comes from moving HTML5 based writers on 2.0.

**Comment by stephenfin** [comment]
@2uasimojo To clarify, we switched the default builder from HTML4 to HTML5 in Sphinx 2.0. This will result in some different HTML output, meaning you may need to rework your theme (openstackdocstheme?) to target different elements now. See [here](https://review.opendev.org/#/c/655734/) for a non-theme example of the type of the changes you could expect to see.

**Comment by 2uasimojo** [comment]
Okay, I have no idea how to do that, so I opened https://bugs.launchpad.net/openstack-doc-tools/+bug/1828265 against openstackdocstheme. Thanks.

**Comment by ianychoi** [comment]
FYI for reference: https://review.opendev.org/#/c/661344/
