### ISSUE TITLE
Table of Contents doctree elements "pending"

### ISSUE THREAD

**Issue by Phillip-M-Feldman** [sphinx-doc/sphinx#6315]
When I look at http://docutils.sourceforge.net/docs/ref/rst/directives.html#table-of-contents, I see the following:

  Doctree Elements: | pending, topic

The word "pending" suggests that this documentation is incomplete.  In any case, a better explanation is needed.

**Comment by tk0miya** [comment]
Would you like to update the page? If so, you should report this to docutils project instead.
It is not ours.
