### ISSUE TITLE
undocumented behavior: inner functions ignored

### ISSUE THREAD

**Issue by Phillip-M-Feldman** [sphinx-doc/sphinx#6318]
This is not a bug per se: From looking at the following code in pycode/parser.py, I realized that Sphinx ignores inner functions.  This behavior is reasonable, but should be documented in the user documentation.

    def add_definition(self, name, entry):
        # type: (str, Tuple[str, int, int]) -> None
        if self.indents and self.indents[-1][0] == 'def' and entry[0] == 'def':
            # ignore definition of inner function
            pass
        else:
            self.definitions[name] = entry

**Comment by tk0miya** [comment]
Are you saying autodoc should be document inner functions? If so, it is hard to realize that. Because autodoc generates document from imported python script dynamically. As you know, we can't touch inner functions from outside of module.

Note: `parser.py` is mainly used to obtain the location of functions, classes and methods. It is not related with generating documentation directly.

**Comment by Phillip-M-Feldman** [comment]
This makes complete sense.  Perhaps a note should be added to the user
documentation stating that autodoc does not document inner functions?

**Comment by tk0miya** [comment]
I don't think so. autodoc extension has been mainly used to create a reference manual. Therefore, inner functions are not important for such kind of documents. So -1 for adding a note.

**Comment by Phillip-M-Feldman** [comment]
It depends whether the reference manual is for users or for developers.  If
the former, I agree with you.

**Comment by tk0miya** [comment]
AFAIK, autodoc has been used for the reference manual for users. Python's, scipy, numpy, and so on. I don't know about cases for developers. I don't know autodoc can't use for references for developers. But it is hard to do both for users and for developers.

To describe internal functions and methods, we should also describe about local variables. But autodoc does not support them also. I suppose you need to create new module which analyze the source code statically. It would be very worthy for other users :-)

**Comment by Phillip-M-Feldman** [comment]
OK.  Point taken.

On a related subject: Is there any way to force Sphinx to include TOC
entries for (non-internal) functions, classes, and methods?

**Comment by tk0miya** [comment]
AFAIK, there are no official way to do that. But it only means sphinx-core does not support it. You can do it with your own extension.

**Comment by tk0miya** [comment]
I'm closing this now.
