### ISSUE TITLE
Add pass-through of sphinx-build CLI arguments to make.bat.new_t

### ISSUE THREAD

**Issue by bskinn** [sphinx-doc/sphinx#6323]
**Is your feature request related to a problem? Please describe.**

It's frustrating not being able to pass extra arguments to `make.bat` that then get provided to `sphinx-build`. E.g., `> make html -Ean` is not feasible.  (This is a subset of #3741.)

**Describe the solution you'd like**

I'd like this capability to be added to Sphinx.  I already have an implementation in [my fork](https://github.com/bskinn/sphinx/commit/1295ae861cd109089206e3e37ba5973d7fa1f714).

**Describe alternatives you've considered**

#3841 attempted a more-ambitious implementation, but was rejected due to likely too-great maintenance requirements.  It looks like the whole makefile/make.bat setup will be obsoleted by #5618; but this seems like a simple enhancement to implement in the meantime.

**Additional context**

Screencap of implemented feature in action:

![image](https://user-images.githubusercontent.com/11325439/56745872-29055680-6749-11e9-8edf-759ca11301b6.png)

**Comment by tk0miya** [comment]
`make.bat` already provides an environment variable `%SPHINXOPTS%` to give extra option on execution. I think this would help your case. Please try it :-)
https://www.sphinx-doc.org/en/master/man/sphinx-build.html#environment-variables

**Comment by bskinn** [comment]
Yes, I know of `%SPHINXOPTS` already. Using an env variable for this purpose is awkward and slow, because I rarely want to use the same sphinx-build options in consecutive invocations, and as far as I know there's no elegant/quick way to tweak the environment for a particular shell command.

On Linux, `make html O={options}` works nicely, but I have not been able to get anything like that to work on Windows. If it *does* work somehow, and I've just been doing it wrong, then introducing the same `%O%` (or similar) shorthand variable as in `Makefile` would be most convenient. Then at least something terse like `> set O=-E -a & make html` should work ok.

**Comment by tk0miya** [comment]
Thank you for explanation. I understand your goal. But, personally, I feel a bit strange for giving parameters for sphinx-build as arguments of make.bat. I know windows is not under UNIX culture. But...

Note: I'm okay to add `%O%` shorthand to `make.bat`.  But it would not resolve your concern.

**Comment by bskinn** [comment]
> I feel a bit strange for giving parameters for sphinx-build as arguments of make.bat.

Ahh, I hadn't thought of it from that angle -- yeah, `make` doesn't pass arguments through, so it *would* be odd for `make.bat` to do so.

I can open a PR to add the `%O%` shorthand option to `make.bat`--that at least will reduce the amount of typing necessary to adjust the build arguments.  Which branch should I take out the PR against... probably `2.0`, since this shouldn't be a breaking change?

**Comment by tk0miya** [comment]
@bskinn I think `%O%` does not break compatibility. So 2.0 branch is better for this. Could you send a PR please?
