### ISSUE TITLE
Regression in reference rendering in scikit-image gallery examples

### ISSUE THREAD

**Issue by soupault** [sphinx-doc/sphinx#6324]
**Describe the bug**
Hi!
There is a regression in the rendering of the references.
Built with Sphinx 1.7.0:
![image](https://user-images.githubusercontent.com/1315589/56764403-4966fc80-67ad-11e9-8944-ebcd768836a9.png)
Built with Sphinx 2.0.0 (1.8.0 and later versions are, probably, also affected):
![image](https://user-images.githubusercontent.com/1315589/56764481-71eef680-67ad-11e9-8a89-bea4ef485ff8.png)

**To Reproduce**

```
$ git clone https://github.com/scikit-image/scikit-image
$ cd scikit-image
$ pip install all the requirements from ./requirements
$ pip install .
$ cd doc
$ make html
$ open build/html/auto_examples/applications/plot_haar_extraction_selection_classification.html
```

**Environment info**
- OS: Ubuntu 18.04 / Mac 10.14.4
- Python version: 3.6.8
- Sphinx version: see above
- Sphinx extensions:
```
'sphinx_copybutton',
'sphinx.ext.autodoc',
'sphinx.ext.mathjax',
'numpydoc',
'doi_role',
'sphinx.ext.autosummary',
'sphinx.ext.intersphinx',
'sphinx.ext.linkcode',
'sphinx_gallery.gen_gallery'
```
- Extra tools: any browser

**Additional context**

- https://github.com/scikit-image/scikit-image/issues/3853

**Comment by jfbu** [comment]
I doubt this is core Sphinx issue. Have you tried obtaining a small project demonstrating the issue without `numpydoc` for example?

**Comment by soupault** [comment]
@jfbu I have tried several different versions of `numpydoc` and the issue remained.

Hmm... Would it help if I attach also the generated html pages from the examples above?

**Comment by jfbu** [comment]
@soupault I don't know, your problem reminded me of https://github.com/numpy/numpydoc/issues/169 and if it is problem of interaction of numpydoc with current Sphinx, it should primarily be asked at numpydoc.

**Comment by jfbu** [comment]
It is too complicated to test with your big project. After installing all requirements I get

```
ImportError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are using (Ana)Conda please install python.app and replace the use of 'python' with 'pythonw'. See 'Working with Matplotlib on OSX' in the Matplotlib FAQ for more information.
```

which apparently originates in matplotlib installed via pip. Please try to produce some small project with the error so that it can be tested.

**Comment by tk0miya** [comment]
There are two difference to my eyes. One is layout (gray bar is shown!). And another is back references are shown. Did you say which is unexpected?
I think this has came from the change of HTML writer. I guess you can see the original behavior with `html4_writer = True` option (And you will see same result even with Sphinx-1.8 if  `experimental_html5_writer = True`).

If you mean first one is strange. Your theme does not support HTML5 mode. So please modify your theme or use HTML4 writer.

**Comment by tk0miya** [comment]
I'm closing this now because no updates.
Please feel free to reopen if you're still in trouble.
Thanks,
