### ISSUE TITLE
Allow for slots to be documented in the 3.8 mentioned dictionary style

### ISSUE THREAD

**Issue by 13steinj** [sphinx-doc/sphinx#6325]
**Is your feature request related to a problem? Please describe.**
To an extent. Sphinx's support of slots and conflicts between slots and the ideas of member types vs class variables has been a long standing issue (see context).

**Describe the solution you'd like**
*If* slots is a dictionary, the values of the dictionary can be used as docstrings for that slot.

**Describe alternatives you've considered**
Current documentation methods for slots, but it is lacking and has issues with conflicts and more.

**Additional context**
- https://docs.python.org/dev/whatsnew/3.8.html#inspect
- #4678
- https://github.com/sphinx-doc/sphinx/issues/4678#issuecomment-426334192
- https://github.com/sphinx-doc/sphinx/issues/2549#issuecomment-408709869

**Comment by tk0miya** [comment]
Done in #6388.
Thank you for reporting!
