### ISSUE TITLE
sphinx-build -b html -d NameError: name 'reportlab' is not defined

### ISSUE THREAD

**Issue by devwithzachary** [sphinx-doc/sphinx#6329]
**Describe the bug**
When running html generation I ended up with the error:

```
Exception occurred:
File "/usr/local/lib/python2.7/dist-packages/rst2pdf/flowables.py", line 895, in <module>
   if reportlab.Version == '2.1':
 NameError: name 'reportlab' is not defined
```

**To Reproduce**
```
sphinx-build -b html -d stage/doctrees   source/welcome stage/html
```

**Expected behavior**
HTML should be generated

**Environment info**
- OS: [Linux - Ubuntu 18.04.1]
- Python version: [2.7.15rc1]
- Sphinx version: [1.8.5]

**Additional context**
Editing the flowables.py file to add in 'import reportlab' seemed to fix the issue. Now sure if tihs is a Sphinx issue or a rst2pdf issue

**Comment by devwithzachary** [comment]
I have added a pull request to https://github.com/rst2pdf/rst2pdf/pull/770 to be sure

**Comment by tk0miya** [comment]
As you did, this must be a bug of rst2pdf, not Sphinx. Closing.
