### ISSUE TITLE
invalid markup in man page when doctest follows rubric

### ISSUE THREAD

**Issue by anntzer** [sphinx-doc/sphinx#6331]
**Describe the bug**

When a rst doctest follows a rst rubric, sphinx's man output inserts incorrect markup which ends up not rendered by man.

**To Reproduce**
```
$ sphinx-quickstart -q -pfoo -afoo
```
edit index.rst to add
```
.. rubric:: Examples

>>> print("hello, world")
```
then
```
$ make man
$ man _build/man/foo.1
```
The rendered man page contains the following
```
Examples.sp
>>> print("hello, world")
```
(note the `.sp`)

**Expected behavior**
The rendered man page should show up as
```
Examples

>>> print("hello, world")
```

It would also be nice if the rubric name was highlighted in some way (e.g., like a `.. topic::`).

**Your project**
N/A

**Screenshots**
N/A

**Environment info**
- OS: arch linux
- Python version: 3.7.3
- Sphinx version: 2.0.1
- Sphinx extensions: none
- Extra tools: man

**Additional context**

- [e.g. URL or Ticket]

**Comment by tk0miya** [comment]
Fixed by #6343.
Thank you for reporting!
