### ISSUE TITLE
Not all dependencies are installed from an editable pip install of sphinx in a virtualenv

### ISSUE THREAD

**Issue by jfbu** [sphinx-doc/sphinx#6336]
Creating a fresh virtualenv and then executing

` ` ` 
pip install -e .
` ` ` 

from a git clone of sphinx-doc/sphinx dev repo, some dependencies are not installed for a fully functional install:

- sphinxcontrib-websupport,

- graphviz

Both are needed when one builds the doc from sphinx/doc/.

Absence of graphviz causes a failed `make latexpdf` due to graphics inclusion of non-existent "None" file. This comes from documentation of [`sphinx.ext.inheritance-diagram`](http://www.sphinx-doc.org/en/master/usage/extensions/inheritance.html)

Also

- pytest

- html5lib

are not automatically installed. But there are needed for running test with make. Maybe this is anyhow deprecated from using `tox`?

**Comment by jfbu** [comment]
(I do understand graphviz is not a Python dependency .... :) )

**Comment by tk0miya** [comment]
About latter dependencies, you can install them with `pip install -e '.[test]'` command. They're defined as "extra" dependencies tagged by "test". So you need to give `[test]` parameter to pip to install them all.
https://github.com/sphinx-doc/sphinx/blob/b0d070c8572c8316bf72889d6b04b95e6ce905bf/setup.py#L36-L50

On the other hand, former one is not defined yet. So it would be better to define them on setup.py soon. But, I don't have good idea to describe dependencies for non python packages like graphviz. bindep.txt might help us.

**Comment by jfbu** [comment]
> About latter dependencies, you can install them with `pip install -e '.[test]'` command.

Works for me thanks.

**Comment by tk0miya** [comment]
I just added extra dependency named "docs" in #6337.
Closing.
