### ISSUE TITLE
Escaping of nested braces with :samp: doesn't work properly

### ISSUE THREAD

**Issue by jwodder** [sphinx-doc/sphinx#6340]
Using the `:samp:` role and trying to enclose the variable part inside literal braces does not produce the correct results.  This input:

```
:samp:`%\{{name}\}C`
```

(Note that the outer braces are escaped) results in the following HTML:

```html
<code class="samp docutils literal notranslate"><span class="pre">%</span><em><span class="pre">{name</span></em><span class="pre">}C</span></code>
```

Note that the left brace in the output is emphasized as though it were part of the variable portion of the sample text, which does not make sense, as the escaped left brace in the input occurs before the non-escaped left brace that should mark the start of the variable part.

**Environment info**
- OS: Ubuntu Xenial 18.04.2
- Python version: 3.6.7
- Sphinx version: 2.0.1

**Comment by tk0miya** [comment]
Unfortunately, the first left brace is not escaped with your notation. Before evaluating contents inside backquotes, reST parser considers the backslash as a escaping character. As a result, ```:samp:`%\{{name}\}C` ``` is parsed as `%{{name}}C` (not containing backslashes) is given to `:samp:` role. Therefore, the first left brace is considered for opening emphasis, not escaped.

To escape the braces, please put **double** backslashes before them.  So ```:samp:`%\\{{name}\\}C` ``` will work as you want.

**Comment by jwodder** [comment]
Thank you for your help.  That might be useful to note in the `:samp:` documentation.
