### ISSUE TITLE
Quick-start utility questions missing

### ISSUE THREAD

**Issue by matthijsramlab** [sphinx-doc/sphinx#6346]
**Describe the bug**

When I am using the quick-start command, some of the questions are not asked. I get the following questions:

Welcome to the Sphinx 2.0.1 quickstart utility.

Please enter values for the following settings (just press Enter to
accept a default value, if one is given in brackets).

Selected root path: .

You have two options for placing the build directory for Sphinx output.
Either, you use a directory "_build" within the root path, or you separate
"source" and "build" directories within the root path.
> Separate source and build directories (y/n) [n]: y

The project name will occur in several places in the built documentation.
> Project name: MonitoringApp
> Author name(s): Test
> Project release []: 0.1

If the documents are to be written in a language other than English,
you can select a language here by its language code. Sphinx will then
translate text that it generates into that language.

For a list of supported codes, see
http://sphinx-doc.org/config.html#confval-language.
> Project language [en]: en

Creating file .\source\conf.py.
Creating file .\source\index.rst.
Creating file .\Makefile.
Creating file .\make.bat.

Finished: An initial directory structure has been created.

You should now populate your master file .\source\index.rst and create other documentation
source files. Use the Makefile to build the docs, like so:
   make builder
where "builder" is one of the supported builders, e.g. html, latex or linkcheck.

I was following the documentation and it seems that are questions missing, in the docs it is asking to say yes to autodoc? Of course, I can edit this to the config.py manually,

**Comment by tk0miya** [comment]
Since 2.0, questions of quickstart become simple (refs: #4148). To enable autodoc, please give `--ext-autodoc` option to quickstart.

Thanks,

**Comment by tk0miya** [comment]
Closing. Thanks,

**Comment by Duckle29** [comment]
Re-opening as I think docs need to be updated to reflect this change: https://www.sphinx-doc.org/en/master/usage/quickstart.html
