### ISSUE TITLE
Fail to parse signature with typing that contains a Union with a plain Tuple on Python 3.6 and 3.5

### ISSUE THREAD

**Issue by volans-** [sphinx-doc/sphinx#6347]
**Describe the bug**
Sphinx fails to parse the signature of a class method that uses type hints and has a parameter with a `Union` type that includes a plain `Tuple` on Python 3.6 and 3.5.
Example signature:
```python
    def mymethod(self, myparam: Union[int, Tuple] = 10) -> List[Dict]:
```

When parsing this code Sphinx fails on Python 3.5 and 3.6 with:
```
Warning, treated as error:
error while formatting arguments for mymodule.MyClass.mymethod: 'NoneType' object is not iterable
```

While it work as expected on Python 3.7.
Just for reference a plain `Tuple` is a valid type and is equivalent to `Tuple[Any, ...]`.

**To Reproduce**
To my understanding any signature with a type hint of `Union[Tuple]` should reproduce the error.

**Expected behavior**
Sphinx should have correctly parsed the signature.

**Environment info**
- OS: the issue was reproduced on both Linux Debian and Macos
- Python version: 3.5.6, 3.6.7 for the repro, 3.7.3 where it works
- Sphinx version: 2.0.1
- Sphinx extensions:  not applicable

**Additional context**
I've managed to get a full stacktrace that is pretty long, so pasting here only the final relevant part. This is on 3.5 but the 3.6 one is equivalent:
```python
  File "/tmp/myproject/.tox/py35-tests/lib/python3.5/site-packages/sphinx/ext/autodoc/__init__.py", line 1305, in format_args
    args = Signature(self.object, bound_method=True).format_args()
  File "/tmp/myproject/.tox/py35-tests/lib/python3.5/site-packages/sphinx/util/inspect.py", line 384, in format_args
    arg.write(self.format_annotation(param.annotation))
  File "/tmp/myproject/.tox/py35-tests/lib/python3.5/site-packages/sphinx/util/inspect.py", line 437, in format_annotation
    return self.format_annotation_old(annotation)
  File "/tmp/myproject/.tox/py35-tests/lib/python3.5/site-packages/sphinx/util/inspect.py", line 540, in format_annotation_old
    param_str = ', '.join(self.format_annotation(p) for p in params)
  File "/tmp/myproject/.tox/py35-tests/lib/python3.5/site-packages/sphinx/util/inspect.py", line 540, in <genexpr>
    param_str = ', '.join(self.format_annotation(p) for p in params)
  File "/tmp/myproject/.tox/py35-tests/lib/python3.5/site-packages/sphinx/util/inspect.py", line 437, in format_annotation
    return self.format_annotation_old(annotation)
  File "/tmp/myproject/.tox/py35-tests/lib/python3.5/site-packages/sphinx/util/inspect.py", line 499, in format_annotation_old
    param_str = ', '.join(self.format_annotation(p) for p in params)
TypeError: 'NoneType' object is not iterable
```

After some debugging I've noticed that the code enters the first `if` block in https://github.com/sphinx-doc/sphinx/blob/master/sphinx/util/inspect.py#L526 where at line 530-531 does:
```python
            params = annotation.__args__
            param_str = ', '.join(self.format_annotation(p) for p in params)
```

But on Python 3.5 and 3.6 a plain Tuple has `__args__` that is `None`:
```python
>>> from typing import Tuple
>>> Tuple.__args__ is None
True
```
So the iteration over `params` fails.

**Possible Fix**
A quick fix could be to just replace line 530 with:
```python
            params = annotation.__args__ or ()
```

Although I've not sent yet a PR because the comments in that part of the code confuses me as they seem to contradict each other, in particular line 529 `# This is for Python 3.6+, 3.5 case is handled below` vs line 533 `# for py36 or below`.
When clearly the first `if` block would not match Python 3.7 given that on 3.7:
```python
>>> hasattr(typing, 'TupleMeta')
False
```
So I would like some advice from people more familiar with that part of the code before sending a patch.

**Comment by tk0miya** [comment]
Fixed by #6404.
Thank you for reporting.
