### ISSUE TITLE
Documentation: FAQ refers to heiroglyph which doesn't work with current version

### ISSUE THREAD

**Issue by cheshirekow** [sphinx-doc/sphinx#6348]
The sphinx documentation FAQ at https://www.sphinx-doc.org/en/master/faq.html says:

> How do I
> … create HTML slides from Sphinx documents?
> See the “Hieroglyph” package at https://github.com/nyergler/hieroglyph.

But this project apparently doesn't work with sphinx > 1.8 (see, for example https://github.com/nyergler/hieroglyph/issues/155). Which is unfortunate, because it sounds cool.

The FAQ page source appears to be: https://github.com/sphinx-doc/sphinx/blob/59661f04722d81a4b7504650458d5c20cfc01d2d/doc/faq.rst

I guess it should probably be removed from the FAQ.

**Comment by tk0miya** [comment]
Let's wait the update of hieroglyph for a while.

**Comment by cheshirekow** [comment]
Note that it hasn't seen a commit since september of 2017... I guess sphinx 2.0 is pretty new but even sphinx 1.8 has open issues that haven't been fixed.

**Comment by tk0miya** [comment]
I just post https://github.com/nyergler/hieroglyph/pull/156 to fix the extension. I think it will resolve this situation soon.

**Comment by cheshirekow** [comment]
Awesome! Thanks for doing that.

**Comment by tk0miya** [comment]
It seems another fix is needed for hieroglyph. So I'll remove the mention to hieroglyph from our docs temporarily.

**Comment by tk0miya** [comment]
Removed by #6392. Closing. I'll recover it after hieroglyph supports latest Sphinx release.

**Comment by cheshirekow** [comment]
FYI: I took a stab at building off of what you did and I think I got the quickstart to work. [here][1] is the diff against the upstream, and [here][2] is the diff against your branch.

[1]: https://github.com/nyergler/hieroglyph/compare/master...cheshirekow:cheshirekow/sphinx20
[2]: https://github.com/tk0miya/hieroglyph/compare/155_sphinx20...cheshirekow:cheshirekow/sphinx20

**Comment by tk0miya** [comment]
It seems hieroglyph tries to keep compatibilities with old Sphinx releases. And your patch breaks them. I don't mind to drop supports (because Sphinx project does not support them!), but you need to ask the owner of the extension to do that.
