### ISSUE TITLE
astroid.exceptions.AstroidSyntaxError: Parsing Python code failed: invalid syntax (<unknown>, line 375)

### ISSUE THREAD

**Issue by JoshSullivan11** [sphinx-doc/sphinx#6349]
**Describe the bug**
sphinx "make clean html" fails to recursively search folders to generate autodoc.

**To Reproduce**
```
In the root directory of my project
$ make clean html
```

**Expected behavior**
The 'make clean html' command should recursively parse through all sub-directories under root directory of my project and generate autodoc (doctree, index.rst and .hml) files for all .py files in each folder. The picture shows what my index page looked like before I upgraded to python 3.5.

![image](https://user-images.githubusercontent.com/46171231/57494217-0f056100-727d-11e9-9b46-971980406a39.png)

**Your project**
Link to your sphinx project, or attach zipped small project sample.

**Environment info**
- OS: Linux Ubuntu 16.04
- Python version: 3.5.2
- Sphinx version: 2.0.1
- Sphinx extensions:  sphinx.ext.autodoc

**Additional context**

[conf.txt](https://github.com/sphinx-doc/sphinx/files/3164342/conf.txt)
[terminal_output (1).txt](https://github.com/sphinx-doc/sphinx/files/3164420/terminal_output.1.txt)
[builderpy.txt](https://github.com/sphinx-doc/sphinx/files/3164158/builderpy.txt)
[sphinx-err-nm7k_wyi.log](https://github.com/sphinx-doc/sphinx/files/3164358/sphinx-err-nm7k_wyi.log)

- [e.g. URL or Ticket]

**Comment by tk0miya** [comment]
Thank you for reporting. But this error comes from that the astroid extension does not support python3.
```
Traceback (most recent call last):
  File "/home/joshsullivan/.py_virtualenvs/verb_py3/lib/python3.5/site-packages/astroid/builder.py", line 166, in _data_build
    node = _parse(data + "\n")
  File "/home/joshsullivan/.py_virtualenvs/verb_py3/lib/python3.5/site-packages/astroid/_ast.py", line 31, in _parse
    return parse_func(string)
  File "/home/joshsullivan/.py_virtualenvs/verb_py3/lib/python3.5/site-packages/typed_ast/ast3.py", line 62, in parse
    return _ast3._parse(source, filename, mode, feature_version)
  File "<unknown>", line 375
    except IOError, err:
                  ^
SyntaxError: invalid syntax
```

So please downgrade your python or send a request to support python3 to astroid project.

Thanks,

**Comment by JoshSullivan11** [comment]
Astroid definitely supports python 3. In fact that is the only version of python it does support and that package is working just fine with other parts of my code base. That is what leads me to believe there may be a bug with Sphinx. Is there there a way for me to disable that package for Sphinx, or is Sphinx dependent on that package?

**Comment by tk0miya** [comment]
I don't know what astroid is doing. So I can't help you in this case.
It seems astroid builder tries to parse "<unknown>" file, and it is written in py2 style. If astroid supports py3, this unknown file might be related with the error.
```
  File "<unknown>", line 375
    except IOError, err:
```

In this case, the error is raised inside astroid builder. So nothing to do from sphinx side. Could you ask this to them please?
