### ISSUE TITLE
hyperlink target "licenses-mit" is not referenced is wrong

### ISSUE THREAD

**Issue by dvorapa** [sphinx-doc/sphinx#6351]
**Describe the bug**
When building HTML of our project, Sphinx outputs this specific warning. But the warning is wrong as the anchor is actually referenced, just in other files, not the current one. The whole warning looks like:

    /src/docs/licenses.rst:8: Hyperlink target "licenses-mit" is not referenced.

**To Reproduce**
Build HTML of Pywikibot (last build by us: https://integration.wikimedia.org/ci/job/pywikibot-core-tox-doc-docker/6505/console) or try to simulate the situation
```
$ git clone https://github.com/wikimedia/pywikibot/
$ cd pywikibot
$ pip install -r requirements.txt
$ cd docs
$ make html
```
open https://doc.wikimedia.org/pywikibot/master/ and click the MIT license link in the third paragraph

**Expected behavior**
The link works and the anchor is therefore referenced, so the warning is thrown for no reason. The check should be improved.

**Your project**
Site: https://www.mediawiki.org/wiki/Manual:Pywikibot
Doc: https://doc.wikimedia.org/pywikibot/master/
Repo: https://phabricator.wikimedia.org/diffusion/PWBC/

**Environment info**
- OS: Debian Jessie
- Python version: 3.4
- Sphinx version: 1.8.5
- Sphinx extensions: Autodoc, Napoleon, Epytext

**Additional context**
- https://phabricator.wikimedia.org/T187009

**Comment by tk0miya** [comment]
The checker is not working well for Sphinx. It is only available for docutils (base library of Sphinx). So it should be disabled.

**Comment by dvorapa** [comment]
Thank you!
