### ISSUE TITLE
Faulty Import Mechanism causes MemoryError

### ISSUE THREAD

**Issue by VasLem** [sphinx-doc/sphinx#6357]
In my work project, there are more than one files that import a specific library, which is already installed as site-package, which loads a big file upon initialization. During `make html`, I would expect the library to be loaded once in RAM and then be used by the subpackages. This does not happen. Instead, the library is loaded multiple times, filling up memory and causing MemoryError at the end. Are there any plans to address this faulty behavior? Unfortunately I cannot post the project as the distribution is prohibited by the terms of usage. If the issue is not understood, I will try to create a toy example of the situation.

**Comment by tk0miya** [comment]
How did you check "the library is loaded multiple times"? AFAIK, sphinx only loads the library once. It would be nice if you can create an example to reproduce the error.

**Comment by tk0miya** [comment]
I'm closing this now because of no response.
Please feel free to reopen if you're still in problem.
Thanks,
