### ISSUE TITLE
Sphinx v2.0.1 fails on Windows with python 3.6

### ISSUE THREAD

**Issue by epogrebnyak** [sphinx-doc/sphinx#6360]
**Describe the bug**

```sphinx-build -b html docs site -c .``` fails with dependency error(s) on Windows. 

**To Reproduce**

```
λ sphinx-build -b html docs site -c .
Running Sphinx v2.0.1

Extension error:
Could not import extension sphinx.builders.linkcheck (exception: No module named 'chardet.enums')
```
When I downgrade enums to ```pip install chardet==3.0.2``` I get following error:

```
Extension error:
Could not import extension sphinx.builders.linkcheck (exception: No module named 'urllib3.exceptions')
```
When I downgrade ```pip install urllib3==1.21.1``` I get following error:

```
Running Sphinx v2.0.1

Extension error:
Could not import extension sphinx.builders.linkcheck (exception: cannot import name 'where')
```

**Expected behavior**
Expecting sphinx to build documentation. 

**Your project**

<https://github.com/epogrebnyak/econometrics-navigator>

**Environment info**
- Win 10, 64
- Python 3.6.0 :: Anaconda 4.3.1 (64-bit)
- Running Sphinx v2.0.1
- Sphinx extensions:  ['sphinx.ext.mathjax',
    'sphinx.ext.githubpages',
    'm2r']

**Additional context**

- I do have non-latin chars in my paths, if that matters

**Comment by epogrebnyak** [comment]
Downgrading to version ```1.4.6``` allows running my build. Maybe the problem is caused by `m2r`?

**Comment by tk0miya** [comment]
Both chardet and urllib3 are dependency of `requests` package. `certifi.where` is also dependency of it. I guess your environment is broken. Could you reinstall `requests` package please?
Thanks,

**Comment by epogrebnyak** [comment]
> 
> 
> Both chardet and urllib3 are dependency of `requests` package. `certifi.where` is also dependency of it. I guess your environment is broken. Could you reinstall `requests` package please?
> Thanks,

So very much true! I uninstalled `requests` and its every other dependency, then installed `requests` back, with dependencies, and Sphinx v2.0.1 working now!

Also updated `m2r` package.

Many thanks for help!
