### ISSUE TITLE
error

### ISSUE THREAD

**Issue by xBlackSwan** [sphinx-doc/sphinx#6362]
**Describe the bug**

**To Reproduce**
```
<Paste your command-line here which cause the problem>

$ git clone https://github.com/.../some_project
$ cd some_project
$ pip install -r requirements.txt
$ cd docs
$ make html SPHINXOPTS="-D language=de"
$ # open _build/html/index and see bla bla
```

**Expected behavior**

**Your project**
Link to your sphinx project, or attach zipped small project sample.

**Screenshots**

**Environment info**
- OS: [e.g. Unix/Linux/Mac/Win/other with version]
- Python version: [e.g. 3.7.1]
- Sphinx version: [e.g. 1.8.2]
- Sphinx extensions:  [e.g. sphinx.ext.autodoc, recommonmark]
- Extra tools: [e.g. Browser, tex or something else]

**Additional context**

- [e.g. URL or Ticket]

[sphinx-err-fqga6i6g.log](https://github.com/sphinx-doc/sphinx/files/3173166/sphinx-err-fqga6i6g.log)

**Comment by tk0miya** [comment]
```
  File "c:\python37\lib\site-packages\zzzeeksphinx\__init__.py", line 5, in setup
    from . import autodoc_mods, dialect_info, mako, \
  File "c:\python37\lib\site-packages\zzzeeksphinx\dialect_info.py", line 2, in <module>
    from sphinx.util.compat import Directive
ImportError: cannot import name 'Directive' from 'sphinx.util.compat' (c:\python37\lib\site-packages\sphinx\util\compat.py)
```

It seems `zzzeeksphinx\dialect_info.py` is using removed module. It was deprecated in 1.6 and removed since 1.7.
The successor of the module is `docutils.parsers.rst.Directive` class. Please report the error to zzzeeksphinx project.

Thanks,
