### ISSUE TITLE
Allow suppressing warnings for autosectionlabel

### ISSUE THREAD

**Issue by gibfahn** [sphinx-doc/sphinx#6371]
Raising an issue as per the suggestion in https://github.com/sphinx-doc/sphinx/pull/2346#issuecomment-261267441 , adding a `type` and `subtype` to this warning would be helpful:

https://github.com/sphinx-doc/sphinx/blob/ba86f4ea7895ff59368a602d43bb85fc4d453546/sphinx/ext/autosectionlabel.py#L56-L58

The reason I need this is that I would like to autogenerate section labels to resolve https://github.com/rtfd/recommonmark/issues/155.

This works well but some files have duplicate headings, which I can resolve by manually specifying a section. So to run with `-W` I need to be able to ignore the warnings.

**Comment by tk0miya** [comment]
Closing now. Thanks,
