### ISSUE TITLE
Broken redirect on sphinx-doc.org

### ISSUE THREAD

**Issue by stephenfin** [sphinx-doc/sphinx#6372]
http://sphinx-doc.org/domains.html should redirect to http://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html or similar. It instead redirects to the home page. Could we get a redirect for this?

**Comment by stephenfin** [comment]
Meanwhile http://www.sphinx-doc.org/en/1.5.1/domains.html actually does redirect to http://www.sphinx-doc.org/en/1.5.1/usage/restructuredtext/domains.html, but that didn't exist in 1.5.x so it's broken.

**Comment by tk0miya** [comment]
Who's using these URLs? If my memory is correct, they were not used so far. It means no links are broken. Especially, former one is out of control for us. To fix it, we might go out from readthedocs...

**Comment by stephenfin** [comment]
I found them via Google when searching for the 'default-domain' directive.

**Comment by tk0miya** [comment]
I feel search index of google has been broken. There're nothing to do from our side. The only thing we can do is sending a request to Google to remove them from their index.

**Comment by tk0miya** [comment]
Closing.
