### ISSUE TITLE
Makefile:20: recipe for target 'html' failed

### ISSUE THREAD

**Issue by holzerseb** [sphinx-doc/sphinx#6377]
`Exception occurred:
  File "conf.py", line 9, in <module>
ImportError: No module named 'pbr'`

Traceback attached

[sphinx-err-mt2uro7l.log](https://github.com/sphinx-doc/sphinx/files/3188410/sphinx-err-mt2uro7l.log)

**Comment by tk0miya** [comment]
It seems the error was raised inside your conf.py. Please check your environment. It says `pbr` is not installed.
