### ISSUE TITLE
Module index (py-modindex.html) has duplicate titles, one of which is a hyperlink and the other is openable/closable

### ISSUE THREAD

**Issue by Mahi** [sphinx-doc/sphinx#6379]
After running `sphinx-apidoc` on my project, then using the default `make html` created by `sphinx-quickstart`, I ended up with a Module Index that had duplicate titles for some packages. One of the titles is a clickable hyperlink, and the other one is an "openable" directory. I believe these two titles should be merged into one clickable hyperlink that's also an openable directory.

There's an easy way to show the bug, it happens in Sphinx's official documentations too: https://www.sphinx-doc.org/en/master/py-modindex.html

At the time of this bug report, this is what the `sphinx.builders` section looks like:

![sphinx.builders](https://user-images.githubusercontent.com/11020883/57912316-b2b0cb80-7892-11e9-8be9-106989103b84.png)

The same also happens with the `sphinx.environment`. Clicking the `[-]` icon next to the hyperlink title doesn't do anything (it just turns into a `[+]` icon), while the icon next to the non-hyperlink one works fine.

**Comment by Mahi** [comment]
Issue happens on sphinx 2.0.1, Windows 10, Google Chrome 74

**Comment by tk0miya** [comment]
Fixed by #6383.
Thank you for reporting!
