### ISSUE TITLE
Add Deployment Documentation

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#638]
Hi there,

I think it'd be nice to include a 'deploying sphinx' documentation section. This could include sample configurations for popular web servers (apache, nginx, lighttpd, etc.) to serve Sphinx documentation nicely.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/638
- Originally reported by: Anonymous
- Originally created at: 2011-02-15T18:58:38.279

**Comment by shimizukawa** [comment]
_From Éric Araujo on 2011-02-17 11:46:33+00:00_

Given that Sphinx doc is static HTML, CSS and JavaScript, I’d guess that the basic docs you’ve already read for your Web server of choice apply for Sphinx too.  Do you agree?

**Comment by shimizukawa** [comment]
_From Hoat Le on 2013-08-18 19:05:44+00:00_

Hello, we created sphinx-deployment to handle automatic sphinx deployment, please take a look at it, it's very easy to use https://github.com/teracy-official/sphinx-deployment

**Comment by AA-Turner** [comment]
https://www.sphinx-doc.org/en/master/tutorial/deploying.html
