### ISSUE TITLE
Latest WebSupport doesn't work with latest Sphinx

### ISSUE THREAD

**Issue by liborjelinek** [sphinx-doc/sphinx#6380]
**Describe the bug**
Latest WebSupport (1.1.0) crashes with latest Sphinx (2.0.1) with error `sphinx.errors.SphinxError: Builder name websupport not registered or available through entry point`.

Latest Sphinx that works with WebSupport 1.1.0 is Sphinx 1.8.5.

**To Reproduce**
```
$ git clone https://gitlab.com/bircow/sphinxwebsupport-builder-name-not-registered
$ cd sphinxwebsupport-builder-name-not-registered
$ pip3 install -r requirements.txt
$ python3 websupport_crash.py
```

**Your project**
Repo to demonstrate a bug https://gitlab.com/bircow/sphinxwebsupport-builder-name-not-registered

**Environment info**
- OS: Ubuntu 18.04
- Python version: 3.6
- Sphinx version: 2.0.1

**Comment by tk0miya** [comment]
Fixed by https://github.com/sphinx-doc/sphinxcontrib-websupport/pull/29. And it is released as v1.1.2.
Thanks,
