### ISSUE TITLE
Pressing back in browser does not reset certain page elements

### ISSUE THREAD

**Issue by billtubbs** [sphinx-doc/sphinx#6382]
**Describe the bug**
I noticed this issue on the following Python documentation page:

https://docs.python.org/3/library/dataclasses.html

I was pretty sure this feature was introduced in Python 3.7 but as a perhaps unusual way of checking that I decided to try changing the documentation version in the drop-down at the top left of the page and then refreshing the page (to confirm that there is no data classes page in the documentation for 3.6).

This is in fact true as it displays the home-page for Python 3.6 documentation instead:

https://docs.python.org/3.6/

Having confirmed what I thought I then pressed the back button in my browser (Safari Version 12.1 on Mac OS X 10.14.4).

While it did then return me to the dataclasses documentation page, it left the current Python version element showing 3.6.  This is easily resolved by refreshing the page but I thought I would point it out.

**To Reproduce**

1. Go to this page in a browser: https://docs.python.org/3/library/dataclasses.html
2. Change the Python version from 3.7.3 to 3.6 in the drop-down menu at top left (browser automatically changes the page to https://docs.python.org/3.6/)
3. Press the back button in the browser (browser returns to https://docs.python.org/3/library/dataclasses.html).

**Expected behavior**

After step 3 above, I expect the page https://docs.python.org/3/library/dataclasses.html to show the Python version as 3.7.3 not 3.6.

**Your project**
https://docs.python.org

**Screenshots**
- Click [here](https://ibb.co/KxXCtx6) for screenshot of the issue

**Environment info**
- OS: Mac OS X 10.14.4
- Python version: N/A
- Sphinx version: not sure

**Additional context**

- [e.g. URL or Ticket]

**Comment by tk0miya** [comment]
The version selector is a custom component of python.org. It is not provided by sphinx. So please report this to python project.
Thanks,

**Comment by billtubbs** [comment]
Ah.  Okay thanks.
