### ISSUE TITLE
Link to "Write the docs" on the Introduction page doesn't work

### ISSUE THREAD

**Issue by ericonr** [sphinx-doc/sphinx#6384]
On the [introduction page](http://www.sphinx-doc.org/en/latest/intro.html) of both the latest and master sphinx docs, the link to the recommended reading about documentation, "Write the docs" is not working. Currently, the page it links to ( https://write-the-docs.readthedocs.io/ ) is just showing some text about "Time".

It was supposed to link to a doc talking about the importance of documentation, which, after some quick searching, led me to believe it should be this one: http://www.writethedocs.org/guide/writing/beginners-guide-to-docs/.

If someone can confirm that is indeed the correct link, I can make a pull request with the fix (if it is necessary).

**Comment by tk0miya** [comment]
Thank you reporting. Fixed.
