### ISSUE TITLE
Path to built docs is wrong when make is executed from a script which changes directory

### ISSUE THREAD

**Issue by jugmac00** [sphinx-doc/sphinx#6389]
**Describe the bug**
After a successful build, the relative path is printed eg. `The HTML pages are in _build/html.` This is only true when make gets directly executed from within the docs directory.

Instead of changing in the directory and manually call `make html` we auto generate a small helper script to do that with following content via buildout.

This one is generated on my linux box:
```
#!/bin/sh
cd /home/jugmac00/Projects/Zope/docs
make html
```

**To Reproduce**
Just create a similar bash script like above.

**Expected behavior**
Give the correct path to the built docs.

**Actual behavior**
```
The HTML pages are in _build/html.
```

Actually, the docs are in docs/_build/html.

**Wished behavior**
Instead of printing the relative path, I'd like to see the absolute path printed.

**Your project**
Bug was reported against the Zope project, but closed there, as Zope only applies this small bash wrapper, and the output comes from Sphinx.
https://github.com/zopefoundation/Zope/issues/602

**Environment info**
- OS: Ubuntu 18.04
- Python version: 3.6.7
- Sphinx version: 1.8.4

**Additional Info**
The relevant part in the source is .. amongst others:
https://github.com/sphinx-doc/sphinx/blob/f63abac2cad2664a8af816017f0f997bae510d14/sphinx/builders/html.py#L182

`outdir` should be an absolute path, not a relative one.

**Comment by tk0miya** [comment]
`sphinx-build` command already shows relative directory from current directory. But the wrapper script conceals the current directory. I think there are nothing to do for this issue from sphinx side. It should be better to update the wrapper script of django project.

Note: -0 to show absolute directory. It is a bit ugly to me.

**Comment by jugmac00** [comment]
@tk0miya Thanks for your feedback.

PS haha, I searched the documentation for this mysterious -0 argument, which shows the absolute URL, but just now I reread your answer... haha :-)

**Comment by tk0miya** [comment]
I'm closing this now. Thank you for your proposal!
