### ISSUE TITLE
:exclude-members: does not prevent missing attribute warning

### ISSUE THREAD

**Issue by simberaj** [sphinx-doc/sphinx#6391]
Including a name in the `:exclude-members:` directive does not prevent the warning about a missing attribute mentioned in `__all__`.

In my case, I have some documentable objects in `__init__.py`. The package also has a submodule `sub` that I need to include in `__all__` but I do not want to import the submodule in `__init__.py`. In this setup, Sphinx complains about a missing module member from `__all__` even when I specify I do not want to document that member using the `:exclude-members:` directive of the automodule command for the main package file.

**To Reproduce**
Run the attached MWE with `make html`.

**Expected behavior**
The warning should not appear; `ModuleDocumenter.get_object_members()` should be informed about names it should not search for.

**Your project**
[MWE](https://github.com/sphinx-doc/sphinx/files/3208321/sphex.zip)

**Screenshots**
![MWE run](https://user-images.githubusercontent.com/13705363/58190956-e68a5780-7cbd-11e9-9f64-d88973d99405.png)

**Environment info**
- OS: Win10
- Python version: 3.7.3
- Sphinx version: 2.0.1
- Sphinx extensions:  sphinx.ext.autodoc

**Comment by tk0miya** [comment]
If my understanding is correct, the `package.__all__` is invalid because `submod` is not a member of `package`.
```
>>> import package
>>> package.__all__
['submod', 'rootfunc']
>>> package.submod
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'package' has no attribute 'submod'
```

**Comment by simberaj** [comment]
Understood, closing the issue.
