### ISSUE TITLE
Proper design for the sphinxcontrib-bibtex extension

### ISSUE THREAD

**Issue by cpitclaudel** [sphinx-doc/sphinx#6393]
**Is your feature request related to a problem? Please describe.**

The sphinxcontrib-bibtex extension has two long-running issues:

- It requires the file that references the bibtex bibliography to be processed last (so people usually call it `zbibliography`, or something similar)
- It doesn't support parallel processing

The cause of these issues is simple: `sphinxcontrib-bibtex` loads a subset of entries from a bibtex file (by default only the ones that are cited, but users can use a more complex custom filter), so it needs to know which entries are cited.  It registers itself as a `transform`, and if the document that contains the `.. bibliography` directive doesn't come last, the bibliography filter will remove too many entries (because it will think that they are not cited, even though they may be in other not-yet-processed documents).

I'm trying to fix these two issues, but I'm running into a Sphinx limitation.  As far as I can tell, there's no way to run transforms that process all documents at once (instead, each transform is run on each document, document by document).

**Describe the solution you'd like**

It could work to be able to register a global transform, which would be passed a list of doctrees and could modify them in place.  This would happen before other transforms are run.  The transform would load and filter bibtex files, after all references have been collected by the reader.

In general, I don't know of a way currently to register a transformation that needs to operate over all documents, taken together.  I'm not sure whether the suggestion above is the right way to tackle this issue, though.

**Describe alternatives you've considered**

I've tried splitting the BibTeX Sphinx transform into two phases:

1. Load all entries from the Bibtex file in a transform
2. Filter unused entries in a post-transform

But the problem with this approach is that that consistency check in `citation.py` kicks in and notices unreferenced citations before the post-transform (step 2) can filter them out.

Related: https://github.com/mcmtroffaes/sphinxcontrib-bibtex/issues/80

**Comment by tk0miya** [comment]
I think using both "Reading phase" and "Resolving Phase" is better for bibtex extension. In reading phase, Sphinx parses and transforms each document (sometime paralelly). And the result of the process are stores to doctrees, domains and environments. On the other hand, in resolving phase, Sphinx transforms the doctree again using domains and environments for individual output format.

>I've tried splitting the BibTeX Sphinx transform into two phases:
>
>1. Load all entries from the Bibtex file in a transform
>2. Filter unused entries in a post-transform

I think these bibtex's phases are similar to Sphinx's build phases. I think 1) overriding citation domain to suppress warning, 2) loading bibtex file on each directives and expand it to citation_definition nodes (they will be registered into custom citation domains automatically), and 3) filtering unused citation definitions on resolving phase.

I think sphinx already have two different phases. They allows to extensions to collect items from each document, and allow to modify them on latter phase. So you can do it with current mechanism, I believe.

**Comment by cpitclaudel** [comment]
Interesting, thanks a lot.  Overriding the citation domain was the missing piece. I'll update this issue when I'm done with the implementation.

Thanks for taking the time to respond :)

**Comment by eric-wieser** [comment]
@cpitclaudel: Were you able to get anywhere with this?

**Comment by cpitclaudel** [comment]
Not yet

**Comment by mcmtroffaes** [comment]
Note that both issues (unresolved citations, parallel build support) will be addressed with the next sphinxcontrib-bibtex release. I've opted for using an external file to store the citations outside the environment cache, so they persist between sphinx runs and all citations can be resolved. See

https://github.com/mcmtroffaes/sphinxcontrib-bibtex/pull/208
https://github.com/mcmtroffaes/sphinxcontrib-bibtex/pull/210

**Comment by cpitclaudel** [comment]
Thanks for the update!  :tada: :+1:  Out of curiosity, can you say more about why you need a separate file rather than Sphinx' own cache?

**Comment by mcmtroffaes** [comment]
That's an excellent question. To keep the implementation simple, I've always left formatting and resolving references from/to citation nodes to docutils/sphinx. Consequently, the list of citations per document must be known already in the 1st stage. There may be a different solution for this using the internal cache and by replicating some of the sphinx/docutils formatting at a later stage. However, after having tried various things, I've surrendered to the idea that it's simplest to store the citation information outside the regular cache so it is known at the start of the build which citations are used in which documents.

**Comment by tk0miya** [comment]
Sounds good :-)

**Comment by tk0miya** [comment]
@cpitclaudel  Can I close this issue?

**Comment by cpitclaudel** [comment]
> so it is known at the start of the build which citations are used in which documents.

Oh, so you mean that the bib file is loaded before processing the rest of the document?  That sounds fine.  Thanks a lot for clarifying.
