### ISSUE TITLE
Colons missing between parameter names and types in API docs 

### ISSUE THREAD

**Issue by Bultako** [sphinx-doc/sphinx#6400]
**Describe the bug**
The HTML API docs generated with Sphinx 2.0 do not display the colons separating parameter names and types.

**Your project**
You may find more detailed info about the issue and project (as well as screenshots) in https://github.com/gammapy/gammapy/issues/2164

**Environment info**
- OS: Mac
- Packages: https://gist.github.com/cdeil/d71faf30b6ecdbbd83bc8e91eea914be

**Comment by tk0miya** [comment]
Since 2.0, HTML5 writer becomes default writer of HTML. And it represents the separator of field-list using CSS. But rtd theme does not provides the style for field-list. Could you file this to their project please?
Thanks,
