### ISSUE TITLE
Exception TypeError: '<' not supported between instances of 'str' and 'NoneType' when using image file with .* extension

### ISSUE THREAD

**Issue by davbeek** [sphinx-doc/sphinx#6402]
**Describe the bug**
I get the following exception when I use an image with a star extension (.. image car.*), when there is a non proper/fitting file candidate for the image (I am generating html output, but I have supplied an car.pdf file. which is suitable for pdflatex, but not for html) and there is also an "image" file available for which a mime type is not known (in my case car.graphml):

Exception occurred:
  File "/usr/local/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 227, in post_process_images
    mimetypes = sorted(node_cand)
TypeError: '<' not supported between instances of 'str' and 'NoneType'

The reason is that python tries to sort a list of two items: one for the pdf file pointing to its mime type, and one for the file without mime type.

**To Reproduce**
$ make html

main file contains just one line:

.. image:: car.*

two files in directory:
- car.pdf
- car.graphml
[image_bug.zip](https://github.com/sphinx-doc/sphinx/files/3226397/image_bug.zip)

**Expected behavior**
I expect an error message to be generated that there is no proper candidate file for the image car.*

**Your project**
Link to your sphinx project, or attach zipped small project sample.

**Screenshots**

**Environment info**
- OS: MacOS Mojave
- Python version: 3.7.3
- Sphinx version: 1.8.5
- Sphinx extensions:  sphinx_rtd_theme
- Extra tools: -

To solve the bug, it was sufficient to remove the None entry in the list that caused the exception (the None entry being caused by the car.graphml file without Mime type)

[sphinx-err-2t7d66o2.log](https://github.com/sphinx-doc/sphinx/files/3226428/sphinx-err-2t7d66o2.log)

[image_bug.zip](https://github.com/sphinx-doc/sphinx/files/3226404/image_bug.zip)

**Comment by tk0miya** [comment]
Fixed by #6403.
Thank you for reporting.
