### ISSUE TITLE
Invalid links in "Developing a Hello world extension" documentation page

### ISSUE THREAD

**Issue by liborjelinek** [sphinx-doc/sphinx#6405]
Page http://www.sphinx-doc.org/en/master/development/tutorials/helloworld.html (file doc/development/tutorials/helloworld.rst) contains two invalid links:

Link 
![image](https://user-images.githubusercontent.com/383059/58490982-6ad15480-816e-11e9-9d8e-b7782c887652.png)
should point to http://docutils.sourceforge.net/docs/howto/rst-directives.html.

Link 
![image](https://user-images.githubusercontent.com/383059/58491036-889eb980-816e-11e9-9fe9-a0302d364835.png)
should point to http://docutils.sourceforge.net/docs/ref/doctree.html.

**Comment by tk0miya** [comment]
Fixed by #6420.
Thank you for reporting!
