### ISSUE TITLE
SystemError: <built-in function isinstance> returned NULL without setting an error

### ISSUE THREAD

**Issue by schotte** [sphinx-doc/sphinx#6409]
**Describe the bug**
I get the Error 
> Exception occurred:
>   File "/usr/lib/python3/dist-packages/sphinx/ext/autodoc.py", line 1408, in can_document_member
>     return isinstance(member, class_types)

SystemError: <built-in function isinstance> returned NULL without setting an error
When I execute the html build. The Error is coming from my module written in c++. 
I did add a Enum type to the module by adding the following lines in PyInit function:

```
    if (PyType_Ready(&ButtonState) < 0)
        return NULL;
    Py_INCREF(&ButtonState);
    PyModule_AddObject(m, "ButtonState", PyObject_CallObject((PyObject *) &ButtonState, nullptr));
```

Errorlog:
[sphinx-err-y9scpte2.log](https://github.com/sphinx-doc/sphinx/files/3231622/sphinx-err-y9scpte2.log)

The sphinx generation is done on the already build shared object files. 
When I import the module in python (I use python3.6) I can access the enum with modulename.ButtonState without getting a error. It will just print the content of the object.

**Environment info**
- OS: XUbuntu 18.04
- Python version: 3.6.7
- Sphinx version: 1.6.7
- Sphinx extensions:  sphinx.ext.autodoc

**Additional context**
I created the config with sphinx-quickstart and then adjusted to my needs (the path were my modules are)
I build with: make html

I hope we can find a solution to the problem. Thank you in advance
Schotte

**Comment by tk0miya** [comment]
It seems python interpreter raise an error on calling `isinstance()` to attribute of some object. I think it is not a special operation for python scripts. So I suspect this is a bug of your custom python module. The error was raised inside python itself. So it is hard to fix from sphinx side...
Could you check it please?

**Comment by tk0miya** [comment]
I'm closing this because this would not be a bug of Sphinx.
Please feel free to reopen if you're still in trouble.

Thanks,
