### ISSUE TITLE
sphinx-apidoc output missing blank lines between modules

### ISSUE THREAD

**Issue by bmerry** [sphinx-doc/sphinx#6440]
sphinx-apidoc produces invalid RST: it fails to output a blank line after each `automodule` block and before the next section header. This causes warnings when building the docs.

This seems to be a regression since 1.8.1. I haven't bisected it.

**To Reproduce**
Steps to reproduce the behavior: in an empty directory,
```sh
$ mkdir dummy doc
$ touch dummy/__init__.py dummy/mod1.py dummy/mod2.py
$ sphinx-apidoc -f -o doc dummy
```

Now `doc/dummy.rst` contains the following:
```
dummy package
=============

Submodules
----------

dummy.mod1 module
-----------------

.. automodule:: dummy.mod1
   :members:
   :undoc-members:
   :show-inheritance:
dummy.mod2 module
-----------------

.. automodule:: dummy.mod2
   :members:
   :undoc-members:
   :show-inheritance:


Module contents
---------------

.. automodule:: dummy
   :members:
   :undoc-members:
   :show-inheritance:
```

**Expected behavior**
There should be a blank line immediately above the header for `dummy.mod2.`

**Environment info**
- OS: Ubuntu 18.04
- Python version: 3.6.6
- Sphinx version: 2.1.0
- Sphinx extensions: sphinx.ext.autodoc

**Comment by dangunter** [comment]
I have also seen this issue. Since we check that the docs build without warnings, it is breaking our builds and we had to pin Sphinx to an older version.

**Comment by stephenfin** [comment]
I've tested this and it's not an issue with 2.0.0 but is introduced with 2.1.0.
