### ISSUE TITLE
Note prevents a section to be moved to the next page

### ISSUE THREAD

**Issue by josuegomes** [sphinx-doc/sphinx#6442]
If the first element in a section is a note and the section is near the end of the page the section title is not moved to the next page.
If the first element is a normal paragraph the section is moved to the next page.

See screenshots to better understand the problem.

Note is the first element:

![note-1st](https://user-images.githubusercontent.com/2146286/58874651-be2c3100-869f-11e9-88c0-af4bbea3b02b.png)

Normal paragraph is the first element:

![par-1st](https://user-images.githubusercontent.com/2146286/58874690-d8fea580-869f-11e9-81c7-3794bcfe2ce9.png)

**Environment info**
- OS: Ubuntu 18.04
- Python version: 3.6.7
- Sphinx version: 2.0.1
- Latex

**Comment by tk0miya** [comment]
@jfbu #6443 was merged. Can I merge this?

**Comment by jfbu** [comment]
@tk0miya oh yes. Sorry I did not close (one has to wait until 2.1.1 is merged into master for it to happen automatically). Closing now!

@josuegomes Thanks for reporting!

**Comment by josuegomes** [comment]
>@josuegomes <https://github.com/josuegomes> Thanks for reporting!

You're welcome.



<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
