### ISSUE TITLE
Autodocumented module constants emit warnings

### ISSUE THREAD

**Issue by cmurphy** [sphinx-doc/sphinx#6447]
**Describe the bug**
Since https://github.com/sphinx-doc/sphinx/pull/6423 the OpenStack keystone autodoc build emits warnings, which we treat as failures in our CI. The problem is that we import external modules as top-level module constants, e.g.:

https://opendev.org/openstack/keystone/src/commit/3d2b293d7edfb0bd4bdec9b33abc63d1308e10bd/keystone/common/sql/core.py#L54-L71
https://opendev.org/openstack/keystone/src/branch/master/keystone/oauth1/core.py#L32-L39

which now are being autodoc'd, and some of these modules have issues such as requiring another sphinx extension that we don't use, syntax errors, or references to anchors that aren't part of the docstring. Example CI failure due to sqlalchemy's dependency on sphinx-paramlinks:

http://logs.openstack.org/93/660193/1/gate/openstack-tox-docs/93089c7/job-output.txt.gz#_2019-06-04_14_49_26_215401

With that resolved, we still see issues with other libraries that are hard to fix from our end:

```
Warning, treated as error:
/home/colleen/projects/keystone/.tox/docs/lib/python3.7/site-packages/oauthlib/oauth1/rfc5849/request_validator.py:docstring of keystone.oauth1.core.RequestValidator.save_verifier:4:Field list ends without a blank line; unexpected unindent.
```

**To Reproduce**

```
$ git clone https://opendev.org/openstack/keystone
$ cd keystone
$ tox -edocs
```

**Expected behavior**
Ideally, the docstrings from external modules could be automatically ignored, or there could be some way to ignore the module import on a case by case basis.

**Your project**
https://opendev.org/openstack/keystone

**Environment info**
- OS: Linux
- Python version: 3.6, 3.7
- Sphinx version: 2.1.0
- Sphinx extensions:  
```
extensions = ['sphinx.ext.coverage',
              'sphinx.ext.viewcode',
              'oslo_config.sphinxconfiggen',
              'oslo_config.sphinxext',
              'oslo_policy.sphinxpolicygen',
              'openstackdocstheme',
              'oslo_policy.sphinxext',
              'sphinxcontrib.apidoc',
              'sphinxcontrib.seqdiag',
              'sphinx_feature_classification.support_matrix',
              ]
```

**Comment by stephenfin** [comment]
It's perhaps not a long-term answer but you could try mocking those modules using the [`autodoc_mock_imports` setting](http://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_mock_imports)?

**Comment by tk0miya** [comment]
OMG! #6423 tells us that real world is complex...

At present, Sphinx only classifies python objects to "imported" or not. So we can only choose document all imported-objects or nothing. But, in real world, we've used many 3rd party libraries. And it sometimes contains invalid, broken or customized docstrings like this case. And it can break document builds easily.

Even before #6423, 3rd party libraries can break document easily. For example, broken docstrings can easily spreads with inheritance.
```
from some.framework import BaseClass

class Derived(BaseClass):
    pass
```
If docstring of some method in `BaseClass` contains the error, it will be inherited into `Derived` class like virus.

To avoid this, we need to improve autodoc much more. We need to classify objects and docstrings to 1st or 3rd party's. And 3rd party's should be restricted (if needed)...

**Comment by cmurphy** [comment]
@stephenfin thanks for the suggestion, unfortunately it seems like using that setting mucks with the import logic in a strange way that still leaves the build in a broken state :( :

```
autodoc_mock_imports = ["sqlalchemy", "alembic", "oslo_db"]
```

```
Warning, treated as error:
autodoc: failed to import module 'sql' from module 'keystone.identity.backends'; the following exception was raised:
Traceback (most recent call last):
  File "/home/colleen/projects/keystone/.tox/docs/lib/python3.7/site-packages/sphinx/ext/autodoc/importer.py", line 36, in import_module
    __import__(modname)
  File "/home/colleen/projects/keystone/keystone/identity/backends/sql.py", line 29, in <module>
    from keystone.identity.backends import sql_model as model
  File "/home/colleen/projects/keystone/keystone/identity/backends/sql_model.py", line 32, in <module>
    class User(sql.ModelBase, sql.ModelDictMixinWithExtras):
  File "/home/colleen/projects/keystone/keystone/identity/backends/sql_model.py", line 83, in User
    @name.setter
AttributeError: 'function' object has no attribute 'setter'
```

@tk0miya given the complex nature of the problem, would you consider reverting #6423 until a more well-rounded solution is in place?

**Comment by cmurphy** [comment]
[**@stephenfin**](https://github.com/stephenfin) commented on [Jun 5, 2019, 1:52 AM PDT](https://github.com/sphinx-doc/sphinx/issues/6447#issuecomment-498997640 "2019-06-05T08:52:48Z - Replied by Github Reply Comments"):
> It's perhaps not a long-term answer but you could try mocking those modules using the [`autodoc_mock_imports` setting](http://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_mock_imports)?

While this didn't quite work, it led me to another workaround that seems to work in our case: https://review.opendev.org/663373 so thanks for the hint.

**Comment by cmurphy** [comment]
[**@cmurphy**](https://github.com/cmurphy) commented on [Jun 6, 2019, 9:59 AM PDT](https://github.com/sphinx-doc/sphinx/issues/6447#issuecomment-499580861 "2019-06-06T16:59:03Z - Replied by Github Reply Comments"):

> @tk0miya given the complex nature of the problem, would you consider reverting #6423 until a more well-rounded solution is in place?

Or alternatively, maybe a toggle could be added to turn this behavior on and off? Even with being able to work around the broken build, we now have a ton of constants autodoc'd that we didn't expect and don't really need to have, it would have been nice to be able to opt into the behavior instead of having to create a blacklist to opt out.

**Comment by tk0miya** [comment]
@cmurphy I'm wondering reverting or adding a new option now. I understand generating document for global variables is bother even if `:undoc-members:` given. In https://github.com/sphinx-doc/sphinx/issues/6451#issuecomment-499656503, I heard some examples about loggers, blueprints and apps.
Please wait a moment. I will update Sphinx soon with "not" generating global variables by default.

**Comment by tk0miya** [comment]
Finally, I decided to revert #6423 (refs: #6471). So I'm closing this now.
Thank you for reporting.

**Comment by cmurphy** [comment]
Thank you!
