### ISSUE TITLE
Support generic "admonitions"

### ISSUE THREAD

**Issue by mcallaway** [sphinx-doc/sphinx#6450]
**Is your feature request related to a problem? Please describe.**

RST supports "Generic Admonitions":  http://docutils.sourceforge.net/docs/ref/rst/directives.html#generic-admonition

When attempting to use them in confluencebuilder an exception occurs:

    Exception occurred:
      File "/opt/pyenv/.pyenv/versions/sphinx/lib/python3.7/site-    packages/sphinxcontrib/confluencebuilder/translator.py", line 132, in unknown_visit
    raise NotImplementedError('unknown node: ' + node.__class__.__name__)
    NotImplementedError: unknown node: admonition

**Describe the solution you'd like**

Support generic admonitions.

**Describe alternatives you've considered**

I've considered using specific admonitions, and this is ok, but would still prefer generic admonitions.

**Additional context**

**Comment by tk0miya** [comment]
As you said, this is caused from confluencebuilder does not support generic admonitions. I think this should be filed to their project.
Thanks,
