### ISSUE TITLE
v2.1.0 does render return types for google style docstrings correctly

### ISSUE THREAD

**Issue by TheFriendlyCoder** [sphinx-doc/sphinx#6455]
**Describe the bug**
After upgrading Sphinx from v2.0.1 to 2.1.0 return types for properties that use the Google style docstrings aren't parsed correctly.

**To Reproduce**

```
class MyClass:
   @property
    def my_prop(self):
        """bool: return some value"""
        return True
```

**Expected behavior**
The code snippet above should render HTML markup that looks something like this:

```
return some value
   Return Type:
     bool
```

actual output looks like:

```bool: return some value```

**Environment info**
- OS: Mac OS
- Python version: 3.7.3
- Sphinx version: 2.1.0

**Comment by tk0miya** [comment]
Fixed by #6457.
Thank you for reporting!
