### ISSUE TITLE
Stop using Makefile and promote building with sphinx-build only

### ISSUE THREAD

**Issue by astromatt** [sphinx-doc/sphinx#6456]
## Feature request / idea
* `Makefile` requires lots of additional dependencies
* This is particular a problem on Alpine Linux (docker container).
* Standalone `sphinx-build` works very well without any external dependency.
* Stop generating `Makefile` for new projects and move all `sphinx-build` arguments to `conf.py`.

**Describe the solution you'd like**
* Start promoting use of `sphinx-build -c conf.py`.
* If flag `-c <FILE>` is not specified, `sphinx-build` should look in current directory for conf file.
* All `sphinxopts`, `sourcedir` and `builddir` should be in `conf.py`.
* `sphinxopts` should be configuration variables not just simply "list of opts to pass to `sphinx-build`"
* This will also give opportunity to have multiple configuration in one project.

**Comment by tk0miya** [comment]
The same idea was posted to #5618. Could you post a comment to it please?
