### ISSUE TITLE
.. option:: doesn't support '.' separator for options

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#646]
In Drizzle (http://www.drizzle.org/ Sphinx docs at http://docs.drizzle.org/) we use options in the form --plugin.option=whatever.  Unfortunately trying to express this with ".. option::" results in a duplicate option error.

I believe this is because the regex used doesn't support the '.'.  Is is possible to add this support?

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/646
- Originally reported by: [LinuxJedi](https://bitbucket.org/LinuxJedi)
- Originally created at: 2011-02-24T17:04:08.344

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2011-09-22 12:15:29+00:00_

I'll have a look.

**Comment by shimizukawa** [comment]
_From Nick Veitch on 2012-10-11 10:23:58+00:00_

it seems it struggles with multiple separators too, for example:

.. option:: create-auth-token

.. option:: delete-auth-token

strips the first word from each and produces an identical reference

**Comment by tk0miya** [comment]
In my short investigation:

It seems the `option` directive expects the option names is alphanumeric. As a result, `--plugin.option=whatever` is recognized as following:
- option name: `plugin`
- option argument: `.option=whatever`
