### ISSUE TITLE
Can i use include file in Glossary?

### ISSUE THREAD

**Issue by rigilfanov** [sphinx-doc/sphinx#6476]
The documentation for the Glossary states:
> This directive must contain a reST definition-list-like markup with terms and definitions

As I understand, this markup is not supported?
```
.. glossary::
    :sorted:

    .. include:: terms/contributing.rst
    .. include:: terms/development.rst
    .. include:: terms/maintainer.rst
```

Why am I asking?

Glossary supports alphabetical order, which is convenient for internationalization.

But many terms and definitions may be appropriate to include in the text of other files.

I think `.. glossary::` and `.. include::` could complement each other well.

In addition, joint use two directives seems simpler and clearer than extending the syntax.

Thanks.

**Comment by tk0miya** [comment]
No you can't. The `glossary` directive only allows definition-like list as its content.

Note: As you saw, this is an issue list of Sphinx. So please move to forum for questions.
