### ISSUE TITLE
Add documentation on "meta" directive 

### ISSUE THREAD

**Issue by GeorgeBekh** [sphinx-doc/sphinx#6503]
**Is your feature request related to a problem? Please describe.**
There's no documentation on "meta" directive added in https://github.com/sphinx-doc/sphinx/pull/2516

**Describe the solution you'd like**
Official documentation describing "meta" directive

**Additional context**
Example usage:
```
.. meta::
   :description: The reStructuredText plaintext markup language
   :keywords: plaintext, markup language
```

It is the feature i was searching for and it was pretty difficult to find.

**Comment by tk0miya** [comment]
At present, our document does not describe standard reST directives. It only has hyperlinks to upstream document:
https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#directives

+1: for adding description of standard reST directives and roles.
