### ISSUE TITLE
Text differences in "continues on next page" between code blocks and tables in PDF

### ISSUE THREAD

**Issue by jessetan** [sphinx-doc/sphinx#6512]
If a code-block or table crosses a page boundary in a PDF, there is a piece of text that hints that it continues on the next page.
This text is different if this is a code block or a table.

Table uses [Continued on next page](https://github.com/sphinx-doc/sphinx/blob/f63abac2cad2664a8af816017f0f997bae510d14/sphinx/templates/latex/longtable.tex_t#L29). This starts with a capital `C`, all others use lowercase `c`. It also uses continue**d** while [code block](https://github.com/sphinx-doc/sphinx/blob/af2bb9f80d6a1ff6ce675928020c38c2fa285b3f/sphinx/templates/latex/sphinxmessages.sty_t#L9) uses continue**s**

There may be other similar lines that I did not spot. Would be good to move them all to sphinxmessages.sty_t.

Sphinx version: master (did not check when this was introduced)

**Comment by tk0miya** [comment]
I think present form is better for the label. #6513 will fix it. It does not contain to move it to sphinxmessages.sty. Is that really needed?

Note: to keep the message translated, I will fix this in next major release (3.0.0).

**Comment by jessetan** [comment]
Moving to sphinxmessages.sty is not required, but it makes it easier to inspect/change them all in one go. Maybe even use the same text for tables, code blocks and others.
I have no idea how complex that is to implement though

**Comment by tk0miya** [comment]
That's not difficult. But I think adding customizability also brings complexity. I'm okay to add it if somebody wants to customize these messages really.

**Comment by tk0miya** [comment]
This issue is closed unexpectedly by github. Reopened.

**Comment by jfbu** [comment]
For the record the ``Continued on next page" for tables had always been there, see [here at 1.0 release](https://github.com/sphinx-doc/sphinx/blob/690fc257e9a539a4c193ba8efe5587f7c102785c/sphinx/writers/latex.py#L647). This is probably the reason why it had not been modified so far.

As for ``continues on next page`` for code-blocks it was introduced I think at 1.6.3 (see  #3792). By the way if one examines that PR one sees a mismatch as the documentation says ``continued on next page``... in a  [latex code comment](https://github.com/sphinx-doc/sphinx/blob/ddeccfc2c747942646b24fd52a0d09757cc9308b/sphinx/texinputs/sphinx.sty#L752-L753) which was at odds with the [actual latex code](https://github.com/sphinx-doc/sphinx/blob/ddeccfc2c747942646b24fd52a0d09757cc9308b/sphinx/texinputs/sphinx.sty#L780). This bad code comment disappeared at 1.7 (#3872). (just had time for detective work tonight...)

**Comment by tk0miya** [comment]
I'm closing this now. Please let me know if you'd like to customize the message.
Thanks,
