### ISSUE TITLE
Apidoc doesn't pass the user_template_dir when it recurses

### ISSUE THREAD

**Issue by adriangaro** [sphinx-doc/sphinx#6517]
**Describe the bug**
Tried to replace module template for apidoc; which seems to have no effect, it works for package and toc template. To note is that --separate is passed as an argument.

**To Reproduce**
Create the template module.rst_t, then run sphinx-apidoc --separate -t=./_templates ...
In the generated rst files you can see that the template was not applied.

**Expected behavior**
Expected that the module template in separate mode was used, which was not.

**Your project**
I have attached only the docs folder since the issue can be observed in it, can't attach the source due to it being proprietary. An easy exemple to check will be the rst file app/app.cleanup, the generated module file doesn't respect the template(ie the module word is still appended after the module name).
[docs.zip](https://github.com/sphinx-doc/sphinx/files/3314963/docs.zip)

**Environment info**
- OS: Win 10
- Python version: 3.6.8
- Sphinx version: 3.0.0.dev20190621
- Sphinx extensions:  'sphinx.ext.apidoc', 'sphinx.ext.autodoc', 'sphinx.ext.coverage', 'sphinx_autodoc_typehints', 'sphinx.ext.inheritance_diagram', 'sphinx_paramlinks', 'sphinx.ext.autosummary', 'sphinxcontrib.httpdomain'

**Additional context**
I already have tried checking the files used by apidoc and I have seen that in sphinx.ext.apidoc, in the function create_package_file, on line 160, when it goes through the submodules, the user_template_dir parameter is not passed. if the parameter is added, the templates are used correctly.

**Comment by tk0miya** [comment]
@adriangaro Could you try #6519? You can try it with this installation: `pip install https://github.com/tk0miya/sphinx/archive/6517_passthrough_templatedir_to_separateoption.zip`.

**Comment by adriangaro** [comment]
I have tried it and it works, thanks!

**Comment by tk0miya** [comment]
Thank you for confirming. Merged now.
