### ISSUE TITLE
When trying to install sphinx wih pip or apt for Xapian Haystack, sphinx.main() can't be called.

### ISSUE THREAD

**Issue by memegauste** [sphinx-doc/sphinx#6524]
I use that repo: https://github.com/notanumber/xapian-haystack

`Couldn't import sphinx module and call sphinx.main() for Python3`

`import sphinx` seem to be working, calling `sphinx.main` not:

`AttributeError: module 'sphinx' has no attribute 'main'`

And seems that package is loaded from virtualenv correctly:
`>>> sphinx
<module 'sphinx' from '/home/patryk/workspace/.virtualenvs/muzeum/lib/python3.6/site-packages/sphinx/__init__.py'>`

Any ideas?

**Comment by tk0miya** [comment]
`sphinx.main()` was deprecated since 1.7 and removed in 2.0. Please call `sphinx.cmd.build:main()` instead. But it is not a public API. So I recommend you to use `sphinx-build` command.
Thanks,
