### ISSUE TITLE
If not possible, then feature request. Show class attributes as docs when returned

### ISSUE THREAD

**Issue by securisec** [sphinx-doc/sphinx#6546]
I will try my best to explain what I am looking to achieve. In the example code, we can see that there are two files `output.py` and `code.py`. The class `HandleOutput` is used as a returned object from the `CodeClass` class. 

### Objective
What I am hoping to achieve is two things 

- 1. Document the `HandleOutput` class in a way that the attributes are well defined. 
- **2.** Automatically document the inherited documentation from the `HandleOutput` class when it is being used as a returned object in the `CodeClass` class. See the comment in `CodeClass.checkme` method. My documentation style is numpy style in sphinx. 

At the moment, we can see in the screenshot that it is not showing all the available properties and methods of the `HandleOutput` class. Just shows a generic return. 

### Code
        from __future__ import annotations
        from typing import Any

        # output.py
        class HandleOutput(object):
            def __init__(self, data):
                """The init method
                
                Parameters
                ----------
                data : list
                    Array of data
                """
                self.data = data

            @property
            def count(self) -> int:
                """Count of items
                
                Returns
                -------
                int
                    len of array
                """
                return len(self.data)
            
            def first(self) -> Any:
                """Returns the first item from the array
                
                Returns
                -------
                Any
                    First item
                """
                return self.data[0]

        # code.py
        # from output import HandleOutput
        class CodeClass(object):
            def __init__(self, data):
                self.data = data

            def checkme(self) -> HandleOutput:
                """Lets run a method
                
                Returns
                -------
                HandleOutput
                    Automatically populate this area with the docs from the 
                    HandleOuput class
                """
                return HandleOutput(self.data)

        test = CodeClass(['a', 1, 'string', True])
        print(
            test.checkme()
        )

### Screenshot
[![SS from Vscode][1]][1]

  [1]: https://i.stack.imgur.com/6zsFZ.png

**Comment by tk0miya** [comment]
It seems the screenshot is not Sphinx's output. Is this really a request to Sphinx?

**Comment by securisec** [comment]
The screenshot is from VSCode, and i am using it as a reference. The question remains valid about how to document inherited documentation

**Comment by tk0miya** [comment]
Sorry, I can't understand what is your problem. If my understanding is correct, Sphinx can't document `print()` syntax. What do you expect to Sphinx?

If this is a question, please move to sphinx-users list.

**Comment by securisec** [comment]
> Sorry, I can't understand what is your problem. If my understanding is correct, Sphinx can't document `print()` syntax. What do you expect to Sphinx?
> 
> If this is a question, please move to sphinx-users list.

I am not sure if my post is clear or not. The question is not about documenting the print statement, but documenting the HelperOuput class and/or the CodeClass so that the documentation from the HelperOutput class is inherited by the CodeClass. Some of the methods in the CodeClass is using the HelperOutput as a return object, so I would like the documentation for the HelperOutput class to show in the checkme method of the CodeClass.

**Comment by tk0miya** [comment]
What "inherited" mean? Now, it will be rendered as a hyperlink to `HandleOutput` class in Sphinx. Is it shortage for you? Please, please let me know what you requested.

**Comment by securisec** [comment]
Is there an option to enable the hyperlink? because at the moment, when using `from __future__ import annotations`, there is no hyperlink. Consider this [live example](https://glorifiedgrep.readthedocs.io/en/latest/android/codeanalysis.html) where the returned obeject `GreppedOut` is a class. you can see the [code here](https://github.com/securisec/glorifiedgrep/blob/master/glorifiedgrep/android/modules/codeanalysis.py#L27) It would be a very useful feature if it was possible to automatically expand the class properties and attributes when the class is a returned object. 

At the moment, the output is: 
![image](https://user-images.githubusercontent.com/22226823/60759336-98bd7a80-9ff1-11e9-90da-6d587c97084b.png)
No hyperlink. 

So the request is how can i 
- enable the hyperlink (the GreppedOut class is documented)
- Expand the properties of the GreppedOut class in the method documentation that is returning it.

**Comment by tk0miya** [comment]
Hmm? This screenshot is taken by default settings:
![スクリーンショット 2019-07-07 14 40 59](https://user-images.githubusercontent.com/748828/60764461-46e62480-a0c5-11e9-9040-4ac6b59faeb7.png)

```
# conf.py
import os
import sys
sys.path.insert(0, os.path.abspath('.'))

extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.napoleon',
]
```
```
# index.rst
.. autoclass:: output.HandleOutput
   :members:

.. autoclass:: codes.CodeClass
   :members:
```

**Comment by tk0miya** [comment]
In `glorifiedgrep`'s case, you've specified the type of return value is object `: object`. Is this intended?
```
        Returns
        -------
        GreppedOut : object
            GreppedOut object
```

>Expand the properties of the GreppedOut class in the method documentation that is returning it.

Sorry, I can't imagine it. I guess it outputs the document of `GreppedOut` class for each method which returns an instance of the class. Is this right?

**Comment by securisec** [comment]
Ah. I get it. Thanks for the help! The hyperlinking does help a lot!
