### ISSUE TITLE
Escaped characters in error messages.

### ISSUE THREAD

**Issue by doerwalter** [sphinx-doc/sphinx#6549]
When I use the configuration option `needs_sphinx` and set the value to a Sphinx version I don't have installed, I get an error message (in german) that contains escaped characters, i.e. I get:

```
Sphinx version error:
Dieses Projekt ben\xf6tigt Version 3.1.0 oder sp\xe4ter und kann daher nicht gebaut werden.
make: *** [html] Error 2
```

I would have expected:

```
Sphinx version error:
Dieses Projekt benötigt Version 3.1.0 oder später und kann daher nicht gebaut werden.
make: *** [html] Error 2
```

My Sphinx version is 2.1.2, Python is

```
Python 3.7.3 (default, Apr 24 2019, 11:03:12)
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
```

and the environment variable `PYTHONIOENCODING` is set to `utf-8`.

**Comment by tk0miya** [comment]
Fixed by #6553. Thank you for reporting!
