### ISSUE TITLE
Autoclass interaction between content=both and inherit_doscstrings=True

### ISSUE THREAD

**Issue by CarlAndersson** [sphinx-doc/sphinx#6567]
**Describe the bug**
Documenting class in both the class docstring and the `__init__` docstring has some (to me) counter intuitive behavior with respect to missing `__init__` docstrings in subclasses.

Subclasses without any `__init__` method will be documented with both the subclass class-level docstring and the parent `__init__` docstring, i.e. the `__init__` docstring is "inherited" along with the actual `__init__` method.
Subclasses with an `__init__` without docstring will only be documented with the subclass class-level docstring, i.e. not "inheriting" the `__init__` docstring from the parent.

This is not the same behavior as the built in `help` function or ipython's `?` help.
Using `help(ChildA)` shows `__init__` as inherited from `Parent` with the parents docstring.
Using `help(ChildB)` shows `__init__` as defined in the class, nut still with the parent docstring. The `?` in ipython behaves the same.

**To Reproduce**
- Download the MWE in the zip-archive below.
- Unzip
 - Build using `sphinx-build . docs` from the unzipped folder.

**Expected behavior**
Both `ChildA` and `ChildB` have `The parent init docstring` in the compiled docs.

**Your project**
[MWE.zip](https://github.com/sphinx-doc/sphinx/files/3372975/MWE.zip)

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/20397548/60888865-f9e68780-a257-11e9-87c5-1b0dd4f5c7b7.png)
![ipython screenshot](https://user-images.githubusercontent.com/20397548/60889523-7fb70280-a259-11e9-9035-08bf275cd7f8.png)

**Environment info**
- OS: MacOS 10.12.6
- Python version: 3.7.1
- Sphinx version: 2.1.2
- Sphinx extensions:  sphinx.ext.autodoc

**Comment by tk0miya** [comment]
Thank you for reporting.
Fixed by #6571.
