### ISSUE TITLE
autosummary: missing imported members in auto-generated documentation located in a module docstring

### ISSUE THREAD

**Issue by ghost** [sphinx-doc/sphinx#6568]
**Describe the bug**
This bug only occurs when automatic documentation generation is enabled in `conf.py`:
```python
autosummary_generate = True
autosummary_imported_members = True
```
In a particular case when a `.. autosummary::` directive is located in a module docstring, the `imported_members` configuration is not propagated to submodule generation.

In consequence, the generated documentation is incomplete and doesn't contain the list of imported members (if it has been enabled).

**To Reproduce**
A mininal project could be:

`conf.py`:
```python
import os
import sys
sys.path.insert(0, os.path.abspath('.'))

extensions = ['sphinx.ext.autosummary']
autosummary_generate = True
autosummary_imported_members = True
```

`index.rst`:
```python
test-ext-autosummary-mock_imports
=================================

.. autosummary::
   :toctree: generated

   autosummary_dummy_package
```

`autosummary_dummy_package/__init__.py`:
```python
"""
.. autosummary::
    :toctree:

    submodule
"""
```

`autosummary_dummy_package/submodule/__init__.py`
```python
from .autosummary_dummy_submodule import BarSubmodule, foo_submodule
```

`autosummary_dummy_package/submodule/autosummary_dummy_submodule.py`
```python
class BarSubmodule:
    """BarSubmodule class"""
    pass


def foo_submodule():
    """foo_submodule function"""
    pass
```

```
$ make html
$ vi generated/autosummary_dummy_package.submodule.rst # see no members 
```

**Expected behavior**
Giving the previous example, file content with the current implementation should be:
```rst
autosummary\_dummy\_package.submodule
=====================================

.. automodule:: autosummary_dummy_package.submodule
```
But the following content should be produced:
```rst
autosummary\_dummy\_package.submodule
=====================================

.. automodule:: autosummary_dummy_package.submodule

   
   
   .. rubric:: Functions

   .. autosummary::
   
      foo_submodule
   
   

   
   
   .. rubric:: Classes

   .. autosummary::
   
      BarSubmodule
   
```

**Your project**
[test-ext-autosummary-imported_members.zip](https://github.com/sphinx-doc/sphinx/files/3374687/test-ext-autosummary-imported_members.zip)

**Environment info**
- OS: Linux, Fedora 30 64bits
- Python version: 3.7.3
- Sphinx version: 2.1.3
- Sphinx extensions:  sphinx.ext.autosummary

**Comment by tk0miya** [comment]
Fixed by #7098.
Thank you for reporting.
