### ISSUE TITLE
reversed option for toctree directive has no effect for latex output

### ISSUE THREAD

**Issue by skirpichev** [sphinx-doc/sphinx#6581]
The bug could be seen on the [Diofant](https://github.com/diofant/diofant/) pdf docs, e.g. [v0.10.0](https://github.com/diofant/diofant/releases/download/v0.10.0/diofant-docs-0.10.0.pdf), chapter seven (Release Notes).

The toctree directive in this chapter looks [like this](https://github.com/diofant/diofant/blob/master/docs/release/index.rst):
```
.. toctree::
   :glob:
   :maxdepth: 1
   :reversed:

   sympy
   notes-0.[89]*
   notes-0.10*
   Diofant 0.11 (Not Released Yet) <notes-0.11>
```

As you can see, old release notes come first in the pdf version, this can be reproduced on the sphinx v2.1.2.  I believe, this is a bug.

**Comment by tk0miya** [comment]
Fixed in #7099 
Thank you for reporting!
