### ISSUE TITLE
Error when compiling locales

### ISSUE THREAD

**Issue by Christophe31** [sphinx-doc/sphinx#6584]
**Describe the bug**
when you compile locales it craches (to me it blocks my CI)

**To Reproduce**
simply compile messages from a parent folder:
```
django-admin compilemessages

CommandError: Execution of msgfmt failed: /home/python/venv/lib/python3.7/site-packages/sphinx/locale/hi/LC_MESSAGES/sphinx.po:341: 'msgstr' is not a valid Python format string, unlike 'msgid'. Reason: The character that terminates the directive number 1 is not a valid conversion specifier.
msgfmt: found 1 fatal error
```

**Expected behavior**
Update the .mo file.

The fix seems easy: switch the r and the % just here:
- https://github.com/sphinx-doc/sphinx/blob/master/sphinx/locale/hi/LC_MESSAGES/sphinx.po#L341

**Comment by tk0miya** [comment]
Fixed by #6684 . Thank you for reporting!
