### ISSUE TITLE
Decorated inherited method has no documentation

### ISSUE THREAD

**Issue by nlgranger** [sphinx-doc/sphinx#6588]
**Describe the bug**

If an inherited method has a decorator, it does not inherit the parent's doc.

**To Reproduce**

```python
from abc import ABC, abstractmethod
from functools import lru_cache


class Base(ABC):
    @abstractmethod
    def my_method(self):
        """Do stuff."""
        pass

    @abstractmethod
    def my_other_method(self):
        """Do other stuff."""
        pass


class MyClass(Base):
    @lru_cache()
    def my_method(self):  # that one wont inherit the doc
        pass

    @lru_cache()
    def my_other_method(self):
        """Do other stuff but with a twist."""
        pass
```

```rst
.. autoclass:: MyClass
   :members: my_method, my_other_method
```

**Expected behavior**

Both methods should be documented

**Environment info**
- OS: Linux (Arch)
- Python version: 3.6
- Sphinx version: 2.1.2
- Sphinx extensions:  [sphinx.ext.autodoc]

**Additional context**

Related to https://github.com/sphinx-doc/sphinx/issues/3783 but `functools.lru_cache` calls `functools.update_wrapper` so it should work.

**Comment by tk0miya** [comment]
Note: Now, Sphinx uses `inspect.getdoc()` to get inherited docstring. But it seems not supporting decorators. We need to add custom code to do that.

**Comment by nlgranger** [comment]
Thank you!
