### ISSUE TITLE
Formatting issues with autodoc_typehints='none'

### ISSUE THREAD

**Issue by goodmami** [sphinx-doc/sphinx#6589]
**Describe the bug**

When using `autodoc_typehints='none'`, I see two issues currently:

1. When an annotated parameter has a default value, spaces are inserted around `=` where they are not for unannotated parameters. Consider:

   ```python
   def foo(x=True, y: bool = True, z = True):
       return x and y and z
   ```

   The result looks like:

   **foo**(*x=True, y = True, z=True*)

2. Return types are not removed. Consider:

   ```python
   def bar(x: int) -> int:
       return x * 2
   ```

   The result looks like:

   **bar**(*x*) -> int

**To Reproduce**

Use the above examples with the `autodoc_typehints='none'` option, or with the attached project (see below).

**Expected behavior**

I expect the annotated and unannotated parameters to be rendered similarly and for return type annotations to be removed as well, as if they were not there originally.

**Your project**

See attached [foobar.zip](https://github.com/sphinx-doc/sphinx/files/3406054/foobar.zip)

**Environment info**
- OS: [Pop!_OS 18.10]
- Python version: 3.6.8
- Sphinx version: 2.1.2
- Sphinx extensions:  [sphinx.ext.autodoc]

**Additional context**

- #6361 
- #5868 
- https://github.com/agronholm/sphinx-autodoc-typehints/pull/78

**Comment by tk0miya** [comment]
Fixed by #6592.
Thank you for reporting.
