### ISSUE TITLE
mo files are not getting built

### ISSUE THREAD

**Issue by IronVenom** [sphinx-doc/sphinx#6591]
I am using sphinx to translate some rst files to Spanish. While I am running the command ```set SPHINXOPTS=-D language=es```, the mo files are not getting built but the html files are getting built, and no translation is occurring. 
```
Running Sphinx v2.0.1
loading translations [es]... done
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 26 source files that are out of date
updating environment: 26 added, 0 changed, 0 removed
reading sources... [100%] index
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index
generating indices... genindex
writing additional pages... search
copying images... [100%] img/TWP65_002.jpg
copying static files... done
copying extra files... done
dumping search index in Spanish (code: es) ... done
dumping object inventory... done

The HTML pages are in build\html.

Build finished. The HTML pages are in build/html.
```
What can be the issue?

**Comment by tk0miya** [comment]
Could you share your project? A minimal reproducible example is also okay to me. We need to reproduce the error to help you.
Thanks,

**Comment by IronVenom** [comment]
```
C:.
├───build
├───lectures
│   ├───img
│   └───_static
├───locale
│   └───es
│       └───LC_MESSAGES
├───_sources
├───_static
│   └───audio
└───_templates
    └───plugin_layouts
        └───sphinx_bootstrap
            └───static
                ├───bootstrap-3.0.0
                │   ├───css
                │   ├───fonts
                │   └───js
                └───img
```
This is the project tree. I have the po and mo files in the LC_MESSAGES folder in locale ( used msgfmt to make the mo files), and the rst files that I want to translate are present in the lectures folder. I am running the ```make html``` command from the project directory. When I am doing that, this is happening - ```building [mo]: targets for 0 po files that are out of date```, and the html files that are then generated are not translated.

**Comment by tk0miya** [comment]
Is PyZombis your repository? If true, it seems `locale_dirs` setting was wrong. It should point base directory of locale directory. In this case, it should be `['locale']`, not `['locale/es/LC_MESSAGE']`.
https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-locale_dirs

**Comment by IronVenom** [comment]
I tried that as well, it doesn't work.

**Comment by IronVenom** [comment]
I followed all the instructions as mentioned in the documentation, and now I am stuck at the last step. When I am trying to build the html files, it is not able to check the mo files, and hence the html files being generated are not translated. Can you please try it out?

**Comment by tk0miya** [comment]
It seems your Sphinx-project directory is `lectures/`. Is this right? If so, please move `locale/` directory to under it. I feel your repository contains multiple conf.py and index.rst. I propose you to clean up your repository before posting issue. I think this is not a bug of Sphinx.

**Comment by IronVenom** [comment]
I am using the Runestone framework in the project, which also makes a conf.py file. Is it due to that? Can I accommodate the components and directives specific to the framework in the Translation process as well?

**Comment by IronVenom** [comment]
I am getting the following error 
```
Exception occurred:
  File "c:\users\atharva\anaconda3\lib\site-packages\docutils\nodes.py", line 1367, in set_duplicate_name_id
    old_node = self.ids[old_id]
KeyError: 'operadores-relacionais'
```
@tk0miya How to remove this error? I have seen that some other people also have got the same issue before.

**Comment by tk0miya** [comment]
As I commented above, we need reproducible information to fix the errors. How configured? What extensions did you used? What content did you wrote? Without the reproducible information, we can't help you.
So please post reproducible information in next bug report.

Note: This is not a forum of Sphinx. So we can't answer you to the question of usage.

Thanks,
