### ISSUE TITLE
Error Loading Fonts in Firefox 68

### ISSUE THREAD

**Issue by PapaTim68** [sphinx-doc/sphinx#6595]
**Describe the bug**
Since Firefox Update 68 Symbols/Fonts do not load in any Sphinx Documentation as seen in the first Screenshot.
This is related to a change in Firefox Local File Security policy. 

**Expected behavior**
Normally fonts should be loaded from disc like seen in the second Screenshot.

**Screenshots**
![Sphinx_error](https://user-images.githubusercontent.com/29522870/61616142-03182100-ac68-11e9-85e7-61b45e7c39b4.PNG)
![Sphinx_no_error](https://user-images.githubusercontent.com/29522870/61616432-ae28da80-ac68-11e9-9dd5-8cce2dd58935.PNG)

**Environment info**
- OS: Win7 
- Python version: 3.7.3
- Sphinx version: 2.1.2
- Sphinx extensions:  sphinx.ext.autodoc, sphinx.ext.napoleon
- Extra tools: Firefox 68

**Additional context**
Currently this problem can be fixed by changing Firefox about:config privacy.file_unique_origin
to false. Further information can be found at https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSRequestNotHttp

I am not sure if this can be fixed on Sphinx site, since changing the Firefox config is only a temporary work-around for me.

**Comment by tk0miya** [comment]
I suppose this might be a restriction of firefox browser.

Anyway, we does not use these fonts in builtin themes. So there are nothing to do from our side.
