### ISSUE TITLE
`Include` directive does not include lists correctly

### ISSUE THREAD

**Issue by ArtFlag** [sphinx-doc/sphinx#6596]
**Issue**

Including a list inside another list does not create coherent numbering.

**Steps to reproduce the behavior**

Create the included file:

```rst
#. Included step 1

#. Included step 2
```

Create the main file:

```rst

#. This step

#. That step

.. include:: ../includes/includestep.rst

#. Another step

```
Build.

**Result**

The HTML output is:

```console
1. This step

2. That step

1. Included step 1

2. Included step 2

3. Another step
```

**Expected behavior**

The lists should be merged, and the numbering should be continuous. 

```console
1. This step

2. That step

3. Included step 1

4. Included step 2

5. Another step
```

Am I misusing the include or is it a limitation for list items inside an include?

**Environment info**
- OS: Mac
- Python version: 3.7
- Sphinx version: 2.1.2

**Comment by jessetan** [comment]
This is unfortunately an issue with docutils if I am reading the code correctly. If you look at the `enumerator()` function in https://sourceforge.net/p/docutils/code/HEAD/tree/trunk/docutils/docutils/parsers/rst/states.py, it calls `is_enumerated_list_item()` on every numbered list item to check if the next item is part of the same list, or if it is something else.
`is_enumerated_list_item()` returns True if the next line starts with `#.` or whatever the next number in the list is. In any other case, like `.. include::`, it returns False.
This means that `.. include::` effectively ends the list. When the include is evaluated, a new list is started.

I haven't found anything in docutils mailing lists or bugs about this, except for https://sourceforge.net/p/docutils/mailman/message/4534219/, but that is already 17 years old :(

**Comment by tk0miya** [comment]
Yes, its well known behavior of docutils which is a reST parser of Sphinx. In docutils code, directives start a new block level elements. It means previous block level element is closed before directive declaration. I don't know it is a part of reStructuredText. Anyway, please post a request to docutils project if you'd like to discuss more about this.
Thanks,
