### ISSUE TITLE
When I try to run make html, it gives me - AttributeError: 'Sphinx' object has no attribute 'warn'

### ISSUE THREAD

**Issue by rishabkhincha** [sphinx-doc/sphinx#6600]
[sphinx-err-zsi74osf.log](https://github.com/sphinx-doc/sphinx/files/3423807/sphinx-err-zsi74osf.log)
**AttributeError: 'Sphinx' object has no attribute 'warn'**

I'm running Sphinx v2.1.2 with python 3.6.8. Log file has been attached and the screenshots are given below.

**To Reproduce**
```
<make html>

$ git clonehttps://github.com/rishabkhincha/ImageCube-1.git
$ cd ImageCube-1
$ pip install -r requirements.txt
$ python setup.py install
$ cd docs
$ make html
```

**Your project**
https://readthedocs.org/projects/imagecube-1/

**Screenshots**

![image](https://user-images.githubusercontent.com/19264284/61742581-7487ca80-ad61-11e9-90ef-b1df0d2bfb35.png)
![image](https://user-images.githubusercontent.com/19264284/61742616-879a9a80-ad61-11e9-8674-df53f04deb3c.png)

**Environment info**
- OS: Linux
- Python version: 3.6.8
- Sphinx version: 2.1.2
- Sphinx extensions:  sphinx.ext.autodoc, automodapi

**Comment by tk0miya** [comment]
The `warn()` API was deprecated since 1.6, and removed at 2.0. It seems automodapi module uses this old API. It must be updated to move to new logging framework. Please report this to their project.
Thanks,
