### ISSUE TITLE
#6310 Doesn't seem released in 2.1.*

### ISSUE THREAD

**Issue by fcolas** [sphinx-doc/sphinx#6602]
**Describe the bug**
The `imgmath_use_preview` flag was ported to svg output in #6310 and, according to the documentation is supposed to have been released in version 2.1.
The patch is in the branch master but not the branch 2.1.3 not in any of the tagged release 2.1.0, 2.1.1, 2.1.2.

**To Reproduce**
Check date of the file. On the 2.1.* tags and branch it is stuck at 2019-04-15 whereas the patch dates from 2019-04-24.

**Comment by tk0miya** [comment]
It might be a bug of our document... I'll take a loo later.

BTW, we use tags for point each release. For example, version 2.1.2 was tagged as v2.1.2: https://github.com/sphinx-doc/sphinx/tree/v2.1.2
And all branches are used for development of unreleased versions.

**Comment by jfbu** [comment]
Sorry #6310 got indeed merged into master (meaning 3.0 future release;  and this is the default documentation shown on [sphinx-doc.org](https://www.sphinx-doc.org)) but I accidentally added a CHANGES entry for 2.1.0 release mentioning it. I guess this is what you refer to saying "according to documentation".

The CHANGES at https://www.sphinx-doc.org/en/2.0/changes.html does not mention this merge (this is correct), but the CHANGES at  https://www.sphinx-doc.org/en/master/changes.html has erroneous entry under the Release 2.1.0 added features section.

Fixed at 80abe4945

We can keep this open if to discuss if the #6310 should be made available sooner than 3.0.

**Comment by tk0miya** [comment]
I don't think #6310 is not breaking change. So +1 for cherry-pick it into next release.

**Comment by jfbu** [comment]
@tk0miya Do you mean 2.2.0 release, then I cherry-pick to 2.0 branch right?

**Comment by tk0miya** [comment]
Yes, 2.0 branch is current "stable" branch, and it will be released as 2.2.0 soon.

**Comment by jfbu** [comment]
OK I am currently doing it

**Comment by jfbu** [comment]
sorry I made an error in rebase/merge in imgmath which I have fixed but will execute test before pushing (this time)

**Comment by jfbu** [comment]
#6310 got now merged into 2.0 at 365574f052fff6deb681279773772f838302cad7 and parent commits.

Sorry that during a conflict resolution I made an error in merging ``sphinx/ext/imgmath.py::generate_latex_macro()`` from #6310 into 2.0 and unfortunately I had already merged 2.0 into master before realizing my mistake. I think things are fine now.

@fcolos: #6310 will thus be available in upcoming 2.2.0 release. I will close this after testing succeeds.

**Comment by jfbu** [comment]
Of course, I also made a type annotation error and I had forgotten to fix our documentation. Well, testing passes (apart appveyor currently queuing the jobs)  and I will now go into hiding for a while, sorry for rather messy sequence of events on this occasion.
