### ISSUE TITLE
Autodoc does not emit documentation for imported data

### ISSUE THREAD

**Issue by pavel-kirienko** [sphinx-doc/sphinx#6607]
This is my MWE: https://github.com/pavel-kirienko/sphinx-issues-mwe

Specifically, here is the definition where autodoc seems to be misbehaving (please ignore the other documented issues, they are being discussed over at #6574):

https://github.com/pavel-kirienko/sphinx-issues-mwe/blob/07de46b31dccdc478b8380a34c84ed347ef9a9f7/sphinx_demo/_internal.py#L1-L2

The generated documentation does not include the data entity: https://sphinx-issues-mwe.readthedocs.io/en/latest/

**Comment by pavel-kirienko** [comment]
Same issue with undocumented dataclass attributes.

**Comment by tk0miya** [comment]
autodoc seeks assign statements to detect variables. In this case, `sphinx_demo/__init__.py` does not contains any assign statements. So `DATA_ENTITY` is not detected.
On the other hand, you can document it if you're trying to document `sphinx_demo._internal` package. If you have good idea to detect it expectedly, please send a pull request :-)

>Same issue with undocumented dataclass attributes.

Please file another issue please. One problem per one issue is better to us.

**Comment by tk0miya** [comment]
I noticed this is a dup of #6495. So I'm closing this now. Please follow #6495.
Thanks,
