### ISSUE TITLE
Missing final underscore in class attributes

### ISSUE THREAD

**Issue by david-cortes** [sphinx-doc/sphinx#6608]
If I write some documentation for a class in NumPy style and build docs with Sphinx autodoc + Napoleon extension, attributes that end in underscore will not end up showing the underscore.
Example:
```
Some class docs

Description of the class goes here

Parameters
----------
param1 : int
    Some parameters

Attributes
----------
some_attribute_ : int
    Some attribute you're not supposed to modify
```

Sphinx will generate docs that have the following:
```
Variables: * some_attribute (int) - Some attribute you're not supposed to modify
```
(Note the missing underscore at the end of the name)

As a practical example, I have this project's docs hosted on ReadTheDocs: https://outliertree.readthedocs.io/en/latest/

If you click `source` for the class documentation (first thing in the page), it can be seen that many attributes end in underscore, but are not shown as such in the docs.

**Comment by tk0miya** [comment]
It seems you've used old Sphinx (1.8.5):
https://readthedocs.org/projects/outliertree/builds/9435040/

Could you try latest release? I'd like to know the result of it.

**Comment by david-cortes** [comment]
Tried with 2.1.2. Problem is solved now, but it seems it has been going on for some time as 1.8.1 was also affected.
