### ISSUE TITLE
Support "sum types" on :type:  and :rtype:

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#661]
Sphinx's domains support type references through the `:type typename:`, `:rtype typename:` and `:param typename paramname:` roles.

This works fine for arbitrary local types and automatically refs them, but there is a limitation in that it's not possible to use "sum type" specifications where the variable or return value would be expressed as "type A or type B" (SomeObject or None, for instance), and would be specified as [`type1 | type2 | type3`] where each type would be equivalent to the current simple typespec argument. This may be incompatible with `:param typename param:` as it's non-trivial and would yield unreadable documentation anyway.

It is kind-of possible to fake it by using explicit refs (`:class:` for instance), but this results in a different font than the normal type font (on my machine, typespecs are typeset in 16px italic sans-serif, whereas refs are typeset in 12px bold monospace), and the final result is the following (with the type linked of course):

```
`SomeType`// | None//
```

instead of the expected

```
//SomeType | None//
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/661
- Originally reported by: [masklinn](https://bitbucket.org/masklinn)
- Originally created at: 2011-03-27T16:30:20.796

**Comment by shimizukawa** [comment]
_From Eunchong Yu on 2013-05-01 07:49:20+00:00_

Is there anyone working on this issue? I couldn't found other's work, so I'll try to resolve it.

**Comment by tk0miya** [comment]
For now, we have `typing` module to describe types. So `typing.Union` is much better to do that.
We no longer need to add new syntax.

Thanks,
