### ISSUE TITLE
Autodoc does not emit documentation for undocumented dataclass fields despite :undoc-members:

### ISSUE THREAD

**Issue by pavel-kirienko** [sphinx-doc/sphinx#6630]
MWE: https://github.com/pavel-kirienko/sphinx-issues-mwe/blob/fc701aaeed8dd3e4b2ddace5bf314245048b13cc/sphinx_demo/_internal.py#L32-L33

Generated from the MWE: https://sphinx-issues-mwe.readthedocs.io/en/latest/

This is a split-off from https://github.com/sphinx-doc/sphinx/issues/6607#issuecomment-516085764

**Comment by tapaswenipathak** [comment]
Hi folks: Can I please take the ticket and PR?

**Comment by pavel-kirienko** [comment]
I certainly won't object.

**Comment by tk0miya** [comment]
Now this was fixed by #7057.
And it will be released as 2.4.0 in earlier February.
Thank you for reporting!
