### ISSUE TITLE
.md files with links that end in .md have the .md stripped out

### ISSUE THREAD

**Issue by barbara-sfx** [sphinx-doc/sphinx#6631]
**.md getting stripped out of links**
A link like this in a markup file that is in a sphinx project (with .md at the end):

For all available operators, see ```[the govaluate
documentation](https://github.com/Knetic/govaluate/blob/master/MANUAL.md)```. 

shows up like this in the html output:

```
<a class="reference external" href="https://github.com/Knetic/govaluate/blob/master/MANUAL">the govaluate
documentation</a>
```

The .md has been stripped out, and the link doesn't work.

**To Reproduce**

1. Install/config a project to build md files. (Do I need to include all the steps here? I've included a zipped project.)
2. Add a file in markdown format with this link: ```[the govaluate documentation](https://github.com/Knetic/govaluate/blob/master/MANUAL.md). ```
3. Make html

**Expected behavior**
The link renders as 
```<
a class="reference external" href="https://github.com/Knetic/govaluate/blob/master/MANUAL.md">the govaluate
documentation</a>
```
(I don't care about the class, just the link.)

**Your project**
Link to your sphinx project, or attach zipped small project sample.
[product-docs-copy.zip](https://github.com/sphinx-doc/sphinx/files/3462725/product-docs-copy.zip)

**Environment info**
- OS: Mac 10.13.6
- Python version: 2.7.11
- Sphinx version: 1.85
- Sphinx extensions: see zip file
- Extra tools:

**Comment by tk0miya** [comment]
Please remember Sphinx-core does not support markdown. I guess you're using recommonmark, right? So please post this to their project. We can't answer about the module.

Thanks,
