### ISSUE TITLE
Undefined control sequence. \sphinxmaketitle

### ISSUE THREAD

**Issue by Routhinator** [sphinx-doc/sphinx#6641]
**Describe the bug**
Latext build fails due to unrecognized Sphinx control sequences.

```
! Undefined control sequence.
l.84 \sphinxmaketitle
```

**To Reproduce**
```
sphinx-build -M latex docs docs_output
cd docs_output/latex
make
```

**Expected behavior**
Make should have produced a PDF document.

**Your project**
https://gitlab.routh.io/minecraft/launchers/routh-io-skcraft

**Environment info**
- OS: Ubuntu 18.04
- Python version: 3.6
- Sphinx version: v2.1.2
- Sphinx extensions: autodoc, intersphinx, viewcode, coverage, todo, javasphinx
- Extra tools: Gitlab CI

**Additional context**

Error output
```
[Loading MPS to PDF converter (version 2006.09.02).]
) (/usr/share/texlive/texmf-dist/tex/latex/oberdiek/epstopdf-base.sty
(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/grfext.sty)
(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))
*geometry* driver: auto-detecting
*geometry* detected driver: pdftex
(/usr/share/texlive/texmf-dist/tex/latex/hyperref/nameref.sty
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/gettitlestring.sty))
! Undefined control sequence.
l.84 \sphinxmaketitle
                     
? 
! Emergency stop.
l.84 \sphinxmaketitle
                     
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on routh-io-skcraft-launcher-docs.log.
Latexmk: Index file 'routh-io-skcraft-launcher-docs.idx' was written
Latexmk: Errors, so I did not complete making targets
```

**Comment by jfbu** [comment]
The `\sphinxmaketitle` macro is defined via the LaTeX document loading either `sphinxhowto.cls` or `sphinxmanual.cls` file, corresponding to choice of `'howto'` or `'manual'` in `latex_documents` configuration variable. Yours has

```
latex_documents = [
    (master_doc, 'routh-io-skcraft-launcher-docs.tex', project,
     author, 'book')
]
```

which contains `'book'`. Please try using configuration seeting [latex_docclass](https://www.sphinx-doc.org/en/master/usage/configuration.html?highlight=latex_docclass#confval-latex_docclass) 

```
latex_documents = [
    (master_doc, 'routh-io-skcraft-launcher-docs.tex', project,
     author, 'manual')
]
latex_docclass = {'manual': 'book'}
```

**Comment by jfbu** [comment]
Does my comment solve your problem? I would like to close this.

**Comment by jfbu** [comment]
Actually sorry, I think we do have a bug here. The documentation of ['latex_documents'](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-latex_documents) allows using own classes rather than `'howto'` and `'manual'` Sphinx ones. Hence indeed Sphinx LaTeX should not rely on macros being defined only in its own LaTeX class files.

**Comment by jfbu** [comment]
Fixed at https://github.com/sphinx-doc/sphinx/commit/59890a3b6df3b1e9c91c69a60c7df0cf48e3722a

Thanks for reporting!
