### ISSUE TITLE
Provide `docs_require` option to install additional requirements (similar to `tests_require`)

### ISSUE THREAD

**Issue by theHamsta** [sphinx-doc/sphinx#6644]
**Is your feature request related to a problem? Please describe.**
`python setup.py test` auto-installs needed requirements for testing. The corresponding setuptools command reads an option `tesst_require` to determine which packages . This is not the case for sphinx' `BuildDoc` command. Need packages have to be installed manually.

**Describe the solution you'd like**
E.g. `pytest` assures that all packages specified by `tests_require` and all requirements needed for `your_package[all]` are installed. Similarly, sphinx could provide an option to specify the needed requirements for the build process (themes, sphinx extensions).

**Describe alternatives you've considered**

 - I can specify requirements for documentation building by specifying an setuptools extra `docs` and install the required packages by `pip install -e .[docs]`.
- setuptools could provide an option to install requirements for arbitrary build commands.

**Additional context**
https://github.com/pyscaffold/pyscaffold/issues/250

**Comment by tk0miya** [comment]
Reasonable. Could you make a pull request please?

**Comment by theHamsta** [comment]
Hi, I can create a PR when I have some time next week.

**Comment by tk0miya** [comment]
It seems the proposal to setuptools was rejected (https://github.com/pypa/setuptools/issues/1820).
Is there still anything to do from sphinx side?

**Comment by tk0miya** [comment]
I'm closing this now because there nothing to do from Sphinx side.  Please feel free to reopen if you still have any idea.
Thank you for proposal.
