### ISSUE TITLE
Quickstart no longer asks for autodoc

### ISSUE THREAD

**Issue by nralbers** [sphinx-doc/sphinx#6656]
**Describe the bug**
According to the quickstart documentation, quickstart will ask if you want to run autodoc. However, the latest version no longer does this.

**To Reproduce**
```
sphinx-quickstart

Welcome to the Sphinx 2.1.2 quickstart utility.

Please enter values for the following settings (just press Enter to
accept a default value, if one is given in brackets).

Selected root path: .

You have two options for placing the build directory for Sphinx output.
Either, you use a directory "_build" within the root path, or you separate
"source" and "build" directories within the root path.
> Separate source and build directories (y/n) [n]: y

The project name will occur in several places in the built documentation.
> Project name: Structlog Extensions
> Author name(s): Niels Albers
> Project release []: 0.0.3

If the documents are to be written in a language other than English,
you can select a language here by its language code. Sphinx will then
translate text that it generates into that language.

For a list of supported codes, see
https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-language.
> Project language [en]: 

Creating file ./source/conf.py.


```

**Expected behavior**
Either: ask for autodoc and configure, as stated in the documentation.
Or: Update the documentation to conform to the new behaviour, and document
how to configure autodoc in the quick start documentation

**Environment info**
- OS: Linux
- 3.6.0
- Sphinx version: 2.1.2
- Sphinx extensions:  sphinx.ext.autodoc

**Comment by tk0miya** [comment]
Thank you for reporting.
Since 2.0, quickstart does not ask for extensions (see #4148). So our docs are wrong for this case.

**Comment by tapaswenipathak** [comment]
Hi folks: I will PRing.

**Comment by nerdenator** [comment]
I am looking through Google to find a tutorial to learn how to use Sphinx to document a project. Pretty much every single one of them recommends using sphinx-quickstart, and does so using the old set of questions. To me, this is a major, breaking change that is preventing me from using sphinx. I don't suppose there's any way to add in the old questions using a command line flag or some other optional route?

**Comment by JacksonWuxs** [comment]
I am wondering what is the change between V2.0+ and V1.0+. If the updates are not significant, should I use V1.0+ to fix this problem?

**Comment by domdog** [comment]
I ran into the same problem.

Would like a command line flag to have access to the old behaviour,  so commonly mentioned across the web, or a clear document that describes:

    -what is completely setup as a default now.  There is nothing to do with these and they are working in the present setup.
    - what is installed but need configuration and a clear example at each point in the process.
    - what I can install and clear directions with examples of how to do so.

**Comment by astrojuanlu** [comment]
I was looking at this but I'm not sure _which_ part of the documentation is outdated with respect to `sphinx-quickstart`? Could you clarify?

**Comment by nralbers** [comment]
It looks like the documentation has had a major revamp since this ticket was opened. The issue was in the "Getting started" and "Tutorial" sections, but the original issue is no longer present.
