### ISSUE TITLE
Adding Contributor Covenant Code of Conduct 

### ISSUE THREAD

**Issue by tapaswenipathak** [sphinx-doc/sphinx#6658]
Hey maintainers: Can the project has Contributor Covenant Code of Conduct added https://en.wikipedia.org/wiki/Contributor_Covenant?

**Comment by tk0miya** [comment]
+1

**Comment by techtonik** [comment]
@tapaswenipathak will you actively contribute to the project if that thing is added here?

**Comment by tapaswenipathak** [comment]
Hi @techtonik: I missed the mail, sorry! I am interested, would just guarantee behavioral issues if Contributor Covenant Code of Conduct is added.

**Comment by tapaswenipathak** [comment]
Hi @techtonik: I missed the mail, sorry! yeah I think, would just guarantee behavioral issues if Contributor Covenant Code of Conduct is added, works for me you if you write a statement having confidence on Sphinx community principles.

**Comment by techtonik** [comment]
@tapaswenipathak thanks for the answer. It is really important to understand the motivation of different people. To make it even more useful, can you confirm or deny that your motivation is not really to contribute to Sphinx codebase or help with tracker isues, but mostly to place the rules? (I often just want to place the badge or license)

Do you have any statistics already if adding those Contributor Covenant Code of Conduct increases contributions or their quality? Or maybe there is a reverse trend?

**Comment by tapaswenipathak** [comment]
@techtonik: Nope! Wording issues. I am very much interested. I make folks add Contributor Covenant Code of Conduct before writings PRs in an open source project/org.

**Comment by techtonik** [comment]
Thanks for the answer. That clarifies things for more questions. ) Why is it important for you to have CoC in place before contributing? Do you image any project without CoC as potentially unfriendly to contributors? If yes, then what contributes to this feeling (e.g. previous conflicts, world of mouth, ...)? In which circumstances you would contribute to the project without CoC in place?

Answering these questions can help people with different mental models (like me) to understand people like you better, which improves communication in a long term. I hope you don't find these questions as too private and personal. )
