### ISSUE TITLE
Run python3 make html and Error of referring of Py2 sphinx in Makefile and make.dat

### ISSUE THREAD

**Issue by krmanish** [sphinx-doc/sphinx#6669]
**Describe the bug**
Fedora 29 and run command sphinx-quickstart-3 generates workflow with reference of ``sphinx-build`` in the ``make.dat`` and ``Makefile`` which is wrong and should be `sphinx-build-3`

**To Reproduce**
```
$ sudo yum install python3-sphinx
$ cd Docs/
$ sphinx-quickstart-3  # Select all default option
$ make html  # Error
```
``/bin/sh: sphinx-build: command not found
make: *** [Makefile:20: html] Error 127
``

**Expected behavior**
It should build without any issues using python3 sphinx which seems not being considered. 
make.dat and Makefile should have reference to python-3 `sphinx-build-3` instead of py2 i.e `sphinx-build`

**Environment info**
- OS: Fedora 29
- Python version:  3.7.4
- Sphinx version: 1.7.6

**Comment by AA-Turner** [comment]
We no longer support Python 2. Perhaps this is a Fedora issue?

A
