### ISSUE TITLE
Allow code literals in plural e.g. `iframe`s

### ISSUE THREAD

**Issue by stdedos** [sphinx-doc/sphinx#6677]
**Describe the bug**

Documentation:
```
Has `iframe`s [...]
```

leads to:
```
WARNING: Inline interpreted text or phrase reference start-string without end-string
```

**To Reproduce**
^^

**Expected behavior**
As per Markdown:
Has `iframe`s [...]
Instead of:
Has &#96;iframe&#96;s [...]

**Your project**
^^

**Screenshots**
![image](https://user-images.githubusercontent.com/133706/63755595-a68bcf80-c8bf-11e9-8ce2-364570e6e6d5.png)

**Environment info**
- OS: [e.g. Unix/Linux/Mac/Win/other with version] Ubuntu 16.04
- Python version: [e.g. 3.7.1] v3.5
- Sphinx version: [e.g. 1.8.2] v2.2.0
- Sphinx extensions:  [e.g. sphinx.ext.autodoc, recommonmark] `sphinx.ext.autodoc`
- Extra tools: [e.g. Browser, tex or something else]

**Additional context**

- [e.g. URL or Ticket]

**Comment by jfbu** [comment]
Try

```
Has ``iframe``\ s
```

reST mark-up.

Please report upstream your desired mark-up extension to [Docutils](https://sourceforge.net/p/docutils/feature-requests/)

**Comment by jfbu** [comment]
Closing as not being a Sphinx issue.
