### ISSUE TITLE
Should htmlhelp use HTML4 output by default?

### ISSUE THREAD

**Issue by ghost** [sphinx-doc/sphinx#6685]
Since Sphinx 2.0.0, `html` outputs HTML5 by default, see commit https://github.com/sphinx-doc/sphinx/commit/a3cdd465ecf018fa5213b6b2c1c4e495973a2896.

This caused a small problem for `htmlhelp`.
Below screenshots are Python's official chm document.

Before Sphinx 2.0.0, when double click an index, the item is highlighted:
![Pic1](https://raw.githubusercontent.com/animalize/pics/master/issues/chm373.PNG)

After Sphinx 2.0.0, when double click an index, the item is not highlighted:
![Pic2](https://raw.githubusercontent.com/animalize/pics/master/issues/chm374.PNG)

This may be because the chm viewer doesn't support HTML5 well?
Or may be because the page is not well written?
Very sorry, I'm not a HTML expert, can't give a conclusion to this question.

But after I set `html4_writer = True`, the problem disappears, the selected item is highlighted as before.
So, should `htmlhelp` use HTML4 output by default?

**Comment by ghost** [comment]
This article said chm viewer uses IE7 mode to render chm content, it doesn't support HTML5 well.
https://weblog.west-wind.com/posts/2012/feb/15/make-your-chm-help-files-show-html5-and-css3-content

It seems `htmlhelp` should output HTML4 by default.

**Comment by ghost** [comment]
@JulienPalard @zooba for know.

**Comment by JulienPalard** [comment]
Thanks for the report @animalize, sadly I have no Windows machine here to test, so I won't be of any help on this issue.

**Comment by tk0miya** [comment]
I consider this is a bug of Sphinx-2.x. So I'll fix it later.
Thanks,

**Comment by tk0miya** [comment]
I fixed this. Could you check with this?
You can try it with `pip install git+https://github.com/sphinx-doc/sphinxcontrib-htmlhelp`.

**Comment by ghost** [comment]
I will try it today or tommorow.

**Comment by ghost** [comment]
> I fixed this. Could you check with this?
> You can try it with `pip install git+https://github.com/sphinx-doc/sphinxcontrib-htmlhelp`.

Tested this with Sphinx v2.3.1, it doesn't work (the item is not highlighted).

BTW, this combination works (the item is highlighted):
- use Sphinx v2.3.1, without this change. 
- add `html4_writer = True` to `conf.py`

**Comment by tk0miya** [comment]
Thank you for comment. Sorry, it's my wrong. It still output headers in HTML5 mode. I just push another change. Could you try new htmlhelp extension please?

**Comment by ghost** [comment]
It works now! thanks.

**Comment by tk0miya** [comment]
Thank you for confirming. Closing :-)
