### ISSUE TITLE
:scale: option of image/figure directive not working for SVG images in HTML builds

### ISSUE THREAD

**Issue by quba42** [sphinx-doc/sphinx#6696]
**Describe the bug**
When including an SVG image, using the `.. image::` or `.. figure::` directives, The `:scale:` option (e.g. `:scale: 50%`) appears to have no effect on the output of HTML builds.

**To reproduce**

Include any SVG image in a sphinx document as follows:
```
.. image:: example_image.svg
  :scale: 50%
```
Build the HTML version of the document:
```
make html
```

**Expected behaviour**
The image in the HTML output is half the size as compared to when I am not using the option `:scale: 50%`.

**Actual behaviour**
The `:scale: 50%` directive has no effect on the resultant HTML.

**Environment info**
- OS: [Debian Buster]
- Python version: 3.7.4+
Sphinx was installed in a virtual python environment as follows:
```
pip install -U sphinx
pip install sphinxcontrib-svg2pdfconverter
```
This resulted in the following versions:
- sphinx 2.2.0
- sphinxcontrib-svg2pdfconverter 0.1.0

Here, `sphinxcontrib-svg2pdfconverter` is only needed to compare the HTML behaviour with a successful LaTeX build. The HTML issue itself can be recreated with Sphinx alone.

**Additional context**
The `:scale:` option works as expected for SVG imgaes in latexpdf builds (in conjunction with [this](https://github.com/sephalon/sphinxcontrib-svg2pdfconverter) extension).

The `:width:` and `:height:` options, do work as expected for SVG images in HTML builds.

**Comment by Borda** [comment]
the fix should be simple, just transform to `\includesvg{figure1.svg}` add missing package `\usepackage{svg}`
https://tex.stackexchange.com/questions/122871/include-svg-images-with-the-svg-package

**Comment by tk0miya** [comment]
Unfortunately, `:scale:` option is not implemented now. To do that, I posted https://github.com/shibukawa/imagesize_py/pull/27 to imagesize_py project as a preparaton. I will post another PR to sphinx to support it laster.

**Comment by tk0miya** [comment]
Fixed by #6985 
Thank you for reporting!

**Comment by quba42** [comment]
Thank you for the good work!

**Comment by pfheatwole** [comment]
Be aware, there are currently some issues with how "imagesize_py" handles SVG files. For example, my SVG `<img>` widths and heights were enormous in HTML builds because of shibukawa/imagesize_py/issues/42
