### ISSUE TITLE
Python numeric literals with underscores don't generate correct markup

### ISSUE THREAD

**Issue by h1nk** [sphinx-doc/sphinx#6697]
I'm a little confused about why this happens because I see PEP 515 lexer support was added in Pygments quite a while ago in [birkenfeld/pygments-main#720](https://bitbucket.org/birkenfeld/pygments-main/pull-requests/720), yet it seems `pygmentize` is generating incorrectly syntax highlighted markup.

**To Reproduce:**
```rest
.. code-block:: python

    1_024
```
```shell
$ make -C ./docs/ clean html
```

**Produces:**
```html
...
<span class="mi">1</span>
<span class="n">_024</span>
...
```

**Expected Behavior:**
Correct syntax highlighting generation for PEP 515 numeric literals.

**Environment Info:**
- OS: Linux/Ubuntu LTS
- Python: 3.7.4
- Sphinx: 2.2.0 w/:
```python
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.extlinks',
    'sphinx.ext.intersphinx',
    'sphinx.ext.doctest',
    'sphinx.ext.coverage',
    'sphinx.ext.githubpages',
    'sphinxcontrib.programoutput',
]
```

**Comment by tk0miya** [comment]
Yes, this is lack of support of pygments.
```
(py37) bash-3.2$ pygmentize -V
Pygments version 2.4.2, (c) 2006-2019 by Georg Brandl.
(py37) bash-3.2$ echo 1_024 | pygmentize -l python -f html
<div class="highlight"><pre><span></span><span class="mi">1</span><span class="n">_024</span>
</pre></div>
```
There are nothing to do from sphinx side. Please let me know if you'll see same error in spite of  updating pygments.
