### ISSUE TITLE
Warning in note: Warning's header is blue 

### ISSUE THREAD

**Issue by vincentBenet** [sphinx-doc/sphinx#6701]
**Describe the bug**
The header of a warning box is blue when inside a note

**To Reproduce**
```
.. note::
  Wires enough for ONE actuator. For each additional you need to count +2 wires.
  
  .. warning:: Make sure your wires are adapted to the current intensity.
```

**Expected behavior**
Having an orange header

**Screenshots**
![image](https://user-images.githubusercontent.com/38955854/65236033-a0a89900-dacf-11e9-980b-dca895fc780b.png)

**Comment by tkoyama010** [comment]
@Vincentimetr 
Thank you for your report. It seems that this is a problem of the sphinx_rtd_theme. Could you report this issue to [sphinx_rtd_theme](https://github.com/readthedocs/sphinx_rtd_theme/issues) ?

**Comment by tk0miya** [comment]
@tkoyama010 Thank you for comment. Indeed, it seems this is a bug of sphinx_rtd_theme.
It is not reproduced with alabaster and other themes.
So I'm closing this because not a bug of Sphinx.
Thanks,
