### ISSUE TITLE
Tables should could graphemes instad of code points

### ISSUE THREAD

**Issue by sebastian-philipp** [sphinx-doc/sphinx#6702]
**Is your feature request related to a problem? Please describe.**

Tables look unaliged, if they use complex unicode characters. 

E.g.: the table in the bottom of https://raw.githubusercontent.com/ceph/ceph/master/doc/mgr/orchestrator_cli.rst

Would be cool, if you could use graphemes instead of code points for calculating the table grid:

https://github.com/alvinlindstam/grapheme

**Additional context**

https://stackoverflow.com/questions/27331819/whats-the-difference-between-a-character-a-code-point-a-glyph-and-a-grapheme/27331885#27331885

**Comment by tk0miya** [comment]
Reasonable. But we're using [docutils](http://docutils.sourceforge.net/) for a reST parser. So it is better to propose this to their project.
Thanks,
