### ISSUE TITLE
C/CPP domains: support for bit fields

### ISSUE THREAD

**Issue by rhssk** [sphinx-doc/sphinx#6707]
Context: [breathe #358](https://github.com/michaeljones/breathe/issues/358)

It looks like Sphinx declaration validator doesn't support bit fields since a declaration like
`uint8_t foo : 3` triggers fail in [`sphinx/domains/cpp.py`](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/domains/cpp.py#L4646). With my limited insight in Sphinx's internals, my guess would be that [`_parse_declarator`](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/domains/cpp.py#L5766) might need some modifications.

Ping @jakobandersen

**Comment by jakobandersen** [comment]
Thanks, bit fields should now be supported for C++ on the 2.0 branch. Please open another issue for support in the C domain, if relevant.
