### ISSUE TITLE
Change mock to work with class decorators

### ISSUE THREAD

**Issue by rettenbs** [sphinx-doc/sphinx#6709]
**Is your feature request related to a problem? Please describe.**
I am using autodoc and mock an external library that provides class decorators. All classes that use the mocked decorators do not show up in the documentation.

**Describe the solution you'd like**
Checking `args[0]` for `[type, FunctionType, MethodType]` in https://github.com/sphinx-doc/sphinx/blob/master/sphinx/ext/autodoc/mock.py#L61 solves the problem. Currently only `[FunctionType, MethodType]` are checked.

**Describe alternatives you've considered**
I am currently using this workaround in my `conf.py`:
```python
def call_mock(self, *args, **kw):
    from types import FunctionType, MethodType
    if args and type(args[0]) in [type, FunctionType, MethodType]:
        # Appears to be a decorator, pass through unchanged
        return args[0]
    return self

from sphinx.ext.autodoc.mock import _MockObject
_MockObject.__call__ = call_mock
```

**Additional context**

**Comment by tk0miya** [comment]
Fixed by #6719 . Thank you for reporting.
