### ISSUE TITLE
Extra dep on testing

### ISSUE THREAD

**Issue by stanislavlevin** [sphinx-doc/sphinx#6712]
**Describe the bug**
sphinx/util/osutil.py module makes an import of sphinx.testing.path:

https://github.com/sphinx-doc/sphinx/blob/master/sphinx/util/osutil.py#L24
```python
from sphinx.deprecation import RemovedInSphinx40Warning
from sphinx.testing.path import path as Path

if False:
```

This results in sphinx dependency on its own testing module. For my distro packaging policy, we package tests (if we do it) separately from main package. Test package in turn should not be required by the main one because of not used at runtime tests dependencies (for example, pytest).

**Expected behavior**
There should be no dependency on own tests/testing.

**Environment info**
- OS: ALT Linux
- Python version: 3.7.4
- Sphinx version: 2.2.0

**Comment by tk0miya** [comment]
It has been used in `abspath()` to avoid `Path` objects are broken in this function on testing. Do you have good idea to do it without importing? We can remove the code if we'll get better way.

**Comment by stanislavlevin** [comment]
@tk0miya, thank you for looking at this. The idea is very simple: if some code is utilized by the main package then this code should be moved out to the main package.

**Comment by tk0miya** [comment]
That sounds strange for me. `sphinx.testing.path` is only used for testing framework. Why moving out?

>There should be no dependency on own tests/testing.

`sphinx.testing` is not "own testing". It is a testing framework for sphinx itself and extensions. I consider it is a library. IMO, it is better to patch the code on packaging if your distro disagree to ship it together.

**Comment by stanislavlevin** [comment]
I've already dropped dependency on testing in a hackish way:
```diff
+diff --git a/sphinx/util/osutil.py b/sphinx/util/osutil.py
+index f9c7ce6c4..f37aa342c 100644
+--- a/sphinx/util/osutil.py
++++ b/sphinx/util/osutil.py
+@@ -22,7 +22,13 @@ from os import path
+ from typing import Any, Generator, Iterator, List, Tuple
+ 
+ from sphinx.deprecation import RemovedInSphinx30Warning, RemovedInSphinx40Warning
+-from sphinx.testing.path import path as Path
++
++# Path is only used during testing
++# This results in an extra dep on testing package
++try:
++    from sphinx.testing.path import path as Path
++except ImportError:
++    Path = None
+ 
+ if False:
+     # For type annotation
+@@ -178,7 +184,7 @@ fs_encoding = sys.getfilesystemencoding() or sys.getdefaultencoding()
+ 
+ 
+ def abspath(pathdir: str) -> str:
+-    if isinstance(pathdir, Path):
++    if Path is not None and isinstance(pathdir, Path):
+         return pathdir.abspath()
+     else:
+         pathdir = path.abspath(pathdir)
+-- 
```
I just want to inform upstream about this problem.

**Comment by tk0miya** [comment]
Okay, it's acceptable. I'll work for it later.

**Comment by stanislavlevin** [comment]
Thank you in advance!

**Comment by tk0miya** [comment]
#6728 is merged now.
Thank you for reporting!
