### ISSUE TITLE
Function styling not appearing as expected

### ISSUE THREAD

**Issue by pogson** [sphinx-doc/sphinx#6713]
**Describe the bug**
Regardless of which theme is selected, when using `.. func:` I'm expecting the description to formatted in plain text but is formatted similarly to the function call. Though while playing around I got the description to appear correctly by adding `:noindex:` but that has other consequences.

I did notice the html source was using a `dt` with a class `sig-name` whereas the expected uses a `dd` and a nested `p`  tag

**To Reproduce**
Here's my rst file
```
:mod:`example`
==============

.. function:: strange()
   This should be a description


.. function:: expected()
   :noindex:

   This is a description
```

**Screenshots and Expected behavior**
Classic Theme:
![example-classic](https://user-images.githubusercontent.com/44173402/65979670-4b5b7880-e43b-11e9-9793-d57935d558ce.PNG)

Sphinx-rtd:
![example-sphinx-rtd](https://user-images.githubusercontent.com/44173402/65979671-4b5b7880-e43b-11e9-94d6-11d284f6155c.PNG)

Generated HTML:
```
<h1><code class="xref py py-mod docutils literal notranslate"><span class="pre">example</span></code><a
        class="headerlink" href="#example" title="Permalink to this headline">¶</a></h1>
<dl class="function">
    <dt id="strange">
        <code class="sig-name descname">strange</code><span class="sig-paren">(</span><span
            class="sig-paren">)</span><a class="headerlink" href="#strange"
                                         title="Permalink to this definition">¶</a></dt>
    <dt>
        <code class="sig-name descname">This should be a description</code></dt>
    <dd></dd>
</dl>

<dl class="function">
    <dt>
        <code class="sig-name descname">expected</code><span class="sig-paren">(</span><span
            class="sig-paren">)</span></dt>
    <dd><p>This is a description</p>
    </dd>
</dl>
```

**Environment info**
- OS: Ubuntu 18.04.1 LTS
- Python version: 3.6.8
- Sphinx version: 2.2.0
- Sphinx extensions: None

**Comment by jfbu** [comment]
Your mark-up is lacking a needed empty line to separate the directive from its contents:

```
.. function:: strange()

   This is indeed be a description
```

Check out [here](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#directives), there is an example with ``function`` directive.

Closing as not being a bug of Sphinx.

**Comment by pogson** [comment]
Ah, thanks. That seems to be the problem.
