### ISSUE TITLE
autodoc and autosummary hang and fail without notice

### ISSUE THREAD

**Issue by drewejohnson** [sphinx-doc/sphinx#6723]
**Describe the bug**
Attempting to build documentation for [`serpentTools`](https://github.com/CORE-GATECH-GROUP/serpent-tools) package. When building documentation and reading sources, autodoc hangs for about ten seconds and exits early. There are no error messages raised, and the return code is zero, so `ReadtheDocs` and other toolchains do not detect a failure. If you search [our most recent build](https://readthedocs.org/api/v2/build/9466783.txt) for 
```
reading sources... [  4%] containers/containers
```
you can see that it stops before reaching the writing phase. 

**To Reproduce**
```
$ python -m venv ~/.venv/st-docs
$ source ~/.venv/st-docs/bin/activate
$ git clone https://github.com/CORE-GATECH-GROUP/serpent-tools.git
$ cd serpent-tools
$ pip install -r requirements.txt
$ cd docs
$ make html SPHINXOPTS="-vv -D language=en" > make.log
<build goes off and hangs>
$ tail -n 10 make.log
[app] emitting event: 'source-read'('containers/containers', ['.. _containers:\n\n==========\nContainers\n==========\n\nMany of the rea
[autodoc] /home/drew/serpent-tools/docs/containers/containers.rst:17: input:
.. autoclass:: serpentTools.objects.BranchContainer

[autodoc] from serpentTools.objects import BranchContainer
[autodoc] adding a mock module as serpentTools!
[autodoc] adding a mock module as serpentTools.objects!
[autodoc] import serpentTools.objects => serpentTools.objects
[autodoc] getattr(_, 'BranchContainer')
[autodoc] => serpentTools.objects.BranchContainer
```
I have noticed this on our develop branch [default when cloning] and on our latest release [git checkout 0.7.1].

**Expected behavior**
I would expect autodoc to progress through the documentation and build safely and correctly. In the event of an error, even a time out error, I would expect a non-zero return code. Because of this, we are not alerted to failing documentation and it is difficult for me to determine the root cause and the fix :grimacing: 

**Your project**
* [Main repo](https://github.com/CORE-GATECH-GROUP/serpent-tools)
* [develop `conf.py`](https://github.com/CORE-GATECH-GROUP/serpent-tools/blob/88b0e4c8a905df328cc93a3d5a63ff9ef0424bd5/docs/conf.py)

**Environment info**
- OS: Arch Linux 5.3.1-arch1-1-ARCH
- Python version: 3.7.4
- Sphinx version: 2.2.0
- Sphinx extensions:  `sphinx.ext.autodoc` and `sphinx.ext.autosummary`
- Extra tools: [e.g. Browser, tex or something else]

**Additional context**

- https://github.com/CORE-GATECH-GROUP/serpent-tools/issues/342

Some things I've tried as a fix:
1) Remove all autoclass/autofunction directives
In doing this, I am able to read sources and write all the documentation. However, as soon as I add a single `autoX`, the problem reappears.
2) The barest of documentation.
Removed everything, started with `sphinx-quickstart` and created a lone `index.rst` with
```
... autofunction:: serpentTools.read
```
with a minimal `conf.py`. Same problem

**Comment by tk0miya** [comment]
On my local, with following Dockerfile, the build is succeeded normally.
```
FROM python:3.7-slim

RUN apt update; apt install -y git make
RUN git clone https://github.com/CORE-GATECH-GROUP/serpent-tools.git
WORKDIR /serpent-tools
RUN pip install -r requirements.txt
RUN pip install Sphinx sphinx_rtd_theme
WORKDIR /serpent-tools/docs
RUN make html SPHINXOPTS="-vv -D language=en"
```

I don't know why not reproducible. But it is hard to investigate to me...

Basically, autodoc goes following steps:
1. import the module
2. inspect the target object

I guess the exit or crash is happened on step 1. If so, it is hard to control from Sphinx side.

**Comment by drewejohnson** [comment]
I have been able to "build" the documentation both locally and on RTD by not having the package installed, following your example. However, none of the `autoX` directives are generating documentation. As an example, [here is a link](https://serpent-tools.readthedocs.io/en/0.8.0rc0/readers/results.html) to the updated RTD docs where the package is not imported.

Playing around with some of the build commands, I believe this issue is on our side. After importing the project on RTD, the package doesn't build due to some importing errors.

I guess the heart of this issue is that the crash is not documented / raised by autodoc or autosummary. This would make error tracking easier, rather than silently failing for no _apparent_ reason. I'm happy to consider this closed if appropriate.

**Comment by drewejohnson** [comment]
I have resolved the failing documentation on my end. We had a combination of bad settings in `conf.py` that just didn't work properly. This allows me to build the full documentation properly.

However, when I have the package installed, it still "appears" to hang when generating documentation. I don't get any status updates [reading this, writing that] but all the documentation is written :man_shrugging:
