### ISSUE TITLE
Syntax error exceptions do not show applicable RST line and file.

### ISSUE THREAD

**Issue by pietvr** [sphinx-doc/sphinx#6726]
**Is your feature request related to a problem? Please describe.**
Sphynx does not provide the RST file and line when a RST syntax error strikes.

**Describe the solution you'd like**
For a RST syntax error the applicable RST file and line should be provided in the error log
For internal sphynx errors, this RST file and line is a start for investigation. 

WarningIsErrorFilter is more or less the idea I have to address a RST syntax error.

All raises can possibly be impacted.

**Describe alternatives you've considered**
Checking my last change to the RST file to find out why there could be a python exception.

**Additional context**
Example exception trigger:
```
.. only:: SOMETHINGTRUE
   we want to write something without newline
```

Example exception syntax error:
```
** Building RST documentation using Sphinx.

Exception occurred:
  File "/usr/local/lib/python3.7/dist-packages/sphinx/util/tags.py", line 68, in eval_condition
    raise ValueError('chunk after expression')
ValueError: chunk after expression
The full traceback has been saved in /tmp/sphinx-err-j_h31t85.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!

make: *** [Makefile:110: doc] Error 2
ERROR: Job failed: exit code 1
```
Example error shinx trows as a syntax error: [sphinx-err.log]
(https://github.com/sphinx-doc/sphinx/files/3707728/sphinx-err.log)
The error is given by:
[tags.py.txt](https://github.com/sphinx-doc/sphinx/files/3707741/tags.py.txt)
[eager_only.py.txt](https://github.com/sphinx-doc/sphinx/files/3707742/eager_only.py.txt)

- [e.g. URL or Ticket]
I logged this in  sphinx_selective_exclude. But this was the wrong place.
https://github.com/pfalcon/sphinx_selective_exclude/issues/6

**Comment by tk0miya** [comment]
Please try bundled "only" directive. It shows a warning message containing source location.
```
/Users/tkomiya/work/tmp/doc/index.rst:4: WARNING: exception while evaluating only directive expression: chunk after expression
```

I think showing source location properly is a responsibility of each component. It is hard to show them by Sphinx side when exception raised. So I think this case should be fixed by sphinx_selective_exclude module. It's not difficult.

**Comment by rchrdgrace** [comment]
Tk0miya is correct; It's not difficult IF you know the details. The '.. only::' directive with a correctly used tag is the way to avoid this problem. Also the text block you're trying to exclude MUST end with a blank line with no indents. Also pay attention to indents - sometimes you need to indent your ONLY to match the piece you're trying to include or exclude or you'll get the 'unexpected indent' error. RST is not intuitive.

**Comment by tk0miya** [comment]
I'm closing this because this has been not updated for long time.
