### ISSUE TITLE
Double escaping necessary in some contexts

### ISSUE THREAD

**Issue by benjimin** [sphinx-doc/sphinx#6730]
Markup `'\\'` is rendered as `‘'` instead of `‘\’`. (The first apostrophe is converted to a left quotation mark, no backslash is rendered, and the second apostrophe remains straight.)

It seems like if there were two passes of escape parsing (one pass overzealously consuming every unpaired backslash, then a more-limited separate pass which can prevent _smartquotes_ transformations). Double-escaping of backslashes is necessary if immediately followed by certain punctuation marks, but elsewhere single-escaping of backslashes is sufficient.

A related problem is that single escaping should be sufficient to prevent curling of a straight apostrophe (or double quote symbol), but instead produces no effect.

**Example 1: _ipython_ docs:**
https://ipython.readthedocs.io/en/7.8.0/interactive/reference.html#caution-for-windows-users
https://github.com/ipython/ipython/blob/7.8.0/docs/source/interactive/reference.rst
(These docs are autogenerated by readthedocs; I also reproduced the problem locally by building latest ipython docs using sphinx 2.2.0 on python 3.6.7, and using the vi text editor to inspect the html that was built. Note the github .rst reader is not affected.)

**Example 2:**
Input:
```
Example 'with quotes' and "double quotes" and many's apostrophes'
Escaped apostrophe \' or \\'
Double escaped slash '\\\\'
Not just punctuation '\\x' or \x
```
Output:
```
Example ‘with quotes’ and “double quotes” and many’s apostrophes’
Escaped apostrophe ‘ or '
Double escaped slash ‘\’
Not just punctuation ‘\x’ or x
```
- Double-escaping (`\\\\`) is necessary to produce the original intended output. 
- Apostrophes (') are converted to left or right single quotation marks, and quotation marks (") are converted to left or right double quotation marks.
- Single-escaping of the backslash does work if it is not immediately followed by a punctuation symbol.
- Double-escaping of a straight apostrophe prevents it from transforming into an angled mark.

**Comment by benjimin** [comment]
Also replicated with a fresh project consisting of a blank/empty `conf.py` file and an `index.rst` consisting of e.g.:
```
Hello 'World' ...

'\' '\\' '\\\' '\\\\'

"\" "\\" "\\\" "\\\\"
```
Output includes `“” “" “" “\”`.

Note, behaviour clearly contradicts reST docs: http://docutils.sourceforge.net/docs/user/rst/quickref.html#escaping

**Comment by tk0miya** [comment]
This is intended behavior of Smart Quotes feature. It's not a bug. If you don't like to convert them and keep them as single quotes, you can disable it with `smartquotes = False` in your `conf.py`.
http://docutils.sourceforge.net/docs/user/smartquotes.html

**Comment by benjimin** [comment]
I think a more desirable behaviour would be:

1. `\'` and `\"` render as a straight symbols `'` and `"` (temporarily disabling smartquotes). Note that there is no other reason to escape an apostrophe/quotation mark (it otherwise currently does nothing). 

2. `"\\"` renders as `"\"` (when smartquotes is off) and as `“\”` (when smartquotes is on), for greater consistency with the explicit reST docs/spec.

As far as I'm aware, nowhere in the current documentation is double-escaping described to temporarily disable smartquotes.

**Comment by benjimin** [comment]
Note that the current behaviour is problematic for widely used projects such as IPython. 

Since the github rst reader and the sphinx-generated ReadTheDocs would expect completely different syntaxes, it reduces the usefulness of the documentation (as some users will inevitably see erroneous rendering). It causes meaningful errors (i.e. displaying a quote mark where the author instead intended to describe a slash) which turn documentation into incorrect nonsense (as in the example I linked above). 

This behaviour is unexpected (as few users would anticipate this sort of non-obvious consequence from toggling a beautify-typography option for the top-level project) and unnecessary (because there is no barrier to implementing a more consistent and desirable behaviour instead). 

Is this something the maintainers would like to see a PR for, or is it something the maintainers don't want to change?

**Comment by tk0miya** [comment]
Sphinx uses docutils as a parser of reStructuredText. docutils is a standard implementation of reStructuredText itself. So it is not specific behavior of Sphinx. And it is hard to fix from Sphinx side.
I think docutils project is appropriate to discuss more about this case.
