### ISSUE TITLE
URL-like text is always turned into a hyperlink for PDF output

### ISSUE THREAD

**Issue by jessetan** [sphinx-doc/sphinx#6736]
**Describe the bug**
Any text that looks like a URL (with or without`http(s)://`) is turned into a clickable hyperlink when creating PDF output. That includes text in literals and code blocks.
This is different from HTML output that only creates a clickable hyperlink for `http://www.example.com`-style URLs that are part of normal text (not literal or code block)

**To Reproduce**
Use the following as input:

```rst
This is a URL without http: www.example.com

This is a URL in literal without http: ``www.example.com``

This is a URL in a code block without http:

.. code-block:: none

    www.example.com


This is a URL with http: http://www.example.com

This is a URL in literal with http: ``http://www.example.com``

This is a URL in a code block with http:

.. code-block:: none

    http://www.example.com
```

In HTML output, only the `http://www.example.com` in the fourth line (after the code block) is clickable.
In PDF output, all URL-like text is a clickable hyperlink. This includes code blocks and literals.

**Expected behavior**
PDF output has only one clickable link, just like the HTML output.
At the very least, URLs inside literals and code blocks should not be clickable.

**Environment info**
- Sphinx version: 1.8.6 and 2.2.0

**Comment by tk0miya** [comment]
It seems `hyperref` package automatically make URL-like strings clickable.
```
\documentclass{report}
\usepackage{hyperref}
\begin{document}
  Is www.example.com a hyperlink?
\end{document}
```

I read the document of hyperref, but I can't find the option to disable the feature...

@jfbu Do you know the way to do that?

**Comment by jfbu** [comment]
@tk0miya I did not look yet at OP, but regarding your example, it may be a feature of PDF viewer.

I get indeed this effect even without hyperref, from this:

```latex
\documentclass{report}
%\usepackage{hyperref}
\begin{document}
  Is www.example.com a hyperlink?
\end{document}
```

and opening the PDF in Skim.app on Mac OS X, here is a screenshot

![Capture d’écran 2019-10-14 à 20 03 18](https://user-images.githubusercontent.com/2589111/66772856-f9e0ce00-eebd-11e9-8c2c-4a16b8390170.png)

Again, this is from a PDF produced via `pdflatex` on the source above not loading `hyperref`. I also tried in Adobe Reader and the link is clickable there too.

@jessetan I thus suspect your issue is one of PDF viewer

**Comment by jfbu** [comment]
@jessetan Thanks for report but this is not under Sphinx control. It is a feature of the PDF viewers. I took your source. As you can see only one ``http://www.example.com`` is colored, meaning it was configured as an hyperlink. All the others are not, and it is the PDF viewer which recognizes a potential hyperlink.

![Capture d’écran 2019-10-14 à 21 09 21](https://user-images.githubusercontent.com/2589111/66776730-58f71080-eec7-11e9-841f-5dbccfc2d8cd.png)

**Comment by jessetan** [comment]
Thanks @jfbu, I didn't know about that hidden feature :)

**Comment by jfbu** [comment]
@jessetan I observe the same in Apple Mail:

![Capture d’écran 2019-10-15 à 12 01 21](https://user-images.githubusercontent.com/2589111/66821961-9d27f680-ef43-11e9-8b03-55faca408ef7.png)

whereas the text/html raw source of message in quoted-printable  is only like this

```
t is a feature of the PDF viewers. I took your source. As you can see only =
one <code>http://www.example.com</code> is colored, meaning it was configur=
ed as an hyperlink. All the others are not, and it is the PDF 
```

:)

**Comment by jfbu** [comment]
we see Apple Mail then has difficulties with the literal-block in my previous reply:

![Capture d’écran 2019-10-15 à 12 08 40](https://user-images.githubusercontent.com/2589111/66822485-9cdc2b00-ef44-11e9-9fca-c7bf94f480eb.png)

**Comment by tk0miya** [comment]
Oh, I also misunderstood. Surely Preview.app and Google-Chrome consider URL-like text as a hyperlink. But firefox consider it as mere text.

@jfbu Thanks!
