### ISSUE TITLE
Compiling with Sphinx v1.8.5 on readthedocs fails with "NotImplementedError: Unknown node: autosummary_table"

### ISSUE THREAD

**Issue by sdomanskyi** [sphinx-doc/sphinx#6737]
I am trying to use Sphinx v1.8.5 with readthedocs extension ``autodocsumm``. The build on local machine succeeds but fails on readthedocs with message:

> ...
Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyiomica/envs/latest/lib/python3.7/site-packages/sphinx/writers/html5.py", line 848, in unknown_visit
    raise NotImplementedError('Unknown node: ' + node.__class__.__name__)
NotImplementedError: Unknown node: autosummary_table

The extension ``autodocsumm`` is included in ``conf.py``:
```
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.doctest',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.imgmath',
    'sphinx.ext.ifconfig',
    'sphinx.ext.viewcode',
    'sphinxcontrib.images',
    'sphinx.ext.autosummary',
    'autodocsumm',
]
```

and the requirements file also has the module ``autodocsumm``:
```
autodocsumm>=0.1.11
```

To use this extension I include in the ``conf.py``:
```
autodoc_default_options = {
    'autosummary': True,
}
```
Am I missing something simple to fix this?

[error log from readthedocs.txt](https://github.com/sphinx-doc/sphinx/files/3730417/error.log.from.readthedocs.txt)

[requirements.txt](https://github.com/sphinx-doc/sphinx/files/3730425/requirements.txt)

**Comment by tk0miya** [comment]
Please ask to autodocsumm project. It is hard to answer to this question because I don't know what is the extension doing. Please let me know if autosummary raises error without it.

**Comment by tk0miya** [comment]
Note:
This is issue tracker for Sphinx, not a forum. Please post a question to  https://groups.google.com/forum/#!forum/sphinx-users.
Thanks,

**Comment by sdomanskyi** [comment]
> Please ask to autodocsumm project. It is hard to answer to this question because I don't know what is the extension doing. Please let me know if autosummary raises error without it.

Actually I have just tried **without** that extension (which uses autosummary too) and the build fails the same way. So looks like the problem is with ``sphinx.ext.autosummary``

**Comment by sdomanskyi** [comment]
The bug occurs at this step (sphinx generating epub docs version):

`python /home/docs/checkouts/readthedocs.org/user_builds/pyiomica/envs/latest/bin/sphinx-build -T -b epub -d _build/doctrees-epub -D language=en . _build/epub`

On my local machine I didn't generate epub, thus the build was successful.
Now I disable epub format on ReadTheDocs and keep only pdf, build is successful too.

**Comment by tk0miya** [comment]
Okay, reopened. I'll take a look later.
