### ISSUE TITLE
Could not import extension sphinx.ext.pngmath (exception: No module named 'sphinx.ext.pngmath')

### ISSUE THREAD

**Issue by bbg221** [sphinx-doc/sphinx#6739]
exception occurred when I use 'make html' to build a doc which I download from opencv git-project.
Could not import extension sphinx.ext.pngmath (exception: No module named 'sphinx.ext.pngmath')

I use 'pip install -U sphinx' to install it and its version is v2.2.0 and my python version is 3.7.0 , OS is win7

when I use sphinx to make html, it faild. 
I write 'import  sphinx'  and 'import sphinx.ext.doctest' into python command line. all these two lines are worked.
but I write 'import sphinx.ext.pngmath', it faild. show the error:  ModuleNotFoundError: No module name 'sphinx.ext.pngmath'

**Comment by tk0miya** [comment]
pngmath extension was deprecated at Sphinx-1.6 and removed at 1.8. Now `sphinx.ext.imgmath` is a successor of pngmath. Please update your configuration list.
Thanks,
