### ISSUE TITLE
:end-before improvement for literalinclude

### ISSUE THREAD

**Issue by avarga** [sphinx-doc/sphinx#6742]
With `literalinclude`, `:end-before:` would be more useful if started matching *after* the first line of the block so that it doesn't generate an empty block.

Illustration:

My input file has the usual ini file syntax, and I want to quote one section in the page. (Similar examples would include quoting one class or struct from a source file containing several class/struct definitions, or generally, quoting from one delimiter line up to the next similar delimiter line). The input file:

```
# file someconfig.ini
[Config Foo]
one = 111
two = 5543
three = 23

[Config Bar]
four = 444
etc = 345
```

And the document source:

```
.. literalinclude:: someconfig.ini
   :start-at: Config Foo
   :end-before: Config
```

Currently it produces an empty block because `:end-before:` matches immediately, but it would be much better if it stopped at the `[Config Bar]` line and included the whole `Foo` section. The current behavior is not that useful (who wants to purposefully add an empty block in the output?)

**Comment by tk0miya** [comment]
+1: Reasonable. I agree nobody wants to match `end-before` pattern to the beginning line of the block (On the other hand, `end-at` should match it).

**Comment by avarga** [comment]
Great, thanks!
