### ISSUE TITLE
Prolog definition breaks/omits the translation from existing po files

### ISSUE THREAD

**Issue by FreeHarry** [sphinx-doc/sphinx#6743]
**Describe the bug**
If you define a `prolog` in the `conf.py` NO translation is done from existing po files. Without a `prolog` definition all runs well and translation is done. This problem exist only with the `prolog` not with the `epilog`. My current work around is to write the HTML metadata I wish to integrate in the epilog and all works.

**To Reproduce**
Steps to reproduce the behavior (slice of my conf.py):
```python
# Definition of the prolog to integrate HTML metadata in each file
rst_prolog = """
.. meta::
   :http-equiv=X-UA-Compatible: IE=edge
"""

# Language definition
language = 'de'
```
**Expected behavior**
A  `prolog` definition should NOT break/omit the translation process.

**Environment info**
- OS: Windows 10
- Python version: 3.7.5
- Sphinx version: 2.2.0
- Sphinx extensions: sphinx-intl
- Extra tools:

**Comment by tk0miya** [comment]
Sorry for inconvenience. I hope #6746 fixes your problem. Please check it.
Thanks,

**Comment by FreeHarry** [comment]
#6746 solves the problem and works for me. Thanks!

**Comment by tk0miya** [comment]
Thank you for confirmation! Now merged. It will be released in next release.
