### ISSUE TITLE
[docs][ext] Emphasise that one shouldn't put their node child classes in `conf.py`

### ISSUE THREAD

**Issue by webknjaz** [sphinx-doc/sphinx#6751]
**Describe the bug**

Docs don't mention that I absolutely must put the extension into a separate module file. As a result (knowing that things are supposed to work the same way) I was trying to have a custom directive declared in `conf.py`. This resulted in me wasting a lot of time and postponing completing the extension several times because when I just imported `nodes` "it worked" and it crashed when I inherited them.

Turns out, that there are at least these two issues reported: https://github.com/sphinx-doc/sphinx/issues/1493 / https://github.com/sphinx-doc/sphinx/issues/1424#issuecomment-68588465.
But they are hard to find for some reason and retrieving the solution from them is not trivial when you don't understand the cause of the problem.

**To Reproduce**

Create an extension in `conf.py` instead of a separate module as the tutorial suggests (but not insists).

**Expected behavior**

No pickling error. Or at least: **clear explanation and warning in docs about this problem**.
Also, I'm pretty sure that Sphinx can be changed to provide a more comprehensive background in the error message.

**Your project**

This was in the sibling `conf.py` originally: [scm_tag_titles_ext]

**Screenshots**

N/A

**Environment info**
- OS: Gentoo Linux
- Python version: 3.7.4
- Sphinx version: 2.2.0
- Sphinx extensions: 
  * sphinx.ext.autodoc
  * sphinx.ext.extlinks
  * sphinx.ext.intersphinx
  * [jaraco.packaging.sphinx](https://github.com/jaraco/jaraco.packaging/blob/master/jaraco/packaging/sphinx.py)
  * [sphinx_tabs.tabs](https://github.com/djungelorm/sphinx-tabs)
  * [scm_tag_titles_ext] (the extension I was developing)
 [e.g. sphinx.ext.autodoc, recommonmark]
- Extra tools: [tox](https://github.com/cherrypy/cheroot/blob/76cbe69ecfd2a3a5d8793a9b97c9c50eb95310e0/tox.ini#L33-L57) (just as a build runner)

**Additional context**

- https://github.com/sphinx-doc/sphinx/issues/1493
- https://github.com/sphinx-doc/sphinx/issues/1424#issuecomment-68588465

[scm_tag_titles_ext]: https://github.com/cherrypy/cheroot/blob/76cbe69ecfd2a3a5d8793a9b97c9c50eb95310e0/docs/scm_tag_titles_ext.py

**Comment by tk0miya** [comment]
From my understanding, it is hard to prevent PicklingError because `conf.py` is not loaded as python module. It is loaded as on-memory script via `compile()` function. In other words, it is eval'ed.
So I think updating document is good for this.

**Comment by webknjaz** [comment]
There are a few tutorial pages. Do you know where is the most appropriate place for adding this info?

**Comment by tk0miya** [comment]
I think todo extension is better to mention about this because it uses custom nodes. Other tutorials do not use it.
https://www.sphinx-doc.org/en/master/development/tutorials/todo.html

**Comment by webknjaz** [comment]
@tk0miya do you think this https://github.com/sphinx-doc/sphinx/pull/6754 will be enough?
