### ISSUE TITLE
Adding the ability to globally exclude all property/static methods in autodoc

### ISSUE THREAD

**Issue by topspinj** [sphinx-doc/sphinx#6755]
**Is your feature request related to a problem? Please describe.**
I would like to exclude all property and static methods from my documentation. Currently, I need to list these in `:exclude-members:` which is a very manual cumbersome process and prone to error. 

**Describe the solution you'd like**
It would be great if there was a way to exclude all members of a certain decorator (e.g., `@static`, `@property`). 

**Describe alternatives you've considered**
It seems like an alternative approach is to remove docstrings for all static/property methods and exclude `undoc` from autoclass. This is not an option for my scenario as I'd like to keep these docstrings in the code for development purposes.

**Comment by tk0miya** [comment]
I feel your usage is not common. So -1 for adding a new option for that purpose. But you can do it with custom handler for `autodoc-skip-member` event. 
https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#event-autodoc-skip-member

Thanks,
