### ISSUE TITLE
autoAPI for go is failing with Python 3

### ISSUE THREAD

**Issue by kakwon** [sphinx-doc/sphinx#6757]
When trying to create the API documentation for a go project using python 3.5, it fails with the following errors:

Exception occurred:
  File "/usr/local/lib/python3.5/dist-packages/sphinxcontrib/golangdomain.py", line 327, in generate
    packages = sorted(self.domain.data['packages'].iteritems(),
AttributeError: 'dict' object has no attribute 'iteritems'

It also fails in this same way on like 376.

**Comment by tk0miya** [comment]
The `iteritems()` method was deprecated and removed in python2. It means the golangdomain extension does not support python3. Please report this into their project.
Thanks,
