### ISSUE TITLE
Support validation of references

### ISSUE THREAD

**Issue by oliver-sanders** [sphinx-doc/sphinx#6761]
**Describe the problem**
Referencing objects using Sphinx domains is great:

```rst
You can find out who you are from the :envvar:`USER` environment variable.
```

Referencing objects in this way gives us:
* Consistency of presentation.
* Links to the relevant documentation if present.

Often we are documenting the things that we are referencing:

```rst
.. envvar:: FOO

   Documentation for FOO.

.. envvar:: BAR

   Documentation for BAR.

* Functional reference :envvar:`FOO`.
* Misspelt reference :envvar:`F00`.
* Reference to removed configuration :envvar:`BAZ`.
```

For this sort of usage it would be really helpful if Sphinx produced a warning to let us know when we are referencing objects which don't exist.

Integrity checks like this are one of the big bonuses of using a system like Sphinx, benifits:
* Prevent documentation from getting out of date by referencing long removed configurations etc.
* Catch typos.

I've implemented validation in a custom Sphinx Domain I wrote for a configuration language by adding a few lines to the `resolve_xref` method:

```python
def resolve_xref(self, env, fromdocname, builder, typ, target, node, contnode):
    # ...
    try:
        data = self.data['objects'][namespace]
    except KeyError:
        # Object being referenced doesn't exist, raise a warning.
        LOGGER.warning('No Ref for "%s"' % namespace, location=node)
        return None
```

**Describe the solution you'd like**

A way of telling Sphinx to raise warnings when referencing objects which don't exist.

For bonus marks if Sphinx could raise a warning when you reference objects which have been marked with `:deprecated:` flags that would be incredibly helpful.

Options:

1. Global Configuration.

    Not a good idea as projects might want to validate some references and not others.

2. A Syntax Solution

    Perhaps something along the lines of:
    ```rst
    .. Don't check the reference
    :envvar:`HOME`
    .. Do check the reference
    :envvar:`*FOO`
    ```

    Better still if the user could configure which domains validation is turned on for "by default" in the global configuration.

3. A new "Role"

    ```rst
    :ref:envvar:`FOO`
    ```

4. Other ideas?

**Describe alternatives you've considered**

Writing / modifying Sphinx domains is a fragile solution which doesn't allow easy changing between validating and not validating.

**Additional context**

None

**Comment by jakobandersen** [comment]
If I understand your suggestion correctly, then the global-option solution already exists in form of the nit-picky mode: give ``-n`` to ``sphinx-build``.
However, this can spew a lot of warnings that were not intended. My own hax to hide them is to have a small extension that intercepts all missing references and raises ``NoUrI`` for those that should be ignored: https://github.com/jakobandersen/mod/blob/develop/doc/source/extensions/ignore_missing_refs/__init__.py

**Comment by oliver-sanders** [comment]
> global-option solution already exists in form of the nit-picky mode

Brilliant! That should be the default!

> My own hax to hide them

Helpful, thanks.

So it's just the "local" side of things left to handle, cases like this:

```rst
Do the following::

   $ # ...
   $ BASE=~/foo

Note :envvar:`BASE` is set to the path of ...
```
I guess the simple workaround is just:

```rst
Note ``BASE`` is set to the path of ...
```

**Comment by jakobandersen** [comment]
Right, though it is debatable whether that should work or if the workaround is actually the correct solution, it depends. Generally the reference roles are meant to link to the declaration of some entity, where it is documented, so if ``BASE`` is an example variable I then using literal text is probably correct. If ``BASE`` is documented somewhere, then a reference role is probably correct.

**Comment by oliver-sanders** [comment]
OK, feel free to close this issue (or edit / re-open under a different name).

**Comment by jakobandersen** [comment]
Ok, I'll close for now, but feel free to re-open if some use cases are not covered.
