### ISSUE TITLE
Documentation for <packages> field in latex.tex_t

### ISSUE THREAD

**Issue by romintomasetti** [sphinx-doc/sphinx#6762]
**Problem description leading to this feature request**
When using `make latexpdf` (or any latex-related), it may be interesting to add extra packages to the preamble.

However, when adding packages via the `preamble` field of the `latex_elements`, they are added after the `hyperref` package.

This may lead to unwanted results with the 
```
\usepackage[makeindex]{imakeidx}
\usepackage[columns=1]{idxlayout}
```
for instance. Indeed, these commands will be added after the `hyperref` package, resulting in an incomplete `.ind` file (instead of `\hyperpage{9}` one would only get `9`).

**Is their a workaround? Yes.**
The workaround I use for the moment is to add
```
\usepackage[makeindex]{imakeidx}
\usepackage[columns=1]{idxlayout}
```
in the `passoptionstopackages` field of `latex_elements`.

**Proposed solution**
I looked at [https://github.com/sphinx-doc/sphinx/blob/master/sphinx/templates/latex/latex.tex_t](url), which is the template file I supposed is used by Sphinx. There is (lines 39-45)
```
<%- for name, option in packages %>
<%- if option %>
\usepackage[<%= option %>]{<%= name %>}
<%- else %>
\usepackage{<%= name %>}
<%- endif %>
<%- endfor %>
```
so I tried the key `packages` in the `latex_elements`, resulting in:
> WARNING: Unknown configure key: latex_elements['packages']. ignored.
Solution:
1) Maybe I miss something and it is possible to add packages before `hyperref` with others means (but after reading [https://www.sphinx-doc.org/en/master/latex.html#latex-macros-and-environments](url) I could not find any)
2) Provide a `packages` field that inserts packages where `<%- for name, option in packages %>` is located in the template. That would be great !

**The last word**
Anyway, Sphinx is an amazing tool !

**Comment by tk0miya** [comment]
It has been added for `add_latex_package()` API: 
https://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx.application.Sphinx.add_latex_package

But, as you said, it is better to add latex packages via `latex_elements`.

**Comment by romintomasetti** [comment]
Ok, I missed that since it was not in the `LaTeX customization`  [https://www.sphinx-doc.org/en/master/latex.html](url) page.  Might be great to have `add_latex_package()` there right?
Many thanks for the quick reply though !

**Comment by tk0miya** [comment]
I don't think so. `add_latex_package()` is provided for extension developers. But the page you pointed is mainly for users. I think it is not good to use Sphinx APIs by users. So I'd like to add new option for users.

**Comment by tk0miya** [comment]
We'll add `extrapackages` key to `latex_elements` in next release.
Thanks,
