### ISSUE TITLE
"keyword" py typed field only accept "paramtype" for type

### ISSUE THREAD

**Issue by lmazuel** [sphinx-doc/sphinx#6763]
**Describe the bug**
This code does not document the type:
```python
:keyword foo: This is foo kwarg
:type foo: str or int
```

this one does:
```python
:keyword foo: This is foo kwarg
:paramtype foo: str or int
```

Maybe I misunderstand the [code base](https://github.com/sphinx-doc/sphinx/blob/685e3fdb49c42b464e09ec955e1033e2a8729fff/sphinx/domains/python.py#L196-L200) or the doc, but to me both should work.

**Environment info**
- OS: Windows
- Python version: 3.7
- Sphinx version: 2.2.0
- Sphinx extensions:  sphinx.ext.autodoc, recommonmark
- Extra tools: None

Hope this helps! :)

**Comment by tk0miya** [comment]
If you're enabling napoleon module, keyword field has been modified by it. And it does not match `type` field. I'm not good at napoleon. But it seems this is side effect of the extension.
https://github.com/sphinx-doc/sphinx/blob/a6a2a59ab0abfaf510d3dcbc43231468d3dc1fff/sphinx/ext/napoleon/__init__.py#L325-L328

**Comment by lmazuel** [comment]
Hi @tk0miya 
Are you saying that the support for `keyword` is a side effect and not an official feature? I don't use napoleon

**Comment by tk0miya** [comment]
I can't say what is napoleon's correct behavior. But it is not correct behavior if you're not using napoleon. But I can't reproduce the behavior without napoleon.
If you're still in trouble, please reopen and share your project (or minimal reproducible example). I'll investigate again.
