### ISSUE TITLE
Force autodoc to write file by file (?)

### ISSUE THREAD

**Issue by gpotter2** [sphinx-doc/sphinx#6764]
*I searched the doc & the autodoc module for an answer. If I missed an option please kindly point it to me and close this issue 😄*

**Is your feature request related to a problem? Please describe.**
We are using the autodoc module, which makes `readthedocs.org` run out of ram. During the build: https://readthedocs.org/projects/scapy/builds/9849916/ it appears that sphinx was able to read the entire source & process, but ran out of RAM during the writing of the files.

If my understanding of the inner of Autodoc/sphinx is correct, sphinx:
- reads everything
- writes everything
Which eventually leads to a massive RAM usage.

**Describe the solution you'd like**
Is there a way to force Autodoc to write each file right after it has been read?
I am aware that this might not be easy to implement, (is it even possible?) but it would be extremely useful in our usecase.

If this isn't possible, we might end up asking kindly readthedocs to get more RAM :/

Thanks for your time !

**Comment by gpotter2** [comment]
Putting this on hold to see if we can find some other way before disturbing you guys

**Comment by tk0miya** [comment]
>Is there a way to force Autodoc to write each file right after it has been read?

No. Sphinx need to read all of documents before writing. Because Sphinx needs to build a database of reference targets in all documents to realize cross reference. Processing file by file will disable cross reference, ToC tree and other features around cross-over the documents.
