### ISSUE TITLE
:doc: role doesn't support #anchor

### ISSUE THREAD

**Issue by 2uasimojo** [sphinx-doc/sphinx#6766]
Attempting to build any variant of `:doc:` with an anchor warns (fails to build with -W) with:

```
Warning, treated as error:
/opt/stack/sphinx-test/doc/source/baz.rst:4:unknown document: foo#section-called-bar
```

Examples:

```
- Relative, implicit title: :doc:`foo#section-called-bar`
- Relative, explicit title: :doc:`a thing with an explicit title <foo#section-called-bar>`
- Absolute, implicit title: :doc:`/foo#section-called-bar`
- Absolute, explicit title: :doc:`a thing with an explicit title </foo#section-called-bar>` 
```

foo.rst looks like this:
```
Foo
===

This is a test

Section called bar
------------------
Hello world
```

**Comment by 2uasimojo** [comment]
This patch fixes it, but I don't know how to github :(

http://paste.openstack.org/raw/785557/

**Comment by 2uasimojo** [comment]
Wow, I'm sure I didn't do that right.

**Comment by tk0miya** [comment]
-1: the responsibility of `:doc:` role is to refer a "document", not a section. So I feel this breaks its meaning. If you'd like to refer a section with its title, you can use `sphinx.ext.autosectionlabel` to generate labels for sections automatically. If enabled, you can refer them with `:ref:` role.

**Comment by jdillard** [comment]
If you don't want to use `sphinx.ext.autosectionlabel` you can use [labels](https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#cross-referencing-arbitrary-locations) instead, along with the `:ref:` role. It seems like this issue could be closed now.

**Comment by 2uasimojo** [comment]
a) I'm no longer working on this; and
b) This is far enough in my past that I retain no context, so I have no idea as to the validity of the comments made by @tk0miya or @jdillard, but I'm willing to take their word for it :)
