### ISSUE TITLE
How to include the latest translation from Transifex to next build?

### ISSUE THREAD

**Issue by oonid** [sphinx-doc/sphinx#6767]
Hello,
I just finished translation for the Indonesian language.

I saw that the files in [locale/id/LC_MESSAGES](https://github.com/sphinx-doc/sphinx/tree/master/sphinx/locale/id/LC_MESSAGES) are not updated automatically.

What is the next step to include it in the next version build of Sphinx-Doc?
Is it automatically included in the next build or any documentation I can read to follow the procedure?

thank you.

**Comment by tk0miya** [comment]
Thank you for your contribution. Great work!
We'll merge it on releasing process. So you don't need to  please wait for a next release; Sphinx-2.3.0.

**Comment by oonid** [comment]
Dear @tk0miya 
do you have any information about the release plan for 2.3?

I saw a new release [2.2.2](https://github.com/sphinx-doc/sphinx/releases/tag/v2.2.2) 2 days ago.
But I still have to wait for version 2.3 to get the translation updated.

thank you for your information.

**Comment by tk0miya** [comment]
Please take a look #6745. It will be shipped within 1-2 weeks.
