### ISSUE TITLE
Make apidoc quiet when sphinx is quiet

### ISSUE THREAD

**Issue by dkfellows** [sphinx-doc/sphinx#6772]
**Is your feature request related to a problem? Please describe.**
It's deeply annoying that apidoc always writes messages (e.g., `Creating file ./foobar.rst`) when a documentation build is done in quiet mode (i.e., when the `-q` option is passed to `sphinx-build`). (We use this as part of checking that documentation builds correctly in various configurations in our CI process, running once verbosely and the other times quietly as an insurance policy against something really strange happening. As the project in question is quite large, the unsuppressable messages make understanding the log more irritating than it should be.)

**Describe the solution you'd like**
For all informational messages produced by apidoc to respect the global quietness control, just like all informational messages produced by the rest of Sphinx appear to.

The basic issue appears (to me) to be that a direct `print()` is used directly three times to produce obviously purely informational messages in _sphinx/sphinx/ext/apidoc.py_ in [`write_file`](https://github.com/sphinx-doc/sphinx/blob/fe06eebfb5c2a24f8a0e297aef2e7a5ec82b062c/sphinx/ext/apidoc.py#L76) (link to first instance, other two are a few lines later) rather than channelling through something capable of knowing when a suppression rule should be applied.

I lack knowledge of the internal workings of Sphinx so I can't suggest a patch.

**Comment by tk0miya** [comment]
+1: Reasonable.

**Comment by tk0miya** [comment]
Wait, `sphinx-apidoc` is an independent from `sphinx-build` command. And it does not have any quiet mode. I'm confused now. How did you get into the situation? I can add `-q` option to apidoc, but it seems that does not resolve your request...

**Comment by dkfellows** [comment]
> How did you get into the situation?

Example repository: https://github.com/SpiNNakerManchester/SpiNNMan
Example build long: https://travis-ci.org/SpiNNakerManchester/SpiNNMan/jobs/637444008
Configuration file: https://github.com/SpiNNakerManchester/SpiNNMan/blob/master/doc/source/conf.py

(We have other, much larger, repositories with the same issues, but they also have much _much_ larger CI build output logs and I think you're not interested in wading through all that irrelevant stuff.)

Specific command line of interest:
```
sphinx-build -q -T -b json -d _build/doctrees-json -D language=en . _build/json
```
Associated _unwanted_ output:
```
Creating file ./spinnman.rst.
Creating file ./spinnman.connections.rst.
Creating file ./spinnman.connections.abstract_classes.rst.
Creating file ./spinnman.connections.udp_packet_connections.rst.
Creating file ./spinnman.messages.rst.
Creating file ./spinnman.messages.eieio.rst.
Creating file ./spinnman.messages.eieio.command_messages.rst.
Creating file ./spinnman.messages.eieio.data_messages.rst.
Creating file ./spinnman.messages.scp.rst.
Creating file ./spinnman.messages.scp.abstract_messages.rst.
Creating file ./spinnman.messages.scp.enums.rst.
Creating file ./spinnman.messages.scp.impl.rst.
Creating file ./spinnman.messages.sdp.rst.
Creating file ./spinnman.messages.spinnaker_boot.rst.
Creating file ./spinnman.messages.spinnaker_boot.boot_data.rst.
Creating file ./spinnman.model.rst.
Creating file ./spinnman.model.enums.rst.
Creating file ./spinnman.processes.rst.
Creating file ./spinnman.utilities.rst.
Creating file ./spinnman.utilities.io.rst.
File ./modules.rst already exists, skipping.
```
Any actual warnings are, of course, highly relevant to us. It's those other progress-only messages that are unwanted (when the build is asked to be quiet with `-q`) because they contribute to problems being missed.

**Comment by tk0miya** [comment]
It seems you're invoking apidoc via your code. We can't support your case...
https://github.com/SpiNNakerManchester/SpiNNMan/blob/885147cb3d871e00d13c3559e4248d0135ba238e/doc/source/conf.py#L369

**Comment by tk0miya** [comment]
I'll add `-q` option to sphinx-apidoc in #7078. Then you can control it in your code.
Thanks,

**Comment by tk0miya** [comment]
I added `-q` option to sphinx-apidoc in #7078. So you'll control it via your code in next release.
Thanks,
