### ISSUE TITLE
NBConvert 6.0 Changes

### ISSUE THREAD

**Issue by MSeal** [sphinx-doc/sphinx#6773]
**Is your feature request related to a problem? Please describe.**
With nbconvert development of master branch now working towards [6.0](https://github.com/jupyter/nbconvert/issues/1045) there's likely some upcoming compatibility issues with the changes.

**Describe the solution you'd like**
It seems that the master branch of nbconvert with some early 6.0 changes will break sphinx template tasks. I added specific details at the bottom about what these changes are.

I'm not sure how you'll want to prep sphinx for the changes, but I imagine an nbconvert 6.0 branch or code path will be needed to account for the changes. Likely this would need a branch first to prove it out and discover any open issues at a minimum.

**Describe alternatives you've considered**
If there's tweaks needed in nbconvert ahead the big release to make sphinx's upgrade easier we're open to helping making such changes.

**Additional context**
https://github.com/jupyter/nbconvert/issues/1126 raised that their accidental pin to master had failures in this manner. Specifically https://github.com/jupyter/nbconvert/pull/1028 reorganized templates with a large change to make viola and nbconvert more compatible with each other (and make templates better overall). Some of the other coming changes may also cause minor issues as they're being made. We're allowing more dramatic changes to the library given it's a major version change.

**Comment by tk0miya** [comment]
I still don't understand what we should do. Is there anything to do from Sphinx side? Are you saying https://github.com/jupyter/nbconvert/issues/1126 is a bug of Sphinx core?

**Comment by mgeier** [comment]
I don't think anything can be done from the Sphinx side, see https://github.com/jupyter/nbconvert/issues/1126#issuecomment-546581707.

**Comment by tk0miya** [comment]
Okay, I understand. Thank you for your help :-)

**Comment by MSeal** [comment]
Thanks for taking a look. I wasn't sure if Sphinx had hardcoded template names or direct imports that might be impacted. I mostly wanted to give a heads up about the upcoming changes so you all would be aware as there's a lot of Sphinx usage with nbconvert involved in various projects

**Comment by tk0miya** [comment]
I think it is better to post such announcement to  sphinx-users group. Then users will catch up the news and changes.
Anyway, thank you for information. I'm looking forward to see new package :-)
