### ISSUE TITLE
link check fails with GitHub blob pages

### ISSUE THREAD

**Issue by banesullivan** [sphinx-doc/sphinx#6779]
**Describe the bug**
Running linkcheck returns the following link as `broken`: https://github.com/pyvista/pyvista/blob/master/CONTRIBUTING.md#testing

```
...
(line  101) broken    https://github.com/pyvista/pyvista/blob/master/CONTRIBUTING.md#testing - Anchor 'testing' not found
...
```

**To Reproduce**
```
<Paste your command-line here which cause the problem>

$ git clone https://github.com/pyvista/pyvista
$ cd pyvista
$ git checkout linkcheck
$ pip install -r requirements.txt
$ pip install -r requirements_docs.txt
$ pip install -e .
$ cd docs
$ make html -b linkcheck
```

**Expected behavior**
 That link is good, please don't mark it as broken.

**Your project**
https://github.com/pyvista/pyvista

**Environment info**
- OS: MacOS Catalina
- Python version: 3.7.3
- Sphinx version: 2.1.2
- Sphinx extensions: n/a
- Extra tools: n/a

**Additional context**
https://github.com/pyvista/pyvista/pull/426

https://travis-ci.org/pyvista/pyvista/jobs/604662852#L2343

**Comment by tk0miya** [comment]
AFAIK, github uses a trick for HTML anchors. In HTML, there are no `testing` anchor. And we can find `user-content-testing` anchor instead.
```
$ curl -s -L -o - https://github.com/pyvista/pyvista/blob/master/CONTRIBUTING.md | grep 'id="testing"'
$ curl -s -L -o - https://github.com/pyvista/pyvista/blob/master/CONTRIBUTING.md | grep 'id="user-content-testing"'
<h2><a id="user-content-testing" class="anchor" aria-hidden="true" href="#testing"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M4 9h1v1H4c-1.5 0-3-1.69-3-3.5S2.55 3 4 3h4c1.45 0 3 1.69 3 3.5 0 1.41-.91 2.72-2 3.25V8.59c.58-.45 1-1.27 1-2.09C10 5.22 8.98 4 8 4H4c-.98 0-2 1.22-2 2.5S3 9 4 9zm9-3h-1v1h1c1 0 2 1.22 2 2.5S13.98 12 13 12H9c-.98 0-2-1.22-2-2.5 0-.83.42-1.64 1-2.09V6.25c-1.09.53-2 1.84-2 3.25C6 11.31 7.55 13 9 13h4c1.45 0 3-1.69 3-3.5S14.5 6 13 6z"></path></svg></a>Testing</h2>
```

I don't know why browsers can link such anchor by `#testing`. I guess some JavaScript codeis working. So we need to add "user-content-" prefix to match it.

**Comment by fepegar** [comment]
Hello! Have you found a way to fix/ignore these errors?

**Comment by tk0miya** [comment]
Nothing changed. I think there is nothing to do from Sphinx side because it would use JS scripts to realize focusing anchors. So I'm closing this now. Thanks,
