### ISSUE TITLE
Add PEP-561 Support by adding a py.typed file

### ISSUE THREAD

**Issue by lewis6991** [sphinx-doc/sphinx#6780]
I'm trying to run the latest mypy on a sphinx extension I am writing and mypy is giving the error:

`error: Cannot find module named 'sphinx'`

However looking at the source code for a lot of sphinx, it appears much of the code includes type annotations. The mypy [docs](https://mypy.readthedocs.io/en/latest/installed_packages.html#making-pep-561-compatible-packages) state that if source code includes annotations in the source then a package can be made PEP-561 compatible by adding a `py.typed` file.

I tried this myself by adding a `py.typed` file to the `sphinx` directory in my `site-packages` and now mypy is happy.

This may be related to #4824

**Comment by tk0miya** [comment]
Could you send a pull request please? Then I'll ship it in next release.

Note: 2.0 branch is good for this.
