### ISSUE TITLE
Customize pot header

### ISSUE THREAD

**Issue by tisonkun** [sphinx-doc/sphinx#6781]
```
# SOME DESCRIPTIVE TITLE.
# Copyright (C) 2019, TubeMQ Team
# This file is distributed under the same license as the TubeMQ package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2019.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: TubeMQ \n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2019-10-29 20:40+0800\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.7.0\n"
```

I'd like to customize LICENSE header as well as no `"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"` and `"Language-Team: LANGUAGE <LL@li.org>\n"` and `# FIRST AUTHOR <EMAIL@ADDRESS>, 2019.`

Is there an option to do that instead of manually remove then from generated?

ref https://github.com/sphinx-doc/sphinx-intl/issues/36

**Comment by tk0miya** [comment]
At present, there are no options to customize the header.

+1 for your idea.

**Comment by tisonkun** [comment]
Thanks for your attention @tk0miya . For me it doesn't matter that I have to do it myself but auto generation `make gettext` will overwrite my customized info[1] so that I have to do it every generation. The latter is quite a bit annoying though QAQ

[1] accurately, from my observation, the LICENSE header is not changed(however, possibly padding empty line above the LICENSE) but "authour" info(I think the whole fuzzy section) is overwritten.

**Comment by shimizukawa** [comment]
No objections from me.

**Comment by tisonkun** [comment]
Seems we reaches a consensus here. I'm not sure how to implement the functionality. Do you have a plan?

**Comment by tk0miya** [comment]
I'll work for it soon. As a preparation, I just posted a PR #6802 now.

**Comment by tk0miya** [comment]
In #6919, I added new config variables: `gettext_last_translator` and `gettext_language_team`.
I hope they help you.
Thank you for reporting.
