### ISSUE TITLE
sphinx-quickstart should use a distinctive build directory name for benefit of svn/gitignores

### ISSUE THREAD

**Issue by ben-spiller** [sphinx-doc/sphinx#6786]
**Is your feature request related to a problem? Please describe.**
Currently when you run sphinx-quickstart you end up with a generated directory called _build. 

Since that name doesn't include the word sphinx some projects will be unable or reluctant to add it to their global gitignores (in case there is some non-sphinx directory with that name). 

**Your project**
Link to your sphinx project, or attach zipped small project sample.

**Describe the solution you'd like**
sphinx-quickstart should use a distinctive name such as _sphinxbuild for the output directory

**Describe alternatives you've considered**
Can be customized in the make.bat/Makefile on a per-project basis - but having a distrinctive default name in widespread use would encourage good practice, and allow _sphinxbuild to be added to gitignores for new Python (and other) projects by default.

**Comment by tk0miya** [comment]
-1: You can ignore the build directory with settings like `docs/_build`. I think `_build` has been in widespread use.

**Comment by ben-spiller** [comment]
Yep you make a good point I'm retracting this :)
