### ISSUE TITLE
Including a document with :orphan: at the top prints orphan:

### ISSUE THREAD

**Issue by Helveg** [sphinx-doc/sphinx#6787]
**Describe the bug**
Document metadata can be added as a field list at the top of a document, and adding the :orphan: metadata works in silencing the 'not in toc' error, but when using the `include` directive on this document, it prints `orphan:` and then the rest of the document, but the `orphan:` part should not be printed!

**To Reproduce**
Create 2 documents, add `:orphan:` to one and include this in the other document

**Environment info**
- OS: Windows 10
- Python version: 3.7.4
- Sphinx version: 1.8.5

**Comment by tk0miya** [comment]
Since Sphinx-1.4, Sphinx does not emit a "orphan" warning for included document. So you don't need to mark it as ":orphan:". So I feel such feature is not needed now.

**Comment by Helveg** [comment]
@tk0miya It does issue this warning if I remove the :orphan: label

```
checking consistency... C:\Users\robin\Documents\GIT\scaffold-model\docs\source\configuration\standard-placement-attributes.rst: WARNING: document isn't included in any toctree
```

**Comment by tk0miya** [comment]
Hmm... that's strange. It's a bug of Sphinx. Could you share your project or small example? I'd like to take a look it to investigate the bug.

**Comment by Helveg** [comment]
When creating a minimal example for you, the page indeed stops throwing the warning if it is included. Most likely I made a mistake when investigating this issue earlier.

**Comment by tk0miya** [comment]
Thank you for confirmation. I guess this behavior might be related with windows path separator. If you're still in trouble, please check it. Thanks,
