### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '}'

### ISSUE THREAD

**Issue by techwanker** [sphinx-doc/sphinx#6791]
**Describe the bug**

Exception occurred:
  File "/usr/lib/python2.7/site-packages/docutils/utils/math/math2html.py", line 5117, in parsebit
    self.number = int(pos.skipcurrent())
ValueError: invalid literal for int() with base 10: '}'
The full traceback has been saved in /tmp/sphinx-err-3u3yb2.log, if you want to report the issue to the developers.

**To Reproduce**
```
<Paste your command-line here which cause the problem>
git clone https://github.com/techwanker/bash-scripts.git
cd bash-scripts/generated-docs
make html
```

**Expected behavior**
expected _build/html/index.html and associated files

**Your project**
https://github.com/techwanker/bash-scripts.git

**Environment info**
- OS: [linux centos 7]
- Python version: [e.g. 2.7.5]
- Sphinx version: [e.g. 1.1.3] this is what I get with yum upgrade 
- Sphinx extensions:  [e.g. sphinx.ext.autodoc, recommonmark]
- Extra tools: [e.g. Browser, tex or something else]

**Additional context**

**Comment by tk0miya** [comment]
Please upgrade Sphinx to latest. 1.1.3 was released in 7 years ago. I think it was already fixed.
Thanks,
