### ISSUE TITLE
Code examples broken in texinfo output following "sidebar"

### ISSUE THREAD

**Issue by bemoody** [sphinx-doc/sphinx#6793]
Given the input:

```
Welcome to test's documentation!
================================

.. sidebar:: Blah blah

   Indented text.

Example::

   Code example.
   This should appear as two lines.
```

in Texinfo format, the code example should be formatted as:

```
@example
Code example.
This should appear as two lines.
@end example
```

As of version 2.2.1, this instead produces:

```
@example
Code example. This should appear as two lines.
@end example
```

This appears to have been broken between version 1.8.1 and 1.8.2.  Using `git bisect`, it appears to have been broken by commit 84f781252f7ec44e2b13da24ea8c3e34589b414c.

**Comment by tk0miya** [comment]
Fixed by #6579 
Thank you for reporting!
