### ISSUE TITLE
Warnings of stub files not found

### ISSUE THREAD

**Issue by miroli** [sphinx-doc/sphinx#6800]
**Describe the bug**
I get this error message:

`/Users/robinlinderborg/dev/sphinxbug/sphinxbug/app.py:docstring of sphinxbug.app.MyPrintClass.rst:25: WARNING: autosummary: stub file not found 'sphinxbug.app.MyPrintClass.print_msg'. Check your autosummary_generate setting.`

when I run `make html` to generate my documentation. I am using typehints and a couple of extensions described below.

**To Reproduce**
```
$ git clone git@github.com:miroli/sphinxbug.git
$ cd sphinxbug
$ pipenv install --dev
$ make html
$ # Warning message appears
```

**Expected behavior**
No warning message.

**Your project**
https://github.com/miroli/sphinxbug

**Environment info**
- OS: Mac
- Python version: 3.7
- Sphinx version: 2.2.1
- Sphinx extensions:  ['sphinx.ext.autodoc', 'numpydoc', 'sphinx.ext.napoleon', 'sphinx_autodoc_typehints']

**Comment by tk0miya** [comment]
As warning message says, please enable `autosummary_generate` in your `conf.py`.
```
autosummary_generate = True
```

It seems numpydoc extension automatically loads autosummary extension. So the configuration is needed to use it.
For more details, please ask to their project. I'm not familiar to it.
Thanks,

**Comment by miroli** [comment]
I should have mentioned this, but I had already tried that. And it does not resolve the issue.

**Comment by tk0miya** [comment]
Confirmed with following Dockerfile.
```
FROM python:3.7-slim

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

RUN apt update; apt install -y git make
RUN git clone https://github.com/miroli/sphinxbug
WORKDIR /sphinxbug
RUN pip install pipenv
RUN pipenv install --dev
RUN echo '' >> conf.py
RUN echo 'autosummary_generate = True' >> conf.py
RUN pipenv run make html
```

And it seems the error goes away when I remove `numpydoc` entry from extensions list.
I don't know numpydoc doing. But this error is caused by numpydoc...
