### ISSUE TITLE
linkcheck results in "can only concatenate str (not "bytes") to str"

### ISSUE THREAD

**Issue by anntzer** [sphinx-doc/sphinx#6806]
**Describe the bug**
Runnin make linkcheck can result in an "can only concatenate str (not "bytes") to str" error.

**To Reproduce**
```
$ sphinx-quickstart -q -pfoo -afoo
$ rm index.rst
$ echo 'https://www.x.org/releases/X11R7.7/doc/man/man7/X.7.xhtml#heading5' > index.rst
$ make linkcheck
```
results in
```
<elided>

(line    1) broken    https://www.x.org/releases/X11R7.7/doc/man/man7/X.7.xhtml#heading5 - can only concatenate str (not "bytes") to str

build finished with problems.
make: *** [Makefile:20: linkcheck] Error 1
```

**Expected behavior**
Successful linkcheck: https://www.x.org/releases/X11R7.7/doc/man/man7/X.7.xhtml#heading5 is a valid URL, with no redirect whatsoever.

**Your project**
N/A

**Screenshots**
N/A

**Environment info**
- OS: Arch Linux
- Python version: 3.7.4
- Sphinx version: 2.2.1
- Sphinx extensions:  N/A
- Extra tools: N/A

**Additional context**
N/A

**Comment by tk0miya** [comment]
Fixed by #6839 
Thank you for reporting!
