### ISSUE TITLE
Allow numref with no number

### ISSUE THREAD

**Issue by Jellby** [sphinx-doc/sphinx#6811]
**Is your feature request related to a problem? Please describe.**
I'd like hyperlinked references like "see [next section]" or "in the [above figure]"

**Describe the solution you'd like**
The custom format to `numref` looks like it should work, but fails if I give no actual placeholder:

    see :numref:`next section <sec:foo>`...
    in the :numref:`above figure <fig:bar>`...

    WARNING: invalid numfig_format: next section
    WARNING: invalid numfig_format: above figure

I'd just check that the `%s` placeholder is present, and if it isn't, use the text as such.

O course, a plain `` see :ref:`next section <sec:foo>` `` works, but why shouldn't numref too?

**Comment by tk0miya** [comment]
`numref` is an abbreviation of "numbered reference" (or "number reference"). So I feel strange a "numbered reference" without number. Why don't you use `:ref:` instead?

**Comment by Jellby** [comment]
Just for consistency. I'm using `numref` everywhere, and suddenly where I want "next section" instead of "section 5" I must use `ref`. Why couldn't `numref` fall back to `ref` if there is no number?

**Comment by tk0miya** [comment]
I feel "referencing a section by number without number" is inconsistency. It's contradiction in semantics. `:ref:` and `:numref:` are similar, but absolutely different roles. -1 for the change.
