### ISSUE TITLE
Intersphinx could fetch remote inventories concurrently

### ISSUE THREAD

**Issue by Zac-HD** [sphinx-doc/sphinx#6818]
Hypothesis has optional integrations with many other libraries, and [our `intersphinx` config](https://github.com/HypothesisWorks/hypothesis/blob/583db593c5bf2d4d2985aa9d31decf785ad364e8/hypothesis-python/docs/conf.py#L66-L73) currently links to six other sets of documentation.  This works beautifully, and we all really appreciate Sphinx!  ❤️

However, when the cache is cold or doing a clean build, fetching all of these inventories can take considerably longer than the rest of the build.  I propose to use a `concurrent.futures` thread pool to run [the inner loop in `load_mappings()`](https://github.com/sphinx-doc/sphinx/blob/e8925e78ca3be64a94c061e71a1da7d161640fa1/sphinx/ext/intersphinx.py#L196-L216) when there is more than one inventory that needs to be fetched.

This could give slightly better or slightly worse performance for all-local inventories, but will be *much* faster for remote inventories.  I am happy to open a PR with this change.

**Comment by tk0miya** [comment]
+1; reasonable. PRs are always welcome!
