### ISSUE TITLE
Translatable strings using `%r` and `%s` cause problems if translation reverses order

### ISSUE THREAD

**Issue by jfbu** [sphinx-doc/sphinx#6821]
On master branch (at circa ``14-11-2019 16:42:29 CET`` for transifex pull)

```
cd sphinx/locale
tx pull -f -a
cd ../..
python setup.py compile_catalog
```

output (trimmed)

```
running compile_catalog
...
error: sphinx/locale/ja/LC_MESSAGES/sphinx.po:1280: positional format placeholders are unbalanced
error: sphinx/locale/ja/LC_MESSAGES/sphinx.po:2415: incompatible format for placeholder 1: 'r' and 's' are not compatible
...
error: sphinx/locale/zh_CN/LC_MESSAGES/sphinx.po:403: incompatible format for placeholder 1: 'r' and 's' are not compatible
compiling catalog sphinx/locale/zh_CN/LC_MESSAGES/sphinx.po to sphinx/locale/zh_CN/LC_MESSAGES/sphinx.mo
...
Compiling failed.
```

Apart from the `％` problem at `sphinx/locale/ja/LC_MESSAGES/sphinx.po:1280` (there were others earlier so I think transifex has been updated recently) the problem is with strings such as 

```
#: sphinx/ext/coverage.py:46
#, python-format
msgid "invalid regex %r in %s"
msgstr "%s 内に無効な正規表現 %r があります"
```

where translation permutes order. For Chinese:

```
#: sphinx/registry.py:464
#, python-format
msgid ""
"the extension %r was already merged with Sphinx since version %s; this "
"extension is ignored."
msgstr "自版本 %s 开始，扩展 %r 已合并至 Sphinx；该扩展被忽略。"
```

When more translation work will be done at transifex more and more such occurrences will arise for languages where order is permuted with respect to English.

<s>It seems usage of `.fmt` should solve this.</s>

edit: I of course meant "usage of `.format()` would solve this"

**Comment by tk0miya** [comment]
I fixed Japanese translations in #6823. But error in Chinese translations still remains. So I keep this opened.
