### ISSUE TITLE
The addition of partial search support in the HTML builds has a logic error

### ISSUE THREAD

**Issue by JustinMaxwell** [sphinx-doc/sphinx#6824]
**Describe the bug**
In certain edge cases, the 'Search module' in searchtools.js will exit the 'performTermsSearch' method early (in the 'check if all requirements are matched' section), resulting in no results being returned, when there should be results returned.

**To Reproduce**
There may be other ways that this error manifest, but I'll give the simplest steps that I'm aware of.
1. quick-start a project
2. add a directory ('foo') and a page ('bar.rst') within foo directory
2. add foo to the index.rst, and change the max depth to 1
3. in bar.rst, add a title ('test title')
4. add some paragraph text containing the term 'mysql' and no other terms that include 'sql'
5. add a section title containing the term 'sql' and no other terms that include 'sql'
6. finally do a search for sql. It should return no results if the bug manifest.

**Expected behavior**
The 'performTermsSearch' method was created before 'support for partial matching' was added earlier this year. The partial matching allows for a condition where a partial match can exist in the 'titleterms' _and_ a full match can exist in the 'terms'. Whereas the performTermsSearch method is coded expecting for this condition of matches in both titleterms and terms to never be able to occur.

**Additional context**
I think the fix is within these two code blocks. 

```
        // set score for the word in each file to Scorer.term
        for (j = 0; j < _files.length; j++) {
          file = _files[j];
          if (!(file in scoreMap))
            scoreMap[file] = {}
--------->else if (word in scoreMap[file])
----------->scoreMap[file][word] += o.score;
--------->else
----------->scoreMap[file][word] = o.score;
        }
      });

      // create the mapping
      for (j = 0; j < files.length; j++) {
        file = files[j];
        if (file in fileMap) {
--------->if (!(fileMap[file].includes(word)))
              fileMap[file].push(word);
        }
        else
          fileMap[file] = [word];
      }
    }


```

**Comment by JustinMaxwell** [comment]
This is almost certainly related to Issue #6783.
Partial matched added by @TimKam.

**Comment by tk0miya** [comment]
@TimKam Could you check this please?

**Comment by TimKam** [comment]
Thanks for reporting. I will check.
