### ISSUE TITLE
Allow regexes for start/end specifiers on literalinclude

### ISSUE THREAD

**Issue by skitt** [sphinx-doc/sphinx#6826]
When specifying start and end search patterns for `literalinclude`, it’s often impossible to fully specify one or both of the patterns. Common issues I run into are the end brackets for C structure declarations, when other structures or unions are embedded in the main `struct`.

I’d like to be able to use regex patterns with the four start/end options.

I have a patch implementing this.

**Comment by tk0miya** [comment]
-0: I understand your idea is good. But literalinclude is already too complicated to me. It is hard to understand for developers and users. So I'd not like to add new options to it anymore... I think it should be extensible via extensions.

**Comment by skitt** [comment]
> -0: I understand your idea is good. But literalinclude is already too complicated to me. It is hard to understand for developers and users. So I'd not like to add new options to it anymore... I think it should be extensible via extensions.

I understand, that makes perfect sense. I’ll close this issue and the related PR!
