### ISSUE TITLE
Running `$ make latexpdf` on CentOS 8 returns `! LaTeX Error: File `cmap.sty' not found.`

### ISSUE THREAD

**Issue by sethgoldin** [sphinx-doc/sphinx#6831]
**Describe the bug**
A component named `cmap.sty` is missing when trying to create a LaTex

**To Reproduce**
```
$ make latexpdf
```

**Expected behavior**
Generate a PDF.

**Environment info**
- OS: CentOS 8
- Python version: 3.6.8
- Sphinx version: 2.2.1

**Additional context**
Error message: `! LaTeX Error: File `cmap.sty' not found.`

**Comment by tk0miya** [comment]
I'm not good at CentOS. But it seems cmap.sty is not installed. Please install it into your PC.
Thanks,

**Comment by sethgoldin** [comment]
I couldn't find anything matching `cmap` in the CentOS repositories, but I tried installing this, to no avail: https://cmap.ihmc.us/cmaptools/cmaptools-download/

**Comment by tk0miya** [comment]
I'm not good at CentOS. But it seems cmap package is distributed as `texlive-cmap` package on CentOS8. Could you try this please?
```
[root@ed86a1535077 /]# cat /etc/redhat-release
CentOS Linux release 8.0.1905 (Core)
[root@ed86a1535077 /]# yum search cmap
Failed to set locale, defaulting to C
Last metadata expiration check: 0:00:37 ago on Sat Nov 16 17:25:03 2019.
==================================================== Name & Summary Matched: cmap ====================================================
texlive-cmap.noarch : cmap package
adobe-mappings-cmap.noarch : CMap resources for Adobe's character collections
adobe-mappings-cmap-deprecated.noarch : Deprecated CMap resources for Adobe's character collections
```

**Comment by sethgoldin** [comment]
Thanks, that's the right package, but now I'm running into a different error when trying to run `$ make latexpdf`. I'll post a different question.

**Comment by flickerfly** [comment]
@sethgoldin Did you figure out all the CentOS 8 dependencies for this?

**Comment by sethgoldin** [comment]
Nope. Gave up trying and returned to 7.7.

**Comment by flickerfly** [comment]
Thanks

**Comment by flickerfly** [comment]
I got it working on Red Hat's Universal Base Image 8 (UBI8) through this use of Docker.

https://unix.stackexchange.com/questions/571580/how-do-i-setup-a-ubi8-container-to-compile-pdf-documents-via-sphinx/571970#571970
