### ISSUE TITLE
config.py shouldn't pop extensions from overrides

### ISSUE THREAD

**Issue by jpmckinney** [sphinx-doc/sphinx#6848]
**Describe the bug**

For example: I'm running Sphinx programmatically multiple times, with `confoverrides` set to a dict that sets `'extensions': ['recommonmark']`. The recommonmark plugin's setup function does:

```python
app.add_source_suffix('.md', 'markdown')
app.add_source_parser(CommonMarkParser)
```

If I use the same dict for `confoverrides` in each instantiation of Sphinx, the first will have the correct configuration, and all the others will not.

The undesired behavior that results is hard to debug, because it only results in warnings like "WARNING: toctree contains reference to nonexisting document 'README'" (where there is a `README.md`, but Sphinx is actually only looking for `*.rst`, because 'recommonmark' was popped from the 'extensions' key).

**To Reproduce**

This is a much simplified version. In reality, the `srcdir` would be different in each case.

```python
from sphinx.application import Sphinx
from sphinx.util.docutils import docutils_namespace
with open('contents.rst', 'w') as f:
    f.write('.. toctree::\n   :hidden:\n\n   README')
with open('README.md', 'w') as f:
    f.write('# Test')
overrides = {
    'extensions': ['recommonmark'],
    'master_doc': 'contents',
}
with docutils_namespace():
    app = Sphinx('.', None, 'outdir', '.', 'gettext', status=None, confoverrides=overrides)
    app.build(True)
    print('1')
with docutils_namespace():
    app = Sphinx('.', None, 'outdir', '.', 'gettext', status=None, confoverrides=overrides)
    app.build(True)
    print('2')
```

Output:

```
1
path/to/contents.rst:1: WARNING: toctree contains reference to nonexisting document 'README'
2
```

Naturally, since the document isn't found, the built documentation is missing a page…

**Expected behavior**

I expect to be able to reuse the variable in the `confoverrides` parameter in multiple calls.

**Your project**

https://github.com/open-contracting/extension_registry.py

**Screenshots**

N/A

**Environment info**

- OS: Mac
- Python version: 3.6.1
- Sphinx version: 2.2.1
- Sphinx extensions:  recommonmark
- Extra tools: N/A

**Additional context**

N/A

**Comment by tk0miya** [comment]
Fixed in #6852 
Thank you for reporting!
