### ISSUE TITLE
Non-RST source text is parsed as RST after translation

### ISSUE THREAD

**Issue by jpmckinney** [sphinx-doc/sphinx#6855]
**Describe the bug**

a12399dbe429f552ab012099491c577de668a81d introduced a regression: If the source text is in Markdown, it gets parsed as RST after translation.

In Sphinx 1.6.7 (and earlier), in `publish_msgstr`, `reader.read()` (i.e. `SphinxBaseReader.read()`) would select the parser based on the `source_path` suffix. After that commit, the parser is instead set by:

```python
parser = app.registry.create_source_parser(app, '')
```

This means that it's always RST that parses the translated text. Obviously, if the translated text is in Markdown syntax, this will not result in a correct translation.

I'll submit a PR that determines the filetype based on the `source_path`. Ideally, this can be applied to 2.2.x.

**To Reproduce**

I have open PRs on CommonMark.py and recommonmark that also need to be merged to be able to translate Markdown in Sphinx, so it will be hard to create a 'small' example.

**Expected behavior**

I expect the translated text to be parsed as Markdown (not RST) if the source text is Markdown.

**Your project**

https://github.com/open-contracting-extensions/public-private-partnerships

**Screenshots**

N/A

**Environment info**

- OS: Mac
- Python version: 3.6.1
- Sphinx version: 2.2.1
- Sphinx extensions:  recommonmark
- Extra tools: N/A

**Additional context**

This was originally fixed in aefab514e2bbce775a00c1aaae057044a02033fb and then broken in a12399dbe429f552ab012099491c577de668a81d

I have open PRs on CommonMark.py and recommonmark that also need to be merged to be able to translate Markdown in Sphinx: 

* https://github.com/readthedocs/commonmark.py/pull/225
* https://github.com/readthedocs/recommonmark/pull/187

**Comment by tk0miya** [comment]
Fixed by #6927.
Thank you for reporting.
