### ISSUE TITLE
Autodoc not rendering docs for classmethod on IntEnum class

### ISSUE THREAD

**Issue by chrisjbillington** [sphinx-doc/sphinx#6857]
The classmethod in the below class is not getting picked up by autodoc when I include the class with the following:
```
.. autoclass:: inotify_simple.flags
    :members:
```

```python
class flags(enum.IntEnum):
    """Inotify flags as defined in ``inotify.h`` but with ``IN_`` prefix omitted.
    Includes a convenience method :func:`~inotify_simple.flags.from_mask` for extracting
    flags from a mask.
    """
    @classmethod
    def from_mask(cls, mask):
        """Convenience method that returns a list of every flag in a mask."""
        return [flag for flag in cls.__members__.values() if flag & mask]

    ACCESS = 0x00000001  #: File was accessed
    MODIFY = 0x00000002  #: File was modified
    ...
```

**To Reproduce**
```
$ git clone https://github.com/chrisjbillington/inotify_simple
$ cd inotify_simple/doc
$ make html
```
Then open `build/html/index.html` and scroll down to or ctrl-f for the `classinotify_simple.flags` docs, and see that the `from_mask()` method documentation is not present.

**Expected behavior**
To see the method documentation for `from_mask()` under the class.

If I either:
* change the class to not be a subclass of `enum.IntEnum` or
* make the method not a classmethod

then I do see the documentation:

![image](https://user-images.githubusercontent.com/1044087/69473760-10642a00-0d86-11ea-9553-102c1bda9b50.png)

So it's an issue specific to the enum class and classmethods.

If I add `:undoc-members:` then I see the member, but without its function signature or docstring:

![image](https://user-images.githubusercontent.com/1044087/69473773-40abc880-0d86-11ea-9c3b-9b66c2285148.png)

**Your project**
https://github.com/chrisjbillington/inotify_simple

**Environment info**
- OS: Arch Linux, fully updated
- Python version: 3.8.0
- Sphinx version: 2.2.1
- Sphinx extensions: sphinx.ext.autodoc, sphinx.ext.napoleon

Readthedocs also fails to render the docs for this classmethod, so the issue is probably not super specific to my environment.

**Comment by chrisjbillington** [comment]
Ah, scratch this. I spent so long debugging only to realise minutes after submitting the bug report that it was due to a monkeypatch I added years ago to work around some other issue long since fixed in sphinx. Everything is fine....

**Comment by chrisjbillington** [comment]
Closed thinking I had found the cause and that it was my fault, reopened as it turned out that was not the case.

**Comment by chrisjbillington** [comment]
A more minimal example of the bug:

[bug_demo.zip](https://github.com/sphinx-doc/sphinx/files/3882187/bug_demo.zip)

make with `make html`.

**Comment by jamesharris-garmin** [comment]
I'm seeing this issue as well. I wonder if there is a clean solution for this.
