### ISSUE TITLE
Sphinx autodoc fails on metaclass

### ISSUE THREAD

**Issue by manns** [sphinx-doc/sphinx#6859]
**Describe the bug**
After introducing a metaclass, sphinx-build raises an Exception:
```
Exception occurred:
  File "/usr/lib/python3.7/abc.py", line 143, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
```
Full error log: [sphinx-err-in6hz620.log](https://github.com/sphinx-doc/sphinx/files/3882822/sphinx-err-in6hz620.log)

When commenting the following code in the file icons.py, the `reading sources` step runs through without error:
```python3

class IconConverter(type):
    """Meta class that provides QIcons for IconPaths icons"""

    def __getattribute__(cls, name):
        return QIcon(str(getattr(IconPath, name)))


class Icon(metaclass=IconConverter):
    """Provides QIcons as attributes for all attributes of IconPaths"""

    pass
```

**To Reproduce**
```
$ git clone https://gitlab.com/pyspread/pyspread.git
$ cd pyspread/apidocs
$ ./build_docs.sh

```

**Expected behavior**
I would expect sphinx to run without an error.

**Your project**
Link to your sphinx project, or attach zipped small project sample.

https://gitlab.com/pyspread/pyspread

See also discussion on issue 
https://gitlab.com/pyspread/pyspread/issues/16

**Environment info**
- OS: Debian unstable
- Python version: 3.7.1
- Sphinx version: 1.8.5
- Sphinx extensions:  sphinxcontrib-fulltoc, sphinxcontrib-autoprogram, sphinxcontrib-blockdiag, sphinxcontrib-napoleon, recommonmark, sphinxbootstrap4theme

**Comment by pedromorgan** [comment]
Here's the relevant snippet


```
 $ sphinx-build -a -b html ./apidocs ./public/
1930 Running Sphinx v2.2.1
1931 [autosummary] generating autosummary for: api/actions.rst, api/commands.rst, api/dialogs.rst, api/entryline.rst, api/grid.rst, api/icons.rst, api/index.rst, api/installer.rst, api/interfaces/index.rst, api/interfaces/pys.rst, ..., api/model/index.rst, api/model/model.rst, api/panels.rst, api/pyspread.rst, api/settings.rst, api/toolbar.rst, api/widgets.rst, api/workflows.rst, dev_quickstart.rst, index.rst
1932 loading intersphinx inventory from http://docs.python.org/3/objects.inv...
1933 intersphinx inventory has moved: http://docs.python.org/3/objects.inv -> https://docs.python.org/3/objects.inv
1934 loading intersphinx inventory from http://docs.scipy.org/doc/numpy/objects.inv...
1935 intersphinx inventory has moved: http://docs.scipy.org/doc/numpy/objects.inv -> https://docs.scipy.org/doc/numpy/objects.inv
1936 loading intersphinx inventory from http://docs.scipy.org/doc/scipy/reference/objects.inv...
1937 intersphinx inventory has moved: http://docs.scipy.org/doc/scipy/reference/objects.inv -> https://docs.scipy.org/doc/scipy/reference/objects.inv
1938 loading intersphinx inventory from https://matplotlib.org/objects.inv...
1939 building [mo]: all of 0 po files
1940 building [html]: all source files
1941 updating environment: [new config] 31 added, 0 changed, 0 removed
1942 reading sources... [  3%] api/actions
1943 /usr/local/lib/python3.7/dist-packages/sphinx/events.py:103: RemovedInSphinx30Warning: autodoc_default_flags is now deprecated. Please use autodoc_default_options instead.
1944   results.append(callback(self.app, *args))
1945 Exception occurred:
1946   File "/usr/lib/python3.7/abc.py", line 143, in __subclasscheck__
1947     return _abc_subclasscheck(cls, subclass)
1948 TypeError: issubclass() arg 1 must be a class
1949 The full traceback has been saved in /tmp/sphinx-err-427k161d.log, if you want to report the issue to the developers.
1950 Please also report this if it was a user error, so that a better error message can be provided next time.
1951 A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
1955 ERROR: Job failed: exit code 1
```

**Comment by tk0miya** [comment]
It seems the error is happened when passing `Icon` class to `logging.debug()`. And it calls `isinstance(Icon, collections.abc.Mapping)` inside it. Finally, it tries to compares its `__class__` attributes with `collections.abc.Mapping`. But `Icon.__class__` returns an instance of `QIcon`. It confuses python.

In my local, this code also crashes:
```
import collections.abc


class IconConverter(type):
    def __getattribute__(cls, name):
        return "QIcon"


class Icon(metaclass=IconConverter):
    pass


isinstance(Icon, collections.abc.Mapping)
```

I think it would be better to modify `IconConverter.__getattribute__()` to return correct values for some special methods.
Thanks,

**Comment by manns** [comment]
@tk0miya  I was not aware that Sphinx relies on ```__class__```.
The solution is replacing ```__getattribute__``` with ```__getattr__``` in the application code, which is recommended anyway. 

Thank you so much for your help.

**Comment by tk0miya** [comment]
No, this is not related with Sphinx. Sphinx simply calls `logging.debug()` to output debug log. I think standard library of python expects all objects follow the rule of special methods.
