### ISSUE TITLE
Document literalinclude before-start end-after same string/Doxygen compatibility

### ISSUE THREAD

**Issue by nilsdeppe** [sphinx-doc/sphinx#6863]
First of all, thanks for creating and maintaining Sphinx! It's really awesome :heart: 

**Is your feature request related to a problem? Please describe.**
I want to have the same comment line in the code twice around the block of code I'd like included. For example,
```cpp
# [[awesome_code_block]]
print("I'm doing something")
# [[awesome_code_block]]
```
Sphinx's `literalinclude` directive supports this!
```rst
.. literalinclude:: file.py
   :start-after: [[awesome_code_block]]
   :end-before: [[awesome_code_block]]
```
Which renders the code exactly as I want :heart: 
However, this support isn't made clear in the documentation:
```
Another way to control which part of the file is included is
to use the start-after and end-before options (or only one of them).
If start-after is given as a string option, only lines that follow the first
line containing that string are included. If end-before is given as a
string option, only lines that precede the first lines containing that
string are included.
```
and I'm not sure if there is a test for this feature.

My motivation for having this feature is that Doxygen (a C++ documentation generator) uses snippets in the way I've shown above and we're looking at moving from Doxygen to Sphinx. Snippet support that is compatible with both Sphinx and Doxygen was something we wanted to maintain.

**Describe the solution you'd like**
I think documenting the possibility of having the begin and end lines be comments in the source code and have the same text would resolve the issue. I'm not sure if there is a test for this behavior in Sphinx (or how testing is done within Sphinx), but that would be a (separate) but additional nice thing to have. I also think that having an example of this feature in the documentation would be nice. The relevant paragraph in the docs is:
```
Another way to control which part of the file is included is to use the
start-after and end-before options (or only one of them). If start-after
is given as a string option, only lines that follow the first line containing
that string are included. If end-before is given as a string option, only
lines that precede the first lines containing that string are included. The
start-at and end-at options behave in a similar way, but the lines containing
the matched string are included.
```
Maybe clarifying that
```
If both start-after and end-before are given, then the block ends at the first
occurrence of the end-before string that appears in the file after the start-before
string.
```

**Comment by ass-spec** [comment]
If both start-after and end-before are given, then the block ends at the first
occurrence of the end-before string that appears in the file after the start-before
string.

**Comment by tk0miya** [comment]
Yes, Sphinx supports such usecase. Could you send us a pull request please? It would be helpful to me!

**Comment by shibukawa** [comment]
I confirmed current Sphinx has this feature. You can use same string.
