### ISSUE TITLE
TypeError: Error when calling the metaclass bases

### ISSUE THREAD

**Issue by gumond** [sphinx-doc/sphinx#6878]
Hello,

I am getting:

[...]
  File "/usr/lib/python2.7/site-packages/jwkest/extra.py", line 3, in <module>
    from jwkest.jws import JWSException
  File "/usr/lib/python2.7/site-packages/jwkest/jws.py", line 116, in <module>
    class HMACSigner(Signer):
TypeError: Error when calling the metaclass bases
    str() takes at most 1 argument (3 given)
when trying to do sphynx build of my code
https://travis-ci.org/rucio/rucio/jobs/617413102?utm_medium=notification&utm_source=github_status

I have seen here troubles with metaclasses, could this issue be related, how could I avoid this crash  ?
https://github.com/IdentityPython/pyjwkest/tree/master/src/jwkest

**Comment by tk0miya** [comment]
Thank you for posting. But here is not place for question. Please move to sphinx-users forum: https://groups.google.com/forum/#!forum/sphinx-users.

BTW, your error is happened at importing modules. I guess it is not related with Sphinx.

**Comment by gumond** [comment]
I find it strange that I can run flake8 and pylint on the imported module without any issue and my program runs without issues as well. To me the TypeError mentioned appears only when I try to run Sphinx. I am sorry if this was the wrong place to ask, I will try in the forum first. Thank you for your response.

**Comment by tk0miya** [comment]
Thanks,

I can't say it is a bug or not. But Sphinx-1.8.5 has no longer supported. So my first recommendation is upgrading Sphinx to newest one.
