### ISSUE TITLE
Smart quotes incorrect when surrounding a dash

### ISSUE THREAD

**Issue by pedro-w** [sphinx-doc/sphinx#6884]
**Describe the bug**
When outputting HTML, Sphinx applies smart quotes to the sequence `'-'` but the closing quote is the wrong way around. 

**To Reproduce**
Apply sphinx-build to the following ReST:
```
Smart Quotes
============

* 'X'
* '_'
* '-'
* 'K'.
```
and view the generated HTML. All symbols have the correct smart quotes except '-'. See screenshot below.

**Expected behavior**
All list items should be rendered as open-quote symbol close-quote. 

**Screenshots**
![Output screen shot](https://user-images.githubusercontent.com/22172519/70133983-0fcd6c80-167f-11ea-9cfa-7d9d9726a84d.png)

**Environment info**
- OS: Debian 10
- Python version: 3.7.3
- Sphinx version: 2.2.1
- Sphinx extensions:  none
- Extra tools: none

**Additional context**
See discussion on StackOverflow: https://stackoverflow.com/questions/59135242/how-to-ensure-correct-smart-quotes-in-sphinx

**Comment by jfbu** [comment]
Thank you for reporting. This is not a Sphinx issue as it is a feature of Docutils

```
$ cat > test.txt <<EOF
> '-'
> EOF
$ rst2html.py --smart_quotes=yes test.txt test.html
```

produces  in test.html this:
```
<p>‘-‘</p>
```
where the two `‘` are identical U+2018. Can you please raise upstream at their [project](https://sourceforge.net/p/docutils/bugs/)?

**Comment by jfbu** [comment]
As work around, use the correct curly quotes directly in reST source.

**Comment by pedro-w** [comment]
Thanks JFBU, I will do that. See https://sourceforge.net/p/docutils/bugs/383/

**Comment by tk0miya** [comment]
I'm closing now. Thank you for reporting!
