### ISSUE TITLE
TypeError: '_traversal_list' object is not reversible

### ISSUE THREAD

**Issue by lpsinger** [sphinx-doc/sphinx#6887]
**Describe the bug**
I get the following error when building my documentation set:

```
Exception occurred:
  File "/src/.eggs/Sphinx-2.2.2-py3.7.egg/sphinx/util/nodes.py", line 151, in apply_source_workaround
    for classifier in reversed(node.parent.traverse(nodes.classifier)):
TypeError: '_traversal_list' object is not reversible
The full traceback has been saved in /tmp/sphinx-err-5sxhweij.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

For the full output, see the attached file [sphinx-err-5sxhweij.log](https://github.com/sphinx-doc/sphinx/files/3924304/sphinx-err-5sxhweij.log).

**To Reproduce**
```
$ docker run --rm -it python bash
# git clone https://git.ligo.org/emfollow/gwcelery
# cd gwcelery
# python setup.py build_sphinx
```

**Expected behavior**
The documentation for my project builds successfully.

**Your project**
http://git.ligo.org/emfollow/gwcelery/

**Environment info**
- OS: Debian 10.2
- Python version: 3.8.0
- Sphinx version: 2.2.2
- Sphinx extensions:  celery.contrib.sphinx, matplotlib.sphinxext.plot_directive, sphinx.ext.autodoc, sphinx.ext.autosectionlabel, sphinx.ext.extlinks, sphinx.ext.graphviz, sphinx.ext.intersphinx, sphinx.ext.napoleon, sphinx.ext.viewcode

**Comment by lpsinger** [comment]
Looks like this broke with docutils==0.16b0.

**Comment by aowen87** [comment]
We're also seeing this when building [VisIt](https://github.com/visit-dav/visit) docs. Is there a workaround or patch that we can apply for the time being? We build with sphinx 2.2.1 and are getting the following error while building our docs:
```
Exception occurred:
  File "/Users/maguire7/Desktop/VisIt_repo/libs_dev/third_party/python/3.7.5/i386-apple-darwin18_clang/lib/python3.7/site-packages/Sphinx-2.2.1-py3.7.egg/sphinx/util/nodes.py", line 151, in apply_source_workaround
    for classifier in reversed(node.parent.traverse(nodes.classifier)):
TypeError: '_traversal_list' object is not reversible
```

**Comment by matham** [comment]
I had the same issue. The workaround is to not use the latest beta release of `docutils` on pypi when installing sphinx. Specifically, I had something like `pip install --pre sphinx`, changing to `pip install sphinx` resolved the issue because the latest stable version of docutils does not have the problem.

Hopefully it will be fixed before docutils makes a new stable release.

**Comment by aowen87** [comment]
We altered a section of our config file to use a lower version of docutils, and this seemed to work for us.

**Comment by tk0miya** [comment]
Thank you for reporting. It seems docutils adds some incompatible changes to new beta release. I'll try to fix it later.

**Comment by tk0miya** [comment]
Fixed by #6918 
Thank you for reporting!

**Comment by williamdes** [comment]
Would that explain https://salsa.debian.org/phpmyadmin-team/phpmyadmin/-/jobs/505908#L1141 ?

**Comment by tk0miya** [comment]
@williamdes It seems you are using Sphinx-1.8.5 and docutils-0.16, right? This has been fixed in Sphinx-2.3.0. If so, please update Sphinx to latest one or pin docutils to 0.15 or older.

FYI: We only supports latest version of Sphinx. So my recommendation is updating Sphinx.

**Comment by williamdes** [comment]
Well https://packages.debian.org/sid/docutils-common has "0.15.2+dfsg-2" in Debian and https://packages.debian.org/source/sid/sphinx is at "1.8.5-4" 
Unless somebody updates the packages it looks like I will be waiting and having a failed CI

**Comment by tk0miya** [comment]
`_traversal_list` was added since docutils-0.16. So it seems the CI execution uses non-debian's docutils.

**Comment by williamdes** [comment]
`Get: 32 http://deb.debian.org/debian sid/main amd64 docutils-common all 0.16~rc1+dfsg-1 [128 kB]`

https://tracker.debian.org/pkg/python-docutils explains why that appeared recently.
0.16 is in unstable and the CI uses unstable 

Should I open a bug so that a new version is uploaded ?

**Comment by tk0miya** [comment]
All I can do is please update Sphinx to latest one as you do for docutils. I don't know rule of Debian. But if updating is called a bug in Debian, please open a bug.

**Comment by tk0miya** [comment]
ping @mitya57 . Could you check this please?

**Comment by mitya57** [comment]
This fixes it:
https://tracker.debian.org/news/1093549/accepted-sphinx-185-5-source-into-unstable/

**Comment by williamdes** [comment]
> All I can do is please update Sphinx to latest one as you do for docutils. I don't know rule of Debian. But if updating is called a bug in Debian, please open a bug.

I can not update Sphinx since the CI uses the latest version available.
> But if updating is called a bug in Debian, please open a bug.

Bugs are used for various things, bugs, tasks, special/security updates, etc..

Thank you @mitya57 !

~~Seems still not okay, but I will wait more in case this is a propagation issue 
https://salsa.debian.org/phpmyadmin-team/phpmyadmin/-/jobs/505942~~
Fixed :tada: !
https://salsa.debian.org/phpmyadmin-team/phpmyadmin/-/jobs/507190

**Comment by tk0miya** [comment]
@mitya57 Thank you for quick work! I really appreciate you :-)
