### ISSUE TITLE
Trailing comma in autoclass directive causes cryptic warning

### ISSUE THREAD

**Issue by dullbananas** [sphinx-doc/sphinx#6889]
**Describe the bug**
When I have this in an rst file:
```rst
.. autoclass:: classname
   :members: member1, member2,
```
It causes this warning to appear:
```
WARNING: missing attribute  in object Classname
```
But when I remove the comma after `member2`, the warning no longer is shown.

**Comment by tk0miya** [comment]
Fixed by #7076 
Thank you for reporting.
