### ISSUE TITLE
sphinx-build -M builds into different directory than sphinx-build -b

### ISSUE THREAD

**Issue by dvorapa** [sphinx-doc/sphinx#6896]
**Describe the bug**
`sphinx-build -M . ./_build` builds into `./_build/html`, but `sphinx-build -b . ./_build` builds into `./_build`. This is an inconsistency between `make html` and `sphinx-build -b` marked as equivalent in https://www.sphinx-doc.org/en/master/usage/quickstart.html.

**To Reproduce**
```
$ git clone https://github.com/wikimedia/pywikibot
$ cd pywikibot
$ pip install -r requirements.txt .[security] -r docs/requirements-py3.txt
$ cd docs
$ make html
$ sphinx-build -M . ./_build
$ sphinx-build -b . ./_build
compare all three results
```
`make html` and `sphinx-build -M` builds into _build/html, but `sphinx-build -b` builds into _build

**Expected behavior**
The build folder should be the same for all three options.

**Your project**
https://github.com/wikimedia/pywikibot (just a mirror from https://phabricator.wikimedia.org/diffusion/PWBC/)

**Environment info**
- OS: Debian Linux
- Python version: 3.5
- Sphinx version: 2.2.2
- Sphinx extensions: autodoc, apidoc, rstcheck, epytext, numpydoc or napoleon, alabaster

**Comment by tk0miya** [comment]
Thank you for reporting. As you mentioned, make-mode (-M) is different with non-make-mode (default). This is intentionally designed behavior. So I'd not like to change this. Anyway, the change will cause incompatibility and troubles.

**Comment by dvorapa** [comment]
Perhaps this should be mentioned in docs then?

**Comment by tk0miya** [comment]
You're right. We have to mention about this behavior.

**Comment by introt** [comment]
Related: #6603

**Comment by AA-Turner** [comment]
Closing in favour of #5618.

A
