### ISSUE TITLE
private methods and arguments ignored with -P / --private argument for sphinx-apidoc

### ISSUE THREAD

**Issue by Dantali0n** [sphinx-doc/sphinx#6899]
**Describe the bug**
When using the `-P` or `--private` arguments for *sphinx-apidoc* the private methods are not listed in the resulting documentation. 

**To Reproduce**
I run *sphinxcontrib-apidoc* in my project but the same occurs when using *sphinx-apidoc* directly from my *tox* file.
```
sphinx-apidoc -P -o doc/source/source_documentation radloggerpy/tests
sphinx-build -W -b html doc/source doc/build/html
```

**Expected behavior**
I expect the *doc/source/source_documentation* to contain source code documentation including private methods and attributes. However, the private methods and attributes are not included in the documentation even though they have documentation.

**Your project**
https://github.com/Dantali0n/radloggerpy

**Screenshots**
This screenshot shows the documentation of a method that is private:
![Screenshot from 2019-12-08 08-38-55](https://user-images.githubusercontent.com/5026295/70386168-2ed54280-198e-11ea-9e9b-5c9b4ce546a6.png)

This screenshot shows that the documentation is missing from the generated output:
![Screenshot from 2019-12-08 08-39-54](https://user-images.githubusercontent.com/5026295/70386175-46143000-198e-11ea-82a8-417a248ae8a4.png)

**Environment info**
- OS: Linux (Ubuntu 18.04 LTS x64)
- Python version: 3.6.8
- Sphinx version: 2.2.1
- Sphinx extensions:  sphinx.ext.autodoc, sphinx.ext.viewcode, sphinxcontrib.apidoc, sphinx_rtd_theme, cliff.sphinxext
- Extra tools: tox, pbr

**Additional context**
The behavior is the same if `-P` or `--private` is used.
I first submitted the bug to *sphincontrib-apidoc* here is the reference: 
https://github.com/sphinx-contrib/apidoc/issues/14

**Comment by anandsimer** [comment]
+1  I have the same issue, I am using `sphinx v2.3.1` and when using `sphinx-apidoc` with option `-P` or `--private` is not picking the private members. 


Working way to get the private methods into the sphinx htmls is using the `autodoc_default_options` in _config.py_ like below:

`autodoc_default_options = {'private-members': True}`

**Comment by tk0miya** [comment]
Thank you for reporting. I just made a PR #7066 to fix this. But I'm not familiar with apidoc. Can anyone try this please? You can use this with `pip install git+https://github.com/tk0miya/sphinx@6899_apidoc_private_members` command.

**Comment by Dantali0n** [comment]
Just tested, works for me :+1:

**Comment by anandsimer** [comment]
Tested and verified, thanks @tk0miya

**Comment by tk0miya** [comment]
Thank you for confirmation!

**Comment by tk0miya** [comment]
Merged. Thank you for your help!
