### ISSUE TITLE
Not possible to set  boolean `latex_use_xindy` via `-D` option to sphinx-build

### ISSUE THREAD

**Issue by jfbu** [sphinx-doc/sphinx#6900]
**Describe the bug**

Impossible to override [`latex_use_xindy`](http://www.sphinx-doc.org/en/master/usage/configuration.html#confval-latex_use_xindy) from command line invocation of `sphinx-build`.

**To Reproduce**
With any project

```
sphinx-build -b latex . _build/latex -D latex_use_xindy=0
```

produces

```
WARNING: The config value `latex_use_xindy' has type `str', defaults to `bool'.
```
And the latex output directory will actually be configured for PDF build to use `xindy`.

Notice that for example
```
sphinx-build -b latex . _build/latex -D latex_use_latex_multicolumn=0
```
raises no warning and behaves as expected. Same for
```
sphinx-build -b latex . _build/latex -D smartquotes=0
```
which works fine.

**Expected behavior**
People reading documentation are rewarded with Sphinx behaving as promised :smile:

**Your project**

Any project.

**Environment info**
- OS: Mac
- Python version: 3.7.5
- Sphinx version: tested with 2.0.1 and current 2.0 branch

**Additional context**

- #6898

**Comment by tk0miya** [comment]
Fixed by #6908!
