### ISSUE TITLE
References to figures without captions: errors in both HTML and LaTeX

### ISSUE THREAD

**Issue by eudoxos** [sphinx-doc/sphinx#6914]
**Describe the bug**
Using figures without captions causes errors in both HTML (though these are properly reported when source is processed) and in LaTeX (they are not reported until LaTeX says there were undefined references).

This was the test document, compiled with sphinx 2.2.2 from pypi; `numfig=True` was added to conf.py, the project was otherwise generated with sphinx-build with no other changes. It is attached here: [sphinx-captions.zip](https://github.com/sphinx-doc/sphinx/files/3947135/sphinx-captions.zip)

```
Welcome to foo's documentation!
===============================

References:

* figure without caption

   * plain reference :ref:`fig-sample-nocaption` (error: HTML, LaTeX)
   * named reference :ref:`figure without caption <fig-sample-nocaption>` (error: LaTeX)
   * numbered reference :numref:`fig-sample-nocaption` (error: LaTeX)

* figure with caption

   * plain reference :ref:`fig-sample-caption`
   * named reference :ref:`figure without caption <fig-sample-caption>`
   * numbered reference :numref:`fig-sample-caption`

.. _fig-sample-nocaption:
.. figure:: sample.png


.. _fig-sample-caption:
.. figure:: sample.png
   
   This is some caption.
```

and these are the results:

1. misleading warning: **index.rst:8: WARNING: undefined label: fig-sample-nocaption (if the link has no caption the label must precede a section header)**
2. this is HTML output (the error highlighted corresponds to the warning mentioned above):
![html output](https://user-images.githubusercontent.com/1029876/70568432-2b150c00-1b98-11ea-98ac-67e7fbc23927.png)
3. this is LaTeX (pdflatex) output:
```
LaTeX Warning: Hyper reference `index:fig-sample-nocaption' on page 1 undefined
 on input line 99.
LaTeX Warning: Hyper reference `index:fig-sample-nocaption' on page 1 undefined
 on input line 102.
```
![latex output](https://user-images.githubusercontent.com/1029876/70568602-7fb88700-1b98-11ea-85bd-b7b6fec93e41.png)

**Expected behavior**
I expect
1. sphinx to produce valid LaTeX input without undefined references;
2. uncaptioned figures to be referencable in LaTeX (this could be an optional setting perhaps causing uncaptioned figured to produce only "Figure 4.1." caption);
3. warning about figure not being captioned to be more meaningful -- I understand that non-numbered figure cannot be referenced via :ref:`label` (as the label will not resolve to any text) but the warning is not pointing to how to fix the issue.

**Environment info**
- OS: Ubuntu 18.04 LTS
- Python version: 3.6.8
- Sphinx version: 2.2.2
- Sphinx extensions: none
- Extra tools: pdflatex TeXLive

**Comment by tk0miya** [comment]
Thank you for reporting.

>sphinx to produce valid LaTeX input without undefined references;

Yes, it would be better to do that by disabling the broken hyperlinks.

>uncaptioned figures to be referencable in LaTeX (this could be an optional setting perhaps causing uncaptioned figured to produce only "Figure 4.1." caption);

I think this is a bug of the figure-number assignment logic. The figure having caption should have "Fig.1" in HTML output. And the `:numref:` reference to the uncaptioned figure should be warned.

>warning about figure not being captioned to be more meaningful -- I understand that non-numbered figure cannot be referenced via :ref:label (as the label will not resolve to any text) but the warning is not pointing to how to fix the issue.

Agreed. I just posted #8075 to make the warning message meaningful.
