### ISSUE TITLE
Regression in autosummary/autodoc

### ISSUE THREAD

**Issue by mgeier** [sphinx-doc/sphinx#6930]
**Describe the bug**

Maybe I'm using it wrong, but since #6223, the `autodoc`-based documentation generated by `autosummary` disappears.

**To Reproduce**

Here's a minimal example:

`module.py`:

```python
"""My module."""

def myfunction(x):
    """My function."""
    return 42
```

`index.rst`:

```rst
.. autosummary::
   :toctree: generated

   module
```

`conf.py`:

```python
extensions = ['sphinx.ext.autosummary']
autodoc_default_flags = ['members']
autosummary_generate = True
```
Generate docs:

```
$ python3 -m sphinx . _build
```

**Expected behavior**

A page `module.html` that contains a summary table followed by the documentation of the function `myfunction()`.

However, with any Sphinx version after #6223 (e.g. the `master` branch), the documentation of `myfunction()` is missing (although it appears in the summary table).

**Environment info**
- OS: Linux (Debian Testing)
- Python version: 3.7.5
- Sphinx version: anything after #6223, e.g. `master` branch
- Sphinx extensions:  sphinx.ext.autodoc, sphinx.ext.autosummary

**Comment by tk0miya** [comment]
`autodoc_default_flags` has been deprecated since v1.8.0. Please move to `autodoc_default_options`.
I guess you'd seen deprecation warning on running 2.x:
```
/Users/tkomiya/work/sphinx/sphinx/events.py:103: RemovedInSphinx30Warning: autodoc_default_flags is now deprecated. Please use autodoc_default_options instead.
  results.append(callback(self.app, *args))
```

Thanks,

**Comment by mgeier** [comment]
Thanks @tk0miya for the hint!

I was using the `master` branch from a few days ago and I did *not* get this warning!

BTW, the current `master` branch is broken!

**Comment by tk0miya** [comment]
The warning is shown during 2.x period and removed in 3.0 release. So master branch is not broken.

On my local, 2.4.0+ (HEAD of 2.0 branch) emits `RemovedInSphinx30Warning` on console:
```
$ sphinx-build --version
sphinx-build 2.4.0+
$ sphinx-build -b html . _build/html
Running Sphinx v2.4.0+
making output directory... done
/Users/tkomiya/work/sphinx/sphinx/events.py:103: RemovedInSphinx30Warning: autodoc_default_flags is now deprecated. Please use autodoc_default_options instead.
  results.append(callback(self.app, *args))
[autosummary] generating autosummary for: index.rst
WARNING: [autosummary] failed to import 'module': no module named module
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 1 source files that are out of date
updating environment: [new config] 1 added, 0 changed, 0 removed
reading sources... [100%] index
WARNING: failed to import module
/Users/tkomiya/work/tmp/doc/tmp/docs/index.rst.rst:1: WARNING: autosummary: stub file not found 'module'. Check your autosummary_generate setting.
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index
generating indices...  genindexdone
writing additional pages...  searchdone
copying static files... ... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 3 warnings.

The HTML pages are in _build/html.
```

**Comment by mgeier** [comment]
> The warning is shown during 2.x period and removed in 3.0 release.

OK, thanks for the info!

**Comment by ianepreston** [comment]
Apologies if this is the incorrect place for this question, but I've been googling for a while and can't seem to find the answer. What is the correct way to do this in Sphinx 2.4? I amended the example code above to 
```autodoc_default_options = {"members": True}```
and I still get the same warning and weird blocky looking output in my docs. I'm trying to resolve a similar issue in a larger project, where some of my code is showing up fine with ```..autoclass:: pkg.module.Class``` and some of it isn't.
