### ISSUE TITLE
Build documents with tr language set with python3

### ISSUE THREAD

**Issue by othercorey** [sphinx-doc/sphinx#6931]
**Describe the bug**
After switching from python 2.7 to 3.5, building documents with language set to `tr` fails.

This occurs with sphinx 1.8.5 and 2.2.

```
Exception occurred:
  File "/usr/local/lib/python3.5/dist-packages/docutils/transforms/frontmatter.py", line 400, in extract_bibliographic
    bibliofields = self.language.bibliographic_fields
AttributeError: module 'tr' has no attribute 'bibliographic_fields'
The full traceback has been saved in /tmp/sphinx-err-_2ck0wqs.log, if you want to report the issue to the developers.
```

**To Reproduce**
With `language = 'tr'`
```
$(SPHINXBUILD) -b html -d $(BUILDDIR)/doctrees/tr . $(BUILDDIR)/html/en
```

**Expected behavior**
Builds finish without python error.

**Your project**
https://github.com/cakephp/docs

**Environment info**
- OS: debian stretch
- Python version: 3.5
- Sphinx version: 1.8.5/2.2.0

**Comment by tk0miya** [comment]
On my local, I succeeded to build your document with following Dockerfile:
```
FROM python:2.7-slim

RUN apt update; apt install -y git make
RUN git clone https://github.com/cakephp/docs.git
WORKDIR /docs
RUN pip install -U setuptools pip
RUN pip install -r requirements.txt
RUN make html
```
Could you make a small reproducible example? 

In addition, I'd like to know where the "module 'tr' came from. It is not a part of docutils and sphinx package. Therefore, I can't imagine why such error happened. Could you try to debug with adding `print(self.language)` to the module (if possible)?
```
Exception occurred:
  File "/usr/local/lib/python3.5/dist-packages/docutils/transforms/frontmatter.py", line 400, in extract_bibliographic
    bibliofields = self.language.bibliographic_fields
AttributeError: module 'tr' has no attribute 'bibliographic_fields'
```

**Comment by othercorey** [comment]
> Could you make a small reproducible example?

```
FROM python:3.5-slim

RUN apt update; apt install -y git make
RUN git clone https://github.com/cakephp/docs.git
WORKDIR /docs
RUN git checkout 4.x-python3
RUN pip install -U setuptools pip
RUN pip install -r requirements.txt
RUN sed -i 's/preamb = ur/preamb = r/g' /usr/local/lib/python3.5/site-packages/cakephpsphinx/config/all.py
RUN make html
```
 
The `sed` command is just in case our python3 fix isn't published when you run.

**Comment by tk0miya** [comment]
Thank you for example. Reproduced on my local.
It seems docutils; a core library of Sphinx is confused by directory named same as language.
```
root@31801945b741:/docs# python
Python 3.5.9 (default, Nov 23 2019, 07:17:24)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> import docutils.languages
>>> docutils.languages.get_language('zz')
<module 'docutils.languages.en' from '/usr/local/lib/python3.5/site-packages/docutils/languages/en.py'>
>>> # => returns "en" language
...
>>> docutils.languages._languages.clear()  # clear language-cache forcedly
>>> os.mkdir('zz')
>>> docutils.languages.get_language('zz')
<module 'zz' (namespace)>
>>> # => returns invalid language module if directory named same as language found
...
```
I think this is not an expected behavior. So we need to report this to docutils project.

BTW, It seems cakephp project adds `docs/` directory to loading path (sys.path). Therefore, you can avoid this error by removing it from loading path as a workaround.
Thanks,

**Comment by tk0miya** [comment]
I just reported this to docutils project: https://sourceforge.net/p/docutils/bugs/385/

**Comment by tk0miya** [comment]
It would be better to track this error on docutils' project. So I'm closing this now.
Thank you for reporting.

**Comment by othercorey** [comment]
Thanks for the help!  I'm trying to use the work-around when loading language-specific configs. I'll track the issue on docutils.
