### ISSUE TITLE
latex_toplevel_sectioning = 'part' causes strange sectioning structure.

### ISSUE THREAD

**Issue by tk0miya** [sphinx-doc/sphinx#6940]
**Describe the bug**
`latex_toplevel_sectioning = 'part'` causes strange sectioning structure.

**To Reproduce**
````````````````````````````````````
.. index.rst

Welcome to project's documentation!
===================================

heading title
-------------

heading title
^^^^^^^^^^^^^

heading title
`````````````

heading title
~~~~~~~~~~~~~

heading title
%%%%%%%%%%%%%

heading title
#############

heading title
.............
````````````````````````````````````
```
# conf.py
latex_documents = [
    ('index', 'manual.tex', '', '', 'manual'),
    ('index', 'howto.tex', '', '', 'howto'),
]
latex_toplevel_sectioning = 'part'
```

`manual.tex` has a correct structure of sectioning units: part, chapter, section, subsection, ...
But `howto.tex` does not have chapter. I feel this is strange.
```
$ grep 'heading title' _build/latex/*.tex
_build/latex/howto.tex:\part{heading title}
_build/latex/howto.tex:\section{heading title}
_build/latex/howto.tex:\subsection{heading title}
_build/latex/howto.tex:\subsubsection{heading title}
_build/latex/howto.tex:\paragraph{heading title}
_build/latex/howto.tex:\subparagraph{heading title}
_build/latex/howto.tex:\subparagraph{heading title}
_build/latex/manual.tex:\part{heading title}
_build/latex/manual.tex:\chapter{heading title}
_build/latex/manual.tex:\section{heading title}
_build/latex/manual.tex:\subsection{heading title}
_build/latex/manual.tex:\subsubsection{heading title}
_build/latex/manual.tex:\paragraph{heading title}
_build/latex/manual.tex:\subparagraph{heading title}
```

**Expected behavior**
The setting causes error on howto style. Or it also outputs chapters like manual style.

**Your project**
N/A

**Screenshots**
N/A

**Environment info**
- OS: Mac
- Python version: 3.8.0
- Sphinx version: 2.3.0+
- Sphinx extensions:  Nothing

**Comment by tk0miya** [comment]
@jfbu I feel this is strange and broken output. Is this correct? Please let me know your opinion for this case.

**Comment by jfbu** [comment]
@tk0miya it is correct for LaTeX to have `\part` but not `\chapter`. 
```latex
\documentclass{article}

\begin{document}
\tableofcontents
\part{A}

\section{A-sec}

foo

\part{B}

\section{B-sec}
\end{document}
```
is perfectly legit document. Sphinx `'howto'` is a super-class of `article` 
https://github.com/sphinx-doc/sphinx/blob/d82e7c12a177a6a547ba1e72540f079f64590f8a/sphinx/writers/latex.py#L490

I see no problem here. I have found in past `'howto'` was somewhat neglected and some things had to be  fixed with it. But having `\part` but not `\chapter` is the expected thing in LaTeX standard document classes. Maybe your are used to Japanese classes which may behave differently?

**Comment by tk0miya** [comment]
Thank you for teaching me. This comes from my lack of understanding for LaTeX. In my understanding, Part is a parent of chapters, not sections. So I thought Sphinx is broken.
Withdrawing now.
