### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by ghost** [sphinx-doc/sphinx#6963]
I am not seeing any support for tags. Is that the case?

https://gohugo.io/content-management/taxonomies

**Comment by tk0miya** [comment]
Sorry, I don't understand what are you saying. Please follow our issue template.

In Sphinx context, tags are used for "only" directive and inside conf.py. I hope our document helps you:
https://www.sphinx-doc.org/en/master/usage/configuration.html
https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-only

Thanks,
