### ISSUE TITLE
sphinx.ext.graphviz: missing support for :class: option

### ISSUE THREAD

**Issue by lpirl** [sphinx-doc/sphinx#6966]
In [Hieroglyph](https://github.com/nyergler/hieroglyph) – a Sphinx extension to build slides/presentations – I want to apply a (CSS) class to an included ``dot`` graph.
From looking at the docs and code of ``sphinx.ext.graphviz``, it looks as if the directives provided by ``sphinx.ext.graphviz`` don't support the ``:class:`` option.

For this specific use – but probably as well for countless extensions and tools which build on Sphinx – it would be useful if the directives provided by ``sphinx.ext.graphviz`` would support the ``:class:`` option. Especially because the ``:class:`` option belongs to the [common options](https://docutils.sourceforge.io/docs/ref/rst/directives.html#common-options) of the reStructuredText directives.
It would allow users to format included graphs just as images, blocks, etc.

Alternatively, one could probably wrap the included graph in a [container](https://docutils.sourceforge.io/docs/ref/rst/directives.html#container) but that is a bit cumbersome. Just imagine every element for which a class should apply would have to be wrapped in a container…

Cheers. :)

**Comment by tk0miya** [comment]
Fixed by #6967 
Thank you for reporting.

**Comment by lpirl** [comment]
Whoop. What an unusual quick fix. :) Awesome. Cheers.
