### ISSUE TITLE
Document ability to add <script> text to header without using a file

### ISSUE THREAD

**Issue by choldgraf** [sphinx-doc/sphinx#6973]
I'm working on a sphinx extension that uses a little Javascript library, and was looking for ways to use variables in the sphinx configuration *within* the Javascript code. I couldn't find a way to do this, then I noticed that the MathJax library calls the `add_js_file` method like so:

`.add_js_file(None, type="text/x-mathjax-config", body=body)`

I gave this a shot using something like this:

`.add_js_file(None, body="var myvariable = 'foo';)`

and it worked! (it was placed in the head of my built docs). 

I couldn't find this functionality documented anywhere. Is this a reasonable thing to do? And if so, would it be helpful if I made a change to the docstring of `add_js_file`? (or elsewhere in the docs)

**Comment by tk0miya** [comment]
Absolutely. Could you send us a pull request please?

BTW, we have a config value; `mathjax_config` to configure mathjax via conf.py. So it would be better to use it to configure mathjax.
https://www.sphinx-doc.org/en/master/usage/extensions/math.html#confval-mathjax_config

**Comment by choldgraf** [comment]
Great, thanks...I'll put something together.

In this case I'm actually not actually configuring mathjax, that was just copypasted from another example. I'm inserting a javascript variable based on a configuration value in `conf.py`

**Comment by choldgraf** [comment]
lemme know if #6989 works for you!
