### ISSUE TITLE
Linkcheck builds excluded documents

### ISSUE THREAD

**Issue by Daltz333** [sphinx-doc/sphinx#6975]
**Describe the bug**
We have excluded a directory with 
```exclude_patterns```

It seems to work fine, however it looks like links are still checked in these excluded documents.

**Your project**
https://github.com/wpilibsuite/frc-docs

**Environment info**
- OS: Windows 10 1903
- Python version: 3.7.2
- Sphinx version: 2.2.0
- Sphinx extensions:  [e.g. sphinx.ext.autodoc, recommonmark]

**Comment by tk0miya** [comment]
Could you let me know the trouble in details. With adding `docs/software` to `exclude_patterns` to your frc-docs project, it seems working fine; Sphinx does not check links in `docs/software/*.rst` files on my local. Thanks,

**Comment by Daltz333** [comment]
Yeah, it just didn't work when I manually did ``docs/software/*.rst``
