### ISSUE TITLE
Is it possible to force inclusion of MathJax?

### ISSUE THREAD

**Issue by Midnighter** [sphinx-doc/sphinx#6981]
This is somewhat related to #5497. I have a plotly figure that includes some math and only renders correctly when MathJax is present. You can see what I mean [in this nbsphinx issue](https://github.com/spatialaudio/nbsphinx/issues/369). This is not detected by Sphinx and thus MathJax is not automatically included.

So I'm wondering if there is a way for me to force the inclusion of MathJax or, alternatively, for Sphinx to detect math in plotly objects?

**Comment by tk0miya** [comment]
I don't know you'd read our template message on posting. But here is not for question. Please post this into our forum again. Thanks,

>This is a list of issues for Sphinx, **not a forum**.
>If you'd like to post a question, please move to sphinx-users group.
>https://groups.google.com/forum/#!forum/sphinx-users

**Comment by Midnighter** [comment]
Apologies. Since there are plenty of questions here in the issues that have been answered and it's slightly annoying to join a google group, I thought I'd try.

**Comment by tk0miya** [comment]
Thank you for posting to forum.

The readers of this list are mainly maintainers of Sphinx. On the other hand, the reader of forum are both maintainers, developers and users. So we'll get answer from somebody in community. It is very helpful for maintainers.
Anyway, I'll take a look tomorrow :-)

**Comment by mgeier** [comment]
For reference, this is the forum thread: https://groups.google.com/d/topic/sphinx-users/0cDKO35c5IQ/discussion
