### ISSUE TITLE
invalid signature for automodule ('my_package.my_module.cpython-37m-x86_64-linux-gnu

### ISSUE THREAD

**Issue by twmr** [sphinx-doc/sphinx#6986]
**Describe the bug**

When I run sphinx-build on a project that contains c-extension modules the autodoc extension raises the following exception:
`sphinx.errors.SphinxWarning: invalid signature for automodule ('my_package.my_module.cpython-37m-x86_64-linux-gnu')`

This problem was probably introduced by #2546.

I nailed it down to a wrongly formatted file generated by sphinx-apidoc. In my case it contains the following entry

```
my_package.my_module.cpython\-37m\-x86\_64\-linux\-gnu module
--------------------------------------------------------------------------

.. automodule:: my_package.my_module.cpython-37m-x86_64-linux-gnu
   :members:
   :undoc-members:
   :show-inheritance:
```
Removing the string ".cpython-37m-x86_64-linux-gnu" from the `.. automodule::` line fixes the problem.

**To Reproduce**
```
<Paste your command-line here which cause the problem>

$ git clone https://github.com/.../some_project
$ cd some_project
$ pip install -r requirements.txt
$ cd docs
$ make html SPHINXOPTS="-D language=de"
$ # open _build/html/index and see bla bla
```

**Expected behavior**

**Your project**
Link to your sphinx project, or attach zipped small project sample.

**Screenshots**

**Environment info**
- OS: Linux
- Python version: 3.7
- Sphinx version: 2.3.1
- Sphinx extensions: sphinx.ext.autodoc

**Additional context**

- [e.g. URL or Ticket]

#2546

**Comment by tk0miya** [comment]
Fixed by #6987 
Thank you for reporting!
