### ISSUE TITLE
Raw substitution doesn't produce any output in man format

### ISSUE THREAD

**Issue by Lennonka** [sphinx-doc/sphinx#6988]
**Describe the bug**
Raw substitution doesn't produce any output in man format

**To Reproduce**
In conf.py:
```
rst_prolog = """
.. |br| raw:: man

   \\n.br
"""
```

In a rST file:
```
line before line break |br|
next line
```

```
> make man
```

|br| doesn't produce any output in the resulting man file:
```
line before line break 
next line
```

**Expected behavior**
The resulting man file should contain:
```
line before line break 
.br
next line
```

**Your project**
I can't publish the project.

**Environment info**
- OS: Ubuntu 18.04
- Python version: 3.6.9
- Sphinx version: 2.0.1
- Sphinx extensions:  none
- Extra tools: man, less

**Comment by tk0miya** [comment]
The formal name of man format builder is "manpage" builder, not "man" builder. So please give "manpage" for raw directive.

BTW, raw directive does not regard "\n" as a return code. So your example does not work even if renamed to manpage.
It seems folding a line before substitution working fine to me.
```
.. |br| raw:: manpage

   .br

line before line break
|br|
next line
```

Thanks,

**Comment by Lennonka** [comment]
Thank you! Perhaps adding it to docs might be useful?

**Comment by tk0miya** [comment]
I don't know it is useful. But please post a PR if you think so :-)
