### ISSUE TITLE
Allow conversion formats to be extensible in sphinx.ext.imgconverter

### ISSUE THREAD

**Issue by modelmat** [sphinx-doc/sphinx#6994]
**Is your feature request related to a problem? Please describe.**
The current sphinx.ext.imgconverter extension only supports a [few conversions](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/ext/imgconverter.py#L26-L30). I would like to add more conversions, as imagemagick already supports many more. 

**Describe the solution you'd like**
Be able to set a sphinx option and add more to the list.

**Describe alternatives you've considered**
1. Creating a new extension which adds them to the list

**Additional context**

**Comment by tk0miya** [comment]
Could you post a pull request please? I think conversion rule of imagemagick is static. So no APIs are needed for this case.

**Comment by modelmat** [comment]
Currently there are the three conversion formats.
If I want to add more to it (say, any other format that imagemagick supports) I have to PR to add it.

I can do this for the few formats I want, but it seems to me that it would be better if you could add extra conversion rules locally, so that there is no need to add a PR.

**Comment by tk0miya** [comment]
I consider adding APIs is very expensive approach because of conversion rule would not be changed dynamically. In addition, it would be better to add new rules imgconverter extension if useful. No reason to keep it on your local.

**Comment by modelmat** [comment]
I added support for the filetype I wanted in #6998 .
