### ISSUE TITLE
Xindy seems to crash due to inability to map memory

### ISSUE THREAD

**Issue by Daltz333** [sphinx-doc/sphinx#7015]
**Describe the bug**
My project is unable to build PDF due to xindy seeming to crash. Disabling xindy with ``latex_use_xindy`` is usable but not preferred due to potential translation and foreign languages being used.

```
------------                                                                                                                   
Run number 1 of rule 'makeindex firstroboticscompetition.idx'                                                                  
------------                                                                                                                   
------------                                                                                                                   
Running 'internal xindy -L english -C utf8  -M sphinx.xdy  -o "firstroboticscompetition.ind" "firstroboticscompetition.idx"'   
------------                                                                                                                   
Latexmk: calling xindy( -L english -C utf8 -M sphinx.xdy -o firstroboticscompetition.ind firstroboticscompetition.idx )        
Cannot map memory to address 0x8009908d2000 .                                                                                  
[/build/clisp-u7VYrq/clisp-2.49.20170913/src/spvw_mmap.d:498] errno = 12 (Latexmk: Errors, so I did not complete making targets
Collected error summary (may duplicate other messages):                                                                        
  makeindex firstroboticscompetition.idx: Command for 'makeindex firstroboticscompetition.idx' gave return code 1024           
Latexmk: Use the -f option to force complete processing,                                                                       
 unless error was exceeding maximum runs of latex/pdflatex.                                                                    
Makefile:33: recipe for target 'firstroboticscompetition.pdf' failed                                                           
make: *** [firstroboticscompetition.pdf] Error 12                                                                              
```
**To Reproduce**
```
$ git clone https://github.com/daltz333/frc-docs.git
$ sudo apt-get install -y python3
$ sudo apt-get install -y texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra latexmk texlive-lang-greek texlive-luatex texlive-xetex texlive-fonts-extra dvipng graphviz xindy
$ cd frc-docs
$ git checkout controls-docs
$ python3 -m pip install -r source/requirements.txt
$ make latexpdf
```

**Expected behavior**
Successful LatexPDF build without crashes.

**Your project**
``https://github.com/daltz333/frc-docs`` and then checkout ``controls-docs``

**Screenshots**

**Environment info**
- OS: Ubuntu 18.04 LTS
- Python version: 3.6.9 (also on 3.7.1 on a different machine)
- Sphinx version: 2.2.0
- Sphinx extensions:  
```
extensions = [
    'sphinx_tabs.tabs',
    'sphinx.ext.imgmath',
    'sphinx.ext.todo',
    'sphinx.ext.graphviz',
    'sphinx.ext.autosectionlabel',
    'sphinxcontrib.ghcontributors',
    'sphinxcontrib.remoteliteralinclude'
]
```
- Extra tools: Graphviz

**Additional context**
PDF output seems to have worked correctly in the past, however, if you look at my commit history in the ``controls-docs`` branch. You'll notice several latex heavy documents were created in the ``source/docs/software/advanced-controls/introduction/`` directory. These files seem to crash xindy for an unknown reason.

**Comment by tk0miya** [comment]
I found similar report on xindy project. And it says update it to latest one. I don't know your case is same as this. But it might be fixed.
https://sourceforge.net/p/xindy/bugs/61/

On my local, it seems xindy working fine.
```
FROM tk0miya/sphinx-pdf

RUN git clone https://github.com/daltz333/frc-docs.git
RUN apt-get install -y python3
RUN apt-get install -y texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra latexmk texlive-lang-greek texlive-luatex texlive-xetex texlive-fonts-extra dvipng graphviz xindy
WORKDIR /docs/frc-docs
RUN git checkout controls-docs
RUN python3 -m pip install -U setuptools pip
RUN python3 -m pip install -r source/requirements.txt
RUN make latexpdf
```

**Comment by Daltz333** [comment]
The sourceforge recommendation is to install TexLive-2019, however that is an *enormous* dependency, one that really is 😢 for a single package needed.

**Comment by tk0miya** [comment]
I noticed Ubuntu provides xindy-2.5.1. It's a latest release of xindy in CTAN.
https://packages.ubuntu.com/ja/bionic/xindy
https://www.ctan.org/tex-archive/indexing/xindy/base

The URL I pasted was an error on old xindy (the report says "not 2.4")
This would be an another bug of xindy. Could you file an issue to xindy project please? I think there are nothing to do on Sphinx side for this...

**Comment by Daltz333** [comment]
The workaround has been to disable Xindy. I'd like to keep this issue open in case anyone else has the same issue.
