### ISSUE TITLE
Absolute path used in translatable (.pot and .po) files

### ISSUE THREAD

**Issue by Harmon758** [sphinx-doc/sphinx#7019]
**Description**
[As I pointed out in the mailing list/Google Group](https://groups.google.com/forum/#!topic/sphinx-users/dcr_wp8f2mE), when using `make gettext`, the generated .pot files use the absolute path, rather than the relative path, to the relevant .rst files.
This applies to the .po files as well, when those are generated afterwards.

After some testing, I pinpointed this to Sphinx >= 2.3.0. Sphinx v2.2.2 uses the relative path as before.
I believe this is due to https://github.com/sphinx-doc/sphinx/commit/399f773d9dcd14d1ba27a74448ba9da5da7c7389, where `MessageCatalogBuilder` was changed from [using `sphinx.util.osutil.relpath`](https://github.com/sphinx-doc/sphinx/commit/399f773d9dcd14d1ba27a74448ba9da5da7c7389#diff-95414fb1f5965c3c8012bc793137fd13L275) (and `sphinx.util.osutil.canon_path`) to use a new `GettextRenderer` that uses `package_dir`:
https://github.com/sphinx-doc/sphinx/blob/399f773d9dcd14d1ba27a74448ba9da5da7c7389/sphinx/builders/gettext.py#L110-L113  which is constructed using [`os.path.abspath`](https://docs.python.org/3/library/os.path.html#os.path.abspath):
https://github.com/sphinx-doc/sphinx/blob/399f773d9dcd14d1ba27a74448ba9da5da7c7389/sphinx/__init__.py#L48

**Reproduction Steps**
Follow the steps at https://www.sphinx-doc.org/en/master/usage/advanced/intl.html#quick-guide.
The generated .pot files in step 3 will use the absolute path, e.g. `#: D:\GitHub\tweepy\docs\api.rst:6`.

**Expected Behavior**
The relative path, e.g. `#: ../../api.rst:6`, is used.

**Relevant Projects**
I tested this with [tweepy](https://github.com/tweepy/tweepy) and [discord.py](https://github.com/Rapptz/discord.py).

**Screenshots**
N/A

**Environment**
- OS: Microsoft Windows [Version 10.0.18363.535] (64-bit)
- Python version: 3.8.1
- Sphinx versions: 2.3.0 and 2.3.1
- Sphinx extension: sphinx.ext.autodoc
- Extra tools: N/A

**Additional Context**

- https://groups.google.com/forum/#!topic/sphinx-users/dcr_wp8f2mE

**Comment by tk0miya** [comment]
Thank you for explanation. Indeed this is a bug. I thought outputting absolute path is not wrong when I commented at forum. But it is an unintended change in 2.3, as you said.

**Comment by tk0miya** [comment]
Fixed by #7020 .
Thank you for reporting.
