### ISSUE TITLE
[Question] Custom command line variables and rst substitution

### ISSUE THREAD

**Issue by DexterMagnific** [sphinx-doc/sphinx#7022]
Dear all,

I'd like to pass custom variables through the command line with -D. For this I use the following code:

```
def setup(app):
    app.add_config_value('myVar', value, True)
```

Now I'd like to reference them in my .rst file using `|myVar|`, just like for `|version|` but I cannot make it work.

Can you tell me how can I achieve this ?

Thanks.

**Comment by tk0miya** [comment]
Sorry, this is not a forum. Please post questions to sphinx-users group instead: https://groups.google.com/forum/#!forum/sphinx-users

Thanks,

FYI: reST parser does not refer config values on substitution. So your example does not work.
