### ISSUE TITLE
:rfc: should format links to sections

### ISSUE THREAD

**Issue by verhovsky** [sphinx-doc/sphinx#7027]
When you do

```rst
:rfc:`7231#section-6.6.1`
```

it's rendered like this:

[RFC 7231#section-6.6.1](https://tools.ietf.org/html/rfc7231.html#section-6.6.1)

Instead, it should figure out that it's a section link and rendered it as something nicer:

[RFC 7231, Section 6.6.1](https://tools.ietf.org/html/rfc7231.html#section-6.6.1)

**Comment by davidfstr** [comment]
An example from an upcoming Python documentation change where improved "RFC section link rendering" would be nice: https://github.com/python/cpython/pull/102328#issue-1603178833

In that issue I suggest that

```
:rfc:`2616#section-5.1.2`
```

be formatted like "RFC 2616 §5.1.2"

**Comment by davidfstr** [comment]
It is possible to workaround the section formatting issue by providing the exact text of the link explicitly:

```rst
:rfc:`RFC 2616 §5.1.2 <2616#section-5.1.2>`
```

**Comment by jstasiak** [comment]
See https://github.com/sphinx-doc/sphinx/pull/11809 which implements this
