### ISSUE TITLE
if a project exists is there anyway to get a list of other projects docs linked to my project as a refrence via intersphinx 

### ISSUE THREAD

**Issue by Harshil-C** [sphinx-doc/sphinx#7028]
i was working for a project and found that one of the rst file called docrules is orphaned ,and i would like to remove the file if no other outer projects docs are not linked to it via intersphinx and among other docs inthe project itself.but i couldnt find anyway to know if  a file is liked by a doc .
is there anyway for that?
it would have been great if there where any method to find that ...

**Comment by tk0miya** [comment]
Unfortunately, there are no way to do that. out projects does not output logs and events on creating references.
Thanks,
