### ISSUE TITLE
Sphinx quickstart should add `master_doc` to conf.py

### ISSUE THREAD

**Issue by Helveg** [sphinx-doc/sphinx#7034]
**Describe the bug**
When using `sphinx-quickstart` no `master_doc` is added to `conf.py` even though the generated files do not contain the standard master document `contents.rst`. This continues to cause issues for many people new to ReadTheDocs (see for example https://github.com/readthedocs/readthedocs.org/issues/2569).

**To Reproduce**
Run and complete `sphinx-quickstart`

**Expected behavior**
Add a line `master_doc = 'index'` to `conf.py`

**Comment by tk0miya** [comment]
-0: I think rtd should upgrade to Sphinx to 2.0+. Is there any reason not to do that? I might agree with you if this proposal was posted at sooner 2.0 release. But it's time to go for 3.0.

**Comment by Helveg** [comment]
I'm not familiar enough with either RTD or sphinx to estimate this.

**Comment by stsewd** [comment]
At rtd we are in the process of updating the default sphinx version, but we recommend using a requirements file with a pinned version of sphinx you are using locally, so it doesn't break (or change unexpectedly) when we update the default version.

**Comment by tk0miya** [comment]
Thank you for comment. Good to hear. It would be nice if RTD provides newer version of Sphinx by default :-)
Anyway, we can use latest version of Sphinx with requirements.txt. I recommend you to use latest version of Sphinx. Hence adding `master_doc` is not good way. So I'm closing this now.
Thanks,
