### ISSUE TITLE
Some documentation improvements for theming / extending Sphinx

### ISSUE THREAD

**Issue by choldgraf** [sphinx-doc/sphinx#7044]
Over the last few months I have been working through the Sphinx documentation to work on [a new theme](https://github.com/pandas-dev/pydata-bootstrap-sphinx-theme). In that time there were a few questions I've had that weren't easily findable in the extension and theming documentation. This is an issue to keep track of this list. I'll include a link to where in the docs I think this information should be...

I think many of these would be good candidates for a short tutorial or other improvement in the docs. Would folks be friendly to a few PRs that add some of these explanations to the Sphinx documentation?

- [ ] link to "developing extensions page" in the HTML themes page (https://www.sphinx-doc.org/en/master/theming.html) https://github.com/sphinx-doc/sphinx/pull/7058
- [ ] How to create a function that a Jinja theme can then use (https://www.sphinx-doc.org/en/master/extdev/index.html#apis-used-for-writing-extensions, maybe https://www.sphinx-doc.org/en/master/theming.html) https://github.com/sphinx-doc/sphinx/pull/7058
- [ ] How to make an extension load and depend on another extension (https://www.sphinx-doc.org/en/master/extdev/index.html#apis-used-for-writing-extensions)
- [ ] How to ensure that static files are properly-linked in an extension or theme (https://www.sphinx-doc.org/en/master/theming.html) https://github.com/sphinx-doc/sphinx/pull/7058
- [ ] Using configuration variables inside javascript within Sphinx https://github.com/sphinx-doc/sphinx/pull/7058
- [ ] Clarify that any file-wide metadata key/val will work, not just the "officially recognized" ones: http://www.sphinx-doc.org/en/master/usage/restructuredtext/field-lists.html#file-wide-metadata

*Note, some of these questions might be in the docs somewhere, but I had a hard time finding them, so thought it would be worth documenting which issues I had in case it helps guide docs development*

*Double note: just to make clear, this issue shouldn't be treated as a complaint or criticism, but hopefully an attempt at constructive feedback for further improvement*

**Comment by tk0miya** [comment]
+1; It sounds good. New tutorial is welcome!

**Comment by danwos** [comment]
> How to make an extension load and depend on another extension

Is that even possible? Searched a lot for how to do that, but found for myself only "dirty" solutions.

See [Sphinx-Test-Reports Install notes](https://sphinx-test-reports.readthedocs.io/en/latest/install.html), which forces the user to add another sphinx-extension on top of ``extensions`` list by themselves. Otherwise the extension will not work.

**Comment by choldgraf** [comment]
@danwos I believe that this can be accomplished with `app.setup_extension`

https://www.sphinx-doc.org/en/master/extdev/appapi.html#extension-setup

E.g., in a theme I've got, I just tried adding `app.setup_extension("sphinx_copybutton")` to my `setup(app)` function and it worked!

**Comment by danwos** [comment]
Thanks, have totally overlooked that.

**Comment by choldgraf** [comment]
OK, I added a few items to this PR: https://github.com/sphinx-doc/sphinx/pull/7058
