### ISSUE TITLE
Regression bug on line numbers in error messages

### ISSUE THREAD

**Issue by barbara-sfx** [sphinx-doc/sphinx#7045]
**Describe the bug**
When errors display the line number containing the error, it is off by the number of lines in rst-prolog

**To Reproduce**

Add rst-prolog with whatever in conf.py

```
rst_prolog = """

.. |br| raw:: html

   <br />

.. |hr| raw:: html

   <hr />

"""
```

Add some text somewhere that will cause a warning during the build.

Paste your command-line here which cause the problem:

```
$ make html

```

**Expected behavior**
The correct line number is shown with the warning.

**Screenshots**

here is the error:
```
112: WARNING: toctree contains reference to nonexisting document u'.. APMv1 starts here'
```

here is the file:

![image](https://user-images.githubusercontent.com/17709550/72838735-e08ab300-3c5e-11ea-9a2b-dc6205f78f91.png)

The difference between 136 and 112 is 24, which is the number of lines in my rst-prolog section in conf.py

**Environment info**
- OS: Mac 10.14.6
- Python version: 2.7.11
- Sphinx version:  1.8.5
- Sphinx extensions:  recommonmark, sphinx_markdown_tables

**Additional context**
I reported this a while ago and it was fixed, so this is a regression.

**Comment by tk0miya** [comment]
Could you check this again with latest Sphinx? I suppose this was already fixed.

**Comment by barbara-sfx** [comment]
It seems as if I can't go higher than 1.8.5 unless I upgrade python, which I haven't done yet. Guess that's my next project.
