### ISSUE TITLE
Extension: How does sphinx handle image-data for different builders?

### ISSUE THREAD

**Issue by danwos** [sphinx-doc/sphinx#7054]
Hi,

In my Sphinx-Extensions I'm doing a lot of direct doctree updates.
And I use the docutils nodes and replace/manipulate existing ones.
So I do not render any generated rst-code nor use the statemachine.

I now have the problem, that I need to add some images on my own via docutils.nodes.image.
This works good (except #7032 ), but the used image-files need to be added to the output folder by my own.
Sphinx does not do this, because it looks like it is checking this stuff prior in the event chain.
Most of my actions happen in the ``doctree-resolved`` event.

However, Sphinx seems to use different output-folders for such data depending on the used builder.
E.g. ``html`` uses a ``_build/html/_static`` folder, which contains everything I have under ``src/_static``.

But for ``latex`` ``src/_static`` seems to be ignored and sphinx puts a lot of stuff directly under ``_build/latex`` (root-level!).
But only the stuff it has collected on its own from self-rendered rst code (e.g. image nodes) is added.
Later added image nodes or "src/_static" and "src/_images" are ignored.

So, **where to put data created during build time and added/referenced via docutils doctree updates**?

Is there any common folder to use or any api?
And even if there is a common folder, is the location of this folder for outputs always same?
That's important, as the used url inside docutils image nodes should be always the same.
But if e.g. html is using _static and latex is using its root folder, images can not be found for one of these builders.

**Comment by danwos** [comment]
Okay, mea culpa.
It looks like it is not enough to just add an image-node to the doctree.
Because in the function:
https://github.com/sphinx-doc/sphinx/blob/703303139cd35081bd11f6b8641209f499f954bf/sphinx/builders/__init__.py#L179

There is this line:
https://github.com/sphinx-doc/sphinx/blob/703303139cd35081bd11f6b8641209f499f954bf/sphinx/builders/__init__.py#L205-L207
Which means, every not registered image is ignored.
Even if it exists and is valid.

The image registration for ``env.images`` is done here:
https://github.com/sphinx-doc/sphinx/blob/703303139cd35081bd11f6b8641209f499f954bf/sphinx/environment/collectors/asset.py#L43
https://github.com/sphinx-doc/sphinx/blob/703303139cd35081bd11f6b8641209f499f954bf/sphinx/environment/collectors/asset.py#L90
I figured out that this function gets called during the event [doctree-read](https://www.sphinx-doc.org/en/master/extdev/appapi.html#event-doctree-read).
But my code was registered for [doctree-resolved](https://www.sphinx-doc.org/en/master/extdev/appapi.html#event-doctree-resolved), which gets called later.

Moving my functions to a prior event like ``doctree-read`` seems not possible, as I need resolved references, which are available from ``doctree-resolved`` on.

So I have to register the image in Sphinx by hand by using this call:
```app.env.images.add_file(docname, url)```

Is it possible to call such internal handling after really all  docutils-operations (even from extensions) are done? I see no reason, why images-collection is done already in ``doctree-read`` and not after/inside ``doctree-resolved``. But I'm just starting understanding the sphinx-internals, so any opinions from the experts are welcome. :)

**Comment by tk0miya** [comment]
The extensions which generates image at resolving phase is not assumed now. So there are no proper way to do that. But, as you said, `app.env.images.add_file()` would work well for your case.
