### ISSUE TITLE
Show linkcheck redirect in yellow, not red

### ISSUE THREAD

**Issue by mtvx** [sphinx-doc/sphinx#7055]
Currently, redirects are shown in RED:

![image](https://user-images.githubusercontent.com/94327/72978072-6bde8280-3dde-11ea-9117-0b79f21a01ef.png)

Also _errors_ are shown in red, but I don't think a redirect is that harmful. Maybe show redirects in yellow, rather?

**Comment by tk0miya** [comment]
Correctly, linkcheck shows redirects with HTTP status code 301 or 308 as red. Others are shown as purple or turquoise. 301 or 308 means the contents on the URL is moved **permanently**. It means the URL is deprecated and would be removed in future. So I feel it is needed to fix as sooner. So -0 to change it.

**Comment by mtvx** [comment]
A matter of taste, I guess. As the link is not broken (yet), then I think it's not as critical as an actual error.

The redirection could vanish in a day, or it could be there for the next 10 years, impossible to know. In any case, the link still works, at the moment, so I was hoping it wouldn't be marked as error.

**Comment by tk0miya** [comment]
Indeed, it is not an error at the moment. So it would be better to highlight it as warning. +0.

**Comment by tk0miya** [comment]
Merged. Thank you for proposal!

**Comment by mtvx** [comment]
Thanks for the speedy actions!
