### ISSUE TITLE
Allow to ignore individual links when running linkcheck

### ISSUE THREAD

**Issue by mtvx** [sphinx-doc/sphinx#7056]
[Linkcheck](http://www.sphinx-doc.org/en/master/usage/configuration.html?highlight=linkcheck#options-for-the-linkcheck-builder) already supports `linkcheck_ignore` option, but it's a global option. We need a way to locally mark a link as ignored of linkchecker.

There are multiple scenarios where this would be useful, simplest example is something like this

> That API is located at https://some.host.somewhere.com/v3/

However, our API returns 404 on main level (you need to know exact path, for security reasons).

I sure can ignore this by:

    ``https://some.host.somewhere.com/v3/``
    `https://some.host.somewhere.com/v3/ <#>`_

Also, I could ignore this in `linkcheck_ignore` but it's kinda cumbersome (because this is local override, why put it into global options).

Also, I don't actually want to break the link. I want the text show as hyperlink (because it looks nice), and lead user to the page which returns 404 because it's just fine, the API is really there.

**Comment by tk0miya** [comment]
What do you mean "locally"? I guess you're saying to add a new syntax or mark-ups, right?

**Comment by mtvx** [comment]
To avoid introducing new markup, maybe ignore all links with certain anchor? E.g. `https://somewhere.com/v3#ignore-linkcheck` or something like that?

A bit ugly, but wouldn't require major changes...

**Comment by SuperKogito** [comment]
well from [docs](http://www.sphinx-doc.org/en/master/usage/configuration.html?highlight=linkcheck#options-for-the-linkcheck-builder), it seems that you can simply do that by combining regular expressions with your base link.

**Comment by mtvx** [comment]
@SuperKogito Uh, you're absolutely correct, I can just use a regex pattern.

Sorry for my stupidity, closing...
