### ISSUE TITLE
Improve role slices in names

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#707]
In languages such as Javascript or C++, namespaces can get fairly deeply nested.

In this case, the `~` slice becomes nice (e.g. `:ref:`~foo.bar.baz.Qux.quux``only displays`quux()` in the document), but this incurs a loss in readability if it slices into a separate class: the document author probably does not want the fully qualified namespace (for verbosity reasons), but having more than just the method name would be nice, for instance to have the class name as well.

I propose that the `~` syntax be extended with an index, which would give the (maximum) number of items displayed from the end: `~2` would display the last two items of the chain instead of only the last one.

With the dotted path above, you would get:

```
    ~foo.bar.baz.Qux.quux
        outputs quux()
    1~foo.bar.baz.Qux.quux
        outputs quux()
    2~foo.bar.baz.Qux.quux
        outputs Qux.quux()
    3~foo.bar.baz.Qux.quux
        outputs baz.Qux.quux()
    4~foo.bar.baz.Qux.quux
        outputs bar.baz.Qux.quux()
    5~foo.bar.baz.Qux.quux
        outputs foo.bar.baz.Qux.quux()
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/707
- Originally reported by: [masklinn](https://bitbucket.org/masklinn)
- Originally created at: 2011-05-27T11:12:39.826

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2011-09-21 07:29:16+00:00_

Sounds interesting and useful.

**Comment by shimizukawa** [comment]
I don't know the usefulness of this feature, but the ticket is old and nobody commented, so I feel that there are no potential users of this feature. I think that it is good to close.

**Comment by tk0miya** [comment]
+0 for closing. At least, nobody post comments and PRs for this while 8 years.
