### ISSUE TITLE
Add support for svgbob ASCII diagrams

### ISSUE THREAD

**Issue by virtualritz** [sphinx-doc/sphinx#7070]
[Svgbob](https://ivanceras.github.io/svgbob-editor/) allows turning ASCII diagrams into SVG.

It is a command line tool that uses `stdin` for the text and `stdout` for the SVG.

It would be very cool to have the ability to draw diagrams inside reST and have them show up as SVG in the resulting compiled docs.

Repo is [here](https://github.com/ivanceras/svgbob).

**Comment by tk0miya** [comment]
Thank you for your proposal. But -1 for your idea. It would be better to make an extension for svgbob. No reason to add it to sphinx-core.
Thanks,

**Comment by virtualritz** [comment]
Is there a repo where 'official' extensions are being developed where such a feature request would be better placed?

**Comment by tk0miya** [comment]
If you'd like to ask to develop it to somebody, sphinx-users forum is good for that purpose.
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!forum/sphinx-users
