### ISSUE TITLE
Sphinx update to v2.2.2 causes breathe's testsuite to fail

### ISSUE THREAD

**Issue by D4N** [sphinx-doc/sphinx#7085]
**Describe the bug**

The breathe sphinx extension suddenly started to show test failures once sphinx got updated to 2.2.2 with the error message "Domain 'c' is not registered" (the full report can be found here: https://github.com/michaeljones/breathe/issues/465).

This issue did not occur with 2.1.2, but unfortunately I haven't found a thing in the changelog that would warant such a failure. Is there anything I am missing here?

**Comment by tk0miya** [comment]
At e42d546685, `CDomain` uses to call `env.get_domain()` API to get the instance of C domain as result of refactoring. I think this is minor and non breaking change. It seems breathe uses many mock object to create Sphinx application object. I thought this is a bug of the mock.

I think large mocks does not work well. So it would be better to use real Sphinx application object using `sphinx.testing` framework.

**Comment by D4N** [comment]
Thank you very much for the pointer @tk0miya! I was able to find a crude workaround that fixes the test failure (unfortunately I don't have the knowledge to port breathe's testsuite to pytest & `sphinx.testing`, which would be the better solution).
