### ISSUE TITLE
HTML builder's caching is broken by material theme

### ISSUE THREAD

**Issue by dzhu** [sphinx-doc/sphinx#7093]
**Describe the bug**
The [sphinx-material](https://github.com/bashtage/sphinx-material/) package provides an HTML context object that [contains functions as values](https://github.com/bashtage/sphinx-material/blob/aebde13c30dd4bc63159482d5b6a87fc3f211556/sphinx_material/__init__.py#L242). As a result, the [config hash](https://github.com/sphinx-doc/sphinx/blob/e7a0af807a58f97be826c19644fac72b50fb6769/sphinx/builders/html.py#L70) in the `.buildinfo` generated by the HTML builder changes on every build, since it includes the `str` of a function, which includes an address in memory that changes each time (e.g., `<function table_fix at 0x7f5dcdef2738>`). Therefore the caching is broken and Sphinx does a full rebuild each time (e.g., `building [html]: targets for 1 source files that are out of date` even when nothing has changed).

**To Reproduce**
```
$ wget https://github.com/sphinx-doc/sphinx/files/4146498/sphinx-test.zip
$ unzip sphinx-test.zip
$ cd sphinx-test
$ pip install -r requirements.txt
$ make html
...
building [html]: targets for 1 source files that are out of date
...
$ make html
...
building [html]: targets for 1 source files that are out of date
...
```

**Expected behavior**
Running Sphinx twice in a row should use the cache and not rebuild everything; 0 files should be considered out of date.

**Your project**
Example project: [sphinx-test.zip](https://github.com/sphinx-doc/sphinx/files/4146498/sphinx-test.zip)

**Environment info**
- OS: Arch Linux
- Python version: 3.6.8/3.8.1
- Sphinx version: 2.2.2/2.3.1
- Sphinx extensions: [sphinx-material](https://github.com/bashtage/sphinx-material/)
- Extra tools: none

**Additional context**
I've also opened [an issue on the sphinx-material repo](https://github.com/bashtage/sphinx-material/issues/27), since I don't know whether this case is intended to be supported or not.

**Comment by bashtage** [comment]
The workaround I used was to produce a function that has a fixed `str` representation across instances as long as the SHA512 of the function's source is identical. Sphinx uses md5(str(obj).encode()).hexdigest() when checking if a config is the same.  Standard functions have random ids in their str, even when they are unchanged, across python sessions and so fail this test.

**Comment by tk0miya** [comment]
It might be fixed this by Sphinx side with ignoring non-literal objects on hashing. But I wonder such fix is really useful. Sphinx expects all config values are picklable. It means lambda functions and functions in conf.py would be failed to build.  So I don't recommend to use such objects for config variables...

**Comment by bashtage** [comment]
It is neither.  The functions are defined in the theme package. They are used to modify content where it is too hard for me to figure out how to fix it a more official way, e.g., rendering the toc.

IOW, everything pickles fine.

**Comment by tk0miya** [comment]
Okay, please forget my comment.

@dzhu It seems this was fixed by sphinx-material side. If it's fine, please close this issue.

Thanks,

**Comment by bashtage** [comment]
I think it would not be safe for Sphinx to try and fix this since by default it cannot be sure that the functions are identical without the theme author making that guarantee.

**Comment by dzhu** [comment]
Looks like it's fixed indeed. Thanks for the quick response!

**Comment by tk0miya** [comment]
Good to hear :-)
