### ISSUE TITLE
binned detector height incorrectly rounded to 94 (from 96.3) for 5x5 binning

### ISSUE THREAD

**Issue by asproutagus** [sphinx-doc/sphinx#7100]
** Bug Description **
Using the EMSPHINX wizard in version 0.2 to index a scan taken with 5x5 binning causes the binned detector width (taken from the up2 file) to be rounded up from 93.6 pix to 94 pix. This value is unable to be changed (the box is grayed out in the software), so the rounded (incorrect) binned detector width propagates throughout the other calculation steps; the unbinned detector width is calculated to be 470 (94 * 5) when in fact the real value should be 468 (93.6 * 5). This ultimately results in incorrect pattern center values, which causes the final re-indexed scan to be entirely black despite the fact that the raw confidence indices (when the scan was originally taken) had an average value of 0.5. Fiddling with the pattern center values will get SOME color to show up in the reindexed png, but it's very noisy and still full of black spots.

**Screenshots**
<img width="429" alt="screenshot1" src="https://user-images.githubusercontent.com/35269133/73881203-c4694300-4814-11ea-8283-e98668e3b400.PNG">
<img width="429" alt="screenshot2" src="https://user-images.githubusercontent.com/35269133/73881204-c4694300-4814-11ea-91b3-e4589ffefdd5.PNG">
<img width="424" alt="screenshot3" src="https://user-images.githubusercontent.com/35269133/73881199-c3381600-4814-11ea-9d1b-ace716db2332.PNG">
<img width="425" alt="screenshot4" src="https://user-images.githubusercontent.com/35269133/73881201-c3d0ac80-4814-11ea-9eb9-6c1cc4052cd9.PNG">
<img width="430" alt="screenshot5" src="https://user-images.githubusercontent.com/35269133/73881202-c3d0ac80-4814-11ea-81b7-1d5a79640783.PNG">

**Environment info**
- OS: Win64
- Python version: 3.7.1
- Sphinx version: 0.2

**Comment by tk0miya** [comment]
Sorry, but I think you're posting a issue to wrong project. This is Sphinx; the "document generator". 
I guess corrrect project might be here: https://github.com/EMsoft-org/EMSphInx
