### ISSUE TITLE
Could Sphinx allow conf.py to raise an exception that generates a user-friendly error message?

### ISSUE THREAD

**Issue by pm215** [sphinx-doc/sphinx#7108]
For the QEMU project, we want to ensure that the user doesn't accidentally build our docs with a Sphinx that's based on too old a version of Python. (We have some local Sphinx extensions, and we want to be able to write them making the same assumption we do elsewhere in the project about what Python facilities are available. For standalone scripts we check the python version in our configure script, but Sphinx extensions get run with whatever Python Sphinx is using, so we'd like our conf.py to check this rather than letting the user proceed and get confusing messages or wrong behaviour later.)

We have a check in conf.py like this:
```
if sys.version_info < (3,5):
    raise VersionRequirementError(
        "QEMU requires a Sphinx that uses Python 3.5 or better\n")
```
which works, but the output presented to the user has a python traceback in it:
```
Configuration error:
There is a programable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/config.py", line 157, in __init__
    execfile_(filename, config)
  File "/usr/lib/python2.7/dist-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/home/petmay01/.local/lib/python2.7/site-packages/six.py", line 709, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "conf.py", line 40, in <module>
    "QEMU requires a Sphinx that uses Python 3.5 or better\n")
VersionRequirementError: QEMU requires a Sphinx that uses Python 3.5 or better
```

It would be nice if Sphinx provided a mechanism for a conf.py to cause the build to fail and report an error to the user which was presented more neatly, without the backtrace. I think the relevant code here is eval_config_file() in config.py, which special-cases SyntaxError and SystemExit and otherwise puts in a Python backtrace for anything else.

(It doesn't need to be VersionRequirementError, obviously -- that was just a plausible seeming exception to use to me. In an actual extension you can use ExtensionError() for this purpose, but throwing that from conf.py gives a backtrace too.)

**Comment by tk0miya** [comment]
I understand you'd like to raise an error intentionally. I'll make a PR to indicate an error to Sphinx apps from conf.py via throwing `ConfigError`.

**Comment by tk0miya** [comment]
#7108 merged.
Thank you for proposal.
