### ISSUE TITLE
No module named 'sphinx.quickstart'

### ISSUE THREAD

**Issue by avinashsai** [sphinx-doc/sphinx#7111]
OS: Ubuntu 18.04

I have installed Sphinx using sudo apt-get install python3-sphinx. However, when I ran sphinx-quickstart it gives following error:

File "/usr/bin/sphinx-quickstart", line 14, in <module>
    from sphinx.quickstart import main
ModuleNotFoundError: No module named 'sphinx.quickstart'

**Comment by tk0miya** [comment]
It seems Sphinx is not installed correctly. I don't know this is a bug of Ubuntu's package or problem of your environment. Could you try to reinstall it again. If reinstalling does not fix the error, please report this to ubuntu community.
Thanks,
