### ISSUE TITLE
sphinx-quickstart shows Mojibake characters around a question line

### ISSUE THREAD

**Issue by t2y** [sphinx-doc/sphinx#7118]
**Describe the bug**

sphinx-quickstart command asks some questions, however it shows Mojibake characters around question lines. See below screenshot.

I guess this issue is my environment issue and not come from sphinx. But, I file to share as an information. Hopefully, someone shares us how to resolve.

**To Reproduce**

```bash
(sphinx3) $ pip install sphinx
(sphinx3) $ sphinx-quickstart --version
sphinx-quickstart 2.3.1
```

```bash
(sphinx3) $ export LANG=en_US.UTF-8
(sphinx3) $ sphinx-quickstart 
```

```bash
(sphinx3) $ LC_ALL=C.UTF-8 sphinx-quickstart
```

**Expected behavior**

There are no Mojibake characters.

**Screenshots**

![sphinx-quickstart-en-mojibake1](https://user-images.githubusercontent.com/96569/74094646-06053100-4b28-11ea-858f-68bd44603aca.png)

**Environment info**

- OS: [Ubuntu 18.04.3]
```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
```

- Python version: [3.8.1]
- Sphinx version: [2.3.1]
- Sphinx extensions:  [none]
- Extra tools: [gnome-terminal]

```bash
$ gnome-terminal --version
# GNOME Terminal 3.28.2 using VTE 0.52.2 +GNUTLS -PCRE2
```

**Comment by t2y** [comment]
I found that `python` interpreter in my environment didn't have readline extension.

```
WARNING: The Python readline extension was not compiled. Missing the GNU readline lib?
```

After I installed `libreadline-dev` and re-compiled `python` interpreter, I confirmed this issue won't be reproduced.

```bash
$ sudo apt install -y libreadline-dev
$ pyenv install 3.8.1
```

**Comment by tk0miya** [comment]
It seems escape sequence characters for readline are output even if the library not found. Finally I can't create the reproducible environment. But I suppose this can be fixed.
