### ISSUE TITLE
Use svg file for plantuml graphics

### ISSUE THREAD

**Issue by septatrix** [sphinx-doc/sphinx#7134]
Currently the image on the page https://www.sphinx-doc.org/en/master/usage/advanced/intl.html is a png, however a svg would yield a higher quality. It should in theory be possible to specify svg format in doc/_static/translation.puml.

**Comment by tk0miya** [comment]
Contribution is always welcome!

**Comment by software2Daniel** [comment]
Enter this article to know the best paid careers in the world

https://sites.google.com/aprendizajesignificativo.org/top-10-pagas/p%C3%A1gina-principal
