### ISSUE TITLE
`code-block:: guess` does not work

### ISSUE THREAD

**Issue by yan12125** [sphinx-doc/sphinx#7139]
**Describe the bug**
I'm building a document with an HTML code block. Using `code-block:: guess` fails. `code-block:: html` still works.

**To Reproduce**
1. Create an empty `conf.py` and `index.rst` with the following content:
```
.. code-block:: html

    <div></div>
```
2. Run `sphinx-build -W . _build`. It fails with:

> /home/yen/tmp/sphinx-bug/index.rst:1:Could not lex literal_block as "guess". Highlighting skipped.

**Expected behavior**
Sphinx+Pygments identifies that code block as HTML and highlights it.

**Your project**
The example above is actually from https://github.com/buildbot/buildbot/blame/master/master/docs/manual/customization.rst#L1255. Many patches are required to reproduce the issue so I split out the relevant file here.

**Screenshots**
N/A - build issue

**Environment info**
- OS: Arch Linux up-to-date
- Python version: 3..1
- Sphinx version: 2.4.1
- Sphinx extensios: none
- Extra tools: none

**Additional context**
If I replace the following line

https://github.com/sphinx-doc/sphinx/blob/v2.4.1/sphinx/highlighting.py#L144

with
```Python
lexer = guess_lexer(source, **opts)
```
then `code-block:: guess` works again.

**Comment by tk0miya** [comment]
Fixed. Thank you for reporting!

**Comment by yan12125** [comment]
Thanks, it works now!
