### ISSUE TITLE
(debug?) output printed to stdout during compilation

### ISSUE THREAD

**Issue by antonio-rojas** [sphinx-doc/sphinx#7170]
**Describe the bug**
During compilation of an rst file to text output, some debug output is printed on top of the compilation output. Seems to come from https://github.com/sphinx-doc/sphinx/blob/2.0/sphinx/writers/text.py#L921

**To Reproduce**
Run the following code
```
import os
from sphinx.application import Sphinx

os.system('touch conf.py')

with open('index.rst', 'w') as filed:
    filed.write(r"""        .. NOTE::
            Foo
""")

sphinx_app = Sphinx('.', '.', 'out', '.', 'text')
sphinx_app.build()
```

**Environment info**
- OS: Linux
- Python version: 3.8.1
- Sphinx version: 2.4.1

**Comment by tk0miya** [comment]
Oh my bad, it's my mistake in #6869
Thank you for letting me know!

**Comment by tk0miya** [comment]
Fixed.
