### ISSUE TITLE
Exception occurred:   File "/usr/lib/python3/dist-packages/sphinx/search/fr.py", line 14, in <module>     import Stemmer ModuleNotFoundError: No module named 'Stemmer' The full traceback has been saved in /tmp/sphinx-err-yza2efq0.log

### ISSUE THREAD

**Issue by MacDev1** [sphinx-doc/sphinx#7172]
**Describe the bug**

**To Reproduce**
```
Exception occurred:
  File "/usr/lib/python3/dist-packages/sphinx/search/fr.py", line 14, in <module>
    import Stemmer
ModuleNotFoundError: No module named 'Stemmer'
The full traceback has been saved in /tmp/sphinx-err-yza2efq0.log, if you want to report the issue to the developers.


$ git clone https://github.com/.../some_project
$ cd some_project
$ pip install -r requirements.txt
$ cd docs
$ make html SPHINXOPTS="-D language=de"
$ # open _build/html/index and see bla bla
```

**Expected behavior**

**Your project**
Link to your sphinx project, or attach zipped small project sample.

**Screenshots**

**Environment info**
- OS: [e.g. Unix/Linux/Mac/Win/other with version]
- Python version: [e.g. 3.7.1]
- Sphinx version: [e.g. 1.8.2]
- Sphinx extensions:  [e.g. sphinx.ext.autodoc, recommonmark]
- Extra tools: [e.g. Browser, tex or something else]

**Additional context**

- [e.g. URL or Ticket]

**Comment by MacDev1** [comment]
This happened when I tried to run this command : make html

**Comment by tk0miya** [comment]
>Sphinx version: [e.g. 1.8.2]

Sphinx-1.8 is too old. Please update to latest one.

In addition, I can't find the line `import Stemmer` in our repository
https://github.com/sphinx-doc/sphinx/blob/v1.8.2/sphinx/search/fr.py#L14


If you're installing Sphinx via distribution's package, please ask to package maintainer.
Thanks,

**Comment by MacDev1** [comment]
I got this when I installed FR language. But while using EN language everything is OK

**Comment by dkgs** [comment]
I got the same problem on Armbian Focal.

Installing from distribution's package : Sphinx 1.8.5
When setting the language to french : same problem.

Installing the package python3-stemmer solved the issue.

**Comment by fconil** [comment]
I got the same problem on Ubuntu 20.04 but not on all docs
I had a problem with the project where conf.py contained "language = 'fr'" and no problem on the project where language is not defined.
Installing python3-stemmer solved the issue.
