### ISSUE TITLE
Since version 2.4.0 sphinx.ext.autodoc raises TypeError for self.objpath[-1]

### ISSUE THREAD

**Issue by ipaleka** [sphinx-doc/sphinx#7178]
**Describe the bug**
Since version 2.4.0 Sphinx raises TypeError in sphinx.ext.autodoc. Everything works fine with <=2.3.1.
```
  File "/home/ipaleka/dev/venvs/posandpdf/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py", line 1427, in add_directive_header
    if self.objpath[-1] in annotations:
TypeError: argument of type 'NoneType' is not iterable
```

**To Reproduce**
```
make html  # or any other target
```

**Expected behavior**
It should run with only the warnings if any.

**Environment info**
- OS: Linux debian 5.4.0-3-amd64 #1 SMP Debian 5.4.13-1 (2020-01-19) x86_64 GNU/Linux
- Python version: 3.7.6 (CPython)
- Sphinx version: v2.4.1
- Sphinx extensions:  sphinx.ext.autodoc

**Additional context**

- 
[sphinx-err-r94n7mzi.log](https://github.com/sphinx-doc/sphinx/files/4216959/sphinx-err-r94n7mzi.log)

**Comment by tk0miya** [comment]
Thank you for reporting. Fixed.
