### ISSUE TITLE
link of usage/restructuredtext/basics.html#sections is broken on sphinx-doc.org/ja

### ISSUE THREAD

**Issue by yukota** [sphinx-doc/sphinx#7181]
**Describe the bug**
link in document of spinx-doc(ja) is broken.
https://www.sphinx-doc.org/ja/master/usage/restructuredtext/basics.html#sections

>  `Pythonドキュメントでのスタイルガイド<https://docs.python.org/devguide/documenting.html#style-guide>`_ 

is expected to linked to https://docs.python.org/devguide/documenting.html#style-guide
but actually linked to https://www.sphinx-doc.org/ja/master/usage/restructuredtext/basics.html#id3

**To Reproduce**
1. open below url
https://www.sphinx-doc.org/ja/master/usage/restructuredtext/basics.html#sections

2. click "Pythonドキュメントでのスタイルガイド"

**Expected behavior**
expected to linked to https://docs.python.org/devguide/documenting.html#style-guide
but actually linked to https://www.sphinx-doc.org/ja/master/usage/restructuredtext/basics.html#id3

**Your project**
https://www.sphinx-doc.org/ja/master/usage/restructuredtext/basics.html#sections

**Screenshots**
None

**Environment info**
- OS: Ubuntu 19.10(LANG=ja_JP.UTF-8)
- Browser: Google Chrome 80.0.3987.100

**Additional context**
None

**Comment by shimizukawa** [comment]
Thanks for your reporting!
refs:
* https://twitter.com/shimizukawa/status/1229782592762740736
* https://www.transifex.com/sphinx-doc/sphinx-doc/
