### ISSUE TITLE
`*args` and `**kwarg` in type comments are not handled properly in 2.4.2.

### ISSUE THREAD

**Issue by toshihikoyanase** [sphinx-doc/sphinx#7184]
**Describe the bug**
Sphinx 2.4.2 failed to handle type comments for  `*args` or `**kwargs`.

This problem was originally reported in https://github.com/optuna/optuna/pull/942.

**To Reproduce**
```
$ git clone http://github.com/optuna/optuna.git
$ cd optuna
$ git checkout 6156ea7432d62da26924c16b3a2632889e6c21aa
$ pip install -e .
$ pip install .\[document\]
$ cd docs
$ make html
$ # open build/html/reference/integration.html
```

I found the following error when I executed `make html`:
```
WARNING: error while formatting arguments for optuna.integration.lightgbm.train: local variable 'arg' referenced before assignment
```

The definition of `optuna.integration.lightgbm.train` is [here](https://github.com/optuna/optuna/blob/6156ea7432d62da26924c16b3a2632889e6c21aa/optuna/integration/lightgbm_tuner/__init__.py).

```python
def train(*args, **kwargs):
    # type: (Any, Any) -> Any

...
```

The entry for `optuna.integration.lightgbm.train` cannot be found in build/html/reference/integration.html.

**Expected behavior**

**Your project**
https://github.com/optuna/optuna

**Environment info**
- OS: Mac
- Python version: 3.7.2
- Sphinx version: 2.4.2
- Sphinx extensions: 
    - sphinx.ext.autodoc
    - sphinx.ext.doctest
    - sphinx.ext.intersphinx
    - sphinx.ext.mathjax
    - sphinx.ext.napoleon
    - sphinx.ext.viewcode
    - sphinx.ext.githubpages
- Extra tools: Chrome

**Additional context**
- I think I can resolve this issue with [a small fix](https://github.com/sphinx-doc/sphinx/compare/3.x...toshihikoyanase:fix_property_access_of_vararg). So, I created a PR #7185.
- The problem in optuna was resolved by https://github.com/optuna/optuna/pull/943. I used Python3-style type hinting instead of type comments.

**Comment by tk0miya** [comment]
Thank you for reporting and contributing!
Will be released as 2.4.3 within a day.
