### ISSUE TITLE
Windows compiled help hides last line in Literal Block with horizontal scrollbar

### ISSUE THREAD

**Issue by AJNeufeld** [sphinx-doc/sphinx#7188]
**Description**
With a literal text block containing a long line, a horizontal scrollbar appears at the bottom of the text block.  In Sphinx 1.8.5 and earlier, the scrollbar was below the last line.  In Sphinx 2.0.0 through 2.4.1, the scrollbar is on top of, obscuring the last line of the literal text block.

**To Reproduce**

```
html_theme = 'classic'
py -3.7 setup.py build_sphinx -b htmlhelp
hhc.exe build\sphinx\htmlhelp\project.hhp
build\sphinx\htmlhelp\project.chm
```

**Expected behavior**
Horizontal scrollbar in literal text block of compiled help file should be below bottom of text, not covering last line of text

**Screenshots**
![image](https://user-images.githubusercontent.com/16822261/74956998-864f5000-53cc-11ea-81e6-b88a88bdd71b.png)

**Environment info**
- OS: [Win 10]
- Python version: [3.7.4]
- Sphinx version: [2.0.0]
- Sphinx extensions:  []
- Extra tools: [Windows Help Compiler]

**Comment by tk0miya** [comment]
Could you try it again with latest Sphinx and sphinxcontrib-htmlhelp? This might be related with #6685.

**Comment by AJNeufeld** [comment]
Confirmed: Problem still exists in 2.4.2

I've created a [repo](https://github.com/AJNeufeld/sphinx-issue-7188) demonstrating the problem.

Running ``build.bat`` will execute each of the following commands to update to the specific versions of Sphinx, then build the compiled help file.
- ``pip install --user sphinx==1.8.5``
- ``pip install --user sphinx==2.0.0``
- ``pip install --user sphinx==2.4.2``

Finally, it will open all 3 generated compiled help files, for comparison.

**Notes**:
- First line of ``build.bat`` file has path to HTML Help Workshop.  Ensure it correct for your environment.
- Launcher explicitly requests Python 3.7; this was to prevent poisoning my 3.8 environment.  Feel free to adjust this as desired as well.

**Comment by AJNeufeld** [comment]
It is related to #6685.  Adding ``html4_writer = True`` to ``conf.py`` fixes the horizontal scrollbar position.  (Tested in Sphinx 1.8.5, 2.0.0, 2.4.2)

Since Sphinx 2.4.2 was released 2 days ago, and the the issue was closed 12 days ago, I'm guessing I actually need to wait for sphinxcontrib-htmlhelp 1.0.3 to be released.

**Comment by tk0miya** [comment]
OMG, I've not noticed the fix in htmlhelp extension did not released yet...
Thank you for letting me know.

**Comment by tk0miya** [comment]
I just upload sphinxcontrib-htmlhelp-1.0.3. Could you try it please? @AJNeufeld

**Comment by AJNeufeld** [comment]
Verified.  With sphinxcontrib-htmlhelp-1.0.3, sphinx 1.8.5, 2.0.0, and 2.4.2 all produce output where the last line is never obscured by the scrollbar.

Thanks!

**Comment by tk0miya** [comment]
Thanks!
