### ISSUE TITLE
autodoc + classmethod coroutines do not play well together

### ISSUE THREAD

**Issue by ewjoachim** [sphinx-doc/sphinx#7189]
**Describe the bug**
When trying to use autodoc to generate documentation for an async classmethod, the method is shown as a classmethod, not mentionning that it is a coroutine

**To Reproduce**
Python code:
```py
class Test:
    @classmethod
    async def a(cls):
        """yay"""
        pass
```
Documentation:
```rst
.. autoclass:: procrastinate.aiopg_connector.Test
    :members:
```

Generated rst:
```rst
.. py:class:: Test
   :module: procrastinate.aiopg_connector

   .. py:method:: Test.a()
      :module: procrastinate.aiopg_connector
      :classmethod:
   
      yay
      
```

Generated doc:
![Screenshot from 2020-02-21 15-11-02](https://user-images.githubusercontent.com/1457576/75041221-6eef9000-54bc-11ea-9b4f-febff513d151.png)

**Expected behavior**
Method should appear as an `async classmethod`, not just a `classmethod`

**Your project**
https://github.com/peopledoc/procrastinate

**Screenshots**
see above

**Environment info**
- OS: Linux
- Python version: 3.7.3
- Sphinx version: 2.4.2
- Sphinx extensions: 
```python
extensions = [
    "sphinx.ext.napoleon",
    "sphinx.ext.autodoc",
    "sphinx_autodoc_typehints",
    "sphinxcontrib.programoutput"
]
```
- Extra tools: not applicable

**Additional context**
I've tried [sphinxcontrib-asyncio](https://pythonhosted.org/sphinxcontrib-asyncio/) and they have the exact same problem but reverse: they indicate it's async, but not a classmethod.

**Comment by tk0miya** [comment]
Thank you for reporting. Good point!
