### ISSUE TITLE
namedtuple autosummary complains about index() and count() methods

### ISSUE THREAD

**Issue by dizcza** [sphinx-doc/sphinx#7198]
In `sparse/greedy_pursuit.py` source file:

```
Solution = namedtuple("Solution", ("x", "support", "residuals"))
```

The .rst file is

```
.. automodule:: sparse.greedy_pursuit
   :members:
```

`make html` warns

```
/home/dizcza/PycharmProjects/SparseRepresentation/sparse/greedy_pursuit.py:docstring of sparse.greedy_pursuit.Solution.rst:29: WARNING: autosummary: stub file not found 'sparse.greedy_pursuit.Solution.count'. Check your autosummary_generate setting.
/home/dizcza/PycharmProjects/SparseRepresentation/sparse/greedy_pursuit.py:docstring of sparse.greedy_pursuit.Solution.rst:29: WARNING: autosummary: stub file not found 'sparse.greedy_pursuit.Solution.index'. Check your autosummary_generate setting.
```

I don't have any `autosummary_generate` defined in `conf.py` which has been created by `sphinx-quickstart` default run. The only thing I modified is a list of extensions below.

**Environment info**
- OS: Ubuntu 18.04
- Python version: 3.7
- Sphinx version: 2.4.2
- Sphinx extensions:  
```
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.autosummary',
    'sphinx.ext.doctest',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.imgmath',
    'sphinx.ext.viewcode',
    'sphinx.ext.mathjax',
    'numpydoc',
]
```

**Comment by tk0miya** [comment]
Please add `autosummary_generate = True` in your conf.py. It is required settings for autosummary.

**Comment by tk0miya** [comment]
Hmm? It's strange. You're using `automodule` directive. But warning says you're using `autosummary` directive. I guess you're confused. automodule is a directive of autodoc extension, and autosummary is a directive of autosummary extension. Please check your document again.

**Comment by dizcza** [comment]
Now I'm confused.

My .rst file is exactly as I posted above.
Adding `autosummary_generate = True` in conf.py does not help.

**Comment by tk0miya** [comment]
Anyway, here is not a forum of sphinx. It is not good for question. Please post it again to sphinx-users forum: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!forum/sphinx-users

Thanks,
