### ISSUE TITLE
Add a summary of build phases and core events

### ISSUE THREAD

**Issue by choldgraf** [sphinx-doc/sphinx#7215]
In the documentation, there is a lot of good detail about each individual event that happens (e.g.: https://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx-core-events). However, it can be hard to wrap your head around the high-level picture of what happens over the course of a whole build.

In a project we are working on @chrisjsewell gave a really nice description of the birds-eye view of the build process. I am wondering if this could be added into the docs somewhere, because I think it'd be useful.

Here's his description - does it look correct, and if so, would it be useful to add as a PR? Maybe to https://www.sphinx-doc.org/en/master/extdev/index.html#build-phases ?

```
1. event.config-inited(app,config)
2. event.builder-inited(app)
3. event.env-get-outdated(app, env, added, changed, removed)
4. event.env-before-read-docs(app, env, docnames)

for docname in docnames:
    5.  event.env-purge-doc(app, env, docname)
    if doc changed and not removed:
        6. source-read(app, docname, source)
        7. run parser: text -> docutils.document
        8. apply transforms (by priority): docutils.document -> docutils.document
        9. event.doctree-read(app, doctree)

10. event.env-updated(app, env)
11. event.env-check-consistency(app, env)

for docname in docnames:
    12. apply post-transforms (by priority): docutils.document -> docutils.document
    13. event.doctree-resolved(app, doctree, docname)

14. call builder

15. event.build-finished(app, exception)
```

**Comment by chrisjsewell** [comment]
It would also be good to note that post transform changes to the doctrees aren’t stored in the doctrees folder, and to add things like when the environment collectors are triggered.

**Comment by ankostis** [comment]
I keep using this as a reference.

Any plans to make it into the documents, preferably in the  `sphinx/doc/extdev/appapi.rst#sphinx-core-events` page & section?

**Comment by choldgraf** [comment]
I'd be happy to make a PR to the docs if the Sphinx devs are +1 on the idea, and as long as @chrisjsewell is OK with me blatantly copying his list :-)

**Comment by chrisjsewell** [comment]
Yeh fine by me.
As I mentioned, there might be some extra info you want to add in, but its mainly good

**Comment by tk0miya** [comment]
Good proposal. +1 for merging this into the official doc.

To be more accurate, it seems some updates are needed.

>        7. run parser: text -> docutils.document

This component is called as a "source parser". And it can be added by `app.add_source_parser()` API.

>        8. apply transforms (by priority): docutils.document -> docutils.document
>        9. event.doctree-read(app, doctree)

The doctree-read event is emitted on the middle of the "apply transforms" step. So you can make a transform component that is invoked after the doctree-read.
https://github.com/sphinx-doc/sphinx/blob/80d9728101ab349050a708261da623a306f09f85/sphinx/transforms/__init__.py#L371-L376

>        9. event.doctree-read(app, doctree)

After this, `env-merged-info` is called to merge environment objects only if parallel build mode.

>10. event.env-updated(app, env)
>11. event.env-check-consistency(app, env)

The `env-get-updated(app, env)` is emitted after the env-update event.

>for docname in docnames:
>    12. apply post-transforms (by priority): docutils.document -> docutils.document
>    13. event.doctree-resolved(app, doctree, docname)

For HTML based builders, this order is correct. But other builders are not. They concatenates doctrees into the single document, and applies post-transforms and emits doctree-resolved event.

In addition, the `missing-reference(env, node, contnode)` is called for each reference node that failed to resolve on the doctree-resolve event.
