### ISSUE TITLE
The spacing between bulleted lists is incorrect on an outdent

### ISSUE THREAD

**Issue by hutfortytwo** [sphinx-doc/sphinx#7218]
When a bulleted list  in indented from the 1st to 2nd level there is a space between the levels, which is correct.

When a bulleted list  in outdented from the 2nd to 1st level the space between the levels is missing.

Please correct the spacing.

I have tested this with numbered lists and the spacing is correct.
![rst_of_lists](https://user-images.githubusercontent.com/54061863/75233748-44018680-57b1-11ea-8aff-7193ef726ca8.jpg)
![html _view_of_list](https://user-images.githubusercontent.com/54061863/75233764-49f76780-57b1-11ea-88fd-8305930c0116.jpg)

**Comment by jfbu** [comment]
Can you please not use a screenshot of original rST source but simple text copy paste? (thanks for reporting anyway ;-) )

**Comment by tk0miya** [comment]
I guess this is a bug of sphinx_rtd_theme. Could you check it with bundled themes (ex. alabaster)?
<img width="108" alt="スクリーンショット 2020-02-26 20 07 14" src="https://user-images.githubusercontent.com/748828/75339368-b9657800-58d3-11ea-9059-0e02d2b2ac27.png">

If you're using sphinx_rtd_theme, it does not support HTML5 output. So it would be fixed with `html4_writer = True` settings.

Thanks,

**Comment by hutfortytwo** [comment]
Hi, thanks for the suggestions. I am using sphinx_rtd_theme. I have added in `html4_writer = True` and this has removed the blank row from above the bullet.

I added the code to this post but it wasn't being displayed correctly, so please see the attached txt file instead.

Claire.

[code.txt](https://github.com/sphinx-doc/sphinx/files/4260547/code.txt)

![nested_list_html4_correction](https://user-images.githubusercontent.com/54061863/75427854-27935480-593f-11ea-8707-da51f15f4a4f.jpg)

**Comment by tk0miya** [comment]
Thank you for confirmation and example. Confirmed too.
It seems sphinx_rtd_theme does not control the spans around enumerated list in both HTML4 and HTML5 mode. Could you report this into their project please?
Thanks,
