### ISSUE TITLE
Make "main" index entries the first

### ISSUE THREAD

**Issue by serhiy-storchaka** [sphinx-doc/sphinx#7220]
You can mark up “main” index entries by prefixing them with an exclamation mark. The references to “main” entries are emphasized in the generated index. But it does not change the order of entries, so the "main" index entry can be the last one.

For example, look at the index for "import statement" in the Python documentation. https://docs.python.org/3/genindex-I.html. There are 5 references. The last one is marked as "main".

Would be nice if references to "main" entries be moved to the beginning of the list.

This issue was reported on the Python bug tracker: https://bugs.python.org/issue22714.

**Comment by tk0miya** [comment]
+1: resonable.

**Comment by tk0miya** [comment]
Done in #7226 
Thank you for your proposal!

**Comment by serhiy-storchaka** [comment]
Great! Thank you for your response!
