### ISSUE TITLE
Got an error when building documentation during git checkout

### ISSUE THREAD

**Issue by PythonCoderAS** [sphinx-doc/sphinx#7233]
**Describe the bug**
When I was running a build, I switched my git branch and got an exception.

**To Reproduce**
```
$ sphinx-build -W --keep-going docs /tmp/sphinx & 
$ git checkout abranchwithdifferentrstfiles
```

Error: 

```Exception occurred:
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '~/PycharmProjects/praw/docs/package_info/praw7_migration.rst'
The full traceback has been saved in /var/folders/_b/lxdb2n41733bg22l3cbkw1c80000gp/T/sphinx-err-zo19glhc.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**Expected behavior**

**Your project**
Link to your sphinx project, or attach zipped small project sample.

**Screenshots**

**Environment info**
- OS: [e.g. Unix/Linux/Mac/Win/other with version] Mac 10.14
- Python version: [e.g. 3.7.1] 3.7.6
- Sphinx version: [e.g. 1.8.2] 2
- Sphinx extensions:  [e.g. sphinx.ext.autodoc, recommonmark]
- Extra tools: [e.g. Browser, tex or something else]

**Additional context**

- [e.g. URL or Ticket]

**Comment by tk0miya** [comment]
Could you paste full traceback here please? It was saved into your disk on error happened.

>The full traceback has been saved in /var/folders/_b/lxdb2n41733bg22l3cbkw1c80000gp/T/sphinx-err-zo19glhc.log, if you want to report the issue to the developers.

**Comment by PythonCoderAS** [comment]
It was saved in a temp folder, and the machine has been shut down, but I'll try to recreate the error.

**Comment by PythonCoderAS** [comment]
@tk0miya I got the same error to occur with another file, so the message changed slightly.

```# Sphinx version: 2.3.1
# Python version: 3.7.6 (CPython)
# Docutils version: 0.15.2 release
# Jinja2 version: 2.10.3
# Last messages:
#   none found
#   pickling environment...
#   done
#   checking consistency...
#   done
#   preparing documents...
#   done
#   writing output... [  0%] code_overview/exceptions
#   writing output... [  1%] code_overview/models/comment
#   writing output... [  2%] code_overview/models/flair
# Loaded extensions:
#   sphinx.ext.mathjax (2.3.1) from /usr/local/lib/python3.7/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.1) from /usr/local/lib/python3.7/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.1) from /usr/local/lib/python3.7/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (1.0.2) from /usr/local/lib/python3.7/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.3) from /usr/local/lib/python3.7/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.2) from /usr/local/lib/python3.7/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /usr/local/lib/python3.7/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc (2.3.1) from /usr/local/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.intersphinx (2.3.1) from /usr/local/lib/python3.7/site-packages/sphinx/ext/intersphinx.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/usr/local/lib/python3.7/site-packages/sphinx/application.py", line 353, in build
    self.builder.build_update()
  File "/usr/local/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 299, in build_update
    len(to_build))
  File "/usr/local/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 361, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/local/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 535, in write
    self._write_serial(sorted(docnames))
  File "/usr/local/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 545, in _write_serial
    self.write_doc(docname, doctree)
  File "/usr/local/lib/python3.7/site-packages/sphinx/builders/html.py", line 622, in write_doc
    self.handle_page(docname, ctx, event_arg=doctree)
  File "/usr/local/lib/python3.7/site-packages/sphinx/builders/html.py", line 1052, in handle_page
    copyfile(self.env.doc2path(pagename), source_name)
  File "/usr/local/lib/python3.7/site-packages/sphinx/util/osutil.py", line 127, in copyfile
    shutil.copyfile(source, dest)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '~/PycharmProjects/praw/docs/code_overview/models/flair.rst'
```

**Comment by tk0miya** [comment]
How did you invoke Sphinx? I don't know why but Sphinx considers the source file is placed at `'~/PycharmProjects/praw/docs/code_overview/models/flair.rst'`. But `~` is not a special character in Python (It's a special character for shell). We need to know where the character came from.

**Comment by PythonCoderAS** [comment]
Oh, don't worry. I ran the output through a script that replaces my username with ~. Feel free to substitute `~` with `/Users/Test`

**Comment by tk0miya** [comment]
Did you mean you rewrote the traceback log that you posted here? 

I don't understand what happened in your environment. It seems Sphinx crashed when copying `code_overview/models/flair.rst` to the output directory. Could you check that `code_overview/models/flair.rst` exists on your source directory? Is it really a part of your documents?

**Comment by PythonCoderAS** [comment]
That's the bug. I have different for branches, and if I start building on one set of documents, but checkout to another set of documents, it'll throw an error. I posted this bug report because it recommended to post a bug report in order to give a better error message.

**Comment by tk0miya** [comment]
Did you mean you switched the branch during document building, right?

**Comment by PythonCoderAS** [comment]
Yes

**Comment by tk0miya** [comment]
Okay, I understand the problem. Thank you for explanation. I'll take a look later.

**Comment by tk0miya** [comment]
-0 for supporting this case. To do that, we need to write thousands of code. But it will make our code unreadable. And I feel this is a rare case, and the user will notice about miss-operation by itself.
