### ISSUE TITLE
Allow HTML download links to be resolved relative to a different path

### ISSUE THREAD

**Issue by dzhu** [sphinx-doc/sphinx#7242]
**Is your feature request related to a problem? Please describe.**

I have a project where I would like to use an out-of-source build: all built files should live in a separate directory from all source files. I'm using the Sphinx HTML builder for documentation, and my docs link to several files that are generated as part of the build process (they are `.tgz` files containing certain subdirectories of the source directory). Right now, I have to create those files into my source directory so that they are in the right location relative to the RST source, which I would like to avoid.

Example code layout:
```
+ docs/
  + index.rst
+ examples/
  + ex1/
+ build/
```
From `ex1/` I generate `ex1.tgz` (there could also be `ex2/` and `ex2.tgz`, etc.). I would like to put `ex1.tgz` directly inside `build/examples/` and use `examples/ex1.tgz` as a link target in the RST, but right now I have to either put it at `docs/examples/ex1.tgz` or make the link point to `../build/examples/ex1.tgz`. If I could specify in `conf.py` that all links should be taken relative to `../build`, I could achieve what I want.

**Describe the solution you'd like**

I would like it to be possible to specify a directory relative to which download links are resolved. Perhaps there could even be a list of directories to search, to handle both built files and files contained in the source, but I don't need it to go that far.

I wrote [an extension that does this](https://gist.github.com/dzhu/4477338e34620d141bc71f4dc214ea47), and it is working, but it takes some hacks and having official support for this use would be much nicer.

**Describe alternatives you've considered**

The links could point directly to the place where the files will be built (e.g., `../build/examples/ex1.tgz`), but I would like to avoid having the build path hardcoded into all the download links. I could copy the entire RST source tree into the build directory and then generate the `.tgz` files there, but I would consider that clumsy, and it comes with other issues around keeping things in sync.

**Comment by tk0miya** [comment]
I think it is a part of pre-processing and out-of-scope for Sphinx. How about adding `tar cf docs/downloads/ex1.tgz ex1/` to your Makefile before sphinx-build?

**Comment by dzhu** [comment]
My goal is to keep all generated files (including the `.tgz` files) separate from the source directory, following the general concept of an out-of-source build, so I was hoping to avoid that. The nicest outcome from my personal perspective would be for this to be added as a feature directly in Sphinx, and I think it's not a crazy use case -- but, as I said, I have a functioning workaround, so please go ahead and close this if you continue to feel that it is out of scope.

**Comment by tk0miya** [comment]
IMO, Sphinx expects all project-related files are placed under the source directory. It is basic concept of Sphinx. So I think your proposal is out of scope at present.

**Comment by tk0miya** [comment]
Thank you for nice proposal. But I'm closing this now.

**Comment by dzhu** [comment]
Makes sense. Thank you for the consideration!
