### ISSUE TITLE
Drop special cross reference helper for exceptions, functions and methods

### ISSUE THREAD

**Issue by tk0miya** [sphinx-doc/sphinx#7246]
**Is your feature request related to a problem? Please describe.**

So far, `:py:exc:` role automatically searches exception classes under `exceptions` module. But, since python3, exception classes has been moved into `builtins` module. So this fallback works fine only for python2 docs.

```
.. py:exception:: exceptions.Exception

:py:exc:`Exception` can refer `exceptions.Exception` automatically even if no ``py:module::`` given.
```

In addition, this fallback is a part of python domain, not intersphinx. So it only works for a document contains descriptions for standard exceptions. It does not work for a document only refers python standard exceptions.

Side note: python domain also has another special support for `:py:func:` and `:py:meth:`. It also automatically searches functions and methods under `object`.
```
.. py:method:: object.__str__()

:py:func:`__str__` and `:py:meth:`__str__` can refer `object.__str__()` automatically even if no ``py:class:`` given.
```
I don't know why python domain searches them on `object.*` namespace. I can understand if it searches under `builtins` module. Anyway, this is also meaningless.

**Describe the solution you'd like**
Drop these special treatment from python domain.

**Describe alternatives you've considered**
Nothing.

**Additional context**
Nothing.

**Comment by shimizukawa** [comment]
+1 to drop special cross reference helper

**Comment by tk0miya** [comment]
Note: python-docs declares exceptions classes as root item (not under builtins package):
```
$ python -m sphinx.ext.intersphinx https://docs.python.org/3/objects.inv
...
py:exception
    ArithmeticError                          library/exceptions.html#ArithmeticError
    AssertionError                           library/exceptions.html#AssertionError
    AttributeError                           library/exceptions.html#AttributeError
    BaseException                            library/exceptions.html#BaseException
    BlockingIOError                          library/exceptions.html#BlockingIOError
    BrokenPipeError                          library/exceptions.html#BrokenPipeError
    BufferError                              library/exceptions.html#BufferError
    BytesWarning                             library/exceptions.html#BytesWarning
    ChildProcessError                        library/exceptions.html#ChildProcessError
    ConnectionAbortedError                   library/exceptions.html#ConnectionAbortedError
    ConnectionError                          library/exceptions.html#ConnectionError
    ConnectionRefusedError                   library/exceptions.html#ConnectionRefusedError
    ConnectionResetError                     library/exceptions.html#ConnectionResetError
    DeprecationWarning                       library/exceptions.html#DeprecationWarning
    EOFError                                 library/exceptions.html#EOFError
    EnvironmentError                         library/exceptions.html#EnvironmentError
    Exception                                library/exceptions.html#Exception
...
```
