### ISSUE TITLE
No warnings from a built document

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#725]
When running "make html", I don't get warnings about built document unless I run "make clean" before.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/725
- Originally reported by: Valentin Lorentz
- Originally created at: 2011-06-29T15:29:32.602

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2011-09-21 07:16:07+00:00_

That's working as designed, since these documents aren't re-read during build. Otherwise you'd have to do a full build every time.

**Comment by shimizukawa** [comment]
_From Valentin Lorentz on 2011-09-21 16:02:43+00:00_

or keep a log of warnings from built file, and display it when the compilation starts/ends.

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2011-09-22 17:14:03+00:00_

That is actually a good idea. Reopening.

**Comment by techtonik** [comment]
So, do warnings stored in DB?

**Comment by techtonik** [comment]
So some http://www.sphinx-doc.org/en/master/extdev/collectorapi.html gathers data and stores in http://www.sphinx-doc.org/en/master/extdev/envapi.html#sphinx.environment.BuildEnvironment Yet I don't see how to store additional info there tied to specific file. Any hints?

**Comment by tk0miya** [comment]
There are no common way. We usually stores them into env object. The env object behaves like a persistent storage during incremental builds.
But it might not work for this case. The env object is dumped after reading phase. But, in this case, warnings are also emitted on resolving and writing phase. So env object might be not good for storing warnings.

**Comment by techtonik** [comment]
So what are the other options? Which objects/databases are available?

**Comment by tk0miya** [comment]
No special option. Sphinx does not depend on any database library. So I prefer to use standard libraries. What kind of database do you want to use?
I suppose it is very simple structure. So no special manager is needed to me.

**Comment by techtonik** [comment]
There should be at least some directory where all files persist between runs. JSON with mapping of source filenames to warning list would be sufficient.

**Comment by tk0miya** [comment]
You can use `app.doctreedir` for such purpose. It is shared between each builds. But it will be removed on `make clean`.

**Comment by techtonik** [comment]
@tk0miya is there any document that describes document parsing phases better than [PEP 0258](http://docutils.sourceforge.net/docs/peps/pep-0258.html)?

**Comment by techtonik** [comment]
I'd better attach some info to some object that represents input document (one that produces warnings) rather than maintain the mapping in external files myself.

**Comment by tk0miya** [comment]
About sphinx, there are nothing. Sadly, our document for development is poor. I've not understood yet.

On the other hand, about docutils, I don't know that.
