### ISSUE TITLE
Add support for LaTeX preambles to the MathJax extension

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#726]
pngmath lets you define pngmath_latex_preamble in conf.py with a bunch of stuff that is executed in the preamble of LaTeX (like \newcommands). It would be great if MathJax also supported this, so I could easily hotswap pngmath and MathJax without having to forgo the preamble.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/726
- Originally reported by: Aaron Meurer
- Originally created at: 2011-07-05T02:32:49.463

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2011-09-21 09:08:21+00:00_

I am not sure if MathJax supports something like that...

**Comment by shimizukawa** [comment]
_From Anonymous on 2011-09-21 15:14:53+00:00_

MathJax lets you add stuff like \newcommand to the top of files.  If preambles are not supported directly, perhaps it could just manually add it to the top of each file.

**Comment by danmackinlay** [comment]
`\newcommand`is one thing we do in preambles, and I for one would love that feature.

The other is loading of particular extensions, e.g. `amsmath`, and this does not function in precisely the same way across MathJax and LaTeX - in particular, only extensions that are (re-)implemented natively in javascript are supported. Nonetheless, that is still a very useful list - including in particular, `\newcommand` and `\def`.

[According to the MathJax docs](http://docs.mathjax.org/en/latest/tex.html#tex-and-latex-extensions), the native extension loading looks like this, from javascript:

``` javascript
<script type="text/x-mathjax-config">
  MathJax.Hub.Config({ TeX: { extensions: ["autobold.js"] }});
</script>
<script type="text/javascript"
    src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML">
</script>
```

Or, from latex:

``` latex
\(\require{autobold}\)
```

It sounds like this configuration directive is possible, but it would not correspond precisely to the pngmath equivalent.

**Comment by certik** [comment]
I have quite a few `\newcommand` lines in `latex_preamble`, it would be nice to provide a similar (perhaps syntactically a bit different if needed) string to MathJax, so that I can switch latex and MathJax. Currently MathJax shows lots of undefined/red commands that I use.

@asmeurer, since you reported the original issue, have you figured out any workaround in the meantime?

**Comment by asmeurer** [comment]
I think the newcommands were removed from the SymPy galgebra docs. However, there's this raw html at the top of [this file](https://raw.githubusercontent.com/sympy/sympy/master/doc/src/modules/galgebra/ga.rst). Maybe that could be used to do what you want.

**Comment by certik** [comment]
Thanks @asmeurer. I figured it out in case anybody is facing the same problem:

https://github.com/certik/theoretical-physics/pull/62

In there I overload the `layout.html` and insert mathjax macros into the body of the document.

**Comment by tk0miya** [comment]
It looks good for me to provide preambles to mathjax.

but, at the same time, I'm not so familier with it.
How do we introduce the feature to Sphinx? Outputting `<script type="text/x-mathjax-config">` tag?

**Comment by karlnapf** [comment]
at @shogun-toolbox we would love to use latex preamples with mathjax

**Comment by tk0miya** [comment]
Note: I found a similar post for customization of mathjax.
https://github.com/sphinx-doc/sphinx/issues/969#issuecomment-151689150

**Comment by tk0miya** [comment]
I just made a new PR #5230 for this. Could anyone test this please?
I'm not good at mathjax. so I don't know this is enough or not.

**Comment by tk0miya** [comment]
Now #5230 is merged.
Thank you for reporting!
