### ISSUE TITLE
autodoc_member_order by alphabetical doesn't work when I want to list members in __all__ 

### ISSUE THREAD

**Issue by kathywt** [sphinx-doc/sphinx#7270]
**Describe the bug**
I want to list members in \_\_all\_\_ of a module with automodule, and also want that members not be the order in \_\_all\_\_, but the order of alphabetical. So I set autodoc_member_order to alphabetical in conf.py, but it doesn't work. Is this not supported?

**To Reproduce**
conf.py set like this,
```
autodoc_member_order = 'alphabetical'
```

rst like this,
```
test.test1
======

.. automodule:: test.test1
   :members:
```

and classes in \_\_all\_\_ without alphabetical order.

sphinx version:
sphinx-build 2.3.1

**Comment by tk0miya** [comment]
I noticed this was already fixed by #7676. Please update your Sphinx to 3.1.0 or above.
Thanks,
