### ISSUE TITLE
ci: improve codecov integration

### ISSUE THREAD

**Issue by blueyed** [sphinx-doc/sphinx#7279]
I'd like to disable codecov's comments (which are large and interrupt the conversion on PRs).

IIRC codecov statuses have been disabled (because of flakiness?), but comments where never a topic.

I therefore think it would be good to 1. disable codecov's comments, and 2. enable the status for the patch.

This would make PRs less "noisy" with regard to comments, and the "patch" check from Codecov would indicate how much the patch/PR is covered.

**Comment by tk0miya** [comment]
@stephenfin Could you check this please?

Personally, I don't refer status of codecov. So +1 for disabling.

**Comment by stephenfin** [comment]
+0. I thought they would be helpful but if not, kill em

**Comment by blueyed** [comment]
I think the comments are getting in the way a lot, but value the status checks in general (admins can override merging (if checks are required to pass in the first place), e.g. when something is not covered).

I've also enabled the status check in https://github.com/sphinx-doc/sphinx/pull/7286, but can remove it again.

**Comment by tk0miya** [comment]
It seems nobody objects to your proposal. So let's merge it. It seems status checks for patches are not bother to us.
