### ISSUE TITLE
Add a strict mode for intersphinx

### ISSUE THREAD

**Issue by blueyed** [sphinx-doc/sphinx#7280]
I think it would be useful to have a strict mode with intersphinx, where it requires to have a prefix in the target.

Currently it might happen that something gets linked to e.g. the Python docs (when added as a mapping), although it was intended to be in the project's documentation itself: this hides warnings in nit-picky mode then etc.

This might be as simple as adding a new setting, and then returning with it being set, but no ":" in the target (https://github.com/sphinx-doc/sphinx/blob/90804238b07194df497af81fc8722b09bea2be65/sphinx/ext/intersphinx.py#L264).

**Comment by tk0miya** [comment]
-0; It's not difficult, but I can't imagine the case that this option is needed. Are there any examples of unexpected links for external project?

**Comment by blueyed** [comment]
In my case I was linking to something more generic, and it was picked up via Intersphinx.
So in nitpicky mode it would have gone unnoticed.

I think it is good practice to use a prefix for explicitness anyway - to make it clear that this is external documentation.

**Comment by tk0miya** [comment]
I feel ```:class:`python:int` ``` is a bit too much. But I understand who wants to declare cross-references explicitly. So +0 to add that option. Could you make a pull request please?

**Comment by AA-Turner** [comment]
Closing; but would consider a PR to implement the functionality
