### ISSUE TITLE
Strings should be in plural forms, but are not treated as such

### ISSUE THREAD

**Issue by rffontenelle** [sphinx-doc/sphinx#7282]
**Describe the bug**
Strings wrapped around `__(` are translatable, and when words vary between singular and plural they should be treated as in [plural form](https://www.gnu.org/software/gettext/manual/html_node/Plural-forms.html). However, those plural-form strings are not present for translation -- instead, only the first string is displayed. This happens with the following strings:

* file sphinx/application.py, line 353-355:

```
msg = __('build %s, %s warning (with warnings treated as errors).',
         'build %s, %s warnings (with warnings treated as errors).',
         self._warncount)
```

* file sphinx/application.py, line 357-359:

```
msg = __('build %s, %s warning.',
         'build %s, %s warnings.',
         self._warncount)
```

**To Reproduce**
```
$ git clone https://github.com/sphinx-doc/sphinx
$ cd sphinx
$ python setup.py extract_messages
$ open `sphinx/locale/sphinx.pot`, and see only the first string of each code block as:

#: sphinx/application.py:353
#, python-format
msgid "build %s, %s warning (with warnings treated as errors)."
msgstr ""

#: sphinx/application.py:357
#, python-format
msgid "build %s, %s warning."
msgstr ""
```

**Expected behavior**
To have the above strings in plural forms, to be able available for translation.

**Your project**
N/A

**Screenshots**
N/A

**Environment info**
- OS: Arch Linux
- Python version: 3.8
- Sphinx version: 3.x branch
- Sphinx extensions:  N/A
- Extra tools: N/A

**Additional context**:
N/A

**Comment by tk0miya** [comment]
Absolutely. babel:extract_message does not support mixed gettext/ngettext() translation. I'll fix it soon.

**Comment by tk0miya** [comment]
Fixed. Thank you for reporting.
