### ISSUE TITLE
Overriding Python splitter results in mismatch with JavaScript splitter

### ISSUE THREAD

**Issue by tst-lsavoie** [sphinx-doc/sphinx#7293]
**Describe the bug**
Sphinx has two ways to split words for searching. There is a Python splitter that parses words to include in the search index and a JavaScript splitter that parses user input to determine what words to look for in the search index. Users can override the Python splitter by subclassing `SearchLanguage`, but they cannot change the JavaScript splitter, which could result in terms in the search index that cannot be searched from an HTML page.

A specific case where this is a problem is if you override the splitter to include dashes in words and you have words (such as part numbers) that you want to index like "A-1234".

**To Reproduce**
```
# Assumes Ubuntu 16.04

# Install Sphinx
sudo apt install python3-pip
sudo pip3 install sphinx

# Download the test file attached to this issue and unzip it
unzip splitter_test.zip

# Build the docs
cd splitter_test
make html

# Verify that "a-1234" is in the search index. The below command should print some
# JavaScript code that includes the string "a-1234".
grep "a-1234" _build/html/searchindex.js

# View the docs
firefox _build/html/index.html &

# Now search for the string "a-1234"
```

**Expected behavior**
The test page comes up in the search results.

**Actual behavior**
The search results are empty.

**Environment info**
- OS: Ubuntu 16.04
- Python version: 3.5.2
- Sphinx version: 2.4.4

**Additional context**
Test project: [splitter_test.zip](https://github.com/sphinx-doc/sphinx/files/4314861/splitter_test.zip)

**Comment by tk0miya** [comment]
I just posted #7315 to allow overriding JS Splitter via `SearchLanguage.js_splitter_code`. I suppose this would help your case. Could you try this please? If it's okay, I'll merge it in the next release.
