### ISSUE TITLE
Bug in 'Developing a “TODO” extension' tutorial

### ISSUE THREAD

**Issue by mattagape** [sphinx-doc/sphinx#7299]
**Describe the bug**
I followed the tutorial. All was well until I changed the line in `conf.py` from

`todo_include_todos = False`

to

`todo_include_todos = True`

**To Reproduce**
```

Follow the tutorial, then type:

$ make html
```

This causes an Exception:

```
➜  sphinx make html
Running Sphinx v2.4.4
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 1 source files that are out of date
updating environment: 0 added, 0 changed, 0 removed
looking for now-outdated files... none found
preparing documents... done
writing output... [100%] index                                                                                        
Exception occurred:
  File "/Users/matthewgillman/play/sphinx/_ext/todo.py", line 82, in process_todo_nodes
    for todo_info in env.todo_all_todos:
AttributeError: 'BuildEnvironment' object has no attribute 'todo_all_todos'
The full traceback has been saved in /var/folders/kj/7h5hgyvn4v9bjtyk88y4s1rh0000gn/T/sphinx-err-answiaoe.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [html] Error 2
```

[sphinx-err-answiaoe.log](https://github.com/sphinx-doc/sphinx/files/4319346/sphinx-err-answiaoe.log)

**Expected behavior**
The tutorial should work

**Environment info**
- OS: Mac Darwin
- Python version: 3.6.10 |Anaconda, Inc.| (default, Jan  7 2020, 15:01:53) 
- Sphinx version: sphinx-build 2.4.4
- Sphinx extensions:  extensions = ['todo']

**Additional context**
See attached error log

**Comment by mattagape** [comment]
The bug occurs when there aren't any todo annotations in the files parsed.

So adding the file `somefile.rst`, and  giving it the following content, per the tutorial, stops the error occurring:

```
foo
===

Some intro text here...

.. todo:: Fix this


```

The problem is in line 80 of `todo.py`:

```for todo_info in env.todo_all_todos:```

Need to check for an empty list in the tutorial

**Comment by mattagape** [comment]
I have tried adding the following code immediately before the inner for-loop in `process_todo_nodes()` :
```
my_todo_list = []
try:
    my_todo_list = env.todo_all_todos
except (NotImplementedError, AttributeError):
    print("There are no todo items to parse")
    continue

for todo_info in my_todo_list:  # env.todo_all_todos:
    para = nodes.paragraph()
    ...  # (as before)
```
[sphinx-err-pl2wbg81.log](https://github.com/sphinx-doc/sphinx/files/4323454/sphinx-err-pl2wbg81.log)



but this still raises a NotImplemented exception in the bowels of the parser. It's not clear where `process_todo_nodes()` calls that code. See second log attached.

**Comment by tk0miya** [comment]
Thank you for reporting. Surely, our example is wrong. I post a fix #7313. Could you try it please?

**Comment by mattagape** [comment]
Hi, I've tried it, and it seems OK, but today I can't reproduce my error for some reason.

**Comment by tk0miya** [comment]
Thank you for confirmation. I don't know why not reproduced in your environment. But this surely fixed the problem, I believe. Please report if you'll meet the error again.
Thanks,
