### ISSUE TITLE
Show term contents in a tooltip

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#73]
In addition of providing the link to glossary terms, the appropriate target formats like HTML could show the term contents in a tooltip. In this way, the reader would not need to jump off the context but see the definition right away.

//The easiest way would probably be using the alt attribute, but the support for multiple lines is preferred.//

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/73
- Originally reported by: Anonymous
- Originally created at: 2008-12-16T17:35:08.710

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2009-01-04 21:53:36+00:00_

Hmm, this would be extensible to other cross-references as well...

**Comment by shimizukawa** [comment]
_From Éric Araujo on 2010-10-29 00:12:07+00:00_

alt exists only on img elements, you may have meant title.

This could increase significantly the size of the HTML files; maybe a lazy, JavaSrript-based solution would be better.

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2011-01-06 19:39:40+00:00_

I've decided not to implement this by default; usually the glossary has quite extensive explanations and displaying them all in a tooltip is not appropriate.

A JS-based solution could potentially work display-wise, but requires an API for fetching the contents.

**Comment by vsajip** [comment]
I have this working (in preliminary form, and can no doubt be improved) in the [Sizzle theme for Sphinx](https://docs.red-dove.com/sphinx_sizzle_theme/index.html#glossary-improvements), in case anyone's interested. Currently implemented only for links to the glossary, but the idea is more widely applicable.

**Comment by ankostis** [comment]
+1 for Sizzle, this would be very useful capability for a project with extensive glossary (lie my [graphtik](https://graphtik.readthedocs.io/en/latest/arch.html#term-pipeline)).
@vsajip  how is it implemented?  Did you dot it with a client-side API, like @shibukawa hinted?

**Comment by vsajip** [comment]
I used a two-step approach:

1. When building the documentation, I extract out the glossary information in a form which is made available to client side code (not really an API - just a set of data sent as JSON).
1. This data is used by code on the client side to actually implement the tooltips.
