### ISSUE TITLE
"Could not parse arglist" with operator pow

### ISSUE THREAD

**Issue by jakobandersen** [sphinx-doc/sphinx#7304]
**Describe the bug**
With the rst
```rst
.. py:method:: f(*, a=2**4)
.. py:method:: g(a=2**4)
```
I get the errors
```
WARNING: could not parse arglist ('*, a=2**4'): Unable to parse BinOp object
WARNING: could not parse arglist ('a=2**4'): Unable to parse BinOp object
```

**Expected behavior**

**Environment info**
- OS: Ubuntu 18.04
- Python version: 3.6.9
- Sphinx version: branches 3.x and master, but not 2.x
- Sphinx extensions:  none
- Extra tools: none

**Comment by tk0miya** [comment]
Thank you for reporting. At present, the parser for python signature does not support expression syntax. I'll try to support them from now on.

**Comment by jakobandersen** [comment]
That was fast. Thanks!
