### ISSUE TITLE
autodoc does not recognize Cython signature

### ISSUE THREAD

**Issue by McSinyx** [sphinx-doc/sphinx#7331]
Signatures generated by Cython with `binding=True` are not recognized by autodoc, although help can see it just right.

### To Reproduce
First create `cyspam.pyx` and `pyspam.py` with the same content as follows:
```python
def foo(bar: int) -> bool: """Docstring."""
```

Then write a minimal `setup.py` for it:
```python
from distutils.core import setup
from Cython.Build import cythonize

setup(name='autospam', py_modules=['pyspam'],
      ext_modules=cythonize('cyspam.pyx',
                            compiler_directives={'binding': True}))
```

After `pip install .` one should be able to get help from the interpreter, e.g.
```python
>>> import cyspam, pyspam
>>> help(cyspam.foo)
...
foo(bar: 'int') -> 'bool'
    Docstring.
>>> help(pyspam.foo)
...
foo(bar: int) -> bool
    Docstring.
```

Note that with `from __future__ import annotations` (PEP 563), the signature of `pyspam.foo` would be the same as the other.

In Sphinx ReST source, add this:
```rst
cyspam
------

.. automodule:: cyspam
   :members:

pyspam
------

.. automodule:: pyspam
   :members:
```

Then the generated HTML would be something like

> ### cyspam
> cyspam.foo
>
>     Docstring.
>
> ### pyspam
> pyspam.foo(bar: int) → bool
>
>     Docstring.

### Expected behavior
Signature generated for `cyspam.foo` should have been `foo(bar: 'int') -> 'bool'`.

### Sample project
[autospam.zip](https://github.com/sphinx-doc/sphinx/files/4346953/autospam.zip)

### Environment info
- OS: Debian GNU/Linux testing
- Python version: 3.7.6
- Sphinx version: 2.4.3
- Sphinx extensions:  sphinx.ext.autodoc
- Extra tools: Cython

### Additional context
This is originally filed against cython/cython#3438, however, Cython is not aware of the mechanism autodoc uses to fetch the signature to apply an appropriate patch.

**Comment by tk0miya** [comment]
Thank you for reporting. It seems autodoc considers `cyspam.foo` is an attribute. As a trial, I gave `-vv` option to `sphinx-build`:

```
[app] emitting event: 'autodoc-process-signature'('attribute', 'cyspam.foo', <cyfunction foo at 0x1108c9280>, {'members': <object object at 0x1106595
[app] emitting event: 'autodoc-process-docstring'('attribute', 'cyspam.foo', <cyfunction foo at 0x1108c9280>, {'members': <object object at 0x1106595
[autodoc] output:

.. py:module:: cyspam


.. py:attribute:: foo
   :module: cyspam

   Docstring.
[app] emitting event: 'object-description-transform'('py', 'attribute', <desc_content: <paragraph...>>)
[app] emitting event: 'doctree-read'(<document: <section "welcome to project's documentation!"...><secti ...>,)
```

Note: It seems inspect module considers the cyfunction is a method-descriptor.
```
Python 3.8.1 (default, Feb 13 2020, 13:34:23)
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from cyspam import foo
>>> import inspect
>>> foo
<cyfunction foo at 0x10f0daa00>
>>> inspect.isfunction(foo)
False
>>> inspect.ismethoddescriptor(foo)
True
```

**Comment by McSinyx** [comment]
Thank you for the prompt response with debugging instructions.  May I ask how does autodoc process a name, since I'm not familiar with the Sphinx codebase?

**Comment by tk0miya** [comment]
Note: cython document says it does not support `inspect` module.
https://cython.readthedocs.io/en/latest/src/userguide/limitations.html#inspect-support

**Comment by McSinyx** [comment]
Thanks, I wasn't aware of that.  However, since the builtin `help` appears to be working, I guess we should at least autodoc a shot, especially it was until quite recently that Python switch to call `inspect.signature` directly for document generation.

**Comment by tk0miya** [comment]
At first, autodoc imports the object and scan objects under the module. After that, it choose an appropriate "documenter" for each object. For example, `FunctionDocumenter` is chosen for cpython's function object. Finally, the documenter read the information of the target object by inspection and build a reST mark-up internally.

As commented above, autodoc does not consider cython's function as a function. It seems `AttributeDocumenter` might be chosen. So the function is rendered as a variable, not a function. It is not related with `inspect.signature()`. autodoc does not call it for cython's functions.

**Comment by McSinyx** [comment]
[This](https://github.com/python/cpython/blob/3.8/Lib/pydoc.py#L379-L382) is how pydoc is currently implemented, relying on `inspect.isroutine` instead of distinguishing between function, method and method descriptor.  I have yet to find how the logic in autodoc is implemented, but I believe it'd be something similar.

**Comment by tk0miya** [comment]
Thank you for the info! I'll take a look later.

**Comment by McSinyx** [comment]
Oops sorry I misclicked.  Cython is only enabling binding by default in the next release (for now signatures embedded in docstrings is more widely used I think), so there is no rush.

**Comment by McSinyx** [comment]
Thank you for the quick fix!  BTW the number of issues is now 666 :smiling_imp:
