### ISSUE TITLE
AttributeError: 'todo_node' object has no attribute 'reporter'

### ISSUE THREAD

**Issue by tkoyama010** [sphinx-doc/sphinx#7354]
**Describe the bug**
Following error occuered.
> $ make html
> 出力中...[  9%] articles/business-document-sample/2portfolio/todo                                                                                                                                                    
> 例外が発生しました
>   File "/home/tetsuo/sphinx-users.jp/.venv/lib/python3.7/site-packages/docutils/nodes.py", line 165, in walk
>     visitor.document.reporter.debug(
> AttributeError: 'todo_node' object has no attribute 'reporter'
> 完全なトレースバックを/tmp/sphinx-err-z9t68b78.logに保存しました。問題を開発者に報告するときに添付してください。
> 次期バージョンでのエラーメッセージ改善のために、ユーザーエラーの場合にも報告してください。
> バグ報告はこちらにお願いします <https://github.com/sphinx-doc/sphinx/issues> 。ご協力ありがとうございます！
> make: *** [Makefile:34: html] エラー 2

[sphinx-err-z9t68b78.log](https://github.com/sphinx-doc/sphinx/files/4364695/sphinx-err-z9t68b78.log)

**To Reproduce**
```
$ git clone https://github.com/sphinxjp/sphinx-users.jp
$ cd sphinx-users.jp
$ git checkout tkoyama010-patch-2
$ python3 -m venv .venv
$ souce .venv/bin/activate
$ pip install -r requirements.txt
$ make html
```

**Expected behavior**
No error.

**Your project**
https://github.com/sphinxjp/sphinx-users.jp

**Screenshots**

**Environment info**
- OS: Linux
- Python version: 3.7.5
- Sphinx version: 2.4.2
- Sphinx extensions:  sphinxcontrib.gist, sphinxcontrib-trimblank

**Additional context**
None

**Comment by tk0miya** [comment]
It seems this is the same as #7195 and already fixed.
Please upgrade your Sphinx to the latest one.
Thanks,

**Comment by tkoyama010** [comment]
Thanks🙂
