### ISSUE TITLE
autodoc does not render correct signatures for built-in functions

### ISSUE THREAD

**Issue by tk0miya** [sphinx-doc/sphinx#7362]
**Describe the bug**
autodoc does not render correct signatures for built-in functions

**To Reproduce**
Source:
```
.. autofunction:: builtins.sum
```
Output:
<img width="609" alt="スクリーンショット 2020-03-23 0 55 22" src="https://user-images.githubusercontent.com/748828/77253905-fb9a9300-6ca0-11ea-8041-63142af2e92f.png">

**Expected behavior**
The correct signatures are rendered.

**Your project**
N/A

**Screenshots**
See above

**Environment info**
- OS: Mac
- Python version: 3.8.2
- Sphinx version: 3.0.0b1
- Sphinx extensions:  sphinx.ext.autodoc
- Extra tools: N/A

**Additional context**
N/A

**Comment by eric-wieser** [comment]
Think this is fixed in my #7384 PR
