### ISSUE TITLE
cpp domain parens in template parameter packs fails

### ISSUE THREAD

**Issue by nilsdeppe** [sphinx-doc/sphinx#7368]
**Describe the bug**
I have C++ code with parentheses in the template parameter list documented as:
```
.. cpp:class:: template <std::integer_sequence<bool, (static_cast<void>(Bs), false)>> foo

    Broken because of parentheses around `static_cast<void>(Bs), false`
```
The same issue comes up if I use a C-style cast:
```
.. cpp:class:: template <std::integer_sequence<bool, (void(Bs), false)>> foo

    Broken because of parentheses around `void(Bs), false`
```

**To Reproduce**
```
$ git clone git@github.com:nilsdeppe/sphinx-bugs.git
$ cd ./sphinx-bugs/issue_cast_templates
$ sphinx-build ./ ./build
$ # open build/index.html
```

**Expected behavior**
Using parentheses to nest expressions inside templates works. This is fairly common when expanding parameter packs, e.g.
```cpp
template <bool... Bs>
using flat_any = std::integral_constant<
    bool,
    not std::is_same<
        value_list<bool, Bs...>,
        value_list<bool, (static_cast<void>(Bs), false)...>>::value>;
```

**Your project**
I've set up a simple repo with an example of the issue: https://github.com/nilsdeppe/sphinx-bugs

**Environment info**
- OS: Linux
- Python version: 3.8.2
- Sphinx version: 2.4.4
- Sphinx extensions:  
- Extra tools: 

**Additional context**
The issue appears to be in the cpp domain, unlike #7367 I haven't had any success in diagnosing and fixing this.

I've attached the build output:
[build.tar.gz](https://github.com/sphinx-doc/sphinx/files/4372224/build.tar.gz)

**Comment by jakobandersen** [comment]
Thanks for reporting! Parsing expressions in template parameter and argument lists is quite icky, and it looks to me that with the 3.x branch the nature of the errors is slightly different, but still present. I'll try to dig into it as soon as possible.

**Comment by nilsdeppe** [comment]
@jakobandersen thanks for the super quick fix! I can confirm that all the issues except one are resolved on the 3.0.x branch.

The remaining issue is (also available in the repo in my original issue, if that's helpful at all):
```
./sphinx-bugs/issue_templates/index.rst:32: WARNING: Error in template parameter list.
Invalid definition: Expected "=", ",", or ">". [error at 18]
  template <Requires<std::enable_if_t<B, std::nullptr_t> = nullptr>> foo
  ------------------^
```
I think `operator=` is the only one of the `_expression_assignment_ops` that really make sense inside a template parameter expression, so it's probably not right to allow all of them.

Again, thank you so much! :smile:

**Comment by nilsdeppe** [comment]
Sorry, previous comment was on wrong issue by accident... 

I'm very sympathetic to how difficult C++ is to parse... A possible option that I fully understand you may not want to entertain would be to treat the template parameters verbatim without parsing, by which I mean adding an option to control handling into Sphinx. I guess this would mean no links for classes/types in the arguments, though this is something I personally would be okay with if it allows us to use Sphinx instead of Doxygen :smile:

**Comment by jakobandersen** [comment]
Actually, there is already this verbatim mode for expressions (the ``_parse_expression_fallback`` method), but unfortunately that sometimes introduces additional problems or hides the underlying issue in strange ways :-).

**Comment by nilsdeppe** [comment]
Ah okay, thanks for explaining that :) If only C++ was easier to parse :smile:

**Comment by jakobandersen** [comment]
Turns out it was not the parenthesis but the comma operator and the pack expansion. See #7380 for simplified examples. The error messages should also now be better, or at least contain strictly more information to get gain a whole new level of confusion :-).

**Comment by nilsdeppe** [comment]
Ah okay, well I'm again very thankful for the super quick fix on this :D It looks like we should be able to render our documentation with Sphinx+Breathe once 3.0.0 is released. Thank you so much! We really appreciate it!
