### ISSUE TITLE
403 Error on Sphinx3B1

### ISSUE THREAD

**Issue by Daltz333** [sphinx-doc/sphinx#7369]
**Describe the bug**
We seem to be getting 403 blocked by the below URL on Sphinx3 Beta 1 specifically.

```
2020-03-24T02:51:04.4428392Z (line  101) broken    https://datatofish.com/add-python-to-windows-path/ - 403 Client Error: Forbidden for url: https://datatofish.com/add-python-to-windows-path/
```

You can verify this in the below pipeline
https://dev.azure.com/wpilib/Documentation/_build/results?buildId=11588&view=logs&jobId=fc8ae5f9-abcc-54af-cfd7-712b49b9dd20

and then using our stable documentation pipeline
https://dev.azure.com/wpilib/Documentation/_build/results?buildId=11574&view=logs&jobId=fc8ae5f9-abcc-54af-cfd7-712b49b9dd20

**To Reproduce**
Linkcheck the following URL https://datatofish.com/add-python-to-windows-path/

**Expected behavior**
Return OK

**Your project**
https://github.com/wpilibsuite/frc-docs

with the attached PR being https://github.com/wpilibsuite/frc-docs/pull/576

**Environment info**
- OS: Ubuntu 18.04
- Python version: 3.7.2
- Sphinx version: 3.0.0b1
- Sphinx extensions:  
```
extensions = [
    'sphinx_tabs.tabs',
    'sphinx.ext.imgmath',
    'sphinx.ext.todo',
    'sphinx.ext.graphviz',
    'sphinx.ext.autosectionlabel',
    'sphinxcontrib.ghcontributors',
    'sphinxcontrib.remoteliteralinclude',
    'notfound.extension'
]
```
- Extra tools: Azure Pipelines

**Additional context**
I've verified on my Windows 10 PC the issue also, so it's not getting blocked by azure.

**Comment by tk0miya** [comment]
Could you add a configuration `user_agent = 'Mozilla/5.0 (X11; Linux x86_64; rv:25.0) Gecko/20100101 Firefox/25.0'` to your conf.py, please?
Since 2.3.0, Sphinx changes the name of user-agent. It seems datatofish.com does not support new user-agent. refs: #1331

**Comment by Daltz333** [comment]
Ah. Thank you. I'll give it a shot
