### ISSUE TITLE
Make generated HTML "Quick Search" facility optionally case INsensitive.

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#738]
The javascript search facility that is set up when you generate HTML
pages is case-sensitive. When I enter text in the "Quick
Search" box, the results depend on the capitalization of my query.
This doesn't seem desirable - the user may not know the exact
capitalization.

The "Quick Search" facility should optionally be case INsensitive.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/738
- Originally reported by: [unsolvable](https://bitbucket.org/unsolvable)
- Originally created at: 2011-07-29T10:37:09.739

**Comment by cdeil** [comment]
+1 to support case-insensitive search.

Most people (I think) are used to write their search queries just all lowercase in Google and other search fields. So I'd prefer to have my Sphinx sites find stuff in a case-insensitive way.

**Comment by tk0miya** [comment]
At current version, the search feature of Sphinx compares keywords by case insensitive. So it seems this issue has been already resolved.
https://www.sphinx-doc.org/en/master/search.html?q=SPHINX
https://www.sphinx-doc.org/en/master/search.html?q=sphinx

Closing.
