### ISSUE TITLE
Property annotations do not show up in autoclass

### ISSUE THREAD

**Issue by eric-wieser** [sphinx-doc/sphinx#7383]
The following code renders the annotation on the method but not the property:
```python
class Foo:
    @property
    def prop(self) -> int:
        """ the prop """
    def get_prop(self) -> int:
        """ get the prop """
```
```rst
.. autoclass:: Foo
    :members:
```
Expected output:

```
Foo
    property prop -> int
        the prop

    get_prop() -> int
        get the prop
```
actual output

```
Foo
    property prop
        the prop

    get_prop() -> int
        get the prop
```

**Environment info**
- OS: Win
- Python version: 3.8
- Sphinx version: 3.0.0b1
- Sphinx extensions: sphinx.ext.autodoc

**Comment by eric-wieser** [comment]
Patch linked above, this was fairly straightforward.

**Comment by pavel-kirienko** [comment]
Are there plans to have this addressed in the near future? Is anybody working on this? Thanks.

**Comment by tk0miya** [comment]
I posted https://github.com/sphinx-doc/sphinx/pull/7298 to implement it. But it was perfectly stalled. I don't have idea to go forward.
