### ISSUE TITLE
Please add a MOBI builder

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#739]
Hello,
there were several requests to provide Python doc in a kindle-friendly format, and the only free alternative we have is the MOBI[1] format.

[1] http://en.wikipedia.org/wiki/Amazon_Kindle#Original_Kindle

Thanks in advance,
Sandro

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/739
- Originally reported by: Anonymous
- Originally created at: 2011-07-31T18:26:57.738

**Comment by shimizukawa** [comment]
_From Georg Brandl on 2011-09-19 07:13:42+00:00_

This might be implemented now that I own a Kindle :)

**Comment by shimizukawa** [comment]
_From Anonymous on 2012-04-30 03:30:41+00:00_

plz plz plz :)

**Comment by shimizukawa** [comment]
_From Dima Kurguzov on 2013-04-29 13:30:48+00:00_

Very desired feature.

**Comment by shimizukawa** [comment]
_From Wes Turner on 2014-01-28 08:24:11+00:00_

seeAlso:
- https://bitbucket.org/birkenfeld/sphinx/pull-request/27/addition-of-mobi-builder
- http://pedrokroger.net/using-sphinx-write-technical-books/
- https://github.com/vkuznet/sphinx-mobi

**Comment by tk0miya** [comment]
We also have kindlebuilder extension (thanks to @shibukawa! BTW, how about release it?)
https://bitbucket.org/shibu/kindlebuilder/overview

These 3rd party extensions are part of Sphinx ecosystem. So I think it is not important to bundle it.

**Comment by shibukawa** [comment]
Mobi format is very old. AZW1 is based on HTML5/CSS3 (very similar to epub) and it is generated via kindlegen command. So we should support valid HTML5 first.

#3464

**Comment by tk0miya** [comment]
Thank you for comment. I don't know about AZW1.
Anyway it is not important to bundle the builders. So I close this now.
Thanks,
