### ISSUE TITLE
width option not working with table directives

### ISSUE THREAD

**Issue by idnsunset** [sphinx-doc/sphinx#7396]
**Describe the bug**
The `width` option does not work with any table directive since Sphinx v2, the HTML `table` tag in the output doesn't have the `style` attribute specifying the width of the table.

With Sphinx v1.8.5 and docutils v0.16, the `width` option works well.

**To Reproduce**

```rst
.. table:: Truth table for "not"
   :width: 100%

   =====  =====
     A    not A
   =====  =====
   False  True
   True   False
   =====  =====
```

**Expected behavior**
Given `:width: 100%` option, the output should have something like `<table style="width: 100%">`.

**Environment info**
- OS: Windows 7
- Python version: 3.8.2
- Sphinx version: 2.4.4
- Docutils version: 0.16

**Comment by tk0miya** [comment]
What is different from #6564?

**Comment by idnsunset** [comment]
> What is different from #6564?

The difference is that the width option is now recognized by newer version of docutils, so it should be the bug of Sphinx itself.

**Comment by tk0miya** [comment]
Now we're working for it on #6564. So I'm closing this.
