### ISSUE TITLE
 Incorrect signature for env-get-outdated

### ISSUE THREAD

**Issue by chrisjsewell** [sphinx-doc/sphinx#7401]
I'm pretty sure here:

https://github.com/sphinx-doc/sphinx/blob/e666a85cf3ced31338e52dd3c11c6a74b90680e8/sphinx/builders/__init__.py#L382

it should be `self.env` not `self` 😬 

I leave it to you to decide if you want to fix it with a breaking change, or just change `env` to `builder` in the documentation:
https://www.sphinx-doc.org/en/master/extdev/appapi.html#event-env-get-outdated
and: https://github.com/sphinx-doc/sphinx/blob/e666a85cf3ced31338e52dd3c11c6a74b90680e8/sphinx/events.py#L39

**Comment by tk0miya** [comment]
OMG, it must be a bug! Thank you for reporting. I'll fix from now on.
