### ISSUE TITLE
Video support

### ISSUE THREAD

**Issue by petsuter** [sphinx-doc/sphinx#7404]
In Sphinx images can be included with `.. image::` or `.. figure::`.
But there is no support for videos yet, right?

It would be nice to have a `.. video::` or even support videos in `.. figure::`.

A workaround is to use:
```
.. raw:: html

   <video controls src="video.mp4"></video>
```
This works quite well! ✨

But:

* The workaround has none of the `.. figure::` features, like a legend etc.
* The workaround is too complicated for non-HTML-experts.
* The workaround is too complicated if repeated for many videos.
* The workaround will never work for [non-HTML output formats](https://helpx.adobe.com/acrobat/using/playing-video-audio-multimedia-formats.html).
* Sphinx does not know to copy the video file.
* ...

In the past video support was probably completely out-of-scope, but maybe nowadays it is easy and appropriate to support it?

Thanks for your consideration.

**Comment by tk0miya** [comment]
+1: Nowadays, video is an important medium. It's reasonable to support.
-0: The only HTML supports it. Other formats do not.
-0: It would be better to add it to the original docutils spec. So it should be proposed into docutils project.

**Comment by astrojuanlu** [comment]
@gmilde notes in sphinx-dev:

> I suppose the issue "Video support #7404" may be closed with a link to
> https://docutils.sourceforge.io/HISTORY.html#release-0-17-2021-04-03
> 
> docutils/writers/html5_polyglot/__init__.py
> 
> [...]
> 
> Use <video> for images with video MIME types supported by HTML5.
> 
> (Unless Sphinx patches the image/figure directive handling in a way that
> breaks Docutils support for moving images.)

**Comment by QuLogic** [comment]
As a note, there currently exists https://sphinxcontrib-video.readthedocs.io/ with support for a bit more HTML5's `video` options than docutils`.

**Comment by picnixz** [comment]
I think I'll close this issue since a fairly good support (and apparently maintained project) already exists as a 3rd party extension.

Closing as `wontfix` (for now). We might consider integrating it in a future Sphinx version but not for now. Thanks for digging out this old issue.
