### ISSUE TITLE
Clean autosummary generated files with make clean in make mode

### ISSUE THREAD

**Issue by vnmabus** [sphinx-doc/sphinx#7408]
As far as I know, `make clean` in make mode only removes the `_build` directory.

I would want that files generated by other sphinx extensions were removed too. For some extensions this can be done placing the generated files under the `_build` directory. However, autosummary only accepts as directories for generated files relative paths (starting at the directory of the document being processed) or absolute paths starting at the root of the filesystem (which in my opinion is totally useless). There is no easy way to generate the files under `_build`.

I would want that either there were a (platform independent) way to specify additional cleaning in make clean, or that absolute paths in autosummary started at the directory of the conf.py file. Both alternatives are, of course, non-exclusive.

**Comment by tk0miya** [comment]
Absolutely!

**Comment by tk0miya** [comment]
I noticed this is a duplicated with #1999. So I'm closing this.
