### ISSUE TITLE
ValueError: too many values to unpack

### ISSUE THREAD

**Issue by sedimentation-fault** [sphinx-doc/sphinx#7409]
**Description**
While building the references of Sage 9.0, I got:

```
# Sphinx version: 2.0.1
# Python version: 3.7.6 (CPython)
# Docutils version: 0.15.2 release
# Jinja2 version: 2.11.1
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/sphinx/cmd/build.py", line 283, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/usr/lib/python3.7/site-packages/sphinx/application.py", line 260, in __init__
    self._init_builder()
  File "/usr/lib/python3.7/site-packages/sphinx/application.py", line 321, in _init_builder
    self.emit('builder-inited')
  File "/usr/lib/python3.7/site-packages/sphinx/application.py", line 440, in emit
    return self.events.emit(event, self, *args)
  File "/usr/lib/python3.7/site-packages/sphinx/events.py", line 76, in emit
    results.append(callback(*args))
  File "/usr/lib/python3.7/site-packages/sphinx/ext/intersphinx.py", line 207, in load_mappings
    for key, (name, (uri, invs)) in app.config.intersphinx_mapping.items():
ValueError: too many values to unpack (expected 2)
```

**How To Reproduce**
I have written a detailed account in:
https://github.com/cschwan/sage-on-gentoo/issues/580

**Expected behavior**
No error should occur.

**Your project**
Sage 9.0 on Gentoo. Using the sage-9.0-r1 ebuild from the sage-on-gentoo overlay: https://github.com/cschwan/sage-on-gentoo

**Environment info**
See error text above.

**Reason**
The error occurs in

`/usr/lib/python3.7/site-packages/sphinx/ext/intersphinx.py", line 207`

According to https://github.com/sphinx-doc/sphinx/issues/3075, it is due to a change that took place in _sphinx 1.4_:

> This is incompatible change since 1.4 (see #2320).
> After the change, the entries was changed to a list of entryname, (links, subitems, key).

Could it be that this change didn't reach line 207 of _intersphinx.py_ yet?

**Comment by tk0miya** [comment]
Please let me know your `intersphinx_mapping` settings. What value did you set?

**Comment by sedimentation-fault** [comment]
Oops...good question - I must confess, I have no idea! Now I feel like a newbie! :baby_chick:  :-)

Let's see: I am trying to compile sage-9.0 and I am stuck at its documentation, which, with sphinx-2.0.1 (and only that! all other versions, from 1.7.5 to 1.8.5 and 2.4.4 break earlier with other errors) breaks at the second pass of the references - you can see the error at the link I posted. 

About the intersphinx_mapping...using _ripgrep_ I found it at

_sage-9.0/src/sage/docs/conf.py_
```

# Cross-links to other project's online documentation.
python_version = sys.version_info.major
intersphinx_mapping = {
    'python': ('https://docs.python.org/',
                os.path.join(SAGE_DOC_SRC, "common",
                             "python{}.inv".format(python_version))),
    'pplpy': (PPLPY_DOCS, None)}

def set_intersphinx_mappings(app):
    """
    Add precompiled inventory (the objects.inv)
    """
    refpath = os.path.join(SAGE_DOC, "html", "en", "reference")
    invpath = os.path.join(SAGE_DOC, "inventory", "en", "reference")
    if app.config.multidoc_first_pass == 1 or \
            not (os.path.exists(refpath) and os.path.exists(invpath)):
        app.config.intersphinx_mapping = {}
        return

    app.config.intersphinx_mapping = intersphinx_mapping

    # Add master intersphinx mapping
    dst = os.path.join(invpath, 'objects.inv')
    app.config.intersphinx_mapping['sagemath'] = (refpath, dst)
```
Now, before you continue please have a look at 

https://trac.sagemath.org/ticket/28856

where some important details might be lurking. For example, it is said there that _"our intersphinx usage differs from normal usage"_ - but I have no idea in which respect...

**Comment by tk0miya** [comment]
Thank you for the info. It seems sagemath docs try to configure via Sphinx events. And it does not work since 2.x because we've refactored the intersphinx. Sorry for inconvenience. But I don't know such hack...
Please let them know to use `config-inited` event instead of `builder-inited` event. And I'll work to allow customizing `intersphinx_mapping` on the event on 3.0.

**Comment by tk0miya** [comment]
I just merged #7415. It allows extensions to modify configurations via `config-inited` event. In this case, sagemath should be fixed to use the event and new Sphinx.

**Comment by sedimentation-fault** [comment]
Thank you very much! I will forward this information to the _sage-on-gentoo_ project.

**Comment by timokau** [comment]
Thanks a lot for going the extra mile and fixing our hacks for us. That is far beyond any responsibility I would have assigned to an upstream project :)

As I said in the trac ticket, I don't really know why we aren't using intersphinx as its supposed to be used. But at least now we'll be able to fix our build with an up-to-date sphinx.
