### ISSUE TITLE
make htmldocs against the kernel with 2.4 versions

### ISSUE THREAD

**Issue by s-t-e-v-e-n-k** [sphinx-doc/sphinx#7419]
**Describe the bug**
Building the HTML docs for the kernel using Python 3.8 and -jauto appears to use at least 1GiB of RAM per-child, whereas under Python 3.6, each child consumed on the order of 280MiB.

I'm also happy to keep digging into this myself with a little direction on the best place to start.

**To Reproduce**
```

Ensure you're using Python 3.8

$ git clone git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
$ cd linux.git
$ pip install sphinx
$ make htmldocs
```

**Expected behavior**
Process children of Sphinx shouldn't consume a large amount of RAM.

**Environment info**
- OS: OpenSUSE Tumbleweed
- Python version: 3.8.1
- Sphinx version: 2.4.4
- Sphinx extensions:  None
- Extra tools: None

**Comment by s-t-e-v-e-n-k** [comment]
Running make htmldocs with Python 3.8 and different Sphinx versions:

2.3.1:  Maximum memory used:  2455.90MiB
2.4.0:  Maximum memory used:  6736.48MiB
2.4.1:  Maximum memory used:  6622.50MiB
2.4.2:  Maximum memory used:  6635.35MiB
2.4.3:  Maximum memory used:  6706.11MiB
2.4.4:  Maximum memory used:  6548.39MiB

**Comment by tk0miya** [comment]
@s-t-e-v-e-n-k How did you measure the memory usage for each version? I'd like to go "git bisect" like approach to find what commit causes the increase of the memory usage.

**Comment by s-t-e-v-e-n-k** [comment]
I set the SPHINXBUILD environment variable for ``make htmldocs`` to a script:

```
#!/bin/bash

trap 'mprof list' EXIT INT TERM

mprof run --include-children /usr/bin/sphinx-build $@
```

That left ``mprofile*dat`` files, which I then sorted to show the highest specific memory usage.

**Comment by tk0miya** [comment]
Thanks, I'll try it later.

**Comment by tk0miya** [comment]
Finally, I found this is the same as #7343, and it was fixed at 3.0. So it would be better to upgrade Sphinx to latest one. But it seems linux-doc conflicts with it...

**Comment by s-t-e-v-e-n-k** [comment]
Excellent, thanks for digging into it! I'm happy to close this if 3.0 fixes it, and we can wait until the kernel supports it.

**Comment by tk0miya** [comment]
Okay, I'm closing this now.
