### ISSUE TITLE
Attributes duplication with Napoleon

### ISSUE THREAD

**Issue by gpotter2** [sphinx-doc/sphinx#7427]
**Describe the bug**
Since 3.0.0 we're seing
```
WARNING: duplicate object description of [xxx], other instance in index, use :noindex: for one of them
```
pop on every attribute of a class documented using Google's style and the `"Attributes:"` tag. The tags are not duplicated but this warning is shown.

**To Reproduce**
I made a reproducible example, available at https://github.com/gpotter2/issues-sphinx
```
git clone https://github.com/gpotter2/issues-sphinx.git
cd issues-sphinx
make html
```

**Expected behavior**
The warning shouldn't be displayed as in Sphinx<3.0.0

**Environment info**
- OS: Ubuntu 18.04/Windows
- Python version: 3.6.9
- Sphinx version: master (Sphinx==3.1.0.dev20200406)
- Sphinx extensions:  `sphinx.ext.autodoc, sphinx.ext.napoleon`

Thanks a lot for your help

**Comment by tk0miya** [comment]
It seems some attributes are shown twice. Sphinx starts to warn they are duplicated since 3.0.
<img width="420" alt="スクリーンショット 2020-04-07 22 23 06" src="https://user-images.githubusercontent.com/748828/78674297-5e855e80-791e-11ea-835f-e7e3ff780268.png">

**Comment by gpotter2** [comment]
You're right.. This isn't supposed to happen right?
This issue could be older than 3.0.0, and i just didn't notice it before..

**Comment by tk0miya** [comment]
I can't remember when autodoc started to support generating a document for class members with `:undoc-members:` option. But it seems Sphinx-2.4 already supported it.
Surely, Sphinx-3.0 starts to warn the conflicts. But I believe it's not broken.

**Comment by gpotter2** [comment]
I see.
I still believe class members should use the given Attributes doc when provided but that's more a feature request than a bug (I'll try to PR that..)
thanks for your help
