### ISSUE TITLE
Autodoc __all__

### ISSUE THREAD

**Issue by yannikschaelte** [sphinx-doc/sphinx#7433]
I use autodoc to generate module documentation, e.g. like [here](https://github.com/ICB-DCM/pyPESTO/blob/master/doc/api_objective.rst). This should document all members of that submodule. However, as seen [here](https://pypesto.readthedocs.io/en/latest/api_objective.html), nothing is shown. In order to make it show, the `__init__.py` of that module must explicitly define `__all__`, it seems. 
If I understand correctly, `__all__` is not required to be defined in python, with some default rules being in use then (exposing all public members). Thus, is it somehow possible to not have to define `__all__` explicitly and still have the module documentation filled properly?

**Comment by tk0miya** [comment]
It seems all members of `pypesto.objective` are imported, right? If so, you should give `:imported-members:` option to generate documents for them. This is not related with `__all__`.
https://github.com/ICB-DCM/pyPESTO/blob/master/pypesto/objective/__init__.py

**Comment by yannikschaelte** [comment]
@tk0miya thanks a lot, `:imported-members:` indeed does the job. I must have missed it in the documentation.
