### ISSUE TITLE
Extra blank lines causes warning errors to display wrong line number

### ISSUE THREAD

**Issue by barbara-sfx** [sphinx-doc/sphinx#7436]
**Describe the bug**
If a file contains multiple blank lines above the location of an error, the warning displays an incorrect line number for where the error is. (It subtracts the number of blank lines when determining what line number contains the error.)

**To Reproduce**
```
make html
```
Look at the warnings

**Expected behavior**
The line number shown in the message matches the line number where the error appears in the file.

**Your project**

[line-number-issue.zip](https://github.com/sphinx-doc/sphinx/files/4447026/line-number-issue.zip)

**Screenshots**
In one of these files, the error is actually on line 18.

![image](https://user-images.githubusercontent.com/17709550/78720910-6e2f8380-78db-11ea-8ee3-84b95ceb8e1c.png)

**Environment info**
- OS: 10.14.6
- Python version: 3.7.7.
- Sphinx version: 2.4.4
- Sphinx extensions:  [ recommonmark, sphinx_markdown_tables]

**Notes**
I originally thought this was a regression for a bug I reported in an old version of sphinx, but in fact it is something new.

**Comment by tk0miya** [comment]
I tried with your attached file and empty conf.py on my local. But I got a correct location.
```
/Users/tkomiya/work/tmp/doc/tmp/apm2-concepts.rst:18: WARNING: undefined label: non-existing-label (if the link has no caption the label must precede a section header)
/Users/tkomiya/work/tmp/doc/tmp/apm2-concepts-ok.rst:16: WARNING: undefined label: non-existing-label-2 (if the link has no caption the label must precede a section header)
```

**Comment by tk0miya** [comment]
I got it. I reproduced your trouble with adding `sphinx_markdown_tables` to the extensions list. I guess this is a bug of the extension, not Sphinx itself. Please report this to their project.
Thanks,
