### ISSUE TITLE
Function's signatures get backslashes on stars (*) after updating sphinx to 3.0.0

### ISSUE THREAD

**Issue by sciunto** [sphinx-doc/sphinx#7439]
**Describe the bug**

In scikit-image, we noticed the appearance of backslashes in the signatures of our functions after updating to sphinx 3.0.0

sphinx 2.4.4:
![Module metrics — skimage v0 16 1 docs](https://user-images.githubusercontent.com/335370/78790832-604b3280-79af-11ea-8665-89a4936e7ec5.png)

sphinx 3.0.0:
![Module metrics — skimage v0 17 dev0 docs](https://user-images.githubusercontent.com/335370/78790844-63deb980-79af-11ea-82dd-b61bea4ac5b3.png)

Original bug report in scikit-image: https://github.com/scikit-image/scikit-image/issues/4566

**Comment by tk0miya** [comment]
Sorry for the inconvenience. Since 3.0, we've stopped to remove backslashes from the signature. So please remove them from your signature. To keep backward compatibility, we also provide `strip_signature_backslash` to remove them like before.
Thanks,

**Comment by sciunto** [comment]
Thanks for the quick reply and the solution @tk0miya !

Actually, I'm not sure to understand fully what you mean by "please remove them from your signature" because there is no backslash in our python files (eg https://github.com/scikit-image/scikit-image/blob/v0.16.1/skimage/metrics/_adapted_rand_error.py#L7)

Nevertheless, I set to True the option you indicate and it solves the issue. Thanks for that!

**Comment by tk0miya** [comment]
Sorry for lack of my word. I guess you're using a 3rd party extension to convert your python script to reST document. So what I meant is that it would be better to remove backslashes "from the extension".

**Comment by sciunto** [comment]
Thank you for your explanations. I'm closing this issue.

**Comment by tk0miya** [comment]
@sciunto I'd like to know what tool or extension do you use to generate these pages. Do you know that?

**Comment by sciunto** [comment]
@tk0miya Our list of dependencies for the documentation is here: https://github.com/scikit-image/scikit-image/blob/master/requirements/docs.txt
We rely on [numpydoc](https://github.com/numpy/numpydoc) for these pages, which is largely used in scientific applications.

**Comment by tk0miya** [comment]
Thank you for letting me know. I'll send a patch to numpydoc not to need to use the `strip_signature_backslash` setting.

**Comment by sciunto** [comment]
Awesome! Thank you @tk0miya !

**Comment by sciunto** [comment]
Please, paste the link in this issue, so I can follow up.

**Comment by tk0miya** [comment]
My PR is here. Please follow it.
https://github.com/numpy/numpydoc/pull/256
