### ISSUE TITLE
Support singledispatch functions in autofunction

### ISSUE THREAD

**Issue by thomascobb** [sphinx-doc/sphinx#7447]
**Is your feature request related to a problem? Please describe.**
At the moment, my docs for https://aioca.readthedocs.io/en/latest/api.html are generated by interspersing text with ``autoclass`` and ``autofunction`` directives. This works well, apart from the fact that singledispatch overloaded signatures get lost when doing this compared to just doing ``automodule``. For now I have a workaround of multiple ``automodule`` directives restricted to single members, which makes sphinx moan about duplicate object references.

**Describe the solution you'd like**
I would like the output of ``autofunction`` on a singledispatch function to be the same as the output of ``SingledispatchFunctionDocumenter`` with an ``automodule`` directive.

**Additional context**
I have tried merging the``SingledispatchFunctionDocumenter`` with the ``FunctionDocumenter`` and it seems to give the expected results, but it makes the ``FunctionDocumenter`` much bigger. I'm happy to submit a PR for this if that is helpful.

**Comment by tk0miya** [comment]
Interesting and Reasonable. I'd like to see how complex it is. Could you make a PR please?

**Comment by thomascobb** [comment]
Ok, I've had a go at this, adding a couple of new test cases.
I also removed the use of `mock.patch` while I was at it...

**Comment by thomascobb** [comment]
I'm reasonably happy at how this looks, what do you think @tk0miya ?

**Comment by tk0miya** [comment]
Please wait a little more. I'll take a look tomorrow. I'm not a full-time OSS worker. So I need time.

**Comment by thomascobb** [comment]
No problem, I didn't mean to sound pushy, thanks for agreeing to take a look
