### ISSUE TITLE
<what happen when you do on which document project>

### ISSUE THREAD

**Issue by Farkhanda123** [sphinx-doc/sphinx#7459]
Exception occurred:
  File "/usr/local/lib/python2.7/dist-packages/sphinxcontrib/doxylink/__init__.py", line 5, in setup
    from .doxylink import setup_doxylink_roles
  File "/usr/local/lib/python2.7/dist-packages/sphinxcontrib/doxylink/doxylink.py", line 63
    def __getitem__(self, arglist: str) -> Entry:
                                 ^
SyntaxError: invalid syntax
The full traceback has been saved in /tmp/sphinx-err-SNIdcy.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
Got this error while ./waf ndn-cxx

**Comment by tk0miya** [comment]
It seems doxylink extension does not support python2! Python2 had already became EOL this year. So please update your environment.
