### ISSUE TITLE
Imgconverter fails to find ImageMagick on Windows

### ISSUE THREAD

**Issue by Daltz333** [sphinx-doc/sphinx#7477]
ImageMagick fails on Windows due to backslash acting as a Python delimiter.

## Issue
ImageMagick is installed on my Windows 10 (Build 2004) machine, but it fails with ```Invalid Drive Specification```. Opening a powershell and running ```convert mysvg.svg mysvg.png``` works as intended, so this is a Sphinx specific issue.

## Workaround
Specify ImageMagick path using
```image_converter = "D:\\System Programs\\ImageMagick-7.0.10-Q16\\convert.exe"```

**Comment by Daltz333** [comment]
I've moved ImageMagick to a non-spaced path on my internal drive and the same issue arises.

**Comment by Daltz333** [comment]
The actual issue was that a program with the name convert already exists in Windows path. Our solution was to do
```
# SVG support
image_converter = "magick"
image_converter_args = "convert"

```

**Comment by tk0miya** [comment]
Thank you for reporting. Good idea to use `magick` command instead.

Note: It seems Debian/Ubuntu does not provide the command...

**Comment by Daltz333** [comment]
That is correct. Debian/Ubuntu default release is still on ImageMagick6, this is introduced in ImageMagick7.

**Comment by Daltz333** [comment]
We've worked around this by using 
```
if os.name == 'nt':
```

**Comment by tk0miya** [comment]
Thank you for comment. I just posted a PR #7483 that switches command by platform. Could you check this please? It is very helpful to me because I don't have windows PC.
