### ISSUE TITLE
make gettext creates a wrong directory

### ISSUE THREAD

**Issue by ynikitenko** [sphinx-doc/sphinx#7488]
**Describe the bug**
In the Sphinx manual (10.2 Translating with sphinx-intl,
10.2.1 Quick guide) it's written 

> 3. Extract translatable messages into pot files.
$ make gettext
The generated pot files will be placed in the _build/gettext directory.

However, this creates pot files in build/gettext (without leading underscore) and disrupts the following recipe. 

The [recipe](https://docs.readthedocs.io/en/stable/guides/manage-translations.html) with `sphinx-build` instead of `make` works fine.

**To Reproduce**

```
$ git clone https://github.com/ynikitenko/lena
$ cd lena
$ pip install -r requirements.txt
$ cd docs
$ make gettext
$ ls build
$ ls
```

**Your project**

https://github.com/ynikitenko/lena

**Environment info**

- OS: Fedora Core 29.
- Python version: 3.7.5
- Sphinx version: v2.4.3.
- Sphinx extensions: [
    'sphinx.ext.autodoc',
    'sphinx.ext.autosummary',
    'sphinx.ext.coverage',
    'sphinx.ext.graphviz',
    'sphinx.ext.mathjax',
    'sphinx.ext.todo',
    'sphinx.ext.viewcode',
    'sphinxcontrib.napoleon',]

**Additional context**

- https://www.sphinx-doc.org/en/2.0/usage/advanced/intl.html#quick-guide

**Comment by tk0miya** [comment]
Oh, our documentation is wrong. Please use `build/gettext` instead in your case.

It came from the difference of choice in `sphinx-quickstart`. The project that choices Yes to "Separate source and build directories" has a build directory without underscore at the top of its name. But the project that choices No has `_build` directory instead.

**Comment by ynikitenko** [comment]
Fine. Now I understand the source. So, is there any reason to use `_build`? In readthedocs they recomment `_build` - I don't know why. 
https://docs.readthedocs.io/en/stable/guides/manage-translations.html

Is it safe to use what you suggest if I use readthedocs to store my documentation?

**Comment by tk0miya** [comment]
>So, is there any reason to use _build?

Nothing. Sphinx and sphinx-intl does not mind the name of the build directory. So you can use any name you like instead.
If my understanding correct, the only reason why `_build` used is the underscored directory is usually displayed before other files or directories on `ls` command and file-explorers.

>Is it safe to use what you suggest if I use readthedocs to store my documentation?

Yes, `build/gettext` is also fine.

**Comment by ynikitenko** [comment]
Thank you. But I disagree with the removal of the *bug* label: this is definitely a bug in the documentation.

**Comment by tk0miya** [comment]
Do you have good idea to fix it?

**Comment by ynikitenko** [comment]
Just change the documentation to contain "build" or, if there are two possible variants, explain them as you explained them here.
