### ISSUE TITLE
Add glob option to autosummary directive

### ISSUE THREAD

**Issue by ghost** [sphinx-doc/sphinx#7495]
**Describe the requested feature**
I am using autosummary to document a large number of python packages and scripts, which are maintained by a number of different developers. An example structure is:

```
repo/
├── package1/
│   ├── __init__.py
│   ├── foo.py
│   └── bar.py
├── package2/
│   ├── __init__.py
│   └── bee.py
├── script1.py
├── script2.py
└── docs/
    └── index.rst
```

I would like to automatically document all packages and scripts, without hard-coding in which modules and scripts are present as I expect them to be frequently changing. My current solution is to use autosummary in the index.rst:
```
# contents of index.rst

.. autosummary::
   :toctree:

   package1
   package2
   script1
   script2
   etc
```

I also need to put an autosummary directive in each package's `__init__.py`, listing out all of the component modules in the package:

``` python
# contents of package1/__init__.py

""" Package docstring here

This package contains the following:

.. autosummary::
   :toctree:

   foo
   bar
"""

import numpy as np
etc
```

This is not ideal, as if anyone for example adds a new file `package1/baz.py`, I need to update the corresponding autosummary directive in `package1/__init__.py` to include `baz`.

**Describe the solution you'd like**
If the autosummary directive accepted the glob directive, I could simply write this in the `__init__.py` and be confident that any and all modules in the package would be documented:

``` python
# contents of package1/__init__.py

""" Package docstring here

.. autosummary::
   :toctree:
   :glob:

   *
"""

import numpy as np
etc
```

**Additional context**
Slightly related to issue #7490

**Comment by tk0miya** [comment]
It seems your goal is a "recursive" feature, right? If so, I think globbing is not a good way for that. Now we're going to add a recursive feature in #6040. I believe it resolves your case.

**Comment by ghost** [comment]
Yes, I think the "recursive" feature would indeed be a better way of doing what I'm trying to do. I'm looking forward to it being released! I'll lose this issue then as it's essentially a duplicate.
