### ISSUE TITLE
The arguments to the __init__ method, which can only be passed as keyword-only arguments, are documented as having a default of None.

### ISSUE THREAD

**Issue by PLCnista** [sphinx-doc/sphinx#7510]
**Describe the bug**
The arguments to the __init__ method, which can only be passed as keyword-only arguments, are documented as having a default of None.

**To Reproduce**
```python
class Foo:
    """Test class."""
    def __init__(self, a: int, *, b: str, c: float):
        """Init Foo

        :param a: first argument
        :type a: int

        :param b: second argument
        :type b: str

        :param c: third argument
        :type c: float
        """
        pass
```
<pre>
Foo
---
.. module:: pytelegrambots.for_so

.. autoclass:: Foo
    :members:
    :special-members: __init__
</pre>
Result:
![Text](https://i.imgur.com/5mOZPJK.png)
**Expected behavior**
A clear and concise description of what you expected to happen:
(edited screenshot)
![Text](https://i.imgur.com/VU6Prtl.png)

**Environment info**
- OS: [Ubuntu 18.04]
- Python version: [3.7.2]
- Sphinx version: [sphinx-build 3.0.1]
- Sphinx extensions:  [sphinx.ext.autodoc, 'sphinx.ext.viewcode']

**Comment by tk0miya** [comment]
Fixed by #7511. Thank you for reporting!
