### ISSUE TITLE
Sphinx inspects objects, can lead to needless build errors

### ISSUE THREAD

**Issue by a-recknagel** [sphinx-doc/sphinx#7516]
**Describe the bug**
If I have an object in one of my modules that raises some kind of error in its `__getattr__`, it will prevent sphinx (with autodocs) from building docs for said module.

**To Reproduce**
Put something like this in a file and try to generate docs for it.
```python
class Foo:
    def __getattr__(self, item):
        raise RuntimeError('fufufu!')

foo = Foo()
```

See also https://github.com/a-recknagel/Flask-Shortcut/pull/7/checks?check_run_id=600063576 for an actual error, the workflow and the run logs should give instructions on how reproduce it in detail.

**Environment info**
- OS: on both windows and ubuntu
- Python version: 3.6.x
- Sphinx version: 3.0.2 (3.0.1 is still fine)
- Sphinx extensions:  sphinx.ext.autodoc

**Additional context**
This bug was introduced with 3.0.2 in this commit: https://github.com/sphinx-doc/sphinx/commit/e9b64373cd3728dc23e8e6b753a6a8d55e74af73#diff-48ca4d6544b092f35d729127500bff5fR581. I think it should be ok to just surround it with a bare `try..except`, since there is no info whatsoever which kind of errors a user might raise. In my case, it was flask's `request` proxy, which probably a few more people will run into. So here is part of the stacktrace to help them google the issue:

 ```
$ sphinx-build docs/ public/ -b html
Running Sphinx v3.0.2
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 2 source files that are out of date
updating environment: [new config] 2 added, 0 changed, 0 removed
reading sources... [ 50%] autodoc/flask_shortcut
Exception occurred:
  File "...\venv\lib\site-packages\flask\globals.py", line 38, in _lookup_req_object
    raise RuntimeError(_request_ctx_err_msg)
RuntimeError: Working outside of request context.

This typically means that you attempted to use functionality that needed
an active HTTP request.  Consult the documentation on testing for
information about how to avoid this problem.
The full traceback has been saved in ...\AppData\Local\Temp\sphinx-err-rzyl88fm.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**Comment by jace** [comment]
I'm encountering this with Sphinx 3.4.2 a few lines above, in the `hasattr` call. The problem appears to have been introduced in https://github.com/sphinx-doc/sphinx/commit/476169284d2c1ae36d60fd139d5631afa2eade4c 10 days ago.
