### ISSUE TITLE
Wrong CWD when creating JavaScript docs

### ISSUE THREAD

**Issue by ghost** [sphinx-doc/sphinx#7521]
**Describe the bug**
When creating JavaScript docs via `devpi upload --with-docs` alias `python3 setup.py build_sphinx -E --build_dir /tmp/xxx` Sphinx expects the cwd being `./docs/`, however it actually is `.`. This wrong cwd results in sphinx not finding the Javascript files below the directory configured with the `js_source_path` directive in `docs/conf.py`. This pertains to line 156sqq. of `sphinx/application.py`. On line 157 `abspath(self.confdir)` returns the wrong path due to the wrong cwd.

**To Reproduce**
I'm not aware of any Python (Django) package containing JavaScript documentation. I came across this bug when dev'ing a package for a client.

So here's the setup:

0. Project Root: `/home/bobesch/python/packages/js-utils/

1. JavaScript file with documentation: `/home/bobesch/python/packages/js-utils/js_utils/static/js_utils/js/utils.js

2. In `docs/conf.py

```
# Add any Sphinx extension module names here, as strings. They can be extensions
# coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = ['sphinx.ext.autodoc', 'sphinx.ext.viewcode', 'sphinx_js']

# Where to find JavaScript files
js_source_path = '../js_utils/static/js_utils/js/'
```

3. Creating the docs via `sphinx-apidoc -o docs/ ./js_utils/static` is ok. The docs are created as expected.

4. BUT, trying to create the docs via `devpi upload --with-docs` alias `python3 setup.py build_sphinx -E --build_dir /tmp/xxx` throws the error:

```
detected devpi:upload section in /home/bobesch/python/packages/js-utils/setup.cfg
using workdir /tmp/devpi9
copied repo /home/bobesch/python/packages/js-utils/.git to /tmp/devpi9/upload/js-utils/.git
pre-build: cleaning /home/bobesch/python/packages/js-utils/dist
-->  /tmp/devpi9/upload/js-utils$ /usr/bin/python3 setup.py build_sphinx -E --build-dir /tmp/devpi9/upload/js-utils/build 
ERROR: Unable to find the source file or directory /tmp/devpi9/upload/js_utils/static/js_utils/js

Sphinx error:
jsdoc found no JS files in the directories ['/tmp/devpi9/upload/js_utils/static/js_utils/js']. Make sure js_source_path is set correctly in conf.py. It is also possible (though unlikely) that jsdoc emitted invalid JSON.
Traceback (most recent call last):
  File "/home/bobesch/.local/bin/devpi", line 8, in <module>
    sys.exit(main())
  File "/home/bobesch/.local/lib/python3.6/site-packages/devpi/main.py", line 36, in main
    return method(hub, hub.args)
  File "/home/bobesch/.local/lib/python3.6/site-packages/devpi/upload.py", line 44, in main
    p = exported.setup_build_docs()
  File "/home/bobesch/.local/lib/python3.6/site-packages/devpi/upload.py", line 437, in setup_build_docs
    "--build-dir", build], cwd=self.rootpath)
  File "/home/bobesch/.local/lib/python3.6/site-packages/devpi/main.py", line 292, in popen_output
    return subprocess.check_output(args, cwd=str(cwd)).decode('utf-8')
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'setup.py', 'build_sphinx', '-E', '--build-dir', '/tmp/devpi9/upload/jsutils/build']' returned non-zero exit status 1.
```

Bottomline: Sphinx expects the cwd being `./docs/`, however it actually is `.`.

**Environment info**
- OS: Linux
- Python version: 3.6 - 3.8
- Sphinx version: 2.8
- Sphinx extensions: ['sphinx.ext.autodoc', 'sphinx.ext.viewcode', 'sphinx_js']

**Comment by tk0miya** [comment]
>Bottomline: Sphinx expects the cwd being ./docs/, however it actually is ..

Really? I think "sphinx_js" expects that, not Sphinx. So I consider this is a bug of sphinx_js.

**Comment by tk0miya** [comment]
I'm closing this because this has been not updated for long time.
