### ISSUE TITLE
Can I add external web page in copyright in conf.py ?

### ISSUE THREAD

**Issue by jiapei100** [sphinx-doc/sphinx#7524]
How to add external web page in **conf.py** ?

**Comment by tk0miya** [comment]
What is an "external web page"? AFAIK, Sphinx does not have a such configuration. What do you expect?

**Comment by jiapei100** [comment]
@tk0miya 

I'm expecting a **linkage** to my **personal/company's webpage** just at the **copyright**, which now resides in **conf.py** .

**Comment by tk0miya** [comment]
Unfortunately, Sphinx does not support such configuration. To do that, please customize HTML template as you like.
https://www.sphinx-doc.org/en/master/templating.html
