### ISSUE TITLE
sphinx-quickstart Makefile is missing targets

### ISSUE THREAD

**Issue by ConorSheehan1** [sphinx-doc/sphinx#7528]
**Describe the bug**
`sphinx-quickstart` Makefile is missing html and many other targets.

**To Reproduce**
```
$ pipenv install sphinx
$ pipenv run sphinx-quickstart
```

**Expected behavior**
I'm following the docs here:
https://docs.readthedocs.io/en/stable/intro/getting-started-with-sphinx.html

I'd expect the Makefile to be the same as the one in the youtube video in the docs
https://www.youtube.com/watch?v=oJsUvBQyHBs
https://github.com/myusuf3/doctut/blob/master/docs/Makefile

However the Makefile generated is the following:
```
# Minimal makefile for Sphinx documentation
#

# You can set these variables from the command line, and also
# from the environment for the first two.
SPHINXOPTS    ?=
SPHINXBUILD   ?= sphinx-build
SOURCEDIR     = source
BUILDDIR      = build

# Put it first so that "make" without argument is like "make help".
help:
	@$(SPHINXBUILD) -M help "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)

.PHONY: help Makefile

# Catch-all target: route all unknown targets to Sphinx using the new
# "make mode" option.  $(O) is meant as a shortcut for $(SPHINXOPTS).
%: Makefile
	@$(SPHINXBUILD) -M $@ "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)

```

**Environment info**
- OS: [e.g. Unix/Linux/Mac/Win/other with version]
- Python version: [e.g. 3.6.8]
- Sphinx version: [e.g. 3.0.2]

**Comment by ConorSheehan1** [comment]
Ah sorry I think I figured it out. I needed to run sphinx-quickstart from the pipenv shell.
```bash
# fails
pipenv run sphinx-quickstart
make html

# works
pipenv shell
sphinx-quickstart
make html
```

Still, might be worth updating the docs, or https://github.com/myusuf3/doctut with the new Makefile?
Or maybe a note on working with pipenv or virtual envs?

**Comment by tk0miya** [comment]
Indeed, the generated Makefile is different from the old one. But It works fine like ever. Is there any problem?

**Comment by ConorSheehan1** [comment]
@tk0miya no it seems to work fine, but maybe the docs could be updated? I think any of the following would help:
1. Add notes on using Sphinx with newer python dependency managers like pipenv and poetry.
2. Update the YouTube video in the docs to use the latest version of Sphinx.
3. Update the example GitHub repo to use the latest version of Sphinx.

```bash
pipenv run sphinx-quickstart
make html
# fails with the following error:
# makefile:20: recipe for target 'html' failed make: *** [html] error 127

pipenv shell
sphinx-quickstart
make html
# finishes successfully
```

**Comment by tk0miya** [comment]
I'm sorry, but all you're listed is not the official resources of Sphinx project. We don't have youtube videos and example repositories. If you're saying about the resources on readthedocs, please report that to readthedocs project.

Thanks,
