### ISSUE TITLE
Convert :kbd: to nested <kbd> HTML elements

### ISSUE THREAD

**Issue by charego** [sphinx-doc/sphinx#7530]
**Is your feature request related to a problem? Please describe.**

[:kbd:](https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#role-kbd) describes "a sequence of keystrokes". Sphinx converts it to a single [`<kbd>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/kbd) element:
```
:kbd:`Control-x Control-f`
```
becomes
```html
<kbd>Control-x Control-f</kbd>
```

**Describe the solution you'd like**

Potentially sphinx could parse the `:kbd:` value and convert it to individual (or nested) `<kbd>` elements, which is what [MDN suggests](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/kbd#Representing_keystrokes_within_an_input) as a way to represent key combinations. Something like:
```html
<-- Individual -->
<kbd>Control</kbd>-<kbd>x</kbd> <kbd>Control</kbd>-<kbd>f</kbd>

<-- Nested -->
<kbd>
    <kbd>Control</kbd>-<kbd>x</kbd> <kbd>Control</kbd>-<kbd>f</kbd>
</kbd>
```

**Describe alternatives you've considered**

Alternatively the sphinx user could rewrite their markup:
```
:kbd:`Control`\ -\ :kbd:`x` :kbd:`Control`\ -\ :kbd:`f`
```

**Related**

- https://github.com/sphinx-doc/sphinx/issues/3160
- https://github.com/sphinx-doc/sphinx/pull/4197

**Comment by tk0miya** [comment]
+1: Reasonable.

**Comment by charego** [comment]
Great! Thank you.

**Comment by charego** [comment]
Hi! I just noticed a potential downside to this implementation. What should happen if a single key is 2+ words?

Example from fish documentation (built with Sphinx 3.2.1):

```
The pager can be navigated with the arrow keys, :kbd:`Page Up` / :kbd:`Page Down`, ...
```

```xml
<p>
  The pager can be navigated with the arrow keys, 
  <kbd class="kbd docutils literal notranslate">
    <kbd class="kbd docutils literal notranslate">Page</kbd> <kbd class="kbd docutils literal notranslate">Up</kbd>
  </kbd> /
  <kbd class="kbd docutils literal notranslate">
    <kbd class="kbd docutils literal notranslate">Page</kbd> <kbd class="kbd docutils literal notranslate">Down</kbd>
  </kbd>, ...
</p>
```

<img width="859" alt="kbd" src="https://user-images.githubusercontent.com/5209296/95662209-41b32900-0b03-11eb-9ab0-4cf5f1d92501.png">

Workaround for now is to use one-word names... "PgUp", "PageDown", "ScrollLock", etc.

**Comment by idnsunset** [comment]
> Hi! I just noticed a potential downside to this implementation. What should happen if a single key is 2+ words?
> 
> Example from fish documentation (built with Sphinx 3.2.1):
> 
> ```
> The pager can be navigated with the arrow keys, :kbd:`Page Up` / :kbd:`Page Down`, ...
> ```
> 
> ```
> <p>
>   The pager can be navigated with the arrow keys, 
>   <kbd class="kbd docutils literal notranslate">
>     <kbd class="kbd docutils literal notranslate">Page</kbd> <kbd class="kbd docutils literal notranslate">Up</kbd>
>   </kbd> /
>   <kbd class="kbd docutils literal notranslate">
>     <kbd class="kbd docutils literal notranslate">Page</kbd> <kbd class="kbd docutils literal notranslate">Down</kbd>
>   </kbd>, ...
> </p>
> ```
> 
> <img alt="kbd" width="859" src="https://user-images.githubusercontent.com/5209296/95662209-41b32900-0b03-11eb-9ab0-4cf5f1d92501.png">
> 
> Workaround for now is to use one-word names... "PgUp", "PageDown", "ScrollLock", etc.

You can escape the space by prefixing it with a single backslash, e.g., `` :kbd:`Page\ Up` ``.
What I think could improve is to put some class attribute in the nested `<kbd>` element so that it would be easy to distinguish between outer and inner kbd elements and write appropriate CSS for them.
