### ISSUE TITLE
Type annotations are omitted on properties

### ISSUE THREAD

**Issue by petsuter** [sphinx-doc/sphinx#7531]
```
class C:
    def f(self) -> int:
        pass

    @property
    def p(self) -> int:
        pass
```

Sphinx creates documentation that includes the type annotations on the function `f` (as desired), but omits the type annotations on the property `p`. This seems like a bug.

**Comment by tk0miya** [comment]
Thank you for reporting. But it was already reported as #7383. So I'm closing this.

**Comment by petsuter** [comment]
Thanks. Sorry, it somehow did not show up in my search.
