### ISSUE TITLE
Big vertical whitespace rendered in official documentation

### ISSUE THREAD

**Issue by septatrix** [sphinx-doc/sphinx#7534]
**Describe the bug**
The docs render a big vertical whitespace in on the official website.
I do not know if this happens whether something in the markup or something in Sphinx changed but it is visible in the docs for versions since 3.x (i.e. 3.x and master in the selection)

**To Reproduce**
Visit https://www.sphinx-doc.org/en/3.x/usage/restructuredtext/domains.html#basic-markup

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/24257556/79983716-6d384d80-84a8-11ea-9db2-f3b27cb333a7.png)

**Environment info**
- Extra tools: current Firefox and current Chromium

**Comment by tk0miya** [comment]
Thank you for reporting. Fixed.
