### ISSUE TITLE
ValueError: not enough values to unpack (expected 5, got 4) readthedocs failed on https://github.com/alexandreCameron/boar/

### ISSUE THREAD

**Issue by alexandreCameron** [sphinx-doc/sphinx#7553]
**Describe the bug**

I'm trying to upload my doc on read the docs, but the build failted.

I could select my github project on read the docs, but the build failed

I'm able to build the doc in the github action CI, see :

https://github.com/alexandreCameron/boar/runs/616112955?check_suite_focus=true

python tests  > python doc

**To Reproduce**

1. Fork repo
2. Try to build the doc on readthedoc

**Expected behavior**

Build succeeds.

**Your project**

https://github.com/alexandreCameron/boar/

**Screenshots**

**Environment info**

readthedocs

**Additional context**

Error message:

```bash
python /home/docs/checkouts/readthedocs.org/user_builds/boar/envs/latest/bin/sphinx-build -b latex -D language=en -d _build/doctrees . _build/latex
```

```
Running Sphinx v1.8.5
loading translations [en]... done
making output directory...
building [mo]: targets for 0 po files that are out of date
building [latex]: all documents
updating environment: 2 added, 0 changed, 0 removed
reading sources... [ 50%] boar-doc
reading sources... [100%] index

WARNING: autodoc: failed to import module 'boar'; the following exception was raised:
No module named 'boar'
looking for now-outdated files... none found
pickling environment... done
checking consistency... done

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/boar/envs/latest/lib/python3.7/site-packages/sphinx/builders/latex/__init__.py", line 192, in write
    docname, targetname, title, author, docclass = entry[:5]
ValueError: not enough values to unpack (expected 5, got 4)
The full traceback has been saved in /tmp/sphinx-err-g0jgkxj3.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**Comment by alexandreCameron** [comment]
Hi,

I'm new to readthedocs, the error might be simple but I was not able to find an answer on SO.

Thanks for the help.

**Comment by tk0miya** [comment]
It seems your setting is broken:
https://github.com/alexandreCameron/boar/blob/45c54f57c5cd5bd47359c3a8af16e251fba684ef/doc/conf.py#L142-L147

`latex_documents` is a list of tuples that contains 5 elements. But your configuration is a list of tuples containing 4-elements.
Please update your conf.py.
