### ISSUE TITLE
htmlhelp builder: keep original HTML files encoding

### ISSUE THREAD

**Issue by char101** [sphinx-doc/sphinx#7563]
**Is your feature request related to a problem? Please describe.**
Most HTML files nowadays are using utf-8 encoding. And htmlhelp supports utf-8 encoding for the HTML files. Only the `hhp`/`hhc`/`hhk` files are required to use `cp125x` encoding. So rather than reencoding the HTML pages based on the locale (with the risk of having box/unreadable characters), it is better to keep the HTML files as is.

**Describe the solution you'd like**
Keep the input HTML files as is, don't reencode them.

One example of the problem I experienced was when I tried to build a chm output for `flask` documentation using the `sphinx_rtd_theme` theme. Since the theme hardcode the HTML encoding as `utf-8`, some characters appears as box characters in the resulted HTML pages.

**Comment by tk0miya** [comment]
Sphinx expect to use a template variable `encoding` to change the encoding of HTML output.
https://github.com/sphinx-doc/sphinx/blob/3.x/sphinx/themes/basic/layout.html#L118-L120

But it seems sphinx_rtd_theme does not support it.
https://github.com/readthedocs/sphinx_rtd_theme/blob/35034930943c38e6f839ad89a4e3bcba811010d5/sphinx_rtd_theme/layout.html#L14

I think sphinx_rtd_theme does not support change output encoding. No reason to change Sphinx itself.
