### ISSUE TITLE
LaTeX with French babel and memoir crash: "Illegal parameter number in definition of \FNH@prefntext"

### ISSUE THREAD

**Issue by ygversil** [sphinx-doc/sphinx#7576]
**Describe the bug**
When running `make latexpdf` on a project which is configured to used Babel with French language and the `memoir` class, there is a crash whith the following error:
```
! Illegal parameter number in definition of \FNH@prefntext.
<to be read again> 
                   1
l.84 \begin{document}
```

**To Reproduce**
```shell
$ sphinx-quickstart # project name: Test ; author: Me ; version: 0.1; and of course, language: fr
```
Now add the following lines in `conf.py`.
```python
# -- Options for LaTeX output ---------------------------------------------
latex_documents = [
    ('index', 'test.tex',
     project, 'Me',
     'memoir'),
]
```
And then try to build PDF.
```shell
$ make latexpdf
```

**Expected behavior**
Successful build with no error.

**Environment info**
- OS: Archlinux with latest packages
- Python version: 3.8.2
- Sphinx version: 3.0.3
- Extra tools: texlive-core 2019.52579

**Additional context**
If I replace `'memoir'` with `'manual'` in `latex_documents`, it works.

If I use Polyglossia instead of babel, with the following key/value pair in `latex_elements`, it works too.
```python
    'babel': (r"""\usepackage{polyglossia}
\setdefaultlanguage{french}""")
```

If I switch to `language = 'en'` in `conf.py`, it also works after cleaning.

**Comment by jfbu** [comment]
Thanks for reporting. I will look into it.

**Comment by jfbu** [comment]
This is a frailty in footnotehyper-sphinx.sty. As a temporary work-around, try adding this to `conf.py`.

```
latex_elements = {
    'preamble' : r'''
\makeatletter
\def\@makefntextFB #1{\def \footscript ####1{####1\dotFFN \kernFFN }%
  \setlength {\footmarkwidth }{\FBfnindent }%
  \setlength {\footmarksep }{-\footmarkwidth }%
  \setlength {\footparindent }{\parindentFFN }\makefootmark #1}%
\makeatother
'''
}
```

A general fix may be some time in coming.
