### ISSUE TITLE
Including file tat has :orphen: as first line adds orphen: text

### ISSUE THREAD

**Issue by Aukstkalnis** [sphinx-doc/sphinx#7585]
**Describe the bug**
I have a project documentation, that has shared folder in source directory. This folder contains common features descriptions. Each file is a separate folder description. I include them in other files. In project's folder I create the same file but the only text is include feature from shared folder. I need :orphen: in shared file to prevent from "file not included anywhere" errors. So now I needed include file from shared folder in the middle of second project's documentation's file and I can see orphen: text there.

**To Reproduce**
```
$ in source folder create shared folder
$ in shared folder create file with context that starts with :orphen:
$ in source directory create file and include shared file
$ In this case no orphen text should be visible
$ create file with context and include shared file in the middle
$ in this case orphen text should be visible.
```

**Expected behavior**
No orphen: text should be visible

**Your project**
Project is internal at our company so it is not allowed to be shared.

**Screenshots**
![image](https://user-images.githubusercontent.com/9738294/80715482-157c9080-8aff-11ea-8bc9-73db663764f6.png)

**Environment info**
- OS: Windows 10
- Python version: 3.8.2
- Sphinx-build version: 3.0.3
- Sphinx extensions:  I don't now. How to get the list?

**Comment by tk0miya** [comment]
To ignore shared folder, please use `exclude_patterns` instead. The orphan flag is used for independent documents.

**Comment by Aukstkalnis** [comment]
Can you provide documentation link abaut this exclude paterns?

**Comment by tk0miya** [comment]
Here
https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-exclude_patterns

**Comment by Aukstkalnis** [comment]
Thank you very much. That's what I was looking for from the very beginning :D It's a shame, tat i couldn't find it sooner. You can close this case if you consider orphen: text adding not a bug :)

**Comment by tk0miya** [comment]
Okay, I'm closing this. Have a good documentation :-)
