### ISSUE TITLE
Typo in sphinx-build output.

### ISSUE THREAD

**Issue by electric-coder** [sphinx-doc/sphinx#7587]
**Describe the bug**
There's a noticeable typo in sphinx-build output.

**To Reproduce**
Run `make html` on a project, the output:

> updating environment: [new config] 
> fimding sources... [ 10%] 

Instead of "fimding" it should read "finding".

**Comment by tk0miya** [comment]
Thank you for reporting. But that's strange. sphinx-build never outputs "finding sources...". It outputs "reading sources..." instead. Could you let me know the version of Sphinx you're using?

**Comment by electric-coder** [comment]
Just tested it again. The bug is actually different from what I initially described.

> Running Sphinx v3.0.2
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 29 source files that are out of date
updating environment: [new config] 29 added, 0 changed, 0 removed
abc4ing sources... [  6%] my_package
abcd5ng sources... [ 96%] my_package.my_sub_package
reading sources... [100%] my_package.another_sub_package
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] my_package.another_sub_package
generating indices...  genindex py-modindexdone
writing additional pages...  searchdone
copying static files... ... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded.

To reproduce introduce 2 prints at the end of 2 different modules, in 2 different packages, like this:

`print("abc4")` at the end of a module in `my_package`.

and 

`print("abcd5")` at the end of a module in `my_package.my_sub_package`.

The OP description had a print("fim") which overwrote the first 3 characters of "reading" resulting in "fimding"...

Should it matter, the project is installed with `pip install -v -e .` from the usual source layout `Project/src/my_package`.

**Comment by tk0miya** [comment]
Thank you for the info. As the document of autodoc said, this is well-known behavior.

>autodoc imports the modules to be documented. If any modules have side effects on import, these will be executed by autodoc when sphinx-build is run.
>If you document scripts (as opposed to library modules), make sure their main routine is protected by a if __name__ == '__main__' condition.
>https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html

Please modify your script if needed.
Thanks,
