### ISSUE TITLE
pyplot disappears with latest master

### ISSUE THREAD

**Issue by jschueller** [sphinx-doc/sphinx#7588]
**Describe the bug**
My pyplots graphs are not shown anymore with recent master around end of april (v3.0.3 is good, or master from 10 april), bisecting points to #7548

**To Reproduce**
I created a small testcase at https://github.com/jschueller/sphinx-pyplot-test:
```
$ git clone https://github.com/jschueller/sphinx-pyplot-test.git
$ cd sphinx-pyplot-test
$ pip install sphinx matplotlib
$ ./build.sh
```

**Expected behavior**
The pyplot graph should appear.

**Your project**
www.OpenTURNS.org

**Screenshots**
with sphinx master 10/4/20 OK: http://openturns.github.io/openturns/latest/user_manual/_generated/openturns.GumbelCopula.html
with sphinx master end of april BAD: http://openturns.github.io/openturns/master/user_manual/_generated/openturns.GumbelCopula.html

**Environment info**
- OS: Linux
- Python version: 3.8.2
- Sphinx version: master
- Sphinx extensions:  autodoc, autosummary, matplotlib.sphinxext.plot_directive

**Additional context**
I bisected between v3.0.3 and HEAD and saw that it stems from #7548:
```
e5192ba48b45576e636e7dce82ad9183051443ed is the first bad commit
commit e5192ba48b45576e636e7dce82ad9183051443ed
Author: Takeshi KOMIYA <i.tkomiya@gmail.com>
Date:   Sat Apr 25 01:25:00 2020 +0900

    refactor: AutosummaryRender
```

but I noticed there are more commits related to this: #7570

cc @tk0miya

**Comment by tk0miya** [comment]
Has it still occurred? I think the #7548's trouble was fixed at #7578.

**Comment by jschueller** [comment]
Yes, this still does not work, I pulled the master this morning.

**Comment by tk0miya** [comment]
I found the reason for the error. #7589 will resolve your case.

**Comment by jschueller** [comment]
thanks
