### ISSUE TITLE
Sphinx, unlike Docutils, incorrectly renders consecutive backslashes

### ISSUE THREAD

**Issue by liborjelinek** [sphinx-doc/sphinx#7610]
**Describe the bug**
Sphinx incorrectly renders four or more consecutive backslashes. In pure Docutils, they are renderer properly according with RST spec.

**To Reproduce**
The following snippet demonstrantes buggy rendering. 
```
Two \\

Three \\\

Four \\\\

Five \\\\\

Six \\\\\\
```

**Expected behavior**
Two backslashes should be rendered as `\`. Three still as `\`. Four and five as `\\`. Six as `\\\` and so on. This is how it works in Docutils.

**Screenshots**
![image](https://user-images.githubusercontent.com/383059/80948942-5cb29c00-8df3-11ea-8fe9-ca4bc390eef9.png)

**Environment info**
- OS: Linux
- Python version: 3.6
- Sphinx version: 3.0.2
- Sphinx extensions:  none

**Comment by tk0miya** [comment]
Thank you for filing. I'll investigate it from now on.
