### ISSUE TITLE
Generate RST content using Jinja templating for Latex builder

### ISSUE THREAD

**Issue by kynzie** [sphinx-doc/sphinx#7612]
**Is your feature request related to a problem? Please describe.**
As a teacher, I use all the time `sphinx-doc` to write my course but also my exams, and my tutorials. Tutorials and exams have the same structure : a succession of exercises. Currently, I use my own directive to include exercises, creating each time I need, a new RST file looking like:

```rst
.. exercise:: ../exercises/fibo_rec/main.rst
  :lang: c

.. exercise:: ../exercises/bst_search/main.rst
  :lang: python
```
This file is included using the `toc-tree` directive in the `master_doc` file.

It would ease my daily work considerably if I can be able to overwrite this document using jinja directly:

```
{% for ex in exercises %}
        {% block ex %}{% endblock %}
{% endfor %}
```
and configure this template in the `conf.py` file.

Going further, this feature would allow me also to create a template for an exercise, generalizing my exercise structure too (which are RST documents for the moment).

**Describe the solution you'd like**
As Jinja is included in sphinx, it would be great to use jinja templating in Latex builder in order to generate an RST on `source-read` event hook, like HTML builder does with the `template` attribute and the `html_context` in the `conf.py` (if I am correct).

**Describe alternatives you've considered**
I could use a sphinx extension like [sphinx-jinja](https://pypi.org/project/sphinx-jinja/) but it is kinda of sad to use an extension as Jinja is natively supported by other builders. 

**Additional context**
I am ready to help on this.

**Comment by tk0miya** [comment]
-1: I think the feature you mentioned is what sphinx-jinja does. No reason to do the same thing on sphinx-core. I'd like to make sphinx-core simple and small.

**Comment by kynzie** [comment]
Yes, I mentioned `sphinx-jinja` as an alternative. I was suggesting this feature in order to linearize features between builders but I get your point.

**Comment by kynzie** [comment]
Oh. Jinja used in HTML builder is to template HTML theme. Not to generate any RST content.

**Comment by tk0miya** [comment]
I forget to mention it. At present, Sphinx itself does not provide any reST generators.
