### ISSUE TITLE
Imgconverter runs in gettext and linkcheck builders

### ISSUE THREAD

**Issue by Daltz333** [sphinx-doc/sphinx#7628]
Imgconverter should not run in these modes.

**Comment by Daltz333** [comment]
Currently investigating manipulating the Image converter class

**Comment by tk0miya** [comment]
How did you check that? AFAIK, imgconverter is invoked only for HTML (and its families), LaTeX, and TeXInfo builders.

Note: At implementation level, it reacts a builder having `supported_image_types` attribute. By default, it is not set. So it does not work for gettext and linkcheck builders.

**Comment by Daltz333** [comment]
The is_available method seems to run. As I get errors about imagemagick not being installed on the linkcheck builder.

**Comment by tk0miya** [comment]
I understand. You're right.
