### ISSUE TITLE
autofunction raises an error if an integer given

### ISSUE THREAD

**Issue by tk0miya** [sphinx-doc/sphinx#7629]
**Describe the bug**
autofunction raises an error if an integer given

**To Reproduce**

```
.. autofunction:: errno.EINTR
```
```
WARNING: error while formatting arguments for errno.EINTR:
Traceback (most recent call last):
  File "/Users/tkomiya/work/sphinx/sphinx/ext/autodoc/__init__.py", line 1049, in format_args
    sig = inspect.signature(unwrapped)
  File "/Users/tkomiya/work/sphinx/sphinx/util/inspect.py", line 406, in signature
    signature = inspect.signature(subject)
  File "/Users/tkomiya/.pyenv/versions/3.8.2/lib/python3.8/inspect.py", line 3093, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped)
  File "/Users/tkomiya/.pyenv/versions/3.8.2/lib/python3.8/inspect.py", line 2842, in from_callable
    return _signature_from_callable(obj, sigcls=cls,
  File "/Users/tkomiya/.pyenv/versions/3.8.2/lib/python3.8/inspect.py", line 2216, in _signature_from_callable
    raise TypeError('{!r} is not a callable object'.format(obj))
TypeError: 4 is not a callable object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tkomiya/work/sphinx/sphinx/ext/autodoc/__init__.py", line 395, in format_signature
    args = self.format_args(**kwargs)
  File "/Users/tkomiya/work/sphinx/sphinx/ext/autodoc/__init__.py", line 1052, in format_args
    if (inspect.is_builtin_class_method(unwrapped, '__new__') and
  File "/Users/tkomiya/work/sphinx/sphinx/util/inspect.py", line 392, in is_builtin_class_method
    classes = [c for c in inspect.getmro(obj) if attr_name in c.__dict__]
  File "/Users/tkomiya/.pyenv/versions/3.8.2/lib/python3.8/inspect.py", line 489, in getmro
    return cls.__mro__
AttributeError: 'int' object has no attribute '__mro__'
```

**Expected behavior**
Shows simple and readable error. (or suppressed?)

**Your project**
No

**Screenshots**
No

**Environment info**
- OS: Mac
- Python version: 3.8.2
- Sphinx version: 3.0.1
- Sphinx extensions: sphinx.ext.autodoc
- Extra tools: No

**Additional context**
No

**Comment by eric-wieser** [comment]
Isn't this correct behavior? Seems like the user _should_ get a warning if they try and document a non-callable object as a function.

**Comment by tk0miya** [comment]
Are you saying to show such complicated error is "correct" behavior, right? Can you understand what is happened from this warning? At least, it is difficult for me.

**Comment by eric-wieser** [comment]
Sorry, to be clear - I think `WARNING: error while formatting arguments for errno.EINTR` is something the user should see. I agree the traceback is a bit much.

Even `TypeError: 4 is not a callable object` seems like a useful thing to show.

**Comment by eric-wieser** [comment]
I would say correct behavior would be to show either:
```
WARNING: error while formatting arguments for errno.EINTR:
Traceback (most recent call last):
  File "/Users/tkomiya/work/sphinx/sphinx/ext/autodoc/__init__.py", line 1049, in format_args
    sig = inspect.signature(unwrapped)
  File "/Users/tkomiya/work/sphinx/sphinx/util/inspect.py", line 406, in signature
    signature = inspect.signature(subject)
  File "/Users/tkomiya/.pyenv/versions/3.8.2/lib/python3.8/inspect.py", line 3093, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped)
  File "/Users/tkomiya/.pyenv/versions/3.8.2/lib/python3.8/inspect.py", line 2842, in from_callable
    return _signature_from_callable(obj, sigcls=cls,
  File "/Users/tkomiya/.pyenv/versions/3.8.2/lib/python3.8/inspect.py", line 2216, in _signature_from_callable
    raise TypeError('{!r} is not a callable object'.format(obj))
TypeError: 4 is not a callable object
```
or
```
WARNING: error while formatting arguments for errno.EINTR:
Traceback (most recent call last):
  <truncated somehow, like you do elsewhere>
  File "/Users/tkomiya/.pyenv/versions/3.8.2/lib/python3.8/inspect.py", line 2216, in _signature_from_callable
    raise TypeError('{!r} is not a callable object'.format(obj))
TypeError: 4 is not a callable object
```

**Comment by eric-wieser** [comment]
So probably, `is_builtin_class_method(4, "nonsense")` should return `False`

**Comment by tk0miya** [comment]
I don't think both of stacktraces will not help users. I thought it helps Sphinx and extension developers to debug it on #7601. But I noticed it is not good for users.

In addition, it would be better to add a new error message for this case like "Failed to get function signature of errno.INTR: TypeError: 4 is not a callable object".

**Comment by tk0miya** [comment]
I noticed this warning does not report the location of the source file. It must be needed.

**Comment by eric-wieser** [comment]
> In addition, it would be better to add a new error message for this case like "Failed to get function signature of errno.INTR: TypeError: 4 is not a callable object".

I'd recommend you write a custom `logging.formatter` which looks at exc_info and only prints the last line - you already have that logic elsewhere.

**Comment by eric-wieser** [comment]
> I noticed this warning does not report the location of the source file. It must be needed.

Which source file should be reported here? The rst?

**Comment by tk0miya** [comment]
>I'd recommend you write a custom logging.formatter which looks at exc_info and only prints the last line - you already have that logic elsewhere.

Sorry, I can't understand what you're saying. What I said is adding a new warning message, not a formatter...

>Which source file should be reported here? The rst?

Yes. I guess users can't find the location of reST.

**Comment by eric-wieser** [comment]
I'm suggesting that instead of modifying the message passed to the `logger.warn` call, you modify the code that displays the message to trim down `exc_info`, if the user is not in verbose mode - exactly like you did in that PR you closed before.

**Comment by tk0miya** [comment]
It seems we're talking about different topics. My concern is a message itself. I feel "Failed to get function signature of errno.INTR" is more clear than "error while formatting arguments for errno.EINTR".

On the other hand, your concern (recommendation) is how to show stacktraces, right? If so, either is okay to me. My main concern is the users.

**Comment by eric-wieser** [comment]
Oh, sorry, now I see your point. Yes, there are multiple problems here, and we're talking about different ones:

1. The stack trace contains information that no one cares about (`AttributeError: 'int' object has no attribute '__mro__'`)
2. The stack trace is something that many users will not care about (but some do)
3. The first line of the message is not worded clearly

**Comment by tk0miya** [comment]
Agreed. Thank you for summarizing 👍
