### ISSUE TITLE
sphinx can not interpret hyphen as underscore or vice-versa

### ISSUE THREAD

**Issue by hanxiao** [sphinx-doc/sphinx#7648]
**Is your feature request related to a problem? Please describe.**

Argument is defined with hyphen in `argparse`, e.g. `--timeout-ready`. In Python, this argument is auto converted to `timeout_ready`. So the user often expects to find the result by searching either, with hyphen or with underscore. However, right now only the `timeout-ready` query gives the full result.

> Result on `timeout_ready`:
> https://docs.jina.ai/search.html?q=timeout_ready&check_keywords=yes&area=default#

> Result on `timeout-ready`:
> https://docs.jina.ai/search.html?q=timeout-ready&check_keywords=yes&area=default#

**Describe the solution you'd like**

I guess some kind of alias needs to be defined for hyphen <> underscore, but at where? Should it be implemented in argparse, or sphinx-argparse, or sphinx, or doc theme level? I'm not really sure

**Describe alternatives you've considered**

**Additional context**

- original post: https://github.com/jina-ai/jina/issues/395#issuecomment-625773716

**Comment by tk0miya** [comment]
I think hyphens and underscores are different things. As you said, you'd like to equate them in python's context. The conversion is meaningless if we write a document for command-line help. So I think it is not responsibility of Sphinx itself.

**Comment by hanxiao** [comment]
thanks for the response. 

To clarify my expected solution here: for an arg defined as `--timeout-ready` at argparse level, add
add an entry `timeout_ready` in `searchindex.js`, to make it searchable. Just like `timeout_readi` here (I guess it is there because of some lemmatization implemented?)

![image](https://user-images.githubusercontent.com/2041322/81494504-b90d3400-92a9-11ea-9099-a919ac49b8e0.png)

Questions:
- Is this the right place to add such alias entry to make underscore searchable?
- Who is responsible for adding such entry? sphinx-argparse extension?

**Comment by tk0miya** [comment]
>Is this the right place to add such alias entry to make underscore searchable?

Yes. But you don't need to care about searchindex. It is built from content automatically. So directives or other components should care the generated content only.

>Who is responsible for adding such entry? sphinx-argparse extension?

I think so. It is strongly related with it.

**Comment by eric-wieser** [comment]
I think the premise behind this issue is flawed. The actual issue lies entirely with `sphinx-argparse`, and is not about `-` and `_` at all, but about the `dest` argument being ignored:
```
parser = argparse.ArgumentParser()
parser.add_argument('with-hyphens', dest='with_underscores')
```
The docs generated from this parser do not contain the text `with_underscores` at all.

I think this issue can be closed.

**Comment by tk0miya** [comment]
I'm closing this now. Thank you for proposal.
