### ISSUE TITLE
autosummary toc escapes * in the signature

### ISSUE THREAD

**Issue by keewis** [sphinx-doc/sphinx#7662]
**Describe the bug**
When using `autosummary` to document a function / method that takes variable parameters (`*args`, `**kwargs`), the stars (`*`) are escaped with literal `\` characters in the html output. However, when documenting a class, this does not happen.

While glancing through `autodoc`'s `Documenter` classes, I noticed https://github.com/sphinx-doc/sphinx/blob/63457c700c803ea2a07c72901aca91e9a1a3fa0b/sphinx/ext/autodoc/__init__.py#L1062-L1065
and https://github.com/sphinx-doc/sphinx/blob/63457c700c803ea2a07c72901aca91e9a1a3fa0b/sphinx/ext/autodoc/__init__.py#L1469-L1472

but I'm not sure if that's really the reason and I couldn't figure out how to set `strip_signature_backslash` to `False` to verify this.

**To Reproduce**
Configure `autosummary` to document a function / method taking `*args` or `**kwargs` arguments.

**Expected behavior**
The signature should not print escape characters in the html output.

**Your project**
The project that hits it is [xarray](https://github.com/pydata/xarray) ([`conf.py`](https://github.com/pydata/xarray/blob/2542a63f6ebed1a464af7fc74b9f3bf302925803/doc/conf.py), [build log](https://readthedocs.org/projects/xray/builds/11039848/), [built documentation](https://xarray.pydata.org/en/latest/api.html)).

**Screenshots**
This shows that `dot` (which is a [function](https://github.com/pydata/xarray/blob/2542a63f6ebed1a464af7fc74b9f3bf302925803/xarray/core/computation.py#L1072)) has the escaped `*` whereas `set_options` (which is a [class](https://github.com/pydata/xarray/blob/2542a63f6ebed1a464af7fc74b9f3bf302925803/xarray/core/options.py#L78-L149)) is formatted correctly (there are also type-hint fragments, but that is a separate issue)

![autosummary](https://user-images.githubusercontent.com/14808389/81955116-ff47f780-9609-11ea-955f-1ceaa0c44f91.png)

**Environment info**
- OS: Linux (readthedocs)
- Python version: 3.8
- Sphinx version: 3.0.3
- Sphinx extensions: `sphinx.ext.autosummary`, `sphinx.ext.autodoc` and more but hopefully unrelated extensions (see the configuration linked above)

**Comment by keewis** [comment]
actually, it seems this happens because the project uses both `numpydoc` and `napoleon`.

**Comment by tk0miya** [comment]
This is as same as reported at #7439. I sent a fix to numpydoc project. But it has not been released yet. Please enable `strip_signature_backslash` as a workaround.

Thanks,
