### ISSUE TITLE
 AttributeError: module 'sphinx.domains.c'  has no attribute 'CStructObject

### ISSUE THREAD

**Issue by NHZlX** [sphinx-doc/sphinx#7664]
The config is:

![image](https://user-images.githubusercontent.com/5595332/81972529-50c9a400-9655-11ea-87ea-f75f20fef815.png)

The project is here: 
https://readthedocs.org/projects/paddle-inference/builds/11041548/

Help welcome.

**Comment by jakobandersen** [comment]
It looks like it's a too new version of Breathe compared to your Sphinx version. I'm not familiar with how Read the Docs builds work, but it looks like it uses a very old version of Sphinx.

**Comment by Chrismarsh** [comment]
For anyone else running into this, it's due to Breathe dropping support for Sphinx < 2.0 as detailed here:
https://github.com/svenevs/exhale#exhale-version-compatibility-with-python-sphinx-and-breathe

It's sufficient to specify ``breathe<4.13.0`` in your requirements.txt
