### ISSUE TITLE
Exception occurred after running the build command `sphinx-build -b html ./ _build`

### ISSUE THREAD

**Issue by b18050** [sphinx-doc/sphinx#7666]
I am pasting the log file as directed by bug report.

`# Sphinx version: 2.2.0
`# Python version: 3.6.6 (CPython)
`# Docutils version: 0.14 
`# Jinja2 version: 2.10
`# Last messages:
`#   done
`#   
`#   checking consistency...
#   
`#   done
`#   
`#   preparing documents...
`#   
`#   failed
`#   
`# Loaded extensions:
`#   sphinx.ext.mathjax
 (2.2.0) from C:\WPy-3662\python-3.6.6.amd64\lib\site-packages\sphinx\ext\mathjax.py
`#   sphinxcontrib.applehelp (1.0.2) from C:\WPy-3662\python-3.6.6.amd64\lib\site-packages\sphinxcontrib\applehelp\__init__.py
`#   sphinxcontrib.devhelp (1.0.2) from C:\WPy-3662\python-3.6.6.amd64\lib\site-packages\sphinxcontrib\devhelp\__init__.py
`#   sphinxcontrib.htmlhelp (1.0.3) from C:\WPy-3662\python-3.6.6.amd64\lib\site-packages\sphinxcontrib\htmlhelp\__init__.py
`#   sphinxcontrib.serializinghtml (1.1.4) from C:\WPy-3662\python-3.6.6.amd64\lib\site-packages\sphinxcontrib\serializinghtml\__init__.py
`#   sphinxcontrib.qthelp (1.0.3) from C:\WPy-3662\python-3.6.6.amd64\lib\site-packages\sphinxcontrib\qthelp\__init__.py
`#   alabaster (0.7.11) from C:\WPy-3662\python-3.6.6.amd64\lib\site-packages\alabaster\__init__.py
`#   sphinx.ext.todo (2.2.0) from C:\WPy-3662\python-3.6.6.amd64\lib\site-`packages\sphinx\ext\todo.py
`#   sphinx_tabs.tabs (unknown version) from C:\WPy-3662\python-3.6.6.amd64\lib\site-`packages\sphinx_tabs\tabs.py
`Traceback (most recent call last):
 ` File "C:\WPy-3662\python-3.6.6.amd64\lib\site-packages\sphinx\cmd\build.py", line 276, in `build_main
    `app.build(args.force_all, filenames)
 ` File "C:\WPy-3662\python-3.6.6.amd64\lib\site-packages\sphinx\application.py", line 346, in build
    `self.builder.build_update()
 ` File "C:\WPy-3662\python-3.6.6.amd64\lib\site-packages\sphinx\builders\__init__.py", line 299, in `build_update
  `  len(to_build))
 ` File "C:\WPy-3662\python-3.6.6.amd64\lib\site-packages\sphinx\builders\__init__.py", line 361, in `build
    self.write(docnames, list(updated_docnames), method)
  File "C:\WPy-3662\python-3.6.6.amd64\lib\site-packages\sphinx\builders\__init__.py", line 527, in write
    self.prepare_writing(docnames)
 ` File "C:\WPy-3662\python-3.6.6.amd64\lib\site-packages\sphinx\builders\html.py", line 495, in `prepare_writing
    'release': return_codes_re.sub('', self.config.release),
`TypeError: expected string or bytes-like object`

**Comment by AA-Turner** [comment]
`release` in `conf.py` must be set to a string.

A
