### ISSUE TITLE
loweralpha has impact on nested lists

### ISSUE THREAD

**Issue by xi** [sphinx-doc/sphinx#7693]
**Describe the bug**

When I use a non-default list style like this:

```
a) Foo
b) Bar
   - asd
   - asd
```

I expect the outer list to use `list-style: lower-alpha` and the inner list to use `list-style: disc`. Instead, both lists use the former.

**Comment by tk0miya** [comment]
I guess you need to insert a blank line before the inner list:

```
a) Foo
b) Bar

   - asd
   - asd
```

How about this? I got following result from it.
<img width="103" alt="スクリーンショット 2020-05-20 1 49 00" src="https://user-images.githubusercontent.com/748828/82354671-15a3e800-9a3c-11ea-8289-362b249f93d8.png">

**Comment by xi** [comment]
This is actually a bug in the theme: https://github.com/readthedocs/sphinx_rtd_theme/pull/929
