### ISSUE TITLE
Links to internal pages of PDF files via ?#page=N not handled by linkcheck builder

### ISSUE THREAD

**Issue by markcmiller86** [sphinx-doc/sphinx#7694]
**Describe the bug**
I have docs with several links of the form...

```
https://wci.llnl.gov/content/assets/docs/simulation/computer-codes/silo/LLNL-SM-654357.pdf?#page=226
```

Which is a [valid link](https://wci.llnl.gov/content/assets/docs/simulation/computer-codes/silo/LLNL-SM-654357.pdf?#page=226)

However, the linkcheck builder reports it as broken...

```
https://wci.llnl.gov/content/assets/docs/simulation/computer-codes/silo/LLNL-SM-654357.pdf?#page=226: Anchor 'page=226' not found
```

**To Reproduce**
```
1. git clone https://github.com/visit-dav/visit.git
1. cd src/doc
1. sphinx-build -b linkcheck . _links -a 
```

**Environment info**
- OS: OSX 10.13.6
- Python version: 2.7.16
- Sphinx version: 1.5.3
- Sphinx extensions:  sphinx.ext.mathjax
- Extra tools:

**Comment by tk0miya** [comment]
It seems 3.0.3 works fine. Please update your Sphinx.
Thanks,
