### ISSUE TITLE
numfig_secnum_depth > 1 leads to wrong figure links in the pdf

### ISSUE THREAD

**Issue by asfg84** [sphinx-doc/sphinx#7715]
When using numfig = True and numfig_secnum_depth greater than 2, the references (links) to the figures in the pdf are wrong. 

The referencing for numfig_secnum_depth = (2) is the following:
A figure is the first figure in its subsection, e.g. 3.7.1. When clicking on the link, it jumps to the first figure in chapter 3 which is first in its subsection, e.g. 3.1.1
If a figure is the second in its subsection, e.g. 3.7.2 it jumps to the first figure in chapter 3 which is second in its subsection, e.g. 3.3.2
If a figure is the third in its subsection, e.g. 3.7.3 it jumps to the first figure in chapter 3 which is third in its subsection, e.g. 3.5.3
etc... 

Found in sphinx version 1.8.5 (I could not find any hint in the Changelog that this issue was fixed in later versions)

**Comment by Jellby** [comment]
Man, I just discovered it and was about to report it. Still alive and kicking in 3.1.0.

**Comment by Jellby** [comment]
It seems the problem is that `@addtoreset` should be issued *after* loading `hyperref`, and right now it is done before, in the `sphinx.sty` file. Wrapping the corresponding code in `AtBeginDocument{}` appears to fix it.
