### ISSUE TITLE
enum support for C++ domain

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#772]
There should be some dedicated support for Enum types.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/772
- Originally reported by: Georg Brandl
- Originally created at: 2011-09-23T11:28:34.126

**Comment by shimizukawa** [comment]
_From [gregcouch](https://bitbucket.org/gregcouch) on 2013-04-25 22:18:26+00:00_

When/if this is done, will it be for both the C and C++ domains?

**Comment by shimizukawa** [comment]
_From [Rapptz](https://bitbucket.org/Rapptz) on 2014-08-30 23:30:00+00:00_

Is this getting any progress? It was created almost 3 years ago and this feature still doesn't exist.

**Comment by shimizukawa** [comment]
_From Jakob Lykke Andersen on 2014-09-14 15:08:29+00:00_

I have tried implementing something (https://bitbucket.org/jakobla/sphinx). It supports both unscoped enums and C++11 scoped enums, both with the possibility to specify the underlying type. Enumerators for unscoped enums are injected into the parent namespace in addition to the enum scope.
Examples:

```
#!rst
.. cpp:enum:: UnscopedEnum : char

   .. cpp:enumerator:: E1

   .. cpp:enumerator:: E2 = 42

.. cpp:enum:: struct ScopedEnum

.. cpp:enumerator:: ScopedEnum::A = 60

   An enumerator declared independently of its enum.

```

(all of this is in the C++ domain, and it's currently completely independent of the C domain)

**Comment by shimizukawa** [comment]
_From [christophercrouzet](https://bitbucket.org/christophercrouzet) on 2014-12-07 02:19:52+00:00_

I'm definitely looking forward to this feature too—any ETA?

**Comment by poulson** [comment]
As far as I can tell, the `:cpp:enum::` plus `:cpp:enumerator::` support is broken with Sphinx 1.3.1 on both Ubuntu and OS X. I see internal errors of the form::

```
reading sources... [ 18%] blas_like/level3/Gemm                                 
Exception occurred:
  File "/Users/poulson/anaconda/lib/python2.7/site-packages/Sphinx-1.3.1-py2.7.egg/sphinx/domains/cpp.py", line 656, in __init__
    assert len(names) > 0
AssertionError
The full traceback has been saved in /var/folders/54/044qly2s21dcnhfh1xk_mtgm0000gn/T/sphinx-err-HgtOqO.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [web] Error 1
```

The offending code appears to be the enum located at https://raw.githubusercontent.com/elemental/elemental-web/master/source/doc-dev/blas_like/level3/Gemm.rst

The log file can be found here: https://gist.github.com/poulson/e5b5b7d39e3770a0a1a7

**Comment by shimizukawa** [comment]
Hi @poulson, thanks for the reporting. However, this ticket is already closed. Please create new issue ticket. Thanks.
