### ISSUE TITLE
TypeVar mentioned in type annotation is not found, causing an unexpected warning on Sphinx 3.x

### ISSUE THREAD

**Issue by pquentin** [sphinx-doc/sphinx#7722]
**Describe the bug**

TypeVar mentioned in type annotation is not found, causing an unexpected warning on Sphinx 3.x

**To Reproduce**

Write conf.py as follows:

```python
import os
import sys

sys.path.insert(0, os.path.abspath('.'))
extensions = ['sphinx.ext.autodoc']
```

Write index.rst as follows:

```rst
Welcome to repro's documentation!
=================================

.. autoclass:: repro.SendChannel
   :members:
```

Write repro.py as follows:

```python
from typing import TypeVar

SendType = TypeVar("SendType")


class SendChannel():
    async def send(self, value: SendType):
        """send"""
        pass
```

Run the following command:

```
sphinx-build -nW -b html . _build/html
```

**Expected behavior**

Like with Sphinx 2.x, the `SendType` type hint is ignored.

**Actual behavior**

The build fails, since we treat warnings as errors:

```Warning, treated as error:
docstring of repro.SendChannel.send::py:class reference target not found: SendType
```

**Environment info**
- OS: macOS 10.15 and Linux
- Python version: 3.8.2
- Sphinx version: 3.1.0+ (302c23fb5c172826499e8b3fb6d9eccd3c32d307)
- Sphinx extensions: sphinx.ext.autodoc

**Additional context**

- https://github.com/python-trio/trio/pull/1465

**Comment by pquentin** [comment]
I just ran git bisect, and realized that this issue is a duplicate of https://github.com/sphinx-doc/sphinx/issues/7493. Closing

**Comment by tk0miya** [comment]
I think this is similar to #7493, but not the same problem.
The warning was caused from that the type annotation `SendType` is not documented. So you need to make a document for it by `.. autoclass:: repro.SendType`. But `autoclass` for TypeVar will generate a long text document unexpectedly. It comes from a docstring of TypeVar class. In addition, autodoc generates a broken type annotation reference for TypeVars. In this case, the absolute pathname of the annotation should be `repro.SendType`. But it refers `SendType` instead. So it will be never resolved.

**Comment by tk0miya** [comment]
I noticed #7930 also fixed this case. It helps to resolve the location of `SendType`.

I confirmed the fix with adding a comment to `SendType` and using the HEAD of 3.x branch:
```
from typing import TypeVar

#: SendType
SendType = TypeVar("SendType")


class SendChannel():
    async def send(self, value: SendType):
        """send"""
        pass
```
