### ISSUE TITLE
Compile Error: TeX capacity exceeded, sorry [parameter stack size=10000]. When I cite with a wikipedia url on Latex on Overleaf.

### ISSUE THREAD

**Issue by shizhe1212** [sphinx-doc/sphinx#7724]
Hi, I am using macOS High Sierra 10.13.6 and I am doing a project report on Latex on overleaf.com. I have the errors on Latex: "LaTeX Error: Option clash for package hyperref." and "TeX capacity exceeded, sorry [parameter stack size=10000]" popping up when I cite a wikipedia page, and the error doesn't occur when I cite other webpages. And with this error, I cannot compile the pdf document with Latex. I need to submit mu project report in 4 days, can someone help me with it please.

**Here are the codes in my project:**
\documentclass[12pt]{article}
\usepackage[lmargin=2.5cm,rmargin=2.5cm,bottom=2.5cm,textheight=23cm,margin=1in]{geometry}
\usepackage{graphicx}
\usepackage{subfig}
\usepackage{lipsum}
\usepackage{setspace}
\usepackage{verbatim}
\usepackage[colorlinks=true, allcolors=blue]{hyperref}
\usepackage{cite}
\usepackage{url}

\usepackage{fancyhdr}
\pagestyle{fancy}
\fancyhead[L]{---}

\input{PomonaLgcsFormatting}

\title{ ---}
\author{---\\
---}
\date{Spring 2020} 

\begin{document}

\maketitle
\section{Introduction}
Contents...  \cite{wiki_GWAS}

\bibliographystyle{plain}
\bibliography{References}

\end{document}

The error disappears when I comment out the '\cite{wiki_GWAS}' part and occurs when I use this code.

**The following is the wikipedia reference I put in the .bib file:**
@misc{wiki_GWAS,
    author = {Wikipedia contributors},
    title = "Genome-wide association study--- {Wikipedia}{,} The Free Encyclopedia",
    url = {https://en.wikipedia.org/wiki/Genome-wide_association_study}
  }
  
**Here are the screenshots of the errors if this helps.**
<img width="604" alt="Screenshot 1" src="https://user-images.githubusercontent.com/47859618/82859621-d567cc80-9f49-11ea-8307-915741c8c1e9.png">
<img width="612" alt="Screenshot 2" src="https://user-images.githubusercontent.com/47859618/82859691-034d1100-9f4a-11ea-9fa2-8483633c53e0.png">

**Comment by tk0miya** [comment]
Is this related to Sphinx?

**Comment by tk0miya** [comment]
The overleaf team gives me a message for you. Please check this and contact to them.

>Our support team are best placed to answer this and can take a closer look at the issue. Please get it touch with them through http://overleaf.com/contact or via support@overleaf.com and give them the URL for the project so that they can have a look?
