### ISSUE TITLE
Add a configuration to sphinx.ext.autosectionlabel to prefix subsection with section label

### ISSUE THREAD

**Issue by fabiencelier** [sphinx-doc/sphinx#7728]
**Is your feature request related to a problem? Please describe.**
In a structured document, such as a changelog, some subsections can have the same name in different sections. This triggers some warnings.

For instance a changelog with Added/Removed sub sections for each version:
<pre>
version 2.0.0
    Added
       - new feature 1
       - new feature 2
    Removed
       - old feature
Version 1.0.0
    Added
       - new feature 3
       - new feature 4
</pre>

All the Added subsection have the same "changelog:added" label.

**Describe the solution you'd like**
A configuration/option to prefix a subsection label with the label of the section, similar to autosectionlabel_prefix_document but with parent section.

**Describe alternatives you've considered**
- Ignoring the warning but labels are still broken
- Adding another label to the section but that does not remove the duplicated ones.

**Comment by tk0miya** [comment]
Do you want to refer the "Added" section? If not, how about using `autosectionlabel_maxdepth`? I think ```:ref:`Version 1.0.0/Added/new feature3` ``` is too much complicated.

>Ignoring the warning but labels are still broken

You can do it with `suppress_warnings = ['autosectionlabel.*']`.

**Comment by stsewd** [comment]
This is kind of related to https://github.com/sphinx-doc/sphinx/issues/7697

**Comment by fabiencelier** [comment]
This is the same issue as  #7697, I just give another idea to resolve it.
I will close it as it is a duplicate
