### ISSUE TITLE
AttributeError: 'Sphinx' object has no attribute 'add_stylesheet'

### ISSUE THREAD

**Issue by nilswagner** [sphinx-doc/sphinx#7747]
I am using

# Sphinx version: 4.0.0+/88a3548a8
# Python version: 3.8.2 (CPython)
# Docutils version: 0.17b.dev release
# Jinja2 version: 3.0.0a1
 
make html in pytest/doc/en fails with

git/pygments-pytest/pygments_pytest.py", line 165, in setup
    app.add_stylesheet('pygments_pytest.css')
AttributeError: 'Sphinx' object has no attribute 'add_stylesheet'

**Comment by tk0miya** [comment]
Yes, the API was deprecated at 1.8.0. Please use `app.add_css_file()` instead.
