### ISSUE TITLE
Format the attribute content

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#775]
I have an attribute in my class with a lot of data (it's a python dictionary), and the autodoc just print the content of the dictionary as a string; to have something better I've tried with something like this in my config.py

```
#!python

import pprint

def setup(app):
    app.connect('autodoc-process-signature', process_signature)

def process_signature(app, what, name, obj, options, signature, return_annotation):
    if what == 'attribute' and obj.__class__ is dict:
        return ('', pprint.pformat(obj, 1))
    return ''
```

But the result is something really ugly (see attachment).

There is a way to have a pretty output for attributes?

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/775
- Originally reported by: Alessandro Pagnin
- Originally created at: 2011-09-24T19:22:21.504

**Comment by shimizukawa** [comment]
There is a `:annotation:` option for `autodata` and `autoattribute:`, however there is no way to provide the option when user using `automodule` and/or `autoclass` directive.

[775.zip](https://github.com/sphinx-doc/sphinx/files/658692/775.zip)

**Comment by usaturn** [comment]
It is not reproduced in the current version.
I will close it.

# Environment info
- OS: Windows 10
- Python version: 3.5.2
- Sphinx version:
- TeX : TeX Live 2016

**Comment by tk0miya** [comment]
In #8424, I added `:no-value:` option for such purpose. Closing.
