### ISSUE TITLE
ImportError on building documents

### ISSUE THREAD

**Issue by ineshbose** [sphinx-doc/sphinx#7766]
**Describe the bug**
When using Makefile to build some documents, I received `ImportError: cannot import name 'main'`.
This may have something to do with [recommonmark](https://github.com/readthedocs/recommonmark) to build `.md` files, however, the exact error message suggests `sphinx`:
```
Traceback (most recent call last):
  File "/usr/bin/sphinx-build", line 14, in <module>
    from sphinx import main
ImportError: cannot import name 'main'
Makefile:55: recipe for target 'html' failed
make: *** [html] Error 1
```

I am using Ubuntu WSL on Windows 10.

**To Reproduce**
```
$ git clone https://github.com/readthedocs/recommonmark/
$ cd recommonmark/docs
$ pip install recommonmark
$ make html
sphinx-build -b html -d _build/doctrees   . _build/html
Traceback (most recent call last):
  File "/usr/bin/sphinx-build", line 14, in <module>
    from sphinx import main
ImportError: cannot import name 'main'
Makefile:55: recipe for target 'html' failed
make: *** [html] Error 1
```
This further breaks other commands as well.
```
$ sphinx-build --version
Traceback (most recent call last):
  File "/usr/bin/sphinx-build", line 14, in <module>
    from sphinx import main
ImportError: cannot import name 'main'
```

**Environment info**
- OS: [e.g. Unix/Linux/Mac/Win/other with version]
- Python version: 3.6.2
- Sphinx version: 2.2.0
- Sphinx extensions:  sphinx.ext.autodoc, recommonmark
- Extra tools:

**Comment by tk0miya** [comment]
It seems you failed to install Sphinx correctly. The error says `sphinx-build` command could not load its main function. Please reinstall Sphinx to your environment again.

**Comment by ineshbose** [comment]
I did reinstall and tried this out on two machines. I was able to `sphinx-quickstart` on installing, however, after installing **recommonmark** through PyPI, I was unable to use `sphinx-build`.

**Comment by tk0miya** [comment]
I don't understand what is happened on your system. I don't think installation recommonmark might not related to the error. But I don't have any idea to resolve your trouble. Only I can say is your system failed to load the sphinx module at all.

**Comment by retrodeluxe** [comment]
Same problem here

**Comment by gitPrinz** [comment]
Same problem here on Ubuntu 18.04  WSL on Windows 10

```
Traceback (most recent call last):
  File "/usr/bin/sphinx-build", line 14, in <module>
    from sphinx import main
ImportError: cannot import name 'main'
```

Searching for the correct way to install it.
