### ISSUE TITLE
Getting an "xml not well-formed" on some doxygen input xml, when running Sphinx with breathe extension 

### ISSUE THREAD

**Issue by breathe67** [sphinx-doc/sphinx#7767]
**Describe the bug**
Getting an "xml not well-formed"  error while processing some xml output from doxygen in the tablet_8cpp.xml file attached:
[tablet_8cpp.zip](https://github.com/sphinx-doc/sphinx/files/4713818/tablet_8cpp.zip)

Note: VS code's XML tools show no XML error when viewing the tablet_8cpp.xml file, *although I have not otherwise verified this.* 

**the full traceback:**
[sphinx-err-tmhw5ray.log](https://github.com/sphinx-doc/sphinx/files/4713863/sphinx-err-tmhw5ray.log)

**The error message:**

Exception occurred:
1>    File "c:\program files\python38\lib\site-packages\breathe\parser\__init__.py", line 93, in parse
1>      raise ParserError(e, filename)
1>  breathe.parser.ParserError: file C:/Users/breat/sketchcraft/docs/doxygen/xml\tablet_8cpp.xml: not well-formed (invalid token): line 731, column 61
1>  The full traceback has been saved in C:\Users\breat\AppData\Local\Temp\sphinx-err-tmhw5ray.log, if you want to report the issue to the developers.
1>  Please also report this if it was a user error, so that a better error message can be provided next time.
1>  A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!

**To Reproduce**
No command line, made using cmake-generated visual studio project, but should be irrelevant.

**Expected behavior**
Using Sphinx to convert my C++ documentation from doxygen xml to its 'read the docs' theme,

**Environment info**
Windows 10
- Python 3.8
- Sphinx version: installed using "pip install -U sphinx" on June 1, 2020
- Sphinx extensions:  breathe, installed using " pip install breathe" on June 1, 2020

**Comment by jakobandersen** [comment]
As the problem is with the Doxygen XML there is nothing Sphinx can do. Please open an issue for Breathe (or perhaps Doxygen) instead. (As the traceback mentions, the problem is in XML line 731 which encodes the original source line 55. My editor shows, for example, ``didn\92t`` in that line.)
