### ISSUE TITLE
No translation for :alt: of images

### ISSUE THREAD

**Issue by kujiu** [sphinx-doc/sphinx#7784]
**Describe the bug**
Text of :alt: parameter of an image is not considered.

**To Reproduce**

Create a project, add an image directive with :alt: text and do `make gettext`.

**Expected behavior**

The text of :alt: property will be in the .pot file.

**Environment info**
- OS: Linux OpenSuSE 15.2
- Python version: 3.6
- Sphinx version: 3.x and master branches
- Sphinx extensions:  No extension
- Extra tools: None

**Comment by tk0miya** [comment]
Absolutely. +1!

**Comment by tk0miya** [comment]
At present, `gettext_additional_targets` is used to translate alt texts:
https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-gettext_additional_targets

But I just thought alt text should be translatable by default. So I post #7979.

**Comment by shimizukawa** [comment]
+1
