### ISSUE TITLE
Add html and charset blocks

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#779]
In basic/layout.html, +/- everything is a block, but there is no html or charset declaration blocks. Could be really nice to use html5 :-)

{&#37;\- block html -&#37;}
<html xmlns="http://www.w3.org/1999/xhtml">
{&#37;\- endblock &#37;}

{&#37;\- block charset -&#37;}
 <meta http-equiv="Content-Type" content="text/html; charset={{ encoding }}" />
{&#37;\- endblock &#37;}

Thx.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/779
- Originally reported by: Anonymous
- Originally created at: 2011-10-04T13:39:10.553

**Comment by tk0miya** [comment]
In #3968, html5 generates charset meta tag by default. I think charset block is not needed by that change.
Please notify me if you want it after #3968.

Thanks,
