### ISSUE TITLE
Sphinx 3.1.0 build fails with unexpected indentation on @classproperty with no docstring

### ISSUE THREAD

**Issue by dvorapa** [sphinx-doc/sphinx#7805]
**Describe the bug**
Since update to Sphinx 3.1.0, [Pywikibot](https://github.com/wikimedia/pywikibot) build fails with "unexpected indentation" on a @classproperty with no docstring. The error can be found here: https://integration.wikimedia.org/ci/job/pywikibot-core-tox-doc-docker/10136/console

**To Reproduce**
```
$ git clone https://github.com/wikimedia/pywikibot
$ cd pywikibot
$ pip install .[security]
$ pip install -r requirements.txt
$ pip install -r docs/requirements-py3.txt
$ pip install rstcheck >= 3.3.1
$ sphinx-build -M html ./docs ./docs/_build
$ rstcheck --recursive --report warning --ignore-directives automodule,autoclass,autofunction .
```

**Expected behavior**
rstcheck does not report any error and build under Sphinx 3.0.4 worked. There should be no difference or clearly defined, what's wrong with our code. I read changelog for 3.1.0 thoroughly, but could not find any indication, what is wrong. Also the error message is not much informative.

You can see the problematic @classproperty here: https://phabricator.wikimedia.org/diffusion/PWBC/browse/master/pywikibot/families/wikisource_family.py$71

**Your project**
Link to your sphinx project, or attach zipped small project sample.

https://github.com/wikimedia/pywikibot

**Environment info**
- OS: Linux Debian Stretch
- Python version: 3.5
- Sphinx version: 3.1.0
- Sphinx extensions:  https://phabricator.wikimedia.org/diffusion/PWBC/browse/master/docs/conf.py$40
- Extra tools: rstcheck, epytext, napoleon

**Additional context**
Console output: https://integration.wikimedia.org/ci/job/pywikibot-core-tox-doc-docker/10136/console
Problematic @classproperty: https://phabricator.wikimedia.org/diffusion/PWBC/browse/master/pywikibot/families/wikisource_family.py$71

**Comment by tk0miya** [comment]
I confired the error:
```
FROM python:3.7-slim

RUN apt update; apt install -y git make build-essential vim
RUN git clone https://github.com/wikimedia/pywikibot
WORKDIR /pywikibot
RUN pip3 install -e .
RUN pip3 install -r requirements.txt
RUN pip3 install -U sphinx
RUN pip3 install -U sphinx_epytext
WORKDIR /pywikibot/docs
RUN make html
```

And it seems Sphinx internally generates a following reST source for `Family.code_aliases`:
```
   .. py:attribute:: Family.code_aliases
      :module: pywikibot.families.wikisource_family

      dict() -> new empty dictionary
      dict(mapping) -> new dictionary initialized from a mapping object's
          (key, value) pairs
      dict(iterable) -> new dictionary initialized as if via:
          d = {}
          for k, v in iterable:
              d[k] = v
      dict(**kwargs) -> new dictionary initialized with the name=value pairs
          in the keyword argument list.  For example:  dict(one=1, two=2)
```
I don't know why it returns dict's docstring. But this is why Sphinx causes "unexpected indentation" error. I'll continue to investigate this.

**Comment by tk0miya** [comment]
Note: This would be a side effect of #7557.
