### ISSUE TITLE
No module named error prevent sphinx to document code

### ISSUE THREAD

**Issue by Nighthyst** [sphinx-doc/sphinx#7826]
**Describe the bug**
Hello,

I am currently working on a project where I try to use sphinx to generate the documentation however I am facing multiple "No module named [MODULE NAME]" with [MODULE NAME] being one of the module of my project. Because of this error some modules are not documented by Sphinx. When trying to run those modules directly (with "python [MODULE NAME].py") everything is  ok. Here is the project's tree : 

![image](https://user-images.githubusercontent.com/38282930/84535066-587b7780-aceb-11ea-85c3-8775d7f31125.png)

**To Reproduce**
For you to be able to recreate the issue I created a repository called "sphinx_test" that you can find here :
https://github.com/Nighthyst/sphinx_test

Once you downloaded the repository, you just have to go inside the docs folder and run the command "make html". Then I have the following output in the terminal :  
![image](https://user-images.githubusercontent.com/38282930/84532017-cb81ef80-ace5-11ea-8073-2eeb5d9ae7eb.png)

As you can see problems occured for "autre" and "example" modules. So the documentation looks like this : 

![image](https://user-images.githubusercontent.com/38282930/84532166-0dab3100-ace6-11ea-81c0-8945271afbb4.png)

Everything is empty for "example" and "autre". To reproduce the bug, open a terminal and run the following commands : 

```
$ git clone https://github.com/Nighthyst/sphinx_test.git
$ cd sphinx_test
$ cd docs
$ make html
$ # open docs/build/html/index.html and see the documentation
```

**Expected behavior**
No warning for "autre" and "example" modules. Documentation for them too.

**Your project**
https://github.com/Nighthyst/sphinx_test

**Environment info**
- OS: Windows 10 Professional 
- Python version: 3.7.6
- Sphinx version: 3.1.0
- Sphinx extensions:  sphinx.ext.autodoc
- Extra tools: Firefox\

**Comment by tk0miya** [comment]
It seems `sphinx_test.autre` and `sphinx_test.example` are not able to import. Is this correct python module?
```
root@9476b9ac0e91:/docs# git clone https://github.com/Nighthyst/sphinx_test
Cloning into 'sphinx_test'...
remote: Enumerating objects: 69, done.
remote: Counting objects: 100% (69/69), done.
remote: Compressing objects: 100% (52/52), done.
remote: Total 69 (delta 18), reused 64 (delta 16), pack-reused 0
Unpacking objects: 100% (69/69), done.
root@9476b9ac0e91:/docs# ls sphinx_test/
__init__.py  __pycache__  autre.py  bateau.py  docs  example.py  machin
root@9476b9ac0e91:/docs# python3
Python 3.6.9 (default, Nov  7 2019, 10:44:02)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sphinx_test
>>> import sphinx_test.autre
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/docs/sphinx_test/autre.py", line 5, in <module>
    from example import mafonction
ModuleNotFoundError: No module named 'example'
>>> import sphinx_test.example
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/docs/sphinx_test/example.py", line 6, in <module>
    from machin.functions import func1
ModuleNotFoundError: No module named 'machin'
>>>
```

I guess `sphinx_test` is not a python package. They are available to import without `sphinx_test` package when I change the directory.
```
root@9476b9ac0e91:/docs# cd sphinx_test/
root@9476b9ac0e91:/docs/sphinx_test# python3
Python 3.6.9 (default, Nov  7 2019, 10:44:02)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import autre
>>> import example
>>>
```

Please check your module again. This is not a problem of Sphinx.

**Comment by Nighthyst** [comment]
If you run example.py or autre.py, you can see that Python has no issue to import them since the results of the instructions below the \_\_name\_\_=="\_\_main\_\_" section are given without any error. A python package is just a directory with a  \_\_init\_\_.py file as stated in the official documentation of python : https://docs.python.org/3/tutorial/modules.html

The presence of all compiled version of the modules in the \_\_pycache\_\_ folders are another indicator that Python treats them as modules inside valid packages as you can see : 
![image](https://user-images.githubusercontent.com/38282930/84564540-bdbe7f80-ad62-11ea-8c9e-94f959bf56ad.png)
![image](https://user-images.githubusercontent.com/38282930/84564554-cfa02280-ad62-11ea-90fe-ebbd99f5101f.png)

So I don't think the issue is related to modules not being true modules or packages not being true packages. However I noticed something that may help you figure out what is wrong. If in example.py instead of 

`
from machin.functions import func1
`

you write : 

`
from sphinx_test.machin.functions import func1
`
 
and similarily in autre.py for the import then everything works for sphinx : 

![image](https://user-images.githubusercontent.com/38282930/84564680-be0b4a80-ad63-11ea-95fe-c37def7cd5ae.png)

![image](https://user-images.githubusercontent.com/38282930/84564676-b055c500-ad63-11ea-9463-12af8205bf26.png)

But Python is no longer able to run example.py or autre.py : 

![image](https://user-images.githubusercontent.com/38282930/84564696-daa78280-ad63-11ea-86bb-bab46df07ea2.png)

So this syntax including the name of the "root" package is not correct for Python but Sphinx seems to see no issue with it. The problems is that it is not always working (especially on larger projects)

**Comment by tk0miya** [comment]
I think you need to learn the structure of python script. If you choose `sphinx_test` for the base package of your program, you should not execute `python example.py` in the package directory directly. And I guess `sphinx_test` package is not needed for your case.

Anyway, this is not a bug of Sphinx. so please ask to your local python community.Thanks,

**Comment by Nighthyst** [comment]
I am sorry but when I tried to reproduce your test above sphinx_test folder I have no issue : 

![image](https://user-images.githubusercontent.com/38282930/84565915-172bac00-ad6d-11ea-8e87-d8aa4750fa64.png)


I can import everything without any error.

**Comment by Nighthyst** [comment]
Thank you for your replies, I understand the mistake now.
`
from sphinx_test.machin.functions import func1


is the right syntax for both Python and Sphinx. To run example.py  as script I must be above sphinx_test folder and run

`
python -m sphinx_test.example
`

Sorry for the incovenience.
