### ISSUE TITLE
List of Listings has a broken format

### ISSUE THREAD

**Issue by dalwar23** [sphinx-doc/sphinx#7828]
**Latex PDF creation with XELATEX has broken TOC format**
`\lstlistoflistings` creates a broken format of TOC unlike list of figures or list of tables.

**To Reproduce**

1. Create a sphinx documentation with quickstart
2. add a "latex_elements"  **preamble** to use "listings" package
```
\usepackage{listings}
```
3. add a few listings in a .rst file like below - and add it in `toctree` of `index.rst`
```
.. code-block:: shell
   :caption: Make PDF with sphinx

   cd docs/
   make latexpdf
 ```
4. add the following in another .rst file and add the file in "index.rst" toctree
```
.. raw:: latex

   \begingroup
   \lstlistoflistings
   \clearpage

.. raw:: latex

   \endgroup
```

**Expected behavior**
The expected behavior would be to produce a list of "Listings" with a similar format as "List of Tables" or
"List of Figures"

**Screenshots**
![image](https://user-images.githubusercontent.com/5631766/84568529-4b5c9800-ad80-11ea-84e0-50975865945c.png)

**Environment info**
- OS: Ubuntu 18.04, Ubuntu 20.04
- Python version: 3.6.9, 3.7.4, 3.8.2
- Sphinx version: 3.0.1, 3.0.4
- Extra tools: xelatex as latex engine

**Comment by tk0miya** [comment]
I don't know this is a bug of Sphinx because Sphinx doesn't use `listings` package to render code-blocks. But it would be nice if we can use `\lstlistoflistings` macro if possible.

**Comment by jfbu** [comment]
Here is the relevant comment in sphinx LaTeX style file

https://github.com/sphinx-doc/sphinx/blob/8f184e07bbc47228e18fa63e6746bc894816fd88/sphinx/texinputs/sphinx.sty#L972-L980

Can you try (without using `\usepackage{listings}`)  adding the LaTeX command `\listof{literalblock}{List of code-blocks}`  via raw latex directive as alternative to `\lstlistoflistings` ?

(as per the table of contents, this needs at least 2 pdflatex of xelatex runs on Sphinx-produces latex file, it is automatized by `make latexpdf` or, after moving to latex build repertory, by `make all-pdf` )

**Comment by dalwar23** [comment]
`listof{literalblock}{List of code-blocks}` works fine. 
thanks 👍 for the help.
🥳
