### ISSUE TITLE
Display property return typehints

### ISSUE THREAD

**Issue by alxroyer** [sphinx-doc/sphinx#7837]
**Problem:**
Unless I missed some configuration, property return typehints are not displayed in the output documentation with *sphinx.ext.autodoc*.

**Suggestion:**
As #7068 states, it is convenient to have properties being displayed the same as attributes.
It would be nice if the property return typehints were used as the type of the *pseudo attributes*.

**Alternatives:**
#7385 tells about the `:type:` directive that we could use in the property docstrings but:
- this is redundant information with the return typehint,
- it does not display the same as attributes.

**Example:**
In the screenshot below:
- `time` is an instance attribute with typehint: `# type: TimeStats`,
- `actions` is a property with return typehint: `# type: (...) -> ExecTotalStats`,
- `steps` is a property with return typehint: `# type: (...) -> ExecTotalStats`, plus a `:type: ExecTotalStats` in its docstring.
---
![2020-06-15 004735](https://user-images.githubusercontent.com/41943581/84606002-3415cb80-aea2-11ea-9235-20fcb63b06ea.png)
---
It would be nice if we had property lines ending with "*: ExecTotalStats*".
Adding a `:type: ExecTotalStats` directive in the `steps` property docstring does not display the information the same way as the `time` attribute.

**Configuration:**
- *sphinx-build* version 3.0.4
- use of the *sphinx.ext.autodoc* extension (*sphix.ext.napoleon* seems to behave the same for that concern)

**Comment by tk0miya** [comment]
Thank you for reporting. But same as #7383. So I'm closing this now as duplicated.
