### ISSUE TITLE
deactivate ext based on builder

### ISSUE THREAD

**Issue by Cielquan** [sphinx-doc/sphinx#7847]
**Is your feature request related to a problem? Please describe.**
I use the viewcode extension for my html builds. But for my confluence builds (made with `sphinxcontrib-confluencebuilder`) I don't want this extension active.

**Describe the solution you'd like**
I think it would only be doable within the `setup()` function in the `conf.py` file. So I want a way to deactivate extensions or activate them from there.

When `self.buildername = buildername` is added to the beginning of `application.Sphinx.__init__` one could get the builder's name inside the `setup()` via `app.buildername`. Then one could conditionally remove ext from the list like so:
```python
def setup(app):
    if app.buildername == "confluence":
        app.config.extensions.remove("sphinx.ext.viewcode")
```

Problem:
And if I understand the code correctly the extensions are initialized before the `setup()` is run. So could the setup part be put before the extension init?

Workaround could be to do it the other way around and instead of removing an extension call `app.setup_extension` with the extension to initialize manually in the user `conf.py`? But I think maybe the setup call needs to be placed before the `preload_builder` call?

**Describe alternatives you've considered**
One way would be to write multiple `conf.py` and put them in directories to choose them with `-c`.

**Comment by tk0miya** [comment]
How about using `-t` option for `sphinx-build` instead? For example, you give `-t noviewcode` option, you can control the list of extensions like this:
```
# in conf.py
if tags.has("noviewcode"):
    extensions.remove("sphinx.ext.viewcode")
```

**Comment by Cielquan** [comment]
Found the tags in the docs too after reading your reply. I did not read the opening in the config section. Seems like I should have.

Thanks. That's working perfectly!

**Comment by Cielquan** [comment]
pylint, mypy, etc complain that they cannot find tags. Do you have a solution for this other than just silencing the errors?

An import like `from sphinx.application import Tags as tags` destroys the conf.

**Comment by tk0miya** [comment]
No way. Please mark the line as skipped for these lint tools.
