### ISSUE TITLE
Code blocks with :linenos: are not accessible to blind people

### ISSUE THREAD

**Issue by kujiu** [sphinx-doc/sphinx#7849]
**Describe the bug**
When the screen reader reads the code block, it starts to say "1, 2, 3, 4, 5, 6, ..." and, after all numbers, it reads the code.

**To Reproduce**
Just create a code block with linenos (and more than one line of code), and try to read it with a screen reader.

**Expected behavior**
The screen reader will read "1 first line of code, 2 second line of code, ...) or, better, permit to browse the code like a table (with a real table or aria properties).

**Environment info**
- OS: Linux
- Python version: All
- Sphinx version: 3.1.1
- Sphinx extensions: none
- Extra tools: Firefox or Chromium and Orca

**Additional context**
The problem here is the structure of the code block. It's generated in a table with a single line. One cell contains all numbers and one all lines of code. It's impossible to the screen reader to associate a number to a line of code, and the user can't get advantage of line numbers. Fixing this can fix issue #1007.

**Comment by tk0miya** [comment]
Is this patch working fine for the purpose?
```
diff --git a/sphinx/directives/code.py b/sphinx/directives/code.py
index f1f4a341a..7476f235e 100644
--- a/sphinx/directives/code.py
+++ b/sphinx/directives/code.py
@@ -155,7 +155,7 @@ class CodeBlock(SphinxDirective):

         literal = nodes.literal_block(code, code)  # type: Element
         if 'linenos' in self.options or 'lineno-start' in self.options:
-            literal['linenos'] = True
+            literal['linenos'] = 'inline'
         literal['classes'] += self.options.get('class', [])
         literal['force'] = 'force' in self.options
         if self.arguments:
@@ -442,7 +442,7 @@ class LiteralInclude(SphinxDirective):
                 retnode['language'] = self.options['language']
             if ('linenos' in self.options or 'lineno-start' in self.options or
                     'lineno-match' in self.options):
-                retnode['linenos'] = True
+                retnode['linenos'] = 'inline'
             retnode['classes'] += self.options.get('class', [])
             extra_args = retnode['highlight_args'] = {}
             if 'emphasize-lines' in self.options:
```

**Comment by kujiu** [comment]
Thanks ! It's perfect !

Sorry for the delay (day off yesterday...)

**Comment by tk0miya** [comment]
I added `html_codeblock_linenos_style` to control the style of the line numbers for code-blocks. Please wait for a next release :-)
