### ISSUE TITLE
autodoc strips trailing underscores from function parameters' names

### ISSUE THREAD

**Issue by Aran-Fey** [sphinx-doc/sphinx#7857]
**Describe the bug**
Function parameters documented with the `:param` syntax have underscores stripped from their names.

**To Reproduce**
With a function like this:
```python
def testfunc(type_):
    """
    :param type_: lorem ipsum
    """
```
And documentation like this:
```rst
.. autofunction:: my_module.testfunc
```
The output generated by `make html` looks like this:
```
testfunc(type_)
    Parameters
        type – lorem ipsum
```
The function signature is correct, but in the "Parameters" section the parameter's name is wrong.

**Expected behavior**
The documentation should show the correct parameter name, i.e. `type_`.

**Environment info**
- OS: Manjaro linux
- Python version: 3.8.3
- Sphinx version: 3.1.1
- Sphinx extensions:  sphinx.ext.autodoc

**Comment by tk0miya** [comment]
It is interpreted as a hyperlink target notation by reST parser. So please add a backslash before the underscore to escape it.

**Comment by Aran-Fey** [comment]
Um, what? How in the world is that not a bug? Why the heck are parameter names treated as markup?

**Comment by tk0miya** [comment]
In Sphinx, it is 1) parsed as a field-list by reST parser, 2) recognized as an info-field list for python at next phase, and 3) converted it to the output format. At the first step, reST parser does not know the field name is a parameter. It considers it is a mere field name "param " and a reference for "type". 

To change this behavior, we need to rewrite whole of reST parser not to escape it. Of course, PR is always welcome :-)
