### ISSUE TITLE
Adding support for HTML table rendering with datatables.net

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#786]
As discussed at PyCon DE with Robert Lehmann I propose to add support for datatables.net when rendering HTML tables. That would allow a huge set of features for interacting with HTML tables, like multi-column sorting, column swapping, searching/filtering and tons more. 

Datatables.net is written in Javascript and can be configured only in Javascript, so this code needs to be placed either in the global conf.py file if it should be valid for all tables, maybe, or in a special directive/option if it should be applied to a specific table only.

Adding support for the many existing plugins for datatables.net as well might be some challenge, though.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/786
- Originally reported by: Dinu Gherman
- Originally created at: 2011-10-11T18:10:04.571

**Comment by cdeil** [comment]
I would like to add tables to my Sphinx page, and have them be a bit interactive and possibly rendering data from a JSON or CSV file like datatables.net.

Is there such a good table extension for Sphinx?

Alternatively -- could you point me to an extension or code example that's similar? I.e. adding something that requires adding HTML / JS and getting it working as part of (or subpage of) a Sphinx page?

I think this one might be similar, but it's very complicated:
https://github.com/bokeh/bokeh/blob/master/bokeh/sphinxext/bokeh_plot.py
cc @bryevdv

I looked a bit at these, but none seems to generate JS-powered table?
```
$ pip search sphinx | grep table
sphinxcontrib-exceltable (0.2.2)                     - Support for including Excel spreadsheets into Sphinx documents
sphinxcontrib-fulltoc (1.1)                          - Include a full table of contents in your Sphinx HTML sidebar
orgtblfilter (0.1)                                   - A sphinx extension to pre-process orgtbl-mode tables to sphinx tables
sphinx-prompt (1.0.0)                                - Sphinx directive to add unselectable prompt
sphinxcontrib-sqltable (1.0)                         - Sphinx "SQLTable" extension
sphinxcontrib.divparams (0.0.5)                      - Converts parameter tables in HTML documentation generated by Sphinx into <div>'s.
t3fieldlisttable (0.2.0)                             - Implement t3-field-list-table Directive for Sphinx
t3tablerows (0.1.0)                                  - Implement Sphinx transformation of "table-row" containers
```

**Comment by bryevdv** [comment]
Hi the `:bokeh-plot:` is generates interactive Bokeh plots inline in Sphinx documentation. It's probably alot more involved and sophisticated than you need, with a custom parser, event handlers, etc. You might have a look at this one:

https://github.com/bokeh/bokeh/blob/master/bokeh/sphinxext/bokeh_palette_group.py

which is much simpler, more along the standard lines of "define a new node, have the directive just dump the node in the doc, process the output with a html visitor".

**Comment by tk0miya** [comment]
I think it is better to implement this as an extension, not sphinx-core. So I marked this as wontfix and closing now.
Thank you for proposal.
