### ISSUE TITLE
autodoc + intersphinx: Document module members as though they were part of another module

### ISSUE THREAD

**Issue by Aran-Fey** [sphinx-doc/sphinx#7861]
Say I have a project like this:
```
my_package/
    __init__.py
    my_module.py
    my_other_module.py
```
Contents of `my_module.py`:
```python
def my_func():
    "doc for my_func"

def my_other_func():
    "doc for my_other_func"
```
Contents of `__init__.py`:
```python
from .my_module import *
from .my_other_module import *
```
Now I want to use the `automodule` directive to document all functions in `my_module.py`:
```rst
.. automodule:: my_package.my_module
```
The problem with this is that it registers the functions as members of `my_package.my_module`, but I want them to be members of `my_package`. Intersphinx shows the problem:
```
~> python -m sphinx.ext.intersphinx docs/build/html/objects.inv
py:function
	my_package.my_module.my_function          foo.html#my_package.my_module.my_function 
	my_package.my_module.my_other_function    foo.html#my_package.my_module.my_other_function 
```
I'd like this to be
```
py:function
	my_package.my_function          foo.html#my_package.my_function 
	my_package.my_other_function    foo.html#my_package.my_other_function 
```
instead.

**Workaround**
The workaround, of course, is to manually document all members of `my_module` with `autofunction`/`autoclass` directives. This is a huge hassle if the module contains a lot of stuff.

**Suggested solution**
Make the `automodule` directive accept a modifier that makes it masquerade as another module, for example like so:
```rst
.. automodule:: my_package.my_module
   :as-module: my_package
```

**Comment by tk0miya** [comment]
Why don't use use `.. automodule:: my_package`? I don't understand why you specified `my_package.my_module`.

**Comment by Aran-Fey** [comment]
That would document everything imported from `my_other_module.py` as well. I want to document each (sub-)module on a separate html page.

**Comment by tk0miya** [comment]
-1 for your idea. The autodoc should generate documents from source code as-is. Arrangement the output is not a responsibility of it.
