### ISSUE TITLE
HTMLWriter strips the first two entries of `meta`

### ISSUE THREAD

**Issue by xmo-odoo** [sphinx-doc/sphinx#7863]
**Describe the bug**
When creating a custom translator which does *not* ultimately inherit from `docutils.writers._html_base.HTMLTranslator`, getting metadata out through HTMLWriter requires "padding" the `meta` fields with two ingnored entries.

**To Reproduce**
* create a translator which only inherits from NodeVisitor and implements everything itself
* define a `meta` field with any number of entries
* set the custom translator as the application's
* generate HTML

**Expected behavior**
A tag for each entry into the corresponding field

**Observed**
Nothing for the first two entries, because [HTMLWriter skips the first two entries when generating clean_meta](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/writers/html.py#L76).

I expect because docutils fills those with a "charset" entry and a "generator" (setting itself as generator). Sadly [the original sphinx commit](https://github.com/sphinx-doc/sphinx/commit/4b9119f9905e608e74335214d9e15514d0adf2f7) does not explain why it strips the content during `translate` instead of the translator removing or fixing the entries it wants gone or replaced.

**Comment by tk0miya** [comment]
+1: Reasonable change.

**Comment by tk0miya** [comment]
I posted #7864 to fix this. Could you check this please?

**Comment by tk0miya** [comment]
As I commented at https://github.com/sphinx-doc/sphinx/pull/7864#issuecomment-748486209, I changed my opinion not to support custom translators not inheriting HTMLTranslator. Sorry for the confusion.
