### ISSUE TITLE
autosummary "first-sentence" detection fails in presence of abbreviations.

### ISSUE THREAD

**Issue by anntzer** [sphinx-doc/sphinx#7865]
**Describe the bug**

If a docstring's first sentence contains an abbreviation such as `i.e.`, autosummary incorrectly cuts the summary immediately after the abbreviation.

**To Reproduce**
```
$ sphinx-quickstart --sep -m -p foo -a author -r0 -len --extensions sphinx.ext.autosummary
```
edit `index.html` to contain
```
.. autosummary::
   foo.foo
```
and `foo.py` to contain
```
def foo():
    """
    Does foo, i.e. fooing the thing.
    """
```
then build with `make html` and open the built docs.

This results in 
![test](https://user-images.githubusercontent.com/1322974/85424765-9b094380-b578-11ea-90df-73c82a6e4fce.png)
i.e. the docstring summary is cut.

**Expected behavior**

Not cutting the summary.

The summary detection logic is at https://github.com/sphinx-doc/sphinx/blob/3.x/sphinx/ext/autosummary/__init__.py#L526 (basically splitting at dots followed by whitespace).  I can think of two ways for fixing it: either check that the dot is not followed by a lowercase character, or just special-case `i.e.` and perhaps a couple of other abbreviations.

**Environment info**
- OS: linux
- Python version: 3.8.1
- Sphinx version: 3.1.0
- Sphinx extensions:  autosummary

**Additional context**
N/A

**Comment by tk0miya** [comment]
Thank you for reporting. I choose the latter way in #7877.
