### ISSUE TITLE
autosummary spuriously removes spaces and appends an extra dot to the summary line in some cases

### ISSUE THREAD

**Issue by anntzer** [sphinx-doc/sphinx#7866]
**Describe the bug**

In some circumstances, autosummary spuriously removes spaces and appends an extra dot to the summary line.

**To Reproduce**
```
$ sphinx-quickstart --sep -m -p foo -a author -r0 -len --extensions sphinx.ext.autosummary
```
edit `index.html` to contain
```
.. autosummary::
   foo.foo
```
and `foo.py` to contain
```
def foo():
    """
    Do `this <https://www.google.com>`_ and that.  Pretend this line is really
    long and has some interesting contents.
    """
```
then build with `make html` and open the built docs.

This results in 
![test](https://user-images.githubusercontent.com/1322974/85426853-4ddaa100-b57b-11ea-8bc2-e1b78198de4c.png)
i.e. the docstring has a space missing after `that.`, and an extra dot at the end.

**Expected behavior**

A space after `that.`, and no extra dot at the end.

**Environment info**
- OS: linux
- Python version: 3.8.1
- Sphinx version: 3.1.0
- Sphinx extensions:  autosummary

**Additional context**
N/A

**Comment by tk0miya** [comment]
Thank you for reporting. I fixed it now (see #7876)
