### ISSUE TITLE
:abbr: without an explanation will show the explanation from the previous :abbr: role

### ISSUE THREAD

**Issue by brechtm** [sphinx-doc/sphinx#7869]
**Describe the bug**
An `:abbr:` role _without an explanation_ in parentheses will show the explanation from the previous `:abbr:` role.

**To Reproduce**

1. Tag some text with the `:abbr:` role and include an explanation within parentheses, e.g. ``:abbr:`LIFO (last-in, first-out)` ``
2. Later in the document, tag some other text with the `:abbr:` role but omit the explanation, e.g. ``:abbr:`KISS` ``
3. Build the document (HTML, LaTeX, ...)

The output will include the explanation for the first `:abbr:` role also for the second one:

<img width="191" alt="image" src="https://user-images.githubusercontent.com/652887/85712504-ad09f400-b6e8-11ea-8a94-9b7329f0ffe3.png">

**Expected behavior**
The output should not include an explanation for the second `:abbr:`:

**Environment info**
- OS: macOS High Sierra 10.13.6 (17G13035)
- Python version: 3.8.3
- Sphinx version: 3.1.1
- Sphinx extensions:  none
- Extra tools: none

**Comment by brechtm** [comment]
Additionally for the HTML builder, the second LIFO mention will show the explanation for KISS (the last use of `:abbr:` _with_ explanation) for this input:

    :abbr:`LIFO (last-in, first-out)` :abbr:`KISS (keep it simple, stupid)` :abbr:`LIFO`

**Comment by tk0miya** [comment]
Oops... Thank you for reporting. #7873 will fix this.
