### ISSUE TITLE
sphinx requires package sphinx.ext.mathbase

### ISSUE THREAD

**Issue by cecilchurms** [sphinx-doc/sphinx#7883]
I have installed new sphinx as part of the espressif skd but node_factory  requires 'sphinx.ext.mathbase'

The discussions say this module is no longer needed, so I think this is due to sphinx

File "/home/cecil/.espressif/python_env/idf4.0_py3.8_env/lib/python3.8/site-packages/breathe/node_factory.py", line 5, in <module>
    import sphinx.ext.mathbase
ModuleNotFoundError: No module named 'sphinx.ext.mathbase'

**Comment by tk0miya** [comment]
Yes, `sphinx.ext.mathbase` module was deprecated at 1.8.0, and removed at 3.0.0. So you need to upgrade breathe to newest one (or let this them to fix the error).
Thanks,
