### ISSUE TITLE
Refactor sphinx.js locale files to improve readability

### ISSUE THREAD

**Issue by chuckyQ** [sphinx-doc/sphinx#7887]
**Is your feature request related to a problem? Please describe.**
I was reading through the sphinx.js locale files and found all of them were a single line.
It was really tough to figure out what they were doing. After looking through them,
I wanted to edit the formatting to improve the readability and make it easier
to see which areas still need work.

**Describe the solution you'd like**
I reformatted all of them with a combination of sed and Python.

**Describe alternatives you've considered**
I considered not touching them and hold the history of the files, 
but I also wanted to experiment to see if I could improve readability.

**Additional context**
N/A

**Comment by tk0miya** [comment]
They are generated from translations catalog. see `compile_catalog_plusjs` class in `setup.py`. It would be nice if you make a PR to format them.

**Comment by chuckyQ** [comment]
After reviewing more of the codebase, I see this will require some more work to be effective (and may not even be necessary). I would not use my PR and instead I can investigate formatting the auto-generated files. One idea I had was to just have the .js files exist statically and only be generated if not found, otherwise, just use the existing *formatted* js files.

**Comment by tk0miya** [comment]
How do you update messages in sphinx.js? At present, they are always overridden by latest translations forcedly. In your idea, there are no way to update the messages if file exists.

**Comment by chuckyQ** [comment]
Good point, I would have to figure out a way to format them every time they are built.

**Comment by chuckyQ** [comment]
Turns out, it was a simple add-on to the `json.dump` call in setup.py

**Comment by jakobandersen** [comment]
Aren't the the final js files supposed to be as small as possible? If I understand correctly it is possible to provide source maps back to a nicely formatted js file instead, if one wants to read the files.

**Comment by tk0miya** [comment]
+0: Either is okay to me. The generated JS files are all small. So I think the indentation does not harm anyone.
