### ISSUE TITLE
apidoc generates an extra newline at the end of the rst file if a module has submodules

### ISSUE THREAD

**Issue by AleksaC** [sphinx-doc/sphinx#7890]
**Describe the bug**
This is not really a bug but rather an annoyance if you are using pre-commit hooks that format end of file, as it would often make commits fail that wouldn't otherwise.

**To Reproduce**
Create a package with at least one submodule. and use apidoc on it. Something like this
```
├── docs
│   ├── conf.py
│   ├── index.rst
│   ├── make.bat
│   ├── Makefile
│   ├── package
│   │   ├── modules.rst
│   │   └── package.rst
│   ├── _static
│   └── _templates
└── package
    ├── __init__.py
    └── test.py
```
```
$ sphinx-apidoc -f -q -o package ../package -M 
```
**Expected behavior**
`package.rst` ends with a single newline instead of two.

---

From what I could quickly gather from the codebase this can be easily resolved by adding:
```python
if text.endswith('\n\n'):
  text = text[:-1]
```
to `def write_file(name: str, text: str, opts: Any) -> None:` in `apidoc.py`

**Comment by tk0miya** [comment]
Thank you for reporting. I guess this is a problem of default template of apidoc. I'll take a look later.
https://github.com/sphinx-doc/sphinx/blob/3.x/sphinx/templates/apidoc/package.rst_t

**Comment by AleksaC** [comment]
Thanks for the response. You are right. I think I found a way to fix it, I can provide a PR if it's ok.

**Comment by tk0miya** [comment]
Sounds good. It's helpful :-)
