### ISSUE TITLE
TODO example is missing env-merge-info

### ISSUE THREAD

**Issue by JulienPalard** [sphinx-doc/sphinx#7898]
Looks like the [tutorials/todo](https://www.sphinx-doc.org/en/master/development/tutorials/todo.html) example is missing the `env-merge-info` step to make it work for parallel builds.

In cpython we use a similar pattern, and it was not working in parallel builds, I added it like this: https://github.com/python/cpython/pull/21237

Am I right? If so I can add it to the example.

**Comment by tk0miya** [comment]
OMG! Indeed, it misses `env-merge-info`. It would be helpful if you post a PR :-)
