### ISSUE TITLE
viewcode fails to execute when autodoc is not used

### ISSUE THREAD

**Issue by prazzb** [sphinx-doc/sphinx#7903]
**Describe the bug**
When viewcode is enabled (autodoc is disabled), the plugin fails to execute

**To Reproduce**

file a.c
```
#include "a.h"
static uint8_t abcd[4]; 
uint8_t abcd12(uint8_t a,uint16_t b)
{
    a=b;
    abcd[2]=a;
}
```
file a.h
```
#include <stdint.h>
uint8_t abcd12(uint8_t a,uint16_t b);
```
snippet of conf.py
```
author = 'AUTHOR'

extensions = [
'sphinx.ext.todo',
'sphinx.ext.graphviz',
'sphinx.ext.viewcode',
]
```
file code.rst
```
Code page
=========

.. graphviz::

   digraph foo {
    "bar" -> "baz";
   }
 
.. todo:: This is a todo for test
 
.. c:function:: uint8_t abcd12(uint8_t a,uint16_t b)
 
   The above function takes in a and b and returns an uint8_t data
 
   :param uint8_t a: a parameter
   :param uint8_t b: another parameter 
   :return: the return variable
 
.. todo:: This is an extra todo for test
```
after adding code.rst to index.rst and running
```
sphinx-build . _build
```
**Expected behavior**
There should be a link to the source code which is not seen.

**Environment info**
- OS: Linux Ubuntu
- Python version: [e.g. 3.6.9]
- Sphinx version: [e.g. 3.1.0]
- Sphinx extensions:  [e.g. sphinx.ext.viewcode,sphinx.ext.todo,sphinx.ext.graphviz]

**Additional context**
Sphinx installed using pip.Other extensions todo and graphviz work as expected.
For this testing, the c and header files are in the same folder as conf.py,index.rst,code.rst

I want this clarified, can the viewcode not used without autodoc ? Do I need to use
something else like module etc

**Comment by tk0miya** [comment]
The viewcode extension is independent of autodoc. You can use it without autodoc. But it only supports python codes, not C codes. So this is expected behavior. It would be nice if we can support also other languages. But it's not a responsibility of Sphinx-core. So I'm closing this now.

**Comment by prazzb** [comment]
Thanks for the reply tk0miya.
