### ISSUE TITLE
Building the Sphinx documentation using 'make latexpdf' fails

### ISSUE THREAD

**Issue by brechtm** [sphinx-doc/sphinx#7921]
Trying to build a PDF of the Sphinx 3.1.2 manual using `make latexpdf` in the docs directory fails with

    ! LaTeX Error: Unknown graphics extension: .svg.

Should `sphinx.ext.imgconverter` be added to the list of extensions in _conf.py_?

**Comment by tk0miya** [comment]
Yes, LaTeX does not support SVG images. Please add some imageconverter extensions (ex. `sphinx.ext.imgconverter`, `sphinxcontrib-svg2pdfconverter`, and so on).

**Comment by brechtm** [comment]
Is it ok for this to be broken in a clean checkout? Shouldn't `sphinx.ext.imgconverter` be added to the list of extensions?

**Comment by tk0miya** [comment]
Oh, sorry. it's my bad. I considered you were saying about your own docs. Okay, I understand. I thought adding `sphinx.ext.imgconverter` requires extra third party tools on building PDF. I don't know it is really worthy.

**Comment by brechtm** [comment]
I would vote to include `sphinx.ext.imgconverter` in the list of extensions. It is included with Sphinx and will should affect the HTML build.

I assume `sphinx.ext.imgconverter` will abort with a clear message to the user when ImageMagick could not be found? Building the Sphinx PDF docs now just crashes latex, which makes it look like there's a bug.

**Comment by brechtm** [comment]
I'm wondering whether the Sphinx PDF docs are generated as part of CI. If so, how is this handled?

**Comment by mgeier** [comment]
We are talking about a single static SVG, right?
What about manually converting it to PDF, storing it in the repo and using `translation.*` as image source?

**Comment by brechtm** [comment]
> What about manually converting it to PDF, storing it in the repo and using `translation.*` as image source?

That crossed my mind as well... and then I forgot. :-)
This is probably the best approach!

**Comment by tk0miya** [comment]
Reasonable. +1 for adding .PDF (or .PNG) file.

**Comment by tk0miya** [comment]
Done in #7924. Closing.
