### ISSUE TITLE
Default value of inspect.Parameter.empty breaks autofunction signature

### ISSUE THREAD

**Issue by Aran-Fey** [sphinx-doc/sphinx#7935]
**Describe the bug**
When you have a function with (at least) 2 optional parameters and the default value for the 2nd parameter is `inspect.Parameter.empty`, something goes wrong and the documentation generated for this function will not display
any parameters at all in the signature.

**To Reproduce**
Create a python function like this:
```python
import inspect

def func(optional_arg1='whatever',
         optional_arg2=inspect.Parameter.empty,
         ):
    """lorem ipsum"""
```
Document it with the `autofunction` directive:
```rst
.. autofunction:: func
```
Run `make html` and observe the missing parameters in the output:
```
package_name.func()¶
    lorem ipsum
```

**Expected behavior**
The function's parameters should show up in the documentation. I understand that it's difficult to deal with `inspect.Parameter.empty` as a default value, but completely omitting the function's parameters without any kind
of error or warning is not acceptable.

**Environment info**
- OS: linux
- Python version: 3.8
- Sphinx version: 3.1.2
- Sphinx extensions:  sphinx.ext.autodoc

**Comment by tk0miya** [comment]
Thank you for reporting. I just posted a fix #7937 to resolve this issue.
