### ISSUE TITLE
autosummary strips docstrings after the first dot

### ISSUE THREAD

**Issue by Yura52** [sphinx-doc/sphinx#7939]
**Describe the bug**

`autosummary` strips docstrings after the first "." sign.

**To Reproduce**

a.py:
```python
"""The best module. Ever."""
```

a.rst
```
.. autosummary::

    a
```

output (no " Ever." part):
```
a | The best module.
```

**Environment info**
- OS: Mac/Win/other with version]
- Python version: 3.6.10
- Sphinx version: 3.1.2
- Sphinx extensions:  sphinx.ext.autodoc, sphinx.ext.autosummary, sphinx.ext.doctest, sphinx.ext.intersphinx, sphinx.ext.napoleon, sphinx.ext.viewcode

**Comment by tk0miya** [comment]
Yes. The autosummary extension picks the first sentence up from its docstring. So this is intended behavior.

**Comment by Yura52** [comment]
As I see it, docstrings, "by design", are supposed to contain one-line description as the first line and details somewhere further in separate paragraphs. This is why I expected autosummary to take the first line. This is not a blocker to me, of course :) Just sharing thoughts.

**Comment by tk0miya** [comment]
I also don't know why autosummary picks the first sentence up. I guess some components might have a very very long first line. Anyway, this is a part of (well-known) current behavior of autosummary. So I'd like to keep this as is. Thank you for your proposal!
