### ISSUE TITLE
Date formatting in latex output is not localized

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#794]
When outputting localized documents, Sphinx doesn't localize generated date output.

Functions such as time.strftime use the current locale to format their output. By default, the interpreter uses the C locale, in order to use the user's preferred locale it needs to call locale.setlocale(locale.LC_ALL, '').

For example, writers/latex.py:189 formats the current month without calling locale.setlocale before:

```
#!python

            self.elements['date'] = ustrftime(builder.config.today_fmt
                                              or _('&#37;B &#37;d, &#37;Y'))
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/794
- Originally reported by: [doublea](https://bitbucket.org/doublea)
- Originally created at: 2011-10-14T23:32:40.261

**Comment by shimizukawa** [comment]
_From [doublea](https://bitbucket.org/doublea) on 2011-10-14 21:40:25+00:00_

Here's a patch that solves the issue by explicitly calling locale.setlocale(locale.LC_ALL, ''), which means use the locale specified by the $LANG envvar.

It has a very ugly workaround to avoid importing the "locale" directory that sphinx includes.

**Comment by tk0miya** [comment]
In my short investigation: 
There is 7 files using `ustrftime()` in Sphinx. But no `setlocale()` in anycase.
If we support this, it would good to call `setlocale()` on starting Sphinx application, I think.

**Comment by tk0miya** [comment]
@shimizukawa is this good to translations? How do you think?

**Comment by shimizukawa** [comment]
Calling `locale.setlocale(locale.LC_ALL, '')` at start of sphinx is works well. However it doesn't depend on the `language` parameter in conf.py which means doc building for other language always require LANG environment variable as `LANG=ja_JP.utf-8 sphinx-build -D='language=ja'` to build with correct translations.

BTW, on windows environment, `LANG=Japanese_Japan.932` is correct instead of `LANG=ja_JP.utf-8`. IMO, if we want to use `locale.setlocale()` to provide date/time translation, we should prepare LANG/language mapping.

**Comment by shimizukawa** [comment]
IMO, `babel.dates.date_format` can provide better solution.

```
>>> from babel.dates import format_date
>>> from datetime import date
>>> d = date.today()
>>> print format_date(d, locale='ja', format='G Y y u Q q M L W w D d F E e c')
西暦 2016 2016 2016 1 1 1 1 4 4 23 23 4 土 6 6                                                                                                                                                                                                                                                                   
>>> print format_date(d, locale='zh', format='G Y y u Q q M L W w D d F E e c')
公元 2016 2016 2016 1 1 1 1 4 4 23 23 4 周六 6 6                                                                                                                                                                                                                                                                 
>>> print format_date(d, locale='de', format='G Y y u Q q M L W w D d F E e c')
n. Chr. 2016 2016 2016 1 1 1 1 4 4 23 23 4 Sa. 6 6
>>> print format_date(d, locale='fr', format='G Y y u Q q M L W w D d F E e c')
ap. J.-C. 2016 2016 2016 1 1 1 1 4 4 23 23 4 sam. 6 6
>>> print format_date(d, locale='en', format='G Y y u Q q M L W w D d F E e c')
AD 2016 2016 2016 1 1 1 1 4 4 23 23 4 Sat 6 6
```

This solution requires incompatible change for date formatting strings.

**Comment by tk0miya** [comment]
+1 for shimizukawa's proposal. That's sphinx way!
