### ISSUE TITLE
Improve deprecated_alias warnings

### ISSUE THREAD

**Issue by peterbell10** [sphinx-doc/sphinx#7952]
**Is your feature request related to a problem? Please describe.**
Consider this warning generated by [`deprecated_alias`](https://github.com/sphinx-doc/sphinx/blob/293fa1e5fc7ee663cb2b2c7e446623773fa9735a/sphinx/directives/__init__.py#L281):
```
>>> from sphinx.directives import SeeAlso
__main__:1: RemovedInSphinx40Warning: sphinx.directives.SeeAlso is deprecated. Check CHANGES for Sphinx API modifications.
```
That makes it sound like `SeeAlso` is being removed in Sphinx 4.0 when in reality it seems to only be that importing from `sphinx.directives` is deprecated. That really isn't clear from the warning.

**Describe the solution you'd like**
The warning should specify it's just the alias that's depreacted and tell you what the canonical version is. e.g.

> The alias "sphinx.directives.SeeAlso" is deprecated, use "sphinx.directives.other.SeeAlso" instead. Check CHANGES for Sphinx API modifications.

**Comment by tk0miya** [comment]
Reasonable. Could you make a PR please?
