### ISSUE TITLE
Cannot 'make html' with sphinx on (relatively) fresh ubuntu 18.04 install

### ISSUE THREAD

**Issue by llionevans** [sphinx-doc/sphinx#7963]
**Describe the bug**
Despite trying various methods of installing sphinx (see below), I get a range of different errors when trying to do `make html`.

**To Reproduce**

First I tried:
`pip3 install -U sphinx`
Version from `pip3 list`: Sphinx (3.1.2)
Error:
```
/bin/sh: 1: sphinx-build: not found
Makefile:20: recipe for target 'html' failed
make: *** [html] Error 127
```

Then after pip3 uninstall, I tried:
`pip3 install git+https://github.com/sphinx-doc/sphinx`
Version from `pip3 list`: Sphinx (3.2.0.dev20200716)
Error:
```
/bin/sh: 1: sphinx-build: not found
Makefile:20: recipe for target 'html' failed
make: *** [html] Error 127
```

Then after pip3 uninstall, I tried:
`sudo apt install -y python3-sphinx`
Version from `pip3 list`: Sphinx (1.6.7)
Error:
```
Running Sphinx v1.6.7
making output directory...

Exception occurred:
  File "/home/ubuntu/.local/lib/python3.6/site-packages/sphinxcontrib/bibtex/__init__.py", line 134, in setup
    transforms = app.registry.get_transforms()
AttributeError: 'SphinxComponentRegistry' object has no attribute 'get_transforms'
The full traceback has been saved in /tmp/sphinx-err-15n130td.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Makefile:20: recipe for target 'html' failed
make: *** [html] Error 1
```

Finally I tried to update the super old version from apt install:
`pip3 install -U sphinx`
Version from `pip3 list`: Sphinx (3.1.2)
Error:
```
Traceback (most recent call last):
  File "/usr/bin/sphinx-build", line 14, in <module>
    from sphinx import main
ImportError: cannot import name 'main'
Makefile:20: recipe for target 'html' failed
make: *** [html] Error 1
```

In addition to sphinx, I have the following relevant packages installed
```
sphinx-rtd-theme (0.5.0)
sphinxcontrib-applehelp (1.0.2)
sphinxcontrib-bibtex (1.0.0)
sphinxcontrib-devhelp (1.0.2)
sphinxcontrib-htmlhelp (1.0.3)
sphinxcontrib-jsmath (1.0.1)
sphinxcontrib-qthelp (1.0.3)
sphinxcontrib-serializinghtml (1.1.4)
```

**Expected behavior**
It should compile the docs in html. I know that this `make html` script works on a number of other systems, So I'm assuming the issue lies with the sphinx installation on this system.

**Environment info**
- OS: Ubuntu 18.04 (fresh install with basic updates and installation of things like python3 and git)
- Python version: 3.6.9
- Sphinx version: see above (no idea why apt install retrieves such an old version)
- Sphinx extensions:  see above
- Extra tools: pip3

Hopefully that's enough info, let me know if anything else is needed.

**Comment by llionevans** [comment]
Similar to [this issue](https://github.com/sphinx-doc/sphinx/issues/7046).

`sudo pip3 install -U sphinx` seems to work (v3.1.2). But I wouldn't class that as issue closed because I would never normally use `sudo pip3 install` for any other packages.

Also, it doesn't explain why apt install retrieves such an old version.

If this is expected behaviour, then please mark as closed, but can I suggest you note the sudo requirement in documentation.

**Comment by tk0miya** [comment]
Hmm... I don't know what happened here.
```
/bin/sh: 1: sphinx-build: not found
Makefile:20: recipe for target 'html' failed
make: *** [html] Error 127
```

It seems sphinxcontrib-bibtex depends on newer version of Sphinx. So you need to install a newer one (I don't know the required version of bibtex).
```
Exception occurred:
  File "/home/ubuntu/.local/lib/python3.6/site-packages/sphinxcontrib/bibtex/__init__.py", line 134, in setup
    transforms = app.registry.get_transforms()
```

>Also, it doesn't explain why apt install retrieves such an old version.

Simply, ubuntu 18.04 provides a package versioned 1.6.7.
https://packages.ubuntu.com/ja/bionic/python3-sphinx

>If this is expected behaviour, then please mark as closed, but can I suggest you note the sudo requirement in documentation.

I don't know what happened in your environment. But sudo is not required for installation.

**Comment by jakobandersen** [comment]
An educated guess on what is going on:
> `pip3 install -U sphinx`
> Version from `pip3 list`: Sphinx (3.1.2)

This not only installs Sphinx, but all the dependencies for this particular version.
On Ubuntu the installation folder is usually ``$HOME/.local/``. However ``$HOME/.local/bin`` is not as default in the ``$PATH``, so
> ```
> /bin/sh: 1: sphinx-build: not found
> Makefile:20: recipe for target 'html' failed
> make: *** [html] Error 127
> ```

Is probably because you use the default ``$PATH``. (Try ``echo $PATH``)

> `pip3 install git+https://github.com/sphinx-doc/sphinx`
> Version from `pip3 list`: Sphinx (3.2.0.dev20200716)

This basically does the same as the previous installation, just with a dev version.

> Then after pip3 uninstall, I tried:
> `sudo apt install -y python3-sphinx`
> Version from `pip3 list`: Sphinx (1.6.7)
> Error:
> 
> ```
> Running Sphinx v1.6.7
> making output directory...
> 
> Exception occurred:
>   File "/home/ubuntu/.local/lib/python3.6/site-packages/sphinxcontrib/bibtex/__init__.py", line 134, in setup
>     transforms = app.registry.get_transforms()
> AttributeError: 'SphinxComponentRegistry' object has no attribute 'get_transforms'
> The full traceback has been saved in /tmp/sphinx-err-15n130td.log, if you want to report the issue to the developers.
> Please also report this if it was a user error, so that a better error message can be provided next time.
> A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
> Makefile:20: recipe for target 'html' failed
> make: *** [html] Error 1
> ```

Pip and apt does not mix well, they use different directories, but they interact in strange ways. Your uninstall of the pip-installed Sphinx probably didn't remove all the dependencies. So now the apt-installed old Sphinx version imports newer-Sphinx dependencies that were pip-installed.
Basically, only use pip or only use apt seems to me to be the only way to not break things in the long run.

> Finally I tried to update the super old version from apt install:
> `pip3 install -U sphinx`
> Version from `pip3 list`: Sphinx (3.1.2)
> Error:
> 
> ```
> Traceback (most recent call last):
>   File "/usr/bin/sphinx-build", line 14, in <module>
>     from sphinx import main
> ImportError: cannot import name 'main'
> Makefile:20: recipe for target 'html' failed
> make: *** [html] Error 1
> ```
The ``$PATH`` problem hits again, notice that it is ``/usr/bin/sphinx-build`` that you run, which is the apt-installed version. Pip can't (and should) not change it. The error is because the ``sphinx-build`` executable not tries to import the sphinx module, and because Python _does_ search in ``$HOME/.local/`` it picks the pip-installed version, which is not compatible.

So, purge the apt-installed version and add ``$HOME/.local/bin`` to your ``$PATH``.

**Comment by llionevans** [comment]
I should mention that I also tried installing sphinx via `apt install` before using pip3 at all on another fresh copy of the system. In that case it still installed v1.6.7. As @tk0miya points out, this is the version that comes for ubuntu but it's too old for use with sphinxcontrib-bibtex.

Is there a way of forcing a newer version via apt e.g. `sudo apt install python3-sphinx=3.1.2`? (this doesn't work) Or is v1.6.7 the newest version available via `apt install`?

If it's not possible, I guess using pip3 is my only option. See $PATH below, `/home/ubuntu/.local/bin` is already there.

`/home/ubuntu/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`

**Comment by jakobandersen** [comment]
> Is there a way of forcing a newer version via apt e.g. `sudo apt install python3-sphinx=3.1.2`? (this doesn't work) Or is v1.6.7 the newest version available via `apt install`?

Not as far as I understand. They package a specific version, which is probably the one used to build documentation for other packages in their repository. So packaging a newer major version probably make other packages break, and someone need to do the work to fix it :-). Though, Ubuntu usually bases its packages off of Debian, so you should look there for what's to come.

> If it's not possible, I guess using pip3 is my only option. See $PATH below, `/home/ubuntu/.local/bin` is already there.
> 
> `/home/ubuntu/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`

Yes, pip is the only way to go if you always want the newest version (of any Python package) on Ubuntu.
This really isn't a Sphinx issue it should probably go on the users mailing list, but:
As mentioned, try purging the apt version, reinstalling the pip version, and then check if ``sphinx-build`` is in ``$HOME/.local/bin``.

**Comment by LyonsDo** [comment]
The only way that worked for me (after many efforts) was @jakobandersen
pip3 install git+https://github.com/sphinx-doc/sphinx

That installed a working Sphinx 4.0.0.dev20210310.dev-20210310 e1a02dc
and I now see "Running Sphinx v3.5.3+" which is fine.
