### ISSUE TITLE
sidebar's TOC pushes down code-block and the following contents

### ISSUE THREAD

**Issue by kenjiuno** [sphinx-doc/sphinx#7970]
**Describe the bug**

![image](https://user-images.githubusercontent.com/5955540/87753060-b811f900-c83c-11ea-821a-506b1165d6cf.png)

**To Reproduce**

1. Place `.. code-block::`
2. Use `html_theme = 'solar_theme'` in `conf.py`

```
WCQ 検索式
=============

WCQ (Word Complex Query)

逆ポーランド法で検索式を組み立てます。8 ビットのバイナリセーフ、バイトオーダーはリトルエンディアンです。

引数は左からプッシュします。中置記法で ``1 < 2`` の場合、後置記法では ``1 2 <``

1 バイト目の構造
-----------------

.. code-block::

   0x00 - 0x7F = 引数(文字列、バイト数を示します)
   0x80 - 0xBF = 引数(DB フィールド)
   0xC0 - 0xFF = オペコード
```

**Expected behavior**

![image](https://user-images.githubusercontent.com/5955540/87753073-bcd6ad00-c83c-11ea-8eac-95288ae428d5.png)

**Your project**
https://github.com/HiraokaHyperTools/dd-u

**Screenshots**
Please check the above ones.

**Environment info**
- OS: Windows 10
- Python version: 3.7.3
- Sphinx version: 3.1.2
- Sphinx extensions:  `sphinx.ext.githubpages`
- Extra tools: none

**Additional context**

I have checked set of diffs between good one and wrong one.

These 3 lines seem to cause:

```
pre, div[class|="highlight"] {
    clear: both;
}
```

https://github.com/sphinx-doc/sphinx/commit/045fc6807820ba1a1976799a237cc01cfc8403c8#diff-f19a96d9d3ab687445d135108041a607R681-R684

**Comment by mgeier** [comment]
See #7689. I guess the same change could be made to the `solar_theme`?

**Comment by kenjiuno** [comment]
@mgeier Thanks for the advice, it worked!

I have installed `solar_theme` locally, and I have fixed it within my side.
https://github.com/HiraokaHyperTools/dd-u/commit/c66d6a9a2e67bf150e0ff443f9c8a83521be9596
