### ISSUE TITLE
ImgConverter runs is_available in HTML builder

### ISSUE THREAD

**Issue by Daltz333** [sphinx-doc/sphinx#7973]
Since ImgConverter is only used in the LaTeX builder, this check should not happen in HTML.

**Comment by tk0miya** [comment]
Why do you think so? It is available for all of the builders. For example, it converts PDF image to an appropriate format for 
HTML builder. The extension is not only for the LaTeX builder, I think.

**Comment by Daltz333** [comment]
I use the svg2pdf-converter extension which is based on the ImageConverter class. Currently on windows it throws 150+ errors (one per document) because of missing dependencies. Since we only build PDF on latex we were hoping using the extension wouldn't be a problem.

**Comment by tk0miya** [comment]
I understand. I agreed that so many warnings are meaningless and noisy. It would be better to emit only one warning during the build (Note: I don't think to suppress all of the warnings is better).
