### ISSUE TITLE
copy button copies `>>>` lines, but doesn't copy "..." lines

### ISSUE THREAD

**Issue by stas00** [sphinx-doc/sphinx#7988]
**Describe the bug**

When the copy button is clicked on a code like [this](https://huggingface.co/transformers/quicktour.html#using-the-tokenizer):

```
>>> pt_batch = tokenizer(
...     ["We are very happy to show you the 🤗 Transformers library.", "We hope you don't hate it."],
...     padding=True,
...     truncation=True,
...     return_tensors="pt"
... )
```

only the first line is copied. 

All lines starting with `>>>` get copied, but `...` lines are ignored. So for example, [this](https://huggingface.co/transformers/quicktour.html#customizing-the-model) gets fully copied:

```
>>> from transformers import DistilBertConfig, DistilBertTokenizer, DistilBertForSequenceClassification
>>> config = DistilBertConfig(n_heads=8, dim=512, hidden_dim=4*512)
>>> tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')
>>> model = DistilBertForSequenceClassification(config)
```

I was told that this could be `sphinx_copybutton`.

**To Reproduce**

e.g. click the copy button at this url and scroll a few lines down to the third code section at:
https://huggingface.co/transformers/quicktour.html#using-the-tokenizer

**Expected behavior**

lines starting with `...` should be copied just as they do for lines starting with `>>>`

**Your project**
https://huggingface.co/transformers/

**Environment info**

I'm just a user, so I'm not sure about the environment.
All I know is that it says at the bottom of the page, that it uses this theme:
https://github.com/rtfd/sphinx_rtd_theme
I'd be happy to ask for more details if needed.

I was able to reproduce it in the latest firefox and chrome on linux.

**Comment by tk0miya** [comment]
This is an issue list of Sphinx core, not sphinx-copybutton. Unfortunately, we can't fix the extension.
The sphinx-copybutton project is here: https://github.com/executablebooks/sphinx-copybutton

Thanks,

**Comment by stas00** [comment]
Thank you for directing me to the right project, @tk0miya! I found there is an issue open already: https://github.com/executablebooks/sphinx-copybutton/issues/65
