### ISSUE TITLE
3.1.2 introduces WARNING: py:class reference target not found: Callable[[...], Awaitable[None]]

### ISSUE THREAD

**Issue by altendky** [sphinx-doc/sphinx#8008]
**Describe the bug**
```python
@decorator.decorator
def host(
    func: typing.Callable[..., typing.Awaitable[None]],
    timeout: float = 3,
    *args,
    **kwargs
):
```

My project, including the above function definition, builds cleanly with Sphinx 3.1.1 but with 3.1.2 I get the following warning.

```
/home/altendky/repos/preqtrio/qtrio/_pytest.py:docstring of qtrio.host:: WARNING: py:class reference target not found: Callable[[...], Awaitable[None]]
```

Note that the resulting parameter documentation does properly hyperlink `Callable` and `Awaitable` but `None` does not get a link.

https://qtrio--105.org.readthedocs.build/en/105/testing.html#qtrio.host

**To Reproduce**
```bash
git clone https://github.com/altendky/qtrio
cd qtrio
git checkout 38d8e6501b032429f2875e21779dfb67b2604d94
python3 -m venv venv
venv/bin/pip install --upgrade pip setuptools wheel
venv/bin/pip install -e .[pyside2,docs]
source venv/bin/activate
cd docs
../venv/bin/pip install --upgrade sphinx==3.1.1
rm -rf build; make html
../venv/bin/pip install --upgrade sphinx==3.1.2
rm -rf build; make html
```

**Expected behavior**
The error doesn't happen in either case and `Callable`, `Awaitable`, and `None` all get properly hyperlinked.

**Your project**
https://github.com/altendky/qtrio

**Screenshots**
![image](https://user-images.githubusercontent.com/543719/88496663-e5bd1780-cf8b-11ea-8fe5-a9c8e89f4184.png)

**Environment info**
- OS: Linux - Ubuntu 20.04
- Python version: 3.8.3
- Sphinx version: 3.1.2
- Sphinx extensions:
  - sphinx.ext.autodoc
  - sphinx.ext.intersphinx
  - sphinx.ext.coverage
  - sphinx.ext.napoleon
  - sphinx_autodoc_typehints
  - sphinx_qt_documentation
  - sphinxcontrib_trio

**Additional context**
https://github.com/altendky/qtrio/pull/105

**Comment by altendky** [comment]
#8020 does address the warning.  It is gone.  The `None` is still not linked though.

![image](https://user-images.githubusercontent.com/543719/88838082-06ad8480-d1a7-11ea-9c7a-27b0cc7bb36d.png)

That may belong in another ticket or it might be an issue with `sphinx-autodoc-typehints` or...

I will note that this may or may not be a difference between this issue and #8015.  In #8015 I got to `@typing.overload` which `sphinx-autodoc-typehints` does not yet support so there was nothing to be linked (or fail to be linked).

(P.S. thanks here too)

**Comment by tk0miya** [comment]
Thank you for confirming. I'll merge it soon.

About `None` problem, it would be a problem of sphinx-autodoc-typehints extension. The autodoc extension can make it linkable. On the other hand, autodoc can't make containers (`Callable` and `Awaitable`) linkable. I'll work for that in the near future.
