### ISSUE TITLE
Instance attributes are omitted with autosummary

### ISSUE THREAD

**Issue by Chilipp** [sphinx-doc/sphinx#8011]
This issue is a followup of #7948. Sorry, I forgot to open it.

**Is your feature request related to a problem? Please describe.**
Instance attributes are omitted when using the autosummary, as they cannot be imported. Consider the following class

```python
# contents of test_mod.py

class Test:
    """Test class"""

    #: int. Some class attribute
    test: int = 1

    def __init__(self, a: int):
        #: int. An instance attribute
        self.a = 1

```

`autodoc` via 

```rst
.. autoclass:: Test
    :members:
``` 

will document the `a` attribute, but `autosummary` via

```rst
.. autosummary::

    Test.a
    Test.test
```
won't.

**Describe the solution you'd like**
Instance attributes should be documented, too

**Describe alternatives you've considered**
it did work before 1dcfc44, i.e. for `sphinx<3.1` (although the documentation was omitted).

**Additional context**

- #7948
- files to reproduce the issue (including page build) [test.zip](https://github.com/sphinx-doc/sphinx/files/4982157/test.zip)
- Screenshot of index.html
  ![image](https://user-images.githubusercontent.com/9960249/88545154-ddf88400-d01a-11ea-906c-193e39fbb4d3.png)

**Comment by Chilipp** [comment]
@tk0miya, I cannot  add labels or milestones here, but nonetheless already closed #7948

**Comment by tk0miya** [comment]
Okay, I'll try to fix this if I have time until the next release.

**Comment by Chilipp** [comment]
Absolutely great! Thanks a lot @tk0miya!
