### ISSUE TITLE
Running LinkCheck on Git Diff

### ISSUE THREAD

**Issue by Daltz333** [sphinx-doc/sphinx#8046]
This would be useful to avoid websites blocking us (CI) because we're pinging the same URL many many times.

The reason I brought this issue up, is it seems websites are blocking our CI linkcheck, causing us to consistently exclude URLs, even though these URLs should be checked.

**Comment by Daltz333** [comment]
We are thinking of doing full link-checks on merge (to determine if websites broke), and do a smaller git-diff linkcheck on PR, to verify a change is actually valid.

**Comment by tk0miya** [comment]
I can't imagine how Sphinx will do it. Contribution is welcome :-)

**Comment by Daltz333** [comment]
We ended up creating an extension to do it here: 
https://github.com/wpilibsuite/sphinxext-linkcheckdiff

**Comment by Daltz333** [comment]
I am closing this issue as resolved. Our extension fits out use-case, and is open for contribution if anyone else wants to adapt it.
