### ISSUE TITLE
xpending ref error when using getpass in python notebook cell

### ISSUE THREAD

**Issue by doutriaux1** [sphinx-doc/sphinx#8059]
**Describe the bug**
I'm using nbsphinx to render my notebooks. Unfortunately since introducing a notebook asking for a password with getpass I get an error

**To Reproduce**

Create a notebook with a cell containing this code

```python
# Let's ask for the password and setup ssh agent
import getpass
password = getpass.getpass()+"\n"
```

**Expected behavior**
The notebook is generated with "*" where the password was typed (as in the notebook)

**Screenshots**
notebook gen error:
```bash
Exception occurred:
  File "/g/g19/cdoutrix/miniconda3/envs/kosh/lib/python3.6/site-packages/sphinx/writers/html5.py", line 790, in unknown_visit
    raise NotImplementedError('Unknown node: ' + node.__class__.__name__)
NotImplementedError: Unknown node: pending_xref
The full traceback has been saved in /tmp/sphinx-err-m33kximb.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**Environment info**
- OS: [e.g. Unix/Linux/Mac/Win/other with version]
- Python version: 3.6.5
# packages in environment at /g/g19/cdoutrix/miniconda3/envs/kosh:
#
# Name                    Version                   Build  Channel
nbsphinx                  0.7.0              pyh9f0ad1d_0    conda-forge
sphinx                    3.0.3                      py_0    conda-forge
sphinx-autoapi            1.3.0              pyh9f0ad1d_0    conda-forge
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-dotnetdomain 0.4                        py_0    conda-forge
sphinxcontrib-golangdomain 0.2.0.dev0                 py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.3                      py_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.4                      py_0    conda-forge

**Comment by tk0miya** [comment]
I guess this is a bug of nbsphinx. So please report this to their project.
Thanks,
