### ISSUE TITLE
Migrate `questions` on new issues to Stackoverflow ?

### ISSUE THREAD

**Issue by yves-chevallier** [sphinx-doc/sphinx#8062]
Using Google Groups ten years ago was a great idea, but I think it would be nice to redirect the users having questions about sphinx to post their questions on https://stackoverflow.com/questions/tagged/python-sphinx

Would it be a good idea ?

![image](https://user-images.githubusercontent.com/52489316/89644568-7d8a0200-d8b8-11ea-83bb-8288a80b984d.png)

**Comment by tk0miya** [comment]
+0: SO is a well-known Q&A platform. So it's a nice proposal. But it would be better to post this to sphinx-users forum first. It should not be determined without community.
