### ISSUE TITLE
References to items in Python's os.path module do not expand to links

### ISSUE THREAD

**Issue by andy-maier** [sphinx-doc/sphinx#8083]
**Describe the bug**

When specifying a reference to any item in Python's `os.path` module, the reference is not expanded to a link

**To Reproduce**

1. Create an .rst file with the following content:

```
* Reference to ``os.path.expanduser()``: :func:`py:os.path.expanduser`
* Reference to ``collections.namedtuple()``: :func:`py:collections.namedtuple`
```

2. Generate docs with Sphinx.

The reference to `collections.namedtuple()` is properly expanded to a link, while the reference to `os.path.expanduser()` is not.

**Expected behavior**

References to any documented item from the Python library, including items in `os.path`, should properly expand to a link.

**Your project**

* Source: PR https://github.com/pywbem/pywbemtools/pull/715 - check out and build with `make builddoc`, then look at docs section "Appendix" -> "Special terms" -> "connections file" and find the unexpanded `expanduser()`.
* RTD build: At https://pywbemtools.readthedocs.io/en/latest/ - but this issue is not yet out there since our PR is not yet merged.

**Screenshots**

None

**Environment info**
- OS: macOS catalina
- Python version: 3.8.5
- Sphinx version: 3.2.0
- Sphinx extensions: sphinx.ext.autodoc, sphinx.ext.napoleon, sphinx.ext.intersphinx, sphinx.ext.extlinks, sphinx.ext.todo, sphinx.ext.coverage, sphinx.ext.viewcode, sphinx.ext.ifconfig, sphinx_git
- Extra tools: None

**Additional context**

None

**Comment by tk0miya** [comment]
It seems your conf.py contains two `intersphinx_mapping` (and latter one wins). Could you check this please?
https://github.com/pywbem/pywbemtools/blob/7d7c5065814a6a4827184d93dd6f96273c42f49b/docs/conf.py#L436-L440
https://github.com/pywbem/pywbemtools/blob/954813f5e9726fd84f348d0e98941e1c45d9bff5/docs/conf.py#L498-L501

**Comment by tk0miya** [comment]
I'm closing this now. Please feel free to reopen if you are still in the problem.
Thanks,
