### ISSUE TITLE
Highlight warn not the current node location 

### ISSUE THREAD

**Issue by yves-chevallier** [sphinx-doc/sphinx#8093]
In `writer/html5.py/visit_literal_block` we find this:

        highlighted = self.highlighter.highlight_block(
            node.rawsource, lang, opts=opts, linenos=linenos,
            location=(self.builder.current_docname, node.line), **highlight_args
        )

The good news is that it works in most cases. However if a node is moved during the build process, you'll get an error with the wrong document name as we use the `node.line`, but the current docname.

Wouldn't be better to use `node.source` and `node.line`?

**Comment by tk0miya** [comment]
I think `current_docname` is intentionally used here. Could you check `node.source` is working fine on dirhtml or singlehtml builders?

**Comment by yves-chevallier** [comment]
In either case (`html`, `dirhtml`, `singlehtml`, `latex`), `node.source` equals the absolute path of the file : 

    '/home/me/test-sandbox/other.rst'

The value of `self.builder.current_docname` is less verbose, it is 

    'other'

But the output is in either case the abs path and it work with all builders.

**Comment by tk0miya** [comment]
Ah, my last comment was wrong. Absolutely you're right. We have to use `location=node` instead of `current_docname`. It uses `node.source` internally.
