### ISSUE TITLE
autodoc uses a wrapper's signature for a decorated class

### ISSUE THREAD

**Issue by harupy** [sphinx-doc/sphinx#8105]
**Describe the bug**

`autodoc` uses a wrapper's signature for a decorated class.

**To Reproduce**

Branch: https://github.com/harupy/sphinx/tree/decorated-class

In `tests/roots/test-ext-autodoc/target/decorator.py`, add:.

```python

def deco(cls):
    _original_init = cls.__init__

    @wraps(_original_init)
    def wrapped(self, *args, **kwargs):
        _original_init(self, *args, **kwargs)

    cls.__init__ = wrapped
    return cls

@deco
class Bar2:
    def __init__(self, name=None, age=None):
        pass
```

In `tests/test_ext_autodoc.py`, add:

```python
@pytest.mark.sphinx('html', testroot='ext-autodoc')
def test_decorated_class(app):
    print(do_autodoc(app, 'class', 'target.decorator.Bar2'))
    raise Exception  # fails this test to see stdout
```

Then, run:

```
tox -e py37 tests/test_ext_autodoc.py::test_decorated_class
```

This outputs:

```
--- Captured stdout call ---
['', '.. py:class:: Bar2(*args, **kwargs)', '   :module: target.decorator', '']
```

**Expected behavior**

```
--- Captured stdout call ---
['', '.. py:class:: Bar2(self, name=None, age=None)', '   :module: target.decorator', '']
```

**Your project**
Link to your sphinx project, or attach zipped small project sample.

**Screenshots**

**Environment info**
- OS: [e.g. Unix/Linux/Mac/Win/other with version]
- Python version: [e.g. 3.7.1]
- Sphinx version: [e.g. 1.8.2]
- Sphinx extensions:  [e.g. sphinx.ext.autodoc, recommonmark]
- Extra tools: [e.g. Browser, tex or something else]

**Additional context**

- [e.g. URL or Ticket]

**Comment by harupy** [comment]
`ClassDocumenter` doesn't seem to set `follow_wrapped` to `True` when extracting a signature.

https://github.com/sphinx-doc/sphinx/blob/38b868cc0d0583d9a58496cd121f0bc345bf9eaa/sphinx/ext/autodoc/__init__.py#L1401

**Comment by harupy** [comment]
The same thing occurs here:

https://github.com/sphinx-doc/sphinx/blob/38b868cc0d0583d9a58496cd121f0bc345bf9eaa/sphinx/ext/autodoc/type_comment.py#L120-L122

This causes `type_sig` and `sig` to have different parameters and throw `KeyError` here:

https://github.com/sphinx-doc/sphinx/blob/38b868cc0d0583d9a58496cd121f0bc345bf9eaa/sphinx/ext/autodoc/type_comment.py#L125

**Comment by harupy** [comment]
@tk0miya Correct me if I'm wrong. It looks like just specifying `follow_wrapped=True` solves the issue. If so, I'd be happy to open a PR (that makes the change and adds some tests to verify it).

**Comment by tk0miya** [comment]
@harupy You're right! Could you make a PR, please? Additionally, cases of `__call__` and `__new__` are also needed to add `follow_wrapped=True`, I think. Could you check them too if possible?

**Comment by harupy** [comment]
@tk0miya Created a PR: https://github.com/sphinx-doc/sphinx/pull/8115 😄

**Comment by untitaker** [comment]
This issue prevents me from upgrading from 3.0 to 3.2.1, the bugfix by @harupy works perfectly.

**Comment by harupy** [comment]
@tk0miya Could you review #8115?
