### ISSUE TITLE
Make the "only" directive play nicer with lists

### ISSUE THREAD

**Issue by fpoirotte** [sphinx-doc/sphinx#8110]
Hi,

I would like for the ``only`` directive to play nicely with lists.

Using the following snippet:
```
foo:

* bar

.. only:: html

   * baz

* qux
```
results in the following HTML code when building with the html builder:
```
<p>foo:</p>
<ul class="simple">
<li>bar</li>
</ul>
<ul class="simple">
<li>baz</li>
</ul>
<ul class="simple">
<li>qux</li>
</ul>
```

Notice that 3 lists have actually been created from a single list in the source file.
I would like for the list's items to stay as one list, as if the ``only`` directive had never been there in the first place, i.e.
```
<p>foo:</p>
<ul class="simple">
<li>bar</li>
<li>baz</li>
<li>qux</li>
</ul>
```
Same would be true for other builders.

I've also considered using this alternate syntax:
```
toto:

* tata

*
  .. only:: html
  
     titi

* tutu
```
This does result in the expected output when the tag is defined, but results in an empty bullet item when it is not:
```
<p>toto:</p>
<ul class="simple">
<li>tata</li>
<li></li>
<li>tutu</li>
</ul>
```

I also tried using the ``ifconfig`` directive instead, to no avail. If this feature gets implemented, it might be worth to support it in ``ifconfig`` too.

Best regards,
François

**Comment by tk0miya** [comment]
Unfortunately, it is difficult to support this. Please surround whole of the list by ifconfig directive. Sorry.
