### ISSUE TITLE
"Invalid C declaration" on C function with macro after function arguments

### ISSUE THREAD

**Issue by protobits** [sphinx-doc/sphinx#8114]
**Describe the bug**
I have a C function definition with a trailing macro which specifies the function as "noreturn" and this gives an error during build, even when this keyword is defined in `c_id_attributes`.

**To Reproduce**
I have the following on an RST:

    .. c:function:: void up_exit(int status) noreturn_function;

And this on the config:
<pre>
c_id_attributes = [
  'FAR',
  'CODE',
  'noreturn_function'
]
</pre>

And during build I get:

<pre>
/home/v01d/coding/nuttx_docs/nuttx/doc/reference/os/arch.rst:225: WARNING: Invalid C declaration: Expected end of definition. [error at 25]
  void up_exit(int status) noreturn_function;
  -------------------------^
</pre>

**Expected behavior**
The macro should be ignored while parsing the function declaration.

**Your project**
https://github.com/v01d/incubator-nuttx/tree/docs/doc

**Environment info**
- OS: Ubuntu 20.04
- Python version: 3.8.2
- Sphinx version: 3.1.2
- Sphinx extensions:  sphinx.ext.autodoc, recommonmark

**Comment by jakobandersen** [comment]
Thanks! Attributes can appear in many different places, and parsing of them was simply not added to this position. It should be in the next version (#8078), so your code should work then.
Note though that custom attributes are not ignored by the parser, but are rendered in the output.
