### ISSUE TITLE
Support for PEP 582 (Python local packages directory)

### ISSUE THREAD

**Issue by noritada** [sphinx-doc/sphinx#8129]
**Is your feature request related to a problem? Please describe.**
I am using [Pyflow](https://github.com/David-OConnor/pyflow), which implements [PEP 582 (Python local packages directory)](https://www.python.org/dev/peps/pep-0582/), for documentation built with Sphinx and find some warnings like this in building the document:

```
/path/to/doc/dir/__pypackages__/3.8/lib/sphinx/ext/autosummary/templates/autosummary/base.rst:3: WARNING: Error in "currentmodule" directive:
maximum 1 argument(s) allowed, 3 supplied.
```

**Describe the solution you'd like**
Since the cause of above-mentioned errors is that `.rst` files in the local packages directory are detected in searching for documentation source files, I consider that it would be nice if these files are **automatically** ignored.

**Describe alternatives you've considered**
Since putting that directory into `exclude_patterns` in `conf.py` can solve this issue in user side, exclusion based on user configuration is another solution.  In that case, it may be nice to provide that directory as one of default entries of that configuration.

**Additional context**
Since this is an easy issue and I already have a fix in my environment, I can submit a PR immediately.  However, I'd like to confirm the direction beforehand here.

**Comment by noritada** [comment]
I missed that this PEP is just a draft as of now.  So, it might be too early.

**Comment by tk0miya** [comment]
Thank you for proposal. But, as you said, it's too early to implement it because PEP-582 is still in draft. So please propose again after it accepted.

**Comment by noritada** [comment]
OK. I understand.  Thank you very much for your reply.
