### ISSUE TITLE
Got an error while generating a docx output in Sphinx

### ISSUE THREAD

**Issue by ketansevekari** [sphinx-doc/sphinx#8133]
1. Installed the sphinx-docxbuilder from https://pypi.org/project/sphinx-docxbuilder/
2. Added 'sphinx-docxbuilder' to 'extensions' in conf.py
3, Ran the following command to generate the documentation
**sphinx-build -b docx docs output**

But, got the following error:
_Exception occurred:
  File "/usr/local/lib/python3.7/site-packages/sphinx-docxbuilder/builder.py", line 69, in write
    self.info(bold('preparing documents... '), nonl=True)
AttributeError: 'DocxBuilder' object has no attribute 'info'_

**Comment by tk0miya** [comment]
Unfortunately, the builder uses removed API. Please post an issue to their project. Thanks,
