### ISSUE TITLE
Link in search result is broken with link_suffix = undefined

### ISSUE THREAD

**Issue by kenoss** [sphinx-doc/sphinx#8138]
**Describe the bug**

With recent sphinx release, links of search result https://idein.github.io/actfw-docs/1.3.9/search.html?q=CommandServer&check_keywords=yes&area=default are broken like https://idein.github.io/actfw-docs/1.3.9/actfwundefined?highlight=commandserver#actfw.command_server.CommandServer .

With old release, we got correct links https://idein.github.io/actfw-docs/1.3.5/search.html?q=CommandServer&check_keywords=yes&area=default

**To Reproduce**

We generated those pages with [this CI](https://github.com/Idein/actcast-app-python/blob/master/.circleci/config.yml#L35).  
[The above 1.3.9 doc is generated by sphinx 3.2.1.](https://app.circleci.com/pipelines/github/Idein/actcast-app-python/157/workflows/38db9b99-5cb2-48e7-8f36-c270f5777f2f/jobs/147/parallel-runs/0/steps/0-102)

**Expected behavior**
Generate correct link.

**Your project**
N/A

**Screenshots**
N/A

**Environment info**
- OS: Linux
- Python version: 3.6
- Sphinx version: 3.2.1
- Sphinx extensions:  sphinx_theme
- Extra tools: N/A

**Additional context**

I'm willing to fix this but I'm stuck.

Here, `DOCUMENTATION_OPTIONS.LINK_SUFFIX` is undefined.

https://github.com/sphinx-doc/sphinx/blob/3.x/sphinx/themes/basic/static/searchtools.js#L268

`DOCUMENTATION_OPTIONS` comes from here.

https://github.com/Idein/actfw-docs/blob/master/1.3.9/search.html#L187-L194

If my understanding is correct, this is generated by

https://github.com/sphinx-doc/sphinx/blob/3.x/sphinx/themes/basic/layout.html#L91

But `documentation_option.js` seems to be correct.

https://github.com/Idein/actfw-docs/blob/master/1.3.9/_static/documentation_options.js

Any ideas? Or let me know how can I investigate this.

**Comment by tk0miya** [comment]
It seems your website uses `sphinx_theme`. But it does not inherit our basic theme. And it does not import `documentation_options.js`. I suppose the theme does not support the recent versions of Sphinx (maybe 1.8+ or 2.0+). Please update it or migrate to other themes.

**Comment by kenoss** [comment]
Thanks for helpful information.  I'll try that.

**Comment by jessegv** [comment]
@kenoss Were you able to resolve this?  I have the same problem, and having a hard time trying to figure out how to update my theme.

**Comment by jessegv** [comment]
I just figured it out.  I had to make the following change in my layout.html in my theme:

```
-    <script type="text/javascript">
-        var DOCUMENTATION_OPTIONS = {
-            URL_ROOT:'{{ url_root }}',
-            VERSION:'{{ release|e }}',
-            COLLAPSE_INDEX:false,
-            FILE_SUFFIX:'{{ '' if no_search_suffix else file_suffix }}',
-            HAS_SOURCE:  {{ has_source|lower }}
-        };
-    </script>
+    <script id="documentation_options" data-url_root="{{ url_root }}" src="{{ pathto('_static/documentation_options.js', 1) }}"></script>
```
Hopefully that can help someone else.
