### ISSUE TITLE
Add option to c:alias to alias structure contents

### ISSUE THREAD

**Issue by Shamino0** [sphinx-doc/sphinx#8141]
Thank you very much for the `c:alias` directive.  It allows me to copy bits and pieces from my Doxygen-generated contents (produced using Breathe) to other locations in my document without breaking the links to the definitions.

For functions and macros, the alias is just what I want - I get the symbol, the return value and the parameters.

When displaying an alias of a struct, however, all I see is the name of the struct.  This isn't terribly useful - it's no better than a ``:c:struct:`foo_t` `` statement.

Would it be possible to add an option to `c:alias` so the list of the fields could be displayed with the structure name itself?

For example:
~~~~
.. c:struct:: Data

   .. c:var:: int a

   .. c:var:: double b

Assorted text here

.. c:alias:: Data
   :members:

More random text

.. c:alias:: Data
~~~~

Rendering as:

> struct **Data**
> &nbsp;&nbsp; int **a**
> &nbsp;&nbsp; double **b**
>
> Assorted text here
>
> struct **Data**
> &nbsp;&nbsp; int **a**
> &nbsp;&nbsp; double **b**
>
> More random text
>
> struct **Data**

**Comment by jakobandersen** [comment]
Good idea!
