### ISSUE TITLE
Code Readable definitions of Sphinx directives and roles

### ISSUE THREAD

**Issue by kreuzberger** [sphinx-doc/sphinx#8154]
Hi!

I am currently developing a Sphinx Editor Plugin. I would like to improve Code Completion for directive and roles and therefore have to define them in a computer readable way. Currently i use XML, but also JSON or other formats are ok.

Should there be a "general" valid format defined by the project, to support the Sphinx Ecosystem? This could but must not include

* Definition of directives, roles and their options
* Oneliner descriptions 
*  A "link page definition" to the extension index page for online help support

And further more. Idea is to have several files, for each extension one e.g. and a main Sphinx and RestructuredText File.

Or is there something similar available and i have not found it?

**Comment by tk0miya** [comment]
>Definition of directives, roles and their options
>Oneliner descriptions

I think we can use directive classes and role functions themselves. They have their behaviors as their attributes; arguments, options, content acceptable or not, description (as docstring), and so on. Unfortunately, there is no way to list them up.

>A "link page definition" to the extension index page for online help support

At present, there is no such information at runtime.
