### ISSUE TITLE
manpage role display as a <em> label

### ISSUE THREAD

**Issue by cathaysia** [sphinx-doc/sphinx#8155]
**Describe the bug**

I try use this role:

```shell
:manpage:`semanage(8)`
```
I think this code should became a url, but a <em> label instead.

**To Reproduce**
```
make.bat html
```

**Expected behavior**
manpage role beacme a url.

**Your project**
[new.zip](https://github.com/sphinx-doc/sphinx/files/5136932/new.zip)

**Screenshots**

![图片](https://user-images.githubusercontent.com/42114817/91454623-c9c2d380-e8b3-11ea-966d-0fef331280c5.png)

**Environment info**
- OS: Win10 2004
- Python version:  3.8.5
- Sphinx version: 3.2.1
- Sphinx extensions:  sphinx-materialdesign-theme, recommonmark, sphinxcontrib.plantuml

- Extra tools: vsode, powershell

**Additional context**

- [e.g. URL or Ticket]

https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html

This issue is produce even through I use the default theme.

**Comment by tk0miya** [comment]
The `manpage` role will be rendered as a hyperlink only if you set `manpages_url` config value. It seems your example does not set it. Please check your settings again.
Thanks,
