### ISSUE TITLE
Syntax highlighting skipped on literal_block with custom exceptions traceback

### ISSUE THREAD

**Issue by thepabloaguilar** [sphinx-doc/sphinx#8156]
**Describe the bug**
When we have a docstring with traceback example with the last line containing something similar to `lib.example.something` Sphinx warning about and don't highlight that piece of code

**To Reproduce**
```
$ git clone git@github.com:dry-python/returns.git
$ cd returns
$ poetry install
$ cd docs
$ make html
```

Code example:

```python
class IOResult:
    def unwrap(self) -> IO[_ValueType]:
        """
        Example.

        .. code:: pycon

          >>> from returns.io import IO, IOFailure, IOSuccess
          >>> assert IOSuccess(1).unwrap() == IO(1)

          >>> IOFailure(1).unwrap()
          Traceback (most recent call last):
            ...
          returns.primitives.exceptions.UnwrapFailedError

        """
```

If we remove the line `returns.primitives.exceptions.UnwrapFailedError` everything works fine, or if we change the line to `Something: returns.primitives.exceptions.UnwrapFailedError`

___PS___: I tried to change `pycon` to `python`, I got no success too!

**Expected behavior**

Sphinx should can highlight that code.

**Your project**

[returns](https://github.com/dry-python/returns)

**Environment info**
- OS: Linux 5.7.9-1-MANJARO
- Python version: 3.8.3
- Sphinx version: 3.1.1
- Sphinx extensions: 
```text
sphinx.ext.autodoc
sphinx.ext.doctest
sphinx.ext.todo
sphinx.ext.coverage
sphinx.ext.viewcode
sphinx.ext.autosummary
sphinx.ext.napoleon
m2r
sphinx_autodoc_typehints
sphinxcontrib.mermaid
hoverxref.extension
```

---

related issue https://github.com/dry-python/returns/issues/568

**Comment by tk0miya** [comment]
It seems your code block is not a valid "pycon" code. The pygments fails to highlight it without error.
```
$ cat pycon.txt
>>> from returns.io import IO, IOFailure, IOSuccess
>>> assert IOSuccess(1).unwrap() == IO(1)

>>> IOFailure(1).unwrap()
Traceback (most recent call last):
  ...
returns.primitives.exceptions.UnwrapFailedError
```
```
$ cat pycon.txt | pygmentize -l pycon -F raiseonerror

*** Error while highlighting:
pygments.filters.ErrorToken: r
   (file "/Users/tkomiya/work/tmp/lib/python3.8/site-packages/Pygments-2.6.1-py3.8.egg/pygments/filters/__init__.py", line 196, in filter)
*** If this is a bug you want to report, please rerun with -v.
>>> from returns.io import IO, IOFailure, IOSuccess
>>> assert IOSuccess(1).unwrap() == IO(1)

>>> IOFailure(1).unwrap()
Traceback (most recent call last):
  ...
```

I guess you'd seen a warning about highlightation. To do it forcedly, please use `code-block` directive instead and pass `:force:` option to it:
```
.. code-block:: pycon
  :force:

  >>> from returns.io import IO, IOFailure, IOSuccess
  >>> assert IOSuccess(1).unwrap() == IO(1)

  >>> IOFailure(1).unwrap()
  Traceback (most recent call last):
    ...
  returns.primitives.exceptions.UnwrapFailedError
```

Then the code-block will be highlighted as possible.

Note: Some CSS customize is needed to hide the highlightation error.
