### ISSUE TITLE
Markdown syntax documentation file fails to create HTML and contains garbage tags in HTML file.

### ISSUE THREAD

**Issue by Sameeranjoshi** [sphinx-doc/sphinx#8168]
**Describe the bug**
Markdown syntax documentation file fails to create HTML and contains garbage tags in HTML file.

**To Reproduce**
Consider an .md file like
```
<!--===- docs/ArrayComposition.md 
  
   Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
   See https://llvm.org/LICENSE.txt for license information.
   SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
  
-->

Some more details of documentation here.
```
This file is build using SPHINX tool.
The error is mentioned in more detailed in below link
https://reviews.llvm.org/D86131#2247275

**Expected behavior**
The sphinx tool should not give garbage values in html files.

**Your project**
llvm-compiler flang 

**Environment info**
- OS: Linux
- Sphinx extensions:  [e.g. recommonmark]
- Firefox, Edge

**Comment by tk0miya** [comment]
Sphinx core does not support markdown format as input. I guess you're using 3rd party's extension to do that. So please report this to their project. Thanks,

Note: I guess blank lines might cause this problem. Some kinds of markdown processors does not accept blank lines inside HTML block.
