### ISSUE TITLE
pxjahyper loaded even when latex_engine is not platex

### ISSUE THREAD

**Issue by andreyv** [sphinx-doc/sphinx#8169]
Since 6c324be96b936c619eb51ce5973ce58fb663df12
```tex
\usepackage{pxjahyper}
```
is added to the generated LaTeX document when `language` is `ja`. However, it is also loaded when `latex_engine` is not the default `platex`, but, for example, `xelatex`.

The `pxjahyper` package has
```tex
\NeedsTeXFormat{pLaTeX2e}
```
and loading it with XeLaTeX results in
```
! LaTeX Error: This file needs format `pLaTeX2e'
               but this is `LaTeX2e'.
```

**Comment by tk0miya** [comment]
Absolutely. Thank you for reporting.
