### ISSUE TITLE
Python 3.8.5 renders '**irc.abort**' as invisible: '<strong></strong>'

### ISSUE THREAD

**Issue by SwissalpS** [sphinx-doc/sphinx#8173]
Python 3.8.5 renders `'**irc.abort**'` as invisible: `'<strong></strong>'`

But `'**sirc.abort**'` is rendered correctly as: `'<strong>sirc.abort</strong>'`

Somehow newer python seems to detect `'**i'` as something special. I have
tried escaping with `'**\i'` without success.

**To Reproduce**
Steps to reproduce the behaviour are described in readme of
https://github.com/SwissalpS/sphinxBugIsolation

**Expected behaviour**
`'**irc.abort**'`  ->  `'<strong>irc.abort</strong>'`
just like:
`'**sirc.abort**'` -> `'<strong>sirc.abort</strong>'`

**Your project**
https://github.com/SwissalpS/sphinxBugIsolation

**Screenshots**
what it should look like: https://i.imgur.com/hYn7flQ.png

**Environment info**
- OS: Linux Fedora 32
- Python version: 3.8.5
- Sphinx version: 3.2.1
- Sphinx extensions:  exhale, breathe, groundwork
- Extra tools: [Browser]

**Additional context**
Seems to be Python version related.

@6r1d Thanks for testing on your system.

**Comment by tk0miya** [comment]
Are you saying old pythons are working fine?

**Comment by SwissalpS** [comment]
yes, seems so. We have only tested the two versions mentioned in readme and foo.cpp.

Of course it could be a number of other things, I guess.

**Comment by 6r1d** [comment]
I'm interested in isolating the bug. I'm (still) using Ubuntu 18.04.5 LTS, so there's something that shows a different behavior. Any ideas about finding the package causing it? P.S.:

    $ python3 -V
    Python 3.6.9

**Comment by jakobandersen** [comment]
I'm pretty sure this is not a C++ domain problem, and I think there is a high chance that the problem is somewhere in Doxgen/Breathe. From the Doxgen XML (``namespaceSwissalpS_1_1FooTest_1_1IRC.xml``):

```xml
        ...
        <briefdescription>
<para>called from lua by <bold>core.abort</bold>(iNumber) as <bold><ulink url="irc.abort">irc.abort</ulink></bold>(iNumber) </para>
        </briefdescription>
        ...
        <briefdescription>
<para>called from lua by <bold>core.bort</bold>(iNumber) as <bold>sirc.abort</bold>(iNumber) </para>
        </briefdescription>
        ...
        <briefdescription>
<para>called from lua by <bold>core.ort</bold>(iNumber) <bold>as <ulink url="irc.abort">irc.abort</ulink></bold>(iNumber) </para>
        </briefdescription>
        ...
```
I guess there is an issue with how the ``ulink`` tag is handled. Please open an issue over at Breathe.
