### ISSUE TITLE
Sphinx parallel build error on C++20 concepts

### ISSUE THREAD

**Issue by mpusz** [sphinx-doc/sphinx#8184]
```
Sphinx parallel build error:
sphinx.util.cfamily.DefinitionError: Invalid C++ declaration: Expected identifier in nested name, got keyword: constexpr [error at 78]
  template<Quantity To, typename D, typename U, typename Rep> requires constexpr QuantityOf< To, D > auto quantity_cast (const quantity< D, U, Rep > &q)
```

The full log can be found here: https://travis-ci.com/github/mpusz/units/builds/183406029.

Sphinx (or Breathe) does not like the `Concept auto funcion_name()` syntax and crashes the build.

**To Reproduce**

To reproduce this and many other C++20-related problems you can try to build the documentation for https://github.com/mpusz/units. The build instructions can be found here: https://mpusz.github.io/units/usage.html#contributing-or-just-building-all-the-tests-examples-and-documentation.

Please note that in order for CI to stop crashing I had to move `reference` folder to `docs_disabled` folder. In order to reproduce, please copy its contents to `docs`.

**Comment by jakobandersen** [comment]
I think there are multiple problems:

- It looks like the declaration got garbled somewhere in Doxygen/Breathe: the ``constexpr`` of the function is in the middle of the requires clause. I recommend trying to find the Doxygen xml for the declaration and open an issue over at Breathe.
- The adjective syntax is not yet supported in Sphinx (I don't know the status of Doxygen (nor Breathe)), though I don't think that is used in this example.
- (I tried to follow your build instructions but I couldn't run ``cmake``. It detected the Canon-installed Doxygen, but it seems that the ``doxygen`` executable doesn't have correct linker paths:
  ```
  $HOME/.conan/data/doxygen/1.8.18/_/_/package/4db1be536558d833e52e862fd84d64d75c2b3656/bin/doxygen: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
  ```

**Comment by mpusz** [comment]
@jakobandersen, thanks for the quick answer. The `constexpr` issue is somewhere in the documentation tools. The source code is correct: https://github.com/mpusz/units/blob/master/src/include/units/quantity_cast.h.

 Yeah, doxygen in Conan is broken: `sudo apt install libtinfo5`.

It would be awesome if you could try generating documentation of `mp-units` in your environment. There are lots of C++20-related issues with the documentation generation toolchain right now. If you could help me resolve some of those it would be great. In case of any further issues please do not hesitate to reach me. I deeply care to help you to setup this.

**Comment by mpusz** [comment]
BTW, in a week from now, I will talk on CppCon 2020 about my library and provide links to the generated documentation https://mpusz.github.io/units/index.html. Lots of C++ engineers will get there after the talk :-)
