### ISSUE TITLE
The :name: option for container directives in the top-level rST file is not properly handled

### ISSUE THREAD

**Issue by brechtm** [sphinx-doc/sphinx#8196]
The [documentation](https://docutils.sourceforge.io/docs/ref/rst/directives.html#container) for the container directive mentions that it accepts the `:name:` option. However, this doesn't work for containers in the top-level reStructuredText file. When :name: is supplied, the container node's 'names' attribute is empty and 'name' followed by the supplied name are added to the 'classes' attrribute instead. Containers in other files (referenced in the toctree) seem to properly handle the `:name:` option.

Example index.rst:

~~~rst
Welcome to Minimal Sphinx Project's documentation!
==================================================

.. container:: container-1
   :name: cnt1

  Paragraph in a container before top-level toctree.


.. toctree::
   :maxdepth: 2
   :caption: Contents:

   bla


.. container:: container-2
   :name: cnt2

  Paragraph in a container after top-level toctree.
~~~

After `sphinx-build -b pseudoxml . _pseudoxml`, results in index.pseudoxml:

~~~
<document source="/Users/brechtm/Documents/Code/rinohtype/tests_regression/sphinx_minimal/index.rst">
    <section ids="welcome-to-minimal-sphinx-project-s-documentation" names="welcome\ to\ minimal\ sphinx\ project's\ documentation!">
        <title>
            Welcome to Minimal Sphinx Project’s documentation!
        <container classes="container-1 name cnt1">
            <paragraph>
                Paragraph in a container before top-level toctree.
        <compound classes="toctree-wrapper">
            <compact_paragraph toctree="True">
                <caption>
                    Contents:
                <bullet_list>
                    <list_item classes="toctree-l1">
                        <compact_paragraph classes="toctree-l1">
                            <reference anchorname="" internal="True" refuri="bla">
                                ABC
        <container classes="container-2 name cnt2">
            <paragraph>
                Paragraph in a container after top-level toctree.
~~~

I would expect containers, also in the top-level file, to respect the `:name:` option.

**Environment info**
- Sphinx version: 3.2.1
- Python version: 3.8.3
- OS: macOS 10.13.6

**Comment by tk0miya** [comment]
It seems your mark-up has broken. Please add a space before the paragraph like this. The directive option and content should be at the same level.
```
.. container:: container-1
   :name: cnt1

   Paragraph in a container before top-level toctree.
```

**Comment by brechtm** [comment]
Oh god, I feel stupid now! 😞 
Thanks for pointing out the issue.

Though I guess that was easy to miss since there is no warning, and a bit surprising that `:name:` and `cnt1` end up in the list of classes. I'll check if this has been discussed on the docutils ML/tracker before...

**Comment by tk0miya** [comment]
In docutils parser, the input is recognized as following:

```
.. container:: container-1\n :name: cnt1

  Paragraph in a container before top-level toctree.
```

The `:name:` option is recognized as a part of the argument because the second line starts with space. Only non-indented option (a.k.a. field-list) or a blank line can break the argument list.
