### ISSUE TITLE
make.sh for Windows 10 WSL2 environment

### ISSUE THREAD

**Issue by CodeCox** [sphinx-doc/sphinx#8197]
**Is your feature request related to a problem? Please describe.**
`make.bat` fails in **WSL2-Ubuntu Windows 10** (after sucessfully running `sphinx-quickstart`) ie. I can't run `make html`  or `make clean`, etc. 

**Describe the solution you'd like**
The CLI is run in a bash shell on WSL2 so I need the `make.sh` version of the batch file? (Actually, a more comprehensive review  wrt supporting a WSL2 environment might be needed! )

**Describe alternatives you've considered**
- running on Windows 10 proper
- using `cmd.exe` to execute the `.bat` file, but unfortunately the paths are not recognised.
- `sphinx-build -b html sourcedir builddir` works in place of `make html`. Generally, the workaround is to use the equivalent `sphinx-build` form instead but I find this less intuitive eg. `make clean` vs `sphinx-build -E`

**Additional context**
`.bat` file execution is not currently supported in WSL2, however this may become possible in future versions since it is a known Microsoft issue.

**Comment by tk0miya** [comment]
I don't know WSL2 at all. But I guess you can use GNU make, right? If so, no `make.sh` is needed.

**Comment by CodeCox** [comment]
Thanks.
