### ISSUE TITLE
Please include eclipsehelp into standard distribution.

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#820]
Hi,

is it somehow possible to add the eclipsehelp builder to the official distribution of Sphinx: https://bitbucket.org/konrada/sphinx-extensions/src/2bf7e31f77b7/sphinx/builders/eclipsehelp.py

I just tested it with the recent version and it worked fine!

With best regards,
Tobias

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/820
- Originally reported by: [schlauch](https://bitbucket.org/schlauch)
- Originally created at: 2011-11-14T19:40:31.291

**Comment by shimizukawa** [comment]
_From Anonymous on 2011-12-29 08:25:36+00:00_

You will find really 100s of exercises available that will help you gain muscles and this can be done by doing bench presses, dead lifts or by utilizing hand weights. These workouts are the very best if this involves firming and strengthening the muscles.
nfl shop http://www.nfl-shops.com/
Cheap NFL Jerseys  http://www.nfl-shops.com/
NFL Jerseys http://www.nfl-shops.com/
nfl shop jerseys http://www.nfl-shops.com/
http://www.nfl-shops.com/san-francisco-49ers-jerseys-c-76.html

**Comment by tk0miya** [comment]
Recently our policy is making sphinx-core simple and smart.
So I'm closing this now.
Thanks,
