### ISSUE TITLE
Generate warning when toctree contains duplicate entries

### ISSUE THREAD

**Issue by jd41** [sphinx-doc/sphinx#8201]
**Is your feature request related to a problem? Please describe.**
I am now fixing a problem of this sort, on the TOC on the left page of a Sphinx HTML documentation, a part of the documentation was referenced twice.

**Describe the solution you'd like**
It would be nice if this could have been caught by a warning. I guess it's not an exceptionally pressing issue though.

**Comment by tk0miya** [comment]
+1: Reasonable.

**Comment by tk0miya** [comment]
I found this was already resolved by #8203 . Closing.
