### ISSUE TITLE
Incorrect spacing around tokens in C++

### ISSUE THREAD

**Issue by Chlorie** [sphinx-doc/sphinx#8212]
**Describe the bug**
Spacing around tokens are really inconsistent with C++ docs generated by sphinx.

**Current / Expected behavior**
Currently `const`, `noexcept`, `constexpr` and the like are categorized as properties of the function, and the properties have a space after them, like in `constexpr `. But sometimes these properties come after the function parameters, most people put spaces before those "postposition" modifiers like `constexpr int foo() const noexcept` not `constexpr int foo()const noexcept ` which is the current behaviour. Also this makes the gap between `const` and the type it modifies too big, like in `const  uint64_t`

Also, when the return type has reference link attached to it, it seems that the appropriate spaces around them are lost, that causes the return type to be concatenated with the function name, which is really not easy to the eyes, like in `constexpr Retfoo()` while `constexpr Ret foo()` is obviously the preferred output.

These issues are presented in the following screenshot.

![image](https://user-images.githubusercontent.com/34185634/93176756-51d62380-f764-11ea-97f6-3ed5420964b5.png)

**Environment info**
- OS: [e.g. Unix/Linux/Mac/Win/other with version]
- Python version: 3.7.1
- Sphinx version: 3.2.1
- Sphinx extensions:  [e.g. breathe]

**Comment by Chlorie** [comment]
Emmm this may be an issue of the ReadTheDocs theme, sorry for the inconvenience...

**Comment by jakobandersen** [comment]
Right, I tried to reproduce it but it looked nice. I guess it may be the CSS in the theme you are using?

**Comment by Chlorie** [comment]
> Right, I tried to reproduce it but it looked nice. I guess it may be the CSS in the theme you are using?

Yeah probably... I've found the right place to report this issue. Thanks anyways!
