### ISSUE TITLE
Translated HTML output also includes source content

### ISSUE THREAD

**Issue by ArtFlag** [sphinx-doc/sphinx#8217]
The translated HTML output does not only contain the content of the PO file for the given language but also the difference with the content of its matching rST file.

1. Generate the PO files from your source language and translate them. At this point, translation = source.
2. Update the rST file to add a new section at the top. Do not update the matching PO file. At this point, the source is ahead of the translation. Naturally the HTML output should be different.
3. Build to HTML with: 
    ```bash
    sphinx-build -a -E -D language='fr' $(SOURCEDIR) $(BUILDDIR)/html_$(lang) 
    ```
4. Notice that the new section of the rST file now appears in the translated output even though my PO file didn't change. 🔴 

Is this a bug or a feature? It sounds like a bug to me because I do not want to see any other language in whatever translation I build. 

If this is a feature, how can I avoid automatically adding the source content to my translation?
I'm happy to update the docs based on the answer.

**Environment info**
- OS: Mac
- Python version: 3.8.2
- Sphinx version: 3.1.2

**Comment by tk0miya** [comment]
The i18n feature of Sphinx is based on the merging model. It merged translations into the original content. It means no way to filter the untranslated content. So I don't have an idea for your request.

**Comment by ArtFlag** [comment]
Ok I wasn't aware of that and that changes things! I'll send a PR to improve the translation docs a little bit. Thanks!
