### ISSUE TITLE
Use LF for line endings in sphinx-apidoc also on windows

### ISSUE THREAD

**Issue by PhilippSelenium** [sphinx-doc/sphinx#8221]
**Is your feature request related to a problem? Please describe.**
We use windows and linux machines for development so when running sphinx-apidoc on windows or linux the .rst files are always created with different line endings LF vs CRLF.
See also: https://stackoverflow.com/questions/63888463/possibility-to-define-line-endings-in-sphinx-apidoc

**Describe the solution you'd like**
sphinx-apidoc only creates .rst files using LF also on Windows
**or**
sphinx-apidoc option to configure desired line ending

**Describe alternatives you've considered**
Running a script that converts all line endings to LF . But there must be a better way, right?

**Additional context**
I know that isort also had this problem but now they use LF everywhere

**Comment by cblegare** [comment]
In case you use git, it provides a way to convert them (see https://docs.github.com/en/free-pro-team@latest/github/using-git/configuring-git-to-handle-line-endings)

Else, if you don't commit the generated files, the different line ending should not mess with the built result.

If you do keep the generated files but do not use git for this purpose, you are indeed on your own.
