### ISSUE TITLE
Napoleon: Support NumpyDoc "Receives" docstring section

### ISSUE THREAD

**Issue by tcjennings** [sphinx-doc/sphinx#8236]
Support the "Receives" section of NumpyDoc guidelines; it is related to Yields, which is already supported.

https://numpydoc.readthedocs.io/en/latest/format.html#sections

   Receives

Explanation of parameters passed to a generator’s .send() method, formatted as for Parameters, above. Since, like for Yields and Returns, a single object is always passed to the method, this may describe either the single parameter, or positional arguments passed as a tuple. If a docstring includes Receives it must also include Yields.

**Comment by tk0miya** [comment]
Reasonable. It should be supported.
