### ISSUE TITLE
False "reference target not found" error when using optional arguments for dataclasses

### ISSUE THREAD

**Issue by robsan00** [sphinx-doc/sphinx#8237]
**Describe the bug**
When trying to define type hinting for optional arguments of a dataclass (type hint `typing.Union[int, None]`) and tell Sphinx to be nitpicky regarding references, I get an error: `WARNING: py:class reference target not found: NoneType`.

**To Reproduce**
Use the following simple dummy script:
```
import typing
from dataclasses import dataclass


def a(a: int, b: typing.Union[int, None]):
    pass


@dataclass
class A:
    a: int
    b: typing.Union[int, None]
```

together with the following config file:
```
extensions = ['sphinx.ext.autodoc']
source_suffix = '.rst'
master_doc = 'index'
nitpicky = True
```

**Expected behavior**
No error.

Actual behavior:
```
python -m sphinx rst dst
Running Sphinx v3.2.1
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 0 source files that are out of date
updating environment: 0 added, 1 changed, 0 removed
reading sources... [100%] src
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] src
C:\work\sphinx_bug\src\sphinx_bug.py:docstring of src.sphinx_bug.A:: WARNING: py:class reference target not found: NoneType
generating indices...  genindex py-modindexdone
writing additional pages...  searchdone
copying static files... ... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 1 warning.

The HTML pages are in dst.
```

**Environment info**
- OS: Win 10 64 bit
- Python version: 3.6.4
- Sphinx version: 3.2.1
- Sphinx extensions:  sphinx.ext.autodoc
- Extra tools: as I am using Python 3.6, I am using the dataclasses module (version 0.7)

**Additional context**
I first tried with Sphinx 3.1.2, and there got similar, but slightly different errors:
```
C:\work\sphinx_bug\src\sphinx_bug.py:docstring of src.sphinx_bug.A:: WARNING: py:class reference target not found: NoneType
C:\work\sphinx_bug\src\sphinx_bug.py:docstring of src.sphinx_bug.A.b:: WARNING: py:class reference target not found: typing.Union[int, None]
```
When using `typing.Union[int, str]` instead, it works fine. The function in the example also works. It's only the `None`, that does not work here (it works again, if I define `None` as default value).

**Comment by tk0miya** [comment]
In python 3.7 and 3.8, the docstring of dataclass contains wrong reference `NoneType`. By default, this docstring changes the signature of the class because of autodoc_docstring_signature is enabled. As a result, it causes the reported warning.
```
$ python3.7
Python 3.7.9 (default, Sep  8 2020, 12:48:11)
[Clang 11.0.3 (clang-1103.0.32.62)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import example
>>> example.A.__doc__
'A(a: int, b: Union[int, NoneType])'
```
```
$ python3.8
Python 3.8.6 (default, Dec 12 2020, 22:30:28)
[Clang 11.0.3 (clang-1103.0.32.62)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import example
>>> example.A.__doc__
'A(a: int, b: Union[int, NoneType])'
```

On the other hand, python 3.9 generates a correct docstring.
```
$ python
Python 3.9.1 (default, Dec 12 2020, 22:52:49)
[Clang 11.0.3 (clang-1103.0.32.62)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import example
>>> example.A.__doc__
'A(a: int, b: Optional[int])'
>>>
```

So I propose you to upgrade your python to the latest one. Or, please add docstrings to the dataclass as a workaround (then invalid signature will not be generated).

**Comment by xuhdev** [comment]
Thanks. Python 3.9 seems having fixed a lot of issues related to Sphinx :)
