### ISSUE TITLE
minor css issue on dark-themed desktop

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#824]
here is a screenshot from firefox on kde4 with a dark theme:
http://img802.imageshack.us/img802/326/sphinxwebsitedarktheme.png

The input boxes are rather ugly. 
I use sphinx-based theme for my website and I've added to my css:

```
input, textarea, select {
        color: #000;
        background-color: #fff;
}
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/824
- Originally reported by: Marcin Wojdyr
- Originally created at: 2011-11-19T16:22:58.227

**Comment by tk0miya** [comment]
What is "dark" theme?
AFAIK, it is not bundled theme.

Please reopen if you are still in trouble.
