### ISSUE TITLE
extension error when using metadata with parallel-read

### ISSUE THREAD

**Issue by rscohn2** [sphinx-doc/sphinx#8256]
The notfound extension gets an error when using parallel read. It is described here:
https://github.com/readthedocs/sphinx-notfound-page/issues/111

Can you look it over to see if it should be safe to use metadata and parallel read together?

**Comment by jakobandersen** [comment]
It looks to me like the ``OrphanMetadataCollector`` class does not implement all necessary methods. In particular the ``merge_other`` method is needed when running in parallel (https://github.com/sphinx-doc/sphinx/blob/3.x/sphinx/environment/collectors/__init__.py#L55).

**Comment by rscohn2** [comment]
I will fix the problem in the extension. Thanks.
