### ISSUE TITLE
Documentation of admissible characters in "replace"/substitution

### ISSUE THREAD

**Issue by jd41** [sphinx-doc/sphinx#8267]
I am sorry, I guess a better place to post would be the docutils mailing list, but I would need to post there with my full e-mail address and full name.

https://docutils.sourceforge.io/docs/ref/rst/directives.html#directives-for-substitution-definitions doesn't specify which characters are allowed within `|substitution definitions|`. As a result, there are some inconsistencies in RST tools. For example, |qq'q| is not recognized by kate syntax highlighting (`.. |qq'q| replace:: onemorerep` gets rendered like a comment), but it seems to work with sphinx.

Is it correct that all characters except | work? If yes, it would be nice for my use case (a glossary with hoverxref, where I want to specify `|the correct links for the term's genitive case etc.|`).

I'd then also like to suggest making this explicit in the documentation. But this is not the right place, I guess.

**Comment by tk0miya** [comment]
I can't understand why do you post this to here in spite of here is not an appropriate place. What do you expect to Sphinx maintainers? Posting this instead of you? Fix docutils instead of docutils team? Please let me know what we should do.

**Comment by jd41** [comment]
Yes, point taken. My actual understanding of which program does what with the documentation is less than 100% clear. My only question is then: Does rendering the stuff with sphinx break anything that would work from the docutils side, for any character?

**Comment by tk0miya** [comment]
About reST parsing, what Sphinx does is only invoking the reST parser module of docutils. So we don't know how docutils parses text at all.

**Comment by jd41** [comment]
Alright, thanks. Sorry for writing here again.
