### ISSUE TITLE
Cannot use asterisk emoji with Sphinx and without warnings?

### ISSUE THREAD

**Issue by Peque** [sphinx-doc/sphinx#8276]
**Describe the bug**

If I use an asterisk emoji character in my documentation (`*️⃣`) then Sphinx will complain with a warning:

```
WARNING: Inline emphasis start-string without end-string.
```

That is because it is interpreting the character as a separate asterisk plus something else.

**To Reproduce**

Add a `*️⃣` character to your documentation. Example index file:

```
Asterisk emoji
==============

*️⃣
```

**Expected behavior**

No warnings are thrown.

**Environment info**

- OS: Linux (Fedora 32)
- Python version: 3.8.5
- Sphinx version: 3.2.1
- Sphinx extensions:  sphinxemoji.sphinxemoji

**Comment by tk0miya** [comment]
Thank you for reporting. But this is a bug of docutils (a reST parser which Sphinx uses internally). Could you report this into docutils project?

Reproducing the error with docutils' rst2html.py:
```
$ cat test.rst
Asterisk emoji
==============

*️⃣
$ rst2html.py test.rst > /dev/null
test.rst:4: (WARNING/2) Inline emphasis start-string without end-string.
```

**Comment by Peque** [comment]
@tk0miya Sure: https://sourceforge.net/p/docutils/bugs/405/

Long time since the last time I interacted with an SVN project in SourceForge! :joy:

**Comment by tk0miya** [comment]
Good work :-)
