### ISSUE TITLE
No way to specify `--no-sep` in `sphinx-quickstart`

### ISSUE THREAD

**Issue by webknjaz** [sphinx-doc/sphinx#8298]
**Describe the bug**

You can pre-fill project generation question answers when you run something like `python -m sphinx.cmd.quickstart`. For example, for omitting Makefile, you'd just specify `--no-makefile`.

But for `--sep` it does not work like that and it needs to be fixed.

**To Reproduce**

This happens without the arg:
```console
$ python -m sphinx.cmd.quickstart
[...]
> Separate source and build directories (y/n) [n]:
```

This 
```console
$ python -m sphinx.cmd.quickstart --sep
```
chooses "y" automatically.

And there's no way to choose "n" automatically.

**Expected behavior**

Have `--no-sep` disabling dir separation.

**Your project**

N/A

**Screenshots**

N/A
**Environment info**

N/A

**Additional context**

N/A

**Comment by andres-fr** [comment]
+1! A quick workaround would be something like (untested):

```python
import sphinx.cmd.quickstart as sphinx_quickstart
quickstart_argv = ["-q", "-p", PACKAGE_NAME, "-a", AUTHOR,
                   "--ext-autodoc", "--ext-imgmath", "--ext-viewcode",
                   "--ext-githubpages", "-d", "version="+VERSION,
                   "-d", "release="+VERSION, OUT_DIR]
sphinx_quickstart.main(argv=quickstart_argv)
```
