### ISSUE TITLE
Only load a JS / CSS file on certain pages?

### ISSUE THREAD

**Issue by choldgraf** [sphinx-doc/sphinx#8302]
Many extensions use a javascript file that is only relevant on certain pages (e.g. if a certain directive is called). However, thus far I haven't found a way to tell Sphinx to *only* add a JS / CSS file to a page under some condition. `app.add_js_file` adds it to all pages.

Does anyone know of a way to only add JS/CSS files to some pages but not all?

**Comment by mgeier** [comment]
Probably related: #6241.

**Comment by choldgraf** [comment]
I think that the pattern I'm going to use is to add the JS/CSS files as normal, and then add an `html-page-context` event listener to **remove** pages when they don't need the CSS/JS. See this comment for a code example of this:

https://github.com/sphinx-doc/sphinx/issues/6241#issuecomment-705070598

Going to close this issue as it is resolved for me, but others should feel free to re-open if they want a more "official" support for this.
