### ISSUE TITLE
Sphinx is not able to generate documentation from python files of gauge framework

### ISSUE THREAD

**Issue by Ramanpreet19** [sphinx-doc/sphinx#8305]
### Sphinx is not able to generate documentation from python files of gauge framework.
I am trying to generate documentation from .py files which are used in Gauge frame work. sphinx-apidoc is not able to parse python docstring. In my python file functions are defined as:-
```
\-------Hello_world.py------
@step("Function")
def function(val, key=None):
    """[summary]
    Args:
        val ([type]): [description]
        key ([type], optional): [description]. Defaults to None.
    Returns:
        [type]: [description]
    """    
    return val 
\----------end --------
```
and my generated .rst looks like 
```
\-------Hello_world.rst--------
hello\_world module
\===================
.. automodule:: hello_world
   :members:
   :undoc-members:
   :show-inheritance:
\---------
```

If I remove @step("Function") line then everything works fine, so my setup is clean. But I need @step("Function") line for my gauge frame work to run. 

I am using sphinx-apidoc 3.2.1 version.

Any leads would be helpful. Could you please help me with this.

**Comment by tk0miya** [comment]
Sorry for not respond you long. For decorators, you need to use `functools.wraps()` in the `@step` decorator to keep docstrings of decorated function.
