### ISSUE TITLE
make.bat in Windows doesn't work with pyenv-win due to weird Windows batch file behavior

### ISSUE THREAD

**Issue by mmaeusezahl** [sphinx-doc/sphinx#8308]
**Describe the bug**

I am using [pyenv-win](https://github.com/pyenv-win/pyenv-win) on Windows to switch between different python versions while developing. pyenv-win will replace all python script commands (including ```sphinx-build.exe```) with a batch file shim such that it can transparently switch between different python versions. This means that running the line

```
$ %SPHINXBUILD% >NUL 2>NUL
```

in the ```make.bat``` file will essentially run the ```sphinx-build.bat``` that in turn calls ```sphinx-build.exe``` and works.

The problem is that calling a batch file from a batch file [will then stop executing the original batch file](https://stackoverflow.com/a/13258451). In the case of sphinx-build this means that the check, whether sphinx-build is installed, succeeds but then terminates everything else with no error. The actual  build command a few lines below never gets executed.

I'm not sure if you would consider this a bug on the side of pyenv-win or sphinx, but I'm starting here since I first noted it while using sphinx. This (and the fact that the proposed fix is so simple) is the reason why I did not add a pull-request as well.

**Proposed fix**

I propose that ```call``` is added in front of all the ```%SPHINXBUILD%``` calls inside the ```sphinx\templates\quickstart``` templates.

I briefly tested this here in my local configuration and it seems to fix the problem. It moreover does work with pyenv-win *.bat shims as well as with the regular *.exe shims in a venv.

Please note that I'm not very familiar with batch files and just learned about this behavior today, so maybe someone should check whether this could trigger any other unwanted side effect? The SO thread I linked above mentions that in general adding call in front of an actual *.exe file won't do anything harmful but there might be some quirks with parameter expansion.

**To Reproduce**

First make sure that your are using pyenv-win on Windows.
```
$ pyenv version
```

Really any somewhat modern python version should work. **You can't use a venv or virtualenv** since this will replace the shims created by pyenv-win (and this is also the reason why I probably never saw this until recently). You must perform the following in your global pyenv-win python installation.

In the following demonstration I will be using the sphinx gallery demonstration https://github.com/sphinx-gallery/sample-project.

```
$ git clone https://github.com/sphinx-gallery/sample-project.git sample-project
$ cd sample-project
$ pip install -r requirements_doc.txt
$ pip install -e .
$ pyenv rehash
$ cd docs
$ make.bat html
```

Nothing (no error, **really nothing at all**) happens. This is also the fact that potentially makes this "bug" so confusing.

**Expected behavior**
I really expected that **something** happens ;)

**Your project**
Doesn't matter. This affects all projects.

**Environment info**
- OS: Windows

**Additional context**
- A SO thread explaining the different behavior of batch file processing when running commands *.exe and *.bat commands   https://stackoverflow.com/a/13258451

**Comment by tk0miya** [comment]
Unfortunately, there are no windows users in our team. So we can't ensure it working fine. But I'll merge it to Sphinx if you post a PR. Could you make a PR please?

**Comment by AA-Turner** [comment]
This seems a bug in `pyenv-win` -- their calling mechanism should be transparent. Closing here, as there is an aspiration to move away from Make.bat et al.

A
