### ISSUE TITLE
Consider removing old Sphinx documentation versions from Google search

### ISSUE THREAD

**Issue by choldgraf** [sphinx-doc/sphinx#8309]
A frustration that I often have with Sphinx is that Google search results consistently bring up (often very) old documentation pages for Sphinx.

For example, a recent search for `sphinx glob toctree` brought up *3 different Sphinx versions* as the top results:

![image](https://user-images.githubusercontent.com/1839645/95683633-665dde00-0ba1-11eb-8045-218bf3820b90.png)

The first result was from Sphinx 1.5.

I think this kind of thing confuses newcomers because they'll find themselves on an out-of-date page but don't realize that there's a newer version. It is also frustrating for current developers because they have to click-through multiple versions of a page before getting to the latest-documented version.

I believe that Sphinx is hosted on ReadTheDocs, and I believe they have support for hiding older versions of documentation (so they're still reachable but won't show up in search results). I think that Sphinx should consider hiding all documentation versions except for the last few releases, or hiding all but `stable/` and `latest/` from google searches.

I looked up in RTD how to do this, and found [this page on `hidden` versions](https://docs.readthedocs.io/en/stable/versions.html#hidden) and [this page on `robots.txt`](https://docs.readthedocs.io/en/stable/hosting.html#custom-robots-txt-pages) but not quite sure if those are the right pattern. Maybe @ericholscher or @stsewd have thoughts?

**Comment by stsewd** [comment]
Yeah, using hidden versions or a custom robots.txt is the solution. If you hide a version, it won't be listed here

![Screenshot_2020-10-11 Overview — Sphinx 4 0 0+ documentation](https://user-images.githubusercontent.com/4975310/95685064-3ae7ed00-0bbb-11eb-8f9c-b0ed08dbe446.png)

But they will still be listed here https://readthedocs.org/projects/sphinx/versions/ (maybe we should link to this page when there are hidden versions).

If you don't want that behavior, using a custom robots.txt should be fine.

**Comment by tk0miya** [comment]
+1: I feel old documents are not useful for users. What do you think? @shimizukawa @stephenfin

**Comment by shimizukawa** [comment]
Agreed. I think it's fine to show only the master and latest release versions, too.

For now, I've hidden 1.2-1.8, which I'm sure you won't object to by hiding them.
![image](https://user-images.githubusercontent.com/151623/98994292-ebf2f600-2572-11eb-8e9f-df3018c21322.png)

This operation on the ReadTheDocs also disables robots.txt.
https://www.sphinx-doc.org/robots.txt
```
User-agent: *

Disallow: /en/1.8/ # Hidden version

Disallow: /en/1.7/ # Hidden version

Disallow: /en/1.6/ # Hidden version

Disallow: /en/1.5/ # Hidden version

Disallow: /en/1.4/ # Hidden version

Disallow: /en/1.3/ # Hidden version

Disallow: /en/1.2/ # Hidden version

Sitemap: https://www.sphinx-doc.org/sitemap.xml
```

However, direct access to the hidden version is still valid. This will not break direct links to the old version from other sites.
(e.g. https://www.sphinx-doc.org/en/1.8/ )

If there are no other objections, I will also hide 2.0 on en and modify versions on other languages.

**Comment by xmo-odoo** [comment]
An other (possibly better) option is `<link rel="canonical">`, it doesn't prevent or stop search engines from indexing older versions of the documentations, and thus doesn't prevent users from finding them if they need to, however it would lead the non-canonical versions to "feed into" the canonical ones, and should lead search engine bots to favor crawling the canonical page.

**Comment by shimizukawa** [comment]
Actually, Sphinx official document on ReadTheDocs already have canonical url to "master".
e.g. https://www.sphinx-doc.org/en/1.8/ have `<link rel="canonical" href="http://www.sphinx-doc.org/en/master/index.html">`

**Comment by shimizukawa** [comment]
I'm going to hide 2.0 on en and modify versions on other languages.

**Comment by shimizukawa** [comment]
In progress....

**Comment by choldgraf** [comment]
Great! 🙂 perhaps one this is done, we should all try doing some google searches to see what links pop up? Maybe after a few days? I have no idea how search engines handle their indexing. The search term I used originally was “sphinx glob toctree”

**Comment by mgeier** [comment]
I don't know whether this is relevant, but just for the record: currently, the `canonical` URL is set twice, see https://github.com/readthedocs/readthedocs-sphinx-ext/issues/83. See also https://github.com/readthedocs/readthedocs-sphinx-ext/pull/93 and https://github.com/readthedocs/readthedocs.org/pull/7540.

**Comment by ericholscher** [comment]
I've confirmed the canonical issue is fixed now on a doc rebuild with our latest deploy. I've rebuilt the `master` branch of Sphinx, and it is looking good.

**Comment by shimizukawa** [comment]
Now `en` has `master` and `3.x` versions.
All other languages only have the `master` version.
![image](https://user-images.githubusercontent.com/151623/105569386-88602280-5d84-11eb-92ea-6ce9e8e49df7.png)

**Comment by shimizukawa** [comment]
I checked robots.txt and sitemap.xml and they look fine.

https://www.sphinx-doc.org/robots.txt
```
User-agent: *

Disallow: /en/2.0/ # Hidden version

Disallow: /en/1.8/ # Hidden version

Disallow: /en/1.7/ # Hidden version

Disallow: /en/1.6/ # Hidden version

Disallow: /en/1.5/ # Hidden version

Disallow: /en/1.4/ # Hidden version

Disallow: /en/1.3/ # Hidden version

Disallow: /en/1.2/ # Hidden version

Sitemap: https://www.sphinx-doc.org/sitemap.xml
```

https://www.sphinx-doc.org/sitemap.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xhtml="http://www.w3.org/1999/xhtml">
  
  <url>
    <loc>https://www.sphinx-doc.org/en/master/</loc>
    
    <xhtml:link
        rel="alternate"
        hreflang="ar"
        href="https://www.sphinx-doc.org/ar/master/"/>
    
    <xhtml:link
        rel="alternate"
        hreflang="ca"
        href="https://www.sphinx-doc.org/ca/master/"/>
    
    <xhtml:link
        rel="alternate"
        hreflang="de"
        href="https://www.sphinx-doc.org/de/master/"/>
    
    <xhtml:link
        rel="alternate"
        hreflang="ru"
        href="https://www.sphinx-doc.org/ru/master/"/>
    
    <xhtml:link
        rel="alternate"
        hreflang="es"
        href="https://www.sphinx-doc.org/es/master/"/>
    
    <xhtml:link
        rel="alternate"
        hreflang="fr"
        href="https://www.sphinx-doc.org/fr/master/"/>
    
    <xhtml:link
        rel="alternate"
        hreflang="it"
        href="https://www.sphinx-doc.org/it/master/"/>
    
    <xhtml:link
        rel="alternate"
        hreflang="ja"
        href="https://www.sphinx-doc.org/ja/master/"/>
    
    <xhtml:link
        rel="alternate"
        hreflang="ko"
        href="https://www.sphinx-doc.org/ko/master/"/>
    
    <xhtml:link
        rel="alternate"
        hreflang="pl"
        href="https://www.sphinx-doc.org/pl/master/"/>
    
    <xhtml:link
        rel="alternate"
        hreflang="pt-BR"
        href="https://www.sphinx-doc.org/pt_BR/master/"/>
    
    <xhtml:link
        rel="alternate"
        hreflang="sr"
        href="https://www.sphinx-doc.org/sr/master/"/>
    
    <xhtml:link
        rel="alternate"
        hreflang="zh-CN"
        href="https://www.sphinx-doc.org/zh_CN/master/"/>
    
    <xhtml:link
        rel="alternate"
        hreflang="en"
        href="https://www.sphinx-doc.org/en/master/"/>
    
    
    <lastmod>2021-01-22T13:52:45.917848+00:00</lastmod>
    
    <changefreq>weekly</changefreq>
    <priority>1</priority>
  </url>
  
  <url>
    <loc>https://www.sphinx-doc.org/en/3.x/</loc>
    
    <xhtml:link
        rel="alternate"
        hreflang="en"
        href="https://www.sphinx-doc.org/en/3.x/"/>
    
    
    <lastmod>2021-01-22T13:07:09.438080+00:00</lastmod>
    
    <changefreq>daily</changefreq>
    <priority>0.9</priority>
  </url>
  
  <url>
    <loc>https://www.sphinx-doc.org/en/2.0/</loc>
    
    <xhtml:link
        rel="alternate"
        hreflang="en"
        href="https://www.sphinx-doc.org/en/2.0/"/>
    
    
    <lastmod>2020-02-17T15:24:39.551176+00:00</lastmod>
    
    <changefreq>monthly</changefreq>
    <priority>0.8</priority>
  </url>
  
  <url>
    <loc>https://www.sphinx-doc.org/en/1.8/</loc>
    
    <xhtml:link
        rel="alternate"
        hreflang="es"
        href="https://www.sphinx-doc.org/es/1.8/"/>
    
    <xhtml:link
        rel="alternate"
        hreflang="ja"
        href="https://www.sphinx-doc.org/ja/1.8/"/>
    
    <xhtml:link
        rel="alternate"
        hreflang="pt-BR"
        href="https://www.sphinx-doc.org/pt_BR/1.8/"/>
    
    <xhtml:link
        rel="alternate"
        hreflang="en"
        href="https://www.sphinx-doc.org/en/1.8/"/>
    
    
    <lastmod>2019-03-29T16:25:48.022608+00:00</lastmod>
    
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  
  <url>
    <loc>https://www.sphinx-doc.org/en/1.7/</loc>
    
    <xhtml:link
        rel="alternate"
        hreflang="es"
        href="https://www.sphinx-doc.org/es/1.7/"/>
    
    <xhtml:link
        rel="alternate"
        hreflang="ja"
        href="https://www.sphinx-doc.org/ja/1.7/"/>
    
    <xhtml:link
        rel="alternate"
        hreflang="pt-BR"
        href="https://www.sphinx-doc.org/pt_BR/1.7/"/>
    
    <xhtml:link
        rel="alternate"
        hreflang="en"
        href="https://www.sphinx-doc.org/en/1.7/"/>
    
    
    <lastmod>2018-09-12T15:54:24.908331+00:00</lastmod>
    
    <changefreq>monthly</changefreq>
    <priority>0.6</priority>
  </url>
  
  <url>
    <loc>https://www.sphinx-doc.org/en/1.6/</loc>
    
    <xhtml:link
        rel="alternate"
        hreflang="es"
        href="https://www.sphinx-doc.org/es/1.6/"/>
    
    <xhtml:link
        rel="alternate"
        hreflang="ja"
        href="https://www.sphinx-doc.org/ja/1.6/"/>
    
    <xhtml:link
        rel="alternate"
        hreflang="pt-BR"
        href="https://www.sphinx-doc.org/pt_BR/1.6/"/>
    
    <xhtml:link
        rel="alternate"
        hreflang="en"
        href="https://www.sphinx-doc.org/en/1.6/"/>
    
    
    <lastmod>2018-02-12T07:29:07.711315+00:00</lastmod>
    
    <changefreq>monthly</changefreq>
    <priority>0.5</priority>
  </url>
  
  <url>
    <loc>https://www.sphinx-doc.org/en/1.5/</loc>
    
    <xhtml:link
        rel="alternate"
        hreflang="es"
        href="https://www.sphinx-doc.org/es/1.5/"/>
    
    <xhtml:link
        rel="alternate"
        hreflang="ja"
        href="https://www.sphinx-doc.org/ja/1.5/"/>
    
    <xhtml:link
        rel="alternate"
        hreflang="pt-BR"
        href="https://www.sphinx-doc.org/pt_BR/1.5/"/>
    
    <xhtml:link
        rel="alternate"
        hreflang="en"
        href="https://www.sphinx-doc.org/en/1.5/"/>
    
    
    <lastmod>2018-02-12T07:34:51.390341+00:00</lastmod>
    
    <changefreq>monthly</changefreq>
    <priority>0.4</priority>
  </url>
  
  <url>
    <loc>https://www.sphinx-doc.org/en/1.4/</loc>
    
    <xhtml:link
        rel="alternate"
        hreflang="es"
        href="https://www.sphinx-doc.org/es/1.4/"/>
    
    <xhtml:link
        rel="alternate"
        hreflang="ja"
        href="https://www.sphinx-doc.org/ja/1.4/"/>
    
    <xhtml:link
        rel="alternate"
        hreflang="pt-BR"
        href="https://www.sphinx-doc.org/pt_BR/1.4/"/>
    
    <xhtml:link
        rel="alternate"
        hreflang="en"
        href="https://www.sphinx-doc.org/en/1.4/"/>
    
    
    <lastmod>2018-02-11T08:44:31.045539+00:00</lastmod>
    
    <changefreq>monthly</changefreq>
    <priority>0.3</priority>
  </url>
  
  <url>
    <loc>https://www.sphinx-doc.org/en/1.3/</loc>
    
    <xhtml:link
        rel="alternate"
        hreflang="es"
        href="https://www.sphinx-doc.org/es/1.3/"/>
    
    <xhtml:link
        rel="alternate"
        hreflang="ja"
        href="https://www.sphinx-doc.org/ja/1.3/"/>
    
    <xhtml:link
        rel="alternate"
        hreflang="pt-BR"
        href="https://www.sphinx-doc.org/pt_BR/1.3/"/>
    
    <xhtml:link
        rel="alternate"
        hreflang="en"
        href="https://www.sphinx-doc.org/en/1.3/"/>
    
    
    <lastmod>2018-02-11T08:44:26.481932+00:00</lastmod>
    
    <changefreq>monthly</changefreq>
    <priority>0.2</priority>
  </url>
  
  <url>
    <loc>https://www.sphinx-doc.org/en/1.2/</loc>
    
    <xhtml:link
        rel="alternate"
        hreflang="es"
        href="https://www.sphinx-doc.org/es/1.2/"/>
    
    <xhtml:link
        rel="alternate"
        hreflang="ja"
        href="https://www.sphinx-doc.org/ja/1.2/"/>
    
    <xhtml:link
        rel="alternate"
        hreflang="pt-BR"
        href="https://www.sphinx-doc.org/pt_BR/1.2/"/>
    
    <xhtml:link
        rel="alternate"
        hreflang="en"
        href="https://www.sphinx-doc.org/en/1.2/"/>
    
    
    <lastmod>2018-02-11T08:39:07.151772+00:00</lastmod>
    
    <changefreq>monthly</changefreq>
    <priority>0.1</priority>
  </url>
  
</urlset>
```

**Comment by shimizukawa** [comment]
The canonical url of the recently built pages all point to `en/master`.
![image](https://user-images.githubusercontent.com/151623/105570150-b8aabf80-5d8a-11eb-8919-88a835488628.png)

However search results of `sphinx glob toctree` still points to
1st. https://www.sphinx-doc.org/en/1.5/markup/toctree.html
2nd. https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html
3rd. https://www.sphinx-doc.org/ja/1.3/markup/toctree.html
![image](https://user-images.githubusercontent.com/151623/105570211-10e1c180-5d8b-11eb-94cd-2a922c57d56f.png)

**Comment by shimizukawa** [comment]
To remove too old documents (1.x), deactivate them as:

Before
![image](https://user-images.githubusercontent.com/151623/112712314-1f2a9600-8f12-11eb-82dc-cfb06e213e68.png)

After
![image](https://user-images.githubusercontent.com/151623/112712393-ad9f1780-8f12-11eb-91c1-5858830ada34.png)

and now, all other languages also only activating `master` document.

**Comment by shimizukawa** [comment]
Now en document has master and 3.x: https://readthedocs.org/projects/sphinx/versions/
![image](https://user-images.githubusercontent.com/151623/112712388-919b7600-8f12-11eb-84ed-ec0c5e35588b.png)

**Comment by shimizukawa** [comment]
I've done all I can do, so I will close the ticket.

**Comment by humitos** [comment]
Hi @shimizukawa! If you don't want to serve old documentation, but also avoid dead links, I would recommend you to create redirects from old versions to new ones. For example, `/en/1.8/` could redirect to `/en/master/`.

On the other hand, you can take a look at the [`sphinx-notfound-page`](https://sphinx-notfound-page.readthedocs.io/) to generate nice 404 pages following the same page style than a normal document instead of the default "Maze Found" from Read the Docs.

**Comment by shimizukawa** [comment]
Uh, okay. I thought it was inevitable that the links would be broken, but I forgot that I could set a redirect. 
I've set it up for: 1.2, ... 1.8 and 2.0
For example: https://www.sphinx-doc.org/en/1.8/usage/quickstart.html now redirects to `/en/master/usage/quickstart.html`
Thank you very much for letting me know!

![image](https://user-images.githubusercontent.com/151623/113502316-955c7780-9566-11eb-91bd-f67dd1733063.png)
