### ISSUE TITLE
No way to say which option an :option: refers to.

### ISSUE THREAD

**Issue by cjw296** [sphinx-doc/sphinx#8318]
**Describe the bug**
If an :option: is defined more than once is a set of Sphinx documentation, it's not possible to say which occurrence of that option you're linking to.

**To Reproduce**

- have ``:option:`--version` `` somewhere in your .rst.
- define a `.. option:: --version`
- include an intersphinx reference to python docs, or have another doc with a `.. option:: --version` in it.

When you build, the ``:option:`--version` `` will link to Python's `--version` option, not the one in your project.

**Expected behavior**

Some way to say which `--version` is the intended target.

**Comment by tk0miya** [comment]
Can't reproduced. Could you provide an example project?

Note: intersphinx will work only when the reference could not be resolved on that project. So it is a bit strange.

**Comment by cjw296** [comment]
I'm afraid this was an internal project, so difficult to work up a small reproducer...

**Comment by tk0miya** [comment]
I don't need to share your business document. Is it difficult to create a similar document as an example? If you can't, I also can't fix the error...

**Comment by cjw296** [comment]
You're right, let's close this until I or someone else can come up with a reproducer.

**Comment by jakobandersen** [comment]
I think I recently ran into the issue you describe:
```rst
prog1
=====

.. program:: prog1

.. option:: --version

	- :option:`--version`

- :option:`--version`


prog2
=====

.. program:: prog2

.. option:: --version

	- :option:`--version`

- :option:`--version`


xrefs
=====

.. program:: None

- None: :option:`--version`

.. program:: prog1

- prog1: :option:`--version`

.. program:: prog2

- prog2: :option:`--version`
```
How I think it works is that every ``option`` directive and role works within the current ``program`` context. This means that you basically _must_ use the ``program`` directive before every `:option:` to be sure which option will be looked up.
Incidentally, when compiling the above with the Python docs in intersphinx, then the ``None`` ``:option:`` selects ``--version`` from Python. I guess the ``program`` directive is not used in the Python docs, or perhaps intersphinx does a different kind of lookup than the ``std`` domain.
This restriction means that you can not refer to options in two different programs within the same paragraph, list, etc. where a directive would break the construct.

I suggest we somehow make it possible to write an option role where the program is specified as well, preferably by adding extra parsing to the existing role. For example if ``!`` can not appear in a program name or option then something like
```rst
:option:`prog1!--version`
```

**Comment by tk0miya** [comment]
We can pass a program name explicitly to the role: ```:option:`prog1 --version` ``` or ```:option:`--version <prog1 --version>` ```. So I feel new notation is not needed.

**Comment by jakobandersen** [comment]
Ah, I have overlooked that syntax. Thanks!
