### ISSUE TITLE
Highlight parameter breaks browser search

### ISSUE THREAD

**Issue by Avamander** [sphinx-doc/sphinx#8322]
**Describe the bug**
The highlight parameter breaks browser search functionality.

**To Reproduce**

Go to for example `https://docs.lvgl.io/v7/en/html/overview/style.html?highlight=lv_style_set%20opa` and try to search for e.g. `lv_style_set_bg_opa` then there are no results. Which is incorrect.

**Expected behavior**

The documentation pages don't break Ctrl+F and results are found when searching for something that is partially highlighted. Currently it makes the entire documentation a massive pain in the arse to use.

**Your project**

https://docs.lvgl.io/v7/en/html/overview/style.html

**Screenshots**

![bug](https://user-images.githubusercontent.com/5392141/96513517-e273b800-126a-11eb-81cb-a1b6b9f1177d.png)

**Environment info**
- Browser: Chromium 86

**Comment by embeddedt** [comment]
I've just upgraded the LVGL 8 docs to Sphinx 4, and it looks like this has been fixed!

https://docs_compiled.lvgl.io/8.0/overview/style.html?highlight=lv_style_set#initialize-styles-and-set-get-properties

**Comment by tk0miya** [comment]
I don't know what change fixed this. But it seems surely working now. Closing.
