### ISSUE TITLE
conf.py parameter for default document name uses exclusionary language

### ISSUE THREAD

**Issue by moshez** [sphinx-doc/sphinx#8326]
**Is your feature request related to a problem? Please describe.**

In a number of projects I am involved with which use sphinx, avoiding exclusionary language, and especially terms that are related to racial injustices, is a priority. In `conf.py`, to override which document is the root, it uses the term `master_doc`.

**Describe the solution you'd like**

An alias to the term `master_doc` in `conf.py`. For example, if this was `root_doc`, then using

```
root_doc = "README.rst"
```

would have the same effect as

```
master_doc = "README.rst"
```

If both are defined, this is either an error or `root_doc` takes precedence. I have no strong feelings about the behavior in this corner case.

**Describe alternatives you've considered**

* We can have alternative names for `root_doc` (for example, `content_doc`)
* For some use cases, taking advantage of the default `index.rst` works well, so I don't need to explicitly set it.
* I considered playing games with global so offensive terms are not explicit in my code. e.g. `globals()[rot13(...)] = "README.rst`
* I can copy files to the default filename.

**Comment by shimizukawa** [comment]
+1 for the `root_doc` alias of `master_doc`

**Comment by tk0miya** [comment]
+1: I think `root_doc` is a good name to describe its meaning.

**Comment by jfbu** [comment]
Maybe one should inform people that a degree such as [master of arts](https://en.wikipedia.org/wiki/Master_of_Arts) is impropriately worded.

**Comment by tk0miya** [comment]
I think I would object to rename if no good alternative was found. But "root" is so natural for me because we already use the "tree" metaphor for the Table of Contents. Therefore, I think this is a good change, not only for political requests.
