### ISSUE TITLE
C domain: References generated by types in function signatures don't use intersphinx

### ISSUE THREAD

**Issue by eric-wieser** [sphinx-doc/sphinx#8341]
**Describe the bug**
Over in https://github.com/numpy/numpy/pull/16370, we're getting warnings about missing references to C identifiers even though we know they exist in projects in our intersphinx

**To Reproduce**
Create an RST file with
```rst
.. c:function:: PyObject* MyFunction(PyObject* op)
   Some description
```
put the following in `conf.py`
```python
extensions = ['sphinx.ext.intersphinx']
intersphinx_mapping = {
    'python': ('https://docs.python.org/dev', None),
}
```
Build the sphinx docs with reference warnings enabled.  The output log will contain
```
c:identifier reference target not found: PyObject
```
which is strange, because the `https://docs.python.org/dev/objects.inv` definitely contains an entry for `PyObject`.

**Expected behavior**
No warning

**Your project**
Link to your sphinx project, or attach zipped small project sample.

**Screenshots**

**Environment info**
- Python version: 3.8
- Sphinx version: 3.2.1
- Sphinx extensions:  sphinx.ext.intersphinx

**Comment by jakobandersen** [comment]
Fixed in 3.x (to become v3.5). The fix is only on the client side so you can simply recompile your own project with the new version.
