### ISSUE TITLE
Dead links on extensions page

### ISSUE THREAD

**Issue by henrikh** [sphinx-doc/sphinx#8349]
**Describe the bug**
The link to the "sphinx-contrib" repository doesn't work on the "Sphinx development" page: https://www.sphinx-doc.org/en/master/develop.html#extensions

**To Reproduce**
Click on the link "sphinx-contrib".

**Expected behavior**
Should go to the proper repository site. Don't know what it is. Might be this: https://github.com/sphinx-contrib

**Your project**
N/A

**Screenshots**
N/A

**Environment info**
- OS: N/A
- Python version: N/A
- Sphinx version: 4.0.0

**Additional context**

I'd like to help contributing to some better documentation of Sphinx. So if someone can tell where the URL can point to, then I can put together the pull request :)

**Comment by Daltz333** [comment]
That is the correct repository.

**Comment by tk0miya** [comment]
Fixed. Thank you for reporting
