### ISSUE TITLE
ASCII table for Chinese

### ISSUE THREAD

**Issue by cathaysia** [sphinx-doc/sphinx#8370]
**Is your feature request related to a problem? Please describe.**

Hi, friends. I use ASCII table sometimes, but Chinese character's view width not equality with its  with in fact. So, make a ASCII table must be a problem for me. Could we have a tool to auto build a table?

Such a table in contain Chinese:

Ugliness Very Much!

+-------+-------+------+
| haha  |  sss  |  bb  |
+=======+=======+======+
| haha1 |       | xx   |
+-------+       +------+
| 哈哈  | 嘻嘻  | 哈哈 |
+-------+-------+------+

**Comment by tk0miya** [comment]
>Could we have a tool to auto build a table?

Why did you post a question here? This is the issue list of Sphinx itself, not a forum.
Thanks,
