### ISSUE TITLE
Broken link in contribution page

### ISSUE THREAD

**Issue by urbalazs** [sphinx-doc/sphinx#8375]
The page https://github.com/sphinx-doc/sphinx/blob/3.x/doc/internals/contributing.rst#translations has a broken link to Trasifex in the **Translations** section:

```
The Sphinx core messages can also be translated on `Transifex <https://www.transifex.com/sphinx-doc/>`_.
```

This points to an error 404 page. However, these links work:

- Core messages: https://www.transifex.com/sphinx-doc/sphinx-1/
- Documentation: https://www.transifex.com/sphinx-doc/sphinx-doc/

Please update the contribution page, if the links above are correct.

**Comment by tk0miya** [comment]
Thank you for reporting!
