### ISSUE TITLE
app.connect('read-source', methodname) doesn't read all files

### ISSUE THREAD

**Issue by Martiix** [sphinx-doc/sphinx#8381]
I'm trying to make a directive to make some changes to the rst before the html is built using:
`sphinx-build -W -b html source-dir build-dir`
This is my file structure
```
-rst-source-sir
   -other.rst
-source-dir
   -conf.py
   -index.rst
```
Index.rst imports other.rst using include and it works for the generated html.

The problem is that when trying to change other.rst during build time, it doesn't read the module. Changing index.rst works fine.
Im using `app.connect('read-source', methodname)` where methodname is making the adjustments to the source[0] argument. 

Another note: warnings from the rst is displayed before read-source is run based on the unchanged rst, even though the rst after methodname is run, should not provide any warnings.

**Comment by tk0miya** [comment]
The "source-read" events are emitted only when "a source file has been read". Sadly, the content of the "literalinclude" directive is not a "source file". So the event is not emitted.
https://www.sphinx-doc.org/en/master/extdev/appapi.html#event-source-read

**Comment by Martiix** [comment]
Is it any other way of reading and editing the file?

**Comment by tk0miya** [comment]
Please customize `literalinclude` directive and install your custom version as an extension.

**Comment by Martiix** [comment]
Is it also correct that the warnings provided by sphinx should be based on the source[0] before the editing?
if so, is there an elegant way to work around that besides making a placeholder directive?

**Comment by Martiix** [comment]
Edit: I use include and not literalinclude to import the files if that makes a difference.

**Comment by tk0miya** [comment]
>Is it also correct that the warnings provided by sphinx should be based on the source[0] before the editing?

The parser components of Sphinx tries to read the source that the `source-read` event handlers modified. They never be able to touch the original source input.

**Comment by Martiix** [comment]
I'm not sure I understand what you're saying.
My situation is,
I have invalid rst originally, and using source-read, I edit the content, making it valid rst. 
I still get a warning(turned into error) from the invalid rst before the source-read event is run. 
Is this what should happen?

**Comment by tk0miya** [comment]
Could you show a reproducible example, please? As I commented above, the `source-read` event does not affect the `literalinclude` directive. So I can't imagine what is happened in your environment. I need to know what you're doing in your extension and see what warning is shown.

**Comment by Martiix** [comment]
I'm sorry, something else was wrong in my project, the source-read works fine!
