### ISSUE TITLE
astropy: Significant performance hit upgrading Sphinx 3.2.1 to 3.3.0

### ISSUE THREAD

**Issue by pllim** [sphinx-doc/sphinx#8403]
**Describe the bug**

Build time increased from 550-ish seconds to 1400-ish seconds when Sphinx was upgraded from 3.2.1 to 3.3.0.

**To Reproduce**

I am not sure how to reproduce this as the `astropy` package has a lot of documentation and uses its own [sphinx-astropy](https://github.com/astropy/sphinx-astropy/) and [sphinx-automodapi](https://github.com/astropy/sphinx-automodapi) on top of vanilla Sphinx.

**Expected behavior**

Upgrading Sphinx minor version should not have such significant slowdown.

**Your project**

https://github.com/astropy/astropy/ and https://readthedocs.org/projects/astropy/

**Screenshots**

N/A

**Environment info**
- OS: Linux
- Python version: 3.8
- Sphinx version: 3.2.1, 3.3.0
- Sphinx extensions: Various, see above
- Extra tools: RTD

**Additional context**

- astropy/astropy#11014 (particularly https://github.com/astropy/astropy/pull/11014#issuecomment-724801783)
- readthedocs/readthedocs.org#7648

Any insight would be greatly appreciated. Thank you!

**Comment by tk0miya** [comment]
I fixed some slowdown bugs in 3.3.1. Could you try the new one, please?

**Comment by pllim** [comment]
Yes, seems fixed. Thanks!
