### ISSUE TITLE
Sphinx doesn't handle correctly semicolons as a delimiter in external links

### ISSUE THREAD

**Issue by Jpfonseca** [sphinx-doc/sphinx#8405]
**Describe the bug**
I have been following a document made with Read the Docs for Sphinx in which and I realised Sphinx doesn't handle the delimiter `;` in a proper way, substituting it by the charset encode `%3B`. This will make the generated html having a link with the  charset encoded value instead of the delimiter which makes the link incorrect. The problem is greater than it seems as most browsers don't accept url encoded links (tested on chromium based browsers, firefox, others(?))

The delimiter `;` is part of a long list of delimiters listed in the [RFC 3986](https://tools.ietf.org/html/rfc3986) which specifies the `Uniform Resource Identifier (URI): Generic Syntax`

**To Reproduce**
```
Create a `.md` file

Generate a external link  using semicolons in it : 
[example](https://osm.etsi.org/gitweb/?p=osm/devops.git;a=blob;f=descriptor-packages/vnfd/ref11_vnf/src/ref11_vnfd.yaml)  

After running the makefile, Sphinx will create a similar url, which doesn't have the delimiter `;` decoded:
https://osm.etsi.org/gitweb/?p=osm/devops.git%3Ba=blob%3Bf=descriptor-packages/vnfd/ref11_vnf/src/ref11_vnfd.yaml

Th url doesn't exist as the browser is unable to change the `%3B` back to `;`.

```

**Expected behavior**

Sphinx should have generated a html page in which the url has a decoded value of the said delimiter.

**Your project**
[Not my project, but where I found the issue](https://osm.etsi.org/docs/vnf-onboarding-guidelines/05-basic-examples.html)

**Comment by tk0miya** [comment]
What extension do you use? Sphinx itself does not support markdown directly. I guess this bug came from the parser of markdown.

As a trial, I put a hyperlink that points to https://osm.etsi.org/gitweb/?p=osm/devops.git;a=blob;f=descriptor-packages/vnfd/ref11_vnf/src/ref11_vnfd.yaml to a reStructuredText file, and I got the following HTML:

```
<p><a class="reference external" href="https://osm.etsi.org/gitweb/?p=osm/devops.git;a=blob;f=descriptor-packages/vnfd/ref11_vnf/src/ref11_vnfd.yaml">https://osm.etsi.org/gitweb/?p=osm/devops.git;a=blob;f=descriptor-packages/vnfd/ref11_vnf/src/ref11_vnfd.yaml</a></p>
```

**Comment by Jpfonseca** [comment]
The project is using Read the Docs. I didn't got enough time to make sure it was a Sphinx issue, but  for what what I have seen in the code  so far, you are right.


________________________________

**Comment by tk0miya** [comment]
Okay. Please let me know if you found new information about this and feel free to reopen this.
Thanks,
