### ISSUE TITLE
inherited-members should support more than one class

### ISSUE THREAD

**Issue by drootang** [sphinx-doc/sphinx#8417]
**Is your feature request related to a problem? Please describe.**
I have two situations:
- A class inherits from multiple other classes. I want to document members from some of the base classes but ignore some of the base classes
- A module contains several class definitions that inherit from different classes that should all be ignored (e.g., classes that inherit from list or set or tuple). I want to ignore members from list, set, and tuple while documenting all other inherited members in classes in the module.

**Describe the solution you'd like**
The :inherited-members: option to automodule should accept a list of classes. If any of these classes are encountered as base classes when instantiating autoclass documentation, they should be ignored.

**Describe alternatives you've considered**
The alternative is to not use automodule, but instead manually enumerate several autoclass blocks for a module. This only addresses the second bullet in the problem description and not the first. It is also tedious for modules containing many class definitions.

**Comment by tk0miya** [comment]
+1: Acceptable change.

**Comment by tk0miya** [comment]
>A class inherits from multiple other classes. I want to document members from some of the base classes but ignore some of the base classes

For example, there is a class that inherits multiple base classes:
```
class MyClass(Parent1, Parent2, Parent3, ...):
    pass
```
and

```
.. autoclass:: example.MyClass
   :inherited-members: Parent2
```

How should the new `:inherited-members:` work? Do you mean that the member of Parent2 are ignored and the Parent1's and Parent3's are documented? And how about the methods of the super classes of `Parent1`?

Note: The current behavior is ignoring Parent2, Parent3, and the super classes of them (including Parent1's also). In python words, the classes after `Parent2` in MRO list are all ignored.
