### ISSUE TITLE
language_data.js is loaded from all pages.

### ISSUE THREAD

**Issue by methane** [sphinx-doc/sphinx#8419]
**Describe the bug**

`language_data.js` is used by `searchtools.js`.

But `language_data.js` is loaded in all pages.
https://github.com/sphinx-doc/sphinx/blob/68cc0f7e94f360a2c62ebcb761f8096e04ebf07f/sphinx/builders/html/__init__.py#L304

Can we move it to `search.html`?

https://github.com/sphinx-doc/sphinx/blob/af62fa61e6cbd88d0798963211e73e5ba0d55e6d/sphinx/themes/basic/search.html#L14

**To Reproduce**

See this page and show source.
https://docs.python.org/3/library/stdtypes.html

**Expected behavior**

If language_data.js is used only by searchtool.js, don't load language_data.js unless searchtool.js is loaded.

**Your project**
python/cpython project, Docs/

**Environment info**
- Sphinx version: 2.4.4.

**Additional context**

- https://github.com/python/python-docs-theme/issues/58

**Comment by tk0miya** [comment]
Thank you for reporting. It will be fixed soon.

**Comment by pedrohdz** [comment]
@tk0miya 
It seems as if search is broken from this change forward.  I opened a new issue regarding this issue: https://github.com/sphinx-doc/sphinx/issues/8623.
