### ISSUE TITLE
autodoc strips spaces from values

### ISSUE THREAD

**Issue by hansonap** [sphinx-doc/sphinx#8446]
If I define a module level data as:
```
INDENT: str = '    ' 
"""
: Defines the single level indentation that will be used in the generated stubs /  wrapper. Default is four spaces. 
Can be overridden if necessary.
"""
```

and in my .rst file
```
.. autodata:: INDENT
```

It is rendered as as a single space
![image](https://user-images.githubusercontent.com/666037/99564818-c35a6a00-297f-11eb-948f-6a80b518d06f.png)

Expected result is four spaces as defined in .py file.

Same result if defined with` .. data::` directive.

**Comment by tk0miya** [comment]
It is converted to the following HTML:
```
<code class="sig-prename descclassname">example.</code><code class="sig-name descname">INDENT</code><em class="property">: str</em><em class="property"> = '    '</em>
```

The four spaces are kept as is. But HTML browsers consider them as one space. It should be escaped on generating HTML.

**Comment by hansonap** [comment]
Got it, thanks for the explanation. 

I can probably tackle this if no one has started working it yet. Looks like HTMLTranslator in sphinx/writers/html.py is a logical starting point?

**Comment by tk0miya** [comment]
I still don't have time to investigate this yet. So I don't have an answer for your question. But it and `sphinx/domains/python.py` would be related to this problem, I suppose.
