### ISSUE TITLE
Graphviz Extension: graphviz_dot option is not replaced by layout for graph and digraph directives

### ISSUE THREAD

**Issue by loebl** [sphinx-doc/sphinx#8454]
**Describe the bug**

When adding the new layout option to `class Graphviz`, it was forgotten to add it to ` GraphvizSimple`. This way the documentation and code/behaviour are not consistent

**To Reproduce**

Compare:
* https://github.com/sphinx-doc/sphinx/blob/68c91b19208cff332eacf30908b63b80482fafb8/sphinx/ext/graphviz.py#L121
* https://github.com/sphinx-doc/sphinx/blob/68c91b19208cff332eacf30908b63b80482fafb8/sphinx/ext/graphviz.py#L185
As well as:
* https://github.com/sphinx-doc/sphinx/blob/68c91b19208cff332eacf30908b63b80482fafb8/sphinx/ext/graphviz.py#L156
* https://github.com/sphinx-doc/sphinx/blob/68c91b19208cff332eacf30908b63b80482fafb8/sphinx/ext/graphviz.py#L196

**Expected behavior**
Option listing (and processing) should be identical

**Your project**

Mini-Example:
```
.. works

.. graphviz::
   :layout: neato

   graph foobar {
   foo -- bar;
   bar -- baz;
   baz -- foo;
   }

.. doesn't work

.. graph::
   :layout: neato

   foo -- bar;
   bar -- baz;
   baz -- foo;
```
EDIT: corrected graph directive in example

**Screenshots**
none

**Environment info**
- OS: Debian 10 (Buster), Sphinx inside virtualenv
- Python version: 3.7.3
- Sphinx version: 3.2.1
- Sphinx extensions:  sphinx.ext.graphviz, sphinx_rtd_theme
- Extra tools: firefox 78.5.0

**Additional context**
None

**Comment by loebl** [comment]
:+1: 
Thanks

**Comment by tk0miya** [comment]
Fixed. Thank you for reporting!
