### ISSUE TITLE
Report underlying type information for NewType and TypeVar

### ISSUE THREAD

**Issue by anselor** [sphinx-doc/sphinx#8460]
**Is your feature request related to a problem? Please describe.**
Autodoc for NewType and TypeVar report the name of the type and the developer doc-comments but doesn't report the type metadata. 

**Describe the solution you'd like**
For NewType I'd expect it to report the underlying type.
For example:
MyInt = NewType('MyInt', int) should report in the generated docs that the underlying type is int.

ForTypeVar there are multiple attributes. If there's bound type information, that should be reported. Additionally, it should report whether the type is invariant, covariant, or contravariant. As a bonus, cross-linking between invariant, covariant, or contravariant TypeVar declarations for the same underlying type.

**Describe alternatives you've considered**
The alternative would be  for the developer to manually document the type information they've already declared - which seems redundant since this should be easy to resolve.

**Additional context**
- See also discussion in #8415

**Comment by tk0miya** [comment]
Thank you for posting. I'll take a look at NewType from now on.

>ForTypeVar there are multiple attributes. If there's bound type information, that should be reported. Additionally, it should report whether the type is invariant, covariant, or contravariant. 

Now autodoc support to show attributes of TypeVar now. Do you know this?
https://github.com/sphinx-doc/sphinx/blob/3.x/tests/test_ext_autodoc.py#L1729-L1761

**Comment by tk0miya** [comment]
Now I implement the support of NewTypes. It enables to render NewType variables in Sphinx. But referencing is still not working because NewType objects do not know where the type is defined.

**Comment by tk0miya** [comment]
Additionally, I noticed `autodata` and `autoattribute` directives does not support displaying the type information of TypeVars. So I'll post a fix soon.

**Comment by tk0miya** [comment]
Now autodoc supports NewType variables. So I'm closing this. About better output for TypeVars, please let me know if you find a nice idea!
