### ISSUE TITLE
need help!!!

### ISSUE THREAD

**Issue by dengz11** [sphinx-doc/sphinx#8473]
File "/home/ds/Envs/odoo13_sphinx_test/lib/python3.6/site-packages/sphinx/writers/latex.py", line 2044, in unknown_visit
    raise NotImplementedError('Unknown node: ' + node.__class__.__name__)
NotImplementedError: Unknown node: div

**Comment by tk0miya** [comment]
Sorry, we can't help you because we can't know what happened in your environment.
Please fill our questionnaire on posting issues. Then I'll take a look into your case.
