### ISSUE TITLE
Proposal: Invite francoisfreitag as a new maintainer 

### ISSUE THREAD

**Issue by tk0miya** [sphinx-doc/sphinx#8489]
# Proposal

Hello maintainers,
Today, I'd like to invite @francoisfreitag  as a new committer/maintainer of our project

He had already contributed many works until now:

* Improve test cases for linkcheck (#8414, #8421, and so on)
* linkcheck: Handle rate-limiting (#8467)

I believe his experience would help us.
What do you think? Please 👍 for this if you agreed.

I know there is no special procedure to welcome a new committer. So I will invite him if no objection.

**Comment by tk0miya** [comment]
Thank you for voting. I just sent invitation to him. Let's welcome him :-)

**Comment by francoisfreitag** [comment]
Thanks to you all!
