### ISSUE TITLE
sphinx/ext/autodoc/__init__.py:719 could lead to `__bool__` method call, what can lead to side effect or direct failure in case it generate an error

### ISSUE THREAD

**Issue by artsiomkaltovich** [sphinx-doc/sphinx#8522]
**Describe the bug**
The code is the following:

        keep = False
        if safe_getattr(member, '__sphinx_mock__', None) is not None:
            # mocked module or object
            pass

But if ``safe_getattr`` returns some object with redefined ``__bool__``, e.g.

     def __bool__(self):
           raise TypeError("Do not pass this object to if and while clause, use all or any function")

     def __bool__(self):
           write_to_db()
           send_email()
           request_http()
           log()
           some_other_side_effect

This code will be executed and will lead to sphinx failure or unexpected side effects.

**To Reproduce**
Unfortunately I can't reproduce it as a toy example, but it lead to failure on my work project.

**Expected behavior**
Do not call user code.

**Comment by tk0miya** [comment]
+0; autodoc analyzes the target code by dynamic inspection. So we can't promise it will never call a method having side effects (like `__bool__`). I can accept the fix. But it does not mean "autodoc will never call `__bool__` and other methods on analysis.

**Comment by artsiomkaltovich** [comment]
Hello again)

I fix the changelog in PR. I understand there can be another side effects or user code calls, and I've just remove this one. :)

The issue was created just to submit this exact case.
