### ISSUE TITLE
The `middle` and `center` values of the `image` directive's `:align:` option: (not) valid depending on substitution definition or not

### ISSUE THREAD

**Issue by dbitouze** [sphinx-doc/sphinx#8536]
**Describe the bug**
The `middle` and `center` values of the `:align:` option of the `image` directive are (not) valid depending on substitution definition or not, as outlined in the following table:

|                           | Direct inclusion | Substitution |
|---------------------------|------------------|--------------------|
| `:align: middle` option | ✗                | ✓                  |
| `:align: center` option | ✓                | ✗                  |

and pointed out by the following (rather) minimal `.rst` file:

```rst
Welcome to Test's documentation!
================================

Direct inclusion
----------------

Direct inclusion and no ``:align:`` option: *success*
+++++++++++++++++++++++++++++++++++++++++++++++++++++

.. image:: https://www.sphinx-doc.org/en/master/_static/sphinxheader.png

Direct inclusion and ``:align: middle`` option: *failure*
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++

.. image:: https://www.sphinx-doc.org/en/master/_static/sphinxheader.png
   :align: middle

Direct inclusion and ``:align: center`` option: *success*
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++

.. image:: https://www.sphinx-doc.org/en/master/_static/sphinxheader.png
   :align: center


Indirect inclusion
------------------

Indirect inclusion and no ``:align:`` option: *success*
+++++++++++++++++++++++++++++++++++++++++++++++++++++++

|test1|

Indirect inclusion and ``:align: middle`` option: *success* (but not centered)
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

|test2|

Indirect inclusion and ``:align: center`` option: *failure*
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

|test3|

.. |test1| image:: https://www.sphinx-doc.org/en/master/_static/sphinxheader.png

.. |test2| image:: https://www.sphinx-doc.org/en/master/_static/sphinxheader.png
   :align: middle

.. |test3| image:: https://www.sphinx-doc.org/en/master/_static/sphinxheader.png
   :align: center
```

**To Reproduce**
```
$ make html
```
returns the errors:

>WARNING: Error in "image" directive: "middle" is not a valid value for the "align" option.  Valid values for "align" are: "left", "center", "right".
WARNING: Error in "image" directive: "center" is not a valid value for the "align" option within a substitution definition.  Valid values for "align" are: "top", "middle", "bottom".

**Expected behavior**
The `middle` and `center` values of the `:align:` option should be synonym and be valid both with direct inclusion and with substitution.

**Your project**
See attach zipped project sample.
[test.tar.gz](https://github.com/sphinx-doc/sphinx/files/5684710/test.tar.gz)

**Environment info**
- OS: Linux Mageia 7
- Python version: 3.7.9
- Sphinx version: 3.3.1
- Sphinx extensions:  any

**Comment by tk0miya** [comment]
>The middle and center values of the :align: option should be synonym and be valid both with direct inclusion and with substitution.

No, they are not synonyms. The `middle` controls the vertical alignment of the image, and `center` controls horizontal one.
Please read the document of the option: https://docutils.sourceforge.io/docs/ref/rst/directives.html#image

Anyway, this is a limitation of the reStructuredText format itself. Unfortunalyte we can't work for it because the spec is not ours. Please post this into docutils project instead?
