### ISSUE TITLE
Search crashes my browser (on docs.sqlalchemy.org)

### ISSUE THREAD

**Issue by Dreamsorcerer** [sphinx-doc/sphinx#8562]
When I use the search functionality on docs.sqlalchemy.org it typically starts displaying a huge number of results which in only a couple of seconds results in using GBs of RAM, which then results in my browser crashing when the system runs out of memory.

The documentation is created with Sphinx.

I guess an obvious solution would be to implement pagination, rather than loading unlimited amount of results in the page.

Firefox on Linux.

docs.sqlalchemy.org may be a special case here, as the documentation is so big it's pretty common to get a huge number of search results.

See also: https://github.com/sqlalchemy/sqlalchemy/issues/5790

**Comment by tk0miya** [comment]
For example, I searched "sql" on sqlalchemy project. And I got 4746 entries at once.

>Search finished, found 4746 page(s) matching the search query.
>https://docs.sqlalchemy.org/en/13/search.html?q=sql&check_keywords=yes&area=default#

And it makes the page very huge with heavy loop. I guess this wastes CPU and RAM.

I think it would be better to add a threshold to stop listing search-result. I believe nobody sees the 4000th item.
