### ISSUE TITLE
Autosummary fails on NumPy with 3.4.0 

### ISSUE THREAD

**Issue by mattip** [sphinx-doc/sphinx#8566]
The new 3.4.0 release does not properly import in autosummary docstrings. We get lots of errors like
```
/home/matti/miniconda3/envs/test/lib/python3.8/site-packages/numpy/__init__.py:docstring of numpy.bool_.rst:62: \
    WARNING: autosummary: failed to import astype
```

**To Reproduce**
checkout numpy, `pip install cython; pip install .; pip install -r doc_requirements.txt; cd doc; make html`
```
<Paste your command-line here which cause the problem>

$ git clone https://github.com/numpy/numpy
$ cd numpy
$ pip install cython .; # note the "."
$ pip install -r doc_requirements.txt
$ cd doc
$ make html 
```

**Expected behavior**
3.3.1 worked fine. 3.4.0 fails with many `fail to import ...` and then 
```
/home/matti/miniconda3/envs/test/lib/python3.8/site-packages/numpy/__init__.py:docstring of numpy.bool_.rst:62: \
     WARNING: autosummary: stub file not found 'numpy.all'. Check your autosummary_generate setting.
```
Here is the complete log

[log.txt](https://github.com/sphinx-doc/sphinx/files/5724036/log.txt)

**Comment by tk0miya** [comment]
Finally, I found this bug came from the bug of autodoc. On my local, #8581 resolves this issue.

Note: reproducible Dockerfile

```
FROM python:3.8-slim

RUN apt update; apt install -y build-essential curl git make unzip vim
RUN git clone https://github.com/numpy/numpy
WORKDIR /numpy
RUN pip install cython .; # note the "."
RUN pip install -r doc_requirements.txt
RUN pip install git+https://github.com/tk0miya/sphinx@8566_autodoc_process_docstring_for_alias_classes
WORKDIR /numpy/doc
RUN make html
```

**Comment by jorisvandenbossche** [comment]
With pandas we had the same issue (see https://github.com/sphinx-doc/sphinx/pull/8533#commitcomment-45371488), and I can confirm that #8581 fixes it.

Thanks for the quick follow-up!

**Comment by tk0miya** [comment]
@jorisvandenbossche Thank you for confirmation!

**Comment by mattip** [comment]
Thanks for the fix.
