### ISSUE TITLE
I got the function address in html

### ISSUE THREAD

**Issue by jzmexec** [sphinx-doc/sphinx#8574]
At version 1.7.6，
    I will build the python-pillow htmls.
    rst file:
    :mod:`IcnsImagePlugin` Module
    .. automodule:: PIL.IcnsImagePlugin
      :members:
      :undoc-members:
      :show-inheritance:
   PIL.IcnsImagePlugin class has a members:
      SIZES = { (512, 512, 2): [ (b'IC10', read_png_or_jpeg2000),],  ... }
      read_png_or_jepg2000 is a function
   I got the html success, and got the html SIZES like this:
      SIZES = {(512, 512, 2): [ (b'IC10', <function read_png_or_jpeg2000 at 0xffff8ca52780>), ]}
   But the version 1.8.0, I got this:
      SIZES = {(512, 512, 2): [ (b'IC10', \<function read_png_or_jpeg2000 \>), ]}
Can you give me a patch for 1.7.6 version to get the result as same as  version 1.8.0.

**Comment by tk0miya** [comment]
Sorry, we're supporting the latest release only. We don't provide such a patch for old release.
Thanks,
