### ISSUE TITLE
python logging problem

### ISSUE THREAD

**Issue by kessero** [sphinx-doc/sphinx#8577]
In my scripts I use logging lib for logging warnigs etc. in log files
`import logging
from logging.handlers import TimedRotatingFileHandler
formatter = logging.Formatter("%(asctime)s - %(levelname)s - %(message)s")
handler = TimedRotatingFileHandler('log/device.log', when="midnight", interval=1, encoding='utf8')
handler.suffix = "%Y-%m-%d"
handler.setFormatter(formatter)
logger = logging.getLogger()
logger.setLevel(logging.INFO)
logger.addHandler(handler)
...
logging.info("connected") 
`
But when I try generate docs "make html" I get error 
" no folder or file .../log/device/log" 
It doesn't metter that file exists or not.
Documentation isn't generated because this file path.
How can I manage this?

**Comment by tk0miya** [comment]
duplicated with #8578. Closing.
