### ISSUE TITLE
python logging lib and file path

### ISSUE THREAD

**Issue by kessero** [sphinx-doc/sphinx#8578]
In my scripts I use logging lib for logging warnigs etc. in log files
```
import logging
from logging.handlers import TimedRotatingFileHandler
formatter = logging.Formatter("%(asctime)s - %(levelname)s - %(message)s")
handler = TimedRotatingFileHandler('log/device.log', when="midnight", interval=1, encoding='utf8')
handler.suffix = "%Y-%m-%d"
handler.setFormatter(formatter)
logger = logging.getLogger()
logger.setLevel(logging.INFO)
logger.addHandler(handler)
...
logging.info("connected") 
```

But when I try generate docs "make html" I get error 
" no folder or file .../log/device/log" 
It doesn't metter that file exists or not.
Documentation isn't generated because this file path.
How can I manage this?

**Comment by tk0miya** [comment]
You can see the answer in our document:
https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html

>Warning
>
>autodoc imports the modules to be documented. If any modules have side effects on import, these will be executed by autodoc when sphinx-build is run.
>
>If you document scripts (as opposed to library modules), make sure their main routine is protected by a if __name__ == '__main__' condition.

Please put the code to the if block, or change it to a function.

Thanks,
