### ISSUE TITLE
Load theme from egg/entrypoint

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#858]
At the moment, themes either need to be in the core sphinx distribution or present at the location of the documentation I'm building.
It would be very useful if themes could be packaged as python eggs, for reusability.

There are several possibilities to do that, for example, allow theme paths to contain a package name (like Pyramid does, "my.package:path/to/file", or even better, by enabling themes to be registered via entrypoints -- there's even an extension that does just that: http://pypi.python.org/pypi/sphinxjp.themecore

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/858
- Originally reported by: Wolfgang Schnerring
- Originally created at: 2012-01-20T12:10:19.098

**Comment by shimizukawa** [comment]
_From Takayuki Shimizukawa on 2012-05-03 02:32:19+00:00_

+1

**Comment by shimizukawa** [comment]
_From Anonymous on 2012-05-03 03:10:21+00:00_

great suggestion. +1

**Comment by tk0miya** [comment]
Since Sphinx-1.2, we load HTML themes from entry point named `sphinx_themes`.
More details, please read http://www.sphinx-doc.org/en/stable/theming.html .

Thanks,
