### ISSUE TITLE
AssertionError on domains/c.py

### ISSUE THREAD

**Issue by inconstxpr** [sphinx-doc/sphinx#8580]
**Describe the bug**
I have set up a CMake project that generates documentation for C using doxygen, breathe and sphinx, following this [guide](https://devblogs.microsoft.com/cppblog/clear-functional-c-documentation-with-sphinx-breathe-doxygen-cmake/). The sphinx target depends on `sphinx/index.html`, which can be generated by a custom command that in turn, depends on `doxygen/xml/index.xml`.

When using Visual Studio, `Build > Clean All` deletes all files that are generated by the build, in this case `doxygen/xml/index.xml` and `sphinx/index.html`. After that, the next build will fail with:
```
Exception occurred:
    File "c:\python39\lib\site-packages\sphinx\domains\c.py", line 1532, in _fill_empty
      assert line is not None
  AssertionError
```
After getting the error, running `Build > Clean All` and then another build works without problems. It alternates between the two, so the next cycle will give the same error. This is not exclusive to Visual Studio.

**To Reproduce**
```
$ git clone https://github.com/inconstxpr/icanc.git
$ cd icanc
$ mkdir build
$ cd build
$ cmake ..
$ cmake --build . --target sphinx # works
$ rm docs/doxygen/xml/index.xml
$ rm docs/sphinx/index.html
$ cmake --build . --target sphinx # error
$ rm docs/doxygen/xml/index.xml
$ # sphinx/index.html was not generated
$ cmake --build . --target sphinx # works
```

**Expected behavior**
The build should work every time.

**Your project**
https://github.com/inconstxpr/icanc.git

**Environment info**
- OS: Windows 10
- Python version: 3.9.0
- Sphinx version: 3.3.0
- Sphinx extensions:  breathe
- Extra tools: CMake 3.19.0

**Comment by jakobandersen** [comment]
It looks like this could be the same problem reported and fixed in #8364. Try upgrading to a newer version of Sphinx. If it doesn't fix it, please reopen the issue.
