### ISSUE TITLE
Load dependencies after loading conf.py

### ISSUE THREAD

**Issue by AkibAzmain** [sphinx-doc/sphinx#8584]
Sometimes I want to load my custom python module (e.g. custom pygments module) into Sphinx (not to be confused with extension). I can load extensions from custom directory by changing `sys.path`. But changing it does notl work the modules on which Sphinx depends directly. It is possible to change `sys.path` directly from command-line with arguments to python or with environment variables to python, but that's messy, especially when using `make`.

It would be good if Sphinx loads all extensions (except those required before loading `conf.py`) after loading `conf.py`. This will allow to modify `sys.path` inside `conf.py` which can take effect on loading modules required by Sphinx.

**Comment by tk0miya** [comment]
Sphinx has already load extensions after reading conf.py. Please rewrite your `Makefile` to pass command-line arguments to python. Then it will go well.
