### ISSUE TITLE
regression: c:identifier reference target not found

### ISSUE THREAD

**Issue by lazka** [sphinx-doc/sphinx#8586]
**Describe the bug**

When nesting a c struct member in the docs of a c:type then referencing the parent type no longer works. It works in 3.2 and is broken in 3.4.1

**To Reproduce**
```reST
.. c:type:: PyObject

.. c:type:: PyObject PycairoContext

    .. c:member:: PyObject* PycairoContext.ctx
```

```
pycairo_c_api.rst:12: WARNING: c:identifier reference target not found: PycairoContext
```

**Expected behavior**
PycairoContext for the member creates a link to the type

See https://github.com/pygobject/pycairo/pull/222 for a workaround I found

**Environment info**

Python 3.8.6, Ubuntu/Windows

**Comment by jakobandersen** [comment]
I believe the warning is correct:
- The first directive declares a type alias ``PyObject`` for an unknown type.
- The second directive declares a type alias ``PycairoContext`` for the type ``PyObject``.
- The third directive is indented, so you are now within the scope of ``PycairoContext``. This is somewhat icky as it is a type alias.
- The third directive declares a variable ``ctx`` of type ``PyObject*`` within the nested scope ``PycairoContext`` which is already within the scope ``PycairoContext``, so the full declared name is ``PycairoContext.PycairoContext.ctx``.
  In v3.2.1 this was not done correctly as the two ``PycairoContext`` got merged.

Based on ``pycairo.h`` I suggest something like:
```rst
.. c:struct:: PycairoContext

	something something "inherits" from :c:type:`PyObject` or what the correct description would be

	.. c:member:: PyObject *ctx

		nice description
```
and then use Intersphinx to get the ``PyObject`` mentions to resolve to the Python documentation (though #8341 is hit, hopefully fixed soon'ish). That is, in ``conf.py``:
```python
extensions = [
	'sphinx.ext.intersphinx',
]
intersphinx_mapping = {
	'python': ('https://docs.python.org/3', None)
}
```

**Comment by lazka** [comment]
ok, thanks for the detailed help! I'll give this a try.
