### ISSUE TITLE
Inconsistent treatment of type annotation

### ISSUE THREAD

**Issue by xuhdev** [sphinx-doc/sphinx#8606]
**Describe the bug**
The resolutions of a type in type annotation are inconsistent for imported members.

**To Reproduce**

```
$ # Download the attached bug.tar.gz and extract the file here...
$ PYTHONPATH=. sphinx-build -d "./_build" docs "_build/html" -b html -W --color
```

**Expected behavior**
All `A` in type annotations should be resolved to be either `A`, or `myproject._impl.A`.

**Your project**
Link to your sphinx project, or attach zipped small project sample.

[bug.tar.gz](https://github.com/sphinx-doc/sphinx/files/5746032/bug.tar.gz)

Source tree:

```
.
├── docs
│   ├── conf.py
│   └── index.rst
└── myproject
    ├── _impl.py
    └── __init__.py
```

`__init__.py`:

```python
from ._impl import A, create_A_from_outside
```

`_impl.py`:

```python
from __future__ import annotations

class A:
    "A lovely class."
    @classmethod
    def create_A_from_inside(cls) -> A:
        "Inside."
        return A()
    @classmethod
    def create_A_again_from_inside(cls) -> 'A':
        "Inside again."
        return A()

def create_A_from_outside() -> A:
    "Outside."
    return A()
```

`conf.py`:

```python
project = 'myproject'
copyright = '2020, someone'
author = 'someone'
extensions = [
    'sphinx.ext.autodoc',
]
html_theme = 'alabaster'
```

`index.rst`:

```rst
Welcome to myproject's documentation!
=====================================

.. automodule:: myproject
   :members:
   :imported-members:
```

**Screenshots**

![Screenshot_2020-12-27_21-54-32](https://user-images.githubusercontent.com/325476/103192620-2d730280-488e-11eb-9364-1e1de3a7f79c.png)

Note how `A`s are treated differently in these functions, simply because `create_A_again_from_inside` is annotated with string `'A'`. If I remove `from __future__ import annotations` from `_impl.py`, and quote all occurrences of `A`:

```python
class A:
    "A lovely class."
    @classmethod
    def create_A_from_inside(cls) -> 'A':
        "Inside."
        return A()
    @classmethod
    def create_A_again_from_inside(cls) -> 'A':
        "Inside again."
        return A()

def create_A_from_outside() -> 'A':
    "Outside."
    return A()
```

I got:

![Screenshot_2020-12-27_22-01-32](https://user-images.githubusercontent.com/325476/103192860-1ed91b00-488f-11eb-8075-2c2694c59ac8.png)

Note that all `'A'`s are resolved to `myproject._impl.A`.

**Environment info**
- OS: Debian 10
- Python version: 3.7.3
- Sphinx version: 3.4.1
- Sphinx extensions:  `sphinx.ext.autodoc`

**Comment by tk0miya** [comment]
The behavior is based on `typing.get_type_hints()`. The case annotated by string `'A'` is considered as `ForwardRef('A')` in python3.8. But others are considered as `_impl.A`. So it is hard to fix it from Sphinx side.
```
$ python
Python 3.8.2 (default, Mar  2 2020, 00:44:41)
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import _impl
>>> import typing
>>> typing.get_type_hints(_impl.A.create_A_from_inside)
{'return': <class '_impl.A'>}
>>> typing.get_type_hints(_impl.A.create_A_again_from_inside)
{'return': ForwardRef('A')}
>>> typing.get_type_hints(_impl.create_A_from_outside)
{'return': <class '_impl.A'>}
```

FYI: It seems the behavior is fixed in the latest Python release. So it will be fixed by upgrading your python.
```
$ python3.9
Python 3.9.1 (default, Dec 18 2020, 00:18:40)
[Clang 11.0.3 (clang-1103.0.32.59)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import _impl
>>> import typing
>>> typing.get_type_hints(_impl.A.create_A_from_inside)
{'return': <class '_impl.A'>}
>>> typing.get_type_hints(_impl.A.create_A_again_from_inside)
{'return': <class '_impl.A'>}
>>> typing.get_type_hints(_impl.create_A_from_outside)
{'return': <class '_impl.A'>}
```

**Comment by xuhdev** [comment]
I can confirm using Python 3.9 fixes the issue above. Thanks for the quick reply!
