### ISSUE TITLE
building psf/requests documentation fails with AttributeError: 'LookupDict' object has no attribute '__name__'

### ISSUE THREAD

**Issue by eriol** [sphinx-doc/sphinx#8616]
**Describe the bug**

Since sphinx 3.4.1 building [psf/requests](https://github.com/psf/requests/) documentation fails with the following:
```
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v3.4.1
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://urllib3.readthedocs.io/en/latest/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 15 source files that are out of date
updating environment: [new config] 15 added, 0 changed, 0 removed
reading sources... [  6%] api                                                                                                                                                                
Exception occurred:
  File "/usr/lib/python3/dist-packages/sphinx/util/typing.py", line 160, in _restify_py37
    return ':obj:`%s.%s`' % (cls.__module__, cls.__name__)
AttributeError: 'LookupDict' object has no attribute '__name__'
The full traceback has been saved in /tmp/sphinx-err-yt45bplo.log, if you want to report the issue to the developers.
```
Attached the full log: [sphinx-err-yt45bplo.log](https://github.com/sphinx-doc/sphinx/files/5751590/sphinx-err-yt45bplo.log)

The issue is not reproducible using sphinx 3.3.1.

**To Reproduce**
In addiction to build requests' documentation I managed to reproduce the issue in the interactive python console using the following:
```
Python 3.9.1 (default, Dec  8 2020, 07:51:42) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> import sphinx
>>> requests.__version__
'2.25.0'
>>> sphinx.__version__
'3.4.1'
>>> from requests import codes
>>> from sphinx.util.typing import restify
>>> restify(codes)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/sphinx/util/typing.py", line 103, in restify
    return _restify_py37(cls)
  File "/usr/lib/python3/dist-packages/sphinx/util/typing.py", line 160, in _restify_py37
    return ':obj:`%s.%s`' % (cls.__module__, cls.__name__)
AttributeError: 'LookupDict' object has no attribute '__name__'
```

I'm able to reproduce the issue in a clean virtualenv with only requests and sphinx installed.

Thanks!

**Comment by ConstantinoSchillebeeckx** [comment]
I'm seeing the same building docs with Airflow
```
File "/somewhere/lib/python3.7/site-packages/sphinx/util/typing.py", line 158, in _restify_py37
    return ':obj:`%s.%s`' % (cls.__module__, cls.__name__)
AttributeError: 'PythonOperator' object has no attribute '__name__'
```

Downgrading to 3.3.1 avoids the issue.

**Comment by tk0miya** [comment]
It seems requests' document is using `autoclass` for `requests.codes`.
https://github.com/psf/requests/blob/4f6c0187150af09d085c03096504934eb91c7a9e/docs/api.rst

But it is not a class. Is this mark-up intended?
https://github.com/psf/requests/blob/4f6c0187150af09d085c03096504934eb91c7a9e/requests/status_codes.py#L105

I don't know autoclass directive should support non-class items. But it is not intended to make a breaking change. So I'll try to fix it if possible.

**Comment by tk0miya** [comment]
@ConstantinoSchillebeeckx Is your case the same as requests' case? Please check your document. If not, please file another issue to investigate your case in detail.

**Comment by eriol** [comment]
@tk0miya many thanks for the analysis and the fix! That line was not touched in 5 years, so I think that since just worked it was used and never touched again.

**Comment by tk0miya** [comment]
@eriol :-)  I recommend you to use `autodata` directive for variables instead of `autoclass`. At present, Sphinx renders it as an attribute. But the behavior might be changed because the author considers it is a "class".
