### ISSUE TITLE
Search never stops searching, fails

### ISSUE THREAD

**Issue by pedrohdz** [sphinx-doc/sphinx#8623]
**Describe the bug**
From `3.4.0` on, it seems as if the search functionality is broken.

The error found in the browser console:

```
Uncaught ReferenceError: Stemmer is not defined
    query http://localhost:8000/_static/searchtools.js:158
    setIndex http://localhost:8000/_static/searchtools.js:98
    <anonymous> http://localhost:8000/search/?q=jenkin&check_keywords=yes&area=default# line 2 > injectedScript:1
```

This issue seems to be directly related to the fix for https://github.com/sphinx-doc/sphinx/issues/8419 in PR https://github.com/sphinx-doc/sphinx/pull/8445.

**To Reproduce**

1. Create a site using `3.4.0` or later.
2. Try and search for something on the site.
3. Watch the search page run for ever...

**Expected behavior**

For search to function.

**Environment info**
- Docker image with:
   ```
   FROM sphinxdoc/sphinx:latest
   ```

**Workaround**
 Pin to version `3.3.1` or earlier.

**Comment by tk0miya** [comment]
Are you using sphinx_rtd_theme?  If so, it was already fixed by sphinx_rtd_theme. Please install it from the its repository. see readthedocs/sphinx_rtd_theme#1021.
refs: https://github.com/sphinx-doc/sphinx/issues/8603.

**Comment by pedrohdz** [comment]
I am using that theme!  I will give it a try on Monday.  I will update the issue then.

Thank you so much for the quick response!

**Comment by pedrohdz** [comment]
That did this trick!  Thanks again for the quick response @tk0miya!

**Comment by stsewd** [comment]
Hi everyone I'll see if I can cut a new release of the theme this week!

**Comment by stsewd** [comment]
Just released 0.5.1 https://pypi.org/project/sphinx-rtd-theme/ Let us know if that works!

**Comment by pedrohdz** [comment]
Works!  Thank you @stsewd!  I appreciate the quick response!

**Comment by tk0miya** [comment]
Congrats!
