### ISSUE TITLE
autosummary's custom template only applies to the first module

### ISSUE THREAD

**Issue by xuhdev** [sphinx-doc/sphinx#8637]
**Describe the bug**
When multiple modules are listed in autosummary and a custom template  is specified, it only applies to the first entry.

**To Reproduce**

1. Unarchive [bug.tar.gz](https://github.com/sphinx-doc/sphinx/files/5758743/bug.tar.gz).
2. Run `PYTHONPATH=. sphinx-build -d "./_build" docs "_build/html" -b html -W --color`

Some key facts:

In bug.tar.gz:

```
├── docs
│   ├── conf.py
│   ├── index.rst
│   └── _templates
│       └── my-module.rst
└── main
    ├── __init__.py
    └── sub.py
```

conf.py is minimal:

```python
project = 'aaa'

extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.autosummary',
]

autosummary_generate = True

templates_path = ['_templates']
```

index.rst:

```rst
My Documentation
================

.. autosummary::
   :toctree: apis
   :recursive:
   :template: my-module.rst

   main
   main.sub
```

`my-module.rst` is copied from `sphinx/ext/autosummary/templates/autosummary/module.rst`, with **a new line of text `This is my template...` inserted under title**:

```rst
{{ fullname | escape | underline}}

This is my template...

... rest is the same as the default module.rst
```

After run `sphinx-build` as above, `docs/apis/main.sub.rst` doesn't have this new line while `docs/apis/main.rst` has.

**Expected behavior**

Both `main` and `main.sub` should apply the custom template and include the new line.

**Environment info**
- OS: Debian 10
- Python version: 3.7.3
- Sphinx version: 3.4.1
- Sphinx extensions:  autosummary

**Comment by xuhdev** [comment]
However, after deleting `main` under `autosummary::`, `docs/apis/main.sub.rst` has the new line included.

**Comment by tk0miya** [comment]
It seems the autosummary directive in `index.rst` generates `apis/main.rst` and `api/main.sub.rst` with `_templates/my-module.rst`.  After that, the autosummary directive in `api/main.rst` overwrites `api/main.sub.rst` with standard template. I think you should also add `:template: my-module.rst` to your `my-module.rst` template.

Additionally, you don't need to list `main.sub` to the `index.rst` because you're using `:recursive:` option.

Thanks,

**Comment by xuhdev** [comment]
@tk0miya Thanks, that did solve the problem. Is it possible to add a proper warning for this? Seems like these things can go undetected.

**Comment by tk0miya** [comment]
I don't know "a proper warning". Do you have an idea?

**Comment by xuhdev** [comment]
A warning when overriding existing files such as:

    [WARNING] some-file.rst exists. Autosummary is overriding it...

I'm not sure how it would fit into the existing codebase (e.g., does sphinx have a task dependency system like "make" as in "Makefile"?), just think it would be good if something like this can be added.

**Comment by tk0miya** [comment]
I think such a warning harms rebuild because it is always emitted by the stub files generated in the last build. I guess what you really want is a warning for writing a stub file for the same object twice in the build. But I don't understand it is wrong really behavior.

**Comment by xuhdev** [comment]
I can tell it's a bit difficult to actually know something's wrong. I'll close this for now.
