### ISSUE TITLE
cmdoption permalinks don't work for uppercase letters

### ISSUE THREAD

**Issue by mgeier** [sphinx-doc/sphinx#8662]
This link used to work:

https://www.sphinx-doc.org/en/master/man/sphinx-build.html#cmdoption-sphinx-build-W

The links on the same page with lowercase letters work fine, e.g. https://www.sphinx-doc.org/en/master/man/sphinx-build.html#cmdoption-sphinx-build-w

Uppercase options seem to get an auto-generated permalink: https://www.sphinx-doc.org/en/master/man/sphinx-build.html#id6

**Expected behavior**

A working link to https://www.sphinx-doc.org/en/master/man/sphinx-build.html#cmdoption-sphinx-build-W (and other uppercase options)

**Comment by tk0miya** [comment]
It seems our document was built with Sphinx-1.8.5. I guess readthedocs downgrade the default version of Sphinx.

Build log at Jan 6th: It used 3.5.0+.
https://readthedocs.org/projects/sphinx/builds/12705105/

Build log at Jan 7th: It used 1.8.5.
https://readthedocs.org/projects/sphinx/builds/12712472/

**Comment by tk0miya** [comment]
I reported this as https://github.com/readthedocs/readthedocs.org/issues/7816

**Comment by mgeier** [comment]
Thanks for reporting this!

I was wondering: where is the RTD configuration for this project?

There doesn't seem to be a `.readthedocs.yml` file, right?

I would expect something like this in there:

```yml
python:
  version: 3
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
```

See https://docs.readthedocs.io/en/stable/config-file/v2.html#python.

Maybe this would solve the problem?

**Comment by tk0miya** [comment]
I posted #8666, but it seems not working. 

>I was wondering: where is the RTD configuration for this project?

AFAIK, we've not used configuration file. We've used web console only.

**Comment by mgeier** [comment]
> I posted #8666, but it seems not working.

Just out of curiosity, do you happen to have the RTD build log for that?

**Comment by mgeier** [comment]
Never mind, I found it: https://readthedocs.org/projects/sphinx/builds/12728739/

It seems to work well at some point:

```
...
creating 'dist/Sphinx-3.5.0.dev20210110-py3.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing Sphinx-3.5.0.dev20210110-py3.7.egg
creating /home/docs/checkouts/readthedocs.org/user_builds/sphinx/envs/8666/lib/python3.7/site-packages/Sphinx-3.5.0.dev20210110-py3.7.egg
Extracting Sphinx-3.5.0.dev20210110-py3.7.egg to /home/docs/checkouts/readthedocs.org/user_builds/sphinx/envs/8666/lib/python3.7/site-packages
Adding Sphinx 3.5.0.dev20210110 to easy-install.pth file
Installing sphinx-apidoc script to /home/docs/checkouts/readthedocs.org/user_builds/sphinx/envs/8666/bin
Installing sphinx-autogen script to /home/docs/checkouts/readthedocs.org/user_builds/sphinx/envs/8666/bin
Installing sphinx-build script to /home/docs/checkouts/readthedocs.org/user_builds/sphinx/envs/8666/bin
Installing sphinx-quickstart script to /home/docs/checkouts/readthedocs.org/user_builds/sphinx/envs/8666/bin

Installed /home/docs/checkouts/readthedocs.org/user_builds/sphinx/envs/8666/lib/python3.7/site-packages/Sphinx-3.5.0.dev20210110-py3.7.egg
Processing dependencies for Sphinx==3.5.0.dev20210110
...
```

But later, when running Sphinx, it says:

```
Running Sphinx v1.8.5
...
```

Very strange ...

**Comment by mgeier** [comment]
@tk0miya Thanks for the quick fix!
