### ISSUE TITLE
Unclear documentation of ` html_baseurl`

### ISSUE THREAD

**Issue by xuhdev** [sphinx-doc/sphinx#8677]
The document says:

> The URL which points to the root of the HTML documentation. It is used to indicate the location of document like `canonical_url`.

I searched the whole repo but didn't found `canonical_url` mentioned anywhere else.

Additionally, does `html_baseurl` default to `''`?

**Comment by tk0miya** [comment]
Wow, it describes nothing...

**Comment by tk0miya** [comment]
I posted #8678 yesterday. Is this helping you?

**Comment by xuhdev** [comment]
This is perfect! Thanks!
