### ISSUE TITLE
html_last_updated_fmt does not support UTC offset (%z)

### ISSUE THREAD

**Issue by th0ger** [sphinx-doc/sphinx#8683]
According to Sphinx docs, [html_last_updated_fmt](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_last_updated_fmt) uses the `strftime()`.
The [python strftime format codes](https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes) defines: `%z`  as *UTC offset in the form ±HHMM[SS[.ffffff]] (empty string if the object is naive).*

However, with:
```
html_last_updated_fmt = '%Y-%m-%d %H:%M:%S %z'
```
I get a literal `%z` at output:
```
© Copyright 2020, .... Revision 81dbc58. Last updated on 2021-01-12 07:34:52 %z.
```
The expected output in my case is `... +0100`.

Notes:
- Uppercase `%Z` (*Time zone name*) does "work". On my local box is gives `GMT+01:00`, but on our CI pipeline is gives the full string `Coordinated Universal Time` which is a bit anoying. I guess it may be platform dependent.
The "literal %z"-issue occurs on both platforms.
- Some basic testing with Python, shows that `%z` works well with `strftime()`.
- I have tested all other format tokens and they all work, except `%U` and `%W` (week numbers) which throws an exception. Someone may want to raise a separate issue for this.

**Comment by tk0miya** [comment]
Thank you for reporting. Both `%z` and `%Z` are bugs.

**Comment by th0ger** [comment]
@tk0miya thanks for fixing. 
I see that `test_format_date()` needs a little love to fully cover https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes
For example `%U` and `%W` which fails for me. Will you create an issue for this?

**Comment by tk0miya** [comment]
Could you try to make a pull request instead of issue? Contributions are always welcome :-)
