### ISSUE TITLE
Having a `main_doc` instead of `master_doc` in the configuration

### ISSUE THREAD

**Issue by Mariatta** [sphinx-doc/sphinx#8687]
**Is your feature request related to a problem? Please describe.**

It would be great to use `main_doc` instead of `master_doc` in the Sphinx configuration file.
https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-master_doc

**Describe the solution you'd like**

Perhaps for backward compatibility, the configuration can support either one of `master_doc` and `main_doc` instead of completely replacing it.

Thanks for considering.

**Comment by mgeier** [comment]
See #8326 and #8484.
