### ISSUE TITLE
build a translated rst

### ISSUE THREAD

**Issue by fanhao0915** [sphinx-doc/sphinx#8688]
Dear team,

Is there any chance that we can build a translated rst in addition to xml, epub, text...by following the pot/po workflow?

Thank you in advance.

**Comment by tk0miya** [comment]
-1 for adding a new builder to the Sphinx core more because of maintenance costs.

BTW, I know an extension that converts the documents to the reST: https://pypi.org/project/sphinx-rst-builder/. How about using this?

**Comment by fanhao0915** [comment]
@tk0miya Thank you so much for your advise. I tried "sphinx-rst-builder" and it worked well with pot/po. However the i18n project out team has been working on is looking for a "mirrored" rst, rather than a "published" rst. Our goal is to only replace the English strings with the target strings in the original rst and maintain everything else.

**Comment by tk0miya** [comment]
The internal data structure of reST parser is irreversible. So there is no way to generate the original notation of the reST document via a program. Of course, there is no tool to apply translations to the original reST documents too.

**Comment by fanhao0915** [comment]
Thank you again for the info ! @tk0miya
