### ISSUE TITLE
:kbd: role with Caps Lock rendered incorrectly

### ISSUE THREAD

**Issue by madjxatw** [sphinx-doc/sphinx#8714]
**Describe the bug**

`` :kbd:`Caps Lock` `` produces:

```html
<kbd class="kbd compound docutils literal notranslate">
  <kbd class="kbd docutils literal notranslate">Caps</kbd>
  <kbd class="kbd docutils literal notranslate">Lock</kbd>
</kbd>
```

**Expected behavior**

```html  
<kbd class="kbd docutils literal notranslate">Caps Lock</kbd>
```

**Environment info**
- OS: Debian unstable
- Python version: 3.9.1
- Sphinx version: 82ef497a8

**Comment by madjxatw** [comment]
The same issue goes with other keys like "Page Up", "Page Down"...

**Comment by tk0miya** [comment]
Absolutely. But we have to separate ```:kbd:`M-x M-s` ``` to two keystrokes....
