### ISSUE TITLE
Referencing :cpp:enum-class: doesn't work as it should be.

### ISSUE THREAD

**Issue by GinkoBalboa** [sphinx-doc/sphinx#8718]
**Describe the bug**
I have defined a cpp enum class 

.. :cpp:enum-class:`MyEnumClass`

When I try to reference it with :cpp:enum-class:`MyEnumClass`, raises a warning and the reference is not working, so I have to use :cpp:enum: instead.

**To Reproduce**
```
$ ./make html
```

**Expected behavior**
I expect that for every definition should be corresponding ref key word. 

**Your project**
[sphinx_bug.zip](https://github.com/sphinx-doc/sphinx/files/5850054/sphinx_bug.zip)

**Screenshots**
None

**Environment info**
- OS: Win
- Python version: 3.7.7
- Sphinx version: 3.0.2
- Sphinx extensions:  None
- Extra tools: Browser

**Additional context**

- [e.g. URL or Ticket]

**Comment by jakobandersen** [comment]
I'm not sure I would consider this a bug. A scoped enum is still an enum so I think it is fine that the ``enum`` role is used for cross-referencing (arguably the ~~``struct``~~ ``var`` and ``member`` roles are similarly redundant).
Should potential ``enum-struct`` and ``enum-class`` roles have a different behaviour than the current ``enum`` role?

**Comment by GinkoBalboa** [comment]
It is ok if you are fine with inconsistencies in your code: having a role ``enum-class`` that cannot be referenced as ``enum-class``. I'm just trying to be helpful here, as I find sphinx very useful. I agree with you that ``enum-class`` and ``enum`` should have the same behavior. But currently, they don't have the same behavior, i.e. referencing with ``enum-class`` doesn't work.

**Comment by jakobandersen** [comment]
I don't follow the argument for inconsistency and as there would be no difference in behaviour I find it would be unnecessarily redundant (I would rather go towards removing the already redundant functionality).

**Comment by GinkoBalboa** [comment]
If you remove ``enum-class`` role, you will break backward compatibility. Then you'll have a much more severe issue than this.

**Comment by jakobandersen** [comment]
With the removal I referred to my previous comment about the ``var``/``member`` roles/directives (though I see now that I wrote ``struct`` instead of ``var``), but as you point out, it will break backward compatibility so should be done carefully.
The ``enum``, ``enum-class``, and ``enum-struct`` directives have different behaviour, so there is no direct redundancy.

Anyway, as there is no new information I'm closing the issue for now. Feel free to reopen should some come to light.
