### ISSUE TITLE
ValueError: No template sub-directory with name 'rst' found in the following paths

### ISSUE THREAD

**Issue by Manish-Flexcompute** [sphinx-doc/sphinx#8725]
.\make.bat html
Running Sphinx v3.4.3

Exception occurred:
  File "C:\Users\manis\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\nbconvert\exporters\templateexporter.py", line 601, in get_template_names
    raise ValueError('No template sub-directory with name %r found in the following paths:\n\t%s' % (base_template, paths))
ValueError: No template sub-directory with name 'rst' found in the following paths:
        C:\Users\manis\AppData\Roaming\jupyter
        C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\share\jupyter
        C:\ProgramData\jupyter
The full traceback has been saved in C:\Users\manis\AppData\Local\Temp\sphinx-err-eh766ct7.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
[sphinx-err-eh766ct7.log](https://github.com/sphinx-doc/sphinx/files/5852531/sphinx-err-eh766ct7.log)

**Comment by tk0miya** [comment]
>File "C:\Users\manis\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\nbconvert\exporters\templateexporter.py", line 601, in get_template_names

It seems this error was raised by nbconvert. I guess this might be a trouble of the extension. Could you ask it again to their community.
Thanks,
