### ISSUE TITLE
sphinx==3.4.2 

### ISSUE THREAD

**Issue by awais786** [sphinx-doc/sphinx#8742]
After upgrading to 3.4.2 `make docs` command giving error. Any idea why this error is appearing ?

```
value = self.settings[key]
KeyError: '__sphinx_mock__'
```
Python3.8
Django2.2

**Comment by tk0miya** [comment]
It might be related to https://github.com/sphinx-doc/sphinx/issues/8655. Please update 3.4.3. If not resolved even if updated, please report your trouble in details. To understand what happened in your environment, we need to know your environment. So please fill our issue template.
Thanks,
