### ISSUE TITLE
Get Error 500 when tuning multiple models

### ISSUE THREAD

**Issue by DalilaB000** [sphinx-doc/sphinx#8761]
**Describe the bug**
I choose all Auto-Tuned Word N-gram for all text features and tune them.  I tried the job.wait_for_completion() after each job starts running, I also decided to check if all job complete by creating a small loop

   ```
 while project.get_all_jobs():
        time.sleep(5)
```

```
text_feature = model_p.text_feature
        model_id = model_p.model_id
        model_1,tune = prepare_model_for_tuning(model_id,project)
        try:
            tune2 = set_parameters(3, tune)
            print("tune ", index)
            job = tune2.run()
            tmp_df= tmp_df.append({"model_id":job.model_id,'text_feature':text_feature,'parameters_modified':3}, \
                                      ignore_index= True)
            job.wait_for_completion()
        except JobAlreadyRequested:
            print("duplicate Job")
        model_1,tune = prepare_model_for_tuning(model_id,project)
```
Sometimes, the application finishes with no problems, but sometimes I get Error 500 
```
while project.get_all_jobs():
      time.sleep(5)
  File "/Users/dalila.benachenhou/Documents/Fake_Posting/Blend_Models/src/Detecting_Fake_Jobs.py", line 420, in <module>
    result_df = rerun_text_models_with_new_param(project)
  File "/Users/dalila.benachenhou/Documents/Fake_Posting/Blend_Models/src/Detecting_Fake_Jobs.py", line 384, in rerun_text_models_with_new_param
    model_tuned_df = run_auto_tuned_with_different_settings(models_df, project)
  File "/Users/dalila.benachenhou/Documents/Fake_Posting/Blend_Models/src/Detecting_Fake_Jobs.py", line 259, in run_auto_tuned_with_different_settings
    while project.get_all_jobs():
  File "/Users/dalila.benachenhou/anaconda3/envs/allennlp/lib/python3.7/site-packages/datarobot/models/project.py", line 2432, in get_all_jobs
    res = self._client.get(url, params=params).json()
  File "/Users/dalila.benachenhou/anaconda3/envs/allennlp/lib/python3.7/site-packages/datarobot/rest.py", line 124, in get
    return self.request("get", url, params=to_api(params), **kwargs)
  File "/Users/dalila.benachenhou/anaconda3/envs/allennlp/lib/python3.7/site-packages/datarobot/rest.py", line 120, in request
    handle_http_error(response, **kwargs)
  File "/Users/dalila.benachenhou/anaconda3/envs/allennlp/lib/python3.7/site-packages/datarobot/rest.py", line 260, in handle_http_error
    raise errors.ServerError(exc_message, response.status_code)
datarobot.errors.ServerError: 500 server error: {'message': 'Internal Server Error'} (edited) 
```

**To Reproduce**
```
<Paste your command-line here which cause the problem>

$ git clone https://github.com/.../some_project
$ cd some_project
$ pip install -r requirements.txt
$ cd docs
$ make html SPHINXOPTS="-D language=de"
$ # open _build/html/index and see bla bla
```

**Expected behavior**

**Your project**
Link to your sphinx project, or attach zipped small project sample.

**Screenshots**

**Environment info**
- OS: [e.g. Unix/Linux/Mac/Win/other with version]
- Python version: [e.g. 3.7.1]
- Sphinx version: [e.g. 1.8.2]
- Sphinx extensions:  [e.g. sphinx.ext.autodoc, recommonmark]
- Extra tools: [e.g. Browser, tex or something else]

**Additional context**

- [e.g. URL or Ticket]

**Comment by tk0miya** [comment]
Excuse me, is this a bug of Sphinx? Please describe what are you doing. Thanks,

**Comment by DalilaB000** [comment]
I’m tuning multiple models at the same time, and then I’m blending these models into 1 model.

Regards,

Dalila Benachenhou
Execution Data Scientist
Phone 202-427-4631
DataRobot
Join us online: DataRobot.com <https://www.datarobot.com/> | LinkedIn <https://www.linkedin.com/company/datarobot> | Facebook <https://www.facebook.com/datarobotinc/> | Twitter <https://twitter.com/DataRobot> | Instagram <https://www.instagram.com/datarobot/>
BOSTON   NEW YORK   SAN FRANCISCO   WASHINGTON DC   LONDON   MUNICH   KYIV   SAO PAULO   SEOUL   SINGAPORE   SYDNEY   TOKYO

**Comment by tk0miya** [comment]
Sorry, I can't understand what you're saying. I think your trouble does not relate to Sphinx at all. So I recommend you to post to other place. Thanks,
