### ISSUE TITLE
`AttributeError` when using X | Y type hinting syntax with sphinx.ext.autodoc

### ISSUE THREAD

**Issue by adamtheturtle** [sphinx-doc/sphinx#8775]
**Describe the bug**

Using type syntax like `name: str | int` is now supported in Python (with an import from `__future__`) but `autodoc`-ing a class which uses this syntax produces an `AttributeError`.

**To Reproduce**

I have the following sample project:

Python 3.9.1

```
.
├── docs
│   └── source
│       ├── conf.py
│       └── index.rst
└── example_module.py
```

`docs/source/conf.py`:

```python
import os
import sys

sys.path.insert(0, os.path.abspath('../..'))
extensions = ['sphinx.ext.autodoc']
```

`docs/source/index.rst`:

```rst
.. autoclass:: example_module.Foo
   :members:
   :undoc-members:
```

`example_module.py`:

```python
from __future__ import annotations

class Foo:
    # See http://mypy-lang.blogspot.com/2021/01/mypy-0800-released.html
    # for a description of this syntax.
    name: str | int
```

Command:
    
```
sphinx-build -b html docs/source/ docs/build
```

**Expected behavior**

No error.
Sphinx builds documentation which makes it clear that `name` can be an `int` or a `str`.

**Environment info**
- OS: macOS 11.1
- Python version: 3.9.1
- Sphinx version: 3.4.3
- Sphinx extensions:  `sphinx.ext.autodoc`

**Comment by tk0miya** [comment]
autodoc uses python interpreter itself to recognize type hints. So you need to run Sphinx under python 3.10 to recognize union types operator.

**Comment by adamtheturtle** [comment]
@tk0miya Thank you for your response. This is a topic I'm not super familiar with but my hope was that as the type checking works under 3.9.1 (given the `__future__` import), so would `autodoc`.

**Comment by tk0miya** [comment]
No, it is not related to your python interpreter. mypy-0.800 supports the new Union syntax, not python itself. So it will also work when you're using new mypy even with python-3.8. autodoc can support the syntax if somebody sends us a patch!

**Comment by adamtheturtle** [comment]
Great, and thanks for the work I can see already on this from you @tk0miya . Your work on this project is a gift 🙏

**Comment by tk0miya** [comment]
Now I posted #8805 to avoid the crash by union types operator. But it does not mean Sphinx supports it with Python 3.9 or below. I think it is a workaround because it disables `autodoc_type_alises` feature when the error is raised internally. I don't know it's really worthy. But it would work well for some people. Thanks,
