### ISSUE TITLE
optional rST directive

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#879]
It would be nice to have another restructured text directive to create an "optional" box, like the "note" or "see also" directives. Would be particularly useful for increasing clarity in tutorials and instructions.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/879
- Originally reported by: [tychoish](https://bitbucket.org/tychoish)
- Originally created at: 2012-02-15T19:06:46.631

**Comment by shimizukawa** [comment]
_From Robert Lehmann on 2012-02-15 19:04:19+00:00_

Would generic admonitions suit your use case?  http://docutils.sourceforge.net/docs/ref/rst/directives.html#generic-admonition

**Comment by shimizukawa** [comment]
_From [tychoish](https://bitbucket.org/tychoish) on 2012-02-16 20:28:00+00:00_

I've managed to work up an extension that works for my use case, and I think that's good enough for now. I'm happy to close this ticket if it's not something that you're likely to include or peruse, but I think it would be a useful improvement if you want to leave the ticket open for the future development that's fine.

**Comment by stephenfin** [comment]
As Robert Lehmann suggested, we can use the generic admonition for this. In any case, admonitions are in the remit of docutils and not Sphinx. I think this can be closed?

**Comment by shimizukawa** [comment]
Thanks, I also think that it is good to use admonition.
