### ISSUE TITLE
Sphinx autodoc no longer accepts 'Any' in Dict parent class declaration

### ISSUE THREAD

**Issue by anselor** [sphinx-doc/sphinx#8818]
**Describe the bug**
In my case, I have a class that is a subclass of a `Dict[str, Any]`. 
I get the following error starting in sphinx 3.4.0:
`subclass_dict.py:docstring of issue.any_unknown.subclass_dict.MyData:1:py:obj reference target not found: Any`

**To Reproduce**

```
$ git clone https://github.com/anselor/sphinx-issues-examples/
$ cd sphinx-issues-examples/typevar-namespace
$ python -m sphinx -b html docs/ doc-out/ -nvWT
```

**Expected behavior**
It shouldn't generate an error since this is valid python

**Your project**
https://github.com/anselor/sphinx-issues-examples/tree/main/typevar-namespace

**Screenshots**

**Environment info**
- OS: Ubuntu 18.04, 20.04
- Python version: 3.6.9, 3.8.2
- Sphinx version: 3.4.0 and greater
- Sphinx extensions:  sphinx.ext.autodoc
- Extra tools: 

**Additional context**

- [e.g. URL or Ticket]

**Comment by anselor** [comment]
@tk0miya It really seems like I can't use anything from typing inside of Optional[] or Dict[]. Any doesn't work. And I'm having trouble with NewType declarations resolving either.

**Comment by hoefling** [comment]
Bisecting shows first bad commit e2bf9166da3e89eb7cbe7abb9c1e47e34351bbf8, first introduced in v3.4.0 release.

**Comment by hoefling** [comment]
A temporary workaround could be resolving the failing refs to typing members yourself, for example by extending the `conf.py` with
```py
from sphinx.ext.intersphinx import missing_reference

def setup(app):
    app.connect("missing-reference", __sphinx_issue_8818)

def __sphinx_issue_8818(app, env, node, contnode):
    reftarget = node.get("reftarget", None)
    import typing
    try:
        obj = getattr(typing, reftarget)
        node["reftarget"] = f"typing.{reftarget}"
        return missing_reference(app, env, node, contnode)
    except AttributeError as e:
        return None
```
