### ISSUE TITLE
User-friendly error message for broken search in WebKit browsers

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#882]
It would be much more friendly if Sphinx could tell users what to do in reaction to https://github.com/sphinx-doc/testing/issues/723

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/882
- Originally reported by: anatoly techtonik
- Originally created at: 2012-02-18T13:09:13.445

**Comment by tk0miya** [comment]
Sorry, I can't understand the problem...

**Comment by tk0miya** [comment]
This is related with #723. And it seems already resolved.
