### ISSUE TITLE
Manual isn't clear on how to handle parallel reading in an extension

### ISSUE THREAD

**Issue by brechtm** [sphinx-doc/sphinx#8829]
It's not clear to me from the manual which event handlers are affected by parallel reading of the source files. I'm _assuming_ that when an extension implements any of the [event handlers](https://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx-core-events) between 4 and 9 (exclusive), it should also implement _env-merged-info_. Is that correct?

For example, my extension only provides an _env-before-read-docs_ handler. Am I correct in assuming that it is always safe for parallel reading in this case?

Perhaps Sphinx could automatically determine when an extension is safe for parallel reading? If my assumption above is correct, extensions that do not register handlers for events 5-8 are always safe?

**Comment by tk0miya** [comment]
>I'm assuming that when an extension implements any of the event handlers between 4 and 9 (exclusive), it should also implement env-merged-info. Is that correct?

No, it's only mandatory only if you're storing custom data to the env object.

> For example, my extension only provides an env-before-read-docs handler. Am I correct in assuming that it is always safe for parallel reading in this case?

Yes. It's emitted before invoking subprocesses. It means your extension is not related to parallel processing at all. Therefeore, your extension is parallel reading safe.

>Perhaps Sphinx could automatically determine when an extension is safe for parallel reading? If my assumption above is correct, extensions that do not register handlers for events 5-8 are always safe?

No, it can't. We don't have the way to know the extension can read or write docs parallelly. How we can know if some extension crashes by dead-lock on parallel execution?

**Comment by brechtm** [comment]
Thanks for the clarifications, @tk0miya. It's still not 100% clear to me however, so please allow me to follow up with some more questions below.

> > I'm assuming that when an extension implements any of the event handlers between 4 and 9 (exclusive), it should also implement env-merged-info. Is that correct?
> 
> No, it's only mandatory only if you're storing custom data to the env object.

But only when you change the env object in any of the event handlers 5-8, right? I don't know whether it's even allowed to change the env object in other handlers.

> > For example, my extension only provides an env-before-read-docs handler. Am I correct in assuming that it is always safe for parallel reading in this case?
> 
> Yes. It's emitted before invoking subprocesses. It means your extension is not related to parallel processing at all. Therefeore, your extension is parallel reading safe.

Thanks for confirming!

> > Perhaps Sphinx could automatically determine when an extension is safe for parallel reading? If my assumption above is correct, extensions that do not register handlers for events 5-8 are always safe?
> 
> No, it can't. We don't have the way to know the extension can read or write docs parallelly. How we can know if some extension crashes by dead-lock on parallel execution?

Sorry, I was not clear enough. I meant to say that if the extension **doesn't implement** any of the event handlers 5-8, it cannot possibly change the env object and thus is guaranteed to be parallel-read-safe. Is that correct? In this case, Sphinx would (in theory) not need to be informed by the extension (setting `parallel_read_safe`).

Of course, if the extension **does implement** any of the event handlers 5-8, it *could* be changing the env object, so it could still be parallel-read-safe. In that case, `parallel_read_safe` would need to be set explicitly.

While it would be nice if Sphinx could automatically determine whether an extension is parallel-read-safe *in some cases*, I mainly want to improve the documentation.

**Comment by tk0miya** [comment]
>But only when you change the env object in any of the event handlers 5-8, right? I don't know whether it's even allowed to change the env object in other handlers.

Yes, you need to implement `env-merged-info` to support parallel builds if your extension hooks 5-8 steps and modifies the env object.

>I meant to say that if the extension doesn't implement any of the event handlers 5-8, it cannot possibly change the env object and thus is guaranteed to be parallel-read-safe.

Almost yes. But you also need to pay attention to other components. Source parsers, directives, roles, transforms and other components working during 5-8 steps are related to the parallel-readability.

To make an extension parallel-read-safe, 1) it must handle `env-merged-info` if it modifies the env object during 5-8 steps, 2)   its components can work even if invoked parallelly during 5-8 steps.

**Comment by brechtm** [comment]
> > I meant to say that if the extension doesn't implement any of the event handlers 5-8, it cannot possibly change the env object and thus is guaranteed to be parallel-read-safe.
> 
> Almost yes. But you also need to pay attention to other components. Source parsers, directives, roles, transforms and other components working during 5-8 steps are related to the parallel-readability.

This only clicked with me now, after running into issues 😊. How about making this more explicit in the manual where [parallel_read_safe](https://www.sphinx-doc.org/en/master/extdev/index.html?highlight=parallel_read_safe#extension-metadata) is described? Here's a start:

_An extension is not parallel read safe if it changes the Sphinx [environment](https://www.sphinx-doc.org/en/master/extdev/index.html?highlight=parallel_read_safe#important-objects) during the parallel reading phase. This could be done through source parsers, directives, roles, transforms, [event 5-8 handlers](https://www.sphinx-doc.org/en/master/extdev/appapi.html?highlight=env_before_read_docs#sphinx-core-events) and other components. It can be made parallel read safe by providing an [env-merge-info](https://www.sphinx-doc.org/en/master/extdev/appapi.html?highlight=env_before_read_docs#event-env-merge-info) event handler._

> > Perhaps Sphinx could automatically determine when an extension is safe for parallel reading? If my assumption above is correct, extensions that do not register handlers for events 5-8 are always safe?
> 
> No, it can't. We don't have the way to know the extension can read or write docs parallelly. How we can know if some extension crashes by dead-lock on parallel execution?

For future reference, some thoughts about this:

I think this would be detectable if Sphinx would enforce a specific location for extensions to store their environment data. Currently, extensions are free to alter the environment at their discretion, which is a bit icky since it could lead to conflicts between extensions if they happen to store their data at the same location in the env. A better approach would be collect all extension data in a dictionary indexed by the extension name. This way, Sphinx would know where each extension stores its data, and it can compare that data resulting from each of the parallel reading jobs.

This might be too limiting for some extensions however...

**Comment by tk0miya** [comment]
I tried to describe it on #9050. Could you check it, please?
