### ISSUE TITLE
LaTeX: lualatex build crash (undefined control sequence pdfnobuiltintounicode) with up-to-date TeXLive 2020 due to version v1.0i of cmap.sty

### ISSUE THREAD

**Issue by jfbu** [sphinx-doc/sphinx#8831]
**Describe the bug**

After updating TeXLive2020, no project can build with latex_engine set to `lualatex`.

During the `\sphinxmaketitle` an error arises (turns out it is due to `\begin{tabular}` triggering LaTeX into looking for an OT1 encoded old TeX font, and then cmap hooks cause the breakage with error

```
! Undefined control sequence.
reserved@a ...ng endcsname {pdfnobuiltintounicode 
                                                  noexpand font@name noexpan...

```

edited: to be precise, the errror trigger is that `tabular` enters momentarily math mode. The math fonts initialization then triggers cmap hooks. So in place of `tabular`, one can also use `$a$` to trigger error. Also `\fontencoding{OT1}\selectfont` will give the error.

I have tested with TeXLive 2019 and this new version of `cmap.sty` and it causes the same error.

**Environment info**
- OS: [e.g. Unix/Linux/Mac/Win/other with version]
- Python version: [e.g. 3.7.1]
- Sphinx version: all versions
- Sphinx extensions:  [e.g. sphinx.ext.autodoc, recommonmark]
- Extra tools: TeXLive 2020 with file cmap.sty 2021/01/29 v1.0i CMap support: searchable PDF

**Discussion**

We probably don't need at all `cmap` under lualatex, as the fonts used by default are not in old TeX encodings but "Unicode" fonts in OpenType format (or ttf)

**Comment by zauguin** [comment]
> We probably don't need at all `cmap` under lualatex, as the fonts used by default are not in old TeX encodings by "Unicode" fonts in OpenType format (or ttf)

I fully agree with this: Loading `cmap` here seems pretty useless since LuaTeX creates CMaps for OpenType fonts anyway.

That being said the issue should be fixed with the latest `cmap` version which is compatible with LuaTeX. (The update has been picked up by TeX Live yesterday around 22:30 so it might take until the evening to reach your favorite mirror.)

You might also want to look into the related discussion on tex-live: https://tug.org/pipermail/tex-live/2021-February/046432.html

**Comment by jfbu** [comment]
Thanks @zauguin and also for the relevant info you shared with me by mail, inclusive of some additional issue which arises with polyglossia. I will recapitulate here briefly.

- the problem was very short-lived,
- as of today 2021/02/07 the new cmap (1.0j) has made it to TeXLive mirrors, and it fixes the issue. And as the [tex-live list discussion shows](https://tug.org/pipermail/tex-live/2021-February/046432.html) Debian TeX maintainers are aware of the issue, so we can trust no stable Debian-based release will exhibit the problem in future,
- cmap adds to PDF "glyph to unicode maps". These help copy-paste and search. This is particularly relevant for pdflatex as fonts are then in antique 8bit "TeX font" encodings (at some point in the chain at least).
- turns out that cmap exited for Sphinx project automatically under platex and xelatex engine, but not lualatex (because of luatex85 package, `\pdffontattr` primitive exists and test of cmap for pdftex is positive).
- cmap for luatex was not very useful, due to usage of OpenType fonts and luatex incorporating glyph to unicode maps for them (not sure I get this completely right) but not completely useless because (or only because) of math fonts, which still, in our basic set-up, are Knuth TeX-encoded. So with cmap, when one copies or searches from PDF a Greek alpha in math mode it works  with ``𝛼`` whereas without cmap it would not find this by but ``α``
- turns out that at some point during the TeXLive 2020 cycle (perhaps even at its start but [I can't tell](https://github.com/reutenauer/polyglossia/issues/472)), polyglossia has opted for always using the "Harfbuzz renderer". This causes an issue now in copying-pasting from a lualatex produced Sphinx document: all ascii letters from operator names (such as ``cos``) are rendered in Private User area Unicode codepoints (and Adobe Reader gave not the same as mac os Skim or Preview). I did some extra testing with 
```
latex_engine = 'lualatex'

latex_elements = {
    'preamble': r"""
\usepackage{unicode-math}
\setmathfont{STIXTwoMath-Regular}[Extension=.otf]
""",
}
```
but the described polyglossia problem shows nevertheless. It doesn't matter that the document does use OpenType Math font:
```
LaTeX Font Info:    Overwriting symbol font `operators' in version `normal'
(Font)                  OT1/cmr/m/n --> TU/STIXTwoMath-Regular(1)/m/n on input l
```


The problem goes away if polyglossia is loaded with ``[luatexrenderer=Node]`` or ``[luatexrenderer=none]``. Here at Sphinx we should decide if:

- do we still use cmap with lualatex? it has limited utility but is not useless
- but combination with polyglossia as current since mid 2020 is bad, should we continue using polyglossia in particular for English language with lualatex/xelatex? Already for French we use babel rather. Be it babel or polyglossia we have anyhow no built-in support for multilingual documents and no usage for all the extra mark-up they require to make it work (it is notoriously problematic with LaTeX that it does not know how to switch automatically to suitable fonts, and considerable effort has to enter the font set-up for multilingual documents)

Broken or not, copying-pasting from math formula to get Unicode code-points is anyhow moderately useful as the math input form is Knuth TeX notation (which is commonly described as "LateX notation", although it has nothing to do with LaTeX especially) for our ``:math:`` directive and although ``unicode-math`` helps interpreting Unicode literals in math setting, this is another complex domain.

Memo: there will be in future some upstream changes in pdftex (1.40.22, TeXLive 2021) which affects `cmap` status. This is discussed [there](https://github.com/latex3/latex2e/issues/465)

**Comment by jfbu** [comment]
> * do we still use cmap with lualatex? it has limited utility but is not useless
> 
> * but combination with polyglossia

I knew I was going to add confusion. No, in fact I had spent a few hours ago some time testing that the polyglossia +lualatex TL2020 problem is there with or without `\usepackage{cmap}` inclusion. Anyway I will open a separate ticket for it.

**Comment by jfbu** [comment]
Closing as this problem with `cmap+lualatex` was quickly fixed upstream and was very short-lived.
