### ISSUE TITLE
sphinx-doc.org should point to latest release by default not master

### ISSUE THREAD

**Issue by ghost** [sphinx-doc/sphinx#8837]
**Describe the bug**
Currently [sphinx-doc.org](https://www.sphinx-doc.org/) points to the `master` branch by default, this should point to the latest released version. I'm not sure if this is related to changes made in #8309.

RTD is able to [track the latest version (tag)](https://docs.readthedocs.io/en/stable/versions.html#how-we-envision-versions-working) and have it marked as `stable` which should be displayed as the default instead of `master`.

**To Reproduce**
Visit [sphinx-doc.org](https://www.sphinx-doc.org/), which redirects to [en/master/](https://www.sphinx-doc.org/en/master/).

**Expected behavior**
Documentation for the latest released version to be displayed by default.

**Comment by ghost** [comment]
Looks like I picked the wrong issue template, could someone with powers label this as `enhancement` and `docs`. Thanks.

**Comment by tk0miya** [comment]
Do you have any actual troubles in the master doc? If not, it's enough to remove the version info for me. What do you think?

**Comment by ghost** [comment]
No I didn't have any touble, it was the page title saying 4.0.0 that resulted in me spending 10 minutes trying to work out why `pip` couldn't find 4.0.0 :grin:

IMHO it would make sense to avoid any issues/confusion in the future if the development version differs from the current released version.

**Comment by mgeier** [comment]
For reference, there was a somewhat related issue a few years ago: #4744
