### ISSUE TITLE
Problem with options in custom domain

### ISSUE THREAD

**Issue by SimonWalth** [sphinx-doc/sphinx#8860]
Hi,
I have a problem with reading the options given to a custom domain in sphinx.

I'm follwing the tutorial "Developing a “recipe” extension" (https://www.sphinx-doc.org/en/master/development/tutorials/recipe.html) and can't get the ":containes" option to work. self.options is always empty.

**Comment by tk0miya** [comment]
It seems working fine when I downloaded the recipe.py from our repository and enable it on a sample project.
https://raw.githubusercontent.com/sphinx-doc/sphinx/3.x/doc/development/tutorials/examples/recipe.py

Please let me know what happened in your project in details.

**Comment by SimonWalth** [comment]
Thanks for your time.
I created a new project to test this again and have the same problem again.


Console output:

Running Sphinx v3.4.3
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 2 source files that are out of date
updating environment: [new config] 2 added, 0 changed, 0 removed
reading sources... [100%] tomato-soup                                          
Exception occurred:
  File "*********\sw\sphinxtestDocuRecipe\_ext\recipe.py", line 29, in add_target_and_index
    x.strip() for x in self.options.get('contains').split(',')]
AttributeError: 'NoneType' object has no attribute 'split'
The full traceback has been saved in C:\Users\sw\AppData\Local\Temp\sphinx-err-e2k40rf6.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!

Process finished with exit code 2

[sphinx-err-e2k40rf6.log](https://github.com/sphinx-doc/sphinx/files/5964712/sphinx-err-e2k40rf6.log)


This is my run configuration, that I use in pyCharm:


    <component name="ProjectRunConfigurationManager">
      <configuration default="false" name="sphinx-build" type="PythonConfigurationType" factoryName="Python">
        <module name="sphinxtestDocuRecipe" />
        <option name="INTERPRETER_OPTIONS" value="" />
        <option name="PARENT_ENVS" value="true" />
        <envs>
          <env name="PYTHONUNBUFFERED" value="1" />
        </envs>
        <option name="SDK_HOME" value="C:\Users\sw\AppData\Local\Microsoft\WindowsApps\python3.8.exe" />
        <option name="WORKING_DIRECTORY" value="$PROJECT_DIR$" />
        <option name="IS_MODULE_SDK" value="false" />
        <option name="ADD_CONTENT_ROOTS" value="true" />
        <option name="ADD_SOURCE_ROOTS" value="true" />
        <option name="SCRIPT_NAME" value="$USER_HOME$/PycharmProjects/docProject/venv/Lib/site-packages/sphinx/cmd/build.py" />
        <option name="PARAMETERS" value="-b html . ./out" />
        <option name="SHOW_COMMAND_LINE" value="false" />
        <option name="EMULATE_TERMINAL" value="false" />
        <option name="MODULE_MODE" value="false" />
        <option name="REDIRECT_INPUT" value="false" />
        <option name="INPUT_FILE" value="" />
        <method v="2" />
      </configuration>
    </component>

And that is what I see when debugging:

![grafik](https://user-images.githubusercontent.com/72194348/107626331-ee421a80-6c5d-11eb-8e0f-0ca25d829e14.png)

Also another thing: Shouldn't the example tomato-soup.rst ingredients be comma seperated like:
.. recipe:recipe:: TomatoSoup
  :contains: tomato,cilantro,salt,pepper

rather than:
.. recipe:recipe:: TomatoSoup
  :contains: tomato cilantro salt pepper

**Comment by tk0miya** [comment]
Thank you for the info. Could you paste the source mark-up for this error? It seems the `:contains:` option was considered as a part of the arguments. I guess there is something wrong in mark-ups.

**Comment by tk0miya** [comment]
I found the reason for the crash. #8869 will resolve this error. But, as I commented above, it comes from the mark-up error, I guess. So please check your input, please.

**Comment by SimonWalth** [comment]
You mean the tomato-soup.rst?

tomato-soup.rst:

The recipe contains `tomato` and `cilantro`.

.. recipe:recipe:: TomatoSoup
  :contains: tomato cilantro salt pepper

 This recipe is a tasty tomato soup, combine all ingredients
 and cook.



Attached as txt (because rst is not supported)
[tomato-soup.txt](https://github.com/sphinx-doc/sphinx/files/5965899/tomato-soup.txt)

**Comment by tk0miya** [comment]
Please align the indentation of directive options and contents. The options is indented by 2 spaces. But contents are by 1 space. The reST parser is confused by this mark-ups, and considers that the line starts with `:contains:` is a part of directive argument (and there are no directive options).

**Comment by SimonWalth** [comment]
Oh, I see. There were 2 spaces before :contains:, with 1 space it works. That seems to be an error in the tutorial.

**Comment by SimonWalth** [comment]
Or maybe it's just that copy pasting the tutorial just gives you 2 spaces.

**Comment by tk0miya** [comment]
Absolutely. The example of our tutorial is wrong. Thanks!
