### ISSUE TITLE
Extension error (sphinx.ext.viewcode) with Sphinx 3.5

### ISSUE THREAD

**Issue by xqt** [sphinx-doc/sphinx#8880]
After deployment of **Sphinx 3.5.0** our Pywikibot CI-Tests fails with following exception:

```
11:12:45 Extension error (sphinx.ext.viewcode):
11:12:45 Handler <function env_purge_doc at 0x7fb96305e6a8> for event 'env-purge-doc' threw an exception (exception: 'bool' object is not iterable)
11:12:46 ERROR: InvocationError for command /src/.tox/doc/bin/sphinx-build -M html ./docs ./docs/_build (exited with code 2)
```
See
- https://integration.wikimedia.org/ci/job/pywikibot-core-tox-doc-docker/13751/console
- https://integration.wikimedia.org/ci/job/pywikibot-core-tox-doc-docker/13752/console

Our bug tracker:
- https://phabricator.wikimedia.org/T274730

**Comment by virtuald** [comment]
I'm also running into this issue. Anyone got a workaround?

**Comment by virtuald** [comment]
Looks like `modules.items()` in `viewcode.py: env_purge_doc` sometimes returns a bool. Added a print statement:

```
    x = list(modules.items())
    print(x)
```

And get

```
[('wpilib.controller._controller', False)]
```

**Comment by virtuald** [comment]
Pushed a fix at https://github.com/sphinx-doc/sphinx/pull/8888, hopefully they can get a new release out as soon as possible?

**Comment by ksunden** [comment]
https://github.com/pyqtgraph/pyqtgraph/runs/1900044069

This is affecting pyqtgraph as well.
