### ISSUE TITLE
The depth of bookmarks panel in PDF is not enough for navigation (even in absence of ``:maxdepth:`` option with ``toctree`` directive)

### ISSUE THREAD

**Issue by jfbu** [sphinx-doc/sphinx#8881]
**Describe the bug**

Consider for example the Sphinx own docs, which uses a toctree with maxdepth set to 2. In PDF output, if I revert the 
commit 3a3a479f1e739d688 (#8746, merged into 3.5.0), the following shows:
![Capture d’écran 2021-02-14 à 11 08 17](https://user-images.githubusercontent.com/2589111/107873847-d1a01f80-6eb5-11eb-97d4-9af19dcb5fa2.png)
i.e.
- from the opened bookmarks panel one does not see and can not navigate to all extensions built-in into Sphinx,
- from the PDF contents one can not either, and there are about 50 pages with no way to navigate except do a linear continuous reading, whether on screen or on print.

Compare to the html which looks like this

![Capture d’écran 2021-02-14 à 11 09 13](https://user-images.githubusercontent.com/2589111/107873911-2d6aa880-6eb6-11eb-82fb-136e95ee552f.png)

once one has gone to the Extensions page.

The underlying problem here is that the latexpdf route builds a single document.

Another sub-issue is that our docs says in the documentation of ``toctree`` directive:

> A numeric maxdepth option may be given to indicate the depth of the tree; by default, all levels are included.

However, if one does not use the ``maxdepth`` option, then, with ``'manual'`` type only 2 levels are kept, not the maximum number of levels.

File ``file.rst``

```rest
=====
 aaa
=====

bbb
=====

ccc
****

ddd
~~~~

eee
^^^^

fff
----

ggg
```

file ``index.rst``:

```
Welcome to FOO's documentation!
===============================

.. toctree::
   :caption: Contents:

   file
```

Only two levels in TOC and bookmarks in output.

![Capture d’écran 2021-02-14 à 11 47 28](https://user-images.githubusercontent.com/2589111/107874513-71f84300-6eba-11eb-8e38-4ea24dac8282.png)

But the html output uses full depth:

![Capture d’écran 2021-02-14 à 11 46 28](https://user-images.githubusercontent.com/2589111/107874501-61e06380-6eba-11eb-8ee7-a383c8df24d4.png)

**Options to consider**

The options to fix this:

1. use some latex package to add automatically local table of contents in each sectioning level at maxdepth,
2. set the document TOC depth to a high value always
3. disconnect the bookmarks panel depth from the document TOC depth 

Option 1 is no good because it adds a dependency (`etoc`  latex package can do that), and will be redundant with a usage of [``.. contents::``](https://docutils.sourceforge.io/docs/ref/rst/directives.html#table-of-contents) directive; besides if there is no way to click back to the local toc, it is useless for navigation on screen. But would be fine for paper.

Option 2 fixes the bookmarks issue because by default the hyperref arranges the bookmarks panel depth to match the latex tocdepth which governs the looks of the main TOC. However it will suddenly make all documents produced from Sphinx have a detailed TOC (cf [our own docs at 3.5.0](https://www.sphinx-doc.org)  in PDF format to see what this gives) which will possibly extend over many pages. 

Also, for example for Sphinx own docs we incorporate the Change log, and each entry for a given version has subentries "Dependencies", "Incompatibles changes", "Deprecated", "Features added", "Bugs fixed", so this will make very long TOC at start of PDF (we use raw latex to avoid that despite elevated global tocdepth).

For me it is not really a problem to have a long detailed TOC at start of PDF, and it makes the PDF on paper much more usable.

Option 3 does not change anything to PDF contents (and paper printouts) but makes navigation on screen convenient. It consists in using ``bookmarksdepth=`` option of hyperref which disconnects the bookmarks panel depth from the main TOC depth. Advanced users can also use raw latex directives with usage of ``\hypersetup{bookmarksdepth=<desired depth>}`` to control locally. This is what we do for the Change Log part, although this is not very important. In fact by default PDF viewer will show the bookmarks panel collapsed at first level, and it is human who opens up into deeper levels.

Regarding the behaviour in absence of usage of ``:maxdepth:`` option, option 3 would also fix it for the bookmarks panel.

We could set ``bookmarksdepth=5`` for maximally detailed panel. Here the numbering corresponds to LaTeX own conventions, it is not relative to top sectioning. At least ``bookmarksdepth=3`` should be default in my opinion.

I like detailed TOCs, so option 2 could be envisioned but is breaking change. Besides LaTeX has problems with long numbers in TOCs such as ``10.113 Relase 1.2.3 (2010/01/01)``, often the ``113`` will then overwrite the start of ``Release`` and special latex commands have to be issued to configure the TOC.

On the other hand option 3 only changes the bookmarks panel. The bookmarks panel can always be shown by pdf viewer, and is more useful than body TOC when navigating on screen.

Making its depth maximal is no big deal because pdf viewers I know by default present the panel in collapsed mode.

**Your project**
Sphinx own docs  version ``<`` 3.5.0 which incorporated a custom fix.

**Screenshots**
See above

**Environment info**
- OS: [e.g. Unix/Linux/Mac/Win/other with version]
- Python version: [e.g. 3.7.1]
- Sphinx version: all versions
- Sphinx extensions:  [e.g. sphinx.ext.autodoc, recommonmark]
- Extra tools: [e.g. Browser, tex or something else]

**Related**

- #8746

**Comment by jfbu** [comment]
If option 3 is chosen then this could go into 3.x, if it is option 2 then it should be for next major release.

**Comment by jfbu** [comment]
>  (cf our own docs at 3.5.0 in PDF format to see what this gives) 


@tk0miya  I discover this does not work: our [doc site](https://www.sphinx-doc.org/) seems not to offer PDF download, at least I could not find a link to it and going to [read the docs downloads page](https://readthedocs.org/projects/sphinx/downloads/) it stops at 2.0.

**Comment by tk0miya** [comment]
I enabled the PDF build by #8900. Now PDF document is available on our site.

**Comment by tk0miya** [comment]
I think it is difficult to configure the depth of ToC for all media by one setting. It would be changed for each media, HTML, EPUB, PDF, and so on. So it would be better to configure the depth for LaTeX output. I don't know the configuration for the depth of bookmarks is needed or not. But it's okay to add it also.

**Comment by jfbu** [comment]
> I don't know the configuration for the depth of bookmarks is needed or not. But it's okay to add it also.

if using PDF on screen with large document, I feel the bookmarks are useful. I made #8907 to let them have high depth per default. This will not change the printed on paper version.

**Comment by jfbu** [comment]
Fixed at https://github.com/sphinx-doc/sphinx/commit/796d36fd627c5a581f4de84b6f45258e06331130
