### ISSUE TITLE
Minified js stemmers not included in the pypi distribution 3.5.0

### ISSUE THREAD

**Issue by heitorPB** [sphinx-doc/sphinx#8884]
**Describe the bug**
Updated Sphinx to 3.5.0 and got a warning (treated as error with `SPHINXOPTS="-W" make html`) that `
FileNotFoundError: [Errno 2] No such file or directory: 'venv/lib/python3.9/site-packages/sphinx/search/minified-js/base-stemmer.js'`

Downgrading to sphinx 3.4.3 fixes the problem.

**To Reproduce**
```
$ git clone https://github.com/grupy-sanca/curso-python
$ cd curso-python
$ virtualenv venv && source venv/bin/activate
$ pip install -r requirements.txt
$ make html SPHINXOPTS="-WT"

[ommited checks]

Traceback (most recent call last):
  File "/home/h/projects/curso-python-intro-plus/venv/lib/python3.9/site-packages/sphinx/builders/html/__init__.py", line 806, in copy_static_files
    context.update(self.indexer.context_for_searchtool())
  File "/home/h/projects/curso-python-intro-plus/venv/lib/python3.9/site-packages/sphinx/search/__init__.py", line 442, in context_for_searchtool
    'search_language_stemming_code': self.get_js_stemmer_code(),
  File "/home/h/projects/curso-python-intro-plus/venv/lib/python3.9/site-packages/sphinx/search/__init__.py", line 465, in get_js_stemmer_code
    with open(path.join(js_dir, 'base-stemmer.js')) as js_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/h/projects/curso-python-intro-plus/venv/lib/python3.9/site-packages/sphinx/search/minified-js/base-stemmer.js'
```

**Expected behavior**
No warning/error on Sphinx js files.

**Environment info**
- OS: ArchLinux
- Python version: 3.9
- Sphinx version: 3.5.0
- Sphinx extensions:  sphinxcontrib-spelling

**Comment by heitorPB** [comment]
curiously, on sphinx 3.4.3 there's no warning/error, but those minified files also don't exist.

**Comment by mitya57** [comment]
It was my change which broke this — so sorry for the inconvenience. I created PR #8886 to fix this.

**Comment by heitorPB** [comment]
Thanks for fixing it quickly! Do you think it is possible to release 3.5.1 with this fix soon? I'm not sure how/if this bug affects other projects

**Comment by mitya57** [comment]
> Do you think it is possible to release 3.5.1 with this fix soon?

I am not a project member, just a contributor, so that's a question to @tk0miya.

**Comment by tk0miya** [comment]
Now I merged the fix. And I'll take a look at other reports for 3.5.0 from now on. So please wait a moment.
Thank you for reporting.

**Comment by heitorPB** [comment]
Thanks for fixing it!
Have a nice week
