### ISSUE TITLE
`AttributeError: 'str' object has no attribute 'priority'` in Sphinx 3.5.0

### ISSUE THREAD

**Issue by ryan-williams** [sphinx-doc/sphinx#8885]
Dask documentation builds started failing when picking up the latest Sphinx (3.5.0); pinning to `<3.5.0` seems to work around the issue. See https://github.com/dask/dask/issues/7216 / https://github.com/dask/dask/pull/7217:

> ```
> Exception occurred:
>   File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/sphinx/builders/html/__init__.py", line 1039, in <lambda>
>     ctx['css_files'].sort(key=lambda js: js.priority)
> AttributeError: 'str' object has no attribute 'priority'
> The full traceback has been saved in /tmp/sphinx-err-z6ie2z11.log, if you want to report the issue to the developers.
> Please also report this if it was a user error, so that a better error message can be provided next time.
> A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
> ```

**Comment by rmk135** [comment]
Same  stuff at [ets-labs/python-dependency-injector](https://github.com/ets-labs/python-dependency-injector).

Broken job: https://github.com/ets-labs/python-dependency-injector/runs/1899866966?check_suite_focus=true

**Comment by spacemanspiff2007** [comment]
Same [here](https://github.com/spacemanspiff2007/HABApp/runs/1900960386?check_suite_focus=true)

**Comment by tk0miya** [comment]
Since Sphinx-1.8, configuration variables `html_css_files` and `html_js_files` to install custom CSS/JS files for users. Could you migrate these settings, please? I posted #8893 to avoid the crash. But it does not mean all of features (including sorting CSS/JS files) will work.

**Comment by djhoese** [comment]
@tk0miya Should using the old `html_context` have generated a warning? I just started building my sphinx docs with `-W` so all warnings cause errors and I don't think anything was every raised about it.

Edit: I mean, before #8893 that is.

Edit 2: Converting old `html_context` to `html_css_files` did the trick. Thanks!

**Comment by tk0miya** [comment]
In my understanding, `html_context` was introduced to add custom template variables by users. So it is not designed to override `css_files` and `script_files`. So I've never thought a deprecation warning is needed.

But, now I understand some (many?) users have used it to override them. So deprecation period is needed.
