### ISSUE TITLE
sphinx.ext.viewcode: separate highlight_language?

### ISSUE THREAD

**Issue by mgeier** [sphinx-doc/sphinx#8901]
I would like to have no highlighting by default in literal blocks, so I'm using:

```python
highlight_language = 'none'
```

However, I would still like the code shown by the `sphinx.ext.viewcode` extension to be highlighted.

**Describe the solution you'd like**

I'm not sure, probably a separate configuration value for the `viewcode` extension?

Or probably the language could be determined automatically?

**Describe alternatives you've considered**

I can put this at the top of each source file to disable the highlighting:

```
.. highlight:: none
```

But this seems cumbersome.

Is there a better way?

**Additional context**

Probably related: #3700, #3714

**Comment by mgeier** [comment]
For a bit more context: this would be useful when using my `nbsphinx` extension, because Jupyter notebooks don't have a default highlight language, so disabling the default in Sphinx is necessary to simulate the behavior of Jupyter notebooks.

However, I've just created a PR that would make this obsolete: https://github.com/spatialaudio/nbsphinx/pull/542.
This automatically inserts `.. highlight:: none` at the top of each Jupyter notebook.

If I'm merging that PR (and I think I will), I won't really need this PR anymore, but maybe it might still be useful for other situations?

**Comment by tk0miya** [comment]
I'm not sure there is who wants to disable highlights for code-blocks and enable highlights for viewcode. So I suppose the main user of the option would be only nbsphinx...

**Comment by mgeier** [comment]
I've merged https://github.com/spatialaudio/nbsphinx/pull/542, so for `nbsphinx` this is not necessary anymore.

> I'm not sure there is who wants to disable highlights for code-blocks and enable highlights for viewcode.

Well, I don't know.

Probably some project has a lot of shell code in its documentation but `autodoc` should still use Python highlighting.

Also, I just find it a bit strange that an extension (albeit a built-in one) piggy-backs on an existing configuration value.

And I'm wondering: would it be possible to have `autodoc` documentation for more than one language?
For example, there might be a backend API for Python and a frontend for JavaScript?

Anyway, those are just hypothetical situations, I'm OK with closing this issue.

**Comment by tk0miya** [comment]
>Also, I just find it a bit strange that an extension (albeit a built-in one) piggy-backs on an existing configuration value.

It's a natural behavior to me. For example, if I change `language`, some extensions should also follow it.
I can understand it does not follow if its own configuration like `custom_language`.

>And I'm wondering: would it be possible to have autodoc documentation for more than one language?

I don't know why do you mention autodoc, but it's available for other languages (with large effort).
The core feature of autodoc is "generating reST code from source code". So somebody writes a reST generator for some language, it will become true.

>Anyway, those are just hypothetical situations, I'm OK with closing this issue.

Okay. I'm closing this. (And will consider this again if somebody will request it).

**Comment by mgeier** [comment]
> I don't know why do you mention autodoc

Because that's where I normally see the "[source]" link which points to the source code generated with `sphinx.ext.viewcode`.
But I guess it can also be used without `sphinx.ext.autodoc`, I've just never done that.

I thought the directives for creating API documentation are aware of the programming language, so I find it strange that the highlight language has to be specified separately.

But, as I said before, these are only hypothetical deliberations, I don't actually need any of this ...

**Comment by tk0miya** [comment]
Understand. The links are related to the python domain feature, not autodoc.
