### ISSUE TITLE
Class variable name cross referencing 

### ISSUE THREAD

**Issue by heavelock** [sphinx-doc/sphinx#8902]
**Describe the bug**
Names of class variables that are described with `:ivar` are getting cross-referenced. I would rather expect that this would not be crossreferenced, as the names of parameters (`:param:`) in methods are not. 

Here is a screenshot:
![obraz](https://user-images.githubusercontent.com/10303802/108172681-647ecb00-70fd-11eb-8cb9-576b10c1cdbf.png)

Notice here names of variables `time` and `phase`. Both are links. The former one is linked to python's `time` module, the latter is linked to some not relevant part of our code.

Code that defines that page is here:
https://github.com/obspy/obspy/blob/master/obspy/taup/helper_classes.py

I tried to use `:samp:` directive but it breaks rendering. https://github.com/obspy/obspy/pull/2662#issuecomment-780372177

**To Reproduce**
```
$ apt-get install apt-get install -yqq build-essential gcc libproj-dev proj-data proj-bin libgeos-dev
$ python -m pip install numpy
$ python -m pip install shapely --no-binary shapely
$ git clone git@github.com:obspy/obspy.git
$ cd obspy
$ git switch sphinx3
$ pip install .
$ cd misc/docs
$ python -m pip install -r requirements.txt
$ make html
$ # open build/html/packages/autogen/obspy.taup.helper_classes.Arrival.html and see the class vars of Arrival
```

**Expected behavior**
Names of class variables should not be links. Exactly as names of method parameters are not.

**Your project**
https://github.com/obspy/obspy

**Environment info**
- OS: Linux
- Python version: 3.8.7
- Sphinx version: 3.4.3
- Sphinx extensions:  
```python
    'sphinx.ext.intersphinx',
    'sphinx.ext.doctest',
    'sphinx.ext.autodoc',
    'sphinx.ext.viewcode',
    'sphinx.ext.mathjax',
    'sphinx.ext.autosummary',
    'sphinx.ext.coverage',
    'sphinx.ext.duration',
    'sphinx.ext.todo',
    'm2r2',
    # theme
    'sphinx_rtd_theme',
    # custom extensions
    'plot_directive',
    'credits',
    'citations',
```
- Extra tools: [e.g. Browser, tex or something else]

**Additional context**

- [e.g. URL or Ticket]

**Comment by tk0miya** [comment]
This will be fixed in 4.0.0 release (refs: #8638).
Thanks,
