### ISSUE TITLE
Add .ASPX as output option for sphinx-build

### ISSUE THREAD

**Issue by bizzfitch** [sphinx-doc/sphinx#8908]
Title. Some docs that I'm generating are being hosted on a sharepoint site. Hosting these docs is as simple as converting all of the .html files to .aspx files. My first thought was to just write a script that does this for me, but I think the best solution is to try and integrate this as a feature available in sphinx-build.

Looking for any feedback on potential obstacles or challenges I might not be aware of. Fundamentally, I'm just going to have the option invoke the html builder, rename the files, and then maybe run some tests to make sure nothing is broken.

**Comment by tk0miya** [comment]
I think .aspx is not a common document format. AFAIK, it's mainly used for building a web application, right? -1 for adding it to the Sphinx core. How about creating your own builder? Sphinx allows you to enhance its feature via extensions.

Note: If your goal is renaming the suffix of HTML output, `html_file_suffix` configuration will resolve your case.
