### ISSUE TITLE
Unable to use Sphinx for Github projects

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#891]
The HTML output from Sphinx creates hardcoded _sources and _static folders. Unfortunately, Github automatically ignores all "_" folders when it updates the public page of a project, resulting in broken output such as this:

http://jacek99.github.com/corepost/

It would be great if the "_sources" and "_static" folders where configurable in conf.py, so that they could be overriden for those sites that may have issues with Sphinx's default HTML folder structure.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/891
- Originally reported by: Jacek Furmankiewicz
- Originally created at: 2012-03-08T15:40:47.528

**Comment by shimizukawa** [comment]
_From Robert Lehmann on 2012-03-08 15:33:43+00:00_

http://sphinx.pocoo.org/faq.html#using-sphinx-with has a section on Github Pages, advocating the use of a {{{.nojekyll}}} file:

//Directories starting with underscores are ignored by default which breaks static files in Sphinx. GitHub’s preprocessor can be [[https://github.com/blog/572-bypassing-jekyll-on-github-pages|disabled]] to support Sphinx HTML output properly.//

**Comment by shimizukawa** [comment]
_From Jacek Furmankiewicz on 2012-03-08 18:02:51+00:00_

Sorry, I missed that. That fix works great, much appreciated.

**Comment by ajgpitch** [comment]
What if you want to host your sphinx doc pages on a site that uses Jekyll? 

I see there are some tools out there for removing the underscores, but they are very old and don't seem compatible with latest sphinx doc

**Comment by shimizukawa** [comment]
Now sphinx have `sphinx.ext.githubpages` extension. It would help us 👍 
http://www.sphinx-doc.org/en/1.5.1/ext/githubpages.html
