### ISSUE TITLE
Documentation on cpp_index_common_prefix should state how to handle nested namespaces

### ISSUE THREAD

**Issue by ninkibah** [sphinx-doc/sphinx#8911]
The documentation for cpp_index_common_prefix
https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-cpp_paren_attributes
does not explain how to specify child namespaces.

It took me some time to figure out that I needed to specify the child namespace before the parent.

Suggested wording change to the documentation:

```text
A list of prefixes that will be ignored when sorting C++ objects in the global index. For example ['awesome_lib::'].
Child namespaces must be listed before parent namespaces, otherwise the child will not be recognized.

For example: ['awesome_lib::internal::', 'awesome_lib::']
```

**Comment by jakobandersen** [comment]
Thanks for reporting, that's a good point. I consider this a bug in the implementation rather than in the documentation. I have posted #8912 which should make it remove the longest of the given prefixes instead of simply the first one that matches.

**Comment by ninkibah** [comment]
Wow, I didn't expect such a fast response, and I only added the issue so that other users would know the workaround. But removing the longest prefix sounds reasonable. One final point: I suppose there are some edge cases where it's useful to not match the "::", so you can match against partial namespace names. But I can't think why you would want that. so, would you want to internally append "::" to a prefix if it didn't end in "::"?

**Comment by jakobandersen** [comment]
At this point I can't think of a use-case where the prefix doesn't end in ``::`` either. Though, I would rather leave it as is, so it at least is possible if someone finds it useful.
