### ISSUE TITLE
Can't enable translation of sphinx_rtd_theme

### ISSUE THREAD

**Issue by zhsj** [sphinx-doc/sphinx#8915]
**Describe the bug**

sphinx_rtd_theme has translation support since v0.5.0. However it can't be enabled.

**To Reproduce**
```
$ make html SPHINXOPTS="-D language=zh_CN -D html_theme=sphinx_rtd_theme"
$ # open _build/html/index and see the message in search box.
```

**Expected behavior**

The message in search box has been translated.

**Your project**

The message in search box is still "Search docs".

**Environment info**
- OS: [Linux]
- Python version: [e.g. 3.9.1]
- Sphinx version: [e.g. 3.5.1]
- Sphinx extensions:  [sphinx-rtd-theme]
- Extra tools: []

**Additional context**

sphinx-rtd-theme has a setup function to extend locale dir.
https://github.com/readthedocs/sphinx_rtd_theme/blob/3ed52c4df52a4edd4bf3673b7d787b61685e2287/sphinx_rtd_theme/__init__.py#L40

However it's never been called, since sphinx_rtd_theme is a special theme.

https://github.com/sphinx-doc/sphinx/blob/f8878bb0b67df6e56ca95c003a41edd9eb59d79e/sphinx/theming.py#L192-L199

If I remove these lines, then the translation works fine.

https://github.com/sphinx-doc/sphinx/blob/f8878bb0b67df6e56ca95c003a41edd9eb59d79e/sphinx/theming.py#L182-L183

**Comment by tk0miya** [comment]
Thank you for reporting. It seems sphinx_rtd_theme has already support loading via entry_point. So special treatment is no longer needed. It's better to remove the code (since 4.0).
