### ISSUE TITLE
Error in the __init__.py with python version 3.9 // ValueError: unsopported format character '(' (0x28)

### ISSUE THREAD

**Issue by josep123** [sphinx-doc/sphinx#8930]
When i make a | sphinx-build doc html | the platfom make a warning

 File "/linuxbrew/opt/python@3.9/lib/python3.9/site-packages/sphinx/transforms/post_transforms/__init__.py", line 177, in warn_missing_reference
    logger.warning (msg % {'target': target},
ValueError: unsupported format character '(' (0x28) at index 48

**Comment by tk0miya** [comment]
Thank you for reporting. But it's hard to support you because there are no environment info. Please fill our issue template.

**Comment by tk0miya** [comment]
If you'll file another new issue, please let us know your `language` setting.
