### ISSUE TITLE
Warning for wrong list layout.

### ISSUE THREAD

**Issue by MMKrell** [sphinx-doc/sphinx#8931]
**Is your feature request related to a problem? Please describe.**
People new to restructured text regularly miss the blank line before a list, 
even though the rst rules state 

> Lists must always start a new paragraph -- that is, they must appear after a blank line.

If they combine the list with an indentation, the error is reported during sphinx compilation.
Otherwise, it's hard to discover it during normal development.

**Describe the solution you'd like**
Whenever a line starts with a symbol that is associated with lists (like the hash symbol)
and the line is not associated with a caption or list symbol,
an error/warning is thrown to point out that probably an intended list will not be layout.

**Describe alternatives you've considered**
It might be even nice to layout lists without requiring the empty line.
However, this will probably make the parsing harder/impossible.
Also it would encourage documentation that is less readable.

**Additional context**

Example of incorrect rst code that should result in a warning/error:

```
For handling this ticket, it would be good to:
#. Analyze the parser and how it can detect the misplaced list
#. Add a warning/error message, when a list seems to be intended 
within a paragraph.
#. Write a test
Win.
```

The correct layout would be:

```
For handling this ticket, it would be good to:

#. Analyze the parser and how it can detect the misplaced list
#. Add a warning/error message, when a list seems to be intended 
    within a paragraph.
#. Write a test

Win.
```

The error could be:

```
[error] Unexpected list start symbol detected at line 2. Please add an empty line or use a different symbol.
```

**Comment by tk0miya** [comment]
Good point. +1 for the improvement. But Sphinx uses docutils for the parser of reST. So it's difficult to emit warnings on the syntax error. How about proposing this for the docutils project?

**Comment by AA-Turner** [comment]
Please use Sphinx-Lint or report to the Docutils project.

A
