### ISSUE TITLE
PDF build on sphinx latex docker image fails due to missing xindy package

### ISSUE THREAD

**Issue by SeanDS** [sphinx-doc/sphinx#8941]
**Describe the bug**
Using the Sphinx LaTeX Dockerfile [here](https://github.com/sphinx-doc/docker/blob/master/latexpdf/Dockerfile) in my CI pipeline to build a PDF, I run into the following error:

```
Can't exec "xindy": No such file or directory at (eval 13) line 14.
```

My project (not yet public unfortunately) contains indexes so I assume that's why `latexmk` needs to generate them, but can't. HTML build works fine (i.e. there are no errors in the rst files).

I can fix this by running `apt install -y xindy` before building the PDF. It seems `xindy` should be added to the dependencies of the `sphinx-latexpdf` Dockerfile.

**To Reproduce**

- Pull the `sphinxdoc/sphinx-latexpdf` docker image.
- Run something like `docker run --rm -v /path/to/document:/docs sphinxdoc/sphinx-latexpdf make latexpdf` on an existing project that uses indexes
- Observe missing dependency error.

**Expected behavior**
Anything Sphinx can build as HTML without error should build as PDF without error when using the provided Dockerfile!

**Your project**
I can share if required, but it's not public right now so it would require some preparation. I don't think the project is needed to understand the problem.

**Environment info**
- OS: Docker
- Python version: 3.9
- Sphinx version: 3.5.1
- Sphinx extensions:
   - "sphinx.ext.autodoc",
   - "sphinx.ext.autosummary",
   - "sphinx.ext.coverage",
   - "sphinx.ext.doctest",
   - "sphinx.ext.intersphinx",
   - "sphinx.ext.todo",
   - "sphinx.ext.ifconfig",
   - "sphinx.ext.viewcode",
   - "sphinxcontrib.bibtex",
   - "sphinxcontrib.katex",
   - "sphinxcontrib.rsvgconverter",
   - "sphinx_click",
   - "numpydoc",
   - "jupyter_sphinx",

**Comment by tk0miya** [comment]
Could you send a pull request please?

**Comment by SeanDS** [comment]
Sure, here you go: https://github.com/sphinx-doc/docker/pull/5
