### ISSUE TITLE
lex JSON even if it contains comments

### ISSUE THREAD

**Issue by JulianGro** [sphinx-doc/sphinx#8950]
**Is your feature request related to a problem? Please describe.**
```
WARNING: Could not lex literal_block as "JSON". Highlighting skipped.
```
JSON code blocks containing comments cannot be lexed. While the standard does not allow comments, it makes sense to diverge from this limitation in some case. One of these cases is documentation. In my case it is also comments commonly being used in JSON files on the Vircadia platform. Without these comments end users won't be able to understand what a field does.

**Describe the solution you'd like**
Ideally Sphinx would lex JSON code blocks even if they contain comments. 

**Describe alternatives you've considered**

**Additional context**
In my case we use `//` to mark comments, same as on JavaScript.

- an example page is here: https://docs.vircadia.dev/create/entities/open-tablet-page-tutorial.html#create-an-entity-to-use-as-a-button

**Comment by tk0miya** [comment]
Sphinx uses pygments for highlighting. It means the error came from pygments. So please propose to support commented JSON to the pygments project.
