### ISSUE TITLE
Spurious error with function pointer as template argument

### ISSUE THREAD

**Issue by wintersteiger** [sphinx-doc/sphinx#8953]
**Describe the bug**

For this:

    /// @brief A template class
    template <void (*F)()>
    class C {};

Sphinx complains thusly:

    | [(DefinitionError('Invalid C++ declaration: Expected "," or ">". [error at 19]\n  template<void(*)() F> C\n  -------------------^'), 'If no parameter')]
    |/data/cwinter/breathe/source/index.rst:11: WARNING: Error in template parameter list.
    Invalid C++ declaration: Expected "," or ">". [error at 19]
      template<void(*)() F> C
      -------------------^

**To Reproduce**

Copy source snippet above into .h file and run Sphinx with Breathe extension enabled (see project files)

    $ sphinx-autobuild source build

**Expected behavior**

Don't throw an error and produce the right type names. (When the error is thrown some types are assigned names with `PhonyNameDueToError`.)

**Your project**

[sphinx-templates.zip](https://github.com/sphinx-doc/sphinx/files/6077445/sphinx-templates.zip)

**Environment info**
- OS: Ubuntu 18.04
- Python version: 3.8.0
- Sphinx version: 3.5.1
- Sphinx extensions:  breathe
- Extra tools: doxygen 1.9.2

**Comment by wintersteiger** [comment]
(Not sure it's helpful information, but removing `<declname>F</declname>` from the doxygen XML means the error isn't thrown anymore, but the parameter has no name in the Sphinx output.)

**Comment by jakobandersen** [comment]
Thanks for the report, though this is not a Sphinx bug, but a Doxygen and/or Breathe issue. Please open a bug report over at Breathe instead.
