### ISSUE TITLE
Referenced file not found in .. image:: <path> directive

### ISSUE THREAD

**Issue by mhdirkse** [sphinx-doc/sphinx#8959]
**Describe the bug**
I have a ReadTheDocs project that includes the following text:

    #. Browse to http://localhost.
    #. Click "Testing":

       .. image:: ../../frankConsoleFindTestTools.jpg

    #. Click Ladybug and tab "Test".

When I build my project under Windows with Sphinx 3.5.1, my console shows warnings like:

    \downloadUpload\downloadUpload.rst:: WARNING: image file not readable: frankConsoleFindTestTools.jpg

I do not have this issue with Sphinx 3.0.3.

**To Reproduce**
```
$ git clone https://github.com/ibissource/frank-manual
$ cd frank-manual
$ git checkout dbc5d68f1b3f056512320782b3a875462c6bce7c
$ cd docs
$ make.bat html
```

**Expected behavior**
The build finishes without warnings

**Your project**
https://github.com/ibissource/frank-manual

**Screenshots**

**Environment info**
- OS: Windows (DOS prompt)
- Python version: 3.8.2
- Sphinx version: 3.5.1
- Sphinx extensions:  ??
- Extra tools: ??

**Additional context**
Here is the console output I have:

[output.txt](https://github.com/sphinx-doc/sphinx/files/6085624/output.txt)

**Comment by tk0miya** [comment]
I hope https://github.com/sphinx-doc/sphinx/pull/8967 will fix this problem. Could you check this please? You can try it with `pip install git+https://github.com/tk0miya/sphinx@8959_unix_pathsep_on_windows`.

**Comment by mhdirkse** [comment]
Dear tk0miya,

Your fix works. I installed the fix with the pip-command you provided. I removed my old "build" directory and did "make.bat html" again. I did not get warnings anymore. I also checked that the file frankConsoleFindTestTools.jpg is rendered again. Thank you very much.

With kind regards,

Martijn Dirkse

**Comment by ndunnewind** [comment]
I ran into the same issue with the `:download:` role. #8967 also seems to work for this problem.
