### ISSUE TITLE
Remove unnecessary dependencies in default install

### ISSUE THREAD

**Issue by enkore** [sphinx-doc/sphinx#8979]
This can likely only be done in a major version bump.

This is the dependency tree of Sphinx:

```
Sphinx==3.5.2
  - alabaster [required: >=0.7,<0.8, installed: 0.7.12]
  - babel [required: >=1.3, installed: 2.9.0]
    - pytz [required: >=2015.7, installed: 2021.1]
  - docutils [required: >=0.12, installed: 0.16]
  - imagesize [required: Any, installed: 1.2.0]
  - Jinja2 [required: >=2.3, installed: 2.11.3]
    - MarkupSafe [required: >=0.23, installed: 1.1.1]
  - packaging [required: Any, installed: 20.9]
    - pyparsing [required: >=2.0.2, installed: 2.4.7]
  - Pygments [required: >=2.0, installed: 2.8.1]
  - requests [required: >=2.5.0, installed: 2.25.1]
    - certifi [required: >=2017.4.17, installed: 2020.12.5]
    - chardet [required: >=3.0.2,<5, installed: 4.0.0]
    - idna [required: >=2.5,<3, installed: 2.10]
    - urllib3 [required: >=1.21.1,<1.27, installed: 1.26.3]
  - setuptools [required: Any, installed: 51.1.1]
  - snowballstemmer [required: >=1.1, installed: 2.1.0]
  - sphinxcontrib-applehelp [required: Any, installed: 1.0.2]
  - sphinxcontrib-devhelp [required: Any, installed: 1.0.2]
  - sphinxcontrib-htmlhelp [required: Any, installed: 1.0.3]
  - sphinxcontrib-jsmath [required: Any, installed: 1.0.1]
  - sphinxcontrib-qthelp [required: Any, installed: 1.0.3]
  - sphinxcontrib-serializinghtml [required: Any, installed: 1.1.4]
 ```

Observations:
- The sphinxcontrib-... are probably rarely used, so imho they shouldn't be required by default.
- requests only seems to be used to check if links are up and to download images. Since Sphinx requires Python 3.5+, I feel like this could be done with the newer stdlib urllib.
- packaging is used in sphinx.ext.doctest to check version specifiers. I'm guessing this is also implemented in setuptools, which could be used instead if that's the case.

(eref 42d478fb6976)

**Comment by tk0miya** [comment]
>The sphinxcontrib-... are probably rarely used, so imho they shouldn't be required by default.

I don't know how much they're used. But +1 for unbundling them. But we need to discuss it before to do that. And it's too late to drop them since the 4.0 release.

>requests only seems to be used to check if links are up and to download images. Since Sphinx requires Python 3.5+, I feel like this could be done with the newer stdlib urllib.
>packaging is used in sphinx.ext.doctest to check version specifiers. I'm guessing this is also implemented in setuptools, which could be used instead if that's the case.

Good point. Before dropping, we need to refactor our code first. Could you send a pull request?
