### ISSUE TITLE
missing line break in pysigline

### ISSUE THREAD

**Issue by ndarmage** [sphinx-doc/sphinx#8980]
When producing the documentation for tex by ``make latexpdf`` with Sphinx v.3.5.2, I've noticed long lines extending out of the right page margin in the output pdf file with dictionaries used as class (or module) attributes. Minimal example:

```
mod_attr = {'key1': [i for i in range(10)], 'key2': 2, 'key3': 'ok'}
class example_class:
    "my class"
    cls_attr = {'key1': [i for i in range(100)], 'key2': 2, 'key3': 'key3'}
    def __init__(self, a):
        self.a = a
```

The problem is caused by the following line in the file sphinx.sty:
\newcommand{\pysigline}[1]{\item[{#1}]}
The optional argument of the item, that is the label, is typeset in horizontal mode, so that it is not possible to have line breaks. A possible solution is to use a parbox like:
\newcommand{\pysigline}[1]{\item[{\parbox[b]{\textwidth}{#1}}]}
which fixed my problem.

**Comment by jfbu** [comment]
Thanks for report. This is related to #7241. Maybe https://github.com/sphinx-doc/sphinx/issues/7241#issuecomment-595751032 will help you with better workaround for time being.

**Comment by jfbu** [comment]
Fixed at 2934aac441392f70d9baad994ea866f6bdbd8352

**Comment by ndarmage** [comment]
Hello, this issue is marked as close.
I retrieved sphinx v.3.5.3 under Py 3.9.2.
Still the file .../sphinx/texinputs/sphinx.sty contains the old line :
```python
\newcommand{\pysigline}[1]{\item[{#1}]}
```
which reproduces the bad behavior (line extending out of page margin) that started the same issue.

Thanks for your kind attention.
Best regards,

**Comment by jfbu** [comment]
Le 12 avr. 2021 à 21:34, ndarmage ***@***.***> a écrit :

> 
> Hello, this issue is marked as close.
> I retrieved sphinx v.3.5.3 under Py 3.9.2.
> Still the file .../sphinx/texinputs/sphinx.sty contains the old line :
> 
> \newcommand{\pysigline}[1]{\item[{#1}]}
> which reproduces the bad behavior (line extending out of page margin) that started the same issue.
> 
> Thanks for your kind attention.
> Best regards,
> 
> 
Hi, https://github.com/sphinx-doc/sphinx/commit/2934aac441392f70d9baad994ea866f6bdbd8352 is a merge into 4.x branch. The 4.0 beta is already out which contains this patch.

**Comment by ndarmage** [comment]
Thanks for your kind reply - c'est noté.
