### ISSUE TITLE
Table of contents items not associated with their headers

### ISSUE THREAD

**Issue by jonels-msft** [sphinx-doc/sphinx#8989]
### Problem

Menu items in the toctree have no markup that associates them with non-link menu headers.
https://github.com/readthedocs/sphinx_rtd_theme/blob/a13a7b4b448b040ae0867d76fe71643bd83035b1/sphinx_rtd_theme/layout.html#L157

The menu headers are merely paragraphs with a class:
```html
<p class="caption"><span class="caption-text">Foo</span></p>
```

### Reproducible Project

https://docs.citusdata.com/en/v9.3/get_started/what_is_citus.html

#### Error Logs/Results

Here is a video demonstrating the problem: https://www.youtube.com/watch?v=BmeXqA3Bzt4

#### Expected Results

A screenreader should understand the relationship of links to headers, and be able to announce e.g. "Link, What is Citus, under Get Started."

See [WCAG 1.3.1](https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships.html) for guidance.

### Environment Info

- Python Version: 3.7.7
- Sphinx Version: 1.4.9
- RTD Theme Version: 0.2.4

**Comment by jonels-msft** [comment]
Originally reported in https://github.com/readthedocs/sphinx_rtd_theme/issues/957 but they suggested I open the bug against Sphinx itself.

**Comment by tk0miya** [comment]
What should we do?

**Comment by jonels-msft** [comment]
This page has suggested techniques: https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships.html#techniques

When i looked through the list, I noticed [H97: Grouping related links using the nav element](https://www.w3.org/WAI/WCAG21/Techniques/html/H97) which might work in the table of contents case.

Basically change this:

```html
<p class="caption"><span class="caption-text">Topic A</span></p>
<ul>
<li class="toctree-l1"><a class="reference internal" href="foo.html"><span class="toctree-expand"></span>Foo</a></li>
<li class="toctree-l1"><a class="reference internal" href="bar.html"><span class="toctree-expand"></span>Bar</a></li>
</ul>
```

to this

```html
<nav aria-label="Topic A">
<p><span class="caption-text">Topic A</span></p>
<ul>
<li class="toctree-l1"><a class="reference internal" href="foo.html"><span class="toctree-expand"></span>Foo</a></li>
<li class="toctree-l1"><a class="reference internal" href="bar.html"><span class="toctree-expand"></span>Bar</a></li>
</ul>
</nav>
```

It might be semantically cleaner to make it all one big list, so Topic A would be a top-level list item, and Foo,Bar would be nested. But it would probably require more CSS tricks to keep the display the same. This `<nav>` technique might require fewer CSS tweaks.

I'm unsure whether a screen reader would say "Topic A" twice given it's an aria-label and a caption. Might require a test...

**Comment by jonels-msft** [comment]
Actually, a simpler way would be to use `aria-labeledby`:

```html
<p class="caption" id="topic-a-header"><span class="caption-text">Topic A</span></p>
<ul aria-labelledby="topic-a-header">
<li class="toctree-l1"><a class="reference internal" href="foo.html"><span class="toctree-expand"></span>Foo</a></li>
<li class="toctree-l1"><a class="reference internal" href="bar.html"><span class="toctree-expand"></span>Bar</a></li>
</ul>
```

You'd just need to have a programmatically defined ID for each caption paragraph.

Additionally you could consider making the paragraphs some level of heading, like `<h3>`. That provides more context that the text is serving as a heading for menu sections.

**Comment by jonels-msft** [comment]
OK, an even simpler way would be using [role=heading](https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA12).
