### ISSUE TITLE
Property gets linked instead of external type in class with inline type annotations

### ISSUE THREAD

**Issue by bluetech** [sphinx-doc/sphinx#8992]
**Describe the bug**

The project is using autodoc with inline Python type annotations. Given the following class (snipped to the relevant parts):

```py
from types import TracebackType

class ExceptionInfo(Generic[E]):
    @classmethod
    def from_exc_info(
        cls,
        exc_info: Tuple[Type[E], E, TracebackType],
        exprinfo: Optional[str] = None,
    ) -> "ExceptionInfo[E]":
        pass

    @property
    def traceback(self) -> Traceback:
        pass
```

The class and `from_exc_info` method get rendered [as follows](https://docs.pytest.org/en/stable/reference.html#pytest._code.ExceptionInfo.from_exc_info):

![Screenshot_2021-03-13 API Reference — pytest documentation](https://user-images.githubusercontent.com/1223550/111029541-d51bbd80-8405-11eb-9fed-b0ac2ece733f.png)

In the class, the `TracebackType` gets rendered as `traceback` and is not linked.

In the method, the `TracebackType` gets rendered as `traceback` and links to the `traceback` property.

**Expected behavior**

I expect it to show as `TracebackType`. A `traceback` is also OK I guess (if it's meant to refer to a "traceback object"), but in that case it should link to https://docs.python.org/3/library/types.html#types.TracebackType or https://docs.python.org/3/reference/datamodel.html#traceback-objects instead of the local property.

**To Reproduce**

I can try to create a minimal reproduction if the above is not sufficient or gets outdated.

**Your project**

https://github.com/pytest-dev/pytest

**Environment info**
- OS: Linux
- Python version: 3.9.2
- Sphinx version: 3.5.2
- Sphinx extensions: 

```py
extensions = [
    "pallets_sphinx_themes",
    "pygments_pytest",
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.intersphinx",
    "sphinx.ext.todo",
    "sphinx.ext.viewcode",
    "sphinx_removed_in",
    "sphinxcontrib_trio",
]
```

**Comment by tk0miya** [comment]
Unfortunately, the real name of `types.TracebackType` is `traceback`.

```
$ python
Python 3.9.1 (default, Dec 18 2020, 00:18:40)
[Clang 11.0.3 (clang-1103.0.32.59)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from types import TracebackType
>>> TracebackType
<class 'traceback'>
>>> TracebackType.__module__
'builtins'
```

As a result, `ExceptionInfo.from_exc_info` was rendered as following (internally):
```
   .. py:method:: ExceptionInfo.from_exc_info(exc_info: Tuple[Type[example.E], example.E, traceback], exprinfo: Optional[str] = None) -> example.ExceptionInfo[example.E]
      :module: example
      :classmethod:
```

After that, the "traceback" name confuses Sphinx.

**Comment by bluetech** [comment]
Ah the `traceback` makes sense now, thanks.

So I guess the problem is that the `builtins` gets elided + has lesser priority than the property. The second part makes sense, but for the first part, is it viable to keep the `builtins`, but just not display it?

**Comment by tk0miya** [comment]
Would you like to see `builtins.int` or `builtins.str`? Of course, it's possible technically. But nobody wants to show it, I think.

**Comment by bluetech** [comment]
I mean that it would become `builtins.traceback` in the sphinx code but rendered in HTML as just `traceback`. But that's just a thought, I didn't try to check how viable this is. Another complicating factor is that `traceback` is not actually present in the `builtins` module.

BTW, if it's rendered as

```rst
   .. py:method:: ExceptionInfo.from_exc_info(exc_info: Tuple[Type[example.E], example.E, traceback], exprinfo: Optional[str] = None) -> example.ExceptionInfo[example.E]
      :module: example
      :classmethod:
```

maybe it makes sense to just skip properties when trying to resolve *types*.

**Comment by tk0miya** [comment]
I just post #9015 to resolve the correct name of `types.TracebackType`.
