### ISSUE TITLE
`@overload` with only one context manager case shows all as context managers

### ISSUE THREAD

**Issue by bluetech** [sphinx-doc/sphinx#8993]
**Describe the bug**

The project is using autodoc with inline Python type annotations.

Given the following function definition (snipped to relevant parts):

```py
@overload
def raises(
    expected_exception: Union[Type[E], Tuple[Type[E], ...]],
    *,
    match: Optional[Union[str, Pattern[str]]] = ...,
) -> "RaisesContext[E]":
    ...


@overload
def raises(
    expected_exception: Union[Type[E], Tuple[Type[E], ...]],
    func: Callable[..., Any],
    *args: Any,
    **kwargs: Any,
) -> _pytest._code.ExceptionInfo[E]:
    ...
```

The type `RaisesContext` is a context manager, but `ExceptionInfo` isn't. It is [rendered as follows](https://docs.pytest.org/en/stable/reference.html#pytest.raises):

![Screenshot_2021-03-13 API Reference — pytest documentation(1)](https://user-images.githubusercontent.com/1223550/111029959-5b390380-8408-11eb-8119-5a3845c34f31.png)

**Expected behavior**

The first case is rendered as `with .. as ..`. The second case is rendered as a regular function.

**To Reproduce**

I can provide a minimal reproduction if the above is not sufficient.

**Your project**

https://github.com/pytest-dev/pytest

**Environment info**
- OS: Linux
- Python version: 3.9.2
- Sphinx version: 3.5.2
- Sphinx extensions: 

```py
extensions = [
    "pallets_sphinx_themes",
    "pygments_pytest",
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.intersphinx",
    "sphinx.ext.todo",
    "sphinx.ext.viewcode",
    "sphinx_removed_in",
    "sphinxcontrib_trio",
]
```

**Comment by tk0miya** [comment]
The standard Sphinx (autodoc) does not render the contextmangers as `with ... as ...`. Is this a bug of sphinxcontrib_trio?

**Comment by bluetech** [comment]
Yes -- the `with` here is handled by `sphinxcontrib_trio`:

```
.. autofunction:: pytest.raises(expected_exception: Exception [, *, match])
    :with: excinfo
```

I thought `sphinxcontrib_trio` was just some async stuff but apparently it does more. Thanks for looking.
