### ISSUE TITLE
Add ability to override external links marking them as internal.

### ISSUE THREAD

**Issue by Blendify** [sphinx-doc/sphinx#8998]
**Is your feature request related to a problem? Please describe.**
Currently when linking to an external URL the '<a>' tag gets a `.external` class.
It would be nice if there was a config option were the user could specify URLs that 
should be internal.

**Describe the solution you'd like**
In `conf.py` a user should be able to do something like this

```
internal_domains = {
        "https://www.blender.org",
        "https://docs.blender.org",
        "https://wiki.blender.org",
}
```

Links that link to these domains should be considered internal (use the `.internal` class instead of `.external`)

**Describe alternatives you've considered**
It is possible to do this in css with:

```
.external[href^="https://www.blender.org"], .external[href^="https://docs.blender.org"], .external[href^="https://wiki.blender.org"] {
	color:#2980B9;
}
```

However, this solution is tricky and can be difficult to remove all the external style rules.

**Comment by tk0miya** [comment]
The CSS class is added by docutils (the reST parser of Sphinx), but it's not treated as a special class in the Sphinx. So the configuration should be added into the docutils itself.

As a workaround, you can remove the class from doctree using a transform:
```
class BlenderURLTransform(Transform):
  def apply():
    for node in self.document.traverse(nodes.reference):
        if node.get('refuri', '').startswith(...):
          node.classes.pop('external', None)
```
