### ISSUE TITLE
Compact module index

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#9]
There should be an option to generate the module index compactly, not
showing the synopses for every module.

[Comment 1  by ted.drain, Sep 14, 2008]

Assuming I understand the intent of this, it would be nice to extend this to also
support generating a short class index as well.  Something similar to what
doxygen/javadoc/others do is a page something something like:
- class/module name and short description
- list of all members (module contents or class contents)
- member 1 detailed docs
- ...
- member n detailed docs

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/9
- Originally reported by: Georg Brandl
- Originally created at: 2008-11-02T22:17:26.118

**Comment by goerz** [comment]
To the extent that this refers to `apidoc`, this could be solved by adding templating support, see #3545

**Comment by tk0miya** [comment]
I think this was already done via autosummary or apidoc. So I'm closing this now.
