### ISSUE TITLE
Logger stops to log in status_iterator

### ISSUE THREAD

**Issue by J-Christophe** [sphinx-doc/sphinx#9005]
**Describe the bug**
When using the a gallery's plugin, the logger stops to log (see my comment https://github.com/sphinx-gallery/sphinx-gallery/issues/479).

I have two ways to fix it:
1/ Replace logger.info(s, nonl=True) by logging.getLogger(__name__).info(s, nonl=True) in sphinx/util/__init__.py
2/ I comment the import of my logging.conf :  https://github.com/J-Christophe/lisacattools/blob/3f5dcaa42adfbbb565252e0cd6016a23791fb901/lisacattools/__init__.py#L56

In the logging.conf, two loggers are defined by default : "root" and "lisacattools". If only "root" is defined, the problem is still there

**To Reproduce**
```
$ git clone https://github.com/J-Christophe/lisacattools
$ cd lisacattools
$ make prepare-dev
$ source .lisacattools-env
$ make install-dev
$ make data 
$ make github -C docs
```
The logger stops at that level :  
Running Sphinx v3.5.1
making output directory... done
generating gallery...
Using Sphinx-Gallery to convert rst text blocks to markdown for .ipynb files.
generating gallery for examples_ucb... [ 28%] plot_source_Mc_DL.py 

But the builds go on (see my comment on https://github.com/sphinx-gallery/sphinx-gallery/issues/479)

**Expected behavior**
The progress should be > 28%: For instance :
generating gallery for examples_ucb... [ 71%] plot_source_joint_sky_pdf.py
NB : Do not wait after that because the other scripts take time to process

**Environment info**
- OS: [Ubuntu 20.04.2 LTS]
- Python version: [3.8.5]
- Sphinx version: [3.5.1]
- Sphinx extensions:  [sphinx-gallery==0.8.2]

**Comment by tk0miya** [comment]
Sphinx uses logging framework to show console messages. And it seems your code resets the whole of the configuration of logging module on loading it.

So please don't reset it automatically on loading your code.

**Comment by J-Christophe** [comment]
Thanks, I found how to make it works (just a stupid boolean to pass as parameter):  
    logging.config.fileConfig(
        os.path.join(PATH_TO_CONF, "logging.conf"),
        disable_existing_loggers=False,
    )
