### ISSUE TITLE
"release" value with underscore leads to invalid LaTeX

### ISSUE THREAD

**Issue by das-g** [sphinx-doc/sphinx#9009]
**Describe the bug**
Underscores (`_`) in the value of the `release` setting aren't properly handled in the generated LaTeX files.

**To Reproduce**

With Sphinx installed (tested with 2.3.1, 3.3.1 and 3.5.2):
- create a new empty directory and change into it:
   ```bash
   cd $(mktemp -d)
   ```
- create a new Sphinx project with `release` set to a name with underscores
   ```bash
   sphinx-quickstart --sep -p coolproject -a "Joe Doe" -r release_with_underscore -l en
   ```
- generate LaTeX files
   ```bash
   make latex
   ```

**Observed behavior**

`build/latex/coolproject.tex` contains the un-escaped release name as an argument to `\release{...}`:
```latex
% ...

\title{coolproject}
\date{Mar 15, 2021}
\release{release_with_underscore}
\author{Joe Doe}
\newcommand{\sphinxlogo}{\vbox{}}
\renewcommand{\releasename}{Release}
\makeindex
\begin{document}
% ...
```

This makes the LaTeX files invalid, as underscores have a special meaning in LaTeX.

**Expected behavior**

The LaTeX should be valid. For that, the underscores from the release name should probably be escaped with `\`:

```latex
% ...

\title{coolproject}
\date{Mar 15, 2021}
\release{release\_with\_underscore}
\author{Joe Doe}
\newcommand{\sphinxlogo}{\vbox{}}
\renewcommand{\releasename}{Release}
\makeindex
\begin{document}
% ...
```

**Your project**
n/a, as the above reproduction is self-contained.

However, we noticed this problem in [gitlab.ost.ch/epj/documentation-template#14](https://gitlab.ost.ch/epj/documentation-template/-/issues/14).

**Screenshots**
n/a

**Environment info**
- OS: Probably all. Tested in
  - Linux
  - Docker
- Python version: 3.7.10
- Sphinx version: Tested with:
  - 2.3.1
  - 3.3.1
  - 3.5.2
- Sphinx extensions:  n/a
- Extra tools:
  - none for above reproduction
  - LaTeX to reproduce the problem in building the LaTeX files (Use `make latexpdf` and note the `"Missing $ inserted"` message.)

**Additional context**

- [gitlab.ost.ch/epj/documentation-template#14](https://gitlab.ost.ch/epj/documentation-template/-/issues/14)

**Comment by tk0miya** [comment]
Thank you for reporting. Reproduced. I'll fix it later.
