### ISSUE TITLE
Displaying UNC paths in ReStructuredText

### ISSUE THREAD

**Issue by kmcanney-sony** [sphinx-doc/sphinx#9014]
In a Sphinx project, I'm attempting to display UNC paths. Let's take \\volume\folder\ for example.

My understanding was that I'd need to double the backslashes as follows in my reStructuredText: `\\\\volume\\folder\\`

Doing that works correctly for the backslashes before and after "folder" but the 4 backslashes before "volume" are still displayed as a single backslash in my output: \volume\folder\

Can anyone advise how to display the double backslashes before "volume" so my output correctly displays \\volume\folder\?

Thanks in advance!

**Comment by tk0miya** [comment]
It seems rendering fine (as two backslashes) in my environment.

Anyway, this is not good place for question. Please re-post this into sphinx-users form: https://groups.google.com/g/sphinx-users or stackoverflow.

Thanks,
