### ISSUE TITLE
Autodoc feature request: Attribute docstring signatures

### ISSUE THREAD

**Issue by drewcassidy** [sphinx-doc/sphinx#9025]
**Is your feature request related to a problem? Please describe.**
Right now theres no way for a docstring for an attribute to define its type option, only a type field, which is frustrating when documenting extension modules. I propose the `autodoc_docstring_signature` feature be extended to include attributes to allow type documentation from within non-python code.

Currently the only workarounds I'm aware of are 
* manually document each attribute
* use the function signature syntax (e.g. `.. autoproperty:: field(type)`) which is kinda weird
* to use the `:type:` field which makes the documentation a lot messier looking than I would like

**Describe the solution you'd like**
similar to functions, allow for the first line of an attribute docstring to contain a signature in the form `name: type`, and have that type automatically added to the `:type:` option (not field) of the auto documented member. 

**Describe alternatives you've considered**
* removing the newline from before `:type:` fields on the first line of a docstring to make them into options instead
* using a function style signature (e.g. `name(self)-> type`) (this is probably the easiest to implement by reusing the method signature function)

**Additional context**

![Screen_Shot_2021-03-20_at_7 16 59_PM](https://user-images.githubusercontent.com/3837797/111892049-f73caf00-89b4-11eb-8e53-91f05ac938f7.png)
<img width="317" alt="Screen_Shot_2021-03-20_at_7 17 07_PM" src="https://user-images.githubusercontent.com/3837797/111892052-fd329000-89b4-11eb-9cf3-d0686edca9da.png">

- this is a similar problem to #7582 but not with napoleon

I'm open to doing a PR for this feature, I just want feedback on what the best way to go about doing it is, and if anyone else wants it.

**Comment by brenthuisman** [comment]
Possibly related:

I have a Pybind project with a class with a property with the following docstring: `":type: int\n\nThe id of the branch."`. This generates something like the first example in your image, but I'd like the second.

`"the_prop() -> int\n\nThe id of the branch."` seems to be picked up, because it disappears from the output, but it's not used to add in the type of the property at all.

When I create some documentation without autodoc, I see that a newline matters. To generate what I see in your example:

```
.. class:: someclass

    .. attribute:: two_ls_passes

        :type: bool

    .. attribute:: two_ls_passes
        :type: bool
```
I'm wondering if autodoc adds this newline as well, and if I can remove it somehow.

**Comment by shimizukawa** [comment]
If sphinx supports pyi files, it would be better than using docstrings to specify types.
i.e. https://github.com/sphinx-doc/sphinx/issues/7630

**Comment by drewcassidy** [comment]
Im not thrilled with the idea of using pyi files if only because it means juggling even more files for an extension module

**Comment by tk0miya** [comment]
I agree with @shimizukawa's idea. The .pyi file is now the standard of Python to distribute type information (see PEP 561; https://www.python.org/dev/peps/pep-0561/). It also helps type checkers, IDEs, and other typing tools. There is no reason to add an original docstring format only for documentation to me.

**Comment by drewcassidy** [comment]
Is there any further documentation on pyi files? I have no idea where to put them or how to write them

**Comment by drewcassidy** [comment]
never mind, i think I figured it out. I agree that this is the best way to go

**Comment by tk0miya** [comment]
Thank you for your understanding.
We must hurry to implement .pyi file support!
