### ISSUE TITLE
Re-introduce  sphinx.environment.NoUri in 3.x

### ISSUE THREAD

**Issue by dilyanpalauzov** [sphinx-doc/sphinx#9032]
According to https://www.sphinx-doc.org/en/master/extdev/deprecated.html sphinx.environment.NoUri is deprecated in v2.1 and will be removed in version 4.  This means, that it shall be available on 3.x.

384650d138a2e68b5337 (or something else) has removed sphinx.environment.NoUri from the 3.x branch.

Either update https://www.sphinx-doc.org/en/master/extdev/deprecated.html to state the version, which removed sphinx.environment.NoUri, or re-introduce sphinx.environment.NoUri on the 3.x branch.

**Comment by tk0miya** [comment]
Indeed. It was removed in v3.0.0 (at https://github.com/sphinx-doc/sphinx/pull/6223). It would be better to update the list to the actual removal version.
