### ISSUE TITLE
Option addition: adjust man page width

### ISSUE THREAD

**Issue by marxin** [sphinx-doc/sphinx#9044]
I may miss that mentioned in the documentation (and so that I asked at StackOverflow [1]). 

Sphinx can generate man pages: `sphinx-build -b man` and the lines are wrapped at 80th character. Is there an option to make the generated manual page width variable? By variable, I mean that wrapping will be done based on terminal width like e.g. `man man`.

[1] https://stackoverflow.com/questions/66891125/how-to-adjust-man-page-width

**Comment by tk0miya** [comment]
AFAIK, Sphinx does not control the width of the man page output. Could you check the envvars of your console? On my local, I can control the width of man page via `MANWIDTH` envvar.
https://stackoverflow.com/questions/30173224/change-width-of-man-command-ouput

**Comment by marxin** [comment]
I don't have the env variable set. Looking at the generated output of `sphinx-build -b man . man` I see the following line splitting:

```
.SS Options for Debugging Your Program
.sp
To tell GCC to emit extra information for use by a debugger, in almost
all cases you need only to add \fI\%\-g\fP to your other options.
.sp
GCC allows you to use \fI\%\-g\fP with
\fB\-O\fP\&.  The shortcuts taken by optimized code may occasionally
be surprising: some variables you declared may not exist
at all; flow of control may briefly move where you did not expect it;
some statements may not be executed because they compute constant
results or their values are already at hand; some statements may
execute in different places because they have been moved out of loops.
Nevertheless it is possible to debug optimized output.  This makes
it reasonable to use the optimizer for programs that might have bugs.
.sp
If you are not using some other optimization option, consider
using \fB\-Og\fP (see optimize\-options) with \fI\%\-g\fP\&.
With no \fB\-O\fP option at all, some compiler passes that collect
information useful for debugging do not run at all, so that
\fB\-Og\fP may result in a better debugging experience.
.INDENT 0.0
.TP
.B \-g
Produce debugging information in the operating system\(aqs native format
(stabs, COFF, XCOFF, or DWARF).  GDB can work with this debugging
information.
.sp
On most systems that use stabs format, \fI\%\-g\fP enables use of extra
debugging information that only GDB can use; this extra information
makes debugging work better in GDB but probably makes other debuggers
crash or
refuse to read the program.  If you want to control for certain whether
to generate the extra information, use \fI\%\-gstabs+\fP, \fI\%\-gstabs\fP,
\fI\%\-gxcoff+\fP, \fI\%\-gxcoff\fP, or \fI\%\-gvms\fP (see below).
.UNINDENT
.INDENT 0.0
.TP
.B \-ggdb
```

which corresponds to http://marxin.eu/sphinx/output/options-for-debugging-your-program.html (which contains rather long lines).

**Comment by marxin** [comment]
Sorry for the noise, the output is correct when I run `man ./gcc.1`.

**Comment by tk0miya** [comment]
:-)

Note: The line folding of man output corresponds to the original source text.

**Comment by marxin** [comment]
> Note: The line folding of man output corresponds to the original source text.

Yes, I can confirm that! Thanks.
