### ISSUE TITLE
(ERROR/3) Undefined substitution referenced:

### ISSUE THREAD

**Issue by xqt** [sphinx-doc/sphinx#9045]
Sphinx provides three default substitutions |release|, |version| and |today|
see: https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#default-substitutions

but their usage fails with (ERROR/3) Undefined substitution referenced:"release"
see: https://integration.wikimedia.org/ci/job/pywikibot-core-tox-doc-docker/14497/console

See also: https://stackoverflow.com/questions/41269319/why-the-substitution-version-is-not-working-on-sphinx

**Comment by tk0miya** [comment]
Please check your log again. The error was raised by rstcheck, not Sphinx.

>19:06:06 doc run-test: commands[1] | rstcheck --recursive --report warning --ignore-directives automodule,autoclass,autofunction .
19:06:06 [163] /src$ /src/.tox/doc/bin/rstcheck --recursive --report warning --ignore-directives automodule,autoclass,autofunction .
19:06:07 ./docs/index.rst:2: (ERROR/3) Undefined substitution referenced: "release".
