### ISSUE TITLE
'Next page' button cutoff when right-hand contents takes entire window

### ISSUE THREAD

**Issue by kn0wmad** [sphinx-doc/sphinx#9060]
**Describe the bug**
The 'next page' button is cutoff by the contents on the right-hand frame, if there is not enough window space - for example, on zoomed window, or window that is not full screen

**To Reproduce**
Create a contents frame long enough to cover the button

**Expected behavior**
The button to move to the left of the fram

**Your project**
github.com/start9labs/documentation

**Screenshots**
![image](https://user-images.githubusercontent.com/39687477/113523907-44e61980-9568-11eb-8dbb-c94aedfb20f1.png)

**Environment info**
- Linux
- Python version: 3.9.2
- Sphinx version: 3.5.2
- Sphinx extensions:  autobuild, book theme
- Firefox

https://docs.start9labs.com/support/FAQ/general-faq.html

**Comment by mgeier** [comment]
This is not a problem with Sphinx itself but with the HTML theme you are using.
You should create an issue at the theme's issue tracker.

**Comment by kn0wmad** [comment]
I'll do that, thank you
