### ISSUE TITLE
contents directive style breaks with docutils 0.17

### ISSUE THREAD

**Issue by ericvanbuhler** [sphinx-doc/sphinx#9065]
After upgrading `docutils` to 0.17, the local tables of contents on my documentation website changed from begin displayed as bulleted lists with indentation:

![image](https://user-images.githubusercontent.com/10039915/113921704-2b78e380-979b-11eb-8292-b810e51034f4.png)

to a flat list:

![image](https://user-images.githubusercontent.com/10039915/113921571-07b59d80-979b-11eb-9310-75d6e61acbc8.png)

The key difference is the way the headers are defined. with `docutils` 0.16 they are defined like this:
```
<div class="section" id="header-1">
```

and with `docutils` 0.17 they are defined like this:
```
<section id="header-1">
```

**To Reproduce**

Here is the `requirements.txt` file for my project:
```
sphinx==3.3.1
recommonmark
sphinx_markdown_tables
```

Here is a sample of what the .rst file looks like:
```
Title
+++++

Content goes here...

.. contents:: :local:

Header 1
--------

Content goes here...

Subheader 1
-----------

Content goes here...

Header 2
--------

Content goes here...

Subheader 2
-----------

Content goes here...
```

I built with the following command:
```
$ make html SPHINXOPTS="-W --keep-going"
```

**Expected behavior**
I expected the local table of contents to be formatted as a bulleted list with indentation.

**Environment info**
- OS: Debian Linux in Docker
- Python version: 3.6.9
- Sphinx version: 3.3.1
- Sphinx extensions:  'sphinx.ext.autodoc', 'recommonmark', 'sphinx_markdown_tables', 'sphinx.ext.napoleon', 'sphinx.ext.autosectionlabel'

**Workaround**
I was able to work around the issue by locking the `docutils` version to 0.16 in my requirements.txt file:
```
docutils==0.16
sphinx==3.3.1
recommonmark
sphinx_markdown_tables
```

**Comment by tk0miya** [comment]
What theme do you use? It seems the default theme of Sphinx; alabaster works fine.

**Comment by mgeier** [comment]
This sounds similar to https://github.com/readthedocs/sphinx_rtd_theme/issues/1115.

**Comment by ericvanbuhler** [comment]
I'm using sphinx_rtd_theme. This looks like the same issue as https://github.com/readthedocs/sphinx_rtd_theme/issues/1115, thanks for sharing that one! If this issue doesn't exist on the standard sphinx theme, we can close the issue here and track progress on the sphinx_rtd_theme issue.

**Comment by tk0miya** [comment]
Thank you for your confirmation. Okay, now closing this.
