### ISSUE TITLE
TOC didn't extract to PO file when I used gettext function.

### ISSUE THREAD

**Issue by HenryHsu** [sphinx-doc/sphinx#9067]
**Describe the bug**
If I set subtitle at toctree as below:

.. toctree::
   :maxdepth: 1
   :hidden:
   :titlesonly:
   :caption: XXXXXX

   Title 1<overview>

I cannot extract "caption" and "Title1" to PO file for localization.

**Expected behavior**
I can extract "Title 1" and "Caption" to PO for localization.

**Environment info**
- OS: Windows10 
- Python version: 3.9
- Sphinx version: 1.8.5

**Comment by Daltz333** [comment]
That is a really old sphinx version...

**Comment by tk0miya** [comment]
Indeed. It's too old. Please try it again with the latest version. I think they've already resolved now.
Thanks,
