### ISSUE TITLE
IndexError: list index out of range on sphinxrenderer.py rst_node = nodes[1]

### ISSUE THREAD

**Issue by neel** [sphinx-doc/sphinx#9070]
**Describe the bug**

Sphinx giving the following error and not generating the HTML output

```
Exception occurred:
  File "/usr/lib/python3.9/site-packages/breathe/renderer/sphinxrenderer.py", line 611, in run_directive
    rst_node = nodes[1]
IndexError: list index out of range
```

**To Reproduce**

```
$ git clone https://github.com/neel/dhyara.git
$ cd dhyara
$ pip install -r requirements.txt
$ mkdir build
$ cd build
$ cmake ..
$ make sphinx
```

**Expected behavior**
Generate HTML output

**Your project**

https://github.com/neel/dhyara.git

**Environment info**
- OS: Arch Linux
- Python version: 3.9.2
- Sphinx version: 3.5.2
- Sphinx extensions:  sphinx.ext.todo, sphinx.ext.autosectionlabel, sphinx.ext.graphviz

Full Traceback attached 
[sphinx-err-l67in1g5.log](https://github.com/sphinx-doc/sphinx/files/6281585/sphinx-err-l67in1g5.log)

**Additional context**

Looks like #3385 (marked close) reappeared.

**Comment by jakobandersen** [comment]
As this is a bug in Breathe I'll close this issue.
