### ISSUE TITLE
autodoc add_module_names equivalent for arguments

### ISSUE THREAD

**Issue by ruro** [sphinx-doc/sphinx#9075]
The `add_module_names = False` configuration seems to only affect the class/function/attribute header names.
The type hints are still always rendered as fully qualified names.

`mypackage/mymodule.py`:
```python
class MyClass:
    """Whatever 1."""
    pass


def foo(arg: MyClass):
    """Whatever 2."""
    pass
```

`conf.py`:
```python
# ...
add_module_names = False
# ...
```

`index.rst`:
```rst
mypackage.mymodule module
=========================

.. automodule:: mypackage.mymodule
   :members:
   :undoc-members:
   :show-inheritance:
```

Expected documentation:
```
foo(arg: MyClass)
    Whatever 2.
```

Actual documentation:
```
foo(arg: mypackage.mymodule.MyClass)
    Whatever 2.
```

## Describe the solution you'd like

I would be OK with any of the following:
```python
add_module_names = False # now affects type annotations too
# or
add_type_module_names = False # new sphinx config option (name up for debate)
# or
autodoc_add_module_names = False # new autodoc config option (name up for debate)
```

## Describe alternatives you've considered

There's a [StackOverflow post](https://stackoverflow.com/questions/51394955/sphinx-remove-module-prefix-for-args-in-automodule) which suggests using the `autodoc_docstring_signature` option to manually specify the function signature. This is not really a viable solution in my opinion.

**Comment by tk0miya** [comment]
+1 for adding a new confval only for autodoc. It would be nice if we can give better name to it. I feel "add_module_names" is a bit ambiguous and difficult to understand its behavior from the name.

**Comment by ruro** [comment]
To be clear, the [`add_module_names` confval](https://www.sphinx-doc.org/en/master/usage/configuration.html?highlight=add_module_names#confval-add_module_names) already exists. It's just that it doesn't affect parameter types for some reason.

**Comment by tk0miya** [comment]
Sorry for confuse. I know that. I thought it's better to separate the confval for autodoc and python-domain.

**Comment by tk0miya** [comment]
Just FYI: Sphinx-4.0 provides a new configuration `python_use_unqualified_type_names`. It suppresses the module name if hyperlinks can be resolved.

**Comment by felix-hilden** [comment]
So does this mean that the proposed `add_module_names` configuration is completely unnecessary?

**Comment by ruro** [comment]
My understanding is that `python_use_unqualified_type_names` only works with resolved refs and only for the `python` domain. Although, I would personally consider this issue fixed if `python_use_unqualified_type_names` would also work for unresolved refs.

**Comment by felix-hilden** [comment]
Oh that's a fair point! Yep.

**Comment by ruro** [comment]
Also, not sure if this deserves a separate issue/feature request, but one more place where sphinx currently produces fully qualified names is in the package/module headings generated with `apidoc`. So for example, if you have
```
foo/__init__.py
foo/bar/__init__.py
foo/bar/baz.py
```
you will get the documentation for
```
foo package
 - foo.bar package
    - foo.bar.baz module
```
instead of
```
foo package
 - bar package
    - baz module
```

The FQN version is kind of redundant, since the parent packages of `bar` and `baz` are already obvious from the ToC. And with longer package/module names, this can lead to really ugly wrapping in the sidebar ToC.
