### ISSUE TITLE
Support multiple docstring

### ISSUE THREAD

**Issue by tchaton** [sphinx-doc/sphinx#9089]
**Is your feature request related to a problem? Please describe.**

Usually, building a documentation will contain API reference, examples and how it works.

API Reference is well cover by Sphinx, but examples and how it works usually live in the doc directly.
And quickly, they are being out of sync.

**Describe the solution you'd like**

Would be nice to have a key - value pair with the docstring, to keep everything in 1 place.

```
class MyClass
  [How-it-works]
  """
   ....
  """
  [API]
  """
   ....
  """
```

```
.. autoclass:: ...MyClass # path to my class.
.. key: How-it-works. # select only How it works docstring
.. docstring-only # don't render API
```

**Describe alternatives you've considered**

**Additional context**

- [e.g. URL or Ticket]

**Comment by felix-hilden** [comment]
Have you considered an alternative like this:

```python
class C:
    """
    Class for doing things.

    This class does things that the extended description
    tells the reader. It's pretty handy for doing things.

    Attributes
    ----------
    a
        Attribute 1: class attribute.
    b
        Attribute 2: instance attribute.

    Examples
    --------
    These are the examples.

    .. code:: python

       >>> c = C()
       >>> c.do_thing()
    """

    a = 1

    def __init__(self):
        self.b = 2

    def do_thing(self):
        """Do Doc."""
```

This example uses Numpy-style docstrings. It's enabled with the extension `sphinx.ext.napoleon`. Then you can use autodoc or any other way you'd like to include the class in your documentation. See [here](https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html#docstring-sections) for all defined sections. And here's how it looks:

![example](https://user-images.githubusercontent.com/25202257/114397987-f1974b00-9ba7-11eb-90ca-cab9a4824b64.png)

**Comment by tk0miya** [comment]
Autodoc uses the `__doc__` attribute to get the docstring of python objects. But it does not support multiple docstring. So we need to create a full source code parser for python from scratch. And I can't imagine this is a common feature for python developers. So -1 for implement this.

**Comment by felix-hilden** [comment]
To add to that, the syntax you propose isn't even valid Python. Although literal lists are allowed in class bodies.

Part of the power of Sphinx comes from the dynamic modification of docstrings (e.g. adding things after the fact for building documentation), so reading them directly from source or parsing like Takeshi suggested wouldn't allow that.

Hopefully my example is enough though!
