### ISSUE TITLE
Sphinx docs with ReadTheDocs theme: custom css not included into the html after build

### ISSUE THREAD

**Issue by AngryMaciek** [sphinx-doc/sphinx#9090]
This is a Q&A issue but I got no reply on stack-overflow, so I would like to contact the developers directly.
It might be a bug report or maybe I am just doing something wrong...

**Describe the bug**
The problem is that my custom _css_ file is not included in the _html_ site resulting after build process with `make html`.
The problem is described here: https://stackoverflow.com/questions/66971299/sphinx-documentation-with-readthedocs-theme-text-block-wrapping

**To Reproduce**
`make html` on a documentation which contains a custom _css_ file. The file will be copied under `_build/html/_static` but it will not be included into the _html_.

**Expected behavior**
I assume that the custom _css_ should be included on top of the _html_ source, just like another one:
```html
  <link rel="stylesheet" href="../_static/pygments.css" type="text/css" />
```

**Environment info**
- OS: macOS
- Python version: 3.7.4
- Sphinx version: 3.5.3
- Sphinx extensions:  sphinx.ext.autodoc, recommonmark, sphinx_rtd_theme
- Extra tools: the problem appears on Chrome, Firefox and Safari

**Comment by tk0miya** [comment]
On my local, it seems a link tag for custom.css is generated.
```
  <link rel="stylesheet" href="_static/css/theme.css" type="text/css" />
  <link rel="stylesheet" href="_static/pygments.css" type="text/css" />
  <link rel="stylesheet" href="_static/graphviz.css" type="text/css" />
  <link rel="stylesheet" href="_static/custom.css" type="text/css" />
```

Could you share a minimal reproducible example, please?

**Comment by AngryMaciek** [comment]
Dear @tk0miya,

I have stripped down my project into a minimal failing example, please find attached two directories: before I run `make html` inside as well as after the build process.

[before.zip](https://github.com/sphinx-doc/sphinx/files/6310728/before.zip)
[after.zip](https://github.com/sphinx-doc/sphinx/files/6310729/after.zip)

The build logs:
```
$ make html
Running Sphinx v3.5.3
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 2 source files that are out of date
updating environment: [new config] 2 added, 0 changed, 0 removed
reading sources... [100%] license
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] license
generating indices... genindex done
writing additional pages... search done
copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded.

The HTML pages are in _build/html.
```

**Comment by tk0miya** [comment]
It seems all of the generated HTML files contains a reference to the custom.css...
```
$ grep -r custom.css after
after/conf.py:    'custom.css',
after/_build/html/index.html:  <link rel="stylesheet" href="_static/custom.css" type="text/css" />
after/_build/html/license.html:  <link rel="stylesheet" href="_static/custom.css" type="text/css" />
after/_build/html/genindex.html:  <link rel="stylesheet" href="_static/custom.css" type="text/css" />
after/_build/html/search.html:  <link rel="stylesheet" href="_static/custom.css" type="text/css" />
Binary file after/_build/doctrees/environment.pickle matches
```

**Comment by AngryMaciek** [comment]
Oh, you are right... 
It seems that this is a bad example. I have simplified my project too much and now it is not failing anymore.
I will post a correct minimal failing example once again.

**Comment by AngryMaciek** [comment]
@tkoyama010 
I am uploading a better example again. I have stripped down my project to leave only the necessary fragments. Please go to _docs_ and execute `make html`. My build logs are:

```
$ make html
Running Sphinx v3.5.3
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 2 source files that are out of date
updating environment: [new config] 2 added, 0 changed, 0 removed
reading sources... [100%] index
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index
generating indices... genindex done
writing additional pages... search done
copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded.

The HTML pages are in _build/html.
```

The resulting _html_ does not have my custom _css_ in the source...

[before.zip](https://github.com/sphinx-doc/sphinx/files/6327779/before.zip)
[after.zip](https://github.com/sphinx-doc/sphinx/files/6327780/after.zip)

**Comment by tk0miya** [comment]
I confirmed the HTML inside after.zip does not have a link tag for custom.css. But it is appeared after the build on my local. Could you check the version of sphinx_rtd_theme? I'm using 0.5.2; the latest version of sphinx_rtd_theme (refs: https://pypi.org/project/sphinx-rtd-theme/).

**Comment by AngryMaciek** [comment]
Yes, I confirm I also use `0.5.2`; I am on macOS `11.0.1`.

**Comment by tk0miya** [comment]
OMG. I did not mention to you about the `html_css_files` setting is commented-out in the after.zip. So I enabled it on rebuilding.

Now I confirmed it again on this Dockerfile:
```
FROM python:3.9-slim

RUN apt update; apt install -y build-essential curl git make unzip vim

RUN pip install Sphinx sphinx_rtd_theme recommonmark
RUN curl -LO https://github.com/sphinx-doc/sphinx/files/6327780/after.zip
RUN unzip after.zip
WORKDIR /after/docs
RUN echo "\nhtml_css_files = ['custom.css']" >> conf.py
RUN make clean html
RUN grep -r custom.css _build/
```

And I got the custom.css tags from the generated docs.
```
Step 9/9 : RUN grep -r custom.css _build/
 ---> Running in bb4508a8e4fb
Binary file _build/doctrees/environment.pickle matches
_build/html/index.html:  <link rel="stylesheet" href="_static/custom.css" type="text/css" />
_build/html/general-info/license.html:  <link rel="stylesheet" href="../_static/custom.css" type="text/css" />
_build/html/genindex.html:  <link rel="stylesheet" href="_static/custom.css" type="text/css" />
_build/html/search.html:  <link rel="stylesheet" href="_static/custom.css" type="text/css" />
Removing intermediate container bb4508a8e4fb
 ---> a4a53fc8c922
```

**Comment by AngryMaciek** [comment]
OMG...
I am terribly sorry, I see that the `html_css_files` is commented in both "before" and "after".  
Once I include it in the code again the _html_ is indeed correct:
```
  <link rel="stylesheet" href="_static/css/theme.css" type="text/css" />
  <link rel="stylesheet" href="_static/pygments.css" type="text/css" />
  <link rel="stylesheet" href="_static/custom.css" type="text/css" />
```

To my surprise, it does not solve the initial problem I wrote about in SO. I know it goes out of this specific issue, but since I already posted it here and still did not get a response on SO - would you be so kind to take a look into it too, kind sir?

### EDIT

There is no need for any further assitance, I have solved my SO problem later today.  
Thank you very much for your help! We can close the issue!
