### ISSUE TITLE
"Parallel mode" error strikes again

### ISSUE THREAD

**Issue by alliter8** [sphinx-doc/sphinx#9092]
**Describe the bug**

Even though [Fix #6803: Disable parallel build on macOS and py38+ #6879](https://github.com/sphinx-doc/sphinx/pull/6879) was implemented, I am once again receiving this error on Big Sur. (I did not experience an issue on Catalina, though I only started using Sphinx a few months ago on this Mac, which is long after those fixes were added.)

When attempting `make html` with the minimal `Makefile` from `sphinx-quickstart`, I get the following error:

```
Running Sphinx v3.5.4
For security reason, parallel mode is disabled on macOS and python3.8 and above. For more details, please read https://github.com/sphinx-doc/sphinx/issues/6803
make: *** [html] Error 2
```

I am *not* receiving this issue with the exact same repo on Windows or Linux.

**To Reproduce**

```
$ cd /path/to/repo
$ make html
```

**Expected behavior**

I expect the html to be built as it does on the other systems.

**Your project**

I cannot share this because it is proprietary.

**Screenshots**

[sphinx parallel error](https://user-images.githubusercontent.com/81274910/114445401-e2eb6c80-9b84-11eb-8652-a4489743c085.jpg)

**Environment info**

- OS: Mac v11.2.3
- Python version: v3.9.3
- Sphinx version: v3.5.4 (Homebrew as recommended in official docs for Mac)
- Sphinx extensions: 'sphinx.ext.autodoc', 'sphinx.ext.autosectionlabel', 'sphinx.ext.graphviz', 'sphinx.ext.inheritance_diagram', 'sphinx.ext.intersphinx', 'sphinx.ext.ifconfig', 'sphinx.ext.mathjax', 'sphinx.ext.napoleon', 'sphinx.ext.todo'
- Extra tools: N/A

**Additional context**

Unfortunately, I have nothing else about why this is happening. I had hoped to come here and find a quick answer, lol.

**Comment by tk0miya** [comment]
Thank you for reporting. We need to reimplement the whole of the parallel build feature to do that.

Same as #6881. Closing.

**Comment by alliter8** [comment]
So, to be clear, this is not on the roadmap currently? Is there a workaround for Mac users?

**Comment by tk0miya** [comment]
Unfortunately, perfectly stalled. We need to scrap and build the whole of the feature. In details, we need to replace the thread model with process model. So it should be fully redesigned. And nobody work on it AFAIK.
