### ISSUE TITLE
fully stylisable topic box

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#910]
Hi!

First of all, thanks for keeping Sphinx a great piece of software! It's got great looks and great configurability.

One thing we were missing though was the ability to fully change the look of the topic box in latex - this is impossible (unless I'm mistaken) due to the fact that some of the latex syntax is generated directly from within the Sphinx builder rather than being a part of the sphinx.sty file.

I patched my Sphinx to fix that but since I don't use Mercurial it's tougher for me to create a pull request than to just write that here, especially that the changes required are quite minor.

in **writers/latex.py**:

```
    def visit_topic(self, node):
        self.body.append('\\setbox0\\vbox{\n'
                         '\\begin{minipage}{0.95\\linewidth}\n')
    def depart_topic(self, node):
        self.body.append('\\end{minipage}}\n'
                         '\\begin{center}\\setlength{\\fboxsep}{5pt}'
                         '\\shadowbox{\\box0}\\end{center}\n')
```

is simplified into:

```
    def visit_topic(self, node):
        self.body.append('\\begin{topicbox}\n')
    def depart_topic(self, node):
        self.body.append('\n\\end{topicbox}')
```

and at the end of **texinputs/sphinx.sty** we add:

```
\newenvironment{topicbox} {
  \setbox0\vbox\bgroup
    \begin{minipage}{0.95\linewidth}
}
{
    \end{minipage}
  \egroup
  \begin{center}
    \setlength{\fboxsep}{5pt}
    \shadowbox{\box0}
  \end{center}
}
```

And voila! Now we can redefine the topicbox environment to have e.g. a box with no shadow and rounded corners using tikz, etc.

What do you think about such a solution?

Best regards,
Michael

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/910
- Originally reported by: [mgielda](https://bitbucket.org/mgielda)
- Originally created at: 2012-04-09T14:03:58.067

**Comment by tk0miya** [comment]
Now sphinx defines and uses `SphinxShadowBox` to represent topic node.
