### ISSUE TITLE
Accessibility: "Example of configuration file" contrast is very bad

### ISSUE THREAD

**Issue by cgay** [sphinx-doc/sphinx#9108]
The contrast in the [config file example](https://www.sphinx-doc.org/en/master/usage/configuration.html?highlight=conf.py#example-of-configuration-file) is really bad. I think the intention is for this example to be instructive, but I can barely read the comments in the file because they're grey on slightly-lighter grey. I had to copy them to my editor and then read them.  Thanks.

**Comment by cgay** [comment]
For the record, I did not add the `bug` label. That's some crazy GitHub magic right there.

**Comment by tk0miya** [comment]
Thank you for reporting. And sorry for the inconvenience. I'll try to fix it after the v4.0.0 release.

**Comment by cgay** [comment]
Thanks, and looking at my original report I think my tone probably wasn't the most friendly. Sorry about that! I don't always take the time to word things in the best way and I should do better.

**Comment by mgeier** [comment]
The code highlighting colors are defined by the `pygments_style` option in `conf.py`, and each `html_theme` has its default Pygments style in case no style is selected by the user.

In case of the Sphinx documentation, `pygments_style` is undefined and the HTML theme uses the Pygments style `trac`:

https://github.com/sphinx-doc/sphinx/blob/668bc9eec9f9e3cbf76b9198d0223dc02dc1d1e2/doc/_themes/sphinx13/theme.conf#L4

I think the colors in the Pygments theme should be changed.

There is already a Pygments issue about the low contrast problem: https://github.com/pygments/pygments/issues/1718

**Comment by cgay** [comment]
Thank you! 💯
