### ISSUE TITLE
html_last_updated_fmt not working

### ISSUE THREAD

**Issue by statiksof** [sphinx-doc/sphinx#9114]
**Describe the bug**

`html_last_updated_fmt` not working e.g in gitlab pages and [readthedocs](https://last-fmt.readthedocs.io/en/latest/). It works perhaps locally. 

**To Reproduce**
```
$ git clone https://github.com/statiksof/test-sphinx
$ cd test-sphinx
$ pip install -r requirements.txt
$ make html 
$ # open build/html/index
```

**Expected behavior**

![last_fmt](https://user-images.githubusercontent.com/42906766/115208474-e3dc4b00-a0fc-11eb-965d-cfe008dcfa9b.png)

**Your project**

https://github.com/statiksof/test-sphinx

**Environment info**
- OS: Unix/Linux
- Python version: 3.8
- Sphinx version: 3.5.4

**Comment by tk0miya** [comment]
It seems pydata theme requires additional settings to display last updated info.
see https://groups.google.com/g/sphinx-users/c/UOy-HwGJGgU

Thanks,
