### ISSUE TITLE
Documentation: "Changed in version 4.0: Renamed master_doc to master_doc"

### ISSUE THREAD

**Issue by chrisjsewell** [sphinx-doc/sphinx#9116]
See https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-master_doc

I imagine this is a mistake? What is the renaming meant to be to/from?

**Comment by mgeier** [comment]
I think the renaming was `master_doc` -> `root_doc`, but keeping `master_doc` for backwards compatibility.

**Comment by chrisjsewell** [comment]
Yeh thanks that's what I was guessing

**Comment by tk0miya** [comment]
Thanks. It must be a bug!

**Comment by chrisjsewell** [comment]
Thanks @tk0miya, perhaps this renaming should be added to https://www.sphinx-doc.org/en/master/extdev/deprecated.html

**Comment by tk0miya** [comment]
It's still available. Not deprecated.
