### ISSUE TITLE
autodoc does not inherit a python class, when docstring is missing in the derived class

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#912]
autodoc does not inherit a python class, when docstring is missing in the derived class

I use:

```
#!sphinx

.. automodule:: agent
    :members:
    :inherited-members:
    :show-inheritance:
```

where agent is a class that imports agentengine, which containes the AgentEngine class.

```
#!python

from agentengine import *


class Agent(AgentEngine):
    def __init__(self, arguments):
        AgentEngine.__init__(self, *arguments)
```

This results as an empty page. The methods inherited from AgentEngine are not shown. When I introduce a docstring for the class.  It suddenly works
from agentengine import *

```
#!python

...
class Agent(AgentEngine):
    """ The Agent class contains and registers agents actions. """
    def __init__(self, arguments):
...
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/912
- Originally reported by: [taghawi](https://bitbucket.org/taghawi)
- Originally created at: 2012-04-14T14:43:33.441

**Comment by shimizukawa** [comment]
_From Bob Ziuchkovski on 2013-04-09 20:25:04+00:00_

Indeed, this would be a welcome enhancement in my book.  My understanding from searching the same issue is that epydoc automatically recognizes and handles this scenario.  It would be very nice if sphinx did the same.

**Comment by tk0miya** [comment]
It seems latest Sphinx recognize subclasses not having any docstring. So I'm closing this.
Feel free to reopen if you're still in problem.

Thanks,
