### ISSUE TITLE
Inconsistent Search Results Behaviour

### ISSUE THREAD

**Issue by daixiang0** [sphinx-doc/sphinx#9135]
**Describe the bug**

I noticed when searching for [ip tagging](https://www.envoyproxy.io/docs/envoy/v1.17.0/api-v3/extensions/filters/http/ip_tagging/v3/ip_tagging.proto.html), that I could only find the page when i matched text in the qualified names referenced on the page. Other pages I could find by matching any text on the page.

**To Reproduce**

I reproduced the below behaviour on firefox, chrome, and safari. I did not test on all versions, but reproduced using latest, 1.17.1, 1.16.1, and 1.13.1

in the search field of [the docs](https://www.envoyproxy.io/docs/envoy/latest/) enter any of these terms: "ip tagging", "ip tag", "ip" and note the results.
enter "iptag" and note the results.
enter "kafka broker", "kafka", "kafka b", "emitting results", then note results.
The first set of terms will not bring up the ip tagging page. "iptag" will return the page by matching on the qualified names in the page. Any of the last terms will bring up the correct [kafka broker page](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/kafka_broker/v3/kafka_broker.proto.html) among its results.

**Expected behavior**
I can get results with `iptag` input.

**Your project**

https://github.com/envoyproxy/envoy/tree/main/docs

**Comment by tk0miya** [comment]
Could you try v4.0.0b1? It contains a fix #8070 for short terms like "ip".

**Comment by daixiang0** [comment]
I try install it but fail:
```
Could not find a version that matches sphinx<4,==4.0.0b1,>=1.5,>=1.8,>=2 (from -r requirements.in (line 89))
...

There are incompatible versions in the resolved dependencies:
  sphinx==4.0.0b1 (from -r requirements.in (line 89))
  sphinx<4,>=2 (from sphinx-tabs==2.1.0->-r requirements.in (line 87))
```
Since I need sphinx-tabs, what can I do? Please help me @tk0miya , thanks.

Is it possible to release a bugfix version for Sphinx3?

**Comment by Daltz333** [comment]
Sphinx Tabs will soon get updated for Sphinx 4

**Comment by daixiang0** [comment]
Happy to hear it!

@Daltz333 could share detail plan, we want it deeply!
