### ISSUE TITLE
Cross-reference to general program namespace unknown when defined inside another program namespace

### ISSUE THREAD

**Issue by SeanDS** [sphinx-doc/sphinx#9137]
**Describe the bug**
I have an option defined without a namespace:

```rst
.. option:: --flag

    Some description.
```

Later in the document I define a program role and reference the option above within an option there:

```rst
.. program:: myprogram

.. option:: --another-flag

    Reference to :option:`--flag`.
```

When built, I get

```
WARNING: unknown option: --flag
```

It seems that when inside a `program` role, `:option:` cannot reference `option` roles that do not have a `program`. How can I make a reference to an option that exists without a corresponding `.. program`?

**To Reproduce**
Example document:

```
Test
####

.. option:: --flag

.. program:: myprogram

.. option:: --another-flag

    Ref to :option:`--flag`.
```

Use `sphinx-build` on the above with some default `conf.py`. During build, the mentioned warning will occur.

**Expected behavior**
The `:option:` reference gets converted to a link to the `--flag` option role.

**Environment info**
- OS: Linux
- Python version: 3.9
- Sphinx version: 3.5.3
- Sphinx extensions: "sphinx.ext.autodoc", "sphinx.ext.autosummary", "sphinx.ext.coverage", "sphinx.ext.doctest", "sphinx.ext.intersphinx", "sphinx.ext.todo", "sphinx.ext.ifconfig", "sphinx.ext.viewcode", "sphinxcontrib.bibtex", "sphinxcontrib.katex", "sphinxcontrib.rsvgconverter", "sphinxcontrib.programoutput",  "numpydoc", "jupyter_sphinx"

**Comment by tk0miya** [comment]
I found the `program` directive can reset its namespace with `None`:

```
.. program:: None
```

So you can refer the option without namespace inside it. But I don't understand why don't you use a program namespace for `--flag` option...

**Comment by SeanDS** [comment]
> But I don't understand why don't you use a program namespace for --flag option...

I want to document command line flags that are shared for many subcommands of my program (like `-v` or `--help`), without repeating myself under each `.. program` directive. Do you have a better suggestion?

**Comment by tk0miya** [comment]
If your command consists of the main command and its sub commands, it's better to define common options as the options for the main command:

```
.. program:: maincmd

.. option:: -v

.. option:: --help

.. program:: maincmd subcmd1

.. option:: --name

.. program:: maincmd subcmd2

.. option:: --otheropt
```

**Comment by SeanDS** [comment]
> I found the `program` directive can reset its namespace with `None`:

This doesn't appear to work, if I understand your response correctly. I changed the text file to:

```
Test
####

.. program:: None

.. option:: --flag

.. program:: myprogram

.. option:: --another-flag

    Ref to :option:`--flag`.
```

I still get the same warning about `--flag` not existing.

**Comment by tk0miya** [comment]
You need to insert `.. program:: None` just before the reference.

```
The default "program" namespace is empty by default.

A reference :option:`--flag` will search the option ``--flag`` for the default program.

.. program:: myprogram

The "program" namespace is now changed to "myprogram".

A reference :option:`--flag` will search the option ``--flag`` for myprogram. It's the same as :option:`myprogram --flags`.

.. program:: None

The "program" namespace is now changed to empty again.

A reference :option:`--flag` will search the option ``--flag`` for the default program again.
```

But this is awful. So it would be better to define an option `--flag` for the main command as I commented above.

**Comment by tk0miya** [comment]
I'm closing this because there is nothing to do more.
Thanks,
