### ISSUE TITLE
Inline interpreted text or phrase warning produced for generated docs

### ISSUE THREAD

**Issue by ad12** [sphinx-doc/sphinx#9140]
**Describe the bug**
The following warning is produced for generated docs:

```
WARNING: Inline interpreted text or phrase reference start-string without end-string.
```

**To Reproduce**
```
$ git clone https://github.com/ad12/DOSMA.git
$ make build-docs
```

**Expected behavior**
For docs that are generated, this warning should not appear.

**Environment info**
- OS: Ubuntu 20.04
- Python version: 3.6.9
- Sphinx version: 3.5.4
- Sphinx extensions:
```
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.intersphinx",
    "sphinx.ext.todo",
    "sphinx.ext.coverage",
    "sphinx.ext.mathjax",
    "sphinx.ext.ifconfig",
    "sphinx.ext.viewcode",
    "sphinx.ext.githubpages",
    "sphinx.ext.napoleon",
    "sphinxcontrib.bibtex",
    "sphinx_rtd_theme",
    "sphinx.ext.githubpages",
]
```
- Extra tools: [e.g. Browser, tex or something else]

**Additional context**

- [e.g. URL or Ticket]

**Comment by hcstern** [comment]
For anyone else who is encountering this error: In my case it was caused by a mismatched backtick ` in a docstring. The warning I was getting was at line 1 of __init__.py but the mismatch was in a submodule's class's function's docstring somewhere.
