### ISSUE TITLE
<picture> element to handle multiple image format and media queries

### ISSUE THREAD

**Issue by nboisteault** [sphinx-doc/sphinx#9147]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to generate [`<picture>`](https://developer.mozilla.org/fr/docs/Web/HTML/Element/picture) HTML element instead of `<img>`. This way we could define multiple `<source>`, e.g. for `webm` and `jpg`.
We could also define media queries.
It allows to have smaller size images for compatible browser and a fallback for incompatible ones.

**Describe the solution you'd like**
For instance, we could have this code in rst:
```
.. picture:: /images/image.webm|/images/image.jpg
```
Which would result to:

```
<picture>
   <source srcset="image.webm">
   <source srcset="image.jpg">
   <img src="image.jpg">
</picture>
```
We could also define media queries for every `<source>`.

**Comment by tk0miya** [comment]
It would be better to add the new directive to reStructuredText itself. So this feature request should be posted to the docutils project.

Note: This is very similar topic: https://sourceforge.net/p/docutils/mailman/message/37264494/


The reStructuredText is not only for converting HTML. So it might not be good to add the notation, IMO. It's not available (ignored?) for other outputs.
