### ISSUE TITLE
Sphinx not rendering flat-table

### ISSUE THREAD

**Issue by alliter8** [sphinx-doc/sphinx#9151]
Sphinx is rendering `list-table` just fine, but `flat-table` is not working. Is this table deprecated or just not functioning for me?

OS -> Win 10 Pro
Sphinx -> v.3.5.4
RTD theme -> v.0.5.2

**Comment by alliter8** [comment]
Sorry, seems like I needed to install the LinuxDoc lib. Everything is working well now. Could this little nugget of info be added to the docs, though? Everything in the documentation points to this being out-of-the-box functionality. Not having it in there sent me spinning for over an hour.

Resolution found here:
[LinuxDoc Sphinx-doc extensions for sophisticated C developer (NEW, 2016-07)](https://pvbookmarks.readthedocs.io/en/master/documentation/doc_generators/sphinx/contributed_extensions/linux/linux.html#install-linux-doc)

**Comment by tk0miya** [comment]
As you saw, the flat-table directive is a part of 3rd party extension of the kernel project. I think it's strange to point it in our document. -1 for adding.
