### ISSUE TITLE
Search result page does not show the highlighted snippets when browsing from the local filesystem

### ISSUE THREAD

**Issue by daronburleson** [sphinx-doc/sphinx#9156]
**Describe the bug**
Search page works well but the search results just show the pages that contain the word that I am searching for without showing a highlighted snippet of the actual word in the context of the search. This **only** happens when navigating the documentation from the local computer. This is not a big problem as the documentation will go finally published somewhere and served by a HTTP server, but it's quite annoying and confusing when you are deploying the files locally. 

**To Reproduce**
Build the documentation in your local machine ("make html")
Open the _build/index.html file with your browser
Search for word and see the result: no snippets from the page results.

**Expected behavior**
Search snippets should be shown 

**Your project**
Link to your sphinx project, or attach zipped small project sample.

**Screenshots**
![search_with_context_](https://user-images.githubusercontent.com/83514889/116793032-9b416c00-aac4-11eb-9008-85e57fdf5d25.png)

![search_without_context](https://user-images.githubusercontent.com/83514889/116793043-a3011080-aac4-11eb-82a8-518ee5b81bb9.png)

**Environment info**
- OS: Mac Big Sur
- Python version: 2.7.16
- Sphinx version: 3.3.1
- Sphinx extensions:  none

**Additional context**
Related StackOverflow issue [https://stackoverflow.com/questions/67346943/search-results-in-sphinx-do-not-show-text-snippets-with-the-searched-word](url).

**Comment by tk0miya** [comment]
I guess this happened when opening search page from local directory, right? If so, this is a restriction of the web browsers. The XHR feature is prohibited on browsing local files. So there is no way to avoid it by Sphinx side, AFAIK.

**Comment by daronburleson** [comment]
Yes, this happened while browsing from the local directory on my computer. Thanks for the explanation! I guess we can close the issue, but maybe adding a little note on the documentation stating this behaviour will help other people if they come across the same situation. Thanks!

**Comment by jzietz** [comment]
We have the same issue on our staging and production system after publishing documentation on both servers. Is there anything we can do to get summary in search results?
