### ISSUE TITLE
Autodoc fails to resolve names inherited from external, mocked grandparent classes

### ISSUE THREAD

**Issue by rtobar** [sphinx-doc/sphinx#9168]
**Describe the bug**

Autodoc fails to resolve names inherited from externa, mockedl grandparent classes, but that are not present in direct, local parent classes.

**To Reproduce**

`a.py`:
```python
from ext import Parent
# Parent (external) defines Inner

class Child(Parent):
    pass

class Grandchild(Child):
    class Inner(Child.Inner):
        pass

```

`conf.py`:
```python
import os
import sys
sys.path.insert(0, os.path.abspath('.'))

project = 'test'
copyright = '2021, me'
author = 'me'
version = '0.1'
release = '0.1'
extensions = [
    'sphinx.ext.autodoc',
]
autodoc_mock_imports = [
    'ext'
]
```

`index.rst`:
```rst
.. autoclass:: a.Grandchild
    :members:
```

Put those files in a directory and run `python -msphinx . html`. It fails with:

```
WARNING: autodoc: failed to import class 'Grandchild' from module 'a'; the following exception was raised:
Traceback (most recent call last):
  ...
  File "/home/rtobar/tmp/a.py", line 7, in <module>
    class Grandchild(Child):
  File "/home/rtobar/tmp/a.py", line 8, in Grandchild
    class Inner(Child.Inner):
AttributeError: type object 'Child' has no attribute 'Inner'
```

**Expected behavior**
`Inner` should be resolved to be a member of `Parent`, even if `Child` doesn't declare one.

**Your project**
The code above should be enough, but this was found while documenting https://gitlab.com/ska-telescope/cbf-sdp-emulator-tango-device. In particular this happened [here](https://gitlab.com/ska-telescope/cbf-sdp-emulator-tango-device/-/blob/master/ska/cbf/tango_device.py#L343), where `Base` is locally defined but it `ConfigureScanCommand` member is inherited from an external class.

**Screenshots**
N/A

**Environment info**
- OS: Linux (various Ubuntu flavours)
- Python version: 3.8, 3.9
- Sphinx version: 3.5.4, also tried with 4.0.0b2
- Sphinx extensions:  sphinx.ext.autodoc
- Extra tools: N/A

**Additional context**

Note that if `Child` is defined like:

```python
class Child(Parent):
    Inner = Parent.Inner
```

then it works. The difference here is that `Parent.Inner` is being explicitly referenced, while in the original case the reference is more subtle.

**Comment by tk0miya** [comment]
It seems you installed a mock to `ext` module. So autodoc does not know how the `ext.Parent` class implemented.
```
autodoc_mock_imports = [
    'ext'
]
```

So it can't find the `Inner` attribute.

**Comment by rtobar** [comment]
@tk0miya yes, I'm mocking the `ext` module, but isn't it the point of mocking that it doesn't matter how the mocked modules/classes are defined?

Note that if I replace:

```python
class Child(Parent):
    pass
```

with

```python
class Child(Parent):
    Inner = Parent.Inner
```

then things work (this is what I'm currently doing to workaround the issue). But at first glance it looks like re-defining `Inner` is unnecessary.

**Comment by rtobar** [comment]
I've changed the title and description of the issue to better reflect that this is an issue with the mocked classes, which wasn't clear in the original title and description.

**Comment by tk0miya** [comment]
>yes, I'm mocking the ext module, but isn't it the point of mocking that it doesn't matter how the mocked modules/classes are defined?

Our mocking system never imports the target module. So autodoc can't know what class, methods, attributes, and so on are defined on the module. So any methods and attributes are inherited even when `ext.Parent` is mocked.

**Comment by rtobar** [comment]
> Our mocking system never imports the target module. So autodoc can't know what class, methods, attributes, and so on are defined on the module. So any methods and attributes are inherited even when `ext.Parent` is mocked.

That's exactly my point: with the mocked `ext.Parent`, `Inner` is not resolved as inherited in the reported case, but is correctly resolved when referred to directly in the second case.

Sorry for not understanding, but I'm not sure what your opinion is on this. So just to be clear: do you think this is not a bug? If not, why is it OK that the second case works and the first doesn't?

**Comment by tk0miya** [comment]
>Sorry for not understanding, but I'm not sure what your opinion is on this. So just to be clear: do you think this is not a bug? If not, why is it OK that the second case works and the first doesn't?

Yes, I think this is a limitation of autodoc_mock_imports, not a bug.

The mock object generates another mock object on accessing its attributes:
```
Parent.Inner  # => New mock object for Parent.Inner

Parent.AnotherAttr  # => New mock object for Parent.AnotherAttr (even if not defined at original object)

Parent.Inner.More.Deep.Inner  # => New mock object for each attribute
```

I agree this is not best implementation. So please let me know the idea of better mocking if you have :-)

**Comment by rtobar** [comment]
> So please let me know the idea of better mocking if you have :-)

Other than a very vague "I'd expect my use case to work out of the box" I don't really have any constructive ideas, sorry. I thought that attribute resolution would have worked already regardless of how it happens, and thought of giving it a try at understanding the autodoc code, and how its mocking system is attached to it. The system is much more complex than I imagined at first, so I don't think I'd be capable of correctly modifying it in order for it to work as I wish.

**Comment by tk0miya** [comment]
Thanks for your comment. Indeed, it's difficult to make it better at present. So please understand it's a limitation of our magic mock module. Thanks,
