### ISSUE TITLE
Support to s5

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#917]
It would be good to add support to s5, so one could build also slides from rst source. Should be easy to implement, using rst2s5. Thanks.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/917
- Originally reported by: [pcav](https://bitbucket.org/pcav)
- Originally created at: 2012-04-30T09:22:16.621

**Comment by tk0miya** [comment]
Instead s6, you can do it with `sphinxjp.themes.s6` extension.
https://pypi.python.org/pypi/sphinxjp.themes.s6/

Anyway, it should be implmented as an extension.

**Comment by pcav** [comment]
Great, thanks for the hint. However, the project seems not to be developed in the recent years. I'd be willing to lend a hand if necessry.
