### ISSUE TITLE
Print traceback on stderr / stdout

### ISSUE THREAD

**Issue by arwedus** [sphinx-doc/sphinx#9177]
**Is your feature request related to a problem? Please describe.**

I would like to see a full traceback on the console, because I have no access to /tmp/, where `sphinx-err-*.log` files are stored.

When I run sphinx with html builder in a Docker container on a Jenkins node, I sometimes get a crash - not always, and never locally. After that, the container is removed and the `/tmp/sphinx-err...log` is lost, because only the logs from within the $BUILD_DIR/logs directory are copied and saved.

A crash output looks like this:

```
Running Sphinx v3.5.4
/lhome/pid23b2/.local/lib/python3.6/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.26.2) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)

Exception occurred:
  File "/lhome/pid23b2/.local/lib/python3.6/site-packages/matplotlib/sphinxext/plot_directive.py", line 262, in setup
    app.add_directive('plot', plot_directive, True, (0, 2, False), **options)
TypeError: add_directive() got an unexpected keyword argument 'alt'
The full traceback has been saved in /tmp/sphinx-err-sm3jy1xk.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
CMakeFiles/documentation_html.dir/build.make:79: recipe for target 'CMakeFiles/documentation_html' failed
```

**Additional context**
behavior occurs (sometimes!) with

- Sphinx 3.5.4
- matplotlib 3.3.4
- Python 3.6.9

**Comment by jakobandersen** [comment]
If I remember correctly, then if you give ``-v`` to ``sphinx-build`` you get this full trace in the output.

**Comment by tk0miya** [comment]
Please pass the `-T` option to `sphinx-build` command (or set `$SPHINXOPTS` envvar if you're using original Makefile).
https://www.sphinx-doc.org/en/master/man/sphinx-build.html#cmdoption-sphinx-build-T
