### ISSUE TITLE
autodoc typehints do not create link for parametrized types

### ISSUE THREAD

**Issue by anntzer** [sphinx-doc/sphinx#9194]
**Describe the bug**

autodoc typehints normally generate a link to the hinted type, but do not do so for parametrized types.

**To Reproduce**
```
$ cat >project.py <<EOF
from typing import Literal

def func(x: Literal["a", "b"], y: int):
    """
    :param x: The x.
    :param y: The y.
    """
EOF
sphinx-apidoc . -o . -F -A me -V 0.0 --extensions sphinx.ext.intersphinx
PYTHONPATH=. make O=-Dautodoc_typehints=description html
```
and open _build/html/project.html

**Expected behavior**
`Literal` (in the parameter description) should link to typing.Literal in CPython's docs, just like `int` does.

**Your project**
N/A

**Screenshots**
![s](https://user-images.githubusercontent.com/1322974/117574897-ab1e0900-b0df-11eb-8813-266fc5c744af.png)

**Environment info**
- OS: linux
- Python version: 3.9.4
- Sphinx version: 4.0.0
- Sphinx extensions: intersphinx, autodoc
- Extra tools: N/A

**Additional context**
N/A

**Comment by tk0miya** [comment]
Duplicated with #9195? Closing.

**Comment by tk0miya** [comment]
Oh, sorry. I understood these are different topic. Reopened now.

**Comment by pradyunsg** [comment]
The issue seems to be stemming from https://github.com/sphinx-doc/sphinx/blob/80fbbb8462f075644e229c9d00293d4afde7adf2/sphinx/ext/autodoc/typehints.py#L33 -- since the types coming from typing are "stringified" and not being passed through intersphinx.

**Comment by pradyunsg** [comment]
I guess the fix here is to pass these through `typing.restify` instead?

**Comment by tk0miya** [comment]
>I guess the fix here is to pass these through typing.restify instead?

No, it will generate incorrect mark-ups:

```
.. py:function:: func(x: :py:class:`Literal`\["a", "b"], y: :py:class:`int`)
```
