### ISSUE TITLE
Sphinx 4.0 inserts doubled css links

### ISSUE THREAD

**Issue by pbudzyns** [sphinx-doc/sphinx#9202]
After building docs with sphinx 4.0 theme stylesheet links in output html are doubled. It occurs for themes only, custom css files works fine.

**To Reproduce**

```
$ git clone https://github.com/pbudzyns/sphinx-minimal.git
$ cd sphinx-minimal
$ pip install sphinx sphinx-rtd-theme
$ sphinx-build docs/ build/
$ cat build/index.html
```

Output:
```
...
<link rel="stylesheet" href="_static/css/theme.css" type="text/css" />
<link rel="stylesheet" href="_static/pygments.css" type="text/css" />
<link rel="stylesheet" href="_static/pygments.css" type="text/css" />
<link rel="stylesheet" href="_static/css/theme.css" type="text/css" />
<link rel="stylesheet" href="_static/custom.css" type="text/css" />
...
```

**Expected behavior**
Unique CSS files from theme are attached only once. 

**Your project**
https://github.com/pbudzyns/sphinx-minimal

**Environment info**
- OS:  Ubuntu 20.04
- Python version: 3.8.5
- Sphinx version: 4.0.0

**Comment by tk0miya** [comment]
It seems sphinx_rtd_theme need to be updated. Please report this to them.
refs: https://github.com/sphinx-doc/sphinx/pull/8732

Thanks,
