### ISSUE TITLE
Support Mobile Browsers

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#921]
It would be unbelievably useful if the default templates displayed well on mobile browsers such as WebKit.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/921
- Originally reported by: Anonymous
- Originally created at: 2012-05-05T11:53:35.182

**Comment by shimizukawa** [comment]
_From Anonymous on 2012-05-24 20:27:42+00:00_

See also: https://github.com/rtfd/readthedocs.org/issues/202

**Comment by shibukawa** [comment]
Alabaster template supports mobile browser.

**Comment by tk0miya** [comment]
Right, this is already resolved. So I close this now.
Thanks,
