### ISSUE TITLE
Undefined references for glossary entries with multiple voices

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#922]
The new glossary feature whereby it is possible to have one explanation
for multiple voices is really great.  There seems to be one remaining
problem in that an anchor seems to be provided only for the first
voice.  For example, suppose we have:

```
   morpheme
   morphemes
      In linguistics, a morpheme is a speech element having a meaning
      or grammatical function that cannot be subdivided into further
      such elements.
```

The idea is to freely use :term:`morpheme` and :term:`morphemes`, but
the latter causes the following:

```
  LaTeX Warning: Hyper reference `glossary:term-morphemes' on page 47 undefined on input line 2906.
```

Would it be possible to provide anchors for all the voices?
Thanks,

```
Roberto 
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/922
- Originally reported by: Anonymous
- Originally created at: 2012-05-05T15:45:37.329

**Comment by flickerfly** [comment]
I'm getting this same error, but I'm not sure if it is related to the same cause. What is this multiple voice idea in glossary?

**Comment by tk0miya** [comment]
It seems latest Sphinx release already support this. I don't know when it was added. So I'm closing this.

@flickerfly Please file an new issue if you still have trouble with latest Sphinx.

Thanks,
