### ISSUE TITLE
Upgrade docutils links to HTTPS?

### ISSUE THREAD

**Issue by igo95862** [sphinx-doc/sphinx#9226]
[Docutils website supports HTTPS](https://docutils.sourceforge.io/docs/ref/rst/directives.html#pull-quote) but all the link in the [sphinx documentation](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#directives) uses unsafe links.

I can create Pull Request.

**Comment by tk0miya** [comment]
Thank you for letting us know. Could you send a pull request, please? Then, I'll merge it soon.

**Comment by igo95862** [comment]
I upgraded not only docutils links but upgraded and fixed some others as well. For example, it seems like Jinja has moved its home page.
