### ISSUE TITLE
Sphinx 4: Error using the autodoc module while Sphinx 3 worked

### ISSUE THREAD

**Issue by Tilix4** [sphinx-doc/sphinx#9227]
**Describe the bug**
Sphinx 4: Using `make html` with the autodoc module returns:

```py
Exception occurred:
  File "/Applications/Blender.app/Contents/Resources/2.83/python/lib/python3.7/site-packages/sphinx/util/typing.py", line 303, in stringify
    elif annotation in INVALID_BUILTIN_CLASSES:
TypeError: unhashable type: 'dict'
```

It was working with Shinx 3.5.4

I've tested by hand to make sure, I can confirm Sphinx 4 makes it crash when Sphinx 3 worked.

**To Reproduce**
```
<Paste your command-line here which cause the problem>

$ install Blender: https://www.blender.org/download/lts/
$ git clone https://gitlab.com/superprod/stax_suite/stax.git
$ cd stax
$ Follow these instructions: https://gitlab.com/superprod/stax_suite/stax/-/blob/master/CONTRIBUTING.md#documentation
```

**Expected behavior**
To build as it did with Sphinx 3.

**Your project**
https://gitlab.com/superprod/stax_suite/stax/-/tree/master/docs

**Environment info**
- OS: Linux Ubuntu
- Python version: 3.7.4
- Sphinx version: 4.0.1
- Sphinx extensions:  [
    "sphinx.ext.autodoc",
    "sphinx.ext.viewcode",
    "sphinx.ext.todo",
    "sphinx_rtd_theme",
    "sphinx_autodoc_future_annotations",
    "sphinx_autodoc_typehints",
    "sphinx.ext.graphviz",
    "sphinx_copybutton",
    "video", # Custom directive
]
- Extra tools: Blender

**Additional context**
It worked like a charm some weeks ago. You can read the Sphinx 4 CICD pipeline failing on my repo: https://gitlab.com/Tilix4/stax/-/jobs/1263417585

The working Sphinx 3 CICD Pipeline: https://gitlab.com/Tilix4/stax/-/jobs/1263526707

You can see the error message in the end of the log.

Here is the full log
[sphinx-err-bv6bgh3r.log](https://github.com/sphinx-doc/sphinx/files/6480291/sphinx-err-bv6bgh3r.log)

**Comment by tk0miya** [comment]
>TypeError: unhashable type: 'dict'

The error lets us know some function or attribute has type annotation using a dict instance. AFAIK, it's wrong type annotations. Is this intended?

Note: You can investigate what function or attribute has wrong type annotation via `-vv` option for `sphinx-build`.

**Comment by jpmckinney** [comment]
If anyone arrives here with `WARNING: error while formatting arguments for XXX: unhashable type: 'list'`, then check that your type annotation is not like `[str]` but rather like `List[str]`.

**Comment by j-ittner** [comment]
> If anyone arrives here with `WARNING: error while formatting arguments for XXX: unhashable type: 'list'`, then check that your type annotation is not like `[str]` but rather like `List[str]`.

That's generally true, but the error also appears to happen for `Callable[[<arg_1>, <arg_2>, ..., <arg_n>], <return>]` which (legally) includes a list of argument types.

**Comment by tk0miya** [comment]
@j-ittner I guess your problem is different with this issue. Could you file a new issue, please? Then I'll investigate it.

**Comment by picnixz** [comment]
@Tilix4 Is the issue still persisting in Sphinx 7.x ? We won't support old Sphinx versions so there won't be any backports.

**Comment by picnixz** [comment]
Closing the issue since the OP hasn't replied for a while. Feel free to reopen if the issue persists with the latest Sphinx version.
