### ISSUE TITLE
Bulleted list in RST rendered without bullet points

### ISSUE THREAD

**Issue by david-cortes** [sphinx-doc/sphinx#9228]
I have this `rst` file with a bulleted list at the beginning: https://github.com/david-cortes/isotree/blob/master/docs/index.rst

With Sphinx 4, this bulleted list is now rendering without the bullet points: https://isotree.readthedocs.io/en/latest/

Was working fine with Sphinx 3.2.

**Comment by tk0miya** [comment]
It seems this is the same as https://github.com/readthedocs/sphinx_rtd_theme/issues/1115.
Please upgrade sphinx_rtd_theme to the latest one.

Thanks,
