### ISSUE TITLE
Proposal: Install Lock bot

### ISSUE THREAD

**Issue by tk0miya** [sphinx-doc/sphinx#9237]
Sometimes we've seen some people posts a message into the already closed issue. In my experience, these messages does not contains enough information to resolve the problem (or improve the feature). So it would be better to post a new issue instead of post a response to the closed issue.

To step go forward with this situation, I'd like to install the Lock bot to this project. It automatically locks issues that are closed and inactive for N days.
https://github.com/apps/lock

I heard this great tool from @pradyunsg (Thanks!). He said the pip project also uses it (refs: https://github.com/pypa/pip/blob/main/.github/lock.yml)

**Comment by astrojuanlu** [comment]
+1 on this (@tk0miya pointed me to this issue [from sphinx-dev](https://groups.google.com/g/sphinx-dev/c/K8_bm4BV9SE/m/wuo7-nC2AwAJ)). Looks like the app has been migrated to https://github.com/dessant/lock-threads

@tk0miya What do you think it's a reasonable wait period? 30 days? I would be happy to send a pull request. After that, we will probably get a massive number of notifications for old closings. Is that acceptable, or do we want to somehow avoid it?

**Comment by tk0miya** [comment]
@astrofrog I think it's time to enable it. Could you send a PR, please? It's helpful to me :-)

**Comment by astrojuanlu** [comment]
I think you pinged the wrong `@astro` person :) Sure, will do today!

**Comment by tk0miya** [comment]
Oops... I'm very sorry, astrofrog.

**Comment by shimizukawa** [comment]
+10!

**Comment by astrojuanlu** [comment]
The action is now running, but it doesn't do anything. I'm not sure why, so I opened an issue upstream: https://github.com/dessant/lock-threads/issues/26

**Comment by astrojuanlu** [comment]
Forget my comment, it's actually working! But it's not generating notifications, see the comment left on dessant/lock-threads#26 for more info.
