### ISSUE TITLE
Submenus in TOC do not show + to denote expandability when hovered over

### ISSUE THREAD

**Issue by FrightRisk** [sphinx-doc/sphinx#9248]
Using the "read the docs" theme. On the main menu in the left sidebar, anything I hover over that is expandable shows a "+". I can click on it to expand it. But on the submenu that opens, none of the expandable items show a "+". I can click on them and then they open and show a "-". I can open and close that item and the icons remain. But as soon as I click on another menu item, it goes away. How can I get expand indicators when hovering in submenus? Even better, how can I have them always show, not just when hovered over? First picture shows no + before "Documents" even though I am hovering over it (the snip tool doesn't show the cursor in captured images)

![image](https://user-images.githubusercontent.com/37218136/118754551-52fcaa80-b835-11eb-8db7-c48fb689d475.png)

And below you can see once I click on it, it shows the icon

![image](https://user-images.githubusercontent.com/37218136/118754199-8985f580-b834-11eb-8848-b3b57108687c.png)

**Comment by mgeier** [comment]
The "read the docs" theme has a separate issue tracker: https://github.com/readthedocs/sphinx_rtd_theme/issues
