### ISSUE TITLE
Formatting error when I make sphinx-build docs for classes that inherits param.Parameterized

### ISSUE THREAD

**Issue by grant-m-s** [sphinx-doc/sphinx#9249]
**Describe the bug**
I am trying to create documentation for some software I am making and I have ran into the following problem. Any of my classes that inherits from param.Parameterized [repo here](https://github.com/holoviz/param) end up having what looks like a "mini" documentation of param written in plaintext after the Docstring stuff I have written. I am not sure whether the problem lies with the param class or sphinx.

This happens when I build both locally and when readthedocs builds it after pushing to my repo.

The output of the example below is shown here:
![image](https://user-images.githubusercontent.com/12834844/118796734-c9c89080-b893-11eb-9f29-6babb7abec24.png)

**To Reproduce**
Here's a small example that produces the same problem:

`conf.py`:
```
import os
import sys

sys.path.insert(0, os.path.abspath("."))

project = "example"
copyright = ""
author = ""

extensions = [
    "sphinx.ext.napoleon",
    "sphinx.ext.autodoc",
    "sphinx.ext.todo",
    "sphinx.ext.coverage",
    "numpydoc",
]

numpydoc_show_class_members = False
numpydoc_show_inherited_class_members = False

autodoc_default_options = {
    "show-inheritance": False,
}

templates_path = ["_templates"]

exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

html_theme = "sphinx_rtd_theme"

html_static_path = ["_static"]
```

`index.rst`:
```
Welcome to Documentation!
========================================

.. autoclass:: example.Example
   :members: example_method

```

`example.py`:
```
import param

class Example(param.Parameterized):
    """Example Class.

    Parameters
    ----------
    example : Type
        Example parameter


    Attributes
    ----------
    example : Type
        Example attribute

    """

    test = param.Boolean()

    def __init__(self):

        testing = True

    def example_method(self, example):
        """Example Method.

        Parameters
        ----------
        example : Type
            Example parameter


        Returns
        ----------
        None

        """

        testing = True

```

**Expected behavior**
I am not expecting the part that prints out:
```
    [1;32mParameters of ‘Example’
    =======================
    [0m
    [1;31mParameters changed from their default values are marked in red.[0m
    [1;36mSoft bound values are marked in cyan.[0m
    C/V= Constant/Variable, RO/RW = ReadOnly/ReadWrite, AN=Allow None
    [1;34mName Value Type Bounds Mode [0m
    test False Boolean (0, 1) V RW
    [1;32mParameter docstrings:
    =====================[0m
    [1;34mtest: < No docstring available >[0m
```

**Environment info**
- OS: Ubuntu 18.04
- Python version: 3.6.9
- Sphinx version: 3.5.2
- Sphinx extensions:     sphinx.ext.napoleon, sphinx.ext.autodoc, sphinx.ext.todo, sphinx.ext.coverage, numpydoc

**Comment by tk0miya** [comment]
It seems the param package decorates the docstring of the subclasses. I saw colorized docstring via console:

```
$ python
Python 3.9.1 (default, Dec 12 2020, 22:52:49)
[Clang 11.0.3 (clang-1103.0.32.62)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import example
>>> print(example.Example.__doc__)
params(test=Boolean, name=String)
Example Class.

    Parameters
    ----------
    example : Type
        Example parameter


    Attributes
    ----------
    example : Type
        Example attribute


Parameters of 'Example'
=======================

Parameters changed from their default values are marked in red.
Soft bound values are marked in cyan.
C/V= Constant/Variable, RO/RW = ReadOnly/ReadWrite, AN=Allow None

Name   Value    Type   Bounds  Mode

test   False  Boolean  (0, 1)  V RW

Parameter docstrings:
=====================

test: < No docstring available >
```

I think Sphinx can't create document for the python package using `param` package.

**Comment by edwardransome** [comment]
Did you ever find a workaround for this? I have the same issue and can see that this issue even appears in the official [Param documentation](https://param.holoviz.org/reference.html).

**Comment by edwardransome** [comment]
We have found a workaround which is to set
```python
param.parameterized.docstring_describe_params = False
param.parameterized.docstring_signature = False
```
directly after importing Param.

**Comment by picnixz** [comment]
Closing since the corresponding package provided a way to patch itself. Also, removing ANSI control sequences from docstrings is (and won't probably) be supported in the future so we probably wouldn't be able to make it work (like, we don't really know whether the ANSI control sequence is part of the docstring or meant for colorizing, and we don't (and should not, probably cannot in cases when it's dynamic) detect whether the docstring is a raw string (wrapped in ``r''``) or not.
