### ISSUE TITLE
Documentation of the default value of highlight_language is unclear

### ISSUE THREAD

**Issue by anntzer** [sphinx-doc/sphinx#9252]
**Describe the bug**
The documentation for the configuration entry `highlight_language` currently states:

> The default language to highlight source code in. **The default is 'python3'.** The value should be a valid Pygments lexer name, see Showing code examples for more details.

> New in version 0.5.

> Changed in version 1.4: **The default is now 'default'.** It is similar to 'python3'; it is mostly a superset of 'python' but it fallbacks to 'none' without warning if failed. 'python3' and other languages will emit warning if failed. If you prefer Python 2 only highlighting, you can set it back to 'python'.

The bold sections (emphasis mine) seem contraductory.  I *guess* this actually means that the default is currently 'default' (not 'python3', despite what the second sentence states), and that it was 'python3' at some point in the past and the first sentence didn't get updated.  But the wording could perhaps be clarified.

**To Reproduce**
**Expected behavior**
**Your project**
**Screenshots**
N/A

**Environment info**
- OS: [e.g. Unix/Linux/Mac/Win/other with version]
- Python version: [e.g. 3.7.1]
- Sphinx version: 4.0.1
- Sphinx extensions:  [e.g. sphinx.ext.autodoc, recommonmark]
- Extra tools: [e.g. Browser, tex or something else]

**Additional context**
N/A

**Comment by tk0miya** [comment]
Thank you for reporting. Indeed, it's wrong. I posted #9253 to fix it.
