### ISSUE TITLE
`make linkcheck` wrongly reports valid anchors as broken for certain links

### ISSUE THREAD

**Issue by mara004** [sphinx-doc/sphinx#9255]
**Description**
`make linkcheck` reports certain links with anchor would be broken, altough they are not.
Example: `https://framagit.org/peppercarrot/wiki/-/blob/master/Creatures.md#phanda`

**Steps to Reproduce**
- initialise a new documentation via `sphinx-quickstart`
- create a file with the aforementioned link connected to `index.rst`
- run `make linkcheck`
```
(...)    broken    https://framagit.org/peppercarrot/wiki/-/blob/master/Creatures.md#phanda - Anchor 'phanda' not found
```

**Expected behavior**
The link is valid and works from the browser, hence it should be reported as `ok` rather than `broken`

**Environment info**
- OS: KDE Neon User 5.21.5 (Linux)
- Python version: 3.8.5
- Sphinx version: 3.5.3
- Extra tools: Chromium M90

**→ Potential duplicate of #9016**

**Comment by mara004** [comment]
As the discussion on #9016 suggests, this is hard to fix. Would it be possible to rather report not-found anchors as `partly ok` or something like this as a workaround?

**Comment by bskinn** [comment]
Concur, having not-found anchors report as a warning, instead of a hard error, would be useful for me, too.

Adding a config/CLI option to convert these linkcheck warnings to errors would be a nice feature also.

**Comment by tk0miya** [comment]
It seems the HTML returned from https://framagit.org/peppercarrot/wiki/-/blob/master/Creatures.md does not contains `#phanda` anchor.
```
$ curl -s -o - -L https://framagit.org/peppercarrot/wiki/-/blob/master/Creatures.md | grep phanda
$ 
```
I can't find any content in the .md file also.

```
$ curl -s -o - -L https://framagit.org/peppercarrot/wiki/-/blob/master/Creatures.md | grep "Argiope Spiders"
$ 
$ curl -s -o - -L https://framagit.org/peppercarrot/wiki/-/blob/master/Creatures.md | grep "DragonCow"
$ 
```
I guess the whole of the content is lazily rendered by JavaScript. Surely this is similar to #9016. So I feel this is also difficult to resolve.

How about using `linkcheck_anchors_ignore`? In this case, the above link is considered as "working" with this setting:
```
linkcheck_anchors_ignore = ['phanda']
```

**Comment by mara004** [comment]
Thanks for the explanation. Where do I need to add this rule?
