### ISSUE TITLE
add_css_file adds file twice.

### ISSUE THREAD

**Issue by cblegare** [sphinx-doc/sphinx#9267]
**Describe the bug**

While playing at building a theme, I noticed that when I use `sphinx.application.Sphinx.add_css_file`, the file gets added twice in the generated HTML.

**To Reproduce**

Create a new theme and setup it with the following setup function

```python
def setup(app):
    app.require_sphinx("3")

    theme_path = Path(__file__).parent.resolve()
    app.add_html_theme("mytheme", str(theme_path))

   # This call behaves wierdly
    app.add_css_file("basic.css")
```

add also the theme conf file:

```ini
[theme]
inherit = basic
stylesheet = mytheme.css

[options]
```

The whether or not I'm using `add_css_file("basic.css")`, the generated `HTML/_static` folder contains 

- `mytheme.css`
- `basic.css`

in either case.

**With** `add_css_file("basic.css")`, the HTML `<head>` looks like (comment added for emphasis on duplicated `link` tag)

```html
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="generator" content="Docutils 0.17.1: http://docutils.sourceforge.net/" />

    <title>A theme &#8212; mytheme 0.0.1 documentation</title>
    <link rel="stylesheet" type="text/css" href="_static/pygments.css" />
    <link rel="stylesheet" type="text/css" href="_static/mytheme.css" />
    <!-- HERE notice there are two -->
    <link rel="stylesheet" type="text/css" href="_static/basic.css" />
    <link rel="stylesheet" type="text/css" href="_static/basic.css" />
    <script data-url_root="./" id="documentation_options" src="_static/documentation_options.js"></script>
    <script src="_static/jquery.js"></script>
    <script src="_static/underscore.js"></script>
    <script src="_static/doctools.js"></script>
    <link rel="index" title="Index" href="genindex.html" />
    <link rel="search" title="Search" href="search.html" />
  </head>
```

**Without** `add_css_file("basic.css")`, the `_stagic/basic.css` `link` tag is added 0 times.

**Expected behavior**

I am not sure was would be the expected behavior.  Should the parent theme CSS always be added implicitely? I am not sure.  But having it linked twice seams weird to me.

**Comment by leotrs** [comment]
I'm having the same problem with `add_js_file`, in particular with the html builder. I am developing a custom theme with a `setup` function that calls `app.add_js_file`. This method calls `self.registry.add_js_file` and then calls `self.builder.add_js_file`. However, the builder has another method called `init_js_files` which includes the following excerpt:
```python
for filename, attrs in self.app.registry.js_files:
    self.add_js_file(filename, **attrs)
```
Since `app.add_js_file` already called put the js file in the registry AND called `self.builder.add_js_file`, every file is being added twice.

The workaround for now is to call `app.registry.add_js_file` from my `setup()` function and then let the builder process the files found there when it calls `init_js_files`. However, this bug should be addressed as the official documentation mentions `app.add_js_file` is the correct way of adding js files.

**Comment by tk0miya** [comment]
I found the reason. CSS/JS files added at `setup()` of theme will be added twice unexpectedly. It must be a bug.

**Comment by mgeier** [comment]
Regardless of the discussed error, I think it is not good to rely on `add_css_file()` in a theme. Ideally, a theme should be usable by just copying the theme directory somewhere and setting [`html_theme_path`](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_theme_path).

There might be a better way to do this (please let me know!), but I've done it like this: https://github.com/mgeier/insipid-sphinx-theme/blob/3336d6b50f5a7c7d18e6efc3a974c4b2e2cc3a60/src/insipid_sphinx_theme/insipid/layout.html#L50-L56

This way, it is not necessary to install the *theme* as an *extension*.

**Comment by leotrs** [comment]
@mgeier I am not installing my theme as an extension. The only change in my conf.py is to set the value of `html_theme`. The theme itself has its own `setup` function that the user need not interact with or even know about.

Furthermore, the [official documentation recommends](https://www.sphinx-doc.org/en/master/development/theming.html#inject-javascript-based-on-user-configuration) `add_js_file` for theme developers.

**Comment by tk0miya** [comment]
Yes, it is one of the officially recommended ways to install JS files. It helps to distribute the HTML theme as a python package.

**Comment by leotrs** [comment]
Did you read what I said upthread?

**Comment by tk0miya** [comment]
Hmm? What do you mean?

**Comment by leotrs** [comment]
The recommend method is broken.

**Comment by tk0miya** [comment]
Yes. The goal of this issue is to fix it.
