### ISSUE TITLE
license mismatch

### ISSUE THREAD

**Issue by dehesselle** [sphinx-doc/sphinx#9274]
**Describe the bug**
The license for sphinx is not specified in an unambiguous way.

**To Reproduce**
Check the following files:
- BSD-3-Clause in readme: https://github.com/sphinx-doc/sphinx/blame/4.x/README.rst#L27
- BSD-2-Clause in LICENSE: https://github.com/sphinx-doc/sphinx/blob/4.x/LICENSE#L11-L17
- generic BSD in setup.py: https://github.com/sphinx-doc/sphinx/blob/4.x/setup.py#L178

**Expected behavior**
The license for Sphinx (I am aware that different licenses for components are mentioned in the license file) should not differ between the various locations.

**Your project**
n/a

**Screenshots**
n/a

**Environment info**
n/a

**Additional context**
n/a

**Comment by mgeier** [comment]
That's interesting!

A change in the license text from BSD-3 to BSD-2 seems to have happened in 26d7aafaaef096c706b563fa3cc17aae322896be.

The badge was added much later: #6892

**Comment by mgeier** [comment]
`setup.py`/PyPI seems to recognize only one "BSD" license:

https://github.com/pypa/trove-classifiers/blob/02a63376c7c9a6898178ba45e129b40c36323ebb/src/trove_classifiers/__init__.py#L203

See also https://github.com/pypa/trove-classifiers/issues/17 and https://github.com/pypa/trove-classifiers/issues/70.

**Comment by dehesselle** [comment]
Good catch, I didn't check for limitations regarding setup.py, I just threw that out there.

**Comment by AA-Turner** [comment]
Would be fixed by #10513

A

**Comment by AA-Turner** [comment]
#10513 has been merged, thanks for raising.

A
