### ISSUE TITLE
RFE: add stuptools target which would allow install documentation (install_sphinx?)

### ISSUE THREAD

**Issue by kloczek** [sphinx-doc/sphinx#9279]
At the moment it is possible to build documentation in any format by use "setup.py build_sphinx -b <format>' but that it is only about generate documentation.

For example I'm trying to generate and install documentation generated by sphinx as roff man pages so I'm using `setup.py build_sphinx -b man` however after that seems like is missing possibility to install that documentation.

I think that it would be good to have something like `setup.py install_sphinx -b <format>  --root </install/root>`

**Comment by kloczek** [comment]
As same as https://github.com/sphinx-doc/sphinx/issues/9517 I thing that this ticket can be closed now.

**Comment by tk0miya** [comment]
Okay, closing now.
