### ISSUE TITLE
Custom module's name "exceptions" is not displayed with autoclass

### ISSUE THREAD

**Issue by AngryMaciek** [sphinx-doc/sphinx#9280]
This might be a bug report or just a "question", I asked on StackOverflow but did not get an answer and one other person commented being able to reproduce the problem...

Please take a look at SO, the issue is documented there:
https://stackoverflow.com/questions/67725999/custom-module-name-is-not-displayed-with-autoclass

**Environment info**
- OS: Mac
- Python version: 3.7.4
- Sphinx version: 3.5.3
- Sphinx extensions:  The docstrings are parsed with `sphinx.ext.napoleon` but the same problem appears on `sphinx.ext.autodoc`

**Comment by tk0miya** [comment]
At present, `exceptions` module has been ignored on prefixing module name.
https://github.com/sphinx-doc/sphinx/blob/4.x/sphinx/domains/python.py#L452-L456

I don't know why this code is needed. It was added at 859e30e485 (14 years ago!).

**Comment by mzjn** [comment]
The code that ignores `exceptions` made some sense in Python 2. See https://stackoverflow.com/q/27030933/407651.

**Comment by tk0miya** [comment]
@mzjn Thank you for your wisdom! I've forgotten the exceptions module completely! The special treatment for the module might be worthy in the py2 era. But it's meaningless at present. I'll remove it in the next release.
