### ISSUE TITLE
:term: referenced via intersphinx is case sensitive

### ISSUE THREAD

**Issue by tomoinn** [sphinx-doc/sphinx#9291]
**Describe the bug**

When a doc website A contains a term in a glossary, that term can be referenced without case sensitivity applied. If, however, that term is referenced from a second doc build B, by adding an intersphinx reference to A, only exact cases match.

**To Reproduce**

Add the following intersphinx reference:

```
'oe': ('https://icebreakerone.github.io/open-energy-technical-docs/main/', None)
```

Then attempt to reference a term within the glossary from a second project, i.e.

```
:term:`data provider` - this fails
:term:`Data Provider` - this correctly references back into the external glossary
```

**Expected behavior**

References to terms in external projects linked through intersphinx resolve in the same way as those defined locally.

**Your project**

https://github.com/icebreakerone/open-energy-technical-docs contains source, https://icebreakerone.github.io/open-energy-technical-docs/main/index.html is the site containing the manifest from which I'm trying to import terms.

**Environment info**

Sphinx build run from linux, python 3.8.6, sphinx 4.0.2

**Comment by jhuitema** [comment]
I've also just run into this. From my (non-exhaustive) testing, it looks like the case-insensitive intersphinx term linking stopped working with Sphinx v3. The term links work correctly in Sphinx 2.4.4 and under.

**Comment by AWhetter** [comment]
A git bisect indicates that this was an intentional change made in https://github.com/sphinx-doc/sphinx/commit/a5dadeb890beca64bb9eabe86e6634c9dd3e1d50 to address #7418.
It's documented that terms are now case sensitive, and this was a breaking change introduced for Sphinx v3.
There was a change made in https://github.com/sphinx-doc/sphinx/commit/61f00bf675c1a2f7955f3d342a560dc8680d87c5 (v3.0.2) to fall back to case insensitive matching and to raise a warning when this happens, but from testing it seems like this doesn't happen for matches against an intersphinx mapping.

**Comment by tomoinn** [comment]
Yup, it looks like the resolver for :term: isn't used when loading references from intersphinx? If anyone has better knowledge of how things are structured they'd probably have a better idea, but as far as I can tell the resolution in intersphinx is happening in https://github.com/sphinx-doc/sphinx/blob/4d90277c49633705148793ab02b28353c8a59b48/sphinx/ext/intersphinx.py#L261 and just doing a straight 'is X in Y' check

**Comment by tomoinn** [comment]
I've had a play patching `intersphinx.py`, adding the following within `missing_reference(...)` and it does what I need, in that it allows for case insensitive match of terms from intersphinx:

This is inside the loop on line 319 of the current version

```
            if objtype == 'std:term' and objtype in inventory:
                cased_keys = {k.lower(): k for k in inventory[objtype].keys()}
                if target.lower() in cased_keys:
                    corrected_target = cased_keys[target.lower()]
                    proj, version, uri, dispname = inventory[objtype][corrected_target]
                else:
                    continue
            else:
                if objtype not in inventory or target not in inventory[objtype]:
                    continue
                proj, version, uri, dispname = inventory[objtype][target]
```
