### ISSUE TITLE
Allow wildcards when excluding paths from sphinx-apidoc

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#930]
Attached patch changes the exclusion feature of sphinx-apidoc to
1. Correctly handle relative root paths (by postponing the normalisation of the exclude paths until after the root path has been made absolute and normalised)
2. Use fnmatch.fnmatch() rather than str.startswith() so that wildcards are supported

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/930
- Originally reported by: Nick Coghlan
- Originally created at: 2012-05-22T09:01:14.640

**Comment by shimizukawa** [comment]
_From James Mills on 2013-06-21 06:05:25+00:00_

+!

**Comment by posita** [comment]
Dup. of #944?

**Comment by shimizukawa** [comment]
I closed #944. 
I salvaged attached patch on BB.
[wildcard_excludes.diff.zip](https://github.com/sphinx-doc/sphinx/files/573547/wildcard_excludes.diff.zip)
