### ISSUE TITLE
Unable to refer a cross reference link inside the table for Markdown

### ISSUE THREAD

**Issue by s-vanam** [sphinx-doc/sphinx#9316]
Hello All , 

I am unable to X-reference a link in the Markdown table by defining a common definition. 

for example, I could X-reference the links in a normal paragraph [google] , [cisco] & [twitter]

Also , I could render the same thing using Github Markdown in tables

| Website 1 | Website 2 | Website 3| 
|-----------|---------------|-----------|
| [google]  | [cisco] | [twitter] | 

When I do the same thing with Sphynx I have issues with rendering the URL references in the table. I have this problem across Multiple themes and also both with recommon and Myst-parsers for Markdown.

An example screenshot 

![image](https://user-images.githubusercontent.com/47424719/121402313-5b995a00-c977-11eb-8eed-450d158f8530.png)

Can someone help me with this 

[//]: # (These are reference links used in the body of this note and get stripped out when the markdown processor does its job. There is no need to format nicely because it shouldn't be seen)

[google]: <https://www.google.com/>
[cisco]: <https://www.cisco.com/c/en_in/index.html?country-redirect=true>
[twitter]: <https://twitter.com/home>

**Comment by astrojuanlu** [comment]
Hi @s-vanam, I think this should probably be raised in the MyST-Parser repository (notice that recommonmark is deprecated). Besides, if you include some code, it will help the developers understand your issue.
