### ISSUE TITLE
Regression: autodoc loses the first staticmethod parameter

### ISSUE THREAD

**Issue by FlotterCodername** [sphinx-doc/sphinx#9318]
This is a re-open of #4769 and #5032.
We considered using `autodoc_preserve_defaults = True` as a workaround but this did not work because it is not in the stable version 4.0.2 yet, I believe.

**Comment by tk0miya** [comment]
I can't reproduce the error. I'd like to know what is happened in your case. I need more information about this bug.
Could you post another issue and follow our issue template, please?
