### ISSUE TITLE
Make 4.x branch documentation available?

### ISSUE THREAD

**Issue by astrojuanlu** [sphinx-doc/sphinx#9341]
**Is your feature request related to a problem? Please describe.**
I see that now the user can either pick `master` or `3.x` in the documentation, which are [the enabled versions on Read the Docs](https://readthedocs.org/projects/sphinx/). After reading the current [Branch Model](https://www.sphinx-doc.org/en/master/internals/release-process.html#branch-model), I wonder if `4.x` should be made available there as well, since it's an active branch where releases are happening.

**Describe the solution you'd like**
Make this work: https://www.sphinx-doc.org/en/4.x/
(And besides, making it the default, rather than `master`? But this is a separate question)

**Describe alternatives you've considered**
I see that release branches are frequently merged to `master`, so changes end up there after some time anyway. However, it looks weird not being able to browse the latest release.
On the other hand, there might be a reason why the latest "active" branch is not published on RTD, but I have not found an explanation on the [internal documentation](https://www.sphinx-doc.org/en/master/internals/).

**Additional context**
Screenshot of the flyout menu on RTD:
![Screenshot 2021-06-14 at 22-35-21 Overview — Sphinx documentation](https://user-images.githubusercontent.com/316517/121955969-db04a000-cd60-11eb-947a-0be1feca0e2b.png)

**Comment by astrojuanlu** [comment]
In fact, as @jdillard pointed out to me, the `3.x` branch doesn't exist on GitHub anymore https://github.com/sphinx-doc/sphinx/branches/all

**Comment by tk0miya** [comment]
We determined to publish only the latest version, not each version. So I inactivated 3.x just now.
Thank you for letting me know.

**Comment by astrojuanlu** [comment]
Makes sense, thanks @tk0miya! I also see that you merged `4.x` into `master` 👍🏽 Closing this issue
