### ISSUE TITLE
External links in toctree don't work in the sidebar

### ISSUE THREAD

**Issue by HuidaeCho** [sphinx-doc/sphinx#9351]
**Describe the bug**
Adding external links to `toctree` works fine in the main document, but it doesn't in the sidebar. In HTML, the sidebar links to `https%3A//example.com` instead of `https://example.com`

Please check this built documentation at https://projpicker.readthedocs.io/en/latest/?badge=latest and try the GRASS GIS module link from the sidebar.

**To Reproduce**
```
$ git clone https://github.com/HuidaeCho/projpicker.git
$ cd projpicker/docs
$ make html
# open build/html/index
# click GRASS GIS module in the main document; it works
# click GRASS GIS module in the sidebar; it doesn't work
```

**Expected behavior**
External links in the sidebar should work.

**Your project**
https://github.com/HuidaeCho/projpicker

**Screenshots**

**Environment info**
- OS: Linux 4.4.172, Slackware 14.2
- Python version: 3.7.2
- Sphinx version: 4.0.2
- Sphinx extensions:  Press Theme 0.7.3

**Additional context**

Could it be a theme issue?

**Comment by HuidaeCho** [comment]
It turned out to be a theme issue. We switched to the default theme. Closing this issue.

**Comment by astrojuanlu** [comment]
Hi @HuidaeCho, were you using `sphinx_rtd_theme` before? Would you like to open this issue there? https://github.com/readthedocs/sphinx_rtd_theme/issues/

**Comment by HuidaeCho** [comment]
@astrojuanlu, I was using the [Press theme](https://github.com/schettino72/sphinx_press_theme) and opened [a PR](https://github.com/schettino72/sphinx_press_theme/pull/59) there, but I'm not sure if my PR is the right fix. They were using `pathto()` even for external links, so the colon in an URL was being encoded to %3A as if it were part of an internal document name. The RTD theme invokes a single function to create the TOC for the sidebar, if I'm not wrong. Does Sphinx have any unified function that can handle both document names and external URLs so I can simply replace `pathto()` with that function? That would be great.
