### ISSUE TITLE
sphinx+myst+rtd-theme doesnt generate bullets for the list in the .md file

### ISSUE THREAD

**Issue by armando-fandango** [sphinx-doc/sphinx#9380]
**Describe the bug**
My readme.md file has this:

```
### For directly running on the host
  
* Anaconda or Miniconda  
* X-window system  
* nvidia drivers 
```

The index.rst is this:

```
.. toctree::
   :maxdepth: 2

   Introduction <README.md>
```

But this is the output (list is without bullet signs):

Anaconda or Miniconda

X-window system

nvidia drivers

**Expected behavior**
The list should come with bullet signs.

**Screenshots**
![image](https://user-images.githubusercontent.com/570019/123341498-02efc280-d51c-11eb-9755-18a33d0b9472.png)

**Environment info**
- OS: Ubuntu 18.04
- Python version: 3.8.5
- Sphinx version: 4.0.2
- MyST extension enabled
sphinx-rtd-theme @ file:///home/conda/feedstock_root/build_artifacts/sphinx_rtd_theme_1617698677674/work
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp @ file:///home/conda/feedstock_root/build_artifacts/sphinxcontrib-htmlhelp_1621704829796/work
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml @ file:///home/conda/feedstock_root/build_artifacts/sphinxcontrib-serializinghtml_1621704833237/work

**Comment by astrojuanlu** [comment]
Hi @armando-fandango , can you show what docutils version do you have? And also, can you inspect the HTML to see if a `<ul>` is being generated? This is most likely a duplicate of https://github.com/readthedocs/sphinx_rtd_theme/issues/1115

**Comment by astrojuanlu** [comment]
And also https://github.com/readthedocs/sphinx_rtd_theme/issues/1115

**Comment by armando-fandango** [comment]
@astrojuanlu The docutils was 0.17.1
>>> import docutils
>>> print(docutils.__version__)
0.17.1

**Comment by astrojuanlu** [comment]
Thanks! This can be closed as duplicate then.

**Comment by armando-fandango** [comment]
> Thanks! This can be closed as duplicate then.

Also it works when I drop back to docutils 0.15.x. Thanks.
