### ISSUE TITLE
automodule in v4.0.2 skips python submodule but v3.4.3 does not

### ISSUE THREAD

**Issue by schiebel** [sphinx-doc/sphinx#9393]
**Describe the bug**

I have a new project on [readthedocs.io](https://casagui.readthedocs.io/en/latest/) .  It is a little complicated because the python package portion is only a part of the overall project. I have it set up so that I can build docs for the whole project or only the python package, and I use a symlink in `docs/sources` to allow the the python package `*.rst` files to be found.

Sphinx version 4.0.2 does not generate documentation for `casagui.bokeh.sources` but version 3.4.3 does...

**To Reproduce**

[Build #14136035](https://readthedocs.org/projects/casagui/builds/14136035/) on readthedocs was built with v4.0.2 and it failed to generate documentation for `casagui.bokeh.sources` but [build #14136505](https://readthedocs.org/projects/casagui/builds/14136505/) did build the [docs for casagui.bokeh.sources](https://casagui.readthedocs.io/en/latest/python/casagui.bokeh.sources.html). I believe the only substantive difference between these two is that I switched from v4.0.2 to v3.4.3.

I'm new to sphinx and readthedocs, so apologies in advance if this turns out to be a silly mistake...

**Comment by astrojuanlu** [comment]
Hi @schiebel , I tried debugging your issue locally but I got these warnings and no output for the sources, even on Sphinx 3:

```
WARNING: autodoc: failed to import module 'resources' from module 'casagui'; the following exception was raised:
No module named '_synthesismaskhandler'
WARNING: autodoc: failed to import module 'utils' from module 'casagui'; the following exception was raised:
No module named '_synthesismaskhandler'
WARNING: autodoc: failed to import module 'casagui'; the following exception was raised:
No module named '_synthesismaskhandler'
WARNING: autodoc: failed to import module 'bokeh.state' from module 'casagui'; the following exception was raised:
No module named '_synthesismaskhandler'
WARNING: autodoc: failed to import module 'bokeh' from module 'casagui'; the following exception was raised:
No module named '_synthesismaskhandler'
WARNING: autodoc: failed to import module 'bokeh.sources' from module 'casagui'; the following exception was raised:
No module named '_synthesismaskhandler'
WARNING: autodoc: failed to import module 'bokeh.utils' from module 'casagui'; the following exception was raised:
No module named '_synthesismaskhandler'
```

I tried finding in your docs how to solve the issue but didn't find anything.

**Comment by schiebel** [comment]
Yes one of the python packages requires `libgfortran3`... see: https://github.com/casangi/casagui/blob/main/.readthedocs.yaml

**Comment by astrojuanlu** [comment]
I can't reproduce this issue locally. Just built the documentation using Sphinx 4.0.2 and I can access http://0.0.0.0:8000/python/casagui.bokeh.sources.html . I propose we continue at casangi/casagui#8 .

**Comment by schiebel** [comment]
I (just) added _pull requests_ to the things built on readthedocs... but it doesn't seem to have built again for casangi/casagui#8

**Comment by schiebel** [comment]
I created the [sphinx-9393](https://github.com/casangi/casagui/tree/sphinx-9393) branch to test out builds and I **cannot** reproduce the problem on readthedocs. I'm not sure why I saw empty documentation files (just sections/subsections).

Sorry for the distraction... however... if you could recommend a fix for the warnings:
```
/home/docs/checkouts/readthedocs.org/user_builds/casagui/checkouts/latest/kernels/python/casagui/bokeh/sources/data_pipe.py:docstring of casagui.bokeh.sources.DataPipe.address:1: WARNING: duplicate object description of casagui.bokeh.sources.DataPipe.address, other instance in python/casagui.bokeh.sources, use :noindex: for one of them
```
it would be very helpful... I'm not sure how to add `:noindex:` with automodule...

```

**Comment by astrojuanlu** [comment]
Glad the other issue is fixed in any case! Would you please close this one and open a new issue for that, with as much detail as possible to reproduce?

**Comment by schiebel** [comment]
OK, thanks very much for your help.
