### ISSUE TITLE
sphinx.ext.graphviz: Node shape cylinder not rendering

### ISSUE THREAD

**Issue by just-krivi** [sphinx-doc/sphinx#9397]
**Describe the bug**

I've been using [sphinx.ext.graphviz](https://www.sphinx-doc.org/en/master/usage/extensions/graphviz.html) extension to render graphs using [graphviz](https://graphviz.org/).

The problem is when I tried to apply a `cylinder node shape` ([graphviz node shapes](https://graphviz.org/doc/info/shapes.html)), to represent a database, it's being rendered just as a regular rectangle node, as what happens by default. I've tried with other node shape types, not all of them, but the ones that I've tried worked properly. 

**To Reproduce**

Here is a simple example graph that illustrates the problem.

To reproduce use following directive with graph and add it to the docstring or rst file:
```
.. graphviz::


  digraph G {
    node1 [shape="cylinder",label="DB 1"];
    node2 [shape="cylinder",label="DB 2"];
    node1->node2;
  }
```

**Expected behavior**

This is the [desired and expected](https://dreampuf.github.io/GraphvizOnline/#%2F*%20Generated%20by%20GvGen%20v.1.0%20(https%3A%2F%2Fwww.github.com%2Fstricaud%2Fgvgen)%20*%2F%0A%0Adigraph%20G%20%7B%0Acompound%3Dtrue%3B%0A%20%20%20node1%20%5Bshape%3D%22cylinder%22%2Clabel%3D%22DB%201%22%5D%3B%0A%20%20%20node2%20%5Bshape%3D%22cylinder%22%2Clabel%3D%22DB%202%22%5D%3B%0Anode1-%3Enode2%3B%0A%7D%0A) graph.

**Screenshots**

How it should look like:
![image](https://user-images.githubusercontent.com/30963594/124275675-267dc300-db43-11eb-9cd0-f407b970de11.png)

What we get as a result:
![image](https://user-images.githubusercontent.com/30963594/124275702-309fc180-db43-11eb-8507-dfc3ac309aeb.png)

**Environment info**
- OS: [Mac 11.3]
- Python version: [3.8]
- Sphinx version: [3.4.3]
- Sphinx extensions:  [sphinx.ext.graphviz]

**Comment by tk0miya** [comment]
On my local, cylinders are rendered as expected from your input. Internally, the graphviz extension passes the given diagram to the dot command. So I guess your graphviz command does not support cylinders shape. Could you check your command, please?

**Comment by just-krivi** [comment]
Apologies on my side for the late reply. :) 

I'm using [GvGen](https://github.com/stricaud/gvgen) python library to create graphviz graphs and save them into the .dot files. The library seems to be working fine and generating graph without any errors. I also used [graphviz onlie editor](https://dreampuf.github.io/GraphvizOnline/#%2F*%20Generated%20by%20GvGen%20v.1.0%20(https%3A%2F%2Fwww.github.com%2Fstricaud%2Fgvgen)%20*%2F%0A%0Adigraph%20G%20%7B%0Acompound%3Dtrue%3B%0A%20%20%20node1%20%5Bshape%3D%22cylinder%22%2Clabel%3D%22DB%201%22%5D%3B%0A%20%20%20node2%20%5Bshape%3D%22cylinder%22%2Clabel%3D%22DB%202%22%5D%3B%0Anode1-%3Enode2%3B%0A%7D%0A) to double check if graphs are created without any errors with that library.

Those files are later on put provided to the graphviz directive, which is in the docstring :
```
.. graphviz:: file_containing_graphviz_graph.dot
    :align: center
```

It doesn't work neither by directly putting the graph with cylinder shaped nodes under the graphviz directive nor if I provide the .dot file path to the directive.

To be honest, I'm not completely sure what you meant to check my command?

**Comment by tk0miya** [comment]
>To be honest, I'm not completely sure what you meant to check my command?

The graphviz extension simply passes your input diagram to the `dot` command. So please try `dot -T png -o output.png file_containing_graphviz_graph.dot`.

**Comment by just-krivi** [comment]
Thanks for helping out and for explanation!

I've tried generating png from dot file via `dot command` and it renders cylinder shaped nodes fine.

Here is the version that's being used:
```bash
dot -V
> dot - graphviz version 2.47.2 (20210527.0053)
```

Uploaded image that is rendered from demo example:
![image](https://user-images.githubusercontent.com/30963594/126795900-c4662e5d-0fa1-40c8-8637-0079cc4d2636.png)

**Comment by just-krivi** [comment]
I'm building docs from docker container with base image `amazonlinux:2.0.20210326.0` and in Dockerfile, I'm installing the graphviz: `RUN yum install graphviz`.

Could it be maybe for some reason because of that?

**Comment by tk0miya** [comment]
Please try converting on where you built the document actually. 

>Could it be maybe for some reason because of that?

I think so. Sphinx simply invokes the `dot` command internally. The graphviz extension passes through the given string (or file) to the command. No additional conversions and modifications there. So I guess the `dot` command you used does not support the cylinder shape. The reason of this problem is environment, I think.

**Comment by just-krivi** [comment]
@tk0miya thanks again for helping out and for detailed explanation how sphinx renders graphs!
