### ISSUE TITLE
Typo in sphinx.locale.get_translation doc strings?

### ISSUE THREAD

**Issue by igo95862** [sphinx-doc/sphinx#9408]
### Describe the bug

```
import os
from sphinx.locale import get_translation

MESSAGE_CATALOG_NAME = 'myextension'  # name of *.pot, *.po and *.mo files
 _ = get_translation(MESSAGE_CATALOG_NAME)

text = _('Hello Sphinx!')
       
def setup(app):
    package_dir = path.abspath(path.dirname(__file__))
    locale_dir = os.path.join(package_dir, 'locales')
    app.add_message_catalog(MESSAGE_CATALOG_NAME, locale_dir)
```
This code snippet in get_translation doc string references `path.abspath` and `path.dirname` which are not imported.

Most likely it actually references `os.path.abspath` and `os.path.dirname`.

### How to Reproduce

Link to typo: https://github.com/sphinx-doc/sphinx/blob/996c5855bcda6cc49986bcecd18290c9fcd5e06c/sphinx/locale/__init__.py#L217

### Your project

sphinx

### OS

Linux

### Python version

3.9

### Sphinx version

latest

**Comment by tk0miya** [comment]
Surely. Could you send a pull request, please?
