### ISSUE TITLE
Autodoc generates invalid xml 

### ISSUE THREAD

**Issue by nemani** [sphinx-doc/sphinx#9413]
### Describe the bug

When using autodoc along with python function signatures containing "params" with XML builder the generated xml is not valid. 

We think the issue is due to the following commit: https://github.com/sphinx-doc/sphinx/commit/30c594fbc592a741956c067f5188f9bf6ecd25da#

### How to Reproduce

1. git clone https://github.com/nemani/sphinx-bug-report-example 
1. Install sphinx
1. cd docs
1. make xml
1. xmllint --noout docs/build/xml/index.xml

### Expected behavior

The generated XML should be valid and xml lint should not have any errorss

### Your project

https://github.com/nemani/sphinx-bug-report-example

### OS

mac 

### Python version

3.7.5

### Sphinx version

4.0.3

### Sphinx extensions

sphinx.ext.autodoc

### Extra tools

- 

### Additional context

-

**Comment by nemani** [comment]
This is being a huge blocker for me.
@tk0miya any suggested workarounds for this?

**Comment by nemani** [comment]
I have a suggested fix up as a PR.

**Comment by ghost** [comment]
The moment I thought to have finally found a solution to work around `autodoc` bugs... this appears to be also broken at the baseline. Lol. Please, please fix it... the amount of work I've invested already in trying to generate documentation and trying to work around broken parts is getting into the area where it would've been just easier to do it all from scratch.
