### ISSUE TITLE
CJK render issue in latexpdf code block

### ISSUE THREAD

**Issue by zhsj** [sphinx-doc/sphinx#9414]
### Describe the bug

Some extra spaces are inserted in the code block if there are CJK characters.

### How to Reproduce

Create a simple project with 3 files.

```
==> conf.py <==
project = 'test'
copyright = '2021, test'
author = 'test'
language = 'zh_CN'
```
```
==> index.rst <==
.. code-block:: json

   {
     "test": "你好"
   }

.. code-block:: json

   {
     "test": "こんにちは"
   }
```
```
==> Makefile <==
# Minimal makefile for Sphinx documentation
#

# You can set these variables from the command line, and also
# from the environment for the first two.
SPHINXOPTS    ?=
SPHINXBUILD   ?= sphinx-build
SOURCEDIR     = .
BUILDDIR      = _build

# Put it first so that "make" without argument is like "make help".
help:
        @$(SPHINXBUILD) -M help "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)

.PHONY: help Makefile

# Catch-all target: route all unknown targets to Sphinx using the new
# "make mode" option.  $(O) is meant as a shortcut for $(SPHINXOPTS).
%: Makefile
        @$(SPHINXBUILD) -M $@ "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)
```

Built with the docker

```
docker run --rm -it -v `pwd`:/docs sphinxdoc/sphinx-latexpdf
```

### Expected behavior

No extra spaces.

### Your project

none

### Screenshots

![image](https://user-images.githubusercontent.com/227180/124650958-e87af900-decc-11eb-8a5c-26f08e14a528.png)

There are some extra space between `"` and the first CJK character.

### OS

Linux

### Python version

3.9.6

### Sphinx version

4.0.3

**Comment by zhsj** [comment]
Probably the root cause is at xeCJK :thinking:

**Comment by tk0miya** [comment]
It seems this issue came from the combination of the JSON lexer of pygments and xeCJK package.

I can reproduce it with the following command (it does not use Sphinx at all):
```
echo '"你好"' | pygmentize -l json -f latex -O full -O 'preamble=\usepackage{xeCJK}' > json.tex && xelatex json.tex
```
<img width="92" alt="スクリーンショット 2021-07-07 10 45 11" src="https://user-images.githubusercontent.com/748828/124687726-70cebd80-df10-11eb-8695-89acbba9d37b.png">

It seems whitespace appears just after the opening quote.

But it's not reproduced if I use python lexer.
```
echo '"你好"' | pygmentize -l python -f latex -O full -O 'preamble=\usepackage{xeCJK}' > python.tex && xelatex python.tex
```
<img width="104" alt="スクリーンショット 2021-07-07 10 44 53" src="https://user-images.githubusercontent.com/748828/124687737-775d3500-df10-11eb-866d-b8540d233d1d.png">


I don't know this bug is either pygments or xeCJK. But this is not related to Sphinx itself, I believe. Could you report this to their project, please?

**Comment by zhsj** [comment]
Thanks for narrowing down the issue.

**Comment by zhsj** [comment]
https://tex.stackexchange.com/questions/374469/extra-spaces-when-using-fancyvrb-with-xecjk

```tex
\documentclass{article}
\usepackage{fancyvrb}
\usepackage[utf8]{inputenc}
\usepackage{xeCJK}



\begin{document}

{
\CJKsetecglue{}
\begin{Verbatim}
"你好"
\end{Verbatim}
}

{
\begin{Verbatim}
"你好"
\end{Verbatim}
}

\end{document}

```

the output is

![image](https://user-images.githubusercontent.com/227180/124717479-bce12880-df37-11eb-8d4c-9f0140f4d065.png)


Any suggestion to create a local env and add `\CJKsetecglue{}` for `Verbatim` to workaround this?

**Comment by zhsj** [comment]
I miss a better solution in the tex.stackexchange.com,

Adding `\AtBeginEnvironment{Verbatim}{\CJKsetecglue{}}` is just enough.

So for sphinx, it's adding `\AtBeginEnvironment{sphinxVerbatim}{\CJKsetecglue{}}` to preamble.

@tk0miya could sphinx workaround this by adding above line to default preamble when xeCJK is used?

**Comment by stone-zeng** [comment]
A better solution:

```tex
% Preamble
\fvset{formatcom=\xeCJKVerbAddon}
```

or

```tex
% Locally
\begin{Verbatim}[formatcom=\xeCJKVerbAddon]
"你好"
\end{Verbatim}
```

See <https://github.com/CTeX-org/ctex-kit/issues/331>.

**Comment by zhsj** [comment]
CTeX-org/ctex-kit#331 is written in Chinese, in summary, it's not easy to fix on xeCJK side.

**Comment by zhsj** [comment]
I can confirm adding `\fvset{formatcom=\xeCJKVerbAddon}` to sphinx preamble configuration fix the problem.

**Comment by muzimuzhi** [comment]
Checking [how they are defined](http://www.tug.org/svn/texlive/trunk/Master/texmf-dist/tex/latex/fancyvrb/fancyvrb.sty?view=markup&pathrev=57488#l590), `formatcom*=\xeCJKVerbAddon` is better than `formatcom=...`. Also I've proposed a patch to `xeCJK` in https://github.com/CTeX-org/ctex-kit/issues/580#issuecomment-875701046.
