### ISSUE TITLE
Please do a Sphinx 4.1.x prerelease to PyPI

### ISSUE THREAD

**Issue by PhilipMay** [sphinx-doc/sphinx#9423]
Hi,

I would like to have a Sphinx 4.1.x prerelease on PyPI.
Can you create one please?

**Comment by astrojuanlu** [comment]
Hi @PhilipMay , it would help if you gave a bit of context on why do you need such a thing, if it's urgent or not, etc. From what I understand from #9412, the release is coming _this weekend_. Can you wait a few days?

**Comment by PhilipMay** [comment]
> Can you wait a few days?

I can. Thanks!
