### ISSUE TITLE
Images aren't copied over anymore after upgrade to 4.1.0

### ISSUE THREAD

**Issue by ahill187** [sphinx-doc/sphinx#9437]
### Describe the bug

After upgrading to Sphinx 4.1.0, our logo file is not being properly copied over. When we build our docs, the logo is missing. This was working perfectly fine before the upgrade.

We noticed that for our `conf.py` file with this line:

```
html_logo = './_static/img/sct_logo_blue.png'
```

the resulting path in the rendered version is:

```
'../_static/../imgs/sct_logo_blue.png'
```

Note how the folder name was changed from `img` to `imgs`? 

### How to Reproduce

```
$ git clone https://github.com/spinalcordtoolbox/spinalcordtoolbox
$ cd spinalcordtoolbox/documentation
$ pip install sphinx
$ pip install -r requirements.txt
$ make html
```

### Your project

https://github.com/spinalcordtoolbox/spinalcordtoolbox

### Screenshots

<img width="744" alt="sphinx" src="https://user-images.githubusercontent.com/23019211/125356620-4cf9e600-e31b-11eb-8d66-520098c225a4.png">

### OS

Mac

### Python version

3.6.12

### Sphinx version

4.1.0

**Comment by ViktorHaag** [comment]
Duplicated in #9438 -- I'm happy to close mine if you want, or we can close this one as a duplicate?

**Comment by ahill187** [comment]
> Duplicated in #9438 -- I'm happy to close mine if you want, or we can close this one as a duplicate?

Oh I didn't see that, sure we can close this one as a duplicate!
