### ISSUE TITLE
Hide/show possibility for html-generated text.

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#945]
It would be useful to have possibility to hide/show some parts of the document's text (it is possible only for html) like code folding.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/945
- Originally reported by: Konstantin Sedykh
- Originally created at: 2012-06-09T07:24:10.472

**Comment by tk0miya** [comment]
-1 for adding such a feature to the core. I can't imagine how the block is represented in non-HTML formats. I think it is better to use CSS and JS to control visual decorations of HTML output.
