### ISSUE TITLE
`:property:` directive does not work

### ISSUE THREAD

**Issue by lmmx** [sphinx-doc/sphinx#9452]
### Describe the bug

I have tried all possible ways of using the `py:property:` directive [as introduced in March](https://github.com/sphinx-doc/sphinx/pull/7298) in #7298 and can't get it to work for me.

I have Python 3.9 and Sphinx 4.1.1 and made a minimal reproduction repo

### How to Reproduce

The quickest way to show you what I mean is to [view the ReadTheDocs build](https://sphinx-property-bug-demo.readthedocs.io/en/latest/api.html#demo-class-foo)

The steps to reproduce for yourself are below.

Optional: conda setup with Python 3.9 (though I also found the same result on 3.8)
```sh
conda create -n sphinx_property_bug_demo
conda activate sphinx_property_bug_demo
conda install python=3.9
```

Clone my demo repo and pip install its doc-building requirements:

```sh
git clone https://github.com/lmmx/sphinx-property-bug-demo/
pip install -e .[docs]
cd docs
make html
```

Open `_build/html/api.html` and see the un-modified directives "left in" rather than becoming inline code elements.

### Expected behavior

I expected the following docstring:

```py
#. Attempt to write :property::`greeting`.
#. Attempt to write :py:property::`greeting`.
#. Attempt to write :prop::`greeting`.
#. Attempt to write :py:prop::`greeting`.
```

to give a list where there was the word greeting in a code block like this:

> Attempt to write `greeting`.

but instead I got the original directive, including the word property, and the colons, "intact", like this:

> 1. Attempt to write :property::_greeting_.
> 2. Attempt to write :py:property::_greeting_.
> 3. Attempt to write :prop::_greeting_.
> 4. Attempt to write :py:prop::_greeting_.

See attached [repo](https://github.com/lmmx/sphinx-property-bug-demo/) and [ReadTheDocs](https://sphinx-property-bug-demo.readthedocs.io/en/latest/api.html)

### Your project

https://github.com/lmmx/sphinx-property-bug-demo/

### OS

Linux

### Python version

3.9

### Sphinx version

4.1.1

### Sphinx extensions

"sphinx.ext.autodoc", "sphinx.ext.autosummary", "sphinx.ext.intersphinx", "sphinx.ext.doctest", "sphinx.ext.napoleon", "sphinx.ext.viewcode", "sphinx_autodoc_typehints",

### Additional context

This feature was introduced by @tk0miya and @eric-wieser in #7298 (https://github.com/sphinx-doc/sphinx/pull/7298) following on from #7068, but I don't think the problem I'm observing has been reported yet.

I also tried disabling the Napoleon and `sphinx_autodoc_typehints` extensions, neither made a difference to the result.

**Comment by eric-wieser** [comment]
```
#. Attempt to write :property::`greeting`.
#. Attempt to write :py:property::`greeting`.
#. Attempt to write :prop::`greeting`.
#. Attempt to write :py:prop::`greeting`.
```
Unless I'm mistaken, all four of these are just invalid syntax. Do any of them work with `meth` or `function`?

The valid syntaxes are ``:role:`greeting` `` or `<newline> .. directive:: greeting <newline>`.

**Comment by tk0miya** [comment]
It seems you're misunderstanding the wording. In this case, the "directive" is a syntax to describe the property object, not for reference.

```
.. py:property:: SomeClass.prop

   blah blah blah.
```

And I guess what you want is a "role". To refer the defined property, please use ``:py:attr:` role.
```
blah blah blah :py:attr:`SomeClass.prop` blah blah blah
```

Thanks,

**Comment by lmmx** [comment]
Ahh, no it seems I'm the one who's mistaken! So it's an internal reference to it being a property then, my bad. Sorry for this.

I was reading [this page](https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html) on domains and it seems I should have been reading [just this section of it](https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#cross-referencing-python-objects) on cross-referencing

I missed the fine print:

> **:py:attr:**
>    Reference a data attribute of an object.
>
>    Note
>    The role is also able to refer to property.

Thanks very much!
