### ISSUE TITLE
assert 'Verbatim' in lines[0]

### ISSUE THREAD

**Issue by jaidisido** [sphinx-doc/sphinx#9458]
### Describe the bug

Upgrading `sphinx` from 4.0.3 to 4.1.0 raises an `nbsphinx` exception when building docs in ReadTheDocs:
writing... failed
```
Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/aws-data-wrangler/conda/latest/lib/python3.9/site-packages/nbsphinx.py", line 2151, in depart_codearea_latex
    assert 'Verbatim' in lines[0]
AssertionError
The full traceback has been saved in /tmp/sphinx-err-332dfpxm.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
```

### How to Reproduce

Error happens in ReadTheDocs build so not sure how to reproduce. Building locally works fine:
https://github.com/awslabs/aws-data-wrangler/blob/main/building/build-docs.sh

### Your project

https://github.com/awslabs/aws-data-wrangler/tree/main/docs

### OS

Catalina

### Python version

3.9

### Sphinx version

4.1.0

### Sphinx extensions

sphinx==4.0.3 sphinx_bootstrap_theme==0.7.1 nbsphinx==0.8.6 nbsphinx-link==1.3.0

**Comment by mgeier** [comment]
I think this is the same as https://github.com/spatialaudio/nbsphinx/issues/584.

As mentioned there, the problem exists since #9166.

This issue could be either fixed here or in `nbsphinx`.

@dham Do you have an idea how to best solve this?

**Comment by jfbu** [comment]
As [commented](https://github.com/spatialaudio/nbsphinx/issues/584#issuecomment-882386084) at  https://github.com/spatialaudio/nbsphinx/issues/584, the https://github.com/sphinx-doc/sphinx/pull/9166 transforms container  classes into LaTeX environment. This upsets the nbsphinx.depart_codearea_latex(), as first line is not as expected. Simply removing from this procedure the two assert seems to solve the issue, as the output LaTeX code is then valid.

The #9166 provides opportunity to abstract away from output latex the latex additions done by the nbsphinx code and put them into suitable `sphinxnbinput` or `sphinxnboutput` environment definitions. This I hope can be done in a conditional way, even entirely from LaTeX by testing if `\sphinxuseclass` is defined (as it is the master dispatch to individual LaTeX environments).

**Comment by jfbu** [comment]
> The #9166 provides opportunity to abstract away from output latex the latex additions done by the nbsphinx code and put them into suitable `sphinxnbinput` or `sphinxnboutput` environment definitions. T

sorry I meant `sphinxclassnbinput` and `sphinxclassnboutput`.

**Comment by jaidisido** [comment]
I see that issue https://github.com/spatialaudio/nbsphinx/issues/584 which is related to this has been merged and closed. Does this mean it will be fixed in the next `sphinx` release (4.1.3)? Thanks

**Comment by tk0miya** [comment]
No, it will be fixed in the next nbsphinx's release instead of Sphinx. I think there is nothing to do on Sphinx side. So I'm closing this.
Thanks,

**Comment by mgeier** [comment]
> it will be fixed in the next nbsphinx's release

Yes indeed. I've just made a new `nbsphinx` release (version 0.8.7) which should fix the issue.

**Comment by jaidisido** [comment]
Confirm upgrading to 0.8.7 solved this, thanks for the fix
