### ISSUE TITLE
PEP 585 type hints not rendered correctly

### ISSUE THREAD

**Issue by Gobot1234** [sphinx-doc/sphinx#9463]
### Describe the bug

If you use a PEP 585 generic as an annotation i.e. `list[str]`, autodoc renders the annotation as `list` rather than `list[str]`, this behaviour differs from using `typing.List[str]` which renders as expected.

Fixing this is quite simple as far as I can tell, https://github.com/sphinx-doc/sphinx/blob/810a1e2988b14f4d139b5ef328a91967f5ed7a08/sphinx/util/typing.py#L311-L313 just needs to check if the annotation has `__args__` and if it does, return `repr(annotation)`

### How to Reproduce

```py
def foo() -> list[str]:
	...
```

```rst
.. autofunction:: foo
```

### Expected behavior

An annotation of `list[str]` to be rendered as `list[str]`

### Your project

https://github.com/Gobot1234/sphinx-test

### Screenshots

![image](https://user-images.githubusercontent.com/50501825/126038116-252eee01-228a-42bb-b6ab-23bdf72968e3.png)

### OS

Mac

### Python version

Python 3.9.3

### Sphinx version

4.1.1

### Sphinx extensions

autodoc

**Comment by astrojuanlu** [comment]
Hi @Gobot1234 , would you please upload your project to GitHub instead? Google Drive is not very convenient to read code.

**Comment by Gobot1234** [comment]
https://github.com/Gobot1234/sphinx-test

**Comment by Gobot1234** [comment]
@astrojuanlu Should I open a PR to fix this?

**Comment by tk0miya** [comment]
@Gobot1234 Yes, please!
