### ISSUE TITLE
automodule: add option to ignore __all__

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#947]
I'm dealing with a large set of Python modules and would like a way to see all the code in the generated HTML documentation.  This would be a conveniently way to search for duplicated code and such.

However, currently the automodule extension honors the `__all__` defined in modules, which is nice.  But it would also be nice to have an option that would ignore the `__all__` so that all the functions and classes in a module are pulled out and documentation generated.

I propose adding a 'hidden-members' that would effectively ignore the `__all__` variable, generating documentation for all vars, methods & classes, including those not specified in the `__all__`.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/947
- Originally reported by: Nick Hilton
- Originally created at: 2012-06-12T21:20:55.983

**Comment by rmorshea** [comment]
You can work around this by adding your constants to `__all__`
