### ISSUE TITLE
Multiple glossary terms do not always link

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#948]
In the generated pdf file, where there are multiple terms per glossary entry, only cross-references to the first term have a working link.
For example, suppose the glossary includes:

```
   dictionary
   dictionaries
      A *dictionary* is a list of words ...
```

and there are references to this entry:

```
A vocabulary has one or more :term:`dictionaries`, where each :term:`dictionary` ...
```

Only a link to the glossary term "dictionary" is created in the latex. The cross-reference to the term "dictionaries" generates a warning message during the build.

Note that this problem only applies to the generated pdf file; all the cross-reference links appear to work in the generated html file.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/948
- Originally reported by: Anonymous
- Originally created at: 2012-06-13T09:12:42.956

**Comment by usaturn** [comment]
It is not reproduced in the current version.
I will close it.

# Environment info
- OS: Windows 10
- Python version: 3.5.2
- Sphinx version:
- TeX : TeX Live 2016
