### ISSUE TITLE
Insipid Theme Error

### ISSUE THREAD

**Issue by Rickodesea** [sphinx-doc/sphinx#9485]
### Describe the bug

Get this error every time try to use the Insipid theme.  No error is given when using the Alabaster theme:

```
# Sphinx version: 1.8.5
# Python version: 3.8.10 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 2.10.1
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/cmd/build.py", line 300, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3/dist-packages/sphinx/application.py", line 263, in __init__
    self._init_builder()
  File "/usr/lib/python3/dist-packages/sphinx/application.py", line 324, in _init_builder
    self.builder.init()
  File "/usr/lib/python3/dist-packages/sphinx/builders/html.py", line 329, in init
    self.init_templates()
  File "/usr/lib/python3/dist-packages/sphinx/builders/html.py", line 378, in init_templates
    self.templates.init(self, self.theme)
  File "/usr/lib/python3/dist-packages/sphinx/jinja2glue.py", line 190, in init
    self.loaders = [SphinxFileSystemLoader(x) for x in loaderchain]
  File "/usr/lib/python3/dist-packages/sphinx/jinja2glue.py", line 190, in <listcomp>
    self.loaders = [SphinxFileSystemLoader(x) for x in loaderchain]
  File "/usr/lib/python3/dist-packages/jinja2/loaders.py", line 163, in __init__
    self.searchpath = list(searchpath)
TypeError: 'PosixPath' object is not iterable
```

### How to Reproduce

```
make html
```

config file:
```python
html_theme = 'insipid'
```

Everything else is default.

### Expected behavior

Should produce the HTML manual

### Your project

https://github.com/mgeier/insipid-sphinx-theme

### OS

Ubuntu 20.04

### Python version

3.8.10

### Sphinx version

1.8.5

### Additional context

[sphinx-test.zip](https://github.com/sphinx-doc/sphinx/files/6858865/sphinx-test.zip)

**Comment by astrojuanlu** [comment]
Hi @Rickodesea , do you have the possibility of upgrading Sphinx? The version you are using is quite old.

**Comment by Rickodesea** [comment]
```
sudo apt-get install python3-sphinx
```
results:
```
python3-sphinx is already the newest version (1.8.5-7ubuntu3).
```
![image](https://user-images.githubusercontent.com/23009333/126569252-d94d91c4-91e4-44b5-9c84-c16cc066b9cf.png)

**Comment by Rickodesea** [comment]
Issue seems to only exist on Ubuntu 20.04.  Ubuntu 18.04 works fine.

**Comment by Rickodesea** [comment]
```
python3 -c 'import sphinx; print(sphinx.__version__)'
```
results:
```
4.1.1
```

**Comment by astrojuanlu** [comment]
Thanks for checking! If the problem is only with Sphinx 1.8 and Sphinx 4.1 works fine, I think there is not much that can be done here.

**Comment by tk0miya** [comment]
I confirmed the latest Sphinx can build the attached document without error:
```
# Dockerfile
FROM python:3.9-slim

RUN apt update; apt install -y build-essential curl git unzip vim
RUN curl -LO https://github.com/sphinx-doc/sphinx/files/6858865/sphinx-test.zip
RUN unzip sphinx-test.zip
WORKDIR /sphinx-test
RUN pip3 install sphinx insipid-sphinx-theme
RUN make html
```

**Comment by Rickodesea** [comment]
> I confirmed the latest Sphinx can build the attached document without error:
> 
> ```
> # Dockerfile
> FROM python:3.9-slim
> 
> RUN apt update; apt install -y build-essential curl git unzip vim
> RUN curl -LO https://github.com/sphinx-doc/sphinx/files/6858865/sphinx-test.zip
> RUN unzip sphinx-test.zip
> WORKDIR /sphinx-test
> RUN pip3 install sphinx insipid-sphinx-theme
> RUN make html
> ```

Thank you @tk0miya .  The issue is fixed by upgrading my python from Python3.8 to Python3.9
