### ISSUE TITLE
Add autoproperty to the documentation

### ISSUE THREAD

**Issue by SwampFalc** [sphinx-doc/sphinx#9486]
The current documentation for `ext.autodoc` does not mention the existence of `autoproperty`.

Since I spent a few hours trying to find a workaround, only for a random comment in a thread to reveal that it actually exists, I would like this documentation error to be fixed.

**Comment by tk0miya** [comment]
Indeed, it must be added.

**Comment by astrojuanlu** [comment]
For reference, the `.. autoxxx` directives are registered here:

https://github.com/sphinx-doc/sphinx/blob/186bbc11e946211795c07da8244d1029ef979bb8/sphinx/application.py#L1106

and the `PropertyDocumenter` class is defined here:

https://github.com/sphinx-doc/sphinx/blob/1f860cb77ee3183c3b2c96058c4992f4f5870c52/sphinx/ext/autodoc/__init__.py#L2555-L2559

and was added in Sphinx 2.1.0.
