### ISSUE TITLE
cached_property does not show typehint

### ISSUE THREAD

**Issue by SwampFalc** [sphinx-doc/sphinx#9487]
### Describe the bug

When documenting a `functools.cache_property`, the type hint is not shown.

### How to Reproduce

I have a class that has a number of `functools.cached_property` methods.

Both through `:members:` as well as through `autoproperty`, I am unable to have them show their type hint.

To doublecheck, I turned some of them into regular `property` methods, and their type hint does get shown.

### Expected behavior

`functools.cached_property` methods should show their typehint.

### Your project

x-special/nautilus-clipboard copy file:///home/ldt/Projects/mde3/exportit/sphinx.zip

### Screenshots

![image](https://user-images.githubusercontent.com/20422044/126643517-6537986c-608c-4144-aa44-a20698113483.png)

At the top, I changed it to a regular `property`, at the bottom I left it as a `functools.cached_property`.

### OS

Linux Ubuntu 20.0.4

### Python version

3.9.6

### Sphinx version

4.1.1

### Sphinx extensions

autodoc

**Comment by SwampFalc** [comment]
Oops, that upload failed...

[sphinx.zip](https://github.com/sphinx-doc/sphinx/files/6862430/sphinx.zip)

**Comment by tk0miya** [comment]
Could you let me know the way to build this example? It seems some additional libraries are needed.

**Comment by tk0miya** [comment]
I reproduced the error with following code:

```
from functools import cached_property


class Foo:
    @property
    def prop1(self) -> int:
        """docstring"""
        return 0

    @cached_property
    def prop2(self) -> int:
        "docstring"
```
