### ISSUE TITLE
.. snippet

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#950]
Hello,

My problem:

The documentation of my project Atta need to share descriptions of the parameters, return values ​​and other information in a hierarchy of classes.

After several hours searching the web, unfortunately not found a solution for the Sphinx (maybe I was looking badly ;)).

I wrote a small extension, which I think can be useful to other users.

Define snippet:

.. snippet :: name

   some text ...

Use snippet (in any other file):

.. snippetref :: name

Sources and demonstration you will find in the attached file.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/950
- Originally reported by: Piotr Boguslawski
- Originally created at: 2012-06-21T01:24:51.003

**Comment by AA-Turner** [comment]
For reusable snippets of reST, use `.. include::` directives.

A
