### ISSUE TITLE
4.1.2 test suite regressions with Python 3.10.0b4: TypeError: isinstance() arg 2 must be a type, a tuple of types or a union

### ISSUE THREAD

**Issue by mgorny** [sphinx-doc/sphinx#9505]
### Describe the bug

Sphinx 4.1.2's test suite has 367 test failures and 13 errors with Python 3.10.0b4. They all seem to have a common cause in:

```
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

obj = <class 'autodoc_target.Class'>

    def isNewType(obj: Any) -> bool:
        """Check the if object is a kind of NewType."""
        if sys.version_info >= (3, 10):
>           return isinstance(obj, typing.NewType)
E           TypeError: isinstance() arg 2 must be a type, a tuple of types or a union

obj        = <class 'autodoc_target.Class'>

sphinx/util/inspect.py:215: TypeError
```

### How to Reproduce

```
$ git clone https://github.com/sphinx-doc/sphinx
$ cd sphinx
$ tox -e py310
```

### Your project

n/a

### OS

Gentoo Linux

### Python version

3.10.0b4

### Sphinx version

4.1.2 (+ git master)

### Additional context

Full superverbose build log (17M): [dev-python:sphinx-4.1.2:20210727-064745.log](https://github.com/sphinx-doc/sphinx/files/6883359/dev-python.sphinx-4.1.2.20210727-064745.log)

**Comment by mgorny** [comment]
This is how a similar problem was fixed in hypothesis: https://github.com/HypothesisWorks/hypothesis/pull/3044/files

**Comment by tk0miya** [comment]
Oops... the change of NewType was introduced after b4 release. It will be included in the next release (rc1?). Could you wait for it for a while?

**Comment by mgorny** [comment]
That would effectively mean we can't package new Sphinx version until it happens. Can't you just extend `sys.version_info` check to include beta5?

**Comment by psss** [comment]
Hi, seems one of our tests is failing on this on Fedora Rawhide.

> Could you wait for it for a while?

Sure, but how roughly long is "a while"? :) Is it worth disabling failing tests or will it be fixed soon?

**Comment by abravalheri** [comment]
Hello, I also found the [same error](https://cirrus-ci.com/task/6118524063055872?logs=test#L962) when running `sphinx-build ...` / `python -m sphinx ...` on [Python 3.10.0b4](https://github.com/docker-library/python/blob/05b3ac67046ed211befb80510ce49cd415cea243/3.10-rc/buster/Dockerfile) on my project (not related to `sphinx` test suite).

**Comment by tk0miya** [comment]
3.10.0rc1 will be released next Monday. IMO, it's not too far.
https://www.python.org/dev/peps/pep-0619/#schedule

**Comment by abravalheri** [comment]
Aaah, OK, I see, so sphinx should be compatible with 3.10.0rc1, right?

That is wonderful news, thank you very much @tk0miya 👏

**Comment by tk0miya** [comment]
Yes, we're using the HEAD of 3.10 for testing. So it will be compat with 3.10.0rc1. (But I can't promise that because it's still fragile)

**Comment by mgorny** [comment]
And so it turns out that due to other last minute changes, sphinx 4.1.2 is compatible neither with 3.10.0b4 nor with 3.10.0rc1.
