### ISSUE TITLE
Eliminate the need for conf.py

### ISSUE THREAD

**Issue by woutdenolf** [sphinx-doc/sphinx#9506]
Using Sphinx involves lots of boilerplate. The `conf.py`file is a prominent example of that. Only a limited subset of parameters can be defined in `setup.cfg` (setuptools configuration). I was wondering whether it would be possible to allow everything to be configured in `setup.cfg` thereby eliminating the need for `conf.py` altogether. Many projects like pytest, black, flake8 etc. do this.

**Comment by astrojuanlu** [comment]
Without agreeing or disagreeing with your proposal, if we are debating about moving the configuration to a different file, we should be talking about `pyproject.toml`, which isn't setuptools-specific. There are more installation backends these days (flit, poetry).

**Comment by astrojuanlu** [comment]
See also #9473 and #9040.
