### ISSUE TITLE
RFE:  Allow use `setup.py sphinx_build -j N`

### ISSUE THREAD

**Issue by kloczek** [sphinx-doc/sphinx#9514]
Looks like at the movement when `python setup.py build_sphinx` is used documentation build is always done without parallelisation.
I think that by default it would be good to use by default `-j auto` and allow specify `setup.py sphinx_build -j N`.

This would allow greatly speedup building documentation over setuptools `build_sphinx` command.
In case of building `botocore` documentation it takes even on very powerful box up to 20 min. and with parallelisation it would be possible to shorten that time by few times.

**Comment by tk0miya** [comment]
+1 for adding a new option. It's reasonable. But, I think the default value should be the same as sphinx-build.

**Comment by tk0miya** [comment]
I'll take time for this issue until the 5.0 release. It would be nice if you try to improve this. Please check `sphinx/setup_command.py` :-)

**Comment by kloczek** [comment]
Reading sphinx documentation I've noticed that `sphinx-build` command can use $SPHINXOPTS env variable
From sphinx-build(1):
```man
       SPHINXOPTS
              Additional options for sphinx-build. These options can also be set via the shortcut variable O (capital 'o').
```
So I've modified my rpm macro which I'm using to build python modules man pages to:
```console
[tkloczko@barrel SPECS]$ rpm -E %py3_build_sphinx_man
\
        PBR_VERSION=%{version} \
        SETUPTOOLS_SCM_PRETEND_VERSION=%{version} \
        SPHINXOPTS="-j48" \
        /usr/bin/python3 setup.py build_sphinx -b man --build-dir build/sphinx
```
Today I've used that new macro to build first time `botocore` and `boto3` modules man pages however I think that this was not able shorten rpm packages time.
I must test that using raw `sphinx-build` command started with and without `-j48` to check is it any impact of the `-jN` param. If if will be no difference it will mean that parallelisation is not working.

I've been assuming that as boto3/botocore modules is produced from many source files sphinx parallelisation will start parsers of separated files in parallel (which could be useful and improve whole documentation build process).
Someone knows what exactly `-jN` should do?

**Comment by kloczek** [comment]
I made experiment with building rpm package with `-j1` and `-j48` injected into $SPHINXOPTS and looks like there is no difference:
```
-j1:
real    24m24.944s
user    22m48.218s
sys     0m34.586s

-j48:
real    24m27.666s
user    22m49.624s
sys     0m34.438s
```
So looks like at least passing `-jN` in that env variable does not work :(

**Comment by tk0miya** [comment]
>Reading sphinx documentation I've noticed that sphinx-build command can use $SPHINXOPTS env variable

Unfortunately, it's not an option of sphinx-build command. It's described as "Makefile Options". You can pass it via an option of Makefile (or make.bat).

**Comment by kloczek** [comment]
> Unfortunately, it's not an option of sphinx-build command. It's described as "Makefile Options". You can pass it via an option of Makefile (or make.bat).

So documentation is wrong? .. because that variable is mentioned in `sphinx-build(1)` man page
```man
NAME
       sphinx-build - Sphinx documentation generator tool

SYNOPSIS
       sphinx-build [options] <sourcedir> <outputdir> [filenames ...]
[..]
OPTIONS

       -j N   Distribute the build over N processes in parallel, to make building on multiprocessor machines more effective.  Note that  not  all  parts  and  not  all
              builders of Sphinx can be parallelized.  If auto argument is given, Sphinx uses the number of CPUs as N.

              New in version 1.2: This option should be considered experimental.

              Changed in version 1.7: Support auto argument.
[..]
ENVIRONMENT VARIABLES
[..]
       SPHINXOPTS
              Additional options for sphinx-build. These options can also be set via the shortcut variable O (capital 'o').

**Comment by tk0miya** [comment]
It's described in the subsection named "Makefile options". So I think it's not wrong.
```
ENVIRONMENT VARIABLES
       The sphinx-build refers following environment variables:

       MAKE   A path to make command.  A command name is also allowed.  sphinx-build uses it to invoke sub-build process on make-mode.

       Makefile Options

       The Makefile and make.bat files created by sphinx-quickstart usually run sphinx-build only with the -b and -d options.  However, they support the  following  vari-
       ables to customize behavior:

       PAPER  This sets the 'papersize' key of latex_elements: i.e. PAPER=a4 sets it to 'a4paper' and PAPER=letter to 'letterpaper'.

              NOTE:
                 Usage  of  this  environment variable got broken at Sphinx 1.5 as a4 or letter ended up as option to LaTeX document in place of the needed a4paper, resp.
                 letterpaper.  Fixed at 1.7.7.

       SPHINXBUILD
              The command to use instead of sphinx-build.

       BUILDDIR
              The build directory to use instead of the one chosen in sphinx-quickstart.

       SPHINXOPTS
              Additional options for sphinx-build. These options can also be set via the shortcut variable O (capital 'o').
```

**Comment by kloczek** [comment]
There are some number of large domumentations in some packages/projects in which some kind of parallelisation of processing input documents may be very usewfull allowing utilisation of the modern multi CPU cores HW arhitecture.

If such such thing may be in some future on the table I would suggest keep that RFE opened.

If internal design of the sphinx curently make such processing currently not possible even in mid range perspective I would not have anyting against to close that RFE.

Thx.

**Comment by tk0miya** [comment]
We determined to deprecate `build_sphinx` command and will remove it in 7.0. So it will not be improved more. So closing this now. Thank you for your proposal.
