### ISSUE TITLE
Failed to correctly document subclass or `property`.

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#952]
Consider the class:

```
#!python

class EventProperty(property):
    """ Used to declare events on the class ...  """

    def fire(self, *args, **kwargs):
        """ Fire the event.  """
        pass
```

and the associated rst file:

```
#!python

**************
pkg.autodocbug
**************

.. automodule:: pkg.autodocbug
   :members:
```

The resulting (HTML) documentation seems to think EventProperty is a function and does not document its members. Now, if I change the subclass of EventProperty as follows:

```
#!python

class EventProperty(object):
    """ Used to declare events on the class ...  """

    def fire(self, *args, **kwargs):
        """ Fire the event.  """
        pass
```

then the documentation is as expected.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/952
- Originally reported by: Anonymous
- Originally created at: 2012-06-22T14:24:21.742

**Comment by tk0miya** [comment]
At python2 era, `property` is a kind of `type` not `class.
```
$ python2.7
Python 2.7.16 (default, Mar 15 2019, 01:13:14)
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.10.44.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> property
<type 'property'>
```

But it becomes a kind of class in python3 era.
```
$ python3.5
Python 3.5.7 (default, Apr 21 2019, 22:35:13)
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.10.44.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> property
<class 'property'>
```

As a result, latest Sphinx (only for python3) can generate documents for subclass of property. So I'm closing this issue.
Thanks,
