### ISSUE TITLE
Support napoleon syntax for cvar

### ISSUE THREAD

**Issue by joernheissler** [sphinx-doc/sphinx#9531]
Hello,
I'd like to use napoleon syntax to document class variables.

So instead of:
```python
class Foo:
    """
    :cvar int CONST: Some constant
    """

Foo.CONST = func()
```

I'd prefer to write something like:
```python
class Foo:
    """
    Class Vars:  # or Class Variables
        CONST (int): Some constant
    """

Foo.CONST = func()
```

**Comment by astrojuanlu** [comment]
Hi @joernheissler , just to clarify: this is not "Napoleon syntax" - Napoleon translates the Google style guide https://google.github.io/styleguide/pyguide.html into proper reST for docstrings. I am not familiar with that guide, but if the syntax is not supported there, I don't think it is in scope for napoleon.

**Comment by joernheissler** [comment]
Thanks, @astrojuanlu!
That document describes only `Attributes:` which I must have missed before. It's supported by sphinx-napoleon, but generates quite different output compared to `cvar`.
