### ISSUE TITLE
C-language code-block lexing error with specific comment syntax "//@"

### ISSUE THREAD

**Issue by srikumarks** [sphinx-doc/sphinx#9548]
### Describe the bug

The following code block causes a C-language "lexing error" to be reported and highlighting skipped.

    .. code-block :: c

        int div(int x, int y)
        //@requires y >= 0;
        {
            return x / y;
        }

On the other hand, if I just remove the trailing semicolon on the comment line, the error goes away. i.e. the below version lexes fine.

    .. code-block :: c

        int div(int x, int y)
        //@requires y >= 0
        {
            return x / y;
        }

.. and the following lexes fine too -

    .. code-block :: c

        int div(int x, int y)
        // requires y >= 0;
        {
             return x / y;
        }

Since the line in question is a comment line, what characters feature within the comment line should not be of any consequence for lexing the block as "C".
    

### How to Reproduce

Include the example code blocks shown in any rat documentation processed by Sphinx.

### Expected behavior

All the indicated C-language code blocks should lex fine since the line in question is a comment line.

### Your project

not required as examples given in doc

### OS

MacOS

### Python version

3.8.8

### Sphinx version

4.0.1

### Sphinx extensions

none

### Extra tools

none

### Additional context

Tested using project created by sphinx-quickstart

**Comment by jakobandersen** [comment]
Thanks for reporting, though the lexing and highlighting is under the hood done with Pygments. It seems that running ``pygmentize -l c -F raiseonerror test.c`` emulates what Sphinx does, and for your first example I indeed get an error:
```
*** Error while highlighting:
pygments.filters.ErrorToken: @
   (file "/home/jla/.local/lib/python3.8/site-packages/pygments/filters/__init__.py", line 782, in filter)
*** If this is a bug you want to report, please rerun with -v.
int div(int x, int y)
```
I suggest opening an issue over at https://github.com/pygments/pygments.

**Comment by srikumarks** [comment]
Thank you @jakobandersen. Reposted here - https://github.com/pygments/pygments/issues/1891

**Comment by jakobandersen** [comment]
Great, I'll this here, but please reopen or make a new report if it turns out Sphinx needs to do something different.
