### ISSUE TITLE
Plotly plots are not shown on Sphinx 4

### ISSUE THREAD

**Issue by astrojuanlu** [sphinx-doc/sphinx#9563]
### Describe the bug

As demonstrated in https://sphinx-widgets-test.readthedocs.io/en/latest/Plotly%20plot.html, Plotly plots are not shown in Sphinx 4, and a bunch of JavaScript errors appear on the console:

![js-errors](https://user-images.githubusercontent.com/316517/130047092-692f258d-1cfe-43a6-aa5a-40603348c890.png)

However, if I switch to Sphinx 3, as in https://sphinx-widgets-test.readthedocs.io/en/sphinx-3/Plotly%20plot.html, the plots are shown normally and no JS errors can be seen:

![Screenshot 2021-08-19 at 11-46-49 Plotly plot — Sphinx Widgets Test 0 1 documentation](https://user-images.githubusercontent.com/316517/130047551-10ca3269-efdd-46ba-972c-5bef6758a81b.png)

This is with Alabaster, but in https://github.com/poliastro/poliastro/pull/1308 I was using `sphinx_rtd_theme`, with identical result.

I am not sure where the bug is, since there are several systems interacting here (sphinx, nbsphinx, plotly). But I hope it serves as a good starting point for debugging.

### How to Reproduce

Bad:

```
$ git clone https://github.com/astrojuanlu/sphinx-widgets-test
$ cd sphinx-widgets-test
$ pip install -r requirements.txt
$ cd docs
$ make html
$ # open _build/html/index and see the error
```

Good:

```
$ cd sphinx-widgets-test
$ git switch sphinx-3
$ cd docs
$ rm -rf _build
$ make html
$ # open _build/html/index and see that the plot displays correctly
```

### Expected behavior

The plots show normally.

### Your project

https://github.com/astrojuanlu/sphinx-widgets-test

### OS

Linux Mint

### Python version

3.9

### Sphinx version

Sphinx 3.5.4 (good) and 4.1.2 (bad)

### Sphinx extensions

nbsphinx

**Comment by astrojuanlu** [comment]
cc @nicolaskruchten @mgeier

**Comment by nicolaskruchten** [comment]
That MIME-type error suggests that there is a misconfiguration in your HTTP server such that the Plotly.js file cannot be interpreted as Javascript, at first read.

**Comment by astrojuanlu** [comment]
To clarify, this happens both locally with `python -m http.server` as well as online as served by Read the Docs.

**Comment by nicolaskruchten** [comment]
I see a different error here: https://sphinx-widgets-test.readthedocs.io/en/latest/Plotly%20plot.html ... do you have a Plotly-compatible version of MathJax installed? Plotly is compatible with MathJax 2.7.9 but not 3.x.

**Comment by astrojuanlu** [comment]
Indeed, https://sphinx-widgets-test.readthedocs.io/en/latest/Plotly%20plot.html loads MathJax 3. I tested changing the Sphinx configuration to MathJax 2 in https://sphinx-widgets-test.readthedocs.io/en/mathjax-2-sphinx-4/Plotly%20plot.html and looks like now the plot loads. Thanks @nicolaskruchten, I guess there is nothing else to do here.

**Comment by mgeier** [comment]
See also https://github.com/spatialaudio/nbsphinx/issues/572#issuecomment-853389268 and https://github.com/plotly/plotly.py/issues/3152#issuecomment-855432931.

**Comment by astrojuanlu** [comment]
That solution works, thanks to both. Closing!
