### ISSUE TITLE
Something broke with C++ templates/namespaces between 4.0.3 and 4.1.2

### ISSUE THREAD

**Issue by cary-ilm** [sphinx-doc/sphinx#9584]
### Describe the bug

I have a C++ class template inside a namespace and all was good with Sphinx 4.0.3, but it fails with 4.1.2, but only when invoked by readthedocs. Error is:

```
  File "/home/docs/checkouts/readthedocs.org/user_builds/cary-ilm-docs-test/envs/latest/lib/python3.7/site-packages/sphinx/util/cfamily.py", line 275, in fail
    raise self._make_multi_error(errors, '')
sphinx.util.cfamily.DefinitionError: Invalid C++ declaration: Expected identifier in nested name. [error at 5]
  class
  -----^

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/cary-ilm-docs-test/envs/latest/lib/python3.7/site-packages/sphinx/util/cfamily.py", line 275, in fail
    raise self._make_multi_error(errors, '')
sphinx.util.cfamily.DefinitionError: Invalid C++ declaration: Expected identifier in nested name. [error at 5]
  class
  -----^
```
The template is:

```
template <class T> class Vec
{
  public:
    constexpr Vec (const Vec& v) noexcept;
    template <class S>  constexpr Vec (const Vec<S>& v) noexcept;
};

template <class T>
constexpr inline Vec<T>::Vec (const Vec& v) noexcept
{
}

template <class T> template <class S>
constexpr inline Vec<T>::Vec (const Vec<S>& v) noexcept
{
}

}
```

This is referenced in index.rst via:

```
.. doxygenclass:: Test::Vec
   :undoc-members:
   :members:

```

It seems to be triggered by a combination of the template and the namespace. Removing the namespace makes the error go away. The error also only seems to happen with both constructors are included.

If I revert the sphinx version to 4.0.3, no error.

Full log for the failed 4.1.2 build: https://readthedocs.org/api/v2/build/14568472.txt
Log for the successful 4.0.3 build: https://readthedocs.org/api/v2/build/14568456.txt

The only difference between the two builds is the line in requirements.txt that specifies the sphinx version.

### How to Reproduce

Here is a simple pared-down repo that illustrates the problem: https://github.com/cary-ilm/docs-test
The readthedocs project is: https://readthedocs.org/projects/cary-ilm-docs-test/

The project specifies the sphinx version in docs/requirements.txt. 4.0.3 works fine, 4.1.2 fails.

Running sphinx 4.1.2 locally works fine, it only fails when invoked via readthedocs.

### Your project

 https://github.com/cary-ilm/docs-test

### OS

ubuntu 20, but the problem is on readthedocs.

### Python version

3.7

### Sphinx version

4.1.2

### Sphinx extensions

breathe

**Comment by jakobandersen** [comment]
Thanks for reporting. I'm quite sure this is a duplicate of #9449, #9433, #9460, and #9477 though, but otherwise please reopen or post a new issue.
The problem is in Breathe and I think it should be fixed by michaeljones/breathe#711. Using that branch locally, your example compiles locally for me.
