### ISSUE TITLE
.qhcp file does not include <applicationIcon>

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#959]
It'd be nice if the html-favicon set in conf.py is used as the application icon in the qhcp file as well.

It's just a simple xml node inside the assistant tag to refer to the icon (which also must be copied into the qthlelp directory, so that it's picked up by the qcollectiongenerator.)

```
<assistant>
     <title>...</title>
     ...
     <applicationIcon>myicon.ico</applicationIcon>
</assistant>
```

The workaround is to write the file myself, which works for one or two projects, but now I have to create a whole slew of documents using sphinx, and there's a lot of dupliacate info that goes into both conf.py and the qhcp-file. (Maintaining that manually is not pleasant.)

Love Sphinx though! Keep it up! :)

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/959
- Originally reported by: Marcus Lindblom Sonestedt
- Originally created at: 2012-07-04T12:14:39.649

**Comment by AA-Turner** [comment]
Issue should be reported against `sphinxcontrib/qthelp`.

A
