### ISSUE TITLE
Give 'document isn't included in any toctree' warning a type and subtype so it can be suppressed

### ISSUE THREAD

**Issue by hocjordan** [sphinx-doc/sphinx#9596]
**Is your feature request related to a problem? Please describe.**
I would like to be able to generate multiple overlapping documents from a shared set of source `rst` files. My problem is that generating a document using only a partial set of the source files triggers a warning: 'document isn't included in any toctree'. Our CI treats warnings as errors and so crashes. 

**Describe the solution you'd like**
I would like to use the `suppress_warnings` option in `conf.py` to suppress the 'document isn't included' warning. This seems to require passing a `type` and `subtype` argument to `logger.warning` (https://github.com/sphinx-doc/sphinx/blob/abe5ab4fa7aa4af4de8a65de1b51241852324591/sphinx/environment/__init__.py#L632-L633) so that it can be added to `suppress_warnings`. Would this work? And would a PR providing this functionality be acceptable if I produced it?

**Describe alternatives you've considered**
The alternative solution is to use the `exclude_patterns` option in `conf.py`. This seems to work but is not optimal because we have to exclude every file that is not being used, for every document we want to produce, and we have to keep those lists up to date.

**Additional context**
Warning suppression derives from: https://github.com/sphinx-doc/sphinx/pull/2346

A similar PR for a different warning was produced here: https://github.com/sphinx-doc/sphinx/pull/7851/files, although that PR was not merged because the user wanted to suppress warnings that indicated serious problems with their code. I think that suppressing 'document not included' should be much safer.

**Comment by tk0miya** [comment]
How about marking the "shared" document as orphaned? (refs: https://www.sphinx-doc.org/en/master/usage/restructuredtext/field-lists.html)
Then, they will not be warned.

**Comment by hocjordan** [comment]
Thanks for the advice. I'll give it a go and report back.

**Comment by JasperCraeghs** [comment]
Instead of configuring your CI to treat all warnings as errors, you could use [`mlx.warnings`](https://melexis.github.io/warnings-plugin/readme.html) (a script that I maintain) to [exclude specific Sphinx warnings](https://melexis.github.io/warnings-plugin/readme.html#exclude-matches-with-regexes) and even [configure](https://melexis.github.io/warnings-plugin/readme.html#parse-for-sphinx-warnings) a minimum and/or maximum limit of warnings that are allowed.

**Comment by picnixz** [comment]
Closing since using `:orphan:` should be the way to do it (but maybe we can come back later when doing https://github.com/sphinx-doc/sphinx/pull/11677)
