### ISSUE TITLE
The number is superimposed on its title in generated PDF

### ISSUE THREAD

**Issue by xvitaly** [sphinx-doc/sphinx#9597]
### Describe the bug

The number is superimposed on its title in generated PDF.

Appears if the section number field exceeds 4 characters.

### How to Reproduce

```
$ git clone https://github.com/RussianFedora/FAQ.git faq
$ cd faq
$ make latexpdf
```

### Your project

https://github.com/RussianFedora/FAQ

### Screenshots

![image](https://user-images.githubusercontent.com/966711/131644179-1f7ac50a-6ca8-4145-8a8d-fe51fb046bb6.png)

### OS

Linux

### Python version

3.9.1

### Sphinx version

4.1.2

**Comment by tk0miya** [comment]
Please configure `\l@section` setting via preamble.
```
latex_elements = {
    'preamble': r'''
\makeatletter
\renewcommand{\sphinxtableofcontentshook}{%
  % widen the space after the section number to 3.6em (original: 2.6em)
  \renewcommand*\l@section{\@dottedtocline{1}{1.5em}{3.6em}}%
  % widen the space after the subsection number to 4.5em (original: 3.5em)
  \renewcommand*\l@subsection{\@dottedtocline{2}{4.1em}{4.5em}}%
}
\makeatother
'''
}
```

**Comment by xvitaly** [comment]
> Please configure \l@section setting via preamble.

Looks better now. Thanks.

4+ letters. New:

![image](https://user-images.githubusercontent.com/966711/132091469-2b782c69-bb06-47d7-811e-054c04450f6c.png)

4- letters. Old:

![image](https://user-images.githubusercontent.com/966711/132091512-c12e95b4-3a79-4dc2-bcca-3a0eeaa56178.png)

4- letters. New:

![image](https://user-images.githubusercontent.com/966711/132091537-730af531-963c-4db6-94cc-db6cbcdb80a2.png)
