### ISSUE TITLE
Link sidebarlogo to custom URL

### ISSUE THREAD

**Issue by bsipocz** [sphinx-doc/sphinx#9601]
This is a duplicate of #2018, as the PR https://github.com/sphinx-doc/sphinx/pull/8737 added a different feature (comments are closed for both of those, thus I open a new issue) 

If PRs are welcome to address the original, I'm happy to open one to add an e.g. `logo_link_url` config option for at least the basic layout.

**Comment by tk0miya** [comment]
I think you can modify it via your own custom template. -0 for adding a new option.

**Comment by picnixz** [comment]
Closing in favor of using a custom template since adding a new option means implementing it for all native themes.
