### ISSUE TITLE
`linkcheck` gives `Anchor 'xxx' not found`  when the link works

### ISSUE THREAD

**Issue by dukecat0** [sphinx-doc/sphinx#9603]
### Describe the bug

I have few links here:

- https://github.com/linkedin/shiv#shiv
- https://github.com/pantsbuild/pex#pex

Both of them work fine. However, `linkcheck` gives errors about them:
```
overview.rst:253: [broken] https://github.com/linkedin/shiv#shiv: Anchor 'shiv' not found
overview.rst:251: [broken] https://github.com/pantsbuild/pex#pex: Anchor 'pex' not found
```

### How to Reproduce

```bash
$ git clone https://github.com/pypa/packaging.python.org.git
$ cd packaging.python.org
$ python -m pip install --user nox
$ nox -s linkcheck
```
And then check the output in `build/output.txt`.

You should be able to see something like this:
```
overview.rst:253: [broken] https://github.com/linkedin/shiv#shiv: Anchor 'shiv' not found
overview.rst:251: [broken] https://github.com/pantsbuild/pex#pex: Anchor 'pex' not found
```

### Expected behavior

There shouldn't have any errors about these two links.

### Your project

https://github.com/pypa/packaging.python.org

### OS

macOS Big Sur 11.4

### Python version

3.9.2

### Sphinx version

4.1.2

**Comment by francoisfreitag** [comment]
Looks like a duplicate of https://github.com/sphinx-doc/sphinx/issues/9016?

**Comment by dukecat0** [comment]
Yes, they are the same issue.
