### ISSUE TITLE
Python 3.10 support

### ISSUE THREAD

**Issue by jab** [sphinx-doc/sphinx#9604]
### Describe the bug

I just hit https://github.com/sphinx-doc/sphinx/issues/9512 while testing my project in CI with the latest release of Sphinx (4.1.2) and the latest release of Python 3.10 (currently 3.10.0-rc1). (Thanks for fixing this [already](https://github.com/sphinx-doc/sphinx/pull/9513)!)

This prompted me to check whether Sphinx itself is testing against the latest release of Python 3.10 in CI, and it looks like Sphinx is currently only [testing against 3.10-dev](https://github.com/sphinx-doc/sphinx/blob/6c38f68dae221e8cfc70c137974b8b88bd3baaab/.github/workflows/main.yml#L26-L27). This in turn prompted me to look for an existing, high-level "Python 3.10 support" issue, which users could subscribe to in order to track Sphinx's Python 3.10 compatibility. Since I didn't find such an issue, I'm creating this one in case it's helpful.

### How to Reproduce

.

### Your project

https://github.com/jab/bidict

### OS

all

### Python version

3.10

### Sphinx version

4.1.2

**Comment by tk0miya** [comment]
Thank you for reporting. It was already reported as #9562. As you mentioned, problems have already been fixed in the HEAD of Sphinx. So please wait for the next release. If you'd like to try to use the fixed version, please install it from github directly.

Thanks,
