### ISSUE TITLE
Support for fuzzy translations

### ISSUE THREAD

**Issue by topogps** [sphinx-doc/sphinx#9618]
Problem
---------
Entries in po files that are currently marked as "fuzzy" are not used in "mo" files. The original source language is used instead of the translated language. Fuzzy translations are translations that in general need to be reviewed by a translator. For example all machine translations could be marked as fuzzy. It would be desirable to let the user decide whether to include these fuzzy translations in the generated documentation.

Proposed solution
------------------
Add a new configuration parameter "use_fuzzy_translations".

Change in line 72 of the file sphinx/sphinx/util/i18n.py 

   write_mo(file_mo, po)

to 
               
   write_mo(file_mo, po, use_fuzzy_translations)

Writing mo files with fuzzy translations is supported by the babel package, as can be seen in the documentation:

http://babel.pocoo.org/en/latest/api/messages/mofile.html

**Comment by tk0miya** [comment]
+1: Reasonable. I prefer to name it as `gettext_allow_fuzzy_translations` for the setting because we've given "gettext_" prefix to the i18n settings so far.
https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-internationalization
