### ISSUE TITLE
Incremental build not possible if func is assigned to a config-var

### ISSUE THREAD

**Issue by danwos** [sphinx-doc/sphinx#9622]
### Describe the bug

Sphinx always rewrites all files, if a function is assigned to a config-variable in ``conf.py``.
Other objects types like string, int, class or even modules do not trigger this behavior.

### How to Reproduce

Create a test project via ``sphinx-quickstart``.
Set the below code in ``conf.py``.

```python
# conf.py

def setup(app):
    app.add_config_value("test_option", None, "html")

import os  # used to represent a module assignment

def test_func():
    pass

class test_class:
    def __init__(self):
        pass

    def test_me(self):
        pass

# Use only one example of the below in a test

test_option = test_func()  # all good. func gets executed and return value is assigned
test_option = test_func  # no incremental build. func itself gets assigned

test_option = "string"  # all good
test_option = test_class  # all good
test_option = test_class() # no incremental build

test_ option = os  # all_good
test_option = os.path.isdir  # no incremental build

# Same results for embedded functions
test_option = {'test': {'test': [test_func,]}}  # no incremental build
test_option = {'test': {'test': ["string",]}}   # all good  
```

Build the project twice.
Check the second build output for "Writing output ..." lines

### Expected behavior

Incremental build is always happening, not matter what kind of object-type a registered sphinx-variable in ``conf.py`` is getting as value.

### Your project

https://github.com/useblocks/sphinxcontrib-needs/issues/343#issuecomment-915927604

### OS

linux

### Python version

3.8

### Sphinx version

3.5.4, 4.1.2

**Update**: Added func in nested dicts as example. Also added dummy func to class.

**Comment by danwos** [comment]
I make some further testing to figure out, in which event/phase the error may be.

```python
# conf.py

def test_func():
    pass

def change_test_option(app, *args, **kwargs):
   """Change the "empty" test_option to the problematic function """
    app.config.test_option = test_func


def print_test_option(app, *args, **kwargs):
    """Not really needed. Just to make sure that config change really happened"""
    from sphinx.util import logging
    log = logging.getLogger(__name__)
    log.info(f'\n\n--> test_option = {app.config.test_option}')


def setup(app):
    app.add_config_value("test_option", None, "html")
    # app.connect("env-purge-doc", change_test_option)  # Seems not to be fired in my tests
    app.connect("config-inited", change_test_option)  # No incremental build
    # app.connect("env-before-read-docs", change_test_option)  # all good
    # app.connect("doctree-resolved", change_test_option)  # all good
    app.connect("build-finished", print_test_option)  # Just prints the test_option value
```
So the problematic code gets executed during the "config-inited" phase.
Changes of ``test_option`` in phases after this event are not problematic and the incremental build works.

**Comment by mgeier** [comment]
This is known behavior, but it is probably not documented. I've stumbled upon this as well in the past.

It is mentioned in a comment here: https://github.com/sphinx-doc/sphinx/issues/7093#issuecomment-581484955.

I've asked a related question at the mailing list: https://groups.google.com/g/sphinx-dev/c/aGfJb-TC8PI/m/zxM3l9kAAgAJ

And I've changed an extension of mine to be able to avoid the problem: https://github.com/spatialaudio/nbsphinx/pull/408

**Comment by danwos** [comment]
Thanks a lot for the detailed links.
I also came to the conclusion that this behaviour is maybe a design decision, as functions may change between builds and sphinx can not detect this.

The suggested solution in your links (provide an API and let the user use it in setup.py) may be a solution.
Another one would be to get a string, which defines the importable location of a function and then import the function during runtime(not tested).

I think there is no way to handle function assignment by sphinx in a safe way. So I close this issue and try to solve it in my extension.

Thanks for the help.
