### ISSUE TITLE
``:dedent: 0`` not respected and :dedent: without argument seems broken

### ISSUE THREAD

**Issue by ghost** [sphinx-doc/sphinx#9636]
### Describe the bug

# `:dedent: 0` not respected

The `.. code-block::` (and probably related directives, too) does not respect the ``:dedent: 0`` option.
Instead of doing nothing, it does the same as ``:dedent:`` (without argument).
I believe ``:dedent: 0`` should be a noop to be in line with the expectation of dedenting by 0 characters.

Use case:

```
First part

.. code-block::

   class PythonClass:

Second part

.. code-block::
   :dedent: 0

       def __init__():
           pass

third part
```
Without the :dedent: the code block would (by I think the ReST parser, not the renderer) be read with ONE 7 space indent (instead of ONE 3 space indent and a 4 space indent inside the code block). Thus, messing up the code layout.  The :dedent: 0 would help in such cases as it indicates ONE 3 space indent for the directive.
As a workaround `:class: dummy` can also be used, however, this pollutes the class attribute of the node.

## Proposed solution:

Instead of `if not dedent:` use `if dedent is None:` in sphinx/directives/code.py line 60

# :dedent: (without argument)

Also, I noticed that :dedent: (without any argument) seemingly produces garbage, namely it removes all newlines and only the indent of the first line, producing a single long line.

## Proposed solution

The reason seems to be that the function dedent_lines() (sphinx/directives/code.py line 59) uses
```
        return textwrap.dedent(''.join(lines)).splitlines(True)
```
instead of the line preserving
```
        return textwrap.dedent('\n'.join(lines)).split('\n')
```

# Closing words

If the above analysis is correct and you agree with the proposed solutions, I'm happy to provide a PR if that reduces the workload for you.

### How to Reproduce

MWE is given above in the use case.

### Your project

Sorry that's a private one, the MWE above should do.

### OS

Linux

### Python version

3.9

### Sphinx version

4

**Comment by tk0miya** [comment]
I don't think this is a bug because your goal is not "dedenting" the content by 0. I think you'd like to use the `:dedent: 0` option as a workaround to keep indentation, right? To fix this properly, we need to add a new syntax or parsing rules to reStructuredText.

But, at this moment, supporting 0 value is a good workaround for your case. And it is low cost to implement it and it does not harm anybody. So I can agree to add the change as a "secret" feature.

>If the above analysis is correct and you agree with the proposed solutions, I'm happy to provide a PR if that reduces the workload for you.

It must be help us. Could you make a PR?

**Comment by ghost** [comment]
> I don't think this is a bug because your goal is not "dedenting" the content by 0.

I agree that I use the feature in a hacky way, however, – nitpick – I don't agree that it is not a bug as the implementation does not follow the documentation, which states:

>   When number given, leading N characters are removed.

and (to me) N = 0 is a perfectly fine number.  But lets not talk about distinctions without difference and instead focus on a more important issue:

Could you have a look at the second part of this report: ``:dedent:`` without argument.  I noticed I did not provide a MWE as it is so obvious:

```rst
.. code-block::
   :dedent:

   first line
   second line
```

The above produces ``first linesecond line`` as output (no newline between the lines), which, I guess, is not intended.
As suggested in the initial report: I propose to change line 59 in sphinx/directives/code.py line 59 from

        return textwrap.dedent(''.join(lines)).splitlines(True)

to the newline preserving:

        return textwrap.dedent('\n'.join(lines)).split('\n')

**Comment by tk0miya** [comment]
>Could you have a look at the second part of this report: :dedent: without argument. I noticed I did not provide a MWE as it is so obvious:

Oops... it must be a bug!
