### ISSUE TITLE
`sphinx.builder.Builder.allow_parallel` not part of public Builder API

### ISSUE THREAD

**Issue by ghost** [sphinx-doc/sphinx#9637]
### Describe the bug

I noticed that `sphinx.builder.Builder.allow_parallel` is not part of the public Builder API – or at least it's not documented as such [2]

Thus, a custom Builder thus cannot provide parallel writes (at least not via the public API).  This seems like an oversight to me. I'd suggest making `allow_parallel` part of the official Builder API. The docstring is already present, so changing `#` to `#:` should do the trick.

[2] https://www.sphinx-doc.org/en/master/extdev/builderapi.html#sphinx.builders.Builder

### How to Reproduce

N/A

### Your project

N/A

### OS

N/A

### Python version

N/A

### Sphinx version

4

**Comment by tk0miya** [comment]
Indeed, this must be a bug. Thanks!
