### ISSUE TITLE
There's no obvious way to update pdfminorversion

### ISSUE THREAD

**Issue by oharboe** [sphinx-doc/sphinx#9645]
pdf files newer than 1.5 are now floating around. It would be good to support them.

Modifying the pre-amble is too late.

```
latex_elements = {
    'preamble':
    "\\pdfoptionpdfminorversion=7\n" 
...
```

Error:

```
! pdfTeX error (setup): \pdfminorversion cannot be changed after data is writte
n to the PDF file.
\Hy@OutlineName ...utline goto name{#2}count#3{#4}
                                                  
l.1 ...\000o\000o\000l\000c\000h\000a\000i\000n}{}
                                                  % 1
!  ==> Fatal error occurred, no output PDF file produced!
```

**Comment by tk0miya** [comment]
It seems the macro should be called on the earlier step. How about using `passoptionstopackages` key instead of `preamble`?
https://github.com/sphinx-doc/sphinx/blob/4.x/sphinx/templates/latex/latex.tex_t#L29

**Comment by oharboe** [comment]
That worked!

Thanks!
