### ISSUE TITLE
Do you plan on releasing 4.1.3?

### ISSUE THREAD

**Issue by befeleme** [sphinx-doc/sphinx#9646]
Hello, 

Do you plan to release an official 4.1.3 (seeing there is an existing milestone and all the tasks there are done/closed)? What's the planned date?

**Is your feature request related to a problem? Please describe.**
In Fedora 35 we've landed Sphinx 4.1.2, it will also bring Python 3.10 as main interpreter. It's important for us to have the working fine-tuned Sphinx version there. It would be handy to package the official 4.1.3 which fully supports Python 3.10.

**Comment by tk0miya** [comment]
Unfortunately, 4.1.3 will not be released. Please upgrade to 4.2.x. Thanks,
