### ISSUE TITLE
Sphinx autodoc gives WARNING: py:class reference target not found: type warning

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#965]
I am using sphinx with autodocs for documentation. But it appears that autodocs can't resolve the class `type`. This means that whenever I create a metaclass (which needs to extend `type`) I will not be able to rebuild my sphinx documentation properly.

For more information and an example see: http://stackoverflow.com/questions/11417221/sphinx-autodoc-gives-warning-pyclass-reference-target-not-found-type-warning

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/965
- Originally reported by: Anonymous
- Originally created at: 2012-07-10T22:35:41.872

**Comment by AA-Turner** [comment]
Cannot reproduce on Sphinx 4.5 with

```python
class MetaClass(type):
    pass

class MyClass(metaclass=MetaClass):
    pass
```

```rest
Example Module
==============

.. autoclass:: example_module.MyClass
   :members:
   :show-inheritance:
```

A
