### ISSUE TITLE
python bases in packages - follow up on #4944

### ISSUE THREAD

**Issue by Bibo-Joshi** [sphinx-doc/sphinx#9664]
**Is your feature request related to a problem? Please describe.**
Same problem as described in #4944

**Describe the solution you'd like**
sphinx checks if the base class is documented somewhere. If yes, it inserts the reference to the corresponding page automatically.

**Describe alternatives you've considered**
As originally proposed in #3104, allow `autodoc-process-signature` to return a list of strings that will be appended to `Bases: `

**Additional context**
#4944 was marked as closed by #9233, but that PR unfortunately doesn't solve the problem: While I now can return a different base class, I still can't control the text of the hyperlink for that class.
With `autodoc-process-signature` being allowed to return strings, one could just return something like ``':class:`telegram.TelegramObject`'``

PS: maybe we can just reopen #4944 and continue discussion there …

**Comment by tk0miya** [comment]
I posted #9665. Could you check it please?
