### ISSUE TITLE
New install Python 3.9.7 install of Sphinx Document Generator fails

### ISSUE THREAD

**Issue by pbroe** [sphinx-doc/sphinx#9669]
### Describe the bug

Brand new build of Python 3.9.7 on RHEL 7.  Placed in /usr/local/python3

Created new python environment

cd /usr/opt/oracle/
 python3 -m venv py3-sphinx
source /usr/opt/oracle/py3-sphinx/bin/activate
Now verify that python is now linked to Python 3.
In this virtual environment python is a link to python3
python -V
Python 3.9.7

I installed all the pre-requisites correctly for Sphinx 4.2.0
See the output of the command in the attached file
command:
pip install -vvv --no-index --find-link=/usr/opt/oracle/downloads/python-addons sphinx

[Sphinx install output.txt](https://github.com/sphinx-doc/sphinx/files/7220720/Sphinx.install.output.txt)

### How to Reproduce

Setting up a virtual environment for Python3
Most people use Virtual Environments because it’s a recommended practice when working in Python to ensure a known starting point or state. 

First create a Python 3 virtual environment using the venv module included with Python 3.
As user oracle, run
cd /usr/opt/oracle/
 python3 -m venv py3-sphinx
source /usr/opt/oracle/py3-sphinx/bin/activate
Now verify that python is now linked to Python 3.
In this virtual environment python --> python3
python -V
Python 3.9.7
Install Sphinx in the Virtual Environment
With the virtual environment activated, install Sphinx.

pip install -vvv --no-index --find-link=/usr/opt/oracle/downloads/python-addons sphinx

Requirement already satisfied: setuptools in /usr/opt/oracle/py3-sphinx/lib/python3.9/site-packages (from sphinx) (58.0.4)
0 location(s) to search for versions of packaging:
Skipping link: Missing project version for packaging: file:///usr/opt/oracle/downloads/python-addons/Sphinx-4.2.0.tar.gz
Given no hashes to check 0 links for project 'packaging': discarding no candidates
ERROR: Could not find a version that satisfies the requirement packaging (from sphinx) (from versions: none)
ERROR: No matching distribution found for packaging
Exception information:

### Expected behavior

It should install Sphinx in my virtual Python environment.

### Your project

attached py3-sphinx_venv.tar.gz 

### OS

Linux RHEL 7

### Python version

3.9.7

### Sphinx version

4.2.0

### Sphinx extensions

N/A

### Extra tools

N/A

### Additional context

Brand new install of Python.   I need to have Sphinx to build GCC 11.

**Comment by pbroe** [comment]
Attaching my virtual environment for python.
[py3-sphinx_venv.tar.gz](https://github.com/sphinx-doc/sphinx/files/7220755/py3-sphinx_venv.tar.gz)

**Comment by tk0miya** [comment]
> ERROR: Could not find a version that satisfies the requirement packaging (from sphinx) (from versions: none)

Have you installed the packaging package?
https://pypi.org/project/packaging/

**Comment by pbroe** [comment]
Thank you so much.    That was it.   I thought it was looking for a package but I completely missed the fact that the package name was package.    I can't connect to the internet from my machines.  So, I have to download everything manually from PyPI.  

I added packages pyparsing and packaging ...
And

Building wheels for collected packages: sphinx
  Building wheel for sphinx (setup.py) ... done
  Created wheel for sphinx: filename=Sphinx-4.2.0-py3-none-any.whl size=3061858 sha256=c5b28f87749557dc8c06b9820c748d6c5e764e32f2f25620d08b3259993ea90a
  Stored in directory: /usr/opt/oracle/.cache/pip/wheels/31/d2/bc/aa1cbddf1cd38373f4632ab20b0e3400f037bcf271b50b2397
Successfully built sphinx
Installing collected packages: sphinx
Successfully installed sphinx-4.2.0
