### ISSUE TITLE
SVG inheritance diagram is not hyperlinked (clickable)

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#967]
PNG inheritance diagrams can be clicked on, while the SVG variant is not clickable. 

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/967
- Originally reported by: [eudoxos](https://bitbucket.org/eudoxos)
- Originally created at: 2012-07-14T08:48:02.161

**Comment by tk0miya** [comment]
Fixed at e859543.
