### ISSUE TITLE
Show some imported names in autodoc' modules

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#968]
It is a common practice in python projects to import compiled functions into python extension module such that it is transparent for the user. For instance,

```
_ham.so (compiled python module)
     # defines foo()
ham.py (contains also "from _ham import *")
     # defines bar()
```

Autodoc currently filters out any objects, of which **module** does not match the one being documented. A parameter (like ":internal-modules: _ham") should also include objects in internal modules:

```
.. :automodule:: ham
     :internal-modules: _ham    # possibly more
     :internal-modules-rewrite: # change _ham to ham in listing
```

would document

```
ham.foo # would be "_ham.foo" without :internal-modules-rewrite:
ham.bar
```

I can try to patch sphinx, but please give me some feedback before I do so.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/968
- Originally reported by: [eudoxos](https://bitbucket.org/eudoxos)
- Originally created at: 2012-07-14T08:59:20.295

**Comment by Zac-HD** [comment]
The proper way to do this is either to set `__all__ = ['foo', 'bar']` in the Python module (to declare which names are public API), or to explicitly list the members for autodoc (e.g. `:members: foo, bar`).

This issues should therefore be closed as redundant, or conflicting with existing standards.

**Comment by tk0miya** [comment]
+1 for @Zac-HD . Using `__all__` in python or `:imported-members:` is better for this case. I agreed the replacement feature is not needed for this case.

@shimizukawa any comments? If none, I'll close this soon.

**Comment by shimizukawa** [comment]
+1 to closing this issue. Thanks.
