### ISSUE TITLE
connect() keyword 'priority' missing during compilation of Jupyter-Book

### ISSUE THREAD

**Issue by leighfletcher** [sphinx-doc/sphinx#9681]
### Describe the bug

Hello,

I consider myself a Python beginner, but a google-search did not help me resolve this one. In compiling a Jupyter book using sphinx as `jupyter-book build book/`, I'm seeing the exception below, and the compilation ceases.  I'm not sure how to begin debugging this, and would welcome ideas.

I have tried to roll back Sphinx by editing book/requirements.txt to point at Sphinx==2.1.0, but it seemed to default to 2.2.0 no matter what I tried.  I expected that a fresh Sphinx installation would bring me a newer version (v4*), but it always seemed to stick with v2.2.0.

I have been using jupyter-book for several months on a different machine, but having moved to a new machine, this is the first time this exception has occurred (installation via pip on 2021-09-08). Both run Python 3.7.4, but the only difference seems to be that the new machine is on OSX Big Sur, whereas the old one is OSX Catalina.

Thank you!

Running Sphinx v2.2.0

Exception occurred:
File "/opt/anaconda3/lib/python3.7/site-packages/sphinx_external_toc/init.py", line 29, in setup
app.connect("config-inited", parse_toc_to_env, priority=900)
TypeError: connect() got an unexpected keyword argument 'priority'
The full traceback has been saved in /var/folders/cs/qnn7xrcs7xq3gjn8_81vgqnr00045m/T/sphinx-err-kbzib9p_.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at https://github.com/sphinx-doc/sphinx/issues. Thanks!
Traceback (most recent call last):
File "/opt/anaconda3/lib/python3.7/site-packages/jupyter_book/sphinx.py", line 128, in build_sphinx
keep_going=keep_going,
File "/opt/anaconda3/lib/python3.7/site-packages/sphinx/application.py", line 236, in init
self.setup_extension(extension)
File "/opt/anaconda3/lib/python3.7/site-packages/sphinx/application.py", line 395, in setup_extension
self.registry.load_extension(self, extname)
File "/opt/anaconda3/lib/python3.7/site-packages/sphinx/registry.py", line 487, in load_extension
metadata = setup(app)
File "/opt/anaconda3/lib/python3.7/site-packages/sphinx_external_toc/init.py", line 29, in setup
app.connect("config-inited", parse_toc_to_env, priority=900)
TypeError: connect() got an unexpected keyword argument 'priority'

### How to Reproduce

jupyter-book build book/

Versions of my packages:
Jupyter Book : 0.11.3
External ToC : 0.2.3
MyST-Parser : 0.13.7
MyST-NB : 0.12.3
Sphinx Book Theme : 0.1.3
Jupyter-Cache : 0.4.3
NbClient : 0.5.4

### Expected behavior

On a machine running Sphinx v4.1.2 (Mac Catalina) I get a successfully compiled Jupyter Book.  

### Your project

Unavailable

### OS

OSX Big Sur

### Python version

3.7.4

### Sphinx version

2.2.0

### Additional context

This same query was submitted here, but currently with no suggestions:
https://github.com/executablebooks/jupyter-book/issues/1456

On the working machine, I just checked the version of my installed packages, in case this provides helpful diagnostics:

```
jupyter-book --version

Jupyter Book      : 0.11.2

External ToC      : 0.2.3

MyST-Parser       : 0.13.5

MyST-NB           : 0.12.0

Sphinx Book Theme : 0.1.1

Jupyter-Cache     : 0.4.2

NbClient          : 0.5.3
```

**Comment by tk0miya** [comment]
The priority of event handlers was introduced since Sphinx 3.0. So please upgrade your Sphinx to the newer one, or downgrade to jupyter-book to the older one.

**Comment by leighfletcher** [comment]
> The priority of event handlers was introduced since Sphinx 3.0. So please upgrade your Sphinx to the newer one, or downgrade to jupyter-book to the older one.

Thanks so much, tk0miya!  I attempted to update sphinx using the instructions here:  https://www.sphinx-doc.org/en/master/usage/installation.html

However, for reasons I don't understand, the most recent I ever got was v2.2.0.  Is there any reason why it should be held back on OSX Big Sur?  Do you have a recommendation for doing a Sphinx update (I tried via conda and brew).

**Comment by tk0miya** [comment]
I can't tell you the way to upgrade because I'm not good at conda. Please ask it in sphinx-users community. Somebody will help you.
https://groups.google.com/g/sphinx-users

**Comment by leighfletcher** [comment]
Thank you - I've emailed that user community.

Edit:  I finally resolved this issue by forcing an update with, just in case it's of use to others:
`pip install sphinx --upgrade`
