### ISSUE TITLE
Allow MathJax customization via local.js

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#969]
MathJax allows for customization via local.js files (such as definition of new macros, among other): http://www.mathjax.org/docs/1.1/configuration.html .

Such custom configuration should interfere with using MathJax's CDN.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/969
- Originally reported by: [eudoxos](https://bitbucket.org/eudoxos)
- Originally created at: 2012-07-14T09:03:41.940

**Comment by shimizukawa** [comment]
_From Hiroaki Itoh on 2012-07-25 12:08:45+00:00_

I think so.
My personal solution is,
in conf.py:
{{{
mathjax_path = 'MathJax_local.js'
}}}

_static/MathJax_local.js is:
{{{
document.write('<script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML"></script>');
document.write('\
<script type="text/x-mathjax-config">\
          MathJax.Hub.Config({\
            TeX: {\
              Macros: {\
                iddots: "{\\kern3mu\\raise1mu{.}\\kern3mu\\raise6mu{.}\\kern3mu\\raise12mu{.}}"\
              }\
            }\
          });\
        </script>')
}}}

But I want more sophisticated way.

**Comment by shimizukawa** [comment]
_From [eudoxos](https://bitbucket.org/eudoxos) on 2013-04-19 13:21:03+00:00_

It works for me now also. I had a syntax error in the code, which was not reported anywhere. Thanks!

**Comment by hhsprings** [comment]
I wrote (maybe) below, just in case. (But I didn't reconfirm that.)

## 

_static/MathJax_local.js is:

``` js
document.write('<script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML"></script>');
document.write('\
<script type="text/x-mathjax-config">\
          MathJax.Hub.Config({\
            TeX: {\
              Macros: {\
                iddots: "{\\\\kern3mu\\\\raise1mu{.}\\\\kern3mu\\\\raise6mu{.}\\\\kern3mu\\\\raise12mu{.}}"\
              }\
            }\
          });\
        </script>')
```

**Comment by tk0miya** [comment]
I just made a new PR #5230 for this. Could anyone test this please?
I'm not good at mathjax. so I don't know this is enough or not.

**Comment by tk0miya** [comment]
Now #5230 is merged.
Thank you for reporting!
