### ISSUE TITLE
Toctree reverse

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#971]
A reverse sorting could be nice, for changelogs or blogs: the last entry appears first

```
#!python

.. toctree::
    :glob:
    :reverse:

    *
```

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/971
- Originally reported by: Anonymous
- Originally created at: 2012-07-15T23:27:16.153

**Comment by shimizukawa** [comment]
Now close this issue. Please create another issue if you still need such feature.

**Comment by JohnVillalovos** [comment]
I put up a pull request to do this:

https://github.com/sphinx-doc/sphinx/pull/2527
