### ISSUE TITLE
Search not working with sphinx versions newer than 3.3.1 (error with searchtools.js file)

### ISSUE THREAD

**Issue by daronburleson** [sphinx-doc/sphinx#9714]
### Describe the bug

Search page does not load results when using sphinx versions newer than 3.3.1. This is happenning at least with "sphinx-rtd-theme" and "classic" theme as well.

### How to Reproduce

Install any sphinx version older thatn 3.3.1 (eg: 3.4.0) and check how this error is given in the search results page (console logs): 

`Uncaught ReferenceError: Stemmer is not defined  at Object.query (searchtools.js:158)`

### Expected behavior

Search should work well and give search results.

### Your project

Not available

### OS

Mac OS

### Python version

2.7.16

### Sphinx version

3.4.0 and older

**Comment by astrojuanlu** [comment]
Hi @daronburleson , if this only happens with sphinx_rtd_theme 1.0, it will be better to open the issue in its repository.

**Comment by daronburleson** [comment]
Hi @astrojuanlu! I have just checked with "classic" theme and the problem remains. I have edited my original comment to emphasize this fact. If there's anything else that I can do, please let me know.

**Comment by jakobandersen** [comment]
I'm a bit unsure about which versions this applies to. In the initial description you write "versions newer than 3.3.1", but in the reproduction you write "any sphinx version older thatn 3.3.1 (eg: 3.4.0)". Did you mean "newer" the second time as well.
Is the bug present with the newest release?

**Comment by daronburleson** [comment]
Sorry for the misunderstanding, I mixed newer/older ;)

Version 3.3.1 is working well, versions 3.4.0 and above are NOT working. I've checked with the newest one as well (4.2.0) and it doesn't work either.

**Comment by tk0miya** [comment]
On my local, I can't reproduce the error. I used Sphinx-4.2.0 and a brand-new project.
<img width="1099" alt="スクリーンショット 2021-10-09 13 26 19" src="https://user-images.githubusercontent.com/748828/136643985-2512a0b4-40c7-474a-b80c-078b337718b2.png">

Could you share your project or a minimal reproducible example?

**Comment by tk0miya** [comment]
This is the same result when I used the classic theme.
<img width="1099" alt="スクリーンショット 2021-10-09 13 28 41" src="https://user-images.githubusercontent.com/748828/136644037-acd8fe17-84a9-4448-a674-b9b87576c01e.png">

**Comment by daronburleson** [comment]
OMG... I have just checked that I was using a search.html file in the _templates folder from an older version. I just removed this file and the search started to work as expected. Sorry for the noise!
