### ISSUE TITLE
Emit event after `prepare_writing`

### ISSUE THREAD

**Issue by ain-soph** [sphinx-doc/sphinx#9716]
**Is your feature request related to a problem? Please describe.**
I want to do some modification to the `builder.globalcontext` in `setup.py`, but seems to have no event for that. Since after `prepare_writing`, it'll be the page writing in parallel, so I think it might not be a good idea to modify the shared `globalcontext` in each subprocess.

**Describe the solution you'd like**
Emit an event at #L524.
https://github.com/sphinx-doc/sphinx/blob/3f51f1a6cf9f1b710ffbf391dd31200b845c7873/sphinx/builders/__init__.py#L522-L532

**Comment by tk0miya** [comment]
Please let me know the reason why you need the event in detail. We already have `html-page-context` event to modify the context for each page. I think it also helps to modify the output.

**Comment by ain-soph** [comment]
> Please let me know the reason why you need the event in detail. We already have `html-page-context` event to modify the context for each page. I think it also helps to modify the output.

Yes, I could use `html-page-context` to mofify them for each time, but that would be a waste. I should only need to do once globally to change the context, rather than modify each separate context individually.

If we only consider the adding new variables during the emit function I suppose, it would be very similar to the current `html_theme_options`. But I'm currently working on an extension rather than a theme, and I also need to modify existing values rather than simply adding new ones.

**Comment by ain-soph** [comment]
Currently I'm using `html-page-context`, though it operates for every page rather than once globally. But it's not a big deal.

I'm fine if the maintainer wants to close this issue. @tk0miya

**Comment by tk0miya** [comment]
Sorry for the late response. I think the new event is not needed if the `html-page-context` event satisfies you. I understand it is wasteful to fill in context for each page. But it's tough to design a new event. So I'd like to know it is really needed or not.
Thanks,

**Comment by ain-soph** [comment]
> Sorry for the late response. I think the new event is not needed if the `html-page-context` event satisfies you. I understand it is wasteful to fill in context for each page. But it's tough to design a new event. So I'd like to know it is really needed or not.
> Thanks,

Glad to receive your reply. I’ve got my task working using the html-page-context. So it’s okay to keep the current status.
