### ISSUE TITLE
sphinx v4.1.2 emits stray "aggedright" text in LaTeX output

### ISSUE THREAD

**Issue by ahippo** [sphinx-doc/sphinx#9734]
### Describe the bug

Sphinx versions starting with 4.0 (including currently used 4.1.2 and latest 4.2.0)
introduced a bug in handling hlists in its LaTeX backend in commit 20884bb0c9f76834972b52e28f24df989a10eb68.
Due to improper backslash escaping, LaTeX "\raggedright" command is written
as Carriage Return character (0x0D) followed by "aggedright".

This results in stray "aggedright" text appearing in the resulting PDF and lack of effect \raggedright was supposed to achieve.

Proposed fix:
```patch
--- sphinx/writers/latex.py.orig        2021-07-11 13:41:57.000000000 -0400
+++ sphinx/writers/latex.py     2021-10-11 23:54:00.081303222 -0400
@@ -1213,3 +1213,3 @@
             self.body.append(r'\setlength{\multicolsep}{0pt}' + CR)
-        self.body.append(r'\begin{multicols}{' + ncolumns + '}\raggedright' + CR)
+        self.body.append(r'\begin{multicols}{' + ncolumns + r'}\raggedright' + CR)
         self.body.append(r'\begin{itemize}\setlength{\itemsep}{0pt}'
```

This appears to be the only occurrence of missing escaping:
```
$ grep -P "[^r]'[^']*\\\\+[^']*'" /usr/lib/python3.9/site-packages/sphinx/writers/latex.py
CR = '\n'
BLANKLINE = '\n\n'
            replace('\\', '_')
        self.body.append(r'\begin{multicols}{' + ncolumns + '}\raggedright' + CR)
            self.body.append('\n\\begin{sphinxuseclass}{%s}' % c)
            self.body.append('\n\\end{sphinxuseclass}')
```

### How to Reproduce

```
$ mkdir bug
$ cd bug
$ cat > conf.py <<EOFF
source_suffix = '.rst'
root_doc = 'index'

latex_engine = "lualatex"
latex_documents = [
    (root_doc, 'Bug.tex', 'Bug', 'Bug', 'manual'),
]
EOFF
$ cat > index.rst <<EOFF
Bug report
==========

.. toctree::
   intro
EOFF
$ cat > intro.rst <<EOFF
.. hlist::

   * a
EOFF
$
$ sphinx-build -M latexpdf . _build -W
$ grep aggedright'$' _build/latex/Bug.tex | cat -A  # notice the ^M just before "aggedright"
\begin{multicols}{2}^Maggedright$
```

### Expected behavior

\raggedright directive is properly emitted.

### Your project

See the reproducer in How to reproduce field

### Screenshots

![image](https://user-images.githubusercontent.com/1228485/137063405-93d7cb3a-96f6-4f65-9b73-46a805177e05.png)

### OS

Linux

### Python version

3.9.6

### Sphinx version

4.1.2

### Extra tools

lualatex / luahbtex -- LuaHBTeX, Version 1.13.0 (TeX Live 2021 Gentoo Linux)

**Comment by stratosgear** [comment]
Got bitten by it, too! Looking forward for the next release!
