### ISSUE TITLE
Sphinx does not render rst file correctly

### ISSUE THREAD

**Issue by alex4200** [sphinx-doc/sphinx#9742]
### Describe the bug

I have a `test.rst` file in the source folder which is not correctly rendered when I use sphinx on it. 

The content of that rst file in utf-8 encoding is:

`b':orphan:\nTest\n====\n\n.. raw:: html\n\n   <div>\n      <p><i>first line\n\rsecond line</i></p>\n   </div>\n  '
`
### How to Reproduce

Use the following content

[demo.tar.gz](https://github.com/sphinx-doc/sphinx/files/7352285/demo.tar.gz)

and run 

sphinx-build -M html source build -v

### Expected behavior

I expect some output like 

```
first line
second line
```

without rendered(!) html tags.

### Your project

See above

### Screenshots

![Screenshot 2021-10-14 at 15 08 04](https://user-images.githubusercontent.com/12729291/137462566-ddd614c3-538b-4881-a196-c724d93233c2.png)

### OS

Mac OS 10.14.6

### Python version

3.8.12

### Sphinx version

4.2.0

**Comment by tk0miya** [comment]
```
b':orphan:\nTest\n====\n\n.. raw:: html\n\n <div>\n <p><i>first line\n\rsecond line</i></p>\n </div>\n '
```

This source code is recognized as following:

```
:orphan:
Test
====

.. raw:: html

   <div>
      <p><i>first line

second line</i></p>
   </div>
```

As you see, the "second line" is placed out of the raw block. So it is recognized as mere text.

Please indent the line deeper.
