### ISSUE TITLE
Allow a 2-item list as well as a 2-item tuple in nitpick_ignore

### ISSUE THREAD

**Issue by hyanwong** [sphinx-doc/sphinx#9748]
**Is your feature request related to a problem? Please describe.**
I'm using the jupyterbook program to create Sphinx docs, which uses a YML file to configure Sphinx. But YML doesn't allow tuples, only lists, so I can't specify `nitpick_ignore` values (also see someone else who has a similar problem https://github.com/nengo/nengo-bones/issues/42)

**Describe the solution you'd like**
Can the `nitpick_ignore` config option take a list of lists, as well as a list of tuples. E.g.

```
nitpick_ignore = [
    ['py:func', 'int'],
    ['py:func', 'float'],
    ['envvar', 'LD_LIBRARY_PATH']
]
```

**Describe alternatives you've considered**
Alternatively a more concise form would be to allow a dict, keyed by the first element of the tuple:

```
nitpick_ignore = {
    'py:func': ['int', 'float'],
    'envvar': ['LD_LIBRARY_PATH']
}
```

**Comment by jeromekelleher** [comment]
If anyone else lands on this, an easy workaround is to use ``nitpick_ignore_regex`` instead. This requires sphinx >= 4.1 I think.
