### ISSUE TITLE
Annotations on "next generation" attrs classes not supported by autodoc

### ISSUE THREAD

**Issue by jwodder** [sphinx-doc/sphinx#9752]
### Describe the bug

Version 20.1.0 of [attrs](https://www.attrs.org) introduced a new ["next generation" API](https://www.attrs.org/en/stable/api.html#next-generation-apis) that uses `attr.define` and `attr.field` instead of `attr.s` and `attr.ib`.  Unfortunately, autodoc does not treat this new API the same way as the old one; in particular, type annotations on attributes are not shown when using the new API.

### How to Reproduce

```
$ git clone https://github.com/jwodder/sphinx-attrs-bug-20211018
$ cd sphinx-attrs-bug-20211018
$ tox -e docs
$ open docs/_build/html/index.html
```

Open `docs/_build/html/index.html` in a browser and observe that the `@attr.s`-using class has its attributes' type annotations shown, while the `@attr.define`-using one does not.  Conversely, the `@attr.define` class has a constructor signature shown, while the `@attr.s` one does not.

### Expected behavior

The rendered documentation for the `@attr.s` class and the `@attr.define` class should be the same, particularly in that the attributes of the `@attr.define` class should have their type annotations shown.

### Your project

https://github.com/jwodder/sphinx-attrs-bug-20211018

### Screenshots

<img width="475" alt="Screen Shot 2021-10-18 at 19 21 32" src="https://user-images.githubusercontent.com/98207/137819329-6b83d009-21d2-4361-bb32-be856ecae94c.png">

### OS

macOS

### Python version

3.9.7

### Sphinx version

4.2.0

### Sphinx extensions

sphinx.ext.autodoc

**Comment by tk0miya** [comment]
Note: It seems `@attr.define` uses `__slots__` to generate attributes:
```
root@91e94d32e5d8:/sphinx-attrs-bug-20211018/docs# python
Python 3.9.7 (default, Sep  3 2021, 02:02:37)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sphinx_attrs
>>> sphinx_attrs.Foo.__slots__
('bar', 'baz', 'quux', '__weakref__')
```
