### ISSUE TITLE
tf.Tensor not recognised by Sphinx.

### ISSUE THREAD

**Issue by SamTov** [sphinx-doc/sphinx#9754]
### Describe the bug

When I try to build docs on readthedocs much of the module documentation is not built due to the following error:

```bash
AttributeError: module 'tensorflow' has no attribute 'Tensor'
```

All tf.Tensors are used in type definition in python scripts of the form:

```python
import tensorflow as tf

class MyClass:
    def my_method(b: tf.Tensor) -> tf.Tensor:
        ...

```

### How to Reproduce

Assumedly one can have tf.Tensor as a type hint and try to compile this.

### Expected behavior

I would expect it to treat the type as any other.

### Your project

https://github.com/zincware/MDSuite

### OS

Unix

### Python version

3.7.9

### Sphinx version

4.2.0

### Sphinx extensions

extensions = [     "sphinx.ext.autodoc",     "sphinx.ext.napoleon",     "sphinx.ext.autosummary",     "sphinx.ext.githubpages",     "sphinx.ext.intersphinx",     "sphinx.ext.mathjax",     "sphinx.ext.viewcode",     "IPython.sphinxext.ipython_directive",     "IPython.sphinxext.ipython_console_highlighting",     "numpydoc",     "sphinx_copybutton",     "nbsphinx",     "IPython.sphinxext.ipython_console_highlighting",     "IPython.sphinxext.ipython_directive",     "sphinx.ext.autosectionlabel",     "sphinxcontrib.bibtex", ]

### Extra tools

Using readthedocs server

**Comment by astrojuanlu** [comment]
> When I try to build docs on readthedocs

Do you have a link to the build?

**Comment by SamTov** [comment]
[docs](https://mdsuite.readthedocs.io/en/samtov_fix_docs/modules_and_classes.html)

This is on a specific branch and in the module and classes nothing renders were tensors are used as types in the hinting. Of course there could be other reasons for it not rendering but all of the modules that do not render raise the exception listed above.

**Comment by astrojuanlu** [comment]
Weird. I just tried

```
$ python3.7 -m venv .venv
$ source .venv/bin/activate
$ pip install "tensorflow==2.6.0"
$ python    
Python 3.7.12 (default, Sep 10 2021, 00:20:04) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
2021-10-21 11:38:52.098733: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-10-21 11:38:52.098752: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
>>> tf.Tensor
<class 'tensorflow.python.framework.ops.Tensor'>
```

And my `tensorflow/__init__.py` contains very clearly

```
from tensorflow.python.framework.ops import Tensor
```

Perhaps Sphinx gets confused by the warnings that appear?

**Comment by tk0miya** [comment]
I got this result. It seems working correctly:
<img width="729" alt="スクリーンショット 2021-10-23 1 47 49" src="https://user-images.githubusercontent.com/748828/138492889-e730bbf4-9df3-4292-ae5b-c010bbf35a13.png">

Input:
```
.. automodule:: example
   :members:
   :undoc-members:
```
```
import tensorflow as tf

class MyClass:
    def my_method(b: tf.Tensor) -> tf.Tensor:
        ...
```

Dockerfile:
```
FROM python:3.7-slim

RUN apt update; apt install -y build-essential curl git unzip vim
RUN pip install Sphinx tensorflow
```

Log:
```
root@d5b447f6c5c6:/doc# make html
Running Sphinx v4.2.0
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 1 source files that are out of date
updating environment: [new config] 1 added, 0 changed, 0 removed
2021-10-22 16:47:21.040198: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-10-22 16:47:21.040277: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index
generating indices... genindex py-modindex done
writing additional pages... search done
copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded.

The HTML pages are in _build/html.
```

**Comment by tk0miya** [comment]
Note: This is the build log on failed to build the document. Indeed, it failed to import tensorflow.
https://readthedocs.org/projects/mdsuite/builds/15036490/

**Comment by SamTov** [comment]
Okay no problem. It seems then like something else is going on. Thank you for the help.
