### ISSUE TITLE
Overridden classmethod documentation not inherited with autodoc

### ISSUE THREAD

**Issue by EpicWink** [sphinx-doc/sphinx#9757]
### Describe the bug

The documentation for a classmethod in a parent class is not inherited by the method re-defined (without documentation) in a child class

### How to Reproduce

Module `src/spam.py`:
```python
class Parent:
    @classmethod
    def method(cls) -> int:
        """Return an integer."""
        return 17


class Child(Parent):
    @classmethod
    def method(cls):
        return 42
```

Sphinx configuration `docs/conf.py`:
```python
project = "spam"
extensions = ["sphinx.ext.autodoc"]
```

Documentation index `docs/index.rst`:
```rst
spam
====

.. automodule:: spam
   :members:
   :undoc-members:
```

Build:
```shell
PYTHONPATH=src sphinx-build docs/ build
```

### Expected behavior

Overridden classmethod to inherit documentation from parent class

### Your project

https://github.com/EpicWink/python-swf-typed

### Screenshots

![Screenshot from 2021-10-21 20-13-39](https://user-images.githubusercontent.com/25142085/138257992-3e1f06b2-d5b1-4195-bfe8-451e09a4828a.png)

### OS

Ubuntu 20.04

### Python version

3.8

### Sphinx version

4.2.0

### Sphinx extensions

sphinx.ext.autodoc

### Additional context

`inspect.getdoc(Child.method)` returns the expected value

**Comment by tk0miya** [comment]
By default, autodoc searches the docstring from the parent class. Please disable `autodoc_inherit_docstrings`.
https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_inherit_docstrings

**Comment by EpicWink** [comment]
Setting `autodoc_inherit_docstrings = False` didn't fix it. As a matter of fact, it (as the name suggests) disabled inheritance of docstrings for all methods, not just classmethods. Also, explicitly setting  `autodoc_inherit_docstrings = True` didn't fix it

This to me seems like a bug specific to classmethods

**Comment by EpicWink** [comment]
@tk0miya I don't think this issue is resolved

**Comment by tk0miya** [comment]
Okay, I'll take a look.

**Comment by tk0miya** [comment]
Sorry, I misunderstand your report. Reproduced the error on my local.
