### ISSUE TITLE
Allow 403: Forbidden as acceptable in linkcheck

### ISSUE THREAD

**Issue by robinovitch61** [sphinx-doc/sphinx#9761]
**Is your feature request related to a problem? Please describe.**
I'd like our sphinx build to check links with the `linkcheck` builder. A number of links are behind oauth and throw 403s when requested. I'd like to make this acceptable and not report as a broken link.

The current linkcheck accepts 401s:
https://github.com/sphinx-doc/sphinx/blob/cf96c93cf17c2659f1947201a684bb8e2b6c6250/sphinx/builders/linkcheck.py#L475-L477

[403 is similar](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403):
> The HTTP 403 Forbidden client error status response code indicates that the server understands the request but refuses to authorize it.
>
> This status is similar to 401, but in this case, re-authenticating will make no difference. The access is permanently forbidden and tied to the application logic, such as insufficient rights to a resource.

**Describe the solution you'd like**
Add 403 as an acceptable, not-broken link response code.

**Describe alternatives you've considered**
None

**Additional context**
I've made a PR for this [here](https://github.com/sphinx-doc/sphinx/pull/9762). Thank you!

**Comment by AA-Turner** [comment]
Closing, though the allowable responses config option in the linked PR would be considered as a feature.

A
