### ISSUE TITLE
proposal: pngmath_also_latex

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#977]
It will be worth that pngmath handle `:math:` even where in latex output.

Please see atatched for details.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/977
- Originally reported by: Hiroaki Itoh
- Originally created at: 2012-07-25T13:56:04.735

**Comment by tk0miya** [comment]
IMO, I don't think merging this patch is good idea because the feature is not common. However, it looks good for some people. I think it's nice if the feature is released as a sphinx extension. It will help someone in similar situation.

Thanks,
