### ISSUE TITLE
Python 2.7 compatible type hinting

### ISSUE THREAD

**Issue by tallero** [sphinx-doc/sphinx#9776]
Packages like `sphixcontrib-serializinghtml` should still work with sphinx `v1.8.5` but they have introduced (long ago) incompatible type-hinting.

Since PEP-484 defines a retro-compatible [style](https://stackoverflow.com/a/35230792/9402438), why don't adopt that?

**Comment by tk0miya** [comment]
We determined to drop python2 support on releasing 2.0. So the current packages do not support it at all. Please use the old version or upgrade your Python. Thanks,
