### ISSUE TITLE
Re-opening #8255: hexadecimal default arguments are changed to decimal

### ISSUE THREAD

**Issue by mara004** [sphinx-doc/sphinx#9781]
### Describe the bug

I am experiencing the exact same problem as described in #8255: hexadecimal default arguments are changed to decimal.

### How to Reproduce

Autodoc the following function:

```python3
def some_function(
        param_a,
        param_b,
        *,  # enforce keyword arguments from this point onwards
        background_colour: int = 0xFFFFFFFF,
        # ... other optional parameters
    ):
    pass
```

HTML result looks like this
```
background_colour: int = 4294967295
```

### Expected behavior

Hexadecimal defaults should not be converted to decimal, or at least there should be an option to enforce this behaviour.

### Your project

I'm afraid this is private

### OS

Linux Ubuntu 20.04

### Python version

3.8.10

### Sphinx version

4.2.0

### Sphinx extensions

autodoc, intersphinx, napoleon

### Extra tools

Chromium 94

**Comment by tk0miya** [comment]
Does `autodoc_preserve_defaults` help you?
https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_preserve_defaults

**Comment by mara004** [comment]
I had already added
```python3
autodoc_preserve_defaults = True
```
to my `conf.py` file but it didn't change the output. So no, it doesn't help.

**Comment by mara004** [comment]
Thanks!
