### ISSUE TITLE
Please document how to migrate away from deprecated or removed API

### ISSUE THREAD

**Issue by thomasgoirand** [sphinx-doc/sphinx#9782]
### Describe the bug

Hi,

This bug report is a message in the bottle that I hope will find the correct reader.

I'm the maintainer of more than 500 packages in Debian (because maintaining OpenStack). Since the upgrade to Sphinx 4.2, I'm having a very hard time to fix all the brokenness there is all over the place. The main issue is that, while there's a list of deprecated and removed API over here:

https://www.sphinx-doc.org/en/master/extdev/deprecated.html

there's no link to what one should do. What I would expect instead, is a link to some code for each of the API related deprecation/removal. For example:

If you had this in your code:

bla

then you need to transform your code to do that:

bli

With this as a convenient resource, it would be much much easier to follow the API lifecycle of Sphinx, instead of doing helpless google search queries in the hope to find a solution.

Please understand that, as a package maintainer for distributions, I unfortunately cannot dedicate my time to each individual project documentation. We just package the documentation on best effort. The result of not enough documentation in Sphinx could lead to a simple documentation removal, which is really not the effect we're seeking here. Also keep in mind that, for downstream distribution, we sometimes need to maintain packages that may sometimes become unmaintained upstream, which adds complexity because of the lost upstream support. Having all of these removal and deprecation is hard, especially considering the number of package one may maintain.

A better documentation in Sphinx on how to fix would very much help. I of course would prefer that Sphinx stops breaking its API, but this looks like a lost cause... :/

Cheers,

Thomas Goirand (zigo)

### How to Reproduce

Build some docs with Sphinx 4.2...

### Your project

https://qa.debian.org/developer.php?login=team%2Bopenstack%40tracker.debian.org

### OS

Linux

### Python version

3.9

### Sphinx version

4.2.0

**Comment by tk0miya** [comment]
+0: It would be nice if we can improve the document. But the almost entries were non-public API. So I'm not sure it's really worthy or not.
