### ISSUE TITLE
Sphinx 2.3.2 with MySQL8.0.17 

### ISSUE THREAD

**Issue by prashantjadhav16** [sphinx-doc/sphinx#9785]
### Describe the bug

Hi Folks,
Using source code:

I am trying to install MySQL 8.0.17 with sphinx 2.3.2 using source code installation method but at the cmake3 step i am facing issue like  source directory  doesn't exist but file is there at that place.

![Sphinx_cmake issue](https://user-images.githubusercontent.com/93263465/139070986-e73866d6-e26f-460b-99c9-2b8fd8d7e0d6.JPG)

Using RPM installation:

 I have tried using rpm installation , installation was completed  but while installing sphinx plugin error occurred like
can't open shared library '/usr/lib64/mysql/plugin/ha_sphinx.so'

also i want  to know does sphinx support MySQL 8.0 version or not?

![image](https://user-images.githubusercontent.com/93263465/139071952-fe053cab-aeed-4d7b-bfb6-3a60f2f012a1.png)

### How to Reproduce

```
$ git clone https://github.com/.../some_project
$ cd some_project
$ pip install -r requirements.txt
$ cd docs
$ make html SPHINXOPTS="-D language=de"
$ # open _build/html/index and see bla bla
```

### Expected behavior

Sphinx 2.3.2 needs to work with MySQL 8.0.17.

### Your project

We are using sphinx as search engine, basically it is used for fetching data.

### OS

centOS 7

### Python version

2.7.5

### Sphinx version

2.3.2

**Comment by tk0miya** [comment]
I think you got a wrong site. This repository is Sphinx for the documentation tool, not a search engine. Please visit http://sphinxsearch.com/ and ask your question.
Thanks,

**Comment by prashantjadhav16** [comment]
Thank You @tk0miya for your quick response.
