### ISSUE TITLE
Build failed - 'generator' object is not reversible

### ISSUE THREAD

**Issue by BennyEronson** [sphinx-doc/sphinx#9786]
### Describe the bug

TypeError: 'generator' object is not reversible.

Even the tech guides at our company could not understand what could cause this.

See the complete error messages in the attached file.

[Error log file 20211027.txt](https://github.com/sphinx-doc/sphinx/files/7427051/Error.log.file.20211027.txt)

### How to Reproduce

Build project Omnia Docs G2.

### Expected behavior

A new version (latest) of the documentation should have been built.

### Your project

https://readthedocs.org/projects/omnia-docs-g2/builds/

### OS

Windows 10 version 20H2

### Python version

python 3.7

### Sphinx version

1.8.5

**Comment by astrojuanlu** [comment]
Duplicate of #9727 and https://github.com/readthedocs/readthedocs.org/issues/8616.

**Comment by BennyEronson** [comment]
Hello Juan,

Authored what thread? (Sorry I'm just an author).

Benny

Den ons 27 okt. 2021 kl 17:26 skrev Juan Luis Cano Rodríguez <
***@***.***>:

**Comment by Jason2013** [comment]
I encountered the same issue:

https://readthedocs.org/projects/getting-started-with-llvm-core-libraries-zh-cn/builds/

**Comment by astrojuanlu** [comment]
Have a look at https://github.com/sphinx-doc/sphinx/issues/9727#issuecomment-953025696 and https://github.com/readthedocs/readthedocs.org/issues/8616#issuecomment-952034858 to solve the problem.

**Comment by BennyEronson** [comment]
Thank you for your effort. I will tell our tech guys to give me a hand with
this.

Benny

Den ons 27 okt. 2021 kl 17:44 skrev Juan Luis Cano Rodríguez <
***@***.***>:
