### ISSUE TITLE
Reference to class properties that are classes are wrong

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#980]
If a class has a class property that is set to a class, then this class is not linked correctly.

So, in the following code, the property Foo.test will link to "Test" instead of "a.Test". I'll attach a patch that fixes the issue for me.

File a:

class Test(object):
    pass

File b:

import a

class Foo(object):
    test = a.Test

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/980
- Originally reported by: [benzea](https://bitbucket.org/benzea)
- Originally created at: 2012-07-28T23:17:07.065

**Comment by tk0miya** [comment]
It seems this is already fixed at latest version. Closing.
