### ISSUE TITLE
Build started failing without any changes to my documentation.

### ISSUE THREAD

**Issue by hydroflame** [sphinx-doc/sphinx#9810]
### Describe the bug

https://readthedocs.org/projects/bitburner/builds/15099218/

A week ago my readthedoc builds started failing on their own. The change that triggered the first failure does not include any changes to any of the documentation files.

    TypeError: 'generator' object has no attribute '__getitem__'

The documentation builds correctly without errors locally.

### How to Reproduce

```
Cannot be reproduced locally
```

### Your project

https://readthedocs.org/projects/bitburner/

### OS

OSX

### Python version

2.7

### Sphinx version

v1.8.5

### Sphinx extensions

'sphinx.ext.autodoc','sphinx.ext.doctest','sphinx.ext.intersphinx','sphinx.ext.todo','sphinx.ext.coverage','sphinx.ext.mathjax','sphinx.ext.ifconfig','sphinx.ext.viewcode','sphinx.ext.githubpages'

**Comment by astrojuanlu** [comment]
Please check out #9809, #9727, #9788, readthedocs/readthedocs.org#8616 , readthedocs/readthedocs.org#8618, readthedocs/readthedocs.org#8640, readthedocs/readthedocs.org#8642.

**Comment by hydroflame** [comment]
Fixed it
