### ISSUE TITLE
TypeError: 'generator' object is not reversible

### ISSUE THREAD

**Issue by EnricoCorsaro** [sphinx-doc/sphinx#9834]
### Describe the bug

I cannot compile anymore my online readthedocs linked to my github repo. I can confirm that I am able to compile sphinx successfully in my local machine (I am using a Mac OS v. 11.6), so the problem should not rely on my actual documentation, but it appears to be a bug of the online readthedocs compiling system.

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/famed/envs/latest/lib/python3.7/site-packages/sphinx/util/nodes.py", line 94, in apply_source_workaround
    for classifier in reversed(node.parent.traverse(nodes.classifier)):
TypeError: 'generator' object is not reversible

### How to Reproduce

```
$ git clone --no-single-branch --depth 50 https://github.com/EnricoCorsaro/FAMED.git .
$ git checkout --force origin/master
$ git clean -d -f -f
$ python3.7 -mvirtualenv /home/docs/checkouts/readthedocs.org/user_builds/famed/envs/latest
$ /home/docs/checkouts/readthedocs.org/user_builds/famed/envs/latest/bin/python -m pip install --upgrade --no-cache-dir pip setuptools
$ /home/docs/checkouts/readthedocs.org/user_builds/famed/envs/latest/bin/python -m pip install --upgrade --no-cache-dir mock==1.0.1 pillow==5.4.1 alabaster>=0.7,<0.8,!=0.7.5 commonmark==0.8.1 recommonmark==0.5.0 sphinx<2 sphinx-rtd-theme<0.5 readthedocs-sphinx-ext<2.2
$ cat docs/source/conf.py
$ /home/docs/checkouts/readthedocs.org/user_builds/famed/envs/latest/bin/python -m sphinx -T -b html -d _build/doctrees -D language=en . _build/html
```

### Expected behavior

Just that the compilation could run smoothly, with only warning messages at most.

### Your project

https://readthedocs.org/projects/famed/

### Screenshots

I attach the full log of the compilation.
[sphinx_error.txt](https://github.com/sphinx-doc/sphinx/files/7505481/sphinx_error.txt)

### OS

GitHub repo

### Python version

3.7

### Sphinx version

1.8.5

### Additional context

https://famed.readthedocs.io/en/latest/

**Comment by astrojuanlu** [comment]
See #9811, #9810, #9809, #9727, #9788, readthedocs/readthedocs.org#8616 , readthedocs/readthedocs.org#8618, readthedocs/readthedocs.org#8640, readthedocs/readthedocs.org#8642. You can solve this by capping docutils to <0.18 in your requirements. More information here: https://blog.readthedocs.com/build-errors-docutils-0-18/
