### ISSUE TITLE
Warning, treated as error: node class 'meta' is already registered, its visitors will be overridden

### ISSUE THREAD

**Issue by nomathx** [sphinx-doc/sphinx#9841]
### Describe the bug

sphinx-build -W -b html -d /tmp/doctrees docs docs/html 
Warning, treated as error:
`node class 'meta' is already registered, its visitors will be overridden`

### How to Reproduce

build documentation

### Expected behavior

No warning

### Your project

source is not available

### OS

Centos7

### Python version

Python 3.8

### Sphinx version

sphinx==2.3.1

### Sphinx extensions

-

### Additional context

index.rst:

Welcome to project's documentation!
=========================================

.. toctree::
   :maxdepth: 2
   :caption: Contents:

   syntax_introduction

Indices and tables
==================

* :ref:`genindex`
* :ref:`modindex`
* :ref:`search`

**Comment by tk0miya** [comment]
Could you check the version of docutils, please? If you're using docutils-0.18, please upgrade your Sphinx or downgrade docutils to 0.17.
Thanks,

**Comment by eviljeff** [comment]
> Could you check the version of docutils, please? If you're using docutils-0.18, please upgrade your Sphinx ...

@tk0miya  I'm reading this as there is a more recent version of Sphinx that is compatible with docutils-0.18, but setup.py still [specifies <0.18](https://github.com/sphinx-doc/sphinx/blob/master/setup.py#L26)

**Comment by tk0miya** [comment]
Sorry for lack of my words. Yes, all of Sphinx does not support the latest docutils. So you need to downgrade it via 1) installing the latest Sphinx (it will downgrade docutils through its dependency), 2) downgrade docutils by your hand.
