### ISSUE TITLE
Configuration variable `copyright` is shadowing a Python builtin constant

### ISSUE THREAD

**Issue by mondeja** [sphinx-doc/sphinx#9845]
### Describe the bug

[`copyright` is a Python builtin constant](https://docs.python.org/3/library/constants.html#copyright), so Sphinx is always shadowing the `copyright` builtin in documentation.

### How to Reproduce

```python
$ python3 -c 'import builtins as b;print("copyright" in dir(b))'
True
```

### Your project

Any

### OS

All

### Python version

Tested in Python3.10 and Python2.7

### Sphinx version

All

**Comment by tk0miya** [comment]
For that purpose, we've also provide `project_copyright` as an alias of `copyright`. Please use it instead.
https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-project_copyright
