### ISSUE TITLE
NameError: name 'configs' is not defined

### ISSUE THREAD

**Issue by banyous** [sphinx-doc/sphinx#9851]
### Describe the bug

I am having the following error when trying to make build my project

> WARNING: autodoc: failed to import module 'stream'; the following exception was raised:
> Traceback (most recent call last):
>   File "/home/youcef/.local/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 70, in import_module
>     return importlib.import_module(modname)
>   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 848, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/home/youcef/streaming_main/src/stream.py", line 37, in <module>
>     if not os.path.exists(configs['log']):
> NameError: name 'configs' is not defined

Here is part of code that renders the error :

```
try:
    with open(r'.config.yml') as file:
        configs = yaml.load(file, Loader=yaml.FullLoader)
except Exception as exp:
    print('Please add configuration file')
    #sys.exit(-1)
        
if not os.path.exists(configs['log']):
    os.makedirs(configs['log'])
```

### How to Reproduce

```
$ git clone https://github.com/.../some_project
$ cd some_project
$ pip install -r requirements.txt
$ cd docs
$ make html SPHINXOPTS="-D language=de"
$ # open _build/html/index and see bla bla
```

### Expected behavior

I excpected the make to happen without errors

### Your project

code added in the text

### OS

linux

### Python version

3.8

### Sphinx version

4.3.0

### Sphinx extensions

'sphinx.ext.autodoc', 'sphinx.ext.napoleon', 'sphinx.ext.viewcode',

**Comment by tk0miya** [comment]
Autodoc extension automatically imports your module to build document. So your module should be able to be importable even outside of the directory where you expect. It seems `configs` variable is not defined if OSError raised. Please check your code.

**Comment by banyous** [comment]
Thanks @tk0miya
