### ISSUE TITLE
dataclass member variables are documented out of order

### ISSUE THREAD

**Issue by stefanseefeld** [sphinx-doc/sphinx#9853]
### Describe the bug

class members documented via `autoclass` or similar will be reordered during documentation (apparently alphabetically).
However, for dataclasses, the actual ordering actually matters, as it dictates the argument order in the (generated) constructor.

### How to Reproduce

```
@dataclass
class Foo:
    a: str  #: a doc
    c: str  #: c doc
    b: str  #: b doc

```
will yield documentation such as

1. a ...
2. b ...
3. c ...

### Expected behavior

The expected ordering is of course

1. a ...
2. c ...
3. b ...

### Your project

no (public) project, sorry

### OS

Ubuntu 20.04

### Python version

3.8.10

### Sphinx version

4.3.0

**Comment by tk0miya** [comment]
Have you every tried `autodoc_member_order`? By default, autodoc extension orders the members alphabetically.
https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_member_order

**Comment by stefanseefeld** [comment]
I wasn't aware of that config option; thanks for pointing me to it !
(It would be nice if such a setting was available also at the level of individual `auto*` directives. It's only there that I was looking for such a setting, but didn't find any.)

**Comment by tk0miya** [comment]
You can also use `:member-order:` option for individual auto-directives :-)

**Comment by stefanseefeld** [comment]
Ah ! That's the one I was looking for, but for some reason missed. Thanks !
