### ISSUE TITLE
Ability to "inline" docs from another component instead of just linking to it

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#986]
Writing the IP address docs, it would be very handy to be able to "inline" snippets of docs rather than either duplicating them or make readers traverse a link maze.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/986
- Originally reported by: Nick Coghlan
- Originally created at: 2012-08-05T14:17:41.178

**Comment by shimizukawa** [comment]
_From Jon Waltman on 2012-08-12 09:38:34+00:00_

The {{{literalinclude}}} directive can be used to include the contents of an entire file or just specific parts using the {{{:lines:}}} or {{{:pyobject:}}} options.

http://sphinx.pocoo.org/markup/code.html?highlight=include#directive-literalinclude

The built-in {{{include}}} directive can be used to insert text that will be parsed as reStructuredText.

http://docutils.sourceforge.net/docs/ref/rst/directives.html#including-an-external-document-fragment

Do these work for you?

**Comment by shimizukawa** [comment]
_From Nick Coghlan on 2012-08-12 10:04:33+00:00_

Interesting (and useful!), but not quite what I'm after with this report. The cases that come up in the Python docs are of two forms:
1. Similar APIs where we want to share a :note: entry or a description of some parameters.
2. Classes that share a lot of attributes but are duck-typed rather than related by inheritance

In both cases, my current answer is to document in one place and then add a hyperlink as needed. This works OK in the HTML version, but is still not a good reader experience (the API docs are not self-contained, you have to go read another section). In a form without hyperlinks, it's a lot worse, since you can't readily get to the linked data.

I could probably cobble something together with the include directive and start-after and end-before, but I am hoping for something a bit more streamlined where anything that can be used to create a cross-reference can instead be included like doing the following to quote the full definition of a term in the glossary:

  .. literalinclude: :term:`some glossary entry`

The rules for figuring when the quoting _stops_ might be a little tricky, so it may need to be limited to links that target a clearly defined region, like a section heading or a glossary entry.

**Comment by shimizukawa** [comment]
_From Jon Waltman on 2012-08-12 10:34:11+00:00_

Yes, I see what you mean.

Another method might be to put your {{{:note:}}} or what have you in a separate file and then\
{{{.. include:: file-with-note}}} in the docstrings.

**Comment by tk0miya** [comment]
Nowadays, we have some 3rd party extensions like sphinx-jinja. I think this discussion is too old.
I'm closing this now. Please file a new issue if you still in the problem.
