### ISSUE TITLE
sphinx rendering double dash error

### ISSUE THREAD

**Issue by ownia** [sphinx-doc/sphinx#9871]
### Describe the bug

sphinx rendering double dash(a string of two hyphen-minus characters) to em dash, it will trigger errors while copy and paste.

### How to Reproduce

https://korg.docs.kernel.org/linuxdev.html
![Untitled Diagram drawio](https://user-images.githubusercontent.com/16909431/142589877-8ba0c537-5c76-4849-83d1-09ef167689d1.png)
https://korg.docs.kernel.org/_sources/linuxdev.rst.txt
![Untitled Diagram drawio (1)](https://user-images.githubusercontent.com/16909431/142589930-5a0e81e8-0c40-4f33-b7c9-60bae6d4eb83.png)

### Your project

https://korg.docs.kernel.org/index.html

### OS

Linux ownia 5.13.0-22-generic #22-Ubuntu SMP Fri Nov 5 13:21:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Python version

null

### Sphinx version

null

**Comment by jakobandersen** [comment]
I think this is working as intended as the snippet in question is written as "text". Try writing the command line as literal text by enclosing it in double `.
That is, something like this rst:
```rst
then we will check for linux-next for "``git log --author=[canonical address]``"
```

See also https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#inline-markup.

**Comment by tk0miya** [comment]
How about disabling the smartquotes feature? It replaces quotes and dashes to typographically correct entities (ex. straight quotes to curly quotes).
https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-smartquotes
