### ISSUE TITLE
Class namespace collision between autodoc signatures and docutils >= 0.17

### ISSUE THREAD

**Issue by ebolyen** [sphinx-doc/sphinx#9872]
### Describe the bug

In [docutils version 0.17](https://docutils.sourceforge.io/HISTORY.html#release-0-17-2021-04-03), the following change was made:

> `Use HTML text-level tags <small>, <s>, <q>, <dfn>, <var>, <samp>, <kbd>, <i>, <b>, <u>, <mark>, and <bdi> if a unique, matching class value is found in inline and literal elements. Use <ins> and <del> if a unique matching class value is found in inline, literal, or container elements. Use <small> for generated code line numbers.`

This appears to conflict with the signature line generated by autodoc, which adds Pygment classes to certain nodes:

https://github.com/sphinx-doc/sphinx/blob/ecee2335c561618800ce7562db890e68646ad020/sphinx/addnodes.py#L332-L334

**The result is a rather funky looking signature with an unusual DOM:**
![image](https://user-images.githubusercontent.com/3976804/142688671-8cc76ce0-1e6d-4945-a8eb-d79a9252d5f5.png)
![image](https://user-images.githubusercontent.com/3976804/142688740-49bdc3f1-5b21-42d8-ab17-6ef0340d4251.png)

---

**This can be fixed by changing the added class to something like `pygments-s`:**
![image](https://user-images.githubusercontent.com/3976804/142688885-1edfa72d-cf7d-4283-9b48-ead387b54553.png)
![image](https://user-images.githubusercontent.com/3976804/142690348-c1bf559d-6af7-415f-ad77-7a019cef3cff.png)

That said, the above probably won't play nicely with the many existing pygment stylesheets, so I don't really know the best approach.

### How to Reproduce

Use a `typing.Literal['foo']` in an autodoc'ed signature line.

### Your project

https://github.com/qiime2/qiime2/pull/610

### OS

Linux

### Python version

3.8

### Sphinx version

4.3

### Sphinx extensions

sphinx.ext.autodoc

### Extra tools

Firefox/Chrome

**Comment by ebolyen** [comment]
I should mention I also tried returning multiple classes like `["pygments", "s"]`, 
but all that earned me from docutils was a `<s class="pygments">...</s>`

**Comment by lorenzncode** [comment]
I also see this issue building docs for another project:

https://cadquery--916.org.readthedocs.build/en/916/classreference.html#cadquery.Workplane.mirror

![image](https://user-images.githubusercontent.com/16394272/142750736-6ad7732f-b17a-4143-ac82-069bfe8c7bdd.png)
