### ISSUE TITLE
References with apostrophe make smartypants fall over

### ISSUE THREAD

**Issue by shimizukawa** [sphinx-doc/sphinx#988]
Example

```
======
Object
======

...

===========
Other Topic
===========

Use the `Object`_'s foo to do bar. Any object's bar cab be used to do foo.
```

In the 1st case, SmartyPants falls over and writes "objects‘s" (closing single quote instead of apostrophe). In the 2nd case (no reference) it works and the result is "onjects’s", as it should be.

---
- Bitbucket: https://bitbucket.org/birkenfeld/sphinx/issue/988
- Originally reported by: [virtualritz](https://bitbucket.org/virtualritz)
- Originally created at: 2012-08-08T14:47:53.465

**Comment by shimizukawa** [comment]
_From Eric Knibbe on 2014-11-14 07:46:05+00:00_

A similar case can be seen with the text `The``<div>``'s CSS class`, where the apostrophe becomes an open single quote instead.

**Comment by tk0miya** [comment]
It seems this is already fixed at latest version. Closing.
