### ISSUE TITLE
How to include and preview external pdf documents inside rst menu <short description for the feature>

### ISSUE THREAD

**Issue by banyous** [sphinx-doc/sphinx#9887]
Hi. I built a separate section of my code documentation on Overleaf. I need to include this part into the sphinx documentation. Is there a way to include external PDF or Latex document inside Sphinx index page. 

I found this suggestion to include the file location inside the index.rst, but this only show the pdf as a donloadable file. I need it to be integratated into the sphinx theme as part of the content.

> :download:`A Detailed Example <file.pdf>`.

**Comment by tk0miya** [comment]
Why do you post such a question as a feature request? Please post a question to StackOverflow or sphinx-users group https://groups.google.com/g/sphinx-users
