### ISSUE TITLE
deprecate python 3.6 support

### ISSUE THREAD

**Issue by danieleades** [sphinx-doc/sphinx#9892]
any plans to drop support for python 3.6? it reaches end of life in 3 weeks

**Comment by tk0miya** [comment]
We use Ubuntu LTS as the base of supported versions. So python 3.6 will be dropped after Ubuntu 18.04 (bionic) will become EOL.

**Comment by astrojuanlu** [comment]
This is Sphinx policy: https://www.sphinx-doc.org/en/master/internals/release-process.html#python-version-support-policy

**Comment by danieleades** [comment]
> We use Ubuntu LTS as the base of supported versions. So python 3.6 will be dropped after Ubuntu 18.04 (bionic) will become EOL.

Oh wow, so another 7 years or so?

**Comment by danieleades** [comment]
> This is Sphinx policy: https://www.sphinx-doc.org/en/master/internals/release-process.html#python-version-support-policy

Ah, so not until 18.04 is EOL, just until the standard support period ends. Another 2 years. That seems more reasonable

**Comment by tk0miya** [comment]
Ah, sorry. My answer is not correct.
