### ISSUE TITLE
_pickle.PicklingError: Can't pickle <class 'CustomCommonMarkParser'>: attribute lookup CustomCommonMarkParser on builtins failed

### ISSUE THREAD

**Issue by CdeMills** [sphinx-doc/sphinx#9895]
### Describe the bug

Hello
I'm trying to build flang-12.0.1 from the Fedora-34 sources on a CentOS-8-Stream machine which does not have flang, and lacks the glibc version required by the Fedora binary package.
The build fails at the documentation stage; I tried avoiding the generation of the flang-doc.rpm but without success.

The last operation in rpmbuild is
/usr/bin/sphinx-build-3 -b html -d ~/rpmbuild/BUILD/flang-12.0.1.src/x86_64-redhat-linux-gnu/docs/_doctrees-flang-html -q -t builder-html ~/rpmbuild/BUILD/flang-12.0.1.src/docs ~/rpmbuild/BUILD/flang-12.0.1.src/x86_64-redhat-linux-gnu/docs/html

This fails with the error message:

Exception occurred:
  File "/usr/lib/python3.6/site-packages/sphinx/environment/__init__.py", line 148, in dump
    pickle.dump(env, f, pickle.HIGHEST_PROTOCOL)
_pickle.PicklingError: Can't pickle <class 'CustomCommonMarkParser'>: attribute lookup CustomCommonMarkParser on builtins failed
The full traceback has been saved in /var/tmp/sphinx-err-yvijpl6j.log, if you want to report the issue to the developers.

Any idea why ?
Regards
Pascal

### How to Reproduce

```
sudo dnf install python3-sphinx-1.7.6-2.el8.noarch # note: python3 is python36
cd   ~/rpmbuild; rpm -bb SPECS/flang.spec
```

### Expected behavior

generating flang-doc.rpm

### Your project

flang-12.0.1

### OS

CeontOS8 Stream on x86_64

### Python version

Python 3.6.8

### Sphinx version

1.7.6

### Additional context

```
# Sphinx version: 1.7.6
# Python version: 3.6.8 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10.1
# Last messages:
#   reading sources... [100%] index
#   
#   
#   
#   looking for now-outdated files...
#   
#   none found
#   
#   pickling environment...
#   
# Loaded extensions:
#   alabaster (0.7.9) from /usr/lib/python3.6/site-packages/alabaster/__init__.p
y
#   sphinx.ext.todo (1.7.6) from /usr/lib/python3.6/site-packages/sphinx/ext/tod
o.py
#   sphinx.ext.mathjax (1.7.6) from /usr/lib/python3.6/site-packages/sphinx/ext/
mathjax.py
#   sphinx.ext.intersphinx (1.7.6) from /usr/lib/python3.6/site-packages/sphinx/
ext/intersphinx.py
[padupuis@aquilaris]BUILD/flang-12.0.1.src/x86_64-redhat-linux-gnu% more /var/tmp/sphinx-err-yvijpl6j.log
# Sphinx version: 1.7.6
# Python version: 3.6.8 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10.1
# Last messages:
#   reading sources... [100%] index
#   
#   
#   
#   looking for now-outdated files...
#   
#   none found
#   
#   pickling environment...
#   
# Loaded extensions:
#   alabaster (0.7.9) from /usr/lib/python3.6/site-packages/alabaster/__init__.py
#   sphinx.ext.todo (1.7.6) from /usr/lib/python3.6/site-packages/sphinx/ext/todo.py
#   sphinx.ext.mathjax (1.7.6) from /usr/lib/python3.6/site-packages/sphinx/ext/mathjax.py
#   sphinx.ext.intersphinx (1.7.6) from /usr/lib/python3.6/site-packages/sphinx/ext/intersphinx.py
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/sphinx/cmdline.py", line 304, in main
    app.build(args.force_all, filenames)
  File "/usr/lib/python3.6/site-packages/sphinx/application.py", line 331, in build
    self.builder.build_update()
  File "/usr/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 342, in build_update
    'out of date' % len(to_build))
  File "/usr/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 371, in build
    self.env.topickle(path.join(self.doctreedir, ENV_PICKLE_FILENAME))
  File "/usr/lib/python3.6/site-packages/sphinx/environment/__init__.py", line 164, in topickle
    self.dump(self, f)
  File "/usr/lib/python3.6/site-packages/sphinx/environment/__init__.py", line 148, in dump
    pickle.dump(env, f, pickle.HIGHEST_PROTOCOL)
_pickle.PicklingError: Can't pickle <class 'CustomCommonMarkParser'>: attribute lookup CustomCommonMarkParser on builtins failed
```

**Comment by astrojuanlu** [comment]
I see that flang is using a `CustomCommonMarkParser`:

https://github.com/llvm/llvm-project/blob/f1ba48d50800e3d39027af9e5dff56f35ac21ce4/flang/docs/conf.py#L23-L27

I wonder if the problem is similar to #6751, and would be solved by flang moving their `CustomCommonMarkParser` outside of `conf.py`. However, I see that the docs are built online: https://flang.llvm.org/docs/ (skip SSL error).

I am not sure if this is because of the super old Sphinx version, but if it's a problem in recommonmark, unfortunately it's not maintained anymore and users are encouraged to migrate to MyST-Parser: https://github.com/readthedocs/recommonmark/issues/221

**Comment by tk0miya** [comment]
Adding a source parser via `source_parsers` was deprecated since v1.8. So only I can say is upgrading your Sphinx. It seems flang project already supports a new standard configuration option:
https://github.com/llvm/llvm-project/blob/f1ba48d50800e3d39027af9e5dff56f35ac21ce4/flang/docs/conf.py#L51-L53
