### ISSUE TITLE
Compact mode for things like :option: or :function:

### ISSUE THREAD

**Issue by marxin** [sphinx-doc/sphinx#9897]
Sometimes, one wants to list multiple options, functions or simple items and document them after:

```rst
Multiple
====

Arithmetic functions
^^^^^^^^^^^^^^^^^^^^

.. function:: _Decimal32 __dpd_addsd3 (_Decimal32 a, _Decimal32 b)
.. function:: _Decimal32 __bid_addsd3 (_Decimal32 a, _Decimal32 b)
.. function:: _Decimal64 __dpd_adddd3 (_Decimal64 a, _Decimal64 b)
.. function:: _Decimal64 __bid_adddd3 (_Decimal64 a, _Decimal64 b)
.. function:: _Decimal128 __dpd_addtd3 (_Decimal128 a, _Decimal128 b)
.. function:: _Decimal128 __bid_addtd3 (_Decimal128 a, _Decimal128 b)

  These functions return the sum of :samp:`{a}` and :samp:`{b}`.

Names:
^^^^^^

* Tools/packages necessary for building GCC
=========================================

autoconf version 2.69
GNU m4 version 1.4.6 (or later)
  Necessary when modifying :samp:`configure.ac`, :samp:`aclocal.m4`, etc.
  to regenerate :samp:`configure` and :samp:`config.in` files.

git (any version)
SSH (any version)
Foobar (all versions)

  Necessary to access the source repository.  Public releases and weekly
  snapshots of the development sources are also available via HTTPS.

.. option:: -mmmx
.. option:: -msse
.. option:: -msse2

  These switches enable the use of instructions in the MMX, SSE,
  SSE2, ... 
```

Is there a way how to compact the definitions? As seen, there's quite some vertical spacing among them (and simple items are separated by space).
@jakobandersen 

![Screenshot from 2021-11-27 16-26-58](https://user-images.githubusercontent.com/2658545/143687275-19fb90a2-38cb-4348-9105-524a448af3a5.png)

**Comment by jakobandersen** [comment]
Yes, there is a way: you can have multiple declarations in one directive. E.g.,
```rst
.. function:: void foo()
              void bar()
```
If you have a declaration the in the source span multiple lines, then you can escape the line break. E.g.,
```rst
.. function:: template<typename T> \
              void foo()
              template<typename T> \
              void bar()
```
Similarly for the ``option`` directive.

**Comment by marxin** [comment]
Oh, great! That works!

**Comment by marxin** [comment]
> ```
> 
> git (any version)
> SSH (any version)
> Foobar (all versions)
> 
>   Necessary to access the source repository.  Public releases and weekly
>   snapshots of the development sources are also available via HTTPS.
> ```

Is there anything I can do here better (except use of unnumbered lists)?

**Comment by jakobandersen** [comment]
Hmm, how about the "dual" version:
```rst
Necessary to access the source repository:

* Git (any version)
* SSH (any version)
* Foobar (all versions)

Public releases and weekly snapshots of the development sources are also available via HTTPS.
```

**Comment by marxin** [comment]
> Hmm, how about the "dual" version:

Yes, that's what I shall use.
