### ISSUE TITLE
Do not break lines within :option: references

### ISSUE THREAD

**Issue by marxin** [sphinx-doc/sphinx#9909]
Something one needs to do a listing of options and the line breaks does not look good.

![Screenshot from 2021-11-29 10-44-59](https://user-images.githubusercontent.com/2658545/143844957-e269aa12-aa86-4cc8-a906-573fb4fef667.png)

Is it possible to mark the `:option:` references as non-breaking?

**Comment by marxin** [comment]
Note I'm using RTD theme so I'm not sure what's the correct place for reporting the issue.
Solution can be as simple as `white-space: nowrap` for `.literal` ?

**Comment by astrojuanlu** [comment]
If it happens with other themes, the issue could be raised against the HTML generated by Sphinx. But probably dealing with this in the theme would be more appropriate. Although some custom css fixes the issue, I assume?

**Comment by marxin** [comment]
Yep. The following helps:
```css
.literal {
  white-space: nowrap !important;
}
```
