### ISSUE TITLE
Multi-line .. function:: directive has big vertical spacing in Latexpdf

### ISSUE THREAD

**Issue by marxin** [sphinx-doc/sphinx#9924]
### Describe the bug

```rst
.. function:: _Decimal32 __dpd_addsd3 (_Decimal32 a, _Decimal32 b)
              _Decimal32 __bid_addsd3 (_Decimal32 a, _Decimal32 b)
              _Decimal64 __dpd_adddd3 (_Decimal64 a, _Decimal64 b)
              _Decimal64 __bid_adddd3 (_Decimal64 a, _Decimal64 b)
              _Decimal128 __dpd_addtd3 (_Decimal128 a, _Decimal128 b)
              _Decimal128 __bid_addtd3 (_Decimal128 a, _Decimal128 b)
```

Is wrongly rendered in Latexpdf:
![Screenshot from 2021-12-02 10-46-47](https://user-images.githubusercontent.com/2658545/144398529-1a826346-af9b-4603-975e-524c1ee89ab0.png)

While it correctly works for `.. option` directive:

```rst
.. option:: -mmmx
            -msse
            -msse2
```

![Screenshot from 2021-12-02 10-47-03](https://user-images.githubusercontent.com/2658545/144398614-3982fac8-0203-4d71-a8ae-78209c5a0749.png)

### How to Reproduce

`make latexpdf` for the provided snippet

### Your project

snippet provided

### OS

Linux

### Python version

3.8

### Sphinx version

4.3.0

**Comment by jakobandersen** [comment]
I don't immediately know how to fix it, but as far as I can see the reason for the difference is that the C++ domain outputs functions as multi-line declarations (e.g., for templates), and the Latex styles have some more spacing.
Perhaps @jfbu may have time at some point to look into this. I tried with some Python declarations and there the spacing seems to be too little:
```rst
.. py:function:: __dpd_addsd3 (a, b)
                 __bid_addsd3 (a, b)
                 __dpd_adddd3 (a, b)
                 __bid_adddd3 (a, b)
                 __dpd_addtd3 (a, b)
                 __bid_addtd3 (a, b)

    something

.. cpp:function:: _Decimal32 __dpd_addsd3 (_Decimal32 a, _Decimal32 b)
                  _Decimal32 __bid_addsd3 (_Decimal32 a, _Decimal32 b)
                  _Decimal64 __dpd_adddd3 (_Decimal64 a, _Decimal64 b)
                  _Decimal64 __bid_adddd3 (_Decimal64 a, _Decimal64 b)
                  _Decimal128 __dpd_addtd3 (_Decimal128 a, _Decimal128 b)
                  _Decimal128 __bid_addtd3 (_Decimal128 a, _Decimal128 b)

    something

.. cpp:function:: template<typename T> \
                  _Decimal32 __dpd_addsd3 (_Decimal32 a, _Decimal32 b)
                  template<typename T> \
                  _Decimal32 __bid_addsd3 (_Decimal32 a, _Decimal32 b)
                  template<typename T> \
                  _Decimal64 __dpd_adddd3 (_Decimal64 a, _Decimal64 b)
                  template<typename T> \
                  _Decimal64 __bid_adddd3 (_Decimal64 a, _Decimal64 b)
                  template<typename T> \
                  _Decimal128 __dpd_addtd3 (_Decimal128 a, _Decimal128 b)
                  template<typename T> \
                  _Decimal128 __bid_addtd3 (_Decimal128 a, _Decimal128 b)

    something


.. option:: -mmmx
            -msse
            -msse2

    something
```

**Comment by jfbu** [comment]
The too large vertical spacing from C++ function declarations originate in each signature generating a `\pysigstartmultiline/\pysigstopmultiline` pair in LaTeX mark-up from LaTeX writer output: https://github.com/sphinx-doc/sphinx/blob/edd14783f3cc6222066fd63efbe28c2728617e18/sphinx/writers/latex.py#L734-L752

@jakobandersen is this something that could be modified in C++ domain compared to Python domain? Perhaps the `is_multiline` attributed is omitted. I did not look, so far.

The too small spacing in Python domain is something else for which I will make a bugfix PR soon.

**Comment by jakobandersen** [comment]
> @jakobandersen is this something that could be modified in C++ domain compared to Python domain? Perhaps the `is_multiline` attributed is omitted. I did not look, so far.
> 
> The too small spacing in Python domain is something else for which I will make a bugfix PR soon.

The ``is_multiline`` is needed to add another level of nesting to the document structure.
At the highest level you have ``<desc>``. E.g.,
```rst
.. function:: sig1

   Content1

.. function:: sig2

   Content2
```
creates something like the following (lots of inner details omitted)
```xml
<desc>
   <desc_signature>sig1</desc_signature>
   <desc_content>Content1</desc_content>
</desc>
<desc>
   <desc_signature>sig2</desc_signature>
   <desc_content>Content2</desc_content>
</desc>
```

At the next level you have ``<desc_signature>`` for when multiple declarations share a description. E.g.,
```rst
.. function:: sig1
              sig2

   Content1and2
```
creates something like
```xml
<desc>
   <desc_signature>sig1</desc_signature>
   <desc_signature>sig2</desc_signature>
   <desc_content>Content1and2</desc_content>
</desc>
```
As default a ``<desc_signature>`` is rendered as a single line.

The third level is optional (for backwards compatibility). If a ``<desc_signature>`` has ``is_multiline=True``, then it has one or more children which are all ``<desc_signature_line>``. Each of those are rendered as a single line.
E.g.,
```rst
.. cpp:function:: template<typename T> \
                  void f1()
                  template<typename T> \
                  void f2()

   Content1and2
```
creates something like
```xml
<desc>
   <desc_signature is_multiline=True>
      <desc_signature_line>"template<typename T>"</desc_signature_line>
      <desc_signature_line>"void f1()"</desc_signature_line>
   </desc_signature>
   <desc_signature is_multiline=True>
      <desc_signature_line>"template<typename T>"</desc_signature_line>
      <desc_signature_line>"void f2()"</desc_signature_line>
   </desc_signature>
   <desc_content>Content1and2</desc_content>
</desc>
```
So I guess the spacing should be:
- between ``<desc>`` nodes: moderate vertical gap
- between ``<desc_signature>`` nodes (no matter ``is_multiline``): a bit of extra vertical gap
- between ``<desc_signature_line>`` nodes:  no vertical gap, i.e., single line spacing

**Comment by jfbu** [comment]
I should have said more explicitly that the problem on latex side is that rather than a single `\pysigstartmultiline/\pysigstopmultiline` pair there is one for each line. With a single pair and all signatures lines in-between the spacing is correct in pdf output.

**Comment by marxin** [comment]
@jfbu Are planning working on that, I noticed the C++ domain is still affected? Thanks.
