### ISSUE TITLE
Latex: do not allow splitting for :option: roles 

### ISSUE THREAD

**Issue by marxin** [sphinx-doc/sphinx#9925]
### Describe the bug

For:

```rst
Use these options: :option:`-Wno-shift-overflow3` :option:`-Wno-shift-overflow3` :option:`-Wno-shift-overflow3` :option:`-Wno-shift-overflow3` :option:`-Wno-shift-overflow3` :option:`-Wno-shift-overflow3` :option:`-Wno-shift-overflow3` :option:`-Wno-shift-overflow3` :option:`-Wno-shift-overflow3` :option:`-Wno-shift-overflow3` :option:`-Wno-shift-overflow3` :option:`-Wno-shift-overflow3` :option:`-Wno-shift-overflow3` :option:`-Wno-shift-overflow3`.
```

I don't want to allow splitting of the options:
![Screenshot from 2021-12-02 11-16-21](https://user-images.githubusercontent.com/2658545/144402801-2ecff288-1505-4e4f-84b6-182973464212.png)

### How to Reproduce

Build the snippet

### Your project

Build the snippet

### OS

Linux

### Python version

3.8

### Sphinx version

4.3.0

**Comment by marxin** [comment]
HTML counter-part was #9909. CCing @jfbu.

**Comment by jfbu** [comment]
What is LaTeX engine, pdflatex or xelatex? 

Update: surely xelatex, as I reproduced it with it.

With the default setting I can not reproduce:

![Capture d’écran 2021-12-06 à 14 08 25](https://user-images.githubusercontent.com/2589111/144851579-710b3475-97d8-4a3a-a64a-16aadeebc0ca.png)

from

```
xxxxxxxxxxxxxxx 123456 123456 123456 12 Use these options: :option:`-Wno-shift-overflow3` :option:`-Wno-shift-overflow3` :option:`-Wno-shift-overflow3` :option:`-Wno-shift-overflow3` :option:`-Wno-shift-overflow3` :option:`-Wno-shift-overflow3` :option:`-Wno-shift-overflow3` :option:`-Wno-shift-overflow3` :option:`-Wno-shift-overflow3` :option:`-Wno-shift-overflow3` :option:`-Wno-shift-overflow3` :option:`-Wno-shift-overflow3` :option:`-Wno-shift-overflow3` :option:`-Wno-shift-overflow3`.

xxxxxxxxxxxxxxx 123456 123456 123456 1 Use these options: :option:`-Wno-shift-overflow3` :option:`-Wno-shift-overflow3` :option:`-Wno-shift-overflow3` :option:`-Wno-shift-overflow3` :option:`-Wno-shift-overflow3` :option:`-Wno-shift-overflow3` :option:`-Wno-shift-overflow3` :option:`-Wno-shift-overflow3` :option:`-Wno-shift-overflow3` :option:`-Wno-shift-overflow3` :option:`-Wno-shift-overflow3` :option:`-Wno-shift-overflow3` :option:`-Wno-shift-overflow3` :option:`-Wno-shift-overflow3`.
```

and default settings (in particular letter size paper).

Could you post the actual LaTeX mark-up as seen in the `.tex` file ? At my locale it involves:
```latex
{\hyperref[\detokenize{index:cmdoption-11}]{\sphinxcrossref{\sphinxcode{\sphinxupquote{\sphinxhyphen{}Wno\sphinxhyphen{}shift\sphinxhyphen{}overflow3}}}}}
```

It appears that `\sphinxcode` which does by default `\texttt` (monospace font) is what prevents linebreaks.

*But*, for xelatex, fonts behave differently. Try this in conf.py

```
latex_elements = {
    'preamble': r'\def\sphinxhyphen{\mbox{-}}',
}
```

The actual bug here may be that the linebreaks were not observed with `pdflatex`: the latex code comments say https://github.com/sphinx-doc/sphinx/blob/edd14783f3cc6222066fd63efbe28c2728617e18/sphinx/texinputs/sphinxlatexstyletext.sty#L77-L80 so it seems linebreaks were expected. But the `\texttt{}` with `pdflatex` prevents them...

**Comment by jfbu** [comment]
Memo: this issue also has to do with the

```
\defaultfontfeatures[\rmfamily,\sffamily,\ttfamily]{}
```

which was added at #6888 to the latex preamble when using `xelatex` engine in order to fix #6886.

Without it `xelatex` like `pdflatex` would not have linebreaks after dashes when using monospace font family. But this addition fixed the #6886 (and see also related #6890) problems with curly quotes .

**Comment by marxin** [comment]
> Update: surely xelatex, as I reproduced it with it.

Yes, I use `latex_engine = 'xelatex'`.

**Comment by marxin** [comment]
> _But_, for xelatex, fonts behave differently. Try this in conf.py
> 
> ```
> latex_elements = {
>     'preamble': r'\def\sphinxhyphen{\mbox{-}}',
> }
> ```

I can confirm this fixes the problem! You can build my project with:
```
git clone https://github.com/marxin/texi2rst-generated
cd texi2rst-generated/sphinx/demo
make latexpdf
```

**Comment by marxin** [comment]
> Could you post the actual LaTeX mark-up as seen in the `.tex` file ? At my locale it involves:

```tex
Use these options: {\hyperref[\detokenize{demo:cmdoption-Wno-shift-overflow3}]{\sphinxcrossref{\sphinxcode{\sphinxupquote{\sphinxhyphen{}Wno\sphinxhyphen{}shift\sphinxhyphen{}overflow3}}}}} {\hyperref[\detokenize{demo:cmdoption-Wno-shift-overflow3}]{\sphinxcrossref{\sphinxcode{\sphinxupquote{\sphinxhyphen{}Wno\sphinxhyphen{}shift\sphinxhyphen{}overflow3}}}}} {\hyperref[\detokenize{demo:cmdoption-Wno-shift-overflow3}]{\sphinxcrossref{\sphinxcode{\sphinxupquote{\sphinxhyphen{}Wno\sphinxhyphen{}shift\sphinxhyphen{}overflow3}}}}} {\hyperref[\detokenize{demo:cmdoption-Wno-shift-overflow3}]{\sphinxcrossref{\sphinxcode{\sphinxupquote{\sphinxhyphen{}Wno\sphinxhyphen{}shift\sphinxhyphen{}overflow3}}}}} {\hyperref[\detokenize{demo:cmdoption-Wno-shift-overflow3}]{\sphinxcrossref{\sphinxcode{\sphinxupquote{\sphinxhyphen{}Wno\sphinxhyphen{}shift\sphinxhyphen{}overflow3}}}}} {\hyperref[\detokenize{demo:cmdoption-Wno-shift-overflow3}]{\sphinxcrossref{\sphinxcode{\sphinxupquote{\sphinxhyphen{}Wno\sphinxhyphen{}shift\sphinxhyphen{}overflow3}}}}} {\hyperref[\detokenize{demo:cmdoption-Wno-shift-overflow3}]{\sphinxcrossref{\sphinxcode{\sphinxupquote{\sphinxhyphen{}Wno\sphinxhyphen{}shift\sphinxhyphen{}overflow3}}}}} {\hyperref[\detokenize{demo:cmdoption-Wno-shift-overflow3}]{\sphinxcrossref{\sphinxcode{\sphinxupquote{\sphinxhyphen{}Wno\sphinxhyphen{}shift\sphinxhyphen{}overflow3}}}}} {\hyperref[\detokenize{demo:cmdoption-Wno-shift-overflow3}]{\sphinxcrossref{\sphinxcode{\sphinxupquote{\sphinxhyphen{}Wno\sphinxhyphen{}shift\sphinxhyphen{}overflow3}}}}} {\hyperref[\detokenize{demo:cmdoption-Wno-shift-overflow3}]{\sphinxcrossref{\sphinxcode{\sphinxupquote{\sphinxhyphen{}Wno\sphinxhyphen{}shift\sphinxhyphen{}overflow3}}}}} {\hyperref[\detokenize{demo:cmdoption-Wno-shift-overflow3}]{\sphinxcrossref{\sphinxcode{\sphinxupquote{\sphinxhyphen{}Wno\sphinxhyphen{}shift\sphinxhyphen{}overflow3}}}}} {\hyperref[\detokenize{demo:cmdoption-Wno-shift-overflow3}]{\sphinxcrossref{\sphinxcode{\sphinxupquote{\sphinxhyphen{}Wno\sphinxhyphen{}shift\sphinxhyphen{}overflow3}}}}} {\hyperref[\detokenize{demo:cmdoption-Wno-shift-overflow3}]{\sphinxcrossref{\sphinxcode{\sphinxupquote{\sphinxhyphen{}Wno\sphinxhyphen{}shift\sphinxhyphen{}overflow3}}}}} {\hyperref[\detokenize{demo:cmdoption-Wno-shift-overflow3}]{\sphinxcrossref{\sphinxcode{\sphinxupquote{\sphinxhyphen{}Wno\sphinxhyphen{}shift\sphinxhyphen{}overflow3}}}}}.
```

**Comment by jfbu** [comment]
> > Could you post the actual LaTeX mark-up as seen in the `.tex` file ? At my locale it involves:
> 
> ```
> Use these options: {\hyperref[\detokenize{demo:cmdoption-Wno-shift-overflow3}]{\sphinxcrossref{\sphinxcode{\sphinxupquote{\sphinxhyphen{}Wno\sphinxhyphen{}shift\sphinxhyphen{}overflow3}}}}} {\hyperref[\detokenize{demo:cmdoption-Wno-shift-overflow3}]{\sphinxcrossref{\sphinxcode{\sphinxupquote{\sphinxhyphen{}Wno\sphinxhyphen{}shift\sphinxhyphen{}overflow3}}}}} etc...
> ```

Ok thanks for confirmation this is exactly same mark-up as I observed at my locale (i was in the dark for a while was asking for more details).

The root cause is the diverging behaviour of `xelatex` compared to `pdflatex`.

This appears as an after-effect of the fact it was configured to not apply TeX ligatures such as replacing `--` by a long dash.

I am not sure how to proceed now, because, although possibly not good for options, breaking at `-` in literals was actually intended. But it did not happen with `pdflatex`... (in this case of inline literals, when the `-` is escaped by mark-up into `\sphinxhyphen`  which is not the case for code-blocks or parsed-literals)

**Comment by marxin** [comment]
> I am not sure how to proceed now, because, although possibly not good for options, breaking at `-` in literals was actually intended.

I see, makes sense. What about emitting something like `\sphinx_never_break_hyphen` within `:option:` directives that will never be broken?

**Comment by jfbu** [comment]
> I see, makes sense. What about emitting something like `\sphinx_never_break_hyphen` within `:option:` directives that will never be broken?

`:option:` uses same latex mark-up as for inline literals.  I will think about situation...

**Comment by marxin** [comment]
Btw. I've just tried the `xelatex` with the `'preamble': r'\def\sphinxhyphen{\mbox{-}}'` and the result is not good for:

```sphinx
*Diagnostic Message Formatting Options*

  See :ref:`diagnostic-message-formatting-options`.

  :option:`-fmessage-length`:samp:`={n}`
  :option:`-fdiagnostics-plain-output`
  :option:`-fdiagnostics-show-location`:samp:`=[once|every-line]`
  :option:`-fdiagnostics-color`:samp:`=[auto|never|always]`
  :option:`-fdiagnostics-urls`:samp:`=[auto|never|always]`
  :option:`-fdiagnostics-format`:samp:`=[text|json]`
  :option:`-fno-diagnostics-show-option`  :option:`-fno-diagnostics-show-caret`
  :option:`-fno-diagnostics-show-labels`  :option:`-fno-diagnostics-show-line-numbers`
  :option:`-fno-diagnostics-show-cwe`
  :option:`-fdiagnostics-minimum-margin-width`:samp:`={width}`
  :option:`-fdiagnostics-parseable-fixits`  :option:`-fdiagnostics-generate-patch`
  :option:`-fdiagnostics-show-template-tree`  :option:`-fno-elide-type`
  :option:`-fdiagnostics-path-format`:samp:`=[none|separate-events|inline-events]`
  :option:`-fdiagnostics-show-path-depths`
  :option:`-fno-show-column`
  :option:`-fdiagnostics-column-unit`:samp:`=[display|byte]`
  :option:`-fdiagnostics-column-origin`:samp:`={origin}`
  :option:`-fdiagnostics-escape-format`:samp:`=[unicode|bytes]`
```

![Screenshot from 2021-12-06 17-13-08](https://user-images.githubusercontent.com/2658545/144881588-86be19fb-4949-4b50-8394-57cc113f93ba.png)

While `pdflatex` looks fine:
![Screenshot from 2021-12-06 17-12-21](https://user-images.githubusercontent.com/2658545/144881612-60019442-fdb8-44b7-9ead-3182e05a9f8b.png)

**Comment by jfbu** [comment]
From quick look this is simply due to xelatex font being wider. In both cases some lines are overfull with TeX going into the margin because it does not know how to break things.  Also it spreads white space in the line to try to fill it which explains the layout of non-overfull lines.

Perhaps you can try to add this to `latex_elements['preamble']` as well
```
\defaultfontfeatures[\ttfamily]{ Scale = 0.9 }
```
or some other factor. 

But this will not fix the fact that TeX which is conceived to typeset natural language has no a priori knowledge of breaking overlong lines.

Or try to find another font, the default is doing
```
\setmonofont{FreeMono}[
  Extension      = .otf,
  UprightFont    = *,
  ItalicFont     = *Oblique,
  BoldFont       = *Bold,
  BoldItalicFont = *BoldOblique,
]
```

**Comment by jfbu** [comment]
> But this will not fix the fact that TeX which is conceived to typeset natural language has no a priori knowledge of breaking overlong lines.

I mean overlong lines with symbols such as `[`, `|`, `]` or non natural words like long option names when the linebreaks at `-`  have been prohibited by some mechanism.

**Comment by jakobandersen** [comment]
> > I see, makes sense. What about emitting something like `\sphinx_never_break_hyphen` within `:option:` directives that will never be broken?
> 
> `:option:` uses same latex mark-up as for inline literals. I will think about situation...

I think it is fine to prevent line-breaking in literals. A similar change was recently made for HTML (https://github.com/sphinx-doc/sphinx/pull/9929), so that would be consistent.

**Comment by marxin** [comment]
Looking more at the `pdflatex` output, even that is not ideal:
![Screenshot from 2021-12-06 17-44-02](https://user-images.githubusercontent.com/2658545/144886508-69b8b38f-2af2-4c21-ab70-4517788abed6.png)

Please look at the 4th line from the bottom. So I do worry I'll have to place there some equivalent to `@gol` that we use in Texinfo right now:

```
...
@item Warning Options
@xref{Warning Options,,Options to Request or Suppress Warnings}.
@gccoptlist{-fsyntax-only  -fmax-errors=@var{n}  -Wpedantic @gol
-pedantic-errors @gol
-w  -Wextra  -Wall  -Wabi=@var{n} @gol
-Waddress  -Wno-address-of-packed-member  -Waggregate-return @gol
-Walloc-size-larger-than=@var{byte-size}  -Walloc-zero @gol
-Walloca  -Walloca-larger-than=@var{byte-size} @gol
-Wno-aggressive-loop-optimizations @gol
-Warith-conversion @gol
-Warray-bounds  -Warray-bounds=@var{n}  -Warray-compare @gol
-Wno-attributes  -Wattribute-alias=@var{n} -Wno-attribute-alias @gol
...

**Comment by jfbu** [comment]
> I think it is fine to prevent line-breaking in literals. A similar change was recently made for HTML (#9929), so that would be consistent.

Thanks for tip, yes I will make PR. In retrospect line splitting was already prohibited in inline literals and parsed literals at dashes, with `pdflatex`, so I will base the PR on 4.3.x branch as a bugfix for xelatex (I hesitated as #9929 was merged into 4.x branch). Also because I made PRs on 4.3.x related to latex recently, but I hesitate still now which branch is better target.

**Comment by jfbu** [comment]
@marxin I guess having each ``:option:`optionname` `` in its own paragraph is not an option (sic) due to vertical spacing? you can not use a list for similar reason?

**Comment by jfbu** [comment]
```rest
.. |gol| raw:: latex

               \\


Use these options: :option:`-Wno-shift-overflow3`\ |gol| :option:`-Wno-shift-overflow3`\ |gol| :option:`-Wno-shift-overflow3`\ |gol| :option:`-Wno-shift-overflow3`\ |gol| :option:`-Wno-shift-overflow3`\ |gol| :option:`-Wno-shift-overflow3`\ |gol| :option:`-Wno-shift-overflow3`\ |gol| :option:`-Wno-shift-overflow3`\ |gol| :option:`-Wno-shift-overflow3`\ |gol| :option:`-Wno-shift-overflow3`\ |gol| :option:`-Wno-shift-overflow3`\ |gol| :option:`-Wno-shift-overflow3`\ |gol| :option:`-Wno-shift-overflow3`\ |gol| :option:`-Wno-shift-overflow3`.
```

**Comment by marxin** [comment]
> @marxin I guess having each `` :option:`optionname `` in its own paragraph is not an option (sic) due to vertical spacing? you can not use a list for similar reason?

Exactly, that's too much of the vertical spacing.

**Comment by marxin** [comment]
> ```
> .. |gol| raw:: latex
> 
>                \\
> 
> 
> Use these options: :option:`-Wno-shift-overflow3`\ |gol| :option:`-Wno-shift-overflow3`\ |gol| :option:`-Wno-shift-overflow3`\ |gol| :option:`-Wno-shift-overflow3`\ |gol| :option:`-Wno-shift-overflow3`\ |gol| :option:`-Wno-shift-overflow3`\ |gol| :option:`-Wno-shift-overflow3`\ |gol| :option:`-Wno-shift-overflow3`\ |gol| :option:`-Wno-shift-overflow3`\ |gol| :option:`-Wno-shift-overflow3`\ |gol| :option:`-Wno-shift-overflow3`\ |gol| :option:`-Wno-shift-overflow3`\ |gol| :option:`-Wno-shift-overflow3`\ |gol| :option:`-Wno-shift-overflow3`.
> ```

Great, that works perfectly, I'm going to use it very likely (note one does not need the `\` before `|gol|`).
Thanks for help!

**Comment by marxin** [comment]
Thanks for the fix. One more question: how difficult would it be to add a new directive:

```rst
..optionlisting:

  :option:`-fdiagnostics-plain-output`
  :option:`-fdiagnostics-show-location`:samp:`=[once|every-line]`
  :option:`-fdiagnostics-color`:samp:`=[auto|never|always]`
```

That would emit `|gol|` at the end of each line? Instead of manually placing the `|gol|` at the end of every line.
Thank you.

**Comment by jfbu** [comment]
> Thanks for the fix. One more question: how difficult would it be to add a new directive:

please raise a new issue/feature request for discussion

**Comment by marxin** [comment]
> please raise a new issue/feature request for discussion

Sure, done in #9995.
