### ISSUE TITLE
TypeError when generating pdf for sphinx-quickstart

### ISSUE THREAD

**Issue by guitsy** [sphinx-doc/sphinx#9950]
### Describe the bug

Exception occurred:
  File "c:\users\msd\documents\csa\projekte\sphinx_to\.venv\lib\site-packages\rst2pdf\pdfbuilder.py", line 416, in get_outdated_docs
    targetname = self.env.doc2path(docname, self.outdir, self.out_suffix)       
TypeError: BuildEnvironment.doc2path() takes from 2 to 3 positional arguments but 4 were given

When checking the mentioned file pdfbuilder.py:416 only docname is needed as on line 422?

### How to Reproduce

```
$ git clone https://github.com/.../some_project
$ cd some_project
$ pip install -r requirements.txt
$ cd docs
$ make html SPHINXOPTS="-D language=de"
$ # open _build/html/index and see bla bla
```

### Your project

sphinx-quickstart

### OS

Windows10

### Python version

3.10.0a5

### Sphinx version

latest

**Comment by tk0miya** [comment]
The 3rd argument was deprecated since v2.0 and removed since v4.0.
Unfortunately, rst2pdf does not support Sphinx-4.x yet (see https://github.com/rst2pdf/rst2pdf/pull/1020).
