### ISSUE TITLE
No useful error for missing `/usr/bin/python` in `make html`

### ISSUE THREAD

**Issue by leander-j** [sphinx-doc/sphinx#9951]
### Describe the bug

Running `make html` only yields (after creating `_api` files)

```
Sphinx-apidoc is done, building directories
sphinx-build -b html -v -d _build/doctrees  -E -a . _build/html
make: sphinx-build: No such file or directory
make: *** [Makefile:68: html] Error 127
```

Only after running `sphinx-quickstart` did I find the error was the missing `/usr/bin/python` file.

Also the location of a log file was not indicated.

### How to Reproduce

```
$ git clone https://github.com/pik-copan/pycopancore
$ git checkout imitation_component
$ # somehow temporarily remove or rename your `/usr/bin/python` file
$ cd docs
$ make html
```
Should work in any project so feel free to skip the first 2 steps.

### Expected behavior

The error should include the path to the missing file or directory.

### Your project

https://github.com/pik-copan/pycopancore/tree/imitation_component

### OS

Debian 11

### Python version

3.9.2

### Sphinx version

3.4.3

**Comment by tk0miya** [comment]
I guess the message was emitted from your shell (bash, zsh, and so on). It's difficult to change the message from Sphinx side.

**Comment by leander-j** [comment]
Yes, it's a bash output. Since the complete error can be found by running `sphinx-build`, I think it's not tragic if no solution can be found from Sphinx side
