### ISSUE TITLE
html kbd KeyboardTransform does not work when using the dirhtml builder

### ISSUE THREAD

**Issue by page-down** [sphinx-doc/sphinx#9961]
### Describe the bug

If you use `sphinx.builders.dirhtml.DirectoryHTMLBuilder` to generate a document, then `:kbd:` will not use `KeyboardTransform` to do the transformation. There are other html-based builders that are affected.

sphinx/builders/html/transforms.py
```python
class KeyboardTransform(SphinxPostTransform):
    # ...
    builders = ('html',)
```

Is it possible to enable `:kbd:` conversion support for other HTML-based builders? Thanks.

### How to Reproduce

```
$ make dirhtml
```

### Expected behavior

```rst
:kbd:`ctrl+s`
```

```html
<kbd>
    <kbd>ctrl</kbd>+<kbd>s</kbd>
</kbd>
```

### Your project

n/a

### OS

Linux

### Python version

3.9

### Sphinx version

4.3.1

### Additional context

Feature Request # 7530
[Convert :kbd: to nested < kbd > HTML elements](https://github.com/sphinx-doc/sphinx/issues/7530)

**Comment by tk0miya** [comment]
Thank you for reporting. I did not notice that. I'll fix it soon.
