### ISSUE TITLE
[texinfo writer] `@definfoenclose` is discouraged and raises warnings

### ISSUE THREAD

**Issue by mitya57** [sphinx-doc/sphinx#9962]
### Describe the bug

Sphinx uses `@definfoenclose` command here:
https://github.com/sphinx-doc/sphinx/blob/20732a3665e1768958e874e54ff77a1a5bca2976/sphinx/writers/texinfo.py#L63-L64

However the [texinfo documentation](https://www.gnu.org/software/texinfo/manual/texinfo/html_node/_0040definfoenclose.html) says:
> In practice, there is little use for this command, and we do not recommend you use it. Support for `@definfoenclose` may be removed in future releases of Texinfo.

And Texinfo prints these warnings when building documentation:

    sphinx.texi:18: warning: @definfoenclose is obsolete.
    sphinx.texi:19: warning: @definfoenclose is obsolete.

### How to Reproduce

```bash
$ git clone https://github.com/sphinx-doc/sphinx.git
$ cd sphinx
$ pip install .
$ python ./sphinx/cmd/build.py -b texinfo doc doc/_build/texinfo
$ make -C doc/_build/texinfo info
make: Entering directory '/home/dmitry/upstream/sphinx/_build/texinfo'
makeinfo --no-split -o 'sphinx.info' 'sphinx.texi'
sphinx.texi:18: warning: @definfoenclose is obsolete.
sphinx.texi:19: warning: @definfoenclose is obsolete.
...
```

### Your project

Reproducible with Sphinx itself

### OS

Linux

### Python version

3.10

### Sphinx version

4.3

**Comment by tk0miya** [comment]
Thank you for your reporting.

Note: I found our docs introcuces a way to customize the style of emphasized texts. So we need to drop the command usage at v5.0.
https://www.sphinx-doc.org/en/master/faq.html#notes
