### ISSUE TITLE
Allow a variable part in ..option directives

### ISSUE THREAD

**Issue by marxin** [sphinx-doc/sphinx#9965]
### Describe the bug

When I refer to options, I commonly use
```rst
:option:`-foo`:samp:`={style}`
```

where `style` is a variable part as defined here:
https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html?highlight=samp#role-samp

I would also appreciate that support in `option` directive:

```rst
.. option:: -foo={style}
```

so that the `style` option uses italic font in an output format.
@jakobandersen: What do you think?

### How to Reproduce

Build the snippet.

### Your project

Build the snippet

### OS

Linux

### Python version

3.8

### Sphinx version

4.3.0

**Comment by tk0miya** [comment]
+1: Reasonable. I'm not sure treating `={...}` syntax is a best solution. But it's cool to notate the value of the option.

**Comment by marxin** [comment]
Good. What about supporting a normal `:samp:` directive?

**Comment by tk0miya** [comment]
I think supporting nested notation will make a new Goldberg machine. So -1 for the idea.

FYI: A "directive" is a block level element written by `.. directive-name::`. `:samp:` is not a directive. It's an inline element called "role".

**Comment by marxin** [comment]
> It's an inline element called "role".

Oh yeah, I wanted to say `role`. Does the same apply also the nested role in a directive?

**Comment by jakobandersen** [comment]
> Oh yeah, I wanted to say `role`. Does the same apply also the nested role in a directive?

The argument of a directive is interpreted directly by the directive implementation. E.g., the ``cpp`` directives are parsed in the C++ domain and the ``py`` directives in the Python domain.
Each directive implementation then emits docutils nodes in whichever way makes sense in that context.
The ``option`` directive parses its argument via the code in https://github.com/sphinx-doc/sphinx/blob/40db5694faf8d74d34675a686960ca76d984042b/sphinx/domains/std.py#L184
So I would say it is not a good idea to directly support a role inside the directive argument, but rather we should figure out if there is special syntax that should be recognized such that different docutils nodes could be emitted. As @tk0miya indicates, one could for example find occurrences of ``{someIdentifier}`` and emit the identifier inside an emphasis node, or whatever mimics what the ``samp`` role does. But we can invent whatever syntax.

**Comment by marxin** [comment]
Thank you for the hint. I was able to come up to the following patch:

```patch
diff --git a/sphinx/domains/std.py b/sphinx/domains/std.py
index 7660f84c9..ada65f4bc 100644
--- a/sphinx/domains/std.py
+++ b/sphinx/domains/std.py
@@ -203,7 +203,18 @@ class Cmdoption(ObjectDescription[str]):
             if count:
                 signode += addnodes.desc_addname(', ', ', ')
             signode += addnodes.desc_name(optname, optname)
-            signode += addnodes.desc_addname(args, args)
+            if '{{' in args and '}}' in args:
+                start = args.find('{{')
+                end = args.find('}}')
+                before = args[:start]
+                after = args[end + 2:]
+                variable = args[start + 2:end]
+
+                signode += addnodes.desc_addname(before, before)
+                signode += nodes.literal('', '', nodes.emphasis(variable, variable))
+                signode += addnodes.desc_addname(after, after)
+            else:
+                signode += addnodes.desc_addname(args, args)
             if not count:
                 firstname = optname
                 signode['allnames'] = [optname]
```

That does for:

```rst
.. option:: -mcpu={{TYPE}}, -m={{TYPE}}

   Best option ever.

.. option:: -mcpu2=foo|bar

  Normal option2.

.. option:: -mcpu3={}

  Normal option3. Test :samp:`{samp}` and ``emph``.
```

The following output:
![Screenshot from 2021-12-20 16-47-46](https://user-images.githubusercontent.com/2658545/146794749-df3d05c6-ac80-43d6-b936-d770edcde5c5.png)

![Screenshot from 2021-12-20 16-48-11](https://user-images.githubusercontent.com/2658545/146794763-e8fc2af0-1b02-4fa0-a2ee-2a5820e5a85c.png)

What do you think about the syntax? I can create a proper pull request then.

**Comment by tk0miya** [comment]
I think using `{value}` is better than `{{value}}` as you proposed because curly brackets has already been used in `:samp:` role. On the other hand, I'm not sure nobody uses `{...}` for the option name. So this behavior should be disabled via configuration.

Addition to this, it's better to able to refer `-mcpu={TYPE}` option via ```:option:`-mcpu` ``` (without value). So let's remove value part from an index entry.
