### ISSUE TITLE
Using position-only parameter syntax in `__init__` prevents docstrings for attributes from being parsed

### ISSUE THREAD

**Issue by bryanforbes** [sphinx-doc/sphinx#9968]
### Describe the bug

I'm currently using [position-only parameters](https://www.python.org/dev/peps/pep-0570/) in most of my functions, including `__init__`, however this prevents inline, before, and after doc strings from being parsed.

### How to Reproduce

```
$ git clone https://github.com/bryanforbes/sphinx-positional-only-issue
$ cd sphinx-positional-only-issue
$ pip install -r requirements.txt
$ cd docs
$ make html
$ open _build/html/index.html
```

Once `index.html` is open, you will see that only `test.WithoutPositional` has the `a` property documented.

### Expected behavior

Both classes should have the `a` property documented

### Your project

https://github.com/bryanforbes/sphinx-positional-only-issue

### Screenshots

<img width="636" alt="image" src="https://user-images.githubusercontent.com/204106/145874239-8fca2943-1321-4098-b0d9-7c2ca81e1e18.png">

### OS

macOS 11.6.1

### Python version

3.10

### Sphinx version

4.3.1

### Sphinx extensions

sphinx.ext.autodoc, sphinx.ext.napoleon

**Comment by tk0miya** [comment]
Thank you for reporting. The posonlyargs confuses our parser. Will be fixed via #9987.
