### ISSUE TITLE
AttributeError: 'Sphinx' object has no attribute 'add_javascript'

### ISSUE THREAD

**Issue by StephaneBereux** [sphinx-doc/sphinx#9975]
### Describe the bug

While trying to compile the doc from [sklearn-template](https://sklearn-template.readthedocs.io/en/latest/quick_start.html) with `make html`, Sphink throws the error :

`# Sphinx version: 4.2.0`
`# Python version: 3.8.10 (CPython)`
`# Docutils version: 0.17.1 release`
`# Jinja2 version: 3.0.1`
`# Last messages:`

`# Loaded extensions:`
`Traceback (most recent call last):`
  `File "/home/sbereux/.local/lib/python3.8/site-packages/sphinx/cmd/build.py", line 276, in build_main`
    `app = Sphinx(args.sourcedir, args.confdir, args.outputdir,`
  `File "/home/sbereux/.local/lib/python3.8/site-packages/sphinx/application.py", line 251, in __init__`
    `self.config.setup(self)`
`File "/home/sbereux/multidataset-lowrank-models/doc/conf.py", line 320, in setup`
    `app.add_javascript('js/copybutton.js')`
`AttributeError: 'Sphinx' object has no attribute 'add_javascript'`

### How to Reproduce

```
$ git clone https://github.com/scikit-learn-contrib/project-template.git
$ cd project-template
$ pip install -r requirements.txt
$ cd doc
$ make html
```

### Your project

https://github.com/scikit-learn-contrib/project-template

### OS

Linux Ubuntu 20.04

### Python version

3.8.10

### Sphinx version

4.2.0

### Sphinx extensions

sphinx-gallery, sphinx_rtd_theme

**Comment by astrojuanlu** [comment]
Could you try with Sphinx 4.3?

**Comment by StephaneBereux** [comment]
Sure, I just did but it didn't solve the error :

```
# Sphinx version: 4.3.1
# Python version: 3.8.10 (CPython)
# Docutils version: 0.17.1 release
# Jinja2 version: 3.0.1
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/home/sbereux/.local/lib/python3.8/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/home/sbereux/.local/lib/python3.8/site-packages/sphinx/application.py", line 251, in __init__
    self.config.setup(self)
  File "/home/sbereux/project-template/doc/conf.py", line 320, in setup
    app.add_javascript('js/copybutton.js')
AttributeError: 'Sphinx' object has no attribute 'add_javascript'
```

**Comment by astrojuanlu** [comment]
Sorry, I got confused with another function. This function has been deprecated and removed:

> Yes, add_javascript() was deprecated in v1.8 and removed in v4.0. add_js_file() is a successor of the API.

https://github.com/sphinx-doc/sphinx/issues/9372

**Comment by StephaneBereux** [comment]
Great, thank you very much !
