### ISSUE TITLE
auto_cases gives error

### ISSUE THREAD

**Issue by bbognar1992** [sphinx-doc/sphinx#9976]
### Describe the bug

After building the html with sphinx, I got the following error

Exception occurred:
  File "/home/bence/PycharmProjects/data-processing-core/venv/lib/python3.9/site-packages/sphinxcontrib/test_reports/directives/test_case.py", line 109, in run
    if len(case["system-out"]) > 0:

### How to Reproduce

my junit styled xml file:
```
<testsuite name="nose2-junit" errors="1" failures="0" skipped="0" tests="4" time="7.294">
  <testcase time="0.054618" classname="tests.test_MappingExecutor.TestMappingExecutor" name="test_mapping_query">
    <system-out />
  </testcase>
  <testcase time="0.107565" classname="tests.test_AccelerometerProcess.TestAccelerometerProcess" name="test_run_with_empty_source_tables">
    <system-out />
  </testcase>
  <testcase time="7.129966" classname="tests.test_AccelerometerProcess.TestAccelerometerProcess" name="test_run_with_filled_source_tables">
    <system-out />
  </testcase>
</testsuite>

```

The following example not works:
```
.. test-file:: Nosetests Test File
   :id: NOSE01
   :tags: nose, example
   :file: ../tests/data/nose_data.xml
   :auto_suites:
   :auto_cases:
```

### Expected behavior

I would expect to see Test-Suite and Test-Case blocks in the html file.

### Your project

sorry it is not possible

### OS

Ubuntu

### Python version

3.9

### Sphinx version

4.3.1

### Sphinx extensions

'sphinx.ext.duration',     'sphinx.ext.doctest',     'sphinx.ext.autodoc',     'sphinx.ext.autosummary',     'sphinxcontrib.needs',     'sphinxcontrib.test_reports',     'sphinxcontrib.plantuml'

**Comment by tk0miya** [comment]
It seems the error was raised inside sphinx-test-reports extension. How about reporting this into https://github.com/useblocks/sphinx-test-reports instead?

Thanks,

**Comment by bbognar1992** [comment]
yes, sorry.
