### ISSUE TITLE
Different build warnings are colored differently

### ISSUE THREAD

**Issue by aofarrel** [sphinx-doc/sphinx#9979]
### Describe the bug

Some types of warnings seem to be different colors than others. An image warning is light red, a transition warning is dark red. This behavior exists regardless of `-W --keep-going` being set.

### How to Reproduce

```
$ git clone https://github.com/dockstore/dockstore-documentation.git
$ cd dockstore-documentation
$ git checkout make-html-warnings
$ pip install -r requirements.txt
$ cd docs
$ make html
```
Use the branch specified. I purposely broke an image's path to showcase the differently-colored warning so it's not on main or develop.

### Expected behavior

Based on [this](https://github.com/sphinx-doc/sphinx/blob/9e1b4a8f1678e26670d34765e74edf3a3be3c62c/doc/extdev/logging.rst), I'd expect all warnings to have the same color, and to not match the color of errors.

### Your project

https://github.com/dockstore/dockstore-documentation/tree/make-html-warnings

### Screenshots

![Screenshot 2021-12-15 at 1 06 31 PM](https://user-images.githubusercontent.com/27784612/146270640-ce30f40c-d49a-4ce7-9625-8e61e97e582b.png)

### OS

macOS 10.15.7 (Catalina)

### Python version

3.7

### Sphinx version

Sphinx v4.1.2

**Comment by tk0miya** [comment]
Oops. The labels of dark red messages are wrong. They should be "ERROR:" instead of "WARNING:". This must be a bug. Thank you for reporting.

**Comment by aofarrel** [comment]
When building this, the build will be reported as a success (assuming you don't set `-W`). Is a build success vs a build failure determined from the labeling? Asking because if so, we have had an error slip through our CI for quite some time now and will want to investigate that.

**Comment by tk0miya** [comment]
This error was raised from docutils; a framework library for document parsing and conversion. Sphinx does not exit (or crash) even if docutils raises an error. So it does not prevent building document if you don't set `-W` option. It's almost same as a warning. So I guess it's not related to your CI error.

**Comment by aofarrel** [comment]
Thank you for the clarification, it's much appreciated.
