### ISSUE TITLE
Latex: some internal document option references lead to Intersphinx HTML links

### ISSUE THREAD

**Issue by marxin** [sphinx-doc/sphinx#9984]
### Describe the bug

While working on GCC documentation migration to Sphinx, I noticed some internal links lead
to HTML links, and not the PDF document itself:

![Screenshot from 2021-12-17 11-43-14](https://user-images.githubusercontent.com/2658545/146532681-8e340fe5-ce72-4c2e-bc79-7e1b8e3058ea.png)

while Index links are fine:

![Screenshot from 2021-12-17 11-44-46](https://user-images.githubusercontent.com/2658545/146532852-0547d1f8-7062-47d9-8480-f276051c28fe.png)

@jakobandersen @jfbu 

### How to Reproduce

```
$ git clone git@github.com:marxin/texi2rst-generated.git
$ cd texi2rst-generated/sphinx/gcc
$ make latexpdf
```

### Your project

git@github.com:marxin/texi2rst-generated.git

### OS

Linux

### Python version

3.8

### Sphinx version

4.3.0

**Comment by jfbu** [comment]
```diff
index c87ac7ed..17e9c276 100644
--- a/sphinx/gcc/gcc-command-options/options-controlling-c-dialect.rst
+++ b/sphinx/gcc/gcc-command-options/options-controlling-c-dialect.rst
@@ -3,6 +3,8 @@
   This is part of the GCC manual.
   For copying conditions, see the GPL license file
 
+.. program:: gcc
+
 .. _c-dialect-options:
 
 Options Controlling C Dialect
```
appears to fix this for the links to the options as described in `options-controlling-c-dialect.rst`.

**Comment by marxin** [comment]
Ah, my bad, thank you very much!

**Comment by tk0miya** [comment]
In `gcc-command-options/option-summary.rst`, `.. program:: gcc` is declared at first. So ```:option:`-ansi` ``` searches a `-ansi` option for `gcc` command.

On the other hand, in `gcc-command-options/options-controlling-c-dialect.rst`, the `-ansi` option is defined without `.. program:: gcc`. So it's defined as a `-ansi` option without any command.

Therefore, the reference in gcc-command-options/option-summary.rst does not match to the entry in gcc-command-options/options-controlling-c-dialect.rst, and intersphinx automatically fallbacks to find the option to the external document.

As jfbu said, please add `.. program:: gcc` before reference.

**Comment by tk0miya** [comment]
It would be helpful in the next time if you gives us a pointer for the problem on the document. I needed to read your document to find the location where problem happens.

**Comment by marxin** [comment]
> It would be helpful in the next time if you gives us a pointer for the problem on the document. I needed to read your document to find the location where problem happens.

Sure, will do that next time. Thank you for your time and investigation!
