### ISSUE TITLE
Sphinx: In-line cross referencing target should not need explicit title

### ISSUE THREAD

**Issue by psunthar** [sphinx-doc/sphinx#9993]
**Is your feature request related to a problem? Please describe.**
Yes, in-line targets such as  `` _`this one` `` cannot be easily referred using role based `:ref:` cross-referencing, which is needed across RST files of the same document.  It needs an explicit title.  For example, ``:ref:`this one` `` does not insert the target text as the title.  It needs an explicit tltle like this `` :ref:`That one<this one>` ``.  Without explicit link, there is a warning 
```
WARNING: Failed to create a cross reference. A title or caption not found: this one
```

**Describe the solution you'd like**
``:ref:`this one` `` must insert the text `this one` and also link it to the target.  This will avoid duplicate typing of the same text, when avoidable.

**Describe alternatives you've considered**
Duplicating the target text as the title. `` :ref:`this one<this one>` ``

**Comment by tk0miya** [comment]
+1: Good idea. Reasonable!

**Comment by tk0miya** [comment]
Unfortunately, this change brings an incompatible change to Sphinx. So I determined to revert this feature during 4.x.
Sorry for the inconvinience.

**Comment by tk0miya** [comment]
refs: https://github.com/sphinx-doc/sphinx/issues/10177
