### ISSUE TITLE
Add optionlisting directive

### ISSUE THREAD

**Issue by marxin** [sphinx-doc/sphinx#9995]
Please support a new `optionlisting` directive:

```rst
..optionlisting:

  :option:`-fdiagnostics-plain-output`
  :option:`-fdiagnostics-show-location`:samp:`=[once|every-line]`
  :option:`-fdiagnostics-color`:samp:`=[auto|never|always]`
```

That would emit `|gol|` at the end of each line? Instead of manually placing the `|gol|` at the end of every line.

Originally reported in #9925.

**Comment by jakobandersen** [comment]
Do you mean this for declare multiple options a la the normal option directive (``.. option::``) but with a common description?
You can already now do
```rst
.. option:: -fdiagnostics-plain-output
            -fdiagnostics-show-location=[once|every-line]
            -fdiagnostics-color=[auto|never|always]

   Diagnostics options.
```

**Comment by marxin** [comment]
> Do you mean this for declare multiple options a la the normal option directive (`.. option::`) but with a common description?

No, it's about using `option` role for a listing of already defined options. Something like:

Enable with `-O2` optimization level:

```rst
..optionlisting:

  :option:`-fdiagnostics-plain-output`
  :option:`-fdiagnostics-show-location`:samp:`=[once|every-line]`
  :option:`-fdiagnostics-color`:samp:`=[auto|never|always]`
```

**Comment by jakobandersen** [comment]
Would it be possible to use a normal list?

**Comment by marxin** [comment]
Well, I don't want to emit the bullet points at the beginning of a line.

**Comment by jakobandersen** [comment]
Right. Then perhaps a line block might be useful:
```rst
| :option:`-fdiagnostics-plain-output`
| :option:`-fdiagnostics-show-location`:samp:`=[once|every-line]`
| :option:`-fdiagnostics-color`:samp:`=[auto|never|always]`
```

**Comment by marxin** [comment]
Kudos! It works perfectly well.

**Comment by marxin** [comment]
However, a small difference is the vertical spacing:

![Screenshot from 2021-12-20 17-14-55](https://user-images.githubusercontent.com/2658545/146798476-8cf30f8a-37b9-4c97-866e-ebd228efb15f.png)

for
```rst
  Normal option3. Test :samp:`{samp}` and ``emph``.

  | :option:`-fdiagnostics-plain-output`
  | :option:`-fdiagnostics-show-location`:samp:`=[once|every-line]`
  | :option:`-fdiagnostics-color`:samp:`=[auto|never|always]`

Using GOL:

  :option:`-fdiagnostics-plain-output` |gol|
  :option:`-fdiagnostics-show-location`:samp:`=[once|every-line]` |gol|
  :option:`-fdiagnostics-color`:samp:`=[auto|never|always]` |gol|
```

```
rst_prolog = r'''
.. |gol| raw:: latex

               \\
'''
```
