### ISSUE TITLE
Can not use "ähnlich" as a glossary term (but "über" works)

### ISSUE THREAD

**Issue by jfbu** [sphinx-doc/sphinx#9996]
### Describe the bug

```
index.rst:12: WARNING: term not in glossary: ähnlich
```

### How to Reproduce

Use this as `index.rst` and then `make html`

```
Welcome to FOO's documentation!
===============================

test-glossary
=============

We use :term:`boson`, :term:`fermion`, :term:`tauon`, :term:`über` and :term:`ähnlich`.

.. glossary::
   :sorted:

   boson
      Particle with integer spin.

   *fermion*
      Particle with half-integer spin.

   tauon
   myon
   electron
      Examples for fermions.

   über
      Gewisse

   änhlich
      Dinge
```

### Expected behavior

no warning and output contains link to term definition

### Your project

See code snippet

### Screenshots

![Capture d’écran 2021-12-20 à 11 48 45](https://user-images.githubusercontent.com/2589111/146755585-507a4b0d-f7a6-43b7-a3a0-84882316ae9a.png)

### OS

Mac

### Python version

3.8.0 (CPython)

### Sphinx version

4.3.2

### Additional context

If testing this for `make latexpdf` please add `latex_use_xindy = True` to `conf.py` or use `xelatex` or `lualatex`.

**Comment by john-hen** [comment]
This is due to a typo: "änhlich" instead of "ähnlich".

**Comment by jfbu** [comment]
@john-hen oh my... good catch thanks! how embarrassing... my bad!
